### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by miclnl** [mailcow/mailcow-dockerized#1]
Hey @andryyy 

Nice to see you working on a Docker version!
Just a few questions as I'm not that familiar with Docker;

* I saw you aren't using a data container for the website nor the ssl-certs, is there a reason for this?
(https://github.com/miclnl/mailcow-dockerized/commit/4b2f522aceee9d5a6771ea34c7ac9b54c0762ef6)
* Would you object to adding the certbot image to also integrate Let's Encrypt in the image?
* Is it possible to add Fail2ban to the docker image, with the docker networking and all?

Regards, Michel

**Comment by andryyy** [comment]
Hi! I'm still working on the web files and was too lazy to push them in a container/data container/volume.
I'm totally thinking about integrating LE, but I'm not sure about "how". I can write a script to auto-request the certs if a env var is set or something. 
Fail2ban will be hard. It needs to read the log files from the containers. You can try to use the syslog driver and install f2b locally.

**Comment by miclnl** [comment]
Hey,

Guess I was too quick ;)  
[This blog](https://dantehranian.wordpress.com/2015/03/25/how-should-i-get-application-configuration-into-my-docker-containers/) writes about this problem I think. Would option 3 be easiest implementable?

**Comment by andryyy** [comment]
Hi, no, we don't just need the config files (which is no problem), but access to the logs of each application we want to monitor. Fail2ban needs to parse these logs and then ban accordingly. The best approach is running it on the host and use the syslog driver for Docker. Or give the docker socket to a f2b container and parse the logs from here. But again we need to call back the host and tell "him" to ban the ip. 
Running this in a swarm hurts, I guess. :-)

**Comment by miclnl** [comment]
Hi, The configuration was meant for your LE remark.
As I'm reading the code now, it appears that you're putting the configuration in the ENVIRONMENT. But this would require all the users to build the image themselves or use command line arguments at start, right? Wouldn't it be easier to make a dedicated, persistent, config-volume and mount it on every container at `/var/mailcow` for example? (or go sql-config only with a bash parser)

Fail2ban seems very complicated indeed :( Seems like there isn't much prior work on this either. Looking at this package, [the SSHGuard docker package](https://github.com/pablocouto/coreos-sshguard) however (sshguard might also be easier to implement), it looks like they're also doing the blocking on the host. Wouldn't this be an option as well?

Again, I'm still reading up on Docker; never needed it before, but seems quite interesting  :)
edit: You should check [this ](https://github.com/phusion/baseimage-docker)out as well, using a baseimage instead of ubuntu and [this guy's ideas](https://github.com/jprjr/docker-ubuntu-stack)

**Comment by andryyy** [comment]
Oh, sorry. :-) We can create a one-shot container that tries to obtain/renew a certificate. We could check if the given cert is self-signed or trusted. If it is trusted, covers all names and is still good for n days, we skip the process. That way we prevent it from overwriting valid certificates that are not issued by LE.

phusion/ubuntu: `By running multiple processes, we solve very real Unix OS-level problems, with minimal overhead and without turning the container into multiple logical services.`. That's what you don't want in Docker: multiple services in a single container. They also implement stuff I don't want to rely on.
If one doesn't want SSHd, Crond etc. running by default, then they shouldn't use Docker. :-)

But anyway, I am thinking about rebasing all containers to the same image to save space. We should also implement some clean-up routines in the Dockerfile.

**Comment by miclnl** [comment]
Hey, Yeah phusion does that.. kinda strange and not really fitting into the Docker philosophy.. 
I think it's a great idea to rebase them! I saw that a lot of images try to use [Alpine](https://alpinelinux.org/), which defines itself as a small & secure distro. I guess this would be used for many of mailcow's services as well: https://wiki.alpinelinux.org/wiki/Hosting_Web/Email_services_on_Alpine  :)

Also I'm not sure if you need to define the networking in the compose file: https://docs.docker.com/compose/networking/ It creates a private network by default with resolvable names per container, based on the service-name [even without a DNS-server](https://jpetazzo.github.io/orchestration-workshop/#22) or a predefined network range.

**Comment by andryyy** [comment]
I know it does. I need a fixed range with a static ip, that's why I do it. :-) No need for it if we drop the DNS recursor, but I feel better keeping it. 

The alpine packages are really up to date! I will check it out tomorrow. The smaller size is also very useful.

**Comment by Braintelligence** [comment]
Hi @andryyy, sorry for derailing this issue but I wanted to ask if mailcow-dockerized is ready for production in your opinion 😸.
I'd like to switch from Virtualmin-managed mailing-stuff to mailcow 😺.
