### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by fabreg** [mailcow/mailcow-dockerized#100]
ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (dfca223c4c914f2abc412e71e2069624d8c23ed43ef31013dbd6bdd2cf50d910): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by fabreg** [comment]
This problem is related to the exim4 already installed (it comes by default on all Debian images)
You can fix the problem with

**apt-get remove --purge exim4-base exim4-config exim4-daemon-light exim4**

**Comment by PhoenixPeca** [comment]
Hi, Just to be easy, you can execute it like this: `apt-get purge exim4*`
😄
