### ISSUE TITLE
Docker Containers Keep filling 100% of Disk

### ISSUE THREAD

**Issue by nickian** [mailcow/mailcow-dockerized#1000]
I had mailcow on a 40GB server. Then the disk reached 100%, so I updated it to an 80GB server. A few days later I'm at 100% somehow.

My `/var/lib/docker/conatiners` is taking up 76GB. When I look through the subfolders I'm finding gigantic json.log files. This one is 50GB:

 `/var/lib/docker/containers/cd869d2bfadada0b3609e336a994d8be8dc2e6bab9d5141d869f38f5f985/ cd869d2bfadada0b3609e336a994d8be8dc2e6bab9d5141d869f38f5f985202d-json.log`

I deleted this file and rebooted the server, which seemed to fix it. But Is there a way to prevent this? I think it's just going to happen again. I'm not familiar enough with Docker to understand what is going on here. Thanks!

**Comment by andryyy** [comment]
The container name would be very helpful. 

How old is your installation? Last update?

**Comment by nickian** [comment]
How can I determine the container name based on looking in `/var/docker/containers`? The folder names are just random strings. 

The `docker-compose.yml` file says `image: mailcow/unbound:1.0` Is this the version? I think I created it in October of last year.

**Comment by andryyy** [comment]
You can determine the id by running “docker ps”.

**Comment by nickian** [comment]
Oh ok, I didn't realize that the ID was the first serveral characters of those long folder names. It's hard to tell which one is causing the problem now that I've already deleted the giant JSON files. I may have to let some time pass to let it build up again.

This is what it looks like now (number on the left is the directory size in bytes):

```
28 (robbertkl/ipv6nat)	2ddfca69692ab77468f8c48dd7934b7ce117e3b7e3ca5147828c21c69973ffda
36 (memcached:alpine)	b01a6507433c84a24bc0e1ec7ccd53378f31d60159a60bbee7862eb53b3f03d0
68 (mailcow/unbound:1.0) 5807e2d59921624f51b9a5e88ccdf5f9ccf3286e3356ac7a09cef0ca1f511ce8
88 (mailcow/fail2ban:1.6)	8b23bf151e56d7a6637dec7a20156386837a0ef52f9dfba04212e85b5c81d685
164 (mariadb:10.2)	ca76ba718098180096a8acf68e7a48487be2c78ffcaa8de53100e52eecc33cd2
672	(mailcow/phpfpm:1.1) 2a39e249a1ccb0fb5fd7c2d9934a1bf73b5a04fedfc047452b65e9e17a5d93aa
1108 (nginx:mainline-alpine)	3b3901778985bf249f5f4e59d3e4d7617b76fcdef3242f05a8c22e3d3a8a8f1c
3784 (mailcow/clamd:1.3)	3567604d006c325e542bfbd10af1b2de27702f3f73b5677aa9c56f4a6606faa8
3864 (mailcow/acme:1.17)	1968e73b67801dcb7f7855df09903486e2dc2804633eda311d98b63d018cbad9
6108 (redis:alpine)	15e01ac019d241ceb7040429dff5d67bf88a7bc51a42ce991690da6889489afe
6680 (mailcow/rspamd:1.8)	cd869d2bfadada0b3609e336a994d8be8dc2e6bab9d5141d869f38f5f985202d
38740 (mailcow/postfix:1.4)	5015ec343eba23c37dbdb762ac1a08d23c1611b7f6fab3ed05e261ff5ff1a5a0
156164	(mailcow/dovecot:1.8) c35efe757767f63c71eaf1cd4274adc02c6fa6c39d36b59a312721c0bb88a056
164596 (mailcow/sogo:1.8)	e2f0c799c5b2d47efdd8def9db1007da5437f5f76d18733dc12930e49d593177
```

**Comment by nickian** [comment]
When I look at my previous commands, it looked like the two largest ones I deleted were for nginx/mainline and and mailcow/phpfpm.

Is there a way to prevent log files from getting so large with docker?

**Comment by lazyfrosch** [comment]
You can limit the default log size of containers:

```
cat /etc/docker/daemon.json 
{
   "log-opts" : {
      "max-file" : "10",
      "max-size" : "10m"
   },
   "log-driver" : "json-file"
}
```

**Comment by nickian** [comment]
`/etc/docker/daemon.json` didn't exist in that directory on my server. Assuming it will work if I create the file? Thanks.

**Comment by andryyy** [comment]
Yes

Restart dockerd after adding these lines.

**Comment by nickian** [comment]
Thanks!
