### ISSUE TITLE
Dovecot imap-login aborted from 172.22.1.9

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1001]
Hello,

after updating to the current master my dovecot logs are spammed with the following lines.

```
4.2.2018, 13:08:04 | info | managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13
-- | -- | --
4.2.2018, 13:08:04 | info | imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13
4.2.2018, 13:08:04 | info | imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13, TLS: Disconnected, TLSv1.2 with cipher DHE-RSA-CAMELLIA256-SHA256 (256/256 bits)
4.2.2018, 13:08:04 | info | lmtp(57): Disconnect from 172.22.1.9: Successful quit
4.2.2018, 13:08:04 | info | lmtp(57): Connect from 172.22.1.9
4.2.2018, 13:07:37 | info | managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13
4.2.2018, 13:07:37 | info | imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13
4.2.2018, 13:07:37 | info | imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.13, TLS: Disconnected, TLSv1.2 with cipher DHE-RSA-CAMELLIA256-SHA256 (256/256 bits)
4.2.2018, 13:07:37 | info | lmtp(57): Disconnect from 172.22.1.9: Successful quit
4.2.2018, 13:07:37 | info | lmtp(57): Connect from 172.22.1.9
```

What does that mean exactly? Which container is 172.22.1.9?

**Comment by MAGICCC** [comment]
Use following command to get all IPs
```docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)```
Then you can narrow it down

**Comment by andryyy** [comment]
It’s the watchdog. We should hide it from syslog. :-)

**Comment by phipag** [comment]
Thank you, so this is nothing i have to worry about? :-)

**Comment by andryyy** [comment]
No, not a problem at all. :-)

**Comment by phipag** [comment]
Do you still have in mind to hide it from log? Because it is a little bit annoying to read the logs like that :-)

**Comment by alankessler** [comment]
It would be nice if this got fixed.

**Comment by RobMeerwijk** [comment]
> 

I agree, it took me quite some time to figure out that these log lines were no issue in the end. I was initially a bit worried by this unrelated issue https://github.com/mailcow/mailcow-dockerized/issues/2159 that suggested that I had a open relay config, which was clearly not the case.

**Comment by gpz1100** [comment]
@andryyy 

Has any progress been made on this issue?

It appears watchdog is generate multiple log lines every minute in dovecot, obfuscating any meaningful (error) dovecot log entries.

**Comment by quentingosset** [comment]
Hello everyone,
If I understand correctly, there's nothing wrong with my log? 
it's just watchdog spamming the dovecot every minute, isn't it?
![image](https://github.com/mailcow/mailcow-dockerized/assets/6824137/325379dd-639e-4e84-ab0b-70f1089af1db)

@andryyy it's still on your roadmap ? 

> It’s the watchdog. We should hide it from syslog. :-)
> […](#)
> Am 04.02.2018 um 13:26 schrieb Peter ***@***.***>: Use following command to get all IPs docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) Then you can narrow it down — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks


Ps : for people who need the new command to find the ip dedicated to the container 
`sudo docker container inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(sudo docker ps -aq)`

**Comment by C0NZZ** [comment]
Is this still on anyone's watch? Is it supposed to get fixed?

**Comment by schoebelh** [comment]
For me crowdsec also begins to complain about these connections since last update.
