### ISSUE TITLE
Docker-Compose v3

### ISSUE THREAD

**Issue by stevenklar** [mailcow/mailcow-dockerized#1004]
Hey *,

after searching for some time I couldn't find a request for docker-compose v3.

Are there any plans on supporting docker swarm / docker-compose v3 yet?
Would be happy to use mailcow but docker-compose v2 is really nothing I want to downgrade to.

Regards

**Comment by kb1ibt** [comment]
Some of the included services are not compatible with swarm mode, specifically [robbertkl/ipv6nat](https://github.com/robbertkl/docker-ipv6nat).

**Comment by stevenklar** [comment]
Well. I experienced that already when try to convert v2 to compatible v3 which resulted in ipv6nat and rspamd (nginx also because of rspamd) failing to run.

Rephrased: Are there any plans on replacing or upgrading the uncompatible services?

**Comment by mkuron** [comment]
> after searching for some time I couldn't find a request for docker-compose v3.

Related to #619. We decided to keep the compose file at version 2 for compatibility with some older (but still officially supported) Docker versions. Newer compose versions support older file versions just fine though, so you can upgrade Docker Compose.

> Are there any plans on supporting docker swarm

See #669 and #479. We'd like to be Swarm-compatible, but currently aren't. ipv6nat and all the dockerapi-related stuff are the main problem. The former will be obsolete once Docker supports IPv6 NAT by itself (https://github.com/docker/libnetwork/pull/2023) and the latter may require pinning the dockerapi container to the swarm master or something.
