### ISSUE TITLE
Getmail (permanent retrieval of the INBOX with IMAP Idle)

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#1005]
I have previously used Getmail for multiple mailboxes to monitor the INBOX permanetne with IMAP IDEL (Push) for new emails, these were then delivered via Dovecot (/usr/lib/dovecot/deliver) to my main INBOX and then distributed via Sieve into subfolders.
Is this possible with mailcow?

I know mailcow uses imapsync (sync jobs), but this is (in my opinion) rather for the one-time migration of all IMAP folders and not for permanent syncing the INBOX via push.

Getmail Example configuration: deliver to dovecot
http://www.stefan-seelmann.de/wiki/getmail

**Comment by christianbur** [comment]
So I integrated getmail, but it was my first attempts with Docker and unfortunately I can not build a GUI either. However, it would be nice to include this in the official release

With the integration, you can syncronize any number of IMAP accounts using IMAP IDLE (via push). As soon as a new message arrives in the INBOX of the monitored mailbox, getmail picks it up and delivers it to Dovecot via LDA, the message goes through the Sieve rules and is then stored in the Maildir.

Changes  in mailcow-dockerized/data/Dockerfiles/dovecot/     **(remove .txt)**
[Dockerfile.txt](https://github.com/mailcow/mailcow-dockerized/files/1708935/Dockerfile.txt)
    - only add "getmail4"
[supervisord.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/1708937/supervisord.conf.txt)
    - add include folder

Changes  in mailcow-dockerized/data/conf/dovecot    **(remove .txt)**
[extra.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/1708770/extra.conf.txt)

Add Folder mailcow-dockerized/data/conf/dovecot/supervisor.d and add supervisor-config-file for each mailbox 
[getmail1.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/1708943/getmail1.conf.txt)

For each supervisor-config-file, a getmail-config-file must also be created under ../docker/volumes/mailcowdockerized_vmail-vol-1/_data/getmail/, please make sure that the new folder getmail has the correct permissions (chown 5000: 5000 ./getmail).

[mail@xxxx.de.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/1708956/mail.xxxx.de.conf.txt)


it is now possible to monitor many imap mailboxes, for each one a getmail and a supervisor.d config-file have to be created

Instead of LDA, I would have liked to use LMTP (as well as postfix, with Port 24), but unfortunately, getmail does not support this. Because then you could have created your own container for getmail.

https://github.com/christianbur/docker_projects/tree/master/getmail

**Comment by Miarka24** [comment]
We too are using getmail to deliver mail to the mailboxes in mailcow.
But I am using a different approach. Did you ever have problems with IMAP IDLE? Because I had. Getmail stopped getting mails with IMAP IDLE from time to time without any error message and without ending the process at all. I could observe this behaviour once about every week or two weeks. I allways had to restart getmail and it started working again. I am using getmail 4.46.0. 
Hmm ... I just saw version 5.6 is out mabye i should just update, there seem to be some updates concerning IMAP IDLE ;).

Best Regards
Jonas Stunkat

**Comment by christianbur** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/1554
