### ISSUE TITLE
IPV6: connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by nightah** [mailcow/mailcow-dockerized#1006]
I'm regularly seeing errors in the nginx-mailcow logs which seem to be related to ipv6 as per the below snippet:
```
nginx-mailcow_1      | 2018/02/06 03:34:16 [error] 13#13: *41482 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.1.1, server: mail.example.com, request: "POST /SOGo/Microsoft-Server-ActiveSync?User=user@example.com&DeviceId=SKMHDAGKID1I72NVQEK44VMPMO&DeviceType=iPhone&Cmd=Ping HTTP/1.0", upstream: "http://[fd4d:6169:6c63:6f77::6]:20000/SOGo/Microsoft-Server-ActiveSync?User=user@example.com&DeviceId=SKMHDAGKID1I72NVQEK44VMPMO&DeviceType=iPhone&Cmd=Ping", host: "host:9000"
```

I have no idea why the internal ipv6 address is being referenced in this request: http://[**fd4d:6169:6c63:6f77::6**]:20000/SOGo/Microsoft-Server-ActiveSync?User=user@example.com&DeviceId=SKMHDAGKID1I72NVQEK44VMPMO&DeviceType=iPhone&Cmd=Ping

Also not sure if this was an issue that has been present for quite some time or if in relation to having a RP infront of Mailcow.

**Comment by andryyy** [comment]
Do you set the x-forwarded-for headers with your rp?

**Comment by nightah** [comment]
> Do you set the x-forwarded-for headers with your rp?

Yes, I have:
```
    location / {
        proxy_pass http://host:9000/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100m;
    }
```

**Comment by andryyy** [comment]
Should be fixed
