### ISSUE TITLE
cant get certbot to obtain certs

### ISSUE THREAD

**Issue by ledodev** [mailcow/mailcow-dockerized#101]
Hi, I'm struggling with certboot to obtain multi SAN cert. I used your instructions from First Steps. 
- `wget https://dl.eff.org/certbot-auto -O /usr/local/sbin/certbot && chmod +x /usr/local/sbin/certbot`
- add `HTTP_BIND=0.0.0.0` to `mailcow.conf`
- restart nginx `docker-compose restart nginx-mailcow`
So far no problems. But when using certbot to obtain the cert, LE cant connect to verify the challenge. 

```
   Domain: autoconfig.domain.tld
   Type:   connection
   Detail: Could not connect to autoconfig.domain.tld

   Domain: mail.domain.tld
   Type:   connection
   Detail: Could not connect to mail.domain.tld

   Domain: autodiscover.domain.tld
   Type:   connection
   Detail: Could not connect to autodiscover.domain.tld
```
Certbot gives me a hint to check dns entrys. I double-checked them, they are alright. Same as [here](https://github.com/andryyy/mailcow-dockerized/issues/77).

Does someone has any further advice what prevent me from geting my cert? Thanks a lot.

**Comment by andryyy** [comment]
Port for HTTP is 80?

**Comment by ghost** [comment]
I had this problem. I changed port 8080 to 80, and it worked.

**Comment by ledodev** [comment]
Where did you change that?

EDIT: Just saw you fixed it. Thanks for that! Works like a charm.
