### ISSUE TITLE
imapsync failing for lots of folders

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized#1011]
When using imapsync with lots of folders imapsync_cron.pl fails to save the output as it is too long:

`DBD::mysql::st execute failed: Data too long for column 'returned_text' at row 1 at /usr/local/bin/imapsync_cron.pl line 102.`

This means the result isn't saved and the UI thinks the job is still running.

The migration is actually successful though and because imapsync_cron.pl doesn't check for is_running (just the timestamp) it'll reschedule it immediately (even if the time elapsed between runs hasn't occurred).

**Comment by stevesbrain** [comment]
Correct me if I'm wrong, but wouldn't this be an imapsync specific issue (and therefore a problem for their repo, rather than mailcow)?

**Comment by jhesketh** [comment]
No, it's to do with storing the result in mailcow's database. The output is captured in imapsync_cron.pl and stored in mysql. I have a fix incoming.

**Comment by stevesbrain** [comment]
Ah, no worries - I'll leave you to it :)
