### ISSUE TITLE
autodiscover dont work with "&" in name

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1013]
When I create a new mailbox, and in the Name i have a & "Me & you", than autodiscover don't fill out the settings like server and so. (Tested on ios). When I remove "&" and write "and" (i must restart mailcow/system), than autodiscover work. I have tested on Debian 9 stretch.

**Comment by D3luxee** [comment]
This behavior is reproduceable and seems logical to me.

Autodiscovery is using XML and the & symbol is a special character which needs to be escaped.

http://xml.silmaril.ie/specials.html

The autodiscover.php is very simple and does not escape those characters, it just places the data from the database in the XML response, which can't be parsed from your client with those special characters.

**I'm working on a fix and already forked.**

**Comment by andryyy** [comment]
Sorry, I added this just after reading your comment. What is your approach to fix this issue?

**Comment by D3luxee** [comment]
Basically the same but on a more central position line 123.

> $displayname = htmlspecialchars($MailboxData['name'], ENT_XML1);

Currently im stress testing $email with this mail address: "\"\\\"huehue\\\"\""@neuland.tech which is valid referring to RFC 5322 and i was able to create this mail in mailcow.

Unfortunately the mailclient on my phone dont let me press the login button using this mail

**I broke it for testing, you can create the mail address i mentioned above but its impossible to edit or delete afterwards, maybe its time for a new issue**
