### ISSUE TITLE
How to set up enrcypted mail transfer for all users system-wide

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1016]
Good evening everyone,

working with mailcow for a long time now, i now have the necessity to set up encrypted mail transfer for all users. Mailcow itself provides this as a per-user feature. How can i set encrypted mail transfer as a system-wide feature with no per-user option?

Any help is appreciated :-)

**Comment by andryyy** [comment]
Hi,
`docker-compose exec postfix-mailcow postconf -c /opt/postfix/conf -e default_transport=smtp_enforced_tls` should do the trick. :-)

**Comment by ghost** [comment]
I forgot about this post ...
This works like a charm :-)

Should smtpd_tls_security_level = may not be set to smtpd_tls_security_level = encrypt ?
If i unterstand this correctly all mail-transfers are encrypted by default an all connection which are not secured will be dropped.

Am i right?

Regards

**Comment by mkuron** [comment]
That is set on port 465 and 587 by default, which your users use to submit messages to the server. Only port 25, which is for receiving messages from other servers, has optional encryption. And only these server-to-server connections are affected by the per-user TLS enforcement
