### ISSUE TITLE
Switch to a safer password hash

### ISSUE THREAD

**Issue by klausenbusk** [mailcow/mailcow-dockerized#1019]
[A single round](https://github.com/mailcow/mailcow-dockerized/blob/55586f4cb13ff0f197f6bff4f7646c0428c9bb7f/data/web/inc/functions.inc.php#L4) of sha256 provides close to no security. Off-the-shelf hardware these days can hash [2000 millions hash/s](https://gist.github.com/epixoip/a83d38f412b4737e99bbef804a270c40).

We should switch to something safer (ex bcrypt), which both [Dovecot](https://wiki.dovecot.org/Authentication/PasswordSchemes) and [PHP](http://php.net/manual/en/function.password-hash.php) seems to support.

**Comment by andryyy** [comment]
It is salted sha256.

There were no better alternatives compatible by all used software when we started mailcow with SOGo.

May consider this now.

**Comment by klausenbusk** [comment]
> compatible by all used software

I assume that last missing piece is Postfix? Right now we use a simple SQL query (https://github.com/mailcow/mailcow-dockerized/blob/079170682c5905c56938789c2f4bab3b644c037e/data/Dockerfiles/postfix/postfix.sh#L77-L91) which won't work with bcrypt, but it should be possible to use Dovecot for the SASL auth (https://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL).

**Comment by andryyy** [comment]
SOGo

Please check the current config. We already use Dovecot as sasl provider. 

Any migration to a new cipher must not destroy current configurations.

**Comment by klausenbusk** [comment]
> We already use Dovecot as sasl provider.

Oh, correct. I'm new to all this :)

> SOGo

SOGo does not support blowfish at the momemt, and there seems to be no plan to implement it: https://sogo.nu/bugs/view.php?id=2682

> Any migration to a new cipher must not destroy current configurations.

Definitely! :)

**Comment by jkaberg** [comment]
From [Dovecot](https://wiki2.dovecot.org/Authentication/PasswordSchemes):
> MD5 based schemes:
>     PLAIN-MD5: MD5 sum of the password stored in hex.
>     LDAP-MD5: MD5 sum of the password stored in base64.
>     SMD5: Salted MD5 sum of the password stored in base64. 
> 
> SHA based schemes (also see below for libc's SHA* support):
>     SHA: SHA1 sum of the password stored in base64.
>     SSHA: Salted SHA1 sum of the password stored in base64.
>     SHA256: SHA256 sum of the password stored in base64. (v1.1 and later).
>     SSHA256: Salted SHA256 sum of the password stored in base64. (v1.2 and later).
>     SHA512: SHA512 sum of the password stored in base64. (v2.0 and later).
>     SSHA512: Salted SHA512 sum of the password stored in base64. (v2.0 and later). 
> 
> Other schemes
>     ARGON2I: ARGON2i password scheme (v2.3.0+), needs libsodium
>     ARGON2ID: ARGON2id password scheme (v2.3.0+), needs libsodium
>     PBKDF2: PKCS5 Password hashing algortihm 

From [Sogo documentation](https://sogo.nu/files/docs/SOGoInstallationGuide.html) - [source code](https://github.com/inverse-inc/sogo/blob/master/SoObjects/SOGo/NSData%2BCrypto.m#L179-L239):

> The default algorithm used for password encryption when changing passwords. Possible values are: none, plain, crypt, md5, md5-crypt, smd5, cram-md5, ldap-md5, and sha, sha256, sha512 and its ssha (e.g. ssha or ssha256) variants. Passwords can have the scheme prepended in the form {scheme}encryptedPass.
> 
> If no scheme is given, userPasswordAlgorithm is used instead. The schemes listed above follow the algorithms described in http://wiki.dovecot.org/Authentication/PasswordSchemes.
> 
> Note that cram-md5 is not actually using cram-md5 (due to the lack of challenge-response mechanism), its just saving the intermediate MD5 context as Dovecot stores in its database. 

So it seems we're stuck with ssha256 for the time being.

**Comment by phenomax** [comment]
Is this still on your todo @andryyy?

**Comment by duracell** [comment]
Just if someone else finds this and want to ask if there is anything changed yet in sogo: nope.
For reference, here is the "feature request" on the sogo bugtracker:
https://sogo.nu/bugs/view.php?id=4895

**Comment by phenomax** [comment]
@duracell Someone followed up to the feature request and created a PR to implement several password hashing algos: https://github.com/inverse-inc/sogo/pull/272
