### ISSUE TITLE
Backup solution

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1020]
What is the best way for a backup solution?

I think that I don't lost all my settings and config, I will backup daily with
./helper-scripts/backup_and_restore.sh backup all
and move it to backupstorage.

But how can I save all my maildirs to external backup storage?

**Comment by levinuss** [comment]
The helper backup script does include the mysql database, the volumes of redis, postfix, rspamd and also the vmail volume. That means that all your mails should be backed up when using the backup script. You could try to restore a backup to validate it includes your mails and to train for a serious case :)

**Comment by ghost** [comment]
Oh great. Thank you. I had think that 
 ./helper-scripts/backup_and_restore.sh backup all
is only for all my settings and not for mail
