### ISSUE TITLE
Domain Aliases only working on real mail accounts

### ISSUE THREAD

**Issue by myReaper** [mailcow/mailcow-dockerized#1021]
Hi,

it seems that Domain Aliases do not forward mails to mail address aliases of the forwarded domain.

For example:

I have the domain example.io and example.com in my mailcow-dockerized installation. example.io is an Domain Alias to example.com. I have created an real mail account for user@example.com and an alias from admin@example.com to user@example.com.

When i send an email to admin@example.com directly, the email gets delivered to user@example.com - so thats correct.

When i send an email to admin@example.io i receive an 550 Recipient address rejected: User unknown in virtual mailbox table.

So the redirect admin@example.io (Domain Alias) -> admin@example.com -> user@example.com is not working.

Best Regards
Michael

**Comment by andryyy** [comment]
Yes, that's wanted.

**Comment by myReaper** [comment]
Is it maybe possible to add an option to activate this?

Right now, I'm using 4 other tld's as alias domains for my .de domain, they should all offer the same email addresses (e.g. use the same forwarders, many of them are default forwarders, like hostmaster, webmaster, postmaster, ...)

Would it be an option to add any setting for the alias domain like "Send email also to aliases" or similiar?

**Comment by mkuron** [comment]
Duplicate of #724

**Comment by Braintelligence** [comment]
Ran into this today, had really weird errors for microsoft mailboxes. GMail correctly said something of the like "user not known" but microsoft mailboxes returned something akin "AAAA host not known". (Well it's true the mail servers only have an A record, still strange.)

**Comment by BlackVoid** [comment]
Noticed this today, would be awesome if domain aliases were also applied to aliases.

**Comment by andryyy** [comment]
No, sorry. It was deactivated after most people seemed to not want it. :-(

**Comment by michacassola** [comment]
Could something like this be achieved with Routing?

**Comment by andryyy** [comment]
No, too many changes. :(

**Comment by logicethos** [comment]
Been scratching my head over this problem for the past hour.  I wrongly assumed this would be the way it worked. :( I cant think why anyone would not want this.

**Comment by michacassola** [comment]
@logicethos Me too. It should at least be optional. It also sounded like this was implemented and then deliberately taken out @andryyy ?

**Comment by andryyy** [comment]
It's in the docs.

The behavior changed in 2017, yes. I don't have resources nor time to change this _without breaking existing setups_. I know it is easy to change in SQL, but it _will_ have side effects. A lot of side effects. Functions and behavior of direct aliases may change, the SOGo static view may have duplicates in a single column (this breaks things) and so on...

Since this is the default behavior as of today, it _will_ break installations, if it's not made optional. And I really, really don't want to maintain both ways of handling aliases in mailcow. :/ So if no one sponsors this pita-work, I don't want to work on it. :( As always my mind can change... 😄

**Comment by michacassola** [comment]
Best Workaround?

**Comment by andryyy** [comment]
Create aliases in alias domains is the easiest. Copy/auto-create them in SQL is probably next.

**Comment by michacassola** [comment]
I don't understand. Maybe my question was too short: How do we as users best work around this so we can receive emails from all domains and aliases?

Do we create extra inboxes where we forward messages to other inboxes?
Can there be a way to also send from admin@example.io (see first post)?

**Comment by andryyy** [comment]
Behavior now: Aliases are not applied on alias domains. Workaround: Create aliases in domains AND alias domains.

**Comment by michacassola** [comment]
Hm, if it is that easy, then why this thread I start wondering? 😄 
This was a big thing for me not to start using mailcow...

**Comment by andryyy** [comment]
Hehe, yes, it is not a big deal. Just annoying if you need to create all aliases in the alias domain again.

**Comment by mikl** [comment]
Wow, this should be better documented. I just lost several days worth of mails because I thought I could clean up my alias table by using domain aliases. More fool I, I guess.

**Comment by andryyy** [comment]
Hm, where did you expect to find it? It is - somewhere - in the docs. If you tell me a place where it would have helped you better, we can change it. :)

**Comment by mikl** [comment]
@andryyy maybe a short warning in the domain aliases admin table interface itself, nothing that it only applies to mailboxes, not aliases?

I naïvely assumed that a domain alias would alias everything on that domain, including address aliases. The feature seemed so obvious that I didn’t think I needed to read the docs first.

**Comment by andryyy** [comment]
Hm. I would agree to merge such a pull request. :) Or a link to the docs.
