### ISSUE TITLE
Couldn't connect to Docker

### ISSUE THREAD

**Issue by v1nyeru** [mailcow/mailcow-dockerized#1024]
Console:
root@c1267271:~/mailcow-dockerized# docker-compose pull
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Pulling postfix-mailcow (mailcow/postfix:1.13)...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

What can I do to get the Error away?
I got my Server on Debian 8 Jessie.

**Comment by klausenbusk** [comment]
Is docker running?

**Comment by Braintelligence** [comment]
You also get this error if you need to run docker-compose as root/sudo.

**Comment by v1nyeru** [comment]
How can I see if docker is started?

**Comment by klausenbusk** [comment]
> How can I see if docker is started?

`systemctl status docker`

**Comment by v1nyeru** [comment]
If I write this, this comes:

root@c1267271:~/mailcow-dockerized# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Sat 2018-02-10 19:41:16 CET; 14min ago
     Docs: https://docs.docker.com
  Process: 5172 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 5172 (code=exited, status=1/FAILURE)

Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Feb 10 19:41:16 c1267271 systemd[1]: Failed to start Docker Application Container Engine.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Unit entered failed state.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Failed with result 'exit-code'.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Feb 10 19:41:16 c1267271 systemd[1]: Stopped Docker Application Container Engine.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Start request repeated too quickly.
Feb 10 19:41:16 c1267271 systemd[1]: Failed to start Docker Application Container Engine.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Unit entered failed state.
Feb 10 19:41:16 c1267271 systemd[1]: docker.service: Failed with result 'start-limit-hit'.
root@c1267271:~/mailcow-dockerized#

**Comment by klausenbusk** [comment]
> If I write this, this comes:

So `docker` fails to start for some reason (check with `journalctl -b -u docker`). Are you sure you wanna run your own mailserver? If you aren't even sure how to check if a system service is running, debugging is gonna be hard.

**Comment by tkorves** [comment]
+1 for klausenbusk - This is not a mailcow-dockerized related issue - can be closed.
