### ISSUE TITLE
(sieve extension 'mailbox') Sieve parser error: line 1: unexpected quoted string "mailbox"

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#1027]
I am trying to make a sieve rule that creates a folder for each recipient (even if it does not exist), so if an email is sent to inexistentaddress@mydomain.com i want to `fileinto` INBOX.inexistentaddress@mydomain.com

From what I understand i need to add the extension  mailbox with `require "mailbox";` to be able to `:create` the folder if it does not exist but I can't add the "mailbox" extension and get the following error in the mailcow UI

> Sieve parser error: line 1: unexpected quoted string "mailbox"

This is what I am trying to do:
```
require ["variables", "fileinto", "mailbox"];
if address :matches "To" "*@mydomain.com"
{
    if mailboxexists "INBOX/${1}" {
      fileinto "INBOX/${1}";
    } else {
      fileinto :create "INBOX/${1}";
    }
}
```

**Comment by andryyy** [comment]
Can you confirm the fix?

**Comment by chaosbunker** [comment]
Thanks for the quick fix! My rule doesn't do what i want it to, but at least i can use the mailbox extension now :-P

**Comment by chaosbunker** [comment]
Could there be anything in mailcow preventing the rule from creating a not-yet-existing folder? Shouldn't this work and create a folder or am i missing something?

```
require ["variables", "fileinto", "envelope", "subaddress", "mailbox"];

if envelope :matches :detail "to" "*" {
  # you can prefix with INBOX/ or INBOX. if necessary
  # remove :create if you want to permit only existing mailboxes
  fileinto :create "INBOX/${1}";
}
```

**Comment by andryyy** [comment]
Looks very similar to the default sieve_after script of mailcow:

```
require "fileinto";
require "mailbox";
require "variables";
require "subaddress";
require "envelope";

if header :contains "X-Spam-Flag" "YES" {
  fileinto "Junk";
}

if allof (
  envelope :detail :matches "to" "*",
  header :contains "X-Moo-Tag" "YES"
  ) {
  set :lower :upperfirst "tag" "${1}";
  if mailboxexists "INBOX/${1}" {
    fileinto "INBOX/${1}";
  } else {
    fileinto :create "INBOX/${tag}";
  }
}
```

**Comment by chaosbunker** [comment]
Yup.

Doesn't seem to work. If I tell it to fileinto an existing folder like archive it works, but new folders are not created.

**Comment by andryyy** [comment]
It is possible for them to be created but not subscribed, have you checked that? Check the vmail directory.

**Comment by chaosbunker** [comment]
Ha! Thanks for pointing it out, I can see the folder(s) in vmail.
from how i understand it, newly created folders should be automatically subscribed to, but it does not happen. haven't figured out how to instruct it to do that (yet). Any clues?

**Comment by andryyy** [comment]
Hmmmm. Can you try settings 

```
lda_mailbox_autocreate = yes
lda_mailbox_autosubscribe = yes
``` 

in data/conf/dovecot/extra.conf ?

Oh, and restart Dovecot. :-)

**Comment by chaosbunker** [comment]
Thanks, this works :-)
