### ISSUE TITLE
rspamd history limit / configuration

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#1028]
I just noticed that the rspamd history in Debugging is caped to 200 entries (if I try to load more it tells me that there are no more rows to load).

In the rspamd web interface itself I cannot load the history at all. Here I get
`Cannot receive data from mymailserver: SyntaxError: Unexpected end of JSON input`
and when I look at the request via dev tools it's really a not valid JSON which looks like it got randomly cut.

I wouldn't mind the rspamd interface as long as the log is in the Mailcow Debugging section. However 200 lines is a little short. In my old rspamd config I have `history_rows = 8000;` in `options.inc` but either it is depreciated or ignored for some other reason meanwhile.
Is there currently a similar way to increase my rspamd log?

**Comment by apintocr** [comment]
I can confirm this too.
Not an issue for me, but would be nice to be able to change that.

**Comment by ata88** [comment]
Also just noticed this after updating...

**Comment by mritzmann** [comment]
There are already three other open issues on this topic: https://github.com/mailcow/mailcow-dockerized/issues/1116 https://github.com/mailcow/mailcow-dockerized/issues/1028 https://github.com/mailcow/mailcow-dockerized/issues/692

**Comment by apintocr** [comment]
@mritzmannn I think the 3 issues are not the same.

**Comment by tehXor** [comment]
mritzmann wrote:
> There are already three other open issues on this topic: #1116 #1028 #692

@mritzmann 
#1116 "[...]history not showing behind nginx reverse proxy" -> The topic already tells us this has nothing to do with the possibility to configure the amount of lines in the history.
#1028 -> This is this issue we are currently in Oo
#692 "rspamd sometimes does not display history" -> Again the topic already tells us this has nothing to do with configuration capabilities (if you refer to my side note, this was only relevant for the rspamd interface and I clearly stated it is irrelevant for this issue)

**Comment by Xadagain** [comment]
I have that problem too. on a clean mailcow-stack. (only mailcow.conf changed)

@tehXor I guess rspamd normal behavior is to use the loglimit(redis) from mailcow.conf. But somehow it's not applied. I think the 200 limit comes from the default limit in rspamd shown here:
`nrows = 200; # Default rows limit`
https://github.com/vstakhov/rspamd/blob/27801290025f0af9f1223f89be7f1f6bc2a42cb4/conf/modules.d/history_redis.conf

but maybe I'm wrong. did not find the code in mailcow where rspamds limit is set.

Actually i want to increase this problems priority. I use mailcow in my company and a limit of 200 are max 3 hours back in time for me. makes it hard to debug missing mails^^

**Comment by tehXor** [comment]
This issue can meanwhile be closed with an reference to rspamd documentation (which I think didn't exist yet when I started this issue ;-)): https://rspamd.com/doc/modules/history_redis.html

For mailcow add
```
nrows = 2000; # Default rows limit
```
to `redis.conf` in `local.d`.

Obviously you could also add the suggested `history_redis.conf` and mange the setting there but just be careful not to override the `servers` value from mailcow.

**Comment by PaoloVi** [comment]
Add "nrows = 20000;" in data/conf/rspamd/local.d/redis.conf seems to have no effect. I restarted rspamd-mailcow and the whole Vm too.

**Comment by andryyy** [comment]
local.d/history_redis.conf

**Comment by PaoloVi** [comment]
> local.d/history_redis.conf

Works perfect. Thank you

**Comment by apintocr** [comment]
Hello @andryyy ,
Can you let me know how to add that .conf correctly to MailCow?
I do not see the file and I'm a bit afraid about messing up something.

I also believe other users would benefit from this :)

Thank you very much!

**Comment by andryyy** [comment]
Hi, in `data/conf/rspamd/local.d/history_redis.conf`. :)

**Comment by apintocr** [comment]
@andryyy I did try that.
Even restarted all containers (at the command line level)
However it did made any difference, logs are still locked at 200 :(

Am I missing something?

**Comment by apintocr** [comment]
Ok!
For some reason I forgot to change the user:group of the file.

For reference, here is what I did:

- Create the file `data/conf/rspamd/local.d/history_redis.conf`
- With _only_ this line of content on the file `nrows = 5000;
` (you can use any number, the default is 200).
- Double check if the created file has the same user:group permissions as the rest of the files.
- Restart all containers using _docker-compose_

Hope this helps!
