### ISSUE TITLE
2FA problem after restore

### ISSUE THREAD

**Issue by zero-one-devteam** [mailcow/mailcow-dockerized#103]
I configured 2FA for User admin. After a database restore, the 2nd factor no longer works (I'm using U2F with Yubikey). I guessed the only relevant place is the table "tfa" in the mailcow database. Is there any additional file necessary?

**Comment by broedli** [comment]
The only place that is relevant to your tfa settings is your [mailcow db](https://github.com/andryyy/mailcow-dockerized/blob/aa7d0083d77b4bd992f5122fe37c96ff00ce532a/data/web/inc/functions.inc.php#L2035-L2105). I just did a complete reinstall of mailcow and imported a db with tfa protected admin accounts and all of them work fine after the import.

What problems are you having? What is in your logs? How are we supposed to answer your question with no informations given?

**Comment by andryyy** [comment]
Has your hostname changed?

**Comment by zero-one-devteam** [comment]
Yes, the hostname changed, thanks for steering me in the right direction. I will delete the entry in the tfa table and re-create the 2fa in the Admin-Frontend. It is important to know for future restores that it will work with pure db restore when not changing the hostname.
