### ISSUE TITLE
SPAM not going to junk folder

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#1030]
Hello,

I have problems with SPAM messages not being sent to junk folder. Here are the setting for the mailbox:
SPAM rating 4.5:12.5
*@adwordparaventas.com is on the domain.com blacklist
Mailcow updated to master about 5-10 days ago

Headers for a message not going to junk folder:

X-Rspamd-Queue-Id: E4BED1F40A9B
X-Spamd-Result: default: False [10.89 / 15.00]
	 SUBJ_EXCESS_QP(0.00)[]
	 PREVIOUSLY_DELIVERED(0.00)[mailbox@domain.com]
	 RWL_MAILSPIKE_EXCELLENT(0.00)[184.12.105.148.rep.mailspike.net : 127.0.0.20]
	 RCVD_COUNT_TWO(0.00)[2]
	 TO_MATCH_ENVRCPT_ALL(0.00)[]
	 REPLYTO_EQ_FROM(0.00)[]
	 TO_DN_NONE(0.00)[]
	 R_DKIM_ALLOW(-0.20)[mail184.sea22.mcdlv.net]
	 URIBL_GREY(1.50)[list-manage.com.multi.uribl.com]
	 ARC_NA(0.00)[]
	 GREYLIST(0.00)[pass,body]
	 FORGED_SENDER_VERP_SRS(0.00)[]
	 RCPT_COUNT_ONE(0.00)[1]
	 IP_SCORE(0.00)[ipnet: 148.105.0.0/17(2.29), asn: 14782(1.40), country: US(-0.07)]
	 MX_GOOD(-0.01)[cached: mail.mail184.sea22.mcdlv.net]
	 RCVD_IN_DNSWL_NONE(0.00)[184.12.105.148.list.dnswl.org : 127.0.15.0]
	 ASN(0.00)[asn:14782, ipnet:148.105.0.0/17, country:US]
	 RCPT_MAILCOW_DOMAIN(0.00)[domain.com]
	 DMARC_NA(0.00)[adwordparaventas.com]
	 DYN_RL_CHECK(0.00)[]
	 FROM_EXCESS_QP(1.20)[]
	 DKIM_TRACE(0.00)[mail184.sea22.mcdlv.net:+]
	 FROM_NEQ_ENVFROM(0.00)[wordpymes@adwordparaventas.com,bounce-mc.us17_89316505.129763-mailbox=domain.com@mail184.sea22.mcdlv.net]
	 R_SPF_ALLOW(-0.20)[+ip4:148.105.12.184]
	 FROM_HAS_DN(0.00)[]
	 RCVD_NO_TLS_LAST(0.00)[]
	 REPLYTO_EXCESS_QP(1.20)[]
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain]
	 BAYES_SPAM(7.50)[100.00%]
	 HAS_REPLYTO(0.00)[wordpymes@adwordparaventas.com]
X-Spam-Flag: YES
X-Spam: Yes

I see that PREVIOUSLY_DELIVERED flag is set, but I manually moved all previous messages to junk before receiving this one. Also, X-Spamd-Result: default: False [10.89 / 15.00] seems weird.

I have hundreds of messages like that one and this problem has been present for months. What am I doing wrong?

**Comment by andryyy** [comment]
Did you change the default spam scores via Rspamd UI?

`docker-compose exec rspamd-mailcow rspamadm configdump` output would be helpful. Is everything up to date?

Is watchdog running? If not, enable it and check if Rspamd checks fail.

**Comment by andryyy** [comment]
Btw., there is a X-Spam-Flag and X-Spam header, where are these coming from? Please let us know about modifications you made.

**Comment by catcun** [comment]
- spam score for that mailbox is 4.5:12.5
- I haven't touched the default spam scores
As far as I remember my rspamd configuration is standard. The mailbox has a forward to another local mailbox; otherwise is a standard mailbox.
I am attaching rspamd configuration and full mail headers for the same message
[rspamd_conf.txt](https://github.com/mailcow/mailcow-dockerized/files/1717673/rspamd_conf.txt)
[headers.txt](https://github.com/mailcow/mailcow-dockerized/files/1717674/headers.txt)

 EDIT:
I forgot, I disabled watchdog as it was complaining: 
Watchdog: rspamd-mailcow service hit the error rate limit
Service was restarted, please check your mailcow installation.

What should I check?

**Comment by catcun** [comment]
Is it possible to completely delete rspamd container and install a fresh one? I am willing to lose the learned spam/ham and any customization

**Comment by andryyy** [comment]
Hm, something is wrong with the settings table, I guess. Can you please check in "debug" for the settings map and send it to info@servercow.de ?  It's possible I already fixed that in dev.

**Comment by catcun** [comment]
@andryyy helped me checking part of my server's configuration but it seemed all right. I believe it is something related to my particular installation and not Mailcow related; soon I will reinstall the server so I am closing this is issue.
