### ISSUE TITLE
Question about backup consistency...

### ISSUE THREAD

**Issue by jfguyet** [mailcow/mailcow-dockerized#1031]
Hi there!
First, congrats for the fantastic job done here. Really impressive!

I have a question about backup_and_restore.sh helper script. Given it uses tar to backup emails from dovecot, I don't understand how consistency of the backup can be guaranteed... Actually I was more expecting something based on "doveadm backup" to handle the backup part. 

Am I missing something here? 

Regards

**Comment by klausenbusk** [comment]
https://serverfault.com/questions/758450/make-consistent-copy-of-maildir is worth reading.

**Comment by andryyy** [comment]
Doveadm backup is the proper way, we just rely on Dovecots self-healing Index here. Should be changed in the future, I agree.
