### ISSUE TITLE
Typo in location regexpr?

### ISSUE THREAD

**Issue by danielmorlock** [mailcow/mailcow-dockerized#1033]
There is no closing parentheses for the first "(":

https://github.com/mailcow/mailcow-dockerized/blob/fb92619aac6274aff29261ecf8edb2b8f33ac994/data/conf/nginx/site.conf#L352

**Comment by andryyy** [comment]
Thanks, good catch!

Makes me wonder if that rule has a use anymore.

**Comment by danielmorlock** [comment]
I traced back the leading "(" until the initial commit of the nginx.conf
