### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by klausenbusk** [mailcow/mailcow-dockerized#1034]
I get the following mixed content warning (on the mailcow login screen):
```
Blocked loading mixed active content “http://redant.com.au/fonts/fontawesome-webfont.woff?v=4.0.3”
Blocked loading mixed active content “http://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0b.woff2”
```

A quick `grep` I couldn't find where we use them.

**Comment by andryyy** [comment]
You are probably using another Bootstrap theme than the default?

**Comment by klausenbusk** [comment]
> You are probably using another Bootstrap theme than the default?

I havent changed anything related to the theme. I will do some more debugging when I get home.

**Comment by andryyy** [comment]
We don't load any of these files. :-/

**Comment by klausenbusk** [comment]
> We don't load any of these files. :-/

Hmm, I'm not sure what was causing this, but it is gone now. Very weird..
