### ISSUE TITLE
Moving mailcow-dockerized installations folder?

### ISSUE THREAD

**Issue by ohobby** [mailcow/mailcow-dockerized#1039]
Hi,

by mistake I installed mailcow-dockerized in a wrong folder and set everything up completely.
Is it possible to move now the folder "mailcow-dockerized" into /opt? What should I possibly consider?

Thanks,
Oliver

**Comment by klausenbusk** [comment]
If you rerun `docker-compose` afterwards I think it should work. A lot of the containers mounts `data/<something>`.

**Comment by andryyy** [comment]
Copy with rsync -avh or cp -rp to keep permissions and owners. Run "docker-compose down" before moving files. :-) You should be fine then.

**Comment by ohobby** [comment]
I have done this and it looks good.

cd 'old Folder'
docker-compose stop
cp -rp 'old Folder' 'new Folder'
cd 'new Folder'
docker-compose up -d

Many Thanks 👍

**Comment by wreidlinger** [comment]
@andryyy thanks for the info.
I also tried to move the installation folder for mailcow.
In my case I moved it from `/opt/docker/mailcow-dockerized` to `/opt/docker/stacks/mailcow-dockerized`.
If I try to restart the mailcow stack I ran into this error.

```bash
root@host:/opt/docker/stacks/mailcow-dockerized# docker compose start
[+] Running 0/3
 ⠧ Container mailcowdockerized-sogo-mailcow-1     Starting                    0.7s
 ⠧ Container mailcowdockerized-unbound-mailcow-1  Starting                    0.7s
 ⠧ Container mailcowdockerized-php-fpm-mailcow-1  Starting                    0.7s
Error response from daemon: failed to create task for container: failed to create shim task:
OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting
"/opt/docker/mailcow-dockerized/data/web/inc/init_db.inc.php" to rootfs at "/init_db.inc.php":
mount /opt/docker/mailcow-dockerized/data/web/inc/init_db.inc.php:/init_db.inc.php (via /proc/self/fd/6),
flags: 0x5000: not a directory: unknown:
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

The error refers to the old path. Do I need to update the path somewhere? Or how I can fix this mounting problem? Hope anybody can help.
