### ISSUE TITLE
lets encrypt renewal failed

### ISSUE THREAD

**Issue by christoph5180** [mailcow/mailcow-dockerized#1040]
it's not possible to renewal the certs

log:
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 23.45.101.142
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:f1:189::3d5
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:f1:19d::3d5
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: new-reg
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: bad HTTP: 400
acme-mailcow_1       | acme-client: transfer buffer: [{ "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]", "status": 400 }] (267 bytes)
acme-mailcow_1       | acme-client: bad exit: netproc(88): 1
acme-mailcow_1       | Verified hashes.
acme-mailcow_1       | Retrying in 30 minutes...

can I do something?

**Comment by andryyy** [comment]
You should update mailcow. :-)

**Comment by christoph5180** [comment]
I already had update malcow before I opened the issue. I wait 30 minutes for renewal and hope it work.

**Comment by andryyy** [comment]
Did you run update.sh? Current acme-mailcow does use the new agreement. It's possible you just updated code (pull, merge) and forgot to get the new images?

**Comment by christoph5180** [comment]
I had run the update.sh.

**Comment by andryyy** [comment]
Something failed then, this is not the currently used acme image of mailcow. The agreement was fixed a long time ago.

**Comment by christoph5180** [comment]
OK, I will try the manual update.
I get an error by execute the following:
```
# If it conflicts with files that were deleted from the mailcow repository, just run...
git status --porcelain | grep -E "UD|DU" | awk '{print $2}' | xargs rm -v

rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
```

**Comment by christoph5180** [comment]
OK danke. Ich habe immer nur das update.sh Skript ausgeführt. Habe jetzt die Anleitung für das manuelle Update genommen damit funktioniert es nun. Ich nehme an, dass "git status --porcelain | grep -E "UD|DU" | awk '{print $2}' | xargs rm -v" nur funktioniert wenn Konflikte beim merge aufgetreten sind?

I've done a pull and merge, now the renewal working.

**Comment by andryyy** [comment]
Hm, eigenartig. Danke für die Info. Hast du noch den Output vom Update via update.sh? Kamen Fehler auf?
