### ISSUE TITLE
HowTo learn existing Spam Mails (from a other Mailbox and Server)?

### ISSUE THREAD

**Issue by ohobby** [mailcow/mailcow-dockerized#1049]
Hi,

I have some spam folders (from another mailbox and server) and want the rspamd to reject this.

What is the easiest or best way?

Are mails being moved to the spam folder by me, learned as spam and mails that I move from the spam folder back to the inbox as HAM?

Thanks,
Oliver

**Comment by ohobby** [comment]
At https://mailcow.github.io/mailcow-dockerized-docs/u_e-rspamd/ is to read "Rspamd learns mail as spam or ham when you move a message in or out of the junk folder to any mailbox besides trash." But i cannot see this. How can i check if this work right or not?

**Comment by evilstiefel** [comment]
Check https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rspamd_ui/ where you can find details on how to login to the interface of rspamd. There, you can see the status of the database (messages processed etc).
