### ISSUE TITLE
Navbar CSS prevents admin tabs from being accessed

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#1051]
The CSS for the Navbar inside the admin pages hides the configuration tabs.

The navbar either need to have `position: fixed` removed, or the page below needs to have some padding added to the top.

Default:
![2018-02-15 11_02_33-mailcow ui - opera](https://user-images.githubusercontent.com/7480500/36253578-d785c402-123f-11e8-8a59-d837094298b8.png)

With `position: fixed` removed.
![2018-02-15 11_02_52-mailcow ui - opera](https://user-images.githubusercontent.com/7480500/36253596-e906258c-123f-11e8-9c24-6674a47db091.png)

**Comment by andryyy** [comment]
Can't confirm on Chrome and Firefox. Even on IE 11 it is alright.

**Comment by MrSuttonmann** [comment]
My apologies, I forgot to mention the browser. It does not display properly in Opera. I assumed this would be the same in Chrome as it uses Chromium behind the scenes, but apparently not. Not a high priority browser I realise.

When I get home tonight I'll see if I can fix it and create a pull request.

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/36270855-2814543c-127d-11e8-960d-902cd411d052.png)

It works on Opera, too. :-/

Please do not remove the position tag with a PR. We already have padding here, is it possible you removed something?

**Comment by MrSuttonmann** [comment]
Hmm, I tried a hard cache reset and it's started displaying properly. Oh well, sorry for wasting your time.

**Comment by andryyy** [comment]
No problem. :-)
