### ISSUE TITLE
mailcow.mobileconfig File make issues if you try to configure more then one mailbox at MAC Mail

### ISSUE THREAD

**Issue by ohobby** [mailcow/mailcow-dockerized#1053]
Hi,

i found possible a bug.

If you try to configure two mailboxes from one domain at MAC Mail with the created mailcow.mobileconfig file, you remove the first one if you configure the second. :-(

Possible because it show only the Domain and not the Email Address and/or use the same PayloadUUID.

regards,
Oliver

**Comment by mkuron** [comment]
Fixed by #972. Hopefully that is ready to merge soon.
