### ISSUE TITLE
Admin Web fields lose focus 1-2 seconds after cursor placement.

### ISSUE THREAD

**Issue by ohobby** [mailcow/mailcow-dockerized#1055]
Admin Web fields lose focus 1-2 seconds after cursor placement and you have problems to write something into fields.
Google Chrome 63.0.3239.132 at Apple MAC
Other Browsers have not this problem.

**Comment by andryyy** [comment]
Hm, probably due to U2F init, I will check this.

**Comment by ohobby** [comment]
I have also update Chrome to 64.0.3282.167 and at the first look, the focus stay and is not lost. Possible it was the Chrome.

**Comment by andryyy** [comment]
Possibly, yes. I cannot reproduce. :-/ Feel free to reopen when you run into this again.

**Comment by MAGICCC** [comment]
There's also the issue when you login to a user which has 2FA activated, cancel it and login with a user without 2FA the popup still shows up
https://m.mufff.in/915.webm

**Comment by andryyy** [comment]
Thanks @MAGICCC, fixed it.
