### ISSUE TITLE
Set users to require password change on next login ? 

### ISSUE THREAD

**Issue by burntout** [mailcow/mailcow-dockerized#1058]
It is possible to force users to change password ? 
For example, users may forget their password, and have it reset to a known value by a domain administrator, but as part of organisastional policy may need to force the user to change it to something secret.
Or, users could be created in bulk, and passwords sent to them via a different, but they could be required to change at next login. 
Or, a users a/c may become compromised, and an administrator require that they reset their password.

**Comment by tkorves** [comment]
Will be fixed in the future and see #1059
