### ISSUE TITLE
Introduction of a password policy function in mailcow

### ISSUE THREAD

**Issue by burntout** [mailcow/mailcow-dockerized#1059]
Is it possible to force a password strength policy. 

For example, > 12 char, must contain upper case, lower case, digit, symbol. Must not contain parts of username or domain, must not be one last 12 previous passwords. 

Thanks,

**Comment by christianbur** [comment]
Das wäre eine sehr sinnvolle funktion, meine "Kunden" wählen immer sehr einfach Passwörter.

**Comment by andryyy** [comment]
Hi, you can set a regex in data/web/inc/vars.local.inc.php like `$PASSWD_REGEP = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$';`

"Must not contain parts of username or domain, must not be one last 12 previous passwords" is not supported, I will add a label.

**Comment by tkorves** [comment]
Let's bring things together:
- Password policy configurable by domain
- Password complexity (defined minimum character count, needed characters such as upper/lower case, digits, symbols)
- Password change interval (every x months, must not match the y previous passwords nor should it match parts of the username nor the domain)
- Force password change at next login

Any further ideas?

(last edited 2018/02/21, 11:21am CET)

**Comment by burntout** [comment]
I'd like to see a "Force password change at next login" ( though I see this is referenced here #1058 )

**Comment by ruffy91** [comment]
Has this been implemented?
I ask because if I try to set a Diceware password like DimmedAngelicDuplicityTrollingUndercutEbay I get an error that the password does not meet the policy.

**Comment by andryyy** [comment]
Check the docs and vars.inc.php - it wants a number, you can override it in `vars.local.inc.php`.

**Comment by mokou** [comment]
[According to NIST](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5), password policies shouldn't force people to meet specific character rules. They also recommend a minimum password length of 8 and that passwords shouldn't be changed "arbitrarily (e.g., periodically)".

Of course admins should be able to deviate from recommendations if they need to, but I think the default should be `$PASSWD_REGEP = '.{8,}';` paired with HIBP checks, context checks (username, domain, etc.), and no rotation.

**Comment by gromain** [comment]
I have to agree with @mokou here, password policies are not good for security. The only valid policy is minimum length. Maybe what could be added would be password check with known passwords lists from previous hacks. That would make a LOT of sense.
Everything else will encourage bad security practices and password reuse.

**Comment by vermium** [comment]
@DerLinkman This is implemented I think
