### ISSUE TITLE
Password expire policy

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#1060]
Is there a way to set up password expiration time, and notify the user by email, 5 days prior to expiration to change the password?

Would be great to implement this feature in administration panel per domain and per user.

**Comment by tkorves** [comment]
Please see https://github.com/mailcow/mailcow-dockerized/issues/1059 .

I'd personally would give a +1 vote for 'per domain' - 'per user' doesn't make sense to me. Either all or none.
