### ISSUE TITLE
Is there any way to manage the mail queue via web?

### ISSUE THREAD

**Issue by jonasport** [mailcow/mailcow-dockerized#1061]
Hi,

I'm configuring a mail server using mailcow, so far so good, i only need to test the DNS configuration with multiple domains. Since i'll be using multiple domains i would like a "cleaner" way to manage the queue. Is there any add-on/app we can add? Or do i need to do it via terminal? And if so, where is the queue folder? 

Thanks

**Comment by andryyy** [comment]
Hi,

You can use `docker-compose exec postfix-mailcow postqueue -p` etc.

**Comment by tkorves** [comment]
As this seems to be a sufficient answer by @andryyy , I'm closing this issue.
