### ISSUE TITLE
Deleting mailbox in mailcow interfaces does not delete mails

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1062]
Hi,

when I delete a mailbox in the mailcow interface and readd the same mail address again the old emails are still there in sogo. But the mailbox quota in mailcow does not fit to the messages in sogo (it shows 0 messages).

**Comment by andryyy** [comment]
There is another issue for this, can someone find it? Well... it is not implemented. We are still thinking about it. Just remove these mails from vmail-vol-1.

**Comment by hachre** [comment]
Kind of a duplicate of https://github.com/mailcow/mailcow-dockerized/issues/921

**Comment by chaosbunker** [comment]
I kind of like that they have to be manually removed. Recently, I really appreciated the fact they are not removed upon delete :-P
