### ISSUE TITLE
Skip ClamAV and Rspamd errors

### ISSUE THREAD

**Issue by discofris** [mailcow/mailcow-dockerized#1064]
Because ClamAV eats so much memory, I disabled it in mailcow.conf: 

> SKIP_CLAMD=y

Despite the comment "(Rspamd will auto-detect a missing ClamAV container)", I still have errors in the Rspamd logs:

> failed to scan: Socket error detected: Connection refused

Command `docker-compose ps` still shows a running `mailcowdockerized_clamd-mailcow_1` container ?

Sending / receiving mails do work though!

**Comment by mkuron** [comment]
The disabled containers still run, but sleep forever, consuming no resources.

Rspamd occasionally checks whether ClamAV is available. If it isn’t, it prints that warning message, which can safely be ignored. If you really want to get rid of it, you would have to manually edit the rspamd config to disable the antivirus plugin. We can‘t do that automatically, so we decided to live with that message.

**Comment by discofris** [comment]
> Rspamd occasionally checks whether ClamAV is available. If it isn’t, it prints that warning message, which can safely be ignored.

Actually that warning message is printed every time an email is received.
Good to know this can be ignored 👍
