### ISSUE TITLE
Nothing Works after Update

### ISSUE THREAD

**Issue by xxtim42xx** [mailcow/mailcow-dockerized#1066]
Hello,

2 days ago I updatet my Mailcow server to the newest version with the update Script. After the update I had no problems. All things worked. But now I noticed that I can't connect to the Webinterface. Many services had errors when I restarted them. 
How can I fix the problem? I need the server. The Downtimes are a big problem.

`Restarting mailcowdockerized_rspamd-mailcow_1    ... error
Restarting mailcowdockerized_acme-mailcow_1      ... done
Restarting mailcowdockerized_nginx-mailcow_1     ... error
Restarting mailcowdockerized_fail2ban-mailcow_1  ... done
Restarting mailcowdockerized_php-fpm-mailcow_1   ... error
Restarting mailcowdockerized_ipv6nat_1           ... done
Restarting mailcowdockerized_postfix-mailcow_1   ... error
Restarting mailcowdockerized_sogo-mailcow_1      ... error
Restarting mailcowdockerized_redis-mailcow_1     ... error
Restarting mailcowdockerized_dovecot-mailcow_1   ... error
Restarting mailcowdockerized_memcached-mailcow_1 ... done
Restarting mailcowdockerized_unbound-mailcow_1   ... done
Restarting mailcowdockerized_watchdog-mailcow_1  ... error
Restarting mailcowdockerized_clamd-mailcow_1     ... done
Restarting mailcowdockerized_dockerapi-mailcow_1 ... done
Restarting mailcowdockerized_mysql-mailcow_1     ... error

ERROR: for mailcowdockerized_nginx-mailcow_1  Cannot restart container 1642f9ad36c234c80889af7c47d9a1c10d992ecdc4a46d47172b487a1dcadf24: container "1642f9ad36c234c80889af7c47d9a1c10d992ecdc4a46d47172b487a1dcadf24": already exists

ERROR: for mailcowdockerized_rspamd-mailcow_1  Cannot restart container 8f526e4049e1fd8e2b5428bb1ad68deb92a6e4d763bdad0d717d726f80e2e41f: container "8f526e4049e1fd8e2b5428bb1ad68deb92a6e4d763bdad0d717d726f80e2e41f": already exists

ERROR: for mailcowdockerized_dovecot-mailcow_1  Cannot restart container 5316a7c5b428bc9357a0869202cb55b3414c1155875677d281e430e0ae4264d4: container "5316a7c5b428bc9357a0869202cb55b3414c1155875677d281e430e0ae4264d4": already exists

ERROR: for mailcowdockerized_mysql-mailcow_1  Cannot restart container cb79d67d754631262637c63f51be39909f03b9be493e42ab645508f862a1b0c1: container "cb79d67d754631262637c63f51be39909f03b9be493e42ab645508f862a1b0c1": already exists

ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot restart container 7187bb4ab93726ad592efbb6c0e93c7b93e697281a084753db01a64fa1362baa: container "7187bb4ab93726ad592efbb6c0e93c7b93e697281a084753db01a64fa1362baa": already exists

ERROR: for mailcowdockerized_redis-mailcow_1  Cannot restart container 56ec54c3be272eca8b2deaae1f249d8ab55eb31b5d5cfac5c489087f2867dab2: container "56ec54c3be272eca8b2deaae1f249d8ab55eb31b5d5cfac5c489087f2867dab2": already exists

ERROR: for mailcowdockerized_sogo-mailcow_1  Cannot restart container d361bec8a59ec9cb4c7c7ee59bd63c2e3ca0d5d8e3a161ffe2d5a48e66c5a574: container "d361bec8a59ec9cb4c7c7ee59bd63c2e3ca0d5d8e3a161ffe2d5a48e66c5a574": already exists

ERROR: for mailcowdockerized_php-fpm-mailcow_1  Cannot restart container 6e4554853742a2e83f34966adfc7f239a1e9fbfe87880da83a1ad0e70e60fa50: container "6e4554853742a2e83f34966adfc7f239a1e9fbfe87880da83a1ad0e70e60fa50": already exists

ERROR: for mailcowdockerized_watchdog-mailcow_1  Cannot restart container 34eb70a471f076af4d6b8458a8d17529bf432dc3eb5b1be65cdb8e44a4064003: container "34eb70a471f076af4d6b8458a8d17529bf432dc3eb5b1be65cdb8e44a4064003": already exists
`

Your sincerely
Tim

**Comment by andryyy** [comment]
Do not update Docker when services are running.

You can try to purge all running containers, restart Docker and run the stack...
```
docker-compose down
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker-compose up -d
```

https://mailcow.email/ <- Check for remote hands for critical services.

**Comment by xxtim42xx** [comment]
OK thanks it works
