### ISSUE TITLE
Update - NextCloud 13.0

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1067]
Hello,

has anyone tried to do an update to NextCloud 13 within mailcow?
Looking through the code i am a little bit confused how to do the update.
I see the necessity deleting the folder "updater" but i never updated NexCloud on command-line.

Any help is appreciated.

Thanks :-)

**Comment by apoc4lyps** [comment]
Hi,
I've updated my nextcloud to 13 (not sure if web updater worked). After update nextcloud complains about missing php freetype (needed for avatar etc.) support. Maybe this can be fixed on the php-fpm container.

Just try the web updater. if fails to apply the update you could use the manual update (https://docs.nextcloud.com/server/11/admin_manual/maintenance/manual_upgrade.html). To invoke the database update you must run the following command:
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ upgrade

**Comment by andryyy** [comment]
The self-update function should work, but I have not tested it.

Does it complain about gd without freetype support?

**Comment by andryyy** [comment]
Fixed it.

**Comment by apoc4lyps** [comment]
Thanks @andryyy for the fast fix 👍

**Comment by Dragnucs** [comment]
I am a bit confused. How is NextCloud integrated into mailcow?

**Comment by andryyy** [comment]
We still need to update the docs. :-( There is a helper script in ./helper-scripts. You can run it like `bash helper-scripts/nextcloud.sh --install` to install NC.

**Comment by Dragnucs** [comment]
I am running NextCloud on a separte server. Can I still integrate mailcow like the NC Mail application?

**Comment by andryyy** [comment]
You can install the mail app and configure it to use mailcow.
The helper script configures NC to use IMAP logins, Redis etc. - you can do this as well on a separate instance.

**Comment by Dragnucs** [comment]
Thank you for the clarification.
