### ISSUE TITLE
Feature request: Integration of solr in dovecot

### ISSUE THREAD

**Issue by zero-one-devteam** [mailcow/mailcow-dockerized#107]
Like in the non-dockerized version of mailcow it would be great to integrate solr plugin into dovecot for better search performance in SOGo. No problem to add it by myself, but would be great to have it as default. Or did you remove it due to performance issues concerning jetty & co?

**Comment by Braintelligence** [comment]
Better speed performance for mail search is nice. Can you give us a hint on how to make solr work with mailcow-dockerized? :)

**Comment by andryyy** [comment]
I think the Dovecot guys focus on their proprietary FTS engine. They merged with Open Xchange a while ago, so I think we will see more features getting ripped out or not being released under GPL.

Alternatives are very welcome. ;)

**Comment by ntimo** [comment]
Solr has been added by @andryyy today :) You can find the docs here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-fts/

**Comment by andryyy** [comment]
Thanks to @evilstiefel !

**Comment by zeigerpuppy** [comment]
I have been testing the solr integration in the last couple of days.  It works beautifully, no problems with out-of-memory errors and the memory usage is quite reasonable currently (solr process is using about 1GB).  CPU is also very low at idle, but of course ramps up when indexing is in process.

Bravo!

**Comment by Braintelligence** [comment]
What is the worst case that could happen if you activate solr and never check on it?

**Comment by andryyy** [comment]
Nothing really. Just no index. 

Ah, or a bloated server (full memory). But most people catch that with basic monitoring of the machine anyway.

It will at least not destroy anything.

**Comment by Braintelligence** [comment]
@andryyy Thanks for the explanation! Just another question to be totally sure: If solr fails completely then (full text) search will not work at all or will it fall back to the old method?

Oh and how would a monitor setting look like? I mean the whole RAM should be used up in certain cases normally, right? Or are we talking about HDD space?

**Comment by andryyy** [comment]
Searching will still work, just not via index. So it will be "slow" as before. 

Monitoring: the usual things like CPU, memory etc.

**Comment by Braintelligence** [comment]
Updated, activated and indexed everything on my own machine. Works awesomely and didn't kill my 4GB RAM 😹 
Thank you guys, this is awesome!

Not sure how to monitor it yet, will try to look from time to time at the "solr status" in the mailcow UI and if it shows something bad try to look at CPU/memory/etc. if I spot something that I can monitor in the future.

It would be cool if mailcow would expose an API for checking on status that you could webhook to 😼 or also the other way round where mailcow would execute webhooks when something fails. (The latter would work awesome with things like Mattermost, Slack, Discord etc.)

**Comment by andryyy** [comment]
"It would be cool if mailcow would expose an API for checking on status that you could webhook to"

That's something to be implemented next. Besides quota warnings and quarantine notifications. :)

**Comment by Braintelligence** [comment]
You've just earned yourself another donation. Keep up the good work ;).

**Comment by andryyy** [comment]
Thank you very much. :)
