### ISSUE TITLE
mail not visible in iOS after moving from spam to inbox

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1072]
Today i had the second time the problem, that i moved a mail with the mail app from iOS on my phone from the spam folder to the inbox. After this action, the mail was not visible in the inbox folder on the phone. The iOS is the actual version 11.2.6 from monday this week. The strange thing is, that i found the mail on my mac and on my iPad in the inbox. But everything i try, this mail is not shown in the inbox on the phone i moved. But i have no problems moving mails in my iCloud account. So i am not able to decide if it is perhaps a problem with the IMAP protocol in mailcow or if it is a problem in iOS.
I had also a look in the rspamd log, perhaps if i found something about learning that this specific mail was no spam, but the last entry was the spam score about this mail and why it was moved to the spam folder.

**Comment by andryyy** [comment]
Well, it was moved. You see it on your Mac. Dovecot is - most likely - not doing bad things.

**Comment by tkorves** [comment]
This is mostly caused by iOS Mail not having updated the Inbox itself. No error in mailcow at all.
