### ISSUE TITLE
Calendar/Contacts Outlook 2016 (O365)

### ISSUE THREAD

**Issue by flaviomeyer** [mailcow/mailcow-dockerized#1073]
Hello Guys,

First of all i will thank you for the best Mailserver ever. I use for a long time mailcow in docker version and now i want to use contacts and calendar function in Outlook 2016 (O365) version. 
Does anyone know, how i can get access to contacts and calendar in Outlook 2016 (O365)?

Kind regards,

Flavio

**Comment by mritzmann** [comment]
Setup your email account in outlook as EAS (not imap or pop).

https://mailcow.github.io/mailcow-dockerized-docs/client-outlook/

**Comment by flaviomeyer** [comment]
Hello,
Yes my setup in Outlook is EAS but i can't see contacts and calendar :(

**Comment by flaviomeyer** [comment]
Hey @mritzmann 
I checked my settings again. I have seen that it is an IMAP setting. But if I follow your instructions by calling C:\ Program Files (x86)\Microsoft Office\root\Office16\OLCFG.EXE I have only this option as IMAP and not EAS.

I've already seen the issue #615, is there a solution?

**Comment by andryyy** [comment]
You will need a retail Outlook, not one of those O365 Outlooks. They don't cost that much on eBay. Or just go for Cal-/CardDAV, I'd recommend it anyway.

**Comment by flaviomeyer** [comment]
@andryyy Is it planned to fix this issue?

**Comment by andryyy** [comment]
Fix Outlook? :-)

If you choose to buy O365, that's what you get: no EAS.

**Comment by QuocurIQ** [comment]
You can work around it by setting up a profile in the old windows control panel: Win+R > control > User Accounts > Email (Microsoft Outlook). Add a new profile, you will get ActiveSync as a choice. A bit late, but I found this thread when trying to solve the same issue.
