### ISSUE TITLE
ERROR: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by cappuccino0341** [mailcow/mailcow-dockerized#1075]
I have recently the following error message when reinstalling:

Pulling nginx-mailcow (nginx:mainline-alpine)...
mainline-alpine: Pulling from library/nginx

ERROR: no matching manifest for linux/amd64 in the manifest list entries

**Comment by dmmev** [comment]
https://github.com/nginxinc/docker-nginx/issues/230

**Comment by shaneonabike** [comment]
I had to modify the docker-compose.xml to use `nginx:stable-alpine` instead. It begs the question whether we should be using the most bleading edge version when builds go down or take a long tme :/

**Comment by cappuccino0341** [comment]
I also modified the docker-compose.yml in line 233 in
'image: nginx: stable-alpine' before the installation.

Thats how it works.

**Comment by dmmev** [comment]
> I also modified the docker-compose.yml in line 233 in
'image: nginx: stable-alpine' before the installation.

> Thats how it works.

I think its a temporary solution.

**Comment by PeterHagen** [comment]
It seems this is still an issue. I just did a clean checkout and build, and got the same error. Using stable-alpine seems to work

**Comment by andryyy** [comment]
Nope, it is most likely a temporarily non-existing image. :-) They will push a new image soon, I think.
