### ISSUE TITLE
How to release these few things?

### ISSUE THREAD

**Issue by dmmev** [mailcow/mailcow-dockerized#1076]
Thanks for the great container, which works as stated.

Unfortunately, I encounter the first time with such settings, before that I collected everything manually by separate packages.
It is very necessary to change a few things, but I have no idea how to do this.
1) enable server blocks for other domains, as is done with the usual installation of batch nginx
2) disable Ip6
3) make it possible to connect to MySQL through SQLyog (over SSH)

Perhaps someone knows the solution or suggests how to release this in this container.
Thank you and sorry for my low professionalism in this topic.

**Comment by tkorves** [comment]
1. Why would you like to host stuff for other domains on your mailsystem?
2. Why? Is there any reason for it? It's only used internally and doesn't harm anything. Neither it does on a IPv4-only Host.
3. What are you going to achieve? You could do this easily by yourself - I'd suggest, this is no change, which should be in master.

**Comment by dmmev** [comment]
1) I have one VPS and few sites on him
2) if its a only local proxy - its ok, but I doubt it
3) I tried to connect through localhost and 172 subnet, tried through different ports except 3306, but did not reach success

**Comment by andryyy** [comment]
1 and 2 will be available with the next dev => master merge. You could add a binding to the mysql-mailcow service in docker-compose.yml to easily gain access to sql.

For further sites, just add data/conf/nginx/**whatevername**.conf and restart nginx-mailcow by running "docker-compose restart nginx-mailcow".

**Comment by dmmev** [comment]
Wow! Big thanks! I will look forward to the new version.
