### ISSUE TITLE
"docker-compose up -d" ERROR - After ./update.sh

### ISSUE THREAD

**Issue by Marvo2011** [mailcow/mailcow-dockerized#1078]
Hello,

I have updated my mailcow with ./update.sh because I would use EWS in Outlook 2016. But I become the following error by the update script and typing "docker-compose up -d" in the mailcow dir.

`ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

The "docker-compose.yml" file is the same as here in the repository.

**Comment by andryyy** [comment]
EWS cannot be emulated, but EAS is available.

`docker-compose up -d` is not needed after updating.

Try `docker-compose down` followed by `systemctl restart docker` and `docker-compose up -d` to fix your error.

**Comment by Marvo2011** [comment]
Sorry I mean EAS.

`docker-compose down` gives the same error. 
`systemctl restart docker` takes a very long time... 

Edit: It looks like docker would have a hang up.
Edit: Thanks, It can closed. Docker had a hang up, killing it and restart the docker service fix the issue.
