### ISSUE TITLE
Fail2Ban unban option?

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#1079]
Hello, i have struggled a few times to try unbanning an ip,
1)docker-compose restart fail2ban-mailcow
doesnt help...
2)docker-compose excec fail2ban-client -i
No such command is found

Only option is to reboot everything :(
It would be great to unban an IP just by typing one command, or even better if it was included in Mailcaw UI.

**Comment by mritzmann** [comment]
> Only option is to reboot everything :(

Should be enough if you just restart the fail2ban container.

Configuration -> Debugging -> Containers -> Restart fail2ban

Or you can wait for 30 minutes.

**Comment by lazyfrosch** [comment]
The container is not a classic Fail2Ban instance, its mailcow's own implementation.

**Comment by andryyy** [comment]
There are already hashes for that in Redis, but I have not yet implemented them into the UI.

**Comment by lucianlazar1983** [comment]
I too would like to see the option to unban a banned ip directly from the user interface

**Comment by edijs** [comment]
> Should be enough if you just restart the fail2ban container.

The only problem is that then the ban is removed from all the addresses.. Is there any command line option to remove the ban for a specific address?
