### ISSUE TITLE
2FA authentication fails to work with the new defaults for reverse proxy setup

### ISSUE THREAD

**Issue by afzalarsalan** [mailcow/mailcow-dockerized#108]
Following the instructions recently posted for using an NGINX reverse proxy, I've noticed that neither form of 2FA is able to be registered from what I presume is due to incorrect parameters being put into the auth request. This change directly manifested with the removal of proxy_set_header Host and the required move to proxy_redirect. Trying to use both ends up with Sogo no longer working due to it returning the local proxy port in the http return address.

**Comment by afzalarsalan** [comment]
And apparently autodiscover and autoconfig no longer work, as in they just return the main page

**Comment by andryyy** [comment]
Do you change the hostname with the reverse proxy?

Do you access autodiscover and autoconfig with the correct path?

"due to incorrect parameters being put into the auth request" <- which exactly?

**Comment by afzalarsalan** [comment]
I've tried a variety of configurations including without a reverse proxy and it doesn't seem to make a difference without a reverse proxy for autodiscover and autoconfig. And the U2F standard was giving error code two which derives from bad parameterization.

**Comment by afzalarsalan** [comment]
The easiest way to see it not working is the lack of any client applications being able to detect the server settings from the email address alone.

**Comment by andryyy** [comment]
No, you need to access the correct URL to test it.

http://autoconfig.develcow.de/mail/config-v1.1.xml <- works
https://autodiscover.develcow.de/autodiscover/autodiscover.xml <- works (with credentials)

But the U2F error is indeed bad, I will fix it now. :-)

Edit: The URLs above use a reverse proxy.

**Comment by andryyy** [comment]
You need to add `proxy_set_header Host $host;` to your reverse proxy and merge the changes I just commited to master.

**Comment by afzalarsalan** [comment]
U2F now works and you were right about the autoconfig however now I'm unable to log into Sogo because the browser is being redirected to an internal port, in my case 8080.

**Comment by afzalarsalan** [comment]
This is after login in which it tries to redirect

**Comment by andryyy** [comment]
Any changes done to Nginx config? Can you check and confirm it works without the new host setting?

> Am 09.03.2017 um 10:57 schrieb Arsalan Afzal <notifications@github.com>:
> 
> e

**Comment by afzalarsalan** [comment]
Yes, the login works perfectly fine without the new host setting

**Comment by andryyy** [comment]
Thanks, will fix it now.

**Comment by afzalarsalan** [comment]
But now 2FA no longer works so we're back where we started

**Comment by andryyy** [comment]
Yes. :-) I just pushed another fix: Removed the "host" part and use "server_name" instead of "http_host" in PHP. Sorry for that.

**Comment by afzalarsalan** [comment]
That's the trick, works perfectly now. Thanks so much for the quick fix 👍
