### ISSUE TITLE
always internal ip?

### ISSUE THREAD

**Issue by toupou** [mailcow/mailcow-dockerized#1080]
Hi, 

first thanks for this great tool! installation worked flawlessly and internally all is working good. 

I have one issue I´m not able to solve and I´m reading and trying weeks now. 
I use UTM 9.5 as my firewall and added the mailcow server as a webserver. 
when I try to connect from outside my network I always get forwarded to my internal ip in DMZ 192.168.20.200

I have another virtual webserver configured in UTM and with this one (apache2) I do not have this issue. After reading, reading and trying I´m not sure what to do anymore. 

any hints? what I need to have a look at?

Thanks
toupou

**Comment by andryyy** [comment]
Hi,

I don't know how we can help you.

You shouldn't be using mailcow behind NAT without proxy protocol.
