### ISSUE TITLE
install failed docker-compose version and invalid interpolation

### ISSUE THREAD

**Issue by changchichung** [mailcow/mailcow-dockerized#1081]
root@mail:/mailcow/mailcow-dockerized# docker-compose pull
ERROR: Version in "./docker-compose.yml" is invalid. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@mail:/mailcow/mailcow-dockerized# vim docker-compose.yml
root@mail:/mailcow/mailcow-dockerized# docker-compose pull
ERROR: Invalid interpolation format for "dns" option in service "mysql-mailcow": "${IPV4_NETWORK:-172.22.1}.254"
root@mail:/mailcow/mailcow-dockerized#

please help , thanks ...

**Comment by mritzmann** [comment]
Whats your docker-composer version?

`docker-compose -v`

---

edit: https://github.com/mailcow/mailcow-dockerized/issues?q=is%3Aissue+You+might+be+seeing+this+error+because+you%27re+using+the+wrong+Compose+file+version+is%3Aclosed

**Comment by changchichung** [comment]
root@mail:/mailcow# docker-compose -v
docker-compose version 1.8.0, build unknown
root@mail:/mailcow#

**Comment by mritzmann** [comment]
Your version is too old. Install a newer docker-compose version. 1.8.0 was from 2016-06-14 ...

**Comment by changchichung** [comment]
that`s the newest docker-compose version on ubuntu 16.04 ...
need what version  to install ?

**Comment by mritzmann** [comment]
> need what version to install ?

Version 1.19.0.

see: https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by changchichung** [comment]
I figure out why I follow all steps in installation guide but still failed ..
I should use /usr/local/bin/docker-compose up , not just docker-compose up
