### ISSUE TITLE
Mail moving from inbox subfolder to inbox, create many duplicate mails?!

### ISSUE THREAD

**Issue by ohobby** [mailcow/mailcow-dockerized#1082]
Hi,

at the weekend i have moved mails from a other imap mailbox into a subfolder from my inbox and i have cleanup the mails and want now move the inbox subfolder mails into the Inbox. (With Apple Mail)
Then i see that the counter how many Mails he want move grow up and up. I have then kill the mail program and take a look over SoGo and see now, that i have many duplicates in the Inbox.

What did i do wrong? 
What went wrong there?
What is the best way to remove the duplicates?

regards,
Oliver

**Comment by andryyy** [comment]
I don't know what you did wrong, but it is not a Dovecot issue.

To deduplicate it should be enough to run `docker-compose exec dovecot-mailcow doveadm -D deduplicate -u user@domain mailbox '*'`.
