### ISSUE TITLE
I can't share my calender

### ISSUE THREAD

**Issue by FN-Florian** [mailcow/mailcow-dockerized#1087]
Hi,
i will share my calender from user  test1@testtld1.com  to  user  test2@testtld2.com  but i don't see the user in the permission field.
When i enter an user with  testtld1.com domain then i see this user and i can give rights to my calender.
I try it in SOGo with my personal calender

It is normal and can i change a setting to change this?

_Florian_

**Comment by andryyy** [comment]
Hi, you can find an example for multi domain visibility in data/conf/sogo/sogo.conf, restart SOGo after changing that file.

**Comment by FN-Florian** [comment]
How can i edit this file in a running docker container?

**Comment by andryyy** [comment]
? Just edit that file and restart the container.

**Comment by FN-Florian** [comment]
I have now edit the file and restartet the container in mailcow. But i can't give rights in SOGo.

```
SOGoDomainsVisibility = (
      (testtld1.com,testtld2.com)
     );
```

I works first time with docker, its right when i edit the file in the download path? Or i must enter docker-compose pull for upload the file in the container?

**Comment by andryyy** [comment]
I don’t understand.

It works like that. Edit the file correctly and restart SOGo or even run down and up -d.

**Comment by FN-Florian** [comment]
After Restart i get an error when i try open SOGo

502 Bad Gateway  ,  but i find no entrys in the log in mailcow  -> Debugging -> Logs -> SOGo

**Comment by andryyy** [comment]
You destroyed your SOGo config then. Checkout the original sogo.conf and start over. I tested it just a few mins ago and it works fine.

I close this, but feel free to ask further questions.

**Comment by FN-Florian** [comment]
Ok, this is now fixed.

But i can't share my calender to the other domain.  Is my syntax right?

```
    SOGoDomainsVisibility = (
      (tld1.de,tld2.de),
      (tld5.de,tld7.de)
     );

```
I use an email adress with tld1.de  and the other user has an mail adress with tld2.de  but i don't see users with the tld2.de  mail adresses.


-------

I find my mistake ...  i use the wrong domain (tld.eu -> tld.de)  -.-
