### ISSUE TITLE
Stable, Beta or Alpha?

### ISSUE THREAD

**Issue by jkaberg** [mailcow/mailcow-dockerized#109]
I failed to find any status on this project? In what phase is it (stable, beta ... )?

You should mention this somewhere (like in the README.md)

**Comment by PhoenixPeca** [comment]
Hi,
The master branch of the dockerized-mailcow is already stable and we (currently) recommend using it rather than the standard mailcow.

**Comment by jkaberg** [comment]
Roger that. You guys should mention that somewhere, as currently you actively push towards master (instead of feature branch->master).

I'm actually missing something like [this](http://fle.github.io/an-efficient-git-workflow-for-midlong-term-projects.html). The current setup seems fragile.

**Comment by jaketame** [comment]
Do you have a guide on migrating from standard mailcow to docker mailcow?

**Comment by josephbu** [comment]
@jaketame user @wucke13 wrote about his migration steps from standard to docker in another [issue](https://github.com/andryyy/mailcow-dockerized/issues/132#issuecomment-288035473). This may be of help!

**Comment by broedli** [comment]
Please check the guide in [our documentation](https://mailcow.github.io/mailcow-dockerized-docs/) and try to improve it if necessary. Every PR is welcome!

I'm closing this issue for now. Please feel free to open a new Issue in the repository of our documentation if needed.
