### ISSUE TITLE
Mails not signed with DKIM key

### ISSUE THREAD

**Issue by SvenWen** [mailcow/mailcow-dockerized#1091]
Hello,

I have an issue with my DKIM setup. I am using two domains on my server @domain1.com @domain2.com.

I have generated DKIM keys for both domains in the admin panel. For domain1 (which was the first domain to be added to the server) everything just works fine. For domain2, the e-mails are not signed by the server with a DKIM-record. When I send the mails to e.g. Gmail, I get the SPF and DMARC pass, but no DKIM. Looking at the headers of the e-mail, it simply does not contain a DKIM entry.

I have already deleted the DKIM entry for domain2 in the admin panel, restarted mailcow and generated a new one - still the same problem.

Any ideas where to look in order to start some troubleshooting?

Thank you,

Sven.

**Comment by SvenWen** [comment]
Just to add a piece of information:

The log of rspamd shows that the mails of domain1 are signed with DKIM; that entry is missing for mails sent in domain2.

HGET DKIM_PRIV_KEYS and HGET DKIM_SELECTORS in the redis-cli both show the entries created in the admin web interface for both domains.

**Comment by andryyy** [comment]
Hi, Can you please run `docker-compose exec rspamd-mailcow rspamadm configdump` and post your config? `iptables -L -vn` and `ip6tables -L -vn` would be helpful, too. :-)

**Comment by SvenWen** [comment]
Hi, here are the requested infos. I guess the iptables and ip6tables refer to the host system and not something within the docker containers?! - Sorry, but I'm not completely settled in the docker thematic yet. ;-)

[config_rspamd.txt](https://github.com/mailcow/mailcow-dockerized/files/1764050/config_rspamd.txt)
[ip6tables.txt](https://github.com/mailcow/mailcow-dockerized/files/1764051/ip6tables.txt)
[iptables.txt](https://github.com/mailcow/mailcow-dockerized/files/1764052/iptables.txt)

**Comment by andryyy** [comment]
Can you please also show the output of `docker-compose logs --tail=200 rspamd-mailcow` when you send a mail?

**Comment by SvenWen** [comment]
After updating mailcow, the problem vanished. So unfortunately, I cannot track down the error anymore.

But thank you very much for the support!
