### ISSUE TITLE
Feature Request: Mailbox Quote Sort by Size Instead of Numerical Order

### ISSUE THREAD

**Issue by stevesbrain** [mailcow/mailcow-dockerized#1092]
Hi guys - just wondering if it'd be possible to ask for a feature to sort the "Quota" in the admin panel by actual size, rather than just numerical order? Right now, for example, sorting by "quota" descending will sort by 9 -> 1 (i.e. 9GB, 9MB, etc all appear before 1GB, 1MB), for example, rather than 9GB to 1GB:

![Example of sorting](https://i.imgur.com/ZmxbSMU.png)

I would typically sort quota usage in an attempt to find who's using the most - but as you see in my example image, a user who is using 5GB appears further down the list than someone using 84MB. If there's a reason it wasn't implemented this way, then please feel free to tell me to buzz off - but I figured this was a minor oversight and we're simply using a basic numerical sorting instead of sorting by "human values" :)

**Comment by andryyy** [comment]
Thank you, fixed it (in dev).
