### ISSUE TITLE
Nextcloud Picture Preview

### ISSUE THREAD

**Issue by Icki153** [mailcow/mailcow-dockerized#1096]
Hello,
i installed with helper Script Nextcloud. All working fine. But Picture Preview Not working. I also tried to install Nextcloud 13 same issue.

**Comment by andryyy** [comment]
Hi, I need anything to start with. Nginx logs, URL of the picture which results in a 404 etc.

**Comment by andryyy** [comment]
I tested it and it works fine. What is your config? Subfolder? Subdomain? Reverse proxy?

**Comment by Icki153** [comment]
Hello, i send you the Information later. 

New installed Ubuntu 16.04. LTS
Install Mailcow with Manual
Restore Mails
Setup Nextcloud as Subdomain.

**Comment by Icki153** [comment]
Public Link is https://cloud.graf-jaekel.de/s/HhqlsKdMwBqk09G
Private Link is https://cloud.graf-jaekel.de/apps/files/?dir=/Photos&fileid=6#/Photos/Coast.jpg

Log from NGINX with only the last Lines after open the Picture.
[nginx_log.txt](https://github.com/mailcow/mailcow-dockerized/files/1764285/nginx_log.txt)

I cant find any problem. Log from Nextcloud says 

Error | gallery | Exception: Preview generation has failed

**Comment by andryyy** [comment]
Reverse proxy? I cannot reproduce it here, it is fine.

Ah, it is possible you have to wait for dev => master to get it to work.

**Comment by Icki153** [comment]
No Reverse proxy.

Ok. I give up my seafile Cloud because the Integration of nextcloud :D

How long to wait? Or is it possible to use temporary the dev Branch?

**Comment by MAGICCC** [comment]
You can switch to the dev branch with `git checkout dev` and restarting all containers.
Do note, that it may includes bugs and such!
