### ISSUE TITLE
Aliases with Plus Adressing Not Sorted

### ISSUE THREAD

**Issue by luroden** [mailcow/mailcow-dockerized#1098]
**Setup:**
Primary account: david@mydomain.com
david@mydomain.com has Set handling for tagged mail: set to "In Subfolder"
There is an alias: david@myotherdomain.com -> david@mydomain.com

**Problem:**
When sending an email to david+tag@myotherdomain.com, it gets routed to the inbox david@mydomain.com 

**Expected Action:**
When sending an email to david+tag@myotherdomain.com, it gets routed to the tagged folder under david@mydomain.com

Here is some headers from the incorrectly sorted email with important info stripped out
```
    Return-Path: <david@gmaildomain.com>
    Delivered-To: david+test@mydomain.com
    Received: from my.email.server.com ([REDACTED])
	by my.email.server.com with LMTP id gHUjCoGclVpTRgAAXwvI7A
	for <david+test@mydomain.com.com>; Tue, 27 Feb 2018 10:59:29 -0700
    Received: from mail-ot0-f173.google.com (mail-ot0-f173.google.com [74.125.82.173])
	by my.email.server.com (Postfix) with ESMTPS id C649D18E00A7
	for <david+test@myotherdomain.com>; Tue, 27 Feb 2018 10:59:27 -0700 (MST)
    Received: by mail-ot0-f173.google.com with SMTP id n74so4625805ota.1
        for <david+test@myotherdomain.com>; Tue, 27 Feb 2018 09:59:27 -0800 (PST)
```

**Comment by andryyy** [comment]
It doesn't work for alias addresses. :-(

And I think we already have an open issue for it.

**Comment by luroden** [comment]
Oh sorry! I thought I looked. I will look through for it again

**Comment by mkuron** [comment]
Duplicate of #408.
