### ISSUE TITLE
SOGo stopped

### ISSUE THREAD

**Issue by mobeustech** [mailcow/mailcow-dockerized#1099]
Fresh install and nothing else is running on this server except for mailcow-docker.  

Everything was working fine until I added a domain, domain alias, and users.  After telling Mailcow admin to restart SOGo I get 502 bad gateway when trying to login and test.

My SOGo log shows:

root@securemail:/data/mailcow-dockerized# docker-compose logs sogo-mailcow
Attaching to mailcowdockerized_sogo-mailcow_1
sogo-mailcow_1       | 2018-02-27 11:07:00,212 CRIT Set uid to user 0
sogo-mailcow_1       | 2018-02-27 11:07:00,226 INFO supervisord started with pid 1
sogo-mailcow_1       | 2018-02-27 11:07:01,230 INFO spawned: 'syslog-ng' with pid 9
sogo-mailcow_1       | 2018-02-27 11:07:01,233 INFO spawned: 'cron' with pid 10
sogo-mailcow_1       | 2018-02-27 11:07:01,239 INFO spawned: 'bootstrap-sogo' with pid 11
sogo-mailcow_1       | 2018-02-27 11:07:01,246 INFO spawned: 'sogo-webres' with pid 12
sogo-mailcow_1       | Feb 27 11:07:01 c09af32d2478 syslog-ng[9]: syslog-ng starting up; version='3.8.1'
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:01 c09af32d2478 sogod: 2018-02-27 11:07:01.663 sogod[11:11] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:01,676 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:02,677 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | 2018-02-27 11:07:02,677 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | 2018-02-27 11:07:02,679 INFO spawned: 'bootstrap-sogo' with pid 31
sogo-mailcow_1       | 2018-02-27 11:07:02,679 INFO success: sogo-webres entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:02 c09af32d2478 sogod: 2018-02-27 11:07:02.820 sogod[31:31] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:02,823 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:04,827 INFO spawned: 'bootstrap-sogo' with pid 46
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:04 c09af32d2478 sogod: 2018-02-27 11:07:04.959 sogod[46:46] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:04,962 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:07,967 INFO spawned: 'bootstrap-sogo' with pid 62
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:08 c09af32d2478 sogod: 2018-02-27 11:07:08.157 sogod[62:62] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:08,161 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:12,168 INFO spawned: 'bootstrap-sogo' with pid 78
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:12 c09af32d2478 sogod: 2018-02-27 11:07:12.435 sogod[78:78] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:12,438 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:17,446 INFO spawned: 'bootstrap-sogo' with pid 93
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:17 c09af32d2478 sogod: 2018-02-27 11:07:17.615 sogod[93:93] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:17,618 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:23,627 INFO spawned: 'bootstrap-sogo' with pid 109
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:23 c09af32d2478 sogod: 2018-02-27 11:07:23.786 sogod[109:109] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:23,789 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:30,800 INFO spawned: 'bootstrap-sogo' with pid 124
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | 2018-02-27 11:07:30,967 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | Feb 27 11:07:30 c09af32d2478 sogod: 2018-02-27 11:07:30.965 sogod[124:124] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:38,979 INFO spawned: 'bootstrap-sogo' with pid 139
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:39 c09af32d2478 sogod: 2018-02-27 11:07:39.140 sogod[139:139] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:39,144 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:48,156 INFO spawned: 'bootstrap-sogo' with pid 155
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:48 c09af32d2478 sogod: 2018-02-27 11:07:48.281 sogod[155:155] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:48,284 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:58,296 INFO spawned: 'bootstrap-sogo' with pid 170
sogo-mailcow_1       | mysqld is alive
sogo-mailcow_1       | Feb 27 11:07:58 c09af32d2478 sogod: 2018-02-27 11:07:58.450 sogod[170:170] unable to get status of descriptor 2 - Bad file descriptor
sogo-mailcow_1       | 2018-02-27 11:07:58,453 INFO exited: bootstrap-sogo (exit status 1; not expected)
sogo-mailcow_1       | 2018-02-27 11:07:59,454 INFO gave up: bootstrap-sogo entered FATAL state, too many start retries too quickly
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[188]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[190]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[189]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[192]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[188]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:08:01 c09af32d2478 CRON[189]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[194]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[197]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[195]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[199]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[195]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:09:01 c09af32d2478 CRON[194]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[201]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[204]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[202]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[206]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[202]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:10:01 c09af32d2478 CRON[201]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:11:01 c09af32d2478 CRON[208]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:11:01 c09af32d2478 CRON[211]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Feb 27 11:11:01 c09af32d2478 CRON[209]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Feb 27 11:11:01 c09af32d2478 CRON[213]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Feb 27 11:11:02 c09af32d2478 CRON[208]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Feb 27 11:11:02 c09af32d2478 CRON[209]: pam_unix(cron:session): session closed for user sogo
root@securemail:/data/mailcow-dockerized# 

I do see an error in nginx logs

[error] 15#15: *27 connect() failed (111: Connection refused) while connecting to upstream client.

I have tried running the update.sh script and rebooting the server.  I have no idea where to look as this is all new to me.

**Comment by andryyy** [comment]
System info? KVM?

**Comment by mobeustech** [comment]
Debian 9 64bit with backports, 8GB ram 160GB HDD.  DigitalOcean droplet.

`root@securemail:/# uname -a
Linux securemail 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux`

root@securemail:/# lshw
securemail                  
    description: Computer
    product: Droplet
    vendor: DigitalOcean
    version: 20171212
    serial: 82553149
    width: 64 bits
    capabilities: smbios-2.4 dmi-2.4 smp vsyscall32
    configuration: boot=normal family=DigitalOcean_Droplet uuid=5A604D46-570C-422B-8D37-6024E73035C0
  *-core
       description: Motherboard
       physical id: 0
     *-firmware
          description: BIOS
          vendor: DigitalOcean
          physical id: 0
          version: 20171212
          date: 12/12/2017
          size: 96KiB
     *-cpu:0
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 401
          bus info: cpu@0
          slot: CPU 1
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
     *-cpu:1
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 402
          bus info: cpu@1
          slot: CPU 2
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
     *-cpu:2
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 403
          bus info: cpu@2
          slot: CPU 3
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
     *-cpu:3
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 404
          bus info: cpu@3
          slot: CPU 4
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
     *-memory
          description: System Memory
          physical id: 1000
          size: 8GiB
          capabilities: ecc
          configuration: errordetection=multi-bit-ecc
        *-bank
             description: DIMM RAM
             physical id: 0
             slot: DIMM 0
             size: 8GiB
             width: 64 bits
     *-pci
          description: Host bridge
          product: 440FX - 82441FX PMC [Natoma]
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 02
          width: 32 bits
          clock: 33MHz
        *-isa
             description: ISA bridge
             product: 82371SB PIIX3 ISA [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: isa
             configuration: latency=0
        *-ide
             description: IDE interface
             product: 82371SB PIIX3 IDE [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: ide bus_master
             configuration: driver=ata_piix latency=0
             resources: irq:0 ioport:1f0(size=8) ioport:3f6 ioport:170(size=8) ioport:376 ioport:c140(size=16)
        *-usb
             description: USB controller
             product: 82371SB PIIX3 USB [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.2
             bus info: pci@0000:00:01.2
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: uhci bus_master
             configuration: driver=uhci_hcd latency=0
             resources: irq:11 ioport:c0c0(size=32)
           *-usbhost
                product: UHCI Host Controller
                vendor: Linux 4.9.0-6-amd64 uhci_hcd
                physical id: 1
                bus info: usb@1
                logical name: usb1
                version: 4.09
                capabilities: usb-1.10
                configuration: driver=hub slots=2 speed=12Mbit/s
        *-bridge
             description: Bridge
             product: 82371AB/EB/MB PIIX4 ACPI
             vendor: Intel Corporation
             physical id: 1.3
             bus info: pci@0000:00:01.3
             version: 03
             width: 32 bits
             clock: 33MHz
             capabilities: bridge
             configuration: driver=piix4_smbus latency=0
             resources: irq:9
        *-display
             description: VGA compatible controller
             product: QXL paravirtual graphic card
             vendor: Red Hat, Inc.
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 04
             width: 32 bits
             clock: 33MHz
             capabilities: vga_controller rom
             configuration: driver=qxl latency=0
             resources: irq:11 memory:f8000000-fbffffff memory:fc000000-fcffffff memory:fd050000-fd051fff ioport:c0e0(size=32) memory:c0000-dffff
        *-network
             description: Ethernet controller
             product: Virtio network device
             vendor: Red Hat, Inc
             physical id: 3
             bus info: pci@0000:00:03.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: msix bus_master cap_list rom
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:c100(size=32) memory:fd052000-fd052fff memory:fd000000-fd03ffff
           *-virtio0
                description: Ethernet interface
                physical id: 0
                bus info: virtio@0
                logical name: eth0
                serial: ca:bb:16:47:81:d2
                capabilities: ethernet physical
                configuration: autonegotiation=off broadcast=yes driver=virtio_net driverversion=1.0.0 ip=159.xxx.xxx.xxx link=yes multicast=yes
        *-scsi:0
             description: SCSI storage controller
             product: Virtio SCSI
             vendor: Red Hat, Inc
             physical id: 4
             bus info: pci@0000:00:04.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: scsi msix bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:11 ioport:c000(size=64) memory:fd053000-fd053fff
           *-virtio1 UNCLAIMED
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@1
                configuration: driver=virtio_scsi
        *-scsi:1
             description: SCSI storage controller
             product: Virtio block device
             vendor: Red Hat, Inc
             physical id: 5
             bus info: pci@0000:00:05.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: scsi msix bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:c040(size=64) memory:fd054000-fd054fff
           *-virtio2
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@2
                logical name: /dev/vda
                size: 160GiB (171GB)
                capabilities: partitioned partitioned:dos
                configuration: driver=virtio_blk logicalsectorsize=512 sectorsize=512
              *-volume
                   description: EXT4 volume
                   vendor: Linux
                   physical id: 1
                   bus info: virtio@2,1
                   logical name: /dev/vda1
                   logical name: /
                   logical name: /var/lib/docker/plugins
                   logical name: /var/lib/docker/overlay2
                   version: 1.0
                   serial: b013aeee-1206-4dc7-9f9c-05727f8ae6e5
                   size: 159GiB
                   capacity: 159GiB
                   capabilities: primary bootable journaled extended_attributes large_files huge_files dir_nlink 64bit extents ext4 ext2 initialized
                   configuration: created=2018-02-13 07:52:38 filesystem=ext4 lastmountpoint=/ modified=2018-02-27 10:53:39 mount.fstype=ext4 mount.options=rw,relatime,errors=remount-ro,data=ordered mounted=2018-02-17 13:47:31 state=mounted
        *-scsi:2
             description: SCSI storage controller
             product: Virtio block device
             vendor: Red Hat, Inc
             physical id: 6
             bus info: pci@0000:00:06.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: scsi msix bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:11 ioport:c080(size=64) memory:fd055000-fd055fff
           *-virtio3
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@3
                logical name: /dev/vdb
                size: 424KiB (434KB)
                configuration: driver=virtio_blk logicalsectorsize=512 sectorsize=512
        *-generic
             description: Unclassified device
             product: Virtio memory balloon
             vendor: Red Hat, Inc
             physical id: 7
             bus info: pci@0000:00:07.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: bus_master
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:c120(size=32)
           *-virtio4 UNCLAIMED
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@4
                configuration: driver=virtio_balloon
  *-network:0
       description: Ethernet interface
       physical id: 1
       logical name: vetha42f7cc
       serial: 56:8f:23:f9:86:1d
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:1
       description: Ethernet interface
       physical id: 2
       logical name: vethb2dac39
       serial: 1a:ed:ad:ee:91:7c
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:2
       description: Ethernet interface
       physical id: 3
       logical name: vethe4dca9f
       serial: 3e:dc:2b:e5:62:73
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:3
       description: Ethernet interface
       physical id: 4
       logical name: br-774aecf74b1d
       serial: 02:42:7b:65:e3:de
       capabilities: ethernet physical
       configuration: broadcast=yes driver=bridge driverversion=2.3 firmware=N/A ip=172.22.1.1 link=yes multicast=yes
  *-network:4
       description: Ethernet interface
       physical id: 5
       logical name: veth9e24ed1
       serial: 4e:bf:53:f7:7b:b5
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:5
       description: Ethernet interface
       physical id: 6
       logical name: vethc17d644
       serial: 92:af:db:f4:35:68
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:6
       description: Ethernet interface
       physical id: 7
       logical name: veth1263d45
       serial: 86:f5:ee:33:bf:9e
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:7
       description: Ethernet interface
       physical id: 8
       logical name: veth6001b8e
       serial: 06:00:0f:d2:d8:ba
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:8
       description: Ethernet interface
       physical id: 9
       logical name: vethe53afca
       serial: c2:d4:23:0f:c2:3f
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:9
       description: Ethernet interface
       physical id: a
       logical name: veth71b8039
       serial: 9a:5c:e2:72:6b:c9
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:10
       description: Ethernet interface
       physical id: b
       logical name: veth68e368b
       serial: de:81:5b:5d:4e:1b
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:11
       description: Ethernet interface
       physical id: c
       logical name: vethf91aa2d
       serial: b2:cc:93:f1:df:59
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:12
       description: Ethernet interface
       physical id: d
       logical name: docker0
       serial: 02:42:bb:75:b1:8a
       capabilities: ethernet physical
       configuration: broadcast=yes driver=bridge driverversion=2.3 firmware=N/A ip=172.17.0.1 link=no multicast=yes
  *-network:13
       description: Ethernet interface
       physical id: e
       logical name: veth3a84351
       serial: 7a:15:b4:ea:0f:aa
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:14
       description: Ethernet interface
       physical id: f
       logical name: veth54ad540
       serial: 12:9d:89:ee:ac:60
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:15
       description: Ethernet interface
       physical id: 10
       logical name: vethd423a83
       serial: 06:e4:7f:10:12:e0
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s

**Comment by andryyy** [comment]
Can you try to run `docker-compose down; docker rm -f $(docker ps -a -q); systemctl restart docker; docker-compose up -d`?

**Comment by mobeustech** [comment]
Ran that but still have the same issue.

**Comment by andryyy** [comment]
I have a few mins left... you can send me access to AnyDesk or similar to info@servercow.de

**Comment by mobeustech** [comment]
Would direct ssh access work for now?



            /Joshua

[/Users/joshua/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_180851548]

Joshua Hopkins
O: 719.425.8920 | M: 719.209.1414
joshua@mobeustech.com<mailto:joshua@mobeustech.com>

**Comment by andryyy** [comment]
WOLogFile was set to "/var/log/sogo_log" or something like that. This would have saved me so much time if someone just had told me. :-P
