### ISSUE TITLE
Implement SRS to Postfix for forwarded email

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#110]
Well lately I've been using Mailcow as principal mail server for my domains, I've encountered in a problem with Gmail specifically when I'm using forwarding filters for my accounts to a Gmail account.

Gmail keep denying my emails with this error:

`postfix-mailcow_1 | Mar  9 23:49:47 server postfix/smtp[188]: 4DF2621C2B: host gmail-smtp-in.l.google.com[74.125.22.27] said: 421-4.7.0 [XXX.XXX.XXX.XXX 15] Our system has detected an unusual rate of 421-4.7.0 unsolicited mail originating from your IP address. To protect our 421-4.7.0 users from spam, mail sent from your IP address has been temporarily 421-4.7.0 rate limited. Please visit 421-4.7.0  https://support.google.com/mail/?p=UnsolicitedRateLimitError to 421 4.7.0 review our Bulk Email Senders Guidelines. n88si6829780qtd.62 - gsmtp (in reply to end of DATA command)`

After a research I found that the problem is SPF usage in other domains, that being said, I've found a solution and is implement **SRS** (Sending Rewriting Scheme) to rewrite the sender email address for forwarded email to another email server (Gmail in this case)
You can find more about this at: [http://www.openspf.org/SRS](http://www.openspf.org/SRS)

Also I've found how to implement to Postfix the following repository has it flaws but it worth look at it:
PostSRSd - [https://github.com/roehling/postsrsd/](https://github.com/roehling/postsrsd/)

I don't know if this is **REALLY** necessary to implement and is not that demanding for all the community, is just a _slight_ problem that I found.

Cheers.

**Comment by andryyy** [comment]
Naah, this is just a rate limit.

**Comment by andryyy** [comment]
Were you able to fix it? :-)

**Comment by axd** [comment]
No, it still the same. :-( I have to setup another machine to test this I don't want to screw things on my production environment.

**Comment by madbence** [comment]
i've tried SRS on my server (with a custom smtp server), and it was really bad, almost every incoming email was flagged as spam :crying_cat_face: (despite the fact that all of them passed SPF), so i guess keeping the original envelope sender is fine (but indeed SPF checks will fail).
