### ISSUE TITLE
warnings in postfix log

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1100]
I found some warnings in the log, after the update from today:

`warning: group or other writable: /opt/postfix/conf/./postscreen_access.cidr`
`warning: group or other writable: /opt/postfix/conf/./smtp_dsn_filter`
`warning: group or other writable: /opt/postfix/conf/.`
`warning: not owned by root: /opt/postfix/conf/./postscreen_access.cidr`
`warning: not owned by root: /opt/postfix/conf/./smtp_dsn_filter`
`warning: not owned by root: /opt/postfix/conf/.`

Something i can do or i have to worry about?

**Comment by fairlygood** [comment]
I have the same.

**Comment by mkuron** [comment]
That’s fine, you can ignore the warnings. If you want to get rid of these messages, you can `chown` and `chmod` the files in data/conf/postfix accordingly. That is the directory that is mounted to /opt/postfix/conf in the container.
