### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by KarstenHahn** [mailcow/mailcow-dockerized#1102]
Hi,

I've started the update.sh script (not-customized installation). After updating the update script and restart update.sh. errors appeared (pulls failed)

While starting docker-compose up (without -d) a compilation task (!!!) was started. I've never seen this on previus updates.

To analyse it: what logs do you need? I'm not a docker guru so it is the best to guilde me through the necessary commands.

Thanks, Karsten

**Comment by Daniel133** [comment]
Also i can`t login through imap or pop3 after self building the missing images:

```
imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.11, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
```

**Comment by MAGICCC** [comment]
@KarstenHahn What errors appeared? Can you get use a dump of `docker-compose logs`?

@Daniel133 Which missing images? Best thing is to create a new issue and dont hijack another one!

**Comment by roswitina** [comment]
ERROR: for dovecot-mailcow  manifest for mailcow/dovecot:1.23 not found
ERROR: for clamd-mailcow  manifest for mailcow/clamd:1.9 not found
ERROR: manifest for mailcow/dovecot:1.23 not found
manifest for mailcow/clamd:1.9 not found

**Comment by andryyy** [comment]
It works now.

**Comment by roswitina** [comment]
thats all after update.sh

```
root@mailcow:/opt/mailcow-dockerized# ./update.sh
Checking internet connection... OK
Checking for newer update script...
From https://github.com/mailcow/mailcow-dockerized
 * branch            master     -> FETCH_HEAD
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Stopping mailcow...
Removing network mailcowdockerized_mailcow-network
WARNING: Network mailcowdockerized_mailcow-network not found.
Committing current status...
root@mailcow:/opt/mailcow-dockerized#
```

**Comment by MAGICCC** [comment]
Try to start the containers again and rerun the update script.

**Comment by roswitina** [comment]
after docker-compose up -d the system run.
after ./update.sh

```
./update.sh
Checking internet connection... OK
Checking for newer update script...
From https://github.com/mailcow/mailcow-dockerized
 * branch            master     -> FETCH_HEAD
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Stopping mailcow...
Stopping mailcowdockerized_rspamd-mailcow_1    ... done
Stopping mailcowdockerized_acme-mailcow_1      ... done
Stopping mailcowdockerized_netfilter-mailcow_1 ... done
Stopping mailcowdockerized_nginx-mailcow_1     ... done
Stopping mailcowdockerized_php-fpm-mailcow_1   ... done
Stopping mailcowdockerized_portainer-mailcow_1 ... done
Stopping mailcowdockerized_postfix-mailcow_1   ... done
Stopping mailcowdockerized_watchdog-mailcow_1  ... done
Stopping mailcowdockerized_memcached-mailcow_1 ... done
Stopping mailcowdockerized_clamd-mailcow_1     ... done
Stopping mailcowdockerized_ipv6nat_1           ... done
Stopping mailcowdockerized_dockerapi-mailcow_1 ... done
Stopping mailcowdockerized_mysql-mailcow_1     ... done
Stopping mailcowdockerized_sogo-mailcow_1      ... done
Stopping mailcowdockerized_redis-mailcow_1     ... done
Stopping mailcowdockerized_unbound-mailcow_1   ... done
Stopping mailcowdockerized_dovecot-mailcow_1   ... done
Removing mailcowdockerized_rspamd-mailcow_1    ... done
Removing mailcowdockerized_acme-mailcow_1      ... done
Removing mailcowdockerized_netfilter-mailcow_1 ... done
Removing mailcowdockerized_nginx-mailcow_1     ... done
Removing mailcowdockerized_php-fpm-mailcow_1   ... done
Removing mailcowdockerized_portainer-mailcow_1 ... done
Removing mailcowdockerized_postfix-mailcow_1   ... done
Removing mailcowdockerized_watchdog-mailcow_1  ... done
Removing mailcowdockerized_memcached-mailcow_1 ... done
Removing mailcowdockerized_clamd-mailcow_1     ... done
Removing mailcowdockerized_ipv6nat_1           ... done
Removing mailcowdockerized_dockerapi-mailcow_1 ... done
Removing mailcowdockerized_mysql-mailcow_1     ... done
Removing mailcowdockerized_sogo-mailcow_1      ... done
Removing mailcowdockerized_redis-mailcow_1     ... done
Removing mailcowdockerized_unbound-mailcow_1   ... done
Removing mailcowdockerized_dovecot-mailcow_1   ... done
Removing network mailcowdockerized_mailcow-network
Committing current status...
root@mailcow:/opt/mailcow-dockerized#
```

**Comment by andryyy** [comment]
Why would it quit after `Committing current status...`? Seems more like your system is broken.

**Comment by MAGICCC** [comment]
Should be fixed in https://github.com/mailcow/mailcow-dockerized/commit/ce7643b3adf5f465bca19ea31dd0e56da73554b2

**Comment by andryyy** [comment]
Yes, sorry.

**Comment by KarstenHahn** [comment]
Hmm. Setup a new instance (debian 9) according to the install docs with that result:

[e2.txt](https://github.com/mailcow/mailcow-dockerized/files/1768545/e2.txt)

Have you any ideas? Thx, Karsten

**Comment by andryyy** [comment]
Why is that? Did you run docker-compose up without a `-d`?

**Comment by andryyy** [comment]
Can you please run `docker-compose down; systemctl restart docker; ./update.sh`? 👍

**Comment by KarstenHahn** [comment]
@andryyy : no, docker-compose logs>e2.txt

just done the update.sh.

It seems that the mail-server is started somehow -- Thinderbird gives an certificate error because it is accessing with the "old" credentials. But i can't access the admin UI. And so I can not configure the system.

In the logs I found these error msgs:
nginx-mailcow_1      | nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/28 19:44:54 [emerg] 10#10: could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/28 19:44:55 [emerg] 10#10: could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/28 19:44:57 [emerg] 10#10: could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/28 19:45:00 [emerg] 10#10: could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed

Can this be a hint?

Karsten
