### ISSUE TITLE
Possible error in generate_config.sh

### ISSUE THREAD

**Issue by C78dev** [mailcow/mailcow-dockerized#1105]
When trying a fresh installation

[~/mailcow-dockerized]#:./generate_config.sh
./generate_config.sh: Zeile 3: +#exit: Kommando nicht gefunden.
./generate_config.sh: Zeile 4: +set: Kommando nicht gefunden.
./generate_config.sh: Zeile 5: +set: Kommando nicht gefunden.

cat generate_config.sh
#!/bin/bash

+#exit on error and pipefail
+set -o errexit
+set -o pipefail

if grep --help 2>&1 | grep -q -i "busybox"; then
....................

Solution 
Remove the +

Or am i wrong?
Thanks!

**Comment by andryyy** [comment]
Fixed with 450c0e936dec88529e965f0272d3884be35a06bf, thanks!
