### ISSUE TITLE
Forward and vacation auto reply incomming new mail from Sync Jobs (mailcow SoGo)

### ISSUE THREAD

**Issue by MailTw** [mailcow/mailcow-dockerized#1109]
Hello,
from internal mailboxes the auto reply and forwarding by new Emails works. (settings in SoGo Webinterface).
With a sync job to an internal mailbox with a new email no forwarding and no auto reply works.
Is there a possibility to use the function even with a sync job ?
Where can I adjust this ?

Thank you,
Tobias

**Comment by mkuron** [comment]
Duplicate of #220.
