### ISSUE TITLE
warning: TLS library problem

### ISSUE THREAD

**Issue by Tim-Rambo** [mailcow/mailcow-dockerized#1110]
2/28/2018, 9:05:54 PM | info | disconnect from unknown[***********] commands=0/0
-- | -- | --
2/28/2018, 9:05:54 PM | info | lost connection after CONNECT from unknown[***********]
2/28/2018, 9:05:54 PM | warning | warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:

**Comment by andryyy** [comment]
More info?

It is possible you connect to port 587 with SSL or 465 with a plain-text connection. Or your client is just very old. These lines do not tell us anything.

**Comment by tkorves** [comment]
As I'm currently doing a lot of SSL-Foo for a customer of mine, I can tell you for sure, it's a problem with the client's library... I'd suggest to close this issue.

**Comment by Tim-Rambo** [comment]
@andryyy do u have an suggestion on how i can give u more info ?

i am trying to setup an mailserver for my MyBB forum.

i am currently trying to setup SMTP
and mybb wont connect to mailcow at all 


when i change between TLS or SSL with 587 and 465 i get this error from mailcow


warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:

and that blocks mybb to connect to mailcow too. i can send and recive mails with mailcow.

and mailcow was installed yesterday.

**Comment by euantorano** [comment]
Hi,

The logs above are from trying to use [MyBB](https://github.com/mybb/mybb) with Mailcow. I've been trying to help @ConflictKingdoms get MyBB to talk with his mail server.

He's tried using the following settings:

- Port 25 with no encryption
- Port 465 with SSL encryption
- Port 587 with STARTTLS encryption

The client is obviously PHP, though I don't know which version is installed on the server.

**Comment by andryyy** [comment]
Is this instance still using a self-signed certificate (mail.example.org) on these ports?

Logs from MyBB would be

**Comment by Tim-Rambo** [comment]
@andryyy i dont know

in this case how do i change that ? 

so i can double check bcs i am unsure

**Comment by andryyy** [comment]
You can mail me your hostname for example. There are many ways to check that. What about the BB logs?

**Comment by Tim-Rambo** [comment]
@andryyy ive alrady talked to BB support wich is @euantorano he is the 1 that knows my BB logs and he said it was mailcows fault wich at the begining of this issue is the log from mailcow.......

ive sendt u an email

**Comment by andryyy** [comment]
What the ... ?

Your snippet is a common issue when a client fucks up initiating a TLS connection. I think you most likely use a self-signed certificate, which seems not to be supported by MyBB (I understand that).

Nice to hear @euantorano knows your logs. They may hold information about the failing handshake. This can also be debugged by setting `smtpd -v` in master.cf.

**Comment by Tim-Rambo** [comment]
@andryyy idk why u want this tho. http://prntscr.com/ilgwyl

@euantorano is 1 of the maker of MyBB XD

contacted them tested everything he said and found logs on mailcow and went here with that error from mailcow

and i am not that used to linux either so yeah....

**Comment by mritzmann** [comment]
test your sever with: http://www.checktls.com/perl/TestReceiver.pl

Is everything green there?

**Comment by andryyy** [comment]
So it is not possible for MyBB to fail on a TLS handshake because he is the creator of MyBB? If you don't want to provide any useful information, please close this issue. We want to help you, but you started by posting a failed handshake without **any** further information.

Check your FQDN, you sent me a domain name name. The script says "example.com is NOT a FQDN". You may have used a domain name and you may still use the snake-oil cert.

**Comment by ConflictKingdoms** [comment]
@andryyy i said i sendt u an email like 22min ago.

**Comment by andryyy** [comment]
Check my comment above, it is a domain name, not a FQDN. You need to change that and restart the stack.

**Comment by Tim-Rambo** [comment]
@andryyy i ment to delete that comment. but somehow github on my side pooped itself.

ok so where do i get FQDN ?

i am noob to all this stuff. trying 

and when i placed FQDN i did do my domain name yes.

**Comment by tkorves** [comment]
@ConflictKingdoms You don't know what a FQDN is? Ok buddy, I'd suggest to NOT run a mailserver nor any other server on the Internet...

**Comment by Tim-Rambo** [comment]
@tkorves there is no point being rude.....

**Comment by Tim-Rambo** [comment]
just trying to get help here.

**Comment by tkorves** [comment]
@ConflictKingdoms You can get help for issues related to these software stack - but there are no issues at all with it ... It's either your or your software you're trying to use causing these issues - running a server on the Internet, which is providing services, can be a severe problem to all of us, if the administrator doesn't know what he's doing. Sorry, this isn't rude at all - this is the truth.

**Comment by Tim-Rambo** [comment]
@tkorves he aint my adminstator....

i am the adminstrator of my own stuff and yes i am a beginner and dosent know shit about linux etc.

but 1 way i need to either figure shit out or contact ppl that probably want to help.

i asked mybb support first bcs might been an error there but ive checked mailcow log and there was an error there.

after 2 days straight up talking to @euantorano wich is one of the creator of MyBB tried to help me.
he told me to go here to get support with mailcow.

and 1 place u gotta start to know everything. 1 month ago i didnt know shit about linux but with threads here and there and some help from ppl ik they helped.

even my dev hasent touched this before....

so i checked up FQDN (Fully Qualified Domain Name)

i am just trying to get pushed into the right direction maybe i did do something wrong. but again u gotta fail and test etc to know shit....


and ppl dont know stuff straigh away either u gotta learn from somewhere....

and even i dont know what it is its better off telling me and get me in the right direction instead of just telling me basicly dont host anything on the internet....

**Comment by tkorves** [comment]
No one says, you need to know everything up front - but I'm saying (from a dozen of years of experience): Don't run a server which is publicly accessible on the Internet as a beginner... Try to learn with some old hardware on your local network.

But: We are unable to provide that basic level of support - if you're eager to use such a software stack like mailcow, you need to have the minimum basic knowledge on how to run a server - and FQDN (e.g.) isn't a Linux-specific abbreviation ... Are you aware of the things, which can happen if you're running a server without knowledge? It can range up to legal probems for you - and I'm not someone who paints everything black ... ;-)

**Comment by Tim-Rambo** [comment]
ok since u telling me to not host or touch mailcow whats ur recommendation for me to get a mailserver for my forum then ? @tkorves

**Comment by tkorves** [comment]
Get an account at https://hosted.mailcow.de/

**Comment by Tim-Rambo** [comment]
recommendations wich is free plz i dont have $$$ for everything in the world... i have money for my machine and thats about it. and i am not from germany either and didnt see a language changer either @tkorves 

idk if it was monthly or wut :/
