### ISSUE TITLE
sogo blue

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1111]
Just updated the mailcow and found a blue default theme in sogo. People are different and i like the old green. Blue is to dark and the contrast between the sogo logo and text is bad. So i changed the config in sogo.conf back to green. Would be nice if green could stay in future, because i read something in the repo about red, but this comment was at the green file. And perhaps it could be set over the ui and not the text file?

**Comment by andryyy** [comment]
So i changed the config in sogo.conf back to green. 

How? :-) You need to comment out `SOGoUIAdditionalJSFiles` to disable the theme. But I guess it just defaults to "sogo-green" when you set it to anything but blue or green. "theme-green" is btw. a non-default green. I will add more colors soon... 

The logo is meant to be very light, that's intended. You can replace `data/Dockerfiles/sogo/sogo-full.svg` and run `docker-compose build sogo-mailcow`.

**Comment by lgusewski** [comment]
I searched the repository for the changed files in sogo and found data/conf/sogo/sogo.conf the the line `SOGoUIAdditionalJSFiles = (js/theme-blue.js);`
So i changed this line to
`SOGoUIAdditionalJSFiles = (js/theme-green.js);`
and restart sogo over the mailcow admin UI.
Looks much better.

**Comment by andryyy** [comment]
Ah, I see. 👍 You can comment it out like `//SOGoUIAdditionalJSFiles = bla` to reset it.
