### ISSUE TITLE
Fresh installation fails

### ISSUE THREAD

**Issue by KarstenHahn** [mailcow/mailcow-dockerized#1112]
Hi,

after blowing up my last installation I decided to re-install the server starting with a fresh debian 9

installation as described brings no errors. But: I cannot access the web-console.

a docker-compose logs brings that:

[logs.txt](https://github.com/mailcow/mailcow-dockerized/files/1768972/logs.txt)

a docker-compose top brings that:

[top.txt](https://github.com/mailcow/mailcow-dockerized/files/1768979/top.txt)

I've got no idea to deal with the last error msg: Container ... is restarting....

Have you got a hint?

Thanks a lot, Karsten

**Comment by andryyy** [comment]
I wonder why it complains about map_hash_bucket_size. But you can try to set it to 128... like this:

```
nano data/conf/nginx/000-map-size.conf
```

Add this:
```
map_hash_max_size 256;
map_hash_bucket_size 256;
```

Restart the stack or Nginx afterwards.

**Comment by andryyy** [comment]
I edited my comment above, can you try it?

**Comment by KarstenHahn** [comment]
Thats it. Thx. 

the file 000-map-size.conf doesn't exist in my installation, I've created it. 

So hopefully I can restore my backup :-)

Thanks a lot for this wonderful project!

Karsten

**Comment by andryyy** [comment]
Strange you needed that line. Could be added as default, thanks.
