### ISSUE TITLE
MariaDB errors after upgrade

### ISSUE THREAD

**Issue by FrontLetter-IO** [mailcow/mailcow-dockerized#1113]
I just upgraded my Mailcow instance to the latest version with the upgrade script.
But my MariaDB instance isn't working anymore. 

I'm receiving this error:

> Database initialisation failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-mail.api DROP FOREIGN KEY fk_username_api' at line 1

**Comment by andryyy** [comment]
Near 'mail.api'? We don't have such a line in init_db.

Try `git checkout origin/master data/web/inc/init_db.inc.php`

**Comment by FrontLetter-IO** [comment]
I found the problem. My database name was 'FrontLetter-mail', so the error that I received told me that the `-` in the name was wrong (It worked in the previous version). I changed the database name and now is everything working.

**Comment by andryyy** [comment]
I see, thanks for letting us know.

**Comment by Braintelligence** [comment]
> 
> 
> Near 'mail.api'? We don't have such a line in init_db.
> 
> Try `git checkout origin/master data/web/inc/init_db.inc.php`

Thanks, this helped me with an error that kept showing up on the main login page 👍

**Comment by andryyy** [comment]
Strange. :-) You could also try "git pull" to see if it failed to merge some other files, too. But create a backup first.

**Comment by Braintelligence** [comment]
I always use the update.sh but for some reason I kept getting this error (without any consequences) on the main front page for about a year now, I think. Just tried this out and it helped 👍
