### ISSUE TITLE
some email error with "Host or domain name not found" 

### ISSUE THREAD

**Issue by changchichung** [mailcow/mailcow-dockerized#1115]
I setup a mailcow as my mail server for several days , everything works find.
But mail to specific domain will be deferred due to "Host or domain name not found"
not every , but some of specific domains.

please help how to solve that problem ?

**Comment by MAGICCC** [comment]
Do you use the dockerized version or not? You don't need to open the same issue [here](https://github.com/mailcow/mailcow/issues/931) when it's the wrong repo!
Can you paste us some logs of the issue?

**Comment by changchichung** [comment]
I`m sorry , I solve this proble by replace the dns setting in docker-compose.yml 
change 
```
dns:
  - ${IPV4_NETWORK:-172.22.1}.254
```
to 
```
dns:
  - 8.8.8.8
  - 8.8.4.4
```
and problem solved.

**Comment by Braintelligence** [comment]
It's strange if you had problems because of this. Other than that I'd rather recommend Quad9 than Google.

**Comment by mkuron** [comment]
Probably a duplicate of #850,  #817 and #85. the last one also tells you why you should always use mailcow‘s DNS recursor. @changchichung's workaround is fine for testing, but does not fix the underlying issue.

**Comment by aureq** [comment]
@changchichung Maybe look at https://github.com/mailcow/mailcow-dockerized/issues/850#issuecomment-561572912
