### ISSUE TITLE
rspamd "history" not showing behind nginx reverse proxy

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#1116]
Rspamd "History" cannot be seen when running mailcow behind a reverse proxy. Displaying of "Errors" works, though. History shows as expected without rp.

This is the error message:

> Cannot receive data from mail.example.com: SyntaxError: JSON.parse: unterminated string literal at line 1 column 434518 of the JSON data

**Comment by mritzmann** [comment]
I have the same Problem.

Error Message on History of https://mail.example1.com/rspamd/:

```
Cannot receive data from mail.example1.com: SyntaxError: JSON.parse: unterminated string literal at line 1 column 310083 of the JSON data
```

On another host with the same setting (nginx reverse proxy) it works without problems.

**Comment by mritzmann** [comment]
Re-tested this morning: And it works again. I haven't changed anything. No restart either. Next time I will test with SSH Port forwarding to see if it will work without a reverse proxy.

```
ssh -L localhost:8080:127.0.0.1:8080 mail.example1.com
```

**Comment by chaosbunker** [comment]
Still not working for me after updating mailcow

**Comment by mritzmann** [comment]
I had the same problem this morning.

With Mozilla Firefox:

```
Cannot receive data from localhost:8080: SyntaxError: JSON.parse: unterminated string at line 1 column 464563 of the JSON data
```
![screenshot from 2018-04-13 09-36-50](https://user-images.githubusercontent.com/4533780/38722502-62d9b12c-3efe-11e8-92c5-7721833b9d5a.png)

With Google Chrome:

```
Cannot receive data from mail.rtpmail.ch: SyntaxError: Unexpected end of JSON input
```

Tested it with SSH port forwarding:

```
ssh -L localhost:8080:127.0.0.1:8080 mail.example1.com
```

Same problem, though. So it's not the nginx reversy proxy.

**Comment by mritzmann** [comment]
![rspamd01](https://user-images.githubusercontent.com/4533780/38722134-32a87f0c-3efd-11e8-9ad1-e78746a0a28d.png)
And in server log:

```
Apr 13 09:29:16 localhost.localdomain 3a72233d4453[1843]: 2018-04-13 07:29:16 #9(controller) <53af19>; csession; rspamd_controller_check_password: absent password has been specified
Apr 13 09:29:16 localhost.localdomain f75087ce3f20[1843]: 85.195.242.220 - - [13/Apr/2018:07:29:16 +0000] "GET /rspamd/history HTTP/1.0" 403 24 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
```

**Comment by cklabautermann** [comment]
apache2 repro works, though....

`
<VirtualHost *:80>
  ServerName mail.example.org
  RedirectPermanent / https://mail.example.org/
</VirtualHost>
<VirtualHost *:443>
         ServerName mail.example.org
         ServerAlias autodiscover.example.org
         ServerAlias autoconfig.example.org
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/

    ProxyPreserveHost On
    ProxyAddHeaders On
        SSLEngine On
        SSLCertificateFile /opt/mailcow-dockerized/data/assets/ssl/acme/cert.pem
        SSLCertificateKeyFile /opt/mailcow-dockerized/data/assets/ssl/acme/private/privkey.pem
        SSLCertificateChainFile /opt/mailcow-dockerized/data/assets/ssl/acme/chain.pem



SSLProtocol             all -SSLv2 -SSLv3
SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
SSLHonorCipherOrder     on
SSLCompression          off

SSLOptions +StrictRequire

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common

</VirtualHost>
`

**Comment by mritzmann** [comment]
Possibly a problem with the reverse proxy of mailcow itself? As I said, it has nothing to do with my reverse proxy before it.
