### ISSUE TITLE
ailcowdockerized_postfix-mailcow_1 address already in use

### ISSUE THREAD

**Issue by GYJohn** [mailcow/mailcow-dockerized#1119]
Hello i try to install mailcow docker on a stretch debian.
The error says the adress is already in use. But i already tryed to reboot, same proble. Postfix wont start.

Any ideas?

Thank you!

`ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (93ef9e71deaa0adbe017d276f3cbcb401d2f137ed968bcb48ae95b1987f0da73): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use
`

**Comment by tkorves** [comment]
@GYJohn, can you please issue a "netstat -tulpen" as root on your server and paste all lines returned? Thanks.

**Comment by GYJohn** [comment]
@tkorves 

I fixxed it by:

https://github.com/mailcow/mailcow-dockerized/issues/63

But i got a other problem.
When i set a new admin password, it jumps back to admin.php and the password is not set.

**Comment by tkorves** [comment]
Do you run mailcow behind another reverse proxy? Or have you installed any plugins in your local browser which prevent stuff run on websites?

**Comment by GYJohn** [comment]
@tkorves 

Okey now i feel rly stupid.
IE works...
Thank you!

But what da hack.. I only got adblocker on Firefox..

**Comment by tkorves** [comment]
This could be the problem - will check this.

Which version of FF are you running on which OS? Which adblocker are you using?

**Comment by GYJohn** [comment]
FF 58.0.0.2  on Win10 with Adblock Plus

**Comment by tkorves** [comment]
Ok, this is something I can try - please standby ...

**Comment by GYJohn** [comment]
After around 15minutes i cant access viva browser anymore.
How can i check if nginx container is running?

Okey. I am out.
The mailcow without docker was good. 

Now i can access the wi again.. Without any configuration.

**Comment by tkorves** [comment]
docker-compose ps

**Comment by GYJohn** [comment]
Thanks.
Since i am running the docker mailcow i get so many timeouts. Sometimes 10-15 minutes.
I am really confused

**Comment by tkorves** [comment]
We're running mailcow-dockerized in a productive environment without any bigger issues.

Timeouts are giving a hint to look at your connection (the path, the packets traverse) between you and your server (which runs mailcow).

**Comment by andryyy** [comment]
Timeouts where? No logs, no support. :-(

**Comment by andryyy** [comment]
Is watchdog restarting any container? Does SOGo timeout?

**Comment by GYJohn** [comment]
The hole server is timing out. Before i installed the dockerized mailcow, it works fine(with mailcow)
Maybe 1 gb ram is really too little

**Comment by tkorves** [comment]
1GB RAM is far off what's even "normal" for server-usage... Sorry, but this isn't a mailcow problem itself - therefor closing this ticket.

**Comment by GYJohn** [comment]
RAM | 1 GiB (or better 1,5 GiB + Swap)
Then maybe correct the documentation to 1,5 not 1.

**Comment by Braintelligence** [comment]
I guess 1GB is not enough if you also run ClamAV. I think the hardware recommendations were made before ClamAV was integrated.

**Comment by MAGICCC** [comment]
@Braintelligence @GYJohn Actually the docs are mentioning 1,5GB for min. RAM and disabling ClamAV in the mailcow.conf
