### ISSUE TITLE
error when adjust the rspamd threshold

### ISSUE THREAD

**Issue by changchichung** [mailcow/mailcow-dockerized#1122]
some of email were "soft reject" due to greylist.
there`s a post about greylist mention that we could change the threshold in rspamd.
so i go to the rspamd configuration and change the greylist value to 10 and click save changes
then there`s a error messages "Syntax Error" 
![](https://i.imgur.com/zG8LlBG.png)

any suggestions ?

**Comment by andryyy** [comment]
Reverse proxy?

**Comment by changchichung** [comment]
I`m not sure what you mean ?
I have no setup any reverse proxy outside the docker ..
