### ISSUE TITLE
Missing perl module for qshape 

### ISSUE THREAD

**Issue by jpramming** [mailcow/mailcow-dockerized#1123]
I was trying to use the Postfix qshape command, but it failed because of a missing Perl module.

``# qshape``

``Can't locate File/Find.pm in @INC (you may need to install the File::Find module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/sbin/qshape line 114.
BEGIN failed--compilation aborted at /usr/sbin/qshape line 114.``

I could install this for my own installation, but am I the only one missing this command, or should I make an effort to include the module in Mailcow?

**Comment by mkuron** [comment]
Since everyone is using the same Docker images, the situation will be the same for everyone. I don‘t know what qshape does, but if it is useful in any way, please feel free to submit a pull request to add that Perl module.

**Comment by jpramming** [comment]
It's a tool for showing queue depth and age, which at least I find usefull.
I'll investigate and submit a PR if possible.

**Comment by jpramming** [comment]
The missing module is part of a standard Perl installation, and the package should not be referenced directly.
Therefore, I have added PR #1128 to include full Perl installation, and not just perl-base.
