### ISSUE TITLE
Master user and password

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#1127]
Hello,

It would be nice to have a section in Web UI to create dovecot master user and password, to use it for debugging user mailboxes.

**Comment by apintocr** [comment]
Actually I believe this is useful.

However it can easily get in front of privacy issues of your users and I'm not sure if that is good.

Specially with GDPR coming soon.

**Comment by reinistihovs** [comment]
The feature is already there, and it is already used by mailcow to do syncjobs.
So this is a GDPR violation already.
All relies on trust to your IT admin :)

**Comment by andryyy** [comment]
It is not like you could use doveadm to read their mails anyway. :-P

```
docker-compose exec dovecot-mailcow cat /etc/sogo/sieve.creds
```

**Comment by reinistihovs** [comment]
I use master user in these cases: 
1) If i want to migrate a mailbox from another mailserver with imapsync
2) If a employee forgets to set up Vocation filter, and is unreachable by phone, and Company CEO requests it.


@andryyy 
Thanks!  This works, but not for SOGo :(
Made a research and found out that SOGo doesnt support master user logins, and they wont change this.

**Comment by zawadaa** [comment]
> It is not like you could use doveadm to read their mails anyway. :-P
> 
> ```
> docker-compose exec dovecot-mailcow cat /etc/sogo/sieve.creds
> ```

Put this into documentation, please.
