### ISSUE TITLE
I installed mailcow-dockerized, but I have got a few questions

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#113]
Hi,

I have got successful install mailcow-dockerized.

It works fine
[](url)
But I have got a question to let's encrypt.
I used the tutorial from [here](https://andryyy.github.io/mailcow-dockerized/first_steps/#obtain-multi-san-certificate-by-lets-encrypt) ....
... OK
What is post-hook in a script?

Is this a shell-script for a cronjob?

Will the let's encrypt certificate automatically renewed?

Regards
jm3west

**Comment by broedli** [comment]
The documentation only shows you one way of acquiring a certificate from Let's Encrypt with certbot. It doesn't cover any mechanics beyond that. For a better understanding on how to use certbot please consult the [documentation](https://certbot.eff.org/docs/using.html) of certbot. 

What is a `--post-hook`? - https://certbot.eff.org/docs/using.html#renewing-certificates

**Comment by broedli** [comment]
Since we have not heard back from you, I assume that you resolved your Issue. 
Please feel free to reopen with I'm mistaken.
