### ISSUE TITLE
Mailcow - NextCloud 13 - Security & setup warnings

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1130]
Good evening,

@andryyy 
Thank you for the updates within mailcow and the NextCloud helper-script.

I installed NextCloud using the helper-script.
Checking security & setup warnings i was faced with this error message:
"The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly."

How can i fix this error?

Feuernatter

**Comment by andryyy** [comment]
Hmm, I think I added it to data/conf/nginx/site.conf already. :-)

![grafik](https://user-images.githubusercontent.com/2972950/36921427-a0b373a8-1e64-11e8-841f-de47f1a61dea.png)

**Comment by ghost** [comment]
data/conf/nginx/site.conf ist exactly the same on my system.
But where does this error come from?

**Comment by ghost** [comment]
I found this [post](https://help.nextcloud.com/t/x-frame-options-sameorigin-nc-on-nginx-keeps-warning-me/1553).

The same problem ist mentioned here.
I'm currently working through it.

**Comment by andryyy** [comment]
Ah.. no. Damn. Sorry.

It is, depending on wether you installed as subfolder or subdomain installation, in data/conf/nginx/nextcloud.conf or data/conf/nginx/site.nextcloud.custom.

**Comment by ghost** [comment]
No problem :-)
I think this is quite tricky ...

**Comment by ghost** [comment]
data/conf/nginx/site.nextcloud.custom doesn't exist.
So i have to create this file with als existing lines in data/conf/nginx/nextcloud.conf

**Comment by andryyy** [comment]
No, it is a "either or". xy.custom exists for NC installations to a subdirectory, nextcloud.conf exists for installations as a subdomain.

You seem to use data/conf/nginx/nextcloud.conf, so you'll need to add that missing 'add_header' to this file and restart nginx-mailcow by running docker-compose restart nginx-mailcow.

**Comment by ghost** [comment]
Ok, but this 'add header' is part of data/conf/nginx/nextcloud.conf
If this is indeed a bug as mentioned before, i think i have to delete this 'add header'

**Comment by ghost** [comment]
I deleted the 'add header' and restarted nginx-mailcow.
... and - i don't believe it - the error has vanished.
Now i don't now if this is best-practice but it works for me now.

@andryyy 
What do you think about this?

**Comment by andryyy** [comment]
I will check this. :-)

**Comment by ghost** [comment]
If i understand this correctly 'add_header X-Frame-Options "SAMEORIGIN";' is inside data/conf/nginx/site.conf and so is defined system-wide.
As a matter of fact using this 'add header' twice causes the error within NextCloud.
This is the conclusion of the post i found an linked in one of my earlier comments.

**Comment by ghost** [comment]
@andryyy 
Is it possible to set this in nextcloud helper-script?

**Comment by andryyy** [comment]
No it is not set system-wide, it is a single site. It has to be set in the nextcloud.conf site as well. I tested it two times without warnings. Subfolder and subdirectory configurations are fine.

You can post a dump of your configuration for further help. I think it is a matter of old configs.

**Comment by andryyy** [comment]
It was _me_ having a custom config, sigh. Sorry. Fixed it.

**Comment by ghost** [comment]
No problem :-) 👍

**Comment by koshia** [comment]
So i have this exact problem, but i'm not finding where the reference is for the X-Frame-Options "SAMEORIGIN";' - that isn't commented out (that is, i've gone and commented out all of the ones I could find).    What was your final fix to get rid of the error?

**Comment by ghost** [comment]
Today I installed NextCloud as mentioned before.
The SAMEORIGIN-Error appears again.
Commenting out the SAMEORIGIN-Entry in data/conf/nginx/nextcloud.conf an restartin nginx-mailcow fixed it.
I don't think this is best-practice so how can this be fixed?

**Comment by andryyy** [comment]
Hm, can you please check the diff for the files when it worked and when it broke? Or just check the history of the files. I don’t have time to look into this right now.
