### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by HorayNarea** [mailcow/mailcow-dockerized#1131]
It would be nice to integrate prometheus-exporters for dovecot¹ and postfix² and maybe other containers too, so one can create a grafana dashboard for mailcow

Is there anything that speaks against it?

¹ https://github.com/kumina/dovecot_exporter
² https://github.com/kumina/postfix_exporter

**Comment by jpramming** [comment]
Sounds very interesting, but probably a feature that should exist outside/beside Mailcow. Or maybe as an optional docker container and not part of a default installation.

IMO, users will have very different requirements and available tools for monitoring their Mailcow instances. And it will be a hard job to to support them all.
However, with the use of Docker containers we have a very flexible solution, that makes it easy to implement such a feature in a separate container or at the host level.

The examples you have linked have some requirements which is currently not met by the installation, but could be used as inspiration going forward.
So one could look into implementing some examples for this in relation to Mailcow, and from there decide if it should be part of Mailcow.

BTW, I have just added Filebeat shipping of Docker logfiles to Elasticsearch and log visualization in Kibana. And I was planing on adding Grafana for metrics, if the Kibana dashboards aren't sufficient.
So I would very much be interested in a solution for this.
