### ISSUE TITLE
Can't access to rspamd after upgrade

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#1132]
Hi,

I just made the latest update and I'm not able to access to rspamd, it returns an error when introducing the password: "Forbidden".

Any idea about this?

Regards.

**Comment by ajcutshall** [comment]
In order for me to even be able to update with update.sh, I had to remove worker-controller-password.inc from %mailcow_dir%/data/conf/rspamd/override.d/ - It appears that this file contained a hash of the password I set for rspamd. Following the update, I noticed this same behavior. I used the mailcow webui to set the admin password for rspamd again, which corrected the issue.

**Comment by tbsbckr** [comment]
I have the same issue, after upgrading to the newest version it won't let me in anymore! Is there a fix to this problem? @andryyy

**Comment by andryyy** [comment]
Have you tried what @ajcutshall wrote?

**Comment by tbsbckr** [comment]
Yes I tried that, I removed the file and tried setting the password via the Web UI but only receive an "Unknown error".
A new file is create with the content "#Placeholder", that it's. I've also restarted the whole docker stack to eliminate any issues there.

Any other ideas?

**Comment by normanu** [comment]
Hi @andryyy I did a brand new install to migrate from 0.14 and also have the same issue.
On new installation a file is created with a password, setting a new password from webinterface doesn't do anything. (password from override file works)
Removing the file restarting rspamd places a #placeholder file after changing the password on the webinterface.
So in otherwords, setting a password through the webinterface doesn't seem to work.

**Comment by andryyy** [comment]
"Brand new" does not mean anything, there are a lot of things that can be messed up on your system - including file permissions. 

I just tested it and it works.

Deleting the file and restarting rspamd-mailcow _will_ recreate a placeholder file, sure. That's what it should do.

The fix I just pushed is not related to this problem. It just extracts the string from stdout as it can contain error messages since Rspamd 1.7.x.

**Comment by normanu** [comment]
Mmm for some strange reason after doing a new update it works here aswell.

As a side note, I'm running Alpinelinux as a host OS.
I installed coreutils and grep to replace the busybox versions. (cp & grep) 
I saw a error during update, for grep .... 
In any case now it works.

**Comment by axd** [comment]
What @ajcutshall said worked for me. :+1: I set a password using the webUI, the only issue that I've faced is that I have to do that every time I update mailcow.
