### ISSUE TITLE
After update nginx container always restarts

### ISSUE THREAD

**Issue by ulrich379** [mailcow/mailcow-dockerized#1133]
daemon log:
Mar  3 08:41:21 mx2 systemd-udevd[2679]: Could not generate persistent MAC address for vethf574359: No such file or directory
Mar  3 08:41:21 mx2 systemd-udevd[2680]: Could not generate persistent MAC address for veth57a8f76: No such file or directory
Mar  3 08:41:25 mx2 dockerd[665]: time="2018-03-03T08:41:25+01:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/eab85af2b60bc36495d916ba0f2ccdf73f13c98c5a6e409c18ea56a750ec4d13/shim.sock" debug=false module="containerd/tasks" pid=2728
Mar  3 08:41:28 mx2 dockerd[665]: time="2018-03-03T08:41:28+01:00" level=info msg="shim reaped" id=eab85af2b60bc36495d916ba0f2ccdf73f13c98c5a6e409c18ea56a750ec4d13 module="containerd/tasks"
Mar  3 08:41:28 mx2 dockerd[665]: time="2018-03-03T08:41:28.042347156+01:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

**Comment by tkorves** [comment]
Seems to be a Docker-related problem on your host and not a mailcow-wide issue. Have you proceeded with this? Or do you need additional assistance?

**Comment by Alireza2n** [comment]
Have you tried destroying and recreating the nginx container?
