### ISSUE TITLE
mailcow-dockerized doesn't renew ssl certificate

### ISSUE THREAD

**Issue by ravi0lii** [mailcow/mailcow-dockerized#1137]
Hello,
I am trying to renew my ssl certificate in mailcow-dockerized using `docker-compose restart acme-mailcow`. But when I run it the server crashes and the ssl certificates aren't renewed. I tried `docker-compose down && docker-compose up -d` to restart it but it doesn't work, too. Would be nice if someone can help me.

**Comment by lazyfrosch** [comment]
How about providing some logs:

    docker logs mailcowdockerized_acme-mailcow_1

**Comment by mattnotmitt** [comment]
```
❯ docker logs mailcowdockerized_acme-mailcow_1
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
/srv/docker-entrypoint.sh: line 6: log_f: command not found
```
This is the output I get, currently experiencing this issue.

**Comment by lazyfrosch** [comment]
`log_f` actually gets defined inside the same script, have you changed the container somehow?

https://github.com/mailcow/mailcow-dockerized/blob/182b7826bda9be94c0652c2ff2566e2fac75b220/data/Dockerfiles/acme/docker-entrypoint.sh#L5-L16
