### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by Keglerz** [mailcow/mailcow-dockerized#1139]
Hi all

I have an issue with the space requirement, wondering what is the requirement for running mailcow
I subscribed digitalocean with 25gb disk space but after a few days its always end up full. I've reinstalled twice with the same issue.
Anyone please advice
Thanks

**Comment by Braintelligence** [comment]
Are you removing old docker-containers after updating?

EDIT: And also doing apt-get autoremove?

**Comment by Keglerz** [comment]
I didn't remove old docker-containers

I just followed this 
https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by ghost** [comment]
Hello Keglerz,

if your disk space is runnig "out of space" try the following code within your mailcow folder:

`if docker images -f "dangling=true" | grep ago --quiet; then
  docker rmi -f $(docker images -f "dangling=true" -q)
fi`

This code deletes all old docker images that are not associates with runnig mailcow images.

I hope this will help you.

**Comment by ghost** [comment]
Thinking about this again:

You can also do a `docker system prune`.
But be aware that mailcow has to be running, since this command will delete:
        - all networks not used by at least one container
        - all dangling images
        - all build cache

**Comment by andryyy** [comment]
Yes, that will work. But it is really important to have mailcow running.

**Comment by lazyfrosch** [comment]
Here is an example for a cleanup that keeps named volumes intact: https://gist.github.com/lazyfrosch/030c10c444ff49aba86c62fac3c13cbb

**Comment by mkuron** [comment]
As long as you don‘t add the `--volumes` flag to `docker system prune`, no volumes (and thus none of your data) will ever be deleted. The worst thing that could happen (when Mailcow is not running) is that you need to rerun `docker-compose pull` to get the images again.

**Comment by tkorves** [comment]
Seems to be solved. Closing this issue.
