### ISSUE TITLE
SOGo v4 upcoming release

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#1140]
Hey @andryyy ,
just wanted to make sure you know about the upcoming SOGo v4 release!

From 2018-03-01:
```
Hello,

Early next week, we'll release SOGo v4. We've been working hard on this release for many months. Among some of important features of SOGo v4, there are:

    full S/MIME support for signing and encryption
    complete rework of the handling of recurrence exceptions
    performance optimizations of the Web GUI by creating AngularJS components
    many Enterprise ActiveSync improvements

We also made a gazillion of bug fixes and improvements.

Nightly builds of the upcoming v4 have been available since the beginning of the week - just replace /3/ by /4/ in the URL for the repositories while we update the website for the release.

Thanks!
```

**Comment by lgusewski** [comment]
My cow shows me version 4.0 201802270244 from sogo. I think he knows.

**Comment by Braintelligence** [comment]
@lgusewski Wait, really? There should be no stable v4 yet. Are you running nightlies?

**Comment by lgusewski** [comment]
I only use `sudo ./update.sh` in my installation and with the last merge of dev to master i got the new version.

**Comment by Braintelligence** [comment]
Excited to hear what @andryyy has to say about this 😸 . Are you using nightlies in the docker-containers?

**Comment by lgusewski** [comment]
Not conscious. I think that i only use every time the last official version of master branch.

**Comment by Braintelligence** [comment]
Does it look different to v3, though? Is UI/UX the same?

**Comment by lgusewski** [comment]
Did not see any difference. Only the new color scheme, andryyy adds. The info about the version is in in "i" in the login dialog.

**Comment by andryyy** [comment]
Yes, we are using nightly repositories.

Please consider supporting @extrafu and @cgx (or inverse.ca in general) for their great work, they offer support contracts. 👍

**Comment by Braintelligence** [comment]
@andryyy What would be an example use-case for support contracts in the context of mailcow?

**Comment by mkuron** [comment]
@Braintelligence, if you get a support contract from @inverse-inc, they help you if you run into trouble with SOGo and will quickly fix bugs that you report. It's their business model -- they need paying customers so that they can pay their developers.

**Comment by Braintelligence** [comment]
@mkuron I'll consider it as soon as I'll encounter problems with SOGo I can't fix myself. Up till now, other than groups requiring LDAP, I had no problems that either weren't already on the bugtracker being worked on or not solveable by myself.
