### ISSUE TITLE
Umlaute in Mail-Domains

### ISSUE THREAD

**Issue by ttjaden** [mailcow/mailcow-dockerized#1142]
Danke für die tolle Mailserver-Lösung. Es läuft bei mir einwandfrei, jedoch habe ich eine wichtige Frage:

Als ich eine zweite Domain in der Admin-Oberfläch angelegt habe, muste ich feststellen, dass Umlaute leider nicht übernommen werden. Aus "gröönlandhof.de" wurde "xn--grnlandhof-fcba.de"

Besteht irgendwie die Möglichkeit auch Domains mit Umlauten zu nutzen?

**Comment by MAGICCC** [comment]
Nein, da im normalen RFC Standart nur bestimmte ASCII Zeichen enthalten sein dürfen, gibts auch keine Umlaute. Seit es IDN gibt, wurde dies erweitert und man darf nun auch Umlaute, aber nur als ACE String, eingesetzen.
https://de.wikipedia.org/wiki/E-Mail-Adresse#Der_Dom%C3%A4nenteil_(Domain_Part)

**Comment by ttjaden** [comment]
Danke MAGICCC. Dort steht aber auch, dass die Mail-Programme lediglich das Codieren beherschen müssen, damit rein technisch der Versand und der Empfang funktionieren. Oder verstehe ich hier was falsch?

EDIT: Konnte erfolgreich eine Mail an user@gröönlandhof.de schicken. Problem ist, dass 
a) der Login in Sogo immer als user@xn--grnlandhof-fcba.de angegeben werden muss
b) der Absender auch so angezeigt wird. Dies kann man in den Einstellungen leider nicht auf @gröönlandhof.de anpassen

Wäre also klasse, wenn Mailcow eine Domainerstellung mit Umlauten (inkl. Absender und Login mit derselben) erlauben würde. Ist das möglich?

**Comment by MAGICCC** [comment]
Naja man könnte übers UI dies wieder in Umlaute usw. aufquirllen. Solange das Backend (Postfix/Dovecot usw) das als ACE String bekommt, sollte es möglich sein (wobei das Umzuwandeln die Aufgabe des MUAs ist afaik - also des Clients.

**Comment by ttjaden** [comment]
> Naja man könnte übers UI dies wieder in Umlaute usw. aufquirllen. Solange das Backend (Postfix/Dovecot usw) das als ACE String bekomme sollte es möglich sein

Dann wäre es grandios, wenn die Funktionalität Einzug in das Mailcow-Paket halten würde. An wen müsste ich mich mit der bitte konkret wenden? Wäre auch bereit eine Kleinigkeit dafür zu geben.

**Comment by Shadowghost** [comment]
Müsste in den Fall an Sogo liegen, wenn das alles Clientseitig zu einem ACE-String geparst werden muss. Also musst du dich da an die Sogo-Entwickler wenden.
Die Mailcow UI scheint die Domain ja anscheinend korrekt zu erstellen, zeigt dann aber eben den ACE-String, statt der eigentlich Domain mit Umlauten, das müsste sich dann @andryyy oder einer der andern mailcow-Devs anschauen.

**Comment by mkuron** [comment]
Postfix weiß nichts von Unicode, also ist es zumindest konsequent, dass das Admin-Interface die Domain so anzeigt, wie sie im System hinterlegt ist, als `xn--`.
Zum SOGo-Login gibt es schon einen Bugreport: https://sogo.nu/bugs/view.php?id=4261 . Es gibt jedoch kein RFC, das sagt, dass der Client den Usernamen kodieren muss, also verhält sich SOGo eigentlich korrekt. Dovecot wiederrum gibt den Usernamen unverändert an das Auth-Backend weiter — aber in einer SQL-Abfrage kann man die Kodierung auch nicht machen, deswegen können wir das Problem nicht beheben.

Zu dem Problem, dass der Absender immer kodiert angezeigt wird: da kannst du bei SOGo einen Bugreport öffnen.

Insgesamt kann man aber sagen: auch im Jahr 2018 passen Unicode und E-Mail nicht zusammen; keiner der Fehler liegt im Einflussbereich von Mailcow. Eine Unicode-Domain sollte man also daher als das betrachten, was sie technisch ist: eine ASCII-Domain mit `xn--` am Anfang. Die „schöne“ Variante mit echtem Umlaut ist für die Visitenkarte, wird aber nicht tatsächlich für die Kommunikation genutzt.

**Comment by ttjaden** [comment]
Danke für das gute Feedback. Dann müssen wir hier mal über einen neuen Namen nachdenken, denn groeoenlandhof sieht ja grauenhaft aus :-)

**Comment by mkuron** [comment]
Naja, für Werbung und Visitenkarte geht es schon mit Umlauten. Für den SOGo/Dovecot-Login finden wir vielleicht noch eine andere Lösung. Nur bei ausgehenden Mails ist es unschön.

Wie handhaben eigentlich Outlook und Thunderbird beim Verschicken Umlaute im Absender? Wird der To-Header in UTF-8 verschickt und der Envelope-Sender `xn--`-kodiert? Falls ja, könnte man bei SOGo ein Ticket erstellen, dass es sich auch so verhalten sollte.

**Comment by TheUltimateC0der** [comment]
Habt ihr schon eine Lösung gefunden ?

**Comment by ttjaden** [comment]
Hatte bei Sogo mal ein Ticket eröffnet, allerdings hatte sich dort leider niemand gemeldet. Daher nutzen wir Mailcow/Sogo nun einfach so, wie es aktuell funktioniert. Domain ist ohne Umlaute angelegt und zusätzlich gibt es einen Domain-Alias mit Umlauten.

**Comment by nbartels** [comment]
Auch wenn das Ticket schon ewig geschlossen ist, gibt es in SOGO inzwischen einen Weg eine Umlautdomäne als Login direkt zu verwenden. Die Punycode Repräsentation funktioniert natürlich, aber das kann man sich ja nicht wirklich merken. Wenn es Tipps gibt, wäre ich dankbar.
