### ISSUE TITLE
Mailcow as Backup MX fails after update

### ISSUE THREAD

**Issue by pgollor** [mailcow/mailcow-dockerized#1144]
I dont know if it's a problem from my server or from mailcow but this was happened:

I updated last week to the master brunch and everything seems to be fine. But after one week my backup mailserver did not receive any mails. After testing i get the following problem from the sender server:
`Temporary lookup failure`
That was a problem in `mysql_sender_dependent_default_transport_maps.cf`.
After that i deleted the `sql` directory in the postfix configuration folder and let the postfix container generate this files again. This solved the problem. A diff between the old and the new one shows:
```
diff ./mysql_sender_dependent_default_transport_maps.cf /tmp/sql/mysql_sender_dependent_default_transport_maps.cf
15c15
<         AND json_extract(attributes, '$.tls_enforce_out') LIKE '%%1%%'
---
>         AND mailbox.tls_enforce_out = '1'
diff ./mysql_tls_enforce_in_policy.cf /tmp/sql/mysql_tls_enforce_in_policy.cf
13c13
<       ) AND json_extract(attributes, '$.tls_enforce_in') LIKE '%%1%%' AND mailbox.active = '1'
---
>       ) AND mailbox.tls_enforce_in = '1' AND mailbox.active = '1'

```
In my opinion this is a problem from the updater Process. So a hint in the update help should be useful and maybe for future updates this have to be handled in the updater script?

**Comment by andryyy** [comment]
These files are generated automatically by the images/containers after a restart. The update process stops all containers, removes them and downloads new images to create new containers. I don't see how that's possible to happen with a default installation. :-/

Sounds like you run a manual update of the code without updating/crecreating the containers.

**Comment by pgollor** [comment]
Multiple restart (`down` and `up`) didn't worked. But this problem should be not interested for others.
You did a great work here thanks.
