### ISSUE TITLE
Rspamd errors in log: "couldnt increment reputation: NOSCRIPT No matching script. Please use EVAL."

### ISSUE THREAD

**Issue by Anima79** [mailcow/mailcow-dockerized#1147]
Hello,
it's me again with yet another problem after my migration from mailcow 0.14 to dockerized. My "error" tab in the rspamd UI throws at me the following line after every incoming (!) mail: 

`7.3.2018, 12:50:55 | normal | 16 | lua | 8d607b | couldnt increment reputation: NOSCRIPT No matching script. Please use EVAL.`

Steps undertaken so far: 
I completely wiped the rspamd and redis containers, also the jointed rspamd and redis volumes, and repulled and restarted everything afterwards. I also updated the "Symbols and Rules". Pitifully, the problems persists. 

My installation of mailcow dockerized is completely vanilla, except that it runs behind a proxying apache2. Last week I wrote about the strange "rrd-problem" sometimes showing up in the "Throughput"-page of the rspamd UI, but the two problems don't seem to be connected. 

Except these two problems, everything runs smooth and really fast. 

Thanks for your time and help!

Michael

**Comment by SvenWen** [comment]
I've got the same problem. The problem must have started somewhen within the last two days. Before that no issues in the log.

**Comment by Anima79** [comment]
No ideas anyone? The problem still clutters up my rspamd-logs ...

Thanks again,

Michael

**Comment by mkuron** [comment]
I can confirm this error message, but it seems to have no adverse effects. It is only supposed to be shown when a Redis connection is dropped, but it happens way too often for that.

**Comment by Anima79** [comment]
Thanks for your clarification, @Mkuron! Maybe it will be fixed in one of the upcoming updates.

Regards, Michael

**Comment by mkuron** [comment]
It's unlikely that we'll fix it, but maybe a future rspamd update will. You can file a bug report at https://github.com/vstakhov/rspamd if you like, but you would need to provide a minimal configuration that exhibits this issue so that the rspamd developer can reproduce it.

**Comment by Anima79** [comment]
Yes, I thought about a future update of rspamd, not of mailcow. I'll try a bug report at rspamd next week.

Thanks for your time,

Michael

**Comment by normanu** [comment]
Just as a note, I also have this issue ....

**Comment by andryyy** [comment]
Anyone reported this to Rspamd?

**Comment by mkuron** [comment]
No. https://github.com/vstakhov/rspamd/issues/1716 is the same issue, but supposedly fixed a year ago.

**Comment by normanu** [comment]
for me all rules work, it is only this one giving a exception.
2018-04-30 12:31:50 #10(normal) <8fdb5e>; lua; url_reputation.lua:120: couldnt increment reputation: NOSCRIPT No matching script. Please use EVAL.

**Comment by Anima79** [comment]
To be honest, I didn't report the issue back in March, since I didn't know how to provide the minimal configuration of rspamd as mkuron suggested. I learned to live with the error ...

**Comment by normanu** [comment]
This problem is solved for me in latest ./update.sh

**Comment by andryyy** [comment]
Thanks for reporting back. :-)

**Comment by Anima79** [comment]
Confirmed! No errors in my logs anymore. Thank you very much for your great work, Andryy :))
