### ISSUE TITLE
DNS resolution errors

### ISSUE THREAD

**Issue by mrukas** [mailcow/mailcow-dockerized#115]
Hi!
I'm using this on CentOS 7 and did a clean build multiple times. I setup the image according to the guides multiple times, but i keep getting error messages. Everytime i try to send mails the postfix logs report the following problem:

`postfix-mailcow_1    | Mar 11 14:26:24 mail postfix/smtp[150]: 7EB4B4B80B5D: to=<******@gmail.com>, relay=none, delay=24, delays=4.2/0.02/20/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=gmail.com type=MX: Host not found, try again)
`
I also found out that there are multiple "dnsblog_query" errors like this: 
`postfix-mailcow_1    | Mar 11 14:22:04 mail postfix/dnsblog[126]: warning: dnsblog_query: lookup error for DNS query 189.126.22.195.b.barracudacentral.org: Host or domain name not found. Name service error for name=189.126.22.195.b.barracudacentral.org type=A: Host not found, try again`.

It seems like the internal dns resolution does not work, altough the bind9 image is started.
My host system is able to resolve the dns for gmail correclty:
`gmail.com has address 172.217.17.101
gmail.com has IPv6 address 2a00:1450:400e:806::2005
gmail.com mail is handled by 20 alt2.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 10 alt1.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 40 alt4.gmail-smtp-in.l.google.com.
gmail.com mail is handled by 5 gmail-smtp-in.l.google.com.
gmail.com mail is handled by 30 alt3.gmail-smtp-in.l.google.com.`

Any ideas?

Thanks in advance.

**Comment by edannenberg** [comment]
Well test it with something simple like `docker run -it --rm busybox ping foo.com`. If that does not work you might need to set up a dns cache like unbound on your server and make that the default server in `/etc/resolv.conf`, my hoster for example only allows dns queries from IPs within their network, but the containers each have their own private IP, so any requests from within a container are blocked.

**Comment by broedli** [comment]
Since there has been no answer since a month, I'm closing this.

Please feel free to reopen, if your problem still persits.

**Comment by goldsziggy** [comment]
My issue seems to be the same as this issue. @mrukas any chance you can post what your fix ended up being?
