### ISSUE TITLE
Mysql error after update

### ISSUE THREAD

**Issue by reinoldus** [mailcow/mailcow-dockerized#1150]
Hi,

I've tried to upgrade to the recent version today, but dovecot and SOGO threw these errors:

```
dovecot-mailcow_1    | Mar  9 14:33:13 mx dovecot: auth-worker(64): Warning: mysql: Query failed, retrying: Unknown column 'attributes' in 'where clause'
dovecot-mailcow_1    | Mar  9 14:33:13 mx dovecot: auth-worker(64): Error: sql(xxx): Password query failed: Unknown column 'attributes' in 'where clause'
sogo-mailcow_1       | ERROR 1054 (42S22) at line 1: Unknown column 'attributes' in 'field list'
sogo-mailcow_1       | Will retry to setup SOGo view in 3s
sogo-mailcow_1       | ERROR 1054 (42S22) at line 1: Unknown column 'attributes' in 'field list'
sogo-mailcow_1       | Will retry to setup SOGo view in 3s
```

It is not obvious to me on which version I am, but the migration guide from 0.14 does not seem to match theses errors.

The issue seems to be some changes to the database, but I do not know what exactly has to be patched.

Best Regards

**Comment by mkuron** [comment]
Go to the mailcow admin web UI. It looks like your database schema hasn’t been upgraded yet. If that fails, it‘ll show an error message in the bottom right corner.

**Comment by reinoldus** [comment]
I have reverted everything, but the problem was that I could not access the mailcow-ui, but that gives a good hint. I will retry and figure out why I can't access the ui.

**Comment by clementlecorre** [comment]
I have same issue!

**Comment by rototom** [comment]
Same here, mailserver is not working, need help really fast!
Thank you!

**Comment by thche** [comment]
+1

**Comment by andryyy** [comment]
Open the UI to update the schema.

**Comment by sonicsharp** [comment]
+1

**Comment by reinoldus** [comment]
Opening the UI does the trick. The main problem for me was that the update overwrote my jwilder/proxy and let's encrypt env-vars and therefore I couldn't access the UI anymore.

For me this issue is closed.
