### ISSUE TITLE
DNS advanced configuration - SRV

### ISSUE THREAD

**Issue by razvan-horobeanu** [mailcow/mailcow-dockerized#1153]
Hello,
I was trying to solve all the issues regarding DNS records presented under Domains / mailcow UI.
I was unable to close the ones of the type _25._tcp.mail.domain.tld even asking the domain provider to add to its configuration the settings presented under advanced DNS configuration / documentation. We tried them both ways with / without "." at the end of the FQDN. I supposed that they should be without based on the description.
Any additional information how to solve them is highly appreciated.
Thanks.

**Comment by tkorves** [comment]
If your domain provider is unable to create those TLSA records, it might be related to the DNS server software used by them. E.g. Amazon AWS Route 53 isn't able to set those records. It's not related to having or not having the dot at the end of it (while it is technically required, some implementations of DNS server software don't need it in their configuration).

**Comment by andryyy** [comment]
We tried them both ways with / without "."

That's not the same thing - one is absolute, one is relative. I hope it wasn't your DNS providers idea to try it with and without a trailing dot. :-)

It can take a while for the DNS records to propagate. Check them against their nameservers like `dig tlsa _25._tcp.hosted.mailcow.de @ns1.servercow.de`

**Comment by razvan-horobeanu** [comment]
I compared the dig results from your servers vs my servers and the differences that I noted are the following:
- you receive under Header NOERROR, and I receive NXDOMAIN
- you receive an ANSWER 1 + related section
- I receive an AUTHORITY + related section

It was my idea to ask the DNS provider to do the tests with / without "." 

The email server is working, those such DNS records are reported x under UI. Any other suggestion is highly appreciated.

**Comment by andryyy** [comment]
There is no "other suggestion". Just create the correct TLSA records.

**Comment by razvan-horobeanu** [comment]
DNS provider is not able to make the TLSA records.
Thank you for the support.
