### ISSUE TITLE
sieve: Execution of script dict:proxy::sieve_before failed

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1155]
Hey,

when executing a redirect sieve script, it shows the following error line in the dovecot logs:
`lmtp(example@domain.com): Error: 2JP2Br5ApFqQAgAAuWCjbw:2: sieve: Execution of script dict:proxy::sieve_before;user=example@domain.com;name=active failed, but implicit keep was successful`

**Comment by andryyy** [comment]
You should post the script... probably just bad syntax. 

Added via web ui?

**Comment by phipag** [comment]
```
require ["reject", "editheader", "regex"];

if not address :regex "from" ".*@domain.com"
{
	reject "Nachricht";
}
else
{
	# Unsubscribe E-Mail Adresse
	addheader "List-Unsubscribe" "<mailto:unsubscribe@domain.com>";

	# Mitglieder der Mailing Liste
  deleteheader "To";
  addheader "To" "mail@domain.com";
  redirect "mail@domain.com";
  deleteheader "To";
  addheader "To" "mail2@domain.com";
  redirect "mail2@domain.com";
keep;
}
```
And that for a bit more e-mails. I have added it via web UI, so it is validated. I am using this as temporary mailing list solution until the mailman branch gets merged. How long will this take do you think @andryyy ?

**Comment by andryyy** [comment]
It does not guarantee to validate sieve. I think some values still look bad.

It will never get merged.

**Comment by phipag97** [comment]
Okay then i will have a look at it again.

Oh okay. Can you tell me how i can „update“ to mailman?

**Comment by phipag** [comment]
Can I use the Update script to update to the mailman branch?
