### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by measwel** [mailcow/mailcow-dockerized#1156]
Good day,

I am using mailcow-dockerized with certs from LE which I copy from /live to /ssl. This seems to work, the client is not complaining about the certificate. However, I keep getting the error:
`dovecot-mailcow_1    | Mar 11 00:19:56 mail dovecot: pop3-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<marek@somemail.com>, method=PLAIN, rip=184.73.218.144, lip=172.22.1.12, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)`

I am sure the username and password are correct. What could be causing the authentication problem?

PS I suspect that the user might not be in the db. How can I check that?

**Comment by MAGICCC** [comment]
You use LE but then again you connect via plaintext which isn't that secure...
You can check the Mailcow UI to see if there's a mailbox for that user.

**Comment by tkorves** [comment]
Guess, everything has been said. Closing this issue.
