### ISSUE TITLE
missing mailbox account editor after upgrade to latest

### ISSUE THREAD

**Issue by rtulke** [mailcow/mailcow-dockerized#1158]
Today I started to update my mailcow-dockerized to the latest version, I also update the update. sh and restart all docker containers.... Even, sogo, postfix, dovecot seems to work fine, but when I logged in to mailcow ui => menu => mailboxes I got an overview only with domains... i can edit my domains and it seems also ok (My domains are active and count the number of my mailboxes per domain - should all be there)

But I can't see my mailboxes anymore....

**Comment by andryyy** [comment]
Can you please check your cache (empty it) and try another browser?

**Comment by rtulke** [comment]
ah fine you are right...  it works - sorry, thanks for the quick answer!
