### ISSUE TITLE
hsts whole domain

### ISSUE THREAD

**Issue by unicorn667** [mailcow/mailcow-dockerized#1160]
Hi @all,

now i have installed mailcow on my vps server, so far so good. I want to use some other https services on this server and it´s not realy possible to do that.

hsts is enable for the whole domain

https services is nextcloud snap that i want to run also on this vps

any ideas?

**Comment by andryyy** [comment]
There is really no problem to do this. Your NC instance seems not to use a valid certificate - if any.

**Comment by unicorn667** [comment]
Hi,

i can´t load a new cert with nextcloud.enable-https lets-encrypt but port 80 and 443 are used from mailcow. 

How can i tell them to use another vhost?

Best

**Comment by unicorn667** [comment]
Hi,

created a subdomain for mailcow admin access and edited mailcow.conf and disable lets encrypt. 
nextcloud snap changed http port to 8090 and not using lets encrypt

installed a extra nginx server for above services and installed a lets encrypt wildcard cert
