### ISSUE TITLE
Wrong Caldav url given: https://:/SOGo/dav/user@email.co/

### ISSUE THREAD

**Issue by D4RKNOISE** [mailcow/mailcow-dockerized#1161]
Email Client (em)
New Account > Exchange > Asked credentials "Email address, username, password >>> adding account succesfull.

Do the client ask to change the incorrect CalDAV url thats given: https://:/SOGo/dav/user@email.co/.

Is there a fix for this?

**Comment by andryyy** [comment]
I don't understand. :-(

**Comment by D4RKNOISE** [comment]
I use em client for mail on my computer, adding a new account is no problem...

After i add a new account the mail client gives me a notice that the Caldav URL is incorrect.
This value is inside the Caldav URL field: https://:/SOGo/dav/user@domain.co/
I need to change this manually to https://mail.domain.co/SOGo/dav/user@domain.co/

**Comment by mkuron** [comment]
Are you using a reverse proxy in front of Mailcow? If so, you need to add some headers as per the documentation to get these URLs right.

**Comment by D4RKNOISE** [comment]
reverse looks ok: https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a37.59.42.140&run=toolpage

**Comment by D4RKNOISE** [comment]
As described in the reverse proxy guide:
mailcow.conf
HTTP_BIND=127.0.0.1
HTTP_PORT=8080
HTTPS_BIND=127.0.0.1
HTTPS_PORT=8443
Do i add this or replace it ?
___________________________________________________________________________________________________________
# ------------------------------
# HTTP/S Bindings
# ------------------------------

# You should use HTTPS, but in case of SSL offloaded reverse proxies:
HTTP_PORT=80     > to 8080
HTTP_BIND=0.0.0.0 >to 127.0.0.1

HTTPS_PORT=443 to 8443
HTTPS_BIND=0.0.0.0 to 127.0.0.1

**Comment by mkuron** [comment]
> reverse looks ok

not relevant here

> Do i add this or replace it ?

You add it. But only if you are actually using a reverse proxy in front of Mailcow (e.g. Apache, Nginx, HAProxy). You also need to modify the configuration of the reverse proxy as documented.

**Comment by D4RKNOISE** [comment]
So if i understand correctly, i need to add  the following lines (with the correct information) to nginx site file...
(i'm sorry, still learning and googling)

server {
    listen 443;
    server_name mail.example.org autodiscover.example.org autoconfig.example.org;

    [...]
    your-ssl-configuration-here

    location / {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100m;
    }
    [...]
}

**Comment by mkuron** [comment]
Only if you have a reverse proxy. Don't edit mailcow-dockerized/data/config/nginx/site.conf!

**Comment by D4RKNOISE** [comment]
Ok, thanks in advance for your help... i'll try to google where to put this data! 
https://scontent.fbru1-1.fna.fbcdn.net/v/t1.0-0/p480x480/29066245_10210911414571196_4513713781431336960_o.png?oh=c0dc72bb5b2c1f0a73b47a72ac0749ab&oe=5B31FB97
