### ISSUE TITLE
Banned IP's are only unbanned at netfilter container restart

### ISSUE THREAD

**Issue by jpramming** [mailcow/mailcow-dockerized#1162]
I'm experiencing an issue with the netfilter container.
The IP's that are banned, are never unbanned again.
Only after a netfilter container restart, all banned IP's are unbanned.

The only change I have made to the default setup is changing the ban size from /24 to /32.
From what I can see in the log, everything seems to work as expected, but I only see unbans when restarting.

The following log snippet shows the issue:
![fail2ban_mailcow_issue](https://user-images.githubusercontent.com/18173503/37304109-01e1789a-2631-11e8-8619-2a693649065b.png)
And from the logfile (reverse order):
```
2018-03-12T17:15:49.173041891Z 80.71.xxx.xxx matched rule id 3
2018-03-12T17:15:49.175335618Z Banning 80.71.xxx.xxx/32 for 30 minutes
2018-03-12T18:12:28.696823816Z Clearing all bans
2018-03-12T18:12:28.700002630Z Unbanning 94.102.xxx.xxx/32
2018-03-12T18:12:28.717804329Z Unbanning 107.170.xxx.xxx/32
2018-03-12T18:12:28.724197916Z Unbanning 80.71.xxx.xxx/32
2018-03-12T18:12:29.950214862Z Cleaning previously cached bans
2018-03-12T18:12:29.952490285Z Subscribing to Redis channel F2B_CHANNEL
2018-03-12T18:13:23.274285283Z 94.102.xxx.xxx matched rule id 1
2018-03-12T18:13:23.278280614Z 9 more attempts in the next 600 seconds until 94.102.xxx.xxx/32 is banned
```
The logs aren't very verbose, so any suggestions on how to debug further are greatly appreciated.

**Comment by andryyy** [comment]
```
netfilter-mailcow_1  | 2018-03-12T19:34:39.082022359Z 5.1.76.x matched rule id 1
netfilter-mailcow_1  | 2018-03-12T19:34:39.083731816Z Banning 5.1.76.0/24 for 1 minutes
netfilter-mailcow_1  | 2018-03-12T19:35:40.874572858Z Unbanning 5.1.76.0/24
```

Cannot confirm. Did you restart Redis in the meantime?

I am testing it with your settings rn.

**Comment by jpramming** [comment]
Thank you for testing.
I have not restarted Redis, and the server have been running since last upgrade (8 days ago).
I had some users complaining about problems connecting and suspected netfilter.

BTW, I have just seen the same issue on an other installation I'm running, and here I have the default configuration.

**Comment by apintocr** [comment]
I had a similar issue where a banned IP was not getting removed.

I had to manually remove the iptables block.

Checking the logs at the time I remember seeing that the IP was unbanned.

The symptoms are similar, however I had not restarted any container.

(just leaving this here to confirm OP is not alone :) )

**Comment by jayphizzle** [comment]
I have the same issue.
Default netfilter settings.
Latest mailcow version.

Reboot at 21:24:01.
![greenshot 2018-03-18 21 28 03](https://user-images.githubusercontent.com/9048913/37570696-5eb007e6-2af3-11e8-8477-03cfeb947152.png)

**Comment by jpramming** [comment]
I believe that there are multiple issues with the netfilter container.
Beside the issue with missing unbans, I also see iptable rules (as described by @apintocr), that are newer removed (not even on container restart).

These issues are really hurting my users (and thereby me).
I would gladly help resolving this issue, but I'm completely new to redis, and don't know where to start.

**Comment by mkuron** [comment]
@jpramming, you can have a look at https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/netfilter/server.py . Redis is only used to store a list of bans and settings and is not directly involved with iptables. If you make changes to the file, rebuild the container using `docker-compose build netfilter-mailcow && docker-compose up -d`. 

I don‘t see a codepath where these bans wouldn’t get cleared, but if you find one let me know. Also, the container logs (`docker-compose logs netfilter-mailcow`) might be helpful as they would show when the unbanning fails.

**Comment by andryyy** [comment]
We now create a mailcow chain in netfilter (dev). Perhaps we can cherry-pick it to master.

**Comment by jpramming** [comment]
After a manual removal of all leftover iptable rules and a restart of all the containers, the netfilter seem to work as intended, at least for now.
I will keep monitoring the situation and see if I can find out what triggers the issue.

@mkuron the container logs didn't show any information, that I could relate to the issue. I will look a bit into `server.py`. Thank you for your sugestions.

@andryyy I guess that it would make it easier to flush abandoned rules, but is there any other benefits of using a separate chain?

**Comment by andryyy** [comment]
Yes, + the logic changed a bit.

It is also easier to debug this problem, but still - I don't see it happening on any productive system of mine. :-/

**Comment by burn79** [comment]
Same problem here.
Before netfilter-container restart:
![grafik](https://user-images.githubusercontent.com/25819251/38388721-4ec80da6-391c-11e8-99ed-367f9af40fe5.png)

after restart, 4 pages with uban:
![grafik](https://user-images.githubusercontent.com/25819251/38388759-762b4872-391c-11e8-8e05-5e8e3b6ef3ab.png)

**Comment by Lucky88888** [comment]
I can confirm, same behaviour here.

**Comment by vain90** [comment]
@andryyy
For me, the problem still exists.
Today I had to restart the netfilter because 100th of IPs were blocked.

**Comment by andryyy** [comment]
Were they blocked in iptables only? Did they show as blocked in mailcow UI?

**Comment by vain90** [comment]
The IPs are only blocked in iptables.
In UI i've never seen any Blocked IP there. Except manual added IPs

**Comment by andryyy** [comment]
It should write these things to redis-mailcow, mailcow UI would also brint those IPs as banned then.

Sounds like they are banned but not written to Redis. Hm. I will try to check if it works for me.

**Comment by andryyy** [comment]
Should look like this, when it bans an IP:

![grafik](https://user-images.githubusercontent.com/2972950/54524385-1c375b00-4972-11e9-9e21-e2af1a5ada73.png)

Can you post your Redis logs?

If there is nothing suspicious, I would need to see it on the server itself. :(

**Comment by vain90** [comment]
```Attaching to mailcowdockerized_redis-mailcow_1
redis-mailcow_1      | 1:C 09 Mar 2019 02:06:04.795 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-mailcow_1      | 1:C 09 Mar 2019 02:06:04.795 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis-mailcow_1      | 1:C 09 Mar 2019 02:06:04.795 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.798 * Running mode=standalone, port=6379.
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.798 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.798 # Server initialized
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.798 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.798 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.959 * DB loaded from disk: 0.161 seconds
redis-mailcow_1      | 1:M 09 Mar 2019 02:06:04.959 * Ready to accept connections
redis-mailcow_1      | 1:M 09 Mar 2019 02:11:05.000 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 09 Mar 2019 02:11:05.002 * Background saving started by pid 12
redis-mailcow_1      | 12:C 09 Mar 2019 02:11:05.225 * DB saved on disk
redis-mailcow_1      | 12:C 09 Mar 2019 02:11:05.226 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 09 Mar 2019 02:11:05.303 * Background saving terminated with success
redis-mailcow_1      | 1:M 09 Mar 2019 02:16:06.020 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 09 Mar 2019 02:16:06.021 * Background saving started by pid 13
redis-mailcow_1      | 13:C 09 Mar 2019 02:16:06.254 * DB saved on disk
redis-mailcow_1      | 13:C 09 Mar 2019 02:16:06.255 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 09 Mar 2019 02:16:06.323 * Background saving terminated with success
redis-mailcow_1      | 1:M 09 Mar 2019 02:21:07.041 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 09 Mar 2019 02:21:07.044 * Background saving started by pid 14
redis-mailcow_1      | 14:C 09 Mar 2019 02:21:07.296 * DB saved on disk
redis-mailcow_1      | 14:C 09 Mar 2019 02:21:07.297 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 09 Mar 2019 02:21:07.345 * Background saving terminated with success
redis-mailcow_1      | 1:M 09 Mar 2019 02:26:08.060 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 09 Mar 2019 02:26:08.062 * Background saving started by pid 15

... Many more of this loglines ...

redis-mailcow_1      | 2719:C 18 Mar 2019 12:18:30.338 * DB saved on disk
redis-mailcow_1      | 2719:C 18 Mar 2019 12:18:30.340 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:18:30.349 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:23:31.035 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:23:31.036 * Background saving started by pid 2720
redis-mailcow_1      | 2720:C 18 Mar 2019 12:23:31.291 * DB saved on disk
redis-mailcow_1      | 2720:C 18 Mar 2019 12:23:31.292 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:23:31.338 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:28:32.014 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:28:32.016 * Background saving started by pid 2721
redis-mailcow_1      | 2721:C 18 Mar 2019 12:28:32.287 * DB saved on disk
redis-mailcow_1      | 2721:C 18 Mar 2019 12:28:32.288 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:28:32.318 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:33:33.088 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:33:33.090 * Background saving started by pid 2722
redis-mailcow_1      | 2722:C 18 Mar 2019 12:33:33.342 * DB saved on disk
redis-mailcow_1      | 2722:C 18 Mar 2019 12:33:33.343 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:33:33.391 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:38:34.056 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:38:34.058 * Background saving started by pid 2723
redis-mailcow_1      | 2723:C 18 Mar 2019 12:38:34.308 * DB saved on disk
redis-mailcow_1      | 2723:C 18 Mar 2019 12:38:34.310 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:38:34.359 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:43:35.020 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:43:35.022 * Background saving started by pid 2724
redis-mailcow_1      | 2724:C 18 Mar 2019 12:43:35.261 * DB saved on disk
redis-mailcow_1      | 2724:C 18 Mar 2019 12:43:35.263 * RDB: 1 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:43:35.323 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:48:36.090 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:48:36.092 * Background saving started by pid 2725
redis-mailcow_1      | 2725:C 18 Mar 2019 12:48:36.334 * DB saved on disk
redis-mailcow_1      | 2725:C 18 Mar 2019 12:48:36.335 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:48:36.393 * Background saving terminated with success
redis-mailcow_1      | 1:M 18 Mar 2019 12:53:37.008 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 18 Mar 2019 12:53:37.012 * Background saving started by pid 2726
redis-mailcow_1      | 2726:C 18 Mar 2019 12:53:37.259 * DB saved on disk
redis-mailcow_1      | 2726:C 18 Mar 2019 12:53:37.260 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 18 Mar 2019 12:53:37.317 * Background saving terminated with success```

**Comment by andryyy** [comment]
Can I check that on your server? AnyDesk? Or something like that.

**Comment by vain90** [comment]
Thank you André.

The netfilter works correctly!!!
The problem is due to a misunderstanding of the log entries.

**To make it clear:**

<hr>

### 1.
![Bildschirmfoto 2019-03-18 um 13 56 43](https://user-images.githubusercontent.com/11925757/54531791-70e4d100-4986-11e9-9cd8-8f20d758bd9c.jpg)
This means that a login attempt from IP XXX failed.
At this moment, the IP is stored together with the number of failed attempts in redis.
The IP isn't banned yet.

<hr>

### 2.
![Bildschirmfoto 2019-03-18 um 13 56 49](https://user-images.githubusercontent.com/11925757/54532112-48a9a200-4987-11e9-8afb-9583e20e7402.jpg)
If this particular IP try to log in another 19 times within 10 seconds with the wrong credentials. Than the IP get banned for XX Seconds.

<hr>

### 3.
![Bildschirmfoto 2019-03-18 um 13 57 03](https://user-images.githubusercontent.com/11925757/54532285-b2c24700-4987-11e9-973d-95b3fbe89122.jpg)
This log entry can have two meanings:

1.  The IP was really banned (see point 2) and is now unbanned.
2. OR you've restarted the netfilter and netfilter deletes now the whole list of "wich IP have how many failed attempts" from redis (see point 1).

<hr>

I hope this is helpful.

**Comment by andryyy** [comment]
Thank you for clarifying. :)
