### ISSUE TITLE
Cant get dns records in the correct format.

### ISSUE THREAD

**Issue by D4RKNOISE** [mailcow/mailcow-dockerized#1163]
Tryed everything but they keep ending with a red cross 

Here is an image.
https://pasteboard.co/HbIxpLR.png

**Comment by andryyy** [comment]
A new issue?

**Comment by andryyy** [comment]
```
;_25._tcp.mail.vcloud24.nl.     IN      TLSA
```

There is no TLSA record. That's nothing we can help you with. You should contact your DNS ISP and ask him to setup these records.

@mkuron Any idea about these "cannot parse" msgs?

**Comment by D4RKNOISE** [comment]
I'll ask this to my isp, i'm able to select TLSA but the dns tool is not adding it to the records (no error).
_25._tcp.mail.vcloud24.nl | TLSA | 3 1 1 d77f97ff31f2e881dd24fc808001f2701e03a98bbf83927fc403fdd2f0b40c99
-- | -- | --

Ive i understand the BOTH srv and tlsa records need to be existant to make mailcow working properly.
I cant find anything about the tlsa records in the dns setup (manual).

Kind regards,
Bart

**Comment by mkuron** [comment]
I think these "cannot parse" messages appear if you set invalid ports in mailcow.conf, e.g. like this:
```
IMAP_PORT=
SUBMISSION_PORT=
```

**Comment by mkuron** [comment]
TLSA and SRV records are actually optional. The former are needed for DANE encryption and the latter if you use non-standard ports.
