### ISSUE TITLE
Can't import PST-File with Active Sync

### ISSUE THREAD

**Issue by manule87** [mailcow/mailcow-dockerized#1165]
Hello,
I have successfully installed and set up MailCow, it works perfectly.
But I have a problem:
I have exported all mails from Outlook 2016 into a PST file, then started Outlook 2016 via ActiveSync with MailCow to import the PST file.
The following error appears
![mailcowpstimport](https://user-images.githubusercontent.com/37369625/37401100-4cd438e0-2787-11e8-8230-cc0e3686f68c.JPG)

The operation could not be completed successfully because it is not supported by the service provider.

If the connection between Outlook and MailCow is established via IMAP, the import works without errors, however, the typical IMAP folders SENT etc. are created here.

Is there a solution for PST import via ActiveSync?

**Comment by evilstiefel** [comment]
I don't know if Mailcow/SOGo uses ActiveSync v14.x, but according to this [Microsoft Knowledgebase Article](https://support.microsoft.com/de-de/help/2781261/cannot-move-the-items-error-when-you-move-items-from-an-outlook-2013-c), ASv14 does not support importing PST files.

Could this be the cause of your issue?

**Comment by mkuron** [comment]
This is probably a SOGo limitation and not Mailcow's fault. You can file a bug with them.

SOGo supports only a subset of the Exchange ActiveSync protocol. If you want to know whether a specific feature of a specific version is availble, https://github.com/inverse-inc/sogo/search?utf8=✓&q=MS-ASProtocolVersion+OR+ASProtocolVersion&type= Is a good place to start looking.

**Comment by mkuron** [comment]
SOGo recently added EAS support for Drafts, which appears to be the same feature (see https://github.com/inverse-inc/sogo/commits/master/ActiveSync/SOGoMailObject%2BActiveSync.m). So this issue is already being worked on.
