### ISSUE TITLE
Cannot issue SSL cert

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#1166]
Hello,

I am here again with SSL cert problem, I am trying to add new domain into an existing certificate.

- I added the domain into the mailcow.conf file
- I checked my DNS records and everything point to where it should
- I resatrted the mailcow according to your documentation

Here is my log from the ACME container: https://hastebin.com/uwipuwuyud.scala

I am sorry for asking again about something, but I used the same procedure as always..and it does not work now :/

**Comment by TheUltimateC0der** [comment]
Is your server running behind some kind of WAF or some reverse proxy like Cloudflare?

**Comment by DJIronic** [comment]
Hi,

Unfortunately no, I am using Cloudflare as my DNS provider, but proxy is turned off:
![image](https://user-images.githubusercontent.com/9658012/37432325-47764996-27d8-11e8-841a-dcb9ebcf8b81.png)

Proxy is off for all DNS records on this domain.

But thanks for your help! (issue still not  resolved :/ )

**Comment by TheUltimateC0der** [comment]
Since it is a CNAME record, is the domain that this alias is pointing to behind any proxy ?

**Comment by DJIronic** [comment]
No, I closed the issue already...somehow it worked next day...maybe really slow DNS server on some side. as you can see...the DNS record test passed on my server (I even tried ping). But maybe something on the LE side..I don't know.

and about the CNAME..the domain i aliased it to is my main mail domain and I used this exact CNAME record for all my domains hosted by mailcow. I am sure there is no proxy.
