### ISSUE TITLE
DNS SRV settings are not visible

### ISSUE THREAD

**Issue by garybsimon** [mailcow/mailcow-dockerized#1171]
[Hi]([url](url)) there,

I got a problem with SRV record setup at Cloudflare.
I have created a setup as shown in documentation, but there is no visible SRV record in my DNS.

The records are the following. The DNS can change in 24Hour and still not visible.

MX mydomain.hu	mail handled by mail.mydomain.hu Automatic		
SRV _autodiscover._tcp.mydomain.hu.	SRV 0 1 443 mail.mydomain.hu.	Automatic		
SRV _caldavs._tcp.mydomain.hu.	SRV 0 1 443 mail.mydomain.hu.	Automatic		
SRV _carddavs._tcp.mydomain.hu.	SRV 0 1 443 mail.mydomain.hu.	Automatic		
SRV _imap._tcp.mydomain.hu.	SRV 0 1 143 mail.mydomain.hu.	Automatic		
SRV _imaps._tcp.mydomain.hu.	SRV 0 1 993 mail.mydomain.hu.	Automatic		
SRV _pop3._tcp.mydomain.hu.	SRV 0 1 110 mail.mydomain.hu.	Automatic		
SRV _pop3s._tcp.mydomain.hu.	SRV 0 1 995 mail.mydomain.hu.	Automatic		
SRV _sieve._tcp.mydomain.hu.	SRV 0 1 4190 mail.mydomain.hu.	Automatic		
SRV _smtp._tcp.mydomain.hu.	SRV 0 1 25 mail.mydomain.hu.	Automatic		
SRV _smtps._tcp.mydomain.hu.	SRV 0 1 465 mail.mydomain.hu.	Automatic		
SRV _submission._tcp.mydomain.hu.	SRV 0 1 587 mail.mydomain.hu.	Automatic		
TXT _caldavs	"path=/SOGo/dav/"	Automatic		
TXT _carddavs	"path=/SOGo/dav/"	Automatic

On the Admin side I see red crosses in SRV (TLSA) records.
![bug](https://user-images.githubusercontent.com/1783851/37558291-d1c637d8-2a11-11e8-8361-f180238636a0.JPG)

Why???

With MXtoolbox.com I have checked the SRV records and nothing is visible.
No records.

Where can I check this in Mailcow? How to fix that?

Thanks. Regard. Gary

**Comment by lucianlazar1983** [comment]
That check is for TLSA records, if i'm right TLSA records are available only when using DNSSEC on that domain.
