### ISSUE TITLE
Is is possible to connect Proxmox Mail Gateway with mailcow?

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1172]
Is is possible to connect Proxmox Mail Gateway with mailcow?

I need to use Proxmox Mail Gateway as In and Out mail proxy

**Comment by Braintelligence** [comment]
I'm running Mailcow as guest on Proxmox VE, if experience with this can help you, ping me up. Didn't use the Proxmox mail gateway yet.

**Comment by proea** [comment]
Hi @Braintelligence, 
Thx, but i'm talking about **Proxmox Mail Gateway**

**Comment by mkuron** [comment]
I assume Proxmox is just an SMTP proxy. So you would configure it to deliver all incoming messages to your Mailcow server and set Mailcow to use the Proxmox server as a relayhost for all domains.

Then, you need to add the Proxmox server to Mailcow's forwarding hosts list so that messages are never rejected. Also, you may want to disable the rspamd and ClamAV filters because Proxmox already does filtering. And you may need to edit the global sieve rule to put spam recognized by Proxmox into the Spam folder. The last two things are not possible through the GUI.

**Comment by proea** [comment]
proxmox uses port 26 to receive outgoing mail, however mailcow does not have the ability to set the port for relayhost .. only the ip address is accepted. at least when I put <ipaddr>: 26, then the test showed a connection to port 25, not 26, 
and also 
```
...
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
    ↪ Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
    ↪ error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed [/web/inc/lib/vendor/phpmailer/phpmailer/class.smtp.php line 374]
    ↪ SMTP Error: Could not connect to SMTP host.
...
```

**Comment by green2blue** [comment]
How can you disable rspamd via the GUI?

**Comment by andryyy** [comment]
@proea It supports setting ports. I also confirmed it is working. And "certificate verify failed" sounds fixable. ;-)

**Comment by andryyy** [comment]
@green2blue You can remove the milter settings from main.cf.

**Comment by proea** [comment]
@andryyy 
The test procedure does NOT use the installed port

I will also conduct several checks in the near future

generally I want to say that the UI is not organized very conveniently, for example poste.io is much more convenient and clearer for configuring. even a page with DNS records checking for the mail domain.

I think it is worth thinking about the development of mailcow in analogy with poste.io UI

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/37586186-d7377984-2b5b-11e8-87ec-62d1276d136a.png)

```
Connection: opening to smtp.gmail.com:587, timeout=300, options=array 
```

![grafik](https://user-images.githubusercontent.com/2972950/37586211-e9b819d8-2b5b-11e8-9bc8-937982580cc1.png)

Might still be a bug. Or you had a space between your host and port.

**Comment by andryyy** [comment]
Just because you might be used to poste.io, we won't copy their menus/UI/whatever. In my (!) opinion mailcow UI is easier to use. But I totally accept and understand if you like their UI better.

**Comment by proea** [comment]
@andryyy
  I will try to make a more specific list of which places, etc. can be improved soon

**Comment by andryyy** [comment]
Thank you. :-)

**Comment by proea** [comment]
@andryyy 
Regarding the configuration of the relay host

![image](https://user-images.githubusercontent.com/2929968/37587000-0f6bc23e-2b6f-11e8-9ac8-17751df98341.png)

![image](https://user-images.githubusercontent.com/2929968/37587022-1762615a-2b6f-11e8-9c1b-200a790354c5.png)

ip addr and hostname have been replaced on the screens

can be seen in the log written port 25, not 26

**Comment by proea** [comment]
however relay seems to work with custom port, despite the test

**Comment by andryyy** [comment]
Thanks, yes, it just happened with an empty username. I will push a fix in a bit.

**Comment by proea** [comment]
@andryyy Thanks!

**Comment by andryyy** [comment]
32c0b4a

**Comment by proea** [comment]
@andryyy Yes, it works!

**Comment by proea** [comment]
@andryyy 
How to configure ipv6 address there?
[ipv6]:26 is not working
