### ISSUE TITLE
SOGo / Exchange Active Sync Hanging

### ISSUE THREAD

**Issue by SnowBlinderP** [mailcow/mailcow-dockerized#1173]
Hello

I have some Problems with SOGo Hanging / just being really Slow in the last 2 Weeks since the Newest Update

Mobile / Desktop Clients have the same Problem (Not loading) | Webclient is also very slow

1. Is there any way to fix this?
2. Is there a Way to use a Previous Version of the Docker Container to rollback the Update?

**Comment by SnowBlinderP** [comment]
Issue Fixed after Resetting ActiveSync Cache

**Comment by andryyy** [comment]
Also check/increase SOGoWorkerCount in sogo.conf

**Comment by SnowBlinderP** [comment]
Thanks for the Tip @andryyy | SOGo works better since that Change :D

**Comment by SnowBlinderP** [comment]
Problem appears again.. | Mobile Phones dont send / Recieve and Desktop Clients are "Waiting for Server"

**Comment by SnowBlinderP** [comment]
Problems seems to be Insufficent Ram Allocation / Sync Intervals

Changed and Seems to be "Working" 


Maybe the Ram should scale with the Mailboxes?

**Comment by lavdnone** [comment]
Please share the settings you used if possible. Was voting to get ActiveSync separate container, maybe we should. #976

**Comment by stevesbrain** [comment]
@SnowBlinderP Your worker change didn't get overwritten by an `update.sh` did it?

**Comment by SnowBlinderP** [comment]
@stevesbrain Changes seem to be persistent
@lavdnone Complete Config File or Just the Changed Lines?

**Comment by andryyy** [comment]
Having containers for EAS and web workers will change nothing. You will still run out of workers but you will have to check which container ate them.

Check your logs for "no childs available to handle incoming requests" or something similar (don't grep that exact line). Are there any lines?

**Comment by SnowBlinderP** [comment]
@andryyy Issue doesnt seem to be Worker Related anymore (after increasing WorkerCount to 50 and Changing Ram Settings)

When i resync / reset the Active Sync Profiles i noticed something:

@ First the Sync works (Normally)

After some Time it hits some Kind of Mail / Cache and everytime the Device tries to get its Inbox the SOGo Log Says: "xml2wbxml From Content: failed: Parsing of XML Document Failed"

After that the Active Sync Account on Outlook is broken (Doesnt Sync Anymore)

IMAP / POP still works fine

**Comment by andryyy** [comment]
You need to report that to SOGo, sounds like a bug. Please also enable EAS debugging.

**Comment by SnowBlinderP** [comment]
@andryyy Where do i need to report them ?

**Comment by andryyy** [comment]
To their bug tracker.

**Comment by stevesbrain** [comment]
@SnowBlinderP Which is [here](https://sogo.nu/bugs/my_view_page.php) :)

**Comment by fibis** [comment]
What it the best way to resetting ActiveSync Cache for all users?

**Comment by lavdnone** [comment]
restart docker container?
