### ISSUE TITLE
quarantine does not support remote aliases

### ISSUE THREAD

**Issue by rskallies** [mailcow/mailcow-dockerized#1176]
I have some aliases defined which are being forwarded to another address which is not handled by mailcow. The Quarantine plugin works very well for local accounts but for  aliases pointing to a remote address no entry is seen in the quarantine. rspamd show them as rejected but they are not visible in the quarantine tab.

Is there some other way to have remote forwards to be completely excluded from rspamd checks?

**Comment by andryyy** [comment]
It supports aliases, just not those to non-local/virtual destinations.

You can whitelist a rcpt by adding a multimap entry:

Add to `data/conf/rspamd/local.d/multimap.conf`:
```
PREFILTER_WHITELIST_RCPT_DOMAIN {
    type = "rcpt";
    map = "${LOCAL_CONFDIR}/custom/whitelisted_rcpt_domains.map";
    regexp = true;
    prefilter = true;
    action = "accept";
}
```

Add a new file `data/conf/rspamd/custom/whitelisted_rcpt_domains.map`:
```
/(.*)example.com/i
```

Run `docker-compose restart rspamd-mailcow`

**Comment by rskallies** [comment]
Works fine. Thank you very much.

**Comment by friedPotat0** [comment]
I don't think the issue is solved since mails to remote aliases are not supported to be quarantined at the moment. Did I missing something?

As @rskallies said before the mails are visible as rejected but not stored in the quarantine so that they can be manually learned as spam. I tested the solution from @andryyy with no success. Neither the mails  got excluded completely from rspamd checks (which I don't want to achieve anyway) nor the mails were stored in the quarantine.

**Comment by andryyy** [comment]
You probably see them when logged in as admin (where else though? They don’t belong to a user).

But why would my solution to whitelist a rcpt show you remote destinations in quarantine?

Do that quarantine stuff on your remote destination, I don’t really understand how that is an issue. :/

**Comment by friedPotat0** [comment]
OK, I understand that your solution is only for whitelisting a remote recipient completely. But this solves only the last part of the initial question by @rskallies. The remaining problem is that there is no way to keep rejected mails directed to a remote alias in the quarantine. They are not shown there at all even when logged in as an admin (of course not as a user that doesn't exist).

It is not possible to handle the quarantine stuff on the remote side, if the mail addresses belong to many different users using different external mail providers like gmail. So it would be nice to store the rejected mails of those addresses as well to manually learn them as spam in the mailcow quarantine tab.
