### ISSUE TITLE
Simplest way to whitelist in rspamd

### ISSUE THREAD

**Issue by green2blue** [mailcow/mailcow-dockerized#1177]
I tried to edit the file spf_whitelist.inc.local in the GUI via the tab "Configuration" unfortunately these settings do not work.

In which format do you have to enter domains here?

Unfortunately that does not help me: https://rspamd.com/doc/modules/whitelist.html

Kind Regards

**Comment by andryyy** [comment]
Just use mailcows whitelist.

spf_whitelist.inc.local does work as intended - but it requires a valid SPF record.

**Comment by green2blue** [comment]
Thanks, sometimes I just think way too complicated :-D
