### ISSUE TITLE
update.sh deleted anything

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1178]
Hi there, 

i just runned update.sh after i added a sogo theme, now my database is empty and it seems the mysql volume is freshly created!
What todo? How i could fix this?
Thanks!

**Comment by develth** [comment]
I just recognized that ALL of my data folders are newly created and everything is overwritten

**Comment by stevesbrain** [comment]
That seems extremely odd :/ So you're referring to docker volumes, and not just the git directories? So `/var/lib/docker/volumes` doesn't have any old volumes there? Might have to restore a backup if that's the case

**Comment by develth** [comment]
Yes, after update.sh all volume directories were newly created, all lost...

Sadly my (volumes) Backup was too old - so no way to get anything back, right?

**Comment by develth** [comment]
But how that could happen with update.sh?

**Comment by stevesbrain** [comment]
I actually have no idea! Maybe wait to hear from @andryyy to be sure, but it doesn't sound like there'll be a way to get it back :( The relevant line that would do damage is https://github.com/mailcow/mailcow-dockerized/blob/32c0b4a2931e6512a19d16d6d4b4fb100bab309b/update.sh#L156 - but that looks correct. The only destructive action would be `docker-compose down -d` - however, that script is doing `docker-compose down` (as it should be). You didn't manually do a `docker-compose down -d` before running the script by any chance?

**Comment by develth** [comment]
No, the things i did before was to work with SoGo (docker-compose build sogo-mailcow & docker-compose up -d sogo-mailcow & docker-compose exec sogo-mailcow /bin/bash)

**Comment by Braintelligence** [comment]
@stevesbrain Do you mean `docker-compose down -v`?

@develth Whenever I update mailcow I either do a backup or a rerollable snapshot, so things like this can't happen. Did you use normal docker volumes or did you bind container folders to local filesystem folders?

**Comment by develth** [comment]
Docker Volumes. 
I made backups of the project itself, but not data - sadly. Thought the update.sh wouldn´t kill anything..big failure

**Comment by Braintelligence** [comment]
I wish you could find some logs showing what happened there.

**Comment by develth** [comment]
Where could i find those? I assume those would be deleted, too?

**Comment by Braintelligence** [comment]
I'm not deep enough into docker to know if and where to find such stuff. Maybe your syslog can tell you which commands were run?

**Comment by Dragnucs** [comment]
`docker-compose logs` can probably have something.

**Comment by develth** [comment]
sadly nothing from this time range. is it possibly to go back?

**Comment by Braintelligence** [comment]
Do you use special logging drivers as described here: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/#logging-drivers ?

**Comment by develth** [comment]
No

**Comment by Dragnucs** [comment]
How does your docker-compose.yml look like? Do you have any overrides, override files or the likes?

**Comment by develth** [comment]
As the default one, nothing special.

For example: I just made a new little change (added theme-test.js to sogo Docker), pushed it, runned update.sh - everything works like before... No deletions. All Ok

**Comment by Dragnucs** [comment]
You *pushed* it? How?

**Comment by develth** [comment]
Via git - i forked mailcow (to test features) and it is running in a different branch.

**Comment by andryyy** [comment]
No, it has no ability to delete volumes. You may have changed the project name in mailcow.conf. But the update script does never ever delete volumes. Show me your docker volumes ls output, please. 

This is not a default behavior...

**Comment by develth** [comment]
No - didn´t changed anything in mailcow.conf. 
The crazy thing is , updater worked perfectly 3 times before in a hour - after the last [commit](https://github.com/gigabit-gmbh/mailcow-dockerized/commit/b599a878d735545799e330774ef529d989b3db98) and update it broke. If you check my commits nothing happend in this time-area. 

output: 
 
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_crypt-vol-1
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_mysql-vol-1
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_postfix-vol-1
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_redis-vol-1
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_rspamd-sock
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_rspamd-vol-1
    drwxr-xr-x 3 root root  4096 Mar 19 12:47 mailcowdockerized_vmail-vol-1
    -rw------- 1 root root 65536 Mar 19 12:47 metadata.db

**Comment by nupplaphil** [comment]
Do you use any special volume drivers? f.e. lvm? I had similar issues with lvm-volume-driver because it stopped working and so the volumes were restarted with volumes on non-mounted directories. So it seemed to me that everything was gone, but I just had to manually remount the volume paths again

**Comment by stevesbrain** [comment]
Oh, that's a fair point @nupplaphil - same thing could happen if you had encrypted containers waiting to be mounted, or mountpoints of external media had changed. 

@Braintelligence I likely do mean that; I never used that feature, so that's probably what it was :P I just remember it being dangerously close in my mind to `up -d`, so I had to force myself consciously to not type it out of habit in the early days!

**Comment by ghost** [comment]
I have the same problem. I have make ./update, after this the Mailcow is reset.
I make every day a backup with /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all.
But I can't use the restore.

When I first try Nr. 1 RSPAMD
`Select a dataset to restore: 1
Restoring rspamd from /root/backup/MailCow/mailcow-2018-04-12-04-00-01/...
66a73fe928b5
1fa047a7a0fc
Unable to find image 'mailcow-dockerized_rspamd-vol-1:latest' locally
docker: Error response from daemon: pull access denied for mailcow-dockerized_rspamd-vol-1, repository does not exist or may require 'docker login'.
See 'docker run --help'.
1fa047a7a0fc
66a73fe928b5
`

When I try 5 SQL DB:
`Select a dataset to restore: 5
Restoring mysql from /root/backup/MailCow/mailcow-2018-04-12-04-00-01/...
66a73fe928b5
d353870f9c48
docker: invalid reference format.
See 'docker run --help'.
d353870f9c48
66a73fe928b5
`

**Comment by andryyy** [comment]
You just need to change `COMPOSE_PROJECT_NAME=mailcow-dockerized` to `COMPOSE_PROJECT_NAME=mailcowdockerized` in mailcow.conf. But stop and delete all running containers before proceeding.

**Comment by ghost** [comment]
I have only COMPOSEPROJECT_NAME and the value is allready mailcowdockerized

**Comment by andryyy** [comment]
Then delete it and add the correct variable name. But please delete all containers before doing that.

**Comment by ghost** [comment]
> But please delete all containers before doing that.

Thank you. How can I delete it? I have stop it "docker-compose down -v"
After this, I can start mailcow and restore?

**Comment by Dragnucs** [comment]
The `down -v` would stop the containers, remove them and remove the volumes and networks as well. make sure that this is what you want before running.

**Comment by ghost** [comment]
Sorry mailcow is my first docker app. Delete the /opt/mailcow folder? Or deinstall like here? https://mailcow.github.io/mailcow-dockerized-docs/u_e-deinstall/

**Comment by andryyy** [comment]
Or mail me access to this machine (AnyDesk etc.) to Info@servercow.de

**Comment by ghost** [comment]
Thank you. I have send you a mail

**Comment by ghost** [comment]
@andryyy Now it works thank you. I have found this solutions and now I understand :) https://github.com/mailcow/mailcow-dockerized/issues/1257

But one Question: Why the Restore don't work? Is this only because COMPOSEPROJECT_NAME or is my backup corrupt?

**Comment by andryyy** [comment]
That’s another problem. We added a second Rspamd volume. But I will fix it!

**Comment by fibis** [comment]
I had the same problem. My solution was to take all containers down, add `COMPOSE_PROJECT_NAME=mailcowdockerized` to my config and started them with `docker-compose up -d`. With this solution takes mailcow the old volumes
