### ISSUE TITLE
Watchdog notification when SoGo config SOGoPageTitle is different

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1179]
Hi there,

when changing the 

    SOGoPageTitle
in data/conf/sogo/sogo.conf watchdog is barking because the check 

    /usr/lib/nagios/plugins/check_http -4 -H ${host_ip} -u /SOGo.index/ -p 20000 -R "SOGo\sGroupware" 1>&2; err_count=$(( ${err_count} + $? ))

will fail.

**Comment by andryyy** [comment]
Thanks. 👍
