### ISSUE TITLE
Suggest DNS records in DNS check page

### ISSUE THREAD

**Issue by Dragnucs** [mailcow/mailcow-dockerized#1181]
Currently mailcow proposes a way of checking if DNS records are correct or not. For amateur users like myself, it is difficult to correctly setup the right configuration. For example, I don't know what option to choose in Gandi interface for TLSA types.

If the same screen provided an example configuraztion or even better, the actual tailored missing parts that I could past in the advance zone editor, that would be perfect.

**Comment by mkuron** [comment]
The page already tells you the name, type and value of the records you need to create in your DNS provider‘s zone editor. We found this more useful than providing a copy-and-paste zonefile because most people use DNS providers that don‘t let them edit the textual zone file.

**Comment by Dragnucs** [comment]
Name, type and value differ a lot from a provider to an other, however, a zone file does not.

This additional information should not replace the actual table, which is does an excellent job at detecting correct and incorrect config, but just complement it.

**Comment by mkuron** [comment]
Feel free to submit a pull request that makes the page layout switchable between the current table view and a zonefile. I suppose you could color-code it for good and missing records, but how do you want to display records that are present but do not match the suggested value?

**Comment by Dragnucs** [comment]
Color codes:

- Green for OK
- Orange for missing
- Red present but does not match
