### ISSUE TITLE
Problems with sender acl

### ISSUE THREAD

**Issue by bityoda** [mailcow/mailcow-dockerized#1182]
Hello,

i just setup successfully mailcow with currently 3 domains. I have some trouble correctly configuring the sender acl for a kind of a "master" mailbox account.

Simply i want that this account is able to use in sogo the mail account from the other domains. In a first test, (don't finally configured all domains), this has already worked so far.

But now if i set in the admin panel for "master" mailbox account the allowed sender addresses, nothing is changing in sogo. Even if i restart the complete docker-compose.

The post in the api log looks like this:
/api/v1/edit/mailbox | POST | x.x.x.x | items='["master@somedomain.tld"]', attr='{"sender_acl":["0","domain1.tld","domain.tld"],"active":["0","1"],"force_pw_update":"0","name":"SomeName","quota":"10000","password":"xxx","password2":"xx"}'
-- | -- | -- | --

Probably you have a hint where to double check the issue. I already looked at the table sogo_view where only the aliases from the main domain are set. I have not setup any domain_aliases.

Thanks in advance.

Greetings

**Comment by andryyy** [comment]
Hi,

You want to see the "send as" addresses in SOGo (selectable), right?

Mailboxes must be delegated to other mailboxes within SOGo. We can only show alias addresses as selectable from-addresses in SOGo by ourselves. When we add real mailboxes as selectable aliases to the SOGo view, we break things. You login and SOGo greets you with the name of other mailboxes, the UI does not load and other strange things happen. :-)

You can delegate them like this:

![grafik](https://user-images.githubusercontent.com/2972950/37621913-a3679af2-2bc0-11e8-8b8b-70a1bed9d73a.png)

**Comment by bityoda** [comment]
Hi,

Right.

I understand.
I saw this delegation before, but there was no entries. Now it worked. Perhaps this directly depends of the setting in the mailcow mailbox administration. --> Configuration -> Mailboxes -> [Mailbox] -> Edit -> Allowed to send "as".

If yes, i guess this information could help others in your documentation.

But anyway, thank you very much. You saved me much time!
