### ISSUE TITLE
Not working on OVZ.

### ISSUE THREAD

**Issue by OfficialCRUGG** [mailcow/mailcow-dockerized#1183]
Dockerized isn't working on O(pen)VZ VServers. Please fix that.

**Comment by mritzmann** [comment]
Docker will not run if your OpenVZ-VPS provider uses an old kernel.

**Comment by OfficialCRUGG** [comment]
How can I check if my kernel is old or not?

**Comment by Braintelligence** [comment]
Are you asking how to check the kernel version of your OS?

**Comment by Dragnucs** [comment]
`uname -a` will input all information about your OS including its version. [Latestest stabe Linux version is 4.15.14](https://www.kernel.org/). Oldest long term support is 3.2.101.

Please refer to this [page](https://success.docker.com/article/compatibility-matrix) for Docker compatibility matrix

**Comment by OfficialCRUGG** [comment]
Mine is 2.6.32. Is it possible to upgrade that?

**Comment by Dragnucs** [comment]
You need to check that with your provider.
