### ISSUE TITLE
Switch for Public Calendar

### ISSUE THREAD

**Issue by Fvbor** [mailcow/mailcow-dockerized#1184]
How about a global Switch in the Mailcow GUI to allow Public Calendar in SOGo?
Works with SOGo 4

Config File: data/conf/sogo/sogo.conf
Add Switch: SOGoForwardEnabled = YES;
Restart SOGo

Now it is possible to set Public Permissions
![image](https://user-images.githubusercontent.com/18524580/37661158-67d5e586-2c54-11e8-9b6a-d793009fd668.png)

And to receive links
![image](https://user-images.githubusercontent.com/18524580/37661208-86f4a632-2c54-11e8-9a19-0513175ad91a.png)

**Comment by Braintelligence** [comment]
Yes, please!

**Comment by roswitina** [comment]
+1

**Comment by lavdnone** [comment]
public per domain?

**Comment by Fvbor** [comment]
As far as I know supports SOGo only a global switch, to activate these feature.
After this each user can set the setting for every of his calendars per calendar.
