### ISSUE TITLE
Is there a way to mark a message as spam on SOGo?

### ISSUE THREAD

**Issue by sardaukar** [mailcow/mailcow-dockerized#1185]
Is there a config setting to show a button to mark as email as spam? And since there's no button, does moving an email to the Spam folder serve as enough to mark it as spam and for the filter to learn?

**Comment by mritzmann** [comment]
> Rspamd learns mail as spam or ham when you move a message in or out of the junk folder to any mailbox besides trash. This is achieved by using the Dovecot plugin "antispam" and a simple parser script. 

from: https://mailcow.github.io/mailcow-dockerized-docs/u_e-rspamd/

---

> You have to mark the emails in the list, by clicking on the gravatar icon.
Then there is a thumbs down icon for marking as spam.

from: https://lists.inverse.ca/sogo/arc/users/2018-03/msg00035.html ;-)

**Comment by sardaukar** [comment]
Thanks, I'll try it :)

**Comment by mamair** [comment]
Strange. In my SOGo I cant find a way to move a message into the Spam-folder, there is only a trash button ...
Hm. I am not a programmer / hacker and dont know how to use the scripts and how to put the spam messages as plain file to the loacation where the script is looking for and were to put the script. Documentation is a little bit to slight for me.

**Comment by mamair** [comment]
In roundcube its no problem to move spams to spam-folder. How long should spam-messages stay in spam folder to to train the spam-blocker. Can I delete them imedeately after moving to spam folder or have I to wait because a cron job starts the training?

**Comment by AndrassGray** [comment]
@mamair : Hovering over the avatar icon of the email unhides a checkbox. Checking it develops the Thumbs-down icon, and also develops the menu to move to a different folder.

**Comment by sashaman** [comment]
imho, that is pretty much hidden, unintuitive and requires extra steps - even the submenu of the email doesn't offer to mark it as spam, the only possibility is to select it in list, which is like a "hidden" feature itself.... 
please provide a button!

**Comment by andryyy** [comment]
Hm, but we are not SOGo/inverse. You should ask them. Just move the mail to spam. It is drag and drop. Couldn’t be much easier.

**Comment by sashaman** [comment]
dang sry i missed i'm in mailcow supp lol! 
will do, thx andryyy :)

**Comment by andryyy** [comment]
No problem, though I was not helpful. :)
