### ISSUE TITLE
550 Invalid RDNS entry for xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by can0199-zz** [mailcow/mailcow-dockerized#1187]
Hello sometimes i get an email back an the error code is 
 550 Invalid RDNS entry for my server ip

but i setup the rdns for my server to mail.domain.tld
and if i check my rdns with mxtoolbox there is the correct entry

sorry for my bad english but i hope somewhere can help me

**Comment by RobinFlikkema** [comment]
Does mail.domain.tld also resolve back to xxx.xxx.xxx.xxx?

Not sure who's sending this email, but you could with them to see if they ge tthe correct IPs/records back when using nslookup/dig

**Comment by andryyy** [comment]
I will close this, as the Reverse-DNS setup is never related to mailcow. As long as your rDNS is set, you are fine. It takes a while to propagate the record.
