### ISSUE TITLE
Is there option to sign (dkim) relayed emails?

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1188]
Is there option to sign (dkim) relayed emails?

**Comment by proea** [comment]
@andryyy 

The problem is that relayed emails do not have dkim signatures, while ordinary mail sending has a signature

(domain is configured, dkim signature is generated)

**Comment by andryyy** [comment]
Why doesn't your relayhost sign your msgs?

**Comment by proea** [comment]
@andryyy 
mailcow is the relayhost

| web-node01 | 
| web-node02 | ------> | mailcow | ----- > ...
| web-node0X |

mailcow is now in relay mode for web-nodes. but emails weren't signed

**Comment by proea** [comment]
messages that are sent using postfix sender_dependent_relayhost_maps and smtp_sasl_password_maps also not signed

postfix host -> mailcow -> ..

_postfix host_:
sender: test@domain.com
recipient: recipient@otherdomain.com

_sender_dependent_relayhost_maps_:
@domain.com [mailcowip]:587

_smtp_sasl_auth_enable_:
yes

_smtp_sasl_password_maps_:
[mailcowip]:587 test@domain.com:password

the received message has no signature

**Comment by chindocaine** [comment]
I have the same problem. I have mailcow running one one server and some web applications on another server. I created a mailbox in mailcow and configured postfix on the other server to use mailcow as a relay host, using this mailbox for authentication.
It works, emails are sent and relayed by mailcow, but they don't have the DKIM signature. When I send mails from Sogo or Outlook (directly through mailcow) they get signed.
Is there any solution to this yet?

**Comment by andryyy** [comment]
You should use it authenticated and make sure the sender (envelope from) is actually a domain in mailcow.

As long as it authenticates, mailcow will sign the messages. 

Please post your Postfix logs of mailcow when you relay a message. Maybe Rspamd logs of the same time.

**Comment by chindocaine** [comment]
Wow, thanks for the quick reply.
What can I say, I tried it again, and now the DKIM signature is there. I have no idea what I did differently a week ago and why it didn't work then. But thanks anyway!

**Comment by leifnel** [comment]
May I be daft and reopen this?

I have the same setup as @proea

| web-node | ------> | mailcow | ----- > ...

The webnode is sending with envelope-address bounce+<uniqueid>@example.org and from-address <uniqueid>@sup.example.org, from the server web.example.org

I have setup dkim for both example.org and sup.example.org
_It works if I send mail from test@sup.example.org from SOGo on the server, but mails from the webnode does not get signed._

The servers are behind firewall, and internally use 10.0.5.x addresses; the mailserver and webserver also have public addresses.

I can not get authentication to work; where in the gui to put credentials?

I'm connecting from nullmailer, trying different stuff like 
10.0.5.201 smtp --port=25  --starttls --insecure --auth-login --user=someuser --pass=somepass

But I get 
```
mail postfix/smtpd[1135]: Anonymous TLS connection established from unknown[10.0.5.203]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
mail postfix/smtpd[1135]: warning: unknown[10.0.5.203]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
mail postfix/smtpd[1135]: disconnect from unknown[10.0.5.203] ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```

**Comment by Adorfer** [comment]
having this resolved would help a lot for people with hosts behind firewalls/inside private networks. 

(Mail via delivery-Protocol with full auth is not always an option if your applicance 'in local network' is some $itty old embedded device offering 'email notification' in case of event. some just ask for an smtp on port 25.)
