### ISSUE TITLE
Mail forwarding SPF and relayhost

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#1189]
Hi,

I would like to report that there is two issues when using mail forwarding in mailcow.

1) When you have a relayhost set for the domain, it will not use it when a mail is forwarded.

2) When you use SPF (it's like mandatory nowadays) and you use mail forwarding, you MUST activate SRS so that the sender is rewritten to avoid SPF check to fail on remote host..
This because without SRS the SPF check will lookup the original sender SPF record instead of the the forwarder's SPF record, so it will fail.
Because of this it's really not advised to allow mail forwarding to external mailboxes, because every mail from domains having SPF and forwarded to external SMTPs will fail.
As a nasty side effect, big mail providers will flag your system and destroy your server reputation if you keep forwarding mail that will fail the SPF check.

As example here is the result of a mail sent from gmail to a mailcow mailbox which is redirected to hotmail.

`Authentication-Results: spf=softfail (sender IP is xx.xx.96.134)
 smtp.mailfrom=gmail.com; outlook.com; dkim=fail (body hash did not verify)
 header.d=gmail.com;outlook.com; dmarc=fail action=none header.from=gmail.com;
Received-SPF: SoftFail (protection.outlook.com: domain of transitioning
 gmail.com discourages use of xx.xx.96.134 as permitted sender)
`

xx.xx.96.134 is my mailcow install

Hotmail checks the SPF for the original sender google.com. With SRS it would check SPF record of my domain and would pass.

Additionally for the 1) issue please note that I've configured mailcow to use relayhost xx.xx.96.150 for my domain, and that it's not used when forwarding mail.

When i send a mail from SMTP or Sogo it uses the relayhost:

`
Authentication-Results: spf=pass (sender IP is xx.xx.96.150)
 smtp.mailfrom=mysuperdomain.ch; outlook.com; dkim=pass (signature was verified)
 header.d=madjix.ch;outlook.com; dmarc=pass action=none header.from=mysuperdomain.ch;
Received-SPF: Pass (protection.outlook.com: domain of mysuperdomain.ch designates
 94.103.96.150 as permitted sender) receiver=protection.outlook.com;
 client-ip=xx.xx.xx.xx; helo=mta-gw.xxxxxxxx.net;
`

more reading:
http://www.openspf.org/SRS
https://www.mind-it.info/2014/02/22/forward-postfix-spf-srs/

Thank you for reading!

**Comment by mkuron** [comment]
Relayhost and Sieve rules: that's a known problem, but I can't find the issue for it right now.

SRS: we can't use it because it's not supported by rspamd. Judging from the latest comment on https://github.com/vstakhov/rspamd/issues/1789, it might get implemented soon though. If the original message is DKIM-signed, an SPF failure does not matter. The headers you showed indicate that the hash did not match - that's a different issue, but we can only try to fix it if you can provide the full unmodified message (including headers) as received by Mailcow and as received by Hotmail.

**Comment by ghost** [comment]
Is there any MTA supporting SRS? As far as I am concerned, Postfix does not and never will.

**Comment by JeroenvO** [comment]
This is the best i can find at the moment. https://github.com/roehling/postsrsd
