### ISSUE TITLE
Cron sync not working. Sees folders but doesn't move messages

### ISSUE THREAD

**Issue by tamerax** [mailcow/mailcow-dockerized#1190]
Sorry if this is a dumb issue and I'm missing something but I have been trying to sync up a few populated test accounts from my old server and bring them over to my never server.  No matter what combination of options I use, it connects, sees the rooter folders but then doesn't move the messages or subfolderss except for once with one account where it moved into a new folder called the default "external" but it hasn't worked since with even the same options.
Here is my log file of my list attempt. I'm not sure what I'm doing wrong. For reference sake, my old server is running Iredmail. This account has many emails and subfolders that should be listed.
`
Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
Transfer started at Wed Mar 21 09:34:02 2018
PID is 1374
Load is 0.00 0.01 0.00 1/459 on 1 cores
Current directory is /var/tmp
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.836 $ $Date: 2017/09/05 16:14:53 $ 
Here is mail.pclemail.com, a 1.9 GiB [linux] system (Linux mail.pclemail.com 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64)
with Perl 5.24.1 and Mail::IMAPClient 3.39
Command line used:
/usr/local/bin/imapsync --timeout1 10 --tmpdir /tmp --subscribeall --nofoldersizes --skipsize --buffersize 8192000 --split1 3000 --split2 3000 --fastio1 --fastio2 --exclude (?i)spam|(?i)junk --delete2duplicates --automap --ssl1 --host1 mail.pclemail.com --user1 peter@montvalinc.com --passfile1 /tmp/imapsync.VTwnZtk --port1 993 --host2 localhost --user2 peter@montvalinc.com*gtcpg6tbsjij0ey9 --passfile2 /tmp/imapsync.UZIYdL8 --no-modulesversion
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 SSL_verify_mode=0 meaning SSL_VERIFY_NONE on host1 (do not check the certificate server)
Host1: Use --sslargs1 SSL_verify_mode=1 for SSL_VERIFY_PEER on host1
Host2: SSL default mode is like --sslargs2 SSL_verify_mode=0 meaning SSL_VERIFY_NONE on host2 (do not check the certificate server)
Host2: Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
Info: will act as --uidexpunge2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 10 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [mail.pclemail.com] port [993] user [peter@montvalinc.com]
Host2: IMAP server [localhost] port [993] user [peter@montvalinc.com*gtcpg6tbsjij0ey9]
Host1: connecting and login on host1 [mail.pclemail.com] port [993] with user [peter@montvalinc.com]
Host1 IP address: 172.22.1.7
Host1 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host1 capability before authentication: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN
Host1: mail.pclemail.com says it has CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [mail.pclemail.com] with user [peter@montvalinc.com] auth [LOGIN]
Host2: connecting and login on host2 [localhost] port [993] with user [peter@montvalinc.com*gtcpg6tbsjij0ey9]
Host2 IP address: ::1
Host2 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host2 capability before authentication: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN
Host2: localhost says it has CAPABILITY for AUTHENTICATE LOGIN
Host2: success login on [localhost] with user [peter@montvalinc.com*gtcpg6tbsjij0ey9] auth [LOGIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability once authenticated: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE METADATA COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk
Host2 capability once authenticated: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE METADATA COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk

Host1: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid

Host2: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid

Host2: found quota, presented in raw IMAP

Host2: Quota current storage is 2048 bytes. Limit is 3221225472 bytes. So 0.00 % full
Host1: found 6 folders.
Host2: found 6 folders.
Including all folders found by default. Use --subscribed or --folder or --folderrec or --include to select specific folders. Use --exclude to unselect specific folders.
Excluding folders matching pattern (?i)spam|(?i)junk
[Junk]

Host1: checking all wanted folders exist.
Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
Host1: guessing separator from folder listing: [/]
Host1: separator given by NAMESPACE: [/]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [/]
Host1: guessing prefix from folder listing: []
Host1: prefix given by NAMESPACE: []
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1 separator and prefix: [/][]
Host2 separator and prefix: [/][]
Turned on automapping folders ( use --noautomap to turn off automapping )
Host1: special Sent                 = \Sent
Host1: special Drafts               = \Drafts
Host1: special Archive              = \Archive
Host1: special Trash                = \Trash
Host1: special Junk                 = \Junk

Host2: special Sent                 = \Sent
Host2: special Drafts               = \Drafts
Host2: special Archive              = \Archive
Host2: special Trash                = \Trash
Host2: special Junk                 = \Junk

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the uft8 output just printed for convenience, to recognize it.

Host1 folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
15 OK List completed (0.001 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Host2 folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
11 OK List completed (0.001 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Folders mapping from --automap feature (use --f1f2 to override any mapping):
[Trash]                                  -> [Trash]                                 
[Archive]                                -> [Archive]                               
[Sent]                                   -> [Sent]                                  
[Drafts]                                 -> [Drafts]                                

++++ Looping on each one of 5 folders to sync
Folder     1/5 [Archive]                           -> [Archive]                          
Host1 folder [Archive] has 0 messages in total (mentioned by SELECT)
Host2 folder [Archive] has 0 messages in total (mentioned by SELECT)
Host2 folder [Archive] permanentflags: 
Host1 folder [Archive] considering 0 messages
Host2 folder [Archive] considering 0 messages
Host2 folder Archive selected: 0 messages,  duplicates: 0
Folder     2/5 [Drafts]                            -> [Drafts]                           
Host1 folder [Drafts] has 0 messages in total (mentioned by SELECT)
Host2 folder [Drafts] has 0 messages in total (mentioned by SELECT)
Host2 folder [Drafts] permanentflags: 
Host1 folder [Drafts] considering 0 messages
Host2 folder [Drafts] considering 0 messages
Host2 folder Drafts selected: 0 messages,  duplicates: 0
Folder     3/5 [INBOX]                             -> [INBOX]                            
Host1 folder [INBOX] has 1 messages in total (mentioned by SELECT)
Host2 folder [INBOX] has 1 messages in total (mentioned by SELECT)
Host2 folder [INBOX] permanentflags: 
Host1 folder [INBOX] considering 1 messages
Host2 folder [INBOX] considering 1 messages
Host2 folder INBOX selected: 1 messages,  duplicates: 0
Folder     4/5 [Sent]                              -> [Sent]                             
Host1 folder [Sent] has 0 messages in total (mentioned by SELECT)
Host2 folder [Sent] has 0 messages in total (mentioned by SELECT)
Host2 folder [Sent] permanentflags: 
Host1 folder [Sent] considering 0 messages
Host2 folder [Sent] considering 0 messages
Host2 folder Sent selected: 0 messages,  duplicates: 0
Folder     5/5 [Trash]                             -> [Trash]                            
Host1 folder [Trash] has 0 messages in total (mentioned by SELECT)
Host2 folder [Trash] has 0 messages in total (mentioned by SELECT)
Host2 folder [Trash] permanentflags: 
Host1 folder [Trash] considering 0 messages
Host2 folder [Trash] considering 0 messages
Host2 folder Trash selected: 0 messages,  duplicates: 0
++++ End looping on each folder
++++ Statistics
Transfer started on               : Wed Mar 21 09:34:02 2018
Transfer ended on                 : Wed Mar 21 09:34:03 2018
Transfer time                     : 0.3 sec
Folders synced                    : 5/5 synced
Messages transferred              : 0 
Messages skipped                  : 1
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 1330 (1.299 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 223.3 MiB
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Detected 0 errors

Homepage: http://imapsync.lamiral.info/
Exiting with return value `0``

**Comment by andryyy** [comment]
Hm, well, it says 0 messages. Are you sure mailcow knows "mail.pclemail.com" is your old instance and not itself?

**Comment by tamerax** [comment]
@andryyy 
So the current setup is mail.pclemail.com is my old email server name and my new email server name but I have no switched the DNS settings yet to not disrupt services while I'm testing.
As such,  I am doing all my mailcow work through the IP address while mail.pclemail.com is still pointing to the old server.
Would this be why?  If so, what is the proper procedure for this.  I think I ran into the same issue when I had the reverse going during one short test a few days ago where I accessed the remote by IP into my mailcow running mail.pclemail.com.

another log from a different account just now which I made sure was using the above setup

Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
Transfer started at Wed Mar 21 23:03:03 2018
PID is 4065
Load is 0.00 0.00 0.00 1/471 on 1 cores
Current directory is /var/tmp
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.836 $ $Date: 2017/09/05 16:14:53 $ 
Here is mail.pclemail.com, a 1.9 GiB [linux] system (Linux mail.pclemail.com 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64)
with Perl 5.24.1 and Mail::IMAPClient 3.39
Command line used:
/usr/local/bin/imapsync --timeout1 10 --tmpdir /tmp --subscribeall --nofoldersizes --skipsize --buffersize 8192000 --split1 3000 --split2 3000 --fastio1 --fastio2 --exclude (?i)spam|(?i)junk --automap --ssl1 --host1 mail.pclemail.com --user1 contact@townshipssun.ca --passfile1 /tmp/imapsync.MjVvzCO --port1 993 --host2 localhost --user2 contact@townshipssun.ca*07wye6833242zz4a --passfile2 /tmp/imapsync.RaReL7Q --no-modulesversion
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 SSL_verify_mode=0 meaning SSL_VERIFY_NONE on host1 (do not check the certificate server)
Host1: Use --sslargs1 SSL_verify_mode=1 for SSL_VERIFY_PEER on host1
Host2: SSL default mode is like --sslargs2 SSL_verify_mode=0 meaning SSL_VERIFY_NONE on host2 (do not check the certificate server)
Host2: Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 10 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [mail.pclemail.com] port [993] user [contact@townshipssun.ca]
Host2: IMAP server [localhost] port [993] user [contact@townshipssun.ca*07wye6833242zz4a]
Host1: connecting and login on host1 [mail.pclemail.com] port [993] with user [contact@townshipssun.ca]
Host1 IP address: 172.22.1.7
Host1 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host1 capability before authentication: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN
Host1: mail.pclemail.com says it has CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [mail.pclemail.com] with user [contact@townshipssun.ca] auth [LOGIN]
Host2: connecting and login on host2 [localhost] port [993] with user [contact@townshipssun.ca*07wye6833242zz4a]
Host2 IP address: ::1
Host2 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host2 capability before authentication: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN
Host2: localhost says it has CAPABILITY for AUTHENTICATE LOGIN
Host2: success login on [localhost] with user [contact@townshipssun.ca*07wye6833242zz4a] auth [LOGIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability once authenticated: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE METADATA COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk
Host2 capability once authenticated: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE METADATA COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk

Host1: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid


Host2: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid


Host2: found quota, presented in raw IMAP

Host2: Quota current storage is 36864 bytes. Limit is 3221225472 bytes. So 0.00 % full
Host1: found 6 folders.
Host2: found 6 folders.
Including all folders found by default. Use --subscribed or --folder or --folderrec or --include to select specific folders. Use --exclude to unselect specific folders.
Excluding folders matching pattern (?i)spam|(?i)junk
[Junk]

Host1: checking all wanted folders exist.
Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
Host1: guessing separator from folder listing: [/]
Host1: separator given by NAMESPACE: [/]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [/]
Host1: guessing prefix from folder listing: []
Host1: prefix given by NAMESPACE: []
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1 separator and prefix: [/][]
Host2 separator and prefix: [/][]
Turned on automapping folders ( use --noautomap to turn off automapping )
Host1: special Sent                 = \Sent
Host1: special Drafts               = \Drafts
Host1: special Archive              = \Archive
Host1: special Trash                = \Trash
Host1: special Junk                 = \Junk

Host2: special Sent                 = \Sent
Host2: special Drafts               = \Drafts
Host2: special Archive              = \Archive
Host2: special Trash                = \Trash
Host2: special Junk                 = \Junk


++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the uft8 output just printed for convenience, to recognize it.

Host1 folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
15 OK List completed (0.001 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Host2 folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
11 OK List completed (0.001 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Folders mapping from --automap feature (use --f1f2 to override any mapping):
[Archive]                                -> [Archive]                               
[Sent]                                   -> [Sent]                                  
[Drafts]                                 -> [Drafts]                                
[Trash]                                  -> [Trash]                                 

++++ Looping on each one of 5 folders to sync
Folder     1/5 [Archive]                           -> [Archive]                          
Host1 folder [Archive] has 0 messages in total (mentioned by SELECT)
Host2 folder [Archive] has 0 messages in total (mentioned by SELECT)
Host2 folder [Archive] permanentflags: 
Host1 folder [Archive] considering 0 messages
Host2 folder [Archive] considering 0 messages
Folder     2/5 [Drafts]                            -> [Drafts]                           
Host1 folder [Drafts] has 0 messages in total (mentioned by SELECT)
Host2 folder [Drafts] has 0 messages in total (mentioned by SELECT)
Host2 folder [Drafts] permanentflags: 
Host1 folder [Drafts] considering 0 messages
Host2 folder [Drafts] considering 0 messages
Folder     3/5 [INBOX]                             -> [INBOX]                            
Host1 folder [INBOX] has 1 messages in total (mentioned by SELECT)
Host2 folder [INBOX] has 1 messages in total (mentioned by SELECT)
Host2 folder [INBOX] permanentflags: 
Host1 folder [INBOX] considering 1 messages
Host2 folder [INBOX] considering 1 messages
Folder     4/5 [Sent]                              -> [Sent]                             
Host1 folder [Sent] has 0 messages in total (mentioned by SELECT)
Host2 folder [Sent] has 0 messages in total (mentioned by SELECT)
Host2 folder [Sent] permanentflags: 
Host1 folder [Sent] considering 0 messages
Host2 folder [Sent] considering 0 messages
Folder     5/5 [Trash]                             -> [Trash]                            
Host1 folder [Trash] has 0 messages in total (mentioned by SELECT)
Host2 folder [Trash] has 0 messages in total (mentioned by SELECT)
Host2 folder [Trash] permanentflags: 
Host1 folder [Trash] considering 0 messages
Host2 folder [Trash] considering 0 messages
++++ End looping on each folder
++++ Statistics
Transfer started on               : Wed Mar 21 23:03:03 2018
Transfer ended on                 : Wed Mar 21 23:03:04 2018
Transfer time                     : 0.3 sec
Folders synced                    : 5/5 synced
Messages transferred              : 0 
Messages skipped                  : 1
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 36674 (35.814 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 223.3 MiB
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Detected 0 errors


Homepage: http://imapsync.lamiral.info/
Exiting with return value 0
