### ISSUE TITLE
zen.spamhaus.org is not reachable anymore

### ISSUE THREAD

**Issue by thannaske** [mailcow/mailcow-dockerized#1191]
I'm getting several warning messages in my postfix log that indicate that zen.spamhaus.org could not resolved using DNS.

**Log lines**
```
warning: dnsblog_query: lookup error for DNS query 155.144.143.198.zen.spamhaus.org: Host or domain name not found. Name service error for name=155.144.143.198.zen.spamhaus.org type=A: Host not found, try again
warning: dnsblog reply timeout 10s for zen.spamhaus.org
warning: dnsblog_query: lookup error for DNS query 153.114.114.195.zen.spamhaus.org: Host or domain name not found. Name service error for name=153.114.114.195.zen.spamhaus.org type=A: Host not found, try again
```

**Confirmation on my local device**
```
 thannaske@imc01 ~ dig +short zen.spamhaus.org
 thannaske@imc01 ~ dig +short 155.144.143.198.zen.spamhaus.org
```
-> Can't resolve the address.

**Comment by MAGICCC** [comment]
Yes seems it down, https://downforeveryoneorjustme.com/zen.spamhaus.org
To bad they dont annouce it on e.g. Twitter

**Comment by andryyy** [comment]
It works => dig +short 2.0.0.127.zen.spamhaus.org

Could be unbound. Did you restart the stack?

**Comment by thannaske** [comment]
@MAGICCC It's normal that there is no website served at zen.spamhaus.org. It's basically a DNS resolver that sends you responses based upon the fact if a IP address is blocked or not. e.g if your mailserver receives a message from 1.2.3.4 it queries the A record of 4.3.2.1.zen.spamhaus.org. Depending on the answer the server decides if it's going to accept the message or not.

@andryyy I actually restarted the whole stack, but the messages are the same. I found out that there is no resolution of my example above possible, because I'm actually using Googles Public DNS on my home computer. When I'm explicitly using another - not so public - DNS service the DNSBL is answering me correctly.

```
thannaske@vsc03:~$ dig +short +noshort 234.74.182.213.zen.spamhaus.org # No result :(
thannaske@vsc03:~$ dig @ns1.superdns.nl +short +noshort 234.74.182.213.zen.spamhaus.org # Correct result :)
234.74.182.213.zen.spamhaus.org. 638 IN	A	127.0.0.4
```

Seems like unbound is messing up something in the container stack

PS: The FAQ of Spamhaus says that using Google Public DNS, etc. is discouraged (see https://www.spamhaus.org/faq/section/DNSBL%2520Usage#261). That's why it didn't work on my home computer.

**Comment by ionphractal** [comment]
I hit the same symptoms and it seems in my case the issue is Spamhaus blocking access from my server's network. Workaround for my case was using different resolvers for Spamhaus in `data/conf/unbound/unbound.conf`:
```
forward-zone:
  name: "zen.spamhaus.org."
  forward-addr: 1.1.1.1
  forward-addr: 1.0.0.1
```
