### ISSUE TITLE
No service is getting started

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1195]
Trying to get to work mailcow on a LXC container i created with Proxmox. But the only thing I am seeing are errors. I think It's a network thing, but not sure about that.

Any recommendations what to do? 

`ERROR: for mailcowdockerized_ipv6nat_1  Cannot start service ipv6nat: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/vfs/dir/8d21a0a0a188d986ef387303430779b619da1c8584fd09eaRecreating mailcowdockerized_dovecot-mailcow_1  ... error`

```
Recreating mailcowdockerized_postfix-mailcow_1  ... error
ERROR: for mailcowdockerized_dockerapi-mailcow_1  Cannot start service dockerapi-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 10\"": unknown
```

`ERROR: for mailcowdockerized_dovecot-mailcow_1  Cannot start service dovecot-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:329: setting rlimits for ready process caused \\\"error setting rlimit type 7: operation not permitted\\\"\"": unknown`

`ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (b200795ade6890d0dd74d21673e9bfa4151b3fbb9a7d8f92859b10902bc49b8e): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use
`
`ERROR: for mailcowdockerized_watchdog-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for mailcowdockerized_sogo-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for mailcowdockerized_php-fpm-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for mailcowdockerized_mysql-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for ipv6nat  Cannot start service ipv6nat: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/vfs/dir/8d21a0a0a188d986ef387303430779b619da1c8584fd09ea4afc0b3b4ab30faf/dev/tty: no such device or address\\\"\"": unknown`

`ERROR: for dockerapi-mailcow  Cannot start service dockerapi-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 10\"": unknown`

`ERROR: for dovecot-mailcow  Cannot start service dovecot-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:329: setting rlimits for ready process caused \\\"error setting rlimit type 7: operation not permitted\\\"\"": unknown`

`ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (b200795ade6890d0dd74d21673e9bfa4151b3fbb9a7d8f92859b10902bc49b8e): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use`

`ERROR: for watchdog-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for sogo-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

`ERROR: for php-fpm-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

```
ERROR: for mysql-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
````

**Comment by Braintelligence** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/1192#issuecomment-375033965
