### ISSUE TITLE
Mailcow dockerized need to restart every day.

### ISSUE THREAD

**Issue by garybsimon** [mailcow/mailcow-dockerized#1196]
Hi there
I have an issue with my new mailcow server.
The symptom are the following:
There is 4 domain hosted.
In log file there is no error message, but recently I need to restart the server every day why it stop working every morning.
Why?
What I need to check first?
Please help me out.
Thanks a lot.

**Comment by andryyy** [comment]
We really need information like what exactly stops working. Any log is appreciated too.

**Comment by Braintelligence** [comment]
At the very least your system specs and logs should be always provided when inquiring about such issues.

**Comment by ripkens** [comment]
I have the same issue.
All connectivity is lost (ssh, web, imap, pop, smtp)

Unable to connect to remote host: Connection refused

Reboot doesnt help, only ./update.sh via vnc console (KVM) helps and brings services back.

Ubuntu 16.04, all updates installed, 4G RAM

**Comment by ripkens** [comment]
Is there an unattended way of calling ./update.sh?

It could be used to overcome the problem until its found and fixed.
I would use it in a cronjob every 4 hours for example.

**Comment by mkuron** [comment]
update.sh stops and restarts all Mailcow containers -- but please don't automate that. You need to fix the actual issue. Mailcow does not interfere with SSH in any way. The only explanation I have is that something causes one of the containers to eat up all available memory or CPU, rendering the machine very unresponsive. So the next time, before calling update.sh, please check memory and CPU usage using `top` or `ps axuc` and tell us which process is consuming all available resources.

**Comment by garybsimon** [comment]
More information about this issue.

At our side there is a little VPS with 1gb RAM, it has 3 domain and 25 email address with Exchange profile connected. (I have another working servers like this without this problem)

Could it be that Portainer add-on is too much for this VPS? 

The problem start from SoGo. I think SoGo eats all the Free memory even when I modify the max memory size from 389 > 350  and even when I changed the Workers from 7 to 5.

Log files from SoGo get the following.

`

2018. 04. 05. 13:00:03 | notice | [9]: [ERROR] <0x0x557094e73750[WOWatchDog]> No child available to handle incoming request!
-- | -- | --
2018. 04. 05. 13:00:02 | notice | [29]:  <0x0x55709609c170[SOGoActiveSyncDispatcher]> Sleeping 30 seconds  while detecting changes for user x.y@domain.com in Ping...

`

When I restart only the SoGo container then everything go back to normal.

**Comment by andryyy** [comment]
I answered your other issue, you just need to increase the workers. :-) I recommend ~32.

**Comment by garybsimon** [comment]
@andryyy Thank you.
I give a try. I'll back with the info is it work or not. I hope it will be the solution.
