### ISSUE TITLE
how to remove unused containers?

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1198]
im not used '
robbertkl/ipv6nat
mailcow/clamd:1.9
mailcow/watchdog:1.14'
if I just delete them, nothing bad will happen?

**Comment by mkuron** [comment]
You can safely comment them out in docker-compose.yml (unless you have IPv6, the you definitely need the ipv6nat container). You don’t need to do that, however: their images only take up a few hundred megabytes on disk and if you already disabled clamd in mailcow.conf, they basically don’t consume any memory.
