### ISSUE TITLE
posible to use integrated nginx to reverse proxy an additional server? 

### ISSUE THREAD

**Issue by 1mN3r0** [mailcow/mailcow-dockerized#1199]
Hey @ all. Thanks for this brilliant work!
Is there any way to use the included nginx proxy to proxy another service on the same docker host?
I have an onlyoffice document server running on https port 8888 and hope to be use office.domain.tld next to mail.domain.tld with a additional SAN Entry in mailcow.conf. 

Can anyone give me please a hint or solution how i can add this situation to mailcow nginx as a custom or additional office.domain.tld.conf to serve this SSL reverse port. 

Actually is running the mailcow dockerized docker-compose Version with SSL autorenew and parallel installed nextcloud with the helper script. 

Thanks for your efforts!

**Comment by lavdnone** [comment]
nginx has 
`include /etc/nginx/conf.d/site.*.custom;`
folder is mapped in docker-compose.yml volumes: `./data/conf/nginx/:/etc/nginx/conf.d/`

you should be able to put site.somethig.custom files there with additional nginx config lines, something like this
```
    location ^~ /lool/adm {
        proxy_pass http://IP:8888;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }
```
