### ISSUE TITLE
SOGo / Roundcube - select on installation

### ISSUE THREAD

**Issue by SimonVillage** [mailcow/mailcow-dockerized#120]
Hey there,

would it be possible to let the user select if SOGo will be installed or not?
I removed the SOGo container and customized the docker-compose.yml file.

But it would be nice if the link to SOGo will be removed automatically.
Maybe an option to select roundcube at the beginning?

<img width="485" alt="bildschirmfoto 2017-03-13 um 18 14 44" src="https://cloud.githubusercontent.com/assets/1446685/23852143/f90dcd22-0818-11e7-9cbb-24dd69efb269.png">

**Comment by andryyy** [comment]
Thanks, I will look into it. :-)
