### ISSUE TITLE
[SOGo] "Native" Outlook Support

### ISSUE THREAD

**Issue by nupplaphil** [mailcow/mailcow-dockerized#1200]
I'm not SO familiar with SOGo and Outlook-Support, but I think, I found some known issues with the ActiveSync implementation.

- Labeling/Categorization/synchronisation of Calendar & address-book in Outlook has some issues for me (f.e. it recently drops all labels in my calendar when I re-added the mailbox)
- Copying Items from one Outlook-Mailbox to the SOGo-Outlook-mailbox (ActiveSync) isn't supported
- Outlook-Rules aren't synchronized to SOGo-filters

I found that SOGo also works with native MAPI support if there is a samba-instance working with the "openchange"-plugin. I believe that the native mapi support has a more integrated featureset for outlook than the activesync version.

What do you think?
What were the cocerns about mapi?

I think the major concern is the integration of a full-blown samba in mailcow and the sync of the mailbox/domain-configs would be somehow painfull, wouldn't it?

Because it would be a major reason to completely switch from exchange to mailcow, I would help working on a branch with samba-support.

**Comment by mkuron** [comment]
Duplicate of #223. OpenChange is essentially dead. And we would need to migrate most of the data from the MySQL database into LDAP, which is not an easy task.

**Comment by nupplaphil** [comment]
Damn, sorry to hear that it's dead :-( .. Hopefully there will be a successor someday

**Comment by Braintelligence** [comment]
This one works pretty well for now: https://sourceforge.net/projects/outlookcaldavsynchronizer/
