### ISSUE TITLE
how to connect smtp to site?

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1202]
I want to use mailcow as a SMTP server, to confirm registration user on the site.
im create user info@website.com, but when connect to mail.mailserver.com:25 with user  info@website.com i have error "Helo command rejected: need fully-qualified hostname"

**Comment by mkuron** [comment]
You need to use port 587, which is for authenticated message submission (i.e. client-to-mailserver communication). Port 25 is only used for mailserver-to-mailserver communication and doesn‘t require authentication but forbids relaying.

**Comment by rassemdev** [comment]
> 

@twixi did you able to connect smtp to your site?

**Comment by twixi** [comment]
yes

**Comment by rassemdev** [comment]
> yes

Can you share your code here please/some sort of instruction how you manage to connect to smtp, I am also having some problem sending mail through smtp. Or any kind of help will be appreciated

**Comment by twixi** [comment]
you need to configure correctly **DNS**

**Comment by rassemdev** [comment]
Will you share what dns record you have added. And is my env config is okay!
MAIL_DRIVER=smtp
MAIL_HOST=mail.myclearmargin.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls

if i use MAIL_PORT=587 i am getting this error `Expected response code 354 but got code “554”, with message “554 5.5.1 Error: no valid recipients`
if i use MAIL_PORT=465 i am getting this error `Connection to tcp://mail.myclearmargin.com:465 Timed Out`
