### ISSUE TITLE
Single Sign On possible?

### ISSUE THREAD

**Issue by alexanderrieder** [mailcow/mailcow-dockerized#1204]
Hey Guys,

is it somehow possible to enable a Singe Sign On? I have a customer panel and would like to integrate mailcow with single sign on.. :)

Greetings,

Alex

**Comment by mkuron** [comment]
@andryyy has started integrating an OAuth provider (36532c3, 541e1d9) which would allow other services to authenticate against Mailcow. You could also modify your customer panel to directly read Mailcow‘s database or test authenticating to it via IMAP.

If you want to do it the other way round (have Mailcow do its authentication via your customer panel): that‘s not easily possible. If you only care about Mailcow‘s web UI, you might be able to modify your panel to set the correct cookie and session variables so mailcow thinks the user is authenicated. If you wanted Mailcow to use some external authentication database (including for IMAP/SMTP): that‘s probably never going to be implemented.

**Comment by alexanderrieder** [comment]
ok thanks :)

**Comment by alexanderrieder** [comment]
How could I create such a php cookie?

**Comment by Reitz86** [comment]
That seems interesting. Just fetched the dev branch and inserted an application into the database.  Now im confused, lets create an example:
mailcow url: 'https://mail.mydomain.com
application: 'https://cloud.mydomain.com

Application in mailcow oauth:
Client ID: 'testapp'
Client secret: 'abcde'
Redirect/Callback URL: 'https://mail.mydomain.com'
Grant types: 'refresh_token password authorization_code'
Scope: 'profile'

Client application config (seafile in my example):
OAUTH_CLIENT_ID = "testapp"
OAUTH_CLIENT_SECRET = "abcde"
OAUTH_REDIRECT_URL = 'https://mail.mydomain.com/'
OAUTH_PROVIDER_DOMAIN = 'mydomain.com'
OAUTH_AUTHORIZATION_URL = 'https://mail.mydomain.com/oauth/authorize.php'
OAUTH_TOKEN_URL = 'https://mail.mydomain.com/oauth/token.php'
OAUTH_USER_INFO_URL = 'https://mail.mydomain.com/oauth/profile.php'
OAUTH_SCOPE = ["profile",]
OAUTH_ATTRIBUTE_MAP = {
    "id": (True, "email"),
    "name": (False, "name"),
    "email": (False, "contact_email"),
}

Does that seem like a correct setup?
