### ISSUE TITLE
change path "mailcow-dockerized"

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1206]
how to right change path "opt/mailcow-dockerized" to example "/home/mail".
when I do it in another folder I get a 502 error,and more...

**Comment by MAGICCC** [comment]
And what did you move?
You could stop all containers and move the entire mailcow-dockerized folder and change the permissions again. Since the volumes are still in /var/lib/docker it should work

**Comment by andryyy** [comment]
Yes, you need to stop/recreate all containers. Run `docker-compose down` and `up -d` at the new location. Do not change file permissions and check /home/mail is readable by others.

**Comment by twixi** [comment]
i have warning error after next command:

sudo mkdir -p /home/mail
cd /home/
sudo git clone https://github.com/mailcow/mailcow-dockerized
sudo mv /home/mailcow-dockerized/* /home/mail/
sudo rm -R /home/mailcow-dockerized
cd /home/mail/
sudo ./generate_config.sh
sudo docker-compose pull

root@vps:/home/mail# sudo docker-compose pull
WARNING: The TZ variable is not set. Defaulting to a blank string.
WARNING: The DBROOT variable is not set. Defaulting to a blank string.
WARNING: The DBNAME variable is not set. Defaulting to a blank string.
WARNING: The DBUSER variable is not set. Defaulting to a blank string.
WARNING: The DBPASS variable is not set. Defaulting to a blank string.
WARNING: The MAILCOW_HOSTNAME variable is not set. Defaulting to a blank string.
WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.

when mailcow in /opt/mailcow-dockerized - no any WARNINGS
