### ISSUE TITLE
'Wrong username or password' when trying to log in to SOGo, even when it's right

### ISSUE THREAD

**Issue by soccermitchy** [mailcow/mailcow-dockerized#121]
When I try to log into SOGo, I just get "Wrong username or password", even when it's correct. When I hit F12, I see it sent a POST request to /SOGo/connect, and got `{"LDAPPasswordPolicyError": 65535}` in theresponse. I also got this in the logs for the SOGo container: `Mar 13 22:00:28 sogod [31]: SOGoRootPage Login from '172.22.1.1' for user 'mitchell@studiowolfree.com' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0`.
 I looked and saw another issue (#40) like this one, but unlike that issue, this was a fresh install of mailcow. Any way to fix this?

**Comment by andryyy** [comment]
Restarted SOGo?

**Comment by soccermitchy** [comment]
How would I do that? I'm not that familiar with Docker (tbh I thought it
was easier to set up the old version of mailcow >.>)

**Comment by andryyy** [comment]
In the UI. Navigation bar on the top. :-)


Am 14.03.2017 um 07:24 schrieb Mitchell Monahan:

**Comment by soccermitchy** [comment]
Ah, ok. Thought it was a command I had to run to do it. Yeah, I forgot to
hit the button earlier (I saw the warning when making a domain, just didn't
think anything of it), restarted it and it works now.
