### ISSUE TITLE
Nextcloud

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#1215]
Hi everybody,

is there a howto fpr install nextcloud?

regards
jm3west

**Comment by Icki153** [comment]
Hi,

go to mailcow install dir and execute `helper-scripts/nextcloud.sh -i`. Then you can decide if you use an subdomain or an subfolder. Thats all. Login works for every mailcow user with mail address and same password as sogo.

**Comment by jm3west** [comment]
Hi,

yes I've got it.
I'm still install "dirmngr"
So, now I can use helper-scripts/nextcloud.sh -i

jm3west

**Comment by Icki153** [comment]
Hi,

sorry. I do it few weeks ago. So i miss this point.
But when its now working it's all ok 👍
