### ISSUE TITLE
Mailcow crashed in Docker Swarm

### ISSUE THREAD

**Issue by measwel** [mailcow/mailcow-dockerized#1216]
Good day,

I had mailcow running in an experimental docker swarm. The server crashed. After restart I do not see mailcow as a service in the swarm anymore. Should it not have restarted automatically?

**Comment by mkuron** [comment]
That's a Swarm question, not a Mailcow question. Nobody can answer that here.

**Comment by ruanbekker** [comment]
Correct, it is related to swarm. @measwel - if your manager nodes lost quorum they probably lost the ability to provide insights into your mailcow service. 

Also if something went wrong with the Docker itself that could also be a factor. The docker community will be able to help out with that.
