### ISSUE TITLE
rspamd whitelist for aliases

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#1217]
I've created a mail alias that forwards all mails to my private mail address on an external server. Now, i tried  to receive an unblocking key from matrix.spfbl.net, but rspamd keeps blocking this mail:

![image](https://user-images.githubusercontent.com/81188/38140971-90ab1884-3436-11e8-8dee-80c054db3c9a.png)

Within a normal mailbox, i could whitelist the address. But how to do it with an alias?

**Comment by andryyy** [comment]
Probably not a direct, but a shared alias.
