### ISSUE TITLE
Login is slow

### ISSUE THREAD

**Issue by bigjerms** [mailcow/mailcow-dockerized#1219]
I just installed a fresh mailcow dockerized install and when I login it is extremely slow.  You enter the username and password and click login and the login button changes to say please wait and it stays this way for several minutes before it actually logs you in.

It takes about 2 to 3 minutes for it to login.  It also seems to do this when you click logout.  I'm not seeing any errors in the logs to indicate any issues.  The containers all look healthy.  Any ideas or direction on where I might look to resolve this would be appreciated.  

I'm running this on a ubuntu 16.04 VPS with 4 gigs of ram and plenty of disk space.  When look at memory and cpu utilization nothing is spiking to indicate any resource issues.

**Comment by bigjerms** [comment]
This is the only thing in the logs that seems to be related.  I'm not sure what I'm doing wrong.
2018/04/13 19:42:43 [error] 15#15: *7684 upstream timed out (110: Operation timed out) while connecting to upstream, client: 50.187.222.111, server: mail.xxxxxx.net, request: "POST / HTTP/1.1", upstream: "fastcgi://[::2]:9000", host: "mail.xxxxxx.net", referrer: "http://mail.xxxxxx.net/"

Note ip info and urls changed for this post.

**Comment by andryyy** [comment]
Sounds like ip6tables rules block IPv6 connections. `::2` looks wrong, too. Any changes made to mailcow.conf? Is ufw disabled?

**Comment by bigjerms** [comment]
The ::2 was me just clearning out the rest of the ipv6 address in the error message.  Turning off ufw fixed the issue.  Thank you so very much for your help.
