### ISSUE TITLE
property oom_score_adj is not allowed

### ISSUE THREAD

**Issue by measwel** [mailcow/mailcow-dockerized#1221]
When trying to deploy mailcow in docker swarm with portainer:
property oom_score_adj is not allowed.

What is causing this error?

**Comment by mkuron** [comment]
It's in docker-compose.yml: https://github.com/mailcow/mailcow-dockerized/blob/1534c5aa76510ef0a13a29d56ace491169dfa6f4/docker-compose.yml#L376 . You can safely delete that line.
