### ISSUE TITLE
Nextcloud conversion

### ISSUE THREAD

**Issue by KubqoA** [mailcow/mailcow-dockerized#1223]
Hello,
going through the sources of this project I stumbled upon the helper script for nextcloud. I already have running installation of nextcloud with some data in it. How difficult would it be to convert regular install of nextcloud to docker (mailcow) based one? And what would I have to do to keep my existing data and users? Thank you

**Comment by nupplaphil** [comment]
I'm currently working on the same setup.

My steps so far:
- Creating a new private network, which is attachable per `docker network create`
- Adding the private network in the **mailcow** docker-compose.yml as a new network
- Adding `dovecot-mailcow` and `postfix-mailcow` to the private network
- Adding the private network in the **nextcloud** docker-compose.yml as a new network
- Adding the nextcloud service (for me it is a php-fpm Container)  to the private network

Now you can use the imap-backend of nextcloud similar to the [Nextcloud-Script](https://github.com/mailcow/mailcow-dockerized/blob/master/helper-scripts/nextcloud.sh)

**Postfix-Support**
> docker exec -ti -u www-data nextcloud_app_1 php occ config:system:set mail_smtpmode --value=smtp;
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set mail_smtpauthtype --value=LOGIN;
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set mail_from_address --value=nextcloud;
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set mail_domain --value=${MAILCOW_HOSTNAME}; \
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set mail_smtphost --value=postfix; \
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set mail_smtpport --value=588

**IMAP-Support**
> docker exec -ti -u www-data nextcloud_app_1 occ app:enable user_external
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set user_backends 0 arguments 0 --value={dovecot:143/imap/tls/novalidate-cert}
> docker exec -ti -u www-data nextcloud_app_1 occ config:system:set user_backends 0 class --value=OC_User_IMAP"

Now the user is able to login to nextcloud with his mailcow credentials.

But I'm currently searching for a easy way to migrate "local" Users to "IMAP_User" Users too.

**Comment by nupplaphil** [comment]
Hm.

If you have your nextcloud data on a separated volume, you can mount it inside a new nextcloud-container (created with https://github.com/mailcow/mailcow-dockerized/blob/master/helper-scripts/nextcloud.sh)
Then you have the data and accounts of all your old users but you can now use the IMAP-Backend of mailcow too.

To merge your old users, you can give occ a try:
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/file_sharing_configuration.html#transferring-files-to-another-user

**[Edit]**
I personally prefer to use another docker-compose file for nextcloud with php-fpm and nginx reverse proxy (see [Docker-Github](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm) for examples) where just postfix, dovecot and nextcloud share a second, private network :-) -> Keeping them separated

So upgrading/using nextcloud is not directly bound to mailcow (over the same php-fpm container) and vice versa .

**Comment by djmwj** [comment]
> I personally prefer to use another docker-compose file for nextcloud with php-fpm and nginx reverse proxy (see Docker-Github for examples) where just postfix, dovecot and nextcloud share a second, private network :-) -> Keeping them separated

@nupplaphil How do you actually accomplish this? If you run mailcow-dockerized it spins up its own instance of NGINX which also requires access to port 80 as does nextcloud's nginx. How do you accomplish this? Would you be will to share your docker-compose?  

Your help is appreciated, It sounds like your doing exactly what i would like to be able to accomplish. Right now the only way I can get it to work is to use the install script, which in my mind is not as clean and harder to manage. 

Thanks!

**Comment by nupplaphil** [comment]
I'm using [traefik](https://traefik.io/) as reverse proxy and nextcloud-nginx and mailcow-nginx are using a separated subdomain.

My [docker-compose.txt](https://github.com/mailcow/mailcow-dockerized/files/1871249/docker-compose.txt) (you have to rename it to *.yml)

If you don't use traefik:
- Create a simple nginx-container
- bind the ports 80 & 443
- add nginx-nextcloud to the same network
- add nginx-mailcow to the same network 
- make subdomain-rules for each

The disadvantage is, that you also need a separated ACME-container for certificates.

**Comment by djmwj** [comment]
Thanks! I have spent some time and now have my nextcloud working with a seperate NGINX reverse proxy in front! BUT, I cannot get MAILCOW to work correctly. It appears that none of the docker services can access the database. When trying to visit the mail site i get 

> Connection to database failed.
> The following error was reported:
> SQLSTATE[HY000] [1045] Access denied for user 'mailcow'@'172.22.1.9' (using password: YES)

This is corroborated in the logs as well, all of the services are being denied access. The database service is up. I also attached a copy of my docker-compose, [docker-compose.txt](https://github.com/mailcow/mailcow-dockerized/files/1886853/docker-compose.txt) if you can help me troubleshoot i would be very grateful.

PS. I think there may be a typo in your docker compose:
Under the nginx-mailcow labels:
- "traefik.frontend.headers.froceSTSHeader=true" 
Should read: - "traefik.frontend.headers.f**or**ceSTSHeader=true"

**Comment by djmwj** [comment]
Looks like I was able to get around this by delete the old image "docker-compose down -v" and rebuilding the database. I have also went ahead and turned off the letsencrypt cert as its being done now by the nginx companion. However, what is the best way to enable smtp again? I am assuming i need to somhow connect the certs back into mailcow manually. 

Any ideas? 

Thanks!
