### ISSUE TITLE
[Request] Adding some features

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1224]
Hi. :)

In the last days I migrated hundreds of people with over 50k E-Mails and GBs of data from a shared webhosting email service to a self hosted mailcow solution. 

For that I built my own solutions and scripts like "Force the password for all accounts at once" or "delete syncing jobs for all accounts at once". I also build things like "automatically increase the mailbox size by 10% when 90% of the maximum size has been reached." It's all about making daily admin life easier.

Unfortunately I missed those 1 click functionality in the admin area. If you want I could build it into the admin backend area and do a pull request, are you open for that?

Kind regards
Ron

**Comment by catcun** [comment]
@ronhoffmann 
I am not the project owner, but your additions feel very useful (anything that saves time is potentially good). Let's see what the rest of the community think.
