### ISSUE TITLE
Changes and Suggestions

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1226]
Hi,

1. Welcome page after login (as admin)
- it is more logical to make this page "mailboxes"

2. Menu configuration -> mailboxes 
If you want to create a new mailbox you have to go to the configuration -> mailboxes -> mailboxes tab
it is not comfortable. I propose to restructure the menu, to put mailboxes in a separate menu item

3. Address rewriting tab is not clear for the first time.
it would be nice to add comments about the BCC type, for example

4. font is sometimes too light, which makes it difficult to read, for example, in the dropdown-menu

5. it would be useful to add a field with the current size occupied by the disk with this domain in the Domains tab
and somewhere below the page how much space is currently available on the system

6. domain Ratelimit - it is not clear whether this applies to relay letters or only to those sent from this box?

7. dkim is not generated by default. for its generation it is required to go to the administration and create manually and manually enter the domain name for which you want to create

8. it would be useful to create the option "relay host for all domains"

9. I can create instructions for installing and configuring rainloop and afterlogic (PrivMX in the plans)

10. very strange behaves SOGo for multiple boxes. in particular it is not possible to create a separate name for the alias

11. What is "resources" in the UI? it's not clear

12. address rewriting does not go through Relayhost

13. What is 240.240.240.240 ???
```} else {
  try {
    echo '240.240.240.240' . PHP_EOL;
    foreach ($redis->hGetAll('WHITELISTED_FWD_HOST') as $host => $source) {
      echo $host . PHP_EOL;
    }
  }
  catch (RedisException $e) {
    echo '240.240.240.240' . PHP_EOL;
    exit;
  }
}
```
File: data/conf/rspamd/dynmaps/forwardinghosts.php

14. It would be nice to add configurable 'mynetworks' option via UI

15. Relayed mails are not signed by dkim

16. bug in UI: in App links:
if you add two new lines and click "Save Changes", they will not be saved

**Comment by cwildfoerster** [comment]
I also like to add that it is not possible to create multiple dkim keys and just check which one to use. I would really like that feature because that way i could update or add all my dns changes in advance and then just switch the dkim key to use.

**Comment by PhoenixPeca** [comment]
Hi,
> Welcome page after login (as admin)
...it is more logical to make this page "mailboxes"

this is already in effect with domain-administrators.

>dkim is not generated by default. for its generation it is required to go to the administration and create manually and manually enter the domain name for which you want to create

DKIM requires you to (manually) change the DNS for the domain. This means we cannot automate the DKIM generation unless we can find a general solution for updating the DNS for all domains.

> What is 240.240.240.240 ???

I believe this question should be asked to the rspamd maintainers.


> bug in UI: in App links:
if you add two new lines and click "Save Changes", they will not be saved

I cannot reproduce your issue. Perhaps clearing your browser data for your mailcow instace could be a great idea.
