### ISSUE TITLE
nginx: allow custom "server" blocks configuration

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#1227]
Currently the `include` for custom configuration in `site.conf` is only set inside a `server` block. It would be nice to allow including configuration (in a similar fashion as shown in the docs) outside the blocks (for, e.g. providing other containers on different domain names, or to customize the setup without breaking anything in `site.conf`).

**Comment by lbeltrame** [comment]
Forgot to mention, but are PRs welcome for this? It may sound like a rhetorical question, but I'd like to know first if this additional feature makes sense from the maintainers' POV.

**Comment by andryyy** [comment]
You can create conf files inside data/conf/nginx

**Comment by lbeltrame** [comment]
Yes, but I mean that if I want to add a custom server block, I can't unless I change `site.conf`.

That's because the include directive is *inside* a `server` block. Changing `site.conf` is also prone to conflicts when updating. See the PR for a better explanation than my words.

**Comment by andryyy** [comment]
Just add a new file. It is included at top level.

**Comment by lbeltrame** [comment]
I took a second to parse the answer, and I assume you meant from /etc/nginx.conf. I'll focus on the other issue then, as this is not a real problrm.
