### ISSUE TITLE
can't receive emails from specific providers

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1230]
Hey.

I'm not able to receive emails from any provider except Gmail. Sending is not a problem at all to anyone. I think It's something with Postfix. DNS and spam related things are ok. No firewall rules at all yet because of debugging, standard mailcow installation on a standard debian host.

GMX for example answering with the following:

> This message was created automatically by mail delivery software. A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. The following address(es)
failed: name@company.de: non-existent domain

Also, if I do SMTP tests with various tools on the web they can't connect to
> Connecting to IP_OF_MAIL_SERVER
4/2/2018 6:19:12 AM Connection attempt #1 - Unable to connect after 15 seconds. [15.02 sec]

But again, sending is still not a problem, how does that fit together? 

It seems it's something between Postfix and Dovecot and SASL Authentication, is that possible? In postfix logs the following is coming up quite often: SASL Login aborted. 

I also did the standards things like restart postfix, build a new stack with `docker-compose up -d` etc. I also build a complete new mailcow and restored a backup, but nothing changed

Maybe the information that mail.company.de and company.de don't have the same A/AAAA Record is an important note?

Any suggestions?

Thank you
Ron

**Comment by xetorixik** [comment]
> I also build a complete new mailcow and restored a backup, but nothing changed

Does the system work with a clean installation?
Because you mentioned backup.
I assume that the mail server previously worked properly.

In order to prevent your useless, hours searching for an unknown problem.
What I always do in the case of a similar problem.
Is starting another VPS (other provider, maybe test domain) and simulate the problem.

Many providers support pay per hour. So that's easy.
This prevents annoyance. And quickly provides a solution.

For example if your provider blocked a gate, in case of a software related problem etc.

**Comment by ghost** [comment]
Nope it doesn't work with a clean install also. Still have SASL Login failures.

**Comment by xetorixik** [comment]
As it won't work on a fresh installation.
It seems to me that it (I assume that you have installed it properly) is a provider problem.
For example the host server.

Which provider do you use?

P.s. it is advisable to remove your IP address from the start post.

**Comment by ghost** [comment]
Yes, it's a provider problem, figured it out some minutes ago, works like a charme on another server infrastructur. So not a mailcow related problem. Sorry. :)

**Comment by xetorixik** [comment]
No problem.
Good to hear that it works like a charm without problems. 

It seems so easy to have your own mail server. But nowadays you are more and more opposed by various providers. Common problem: The mail ports are blocked by default.

Unfortunately, the bad ones spoil it for the good users.

**Comment by ghost** [comment]
Just for the record, provider was blocking all incoming traffic on email related ports by default, so maybe you just have to talk to your provider. ;)
