### ISSUE TITLE
[Feature Suggestion] Rspamd 1.7.*

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1231]
As the Rspamd team released a new version: Rspamd 1.7.*
They also changed from development model.

> Release cycle model change
> From this version onwards, Rspamd will no longer have stable and experimental branches. All development will be concentrated in the main branch with more frequent releases of both minor and major versions. Major version change (e.g. from 1.7 to 1.8) will mean some important change with backward compatility or a clear conversion path. Minor releases (e.g. 1.7.0 -> 1.7.1) will be released as soon as there are enough important changes. Any critical fix will cause a new version to be released.
> 
> We have decided to eliminate the concept of stable branches since it makes the processes of development and migration more complicated for both developers and Rspamd users. We will concentrate on stability and backward compatibility of the main branch instead.

**Comment by mkuron** [comment]
In August 2017, we switched to using nightly builds of rspamd, so we have already been using pre-release versions of rspamd 1.7.0. Unless @andryyy wants to switch back to the main branch, there is nothing we need to do.

**Comment by xetorixik** [comment]
@mkuron Thanks for your quick reply.
The rspamd Dockerfile writes about [about xenial main](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/rspamd/Dockerfile#L13) last modified 15 Nov 2017. 

The [Rspamd docker file that is being downloaded is a month old.](https://hub.docker.com/r/mailcow/rspamd/) and https://hub.docker.com/r/mailcow/rspamd/~/dockerfile/

In short therefore my assumption that Mailcow used Rspamd 1.6.
It still seems that way, anyway. Looking at both files above.

Perhaps that's the only thing that left is to ask for upgrading to the latest bits.
As there are a lot of bugs smashed the last weeks.

**Comment by mkuron** [comment]
> The rspamd Dockerfile writes about about xenial main last modified 15 Nov 2017.

The Dockerfile refers to `"deb https://rspamd.com/apt/ xenial main"`, which is the nightly repository, not `"deb https://rspamd.com/apt-stable/ xenial main"`, which is the release repository.

> The Rspamd docker file that is being downloaded is a month old

Ok, so it's a one-month old beta of 1.7. The release 1.7 (or a slightly newer nightly version) will come when @andryyy rebuilds the image as part of the next update.

**Comment by xetorixik** [comment]
@mkuron 
You are absolutely right.
Of course I should have looked further and assumed that main, is the main repo, thus allways stable.
I am not a fan of Debian and Ubuntu but that is obviously a weak excuse :)

> The Dockerfile refers to "deb https://rspamd.com/apt/ xenial main", which is the nightly repository, not "deb https://rspamd.com/apt-stable/ xenial main", which is the release repository.

@andryyy @mkuron and team. Mailcow is great. 
Please forgive my mistake :)

Looking forward to the latest Rspamd bits. 
With love from Belgium, regards.
