### ISSUE TITLE
Form token invalid or timed out

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1233]
Hi there, i am unable to logout nor change any settings after being connected for  a while (more than 24 hours)
On every page refresh i keep seeing "Form token invalid or timed out" and so i am unable to perform any action. The only way to solve is by cleaning browser cache, sessions and cookies. Is there any way we can prevent this behavior?
Thanks

**Comment by andryyy** [comment]
Do you use a user agent changer? Or does your browser update very, very often?

**Comment by lucianlazar1983** [comment]
nope, using google chrome only without any user agent change

--
Lucian Lazar – System Engineer
ecoIT Solutions Srl
@ lucian.lazar@ecoit.ro
Tel +40371783679
www https://www.ecoit.ro
________________________________

**Comment by develth** [comment]
I recognized that on my mobile (Android / Chrome) i always geht 'Form token invalid or timed out' - on my Desktop Chrome everything works fine.

**Comment by ghost** [comment]
Getting the same issue right now, is there a fix/workaround?

**Comment by andryyy** [comment]
I think the major problem is the switching IP (cellular/wifi) and the session binding. I think it is safe to remove the IP check and, if any, replace it by something fail-safe.

**Comment by andryyy** [comment]
Or... wait. I think I removed that check a while ago. This probably happens after a browser update, which happens often on mobile.

**Comment by ghost** [comment]
I installed Firefox on my phone and it worked straight away, tried clearing all browser data on Chrome even using incognito and it kept popping up with the same error. I'll keep Firefox in case I need it again for that :)
