### ISSUE TITLE
Question about Sync Jobs

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1234]
Hi there, i have a question regarding SyncJobs: Can this function be used like ImapSync? My purpose is to:
1) Migrate from an old imap system all mailfolders (with subfolders) and emails
2) Migration process only one-way, from the original server to the new Mailcow server
3) Delete migration job once everything has been transferred to Mailcow.

Can all this be achieved using the inclused Sync Jobs? Sorry for probably a silly question but i was unable to fully understand from official documentation.
Thanks!

**Comment by ghost** [comment]
syncjob is basically imapsync. So yes, that's all possible.

**Comment by mritzmann** [comment]
> Delete migration job once everything has been transferred to Mailcow.

Currently not implemented: https://github.com/mailcow/mailcow-dockerized/issues/1197

**Comment by lucianlazar1983** [comment]
Thank you, one last question: On create new Sync Job, the first parameter is username (existing Mailcow mailbox). This is intended as destination or source for the sync process?
Thanks

**Comment by Lucky88888** [comment]
First occurrence of username (pull menu list)  is the destination username/mailbox the second username occurrence is the username of your remote mailbox (source).

Note: Be aware that in some cases you cannot use the FQN to your old environment as the local dns of your mailcow server points to local machine. Use instead an IP address (one final tip use different passwords on both mailboxes, not only for security reasons ;) ).

**Comment by cm91** [comment]
I have another question regarding the syncjobs.
It would be nice if it would be possible to use "doveadm" to sync mailboxes.
This is a good way to keep 2 mailboxes in sync without having 1 primary and 1 secondary mailbox as it is with imapsync.
