### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#1235]
Hello,

I have the following questions:
- Is it possible to create redirect and autoreponders?
- After following the docs the containers are running in save-modus and after a reboot all data are consistent safed?

Sorry i am not familiar with docker.

Thanks

**Comment by nupplaphil** [comment]
I don't know the answer to your first question

But a reply to your second question:
Your data is saved on [volumes](https://docs.docker.com/storage/volumes/).
If you "just" start mailcow with `docker-compose up -d`, the underlying system would create, per default, **local** volumes for your data, so they are safe after reboots and even if you delete/upgrade the containers.

But beware of the volumes (you can list them with `docker volume ls`)
**Backup them periodically (to other physical drives!)**

Depending of your setup (scale from "just testing" (or just for 1-2 users) to enterprise) choose an appropriate driver for the volumes (see [volume plugins](https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins) )

**Comment by mkuron** [comment]
Regarding question 1: yes, that can be done by configuring Sieve rules, which are available in the SOGo web mailer‘s settings.
