### ISSUE TITLE
Moving Mailcow app from web root

### ISSUE THREAD

**Issue by sebam91** [mailcow/mailcow-dockerized#1239]
Is it safe to change path of mailcow app - move all current web content to folder and have something else as front page? I would like to have my Rainloop on root.

**Comment by mkuron** [comment]
Partial duplicate of #393.

What you are trying to do may work, but is unsupported and may cause issues when upgrading. The recommended way to do this is using a reverse proxy. If you don't want to set up one, you might have success modifying the Nginx config.
