### ISSUE TITLE
Quarantine doesn't work?

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#1241]
I don't see any email in Quarantine in web ui even though rspamd rejected some (I've updated a couple of days ago, so it should be there). Should I configure something?

**Comment by mritzmann** [comment]
Yes, see /admin.php#quarantine. The amount must be defined there.

**Comment by andryyy** [comment]
After checking the configuration, shame me for not updating the docs. :-(

**Comment by pschiffe** [comment]
Right, got it, thanks :)

**Comment by kilo42L** [comment]
I still dont see this in the docs.

**Comment by andryyy** [comment]
Create a PR.

**Comment by thomas126** [comment]
Having the same problem even though I set the admin page up...

**Comment by andryyy** [comment]
Is it rejected by Postscreen or Rspamd?

Oh, can you add screenshot of the config?

**Comment by andryyy** [comment]
Hm, I just checked it and it works as expected here. But let's check your config first. :-)

**Comment by thomas126** [comment]
By Rspamd. I see entries listing rejected but nothing is inside the quarantine.

What confit do you need?

**Comment by andryyy** [comment]
Screenshot of the admin UI (quarantine config) and maybe the reject in Rspamd. 

Are you logged in as admin when you check the quarantine?

**Comment by thomas126** [comment]
I tried both via admin and via mail address. How to add photos?

**Comment by MAGICCC** [comment]
Best way is to use the snipping tool and copy the output picture and paste it just in here. Or save it somewhere on your PC and drag+drop it

**Comment by thomas126** [comment]
![fullsizeoutput_b51a](https://user-images.githubusercontent.com/26501736/45590063-d94bea80-b930-11e8-9ddd-24ca74b3a429.jpeg)
![fullsizeoutput_b523](https://user-images.githubusercontent.com/26501736/45590111-a9511700-b931-11e8-8369-f406da5501a6.jpeg)

**Comment by andryyy** [comment]
Did you exclude your domain in the config? That's the dropdown in the quarantine menu below "max size in mb".

**Comment by thomas126** [comment]
No none. Might it be a problem that the mail is being forwarded by another mail provider?

**Comment by andryyy** [comment]
We need the rspamd-mailcow log for that message (or any, that is not kept) and the php-fpm-mailcow logs. It doesn't matter where the message comes from.

Any firewall?

**Comment by thomas126** [comment]
Ufw is Running. Sorry for the missing text assigning. I can’t work it out from the iPhone.

I couldn’t find the log of the rejected mail. Instead I post a soft reject log. The mail is not in the quarantine. And not in the mailbox.


Log1:
rspamd-mailcow_1     | 2018-09-16 11:20:11 #9(normal) <669f6a>; task; rspamd_task_write_log: id: <dec278e471d135aaf69d42895.1641f05419.20180916090357.29c4159ffe.7bc50b97@mail147.atl171.mcdlv.net>, qid: <A186B3F6C8>, ip: 198.2.138.147, from: <bounce-mc.us1_1757341.280013-me=me.de@mail147.atl171.mcdlv.net>, (default: F (add header): [8.92/15.00] [RSPAMD_URIBL(4.50){page.link;},URIBL_GREY(1.50){list-manage.com.multi.uribl.com;},FROM_EXCESS_QP(1.20){},REPLYTO_EXCESS_QP(1.20){},SUBJ_EXCESS_QP(1.20){},R_DKIM_ALLOW(-0.20){mail147.atl171.mcdlv.net;},R_SPF_ALLOW(-0.20){+ip4:198.2.138.147;},IP_SCORE(-0.16){country: US(-0.78);},MIME_GOOD(-0.10){multipart/alternative;text/plain;},HAS_LIST_UNSUB(-0.01){},MX_GOOD(-0.01){cached: mail.mail147.atl171.mcdlv.net;},ARC_NA(0.00){},ASN(0.00){asn:14782, ipnet:198.2.128.0/19, country:US;},DKIM_TRACE(0.00){mail147.atl171.mcdlv.net:+;},DMARC_NA(0.00){tripwolf.com;},FORGED_SENDER_VERP_SRS(0.00){},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){tripwolf@tripwolf.com;bounce-mc.us1_1757341.280013-me=me.de@mail147.atl171.mcdlv.net;},GREYLIST(0.00){pass;body;},HAS_REPLYTO(0.00){tripwolf@tripwolf.com;},PREVIOUSLY_DELIVERED(0.00){me@me.de;},RCPT_COUNT_ONE(0.00){1;},RCPT_MAILCOW_DOMAIN(0.00){me.de;},RCVD_COUNT_TWO(0.00){2;},RCVD_IN_DNSWL_NONE(0.00){147.138.2.198.list.dnswl.org : 127.0.15.0;},RCVD_NO_TLS_LAST(0.00){},REPLYTO_EQ_FROM(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 68324, time: 3917.125ms real, 47.875ms virtual, dns req: 64, digest: <303c5ac233f79e0536fd81d89d3eecb6>, rcpts: <me@me.de>, mime_rcpts: <me@me.de>

Log2:
php-fpm-mailcow: does not have any log with the specific time stamp...

php-fpm-mailcow_1    | 172.522.1.10 -  16/Sep/2018:10:48:00 +0200 "GET /index.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c69:6f77::1 -  16/Sep/2018:10:48:56 +0200 "GET /index.php" 200
root@docker:/opt/mailcow-dockerized#

**Comment by andryyy** [comment]
Please check the Rspamd docs. It is not a reject but a soft reject. 

A soft reject is a 4.x.x milter reject. A temporary reject. That’s what greylisting is about. This is a very good example how it worked. The spam server didn’t try to redeliver its spam. 

A soft reject should never be put in quarantine, that would be bad. 

I would still need to see both containers logs (not symbols) when a reject happens. 

Since ufw is running, I cannot support this anyway. :-( Something could be blocking the communication between containers. 

I tested it on multiple machines yesterday and can confirm it is working and not a bug in general. 

Again, check and post the container logs, I’m positive it will help resolving the issue. :-)

**Comment by thomas126** [comment]
Well I wasn’t aware of that. It was a newsletter mail and not spam i don’t want to receive. How can I reconfigure to receive those mails then?

Do you recommend disabling any firewall?

Okay thanks for your quick replys. Im waiting for another rejected mail to post the logs.

**Comment by andryyy** [comment]
Hm, RSPAMD_URIBL(4.50){page.link;},URIBL_GREY(1.50) is pretty bad for a newsletter. :-)

Every normal mail server will retry to deliver a mail after a 4.x.x (soft) reject. I could imagine they did and it just landed in your junk folder.

You can whitelist them to always accept their mail.

Yes, I recommend to disable it or be absolutely sure it does not interfere with Dockers iptables rules and brdiges in general.
