### ISSUE TITLE
Quarantine error on one specific mailbox

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1242]
Hi there, my mailcow is set up to serve 3 domains with multiple mailboxes for each domain.
On only one specific mailbox i get the following error every time rspamd rejects a mail:

> got unexpected http status: 503

php-fpm-mailcow log:

> php-fpm-mailcow_1    | [05-Apr-2018 10:52:53] WARNING: [pool www] child 253 said into stderr: "NOTICE: PHP message: quarantine pipe: query mail@example.com as username from mailbox"
php-fpm-mailcow_1    | [05-Apr-2018 10:52:53] WARNING: [pool www] child 253 said into stderr: "NOTICE: PHP message: quarantine pipe: mailbox found: mail@example.com"
php-fpm-mailcow_1    | [05-Apr-2018 10:52:53] WARNING: [pool www] child 253 said into stderr: "NOTICE: PHP message: quarantine pipe: goto array count on loop #1 is 0"
php-fpm-mailcow_1    | [05-Apr-2018 10:52:53] WARNING: [pool www] child 253 said into stderr: "NOTICE: PHP message: quarantine pipe: processing quarantine message for rcpt mail@example.com"
php-fpm-mailcow_1    | [05-Apr-2018 10:52:53] WARNING: [pool www] child 253 said into stderr: "NOTICE: PHP message: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF6rer 1...' for column 'msg' at row 1"

Maybe someone has some advice to get around this error?

**Comment by andryyy** [comment]
I wonder if it would help to run utf8_encode on $raw_data here..

**Comment by andryyy** [comment]
Can you try to change `data/conf/rspamd/meta_exporter/pipe.php`, please? =>


Old:
```
$raw_data = file_get_contents('php://input');
```

New:
```
$raw_data_content = file_get_contents('php://input');
$raw_data = mb_convert_encoding($raw_data_content, 'HTML-ENTITIES', "UTF-8");
```

**Comment by ghost** [comment]
Hi andryyy, thanks for reply. I'll try that and report back asap

**Comment by ghost** [comment]
Hi there!

I tried your changes and now it works as expected. At least the only two(!) rejected spam mails in the last six days were tranfered to the quarantine without any error.
