### ISSUE TITLE
Redirect index to specific folder (multiple domains)

### ISSUE THREAD

**Issue by sebam91** [mailcow/mailcow-dockerized#1243]
I use two domains for my mailcow server

for example
one is mail.first.com (which is also a hostname)
second is second.com

I would like for second.com to redirect to /web/mail/ folder and mail.first.com to stay as it is by default (/web/ as root).

**Comment by mitchellurgero** [comment]
An HTML or PHP redirect might do the trick or if you are hosting both on the same server try nginx redirect for just the second domain.
