### ISSUE TITLE
Security concerns caused by the default password moohoo

### ISSUE THREAD

**Issue by herbetom** [mailcow/mailcow-dockerized#1245]
I have some security concerns about the fact that a preset admin password is used. The user is not told to change it after installation with much insistence. And also if that would be the case somebody could get their before me.

Especially because after mailcow is started the first time their will be some time till LetsEncrypt has run succesfully and all is clear to go. So the user may starts Mailcow, takes a break because it is not responding directly. Comes after a few minutes back and changes the password. But until then many things could have happened. For example if somebody else (human or bot) is able to visit the page while the password is still moohoo he would be able to change things the user might never recognize but which can make some damage. This seems really unreasonable to me.

How difficult would it be to implement a random admin password which is shown in the console to the user?

**Comment by Linus9000** [comment]
Implementing this took me around an hour, it will show the generated password after executing the generate-config.sh. I will gladly submit a pull request if it's wanted by the maintainers :)

**Comment by herbetom** [comment]
I would really like that. You should not forget aubout `mailcow-reset-admin.sh` in the helper-scripts. The hash is their also stored as fixed hash as I have seen it. But that should be really simple easy to solve as in that file only a password must be generated randomly and then hashed and wrote to the DB like it is already the case.

I hope the maintainers are willing to change this, as it is a simple way to increase the security. Fixed default passwords are always a bad idea.

**Comment by andryyy** [comment]
We had this once, I removed it due to the processing of init_db.inc.php and have not re-added it since then. Doing it in Bash is another method. But what happens when something fails? Leave it in mailcow.conf? What happens when you change the admin username?

Implementing the routine is not much work, but it needs to be fail-safe.

We could also implement a modal (or an alert) to warn about an unchanged password.

**Comment by Linus9000** [comment]
Well, I hope my approach should cover the case that "something" fails in that it doesn't introduce that much more failure potential, it's almost entirely reusing code I discovered when finding out how to implement this. 

Feel free to discuss this, maybe something can be worked out :)

**Comment by dannylee71** [comment]
Password is ok

**Comment by herbetom** [comment]
I still think that it is not a good solution not to force the user to change the password in something diffrent then `moohoo`. If changing the password would be neccesary before accesing the config their would be at least a minimum of security that anyone messed sth. up. Although it is not a ideal solution it would be a little bit better then now.
