### ISSUE TITLE
Block all external emails

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1246]
I want to use team@mydomain.com as an internal mail-forwarder. But it should only forward mails to other members if they were sent from my domain.

I tried to blacklist all domains in mailbox settings (*@*.*) and whitelist my domain (*@mydomain.com) - this worked so in Plesk for example.

Is this possible to do this with Mailcow too?

**Comment by davidus05** [comment]
+1

**Comment by mitchellurgero** [comment]
A rule in the soho webui filter with:

If from contains @mydomain.com then forward to c@mydomain.com (repeat this action for as many emails as you have)

Then do another rule where:

If to does not contain @mydomain.com then file in trash.
