### ISSUE TITLE
Recalculate Quote after vmail-Restore

### ISSUE THREAD

**Issue by nupplaphil** [mailcow/mailcow-dockerized#1248]
Hi,

I recently had to restore one user-mailbox from my backup.

Therefore I completly overwrote the vmail-directory in vmail-vol-1 and made a "doveadm force-resync" for this user.

The mails are now restored, but the quota in SOGo and in the admin-panel are still the old values. Is there a way to recalculate the mails for this user?

**Comment by andryyy** [comment]
You probably want to run `docker-compose exec dovecot-mailcow doveadm quota recalc -A` :-)

**Comment by nupplaphil** [comment]
Far to easy. Isn't there a more complicated way ;-)

Earnestly: Thank you!!!! It worked 👍
