### ISSUE TITLE
Last update broke nginx

### ISSUE THREAD

**Issue by maffo999** [mailcow/mailcow-dockerized#1249]
Hi,
after updating to the latest version, the nginx:mainline-alpine container keeps restarting and I can't get it to stay up properly.

The main problem seems to be logged as follows
`2018/04/09 18:22:40 [emerg] 11#11: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
nginx: configuration file /etc/nginx/nginx.conf test failed`

A more extensive log, including the upgrade process followed is available [here](https://pastebin.com/h29RsZGX).

My system is Debian 9.3 updated just before this
`user@######:~/mailcow-dockerized$ uname -a
Linux ###### 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`

Thanks in advance for any help.

**Comment by andryyy** [comment]
I think you installed portainer, right? You can checkout the default site config: `git checkout origin/master data/conf/nginx/site.conf` and restart Nginx: `docker-compose restart nginx-mailcow`

**Comment by maffo999** [comment]
Hi @andryyy,
that did the trick, thanks!

**Comment by maffo999** [comment]
I just ran the update script again and now it worked flawlessly, not sure why this time it did and last week it caused me that problem.

On Monday, April 09, 2018 20:43 CEST, André Peters <notifications@github.com> wrote:
 
I think you installed portainer, right? You can checkout the default site config: git checkout origin/master data/conf/nginx/site.conf
