### ISSUE TITLE
additional_san causing acme error

### ISSUE THREAD

**Issue by epiccitizen-zz** [mailcow/mailcow-dockerized#1250]
I've configured a new mailcow instance. The server has hostname mail.example.com, and serves mail for example.com and example2.com. Both domains have proper A records, etc. 

Browsing to mail.example.com serves the mailcow website great with a valid SSL certificate. 
Browsing to mail.example2.com generates a security warning in Chrome, saying the website is mail.example2.com, but the certificate was issued to mail.example.com. Which is technically accurate. 

I googled, and found the ADDITIONAL_SAN parameter in mailcow.conf. I added mail.example2.com, saved the file, and bounced docker. 

acme-mailcow log shows the following errors:
"acme-client: bad exit: netproc(207):1"
"acme-client: bad exit: challengeproc(210): 1"
"Error requesting certificate, restoring from previous acme request and restarting containers..."

What have I done wrong? I assume if I get mail.example2.com added as a SAN to the certificate that will quiet the security warning in Chrome. How do I figure out why acme or letsencrypt aren't completing the certificate request?

Thanks!

**Comment by catcun** [comment]
Try 
docker-compose logs acme-mailcow

**Comment by andryyy** [comment]
Yes, the logs are important, plus the format you used. You should use it like `BLA=domain1,domain2,domain3` without `""` or spaces.

**Comment by epiccitizen-zz** [comment]
Attached is the acme-mailcow log file. 
Andryyy, are you saying to add an SAN I should use example2.com, not mail.example2.com, even though domain2 is already configured in mailcow UI? It works, I just need the certificate added for the second web interface. 

When view the certificate in chrome, it lists:
DNS Name=autoconfig.domain1.com
DNS Name=autoconfig.domain2.com
DNS Name=autodiscover.domain1.com
DNS Name=autodiscover.domain2.com
DNS Name=mail.domain1.com

So I assumed the new SLA would be the FQDN of the second site. 

[acme-mailcow.txt](https://github.com/mailcow/mailcow-dockerized/files/1895085/acme-mailcow.txt)

**Comment by epiccitizen-zz** [comment]
Just an update,
That log file was generated last night as I was posting this ticket. After that I went to bed. This morning everything is working fine. Mail.example2.com has a valid certificate due to being added as a SAN. Shows up in the certificate details and everything just the way I was hoping. 

My understanding was that it should be a semi-immediate change just by restarting acme-mailcow so I'm not sure why the delay. Anyway, I just wanted to let you two know it worked; And anyone who reads this in the future, wait a while. It should eventually update.

**Comment by mkuron** [comment]
If it fixed itself, either there was a hiccup at Let's Encrypt or your DNS entry hadn't propagated yet. The log entries don't make much sense in either case though.
