### ISSUE TITLE
netfilter is blocking my monitoring host

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1253]
Hi there,

i recognized that my monitoring host´s subnet is blocked by netfilter by matching rule 3. 
How could i prevent that? A new entry in fail2ban parameters wouldn´t solve it.

Thanks!

**Comment by mkuron** [comment]
You can just add its IP address to the fail2ban whitelist in the admin UI and restart the fail2ban-mailcow container. 

If the monitoring host just opens and closes a TCP connection and doesn't authenticate, it does indeed run the risk of getting blocked if not whitelisted.

**Comment by develth** [comment]
I added it to the whitelist and restarted the netfilter container (because there is no fail2ban-mailcow) - resulted in no change - still gets blocked

**Edit**: Nevermind - had an typo in the IP....
Fixed & Thanks!
