### ISSUE TITLE
10Gb limitation on email storage

### ISSUE THREAD

**Issue by Zert** [mailcow/mailcow-dockerized#1255]
Have this error on dockerized mailcow after 10Gb disk quota exceeded: https://github.com/mailcow/mailcow/issues/930
How to fix it?

**Comment by mitchellurgero** [comment]
Sounds like increasing the quota for the domain would help

**Comment by kevinsingapore** [comment]
i have meet the save problem.
and, i want to expand the Domain Quota storage size, how to do ? please.
the information like below:
![image](https://user-images.githubusercontent.com/39163739/77902916-89cfd400-72b4-11ea-9410-34d0f55214b7.png)

**Comment by andryyy** [comment]
Edit the domain and change the domain quota.
