### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by 00tiagopolicarpo00** [mailcow/mailcow-dockerized#1258]
I try restore my datas vol. But give me erros

DRIVER              VOLUME NAME
local               mailcow-dockerized_crypt-vol-1
local               mailcow-dockerized_mysql-vol-1
local               mailcow-dockerized_postfix-vol-1
local               mailcow-dockerized_redis-vol-1
local               mailcow-dockerized_rspamd-sock
local               mailcow-dockerized_rspamd-vol-1
local               mailcow-dockerized_vmail-vol-1
local               mailcowdockerized_crypt-vol-1
local               mailcowdockerized_dkim-vol-1
local               mailcowdockerized_mysql-vol-1
local               mailcowdockerized_postfix-vol-1
local               mailcowdockerized_redis-vol-1
local               mailcowdockerized_rspamd-sock
local               mailcowdockerized_rspamd-vol-1
local               mailcowdockerized_vmail-vol-1

Restoring rspamd from /backup/mailcow-2018-01-16-10-37-00/...
c4325def4467
505d1d808ade
Unable to find image 'mailcow-dockerized_rspamd-vol-1:latest' locally
docker: Error response from daemon: pull access denied for mailcow-dockerized_rspamd-vol-1, repository does not exist or may require 'docker login'.
See 'docker run --help'.
505d1d808ade
c4325def4467

**Comment by andryyy** [comment]
You probably just need to run...
``
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
```
... to remove all containers (also non-mailcow, be aware!).

After that edit `mailcow.conf` and add or change the value of "COMPOSE_PROJECT_NAME" to "mailcowdockerized" -> `COMPOSE_PROJECT_NAME=mailcowdockerized`.
If there is a "COMPOSEPROJECT_NAME", remove that line (note the missing "_").

Now run `docker-compose up -d` to regain access to your volumes.

**Comment by andryyy** [comment]
It would be nice of you to add `set -x` to the second line of `helper-scripts/backup_and_restore.sh` (just below `#!/bin/bash`) and try the restore again. Just paste the output to paste.ee then. 👍 This will help me to fix this issue.

**Comment by 00tiagopolicarpo00** [comment]
/opt/mailcow-dockerized/helper-scripts# ./backup_and_restore.sh restore
+ [[ ! restore =~ (backup|restore) ]]
+ [[ restore == \b\a\c\k\u\p ]]
+ [[ -z '' ]]
+ [[ -z '' ]]
+ read -ep 'Backup location (absolute path, starting with /): ' BACKUP_LOCATION
Backup location (absolute path, starting with /): 


+ [[ -z /backup ]]
+ [[ ! /backup =~ ^/ ]]
+ [[ -f /backup ]]
+ [[ ! -d /backup ]]
+ [[ restore == \b\a\c\k\u\p ]]
++ sed 's#/$##'
++ echo /backup
+ BACKUP_LOCATION=/backup
+++ dirname ./backup_and_restore.sh
++ cd .
++ pwd
+ SCRIPT_DIR=/opt/mailcow-dockerized/helper-scripts
+ COMPOSE_FILE=/opt/mailcow-dockerized/helper-scripts/../docker-compose.yml
+ echo 'Using /backup as backup/restore location.'
Using /backup as backup/restore location.
+ echo

+ source /opt/mailcow-dockerized/helper-scripts/../mailcow.conf
++ MAILCOW_HOSTNAME=*****************
++ DBNAME=mailcow
++ DBUSER=mailcow
++ DBPASS=***************************
++ DBROOT=***************************
++ HTTP_BIND=0.0.0.0
++ HTTPS_PORT=443
++ HTTPS_BIND=0.0.0.0
++ SMTP_PORT=25
++ SMTPS_PORT=465
++ SUBMISSION_PORT=587
++ IMAP_PORT=143
++ IMAPS_PORT=993
++ POP_PORT=110
++ POPS_PORT=995
++ SIEVE_PORT=4190
++ TZ=Europe/Lisbon
++ COMPOSEPROJECT_NAME=mailcowdockerized
++ ADDITIONAL_SAN=********************
++ SKIP_LETS_ENCRYPT=n
++ SKIP_IP_CHECK=n
++ SKIP_FAIL2BAN=y
++ SKIP_CLAMD=n
++ DOVEADM_PORT=127.0.0.1:19991
++ USE_WATCHDOG=y
++ WATCHDOG_NOTIFY_EMAIL=watchdog@*****
++ IPV4_NETWORK=172.22.1
++ IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
++ LOG_LINES=9999
++ SYSCTL_IPV6_DISABLED=0
++ SQL_PORT=127.0.0.1:13306
+ [[ restore == \b\a\c\k\u\p ]]
+ [[ restore == \r\e\s\t\o\r\e ]]
+ i=1
+ declare -A FOLDER_SELECTION
++ wc -l
++ find /backup/mailcow-2018-01-16-10-37-00 -maxdepth 1 -type d
+ [[ 1 -lt 1 ]]
++ ls -d /backup/mailcow-2018-01-16-10-37-00/
+ for folder in '$(ls -d ${BACKUP_LOCATION}/mailcow-*/)'
+ echo '[ 1 ] - /backup/mailcow-2018-01-16-10-37-00/'
[ 1 ] - /backup/mailcow-2018-01-16-10-37-00/
+ FOLDER_SELECTION[${i}]=/backup/mailcow-2018-01-16-10-37-00/
+ (( i++ ))
+ echo

+ input_sel=0
+ [[ 0 -lt 1 ]]
+ read -p 'Select a restore point: ' input_sel
Select a restore point: 1
+ [[ 1 -lt 1 ]]
+ [[ 1 -gt 2 ]]
+ i=1
+ echo

+ declare -A FILE_SELECTION
+ RESTORE_POINT=/backup/mailcow-2018-01-16-10-37-00/
++ find /backup/mailcow-2018-01-16-10-37-00/ -maxdepth 1 -type f -regex '.*\(redis\|rspamd\|mysql\|vmail\|postfix\).*'
+ [[ -z /backup/mailcow-2018-01-16-10-37-00/backup_rspamd.tar.gz
/backup/mailcow-2018-01-16-10-37-00/backup_mysql.gz
/backup/mailcow-2018-01-16-10-37-00/backup_postfix.tar.gz
/backup/mailcow-2018-01-16-10-37-00/backup_vmail.tar.gz
/backup/mailcow-2018-01-16-10-37-00/backup_redis.tar.gz ]]
++ ls -f /backup/mailcow-2018-01-16-10-37-00/
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ backup_rspamd.tar.gz =~ vmail ]]
+ [[ backup_rspamd.tar.gz =~ redis ]]
+ [[ backup_rspamd.tar.gz =~ rspamd ]]
+ echo '[ 1 ] - Rspamd data'
[ 1 ] - Rspamd data
+ FILE_SELECTION[${i}]=rspamd
+ (( i++ ))
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ backup_mysql.gz =~ vmail ]]
+ [[ backup_mysql.gz =~ redis ]]
+ [[ backup_mysql.gz =~ rspamd ]]
+ [[ backup_mysql.gz =~ postfix ]]
+ [[ backup_mysql.gz =~ mysql ]]
+ echo '[ 2 ] - SQL DB'
[ 2 ] - SQL DB
+ FILE_SELECTION[${i}]=mysql
+ (( i++ ))
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ backup_postfix.tar.gz =~ vmail ]]
+ [[ backup_postfix.tar.gz =~ redis ]]
+ [[ backup_postfix.tar.gz =~ rspamd ]]
+ [[ backup_postfix.tar.gz =~ postfix ]]
+ echo '[ 3 ] - Postfix data'
[ 3 ] - Postfix data
+ FILE_SELECTION[${i}]=postfix
+ (( i++ ))
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ . =~ vmail ]]
+ [[ . =~ redis ]]
+ [[ . =~ rspamd ]]
+ [[ . =~ postfix ]]
+ [[ . =~ mysql ]]
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ .. =~ vmail ]]
+ [[ .. =~ redis ]]
+ [[ .. =~ rspamd ]]
+ [[ .. =~ postfix ]]
+ [[ .. =~ mysql ]]
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ backup_vmail.tar.gz =~ vmail ]]
+ echo '[ 4 ] - Mail directory (/var/vmail)'
[ 4 ] - Mail directory (/var/vmail)
+ FILE_SELECTION[${i}]=vmail
+ (( i++ ))
+ for file in '$(ls -f "${FOLDER_SELECTION[${input_sel}]}")'
+ [[ backup_redis.tar.gz =~ vmail ]]
+ [[ backup_redis.tar.gz =~ redis ]]
+ echo '[ 5 ] - Redis DB'
[ 5 ] - Redis DB
+ FILE_SELECTION[${i}]=redis
+ (( i++ ))
+ echo

+ input_sel=0
+ [[ 0 -lt 1 ]]
+ read -p 'Select a dataset to restore: ' input_sel

Select a dataset to restore: 1
+ [[ 1 -lt 1 ]]
+ [[ 1 -gt 6 ]]
+ echo 'Restoring rspamd from /backup/mailcow-2018-01-16-10-37-00/...'
Restoring rspamd from /backup/mailcow-2018-01-16-10-37-00/...
+ restore /backup/mailcow-2018-01-16-10-37-00/ rspamd
++ docker ps -qf name=watchdog-mailcow
+ docker stop 8a5c2738d659
8a5c2738d659
+ RESTORE_LOCATION=/backup/mailcow-2018-01-16-10-37-00/
+ shift
+ ((  1  ))
+ case "$1" in
++ docker ps -qf name=rspamd-mailcow
+ docker stop 56efdce4bb7c
56efdce4bb7c
++ docker volume ls -qf name=rspamd
+ docker run -it --rm -v /backup/mailcow-2018-01-16-10-37-00/:/backup -v mailcow-dockerized_rspamd-sock mailcow-dockerized_rspamd-vol-1 mailcowdockerized_rspamd-sock mailcowdockerized_rspamd-vol-1:/rspamd debian:stretch-slim /bin/tar -xvzf /backup/backup_rspamd.tar.gz
Unable to find image 'mailcow-dockerized_rspamd-vol-1:latest' locally
docker: Error response from daemon: pull access denied for mailcow-dockerized_rspamd-vol-1, repository does not exist or may require 'docker login'.
See 'docker run --help'.
++ docker ps -aqf name=rspamd-mailcow
+ docker start 56efdce4bb7c
56efdce4bb7c
+ shift
+ ((  0  ))
++ docker ps -aqf name=watchdog-mailcow
+ docker start 8a5c2738d659
8a5c2738d659

**Comment by andryyy** [comment]
Oh, I see. I will fix it later today. 

You are fine proceeding with the given steps above. :-)
