### ISSUE TITLE
Outgoing email not saved

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1259]
my outgoing emails is not save in sent after a send!
In android and ms outlook! from web panel all is good.
In rspamd email "no action" tag!

**Postfix** 
12.04.2018, 14:28:34 | info | CCDD27FF20: to=<USER@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.166.26]:25, delay=3.5, delays=1.2/0.03/0.48/1.8, dsn=2.0.0, status=sent (250 2.0.0 OK 1523532514 v11si2335337wri.218 - gsmtp)
-- | -- | --
12.04.2018, 14:28:32 | info | Trusted TLS connection established to gmail-smtp-in.l.google.com[64.233.166.26]:25: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)

**Dovecot** 
12.04.2018, 14:28:34	info	lmtp(13114): Disconnect from 172.22.1.9: Successful quit
12.04.2018, 14:28:34	info	lmtp(mail@site.com): 4PRnE+JCz1o6MwAAZ+wXZA: sieve: msgid=<20180412112834.46B6C8A815@mail.site.com>: stored mail into mailbox 'INBOX'
12.04.2018, 14:28:34	info	lmtp(mail@site.com): 4PRnE+JCz1o6MwAAZ+wXZA: sieve: msgid=<20180412112834.46B6C8A815@mail.site.com>: discarded vacation reply to <>
12.04.2018, 14:28:34	info	lmtp(13114): Connect from 172.22.1.9

**Comment by twixi** [comment]
F@@ked outlook with default settings.

**Comment by hamedty** [comment]
I still have issue with this:

When I send an email from SMTP client (here: gmail connected to mailcow), the email reaches the destination perfectly, but is not stored in the SOGo sent folder. Sending from SOGo is good though. 

From logs I can say it hits `postfix`, but not `dovecot`. Any idea?

**Comment by andryyy** [comment]
Just check where your client stores it. It is not something a mail server does by itself.

**Comment by mkuron** [comment]
@hamdty: If you send from an alternate sender address in Gmail, only Gmail will store the message in its sent folder. It's the client's job to store a copy in Mailcow's sent folder via IMAP, and Gmail doesn't do that.

**Comment by ademenev** [comment]
I am having the same issue, and observing a strange behavior:

When email is sent using a web application (PHP with PHPMailer), it is not stored in Sent. But emails sent with Mail program on MacOS or iOS are saved in Sent

**Comment by andryyy** [comment]
That's normal.

SMTP and IMAP are independent from each other. There is no need to talk to IMAP when you send a mail via SMTP. What a client normally does is 1) send via SMTP, 2) place a copy to Sent.

**Comment by ademenev** [comment]
I have 2 SMTP clients. Both using same account, with identical settings. Mail sent by one of the clients is saved in Sent, mail from the other one is not.

I cannot call that normal

**Comment by ademenev** [comment]
And I am talking about mailcow's dovecot Sent folder

**Comment by andryyy** [comment]
It's perfectly fine. How would the SMTP protocol place a mail into an IMAP folder?
You need to do that as second step if you want to keep a copy. There is simply no correlation.

**Comment by ademenev** [comment]
Ah, got it. That's email client appending the sent message to Sent, correct?

**Comment by andryyy** [comment]
Yes :)
