### ISSUE TITLE
Login for mailcow, sogo and mail clients broken

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1260]
Hello,

i made some minutes before updates on my system. Ubuntu 16.04 have a new docker ce version. This time, i shutdown mailcow before with docker-compose down and then i run the apt dist-upgrade. Next step was ./update.sh to get the minor change in the update script from today. Here i got an warning that the docker network was not found, but this was ok because of the manual shutdown. After this steps, mailcow seems to run, but i can't login at mailcow admin interface, not in sogo and now my mailclients also ask for an password. docker ps shows that the containers must be running. What could be happend?

**Comment by andryyy** [comment]
Try this:

```
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
```
Run update again.

**Comment by lgusewski** [comment]
Thank you, all logins now working again.
