### ISSUE TITLE
nextcloud installation error on Centos7 Host

### ISSUE THREAD

**Issue by Andware** [mailcow/mailcow-dockerized#1261]
Hello 

When I try to install nextcloud with helper script nextcloud, I receive the following error on CentOS7 Host.

sh nextcloud.sh --install
which: no dirmngr in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Cannot find dirmngr, exiting...

How I can fix this?

/Andreas

**Comment by MAGICCC** [comment]
By installing `dirmngr`
http://rpmfind.net/linux/rpm2html/search.php?query=dirmngr

**Comment by Andware** [comment]
Thanks @MAGICCC. It worked for my but I also had to install b2zip. I can close this Issue
