### ISSUE TITLE
Monitoring Quota - Nagios

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#1263]
Hi,
I would like to monitor all user's quota with Nagios. This plugins seems nice but I don't know how to implement this since it's dockerized.
https://exchange.nagios.org/directory/Plugins/System-Metrics/File-System/check_quota-2Epl/details

Does someone have an idea or experience?

We're on git commit bc3daa836ffa4bb848a34aacc486a7bb3cd1fbf4

ty

**Comment by andryyy** [comment]
This seems like a plugin to monitor filesystem quotas.

**Comment by imp1sh** [comment]
Right, my fault.
I found the table quota2 in the database. What is best practice to get the user's current level of usage? I will script myself a solution then.

**Comment by andryyy** [comment]
You could parse the output of `docker exec -it $(docker ps -f name=dovecot-mailcow -q) doveadm quota get -A`. Or read it from the database.
