### ISSUE TITLE
helper-scripts Backup not working

### ISSUE THREAD

**Issue by cataldoc** [mailcow/mailcow-dockerized#1264]
Hi !

I tried using the helper script to backup my installation (as explained in the documentation) but it doesn't seems to work

```
root@smtp:~/mailcow-dockerized# ./helper-scripts/backup_and_restore.sh backup all
Backup location (absolute path, starting with /): /backup/
Using /backup as backup/restore location.

docker: invalid reference format.
See 'docker run --help'.
OK
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
```

**Comment by MAGICCC** [comment]
Just tested it with latest master and it works. Be sure you have updated mailcow + running latest docker-ce (which is 18.03)

**Comment by fibis** [comment]
I have the newest mailcow version and docker-ce 18.03 and get the same error.

**Comment by byteturtle** [comment]
Same here on Docker version 18.04.0-ce, build 3d479c0 on Debian Stretch.

**Comment by wucke13** [comment]
Same here, `Docker version 18.03.0-ce, build 0520e24` and Debian Stretch.

**Comment by MAGICCC** [comment]
`0520e24` nor `3d479c0` is latest master. Be sure you look at the actual commits and the not the commit which the updater does while merging.
I tried with Debian Stretch as well, but works fine.
What's your output of `docker info`?

**Comment by byteturtle** [comment]
```3d479c0``` is my Docker build version.
I'm currently on https://github.com/mailcow/mailcow-dockerized/commit/03ed132363bf8ec4d73ca9055471b5abb94634e5

Output of  ```docker info```

```
Containers: 16
 Running: 16
 Paused: 0
 Stopped: 0
Images: 171
Server Version: 18.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.957GiB
Name: shigure
ID: 5VC2:Q2QN:H5E5:JBL2:AV33:DBQI:SGXN:SDZD:XGYY:GJGZ:XP7R:2K3P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by 00tiagopolicarpo00** [comment]
And over last update, i lost acess my settings, account,mailboxs user, reset setting to default install.
i have this error two, on backup all or restore. 
Containers: 16
 Running: 16
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.828GiB
Name: mx.local
ID: VWED:I4CE:HOE5:QW5A:JNUB:KPAV:522V:FOQI:PGQR:CI5X:4JM5:D6PV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

 docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               mainline-alpine     ebe2c7c61055        8 days ago          18MB
mailcow/unbound     1.1                 4b89d5b2bb6f        11 days ago         18.7MB
mailcow/acme        1.28                0fa7825bd98e        12 days ago         51.5MB
mailcow/clamd       1.9                 3fb550986d7c        12 days ago         187MB
memcached           alpine              44e151ee7837        2 weeks ago         7.88MB
mariadb             10.2                ca06ca3d8fad        2 weeks ago         396MB
redis               alpine              98bd7cfc43b8        3 weeks ago         27.8MB
debian              stretch-slim        dd99abd0503e        5 weeks ago         55.3MB
mailcow/sogo        1.20                b47376b55695        6 weeks ago         467MB
mailcow/dovecot     1.24                fd4a87260ace        7 weeks ago         442MB
mailcow/postfix     1.14                088f5257e867        7 weeks ago         156MB
robbertkl/ipv6nat   latest              20acd6529e3e        7 weeks ago         21.6MB
mailcow/dockerapi   1.9                 63ff2c4ea054        8 weeks ago         92.7MB
mailcow/phpfpm      1.12                dcee8e3e11a8        8 weeks ago         271MB
mailcow/netfilter   1.11                583a7b56e240        2 months ago        66.8MB
mailcow/watchdog    1.14                8f8b9aa1b7fe        2 months ago        59.3MB
mailcow/rspamd      1.17                5deeeadb3fc9        2 months ago        320MB

docker volume list
DRIVER              VOLUME NAME
local               mailcow-dockerized_crypt-vol-1
local               mailcow-dockerized_mysql-vol-1
local               mailcow-dockerized_postfix-vol-1
local               mailcow-dockerized_redis-vol-1
local               mailcow-dockerized_rspamd-sock
local               mailcow-dockerized_rspamd-vol-1
local               mailcow-dockerized_vmail-vol-1
local               mailcowdockerized_crypt-vol-1
local               mailcowdockerized_mysql-vol-1
local               mailcowdockerized_postfix-vol-1
local               mailcowdockerized_redis-vol-1
local               mailcowdockerized_rspamd-sock
local               mailcowdockerized_rspamd-vol-1
local               mailcowdockerized_vmail-vol-1

**Comment by andryyy** [comment]
Please try to find the other issues. Also try to run ./update.sh again.

**Comment by 00tiagopolicarpo00** [comment]
@andryyy I received over telegram notification, and I just did update.sh , but the problem is continues.

**Comment by andryyy** [comment]
This is a very easy fix explained in the other issues, but can you please give me access to this machine to check why the update script fails to adjust the values?

**Comment by wucke13** [comment]
Lost everything on the last update too (blank install afterwards). Had a backup laying around, gratefully. Maybe put a warning not to update as long as this happens?

**Comment by andryyy** [comment]
You did not lose everything. The volume names just changed. There are 5 issues or more regarding this error.

You can give me access to the machine to check why the sed commands did not replace the compose project name.

**Comment by wucke13** [comment]
I fixed it myself renaming the volumes, so everything is ok atm. Is that the only "breaking" which might happen on an update?

**Comment by andryyy** [comment]
Yes, I still need a failing machine to test the update script. The sed commands should not fail. But they do. @mkuron any idea?

**Comment by byteturtle** [comment]
I could offer mine, but renaming worked flawlessly as far as i can see. Only the backup and restore script is failing (as OP states)

**Comment by MAGICCC** [comment]
I wonder what happens when you run `docker run  --rm -v backup/mailcow-$(date +"%Y-%m-%d-%H-%M-%S"):/backup -v $(docker volume ls -qf name=redis-vol-1):/vmail debian:stretch-slim /bin/tar -cvpzf /backup/backup_vmail.tar.gz /vmail`
I guess you'll get the same error message...

Does the `docker run` command fail or some other part of the command? You can test it e.g. with `docker run --rm debian:stretch-slim echo "test"` - it should output 'test'.

Can you also state where you host the server? Maybe they use some weird selfbuild Debian image

**Comment by mkuron** [comment]
@andryyy, I have to admit I have never used the update script. My prior `sed` experience however suggests that there are at least three different implementations (BSD, GNU and Busybox) that all support a different set of arguments, behave differently with respect to inplace mode and have different regex engines.

Another problem with the current update script is that it also changes the project name if someone has manually edited it.

**Comment by andryyy** [comment]
Hm, that was my first guess, too. 

It should only fix a misspelled COMPOSEPROJECT_NAME variable name and remove hyphens and underscores from custom names.

**Comment by byteturtle** [comment]
```docker run```works in general, seems some other part of that command is failing.


The server mailcow is running on was installed from a debian-9.3.0-amd64-netinst.iso directly from the official debian site.
```
docker run --rm -v backup/mailcow-$(date +"%Y-%m-%d-%H-%M-%S"):/backup -v $(docker volume ls -qf name=mailcowdockerized_postfix-vol-1):/vmail debian:stretch-slim /bin/tar -cvzf /backup/backup_vmail.tar.gz /vmail
docker: Error response from daemon: create backup/mailcow-2018-04-19-21-35-40: "backup/mailcow-2018-04-19-21-35-40" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.```

When passing the absolute path this command completes without error

The command you provided ends in docker: invalid reference format. again

**Comment by MAGICCC** [comment]
Oh I missed a leading / in the command...
Ah damn, it's odd that you cant even run a simple container. I may install debian 9.3.0 from an .iso and test it. Latest on debian.org is 9.4.0, but I doubt its something wrong with that image, since docker is somewhat using its own workspace...

**Comment by byteturtle** [comment]
Maybe i wrote it the wrong way: ```docker run --rm debian:stretch-slim echo "test"``` works just fine for me.

**Comment by byteturtle** [comment]
In the backup section i changed the part ```docker volume ls -qf name=vmail-vol-1``` to ```docker volume ls -qf name=${COMPOSE_PROJECT_NAME}_vmail-vol-1``` (for each volume of course) which worked for me to backup. Restore is another thing, but at least this seems to output valid backup data.

**Comment by andryyy** [comment]
Yes, due to possible duplicates from when the project name changed, you may have two volumes of the same type.
Another fix would be to run (while mailcow is up and running, this is important!): `docker volume rm $(docker volume ls -q -f dangling=true)`
