### ISSUE TITLE
Home internet connection blocked by Mailcow

### ISSUE THREAD

**Issue by rototom** [mailcow/mailcow-dockerized#1269]
This is a strange problem:
I use mailcow on my server and it runs without problems, but:
When I add a mailcow account in thunderbird, my server becomes unresponsive from my home-internet. IT is reachable from anywhere else but from my home. As soon as I do docker-compose stop, its fine again. When the problem comes up, I cant even ping my server, nor does anything other work.

**Comment by mkuron** [comment]
That‘s the fail2ban container. If there are a few failed authentication attempts from an IP address (like your home), it blocks all connections to that address. Make sure you enter the correct user and password in Thunderbird so this doesn‘t happen. As a temporary workaround, you can also whitelist your home IP address in Mailcow‘s web UI.

**Comment by rototom** [comment]
I cant remember to have typed my password wrong, any time.

**Comment by rototom** [comment]
How can I find logs for fail2ban? THis happens everytime, when I add a mailaccount with thunderbird. Even if the password is right. (Setup Thunderbird, server becomes unresponsible, restart mailcow, click ok in thunderbird, everything is ok.)

**Comment by andryyy** [comment]
What's your configuration for Fail2ban? You seem to block after 1-2 tries, do you?
You will find the logs @ Netfilter in debug.

**Comment by rototom** [comment]
Never changed fail2ban config, was set to 10 attempts, changed it to 20, but with no success.
