### ISSUE TITLE
Expunge all emails order than X? 

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#1271]
Hello,

I have a question:
How can I delete all mails from all domains in all folders that are older than 180 days?

Here is the code-example from docs (Delete all user's mails in the junk folder that are older than 7 days):
`docker-compose exec dovecot-mailcow doveadm expunge -A mailbox 'Junk' savedbefore 7d`

EDIT: Can this be right that way?:
`docker-compose exec dovecot-mailcow doveadm expunge -A mailbox % savedbefore 180d`

https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-expunge/

Thanks you.

**Comment by MAGICCC** [comment]
After a quick search I couldn't find anything about this, but you can always try such commands when you have backups....
If it's really not possible you can use `doveadm move` and then expunge them from a `expunge` folder

**Comment by omexlu** [comment]
Thanks for your reply, maybe somebody else know if one way @andryyy :)

**Comment by omexlu** [comment]
Hi,

Maybe a way to do this? Or how can i delete them maybe in few steps easly?

Thanks

**Comment by andryyy** [comment]
You may need to run doveadm search and pipe the results to expunge. 

Or try doveadm expunge -A ALL SAVEDBEFORE BLA
