### ISSUE TITLE
Wordpress Mail Problem

### ISSUE THREAD

**Issue by Finnlife** [mailcow/mailcow-dockerized#1272]
Um eine Mailcow Mail zu verwenden habe ich das Plugin "Easy WP SMTP" installiert.

Leider kommen bei jeder versuchter konfiguration nur Errors.

Hier die letzten Einstellungen:

http://prntscr.com/j5kelb

Und der Error:

 http://prntscr.com/j5kfs1

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/38780392-c85d24ec-40d5-11e8-996a-0d9a5646441b.png)

:-)

**Comment by andryyy** [comment]
Bitte als Mailserver auch den FQDN verwenden! Du hast als MAILCOW_HOSTNAME bestimmt nicht afk-army.de angegeben, richtig? Das wäre falsch. Richtig ist etwa "mail.afk-army.de".

**Comment by Finnlife** [comment]
Ich glaube des afk-army.de:8082 schon richtig ist. Ich habe den Port 80 auf 8082 verändert.

**Comment by andryyy** [comment]
Aber das ist der Webserver von mailcow, nicht Postfix. Er will nur den Servernamen von dir haben. Port 587 ist soweit korrekt, nur muss dann TLS ausgewählt werden.

Wichtig ist aber wirklich, dass du einen FQDN verwendest und nicht "afk-army.de" (kein FQDN).

**Comment by Finnlife** [comment]
So richtig: 
http://prntscr.com/j5kj0s

Wenn ja, der Fehler:
http://prntscr.com/j5kjz2

**Comment by Finnlife** [comment]
Ich glaube ich habe als Host "afk-army.de" eingegeben und nicht "mail.afk-army.de" Wie kann ich das jetzt noch ändern. ?

**Comment by andryyy** [comment]
`docker-compose down`, mailcow.conf anpassen, `docker-compose up -d`.

Im DNS muss es mail.afk-army.de natürlich noch geben. 👍

**Comment by Finnlife** [comment]
Leider ein Fehler: http://prntscr.com/j5ks3l
und http://prntscr.com/j5kss9

**Comment by andryyy** [comment]
Der ganze interessante Rest fehlt. Er schreibt dir auch, warum ein Fehler auftrat.

**Comment by Finnlife** [comment]
Der ganze Fehler: http://prntscr.com/j5kud7

**Comment by andryyy** [comment]
Irgendwas läuft noch auf Port 25. Bestimmt exim4 oder Postfix von der Installation des Betriebssystems. Das haben wir in den docs irgendwo beschrieben. Musst den Dienst beenden und deaktivieren oder das Paket entfernen. Alternativ kann der vorinstallierte Mailserver umkonfiguriert werden.

**Comment by Finnlife** [comment]
Also der befehl ist jetzt durch gegangen.

Beim testen kommt dann das: http://prntscr.com/j5l79u

**Comment by tkorves** [comment]
Es fehlt mal wieder die Haelfte der Fehlermeldung - aber das, was sie aussagt, solltest Du schon verstehen @Finnlife - ansonsten wuerde ich Dir dringend davon abraten, einen eigenen Mailserver oder irgendeinen anderen Server zu betreiben - sorry, ist nicht boese gemeint, aber das, was ich hier lese, ist gar nicht gut.

Auf Port 25 lauscht nun nichts mehr, mailcow-dockerized durchstarten und gut ist.

**Comment by Finnlife** [comment]
Ich habe mailcow neugestartet (docker-compose down und docker-compose up -d) und es dann noch einmal probiert

Wieder ein Fehler:
http://prntscr.com/j5m4kx
Ich wüsste jetzt nicht, was bei diesem Fehler fehlt.
Und ich sehe jetzt auch nicht, was er bedeutet. Nur das er sich nicht verbinden konnte.

**Comment by tkorves** [comment]
Die von Dir benutzte Config des Wordpress Plugins scheint kein TLS zu sprechen bzw Deinen Mailserver auf dem falschen Port anzusprechen - das ist KEIN Mailcow-Fehler, denn ich benutze fuer einen Kunden auch Wordpress und Mailcow in genau der selben Konstellation.

**Comment by andryyy** [comment]
Brauchst sie ja nicht locken, er kann ja weiter nachfragen.

Eventuell hat er SSL anstatt TLS bei seinem Test angehakt und dann die eigenartigen Zeichen zurückbekommen.

**Comment by Finnlife** [comment]
Ich habe jetzt ein anderes Mail Plugin probiert. Auch ein Fehler. Welches Plug-in nutzt den der Kunde für ein Plug-in? Oder gibt es da eine andere Möglichkeit.
