### ISSUE TITLE
SOGo change base url

### ISSUE THREAD

**Issue by oncul** [mailcow/mailcow-dockerized#1274]
Hi, how can i change /SOGo base url. I modified site.conf but i think i need to modify Sogo HTML files. I newbie on docker

```
In login page js line
var ApplicationBaseURL = '/SOGo/so/';
```

**Comment by mritzmann** [comment]
does that help? https://github.com/mailcow/mailcow-dockerized/issues/393

**Comment by mkuron** [comment]
Duplicate of #393

**Comment by maverick85** [comment]
how can a post be duplicate of self?
