### ISSUE TITLE
Mailcow reset after upgrade

### ISSUE THREAD

**Issue by Ric878** [mailcow/mailcow-dockerized#1275]
Hi,

Last night, I ran the upgrade update.sh script. Everything seemed to run okay but after the update was complete my entire installation was reset back to defaults. No domains, no mailboxes. Everything seems to be gone. Is there any way to revert?

Thanks,
Ric

**Comment by mritzmann** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/1178

**Comment by Ric878** [comment]
Thanks, should have done a bit more searching.
