### ISSUE TITLE
Autodiscover when using nginx proxy

### ISSUE THREAD

**Issue by rototom** [mailcow/mailcow-dockerized#1278]
I use mailcow behind a "normal" nginx installation on my server.
nginx-vhostfile:
https://code.okaris.de/akefiliruv.nginx
Autoconfig/discover fails, due to a missing certificate, so what can I do?

**Comment by chriscroome** [comment]
Get a Let's Encrypt certificate for your server?

That is what I have done, see #461, also remember that a reverse proxy for `autodiscover.*` can be used to bypass fail2ban abuse blocking.

**Comment by HesselTjeerdsma** [comment]
Make sure mailcow is availabe at port 80. So, do not use the redirect all traffic function of certbot. Port 80 is required for the acme check. After opening port 80, restart the acme container.

**Comment by mkuron** [comment]
You can try to use the Let‘s Encrypt certificate generated by Mailcow with the reverse proxy, for which you need to write some custom scripts. Or you can generate a separate certificate for the reverse proxy with all hostnames, including the autodiscovery/autoconfig ones. Note that the challenge path (/.well-known/acme-challenge cannot be used by both at the same time, so it‘s a bit difficult to use separate Let‘s Encrypt certificates for both.

@chriscroome, autodiscover, fail2ban and reverse proxies work together just fine if the proxy adds an `X-Forwarded-For` header and runs on the Docker host (i.e. not on a different host and not inside Docker).
