### ISSUE TITLE
HTTPS is broken

### ISSUE THREAD

**Issue by SimPlaysGames** [mailcow/mailcow-dockerized#1279]
I am trying to set up the mail server. Had a clean install of ubuntu 16.04.

I follow the guide as well as I could, but when trying to get an SSL certificate something goes wrong. It says the certificate is valid and trusted. But there are resources with certificate errors. How would I go about solving this? 

![image](https://user-images.githubusercontent.com/10297585/38864884-67e9ffb4-423c-11e8-94f5-ec5fd4dc7a90.png)

**Comment by develth** [comment]
Whats in the acme-mailcow logs?

**Comment by SimPlaysGames** [comment]
Ok, so now I got the main url working with ssl, but if I use an alternative url. It doesn't give it a cert. So I get error for it having the main url cert.
Main: cow.(domain).no
alternative (domain).no

**Comment by develth** [comment]
Logs...?

**Comment by SimPlaysGames** [comment]
Doesn't say anything in the acme-mailcow logs about that the alternative domain

**Comment by SimPlaysGames** [comment]
`4/17/2018, 3:44:11 PM	ACME certificate validation done. Sleeping for another day.
4/17/2018, 3:44:11 PM	Certificate was not changed
4/17/2018, 3:44:11 PM	Verified hashes.
4/17/2018, 3:44:11 PM	acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating) acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating) acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left acme-client: adding SAN: autoconfig.{another-domain}.no acme-client: adding SAN: autoconfig.{my-domain}.no acme-client: adding SAN: autodiscover.{another-domain}.no acme-client: adding SAN: autodiscover.{my-domain}.no acme-client: adding SAN: mail.{my-domain}.no
4/17/2018, 3:44:11 PM	Confirmed A record mail.{my-domain}.no
4/17/2018, 3:44:11 PM	Found A record for mail.{my-domain}.no: {my-ip}
4/17/2018, 3:44:11 PM	Confirmed A record cow.{my-domain}.no
4/17/2018, 3:44:11 PM	Found A record for cow.{my-domain}.no: {my-ip}
4/17/2018, 3:44:11 PM	Confirmed A record autodiscover.{my-domain}.no
4/17/2018, 3:44:11 PM	Found A record for autodiscover.{my-domain}.no: {my-ip}
4/17/2018, 3:44:11 PM	Confirmed A record autoconfig.{my-domain}.no
4/17/2018, 3:44:11 PM	Found A record for autoconfig.{my-domain}.no: {my-ip}
4/17/2018, 3:44:10 PM	Confirmed A record autodiscover.{another-domain}.no
4/17/2018, 3:44:10 PM	Found A record for autodiscover.{another-domain}.no: {my-ip}
4/17/2018, 3:44:10 PM	Confirmed A record autoconfig.{another-domain}.no
4/17/2018, 3:44:10 PM	Found A record for autoconfig.{another-domain}.no: {my-ip}
4/17/2018, 3:44:07 PM	Found domain tables.
4/17/2018, 3:44:07 PM	Waiting for domain table...
4/17/2018, 12:42:46 PM	ACME certificate validation done. Sleeping for another day.
4/17/2018, 12:42:46 PM	Certificate was not changed
4/17/2018, 12:42:46 PM	Verified hashes.
4/17/2018, 12:42:46 PM	acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating) acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating) acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left acme-client: adding SAN: autoconfig.{another-domain}.no acme-client: adding SAN: autoconfig.{my-domain}.no acme-client: adding SAN: autodiscover.{another-domain}.no acme-client: adding SAN: autodiscover.{my-domain}.no acme-client: adding SAN: mail.{my-domain}.no
4/17/2018, 12:42:46 PM	Confirmed A record mail.{my-domain}.no
4/17/2018, 12:42:46 PM	Found A record for mail.{my-domain}.no: {my-ip}
4/17/2018, 12:42:46 PM	Confirmed A record cow.{my-domain}.no
4/17/2018, 12:42:46 PM	Found A record for cow.{my-domain}.no: {my-ip}
4/17/2018, 12:42:45 PM	Confirmed A record autodiscover.{my-domain}.no
4/17/2018, 12:42:45 PM	Found A record for autodiscover.{my-domain}.no: {my-ip}
4/17/2018, 12:42:45 PM	Confirmed A record autoconfig.{my-domain}.no
4/17/2018, 12:42:45 PM	Found A record for autoconfig.{my-domain}.no: {my-ip}
4/17/2018, 12:42:45 PM	Confirmed A record autodiscover.{another-domain}.no
4/17/2018, 12:42:45 PM	Found A record for autodiscover.{another-domain}.no: {my-ip}
4/17/2018, 12:42:45 PM	Confirmed A record autoconfig.{another-domain}.no
4/17/2018, 12:42:45 PM	Found A record for autoconfig.{another-domain}.no: {my-ip}
4/17/2018, 12:42:42 PM	Found domain tables.
4/17/2018, 12:42:42 PM	Waiting for domain table...
4/17/2018, 12:42:33 PM	Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: autoconfig.{another-domain}.no autoconfig.{my-domain}.no autodiscover.{another-domain}.no autodiscover.{my-domain}.no cow.{my-domain}.no mail.{my-domain}.no
4/17/2018, 12:42:32 PM	Found Docker API
4/17/2018, 12:42:32 PM	Waiting for Docker API...
4/17/2018, 12:36:32 PM	ACME certificate validation done. Sleeping for another day.
4/17/2018, 12:36:32 PM	command completed successfully
4/17/2018, 12:36:30 PM	Restarting 1557532418ffbc94e837825e2b31cc058fb4110da5f57b798c4d63d367d7c776...
4/17/2018, 12:36:30 PM	command completed successfully
4/17/2018, 12:36:29 PM	Restarting aa3f4d90ea732097b1539a1dbca762e50c404cf1a44a1de1e7a54b37e299db06...
4/17/2018, 12:36:29 PM	command completed successfully
4/17/2018, 12:36:28 PM	Restarting 103eaa396d9f94afdb50dffc2bdbf1dbf87b4f92af8c11eee613958552037d05...
4/17/2018, 12:36:28 PM	Verified hashes.
4/17/2018, 12:36:28 PM	acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating) acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating) acme-client: /var/lib/acme/acme/cert.pem: expanding with domain: autoconfig.{another-domain}.no acme-client: /var/lib/acme/acme/cert.pem: expanding with domain: autoconfig.{my-domain}.no acme-client: /var/lib/acme/acme/cert.pem: expanding with domain: autodiscover.{another-domain}.no acme-client: /var/lib/acme/acme/cert.pem: expanding with domain: autodiscover.{my-domain}.no acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left acme-client: /var/lib/acme/acme/cert.pem: forcing renewal acme-client: adding SAN: autoconfig.{another-domain}.no acme-client: adding SAN: autoconfig.{my-domain}.no acme-client: adding SAN: autodiscover.{another-domain}.no acme-client: adding SAN: autodiscover.{my-domain}.no acme-client: adding SAN: mail.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/directory: directories acme-client: acme-v01.api.letsencrypt.org: DNS: 184.87.187.237 acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28d::3a8e acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28c::3a8e acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: cow.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: autoconfig.{another-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: autoconfig.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: autodiscover.{another-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: autodiscover.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: mail.{my-domain}.no acme-client: /var/www/acme/-REVhCreDNb92eVAtb5UC7PrOu3yXMWzi7DYfzp0UPI: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: challenge acme-client: /var/www/acme/Plmn0aTRcu2q4NUd6HlkvXlxri5judCDc8AHs5TYBmM: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/5eVi OKiSjwdktYMbXPg - Sr01hPcrI2OIqM pREM0/4258417650: challenge acme-client: /var/www/acme/U5iRTF3FCQELXTCb5V9DXIOYc9pRra67cEaH-xjvDn0: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/SxCiSphCPnhWIdS22N5rr1Kt57rZOolzQ8PPjb9w-iY/4258417725: challenge acme-client: /var/www/acme/-SENByRNAiXiKg0BKlcLL-xlaBse5THkFGEAuWsk9sM: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/F-fh8EphvyIW4rcqwVh9UJkMZEczj repL78DvvLsjk/4258417828: challenge acme-client: /var/www/acme/t QRYhoJKhOcVe5LinGqXlH-pTWV1w7Hf9dybbn-yF0: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/SDDzM8RQoehDBIuGkqIlf6LrlmozBaQUc5w4XJT38rU/4258417932: challenge acme-client: /var/www/acme/cNNjUQUqDu0AlCr4IuiKnyQj7iZKHK9JJnqs8jt0CPs: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/-66ibeQoJWb695r8k6 R6Pw6lIkakFOdO-lpbCr1N20/4256968994: challenge acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/5eVi OKiSjwdktYMbXPg - Sr01hPcrI2OIqM pREM0/4258417650: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/SxCiSphCPnhWIdS22N5rr1Kt57rZOolzQ8PPjb9w-iY/4258417725: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/F-fh8EphvyIW4rcqwVh9UJkMZEczj repL78DvvLsjk/4258417828: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/SDDzM8RQoehDBIuGkqIlf6LrlmozBaQUc5w4XJT38rU/4258417932: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/-66ibeQoJWb695r8k6 R6Pw6lIkakFOdO-lpbCr1N20/4256968994: status acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: certificate acme-client: http://cert.int-x3.letsencrypt.org/: full chain acme-client: cert.int-x3.letsencrypt.org: DNS: 92.123.198.214 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:28c::ce0 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:284::ce0 acme-client: /var/lib/acme/acme/cert.pem: linked to cert-1523961388.pem acme-client: /var/lib/acme/acme/chain.pem: linked to chain-1523961388.pem acme-client: /var/lib/acme/acme/fullchain.pem: linked to fullchain-1523961388.pem acme-client: /var/lib/acme/acme/chain.pem: created acme-client: /var/lib/acme/acme/cert.pem: created acme-client: /var/lib/acme/acme/fullchain.pem: created
4/17/2018, 12:35:46 PM	Confirmed A record mail.{my-domain}.no
4/17/2018, 12:35:46 PM	Found A record for mail.{my-domain}.no: {my-ip}
4/17/2018, 12:35:46 PM	Confirmed A record cow.{my-domain}.no
4/17/2018, 12:35:46 PM	Found A record for cow.{my-domain}.no: {my-ip}
4/17/2018, 12:35:46 PM	Confirmed A record autodiscover.{my-domain}.no
4/17/2018, 12:35:46 PM	Found A record for autodiscover.{my-domain}.no: {my-ip}
4/17/2018, 12:35:46 PM	Confirmed A record autoconfig.{my-domain}.no
4/17/2018, 12:35:46 PM	Found A record for autoconfig.{my-domain}.no: {my-ip}
4/17/2018, 12:35:46 PM	Confirmed A record autodiscover.{another-domain}.no
4/17/2018, 12:35:46 PM	Found A record for autodiscover.{another-domain}.no: {my-ip}
4/17/2018, 12:35:44 PM	Confirmed A record autoconfig.{another-domain}.no
4/17/2018, 12:35:44 PM	Found A record for autoconfig.{another-domain}.no: {my-ip}
4/17/2018, 12:35:39 PM	Found domain tables.
4/17/2018, 12:35:39 PM	Waiting for domain table...
4/17/2018, 12:35:02 PM	Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: cow.{my-domain}.no mail.{my-domain}.no
4/17/2018, 10:34:51 AM	ACME certificate validation done. Sleeping for another day.
4/17/2018, 10:34:51 AM	command completed successfully
4/17/2018, 10:34:50 AM	Restarting 1557532418ffbc94e837825e2b31cc058fb4110da5f57b798c4d63d367d7c776...
4/17/2018, 10:34:50 AM	command completed successfully
4/17/2018, 10:34:48 AM	Restarting aa3f4d90ea732097b1539a1dbca762e50c404cf1a44a1de1e7a54b37e299db06...
4/17/2018, 10:34:48 AM	command completed successfully
4/17/2018, 10:34:47 AM	Restarting 103eaa396d9f94afdb50dffc2bdbf1dbf87b4f92af8c11eee613958552037d05...
4/17/2018, 10:34:47 AM	Verified hashes.
4/17/2018, 10:34:47 AM	acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating) acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating) acme-client: acme-client: /var/lib/acme/acme/cert.pem: expanding with domain: mail.{my-domain}.no acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left acme-client: /var/lib/acme/acme/cert.pem: forcing renewal adding SAN: mail.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/directory: directories acme-client: acme-v01.api.letsencrypt.org: DNS: 104.66.96.217 acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28d::3a8e acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28c::3a8e acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: cow.{my-domain}.no acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: mail.{my-domain}.no acme-client: /var/www/acme/-REVhCreDNb92eVAtb5UC7PrOu3yXMWzi7DYfzp0UPI: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: challenge acme-client: /var/www/acme/cNNjUQUqDu0AlCr4IuiKnyQj7iZKHK9JJnqs8jt0CPs: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/-66ibeQoJWb695r8k6 R6Pw6lIkakFOdO-lpbCr1N20/4256968994: challenge acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: status acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/-66ibeQoJWb695r8k6 R6Pw6lIkakFOdO-lpbCr1N20/4256968994: status acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: certificate acme-client: http://cert.int-x3.letsencrypt.org/: full chain acme-client: cert.int-x3.letsencrypt.org: DNS: 23.52.51.36 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:28c::ce0 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:284::ce0 acme-client: /var/lib/acme/acme/cert.pem: linked to cert-1523954087.pem acme-client: /var/lib/acme/acme/chain.pem: linked to chain-1523954087.pem acme-client: /var/lib/acme/acme/fullchain.pem: linked to fullchain-1523954087.pem acme-client: /var/lib/acme/acme/chain.pem: created acme-client: /var/lib/acme/acme/cert.pem: created acme-client: /var/lib/acme/acme/fullchain.pem: created
4/17/2018, 10:34:33 AM	Confirmed A record mail.{my-domain}.no
4/17/2018, 10:34:33 AM	Found A record for mail.{my-domain}.no: {my-ip}
4/17/2018, 10:34:33 AM	Confirmed A record cow.{my-domain}.no
4/17/2018, 10:34:33 AM	Found A record for cow.{my-domain}.no: {my-ip}
4/17/2018, 10:34:33 AM	Found domain tables.
4/17/2018, 10:34:33 AM	Waiting for domain table...
4/17/2018, 10:34:29 AM	Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: cow.{my-domain}.no
4/17/2018, 10:34:29 AM	Found Docker API
4/17/2018, 10:34:29 AM	Waiting for Docker API...
4/17/2018, 10:28:39 AM	ACME certificate validation done. Sleeping for another day.
4/17/2018, 10:28:39 AM	command completed successfully
4/17/2018, 10:28:37 AM	Restarting 1557532418ffbc94e837825e2b31cc058fb4110da5f57b798c4d63d367d7c776...
4/17/2018, 10:28:37 AM	command completed successfully
4/17/2018, 10:28:36 AM	Restarting aa3f4d90ea732097b1539a1dbca762e50c404cf1a44a1de1e7a54b37e299db06...
4/17/2018, 10:28:36 AM	command completed successfully
4/17/2018, 10:28:35 AM	Restarting 103eaa396d9f94afdb50dffc2bdbf1dbf87b4f92af8c11eee613958552037d05...
4/17/2018, 10:28:34 AM	Verified hashes.
4/17/2018, 10:28:34 AM	acme-client: acme-client: /var/lib/acme/acme/private/account.key: generating RSA account key /var/lib/acme/acme/private/privkey.pem: generating RSA domain key acme-client: https://acme-v01.api.letsencrypt.org/directory: directories acme-client: acme-v01.api.letsencrypt.org: DNS: 104.66.96.217 acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28d::3a8e acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:105:28c::3a8e acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: new-reg acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: cow.{my-domain}.no acme-client: /var/www/acme/-REVhCreDNb92eVAtb5UC7PrOu3yXMWzi7DYfzp0UPI: created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: challenge acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/N6lLh8vT-NDaQ0m0gz65CZGo0j7 WBvaR9RclgnUT5Q/4256915240: status acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: certificate acme-client: http://cert.int-x3.letsencrypt.org/: full chain acme-client: cert.int-x3.letsencrypt.org: DNS: 23.52.51.36 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:28c::ce0 acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:105:289::ce0 acme-client: /var/lib/acme/acme/cert.pem: linked to cert-1523953714.pem acme-client: /var/lib/acme/acme/chain.pem: linked to chain-1523953714.pem acme-client: /var/lib/acme/acme/fullchain.pem: linked to fullchain-1523953714.pem acme-client: /var/lib/acme/acme/chain.pem: created acme-client: /var/lib/acme/acme/cert.pem: created acme-client: /var/lib/acme/acme/fullchain.pem: created
4/17/2018, 10:28:21 AM	Confirmed A record cow.{my-domain}.no
4/17/2018, 10:28:21 AM	Found A record for cow.{my-domain}.no: {my-ip}
4/17/2018, 10:28:19 AM	Found domain tables.
4/17/2018, 10:28:18 AM	Waiting for domain table...
4/17/2018, 10:28:06 AM	Found Docker API
4/17/2018, 10:28:06 AM	Waiting for Docker API...
4/17/2018, 10:27:10 AM	Waiting for domain table...
4/17/2018, 10:26:58 AM	Found Docker API
4/17/2018, 10:22:34 AM	Waiting for domain table...
4/17/2018, 10:22:17 AM	Found Docker API
`

Here you got the logs

**Comment by develth** [comment]
Whats in your mailcow.conf in Setting:

    MAILCOW_HOSTNAME
    ADDITIONAL_SAN

**Comment by SimPlaysGames** [comment]
MAILCOW_HOSTNAME=cow.{my-domain}.no
ADDITIONAL_SAN=mail.{my-domain}.no,{my-domain}.no,mail.{another-domain}.no,{another-domain}.no

**Comment by develth** [comment]
And you did the

    docker-compose up -d

afterwards but the error still shows up?

**Comment by SimPlaysGames** [comment]
Still getting this error when trying to access with https
This server could not prove that it is {my-domain}..no; its security certificate is from cow.{my-domain}.no. This may be caused by a misconfiguration or an attacker intercepting your connection.
