### ISSUE TITLE
SpamAssassin configuration

### ISSUE THREAD

**Issue by rootifera** [mailcow/mailcow-dockerized#128]
Hello, 

I just installed mailcow and I can't find "spam filter" configuration in menus. Can you please tell me how can I find that?

Thanks

**Comment by broedli** [comment]
mailcow-dockerized uses rspamd for spam handling. The spam settings are located in the mailcow-user-ci.
![](http://i.imgur.com/bljXyHj.png)

**Comment by andryyy** [comment]
For domain-wide filters you need to edit the specific domain.
