### ISSUE TITLE
sync job hangs

### ISSUE THREAD

**Issue by schnurzli** [mailcow/mailcow-dockerized#1280]
Hi,

i have activated a sync job for an interval of 10 minutes from gmx via imap.
In the beginning it works and after about one day the sync job does'nt sync anymore.
Status says: sync being executed....

Any advice?

**Comment by Braintelligence** [comment]
After one day? Why does syncing take so long? How many GB are we talking about?

**Comment by schnurzli** [comment]
First Sync was about 1 GB. And now there are about 5 to 7 Mails waiting for beeing synced :-)

**Comment by reinistihovs** [comment]
I preffer to sync mails with command line :)
Feel free to use my script:
https://github.com/mailcow/mailcow-dockerized/pull/1251/files

**Comment by theftf** [comment]
I had a similar issue with sync jobs... After a reboot a interuptet job remained running. I needed to set "is_running" to 0 manually in the database to get the queue going again.

**Comment by nicolaspernoud** [comment]
How do you edit the database ?
Anyway, it would be nice to make the sync job reboot proof...

**Comment by theftf** [comment]
@nicolaspernoud 
https://mailcow.github.io/mailcow-dockerized-docs/debug-attach_service/#mysql

You need to change the field "is_running" in the of the "imapsync" table in the "mailcow" database.
Can be checked via: "select is_running from mailcow.imapsync;"
Fixed via: "update mailcow.imapsync set is_running=0;" <--- use with CAUTION :)

**Comment by nicolaspernoud** [comment]
@theftf 
That did the trick ! Thanks a lot !

**Comment by andryyy** [comment]
I integrated it to the image, but have not yet pushed, sorry. :-(
