### ISSUE TITLE
SOGo NSRangeException

### ISSUE THREAD

**Issue by NickUfer** [mailcow/mailcow-dockerized#1281]
Hello,
I just updated my mailcow installation and when I try to log into my email account I am getting the following error message in the console:

```
sogod[44:44] EXCEPTION: <NSException: 0x5602a342e2b0> NAME:NSRangeException REASON:Range location + length too great INFO:(null)
```

That must have something to do with the update. Before that everything worked perfectly

**Comment by andryyy** [comment]
Sounds like the database was not updated. Visit the mailcow UI to update the schema.

**Comment by NickUfer** [comment]
Already tried that but it doesn't seem to work.

**Comment by NickUfer** [comment]
Ok somehow it just worked right now after trying like 20 times...
