### ISSUE TITLE
SOGo password change not working any more

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#1282]
In previous versions i edited in sogo.conf with:
SOGoPasswordChangeEnabled = YES
and then it was possible to change password from SOGo UI.

Now in latest mailcow version, when i attempt to change password, i get this: Unhandled error response

Any ideas how to fix this ?

**Comment by reinistihovs** [comment]
*BUMP*

**Comment by andryyy** [comment]
I don’t think that ever worked. You cannot write to the sql view we use. If that ever worked, it must have been a very old version without any aliases visible to SOGo.

mailcow UI should be used for that anyway. Changing the passwords in SOGo will remove the prepended hash type (if not set in sogo.conf) and possibly cause more trouble.

A user in our IRC channel was able to create a second view for some SOGo table and use it for password changes.

**Comment by andryyy** [comment]
So this is a won’t fix (any time soon - at least), sorry. :-(
