### ISSUE TITLE
Uploading Attachments Failes (SoGO)

### ISSUE THREAD

**Issue by Seji64** [mailcow/mailcow-dockerized#1283]
Hi,

its more a question than a real issue but i cannot upload attachments which are larger than ~ 1MB.

I already added `WOMaxUploadSize = 102400;` to `data/conf/sogo/sogo.conf` und restarted the SoGO Container.

Is anyone also have this Problem? Or did i missed something?

Thanks in advance!

**Comment by mritzmann** [comment]
Are you using a reverse proxy?

**Comment by Seji64** [comment]
Yes, i'am using [https://github.com/jwilder/nginx-proxy](url)

**Comment by mritzmann** [comment]
https://github.com/jwilder/nginx-proxy/issues/376

**Comment by Seji64** [comment]
Looks like that what i need. I will have a look at that this evening. Thanks for your help.

**Comment by Seji64** [comment]
@mritzmann  I just tried what you mentioned - it worked :-)

Thx again.
