### ISSUE TITLE
Update Script Broken

### ISSUE THREAD

**Issue by bully1980** [mailcow/mailcow-dockerized#1285]
Hi,

I just used the Update-Script and now my mailserver is gone. No mailboxes, nothing...

Errormsg from update.sh

Fetching new images, if any...
WARNING: --parallel option is deprecated and will be removed in future versions.
Pulling unbound-mailcow   ... done
Pulling mysql-mailcow     ... done
Pulling redis-mailcow     ... done
Pulling clamd-mailcow     ... done
Pulling php-fpm-mailcow   ... done
Pulling sogo-mailcow      ... done
Pulling dovecot-mailcow   ... error
Pulling postfix-mailcow   ... done
Pulling memcached-mailcow ... done
Pulling nginx-mailcow     ... done
Pulling rspamd-mailcow    ... done
Pulling acme-mailcow      ... done
Pulling fail2ban-mailcow  ... done
Pulling watchdog-mailcow  ... done
Pulling dockerapi-mailcow ... done
Pulling ipv6nat           ... done

ERROR: for dovecot-mailcow  manifest for mailcow/dovecot:1.17 not found
ERROR: manifest for mailcow/dovecot:1.17 not found**

I tried to restore from backup, but this gives me also errors:

[root@mail mailcow-dockerized]# ./helper-scripts/backup_and_restore.sh restore all
Backup location (absolute path, starting with /): /tmp
Using /tmp as backup/restore location.

[ 1 ] - /tmp/mailcow-2018-04-18-18-06-32/

Select a restore point: 1

[ 1 ] - Mail directory (/var/vmail)
[ 2 ] - Postfix data
[ 3 ] - Rspamd data
[ 4 ] - Redis DB
[ 5 ] - SQL DB

Select a dataset to restore: 1
Restoring vmail from /tmp/mailcow-2018-04-18-18-06-32/...
9f5ec4d01f34
ca38a21d8012
docker: invalid reference format.
See 'docker run --help'.
ca38a21d8012

In most cases it is not required to run a full resync, you can run the command printed below at any time after testing wether the restore process broke a mailbox:

docker exec ca38a21d8012 doveadm force-resync -A '*'

Force a resync now? [y|N] y
9f5ec4d01f34

Under /var/lib/docker/volumes are now all volumes duplicated

[root@mail mailcow-2018-04-18-18-06-32]# ls -al /var/lib/docker/volumes/
insgesamt 96
drwx------ 16 root root  4096 18. Apr 18:10 .
drwx--x--x 14 root root  4096 18. Apr 18:24 ..
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_crypt-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_crypt-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_dkim-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_dkim-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_mysql-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_mysql-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_postfix-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_postfix-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_redis-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_redis-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_rspamd-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_rspamd-vol-1
drwxr-xr-x  3 root root  4096 15. Jan 22:49 mailcowdockerized_vmail-vol-1
drwxr-xr-x  3 root root  4096 18. Apr 18:10 mailcow-dockerized_vmail-vol-1
-rw-------  1 root root 65536 18. Apr 18:24 metadata.db

How can I get my server back to work?

**Comment by andryyy** [comment]
Run ...
```
docker-compose down
sed -i 's#COMPOSEPROJECT_NAME#COMPOSE_PROJECT_NAME#g' mailcow.conf
sed -i '/COMPOSE_PROJECT_NAME=/s/-//g' mailcow.conf
docker-compose up -d
```
You also have a file "mailcow.confe", right?

**Comment by bully1980** [comment]
jo, I got a working mailcow.conf 
I used ur sed lines and now everything seems to work. 
How can I clean the unused Volumes under /var/lib/docker/volumes

Should I be worried about the update error?

ERROR: for dovecot-mailcow manifest for mailcow/dovecot:1.17 not found
ERROR: manifest for mailcow/dovecot:1.17 not found**

**Comment by MAGICCC** [comment]
You can e.g. use `docker volume rm $(docker volume ls -qf dangling=true)` to delete such volumes

**Comment by bully1980** [comment]
I deleted the wrong volumes the way @MAGICCC said.
The backup scripts is working again.

I think my problem way caused because the update script was not updating every file. The docker-compose.yml was not updated. 

Is there a safe way to get all files fresh from git? I am not very familiar with git and I don't want to break anything.

**Comment by PhoenixPeca** [comment]
>Is there a safe way to get all files fresh from git? I am not very familiar with git and I don't want to break anything.


you can just backup "mailcow.conf",
delete the mailcow-dockerized folder and
`git clone https://github.com/mailcow/mailcow-dockerized`, then
put the old "mailcow.conf" file back into the new maillcow-dockerized folder.

Anyway, this is off topic, so i'm closing this now.
