### ISSUE TITLE
MX not found

### ISSUE THREAD

**Issue by cekpek** [mailcow/mailcow-dockerized#1287]
Just installed this awesome cow, but get some error when trying to send email.

> BBF311821BD: to=<haha@yahoo.com>, relay=none, delay=1.7, delays=0.67/0/1/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=yahoo.com type=MX: Host not found, try again)

The host it self is able to ping to yahoo.com 

> root@email:/opt/mailcow-dockerized# ping yahoo.com
PING yahoo.com (98.138.219.232) 56(84) bytes of data.
64 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=1 ttl=46 time=260 ms
64 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=2 ttl=46 time=249 ms
64 bytes from media-router-fp2.prod1.media.vip.ne1.yahoo.com (98.138.219.232): icmp_seq=3 ttl=46 time=249 ms

And tried to pin through docker and it does reply

> root@email:/opt/mailcow-dockerized# docker run -it --rm busybox ping yahoo.com
PING yahoo.com (98.138.219.232): 56 data bytes
64 bytes from 98.138.219.232: seq=0 ttl=45 time=250.452 ms
64 bytes from 98.138.219.232: seq=1 ttl=45 time=249.631 ms
64 bytes from 98.138.219.232: seq=2 ttl=45 time=249.434 ms
64 bytes from 98.138.219.232: seq=3 ttl=45 time=249.259 ms

Try to DIG yahoo.com

> root@email:/opt/mailcow-dockerized# dig mx yahoo.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> mx yahoo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28828
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;yahoo.com.                     IN      MX

;; ANSWER SECTION:
yahoo.com.              695     IN      MX      1 mta7.am0.yahoodns.net.
yahoo.com.              695     IN      MX      1 mta6.am0.yahoodns.net.
yahoo.com.              695     IN      MX      1 mta5.am0.yahoodns.net.

;; Query time: 9 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Apr 19 11:08:07 WIB 2018
;; MSG SIZE  rcvd: 117

Try to dig through docker

> root@email:/opt/mailcow-dockerized# dig mx yahoo.com @172.22.1.254

; <<>> DiG 9.10.3-P4-Ubuntu <<>> mx yahoo.com @172.22.1.254
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 31399
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;yahoo.com.                     IN      MX

;; Query time: 535 msec
;; SERVER: 172.22.1.254#53(172.22.1.254)
;; WHEN: Thu Apr 19 11:09:06 WIB 2018
;; MSG SIZE  rcvd: 38

It seems it does not able to dig (short reply)

Anyone know what is the problem?

**Comment by mritzmann** [comment]
Potentially helpful: https://github.com/mailcow/mailcow-dockerized/issues/850

**Comment by cekpek** [comment]
it does not resolve my problem, still having the same problem although all DNS tests through docker are success. 

EDIT:
Forget to mention that i am not using AWS, i am using a dedicated server built ON ubuntu 16.04.4 LTS.

**Comment by PhoenixPeca** [comment]
are you still experiencing the issue? Perhaps it is an issue with your network or ISP.
