### ISSUE TITLE
SOGo Nightly

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#1289]
Is it possible to use SOGo stable and rspamd stable for Mailcow instead of the nightlies? Or make it an option?

I know in the past it was required for some advanced features, is that still required?

We rebuild all docker images every week to prevent outdated dependencies, but sometimes Mailcow breaks due to its reliance on bleeding edge.

**Comment by andryyy** [comment]
Where does it break? You are doing something wrong then. I also don’t see why you need to update weekly to fix dependencies and at the same time complain about bleeding edge? We are not even close to this level of bleeding edge. :-)

You can buy a subscription for SOGo and use their stable repository. Just change the Dockerfiles for what you need your changes applied to.

Rspamd changed their release model. Besides that, I always made sure to use the latest features to prevent spam with Rspamd.
