### ISSUE TITLE
Reset admin password in docker?

### ISSUE THREAD

**Issue by Q-efx** [mailcow/mailcow-dockerized#129]
I sadly forgot the admin password in the docker version. 

I know there is script to reset it. But where is it in the docker version?

**Comment by sfnke** [comment]
https://andryyy.github.io/mailcow-dockerized/u_and_e/#reset-admin-password

**Comment by Q-efx** [comment]
Hmm that looks quit different than what is done in the "normal" version in the mc-reset script.

I did it on my own. What is the exact difference?

**Comment by andryyy** [comment]
It just works different, but does the same job. :-)

**Comment by OKNoah** [comment]
@Q-efx 404

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/
