### ISSUE TITLE
Update policy new docker containers

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1290]
Is there a fixed moment (say once a month for example) when new docker containers are pushed from dev branch to the master branch?

**Comment by MAGICCC** [comment]
Sadly, there isn't a proper 'release cycle'

**Comment by mkuron** [comment]
No. Also, duplicate of #971.

**Comment by xetorixik** [comment]
Cristal clear. 
Couldn't find #971 as in didn't searched on "release model"
Perhaps it is an idea to include it in the documentation. To prevent "same" follow-up questions.
Thanks everyone for the replies.

**Comment by andryyy** [comment]
We should add it. :-) You can push that to the docs, if you like to.

**Comment by xetorixik** [comment]
@andryyy Consider it done.
