### ISSUE TITLE
Feature request Paypall

### ISSUE THREAD

**Issue by Lucky88888** [mailcow/mailcow-dockerized#1291]
@andryyy : Triggered today by the donation request of Wikipedia. Please consider adding the donation per month to your site. So we can donate a steady financial contribution to your great work. 
Just an idea. ;)

**Comment by Fvbor** [comment]
Take a look into the documentation ;)
There is a Paypal link and on the Paypal page is the option for a monthly support. "Dies soll eine Monatliche Spende sein"
(Sorry, for German Paypal Interface)

![image](https://user-images.githubusercontent.com/18524580/39186893-1f0f7112-47cc-11e8-8b9c-bbcc79d3e684.png)
![image](https://user-images.githubusercontent.com/18524580/39186958-3ad60712-47cc-11e8-939f-02c2367a98af.png)
