### ISSUE TITLE
Mails are not getting signed

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#1293]
Because my document management system has a lesser TLS support.
I send my mails through the 588 port already in master.cf
Now SOGo is also sending mails through that port (i think) and those get signed with the DKIM keys etc.
But the mails I send with my document management system through there, don't get a DKIM key.

What could this be?

**Comment by normanu** [comment]
To add to this ticket,

correctly signed outgoing emails get the following flags in rspamd,

TO_DN_NONE(0)
DKIM_SIGNED(0)
ARC_SIGNED(0)[i=1]
FROM_EQ_ENVFROM(0)
MIME_GOOD(-0.1)[multipart/alternative,text/plain]
MID_RHS_NOT_FQDN(0.5)
RCVD_COUNT_ZERO(0)[0]
DYN_RL_CHECK(0)
FROM_HAS_DN(0)
RCVD_TLS_ALL(0)
RCPT_COUNT_ONE(0)[1]
MAILCOW_AUTH(-20)
TO_MATCH_ENVRCPT_ALL(0)
R_PARTS_DIFFER(0.5)[100.0%]
ARC_NA(0)

The email that don't get signed, get only this

DYN_RL_CHECK(0)
KEEP_SPAM(0)[192.168.1.6]


The emails that are send by the doc mng sys, there is one user authenticating that can send for all users.

**Comment by mkuron** [comment]
This looks like you added 192.168.1.6, the document management system, to the forwarding hosts list in the admin UI. If there you didn‘t select that these messages should still go through the spam filter, they will not be signed.

**Comment by normanu** [comment]
You sir are correct!
I didn't think of this as SOGo is also local, but thats offcourse on the docker network subnet .....
