### ISSUE TITLE
clamav container not working

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#1296]
The clamav container does not seem to work.
Looking in the container I see no service running on 3310

In the log file the following error is mentioned,

/bootstrap.sh: line 16: /bootstrap.sh: line 15: /tmp/logpipe_freshclam: Permission denied
/tmp/logpipe_clamd: Permission denied

and rspamd also says 

failed to scan: Socket error detected: Connection refused
--

I removed the container and images files and rebuild the complete image with 
 docker-compose up -d --no-recreate --build clamd-mailcow

Still doesn't work after this.

**Comment by normanu** [comment]
entering the container
docker exec -it mailcowdockerized_clamd-mailcow_1 /bin/bash

and running 
clamd --debug  --config-file=clamd.conf

gives no response / empty response

**Comment by normanu** [comment]
running  clamd --debug --config-file=/etc/clamav/clamd.conf by hand in the docker does start clamd and opens port 3310.

The permission denied comes from the following commands,

cat <> /tmp/logpipe_clamd 1>&2 &
cat <> /tmp/logpipe_freshclam 1>&2 &

**Comment by andryyy** [comment]
When the container is up, clamd is (most likely) already running. You cannot enter the container and start clamd without checking if it is already running.

I can reach clamd-mailcow via telnet from rspamd-mailcow:
```
telnet clamd-mailcow 3310
Trying fd4d:6169:6c63:6f77::a...
Connected to clamd-mailcow.
```

It is probably related to a local firewall or something like this.

The cat commands do not matter here.

---

You didn't even provide clamd-mailcow logs, I don't see how we can help you.

**Comment by normanu** [comment]
Hi @andryyy I checked if it was running with both netstat -tln and ps aux.
Nothing was running, could also not telnet.
Now I manually started clamd and it works, dunno why it won't start by itself.

**Comment by andryyy** [comment]
What does it log?

**Comment by normanu** [comment]
Only thing mentioned in the log is,

/bootstrap.sh: line 16: /bootstrap.sh: line 15: /tmp/logpipe_freshclam:
Permission denied
/tmp/logpipe_clamd: Permission denied


2018-04-20 15:56 GMT+02:00 André Peters <notifications@github.com>:

**Comment by andryyy** [comment]
Strange. Can you grant me access to that machine?

**Comment by normanu** [comment]
I can, but please note it currently is a live environment.

2018-04-20 15:59 GMT+02:00 André Peters <notifications@github.com>:

**Comment by andryyy** [comment]
I’ll be back in a few hours. Can you mail me to info@servercow.de ?
