### ISSUE TITLE
Delete Mail permanently

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1297]
Hi

since a few days (i can't say since a uupdate or since new configuration of outlook) I can't delete a mail permanently (ctrl + del). The Mail is moved to trash. 

Givs a settings for this in Mailcow?

Mail in Outlook was configuratet in the systemconfiguration --> Mail. I think with autodisover. Bevore this, I have create the accounts with manual IMAP settings.

Koda

**Comment by ghost** [comment]
Now I have make a test: When I configurate the E-Mail as IMAP, it works. When I configurate it as Exchange (autodiscover) I can not permanent delete it. It goes into trash

**Comment by mkuron** [comment]
I believe that is a limitation of the ActiveSync protocol. It always deletes to the trash.

**Comment by ghost** [comment]
ok thank you. So you think this is a problem where I can solved?

**Comment by ghost** [comment]
In a normal MS exchange server it works.

**Comment by PhoenixPeca** [comment]
This is an expected action of the ActiveSync protocol. Whenever you delete something, the protocol moves it to the trash first to prevent accidental permanent deletion and to make recovery possible. As for the settings to disable it, I don't also think there is, but maybe it's something that you can ask the SOGo team..

I think it is more appropriate for you to be concerned about automatically deleting emails in the Trash after being stored in that folder for a specific number of days (or perhaps this was already implemented, I can't really tell). Any thoughts @mkuron?

**Comment by mkuron** [comment]
@kodacch, if it works on an Exchange Server, maybe you should file a bug with the SOGo project. Does it work with any Exchange version or just the latest one?

**Comment by ghost** [comment]
I can only test it with exchange 2013

**Comment by PhoenixPeca** [comment]
@KodaCCH as we have pointed out, this problem isn't really because of mailcow, but with the ActiveSync protocol of SOGo itself. I don't really think there's much we can do to help. We recommend that you open this issue into the SOGo developers instead. Good luck! :-)
