### ISSUE TITLE
rspamd: JSON.parse: unterminated

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1298]
Since the last update I get this error in rspamd history:
Cannot receive data from MyMailserver: SyntaxError: JSON.parse: unterminated string at line 1 column 427807 of the JSON data

have you an idea? In firefox console Log i don't see an error

**Comment by mritzmann** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/1116

**Comment by andryyy** [comment]
Duplicate.

**Comment by ghost** [comment]
Oh sorry. Thank you :)
