### ISSUE TITLE
Bug: When using alias goto-adresses with tag (e.g. test+news@example.com) tag filters do not apply

### ISSUE THREAD

**Issue by BjarneRest** [mailcow/mailcow-dockerized#1299]
Heyho,

I would like to point a catch-all alias to user+CatchAll@domain.com because I'd like to have them in my CatchAll folder.
However, the tagging filters don't apply to emails routed through an alias adress.

Thank you so far,
Bjarne Rest

**Comment by mkuron** [comment]
Duplicate of #408
