### ISSUE TITLE
Roundcube integration

### ISSUE THREAD

**Issue by emcniece** [mailcow/mailcow-dockerized#13]
Any plans for bringing Roundcube into the dockerized stack?

**Comment by andryyy** [comment]
Plans, yes. :) But I don't have an ETA.

**Comment by emcniece** [comment]
On the other hand, there are many Dockerized Roundcube images available already - adding one of these manually is not hard, and is maybe a better user-driven approach.

**Comment by tehXor** [comment]
Just out of curiosity as I haven't worked with either a lot yet, where do you see the advantages in Roundcube over SOGo or vice versa?

**Comment by emcniece** [comment]
@tehXor I didn't even realize that SOGo was a webmail client until reading your comment. SOGo is way nicer!

**Comment by andryyy** [comment]
The devs are really nice, too! Helping you out even without a commercial subscription. Nevertheless, if you can, support them! :)

**Comment by psi-4ward** [comment]
We should close this issue. 
I use rainloop atm and its easy to integrate, just start the container ... 

Probably we should take some notes in the docs how to start reinloop, roundcube whatever.

**Comment by oviliz** [comment]
Any chance to see this in the docs?

**Comment by kwisatz** [comment]
> Just out of curiosity as I haven't worked with either a lot yet, where do you see the advantages in Roundcube over SOGo or vice versa?

Sieve support. That's a big issue with SoGo. Their sieve support is a joke!

**Comment by andryyy** [comment]
I actually like their sieve support. Hm. :(

**Comment by kwisatz** [comment]
> I actually like their sieve support. Hm. :(

Maybe I'm missing something… I don't even have date-based filters available within Sogo. In comparison with roundcube's managesieve, what I see is very basic. Again, maybe I'm not looking at the right thing?

Here's what I can do with the date field in roundcube's managesieve:

![image](https://user-images.githubusercontent.com/237949/104710287-3124d700-5720-11eb-86df-dfe82cca02a2.png)

**Comment by kwisatz** [comment]
@andryyy Do you have any feedback for me on whether I'm looking at the wrong thing in `SOGo` or might have forgotten to configure/activate something rather than it actually missing a good deal of the sieve functionality that `managesieve` offers?
