### ISSUE TITLE
Subfolders of INBOX do not show up

### ISSUE THREAD

**Issue by wucke13** [mailcow/mailcow-dockerized#130]
As stated in the title, subfolder of the inbox folder are invisible both in SOGo and Email client, however they exist (in the docker volume vmail). This seems to be common issue with dovecot, however the folders did show up on my old mailcow + roundcube 0.14 Instance. Any suggestions how to make these subfolders visible? Normal folders are visible both in SOGo and any mailclient.

Cheers, wucke13

**Comment by broedli** [comment]
Please check your sogo logs: `docker-compose logs sogo-mailcow`

**Comment by wucke13** [comment]
I am sorry, I just was to dumb to use SOGo. At some point I found out, that you have to click on the folder icon to the left of the name of a folder. So after toggling that, my subfolders showed up. Can be closed.
