### ISSUE TITLE
Replace local MTA

### ISSUE THREAD

**Issue by pennybuster** [mailcow/mailcow-dockerized#1300]
Hi there! Can I replace Postfix with Msmtp as local MTA? (Not the dockerized Postfix)
Thanks a lot

**Comment by mkuron** [comment]
Why is this a Mailcow question? The dockerized Postfix cannot be replaced (no other MTA has all the needed features), but that‘s not what you wanted to do anyway. If it is not a Mailcow question, Google will almost certainly help and suggest pages like https://superuser.com/questions/1289550/msmtp-vs-msmtp-mta-package-which-one-to-choose to you, which are better places for posting such questions anyway.

**Comment by pennybuster** [comment]
Sorry. I thought there was a possibility that the local Postfix on Docker host (not the dockerized one) could be replaced. I'm a total newbie.
Thanks anyway!

**Comment by hachre** [comment]
@pennybuster You can generally do whatever you want on the host, as long as you don't interfere with the operation of Docker, which runs the Mailcow containers. The major source of problems comes from installing / running firewalls or any programs that interfere with the network setup or attempting to run services on the host which require network ports open that are already in use by Mailcow.

**Comment by pennybuster** [comment]
Thank you for the information. It helped me understand this solution better, which I've read it's amazing.
