### ISSUE TITLE
Question about Mailman

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1303]
I saw in the dev branch some commits concerning the integration of mailman. Do you consider to merge this to the master branch in the future or do i need to switch to the dev branch to use it?

**Comment by MAGICCC** [comment]
For not you would need to use the dev branch to use mailman yes. But since there is no real 'release cycle/merge into master/dev is only for developing/master is stable' thing, it may lack features or is not stable.
Be sure to make backups before invoking `git checkout dev`

**Comment by phipag** [comment]
Okay, thank you. Do i only need to run git checkout dev ?

**Comment by MAGICCC** [comment]
Just be sure you should run the update script then
