### ISSUE TITLE
Moving rspamd 'admin password change form'

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#1304]
I did a [PR ](https://github.com/mailcow/mailcow-dockerized/pull/1302) regarding moving the 'Rspamd admin password change form', but it seems it wasn't a success.
My intention was that changing a password is an adminstrative task and not a debugging one and since the Mailman counterpart can be found in admin.php it would make more sense to move the Rspamd one next to Mailman. Furthermore splitting the Rspamd settings map and the form, so the map will stay in debug.php may the best way for everyone...

![c02](https://user-images.githubusercontent.com/3279213/39083007-f15066e4-455c-11e8-9cf0-b30f023cd21d.png)
![fcb](https://user-images.githubusercontent.com/3279213/39083009-f299718a-455c-11e8-8deb-1d5a13ddab3b.png)

**Comment by mkuron** [comment]
Actually, the entire rspamd web interface is a debug feature. You can't really make persistent settings changes there. Its main purpose is looking at the log and statistics and testing whether a certain message would be recognized as spam.

**Comment by MAGICCC** [comment]
I dont talk about the interface itsself, I talk about the location where you can edit a password, which is currently in the debug view and not in admin.php which should be the right location of such things.
I doubt you edit a password of e.g. a forum in one of the logs sites and not in some sort of an admin control panel.
