### ISSUE TITLE
Always the same problem with adding new domain

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#1305]
Hi there,

I have always the same problem when I try to add a domain to my mailcow-dockerized server.

I add it into to config file and then I run `docker-compose up -d`  as your [documentation](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#additional-domain-names) says.

Unfortunately, I will always end on the same Error: 
`acme-client: ea18yqRCFQcKKLvRBe3gzRrVJf5MRhvLbfcO44I20so: File exists
acme-mailcow_1       | acme-client: bad exit: netproc(691): 1
acme-mailcow_1       | acme-client: bad exit: challengeproc(694): 1
acme-mailcow_1       | Sun Apr 22 06:52:38 UTC 2018 - Error requesting certificate, restoring from previous acme request and restarting containers...
`
Complete log: https://hastebin.com/uvogiqeqay.scala

Image version:
![image](https://user-images.githubusercontent.com/9658012/39092297-016de02a-460b-11e8-99fc-cad77893ce48.png)

Last time, it got fixed without my touching in like 24 hours. Now it's more and still nothing...and it's pretty annoying to wait about 2 - 3 days for every domain to get fully working.

Thanks for your time and work! Mailcow is an awesome mail software!

**Comment by mkuron** [comment]
At first sight, it seems like #489, #550 and #1126 are related, but they are not; these were due to temporary API errors that were fixed by Let's Encrypt within a few days. Your error is this one:
```
acme-client: ea18yqRCFQcKKLvRBe3gzRrVJf5MRhvLbfcO44I20so: File exists
```
Unfortunately there is not much information about this error available online. http://openbsd-archive.7691.n7.nabble.com/acme-client-problem-when-requesting-certificate-td331167.html mentions it but has no solution. I also haven't been able to find the place in the code of https://github.com/kristapsdz/acme-client that prints this message. That project hasn't been updated in a year anyway, so we may night to move to a different ACME client if it the issue doesn't fix itself.

**Comment by andryyy** [comment]
It doesn't look like this file was ever created in that specific acme session. Can you please show us the output of `ls ./data/web/.well-known/acme-challenge`?

@mkuron I think this happens here: https://github.com/kristapsdz/acme-client-portable/blob/master/chngproc.c#L166 (or 163). But the file "ea18yqRCFQcKKLvRBe3gzRrVJf5MRhvLbfcO44I20so" was not created according to his logs. So it either exists or that check fails.

**Comment by DJIronic** [comment]
Hi guys, thank you for your answers!

Here it is: https://photos.app.goo.gl/Jxl1u6rjchqpv9lP2

Folder is probably empty, sorry for sharing it like that, but I can't find a way how to post image directly from android.

**Comment by andryyy** [comment]
We could remove `O_EXCL` from open() for the fun of it... worst to happen is an invalid challenge. I am just curious.

**Comment by DJIronic** [comment]
Well..that's probably up to you..as I dont't understand that much to get what is wrong and what should do with it :D I just reported the problem I have and I don't know what to do with it :)

So good luck guys, I am sure you will figure it out.

**Comment by DJIronic** [comment]
OK, it's working now - new domain has its own cert.

I just wait another 12 hours...but still..this is pretty annoying. :/

**Comment by andryyy** [comment]
Can you post the whole log output? From the last paste until now.

**Comment by DJIronic** [comment]
Sorry for asking...but how can I get it from the system? :)

**Comment by andryyy** [comment]
No problem, `docker-compose logs acme-mailcow > acme.log` should do it.

**Comment by DJIronic** [comment]
Here it is: https://paste.ubuntu.com/p/nH3zQvdzGG/

Pretty long tho.

**Comment by andryyy** [comment]
Thanks. It looks strange. It always takes two attempts to create that file. What's your hosts OS and filesystem?

**Comment by DJIronic** [comment]
Debian 8 64-bit, virtualized in VMWare ESXi.

Filesystem is Debian's native.

**Comment by andryyy** [comment]
And `docker ps -a`? :-)

**Comment by DJIronic** [comment]
Sorry for the delay. :/

![image](https://user-images.githubusercontent.com/9658012/39097667-a6d051de-465f-11e8-9061-d6470fc68753.png)

**Comment by mitchellurgero** [comment]
Why not add domain through the admin panel?


EDIT: Looks like you just need to wait for DNS to finish propagating. And your comment:

> Last time, it got fixed without my touching in like 24 hours. 

Kinda suggests that as well. Remember DNS takes at max 48 hours to update completely when adding a new record (usually much faster but some places might take this long).

EDIT 2:
I see a bunch of `No A record for autoconfig.burningcube.eu found` for all sorts of domains you have meaning DNS record hasn't been made or propagation hasn't completed. Just FYI.
