### ISSUE TITLE
Apple-Mail / Anonymize Headers

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1306]
As shown in the Mailcow documentation, it is possible to [hide specific headers](https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-anonym_headers/).

The problem is that if you are using Apple mail. The content type is listed as mail header source:

```
Content-Type: multipart/alternative;
	boundary=Apple-Mail-FE75BFEA
```

Which can reveal what mail program you are using. 
In this specific case Apple Mail.

I looked at the Postfix parameters to hide the specific data. 
It seems that no parameter is available to hide this kind of specific information.
Does anyone have a solution?

Thanks.

**Comment by mkuron** [comment]
You might need to write a milter to do that. Or maybe this works: https://serverfault.com/questions/647154/postfixheader-checks-custom-multi-line-text-replace-in-the-mail-header#647491

 It's not worth the effort though as you can usually also guess the mail program from the HTML it generates for a richt-text message - and there is no reasonable way to obscure that.

**Comment by xetorixik** [comment]
Thanks @mkuron working fine.
Highly appreciated!

If someone ever wants to have the extact bits.
Let me know.
