### ISSUE TITLE
docker-compose pull fails on fresh installation

### ISSUE THREAD

**Issue by OCram85** [mailcow/mailcow-dockerized#131]
Hi,
`mailcow-dockerized` installation fails at `docker-compose pull` on a fresh Ubuntu 16.04 LTS host:
```
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

Tried to install mailcow with the given [instructions](https://andryyy.github.io/mailcow-dockerized/install/#update-mailcow)

**Comment by tehXor** [comment]
Is your docker-compose up to date? You can check it with `docker-compose version`. Version 1.11.1 or later should work in any case.

**Comment by OCram85** [comment]
Well, this was my fault ^^ - Used the docker and docker-compose version form the repo...
