### ISSUE TITLE
Roundcube on mailcow error: rcube_db.php: Table 'mailcow.session' doesn't exist

### ISSUE THREAD

**Issue by chriswayg** [mailcow/mailcow-dockerized#1311]
I installed Roundcube 1.3.6 on a working, fresh install of mailcow according to these instructions:
https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

The installer and testmails were successful, but when I tried to use Roundcube at https://mail.example.org/rc/  I get the following error:

`rcube_db.php (543): [1146] Table 'mailcow.session' doesn't exist`

---

I was able to get it working eventually, after slightly changing the installation steps from the above instructions. 

Instead of saving 'config.inc.php' before running the rc/installer, I completed the installer steps 1 and 2 and after that copied the  'config.inc.php'  (as configured in the mailcow-dockerized-docs instructions).

In step 3 the installer asked me to initialize the database, which did not happen in the first attempt. The tests completed, and I was able to login successfully. 

Debian 9, PHP 7

**Comment by andryyy** [comment]
Thanks, I will check that.

But are you sure you didn't just miss to press the button to init the database?
