### ISSUE TITLE
Update Failure - After Update -> Factory Settings

### ISSUE THREAD

**Issue by Fvbor** [mailcow/mailcow-dockerized#1315]
Detected today, that there is a bug in the Update of Mailcow.
Two friends and me have our own mailcow-dockerized installed on CentOS.
After an Update today every data was lost. 
It seems, that the updater delete the mysql db.
Known bug?
Is there a Workaround?

> [root@dockertest mailcow-dockerized]# ./update.sh
> Checking internet connection... OK
> Checking for newer update script...
> remote: Counting objects: 18, done.
> remote: Total 18 (delta 11), reused 11 (delta 11), pack-reused 7
> Unpacking objects: 100% (18/18), done.
> From https://github.com/mailcow/mailcow-dockerized
>  * branch            master     -> FETCH_HEAD
> Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
> Stopping mailcow...
> Stopping mailcowdockerized_acme-mailcow_1      ... done
> Stopping mailcowdockerized_rspamd-mailcow_1    ... done
> Stopping mailcowdockerized_nginx-mailcow_1     ... done
> Stopping mailcowdockerized_netfilter-mailcow_1 ... done
> Stopping mailcowdockerized_php-fpm-mailcow_1   ... done
> Stopping mailcowdockerized_clamd-mailcow_1     ... done
> Stopping mailcowdockerized_ipv6nat_1           ... done
> Stopping mailcowdockerized_sogo-mailcow_1      ... done
> Stopping mailcowdockerized_memcached-mailcow_1 ... done
> Stopping mailcowdockerized_dovecot-mailcow_1   ... done
> Stopping mailcowdockerized_dockerapi-mailcow_1 ... done
> Stopping mailcowdockerized_watchdog-mailcow_1  ... done
> Stopping mailcowdockerized_postfix-mailcow_1   ... done
> Stopping mailcowdockerized_unbound-mailcow_1   ... done
> Stopping mailcowdockerized_redis-mailcow_1     ... done
> Stopping mailcowdockerized_mysql-mailcow_1     ... done
> Removing mailcowdockerized_acme-mailcow_1      ... done
> Removing mailcowdockerized_rspamd-mailcow_1    ... done
> Removing mailcowdockerized_nginx-mailcow_1     ... done
> Removing mailcowdockerized_netfilter-mailcow_1 ... done
> Removing mailcowdockerized_php-fpm-mailcow_1   ... done
> Removing mailcowdockerized_clamd-mailcow_1     ... done
> Removing mailcowdockerized_ipv6nat_1           ... done
> Removing mailcowdockerized_sogo-mailcow_1      ... done
> Removing mailcowdockerized_memcached-mailcow_1 ... done
> Removing mailcowdockerized_dovecot-mailcow_1   ... done
> Removing mailcowdockerized_dockerapi-mailcow_1 ... done
> Removing mailcowdockerized_watchdog-mailcow_1  ... done
> Removing mailcowdockerized_postfix-mailcow_1   ... done
> Removing mailcowdockerized_unbound-mailcow_1   ... done
> Removing mailcowdockerized_redis-mailcow_1     ... done
> Removing mailcowdockerized_mysql-mailcow_1     ... done
> Removing network mailcowdockerized_mailcow-network
> Committing current status...
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'root@dockertest.(none)')
> Fetching updated code from remote...
> From https://github.com/mailcow/mailcow-dockerized
>  * branch            master     -> FETCH_HEAD
> Merging local with remote code (recursive, strategy: "theirs", options: "patience"...
> Already up-to-date.
> Fetching new docker-compose version...
> which: no pip in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin)
> ######################################################################## 100.0%
> ######################################################################## 100.0%
> Fetching new images, if any...
> WARNING: --parallel option is deprecated and will be removed in future versions.
> Pulling unbound-mailcow   ... done
> Pulling mysql-mailcow     ... done
> Pulling redis-mailcow     ... done
> Pulling clamd-mailcow     ... done
> Pulling php-fpm-mailcow   ... done
> Pulling sogo-mailcow      ... done
> Pulling dovecot-mailcow   ... done
> Pulling postfix-mailcow   ... done
> Pulling memcached-mailcow ... done
> Pulling nginx-mailcow     ... done
> Pulling rspamd-mailcow    ... done
> Pulling acme-mailcow      ... done
> Pulling netfilter-mailcow ... done
> Pulling watchdog-mailcow  ... done
> Pulling dockerapi-mailcow ... done
> Pulling ipv6nat           ... done
> Fixing project name...
> Starting mailcow...
> Creating network "mailcow-dockerized_mailcow-network" with driver "bridge"
> Creating volume "mailcow-dockerized_vmail-vol-1" with default driver
> Creating volume "mailcow-dockerized_mysql-vol-1" with default driver
> Creating volume "mailcow-dockerized_redis-vol-1" with default driver
> Creating volume "mailcow-dockerized_rspamd-vol-1" with default driver
> Creating volume "mailcow-dockerized_postfix-vol-1" with default driver
> Creating volume "mailcow-dockerized_crypt-vol-1" with default driver
> Creating volume "mailcow-dockerized_rspamd-sock" with default driver
> Creating mailcow-dockerized_clamd-mailcow_1     ... done
> Creating mailcow-dockerized_sogo-mailcow_1      ... done
> Creating mailcow-dockerized_dovecot-mailcow_1   ... done
> Creating mailcow-dockerized_mysql-mailcow_1     ... done
> Creating mailcow-dockerized_memcached-mailcow_1 ... done
> Creating mailcow-dockerized_dockerapi-mailcow_1 ... done
> Creating mailcow-dockerized_redis-mailcow_1     ... done
> Creating mailcow-dockerized_watchdog-mailcow_1  ... done
> Creating mailcow-dockerized_postfix-mailcow_1   ... done
> Creating mailcow-dockerized_unbound-mailcow_1   ... done
> Creating mailcow-dockerized_ipv6nat_1           ... done
> Creating mailcow-dockerized_php-fpm-mailcow_1   ... done
> Creating mailcow-dockerized_nginx-mailcow_1     ... done
> Creating mailcow-dockerized_netfilter-mailcow_1 ... done
> Creating mailcow-dockerized_acme-mailcow_1      ... done
> Creating mailcow-dockerized_rspamd-mailcow_1    ... done
> Collecting garbage...
> Further cleanup...
> If you want to cleanup further garbage collected by Docker, please make sure all containers are up and running before cleaning your system by executing "docker system prune"
>

**Comment by andryyy** [comment]
Just run...

```
cd /your/mailcow-dockerized-path
docker-compose down
sed -i 's#COMPOSEPROJECT_NAME#COMPOSE_PROJECT_NAME#g' mailcow.conf
sed -i '/COMPOSE_PROJECT_NAME=/s/-//g' mailcow.conf
docker-compose up -d
```

BUT. It would be very cool to let me have a look at the machine and why the sed commands in the update script fails to rename that parameter. Let me know @ info@servercow.de :-)

**Comment by Fvbor** [comment]
Ok thanks!
You will get in the next few minutes an e-mail from a friend.
My dev system is, because of testing, on a newer version.

**Comment by Braintelligence** [comment]
It seems I had the same problems. Gonna try this solution now after restoring the backup.

**Comment by Braintelligence** [comment]
@andryyy My problem with this was rather simple: My mailcow.conf just doesn't contain a COMPOSE_PROJECT_NAME variable at all. Not after the update.sh and also not after your sed command which only applies to an already existing COMPOSEPROJECT_NAME entry I believe.

**Comment by andryyy** [comment]
Strange, it was never added? File permission issues? Updating with a user that cannot write to mailcow.conf?

**Comment by Braintelligence** [comment]
It could be that I updated once or twice without sudo by accident, yeah, but not this time.

**Comment by andryyy** [comment]
That’s bad anyways. Some files may never have been updated.

**Comment by Braintelligence** [comment]
Are there any suitable commands that I could run to verify this? 😸

**Comment by andryyy** [comment]
Mail me and we check it this evening, if you want to. :-)

**Comment by Braintelligence** [comment]
This evening I'm busy as hell, maybe tomorrow? 😸

**Comment by andryyy** [comment]
Just mail me :-)

**Comment by Braintelligence** [comment]
I ran the update script on another server with sudo. It said "Fixing project name" in one line but again the mailcow.conf didn't contain the new variable at all.

**Comment by andryyy** [comment]
You run the script before (!) without sufficient rights. 

It does not add that variable name now.
