### ISSUE TITLE
How to disable clamAV?

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#1317]
Hello,

I am running out of memory on my vServer (2GB RAM).

How can i disable clamAV without loosing anything (also my manual modifications)?

Thanks in advance.

**Comment by hachre** [comment]
Edit `mailcow.conf` and set
```
SKIP_CLAMD=y
```

Afterwards it should be enough to run
```
docker-compose up -d
```

**Comment by mritzmann** [comment]
duplicate https://github.com/mailcow/mailcow-dockerized/issues/672

**Comment by ruffy91** [comment]
Is it normal that a mailcowdockerized_clamd-mailcow_1 is still created even when SKIP_CLAMD=y is set?

Changing this setting and running 
`docker-compose up  -d`
only modifies the container but is stil running.

**Comment by MAGICCC** [comment]
Yes, but the container itsself does nothing
