### ISSUE TITLE
max connection rate

### ISSUE THREAD

**Issue by minimins** [mailcow/mailcow-dockerized#1318]
Hi,

In postfix I may have a lot of connections (because i have 10 or so email accounts on the one server to different domains), i seem to be getting rate limited.

Statistics: max connection rate..

How do you increase the connection rate?

Thanks,
Marcus

**Comment by andryyy** [comment]
That's not really a problem. It is a ratelimit of Postfix, anvil reports the stats. What's the exact log line?

**Comment by mritzmann** [comment]
Maybe you mean dovecot? (IMAP)

If so, it would look like this in the log:

```
mail dovecot: master: Warning: service(imap-login): process_limit (100) reached, client connections are being dropped
```

This way you can increase the limit of dovecot:

```
diff --git a/data/conf/dovecot/dovecot.conf b/data/conf/dovecot/dovecot.conf
index 533433a..759a86c 100644
--- a/data/conf/dovecot/dovecot.conf
+++ b/data/conf/dovecot/dovecot.conf
@@ -213,7 +213,8 @@ service managesieve-login {
 }
 service imap-login {
   service_count = 1
   vsz_limit = 64M
+  process_limit = 500
   user = dovenull
 }
 service pop3-login {
```
