### ISSUE TITLE
docker-compose flag "--parallel" is deprecated

### ISSUE THREAD

**Issue by hardoverflow** [mailcow/mailcow-dockerized#1320]
https://github.com/mailcow/mailcow-dockerized/blob/a6810b81c6e2719226243cf38e74a967428d48d6/update.sh#L204

https://docs.docker.com/release-notes/docker-compose/#1210-2018-04-11

https://docs.docker.com/compose/reference/pull/

**Comment by andryyy** [comment]
Thanks, this was already fixed in dev.
