### ISSUE TITLE
Netfilter bans itself when natting another outgoing ip

### ISSUE THREAD

**Issue by Littlericket** [mailcow/mailcow-dockerized#1323]
Hi,

to change the outgoing ip from the mailcow service, instead of using the host's outgoing ip, i've natted the mailcow subnet with
`iptables -t nat -I POSTROUTING -s 172.22.1.0/24 -j SNAT --to 136.243.102.XXX`

This works as far as I can see, the containers talk with another outgoing IP adress (curl/wget www.myip.ch). Issue is now, that the netfilter logs show that he ban's himself:

![image](https://user-images.githubusercontent.com/1573629/39296196-8ec9f480-4940-11e8-8b0d-f735fe00ad21.png)

Is there any chance to actually disable this behaviour for one IP / Subnet only except for disabling the netfilter completely?

```
      image: mailcow/unbound:1.1
      image: mariadb:10.2
      image: redis:alpine
      image: mailcow/clamd:1.9
      image: mailcow/rspamd:1.17
      image: mailcow/phpfpm:1.12
      image: mailcow/sogo:1.20
      image: mailcow/dovecot:1.24
      image: mailcow/postfix:1.14
      image: memcached:alpine
      image: nginx:mainline-alpine
      image: mailcow/acme:1.28
      image: mailcow/netfilter:1.12
      image: mailcow/watchdog:1.14
      image: mailcow/dockerapi:1.11
      image: robbertkl/ipv6nat
```

**Comment by Littlericket** [comment]
I havent seen the new option "SNAT_TO_SOURCE". My bad.

**Comment by andryyy** [comment]
:-) This is not an issue with this option anymore?

**Comment by Littlericket** [comment]
No. Works so far.
I've natted the outgoing IP with iptables to extend the docker chain. I haven't checked mailcow.conf, since I needed that before the new option was available.

**Comment by Littlericket** [comment]
I have to reopen the issue. The netfilter is still banning the outgoing ip ...
![image](https://user-images.githubusercontent.com/1573629/39416374-bf1933f8-4c4c-11e8-9bd8-fa49022d21bd.png)

**Comment by Littlericket** [comment]
Hi,

temporary fixed this by adding the SNAT IP to the netfilter whitelist.
Maybe this should be persistent if the SNAT_TO_SOURCE is given?
