### ISSUE TITLE
Question: How to increase Rspamd history max entries?

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#1324]
Hi everyone,

is it possible to increase the Rspamd history max entries? I currently have only 8 pages of history to look through and it looks like the rest is being deleted in a rolling manner.

**Comment by sbpro86** [comment]
The docs says that you have to create a new config file '/etc/rspamd/local.d/history_redis.conf' with this content:
```
servers = 127.0.0.1:6379; # Redis server to store history
key_prefix = "rs_history"; # Default key name
nrows = 2000; # Default rows limit
compress = true; # Use zstd compression when storing data in redis
```
And change the values accordingly.

Source: https://rspamd.com/doc/modules/history_redis.html
