### ISSUE TITLE
dovecot default realm

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#1325]
Hi,

I'm currently configuring a mailcow box to replace an old sendmail install and I have a little question.

On our current sendmail setup our users can authenticate with username without the domain part, it defaults to our main domain.

So a user authenticating without domain in username, for example `mybuddy` will automaticall be transformed to `mybuddy@maindomain.com`.

This is achieved easily in dovecot.conf by adding 
```
auth_default_realm = maindomain.com
```
in `dovecot.conf` (well I added it to `extra.conf`)

It works like a charm, but it breaks imapsync jobs and probably something with sogo and sieve too.

The imapsync jobs seems to use a master dovecot user/pass (using the `*` separator on the username) and that is grabbed from a file `sieve.creds` in `/etc/sogo`.

Problem is that with `auth_default_realm` activated, dovecot will try to auth as `dovecot_master_user@maindomain.com` and this is not what is found in `dovecot-master.passwd`.
Authentification will then fail.

I thought about manually adding `dovecot_master_user@maindomain.com`  in that file but it guess will be overwritten at every dovecot container restart.

Any idea how I could cleanly add this feature so it's compliant with mailcow guidelines ?

I hope you'll understand the issue despite my bad english :)

**Comment by andryyy** [comment]
Hi, 
Hm... I think there is too much that needs to be changed to make this work. A webmailer could be configured to use a default realm, but you probably want this to work over plain IMAP/SMTP?

**Comment by sriccio** [comment]
Yes it's primarily for IMAP/SMTP to avoid a lot people having to reconfigure their mail clients

**Comment by sriccio** [comment]
I found out that the files are generated here: `docker-entrypoint.sh` for dovecot

```
# Create random master for SOGo sieve features
RAND_USER=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 16 | head -n 1)
RAND_PASS=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 24 | head -n 1)
echo ${RAND_USER}:$(doveadm pw -s SHA1 -p ${RAND_PASS}) > /usr/local/etc/dovecot/dovecot-master.passwd
echo ${RAND_USER}:${RAND_PASS} > /etc/sogo/sieve.creds
```

Wouldn't it be possible to add an environnement value somewhere in mailcow.conf or docker-compose.yml to set a default realm, and then if it's set append it to the user name added in the passwd file ?

(also add it dynamically to dovecot config to be consistant)

**Comment by sriccio** [comment]
Of course the best would be to have a magical dovecot option to tell it not to append the default realm in some cases, but can't find anything about this.

**Comment by sriccio** [comment]
I think i have an idea:

appending `@norealm` to username in both files, so dovecot shouldn't append the default realm as it already has one.

**Comment by sriccio** [comment]
Okay it works like a charm and I guess it shouldn't have any impact:

```
Host2: connecting and login on host2 [localhost] port [993] with user [test@maindomain.com*1td48vq6qaq3wtbn@norealm]
```
The sync was successfull.

This would just need to change the `docker-entrypoint.sh` to:

```
# Create random master for SOGo sieve features
RAND_USER=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 16 | head -n 1)
RAND_PASS=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 24 | head -n 1)
echo ${RAND_USER}@norealm:$(doveadm pw -s SHA1 -p ${RAND_PASS}) > /usr/local/etc/dovecot/dovecot-master.passwd
echo ${RAND_USER}@norealm:${RAND_PASS} > /etc/sogo/sieve.creds
```

Could this be added officially to mailcow, so it can supports default realm without breaking imapsync jobs and sogo/sieve that use this master password ?

**Comment by mkuron** [comment]
That sounds reasonable. Maybe not `@norealm` (because that's technically a realm too), so try to come up with a good name and post a pull request.

**Comment by sriccio** [comment]
I have no idea for a good name, any suggestions.

`@system.local`
`@mailcow.local`
`@mailcow`
`@system`
`@local`
`@default`

any choice or other suggestions ? I'll post a pull request when we're ok with the prefix

**Comment by sriccio** [comment]
Added PR https://github.com/mailcow/mailcow-dockerized/pull/1331

**Comment by PhoenixPeca** [comment]
I see that it has been fixed at #1331. Closing this now. ;-)

**Comment by evilaliv3** [comment]
@sriccio is this still working?

**Comment by evilaliv3** [comment]
I just wanted to confirm this is working like a charm! (```auth_default_realm = maindomain.com```)

We are using it on mail.globaleaks.org where some users need such a config.

Thank you if you could ensure compatibility is preserved also in future releases!

\cc @@FreddleSpl0it DerLinkman
