### ISSUE TITLE
Cannot change SOGo logo

### ISSUE THREAD

**Issue by juantheadmin** [mailcow/mailcow-dockerized#1328]
I am trying to change the logo at /data/Dockerfiles/sogo/sogo-full.svg. I am copying the file over and re-running docker-compose build sogo-mailcow but the icon is not changing. 

Any tips or suggestions?

**Comment by andryyy** [comment]
Run docker-compose up -d after building the image.

**Comment by juantheadmin** [comment]
I forgot to mention I ran docker-compose up -d sogo-mailcow, essentially following the instructions on the site. 

I guess my question should be should I make the change in the "/opt/mailcow-dockerized" folder or the original mailcow-dockerizedmaster?

**Comment by hachre** [comment]
Why do you have two folders? You need to make the change in the folder Mailcow is running from. Also I've noticed that the file is usually cached by Browsers and Cloudflare as well if you have it in between, so make sure to empty those caches after making the change!

**Comment by c0by85** [comment]
Got the same problem, used the howto from the mailcow: dockerized documentation.

https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/

**Comment by andryyy** [comment]
Just copy the svg, build the image, recreate the container. It does indeed work.

**Comment by andryyy** [comment]
Try to restart nginx-mailcow, too. Clean your browsers cache. Or even recreate the mailcow stack (down && up -d).

**Comment by develth** [comment]
Have the same issue. 
I changed the Logo (before i run update.sh), it changed from the mailcow one to the new blue sogo logo - but this file wasn´t in data/Dockerfiles/sogo/sogo-full.svg - there was already the one i would like to insert. 

So i called the two commands in the docs - nothing changed again.
It seems like it ignores the sogo-full.svg in the data/Dockerfiles/sogo/ folder.

**Comment by develth** [comment]
By the way - direct call of Logo URL / Clear Cache / New Other Browser - all of them display the default Logo.

**Comment by ashiq54689** [comment]
It worked for me. But a bit differently.
```
docker-compose build sogo-mailcow
docker-compose up -d
```
It doesn't work, if I use docker-compose up -d sogo-mailcow after the build command as per https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/.

**Comment by XUBIUM** [comment]
Hello, 
I was able to change the logo using docker-compose build sogo-mailcow and docker-compose up -d, but an update returned the logo to the default and I can't change it again (even if the modified sogo-full.svg image remainded in the data/Dockerfiles/sogo/ folder after the update).
Is there something else to try?
Thanks

**Comment by MAGICCC** [comment]
You have to rebuild the container again after an update

**Comment by XUBIUM** [comment]
Thanks for your reply. Rebuild the container is't what docker-compose build sogo-mailcow does?

**Comment by MAGICCC** [comment]
Yep exactly

**Comment by XUBIUM** [comment]
I executed both 
docker-compose build sogo-mailcow 
docker-compose up -d
But the image isn't changing, and it is not an issue with browser caches.

Any other tips or suggestions?

Thanks

**Comment by XUBIUM** [comment]
Do you think that I report this as a new issue? (I see this issue is closed)
Thanks.
