### ISSUE TITLE
nginx 413 with roundcube while upload

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1333]
Hi there,

whats the best and easiest point to prevent the 

    413 Request Entity Too Large

while using roundcube and uploading larger files.
Setting e.g. this in site.conf in the _location ~ \.php$_ section wouldn´t solve the issue:

    client_max_body_size 0;

Thanks

**Comment by mitchellurgero** [comment]
Try:
client_max_body_size 100m;
        client_body_timeout 120s;

Just under the http { line.

Please note though that like 90% of servers you interact with only allow a mail item of 25m. This includes message AND attachments together.

**Comment by develth** [comment]
i put it under the server { line - thanks

**Comment by m0nkeykong** [comment]
Hey.
I am using mail-in-a-box which includes Roundcube.
When attempting to import an email mbox file, I encounter this error.

I've attempted on fixing it using what you've suggested here - but with not luck.

Any advise?
