### ISSUE TITLE
mailcowdockerized_netfilter-mailcow_1 - restarting

### ISSUE THREAD

**Issue by Shadesh** [mailcow/mailcow-dockerized#1335]
This container is restarting permanently after a updating via the updaterscript today.
The log says:

```
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 334, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 209, in clear
netfilter-mailcow_1  |     for rule in input_chain.rules:
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1504, in _get_rules
netfilter-mailcow_1  |     return [self.table.create_rule(e, self) for e in entries]
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1818, in create_rule
netfilter-mailcow_1  |     return Rule(entry, chain)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 954, in __init__
netfilter-mailcow_1  |     self.rule = entry
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1350, in _set_rule
netfilter-mailcow_1  |     m = Match(self, match=match)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 547, in __init__
netfilter-mailcow_1  |     raise XTablesError("can't find match %s" % (name))
netfilter-mailcow_1  | iptc.xtables.XTablesError: can't find match geoip
```
Already restarted the container. Nothing changed, still restarting with this error.

Greetings and thanks

Shade

**Comment by andryyy** [comment]
Hi,
Which OS and which image version? => `docker-compose images netfilter-mailcow` (tag)

**Comment by Shadesh** [comment]
Ubuntu 16.04.4 LTS
```
              Container                    Repository       Tag      Image Id      Size  
-----------------------------------------------------------------------------------------
mailcowdockerized_netfilter-mailcow_1   mailcow/netfilter   1.13   69292c1330fb   63.4 MB

```

**Comment by andryyy** [comment]
That's strange. What's the output of `dpkg --get-selections | grep -i table` on your host?

**Comment by Shadesh** [comment]
iptables
iptables-persistent	
libxtables11:amd64	
xtables-addons-common
xtables-addons-dkms

**Comment by mitchellurgero** [comment]
What is the output of the following:
`iptables -m geoip --help`

On your host system?

**Comment by Shadesh** [comment]
`iptables v1.6.0

Usage: iptables -[ACD] chain rule-specification [options]
       iptables -I chain [rulenum] rule-specification [options]
       iptables -R chain rulenum rule-specification [options]
       iptables -D chain rulenum [options]
       iptables -[LS] [chain [rulenum]] [options]
       iptables -[FZ] [chain] [options]
       iptables -[NX] chain
       iptables -E old-chain-name new-chain-name
       iptables -P chain target [options]
       iptables -h (print this help information)

Commands:
Either long or short options are allowed.
  --append  -A chain		Append to chain
  --check   -C chain		Check for the existence of a rule
  --delete  -D chain		Delete matching rule from chain
  --delete  -D chain rulenum
				Delete rule rulenum (1 = first) from chain
  --insert  -I chain [rulenum]
				Insert in chain as rulenum (default 1=first)
  --replace -R chain rulenum
				Replace rule rulenum (1 = first) in chain
  --list    -L [chain [rulenum]]
				List the rules in a chain or all chains
  --list-rules -S [chain [rulenum]]
				Print the rules in a chain or all chains
  --flush   -F [chain]		Delete all rules in  chain or all chains
  --zero    -Z [chain [rulenum]]
				Zero counters in chain or all chains
  --new     -N chain		Create a new user-defined chain
  --delete-chain
            -X [chain]		Delete a user-defined chain
  --policy  -P chain target
				Change policy on chain to target
  --rename-chain
            -E old-chain new-chain
				Change chain name, (moving any references)
Options:
    --ipv4	-4		Nothing (line is ignored by ip6tables-restore)
    --ipv6	-6		Error (line is ignored by iptables-restore)
[!] --protocol	-p proto	protocol: by number or name, eg. 'tcp'
[!] --source	-s address[/mask][...]
				source specification
[!] --destination -d address[/mask][...]
				destination specification
[!] --in-interface -i input name[+]
				network interface name ([+] for wildcard)
 --jump	-j target
				target for rule (may load target extension)
  --goto      -g chain
                              jump to chain with no return
  --match	-m match
				extended match (may load extension)
  --numeric	-n		numeric output of addresses and ports
[!] --out-interface -o output name[+]
				network interface name ([+] for wildcard)
  --table	-t table	table to manipulate (default: `filter')
  --verbose	-v		verbose mode
  --wait	-w [seconds]	wait for the xtables lock
  --line-numbers		print line numbers when listing
  --exact	-x		expand numbers (display exact values)
[!] --fragment	-f		match second or further fragments only
  --modprobe=<command>		try to insert modules using this command
  --set-counters PKTS BYTES	set the counter during insert/append
[!] --version	-V		print package version.

geoip match options:
[!] --src-cc, --source-country country[,country...]
	Match packet coming from (one of) the specified country(ies)
[!] --dst-cc, --destination-country country[,country...]
	Match packet going to (one of) the specified country(ies)

NOTE: The country is inputed by its ISO3166 code.
`

**Comment by Shadesh** [comment]
Any news here?

**Comment by askanhesse** [comment]
I ran into the same problem and got no solution yet.

**Comment by andryyy** [comment]
Anyone willing to share his/her system for a look?

**Comment by askanhesse** [comment]
@andryyy Sure, `Linux XXXXX 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux`, so `Debian GNU/Linux 8 (jessie)` - or what exact thing you need to know?

**Comment by andryyy** [comment]
Oh, more a look ON the system. :-) Remote. Via AnyDesk etc.

But: You should upgrade your kernel to backports. Debian Jessie with 3.16 will crash Docker sooner or later. :-(

**Comment by askanhesse** [comment]
@andryyy Wrote you an PM per Mail

**Comment by ghost** [comment]
I have this same issue. Funny thing is that the container ran whitout problem for a while 3+ weeks. Then it started showing this behaviour. Any news?

**Comment by andryyy** [comment]
Logs? iptables?

**Comment by marcvorwerk** [comment]
I fixed this issue in my PR: https://github.com/mailcow/mailcow-dockerized/pull/4426
