### ISSUE TITLE
Server hangs up

### ISSUE THREAD

**Issue by requ1Re** [mailcow/mailcow-dockerized#1337]
Hello, I just installed mailcow.
I then tried to connect to it with Thunderbird and noticed that my server is no longer responding.
That happens everytime I try to connect with Thunderbird. I dont know whats happening and my logs are not giving me info neither...

Its a Debian 8 KVM server with Kernel 4.9.0-0.bpo.3-amd64
The server has 6 GB of RAM and 2 Cores. It is using like 2 GB of RAM and ~5% of both cores when this happens.

**Comment by andryyy** [comment]
It is probably netfilter-mailcow which bans you for failed logins. Try to disable existing accounts in all clients which may trigger a bad login. Or whitelist 0.0.0.0/0 in mailcow -> admin -> Fail2ban and check the netfilter logs.

**Comment by requ1Re** [comment]
Thanks for your answer, now I'm not getting banned!

But still Thunderbird wont detect the settings...

**Comment by andryyy** [comment]
Is autoconfig.emaildomain.tld set and valid in your DNS? Remember it can take a while until it propagates.

**Comment by requ1Re** [comment]
I got a "autoconfig" and "autodiscover" CNAME which point to my ${MAILCOW_HOSTNAME}

**Comment by requ1Re** [comment]
nvm, found that my router blocked it.
