### ISSUE TITLE
Lets Encrypt Certificates with HPKP and DANE

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1339]
Hi,

i was thinking about using the acme-client from now on.
In the past and until now a i use / used a skript based on this german [tutorial](https://thomas-leister.de/letsencrypt-zertifikate-mit-hpkp-dane/) with HTTP Public Key Pinning (HPKP) and DANE.
Public key is used for hash calculation because of not being renewed with every certificate renewal.
Can i use the same or a similar technique to create an renew certificates with acme-mailcow?

Thinking about renewing the public key:
How is this done in acme-mailcow?

Thanks for your help.

**Comment by mkuron** [comment]
Mailcow keeps the private key unchanged during renewal so that you can do key pinning.
