### ISSUE TITLE
portainer.conf overwritten on each update

### ISSUE THREAD

**Issue by mitchellurgero** [mailcow/mailcow-dockerized#1340]
## Issue:
portainer.conf overwritten on each update

## Description 
This is problematic because I have to edit the file to get my original configuration back. It should be as described here: https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

But it changes the port to 9002 for whatever reason.

**Comment by andryyy** [comment]
Oh, damn, good catch! I will fix it.

**Comment by andryyy** [comment]
Forgot the reference, but it is fixed.
