### ISSUE TITLE
Mail duplicates itself under drafts 

### ISSUE THREAD

**Issue by Ashby666** [mailcow/mailcow-dockerized#1342]
HI there,

I've got a big problem: I forwarded an email to a friend a now I have over 11000 mails under "draft". And per minute I get two more emails in it...

Already done:
- Reboot SOGO und Postfix
- Reboot machine
- Renew Postfix Container

When I deactivate the mailbox, I can restart sogo without problems... is it enabled, it failed.

Can someone help here?

**Comment by someshnnm** [comment]
can you paste logs ?

**Comment by hachre** [comment]
Probably a duplicate of https://github.com/mailcow/mailcow-dockerized/issues/1203 or https://github.com/mailcow/mailcow-dockerized/issues/1310

**Comment by andryyy** [comment]
What's your current value for `SOGoMaximumSyncWindowSize` and `SOGoMaximumSyncResponseSize`in `data/conf/sogo/sogo.conf`?

**Comment by Ashby666** [comment]
Thank you so far!

@andryyy 
SOGoMaximumSyncWindowSize: //SOGoMaximumSyncWindowSize
and
SOGoMaximumSyncResponseSize = 2048

**Comment by someshnnm** [comment]
yea change the run time parameters. Thats a good one bro.

**Comment by Ashby666** [comment]
@unpopularrhombus 
sorry, i don't get it.
I checked it with a fresh installation: all paramets are equal...

**Comment by andryyy** [comment]
Try to comment `SOGoMaximumSyncResponseSize` out and restart SOGo by running `docker-compose restart sogo-mailcow`. I have not seen this happening myself. If possible, I'd like to have a look at this machine when it happens. Mail me: info@servercow.de

**Comment by Ashby666** [comment]
@andryyy 
Thank you too, but I does not change anything.
Still a lot of new mails per minute. :-(

**Comment by Ashby666** [comment]
We deleted the active sync profile from android smartphone (gmail-app).
At the moment everything is fine...

Xiaomi A1, Android One, 8.0.0.
