### ISSUE TITLE
Question: Running Mailcow behind 2 Mailcow Relays

### ISSUE THREAD

**Issue by c0by85** [mailcow/mailcow-dockerized#1343]
It's maybe possible to run a mailcow mailserver behind 2 mailcow relays? when i try this, the error message with the loopback or forward to myself appears. I can't remember the exact wording.

Here my idea / wish.

@                   IN MX 10   mx01
@                   IN MX 10   mx02

Relays to the "hidden" mail server. So that nobody could find the real mailserver. 

Are further explanations necessary?

**Comment by c0by85** [comment]
i think the problem is, mailcow checks the mx record instead of straid forward the mails to the relayed host.

**Comment by c0by85** [comment]
No one an idea?

**Comment by tkorves** [comment]
Why are you trying to do so? I don't get a clue why this should be done in this way.

**Comment by mkuron** [comment]
> mailcow checks the mx record instead of straid forward the mails to the relayed host

That is correct. You would need to manually edit the Postfix config to tell the relays (configured as backup Mx) where to deliver messages they receive.

@tkorves is right, though. You don't gain anything by doing this. Message headers will still contain the hidden server's address. And there is no reason to hide your server anyway.

**Comment by c0by85** [comment]
the better way would be then, mailserver, 2 mx backup?

mx 5 mailserver
mx 10 backup
mx 10 backup

**Comment by tkorves** [comment]
I'd suggest to completely get rid of those backup servers - it's some sort of 90s if you think about these facts:
- Mail which can't be delivered should be held on the sending server for several days (normally four).
- In a virtualized environment, recovery from a failure should be possible within minutes ;-) .
- ...

I too had Backup MXs for several years running - but they were never really used - despite from spammers trying to use those servers ... ;-)

**Comment by c0by85** [comment]
OK, thanks.

**Comment by c0by85** [comment]
I still have questions and problems. here the config of the mx backup.

relay hosts
mail.server
in use for the relayed domains.

domain is created with the selected relay host.

both options are checked.

Relay domain 
Relay all recipients

but when i try to send a mail via the relay host, i get an error message.

May 02 20:08:56 pi2 sendemail[31172]: WARNING => Received:      550 5.1.0 <root@blub>: Sender address rejected: User unknown in relay recipient table
May 02 20:08:56 pi2 sendemail[31172]: ERROR => Exiting. No recipients were accepted for delivery by the mail server.

where can i find the relay recipient table? or is the relay function from mailcow not designed to keep the mail, until the main server is back up again?

do I have a error of thinking? 

i have my main mailcow server and want a second as a (mx) backup when the first is down.

**Comment by c0by85** [comment]
![image](https://user-images.githubusercontent.com/25707747/39541424-fdbdb7b4-4e45-11e8-89b4-d56183ec9a9e.png)

![image](https://user-images.githubusercontent.com/25707747/39541460-183d3fce-4e46-11e8-9c9c-8c54787015c2.png)
