### ISSUE TITLE
Mailcow deleted contents of dhparams.pem after update

### ISSUE THREAD

**Issue by Schuermi7** [mailcow/mailcow-dockerized#1344]
As said in the title, after yesterdays update my dhparams.pem was emptied, so every try of authorization failed, because TLS could not be enabled. Fixed this by issuing 
`openssl dhparam -dsaparam -out dhparams.pem 1024`
in data/assets/ssl/
This is some unknown behaviour, I didn't yet find in the issues.
Maybe this occured just to me, but I wanted to share this to you

Lukas

**Comment by andryyy** [comment]
Hi,
That's strange, as acme-mailcow would copy the default file: `[[ ! -f ${ACME_BASE}/dhparams.pem ]] && cp ${SSL_EXAMPLE}/dhparams.pem ${ACME_BASE}/dhparams.pem`
Have you ever changed the dhparams.pem yourself before updating?

**Comment by Schuermi7** [comment]
no i never tried to change the dhparams.pem for myself. I had an ACME issue, because of too many requests on my ACME Container but that's a different part of the ACME as far as I know. The SSL Example folder is existant and dhparams.pem is in it. So I am really confused

**Comment by mitchellurgero** [comment]
Default file? Is that regenerated with each install??

**Comment by mkuron** [comment]
@mitchellurgero, no, it is shipped with Mailcow. There is no added security by regenerating it, see #718.

**Comment by mritzmann** [comment]
_only as note:_

I had the same problem. On other installations (1:1 the same) the problem did not occur.

fix:

* `cp data/assets/ssl-example/dhparams.pem data/assets/ssl/dhparams.pem `
* `docker-compose down && docker-compose up -d`
