### ISSUE TITLE
TLSA records recommendations?

### ISSUE THREAD

**Issue by jol64** [mailcow/mailcow-dockerized#1346]
I am using the mailcow UI to check my DNS entries.. I like that the software helps me get this right. However I am wondering about the TLSA recommendations.
- My domains are not using DNSSEC yet (turns out to be difficult at least for one of the registrars). Does a TLSA record make sense in that situation? In any case I´d consider TLSA optional but suggest to use another footnote than the existing “optional”.
- One of them reads: _443._tcp.mailserver.domain	TLSA	3 1 1…
I think directly referencing the hash of the server cert is bad practice as you need to update that (with Letsencrypt no later than 3 months). Why not use the hash of the root cert?
- All the others read _25._tcp.mailserver.domain	TLSA	99: Address not available
99 is not defined in RFC6698. Is this an error message?

Can you please clarify?
Thanks, Joachim

**Comment by mkuron** [comment]
- TLSA records don’t hurt if you don’t have DNSSEC, but they won’t be used for DANE in that case. Feel free to submit a pull request that checks whether DNSSEC is even enabled.
- The key is not regenerated upon renewal. 3 1 1 refers to the public key and not the certificate.
- That is an error indeed. It seems like the PHP script cannot connect to the SMTP server to check the certificate. Can you provide any other information, logs, etc.?

**Comment by jol64** [comment]
- good suggestion, will consider that. Of course will also try to address DNSSEC with my registrars.
- But even referencing the same public key may cause trouble if you want to switch something (from different host name to combining/splitting SANs) - correct?
- In other words, "Address not available" implies TCP connection or TLS handshake failed? May be this is caused by my network setup. I don´t have a public static IP for my mail server, instead the mail server has a VPN (WireGuard) connection to an exposed VPS, that uses the technique described in https://github.com/mailcow/mailcow-dockerized/issues/302 to forward port 25, 143, and 587 to the mail server. In addition 443 is proxied by a nginx on the VPS. Now I would expect errors for any port I did not forward, but don´t understand the error for the ones opened. Connecting via telnet to these ports does work (can see the greetings of postfix and dovecot).
Which log is supposed to show that error?

**Comment by mkuron** [comment]
The private key should be reused whenever possible, so you should be fine. Of course, if you prefer to pin the CA instead of the server key, you can do that. We are only giving recommendations in the web UI.

The unusual setup explains the error. Seems like it doesn’t want to connect back to itself via the VPN for some reason. Since this is a very exotic setup, I‘m sure you‘ll understand that we won’t dedicate resources to fixing the issue, which might not even be Mailcow’s fault.

**Comment by jol64** [comment]
I understand that this is an unusal setup. I am adding a comment because I think I figured out one of the issues and maybe someone else benefits from the info.. the VPN just does IPv4, whereas I was announcing (indirectly via a CNAME) IPv6 as well. When I remove the IPv6 address the error message changes to 111: Connection refused.
To me it looks like IPv4 and IPv6 connections should probably be tested independently and any discrepancies spotted, or IPv6 tests skipped in case there is no AAAA record.
