### ISSUE TITLE
2FA for user accounts

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1348]
Hello,
I was just noticed that it is not possible to enable 2FA when logging in with a user account. I think it would be a nice security addition to have the ability to use 2FA for a normal user account. 

I wish you a great day,
Timo

**Comment by mkuron** [comment]
Duplicate of #740. SOGo doesn‘t support 2FA and there is no standard way to do it via SMTP/IMAP either. Of course, we could add 2FA to the user web page relatively easily, but there isn‘t much there worth securing.

**Comment by Gielovic** [comment]
Hello,
I would disagree on that. Currently running into the issue to use mailcow as a OAuth2 provider for a Nextcloud instance, as documented. However, the oauth login bypasses 2FA from Nextcloud, and I'm unable to add 2FA to the mailcow user.
Best regards,
Giel

**Comment by Adorfer** [comment]
it does not help much to comment on an issue which is 

1) closed
2) closed due to beeing a duplicate of another issue

in other words: your point may be totally valid (and it is in my eyes) and should be taken care of. But this is the wrong place to put that forward.
