### ISSUE TITLE
TOTP Autofocus

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1349]
Hey, this is a very small thing, but could you please add the `autofocus` tag to the TOTP login field?
Current:
`<input type="number" min="000000" max="999999" name="token" id="token" class="form-control" placeholder="123456" aria-describedby="tfa-addon">`
Should be:
`<input type="number" min="000000" max="999999" name="token" id="token" class="form-control" placeholder="123456" aria-describedby="tfa-addon" autofocus>`

If you login on mobile device, you cant just paste something in it, you always have to click on it.
If you login on computer, you cant just type the numbers in, you also first have to click in the field.
With the autofocus tag that wouldnt be the problem anymore.

As I said, a pretty small thing, but perfection is never a bad thing. :)

**Comment by andryyy** [comment]
Hm, it should do this already. Just confirmed it with Firefox.

```
$('#ConfirmTFAModal').on('shown.bs.modal', function(){
      $(this).find('#token').focus();
```

Autofocus will not work when it is hidden at first.

**Comment by PhoenixPeca** [comment]
I can also verify that it works in chrome mobile and desktop.
