### ISSUE TITLE
rspamd - Call to DYN_RL_CHECK failed

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#1350]
Since last update (last was around 17 of April) I get the following error,

call to (DYN_RL_CHECK) failed (2): /etc/rspamd/lua/rspamd.local.lua:62: attempt to index a nil value; trace: [1]:{/etc/rspamd/lua/rspamd.local.lua:62 - [Lua]};

Seems related to commit 7181ee4658926aea4b746d815627e54ce228534f

**Comment by andryyy** [comment]
Not critical, but I will fix it, thanks for your report.

**Comment by andryyy** [comment]
Fixed it aaand forgot the reference. :-(
