### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by AnimaI** [mailcow/mailcow-dockerized#1351]
hi,
I hope someone can help me. If I want to make an update, I get the following output. What can I do?

> ./update
Checking internet connection... OK
Checking for newer update script...
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: Could not read eca494c49cdb9f4fa228275dac1dcb2b202e7f44
error: Could not read f53006f6aba7d22c327c341383f8c76cc1dc62b9
error: refs/remotes/origin/master does not point to a valid object!
error: Could not read eca494c49cdb9f4fa228275dac1dcb2b202e7f44
error: Could not read f53006f6aba7d22c327c341383f8c76cc1dc62b9
error: Could not read 05e026db3a9d2ab098b26436b3b04cde0783ec4a
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 101 (delta 66), reused 85 (delta 50), pack-reused 0
Receiving objects: 100% (101/101), 11.58 KiB | 0 bytes/s, done.
Resolving deltas:  84% (56/66), completed with 18 local objects.
fatal: pack has 10 unresolved deltas
fatal: index-pack failed
fatal: reference is not a tree: origin/master
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Stopping mailcow...
Removing network mailcowdockerized_mailcow-network
Committing current status...
error: invalid object 100644 e3ed0d8b6d31500bca83dfb4619ac1fe21c98ee4 for 'data/web/lang/lang.en.php'
error: invalid object 100644 e3ed0d8b6d31500bca83dfb4619ac1fe21c98ee4 for 'data/web/lang/lang.en.php'
error: Error building trees
Fetching updated code from remote...
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: Could not read eca494c49cdb9f4fa228275dac1dcb2b202e7f44
error: Could not read f53006f6aba7d22c327c341383f8c76cc1dc62b9
error: refs/remotes/origin/master does not point to a valid object!
error: Could not read eca494c49cdb9f4fa228275dac1dcb2b202e7f44
error: Could not read f53006f6aba7d22c327c341383f8c76cc1dc62b9
error: Could not read 05e026db3a9d2ab098b26436b3b04cde0783ec4a
remote: Counting objects: 101, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 101 (delta 66), reused 85 (delta 50), pack-reused 0
Receiving objects: 100% (101/101), 11.58 KiB | 0 bytes/s, done.
Resolving deltas:  84% (56/66), completed with 18 local objects.
fatal: pack has 10 unresolved deltas
fatal: index-pack failed
Merging local with remote code (recursive, strategy: "theirs", options: "patience"...
error: refs/remotes/origin/master does not point to a valid object!
merge: refs/remotes/origin/master - not something we can merge
Potenial conflict, trying to fix...
fatal: unable to read tree 28e343f4460cc9de42192fc1ca0c5eba118553d3
rm: missing operand
Try 'rm --help' for more information.
error: invalid object 100644 e3ed0d8b6d31500bca83dfb4619ac1fe21c98ee4 for 'data/web/lang/lang.en.php'
error: invalid object 100644 e3ed0d8b6d31500bca83dfb4619ac1fe21c98ee4 for 'data/web/lang/lang.en.php'
error: Error building trees
Removed and recreated files if necessary.
Fetching new docker-compose version...
######################################################################## 100.0%
Fetching new images, if any...
WARNING: --parallel option is deprecated and will be removed in future versions.
Pulling unbound-mailcow   ... done
Pulling mysql-mailcow     ... done
Pulling redis-mailcow     ... done
Pulling clamd-mailcow     ... done
Pulling php-fpm-mailcow   ... done
Pulling sogo-mailcow      ... done
Pulling dovecot-mailcow   ... done
Pulling postfix-mailcow   ... done
Pulling memcached-mailcow ... done
Pulling nginx-mailcow     ... done
Pulling rspamd-mailcow    ... done
Pulling acme-mailcow      ... done
Pulling netfilter-mailcow ... done
Pulling watchdog-mailcow  ... done
Pulling dockerapi-mailcow ... done
Pulling ipv6nat           ... done
Fixing project name...
Starting mailcow...
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: stat /var/lib/docker/overlay2/1931cc7b01629db3c95a0c761c939f3e920e98531377066c06d68d36b61b49f5: no such file or directory
Collecting garbage...
Further cleanup...
If you want to cleanup further garbage collected by Docker, please make sure all containers are up and running before cleaning your system by executing "docker system prune"

The change of the Docker Compose also has the error.

> @host:[/opt/mailcow-dockerized]: docker-compose down
Removing network mailcowdockerized_mailcow-network
@host:[/opt/mailcow-dockerized]: sed -i 's#COMPOSEPROJECT_NAME#COMPOSE_PROJECT_NAME#g' mailcow.conf
@host:[/opt/mailcow-dockerized]: sed -i '/COMPOSE_PROJECT_NAME=/s/-//g' mailcow.conf
@host:[/opt/mailcow-dockerized]: docker-compose up -d
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: stat /var/lib/docker/overlay2/1931cc7b01629db3c95a0c761c939f3e920e98531377066c06d68d36b61b49f5: no such file or directory

**Comment by mritzmann** [comment]
Try it manually: https://mailcow.github.io/mailcow-dockerized-docs/install-update/#manual-update
