### ISSUE TITLE
SoGO does not show subfolders

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1353]
Hello,

i have enabled the option that tagged emails are saved in a subfolder of the inbox (e.g. mail+tag@example.com will be saved in Inbox -> tag).

However this subfolder is not shown in sogo but in mailclients like apple mail or outlook.
Any idea how this can be fixed? By the way, creating a subfolder in sogo manually works.

**Comment by tkorves** [comment]
You normally have to subscribe to newly created folders - which would also be the reason, that folders you've created with SOGo are subscribed. Subscribing to folders is a functionality of the IMAP protocol itself.

**Comment by mitchellurgero** [comment]
@phipag - You should be able to expand the inbox to show sub folders, just click (or double click) the folder icon next to inbox:
![screenshot_2018-05-03_19-53-14](https://user-images.githubusercontent.com/4168998/39609067-b0c65b3e-4f0b-11e8-935b-d5df8f85c34e.png)

**Comment by phipag** [comment]
@tkorves How can I subscribe folders?
@mitchellurgero I have tried to expand the Inbox, but that does not work for me.

btw. I have the newest mailcow installation.

**Comment by mitchellurgero** [comment]
In outlook under send/receive go to the options there and select all folders you want synced with imap.
