### ISSUE TITLE
SSL Multiple domains

### ISSUE THREAD

**Issue by xxtim42xx** [mailcow/mailcow-dockerized#1355]
Hello, 
is there any option to use Mailcow with multiple Domains and multiple SSL certificates for Mail sending ?

**Comment by mkuron** [comment]
You cannot use multiple certificates; need a certificate with multiple SANs. Besides the Mailcow hostname, there is _autoconfig._ and _autodiscover._ for each domain. Our Let's Encrypt Integration automatically obtains such a certificate for you.

**Comment by sriccio** [comment]
Talking about this, any idea how we could handle it when the number of SANs reaches letsencrypt limit ? Let's say if you have 1000 mail domains handled by mailcow ?

**Comment by chriscroome** [comment]
@sriccio see #461 for a work-around for the subjectAltName limit of 100 &mdash; hosting a reverse proxy for `auto*.*` domains on another small VPS.

**Comment by sriccio** [comment]
Thank you @chriscroome, I will take a look right away.
