### ISSUE TITLE
Multiple Bookings in ressources is not working as expected

### ISSUE THREAD

**Issue by fgebauer** [mailcow/mailcow-dockerized#1358]
Hi,
the `multiple_bookings` field in the ressources configuration is a simple checkbox, resulting in `0` or `1` in the `sogo_view` view. But according to the SOGo Installation guide, this field should be contain the maximum number of concurrent bookings. Now it's resulting in 0 = unlimited and 1 = one. What's weird because you would expect the opposite if you check the box.

https://sogo.nu/files/docs/SOGoInstallationGuide.html

MultipleBookingsFieldName (optional) | The value of this attribute is the maximum number of concurrent events to which a resource can be part of at any point in time.If this is set to 0, or if the attribute is missing, it means no limit. If set to -1, no limit is imposed but the resource will be marked as busy the first time it is booked.
-- | --

**Comment by MAGICCC** [comment]
Note that mailcow is using SQL and not LDAP. Therefore there's another meaning of the value

> The value of this field is the maximum number of concurrent events to which a resource can be part of at any point in time.
If this is set to 0, or if the attribute is missing, it means no limit and the resource will always be marked as free. If set to -1, no limit is imposed but the resource will be marked as busy the first time it is booked. If greater than 0, the resource will get marked as busy once it reaches the value.

https://sogo.nu/files/docs/SOGoInstallationGuide.html#Authentication-using-SQL

**Comment by fgebauer** [comment]
@MAGICCC 

Thx for your correction, my bad. 

But the text for SQL is saying the exact same thing. There is no difference in meaning. The implementation in mailcow is wrong. The possible values for this field are -1, 0 or greater than 0. How can you implement this with a simple checkbox? If I have enough time next week I will provide a PR.

**Comment by andryyy** [comment]
A checkbox is yes or no. -1 or 0. That's how we implemented it. It is not wrong, it just does not provide more options.

I will recheck this function... I think no one ever used it, tbh.

**Comment by fgebauer** [comment]
Thank you.

It's not a huge thing. That's why i named this issue "... not working as expected". Someone would expect that checking a box named "Multiple booking" enables "Multiple booking", but currently it disables multiple booking.

**Comment by andryyy** [comment]
I will fix it. I wonder if they changed it to fit LDAPs implementation some time ago. I don't want to talk myself out of this bug, but I'm sure I tested it thoroughly.

**Comment by fgebauer** [comment]
You're maybe right. 
Btw. i really like your great project. I'm all about it. Thank you very much for it.

**Comment by MAGICCC** [comment]
@fgebauer A nice description for the docs on how to use resources may be helpful for other users.

**Comment by andryyy** [comment]
Thansk @fgebauer 

I implemented it, will push it later.

Edit: Now it's also tested and confirmed working. :-)

**Comment by hupratt** [comment]
Hi @andryyy,

Sorry to open such an old issue but there seems to be a slight bug. Everything works as expected if I try to overbook with a single event. However the resource gets overbooked if the secondary event is a recurring event. Should I open a bug ticket? 

![Image](https://github.com/user-attachments/assets/8680c5ce-1a69-4630-8a3c-b38394784537)

![Image](https://github.com/user-attachments/assets/84ccbacc-b272-4cf8-b545-02dd0294702f)
