### ISSUE TITLE
Adding Blacklist to Netfilter

### ISSUE THREAD

**Issue by C78dev** [mailcow/mailcow-dockerized#1361]
Hey,

i'am searching for a nice way to configure a Blacklist for Netfilter.
I have serveral IPs blocked on the Docker-Host via F2B, but they are still able to connect to the Docker-Containers.

As mentioned on serveral issues.... dont touch the iptables rules for/from Docker.

So...is there a way to configure a blacklist in the netfilter container?

The best way was a feature request to edit the Blacklist over the MailcowGUI like the Whitelist :)

**Comment by mkuron** [comment]
> As mentioned on serveral issues.... dont touch the iptables rules for/from Docker.

Adding rules to the front of the table is usually safe. So you could do it that way.

> is there a way to configure a blacklist in the netfilter container?

There is currently no way to do that, but it's easy enough to add. Pull requests are welcome.

**Comment by andryyy** [comment]
I think I merged it to master a few days ago. 🐮

**Comment by C78dev** [comment]
The "Blacklist-Feature"? :)

Oooh... it's time for an Update :+1:

**Comment by MAGICCC** [comment]
For sake of completeness https://github.com/mailcow/mailcow-dockerized/commit/05e026db3a9d2ab098b26436b3b04cde0783ec4a

**Comment by C78dev** [comment]
Perfect work @andryyy 
Thx!
