### ISSUE TITLE
Database initialisation failed

### ISSUE THREAD

**Issue by danielfaulknor** [mailcow/mailcow-dockerized#1363]
Brand new install after following the user guide, I get this when I hit the UI for the first (and subsequent times):

`Database initialisation failed: SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key`

**Comment by danielfaulknor** [comment]
Oh, found the issue here: https://github.com/mailcow/mailcow-dockerized/commit/d13539a9adaa283f7075c1baae805d8309d1d809#diff-849fb1b93a046866d89f303a7e5f0275R257

**Comment by andryyy** [comment]
Yes, give me a few mins.

**Comment by danielfaulknor** [comment]
Oops, didn't see your reply
