### ISSUE TITLE
Style of Web UI broken

### ISSUE THREAD

**Issue by codesalatdev** [mailcow/mailcow-dockerized#1365]
In the current version of mailcow, the web ui is rendered almost useless on chrome desktop, because the configuration tabs are overlayed by the header of the site. With Firefox, everything is completely fine.

![How it looks in chrome](https://ngsger.de/images/mailcow_style.png)

**Comment by mkuron** [comment]
Please clear your browser cache.

**Comment by codesalatdev** [comment]
Okay well this is embarrassing 😂 I hate wasting hours of time to debug something like this ... Thanks for the help!
