### ISSUE TITLE
ACME 4096 Bit Keys / dhparam generation

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1366]
Hi,

I think at this time, it should be normal to use 4096bit RSA keys. What do you guys think about it?
`--keylength 4096`
And I think we should create every week a new dhparam file like this:
`openssl dhparam -out dhparam.pem -2 4096`

What you guys think?

**Comment by mkuron** [comment]
Regarding dhparams: that is unnecessary, see #718.
Regarding 4096 bits: that is the default already: https://github.com/kristapsdz/acme-client/blob/6ad1964b1a7e9c83302a825ae7b6ae1cce17d922/rsa.c#L34
