### ISSUE TITLE
Can't change nextcloud data directory

### ISSUE THREAD

**Issue by oli98** [mailcow/mailcow-dockerized#1368]
Hello,

I installed nextcloud with the helper script and I wanted to change my data directory. I tried to change in the config.php file and I got an "Internal Server Error The server encountered an internal error and was unable to complete your request..." error message on the webpage. After a reinstall I renamed the web/nextcloud/data directory, created a soft link in its place to my desired folder and changed the owner to the nginx containers www-data user. I got the same error. How can I change this directory?

**Comment by PhoenixPeca** [comment]
Hi @oli98,
Can we see the before and after changes of the `datadirectory` attribute in your config file?
Also, since you seem to have installed nextcloud within mailcow-dockerized, you should be informed that the value of the `datadirectory` attribute should be relative to the file system of mailcow-dockerized (not with your local machine's file system).

PS: A log would be appreciated. :-)

**Comment by PhoenixPeca** [comment]
## [update]

> ...I renamed the web/nextcloud/data directory, created a soft link in its place to my desired folder and changed the owner to the nginx containers www-data user...


Unfortunately, symlinking files outside docker's build context is not possible. **If you want to change nextcloud's `data` directory to the one in your local machine's (e.g. another partition), then you might be well-off installing nextcloud in your local machine instead and put both mailcow-dockerized and nextcloud in front of a reverse proxy server (e.g. NGINX/Apache2)**

**Comment by Mupohkopmec** [comment]
Hello!
Thank you, Mr., for the diagnosis.
Is there a chance of you to help me fixing all this?
PS: a log could be accomplished/=' true'?
Best regards,
Mupoh

Em qua, 9 de mai de 2018 06:46, Phoenix Eve Aspacio <
notifications@github.com> escreveu:

**Comment by hachre** [comment]
I use `mount --bind` to achieve this. It works well.

Essentially do this (example: you want the data to be in /cloud):
```
cd /opt/mailcow-dockerized
docker-compose down
mkdir /cloud
# optional: mount /dev/something /cloud
mv /opt/mailcow-dockerized/data/web/nextcloud/data /cloud
mkdir /opt/mailcow-dockerized/data/web/nextcloud/data
mount --bind -o noatime,nodiratime /cloud/data /opt/mailcow-dockerized/data/web/nextcloud/data
docker-compose up -d
```
