### ISSUE TITLE
Backup using gzip and tar very slow

### ISSUE THREAD

**Issue by wucke13** [mailcow/mailcow-dockerized#1369]
This combination is rather slow. Backing up a 15GB of emails takes more than an hour on a system based on a SSD. That's not so good. However, there is a quiet similar combination of software, which is noticeable faster:

+ [star](https://linux.die.net/man/1/star) as tar replacement
+ [pigz](https://zlib.net/pigz) as gzip replacement

They both excell the tar+gzip combination in speed, as they both do utilize multi threading. Please consider using them. The output will be readable by tar + gzip, so there is no incompatibility. Mainly tar limits the speed, because it was originally made for usage with tape archives, which are only compatible with sequential, strictly ordered writes. However, most people probably won't backup their mailcow stuff to tape archives...

**Comment by mitchellurgero** [comment]
What exactly is the issue here? backup speeds will depend on what you are doing on the system. Shutting down mailcow before backup will make it much fast since more disk I/O can be given to the backup process instead of MC.

Good luck.

**Comment by mkuron** [comment]
> Shutting down mailcow before backup will make it much fast since more disk I/O can be given to the backup process instead of MC.

Unless your server is really working hard, i.e. lots of messages per second or lots of users logged in, this won’t matter much.

> They both excell the tar+gzip combination in speed, as they both do utilize multi threading. Please consider using them.

Feel free to submit a pull request that makes such a change. It seems reasonable. Also, please give us some before/after numbers so we can see how much gain there is.

**Comment by mitchellurgero** [comment]
> Unless your server is really working hard, i.e. lots of messages per second or lots of users logged in, this won’t matter much.

Well - we don't know the whole story here at this point, I'd venture it is a VPS, and if its on the cheaper end the I/O will be lacking for sure. Depends on many things hence my (`backup speeds will depend on what you are doing on the system. `) statement from my previous post ;)

As an example: he could be using the server for more than just mailcow.

**Comment by wucke13** [comment]
The server is used for more than just mailcow, however the overall IO load is really low. Yes it is an VPS, however I once had a selfmade backup system which first ran of `tar` and `gzip`, but I made the switch to `star` and `pigz` because of throughput issues (to slow). That was on a 12 Core Machine on a raid 0 of 10K SAS HDDs. Thoughput went up noticeable, around 400% up in that case. The use case was to archive a full root file system of a linux box, with both target and destination residing on the raid.

**Comment by wucke13** [comment]
Regarding `tar` + `gz` vs `star` + `pigz`: 
```
time star compress-program=pigz -c nixpkgs > test_star.tar.g  
60.50s user 2.02s system 375% cpu 16.656 total

time tar cfz test_tar.tar.gz nixpkgs
44.88s user 1.59s system 102% cpu 45.518 total

1.1G May 18 21:46 test_star.tar.gz
1.1G May 18 21:47 test_tar.tar.gz
```
Things to note: as you can see on the datestamp, `star` was run first. So, if caching played a role, it played against `star`. Also notable: this was on a dual core laptop with a consumergrade ssd. Using enterprise hardware, the difference probably is even more significant.

**Comment by wucke13** [comment]
Ok then,
I packaged `star` for nixos. Here is an example Dockerfile to create an image, which has both `star` and `gzip` installed. 
```
FROM nixos/nix:latest
RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update
RUN nix-env -iA nixpkgs.pigz nixpkgs.s-tar
```
The equivalent to the `tar` + `gz` command I found in the backup script would be something like this:
```
star -cvp compress-program=pigz f=/backup/backup_vmail.tar.gz /vmail
```

I don't feel confident to make a PR as I don't know how to add the custom image nor how the backup script works in detail.

Edit: I created a [docker image](https://hub.docker.com/r/wucke13/compress/) which includes all needed tools. 

Edti 2: Some comparision using the docker image:
```
time sudo docker run -v $PWD:/test wucke13/compress:0.1 star -cvp compress-program=pigz f=/test/test-star.tar.gz /test/nixpkgs
=> 0.09s user 0.07s system 0% cpu 22.556 total

time sudo docker run -v $PWD:/test wucke13/compress:0.1 tar -cvzpf /test/test-tar.tar.gz /test/nixpkgs
=> 0.35s user 0.43s system 1% cpu 57.666 total
```
The difference probably can be increased by omitting the `verbose` flag.

**Comment by sam2kb** [comment]
For me backing up about 20Gb worth of emails takes forever.
We should definitely switch to pigz or even lbzip2
