### ISSUE TITLE
Autodiscover issues

### ISSUE THREAD

**Issue by lukebunger** [mailcow/mailcow-dockerized#1370]
I have mallow up and running fine, and all seems to be well.

On iOS, setting up email accounts with exchange is straightforward, however on Mac OS and windows, auto discovery fails, no matter what I've tried. Any advice would be appreciated.

**Comment by PhoenixPeca** [comment]
Hi @lukebunger,
Are you using the Outlook 2016 from Office365? You might want to check on this: #615

**Comment by lukebunger** [comment]
I am indeed! That would explain things. Thanks for the help.
