### ISSUE TITLE
Sogo keeps crashing

### ISSUE THREAD

**Issue by marekpierog** [mailcow/mailcow-dockerized#1372]
Hi,
after few minutes from restart SOGO responds for every request with HTTP 501 error.
`

10.05.2018, 07:40:22 | notice | [96]: 188.146.165.92 "GET /SOGo/so/me@[domain_name].net/Mail/view HTTP/1.0" 501 0/0 0.012 - - 3M
-- | -- | --
10.05.2018, 07:40:22 | notice | [96]: \|SOGo\| request took 0.011511 seconds to execute
10.05.2018, 07:40:22 | notice | 07:40:22.541 sogod[96:96] EXCEPTION: <MySQL4CouldNotOpenChannelException: 0x558109e99500> NAME:NoMoreConnections REASON:cannot open a additional connection ! INFO:(null)
10.05.2018, 07:40:22 | notice | [96]: <0x0x5581094249d0[GCSChannelManager]> DBPOOL: create new DB channel for mysql://mysql/mailcow/sogo_view
10.05.2018, 07:40:22 | notice | [96]: \|SOGo\| starting method 'GET' on uri '/SOGo/so/me@[domain_name].net/Mail/view'
`

At the same time there is no active connection to MariaDB from sogo container. Restarting sogo helps for few minutes but then it returns to the same state.

I'm using current version of mailcow-dockerized on ubuntu xenial running in a lxc container

**Comment by andryyy** [comment]
Hi, what does mysql-mailcow log at the same time?

**Comment by marekpierog** [comment]
Completely nothing, last log entry concerns restart of mysql container:
`root@mail2:/opt/mailcow-dockerized# docker-compose logs -t mysql-mailcow | tail -4
mysql-mailcow_1      | 2018-05-09T07:54:31.346645972Z 2018-05-09  9:54:31 140039699576576 [Note] Event Scheduler: scheduler thread started with id 6
mysql-mailcow_1      | 2018-05-09T07:54:31.772507261Z 2018-05-09  9:54:31 140039880542080 [Note] mysqld: ready for connections.
mysql-mailcow_1      | 2018-05-09T07:54:32.674900139Z Version: '10.2.14-MariaDB-10.2.14+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mysql-mailcow_1      | 2018-05-09T07:54:47.685107114Z 2018-05-09  9:54:47 140038977332992 [Note] InnoDB: Buffer pool(s) load completed at 180509  9:54:47

`

**Comment by andryyy** [comment]
Might be some weird "Docker in LXC" problem.

But... is mailcow under load when it happens?

**Comment by marekpierog** [comment]
No, it's a test installation with 2 domains and 3 accounts in total. Just one device with ActiveSync and one user accessing sogo webinterface.
Machine load is also OK and I can't see any sudden spikes of CPU load when sogo container "crashes".
