### ISSUE TITLE
Can't restore with helper script

### ISSUE THREAD

**Issue by Zyplonox** [mailcow/mailcow-dockerized#1373]
Hi when i want to restore the backups with the helper script it just say "Selected backup location has no subfolders"

The location i use:
root@janvn:/opt/mailcow-dockerized# ls -l /home/jan/mailcow
insgesamt 6980
-rw-r--r--  1 root root            3162570 Mai 10 11:54 backup_mysql
-rw-r--r--  1 root root             753401 Mai 10 11:54 backup_mysql.gz
-rw-r--r--  1 root root                871 Mai 10 11:54 backup_postfix.tar.gz
-rw-r--r--  1 root root             928882 Mai 10 11:54 backup_redis.tar.gz
-rw-r--r--  1 root root             366280 Mai 10 11:54 backup_rspamd.tar.gz
-rw-r--r--  1 root root            1904988 Mai 10 11:54 backup_vmail.tar.gz
drwxr-xr-x 20 root root               4096 Apr  9 13:13 postfix
drwxr-xr-x  2 _apt systemd-journal    4096 Mai 10 10:49 redis
drwxr-x---  2 lxd  syslog             4096 Mai  7 16:58 rspamd
drwxr-xr-x  5 5000            5000    4096 Mai  5 23:24 vmail
root@janvn:/opt/mailcow-dockerized#

I'm using current version of mailcow-dockerized on ubuntu server 18.04

**Comment by andryyy** [comment]
It creates time-stamped folders like `/backups/mailcow-2018-05-10-12-30-53/`, you just removed this structure. Try to create a folder `/home/jan/mailcow/mailcow-2018-05-10-12-30-53/` and move the tar files there. Select `/home/jan/mailcow/` as backup location when restoring data.

**Comment by Zyplonox** [comment]
I still have the original folder and first i tried it with the original. 

root@janvn:/opt/mailcow-dockerized/helper-scripts# ./backup_and_restore.sh restore
Backup location (absolute path, starting with /): /home/jan/mailcow-2018-05-10-10-49-35/
Using /home/jan/mailcow-2018-05-10-10-49-35 as backup/restore location.

Selected backup location has no subfolders
root@janvn:/opt/mailcow-dockerized/helper-scripts#

root@janvn:/opt/mailcow-dockerized/helper-scripts# ls -l /home/jan/mailcow-2018-05-10-10-49-35/
insgesamt 6980
-rw-r--r--  1 root root            3162570 Mai 10 12:40 backup_mysql
-rw-r--r--  1 jan  jan              753401 Mai 10 10:49 backup_mysql.gz
-rw-r--r--  1 jan  jan                 871 Mai 10 10:49 backup_postfix.tar.gz
-rw-r--r--  1 jan  jan              928882 Mai 10 10:49 backup_redis.tar.gz
-rw-r--r--  1 jan  jan              366280 Mai 10 10:49 backup_rspamd.tar.gz
-rw-r--r--  1 jan  jan             1904988 Mai 10 10:49 backup_vmail.tar.gz
drwxr-xr-x 20 root root               4096 Apr  9 13:13 postfix
drwxr-xr-x  2 _apt systemd-journal    4096 Mai 10 10:49 redis
drwxr-x---  2 lxd  syslog             4096 Mai  7 16:58 rspamd
drwxr-xr-x  5 5000            5000    4096 Mai  5 23:24 vmail
root@janvn:/opt/mailcow-dockerized/helper-scripts#

**Comment by andryyy** [comment]
But it is still not correct... You should have copied the backup location folder.

Read my comment above: 

    Try to create a folder /home/jan/mailcow/mailcow-2018-05-10-12-30-53/ and move the tar files there. Select /home/jan/mailcow/ as backup location when restoring data.

" /home/jan/mailcow/" is important, not "/home/jan". Since it is a folder in "/home", make sure it is readable by others. That's not the problem here, but it can become a second issue. :-)

**Comment by Zyplonox** [comment]
Ok nvm i got it my fault.
