### ISSUE TITLE
cant access the mobileconfig.php in order to set things up on my iphone

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1375]
Redirects me either to a 404 page or to the admin.php page. Is there anything I can do to fix that or is there anything that needs to be done before? I’d really like to receive mails natively on my iPhone.

**Comment by MAGICCC** [comment]
You need to login as your user in order to open the page and thus downloading the file
https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/mobileconfig.php#L7

**Comment by mfnalex** [comment]
What do you mean with "login as your user"? No matter what mailcow user I am logging into, I only get the admin panel.

**Comment by andryyy** [comment]
Login to mailcow UI with the credentials of a mailbox.
