### ISSUE TITLE
Office 356 messages get rejected because of  milter-reject: END-OF-MESSAGE from

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#1377]
I have some messages getting rejected from a outlook server in the log it only says,

milter-reject: END-OF-MESSAGE from mail-eopbgr50043.outbound.protection.outlook.com[40.107.5.43]: 4.7.1 Service unavailable - try again later; from=<*@*> to=<info@*> proto=ESMTP helo=<EUR03-VE1-obe.outbound.protection.outlook.com>

When I have the email send to my Gmail I see that both SPF & DKIM are a PASS.
What could this error be?

**Comment by andryyy** [comment]
That's a temporary reject as it sometimes occurs for greylisting. Rspamd history will tell you about the symbols and its scores.

**Comment by normanu** [comment]
goodmorning @andryyy 
I see in the log message of Rspamd,

2018-05-11 07:00:58 #7(rspamd_proxy) <b369da>; proxy; proxy_backend_parse_results: cannot parse input: error while parsing <unknown>: line: 1, column: 251 - 'invalid utf escape', character: 'n'

Also when I parse the source message from gmail in rspamd I get 
Cannot upload data: parsererror, SyntaxError: Unexpected token n in JSON at position 251

This seems wrong as gmail can receive this without a issue.

**Comment by andryyy** [comment]
Okay, but you need to find this mail in the history tab and check its score. It will tell you why it was soft-rejected. Check the symbols and show them to us if you need help. :-)

![grafik](https://user-images.githubusercontent.com/2972950/39913806-74bcd3a4-5503-11e8-8358-3f4d13262d54.png)

**Comment by andryyy** [comment]
Can you mail me the email you are trying to parse in Rspamd as attachment to info@servercow.de?

**Comment by normanu** [comment]
This mail does not show up in rspamd history overview, I have to go to
rspamd log with docker to find it.

task; rspamd_task_write_log: id: <
DB5PR07MB1542FE8C06FFBA3F0A99C0E1AB980@DB5PR07MB1542.eurprd07.prod.outlook.com>,
qid: <95C3F148006E>, ip: 104.47.0.64, from: <*@*>, (default: F (no action):
[2.09/9.00] [OMOGRAPH_URL(2.50){*.com;},R_DKIM_ALLOW(-0.20){*.
onmicrosoft.com;},R_SPF_ALLOW(-0.20){+ip4:*.47.0.0/17;},MIME_BASE64_TEXT(0.10){},MIME_GOOD(-0.10){multipart/related;multipart/alternative;text/plain;},MX_GOOD(-0.01){cached:
*.mail.protection.outlook.com;},ARC_NA(0.00){},ASN(0.00){asn:8075, ipnet:
104.40.0.0/13, country:US;},DKIM_TRACE(0.00){*.onmicrosoft.com:+;},DMARC_NA(0.00){*;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},HAS_XOIP(0.00){},HAS_X_PRIO_ONE(0.00){1;},IP_SCORE(0.00){ipnet:
*.40.0.0/13(-5.51), asn: 8075(-3.47), country:
US(-0.29);},RCPT_COUNT_ONE(0.00){1;},RCPT_MAILCOW_DOMAIN(0.00){*.nl;},RCVD_COUNT_THREE(0.00){3;},RCVD_IN_DNSWL_NONE(0.00){64.0.47.*.
list.dnswl.org :
127.0.3.0;},RCVD_NO_TLS_LAST(0.00){},TO_DN_EQ_ADDR_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]),
len: 522220, time: 12044.522ms real, 73.651ms virtual, dns req: 67, digest:
<8fe43525b3fce4bdfda13110fada8997>, rcpts: <info@*.nl>, mime_rcpt: <info@
*.nl>


2018-05-11 10:10 GMT+02:00 André Peters <notifications@github.com>:

**Comment by andryyy** [comment]
Can you try to run ./update.sh ?

**Comment by normanu** [comment]
that seemed to have fixed it!
Thanks @andryyy !
