### ISSUE TITLE
Can’t configure mail account on iPhone 

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1378]
Exchange takes ages to ping the server and although I set all necessary A records in my DNS configuration and unlocked all ports that are necessary on my servers end, I still can’t login also not via the mobileconfig profile. Mail in general via SOGo is working perfectly. Am I missing anything or doing something wrong ? Any help is apprecaited. 

If you may speak german, feel free to answer to that question in German too.

**Comment by mitchellurgero** [comment]
How long ago did you set up DNS? What mail client are you using?

**Comment by PhoenixPeca** [comment]
> Exchange takes ages to ping the server...

**Hi, just to make sure, did you check your iPhone's email sync frequency?** Can you really connect to the email server or not? The title and the content in this thread doesn't really line up properly.

You also mentioned Exchange, so I assume you are referring to the "Exchange ActiveSync Protocol". EAS communicates over HTTP/HTTPS, so if you can access SOGo, and autodiscover works well, then you are doing it right.

**Comment by xL0b0** [comment]
Okay maybe I wrote it a bit undetailed. I’ll try to describe the problem now in detail. 
So, basically I can log in into SOGo, receiving mails and sending mails, both work perfectly. 
Now the problem: I can not log in in any other mail clients. 
Personally I’d like to use my mail accounts on my iPhone. If I use the way via the mobileconfig profile and try to set things up via settings, it takes ages to load and at the end it says „cant reach imap server“, which doesn’t make sense, because I added the needed A record „imap.(mydomin).io which refers to the IP address of my mail server. Same thing applies to the C Name record of autodiscover and autoconfig, both called autoconfig/autodiscover.(mydomain).io referring to the subdomain I set for my Mailserver. 
Or am I doing something wrong about the records and is an SSL connection needed in order to set things up on the iPhone ? 
Also, if I try to set it up via Microsoft Exchange, either via the Windows mail app or via the iPhone default mail app, it says on windows it couldn’t find the necessary settings and on iPhone, it requests me to enter the server and related stuff, like domain, server IP, etc. but if I do that and hit „Save“ the Operation times out in the iPhone settings. 

Hope that’s now a bit more understandable 😅 if not I’m sorry and I’ll try to explain the things still not clear again.

**Comment by mitchellurgero** [comment]
imap.domain.io is incorrect - the server for Exchange(ActiveSync), smtp, and imap should be mail.domain.io.

Secondly - if you just recently did the setup in DNS it can take up to 48 hours to take affect depending on many factors like your DNS host, etc.

If you would like, I can assist via email (use a different one like gmail) to help you on troubleshooting if you do not want to give out the domain in a public forum.

**Comment by xL0b0** [comment]
Yeah, that would be apprecaited if we could mail each other. 
So I set my subdomain to be mail.domain.io. So how should the DNS entry look like then ? I’m a bit confused right now. I just followed the tutorial on mailcow documentation. So the host should be imap and the value mail.domain.io ?

**Comment by mitchellurgero** [comment]
No - who is your registrar where you manage DNS?

You can email me using any method found on my site: https://urgero.org

**Comment by xL0b0** [comment]
My domain provider is NameCheap.

**Comment by xL0b0** [comment]
I mailed you @mitchellurgero

**Comment by mitchellurgero** [comment]
I emailed you back - see response.

**Comment by xL0b0** [comment]
Okay resolved everything myself.

**Comment by iComputer7** [comment]
How did you fix it?

**Comment by Lexumiii** [comment]
@xL0b0 Hey Mate, its been a long time but i am currently facing the same Issue. Can you still remember what the issue was?
