### ISSUE TITLE
MailBox with no quota

### ISSUE THREAD

**Issue by posarelli** [mailcow/mailcow-dockerized#1379]
It is possible to have no quota limit in mailboxes?
I came from iRedMail. In iRedMail you can set a quota for domain and mailboxes with unlimited quota... 
It seems odd to to have this limitation...

Thanks in advance

**Comment by PhoenixPeca** [comment]
duplicate #71

**Comment by posarelli** [comment]
Sorry, you're right, my fault...

**Comment by andryyy** [comment]
It is not odd when you have limited disk space. It is strange to set it to unlimited and run into a full disk after a while.
I am not planning to add it soon, sorry. :-( But it is on my list.

**Comment by posarelli** [comment]
Well, it will be nice to set a global amount of space for domain (off course) but not be obliged set all the space for users... Maybe set a quota for domain but be free to let go single mailboxes. 
Just a tought...
I Have now, for example, some difficult to migrate a server with ca. 250GB of mail for 70 mailboxes.
Some users had a big archive (20GB o 30GB) others almost nothing (50/100Mb and so on). How can I set mailcow server for accomodate this? I'm forced to set a quota for every 70 user but is mandatory to check actual dimension because otherwise is impossible populate the domain: for 70 I just need to lower down the quota if i want to set equal for everyone, otherwise space go out and users can't be inserted enymore.
Hope you understand what I'm saying.
