### ISSUE TITLE
[QUESTION] Rspamd stats are reset

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#138]
I just update the containers to the latest version of master branch, something that I've noticed is that every time I restart the container the stats are reset. So for example I have the following numbers in my stats:

![image](https://cloud.githubusercontent.com/assets/205403/24162484/47dde13e-0e2d-11e7-985e-7e7ea900e39e.png)

When I restart the container it just start from zero, so my question here is: Is this normal behaviour or something is misplaced? Because I have the feeling that rspamd starts from nothing to learn spam messages and stuff again.

Thanks.

**Comment by andryyy** [comment]
Hi,
That shouldn't happen. I think the history file is not being touched. I will fix this tomorrow by moving to redis history.

**Comment by andryyy** [comment]
Fixed it now. You do not need to re-pull the image as long as you are using Rspamd 1.5.3. Just check this change: https://github.com/andryyy/mailcow-dockerized/blob/16d90b86d593795a9d70b7effe62764d3c5b292e/data/conf/rspamd/local.d/rspamd.conf.local

**Comment by axd** [comment]
@andryyy I didn't want to open a new issue, tell me if I have to... But I just noticed that rspamd can't see the dkim files and throw this error:

`cannot load dkim key /var/lib/rspamd/dkim/domain.com.dkim.key: cannot map private key /var/lib/rspamd/dkim/domain.com.dkim.key: No such file or directory`

I have to say that in the admin I've created a dkim key for my domain. Any thoughts? 

Thanks.

**Comment by andryyy** [comment]
That's fine. It signs the mail anyway.
But I changed the way mail is signed in newer versions. If you update mailcow, this message is gone.

**Comment by axd** [comment]
Hi @andryyy after many updates, statistics on rspamd are still being re-established after the volume recreation.

**Comment by andryyy** [comment]
Since we switched to Redis for history, yes. :( But I promise I fixed it in dev. :) Problem was the changing hostname with each container creation.
