### ISSUE TITLE
Phone number issue

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1386]
Hello,
I have found a crazy bug. I am not sure if it is actually a bug, but I wanted to report it anyway.

When I create a contact in Sogo and assign two numbers from the same type (2 cell numbers) to it, only one of them will show up in the contacts app on my iPhone. I am using ActiveSync. Is this normal? And if so can this be fixed, because clearly both numbers should be showing up. 

![img_1578](https://user-images.githubusercontent.com/6145026/40021462-2dd1c8b8-57c5-11e8-9325-a335d886cf8e.jpg)
<img width="711" alt="bildschirmfoto 2018-05-14 um 22 19 20" src="https://user-images.githubusercontent.com/6145026/40021470-338fb01c-57c5-11e8-88bd-d4830b278c5f.png">

**Comment by mitchellurgero** [comment]
That might be a bug in iOS's contacts app. Can you try an Android device? or a CardDAV app on Windows/Mac?

**Comment by andryyy** [comment]
AFAIR this is an ActiveSync limitation. :-(

**Comment by mitchellurgero** [comment]
^ Nice.

**Comment by mitchellurgero** [comment]
CardDAV would work fine though yes?

**Comment by andryyy** [comment]
Yes

**Comment by ntimo** [comment]
Oh, why does ActiveSync has such a stupid limitation? Okay I will just use CardDav then. 
Edit: With CardDAV it works fine.

**Comment by mitchellurgero** [comment]
Awesome! Was just about to ask. Cheers. You will have to ask Microsoft why ActiveSync has such a limitation.

**Comment by mkuron** [comment]
If I remember correctly, this is actually a SOGo limitation. It uses the type field to tell the phone numbers (and email addresses) apart when you use ActiveSync.
