### ISSUE TITLE
Set cipher suites preference in postfix

### ISSUE THREAD

**Issue by madic-creates** [mailcow/mailcow-dockerized#1387]
Hello,

everyone recommends to set a prefered server cipher but it's not activated in postfix for mailcow.
Is there a reason tls_preempt_cipherlist = yes isn't set in postfix main.cf?

Kind Regards,
   Madic

**Comment by mkuron** [comment]
Duplicate of #587.

**Comment by madic-creates** [comment]
I do not think it's a duplicate. The mentioned issue is about disabling TLS1.0 and some ciphers. I'm proposing to activate prefered server ciphers.

**Comment by mkuron** [comment]
Well, these things should go hand-in-hand. If you disable the outdated ciphers, there is no reason to prefer certain ciphers on the server anymore. The clients should already pick the best cipher that both client and server support.

**Comment by redheness** [comment]
> 
> 
> Well, these things should go hand-in-hand. If you disable the outdated ciphers, there is no reason to prefer certain ciphers on the server anymore. The clients should already pick the best cipher that both client and server support.

No, now, to get NIST and HIPAA compliance, you have to set a preferred cipher, it's to enable compatibility with older (and deprecated) ciphers but still force secure cipher if available by the client.
