### ISSUE TITLE
SOGo Super User privileges

### ISSUE THREAD

**Issue by jaapvdv** [mailcow/mailcow-dockerized#1388]
Does SOGo in mallow-dockerized have an active Administrative account?

I am used to having an admin account in SOGo to manage ACL's on user folders, but I am not able to login to SOGo using the mailcow admin account.

**Comment by mkuron** [comment]
This is not currently enabled, but you should be able to add
```
SOGoSuperUsernames = (admin@domain.zz, me@myotherdomain.zz);
```
to your [sogo.conf](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/sogo/sogo.conf).

If you want to make this configurable from the Mailcow admin UI, please feel free to submit a pull request. You would need to modify [bootstrap-sogo.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/sogo/bootstrap-sogo.sh) to write this option to the generated sogod.plist based on a new column that you add to the users database table.

**Comment by jaapvdv** [comment]
Adding the 'SOGoSuperUsernames' line (with my own account) to sogo.conf works, in so far that I have the 'administrator cog' added to the calendar / contacts / mail icons.
Finding users however does not work, it appears I only have the administrator/superuser interface added to my account. Actually finding users to modify ACL's/rights does not work.

The attached image shows a search for my own account (currently logged in), showing 'No matching user':
![capto_capture 2018-05-16_02-49-52_pm](https://user-images.githubusercontent.com/11373035/40118117-4ca8e5e6-5919-11e8-8f23-763e6f091567.png)

**Comment by mitchellurgero** [comment]
@jaapvdv This is not a supported feature at this time so some Admin items might not work as expected.

**Comment by jaapvdv** [comment]
Well, okay. Changing ACL's/rights is the only administrator option in SOGo as far as I know, so the interface is there, but it does not work.

**Comment by mkuron** [comment]
I have checked: it does work. It searches the same list of users that is searched when a user edits the ACLs on their own folders.

**Comment by jaapvdv** [comment]
Weird, as can be seen in the screenshot I attached, on my installation it doesn’t seem to work!

I am curious though, where to find those user ACL settings. I am not aware of their presence in SOGo 3 and have not found them (yet?) in SOGo4.

**Comment by andryyy** [comment]
Any interesting lines in `docker-compose logs sogo-mailcow` when this/nothing happens?

**Comment by mkuron** [comment]
Can regular user accounts search the global address list and edit their calendar/contacts ACLs? If not, this is a separate issue independent of the SOGo admin UI.

**Comment by jaapvdv** [comment]
docker-compose logs sogo-mailcow, me logging with my SuperUser account and executing a search:

sogo-mailcow_1       | May 17 08:57:07 1434749f9504 sogod [53]: SOGoRootPage successful login from '10.9.8.11' for user 'me@domain.nl' - expire = -1  grace = -1
sogo-mailcow_1       | May 17 08:57:08 1434749f9504 sogod [53]: 10.9.8.11 "POST /SOGo/connect HTTP/1.0" 200 54/93 1.661 - - 0
sogo-mailcow_1       | May 17 08:57:09 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me%40domain.nl HTTP/1.0" 302 0/0 0.002 - - 0
sogo-mailcow_1       | May 17 08:57:09 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me%40domain.nl/view HTTP/1.0" 302 0/0 0.003 - - 0
sogo-mailcow_1       | May 17 08:57:09 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Mail HTTP/1.0" 302 0/0 0.002 - - 0
sogo-mailcow_1       | May 17 08:57:09 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Mail/view HTTP/1.0" 200 18016/0 0.034 76942 76% 0
sogo-mailcow_1       | May 17 08:57:09 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/alarmslist?browserTime=1526540228 HTTP/1.0" 200 63/0 0.004 - - 0
sogo-mailcow_1       | May 17 08:57:10 1434749f9504 sogod [53]: <0x0x564ae2cb3670[NGImap4Client]> TLS started successfully.
sogo-mailcow_1       | May 17 08:57:10 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Mail/0/view HTTP/1.0" 200 13745/0 0.358 - - 0
sogo-mailcow_1       | May 17 08:57:10 1434749f9504 sogod [53]: <0x0x564ae3aff340[NGImap4Client]> TLS started successfully.
sogo-mailcow_1       | May 17 08:57:10 1434749f9504 sogod [53]: 10.9.8.11 "POST /SOGo/so/me@domain.nl/Mail/0/folderINBOX/view HTTP/1.0" 200 822/48 0.409 - - -16K
sogo-mailcow_1       | May 17 08:57:10 1434749f9504 sogod [53]: <0x0x564ae2c84a30[NGImap4Client]> TLS started successfully.
sogo-mailcow_1       | May 17 08:57:11 1434749f9504 sogod [53]: 10.9.8.11 "POST /SOGo/so/me@domain.nl/Mail/unseenCount HTTP/1.0" 200 21/31 0.327 - - 0
sogo-mailcow_1       | May 17 08:57:41 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar HTTP/1.0" 302 0/0 0.002 - - 0
sogo-mailcow_1       | May 17 08:57:41 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/view HTTP/1.0" 200 18094/0 0.035 75639 76% 0
sogo-mailcow_1       | May 17 08:57:41 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/alarmslist?browserTime=1526540259 HTTP/1.0" 200 63/0 0.003 - - 0
sogo-mailcow_1       | May 17 08:57:41 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/eventsblocks?ed=20180520&sd=20180514&view=weekview HTTP/1.0" 200 744/0 0.004 - - 0
sogo-mailcow_1       | May 17 08:57:41 1434749f9504 sogod [53]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/weekview?day=20180517 HTTP/1.0" 200 3550/0 0.012 74773 95% 0
sogo-mailcow_1       | May 17 08:57:42 1434749f9504 sogod [53]: 10.9.8.11 "POST /SOGo/so/me@domain.nl/Calendar/saveSelectedList HTTP/1.0" 204 0/25 0.892 - - 0
sogo-mailcow_1       | May 17 08:57:48 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/eventslist?asc=1&day=20180517&filterpopup=view_next7&search=title_Category_Location&sort=start&value= HTTP/1.0" 200 452/0 6.592 - - 0
sogo-mailcow_1       | May 17 08:57:51 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/personal/properties HTTP/1.0" 200 912/0 0.004 3341 72% 0
sogo-mailcow_1       | May 17 08:57:55 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/personal/links HTTP/1.0" 200 606/0 0.217 1917 68% 16K
sogo-mailcow_1       | May 17 08:58:01 1434749f9504 CRON[7668]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | May 17 08:58:01 1434749f9504 CRON[7669]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | May 17 08:58:01 1434749f9504 CRON[7667]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | May 17 08:58:01 1434749f9504 CRON[7670]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | May 17 08:58:02 1434749f9504 CRON[7668]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | May 17 08:58:02 1434749f9504 CRON[7667]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | May 17 08:58:23 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Administration HTTP/1.0" 200 7350/0 0.024 25105 70% 0
sogo-mailcow_1       | May 17 08:58:23 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/Calendar/alarmslist?browserTime=1526540301 HTTP/1.0" 200 63/0 0.004 - - 0
sogo-mailcow_1       | May 17 08:58:50 1434749f9504 sogod [54]: 10.9.8.11 "GET /SOGo/so/me@domain.nl/usersSearch?search=jvan HTTP/1.0" 200 13/0 0.003 - - 4K

The only thing I notice is that in two lines my account name 'me@domain.nl' is shown as 'me%40domain.nl' the last line show the search for an account name containing 'jvan' which results in 'No matching user' (while there actually is an account name starting with 'jvan'. Tried different other searches, same result.

**Comment by jaapvdv** [comment]
> Can regular user accounts search the global address list and edit their calendar/contacts ACLs? If not, this is a separate issue independent of the SOGo admin UI.

I found the settings - had to scroll down in the popup menu for the calendar or addressbook, hmm, the interface does not give any indication of more items in the menu. Anyhow, sharing is available, doing a search there for another account gives no results . . . 

(same results in 'docker-compose logs sogo-mailcow' no apparent indication of something going wrong)

**Comment by andryyy** [comment]
I tried and can confirm it is working here. :-(

But! I cannot search for my own user account. I see all resources and mailboxes but my own.

**Comment by jaapvdv** [comment]
As said, searching for an other account does not work either, not as a SuperUser, not in Calendar or Address Book.

Just remembering something!

My user is the only one for a specific domain, should I make all 20 users member of the same domain to be able to use these settings?
(and use aliases for mail addresses in the other domains?)

Just tested that by logging in as a user from a domain with 5 users, everything works!

I guess that I can use a workaround by adding all users to one (the primary) domain. 
Then making aliases for their actual mail addresses and only allowing the users to send mail as specific selected aliases, disallowing them to send from the primary domain if they are not allowed to.

I am going to close this issue. 
Thanks andryyy and mkuron for assisting! 

In the end, the problem was just me and not mailcow . . .

**Comment by andryyy** [comment]
Any output in the debug console of your browser? Any special chars in a users email address or full name?
