### ISSUE TITLE
Whitelist sender by moving mail or forward it.

### ISSUE THREAD

**Issue by murmelbahn** [mailcow/mailcow-dockerized#1391]
Hey all,

I‘ve checked the documentation and the issues but I didn‘t find an answer to my question.

At the momebt the user or admin or domain admin have to login to the mailcow gui to edit their whitelist. It would be really nice if the user only have to move a ham, which is marked as spam by rspamd to a specific IMAP folder to be added to the whitelist. If this isn’t possible maybe the user could forward the mail to an internal mail adress like whitelist@domain.tld to accomplish the same? I think this would be a nice solution for all mobile only users.

**Comment by mritzmann** [comment]
> if the user only have to move a ham [..] to be added to the whitelist.

I don't think that's a good idea. Just because I drag an email with the sender @example.com from the spam folder doesn't mean that every message from @example.com doesn't have to be spam.

> If this isn’t possible maybe the user could forward the mail to an internal mail adress

That's a better idea.

**Comment by murmelbahn** [comment]
Maybe you can use two folders: One for whitelisting the whole domain and one for the adress only? On the other hand it is still a faster method to edit your own whitelist. Do you know if a function like this exist in mailcow?

**Comment by mritzmann** [comment]
> Maybe you can use two folders

Wouldn't that be a feature that few would use, and all other users would be confused?

**Comment by murmelbahn** [comment]
if you can enable it per user it would be nice;) 

But at the moment there is no function included in mailcow to change the whitelist other then via gui?

**Comment by andryyy** [comment]
It auto-learns the message as ham when moved outside "Junk". That's just for bayes! When the message still triggers too many high scoring symbols, it doesn't help.

The neural module will improve this in the future.

The "whitelist" (as in a "real whitelist") should never be handled via IMAP.
