### ISSUE TITLE
quarantine notification mail

### ISSUE THREAD

**Issue by c0by85** [mailcow/mailcow-dockerized#1392]
is there a command to query the quarantine in the terminal? like the dovecot quota command. i need an email solution with the current status of the quarantine mails.

**Comment by mkuron** [comment]
They are stored in the database, so something like

```
echo 'SELECT * FROM quarantine' | docker-compose exec -T mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}
```

should do.
