### ISSUE TITLE
ClamAV false positive with 5 PDF

### ISSUE THREAD

**Issue by c0by85** [mailcow/mailcow-dockerized#1393]
got an false positive with an mail an 5 PDF attached.
according to virustotal.com scan all files are clean.
disable the PDF scan in data/conf/clamav/clamd.conf is not an option.

other solutions?

FROM_EQ_ENVFROM(0)
DYN_RL_CHECK(0)
MAILCOW_AUTH(-20)
TO_DN_ALL(0)
RCPT_MAILCOW_DOMAIN(0)[fu110.de]
RCVD_TLS_ALL(0)
RCPT_WANTS_SUBJECT_TAG(0)[x@x.de]
MID_RHS_MATCH_FROM(0)
DKIM_SIGNED(0)
TO_DOM_EQ_FROM_DOM(0)
ARC_SIGNED(0)[i=1]
VIRUS_FOUND(2000)
ARC_NA(0)
BAYES_SPAM(7.5)[100.00%]
RCVD_COUNT_ZERO(0)[0]
MIME_GOOD(-0.1)[multipart/mixed,text/plain]
RCPT_COUNT_ONE(0)[1]
FROM_HAS_DN(0)
TO_MATCH_ENVRCPT_ALL(0)
HAS_ATTACHMENT(0)

**Comment by Braintelligence** [comment]
Possible duplicate of https://github.com/mailcow/mailcow-dockerized/issues/990

**Comment by c0by85** [comment]
maybe, but i don't want to disable some scans...

**Comment by andryyy** [comment]
But what can _we_ do to fix ClamAV detections? :-)

What did ClamAV log? Which "virus" was detected?

**Comment by c0by85** [comment]
what is the service name from clamav? -> clamd-mailcow... ;-)
###

clamd is probably only for updates and clean.

**Comment by Braintelligence** [comment]
I had no problems with VBA macro filtering since an update some days ago, though.

**Comment by c0by85** [comment]
wich log do you want to see? the log from clamd is clean without virus detect messages.
###

can't find some qualified log stuff. only this.

xxx: milter-reject: END-OF-MESSAGE from x[xxx.xxx.xxx.xxx]: 5.7.1 Spam message rejected; from=<x@x.de> to=<x@X.de> proto=ESMTP helo=<[xx.xx.xx.xx]>

**Comment by andryyy** [comment]
Must be an older image or another error then, it should log like this:

clamd-mailcow_1      | Wed May 16 19:21:44 2018 -> instream(172.22.1.12@40150): OK

**Comment by c0by85** [comment]
nope nothing to see...

clamd-mailcow_1      | Wed May 16 18:56:45 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 18:56:45 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 18:58:47 2018 -> instream(172.22.1.2@57562): OK
clamd-mailcow_1      | Wed May 16 18:58:47 2018 -> instream(172.22.1.2@57562): OK
clamd-mailcow_1      | Wed May 16 19:01:14 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed May 16 19:01:14 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed May 16 19:01:14 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:01:14 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:06:56 2018 -> instream(172.22.1.2@58452): OK
clamd-mailcow_1      | Wed May 16 19:06:56 2018 -> instream(172.22.1.2@58452): OK
clamd-mailcow_1      | Wed May 16 19:10:47 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:10:47 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:13:59 2018 -> instream(172.22.1.2@59242): OK
clamd-mailcow_1      | Wed May 16 19:13:59 2018 -> instream(172.22.1.2@59242): OK
clamd-mailcow_1      | Wed May 16 19:16:18 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:16:18 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:20:22 2018 -> instream(172.22.1.2@59964): OK
clamd-mailcow_1      | Wed May 16 19:20:22 2018 -> instream(172.22.1.2@59964): OK
clamd-mailcow_1      | Wed May 16 19:28:28 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:28:28 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:32:36 2018 -> instream(172.22.1.2@33356): OK
clamd-mailcow_1      | Wed May 16 19:32:36 2018 -> instream(172.22.1.2@33356): OK

**Comment by andryyy** [comment]
We need the full logs for the time the reject happened..

**Comment by c0by85** [comment]
from docker-compose logs clamd-mailcow? that is the "full" log within the rejection time.
###
or this from postfix. but no other reject message.

postfix-mailcow_1    | May 16 13:02:24 mail postfix/smtpd[23488]: connect from x
postfix-mailcow_1    | May 16 13:02:24 mail postfix/smtpd[23488]: Anonymous TLS connection established from x: TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits)
postfix-mailcow_1    | May 16 13:02:24 mail postfix/smtpd[23488]: x client=x
postfix-mailcow_1    | May 16 13:02:37 mail postfix/cleanup[23493]: xm ilter-reject: END-OF-MESSAGE from x: 5.7.1 Spam message rejected; from=<x> to=<x> proto=ESMTP helo=<x>
postfix-mailcow_1    | May 16 13:02:37 mail postfix/smtpd[23488]: disconnect from x ehlo=2 starttls=1 mail=1 rcpt=1 data=0/1 quit=1 commands=6/7

**Comment by andryyy** [comment]
That's 13:02. And: time is probably UTC. You could grep for "instream" and filter "OK", like `docker-compose logs clamd-mailcow | grep instream | grep -v OK`.

**Comment by c0by85** [comment]
no output with -v... but without -v.

`docker-compose logs clamd-mailcow | grep instream | grep OK`

clamd-mailcow_1      | Wed May 16 19:10:47 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:10:47 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:13:59 2018 -> instream(172.22.1.2@59242): OK
clamd-mailcow_1      | Wed May 16 19:13:59 2018 -> instream(172.22.1.2@59242): OK
clamd-mailcow_1      | Wed May 16 19:16:18 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:16:18 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:20:22 2018 -> instream(172.22.1.2@59964): OK
clamd-mailcow_1      | Wed May 16 19:20:22 2018 -> instream(172.22.1.2@59964): OK
clamd-mailcow_1      | Wed May 16 19:28:28 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:28:28 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:32:36 2018 -> instream(172.22.1.2@33356): OK
clamd-mailcow_1      | Wed May 16 19:32:36 2018 -> instream(172.22.1.2@33356): OK
clamd-mailcow_1      | Wed May 16 19:37:23 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:37:23 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:39:34 2018 -> instream(172.22.1.2@34914): OK
clamd-mailcow_1      | Wed May 16 19:39:34 2018 -> instream(172.22.1.2@34914): OK
clamd-mailcow_1      | Wed May 16 19:39:42 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:39:42 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:42:26 2018 -> instream(172.22.1.2@35468): OK
clamd-mailcow_1      | Wed May 16 19:42:26 2018 -> instream(172.22.1.2@35468): OK
clamd-mailcow_1      | Wed May 16 19:43:34 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:43:34 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:46:58 2018 -> instream(172.22.1.2@36504): OK
clamd-mailcow_1      | Wed May 16 19:46:58 2018 -> instream(172.22.1.2@36504): OK
clamd-mailcow_1      | Wed May 16 19:54:08 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:54:08 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:56:30 2018 -> instream(172.22.1.2@37898): OK
clamd-mailcow_1      | Wed May 16 19:56:30 2018 -> instream(172.22.1.2@37898): OK
clamd-mailcow_1      | Wed May 16 19:58:29 2018 -> instream(local): OK
clamd-mailcow_1      | Wed May 16 19:58:29 2018 -> instream(local): OK

**Comment by andryyy** [comment]
The container was recreated in the meantime. :-( Just... mail the PDFs again and check ClamAV.

**Comment by c0by85** [comment]
same with some other stuff from heise.de. some test virus...

03BFB40156: milter-reject: END-OF-MESSAGE from web.heise.de[193.99.144.71]: 4.7.1 Try again later; from=<emailcheck-robot@ct.de> to=<x@x.de> proto=ESMTP helo=<web.heise.de>

there are also no other logs from the rejection.

**Comment by andryyy** [comment]
There are... rspamd-mailcow for example will tell you exactly which symbols were used. clamd-mailcow will tell you which virus. The milter-reject log line will tell you nothing.

**Comment by c0by85** [comment]
but there are no other logs with detailed stuff... I can't give something that i don't have / see.

**Comment by c0by85** [comment]
Works fine with the Sender on the whitelist, but only when it's external. Internal are rejected immediately.

**Comment by andryyy** [comment]
I told you which logs you need to check for the rejects. 

Rspamd logs exactly which symbols were inserted. Postfix logs the reject itself with no further details. Clamd logs the exact virus it found (as long as the container was not recreated! How is it supposed to know something that it never filtered?). 

The settings need some time to settle. 

I still have no idea what Clamd falsely flagged. Just provide the logs of clamd-mailcow now that it filtered these files again.

**Comment by c0by85** [comment]
if i had the right logs or the right entries, i would share them... if i could see the reason, i could also act. but nothing suitable is logged.

**Comment by andryyy** [comment]
You already posted Clamd logs, so it _is_ logging. You also posted excerpts of Postfix logs. They are not useful, but it _is_ logging. Rspamd seems to log, too, you posted the symbols in your first posts.

Just run `docker-compose logs --tail=100 -f clamd-mailcow` and try to send/receive these files, what exactly is happening?
Or mail me the files to info@servercow.de when they are publicly available or your own stuff you can share - I don't ask for private data. :-)

**Comment by andryyy** [comment]
```
clamd-mailcow_1      | Sat May 19 07:33:15 2018 -> instream(172.22.1.12@32984): OK
clamd-mailcow_1      | Sat May 19 07:33:15 2018 -> instream(172.22.1.12@32984): OK
clamd-mailcow_1      | Sat May 19 07:33:26 2018 -> instream(local): Eicar-Test-Signature(44d88612fea8a8f36de82e1278abb02f:68) FOUND
clamd-mailcow_1      | Sat May 19 07:33:26 2018 -> instream(local): Eicar-Test-Signature(44d88612fea8a8f36de82e1278abb02f:68) FOUND
```

Just confirmed it is working. Please just check these logs when the mail is rejected, post them and we will check what we can do.

**Comment by c0by85** [comment]
i've send you an email.

**Comment by c0by85** [comment]
:-( <info@servercow.de>: host x.mailcow.de[xx.xx.xx.xx] said: 550 5.1.0

@andryyy your given emailaddress was wrong...

**Comment by c0by85** [comment]
i was an paying customer at your service.... my domain is still active at your server, i can't send you mails...

Diagnostic-Code: smtp; 550 5.1.0 <x@x>: Sender address rejected: User
    unknown in virtual mailbox table

**Comment by c0by85** [comment]
Solved, Java Script was included and rejected from spamd.

**Comment by ChessSpider** [comment]
```
clamd-mailcow_1      | Wed May 30 09:03:57 2018 -> instream(172.22.1.2@55686): PUA.Pdf.Trojan.EmbeddedJavaScript-1(6ba63e571a29db98c0ad6a65e3193896:337931) FOUND
clamd-mailcow_1      | Wed May 30 09:03:57 2018 -> instream(172.22.1.2@55686): PUA.Pdf.Trojan.EmbeddedJavaScript-1(6ba63e571a29db98c0ad6a65e3193896:337931) FOUND
```

I saw this in the ClamAV today. I had the same last week. They were for valid emails though. 

Can I configure ClamAV to allow these emails?

**Comment by Braintelligence** [comment]
@ChessSpider You could have read the mentioned duplicate... https://github.com/mailcow/mailcow-dockerized/issues/990#issuecomment-362779477
