### ISSUE TITLE
Experiences with Ubuntu Server 18.04 LTS and mailcow?

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1394]
I thought about upgrading my mailcow server from Ubuntu Server 16.04.4 LTS to Ubuntu Server 18.04 LTS. I did not found a clear statement, if this should makes problems or it is save to upgrade. Have somebody experience with this upgrade?

**Comment by mitchellurgero** [comment]
Anything that can run git + docker can use mailcow-dockerized. In theory it should work. Always make backups before big changes though. Good luck!

**Comment by hachre** [comment]
@lgusewski Canonical does not recommend upgrading before end of July. If I were you, I'd wait. 

Source: https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes

> Upgrading from Ubuntu 16.04 LTS
> Upgrades from 16.04 LTS will not be enabled until a few days after 18.04.1's release expected in late July.

I upgraded one of my production servers (as a mirrored copy in a VM) and found that the entire network configuration hadn't been upgraded to the new system and the server would not have been able to come up after the reboot for SSH anymore.

**Comment by MAGICCC** [comment]
Upgraded all my VMs, and no problem until now. Since Canonical doesn't recommend upgrading like @hachre said, just wait. It's not that 16.04 is deprecated

Also there's no stable release for docker @ 18.04 available

**Comment by xetorixik** [comment]
In response to the subject. Can confirm that Mailcow is running fine with Ubuntu Server 18.04 LTS.
Although freshly installed.

**Comment by lgusewski** [comment]
> It's not that 16.04 is deprecated

Yes, the question comes from an information from my hoster that Images with Ubuntu 18.04 are released and a comment, that this release is with kernel 4.15 secure against Spectre and Meltdown. So that was the reason to thought about compatibility and a upgrade.

**Comment by mitchellurgero** [comment]
To be expected since it’s in docker. Good work though!

**Comment by xetorixik** [comment]
@mitchellurgero Mah, I do not entirely agree.
I tested all the notable distros before.
Running Ubuntu / Debian gave me the best result.

Although I am more of a person of Rhel for production and Arch for other than.
