### ISSUE TITLE
SOGo not working

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#1395]
Just installed MC on a fresh server, but SOGo won't let me in:

```
17.5.2018, 01:58:28 | notice | [47]: x.y.z.x "POST /SOGo/connect HTTP/1.0" 501 0/86 0.012 - - 0
-- | -- | --
17.5.2018, 01:58:28 | notice | 01:58:28.430 sogod[47:47] EXCEPTION: <NSException: 0x5650d3ce9630> NAME:NSRangeException REASON:Range location + length too great INFO:(null)
```

**Comment by gummipunkt** [comment]
Is the Sogo Container up and running?

> docker ps | grep sogo

**Comment by SoftCreatR** [comment]
It is. However, i guess i found the problem. It seems, that the option "Force password update at next login" caused it. After disabling this option, it worked.
