### ISSUE TITLE
seperating main domain and subdomain

### ISSUE THREAD

**Issue by AliBahramiEhsan** [mailcow/mailcow-dockerized#1397]
I was amazed by great mailcow and tried to install it. I've install it on mail.aalimoshaver.com (which is now up and running you can take a look) and used apache2 on first config. everything is fine and thanks to great installer, works as expected. but when I navigate on aalimoshaver.com, I saw what I see on mail.aalimoshaver.com. instead of index.html in /var/www/html i saw that. nothing on that folder is working. 
I searched a little and found out maybe the problem is in apache2 config (something in 000-default.conf). Sorry for newbie question and thank you in advance.

**Comment by daschxx** [comment]
You need to add to your apache2 config the vhost for aalimoshaver.com.
like:
```
<VirtualHost *:443>
    ServerName mail.example.org
    ServerAlias autodiscover.example.org
    ServerAlias autoconfig.example.org
    [...]

</VirtualHost>
<VirtualHost *:80>
    ServerName example.org
    DocumentRoot /var/www/html
</VirtualHost>
```
