### ISSUE TITLE
Quick question regarding the auto SSL Let's Encrypt certificate

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1399]
I know that you have to re validate Let's Encrypt certificates after a certain amount of time. Just for my knowledge, I just looked into the logs of the acme client and it says "ACME certificate validation done, sleeping for another day.". So it checks basically checks every day if there's a new certificate and if there's a new one it'll apply it by itself and I do not have to do anything ?

**Comment by mkuron** [comment]
That‘s correct.
