### ISSUE TITLE
Typo - Mailcows own IP address - Rspamd neural.conf

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1400]
Since this commit https://github.com/mailcow/mailcow-dockerized/commit/8ff4eb80769e071a02c3ba08f730035c44857591
Seems as the Mailcow test server's IP address https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/neural.conf#L1 has come along with the update.

Please fix.

**Comment by andryyy** [comment]
Thanks, I copied some of this, some of that, an that's what you end up with. 👍

**Comment by xetorixik** [comment]
Nice fast fix. Great job. Have a nice day.
