### ISSUE TITLE
Quick question : Any trouble with .htaccess and mailcow and LS ?

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1401]
I'm running my mailcow on port 80, so Let's Encrypt can work. I changed the part where you can log in to mailcow also to another subdomain. I don't want people to see mailcow interface if they access my general domain mailcow is bound to. If I'd add a .htaccess file and people access my domain, would that make any trouble with MailCow or Let's Encrypt ?

**Comment by mkuron** [comment]
.htaccess is only applicable to the Apache web server, but we use Nginx. You would need to make customizations here: https://github.com/mailcow/mailcow-dockerized/tree/master/data/conf/nginx . What you are trying to achieve is a duplicate of #1239 and some of the other issues mentioned there.
