### ISSUE TITLE
Can´t change RSPAMD Password

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1402]
When i want to change the RSPAMD password, follow messages appears:

[Errno 21] Is a directory: '/access.inc'

**Comment by andryyy** [comment]
The file was deleted manually and not recreated as a file.
Remove the directory worker-controller-password-bla in data/conf/rspamd/override.d and run up -d.

**Comment by develth** [comment]
Thanks!

up -d didn´t solved it, 

 docker-compose restart dockerapi-mailcow
 
Returned in an Error (didn´t recreated file):

```
ERROR: for mailcowdockerized_dockerapi-mailcow_1  Cannot restart container b088affcd82861342a22d5cc85d364febdd5956d5da164f181a33a965f6195f5: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/home/data/mailcow-dockerized/data/conf/rspamd/override.d/worker-controller-password.inc\\\" to rootfs \\\"/home/docker-container/aufs/mnt/c02ed5f7dd7b775a6dc51dc5f9088bcf3541e34c957ead11733d0190477550d1\\\" at \\\"/home/docker-container/aufs/mnt/c02ed5f7dd7b775a6dc51dc5f9088bcf3541e34c957ead11733d0190477550d1/access.inc\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Even after creation of file this error appears

**Comment by andryyy** [comment]
```
docker-compose down
rm -r data/conf/rspamd/override.d/worker-controller-password.inc*
docker-compose up -d
```
Should fix it.

**Comment by develth** [comment]
Fixed - thanks

**Comment by andryyy** [comment]
Is/was this an older installation? Like... 2-3 months?

**Comment by develth** [comment]
Yes, last updated ~ 20th March

**Comment by DerEnderKeks** [comment]
I just encountered a similar problem but with a different error message in the mailcow ui (`command did not complete`). Deleting the `worker-controller-password.inc` directory as mentioned above solved it for me too.
Posting this here just in case someone else is searching for the error message ;)

**Comment by andryyy** [comment]
Thanks for posting :)
