### ISSUE TITLE
Gtube bounced even for forwarding hosts

### ISSUE THREAD

**Issue by uonr** [mailcow/mailcow-dockerized#1403]
I have set backup MX as forwarding host:

![image](https://user-images.githubusercontent.com/34709816/40267392-295edab0-5b8e-11e8-9bd5-a4f764e13dff.png)

show milter reject Gtube mail and I received backscatter mail:

![2018-05-19 6 00 16](https://user-images.githubusercontent.com/34709816/40267415-828306f2-5b8e-11e8-8fb0-43449389b9c4.png)

There are not any reject mail record in Rspamd log.

there is bounce mail:

![2018-05-19 6 02 03](https://user-images.githubusercontent.com/34709816/40267439-c348b9a2-5b8e-11e8-8498-9624ec68df04.png)

The log from backup MX:

```
May 19 01:03:30 meta postfix/smtp[12017]: B71D6139025: to=<t@ioover.net>, relay=mail.ioover.net[8.3.29.128]:25, delay=0.66, delays=0.14/0.01/0.48/0.04, dsn=5.7.1, status=bounced (host mail.ioover.net[8.3.29.128] said: 554 5.7.1 Gtube pattern (in reply to end of DATA command))
May 19 01:03:30 meta postfix/cleanup[12016]: 659FE139029: message-id=<20180518170330.659FE139029@meta.ioover.net>
May 19 01:03:30 meta postfix/qmgr[13994]: 659FE139029: from=<>, size=3102, nrcpt=1 (queue active)
May 19 01:03:30 meta postfix/bounce[12019]: B71D6139025: sender non-delivery notification: 659FE139029
May 19 01:03:30 meta postfix/qmgr[13994]: B71D6139025: removed
May 19 01:03:42 meta postfix/smtp[12017]: 659FE139029: to=<t@ioover.net>, relay=mail.ioover.net[8.3.29.128]:25, delay=12, delays=0/0/0.07/12, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 78A189C52B)
```

**Comment by mkuron** [comment]
> milter reject Gtube mail

That is expected. rspamd's Gtube check happens before anything else so it can't be overridden by the forwarding hosts section.
