### ISSUE TITLE
Let's Encrypt certificate just applies to main domain, but does not apply to my subdomain.

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1405]
In the mailcow configuration I added the actual domain, but I would like to access mailcow rather through the subdomain. When I access the main domain, it says it's encrypted by Let's Encrypt and everything is alright. Compared to that if I access mail.mydomain.io it says that the certficate is not tested and is not safe. Is there any way of fixing that ? May be via the config ?

**Comment by andryyy** [comment]
What is main domain on this case?

Where did you add the actual domain and what is that exactly?

Would be great to see the whole mailcow.conf (you can replace the domain name) and the output of “docker-compose logs acme-mailcow” (also censored if you want to).

I’m sure acme-mailcow couldn’t request a certificate for you as an A or AAAA record was missing or wrong.

**Comment by xL0b0** [comment]
@andryyy you mean in the mailcow.conf file ? Honestly, the only thing I changed in there was the Mailcow_Hostname to to my domain.
Logs of acme look like that:
![2018-05-20_13-18-27](https://user-images.githubusercontent.com/38791556/40278364-62ab1d36-5c30-11e8-940c-ccdda554ebee.png)

**Comment by xL0b0** [comment]
@andryyy oh, habe gerade gesehen, dass du aus Deutschland bist, ich denke das ganze ist viel einfacher, wenn wir hier einfach deutsch schreiben denke ich :P

**Comment by andryyy** [comment]
If possible try to write in English. Wenn es gar ich anders geht, dann Deutsch. :)

Mailcow_hostname should never be a domain name but your servers FQDN. Like “mail.domain.tld”. Domain.tld is not a FQDN. It also says so when asking you for the hostname. 

Also ändere den Hostname bitte unbedingt zu sowas wie mx.example.org und führe up -d aus.

**Comment by xL0b0** [comment]
@andryyy Oh, casue in all tutorials on youtube people said that you just gotta put in your domain in that field. So should I put in there my mx.mydomain.io and then restart the server ?

**Comment by xL0b0** [comment]
@andryyy Could I maybe write you an email regarding that issue and we solve it there and close it in here ?

**Comment by andryyy** [comment]
Sure, we can also write in Telegram, just mail me to info@servercow.de - but please use mx.something.tld als MAILCOW_HOSTNAME and run `docker-compose up -d` inside your mailcow-dockerized folder. :-)

I will be back in a few hours.
