### ISSUE TITLE
Migrating from Roundcube (mailcow 0.14) to mailcow-dockerized

### ISSUE THREAD

**Issue by zedtux** [mailcow/mailcow-dockerized#1406]
I'm migrating from Mailcow 0.14 (without docker) to the latest version.

Previously we had Roundcube, and now it's SOGo. I'd like to import the `.mail` files from the `/var/vmail/ folder but I can't figure out how to do so.

Can you please help me?

So far, I've backed up my emails with the command `tar cvfz backup_vmail.tar.gz /var/vmail`. The MySQL database is incompatible so I re-configured everything by hand.

**Comment by normanu** [comment]
You can do either this,
https://mailcow.github.io/mailcow-dockerized-docs/u_e-backup_restore-maildir/

or go to /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1 and extract the mail folder in the correct place.

**Comment by zedtux** [comment]
Thank you @normanu I'll try it.
