### ISSUE TITLE
nextcloud nginx reverse proxy

### ISSUE THREAD

**Issue by xiaoveiti** [mailcow/mailcow-dockerized#1407]
after facing the reverse proxy for sogo, is there any "easy" way to use nextcloud behind a reverese proxy?

I dont want to setup the whole enviroment on the server, if the stuff is available through mailcow :) 
but I also need the reverse proxy for other webui etc. so how could I access nextcloud behind it?

looking forward to an answer :)

**Comment by stevesbrain** [comment]
Nextcloud should be as easy to run as anything else behind a reverse proxy :) Host your nextcloud on specified URL/port, point your proxy at it with appropriate config, and away you go! Some good config guides here:

https://docs.nextcloud.com/server/9/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by xiaoveiti** [comment]
if you are looking for the config.php -  /opt/mailcow-dockerized/data/web/nextcloud/config

**Comment by xiaoveiti** [comment]
deleted

**Comment by xiaoveiti** [comment]
Everything works fine, ... my fail. you just have to use ...:port/nextcloud**/** .... damn *head to table*

```
location ^~ / {
        proxy_pass http://127.0.0.1:8080/nextcloud/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100m;

```
but yea, make sure to also edit this part in the config.php:

```
  'overwritewebroot' => '/',
  'overwritehost' => 'cloud.domain.tld',
```

Closed
