### ISSUE TITLE
latest update broke sieve redirects

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1412]
Hi there, after latest update the redirect in sieve is not working anymore, i suppose it has something to do with IPV6 that in my case it is disabled (SYSCTL_IPV6_DISABLED=1 in mailcow.conf):

lmtp(test@domain.com)<77><UG9NNErjA1tNAAAAvQLlVA>: Error: sieve: Execution of script /var/vmail/sieve/test@domain.com.sieve was aborted due to temporary failure (user logfile /var/vmail/sieve/test@domain.com.sieve.log may reveal additional details)
lmtp(test@domain.com)<77><UG9NNErjA1tNAAAAvQLlVA>: Error: smtp-client: conn postfix:588 [1]: connect(fd4d:6169:6c63:6f77::a:588) failed: Network is unreachable

Looking at the sieve log file:
sieve: info: started log at May 22 11:35:50.
error: msgid=<89F9DF39-F737-41B4-8D7D-97EFD3C538F5@email.it>: failed to redirect message to <someemail@domain.com>: smtp(postfix:588): RCPT TO failed: Failed to connect to remote server (temporary failure).

The server has no networking problem and delivery to normal accounts is working as expected. Only if redirects are setup i get this error on those accounts. 

Can you please help? Should i re-enable IPV6? If yes, how?
Thank you

**Comment by andryyy** [comment]
Hi, That did not break with the last update, but is still something we need to fix.
Anyway: I recommend enabling IPv6 and run “up -d”.

**Comment by lucianlazar1983** [comment]
Thank you, by enabling IPV6 you mean put it in mailcow.conf and run docker down then docker up -d?

**Comment by andryyy** [comment]
Yes, up -d should be enough though.

**Comment by lucianlazar1983** [comment]
thanks, apparently is working now but it gives a warning:

warning | lmtp(email@domain.com)<51><kDKCC7P2A1szAAAAvQLlVA>: Warning: smtp-client: conn postfix:588 [5]: Received invalid EHLO response line: Unexpected character in EHLO keyword
-- | --

is it safe to ignore it for now?
Thanks again

**Comment by mitchellurgero** [comment]
> lmtp(email@domain.com)<51>: Warning: smtp-client: conn postfix:588 [5]: Received invalid EHLO response line: Unexpected character in EHLO keyword

This can be ignored - just a bad server / client trying to send you mail.  (bad as in maybe it is old, or it had a glitch and sent a wrong char.)

**Comment by lucianlazar1983** [comment]
Thank you all again, i will close this issue now.

**Comment by simon-india** [comment]
Guys I'm having the same issue but for some security reason I can't have IPv6 on this server can I override this any how. 

Thanks

**Comment by andryyy** [comment]
Can you post your exact error msg? Just want to be sure. :-)
