### ISSUE TITLE
DNS problems

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1413]
My mailcow setup seems to have a strange problem resolving DNS records; sometimes it works, sometimes it doesn't.

Some excerpts of the Postfix log:
`069D65201BB: to=<*******@web.de>, relay=none, delay=46626, delays=46606/0.04/20/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=web.de type=MX: Host not found, try again)`

`NOQUEUE: reject: RCPT from unknown[74.125.82.65]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [74.125.82.65]; from=<> to=<**********> proto=ESMTP helo=<mail-wm0-f65.google.com>`

Here's the Unbound log:
`######################################################################## 100.0%
unbound-mailcow_1    | [1526939792] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1526939792] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1526939792] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1526939793] unbound[1:0] info: start of service (unbound 1.6.2).`

I already tried several things:
- Testing the hostsystem's DNS resolving capatibilities using `nslookup web.de` - works
- Testing Unbound's DNS resolving capatibilities using `docker-compose exec unbound-mailcow nslookup web.de` - works
- Testing other container's DNS resolving capatibilities using `docker-compose exec unbound-mailcow nslookup web.de` - **doesn't** work
- Testing other container's DNS resolving capatibilities using `docker-compose exec unbound-mailcow nslookup google.com` - **works**

**Comment by nderjung** [comment]
I'm receiving the same error from `unbound-mailcow`.

**Comment by andryyy** [comment]
The "permission denied" error can be ignored.

Please check wether firewall/netfilter rules are active.

"docker-compose exec unbound-mailcow dig web.de" will resolve using **the nodes DNS**, not unbound.
"docker-compose exec unbound-mailcow dig web.de @127.0.0.1" would use unbound-mailcow.

@TebbeUbben2 You should check your list, you wrote "Testing other container's DNS resolving capatibilities" but your command says "docker-compose exec unbound-mailcow...".

You should also monitor the network traffic and see where the packages drop. Maybe your hoster doesn't allow these packages? You could remove all "dns: " settings from docker-compose.yml then.
