### ISSUE TITLE
nginx postfix dovecot restarting every 30 minutes

### ISSUE THREAD

**Issue by jaapvdv** [mailcow/mailcow-dockerized#1415]
Currently testing mailcow (looking to migrate to mailcow). 

While migrating mails from a test user to mailcow (using imapsync) imapsync stops with the following error:
<Unable to connect to <ip-address>: socket closed while reading data from server>

Configuration | Debug | Container information shows that while mailcow has been online since today, approx. 10.42 (after updating to the latest master), nginx, postfix & dovecot have (re)started around the time imapsync stopped:
<Transfer ended on                 : Wed May 23 11:16:49 2018>

![capto_capture 2018-05-23_11-20-27_am](https://user-images.githubusercontent.com/11373035/40415524-5a4395e0-5e7b-11e8-94ec-17e177f807da.png)

Postfix & dovecot logs (in Configuration | Debug | Logs) show that the services are being restarted every (give or take) 30 minutes . . . . (not just since updating mailcow, but since installing mailcow on May 15)

**Comment by andryyy** [comment]
Hi, I'm almost sure this is a firewall issue. Watchdog seems not to be able to reach any container.

Disable ufw or similar fws, run docker-compose down, restart docker.service and run up -d again. This should at least fix the iptables forwarding rules.

**Comment by jaapvdv** [comment]
Hi André,

Watchdog is not enabled.

Mailcow is running in a proxmox vm without a firewall configured or installed (in the vm).

**Comment by andryyy** [comment]
Hi,

Must be more critical then. :-( Are you lacking resources? Does Docker log to syslog why it restarts containers? Are you using LXC?

**Comment by andryyy** [comment]
Is it a test installation without data? If so: could you share credentials with me to have a look? Mail me to info@servercow.de 👍

**Comment by jaapvdv** [comment]
No, using a VM, not a container ;-)

VM is only running mailcow-dockerized and is configured to use 2 CPU's, 5GB of RAM and a 350 GB bootdisk. When running mailcow, memory usage tops at around 3,5GB.

Will check syslog when mailcow restarts the containers again and report back here.

**Comment by jaapvdv** [comment]
It is a test installation (with some actual data, but not live yet) but currently only accessible on the local network.
Have not yet configured a vhost on my reverse (nginx) proxy.

**Comment by jaapvdv** [comment]
Made a quick and dirty port-forward, sending you creds to login

**Comment by jaapvdv** [comment]
These are the contents of syslog when/while restarting the containers:

`May 23 11:50:57 mailcow kernel: [602210.176073] br-14f5def23e00: port 4(veth1d3eb84) entered forwarding state
May 23 12:17:01 mailcow CRON[27410]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 23 12:21:09 mailcow dockerd[17421]: time="2018-05-23T12:21:09+02:00" level=info msg="shim reaped" id=f4eeb1c3b7f2541a51b95b2f05ac190f2eff69de22c3dc0b73ac8e8377d0fabe module="containerd/tasks"
May 23 12:21:09 mailcow dockerd[17421]: time="2018-05-23T12:21:09.882773145+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 23 12:21:10 mailcow kernel: [604023.220910] br-14f5def23e00: port 7(veth8e000c7) entered disabled state
May 23 12:21:10 mailcow kernel: [604023.800897] br-14f5def23e00: port 7(veth8e000c7) entered disabled state
May 23 12:21:10 mailcow kernel: [604023.802063] device veth8e000c7 left promiscuous mode
May 23 12:21:10 mailcow kernel: [604023.802068] br-14f5def23e00: port 7(veth8e000c7) entered disabled state
May 23 12:21:12 mailcow kernel: [604025.443411] device vethbb632a1 entered promiscuous mode
May 23 12:21:12 mailcow kernel: [604025.443450] IPv6: ADDRCONF(NETDEV_UP): vethbb632a1: link is not ready
May 23 12:21:12 mailcow kernel: [604025.443453] br-14f5def23e00: port 7(vethbb632a1) entered forwarding state
May 23 12:21:12 mailcow kernel: [604025.443456] br-14f5def23e00: port 7(vethbb632a1) entered forwarding state
May 23 12:21:12 mailcow kernel: [604025.443725] br-14f5def23e00: port 7(vethbb632a1) entered disabled state
May 23 12:21:15 mailcow dockerd[17421]: time="2018-05-23T12:21:15+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/f4eeb1c3b7f2541a51b95b2f05ac190f2eff69de22c3dc0b73ac8e8377d0fabe/shim.sock" debug=false module="containerd/tasks" pid=28138
May 23 12:21:16 mailcow kernel: [604029.274708] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 23 12:21:16 mailcow kernel: [604029.296434] IPv6: ADDRCONF(NETDEV_CHANGE): vethbb632a1: link becomes ready
May 23 12:21:16 mailcow kernel: [604029.296454] br-14f5def23e00: port 7(vethbb632a1) entered forwarding state
May 23 12:21:16 mailcow kernel: [604029.296459] br-14f5def23e00: port 7(vethbb632a1) entered forwarding state
May 23 12:21:16 mailcow dockerd[17421]: time="2018-05-23T12:21:16+02:00" level=warning msg="OOM monitoring failed" error="cgroups: memory cgroup not supported on this system"
May 23 12:21:16 mailcow dockerd[17421]: time="2018-05-23T12:21:16+02:00" level=info msg="shim reaped" id=4df3f635afeb56e8729a73d71a68a69f7a34b9a1f2118b6bdc398d22c010c3f7 module="containerd/tasks"
May 23 12:21:16 mailcow dockerd[17421]: time="2018-05-23T12:21:16.814937689+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 23 12:21:17 mailcow kernel: [604030.321146] br-14f5def23e00: port 13(vethaa2405f) entered disabled state
May 23 12:21:17 mailcow kernel: [604030.996613] br-14f5def23e00: port 13(vethaa2405f) entered disabled state
May 23 12:21:17 mailcow kernel: [604030.997427] device vethaa2405f left promiscuous mode
May 23 12:21:17 mailcow kernel: [604030.997432] br-14f5def23e00: port 13(vethaa2405f) entered disabled state
May 23 12:21:21 mailcow kernel: [604034.540578] device veth22d71bb entered promiscuous mode
May 23 12:21:21 mailcow kernel: [604034.540615] IPv6: ADDRCONF(NETDEV_UP): veth22d71bb: link is not ready
May 23 12:21:21 mailcow kernel: [604034.540618] br-14f5def23e00: port 13(veth22d71bb) entered forwarding state
May 23 12:21:21 mailcow kernel: [604034.540621] br-14f5def23e00: port 13(veth22d71bb) entered forwarding state
May 23 12:21:21 mailcow kernel: [604034.541357] br-14f5def23e00: port 13(veth22d71bb) entered disabled state
May 23 12:21:24 mailcow dockerd[17421]: time="2018-05-23T12:21:24+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/4df3f635afeb56e8729a73d71a68a69f7a34b9a1f2118b6bdc398d22c010c3f7/shim.sock" debug=false module="containerd/tasks" pid=28674
May 23 12:21:24 mailcow kernel: [604037.971144] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 23 12:21:24 mailcow kernel: [604037.980272] IPv6: ADDRCONF(NETDEV_CHANGE): veth22d71bb: link becomes ready
May 23 12:21:24 mailcow kernel: [604037.980293] br-14f5def23e00: port 13(veth22d71bb) entered forwarding state
May 23 12:21:24 mailcow kernel: [604037.980298] br-14f5def23e00: port 13(veth22d71bb) entered forwarding state
May 23 12:21:25 mailcow dockerd[17421]: time="2018-05-23T12:21:25+02:00" level=warning msg="OOM monitoring failed" error="cgroups: memory cgroup not supported on this system"
May 23 12:21:27 mailcow dockerd[17421]: time="2018-05-23T12:21:27+02:00" level=info msg="shim reaped" id=025027268a5ccf1bee9057ba9dfebd0063b0f0cda42e6d679c77445a951be9ec module="containerd/tasks"
May 23 12:21:27 mailcow dockerd[17421]: time="2018-05-23T12:21:27.224727179+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 23 12:21:27 mailcow kernel: [604040.937977] br-14f5def23e00: port 4(veth1d3eb84) entered disabled state
May 23 12:21:30 mailcow kernel: [604043.736678] br-14f5def23e00: port 4(veth1d3eb84) entered disabled state
May 23 12:21:30 mailcow kernel: [604043.737545] device veth1d3eb84 left promiscuous mode
May 23 12:21:30 mailcow kernel: [604043.737551] br-14f5def23e00: port 4(veth1d3eb84) entered disabled state
May 23 12:21:31 mailcow kernel: [604044.320085] br-14f5def23e00: port 7(vethbb632a1) entered forwarding state
May 23 12:21:39 mailcow kernel: [604053.024120] br-14f5def23e00: port 13(veth22d71bb) entered forwarding state
May 23 12:21:43 mailcow kernel: [604056.263630] device vetha3aea12 entered promiscuous mode
May 23 12:21:43 mailcow kernel: [604056.263669] IPv6: ADDRCONF(NETDEV_UP): vetha3aea12: link is not ready
May 23 12:21:43 mailcow kernel: [604056.263673] br-14f5def23e00: port 4(vetha3aea12) entered forwarding state
May 23 12:21:43 mailcow kernel: [604056.263676] br-14f5def23e00: port 4(vetha3aea12) entered forwarding state
May 23 12:21:43 mailcow kernel: [604056.264652] br-14f5def23e00: port 4(vetha3aea12) entered disabled state
May 23 12:21:46 mailcow dockerd[17421]: time="2018-05-23T12:21:46+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/025027268a5ccf1bee9057ba9dfebd0063b0f0cda42e6d679c77445a951be9ec/shim.sock" debug=false module="containerd/tasks" pid=29028
May 23 12:21:46 mailcow kernel: [604060.004357] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 23 12:21:46 mailcow kernel: [604060.020285] IPv6: ADDRCONF(NETDEV_CHANGE): vetha3aea12: link becomes ready
May 23 12:21:46 mailcow kernel: [604060.020304] br-14f5def23e00: port 4(vetha3aea12) entered forwarding state
May 23 12:21:46 mailcow kernel: [604060.020308] br-14f5def23e00: port 4(vetha3aea12) entered forwarding state
May 23 12:21:47 mailcow dockerd[17421]: time="2018-05-23T12:21:47+02:00" level=warning msg="OOM monitoring failed" error="cgroups: memory cgroup not supported on this system"
May 23 12:22:01 mailcow kernel: [604075.040019] br-14f5def23e00: port 4(vetha3aea12) entered forwarding state
`

The containers that restarted this time are nginx and postfix (was not using accessing dovecot using imap . . . )

**Comment by jaapvdv** [comment]
Currently testing fresh install of mailcow in an AlpineLinux VM (with bash installed) on Proxmox, now using NAS NFS storage using RAID0+1, previously using a ZFS3 datastore where inconsistent and high IO delay was causing the above mentioned problems.
