### ISSUE TITLE
Connection to database failed

### ISSUE THREAD

**Issue by RosaEinhorn** [mailcow/mailcow-dockerized#1418]
Hi everybody,

I've migrated mailcow from one server to another about 14 days ago.
Since a few days I received the following error two times:

```
Connection to database failed.

The following error was reported:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

Does anybody have the same problem? Restarting the machine helps. I am seeing the error at mail.domain.tld instead of the login screen. 

Any idea on where to look at the problem the next time it occurs?

Thanks a lot in advance!

**Comment by andryyy** [comment]
Hi, 

Looks like a firewall problem. It cannot resolve names anymore. Do you use ufw or similar software? Inside the containers, it queries 127.0.0.11 for DNS.
Try to enter php-fpm-mailcow and dig/ping/whatever the name "mysql".

**Comment by tkorves** [comment]
Hi @RosaEinhorn,

you could try reading the logs of the containers itself:

`docker-compose logs --tail=<lines> -f <service>-mailcow`

Maybe it's quite obvious then.

BR, Tim

**Comment by reinistihovs** [comment]
I have the same problem, i have 2 mailcow servers running on Ubuntu 16.04, both of them have this issue.
I have nothing 3rd party installed witch could mess up the firewall.
Both of them are KVM virtual machines.
And i think so, this happens only on high load occasions.

**Comment by andryyy** [comment]
Or just a Docker daemon crash. Or automatic Docker daemon updates that restart the service and don’t recreate the containers (that’s bad for some updates). 

As soon as the internal resolver fails, it is a dockerd problem.

Some really slow IO machines tend to run into these problems. I also never had he chance to debug this when it happens. 

I cannot confirm this as a common problem on any of our managed servers. Make sure you aren’t on the nightly/edge channel for Docker.

**Comment by reinistihovs** [comment]
I use everything stock, and when this happens i have no time to debug, because everyone is freaking out, and i usually reboot the machine, and everything works again, in 7 months this happened aprox 10 times. Each time some hair falls off my head, and i get this cold feeling :) 

Probable solution:
maybe you can make a small script to dump all necessary logs and info to one file?  that would be a great solution, and could be a necessity to post here.

**Comment by andryyy** [comment]
No, sorry, I won’t write that script... it is really not a mailcow issue. We are not responsible for the internal name resolution of Docker. I’m sure the machines dockerd crashes for some reason - like I wrote previously. 

A shitty VM with slow IO, low memory and whatever are possible reasons. Syslogs and monitoring data are important for us to help. Can you monitor this?

Especially those 5 dollar VMs with 12 GB “RAM”, 1 TB “SSD” are prone to this. :-(
Overprovisoning sucks so much nowadays. Sorry for the offtopic rant. :-D But low memory can happen, even when your systems says 4 GB left. Most cheap hosters share 64 GB RAM over 150 VMs. Even with a lot of swap, your machine will do crazy stuff at some point.

**Comment by RosaEinhorn** [comment]
I think we can close this issue. Thanks for the support!
