### ISSUE TITLE
Potenial conflict

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1419]
Hi,

i got an error when i used update.sh

`Updating 7031af4..7002599
error: Your local changes to the following files would be overwritten by merge:
	data/conf/nginx/meta_exporter.conf
	data/conf/nginx/site.conf
	data/conf/postfix/main.cf
Please commit your changes or stash them before you merge.
Aborting
Potenial conflict, trying to fix...
rm: missing operand
Try 'rm --help' for more information.

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@d-2.(none)')`

How to fix it?

**Comment by andryyy** [comment]
Hi,

What's the returned output for `git diff data/conf/nginx/` and `git diff data/conf/postfix`?

To force the update, you could revert your changes by running `git checkout data/conf/postfix` and `git checkout data/conf/nginx`

**Comment by mritzmann** [comment]
> fatal: unable to auto-detect email address (got 'root@d-2.(none)')`

and also run this commands:

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by ghost** [comment]
Thanks guys! I solved this issue with a manual update.

```
git fetch origin master
git add -A
etc ..
```
