### ISSUE TITLE
Engine crashing while processing high amount of outgoing e-mails

### ISSUE THREAD

**Issue by bumbalaga** [mailcow/mailcow-dockerized#1422]
Hello, recently i have set-up a domain on my mail server to send out over 54 thousand mails, due to new privacy policy requirements.

Even though i have slowed down the mail output to 1/s it has caused the engine to crash multiple times slowing down the entire process.

I will provide necessary logs if required, but please help me out on how i can extract logs from yesterday.

Regards.

**Comment by MAGICCC** [comment]
You can get all logs with `docker-compose logs` or for each container with `docker-compose logs name_of_container`

**Comment by andryyy** [comment]
Plus syslog. When the Docker engine crashes, it will be logged there. But I don’t see why it would crash with 1 msg/s, we have machines with a much higher load.

**Comment by bumbalaga** [comment]
Hi, thanks for the input.

I will include the logs once i'm done dumping them. They have 100MB already, might take a while.
On 25/05/2018 14:00:05, André Peters <notifications@github.com> wrote:
Plus syslog. When the Docker engine crashes, it will be logged there. But I don’t see why it would crash with 1 msg/s, we have machines with a much higher load.

**Comment by andryyy** [comment]
You should check them yourself and see what looks critical. Please filter it before uploading or no one will want to check the files. 

Also check each containers log and find what looks suspicious. 

There is commercial support available for when you don’t want to mess with this. Remember all these amazing people here help you for free. :-) Work with them.

**Comment by bumbalaga** [comment]
Sure, i'm not planning on giving the work out and expecting the result to come on a silver plate.

I want to work together with the community, so i am not a burden. In some time someone else might have the same problem as me, so it would be helpful if we could resolve it here, for everyone to see :)
On 25/05/2018 14:09:26, André Peters <notifications@github.com> wrote:
You should check them yourself and see what looks critical. Please filter it before uploading or no one will want to check the files.
Also check each containers log and find what looks suspicious.
There is commercial support available for when you don’t want to mess with this. Remember all these amazing people here help you for free. :-) Work with them.

**Comment by bumbalaga** [comment]
I have extracted the logs and here they are:

Dovecot:
> May 25 00:40:01 mail CRON[379]: pam_unix(cron:session): session opened for user root by (uid=0)
May 25 00:40:01 mail CRON[380]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)
May 25 00:40:02 mail CRON[379]: pam_unix(cron:session): session closed for user root
May 25 00:40:15 mail dovecot: lmtp(365): Connect from IPv6<Hidden)::1
May 25 00:40:15 mail dovecot: lmtp(<e-mail hidden>)<365><oL2xMV9NB1ttAQAATToCew>: sieve: msgid=<20180524234015.C40221C7240@<domain hidden>>: not sending reject message to <>
May 25 00:40:15 mail dovecot: lmtp(<e-mail hidden>)<365><oL2xMV9NB1ttAQAATToCew>: sieve: msgid=<20180524234015.C40221C7240@<domain hidden>>: stored mail into mailbox 'INBOX'
May 25 00:40:15 mail dovecot: lmtp(365): Disconnect from IPv6<Hidden)::1: Client has quit the connection (state = READY)
May 25 00:40:17 mail dovecot: lmtp(65): Connect from IPv6<Hidden)::1
May 25 00:40:17 mail dovecot: lmtp(<e-mail hidden>)<65><wNRwLGFNB1tBAAAATToCew>: sieve: msgid=<20180524234017.B02491C723E@<domain hidden>>: not sending reject message to <>
May 25 00:40:17 mail dovecot: lmtp(<e-mail hidden>)<65><wNRwLGFNB1tBAAAATToCew>: sieve: msgid=<20180524234017.B02491C723E@<domain hidden>>: stored mail into mailbox 'INBOX'
May 25 00:40:17 mail dovecot: lmtp(65): Disconnect from IPv6<Hidden)::1: Client has quit the connection (state = READY)
2018-05-25 00:40:21,770 WARN received SIGTERM indicating exit request
2018-05-25 00:40:21,771 INFO waiting for cron, dovecot, syslog-ng to die
May 25 00:40:21 mail syslog-ng[38]: syslog-ng shutting down; version='3.8.1'
2018-05-25 00:40:21,877 INFO stopped: syslog-ng (exit status 0)
2018-05-25 00:40:21,899 INFO stopped: dovecot (exit status 0)
2018-05-25 00:40:21,900 INFO reaped unknown pid 46
2018-05-25 00:40:21,900 INFO reaped unknown pid 48
2018-05-25 00:40:21,901 INFO reaped unknown pid 50
2018-05-25 00:40:21,902 INFO stopped: cron (terminated by SIGTERM)
2018-05-25 00:40:25,121 CRIT Set uid to user 0
2018-05-25 00:40:25,129 INFO supervisord started with pid 1
2018-05-25 00:40:26,133 INFO spawned: 'cron' with pid 36
2018-05-25 00:40:26,137 INFO spawned: 'dovecot' with pid 37
2018-05-25 00:40:26,141 INFO spawned: 'syslog-ng' with pid 38
May 25 00:40:26 mail syslog-ng[38]: syslog-ng starting up; version='3.8.1'
May 25 00:40:26 mail dovecot: master: Dovecot v2.3.1 (8e2f634) starting up for imap, sieve, lmtp, pop3
2018-05-25 00:40:27,243 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-25 00:40:27,243 INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-25 00:40:27,243 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


postfix:

> 2018-05-25 00:40:17,700 WARN received SIGTERM indicating exit request
2018-05-25 00:40:17,701 INFO waiting for postfix, syslog-ng to die
May 25 00:40:17 mail syslog-ng[8]: syslog-ng shutting down; version='3.8.1'
May 25 00:40:17 mail postfix/cleanup[558]: B02491C723E: message-id=<20180524234017.B02491C723E@<domain hidden>>
May 25 00:40:17 mail postfix/bounce[533]: E16D91C71AC: sender non-delivery notification: B02491C723E
May 25 00:40:17 mail postfix/qmgr[359]: B02491C723E: from=<>, size=12477, nrcpt=1 (queue active)
May 25 00:40:17 mail postfix/qmgr[359]: E16D91C71AC: removed
May 25 00:40:17 mail postfix/lmtp[501]: B02491C723E: to=<<e-mail hidden>>, relay=dovecot[<ipv6 hidden>::3]:24, delay=0.06, delays=0.01/0.01/0.01/0.04, dsn=2.0.0, status=sent (250 2.0.0 <<e-mail hidden>> wNRwLGFNB1tBAAAATToCew Saved)
May 25 00:40:17 mail postfix/qmgr[359]: B02491C723E: removed
2018-05-25 00:40:17,806 INFO stopped: syslog-ng (exit status 0)
2018-05-25 00:40:17,884 INFO reaped unknown pid 356
2018-05-25 00:40:17,884 INFO reaped unknown pid 359
2018-05-25 00:40:17,885 INFO reaped unknown pid 358
2018-05-25 00:40:17,888 INFO reaped unknown pid 360
2018-05-25 00:40:17,889 INFO reaped unknown pid 365
2018-05-25 00:40:17,890 INFO reaped unknown pid 363
2018-05-25 00:40:17,890 INFO reaped unknown pid 367
2018-05-25 00:40:17,890 INFO reaped unknown pid 369
2018-05-25 00:40:17,891 INFO reaped unknown pid 381
2018-05-25 00:40:17,891 INFO reaped unknown pid 501
2018-05-25 00:40:17,891 INFO reaped unknown pid 502
2018-05-25 00:40:17,892 INFO reaped unknown pid 518
2018-05-25 00:40:17,892 INFO reaped unknown pid 533
2018-05-25 00:40:17,892 INFO reaped unknown pid 539
2018-05-25 00:40:17,893 INFO reaped unknown pid 551
2018-05-25 00:40:17,893 INFO reaped unknown pid 552
2018-05-25 00:40:17,893 INFO reaped unknown pid 556
2018-05-25 00:40:17,894 INFO reaped unknown pid 558
2018-05-25 00:40:17,894 INFO reaped unknown pid 559
2018-05-25 00:40:17,895 INFO reaped unknown pid 560
2018-05-25 00:40:17,895 INFO reaped unknown pid 561
2018-05-25 00:40:17,906 INFO stopped: postfix (terminated by SIGTERM)
2018-05-25 00:40:20,521 CRIT Set uid to user 0
2018-05-25 00:40:20,529 INFO supervisord started with pid 1
2018-05-25 00:40:21,532 INFO spawned: 'postfix' with pid 8
2018-05-25 00:40:21,536 INFO spawned: 'syslog-ng' with pid 9
May 25 00:40:21 mail syslog-ng[9]: syslog-ng starting up; version='3.8.1'
2018-05-25 00:40:22,553 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-25 00:40:22,554 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
May 25 00:40:22 mail postfix[269]: Postfix is running with backwards-compatible default settings
May 25 00:40:22 mail postfix[269]: See http://www.postfix.org/COMPATIBILITY_README.html for details
May 25 00:40:22 mail postfix[269]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
May 25 00:40:23 mail postfix/postfix-script[355]: starting the Postfix mail system
May 25 00:40:23 mail postfix/master[357]: daemon started -- version 3.1.8, configuration /opt/postfix/conf

Syslog:

> May 25 00:40:03 <hostname> snmpd[3616]: error on subcontainer 'ia_addr' insert (-1)
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49752->[<ipv4>]:161
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49752->[<ipv4>]:161
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49754->[<ipv4>]:161
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49754->[<ipv4>]:161
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49755->[<ipv4>]:161
May 25 00:40:10 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49755->[<ipv4>]:161
May 25 00:40:14 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49760->[<ipv4>]:161
May 25 00:40:14 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49760->[<ipv4>]:161
May 25 00:40:14 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49761->[<ipv4>]:161
May 25 00:40:14 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49761->[<ipv4>]:161
May 25 00:40:18 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49332->[<ipv4>]:161
May 25 00:40:18 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:49332->[<ipv4>]:161
May 25 00:40:33 <hostname> snmpd[3616]: error on subcontainer 'ia_addr' insert (-1)
May 25 00:40:38 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:60909->[<ipv4>]:161
May 25 00:40:38 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:60909->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56135->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56135->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/default: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/8cb271b3c0308a5d9fa389263dcd38a943143748d47f20cf55f59b0e7c1a6e29/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/8986a9d7e58ca872b75206dd2fdb986bf669fff7d02416bed91c092a5296793a/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/34996d00c22c18dc688589ebbc54c21e9b3325abad7ad26fbddb43a4e420c437/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/faf9c39ed73ebd434deffaf9c2001a790216dfccc2451de0762bf3f03b152815/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/d8917dc0d63eeabb7378940a329a46c7f514cd557bf467d284512da73f4904cc/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/d728bcf94e94654367f038787f9ff5e8c56af243cf988dc8b3c529d81b65d15f/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/743d1e81609bbeae00eeb912020d1f0134c70c51fb16cff23592aae1154955a4/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/5cd4a8971b14503af1c21b1d0869a4fd855fc26963e8774718561909c31c398c/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/942459db4a6d11b826eca1d5bc1f48cae67d49f7b7e8e32dd6ab44bba415c68b/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/74e040c0b088b8e0d4cf3613f5bf1da4a3b459b9b666ab629c95365f1024e2e9/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/619a5b1755c9bded8889dc1bf32a702d7e1a639bac13a84db6b447598590c662/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/2458eab5aa6f4523e9f6f79fc6a73da89b72dda4d2d27489a19eea8257536e02/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/45e4a7aefadc8c56c0b8587cded98130d17f08d28c9a5419e3f351369f948e9b/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/54c803128ed335e68b814a1745c1d2c9f71a4f816cde30ba2d340ed8bec61884/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/41a781018b850e649d98516496ce7a66ff614de434911612efc81b07431698ab/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/8818d0f1b238: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/140fe91572e4dca4df0884f936349decf73007f67c0a950ce49b6e28bb59f865/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/e00d0f81b0c4e5031ba8845767f00b7d0817b8ee382555253f0e9f0e6859c428/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/42f0284d096288457d0011763157217659effc45f1ad6f71de4f63bb5f0fda41/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/ef12e2cfb16c6336278a23665465104121e0f65ff69c99958214973473dcbed5/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/c003b33440dfbeffc4916b610729c02e70e14b8f04cc8915257903edfb497a8e/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/803b8394958b: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/d7616c49eb69: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/a2969ec54cdd: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/6bb5e953dc9e: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/fb5a95ed5235: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/5597d5ca8c60: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/8c70cacc5ad2: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/5bcd0a6dea297cb440a15f72122f58797a5afc07396e93ce34e520e32149152c/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/26ab518a37e1bf7428f57bb2064ed15a6ba9df1a0e38158f91e0fbd8ef82466c/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/07f799e42c6c: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/2c293d9edb9c0e783cb522785a3209908e7721dbe54fa9fc3ef7c706bf1d5ee8/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/b8de11231c89510b54794d541437c0772b0ae71bd05e89e57c2da41cb2e7c86b/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/ccea65dde0cc33b459b1c86f9f4d8c64ee75db7857e4fc1eaffbd3bb89d32143/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/47ef169a83fddecf8f91d60c571215e02e44c148b0874024b013994df7ac88c5/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/9b503b550d2de216341a5b0b79d9422871ff072f092b7b651d9da33226ca1eed/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/0ab021570746ee0e547d989ae41f2c5425f72200879184a5d70e5bcfca29f92d/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/e3853fbae52f: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/9797fc486279: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/overlay2/47497f6c80a8ccb4eb1085393130f5a4f34cbc1e3ccb957725571cfcc436d40d/merged: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/3c0e026af497fa34b518a178574a2d3739aa4389809786bc115576a96ce6cc5a/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/aff2caa1a04e: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/fa3af0fde7f558641416cbd26f015b855f843894e776ca06114bb5d57c351c59/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/85d736527bfb: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /var/lib/docker/containers/7a08d0fd658671092efcb76072bfb9e3f723433c3a114933103a9c7b13dce880/mounts/shm: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Cannot statfs /run/docker/netns/bbdf036c76c3: Permission denied
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56137->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56137->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56139->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56139->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56140->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56140->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56141->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56141->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56142->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56142->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56143->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56143->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56144->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56144->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56145->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56145->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56146->[<ipv4>]:161
May 25 00:40:42 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56146->[<ipv4>]:161
May 25 00:40:46 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56156->[<ipv4>]:161
May 25 00:40:46 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56156->[<ipv4>]:161
May 25 00:40:50 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56166->[<ipv4>]:161
May 25 00:40:50 <hostname> snmpd[3616]: Connection from UDP: [<ipv4>]:56166->[<ipv4>]:161

Combined:

> 2018-05-25 00:40:21,770 WARN received SIGTERM indicating exit request
2018-05-25 00:40:21,771 INFO waiting for cron, dovecot, syslog-ng to die
May 24 14:00:54 mail postfix/qmgr[348]: 4BC091C0B47: removed
May 24 14:00:54 mail postfix/lmtp[369]: 4BC091C0B47: to=<<e-mail hidden>>, relay=dovecot[<ipv6>::9]:24, delay=0.26, delays=0.2/0.01/0.01/0.04, dsn=2.0.0, status=sent (250 2.0.0 <<e-mail hidden>> IMa1HYa3Bls5AAAATToCew Saved)
May 25 00:40:21 mail syslog-ng[38]: syslog-ng shutting down; version='3.8.1'
2018-05-25 00:40:21,877 INFO stopped: syslog-ng (exit status 0)
2018-05-25 00:40:21,899 INFO stopped: dovecot (exit status 0)
2018-05-17 11:44:37 #9(controller) <mtny4g>; lua; settings.lua:615: loaded 3 elements of settings
2018-05-17 11:44:37 #11(normal) <775107>; task; bayes_classify: skip classification as spam class has not enough learns: 0, 20 required
2018-05-25 00:40:21,900 INFO reaped unknown pid 46
2018-05-25 00:40:21,900 INFO reaped unknown pid 48
May 24 14:00:55 mail postfix/smtpd[364]: disconnect from <rdns> ehlo=1 auth=1 mail=1 rcpt=1 data=1 rset=1 quit=1 commands=7
May 24 14:00:55 mail postfix/postscreen[377]: CONNECT from [<ipv4>]:26276 to [<ipv4>]:25
2018-05-25 00:40:21,901 INFO reaped unknown pid 50
2018-05-25 00:40:21,902 INFO stopped: cron (terminated by SIGTERM)
2018-05-17 11:44:37 #11(normal) <775107>; lua; greylist.lua:255: Score too low - skip greylisting
2018-05-17 11:44:37 #11(normal) <775107>; task; rspamd_task_write_log: id: <<rdns>>, qid: <B1F8C1C6F8C>, ip: 54.240.26.38, from: <<rdns>>, (default: F (no action): [1.49/15.00] [HTML_SHORT_LINK_IMG_1(2.00){},IP_SCORE(-1.00){ip: (-9.15), ipnet: <subnet>/22(-7.13), asn: 16509(-4.61), country: US(-0.84);},FORGED_SENDER(0.30){},MIME_HTML_ONLY(0.20){},MX_GOOD(-0.01){cached: <rdns>;},ARC_NA(0.00){},ASN(0.00){asn:16509, ipnet:<subnet>/22, country:US;},DKIM_TRACE(0.00){<domain>:+;<domain>:+;},DMARC_POLICY_ALLOW(0.00){<domain>;reject;},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){no-reply@<domain>;<rdns>;},RCPT_COUNT_ONE(0.00){1;},RCPT_MAILCOW_DOMAIN(0.00){<domain>;},RCVD_COUNT_ZERO(0.00){0;},RCVD_IN_DNSWL_NONE(0.00){<rdns> : <ipv4>;},RCVD_TLS_ALL(0.00){},R_DKIM_ALLOW(0.00){<domain>;<domain>;},R_SPF_ALLOW(0.00){+ip4:54.240.0.0/18;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 14495, time: 670.088ms real, 36.172ms virtual, dns req: 40, digest: <960383a6a295522ece50e8b353d4f24e>, rcpts: <<email>@<domain>>, mime_rcpts: <<email>@<domain>>
2018-05-25 00:40:25,121 CRIT Set uid to user 0
2018-05-25 00:40:25,129 INFO supervisord started with pid 1
2018-05-25 00:40:26,133 INFO spawned: 'cron' with pid 36
May 24 14:00:55 mail whitelist_forwardinghosts: Look up <ipv4> on whitelist, result 200 DUNNO
2018-05-17 11:44:37 #11(normal) <775107>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 4 regexps matched, 172 regexps total, 89 regexps cached, 0B bytes scanned using pcre, 16.69k bytes scanned total
2018-05-25 00:40:26,137 INFO spawned: 'dovecot' with pid 37
2018-05-25 00:40:26,141 INFO spawned: 'syslog-ng' with pid 38
May 24 14:00:55 mail postfix/dnsblog[384]: addr <ipv4> listed by domain hostkarma.junkemailfilter.com as 127.0.0.3
May 24 14:00:55 mail postfix/dnsblog[384]: addr <ipv4> listed by domain hostkarma.junkemailfilter.com as 127.0.1.1
May 25 00:40:26 mail syslog-ng[38]: syslog-ng starting up; version='3.8.1'
May 25 00:40:26 mail dovecot: master: Dovecot v2.3.1 (8e2f634) starting up for imap, sieve, lmtp, pop3
2018-05-25 00:40:27,243 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-25 00:40:27,243 INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-25 00:40:27,243 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-17 11:44:38 #8(rspamd_proxy) <41e4b4>; proxy; proxy_accept_socket: accepted milter connection from <ipv4> port 49726
May 25 00:40:54 mail dovecot: lmtp(53): Connect from <ipv4>

I see that theres an error on "subcontainer ia_addr", but what exactly can i do about it?

**Comment by andryyy** [comment]
Syslog is missing the part where it restarted the containers. Did watchdog restart them? Quiet possible in case you use it.

**Comment by bumbalaga** [comment]
See, there's nothing else in the syslog. Part posted above just repeats itself over and over again.

**Comment by andryyy** [comment]
Watchdog?

**Comment by bumbalaga** [comment]
> Sat May 12 16:09:39 GMT 2018 - USE_WATCHDOG=n, skipping watchdog...

it seems that i am not using it

**Comment by andryyy** [comment]
What's your operation system, dockerd version, resources, bla ... :-)

**Comment by bumbalaga** [comment]
Ubuntu 16.04 Xenial
Kernel: x86_64 Linux 4.4.105-mainline-rev1
CPU: 2x Intel Atom CPU C2750 @ 2.394GHz
Ram: 2GB
SWAP: 4GB

Docker version 18.05.0-ce, build f150324

docker-compose version 1.21.2, build a133471

There are some other services running on the VPS, but they should not affect mailcow.

I have my external Nginx redirect connections to mailcow (although it's not relevant i will mention it) 

Certificates generated by letsencrypt, all domains set-up correctly.

Mailcow was running 4 domains at the time, although only one was sending out large amounts of messages.

Error happened roughly every 5 minutes? Or 700 messages sent without slowing them down to 1/s (roughly 2/3 a second?)

Connections were made throught a php script using smtp with tls.

If you need any more details, let me know.

**Comment by andryyy** [comment]
I think it cannot handle the amount of msgs. 

You could try to disable all modules but DKIM signing for authenticated users (that's something we can add to the mailcow UI btw.):

Open `data/conf/rspamd/dynmaps/settings.php` replace the very last `}` (the last char in this file) by this:

```
    authenticated {
        priority = 10;
        authenticated = yes;
        apply "default" {
            symbols_enabled = ["DKIM_SIGNED"];
        }
    }
}
```

Restart Rspamd by running `docker-compose restart rspamd-mailcow` and check it again.

**Comment by bumbalaga** [comment]
Can you please explain what exactly am i turning off?

And if i understand correctly, it could be a problem with not enough power to scan all outgoing messages? If so, is that a "resource" or engine problem?
On 25/05/2018 23:17:04, André Peters <notifications@github.com> wrote:
I think it cannot handle the amount of msgs.
You could try to disable all modules but DKIM signing for authenticated users (that's something we can add to the mailcow UI btw.):
Open data/conf/rspamd/dynmaps/settings.php replace the very last } (the last char in this file) by this:
authenticated { priority = 10; authenticated = yes; apply "default" { symbols_enabled = ["DKIM_SIGNED"]; } } }
Restart Rspamd by running docker-compose restart rspamd-mailcow and check it again.

**Comment by andryyy** [comment]
All modules of Rspamd, except for the DKIM signing module will run. You could filter this more, my example above just checks for authenticated users.

**Comment by bumbalaga** [comment]
Sadly i don't really have a way of testing it out now, because i've already sent out the mails i have had to send. I will have to wait for a chance to do it again.
On 26/05/2018 22:09:21, André Peters <notifications@github.com> wrote:
All modules of Rspamd, except for the DKIM signing module will run. You could filter this more, my example above just checks for authenticated users.
