### ISSUE TITLE
A way to check if Mailcow is correctly configured ? 

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1424]
I asked myself, now that my Mailcow is working properly, I can send and receive mails and websites like checktls and mail-tester show me the highest score possible, Is that basically the confirmation that I did everything the right way or can I somehow check if I’m still missing anything?

**Comment by mkuron** [comment]
Yes, that sounds like a reasonable test. In terms of email, you are covered by what you did. You could also test SOGo calendar and contacts and set up mail, contacts and calendar in an email client like Thunderbird.
