### ISSUE TITLE
Mozilla Thunderbird problems with sending mails (connection times out)

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1428]
Quick description of the problem : if I log my self in to Thunderbird, configs are being found, it fetches everything and all mails are downloaded properly, so I can view them. If I try to answer an E-Mail it says that the connection to the SMTP server timed out. My question now is, what the issue for that might be ? Using that Mail account via SoGo works, using it via Exchange on my iPhone works too, but why not in Thunderbird ?

Any help is appreciated, thank you !

**Comment by mkuron** [comment]
SOGo uses an internal connection and Exchange uses SOGo. It seems like only external access to port 587/465 is not possible. Do you have a firewall configured on the Mailcow host that might be blocking the connection? Is Thunderbird running behind a router or firewall that might be blocking the connection?

**Comment by xL0b0** [comment]
@mkuron Yeah, on the server, Mailcow currently runs on is a firewall enabled (I can’t disable it, that’s something set by my host, I can just open ports). I looked in the documentation or a Github issue (can’t remeber it exactly anymore) and I opened following ports: 22, 25,  80, 110, 143, 443, 465, 587,  993, 995 and 4190. (all with the TCP protocol)

What do you men with „is Thunderbird running behind a router“ ?

**Comment by mkuron** [comment]
Is this an iptables firewall running on your machine or is it firewalled somewhere else on the network? In the former case, the rules may be conflicting with Docker's own rules.

Please post the output of `iptables --list` so we can determine where the issue lies.

**Comment by xL0b0** [comment]
@mkuron This is the output the iptables list command is giving me : 

https://i.imgur.com/Jak2hpC.png

**Comment by xL0b0** [comment]
I'm not so familiar with what kind of firewall my provider is using, but if I create a server it's a firewall that's added by default, so I don't have to configure anything on the OS itself, instead I'm doing everything in a webinterface. (Not sure if this is the answer you'd expect from me 😅)

**Comment by mkuron** [comment]
Ok, looks good. It seems like your provider is doing the firewalling outside of your machine. This means that on Mailcow's side and on your machine, everything is fine. Most likely this issue resides somewhere in the provider's firewall, e.g. you might have misconfigured something in their web interface.

**Comment by xL0b0** [comment]
@mkuron Okay, that sounds good, but is also bad, as I can just open ports in the Firewall and I am not able to disable it completely :/ So I bascially don't know what I might still be able to do. You might still know something, despite of opening ports ?

**Comment by hachre** [comment]
You might have to contact them to open the SMTP ports. Some providers block them completely unless you contact their Support.

**Comment by xL0b0** [comment]
But theoretically, if SoGo and Exchange on the iPhone with receiving and sendin mails work fine, isn't that basically the confirmation that the SMTP ports are open ?

**Comment by hachre** [comment]
Yeah, it looks like the main port 25 is open but 465/587 are not. It's strange. Is it possible that your router at home blocks access to those ports?

**Comment by xL0b0** [comment]
Is there any way to find that out ? Because yesterday, when I tried sending mails through the mail client Spark (I don't know if you know that client) I even couldn't sign in with my E-Mail. If I tried it through my cellular data, logging in and opening mails worked perfectly.

**Comment by hachre** [comment]
What kind of router do you have? For example, Deutsche Telekom routers use an internal list of allowed SMTP servers. You have to add your server to that list to make it work.

**Comment by mkuron** [comment]
> when I tried sending mails through the mail client Spark (I don't know if you know that client) I even couldn't sign in with my E-Mail. If I tried it through my cellular data, logging in and opening mails worked perfectly.

That definitely sounds like it‘s your home internet connection.

>  if SoGo and Exchange on the iPhone with receiving and sendin mails work fine, isn't that basically the confirmation that the SMTP ports are open ?

No, they have an internal direct connection.

**Comment by xL0b0** [comment]
@mkuron I have a Speedport Smart.

**Comment by hachre** [comment]
@xL0b0 It's a Telekom Router, so you'll either have to add your server to the list of allowed SMTP servers or disable that function entirely. It's called "Liste der sicheren Email-Server verwenden".

**Comment by andryyy** [comment]
This is one of the most fucked up things any router does on this planet.

They even block authenticated users on port 587/465.

**Comment by xL0b0** [comment]
JESUS ! Thank GOD ! I added it now in my router interface and I can finally send E-Mails via Thunderbird !!! Why does something like that even exist ... :O

**Comment by xL0b0** [comment]
And now I can finally send E-Mails via Spark (iOS Mail Client) from my wireless LAN, man I really became desperate because of that ! Highly appreciate it that you could help me !
