### ISSUE TITLE
current mailcow version

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#1429]
Since https://github.com/mailcow/mailcow-dockerized/commit/6ef521e8251b432cc4f87b06413624aead49cd80 introduces the current 'mailcow version' but it should use `.git/logs/refs/remotes/origin/master` in the docker-compose.yml file because the updater creates a new commit and therefore the webpage shows a wrong hash and the link is broken.

Would PR it but dev is behind master

**Comment by mkuron** [comment]
Looking at origin/master is also useless because then `git fetch` would also seem to update Mailcow even though that leaves the working tree untouched. Ideally, one would search for the latest common ancestor of HEAD and origin/master.

Since this would be a bug fix, you can post a PR for master.

**Comment by andryyy** [comment]
Yes, sorry, I messed it up.

**Comment by MAGICCC** [comment]
@mkuron I guess finding the latest common ancestor is more difficult then using tags? 
(/me hides)

**Comment by mkuron** [comment]
No big deal. We can even identify whether someone is on the dev branch or on master:
```
mc=$(git merge-base origin/master HEAD)
dc=$(git merge-base origin/dev HEAD)
if [ "$(git show -s --format=%ct $mc)" -gt "$(git show -s --format=%ct $dc)" ]; then
    echo "master $mc $(git show -s --format=%ci $mc)"
else
    echo "dev $dc $(git show -s --format=%ci $dc)"
fi
```

**Comment by MAGICCC** [comment]
Ah right theres git merge-base...
