### ISSUE TITLE
The Watchdog deamon send no mails

### ISSUE THREAD

**Issue by daschxx** [mailcow/mailcow-dockerized#1430]
the problem is the smtp-cli gives error:
> Can't locate object method "new" via package "IO::Socket::INET6" at ./smtp-cli line 419.

with option --ipv4 it is ok but not ipv6 compatible for the future.

my solution:
https://github.com/mailcow/mailcow-dockerized/commit/1efc31885b3f8d16cce0df8f1fbbeaac15112013

**Comment by andryyy** [comment]
Hm, you disabled IPv6 in mailcow.conf? Or you don't use it on your node?

**Comment by daschxx** [comment]
No, all Containers get both ipv4 and ipv6.
but I think smtp-cli want to use IO::Socket::INET6 and its not installed.

```
bash-4.3# ./smtp-cli --verbose --server localhost
!!! IO::Socket::INET6 -- optional module not found
!!! Socket6 -- optional module not found
!!! These modules are required for IPv6 support

!!! Neither File::LibMagic nor File::Type module found.
!!! Used for guessing MIME types of attachments. Optional.

!!! Digest::HMAC_MD5 -- optional module missing
!!! Used for CRAM-MD5 authentication method
!!! Use --missing-modules-ok if you don't need the above listed modules
!!! and don't want to see this message again.

Can't locate object method "new" via package "IO::Socket::INET6" at ./smtp-cli line 419. 

```
on your machine any other result?

**Comment by andryyy** [comment]
I have not tested it with smtp-cli 3.9 tbh. Thanks for reporting it! I will update images.
