### ISSUE TITLE
Mails from forwarding host still being flagged as spam

### ISSUE THREAD

**Issue by flobeier** [mailcow/mailcow-dockerized#1432]
I added an IPv6 /56 subnet as forwarding host and disabled the spam filter for it (column "spam filter" shows an "X"). The postfix log displays "WHITELISTED" whenever a connection from this subnet occurs. However, Rspamd still flags mail from this subnet even though I disabled the spam filter for it.

**Comment by mkuron** [comment]
Messages are still flagged as spam, they are just never rejected. If you don't want spam checks at all, you can select that on the page where you configure forwarding hosts.

If you are still getting rejections, please show us the appropriate lines from the rspamd log and your forwarding hosts list.

**Comment by flobeier** [comment]
@mkuron I don't want spam checks at all for this subnet and I selected that the spam filter should be inactive for it. Does "inactive" just mean that mails aren't rejected but still flagged?

**Comment by mkuron** [comment]
You've done everything right then. Please post the rspamd log from the time the message was flagged but shouldn't have been. `docker-compose logs rspamd-mailcow`.

**Comment by andryyy** [comment]
Yes, the logs would be of interest. 👍 

@mkuron pushed a fix for Redis symbols in Rspamd 2-3 days ago, perhaps you have not updated mailcow since then?

**Comment by flobeier** [comment]
The timestamp of the flagged mail in the Rspamd web ui is `27.5.2018, 23:46:11`

Here is the rspamd log:

> rspamd-mailcow_1     | 2018-05-27 23:45:34 #19(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:35 #21(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:35 #21(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:37 #22(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:37 #22(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:38 #24(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:38 #24(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:38 #20(controller) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:38 #20(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:39 #18(rspamd_proxy) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:39 #18(rspamd_proxy) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:45:40 #23(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:45:40 #23(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:46:02 #19(controller) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:46:02 #19(controller) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:46:31 #19(controller) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:46:31 #19(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:00 #19(controller) <rznbhc>; map; http_map_finish: http://nginx:8081/forwardinghosts.php([fd4d:6169:6c63:6f77::4]:8081): read map data 64 bytes, next check at Sun, 27 May 2018 23:47:30 GMT
> rspamd-mailcow_1     | 2018-05-27 23:47:00 #19(controller) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:00 #21(normal) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:00 #21(normal) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:01 #20(controller) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:01 #20(controller) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #22(normal) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #22(normal) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #24(normal) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #24(normal) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #18(rspamd_proxy) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:02 #18(rspamd_proxy) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:03 #23(normal) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:03 #23(normal) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #19(controller) <oxhd99>; map; http_map_finish: http://nginx:8081/settings.php([fd4d:6169:6c63:6f77::4]:8081): read map data 448 bytes, next check at Sun, 27 May 2018 23:47:44 GMT
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #19(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #18(rspamd_proxy) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #18(rspamd_proxy) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #20(controller) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #20(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #24(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:14 #24(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:16 #22(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:16 #22(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:16 #21(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:16 #21(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:19 #23(normal) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:19 #23(normal) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:47:44 #19(controller) <rznbhc>; map; rspamd_map_read_cached: http://nginx:8081/forwardinghosts.php: read map data cached 64 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:44 #19(controller) <rznbhc>; map; rspamd_radix_fin: read radix trie of 2 elements: ents=2 tbm=1 lc=2 mem=1k free=16 waste=0
> rspamd-mailcow_1     | 2018-05-27 23:47:58 #19(controller) <oxhd99>; map; rspamd_map_read_cached: http://nginx:8081/settings.php: read map data cached 448 bytes
> rspamd-mailcow_1     | 2018-05-27 23:47:58 #19(controller) <a1gq9u>; lua; settings.lua:610: loaded 2 elements of settings
> rspamd-mailcow_1     | 2018-05-27 23:48:22 #19(controller) <rznbhc>; map; http_map_finish: http://nginx:8081/forwardinghosts.php(172.22.1.4:8081): read map data 64 bytes, next check at Sun, 27 May 2018 23:48:52 GMT

@andryyy Right, I didn't update mailcow since then. I'll do that now. Will the update fix this error?

**Comment by andryyy** [comment]
The time stamps are UTC, you will need to check according to your timezone. :) Or just grep the sender.

I _think_ it will fix that, yes.

**Comment by flobeier** [comment]
@andryyy I just updated mailcow so the logs are gone :( I'll see if it happens again.

**Comment by flobeier** [comment]
@andryyy now the mails from the IPv6 range I added have internal IP adresses in the log files and thus are still being flagged. This was not the case before the recent update.
Example:

> Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)

**Comment by mkuron** [comment]
If internal IPs show up, then the _ipv6nat_ container isn‘t running properly. Please take Mailcow down (`docker-compose down`), reboot the host machine and bring it up again (`docker-compose up -d`). If the issue persists, we need logs (`docker-compose logs ipv6nat`) and firewall information (`ip6tables --list`).

**Comment by flobeier** [comment]
@mkuron @andryyy thanks for your help, now everything is working as it should! :) The rspamd log now displays `KEEP_SPAM (0)` for hosts from the forwarding host IPv6 range I added.
