### ISSUE TITLE
mails in trash folder are automatically deleted after 7 days

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#1433]
Hi all,

see title. Is it possible to configure this? I couldn't find anything related to this within mailcow, and my mail clients are not configured to delete anything. I need to increase that interval to at least 3 months or so, maybe disable completely.

Thanks,

peter

**Comment by mkuron** [comment]
This feature does not currently exist in Mailcow. An implementation was proposed in #1383 but reverted.

Most likely, you have automatic deletion configured in one of your email clients, e.g. Thunderbird.

**Comment by pschiffe** [comment]
@mkuron this is happening for multiple mailboxes with different clients and it started just recently after the mailcow update..

**Comment by mkuron** [comment]
Are you on the latest version?

**Comment by pschiffe** [comment]
master branch from May 19., commit 70025990739184718cf1e73c14b351a6ec4ae86e
My fork: https://github.com/pschiffe/mailcow-dockerized

**Comment by pschiffe** [comment]
Since the last update I see logs like this:
```
dovecot-mailcow_1    | May 23 12:46:39 hostname dovecot: imap(some@mailbox)<11088><AyDpP91sbKGsFgH4>: Logged out in=221 out=30927 deleted=473 expunged=473 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```
Before the update, all logs like this have only `expunged=0`, so it started with mailcow update, and it seems that the mail client is not the reason b/c it's the same for multiple mailboxes with different mail clients. Now, for some mailboxes I see also:
```
nginx-mailcow_1      | someip - - [23/May/2018:12:46:11 +0200] "POST /SOGo/so/some@mailbox/Mail/0/folderINBOX/expunge HTTP/2.0" 200 58 "https://hostname/SOGo/so/some@mailbox/Mail/view" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
...
sogo-mailcow_1       | May 23 12:46:11 ccec35332334 sogod [43]: someip "POST /SOGo/so/some@mailbox/Mail/0/folderINBOX/expunge HTTP/1.0" 200 58/0 0.291 - - 0
```
But not for all; also most of the mailboxes use only desktop/mobile clients, not sogo.

**Comment by mkuron** [comment]
Note that "expunge" in IMAP terminology means to delete messages that have been marked for deletion. When you delete a message in your email client, it is only marked for deletion and deleted upon expunge (usually at log out). 

Since your logs are showing delete and expunge upon logout, it is definitely the client that marked the messages for deletion.

**Comment by pschiffe** [comment]
Yeah, I know how does it look, and I can't find more information, but it makes no sense. After the update, all mail clients delete in one day 1000+ emails from trash. I'm talking here about ~20 mailboxes used by ~10 different people :-(

**Comment by pschiffe** [comment]
@mkuron sorry, I'm still digging into this. Before the update I was on Dovecot 2.2 on mailcow version from Mar 19, commit https://github.com/pschiffe/mailcow-dockerized/commit/32c0b4a2931e6512a19d16d6d4b4fb100bab309b . This deletion from trash started about a week ago, when I've updated to that version mentioned above. Yesterday evening I've updated again to the current latest version of mailcow, the deletion from trash is still happening.

I've enabled `mail_debug` in dovecot to see more information about what's going on, and during the imap sessions when `deleted= expunged=` at the log out is not 0, I see this log message repeat exactly the number of times, the `deleted= expunged=` equals to at the log out of the session:
```
May 29 08:02:17 hostname dovecot: imap(some@mail)<7725><xxb6+VFtL+JT0CE8>: Debug: imapsieve: mailbox Trash: FLAG event (changed flags: \Deleted)
```

**Comment by pschiffe** [comment]
I have verified that the Thunderbird for this particular mailbox have set to move the email to trash on delete, and doesn't have checked to expunge or to empty trash on logout.

@mkuron @andryyy any idea what the log message from above could mean? `imapsieve: mailbox Trash: FLAG event (changed flags: \Deleted)` I'm not able to find any sieve config responsible for this. Sieve tables in db are empty, and there is no additional system wide sieve config.

**Comment by andryyy** [comment]
Could you please post your dovecot.conf?

**Comment by andryyy** [comment]
You didn't pull this PR? https://github.com/mailcow/mailcow-dockerized/pull/1383

**Comment by pschiffe** [comment]
@andryyy no, I use only master branch of this repo. My dovecot.conf is here https://github.com/pschiffe/mailcow-dockerized/tree/master/data/conf/dovecot . I have enabled old_stats plugins + I have `default_process_limit = 400` in `extra.conf`.

**Comment by marcquark** [comment]
Hey there,

i found this issue on google because i had the same problem and wanted to know what's going on. Turns out it was my iPhone which removed deleted messages older than 7 days. Maybe this came in with an update some time ago? I only got the phone a few days ago and it was the default setting on iOS12.
Anyway, under account settings -> advanced you can change that behaviour. Guess i have to restore from a backup now...
