### ISSUE TITLE
SOGo tasks not working - saves but dialog stays open and no tasks added

### ISSUE THREAD

**Issue by asifbacchus** [mailcow/mailcow-dockerized#1435]
I haven't found anything related to this in the open or closed issues so I'm looking for some help.

I can create a task and then save it.  The dialog stays open.  If I click elsewhere to dismiss it, then my task does not show up.  This is the same if I convert an email to a task.  I don't get any errors.

Is this a known bug? Is there something I need to change in my configuration?  Is this a setting in the giant SOGo configuration file?  I don't even know where to begin looking so ANY guidance is appreciated.  EVERYTHING else works amazingly!!! 

Let me know if I need to post any configs or anything.  Thanks in advance for any guidance :-)

(if this is posted in the wrong place, let me know and I'll post elsewhere, sorry, I'm new and I'm not sure)

**Comment by andryyy** [comment]
Huh, that's strange. It doesn't post any request when clicking on "Save". I will try with the newest nightly, could you please create a bug report @ SOGo if that doesn't fix it?

**Comment by asifbacchus** [comment]
I actually found this bug-report for SOGo suggesting that the problem is corrected in version 4.0.1 and currently mailcow seems to use 4.0.0. (https://sogo.nu/bugs/view.php?id=4456)
Is there a (simple) way to upgrade SOGo?  Or do I have to redo my entire mailcow setup?
Thanks for the quick response!!!

**Comment by mkuron** [comment]
4.0.1 is not released yet. However, Mailcow uses nightly builds of SOGo (currently, version 4.0.0.201804230252) . The bug was fixed four days later, so I guess @andryyy just needs to rebuild the image on Docker Hub to get this bugfix.

**Comment by andryyy** [comment]
Will be fixed in a few minutes. 👍 

Closed with commit below. I can confirm it is working now.
