### ISSUE TITLE
"Also allowed to send as user:" problem

### ISSUE THREAD

**Issue by JustAB0x** [mailcow/mailcow-dockerized#1437]
I gave a user permission to send as another user but in sogo the user couldn't select the email that i gave permission for. With aliases it works fine but sadly you can't change the displayed name there.

**Comment by andryyy** [comment]
You need to delegate them in SOGo:

![image](https://user-images.githubusercontent.com/2972950/40621319-9d98db32-629c-11e8-9028-0ffa75706d58.png)

![image](https://user-images.githubusercontent.com/2972950/40621330-a6fc9c86-629c-11e8-9825-0b03ad8c1546.png)

![image](https://user-images.githubusercontent.com/2972950/40621351-b9937590-629c-11e8-986a-4aa8775422b9.png)

Why is that? => We cannot make other mailboxes appear in the dropdown "From" field as they are mailboxes. It works for aliases, but it breaks SOGo when we list mailboxes here.

**Comment by JustAB0x** [comment]
Would be possible to implement custom "Full Names" for aliases?

**Comment by andryyy** [comment]
I'd need to check if it works. I'm not sure.

**Comment by JustAB0x** [comment]
Would be really great :)
