### ISSUE TITLE
SOGo not showing emails

### ISSUE THREAD

**Issue by D3SOX** [mailcow/mailcow-dockerized#1438]
My emails are not showing any more
[https://i.imgur.com/oqAsywL.png](https://i.imgur.com/oqAsywL.png)

On the right side it says no mailbox selected.

**Comment by andryyy** [comment]
You need to provide ANY information. :-(

When? After update? Dovecot logs? SOGo logs?

Dovecot may be busy creating DH params.

**Comment by D3SOX** [comment]
Suddenly it was like this. I didn't do any update. Where can i grab the logs from?

**Comment by mitchellurgero** [comment]
Logs will be in the docker container for Dovecot, but I recommend rebooting the server to see if that resolves the issue. (Especially if only SOGO is affected) is it like this with mobile clients and such?

**Comment by D3SOX** [comment]
Logs:
Postfix: https://i.imgur.com/OR1o0Hz.png
Dovecot: https://i.imgur.com/REpwTxN.png
SOGo: https://i.imgur.com/vCgX1yq.png

**Comment by andryyy** [comment]
I don’t think Dovecot is running (for a while now). :-)

**Comment by D3SOX** [comment]
https://i.imgur.com/nQ0Jzn0.png
Does this help you resolving my issue?

**Comment by andryyy** [comment]
There is a Dovecot instance running on your local host, which blocks ports for Docker.

Run inside the mailcow-dockerized folder `docker-compose down`, run `systemctl stop dovecot` followed by `systemctl disable dovecot` and restart the stack with `docker-compose up -d`

**Comment by D3SOX** [comment]
I entered all commands and this happened: https://i.imgur.com/GfFnhs2.png

**Comment by andryyy** [comment]
Do the same for Postfix.
There is a mail system running on this server. You cannot bind the ports multiple times.

**Comment by D3SOX** [comment]
haha i actually got this idea right now and did it before you wrote it :D thanks working now. i will check if sogo is working

**Comment by D3SOX** [comment]
Working! THANKS <3

**Comment by andryyy** [comment]
Nice :-)
