### ISSUE TITLE
Sender address rejected: not logged in

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#144]
sending email using my provider smtp to a mc-d domain i get this erro:

`SMTP error from remote mail server after RCPT TO: .... Sender address rejected: not logged in`

receiving mail for 2 different domains on mc-d and sending via a third party smtp server from one domain to the other causes the same issue. Also with backup mx domains. 

I don't know if that's the correct solution, but i tried to disable sender verification (any better solution when i can even set an spf record for a domain because i can't list all outgoing server?) but that also did not work, i guess because of a filename error in docs (https://github.com/andryyy/mailcow-dockerized/issues/143).

any suggestion?

**Comment by andryyy** [comment]
Hi,
The correct command is `docker-compose exec postfix-mailcow postmap /opt/postfix/conf/check_sender_access` - I will push the fix now.

**Comment by marrco** [comment]
thanks for the quick fix, but it looks like that's not the correct solution for me, or i'm not able to restart the docker containers:

```
postfix-mailcow_1    | Mar 22 14:51:47 mx postfix/smtpd[121]: Anonymous TLS connection established from [third-part-server-munged]: TLSv1.2 with cipher DHE-RSA-AES128-SHA (128/128 bits)
postfix-mailcow_1    | Mar 22 14:51:47 mx postfix/smtpd[121]: NOQUEUE: reject: RCPT from [third-part-server-munged]: 553 5.7.1 <different-user@domain-on-mc.d> Sender address rejected: not logged in; from=<different-user@domain-on-mc.d> to=<marco@domain-on-mc.d> proto=ESMTP helo=<third-part-server-helo>
```
i see no errors : 

```
root@myserver3:~/mailcow-dockerized# cat data/conf/postfix/check_sender_access
user-to-allow-everything@example.com OK

```

```
smtpd_sender_login_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf
smtpd_sender_restrictions = check_sasl_access hash:/opt/postfix/conf/check_sender_access, reject_authenticated_sender_login_mismatch, permit_mynetworks, reject_sender_login_mismatch, permit_sasl_authenticated, reject_unlisted_sender, reject_unknown_sender_domain
smtpd_soft_error_limit = 3
```
i also tried not to put a "," after the new prepended check, still not working.

```
root@myserver3:~/mailcow-dockerized# docker-compose exec postfix-mailcow postmap /opt/postfix/conf/check_sender_access
root@myserver3:~/mailcow-dockerized#
```

so no errors, everything seem to be correct, then to restart the container i typed: 

```
root@myserver3:~/mailcow-dockerized# docker-compose restart postfix-mailcow
Restarting mailcowdockerized_postfix-mailcow_1 ... done
root@myserver3:~/mailcow-dockerized#
```

so i really i'm not sure what i have to do to tell mc-d to use this new config. Should i rebuild something?

Any suggestion here?

**Comment by andryyy** [comment]
Can you add the map to proxy read maps or remove the proxy: part? Or add the logs?

**Comment by marrco** [comment]
Thanks for your suggestions. I removed the proxy: part so now i have:

```
smtpd_sender_login_maps = 
smtpd_sender_restrictions = check_sasl_access hash:/opt/postfix/conf/check_sender_access, reject_authenticated_sender_login_mismatch, permit_mynetworks, reject_sender_login_mismatch, permit_sasl_authenticated, reject_unlisted_sender, reject_unknown_sender_domain
```

then i `docker-compose restart postfix-mailcow` and everything works fine.

I can now even send email to myself using a third part smtp server. And that's quite important for a backup mx.

**Comment by andryyy** [comment]
Oh, I wrote this on the go from my smartphone. You shouldn't remove the login maps, but you can to totally disable the sender checks.

`check_sasl_access` is the proper way to archive it. But that doesn't matter anyway, because you are not logging in: `not logged in`. 

Are you using the first setup as backup mx to relay to your second server? Then just add the backup mx to mynetworks of  the primary mx. Or leave it as it is. :P

**Comment by marrco** [comment]
I tried to readd the 
`smtpd_sender_login_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf`
and again that stopped me from mailing myself via a third part smtp. 

Not an issue for me, but 
https://andryyy.github.io/mailcow-dockerized/u_and_e/#disable-sender-addresses-verification
it's not enough to disable sender check.

**Comment by andryyy** [comment]
It depends on what exactly you want to archive...

Unauthenticated? Authenticated? Same domain? Domain which is not added to mailcow?

It really depends. The docs describe how to allow an authenticated user (!) to send from any address, no matter if added to mailcow or not.
