### ISSUE TITLE
Dovecot critial error

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#1440]
Hello, not sure if this is a problem but I have this error in dovecot.  Is this something that needs attention? 
Client is using 2 computers and bot have outlook 2010 with caldav connector installed.

5/28/2018, 8:41:17 AM | crit | lmtp(****@forestproperties.com)<540><SEgyI+34C1scAgAA4LTwUA>: Panic: file ostream.c: line 394 (o_stream_send_istream): assertion failed: (!_outstream->finished)
5/28/2018, 8:41:17 AM | crit | lmtp(****@forestproperties.com)<540><SEgyI+34C1scAgAA4LTwUA>: Fatal: master: service(lmtp): child 540 killed with signal 6 (core not dumped - https://dovecot.org/bugreport.html#coredumps - set /proc/sys/fs/suid_dumpable to 2)
5/28/2018, 8:41:17 AM | err | lmtp(****@forestproperties.com)<540><SEgyI+34C1scAgAA4LTwUA>: Error: Raw backtrace: /usr/local/lib/dovecot/libdovecot.so.0(+0xc9bf1) [0x7f9675c42bf1] -> /usr/local/lib/dovecot/libdovecot.so.0(+0xc9cbd) [0x7f9675c42cbd] -> /usr/local/lib/dovecot/libdovecot.so.0(i_fatal+0) [0x7f9675bb2391] -> /usr/local/lib/dovecot/libdovecot.so.0(o_stream_send_istream+0x228) [0x7f9675c69928] -> /usr/local/lib/dovecot/libdovecot.so.0(smtp_client_command_send_more+0x1a7) [0x7f9675bbbf07] -> /usr/local/lib/dovecot/libdovecot.so.0(+0x488c6) [0x7f9675bc18c6] -> /usr/local/lib/dovecot/libdovecot.so.0(+0xf26e0) [0x7f9675c6b6e0] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_call_io+0x69) [0x7f9675c5aa49] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_handler_run_internal+0x109) [0x7f9675c5c339] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_handler_run+0x52) [0x7f9675c5ab52] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_run+0x38) [0x7f9675c5ad68] -> /usr/local/lib/dovecot/libdovecot.so.0(smtp_submit_run+0xba) [0x7f9675bccc9a] -> /usr/local/lib/dovecot/lib90_sieve_plugin.so(+0x2a24) [0x7f967380aa24] -> /usr/local/lib/dovecot/libdovecot-sieve.so.0(+0x501da) [0x7f96735a21da] -> /usr/local/lib/dovecot/libdovecot-sieve.so.0(+0x40581) [0x7f9673592581] -> /usr/local/lib/dovecot/libdovecot-sieve.so.0(sieve_result_execute+0x217) [0x7f9673593a97] -> /usr/local/lib/dovecot/libdovecot-sieve.so.0(+0x52b6e) [0x7f96735a4b6e] -> /usr/local/lib/dovecot/libdovecot-sieve.so.0(sieve_multiscript_run+0xa6) [0x7f96735a59c6] -> /usr/local/lib/dovecot/lib90_sieve_plugin.so(+0x3b66) [0x7f967380bb66] -> /usr/local/lib/dovecot/libdovecot-lda.so.0(mail_deliver+0xf0) [0x7f9676249d50] -> dovecot/lmtp(lmtp_local_data+0x4f1) [0x55d168368fe1] -> dovecot/lmtp(cmd_data_continue+0x233) [0x55d168367cf3] -> /usr/local/lib/dovecot/libdovecot.so.0(+0x4b940) [0x7f9675bc4940] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_call_io+0x69) [0x7f9675c5aa49] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_handler_run_internal+0x109) [0x7f9675c5c339] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_handler_run+0x52) [0x7f9675c5ab52] -> /usr/local/lib/dovecot/libdovecot.so.0(io_loop_run+0x38) [0x7f9675c5ad68] -> /usr/local/lib/dovecot/libdovecot.so.0(master_service_run+0x13) [0x7f9675bd5c83]

Thank you in advance for looking.

**Comment by andryyy** [comment]
Hi, can you please post the full context? :-) This happened once?

**Comment by kilo42L** [comment]
Thanks andryyy but It seems it was a one time deal I dont see the error anymore and not sure how to get the logs from that far back.
I do have these errors regularly from the same user


_

> warning | lmtp(****@forestproperties.com)<27974><aDCLE+q2DltGbQAA4LTwUA>: Warning: smtp-client: conn postfix:588 [0]: Received invalid EHLO response line: Unexpected character in EHLO keyword

_

**Comment by andryyy** [comment]
Don't know. This line doesn't help. I would need the full context. When does it happen, which client etc.

**Comment by kilo42L** [comment]
How would I get the full context?  Maybe I can figure it out and post back to help others, Im just not sure how to get that info.

**Comment by andryyy** [comment]
You need to check when this happened. And try to reproduce it.

**Comment by kilo42L** [comment]
Thank you, Is there a way to search the logs on the containers.  I am not savvy with docker :o 
I read on here from a post that I can do "docker-compose logs -f --tail=200 rspamd-mailcow" for instance but how far can I go back? do the logs rotate, etc. 
I would like to do a docker-compose logs (mainlogfile) rspamd-mailcow | grep "my problem"  but im afraid I might break something

**Comment by andryyy** [comment]
Hm, they are by default stored in /var/lib/docker/containers/ID/ID-json.log and pretty much unlimited.

I cannot guarantee it, but we can both check this on your server tomorrow if you want to.

**Comment by kilo42L** [comment]
Sure, I really appreciate your time.  I know your staying busy on here and I will do what I can to help you and this project.  
Thanks

**Comment by andryyy** [comment]
That's very nice, thank you! 👍

**Comment by kilo42L** [comment]
Ok, I got the critical error today.  I did a search and found the same error on github (dovecot/core) that was committed 2 weeks ago.
https://github.com/dovecot/core/commit/ede3c3be7fc01e51c62f67071b0c73bf0087b7ad

**Comment by andryyy** [comment]
Cool, thanks for checking that!
Let's wait for 2.3.2 then. 👍
