### ISSUE TITLE
ClamAV

### ISSUE THREAD

**Issue by JustAB0x** [mailcow/mailcow-dockerized#1442]
Hello,
i tested the clamav component today and noticed that emails go into the spam box and rspamd sets no virus flag but if you try to download the attachment it is deleted.

**Comment by andryyy** [comment]
Eicar?

**Comment by JustAB0x** [comment]
Did one test and it was flagged with the eicar tag. The behavior I
described earlier is with a real virus.

André Peters <notifications@github.com> schrieb am Mi., 30. Mai 2018, 10:07:

**Comment by andryyy** [comment]
Please start `docker-compose logs -f --tail=200 rspamd-mailcow clamd-mailcow` and try it again. Upload the logs to paste.ee etc. after that. :-)

**Comment by JustAB0x** [comment]
![image](https://user-images.githubusercontent.com/19808218/40719178-eb6e3bb4-6412-11e8-9901-06f0b6af07db.png)

**Comment by andryyy** [comment]
`docker-compose logs -f --tail=200 rspamd-mailcow clamd-mailcow`

**Comment by JustAB0x** [comment]
this is going for over an hour. Is it supposed to last that long?

**Comment by andryyy** [comment]
?

That's how you grab the logs. You should only start the logs command, test clamd and stop the logs command.

Furthermore: what does that mean? => "if you try to download the attachment it is deleted"?

**Comment by JustAB0x** [comment]
Welp. 
https://paste.ee/p/UoRfJ
test file that was attached: https://www.virustotal.com/#/file/f510df34b0ee00116235cc69152eaafac71e925b159a3791753b4853b40bd55e/detection

**Comment by andryyy** [comment]
And where is clamd-mailcows log?

And please see the question above. I cannot help you, when you cut some logs or information is missing. :-(

**Comment by JustAB0x** [comment]
https://paste.ee/p/JtVw4

**Comment by JustAB0x** [comment]
Found the issue. Because i didn't put an extension to the file clam passed it thru. With an extension added to the file it does detect it. Kinda weird tho since normally clam does detect files without an extension.

**Comment by andryyy** [comment]
Hm, that's strange. @vstakhov any idea?

**Comment by Braintelligence** [comment]
@Fytcher Is it possible for you to provide the file in question or would that be problematic per data privacy reasons?

**Comment by JustAB0x** [comment]
Here the log with an extension applied to the file:
https://paste.ee/p/brdmO

**Comment by Braintelligence** [comment]
Could it be that ClamAV works via a kind of "point" system, just like Rspamd, and awards more points if a file extension is given that is binary/runnable?

This would make some sense, because you can't run a trojan-ridden file with a single click, if the extension is missing and doesn't get added and thus the danger is a bit less, wouldn't it?

**Comment by JustAB0x** [comment]
Hm rather strange. Because in the past my ClamAV running on another server picked such test files up because of the sig.
@Braintelligence You mean the virus file with ur previous question?

**Comment by JustAB0x** [comment]
File used for the test (now with extension):
https://void.cat/#723fe0bbbda827d55454de35535e8b46fa5fdb1e

The file is zipped and password protected with the password "infected". 
It is an Trojan dropper in html/vbscript, so for safety reasons don't open it in ur browser.

**Comment by JustAB0x** [comment]
Just verified on my other server that clamav does detect it as a virus without an extension.
https://paste.ee/p/mcEi2

**Comment by andryyy** [comment]
You should have scanned the whole mail msg in VirusTotal, not just the file itself.

Clamd detects no virus when it is mime encoded. It just seems to suck at mime decoding.

Here is the scan report for the mail msg: https://www.virustotal.com/de/file/16062503554b7ce8a8c5b50c359c8b9c2792de9ecd729869e2258d50071a260d/analysis/

**Comment by JustAB0x** [comment]
Thanks for the help but i'm pretty disappointed in ClamAV now :/

**Comment by vstakhov** [comment]
Do you have a full message sample by the way?
