### ISSUE TITLE
Backup- / Restore-Script - How to restore a single folder or a single mail 

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1443]
Good evening,

from time to time there is an occurence of own stupidity ...
I deleted a folder with some important mails.
Looking through the restore-script there is only a complete restore of all mails.
How can i restore a single mail or a single folder from this backup.

Any help is appreciated :-)

**Comment by kilo42L** [comment]
Mailstore archiving software is what I have been using for years.  Its fantastic and has a free version for personal use but it runs on windows only.  For Linux offlineimap looks nice but I have never tried it.  

You should always backup your emails on another device.

**Comment by ghost** [comment]
I know that you should backup emails on another device or some kind of backup software.
This was not the question.
My thought was that if there is a backup routine you should have the possibility to restore a whole folder or a single email out of it.
So this case isn't solved yet ...

**Comment by tkorves** [comment]
Hey @kotekle,

as the shipped backup script ist just very basic, you're welcome to either sponsor or contribute a more advanced script. If both suggestions aren't what you've searched for, I'm very sorry - but if this isn't sufficient, you'd use a archive system to store your mails for stupidity reasons ...

All the best, Tim
