### ISSUE TITLE
tagged email is not processed when from forwarding host

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#1445]
Tagged email (me+Facebook@example.org) is not processed according to the settings (put to subfolder) if it came from forwarding host. Such email doesn't have the `X-Moo-Tag: YES` header. Spam filter is disabled for that forwarding host. Is this by design or a bug? I have the latest mailcow version (from yesterday or so). Emails not from forwarding hosts are processed (put to subfolder) correctly.

**Comment by mkuron** [comment]
The tag is added by the spam filter. If you disable the spam filter, it isn’t going to get added. I know this is not very intuitive... feel free to submit a pull request that clarifies this in the description text.

**Comment by pschiffe** [comment]
I see, thanks @mkuron
