### ISSUE TITLE
Run mailcow from external disk not working

### ISSUE THREAD

**Issue by alaarihan** [mailcow/mailcow-dockerized#1446]
I was running mailcow without problems until my VPS main disk ran out of space so I added an additional disk and mount it, I tried to move docker files to the new disk but mailcow return 502 server error when I try to access Mailcow UI,

I tried with fresh installation I had the same problem!

**Comment by PhoenixPeca** [comment]
Hi @alaarihan 
You may want to take a look at #1152

**Comment by andryyy** [comment]
This also needs additional infos about what exactly you did, the filesystem and in the end some logs.

**Comment by alaarihan** [comment]
@PhoenixPeca I already did that, it's not working, when I enter `docker-compose up -d` it run all containers no problem but when I try to access to UI, it doesn't work (503 server error) i think it's nginx problem.

**Comment by alaarihan** [comment]
@andryyy I did the same steps in #1152 and tried another way too, docker-compose run all containers without problems but when I try to access the UI it doesn't work, how can I sent you logs?

**Comment by andryyy** [comment]
I need information about what exactly you did. Permissions may be wrong. Which file system? 

You could purge all containers and volumes, restart Docker and run up -d again.

**Comment by alaarihan** [comment]
I mounted the disk like this:
mkfs.ext4 /dev/sdb1
mkdir /mnt/sdb1
mount /dev/sdb1 /mnt/sdb1/
admin@serveur-1:~$ vim /etc/fstab
```

/etc/fstab: static file system information.

# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point> <type> <options> <dump> <pass>
UUID=51ba13e7-398b-45f3-b5f3-fdfbe556f62c / ext4 defaults 0 0
UUID=2e4a9012-bf0e-41ef-bf9a-fbf350803ac5 /mnt/sdb1 ext4 nofail 0 0

```
Then I stopped docker service
and did what you wrote here:
https://github.com/mailcow/mailcow-dockerized/issues/1152#issuecomment-372146780
after that I ran docker service and checked that it use the new mounted disk for docker files
and tried with fresh mailcow installation but I faced the same problem.

**Comment by andryyy** [comment]
You could try to stop docker.service, run `mv /var/lib/docker/volumes /var/lib/docker/volumes_` change /etc/fstab to mount sdb1 to /var/lib/docker/volumes, `mkdir /var/lib/docker/volumes` followed by `mount -a`.

**Comment by alaarihan** [comment]
This worked for me thanks but I prefer to have all docker files in my other disk not just volumes, is that possible?

**Comment by andryyy** [comment]
Hm, you can mount it as /var/lib/docker I guess :-)

**Comment by alaarihan** [comment]
OK, I will try that, thank you for your help.
