### ISSUE TITLE
Postfix behaves strange ...

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1447]
Good evening,

looking in postfix logs i see this:

postfix-mailcow_1    | 2018-05-30T20:34:42.075638677Z 2018-05-30 22:34:42,075 WARN received SIGTERM indicating exit request
postfix-mailcow_1    | 2018-05-30T20:34:42.075843539Z 2018-05-30 22:34:42,075 INFO waiting for postfix, syslog-ng to die
postfix-mailcow_1    | 2018-05-30T20:34:42.075863017Z May 30 22:34:42 mx syslog-ng[10]: syslog-ng shutting down; version='3.8.1'
postfix-mailcow_1    | 2018-05-30T20:34:42.180217637Z 2018-05-30 22:34:42,179 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2018-05-30T20:34:42.213070851Z 2018-05-30 22:34:42,212 INFO reaped unknown pid 328
postfix-mailcow_1    | 2018-05-30T20:34:42.213527738Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 330
postfix-mailcow_1    | 2018-05-30T20:34:42.213542096Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1009
postfix-mailcow_1    | 2018-05-30T20:34:42.213547917Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 335
postfix-mailcow_1    | 2018-05-30T20:34:42.213553021Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1017
postfix-mailcow_1    | 2018-05-30T20:34:42.213557595Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1008
postfix-mailcow_1    | 2018-05-30T20:34:42.213562052Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1018
postfix-mailcow_1    | 2018-05-30T20:34:42.213566650Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 331
postfix-mailcow_1    | 2018-05-30T20:34:42.213841749Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 983
postfix-mailcow_1    | 2018-05-30T20:34:42.213855494Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1015
postfix-mailcow_1    | 2018-05-30T20:34:42.213859767Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1020
postfix-mailcow_1    | 2018-05-30T20:34:42.213870887Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1014
postfix-mailcow_1    | 2018-05-30T20:34:42.213873948Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1036
postfix-mailcow_1    | 2018-05-30T20:34:42.213876578Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1079
postfix-mailcow_1    | 2018-05-30T20:34:42.213879155Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1081
postfix-mailcow_1    | 2018-05-30T20:34:42.213881759Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1174
postfix-mailcow_1    | 2018-05-30T20:34:42.213884305Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1189
postfix-mailcow_1    | 2018-05-30T20:34:42.213886920Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1210
postfix-mailcow_1    | 2018-05-30T20:34:42.213994172Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 977
postfix-mailcow_1    | 2018-05-30T20:34:42.214006381Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 866
postfix-mailcow_1    | 2018-05-30T20:34:42.214016370Z 2018-05-30 22:34:42,213 INFO reaped unknown pid 1254
postfix-mailcow_1    | 2018-05-30T20:34:42.214029740Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1294
postfix-mailcow_1    | 2018-05-30T20:34:42.214065773Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1297
postfix-mailcow_1    | 2018-05-30T20:34:42.214092282Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1298
postfix-mailcow_1    | 2018-05-30T20:34:42.214164476Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1312
postfix-mailcow_1    | 2018-05-30T20:34:42.214175805Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1322
postfix-mailcow_1    | 2018-05-30T20:34:42.214179393Z 2018-05-30 22:34:42,214 INFO reaped unknown pid 1010
postfix-mailcow_1    | 2018-05-30T20:34:42.217076189Z 2018-05-30 22:34:42,216 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2018-05-30T20:34:43.601181966Z 2018-05-30 22:34:43,601 CRIT Set uid to user 0
postfix-mailcow_1    | 2018-05-30T20:34:43.602515638Z 2018-05-30 22:34:43,602 INFO supervisord started with pid 1
postfix-mailcow_1    | 2018-05-30T20:34:44.605402531Z 2018-05-30 22:34:44,604 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2018-05-30T20:34:44.608107404Z 2018-05-30 22:34:44,607 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | 2018-05-30T20:34:44.625507458Z May 30 22:34:44 mx syslog-ng[10]: syslog-ng starting up; version='3.8.1'
postfix-mailcow_1    | 2018-05-30T20:34:44.908591987Z May 30 22:34:44 mx postfix[240]: Postfix is running with backwards-compatible default settings
postfix-mailcow_1    | 2018-05-30T20:34:44.908610731Z May 30 22:34:44 mx postfix[240]: See http://www.postfix.org/COMPATIBILITY_README.html for details
postfix-mailcow_1    | 2018-05-30T20:34:44.908615184Z May 30 22:34:44 mx postfix[240]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
postfix-mailcow_1    | 2018-05-30T20:34:45.038908880Z May 30 22:34:45 mx postfix/postfix-script[326]: starting the Postfix mail system

What am i doing wrong?

**Comment by andryyy** [comment]
Did watchdog restart postfix-mailcow?

**Comment by ghost** [comment]
Hi andryyy,

no, watchdog did not restart postfix-mailcow.
I don't see anything like this in watchdog logs:

watchdog-mailcow_1   | Wed May 30 20:34:02 GMT 2018 Dovecot health level: 100% (24/24), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:08 GMT 2018 SOGo health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:13 GMT 2018 Nginx health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:19 GMT 2018 PHP-FPM health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:21 GMT 2018 Postfix health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:23 GMT 2018 Rspamd health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:25 GMT 2018 MySQL/MariaDB health level: 100% (12/12), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:32 GMT 2018 SOGo health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:35 GMT 2018 Dovecot health level: 100% (24/24), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:37 GMT 2018 Rspamd health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:39 GMT 2018 Postfix health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:45 GMT 2018 PHP-FPM health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:46 GMT 2018 Nginx health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:47 GMT 2018 Dovecot health level: 100% (24/24), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:52 GMT 2018 MySQL/MariaDB health level: 100% (12/12), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:34:55 GMT 2018 Postfix health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:35:03 GMT 2018 MySQL/MariaDB health level: 100% (12/12), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:35:06 GMT 2018 Postfix health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed May 30 20:35:07 GMT 2018 SOGo health level: 100% (20/20), health tren

**Comment by andryyy** [comment]
And what about syslog? Did it log something useful?

Run out of RAM (no swap)?

**Comment by ghost** [comment]
In syslog i found:

May 30 22:34:42 mx dockerd[937]: time="2018-05-30T22:34:42+02:00" level=info msg="shim reaped" id=1bfb250a38ccd1d2539ddf801368114cc096f97eda3208f9971f28fa08b853$
May 30 22:34:42 mx dockerd[937]: time="2018-05-30T22:34:42.377682805+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/del$
May 30 22:34:42 mx kernel: [133796.316010] br-62ab9df5ef14: port 3(veth067f2e5) entered disabled state
May 30 22:34:42 mx kernel: [133796.316135] veth6a611c8: renamed from eth0
May 30 22:34:42 mx kernel: [133796.428084] br-62ab9df5ef14: port 3(veth067f2e5) entered disabled state
May 30 22:34:42 mx kernel: [133796.431739] device veth067f2e5 left promiscuous mode
May 30 22:34:42 mx kernel: [133796.431822] br-62ab9df5ef14: port 3(veth067f2e5) entered disabled state
May 30 22:34:42 mx kernel: [133796.566517] br-62ab9df5ef14: port 3(veth85a33d5) entered blocking state
May 30 22:34:42 mx kernel: [133796.566646] br-62ab9df5ef14: port 3(veth85a33d5) entered disabled state
May 30 22:34:42 mx kernel: [133796.566904] device veth85a33d5 entered promiscuous mode
May 30 22:34:42 mx kernel: [133796.567160] IPv6: ADDRCONF(NETDEV_UP): veth85a33d5: link is not ready
May 30 22:34:42 mx kernel: [133796.567286] br-62ab9df5ef14: port 3(veth85a33d5) entered blocking state
May 30 22:34:42 mx kernel: [133796.567405] br-62ab9df5ef14: port 3(veth85a33d5) entered forwarding state
May 30 22:34:42 mx systemd-udevd[13536]: Could not generate persistent MAC address for veth85a33d5: No such file or directory
May 30 22:34:42 mx systemd-udevd[13535]: Could not generate persistent MAC address for vethd59a741: No such file or directory
May 30 22:34:42 mx dockerd[937]: time="2018-05-30T22:34:42+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/1bfb250a38$
May 30 22:34:43 mx kernel: [133797.165508] eth0: renamed from vethd59a741
May 30 22:34:43 mx kernel: [133797.243650] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 30 22:34:43 mx kernel: [133797.245593] IPv6: ADDRCONF(NETDEV_CHANGE): veth85a33d5: link becomes ready
May 30 22:34:44 mx ntpd[4464]: Listen normally on 135 veth85a33d5 [fe80::346f:dfff:fe52:7658%425]:123
May 30 22:34:44 mx ntpd[4464]: Deleting interface #126 veth067f2e5, fe80::7cfd:a2ff:fe19:2d92%399#123, interface stats: received=0, sent=0, dropped=0, active_ti$

My system has about 64GB RAM and a swap partition is in use.

**Comment by andryyy** [comment]
I would need more logs from ~2 minutes before the kill event until ~ 22:35.

The process was sent a sigterm event. Are you sure you didn't restart the container at this time?

**Comment by ghost** [comment]
As a matter of fact i have to say that in this case the "fault" is in front of the computer,
I restarted containers and forgot about it ...
Sorry for stealing your time ... :-(
