### ISSUE TITLE
Anonymize Headers not working

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1448]
Good evening,

i followed the instructions [here](https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-anonym_headers/) for Anonymize Headers.

Unfortunately this isn't working for me.

data/conf/postfix/ looks like this:
drwxr-xr-x  3 root root  4096 Mai 30 22:01 .
drwxr-xr-x 11 root root  4096 Mai 29 00:57 ..
-rwxr-xr-x  1 root root   326 Mai 29 03:30 mailcow_anonymize_headers.pcre
-rw-r--r--  1 root root  6855 Mai 29 03:31 main.cf
-rw-r--r--  1 root root  4553 Mai 29 00:57 master.cf
-rw-r--r--  1 root root 16419 Mai 29 00:57 postscreen_access.cidr
-rw-r--r--  1 root root   190 Mai 29 00:57 smtp_dsn_filter
drwxr-xr-x  2 root root  4096 Mai 29 00:59 sql

In data/conf/postfix/main.cf this is my last line:

smtp_header_checks = pcre:/opt/postfix/conf/mailcow_anonymize_headers.pcre

I restarted postfix-mailcow but header are not anonymized ...

Best regards

**Comment by andryyy** [comment]
Depends on which headers you want to have removed.

Port 587/465 is used?

**Comment by ghost** [comment]
I want to remove IPv6-adresses in all headers.
As an example

Received: from XX.XX.XXX (unknown [IPv6:XXXX::XXXX])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	(Authenticated sender: XX@XX.XX)

... and yes Port 587/465 are in use

**Comment by andryyy** [comment]
Need the full Received header as clean paste to paste.ee or as code in markdown to check the regex.

Or just mail me to info@servercow.de

**Comment by andryyy** [comment]
It should be `(No client certificate requested)` that we added with a new Postfix option a while ago. The regex needs an update.

**Comment by ghost** [comment]
I see :-)
And i started thinking about me being an idiot.
So we have to wait for this update :-)

**Comment by andryyy** [comment]
```
/^\s*Received:.*Authenticated sender:(.+)/
    REPLACE Received: from localhost (localhost [127.0.0.1]) (Authenticated sender:$1
/^\s*User-Agent/        IGNORE
/^\s*X-Enigmail/        IGNORE
/^\s*X-Mailer/          IGNORE
/^\s*X-Originating-IP/  IGNORE
/^\s*X-Forward/         IGNORE
```

It may work like this. Can you try it?

**Comment by ghost** [comment]
I'll give it a try and will report back ASAP.

**Comment by ghost** [comment]
@andryyy 
This worked for me
You are outstanding 👍

**Comment by fabianhick** [comment]
The RegEx unfortunately doesn't work for me either...

My header:
```
Received: from [***.***.*.**] (myreversedomain.de [***.***.***.*])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	(Authenticated sender: user@example.org)
	by mail.example.org (Postcow) with ESMTPSA id *********
	for <john@example.org>; Fri,  8 Mar 2019 23:00:50 +0100 (CET)
```

**Comment by andryyy** [comment]
Which? I don't know your current config and changes you already tried. It works fine on master.

**Comment by fabianhick** [comment]
I used the one given here:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-anonym_headers/

**Comment by andryyy** [comment]
I deleted this page now. We include it by default in master. :/ Forgot 
about it.

------ Originalnachricht ------
Von: "Fabian Hick" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Mention" 
<mention@noreply.github.com>
Gesendet: 08.03.2019 23:15:54
Betreff: Re: [mailcow/mailcow-dockerized] Anonymize Headers not working 
(#1448)

**Comment by fabianhick** [comment]
Thanks, this config works.
I just discovered why I still saw my private data being exposed: I just sent the email internally.
Why is the filter not applied for internal mails?

**Comment by Rattenschwanz** [comment]
Unfortunately the anonymization of the header still doesn't work for me. I haven't changed anything and it's the current version. Ports 465 and 587 are also used to send mails. I have adopted the default settings, which roughly match those here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-anonym_headers/
