### ISSUE TITLE
not enough free space when sending attachments

### ISSUE THREAD

**Issue by Viktova** [mailcow/mailcow-dockerized#1450]
I was getting an error when attaching files, saying that the maximum limit allowed on the server is around 25MBs, so i increased the `message_size_limit` to  `1000000000000` in main.cf of postfix instead of the default one and yes, i restarted the container to take effect.

after that i tried again and the error message changed to
`The size of the message you are trying to send exceeds a temporary size limit of the server. The message was not sent; try to reduce the message size or wait some time and try again. The server responded:  4.3.1 Insufficient system storage.`

here's something from the postfix-mailcow container logs

```
.....
postfix-mailcow_1    | May 31 11:00:46 postfix/smtpd[782]: NOQUEUE: reject: MAIL from xx.xx.com [xxx.xxx.xxx.xxx]: 452 4.3.1 Insufficient system storage; proto=ESMTP helo=<xx.xx.com>
postfix-mailcow_1    | May 31 11:00:46 postfix/smtpd[782]: warning: not enough free space in mail queue: 9679581184 bytes < 1.5*message size limit
.....
```

Note that When i attach to postfix i did a `du -hs /` and `dh -f` i see something similar to this with enough space:

```
Filesystem      Size  Used Avail Use% Mounted on
udev            487M     0  487M   0% /dev
tmpfs           100M   12M   88M  12% /run
/dev/vdax        25G   16G  9.1G  63% /
tmpfs           497M     0  497M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           497M     0  497M   0% /sys/fs/cgroup
/dev/vdaxx      105M  3.4M  102M   4% /boot/efi
overlay          25G   16G  9.1G  63% /var/lib/docker/overlay2/d3ea8390a7d32ec3906487df36d8b77e6cb01ada6f4359c1b56fb4abfc341705/merged
shm              64M     0   64M   0% /var/lib/docker/containers/32e2c0c11c920c3fd78112e73740a9f41b8e4a8c6057a3026379e42cb8604f71/mounts/shm
overlay          25G   16G  9.1G  63% /var/lib/docker/overlay2/5efbd97e1cb03e94e1f1096bb344b596c66924c163b64c6d824b9f7980db4338/merged
overlay          25G   16G  9.1G  63% /var/lib/doc
....
........
```

i even tried to change nginx client_body_size or something like that, it didnt work.

what am i missing?

edit: i'm not even able to send a 2MBs file as attachment
edit2: on gmail it says "blocked for security reasons" when i try to attach the zipped file. its basically a shredded file / truncated, randomly generated.
edit3: tried actual zipped css and html files also got an error from google saying its been blocked for security reasons.. seems its not a security issue its the server rejecting the file or something.
edit4: tried to update.sh and reboot the whole server, nothing worked.
here's a screenshot confirming the freespace:
https://imgur.com/z7MnhdO

**Comment by Viktova** [comment]
issue was with the `message_size_limit`, it seems i cant increase it that much, so i tried something smaller ~250MBs, it worked fine. maybe its good to put something in the documentation concerning a maximum limit for postfix

**Comment by andryyy** [comment]
Or just set message_size_limit = 0 - this is something you will find in the Postfix documentation, not mailcow. :-) Glad you fixed it.
