### ISSUE TITLE
Question: why is mailcow communicating to different IPs on port 80?

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#1451]
Hi,
accidently (after activating firewall rules) I have noticed that mailcow is communicating to different IPs on port 80, e.g. 
138.201.17.217
185.87.185.65
104.16.189.138

**Question:**
What is the functionality behind this communication?
What is the impact if I continue blocking outgoing traffic from mailcow (to these IPs)?

THX

**Comment by andryyy** [comment]
It queries blacklists, checks DNS of incoming MTAs etc. ... these IPs are not queried by mailcow in general ...

Why would we - for example - query 138.201.17.217 which points to "fossies.org"?

**Comment by cmonty14** [comment]
This means it's recommended to open port 80 for mailcow?

**Comment by andryyy** [comment]
Why would you block outgoing 80/tcp? Besides that: no, we don't query fossies.org. You should debug this on your server and find the source for this query.

**Comment by cmonty14** [comment]
hm... I checked 138.201.17.217, and it belongs to "Hetzner Online GmbH".
How do you identify fossies.org?

**Comment by MAGICCC** [comment]
```
host 138.201.17.217
217.17.201.138.in-addr.arpa domain name pointer fossies.org.
```
https://dnslytics.com/ip/138.201.17.217

**Comment by cmonty14** [comment]
Thanks.
Could you please advise how to debug on mailcow server who is calling the "critical" IPs?

BTW mailcow is getting more communicative... I have recorded this:
`May 31 20:54:22 net2-alix kernel: [20063.849023] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=176.9.102.216 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=63955 DF PROTO=TCP SPT=42152 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:26 net2-alix kernel: [20068.104995] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=176.9.102.216 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=63956 DF PROTO=TCP SPT=42152 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:35 net2-alix kernel: [20076.296966] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=176.9.102.216 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=63957 DF PROTO=TCP SPT=42152 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:49 net2-alix kernel: [20091.186077] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=150.214.142.197 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=42265 DF PROTO=TCP SPT=58508 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:50 net2-alix kernel: [20092.200869] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=150.214.142.197 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=42266 DF PROTO=TCP SPT=58508 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:52 net2-alix kernel: [20094.216824] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=150.214.142.197 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=42267 DF PROTO=TCP SPT=58508 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:54:57 net2-alix kernel: [20098.312817] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=150.214.142.197 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=42268 DF PROTO=TCP SPT=58508 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:55:05 net2-alix kernel: [20106.504745] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=150.214.142.197 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=42269 DF PROTO=TCP SPT=58508 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:55:20 net2-alix kernel: [20121.520283] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=185.103.157.37 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=39418 DF PROTO=TCP SPT=46722 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:55:21 net2-alix kernel: [20122.536644] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=185.103.157.37 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=39419 DF PROTO=TCP SPT=46722 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 
May 31 20:55:23 net2-alix kernel: [20124.552652] [DMZ-IN-default-D]IN=eth2.1000 OUT=eth0 MAC=00:0d:b9:2c:b6:fa:32:32:31:33:38:30:08:00 SRC=10.0.0.4 DST=185.103.157.37 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=39420 DF PROTO=TCP SPT=46722 DPT=873 WINDOW=29200 RES=0x00 SYN URGP=0 `

Any idea about the communication on destination port 873?

THX

**Comment by andryyy** [comment]
That's rsync on this port. No, I don't want to debug all connections made by your server.

There are a bunch of connections to blacklists, MX checks, hashes from Rspamd etc. ... I will not debug every single connection and tell you wether it was a MX lookup, a hash check, a blacklist query or just something completely unrelated to mailcow etc. 

You will need to turn of all those checks in Rspamd and even Postscreen in Postfix, if you want to stop these (edit: all outgoing) connections.

I don't even think 10.0.0.4 is the Docker bridge...
