### ISSUE TITLE
Netfilter error?

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1452]
Good evening,

i restarted netfilter and netfilter logs show this error:

`netfilter-mailcow_1  | 2018-05-31T19:55:00.480920534Z Clearing all bans
netfilter-mailcow_1  | 2018-05-31T19:55:00.491228377Z Error in atexit._run_exitfuncs:
netfilter-mailcow_1  | 2018-05-31T19:55:00.491251680Z Traceback (most recent call last):
netfilter-mailcow_1  | 2018-05-31T19:55:00.491256204Z   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
netfilter-mailcow_1  | 2018-05-31T19:55:00.491260437Z     func(*targs, **kargs)
netfilter-mailcow_1  | 2018-05-31T19:55:00.491264440Z   File "/server.py", line 213, in clear
netfilter-mailcow_1  | 2018-05-31T19:55:00.491268488Z     filter_table.commit()
netfilter-mailcow_1  | 2018-05-31T19:55:00.491272485Z   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1596, in commit
netfilter-mailcow_1  | 2018-05-31T19:55:00.491276477Z     raise IPTCError("can't commit: %s" % (self.strerror()))
netfilter-mailcow_1  | 2018-05-31T19:55:00.491280645Z IPTCError: can't commit: Resource temporarily unavailable
netfilter-mailcow_1  | 2018-05-31T19:55:00.491292015Z Error in sys.exitfunc:
netfilter-mailcow_1  | 2018-05-31T19:55:00.491296135Z Traceback (most recent call last):
netfilter-mailcow_1  | 2018-05-31T19:55:00.491299662Z   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
netfilter-mailcow_1  | 2018-05-31T19:55:00.491303365Z     func(*targs, **kargs)
netfilter-mailcow_1  | 2018-05-31T19:55:00.491306554Z   File "/server.py", line 213, in clear
netfilter-mailcow_1  | 2018-05-31T19:55:00.491310059Z     filter_table.commit()
netfilter-mailcow_1  | 2018-05-31T19:55:00.491313452Z   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1596, in commit
netfilter-mailcow_1  | 2018-05-31T19:55:00.491316892Z     raise IPTCError("can't commit: %s" % (self.strerror()))
netfilter-mailcow_1  | 2018-05-31T19:55:00.491320318Z iptc.ip4tc.IPTCError: can't commit: Resource temporarily unavailable
netfilter-mailcow_1  | 2018-05-31T19:55:59.185301801Z Clearing all bans
netfilter-mailcow_1  | 2018-05-31T19:55:59.186302623Z Initializing mailcow netfilter chain
netfilter-mailcow_1  | 2018-05-31T19:55:59.201855602Z Subscribing to Redis channel F2B_CHANNEL
`
Is this a critical fault?

**Comment by andryyy** [comment]
No, it is not problematic.

**Comment by ghost** [comment]
Ok, thanks :-)
