### ISSUE TITLE
Redis problems

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#1454]
Hello, today I experience error in mailcow ui with this error message.

`Redis: RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /web/json_api.php:45 Stack trace: #0 /web/json_api.php(45): Redis->lPush('API_LOG', '{"time":1527861...') #1 /web/json_api.php(56): api_log(Array) #2 {main}`

I try to update redis container to latest version 4 image, but errors appears again after while.

**Comment by andryyy** [comment]
Oh, can you check why it cannot write to the Redis volume?

Try 
```
docker exec --user redis -it $(docker ps -qf name=redis-mailcow) /bin/sh
$ touch /data/1
```

**Comment by feldsam** [comment]
Hello, it is writable, touch work without issues. Error also gone, looks like it only sometimes happen and error message in ui is showing until cancel it. So probably memory issue?

https://stackoverflow.com/a/49839193/1694218

**Comment by feldsam** [comment]
Today I see same error in rspamd log, so I googling and according this https://github.com/openfirmware/docker-redis/issues/1 I set vm.overcommit_memory=1 on host and will see if error disappears.

**Comment by feldsam** [comment]
hi, look like vm.overcommit_memory=1 helps. I never see that error again

**Comment by feldsam** [comment]
vm.overcommit_memory=1 solves problem
