### ISSUE TITLE
DNS resolution in containers

### ISSUE THREAD

**Issue by adeleglise** [mailcow/mailcow-dockerized#1456]
Hi,
First of all, thanks a lot for this great project ! It's wonderful to see all of the well known OSS tied together, ans well configured !

My problem is, not related to the mailcow architecture itself I think, the IP resolved for the MX is the public IP.
I have a shorewall installed on a proxmox server. I have one VM that's hosting the mailcow dockerized solution. All the containers have been deployed without issues. I can access the administration and SOgo pages normally.

However, I can send e-mails but I cannot reveive e-mails. The problem is the postfix container, when trying to deliver to mailboxes, is querying my hostname, and I has i don't have a bind server installed, it's the public IP that's resolved. So the e-mail arrives, and is routed back from the LAN to WAN, and there it's REJECTED by shorewall.

So my question is, is it possible to manage the DNS entries for the docker containers ? So that I can define the LAN adress to my postfix instance.

Configuration :

qemu VM :
debian 9
docker-ce stable from repos
proxmox ve server :
5.2-1
Latest mailcow installed (repo cloned saturday).

Postfix logs :
```

04/06/2018 à 10:10:52 | info | CDF8E4A19E5: to=<XXX.XXXX@XXXX.XX>, relay=none, delay=909, delays=908/0.09/0.74/0, dsn=4.4.1, status=deferred (connect to XXXX.XXXXXX.XX[XXX.XXX.XXX.XXX]:25: Connection refused)
-- | -- | --
04/06/2018 à 10:10:51 | info | 15D514A19E1: to=<XXX.XXXX@XXXX.XX>, relay=none, delay=2395, delays=2394/0.06/0.77/0, dsn=4.4.1, status=deferred (connect to XXXX.XXXXXX.XX[XXX.XXX.XXX.XXX]:25: Connection refused)
04/06/2018 à 10:10:51 | info | connect to XXXX.XXXXXX.XX[XXX.XXX.XXX.XXX]:25: Connection refused
04/06/2018 à 10:10:51 | info | connect to XXXX.XXXXXX.XX[XXX.XXX.XXX.XXX]:25: Connection refused
04/06/2018 à 10:10:51 | info | CDF8E4A19E5: from=<XXX.XXXX@XXXX.XX>, size=19378, nrcpt=1 (queue active)

**Comment by axd** [comment]
What do you mean, are you trying to send emails to IP directly, something like mail@200.120.120.1 ?

In simply words you can actually send email directly to an IP, but if you want to send to some @domain.tld this domain must have MX records pointing to your mail server.

**Comment by adeleglise** [comment]
No, I'm not trying to send e-mail to an IP.

I have already configured all my DNS zone. So the DMARC, SPF and DKIM and of course MX records can be resolved with the public IP of the proxmox hypervisor. Then the needed ports are forwarded and authorized by shorewall to the mailcow VM.

I have tested the installation by just sending an email from mailcow to some of my other email address. Then I responded to the received email address. The error log shows the email coming into mailcow, and the port 25 refused.

I can telnet the port 25 of the proxmox hypervisor. I can also telnet the port 25 of the VM from the hypervisor. 

Maybe it's just something I have not configured correctly. But it's strange to see in the postfix logs of mailcow the public IP of the MX, as it should be routed internally when an incoming mail needs to be delivered to a managed mailbox.

**Comment by adeleglise** [comment]
I've tried different configuration for my_networks and my_destination, but nothing seems to work.

Here are some logs :

```
postfix-mailcow_1    | Jun  6 09:59:37 webmail postfix/postscreen[366]: CONNECT from [46.105.61.149]:50213 to [172.22.1.2]:25
postfix-mailcow_1    | Jun  6 09:59:37 webmail whitelist_forwardinghosts: Look up 46.105.61.149 on whitelist, result 200 DUNNO
postfix-mailcow_1    | Jun  6 09:59:40 webmail postfix/postscreen[366]: PASS NEW [46.105.61.149]:50213
postfix-mailcow_1    | Jun  6 09:59:40 webmail postfix/smtpd[381]: connect from 7.mo177.mail-out.ovh.net[46.105.61.149]
postfix-mailcow_1    | Jun  6 09:59:40 webmail postfix/smtpd[381]: Anonymous TLS connection established from 7.mo177.mail-out.ovh.net[46.105.61.149]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
postfix-mailcow_1    | Jun  6 09:59:40 webmail postfix/smtpd[381]: 8F8164A196B: client=7.mo177.mail-out.ovh.net[46.105.61.149]
postfix-mailcow_1    | Jun  6 09:59:40 webmail postfix/cleanup[385]: 8F8164A196B: message-id=<8cf96cc2d13f5c1bea48054cb3685735@example.net>
postfix-mailcow_1    | Jun  6 09:59:44 webmail postfix/qmgr[362]: 8F8164A196B: from=<alain@example.net>, size=1632, nrcpt=1 (queue active)
postfix-mailcow_1    | Jun  6 09:59:44 webmail postfix/smtpd[381]: disconnect from 7.mo177.mail-out.ovh.net[46.105.61.149] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
postfix-mailcow_1    | Jun  6 09:59:44 webmail postfix/smtp[386]: connect to webmail.example.fr[PUBLIC IP]:25: Connection refused
postfix-mailcow_1    | Jun  6 09:59:44 webmail postfix/smtp[386]: 8F8164A196B: to=<alain.deleglise@example.fr>, relay=none, delay=4.1, delays=4.1/0.03/0/0, dsn=4.4.1, status=deferred (connect to webmail.example.fr[PUBLIC IP]:25: Connection refused)
```

I can telnet the smtp port from a distant machine :

```
telnet webmail.example.fr 25
Trying PUBLIC IP...
Connected to webmail.example.fr.
Escape character is '^]'.
220-webmail.example.fr ESMTP Postfix
^]
```

**Comment by andryyy** [comment]
Hi,
I don't understand, why it should query your hostname, when it delivers to mailboxes (which? internal? external?). 
You can configure fix records in `data/conf/unbound/unbound.conf` by adding this inside the server block:

```
server
  bla
  local-data: "bla.example.com. IN A 123.45.67.89"
```

Oh, and restart unbound: `docker-compose restart unbound-mailcow`

**Comment by adeleglise** [comment]
> I don't understand, why it should query your hostname, when it delivers to mailboxes

Indeed, it don't understand why the postfix needs to connect to itself to deliver a mail localy. It should give it to dovecot, no ?

Those are internal mailboxes.

Which informations can I give you to better understand the problem ?

**Comment by adeleglise** [comment]
OK, i found the problem.

By default the two checkboxes for the secondary MX were checked, I unchecked them, and now postfix delivers mails to dovecot !

Thanks for your help !

**Comment by andryyy** [comment]
Ahh, I see. That happens quiet often, I tend to forget about this everytime... :-)

**Comment by andryyy** [comment]
But they are not checked by default, btw...

**Comment by adeleglise** [comment]
I did not checked those boxes ...

**Comment by andryyy** [comment]
They are not enabled by default. I mean... you can check the code after all. :-)

**Comment by adeleglise** [comment]
Indeed :p

However, it's really a great tool/product mailcow ! Thanks again :)
