### ISSUE TITLE
Feature Request: Set API Key via mailcow.conf

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#1457]
Currently I set the API key like this:

```sh
echo "INSERT INTO \`api\` VALUES ('admin','${APIKEY}','172.22.1.1','2018-06-03 12:07:27',NULL,1);" | /usr/bin/docker exec -i mailcowdockerized_mysql-mailcow_1 /usr/bin/mysql -uroot -p${DBROOT} mailcow
```

For automation it would be much easier if the API key could also be set using `mailcow.conf`.

* This allows you to source mailcow.conf and use the api key on the console.

**Comment by mitchellurgero** [comment]
Isn't the key set in the admin panel? I never used it so i am not sure.

**Comment by mritzmann** [comment]
> Isn't the key set in the admin panel?

Yes. In a CSS-hidden div.

But it is not so practical if you want to automate something from the beginning. It could also be useful for helper-scripts if the API key was accessible from the console.

**Comment by mritzmann** [comment]
If `API_KEY` and `API_ALLOW_FROM` is set before the first `docker-compose up -d`, mailcow cannot be installed.

steps to reproduce:

1. `git clone https://github.com/mailcow/mailcow-dockerized.git && cd mailcow-dockerized`
2. `./generate_config.sh`
3. `echo "API_KEY=273D62-09B35E-5061A0-D5483B-C79856" >> mailcow.conf`
4.  `echo "API_ALLOW_FROM=172.22.1.1" >> mailcow.conf`
5. `docker-compose up -d`

WebUi: Bad Gateway

Log:

```log
Jun 12 13:34:24 localhost.localdomain 178732c2cbae[2039]: ERROR 1146 (42S02) at line 1: Table 'mailcow.domain' doesn't exist
Jun 12 13:34:24 localhost.localdomain 178732c2cbae[2039]: ERROR 1146 (42S02) at line 1: Table 'mailcow.alias_domain' doesn't exist
Jun 12 13:34:24 localhost.localdomain 178732c2cbae[2039]: ERROR 1146 (42S02) at line 1: Table 'mailcow.api' doesn't exist
```

_(the only change I'm making, too: `HTTP_PORT=8080`, `HTTP_BIND=127.0.0.1`. `HTTPS_PORT=8443`, `HTTPS_BIND=127.0.0.1`, `SKIP_LETS_ENCRYPT=y` due my reverse proxy)_

Maybe INSERT INTO bevor db is initialize is the problem: https://github.com/mailcow/mailcow-dockerized/blob/0d9b474f69ebf56a3d33b1e3d185e8fc25cbb338/data/Dockerfiles/phpfpm/docker-entrypoint.sh#L49

**Comment by mitchellurgero** [comment]
> If API_KEY and API_ALLOW_FROM is set before the first docker-compose up -d, mailcow cannot be installed.

This should be  opened in a separate issue.

**Comment by mkuron** [comment]
To fix that issue, we would need to call the database initialization PHP script from the phpfpm entrypoint. Right now it is called when the web site is first accessed, which is a bit late anyway.
