### ISSUE TITLE
Understanding Backup MX and it's possibilities

### ISSUE THREAD

**Issue by Xadagain** [mailcow/mailcow-dockerized#1458]
I'm a little bit new to mails, so i dont know all the basic stuff you know.
I want to create a Backup MX on a second server.

Everything i have to do is:

1. install mc-d on second server with an A and MX record higher priority.
2. Add maildomain i use, like test.de
3. And set "Relay Domain" to true
4. And if i set **additionally** "Relay all recipients" i dont have to create like 400 mailboxes on the Backup MX Server. ( or do i have to check "relay all recipients" alone? 
The first paragraph [here in the wiki](https://mailcow.github.io/mailcow-dockerized-docs/debug-common_problems/) confuse me. )

And then i should have a running backup mx system.
Or am I wrong?

When i get the backup mx working and all recipients are relayed, what happens when Master MX is back online and get mails for recipients dont exists?

Last Question:
I run some website which has to send registration confirmation mails. I would like to make them high available too. If backup mx is active: is it possible to create a mailbox for this backup mx domain and if master mx is off i can send mails over the backup mx?

Well i could also config a local postfix on the webserver with spf and DKIM. But i dont like this setup. (explain the reasons would take too long).

**Comment by marrco** [comment]
> And if i set additionally "Relay all recipients" i dont have to create like 400 mailboxes on the Backup MX Server. 

backscatter could be a problem then.

**Comment by thomas126** [comment]
Also have not found it in the docs. Are those the only steps i have to do in order to cache all receiving mails when the main mx server is down and when it is back online forward those missing mails to it?!
