### ISSUE TITLE
SOGo only displays Domain aliases as possible sender

### ISSUE THREAD

**Issue by wucke13** [mailcow/mailcow-dockerized#146]
I have the following scenario:
+ Domains: `domain.tld, example.tld, domain3.tld`
+ User: `x@domain.tld, x@example.tld`
+ The domain `domain3.tld` is an alias domain for `domain.tld`.
+ The User `x@domain.tld` has the following adresses selected in `Allow to send as:`
   + `x@domain.tld, x@domain3.tld, x@example.tld`. Notable: the first two are always checked, for obvious reasons, so only the last one was manually added

However, when user `x@domain.tld` is logged in in SOGo, only `x@domain.tld` and `x@domain3.tld` show up as possible `Send From` adresses. The manual added `x@example.tld` does not show up. 

Why is that? Is that a Bug? Is there a way to tell SOGo to show `x@example.tld` as possible option for the `Send From` field too?

Best regards, wucke

**Comment by andryyy** [comment]
Hi,
x@example.tld is a "real" mailbox, right? This user needs to delegate his account to yours.

![image](https://cloud.githubusercontent.com/assets/2972950/24264412/acb34f8e-1000-11e7-8167-21b691a55f0f.png)

To be able to send as this user, it is important to also set "allow to send as" - as you already did. :-)

**Comment by wucke13** [comment]
Oh well that's a good hint. When I click on that button, I can enter something in a text field, but there is no button to confirm that delegation. What am I missing?

**Comment by andryyy** [comment]
It auto-completes as you type. But each domain is isolated. You can connect them/make them visible to each other by changing `data/conf/sogo.conf`:

```
SOGoDomainsVisibility = ( (domain1.tld, example.com) );
```

**Comment by wucke13** [comment]
Thanks again! I would love to see an UI option for this in the future!

**Comment by MightyPork** [comment]
The UI option is still missing, but I was able to fix my problem through the config file. So, good news is that it still works!
