### ISSUE TITLE
Add autoresponder / vaction to Roundcube

### ISSUE THREAD

**Issue by tamerax** [mailcow/mailcow-dockerized#1461]
I am trying to add an autoresponder for to Roundcube (my clients like it more than Sogo). 
I have tried adding it as a plugin and it just goes to a whitescreen.
Can anyone walk me through the steps to get it installed and working?

Docker seems to make things more complicated as I'm not familiar enough with it. 

Thank you

**Comment by andryyy** [comment]
Would be interesting how exactly you enabled it.

**Comment by tamerax** [comment]
So I uploaded the files from here
https://github.com/gabor-toth/roundcube-vacation-plugin

and put them into the plugin dir in round cube and then added the plugin name to $config['plugins']

I also tried just following the instructions here to get it installed
https://plugins.roundcube.net/

but this command php composer.phar install doesn't work in that dir so nothing get installed that way. I think there might be some dependacies but I don't know how to get it working.

**Comment by andryyy** [comment]
I don't think you need to add that plugin. Afaik RC comes with such a plugin by default. It is called "managesieve".

```
# default config
$rcmail_config['plugins'] = array('bla', 'managesieve', 'bla');
# managesieve related config should be in config/managesieve/ or something like that
```

**Comment by tamerax** [comment]
Thanks that seems to be the right plugin. Just give me errors now and I'm not sure how to configure properly.

**Comment by tamerax** [comment]
this is all i can really find on the solution 
https://github.com/mailcow/mailcow-dockerized/issues/820

**Comment by ghost** [comment]
@tamerax This is my minimal config for managesieve on roundcube. Maybe this helps you:

> $config['managesieve_port'] = 4190;
> $config['managesieve_host'] = 'tls://dovecot';
> $config['managesieve_conn_options'] = array(
> 'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
> );
> 
> // Enables separate management interface for vacation responses (out-of-office)
> // 0 - no separate section (default),
> // 1 - add Vacation section,
> // 2 - add Vacation section, but hide Filters section
> $config['managesieve_vacation'] = 1;

**Comment by tamerax** [comment]
@pmike1980 That works perfectly! Thank you so much!!

**Comment by lavdnone** [comment]
Looks like those settings are not enough now. If someone can share fresh Roundcube managesieve settings
