### ISSUE TITLE
Enable SOGo EMail reminders

### ISSUE THREAD

**Issue by nicolaspernoud** [mailcow/mailcow-dockerized#1462]
This is a feature request.

It seems that sogo allow email-based reminders for events and tasks (https://sogo.nu/files/docs/SOGoInstallationGuide.html#__em_cronjob_em_email_reminders)
It would be nice if those were enable in mailcow... That's the only reason I keep google calendar for...

**Comment by andryyy** [comment]
Have you tried enabling it in data/conf/sogo/sogo.conf and tested it? I am not sure, why I disabled this feature. We may want to add a whitelist record for those notifications though. I think SOGo uses the default SMTP server to send them, not sure.

**Comment by nicolaspernoud** [comment]
I did : it enables it in the gui (you can set an email reminder) but no email is sent, probably because the cron job described in the sogo documentation is not set...

There is also the OCSEMailAlarmsFolderURL wich should be something like mysql://sogo:xxxxxxxx@sogo.mydomain.com:3306/sogo/sogo_alarms_folder maybe ?!

**Comment by andryyy** [comment]
OCSEMailAlarmsFolderURL is set.
The cronjon is active, too.

Can you check postfix-mailcows log? Hm, and sogo-mailcow.

**Comment by andryyy** [comment]
```
postfix-mailcow_1    | Jun  9 13:05:03 mx postfix/smtpd[6740]: connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
postfix-mailcow_1    | Jun  9 13:05:03 mx postfix/smtpd[6740]: disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 quit=1 commands=2
```
Huh. It tried to send but probably failed.

I will check and fix it.

**Comment by andryyy** [comment]
<0x0x1831960[WOContext]> missing request in -baseURL call ..

Hm, I will report it...

**Comment by nicolaspernoud** [comment]
Thanks a lot.

**Comment by nicolaspernoud** [comment]
Do you have any news on this issue ?

**Comment by andryyy** [comment]
Ping.

**Comment by nicolaspernoud** [comment]
Any news yet ?

**Comment by andryyy** [comment]
No response, I will open a paid support ticket.

**Comment by nicolaspernoud** [comment]
Thanks, I am still looking for that feature so I would be able to ditch my google calendar for good...

**Comment by andryyy** [comment]
Yay, finally fixed.

Thanks to the amazing SOGo team!

Will push it tomorrow and finally update the changelog.

**Comment by nicolaspernoud** [comment]
Perfect, Thanks a lot !

**Comment by andryyy** [comment]
Did you test it already? :)

**Comment by nicolaspernoud** [comment]
Yes, it seems to works fine...

**Comment by nicolaspernoud** [comment]
Closing since it works. Thanks again.
PS : just so you know mailcow is in linux format (issue 244, https://www.linuxformat.com/)

**Comment by andryyy** [comment]
Nice! I didn't know! :)
