### ISSUE TITLE
gogs installation

### ISSUE THREAD

**Issue by constin** [mailcow/mailcow-dockerized#1465]
Hallo, than i trying install gogs by your documentation it forward me to https://mx.example.com/install.
And this path is not exist in nginx config.

location /gogs/ {
    proxy_pass http://gogs:3000/;
}

I made

location /install/ {
    proxy_pass http://gogs:3000/install;
}

But then i get page without css, nothing happens  by pressing "install"

**Comment by constin** [comment]
solved:
tou need create data/gogs/gogs/conf/app.ini BEFORE visit http://site/sogs

**Comment by mitchellurgero** [comment]
Wouldn't Gitea be a slightly easier setup (and is based on Gogs too)

EDIT: Aww why the thumbs down? Gitea and Gogs are literally the same!

**Comment by GVA-Guillaume** [comment]
Hi, same issue,
