### ISSUE TITLE
last update broke webui and rspamd graph

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1467]
Hello,
I just updated to the latest version, now the ui is kind of broken and the rspamd chart does not load when selecting rspamd from the menu, it only loads when reloading the page. Here are some screenshots:

<img width="1192" alt="bildschirmfoto 2018-06-08 um 10 03 01" src="https://user-images.githubusercontent.com/6145026/41146484-d138fd04-6b03-11e8-96bb-67d278f82639.png">
<img width="1160" alt="bildschirmfoto 2018-06-08 um 10 03 54" src="https://user-images.githubusercontent.com/6145026/41146485-d1516178-6b03-11e8-9ea1-bbbcc789385f.png">

**Comment by andryyy** [comment]
I really don't see what happened in your alias view. You will need to describe it or create another screenshot, please. 

I mean... what does address show? What does goto show?

**Comment by andryyy** [comment]
I'm stupid. Forget it. I will push a fix.
