### ISSUE TITLE
Reinstall on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by marzel1** [mailcow/mailcow-dockerized#1468]
Hello, everybody,

i reinstalled my server today with Ubuntu 18.04 and was about to install Mailcow. Unfortunately without success.

I proceeded as described in the documentation, after docker-compose pull I get this error message.

ERROR: Invalid interpolation format for "environment" option in service "php-fpm-mailcow": "API_KEY=${API_KEY:-}"

Anybody have any idea what's going on? Never had this message before.

**Comment by andryyy** [comment]
Did you set API_KEY in mailcow.conf?

**Comment by marzel1** [comment]
No, do i have to?

**Comment by andryyy** [comment]
No. Give me a few mins, I will fix it.

**Comment by andryyy** [comment]
I cannot reproduce it. Can I have a look on that machine via SSH? I will fix it asap then.

**Comment by marzel1** [comment]
Sent you a mail.

**Comment by andryyy** [comment]
I did run `docker-compose pull` and `up -d` on your system without any errors.

Ooops, missing info: Images were not pulled. I guess it tried to build them and failed to due the missing variable. I will add a "invalid" value and check against it.

**Comment by mkuron** [comment]
> ```
> ERROR: Invalid interpolation format for "environment" option in service "php-fpm-mailcow": "API_KEY=${API_KEY:-}"
> ```

This happens if your docker-compose is older than 1.18, see https://github.com/docker/compose/issues/5185. If you use the updater script, you should have automatically installed the necessary update months ago. If you update manually, you may need to run
```
curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
```
