### ISSUE TITLE
Redirecting the "main page" or showing something blank instead of the mailcow login

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1470]
Hello ! I've got a quick question if it is possible to just access the mailcow webinterface from my subdomain and not my main domain. With subdomain I mean in this case mail.mydomain.com. Right now an A Record points from my domain to the server mailcow is running on and honestly if thats possible I'd like to keep that, but is it somehow possible if you try to access my domain itself to display like a blank page or something like that ? Sadly I'm not that experienced with doing websites etc. and would appreciate it, if I could find some help here. (Mailcow itself is running perfectly). 

Thank you

**Comment by mitchellurgero** [comment]
You do not need that A record on the main domain to point to your mailcow IP.

**Comment by xL0b0** [comment]
@mitchellurgero So I could basically fix it, by removing that A Record ? Just thought that because in the documentation it is recommended ?

**Comment by mitchellurgero** [comment]
The only A record that needs that IP is mail.domain.com, not domain.com. Unfortunately you probably read the documentation wrong, or the documentation itself is wrong. From a DNS POV you only need the one on mail.domain.com.  Good luck mate!

**Comment by xL0b0** [comment]
Oh, that sounds cool, so I can remove that A record and achieve what I described ?

**Comment by mitchellurgero** [comment]
PS:
I am talking *only* about the **A** record, *not* MX, SRV, & TXT records.


Yes, removing that A record (or changing it to a different IP for a new webserver as an example) will do as you need.

**Comment by xL0b0** [comment]
Ye, I am also just talking about the A record to the Main domain, nothing like MX or so. Just wanted to know that, thank you !

**Comment by xL0b0** [comment]
@mitchellurgero Okay, that's weird. In my iOS mail client Spark, if I remove the A record, it says "cant connect to mail server", Thunderbird works perfectly fine. If I re add it, it works again. Do you might know if there's anything I can do to resolve that ?
