### ISSUE TITLE
COMPOSE_HTTP_TIMEOUT

### ISSUE THREAD

**Issue by KeNzoooo** [mailcow/mailcow-dockerized#1471]
Can someone help me out ?
Im getting this issue while installing mailcow.

`ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

**Comment by paladine-raistlin** [comment]
Try doing it with
`COMPOSE_HTTP_TIMEOUT=200 docker-compose -f docker-compose.yml up`
