### ISSUE TITLE
Not receiving any push notifications anymore after removing A Record from domain itself to Mailserver

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1472]
Okay, let me explain the entire situation first, as the title might sound a bit weird and confusing. 
Initially I had an A Record set at my domain provider, redirecting my domain to my Mailserver, because in some video guides for Mailcow it was mentioned that this was necessary (but I had also a subdomain redirecting to mailcow, so that was not the problem [in this case mail.mydomain.email] ). 
Yesterday I did a post and asked if this was actually needed, and I was taught that it was't (maybe I mixed some things up during the time I set up my MailServer and reading the documenation with all the records I had to set) so I removed that A Record from my "main" domain to my server, because I didn't want everyone, accessing my domain to see that MailCow interface. 
After I removed the record everything worked fine, I could receive and send E-Mails, but the notifications on my mobile devices weren't working anymore. In this case I used a very common iOS mail client called "Spark" and to test it with something else, also the G-Mail app, to prove that it is not caused by Spark. Both clients did not gave me any push notifications anymore and I was very confused, why this was happening. If I go in the app itself and refresh my Mailbox, mails still appear tho. So I re added the A Record and everything was working fine again.

My question now: is there any way of still achieving that you will not see the MailCow interface if you access my "main" domain, but that l can still receive push notifications ?
(In this case, main domain means anything, but a subdomain).

Thank you very much for taking the time to read, I highly appreciate any help on this !

**Comment by andryyy** [comment]
You should post your zone file or entire domain configuration.

**Comment by xL0b0** [comment]
@andryyy This is my domain configuration. In Mailcow itself it says, despite of the TSLA entries, everything is done correctly. Hope the images help.
https://i.imgur.com/SkoOrvP.png
https://i.imgur.com/koQZfuX.png

**Comment by andryyy** [comment]
Do you use a reverse proxy? What is your MAILCOW_HOSTNAME? You had set it to "domain.tld" a while ago, iirc. What's in SOGos logs? A push notification can still take a few seconds to arrive.

Nginx does only listen to "MAILCOW_HOSTNAME", it does not care about a missing A record for domain.tld at all (but GMail, for example, will punish you, btw.).

Run `docker-compose down`, delete the EAS profiles (do not use GMail with EAS right now, it kills your drafts folder with EAS 16.0 in SOGo), run `docker-compose up -d`, run `docker-compose logs -f sogo-mailcow` and setup your accounts.

**Comment by xL0b0** [comment]
No. I do not use a reverse proxy, to be honest, I also don't really see the advangtages of using it. 😅
My SoGo logs are just filled with "notice" and that the watchdog was notified that "we are ready". (Tho I don't know right know what this should tell me, never really dealt with those logs, all the time looked at the others, like Rspamd, acme, etc.). My MailCow hostname is set to mail.(mydomain).email

And sorry for asking, but what do you mean by "EAS" right now ? Not sure what the moment what this shortform means :/ . Something to the procedure, so I should remove that A Record, wait a bit and then run all of those commands ? @andryyy

**Comment by xL0b0** [comment]
? @andryyy

**Comment by andryyy** [comment]
EAS is ActiveSync. 

Please provide the logs of the described scenario. Start logging and create the accounts on your phone to test push notifications. Upload the logs then. 

EAS does not care about missing A records for the primary domain (domain.tld). 

Please read my comment above. The last part is important. Provide the logs after doing your tests.

**Comment by andryyy** [comment]
Seriously... I think you setup your phone with “domain.tld” as EAS server name with your previously wrong installed mailcow. You remember you configured mailcow with domain.tld instead of bla.domain.tld? Your phone has either cached the autodiscover response or you never rebuilt the containers with the new hostname. Or the old profile was never deleted from your phone?

You really need to provide any logs. Don’t repeat what’s in them. Just post them with private data censored. Nginx logs may help, too. 
But _please_ only post logs for the time you tried EAS on your phone.

// I’m on my phone, sorry for typos

**Comment by xL0b0** [comment]
Okay these are all available ActiveSync logs from the MailCow interface. https://i.imgur.com/dMGr4dT.png
You said I should "delete" the EAS profiles, sorry for asking like that, but is there a way I can simply reset / delete all of those EAS profiles with a command or how am I supposed to do that ? (Sorry for asking like that, I'm still quite unexperienced with debugging of such things. 

And another question, isn't ActiveSync not just in use if I use the "Microsoft Exchange" way to log in to my mail client ? 
@andryyy

**Comment by xL0b0** [comment]
https://i.imgur.com/Jg0umar.png
https://i.imgur.com/NxuuyF5.png
These are the logs given, after I type in the last command you provided with SoGo

**Comment by xL0b0** [comment]
Okay. I removed that A Record now again and I'm not receiving push notifications anymore on my iPhone with "Spark" (not using that default mail client). On my PC with Thunderbird everything is working fine. I also re set up my account in Spark, with the SMTP and IMAP Server mail.mydomain.email, as it is described in the manual configuration guide from mailcow. Still no notifications. So please, I'd appreciate it if you could tell me exactly which logs I should post from the debug part in the MailCow interface, so I can help you at least a bit more, than with just describing my problem :(

**Comment by andryyy** [comment]
You ignored my hints regarding the wrong hostname. As I said your phone probably autodiscovers to “domain.tld” and not “host.domain.tld”. Check this, please! That’s what’s wrong, I’m sure. 

Your setup is very strange and most likely broken. Maybe you changed vars.inc.php, too? 

Whatever, I’m sure the only reason your phone still has the domain name as EAS server is your old and broken config. Again: remove the profiles from your phone. Or just check the autodisovered settings.

You need to understand the basics or open a ticket for support via mailcow.email. I cannot help you much more here besides telling you what I already did. You can also wait for someone else to jump in and help.

**Comment by xL0b0** [comment]
Yeah, I think it does that. But in most mail clients, you have an option to set the mail settings manually and every time I set up a mail account I'm doing that and setting things to mail.domain.email instead just domain.email.
Is there any way of fixing that or resetting those configs ?

**Comment by andryyy** [comment]
You are probably still running the old config. Is .env even a symbolic link to mailcow.conf? I’m sure you are not using a correct mailcow.conf.

**Comment by xL0b0** [comment]
Just looked omtp the vars.inc.php file (tho I somehow can't open vars.local.inc.php file, as I says it in the file) I can't see any possible changes in there. So I think I never changed anything about that.

Also looked in the mailcow.conf file again, but nothing is changed there too. I really become desperate with that ... everything is literally working despite of that right now ._.

**Comment by xL0b0** [comment]
This is my mailcow.conf 
https://i.imgur.com/gjFonGE.png

**Comment by andryyy** [comment]
You can’t open vars.local.inc.php as it says in the file? It does not say to open that file. It says make changes to .local to make them persistent. 

You didn’t answer the symbolic link question...... You should really start over new (do NOT copy files and folders, you will probably break sym links...). 

I will mark this as question but not considering it an issue. I cannot help you much more. Please wait for someone to jump in. My free support time is limited, I need at least SOME rest. :-)

A git diff might help other people, too, I think. But ... just start over new. 

PS: You could also attach to a container (“docker-compose exec nginx-mailcow /bin/sh” for example) and run “echo $MAILCOW_HOSTNAME” to verify the hostname. Or run docker ps to check wether a second mailcow instance is running?

And don’t use YouTube videos about how to setup mailcow. We have docs for this. :-)

**Comment by xL0b0** [comment]
Yeah, I think that's better. Last few questions if I start over new: if I configure the exact same E-Mails, like because I already set up some services, I will still be able to receive those E-Mails in the future, won't I ?
In theory, all E-Mails will be lost with that right now, won't they ?

**Comment by xL0b0** [comment]
Yeah. Not going to use YouTube videos for that anymore, I think that was one of my biggest mistakes. Like for real, they leave out so many things. Many things of the DNS parts were wrong, the entire hostname thing and the SHIT with the A Record ...

**Comment by xL0b0** [comment]
Okay. Sorry for wasting your time any longer, just wanted to give you a quick update. 
Appearantly it's all about Spark. I really, really love that Mail client, but it is that, not giving me any notifications. I even created a new mail server and didn't work. So I switched back to the old one, used the default mail app and everything is working fine. Just asking myself right now, why the app is doing that ? 
Default mail app is working perfectly with notifications, I just like Spark much more :/
@andryyy (So appearantly my Mailcow is configured correctly)
