### ISSUE TITLE
Try to migrate mailcow from 0.14 to dockerized, MySQL problem

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#1474]
Hi,
I'm tried to migrate mail mailcow from old 0.14 to dockerized. In the past I'm found document for migration and I'm saved this for mysql backup.

On mailcow 0.14 I need to do this:

```
MariaDB [mailcow]> ALTER TABLE mailbox MODIFY COLUMN tls_enforce_in TINYINT(1) NOT NULL DEFAULT '0' AFTER domain,
MODIFY COLUMN tls_enforce_out TINYINT(1) NOT NULL DEFAULT '0' AFTER tls_enforce_in;

MariaDB [mailcow]> ALTER TABLE mailbox ADD COLUMN `kind` VARCHAR(255) NOT NULL AFTER `tls_enforce_out`,
ADD COLUMN `multiple_bookings` TINYINT(1) NOT NULL DEFAULT '0' AFTER `kind`,
ADD COLUMN `wants_tagged_subject` TINYINT(1) NOT NULL DEFAULT '0' AFTER `multiple_bookings`;

MariaDB [mailcow]> DESC mailbox;

```

but when I try to import this dump on new server I get error:

ERROR 1136 (21S01) at line 63: Column count doesn't match value count at row 1

On that line I can see INSERT statement fo mailboxes.

Do we have some valid and official migration document because I have several mail server for migration.
Thank's !

**Comment by petarkozic** [comment]
@andryyy 
Please can you help me, this is urgent for me. As I can see DB tables mailbox have now different orders and headers from time when I try to migrate with your documents.

**Comment by andryyy** [comment]
Eh, I am on holiday. You’d need to wait or use mailcow support. I’m not sure if @tkorves is free today. 

The docs were removed because they are not correct, as you found out already. 

Show us an example line of the INSERT, please. 

We also changed the database a few more times. That would auto fix itself, though.

To you have SSHA256 hashes for the passwords?

**Comment by petarkozic** [comment]
Sorry @andryyy thank you !
If @tkorves available maybe see this message.

To you have SSHA256 hashes for the passwords?
Yes, I have.

I need if you have ALTER command to try to export original DB from old mailcow.
Thanks man !

**Comment by andryyy** [comment]
This is something I may help you with in the evening GMT some day this week.

**Comment by andryyy** [comment]
Do you have a lot of mailboxes? Isn’t importing the mails and password hash enough? :-)

**Comment by petarkozic** [comment]
I have 4 servers for migration. Every server have about 10-15 mailboxes. Password is very important to stay same.

**Comment by andryyy** [comment]
We could create all mailboxes on the new dockerized cow and just Import password hashes and mails. Well, DKIM keys, too. Would be easier. You could just run something along update mailbox set password=“old hash” where username=”bla” and use the UI for the private keys.

**Comment by petarkozic** [comment]
Ok, this sounds good !

**Comment by petarkozic** [comment]
@andryyy 
I'm manually ALTER tables in mailbox and resolve migration.
Thank you very much.
