### ISSUE TITLE
Keine Zustellbestätigung

### ISSUE THREAD

**Issue by FN-Florian** [mailcow/mailcow-dockerized#1476]
Hallo zusammen,
wenn ich via Outlook eine Zustellbestätigung bei einem E-Mail Versand anfordere, erhalte ich trotz erfolgreichen Versand keine Zustellbestätigung zugesandt.

Woran kann das liegen bzw. wie kann ich das beheben?

Viele Grüße
Florian

**Comment by roswitina** [comment]
Das geht meines Wissens nur innerhalb bzw zwischen Exchange Servern. Für den Versand zu anderen Mail-Servern wird das SMTP Protokoll laut RFC 821 bzw 822 verwendet und das sieht keine Zustellbestätigung vor. Das hat Microsoft für Outlook und Exchange eingebaut.

**Comment by FN-Florian** [comment]
@roswitina: Danke für deine Antwort, ich weiß jedoch das es schon funktioniert hatte. Jedoch seit einiger Zeit nicht mehr.   Ist es möglich das in diesen Fällen das Ziel ein Exchange war und es deswegen funktionierte?

**Comment by mkuron** [comment]
Das ist tatsächlich standardisiert und wird von Postfix unterstützt: http://www.postfix.org/DSN_README.html . Details unter #362, das hat definitiv schon mal funktioniert. Ob der empfangende Server Exchange ist oder nicht, ist egal, da die Bestätigung von Mailcow kommt.

**Comment by FN-Florian** [comment]
Ich habe bei mir keine Konfiguration dahingehend verändert. Sehe ich es richtig das ich lediglich die postfix Konfiguration anpassen muss und anschließend den Container neustarten?

**Comment by mkuron** [comment]
Vielleicht es das bei irgendeiner anderen Änderung in der jüngeren Vergangenheit kaputtgegangen. Da die Dokumentation sich nur auf die Einschränkung von Bestätigungen bezieht und die entsprechende Option bei Mailcow nicht gesetzt ist, ist wohl nicht die Serverkonfiguration schuld. Eventuell helfen die Logs des Postfix-Containers weiter.

**Comment by mkuron** [comment]
Vielleicht es das bei irgendeiner anderen Änderung in der jüngeren Vergangenheit kaputtgegangen. Da die Dokumentation sich nur auf die Einschränkung von Bestätigungen bezieht und die entsprechende Option bei Mailcow nicht gesetzt ist, ist wohl nicht die Serverkonfiguration schuld. Eventuell helfen die Logs des Postfix-Containers weiter.

**Comment by FN-Florian** [comment]
@mkuron : Ich habe lediglich an der SoGo Konfiguration etwas verändert, damit die Domains nicht alle isoliert sind. Anonsten habe ich an der Konfiguration nichts verändert.
Wo finde ich denn die Logs des Postfix-Containers?  Oder ist das der Postfix Log aus Mailcow, da konnte ich nichts passendes erkennen: https://pastebin.com/dEnPrNw4

**Comment by mkuron** [comment]
Ich meinte auch eher Änderungen, die in einem Update kamen. Das Log ist das richtige. Wenn es keinen weiteren Eintrag ein paar Sekunden später gab, ist tatsächlich keine Bestätigung erzeugt worden. Die Ursache ist aber in der Tat nicht ersichtlich.

**Comment by roswitina** [comment]
@mkuron:
Wieder was dazu gelernt. Ich selber verwende Outlook und habe die "Zustellbestätigung" immer angehakt. Ich meinte aber nur von Exchange-Servern eine solche zurück erhalten zu haben. Zumindest ist mir nie aufgefallen, dass ich das von einem Postfix retour bekommen habe. Das werde ich in nächster Zeit nochmals beobachten.

**Comment by mkuron** [comment]
Nur zur Sicherheit: welche Bestätigung meint ihr mit Zustellbestätigung? Es gibt bei Outlook die Lesebestätigung und die Übermittlungsbestätigung. Letztere ist die aus der Postfix-Dokumentation und #362, erstere kann der empfangende Mailclient verschicken, was die meisten nicht standardmäßig tun. So wie ich die Outlook-Dokumentation verstehe, werden die Übermittlungsbestätigungen auch nicht als normale Mails angezeigt, sondern sind über ein Menü aus der gesendeten Nachricht zugänglich.

**Comment by roswitina** [comment]
In der Kombination Outlook / Exchange bekomme ich bei der Anforderung einer Zustellbestätigung ein eigenes Mail retour. Bin jetzt nicht im Büro, sonst könnte ich mir das genauer anschauen.

**Comment by FN-Florian** [comment]
Ich meine die Übermittlungsbestätigung, bisher kam die immer als normale Mail in den Posteingang.

**Comment by mritzmann** [comment]
Ich habe in meinem E-Mail Client (Thunderbird 52.9.1) zwei Optionen:

- Return Receipt
- Delivery Status Notification

Ersteres bewirkt bei mir nichts. Ich gehe davon aus, dass es um zweiteres geht. Beim zweiteren erhalte unmittelbar nach dem Absenden folgendes E-Mail: 

```
Your message was successfully delivered to the destination(s)
listed below. If the message was delivered to mailbox you will
receive no further notifications. Otherwise you may still receive
notifications of mail delivery errors from other systems.

                   The mail system

<opstest@example2.com>: delivery via dovecot[fd4d:6169:6c63:6f77::3]:24: 250
    2.0.0 <opstest@example2.com> MluwMMK/SFtYXQAAVCZe3g Saved

[...]
```

Laut E-Mail Header wird das E-Mail nicht vom eigenen Mailserver erstellt, sondern vom Empfänger versendet, vorausgesetzt ich Interpretiere das richtig.

```
Delivered-To: markus@example.com
Received: from mail.example.com ([172.22.1.1])
	by mail.example.com with LMTP
	id byH2GsK/SFs1BwIAFKQWWA
	(envelope-from <>)
	for <markus@example.com>; Fri, 13 Jul 2018 17:05:38 +0200
Received: from mail.example2.com (mail.example2.com [185.17.70.71])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail.example.com (Postfix) with ESMTPS id 65CF7160B49
	for <markus@example.com>; Fri, 13 Jul 2018 17:05:38 +0200 (CEST)
Received: by mail.example2.com (Postfix)
	id DFDA3168ED3; Fri, 13 Jul 2018 17:05:38 +0200 (CEST)
```

_(example.com bin ich, example2.com der empfänger)_

Beides Mailcow Installationen.

* example.com: version 8adf3d27db128bdeb45290ca9114aff9797f2a91
* example2.com: version cc573358c950d374ee64a1dfa2123b5181868f0b

Scheint also in meiner Konstellation zu funktionieren.

**Comment by mkuron** [comment]
@mritzmann, danke fürs Überprüfen. Return Receipts werden vom empfangenden Mailclient verschickt, und das ist dort meist deaktiviert.

Soweit ich das im Kopf habe, sollte die DSN aber eigentlich von example.com verschickt werden, d.h. DSNs sollten nicht übers Internet gehen. Sie werden also an dem Punkt verschickt, nach dem der fremde Mailserver zuständig ist.
Vermutlich haben wir also irgendwo einen Konfigurationsfehler, der die DSNs genau bei den falschen Mails verschickt.

**Comment by mritzmann** [comment]
Das [RFC 3464](https://tools.ietf.org/html/rfc3464) liesst sich ziemlich kompliziert. Dort ist von einem [Reporting MTA](https://tools.ietf.org/html/rfc3464#section-1.3) die Rede. Auf welcher Seite der Reporting MTA steht ist mir aber auf dem ersten Blick nicht ganz klar.

**Comment by lo05** [comment]
เยี่ยมครับแต่กระรุณาเลิกยุุ่งกับผมเถอะขอร้องนะตรับ

**Comment by andryyy** [comment]
At least star the repo, @lo05

**Comment by lo05** [comment]
เดี๋ยวจะส่งซิมไปให้นะครับ ตอนสายๆจะลบเมลทิ้ง
รอให้น้องมันสมัคเมลมันก่อนผมเผอไปลบของมัน เราไม่ต้อุ่นวายกันอีก
ผมรู้ว่าคุณต้องการเห็นผมเดือดร้อน เลยจะชวนเพือนๆพวกคุณมาช่วยช่วยกันแกล้ง
ผมคงเป็นตัวตลกในสายตาพวกคุณ ผมอโหสิกรรมให้ อย่าจองเวรจองกรรมกันเลย
เวรกรรมทุกอย่างผมขอรับไว้เองโชคดีนะครับ
