### ISSUE TITLE
ASN setting not creating certificate for domains

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1479]
Hello,
I added 2 domains to the ADDITIONAL_SAN= setting in mailcow conf. It looks like this:
ADDITIONAL_SAN=git.domain.me,ci.domain.me

But the acme container never creates the certificates for these two domains, when I use the dig command I can resolve them correctly so that shouldn't be the issue. Also they are mentioned no where in the acme logs :( Can you please help me?

**Comment by andryyy** [comment]
Did you run up -d after adding them?

If so, please post acme-mailcow logs. It could be a broken IPv6 config.

**Comment by ntimo** [comment]
Sure, yes I did run up -d after adding them but the it said the acme container was up to date. as you can see git.domain.me is not mententkoned anywhere :(

the git.domain.me and ci.domain.me both use a cname of my mailservers A record like the autoconfig and autodiscover subdomains do, so this should work.

here is the output from acme-mailcow:

acme-mailcow_1       | Wed Jun 13 21:21:59 UTC 2018 - Waiting for Docker API...Found Docker API
acme-mailcow_1       | Wed Jun 13 21:21:59 UTC 2018 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: autoconfig.domain.xyz autoconfig.domain.com autoconfig.domain.de autoconfig.domain2.me autoconfig.domain.me autodiscover.domain.xyz autodiscover.domain.com autodiscover.domain.de autodiscover.domain2.me autodiscover.domain.me mailserver.domain2.me
acme-mailcow_1       | Waiting for database to come up...
acme-mailcow_1       | mysqld is alive
acme-mailcow_1       | Wed Jun 13 21:22:04 UTC 2018 - Waiting for domain table... Found domain tables.
acme-mailcow_1       | Wed Jun 13 21:22:04 UTC 2018 - Found A record for autoconfig.domain.xyz: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:04 UTC 2018 - Confirmed A record autoconfig.domain.xyz
acme-mailcow_1       | Wed Jun 13 21:22:04 UTC 2018 - Found A record for autodiscover.domain.xyz: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Confirmed A record autodiscover.domain.xyz
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Found A record for autoconfig.domain.com: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Confirmed A record autoconfig.domain.com
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Found A record for autodiscover.domain.com: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Confirmed A record autodiscover.domain.com
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Found A record for autoconfig.domain.de: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:05 UTC 2018 - Confirmed A record autoconfig.domain.de
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for autodiscover.domain.de: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record autodiscover.domain.de
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for autoconfig.domain2.me: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record autoconfig.domain2.me
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for autodiscover.domain2.me: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record autodiscover.domain2.me
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for autoconfig.domain.me: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record autoconfig.domain.me
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for autodiscover.domain.me: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record autodiscover.domain.me
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Found A record for mailserver.domain2.me: 78.46.122.40
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Confirmed A record mailserver.domain2.me
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-mailcow_1       | acme-client: acme-client: adding SAN: autoconfig.domain.xyz
acme-mailcow_1       | /var/lib/acme/acme/cert.pem: certificate valid: 77 days leftacme-client:
acme-mailcow_1       | adding SAN: autoconfig.domain.com
acme-mailcow_1       | acme-client: adding SAN: autoconfig.domain.de
acme-mailcow_1       | acme-client: adding SAN: autoconfig.domain2.me
acme-mailcow_1       | acme-client: adding SAN: autoconfig.domain.me
acme-mailcow_1       | acme-client: adding SAN: autodiscover.domain.xyz
acme-mailcow_1       | acme-client: adding SAN: autodiscover.domain.com
acme-mailcow_1       | acme-client: adding SAN: autodiscover.domain.de
acme-mailcow_1       | acme-client: adding SAN: autodiscover.domain2.me
acme-mailcow_1       | acme-client: adding SAN: autodiscover.domain.me
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Verified hashes.
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - Certificate was not changed
acme-mailcow_1       | Wed Jun 13 21:22:06 UTC 2018 - ACME certificate validation done. Sleeping for another day.

**Comment by andryyy** [comment]
Is .env still a symbolic link to mailcow.conf?

Typo in ADDITIONAL_SAN?

It would not ignore that variable. Something is very wrong here.

**Comment by ntimo** [comment]
Okay, I just checked with nano .env and in this file the ADDITIONAL_SAN= record misses the domains set in mailcow.conf so maybe this is the error. How can I recreate the symlink? 

The domain names are spelled correctly :)

**Comment by ntimo** [comment]
Okay I just created the symlink with 
`ln -s /opt/mailcow-dockerized/mailcow.conf /opt/mailcow-dockerized/.env` 
and now it created the docker acme container after running up -d and now it worked :)

**Comment by andryyy** [comment]
Happens mostly when people move/copy the mailcow folder and break the sym link. Always keep the links when moving this folder. :-)
