### ISSUE TITLE
Spark mailclient by Readdle for iOS not sending push notifications 

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1484]
I really love that mail app, but the problem is that it doesnt send me any push notifications. The E-Mails still appear in the inbox of the app and I can view, send and receive E-Mails, but the notification part, does not seem to work. 
Compared with other mail-clients, like the default iOS one or Thunderbird, notifications work perfectly. May be someone else uses that mail client too and made already some experience with it. (I really really like that mail-client and actually I do not wanna stop using it (in the past with my web.de mail, notifications worked too) because of that). On the Readdle website you can't find anything related that, just that you have to enable notifications within the app, what I obviously already tried.

Any help is appreciated.
Thank you !

**Comment by hachre** [comment]
Did you solve it?

I use Spark as well and it works for me. It is just set to only notify about mails that it deems "Private" by default. 

I just saw your other thread and noticed you changed the mail server handling the domain multiple times. This confuses Spark. The notifications are done by them server-side. The solution is to delete your mail account from all your Spark clients. Then wait a while. Then set it up again and give it time to propagate to their backend as well. It all takes a while. Whenever you change the server (by keeping the same mail address but changing server hostname, ip, user or pass), you have to go through this process to update their server-side reliably. Whenever you enable notifications, you opt in to have them access your mail account fully from their servers.

**Comment by xL0b0** [comment]
@hachre Man, thank you very much for that detailed explanation ! Really I appreciate the information you wrote, because now everything makes sense ! After waiting some time, notifications finally work again and I can use spark properly, like before 😃, with removing that A record ! I really love spark and happy that i don’t need to use an alternative any longer.

**Comment by xL0b0** [comment]
@hachre After i deleted all accounts myself (before reading your comment) it appearantly started working again. 
Quick question regarding spark: do you also have the issue that you set the spark notification sound but receive notifications with the default iOS one?

**Comment by hachre** [comment]
@xL0b0 No, the sound is a Spark-specific one for me. Maybe it depends on whether the phone is already unlocked or not when you receive the notification? I'm not entirely sure cause I have mine on silent (vibrate) most of the time.
