### ISSUE TITLE
Getting an automated answer on every E-Mail with SoGo vacation feature

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1486]
Hello ! Quick question: is it possible to get a set response to EVERY E-Mail that is being sent by a user ? Right now I can just get it to work with that feature that I get a respond to my first E-Mail and after that, auto responses stop. Is there any way to change that feature to auto respond to every E-Mail or is that not possible ?

**Comment by hachre** [comment]
I think you simply need to check the "Always send vacation message response" box.

**Comment by xL0b0** [comment]
@hachre Yeah thought that too, I enabled that already but when I send one email, I get a response, if I send a second email, no response is being sent.

**Comment by andryyy** [comment]
Can you show us the sieve filter content for this user? Login as this user to mailcow UI and click to show the filter.

**Comment by andryyy** [comment]
But make sure “always send response” was checked in SOGo before.

**Comment by xL0b0** [comment]
These are my current settings: https://i.imgur.com/w7rocIK.png
Anything wrong about that ?

**Comment by andryyy** [comment]
That’s not what I asked for. :-(

Login to mailcow UI as this mailbox user, select “show active Filter”.

**Comment by xL0b0** [comment]
Oh, excuse me. Didn’t read the message above that, sorry. Will do that later when i‘m back home. 

Edit: this what happens when i click on active filter: https://imgur.com/a/DlqshSW

**Comment by xL0b0** [comment]
@andryyy anything that can be said about that or does that not really help ?

**Comment by hachre** [comment]
@xL0b0: Has the screenshot really been created while the the vacation responder was activated in SOGo?

**Comment by xL0b0** [comment]
@hachre Nah it was created afterwards, but does that make a difference ? Like it is still turned on, does that have any effect on that ?

**Comment by hachre** [comment]
I just tried this out as well and the SOGo filters (even though some are active and working) as well as a test auto responder which I created are not showing up in the Mailcow Admin interface under "Show active user sieve filters". It comes up empty just like on @xL0b0's screenshot. I'm currently running on commit 43a6e24b81be340914a391f66022bff47528f442 from June 8th.

**Comment by andryyy** [comment]
“Nah it was created afterwards, but does that make a difference ?”

You clicked on “show active filter” before setting up the filter?!

—

@hachre I will check it 
Edit: Found the reason it is not displayed. Will fix it when I’m home from vacation.

**Comment by andryyy** [comment]
Not home from vacation, but should be fixed.

**Comment by xL0b0** [comment]
So this means that this auto response will be fixed soon ? Or is it something else that will be fixed soon and I’m getting something wrong?

**Comment by andryyy** [comment]
Please read it again.

Update and click “show active filter“ again. It should be shown now. 

But create the filter **BEFORE** you click on „show active filter“.

**Comment by xL0b0** [comment]
Yeah, I created the filter a while back already before clicking on that.
Lookin now like this: https://i.imgur.com/2JJUhF9.png after updating.
In theory, every E-Mail should be answered automatically, shouldn't it ?

**Comment by andryyy** [comment]
It has the “days 1” parameter applied to it, so it will only send once a day. Can anybody confirm SOGo creates the filter as it is shown in the screenshot, even when you select “always send reply”?

**Comment by xL0b0** [comment]
Yeah, that was the thing I worried about. This "days 1" thing, sadly you can't turn that off ? (Or maybe you can, but I dont know how)

**Comment by andryyy** [comment]
You should file a bug to SOGo when others confirm this is what SOGo sets up as filter.

**Comment by xL0b0** [comment]
Alright. If SoGo would update it, how am I going to update my SoGo, just with the update functionality of mailcow update or is there an external update just fo SoGo?

**Comment by hachre** [comment]
It's confirmed: The days parameter is added to the resulting sieve rule no matter whether that SOGo checkbox is on or off. 

@xL0b0: When a new SOGo is released and added to Mailcow, all you'll have to do is run the normal Mailcow update. Please report it to them here: https://sogo.nu/bugs/

SOGo bug have been filed and can be found here:
https://sogo.nu/bugs/view.php?id=4490
https://sogo.nu/bugs/view.php?id=4499

**Comment by xL0b0** [comment]
I really hope they will fix that, as I'm running a small business and such an automated E-Mail response to EVERY E-Mail is quite essential. Sadly I didn't see any sign that this was either viewed or will be fixed. I submitted a second more compact version, hoping that this is going to be acknowledged.

**Comment by andryyy** [comment]
It is quite unusual to send an auto-response to _every_ of the same sender.

If you run a business, get a SOGo commercial subscription, they will probably fix it very fast. Or just use mailcow UI and setup a filter.

**Comment by xL0b0** [comment]
Yeah, but that's what I want, let the sender know that the E-Mail was received successfully (that's just my personal preference :D) 

Do I have to set up such a filter in the Admin account for mailcow or in the individual account I want to have it for ? As I can't find it right now :| There's no way to modify the active filters myself, is it ?

**Comment by xL0b0** [comment]
?

**Comment by andryyy** [comment]
Sorry. You can edit the SOGo filter with an editor inside the users mail_home. Or just use the admin UI. The filter section is in „Mailbox“.

**Comment by andryyy** [comment]
You can also just create an auto-reply for the time of the vacation...

**Comment by xL0b0** [comment]
How can I specify with a sieve rule that it responds to every mail ? If I enable or disable, "always respond" nothing itself changes in the rule (as this issue already says it more or less)

**Comment by andryyy** [comment]
mailcow UI -> /mailbox.php -> Filters.

You can create filters here.

I think you can create an auto-reply rule in SOGo, too. But I'm not sure.

I cannot make changes to SOGo. You need to report them and wait or get a subscription.

**Comment by xL0b0** [comment]
Yes, I know where to make those rules know, but do you maybe know how I can implement it instead of the days that I have right now in my rule: 

> require ["vacation","variables"];
> if header :matches "Subject" "*" { set "subject" "${1}"; } vacation :days 1 :subject "${subject}" :addresses ["email@mail.com"] text:
> Your mail was received successfully and will be answered within 24 hours.
> 
> Best regards,
> ... Team
> .
> ;


Replace that part with the "always respond". Is there any parameter or anything like that may be ? (as I don't really understand how to handle those things and I don't really understand the documentation of that too, looked that up already)

**Comment by andryyy** [comment]
Not sure if days is optional. :-/ 
We could add "vacation_seconds" (or somthing like that) to the sieve extensions and create a check for that in the PHP library.

**Comment by xL0b0** [comment]
Yeah, may be, hope this helps in any way, as I don't understand anything of PHP 😅 
Sad thing is just, if you enable the always respond option, the rule for it isn't written, so I got nothing I could look for, to copy it into the new rule I can create in the Admin panel. (Hope my current problems becomes a bit more clear with that addition)

**Comment by andryyy** [comment]
Or try this...

Add to plugin { } in dovecot.conf =>
```
  sieve_vacation_min_period = 50s
  sieve_vacation_max_period = 0
  sieve_vacation_default_period = 60s
```
and restart dovecot-mailcow.

Skip the days parameter in the filter script (example - untested...):
```
require ["vacation"];
vacation
  :subject "Out of office reply"
"I'm out of office, please contact Joan Doe instead.
Best regards
John Doe";
```

**Comment by xL0b0** [comment]
With the second method sadly, just one E-Mail is being auto answered, I'll try the first one now. If I added that, what am I exactly going to be able to do?

**Comment by xL0b0** [comment]
Okay added it, not really sure what I'm able to do now. I understand what these lines are supposed to do, but not really where I could implement that.

**Comment by andryyy** [comment]
I don't understand what you mean. What did you try now?

**Comment by xL0b0** [comment]
I tried the rule you posted down below, that does not work. (U also added to it untested). Now I’m asking myself, after I added the things into the Dovecot.conf file, what am I supposed to do now or rather, what am I able to do now?

**Comment by xL0b0** [comment]
So could I implement it into a filter that the vacation time is set to seconds instead of days ?

**Comment by hachre** [comment]
Yes, you need to make those proposed Dovecot changes and then try with a filter as shown above. It should send mails every minute then at least.

**Comment by xL0b0** [comment]
I looked things up here: https://wiki2.dovecot.org/Pigeonhole/Sieve/Extensions/Vacation
My plugin section now looks like this: https://i.imgur.com/Bcy80dP.png
I added "sieve_extensions = +vacation-seconds" to the config too. Why am I still receiving that error telling me that I can't use the second parameter instead of days ? https://i.imgur.com/xDpEHVx.png

**Comment by xL0b0** [comment]
Thats kinda weird.

**Comment by hachre** [comment]
Just leave it out of the filter - changing those settings should automatically make it use 60 seconds I think.

**Comment by xL0b0** [comment]
The entire days parameter ? Making it look like that ? https://i.imgur.com/M8N5JGz.png

**Comment by xL0b0** [comment]
Also after doing that I'm just getting one response, why ? 😞 Doesn't make any sense to me.

**Comment by andryyy** [comment]
Have you set the Dovecot parameters in the plugin section? And restarted Dovecot?

**Comment by xL0b0** [comment]
Please explain that Dovecot Parameters part, may be I forgot about that (not sure rn ??) and yes I restarted it after every change.

**Comment by hachre** [comment]
```
  sieve_vacation_min_period = 50s
  sieve_vacation_max_period = 0
  sieve_vacation_default_period = 60s
```

These are the Dovecot parameters we're talking about... Are they applied right now?

**Comment by xL0b0** [comment]
As I posted it above, with the title "My plugin section now looks like this" and the screenshot, following after it, yes it does.

**Comment by hachre** [comment]
Just to make double sure, can you post the output of:
```
docker-compose exec dovecot-mailcow doveconf -a | grep sieve_vacation
```

**Comment by xL0b0** [comment]
@hachre https://i.imgur.com/4bcn0hg.png

**Comment by hachre** [comment]
Okay, then we'll need to wait for better ideas by @andryyy, if he's got any...

**Comment by xL0b0** [comment]
Alright. Still, thank you very much for the help, I appreciate that !

**Comment by xL0b0** [comment]
Something that doesn't really make sense to, if I add "sieve_extensions = +vacation-seconds" to the plugin section and restart dovecot, it theoretically should accept the requirement "vacation-seconds" in the script, but it doesn't. That was the problem of many people, that they forgot about the (looked that up on the Dovecot website), but that does not seem to help. It still says it can't find the quoted string "vacation-seconds", so obviously, I can't use ":seconds" too in the script, which is kind of confusing why this doesn't work.

**Comment by hachre** [comment]
Maybe it's a feature that needs to also be enabled at compile-time and might thus be missing from the Docker image that Mailcow is shipping for Dovecot. I don't know these specifics, can only speculate here.

**Comment by xL0b0** [comment]
Yeah, I guess André would need to help at that point, as he's the developer and knows more about that I think.

**Comment by andryyy** [comment]
The PHP library needs to be updated to accept vacation seconds. 

I’m really busy atm but will add it sooo ...

**Comment by xL0b0** [comment]
Alright. So I will be able to add vacation-seconds to the requests after the next update (if its implemented by then) ?

**Comment by andryyy** [comment]
Yes, I will test it.

**Comment by xL0b0** [comment]
Alright, thank you very much !

**Comment by xL0b0** [comment]
Can an update still be expected for that or should I wait rather for SoGo, as the status of my bug report changed to "acknowledged".

**Comment by hachre** [comment]
Your bug at SOGo was acknowledged but the bad news is, it is nothing more than a misunderstanding of what that option is supposed to do. Your desired behavior is not supported apparently. 

https://sogo.nu/bugs/view.php?id=4499#c12937

**Comment by andryyy** [comment]
I think "always respond" is not supported by vacation. Except for vacation-seconds, where you can kind of trick it.

**Comment by xL0b0** [comment]
Could you still implement that fix you hinted at, so I could use vacation-seconds ? As it is not possible right now so I could somehow still achieve what I would like to have ?

**Comment by xL0b0** [comment]
?

**Comment by andryyy** [comment]
Yes, I can add it. But I don't have much time at the moment and - remember - I am not paid to work on mailcow.

**Comment by xL0b0** [comment]
Yeah, just wanted know in general, if this was possible.

**Comment by xL0b0** [comment]
@andryyy Haven’t looked in the commits for quite a while. Was there already the time to find a fix for the thing you described ?

**Comment by andryyy** [comment]
No. But I did it anyway.

```
require ["vacation-seconds"];

vacation
  :seconds 10
  :subject "Out of office reply"
  :addresses ["j.doe@company.dom", "john.doe@company.dom"]
"I'm out of office, please contact Joan Doe instead.
Best regards
John Doe";
```

That's the script I tested.

Will push the changes in a bit.

**Comment by xL0b0** [comment]
@andryyy Alright. I tested it now and it is working perfectly ! Thank you very much. Every mail is being answered now immediately thanks to this update. I can now happily close this issue.
