### ISSUE TITLE
Recipient maps works incorrectly 

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1487]
Hi There,

Recipient maps works incorrectly 
i use Recipient map with 3 "New recipient"_'s_ - but only first user received the messages

the result is reproducible

**Comment by andryyy** [comment]
?

**Comment by proea** [comment]
@andryyy, Recipient map example:

original recipient        |  new recipient
user@domain.com -> user1@domain.com, user2@domain.com, user3@domain.com

if I send an email to user@domain.com then only user1@domain.com will receive an email

**Comment by andryyy** [comment]
Need more information about he exact map. Best would be a dump from sql (alias table). This is not reproducible here and would not have gone unnoticed. 

We also need logs of postfix-mailcow the moment it happens. It will tell you exactly why it did not address any second or third rcpt.

**Comment by proea** [comment]
@andryyy can i sent it to your email ?

**Comment by andryyy** [comment]
Yes, but please post the logs here first.

**Comment by andryyy** [comment]
Besides the logs, please also tell us where the three destinations point to. Are they aliases on mailcow? External addresses?

**Comment by proea** [comment]
they are internal addresses

and I tried an external addresses .. the same result

i'll post the logs a bit later

**Comment by andryyy** [comment]
@mkuron Can you confirm this?! I’m on holiday + mobile.

**Comment by proea** [comment]
@andryyy @mkuron which logs do you need? (which services)

**Comment by mkuron** [comment]
`docker-compose logs --tail=0 -f postfix-mailcow`, then send a message to user@domain.com, then hit Ctrl-C to exit and post the logs here. Do any of the target addresses contain non-ASCII characters (e.g. umlaut, Chinese) or special characters other than dots, dashes and underscores?

**Comment by tkorves** [comment]
@proea : Can't confirm this behavior - just tested it like you said.

Created an alias test-alias@domain.net, pointed it to test2@domain.net, test3@domain.net and test4@domain.net, sent an eMail to this alias - et voila, all three recipients received the eMail. Can you please post logs like @mkuron asked you to do?

postfix-mailcow_1    | Jun 17 20:00:08 mail postfix/lmtp[18098]: 21C57C009E: to=<test2@domain.net>, orig_to=<test-alias@domain.net>, relay=dovecot[172.22.1.3]:24, delay=0.24, delays=0.08/0.01/0.01/0.14, dsn=2.0.0, status=sent (250 2.0.0 <test2@domain.net> UCixDaihJlsmcgAAOoLqhg Saved)
postfix-mailcow_1    | Jun 17 20:00:08 mail postfix/lmtp[18098]: 21C57C009E: to=<test3@domain.net>, orig_to=<test-alias@domain.net>, relay=dovecot[172.22.1.3]:24, delay=0.24, delays=0.08/0.01/0.01/0.14, dsn=2.0.0, status=sent (250 2.0.0 <test3@domain.net> UCixDaihJlsmcgAAOoLqhg:2 Saved)
postfix-mailcow_1    | Jun 17 20:00:08 mail postfix/lmtp[18098]: 21C57C009E: to=<test4@domain.net>, orig_to=<test-alias@domain.net>, relay=dovecot[172.22.1.3]:24, delay=0.24, delays=0.08/0.01/0.01/0.14, dsn=2.0.0, status=sent (250 2.0.0 <test4@domain.net> UCixDaihJlsmcgAAOoLqhg:3 Saved)

**Comment by proea** [comment]
@andryyy @mkuron @tkorves 
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/postscreen[1434]: CONNECT from [xx.xx.xx.xx]:35988 to [172.22.1.9]:25
postfix-mailcow_1    | Jun 17 20:33:48 mcx whitelist_forwardinghosts: Look up xx.xx.xx.xx on whitelist, result 200 PERMIT
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/postscreen[1434]: WHITELISTED [xx.xx.xx.xx]:35988
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/smtpd[1448]: connect from mailgateway.domain.com[xx.xx.xx.xx]
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/smtpd[1448]: Anonymous TLS connection established from mailgateway.domain.com[xx.xx.xx.xx]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/smtpd[1448]: 89C4E1FCF4: client= mailgateway.domain.com[xx.xx.xx.xx]
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/cleanup[1457]: warning: 89C4E1FCF4: multi-valued recipient_canonical_maps entry for _test@domain.com_
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/cleanup[1457]: 89C4E1FCF4: message-id=<D68453AA-0681-41D1-AC6E-26C4C15C6F9A@gmail.com>
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/qmgr[331]: 89C4E1FCF4: from=<user@gmail.com>, size=4144, nrcpt=1 (queue active)
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/smtpd[1448]: disconnect from mailgateway.domain.com[xx.xx.xx.xx] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/lmtp[1458]: 89C4E1FCF4: to=<info@somedomain>, orig_to=<_test@domain.com_, relay=dovecot[fd4d:6169:6c63:6f77::f]:24, delay=0.38, delays=0.22/0.02/0.05/0.09, dsn=2.0.0, status=sent (250 2.0.0 <_info@domain.com_> xG4rMYypJlvfFgAA6rQxlw Saved)
postfix-mailcow_1    | Jun 17 20:33:48 mcx postfix/qmgr[331]: 89C4E1FCF4: removed


**Mailcow UI**:
_Recipient maps_
Original recipient: test@domain.com
New recipient: info@domain.com,user@otherdomain.com,gmailuser@gmail.com

info@domain.com - internal account
user@otherdomain.com - internal account
gmailuser@gmail.com - external account

_Recipient maps_ is used (Address rewriting tab) (not alias)
as you can see from the logs - the message was delivered only to the first recipient, 2 others did not receive the letter

**Comment by mkuron** [comment]
`warning: 89C4E1FCF4: multi-valued recipient_canonical_maps entry for test@domain.com` sounds like Postfix doesn’t officially support this. I couldn’t find a place in the documentation where it says that this should or shouldn‘t work though.

**Comment by mkuron** [comment]
Duplicate of #1576
