### ISSUE TITLE
Fresh install: Database don't work

### ISSUE THREAD

**Issue by Tagadda** [mailcow/mailcow-dockerized#1488]
Hey, I've just completed a fresh install of mailcow.
Every container seems to start correctly, but when I try to access the web front end, I have a 504 Gateway Time-out from my reverse proxy.
I have a lots of errors about 3 tables from php-fpm-mailcow.
```
php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.domain' doesn't exist
php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.alias_domain' doesn't exist
php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.api' doesn't exist
```
Do you have any idea on what I've done wrong ?

**Comment by mkuron** [comment]
Make sure API_KEY and API_ALLOW_FROM are not set in mailcow.conf, this is currently broken: https://github.com/mailcow/mailcow-dockerized/issues/1457#issuecomment-396560376

**Comment by andryyy** [comment]
And check if a local firewall is active, please. ufw, firewalld etc. - or just your own ruleset. 

I will fix that API stuff when I’m back home.

**Comment by Tagadda** [comment]
Well, when I empty the API_KEY and API_ALLOW_FROM i have this error : 
`ERROR: Invalid interpolation format for "environment" option in service "php-fpm-mailcow": "API_KEY=${API_KEY:-}"`

**Comment by mkuron** [comment]
If you see that message, you need to update docker-compose: https://github.com/mailcow/mailcow-dockerized/issues/1468#issuecomment-395843341
