### ISSUE TITLE
How to whitelist domain becuase arrive in junk !

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#1490]
Please,
how to allow/whitelist whole domain in mailcow that received legal mail don't go into SPAM.

On example, I'm receive mail from one domain but from sevearl users @example.com and all they mails goes to spam.
How to whitelist whole domain example.com

Thank you.

**Comment by andryyy** [comment]
Can you show the headers of one of those mails, please? Want to check the symbols. 

You can add a bl/wl item to a domain. Just edit a domain and you will find the possibility close to the bottom of the page. 

There are other ways like using multimap functionality. There are issues with examples for this. I cannot search for them. I’m on vacation and on mobile. 

It is pretty easy though. :-)

**Comment by petarkozic** [comment]
Great ! Thanks on answer. Resolved !

**Comment by petarkozic** [comment]
@andryyy 
I need urgent response please. Some mails from one domain goes to SPAM constantly. 
I whitelist whole domain with *.mydomain.com and also I added problematic email in whitelist mail@mydomain.com

But, again every mail from that domain goes to spam. Please tell me how can I resolve this issue, does I need to restart container maybe after whitelist ?
Thanks.

**Comment by andryyy** [comment]
There is a mailcow support info at mailcow.email if it is urgent and needs a fast response...

We need headers of the mail that goes to junk and the Rspamd settings map (at least the whitelist part).

**Comment by petarkozic** [comment]
@andryyy 
Here is from rspamd debug

![screen shot 2018-06-26 at 10 33 17 am copy](https://user-images.githubusercontent.com/17702869/41899447-be19cc80-792c-11e8-9d21-8d47efc46a43.png)

This is from multimap.conf:

`RCPT_MAILCOW_DOMAIN {
  type = "rcpt";
  filter = "email:domain";
  map = "redis://DOMAIN_MAP";
  symbols_set = ["RCPT_MAILCOW_DOMAIN"];
}

RCPT_WANTS_SUBJECT_TAG {
  type = "rcpt";
  filter = "email:addr";
  map = "redis://RCPT_WANTS_SUBJECT_TAG";
  symbols_set = ["RCPT_WANTS_SUBJECT_TAG"];
}

RCPT_WANTS_SUBFOLDER_TAG {
  type = "rcpt";
  filter = "email:addr";
  map = "redis://RCPT_WANTS_SUBFOLDER_TAG";
  symbols_set = ["RCPT_WANTS_SUBFOLDER_TAG"];
}

WHITELISTED_FWD_HOST {
  type = "ip";
  map = "redis://WHITELISTED_FWD_HOST";
  symbols_set = ["WHITELISTED_FWD_HOST"];
}

KEEP_SPAM {
  type = "ip";
  map = "redis://KEEP_SPAM";
  action = "accept";
  symbols_set = ["KEEP_SPAM"];
}

LOCAL_BL_ASN {
  require_symbols = "!MAILCOW_WHITE";
  type = "asn";
  map = "$LOCAL_CONFDIR/custom/bad_asn.map";
  score = 5;
  description = "Sender's ASN is on the local blacklist";
  symbols_set = ["LOCAL_BL_ASN"];
}

#SPOOFED_SENDER {
#  type = "rcpt";
#  filter = "email:domain:tld";
#  map = "redis://DOMAIN_MAP";
#  require_symbols = "AUTH_NA | !RCVD_VIA_SMTP_AUTH";
#  symbols_set = ["SPOOFED_SENDER"];
#}`

**Comment by andryyy** [comment]
The settings map from debug.

It is missing the settings map and the mail header.

**Comment by andryyy** [comment]
Please mail me the mail header (need it uncensored) and the settings map.

**Comment by petarkozic** [comment]
@andryyy 
Sorry,
in meantime I restarted rspamd container and after restart I can see whitelist in rspamd conf (from debug)
Before restart I don't see that in debug.

**Comment by andryyy** [comment]
I think that’s something that was fixed in a newer Rspamd version. Can you please run update.sh? It shouldn’t ever be necessary to restart Rspamd then.

**Comment by petarkozic** [comment]
Ok, I will check ! Thanks you. I'm sent mail to you.
Thanks !
