### ISSUE TITLE
ECC Certificates

### ISSUE THREAD

**Issue by carwynR** [mailcow/mailcow-dockerized#1491]
Hello,

mailcow does not support ECC Certificates.

Postfix: `warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1404:`

**Comment by lismueller** [comment]
I don´t know how to fix this

**Comment by andryyy** [comment]
Can you test again after update?

**Comment by lismueller** [comment]
@andryyy I am using the latest mailcow, the issue persists
