### ISSUE TITLE
SSL certificate issues

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#1493]
I noticed my SSL certificate had expired, so I ran `docker-compose logs acme-mailcow` to find an error: 
`Error creating new cert :: Too many certificates already issued for exact set of domains`.

I tried adding a new domain to the `ADDITIONAL_SAN` variable to get around this, however I get the same error as above, and the new domain isn't listed in the logs when I restart `acme-mailcow`.

It seems `acme-mailcow` is trying to renew the certificates too many times, and it also seems it's ignoring `ADDITIONAL_SAN` entries.

Currently, I am unable to use my mailserver due to this issue.

**Comment by EnriqCG** [comment]
Can you please check Certificate Transparency logs for your domain in [crt.sh](https://crt.sh) to check how many certificates have been issued in the last 7 days.

**Comment by MrSuttonmann** [comment]
It's got 8 renewals logged in the last 7 days.

**Comment by EnriqCG** [comment]
You are being rate limited by LE (check https://letsencrypt.org/docs/rate-limits/ for further info). Is the `acme-mailcow` container the only issuer or are you issuing certs with an ACME client (i.e cerbot) anywhere else?

**Comment by andryyy** [comment]
We would also need logs of acme-mailcow. It does not ignore additional SAN when it (mailcow plus DNS) is correctly setup. 

Full logs over the past 7 days or so will help. :-)

**Comment by MrSuttonmann** [comment]
`acme-mailcow` on this server _should_ be the only server requesting certificates for this domain. I do not run any other ACME clients.

I don't think I can get logs further back than today as I did run an update this morning, but the logs I do have are available here: http://paste.debian.net/1030187

**Comment by andryyy** [comment]
Do you have more logs now? You could stop acme-mailcow for a day or two, delete data/assets/ssl and restart it.
