### ISSUE TITLE
Recreated domain administrator not visible in backend

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1494]
After deleting and recreating a domain administrator, the account is not visible in the backend and cannot be edited or deleted. Creating the account again leads to a error message. "Object ACCOUNT already exists". It's a fresh debian 9 installation.

Is there a way to delete the account or make the account visible in the backend?

**Comment by andryyy** [comment]
Hi,
Cannot reproduce this.
What exactly did you do? Did you change anything in the database? Did you set superadmin = 1 or something like that?
Was there a name collision between domain admin and admin?

**Comment by ghost** [comment]
1. I created a account named demo
2. later I deleted the account 
3. I recreated the account demo

The Account issn't visible in the backend but it is in the database and i can login. 

![backend](https://user-images.githubusercontent.com/10342115/41811052-9805786c-7708-11e8-992a-1af92f9748b8.png)
![mysql](https://user-images.githubusercontent.com/10342115/41811054-981fc910-7708-11e8-9a70-ea78e2a4127b.png)

A few minutes ago i created the account demo2 and removed it. Recreating it is possible... Maybe i did somting i can't remeber. Can i just remove the account demo from the database?

**Comment by andryyy** [comment]
Was TFA enabled for "demo"?

You should be fine running:
```
DELETE FROM `domain_admins` WHERE `username` = 'demo';
DELETE FROM `admin` WHERE `username` = 'demo';
DELETE FROM `tfa` WHERE `username` = 'demo';
```

**Comment by ghost** [comment]
No, never activated TFA for any account since installing mailcow. Your querys fixed it. I can now create, delete and recreate the demo account. Thank you.
