### ISSUE TITLE
Network related questions running mailcow-dockerized in VM

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#1496]
Hi,
I'm running Docker in a VM (KVM). This VM's network is in DMZ with restrictive firewall filters.
The firewall filters itself are defined on the router.
In addition there's a reverse proxy for directing network traffic to dedicated server depending on the subdomain.

Question:
Which firewall rules must be applied when mailcow-dockerized is deployed to this VM?
Or should I define another network zone in the firewall for the docker network?
What must be considered for reverse proxy? Should the network traffic be directed to this VM?

THX

**Comment by tkorves** [comment]
Name       : Ports_Mailserver
Type       : port
Description: Mailserver Ports
Members    :
             25
             80
             110
             143
             443
             465
             587
             993
             995
             4190

All of those are needed and of Protocol TCP. Hope that helps. Another thing is, that an additional reverseproxy isn't the best idea to be put in front of Mailcow.

**Comment by cmonty14** [comment]
How should the incoming traffic being directed to mailcow w/o reverse proxy?

**Comment by tkorves** [comment]
It's a DMZ - that's all we know about it. So I gave you the details, which are quite standard.

You've got, depending on your network architecture, several possibilities.

1) You've got public IPs running in your DMZ and need to create corect firewalling rules.
2) You've got internal RFC1918 IP addresses running in your DMZ and you need to a) create correct firewalling routes AND b) a SNAT/DNAT with a public IP address assigned (translated) to your internal Mailcow IP address. In this case, you need to take care of real SNAT/DNAT - do not proxy anything!
3) ...

**Comment by cmonty14** [comment]
Well.
I have (obviously) only 1 public IP; therefore I need a reverse proxy.
Depending on the FQHN the request is redirected to the relevant server.
In my network architecture DMZ is in network segment 10.0.0.0/24.
The VM hosting Docker and consequently mailcow-dockerized is reachable on IP 10.0.0.10.
However, the mail services are running on another IP segment.
This raises the question how I can reach IMAP, SMTP etc. in mailcow-dockerized when running in a VM?
