### ISSUE TITLE
message sending failed: 4.7.1 Ratelimit \"user\" exceeded (451)

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#1497]
Hello,

I using SMTP for sending mails trought my forum-software and there i get sometimes the folling error:
message sending failed: 4.7.1 Ratelimit \"user\" exceeded (451)

Where can i setup the ratelimit and how much must that be to not have troubles? :)

Thanks in advance.

**Comment by andryyy** [comment]
Hi,
Should be fixed now. :-) Can you check and report back?

**Comment by omexlu** [comment]
Hi,
Will do a update the next week and let you know :) 

Thank you.

**Comment by omexlu** [comment]
I have update now, if i get these errors again these days i will notice you :)

**Comment by andryyy** [comment]
Thank you!

**Comment by omexlu** [comment]
Hi,

Seems to be fixed now, no more errors in the logs :)
