### ISSUE TITLE
Dovecot gets restarted by watchdog every 10/15m

### ISSUE THREAD

**Issue by Geitenijs** [mailcow/mailcow-dockerized#1498]
Hello,

I have a problem with dovecot/watchdog, every time dovecot logs the following message, watchdog will register it as an error:

managesieve-login: Disconnected (no auth attempts in 2 secs): user=<>, rip=172.22.1.6, lip=172.22.1.2

However, that doesn't look like an error to me. I could be wrong though, can you help me out?

Thanks in advance!

**Comment by andryyy** [comment]
No, it does not register it as error. There is something else wrong with Dovecot.

Please first provide any changes to Dovecot (`git diff origin/master data/conf` for example).

**Comment by Geitenijs** [comment]
These are the modifications to my Dovecot configuration file:

+login_greeting = Hello

-ssl_cipher_list = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA
+ssl_cipher_list = ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:!aNULL

**Comment by andryyy** [comment]
Try without login_greeting - I think watchdog checks the banner.

**Comment by Geitenijs** [comment]
That worked, thanks!

**Comment by Geitenijs** [comment]
It actually didn't, the same issue returned. Haven't made any modifications since.

It's a lot less frequent though.

EDIT: seems to be gone again, I'll watch it closely

**Comment by andryyy** [comment]
It is possible it reached 0 points in the monitoring score and just waited for the next check. So a small delay would be "ok".

**Comment by Geitenijs** [comment]
After a full restart of mailcow-dockerized the issue completely disappeared.
