### ISSUE TITLE
Can I expose statistic over some port and expose to host ?

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#1501]
Hi guys, 
because I using software for monitoring I need statistics port expose to host machine.
Where and how to add that in dovecot.conf and that tell me does it possible ?
Thanks.

**Comment by andryyy** [comment]
Hm, doveadm is exposed by default, but the new stats plugin does not collect any info by default: https://wiki2.dovecot.org/Statistics

Can be enabled though. Does not look too hard.
