### ISSUE TITLE
Service rspamd-mailcow shows wrong time in the container

### ISSUE THREAD

**Issue by jhahn64** [mailcow/mailcow-dockerized#1502]
Hi,
Service rspamd-mailcow shows wrong time in the container. Symbolis link in the container is dead:
ls -la /etc/localtime -> /usr/share/zoneinfo/Etc/UTC

Directory /usr/share/zoneinfo does not exsist , because package tzdata in the container is not installed:
dpkg -s tzdata
dpkg-query: package 'tzdata' is not installed and no information is available

TZ variable in .env file is set:
TZ=Europe/Berlin

The other containers show right time.
How can I correct that? Because  the logfiles from rspamd  show wrong time.
This is a fresh install on CentOS7

Thank you

**Comment by andryyy** [comment]
Hi,
Thanks, I fixed this. 👍
