### ISSUE TITLE
How to stop scanning for outbound mails and just keep DKIM signing? 

### ISSUE THREAD

**Issue by adityadhawan22** [mailcow/mailcow-dockerized#1503]
How to stop rspamd from scanning outbound mails and just keep DKIM signing? 
I have clamav service stopped.

**Comment by andryyy** [comment]
We just added this. See configuration tab. :-)

You can add a new settings map and select the template there.

**Comment by adityadhawan22** [comment]
Thanks :)

**Comment by igorakkerman** [comment]
Is there a similar template to stop inbound mails from being scanned?

**Comment by andryyy** [comment]
Make sure you update mailcow (last commit from a few mins ago) and apply:

![grafik](https://user-images.githubusercontent.com/2972950/54026945-f656cd00-419f-11e9-92f2-02ab14eceb0a.png)

**Comment by andryyy** [comment]
Or `rcpt = ".*@domain\.tld";`

**Comment by igorakkerman** [comment]
Thank you!

**Comment by igorakkerman** [comment]
Unfortunately, the setting doesn't seem to work. I tried various regular expressions and even removing the `recpt` line as condition.
Maybe there is a way to disable rspamd in postfix while keeping DKIM signing in place?

**Comment by andryyy** [comment]
Tested it successfully. Check your whole settings map. Perhaps another rule has a higher priority.

**Comment by igorakkerman** [comment]
I removed all rules but this one:
```
rcpt = ".*@mydomain\.de";
want_spam = yes;
```
No prioritization whatsoever. 
Can I reset the settings of _only_ rspamd to defaults?
How do you test the functionality? Do you produce spam mail from another account? ;)

**Comment by andryyy** [comment]
Map active:
![grafik](https://user-images.githubusercontent.com/2972950/54074307-4792b980-4291-11e9-849b-48c0af0b3edc.png)

Map inactive:
![grafik](https://user-images.githubusercontent.com/2972950/54074305-43669c00-4291-11e9-875f-49708aa27702.png)

Are you sure your mailcow is up-to-date?

Try "rcpt_mime" instead of "rcpt" if the rcpt is only in the "To: " header field.

It also takes a few seconds to be applied, Rspamd reads the settings map in intervals.

**Comment by igorakkerman** [comment]
Ok, found the issue. When hsj

**Comment by igorakkerman** [comment]
Ok, found the issue. With a concrete address, you can use
```
rcpt = "me@domain.tld"
```
With a regex, you have to write
```
rcpt = "/.*@domain\.tld/"
```
