### ISSUE TITLE
mx domain different mail-address

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#1504]
Hi folks,

I use a VPS for my mailcow mailserver.
The domain for the for the mailserver is mail.mymailserver.de
I create all DNS listings from the mailcow install howto.
All works fine!

But, how is this when I create an other domain for the email address e.g name@domain.de

I must create a new domain in mailcow UI. right?
I must create a new DKIM for domain.de. right?

And now the DNS???

Which listings I got to for domain.de

regards
jm3west

**Comment by mitchellurgero** [comment]
Yes domain.de will need it's own records, specifically it will need autoconfig, and MX records, SPF, and DKIM.

**Comment by jm3west** [comment]
Thank you for your response,

is the autoconfig a CNAME to mail.mymailserver.de?

**Comment by mitchellurgero** [comment]
Yes it would be something like:

`autoconfig    IN CNAME   mail.mymailserver.de` Of course registrar may vary.

**Comment by mitchellurgero** [comment]
MX for domain.de should be mail.mymailserver.de also.

**Comment by jm3west** [comment]
OK thanks,

a last question.
When I don't use a mail address in mailserver self need the mailserver self DKIM, SPF, too

Or just DKIM, SPF for the domain.de

**Comment by mritzmann** [comment]
> Or just DKIM, SPF for the domain.de

yep, only for the domain that sends emails

**Comment by jm3west** [comment]
So, I'm at the finish.

I created a TXT-record (SPF) \
I created a TXT-record (_dmarc) \
I created a TXT-record (dkim) \
I created a MX-record (to mail.mailserver.de) in DNS-zone for domain.de

I deleted the TXT-record (SPF) \
I deleted the TXT-record (_dmarc) \
I deleted the TXT-record (dkim) in DNS-zone for mailserver.de
just because no email-addresses.

mxtoolbox.com said all is good and mail-tester.com gives me 10/10

**Comment by mritzmann** [comment]
SPF and co are only _necessary_ for the domain sending emails. But for unused domains I would still recommend to create the following SPF record.

```dig
v=spf1 -all
```

Does not harm, but prevents someone from sending "valid" mails on behalf of the domain.

> mxtoolbox.com said all is good and mail-tester.com gives me 10/10

:+1:
