### ISSUE TITLE
spam filter: Whitelist does not work as expected

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#1505]
**expected behavior:**

1. Login to MailcowUi
2. Add E-Mail Adresse to Whitelist (Spamfilter -> Whitelist)

X-Spamd-Result gets the following entry: [`MAILCOW_WHITE = -999.0`](https://github.com/mailcow/mailcow-dockerized/blob/b8973648ff0e2a1bf1b1783213b298f287030ca4/data/conf/rspamd/dynmaps/settings.php#L191). The e-mail should not end up in spam.

**my problem**

Emails from senders on the whitelsite sometimes end up in spam. `MAILCOW_WHITE = -999.0` is missing in the e-mail header.

```eml
X-Spamd-Result: default: False [5.01 / 15.00];
	 MID_RHS_MATCH_FROM(0.00)[];
	 URI_COUNT_ODD(1.00)[15];
	 XM_UA_NO_VERSION(0.01)[];
	 BAYES_HAM(-2.50)[100.00%];
	 TO_DN_ALL(0.00)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 R_SPF_NA(0.00)[];
	 IP_SCORE(0.11)[ip: (1.36), ipnet: 185.193.244.0/22(-0.46), asn: 62035(-0.29), country: CH(-0.08)];
	 RCPT_COUNT_ONE(0.00)[1];
	 R_DKIM_NA(0.00)[];
	 GREYLIST(0.00)[pass,body];
	 AUTH_NA(1.00)[];
	 DMARC_NA(0.00)[example.com];
	 ARC_NA(0.00)[];
	 FORGED_RECIPIENTS(2.00)[];
	 RCVD_NO_TLS_LAST(0.00)[];
	 FROM_NO_DN(0.00)[];
	 RCPT_MAILCOW_DOMAIN(0.00)[example.com];
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	 R_UNDISC_RCPT(3.00)[];
	 RCVD_COUNT_THREE(0.00)[3];
	 MV_CASE(0.50)[];
	 ASN(0.00)[asn:62035, ipnet:185.193.244.0/22, country:CH];
	 MX_GOOD(-0.01)[cached: alt1.aspmx.l.google.com]
X-Spam-Flag: YES
X-Spam: Yes
```

----

Does anyone have the same problem, or am I misunderstanding something?

**Comment by andryyy** [comment]
Can you please run update and check again? 

The map update does also need a few seconds to settle.

**Comment by mritzmann** [comment]
> Can you please run update

My test installation is up to date. _([i use the manual way to update](https://mailcow.github.io/mailcow-dockerized-docs/install-update/#manual-update))_

```sh
$ git log -1
commit bb99a8b9783d5818ecb2683529dda571364be43b
Merge: 8937bde 5905a39
Author: Markus Ritzmann
Date:   Tue Jun 26 14:13:15 2018 +0200

    Merge commit '5905a3919ce925993aa030684b293f708ce4b5a4'
```

> The map update does also need a few seconds to settle.

Interesting. It works now on my test installation. On another installation it doesn't work yet -- but there is still an update missing.

I assumed that it generally doesn't work, since it didn't work on my test installation either. I'll update production and reopen if it doesn't work either. Thank you!

**Comment by mritzmann** [comment]
> The map update does also need a few seconds to settle.

@andryyy How long does it usually take? On Production it now works without an update.
