### ISSUE TITLE
Is it possible to move incoming spam messages to the spam folder?

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1506]
I use proxmox mail gateway as an email gateway.
Now quarantine is configured for spam emails, but there is a possibility to change the header (`SPAM: __SUBJECT__`) and Modify Spam Level (`X-SPAM-LEVEL`)

Can the messages be moved to a spam folder with the X-SPAM-LEVEL value automatically?

**Comment by proea** [comment]
@andryyy do you have any information on this issue?

**Comment by mkuron** [comment]
You would need to edit 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/sieve_after
