### ISSUE TITLE
mailcow & acme => no Letsencrypt certificates for mail.<domain>.<tld>

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#1507]
Hi everyone,
first: cool toolset, quick setup, nice to use, was (nearly) easy migration from my old mailserver to this new mailcow-dockerized... but have one issue at the moment and i hope someone can help me and push me in the right direction!?

- Installed a fresh ubuntu 18.04
- did all updates
- did prerequisites
    [Prepare your system](https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-system/)
    [DNS Setup](https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/)

- within DNS Setup i skipped the position "autodiscover" and "autoconfig", also skipped the "The advanced DNS configuration" - was'nt sure if i need all this..
- for DNS i set A, MX, PTR, DKIM, SPF, DMARC

- installed as [mentioned here](https://mailcow.github.io/mailcow-dockerized-docs/install/)

- everything worked and i started to configure domains, create dkim keys, etc...

- after i started to migrate user mailboxes i asked myself if the ssl certificates are correct

- clicked on the "View Website Information" button besides the URL field and it says the LE certificate is valid

- but what about my imap or smtp connections... so i opened a terminal, connect to ubuntu server and run command:
`# docker-compose logs acme-mailcow`
it shows me the following:

> acme-mailcow_1       | Fri Jun 22 09:19:46 UTC 2018 - Waiting for Docker API...Found Docker API
acme-mailcow_1       | mysqld is alive
acme-mailcow_1       | Fri Jun 22 09:19:48 UTC 2018 - Waiting for domain table... Found domain tables.
acme-mailcow_1       | Fri Jun 22 09:19:52 UTC 2018 - Found A record for lxsrv04.sample.de: 173.212.xxx.xxx
acme-mailcow_1       | Fri Jun 22 09:19:52 UTC 2018 - Confirmed A record lxsrv04.sample.de
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: generating RSA domain key
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: generating RSA account key
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 104.109.86.149
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:12f:28e::3a8e
acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:12f:28f::3a8e
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: new-reg
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: lxsrv04.sample.de
acme-mailcow_1       | acme-client: /var/www/acme/OiTfHUdLv_0ZNOUfnYgadALUogJVhVgbaugPom3l1a8: created
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/8_tH67y9ShfakzHukmMoimIKwhvvc2U/5243917188: challenge
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/8_tH67y9Shf98vukmMoimIKwhvvc2U/5243917188: status
acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: certificate
acme-mailcow_1       | acme-client: http://cert.int-x3.letsencrypt.org/: full chain
acme-mailcow_1       | acme-client: cert.int-x3.letsencrypt.org: DNS: 104.109.85.126
acme-mailcow_1       | acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:eb:1b7::ce0
acme-mailcow_1       | acme-client: cert.int-x3.letsencrypt.org: DNS: 2a02:26f0:eb:1ab::ce0
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: linked to cert-1529659203.pem
acme-mailcow_1       | acme-client: /var/lib/acme/acme/chain.pem: linked to chain-1529659203.pem
acme-mailcow_1       | acme-client: /var/lib/acme/acme/fullchain.pem: linked to fullchain-1529659203.pem
acme-mailcow_1       | acme-client: /var/lib/acme/acme/chain.pem: created
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: created
acme-mailcow_1       | acme-client: /var/lib/acme/acme/fullchain.pem: created
acme-mailcow_1       | Fri Jun 22 09:20:03 UTC 2018 - Verified hashes.
acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0     46      0  0:00:01  0:00:01 --:--:--    46
acme-mailcow_1       | Fri Jun 22 09:20:03 UTC 2018 - Restarting 6fa5c2e7f990ae4333f3fbe03892548f8b64fb68fbc1ab6710ed...command completed successfully
acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0     46      0  0:00:01  0:00:01 --:--:--    46
acme-mailcow_1       | Fri Jun 22 09:20:04 UTC 2018 - Restarting 01db7fe5021e34ada6e2141c68f4576a1ded939dbe2273f...command completed successfully
acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
acme-mailcow_1       | Fri Jun 22 09:20:06 UTC 2018 - Restarting 6b48f021542f9bc140dfec0cec1f017891bcabb43099a5...command completed successfully
100    68  100    68    0     0     49      0  0:00:01  0:00:01 --:--:--    49
acme-mailcow_1       | Fri Jun 22 09:20:07 UTC 2018 - ACME certificate validation done. Sleeping for another day.

Later on i saw the following messages within the logfile:

> acme-mailcow_1       | Fri Jun 22 17:43:17 UTC 2018 - Waiting for Docker API...Found Docker API
acme-mailcow_1       | Fri Jun 22 17:43:17 UTC 2018 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: lxsrv04.sample.de
acme-mailcow_1       | mysqld is alive
acme-mailcow_1       | Fri Jun 22 17:43:19 UTC 2018 - Waiting for domain table... Found domain tables.
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - No A record for autoconfig.sample.de found
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - No A record for autodiscover.sample.de found
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - No A record for autoconfig.sample.it found
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - No A record for autodiscover.sample.it found
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - Found A record for lxsrv04.sample.de: 173.212.xxx.xxx
acme-mailcow_1       | Fri Jun 22 17:43:21 UTC 2018 - Confirmed A record lxsrv04.sample.de
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left

I remembered the [DNS Setup](https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/) section from documentation and set autodiscover and autoconfig as TXT record for my domains.
Waited appropriate time and then restarted acme-mailcow as i found in some documentation. What i did get is the following:

> acme-mailcow_1       | Tue Jun 26 14:44:44 UTC 2018 - Waiting for Docker API...Found Docker API
acme-mailcow_1       | Tue Jun 26 14:44:44 UTC 2018 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: autoconfig.sample.de autoconfig.sample.it autodiscover.sample.de autodiscover.sample.it
acme-mailcow_1       | mysqld is alive
acme-mailcow_1       | Tue Jun 26 14:44:46 UTC 2018 - Waiting for domain table... Found domain tables.
acme-mailcow_1       | Tue Jun 26 14:44:47 UTC 2018 - Found A record for autoconfig.sample.de: 173.212.xxx.xxx
acme-mailcow_1       | Tue Jun 26 14:44:47 UTC 2018 - Confirmed A record autoconfig.sample.de
acme-mailcow_1       | Tue Jun 26 14:44:47 UTC 2018 - Found A record for autodiscover.sample.de: 173.212.xxx.xxx
acme-mailcow_1       | Tue Jun 26 14:44:47 UTC 2018 - Confirmed A record autodiscover.sample.de
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Found A record for autoconfig.sample.it: 173.212.xxx.xxx
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Confirmed A record autoconfig.sample.it
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Found A record for autodiscover.sample.it: 173.212.xxx.xxx
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Confirmed A record autodiscover.sample.it
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Found A record for lxsrv04.sample.de: 173.212.xxx.xxx
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Confirmed A record lxsrv04.sample.de
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-mailcow_1       | acme-client: adding SAN: autoconfig.sample.de
acme-mailcow_1       | acme-client: adding SAN: autoconfig.sample.it
acme-mailcow_1       | acme-client: adding SAN: autodiscover.sample.de
acme-mailcow_1       | acme-client: adding SAN: autodiscover.sample.it
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Verified hashes.
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - Certificate was not changed
acme-mailcow_1       | Tue Jun 26 14:44:48 UTC 2018 - ACME certificate validation done. Sleeping for another day.

So, autodiscover and autoconfig TXT records in DNS are found, but what I miss is that there is not mail.sample.de and mail.sample.it generated for the SAN list. 

Also, when i use openssl to query my IMAP or SMTP server with the following command `openssl s_client -starttls smtp -crlf -connect mail.sample.it:25` I do not get a certificate for mail.sample.de within the output of that command but with the servers FQDN

> CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = lxsrv04.sample.de
verify return:1
--
Certificate chain
 0 s:/CN=lxsrv04.sample.de
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
--
Server certificate
-----BEGIN CERTIFICATE-----
MIIJDDCCB/SgAwIBAgISA8wi1BXR+WT8v1aK9cyIt57kMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA2MjYxMzMyNTdaFw0x
ODA5MjQxMzMyNTdaMB4xHDAaBgNVBAMTE2x4c3J2MDQucG9obGUtaXQuZGUwggIi

I think a have a mental blank here... I expected something with my mailservers mail.sample.de address...
Can someone please help me?

Thanks in advance
Markus

**Comment by andryyy** [comment]
autodiscover and autoconfig as TXT record for my domains.

No, you need them as CNAME or A. LE does not care about TXT (not talking about TXT domain validation). Looks like you added them? Or as a wildcard at least?

Anyway, your FQDN is lxsrv04.domain.tld, not mail.domain.tld. Why should it assign a certificate for an unknown name? :-) You can add it to ADDITIONAL_SAN and run up -d.

**Comment by MarkusP** [comment]
Hi andryy, sorry for that mistake of mine! Wrote totally scrap within the second part of my initial post. Checked my DNS server right the moment and I created the "autodiscover" and "autoconfig" entries as CNAME to the MX.

![image](https://user-images.githubusercontent.com/1380385/41941222-a06e5164-799b-11e8-98e5-6362c9922e6f.png)

Shoudn't it be that acme-mailcow then finds, from autodiscover.domain.tld and/or autoconfig.domain.tld to the corresponding mail.domain.tld entry, as it is CNAME?
Instead of that acme client adds the autoconfig and autodiscover hostnames as SAN entries to the certificate:

> X509v3 Subject Alternative Name: 
                DNS:autoconfig.domaine01.de, DNS:autoconfig.domaine02.de, DNS:autoconfig.domaine03.de, DNS:autoconfig.domaine04.schule, DNS:autoconfig.domaine05.schule, DNS:autoconfig.domaine06.de, DNS:autoconfig.domaine07.de, DNS:autoconfig.domaine08.it, DNS:autoconfig.domaine09.de, DNS:autodiscover.domaine01.de, DNS:autodiscover.domaine02.de, DNS:autodiscover.domaine03.de, DNS:autodiscover.domaine04.schule, DNS:autodiscover.domaine05.schule, DNS:autodiscover.domaine06.de, DNS:autodiscover.domaine07.de, DNS:autodiscover.domaine08.it, DNS:autodiscover.domaine09.de, DNS:lxsrv04.domaine07.de
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
                  User Notice:
                    Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

sorry for all the questions... :-)

**Comment by MarkusP** [comment]
Hi, one further questions... You, andryyy, wrote in your answer 
> You can add it to ADDITIONAL_SAN and run up -d. 

But, when I run `docker-compose up -d` what about my container, their configuration etc...?
Before I do `docker-compose up -d` I think I have to do a `docker-compose down` and the help pages for docker-compose say:
> Commands:
...
...
  down               Stop and remove containers, networks, images, and volumes
...
...

**Now I'm a little scared that everything is gone after that - my configs, my data/mails, and so on?? So, maybe you can help me out a little bit?**

And yes, I know I have to teach myself docker and so... I started, just started :) so, will take some time and maybe I will have to ask one or another question...

**Comment by andryyy** [comment]
No, nothing bad happens. It just re-reads the mailcow.conf and recreates the container with the new env vars.

A very bad idea would be to run `docker-compose down -v`, which also purges the volumes. The volumes store all your data (besides data/conf, which is the location for all configuration files, that we mount into mailcow).

When you change ADDITIONAL_SAN and run `up -d`, all containers that read this variable or are dependent on a container with this var will be recreated. "mailcow.conf" is a symbolic link to ".env". ".env" is a file that is read by docker-compose to fill all variables you see in `docker-compose.yml` under `environment:`.

mailcow containers should be seen as applications, they are kind of transitory. You can always stop and remove them (`docker-compose down` - **without -v!**). `docker-compose up -d` will recreate them from the image templates (for example "mailcow/postfix:1.20"). The config files in data/conf/* will be mounted into the new container, so is your data (volumes).

**Comment by MarkusP** [comment]
Hi, added all my mail.\<domain>.\<tld> to the ADDITIONAL_SAN section within mailcow.conf and did what you wrote: docker-compose up -d
This worked as you can see here... and checking the cert.pem with openssl shows me within the "X509v3 Subject Alternative Name:" section all the mail.\<domain>.\<tld> listed.

> WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
mailcowdockerized_clamd-mailcow_1 is up-to-date
mailcowdockerized_unbound-mailcow_1 is up-to-date
mailcowdockerized_ipv6nat_1 is up-to-date
mailcowdockerized_mysql-mailcow_1 is up-to-date
mailcowdockerized_sogo-mailcow_1 is up-to-date
mailcowdockerized_memcached-mailcow_1 is up-to-date
mailcowdockerized_dockerapi-mailcow_1 is up-to-date
mailcowdockerized_watchdog-mailcow_1 is up-to-date
mailcowdockerized_redis-mailcow_1 is up-to-date
mailcowdockerized_dovecot-mailcow_1 is up-to-date
mailcowdockerized_postfix-mailcow_1 is up-to-date
mailcowdockerized_php-fpm-mailcow_1 is up-to-date
mailcowdockerized_netfilter-mailcow_1 is up-to-date
mailcowdockerized_nginx-mailcow_1 is up-to-date
Recreating mailcowdockerized_acme-mailcow_1 ... 
Recreating mailcowdockerized_acme-mailcow_1 ... done

So, the initial question/problem is solved... still not sure if I understand all of this, but maybe I can come back and ask some more questions :)
