### ISSUE TITLE
Question about Relayhost

### ISSUE THREAD

**Issue by jhahn64** [mailcow/mailcow-dockerized#1508]
Hi,
mail server is on the LAN and is configured with a local domain. I configured a relayhost and added smtp_generic_maps to main.cf. If I send an email with the user user1@sc.local, then it should arrive with the email address user1@mydomain.de. Instead, it comes with the email address that I use for authentication at the relayhost relayuser@gmail.com.
Is it possible to change this behavior?
What was done:
`sed -i -e 's+relayhost =+relayhost = [smtp.gmail.com]:587+' /opt/mailcow-dockerized/data/conf/postfix/main.cf
sed -i -e 's+smtp_sasl_password_maps =+#smtp_sasl_password_maps =+' \
-e '/#smtp_sasl_password_maps/a\smtp_sasl_password_maps = hash:/opt/postfix/conf/saslpasswd' /opt/mailcow-dockerized/data/conf/postfix/main.cf

echo "[smtp.gmail.com]:587 relayuser@gmail.com:GeheimPasswort" > /opt/mailcow-dockerized/data/conf/postfix/saslpasswd
echo "smtp_generic_maps = hash:/opt/postfix/conf/generic" >> /opt/mailcow-dockerized/data/conf/postfix/main.cf
echo "user1@sc.local     user1@mydomain.de" >> /opt/mailcow-dockerized/data/conf/postfix/generic

docker-compose exec postfix-mailcow postmap /opt/postfix/conf/saslpasswd
docker-compose exec postfix-mailcow chown postfix: /opt/postfix/conf/saslpasswd /opt/postfix/conf/saslpasswd.db
docker-compose exec postfix-mailcow chmod 600 /opt/postfix/conf/saslpasswd /opt/postfix/conf/saslpasswd.db

docker-compose exec postfix-mailcow postmap /opt/postfix/conf/generic
docker-compose exec postfix-mailcow chown postfix: /opt/postfix/conf/generic /opt/postfix/conf/generic.db
docker-compose exec postfix-mailcow chmod 600 /opt/postfix/conf/generic /opt/postfix/conf/generic.db
docker-compose exec postfix-mailcow postfix reload`

My attempt to add this into master.cf did not work:
`sed -i -e '/-o smtpd_sender_restrictions=/a\  -o smtp_generic_maps=' /opt/mailcow-dockerized/data/conf/postfix/master.cf`

Thanks in advance
Johann

**Comment by mkuron** [comment]
If you are using Gmail as the relay host, that is expected behavior and not Mailcow‘s fault. Gmail overwrites your From address if it‘s not an address belonging to your Gmail account.

You can, however, add extra addresses in the Gmail settings. Gmail sends a confirmation code to the address and after you confirm it, that address should no longer be overwritten in a From header.
