### ISSUE TITLE
Linode Block Storage

### ISSUE THREAD

**Issue by DrTrills** [mailcow/mailcow-dockerized#1509]
Hello,

Writing to see if anyone can point me in the right direction here. I use mailcow for a subset of our company users. Lately i'm having issues with spacing and would like to host the bulk of user data on some block storage like https://www.linode.com/blockstorage while keeping the actualy install on my debian VPS. Does anyone have experience with this type of setup? Any pointers would be greatly appreciated! Thanks in advance!

**Comment by mkuron** [comment]
Linode block storage just adds an extra virtual disk to your Linode VPS. That‘s completely transparent to anything running on your server. You could mount it to /var/lib/docker so all Mailcow data is stored on it. Just be sure to stop Mailcow and copy over the existing data before you do.

**Comment by DrTrills** [comment]
@mkuron thanks for clarifying. This was +/- my understanding as well. Will see how it goes !

**Comment by discofris** [comment]
@DrTrills  Would be great if you shared your experiences when done. 
Also using and loving Linode.

**Comment by DrTrills** [comment]
@discofris yes- i'll do that once i get around to it!
