### ISSUE TITLE
Dovecot container - Timezone?

### ISSUE THREAD

**Issue by roswitina** [mailcow/mailcow-dockerized#1511]
I have set the timezone in mailcow.conf as follows:

#Your timezone
TZ=Europe/Vienna

In the Dovecot container is displayed with the following timezone:
cat /etc/timezone
Etc/UTC

Is this so right? 
What am I doing wrong?

**Comment by andryyy** [comment]
Hi, $TZ is exported to set the proper timezone. Does `docker-compose logs --tail=20` show the correct timestamps for your zone?

**Comment by roswitina** [comment]
No. It show GMT. 
Habe mir erlaubt, den Gesamt-LOG an deine Mailadresse zu senden.

> watchdog-mailcow_1   | Wed Jun 27 16:14:50 GMT 2018 Rspamd health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:14:52 GMT 2018 Postfix health level: 100% (16/16), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:14:54 GMT 2018 Dovecot health level: 100% (24/24), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:14:55 GMT 2018 SOGo health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:14:59 GMT 2018 PHP-FPM health level: 100% (10/10), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:15:05 GMT 2018 MySQL/MariaDB health level: 100% (12/12), health trend: 0
watchdog-mailcow_1   | Wed Jun 27 16:15:15 GMT 2018 Postfix health level: 100% (16/16), health trend: 0

**Comment by andryyy** [comment]
Thanks, I will add the missing packages and vars now.

Remember the Docker daemon itself logs with your local timezone. :-)
