### ISSUE TITLE
Store all data in encrypted containers

### ISSUE THREAD

**Issue by MaxXor** [mailcow/mailcow-dockerized#1512]
Hello, is it currently possible to store all data which is currently stored in `/var/lib/docker/volumes` in encrypted containers? Can the path be modified to point to an encrypted partition or veracrypt container?

Thanks for this project!

**Comment by chriscroome** [comment]
I don't see why not, I'd use a LUKS encrypted partition for this (because I have been using LUKS since soon after it came out, if veracrypt works for you then use that), or do what I do, run Mailcow in a VM and encrypt the whole disk at the hypervisor level.

**Comment by ghost** [comment]
I'm using a fully encrypted headless debian setup. This works very well ans all data is stored encrypted on all volumes.

**Comment by MaxXor** [comment]
Thanks for your input guys, I'm using now a LUKS container for the docker volumes.
