### ISSUE TITLE
Broken configuration for Postfix

### ISSUE THREAD

**Issue by mnin** [mailcow/mailcow-dockerized#1513]
Since #1510 the configuration for Postfix is broken.

I get the following message in the postfix logs:

```
warning: Invalid TLS eecdh grade "auto": EECDH disabled
```

http://www.postfix.org/postconf.5.html
```
auto
Use the most preferred curve that is supported by both the client and the server. This setting requires Postfix ≥ 3.2 compiled and linked with OpenSSL ≥ 1.0.2. This is the default setting under the above conditions.
```

But Mailcow is currently using Postfix 3.1.8.

**Comment by mnin** [comment]
Fixed #1514

**Comment by normanu** [comment]
I just did the update and I see this popping up in the logs now.
Has it been reverted again?

**Comment by andryyy** [comment]
Which image version of postfix? And what diff on data/conf/postfix/main.cf ?
