### ISSUE TITLE
User defined thresholds are ignored by HAM/SPAM/REJECT

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#1515]
Hi all,
searched the issues and found no answer, so here I am with my question and maybe someone can help...

One of my "customers" is receiving hugh amount of spam - hundrets of spam emails every day. mailcow works fine and moves them all tp SPAM folder. Talked to my customer and he is fine with my suggestion to lower the thresholds for HAM SPAM REJECT from the default values of <5, >=5 <15, >=15... to thresholds 4...8

![image](https://user-images.githubusercontent.com/1380385/42000829-40597a5c-7a62-11e8-8b1f-66fefc24f0a7.png)

But after changing and saving these values I do not see that this news thresholds work, if I look into RSPAMD History...

![image](https://user-images.githubusercontent.com/1380385/42001489-65568c9e-7a64-11e8-9e57-45790b764305.png)

Anyone an idea what I did wrong?

TIA,
Markus

**Comment by andryyy** [comment]
When was the last time you run update.sh?

**Comment by andryyy** [comment]
This will also not work for shared aliases btw. Only mailboxes and alias => single rcpt are supported.

We would also need the Rspamd settings map and rcpt (both can be censored).

**Comment by MarkusP** [comment]
hi,
this mailcow instance is running for 2 days now, so I did not run update.sh since now... 
Will try to run update.sh, but will do full backup before that...
Also need little help with providing the needed information. Where can I find Rspamd settings map and  rcpt?
Markus

**Comment by andryyy** [comment]
You can find it in Admin -> Configuration -> Rspamd settings map.

What is the output of `docker image ls | grep rspamd`?

What about the alias stuff? Is it a shared alias? Is the recipient a mailbox?

**Comment by MarkusP** [comment]
customers email is single mailbox, no alias or so...
output of `docker image ls | grep rspamd` looks like this...
>mailcow/rspamd      1.19                feb9791a7fa7        5 weeks ago         302MB

Rspamd settings (hope I fetched the right ones... 
>settings {
	watchdog {
		priority = 10;
		rcpt = "/null@localhost/i";
		from = "/watchdog@localhost/i";
		apply "default" {
			actions {
				reject = 9999.0;
				greylist = 9998.0;
				"add header" = 9997.0;
			}
		}
	}
	score_receiver<domaine>de {
		priority = 4;
		rcpt = "\/r.receiver[+].*@<domaine>.de\/i";
		rcpt = "r.receiver@<domaine>.de";
		rcpt = "\/ralf.receiver[+].*@<domaine>.de\/i";
		rcpt = "ralf.receiver@<domaine>.de";
		rcpt = "\/ralfreceiver[+].*@<domaine>.de\/i";
		rcpt = "ralfreceiver@<domaine>.de";
		rcpt = "\/rreceiver[+].*@<domaine>.de\/i";
		rcpt = "rreceiver@<domaine>.de";
		rcpt = "\/receiver.amazon[+].*@<domaine>.de\/i";
		rcpt = "receiver.amazon@<domaine>.de";
		rcpt = "\/receiver.netflix[+].*@<domaine>.de\/i";
		rcpt = "receiver.netflix@<domaine>.de";
		rcpt = "receiver@<domaine>.de";
		apply "default" {
			actions {
				reject = 8;
				greylist = 3;
				"add header" = 4;
			}
		}
	}
}

**Comment by andryyy** [comment]
Can you please run an update? HTTP settings maps were fixed in a newer image.

It will also work when you just restart Rspamd. :-) As a workaround until you find time for updating.

**Comment by MarkusP** [comment]
ok... did `docker-compose stop`, then waited few secondes and did `docker-compose start`
I will see what happens...

**Comment by MarkusP** [comment]
![image](https://user-images.githubusercontent.com/1380385/42022982-0d8957de-7abf-11e8-957c-8d0e681fed8a.png)

sorry, restart of Rspamd did not help... So, if my other questions according to the backup script is answered (so that I am sure, I did a valid backup from which I can restore), I will try a update...

**Comment by andryyy** [comment]
It also does not help when you post your settings map like this:

```
rcpt = "/r.receiver[+].@.de/i";
rcpt = "r.receiver@.de";
rcpt = "/ralf.receiver[+].@.de/i";
rcpt = "ralf.receiver@.de";
rcpt = "/ralfreceiver[+].@.de/i";
rcpt = "ralfreceiver@.de";
rcpt = "/rreceiver[+].@.de/i";
rcpt = "rreceiver@.de";
rcpt = "/receiver.amazon[+].@.de/i";
rcpt = "receiver.amazon@.de";
rcpt = "/receiver.netflix[+].@.de/i";
rcpt = "receiver.netflix@.de";
rcpt = "receiver@.de";
```
Does it really say "@.de"?

**Comment by andryyy** [comment]
And this is the third time I ask you about the alias... is the recipient address a shared alias? A direct alias? A mailbox?

**Comment by MarkusP** [comment]
Sorry... I am not that firm with Github so please excuse when my posting looses the original formatting.
And no, it does not say "@.de"... was also my fault thru anonymizing all this...

maybe this, as images, is better...
![image](https://user-images.githubusercontent.com/1380385/42024656-fb613096-7ac2-11e8-8bf8-f814fb648019.png)

**Comment by MarkusP** [comment]
I am sorry annoying you... :-(( I answered your question about the receiver email address earlier
please see here: https://github.com/mailcow/mailcow-dockerized/issues/1515#issuecomment-400951531

**Comment by andryyy** [comment]
I think it just fails because of the `\/`. Can you give me access to that machine? You can mail me to info@servercow.de

**Comment by MarkusP** [comment]
Access would have been possible thru a remote session, but I think it is not necessary any more, as you can see on the screenshot... now Rspamd rejects messages with lower rate... seems it just took some time to "activate" the rule? 
Restarted mailcow at 10:24h, last SPAM recognition with score 11.36 was at 10:36h and few minutes later, at 10:48h there was the first REJECT recognition with score 9.26
So, thanks a lot! :+1: I think this issue can be closed :)

![image](https://user-images.githubusercontent.com/1380385/42025540-158c6c22-7ac5-11e8-98e2-44839480b980.png)

**Comment by andryyy** [comment]
Yes, it takes a few seconds. But I still need to fix that `/\` stuff. Thanks you pointing that out. 👍
