### ISSUE TITLE
Use network sub interface

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#1516]
Hello,
  on my server I have two interfaces : eth0 and eth0:0 with two public IP.

I wants that all process of mailcow use the second interface and second ip. How can I force all trafics : web, mail and others to pass by this second interface ?

Thanks

**Comment by andryyy** [comment]
Hi,
You can use SNAT_TO_SOURCE.

**Comment by guidtz** [comment]
Ok I had it to my configuration but there is a problem with Let's Encrypt certificate generation : 

Thu Jun 28 13:40:35 UTC 2018 - Found A record for mx1.guidtz.net: ip_eth0:0
Thu Jun 28 13:40:35 UTC 2018 - Cannot match your IP ip_eth0 against hostname mx1.guidtz.net (ip_eth0:0)
Thu Jun 28 13:40:35 UTC 2018 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.

So I have to disable SKIP_IP_CHECK

Cdlt

**Comment by andryyy** [comment]
Yes, when incoming and outgoing differ, it should be disabled. We may add a new option for that. 

Mit besten Grüßen
André Peters

**Comment by guidtz** [comment]
Ok but it doesn't seems to apply this to sending mails. I tested sending and IP address is the ip address of eth0 and not of eth0:0 

Regards

**Comment by andryyy** [comment]
It is a SNAT rule. It always applies. It will not work when you change iptables rules by yourself. 

Please post the output of “iptables -L -vn -t nat”.

**Comment by guidtz** [comment]
Rules 

# iptables -L -vn -t nat
Chain PREROUTING (policy ACCEPT 100K packets, 5739K bytes)
 pkts bytes target     prot opt in     out     source               destination         
42428 1566K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 41563 packets, 1528K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 47 packets, 3653 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 35462 packets, 2424K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
24203 1860K MASQUERADE  all  --  *      !br-0bb695fe2704  172.22.1.0/24        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.7           172.22.1.7           tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.4           172.22.1.4           tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.4           172.22.1.4           tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.4           172.22.1.4           tcp dpt:25
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.2           172.22.1.2           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.2           172.22.1.2           tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.12          172.22.1.12          tcp dpt:110

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    9   540 RETURN     all  --  br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.7:3306
   13   744 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.4:587
    9   488 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.4:465
   10   436 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.4:25
  211  9696 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.22.1.2:443
  307 15124 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.22.1.2:80
    0     0 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.12:12345
    0     0 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.12:4190
   12   560 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.12:995
   15   884 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.12:993
    2    80 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.12:143
    6   300 DNAT       tcp  --  !br-0bb695fe2704 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.12:110

**Comment by andryyy** [comment]
Okay, there is no SNAT rule here.
What's in `docker-compose logs --tail=200 netfilter-mailcow`? 
And what's in `docker-compose exec netfilter-mailcow /bin/sh -c env`?

**Comment by guidtz** [comment]
**docker-compose logs --tail=200 netfilter-mailcow1**
variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_netfilter-mailcow_1
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Initializing mailcow netfilter chain
netfilter-mailcow_1  | Subscribing to Redis channel F2B_CHANNEL
netfilter-mailcow_1  | Error in atexit._run_exitfuncs:
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
netfilter-mailcow_1  |     func(*targs, **kargs)
netfilter-mailcow_1  |   File "/server.py", line 213, in clear
netfilter-mailcow_1  |     filter_table.commit()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1596, in commit
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  |     raise IPTCError("can't commit: %s" % (self.strerror()))
netfilter-mailcow_1  | IPTCError: can't commit: Resource temporarily unavailable
netfilter-mailcow_1  | Error in sys.exitfunc:
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
netfilter-mailcow_1  |     func(*targs, **kargs)
netfilter-mailcow_1  |   File "/server.py", line 213, in clear
netfilter-mailcow_1  |     filter_table.commit()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1596, in commit
netfilter-mailcow_1  |     raise IPTCError("can't commit: %s" % (self.strerror()))
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't commit: Resource temporarily unavailable
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 51, in <module>
netfilter-mailcow_1  |     if r.exists('F2B_LOG'):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 951, in exists
netfilter-mailcow_1  |     return self.execute_command('EXISTS', name)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
netfilter-mailcow_1  |     connection.send_command(*args)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
netfilter-mailcow_1  |     self.send_packed_command(self.pack_command(*args))
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
netfilter-mailcow_1  |     self.connect()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
netfilter-mailcow_1  |     raise ConnectionError(self._error_message(e))
netfilter-mailcow_1  | redis.exceptions.ConnectionError: Error 111 connecting to 172.22.1.249:6379. Connection refused.
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Initializing mailcow netfilter chain
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 336, in <module>
netfilter-mailcow_1  |     initChain()
netfilter-mailcow_1  |   File "/server.py", line 306, in initChain
netfilter-mailcow_1  |     target = iptc.Target(rule, "MAILCOW")
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 725, in __init__
netfilter-mailcow_1  |     raise XTablesError("can't find target %s" % (name))
netfilter-mailcow_1  | iptc.xtables.XTablesError: can't find target MAILCOW
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Initializing mailcow netfilter chain
netfilter-mailcow_1  | Subscribing to Redis channel F2B_CHANNEL
netfilter-mailcow_1  | Exception in thread Thread-2:
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
netfilter-mailcow_1  |     self.run()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/threading.py", line 754, in run
netfilter-mailcow_1  |     self.__target(*self.__args, **self.__kwargs)
netfilter-mailcow_1  |   File "/server.py", line 257, in snat
netfilter-mailcow_1  |     if get_snat_rule() not in chain.rules:
netfilter-mailcow_1  |   File "/server.py", line 249, in get_snat_rule
netfilter-mailcow_1  |     target = rule.create_target("SNAT")
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 999, in create_target
netfilter-mailcow_1  |     target = Target(self, name=name, revision=revision, goto=goto)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 725, in __init__
netfilter-mailcow_1  |     raise XTablesError("can't find target %s" % (name))
netfilter-mailcow_1  | XTablesError: can't find target SNAT
netfilter-mailcow_1  | 
netfilter-mailcow_1  | 185.122.102.37 matched rule id 6
netfilter-mailcow_1  | 9 more attempts in the next 600 seconds until 185.122.102.0/24 is banned
netfilter-mailcow_1  | 109.190.152.47 matched rule id 6
netfilter-mailcow_1  | 9 more attempts in the next 600 seconds until 109.190.152.0/24 is banned
netfilter-mailcow_1  | 141.212.122.128 matched rule id 3
netfilter-mailcow_1  | 9 more attempts in the next 600 seconds until 141.212.122.0/24 is banned
netfilter-mailcow_1  | 141.212.122.128 matched rule id 3
netfilter-mailcow_1  | 9 more attempts in the next 600 seconds until 141.212.122.0/24 is banned
netfilter-mailcow_1  | 71.6.146.185 matched rule id 3
netfilter-mailcow_1  | 9 more attempts in the next 600 seconds until 71.6.146.0/24 is banned

### docker-compose exec netfilter-mailcow /bin/sh -c env
IPV4_NETWORK=172.22.1
HOSTNAME=mail01
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
TZ=Europe/Paris
SNAT_TO_SOURCE=IP_eth0:0

**Comment by andryyy** [comment]
Looks more like you restarted the Docker daemon while the containers were running or changed iptables rules yourself at some point? Or run stop and start with docker-compose?

Should be fixed by just running docker-compose down, systemctl restart docker and docker-compose up -d.

**Comment by guidtz** [comment]
Yes very good it's Works.
Do you have a good procedure to integrate a firewall in front of mailcow ! Usually I used shorewall. Do you think I could use it without problems ?

Regards

**Comment by andryyy** [comment]
I also fixed this misbehaviour (+ a bug) in the soon-to-be-pushed netfilter image. I forgot to refresh the table in the loop. 

You can check the topic here: http://shorewall.org/Docker.html :-)

**Comment by guidtz** [comment]
Thanks I'll try It with shorewall shortly.

Regards

**Comment by guidtz** [comment]
Hello. I have problem with shorewall and this sub interface routing. Do you have another solution to firewall mailcow ?
Regards
