### ISSUE TITLE
backup_and_restore.sh skript throws error

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#1519]
Used backup script that comes with mailcow today the first time.
Run script from the following folder:` /opt/mailcow-dockerized/helper-scripts`

`# ./backup_and_restore.sh backup all`
Script asks for backup location: `/home/backup/mailcow-dockerized`

Few seconds later I see the following output: `/opt/mailcow-dockerized/helper-scripts/../mailcow.conf: line 55: mail.domaine.de,: command not found`

Anyone an idea, what happened here? Is the backup fine, or corrupted? Can I check if backup is done with correct data, valid, restorable? 
What makes me wonder is the comma directly behind the domain name..
Looked into the backup script and also into mailcow.conf but cannot see anything wrong there.
Every hint or tip or maybe solution is really appreciated.
TIA
Markus

**Comment by andryyy** [comment]
Well, what is in line 55?

Looks like a format error in this line. Like `mail.domain.de` is just sitting there as a command.

**Comment by MarkusP** [comment]
good questions... from which file? :-) I dont know if mailcow.conf is meant or the backup_and_restore.sh script file...
mailcow.conf:55
>ADDITIONAL_SAN=mail.something.de, mail.domaine.de, mail.sample.de, mail.xyzabc.schule, mail.anonym.schule, mail.blablub.de, mail.domaine7.de, mail.domaine8.it, mail.domaine9.de

backup_and_restore.sh:55
>  chmod 755 "${BACKUP_LOCATION}/mailcow-${DATE}"

**Comment by andryyy** [comment]
That's bad. See https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/

Do not use spaces. mailcow.conf is broken with spaces.

**Comment by MarkusP** [comment]
Ok, I see what you mean... acme client haven't had any issues with the spaces... will delete them and then rerun the script... thx! :)

**Comment by andryyy** [comment]
It just didn't parse anything after the first space. Everything after the first space was a new command.

**Comment by MarkusP** [comment]
Ok, wanted to correct the documentation, add a hint to this, but wasn't allowed... Github wants me to fork the whole project for doing this and then propose the changes... is this the only way?
