### ISSUE TITLE
[Question] Dedicated server

### ISSUE THREAD

**Issue by jaketame** [mailcow/mailcow-dockerized#152]
Hey,

Just wondering whether I still need to run a dedicated server for the docker version of mailcow? Which containers can I give a separate IP address to allow me put this into a shared environment?

**Comment by andryyy** [comment]
Hi,
It already uses a non-standard set of internal IPs, so there should be no problem. If that's what you asked for.
In case of public ip addresses: You can bind the services to any IP in mailcow.conf after running ./generate_config.sh.
It does also not interfere with installed applications.

Edit: Just closed it as an issue, feel free to ask anyway.
