### ISSUE TITLE
Postfix hangs

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#1520]
Hello, monitoring alerts me about smtp outage and after a while is up again. So I look into postfix logs and found this error.

```
 warning: /usr/local/bin/whitelist_forwardinghosts.sh: process id 9701: command time limit exceeded
```

**Comment by andryyy** [comment]
whitelist_forwardinghosts.sh calls forwardinghosts.php which calls Redis. Is there a problem with Redis?

**Comment by feldsam** [comment]
According to container logs, no.

**Comment by feldsam** [comment]
Al also checked php-fpm container

**Comment by feldsam** [comment]
I also see this ```Jun 28 10:33:16 mail postfix/postscreen[9696]: CONNECT from [181.229.210.94]:49795 to [172.22.1.4]:25
Jun 28 10:33:23 mail postfix/postscreen[9696]: fatal: watchdog timeout
Jun 28 10:33:24 mail postfix/master[357]: warning: process /usr/lib/postfix/sbin/postscreen pid 9696 exit status 1``` but looks like no directly related to outage

**Comment by andryyy** [comment]
You had Redis problems a while ago. Did you change redis.conf or anything else? 

You could run something like `date; time docker exec -it $(docker ps -qf name=postfix-mailcow) curl http://nginx:8081/forwardinghosts.php?host=1.2.3.4` **in a loop** to monitor when it hangs. Does it hang the same time SMTPd gets unresponsible?

**Comment by andryyy** [comment]
We could add a timeout to the script in PHP. But it should not run in a timeout anyway. 

Do you know how long it is stuck?

**Comment by feldsam** [comment]
hmm, I do it in bash for loop 1...100 and without errors....

**Comment by andryyy** [comment]
Does it happen every few seconds? Did it happen when you run the loop?

**Comment by feldsam** [comment]
Regarding to redis #1454 I just added vm.overcommit_memory=1 on host.

**Comment by feldsam** [comment]
in loop there was no timeout or hang or anything..it just works.....in postfix it happens from time to time.

**Comment by andryyy** [comment]
You need to run it in a loop until your monitoring says smtpd is stuck. That's the whole point of this loop. And please add a "sleep 1", do not flood the script...

Does the loop log a hugh execution time in the same time your monitoring says smtpd is stuck?

**Comment by feldsam** [comment]
yes, monitoring says outage, and after a few secs, eg 30sec on next monitoring cycle it up again. so it happens just for one time in longer time period. them I look into logs and see that error on same time as monitoring says down. also that forwardinghosts check is related to monitoring server IP.

**Comment by andryyy** [comment]
No, that's not what I meant. :-)

Run the loop, add a sleep 1 or something like that, do NOT flood the php script with your loop.

Leave the loop running! Wait until postscreen gets stuck again, check if the loop also had trouble to curl forwardinghosts.php.

It seems like Redis becomes unreachable. You set `LOG_LINES` in mailcow.conf?

**Comment by feldsam** [comment]
aha, ok. I will run....I dont have that 'LOG_LINES' option in mailcow.conf. I am looking into container logs via portainer

**Comment by andryyy** [comment]
It defaults to 9999 then. What did redis-mailcow log in the time Postscreen got stuck? You should go back up to 10 minutes.

**Comment by feldsam** [comment]
I redis log (from 2days ago to now) no error

**Comment by andryyy** [comment]
What did it log though? Did it do background savings that took a very long time?

I think it is best to monitor the script the the loop until it happens again. The machine load would be interesting when it happens, too.

**Comment by feldsam** [comment]
yes, only this

```
1:M 28 Jun 09:45:03.086 * 100 changes in 300 seconds. Saving...
1:M 28 Jun 09:45:03.121 * Background saving started by pid 7506
7506:C 28 Jun 09:45:13.480 * DB saved on disk
7506:C 28 Jun 09:45:13.510 * RDB: 1 MB of memory used by copy-on-write
1:M 28 Jun 09:45:13.650 * Background saving terminated with success
1:M 28 Jun 09:50:14.005 * 100 changes in 300 seconds. Saving...
1:M 28 Jun 09:50:14.033 * Background saving started by pid 7507
7507:C 28 Jun 09:50:23.845 * DB saved on disk
7507:C 28 Jun 09:50:23.873 * RDB: 0 MB of memory used by copy-on-write
1:M 28 Jun 09:50:23.972 * Background saving terminated with success
```

When I was looking on specific time, I did not see any longer saving

**Comment by andryyy** [comment]
It takes about 10 minutes for Postscreen to time out, I think. That's why I asked you to go back a few more minutes. :-)

Overcomitting on a slow disk can cause this, too. That's why you should monitor your IO and server load in general until it happens again.

**Comment by andryyy** [comment]
Ah, damn, keep in mind, that Redis logs in UTC. :-D

**Comment by feldsam** [comment]
jj, I see that :)

**Comment by feldsam** [comment]
Hi, today happens again. After receiving email alert I immediately run loop test script, but no error. Host load was 6 and swap is near full

```
              total        used        free      shared     buffers       cache   available
Mem:           3.9G        3.3G        111M         25M         20M        475M        358M
Swap:          953M        953M          0B
Total:         4.8G        4.2G        111M
```

So probably I have to increase RAM.

**Comment by andryyy** [comment]
Hey, you should leave it running. :-) So we can check wether the script hangs too. But it most likely runs out of resources, yes. 

I will add a timeout to the script, so we can at least return any result.

**Comment by feldsam** [comment]
hello, today another hangs and this in postfix logs

warning: process /usr/lib/postfix/sbin/postscreen pid 11267 exit status 1
warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling

so probably can be ram issue like I post in prev post

**Comment by feldsam** [comment]
Looks like it is solved by more RAM
