### ISSUE TITLE
Cross domain GAL?

### ISSUE THREAD

**Issue by st1172** [mailcow/mailcow-dockerized#1522]
I have several domains and would like to do calendar sharing between them. Is there a way to enable a GAL that includes users from ALL domains?

**Comment by st1172** [comment]
Poking around found [this](https://github.com/mailcow/mailcow-dockerized/issues/1184). I was able to enter the container and edit the sogo.conf file. Is there something I am missing without having to do this?

**Comment by andryyy** [comment]
GAL would be more complicated. But you can setup multi domain visibility in sogo.conf (see mailcow docs). This will show all GALs of all domains. 

You also don’t need to enter the container. The config file is available at data/conf/sogo/sogo.conf and is mounted into the container.

**Comment by andreas-git** [comment]
I use multi domain setup,
to see another Domains just add following lines in mailcow-dockerized/data/conf/sogo/sogo.conf

// Multi-domain setup
// Domains are isolated, you can define visibility options here.
// Example:
SOGoDomainsVisibility = (
      (domain1.tld, domain5.tld),   //domain Group1
      (domain3.tld, domain2.tld)   //domain Group2
      );

Or you can add all domains together.

I hope i could help you.

Best Regards

Andreas
