### ISSUE TITLE
Problem with intermediate certificate

### ISSUE THREAD

**Issue by adeleglise** [mailcow/mailcow-dockerized#1525]
Hi,

I'm running the latest mailcow version.

I can see this error in the postfix logs :

```
28/06/2018 à 16:32:52	info	disconnect from unknown[192.168.12.12] ehlo=1 starttls=0/1 commands=1/2
28/06/2018 à 16:32:52	info	lost connection after STARTTLS from unknown[192.168.12.12]
28/06/2018 à 16:32:52	warning	warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1399:SSL alert number 48:
28/06/2018 à 16:32:52	info	SSL_accept error from unknown[192.168.12.12]: -1
28/06/2018 à 16:32:52	info	connect from unknown[192.168.12.12]
```
I saw another issue with this error, and you guys advised to check using checktls.

So i did this and discovered that the intermediate certificate is a dummy one :

```
subject= /O=mailcow/CN=mail.example.org
issuer= /O=mailcow
```
I think the problem is that I didn't checked the letsencrypt generation at setup, as I thought it is used for the webmail HTTPS (and I use haproxy so the certificate is set there).

How can I issue the TLS certificate for postfix and integrate it now ?

For info, I'm trying to send e-mails from a wordpress instance, so it's PHP trying to use SMTP from LAN.

Thanks.

**Comment by adeleglise** [comment]
Ok, found it :)

I've just recreated the acme-mailcow container, with the right parameters in mailcow.conf

**Comment by shivamtrivedi01** [comment]
@adeleglise  Can you please elaborate on what right parameters you added in the mailcow.conf? I am facing the same issue.
