### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by x3r4n0** [mailcow/mailcow-dockerized#153]
how i can reset the password for admin?

**Comment by lindeto** [comment]
https://andryyy.github.io/mailcow-dockerized/u_and_e/#reset-admin-password

**Comment by MadMooAU** [comment]
Previous answer is now broken, new link is https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/

**Comment by mr412** [comment]
Dear MadMooAU,
I have installed mailcow with docker. I cant locate the bash script. mailcow-reset-admin.sh

**Comment by billthecatt** [comment]
I used:
/usr/local/sbin/mailcow-reset-admin 
on my non docker mailcow install. Hope this helps someone else.
