### ISSUE TITLE
Question ? Add second Postfix instance on another IP

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#1531]
Hello,

   for separate mail flux (users mails and applications mails), I need a second postfix instance wich route mails on a second IP address. 

Can I add it with mailcow or do you sugest me to add another docker postfix instance separate to mailcow ?

Thanks for you're advice

Regards

**Comment by mkuron** [comment]
That is not supported by Mailcow. You could set up two completely separate Mailcows though. Also, duplicate of https://github.com/mailcow/mailcow-dockerized/pull/727#issuecomment-369778058.
