### ISSUE TITLE
SSL-Certificates and Subdomains

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1533]
I know this isn't really an issue, but I wasn't able to find help anywhere else. So now my problem: 

I just set up my mailcow server and I'm running it on ports 8080 and 8443 because ports 80 and 443 are used by an apache2 webserver. But I really want a clean domain like mail.mydomain.com. I wasn't able to get any of the advice other people gave to work (I've set up an A-Record so I can use mail.mydomain.com:8443 already). I saw some people saying you need to use a reverse proxy and I already tried to set one up but it didn't work for me (maybe I just did something wrong). As you might be able to tell I'm not that experienced in working with things like that so please explain it for someone who has no clue. My other problem is, that the SSL certificate which mailcow creates seems to be incorrect. When I connect to the https port I get a notification that the connection is insecure asking me if I want to continue.

I would be really glad if someone could help me

**Comment by mkuron** [comment]
A reverse proxy is indeed what you need. You can configure your existing Apache to pass requests to mail.mydomain.com by following the documentation (https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/), though of course you need to adapt things.

If you get a certificate error, then most likely Mailcow didn’t successfully obtain a certificate. Please check `docker-compose logs acme-mailcow`.

**Comment by ghost** [comment]
First of all thanks for the quick reply but my problem is that the mailcow docs say that acme-mailcow needs your mailcow to be available on port 80 to work.

**Comment by ghost** [comment]
```
<VirtualHost *:443>
        ServerAdmin test@test.de
        ServerName mail.mydomain.com

        ProxyPass / http://mydomain.com:8080/
        ProxyPassReverse / http://mydomain.com:8080/
        ProxyPreserveHost On
        ProxyAddHeaders On

        RequestHeader set X-Forwarded-Proto "https"

        your-ssl-configuration-here

        SSLProxyEngine On
</VirtualHost>
```

This is my apache config but it doesn't change a thing (and yes of course mydomain.com is replaced with my domain). Mailcow is still only available under mail.mydomain.com:8443 and mydomain.com:8443 or the http port.

**Comment by mkuron** [comment]
Did you replace `your-ssl-configuration-here`? Also, you may need the `NameVirtualHost` directive if you didn’t previously use virtual hosts in Apache. Finally, the Apache logs may provide hints why the virtual host you configured isn’t being used.

Port 80 is indeed required to obtain certificates, and that is not our fault. This can be through the reverse proxy though, so this is no problem. But of course, don’t expect the encryption warning to go away before you fix the reverse proxy issue.
