### ISSUE TITLE
update password database mailcowUI error

### ISSUE THREAD

**Issue by NetIds** [mailcow/mailcow-dockerized#1535]
When i add an SSHA512 password from an other server and replace it into the database table "mailbox", I can not login anymore on the Mailcow UI, but I can login into SOGo with the password from the other server.

Also when I save an SSHA265 password, it is the same, i can login into SOGo but not into MailcowUI

Can someone help me out to fix this issue?

**Comment by mkuron** [comment]
Duplicate of #1481. Please check existing issues before creating a new one.
