### ISSUE TITLE
Access denied for user 'mailcow'

### ISSUE THREAD

**Issue by Cr0uchPotato** [mailcow/mailcow-dockerized#154]
I've set up a completely new instance, I'm not tied to any of the data.  I had the server set up and working just fine but I was mucking around with letsencrypt and somewhere along the line screwed something up.  I started getting "Access denied for user 'mailcow' " when I would try to access the main page at ${MAILCOW_HOSTNAME}.  At the time, I could log in to the mariadb directly with both the ${DBUSER} and ${DBPASS} and root and ${DBROOT}.  I attempted to undo the installation by running docker-compose down and deleting the mailcow-dockerized folder.  Then I ran through the installation again but ended up with the same error on when I tried to connect to ${MAILCOW_HOSTNAME}.  Worse, now I EDIT: CAN'T connect to mariadb with either the ${DBUSER} and ${DBPASS} or root and ${DBROOT}!  Any help?  Like I said, if I could cleanly purge everything that would be fine.  There's nothing in the database that I care about.

**Comment by andryyy** [comment]
Run `docker-compose down -v` to delete the old database. This will do it. :-)

**Comment by Cr0uchPotato** [comment]
@andryyy Thanks buddy, that did it.

**Comment by Cr0uchPotato** [comment]
@andryyy Okay, so I'm reopening here because I'm not sure if my new issue is related to the credentials problem I was having before.  Now, I can send emails all day no problem but I can't receive.  Also,  I can't find any log files.  Am I supposed to be declaring my own logs or enabling debug somewhere to see them?

**Comment by Cr0uchPotato** [comment]
I found the log.  The only thing negative I'm seeing is that the watchdog was complaining that pid 45 had been hanging for 5 minutes.  Next update I see from 45 is a successful POST.  Anything else I should be looking for?

**Comment by andryyy** [comment]
What is your domain name and what about `docker-compose logs postfix-mailcow` ?

**Comment by Cr0uchPotato** [comment]
My domain name is revesports[dot]org . That log doesn't show any errors.  I can even see some incoming mail, but it never makes it to a user's inbox.  Also, that log seems to be timestamped to UTC not my local machine time.  Not sure if that's important.

**Comment by andryyy** [comment]
We need the logs to help. Postfix and Dovecot .. when mail arrives.

**Comment by Cr0uchPotato** [comment]
Okay, I'll update likely after the weekend. Thanks for all your help.

On Mar 24, 2017 4:16 PM, "André Peters" <notifications@github.com> wrote:

We need the logs to help. Postfix and Dovecot .. when mail arrives.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/andryyy/mailcow-dockerized/issues/154#issuecomment-289132068>,
or mute the thread

**Comment by broedli** [comment]
@Cr0uchPotato is your problem resolved?
