### ISSUE TITLE
Backup Script issue ./helper-scripts/backup_and_restore.sh backup all

### ISSUE THREAD

**Issue by simon-india** [mailcow/mailcow-dockerized#1542]
when I tried to use the backup script I go this 

I was in the /opt/mailcow-dockerized as root and I was using the command ./helper-scripts/backup_and_restore.sh backup all

`Backup location (absolute path, starting with /): /opt/
Using /opt as backup/restore location.

Unable to find image 'debian:stretch-slim' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
OK
Unable to find image 'debian:stretch-slim' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Unable to find image 'debian:stretch-slim' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/debian/manifests/stretch-slim: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fdebian%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Unable to find image 'debian:stretch-slim' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.`

**Comment by andryyy** [comment]
Hm, is the registry down or has routing problems?

**Comment by simon-india** [comment]
Thanks for the instant response. no i don't think so.

**Comment by andryyy** [comment]
Proxy? Firewall?

Can you curl the URL from your server?

**Comment by simon-india** [comment]
sure one sec

**Comment by simon-india** [comment]
it seems our firewall is blocking the request. but does it need to query the registry for the backup's to work.

root@sogo:/opt/mailcow-dockerized# wget  https://registry-1.docker.io
--2018-07-05 14:32:13--  https://registry-1.docker.io/

Resolving registry-1.docker.io (registry-1.docker.io)... 52.54.216.153, 34.200.90.16, 35.169.231.249, ...
Connecting to registry-1.docker.io (registry-1.docker.io)|52.54.216.153|:443... failed: Connection timed out.
Connecting to registry-1.docker.io (registry-1.docker.io)|34.200.90.16|:443...

**Comment by simon-india** [comment]
Guys I'm closing this but I don't have a solution yet.
