### ISSUE TITLE
Can't add ressources

### ISSUE THREAD

**Issue by Ashby666** [mailcow/mailcow-dockerized#1545]
Hi there,

unfortunately, I can not add resources (tested thing, group or location) to a newly installed cow. An error message does not appear. The tab reloads short, without anything being created. 

So far tried: Restart and new creation of the SOGo container.

Any ideas what I can do?

Thank you!

**Comment by andryyy** [comment]
Oh, I will fix it.

**Comment by Ashby666** [comment]
Thank you, much better after the update :-)
