### ISSUE TITLE
Dovecot process_limit reached

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#1551]
Hello, I experience problems with dovecot service. In logs found following:

```
Jul  9 15:56:19 mail dovecot: master: Warning: service(imap-login): process_limit (100) reached, client connections are being dropped
```

So I add `process_limit  = 256` to `imap-login` and `pop3-login`.

This should be increased by default.

**Comment by mkuron** [comment]
Fixed already by #1489. That was merged to dev, which has diverged quite a bit from master over the recent months. Maybe @andryyy can comment on when he plans to bring dev's fixes into master.

**Comment by mritzmann** [comment]
@feldsam Do you only have problems with IMAP, or also with POP? Otherwise you would also have to make a pull request for POP.

**Comment by feldsam** [comment]
just IMAP, in our environment is IMAP used more that POP
