### ISSUE TITLE
Custom mail scanning plugin

### ISSUE THREAD

**Issue by dshaklein** [mailcow/mailcow-dockerized#1552]
Hello! 
Can I somehow write my own additional scanning plugins with python in mailcow-dockerized?
I saw that in Fuglu there is a suitable functional. You have fuglu included in the old non dockerized version, but I can't find it in mailcow-dockerized. What is the reason for this?

What is a simple way for my problem? Maybe there are good alternatives to fuglu or dockerized version with fuglu included.

**Comment by andryyy** [comment]
We use Rspamd. It has a LUA interface.
