### ISSUE TITLE
Alias matching more than it should

### ISSUE THREAD

**Issue by boecht** [mailcow/mailcow-dockerized#1555]
Somewhere in the last 2-3 months there has been an update that changed the behaviour of the alias matching. It matches more than it should and thereby forwards mail to the wrong box.

I installed an alias `de@example.com` for `user1@example.com`.
Since some time it also forwards mail addressed to `test.de@example.com` instead of leaving it for the catchall. It did not do that before.

Can you reproduce this behaviour?

Edit: It also seems still to forward the mail even if the alias is set to disabled. This may have been a timing/reload config issue while figuring this out though, but I did restart the services and it still did forward.

**Comment by tkorves** [comment]
Hi @boecht,

tried to reproduce this behaviour and I'm able to confirm that there's such an error occuring.

First test without catchall:
de@domain.tld is an alias for user@domain.tld, test.de@domain.tld isn't existant. 
<test.de@domain.tld>: Recipient address rejected: User unknown in virtual mailbox table

Second with a catchall:
It's pretty much the same behaviour you observed - the catchall is working fine, up to the part, where the 'de' is part of the address - but it has to be at the end, right in front of the '@'.

We're investigating.

BR, Tim

**Comment by andryyy** [comment]
I cannot reproduce this. :-(

**Comment by andryyy** [comment]
Alias table:
![grafik](https://user-images.githubusercontent.com/2972950/42623738-ead5d072-85c3-11e8-9755-e70046e130f6.png)

Mailbox table:
![grafik](https://user-images.githubusercontent.com/2972950/42623768-fcc11094-85c3-11e8-880a-a73e693380fe.png)

I send a mail to de@develcow.de. It is delivered to andre@develcow.de.

I send a mail to test.de@develcow.de. It is delivered to dummy@develcow.de only.

I am probably missing something.

**Comment by andryyy** [comment]
Could you please run update.sh and test it again?

**Comment by boecht** [comment]
Updated (last night and again just now), re-added `de@mydomain.de` alias, then the mail to `test.de@mydomain.de` gets forwarded (to `spam@mydomain.de`, which rejects by blacklist) instead of going to catchall.

Edit: I deactivated the alias, restarted all containers (via update) and it still forwards, despite the rule being disabled.

**Comment by andryyy** [comment]
I cannot follow you.

I don't know your setup of aliases etc. ... what is spam@mydomain.de? An alias destination? For what? A sieve forwarding rule?

Which alias was deactivated?

**Comment by andryyy** [comment]
And what about my setup above? Is this correct?

**Comment by andryyy** [comment]
Is everything within a single domain? Like mydomain.de? Nothing cross-domain?

Ooops, re-opened.

**Comment by boecht** [comment]
Your setup is correct.
When I set it up using another domain, it does work fine, just like yours.
It is all only within its own domain, no cross-domain forwarding.

The only difference between the 2 domains is that the target mailbox on the faulty domain has a blacklist set (as a black hole with rejection):
`  blacklist_spammydomainde {`
`    from = "/(^a.*$|^b.*$|^c.*$|^d.*$|^e.*$|^f.*$|^g.*$|^h.*$|^i.*$|^j.*$|^k.*$|^l.*$|^m.*$|^n.*$|^o.*$|^p.*$|^q.*$|^r.*$|^s.*$|^t.*$|^v.*$|^w.*$|^x.*$|^y.*$|^z.*$|^1.*$|^2.*$|^3.*$|^4.*$|^5.*$|^6.*$|^7.*$|^8.*$|^9.*$|^0.*$|^u.*$)/i";`
`    priority = 6;`
`    rcpt = "/de[+].*@mydomain.de/i";`
`    rcpt = "/de@mydomain.de/i";`
`    rcpt = "/spam[+].*@mydomain.de/i";`
`    rcpt = "/spam@mydomain.de/i";`
`    apply "default" {`
`    MAILCOW_BLACK = 999.0;`
`    }`
`    symbols [`
`      "MAILCOW_BLACK"`
`    ]`
`  }`
So now I guess the blacklist does match somehow when the alias is either activated or deactivated, since the blacklist rule does not change when the alias is deactivated.

**Comment by andryyy** [comment]
Can we open a AnyDesk session? I would like to check some Postfix table results.

**Comment by boecht** [comment]
I'm out for today.
I just removed the blacklist and it's working as expected. Really must be the blacklist matching.
If you tell me what you need I'll get it to you tomorrow.

**Comment by andryyy** [comment]
Crazy bug. I try to reproduce it now. :-)

We can talk via mail => info@servercow.de

**Comment by andryyy** [comment]
We could try to make it ` rcpt = "/^spam@mydomain.de$/i";`
