### ISSUE TITLE
Cannot authenticate from Android Gmail or Microsoft Outlook

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#1557]
Hi, since last update login is impossible from Gmail or Outlook app from Android. All active sessions have been terminated and now it is impossible to login. Server response is "invalid username or password". In Gmail App response is "Wrong username or password".

Please help, it is very important!!

Thanks

**Comment by andryyy** [comment]
Hi, did you open mailcow UI in a browser to update the database?

**Comment by samuelebistoletti** [comment]
Yes, I did that and there was the response "Database initialization"

I have also another server: same situation..

**Comment by andryyy** [comment]
failed? succeeded?

Where does it show "invalid username or password"? How did you update mailcow?

**Comment by andryyy** [comment]
Can you please try and restart SOGo?

**Comment by samuelebistoletti** [comment]
Both server with failed authentication from Android app. From Thunderbird on my laptop everything seems to be ok.
When I open the Gmail or Outlook app a message shows app with invalid username or password asking me to login again. I updated Mailcow with the automatic script ./update

**Comment by samuelebistoletti** [comment]
Tried to restart SOGo..same situation, no login possible, also from SOGo webmail
Message is: Wrong username or password also from SOGo

**Comment by andryyy** [comment]
I cannot reproduce this on two test machines. Can you mail me access to info@servercow.de ?

**Comment by samuelebistoletti** [comment]
I sent you an email

**Comment by andryyy** [comment]
I sent you two responses.

I will leave in a few minutes. :-/

**Comment by samuelebistoletti** [comment]
Sorry I answered but I think you did not received my emails. Maybe in spam. Now I tried from Gmail

**Comment by andryyy** [comment]
Very good catch, thank you...

On the test machines I run a manual update of the static view table for SOGo. It would have worked if you changed an alias or mailbox via mailcow UI (it replaces the content then).

Sorry.

**Comment by samuelebistoletti** [comment]
Thanks. I was not able to answer you because of impossible charset, but it's solved now.

For the second server can I run the update script? or you need to fix other things?

Thanks

**Comment by andryyy** [comment]
You can run update.sh now if you want to.

**Comment by samuelebistoletti** [comment]
ok thanks
