### ISSUE TITLE
Adding another domain for outgoing mails only

### ISSUE THREAD

**Issue by skupfer** [mailcow/mailcow-dockerized#1560]
hello there

Unfortunately I didn't get an answer on IRC so I am asking here again.

I have a question regarding multiple domains... I have hosted mailcow on server 1.1.1.1 with "domain1.tld" pointing to it (and configured in mailcow, RDNS, ...)

I have a second "domain2.tld" on 1.1.1.1 ... Some services need a smtp setup for outgoing mails (like info, registration, ...). I wanted to use ie. admin@service.domain2.tld or service@domain2.tld, so users can register for my service. 

What would I have to do to achieve this? This is just for the automated mail during the registration process (some activation link I guess), no "mailbox configuration" for endclients or so is required for this domain.

Is it enough to change the "ADDITIONAL_SAN" field and add domain2.tld or service.domain2.tld?
Or would I have to change some DNS records for domain2.tld?
Or is it enough to add the domain via the web interface?

This has been asked multiple times, but I wasn't able to figure out the right answer. I don't want to go for trial&error.

**Comment by andryyy** [comment]
Hi,

Was domain2 added to mailcow? You could add it as alias-domain for domain1. You would be able to send mail from this domain then.

**Comment by skupfer** [comment]
Thanks for your reply. As of now I didn't to anything, didn't change anything. domain2.tld and its subdomains for the services point to my server, thats all as of now. Thats because domain1 is my domain for mailcow and the appropriate DNS records.

So if I get this right, all I would have to do is going to "Config -> Mailbox -> Aliases -> Add domain alias". Am I getting this right? No further MX/DNS setup required or ADDITIONAL_SAN etc pp. ?

EDIT: could I use i.e. service.domain2.tld or only domain2.tld ?

**Comment by andryyy** [comment]
I think we already talked about this on IRC.

You will probably end in a lot of junk folders when you skip setting up MX, A and AAAA records. You should also setup a DKIM record then.

You can also use service.domain2.tld, why not? It is just another domain. Just remember to setup all DNS records. You cannot send mail from a domain without any MX, A or AAAA record. Or, well, you can, but it will almost never hit the inbox.

ADDITIONAL_SAN is configured for additional SANs in the certificate. You don't need this. Your MX is always MAILCOW_HOSTNAME.

**Comment by skupfer** [comment]
You definitely didn't talk to me, wish I would have been there :-)

So I would have to add the following DNS entries to domain2.tld
- MX: mail.domain1.tld
- dkim._domainkey (generated via adminpanel)

dmarc, "v=spf1 mx ~all", autoconfig, autodiscover are not necessary?
EDIT: I guess I should still add dmarc / spf

After that all I have to do is to add the domain via the admin interface (like the first) and create a mailbox for this one, right?

**Comment by andryyy** [comment]
Yes, right. :-)

You should still add SPF, I think. Some (only some) MTAs may punish this. 

"After that all I have to do is to add the domain via the admin interface (like the first) and create a mailbox for this one, right?"
=> Yes

**Comment by skupfer** [comment]
thank you very much, I decided to add everything just to be sure (even autoconfig/discover to mail.domain1.tld)...

dmarc made some problems since I wasn't able to figure out how to do the external verification (records weren't working) so I created a new mailbox for that^^

thank you very much for your help!
