### ISSUE TITLE
GDPR Questions

### ISSUE THREAD

**Issue by Zauberbutter** [mailcow/mailcow-dockerized#1569]
Is there a way to remove:

* IP's from all the logs (after an amount of time)
* subject and sender/receiver adress from the rspamd log

**Comment by mkuron** [comment]
No, that is not currently possible. The recommended solution is to just not keep your log files for more than a few days. It's usually considered acceptable to have short-term non-anonymized log files for technical purposes (e.g. debugging, checking whether an email has been delivered, investigating spam and hacking attempts, etc.).

To limit the amount of logging to something like the last 10000 emails, put the following into /etc/docker/daemon.json and restart the Docker daemon:
```
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "1m",
    "max-file": "5"
  }
}
```

rspamd only keeps around information for the past 2000 emails, but if you want to change that, see #1324.
