### ISSUE TITLE
Null 'From' when using SOGo filter to send reject msg

### ISSUE THREAD

**Issue by lwl12** [mailcow/mailcow-dockerized#157]
it just has 
From: Mail Delivery Subsystem <postmaster@example.com> Info（After DATA）
but not truth From （before SMTP 'DATA' command）

**Comment by lwl12** [comment]
So this caused some mail system reject my rejection mail. Funny :-)

**Comment by andryyy** [comment]
I heard it before, but it is totally fine regarding some chapter in RFC2298 - can't look it up, I'm on my mobile at the moment). Correct me if I'm wrong! :-)

**Comment by kn007** [comment]
Like this?

RFC2298 Page 7
```
 The envelope sender address (i.e., SMTP MAIL FROM) of the MDN MUST be
   null (<>), specifying that no Delivery Status Notification messages
   or other messages indicating successful or unsuccessful delivery are
   to be sent in response to an MDN.
```

**Comment by lwl12** [comment]
OK,that's means our response is correct, but others system not?
Well, sounds coolヾ(●゜ⅴ゜)ﾉThanks for help

**Comment by andryyy** [comment]
Thanks!
