### ISSUE TITLE
Merge ETA for mailcow without docker

### ISSUE THREAD

**Issue by CrAazZyMaN21** [mailcow/mailcow-dockerized#1570]
Hi mailcow team!

Since the creation of mailcow-dockerized I was worried about that the mailcow "standalone" would be lacking on updates. So I waited about 1 year that you push your changes to the "main" repo and nothing happend since than. Since I saw that the repo was archived, I thought about writing a short text how I see the problem with not continuing the "main" project. 

I am using mailcow since the beginning of fufix 0.4 and I was glad at that time because I started working with linux on a high level. I thought that a mailserver would be the next level of working with linux and I never got it working by myself. Than I found your project and I was happy seeing someone caring about others having the same problem like myself for maintaining a mailserver properly (Thank you very much for that André). 

The Project developed heavily in the professional way when you renamed fufix to mailcow and swapped out postfixadmin with your custom written mailcow alternative (The custom one is really nice btw.). Since then mailcow was getting better and better and then came the dockerized version which killed the "main" project in my eyes. 

I am not saying that the docker version is bad in any way but I don't have the trust and time (I think I am not the only one) in docker to get into the whole thing. As of my knowledge docker had or still has problems with its security of the kernel and the docker images itself. On one point I have to say that the docker version is better than the "main" project because you decide which version of packages get installed and not the OS itself and make it useable on nearly all linux platforms. This is an easier way to maintain the mailserver itself and increases the security a lot.

Since Ubuntu 18.04 came out I wanted to upgrade but the script is not working for it right now. So this is the perfect time to ask for the merge ETA.  

> This version is outdated until "mailcow: dockerized" code is merged to this repository.

To bring this to an end my only question is will there be a merge for the "main" repo or not?

Thank you very much for your project and your effort for keeping this alive.

Ps.: English is not my native language and I didn't want to write it in German because everyone should be able to read it.

**Comment by Keyzmo** [comment]
I would like to know too, but judging by how things have been going so far, I'm afraid the answer is gonna be "never".

**Comment by andryyy** [comment]
Thank you very much for your post @CrAazZyMaN21 👍 

It tends to be never at the moment. Seriously, I already spend hours on this repository (remember this is neither sponsored nor paid in another way). It is very, very time consuming. Some people even mail me and kind of demand support (free, for sure), because after all it is my software and I'm responsible etc. That's insane. I will probably try to make paid support (contracts) a bigger thing, to keep mailcow: dockerized going.

mailcow: dockerized is probably much more secure than mailcow was. :-)

You should give it a try.
