### ISSUE TITLE
Request docs update

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#1574]
Hello, I love this project and support given.
Since I'm not a docker guru and we need to keep mailcow in the same installation environment to run and troubleshoot accurately I am requesting in the documentation steps to update docker itself the way we are told to install it.  

Also somehow, even though I followed the guide to a "t" my docker uses vfs data driver instead of overlay2 by default.  I think this has brought up problems related to performance and storage size here.

Would it also be possible under install options in documentations to check this and how to change it. Possibly adding it to the install or update script.

Thank you much!

**Comment by PhoenixPeca** [comment]
Hi! as for your concern about updating docker, it is already available. 😄 You can check the lines of code that made that possible in the update.sh script.
https://github.com/mailcow/mailcow-dockerized/blob/599d14f8546f2c08dcfd78fad298b16e5ab41578/update.sh#L219-L237

**Comment by kilo42L** [comment]
Wow, genius :)  Maybe it should still mention that it updates docker in the docs.
I figured my other issue out so its not a problem..
