### ISSUE TITLE
cannot find dependency on symbol MAILCOW_WHITE

### ISSUE THREAD

**Issue by xiaoveiti** [mailcow/mailcow-dockerized#1577]
Less an issue, more like an question. 

I set up mailcow on one of my servers, and noticed this error msg in the rspamd webui after an reboot. 
What does it mean? 

Until now I didn't specify anything in an whitelist" does the whitelist exist before? or ist it genereated after filled with stuff?

**Comment by Power2All** [comment]
Same problem after updating mailcow.

**Comment by xiaoveiti** [comment]
@Power2All Still not sure, if its a problem, or just an error msg, because there is no whitelist defined by me. 

But even with this error msg, my mailcow runs smooth and without any problems, with around 30 Mailaccounts and 50 domain. Just some Asian Domains looks kind of weired haha :D

**Comment by Power2All** [comment]
Well, I got issues sending from my websites.
Seems it's greylisting randomly, even though I added whitelistings.

**Comment by cklabautermann** [comment]
Same error message here:

`cannot find dependency on symbol MAILCOW_WHITE`

I am on the latest mailcow-dockerized release.

**Comment by andryyy** [comment]
That's just a warning you can ignore...
