### ISSUE TITLE
Problem with nginx restarting after and upgrade

### ISSUE THREAD

**Issue by bigjerms** [mailcow/mailcow-dockerized#1579]
I did an update and it seemed to kill my nginx container.  It was constantly restarting.  

I checked the log files on the nginx-mailcow container and it was full of the following:

_nginx-mailcow_1      | 2018/07/16 18:59:47 [emerg] 10#10: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:08 [emerg] 10#10: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:09 [emerg] 12#12: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:10 [emerg] 10#10: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:11 [emerg] 11#11: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:13 [emerg] 12#12: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:15 [emerg] 10#10: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/07/16 19:00:19 [emerg] 12#12: host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "mm-web" in /etc/nginx/conf.d/site.conf:96_

I was not able to figure out what was causing this error so I instead commented out this section of the site.conf file and issued a docker-compose restart nginx-mailcow command.  (See the block of config that I commented out below) 

```
 # location /lists/ {
 #   proxy_pass       http://mm-web:8000/;
 #   proxy_set_header Host      $http_host;
 #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 #   proxy_set_header X-Real-IP $remote_addr;
 #   proxy_redirect off;
 #   expires $expires;
 # }

```
The nginx-mailcow container now starts up with no errors.  I'm not sure however what I may be breaking by commenting this code out.

Will there be any negative issues from removing _/location /lists/ block_ from the site.conf?  If there will, what do I need to fix to get nginx to load correctly with this section of the site.conf file uncommented?  Any help or direction would be appreciated.

**Comment by andryyy** [comment]
You were on dev. Dev is not usable atm.
