### ISSUE TITLE
zen.spamhaus.org: Host or domain name not found

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#1581]
Hi,

Eigentlich nur eine Frage:

Ich ging die ganze Zeit davon aus dass die folgenden Meldungen, mit denen die Postfix Logs voll sind, normal wären (z. B. weil er einfach nix auf der Liste gefunden hat), hatte hier allerdings etwas anderes gelesen - eine Lösung dafür aber auch nicht direkt gefunden:

warning: dnsblog_query: lookup error for DNS query 186.206.138.*.zen.spamhaus.org: Host or domain name not found. Name service error for name=186.206.138.*.zen.spamhaus.org type=A: Host not found, try again (letzten IP Block anonymisiert)

Alle anderen dnsbl scheinen die Fehler nicht zu werfen, nur zen.spamhaus.org. Mailcow (dockerized) wurde damals auf einem blanken minimal-debian-stretch installiert, an einer verpfuschten DNS Konfiguration kann es eigentlich nicht liegen. Manuell nachinstalliert hatte ich auch keinen DNS Resolver oder ähnliches.

Sind die Meldungen normal oder stimmt da doch irgendwas nicht?

**Comment by andryyy** [comment]
Anfragen an Spamhaus aus großen Netzen wie OVH (unsicher) und Hetzner (sicher) werden blockiert, habe ich mir sagen lassen. Weitere Erfahrung habe ich nicht. Bist du bei einem der beiden?

**Comment by lalaluuu** [comment]
Hm. Wäre ein Hetzner Server - gut, .. doof - Danke ;-)

**Comment by lalaluuu** [comment]
Jetzt versuchte ich eben die Nameserver zu ändern, die Netzwerkeinstellungen des Servers scheinen aber für den dnsbl check ignoriert zu werden. Der Server selbst kann problemlos auf spamhaus zugreifen, nur der dnsbl check schlägt weiterhin fehl.

Werden die Nameserver von irgendeiner Config File geholt und nicht von den networking/resolv.conf Einstellungen?

Wurde schon komplett neugestartet etc.

**Comment by andryyy** [comment]
Er nimmt unbound-mailcow, damit auch die DANE Checks funktionieren. Welchen Nameserver würdest du denn verwenden? Einen anderen privaten? Oder einen öffentlichen?

**Comment by lalaluuu** [comment]
Den BIND eines anderen Servers von mir.
Hm .. naja, ist ja nicht soo wichtig - hat mich jetzt nur gestört dass das irgendwie nicht ging.

Hast Du noch eine Idee ohne viel tam-tam damit die Spamhaus Queries dort funktionieren? 

Wäre ja auch für andere Hetzner Nutzer interessant.
Mich wunderts ja dass man zum Thema Spamhaus > Hetzner fast nichts findet.

**Comment by andryyy** [comment]
`docker-compose.override.yml` =>
```
version: '2.1'
services:
    rspamd-mailcow:
      dns:
        - 1.2.3.4
    postfix-mailcow:
      dns:
        - 1.2.3.4
```

Ungetestet. Danach `docker-compose up -d`

**Comment by lalaluuu** [comment]
Super, danke! Funktioniert :-)

Jetzt klingelts bei mir auch, wieso das mit den Systemeinstellungen für den DNS nicht gehen konnte ..

**Comment by ghost** [comment]
Ich bin gerade über diesen Thread gestolpert.
Meine Server stehen ebenfalls in einem Hetzner-Rechenzentrum.
In [diesen](https://groups.google.com/forum/#!topic/de.admin.net-abuse.mail/op8mUYME-Ks) Thread wird eine Möglichkeit zur Prüfung der Spamhaus-Erreichbarkeit erörtert.

Die Prüfung kann mit dem Befehl:
`dig +short @<DNS> 2.0.0.127.zen.spamhaus.org`
 durchgeführt werden

Bei meinen Servern habe ich das so getestet und sie scheinen nicht betroffen zu sein.

Im Postix-Log habe ich auch keine Einträge gefunden, dass Spamhaus nicht erreichbar wäre.

**Comment by lalaluuu** [comment]
Ich hatte es mit 4 verschiedenen Hetzner IPs in unterschiedlichen Netzen getestet. Bei mir waren leider alle betroffen. (Oben genanntes Befehls-Beispiel hatte keine Ergebnisse geliefert)

**Comment by ghost** [comment]
Auch mit diesen DNS-Servern?
[Hetzner Standard DNS](https://wiki.hetzner.de/index.php/Hetzner_Standard_Name_Server)

**Comment by lalaluuu** [comment]
Jo mit diesen, .. und mit lokalen Resolvern auf den jeweiligen Servern.
Gehts bei dir mit den Hetzner-Nameservern?

**Comment by ghost** [comment]
... interessant ...
Ich hatte bis vor kuzem noch zwei ältere Hetzner-Server, bin dann aber Anfang des Monats auf neue umgestiegen. Anscheinend sind die dort vergebenen IP-Adressbereiche noch "jungfräulich".

**Comment by andryyy** [comment]
¯\\_(ツ)_/¯
