### ISSUE TITLE
Error after update.sh and Cert change

### ISSUE THREAD

**Issue by FabiB97** [mailcow/mailcow-dockerized#1582]
i get the following lines after i updated mailcow and changed my certificate in the assets folder...
i checked the ports as you see in the code, but when i bring everything up it says the ports are in use
i rebooted the whole system various times but nothing seems to fix it

`root@Mail:~/mailcow-dockerized# docker-compose ps`
`Name   Command   State   Ports`
`------------------------------`
`root@Mail:~/mailcow-dockerized# netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995'`
`root@Mail:~/mailcow-dockerized# docker-compose up -d`
`Creating mailcowdockerized_watchdog-mailcow_1 ...`
`Creating mailcowdockerized_postfix-mailcow_1  ...`
`Creating mailcowdockerized_dovecot-mailcow_1  ...`
`Creating mailcowdockerized_memcached-mailcow_1 ...`
`Creating mailcowdockerized_mysql-mailcow_1     ...`
`Creating mailcowdockerized_dockerapi-mailcow_1 ...`
`Creating mailcowdockerized_clamd-mailcow_1     ...`
`Creating mailcowdockerized_postfix-mailcow_1   ... error`
`Creating mailcowdockerized_unbound-mailcow_1   ...`
`Creating mailcowdockerized_ipv6nat_1           ...`
`Creating mailcowdockerized_sogo-mailcow_1      ...`
`Creating mailcowdockerized_unbound-mailcow_1   ... error`
`ERROR: for mailcowdockerized_redis-mailcow_1  Cannot start service redis-mailcow: Address already in use`

`Creating mailcowdockerized_mysql-mailcow_1     ... error`
`Creating mailcowdockerized_watchdog-mailcow_1  ... done`

`Creating mailcowdockerized_dovecot-mailcow_1   ... done`
`Creating mailcowdockerized_memcached-mailcow_1 ... done`
`zed_postfix-mailcow_1 (2ab0c352679301b5f95928abd68300c2260918b8b5bbff80764168454Creating mailcowdockerized_dockerapi-mailcow_1 ... done`
`Creating mailcowdockerized_clamd-mailcow_1     ... done`
`ERROR: for mailcowdockerized_mysql-mailcow_1  Cannot start service mysql-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_mysql-mailcow_1 (394b35dad62a16c19c2888c1f4ac91da492c9c3e5efad4be6fefcdfcbaf2acd`
`Creating mailcowdockerized_sogo-mailcow_1      ... done`

`ERROR: for redis-mailcow  Cannot start service redis-mailcow: Address already in use`

`ERROR: for unbound-mailcow  Cannot start service unbound-mailcow: Address already in use`

`ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (2ab0c352679301b5f95928abd68300c2260918b8b5bbff807641684548fd7e43): Bind for 0.0.0.0:587 failed: port is already allocated`

`ERROR: for mysql-mailcow  Cannot start service mysql-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_mysql-mailcow_1 (394b35dad62a16c19c2888c1f4ac91da492c9c3e5efad4be6fefcdfcbaf2acdd): Bind for 127.0.0.1:13306 failed: port is already allocated`
`ERROR: Encountered errors while bringing up the project.`
`root@Mail:~/mailcow-dockerized#`

**Comment by andryyy** [comment]
Very sure anther mailcow instance is running. 

Update would not start another mailcow.

**Comment by FabiB97** [comment]
i managed to fix it when i kill all docker containers (`docker kill $(docker ps -q)`) and start them with `docker-compose up -d` again
but after a reboot sogo isn't available, the mailcow backend somehow still works

later when i killed the containers and started them again i get emails saying the sogo service hitting the error rate and restarting


also i got some images doubled which are pretty old

`root@Mail:~/mailcow-dockerized# docker images`
`REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE`
`mariadb                        10.2                43214e07b984        10 hours ago        401MB`
`mailcow/rspamd           1.23                ff664efa93c0        2 days ago          268MB`
`mailcow/sogo               1.28                2b5eb1b3ef24        5 days ago          470MB`
`mailcow/dovecot          1.30                11934017be7a        5 days ago          531MB`
`mailcow/clamd             1.12                d46df11751d8        5 days ago          91.9MB`
`mailcow/postfix            1.16                d6b761657c6c        6 days ago          224MB`
`mailcow/netfilter          1.17                6857b6f7b3fe        6 days ago          69.7MB`
`redis                             4-alpine            80581db8c700        6 days ago          28.6MB`
`memcached                 alpine              b40e8fa7e3e5        7 days ago          8.69MB`
`nginx                           mainline-alpine     920e5c5c8bed        10 days ago         18.6MB`
`mailcow/phpfpm        1.18                39330e4aabd2        13 days ago         301MB`
`nginx                           <none>              5dd52cc7079a        13 days ago         18MB`
`mailcow/acme            1.34                ee5e627bf0c4        2 weeks ago         52.9MB`
`mariadb                     <none>              6fe652377d21        2 weeks ago         401MB`
`mailcow/watchdog     1.19                95ea9a765ca8        2 weeks ago         61MB`
`mailcow/dockerapi     1.13                10854ca0292d        2 weeks ago         95.5MB`
`mailcow/clamd           <none>              8ef189520526        2 weeks ago         194MB`
`debian                         stretch-slim        3e235dbb0ba6        2 weeks ago         55.3MB`
`redis                           <none>              caaeda72bf8f        4 weeks ago         27.8MB`
`memcached               <none>              ac8ecd7127f3        5 weeks ago         8.07MB`
`mariadb                     <none>              2cbeee8bd9cf        2 months ago        399MB`
`nginx                         <none>              ebe2c7c61055        3 months ago        18MB`
`mailcow/unbound     1.1                 4b89d5b2bb6f        3 months ago        18.7MB`
`memcached              <none>              44e151ee7837        3 months ago        7.88MB`
`redis                          alpine              98bd7cfc43b8        3 months ago        27.8MB`
`robbertkl/ipv6nat      latest              20acd6529e3e        4 months ago        21.6MB`

**Comment by FabiB97** [comment]
i didnt restart the system to see if something else is wrong and the mailcow ui shows the following...

![image](https://user-images.githubusercontent.com/16006673/42864246-10c284a0-8a66-11e8-8d8b-e96a1087a656.png)


And the Watchdog from mailcow shows me that the Postfix container hits the error limit every 5 minutes and restarts

**Comment by andryyy** [comment]
You should try this (this will remove _all_ containers, not just mailcow):

```
docker-compose down
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker-compose up -d
```

**Comment by FabiB97** [comment]
that was it 😄 fixed the red labels on the containers and also the postfix restarting

> docker-compose down
> docker rm -f $(docker ps -a -q)
> systemctl restart docker
> docker-compose up -d

**Comment by muresanandrei** [comment]
This
```
 docker-compose down
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker-compose up -d
```
also solved redis error after january 2019 update.

**Comment by andryyy** [comment]
Which Redis error?

"docker-compose down" does remove all running containers, no rm -f needed, only if Docker failed.

**Comment by muresanandrei** [comment]
I had this error today without changing anything
` Uncaught RedisException: php_network_getaddresses: getaddrinfo failed: Try again in /web/inc/prerequisites.inc.php:26 Stack trace: #0 /web/inc/prerequisites.inc.php(26): Redis->connect(‘redis-mailcow’, 6379) #1 /web/index.php(2): require_once(‘/web/inc/prereq...’) #2 {main} thrown in /web/inc/prerequisites.inc.php on line 26`

**Comment by andryyy** [comment]
The name lookup for "redis" failed. Probably broken iptables rules.
The container was either not running or Docker broken. A restart does indeed fix the iptables rules. But make sure nothing messes with theses rules.

**Comment by Ayan-Ali** [comment]
@andryyy 

Thanks you are a life saver
