### ISSUE TITLE
Sending email from external client

### ISSUE THREAD

**Issue by mobeustech** [mailcow/mailcow-dockerized#1583]
I am unable to send email from thunderbird or evolution due to the following : 

> NOQUEUE: reject: RCPT from c-x-x-x-x.hsd1.co.comcast.net[x.x.x.x]: 553 5.7.1 <sitemanager@domain1.org>: Sender address rejected: not owned by user sitemanager@domain1.org; from=<sitemanager@domain1.org> to=<joshua@externalDomain.com> proto=ESMTP helo=<co2>

I am able to send emails from the SOGo app without issue to external email addresses.  I have tried to adjusting the "Allow to send as:" feature under the mailbox and selected all options Disabling sender checks but the error persists.  I have restarted the services and even rebooted the whole system.

I have tried to configure the email clients using both SMTP:465 and Submission:587.  No auth issues or errors in the logs.

**Comment by andryyy** [comment]
It is not a different map. It is the same for SOGos internal smtpd port and for ports 587, 465.

It would also not complain about you sending authenticated from a@b.cd as a@b.cd.

A git diff origin/master would be interesting as well as full logs of postfix-mailcow. A screenshot would be good. Maybe you replaced something useful here.

**Comment by mobeustech** [comment]
I only have 1 user on the domain.  No aliases or domain aliases.

> 7/17/2018, 3:24:01 PM | info | disconnect from c-107-2-220-12.hsd1.co.comcast.net[107.2.220.12] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=7/8
>
> 7/17/2018, 3:24:01 PM | info | NOQUEUE: reject: RCPT from c-107-2-220-12.hsd1.co.comcast.net[107.2.220.12]: 553 5.7.1 <sitemanager@fva.org>: Sender address rejected: not owned by user sitemanager@fva.org; from=<sitemanager@fva.org> to=<joshua@gmail.com> proto=ESMTP helo=co2>
>
> 7/17/2018,  3:24:01 PM | info | Anonymous TLS connection established from c-107-2-220-12.hsd1.co.comcast.net[107.2.220.12]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits) 
>
> 7/17/2018, 3:24:00 PM | info | connect from c-107-2-220-12.hsd1.co.comcast.net[107.2.220.12]

![domain](https://user-images.githubusercontent.com/36897333/42847275-af96895c-89d8-11e8-8756-aa431089e39d.png)
![mailboxes](https://user-images.githubusercontent.com/36897333/42847276-afb3085c-89d8-11e8-92f1-fe358576fe4b.png)
![resources](https://user-images.githubusercontent.com/36897333/42847277-afd0ddb4-89d8-11e8-80a3-8df82ac641f8.png)
![aliases](https://user-images.githubusercontent.com/36897333/42847278-afed762c-89d8-11e8-83a8-ee85d0ab79bc.png)
![domain_aliases](https://user-images.githubusercontent.com/36897333/42847279-b00a6638-89d8-11e8-842d-118c968ae098.png)
![address_rewriting](https://user-images.githubusercontent.com/36897333/42847280-b0357c1a-89d8-11e8-8e02-5df05632ae22.png)

**Comment by mobeustech** [comment]
This is a fresh install only about 1 week old.

**Comment by andryyy** [comment]
Can you mail me access to that (empty) mailbox? With your server name? info@servercow.de

**Comment by mobeustech** [comment]
The mailbox is not empty.  I migrated all the email from the old mail server (not mailcow).

**Comment by mobeustech** [comment]
@andryyy the email has been sent.

**Comment by andryyy** [comment]
I received no mail. :-(

**Comment by mobeustech** [comment]
I just sent it again

/Joshua


[cid:image001.png@01D3B20D.E5BF12E0]

Joshua Hopkins
O:719.425.8920 | M:719.209.1414
joshua@mobeustech.com<mailto:joshua@mobeustech.com>

**Comment by mobeustech** [comment]
@andryyy  I just sent it again

**Comment by andryyy** [comment]
Yes, and I could send mails without a problem. I wrote you from this account.
