### ISSUE TITLE
Extract / Split attachment to file

### ISSUE THREAD

**Issue by kont45** [mailcow/mailcow-dockerized#1584]
Have you know about possibility to split / extract attachment from mail to file? I'm trying to use "[munpack](http://manpages.ubuntu.com/manpages/xenial/man1/munpack.1.html)" but without positive effect.  

```
munpack 1531844820.M999393P1488.mail.MYDOMAIN.COM
Did not find anything to unpack from 1531844820.M999393P1488.mail.MYDOMAIN.COM
```
Moreover after unsuccessful splitting attachment I was trying ripmime. And we have got another problem. Something has been extracted as a textfile0 but it's not original attachment. Seems as a encoded file or with unknown header:

```
admin@admin:/home/ja# file *
textfile0: data
```

**Comment by andryyy** [comment]
Mails are compressed. You will need to decompress them or use doveadm. You probably have the Message-ID, right?

```
docker-compose exec dovecot-mailcow doveadm search -u 'me@domain.tld' HEADER Message-ID 'a-msg-id'
# Output example:
# asdasdasdasd000033a69f92 1123
```

Now fetch the message:
```
docker-compose exec dovecot-mailcow doveadm fetch -u 'me@domain.tld' text mailbox-guid asdasdasdasd000033a69f92 uid 1123
```

**Comment by kont45** [comment]
Ok, Thanky you @andryyy. It works now, but there is another problem. 

Our script should extract attachment from all files:
```
#!/bin/bash
docker-compose exec dovecot-mailcow doveadm search -u user mailbox INBOX > all.txt
while read guid uid;
do
docker-compose exec dovecot-mailcow doveadm fetch -u user text mailbox-guid "$guid" uid "$uid" > "$uid".txt
done < all.txt
```
Unfortunately 5th line is not doing correctly. I mean that script creates empty files. If you could improve it could be useful to other people.

**Comment by andryyy** [comment]
I don't really have time to work on fixing your script. :-( If you need to run it like this, you should use the exposed doveadm listener on 127.0.0.1:19991 (I think), as it does not hammer docker-compose, which is rather slow.

Or you could cp the script to dovecot-mailcow and run it there, like:
```
docker cp myscript.sh mailcowdockerized_dovecot-mailcow_1:/
```
Once it is copied to dovecot-mailcow, you can run it inside this container with `docker-compose exec dovecot-mailcow /myscript.sh`.

Or "just" decompress the files in the vmail directory when reading them.

**Comment by kont45** [comment]
Thanks. We will check this.

**Comment by Viktova** [comment]
@andryyy excuse me for bringing this up here, but where can i find the message ID on the server? is it stored in a file? or in the db? etc..
i know we can get the message ID via rspamd web UI, but i want the source of where that message ID is being pulled from.

so far i know it's doveadm related which must be inside the dovecot container no? but i almost searched the whole container and couldn't find any sign of the IDs.

I'm suspecting that it's located inside: `/var/vmail/domain.tld/user` dovecot* files, but they are encrypted
