### ISSUE TITLE
Alias domain doesn't work with alias mailbox

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#1585]
Hi,

let's assume there are two domains:
abc.com and
xyz.com

In abc.com I would like to put all my users mailboxes whereas xyz.com is only an alias domain for abc.com.
I assume that emails to e.g. user1@xyz.com will be moved into the mailbox user1@abc.com and for all other users respecitvely.

What if there is a mailbox alias like that:
oldusername@abc.com -> currentuser@abc.com

When I now try to send to oldusername@xyz.com it gets rejected with
`postfix-mailcow_1    |^[[0m Jul 18 13:14:16 myhostname postfix/smtpd[18351]: NOQUEUE: reject: RCPT from myhostname[1.2.3.4]: 550 5.1.1 <oldusername@xyz.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<sender@email.de> to=<oldusername@xyz.com> proto=ESMTP helo=<myhostname>`
Only when I create an additional alias
oldusername@xyz.com -> currentuser@abc.com
it works. Why is that? I would assume that I wouldn't have to create the additional alias.

**Comment by andryyy** [comment]
This was changed about a year or more ago. We had much more people asking for independent aliases than the other way round. 

This is expected and mentioned in the docs. :-)

**Comment by imp1sh** [comment]
ty
