### ISSUE TITLE
Question: service behind mailcow proxy

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#1586]
I have a web service that can run on any port that I need to connect through.
Currently, I bypass and just use the IP x.x.x.x:3333
To gain access.
Is there an easy way I can use mailcow to reverse proxy this for me?
So I could go to mail.mailcow.com/service1 

All the websites are at a different location so all I have at this location is mailcow and my service

**Comment by mitchellurgero** [comment]
under data/config/nginx you can use the nginx service to reverse proxy it.

**Comment by kilo42L** [comment]
thank you very much.
Do you know if this will get overwritten by updates?

**Comment by andryyy** [comment]
I added a Nginx section to the docs.

**Comment by kilo42L** [comment]
Andryyy, your awesome man.
:)
