### ISSUE TITLE
Send mail to all mailboxes hosted in / on mailcow

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1587]
Is there a possibility to send a mail - e.g. notifications about updates, maintenances, .. - to all mailboxes hosted on / in mailcow?

**Comment by andryyy** [comment]
This was asked before.

Enotime (tm).

**Comment by chriscroome** [comment]
See: Ability to send an announcement to all users #842

**Comment by andryyy** [comment]
I will try to add it soon. But time is really a problem right now. :-(
