### ISSUE TITLE
Webinterface + Sogo down with 504

### ISSUE THREAD

**Issue by awesome-michael** [mailcow/mailcow-dockerized#1588]
Yesterday the webinterface and Sogo weren't accessible anymore. The reverse proxy throws a 504 error. I restarted the whole container stack a few times without effect and executed update.sh also with no effect on the error.
I noticed that the netfilter container (tag 1.17) keeps restarting every few minutes.
The logs of netfilter show the following error multiple times:
```
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 57, in <module>
netfilter-mailcow_1  |     if r.exists('F2B_LOG'):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 951, in exists
netfilter-mailcow_1  |     return self.execute_command('EXISTS', name)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
netfilter-mailcow_1  |     connection.send_command(*args)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
netfilter-mailcow_1  |     self.send_packed_command(self.pack_command(*args))
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
netfilter-mailcow_1  |     self.connect()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
netfilter-mailcow_1  |     raise ConnectionError(self._error_message(e))
netfilter-mailcow_1  | redis.exceptions.ConnectionError: Error 110 connecting to 172.33.1.249:6379. Operation timed out.
```

The redis container is up and running and I can connect without problems.
Also the Sogo container keeps spamming `Waiting for database initialization...` into its logs, but mariadb is also up, running and I can connect by hand without problems.

Does the netfilter error cause the 504 error because all the internal (docker-)network traffic is managed by netfilter?
Have you got an idea how to fix the netfilter container?

**Comment by andryyy** [comment]
This is not the netfilter container. This is more likely a firewall.

**Comment by awesome-michael** [comment]
I have no idea what went wrong but after I rebooted the whole server now everything works just fine.
I'll close that issue for now and hope the error doesn't return after a while.
Thanks for helping and the great project.
