### ISSUE TITLE
redirect http to https, what about acme-challenge?

### ISSUE THREAD

**Issue by lug-gh** [mailcow/mailcow-dockerized#1589]
hi, 

i want to redirect all http traffic to https, but does acme-challenge work after that?
https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

i dont see any exception for /\.well-known/acme-challenge in there.

or is that a different container then?

**Comment by mkuron** [comment]
The ACME validation service follows redirects, so you don't need to do anything specific for it.
