### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by PhoenixPeca** [mailcow/mailcow-dockerized#159]
Hi Andre,

Allowing mailcow-dockerized to run on **HTTP** is something we should not be considering to prevent hackers from eavesdropping into our connection. I am talking about the security of our mailserver here. And no, I am not proposing to remove support for HTTP again. I am saying that we should redirect all HTTP traffic to HTTPS for encryption. 😉

**Comment by andryyy** [comment]
Hi, no, think of reverse proxys. Most want to offload SSL.

**Comment by PhoenixPeca** [comment]
thanks for clearing that out..

**Comment by ThomasLeister** [comment]
Just stumbled upon the same issue - thanks for clarifying!

**Comment by andryyy** [comment]
:) Perhaps we can ask it when running generate_config.sh and notice about deleting the redirect.conf when a RP should be used.
