### ISSUE TITLE
[Question] Serving SOGo on multiple domains

### ISSUE THREAD

**Issue by Pyton** [mailcow/mailcow-dockerized#1590]
Hi. 

I'm looking for the best approach to serve SOGo on multiple domains.
I have main server on `mail.example.com` 
I also added few domains: `domainA.com`, `domainB.com`.
I want SOGo to be visible on: `webmail.domainA.com` and user able to login only for accounts from this domain so user CAN login as `contact@domainA.com` and CANT `contact@domainB.com`

BUT... I want to be able login on all account from main server domain `mail.example.com`

I know it's little confusing but I hope it's achievable :)

**Comment by mkuron** [comment]
SOGo can't do that. You would need to run one SOGo instance for each domain with a separate config file, and I wouldn't suggest that as it consumes quite a bit of memory.
