### ISSUE TITLE
How hard is it to split mailcow into 2 mailcow instances?

### ISSUE THREAD

**Issue by phibla** [mailcow/mailcow-dockerized#1593]
Currently, we are using mailcow with two domains/groupwares on one server and now we want to transfer one domain+groupware to another server. Is it possible? Is there any guide? Thanks in advance

**Comment by mkuron** [comment]
I guess the process is roughly like this and not even Mailcow-specific:

1. change the MX record for domain B to point to the new server B
2. stop Mailcow on server A to clear the DNS cache and to ensure no messages are accepted while the migration is in progress (they will be re-delivered later)
3. install Mailcow on server B, restoring a complete backup from server A
4. on server A, disable the Postfix container by commenting the corresponding lines in docker-compose.yml, start up Mailcow again and check "Backup MX" in the settings for domain B. Then re-enable Postfix
5. delete domain A from server B
6. wait 48 hours
7. delete domain B from server A
