### ISSUE TITLE
DNS setup for multiple domains

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1595]
Hello,
when using multiple domains (`mail.dom1.mx, mail.dom2.mx`) what DNS values do I need for my `dom2` domain e.g. autodiscover/autoconfig and for the SRV records? Do I use `mail.dom2.mx` or do I refer to my main domain which is also the mailcow hostname (in this case `mail.dom1.mx`)? 
When setting up the mail account (`test@dom2.mx`) with` mail.dom2.mx` it can't reach a connection however using `mail.dom1.mx` works fine. Do I also need to add` mail, autodiscover` and `autoconfig.dom2.mx` to ADDITIONAL_SAN?

**Comment by mkuron** [comment]
You only use one hostname (mail.dom1.com) even if you have two domains (dom1.com and dom2.com). No need to use ADDITIONAL_SAN. And all DNS records point to the same hostname. You can click on the DNS button next to the domain in the admin UI to see what the records should be.

**Comment by amrnassar93** [comment]
i did that and still my messages blocked by gmail for authentication failure as it sees the server with a different name from the domain name.

Any suggestions ?

**Comment by andryyy** [comment]
That’s not related. It just fails DKIM or SPF, I think. 

You need to post the reject, please

**Comment by amrnassar93** [comment]
i setup the SPF record (v=spf1 mx ~all) and DKIM record generated by the adminstration panel and still gmail block messages from the second domain while the first domain's messages are passing good.

**Comment by amrnassar93** [comment]
this is the reject : host gmail-smtp-in.l.google.com[66.102.1.26] said:
    550-5.7.1 This message does not have authentication information or fails to
    pass 550-5.7.1 authentication checks. To best protect our users from spam,
    the 550-5.7.1 message has been blocked. Please visit 550-5.7.1
    https://support.google.com/mail/answer/81126#authentication for more 550
    5.7.1 information. p3si12865383wrj.146 - gsmtp (in reply to end of DATA
    command)

**Comment by andryyy** [comment]
Yes, DKIM, SPF or something else fails. Might even be a missing PTR (not sure though).

**Comment by amrnassar93** [comment]
Can you please recommend what should be the SFP and the DKIM records ?

**Comment by andryyy** [comment]
DKIM can be generated in the UI. SPF depends on what you want/need. You probably try to send from a domain that does deny your mail server from sending. You can check the current SPF record for your sender domain by running `dig txt domain.tld` and see if it lists your mailcow in the given SPF record (if any). But that's something you better ask on IRC. :)
