### ISSUE TITLE
unbound resolving issue

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1596]
All the docker containers use the unbound container to resolve DNS. This is good. But unbound container can not resolve anything. There is no external firewall active which maybe blocks DNS traffic. The only thing I see is in unbound container the /etc/resolv.conf contains two nameserver entries.
search example.com
nameserver=127.0.0.11
nameserver=<my ipv6 DNS address>
options ndots:0

Is this second nameserver entry causing unbound can not resolve anything? And how to solve this?

**Comment by andryyy** [comment]
127.0.0.11 is the Docker DNS proxy service and correct. Unbound does not use a resolver, it is a resolver.

All containers will use 127.0.0.11, no matter their DNS settings. That's to include internal names of Docker containers.

Please post your changes to docker-compose.yml (or any override). The second and empty record is not default.

**Comment by hunter-nl** [comment]
Second entry is not empty (lost in the message) but contains my second dns server IPv6 address as specified on the host where docker is running. 
I did not made any change to the docker-compose.yml and no override file exist.
After the start by ‘docker-compose up -d’, a short moment (about a minute) the resolving is working. After that it will not work anymore.
Netfilter is not banning anything.

**Comment by minimins** [comment]
any SNAT?

**Comment by hunter-nl** [comment]
Yes, I've configured in mailcow.conf the SNAT setting for IPv4 and IPv6.

**Comment by minimins** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/302#issuecomment-340477511

Have a look at that

**Comment by hunter-nl** [comment]
I did have a look at #302 and tried solution mentioned. But this makes no difference. I keep the issue. As unbound can not access /dev/stdout, I can also not debug what's going on inside unbound. Is there already a solution for #585? It makes it difficult to troubleshoot now without the output of unbound.

**Comment by andryyy** [comment]
Regarding this and the issue opened a few minutes ago, you should check your network setup. Internal communication seems to be problematic.

**Comment by hunter-nl** [comment]
I've found the cause. Unbound config file has lines with "private-address", example:
`private-address: 192.168.0.0/16`
This means that any answer containing an IP address in this range will be stripped. In debug logging of unbound you will see:
`sanitize: removing public name with private address` And as sources/destinations of mail traffic are also on my internal network and in this private ranges, it can never be resolved. Because unbound will just strip the "private" IP addresses. After I removed the private-address entries, everything is just working fine.
The access-control lines determine which systems can use unbound as dns resolver.

**Comment by danlorb** [comment]
I have the same DNS resolve Issue with unbound. My Infrastructure is configured with vlan and subnetting. 

Example: Mailcow runs in my environment in Network 170.20.20.224/27, and this was my problem. To fix the Problem i have to add follow Settings to data/conf/unbound/unbound.conf

access-control: 170.20.20.224/27 allow
private-address: 170.20.20.224/27

Restart your envrionment. After this mailcow runs as expected.

Suggestion:
Please make the unbound Configuration configurable in the mailcow.conf

Thanks to your great work.

**Comment by hunter-nl** [comment]
I've fixed it by enabling ipv4 forwarding in the host. In Centos host I added a file /etc/sysctl.d/99-mailcow.conf with content
`net.ipv4.ip_forward=1`

Second: I added to unbound.conf
`forward-zone:`
`<tab>name: "."`
`<tab><tab>forward-addr: first internal dns ip4/ipv6 address`
`<tab><tab>forward-addr: second internal dns ip4/ipv6 address`

So it can now resolve also internal dns zones.
