### ISSUE TITLE
Mailcow UI Mailboxes tab: back button / previous page link always goes back to page 1

### ISSUE THREAD

**Issue by lobsterclaws** [mailcow/mailcow-dockerized#1598]
Hi. 

In the Mailcow UI Mailboxes admin tab (mailbox.php), where all email accounts are listed, whenever you click the browser back button, it always takes you back to the first page of the list, even if the previous page was a later page. Same thing for the 'previous page' link in the mailbox account settings Edit.php pages for each email account - whichever page the Edit page was accessed from, clicking the browser back button or the 'previous page' link takes you back to the first page of the list.

**Comment by andryyy** [comment]
Hi,

Thanks for your feedback. That's annoying, yes. I fixed it but need to run a few tests on this code. It will work for all tables and also adds a counter to the mailbox tables.

**Comment by lobsterclaws** [comment]
Wow, that was quick! Amazing! Thanks very much!
