### ISSUE TITLE
Refresh buttons no longer working (in Safari)

### ISSUE THREAD

**Issue by Geitenijs** [mailcow/mailcow-dockerized#1599]
As of (one of) the latest patches, the refresh button doesn't work anymore in Safari. I haven't tested it in another browser.

I'm using Safari 11.1.2 on macOS 10.13.6.

**Comment by andryyy** [comment]
The debug log refresh button?

You probably just need to clean your cache.

**Comment by Geitenijs** [comment]
Whoops.. I thought I did that already, sorry!
