### ISSUE TITLE
Postfix queue lost on upgrade

### ISSUE THREAD

**Issue by lgleim** [mailcow/mailcow-dockerized#16]
Not sure where this is stored but the queue folder should be persisted on a data or host volume in order to survive container upgrades.
At the moment anything that has not yet been delivered will silently be lost.

**Comment by tehXor** [comment]
A workaround (well I guess actually it's also the best way to do it but I'm not sure) is to add `/var/spool/postfix/` to the volumes of `postfix-mailcow`.

**Comment by miclnl** [comment]
> A workaround (well I guess actually it's also the best way to do it but I'm not sure) is to add /var/spool/postfix/ to the volumes of postfix-mailcow.

Yes this will probably work. Create a dedicated volume in the compose file and link/mount that to `/var/spool/postfix` in the postfix-container. Volumes are persistent and keeping it separate from the host-system would allow you to run another mail service without problems.

**Comment by andryyy** [comment]
Implemented it (finally...). :-)
