### ISSUE TITLE
Add custom parameters to imapsync

### ISSUE THREAD

**Issue by discofris** [mailcow/mailcow-dockerized#1601]
Would be great if we could add extra custom parameters to the Sync Jobs.

`--delete2folders` is one of them.

Adding the parameter to 

> data/Dockerfiles/dovecot/imapsync_cron.pl

 would be erased by a next ./update.sh. Correct?

**Comment by andryyy** [comment]
Indeed, that's a good idea.

Oh, and yes, it would be deleted.

**Comment by discofris** [comment]
I ended up using ImapSync outside of mailcow-dockerized. Simply installed it on my box and added a cron job.
I noticed the version you are using is quite old. I saw some parameters I couldn't find any doc on.

I'm still in favourite in using it on mailcow, because the webgui you've made around it is **really slick and nice**!

**Comment by andryyy** [comment]
It is almost implemented now. :-)

Need to run more tests. I also moved the "hard coded" settings to parameters in mailcow UI (--subscribe, timeout etc.).

Thanks! 👍

**Comment by andryyy** [comment]
Can you test it?

**Comment by discofris** [comment]
I’ll certainly do. I have some other prioroties (holiday) now ... 😬

**Comment by andryyy** [comment]
That's indeed more important. :-) Have fun.

**Comment by discofris** [comment]
Checking the list ...
- [x] Newest version
- [x] Possibiltity to add custom parameters
- [x] Thoroughly tested

Conclusion, really great addition!! I'm using it again on my 2nd (backup) MC server.
Thanks André 🥇
