### ISSUE TITLE
strange error on netfilter redis client

### ISSUE THREAD

**Issue by scher200** [mailcow/mailcow-dockerized#1602]
error straight after doing docker-compose up -d:
```
netfilter-mailcow_1  |   File "/server.py", line 55, in <module>
netfilter-mailcow_1  |     if r.exists('F2B_LOG'):
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 951, in exists
netfilter-mailcow_1  |     return self.execute_command('EXISTS', name)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
netfilter-mailcow_1  |     connection.send_command(*args)
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
netfilter-mailcow_1  |     self.send_packed_command(self.pack_command(*args))
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
netfilter-mailcow_1  |     self.connect()
netfilter-mailcow_1  |   File "/usr/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
netfilter-mailcow_1  |     raise ConnectionError(self._error_message(e))
netfilter-mailcow_1  | redis.exceptions.ConnectionError: Error 110 connecting to 173.22.1.249:6379. Operation timed out.
```

**Comment by andryyy** [comment]
Probably a firewall.

**Comment by scher200** [comment]
sounds like it, but after updating to version 1.17 everything works well:
```
    netfilter-mailcow:
      image: mailcow/netfilter:1.17
```
(docker-compose.yml or better docker-compose.override.yml)

**Comment by scher200** [comment]
oops, not exactly, got the same error again, what can I do?
I use ufw and opened all ports as described in documentation..

**Comment by mkuron** [comment]
> docker-compose.override.yml

Don't just use the newer image, upgrade the entire Mailcow.

> `173.22.1.249`

Looks like you changed the IPv4 network that Mailcow uses internally. Try the original addresses instead, changing them requires some extra care.

> ufw

Opening ports is not sufficient. Docker (not Mailcow) creates a number of iptables rules automatically and this is generally not compatible with firewalls. Therefore, please disable any iptables-based firewalls.
