### ISSUE TITLE
Unable to list SoGo GAL from MacOS contact app

### ISSUE THREAD

**Issue by chihoko** [mailcow/mailcow-dockerized#1606]
I have configured a MacOS client using the profile downloaded from the documentation. We have a small org with < 50 users and would like to be able to view all contacts in the GAL from within the MacOS contacts app. Whilst I can list the GAL in Sogo I can only search it from within the MacOS contacts app. I assume this is done for performance reasons.

**Comment by mkuron** [comment]
The GAL does not sync and cannot be viewed. You can only search it. That is a limitation of the CalDAV protocol.
