### ISSUE TITLE
clamav: false positives => Suggestion for relief

### ISSUE THREAD

**Issue by Arkaniod** [mailcow/mailcow-dockerized#1607]
I have similiar problems with false positives like in [#990](https://github.com/mailcow/mailcow-dockerized/issues/990) or [#1393](https://github.com/mailcow/mailcow-dockerized/issues/1393).

Wouldn't it be a way to integrate an empty local.ign2 which Admins could feed with their own exceptions and copy that file on startup of the container in the clamav database-folder? I think better than disabling PUA detection... Mentioned [here](http://lists.clamav.net/pipermail/clamav-users/2016-March/002710.html)

Just a thought...

Regards

Chris

**Comment by andryyy** [comment]
Thanks, added it.

**Comment by Arkaniod** [comment]
@andryyy : Cool, thanks a lot. Hope this will help others in future, too
