### ISSUE TITLE
How to remove a user spam filter from Rspamd settings map?

### ISSUE THREAD

**Issue by flybyray** [mailcow/mailcow-dockerized#1608]
https://github.com/mailcow/mailcow-dockerized-docs/blob/master/docs/u_e-mailcow_ui-spamfilter.md

It is not possible to reset/remove user settings even if you setup the default values it is not removed.

**Comment by flybyray** [comment]
maybe that is one solution
```sql
delete from filterconf where prefid = ...;
```

**Comment by andryyy** [comment]
I don’t understand. 

Just set it to 5/15.

**Comment by flybyray** [comment]
I think that is not the same.
I seem to experience a difference in overalll behaviour if there is a defaultvalue or null (means no row in database). Especially if you globally change the reject graylisting and other trasholds the user settings have some higher priority. Setting back to the defaults for the user is the only case at the moment where you could (as user) believe you are back at original (no value). But that is not the case.

**Comment by andryyy** [comment]
If you decide to set a fixed limit, remove the feature from mailcow for users.

**Comment by flybyray** [comment]
not needed anymore. the mailcow works fine with defaults if learning is disabled, and enduser have a possiblility to (un)learn the system via api.
