### ISSUE TITLE
X25519 curve and CHACHA20-POLY1305 cipher not working

### ISSUE THREAD

**Issue by Geitenijs** [mailcow/mailcow-dockerized#1611]
The X25519 curve and the CHACHA20-POLY1305 cipher are not working in Nginx, probably due to an outdated version of OpenSSL. And because secp256r1 and secp384r1 are not considered as secure as X25519 (https://safecurves.cr.yp.to), we should at least have the possibility to use X25519.

**Comment by andryyy** [comment]
Please explain why they are not considered secure anymore (which attacks) and tell us the compatibility issues (which clients will be excluded) we will run into when switching methods.

**Comment by Geitenijs** [comment]
I've edited my original post a bit.

Safari supports X25519 as of version 11, which was released in September 2017.
Firefox supports X25519 as of version 51, which was released in January 2017
Chrome supports X25519 as of version 50, which was released in April 2016.
Opera supports X25519 as of version 41, which was released in October 2016
Edge supports X25519 as well. I can't find as of which release though.
IE does _not_ support X25519, however [browser statistics](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) show that it's market share is just around 5%

Then again, I'm not saying we should switch entirely. We should just have to possibility if anyone wants to, or we can set "ssl_ecdh_curve" in nginx to something like "X25519:secp256r1:secp384r1:secp521r1" so that client compatibility won't become worse.

**Comment by Knight1** [comment]
There is already a PR for this https://github.com/mailcow/mailcow-dockerized/pull/1527

**Comment by Geitenijs** [comment]
@Knight1 not at all... That PR is about specifying secp384r1 as the only curve, while this issue is about making X25519 and CHACHA20-POLY1305 work.

**Comment by Knight1** [comment]
Open a PR?
