### ISSUE TITLE
Disable Temporary Aliases

### ISSUE THREAD

**Issue by keithjoshua** [mailcow/mailcow-dockerized#1613]
Hi mailcow team, I am hosting a school's email services with an ".edu" domain. Together with the ".edu" emails are the various freebies that are available to the students like Amazon Prime and [Office 365 for students/teachers](https://products.office.com/en/student/office-in-education), etc..

I am afraid that these exclusive services might be abused by the students using the Temporary Aliases feature. So, I think it would be great if Mailcow can have a toggle option for this feature.

**Comment by keithjoshua** [comment]
As of the moment, I have edited some php files to have this feature disabled. But I don't think i am using the best approach for this because It can break on updates.

would be really great to have this feature official tho.

**Comment by andryyy** [comment]
It is about to come with ACL.

One way to disable it is to run `docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "UPDATE user_acl SET spam_alias = 0";` after adding a new user. 

I hopefully find time to complete this feature soon.

**Comment by keithjoshua** [comment]
ok thanks!
