### ISSUE TITLE
rspamd no rrd configured

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#1614]
Hi,

is there a solution for the "no rrd configured" error within the rspamd webinterface troughput graph?

As i see, this appears also in the mailcow demo, so this may occurs to several other users.

I already tried the stuff of chowning- deleting and purging the rrd-file - without success.

Greetings

**Comment by andryyy** [comment]
English?

Issue opened @ Rspamd?

**Comment by lalaluuu** [comment]
Not yet - will do this asap.

I already searched for this issue outside of mailcow and was wondering that i didn't find much about this issue outside of mailcow.

**Comment by andryyy** [comment]
:-) 

Thanks!

**Comment by mitchellurgero** [comment]
Not that it matters here it looks like the code for this specifically means there was a "404" error in the backend (Taken from upstream source for RSPAMD /src/controller.c):

```C
if (ctx->rrd == NULL) {
    msg_err_session ("no rrd configured");
    rspamd_controller_send_error (conn_ent, 404, "No rrd configured for graphs");
    
    return 0;
}
```

**Comment by zeigerpuppy** [comment]
I recently got this error after changing `MAILCOW_HOSTNAME`
Previously the throughput graph was working

**Comment by andryyy** [comment]
Clean your cache, please.

**Comment by zeigerpuppy** [comment]
resetting browser cache and restaring mailcow don't have any effect.

the throughput page show the following errors:

```
cannot receive throughput data
request failed
```

The error is related to this message in the logs:

```
rspamd-mailcow_1     | 2019-01-25 07:50:41 #11(controller) <13cde6>; csession; rspamd_controller_handle_graph: no rrd configured
```

all the other rspamd gui elements work properly and are up to date

**Comment by andryyy** [comment]
I don't see that here.

You should ask in Rspamds issue list.

Or clear the cache (do not just clean a single page or just via network inspector etc.), close the browser completly (!) and restart it.

**Comment by zeigerpuppy** [comment]
i tried a different browser on a different computer!  same error, so can't be the cache.  I think it may be related to changing domain, maybe the rspamd rule didn't get updated, will see if I can trace the error.

**Comment by andryyy** [comment]
Can you try to delete rspamd.rrd? => `docker-compose exec rspamd-mailcow rm /var/lib/rspamd/rspamd.rrd`? Restart Rspamd afterwards.

**Comment by zeigerpuppy** [comment]
the same error occurs after deleting that file:

```
rspamd-mailcow_1     | 2019-01-25 11:08:33 #11(controller) <32f29b>; csession; rspamd_controller_handle_graph: no rrd configured
```

**Comment by zeigerpuppy** [comment]
this bug may be related https://github.com/rspamd/rspamd/issues/2405

However, when I cat `/etc/rspamd/worker-controller.inc` the `count` seems OK

```
count = 1;
password = "q1";
secure_ip = "127.0.0.1";
secure_ip = "::1";
static_dir = "${WWWDIR}";
```

**Comment by zeigerpuppy** [comment]
I'm thinking of starting from scratch with the rspamd container.  
If I remove the volume and rebuild I guess I'll lose the history data and spam learning, but I can live with that.  Is there anything else that would be lost by starting with a clean container?

**Comment by zeigerpuppy** [comment]
this was fixed by:

```
docker-compose stop rspamd-mailcow
docker-compose rm rspamd-mailcow
docker-compose up -d
```

not sure what the error was, but the above worked without disrupting settings

**Comment by andryyy** [comment]
Hm. Sounds like Rspamd wrote the name to another location. I will try to trace it. 

Running docker-compose down and up -d is necessary anyway when you change the hostname. :) You just run up -d?

**Comment by zeigerpuppy** [comment]
i had previous run `down` and `up` but only `rm` fixed the error

**Comment by andryyy** [comment]
Down does the same. Strange.
