### ISSUE TITLE
SOGo: display birthdays in calendar

### ISSUE THREAD

**Issue by wuha** [mailcow/mailcow-dockerized#1616]
Gibt es eine Möglichkeit die Geburtstage der Kontakte im Kalender anzuzeigen?

**Comment by mkuron** [comment]
No, and there is a long-standing feature request for this at SOGo: 
https://sogo.nu/bugs/view.php?id=504. You can of course do it client-side though: iPhone and Apple Calendar display a birthday calendar by default, in Thunderbird you can install thunderBirthDay, ....
