### ISSUE TITLE
Docker DNS concurrent query limit hard coded to 100

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#1618]
I'm seeing lines like this in `var/log/syslog` on a Mailcow host several times a day:

```
Jul 31 09:04:10 example dockerd[29168]: time="2018-07-31T09:04:10.426904946Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.9:43097"
```
This has been logged 4 times today, 8 times yesterday, 3 the day before (a Sunday), 1 the day before, and 9 the day before that (a Friday, the mail server is used a lot less at weekends).

It would appear that this is a Docker issue and [the DNS concurrent queries limit of 100 is hard coded](https://github.com/docker/libnetwork/issues/2214).

I have had several reports of email problems from non-technical users and perhaps this could be a cause of the problems they have been having?

In `/etc/default/docker` there are no un-commented lines, it would appear to me that it would be sensible to add the local LAN dns servers into this file and restart Docker:

```bash
# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
```

Does anyone else have any other suggestions?

**Comment by chriscroome** [comment]
Actually since the server is running Debian Stretch and systemd it would appear that according to [this page](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/) a `/etc/docker/daemon.json` file is needed, containing something like this (updated with the local DNS servers):

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```

This will get over the Google DNS query limit but not the Docker one.

**Comment by chriscroome** [comment]
Having set the DNS resolvers for Docker in both `/etc/docker/daemon.json` and `/etc/default/docker` to a pair of Bind 9 servers on the local network and after updating to the latest Composer and updating to the latest Mailcow I'm still getting error like this in the `/var/log/syslog`:

```
Jul 31 19:07:36 example dockerd[5963]: time="2018-07-31T19:07:36.357383900Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.12:43732"
```
Is [this comment](https://github.com/docker/libnetwork/issues/2214#issuecomment-409204498) worth a follow up?

> could you set up a caching resolver and point your cluster at that instead of Google's DNS?

I'm not clear exactly where (which process in which container) all the DNS queries are from but following them on the host via `tcpdump udp port 53` they all, kind of, look like typical queries a mail server getting hit by a lot of spam would get.

Am I correct in assuming that all the Mailcow containers use the unbound container to resolve DNS lookups and that I'm seeing the 100 concurrent queries limit being hit by requests from unbound?

If that is the case do busy Mailcow servers need to have a small virtual server running unbound outside of Docker or perhaps we should run unbound on the virtual server which is running Docker?

Any other ideas about how to work around this Docker limit?

**Comment by chriscroome** [comment]
I'm still seeing this around half a dozen times a day:

```
grep "more than 100 concurrent queries" /var/log/syslog
Aug  2 07:05:40 example dockerd[5963]: time="2018-08-02T07:05:40.572676247Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.12:37226"
Aug  2 12:29:41 example dockerd[5963]: time="2018-08-02T12:29:41.197974703Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.12:36008"
Aug  2 14:25:48 example dockerd[5963]: time="2018-08-02T14:25:48.805442856Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.12:50909"
Aug  2 16:09:28 example dockerd[5963]: time="2018-08-02T16:09:28.510186582Z" level=error msg="[resolver] more than 100 concurrent queries from 172.22.1.12:35743"
```

Going through the container IDs to work out which one was triggering these, until we have a match for the IP address:

```
docker ps | grep 9a84db2ae04a
9a84db2ae04a        mailcow/rspamd:1.23      "/docker-entrypoint.…"   2 days ago          Up 2 days                                                                                                                                                        mailcow_rspamd-mailcow_1

docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 9a84db2ae04a
172.22.1.12
```
So it is the mailcow/rspamd container which is the cause of the greater than 100 concurrent DNS lookups.

So my first question is, does the rspamd container use the unbound container for DNS lookups?

Trying to find the answer to this...

```bash
docker-compose exec rspamd-mailcow /bin/bash
root@rspamd:/# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```
Does `127.0.0.11` resolve to the Unbound container?

**Comment by chriscroome** [comment]
Since implementing two suggestions from @andryyy in `data/conf/rspamd/local.d/options.inc` (but using our local DNS servers rather than Cloudflare):

```
dns { nameserver = ["1.1.1.1"]; }
disable_monitored => disable_monitoring;
```
I haven't had any of the "more than 100 concurrent queries" errors in `/var/log/syslog`.

**Comment by chriscroome** [comment]
Just to note that the maximum number of concurrent DNS lookups has been increased by the Docker project and the next version should contain this fix, see:

https://github.com/docker/libnetwork/issues/2214#issuecomment-430950324

I'd suggest however that if there was an variable in `mailcow.conf`, for example:

```bash
# Optionally uncomment this to use alternative DNS resolvers,
# to the Docker Google defaults, comer separate multiple IP 
# addresses, for example (to use Cloudflare and Quad9):
# DNS_SERVERS=1.1.1.1,9.9.9.9
```

And if the variable was uncommented and if the IP address(s) provided did provide a domain name resolution service then the `/etc/docker/daemon.json` file could be updated to match, for example:

```json
{
    "dns": ["1.1.1.1", "9.9.9.9"]
}
```

But perhaps most people are happy using Google for their DNS lookups?

**Comment by andryyy** [comment]
It shouldn't be a problem anymore anyway. I guess it was due to the private-address fields in unbound-mailcow or the Rspamd option we changed a while ago. I have not seen it happening on our managed cows. 

And no, you should not use public resolvers for mailing (blacklist lookups etc.).

You can also check the updated docs, I think I recently added a section to add forwarders. 👍

**Comment by EnriqCG** [comment]
> And no, you should not use public resolvers for mailing (blacklist lookups etc.).

Why is that?

**Comment by andryyy** [comment]
Many if not all DNSBLs have rate limites. The biggest public resolvers are almost always blocked or rate limited after a short time. DNSBLs are very effective to filter spam.
