### ISSUE TITLE
SoGo blank screen

### ISSUE THREAD

**Issue by unclesamwk** [mailcow/mailcow-dockerized#1621]
Hey,

i installed mailcow. backend access is given.
If i started the "SOGo Groupware" with blank screen.
All js,css,... loaded with an 200 but blank browserwindow.

Any idea?

greetings 
Sam

**Comment by EnriqCG** [comment]
Just to know, are you using any reverse proxy - other config, or are you just accessing directly?

**Comment by unclesamwk** [comment]
Hey,

i use no proxy.

i deleted all containers and volumes and try it again => blank screen in sogo (firefox).
But in chrome it works ... any idea?

greetings Sam

**Comment by Geitenijs** [comment]
Firefox is probably still using old files from it's cache. Try clearing the cache
