### ISSUE TITLE
Database Password Hashing 

### ISSUE THREAD

**Issue by Jasper-Ben** [mailcow/mailcow-dockerized#1622]
Hi,
I'm just wondering why mailcow uses SHA256 as default hashing algorithm for passwords instead of e.g. SHA512-crypt? Are there legacy compatibility reasons behind this?

**Comment by andryyy** [comment]
It uses SSHA256 (salted SHA256). It can handle some other algorithms (including SHA512-CRYPT) now, too. Default has not changed, but might change in the future.

I forgot the "Hi" => Hi!
