### ISSUE TITLE
Exchange  settings not workin on windows 10

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1623]
Hallo@all
Ich hoffe ich mache das jetzt so richtig.
Ich hab auf meinem root server ein mailcow eingerichtet.
Ich kann auch er imap und smtp auf meine mails zugreifen. (opera mail)
Jetzt wollte ich meine email in windows 10 hinzufügen.
Ich hab es so porbiert:
https://mailcow.github.io/mailcow-dockerized-docs/client-windows/
Ich hab also zuerst meine email angeben und im nexten fenster mein Passwort.
Dann bekomme ich das:
Exchange
Überprüfen Sie Ihre Informationen, und versuchen Sie es noch mal. Vielleicht haben sSie Ihr KEnnwort nur falsch eingeben.
Email-addresse kasten
KEnnwort kasten
Benutzername kasten
Domäne kasten.

Könnte mir jemand sagen, was falsch ist?
Gruss Conan

PS:ich hab eine lrs und meine eng kenntnisse sind nicht so gut im schreiben, deswegen in Deutsch.

**Comment by mritzmann** [comment]
Die von dir verlinkte Anleitung ist für "Windows Mail". Ich vermute, die Anleitung bezieht sich auf die alte Version aus Windows Vista und Windows 7. Unter Windows 10 heisst das Programm ja nur noch "Mail".

Ob dieses "Mail"-Programm von Windows 10 wirklich via Exchange kompatibel ist, weiss ich nicht. Bereits mit IMAP versucht?

**Comment by Conan179** [comment]
"Windows 8 and higher support email, contacts and calendar via Exchange ActiveSync."
"Open the Mail app."
also ich hatte es so verstanden, das es damit geht.
Imap geht, ich wollte es ausprobieren, ob ich das kontake und den Kalender sync auch hin bekomme.
Mailcow läuft erst seid 3tagen bei mir.

**Comment by mritzmann** [comment]
Habe es soeben getestet. Funktioniert in meinem Fall, ist somit also kein allgemeines Problem.

* Siehst du irgendwas im Mailcow Log?
* Hast du es trotzdem mal mit IMAP versucht? (Um auszuschliessen dass das PW wirklich inkorrekt ist)
* Anmelden an SOGo funktioniert?

**Comment by Conan179** [comment]
oh logs, wie rufe ich die eigentlich bei solchen docker sachen ab? ich bin nur /var/log/ gewöhnt.
imap und sogo gehen. (abspasswort beim erstellen abkopiert)

**Comment by mritzmann** [comment]
`docker-compose logs` im mailcow ordner oder im WebUI unter Debugging.

**Comment by Conan179** [comment]
aha so geht das also, uff da muss ich erst mal durch steigen.

**Comment by mritzmann** [comment]
Könnt mir auch vorstellen, dass Autodiscover / Autoconfig nicht korrekt eingerichtet ist und dein Mail Client die Einstellungen nicht findet.

**Comment by Conan179** [comment]
ja daran könnte es liegen, hab es vor wenigen minuten in der doku gefunden und schnell in die zonefile hinzugefügt, ABER irgendwie habe ich noch einen kurks drin.
C:\Users\Conan>ping autodiscover.tabgalaxymeinedomain.xx

Ping wird ausgeführt für mail.tabgalaxymeinedomain.xx [2a01:4f8:xxxx:] mit 32 Bytes Daten:
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.

Ping-Statistik für 2a01:4f8:xxxx:
    Pakete: Gesendet = 4, Empfangen = 0, Verloren = 4
    (100% Verlust),

C:\Users\Conan>ping autoconfig.tabgalaxymeinedomain.xx

Ping wird ausgeführt für mail.tabgalaxymeinedomain.xx [2a01:4f8:xxxx:] mit 32 Bytes Daten:
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.

Ping-Statistik für 2a01:4f8:xxxx:
    Pakete: Gesendet = 4, Empfangen = 0, Verloren = 4
    (100% Verlust),

C:\Users\Conan>ping mail.tabgalaxymeinedomain.xx

Ping wird ausgeführt für mail.tabgalaxymeinedomain.xx [2a01:4f8:xxxx:] mit 32 Bytes Daten:
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.
Zielnetz nicht erreichbar.

Ping-Statistik für 2a01:4f8:xxxx:
    Pakete: Gesendet = 4, Empfangen = 0, Verloren = 4
    (100% Verlust),

Die Ipv6 stimmt aber, aber ping geht nicht.

**Comment by Conan179** [comment]
ich hab jetzt mal den log Autodiscover angeschaut.
DA steht doch glatt

2.8.2018, 20:09:45 | microsoft.windowscommunicationsapps | none | Error: must be authenticated
-- | -- | -- | --
2.8.2018, 20:09:35 | microsoft.windowscommunicationsapps | none | Error: must be authenticated
2.8.2018, 18:40:15 | WinHttpRequest | none | Error: must be authenticated
2.8.2018, 18:35:56 | microsoft.windowscommunicationsapps | none | Error: must be authenticated
2.8.2018, 18:35:49 | microsoft.windowscommunicationsapps | none | Error: must be authenticated

also doch scheinbar ein login problem.

**Comment by mritzmann** [comment]
Verfügt deine Autodiscover Subdomain über ein gültiges HTTPS Zertifikat?

**Comment by Conan179** [comment]
nein, nur ubuntu-1604-64bit-conans-openvpn-maschine.tabgalaxymeinedomain.xx  imap.tabgalaxymeinedomain.xx smtp.tabgalaxymeinedomain.xx mail.tabgalaxymeinedomain.xx

wie füge ich Autodiscover und autoconfig hinzu?

**Comment by mritzmann** [comment]
`docker-compose restart acme-mailcow` sollte ein neues Zertifikat anfordern. Falls das nicht geht, eventuell auch Mal das ganze mailcow neustarten.

Neustarten:

1. docker-compose down
2. docker-compose up -d

**Comment by Conan179** [comment]
dann kommt nur:
*ganzvielinhalt*
challenge acme-client: mP7REDtRGVKE: File exists acme-client: bad exit: netproc(406): 1 acme-client: bad exit: challengeproc(409): 1

**Comment by Conan179** [comment]
So hab die cert erneuert, jetzt sind  Autodiscover und autoconfig auch dabei, wen ich mich jetzt versuche einzuloggen kommt im log:

2.8.2018, 21:40:37 | microsoft.windowscommunicationsapps | none | Error: must be authenticated
-- | -- | -- | --
2.8.2018, 21:40:29 | microsoft.windowscommunicationsapps | none | Error: must be authenticated

also genau das gleiche.

**Comment by Conan179** [comment]
So leute, fehler gefunden und behoben und schon klappt das einloggen.
der fehler ist follgendes
da
https://mailcow.github.io/mailcow-dockerized-docs/install/
steht " bind HTTPS to 127.0.0.1 on port 8443 and HTTP to 127.0.0.1 on port 8080"
da ich ein root server mit öffentlicher ip habe, hab ich satst der localhost ip, meine öffentliche eingetragen. Wen ich also darauf zugegriffen habe, hab ich immer:
mail.tabgalaxymeinedomain.xx:8443 eingetippt.
Den ssl port auf 443 geändert, docker-compose down && docker-compose up -d eingetippt und versucht einzuloggen und klappt direkt.
Ich endschuldige mich, das ich das nicht gleich gesehen hatte -.- .

Gruss Conan

**Comment by andryyy** [comment]
"If you plan to use a reverse proxy, you can, for example, bind HTTPS to 127.0.0.1 on port 8443 and HTTP to 127.0.0.1 on port 8080."
