### ISSUE TITLE
Enable/disable 2FA as domain administrator

### ISSUE THREAD

**Issue by hellerve** [mailcow/mailcow-dockerized#1624]
As a domain administrator, I can change passwords of accounts. This is important when e.g. offboarding team members. Sometimes you want to remove those members and then set an autoresponder telling people that this person no longer works with the team, for instance.

What I cannot do as a domain administrator is to enable or disable 2FA. This means I can lock other members out of their accounts, but might not be able to log into them, since 2FA is still enable and I do not have access to the device they use for 2FA (nor do I want to).

This is not necessarily a problem for offboarding, since I can still log into SoGo and such, but it does make changing passwords somewhat less useful.

I’d thus suggest that domain administrators can enable and disable 2FA per account.

Cheers

**Comment by andryyy** [comment]
There is no TFA for normal users.

**Comment by hellerve** [comment]
Is that only available on the hosted version or something? I can definitely set 2FA when I login as a regular Mailbox user on hosted.mailcow.de. In fact, the toggle is one of the first things I see when I log in.

Maybe this isn’t the right channel to discuss this then, though?

**Comment by XenGi** [comment]
With the hosted mailcow service (servercow), 2FA can only be enabled for the admin interface for the domain administrator at https://hosted.mailcow.de/manager and also for normal users loggin in to https://hosted.mailcow.de/user. You probably mean the user interface. There the admin indeed has no option to disable the 2FA of the user account.

I just checked all of that to be sure.

**Comment by hellerve** [comment]
Yes, that’s exactly what I mean! Pardon my inability to express that clearly.

**Comment by XenGi** [comment]
Still no update on this one?

**Comment by hellerve** [comment]
This should probably not be closed, since it’s still not fixed.
