### ISSUE TITLE
Set an autoresponder as domain administrator

### ISSUE THREAD

**Issue by hellerve** [mailcow/mailcow-dockerized#1625]
As discussed in #1624, I’d sometimes like to be able to set an auto responder for an account. If, for instance, a team member leaves for vacation and forgets to set an autoresponder, I’d like to be able to do that for them without having to log into their accounts. This is less of a problem in the use case discussed in #1624, but it is a problem when they are on a temporary leave—I don’t want to snoop in people’s e-mails, nor do i want to make it seem like I do.

Cheers

**Comment by andryyy** [comment]
You can create filters in the UI. I will try to add presets.

**Comment by hellerve** [comment]
I don’t think I follow. How exactly do I do that? If it’s a lot to explain, you can just point me to the right piece of the documentation and I’ll try to educate myself a bit more on this!

**Comment by mritzmann** [comment]
> I don’t think I follow. How exactly do I do that?

Never tested it, but maybe this will help you.

* In Mailcow: Configuration -> Mailboxes -> Filter
* https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples#Vacation_auto-reply

**Comment by hellerve** [comment]
This sadly does not work for us, since we are using the hosted version. I should probably specify that from the get-go, hu? Sorry for the confusion.

**Comment by hellerve** [comment]
Is there anything happening to tackle this?

**Comment by hellerve** [comment]
I’d rather have an explicit message about this then let it slip. If no work will be done on this issue, that’s fine, but I’d like a heads-up!

**Comment by andryyy** [comment]
We could migrate you to a managed mailcow. The packages just launched. 

In the hosted mailcow it is not possible. :-(

Sorry, I missed this issue.

**Comment by hellerve** [comment]
Alright, thanks for the update! We’ll think about it and see whether we can and want migrate (but probably not before Christmas).

I think we can close this now, in that case. :)

**Comment by andryyy** [comment]
No problem. It is not even that much work, we migrated a customer just yesterday and also kept the hosted mailcow as fallback. :-)
