### ISSUE TITLE
What is the "nextcloud integration" supposed to do?

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#1626]
Hello,

I have seen the nextcloud-helper script but I could not find any explanation of what it is supposed to do, and I can't decipher the script.

I have separate nextcloud and mailcow instances running under 2 different users on my system. As I rely on LDAP auth for nc, I'm not interested in unified login (I'll wait for Mailcow to support ldap auth).

Could you explain what it is supposed to do?

For that matters, I would like to integrate Sogo's calendar and contacts into nextcloud (and then sync them to my Ubuntu laptop through the Nextcloud integration).

**Comment by mkuron** [comment]
> Could you explain what it is supposed to do?

It installs Nextcloud and configures it for authebtication against Mailcow.

> For that matters, I would like to integrate Sogo's calendar and contacts into nextcloud (and then sync them to my Ubuntu laptop through the Nextcloud integration).

That's not possible. Both mailcow and SOGo have their own CalDAV/CardDAV server. Any client that works with Nextcloud's should also work with SOGo's though.

**Comment by Preisschild** [comment]
Is there any possibility how to make SOGo use webdav instead of their own database yet?

Can't ask at SOGo's Github since they don't have a issue-tracker open.
