### ISSUE TITLE
ACME Cannot match your IP NO_IPV6_LINK against hostname

### ISSUE THREAD

**Issue by MaxXor** [mailcow/mailcow-dockerized#1628]
I'm getting the following error in `acme-mailcow` docker container:
> acme-mailcow_1       | Thu Aug  2 21:22:15 CEST 2018 - Found AAAA record for xxx: 1111::1 - skipping A record check
acme-mailcow_1       | Thu Aug  2 21:22:15 CEST 2018 - Cannot match your IP NO_IPV6_LINK against hostname xxx (1111:0000:0000:0000:0000:0000:0000:0001)

I think the problem is that my AAAA record contains `1111::1` and the [ip-detection website](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh#L84) returns the IPv6 in full length `1111:0000:0000:0000:0000:0000:0000:0001` and thus the comparison fails? Or the [expander](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh#L181) is not working correctly.

**Comment by andryyy** [comment]
Can you mail me the full uncensored output to info@servercow.de ?

**Comment by MaxXor** [comment]
Solved, thanks @andryyy. Problem was a virtual network interface `eth0:0` instead of `eth0` which stopped IPv6 functionality with docker.
