### ISSUE TITLE
2xKonfig fragen: 1.System verschickt keine mails, wo Mailcow innstalliert ist 2.Wie email addresse Whitelisten?

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1630]
Hallo erst mal.
Ich hab 2xkonfig fragen, wo ich hilfe bräuchte.
1. Das system wo ich Mailcow innstalliert habe, verscickt keine mails, in dem fall sind es Fail2ban und Logwatch mails. Was muss ich einstellen, damit das System auch Mails verschicken kann?
2. Vereinzelte bekomme ich noch eine mail vom Mail Delivery System <MAILER-DAEMON@xxxxxxxxx.your-server.de>. Wie stelle ich ein, das diese mails nicht als Spam makiert werden?
Ich hoffe ihr könnt mir helfen.

Gruss Conan

**Comment by mkuron** [comment]
1. https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/

2. Mail in Posteingang verschieben, um den Filter zu trainieren. Falls das nicht reicht, poste bitte die Rspamd-Header aus einer solchen Mail.

**Comment by Conan179** [comment]
ich muss also zusätzlich einen mta innstallieren, darauf wäre ich nciht gekommen.
ok, ich werde es probieren.

**Comment by Ruffythemonkey** [comment]
wie hast du das Problem gelöst ?
