### ISSUE TITLE
Wrong CAA record prevents issuance

### ISSUE THREAD

**Issue by Knight1** [mailcow/mailcow-dockerized#1632]
If there is an CAA record present which prevents the issuance of auto(config|discover).domain.xyz mailcow is going crazy. 

It was falling back to my only additional SAN in the config and the main domain was unavailable due to the error above. 

Can you explain where the ```dns_get_record``` function is? Because i guess it is simple to add this check.

**Comment by mkuron** [comment]
You would need to add that check to 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh. dns_get_record is not involved.

**Comment by andryyy** [comment]
What did you expect? If you mess up the CAA, that’s what happens. Certificates will not be issued. 

dns_get_record is an internal function of PHP. Besides that, acme-mailcow is issuing certificates.

**Comment by Knight1** [comment]
@andryyy not that the ADDITIONAL_SAN shows up at the main Domain :)

So we only need to check if "dig caa ${SQL_DOMAIN} +short" is returning entries and if they contain 'issue "letsencrypt.org"'

We could also check that in dns_management.php and display inside the DNS Block if wanted.

**Comment by andryyy** [comment]
When ADDITION_SAN was issued by LE, that domain does not have a CAA. It is not _us_ to verify the CAA, but Let's Encrypt.

**Comment by andryyy** [comment]
Adding "dig caa ${SQL_DOMAIN} +short" would not have an effect on ADDITIONAL_SAN. 

Think carefully about implementations before saying "just add this and that". I promise that is how we break things. I did it, others did it, it happens. But we can prevent it by not rushing into decisions. :-)
