### ISSUE TITLE
Hardening PHP

### ISSUE THREAD

**Issue by Knight1** [mailcow/mailcow-dockerized#1635]
Hey!

Currently https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/phpfpm/php-fpm.d/pools.conf does not have disable_functions or open_basedir to harden it.

Anything against that?

I currently use for example
```
php_admin_value[open_basedir] = /web:/usr/share/php5:/tmp:/usr/share/php:/usr/share/pear
php_admin_value[disable_functions] = escapeshellarg,escapeshellcmd,ini_alter,pcntl_exec,proc_close,proc_get_status,proc_nice,proc_terminate,symlink,phpinfo,dl,exec,passthru,shell_exec,system,proc_open,popen,show_source,curl_multi_exec
```

**Comment by andryyy** [comment]
Yes, the open_basedir will break functions as it is above.
disable_functions is fine.

I would need to check the correct basedirs when I find some time.

**Comment by Knight1** [comment]
This was just an example. We just need to remove
curl_multi_exec, popen

Does this need exec or is this a pdo function? https://github.com/mailcow/mailcow-dockerized/blob/4227ec15fc07a16b01fa51c60f29059552f31fc1/data/web/inc/init_db.inc.php#L910 
escapeshellarg,escapeshellcmd is used by phpmailer https://github.com/mailcow/mailcow-dockerized/blob/a09ed211bc39f17855a880cc19e63d256180851d/data/web/inc/lib/vendor/phpmailer/phpmailer/class.phpmailer.php#L1435

**Comment by mkuron** [comment]
Since the PHP interpreter is running inside a Docker container, it can only read stuff from inside the container and from the volumes mounted to it. So `open_basedir` doesn't add any extra security.

Similarly, disabling `exec` and the like doesn't help much because there isn't much that could be executed. And anything would only have effect inside the container.

**Comment by Knight1** [comment]
But if someone finds a bug, outdated system, whatsoever it is better to have a system locked down. Disabling unnecessary things is always good.

**Comment by Knight1** [comment]
fixed with https://github.com/mailcow/mailcow-dockerized/pull/1900
