### ISSUE TITLE
Phantom calendar event

### ISSUE THREAD

**Issue by phatina** [mailcow/mailcow-dockerized#1639]
Hi all,

I managed to create a non-reachable event by misclicking somewhere during its creation. Now, I have an event without a date (it defaults to 1/1/1970). When I try to open it in SOGo, it does nothing. When I synchronize my calendar with Thunderbird, I can not find this event anywhere.

When I export my calendar into ICS format, here's the source of my non-displayable event. I think, it does not contain `DTSTART` and `DTEND` keys.

Exported event:

```
BEGIN:VEVENT
UID:8FA3-5B62EC00-37-2BBA88C0
SUMMARY:Naskladnenie Hobis Ergo 2M podnoze
LOCATION:Agatova 22
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER;VALUE=DURATION;RELATED=START:-P1D
ACTION:DISPLAY
END:VALARM
TRANSP:OPAQUE
CREATED:20180802T113403Z
DTSTAMP:20180802T113403Z
LAST-MODIFIED:20180802T114413Z
END:VEVENT
```

Can anyone help me get rid of this event, so it doesn't pop up in SOGo interface?

Thank you a lot!

Peter

**Comment by mkuron** [comment]
First, create a backup as explained in the documentation, just to be sure.

Then you can try to find the event in the database by its UID:
```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "SELECT c_content FROM sogo_store WHERE c_name = '8FA3-5B62EC00-37-2BBA88C0.ics'"
```
If that returns exactly the event you are looking for, delete it:
```
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DELETE FROM sogo_store WHERE c_name = '8FA3-5B62EC00-37-2BBA88C0.ics'"
```
If in the first step it didn't find the event, you can do a full-text search for the UID to find the right `c_name`:
```
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "SELECT c_name FROM sogo_store WHERE c_content LIKE '%UID:8FA3-5B62EC00-37-2BBA88C0%'"
```

**Comment by phatina** [comment]
Oh, thank you very much. Worker like charm!
