### ISSUE TITLE
Edit aliases

### ISSUE THREAD

**Issue by MaxXor** [mailcow/mailcow-dockerized#1642]
When editing an alias you can only change the Goto addresses, not the aliases itself. This feature would be very handy. :)

**Comment by andryyy** [comment]
Indeed. I think it is easier for us to make it a wrapper for "delete and create new". :-)  I will add it.

**Comment by andryyy** [comment]
I added a new primary key (a numeric id) for this. Works better.

**Comment by MaxXor** [comment]
Thanks, don't know if it's easy to implement but a mailbox name can not be edited as well.

**Comment by andryyy** [comment]
Yes, that's for many reasons. It is not as easy as changing the name. So it will not be possible in the near future.
