### ISSUE TITLE
Wo finde ich die "vars.(local.)inc.php"?

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1643]
Hallo erst mal.
Wo finde ich die "vars.(local.)inc.php" ?
Wen ich per google suche finde ich immer nur den Hinweis:
"PLEASE USE THE FILE "vars.local.inc.php" TO OVERWRITE SETTINGS AND MAKE THEM PERSISTENT!"

PS: ich endschuldige mich für meine ganzen Noob fragen.

gruss conan

**Comment by andryyy** [comment]
Noob Fragen.. :-D

Macht doch nichts: `data/web/inc/vars.inc.php`. Wenn etwas geändert wird, dann am besten die Datei `vars.local.inc.php` erstellen (im selben Ordner). Die Inhalte der local-Datei überschreiben die der vorhandenen Datei.

**Comment by Conan179** [comment]
Ich empfinde das so, weil die anderen pots. richtige probleme sind, meine dagegen sind fast schon alltägliches wiessen -.-
mailcow-dockerized ist das erste docker wo ich einsetzte, es ist noch alles neu für mich >.<

Gehe ich recht in der annahme das die vars.local.inc.php den gesamten inhalt auf die data/web/inc/vars.inc.php überschreibt? Ich kopiere sie also einmalig /opt/mailcow-dockerized/data/web/inc# cp vars.inc.php vars.local.inc.php und bearbeite sie dan nur noch.

**Comment by mkuron** [comment]
Nein, du trägst dort nur die Variablen ein, die du überschreiben willst. Also z.B. so was:

```
<?php
$DEFAULT_LANG = 'de';
$autodiscover_config['useEASforOutlook'] = 'no';
$MAILCOW_APPS[] = array('name' => 'Cloud', 'link' => '/cloud')
?>
```
