### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by IchUseKomplexe** [mailcow/mailcow-dockerized#1644]
[Hey,] I got an Email-Server and It's working fine. Today I tried to contact two Emails for a Sponsoring. 
Here the log: 

> Reporting-MTA: dns; mail.syncgaming.org
> X-Postfix-Queue-ID: D203FE2ACD
> X-Postfix-Sender: rfc822; support@syncgaming.org
> Arrival-Date: Wed,  8 Aug 2018 14:30:30 +0000 (Etc)
> 
> Final-Recipient: rfc822; game@aimcontrollers.com
> Original-Recipient: rfc822;game@aimcontrollers.com
> Action: failed
> Status: 5.0.0
> Remote-MTA: dns; aimcontrollers.com
> Diagnostic-Code: smtp; 550-Verification failed for <support@syncgaming.org>
>     550-The mail server could not deliver mail to support@syncgaming.org.  The
>     account or domain may not exist, they may be blacklisted, or missing the
>     proper dns entries. 550 Sender verify failed

Sending a mail to them from Gmail works.

Mail-tester test: https://www.mail-tester.com/web-hwkpj

Cloudflare dns. https://imgur.com/a/fvHTKOn

**Comment by mkuron** [comment]
Your MX record points to an IP address, which is not allowed. Set it to mail.syncgaming.org.
