### ISSUE TITLE
Undelivered Mail Returned to Sender - mail for <domain>.de loops back to myself

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#1645]
I installed mailcow, configured the domain and the mailbox.

I  tried to receive emails and send a email from a other working domain, but got that message back
```
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<admin@<domain>.de>: Host or domain name not found. Name service error for
    name=<domain>.de type=AAAA: Host found but no data record of requested type
```
But i have a AAAA dns entrie with the ipv6 address of my domain.

**Comment by UtechtDustin** [comment]
Now i got that message
```
mail for <domain>.de loops back to myself
```

**Comment by andryyy** [comment]
You probably checked "Backup MX" in the domain settings.

**Comment by UtechtDustin** [comment]
@andryyy 
No 
![bildschirmfoto vom 2018-08-08 19-26-58](https://user-images.githubusercontent.com/13292481/43853658-1288bb42-9b41-11e8-9f8f-f5f8591db402.png)

German:
Evtl. könntest du mir per Discord fix helfen.

**Comment by Conan179** [comment]
Ich bekomme auch 2mal am tag so eine email, auffälig bei mir ist:
This is the mail system at host richtiger hostname.richtigedomain.tt
 
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.
 
For further assistance, please send mail to postmaster.
 
If you do so, please include this problem report. You can
delete your own text from the attached returned message.
 
                   The mail system
 
<root@richtigerhostname.your-server.de> (expanded from <root>): Host
    or domain name not found. Name service error for
    name=richtigerhostname.your-server.de type=A: Host not found

Die Domain "your-server.de" setzt Hetzner ein, da hab ich keinen zugriff drauf und kann sie nicht ändern.

Jeden Tag fast exat immer die selbe uhrzeit.

**Comment by UtechtDustin** [comment]
Oh my fault, i had the wrong ip on the a dns entry.
