### ISSUE TITLE
update script - Cannot determine latest docker-compose version, skipping...

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1646]
Good evening,

i'm really new to mailcow so here is my first issue.
As i was updating mailcow this evening i was faced with this message:

Fetching new docker-compose version...
Cannot determine latest docker-compose version, skipping...

I can't find any errors in all logfiles, an connectivity to and from the server is good.

Any thoughts?

Thanks for your help

**Comment by skupfer** [comment]
Usually happens when you are not running this as root. I don't know how to fix this and in my case `sudo` didn't help either. Just update it manually.

**Comment by ghost** [comment]
Usually i run this script as root and not using sudo.
Running as root results in described error ...

**Comment by andryyy** [comment]
`curl -sL -w "%{http_code}" https://www.servercow.de/docker-compose/latest.php -o /dev/null`

What does this return on your host system?

**Comment by ghost** [comment]
Frankly spoken ... nothing ...

**Comment by skupfer** [comment]
Result: 
```
curl -sL -w "%{http_code}" https://www.servercow.de/docker-compose/latest.php -o /dev/null
200%  
```

EDIT: curl servercrow.de

```
curl servercrow.de
<!doctype html>
<html>
<head>
        <meta charset="utf-8">
        <title>Domainpark - Bitte den Rasen nicht betreten. Vielen Dank!</title>
        <script>
                document.createElement("header");
                document.createElement("section");
                document.createElement("footer");
                document.createElement("nav");
        </script>
[...]
```

**Comment by andryyy** [comment]
Can you curl servercow.de?

**Comment by ghost** [comment]
No ...

**Comment by andryyy** [comment]
Are you on IRC?

**Comment by ghost** [comment]
No ...

**Comment by ghost** [comment]
I get this message:

curl https://servercow.de
curl: (7) Failed to connect to servercow.de port 443

**Comment by andryyy** [comment]
@skupfer Are you on IRC?

**Comment by skupfer** [comment]
@andryyy joined irc now

**Comment by ghost** [comment]
curl -sL -w "%{http_code}" https://www.servercow.de/docker-compose/latest.php -o /dev/null
puts back 000

**Comment by ghost** [comment]
@andryyy joined irc now

**Comment by ghost** [comment]
I can't get IRC to work ...
Can you help me in another way?

**Comment by andryyy** [comment]
There is an official support channel for when it is urgent. I personally don't have resources for support at the moment, sorry. But I am sure someone else can jump in and help.

**Comment by ghost** [comment]
@andryyy Thanks
It is not urgent, i was just wondering, because two days ago it worked without problems.
I haven't changed anything within my system.

**Comment by andryyy** [comment]
Ok, you probably know why I am closing this... 🙄
