### ISSUE TITLE
 Undelivered Mail Returned to Sendervom "the mail system"

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1647]
Ich bekomme 2mal am tag diese email, auffälig ist das die domain falsch ist.:

> This is the mail system at host richtiger hostname.richtigedomain.tt
> 
>
>
>
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
>  
> For further assistance, please send mail to postmaster.
>  
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
>  
>                    The mail system
>  
> <root@richtigerhostname.your-server.de> (expanded from <root>): Host
>     or domain name not found. Name service error for
>     name=richtigerhostname.your-server.de type=A: Host not found

Die Domain "your-server.de" setzt Hetzner ein, da hab ich keinen zugriff drauf und kann sie nicht ändern.

Jeden Tag fast exat immer die selbe uhrzeit.

**Comment by mkuron** [comment]
Irgendeiner deiner User, womöglich ein Cronjob, schickt offensichtlich eine Mail an root@richtigerhostname.your-server.de. Kannst du mal den Rest der Mail (bzw. ihren Anhang) posten, da sollte erkennbar sein, worum es sich handelt. Auch in den Postfix-Logs müsste man das sehen.

**Comment by Conan179** [comment]
Erlich gesagt, würde ich es nur sehr ungern öffentlich posten, da stehen mehrer meiner öffentliche ips und meine emailaddresse+domain.
