### ISSUE TITLE
SSL Cert for additional SAN

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1648]
I am trying to add a second domain name to my server. I have all the DNS records set, added the additional SAN in mailcow.conf, restarted mailcow, and for some reason mailcow still says that it cannot find DNS records for my new domain name.

**Comment by mkuron** [comment]
Wait 24 hours for the DNS record to propagate.

**Comment by Knight1** [comment]
Let's Encrypt uses the nameservers and do not cache anything.

So you can verify it with

```dig %DOMAIN% NS +short | head -1```
```dig %DOMAIN% @(return from above)```
