### ISSUE TITLE
Wrong DNS Settings

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#1649]
Hello to all.

Yesterday i switched my server to another provider to use mailcow dockerized. Mails, Contacts and sync works fine, but i have seen that my dns settings seems to be incorrect.

Screenshot from Mailcow
![2018-08-09 08_40_22-mailcow ui](https://user-images.githubusercontent.com/25910686/43882866-8caaeaba-9bb1-11e8-8875-f07f1cbaff29.png)

My domainprovider is german and called domainfactory. This is my config (for all _service._tcp listings:
![df](https://user-images.githubusercontent.com/25910686/43882910-afc9cebc-9bb1-11e8-96fa-373875c10699.png)

Only one thing is funny, the _autodiscover entry, is the same like the others but he is shown correctly.
I dont know why the others use TLSA as type and what are those strings for.

Hope you can help me,

cheers

**Comment by mkuron** [comment]
You are confusing SRV and TLSA. The latter are for pinning the public key of your certificate, for use with DANE.
Also, your CNAME records seem to be wrong as they aren't pointing at the fully-qualified name.

**Comment by ClepToManix** [comment]
So I should have to delete those records from domain factory?

**Comment by ClepToManix** [comment]
@mkuron

**Comment by mkuron** [comment]
Fix the CNAMEs so that you get checkmarks on Mailcow's DNS page. Add the TLSAs if you like. Delete all SRV records that are not listed on the DNS page. Technically all of these records are optional; the only ones you absolutely need are A, MX and PTR.

**Comment by lo05** [comment]
งง
