### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#165]
Hi, 

after git pull and docker-compose pull I get the following error message:

`dovecot-mailcow_1    | 2017-03-26 13:40:53 auth-worker(55): Error: mysql(mysql): Connect failed to database (mailcow): Can't connect to MySQL server on 'mysql' (111) - waiting for 1 seconds before retry`

Maybe you can help me?

Thanks!

**Comment by andryyy** [comment]
Non of the above would change the configuration file.

You may have changed mailcow.conf.

**Comment by rebek86** [comment]
No, I have not changed anything to the mailcow.conf. Just checked it again...

What can I do to fix it?

**Comment by rebek86** [comment]
After `docker-compose stop` and `docker-compose up -d` everything is running well again. `docker-compose restart` did not work for me. Did you have an idea what went wrong here? Nothing was changed at the mailcow.conf :-/

**Comment by andryyy** [comment]
There should not be a problem like this. Can you try it again? Does it happen again?
