### ISSUE TITLE
SPF und DKIM invalid bei Alias-Domain

### ISSUE THREAD

**Issue by Folkhere** [mailcow/mailcow-dockerized#1651]
Ich habe hier zwar länger gesucht, aber nichts genau passendes gefunden, daher nun meine Anfrage.
Für eine meiner Domains existiert eine reine Alias-Adresse, die zu 2 externen Adressen weiter leitet, also:

alias@xxx.tld -> rec1@yyy.tld,rec2@zzz.tld

Es handelt sich dabei um eine Kontaktadresse, die von einem Joomla CMS auf einem anderen Server via SMTP versandt wird. Eine Mailbox existiert für diese Domain nicht.

Die Weiterleitung durch mailcow funktioniert auch offensichtlich, allerdings werden Empfängerseitig weder SPF- noch DKIM-Eintrag erkannt (obwohl definitiv vorhanden). Dass das Ganze prinzipiell klappt, sehe ich daran, dass yyy.tld etwas  unkritischer ist. Zwar wird im Header ebenfalls SPF und DKIM als „invalid” gekennzeichnet, aber die Mails werden nicht zurück gewiesen, anders als bei zzz.tld.

Für die beiden DNS-Einträge habe ich mich an die entsprechenden Anweisungen aus der Dokumentation gehalten. Für einen kleinen Tip wäre ich wirklich sehr dankbar, wahrscheinlich bin ich nur gerade etwas Betriebsblind, aber ich finde einfach keinen Grund dafür..

**Comment by andryyy** [comment]
Sendest du mir mal eine Nachricht direkt von diesem Konto an andre.peters@servercow.de?

**Comment by Folkhere** [comment]
Hallo Andre,
ich habe die Adresse als 2. Weiterleitung im Alias eingetragen  und eine Testmail aus dem CMS heraus angestoßen - wie gesagt, eine Mailbox zu der Domain existiert nicht und ist auch nicht geplant.
Schon mal Danke für Deine Mühe.

**Comment by Folkhere** [comment]
Sorry, ich hatte den falschen Button beim kommentieren erwischt - muss die Wärme sein ;).

**Comment by andryyy** [comment]
Die Mail hat keine Signatur. DMARC failed dadurch.

Ich verstehe das ganze hin und her aber auch überhaupt nicht. Wer versendet da als was über wen? Warum sendet das Joomla nicht einfach via SMTP über die mailcow? Kennt mailcow überhaupt die Domain la....de ?

**Comment by Folkhere** [comment]
1. Ja, die Domain ist in mailcow eingerichtet.
2. Ich hoste die Seite für eine gute Bekannte, die ungern ihre eigene Mailadresse dort stehen hätte. Die Kontaktadresse ist also nur dafür da, Anfragen an sie und zu Kontrollzwecken an mich zu schicken, alles weitere macht sie dann doch über ihre eigene Adresse. Naja, ist halt eine ältere Dame von knapp 70.
3. Joomla versendet über seine eigene SMTP-Funktion vom Webserver an Mailcow. Der Webserver ist dort als Weiterleitungs-Host eingetragen (da beide eben auf unterschiedlichen VPS liegen). Das nur als Erklärung, denn Du hast völlig Recht - die Lösung ist irgendwie idiotisch.  Ich werde jetzt einfach mal eine entsprechende Mailbox einrichten und dann über den Account versenden, mal sehen, was passiert.
Sorry, dass ich jetzt Deine Zeit verbraten habe, normaler Weise löse ich sowas mühsam selber, aber hier hatte ich mich irgendwie verrannt - daher Danke für die Entfernung des Bretts vorm Kopf ;).

**Comment by andryyy** [comment]
Macht doch nichts. :-)

**Comment by Folkhere** [comment]
So, ich habe es erst mal 2 Tage noch offen gelassen und verschiedene Varianten getestet (und mir dabei noch hübsch selber ein Bein gestellt - wenn man vergisst, das man schon mal eine Empfänger-Umschreibung eingerichtet hatte, darf man sich nicht wundern, wenn nichts in der Mailbox ankommt :D).
Jetzt klappt alles wie vorgesehen, und Danke noch mal für Deinen Support!
