### ISSUE TITLE
Marked as Spam Spamhaus SBL CSS

### ISSUE THREAD

**Issue by ssm3e30** [mailcow/mailcow-dockerized#1653]
Hi Everyone,

I'm not sure why but after a few days of running Mailcow, my IP was marked by spam at Spamhaus unser there CSS list. I mistakenly asked my host for help but they just requested a delist without me confirming the issue was resolved first.

Does anyone know what this blacklist is looking for or to help me find out exactly why its being listed?
I have set all my DNS settings, PRT, SPF,rDNS, DKIM and DMARC. I noticed my registrar had a WhoIS gaurd on so I've since turned that off. Let me know what other info I might need to provide to pinpoint this issue.

Shaun

**Comment by mkuron** [comment]
See https://www.spamhaus.org/css/ for information on this blacklist. You can also query their blocklist at https://www.spamhaus.org/lookup/, which might provide details on why your address was listed.

Maybe one of your users is actually sending out spam mails?

Also, make sure your mail server is not an open relay. This can happen if you severely misconfigure Mailcow or Docker or have an exotic firewall configuration. See #758, #1145, #1469 for hints on that. Check your Postfix logs to see whether it accepts and relays external email. There are also multiple online services that can test for open relaying, e.g. https://www.unlocktheinbox.com/openrelaytest/ .
