### ISSUE TITLE
Open xchange

### ISSUE THREAD

**Issue by xiaoveiti** [mailcow/mailcow-dockerized#1655]
Hey guys, I like the way you implemented SOGo, and I get kind of used to it, but is is possible to run the open xchange appsuite next to SOGo? I just like the webmail much more - Haha. 

Is there any easy way, to add and link the appsuite within a new container?

If not no problem, don't really want to mess around with it, as mailcow runs quite stable!

Looking forward to your answer 😊

**Comment by johann8** [comment]
Soviel ich weiß, unterstützt Open Xchange offiziell keine Container. Ich habe OX App Suite 7.10 manuell auf dem Host unter CentOS7 installiert (kein Container). Läuft gut zusammen mit MailCow.

**Comment by andryyy** [comment]
No, sorry, it will never be implemented. It is not open source.
