### ISSUE TITLE
SOGo error message

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1656]
In the SOGo debug log in Mailcow UI I see a lot of the following two error lines:

`
8/11/2018, 1:40:45 PM | notice | 13:40:45.842 sogod[48:48] could not get DNS name of address 172.22.1.1 in domain <InternetDomain[0x0x55c812383ab0]>: 1
-- | -- | --
`
`
8/11/2018, 1:40:45 PM | notice | 13:40:45.823 sogod[48:48] -[NGInternetSocketAddress _fillHost]: host not found ..
`

None of the containers has ip 172.22.1.1 assigned. 

I use the latest mailcow version (just updated).

**Comment by andryyy** [comment]
It is your Docker hosts gateway. It does not have a PTR. You can ignore these warnings.
