### ISSUE TITLE
404 - Not found wen man [Konfigurationsanleitungen für E-Mail-Programme und Smartphones anzeigen] folgt

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1659]
Hallo erst mal.
Diesmal habe ich wirklich einen kleineren Bug gefunden :D 
![mailcow_1_12082018](https://user-images.githubusercontent.com/1906242/44004427-dbd825b8-9e62-11e8-9eb6-cb69ad8078af.JPG)
![mailcow_2_12082018](https://user-images.githubusercontent.com/1906242/44004429-dd8846e0-9e62-11e8-9b53-769e7ddd920a.JPG)
![mailcow_3_12082018](https://user-images.githubusercontent.com/1906242/44004430-df86e4d8-9e62-11e8-88c7-cdb049cf643f.JPG)

Wie man auf den Screenshots zu sehen ist, hab ich mich mit meiner email addresse angemeldet und bin dan dem Link "[Konfigurationsanleitungen für E-Mail-Programme und Smartphones anzeigen]" angeklickt, auf der seite wo ich dann lande, gehen alle links der Email programme auf eine 404 - Not found error seite.

Gruss Conan

**Comment by andryyy** [comment]
Hi, wohin zeigen die Links denn hin?

Mit besten Grüßen
André Peters

**Comment by Conan179** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/client/client-android
https://mailcow.github.io/mailcow-dockerized-docs/client/client-apple
https://mailcow.github.io/mailcow-dockerized-docs/client/client-emclient
https://mailcow.github.io/mailcow-dockerized-docs/client/client-kontact
https://mailcow.github.io/mailcow-dockerized-docs/client/client-outlook
https://mailcow.github.io/mailcow-dockerized-docs/client/client-thunderbird
https://mailcow.github.io/mailcow-dockerized-docs/client/client-windows
https://mailcow.github.io/mailcow-dockerized-docs/client/client-windowsphone
https://mailcow.github.io/mailcow-dockerized-docs/client/client-manual

**Comment by andryyy** [comment]
Sollte gefixt sein. Sonst den Cache mal leeren.

**Comment by Conan179** [comment]
Ja die links gehen jetzt, aber das:
Since you accessed this page after logging into your mailcow server, all of the guides have been personalized with your email address and server name.
 geht nicht bei mir.

z.b. windows mail (sowll 8 als auch 10)

Windows Mail
Windows 8 and higher support email, contacts and calendar via Exchange ActiveSync.

Open the Mail app.
If you have not previously used Mail, you can click Add Account in the main window. Proceed to step 4.
Click Accounts in the sidebar on the left, then click Add Account on the far right.
Select Exchange.
Enter your email address () and click Next.
Enter your password and click Log in.
Once you have set up the Mail app, you can also use the People and Calendar apps.

Mein server wird nicht eingetragen.

**Comment by andryyy** [comment]
Klappt gleich wieder. :-) Danke.

**Comment by Conan179** [comment]
Jup jetzt gehts.
Zum min. einmal konnte ich bei was helfen :D

**Comment by Conan179** [comment]
Ich möchte das Thema noch mal kurz hoch hollen.
Ist das auf dieser Seite:
https://mailcow.github.io/mailcow-dockerized-docs/client/client-manual/
Das hier:
Contacts and calendars¶
SOGos default calendar (CalDAV) and contacts (CardDAV) URLs:

CalDAV - https://mail.example.com/SOGo/dav/user@example.com/Calendar/personal/
CardDAV - https://mail.example.com/SOGo/dav/user@example.com/Contacts/personal/
Some applications may require you to use https://mail.example.com/SOGo/dav/ or the full path to your calender, which can be found and copied from within SOGo.

Die Tabbele oben auf der seite, hat meine daten eingetragen, wie es vorgesehen ist.

**Comment by andryyy** [comment]
Ah, danke, da fehlt einfach nur das JS Gedöns. Ich versuche es später zu fixen, aber heute ist Patchday und libvirtd Upgradeday, da fehlt die Zeit.

**Comment by Conan179** [comment]
Ist schon Lang erledigt.
