### ISSUE TITLE
rancher integration

### ISSUE THREAD

**Issue by imacks** [mailcow/mailcow-dockerized#1666]
i would like to run mailcow in rancher. the current setup cannot work properly in my use scenario, and i hope a neater system can be worked out.

first of all, creating a new network messed rancher up, and i should be better off using stack isolation instead. then there is all the port mapping, which causes port conflict on my hosts (they run other things too). i also don't like giving docker.socks to mailcow if possible. lastly, i feel there are too many images running, all doing ipc and creating overhead. instead, the core components could just be 1 image, and we can use a manager like s6 to restart any failed processes.

so here's what i propose for a rancher integrated version:

- remove acme
- ssl offload by haproxy (haproxy -> mailcow)
  - 443 -> 80/http
  - 465 -> 25/smtp
  - 993 -> 143/imap
  - 995 -> 110/pop3
- remove dockerapi and rely on rancher scheduler to restart bad containers, or `http://rancher-metadata` to query container stats
- combine dovecot, netfilter, phpfpm, postfix and watchdog into a single image (use s6 to supervise)
- rspamd as a separate image (optional)
- clamd as a separate image (optional)
- sogo as a separate image (optional)
- remove unbound and rely on rancher dns

i would be willing to work on a fork if there are many people with similar requirements.

**Comment by Braintelligence** [comment]
Possible duplicate/related: https://github.com/mailcow/mailcow-dockerized/issues/196

**Comment by andryyy** [comment]
Check dockerapi-mailcow: The Docker socket is given to dockerapi-mailcow, we add a new layer to it and only allow a very limited set of commands.

We do not combine apps... this is Docker after all. We would use a VM if we wanted to do so. ;-)
It has **so many** advantages I do not want to drop. The overhead can really be neglected... it cannot be compared to a VM.

Rspamd will not be optional. ClamAV already is, it starts an idling Bash if disabled (we could let it exit with a custom "expected" code like 200 to not restart it though). SOGo _may_ become optional some time in the future.

It does not sound like a neater setup but like a mail server that should be setup in a VM under a real hypervisor.

**Comment by Braintelligence** [comment]
I also agree on not merging everything into one container. This is not the docker-compose way of doing things.
