### ISSUE TITLE
Mailcow UI not updating Rspamd logs

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1667]
Hello,
since yesterday the mailcow web ui doesn't show me new Rspamd log entries anymore the last entire is from sometime yesterday, but if I check the rspamd web ui directly there are a huge number of new mails that have been checked my Rspamd so why is the webui from mailcow out of sync? The refresh button doesn't help. Can you please help me to debug this? Thank you very much :)

**Comment by ntimo** [comment]
Restarting mailcow didn't solved the problem unfortunately :(

**Comment by andryyy** [comment]
Have you tried cleaning your browsers cache? We pull those stats from Rspamd. That’s strange.

**Comment by ntimo** [comment]
Okay I just tested it in a incognito tab and its working there so its probably a caching issue. I will clear my browser cache and then try it again :) Thanks.
