### ISSUE TITLE
phpfpm mysqli extension

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1668]
Hello 👋,
is it possible to add the mysqli extension to the phpfpm container that would make it possible to use phpmyadmin and other php sites that need it :)

Thank you very much,
Timo

**Comment by mritzmann** [comment]
https://github.com/mailcow/mailcow-dockerized/blob/d5e81b987b7150046559db9ac4a6f1d7bdec6912/data/Dockerfiles/phpfpm/Dockerfile#L60

I think `pdo_mysql` is already installed. `mysqli` is therefore not necessary.

**Comment by ntimo** [comment]
Yes but for example phpmyadmin need mysqli so adding it would definitely be nice. And supporting it should not have any drawbacks so why not just add it?

**Comment by miniskulljob** [comment]
You should try [Adminer](https://www.adminer.org/)
It's lightweight, fast and just one file. Maybe it's not as pretty as PMA, but it does the job.

**Comment by mritzmann** [comment]
> And supporting it should not have any drawbacks so why not just add it?

The basic question is: How far do we want to overload Mailcow? Any piece of software can lead somewhere back for problems (e.g. during the build process). Keeping software thin is important.

And you can use your own PHP container for phpmyadmin instead.

But this is a decision @andryyy has to make.

**Comment by RickD123** [comment]
I have the same issue, I need mysqli in PHPFPM. I can install it manually (via docker-php-ext-install), but I need it for one virtual host that uses it. @andryyy I would suggest we re-open the issue.

**Comment by andryyy** [comment]
That's not a bug or an issue. We don't need it for mailcow.

**Comment by drlight17** [comment]
> I have the same issue, I need mysqli in PHPFPM. I can install it manually (via docker-php-ext-install), but I need it for one virtual host that uses it. @andryyy I would suggest we re-open the issue.

Hi. To workaround this I've added the following to the docker-compose.override.yml file:

```
version: '2.1'
services:
    php-fpm-mailcow:
     command: >
      sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php-fpm -d date.timezone=${TZ} -d expose_php=0"
```

And then:

`docker-compose down && docker-compose up -d`
