### ISSUE TITLE
Watchdog: nginx-mailcow service hit the error rate limit nach update vom Ubuntu 16.04 auf Ubuntu 18.04

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1669]
Hallo erst mal.

Ich hab eben meinen Ubuntu 16.04 server innstallation auf Ubuntu 18.04 geupdatet.

Jetzt bekomme ich diese Watchdog mail:
Watchdog: nginx-mailcow service hit the error rate limit
Service was restarted, please check your mailcow installation.

Könnt ihr mir bitte helfen, das wieder alles läuft?
GRuss Conan

**Comment by andryyy** [comment]
Versuch erst alles mit docker-compose down zu stoppen (im mailcow Verzeichnis ausführen), systemctl restart docker, und dann mit docker-compose up -d wieder starten. 

Vermutlich blockiert einfach was den Port. Zum Beispiel ein lokaler Webserver.

**Comment by Conan179** [comment]
root@Ubuntu-1804:~# cd /opt/mailcow-dockerized/
root@Ubuntu-1804:/opt/mailcow-dockerized# docker-compose down
Stopping mailcowdockerized_rspamd-mailcow_1    ... done
Stopping mailcowdockerized_acme-mailcow_1      ... done
Stopping mailcowdockerized_netfilter-mailcow_1 ... done
Stopping mailcowdockerized_php-fpm-mailcow_1   ... done
Stopping mailcowdockerized_unbound-mailcow_1   ... done
Stopping mailcowdockerized_clamd-mailcow_1     ... done
Stopping mailcowdockerized_postfix-mailcow_1   ... done
Stopping mailcowdockerized_dockerapi-mailcow_1 ... done
Stopping mailcowdockerized_redis-mailcow_1     ... done
Stopping mailcowdockerized_memcached-mailcow_1 ... done
Stopping mailcowdockerized_watchdog-mailcow_1  ... done
Stopping mailcowdockerized_dovecot-mailcow_1   ... done
Stopping mailcowdockerized_sogo-mailcow_1      ... done
Stopping mailcowdockerized_mysql-mailcow_1     ... done
Stopping mailcowdockerized_ipv6nat_1           ... done
Removing mailcowdockerized_rspamd-mailcow_1    ... done
Removing mailcowdockerized_acme-mailcow_1      ... done
Removing mailcowdockerized_netfilter-mailcow_1 ... done
Removing mailcowdockerized_nginx-mailcow_1     ... done
Removing mailcowdockerized_php-fpm-mailcow_1   ... done
Removing mailcowdockerized_unbound-mailcow_1   ... done
Removing mailcowdockerized_clamd-mailcow_1     ... done
Removing mailcowdockerized_postfix-mailcow_1   ... done
Removing mailcowdockerized_dockerapi-mailcow_1 ... done
Removing mailcowdockerized_redis-mailcow_1     ... done
Removing mailcowdockerized_memcached-mailcow_1 ... done
Removing mailcowdockerized_watchdog-mailcow_1  ... done
Removing mailcowdockerized_dovecot-mailcow_1   ... done
Removing mailcowdockerized_sogo-mailcow_1      ... done
Removing mailcowdockerized_mysql-mailcow_1     ... done
Removing mailcowdockerized_ipv6nat_1           ... done
Removing network mailcowdockerized_mailcow-network
root@Ubuntu-1804:/opt/mailcow-dockerized#  systemctl restart docker
root@Ubuntu-1804:/opt/mailcow-dockerized# docker-compose up -d
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
Creating mailcowdockerized_redis-mailcow_1     ... done
Creating mailcowdockerized_clamd-mailcow_1     ... done
Creating mailcowdockerized_mysql-mailcow_1     ... done
Creating mailcowdockerized_watchdog-mailcow_1  ... done
Creating mailcowdockerized_ipv6nat_1           ... done
Creating mailcowdockerized_postfix-mailcow_1   ... done
Creating mailcowdockerized_sogo-mailcow_1      ... done
Creating mailcowdockerized_dovecot-mailcow_1   ... done
Creating mailcowdockerized_unbound-mailcow_1   ... done
Creating mailcowdockerized_dockerapi-mailcow_1 ... done
Creating mailcowdockerized_memcached-mailcow_1 ... done
Creating mailcowdockerized_php-fpm-mailcow_1   ... done
Creating mailcowdockerized_nginx-mailcow_1     ... error
Creating mailcowdockerized_netfilter-mailcow_1 ... done

ERROR: for mailcowdockerized_nginx-mailcow_1  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_                                                                                                               nginx-mailcow_1 (8180174b11e6bce160d08a1a46398ada7470a4a5f11dce233b57cb40e684c1ea): Error starting userland proxy: listen tcp 1xxxxxxxx2:443: bind: address                                                                                                                already in use

ERROR: for nginx-mailcow  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_nginx-mailcow_1 (818                                                                                                               0174b11e6bce160d08a1a46398ada7470a4a5f11dce233b57cb40e684c1ea): Error starting userland proxy: listen tcp 188xxxxxxxxxx:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

Jup sieht es so aus, wie finde ich jetzt heraus, was da den port 443 blockiert?

**Comment by andryyy** [comment]
Ist sowieso Apache2 oder Nginx. :-)

systemctl stop nginx apache2
systemctl disable nginx apache2

**Comment by Conan179** [comment]
netstat -tulpen hat es bei mir auch getan, jup war der pöse apache2.
das waren noch reste von der vor mailcow mail-server lösung, Vor dem upgrade war es "disable", das upgraden hat es wieder scharf gemacht.
Weil ich den nicht mehr brauche, landetet der Apache beim grosen manitu.

Ich DANKE dir für die schnelle Hilfe.
