### ISSUE TITLE
After update cant login mailcow ui

### ISSUE THREAD

**Issue by ulrich379** [mailcow/mailcow-dockerized#1671]
After update Login Page mailcow ui is greyed out, sogo works correct.
No errors in the update process, all cointainers running.
What could be the problem?

**Comment by andryyy** [comment]
Is there just an overlay or a blank page?

**Comment by ulrich379** [comment]
Its the normal site but grey

**Comment by andryyy** [comment]
Could be enough to clean the browser cache.

**Comment by ulrich379** [comment]
i've tryed chrom, firefox and edge, without success. Now trying with a tablet.

**Comment by andryyy** [comment]
Or check your dev console in the browser.

**Comment by ulrich379** [comment]
dev console: Laden fehlgeschlagen für das <script> mit der Quelle "https://mx2.u1m.de/js/jquery-1.12.4.min.js".

**Comment by EnriqCG** [comment]
It looks like the `<div class="overlay"></div>` is not removed once the page is fully loaded. I am getting no errors on the console.

If you need to access your mailcow you can manually remove the overlay with this jQuery function on the Chrome/Firefox console: 
```javascript 
$(".overlay").remove(); 
```

**Comment by andryyy** [comment]
It would have been removed if body was fully loaded.

Can you please set `error_reporting(E_ALL);`  in `data/web/inc/vars.inc.php`?

**Comment by ulrich379** [comment]
done, now lunch ist ready

**Comment by EnriqCG** [comment]
>It would have been removed if body was fully loaded

Yes you are right. Contents from [footer.inc.php](https://github.com/mailcow/mailcow-dockerized/blob/a11cce67654e7cd8a268b58592a25801e710861d/data/web/inc/footer.inc.php) are not loaded.

![image](https://user-images.githubusercontent.com/38569176/44144559-4ebfcb86-a088-11e8-90a9-629c4332c310.png)

**Comment by andryyy** [comment]
`git checkout data/web`?

**Comment by ulrich379** [comment]
this bring me back to the code without error-reporting.
Now trying changes in footer.inc

**Comment by alexanderrieder** [comment]
I have a white overlay ... :/

**Comment by andryyy** [comment]
I would need access to that machine via ssh to check it.

**Comment by alexanderrieder** [comment]
@andryyy to which email should I email the credentials?

**Comment by andryyy** [comment]
info@servercow.de

**Comment by andryyy** [comment]
Should be fixed. :-)

**Comment by ulrich379** [comment]
What was the reason?

**Comment by andryyy** [comment]
See 2c58323e36deb04575085c3021508a0cba26df88

**Comment by ulrich379** [comment]
works thank you!

**Comment by nieselregencom** [comment]
I had the same problem. Logging on to the mailcow UI works again for me, too.

But now I have problems logging in as a mail user: Everything works via IMAP and SMTP. Logon does not work either via the web interface or via Microsoft Exchange ActiveSync.

**Comment by nieselregencom** [comment]
MySQL Fehler: PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'aliases' at row 5 in /web/inc/functions.inc.php:546 Stack trace: #0 /web/inc/functions.inc.php(546): PDO->query('REPLACE INTO _s...') #1 /web/inc/functions.mailbox.inc.php(3498): update_sogo_static_view() #2 /web/json_api.php(957): mailbox('edit', 'mailbox', Array) #3 {main}

**Comment by andryyy** [comment]
I will fix it when I’m home. 

You seem to have a huge alias goto field there.

**Comment by nieselregencom** [comment]
Yeah, I've got a really high number of aliases. You got that right!

**Comment by andryyy** [comment]
@nieselregencom please try again with todays update. :-)

**Comment by nieselregencom** [comment]
It's working again.

Thanks!

**Comment by Afondevi** [comment]
Hello @andryyy, same problème pop again ! ;)

**Comment by andryyy** [comment]
Cannot confirm. Demo seems fine too. 

Need more info.

**Comment by Afondevi** [comment]
@andryyy you can see next picture... :/ 

<img width="1528" alt="capture d ecran 2018-10-11 a 16 00 45" src="https://user-images.githubusercontent.com/11740298/46809567-02fd0380-cd6f-11e8-93d0-ad1e79c60f68.png">
<img width="670" alt="capture d ecran 2018-10-11 a 16 01 00" src="https://user-images.githubusercontent.com/11740298/46809604-1b6d1e00-cd6f-11e8-9f99-f3d2909be2e2.png">

**Comment by andryyy** [comment]
It is not that I don’t believe you. But it is a local problem. :-(

Also: why is there a X-XSS header problem?

**Comment by Afondevi** [comment]
Ok ! Maybe my headers config probleme ! 😄

[UPDATE]
Ok It was my config probléme for this domain.. Sorry :)

**Comment by andryyy** [comment]
No problem. :-)

**Comment by devpanda0** [comment]
Hey, i have this overlay after update but i cant find a error. http://sharex.florianrichter.eu/8xKf
