### ISSUE TITLE
Can not use Mailcow to relay emails

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#1672]
Hello,

i have to different servers. one for my cloud, homepages and many other stuff and my second for mailcow. They use different ips. i would like to relay some emails via plesk and i fill in my mail.domain.tld as relay server. If i send a test message to an e-mail adress there are 2 lines in my postfix log.

`warning: hostname mail.domain.tld does not resolve to address 85.xxx.xx.x7`
shown as warning

`connect from unknown[85.xxx.xx.x7]`
shown as info.

The IP is from my other server but i cant understand why postfix is thinking, that this ip adress has to resolve to mail.domain.tld. 

I also have found an option in mailcow to relay only one or two mailboxes, but i dont know how to create a blind mailbox. i just found some threads in the internet, but nobody talks about to create that blind mailbox. maybe im stupid, maybe im not 🌝 

Hope anybody can help 👍

**Comment by ClepToManix** [comment]
Anybody who can help me

**Comment by Ashby666** [comment]
Hi ClepToManix,

my last update is that the feature is currently not supported (WIP). But that can be outdated.

Currently we use SMTP-AUTH with a dummy mailbox (port 465) if a system should relay. This works quite well so far, but is not practicable in every scenario.

BG,
Ashby

**Comment by constin** [comment]
This is not mailcow issue. This is just problem with your misconfiguration. I think this place is for bugs in code or something.  I'd like to help you anyway , but your description is unreadable.
