### ISSUE TITLE
"Disable sender check for domain *" does not work

### ISSUE THREAD

**Issue by a3li** [mailcow/mailcow-dockerized#1674]
It seems like the relatively new feature (bdf76327579a996dab2594bb1b3936e94c3abd49 was 2 weeks ago) to disable the sender check for any domain does not work.

I'm using it for a mailbox user that relays all kinds of email from satellite hosts through the central mailcow host. I have to explicitly select all my domains for it to relay email correctly.

Log when using the "Disable check for * " feature:
```
Aug 15 19:22:08 satellite-host postfix/qmgr[20676]: 0FA661216FF: from=<alex@example.com>, size=614, nrcpt=1 (queue active)
Aug 15 19:22:08 satellite-host postfix/smtp[25188]: 0FA661216FF: to=<alex.legler@example.com>, relay=my-mailcow[IP]:25, delay=0.26, delays=0.09/0/0.13/0.05, dsn=5.7.1, status=bounced (host my-mailcow[IP] said: 553 5.7.1 <alex@example.com>: Sender address rejected: not owned by user mailrelay@example.com (in reply to RCPT TO command))
```

**Comment by andryyy** [comment]
Are your images up to date?

`docker-compose exec postfix-mailcow postalias -q alex@example.com mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf` does return what?

And `cat data/conf/postfix/sql/mysql_virtual_sender_acl.cf`?

**Comment by a3li** [comment]
Thanks for the quick reply!
Postfix image is on 1.20 which seems to be the latest on docker hub as well.

With the "check for *" feature, `postalias -q` prints nothing; with the domain explicitly added it prints `mailrelay@example.com`.

My mysql_virtual_sender_acl is missing the change from bdf76327579a996dab2594bb1b3936e94c3abd49 (so no `OR send_as='*'`) if that's what you were looking for. If not, full contents here: https://gist.github.com/a3li/179e24f6efdb8b2c82c6409ba41a9d35

**Comment by andryyy** [comment]
Looks like postfix-mailcow cannot write/change that file. A `docker-compose restart postfix-mailcow` _should_ rewrite that file. Does it? Can you check the files access/change times before and after?

**Comment by a3li** [comment]
It does recreate it, but looking into the container, `postfix.sh` is not updated to support the feature there. Can you double-check and maybe push a new container version?

**Comment by andryyy** [comment]
I will push a new image in a bit!

**Comment by a3li** [comment]
Updated and it works. Danke!

**Comment by andryyy** [comment]
Hah, sorry und danke für den Hinweis. :-)
