### ISSUE TITLE
Cant send Emails via Webinterface SOGO

### ISSUE THREAD

**Issue by alexanderrieder** [mailcow/mailcow-dockerized#1676]
Hello,

I just updated my server to the newest release and i cant send emails from the webinterface. THe reason is as far as I think, that the SOGO doesnt know from which address it should send the email. 
![image](https://user-images.githubusercontent.com/31474170/44198423-a9e36b80-a141-11e8-8d32-61df515d7de3.png)

**Comment by andryyy** [comment]
Have you tried to restart SOGo?

**Comment by alexanderrieder** [comment]
Yes, for the Moment i restored My mailcow vm from a backup 

Von meinem iPhone gesendet

**Comment by andryyy** [comment]
I have not seen this problem anywhere on our machines. It is too late for me to help now. :-/

**Comment by alexanderrieder** [comment]
Ok, i can clone the vm and give you Access to the Clone.. i will do it this evening. Maybe the Problem will Appear again. 

Von meinem iPhone gesendet

**Comment by andryyy** [comment]
Don't know if I am available then. My free support is really limited at the moment.

**Comment by alexanderrieder** [comment]
ok, I also got this problem on the server which I've sent you the login details yesterday (where I had problems with the white overlay). 
The login and password are the same as yesterday.

Maybe you find time to look into it :)

**Comment by alexanderrieder** [comment]
The issue was caused by the browser cache... :/ Clearing the cache was the solution.
