### ISSUE TITLE
Share IMAP Folder inside SOGo with any users from the same Domain

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#1677]
Currently, mail folders can be shared with `Any authenticated User` or individual users. (`Any authenticated User` shares the folder with all users on the same installation.)

![sharing](https://user-images.githubusercontent.com/4533780/44199696-114eea80-a145-11e8-9e7d-1c95992bc79d.png)

I would like to share a mail folder with all users of the same domain. All users with same domain (e.g. `@example.com`) should have access to it, but not users from another domain (e.g. `example2.org`).

---

The question now is:

* Is this already possible: If yes, how?
* If it is not possible or only with manual adjustment: Then this would be a feature request (if feasible)

**Comment by andryyy** [comment]
`acl_anyone = allow` needs to be removed from dovecot.conf.

**Comment by andryyy** [comment]
It should be default, I guess.

**Comment by andryyy** [comment]
It is disabled now. Docs were updated.
