### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by Diniboy1123** [mailcow/mailcow-dockerized#1678]
Hi,

I just installed mailcow under an Ubuntu server and when I try to start it, it gives me the following errors:

```
Creating mailcowdockerized_clamd-mailcow_1     ... done
Creating mailcowdockerized_postfix-mailcow_1   ... done
Creating mailcowdockerized_mysql-mailcow_1     ... error
Creating mailcowdockerized_ipv6nat_1           ... done
Creating mailcowdockerized_unbound-mailcow_1   ... done
Creating mailcowdockerized_redis-mailcow_1     ... done
Creating mailcowdockerized_dovecot-mailcow_1 ...
Creating mailcowdockerized_memcached-mailcow_1 ...
Creating mailcowdockerized_watchdog-mailcow_1  ...
Creating mailcowdockerized_sogo-mailcow_1      ... done
Creating mailcowdockerized_dockerapi-mailcow_1 ...
Creating mailcowdockerized_php-fpm-mailcow_1   ...

ERROR: for mailcowdockerized_mysql-mailcow_1  Cannot start service mysql-mailcowCreating mailcowdockerized_dovecot-mailcow_1   ... error
Creating mailcowdockerized_memcached-mailcow_1 ... done
Creating mailcowdockerized_watchdog-mailcow_1  ... done
d3 -o br-<snipped> -p tcp -d <snipped> --dport 3306 -j ACCEPT' failed: AnothCreating mailcowdockerized_dockerapi-mailcow_1 ... done
Creating mailcowdockerized_php-fpm-mailcow_1   ... done
Creating mailcowdockerized_nginx-mailcow_1     ...

ERROR: for mailcowdockerized_dovecot-mailcow_1  Cannot start service dovecot-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_dovecot-mailcow_1 (<snipped>):  (COMMAND_FAILED: '/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport <snipped> -j DNAT --to-destination <snipped>:12345 ! -i br-<snipped>' failed: Another app is currently holding the xtables lock. Stopped waiting after 2s.
Creating mailcowdockerized_nginx-mailcow_1     ... done
Creating mailcowdockerized_rspamd-mailcow_1    ... done

ERROR: for mysql-mailcow  Cannot start service mysql-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_mysql-mailcow_1 (<snipped>):  (COMMAND_FAILED: '/sbin/iptables -w2 -t filter -A DOCKER ! -i br-<snipped> -o br-<snipped> -p tcp -d <snipped> --dport 3306 -j ACCEPT' failed: Another app is currently holding the xtables lock. Stopped waiting after 2s.
)

ERROR: for dovecot-mailcow  Cannot start service dovecot-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_dovecot-mailcow_1 (<snipped>):  (COMMAND_FAILED: '/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport <snipped> -j DNAT --to-destination <snipped>:12345 ! -i br-<snipped>' failed: Another app is currently holding the xtables lock. Stopped waiting after 2s.
)
ERROR: Encountered errors while bringing up the project.
```

Obviously with some snips because it might contain some sensitive data.

Oh and the webinterface is just grey...

What can be wrong?

**Comment by Diniboy1123** [comment]
According to the grey page, it might caused by this:

```
$(window).load(function() {
  $(".overlay").hide();
});
$(document).ready(function() {
  window.mailcow_alert_box = function(message, type) {
    msg = $('<span/>').text(message).text();
    if (type == 'danger') {
      auto_hide = 0;
      $('#' + localStorage.getItem("add_modal")).modal('show');
      localStorage.removeItem("add_modal");
    } else {
      auto_hide = 5000;
    }
    $.notify({message: msg},{z_index: 20000, delay: auto_hide, type: type,placement: {from: "bottom",align: "right"},animate: {enter: 'animated fadeInUp',exit: 'animated fadeOutDown'}});
  }
  <br />
<b>Warning</b>:  Illegal offset type in <b>/web/inc/functions.inc.php</b> on line <b>201</b><br />
```

What is that warning in a JS code?

**Comment by andryyy** [comment]
There is much more wrong with that host. Is this an OpenVZ container?
Well, Docker cannot set any iptables rules. That’s a big problem. What is holding that xtables lock?

The PHP warning does not appear by default. You probably set them to be displayed in vars.inc.php.

**Comment by Diniboy1123** [comment]
I have no idea what is an OpenVZ container so I assume no. The only special thing that we have is a firewalld firewall instead of ufw that comes along with Ubuntu.

The iptables binary is a symlink which points to xtables-multi:

`lrwxrwxrwx 1 root root 13 Nov 12  2017 /sbin/iptables -> xtables-multi`

An interesting thing that I just noticed is this:

```firewalld[2638]: WARNING: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s <snipped> -d <snipped> --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.```

And a few lines before like that. It was in my `systemctl status firewalld` output.

**Comment by Diniboy1123** [comment]
And if I disable logging the warns, it says $ is not defined and it cannot load the https://mydomain.tld/js/footable.min.js file...

**Comment by andryyy** [comment]
You need to fix the iptables errors, I cannot help with that.

driver failed programming external connectivity on endpoint mailcowdockerized_dovecot-mailcow_1 (<snipped>):  (COMMAND_FAILED: '/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport <snipped> -j DNAT --to-destination <snipped>:12345 ! -i br-<snipped>' failed: Another app is currently holding the xtables lock. Stopped waiting after 2s.

This is fatal, Docker cannot create any fw rules, I guess.

Check if apparmor, selinux, whatever is blocking these commands and disable your firewall configuration. It should not interfere with any rules Docker creates. it won't work when Docker cannot inject its rules.

**Comment by Diniboy1123** [comment]
It is a problem with firewalld I think. But unfortunately I cannot disable it since I have a very complicated ruleset there that I cannot remake with ufw. [Similar issue](https://github.com/moby/moby/issues/16137)

Should I open a docker/firewalld ticket? BTW if I stop firewalld completely, none of the docker containers work. If I reenable them, most of them works.

**Comment by stevesbrain** [comment]
Whilst you may not be able to replicate the rules with UFW, is it possible to replicate them with a "standard" iptables setup? If so, that'd then provide you the full interoperability you need, I dare say.

**Comment by mkuron** [comment]
Even UFW and iptables have interoperability issues with Docker. Just search the existing issues here and in the Docker/libnetwork repositories. It's not Mailcow's fault (though it is particularly sensitive as it uses port exposition and inter-container networking) and it's basically impossible to fix on the Docker side because Docker can't understand your firewall rules.

If you can't just switch off the firewall (and work with at most a few minimal hand-written iptables rules), you should move Mailcow to a (separate) virtual machine without a firewall configured.
