### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by colinhall17** [mailcow/mailcow-dockerized#1680]
Hi

I'm new to setting up mail servers and so far have managed to get my way around.

However I'm having trouble redirecting all requests to the Mailcow UI through HTTPS, if I enter https I get the secure connection, however I am still able to access through http.  

I did some research to on how to do this through nginx, however I cant find the nginx config file as I'm guessing its in the docker container.  I'm also new to docker ….

Any pointers as to what I need to do and where?

Thanks

**Comment by ghost** [comment]
Hi colinhall17,
have you looked [here](https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/)

**Comment by colinhall17** [comment]
Sorry … I've read the docs many times, probably including that page.  No excuses for missing that.

**Comment by ghost** [comment]
Never mind, that just can happen :-)
