### ISSUE TITLE
Custom ssl certificate error

### ISSUE THREAD

**Issue by usrlibzy** [mailcow/mailcow-dockerized#1682]
Hello ,
I have a vps which runs nginx mysql etc outside , and docker with mailcow installed in .
Self-signed certificate cannot be used in my project , and due to the occupation of nginx on port 80 , I cannot use the **acme-mailcow** container to set up certificates automatically . In stead , I linked my Letsencrypt certificates of **MAILCOW_HOSTNAME** to **data/assets/ssl** just as this issue told : https://github.com/mailcow/mailcow-dockerized/issues/156
But then , when my application tried to use ssl or tls to send emails , it always get **SSL Handshake timeout** or as the log below :

> warning: TLS library problem: error:140DC002:SSL routines:use_certificate_chain_file:system lib:../ssl/ssl_rsa.c:609:
2018/8/18 12:07:33	warning	warning: TLS library problem: error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:294:
2018/8/18 12:07:33	warning	warning: TLS library problem: error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:292:fopen('/etc/ssl/mail/cert.pem','r'):
2018/8/18 12:07:33	warning	warning: cannot get RSA certificate from file "/etc/ssl/mail/cert.pem": disabling TLS support

Could anyone help me with this problem ?
How to make my custom certificate working ?
Or is there any idea that with nginx outside docker running and occupying the port 80 , **acme-mailcow** containter can still work ?
Thanks , anbody !

**Comment by barry-smithjr** [comment]
I use the docker-compose.override.yml referenced in the comments of #1421 and it works like a charm!

**Comment by andryyy** [comment]
@barry-smithjr 

This comment? => https://github.com/mailcow/mailcow-dockerized/issues/1421#issuecomment-403886658

It is interesting it follows sym links.

**Comment by barry-smithjr** [comment]
@andryyy 

That one and the main initial comment about the override file here which contains the full file => [#1421 (daschxx comment)](https://github.com/mailcow/mailcow-dockerized/issues/1421#issuecomment-392275702)

**Comment by andryyy** [comment]
Ah, okay, thanks. :-)

**Comment by mkuron** [comment]
Symlinks cannot be used as they point outside the container. Using a volume via docker-conpose override is expected to work though.
