### ISSUE TITLE
dkim for domain alias

### ISSUE THREAD

**Issue by daemon-byte** [mailcow/mailcow-dockerized#1685]
Hi,

I have only just started using your software after I was tired of propping up my wobbly iredadmin one. I have to say so far it's much better than the other one. I was wondering however is there a way to copy the dkim signature for my main domain to the alias domains? 
![capture](https://user-images.githubusercontent.com/517787/44287564-933a3300-a26d-11e8-861d-f19bd102badb.PNG)

**Comment by Knight1** [comment]
Yes!

set ```$SHOW_DKIM_PRIV_KEYS = true;``` into data/web/vars.local.inc.php 

Then display the dkim private key and import it when you add the domain :)

**Comment by svengo** [comment]
Just for the files: 
`$SHOW_DKIM_PRIV_KEYS = true;` have to be added to `data/web/inc/vars.local.inc.php`.

**Comment by JackBailey** [comment]
I found it at

`data/web/inc/vars.inc.php`

Just updated it to true and refreshed mailcow in my browser and it worked.

**Comment by subedinfo-it** [comment]
> I found it at
> 
> `data/web/inc/vars.inc.php`
> 
> Just updated it to true and refreshed mailcow in my browser and it worked.

the point of using `vars.local.inc.php` instead of `vars.inc.php` is the former doesn't get overwritten by updates. Editing the original files instead of adding overrides is not a good practice.
