### ISSUE TITLE
ERROR: manifest for mailcow/sogo:1.34 not found

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1686]
Good evening,

i just updated mailcow an got this error: ERROR: manifest for mailcow/sogo:1.34 not found
After that mailcow started to create sogo local.

How to fix that?

**Comment by Knight1** [comment]
It was updated 9 Minutes ago. May you try it again?

**Comment by ghost** [comment]
I did and it works again :-)

**Comment by ghost** [comment]
Thanks, i'm closing this issue.
