### ISSUE TITLE
DKIM Import/Add Multiple Domains & Status Update

### ISSUE THREAD

**Issue by th3technician** [mailcow/mailcow-dockerized#1687]
Hi there, I've a feature request that would be really nice to add or at least if someone could guide me through how could i achieve it manually. 

- The "Add ARC/DKIM Key' + "Import Private Key" forms input field "Domain" is missing the option to use multiple domains and its really annoying when trying to add or import keys for 5-10 domains you would have to go through each one manually one by one while it could be simple as adding a feature to allow multiple domain by using a separator such as a comma

For example in Domain input field we could just use : domain1.com,domain2.com,domain3.com
and so on

Hope you guys got it.

- Is there is a workaround to make a default "ratelimit" for outgoing mail once adding new domain ? All the other fields have a default like domain quota etc except ratelimit which is annoying too, i could forget to add a ratelimit for the user which then he could just use mailcow hostname and connect my smtp to any mailer and use my server for sending spam. 

- And also @andryyy  what is the status on dkim checkbox on adding a new domain ?

Thanks all in advance!

**Comment by andryyy** [comment]
Some things need an estimate, especially when mailcow is used commercially.

**Comment by andryyy** [comment]
Btw. a checkbox will not work. It needs a selector and a size in bits.

**Comment by th3technician** [comment]
> Btw. a checkbox will not work. It needs a selector and a size in bits.


Yeah but what about the other things i mentioned ?

**Comment by th3technician** [comment]
There should be an input field too in the tab where we add domains to specify ratelimit

**Comment by andryyy** [comment]
There is no status update as I am not working on these features.

I added a label, but there is no guarantee I can work on it soon.

**Comment by miniskulljob** [comment]
I'm interested in this too.
From what I could find looking at the source code, I think we can create a simple PHP script to add all the DKIM keys using the function `dkim` in the file `data/web/inc/functions.dkim.inc.php`.

**Comment by andryyy** [comment]
No. Well, yes, for a very rudimentary implementation. It still needs parameters and the option to dupliacte keys etc. ... there is more that needs to be changed.

But even "simple" work is... work. :-)

**Comment by th3technician** [comment]
Yes np. Like your app though! Closing this ticket
