### ISSUE TITLE
Plans to back-port to regular mailcow?

### ISSUE THREAD

**Issue by BlamKiwi** [mailcow/mailcow-dockerized#1692]
MailCow is the best OSS self-hosted EMail/GroupWare solution I've ever tried using. My barrier to deploying this for the businesses I manage (and one that will be shared by many other SysAdmins) is that Docker is not stable enough for static, mission critical deployments such as a mail server. We need infrastructure strong enough to bounce off concrete. 

Particularly hosting databases in Docker is bad practice, the risk of interaction with unknown bugs is still too high and could lead to data corruption. 

Are there any plans to back-port to the original mailcow? Alternatively if we could easily host databases outside the docker-compose cluster I would find the risk more acceptable.

**Comment by andryyy** [comment]
It is stable to use. It is not bad practice.

We have multiple managed mailcows that survived hard server resets. It is not more prone to errors when it runs in a container.

There is no plan to backport mailcow right now.

I thought about external SQL connections, but I don't want to add support for this. SQL != SQL. There are settings that need to fit mailcows requirements, most will ignore them - from experience. :-(

I have setup environments with external SQL clusters, where we just hooked the sockets into the containers. Alternatively one could use ProxySQL or similar software.

We offer service subscriptions, this may reduce discomfort... :-)
