### ISSUE TITLE
Display of emails in Shared Folder not working

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#1694]
Hi all,
I just added a shared folder and added access right for one user of the same domain (dovecot-acl has the rights 'ilrws'). The problem is that if I access the emails from within SOGo or IMAP sometimes it works and sometimes it stalls. If it stalls no more Emails are shown in the shared folder in imap. In SOGo an error message 'Did not find specified message' occurs and nothing else can be selected in that folder. If i select another local folder now this one works correctly and if thereafter the shared folder is selected again the result is what you can see in the screenshot (lists all emails but without any name or details). If I click on refresh (on the screenshot image) the shared folder now is shown with 0 (ZERO) emails. This also now applies to the origin account who is sharing the folder. The folder is display empty (within imap and sogo). The emails however are still available on the filesystem. They all ONLY appear again in imap and SOGO, if I move a new email into that shared folder. Seems to be some kind of indexing problem when shared?!
![unbenannt](https://user-images.githubusercontent.com/11010788/44331140-04920580-a469-11e8-88b9-bc8f8ef76fdf.PNG)

Can anybody reproduce this? It is a complete fresh install of mailcow with actual update.

Further information: The shared folder is a subfolder. The preceeding folder is in the maildir root with dovecot-acl 'kilrwts'.

BR
Mario

**Comment by Mr-Martinez** [comment]
Hi @Skydiver84de

I'm wondering if this is still an issue or have you solved it?
If not, what version of SOGo is running?
Also have you posted this to [SOGo's bug tracking system](https://sogo.nu/bugs/login_page.php)?

**Comment by Skydiver84de** [comment]
The error is still there and appears in SOGo and IMAP. Will do. Thank you for the hint.

**Comment by Mr-Martinez** [comment]
Can you try the following in the root folder of mailcow-dockerized:

```
docker-compose build sogo-mailcow
docker-compose up -d sogo-mailcow
```

Since this error happened after a fresh install, followed by an update, it might be a SOGo issue.

**Comment by Skydiver84de** [comment]
Did try and the error persists:

If I try to access the shared email folder from the user-shared-to the sogo log is without errors but the dovecot log shows the following error (user and domain details substituted <>):

`Error: imap(<user@domain.com>)<820><AdrzKyh0HrqsFgH4>: /var/vmail/<domain.com>/<user-shared-to>/Shared/<user-shared-from>/.Testfolder/dovecot.index.pvt view is inconsistent`

On the filesystem the folder in `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/<domain.com>/<user-shared-to>/Shared/<user-shared-from>/` is **empty**.

Thus the dovecot error makes sense, because it tries to access a file which does not exist on the filesystem.

But why does it not exist? Shall I manually build dovecot-sogo and try again?

Thanks for your help!
Mario

**Comment by Skydiver84de** [comment]
If i login with the user-shared-to and click on refresh in the shared folder the emails sometimes appear again and are readable. Sometimes show empty like in the image above or disappear and give an error code as shown in the first post.

The dovecot log shows several messages like:
`imap(<user-shared-from@domain.com>)<122><xlzfayh0Dvxd0XY2>: Warning: Maildir /var/vmail/<domain.com>/<user-shared-from>/.Testfolder: Expunged message reappeared, giving a new UID (old uid=1, file=1535091867.M363177P156.<server.domain.com>,S=9045,W=9255:2,S)`

**Comment by Skydiver84de** [comment]
OK now after some extensive clicking in the shared folder within the user-shared-to account the SOGo log shows the following errors:

`[52]: [ERROR] <0x55cf5ce76830[SOGoAppointmentInboxFolder]:inbox> (-[SOGoGCSFolder toOneRelationshipKeys]): fetch failed!`

`[52]: <0x0x55cf5ccdac10[NGImap4ResponseParser]> ERROR: got no body content for key: 'body[header.fields'`

`[52]: <0x0x55cf5cde83d0[NGImap4Client]> ERROR(-[NGImap4Client _processCommandParserException:]): catched IMAP4 parser exception NGImap4ParserException: unsupported fetch key: nil)`

`[52]: [ERROR] <0x0x55cf5cf45b20[NGImap4Connection]> Error fetching 3 uids for url: imaps://<user-shared-to>%40<domain.com>@dovecot/Shared/<user-shared-from>@<domain.com>/Testfolder/?tls=YES`

`[52]: [WARN] <0x55cf5cd5ca50[SOGoMailFolder]:folderTestfolder> IMAP connection is broken, trying to reconnect...`

Seems to be a problem with the imap connection?!

**Comment by Mr-Martinez** [comment]
I tried to recreate the error, but I could not.

When sharing email sub-folder between users, I was able to see mail, and their names next to the share screen (where yours is empty mines is not).

On dummy users, I was able to view the mail that was shared.

Have you tried rebuilding?
Also can you try to see if creating a new share sub-folder between 1 user is working?

~Jose

**Comment by Skydiver84de** [comment]
Hi Jose. 

I deleted and created test share folders over and over again. Always the same.  I am on the newest update. 

If you share a folder can you post what is actually on the filesystem (Vmail/domain/user-shared-to/Shared/user-shared-from/)? I think it has to do something with dovecot access rights but I do not understand why because it is a new VM with a fresh install and update of mailcow behind a nginx reverse proxy according the documentation.

**Comment by andryyy** [comment]
Is this a private installation? I can check it via remote access if possible. There are a few things we can try, it would be much faster that way.

**Comment by Skydiver84de** [comment]
Hi Andre,

yes it is a private installation. Will send you an email shortly.

Thank you!

**Comment by Mr-Martinez** [comment]
For the server filesystem, the folder would be

`/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/<domain.com>/<user-shared-to>/Shared/<user-shared-from>/.Folder.SubFolder/dovecot.index.pvt.log`

and

`/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/<domain.com>/<user-shared-to>/Shared/<user-shared-from>/.Folder.SubFolder/dovecot-uidlist`

as for what what the volume filesystem location would be, for me vmail volume is mounted on /var/vmail/...

**Comment by Skydiver84de** [comment]
Andre found a bug in the dovecot.conf namespace for shared folder section and will fix the issue soon. I will close the issue.

Thank you Andre

**Comment by mritzmann** [comment]
I got the same problem, testet on 4b09b5b1bb78cb5e5623954bc9680342e982a725.

> Andre found a bug in the dovecot.conf namespace for shared folder section and will fix the issue soon

Has the problem already been fixed? If not, what was the problem?

**Comment by andryyy** [comment]
```
-    location = maildir:%%h/:CONTROL=~/Shared/%%u:INDEXPVT=~/Shared/%%u
+    location = maildir:%%h/:INDEX=~/Shared/%%u;CONTROL=~/Shared/%%u
```

**Comment by mritzmann** [comment]
@andryyy Thanks, works for me! I think we need this fix in the master. Others are certainly also affected. Is there a reason why this has not yet been generally fixed, or should I make a pull request with this fix?

**Comment by andryyy** [comment]
No, already fixed but not pushed. Will do this later.

**Comment by mritzmann** [comment]
Sounds great :+1:
