### ISSUE TITLE
eM Client doesn‘t autodiscover calendar and contacts anymore

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#1696]
Hallo erst mal..
Ich versuche momentan das Mai programm em Client bei mir, so ein zurichten, das ich sowoll email als auch den Kalender nutzten kann.
Mein Problem ist nicht die mailcow software, das lgaube ich will, android, Windows 10 ohne probleme das geliche machen, was ich mit em client machen möchte.

Per imap und smtp geht das verbinden, aber dann kein zugriff auf den Kalender und die Kontakte.
Wie kann ich heraus finden, woran es genau liegt?

GRuss Conan
![em_exc_1 - kopie](https://user-images.githubusercontent.com/1906242/44352567-0679ba00-a4a5-11e8-8c30-36dd5a999cd5.JPG)
![em_exc_2 - kopie](https://user-images.githubusercontent.com/1906242/44352568-07125080-a4a5-11e8-8147-7836dec05cf5.JPG)
![em_exc_3 - kopie](https://user-images.githubusercontent.com/1906242/44352569-07125080-a4a5-11e8-9791-e9edcf613945.JPG)
![em_exc_4 - kopie](https://user-images.githubusercontent.com/1906242/44352570-07125080-a4a5-11e8-9883-0e32aec1f75e.JPG)
![em_exc_5 - kopie](https://user-images.githubusercontent.com/1906242/44352571-07125080-a4a5-11e8-8613-01a1ba6cdc39.JPG)
![em_exc_6 - kopie](https://user-images.githubusercontent.com/1906242/44352572-07aae700-a4a5-11e8-989a-cff568602f4b.JPG)

**Comment by mkuron** [comment]
Wir haben unter https://mailcow.github.io/mailcow-dockerized-docs/client/client-emclient/ eine Anleitung, aber vielleicht hat sich in der neuesten eM Client Version etwas geändert. Exchange-Accounts gab es in eM Client jedenfalls früher nicht, und Mailcow ist auch kein Exchange.

Du darfst den Account also nicht als Exchange-Account hinzufügen, sondern als "normalen" Mailaccount mit IMAP/SMTP. Bei der Autodiscovery, wo die Serveradressen detektiert werden, müsste dann auch CardDAV/CalDAV erkannt werden.

**Comment by Conan179** [comment]
Stimmt mailcow ist kein Exchange, aber bietet Exchange funktionen, wie gesagt , Android und Windows 10 mail und Kalender erkennen es und nutzten es auch.

Die anleitung habe ich bereits mehrmals gemacht, er erkennt immer nur Imap und Smtp, kein Kalender und keine Kontakte.

https://mailcow.github.io/mailcow-dockerized-docs/client/client-android/
"Select Microsoft Exchange ActiveSync."

https://mailcow.github.io/mailcow-dockerized-docs/client/client-windows/
"Select Exchange."

**Comment by mkuron** [comment]
Windows benutzt Exchange ActiveSync, was Mailcow unterstützt. eM Client scheint Exchange Web Services nutzen zu wollen, wenn man Exchange auswählt, was nur der echte Microsoft Exchange Server unterstützt.

Warum die Autodiscovery Kalender und Kontakte nicht erkennt, muss ich mal testen. Wird der Servername bei dir automatisch gefunden?

**Comment by Conan179** [comment]
Aha wieder was gelernt.
em client erkennt beim einrichten von imap und smtp die einstellungen von allein, wen du das meinst.

**Comment by Conan179** [comment]
Ich hab mich gleichzeitig an den Support vom em client gewand, dort wurde mir empfohlen die autodiscover Einstellungen per https://testconnectivity.microsoft.com/  zu testen.
Inntresannter weise schlägt der test immer fehl:

	The Microsoft Connectivity Analyzer is testing Exchange ActiveSync.
 	The Exchange ActiveSync test failed.
 	
	Additional Details
 	
Elapsed Time: 6663 ms.
 	
	Test Steps
 	
	Attempting the Autodiscover and Exchange ActiveSync test (if requested).
 	Testing of Autodiscover for Exchange ActiveSync failed.
 	
	Additional Details
 	
Elapsed Time: 6662 ms.
 	
	Test Steps
 	
	Attempting each method of contacting the Autodiscover service.
 	The Autodiscover service couldn't be contacted successfully by any method.
 	
	Additional Details
 	
Elapsed Time: 6662 ms.
 	
	Test Steps
 	
	Attempting to test potential Autodiscover URL https://xxxxx.xxxxx.xx:443/Autodiscover/Autodiscover.xml
 	Testing of this potential Autodiscover URL failed.
 	
	Additional Details
 	
Elapsed Time: 1020 ms.
 	
	Test Steps
 	
	Attempting to resolve the host name xxxxx.xxxxx.xx in DNS.
 	The host name resolved successfully.
 	
	Additional Details
 	
IP addresses returned: 188.xxxxxxxxxx 2a01:xxxxxxxx
Elapsed Time: 401 ms.
	Testing TCP port 443 on host xxxxx.xxxxx.xx to ensure it's listening and open.
 	The port was opened successfully.
 	
	Additional Details
 	
Elapsed Time: 211 ms.
	Testing the SSL certificate to make sure it's valid.
 	The SSL certificate failed one or more certificate validation checks.
 	
	Additional Details
 	
Elapsed Time: 408 ms.
 	
	Test Steps
 	
	The Microsoft Connectivity Analyzer is attempting to obtain the SSL certificate from remote server xxxxx.xxxxx.xx on port 443.
 	The Microsoft Connectivity Analyzer wasn't able to obtain the remote SSL certificate.
 	
	Additional Details
 	
The certificate couldn't be validated because SSL negotiation wasn't successful. This could have occurred as a result of a network error or because of a problem with the certificate installation.
Elapsed Time: 381 ms.
	Attempting to test potential Autodiscover URL https://autodiscover.xxxxx.xxxxx.xx:443/Autodiscover/Autodiscover.xml
 	Testing of this potential Autodiscover URL failed.
 	
	Additional Details
 	
Elapsed Time: 1549 ms.
 	
	Test Steps
 	
	Attempting to resolve the host name autodiscover.xxxxx.xxxxx.xx in DNS.
 	The host name resolved successfully.
 	
	Additional Details
 	
IP addresses returned: 188.xxxxxxxxxxxxxxxxx
Elapsed Time: 386 ms.
	Testing TCP port 443 on host autodiscover.xxxxx.xxxxx.xx to ensure it's listening and open.
 	The port was opened successfully.
 	
	Additional Details
 	
Elapsed Time: 208 ms.
	Testing the SSL certificate to make sure it's valid.
 	The SSL certificate failed one or more certificate validation checks.
 	
	Additional Details
 	
Elapsed Time: 954 ms.
 	
	Test Steps
 	
	The Microsoft Connectivity Analyzer is attempting to obtain the SSL certificate from remote server autodiscover.xxxxx.xxxxx.xx on port 443.
 	The Microsoft Connectivity Analyzer wasn't able to obtain the remote SSL certificate.
 	
	Additional Details
 	
The certificate couldn't be validated because SSL negotiation wasn't successful. This could have occurred as a result of a network error or because of a problem with the certificate installation.
Elapsed Time: 399 ms.
	Attempting to contact the Autodiscover service using the HTTP redirect method.
 	The attempt to contact Autodiscover using the HTTP Redirect method failed.
 	
	Additional Details
 	
Elapsed Time: 3217 ms.
 	
	Test Steps
 	
	Attempting to resolve the host name autodiscover.xxxxx.xxxxx.xx in DNS.
 	The host name resolved successfully.
 	
	Additional Details
 	
IP addresses returned: 188.xxxxxxxxxxxxxxxxxxx
Elapsed Time: 2615 ms.
	Testing TCP port 80 on host autodiscover.xxxxx.xxxxx.xx to ensure it's listening and open.
 	The port was opened successfully.
 	
	Additional Details
 	
Elapsed Time: 219 ms.
	The Microsoft Connectivity Analyzer is checking the host autodiscover.xxxxx.xxxxx.xx for an HTTP redirect to the Autodiscover service.
 	The Microsoft Connectivity Analyzer failed to get an HTTP redirect response for Autodiscover.
 	
	Additional Details
 	
An HTTP 401 Unauthorized response was received from the remote Unknown server. This is usually the result of an incorrect username or password. If you are attempting to log onto an Office 365 service, ensure you are using your full User Principal Name (UPN).
HTTP Response Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Tue, 21 Aug 2018 13:23:28 GMT
Server: nginx
WWW-Authenticate: Basic realm="autodiscover.xxxxx.xxxxx.xx"
Elapsed Time: 382 ms.
	Attempting to contact the Autodiscover service using the DNS SRV redirect method.
 	The Microsoft Connectivity Analyzer failed to contact the Autodiscover service using the DNS SRV redirect method.
 	
	Additional Details
 	
Elapsed Time: 875 ms.
 	
	Test Steps
 	
	Attempting to locate SRV record _autodiscover._tcp.xxxxx.xxxxx.xx in DNS.
 	The Autodiscover SRV record was successfully retrieved from DNS.
 	
	Additional Details
 	
The Service Location (SRV) record lookup returned host mail.xxxxx.xxxxx.xx.
Elapsed Time: 243 ms.
	Attempting to test potential Autodiscover URL https://mail.xxxxx.xxxxx.xx:443/Autodiscover/Autodiscover.xml
 	Testing of this potential Autodiscover URL failed.
 	
	Additional Details
 	
Elapsed Time: 632 ms.
 	
	Test Steps
 	
	Attempting to resolve the host name mail.xxxxx.xxxxx.xx in DNS.
 	The host name resolved successfully.
 	
	Additional Details
 	
IP addresses returned: 188.xxxxxxxxxxxxxxxxxx
Elapsed Time: 13 ms.
	Testing TCP port 443 on host mail.xxxxx.xxxxx.xx to ensure it's listening and open.
 	The port was opened successfully.
 	
	Additional Details
 	
Elapsed Time: 206 ms.
	Testing the SSL certificate to make sure it's valid.
 	The SSL certificate failed one or more certificate validation checks.
 	
	Additional Details
 	
Elapsed Time: 412 ms.
 	
	Test Steps
 	
	The Microsoft Connectivity Analyzer is attempting to obtain the SSL certificate from remote server mail.xxxxx.xxxxx.xx on port 443.
 	The Microsoft Connectivity Analyzer wasn't able to obtain the remote SSL certificate.
 	
	Additional Details
 	
The certificate couldn't be validated because SSL negotiation wasn't successful. This could have occurred as a result of a network error or because of a problem with the certificate installation.
Elapsed Time: 382 ms.

egal ob ich die option:

Microsoft Exchange
ActiveSync Connectivity Tests
Exchange ActiveSync
oder
Exchange ActiveSync Autodiscover
oder 
Microsoft Exchange Web Services Connectivity Tests
Synchronization, Notification, Availability, and Automatic Replies

Ich hab also irgend ein kruks in meiner dns config.

**Comment by mkuron** [comment]
Kannst du 
https://xxxxx.xxxxx.xx/Autodiscover/Autodiscover.xml im Webbrowser aufrufen? Wenn nicht, welche Fehlermeldung kommt?

**Comment by Conan179** [comment]
Doch kann ich, ich soll benutzer name und PAsswort eingeben.
und bekomme das:
This XML file does not appear to have any style information associated with it. The document tree is shown below.

 `<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
<Response>
<Error Time="18:33:290.537011" Id="2477xxxxxx">
<ErrorCode>600</ErrorCode>
<Message>Invalid Request</Message>
<DebugData/>
</Error>
</Response>
</Autodiscover>`

**Comment by mkuron** [comment]
Hmm, dann stimmem DNS und Zertifikat aber. Ich schau mal, ob ich es reproduzieren kann.

**Comment by AikoAppeldorn** [comment]
Welches Betriebsystem benutzt du?

Ich hatte am Wochenende das Problem, das Windows 7 + Outlook 16 genau diesen Fehler auch hatte:
`The certificate couldn't be validated because SSL negotiation wasn't successful.`

Problem war das Windows 7 kein TLS 1.2 kann und nur TLS 1.2 von nginx erlaubt wird.
https://blogs.technet.microsoft.com/schrimsher/2016/07/08/enabling-tls-1-1-and-1-2-in-outlook-on-windows-7/

Folgende Stelle in Nginx ist das Problem:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/nginx/site.conf#L26

Ich kann leider nicht genau sagen, ob die Chiper auch Probleme machen. 
Das müsste ich noch testen.

**Comment by Conan179** [comment]
Windows x64 1803
Das doofe ist ja, das nur das programm "em client" probleme macht, Outlook 2016, Windows Mail und Kalender intern selbst bei Android klappt es, per exchange  sich zu verbinden.

Der Support schiebt die schult auf die DNS einträge:
Hello Conan,

Thank you for the results. Unfortunately it seems that your server's autodiscover is not working properly which may cause issues especially during the setup as autodiscover sends recommended settings to the application which requested access to your account.
Here is what test returned: 
Attempting each method of contacting the Autodiscover service.
The Autodiscover service couldn't be contacted successfully by any method.

Can you please review autodiscover settings and adjust them so correct configuration for your account is supplied to eM Client?

**Comment by mkuron** [comment]
Ich habe die aktuelle Version von eM Client getestet und die Konfiguration funktioniert exakt so wie wir es [dokumentiert](https://mailcow.github.io/mailcow-dockerized-docs/client/client-emclient/) haben. Kalender und Kontakte werden automatisch gefunden.

Ich kann dein Problem also nicht reproduzieren. Wenn du DNS und Zertifikat als Fehlerquellen ausgeschlossen hast und keine Änderungen an Mailcow vorgenommen hast, kann es nur noch an irgendwelchen Windows-Einstellungen liegen.

**Comment by Conan179** [comment]
Alter jetzt brat mir einer nen Storch, ungelogen, ich hab NICHTS verändert und plötzlich geht es.

**Comment by Adorfer** [comment]
Evtl. waren vorher alte/nicht abgelaufene DNS-Caches im Weg?

**Comment by Conan179** [comment]
Ich hab keinen Schimmer :( 
Bis vorhin ging es wirklich nicht.
