### ISSUE TITLE
update.sh does not allow X.Y domains

### ISSUE THREAD

**Issue by ishkanan** [mailcow/mailcow-dockerized#1698]
Hi team,

I run mailcow on a domain in the form X.Y and noticed that **update.sh** exits with "MAILCOW_HOSTNAME (X.Y) is not a valid FQDN!". Looks like it is expecting **MAILCOW_HOSTNAME** to contain two or more dots. I believe the script should be updated to allow X.Y domains, happy to submit a PR. Thoughts?

**Comment by mkuron** [comment]
You are right. Duplicate of #1572.
