### ISSUE TITLE
What happens when the ratelimit is exceeded ?

### ISSUE THREAD

**Issue by th3technician** [mailcow/mailcow-dockerized#1699]
Hi @andryyy, First Let's all take a moment and appreciate the beauty of the improvements made by him today ;) :1st_place_medal: 

I have 2 questions, First when the ratelimit of a domain or a mailbox user is exceeded what happens ? Does the system drops the messages or it queues it for later?

Second does the letsencrypt 100 domains limit still on ? They launched the wildcard certificates and i read that it should be better by now, if it needed working well with wildcards is that possible to do from mailcow ? 

Thanks in advance!

**Comment by andryyy** [comment]
Hey,

When a RL is exceeded, the milter returns a 4.x.x.

Yes, I think the LE 100 domain limitation is still a thing. We cannot do TXT validations as of today.

This is not planned at the moment. You can put a RP in front of mailcow to handle multiple keys with ease. :-) Or even put HAProxy in front of it and have it handle SMTP/IMAP (with Proxy Protocol).

**Comment by th3technician** [comment]
Oh, So by that the mail is dropped ?

It would be nice too if there was an input field for rate limit on "add domain" modal

**Comment by mkuron** [comment]
> So by that the mail is dropped ?

No, delivery will be retried later. Messages are never silently dropped.

>  Or even put HAProxy in front of it and have it handle SMTP/IMAP (with Proxy Protocol).

That requires some additional caution. The client IP address is not passed through by the proxy, so fail2ban won’t work anymore. If you proxy port 25, DNSBLs will be useless. But since we use only one `$MAILCOW_HOSTNAME` for all domains, you really only need to reverse proxy the web server for all the autodiscover domains.

**Comment by andryyy** [comment]
Yes, a HAProxy setup requires some more changes. It is not "supported", but I have those setups live and working. This is rarely asked for or even needed.

**Comment by andryyy** [comment]
I added the rate limit field now.

**Comment by th3technician** [comment]
Thanks a lot for the fast detailed reply. I just updated mailcow and tested the ratelimit field it said "ratelimit for object domain.com saved" but when i checked its still unlimited?

**Comment by th3technician** [comment]
I have these errors in mailcow container docker logs 
`unbound-mailcow_1    | [1534879009] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
`

`redis-mailcow_1      | 1:M 21 Aug 19:16:48.715 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
`

`[Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade`

**Comment by andryyy** [comment]
I fixed it now.

**Comment by th3technician** [comment]
Ratelimit on modal working :100: 

Thanks for all the help, I will donate more as i promised in the next few days once i get any bitcoin.

**Comment by andryyy** [comment]
The Unbound error is known and not important. Will be fixed in the future.

Redis explains itself. :-) Just set those values on your node (should be enough - but recreate the mailcow stack).

The "innodb_index_stats" error is something I have not seen, don't know. Try what it suggests:

```
source mailcow.conf
docker exec -it $(docker ps -qf name=mysql-mailcow) bash -c "mysql_upgrade -uroot -p${DBROOT}"
```

**Comment by th3technician** [comment]
Mysql error gone,  and the redis error i tried before a lot but didn't work for me so imma do more tests tonight

there is these too 
`# Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
`

`mysql-mailcow_1      | 2018-08-21 19:31:34 140246709282752 [Warning] InnoDB: Using innodb_file_format is deprecated and the parameter may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
`

`mysql-mailcow_1      | 2018-08-21 19:31:35 140246709282752 [Warning] proxies_priv entry @% root@a49d81fb27c4 ignored in --skip-name-resolve mode.
`

`clamd-mailcow_1      | LibClamAV Warning: **************************************************
clamd-mailcow_1      | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
clamd-mailcow_1      | LibClamAV Warning: ***   Please update it as soon as possible.    ***
clamd-mailcow_1      | LibClamAV Warning: **************************************************
`

`postfix-mailcow_1    | Aug 21 19:31:36 mx postfix/qmgr[360]: warning: bounce_queue_lifetime is larger than maximal_queue_lifetime - adjusting bounce_queue_lifetime
`

`dockerapi-mailcow_1  |    WARNING: Do not use the development server in a production environment.
`

**Comment by andryyy** [comment]
We use the API for very, very, very limited stuff, it is totally fine to use it as-is (dev mode) here. If it fails, it restarts. But I have never even seen it happening. PRs are welcome.

The Postfix var can be adjusted. I have seen it and ignored as it self-adjusts (I know...).

Just Google for the other warnings, it is mostly nothing important (Redis) or I know about it (deprecated file format). The file format is something I still set for setups with older SQLs. 

ClamAV auto-updates.
