### ISSUE TITLE
Autodiscover + reverse proxy forwards internal address instead of hostname

### ISSUE THREAD

**Issue by lug-gh** [mailcow/mailcow-dockerized#1700]
Hi,

I'm using mailcow dockerized behind reverse proxy like the manual shows here: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ (nginx)

But when I add an account to my outlook, it connects to the internal IP of the mailserver.
Why is that?

```
C:\Users\lug>nslookup
Standardserver:  dns.example.local
Address:  10.10.10.111

> mail.example.org
Server:  dns.example.local
Address:  10.10.10.111

Nicht autorisierende Antwort:
Name:    node.example.org
Address:  193.30.xxx.xxx
Aliases:  mail.example.org
```

nginx:
```
server {
        listen 443;
        ssl on;
        ssl_certificate         /etc/letsencrypt/live/example.org/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/example.org/privkey.pem;
        server_name             mail.example.org
                                autodiscover.example.org
                                autoconfig.example.org;

        location / {
                proxy_pass https://10.10.10.102/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                client_max_body_size 100m;
        }
}
```

dns:
```
node.example.org.	86400	IN	A	193.30.xxx.xxx
mail.example.org.	120	IN	CNAME	node.example.org.
autodiscover.example.org.	86400	IN	CNAME	mail.example.org.
autoconfig.example.org.	86400	IN	CNAME	mail.example.org.
_autodiscover._tcp.autodiscover.example.org.	120	IN	SRV	1			1	443	mail.example.org.
```

![image](https://user-images.githubusercontent.com/24546639/44421004-ba4f7800-a57f-11e8-910d-c7a2b82d22e2.png)

I hope somebody knows what's going on there.

**Comment by lug-gh** [comment]
Even if I agree in outlook, I get an error that it didn't work.

![image](https://user-images.githubusercontent.com/24546639/44421290-66915e80-a580-11e8-907e-dc0916173179.png)

**Comment by cklabautermann** [comment]
Sorry, I´m not an expert at nginx, but at least the description for apache2.4 works for me.
Maybe it could be an option to tryout apache?

**Comment by andryyy** [comment]
I don't think this matters at all, but your SRV record is incorrect:

_autodiscover._tcp.autodiscover.example.org.	120	IN	SRV	1			1	443	mail.example.org.

I think it will fall back to A/AAAA anyways.

**Comment by lug-gh** [comment]
What exactly is wrong about it?

**Comment by andryyy** [comment]
_autodiscover._tcp.example.org. 120 IN SRV 1 1 443 mail.example.org. :-)

**Comment by lug-gh** [comment]
Thanks for pointing that out!

But unfortunately, it still provides the servers internal IP as autodiscover.

Do I have to add ALL of these, to make it work? https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/#the-advanced-dns-configuration

Also @cklabautermann, testing apache would be little difficult, because there are like 15 websites on that reverse proxy, which I'd have to temporarily disable, because I've got only one public IP and nginx already uses 443.

**Comment by lug-gh** [comment]
Well, I decided to put a clone of my mailcow vm on another host, where I have another external IP.
(to test apache)

![image](https://user-images.githubusercontent.com/24546639/44481555-68255a00-a646-11e8-8d63-0e890b590ea4.png)

At least it's now showing mail.example.org instead of the internal IP, but if i click "zulassen" (accept), it still fails.. Outlook doesn't even ask for authentication.

**Comment by lug-gh** [comment]
I decided to try this: https://www.codetwo.com/admins-blog/how-to-quickly-verify-if-autodiscover-is-working/

![image](https://user-images.githubusercontent.com/24546639/44482196-02d26880-a648-11e8-8265-f97e7c45448e.png)

After clicking allow the output is this:
![image](https://user-images.githubusercontent.com/24546639/44482302-38775180-a648-11e8-8b76-309837c3da1b.png)

censored= example.org

Every try of outlook to get the config is 301?

**Comment by lug-gh** [comment]
I decided to try this: https://www.codetwo.com/admins-blog/how-to-quickly-verify-if-autodiscover-is-working/

![image](https://user-images.githubusercontent.com/24546639/44482196-02d26880-a648-11e8-8265-f97e7c45448e.png)

After clicking allow the output is this:
![image](https://user-images.githubusercontent.com/24546639/44482302-38775180-a648-11e8-8b76-309837c3da1b.png)

censored= example.org

Every try of outlook to get the config is 301?

nginx:
![image](https://user-images.githubusercontent.com/24546639/44482526-ed117300-a648-11e8-9619-48c20440ad9a.png)

apache:
![image](https://user-images.githubusercontent.com/24546639/44482722-71fc8c80-a649-11e8-8154-78eb80ebd346.png)

**Comment by lug-gh** [comment]
Nginx seems to do a better job here,

tested same on real exchange: 
![image](https://user-images.githubusercontent.com/24546639/44520812-4a510700-a6d1-11e8-8016-ed448101f815.png)

**Comment by lug-gh** [comment]
I tried it again now, after changing exactly nothing. It works.

**Comment by lug-gh** [comment]
Ok, I can connect my Outlook to mailcow via EAS, but it stopped working after loading some mails.
I've checked the acces log and found 
```
87.128.x.x - mail@example.org [23/Oct/2018:13:05:13 +0200] "POST /Microsoft-Server-ActiveSync?Cmd=Sync&User=mail@example.org&DeviceId=B702659BD26142B692XXXXXXXX&DeviceType=WindowsOutlook15 HTTP/1.1" 504 192 "-" "Outlook/16.0 (16.0.4678.1000; MSI; x86)"
```
So I were curious and opened the URL in chrome, authenticated and got ERR_TOO_MANY_REDIRECTS
```
https://mail.example.org/SOGo/Microsoft-Server-ActiveSync/view/view/view/view/view/view/view/view/view/view/view/view/view/view/view/view/view/view/view?Cmd=Sync&DeviceId=B702659BD26142B6XXXXXXXXX&User=mail@example.org&DeviceType=WindowsOutlook15
```

I think this might be in correlation with autoconfig not working.
I can configure the account manually, but autoconfig still does not work.

**Comment by andryyy** [comment]
It does take a while to synchronize. Do _not_ hammer the "synchronize now" button. It will load a bunch of mails, wait a few seconds, load another bunch etc. 

Autoconfig is not relevant for EAS. Autodiscover isn't too, it is just the initial configuration push.

You cannot call a EAS URL in Chrome. Same with autodiscover, it will print that warning, that you cannot run GET on this document.

I think your reverse proxy is not correctly configured. But that's probably not true, because EAS pushed a few mails. Nginx' config would not suddently break while syncing. :-)

I recommend to delete the SOGo and Outlook profile and try again. Are your "too many redirect" errors fixed?

**Comment by lug-gh** [comment]
I know it can take a while, I waited like 3 hours, it was not possible to get any mail loaded.
I'll let autoconfig by side, and try to fix EAS first.
I delete the account in outlook and added it again, now the newest email in the inbox loaded too, but the mails from some folders don't.
I wait again then and will see if that helped. But how do i delete a sogo profile?

Btw this is my reverse proxy conf:
```
server {
        listen 443;
        ssl on;
        ssl_certificate         /etc/letsencrypt/live/example.org/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/example.org/privkey.pem;
        server_name             mail.example.org
                                autodiscover.example.org
                                autoconfig.example.org;

        access_log              /var/log/nginx/mail/access.log;
        error_log               /var/log/nginx/mail/error.log;

        location / {
                proxy_pass https://IP.OF.THE.MAILCOW:8443/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                client_max_body_size 100m;
        }
}
```

So, it happens already while i'm writing: Outlook has a yellow excelmation mark and when I open the outlook connection status it shows the connection to mail.example.org is closed.

This is how the log looks like if I start Outlook
```
nginx-mailcow_1      | *IP* - mail@example.org [23/Oct/2018:13:55:44 +0200] "OPTIONS /Microsoft-Server-ActiveSync HTTP/1.0" 200 0 "-" "Outlook/16.0 (16.0.4678.1000; MSI; x86)"
nginx-mailcow_1      | *IP* - mail@example.org [23/Oct/2018:13:55:44 +0200] "POST /Microsoft-Server-ActiveSync?Cmd=FolderSync&User=mail@example.org&DeviceId=xxxxxxxxx&DeviceType=WindowsOutlook15 HTTP/1.0" 200 50 "-" "Outlook/16.0 (16.0.4678.1000; MSI; x86)"
nginx-mailcow_1      | *IP* - mail@example.org [23/Oct/2018:13:56:44 +0200] "POST /Microsoft-Server-ActiveSync?Cmd=Sync&User=mail@example.org&DeviceId=xxxxxxxxx&DeviceType=WindowsOutlook15 HTTP/1.0" 499 0 "-" "Outlook/16.0 (16.0.4678.1000; MSI; x86)"
```

So it looks like Outlook want's an answers, does'nt get it in time and cancels the operation.
I added the account like 13:55 and the last time it was synchronized is 13:57.. (now it's 30 mins later, still no synchronization)
When I restart outlook it says 'waitung for server response' for like 1-2 mins and then again no synchronization happened.

And thats really strange, because the initial synchronization works just fine when adding a new account to outlook.

**Comment by lug-gh** [comment]
I now noticed why autoconfig didn't work.
I thought I've set it to EAS, but it was set to IMAP and SMTP, where the SMTP Port was set to 465, which I didn't make public accessible... Changed it all to EAS now.

So, I don't know if it's smart too keep posting here, since my problem is completely different now. New Problem is: "Outlook stop synchronizing after initial setup"
