### ISSUE TITLE
Keep persistent data but remove all images and pull new

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1701]
Hi,

i faced a problem right now:
/usr/local/bin/docker-compose was filled with "not found" ...
Mailcow wants to create all images locally.

How can i keep my persistent data an remove all images?

Thanks for every help

**Comment by tkorves** [comment]
Hi @ywolynsky,

I'd like to point you to our support @ mailcow.email
All the best, Tim

**Comment by mkuron** [comment]
You can try to `docker-compose pull` them again if they were not found. If that fails again, you might have a network issue.

It shouldn't be necessary to remove the images manually, but you can do it via `docker system prune -a`.

**Comment by ghost** [comment]
Thanks
When i do curl -Ls https://www.servercow.de/docker-compose/latest.php
i get 22.0.1
Is this correct?

**Comment by andryyy** [comment]
No

**Comment by ghost** [comment]
I wonder why curl shows this ...
Do you have a clue or a hint?
