### ISSUE TITLE
Admin GUI - Adding multiple domain aliases coma-separated

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#1705]
Hi,

Just wanted to let you know that in the GUI, when you add domain aliases, it's says you can add multiple aliases in one shot, separating domain aliases by a coma.

Actually it only adds the last entry.

I tried it with latest version,pulled yesterday.

Cheers,
Sébastien

**Comment by andryyy** [comment]
Thank you, fixed it. :-)

**Comment by sriccio** [comment]
Hi @andryyy,

Thanks a lot. I can confirm it's now working :)

Kind regards
