### ISSUE TITLE
sieve does not work?

### ISSUE THREAD

**Issue by bodsch** [mailcow/mailcow-dockerized#1707]
I use kmail as MTA and the integrated sieve editor.
I was able to import my old sieve scripts without errors. However, these are not used. 
Do I need to activate it somewhere else?
Or does the filter of emails only work with the enclosed SOGo?

**Comment by bodsch** [comment]
Sorry, Layer8 Problem.
I fixed this.

**Comment by Phil12n** [comment]
Hi,

How did you fixed the problem ?
I'd like to import sieve filters in SOGO/Mailcow...

Thanks

**Comment by bodsch** [comment]
> Hi,
> 
> How did you fixed the problem ? I'd like to import sieve filters in SOGO/Mailcow...

That was almost 4 years ago!
Sorry, but my memory is not that good anymore. ;)

**Comment by Phil12n** [comment]
...I retyped all the filters...
Thanks ;-)
