### ISSUE TITLE
How much RAM is needed?

### ISSUE THREAD

**Issue by hansapils** [mailcow/mailcow-dockerized#1708]
Hi guys,

I am retiring my old email-Server (iredmail) and I am planing a new one (mailcow, of course). How much RAM is needed or recommended? I can choose between 2 or 4 GB. The server is going to be used by four users.

Regards,
hansapils

**Comment by MAGICCC** [comment]
1.5GB is the minimum so choose 2GB. 4GB is a bonus when you can afford it

**Comment by mkuron** [comment]
2GB is sufficient, but make sure to configure a few gigabytes of swap space so you don't get out-of-memory terminations when something temporarily takes a bit more than it should.
