### ISSUE TITLE
Quota difference between SOGo and mailcow

### ISSUE THREAD

**Issue by th3technician** [mailcow/mailcow-dockerized#1709]
SOGo and mailcow shows totally different quota values as in these pictures.

SOGo :
https://image.ibb.co/nwCrHp/Capture.jpg

Mailcow :
https://image.ibb.co/iSP5cp/Capture2.jpg

And what is that number in tab "Message #" is that the total of sent messages or received ? both ? or current amount of messages in inbox or all folders?

**Comment by tkorves** [comment]
No, there's no difference. 5GB are 5120MB. 1GB is 1024MB. 5*1024=5120.

Message # is the total amount of messages in all folders of this account.
