### ISSUE TITLE
How can I use a remote (ssh/scp) destination for mailcow backup-script

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#1710]
Hi,

I use a real vServer with static public IP.
How can I use a remote destination for mailcow backup-script.

I'd like a better way - A direct way without copy to local and then scp to home.
This is my bash-script on my vServer ....
```
#!/bin/bash
#
REMOTE=master@111.111.111.111
DDIR=/volume1/homes/master/_BACKUP/Contabo-VPS/vpsm/mailcow/std

BACKUP_LOCATION=~/backup/mailcow/std /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all
scp -P 222 -r ~/backup/mailcow/std/* ${REMOTE}:${DDIR}
rm -R ~/backup/mailcow/std/*
```

jm3west

**Comment by andryyy** [comment]
Hi, you can create a mount with sshfs.

**Comment by jm3west** [comment]
Cool, hat geklappt, danke Dir André.


Cool, everything works, thank you André
