### ISSUE TITLE
Adding subdomain

### ISSUE THREAD

**Issue by botoxin** [mailcow/mailcow-dockerized#1711]
Recently I've installed older version of mailcow and i setup domain which is doing good (mydomain.com). Now what im trying to achieve is to make subdomain like subdomain.mydomain.com so emails sent from it would look like this admin@subdomain.mydomain.com.

My problem is I'm not sure which DNS records i should edit or add and where to point MX record from subdomain.mydomain.com. I have RDNS enabled for mydomain.com

**Comment by mkuron** [comment]
After you add the domain, you can click the blue "DNS" button to see what records you should add. It shows checkmarks and crosses to indicate what is already set correctly and what isn't.
