### ISSUE TITLE
Let's Encrypt for mailserver name.domain.tld

### ISSUE THREAD

**Issue by tobiasreinhard** [mailcow/mailcow-dockerized#1712]
Hello,
I have a small problem with my Mailcow installation.
I defined the subdomain eltanin.domain.tld for the mail server.
However, I will not receive a certificate for this domain.

My logfile:
`acme-mailcow_1 | Sat Aug 25 18:13:22 CEST 2018 - Found AAAA record for eltanin.domain.tld: 2a01:XXX:XXX:XXX:XXX7::XXX - skipping A record check` 
` acme-mailcow_1 | Sat Aug 25 18:13:22 CEST 2018 - Cannot match your IP NO_IPV6_LINK against hostname eltanin.domain.tld (2a01:XXXX:XXXX:XXXX:0000:0000:0000:XXXX)` 
` acme-mailcow_1 | Sat Aug 25 18:13:22 CEST 2018 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.` 
` acme-mailcow_1 | Sat Aug 25 18:13:22 CEST 2018 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.` 

The shortened IPv6 address works, why not the other one?
How can i achieve to get a valid certificate?

**Comment by Yures** [comment]
There was already discussion of this problem. Check the network 
interface configuration file, for ipv6, the interface name should be 
the same as for ipv4.

**Comment by tobiasreinhard** [comment]
I use CentOS for my machine and the device name for both is "eth0".

`TYPE="Ethernet"`
`PROXY_METHOD="none"`
`BROWSER_ONLY="no"`
`BOOTPROTO="none"`
`DEFROUTE="yes"`
`IPV4_FAILURE_FATAL="no"`
`IPV6INIT="yes"`
`IPV6_AUTOCONF="no"`
`IPV6_DEFROUTE="yes"`
`IPV6_FAILURE_FATAL="no"`
`IPV6_ADDR_GEN_MODE="stable-privacy"`
`NAME="eth0"`
`UUID="XXXXXXXXXXXXXXXXXXXXXX"`
`DEVICE="eth0"`
`ONBOOT="yes"`
`IPADDR="XXX.XXX.XXX.XXX"`
`PREFIX="XX"`
`GATEWAY="XXX.XXX.XXX.XXX"`
`IPV6ADDR="XXXX:XXX:XX:XXXX::XXX/XX"`
`IPV6_DEFAULTGW="XXXX:XXX:XX:XXXX::XXX"`
`IPV6_PRIVACY="no"`
`ZONE=public`
