### ISSUE TITLE
Error adding sieve filter

### ISSUE THREAD

**Issue by donarfr** [mailcow/mailcow-dockerized#1714]
Hello,

I cannot add filters to mailcow. I get following error:

`MySQL Fehler: PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /web/inc/functions.mailbox.inc.php:143 Stack trace: #0 /web/inc/functions.mailbox.inc.php(143): PDOStatement->execute(Array) #1 /web/json_api.php(121): mailbox('add', 'filter', Array) #2 {main}`

My filter:
```
require "fileinto";
if address :is ["From", "To"] "debian-security-announce@lists.debian.org" {
   fileinto "INBOX.Debain";
}
```

I get the error with Firefox and Chrome. Mailcow is updated to the last available version.
A screenshot of the error and the logfile:

![error](https://user-images.githubusercontent.com/9257897/44629686-39afc380-a953-11e8-9973-bd94742227b9.PNG)
![log](https://user-images.githubusercontent.com/9257897/44629687-39afc380-a953-11e8-84dc-1486e543f22e.PNG)

Can anybody reproduce this?
DONARfr

**Comment by ntimo** [comment]
Hello,
maybe you should try to add these kinds of filters using SOGo, you can find the option when you go to settings --> mail --> filter

I hope this helps :)

**Comment by andryyy** [comment]
Thanks, fixed it!
