### ISSUE TITLE
Failed request in web-UI rspamd for rrd data

### ISSUE THREAD

**Issue by drosskopp** [mailcow/mailcow-dockerized#1716]
To avoid a failed request in WEB-UI of rspamd for rrd data, set:
```
count = 1
```
in data/conf/rspamd/local.d/rspamd.conf.local
This is discussed here https://github.com/rspamd/rspamd/issues/2405

**Comment by hunter-nl** [comment]
Did not solve it for me.

**Comment by drosskopp** [comment]
@hunter-nl 
Did you restart the rspamd container?
Should be something like this in your installation folder:
```
docker-compose restart rspamd-mailcow
```
For me this works.

**Comment by hunter-nl** [comment]
Yes, I restarted rspamd-mailcow. Also tried docker-compose down && docker-compose up -d

**Comment by drosskopp** [comment]
After some updates I have to change the value in data/conf/rspamd/override.d/worker-controller.inc too for it to work.
Did the change and "docker-compose restart rspamd-mailcow" after.
