### ISSUE TITLE
where to white/blacklist for all domains on a server?

### ISSUE THREAD

**Issue by cklabautermann** [mailcow/mailcow-dockerized#1717]
by editing the domain object I can add objects to whitelist or blacklist for individual domains.
However I´m hosting several mail domains on a mailcow system and would like to know where to change server-wide whitelist or blacklist settings. 

Is there a place in the web UI I didn´t explore yet? Or can it only be done via shell access?

Thanks,
Claudio

**Comment by Mr-Martinez** [comment]
Check out rspamd web interface's configurations settings `https://mail.yourdomain.com/rspamd/`

**Comment by cklabautermann** [comment]
Thank you @Mr-Martinez .
I will try the dmarc_whitelist.local and spf_dkim_whitelist.local maps.

**Comment by andryyy** [comment]
Another possibility is to use Rspamd settings maps via mailcow UI.

**Comment by cklabautermann** [comment]
Thanks, @andryyy ! This looks somewhat more complicated than the way @Mr-Martinez  described, however :-)
