### ISSUE TITLE
Dovecot Cipher Change breaks Outlook POP3s

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1718]
Hi,

i recognized that commit 5905a3919ce925993aa030684b293f708ce4b5a4 breaks the outlook POP3S integration. 

I´ve got the following in the Logs:

    dovecot: pop3-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=x.x.x.x lip=172.22.1.2, TLS handshaking: SSL_accept() failed: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher

After reverted that commit, it works again:

    dovecot: pop3-login: Login: user=<user@domain.de>, method=PLAIN, rip=x.x.x.x, lip=172.22.1.2, mpid=209, TLS, TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits)

Thanks,
Thomas

**Comment by andryyy** [comment]
Which client exactly? And which OS?

**Comment by SvenWen** [comment]
Hi,

I've got the same problem with a POP3 connector which is part of a commercial workflow management program (which in turn is based on the database program Filemaker).

Creating a file 'extra.conf' and reverting to the old ciphers solved the problem for me as well.

Might be, that the POP3 connector is not up to the latest standards anymore...

OS is Windows 10

**Comment by SDFka** [comment]
Hello! 
Tested, Windows Embedded POSReady 2009 (Windows XP SP3 with extended support till April 9, 2019) + outlook 2003 sp3 working only after reverting commit 5905a39
