### ISSUE TITLE
SOGo: External invites

### ISSUE THREAD

**Issue by Ashby666** [mailcow/mailcow-dockerized#1719]
Hey guys,

short question:

We have a ressource-group that we use as a shared calendar.
If there is a date the partner oder family member should be see too, we invite the calendar family@xyz.de. It works good so far.

Unfortunately this works only within the same domain "xyz.de".
Is there a way, that we can share the group/calendar with another domain? And is it possible to accept invites from another server; e.g. from the Exchange Server of our company?

Thanks in advance for a quick tip!

BG,
Ashby

**Comment by phillipplum** [comment]
Funny, we have also this question. We want to share a calendar for our conference room with a different company.

**Comment by Mr-Martinez** [comment]
> Is it possible to accept invites from another server; e.g. from the Exchange Server of our company?

Yes it is possible as an authenticated user. If you would like "read" access only rights of a calendar from another server, head over to the additional options of the calendar, and under links to this calendar, grab the link under Webdav ICS URL. On the other server with mailcow (or any other server) click on the plus sign on web calendar and paste your link.

If you want features added, best bet is to post to SOGo's bug tracking: [https://sogo.nu/bugs/login_page.php](https://sogo.nu/bugs/login_page.php)

**Comment by Ashby666** [comment]
Hi @Mr-Martinez,

Thank you for the answer! :-)
Unfortunately it doesn't work. 

On the company Terminal Server I added my shared calendar over .ics and authenticated successfully. I can read the dates (even when some were unable to load).
I see in the logs that the invite-message has arrived but doesn't get answerd and it doesn't display in the shared calendar.

BTW and maybe important: shared calendar is checked as "Always show as available".

BG,
Ashby
