### ISSUE TITLE
SoGo container not starting

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#1720]
Hi,
SoGo container is not starting anymore, tried one reboot and an update, with no success. This is the container log, anyone can help me please?

Thanks

sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[85]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[84]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[86]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[89]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[85]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[84]: (CRON) info (No MTA installed, discarding output)
sogo-mailcow_1       | Aug 28 09:16:01 0f1c91ba267d CRON[84]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[151]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[150]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[153]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[149]: pam_unix(cron:session): session opened for user root by (uid=0)
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[155]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[149]: pam_unix(cron:session): session closed for user root
sogo-mailcow_1       | Aug 28 09:17:01 0f1c91ba267d CRON[158]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | Aug 28 09:17:02 0f1c91ba267d CRON[151]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Aug 28 09:17:02 0f1c91ba267d CRON[150]: (CRON) info (No MTA installed, discarding output)
sogo-mailcow_1       | Aug 28 09:17:02 0f1c91ba267d CRON[150]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists
sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s
root@mail:~/mailcow-dockerized#

**Comment by andryyy** [comment]
Hi,

Try:

```
docker-compose stop sogo-mailcow
docker-compose rm sogo-mailcow # confirm the deletion
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DROP TRIGGER IF EXISTS sogo_update_password"
docker-compose pull sogo-mailcow
docker-compose up -d
```

Did you try to rebuild sogo-mailcow? For a logo for example. Could have messed up the script format.

**Comment by samuelebistoletti** [comment]
I tried to execute the commands you paste but I got ERROR 1045 (28000): Access denied for user '-p'@'localhost' (using password: NO) 
on docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DROP TRIGGER IF EXISTS sogo_update_password"

**Comment by andryyy** [comment]
`source mailcow.conf` :-)

**Comment by samuelebistoletti** [comment]
I got this ERROR 1360 (HY000) at line 1: Trigger does not exist
Also completing commands no way to start, same errors on logs.
I never rebuilt sogo-mailcow...

**Comment by andryyy** [comment]
So... when did this happen? I see no valid reason why this would happen on a default installation. Any changes made to mailcow? Did it crash?

**Comment by samuelebistoletti** [comment]
Maybe a power loss on the server, because of a storm last week the UPS collapsed and the server shutted down unexpectedly.

**Comment by samuelebistoletti** [comment]
Is there a way to restore it? I have automatic backups with your script in case

**Comment by andryyy** [comment]
I can check it. Can you mail me?

**Comment by samuelebistoletti** [comment]
Ok. I sent you an email to andre.peters at servercow.de

**Comment by andryyy** [comment]
We had to delete `sogo_update_password.TRN`.

**Comment by samuelebistoletti** [comment]
Thank you very much for the help!

**Comment by arusa** [comment]
> docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DROP TRIGGER IF EXISTS sogo_update_password"

That is how the MySQL command worked for me, but it didn't help with the error:

docker-compose exec mysql-mailcow /bin/bash
mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} -e "DROP TRIGGER IF EXISTS sogo_update_password.TRN"

**Comment by arusa** [comment]
I don't know why, but using SQL commands I couldn't see any triggers. But this solution solved my problem:

https://github.com/mailcow/mailcow-dockerized/issues/2117#issuecomment-454350093

```
docker-compose down
rm /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/mailcow/sogo_update_password.TRN
docker-compose up -d
```

**Comment by mrstux** [comment]
> I don't know why, but using SQL commands I couldn't see any triggers. But this solution solved my problem:
> 
> [#2117 (comment)](https://github.com/mailcow/mailcow-dockerized/issues/2117#issuecomment-454350093)
> 
> ```
> docker-compose down
> rm /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/mailcow/sogo_update_password.TRN
> docker-compose up -d
> ```

This worked for me too. I had a crash. Sogo wouldn't come back up. Logs made reference to "ERROR 1359 (HY000) at line 2: Trigger already exists"

Above worked perfectly.
