### ISSUE TITLE
nginx-mailcow - No matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by EnriqCG** [mailcow/mailcow-dockerized#1726]
When `docker-compose pull` is executed, all images are pulled correctly except for **nginx-mailcow** with the following errors.
```
ERROR: for nginx-mailcow  no matching manifest for unknown in the manifest list entries
ERROR: no matching manifest for unknown in the manifest list entries
```
And when pulling the image directly.
```
sudo docker pull nginx:mainline-alpine
mainline-alpine: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries
```

**Comment by Geitenijs** [comment]
Was about to report the same issue!

**Comment by EnriqCG** [comment]
We are not the only ones. This is not an issue with mailcow but with the nginx alpine image. See https://github.com/nginxinc/docker-nginx/issues/262.

**Comment by mkuron** [comment]
Duplicate of #1075. This is not caused by Mailcow and cannot be fixed by us. It's a well-known Docker Hub bug and will resolve itself in a few hours.
