### ISSUE TITLE
[SOGo] Forwarding: Max e-mail addresses

### ISSUE THREAD

**Issue by jooP0** [mailcow/mailcow-dockerized#1728]
Hi! I have set up a forwarding with 52 recipients in SOGo. This isn't working. Is there a limit?

**Comment by andryyy** [comment]
Hi, don't you want to use an alias? I guess there actually is a limit for actions in Dovecot for sieve rules.

**Comment by mritzmann** [comment]
> Is there a limit?

The limit seems to be 30.

https://github.com/mailcow/mailcow-dockerized/blob/775b69f63e2fe4b34463fb636f36e9f4353134a2/data/conf/dovecot/dovecot.conf#L281
