### ISSUE TITLE
ACME problem creating new certificate

### ISSUE THREAD

**Issue by scebll** [mailcow/mailcow-dockerized#1729]
Morning,

We just put another machine running with Mailcow (we have two in production now), and seems like for some reason this new one isn't receiving the certificate returning a 403 error from the acme-client.

Any thoughs?

The debug:

`acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
acme-client: acme-v01.api.letsencrypt.org: DNS: 104.80.230.191
acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:a1:29f::3a8e
acme-client: acme-v01.api.letsencrypt.org: DNS: 2a02:26f0:a1:28b::3a8e
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: ****
acme-client: /var/www/acme/JTfF0O9Ky0aMDTyTIcjlrxwsSZKg3saEDcdoqfTPrM4: created
acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/h6dpumc9UMB4-Wca-j9l8vU4z1awFcKRQWmM7EMHFAo/6902956907: challenge
acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/h6dpumc9UMB4-Wca-j9l8vU4z1awFcKRQWmM7EMHFAo/6902956907: status
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: certificate
acme-client: https://acme-v01.api.letsencrypt.org/acme/new-cert: bad HTTP: 403
acme-client: transfer buffer: type : urn:acme:error:unauthorized , detail : Error creating new cert :: authorizations for these names not found or expired: **** , status : 403 } (179 bytes)
acme-client: bad exit: netproc(169): 1`

I removed the domain for security, with those ****.

Thank you!

**Comment by andryyy** [comment]
Hi, could be a reverse proxy problem. Are you using a RP? Or a not yet fully propagated DNS record.

**Comment by scebll** [comment]
No, we're not using any proxy. The DNS is propagated.

**Comment by andryyy** [comment]
I’d need to see it. But enotime. :-(
