### ISSUE TITLE
[Enhancement] Favicon.png SOGo customization

### ISSUE THREAD

**Issue by Mr-Martinez** [mailcow/mailcow-dockerized#1732]
Hello,

I have worked on code that allows you to customize the favicon file of SOGo by replacing the png file located at data/Dockerfiles/sogo/

Two lines of code added. One png file added (I bought one that you may use or I can turn the original sogo favicon into a png).

You run the same kind of code as the [Change Logo](https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/#change-logo) to get the png file updated. So not much to add to the documentation at [mailcow.github.io](https://mailcow.github.io/mailcow-dockerized-docs/)

I would like to ask how do we contribute code to Mailcow Github?

I understand what I have worked on is not a lot, but it is my first time using GitHub and would like to learn to contribute something small before jumping into something tougher.

**Comment by mitchellurgero** [comment]
I think a pull request would do, BUT:

Wouldn't it be better to do this in the theme_[color].js file instead? which could read from a config.json file that has something like:

```json
{
    "favicon":"/SOGo/favicon.png"
}
```
Or something like that? Instead of replacing a file that is managed by git.

**Comment by Mr-Martinez** [comment]
Hi @mitchellurgero,

Thank you for your advice.
I will look into theme_[color].js file!

I'm not replacing any file added by git.

The favicon file would be added into data/Dockerfiles/sogo/ , and live next to sogo-full.svg

One line of code is in data/Dockerfiles/sogo/Dockerfile that declares the path of favicon.png into the webresource directory of sogo.

The other line of code is in data/conf/sogo/sogo.conf that uses the sogo parameter [SOGoFaviconRelativeURL](https://sogo.nu/files/docs/SOGoInstallationGuide.html#_web_interface_configuration) = "path/to/favicon"

> By default when this is unset, sogo defaults to its sogo.ico file under the web resource directory.
