### ISSUE TITLE
Backup MX not resending emails

### ISSUE THREAD

**Issue by HesselTjeerdsma** [mailcow/mailcow-dockerized#1734]
Hi,

I am using a second Mailcow instance as backup MX, when the secondary Mailcow detects that the primary instance is online again I get the following error (I changed the email address of the sender):

```
> 31/08/2018, 18:09:32 | warning | warning: open active D24218817F: No such file or directory
> -- | -- | --
> 31/08/2018, 18:09:32 | info | D24218817F: from=<sender@example.org>, size=2522, nrcpt=1 (queue active)
```
Could somebody help me fix this?
I have tried to reinstall mailcow, and I tried a different server.

**Comment by mitchellurgero** [comment]
According to a quick google it's possible there is filesystem corruption. a lot of people recommend rebooting and running fsck until it finds no more errors.

**Comment by HesselTjeerdsma** [comment]
Okay thanks, will do that. Closing the issue for now.
