### ISSUE TITLE
correct way to config rspamd

### ISSUE THREAD

**Issue by raako71** [mailcow/mailcow-dockerized#1735]
on the mail-cow web ui it shows "Rspamd settings map", what is the correct way to modify this (that will be persistent through updates? I want to change greylisting so new emails come through quicker - the docs only refer to the rspamd manual which isn't docker specific

**Comment by MaxXor** [comment]
Any update on this?

**Comment by andryyy** [comment]
There is a recently answered issue about disabling Greylisting: #413 

Settings maps just apply settings according to Rspamd: https://rspamd.com/doc/configuration/settings.html

I recommend to check one of the presets. :)
