### ISSUE TITLE
catch-all address / luser_relay

### ISSUE THREAD

**Issue by hamedty** [mailcow/mailcow-dockerized#1736]
Does anyone know how to set-up a catch-all address? So for all non-existing recipients, postfix forward the mail to a specific mailbox?

If I add `luser_relay` should I remove `local_recipient_maps` from `proxy_read_maps` in `main.cf`?

Thanks

**Comment by mkuron** [comment]
Create a regular mailbox with a single address in the web interface. Then go to add an alias and follow the instructions there (i.e., just add @example.com to make a catch-all alias for example.com).
