### ISSUE TITLE
Update displayed size of mailbox in mailcow UI

### ISSUE THREAD

**Issue by spaceman-zz** [mailcow/mailcow-dockerized#1739]
Hi, is it possible to update the used size of a mailbox?
I have migrated my vmail-maildir to mailcow and the new mails are not calculated for the quota. The mailcow UI still display only some MB used for that mailbox. Otherwise the mailbox works create. I can see all the mails and folders with my mail client.

**Comment by mkuron** [comment]
Duplicate of #1248 and #310.
