### ISSUE TITLE
How to configure multiple mailcow-dockerized instances for failover

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#174]
Hi there,

is it possible to set up mailcow-dockerized on multiple machines on different IPs/domains to use them for a failover-mechanism?

What would be the necessary steps to do this?

Basically you would need to sync the mails across all machines and let the MX priority index in the DNS zone handle the rest, right?

**Comment by zero-one-devteam** [comment]
I had a running setup some times ago (before the change to docker). For mySQL you'll need a mysql master-master setup. There is a plugin for dovecot to archive mail replication (you'll need "notify" and "replication") and you'll have to sync some files manually (e.g. DKIM signatures) (e.g. via script when there a changes). I changed the ports of postfix and dovecot and put an IMAP and SMTP nginx proxy before them. Setup in the dockerized version schould be possible as well, but for me it was too complex so I decided to go for a vserver of which I can make snapshots and backup mails and config via rsync each hour (together with a mysql dump).

**Comment by Braintelligence** [comment]
The vserver approach sounds good to me.
So basically you would have, for example, 2 vservers and make vserver nr. 2 lower priority in the MX DNS zone. Then if vserver 1 dies, vserver 2 does the failover and the MX record will follow the lower priority entry due to failure of the higher priority entry.

Is that basically the plan?

**Comment by zero-one-devteam** [comment]
In fact I had two mx records, both with prio 10. my two nodes were mx1.example.com and mx2.example.com, so I had mx1.example.com IN MX 10 and mx2.example.com IN MX 10. it does not matter, which node receives a mail as both are replicated constantly. 

For the clients I had the host mail.example.com. The nginx proxy listens on port 993/143 TLS and 587 (submission) and forwards to the local dovecot or postfix. 

To get failover for mail.example.com I used Amazon AWS route 53 which is able to switch the IP of a host automatically when the node isn't available on a defined port. Unfortunately not as cheap, but it was worth it. I never had any problems with dns caching or anything else and I saved time and money setting up an own failover solution for Mail and webclients.

**Comment by Braintelligence** [comment]
My go-to solution for virtual appliances is Proxmox. I need to find out how to do a live-replication there, didn't try it out yet.

**Comment by zero-one-devteam** [comment]
You do not need your provider to do a live replication, you can do it by yourself:

MySQL/mariaDB:
https://www.digitalocean.com/community/tutorials/how-to-set-up-mysql-master-master-replication
(It's not only applicable for digitalocean, but worls elsewhere)

Dovecot replication:
https://wiki.dovecot.org/Replication

No need for drbd or anything else. You only need two vservers there.

**Comment by Braintelligence** [comment]
Ah I see.
But maybe a whole vserver-replication would be even better, still. I know how to do this with Windows Server but didn't try it with Proxmox yet.

What about Postfix logs, Sogo calendar and contacts and stuff, is that replicated by those two as well?

**Comment by zero-one-devteam** [comment]
SOGo's contact and calendar yes it is in MySQL (and thus replicated via master master). Postfix logs no, as both nodes have the own postfix instance ...

**Comment by Braintelligence** [comment]
I see, so I would have to look at both (or whatever number I have) to find out about specific events. I think that is a caveat I can deal with 😸 .
Thank you a lot for these primers!
