### ISSUE TITLE
Mailcow not dockerized?

### ISSUE THREAD

**Issue by kingfisher77** [mailcow/mailcow-dockerized#1741]
Hi - we are asking ourself if it is worth to wait für a non dockerized version of Mailcow. We are still on an old version without docker and have integrated logwatch, mlmmj and other things. This would be a pain in the dockerized version. We saw statements a year ago about migration current mailcow back to a native version. What happend to this?

**Comment by andryyy** [comment]
There are no _active_ plans. There are a bunch of issues asking this with answers and explanations.

If there was more support, I would consider it. The big problem is time.

I am focusing on managed mailcows at the moment, all of them are dockerized. It would be horrible to go back to non-dockerized and support those 200 different setups.
