### ISSUE TITLE
External account mail sending from SOGo

### ISSUE THREAD

**Issue by EnriqCG** [mailcow/mailcow-dockerized#1742]
Hello, so SOGo has an amazing feature where you can add **IMAP Accounts** to check other inboxes. I was wondering if (like in Gmail) we could also set up SMTP for that account so we can send emails directly from SOGo. Thanks.

**Comment by andryyy** [comment]
Hi, no, would be a cool feature. You can open a feature request @ SOGos bug tracker. :-)
