### ISSUE TITLE
Is there an API

### ISSUE THREAD

**Issue by ClarLabs** [mailcow/mailcow-dockerized#1743]
Hello Mailcow

We have tested Mailcow for about a week, and this will be the first docker based service we intend to use as we plan to migrate everything eventually to docker :smile: 

One thing we really need before we can consider Mailcow is an HTTP API, I don't care if there is no documentation, as long as you can point to the code I might be able to follow it through and determine the routes, as we need to auto-provision domains and email addresses by our panel.

I will look forward to your reply

**Comment by mritzmann** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/1374#issuecomment-404868546

duplicate #1374
