### ISSUE TITLE
Corrupted image (?)

### ISSUE THREAD

**Issue by gajdi8** [mailcow/mailcow-dockerized#1744]
Hi, 

As of yesterday, our disk capacity reached 100% due to a caching error.
Since that, I can't make the nginx container to work, thus we have no mail server.
It spams the logs with these:
```
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/09/05 13:04:15 [emerg] 11#11: PEM_read_bio_X509_AUX("/etc/ssl/mail/cert.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
```
I've already tried updating, everything else works fine (sql, rspamd, clamd, phpfpm)

Any advice on how to proceed? Our non-docker nginx instance runs perfectly, reverse proxy should work as intended.

Thank You in advance,

**Comment by mkuron** [comment]
You could try deleting the CA, certificate and key from data/assets/ssl, then restart the acme-mailcow container so it generates a new certificate. The message suggests that the certificate is corrupted, but that would have affected postfix and dovecot too.

**Comment by gajdi8** [comment]
That's exactly what I did, and it solved it.
Keep up the awesome work :)
