### ISSUE TITLE
Mailbox and Nextcloud share the storage quota

### ISSUE THREAD

**Issue by dagors** [mailcow/mailcow-dockerized#1746]
When installing nextcloud with nextcloud.sh the quota allocated to each mailbox is shared / linked to the storage and quota of nextcloud.

If it is not linked or shared, is it possible to add this feature?

and

How login as admin user in nextcloud?

**Comment by mkuron** [comment]
nextcloud.sh is still somewhat experimental. It displayed rhe admin password when you ran it. The quotas are not shared and it is not possible to change that.

**Comment by mitchellurgero** [comment]
@mkuron - Though it's not possible to automatically sync the quotas it is possible to set the default quota for all users in nextcloud by logging in as admin, going to users and changing the user group quota default from whatever it is to something else.
