### ISSUE TITLE
502 Bad Gateway  / Connection Refused

### ISSUE THREAD

**Issue by Matt-nwt** [mailcow/mailcow-dockerized#1747]
Hi all,

Really hope you can help with this issue, i have been searching for some time for a fix but have not yet found a solution.

I am receiving 502 Bad Gateway error when trying to access the mailcow ui, sogo works fine and all mail is working as intended. I am not knowingly working behind a reverse proxy.

the nginx logs when I try to connect:

nginx-mailcow_1      | 2018/09/06 07:15:17 [error] 15#15: *543491 connect() failed (111: Connection refused) while connecting to upstream, client: 1.2.3.4, server: mx.domain.tld, request: "GET / HTTP/1.1", ucgi://[fd4d:6169:6c63:6f77::c]:9002", host: "mx.domain.tld"

/opt/mailcow-dockerized/mailcow.conf
# ------------------------------
# mailcow web ui configuration
# ------------------------------
# example.org is _not_ a valid hostname, use a fqdn here.
# Default admin user is "admin"
# Default password is "moohoo"
MAILCOW_HOSTNAME=mx.domain.tld

# ------------------------------
# SQL database configuration
# ------------------------------
DBNAME=mailcow
DBUSER=mailcow

# Please use long, random alphanumeric strings (A-Za-z0-9)
DBPASS=
DBROOT=

# ------------------------------
# HTTP/S Bindings
# ------------------------------

# You should use HTTPS, but in case of SSL offloaded reverse proxies:
HTTP_PORT=80
HTTP_BIND=0.0.0.0

HTTPS_PORT=443
HTTPS_BIND=0.0.0.0

# ------------------------------
# Other bindings
# ------------------------------
# You should leave that alone
# Format: 11.22.33.44:25 or 0.0.0.0:465 etc.
# Do _not_ use IP:PORT in HTTP(S)_BIND or HTTP(S)_PORT

SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
DOVEADM_PORT=127.0.0.1:19991
SQL_PORT=127.0.0.1:13306

# Your timezone
TZ=Europe/London

# Fixed project name
COMPOSE_PROJECT_NAME=mailcowdockerized

# Additional SAN for the certificate
ADDITIONAL_SAN=

# Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n
SKIP_LETS_ENCRYPT=n

# Skip IPv4 check in ACME container - y/n
SKIP_IP_CHECK=n

# Skip ClamAV (clamd-mailcow) anti-virus (Rspamd will auto-detect a missing ClamAV container) - y/n
SKIP_CLAMD=n

# Enable watchdog (watchdog-mailcow) to restart unhealthy containers (experimental)
USE_WATCHDOG=n
# Send notifications by mail (no DKIM signature, sent from watchdog@MAILCOW_HOSTNAME)
WATCHDOG_NOTIFY_EMAIL=admin@domain.tld

# Max log lines per service to keep in Redis logs
LOG_LINES=9999

# Internal IPv4 /24 subnet, format n.n.n. (expands to n.n.n.0/24)
IPV4_NETWORK=172.22.1

# Internal IPv6 subnet in fc00::/7
IPV6_NETWORK=fd4d:6169:6c63:6f77::/64

# Use this IP for outgoing connections (SNAT)' >> mailcow.conf
#SNAT_TO_SOURCE=" >> mailcow.conf

# Disable IPv6
# mailcow-network will still be created as IPv6 enabled, all containers will be created
# without IPv6 support.
# Use 1 for disabled, 0 for enabled
SYSCTL_IPV6_DISABLED=0

# Use this IPv6 for outgoing connections (SNAT)
#SNAT6_TO_SOURCE=
# Create or override API key for web UI
#API_KEY=
# Must be set for API_KEY to be active
#API_ALLOW_FROM=

Many thanks for any help given,

Matt

**Comment by andryyy** [comment]
Hi, you are not using IPv6, are you? Do you use a local firewall on this machine?
If you are not using IPv6, try this, please: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-disable_ipv6/

**Comment by Matt-nwt** [comment]
Many thanks anndryy,

No, we are not using IPv6. I have amended the setting as per the link and still have a 502 error.

I use UFW as a firewall - status is:
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
21/tcp                     ALLOW       Anywhere
25                         ALLOW       Anywhere
8                          DENY        Anywhere
80                         ALLOW       Anywhere
110                        ALLOW       Anywhere
143                        ALLOW       Anywhere
443                        ALLOW       Anywhere
465                        ALLOW       Anywhere
587                        ALLOW       Anywhere
993                        ALLOW       Anywhere
995                        ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
21/tcp (v6)                ALLOW       Anywhere (v6)
25 (v6)                    ALLOW       Anywhere (v6)
8 (v6)                     DENY        Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
110 (v6)                   ALLOW       Anywhere (v6)
143 (v6)                   ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
465 (v6)                   ALLOW       Anywhere (v6)
587 (v6)                   ALLOW       Anywhere (v6)
993 (v6)                   ALLOW       Anywhere (v6)
995 (v6)                   ALLOW       Anywhere (v6)

is the fix as simple as opening ports 9001 / 9002?

Many thanks

Matt

**Comment by andryyy** [comment]
UFW will mess with a lot of Docker rules. I am not sure how they both can work together. This is inter-bridge communication, the bridge names may change when you recreate containers. Docker should handle the tables itself. :-) Opening 9001/2 will not work, no.

**Comment by Matt-nwt** [comment]
I've tried testing with UFW disabled and the result is still the same. It is worth noting that at some point in the past this was working fine..

**Comment by andryyy** [comment]
It is not enough to just disable it. Docker needs to rebuild the rules.

We never changed any of this.

**Comment by Matt-nwt** [comment]
Would disabling UFW, then docker down, docker up achieve this andryyy?

**Comment by andryyy** [comment]
Try disabling it, docker-compose down, systemctl restart docker, docker-compose up -d :-)

**Comment by Matt-nwt** [comment]
Ok, no change but maybe onto something...

Docker failed to restart so I rebooted the server

(Failed to restart docker.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files)

In the startup logs I found the following:

nginx-mailcow_1      | 2018/09/06 10:34:30 [emerg] 10#10: host not found in upstream "rspamd" in /etc/nginx/conf.d/site.conf:91

Now if I am reading this write, it is saying its missing a host on line 91 (/opt/mailcow-dockerized/data/conf/nginx/site.conf)  which is the following section:

 location /rspamd/ {
    proxy_pass       http://rspamd:11334/;
    proxy_set_header Host      $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    expires $expires;

Does that give any clues?

**Comment by andryyy** [comment]
No, this is something else on your server. Do not change the mailcow config files, they are not causing this.

The containers fail to communicate with each other. It is a firewall issue. It seems like they can't even reach the internal Docker DNS.

The iptables/ip6tables are definitely not okay.

**Comment by Matt-nwt** [comment]
Thanks andryyy for all your help, I may end up rebuilding this server with a fresh install of mailcow!

The iptables list as follows:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.22.1.2           tcp dpt:submission
ACCEPT     tcp  --  anywhere             172.22.1.2           tcp dpt:urd
ACCEPT     tcp  --  anywhere             172.22.1.2           tcp dpt:smtp
ACCEPT     tcp  --  anywhere             172.22.1.4           tcp dpt:mysql
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:12345
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:sieve
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:pop3s
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:imaps
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:imap2
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:pop3
ACCEPT     tcp  --  anywhere             172.22.1.10          tcp dpt:https
ACCEPT     tcp  --  anywhere             172.22.1.10          tcp dpt:http

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

And ip6tables:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-ISOLATION  all      anywhere             anywhere
DOCKER     all      anywhere             anywhere
ACCEPT     all      anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all      anywhere             anywhere
ACCEPT     all      anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all      anywhere             anywhere

**Comment by olivermg** [comment]
Hi!

We're observing this issue in a very similar form as well (502 errors, but in our case when nginx is trying to access sogo). It only happens when nginx decides to use the IPv6 address of the sogo container, trying to connect to port 9192.

We've checked our firewall/ip6tables rules and they seem to be fine, allowing the traffic.

nginx' error messages look like this:
```
|nginx-mailcow_1      | 2018/09/07 08:18:17 [error] 19#19: *246047 connect() failed
(111: Connection refused) while connecting to upstream, client: ..., 
server: ..., request: "GET /SOGo.woa/WebServerResources/js/vendor/ckeditor/skins/minimalist/editor_gecko.css?t=I63C
HTTP/1.1", upstream: "http://[fd4d:6169:6c63:6f77::7]:9192/WebServerResources/js/vendor/ckeditor/skins/minimalist/editor_gecko.css?t=I63C", 
host: "...", referrer: "https://.../SOGo/so/.../Mail//UIxMailPopupView"
```

Our research regarding the issue suggests that the sogo service is only listening on IPv4 and not on IPv6 on port 9192. While pinging both IPv4 & IPv6 addresses is working fine, HTTP access via port 9192 only works on the IPv4 address:
```
# curl http://172.22.1.248:9192
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
...
```
```
# curl 'http://[fd4d:6169:6c63:6f77::7]:9192'
curl: (7) Failed to connect to fd4d:6169:6c63:6f77::7 port 9192: Connection refused
```

Netstat supports this impression:
```
# nsenter -t 21376 -n netstat -anp | grep LISTEN
tcp        0      0 0.0.0.0:20000           0.0.0.0:*               LISTEN      1264/sogod
tcp        0      0 127.0.0.11:39622        0.0.0.0:*               LISTEN      842/dockerd
tcp        0      0 0.0.0.0:9192            0.0.0.0:*               LISTEN      21376/python
```
No IPv6 ports (esp. 9192) open.

So I guess either the sogo service should listen on IPv6 or the DNS name "sogo" (via which nginx tries to reach the sogo service) should resolve to the IPv4 address only.

Any clues?

Thanks and best regards,
Oliver

**Comment by andryyy** [comment]
I changed it now. I declared /usr/lib/GNUstep/SOGo as volume and use volumes_from to access it from nginx-mailcow. Much easier and no shitty HTTP server via Python. :-) There is some other stuff I need to check before pushing the changes though.
