### ISSUE TITLE
mailcow-setup-relayhost equivalent for mailcow-dockerized?

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#175]
Hi André,

how would you recommend to configure mailcow-dockerized to do smtp-relay? in the regular mailcow version you have the script mailcow-setup-relayhost in the misc folder ..

what's best practice to do that in the dockerized version?

thanks and best regards:-)

**Comment by andryyy** [comment]
Hi,

Insert this to `data/conf/postfix/main.cf`. "relayhost" does already exist (empty), just change its value.
```
relayhost = [your-relayhost]:587
smtp_sasl_password_maps = hash:/opt/postfix/conf/smarthost_passwd
smtp_sasl_auth_enable = yes
```

Create the credentials file:
```
echo "your-relayhost username:password" > data/conf/postfix/smarthost_passwd
```

Run:
```
docker-compose exec postfix-mailcow postmap /opt/postfix/conf/smarthost_passwd
docker-compose exec postfix-mailcow chown postfix: /opt/postfix/conf/smarthost_passwd /opt/postfix/conf/smarthost_passwd.db
docker-compose exec postfix-mailcow chmod 600 /opt/postfix/conf/smarthost_passwd /opt/postfix/conf/smarthost_passwd.db
docker-compose exec postfix-mailcow postfix reload
```

**Comment by chaosbunker** [comment]
Thanks André! I ported the script you provided in mailcow 0.14 to mailcow-dockerized, based on your instructions here .. let me know if you are interested in adding it to mailcow-dockerized:-)

**Comment by andryyy** [comment]
Sure, can you upload it somewhere or create a PR for review?

**Comment by chaosbunker** [comment]
Created the PR ... git is still a bit foreign to me, so I hope the way I did everything is alright..
