### ISSUE TITLE
Watchdog restarting SOGo after update

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1750]
Hello,
I just updated my Mailcow to the latest changes here on Github. But now my SOGo container is always restarted by the watchdog service:

```
9.9.2018, 21:44:41 | SOGo | -2 | Health level: 60% (12/20)
```

Do you know why? And how can I fix this? The new SOGo version was build locally on my machine because the new image wasn't up at the time of running the update.sh

I also receive this email every few minutes from watchdog: 
Title: Watchdog: sogo-mailcow service hit the error rate limit
content: Service was restarted, please check your mailcow installation.

**Comment by andryyy** [comment]
Will fix it in a bit...
