### ISSUE TITLE
Mailcow UI don't work

### ISSUE THREAD

**Issue by CrafterGamer** [mailcow/mailcow-dockerized#1752]
German:
Hey hab da mal eine frage?
Ich habe im news gelesen das mailcow vorrübergened deaktiviert ist.
Wie kann ich mailcow aber benutzen?
Im interface wird
`<div class="overlay"></div>`
gesetzt

Englich:
Hey have there times a question?
I read in the news that mailcow is temporarily disabled.
But how can I use mailcow?
In the interface 
`<div class="overlay"></div>`
is set

Danke / Thanks

**Comment by andryyy** [comment]
mailcow ist nicht deaktiviert...

**Comment by andryyy** [comment]
mailcow is not disabled or deactivated. I don’t know what you mean. The overlay is part of the UI.

**Comment by ghost** [comment]
I got the same problem. It seems the official site also affected.

**Comment by ghost** [comment]
The symptoms are: (after a fresh installation)
1. The main page covered with weird white overlay thus login functionality not working at all.
2. In web browser console it complains about the non-existence of JQuery library.
3. Some of the tables are missing (mailcow.mailbox etc).
4. Visiting mail.example.com/SOGs gives 502 error.

**Comment by andryyy** [comment]
? mailcow.email is online.

**Comment by ghost** [comment]
@andryyy Would you please try to visit https://demo.mailcow.email/SOGo? For me it always return 502 error (both official demo site and my own deployment)

**Comment by andryyy** [comment]
It is not an official demo, it was provided by a user.

**Comment by ghost** [comment]
![screen shot 2018-09-10 at 22 06 00](https://user-images.githubusercontent.com/9502051/45302375-c064c300-b545-11e8-8b10-e872bea38b9d.png)
@andryyy

**Comment by andryyy** [comment]
It is not an official demo, it was provided by a user.

I will check it in a clean environment, Could be something only new installations are affected by.

**Comment by ghost** [comment]
@andryyy Before that demo site works without problem. I followed the document to perform the fresh installation and always get the same result

**Comment by andryyy** [comment]
You don't need to mention me in every post. ;-)

I told you I will check it.

**Comment by andryyy** [comment]
Found the error....

``` 
    [message:protected] => SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mailcow.logs' doesn't exist
```

Will fix it asap.

**Comment by ghost** [comment]
Oh sorry for that :)
![screen shot 2018-09-10 at 22 11 12](https://user-images.githubusercontent.com/9502051/45302732-ab3c6400-b546-11e8-8f51-0f73ec233391.png)
I attempted to login into admin by using tab and enter but no lucks...

**Comment by andryyy** [comment]
Meh, I wanted to set a foreign key with a reference to a table that was not yet existing... I'm stupid. It is fixed now.

**Comment by ghost** [comment]
Thanks andryyy! This really solves all the issues here!

**Comment by Afondevi** [comment]
Hello @andryyy, same probléme here, White screen and SOGo no working..

**Comment by andryyy** [comment]
Updated many mailcows. No problem anywhere. :-/

**Comment by Afondevi** [comment]
Div with class overlay... and mail client have white screen.. i’m on master last version
