### ISSUE TITLE
[admin.php] When domain list is empty specifying a domain administrator gives wrong error message

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1753]
![screen shot 2018-09-10 at 22 33 34](https://user-images.githubusercontent.com/9502051/45304084-e55b3500-b549-11e8-8682-fbe7b0a8cf17.png)
Should be something like "No domain defined yet.."

**Comment by andryyy** [comment]
The field should be required too. Thanks, will fix it.
