### ISSUE TITLE
[mailbox.php] "Add Mailbox" allows malformed email name

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1754]
![screen shot 2018-09-10 at 23 43 43](https://user-images.githubusercontent.com/9502051/45308164-6834bd80-b553-11e8-8611-1b255723f4fa.png)

**Comment by andryyy** [comment]
Did you check the rfc? Is it actually malformed?

**Comment by ghost** [comment]
Oh sorry my mistake let's close this issue now 😅
