### ISSUE TITLE
[QUESTION] How to send an encrypted email?

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1757]
I tried to check encryption option but I got "cannot send email without recipient's certificate"

**Comment by mkuron** [comment]
Which encryption checkbox? Mailcow only has that force TLS option, which is not recommended to use as it is not supported by some mail servers.

If you are talking about PGP or S/MIME, that is the client application's responsibiliy. Mailcow has no and does not need explicit support for it.

**Comment by chilly2go** [comment]
So you are using multiple clients for a mailbox (your phone / SOGo  / thunderbird / ...)
It is quite hard to make the same certs / keys available to all possible clients for the same mailbox.
So just saying that the client application is responsible is an easy way out but I think there might be something better.
Considering that a lot of users are overhelmed with the options and possibilities I'd like to suggest thinking about a server side solution.
It looks like [Mail Crypt](https://wiki.dovecot.org/Plugins/MailCrypt) for example would solve the problem but I was told that there were technical problems using it (I don't know the details).

Update: I was misinformed about MailCrypt which only encrypts the mail directory.

I know that using keys requires that you would have to store them somewhere off-site (at least the private key) to have a system properly secure. (or let the user specifiy a password for the priv-key to decrypt and use it)
