### ISSUE TITLE
Sogo calendar email notification

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#1758]
Hi,

I´m not sure if the issue is already reported or if it is a sogo bug, but I recently have the following problem:

If I go to the settings of a calendar and enable "sent email if I change my calendar" and enter an email address, these settings are changed and saved for the session. If I log out and log in again only the enabled setting is shown, bute the entered email adress is NOT shown (screenshot). There also is NO email sent (even in the logs), if I make an entry or change an entry in that specific calendar.

BR
Mario

![unbenannt](https://user-images.githubusercontent.com/11010788/45343437-34808480-b5a1-11e8-98ea-37a61c64a474.PNG)

**Comment by paescuj** [comment]
This has been fixed recently: https://github.com/inverse-inc/sogo/commit/10485f8943581b8ac9f7df57e2f3954429babf87
