### ISSUE TITLE
mailcow in lxd container - netfilter container failing to start

### ISSUE THREAD

**Issue by laymonk** [mailcow/mailcow-dockerized#1761]
Hi,

I have been tangling with a puzzling situation here .. 

Repeated attempts to install mailcow yields the same result - netfilter containers fail to start:

```
Creating mailcowdockerized_netfilter-mailcow_1 ... error

ERROR: for mailcowdockerized_netfilter-mailcow_1  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/Creating mailcowdockerized_nginx-mailcow_1     ... done
wn

ERROR: for netfilter-mailcow  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/1d98d97ce09cfe9cf8b64967771b63e89926d84b26d1ae8424cb3b7031ee3f1c/devices.allow: operation not permitted\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

I have enabled requisite lxd privileges
```
lxc config set mailct security.nesting true
lxc config set mailct security.privileged true
```

### The Catch-22

* If I use lxc.raw to set the following:

```
raw.lxc: |-
    lxc.apparmor.profile = unconfined
    lxc.cgroup.devices.allow = a
    lxc.mount.auto = proc:rw sys:rw cgroup:rw
    lxc.cap.drop = mac_override sys_time sys_module sys_rawio
   # also tried with  lxc.cap.drop =
``` 
* Then I am not even able to install docker successfully (both the official docker repo and the ubuntu repo) .. 
* Docker installs fail because after install, docker is unable to start .. fails with error suggesting it is restarting too fast.

* I have been through so many iterations of this, and it fails consistently.

### Questions
* So, what are the consequences of running without the netfilter container?  ie, can I safely disable it?
* Is there any other known work-around for using netfilter with mailcow /

**Comment by laymonk** [comment]
Possibly as a consequence of netfilter container failing, `docker-compose ps` shows php-fpm in steady 'Restarting' state.

I have, as a last resort, commented out the whole of netfilter in docker-compose.yml, and all containers seemingly start up OK.  But `docker-compose ps` now shows both php-fpm and nginx containers as constantly 'Restarting' (probably due to the absence of the netfilter container) .. and the system is not usable.

**Comment by laymonk** [comment]
Forgot to add:

Host is ubuntu 18.04 .. and so is the lxd container

**Comment by mkuron** [comment]
LXD is a bit different from regular Docker. Similar errors have been reported in the past. If you disable the netfilter container, you’ll lose the fail2ban and SNAT functionality. If you figure out how to make it work, feel free to submit it pull request.

**Comment by laymonk** [comment]
I actually run mailcow already in an LXD container in ubuntu 16.04, and will test deploying within an ubuntu 16.04 container.  

However, I find your arrogant attitude about this issue surprising, needlessly dismissive and unhelpful.   For instance:
* If there are other reports, then at a minimum link one or more of them here.  That is the underlying principle of what makes github a great platform.
* What's with the rush to close this in particular?  Are you living for statistics on how quickly issues are closed?  Is that how the 'team' is now assessed? 
* LXD is an important platform in the ecosystem, and represent a great middle ground between virtualization and bare-metal servers.  Acting like you don't give a toss about supporting makes me start looking at other platforms.

**Comment by laymonk** [comment]
I have followed this issue up, and worked through the problems I had with docker and lxd .. 

For the records, the following settings for the container ensure running privileged docker containers will always work, and mailcow should work fine.

```
#in container's lxd profile .. can even be tightened and still work
linux.kernel_modules: aufs,nf_nat,xt_conntrack
raw.lxc: |-
    lxc.apparmor.profile = unconfined
    lxc.cgroup.devices.allow = a
    lxc.mount.auto = proc:rw sys:rw cgroup:rw
    lxc.cap.drop = mac_override sys_time sys_module sys_rawio
```

* Mailcow-netfilter still fails, and unfortunately fails without throwing any errors that will help in diagnosing it properly ..  Error message is below.
* Also, while trying to bring up the mailcow containers, it thrashes the underlying interfaces for the container, destroying docker0 and creating a whole bunch of veth devices 
```
ERROR: for mailcowdockerized_netfilter-mailcow_1  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "operation not permitted": unknown

ERROR: for netfilter-mailcow  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "operation not permitted": unknown
ERROR: Encountered errors while bringing up the project.
```

After trying to research this in-depth, I am convinced that the cause for this is `network_mode: host` setting .. and you should consider a different way of supplying the IP address or interface to this container.

**Some  Refs:**
* [1](https://github.com/docker/compose/issues/3442)
* [2](http://www.dasblinkenlichten.com/docker-networking-101-host-mode/)

If I knew enough about how this is intended to work (ie, which interface you want to attach netfilter to: 172.17.0.1/16 or 172.22.1.0/24), then I could have a go at seeking a network_mode setting that will work in lxd.  But I don't have the details and you have prematurely marked this issue as resolved. 

I love lxd and it fits great into my needs, and I will not stop using it because I want to use mailcow.  So, leaves me no choice but to look elsewhere.

**Comment by mkuron** [comment]
`network_mode: host` is necessary for the netfilter container because it dynamically creates firewall rules for fail2ban functionality. For the same reason, this container needs to be privileged.

If you want to use LXD, you might have to live without this security feature. This is not a Mailcow-specific problem; I guess any solition that creates firewall rules would run into it.

**Comment by kyleodonnell** [comment]
Anyone sort this out yet?  Running into this problem myself.

**Comment by kyleodonnell** [comment]
These options in the lxc config worked for me:
lxc.apparmor.profile = unconfined
lxc.cgroup.devices.allow = a
lxc.cap.drop =
lxc.cgroup.devices.allow = b 7:* rwm
lxc.cgroup.devices.allow = c 10:237 rwm
