### ISSUE TITLE
Unable to connect to MailCow using AquaMail on Android. 

### ISSUE THREAD

**Issue by agottschling** [mailcow/mailcow-dockerized#1762]
Hey all, I've been using mailcow for a while now and am loving it. However, I've been recently forced to switch email apps on my phone and decided on aquamail pro. Under the previous app, I was using exchange. But now, AquaMail refuses to find exchange settings for my domain, just returning a 404 error.
Any ideas?

**Comment by tkorves** [comment]
Are you able to see, what Aquamail is requesting from the server (URI / Path)?

This looks like a client-related issue which can’t be addressed here.

**Comment by agottschling** [comment]
![image](https://user-images.githubusercontent.com/8459640/45503549-2d01dc80-b755-11e8-9a48-97f7387c663f.png)
This is all that the app is showing me. I'll contact the developers of the app and see what's going on.

**Comment by andryyy** [comment]
Exchange web services will not work. Only EAS is supported.

**Comment by Braintelligence** [comment]
Why don't you use IMAP instead? It's afaik less taxing on the server anyway.
