### ISSUE TITLE
Can't add new event or contact in sogo with fresh install

### ISSUE THREAD

**Issue by tuxfanou** [mailcow/mailcow-dockerized#1764]
Hello,
I just installed a fresh install of mailcow after a crash.
Everything seems to work except contacts and calendar.
When I try to add something don't have any error in sogo but nothing appear.
In docker I can see this :

- Calendar
```
sogo-mailcow_1       | Sep 13 20:08:44 a65cb5552852 sogod [55]: <0x0x55716824e550[GCSFolder]> ERROR(-[GCSFolder writeContent:fromComponent:container:toName:baseVersion:]): cannot insert content : <MySQL4Exception: 0x557168379cd0> NAME:ExecutionFailed REASON:Column count doesn't match value count at row 1
sogo-mailcow_1       | Sep 13 20:08:44 a65cb5552852 sogod [55]: [ERROR] <0x5571680926b0[SOGoAppointmentObject]:37-5B9AA780-4F-7C908B80.ics> write failed: <MySQL4Exception: 0x557168379cd0> NAME:ExecutionFailed REASON:Column count doesn't match value count at row 1
```

- Contact
```
sogo-mailcow_1       | Sep 13 20:22:22 a65cb5552852 sogod [57]: [ERROR] <0x0x557168368890[GCSFolder]> -[GCSFolder _generateInsertStatementForRow:adaptor:tableName:]: no type found for column name c_folder_id
sogo-mailcow_1       | Sep 13 20:22:22 a65cb5552852 sogod [57]: <0x0x557168368890[GCSFolder]> ERROR(-[GCSFolder writeContent:fromComponent:container:toName:baseVersion:]): cannot insert content : <MySQL4Exception: 0x5571682fc690> NAME:ExecutionFailed REASON:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 'test', 'vcard', '', 'test', '37-5B9AAA80-55-7C908B80.vcf', 0, null, '', '', nu' at line 1
sogo-mailcow_1       | Sep 13 20:22:22 a65cb5552852 sogod [57]: [ERROR] <0x5571686a5dc0[SOGoContactGCSEntry]:37-5B9AAA80-55-7C908B80.vcf> write failed: <MySQL4Exception: 0x5571682fc690> NAME:ExecutionFailed REASON:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 'test', 'vcard', '', 'test', '37-5B9AAA80-55-7C908B80.vcf', 0, null, '', '', nu' at line 1
```

Do you have some idea about that ?

**Comment by andryyy** [comment]
Looks strange. I cannot confirm it on my machines. :-(

Can you run this, please?

```
source mailcow.conf
docker-compose exec mysql-mailcow mysqldump -u${DBUSER} -p${DBPASS} --no-data --compact ${DBNAME} | egrep -v "(^SET|^/\*\!)"
```

**Comment by tuxfanou** [comment]
Thank you @andryyy 
I attached the result.
I don't know if it's a good result or not :)
[result.txt](https://github.com/mailcow/mailcow-dockerized/files/2380827/result.txt)

**Comment by andryyy** [comment]
Was sogo-mailcow build manually? I cannot recreate it with the images from Docker hub. Did you run up -d and it took a long while?

**Comment by tuxfanou** [comment]
I used the documentation :
https://mailcow.github.io/mailcow-dockerized-docs/install/

```
git clone https://github.com/mailcow/mailcow-dockerized
cd mailcow-dockerized
./generate_config.sh
docker-compose up -d
```

And yes, it take a very long time before mailcow was built.

I can try to re-deploy, but I must reconfigure mailcow and transfert again my emails.

**Comment by andryyy** [comment]
Read it again, you missed the pull. The current SOGo nightly might be broken. :-)

**Comment by tuxfanou** [comment]
I can't remember if I did it or not.
I will try and post the result.
If I did this mistake I'm very sorry.

**Comment by tuxfanou** [comment]
Ok, I'm really sorry.
I can't believe I didn't pull images.
If I underderstand, if images are not present (with pull), compose will build them with git sources.
Is it right ?

**Comment by andryyy** [comment]
Yes, they will be built using data/Dockerfiles/container. :-)

It is possible SOGo has changed something in their recent nightly, that breaks the db schema. I will check this. When you build sogo-mailcow, you pull the latest nightly. We use a "pretty new" nightly, but not the latest.

**Comment by tuxfanou** [comment]
Thank you very much for your patience and you informations.
We can close this topic, I'll be more careful the next time.

**Comment by andryyy** [comment]
By the way, I think this was causing it: https://github.com/inverse-inc/sogo/commit/d05e1fed5de900640a7383f269c9d29e87b3b278
