### ISSUE TITLE
Can not add a domain

### ISSUE THREAD

**Issue by ddefosse** [mailcow/mailcow-dockerized#1765]
Hello,

when I try to create a new domain, nothing happens when I click on "add domain only" 

an idea ?

**Comment by ddefosse** [comment]
```
api.js:10 Uncaught ReferenceError: loading_text is not defined
    at is_active (api.js:10)
    at HTMLButtonElement.<anonymous> (api.js:209)
    at HTMLDocument.dispatch (jquery-1.12.4.min.js:3)
    at HTMLDocument.r.handle (jquery-1.12.4.min.js:3)
```

**Comment by andryyy** [comment]
Cannot confirm this. Anyone?

Could you please clean your browsers cache?

**Comment by ddefosse** [comment]
I emptied the cache completely.
tried with chrome, firefox but the problem persists

**Comment by ddefosse** [comment]
oh sorry i just managed
good I did not understand too well but it works
sorry for the inconvenience
