### ISSUE TITLE
DNS Entry error "0: Failed to parse address"

### ISSUE THREAD

**Issue by damian73** [mailcow/mailcow-dockerized#1769]
When I  open the DNS Entries, I'm getting the following error: (See attached error)

Anyone an Idea how this could happend and how I can solve it?

![snap_2018 09 14_23h50m19s_002_](https://user-images.githubusercontent.com/22677354/45577143-d393cd80-b87a-11e8-9f23-dfd672be756f.jpg)

Best regards

D.

**Comment by mkuron** [comment]
Did you change any of the ports in mailcow.conf?

**Comment by andryyy** [comment]
The TLSA records look ... strange:

```
_._tcp
```

**Comment by damian73** [comment]
No, standard installation, no changes in config files.

**Comment by andryyy** [comment]
The DNS configuration is not correct.

**Comment by damian73** [comment]
> 
> 
> The DNS configuration is not correct.

Clear to me, but what to do?

But what is the Problem?
MC Configuration, or DNS at Provider?

What me confuses me is, that the left side is normally fixed..
The entries for Port 143 and 587 are missing...

regards


DAniel

**Comment by andryyy** [comment]
Could also be a changed vars.inc.php. If you are sure you didn't change anything, then it is the DNS configuration.

**Comment by damian73** [comment]
> 
> 
> Could also be a changed vars.inc.php. If you are sure you didn't change anything, then it is the DNS configuration.

For sure, I'm 100% sure that I made no changes on the Configuration, and the DNS settings seems to be ok to me.

Any Idea, what to do?

**Comment by smartens** [comment]
Hi,

I know this is closed. But for anyone who has the same problem I opened https://community.mailcow.email/d/442-wrong-dns-entry to discuss this problem.
