### ISSUE TITLE
Question: possibility of tool-accounts

### ISSUE THREAD

**Issue by sfinke0** [mailcow/mailcow-dockerized#177]
Hi there,

as I host some tools that send mails quite regularly (Gogs, rss2email), I'd like to have an account that may login to SMTP but does not have a mailbox in Dovecot and is not able to receive mails. E.g. an `noreply@example.com` account.

Is this possible already or might this be a feature in a future release?

cheers,
carazzim0

**Comment by andryyy** [comment]
You can use any real mailbox, edit this mailbox and check "Do not check sender for domain xy". Now you can send as user "whatever@this-domain".

**Comment by broedli** [comment]
In addition to @andryyy suggestion, you could also use the vacation feature in sieve to create an autoreply and message discard on incomming mails:

```
require ["vacation"];
vacation :days 1 :subject "Unmonitored Mailbox" :addresses ["alias1@domain.tld", " alias2@domain.tld"] text:
This Mailbox is not being monitored!

Your mail got deleted and won't be read.

The administrator.
.
;
if allof (address :contains "to" "ttlab.de") {
    discard;
}
````

Note you can also use the SOGo interface. It provides a mask for the vacation addon.

I'm closing this issue. @carazzim0 if you still have questions please feel free to open a new post on [the forums](https://forum.mailcow.email/) or open a new issue
