### ISSUE TITLE
Change updater docker-compose order

### ISSUE THREAD

**Issue by Pyton** [mailcow/mailcow-dockerized#1770]
Would be nice to first fetch new docker images and then make `docker-compose down`. There will be lower downtime, cos no need to w8 for fetching new images.

**Comment by mkuron** [comment]
We did that until f7ff93a499e51cc603145757c80a495d015c9640. It occasionally had  problems with old containers not getting removed, which seemed to be a Docker bug. Also updating the Git repo while the containers are running is a bit risky if the database schema changes in the update.
