### ISSUE TITLE
../docker/overlay2 using same disk space as ../docker/volumes

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#1771]
Greetings,

My ../docker/overlay2 folder is using the same disk space as ../docker/volumes

![image](https://user-images.githubusercontent.com/1459530/45584799-de2d8180-b8d1-11e8-8283-3b009e6becb9.png)

```
../docker/volumes/ 9.4 GiB
../docker/overlay2/ 9.0 GiB
```

Is this normal?
Any tips for cleanup?

Thank you very much.

**Comment by mkuron** [comment]
That is just a coincidence. overlay2 is where the images are stored and old images can be removed by `docker system prune -a`. volumes is where your data is stored (e.g. your Mailcow database, your mailboxes, etc.); this data should obviously not be deleted.

**Comment by apintocr** [comment]
Thank you @mkuron 
It solved my problem.

Just as a warning for anyone running **docker system prune**, make sure ALL your containers are UP and running ;)
