### ISSUE TITLE
Mailcow with php mail() function or Smtp in mybb forum software

### ISSUE THREAD

**Issue by Tigerpanzer02** [mailcow/mailcow-dockerized#1773]
I have asked firstly in a german forum my question that is about mybb[Click Here](https://www.mybb.de/forum/thread-35919.html)

I have Mailcow and Mybb on the same Server i would like to use the Mybb Mailfunction to send mails to users. But my problem is that I can´t figure out the problem why it isn´t working. 

When I will use the mail() function it says - MyBB was unable to send the email using the PHP mail() function.
When I try to use Smtp Unable to connect to the mail server with the given details. Reason: 110: Connection timed out

On the Link you can see the Picture´s of the configuration at mybb. 

I hope someone can help me because I can´t find a solution

**Comment by andryyy** [comment]
Hi,

Is mybb running as part of mailcows web root in data/web? Or are you using a reverse proxy?

Can you post your configuration of mybb here? I cannot open attachments as guest. :-(

**Comment by Tigerpanzer02** [comment]
Heey,

I upload the images here again. Mailcow and Mybb are running on the same root server.

![screenshot 172](https://user-images.githubusercontent.com/37453987/45596987-45782e00-b9c5-11e8-8d08-9445c8259f89.png)
![screenshot 173](https://user-images.githubusercontent.com/37453987/45596990-49a44b80-b9c5-11e8-9ddd-0591cd5b53ce.png)

**Comment by andryyy** [comment]
Try to use 172.22.1.1 as mail server IP.

**Comment by Tigerpanzer02** [comment]
why 172.22.1.1? Do you mean localhost Ip (127.0.0.1)? 

When I use it then I become this error "Failed to start TLS encryption"

**Comment by andryyy** [comment]
Your servers name probably points to 127.0.0.1 which it cannot connect to. 172.x.x.x is the bridges IP and the networks gateway.

**Comment by mitchellurgero** [comment]
what @andryyy means is that `172.22.1.1` is the IP of the Docker Bridge, which should have access to the SMTP port you are asking about.

As for The SMTP error Make sure you have port 587 as the port and TLS is enabled and if support disable TLS verification.

**Comment by Tigerpanzer02** [comment]
How can be the ip not my origin ip? (It is not 172.x.x.x) 

> what @andryyy means is that `172.22.1.1` is the IP of the Docker Bridge, which should have access to the SMTP port you are asking about.
> 
> As for The SMTP error Make sure you have port 587 as the port and TLS is enabled and if support disable TLS verification.

When I try to use it with TLS i become this

* Failed to start TLS encryption

When I try to use it without TLS
* The server did not understand the AUTH command

I tried combinations like localhost/origin ip/domain etc. 

So now I have tested with an port (My Https port in mailcow configuration)

Then I become this error

* The mail server is not ready, it did not respond with a 220 status message.

Maybe I need another Port?

**Comment by mkuron** [comment]
Make sure you are using port 587; "did not understand AUTH" sounds like you used 25. TLS fails to verify the server name if you connect via an IP address, so disable it.

**Comment by mitchellurgero** [comment]
> How can be the ip not my origin ip? (It is not 172.x.x.x)

172.22.x.x is the Docker internal Network.

As for what @mkuron 587 might not work without TLS because that port expects it (depending on how Postfix is configured)

I believe if you just put "postfix-mailcow" in the host name it should work. Internally to the docker network for mailcow, DNS should allow this (default for Docker networks)

**Comment by Tigerpanzer02** [comment]
> Make sure you are using port 587; "did not understand AUTH" sounds like you used 25. TLS fails to verify the server name if you connect via an IP address, so disable it.

I use 587... That you can see in the first post.

> > How can be the ip not my origin ip? (It is not 172.x.x.x)
> 
> 172.22.x.x is the Docker internal Network.
> 
> As for what @mkuron 587 might not work without TLS because that port expects it (depending on how Postfix is configured)

Aha but it is also not working

> 
> I believe if you just put "postfix-mailcow" in the host name it should work. Internally to the docker network for mailcow, DNS should allow this (default for Docker networks)

When I type this in the Ip field i become this error

"Unable to connect to the mail server with the given details. Reason: 0: php_network_getaddresses: getaddrinfo failed: Name or service not known"


So does anyone know a solution with php mail() function or another try to have a happy smtp connection -_-

**Comment by rassemdev** [comment]
> 

How did you run both of your web application and mail server at same server? Would you kind enough to share the procedure? and did you able to solve this problem? If yes, can you share this too!
