### ISSUE TITLE
Enabling masquerading on interface makes mailserver an open relay

### ISSUE THREAD

**Issue by tenten8401** [mailcow/mailcow-dockerized#1775]
I'm stumped on this one. I'm not sure if it's an issue with Mailcow or not.
Basically, when I enable IP masquerading on my interface with the following commands, my mail server apparently turns into a wide open relay:
![image](https://user-images.githubusercontent.com/6174343/45603214-d0721c00-b9f7-11e8-856e-637b09b55429.png)
![image](https://user-images.githubusercontent.com/6174343/45603212-c9e3a480-b9f7-11e8-8606-d1efd2a0188b.png)

However, when I disable it with the following commands, it goes back to normal:
![image](https://user-images.githubusercontent.com/6174343/45603219-e54eaf80-b9f7-11e8-8dba-98a407154ed5.png)
![image](https://user-images.githubusercontent.com/6174343/45603221-e97acd00-b9f7-11e8-81f7-7460e807fef1.png)

Tests run on: https://mxtoolbox.com/diagnostic.aspx

I think this might be an issue with Mailcow, but I don't have a non-mailcow server setup to test.

**Comment by mkuron** [comment]
Using a firewall with Mailcow ( or most other dockerized applications) can be dangerous and is not supported, as you can read in many issues (just search for firewall or iptables). In your case, the masquerading will hide the external IP presented to Postfix. You need to restrict the rule to exclude your Docker interfaces (which are automatically masqueraded by Docker) and your external interface (where the masquerading causes the open relay).

**Comment by tenten8401** [comment]
Ah, that makes sense. My bad.
