### ISSUE TITLE
increase log size in web debug

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1777]
Hi there,
Is there any way i can increase the number of days for in-memory (redis) logs? I would like to achieve at leaset 1 week of postfix/dovecot logs. I know syslog or other drivers are an option, but for various reasons i also have to increase the in-memory logs as well.
Any way i can do that?
Thank you.

**Comment by andryyy** [comment]
Hi,
It is possible to change LOG_LINES in mailcow.conf. 
But that's only (obviously) good for line numbers, it cannot be used to set a date/time in the past.

**Comment by lucianlazar1983** [comment]
Thank you, changing that woul imply issuing another command or it is enough just to restart docker daemon and containers?
Thank you again

**Comment by andryyy** [comment]
Run `docker-compose up -d`. :-)

**Comment by lucianlazar1983** [comment]
Thanks, it's working. have a nice day!
