### ISSUE TITLE
Error helper-scripts/backup_and_restore.sh backup all

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#1780]
Hi folks,

I get the following message on terminal

`tar (child): /backup/backup_postfix.tar.gz: Cannot open: Software caused connection abort
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now`

I use a bash-script for backup

```
#!/bin/bash
#
REMOTE=master@111.222.333.444
DDIR=home/_BACKUP/Contabo/VPS1/mailcow/std
MDIR=/mnt/mailcow/std

sshfs -p 222 -o nonempty $REMOTE:$DDIR $MDIR

BACKUP_LOCATION=$MDIR /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all
umount $MDIR
#
```

**Comment by andryyy** [comment]
That's related to the sshfs mount, not a mailcow issue.

Maybe someone can help, I will tag it as question.

**Comment by jm3west** [comment]
oh my god
I'm so stupid

The target-path in my script is ....

DDIR=home/_BACKUP/Contabo/VPS1/mailcow/std

it must be

DDIR=/home/_BACKUP/Contabo/VPS1/mailcow/std

f*** I'm really stupid

regards
jm3west

**Comment by MAGICCC** [comment]
It's resolved now, so I close this
