### ISSUE TITLE
map file readonly in rspamd

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#1785]
I created a multimap like that:

```
COUNTRY_EU {
  type = "country";
  map = "$LOCAL_CONFDIR/custom/countries_eu.map";
  description = "IP in a nice European country";
  score = -2;
}
```
and countries_eu.map appears into Rspamd web interface Configuration menu. But only with the [Read] tag. I chmodded to 777 and reloaded but no luck. 

How can i enable editing for my map files from inside rspamd interface?

![capture](https://user-images.githubusercontent.com/840788/45819789-7d44e580-bce5-11e8-9752-9b9c1a8b8d6f.png)

**Comment by mkuron** [comment]
You need to edit https://github.com/mailcow/mailcow-dockerized/blob/8056ed21af52035e1b4ba71c4d7ae1c61653cafa/docker-compose.yml#L82 and change it from `:ro` to `:rw`.

**Comment by marrco** [comment]
thx, this should be added to some readme or documentation
