### ISSUE TITLE
Outlook and EAS: Follow-up flags deleted

### ISSUE THREAD

**Issue by XUBIUM** [mailcow/mailcow-dockerized#1786]
Hello, 

We have been testing Mailcow with good results in the company, but we do have a small issue that is affecting all users (we have Outlook O365 and we use EAS for sync): When compossing a message you have the option to flag it so you can follow-up later in the tasks list. The issue is that the flag doesn't remail when the email is sent (the email in the sent items doesn't have the flag, and because of that the message is not listed in the Outlook tasks).

Has anybody seem this behavior? Do you have some advice? As this is happening to all users, it must be something about the server (hopefully config) or the way we are configuring the sync. 

Thanks,

**Comment by mkuron** [comment]
Does that even work with a Microsoft Exchange server? EAS does not support everything you can do in Outlook, and I wouldn't be surprised if this was one of the limitations. If it does work with Exchange, it's a SOGo bug/feature request that should be filed with them.

**Comment by XUBIUM** [comment]
Yes, it does work with Microsoft Exchange Server. I'll check with SOGo then. 
Thanks.
