### ISSUE TITLE
Regex in Aliases

### ISSUE THREAD

**Issue by hockeymikey** [mailcow/mailcow-dockerized#1787]
Allow regex to be used in aliases. So we could have an alias like /test\.[A-Z]+[0-9]@example.com.

Also allow for the capture groups to be used in the destination address, like a restrictive catch-all alias. So say we have /([a-z]{1,16}).([a-z]{1,16})@example.com for our alias, we can use /\2@example.com for our destination address.  burner.test@example.com would be directed to test@example.com in that example.

**Comment by EnriqCG** [comment]
could this create a conflict with email tags?

**Comment by andryyy** [comment]
Iirc there was an issue for this.

**Comment by hockeymikey** [comment]
@andryyy Maybe. I didn't run across any when searching personally.

**Comment by BorysVrublevskyi** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/2507#issuecomment-1822328502
