### ISSUE TITLE
Whitelisting an address through web interface fails

### ISSUE THREAD

**Issue by MarkOnDuty** [mailcow/mailcow-dockerized#1788]
After an update a couple of hours ago, using the web interface to whitelist an address fails. It doesn't seem to matter what input is entered in the whitelist field, the result is the same.

See the attached image for what is seen in the browser.

![editobject](https://user-images.githubusercontent.com/40303438/45902065-8647bc80-bda2-11e8-922c-3215ffa042b2.png)

**Comment by andryyy** [comment]
Hey, we didn't change anything there. Probably just JS and your cache. :-) Clean your browsers cache completely, close and open it.

**Comment by MarkOnDuty** [comment]
Yup. That was it.

I'd bet my first-born that we have the same issue in our own code, and our users are much less prepared to deal with this sort of thing than I am. Glad I ran into this.
