### ISSUE TITLE
Adding a new mailbox fails

### ISSUE THREAD

**Issue by MarkOnDuty** [mailcow/mailcow-dockerized#1789]
After upgrading about three hours ago, I can't add mailboxes. Clicking the 'Add' button in the 'Add Mailbox' dialog results in absolutely nothing happening.

Hmmm... Maybe if I make sure that my browser isn't using any cached data for Mailcow's web interface...

**Comment by mkuron** [comment]
Most likely a duplicate of #1788. Reset your browser cache and check its JavaScript console.

**Comment by MarkOnDuty** [comment]
Yup. That was it.

But it is was definitely a jarring experience. It's motivated me to check the code that I maintain for the same issue, and to come up with a remedy.
