### ISSUE TITLE
Found 3 elements with non-unique id #edit_selected

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1792]
Hi,

![screen shot 2018-09-24 at 19 51 34](https://user-images.githubusercontent.com/2929968/45966261-4c411980-c033-11e8-93be-a3084985cffb.png)

source: /edit.php?mailbox=...@..

**Comment by proea** [comment]
the same for [DOM] Found 3 elements with non-unique id #key_id

**Comment by proea** [comment]
Found 8 elements with non-unique id #csrf_token
Found 4 elements with non-unique id #confirm_password

**Comment by andryyy** [comment]
This is known but does not affect usability. I will fix it.

**Comment by proea** [comment]
@andryyy yes, sure. Thank you!
