### ISSUE TITLE
roundcube managesieve settings

### ISSUE THREAD

**Issue by lavdnone** [mailcow/mailcow-dockerized#1793]
Looks like those settings are not enough now. If someone can share fresh Roundcube managesieve settings

> $config['managesieve_port'] = 4190;
> $config['managesieve_host'] = 'tls://dovecot';
> $config['managesieve_conn_options'] = array(
> 'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
> );
> 
> // Enables separate management interface for vacation responses (out-of-office)
> // 0 - no separate section (default),
> // 1 - add Vacation section,
> // 2 - add Vacation section, but hide Filters section
> $config['managesieve_vacation'] = 1;

_Originally posted by @pmike1980 in https://github.com/mailcow/mailcow-dockerized/issues/1461#issuecomment-395172525_

**Comment by lavdnone** [comment]
no need of this any more? https://github.com/mailcow/mailcow-dockerized/issues/820

**Comment by lavdnone** [comment]
It worked but SOGo wipes sieve files using its own data from SQL so roundcube managesieve makes no sense for now.

**Comment by zeigerpuppy** [comment]
It would be good to have a working managesieve option for roundcube, some users may prefer to use that client instead of SoGo

I tried the above settings with a clean install and roundcube throws an error (server name replaced):

```
nginx-mailcow_1      | 2019/01/09 18:35:40 [error] 26#26: *4934 FastCGI sent in stderr: "PHP message: ERROR: Failed to read from socket ()" while reading upstream, client: 49.160.111.57, server: mail.server.net, request: "GET /rc/?_task=settings&_action=plugin.managesieve HTTP/2.0", upstream: "fastcgi://172.22.1.9:9002", host: "mail.server.net", referrer: "https://mail.server.net/"
```

**Comment by andryyy** [comment]
Could be due to a disabled function? Not sure. You need to post Roundcube logs.

You can try to remove the disabled_functions stuff (the whole two lines) from `data/conf/phpfpm/php-fpm.d/pools.conf` and restart php-fpm-mailcow. Does it work then?

**Comment by andryyy** [comment]
I just added the settings to the config and enabled the plugin. It works fine. I tested it.

See the docs.

**Comment by zeigerpuppy** [comment]
thanks, I'll test here too.
Will the docs appear here? https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

current error from roundcube is:
```
PHP Error in /web/rc/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php (222): Unable to connect to managesieve on dovecot:4190
```

**Comment by andryyy** [comment]
Yes, they are online now.

I just tested it and also checked the sieve functionality (vacation). It works.

**Comment by zeigerpuppy** [comment]
thanks, tested and working with the changes you showed for `/data/web/rc/config/config.inc.php`.  Strangely I had entered the same settings in the managesieve plugin configuration `/data/web/rc/plugins/managesieve/config.inc.php` and it didn't work

**Comment by andryyy** [comment]
Ah, I see. :) thanks for reporting back
