### ISSUE TITLE
 DKIM-Signature header exists but is not valid

### ISSUE THREAD

**Issue by Afondevi** [mailcow/mailcow-dockerized#1795]
Hello,

I try to send email to hotmail/outlook and another **microsoft** email but always go in **spam**.
I'm on in from **1 month** and don't find solution...

**check my mail-tester.com score :** https://www.mail-tester.com/test-mgdyu
**SpamAssassin score :** 0.1
**appmaildev.com/en/dkim :**
domainKey-Result: none (no signature)
If DKIM result is passed, you can ignore DomainKey result: none
**spamcheck.postmarkapp.com :** DKIM-Signature header exists but is not valid

See more information here : 

**Signature Did Not Verify**
https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx?huid=9b36a291-b04d-4960-97f3-f799da74a33d

**Is not spam**
http://isnotspam.com/newlatestreport.php?email=ins-3nlf6lka%40isnotspam.com

Thanks in advance
Alex

**Comment by andryyy** [comment]
You should check your DNS settings. Probably a wrong DKIM record there.

**Comment by Afondevi** [comment]
Hello @andryyy I don't see what can be wrong..
If you can help me to send mail to microsoft service, I will be very grateful

**Comment by andryyy** [comment]
Send a mail to apeters87@gmail.com :-)

**Comment by Afondevi** [comment]
Done ! :)

**Comment by andryyy** [comment]
The signature is not broken. 

Your networking reputation is just bad. You can **ask** Microsoft to remove you from their greylist. There are online forms for that. 

OVH, Hetzner etc. shouldn’t be used for mail...

**Comment by Afondevi** [comment]
Ok so for you it's because my server is in OVH FAI ?
Because I ask microsoft to add me in whitelist but they don't want because my email don't have reputation. How create reputation and how see it ? thanks in advance guy !

**Comment by mkuron** [comment]
Duplicate of #1371. The only way to create a reputation with Microsoft is by sending non-spam messages to them, which is impossible if you are blacklisted. Microsoft is absurdly restrictive these days, to the extent that you can’t reliably deliver to them if you are not one of the big established email providers. You apparently can even get blacklisted for not sending enough messages to them, even if you are on an otherwise clean network.
