### ISSUE TITLE
Feature request: jquery chosen

### ISSUE THREAD

**Issue by stAn47** [mailcow/mailcow-dockerized#1800]
Dear friends, we really like mailcow and we are using it for a few hundreds of mailboxes on our server and it's looking very good. 

For the administration of the mailboxes it would be very useful to switch from "boostrap select" into "jquery chosen" dropdowns which allow you to search the values much faster compared to bootstrap select. 

i do not know how to submit code here, but this is how we added chosen jquery select dropdowns to our installation: 

\opt\mailcow-dockerized\data\web\inc\header.inc.php

we commented: 
```
<!--<link rel="stylesheet" href="/css/bootstrap-select.min.css">-->
```
and added:
```
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css">
```

for javascripts: 
\opt\mailcow-dockerized\data\web\inc\footer.inc.php

we commented/removed:
```
<!--<script src="/js/bootstrap-select.min.js"></script>-->

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
```

and to the bottom of the same file:

```
<script>
$("select").chosen();
$('.chosen-drop').css({"width": "auto", "white-space": "nowrap"});
$('.chosen-container').css({"width": "auto", "white-space": "nowrap"});
</script>

```

now the select dropdowns and multiple selects are working much nicer. 

it would be great to have this implemented in the core. 

best regards, stan

**Comment by andryyy** [comment]
Hi,

We added a bunch of `data-live-search="true"` to select fields where it was needed. If you find missing search fields, let me know or create a PR. But there is no need to change to another lib for this. :-)

**Comment by stAn47** [comment]
hello, no problem, i am new to docker and new to mailcow, i updated mailcow instance a few weeks ago and i didn't see any searches there on these selects. 

i believe search is useful for any select that lists more then 20 items, especially mailboxes or domains, especially in the mailbox config "Allow to send as" (multiselect) and "BCC maps"

right now i will probably go through BCC modal adjustment as i'd like to add 50 mailboxes into a single sender BCC address and it will be probably faster to adjust the code then to do it manually via the interface. (i.e. modify BCC email to multiselect array and modify bcc function to support array input ) > a large office needs to have a control of outgoing emails per some employees. 

best regards, stAn

**Comment by andryyy** [comment]
That's not how BCC works. It cannot have multiple destinations. Why not use aliases?

Or use a single alias as BCC dest and add multiple rcpts there?

**Comment by stAn47** [comment]
hello, we only need "sender BCC" not reciever, so each outgoing email from employee is also stored in a common mailbox which is checked by a manager. 

so i need to add all employee's emails like:

john@example.com
jane@example.com

as sender BCC to 
all@example.com

so the output sender bcc map would look like
john@example.com all@example.com
jane@example.com all@example.com

i.e. in "add BCC maps": 
Local destination: (multiple mailboxes can be slected)
Type: sender
BCC destination: (allow just single for thus case)

ideally this would create a new line per each multiple selection within the BCC map list. 


stan

**Comment by stAn47** [comment]
so this is what i did: 

```
<select id="addSelectLocalDest" name="local_dest" multiple="multiple" id="local_dest" required>
```
added the multiple="multiple" in
\opt\mailcow-dockerized\data\web\modals\mailbox.php

and updated "add" action in functions:
\opt\mailcow-dockerized\data\web\inc\functions.address_rewriting.inc.php

```
 case 'add':
      if (!isset($_SESSION['acl']['bcc_maps']) || $_SESSION['acl']['bcc_maps'] != "1" ) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => sprintf($lang['danger']['access_denied'])
        );
        return false;
      }
	   if (is_array($_data['local_dest'])) {
		$myData = array(); 
		foreach ($_data['local_dest'] as $local_dest) {
		  $temp = $_data; 
		  $temp['local_dest'] = strtolower(trim($local_dest)); 
		  if (empty($temp['local_dest'])) continue; 
		  $myData[] = $temp;
		  
		}
		
	}
	else {
		$myData[] = $_data; 
	}
	  $ret = true; 
	  foreach ($myData as $_data) {
      $local_dest = strtolower(trim($_data['local_dest']));
      $bcc_dest = $_data['bcc_dest'];
      $active = intval($_data['active']);
      $type = $_data['type'];
      if ($type != 'sender' && $type != 'rcpt') {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'Invalid BCC map type'
        );
        return false;
      }
      if (empty($bcc_dest)) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'BCC destination cannot be empty'
        );
        continue; 
      }
      if (is_valid_domain_name($local_dest)) {
        if (!hasDomainAccess($_SESSION['mailcow_cc_username'], $_SESSION['mailcow_cc_role'], $local_dest)) {
          $_SESSION['return'] = array(
            'type' => 'danger',
            'msg' => sprintf($lang['danger']['access_denied'])
          );
          continue; 
        }
        $domain = idn_to_ascii($local_dest);
        $local_dest_sane = '@' . idn_to_ascii($local_dest);
      }
      elseif (filter_var($local_dest, FILTER_VALIDATE_EMAIL)) {
        if (!hasMailboxObjectAccess($_SESSION['mailcow_cc_username'], $_SESSION['mailcow_cc_role'], $local_dest)) {
          $_SESSION['return'] = array(
            'type' => 'danger',
            'msg' => sprintf($lang['danger']['access_denied'])
          );
          $ret = false;
		  continue; 
        }
        $domain = mailbox('get', 'mailbox_details', $local_dest)['domain'];
        if (empty($domain)) {
          $ret = false;
		  continue; 
        }
        $local_dest_sane = $local_dest;
      }
      else {
        $ret = false;
		  continue; ;
      }
      if (!filter_var($bcc_dest, FILTER_VALIDATE_EMAIL)) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'BCC map must be a valid email address'
        );
        $ret = false;
		  continue; 
      }
      try {
        $stmt = $pdo->prepare("SELECT `id` FROM `bcc_maps`
          WHERE `local_dest` = :local_dest AND `type` = :type");
        $stmt->execute(array(':local_dest' => $local_dest_sane, ':type' => $type));
        $num_results = count($stmt->fetchAll(PDO::FETCH_ASSOC));
      }
      catch(PDOException $e) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'MySQL: '.$e
        );
        return false;
      }
      if ($num_results != 0) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'A BCC map entry "' . htmlspecialchars($local_dest_sane) . '" exists for type "' . $type . '"'
        );
       $ret = false;
		  continue; 
      }
      try {
        $stmt = $pdo->prepare("INSERT INTO `bcc_maps` (`local_dest`, `bcc_dest`, `domain`, `active`, `type`) VALUES
          (:local_dest, :bcc_dest, :domain, :active, :type)");
        $stmt->execute(array(
          ':local_dest' => $local_dest_sane,
          ':bcc_dest' => $bcc_dest,
          ':domain' => $domain,
          ':active' => $active,
          ':type' => $type
        ));
      }
      catch (PDOException $e) {
        $_SESSION['return'] = array(
          'type' => 'danger',
          'msg' => 'MySQL: '.$e
        );
        return false;
      }
      $_SESSION['return'] = array(
        'type' => 'success',
        'msg' => 'BCC map entry saved'
      );
	  }
     return $ret;
    break;

```

i also disabled any select frameworks (including my chsone or boostrap) so i can easily select all mailboxes with shift key

then i removed all that i don't want to be listed. 

i hope this helps anybody who needs to add "BCC" for tens or hundreds of mailboxes at once. 

best regards, stan

**Comment by andryyy** [comment]
Postfix will not read more than one destination.

As I said: use aliases.

**Comment by stAn47** [comment]
andryy, but i am talking purely about "sender bcc map" where outgoing emails send a copy to the manager without rewriting any of email headers to the remote receiver. 

i tested my case and it works properly. 

i do not understand why would aliases work better when the "collecting mailbox" is not used for anything else then checking employees (it only receives copy of sent emails)

stan

**Comment by andryyy** [comment]
See https://github.com/mailcow/mailcow-dockerized/issues/993 for the limitation... 

Also: http://postfix.1071664.n5.nabble.com/quot-always-bcc-quot-for-multiple-recipients-via-alias-and-quot-recipient-bcc-maps-quot-don-t-work-td86962.html

**Comment by stAn47** [comment]
thank you, i am using always a single destination per single mailbox (and right now also a single detination per configured mailboxes of a domain). the destination is a local mailbox as well, so this is not a problem for me. 

if i needed to rewrite headers with proper DKIM and else, then aliases would make more sense. 

best regards, stan
