### ISSUE TITLE
Mysql/innodb_table_stats length mismatch

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1804]
After restoring my mailcow server. The following error popped up:

> [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade

Mailcow seems to be working fine at first sight. But [given this issue](https://github.com/mailcow/mailcow-dockerized/issues/1699#issuecomment-414792315) 

I think it would be useful to report this.

Regards and thanks @andryyy and team for Mailcow.

**Comment by andryyy** [comment]
Hey, is it up and running? :-)

That would be very easy to run `source mailcow.conf; docker-compose exec mysql-mailcow mysql_upgrade -uroot -p${DBROOT}` then.

**Comment by xetorixik** [comment]
Hi, server is up and running.
Already used the [same command from your comment](https://github.com/mailcow/mailcow-dockerized/issues/1699#issuecomment-414793556) elsewhere. 
Because you have not seen a similar error much more often, I thought it would be useful to post this issue.

> The "innodb_index_stats" error is something I have not seen, don't know. Try what it suggests:

Once again thanks for your time.

**Comment by andryyy** [comment]
Ah, yes, but the error is gone now?

**Comment by xetorixik** [comment]
Yup. But gonna restore the backup and new backup to another server (test server) to make sure.
As it is 12:00 a.m. right now. I will do that tomorrow. I will come back to this afterwards.

**Comment by xetorixik** [comment]
Fixed. ticket is already closed. Thanks @andryyy and team.
