### ISSUE TITLE
Since update to RSpamd 1.8 no spam filtering working anymore

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1807]
Hello. Quick and simple: I have got quite a list of E-Mails which are automatically being declined by mailserver, so they're in the blacklist section in the webinterface of mailcow. Since the latest update, which included a RSpamd update, I am receiving mails from those, actually blocked E-Mails, tho they are still in the blacklist list. My question now: did anything change in the latest version I need to adapat my settings to or something like this, to make the feature become working again ?

**Comment by andryyy** [comment]
Hi, please see the other issue. Just run update.sh again.

**Comment by xL0b0** [comment]
Just did it like 20 minutes ago. Issue still persists. Just tested it.

**Comment by andryyy** [comment]
Try `docker-compose stop rspamd-mailcow`, `docker-compose rm rspamd-mailcow` (confirm), `docker-compose pull rspamd-mailcow`, `docker-compose up -d`

**Comment by andryyy** [comment]
Ah, **after** doing so, please run this:

```
docker-compose exec rspamd-mailcow cat /etc/rspamd/settings.conf
```
and
```
docker-compose restart rspamd-mailcow; docker-compose logs -f --tail=200 | grep -i 'settings'
```
You can stop the above command as soon as you see something like `settings.lua:659: loaded 2 elements of settings`. How many settings did it load?

**Comment by xL0b0** [comment]
Working already again after the first comment you wrote. Just tested it with a secondary email I added and the mail is being declined by the server :) thx

**Comment by xL0b0** [comment]
Didn’t even have to run the second commands

**Comment by andryyy** [comment]
It takes a while to load the settings. :-)

**Comment by xL0b0** [comment]
Thank you. At that point as it’s working again I think I can close the thread.
