### ISSUE TITLE
Changes to aliases are not immediately visible in SOGo

### ISSUE THREAD

**Issue by heavygale** [mailcow/mailcow-dockerized#1808]
When changing aliases in Mailcow UI, those changes are not immediately visible in SOGo. Newly created aliases can't be used as "mail from" addresses or only after a waiting time. If I restart the memcached-mailcow container and reload the SOGo page, the changes are immediately visible. Is there a way to automatically invalidate the cached information after the aliases were edited or something like that? Otherwise the user needs to wait until the old cached information is gone (how long is that?).

**Comment by andryyy** [comment]
Thanks, I added something to flush the cache after these changes.
