### ISSUE TITLE
Sync-Job Mails do pass all filters

### ISSUE THREAD

**Issue by cuthulino** [mailcow/mailcow-dockerized#1810]
When syncing mails via the imap sync tool included in mailcow,
all synced mails do not get checked by saved filters.
Like this they can only be sorted by filters on the collected provider.

How can i get the filter to work for them aswell?
Redirecting mails to really receive them is not the best idea.

**Comment by andryyy** [comment]
Sorry, but there is no way and it is also not planned, this is just IMAP synchronization. It is not intended for this. Either forward them or just use mailcow as the primary MX for that domain, when you want to filter mails anyway.
