### ISSUE TITLE
ProxyPass to SOGo?

### ISSUE THREAD

**Issue by kill0rz** [mailcow/mailcow-dockerized#1811]
I am having a subdomain mail.example.com and want to reach SOGo from there.
I am using an apache2 webserver as a systemwide proxy to handle the redirect from the subdomain to SOGo. I tried following config with proxypass:
`ProxyPassMatch "^/(.*)$" "http://nginx-mailcow:8000/SOGo/$1"`

But this does not work, some JS file cannot be loaded:

![laden_fehlgeschlagen](https://user-images.githubusercontent.com/14353631/46246896-29807d80-c404-11e8-9a8d-64e906ffded3.png)

When I add another rewrite rule, it works:

```
ProxyPass /SOGo.woa/ http://nginx-mailcow:8000/SOGo.woa/
ProxyPassReverse /SOGo.woa/ http://nginx-mailcow:8000/SOGo.woa/
```
But still e.g. calendar does not work.
What would be an apropriate ProxyPassRule to make SOGo available under a subdomain?

I know, I could change config of nginx-mailcow, but I don't want to modify it.

**Comment by jaltek** [comment]
Did you try this example?

https://lists.inverse.ca/sogo/arc/users/2013-06/msg00276.html

**Comment by kill0rz** [comment]
I guess this handles another problem.
The thing here is, that SOGo does not load all the content from /SOGo but from other URIs like /SOGO.woa

I am running this config by now, but calendar still does not work:

```
  ProxyPassMatch "^/SOGo(.*)$" "http://nginx-mailcow:8000/SOGo$1"
  ProxyPassMatch "^/(.*)$" "http://nginx-mailcow:8000/SOGo/$1"
```

**Comment by mitchellurgero** [comment]
@kill0rz I'd be willing to assist, email me if you want a more private discussion (I see you whited out your domain so I can't troubleshoot)

Email: info@urgero.org

As for the fix, if I find something I will post it here afterwards (without identifying information of course)

**Comment by kill0rz** [comment]
@mitchellurgero Thank you for your replay! I did not manage to do a correct redirect by now.
But there is no need atm for the calendar feature. I will post a solution here if find one.

Thanks anyway! :)
