### ISSUE TITLE
Delete mailbox doesn't work

### ISSUE THREAD

**Issue by seppeel** [mailcow/mailcow-dockerized#1815]
i just updated after this announcement:
https://mailcow.email/2018/10/02/updates-updates-updates/
I now tried to delete a mailbox in the mailbox administration, but the "delete" button does nothing. when i try the pulldown menu its the same.
i dont know if this came up after this update, but i believe i already deleted a mailbox before.

thanks for your help
seppel

**Comment by andryyy** [comment]
Hi, I changed quite a lot JS stuff, can you try with a clean cache, please? :-)

**Comment by seppeel** [comment]
-> Works :-)

Thanks!
