### ISSUE TITLE
upgrade.sh deleted all configuration

### ISSUE THREAD

**Issue by leifnel** [mailcow/mailcow-dockerized#1816]
I ran update.sh, then docker(?) asked if I wanted to remove old unused stuff. I agreed.

Now the entire mysql configuration is lost, and the admin password is back to default.

Am I doomed??
The mails are still in the volumes folder.
Can I recreate the users and attach to existing mail folders?

**Comment by andryyy** [comment]
You are not. :-) Probably an older mailcow? Can you post the output of `docker volume ls`, please?

**Comment by leifnel** [comment]
I belive you are onto something, dear sir!
```
DRIVER              VOLUME NAME
local               86e6d828ede49bc942db78c50bc20c28568fe3a00dd525d7ef7ee0279ff2d763
local               lost+found
local               mailcow-dockerized_crypt-vol-1
local               mailcow-dockerized_mysql-vol-1
local               mailcow-dockerized_postfix-vol-1
local               mailcow-dockerized_redis-vol-1
local               mailcow-dockerized_rspamd-sock
local               mailcow-dockerized_rspamd-vol-1
local               mailcow-dockerized_vmail-vol-1
local               mailcow-dockerized_vmail-vol-2
local               mailcowdockerized_crypt-vol-1
local               mailcowdockerized_mysql-socket-vol-1
local               mailcowdockerized_mysql-vol-1
local               mailcowdockerized_postfix-vol-1
local               mailcowdockerized_redis-vol-1
local               mailcowdockerized_rspamd-vol-1
local               mailcowdockerized_vmail-vol-1
local               rancher-agent-state
local               rancher-cni
local               rancher-cni-driver
```
The `mailcow-dockerized_*` are from Jun 6, the `mailcowdockerized_*` from today.

**Comment by andryyy** [comment]
Okay, then try this: Run `docker-compose down`, edit mailcow.conf and change COMPOSE_PROJECT_NAME (or smiliar) to "mailcow-dockerized". Run `docker-compose up -d`.

**Comment by leifnel** [comment]
I tried this, but it didn't fetch the old volumes.

But I am on a VM, and have just made a snapshot (I know, I should have done  before upgrading), so I can now play around.

I guess I can create symlinks between the old and new names.

**Comment by andryyy** [comment]
You can also just move the folder names.

**Comment by leifnel** [comment]
Now up and running again.
I got lots of errors when changing COMPOSE_PROJECT_NAME and linking files, so I reverted to snapshot and only linked the files.
It might just be because `mailcowdockerized_mysql-socket-vol-1` had no corresponding `mailcow-dockerized_mysql-socket-vol-1`, but I didn't want to linger too much debugging.
Anyway, thanks to @andryyy for giving the needed hints. I ove you a beer.
