### ISSUE TITLE
Domains can't be deleted

### ISSUE THREAD

**Issue by heavygale** [mailcow/mailcow-dockerized#1818]
> _Could not move maildir to garbage collector: /bin/mv: cannot stat '/var/vmail/example.com': No such file or directory_ 

Steps to reproduce:
- add a new domain, e.g. exmaple.com
- try to delete it

Can be reproduced in the demo (https://demo.mailcow.email/).

If I try to delete a domain which had mailboxes, so that there is a domain.tl folder in the vmail directory, this folder will be deleted but the domain is still listed in the UI afterwards. If I try to delete it again, the error message listed above will be shown.

**Comment by andryyy** [comment]
Ooops, thanks!
