### ISSUE TITLE
Rspamd-sock volume not needed anymore & dkim-vol-1 removed?

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1819]
Hey, I just updated my Mailcow and now the docker volume rspamd-sock is unused. Can I safely delete the volume?

<img width="443" alt="bildschirmfoto 2018-10-02 um 20 57 45" src="https://user-images.githubusercontent.com/6145026/46370652-71163c00-c686-11e8-8cfb-46803eeef8ce.png">

And it seems like the dkim-vol-1 volume was removed too, where are the dkim keys stored now?

**Comment by andryyy** [comment]
Yes, you can delete it. 
The keys are stored in Redis since a few months.

**Comment by ntimo** [comment]
Thanks :)
