### ISSUE TITLE
[FEATURE] Remove sender verification for given mailbox

### ISSUE THREAD

**Issue by Avalarion** [mailcow/mailcow-dockerized#1820]
Hey ho,

for exactly one mailbox we need to remove the sender verification ( due to a very closed customer infractructure so we send names in their name ), but this is not possible. The only possibility would be to create an empty domain for that customer and remove the sender check for the given domain in the mailbox.

This is not the first time we were locking for something like this, but now it gets some kind of urgent.

Is there a possibility to add `Allow to send as *` with the `*` as real wildcard and not just as placeholder for my domains?

Have a nice evening together,

Bastian

**Comment by andryyy** [comment]
Hi, when was your last update? "Allow to send as *" disables the sender check completly. I just verified it works as expected. :-/

**Comment by andryyy** [comment]
When you run this command, it should return the mailboxes to allow any sender:

```
docker-compose exec postfix-mailcow postalias -q somerandom@trashbla.tld mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf
```

**Comment by Avalarion** [comment]
I updated MailCow today to the latest available version.

In the UI I see a list of multiselect for "allow as sender" starting with the mailadress itself followed by all of our domains followed by all of our email accounts and email aliases, but I do not see "Allow to send as*" anywhere, should it be somewhere?

I ran your command, it responded me the mail address, but I still see no changes. So if the feature is enabled do I perhaps miss some database entry or so?

Thanks for your quick help!

**Comment by andryyy** [comment]
Yes, it should.

Did you run this exact command with trashbla? I used this fictive address intentionally.

I think the update is not working correctly, you could run git pull and fix merge conflicts by hand.

**Comment by Avalarion** [comment]
I see a hidden Text in the HTML saying: `<div style="" id="sender_acl_disabled">↳ <span class="label label-danger">Absenderprüfung deaktiviert</span></div>`

I adjusted the mailaddress in the command of course^^.

Here is a git diff after our pull a minute ago:

```On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   data/conf/postfix/main.cf
	modified:   data/conf/rspamd/override.d/worker-controller-password.inc
	modified:   docker-compose.yml```

```

* docker-compose.yml changed a few volume pathes and added a network ( because we have two docker ip addresses on this maschine )
* main.cf => adjusted only the mail size to have bigger mails available ( git diff confirmed )
* worker-controller-password.inc has a private key in it.

`docker-compose pull` told me that I have no outdated images in usage..

Any Idea where in your code this is located so I can verify my images / my config files? I am able to handle PHP and Docker and also Postfix, but a little bit lost in your code.

**Comment by andryyy** [comment]
You need to run the command with the fictive mail address, not with an existing one, not even with an existing domain.

You can check the demo @ https://demo.mailcow.email/ using admin:moohoo (ignore the andre.peters popup here :-)) =>

![grafik](https://user-images.githubusercontent.com/2972950/46376530-7bd8cd00-c696-11e8-8195-b16a5d28dc88.png)

The div becomes visible once it is active:

![grafik](https://user-images.githubusercontent.com/2972950/46376542-872bf880-c696-11e8-8d09-0c75234067cf.png)

It should look exactly like this with up-to-date code. Is it a forked repo?

**Comment by Avalarion** [comment]
Don't ask me why, I removed all containers manually on this maschine and did a full repull and it looked now like in your screenshot and worked out of the box! Thank so you much for helping me on this!

Are you ever at a PHP, TYPO3 or Linux Event next to the RuhrArea or Düsseldorf so I can invite you to a beer?

**Comment by andryyy** [comment]
Strange. :-) 

Thanks to @tkorves we will be at the OpenRheinRuhr this year.
