### ISSUE TITLE
SOGo web error after update

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#1824]
I updated mailcow with ./update.sh and I cannot load SOGo. The web interface gives me the following error:

```An error occurred during object publishing
tried to access private object (0x0x56151b046200, SoClass=SOGoUserFolder)
```

Everything else is working.
While updating I saw SOGo changed from 1.36 to 1.38
SOGo's logs show 
 
```
[63]: [ERROR] [we-rm] did not find locale for language: English
[63]: [ERROR] [we-rm] did not find MainUIProduct class!
```
And watchdog is issuing lots of 
``` 
Service was restarted, please check your mailcow installation. 
```
Any idea on how to fix this? Google is not particularly helpful this time.
Thank you

**Comment by andryyy** [comment]
Hi, full logs are always more helpful.
I think some old code is mixed with new code. You could try to run `docker-compose down`, `git pull` and fix conflicts.

**Comment by catcun** [comment]
@andryyy  Thank you.
git pull updated some files, no conflicts. After both 
```docker-compose pull
docker-compose up -d --remove-orphans
```
and ./update.sh the problem continues. Here are the latest logs
[sogo-logs.txt](https://github.com/mailcow/mailcow-dockerized/files/2443572/sogo-logs.txt)

**Comment by andryyy** [comment]
Sure no conflicts?

I think your SOGo container is missing /usr/lib/GNUstep/SOGo/ which is an unnamed volume now. This is nothing I can reproduce here.

You could try to clean-up a bit:

```
# Stop mailcow
docker-compose down
# Cleanup unnamed vols
docker volume rm $(docker volume ls | awk '{print $2}' | egrep -o '[0-9a-f]{64}')
# Cleanup containers and images (all, not just mailcow)
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -a -q)
# Restart Docker
systemctl restart docker
# Pull images
docker-compose pull
# Up
docker-compose up -d
```

**Comment by catcun** [comment]
@andryyy 
It didn't work. I will try to setup a new server and then backup/restore. 
I will keep this open as I have another mailcow instance with the same problem and I want to try the cleanup routine and report back
Thanks!

**Comment by catcun** [comment]
After trying both git pull and the cleanup routine I can confirm that the problem still persists on the other mailcow instance. No conflicts on git pull.
Just for completeness:
```
CentOS Linux release 7.5.1804 (Core)

docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```
I checked directory contents and file size inside of /usr/lib/GNUstep/SOGo between a working debian 8 based mailcow and the non working CentOS 7.5 and they seem equal.
Could it be the very recent docker version and/or XFS on CentOS?

**Comment by andryyy** [comment]
What’s your umask? If it’s 0022, you could write a mail to info@servercow.de and I’ll check it remote.

**Comment by catcun** [comment]
I created a test VM with CentOS 7.5 fully up to date for a brand new installation. SOGo works normally
I guess that the next step would be a migration from the non working instance to a brand new CentOS server
So it is a problem with my installations.
Thank you for all the help
