### ISSUE TITLE
Why umask must be 0022?

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#1826]
For new install Mailcow, may I ask is it necessary to set umask to 0022? Can I set it to 027?

I know for updating mailcow it need 022.

thank you.

**Comment by andryyy** [comment]
It is not always "best practice" that a file is not readable by others. This is not something to give you additional security, some files _need_ to be read by others. Files that should not be read by others, are marked o-rwx by mailcow automatically.

Some config files you pull would be not readable by the user that runs a process inside a container, so o-r will break mailcow - or at least parts of it.

So when you install mailcow, don't mark every file as non-readable by others. :-)
