### ISSUE TITLE
Old content in mailbox Subscription file

### ISSUE THREAD

**Issue by Lucky88888** [mailcow/mailcow-dockerized#1827]
In the Subscription file in the root of the user's mailbox there are still some old annoying folders. 

I thought I will fix it by editing the file directly but there is no VIM or NANO present.
`docker-compose exec dovecot-mailcow /bin/bash`

Is there another way?

**Comment by andryyy** [comment]
You can either use IMAP to edit the subscriptions (recommended) or edit `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.tld/user/subscriptions`.

A mail client will most likely resubscribe to these folders anyway, so you should use the client to remove them.

You probably deleted folders by hand in the vmail directory? If yes: don't. Remove them via IMAP.
