### ISSUE TITLE
mysql just keeps crashing, watchdog restarts multiple containers

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1828]
After I've just updated to latest version, Mysql crashed and watchdog restarts it. But then it crash again. And as the mysql socket is not there, watchdog will restart other containers depending on mysql.
Logging:
`mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] mysqld (mysqld 10.2.18-MariaDB-1:10.2.18+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Warning] InnoDB: Using innodb_file_format is deprecated and the parameter may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2018-10-03 15:06:34 140036108179200 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Highest supported file format is Barracuda.
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: Waiting for purge to start
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] InnoDB: 5.7.23 started; log sequence number 54603141
mysql-mailcow_1      | 2018-10-03 15:06:34 140036097533696 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2018-10-03 15:06:34 140036097533696 [Note] InnoDB: Buffer pool(s) load completed at 181003 15:06:34
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [Note] Recovering after a crash using tc.log
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [ERROR] Bad magic header in tc log
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [ERROR] Crash recovery failed. Either correct the problem (if it's, for example, out of memory error) and restart, or delete tc log and start mysqld with --tc-heuristic-recover={commit|rollback}
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [ERROR] Can't init tc log
mysql-mailcow_1      | 2018-10-03 15:06:34 140036835198912 [ERROR] Aborting
`

If I remove tc.log file then I get the following line multiple lines:
`mysql-mailcow_1      | 2018-10-03 15:09:49 140162571695872 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade`

How to solve this issue?

**Comment by marrco** [comment]
run mysql_upgrade inside the container.

I had a similar issue some time ago trying to restore an old backup on a new setup.

**Comment by hunter-nl** [comment]
> run mysql_upgrade inside the container.
> 
> I had a similar issue some time ago trying to restore an old backup on a new setup.

When I run mysql_upgrade inside the container I get this:
`root@c216b7cfef07:/# mysql_upgrade
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
FATAL ERROR: Upgrade failed
`
Even when I try to specify root user and correct password it will fail.

**Comment by hunter-nl** [comment]
I just did a restore. Now it is working again.

**Comment by andryyy** [comment]
You would need to specify the user and password from the old installation.
