### ISSUE TITLE
Unable to modify recipient maps via Mailcow Web UI

### ISSUE THREAD

**Issue by vkukk** [mailcow/mailcow-dockerized#1829]
Hi

I need help debugging situation where mailcow-dockerized at some point allowed creating recipient maps, was updated in the past and then later we discovered that changing, adding or removing recipient maps via web ui is not possible anymore as user 'admin'.

In web UI log call is shown with 'danger access_denied' for user admin in role admin:
`["recipient_map","add","recipient_map_old":"foo@bar.com","recipient_map_new":"foobar@bar.com"},null]`
Removing existing recipient map created for testing was also not possible via web UI. It was possible to modify recipient_maps table in database when logging in with:
```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}
```
Any help to better debug this issue would be appreciated.

**Comment by andryyy** [comment]
I didn't break it. You broke it. 🤡

**Comment by vkukk** [comment]
How does mailcow-dockerized limit/check  'admin' user rights?

**Comment by andryyy** [comment]
Hm? Not exactly sure what you mean.
