### ISSUE TITLE
Invalid timezone

### ISSUE THREAD

**Issue by yazinsai** [mailcow/mailcow-dockerized#183]
When I setup mailcow, I specified the timezone `UTC+3` which appears to be invalid. Now I get the error `Warning: date(): Invalid date.timezone value 'UTC+3', we selected the timezone 'UTC' for now. in /web/inc/functions.inc.php on line 2582` on the dashboard.

How can I modify it? Tried setting `TZ=UTC` in `~/mailcow-dockerized/mailcow.conf` but it doesn't seem to be the config file that the dockerized mailcow reads from (the error persists)

**Comment by andryyy** [comment]
Hi,
It should accept all values you find [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) in the row "TZ".
When you change that value in mailcow.conf (which is correct), you need to restart the stack with `docker-compose restart`. Or recreate them if it fails: `docker-compose down && docker-compose up -d`

**Comment by broedli** [comment]
Ah, something for the documentation ...
