### ISSUE TITLE
whitelist all email addresses

### ISSUE THREAD

**Issue by julesdehenin** [mailcow/mailcow-dockerized#1832]
In the mailcow admin I was trying for a particular mailbox to whitelist all email addresses by entering *@* in the "Add item" field. When I try that, I receive an error message "Record has invalid format".
What I really want to do is turning off spam filtering for a particular mailbox but maybe this is not the correct way of doing it. I also did not find a way in the admin interface to turn off spam filtering for all mailboxes.

**Comment by andryyy** [comment]
You can use Rspamd settings maps from within the mailcow UI. There is a preset to disable all but DKIM and ratelimits.
You can use the same settings map settings to disable spam filtering for a specific mailbox by just replacing `authenticated = yes;` by something like `from = "/bla@bla/i";`.

**Comment by julesdehenin** [comment]
Thanks for your swift reply. I have been looking for info on how to define
settings for rspamd and did not found much except this:
https://rspamd.com/doc/configuration/settings.html.

I have the impression that your answer was meant to stop filtering outbound
messages but I want to be able to stop filtering inbound messages for
certain users. I thought that the following might work but in the rspamd UI
several symbols still get values for inbound mails even with the below high
priority setting which means that at least rspamd still uses CPU time to
calculate scores even if the setting tells that the user wants spam:
  additional_settings_3 {
    priority = 100;
    rcpt = "thisuserwantsallinboundmail@example.com";
    want_spam = yes;
}
Shouldn't the above setting de facto switch of all scanning of mails sent
to "thisuserwantsallinboundmail@example.com"?




Op do 4 okt. 2018 om 08:37 schreef André Peters <notifications@github.com>:

**Comment by julesdehenin** [comment]
I think I found the solution to my previous question. I need to add the
rcpt as a regular expression:
additional_settings_3 {
    priority = 10;
    rcpt = "/thisuserwantsallinboundmail@example\.com
<thisuserwantsallinboundmail@example.com>/i";
    want_spam = yes;
}
and this actually turns off spam filtering to user
thisuserwantsallinboundmail@example.com as can be verified in the rspamd
interface!

Op do 4 okt. 2018 om 08:37 schreef André Peters <notifications@github.com>:

**Comment by julesdehenin** [comment]
Just one last question on the setting
  traps {
    priority = 9;
    want_spam = yes;
  }
From what I understood rspamd tries settings in descending priority and if
there is a match that setting is used. In the default setting their is just
the watchdog setting and the above traps setting. The watchdog setting is
not triggered for a typical user so that means that the traps setting is
triggered meaning that everybody wants spam? I'm clearly misunderstanding
something here. So my main question is what is the traps setting for and
when is it applied and why is it not applied in the standard settings setup
of rspamd in mailcow?

Op do 4 okt. 2018 om 08:37 schreef André Peters <notifications@github.com>:

**Comment by andryyy** [comment]
Hey, your setting should be fine, yes, I don't think you need the full match, ` rcpt = "/thisuserwantsallinboundmail@example\.com/i";` should be enough.

Settings are not applied by priority, check the docs you linked. :-) They only apply when multiple settings match. When multiple settings match and they share the same priority, Rspamd decides by occurrence (first come, first serve).

You need at least one match list, like a rcpt, from, ip, etc. You could try `ip = 0.0.0.0/0;` (untested) to match all.

**Comment by julesdehenin** [comment]
I rechecked the documentation of rspamd and this is what they tell:
*Rules with greater priorities are matched first. From version 1.4 Rspamd
checks rules with equal priorities in alphabetical order. Once a rule
matches only that rule is applied and the rest are ignored. *
Also the picture lower on that page
https://rspamd.com/doc/configuration/settings.html seems to suggest that
first the settings with highest priority are checked and once a setting
applies no other setting is tested for. Do I misinterpret?

Op do 4 okt. 2018 om 20:27 schreef André Peters <notifications@github.com>:

**Comment by andryyy** [comment]
Si, but the traps settings rule was missing a match. If you have two rules with a match, the rule with the higher priority is applied.
