### ISSUE TITLE
Is outgoing email checked by rspamd?

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#1834]
I had an issue a few days ago when a mailbox password was compromised and the account was used to send SPAM. Thanks to the Ratelimit the server wasn't blacklisted (thanks for Ratelimit!), but delivery suffered because of a poor IP reputation.
The issue was detected because the account started to receive Undeliverable messages in the Junk folder. Does that mean that outgoing email is not handled by rspamd?

**Comment by andryyy** [comment]
Yes, it is scanned, but you'd need to reduce the score of the symbol MAILCOW_AUTH in Rspamd UI.

This will not magically detect spam, how would it know? :-) But it probably helps a bit. Besides rate limits of course!
