### ISSUE TITLE
Not possible to add new domain

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#1835]
Hi, just updated and tried to add a new domain. It is not saved?! Same happens if I try to add a DKIM key to an existing domain. I click on save but it is not saved :-)

Can somebody confirm? Nothing in the logs...

Mario

BTW: Adding a new mailbox to an existing domain works?!

**Comment by andryyy** [comment]
Nope, clean your browser cache and it will work. There were many changes to JS.

**Comment by Skydiver84de** [comment]
Sorry Andre you are right of course! Thanks!
