### ISSUE TITLE
How to insert a catchall alias

### ISSUE THREAD

**Issue by xifi-kif** [mailcow/mailcow-dockerized#1836]
Hi, how can I add a catchall alias?
for example 
*@example.com -> myaddress@example.com

like here https://github.com/mailcow/mailcow-dockerized/issues/1555#issuecomment-404446358

**Comment by xifi-kif** [comment]
nevermind I found it >.<

**Comment by Viktova** [comment]
excuse me but where's the catch all alias located at? I'm doing the all@domain.tld as a alias for all the users

**Comment by MAGICCC** [comment]
Add a new alias and fill in only @example.org in the 'Alias address/es' box
There's even a hint below the box
>Full email address/es or @example.com, to catch all messages for a domain (comma-separated). mailcow domains only.

**Comment by Viktova** [comment]
thanks!
