### ISSUE TITLE
No IPv6

### ISSUE THREAD

**Issue by JustAB0x** [mailcow/mailcow-dockerized#1839]
Hello,

if installed mailcow on my new Server today and restored everything via backup. Both servers (new and old) run on Debian 9.5.
I followed the installtion instruction in the documention and restored the backup afterwards.

Now ACME ist telling me the following:

```
4.10.2018, 22:22:42 | Cannot match your IP NO IPV6 LINK against hostname myhostname.com (2a01:04f8:00a1:1336:0000:0000:0000:0003)
-- | --
4.10.2018, 22:22:42 | Found AAAA record for myhostname.com: 2a01:4f8:a1:1336::3 - skipping A record check
```

ip addr returns the following:
[PasteBin because its quite long](https://pastebin.com/Wjm4Px9A)

Thanks in advance.

**Comment by JustAB0x** [comment]
I also have 2 IPv4s connected to my server.
88.198.37.210 and 88.198.37.130 (changed for secruity reasons)
I set up mailcow to use 88.198.37.130 in snat and as the host. 
However acme is returning this once i disable my AAAA record:

```
4.10.2018, 22:41:10 | Cannot match your IP 88.198.37.210 against hostname myhostname.com(88.198.37.130)
-- | --
4.10.2018, 22:41:10 | Found A record for myhostname.com: 88.198.37.130
```

**Comment by andryyy** [comment]
Hi,

Is it a Hetzner Dingens Cloud? Can you check this, please? => https://github.com/mailcow/mailcow-dockerized/issues/1737#issuecomment-419405594

**Comment by JustAB0x** [comment]
Its a Hetzner Dedicated and no virtual adapters are in-use.

**Comment by JustAB0x** [comment]
and the /etc/network/interfaces contains the following and is the only interface conf active:
https://pastebin.com/HxKyVLwk
ofc once again changed for secruity.
The other ip adresses are later added with: 
`ip add add <ip>/<cidr> dev enp4s0`

**Comment by andryyy** [comment]
You can also use IPv6 SNAT, have you tried?

**Comment by JustAB0x** [comment]
@andryyy 
Yep tried it already.

**Comment by JustAB0x** [comment]
Just checked the netfilter logs. SNAT is applied correctly.

**Comment by JustAB0x** [comment]
smtp,pop3,submission,imaps and pop3s ports are used on the ipv6 assign to mailcow. Just ACME is having problems.

**Comment by andryyy** [comment]
What's the output of `docker-compose exec php-fpm-mailcow curl ip6.mailcow.email`?

**Comment by JustAB0x** [comment]
@andryyy 
Output:
```
root@hostname /opt/mailcow-dockerized # docker-compose exec php-fpm-mailcow curl ip6.mailcow.email
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
```

**Comment by Fytcher** [comment]
fyi: just out of curiosity i tried the same command with ping and it returned a successful ping

**Comment by JustAB0x** [comment]
I don't know why that should be the problem source but my server as an dedicated Intel NIC. Could that cause such problems?

**Comment by JustAB0x** [comment]
@andryyy any suggestions? Kinda in a hurry since my old server runs out today and my only server left is my new one that isnt working.

**Comment by JustAB0x** [comment]
ip's are now added on startup in /etc/network/interfaces with:
`up ip addr add <ip>/<cidr> dev enp4s0`
still not fixed, also reinstalled docker multiple times.

**Comment by JustAB0x** [comment]
Just stopped using ipv6 altogether.
Still getting issues with rspamd...
![image](https://user-images.githubusercontent.com/19808218/46917476-0212de80-cfc8-11e8-9c8f-53703167cee4.png)

**Comment by andryyy** [comment]
Restart unbound-mailcow, that will fix it.
