### ISSUE TITLE
Tag buttons and encryption buttons not working

### ISSUE THREAD

**Issue by tsmeets2** [mailcow/mailcow-dockerized#1841]
Probably I am missing something, but before the update I could switch these buttons. But after the update I can not. Can somebody please explain me what I am missing?

![example](https://user-images.githubusercontent.com/43742132/46527325-2d435280-c891-11e8-8d42-19c985b4d54b.png)

**Comment by andryyy** [comment]
Can you please clean your browsers cache? We changed a lot in the JS code. :-)

**Comment by tsmeets2** [comment]
Okay will try

**Comment by tsmeets2** [comment]
It is still not working

**Comment by tsmeets2** [comment]
But if this is an isolated problem with only my setup than I will look further into the code to find the answer. So my question is, Are there others having the same issue?

**Comment by andryyy** [comment]
Check the demo, it works and is known when the cache is not cleaned correctly. Wipe _all_ data and close your browser.

**Comment by tsmeets2** [comment]
Well I tried cleaning all, but it is not working. Also tried different browsers. But I will investigate what the problem is and fix it on my own. Thx for the fast support. I forgot that i could test it with the demo install. Good answer!
