### ISSUE TITLE
imap_idle_notify_interval

### ISSUE THREAD

**Issue by levinuss** [mailcow/mailcow-dockerized#1842]
Hey,
according to [this](https://www.kuketz-blog.de/k-9-mail-akkuverbrauch-bei-imap-push-via-dovecot-reduzieren/) (german) source dovecots default setting for the `imap_idle_notify_interval` setting is at 2min which can be changed to 29min to reduce battery consumption on mobile devices. [RFC2177](https://tools.ietf.org/html/rfc2177) recommends to "re-issue it at least every 29 minutes". Can this safely added to the default mailcow dovecot config or is there something contradicting it? Another alternative could be a explanation in the docs.

**Comment by andryyy** [comment]
This is great for mobile devices, but I don’t really want this to be default in mailcow. I don’t know how much this affects other clients and especially push intervals/timeouts. 

We can add it to the docs. That would be cool. PR anybody? :-)

**Comment by levinuss** [comment]
I will try to write something :)

**Comment by andryyy** [comment]
Awesome. Thanks!

**Comment by mitchellurgero** [comment]
Mail clients can change this on their end or use Mobile PuSH (where supported) for notifications instead as well.

**Comment by levinuss** [comment]
But if the mail client is configured to do this e.g. every 20min he gets the idle notification from dovecot nevertheless. If that happens, the client has to wake up to process the information which consumes energy. Push (e.g. GCM) is not always an option and many mail apps just use the push provided by IMAP.

**Comment by mitchellurgero** [comment]
@levinus if the app in use is set up to not use PuSH then it will not receive those messages to wake up.

**Comment by levinuss** [comment]
mailcow/mailcow-dockerized-docs#106
