### ISSUE TITLE
Timeout bei Verbindung/ Timeout on connection

### ISSUE THREAD

**Issue by Badetuch** [mailcow/mailcow-dockerized#1844]
Guten Tag

English Translation: https://hastebin.com/iqefufanid.pl

Wenn ich mich auf meine Seite verbinde bekomme ich nur einen Timeout.
Ich habe alles nach dem Installation-Guide installiert, wenn ich: 

`docker-compose pull, docker-compose up -d `

eingebe, bekomme ich auch keinen Fehler (https://hastebin.com/bejobayuxu)
(Ich habe meinen Port zu 8082 geändert)

Währe sehr nett wenn mir jemand helfen könnte :)

LG Elia

**Comment by andryyy** [comment]
Mit Sicherheit noch eine Firewall aktiv.

**Comment by Badetuch** [comment]
Wenn ich "# netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995'" eingebe kommt nix.

**Comment by Badetuch** [comment]
Ups habe das # mit eingegeben. Da ist sind noch einige Firewalls aktiv. https://hastebin.com/usevewapum

Soll ich die alle Deaktivieren? Wenn ja wie?

LG Elia

**Comment by Zyplonox** [comment]
Poste mal den output von `docker ps`

**Comment by Badetuch** [comment]
https://hastebin.com/etaxuyohum

**Comment by Zyplonox** [comment]
output von `curl localhost:8082` ?
bzw bekommst du eine html Seite angezeigt?

**Comment by Badetuch** [comment]
https://hastebin.com/zazijiwuza

**Comment by Zyplonox** [comment]
Mhh schätze mal da ist was bei der Port-Änderung schief gegangen.
output von `docker logs mailcowdockerized_nginx-mailcow_1`  Und
`cat /opt/mailcow-dockerized/data/conf/nginx/listen_plain.active` ?

**Comment by Badetuch** [comment]
uiuiuiu https://hastebin.com/ohegemenuv

**Comment by Badetuch** [comment]
docker logs mailcowdockerized_nginx-mailcow_1: https://hastebin.com/ipafuqiwul
cat /opt/mailcow-dockerized/data/conf/nginx/listen_plain.active: https://hastebin.com/pikabudexe

**Comment by Zyplonox** [comment]
Mhh da warte am besten auf einen der Entwickler, ich kann mit dem Fehler von der Ferne leider nichts anfangen ^^

**Comment by Badetuch** [comment]
:(

**Comment by Badetuch** [comment]
Danke trotzdem

**Comment by Braintelligence** [comment]
Ist das normal, dass ich da ein Apache2 auf Port 80 sehe? Sollte hier nicht alles über nginx laufen?

**Comment by Braintelligence** [comment]
Der bad gateway könnte auch daher kommen, dass irgendwas mit der mariadb nicht stimmt (da stand restarting) und daher die Mailcow ui nicht greift.

**Comment by Badetuch** [comment]
Ich bin mir sehr sicher das es an der Firewall liegt da ich sehr viele Ports habe die blockiert wurden das mache ich morgen

**Comment by Zyplonox** [comment]
> 
> 
> Der bad gateway könnte auch daher kommen, dass irgendwas mit der mariadb nicht stimmt (da stand restarting) und daher die Mailcow ui nicht greift.

Das hatte ich ganz übersehen, klar hier sollte man wohl zuerst ansetzen:

output von `docker logs mailcowdockerized_mysql-mailcow_1` ?

> Ich bin mir sehr sicher das es an der Firewall liegt da ich sehr viele Ports habe die blockiert wurden das mache ich morgen

ist die firewall denn direkt auf dem Server geschalten? Wenn ja `iptables-save ` solltest du aber vielleicht nicht hier posten ^^

**Comment by Badetuch** [comment]
https://hastebin.com/awuzuyewux

**Comment by Braintelligence** [comment]
No space left on device. Ist das nicht selbsterklärend? :)

**Comment by Badetuch** [comment]
Ja, komischerweise habe ich mir danach 10GB mehr für meinen Server gekauft und es Zeigt das immernoch an. Ich werde meinen Server einfach komplett neu ausfetzen.

**Comment by Zyplonox** [comment]
Musst du wahrscheinlich auch erst mal partitionieren oder? Mit `fdisk -l ` siehst du alle Festplatten und Partitionen und mit `df -h` kannst du sehen wo wie viel Speicher genutzt/verfügbar ist.

**Comment by Conan179** [comment]
Mit Gparted, kan man Partitionen vergrössern, ohne neu formatierung ;)

**Comment by Zyplonox** [comment]
> 
> 
> Mit Gparted, kan man Partitionen vergrössern, ohne neu formatierung ;)

Wer redet hier von formatieren?

**Comment by Conan179** [comment]
>Ich werde meinen Server einfach komplett neu ausfetzen.

Badetuch :)

edit: tschuldigung, falscher namen kopiert

**Comment by Zyplonox** [comment]
> 
> 
> > Ich werde meinen Server einfach komplett neu ausfetzen.
> > Zyplonox :)

Achso ^^

**Comment by Badetuch** [comment]
Hi, ich habe alles installiert und es geht nun (fast) alles, ich kann E-Mails versenden, aber keine Empfangen?!
