### ISSUE TITLE
Domain mail address whitelist is broken

### ISSUE THREAD

**Issue by MaxXor** [mailcow/mailcow-dockerized#1845]
When checking the domain settings the whitelisted mail addresses are not shown anymore. This maybe applies to the blacklist as well, didn't check it.

![whitelist](https://user-images.githubusercontent.com/7271470/46541218-a6f03600-c8bb-11e8-8ded-00f8a08701c3.png)

**Comment by andryyy** [comment]
Very good catch, thank you.
