### ISSUE TITLE
Mail to all user

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1846]
Is it possible to send a mail to all users ?
For informations vor stuff like that?

**Comment by chriscroome** [comment]
Is this a dupe of #842 ?

**Comment by ghost** [comment]
Yes sorry.

Am 5. Oktober 2018 19:34:07 MESZ schrieb Chris Croome <notifications@github.com>:
>Is this a dupe of #842 ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mailcow/mailcow-dockerized/issues/1846#issuecomment-427442163

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by andryyy** [comment]
Closing this as duplicate, will integrate it asap.
