### ISSUE TITLE
Nginx should redirect to https

### ISSUE THREAD

**Issue by D3luxee** [mailcow/mailcow-dockerized#1848]
Nginx should redirect to https to avoid unencrypted access to mailcow. 

I've already created a pull request: #1847

**Comment by Braintelligence** [comment]
Did you read the documentation? You could have at least copypasted the recommended server block for your PR.

**Comment by Braintelligence** [comment]
Here's what you're looking for: https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

Everyone is free to read the documentation before installing and creating pull requests for known configuration demands.

As to why @andryyy prefers to leave this setting to the user, I can't tell, but I'm pretty sure there's at least a debatable reason for it. That being said I use this block for all of my Mailcow instances.
