### ISSUE TITLE
Aliases: Domain Dropdown not working

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#1849]
There's only "All Domains"

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/46569434-41508800-c955-11e8-928e-88cbfde67a5c.png)

Can you check your cache? And please run update again.

**Comment by patrick7** [comment]
Still not workling. However after I click on "refresh" on the right, I see the domains in the dropdown?

**Comment by andryyy** [comment]
Yes, you are right.

Can you try and add in `data/web/js/mailbox.js` after line 10 (which is `json: false`) this? => `async: false,`

```
        jsonp: false,
        async: false,
        error: function () {
```

But you need to clean your browser cache for it to be loaded.

**Comment by patrick7** [comment]
@andryyy Works

**Comment by andryyy** [comment]
Thanks, I will try to find a better solution but fix it with an async call for now.
