### ISSUE TITLE
[Show active user sieve filter]

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#1855]
If I login as a User and click "[Show active user sieve filter]", it does not show sieve filters created by SOGo.

**Comment by andryyy** [comment]
Check if it’s active (checked) in SOGo

Mit besten Grüßen
André Peters

**Comment by patrick7** [comment]
@andryyy Filters are checked. Also I see the config in /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain/user/sieve

**Comment by andryyy** [comment]
Thanks, I fixed it.
