### ISSUE TITLE
client TLS configuration problem

### ISSUE THREAD

**Issue by ruffy91** [mailcow/mailcow-dockerized#1856]
when trying to send an email to dkimvalidator.com I get following messages in the postfix log:

>10/6/2018, 9:44:32 PM | info | BE74D3E832:  to=<U8cU4MgC82Mwb7@dkimvalidator.com>, relay=none, delay=0.34,  delays=0.12/0.03/0.18/0, dsn=4.7.5, status=deferred (client TLS  configuration problem)
10/6/2018, 9:44:32 PM | warning | warning: TLS policy lookup for dkimvalidator.com/31045262.in2.mandrillapp.com: client TLS configuration problem
10/6/2018, 9:44:32 PM | warning | warning: TLS policy lookup for dkimvalidator.com/31045262.in2.mandrillapp.com: client TLS configuration problem
10/6/2018, 9:44:32 PM | warning | warning: smtp_tls_policy_maps, next-hop destination "dkimvalidator.com": policy table lookup error
10/6/2018, 9:44:32 PM | warning | warning: proxy:mysql:/opt/postfix/conf/sql/mysql_tls_policy_override_maps.cf lookup error for "dkimvalidator.com"
10/6/2018, 9:44:32 PM | warning | warning: TLS policy lookup for dkimvalidator.com/31045262.in1.mandrillapp.com: client TLS configuration problem
10/6/2018, 9:44:32 PM | warning | warning: TLS policy lookup for dkimvalidator.com/31045262.in1.mandrillapp.com: client TLS configuration problem
10/6/2018, 9:44:32 PM | warning | warning: TLS policy lookup for dkimvalidator.com/31045262.in1.mandrillapp.com: client TLS configuration problem
10/6/2018, 9:44:32 PM | warning | warning: smtp_tls_policy_maps, next-hop destination "dkimvalidator.com": policy table lookup error
10/6/2018, 9:44:32 PM | warning | warning: proxy:mysql:/opt/postfix/conf/sql/mysql_tls_policy_override_maps.cf lookup error for "dkimvalidator.com"
10/6/2018, 9:44:32 PM | warning | warning:  mysql:/opt/postfix/conf/sql/mysql_tls_policy_override_maps.cf: query  failed: Table 'mailcow.tls_policy_override' doesn't exist

**Comment by andryyy** [comment]
Open mailcow UI, it needs to init the database.

**Comment by ruffy91** [comment]
Opened the TLS policy maps TAB.
Mail was successfully sent now.
Thanks

**Comment by normanu** [comment]
I updated to the latest and also get these errors.
Logged in to the webclient, opened the TLS policy maps TAB, still nothing.
Added a policy, is not showing up in the GUI and still same errors.

Can't send mail out currently, what can I do?

UPDATE: fixed it, had to manually create the config file and put he information in.

**Comment by andryyy** [comment]
That's strange. You may try git pull and fix conflicts, if any.
