### ISSUE TITLE
Feature request: Notify on update

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1857]
Hello together,
wouldn't it be nice if Mailcow could notify the admin by mail or when login into the admin ui that a update is available and that he should run the .update.sh?

This would truly be awesome. :)

**Comment by Braintelligence** [comment]
Why don't you just subscribe to https://mailcow.email/feed/ ? Or alternatively to https://mailcow.email/category/news/feed/

**Comment by ntimo** [comment]
Because I don't wait to have to use a RSS reader? This is a outdated and old technology. Why not just add it to the UI this way it would be much more transparent and easier.

**Comment by Braintelligence** [comment]
Feedly.com would beg to differ pretty hard. RSS is widely used on the net, I have no idea how you're backing your claim. 
That being said: you'd rather have an online rss reader within the Mailcow ui?

**Comment by Conan179** [comment]
Ich benutzte momentan noch Opera Mail für Email, bin aber momentan dabei eine alternative zu finden.
Für RSS habe zwar den FeedDemon gefunden, leider wird der auch nicht mehr weiter entwicket, Feedly reitz mich nicht, weil es eine Webseite ist und kein Windows programm, wo ich städig im hintergrund lauffen lassen kann.

**Comment by MAGICCC** [comment]
We had https://github.com/mailcow/mailcow-dockerized/commit/6ef521e8251b432cc4f87b06413624aead49cd80 and there's https://github.com/mailcow/mailcow-dockerized/issues/1429

**Comment by ntimo** [comment]
@Peter why is https://github.com/mailcow/mailcow-dockerized/commit/6ef521e8251b432cc4f87b06413624aead49cd80 not shown in the UI?

**Comment by MAGICCC** [comment]
@ntimo It was removed due to my issue
