### ISSUE TITLE
mail_crypt_plugin error in latest version

### ISSUE THREAD

**Issue by markirb** [mailcow/mailcow-dockerized#1859]
Hi,

earlier today i had some issues trying to update to the latest mailcow.
After doing my usual upgrade routine my dovecot-mailcow kept beeing unhealthy with the error
`dovecot-mailcow_1    | sievec: Fatal: mail_crypt_plugin: mail_crypt_global_public_key: Couldn't parse public key: Unknown key format`

The fault is that my crypt container already has a  ecpubkey.pem / ecprivkey.pem but with length zero, so the following line did not apply
https://github.com/mailcow/mailcow-dockerized/blob/2af2f7836d4b882eda6eb2854520d76afa95a3b0/data/Dockerfiles/dovecot/docker-entrypoint.sh#L120

I looked around my backups and i saw that these zero-length files date back to September 2017.

Do not know if anyone of you out there has the same issue, or why those files are there...
But if anyone has the same problem, maybe above lines should extend to check for length zero?

**Comment by andryyy** [comment]
"if -s" should work here.

**Comment by andryyy** [comment]
Can you check the fix?

**Comment by markirb** [comment]
Yup, works fine for me, for both cases (file 0 or file not there). Thanks
