### ISSUE TITLE
Error in Backend after Update

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#186]
Hi,
I have just updated and now I get the following error messages when I go into the backend (mailbox.php):
```
Cannot draw domain table
Cannot draw resource table
Cannot draw mailbox table
Cannot draw alias table
Cannot draw alias domain table
```
I hope you can help me.
Thanks a lot

![mailcow](https://cloud.githubusercontent.com/assets/25428336/24929264/a6ccaa8e-1f05-11e7-8602-1bf410ed5628.png)

**Comment by andryyy** [comment]
Hi,
I guess you either forgot to update the images or the repository files (git pull etc.). Can you check it?

**Comment by rebek86** [comment]
All files and images are up to date

**Comment by andryyy** [comment]
The nginx configuration, too? You should be able to open `https://your.domain.tld/api/v1/domain/all`.

**Comment by rebek86** [comment]
Slowly I think I'm going crazy. :flushed: I have not changed anything and today everything is running. Could here maybe the browser cache caused the error or is this nonsense?

p.s. I can open your link.

**Comment by tehXor** [comment]
We had this after the recent merge as well, however it solved itself after about 2 minutes and another refresh. So maybe this really was a browser cache problem but in our case a very minor one.

**Comment by rockstarcloud** [comment]
I had the same error with a clean installation. I delete my browser cache and it works.

**Comment by broedli** [comment]
Errors like `cannot draw XYZ table` mostly come from browser cache and occur when mailcow updates it's JS.

You may follow one of many guides on the internets on how to do that. Here is one: https://kb.iu.edu/d/ahic#desktop

I'm closing this issue as it's been resolved.
