### ISSUE TITLE
[Feature Request] Add global administrators from GUI

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1861]
Hi, i would like to suggest a new feature such as the possibility to add a global administrator right from GUI. It is possible now for domain administrators so i suppose would not be too difficult to implement also for global administrators.
Thanks!

**Comment by andryyy** [comment]
That's a bold conclusion. ;-) It is not that easy, but doable, yes.

And it is a duplicate of #284

**Comment by lucianlazar1983** [comment]
Thanks and sorry about my assumption ;)

**Comment by andryyy** [comment]
It was easier than expected, you were right. I will push it soon.
