### ISSUE TITLE
Subfolder not callable

### ISSUE THREAD

**Issue by sebiweise** [mailcow/mailcow-dockerized#1862]
-- English
Hello. Unfortunately I can't open folders,

unfortunately I cannot call folders/subfolders with a special character in the name. The names are simply cut off after the special character incl. special characters and provided with a black folder symbol. I can neither click these nor interact with them using the three small dots. Can anyone help me? Because I now have the folders in my mailbox and can neither delete them nor look at the mails that are in these folders.

Translated with www.DeepL.com/Translator

-- German

Hallo,

leider kann ich Ordner/Unterordner mit einem Sonderzeichen im Namen nicht aufrufen. Die Namen werden einfach nach dem Sonderzeichen inkl. Sonderzeichen abgeschnitten und mit einem schwarzen Ordnersymbol versehen. Ich kann diese weder anklicken noch damit mittels der drei kleinen Punkte interagieren. Kann mir einer helfen? Denn ich habe jetzt die Ordner bei mir im Postfach und kann diese weder löschen, noch die Mails anschauen, die in diesen Ordnern liegen.

**Comment by sebiweise** [comment]
Change title

**Comment by andryyy** [comment]
In SOGo? Hast du dort parallel einen Bug Report aufgemacht? Solange kannst du sie via IMAP Client löschen.

**Comment by sebiweise** [comment]
@andryyy Ah stimmt das gehört ja nicht unbedingt zu Mailcow danke für den Hinweis. Dann werde ich das mal bei SOGo hinlegen. Danke für den Tipp mit dem IMAP-Client auf die Variante bin ich gar nicht gekommen da versuche ich es mal den Ordner umzubenennen.

**Comment by andryyy** [comment]
Berichte gerne hier. :-)
