### ISSUE TITLE
GMX.NET Relayhost - Frage

### ISSUE THREAD

**Issue by roswitina** [mailcow/mailcow-dockerized#1865]
Kann mir bitte jemand erklären, wo ich einen Denkfehler habe?

Ich habe "mailcow-dockereized" in meinem interen Netz installiert, um darauf mehrere Mail-Domains zu hosten. Ua. habe ich eine Mailadresse von xx@gmx.net und dazu in "mailcow-dockerized" eine Domain gmx.net angelegt. In den Einstellungen habe ich 1. Relay-Domain und 2. Alle Empfänger-Adressen relayen aktiviert. Zudem habe ich unter Konfiguration -> Relayhost einen Relayhost (smtp meines ISP) eingerichtet. Diesen Relayhost habe ich in den Domain-Einstellungen von "gmx.net" aktiviert. Zudem hab eich im Netz einen Drucker/Scanner, der mir ua das Versenden von PDFs erlaubt. Für diesen habe ich einen lokalen Benutzer im "mailcow-dockerized" eingerichtet.

Wenn ich nun über meinen Drucker/Scanner ein Mail an meine xx@gmx.net Adresse schicken will, benutzt "mailcow-dockerized" nicht meinen eingerichteten Relayhost meines Providers, sondern verbindet offensichtlich direkt mit dem MX von GMX, der meine IP nicht annimmt. Die Fehlermeldung schaut folgend aus:

8248B7E04E4: to=<xx@gmx.net>, relay=mx00.emig.gmx.net[212.227.15.9]:25, delay=4029, delays=4027/0.05/1.9/0, dsn=4.0.0, status=deferred (host mx00.emig.gmx.net[212.227.15.9] refused to talk to me: 554-gmx.net (mxgmx012) Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record. 554 For explanation visit http://postmaster.gmx.com/en/error-messages?ip=1.2.3.4&c=rdns)

Ich bilde mir ein, das dies aber schon einmal funktioniert hat und im Laufe von etlichen Updates jetzt nicht mehr so läuft, wie ich es gewohnt war.

**Comment by Braintelligence** [comment]
Wenn ich das richtig interpretiere klingt das so, als hätte GMX keinen Bock im Namen einer IP-Adresse Mails zu versenden, die nicht im PTR record für die relayhost-domäne hinterlegt ist, könnte mich aber auch irren. Bist du sicher, dass das überhaupt mal funktioniert hat?

EDIT: Wie sieht denn der PTR record für deine IP-Adresse aus? Gibt es den überhaupt?
EDIT2: Und hast du auch eine feste IP-Adresse? Sonst wird das ganze laut deinem eigenen Link nämlich nichts!
EDIT3: Obiges gilt ggf. eher für deinen ISP; einmal prüfen wie es da um die PTR records steht.
EDIT4: Kannst du mich auf die richtige Stelle in der Fehlermeldung verweisen, woraus die direkte Verbindung ersichtlich wird? Ich sehe erstmal nur einen Hinweis auf einen inakzeptablen PTR record, aber nicht darauf *wessen* IP-Adresse gemeint ist (deine oder die deines ISPs). Nimmst du diese Tatsache daraus, dass es die Fehlermeldung deines eigenen Mailer-Daemons ist?

Sobald abschließend klar ist, ob hier von deiner oder der IP-Adresse des ISP die Rede ist, hätte ich ein paar Ideen.

**Comment by roswitina** [comment]
Ich habe eine feste IP-Adresse.
Ich glaube, dass ich mich missverständlich ausgedrückt habe.

Ich bin immer davon ausgegangen, dass man bei Benützung eines Relay-Host (ist in meinem Fall der SMTP meines Poviders samt Authentifizierung [Username:Passwort]) das Versenden der betreffenden Mails über diesen erzwingen kann. Das Mail nimmt daher folgenden Weg: MailClient -> Mailcow -> Relayhost des eigenen ISP -> SMTP der Empfänger-Domain. Dadurch schaut es für die Empfänger-Domain so aus, als wenn das Mail von einem reellen SMTP kommt.

Ich war bisher auch der Meinung, dass ich dies mit der entsprechenden Einstellung bei Mailcow so erreiche und bilde mir ein, dass dies schon funktioniert hat.

Liege ich hier komplett falsch?

Bzgl PTR - Record: Brauche ich den im geschilderten Fall überhaupt? Ich betreibe ja keinen Mail-Server der erreichbar sein muss. Ich hole ja meine Mails mit iMAPSYNC nur ab und ordne sie ein.

**Comment by Braintelligence** [comment]
Ich sehe kein Problem in dem Konstrukt `MailClient -> Mailcow -> Relayhost des eigenen ISP -> SMTP der Empfänger-Domain`, habe sowas aber noch nie probiert.

Es wäre halt aber interessant zu wissen, ob die Fehlermeldung tatsächlich für deine IP-Adresse oder die IP-Adresse deines ISPs gemeint war. Bei Ersterem müssten wir schauen was bei mailcow oder deiner Konfiguration schief läuft, bei Letzterem hat dein ISP vielleicht geschludert.

**Comment by roswitina** [comment]
Es war meine statische IP, die hier angeführt war. Ich habe sie durch 1.2.3.4 ersetzt. Der Relayhost wird gar nicht benutzt, obwohl er in der Domain eingestellt ist.

**Comment by Braintelligence** [comment]
Wärst du interessiert daran, das Ganze über deine statische IP zu lösen? Offenbar existieren hierfür auch Möglichkeiten, wenn ich ein paar Blog-Einträge im Netz richtig interpretiere, die sich auch um dieses Problem drehen (bei bewusster direkter Relayhost-Geschichte).

Was sagen denn die postfix logs zu dem Thema, wenn du versuchst eine Mail entsprechend zu senden?

**Comment by roswitina** [comment]
Hier die Postfix-LOGs vom letzten Versand:


8.10.2018, 18:25:17 | info | 29FA47E04EC:  to=<aa.bb@gmx.net>,  relay=mx00.emig.gmx.net[212.227.15.9]:25, delay=590,  delays=589/0.03/0.98/0, dsn=4.0.0, status=deferred (host  mx00.emig.gmx.net[212.227.15.9] refused to talk to me: 554-gmx.net  (mxgmx017) Nemesis ESMTP Service not available 554-No SMTP service  554-Bad DNS PTR resource record. 554 For explanation visit  http://postmaster.gmx.com/en/error-messages?ip=1.2.3.4&c=rdns)
-- | -- | --
8.10.2018, 18:25:17 | info | 29FA47E04EC:  host mx01.emig.gmx.net[212.227.17.5] refused to talk to me: 554-gmx.net  (mxgmx115) Nemesis ESMTP Service not available 554-No SMTP service  554-Bad DNS PTR resource record. 554 For explanation visit  http://postmaster.gmx.com/en/error-messages?ip=1.2.3.4&c=rdns
8.10.2018, 18:25:16 | info | 29FA47E04EC: from=<test@domain.net>, size=2900, nrcpt=1 (queue active)

**Comment by roswitina** [comment]
Das hier: --> https://github.com/mailcow/mailcow-dockerized/commit/db2d0fa21bbb498523ccdcd24de7f505a515492b habe ich früher einmal benutzt und es hat funktioniert.

**Comment by Braintelligence** [comment]
Dein ISP taucht also gar nicht erst auf? In dem Fall würde ich mal auf @andryyy warten, ob er eine Idee hat :/... Seit dem von dir erwähnten Commit wurde das Thema relayhost mehrmals angefasst: https://github.com/mailcow/mailcow-dockerized/search?q=relayhost&type=Commits 
Falls du eine Snapshot-Funktion für deine Mailcow-Instanz besitzt wäre vielleicht eine Idee den Relayhost neu zu konfigurieren?

**Comment by roswitina** [comment]
Werde ich machen. Ich glaube ich habe irgendwo noch ein Backup. 

Ich habe das auch so verstanden, dass der Relayost aussen vor gelassen wird.

Auf jeden Fall DANKE.

**Comment by Braintelligence** [comment]
Nicht dafür, einer der Member hat bestimmt eine bessere Idee :).

**Comment by mkuron** [comment]
> dazu in "mailcow-dockerized" eine Domain gmx.net angelegt

Auch wenn das im Prinzip funktionieren könnte, ist es nicht empfehlenswert, Domains einzutragen, die man nicht kontrolliert. Es ist zumindest nichts, das wir testen würden und ich kann mir einige Stellen vorstellen, an denen es evtl. problematisch ist.

**Comment by roswitina** [comment]
OK. Danke. Vergessen wir das. War nur eine Frage.

Ich habe bisher so immer problemlos meine Mails verwaltet. Es geht mir dabei auch hauptsächlich darum, dass ich alle Mails an einem Platz habe und diese hier auch zentral sichern kann. Mit dem Versenden in der von mir beschriebenen Art und Weise hat es nie gehapert. Das von mir angeführte Script hat auf jeden Fall immer bestens funktioniert. 

Ich werde jetzt eine ältere Version testen und sollte diese so funktionieren, wie ich sie kenne, bleibe ich einfach dabei.

Das Thema hat sich für mich erledigt und kann geschlossen werden.

**Comment by roswitina** [comment]
NACHTRAG:
Ich habe jetzt nochmals ein bisschen mit dem Script getestet. Das macht jetzt was es meiner Meinung nach tun soll. Es veranlasst Postfix nach Einträgen in die main.cf die Mails an den Relayhost weiter zu leiten. Die Relayeinträge bei dem Domains habe ich entfernt.

Sollte ich irgendwelche RFCs verletzt haben, möge man mir das mitteilen. Ich will den ordentlichen Mailverkehr auf keinen Fall stören.

**Comment by Braintelligence** [comment]
Um das tun zu können wären die konkreten Änderungen am Code interessant. Soweit ich weiß musst du die Änderungen wegen der GPL Lizenz sowieso kommunizieren.

**Comment by roswitina** [comment]
Ich habe das ursprüngliche Script genommen und mit verschiedenen SMTP - Accounts getestet. Mich haben hauptsächlich die Einträge im Header interessiert und ob TLS funktioniert. Danach habe ich einer Account genommen und bin nun zufrieden wie es ist. Alle ausgehenden Mails werden über einer Relayhost versandt. Ich habe keine Probleme mehr, dass meine Mails nicht angenommen werden. Mehr wollte ich nicht. Ich wollte auch keine eigene Mail-Domain betreiben. Mich hat nur irritiert, dass die Relayhosteinstellungen, welche ich im UI gemacht habe, nicht genommen wurden. Ich habe da wohl etwas falsch verstanden.

**Comment by roswitina** [comment]
Kann mir bitte einer die die Funktioen

- Relay Domain
- Alle Empfänger Relayen und
- Relayhost (Einstellungen

erklären. Ich blicke da nicht durch. 

Ich habe eine Relayhost-Einstellung gemacht und diese auch getestet. Sie funktioniert. Jetzt ist es aber so, dass ich keine Einstellung finde (Relayhost aktiviert in den Domain Einstellungen), egal ob Relay Domain und/oder Alle Empfänger relayen aktive oder nicht (was die GUI halt zulässt), kein Email über den eingerichteten und aktivierten Relayhost verschickt wird. Jedenfalls läss sich das anschließend im Mail Header nicht feststellen.

Für was wird denn dann der Relayhost gebraucht? Wo habe ich einen Denkfehler? Ich bin komplett durcheinander......

Danke für jede konkrete Hilfe.

**Comment by mkuron** [comment]
Relayhost: an den werden alle ausgehenden Mails geschickt. Auch bekannt als Smarthost.

Relay domain: Mails sollen nicht auf diesem Mailcow landen, sondern an den nächsten MX übergeben werden, wenn dieser wieder erreichbar ist. Stichwort Backup MX.

Alle Empfänger relayen: standardmäßig nimmt der Backup MX nur Mails für Adressen an, die er kennt. Diese Option schaltet das ab.
