### ISSUE TITLE
Quarantine - Mailcow (not working)

### ISSUE THREAD

**Issue by Aidan16** [mailcow/mailcow-dockerized#1866]
I've been trying to get my quarantine system on mailcow to work for a while. For some odd reason, when a message gets rejected with rspamd, it doesn't save it in the quarantine section of my mailcow. I did check the settings of my quarantine to make sure that the limits were high enough, and they were. I cannot figure out this issue no matter how many threads I have looked at on this forum. Can you please help me?

I tried looking at the commit https://github.com/mailcow/mailcow-dockerized/commit/c6bcf322ffcac59b372dffc76050e3ce89de246f, but that didn't help me at all since that setting was already correct.

**Comment by mitchellurgero** [comment]
I thought quarantine was for messages with virus/malware in it?

**Comment by Aidan16** [comment]
No, it should quarantine messages that get rejected.
