### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Badetuch** [mailcow/mailcow-dockerized#1867]
Hey,

Wenn ich `docker-compose pull` eingebe kommt bei mir: https://hastebin.com/asugazijoz
Also habe ich mir 10GB mehr Speicher zu meinem Server hinzugebucht, jedoch kommt immernoch das selbe.

Hoffe mir kann jemand helfen.

LG Elia

**Comment by Braintelligence** [comment]
Hast du nach der Zubuchung auch die Partition erweitert, oder hast du jetzt einfach nur 10GB unformatierten Platz dazugekommen?

**Comment by Badetuch** [comment]
kp ich hab das bei meinen hoster einfach dazugebucht

**Comment by Braintelligence** [comment]
Das hat eigentlich rein gar nichts mit Mailcow zu tun, sondern ist ein allgemeines Problem der Administrator-Kategorie...

Du hattest vorher einen (wahrschl. virtuellen) Speicher mit X GB. Du hast 10GB dazugebucht, wodurch der "rohe" Speicherplatz nun bei X+10 GB liegt. Die von dir genutzte Partition ist aber weiterhin auf X GB formatiert, direkt danach schließt sich dann der neue, unformatierte Speicherplatz an.

Du kannst die bestehende Partition bspw. erweitern, indem du von einer GParted Live CD bootest, die Swap Wrapper Partition aufs neue Maximum vergrößerst, die Swap Partition dann innerhalb der Wrapper Partition ganz nach hinten verschiebst, die Wrapper Partition aufs Minimum schrumpfst und dann die Systempartition aufs Maximum vergrößerst. (So läuft das bei mir in meinem Hypervisor, wenn ich das QEMU Image vergrößere.)

**Comment by Badetuch** [comment]
Ok vielen Dank 👍
