### ISSUE TITLE
Feature Request: Postmaps via WebGUI

### ISSUE THREAD

**Issue by Schnookeuz** [mailcow/mailcow-dockerized#1869]
Hi André!
It would be great, if we could manage postmaps in the mailcow web Interface, so that for example all mails for one specific domain are routet to another mailserver.
In addition, it should be working this way, that every mail is still going through the "filtering process", so that at the end, mailcow is working as a kind of spamgateway for this particular domain/secondary mailserver. With all the options of white-/blacklists, TLS settings, filter settings and so on.

If it's already built in, then i cannot find it or can not imagine how to workaround the way to this. I realized the sending-way with mailcow as relay, but not the incoming way.

**Comment by Adorfer** [comment]
Adding "delivery via submission including auth&ssl" (i.e. to an exchange server) would make mailcow more versatile in some corporate environments. 
(architectures with outsourced IT departments and/and or hosted exchange are not in scope for discussion here.)

**Comment by marrco** [comment]
this is related to https://github.com/mailcow/mailcow-dockerized/issues/56

**Comment by hunter-nl** [comment]
@andryyy This would be great. Then I can provide the "filtering" and route to/from the different development/test mailservers like Exchange, Domino, etc. As now SoGo can be disabled for the user, so they can configure the rest of the "filtering" options without the possibility to use SoGo. The postqueue UI has been implemented also. So "delivery via submission including auth&ssl" feature is the next one on my wishlist.

**Comment by mkuron** [comment]
It seems like @andryyy has started working on this feature: https://github.com/mailcow/mailcow-dockerized/commit/b99820d0117e364dec337915dde7d697116ee532#diff-849fb1b93a046866d89f303a7e5f0275

**Comment by mkuron** [comment]
This feature is now fully implemented and can be configured in "Transport Maps" on the "Routing" tab in the admin interface. I have confirmed that it works, though currently you can't have multiple destinations (domains) with the same nexthop (when you add an entry, you get a message saying that it interferes with an existing nexthop). Perhaps @andryyy can comment on why that limitation exists and how it could be removed.

**Comment by andryyy** [comment]
It should accept the same next hop as long as the credentials match, that's a bug I have not fixed.

Other than that it should be fine. It was tricky though. Imagine adding a transport map entry "[host]:123". Postfix always looks up credentials for "host" first, _then_ proceeds to check for "[host]:123". This makes it impossible to have 2 transport map entries like "host" and "[host]:123" at the same time with different credentials. What works: 2 entries like "[host]:123" and "[host]:321".

**Comment by mkuron** [comment]
I had actually tried to implement the same feature about two months ago and never got around to finishing it. My main problem there too was credential lookup...

**Comment by andryyy** [comment]
It sucks so much. I was about to drop it 3 times.
Plus having a sender-dependent transport map makes it even worse. I had to create a smtp_via_transport_maps service so it doesn'interfere with the existing passwd maps.

I think I can remove that second check in PHP, that should fix the bug above.

**Comment by andryyy** [comment]
Turns out my fix was stupid. I hope to fix it in a bit...
