### ISSUE TITLE
sogo subfolders not showing up

### ISSUE THREAD

**Issue by a-schaefers** [mailcow/mailcow-dockerized#187]
When I create a subfolder using sogo (inbox>new subfolder) it does not show up within sogo, but does show up in thunderbird, so the creation works, but it appears sogo does not display the subfolders that it creates?

Fresh AWS ec2 ubuntu 16.04 install

**Comment by andryyy** [comment]
Hi,
You may need to click the folder icon left to INBOX. :-)

**Comment by bastianccm** [comment]
Hi,

is it possible to have the folders expanded by default?

(The feature itself works out of the box for me, on Ubuntu 16.04 install)

**Comment by broedli** [comment]
@thebod this is a feature request you should direct at SOGo. 

@a-schaefers is your issue still occurring or can we close this issue?

**Comment by liquidat** [comment]
@andryyy I just spent more than half an hour, panicking, because I did not figure that out on my own. Thanks for your life saving comment here. ;)
