### ISSUE TITLE
Configure Nginx stub_status

### ISSUE THREAD

**Issue by ardichoke** [mailcow/mailcow-dockerized#1872]
It would be useful for monitoring purposes if a stub_status endpoint was available for nginx. Could also add a configuration option to specify the IP address/range to allow stub_status access from.

**Comment by andryyy** [comment]
Hey, we use the official image, but it seems to be build with `with-http_stub_status_module`. So you can just add a new site or extend the default site like this: https://mailcow.github.io/mailcow-dockerized-docs/u_e-nginx/
