### ISSUE TITLE
very large mail folders results in IMAP/SoGo issue

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1874]
In SoGo documentation it notes this issue I have:

> If you have very large mail folders (thousands of messages), you will need to adjust the word size of your IMAP server. In Dovecot, the parameter to increase is "imap_max_line_length" while under Cyrus IMAP Server, the parameter is "maxword". We suggest a buffer of 2MB.

@andryyy Can you add imap_max_line_length into dovecot.conf into section
`protocol imap {`
with value 2097152

Thanks!

**Comment by andryyy** [comment]
I added it, but it seems to be an option that does not belong to a parent (see doveconf).

Will push with some other stuff later.

**Comment by hunter-nl** [comment]
According to https://www.dovecot.org/doc/dovecot-example.conf it belongs to protocol imap section

**Comment by andryyy** [comment]
Sounds reasonable, but just run doveconf.

**Comment by stevesbrain** [comment]
Interesting - I've had folders with approximately 30,000 emails with no issue :/ When you say "thousands", how many "thousands" we talking?

**Comment by Adorfer** [comment]
perhaps something like this. 
![grafik](https://user-images.githubusercontent.com/10302493/46802813-c5907a00-cd5e-11e8-807e-b87ef4afaedc.png)

**Comment by stevesbrain** [comment]
Ah, hundreds of thousands - I'll make sure to archive before then :grin:

**Comment by Adorfer** [comment]
what is the difference between status "mailbox" and "archive"?
Are archived messages packed/indexed more efficiently?

**Comment by stevesbrain** [comment]
Ah, I just meant taking them off the mailserver and keeping them in my own local maildir (which mutt just looks at separately), so won't kill SOGo :) I wasn't referring to a special mode for SOGo etc.

**Comment by Adorfer** [comment]
So you are basically saying: The solution to the problem is, not to use Sogo/mailcow?
(Thunderbird via VNC or just gmail for example)

**Comment by Braintelligence** [comment]
Whip out the good 'ol POP3 without copy remnants :P
I'm curious tho, if the above mentioned setting makes Mailcow viable for such an amount of mails.

**Comment by hunter-nl** [comment]
I've users with 100.000+ mails in a folder. With the setting added, then it works just fine in mailcow.

**Comment by Braintelligence** [comment]
@hunter-nl That's awesome! Can you please shortly elaborate what the negative effects of this setting are? I mean, if there would be none, we could just set it as default, right?

**Comment by andryyy** [comment]
It's iiiiin.

**Comment by extremeshok** [comment]
The issue is not related to imap, its the actual method you are using to store the emails.

My largest single imap folder is 11 million mails. My average imap folder size is 700 000 mails.

maildir is not good for anything over 100 000.

I can submit patches for extremely efficient de-duplicated storage of mails... however Im not sure @andryyy will accept the move to sis+mdbox

**Comment by andryyy** [comment]
It's not that we don't know which options exist.

Moving to mdbox is more than just changing a parameter. We need to check how well a migration will work or only apply it to new setups OR new mailboxes. Forcing all users to migrate to mdbox will not happen, no.

Dovecot is able to detect the mailbox format, but it still has downsides.

Edit: Not sure how well deduplication works on mixed environments. I will also not accept PRs for this change. This needs intensive testing before it is implemented.

We probably need to set all exiting and _non-empty_ mailboxes (important) to "auto:" and create new mailboxes with mdbox. We still need to check how deduplication will work with both mailbox formats available. It may through some errors complaining about maildir blabla.

mail_attachment_fs does need to be configured to store data encrypted with our mail_crpt key.

A migration script for those who _want_ to migrate old-format mailboxes needs to be provided _and_ tested.

**Comment by extremeshok** [comment]
@andryyy have all that, including custom conversion scrips, mods to the installer etc.

Been using mdbox+sis on more than 1000 mailboxes for many years. Ported it over to mailcow 

#1007 #1046

**Comment by ciroiriarte** [comment]
> It's not that we don't know which options exist.
> 
> Moving to mdbox is more than just changing a parameter. We need to check how well a migration will work or only apply it to new setups OR new mailboxes. Forcing all users to migrate to mdbox will not happen, no.
> 
> Dovecot is able to detect the mailbox format, but it still has downsides.
> 
> Edit: Not sure how well deduplication works on mixed environments. I will also not accept PRs for this change. This needs intensive testing before it is implemented.
> 
> We probably need to set all exiting and _non-empty_ mailboxes (important) to "auto:" and create new mailboxes with mdbox. We still need to check how deduplication will work with both mailbox formats available. It may through some errors complaining about maildir blabla.
> 
> mail_attachment_fs does need to be configured to store data encrypted with our mail_crpt key.
> 
> A migration script for those who _want_ to migrate old-format mailboxes needs to be provided _and_ tested.

would it be an option for greenfields?

**Comment by andryyy** [comment]
Yes. I will try to add it with the next push.

**Comment by andryyy** [comment]
The mailbox attribute already exist. Just need to add something to toggle the shared namespace.

**Comment by ciroiriarte** [comment]
Is #1007 related to this somehow?

**Comment by andryyy** [comment]
Its implementation is there, just not finished.
