### ISSUE TITLE
Forwarding Host configuration

### ISSUE THREAD

**Issue by ruffy91** [mailcow/mailcow-dockerized#1875]
I would like to send notification mails from a few IPs without authentication.
I added the IPs to the Forwarding Host List.

When trying to deliver mails to my mailboxes from these IPs I get either "504 5.5.2 : Helo command rejected: need fully-qualified hostname" when trying to deliver via port 25 or "554 5.7.1 : Client host rejected: Access denied" when delivering on 587.

Which is the correct port for this feature and is it possible to deliver without a FQDN HELO?
Where do I have to change the config to allow this?

**Comment by andryyy** [comment]
You can add them to mynetworks in main.cf. Dkim will not be available though. 

You should really fix the sender to be RFC conform and also authenticate. 

Forwarding hosts are not meant for this. There is a description in mailcow UI for what it actually does. :-)
