### ISSUE TITLE
Question regarding mail crypt

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1876]
Hi there,
I have seen that since one of the latest updates, the mail crypt is enabled by default. I am totally ok with that, but i have some questions:

1) "Maildir encryption is enabled by default! Backup “crypt-vol-1”! You lose/delete this key, you lose your mail. There is no way to recover them.
bash helper-scripts/backup_and_restore.sh backup crypt"
This means that if i run the script with parameter "ALL" will include by default now also the encryption keys?

2) Is there a safe way to revert back (maybe give this option?) to unecrypted vmail volume without loosing existing data?

Thank you!

**Comment by andryyy** [comment]
Yes, "ALL" will backup the key.

You can disable encryption by setting `mail_crypt_save_version = 0` in dovecot.conf. It will still be able to read encrypted files, but stops to encrypt new messages.

See this comment for a simple script to decrypt or encrypt existing files: https://github.com/mailcow/mailcow-dockerized/issues/1791#issuecomment-426397136

**Comment by marcquark** [comment]
Sorry for digging this up again, but i didn't want to make a new thread. After reading the thread you referenced i'm wondering whether it's still the case that changing passwords means that we effectively lose the user's emails?
Or is everything now encrypted using the key i can back up using the helper script?

**Comment by ntimo** [comment]
@marcquark Everythink is encrypted using one key this key is stored in the crypt volume. This means that the user can change this password without loosing access to the data. The integrated helper backup script will also backup the encryption key ;)

**Comment by kosli** [comment]
> Yes, "ALL" will backup the key.
> 
> You can disable encryption by setting `mail_crypt_save_version = 0` in dovecot.conf. It will still be able to read encrypted files, but stops to encrypt new messages.
> 
> See this comment for a simple script to decrypt or encrypt existing files: [#1791 (comment)](https://github.com/mailcow/mailcow-dockerized/issues/1791#issuecomment-426397136)

thanks for the comment. would be great if the general encrytion for dovecot in mailcow (and how to disable it) would be documented here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-mail-crypt/  (would do it myself, but i am currently short on time :-( )
