### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#1877]
Mailcow stopeed relaying some mail, and i got this in the logs:

postfix-mailcow_1    | Oct 12 11:39:44 mx postfix/error[7376]: 0A8CA8070E: to=<munged>, relay=none, delay=47562, delays=47562/0.74/0/0.11, dsn=4.4.3, status=deferred (delivery temporarily suspended: Host or domain name not found. Name service error

a reboot solved the issue. My guess is that a temporary connectivity issue more than 12 hrs ago polluted postfix DNS cache. But that's just a guess. The server is in a datacenter and I have no evidence of problems.

I don't know if it's related, but a friend told me he had similar issues in the past when mailcow lost connectivity.

**Comment by Braintelligence** [comment]
Just a quick idea: I heard ICANN changed root DNS or something. Maybe this is related?

**Comment by andryyy** [comment]
Please search other issues first. :-) restart unbound-mailcow
