### ISSUE TITLE
Mailcow not receiving mail

### ISSUE THREAD

**Issue by luckysphere** [mailcow/mailcow-dockerized#1878]
Hello, during this night, i have two Mailcow server stop receiving mail.. and i dont know why, the issue is to reboot servers and it works again

**Comment by andryyy** [comment]
Restart unbound-mailcow and search other issues, please.

**Comment by Braintelligence** [comment]
Good thing I checked my instances xD. All of them also had DNS problems. 😸 Restarting unbound helped indeed.
