### ISSUE TITLE
syslog driver

### ISSUE THREAD

**Issue by constin** [mailcow/mailcow-dockerized#1879]
Hallo, in your documentation:

"This mechanism makes it possible to use whatever Docker logging driver you want to, without losing the ability to read logs from the UI or ban suspicious clients with netfilter-mailcow."

But then i try to use syslog as driver for postfix container there is no more postfix logs in web UI. all postfix logs are only in host syslog

**Comment by andryyy** [comment]
The Postfix web UI logs are written to Redis, no matter the logging driver used by Docker.

Maybe your settings broke the container? :-/ Not sure. But syslog-ng is run independently of the loggin driver, that's strange.
