### ISSUE TITLE
emailsecuritycheck.net virus test...

### ISSUE THREAD

**Issue by a-schaefers** [mailcow/mailcow-dockerized#188]
emailsecuritycheck.net virus test fails with emails 1-3 being blocked but 4-7 are delivered through default mailcow settings. I don't know if this is emailsecuritycheck.net being a irrelevant test or if mailcow is dropping the ball. I just thought I would share the results here and see what others think? Thank you.

**Comment by andryyy** [comment]
Some just contain key words, some contain EICAR which is not tested. I will add a few lines to the docs about how to add ClamAV or similar today!

**Comment by Braintelligence** [comment]
@andryyy Looking forward to the ClamAV-guide in the docs! :)
Btw: Are there any updates on the license topic yet? I don't know if it's safe to use or host mailcow otherwise :(. ( https://github.com/andryyy/mailcow-dockerized/pull/7 )

**Comment by andryyy** [comment]
Don't worry about the mailcow license itself.
I want to collect the licenses used by each component and put them together.
mailcow will stay under GPL.

**Comment by Braintelligence** [comment]
That's great to hear. Thank you so much for your hard work! Is there a way to donate to your cause? 
And sorry for derailing the ticket a bit ^^.

Edit: just saw the donate badge :)

**Comment by andryyy** [comment]
You can find a donate button here: https://github.com/andryyy/mailcow-dockerized

But there is no need to. :-) You can also order a vps at Servercow if you want to help. But again, there is no need to do either!

**Comment by Braintelligence** [comment]
I want to host mailcow in the future for my customers, so the least I can do is to contribute financially and with pull requests (if I can). You deserve that :).
