### ISSUE TITLE
Latest update DNS problems

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#1880]
Hi there, i don't know if the latest update has anything to do with this problem but since then  all mails are remaining in queue with this error:

86EA3101AEBF2     1095 Fri Oct 12 15:53:29  email@email.com
(Host or domain name not found. Name service error for name=email.com type=MX: Host not found, try again)
                                         email1@domain1
                                         email2@domain2

Obviously i masked the real domains and email and checked if DNS is working properly. On host i am using google DNS without problems and trying to switch to other DNS such cloudflare did not resolve the issue. 
Any clues?
Thanks

**Comment by Braintelligence** [comment]
Is this related https://github.com/mailcow/mailcow-dockerized/issues/1877?

**Comment by lucianlazar1983** [comment]
I don't know, the server is in HA and did not lost connectivity o got any DNS realted issue. Rebooting the server has solved the problem, i will monitor and report back if it will happen again. I reported this because it never happend before.

**Comment by Braintelligence** [comment]
Maybe related to new DNS root

**Comment by andryyy** [comment]
Guys, please search the issues.
