### ISSUE TITLE
Sync jobs authentication error

### ISSUE THREAD

**Issue by SecuritySense** [mailcow/mailcow-dockerized#1881]
I set up a sync job in preparation to migrate my hosted mail to my own server.

I entered the details and the account synced without issue the first time.  The next time it attempted to sync (and any time since) it has failed.

I have confirmed the setting are correct and that the credentials are correct in the mailcow.imapsync table.  I have also connected manually using another tools and the same credentials and it connect without any issue.

I have also tried with ports 143 and 993 set within the sync jobs tab.

The error message I am getting is as follows:

Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
Here is imapsync 1.882 on host mail.xxxx.co.uk, a linux system with 1.1/3.8 free GiB of RAM
with Perl 5.24.1 and Mail::IMAPClient 3.39
Transfer started at Fri Oct 12 17:04:03 2018
PID is 85
Load is 0.86 0.35 0.13 3/685 on 4 cores
Current directory is /var/tmp
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.882 $ $Date: 2018/05/05 21:10:43 $ 
Command line used:
/usr/local/bin/imapsync --tmpdir /tmp --nofoldersizes --exclude (?i)spam|(?i)junk --delete2duplicates --subscribeall --automap --tls1 --host1 imap.1and1.co.uk --user1 si@xxxx.co.uk --passfile1 /tmp/imapsync.uoXWQzD --port1 993 --host2 localhost --user2 si@xxxx.co.uk*yxxxxxsshya7d0 --passfile2 /tmp/imapsync.beFHTwJ --no-modulesversion
Temp directory is /tmp ( to change it use --tmpdir dirpath )
kill -QUIT 85 # special behavior
kill -TERM 85 # special behavior
kill -INT 85 # special behavior
kill -USR1 85 # special behavior
PID file is  ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Could not open  for writing. Check permissions or disk space.
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Host2: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe ) 
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host2
Info: will act as --uidexpunge2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: IMAP server [imap.1and1.co.uk] port [993] user [si@xxxx.co.uk]
Host2: IMAP server [localhost] port [993] user [si@xxxx.co.uk*xxxxsshya7d0]
Host1: connecting and login on host1 [imap.1and1.co.uk] port [993] with user [si@xxxx.co.uk]
Host1 failure: can not open imap connection on host1 [imap.1and1.co.uk] with user [si@xxxx.co.uk]: socket closed while reading data from server

**Comment by andryyy** [comment]
Could not open for writing. Check permissions or disk space.

The job is run as root (inside the container), so there is no permission issue. Have you checked `docker-compose exec dovecot-mailcow /bin/bash -c "df -h /"`?

Edit: I also just checked that it is not broken in mailcow. :-/

**Comment by SecuritySense** [comment]
It has just started working again and I haven't changed anything.

Not sure what is going on!!!

Output of df command is:

Filesystem      Size  Used Avail Use% Mounted on
overlay         439G  7.7G  409G   2% /

So no issue there.
