### ISSUE TITLE
Plötzliche eMail-Empfangsprobleme

### ISSUE THREAD

**Issue by pbaeumel** [mailcow/mailcow-dockerized#1882]
Hallo zusammen,

ich weiß die Anfrage ist hier vielleicht nicht gänzlich korrekt gestellt; dennoch hoffe ich wenigstens darauf, dass mir jemand sagen könnte in welcherRichtung ich Ursachenforschung betreiben könnte.

Seit heute morgen gehen gefühlt einige erwartete eMail nicht auf meinem Mailcow-Server ein; z.B. OTRS-Autoresponder vom Support meines VOIP-Anbieters. (Gleiche Autoresponder sind vor 2-3 Tagen hier noch korrekt eingegangen)

Zudem habe ich gerade auch versucht mir selbst von extern (mailbox.org-Account / Arbeitsaccount) eine eMail zu senden; wie auch eine ausgehende eMail zu versenden (Richtung mail-tester.com bzw. zum mailbox.org-Account bzw. zum Arbeitsaccount).

Mit dem Ergebnis: Irgendwie kommen diese Test-eMails alle nicht an!

In der RSPAMD-GUI des Mailcow-Servers sind die ausgehenden eMail allerdings sichtbar - auchmit "no action".

Es wurde durch mich weder am Server (KVM-Server von netcup.de) noch an Mailcow eine Änderung durchgeführt.

Wo könnte ich nun weiter recherchieren?

Grüße,
Patrick B.

**Comment by pbaeumel** [comment]
Gerade fällt mir auf, dass es in den Logs mehrere folgender Zeilen gibt:
`NOQUEUE: reject: RCPT from unknown[212.18.1.34]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [212.18.1.34]; from=<prvs=81686acdf=p.baeumel@hxxx.com> to=<patrick@xxx.com> proto=ESMTP helo=<mail1.donotspam.de>`

`warning: dnsblog_query: lookup error for DNS query 28.42.192.91.dnsbl.sorbs.net: Host or domain name not found. Name service error for name=28.42.192.91.dnsbl.sorbs.net type=A: Host not found, try again`

Sieht für mich als "Linux-Laien" so aus, als ob mein KVM-Server eventuell Problememit der Namensauflösung hat, oder?

Mache ich jedoch testweise einen nslookup, dann sieht dies okay aus:
`nslookup google.de
Server:         46.38.225.230
Address:        46.38.225.230#53
Non-authoritative answer:
Name:   google.de
Address: 216.58.208.35`

Wo könnte ich weitersuchen?

Grüße,
Patrick B.

**Comment by schlalek** [comment]
Hallo Patrick,
Ich hatte heute dasselbe Problem. 
Eine Neustart des Hostsystems hat geholfen. 
Ich vermute es hängt mit der Umstellung der DNS Schüssel von heute zusammen. Irgendwie kann der Resolver von mailcow die reverse lookups nicht mehr auflösen. 
Vielleicht kann hier jemand genau erklären was passiert ist. 

Grüße, 
Alex

**Comment by mkuron** [comment]
Das Problem hatten viele, #1880 #1878 #1877. Die genaue Ursache kennen wir nicht, es klingt aber wie ein Bug in Unbound.

**Comment by Braintelligence** [comment]
Das naheliegendste wird doch wohl das hier sein: https://www.redhat.com/en/blog/what-you-need-know-about-first-ever-dnssec-root-key-rollover-october-11-2018

**Comment by mkuron** [comment]
Ja, aber der neue Key ist seit Monaten in unserem Unbound-Image enthalten. Nirgendwo in der Unbound-Doku steht, dass man nach dem Rollover manuell neustarten muss.

**Comment by Braintelligence** [comment]
Das ist merkwürdig. In dem Link steht auch, dass unbound den neuen Key haben sollte. Dort ist auch ein Verfahren beschrieben, wie man prüfen kann, ob man den neuen Key hat.
Ob man wohl auch nicht-containerisierte Unbounds neustarten musste?
Bei mir waren halt alle Mailcow Instanzen unterschiedlichsten Update-Grades betroffen und das Timing ist einfach zu passend.

**Comment by mkuron** [comment]
Problem gefunden: wir haben Alpine Linux 3.6 mit Unbound 1.6.2. @andryyy, kannst du bitte ein Upgrade auf 3.8 mit 1.7.3 oder 3.7 mit 1.6.7 pushen? Da war laut https://www.unbound.net/root-11sep-11oct.html ein wichtiger Fix in 1.6.5. Der Bug müsste jeden betroffen haben, der in den letzten 30 Tagen `docker-compose down && docker-compose up` gemacht hat; außerhalb von Containern wäre man nur bei einer Neuinstallation innerhalb der letzten 30 Tage betroffen gewesen.

**Comment by andryyy** [comment]
Danke, ist gefixt.
