### ISSUE TITLE
New feature request: postfix queue in UI

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1883]
It would be very useful to see the postfix queue in the web UI as (domain) admin and do actions on the messages in the queue. Like: delete, on hold, release, flush, etc.

**Comment by ntimo** [comment]
This would indeed be a nice feature :-) let’s hope André will add it.

**Comment by andryyy** [comment]
That’s quiet a lot. I don’t need it as I use postqueue manually. If someone wants to sponsor the work, let me know.

Hm. We could probably mount the Postfix volume into the PHP container and work on file system layer. Would be faster and easier.

**Comment by Knight1** [comment]
Getting the count of the queue would be easy. Would that help?

**Comment by andryyy** [comment]
No. Not really. It is not that we don’t know how to implement it. I just don’t want a shitty implementation or even hammer dockerapi with exec requests all the time for queue tasks.

We will probably run in permission issues, that need to be taken care of first (on file system layer). 

Please don’t use any exec, system or shell_exec stuff in PHP. 

Edit: not talking about you when I say shitty implementation. :-D talking about myself and doing it in a hurry. That would mess stuff up. We did this quite too often.

**Comment by Knight1** [comment]
That was not my idea. I just had the idea to add a queue endpoint for the debug section. So you can simply see the count of the queue. So only a request when you visit it.

But just for monitoring purposes so it does not get too big in case of any problems. We could use this https://exchange.icinga.com/exchange/check_postfixmailqueue inside the Watchdogs Container.

exec, .. is blocked :P 

Yeah we try our best :)

**Comment by andryyy** [comment]
I will think about a queue implementation.

**Comment by MAGICCC** [comment]
I tried to implent it on my own once but couldn't get it working due to not enough time to understand the docker API :)
We had e.g. pflogsumm in the non docker version

**Comment by andryyy** [comment]
I messed up the last update, so I thought I owe you this.

![grafik](https://user-images.githubusercontent.com/2972950/47219078-11ba6a80-d3ae-11e8-84ab-70cc7b5d14fb.png)

Not finished yet. I use Postfix' new postqueue JSON output for it.

**Comment by hunter-nl** [comment]
@andryyy It looks already very good. You made my day! :-)

**Comment by andryyy** [comment]
Should be working, let's hope the best. :-P

Nah, seriously, test it and let me know if something fails.

**Comment by hunter-nl** [comment]
It works already great. Thanks andryyy! Maybe one improvement can be done.
When message is on hold or delayed due some reason. The Recipients column shows in a json format the recipient and the reason why it was put on hold or delayed.
Like:
`[{"address":"test@example.com","delay_reason":"connect to 123.0.0.1[123.0.0.1]:25: Connection refused"}]`
It looks better if "delay_reason" will be put into an additional column and format the two without json markup.

**Comment by andryyy** [comment]
I cannot make it a column, but we could indeed parse this in a nicer way.

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/47486996-e6b69780-d841-11e8-9f6c-1f1f89bcc254.png)
...and...
![grafik](https://user-images.githubusercontent.com/2972950/47487010-ee763c00-d841-11e8-9ef9-b56050d22f64.png)
:-)

**Comment by hunter-nl** [comment]
I prefer the second one. As this shows the recipient directly. Which makes searching/lookup easier.
The total width of the table is about 50% of my total screen width. The quarantine table view is much wider. If it is possible to increase the width of the table then it will be nicer to view ;-)
The current queue table is not showing the Sender and Recipient column on my iPhone screen (even after scrolling)?

**Comment by andryyy** [comment]
Both is the same, just different screen sizes. You can open the rows by clicking on them.

**Comment by hunter-nl** [comment]
Ok, that's makes it clear ;-)
Only on my iPhone it do not show the columns sender and recipient.
![image](https://user-images.githubusercontent.com/5203309/47489897-e7eac300-d847-11e8-985a-88578e9a0025.png)

**Comment by andryyy** [comment]
I will check it, but I think I fixed it a few mins ago. :-)
