### ISSUE TITLE
Additional SSL or wildcard certificate for webserver

### ISSUE THREAD

**Issue by mode2k** [mailcow/mailcow-dockerized#1884]
Hi,

my mailcow webif is reachable by mail.mydom.tld. Our website is reachable by mydom.tld (just created a ./data/conf/nginx/custom.conf file for that)
The ssl cert is issued for mail.mydom.tld and by using ADDITIONAL_SAN for mydom.tld.

Now I want to use two independent certs for mail.mydom.tld and mydom.tld.
Alternatively, I want to use a wildcard certificate.

How can I archive that? What is the easiest way?

BR

mode

**Comment by MAGICCC** [comment]
For two independent certs or wildcart cert you would need to disable acme container in the mailcow.conf and use another ACME program to get those.
I recommend to use https://github.com/Neilpang/acme.sh

**Comment by andryyy** [comment]
Or work with a reverse proxy. :-)
