### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by mitchellurgero** [mailcow/mailcow-dockerized#1885]
Randomly on Thursday after updating to ee5142557ee90f4c57e60f1d75249aba46337a92 For whatever reason my postfix container came up but postfix never actually started which halted email. I am still looking through logs to see what happened but so far no luck. Latest commit (as of this post) seems to be fine so far.

**Comment by andryyy** [comment]
Watchdog would catch that. 

But it would definitely log why it didn’t start via supervisor.

**Comment by mitchellurgero** [comment]
How do I set up watch dog? That sounds interesting to use. Does it auto-restart or just alert?

EDIT: Setting up WATCHDOG=Y and WATCHDOG_EMAIL to (phone@isp.com (using: https://www.digitaltrends.com/mobile/how-to-send-a-text-from-your-email-account/ as a guide to do email to SMS) ) seems to have done the trick in setting up watchdog. Now we wait I suppose.

**Comment by mitchellurgero** [comment]
Oh, for the watchdog service, how low does the health need to be seen as for a restart to occur? And where can I find logs of what determined that health percentage?

**Comment by andryyy** [comment]
You need to check the script. But you can also watch the logs. 👍 

Watchdog auto-restarts, yes. :-) I will add watchdog-mailcow to the docs when more checks were added.

**Comment by mitchellurgero** [comment]
Looks like this was a single case. Closing now.

**Comment by stevesbrain** [comment]
@mitchellurgero - same thing actually happened to me :)

**Comment by mitchellurgero** [comment]
@stevesbrain Oh no! Well it seems to have resolved itself. I set up the watchdog service and what not. Tested and confirmed working too so it's all good.
