### ISSUE TITLE
./update.sh hung

### ISSUE THREAD

**Issue by jjkondrat** [mailcow/mailcow-dockerized#1886]
Fetching new images, if any...
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Pulling unbound-mailcow   ... done
Pulling mysql-mailcow     ... done
Pulling redis-mailcow     ... done
Pulling clamd-mailcow     ... done
**Pulling php-fpm-mailcow   ... 
Pulling sogo-mailcow      ...** 
Pulling dovecot-mailcow   ... done
Pulling postfix-mailcow   ... done
Pulling memcached-mailcow ... done
Pulling nginx-mailcow     ... done
Pulling rspamd-mailcow    ... done
Pulling acme-mailcow      ... done
Pulling netfilter-mailcow ... done
Pulling watchdog-mailcow  ... done
Pulling dockerapi-mailcow ... done
Pulling ipv6nat           ... done

seems like it can't get the php-fpm and sogo images.
Is there any way I can get the system restarted without them (or recover the old ones?)
I didn't do a full backup before the update.

**Comment by mitchellurgero** [comment]
How long did you wait? I've noticed sometimes pulling takes a minute depending on your internet and such.

**Comment by jjkondrat** [comment]
It seems to have finally updated.  I’ll get the timings.  At least 15-20 min for those 2 packages.   The others were instantaneous.  I have gigabit Ethernet.  But guess it could have been a speed issue.   

Thanks for the response.

**Comment by andryyy** [comment]
That's up to the connection between Docker Hub and you, cannot fix. :-/
