### ISSUE TITLE
Some important questions regarding this project

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1887]
Hey @andryyy,
I know you are probably quite busy. But there are some very important questions and feedback I and @Knight1 want to give you.

1. Building the containers at your local PC is really really bad for the transparency of the project? How can the user trust the container if the build process is not open source? After all there could be anything running in this container.
2. Why are you commits not linked to your GitHub user? 
3. Why are you not using pgp keys for signing your code?
4. A contribution guideline for pull requests would be good
5. Using issues for Github would be nice, makes life of everyone easier.
6. Automated code audits with travis would be good, this way you can check if a merge is working or not.
7. What are the rules so it gets merged? How do you decide what to merge? Currently it feels like you are rolling a dice.

**Comment by andryyy** [comment]
If you want to ask me stuff, ask me via mail, please. 

You don't need to use mailcow when you don't trust me building the images. This will change in the future, or when you sponsor the project a build machine. Travis is slow. I also prefer to test some images before pushing them.

"Using issues for Github would be nice, makes life of everyone easier." - what do you mean?

Automated audits will **never** catch all errors. Writing tests will probably neither, but I will do this at some point. I do this for some managed mailcow components already.

Closing as it is not an issue.

**Comment by Knight1** [comment]
Travis needs ~18 Minutes. The point is that you build in in a branch after you/we tested local and then PR into master. 18 Minutes later we tag :master at the end of all, push that to docker hub and that's it.

So if i understand correct we should always write an email if we need help around problems with mailcow?

**Comment by andryyy** [comment]
No, it does not always take 18 minutes.

If you write "Hey @andryyy", you want to write me a mail, yes.
