### ISSUE TITLE
Update clamav to 0.100.2

### ISSUE THREAD

**Issue by Knight1** [mailcow/mailcow-dockerized#1890]
Hi :)

https://blog.clamav.net/2018/10/clamav-01002-has-been-released.html

Some security fixes, should/can we update?

**Comment by andryyy** [comment]
Indeed, I will fix it today.

**Comment by Knight1** [comment]
Fixed with https://github.com/mailcow/mailcow-dockerized/commit/5705044af054c557a87b284b097b3482d8a19ae9

**Comment by andryyy** [comment]
Yes, thanks, forgot the reference.
