### ISSUE TITLE
Quarantaine shows empty messages

### ISSUE THREAD

**Issue by jgeusebroek** [mailcow/mailcow-dockerized#1892]
The backend shows quarantaine items, but when I want to display them, it seems like they are empty. When checking the database, I see the messages are not empty.

**To Reproduce**
I pasted the SQL quarantine row, this might help to reproduce.
https://pastebin.com/ht9W6q0s

**Expected behavior**
Display the message so I can make a good assessment whether it is spam or not.

![screen shot 2018-10-14 at 09 33 38](https://user-images.githubusercontent.com/203215/46913807-9400f400-cf94-11e8-98bd-7f0baddfeb0f.png)

**Comment by andryyy** [comment]
Nice catch, can reproduce and will fix it.
