### ISSUE TITLE
Tags in Subject not working with alias

### ISSUE THREAD

**Issue by niklasfyi** [mailcow/mailcow-dockerized#1897]
I have a mailbox named mail@example.org. I have set tags to be displayed in the subject. So when I sent an email to mail+test@example.org I will get a email with the subject "[test] ....". But when I set up an alias mail2@example.org -> mail@example.org and sent an email to mail2+test@example.org I will get an email without the tag in the subject.

**Comment by andryyy** [comment]
It only works for direct aliases, not for shared aliases.

**Comment by niklasfyi** [comment]
Is it possible to be changed?

**Comment by mkuron** [comment]
Duplicate of #408
