### ISSUE TITLE
Reverseproxy - Apache2 -> Nginx

### ISSUE THREAD

**Issue by Christian1998** [mailcow/mailcow-dockerized#1898]
I get only "502 Bad Gateway nginx" error when i try to use the reverseproxy but i fail...
Already tried multiple config-files. Reloaded, Restartet and all that...

My mailcow.conf-File: https://pastebin.com/HeZ6feh2
My Virtualhost-File: https://pastebin.com/Dd9KeLrd

Please help me, i cant find the issue.

**Comment by Christian1998** [comment]
I ran out of time, so i just reinstalled the container and all around it...

**Comment by cklabautermann** [comment]
I am missing one vital line in your vhost:443

   
        **SSLEngine On**
