### ISSUE TITLE
LetsEncrypt unusable with lots of domains

### ISSUE THREAD

**Issue by fifthecho** [mailcow/mailcow-dockerized#1901]
**Describe the bug**
I am using Mailcow Dockerized with 39 domains and it's working great, other than trying to use the automated LetsEncrypt.
For my reverse proxy, given 4 hostnames per domain, I have had to break out each domain into its own LetsEncrypt certificate chain and that is working well, however, as there's more than 100 additional SANs, there's no way to use a single certificate.

Would it be possible for the configuration of Dovecot/postfix (and the built-in nginx) to use a separate directory and certificate from LetsEncrypt for its certificate so that I no longer have to push any client using a domain via a mail client to a single domain?

**How to reproduce**
1. Set up Mailcow-Dockerized
2. Add at least 26 domains
3. Attempt to use LetsEncrypt to generate certificates and get errors about too many SANs

**Expected behavior**
Allow >25 domains within the system

**Comment by Braintelligence** [comment]
Maybe using a wildcard certificate per TLD would be the more viable option here?

**Comment by mkuron** [comment]
Duplicate of #461
