### ISSUE TITLE
Extend validity of spam aliases

### ISSUE THREAD

**Issue by SamuelNitsche** [mailcow/mailcow-dockerized#1903]
**Is your feature request related to a problem? Please describe.**
Sometimes when creating a spam alias you don't really know how long you need it. Then maybe you notice that you need it longer.

**Describe the solution you'd like**
Maybe there could be a little dropdown button next to the spam alias to extend the validity by the default values.
(1 hour, 6 hours, 1 day, etc.)

![bildschirmfoto 2018-10-16 um 15 10 31](https://user-images.githubusercontent.com/24483576/47018888-1389f100-d156-11e8-9f0b-2baaacedfba3.png)

**Comment by ticevi** [comment]
You can already select the Alias and extend the period by 1 hour in the Dropdown "Aktion"

**Comment by andryyy** [comment]
Hi, it was very limited, so I changed it to allow a user to set a new expire time. Will push in a bit.
