### ISSUE TITLE
Docker Migration Guide is missing

### ISSUE THREAD

**Issue by wolkenschieber** [mailcow/mailcow-dockerized#1904]
The guide describing the migration from a local installations to a dockerized installation is missing.

As the local installation bundle has been discontinued and deprecated, a dockerized installation is recommended. So there should be some way to move exisiting configuration and data into the new docker environment.

Several github issues contain some information about this procedure:
* [Tool to migrate from old, non-dockerized to dockerized mailcow? #112](https://github.com/mailcow/mailcow-dockerized/issues/112)
* [Migration from mailcow -> mailcow-dockerized #132](https://github.com/mailcow/mailcow-dockerized/issues/132)
* [Migrate from Non-Mailcow installation to Mailcow-Dockerized? #516](https://github.com/mailcow/mailcow-dockerized/issues/516)
* [Mailcow UI empty after migration from 0.14 with reverse proxy #645](https://github.com/mailcow/mailcow-dockerized/issues/645)
* [How to migrate mails /var/mail to dockerized ? #884](https://github.com/mailcow/mailcow-dockerized/issues/884)

Unfortunatelly these issues link to a gone section of the documentation:
   https://mailcow.github.io/mailcow-dockerized-docs/migrate-mc014

Is there any chance to bring this section back or to attach it to this issue?

**Comment by mritzmann** [comment]
> or to attach it to this issue?

https://github.com/mailcow/mailcow-dockerized-docs/blob/62001c279bbf96837c6bd57d705d25f4299a35cc/docs/migrate-mc014.md

But assume that there are reasons why this was removed...

**Comment by andryyy** [comment]
Yes, some sections are not correct anymore. I do it by hand for migration requests. Is it a private setup?

**Comment by wolkenschieber** [comment]
Yes. This is a private setup.

**Comment by wolkenschieber** [comment]
As I only have two domains and three users, providing a base setup is a doable job. But I'm still looking for a way to migrate existing mails.

**Comment by andryyy** [comment]
You can contact me by mail I can help you with it.

**Comment by wolkenschieber** [comment]
Many thanks, I'll use that as a last resort.

**Comment by andryyy** [comment]
Sure. :) I have no guide handy to refresh the docs at the moment.

**Comment by MAGICCC** [comment]
I have a textdocument for migrating to the dockerized version somewhere.
I'll close this issue since @andryyy may fix it.

**Comment by wualex** [comment]
@MAGICCC could you share the doc please?
