### ISSUE TITLE
Issue after update: 502 Bad Gateway

### ISSUE THREAD

**Issue by rafix1989** [mailcow/mailcow-dockerized#1905]
Hi after update to latest version of mailcow i receive in my UI 502 Bad Gateway.
Can you help me to resolve issue ??

**Comment by andryyy** [comment]
Hi, please read the issue template first and use it. :-( We need logs. Can you post php-fpm-mailcow logs? Or does /SOGo give a bad gateway?

**Comment by rafix1989** [comment]
oh... Sorry. 
it's hard to say what logs are becouse after inserting docker-compose logs php-fpm-mailcow i've got, and /SOGo also give 502.
![obraz](https://user-images.githubusercontent.com/805762/47040707-2d8ff780-d187-11e8-9a47-e8872e6a9efd.png)

**Comment by andryyy** [comment]
Ah, you log to syslog. Then it is in syslog. :-)

Is it only SOGo to not work? Or the main mailcow UI?

**Comment by rafix1989** [comment]
It's in Mailcow UI and for SOGo 
This is what i found in syslog
> Oct 16 19:59:24 localhost d493fa71dec3[1518]: Waiting for SQL...
Oct 16 19:59:24 localhost 01e73575e809[1518]: Waiting for database to come up...
Oct 16 19:59:24 localhost cecec7498e46[1518]: Waiting for database to come up...
Oct 16 19:59:26 localhost d493fa71dec3[1518]: Waiting for SQL...
Oct 16 19:59:26 localhost 01e73575e809[1518]: Waiting for database to come up...
Oct 16 19:59:26 localhost cecec7498e46[1518]: Waiting for database to come up...
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: Oct 16 19:59:27 panel postfix/postscreen[598]: CONNECT from [85.194.241.207]:53394 to [172.22.1.5]:25
Oct 16 19:59:27 localhost a2223fcb1ddb[1518]: 2018/10/16 19:59:27 [error] 17#17: *937 connect() failed (111: Connection refused) while connecting to upstream, client: $
Oct 16 19:59:27 localhost a2223fcb1ddb[1518]: 2018/10/16 19:59:27 [error] 17#17: *937 connect() failed (111: Connection refused) while connecting to upstream, client: $
Oct 16 19:59:27 localhost a2223fcb1ddb[1518]: fd4d:6169:6c63:6f77::1 - - [16/Oct/2018:19:59:27 +0200] "GET /forwardinghosts.php?host=85.194.241.207 HTTP/1.1" 502 150 "$
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: Oct 16 19:59:27 panel whitelist_forwardinghosts: Look up 85.194.241.207 on whitelist, result <html>
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: Oct 16 19:59:27 panel syslog-ng[9]: Error processing log message: <head><title>502 Bad Gateway</title></head>#015
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: <body>#015
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: <center><h1>502 Bad Gateway</h1></center>#015
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: <hr><center>nginx</center>#015
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: </body>#015
Oct 16 19:59:27 localhost 70ef8be82ae9[1518]: </html>#015

**Comment by rafix1989** [comment]
and last syslog entry:

> Oct 16 21:08:34 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:35 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:35 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:36 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:37 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:37 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:38 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:39 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:39 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:39 salit-mail in.telnetd[22175]: connect from 179.222.139.10 (179.222.139.10)
Oct 16 21:08:40 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:41 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:41 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:42 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:43 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:43 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:44 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:45 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:45 localhost 85868bdd8303[1446]: Waiting for database to come up...
Oct 16 21:08:46 localhost 0d99d1d5425f[1446]: Waiting for database to come up...
Oct 16 21:08:47 localhost bfb5a767eb00[1446]: Waiting for SQL...
Oct 16 21:08:47 localhost 85868bdd8303[1446]: Waiting for database to come up...

**Comment by rafix1989** [comment]
I've repair it :) thanks . Sorry next time i will use issue template.

**Comment by ciroiriarte** [comment]
What was the fix?
