### ISSUE TITLE
Mailcow can't send emails because mailcow_anonymize_headers.pcre not found

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1906]
**Describe the bug**
Mailcow can't send emails because the file mailcow_anonymize_headers.pcre is renamed to mailcow_anonymize_headers.pcre_ after running the updater script this makes postfix unable to read the file that's why emails fail.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Update Mallow with updater script
2. Send a email
3. Look in the logs

**Expected behavior**
The mailcow_anonymize_headers.pcre should not be renamed and this way should be accessible by postfix.

**Logs**
postfix-mailcow_1    | Oct 16 21:29:12 mail enforced-tls-smtp/smtp[388]: warning: pcre:/opt/postfix/conf/mailcow_anonymize_headers.pcre is unavailable. open /opt/postfix/conf/mailcow_anonymize_headers.pcre: No such file or directory

postfix-mailcow_1    | Oct 16 21:29:12 mail enforced-tls-smtp/smtp[388]: warning: pcre:/opt/postfix/conf/mailcow_anonymize_headers.pcre lookup error for "Received: from [10.8.8.34] (unknown [37.58.58.230])??(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM"

postfix-mailcow_1    | Oct 16 21:29:12 mail enforced-tls-smtp/smtp[388]: warning: 55A726C0336: smtp header checks lookup error

**Comment by andryyy** [comment]
The file should be pulled from the repo.

**Comment by andryyy** [comment]
I added a check for it, thanks.
