### ISSUE TITLE
Refactor admin

### ISSUE THREAD

**Issue by mhf-ir** [mailcow/mailcow-dockerized#1907]
Problem is php code and administrator panel is old school and not well for extend app.
https://phptherightway.com/

**Describe the solution you'd like**
I like to help to redevelop the php application using REST based for using UI and other app.
separate Function layer to HTTP app layer for testing

**Additional context**
* bring shell and services functionality as non-web dependency layer:
Config fail2ban not depend on session, session must be checked as different layer with REST server.
Easy to testing and easy to extend
https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.fail2ban.inc.php#L19

Use angular or other reactive framework for UI development.
Using JWT instead of seasion(no storage required)

**Comment by mhf-ir** [comment]
i can help you to develope with Node.js/Typescript with fastify framework if you interest but as php version i suggest you using lumen or slim as rest framework.

**Comment by mkuron** [comment]
Duplicate of #708
