### ISSUE TITLE
curl returns invalid string when checking for docker-compose version

### ISSUE THREAD

**Issue by Vectrex** [mailcow/mailcow-dockerized#1909]
The update.sh script checks for the preferred docker-compose version by issuing a

```bash
curl https://www.servercow.de/docker-compose/latest.php
```
which (currently) returns 1.22.0
**but** on one of my servers (coincidentally the one which hosts mailcow) the above call returns
**22.0.1**
Trying to retrieve the version string with wget or viewing it with lynx always returns 22.0.1
A second pretty much identical server returns the expected
**1.22.0**
Both servers run Ubuntu 18.04.

Since 22.0.1 doesn't match my local docker-compose install and since there is no docker-compose version 22.0.1 the update script halts there. Retrieving docker-compose manually and firing it up again is no problem but an annoyance nonetheless.

Since the this issue doesn't change with the tools used I wonder whether https://www.servercow.de/docker-compose/latest.php does some kind of request analysis (IP range?) and responds with a different string.

Any other ideas what else could be the behind this issue?

**Comment by chriscroome** [comment]
That is really weird&hellip; could your local environment be rearranging the number somehow? Is 

```
printenv | egrep "*LANG*|*LOCALE*"```
```

the same on both servers? I assume the IP address does resolve the same on both servers?

```
dig www.servercow.de +short
```

Is the checksum for the file the same on both servers?

```
wget -q https://www.servercow.de/docker-compose/latest.php -O /tmp/docker-compose.txt
sha512sum /tmp/docker-compose.txt
fff968d7fca12dd1592c77c1f06cee34e6c9ffac055f95641b9e13729a51455e29af92d3d3a2b6bca76405a9680764ef881586b102710c3289448b6a323e34b1  /tmp/docker-compose.txt
cat /tmp/docker-compose.txt
1.22.0
```

**Comment by Vectrex** [comment]
Both servers show the exact same output
```bash
root@problematic ~ # printenv | egrep "*LANG*|*LOCALE*"
LANG=en_US.UTF-8
root@problematic ~ # dig www.servercow.de +short
5.1.76.4
```
```bash
root@seemsok ~ # printenv | egrep "*LANG*|*LOCALE*"
LANG=en_US.UTF-8
root@seemsok ~ # dig www.servercow.de +short
5.1.76.4
```
But then
```bash
root@problematic ~ # wget -q https://www.servercow.de/docker-compose/latest.php -O /tmp/docker-compose.txt
root@problematic ~ # sha512sum /tmp/docker-compose.txt
9a306bc2a8463328962490d56b728ca26314d2f08e12a1ed8933e10bf6d80270121ff31b3ce458070ab45b03ef984cadc30f6438a18ace50d4dc1a7f1fdfd1b7  /tmp/docker-compose.txt
root@problematic ~ # cat /tmp/docker-compose.txt
22.0.1
```
and 
```bash
root@seemsok ~ # wget -q https://www.servercow.de/docker-compose/latest.php -O /tmp/docker-compose.txt
root@seemsok ~ # sha512sum /tmp/docker-compose.txt
fff968d7fca12dd1592c77c1f06cee34e6c9ffac055f95641b9e13729a51455e29af92d3d3a2b6bca76405a9680764ef881586b102710c3289448b6a323e34b1  /tmp/docker-compose.txt
root@seemsok ~ # cat /tmp/docker-compose.txt
1.22.0
```
https://www.servercow.de/docker-compose/ lists two more scripts `ip_in_range.php` and `remote.php` - 
don't know whether they are of any relevance. IP address of problematic is 85.10.196.204 and of seemsok 148.251.232.246.

**Comment by andryyy** [comment]
Heh.

Your IP was in a range we used for managed setups where we return other values for a dc wrapper. Strange.

Can you test it again?

**Comment by Vectrex** [comment]
```bash
root@problematic ~ # curl https://www.servercow.de/docker-compose/latest.php
1.22.0
```

So, yes, that fixes it. Most appreciated.
