### ISSUE TITLE
Add option to filter existing messages when creating new filter

### ISSUE THREAD

**Issue by telnet23** [mailcow/mailcow-dockerized#1910]
**Is your feature request related to a problem? Please describe.**
Add an option to filter existing messages when creating a new filter. Apple Mail prompts whether to apply the rule to existing messages when creating a new rule.

**Describe the solution you'd like**
Add a check box on the bottom of the modal window.

**Additional context**
![image](https://user-images.githubusercontent.com/3433012/47059290-c37f4e80-d196-11e8-8219-c01fce0049f3.png)
![image](https://user-images.githubusercontent.com/3433012/47059289-bfebc780-d196-11e8-8dfc-ad9c7982bbad.png)

**Comment by mkuron** [comment]
This can only be done manually from within the Dovecot container (https://www.dovecot.org/list/dovecot/2008-February/028910.htm). The filter editor is part of SOGo, so we can‘t implement that feature ourselves. Requesting this feature from SOGo is unlikely to result in anything as the ManageSieve protocol does not provide this functionality and the `dovecot-deliver` hack cannot be integrated into SOGo.
