### ISSUE TITLE
Watchdog: TLS check hit the error rate limit

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1912]
I installed last Sunday my server completely new. New OS, new mailcow, manually import all mails and so on. Everything works and now i got from watchdog the following mail:

subject: Watchdog: TLS check hit the error rate limit

TLS certificate expires soon!

I did not found something directly in the logs. ACME logs says 86 days left. Is possible an other certificate meant?

**Comment by andryyy** [comment]
Oh, I can imagine the check fails when nginx-mailcow is not available for a short time. That check should be reviewed. You can ignore it. Did you receive a single mail?

**Comment by lgusewski** [comment]
Yes, after the new installation this mail comes since sunday the first time and only once. I got this mail also one or two times before from the old installation, but there i thought i had something broken with my user rights.

**Comment by andryyy** [comment]
Okay, thanks, I will check it. 👍

**Comment by phipag** [comment]
I got the same message.

**Comment by lucianlazar1983** [comment]
Same here, in my case it is repetitive. I get this message 2/3 times every day.

**Comment by ntimo** [comment]
I received it too once yesterday. But the cert is still valid for 85 days.

**Comment by andryyy** [comment]
I close this as I decided to remove the check for now.
