### ISSUE TITLE
Do Not Use sha256crypt / sha512crypt - They're Dangerous

### ISSUE THREAD

**Issue by jkaberg** [mailcow/mailcow-dockerized#1913]
Unsure if you've seen this @andryyy, thought I'd poke you just in-case you haven't

https://pthree.org/2018/05/23/do-not-use-sha256crypt-sha512crypt-theyre-dangerous/

**Comment by ntimo** [comment]
Where is sha256crypt being used in Mailcow?

**Comment by jkaberg** [comment]
HN post with comments regarding the link in OP, https://news.ycombinator.com/item?id=17141943

@ntimo I see that SSHA256 is used here; https://github.com/mailcow/mailcow-dockerized/blob/4459b773f1bf89f940bcc809129e206c23ba3c05/data/web/inc/functions.inc.php#L4
But SSHA256 != sha256crypt so I stand corrected.


A few other links on password encryption:
https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet
https://github.com/riverrun/comeonin/wiki/Choosing-the-password-hashing-algorithm
https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016

It seem's like the general advice is (ordered by preferred algo):
- Argon2
- bcrypt
- scrypt
- PBKDF2

Perhaps its worth consider changing this in favor of more secure algos?

**Comment by andryyy** [comment]
Can you check which algorithm is supported by SOGo and Dovecot? I can implement it to mailcow UI then.

**Comment by jkaberg** [comment]
I noticed there is already an issue for [this](https://github.com/mailcow/mailcow-dockerized/issues/1019), closing in favor of that one (I'll reply with my findings there).
