### ISSUE TITLE
Postfix message_size_limit

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#1914]
Hello,

I have set my message_size_limit in postfix to ~100MB but the Mailserver rejects a mail with 50MB Attachement.

`root@mx01:/opt/mailcow-dockerized# docker-compose exec postfix-mailcow postconf | grep message_size_limit
message_size_limit = 104857600`

Do you have any idea why this happens? I try to send the Mail with outlook.

**Comment by andryyy** [comment]
Hi, can you show the reject message? Did you reload Postfix after changing the value?

**Comment by phipag** [comment]
I cannot even click the send button. I directly receive a message, that the maximum attachement size accepted by the mailserver is 25 mb. Also on Mac with Apple Mail or Spark.

And yes i reloaded postfix.

**Comment by phipag** [comment]
just for reference: https://gyazo.com/e9f4b151707bda7a1e7e94804e0404fd

**Comment by andryyy** [comment]
The mail client would not know about Postfix' limitation (correct me if I am wrong). That's strange it prints 25 MB here.

You changed it in main.cf and not with postconf, right?

**Comment by phipag** [comment]
Yes in main.cf. It prints 25 mb in every mailclient i have: outlook, apple mail, spark. In none of them i can even click the send button.

**Comment by andryyy** [comment]
Can you post your postfix-mailcow logs when this happens? It should print the warning here.

**Comment by phipag** [comment]
There are no logs when I try it on the local mail client. With SOGO I can successfully send the message.

**Comment by andryyy** [comment]
Postfix would log it when it rejects the mail because of its size. It would also need to receive the full message to determine wether the msg size was exceeded. Are you sure this isn't a client setting? You are using SMTP, do you?

**Comment by phipag** [comment]
Okay, i think you are right. I must be a local client issue. I will look at this. Thanks for your help. This can be closed.

**Comment by andryyy** [comment]
Let me know what the problem was. Sounds interesting. :-)

**Comment by phipag** [comment]
It seems, that you cannot increase the local attachement size on mac independendly of the mailserver :-D. 

https://answers.microsoft.com/de-de/msoffice/forum/msoffice_outlook-mso_mac-mso_mac2016/outlook-f%C3%BCr-mac-grenzwert-f%C3%BCr-e-mail/7223389f-2c0f-4c86-9235-51def107aadc

**Comment by Phil12n** [comment]
Hi,
Have you found the solution ?
I've got the same issue receiving too large messages from my FAI Mailbox !
Thanks for your help,
Phil
