### ISSUE TITLE
RSPAMD API [HTTP CODE 403] - Errors and Resolution

### ISSUE THREAD

**Issue by mitchellurgero** [mailcow/mailcow-dockerized#1915]
**Notice (you can delete this paragraph)**
RSPAMD container API 403's after latest commit (https://github.com/mailcow/mailcow-dockerized/commit/40888a713a7e66fbbfdd69e73bcb535a0c337d9c) This means login is unavailable. This 403 happens before and during login. No authentication error is shown on screen, just "Unexpected Error has Occurred"

**Describe the bug**
When attempting to look at my spam logs to find a missing email I noticed I could not login to rspamd (password *was* set when I first setup my mailcow instance.)

**How to reproduce Reproduce**
Currently Unknown.

**Expected behavior**
I should have been able to login.

**Screenshots**
Not available.

**Logs**
Not available.

**System**
 - OS: Ubuntu LTS (16.04) with latest docker stable
 - Browser: IE, Firefox, & Chrome.

**Additional context**
Resetting the RSPAMD password allowed for me to login.

**Comment by andryyy** [comment]
Hi, what exactly do you mean with "RSPAMD container API 403's"?

**Comment by mitchellurgero** [comment]
After updating to the commit listed above it would not accept login. HTTP code 403 is "Unauthorized" status. Resetting the RSPAMD password resolved the issue but I wanted to make sure people were aware of the issue if it happened to them.

EDIT: Title adjusted for confusing English.

**Comment by andryyy** [comment]
Ah, Rspamds API. :-) Okay, I will check it!
