### ISSUE TITLE
Traceback in dockerapi-mailcow after clean install

### ISSUE THREAD

**Issue by mxmfft** [mailcow/mailcow-dockerized#1916]
**Describe the bug**
Ugly looking traceback in docker-compose logs immediately after a clean install.

Output from "docker-compose logs" includes:

dockerapi-mailcow_1  |  * Serving Flask app "server" (lazy loading)
dockerapi-mailcow_1  |  * Environment: production
dockerapi-mailcow_1  |    WARNING: Do not use the development server in a production environment.
dockerapi-mailcow_1  |    Use a production WSGI server instead.
dockerapi-mailcow_1  |  * Debug mode: off
dockerapi-mailcow_1  |  * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
dockerapi-mailcow_1  | 172.22.1.6 - - [18/Oct/2018 15:55:04] "GET /containers/json HTTP/1.1" 200 -
dockerapi-mailcow_1  | ----------------------------------------
dockerapi-mailcow_1  | Exception happened during processing of request from ('172.22.1.6', 40194)
dockerapi-mailcow_1  | Traceback (most recent call last):
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
dockerapi-mailcow_1  |     self.finish_request(request, client_address)
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
dockerapi-mailcow_1  |     self.RequestHandlerClass(request, client_address, self)
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
dockerapi-mailcow_1  |     self.finish()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
dockerapi-mailcow_1  |     self.wfile.close()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/socket.py", line 283, in close
dockerapi-mailcow_1  |     self.flush()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/socket.py", line 307, in flush
dockerapi-mailcow_1  |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/ssl.py", line 759, in sendall
dockerapi-mailcow_1  |     v = self.send(data[count:])
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/ssl.py", line 725, in send
dockerapi-mailcow_1  |     v = self._sslobj.write(data)
dockerapi-mailcow_1  | error: [Errno 32] Broken pipe
dockerapi-mailcow_1  | ----------------------------------------
dockerapi-mailcow_1  | 172.22.1.11 - - [18/Oct/2018 15:55:28] "GET /containers/json HTTP/1.1" 200 -

**How to reproduce Reproduce**
Fired up a new virtual server running nothing else. Follow the documentation instructions to install docker, docker-compose down to docker-compose up -d. 

Check logs with "docker-compose logs" for verification of a good install. Above excerpt seems to be only issue.

**Expected behavior**
Clean logs after a good install.

**Screenshots**
Log extract above.

**Logs**
Log extract above.

**System**
Reproduced on fresh install on Ubuntu 18.04 and Debian 9.5

**Additional context**
Installation seems to work fine. Logs look good after a reboot. Just filing because I'd want to know something like this was showing up for my open source projects. Thanks for all the time and effort put into creating and maintaining mailcow.

**Comment by andryyy** [comment]
It has probably not finished creating the certificate. Thanks, I will check that.

**Comment by andryyy** [comment]
Not sure, but it could be fixed. Anyone still sees it?

**Comment by mxmfft** [comment]
Just fired up a clean Ubuntu 18.04 and installed from scratch. Same traceback still in logs:

dockerapi-mailcow_1  |  * Serving Flask app "server" (lazy loading)
dockerapi-mailcow_1  |  * Environment: production
dockerapi-mailcow_1  |    WARNING: Do not use the development server in a production environment.
dockerapi-mailcow_1  |    Use a production WSGI server instead.
dockerapi-mailcow_1  |  * Debug mode: off
dockerapi-mailcow_1  |  * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
dockerapi-mailcow_1  | 172.22.1.7 - - [28/Oct/2018 22:43:54] "GET /containers/json HTTP/1.1" 200 -
dockerapi-mailcow_1  | ----------------------------------------
dockerapi-mailcow_1  | Exception happened during processing of request from ('172.22.1.7', 56642)
dockerapi-mailcow_1  | Traceback (most recent call last):
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
dockerapi-mailcow_1  |     self.finish_request(request, client_address)
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
dockerapi-mailcow_1  |     self.RequestHandlerClass(request, client_address, self)
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
dockerapi-mailcow_1  |     self.finish()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
dockerapi-mailcow_1  |     self.wfile.close()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/socket.py", line 283, in close
dockerapi-mailcow_1  |     self.flush()
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/socket.py", line 307, in flush
dockerapi-mailcow_1  |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/ssl.py", line 759, in sendall
dockerapi-mailcow_1  |     v = self.send(data[count:])
dockerapi-mailcow_1  |   File "/usr/lib/python2.7/ssl.py", line 725, in send
dockerapi-mailcow_1  |     v = self._sslobj.write(data)
dockerapi-mailcow_1  | error: [Errno 32] Broken pipe
dockerapi-mailcow_1  | ----------------------------------------

**Comment by andryyy** [comment]
It's crazy it happens _after_ the first GET request. Could you post the same logs with timestamps? `docker-compose logs -t`.

**Comment by mxmfft** [comment]
As requested:

dockerapi-mailcow_1  | 2018-10-29T18:43:01.951442876Z  * Serving Flask app "server" (lazy loading)
dockerapi-mailcow_1  | 2018-10-29T18:43:01.980376248Z  * Environment: production
dockerapi-mailcow_1  | 2018-10-29T18:43:01.980420285Z    WARNING: Do not use the development server in a production environment.
dockerapi-mailcow_1  | 2018-10-29T18:43:01.980430424Z    Use a production WSGI server instead.
dockerapi-mailcow_1  | 2018-10-29T18:43:01.980436648Z  * Debug mode: off
dockerapi-mailcow_1  | 2018-10-29T18:43:02.008329034Z  * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
dockerapi-mailcow_1  | 2018-10-29T18:43:30.159045492Z 172.22.1.8 - - [29/Oct/2018 18:43:30] "GET /containers/json HTTP/1.1" 200 -
dockerapi-mailcow_1  | 2018-10-29T18:43:30.175796160Z ----------------------------------------
dockerapi-mailcow_1  | 2018-10-29T18:43:30.178908081Z Exception happened during processing of request from ('172.22.1.8', 58964)
dockerapi-mailcow_1  | 2018-10-29T18:43:30.179127247Z Traceback (most recent call last):
dockerapi-mailcow_1  | 2018-10-29T18:43:30.179303719Z   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
dockerapi-mailcow_1  | 2018-10-29T18:43:30.183630438Z     self.finish_request(request, client_address)
dockerapi-mailcow_1  | 2018-10-29T18:43:30.183823703Z   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
dockerapi-mailcow_1  | 2018-10-29T18:43:30.183999420Z     self.RequestHandlerClass(request, client_address, self)
dockerapi-mailcow_1  | 2018-10-29T18:43:30.184143874Z   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
dockerapi-mailcow_1  | 2018-10-29T18:43:30.184388918Z     self.finish()
dockerapi-mailcow_1  | 2018-10-29T18:43:30.184534843Z   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
dockerapi-mailcow_1  | 2018-10-29T18:43:30.184696282Z     self.wfile.close()
dockerapi-mailcow_1  | 2018-10-29T18:43:30.184839231Z   File "/usr/lib/python2.7/socket.py", line 283, in close
dockerapi-mailcow_1  | 2018-10-29T18:43:30.185827394Z     self.flush()
dockerapi-mailcow_1  | 2018-10-29T18:43:30.186761350Z   File "/usr/lib/python2.7/socket.py", line 307, in flush
dockerapi-mailcow_1  | 2018-10-29T18:43:30.186936068Z     self._sock.sendall(view[write_offset:write_offset+buffer_size])
dockerapi-mailcow_1  | 2018-10-29T18:43:30.187081807Z   File "/usr/lib/python2.7/ssl.py", line 759, in sendall
dockerapi-mailcow_1  | 2018-10-29T18:43:30.192631246Z     v = self.send(data[count:])
dockerapi-mailcow_1  | 2018-10-29T18:43:30.192801896Z   File "/usr/lib/python2.7/ssl.py", line 725, in send
dockerapi-mailcow_1  | 2018-10-29T18:43:30.192985627Z     v = self._sslobj.write(data)
dockerapi-mailcow_1  | 2018-10-29T18:43:30.193155196Z error: [Errno 32] Broken pipe
dockerapi-mailcow_1  | 2018-10-29T18:43:30.193399302Z ----------------------------------------

**Comment by mxmfft** [comment]
Addendum: Just re-read the whole log output looking for any other suspicious entries. Just above the log lines above I found:

dovecot-mailcow_1    | 2018-10-29T18:43:20.756584036Z Waiting for database to come up...
dovecot-mailcow_1    | 2018-10-29T18:43:22.775771362Z Uptime: 1  Threads: 8  Questions: 2  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables:
 11  Queries per second avg: 2.000
dovecot-mailcow_1    | 2018-10-29T18:43:23.165211239Z doveconf: Fatal: Error in configuration file /usr/local/etc/dovecot/dovecot.conf line 293: plu
gin/5/mail_crypt_global_private_key: Can't open file /mail_crypt/ecprivkey.pem: No such file or directory
dovecot-mailcow_1    | 2018-10-29T18:43:27.995481991Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow_1    | 2018-10-29T18:43:27.995596172Z                                  Dload  Upload   Total   Spent    Left  Speed
100 93767  100 93767    0     0  57003      0  0:00:01  0:00:01 --:--:-- 57001
dovecot-mailcow_1    | 2018-10-29T18:43:29.665157599Z 20_blatspammer.cf
dovecot-mailcow_1    | 2018-10-29T18:43:29.665448291Z 70_HS_body.cf
dovecot-mailcow_1    | 2018-10-29T18:43:29.679891622Z 70_HS_header.cf
dovecot-mailcow_1    | 2018-10-29T18:43:29.729502065Z /usr/local/bin/sa-rules.sh: line 19: jq: command not found
dovecot-mailcow_1    | 2018-10-29T18:43:29.729894577Z /usr/local/bin/sa-rules.sh: line 19: jq: command not found
dovecot-mailcow_1    | 2018-10-29T18:43:31.374510057Z 2018-10-29 18:43:31,374 CRIT Set uid to user 0
dovecot-mailcow_1    | 2018-10-29T18:43:31.389125515Z 2018-10-29 18:43:31,388 INFO supervisord started with pid 1
dovecot-mailcow_1    | 2018-10-29T18:43:32.392426828Z 2018-10-29 18:43:32,391 INFO spawned: 'processes' with pid 98
dovecot-mailcow_1    | 2018-10-29T18:43:32.394865355Z 2018-10-29 18:43:32,394 INFO spawned: 'cron' with pid 99
dovecot-mailcow_1    | 2018-10-29T18:43:32.427018958Z 2018-10-29 18:43:32,426 INFO spawned: 'dovecot' with pid 100
dovecot-mailcow_1    | 2018-10-29T18:43:32.473678800Z 2018-10-29 18:43:32,473 INFO spawned: 'syslog-ng' with pid 101

**Comment by andryyy** [comment]
The jq bug is already fixed in the upcoming Dovecot image with v2.3.3.

This `doveconf: Fatal: Error in configuration file /usr/local/etc/dovecot/dovecot.conf` is a good catch, thanks. :-) Will fix it now.
