### ISSUE TITLE
Dockercompose-Versionsabfrage ist leer

### ISSUE THREAD

**Issue by c0by85** [mailcow/mailcow-dockerized#1919]
Aktuell ist die dockercompose Datei leer, selbst nach neuem Download. Sorry für die unzureichenden Daten. Wurde am Handy getippt. Ubuntu 18.04.01 LTS. Fehler trat heute auf. Probiere noch Screenshots anzuhängen.

**Comment by andryyy** [comment]
Nicht leer: https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml 👍

**Comment by c0by85** [comment]
![screenshot_20181019-122135](https://user-images.githubusercontent.com/25707747/47212830-8f27b000-d399-11e8-80fa-f5e655ed2f6a.jpg)

**Comment by c0by85** [comment]
Nicht die Konfiguration.

**Comment by c0by85** [comment]
Demzufolge ist mein Mailserver down.

**Comment by mkuron** [comment]
Bestätigt:
```
curl -i https://www.servercow.de/docker-compose/latest.php
HTTP/1.1 200 OK
Date: Fri, 19 Oct 2018 10:23:50 GMT
Server: Apache
Content-Length: 0
Content-Type: text/html; charset=UTF-8

```

Bis @andryyy das repariert hat, folgenden Befehl benutzen:
```
curl -Lo /usr/local/bin/docker-compose 
https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
```

**Comment by c0by85** [comment]
Und danach nur docker-compose up -d? Weil das Updatescript zerlegt wieder alles.

**Comment by andryyy** [comment]
Ist repariert, sorry.
