### ISSUE TITLE
Recipient aliases not handled as intended?

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#192]
I think we already had a similar issue about sender aliases in the past (#29). And we changed the recipient part about it in our config as well, however we accidentally killed it and therefore I just had to re-add it and thought maybe this is a change which is generally interesting.

The current default SQL of the the generated `mysql_virtual_alias_domain_maps.cf` in https://github.com/andryyy/mailcow-dockerized/blob/master/data/Dockerfiles/postfix/postfix.sh#L44 looks like this:
```sql
SELECT username 
FROM   mailbox, 
       alias_domain 
WHERE  alias_domain.alias_domain = '%d' 
       AND mailbox.username = Concat('%u', '@', alias_domain.target_domain) 
       AND mailbox.active = 1 
       AND alias_domain.active = '1' 
```  
This has the effect that only `username-of-mailbox@alias-domain.de` to the mailbox will be delivered but for example `some-alias-of-mailbox@alias-domain.de` will give a `Recipient address rejected: User unknown in virtual mailbox table`.

Therefore I changed this to
```sql
SELECT username 
FROM   mailbox, 
       alias_domain, 
       alias 
WHERE  alias_domain.alias_domain = '%d' 
       AND ( mailbox.username = Concat('%u', '@', alias_domain.target_domain) 
              OR ( alias.address = Concat('%u', '@', alias_domain.target_domain) 
                   AND mailbox.username = alias.GOTO ) ) 
       AND alias_domain.target_domain = mailbox.domain 
       AND mailbox.active = 1 
       AND alias_domain.active = '1' 
```  
which should have the effect that `any-alias-of-mailbox@alias-domain.de` will be delivered as well, while you could for example create `a-specific-alias-for-alias-domain@alias-domain.de` and `a-specific-alias-for-alias-domain@primary-domain.de` wouldn't be delivered.

This feels logical in our setup as alias domains should always inherit the properties of its parents but not necessarily the parents from their alias domains. So maybe it's worth adding it to Mailcow in general ;-)

**Comment by andryyy** [comment]
Hi,
Thanks for your detailed changes, they might be useful for some people who want to change that behaviour. :)
I actually changed this behavior as some people wanted to handle alias independently.

**Comment by sriccio** [comment]
Hi,

I found out that this query works for aliases that only have one GOTO recipient.

After playing a bit I found out that this query works with aliases that have multiple comma delimited GOTOs:

```
SELECT username FROM mailbox, alias_domain, alias
 WHERE  alias_domain.alias_domain = '%d'
       AND ( mailbox.username = Concat('%u', '@', alias_domain.target_domain)
              OR ( alias.address = Concat('%u', '@', alias_domain.target_domain)
                   AND FIND_IN_SET(mailbox.username, alias.GOTO) ) )
       AND alias_domain.target_domain = mailbox.domain
       AND mailbox.active = 1
       AND alias_domain.active = '1'
EOF
```

Seems to work but not sure it has no side effects :)

Any comments @andryyy ?

**Comment by andryyy** [comment]
If that's what you want, it should work fine. FIND_IN_SET is probably even better than "LIKE" or "REGEXP".

The default behavior will not be changed though.

**Comment by sriccio** [comment]
Yes, this is for a specific setup with one main domain and many domain aliases.

I needed to have all aliases answering under every domain aliases without having to create them under every DA.

Seems to work, just wanted to share it if someone needed it :)
