### ISSUE TITLE
/usr/local/bin/docker-compose: line 1: Not: command not found

### ISSUE THREAD

**Issue by timscha** [mailcow/mailcow-dockerized#1920]
Hi!

Updated mailcow as always. Now every docker container is removed.

If I try an docker-compose up -d I got this error:

/usr/local/bin/docker-compose: line 1: Not: command not found

Tested on two systems- Debian and CentOS.

**Comment by andryyy** [comment]
Fixed, sorry. Run update again, please.

**Comment by Braintelligence** [comment]
Can't blame you, since people keep talking in German and thus provoking them, but this could be a duplicate of https://github.com/mailcow/mailcow-dockerized/issues/1919
Basically your docker-compose binary might be broken.
