### ISSUE TITLE
Issue with restore helper script

### ISSUE THREAD

**Issue by MoritzWeber0** [mailcow/mailcow-dockerized#1921]
I'm having some trouble recovering Mailcow. 
I have changed the server and wanted to use the restore helper script. 

When i restore "SQL DB", i get the following errors in the console:
`[Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade`

When i try to access the mailcow admin web interface, i get the error: 

`Connection to database failed.
The following error was reported:
SQLSTATE[HY000] [1045] Access denied for user 'mailcow'@'localhost' (using password: YES)`

Is there an order in which I need to restore the entries in the restore script? 
How can I fix this problem?

**Comment by MoritzWeber0** [comment]
Running ./update.sh fixed the issue.

**Comment by andryyy** [comment]
Sometimes you also need to run mysql_upgrade. I'm thinking about adding it by default.
