### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by PWNYYY** [mailcow/mailcow-dockerized#1923]
Hi, 
i want to install the Mailcow MailServer on my vServer.
(3vCores, 3GB RAM, 1GB/s up/down)
OS: Debian 9

-----------------------------------------------------------------------------

I stuck on Step 5.

if i type in "docker-compose pull"
i got this error:

root@GermanMafia:/opt/mailcow-dockerized-master# docker-compose pull
WARNING: The TZ variable is not set. Defaulting to a blank string.
WARNING: The DBROOT variable is not set. Defaulting to a blank string.
WARNING: The DBNAME variable is not set. Defaulting to a blank string.
WARNING: The DBUSER variable is not set. Defaulting to a blank string.
WARNING: The DBPASS variable is not set. Defaulting to a blank string.
WARNING: The MAILCOW_HOSTNAME variable is not set. Defaulting to a blank string.
WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

![screenshot_19](https://user-images.githubusercontent.com/44307473/47248824-82dd3a80-d40d-11e8-8dd4-59589da753d3.png)

What did i wrong?
I hope anyone can help me.

Greetings from Germany

**Comment by mitchellurgero** [comment]
Looks like your config might be blank?

**Comment by MAGICCC** [comment]
Did you generate a config file with the generate_config.sh script?

**Comment by andryyy** [comment]
Besides that, Docker seems not to be running.

**Comment by PWNYYY** [comment]
@andryyy How can i start Docker?
@MAGICCC Yes, i generated a config.
@mitchellurgero I watched a Tutorial and they changed nothing in the config.

**Comment by MAGICCC** [comment]
Enable autostartDocker on startup with `systemctl enable docker.service` and start it with `systemctl start docker.service`
Also can you provide us the config, you can redact sensitive infos
And whats the output of `ls -lah` from your mailcow folder?

Which tutorial did you use? You should only use https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by PWNYYY** [comment]
Thanks.

When i start with "**systemctl start docker.service**" 

root@GermanMafia:/opt/mailcow-dockerized-master# systemctl start docker.service
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**This is the Output from ls -lah**

root@GermanMafia:/opt/mailcow-dockerized-master# ls -lah
total 128K
drwxr-xr-x 5 root root 4.0K Oct 20 15:47 .
drwxr-xr-x 7 root root 4.0K Oct 20 01:42 ..
-rw-r--r-- 1 root root   12 Oct 19 11:12 .env
drwxr-xr-x 3 root root 4.0K Oct 20 01:42 .github
-rw-r--r-- 1 root root  685 Oct 19 11:12 .gitignore
-rw-r--r-- 1 root root 1.8K Oct 19 11:12 .travis.yml
-rw-r--r-- 1 root root 3.2K Oct 19 11:12 CODE_OF_CONDUCT.md
-rw-r--r-- 1 root root  954 Oct 19 11:12 CONTRIBUTING.md
-rw-r--r-- 1 root root  35K Oct 19 11:12 LICENSE
-rw-r--r-- 1 root root  746 Oct 19 11:12 README.md
drwxr-xr-x 6 root root 4.0K Oct 20 01:42 data
-rw-r--r-- 1 root root  13K Oct 19 11:12 docker-compose.yml
-rwxrwxrwx 1 root root 4.5K Oct 19 11:12 generate_config.sh
drwxr-xr-x 2 root root 4.0K Oct 20 01:43 helper-scripts
-rw-r--r-- 1 root root 2.7K Oct 20 15:36 mailcow.conf
-rw-r--r-- 1 root root 2.7K Oct 20 01:48 mailcow.conf_backup
-rwxrwxrwx 1 root root  14K Oct 19 11:12 update.sh

I used a German Tutorial from YouTube and the Official Link "https://mailcow.github.io/mailcow-dockerized-docs/install/"

**Comment by PWNYYY** [comment]
And the Config is the standard one. I changed nothing.

The Only one was my Domain and the Region.

mail.germanmafia.eu
Europe/Berlin

**Comment by andryyy** [comment]
Your VPS might be an OpenVZ VM. We cannot help you with getting Docker to work. You need to check the journal etc.

Please also use the docs, not a video tutorial. :-)

**Comment by andryyy** [comment]
I am closing this. Dockerd does not start, it is not a mailcow issue. :-/

Make sure you are not using OpenVZ.

You can still post the Dockerd service logs, maybe someone can help you here.
