### ISSUE TITLE
Add flag to backup script to skip creating archives

### ISSUE THREAD

**Issue by vbrandl** [mailcow/mailcow-dockerized#1926]
**Is your feature request related to a problem? Please describe.**

Since storing my backups on the same machine as mailcow kinda defeats the purpose, I'm syncing my backups to a remote machine using [BorgBackup](https://github.com/borgbackup/borg). Borg can compress files by itself and also does deduplication, so in theory, with each new backup, my repository should only grow by the mails that came in since last time.

Since the backup script provided by mailcow already creates archives, borg is not able to deduplicate anymore.

**Describe the solution you'd like**

Add a flag to the backup script, to skip the creation of archives.

**Comment by andryyy** [comment]
I think someone posted a backup script with Borg today. You may want to try it. :-)

I will rework the backup process in the future, but I cannot add this functionality now, sorry. :-( I hope you understand.
