### ISSUE TITLE
Unable to interact with Postfix configuration wizard

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1927]
**Describe the bug**
`docker-compose up -d` results in a noninteractive prompt from Postfix. Additionally the documentation omits advice on actions to take in response to dialog.

**Logs**
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Postfix Configuration
---------------------

Please select the mail server configuration type that best meets your needs.

 No configuration:
  Should be chosen to leave the current configuration unchanged.
 Internet site:
  Mail is sent and received directly using SMTP.
 Internet with smarthost:
  Mail is received directly using SMTP or by running a utility such
  as fetchmail. Outgoing mail is sent using a smarthost.
 Satellite system:
  All mail is sent to another machine, called a 'smarthost', for delivery.
 Local only:
  The only delivered mail is the mail for local users. There is no network.

  1. No configuration  3. Internet with smarthost  5. Local only
  2. Internet Site     4. Satellite system
General type of mail configuration: 2.
```

**System**
 - OS: Linux: Synology DSM 6

**Comment by mkuron** [comment]
The only situation I could see this happening in is if data/conf wasn't being mounted as a volume into the container. Did you modify docker-compose.yml in any way? Are you sure the Synology Docker integration correctly mounts the volumes?

**Comment by ghost** [comment]
I had to remove the `oom-kill-disable` lines because those were 
preventing me
from even running the container but that's it.

**Comment by andryyy** [comment]
And you probably didn't pull the images but built them.

**Comment by mkuron** [comment]
@andryyy, even if he built the image manually, he shouldn't be getting the configuration wizard. There is no magic in the Dockerfile, so building the image should produce exactly what you have put on Docker Hub.

**Comment by mkuron** [comment]
Hmm, that wizard should indeed only appear during build. And the volume of course isn't mounted at that time. During build the wizard should just complete with some default configuration, which we don't care about because we mount a volume over it later.

**Comment by ghost** [comment]
I am switching to Synology's own MailPlus Server since there doesn't seem to be an easy fix to this. Feel free to close if targeting Synology NASes is not a design concern.

**Comment by mkuron** [comment]
Without a Synology to test, we can‘t ensure that Mailcow works on Synology, though we are not doing anything specific that would prevent it from working. Your problem is probably easy to fix, but we have no way of reproducing it.
