### ISSUE TITLE
New aliases are not created

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#1929]
**Describe the bug**
It is not possible to create new aliases. Wenn I klick "add" in the form of the new alias, the site is reloading and nothing else is happening. When I klick "new Alias" the input of the try before is already filled in

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Create a new alias

**Expected behavior**
A new alias is created

**System**
 - OS: Ubuntu 18.04 LTS (Server), MacOS(Client)
 - Browser: Safari

**Comment by andryyy** [comment]
Can you please clean your browser cache? It is very, very likely a cache issue.

**Comment by mkapra** [comment]
Thank you for your help! It worked! Is there anything in the manual about this?

**Comment by andryyy** [comment]
No, it happens when we change JavaScript code. :-)

**Comment by mkapra** [comment]
ah okay! thank you!
