### ISSUE TITLE
SOGO autodiscover server error

### ISSUE THREAD

**Issue by faxonnet** [mailcow/mailcow-dockerized#193]
mailcow_hostname=domain1.tld
with 2 domains configured : domain1.tld & domain2.tld
SOGO in autodiscover for   domain1.tld set correctly mail server hostname=$mailcow_hostname 
SOGO in autodiscover for   domain2.tld set unwanted hostname mail server hostname=domain2.tld 

why?

**Comment by faxonnet** [comment]
after adding the certificates to domain2 autodiscover now it works correctly

**Comment by andryyy** [comment]
It says FQDN. Please use a valid hostname. domain.tld is not a valid hostname.

**Comment by faxonnet** [comment]
Sorry 
Mailcow_hostname was  mailer.domain1.tld  
Tnks alot for this project is  the best!
 if you include   user authentication  vs LDAP & yubico  for Sogo you have reached perfection.
