### ISSUE TITLE
Can't send email via SOGo

### ISSUE THREAD

**Issue by jjkondrat** [mailcow/mailcow-dockerized#1930]
I am getting the following error when trying to send or reply to an mail with SOGo (roundcube works fine)

cannot send message: (smtp) authentication failure

I didn't see anything obvious in the logs.  I tend to use roundcube, but was informed of this happening on SOGo and would appreciate any thoughts.  I did run an update to see if it would resolve the issue, but there was no change.  Also rebooted afterwards.

Logs:
sogo-mailcow_1       | Oct 21 14:34:48 7ecfe9334ab9 sogod [55]: |SOGo| starting method 'POST' on uri '/SOGo/so/jack@mugglemail.org/Mail/0/folderDrafts/newDraft1540146759-1/send'
sogo-mailcow_1       | Oct 21 14:34:48 7ecfe9334ab9 sogod [55]: <0x0x55dc14397e70[NGImap4Client]> TLS started successfully.
sogo-mailcow_1       | Oct 21 14:34:49 7ecfe9334ab9 sogod [55]: [WARN] <0x0x55dc151fc5c0[SOGoUserDefaults]> expected an NSString for 'SOGoMailComposeFontSize' (ignored)
postfix-mailcow_1    | Oct 21 14:34:49 mail postfix/smtpd[450]: connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
rspamd-mailcow_1     | 2018-10-21 14:34:49 #9(rspamd_proxy) <4cd3a1>; proxy; proxy_accept_socket: accepted milter connection from 172.22.1.10 port 49456
rspamd-mailcow_1     | 2018-10-21 14:34:49 #9(rspamd_proxy) <4cd3a1>; milter; rspamd_milter_process_command: got connection from 172.22.1.248:37660
postfix-mailcow_1    | Oct 21 14:34:49 mail postfix/smtpd[450]: disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 quit=1 commands=2
rspamd-mailcow_1     | 2018-10-21 14:34:49 #9(rspamd_proxy) <4cd3a1>; proxy; proxy_milter_finish_handler: finished milter connection
nginx-mailcow_1      | 98.111.201.185 - - [21/Oct/2018:14:34:49 -0400] "POST /SOGo/so/jack@mugglemail.org/Mail/0/folderDrafts/newDraft1540146759-1/send HTTP/1.1" 405 86 "https://mail.mugglemail.org/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0"
sogo-mailcow_1       | Oct 21 14:34:49 7ecfe9334ab9 sogod [55]: |SOGo| request took 0.272697 seconds to execute
sogo-mailcow_1       | Oct 21 14:34:49 7ecfe9334ab9 sogod [55]: 98.111.201.185 "POST /SOGo/so/jack@mugglemail.org/Mail/0/folderDrafts/newDraft1540146759-1/send HTTP/1.0" 405 86/144 0.277 - - 0
dovecot-mailcow_1    | Oct 21 14:34:49 mail dovecot: imap(jack@mugglemail.org)<713><iDk4ZMF4pMisFgH4>: Logged out in=93 out=1202 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

**System**
 - OS: MacOS
 - Browser: Tried both Safari and Firefox

Thanks,
John

**Comment by andryyy** [comment]
Please post postfix-mailcow logs for the time this happens.

**Comment by jjkondrat** [comment]
I reproduced this at 2:51:27 in those logs.   Output is minimal.
![screen shot 2018-10-21 at 2 53 20 pm](https://user-images.githubusercontent.com/42721057/47270965-22e7b080-d541-11e8-8cd4-8fc25a7aa43a.png)

**Comment by andryyy** [comment]
No, please post the Docker logs:

```
docker-compose logs --tail=200 -f postfix-mailcow
```

Keep this stream open and try to send again. :-)

**Comment by jjkondrat** [comment]
Same time 14:51:27
[postfixout.txt](https://github.com/mailcow/mailcow-dockerized/files/2499508/postfixout.txt)

Thanks!

**Comment by andryyy** [comment]
Okay, you saw the commercial support hint when opening this issue?

**Comment by jjkondrat** [comment]
I apologize, I'll move this there.

**Comment by andryyy** [comment]
It's okay.

Can you post a `git diff origin/master data/conf/sogo data/conf/postfix` and the output of `docker-compose logs -f --tail=200 sogo-mailcow postfix-mailcow` (yes, Postfix too 👍) when this happens, again?

And please mail me from where to where you are trying to send this mail.

Please always post your changes. "sogo.conf" _seems_ not to be original anymore, not sure.

**Comment by jjkondrat** [comment]
Thank you for your help.   I also downloaded an IRC client (haven't used IRC in about 15 years) but will use that next time.

Since I'm new to git and docker I was ignorant of the diff command, but since you had me enter it  it's pretty obvious what the issue was.   I made a change that i had on my old email server for extra hardening, but it didn't impact my RC install, and since I hadn't used SOGo before .  

-  -o smtpd_tls_auth_only=no
+  -o smtpd_tls_auth_only=yes

I reverted the change and restarted the container and SOGo works now!  None of my other minor changes below seems to have a negative impact.   Thanks again!

root@mail:/opt/mailcow-dockerized# git diff origin/master data/conf/sogo data/conf/postfix 
diff --git a/data/conf/postfix/mailcow_anonymize_headers.pcre_ b/data/conf/postfix/mailcow_anonymize_headers.pcre_
new file mode 100644
index 00000000..1d678ffa
--- /dev/null
+++ b/data/conf/postfix/mailcow_anonymize_headers.pcre_
@@ -0,0 +1,9 @@
+if /^\s*Received:.*Authenticated sender.*\(Postcow\)/
+/^\s*Received:.*Authenticated sender:(.+)/
+  REPLACE Received: from localhost (localhost [127.0.0.1]) (Authenticated sender:$1
+/^\s*User-Agent/        IGNORE
+/^\s*X-Enigmail/        IGNORE
+/^\s*X-Mailer/          IGNORE
+/^\s*X-Originating-IP/  IGNORE
+/^\s*X-Forward/         IGNORE
+endif
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index fbcb3d5e..69b4c681 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -85,7 +85,7 @@ smtpd_sasl_authenticated_header = yes
 smtpd_sasl_path = inet:dovecot:10001
 smtpd_sasl_type = dovecot
 smtpd_sender_login_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf
-smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch, permit_mynetworks, permit_sasl_authenticated, reject_unlisted_sender, reject_unknown_sender_domain
+smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch, permit_mynetworks, permit_sasl_authenticated, reject_unlisted_sender, reject_unknown_sender_domain, pcre:/opt/postfix/conf/reject_domains 
 smtpd_soft_error_limit = 3
 smtpd_tls_auth_only = yes
 smtpd_tls_dh1024_param_file = /etc/ssl/mail/dhparams.pem
diff --git a/data/conf/postfix/master.cf b/data/conf/postfix/master.cf
index 4911271e..318e4a60 100644
--- a/data/conf/postfix/master.cf
+++ b/data/conf/postfix/master.cf
@@ -11,7 +11,7 @@ submission inet n       -       n       -       -       smtpd
   -o tls_preempt_cipherlist=yes
 588 inet n      -       n       -       -       smtpd
   -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
-  -o smtpd_tls_auth_only=no
+  -o smtpd_tls_auth_only=yes
 590 inet n      -       n       -       -       smtpd
   -o smtpd_client_restrictions=permit_mynetworks,reject
   -o smtpd_tls_auth_only=no
diff --git a/data/conf/postfix/reject_domains b/data/conf/postfix/reject_domains
new file mode 100644
index 00000000..7e59b4e5
--- /dev/null
+++ b/data/conf/postfix/reject_domains
@@ -0,0 +1,21 @@
+/\.bid$/ REJECT We reject all .bid domains
+/\.click$/ REJECT We reject all .click domains
+/\.date$/ REJECT We reject all .date domains
+/\.diet$/ REJECT We reject all .diet domains
+/\.download$/ REJECT We reject all .download domains
+/\.jp$/ REJECT We reject all .jp domains
+/\.link$/ REJECT We reject all .link domains
+/\.party$/ REJECT We reject all .party domains
+/\.pro$/ REJECT We reject all .pro domains
+/\.py$/ REJECT We reject all .py domains
+/\.review$/ REJECT We reject all .review domains
+/\.science$/ REJECT We reject all .science domains
+/\.space$/ REJECT We reject all .space domains
+/\.stream$/ REJECT We reject all .stream domains
+/\.top$/ REJECT We reject all .top domains
+/\.win$/ REJECT We reject all .win domains
+/\.work$/ REJECT We reject all .work domains
+/\.xyz$/ REJECT We reject all .xyz domains
+/\.zip$/ REJECT We reject all .zip domains
+/haardtobelieve.club$/ REJECT SPAM
+/domai.club$/ REJECT SPAM
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index b5979c82..27c39d12 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -14,7 +14,7 @@
     SOGoEnableEMailAlarms = NO;
     SOGoFoldersSendEMailNotifications = YES;
     SOGoForwardEnabled = YES;
-    SOGoUIAdditionalJSFiles = (js/theme-blue.js);
+    //SOGoUIAdditionalJSFiles = (js/theme-blue.js);
 
     // Multi-domain setup
     // Domains are isolated, you can define visibility options here.
root@mail:/opt/mailcow-dockerized#
