### ISSUE TITLE
Can't send mail after new setup

### ISSUE THREAD

**Issue by wtrdk** [mailcow/mailcow-dockerized#1936]
Hi,

I had a fine working mailcow installation on a virtual server, but I wanted to move it to a physical server.
I decided to setup a complete new mailcow installation. Setup went just fine, I can receive mail, but not send mail.

I get these messages in the postfix log:
`
23-10-2018 11:00:42 | info | B88245E60A5F: to=<wouter.dijk@*****.com>, relay=none, delay=94, delays=1.8/0.02/92/0, dsn=4.4.1, status=deferred (connect to alt1.aspmx.l.google.com[2404:6800:4003:c02::1b]:25: Network is unreachable)
-- | -- | --
23-10-2018 11:00:42 | info | connect to alt1.aspmx.l.google.com[2404:6800:4003:c02::1b]:25: Network is unreachable
23-10-2018 11:00:41 | info | connect to alt1.aspmx.l.google.com[74.125.68.26]:25: Connection timed out
23-10-2018 11:00:29 | info | 52E275E60A3E: to=<wouter.dijk@*****.com>, relay=none, delay=604, delays=512/0.02/92/0, dsn=4.4.1, status=deferred (connect to alt1.aspmx.l.google.com[2404:6800:4003:c02::1b]:25: Network is unreachable)
23-10-2018 11:00:29 | info | connect to alt1.aspmx.l.google.com[2404:6800:4003:c02::1b]:25: Network is unreachable
23-10-2018 11:00:28 | info | connect to alt1.aspmx.l.google.com[74.125.68.26]:25: Connection timed out
23-10-2018 11:00:11 | info | connect to alt2.aspmx.l.google.com[108.177.125.26]:25: Connection timed out
`

Telnetting to the server mentioned in the error returns this:
`telnet alt2.aspmx.l.google.com 25
Trying 108.177.125.26...
Trying 2404:6800:4008:c01::1b...
telnet: Unable to connect to remote host: Network is unreachable`

I use a relay host, and testing it in mailcow looks just fine (all green).

It worked perfectly on my virtual server... Does anyone have a clue?

**Comment by andryyy** [comment]
Hi, looks like a firewall. You can't even telnet Google MX' from your host?

**Comment by wtrdk** [comment]
No, Telnet also returns a 'Network is unreachable' error.
Firewall is turned off...

**Comment by andryyy** [comment]
I cannot help then. mailcow does not block your network communication on the host. :-(

**Comment by wtrdk** [comment]
Google helped met out! I've changed `inet_protocols = all `to `inet_protocols = ipv4` in `/data/conf/postfix/main.conf` and now everything works fine!
