### ISSUE TITLE
Rspamd /rspamd/learnspam endpoint returns 404

### ISSUE THREAD

**Issue by mnin** [mailcow/mailcow-dockerized#1938]
**Describe the bug**
The Rspamd endpoint /rspamd/learnspam returns 404

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Open the rspamd backend
2. Click on `Learning`
3. Insert mail source code into the SPAM source textbox
4. Click on `Upload Text`

**Screenshots**
![bildschirmfoto 2018-10-23 um 22 36 55](https://user-images.githubusercontent.com/92227/47389111-326b2300-d714-11e8-9e81-ae286fc64e55.png)

**Logs**
```
nginx-mailcow_1      | xxxx::x - - [23/Oct/2018:22:34:22 +0200] "POST /rspamd/learnspam HTTP/2.0" 404 99 "https://x.x.x/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
```

**System**
 - Browser: Chrome, Safari...

**Comment by andryyy** [comment]
Check the rspamd-mailcow logs, it is actually passed to Rspamd. The response the browser receives from Rspamd is valid, too. For example: `{"error":"<undef> has been already learned as spam, ignore it"}`

It just seems to return 404 for whatever reason as html response code when the text is invalid or another Rspamd error occured.

When I enter "asdasd" it returns 404 and a JSON error in the JS response (via console). When I paste valid and full mail content, it returns 200.

As it also returns 404 on "already learned", you should report that to Rspamd.

**Comment by mnin** [comment]
Fixed, thanks!
