### ISSUE TITLE
Queue manager not displaying queue

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#1939]
The queue manager that was added to Mailcow does not seem to be displaying the mail queue, on my server I currently got a few mail in queue <pre> docker-compose exec postfix-mailcow mailq </pre> displays them but on the web UI its blank the delete all button seem to be working fine.

I have not included any log as i can't see any error or any other useful info why it not working.

![image](https://user-images.githubusercontent.com/14151000/47393581-d6a29900-d717-11e8-9483-1ee07a914368.png)

**Comment by andryyy** [comment]
It’s very important to clean the browser cache.

**Comment by andryyy** [comment]
Please clean it completely and close your browser. If it still fails, check the dev console, please.

**Comment by K2rool** [comment]
That fixed it, I feel a bit stupid opening this bug report, I forgot browser have a tendency of caching js files.

Sorry for wasting you time.
