### ISSUE TITLE
Acme don´t get renewed when own certificate is placed

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1940]
**Describe the bug**
If a own certificate is placed for e.g. mail.mailcow.host in ```data/assets/ssl/cert.pem```, acme.sh wont request the certs for the further autodiscover / autoconfig Domains:

```Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...```

IMHO this should request, too

**How to reproduce Reproduce**
Place a cert as described in https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#use-own-certificates

**Expected behavior**
It should still request the le cert for the autoconfig / autodiscover Domains.

**Logs**
```Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...```

**System**
 - Ubuntu 17.10

**Comment by andryyy** [comment]
How? It can only handle one certificate.

**Comment by develth** [comment]
E.g. by using another vhost for the autoX Subdomains

**Comment by andryyy** [comment]
See #461, that's a feature I see for commercial setups. There are workarounds described in this issue and a reason why it has no high priority at the bottom. 

I will close it as duplicate. :-)

**Comment by develth** [comment]
Hmm - would handle it a little different.
#461 could also happen with providing this Feature. 

Could change this from bug to feature and lets check if i could provide a PR. 
Or should i open a new issue for that

**Comment by andryyy** [comment]
It is very, very, very important that a feature that covers this can be used universally, does not break current configs or migrates them flawless. It would be much easier to just use a reverse proxy for the autodiscover domains, everything else is very likely to break acme-mailcow.

I don't plan to integrate it at the moment.
