### ISSUE TITLE
Improve "Move vmail volume" in documentation 

### ISSUE THREAD

**Issue by XUBIUM** [mailcow/mailcow-dockerized#1942]
Hello, 

The "Move vmail volume" documentation page could use more details. 
Would this procedure be valid to be included?

- Use docker volume inspect mailcowdockerized_vmail-vol-1 to locate the current vmail folder
- Copy _data to the new folder using cp -a
- build the docker-compose.override.yml file
- docker-compose down
- docker volume rm mailcowdockerized_vmail-vol-1
- docker-compose up -d

If this doesn't have issues, I could provide a more detailed explanation to include in the documentation.

**Comment by andryyy** [comment]
Feel free to create a PR. Just run „down“ first, then create a override.yml. :)

**Comment by XUBIUM** [comment]
Hello, I just created the PR: Update u_e-dovecot-vmail-volume.md 113 at 
mailcow/mailcow-dockerized-docs
