### ISSUE TITLE
PHP-FPM Not Working after Update

### ISSUE THREAD

**Issue by BlamKiwi** [mailcow/mailcow-dockerized#1943]
After an update of a test lab server ( roughly ~120 commits behind HEAD ) a working deployment now fails to start correctly. I've reverted the server using a snapshot to get back to a working state for now.  

The update process itself seemed to be successful. However the MailCow Admin website and NextCloud fails with a 502 upon starting swarm. The SoGO login page works, however logging in fails with a generic error. The only log entry I can find that indicates what the problem might be is ```mailcowdockerized_php-fpm-mailcow_1 exited with code 137```. Which will appear every couple of minutes (I assume from the watchdog process killing the container). 

**System**
 - OS: Ubuntu 18 LTS Server
 - Browser: chrome

**Additional context**
Running inside a libvirt virtual machine.

**Comment by andryyy** [comment]
We need logs. 

php-fpm-mailcow and mysql-mailcow are useful here. :)

**Comment by develth** [comment]
Same with my one.

mysql:
```
mysql-mailcow_1      | 2018-10-25 21:16:19 140464088135424 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
```

**Comment by develth** [comment]
Nothing with php-fpm:

```
php-fpm-mailcow_1    | Uptime: 6  Threads: 9  Questions: 27  Slow queries: 0  Opens: 23  Flush tables: 1  Open tables: 17  Queries per second avg: 4.500
php-fpm-mailcow_1    | Running DB init...
php-fpm-mailcow_1    | Fixed _sogo_static_view
php-fpm-mailcow_1    | Cleaned up memcached
php-fpm-mailcow_1    | Uptime: 93  Threads: 83  Questions: 2245  Slow queries: 0  Opens: 308  Flush tables: 1  Open tables: 219  Queries per second avg: 24.139
php-fpm-mailcow_1    | Running DB init...
php-fpm-mailcow_1    | Fixed _sogo_static_view
php-fpm-mailcow_1    | Cleaned up memcached
php-fpm-mailcow_1    | Uptime: 198  Threads: 86  Questions: 3399  Slow queries: 0  Opens: 396  Flush tables: 1  Open tables: 219  Queries per second avg: 17.166
php-fpm-mailcow_1    | Running DB init...
php-fpm-mailcow_1    | Fixed _sogo_static_view
php-fpm-mailcow_1    | Cleaned up memcached
php-fpm-mailcow_1    | Uptime: 275  Threads: 86  Questions: 4271  Slow queries: 0  Opens: 474  Flush tables: 1  Open tables: 219  Queries per second avg: 15.530
php-fpm-mailcow_1    | Running DB init...
php-fpm-mailcow_1    | Fixed _sogo_static_view
php-fpm-mailcow_1    | Cleaned up memcached
```

**Comment by develth** [comment]
Got Mails from watchdog:

connect to address 172.22.1.9 and port 9001: Connection refused
connect to address 172.22.1.9 and port 9002: Connection refused

**Comment by andryyy** [comment]
Try 

```
source mailcow.conf
docker exec -it $(docker ps -qf name=mysql-mailcow) bash -c "mysql_upgrade -uroot -p${DBROOT}"
```

**Comment by develth** [comment]
Runned that - still loggin it. 
But don´t think that will crash the php-fm

**Comment by develth** [comment]
Until now - no more mysql warnings.
php-fpm still not working (watchdog barks)

**Comment by develth** [comment]
docker port doesn´t list anything

**Comment by andryyy** [comment]
After running that upgrade command, try docker-compose down and up -d

**Comment by develth** [comment]
No more mysql warnings.
Still no php-fpm

**Comment by andryyy** [comment]
Does it exit with 137? Any custom changes to the database?

**Comment by develth** [comment]
Where can i see that it exist with 137, i pasted full fpm logs.

I didn´t changed the database

**Comment by andryyy** [comment]
`docker ps -af name=php`.

I can check it on the machine, if you want to.

**Comment by develth** [comment]
```594dc850d719        mailcow/phpfpm:1.23                   "/docker-entrypoint.…"   10 minutes ago      Up 8 seconds             9000/tcp            mailcowdockerized_php-fpm-mailcow_1```

**Comment by develth** [comment]
i´m on irc @develth  - we could do a teamviewer

**Comment by andryyy** [comment]
It happened due to watchdog-mailcow killing php-fpm-mailcow while it was still updating the db schema.

**Comment by BlamKiwi** [comment]
So is the fix in my case to run ```update.sh``` with watchdog disabled in ```mailcow.conf```.

It would be worth making watchdog more flexible, so it can be aware of things like database and schema updates in flight.

**Comment by andryyy** [comment]
You can try if it is the same problem for you. When was your last update?

Yes, we should add a check.

**Comment by andryyy** [comment]
If it doesn't work I can check it on your installation, too.

**Comment by lucianlazar1983** [comment]
Same problem occured to me on 2 separate instances, but it did resolve all by itself after 5 minutes or so and so far since 2 hours ago no more errors.

**Comment by BlamKiwi** [comment]
Running the update with watchdog disabled seemed to have fix this issue.
