### ISSUE TITLE
 Could not move maildir to garbage collector: Unknown command

### ISSUE THREAD

**Issue by isclever** [mailcow/mailcow-dockerized#1944]
**Describe the bug**
When deleting a mail box you will get a popup message saying " Could not move maildir to garbage collector: Unknown command".  When looking at the vmail volume, the mailbox remains and is not moved to the garbage folder.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Create mailbox
2. Delete mail box
3. Get error message

Reproducible at https://demo.mailcow.email/

**Expected behavior**
Expected mailbox to be deleted with no error message.

**Screenshots**

**Logs**
In response to the api/v1/delete/mailbox POST (Sanitized): 
`[{"type":"warning","log":["mailbox","delete","mailbox",{"username":["deleteme@xxxx"]},null],"msg":"Could not move maildir to garbage collector: Unknown command"},{"type":"success","log":["mailbox","delete","mailbox",{"username":["deleteme@xxxx"]},null],"msg":["mailbox_removed","deleteme@xxxx"]}]`

**System**
 - OS: CentOS - Docker
 - Browser: Firefox 62.0.3

**Comment by andryyy** [comment]
Hi, thanks and sorry. Will fix this in a few hours. :-(

**Comment by andryyy** [comment]
Fixed with 0d4e89e62b2c6cd7bc099649cdb8a7053b949d9d
