### ISSUE TITLE
Restore process - Can't restore to new server

### ISSUE THREAD

**Issue by chessw** [mailcow/mailcow-dockerized#1946]
Hello All,

First off, thank you to the devs of MailCow for a great product. This is a very polished product that just seems to get better and better.

While this is not a bug, it's not a feature request either. I'm looking for the full process to restore mailcow to a new server. My users are asking for larger mailboxes, and while I'd love to say no, one has the power to make me sleep on the couch :)

I've searched for topics on this and have taken all of them to see if I can put together the process for a restore to new server, but I always fail. Seems to be around connecting to the database.

Here is what I have seen as the process so far. Please let me know if there is any missteps that I need to do.

1 - Create backup on existing server -> ./helper-scripts/backup_and_restore.sh backup all
2 - Copy the back up off the server (using filezilla) as well as the mailcow.conf
3 - Run through the install steps up to step 4 from the Installation doc. (clone mailcow to the new server)
4 - Copy the backup to the new server using filezilla. Replace the mailcow.conf file with the one from the original server.
5 - Install MailCow (docker-compose pull, docker-compose up -d)
6 - Restore backup

It is after the restore that it fails. I get the following error:
Error: userdb lookup: connect(/usr/local/var/run/dovecot/auth-userdb) failed: No such file or directory
doveadm: Error: Failed to iterate through some users
60dfe07efff5

If I can get to the SoGo login page accounts don't work, and the config pages only the initial username and password work to log in. This leads me to believe I'm either not able to connect to the DB or the DB is not getting restored.

I suspect I am missing a step but I've not sure where. I've gone through every post I can find on the backup/restore process, and that is how I've gotten to where I am now. 

In case this makes any difference, I'm using Ubuntu 18.04 on the new server. On the original box it is 16.04.

Thanks!
Chess

**Comment by chessw** [comment]
I gather from the crickets here that not many people here have tried to restore their boxes. 

Ran through this process again this weekend and ended up getting the same error using a fresh Ubuntu 16.04 VPS. 

Really looking for a nudge in the right direction so that I can complete the restore process and then once the process has been tested a few times we can post this up on the official documentation for all to use. I still think it is a database issue, but really don't know what to try next. 

Going to try to create a DB backup and then restore just that to the non-working mailcow box, and update after I try that.

**Comment by HesselTjeerdsma** [comment]
+1 for this topic, need to migrate to another server soon. Maybe try to setting the DB user and password manually? Are you migrating from the same versions?

**Comment by cklabautermann** [comment]
Hi @chessw, have a look [here](https://github.com/mailcow/mailcow-dockerized/issues/1798). I experienced the same issue and it finally worked ;-)

**Comment by chessw** [comment]
@cklabautermann 

Thank you for linking your thread. I'm not sure I found that one when I was going through the threads. 

I'm going to follow your experience and see if that works. I'll posts back here when I have gone through the process.

**Comment by chessw** [comment]
@HesselTjeerdsma I think this might be it. But I figured that would be ok, if you are using the mailcow.conf from the old server. Or does the SQL password get created when you create the new container? 

I'm pretty sure this is what is holding me up. Can I force a new SQL password and then update the conf with? I assume I'd have to rebuild mailcow after this.

**Comment by chessw** [comment]
So after following your thread @cklabautermann I'm getting the same error. Error: userdb lookup: connect(/usr/local/var/run/dovecot/auth-userdb) failed: No such file or directory

So it is something with a database around dovevot and dovecot is not running.

**Comment by chessw** [comment]
Wanted to give everyone an update, on a another fresh VPS with a new backup I am now getting something I never saw before, and was confusing me about your thread @cklabautermann. I now am getting the 5 different restore options that was hinted about in your thread. I will restore each one and report back on if this succeeds.

**Comment by chessw** [comment]
Got it to work! Finally! 

I will give an update tomorrow when I am not so tired :)

**Comment by chessw** [comment]
Edited this as one step is not correct!

So I got it to work. Steps are very close to what I started with a shade of difference. 

Thank you to @cklabautermann for the final push over the hump! Your thread got me where I needed to go, even if the issues were were having were not 100% the same. At least I don't think they are the same.

Here are the steps:

1 - Create backup on existing server -> ./helper-scripts/backup_and_restore.sh backup all
2 - Copy the back up off the server (using filezilla) as well as the mailcow.conf
3 - Run through the install steps up to generate config. Upload the old mailcow.conf into the new install.
4 - Complete the last two setups (pull and up) and try to connect to the new mailcow server. Using the default admin account and password to log in.
5 - Insure that you have a functional mailcow setup on the new server. It will be a blank server, and you should be able to access it using the IP address of the server if you don't have DNS updated yet, like I don't.
6 - Copy the backup to the new server using filezilla.  I just created a backup folder under /opt for this. 
7 - Restore backup. You need to restore all 5 options one at a time. I left the mail restore to last as it took quite awhile. Get a beer or two. I had a run and coke to pass the time.
8 - I then did an update.sh on the server to get everything to restart. I did this as I noticed that 2 dockers were not running. A reboot might have fixed it, but I figure that would fix any errors caused by the restore.

This was just a test for me. Tonight I do the swap to the new server, and change the DNS entries for all of my domains. 

@andryyy Do you want to have this process added to the Mailcow documentation? I can clean this up and give it to you to have it posted, or if one of your team would like to edit this and posted it, feel free to change as you see fit!

**Comment by MoritzWeber0** [comment]
I tried the steps from @chessw 
At step 4 (when running docker-compose up -d) i get the error: 

ERROR: for mailcowdockerized_dovecot-mailcow_1_72e1b530744f  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mailcowdockerized_dockerapi-mailcow_1_8d6686b41c97  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mailcowdockerized_sogo-mailcow_1_5c6e7c6a78f3  UnixHTTPConnectionPoolCreating mailcowdockerized_php-fpm-mailcow_1_49e4a9dc35f3   ... done

ERROR: for dovecot-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for dockerapi-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for sogo-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

How can i fix that?

**Comment by hachre** [comment]
@TechMoritz: Is your server really slow? Does it have super slow IO? These timeouts usually happen when Docker takes way too long for certain things. You can try rebooting and see if it fixes it, otherwise you may have to increase the timeouts. If you search for their names together with "docker", you should find info on how to do that. Alternatively it could have super slow or faulty (high packet loss) network connectivity or a firewall in the way.
