### ISSUE TITLE
Sieve port is not limited to local docker network

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#1948]
**Describe the bug**
The sieve port 4190 is open. Shouldn't this port only be exposed to the local mailco network?

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Run a portscan
2. See that port 4190 is open

**Expected behavior**
Sieve port should only be accessible from within the docker network

**Comment by mkuron** [comment]
No, that is intentional. Clients, e.g. Thunderbird with a [plugin](
https://addons.thunderbird.net/de/thunderbird/addon/sieve/), can manage filters remotely. Also Sieve uses the same kind of encryption and authentication as IMAP and thus poses no additional security concerns.
