### ISSUE TITLE
SOGo vacation mail by date behaves strange

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#195]
When setting up a vacation mail by date in SOGo the first time everything seems correct and the `sogo.sieve` is created with the correct dates.

However on the next day the dates in the SOGo interface just "move" forward. So when I created a vacation mail yesterday with 2017-04-14 to 2017-04-18 the interface today shows me that it goes from 2017-04-15 to 2017-04-19 while however `sogo.sieve` still has the initial correct dates. But when I now update/change my vacation mail settings and save them the `sogo.sieve` will always have a offset of one day. No matter what I tried so far I cannot eliminate this offset and I'm guessing (due to problem reports of some users) that this offset gets bigger from day to day making it impossible to set correct vacation dates.

So far I don't know what causes this and if more than the vacation mail is effected.

**Comment by andryyy** [comment]
Weird. Can you report this to SOGo, too? I will try my best to find the bug.

**Comment by tehXor** [comment]
I now also submitted this on the SOGo bug tracker: https://sogo.nu/bugs/view.php?id=4161

In general I have a hard time telling what is SOGo functionality and what comes from mailcow. Are the user settings which are stored in the DB in some SOGo default formatting or is this a mailcow specific one? I'm just asking as I could imagine that there might be a problem related to this issue...

**Comment by mkuron** [comment]
Fixed upstream a few months ago.
