### ISSUE TITLE
clamd errors. Watchdog restarts it

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#1951]
Hi,

Sorry I'm on my mobile so can't provide a full report. 
I'm getting error mails from watchdog regarding clamd.
That's the log from clamd

![screenshot_20181026-094707__01](https://user-images.githubusercontent.com/3374563/47552472-17abd080-d905-11e8-88d8-5e79dea6f57d.jpg)

Updated yesterday

Thanks!

**Comment by andryyy** [comment]
Did you check line 21 of clamd.conf?

**Comment by develth** [comment]
```ExcludePua Packed```

changed to 

```ExcludePUA Packed```

Now working

**Comment by andryyy** [comment]
Oh, I was expecting a file format error. Didn't catch the Pua.

**Comment by develth** [comment]
Has to reopen. The can't move errors crashed it again

**Comment by develth** [comment]
![screenshot_20181026-100819__01](https://user-images.githubusercontent.com/3374563/47553340-24c9bf00-d907-11e8-81c4-e7acdfe43cba.jpg)

**Comment by andryyy** [comment]
Just restart watchdog-mailcow. It kept the kill in the queue. It checks the thresholds at the beginning of a loop, then sleeps and THEN kills. That's something I need to change, you will not really notice it for other checks, but clamd-mailcow has a high-sleep check, so the kill is delayed a lot.

I already fixed the "busy" errors, but not pushed into master. It is nothing that prevents ClamAV from starting, don't worry.
