### ISSUE TITLE
Can't Share to Any authenticated User in Sogo

### ISSUE THREAD

**Issue by isclever** [mailcow/mailcow-dockerized#1954]
**Describe the bug**
When trying to share an imap folder or Calendar to "Any authenticated User" in Sogo the option does not appear.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Attempt to share the calendar
2. No "Any authenticated User" is available for selection.

**Expected behavior**
Authenticated User should be avaiable given this documentation: https://www.svenskadomaner.se/en/support/1920

**Screenshots**
![screenshot from 2018-10-26 13-54-41](https://user-images.githubusercontent.com/16140846/47584370-31aada80-d928-11e8-9004-9c18ebedaa68.png)

**System**
 - OS: CentOS 
 - Browser: Firefox

**Additional context**
This is likely a configuration option that I can't find to enable.

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-any_acl/

**Comment by isclever** [comment]
Thank you.
