### ISSUE TITLE
How to properly disable SOGo

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1955]
I have read #64 - It results in lots of dependency errors. I don't have much RAM and SOGo appears to use about half of it:
![image](https://user-images.githubusercontent.com/42045366/47586335-d0026480-d957-11e8-8522-91ac241d0d6f.png)
I don't need it as I use rainloop. How do I disable it?

BTW: I have almost no experience with Docker.

**Comment by andryyy** [comment]
Guys, read the issue template, please.

It is not possible at the moment to disable SOGo completly. You can reduce its workers (WOWorkersCount) to something like 1, it will eat much less RAM then.

**Comment by ghost** [comment]
How?

EDIT: Found it - #415

**Comment by ghost** [comment]
@andryyy Also, where does it say that in the issue template?

**Comment by Braintelligence** [comment]
@archiebaer He's meaning that your issue is neither a bug report nor a feature request and thus not expected here.

**Comment by ghost** [comment]
Okay

**Comment by discofris** [comment]
FYI, I'm doing `docker-compose stop sogo-mailcow` after each update/restart to save some pricy :moneybag: RAM. 
Never had any issues :ok_hand:, been doing it since 05/2017.

**Comment by andryyy** [comment]
Yes, you can do that, as long as you let it start once. :) Stopping it is fine, just dont remove it from the compose file. :)
