### ISSUE TITLE
why are you switch all DB connections to mysql.sock?

### ISSUE THREAD

**Issue by zkryakgul** [mailcow/mailcow-dockerized#1956]
Hello everyone.
I been using mailcow for a few months. I been try configure mailcow for running on multihost system with docker swarm. But swarm doesnt have any distrubuted file system for volumes so i checked last commits and i been realize you are switch all DB connections to direct linux socket. What is reason for it? I trying hard a few days to change them to connect via "--host mysql". At last i figured out with this problem, i been change all conf files etc. But then wierd problem occured. When i create a new user one after another for 10-15 times then some user's mailbox folders not been created( like inbox, trash etc.). They can send mail but mails does not go to any folder because there is no folder. I so confused because some users have this folders but some others didnt. What is reason can be?

**Comment by andryyy** [comment]
Hi Zekeriya ,

SOGo is very strange in keeping SQL connections alive, it may end up using too many connections. We also get rid of the TCP overhead this way.

You can setup a local Galera Cluster on your nodes and mount the SQL's /var/run directory in a docker-compose.override.yml like this. Don't forget to make the redis-mailcow container a slave of whichever master:

```
version: '2.1'
services:

    php-fpm-mailcow:
      volumes:
        - /var/run/mysqld:/var/run/mysqld/

# all other mysql-enabled services here

    redis-mailcow:
      command: --slaveof 10.123.123.123 6379

```

The file `data/conf/rspamd/local.d/redis.conf` needs to be changed to include a set of master and slave Redis servers like (untested):
```
servers = "master:6379"; # better leave it here, don't know if all modules can read read_servers and write_servers = "master:6379"; # master again
read_servers = "redis:6379"; # mailcows Redis
```

You could use HAProxy or whatever in front of mailcow (and enable the proxy protocol!) or just keep the other mailcow as stand-by.

Dovecots replication needs to be enabled, when you don't share a single storage pool for the cows. 

I do not want to write a full how-to here about clustering mailcow. I may some day add it though.
