### ISSUE TITLE
rspamd not scanning some mails

### ISSUE THREAD

**Issue by stuzfuz** [mailcow/mailcow-dockerized#1957]
Hi,

Most of the incoming mails are scanned and rspamd is detecting spam very good.
But some are not scanned by Mailcow/Rsampd.
Attached is the screenshot where some mails are scanned and marked as spam.
But there are also two mails which are spam, but not scanned.
![mailcow](https://user-images.githubusercontent.com/5834441/47601595-7770ad00-d9d3-11e8-8d1d-576829619cb4.jpg)

Mailcow is running on Ubuntu 16.04 and Docker 18.06.1-ce.
Mailcow is running on the latest release version.

Thanks

**Comment by mkuron** [comment]
Please run `docker-compose logs rspamd-mailcow` and paste those lines that correspond to the time of when these two messages where received.

**Comment by stuzfuz** [comment]
I'm unable to provide the logs as they are too old (to many other log messages provided).
But will provide new data after it happens again.

**Comment by JanHuisink** [comment]
I got the same problem today, attached is the information from 

`docker-compose logs rspamd-mailcow`

[2018-10-28_mailcow-rspamd.txt](https://github.com/mailcow/mailcow-dockerized/files/2522269/2018-10-28_mailcow-rspamd.txt)

**Comment by andryyy** [comment]
rspamd_task_timeout: processing of task timed out, forced processing

I wonder why it timed out.

Please post the full logs around that time or at least grep by "3dfa24". 👍 

PS: Running low on resources?

**Comment by stuzfuz** [comment]
I'm monitoring my vserver with nodequery.com and there is plenty of resources for mailcow.

**Comment by JanHuisink** [comment]
It is already a grep by "3dfa24". Some minutes before and after there were mails being processed normally. The server has 8 GB RAM of which less than 3 GB are in use, over 100 GB free disk space and 6 CPU cores which should be enough.

**Comment by stuzfuz** [comment]
> Please run `docker-compose logs rspamd-mailcow` and paste those lines that correspond to the time of when these two messages where received.

@mkuron had again the same issue three times.
One of the three messages:
rspamd-mailcow_1     | 2018-10-29 15:17:13 #11(normal) <5d1dbe>; task; accept_socket: accepted connection from XXXXXXX port 38924, task ptr: 00007F3268170300
rspamd-mailcow_1     | 2018-10-29 15:17:13 #11(normal) <5d1dbe>; task; rspamd_message_parse: loaded message; id: <SCnlQiJMjdwJJvAX7m32.2P4NNHO@dfqz.lumeninterius.info>; queue-id: <4359C802CB>; size: 3357; checksum: <e659ead56febf487f15959b0b3cf07b3>
rspamd-mailcow_1     | 2018-10-29 15:17:13 #11(normal) <5d1dbe>; lua; settings.lua:358: check for settings
rspamd-mailcow_1     | 2018-10-29 15:17:13 #11(normal) <5d1dbe>; lua; settings.lua:385: <SCnlQiJMjdwJJvAX7m32.2P4NNHO@dfqz.lumeninterius.info> apply settings according to rule score_XXXXXXXXXXXXXX
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; task; rspamd_task_timeout: processing of task timed out, forced processing
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; lua; asn.lua:69: error querying dns (XXXXXX.asn.rspamd.com): query timed out
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; bayes; bayes_classify: ignore bayes probability 0.50 since we have too few text tokens: 0, at least 1 is required
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; lua; greylist.lua:258: Score too low - skip greylisting
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; task; rspamd_task_write_log: id: <SCnlQiJMjdwJJvAX7m32.2P4NNHO@dfqz.lumeninterius.info>, qid: <4359C802CB>, ip: XXXXXXXX, from: <sabineyxwqfmanussbaum@lumeninterius.info>, (default: F (no action): [0.00/15.00] []), len: 3357, time: 12004.000ms real, 9.786ms virtual, dns req: 0, digest: <e659ead56febf487f15959b0b3cf07b3>, rcpts: <XXXXXXXXXX>, mime_rcpts: <XXXXXXXXXXXXXX>
rspamd-mailcow_1     | 2018-10-29 15:17:25 #11(normal) <5d1dbe>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 177 regexps total, 0 regexps cached, 0B bytes scanned using pcre, 0B bytes scanned total

Spam score is 0.00 for the wrong scanned mails.

**Comment by andryyy** [comment]
Please activate log level debug and wait for it to happen again. 

Is IPv6 communication between the containers working? Can you ping6 rspamd from postfix-mailcow? 

Edit: Oops, written from mobile, didn't see the response above. Thanks for posting.

**Comment by mkuron** [comment]
Confirmed. I am also seeing occasional timeouts due to asn.lua. If we can't configure rspamd with a timeout on DNS resolution, we need to disable the ASN check until rspamd's servers are reliable again.

In https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/options.inc, we currently have a 15-second timeout. That is definitely too long as the per-email timeout is also 15 seconds. Maybe decrease that to five seconds and restart rspamd.

**Comment by andryyy** [comment]
Vsevolod run some tests on his nameservers, it should be stable now.

The DNS timeout is indeed too large, that should be changed.

**Comment by stuzfuz** [comment]
It is much stabler now, but it is not solved completely.
Still some mails are not scanned.

**Comment by andryyy** [comment]
You might be rate-limited on a heavy loaded setup.

**Comment by stuzfuz** [comment]
I don't think so as I just receive about 30-40 mails per Day (included Spam).Am 04.12.2018 09:49 schrieb André Peters <notifications@github.com>:You might be rate-limited on a heavy loaded setup.

**Comment by andryyy** [comment]
And what's in your logs?

**Comment by stuzfuz** [comment]
here are the corresponding logs:

^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #9(rspamd_proxy) <cb049c>; proxy; proxy_accept_socket: accepted milter connection from XXXXXX port XXXXX
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #9(rspamd_proxy) <cb049c>; milter; rspamd_milter_process_command: got connection from XXXXXXXXXXX
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <c82966>; task; accept_socket: accepted connection from XXXXXXXXX, task ptr: 00007F3268173780
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <c82966>; task; rspamd_message_parse: loaded message; id: <XXXXXXXXXXXX@qq.shibuichic.com>; queue-id: <861B0804D6>; size: 2805; c
hecksum: <4d4a5aea9dc45d98344a909ca67823ec>
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <ifjkpi>; lua; lua_redis.lua:224: use default Redis settings for dyn_rl
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <ifjkpi>; lua; lua_redis.lua:224: use default Redis settings for keep_spam
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <c82966>; lua; settings.lua:358: check for settings
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:28:57 #11(normal) <c82966>; lua; settings.lua:385: <XXXXXXXXXXXXX@qq.shibuichic.com> apply settings according to rule score_XXXXXXXXXXXXXXXX
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:29:02 #10(controller) <rznbhc>; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 72401 != 72402) for http://nginx:8081/forwardinghosts.php
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:29:09 #10(controller) <533dwi>; map; http_map_finish: data is not modified for server updates.rspamd.com, next check at Tue, 04 Dec 2018 02:29:39 GMT
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:29:09 #11(normal) <c82966>; task; rspamd_task_timeout: processing of task timed out, forced processing
^[[36mrspamd-mailcow_1     |^[[0m 2018-12-04 03:29:09 #11(normal) <c82966>; lua; asn.lua:69: error querying dns (129.145.227.165.asn.rspamd.com): query timed out

**Comment by andryyy** [comment]
When such errors occur, you are probably much better off askin in Rspamds repo. :)
