### ISSUE TITLE
Create rancher-catalog template

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#196]
Hi there!
It would be awesome if mailcow-dockerized provided a rancher-catalog template for easy setup within rancher. This way, people would have an easy upgrade path, as long as they don't stray from the standard configuration. The mailcow.conf could be created from the rancher template when installing.
If successful, you could pitch mailcow to the official Rancher catalog as well.
Best of it all would be guaranteed compatibility with Rancher 😸.

An example on how this looks like can be found in this repo: https://github.com/adi90x/rancher-active-proxy

You create a folder "templates" and a folder with your project name and define the docker-compose.yml and rancher-compose.yml there. I don't know if and how to include "local" files, like you do with `./data/...` in the docker-compose.yml for the rancher catalog, though.
Afterwards, anyone can add the git repo as additional rancher catalog in the rancher web ui.

**Comment by andryyy** [comment]
Thanks, I will tag this issue. :-)

**Comment by Braintelligence** [comment]
Very glad to hear 😸

**Comment by emcniece** [comment]
I have started writing a catalog item: https://github.com/emcniece/rancher-catalog/tree/feat/mailcow/templates/mailcow

Currently I'm fighting with opening some ports on my hosts. Next steps are making the networking more Rancher-friendly, and testing all the container communication.

**Comment by develth** [comment]
Are there any news?

**Comment by emcniece** [comment]
@develth not much progress since last post. I think the stack works though, if you have time to verify I'd appreciate it!

**Comment by pedropereirahg** [comment]
Thanks a lot to @emcniece and @mailcow team. 

I think the @emcniece catalog inspired me to create this fork: [mailcow-rancherized](https://github.com/pedrogoncalvesk/mailcow-rancherized), and that catalog [rancher-catalog](https://github.com/pedrogoncalvesk/rancher-catalog) for rancher. 

If that helps you, I'll be happy! :heart_eyes:

**Comment by kolaente** [comment]
What about just adding mailcow to the official rancher-community catalog?

**Comment by MichelDiz** [comment]
I agree with @kolaente , using the Rancher catalog is a good option to generate more stream of users for this project. Several projects I've only just met were testing things from the catalog.

**Comment by etique57** [comment]
Hello,

Trying to install mailcow-rancherized on my rancher instance but there's a problem with the dovecot image (no healthy host...).

Tried both on Debian and rancheros.

**Comment by pedropereirahg** [comment]
Hey @etique57!
I think that issue will be helpful https://github.com/pedrogoncalvesk/rancher-catalog/issues/1
