### ISSUE TITLE
Sieve Filter

### ISSUE THREAD

**Issue by PaoloVi** [mailcow/mailcow-dockerized#1960]
Unable to add any filter. Validation ok.
The "add" button seems to be in disable state.
mailcow-dockerized update at current day.

![sieve](https://user-images.githubusercontent.com/6122740/47615203-5af47380-daac-11e8-89ab-9b4d93d61c3f.png)

**Comment by andryyy** [comment]
Indeed. Thanks! :-)

PS: Clean your browser cache after updating mailcow, please.
