### ISSUE TITLE
Migrating to docker based mailcow

### ISSUE THREAD

**Issue by YannKr** [mailcow/mailcow-dockerized#1963]
Hi there, 

similar to #1904 I'm looking to migrate from directly-on-host installed mailcow to the dockerized version.
I understand the migration guide can't be maintained forever due to the database structure changes and so on - however I was wondering if there was still a way, even if it's going to an older version of mailcow dockerized and upgrade afterwards.
I'm currently running **Mailcow 0.14** with about ~50 aliases and ~20 mailboxes. When using the old guide, I fail at the SQL level. Reading through issues, vmail folder transfer sounds less like a problem. Hoping that manual migration (recreating all aliases, accounts, domains...) is not the only option here.

Thanks for the great work!

**Comment by xifi-kif** [comment]
Same here, I finally decided to migrate to dockerized version (I still prefer the non-docker one in production, but since it's not maintained anymore.........)
Would be nice to have an updated how-to.
Thanks

**Comment by deanroker123** [comment]
I have the same problem. I am trying to upgrade from 0.14.
`Can't create table ``mailcow``.``mailbox`` (errno: 150 "Foreign key constraint is incorrectly formed")`

**Comment by wualex** [comment]
Anyone managed to do this migration from on-host to docker?
