### ISSUE TITLE
Option to Enable SCAYT by default for SOGo Users.

### ISSUE THREAD

**Issue by BlamKiwi** [mailcow/mailcow-dockerized#1968]
We have a couple of users in our test lab that prefer to use the SOGo web client. A request that has popped up a couple of times is to permanently enable SCAYT in the SOGo UI for composing email. 

The current SCAYT behaviour is a user has to manually enable and configure it each time they compose email. It's quite frustrating for them to just have it disappear each time. 

**Describe the solution you'd like**
As far as I'm aware, I have to dig through config files for the CKEdit module to do this. It would be nice if in the SOGo or MailCow UI if there was a checkbox to enable for a per-user or global basis.

**Comment by andryyy** [comment]
Hi,
I will add an easy way to modify the ckeditor settings via mounted config file.
You'll just need to edit `./data/conf/sogo/custom-sogo.js` and uncomment `CKEDITOR.config.scayt_autoStartup = true;` then.
Per-user will not be possible, though.

**Comment by extremeshok** [comment]
> I will add an easy way to modify the ckeditor settings via mounted config file.
Great news
