### ISSUE TITLE
can not setup my mail account at Devices - invalid certificate

### ISSUE THREAD

**Issue by onefckcps** [mailcow/mailcow-dockerized#1969]
Hello there,
i have some Problems with setting up the mailaccount at my Pc/Android Phone.
I did everything like it is described for this devices.
Error : "invalid certificate".
But i have a valid one, which works nicely!
help pls...

**Comment by andryyy** [comment]
Hi, we need more information. It probably is autodiscover.domain.tld that has no valid cert.
How did you config your PC/phone?
What's in `docker-compose logs --tail=200 acme-mailcow`?

**Comment by onefckcps** [comment]
log : 

> WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
> Attaching to mailcowdockerized_acme-mailcow_1
> acme-mailcow_1       | Tue Oct 30 20:01:06 CET 2018 - Waiting for Docker API...OK
> acme-mailcow_1       | Tue Oct 30 20:01:06 CET 2018 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: mail.xslx.de
> acme-mailcow_1       | Tue Oct 30 20:01:06 CET 2018 - Waiting for database...
> acme-mailcow_1       | Uptime: 5  Threads: 8  Questions: 61  Slow queries: 0  Opens: 27  Flush tables: 1  Open tables: 19  Queries per second avg: 12.200
> acme-mailcow_1       | Tue Oct 30 20:01:07 CET 2018 - Initializing, please wait...
> acme-mailcow_1       | Tue Oct 30 20:01:07 CET 2018 - Detecting IP addresses... OK
> acme-mailcow_1       | Tue Oct 30 20:01:40 CET 2018 - Waiting for domain table... OK
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - No A or AAAA record found for hostname autodiscover.xslx.de
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - Found A record for mail.xslx.de: X.X.X.X
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - Confirmed A record X.X.X.X
> acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
> acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
> acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - Verified hashes.
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - Certificate was not changed
> acme-mailcow_1       | Tue Oct 30 20:01:41 CET 2018 - ACME certificate validation done. Sleeping for another day.

theres a reverse proxy - ssl activ for sub and main domain (sub.domain.tld and domain.tld but different certificates) the mail server runns at sub.domain.tld
sry for this bad english

**Comment by andryyy** [comment]
How did you config your PC/phone? What's the exact certificate error you see? Which name is invalid?

**Comment by onefckcps** [comment]
PC : [https://mailcow.github.io/mailcow-dockerized-docs/client/client-windows/](url)
Android : [https://mailcow.github.io/mailcow-dockerized-docs/client/client-android/](url)

**Comment by onefckcps** [comment]
andorid said "the certificate is invalid" and windows : "we couldnt find your settings"

but SOGo works nicely! i can send messages too...

**Comment by andryyy** [comment]
You are missing the autodiscover DNS record. I still don't know which certificate/name your Android device is referring to, when it says "invalid".

Anyway, you should run the DNS check for your domain and add the missing autodiscover CAME/A/AAAA and SRV _autodiscover._tcp record.
