### ISSUE TITLE
Sending via an alias leaks mailbox address

### ISSUE THREAD

**Issue by pjv** [mailcow/mailcow-dockerized#1971]
First, mailcow-dockerized is **great** - thank you for making this project. 

When I am sending an email from an alias (e.g. `alias@example.com`) of my mailbox (`mailbox@example.com`), if I look at the raw headers of the sent email, the mailbox address is leaked in two places:

```
Received: from localhost (localhost [127.0.0.1])
  (Authenticated sender: mailbox@example.com) by my.server.com (Postcow)
```

```
ARC-Authentication-Results: i=1;	my.server.com;	auth=pass
 smtp.auth=mailbox@example.com smtp.mailfrom=alias@example.com
```

I'd prefer when sending from an alias of my mailbox not to reveal the mailbox address to the recipient of my messages. Before I start hacking away on the `anonymize_headers.pcre` file and sending you a pull request, I wanted to first ask if anyone knows a reason that the mailbox address *should* be leaked like this.

**Comment by mkuron** [comment]
You can remove that header completely by removing ` (Authenticated sender:$1` in that file. There is no way to replace the user with the alias there because the alias isn't contained in the header. We don't want to remove the authentication information entirely, so no need for a pull request. Sorry I can't offer a better solution.

**Comment by pjv** [comment]
Thanks @mkuron I did what you suggested with the first one.

In case anyone else is looking for the same functionality, here's my working regex for the second header that leaks the mailbox address:

```
/^\s*ARC-Authentication-Results:(.*)smtp\.auth=(.+)\ssmtp.mailfrom=(.+)/
  REPLACE ARC-Authentication-Results:$1 smtp.auth=$3 smtp.mailfrom=$3
```

my regex fu is sub-par, so any improvements welcome.

**Comment by niklasfyi** [comment]
@pjv This is not working on my side. Can you show me where in ```anonymize_headers.pcre``` you did the change? And do I need to only restart postfix after this?

Thanks

**Comment by pjv** [comment]
@clue404 here is my `anonymize_headers.pcre` file (with the server name redacted).

    if /^\s*Received:.*Authenticated sender.*\(Postcow\)/
    /^\s*Received:.*Authenticated sender:(.+)/
        REPLACE Received: from localhost (localhost [127.0.0.1]) by MY.SERVER.NAME (Postcow)
    endif
    /^\s*X-Enigmail/        IGNORE
    /^\s*X-Mailer/          IGNORE
    /^\s*X-Originating-IP/  IGNORE
    /^\s*X-Forward/         IGNORE
    /^\s*ARC-Authentication-Results:(.*)smtp\.auth=(.+)\ssmtp.mailfrom=(.+)/
      REPLACE ARC-Authentication-Results:$1 smtp.auth=$3 smtp.mailfrom=$3

it's been a while since I did this, but I'm pretty sure that after that edit i just did:

`docker exec -it $(docker ps -qf name=postfix-mailcow) postfix reload`

**Comment by niklasfyi** [comment]
alright thanks 👍

**Comment by maxmeyer** [comment]
@mkuron @andryyy  Is this still valid today? I would like to ask for an option to remove the authenticated sender? My use case is an "internal mailserver". I've no interest to leak internal information like the "authenticated sender" to the outside world.

Or at least I would expect some kind of documentation about that kind of behavior.

**Comment by mkuron** [comment]
Since it‘s part of the ARC authentication, I wouldn‘t recommend the code above. Sorry, there is no good solution to this. Is there a specific reason why you are worried about "leaking" the user name in the headers? Almost all mail servers do that.

**Comment by andryyy** [comment]
Create multiple mailboxes then. Don't use sensitive information in your mailbox name (?).
You can remove or replace all authed headers with some hacks (header checks are the most dangerous) and config adjustments. 
I can guarantee you will run into trouble with such a setup.

**Comment by maxmeyer** [comment]
@mkuron I use different mail addresses depending on the context: One address which is public on GitHub, e.g. development@example.com and one address just for private use, e.g. private@example.com. Currently those addresses are just aliases for a single mailbox I choose depending on context.

@andryyy Sorry, I think, I missed the `ARC-Authentication`-part. There's nothing about that in my `anonymize_headers.pcre`. 

What about that change below. Can I assume, that's nothing I need to worry about? That's what I wanted to asked for: Remove ` (Authenticated sender:$1` based on a config option.

~~~diff
if /^\s*Received:.*Authenticated sender.*\(Postcow\)/
 /^\s*Received:.*Authenticated sender:(.+)/
-  REPLACE Received: from localhost (localhost [127.0.0.1]) (Authenticated sender:$1
+  REPLACE Received: from localhost (localhost [127.0.0.1])
 endif
~~~

I checked some of my mails I sent via other mail providers (GMX, mailbox.org) before I replied in this thread for the first time. There was nothing recorded in the `Received:`-headers about the *mailbox* used. Only `Return-Path:` and `From:` are set to the "alias" I used for this mail.

What about "temporary aliases" for a short time communication. The mailbox name (private@example.com) is still recorded in the "Received:"-headers and sent to the other party if I don't remove `(Authenticated sender:$1` from `anonymize_headers.pcre`. Correct?

~~~mail
Received: from localhost (localhost [127.0.0.1]) (Authenticated sender: private@example.com)
# [...]
From: c0iov139ua24h5jzbmskqew6@example.com
~~~

**Comment by andryyy** [comment]
Try it. It may or may not work.

You can also remove the authenticated user from the "Received" header with an Postfix option. I think this breaks some authentication check methods in Rspamd (there was one for sure, cannot remember which :/). The regular "user" check is not affected, but I am absolutely sure something broke, when I tried.

**Comment by FingerlessGlov3s** [comment]
https://tools.ietf.org/id/draft-ietf-dmarc-arc-usage-02.html

https://tools.ietf.org/html/draft-ietf-dmarc-arc-protocol-23

There's not mention in the ietf protocol documents that the "Authenticated Sender" is required in the Received header. 

Of course you wouldn't modify any ARC headers, but removing the Authenticated email address from the Received header, ARC should still work.

If I'm wrong please do explain 🙂

**Comment by andryyy** [comment]
smtp.auth was removed a while ago, smtp.from **is** necessary. 

Edit: Ok, I just read the initial issue. You mean the auth-results header in rcvd. Perhaps we can remove it.

**Comment by FingerlessGlov3s** [comment]
Isn't SMTP.from apart of the "ARC Athentication Results" header

not Received header? 🤔

**Comment by FingerlessGlov3s** [comment]
Ah replied before you edited it.

Yes just auth results in the rcvd header, is the bit I'm talking about 😊.

I've not seen anyone else send me an email that's gone though arc thats had it in rcvd, so should be safe to remove.
