### ISSUE TITLE
Inconsistant options when creating vs editing an imap sync

### ISSUE THREAD

**Issue by isclever** [mailcow/mailcow-dockerized#1973]
**Describe the bug**
The options for imapsync are different from creating a new job vs editing a saved job.  

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Login as user
2. Create new sync get presented with these options:
![screenshot_2018-11-01 mailcow ui](https://user-images.githubusercontent.com/16140846/47859591-07906700-ddc5-11e8-8d40-56003b103aab.png)
3. Edit a saved sync and get presented with these options:
![screenshot_2018-11-01 mailcow ui 1](https://user-images.githubusercontent.com/16140846/47859734-4e7e5c80-ddc5-11e8-9494-92ee7ee8b156.png)
4. The descriptions are different as well as Subscribe all (--subscribeall) is missing from a new sync creation.

**Expected behavior**
Options should be the same if possible.  Better UX would be to present but grey out options that can't be used at creation time and create a note saying they can be edited after saving.

**System**
 - OS: CentOS - Latest.
 - Browser: Firefox

**Comment by andryyy** [comment]
Thanks, I fixed it and will close it with the next push cycle.
