### ISSUE TITLE
Outgoing Authenticated SMTP email fails with XLS attachment 

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#1974]
A user has reported to me that that they are unable to send two XLS spreadsheets using authenticated SMTP and Thunderbird, they get the following pop up when they try to send an email with these attachments:

![Mailcow-outgoing-smtp-error-with-xls-attachments.png](https://docs.webarch.net/w/images/3/34/Mailcow-outgoing-smtp-error-with-xls-attachments.png)

I don't yet have a XLS file that I can use to reproduce this error but I will try to get a copy of so I can link to it from here.

I have been unable to track down the corresponding entries in the `rspamd` log.

**Comment by mitchellurgero** [comment]
Does the XLS file have a macro?? rspamd / ClamAV wouldn't mark a user's email as spam unless it was infected (I am pretty sure anyway)

**Comment by chriscroome** [comment]
@mitchellurgero I don't know, I'm hoping to get a copy of the XLS files so I can check things like that.

**Comment by chriscroome** [comment]
The XLS files does have a macro, a minimal test example can be found here:

https://wiki.webarch.net/w/images/8/81/Test_macro_send.xls

**Comment by chriscroome** [comment]
I tried sending the same attachment via Mailcow and Mutt was unable to send it, this was the returned error:

```
SMTP session failed: 554 5.7.1 Spam message rejected
```

Testing this issue on a Debian Stretch machine:

```bash
apt install clamav clamav-daemon clamav-freshclam
mv /etc/clamav/clamd.conf /etc/clamav/clamd.conf.dist
vi /etc/clamav/clamd.conf # paste in data/conf/clamav/clamd.conf from 
                          # Mailcow server but comment LocalSocket path
mv /etc/clamav/freshclam.conf /clamav/freshclam.conf.dist
vi /etc/clamav/freshclam.conf  # paste in data/conf/clamav/freshclam.conf
                               # from Maicow server but commant PidFile path
service clamav-freshclam restart
service clamav-freshclam status | grep "up to date"
Jan 08 10:22:29 nuc freshclam[7240]: Tue Jan  8 10:22:29 2019 -> main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Jan 08 10:22:29 nuc freshclam[7240]: Tue Jan  8 10:22:29 2019 -> daily.cvd is up to date (version: 25279, sigs: 2201719, f-level: 63, builder: raynman)
Jan 08 10:22:29 nuc freshclam[7240]: Tue Jan  8 10:22:29 2019 -> bytecode.cvd is up to date (version: 328, sigs: 94, f-level: 63, builder: neo)
clamdscan --config-file=/etc/clamav/clamd.conf -i test\ macro\ send.xls 

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 0.000 sec (0 m 0 s)
```

Is is odd that I can't reproduce this issue? Am I missing something or could it be a SpamAssassin rather than a ClamAV issue?

**Comment by chriscroome** [comment]
I edited the following line in `data/conf/clamav/clamd.conf`:

```
OLE2BlockMacros no
```

And restarted the container:

```bash
docker-compose restart clamd-mailcow
```
And can now send the XLS file linked above, thanks for the help in IRC @andryyy

**Comment by chriscroome** [comment]
Just to note that the last Mailcow update appears to have removed the following line from `data/conf/clamav/clamd.conf`:

```
OLE2BlockMacros no
```

**Comment by andryyy** [comment]
Think it's a deprecated var. Check Clamd, they renamed it (so did we). :)

**Comment by chriscroome** [comment]
Thanks, [this blog post](https://blog.clamav.net/2018/12/clamav-01010-has-been-released.html) appears to cover it:

```
    | Old `clamd.conf` option          | *New* `clamd.conf` option    |
    | -------------------------------- | ---------------------------- |
    | `OLE2BlockMacros`                | `AlertOLE2Macros`            |
```
I have updated `clamd.conf` and restarted the container.

At some point in the future it might be nice to expose some of these options in the admin interface.
