### ISSUE TITLE
Mailcow Banning extremely fast

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#1975]
Hello. Since a bit I can't log in myself to my E-Mail accounts on some of my devices without getting banned. This means for example in Thunderbird, if the program tries to fetch the necessary data from the server, I'm banned. After changing my IP address and I can access the website again, it even says that the IP was just banned. Which value to I exactly need to change that IP's still get banned if there's an abuse of the website, but not if I'm doing something simple like this ?

**Comment by mitchellurgero** [comment]
Do you have an old tablet, computer, or phone that is still turned on with an old password?

**Comment by andryyy** [comment]
Please ask this in #mailcow on Freenode, we try to keep this a bug tracker.

These rules are matched:

```
RULES = {}
RULES[1] = 'warning: .*\[([0-9a-f\.:]+)\]: SASL .+ authentication failed'
RULES[2] = '-login: Disconnected \(auth failed, .+\): user=.*, method=.+, rip=([0-9a-f\.:]+),'
RULES[3] = '-login: Aborted login \(no auth .+\): user=.+, rip=([0-9a-f\.:]+), lip.+'
RULES[4] = '-login: Aborted login \(tried to use disallowed .+\): user=.+, rip=([0-9a-f\.:]+), lip.+'
RULES[5] = 'SOGo.+ Login from \'([0-9a-f\.:]+)\' for user .+ might not have worked'
RULES[6] = 'mailcow UI: Invalid password for .+ by ([0-9a-f\.:]+)'
```

Check your netfilter-mailcow logs for a rule id your login matched.

You probably just have an old account in Thunderbird that triggers a rule.

**Comment by xL0b0** [comment]
This is the netfilter logs:
![bildschirmfoto 2018-11-05 um 20 22 45](https://user-images.githubusercontent.com/38791556/48065626-8cb3bb80-e1cb-11e8-8532-d1779bc8ba1c.png)

**Comment by xL0b0** [comment]
This is a log example, when I try to log in:
![06 11 18 13 55 58](https://user-images.githubusercontent.com/38791556/48065751-d6040b00-e1cb-11e8-9b56-59856a3fa66b.png)
The thing is when Thunderbird tries finding settings it takes ages and then shows at the outgoing mailserver as authentification "no password", which is obviously wrong. After that I'm banned. 
If I change the authentification to password / SSL, I'm not getting banned (after I changed my IP address and kept the window open to put in my password etc. in Thunderbird.)
So I guess there's definitely a problem finding settings.

**Comment by andryyy** [comment]
Is autoconfig.domain.tld working?

**Comment by xL0b0** [comment]
Where can I check that ?

**Comment by andryyy** [comment]
Open it in a browser.

**Comment by xL0b0** [comment]
Sorry for asking like that, but is it a file or something else ? I can't follow quite well right now.

**Comment by andryyy** [comment]
The URL autoconfig.domain.tld. Run the DNS check for that domain. You will find where to point this record.

**Comment by xL0b0** [comment]
Only records missing are TSLA (you said once this wouldn't be a problem), PTR "in-addr.arpa", I still remember, when I checked the DNS tab twice, it showed me a check symbol, but the one that does not change is "_autodiscover._tcp" and stays at an error. Which doesn't make that much sense to me, as I have this record in my domain config, basically since the beginning and back then, or basically all the time until I did this post, everything worked properly.

**Comment by xL0b0** [comment]
?

**Comment by andryyy** [comment]
I don't know, it does not do that by default. My Thunderbird installation does not hammer my mailcow.

**Comment by gnadlma** [comment]
This seems to be an error I also encountered this week.
Still not quite sure where it came from.
But definitely from a user trying to set up his account in thunderbird.
The autoDISCOVER DNS was indeed wrong for that domain.
Did you mean discover or config @andryyy

**Comment by andryyy** [comment]
We can disable rule id 3, it is not really useful.

**Comment by markirb** [comment]
This seems to be an error I also encountered this week.
Still not quite sure where it came from.
But definitely from a user trying to set up his account in thunderbird.
The autoDISCOVER DNS was indeed wrong for that domain.
Did you mean discover or config @andryyy

**Comment by markirb** [comment]
If it’s not useful then it would be better,
It was definitely this rule.
And I don’t know either how to provoke thunderbird to do this, this has to be kind of magic by special users 🤣

**Comment by xL0b0** [comment]
Folks, if you mean my autodiscover DNS it would be kinda weird, cause I never changed anything about it since I set up mailcow. Back then it showed all DNS to be set as correctly.

**Comment by xL0b0** [comment]
Apparently I closed this issue on accident. Is this change in Mailcow still being considered ?
With the rule being removed ?

**Comment by andryyy** [comment]
I will disable it. Rules will be available via UI in the future.

**Comment by andryyy** [comment]
Fixed it.
