### ISSUE TITLE
Login TFA Bug only in Google Chrome

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#1976]
**Describe the bug**
In the latest Version of Google Chrome and versions beforde there is litte bug from the login ui. If you are using two factor authentication you get a litte box for your code. The coursor is inside the text area and if you type ur code, the coursor jumps out the textbox. Only if ur using chrome. In Firefox, IE and Edge it works fine.
**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Use ur Chrome Browser
2. Login to Mailcow UI (only if TFA is enabled)
3. Try to type ur code

**Comment by andryyy** [comment]
Thanks, I will check it. 

Can you please make sure your cache is clean in Firefox? Maybe it broke there too, but the cache files are still outdated.

**Comment by ClepToManix** [comment]
Forget about it. Cleared the cache and it works.. -.-
