### ISSUE TITLE
Disable jetty in mailcow

### ISSUE THREAD

**Issue by xifi-kif** [mailcow/mailcow-dockerized#1977]
Hello, still using mailcow non-docker (I know it's not supported, I will migrate to dockerized as soon as I learn everything I have to know). 
My server is running low on ram. Can I safely remove/uninstall jetty8 (eating around 20% of my total ram)? AFAIK it is only used by roundcube search feature. Is that true?

Can I safely uninstall it?
Will search function still work?
Other thing I should know?

Thankyou

**Comment by pyy** [comment]
The old non-docker repository has been archived, I also want to check the archived issues, maybe @andryyy can open it.

For stopping jetty8, you can stop it by modify these files below:
1.
```
sudo nano /etc/default/jetty8
# change to 0 to allow Jetty to start
NO_START=1
JAVA_OPTIONS="-Xmx128m -Djava.awt.headless=true"

```
2.
`sudo nano /etc/dovecot/dovecot.conf`
change from
```
mail_plugins = quota acl fts fts_solr
mail_plugins = quota imap_quota imap_acl acl fts fts_solr

```
to 
```
mail_plugins = quota acl fts_solr
mail_plugins = quota imap_quota imap_acl acl fts_solr
```
3.
`sudo nano /etc/cron.daily/dovemaint`
delete
`/bin/su vmail -c "/usr/bin/doveadm fts rescan -A"`


4. then 
```
sudo apt-get purge solr-jetty
sudo apt-get autoremove
```

**Comment by xifi-kif** [comment]
thanks

I agree! It would be very nice to have old non-docker archive to be readable (read-only maybe?) @andryyy
