### ISSUE TITLE
Docker Hub Repo Info is out of date and has broken link

### ISSUE THREAD

**Issue by gene1wood** [mailcow/mailcow-dockerized#1980]
The "Repo Info" for the mailcow postfix docker image on the [mailcow/postfix docker hub page](https://hub.docker.com/r/mailcow/postfix/) links to https://andryyy.github.io/mailcow-dockerized/ instead of https://mailcow.github.io/mailcow-dockerized-docs/

The andryyy.github.io link is broken. Please update the Docker Hub repo info with the fixed link.

**Comment by MAGICCC** [comment]
Seems so that only @andryyy can fix the README in the hub

**Comment by gene1wood** [comment]
@andryyy Can you fix the README?

**Comment by gene1wood** [comment]
stale bot, this issue isn't stale, just waiting on a response from @andryyy I've emailed him just now, maybe he'll see it.

**Comment by andryyy** [comment]
Should be fixed. :)

**Comment by gene1wood** [comment]
@andryyy Thanks for taking a look at this. It looks like the new link which points to

https://mailcow.email/dockerized

returns a 404.

The text currently reads

```
Postfix container for mailcow. See https://mailcow.email/dockerized 
```

Is https://mailcow.github.io/mailcow-dockerized-docs/ a good replacement URL? If so can you switch it to that? If not, is there a better URL that you can drop in there?

**Comment by gene1wood** [comment]
Thanks Andre

```
---------- Forwarded message ---------
From: André Peters
Date: Mon, Mar 4, 2019 at 2:25 PM
Subject: Re[2]: Docker Hub Repo Info is out of date and has broken link
To: Gene Wood

Oh. Thanks. :)

I changed them all to https://mailcow.email
```
