### ISSUE TITLE
Watchdog: clamd-mailcow hit the error rate limit

### ISSUE THREAD

**Issue by flaviomeyer** [mailcow/mailcow-dockerized#1981]
After latest upgrade i receive 4-6 times a day this error from Watchdog.

Watchdog: clamd-mailcow hit the error rate limit
![image](https://user-images.githubusercontent.com/28959963/47966134-37eb3600-e04f-11e8-8bc6-bed15be956a1.png)

How can i fix it?

**Comment by ticevi** [comment]
I recieve an similar error. Not this often but exactly every morning :/
I cant find the error message in the logs:
<details>
<summary>docker-compose logs mailcow-clamd</summary>
`clamd-mailcow_1      | Wed Nov 14 07:50:24 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed Nov 14 07:50:24 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed Nov 14 07:55:20 2018 -> ClamAV update process started at Wed Nov 14 07:55:20 2018
clamd-mailcow_1      | Wed Nov 14 07:55:21 2018 -> main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
clamd-mailcow_1      | Wed Nov 14 07:55:22 2018 -> daily.cld is up to date (version: 25118, sigs: 2150583, f-level: 63, builder: neo)
clamd-mailcow_1      | Wed Nov 14 07:55:23 2018 -> bytecode.cvd is up to date (version: 327, sigs: 91, f-level: 63, builder: neo)
clamd-mailcow_1      | Wed Nov 14 08:50:33 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed Nov 14 08:50:33 2018 -> SelfCheck: Database status OK.
clamd-mailcow_1      | Wed Nov 14 08:56:26 2018 -> ClamAV update process started at Wed Nov 14 08:56:26 2018
clamd-mailcow_1      | Wed Nov 14 08:56:28 2018 -> main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Wed Nov 14 08:57:48 2018 -> Downloading daily-25119.cdiff [100%]
clamd-mailcow_1      | Wed Nov 14 08:58:28 2018 -> daily.cld updated (version: 25119, sigs: 2150834, f-level: 63, builder: neo)
clamd-mailcow_1      | Wed Nov 14 08:58:29 2018 -> bytecode.cvd is up to date (version: 327, sigs: 91, f-level: 63, builder: neo)
clamd-mailcow_1      | Wed Nov 14 09:02:21 2018 -> Database updated (6717174 signatures) from database.clamav.net (IP: 104.16.187.138)
clamd-mailcow_1      | Wed Nov 14 09:02:21 2018 -> Clamd successfully notified about the update.
clamd-mailcow_1      | Wed Nov 14 09:03:40 2018 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | Wed Nov 14 09:03:40 2018 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> +++ Started at Wed Nov 14 09:07:26 2018
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> clamd daemon 0.100.2 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> Running as user clamav (UID 100, GID 101)
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | Wed Nov 14 09:07:26 2018 -> Reading databases from /var/lib/clamav
`
<details>

**Comment by flaviomeyer** [comment]
@ticevi
I solved the problem with an reboot.
