### ISSUE TITLE
Mails needs hours to arrive

### ISSUE THREAD

**Issue by IchUseKomplexe** [mailcow/mailcow-dockerized#1982]
So my hoster switched his Data Center and I got a new IP. Now the mails are arriving a long time later. I don't know why. I edited all my DNS records but It's taking so long.

**Comment by IchUseKomplexe** [comment]
It's resolved.

**Comment by mkuron** [comment]
It can easily take a day for the DNS records to propagate throughout the internet. Once the caches expire, you should be getting immediate delivery again.
