### ISSUE TITLE
not able to save syncjobs 

### ISSUE THREAD

**Issue by rapacides** [mailcow/mailcow-dockerized#1986]
Hi,

yesterday I've updated my mailcow to the actual version.

Now I'm facing the problem, that I'm not able to save/modify my syncjobs.

No error is shown, neither in docker logs nor in the GUI.

Kind Regards

Jan

**Comment by andryyy** [comment]
Hi,

I am closing this, because I am absolutly sure it is your browsers cache. :-) 👍 

This happens when we change the JS code. Make sure you clean it completely and restart it afterwards.

André

**Comment by rapacides** [comment]
Thank you, this helped. I didn't thought about that.

It will be nice if write a little hint in your documentation :)
