### ISSUE TITLE
Cannot change anything in Mailcow UI after Update

### ISSUE THREAD

**Issue by Linusten** [mailcow/mailcow-dockerized#1987]
**Describe the bug**
I Updated with the update.sh to the newest Version, after the Update i couldnt login with the admin user, so i resetted the password with mailcow-reset-admin.sh. 
I try to change the password of a mailbox via mailcow ui -> nothing happens after save
I try to change the name of a mailbox via mailcow ui -> nothing happens after save

**Screenshots**
![unbenannt](https://user-images.githubusercontent.com/9747039/48055224-5d8f5100-e1af-11e8-8d27-6ecf2caecb00.JPG)

**Logs**

warning | DC3F48 | admin | admin | 46.85.xxx | "session_token"
-- | -- | -- | -- | -- | --
Call null | null
null

Please help me...

**Comment by hachre** [comment]
I had the same problem. Erasing browser cache fixed it for me. (Didn't have the login issue, though)

**Comment by Linusten** [comment]
Damn it, thats it... i searched for hours... thanks :-)

**Comment by andryyy** [comment]
We reaaally need to add it to the docs. Or even to the update script.
