### ISSUE TITLE
Adding Release and Delete into Quarantine modal

### ISSUE THREAD

**Issue by Knight1** [mailcow/mailcow-dockerized#1991]
**Is your feature request related to a problem? Please describe.**
It is not very convenient to release or delete an email. 

To delete it you need to close the modal window and click on delete.
If you want to train the spam filter you need to close the window, mark the mal, click on action and then "Learn as spam and delete"
If you want to release the Mail you need the step above but click on release.

**Describe the solution you'd like**
I would like to add a btn-group into the modal with delete, learn as spam and delete and release.

**Additional context**
Just want to know if this is something we want or if there is something against it.

**Comment by andryyy** [comment]
I will try to add it soon. 👍
