### ISSUE TITLE
Take payment in GBP

### ISSUE THREAD

**Issue by jmthackett** [mailcow/mailcow-dockerized#1992]
Liberapay has the option to donate in GBP usually, but this isn't exposed on your payment page. Since my country is in the middle of a colossal act of self harm that might leave our currency more volatile than I'd like, it'd be great to be able to donate in GBP rather than eur/usd. Can you turn on the GBP option?

Thanks.

**Comment by andryyy** [comment]
I didn't know we can/have to enable it. :-O (Just did)

We will miss you guys. :-(

Thanks!
