### ISSUE TITLE
Cant set rspamd password

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#1994]
When i try to set a password over the mailcow ui for rspamd i get an error.
when i look in the log the massage is "unknown"
![bildschirmfoto von 2018-11-09 16-48-00](https://user-images.githubusercontent.com/16965460/48272680-79108b00-e43f-11e8-9934-4006649f407b.png)

**Comment by andryyy** [comment]
Please clean your browser cache, maybe that's all. I cannot reproduce it in a dev machine nor in the demo.

**Comment by Dunky13** [comment]
I get the same issue, cleared cache and all

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/49547780-f666d880-f8e3-11e8-97ac-204fd4e1ca8f.png)
Works even in the demo. :/ Would need more logs, infos etc.

**Comment by wuast94** [comment]
Updated Yesterday everything and tried again..same error and I don't have more logs. 
What can I do for you to have more information?

**Comment by andryyy** [comment]
I can have a look on your machine, if you want to. I'd send you a SSH key.

**Comment by wuast94** [comment]
I have sent you an email :)

**Comment by andryyy** [comment]
Will probably be this evening though. :( Ok? Can you mail me to info@servercow.de?

**Comment by andryyy** [comment]
You found a bug. :) Thanks!

**Comment by Braintelligence** [comment]
Guys, it would be awesome if you could always keep a documentation on what the cause for the issue was 🐱. I bet you also don't like posts on stackoverflow like `yeah, I found a solution, thanks.` 😹

**Comment by andryyy** [comment]
Sorry, was about to close the issue with a commit. :) It was not comparing the individual compose project name case-insensitive.

dockerapi-mailcow tries to find the container ID by the container name (ok) and project name (not ok). It compared "MyProject" to "myproject" and failed. We now compare strtolower("MyProject") to "myproject".
