### ISSUE TITLE
HUGE Redis memory bug

### ISSUE THREAD

**Issue by Knight1** [mailcow/mailcow-dockerized#1999]
Relates to https://github.com/mailcow/mailcow-dockerized/issues/366

I always monitor my server which caused some major problems here and there. Redis was always reporting out of memory while logging in after some time. Restart fixed it for some time.

My Redis was running with ```used_memory_human:1.23G``` now I drooped it to ```used_memory_human:26.08M```

The problem was found with redis-cli --bigkeys

```[88.72%] Biggest list   found so far 'DOVECOT_MAILLOG' with 1555499 items```
```Biggest   list found 'POSTFIX_MAILLOG' has 2283723 items```

I tracked it down to the roots.
This is the Dovecot container.
```
root@development:/etc/syslog-ng# su vmail
$ echo "test" > /dev/stdout
sh: 1: cannot create /dev/stdout: Permission denied
```

We execute the cronjob with logging to /dev/stdout but for 3 crons the user vmails does not have the permission to do so.
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/Dockerfile#L94

@ntimo has the same problem while executing 
```
docker exec -it mailcowdockerized_redis-mailcow_1_* redis-cli monitor | grep LTRIM
```
It should output 5 Lines every minute. 

Solution is to remove the lines after the .sh, to use root, or another solution.

BUT: There are lines in most containers so that the container is doing it themself but it isn't.

Cheers
Tobias

**Comment by andryyy** [comment]
I already fixed it in the current image for managed mailcows, but merged not yet to this repo. :-( Enotime.

There are 3 crons reporting to dev/stdout, but only 2 are run by vmail.

I added a tty to dovecot-mailcow and added vmail to tty.

Thanks for reporting it. :-) I will hurry.

**Comment by andryyy** [comment]
Pushed a slightly different script now. But I promised I tested it... :-P
