### ISSUE TITLE
No sogo login possible

### ISSUE THREAD

**Issue by Bitti09** [mailcow/mailcow-dockerized#2]
Logs:

`sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: |SOGo| starting method 'POST' on uri '/SOGo/connect'
sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: <0x0x56176e01bae0[SOGoCache]> Cache cleanup interval set every 300.000000 seconds
sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: <0x0x56176e01bae0[SOGoCache]> Using host(s) 'memcached' as server(s)

sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: [WARN] <0x0x7ff6533ed820[WOxElemBuilder]> could not locate builders: WOxExtElemBuilder,WOxExtElemBuilder

sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: [ERROR] <0x0x56176e334250[SOGoUserManager]> No authentication sources defined - nobody will be able to login. Check your defaults.

sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: SOGoRootPage Login from '37.201.192.192' for user 'admin' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0

sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: |SOGo| request took 0.027754 seconds to execute

sogo-mailcow_1       | Dec 26 12:42:45 sogod [30]: 37.201.192.192 "POST /SOGo/connect HTTP/1.0" 403 34/58 0.032 - - 8M
`

default config files for sogo used.

**Comment by andryyy** [comment]
Did you restart SOGo after adding a domain?

**Comment by Bitti09** [comment]
Multiple times via webui and docker cli

**Comment by andryyy** [comment]
What about the logs right after restarting the SOGo container? Something about reconf-domains.sh 

Will check this tomorrow when I announce it. Any changes you made to the composer file? Or non alphanumeric db name or password?

> Am 26.12.2016 um 13:45 schrieb Bitti <notifications@github.com>:
> 
> connect'

**Comment by Bitti09** [comment]
@andryyy : Log aftr cklicking on restart sogo button: https://hastebin.com/upudizejaj.sql
log after login try: https://hastebin.com/oxovutiyam.vbs
already changed passwords to  alphanumeric.

**Comment by Bitti09** [comment]
@andryyy 
Update: after converting the domain part from sogd.plist to sogo.conf format and adding it ot  sogo.conf  the login started to work.

**Comment by andryyy** [comment]
Yes but that's not the problem and not a valid solution. That does not help at all. The reconfigure script does not write the defaults for you.
I wrote it without further testing and need to check what fails tomorrow. Can you enter the container and run the script in / manually?

**Comment by andryyy** [comment]
Changing the passwords while you have data in the volumes breaks everything. You would need to clean the volumes first. :O

**Comment by Bitti09** [comment]
if "Changing the passwords while you have data in the volumes breaks everything."
then why it works when  i've added the domain part in sogo.conf ?

**Comment by andryyy** [comment]
You "hardcoded" the passwords into the sogo.conf file. So it does not care about values in mailcow.conf.
The SOGo reconf-domains.sh helper script reads the env vars and writes the defaults. It does not do that anymore. Or .. well .. it tries, fails and SOGo preferes the sogo.conf values.

I will try to fix special chars in passwords today, but it is kind of hard in Bash.

PS: Can you write me your previous password?

**Comment by andryyy** [comment]
I added an invalid label because it says "do not you complex passwords right now".

**Comment by Bitti09** [comment]
@andryyy  it was something like NaphaFR8?#eprEpR
and do i have any disadvantage of hardcoding the passwords into sogo.conf ?

**Comment by kevinbader** [comment]
@andryyy Hi, has this been fixed? After updating from f43e115b3af3dc39e5c689a7c558ac88e8842c25 to 17d3a24d8978230c393cbb339d8d1e5cfd564df4, I see this upon `docker-compose up -d`:

```
sogo-mailcow_1       | Jul  1 15:05:15 72e7c199d2fc sogod [73]: [ERROR] <0x0x559ee3b8c4c0[SOGoUserManager]> No authentication sources defined - nobody will be able to login. Check your defaults.
```

The message holds true - login fails for all users.

I've used `update.sh` and adapted `docker-compose.yml` to use my previous volumes (which are bound to host directories).

Please, let me know if you need further information. `sogo.conf`:

```
{
    SOGoCalendarDefaultRoles = (
        PublicViewer,
        ConfidentialDAndTViewer,
        PrivateDAndTViewer
    );

    WOWorkersCount = "20";
    SOGoACLsSendEMailNotifications = YES;
    SOGoAppointmentSendEMailNotifications = YES;
    SOGoDraftsFolderName = "Drafts";
    SOGoJunkFolderName= "Junk";
    SOGoMailDomain = "sogo.local";
    SOGoEnableEMailAlarms = NO;
    SOGoFoldersSendEMailNotifications = YES;
    SOGoForwardEnabled = YES;
    SOGoUIAdditionalJSFiles = (js/theme-blue.js);

    // Multi-domain setup
    // Domains are isolated, you can define visibility options here.
    // Example:

    // SOGoDomainsVisibility = (
    //  (domain1.tld, domain5.tld),
    //  (domain3.tld, domain2.tld)
    // );

    SOGoIMAPServer = "imap://dovecot:143/?tls=YES";
    SOGoSieveServer = "sieve://dovecot:4190/?tls=YES";
    SOGoSMTPServer = "postfix:588";
    WOPort = "0.0.0.0:20000";
    SOGoMemcachedHost = "memcached";

    SOGoLanguage = English;
    SOGoMailAuxiliaryUserAccountsEnabled = YES;
    SOGoMailCustomFromEnabled = YES;
    SOGoMailingMechanism = smtp;
    SOGoSMTPAuthenticationType = plain;

    SxVMemLimit = 384;

    SOGoMaximumPingInterval = 354;

    SOGoInternalSyncInterval = 30;
    SOGoMaximumSyncInterval = 354;

    // 100 seems to break some Android clients
    //SOGoMaximumSyncWindowSize = 100;
    // This should do the trick for Outlook 2016
    SOGoMaximumSyncResponseSize = 2048;

    WOWatchDogRequestTimeout = 10;
    WOListenQueueSize = 300;
    WONoDetach = YES;

    SOGoIMAPAclConformsToIMAPExt = Yes;
    SOGoPageTitle = "SOGo Groupware";
    SOGoFirstDayOfWeek = "1";

    SOGoSieveFolderEncoding = "UTF-8";
    SOGoPasswordChangeEnabled = NO;
    SOGoSentFolderName = "Sent";
    SOGoMailShowSubscribedFoldersOnly = NO;
    NGImap4ConnectionStringSeparator = "/";
    SOGoSieveScriptsEnabled = YES;
    SOGoTrashFolderName = "Trash";
    SOGoVacationEnabled = YES;

    SOGoCacheCleanupInterval = 900;
    SOGoMaximumFailedLoginCount = 10;
    SOGoMaximumFailedLoginInterval = 900;
    SOGoFailedLoginBlockInterval = 900;

    MySQL4Encoding = "utf8mb4";
  //SOGoDebugRequests = YES;
  //SoDebugBaseURL = YES;
  //ImapDebugEnabled = YES;
  //SOGoEASDebugEnabled = YES;
  //LDAPDebugEnabled = YES;
  //PGDebugEnabled = YES;
  //MySQL4DebugEnabled = YES;
  //SOGoUIxDebugEnabled = YES;
  //WODontZipResponse = YES;
    WOLogFile = "/dev/sogo_log";
}
```

**Comment by andryyy** [comment]
There is no login issue.

If there is no login source, your mailcow installation may be empty. Or you just need to open the web UI of mailcow to init the database.

**Comment by kevinbader** [comment]
Thanks for getting back to me. What do you mean when you say the installation could be "empty"? It worked previously with the same configuration. Also I've made sure to open the mailcow UI, even did a compose down and up after that, but that doesn't change anything. The login fails for the mailcow UI as well. Anything else I could try?

**Comment by andryyy** [comment]
Any domains or mailboxes when you login to mailcow?

**Comment by kevinbader** [comment]
well, I can't login..

**Comment by kevinbader** [comment]
oh my, I actually *can* login, but not with my account but with the default username/password! 😕 

Indeed, while the DKIM keys of my domains are still there, the domain list is empty. How can I fix this?

**Comment by andryyy** [comment]
You messed something up with the volumes. It is not using the correct volumes.

**Comment by andryyy** [comment]
We can check this together, if you want to. Just mail me to info@servercow.de

**Comment by ykayiwa** [comment]
Hello @andryyy , am facing the same issue, the domain list is empty, what is the workaround ?
