### ISSUE TITLE
mysql env variables get autogenerated?!?

### ISSUE THREAD

**Issue by ngarafol** [mailcow/mailcow-dockerized#2000]
Using latest mailcow source and following documentation, using reverse proxy I got infamous 502 bad gateway error. Reading few issues about it, disabling ipv6 inside dockerfile, didnt help. Couldnt even login to mysql container with passwords inside .env or mailcow.conf. 
Went with reseting passwords guide, and there was **mailcow445** database and **mailcow445** user. Where did it come from, I have no idea. But it obviously prevented everything from working out of the box.

Sorry for not following bug reporting rules, and please someone verify this. If my finding is right, we could help out few "502" related issues, at least I believe so. 

If it makes any sense, host is hetzner cloud, ubuntu 18.04.

**Comment by andryyy** [comment]
Probably a broken mailcow.conf, this does _not_ happen on a default installation via docs. I will mark it as question...
