### ISSUE TITLE
502 Bad Gateway -- Nginx Reverse Proxy

### ISSUE THREAD

**Issue by junelsolis** [mailcow/mailcow-dockerized#2001]
Hello,

I'm hoping somebody can help me as I've been at this for hours, read all the related issues I can find, and I still can't figure it out. I'm running an Nginx reverse proxy on the docker host, netstat shows that the mailcow containers are listening. Still, I'm getting the 502 Bad Gateway error when I try to open Mailcow in the browser. The firewall is disabled. I'm on a CentOS 7.5 machine.

Here's the latest netstat of my ports:

`127.0.0.1:13306      0.0.0.0:*       LISTEN      11474/docker-proxy`
`0.0.0.0:443             0.0.0.0:*          LISTEN      13901/nginx: master`
`127.0.0.1:8443        0.0.0.0:*        LISTEN      12553/docker-proxy`
`0.0.0.0:80               0.0.0.0:*           LISTEN      13901/nginx: master`
`127.0.0.1:8080        0.0.0.0:*        LISTEN      12567/docker-proxy`
`0.0.0.0:22               0.0.0.0:*           LISTEN      1241/sshd`
`127.0.0.1:19991       0.0.0.0:*       LISTEN      11791/docker-proxy`
`:::25                   :::*                    LISTEN      11758/docker-proxy`
`:::4190                 :::*                    LISTEN      11833/docker-proxy`
`:::993                  :::*                    LISTEN      11889/docker-proxy`
`:::995                  :::*                    LISTEN      11856/docker-proxy`
`:::587                  :::*                    LISTEN      11619/docker-proxy`
`:::110                  :::*                    LISTEN      12012/docker-proxy`
`:::143                  :::*                    LISTEN      11972/docker-proxy`
`:::80                   :::*                    LISTEN      13901/nginx: master`
`::465                  :::*                    LISTEN      11663/docker-proxy`
`:::22                   :::*                    LISTEN      1241/sshd`

Here is the reverse proxy configuration with the domain names changed:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name mxa.domain.com autodiscover.*;
  return 301 https://$host$request_uri;
}
server {
  listen 80;
  listen [::]:80;
  server_name autoconfig.*;
  rewrite ^/(.*)$ /autoconfig.php last;
  location / {
    proxy_pass http://127.0.0.1:8080/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 0;
  }
}
server {
  listen 443;
  server_name mxa.domain.com autodiscover.* autoconfig.*;

  ssl on;
  ssl_certificate /srv/mailcow-dockerized/data/assets/ssl/cert.pem;
  ssl_certificate_key /srv/mailcow-dockerized/data/assets/ssl/key.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location / {
      proxy_pass http://127.0.0.1:8080/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 100m;
  }

}
```

Maybe it's just a tiny configuration problem I'm missing. I would appreciate if someone could help me figure this out.

**Comment by ticevi** [comment]
I had the same problem a while ago. 
instead of the localhost IP, wich refers to the locahost of the container, you have to put your reverse proxy container on the same dockernetwork as your mailcow-nginx. 
Then you can reach the websites from your reverse-proxy by the container name.
