### ISSUE TITLE
*.domain.tld wildcard certificate 

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#2002]
**Is your feature request related to a problem? Please describe.**
*.domain.tld should create a wildcard cert for all subdomains of domain.tld

**Describe the solution you'd like**
It would be great to be able to create a cert for *.domain.tld this way you can have unlimited subdomains. This would be useful if you use Gitea or Portioner for example.

**Comment by andryyy** [comment]
Pretty sure that’s a duplicate. Also not possible without multiple DNS API. So not really something I plan in the near future. :/ I would probably add it for Servercow and try to keep it simple to add other providers.
