### ISSUE TITLE
Timezone [Etc/UTC]: UTC-8 tr: write error: Broken pipe tr: write error tr: write error: Broken pipe tr: write error

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2007]
I cant install, it always give me this error, no matter what timezone i try to use
```
root@mail:/opt/mailcow-dockerized# ./generate_config.sh 
A config file exists and will be overwritten, are you sure you want to contine? [y/N] y
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Hostname (FQDN): mail.merith.tk
Timezone [Etc/UTC]: UTC-8
tr: write error: Broken pipe
tr: write error
tr: write error: Broken pipe
tr: write error```

**Comment by andryyy** [comment]
Which zones do you actually try?

Edit: That's not a matter of the timezone, but:
DBPASS=$(LC_ALL=C </dev/urandom tr -dc A-Za-z0-9 | head -c 28)
DBROOT=$(LC_ALL=C </dev/urandom tr -dc A-Za-z0-9 | head -c 28)

Which OS do you use?

**Comment by ghost** [comment]
I dont even know what ones were available, so i have tried
+8
-8
UTC-8
UTC+8

*Duncan, 15803*

**Comment by mkuron** [comment]
A list of valid time zones can be found at 
https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones. You probably want Etc/GMT-8.

**Comment by ghost** [comment]
thanks, will look into it shortly

*Duncan, 15803*

**Comment by ghost** [comment]
And thanks, that worked
