### ISSUE TITLE
Not getting emails from the Internet, but are sent without problems.

### ISSUE THREAD

**Issue by vivernet** [mailcow/mailcow-dockerized#201]
Sending emails happens without problems, but on large problems. Moreover, rspamd no error is displayed.
But recently noticed that the letters reach in very rare cases, for example they go with gmail.com and yandex.ru and more is not from where you do not come.

**on the sender's mailbox after a while here comes this error:**

Delivery attempt history for your mail:

Wed, 05 Apr 2017 23:57:04 +0000 (GMT)
Temporary error from SMTP partner: smtp;421 4.4.2 mx.maxus.email Error: timeout exceeded

Wed, 05 Apr 2017 15:52:00 +0000 (GMT)
Temporary error from SMTP partner: smtp;421 4.4.2 mx.maxus.email Error: timeout exceeded

Wed, 05 Apr 2017 07:46:59 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Tue, 04 Apr 2017 23:46:59 +0000 (GMT)
admin@maxus.email: smtp;451 4.3.0 <alex.1501@icloud.com>: Temporary lookup failure

Tue, 04 Apr 2017 15:46:55 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Tue, 04 Apr 2017 07:46:55 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Mon, 03 Apr 2017 23:46:55 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Mon, 03 Apr 2017 15:46:55 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 113)

Mon, 03 Apr 2017 07:46:51 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 113)

Mon, 03 Apr 2017 03:46:48 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 113)

Sun, 02 Apr 2017 23:46:45 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Sun, 02 Apr 2017 19:46:45 +0000 (GMT)
TCP active open: Failed connect() to TCP port 25 of 109.195.87.80(No formatted text for errno = 111)

Sun, 02 Apr 2017 17:46:45 +0000 (GMT)
Temporary error from SMTP partner: smtp;421 4.4.2 mx.maxus.email Error: timeout exceeded

Sun, 02 Apr 2017 15:41:41 +0000 (GMT)
Error reading SMTP packet; response to dot-stuffed message expected; likely problem with network or remote SMTP server

**Comment by vivernet** [comment]
:-(

**Comment by chaosbunker** [comment]
I'm no expert, but if I compare your DNS Records with mine, it looks like your mx record is misconfigured. it is set to `maxus.email` instead of `mx.maxus.email`

**Comment by vivernet** [comment]
The DNS I have configured all right. Especially because of the letters I wrote about is.

**Comment by broedli** [comment]
first, your ptr should be a FQDN -> host.domain.tld
second, your mx record should be a FQDN -> host.domain.tld
third, your server is not reachable via port(s) 25, 587, 465, ... Is mailcow actually running? -> check output of `docker ps`, `netstat -tulpn`, `openssl s_client -connect localhost:25 -starttls smtp`

btw. why is the above log trying to connect to `mx.maxus.email` when your mx record points to `maxus.email`?

**Comment by marrco** [comment]
I'd say your MX is set correct. Btw, in your specific case, you did not even need an MX record to set it, the A record at the root is enough. The issue is just the timeout.

**Comment by vivernet** [comment]
Thank you, it worked. I do not know really what the problem was, but after the updates, installed mailcow again from scratch, and everything works fine :-)

**Comment by vivernet** [comment]
broedli, due to the fact that I tried different ways to configure mailcow, thought suddenly the problem was it stupid of course but decided to check all the options. At the time, however MX records are configured correctly.
