### ISSUE TITLE
Execute script from Sieve with vnd.dovecot.filter

### ISSUE THREAD

**Issue by RudySixOw** [mailcow/mailcow-dockerized#2012]
Hello, sorry for my english and if this question has already been asked.
I am looking to run a script (bash) with a condition.
But as soon as I put: require "vnd.dovecot.filter"or "vnd.dovecot.execute" or "vnd.dovecot.pipe", I have an error: quoted string "vnd.dovecot.filter" where require string expected.
Example:
require "variables";
require "subaddress";
require "envelope";
require "vnd.dovecot.filter";

if allof (address: contains "to" "mail@domain.com") {

     filter "script.sh";

}

Thanks in advance.

**Comment by mkuron** [comment]
According to https://wiki2.dovecot.org/Pigeonhole/Sieve/Plugins/Extprograms, you need to add `sieve_plugins = sieve_extprograms` to data/conf/dovecot/dovecot.conf.

It most likely won't be very useful though as the script would be executed inside the Dovecot container, which has only a limited scripting environment and little access to outside data.

**Comment by RudySixOw** [comment]
Thank you for your answer
 but sieve_plugins = sieve_extprograms and already in data / conf / 
dovecot / dovecot.conf, but I have the error that I mentioned.

Otherwise for the script, it's not a big deal because I just run a curl
that I tested in the bash of the container.



-------- Message initial --------

Date: Thu, 15 Nov 2018 09:13:19 -0800
Objet: Re: [mailcow/mailcow-dockerized] Execute script from Sieve
(#2012)
Cc: RudySixOw <rudysixow@gmail.com>, Author <author@noreply.github.com>
À: mailcow/mailcow-dockerized <mailcow-dockerized@noreply.github.com>
Reply-to: mailcow/mailcow-dockerized <reply+0163b618f321c1bfd81045dca73
cf9f52cc8c611a313b1dc92cf0000000118056b2f92a169ce16b873e2@reply.github.
com>
De: Michael Kuron <notifications@github.com>
According to https://wiki2.dovecot.org/Pigeonhole/Sieve/Plugins/Extprog
rams, you need to add sieve_plugins = sieve_extprograms to
data/conf/dovecot/dovecot.conf.

It most likely won't be very useful though as the script would be
executed inside the Dovecot container, which has only a limited
scripting environment and little access to outside data.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/mailcow/mailc
ow-dockerized","title":"mailcow/mailcow-dockerized","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/emai
l/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name":
"Open in GitHub","url":"https://github.com/mailcow/mailcow-
dockerized"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mkuro
n in #2012: According to
https://wiki2.dovecot.org/Pigeonhole/Sieve/Plugins/Extprograms, you
need to add `sieve_plugins = sieve_extprograms` to
data/conf/dovecot/dovecot.conf.\r\n\r\nIt most likely won't be very
useful though as the script would be executed inside the Dovecot
container, which has only a limited scripting environment and little
access to outside data."}],"action":{"name":"View
Issue","url":"https://github.com/mailcow/mailcow-
dockerized/issues/2012#issuecomment-439117266"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mailcow/mailcow-dockerized/issues/2012#is
suecomment-439117266",
"url": "https://github.com/mailcow/mailcow-dockerized/issues/2012#issue
comment-439117266",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mailcow/mailcow-dockerized] Execute script from Sieve
(#2012)",
"sections": [
{
"text": "",
"activityTitle": "**Michael Kuron**",
"activityImage": "https://assets-cdn.github.com/images/email/message_ca
rds/avatar.png",
"activitySubtitle": "@mkuron",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\":
\"mailcow/mailcow-dockerized\",\n\"issueId\": 2012,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mailcow/mailcow-dockerized/issues/2012#issue
comment-439117266"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
411019006\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mkuron** [comment]
Reopening as requested in #2026

**Comment by RudySixOw** [comment]
No body need this feature ?

**Comment by RudySixOw** [comment]
Sorry to insist but I would like to know if this function will be available because it is really necessary.
The answer that I was given as I explained is not functional in the state.
thanks in advance.

**Comment by andryyy** [comment]
Why is it necessary? :/

You get this error when adding the script via UI?

**Comment by RudySixOw** [comment]
thanks for answering.
I need according to certain criteria to send SMS.

Yes i have this error message with UI but when i try in CLI that don't work too.

**Comment by andryyy** [comment]
From CLI, too? Which error? What exactly do you do? Where do you place the shell script, where do you place the sieve script?

**Comment by RudySixOw** [comment]
I do not remember too much, I will retest and come back to you.
But of memory I had no error but the script was not launched.

**Comment by RudySixOw** [comment]
Well apparently it only works in GLOBAL SIEVE.
I have in dovecot.conf:
  sieve_global_extensions = + vnd.dovecot.pipe + vnd.dovecot.execute + vacation-seconds + vnd.dovecot.environment + vnd.dovecot.filter
   sieve_execute_bin_dir = / var / vmail / sieve /
   sieve_filter_bin_dir = / var / vmail / sieve /

then a rule in /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/sieve/global.sieve:
if allof (address: contains "to" "test@mail.com") {

     filter "script.sh";

then I did:
/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/sieve/script.sh

Everything works with these parameters.
Thank you for your help and for working.

**Comment by RudySixOw** [comment]
Hi, I think there is no module in /usr/lib/dovecot/sieve/ or /usr/lib/dovecot/modules/sieve/ like sieve-execute
