### ISSUE TITLE
Non existing address not getting rejected deferred instead 

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#2013]
**Describe the bug**
Ever since the last update when the option to change the Mailbox format was added any email sent to a non existing mailbox results in a defer  Temporary lookup failure not a reject as it should.

The issue seem to be caused by this line https://github.com/mailcow/mailcow-dockerized/blob/2515a91ac3d4c4270bab9738341b0315d5a2b3f8/data/Dockerfiles/postfix/postfix.sh#L187 as the database on my install dose not have the field mailbox_format and a quick look at init_db.inc.php that field doesn't not exist  so this issue will effect new and older updated installs.

**How to reproduce Reproduce**
The steps to reproduce are simple just send a email to a non existing mailbox of a domain hosted on Mailcow.

**Expected behaviour**
The expected behaviour is that the mail would be rejected not defered. 

**Logs**

<pre>
NOQUEUE: reject: RCPT from mail-yb1-f178.google.com[209.85.219.178]: 451 4.3.0 <bob@*****.eu>: Temporary lookup failure; from=<******@gmail.com> to=<bob@razza.eu> proto=ESMTP helo=<mail-yb1-f178.google.com>

warning: proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_mailbox_maps.cf lookup error for "bob@****.eu"

warning: mysql:/opt/postfix/conf/sql/mysql_virtual_mailbox_maps.cf: query failed: Unknown column 'mailbox_format' in 'field list'
--

</pre>

**Comment by andryyy** [comment]
Thanks, I totally missed that.
