### ISSUE TITLE
HFILTER_HOSTNAME_UNKNOWN always triggers

### ISSUE THREAD

**Issue by langerc** [mailcow/mailcow-dockerized#2014]
I have 3 instances of mailcow up and running in different datacenters.

The spam rule HFILTER_HOSTNAME_UNKNOWN always triggers and adds spam rating to mails that should not have it.

So every mail, does not matter if the host that sent the mail is good or bad will get the 
HFILTER_HOSTNAME_UNKNOWN(2.50)[]
added to its spam score which puts a lot of mails into spam.

The dns status page shows that the local mailserver has a correct ptr record.

If i attach myself to the unbound docker instance (exec ..) and use nslookup to ask for the ptr record of the remote mailserver that was marked as invalid the ptr record resolves correct.

**Expected behavior**
A domain that has a valid ip / namemapping should not be marked as hostname unknown

**System**
 - ubuntu 16
 - docker

**Comment by andryyy** [comment]
Hi,
Can you post a mail or multiple mails with this score?

**Comment by langerc** [comment]
i just found a thing - i use a smtp proxy that does antivirus and antispam in front of the mailserver seems there is an internal ip that was not mapped. i mapped it and will doublecheck in a few hours.

Received: ⁨from firewall (unknown [x.x.x.x]) - this might cause the problem.
i dont want to add the ip to the relay hosts because i would like mails to be analized parsed and sorted by mailcow.
