### ISSUE TITLE
Clamav not working

### ISSUE THREAD

**Issue by techox21** [mailcow/mailcow-dockerized#2015]
Hello,

the clamd-mailcow service does not reject a test email with a eicar attachment. 
If i look into the log files, i can see that the clamd-mailcow service ist running and still up-to-date.
Is there any settings i have to do?

Thanks.

**Comment by patschi** [comment]
I can reproduce this by using the [Heise EICAR Test mailer](https://www.heise.de/security/dienste/emailcheck/virendummies/send-url-eicar/). In this case even Outlook had to block the file after delivering the mail with the fake virus:
![image](https://user-images.githubusercontent.com/2029878/48733823-ff00b300-ec43-11e8-8310-e1642df0961d.png)

```
X-Rspamd-Queue-Id: E94EB4417
X-Spamd-Result: default: False [7.91 / 20.00];
	 ARC_NA(0.00)[];
	 RCPT_WANTS_SUBJECT_TAG(0.00)[mail@domain.tld];
	 XM_UA_NO_VERSION(0.01)[];
	 FROM_HAS_DN(0.00)[];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 HAS_ATTACHMENT(0.00)[];
	 MIME_GOOD(-0.10)[multipart/mixed,text/plain];
	 TO_DN_NONE(0.00)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 BAYES_SPAM(0.00)[18.21%];
	 FROM_EQ_ENVFROM(0.00)[];
	 MIME_BAD_EXTENSION(8.00)[com];
	 RCVD_TLS_LAST(0.00)[];
	 RCVD_COUNT_TWO(0.00)[2];
	 JUST_EICAR(0.00)[Eicar-Test-Signature];
	 RCPT_MAILCOW_DOMAIN(0.00)[domain.tld]
X-Spam-Flag: YES
X-Spam: Yes
```

Apparently the EICAR signature is being detected, see header `JUST_EICAR(0.00)`, but not declined? Shouldn't be such mails still be declined to verify that clamav is working?

**Comment by mkuron** [comment]
Eicar is not a good test here; you could try an actual virus. If you look in rspamd‘s settings, you can see that Eicar messages get the JUST_EICAR symbol instead of the CLAM_VIRUS symbol that we check for: 
https://github.com/rspamd/rspamd/blob/master/conf/modules.d/antivirus.conf#L46
