### ISSUE TITLE
IMAP sync custom options with a space in argument results in error

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#2017]
**Describe the bug**
When using custom options with a IMAP sync job, resulting in the following error:
`Extra arguments found: Messages"=Trash
It usually means a quoting issue in the command line
Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
`
I guess the custom parameter field is not correctly quoted when added to the imapsync command line. I need the quotes because the space in a folder name.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. sync job created
2. with option 'Try to automap folders' enabled.
3. Set custom parameter: `--dry --f1f2 "Deleted Messages"=Trash`

I tried different combinations of the double/single quotes.
Like:
`--dry --f1f2 'Deleted Messages'=Trash`
`--dry --f1f2 "'Deleted Messages'='Trash'"`
`"--dry --f1f2 'Deleted Messages'=Trash"`
etc
Results always in the similar error message.

**Expected behavior**
sync job should run with complete custom commands including the correct quotes.
`--dry --f1f2 "Deleted Messages"=Trash`
I added dry option to see if it will process the custom parameter(s) correctly or not.

**Logs**
Output of sync job:
`Extra arguments found: Messages"=Trash
It usually means a quoting issue in the command line
Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
`

**System**
 - OS: Centos 7.5

**Comment by hunter-nl** [comment]
In data/Dockerfiles/dovecot/imapsync_cron.pl file at line 21:
`sub qqw($) { split /\s+/, $_[0] }` is always split on any space it founds in the custom parameters field.
Split function should only happen on  each `--argument 'eventually some value'` parts.

**Comment by hunter-nl** [comment]
@andryyy Can you apply this fix?
Replace 
In data/Dockerfiles/dovecot/imapsync_cron.pl file at line 21:
`sub qqw($) { split /\s+/, $_[0] }`
into
```
sub qqw($) {
        my @values = split('(?=--)', $_[0]);
        foreach my $val (@values) {
                $val=trim($val);
        }
        return @values
}
```
This results that custom parameters are split on the -- part. Example:
`'--option1 --option2 --option3 "test string " --option4 test with spaces '`
Results into a array:
```
[
          '--option1',
          '--option2',
          '--option3 "test string "',
          '--option4 test with spaces'
]
```

**Comment by andryyy** [comment]
I will try asap. :)

**Comment by andryyy** [comment]
Have you tested all cases?

**Comment by hunter-nl** [comment]
@andryyy Sorry for the late response. Yes I've test many different cases. And you already did the fix. I tested this also and it's just working fine now. Thank you!

**Comment by andryyy** [comment]
Thank _you_ :)

**Comment by QuocurIQ** [comment]
I tried many different quoting options and can't get it to work. I checked the data/Dockerfiles/dovecot/imapsync_cron.pl, it contains something similar to 
sub qqw($) {
        my @values = split('(?=--)', $_[0]);
        foreach my $val (@values) {
                $val=trim($val);
        }
        return @values
}

I don't know how I should understand this:
'--option1 --option2 --option3 "test string " --option4 test with spaces '

I tried enclosing all arguments in single quotes and parameters in double, only parameters in double, only parameters in single ....

nothing works
I use --folder=ARCHIV 2 or --folder="ARCHIV 2" or '--folder=ARCHIV 2"' or '--folder=ARCHIV 2 "' as sugested by this example '--option1 --option2 --option3 "test string " --option4 test with spaces '

**Comment by QuocurIQ** [comment]
data/Dockerfiles/dovecot/imapsync_cron.pl is quite a bit different now, compared to the suggestion above:

sub qqw($) {
  my @params = ();
  my @values = split(/(?=--)/, $_[0]);
  foreach my $val (@values) {
    my @tmpparam = split(/ /, $val, 2);
    foreach my $tmpval (@tmpparam) {
        if ($tmpval ne '') {
          push @params, $tmpval;
        }
    }
  }
  foreach my $val (@params) {
    $val=trim($val);
  }
  return @params;
}
