### ISSUE TITLE
Re, Execute script from sieve with vnd.dovecot.filter

### ISSUE THREAD

**Issue by RudySixOw** [mailcow/mailcow-dockerized#2026]
Thanks you for your answer and sorry to rest but I can not reopen it and I did not get an answer.

sieve_plugins = sieve_extprograms and already in data / conf / 
dovecot / dovecot.conf, but I have the error that I mentioned.

Otherwise for the script, it's not a big deal because I just run a curl
that I tested in the bash of the container.

**Comment by andryyy** [comment]
Can you please write in the closed issue? I don't know the reference here.

**Comment by RudySixOw** [comment]
Hello, sorry for my english and if this question has already been asked.
I am looking to run a script (bash) with a condition.
But as soon as I put: require "vnd.dovecot.filter"or "vnd.dovecot.execute" or "vnd.dovecot.pipe", I have an error: quoted string "vnd.dovecot.filter" where require string expected.
Example:
require "variables";
require "subaddress";
require "envelope";
require "vnd.dovecot.filter";

if allof (address: contains "to" "mail@domain.com") {

 filter "script.sh";

}

Thanks in advance.

**Comment by RudySixOw** [comment]
Sorry to insist but I would like to know if this function will be available because it is really necessary.
The answer that I was given as I explained is not functional in the state.
thanks in advance.

**Comment by RudySixOw** [comment]
Hi, I think there is no module in /usr/lib/dovecot/sieve/ or /usr/lib/dovecot/modules/sieve/ like sieve-execute
