### ISSUE TITLE
NSException: 0x555b8d4705f0

### ISSUE THREAD

**Issue by matias-casal** [mailcow/mailcow-dockerized#2030]
When i try to log in Sogo:
`sogod[60:60] EXCEPTION: <NSException: 0x555b8d4705f0> NAME:NSRangeException REASON:Range location + length too great INFO:(null)`

Any ideas? i really apreciate help

**Comment by andryyy** [comment]
Moving data from an old installation to a new server with new code was probably not a good idea.

The JS error just happened due to old browser cache data.

Please mail me to Info@Servercow.de and I will fix it, if you want to.
