### ISSUE TITLE
Block domain countries with mailcow

### ISSUE THREAD

**Issue by xL0b0** [mailcow/mailcow-dockerized#2031]
Hello. I’m somehow receiving emails from Russian domains lately. Is it somehow possible with Rspamd do decline all emails that end with .ru ? Not just an entire domain ?

**Comment by xL0b0** [comment]
Please help.

**Comment by xL0b0** [comment]
@andryyy

**Comment by andryyy** [comment]
Hey, you are better of asking this on IRC.
Did you update recently? If so, you can open Rspamd UI, go to "Configuration" and open /etc/rspamd/custom/global_from_blacklist.map.
Add `/.*\.ru/i` here.

**Comment by xL0b0** [comment]
Hm, I tried it with my other email, with the ending .email. E-Mail's still go through and aren't blocked. I hit "save changes" and restarted the rspamd container (I'm on latest version.) Did I do something wrong ?
File is looking like that:
```
# /.*@example.com/i
/.*\.email/i
```

**Comment by andryyy** [comment]
`/.+\.ru/i` worked for me.

**Comment by xL0b0** [comment]
Tried with E-Mail, mails still aren't blocked. Do I need to save it on cluster ?

**Comment by andryyy** [comment]
It works like that. Check the file in an editor, recheck the syntax, remove everything else from that file.
Please ask in IRC for further help, we don't use GitHub as support channel.
