### ISSUE TITLE
rspamd: got unexpected http status: 505

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2034]
**Describe the bug**
After latest update rspamd logs "got unexpected http status: 505" when rejecting mails, which should be filed in quarantine.

Maybe someone can help?
Thank you :)

**Comment by andryyy** [comment]
Hi, check your quarantine settings. "0" is not unlimited.

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/48935818-44093b80-ef09-11e8-9531-834e09d59eba.png)
There. :-)

**Comment by ghost** [comment]
Hi andryyy, thank you for your quick response! I missed that setting :(
I now set it up and look forward for some spam to test it :)

**Comment by andryyy** [comment]
It was buggy before and accepted mails when it shouldn't. :-( So I'm to blame, too. 

505 should be the return code for when mail size > max. mail size.

**Comment by ghost** [comment]
I never heard about HTTP 505 before, so didn't know where to start troubleshooting :) Thank you very much for your help!

**Comment by andryyy** [comment]
I just added them to track the errors. :-)
