### ISSUE TITLE
Mailbox.attributes should be reset to defaults if null

### ISSUE THREAD

**Issue by plokko** [mailcow/mailcow-dockerized#2035]
I recently had a lot of problems due to a mailcow update:
the mailbox panel was not working and all the mailboxes gave me an authentication error.

After a LOT of debugging i found the problem: Mailcow does not handle well if mailbox.attributes mysql row is null and not a valid JSON object.

I fixed the javascript panel error caused by a missing null checking on item.attributes but i still got the POP3 authentication error.

The reason is because if mailbox.attributes is null the values are not applied in the database.
I did fix the problem by running a simple sql script but it could be handled a little better.

**Comment by hachre** [comment]
I think this can be closed as the underlying bug has been found and fixed via:
https://github.com/mailcow/mailcow-dockerized/commit/09a2b2d16d34d0445f7b48f372a92a8648ae4897

More info:
https://github.com/mailcow/mailcow-dockerized/issues/2041#issuecomment-442030619
