### ISSUE TITLE
mailcow-dockerized is slow

### ISSUE THREAD

**Issue by perteraul** [mailcow/mailcow-dockerized#2037]
**Describe the bug**
After a clean install of mailcow-dockerized on the $5 DigitalOcean droplet, the login and every request I made after the login was incredibly slow (3-15min) and often I had to refresh the page multime times to get past the login.

**Comment by chriscroome** [comment]
Try running Mailcow on a VM with more RAM and CPU, if I was going to pick a minimum spec from [DigitalOcean](https://www.digitalocean.com/pricing/#tab-compute) I'd suggest:

```
4 GB | 2 vCPUs | 80 GB | 4 TB | $20/mo
```
But some people might well be running on less, the virtual servers I run Mailcow on have between 12G and 36G of RAM each...

**Comment by andryyy** [comment]
I can give you the same price at Servercow without bad IP reputation. 

Edit: Resources are most likely not the issue here. Sounds like it bans you or something. We obviously need any logs. 

PS: You can get support on IRC. It says so in the issue template you deleted. :-(

**Comment by perteraul** [comment]
Thanks! I was thinking of joining Servercow.

**Comment by perteraul** [comment]
I gave Virtualmin a try — if it goes wrong, will turn to Servercow.
