### ISSUE TITLE
Anonymize Mime-Version header

### ISSUE THREAD

**Issue by telnet23** [mailcow/mailcow-dockerized#2039]
**Is your feature request related to a problem? Please describe.**
Mail.app in macOS adds `Mime-Version: 1.0 (Mac OS X Mail 12.1 \(3445.100.42\))` to outgoing messages.

**Describe the solution you'd like**
`Mime-Version: 1.0` is required by [RFC1341](https://tools.ietf.org/html/rfc1341). Add a rule in `anonymize_headers.pcre` to remove the parenthesized part.

**Additional context**
I thought `/^\s*Mime-Version:\s*(\S+).*/ REPLACE Mime-Version: $1` would work, but it doesn't seem to.

**Comment by andryyy** [comment]
This seems to be signed from time to time, so we cannot change it.

@mkuron you probably saw the same?

**Comment by mkuron** [comment]
Yes, I have seen `Mime-Version` and `User-Agent` included in DKIM signatures, so they must not be removed. Any `X-` should be relatively safe to remove, and the first `Received` header as we have the special `Postcow` check. So we shouldn’t add anything beyond what‘s already in 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/anonymize_headers.pcre.
