### ISSUE TITLE
folders encoding after update

### ISSUE THREAD

**Issue by SDFka** [mailcow/mailcow-dockerized#2040]
Hello! 
After update all user-made folders in all users mailboxes on server became unreadable format, i think is something with utf-8 encoding in dovecot.

This is user mailbox folders before update.
![1outlook](https://user-images.githubusercontent.com/44536779/48988134-e5c0a080-f134-11e8-9f6d-2383ef39cddf.png)
Same server, after update.
![2outlook](https://user-images.githubusercontent.com/44536779/48988152-f709ad00-f134-11e8-8d27-31dd3e47b647.png)

Here is docker-compose.yml files before and after update in zip
[docker-compose.zip](https://github.com/mailcow/mailcow-dockerized/files/2613783/docker-compose.zip)
.

**Comment by mkuron** [comment]
I can confirm that I‘ve also seen this happen recently.

**Comment by andryyy** [comment]
Yes, I’ve seen this flag on Friday and was reminded I didn’t remove it. Will fix it.

**Comment by FlyingEagle** [comment]
I have the same problem.
Is there a hot fix somewhere?

**Comment by andryyy** [comment]
The change was reverted a month ago.
