### ISSUE TITLE
No MailBox, Login, ... after update

### ISSUE THREAD

**Issue by Marvo2011** [mailcow/mailcow-dockerized#2041]
Hello,

I have updated the mailcow with ./update.sh after them I can't login to my Mailbox's.
I have found some error messages. In mailcow admin under "Mailbox" there is a infinity loading circle.

SOGo Error:
`Failed to load resource: the server responded with a status of 501 (Request Failed)`

Error in mailcow admin
`Uncaught TypeError: Cannot read property 'tls_enforce_in' of null
    at Object.<anonymous> (mailbox.js:351)
    at Function.each (jquery-1.12.4.min.js:2)
    at Object.success (mailbox.js:340)
    at i (jquery-1.12.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js:2)
    at y (jquery-1.12.4.min.js:4)
    at XMLHttpRequest.c (jquery-1.12.4.min.js:4)`

Dovecot login request (also not working):
`
26.11.2018, 14:12:06 | info | imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<mail@domain.tld>, method=PLAIN, rip=RouterIP, lip=172.22.1.4, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
-- | -- | --
26.11.2018, 14:12:03 | info | imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=RouterIP, lip=172.22.1.4, TLS: Connection closed, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)

`

**Comment by hachre** [comment]
Seems related to https://github.com/mailcow/mailcow-dockerized/issues/2035

**Comment by Marvo2011** [comment]
Thanks

here is the mysql output:

MariaDB [mailcow]> select attributes from mailbox;
+------------+
| attributes |
+------------+
| NULL       |
| NULL       |
| NULL       |
+------------+
3 rows in set (0.00 sec)

helps to edit the rows?

**Comment by hachre** [comment]
The contents of the attribute fields should look like this, it may be enough to just set it to `{}` though:
```
{"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"}
```

**Comment by andryyy** [comment]
Why is it NULL?

**Comment by hachre** [comment]
Is it possible that people who haven't updated in a while (maybe since before the attribute field existed), aren't upgraded properly?

**Comment by Marvo2011** [comment]
I have updated a older instance. 
With `{"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"}` I can login to SOGo but not to imap. **And there are no mails?**

**Comment by andryyy** [comment]
Hm, but it would set the field @hachre 
```
$stmt = $pdo->query("UPDATE `mailbox` SET `attributes` = '{}' WHERE `attributes` = '' OR NULL;");
```

**Comment by hachre** [comment]
> I have updated a older instance.
> With `{"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"}` I can login to SOGo but not to imap. **And there are no mails?**

Try `docker-compose down && docker-compose up -d`

**Comment by Marvo2011** [comment]
Same "No mailbox selected" in SOGo and no **imap** login.

**Comment by hachre** [comment]
Can you print the attributes contents again please, as you did before.

**Comment by hachre** [comment]
> Hm, but it would set the field @hachre
> 
> ```
> $stmt = $pdo->query("UPDATE `mailbox` SET `attributes` = '{}' WHERE `attributes` = '' OR NULL;");
> ```

Would this line only be called after logging into the web interface? Maybe something in the web interface requires the attributes fields before this line runs and thus breaks? Not sure.

Maybe it doesn't get run when people log in to the web interface but haven't erased their browser cache after an update?

**Comment by Marvo2011** [comment]
> Can you print the attributes contents again please, as you did before.

MariaDB [mailcow]> select attributes from mailbox;
+---------------------------------------------------------------------------------------------------------------------------+
| attributes                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------+
| {"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"} |
| {"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"} |
| {"force_pw_update": "0", "tls_enforce_in": "0", "tls_enforce_out": "0", "sogo_access": "1", "mailbox_format": "maildir:"} |
+---------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)

**Comment by hachre** [comment]
Okay, this looks fine now. It seems like you may be running outdated Docker images? Are you sure the `update.sh` went through?

Does your `docker-compose.yml` reference `image: mailcow/dovecot:1.45` for example? If so, you can try running `docker-compose down && docker-compose pull && docker-compose up -d` to make sure the images are up-to-date.

If it doesn't mention `dovecot:1.45`, run `./update.sh` again.

**Comment by Marvo2011** [comment]
`dovecot-mailcow:
      image: mailcow/dovecot:1.45
      build: ./data/Dockerfiles/dovecot
      cap_add:
        - NET_BIND_SERVICE
      volumes:
`
update.sh finished successfully, without an error. I will test `docker-compose down && docker-compose pull && docker-compose up -d`

**Comment by hachre** [comment]
Sorry, yes, 1.45 is current.

**Comment by Marvo2011** [comment]
No change after `docker-compose down && docker-compose pull && docker-compose up -d`

**Comment by hachre** [comment]
Check to see whether the Mailbox area in the web interface works correctly now. It should...

**Comment by Marvo2011** [comment]
Still an empty mailbox, and no imap login.

**Comment by hachre** [comment]
No, I mean the Mailcow admin interface (not SOGo).

**Comment by Marvo2011** [comment]
This works, but I can't save any change.

**Comment by hachre** [comment]
Erase your browser cache, that's a typical problem we've seen after updates.

**Comment by Marvo2011** [comment]
Thanks, Now it works. After a success save from the mailcow admin. Imap and SOGo works.

**Comment by hachre** [comment]
👍 great, glad it's solved

**Comment by Smove** [comment]
> Hm, but it would set the field @hachre
> 
> ```
> $stmt = $pdo->query("UPDATE `mailbox` SET `attributes` = '{}' WHERE `attributes` = '' OR NULL;");
> ```

I tried to run that sql from console but it doesn't set the attributes. When i use
```
OR `attributes` IS NULL
```
at the end it works.

**Comment by andryyy** [comment]
That's true. Good catch, damn. :-)

**Comment by hachre** [comment]
@Smove great, thanks!

**Comment by Smove** [comment]
Note: I had to set this to a default value like `{"force_pw_update": "0", "sogo_access": "0"}`. Mailboxes with empty attributes had login problems.

**Comment by andryyy** [comment]
Yes, that’s correct. The attributes are obligatory.
