### ISSUE TITLE
nginx dont come up

### ISSUE THREAD

**Issue by sap-dev** [mailcow/mailcow-dockerized#2042]
Hi,

after a server reboot nginx container start but not work:

```
        mailcowdockerized_nginx-mailcow_1_2ad043b5777f
6c03a9dc0ab9        mailcow/netfilter:1.19   "python2 -u /server.…"   44 minutes ago      Up 23 minutes                                                                               


```

```

nginx: configuration file /etc/nginx/nginx.conf test failed
2018/11/26 14:48:18 [emerg] 12#12: host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: [emerg] host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: configuration file /etc/nginx/nginx.conf test failed
2018/11/26 14:49:20 [emerg] 12#12: host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: [emerg] host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: configuration file /etc/nginx/nginx.conf test failed
```

When i open the Website, nginx 502 error show.

Have you an idea?
an update.sh run dont change anything

Thanks a lot!

**Comment by hachre** [comment]
Most likely cause is a firewall is running on the host

**Comment by sap-dev** [comment]
Hi,

i have already clean all iptables and no other firewall is enabled.

**Comment by andryyy** [comment]
When you clean iptables, everything stops working in Docker.

Try docker-compose down, systemctl restart docker, docker-compose up -d

**Comment by phipag** [comment]
I am encountering the same error "Nginx 502 Bad Gateway" even though I have disabled every iptables rules on my server.

I also receive Mails Watchdog: sogo-mailcow hit the error rate limit. The appended  log file is empty unfortunately

**Comment by andryyy** [comment]
That’s expected when you disable/remove all iptables rules. That’s not a mailcow issue unfortunately.

**Comment by MAGICCC** [comment]
Better don't do any iptable thing on your server when its running docker

**Comment by phipag** [comment]
I have Never Done anything with iptables. It was just after the update. I just removed all iptables rules to be save. 

However the error persists even if I restart the whole server (no firewall rules are applied)

**Comment by andryyy** [comment]
Okay, post some logs then please. 

php-fpm-mailcow will be useful.

**Comment by andryyy** [comment]
And please update again.

**Comment by phipag** [comment]
Okay, I updated again and there is an error in php-fpm:
```
php-fpm-mailcow_1_bd5da5c99cb9 | Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1356 View 'mailcow.sogo_view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them in /web/inc/init_db.inc.php:1029
php-fpm-mailcow_1_bd5da5c99cb9 | Stack trace:
php-fpm-mailcow_1_bd5da5c99cb9 | #0 /web/inc/init_db.inc.php(1029): PDO->query('REPLACE INTO _s...')
php-fpm-mailcow_1_bd5da5c99cb9 | #1 {main}
php-fpm-mailcow_1_bd5da5c99cb9 |   thrown in /web/inc/init_db.inc.php on line 1029
```

**Comment by andryyy** [comment]
Can you please run update again?

**Comment by andryyy** [comment]
Ah. Hm. SOGo waits for the new schema and will not continue until php-fpm-mailcow has finished db init. But it will never finish, because the references in sogo_view are broken (expected). Meh.

Can you try again, @phipag ?

**Comment by phipag** [comment]
I ran `./update.sh` again, still the same error... Server reboot also does not help.

**Comment by phipag** [comment]
An other fact which is probably important, I ran apt-upgrade before I updated mailcow:
```
Install: containerd.io:amd64 (1.2.0-1, automatic), docker-ce-cli:amd64 (5:18.09.0~3-0~debian-stretch, automatic)
Upgrade: libseccomp2:amd64 (2.3.1-2.1, 2.3.1-2.1+deb9u1), gnupg-agent:amd64 (2.1.18-8~deb9u2, 2.1.18-8~deb9u3), libxapian30:amd64 (1.4.3-2+deb9u1, 1.4.3-2+deb9u2), libsystemd0:amd64 (232-25+deb9u4, 232-25+deb9u6), grub-common:amd64 (2.02~beta3-5, 2.02~beta3-5+deb9u1), grub2-common:amd64 (2.02~beta3-5, 2.02~beta3-5+deb9u1), udev:amd64 (232-25+deb9u4, 232-25+deb9u6), grub-pc:amd64 (2.02~beta3-5, 2.02~beta3-5+deb9u1), libx11-6:amd64 (2:1.6.4-3, 2:1.6.4-3+deb9u1), libudev1:amd64 (232-25+deb9u4, 232-25+deb9u6), grub-pc-bin:amd64 (2.02~beta3-5, 2.02~beta3-5+deb9u1), libfuse2:amd64 (2.9.7-1+deb9u1, 2.9.7-1+deb9u2), systemd-sysv:amd64 (232-25+deb9u4, 232-25+deb9u6), gpgv:amd64 (2.1.18-8~deb9u2, 2.1.18-8~deb9u3), libpam-systemd:amd64 (232-25+deb9u4, 232-25+deb9u6), systemd:amd64 (232-25+deb9u4, 232-25+deb9u6), libx11-data:amd64 (2:1.6.4-3, 2:1.6.4-3+deb9u1), libgnutls30:amd64 (3.5.8-5+deb9u3, 3.5.8-5+deb9u4), gnupg:amd64 (2.1.18-8~deb9u2, 2.1.18-8~deb9u3), linux-image-4.9.0-8-amd64:amd64 (4.9.110-3+deb9u6, 4.9.130-2), docker-ce:amd64 (18.06.1~ce~3-0~debian, 5:18.09.0~3-0~debian-stretch), base-files:amd64 (9.9+deb9u5, 9.9+deb9u6)
End-Date: 2018-11-27  16:28:20
```

**Comment by andryyy** [comment]
Sorry! I forgot to push. Run it again, please.

**Comment by phipag** [comment]
Okay, I updated again. Nice, it works! Thanks for the quick fix.

However, is this correct?
```
Pulling rspamd-mailcow    ... error
Pulling ...
ERROR: for rspamd-mailcow  manifest for mailcow/rspamd:1.31 not found
ERROR: manifest for mailcow/rspamd:1.31 not found
```

**Comment by andryyy** [comment]
Hm, it failed to push the image. I run it again and it worked. But it is okay as long as you could build it yourself. :-)

**Comment by phipag** [comment]
Okay, great. thanks for your support.
