### ISSUE TITLE
Properly disabling clamd

### ISSUE THREAD

**Issue by pjv** [mailcow/mailcow-dockerized#2045]
I have been running clamd, but memory is getting tight and I'm not seeing it actually catching any nasty files, so I want to disable it for now.

I set `SKIP_CLAMD=y` in `mailcow.conf` and then did a `docker-compose up -d`.

Docker rebuilt the `clamd-mailcow` container, but that container is still running. I tried tossing it out and restarting the whole stack, but it still got re-created. I read here that that is expected behavior and that the container is just not doing anything.

But, the mailcow.conf comments say this:

> Rspamd will auto-detect a missing ClamAV container

And now I am seeing errors in the rspamd log like this:

`CLAM_VIRUS [clamav]: failed to scan, maximum retransmits exceed`

So, is what I did the correct procedure to disable clamd and/or is there anything else I should be doing to cleanly disable it?

**Comment by MAGICCC** [comment]
Yes  that should do the trick. Just check your memory usage after disabling it :)

**Comment by pjv** [comment]
Thanks. 

Memory usage is definitely better, but I am wondering about rspamd retransmitting emails to clamd over and over until the max retransmits is exceeded. That seems like not the most efficient way to move mail through the pipeline, no?

**Comment by mkuron** [comment]
Last time I checked, rspamd remembers that ClamAV was unreachable and doesn‘t retry it for a certain time. You can also delete the contens of 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/antivirus.conf so rspamd doesn‘t even try.

**Comment by traumschule** [comment]
[clamd-off.patch](https://github.com/user-attachments/files/23290864/clamd-off.patch)
```
cd /opt/mailcow-dockerized

.env
# Skip ClamAV (clamd-mailcow) anti-virus (Rspamd will auto-detect a missing ClamAV container) - y/n
SKIP_CLAMD=y

# Skip Olefy (olefy-mailcow) anti-virus for Office documents (Rspamd will auto-detect a missing Olefy container) - y/n
SKIP_OLEFY=y

patch docker-compose.yml clamd-off.patch
docker compose down clamd-mailcow
docker compose down ofelia-mailcow
docker compose up -d php-fpm-mailcow
docker compose up -d dovecot-mailcow
docker compose up -d sogo-mailcow
```
