### ISSUE TITLE
Color on categories from outlook with activesync

### ISSUE THREAD

**Issue by PeterHagen** [mailcow/mailcow-dockerized#2048]
I'm not sure if I should put this in a bug request or not, but, today I migrated our users from default Imap to mailcow. First of all, it works really nice! They use outlook here, so I connected it with activesync. I copied the contact from the local contactlist to the new mailbox contact, but noticed that the colors of the categories are not supported in SOGo. Is this correct?

**Comment by mitchellurgero** [comment]
You forgot to fill out the form bud.

**Comment by PeterHagen** [comment]
> You forgot to fill out the form bud.

some mysterious key combination made me post a bit to early... oops

**Comment by andryyy** [comment]
Hi, thanks for using mailcow. :) Please check https://sogo.nu/support.html for SOGo-related stuff. I will leave it open as question, maybe someone can jump in and help you.

**Comment by PeterHagen** [comment]
Thanks @andryyy, I now also noticed that the SOGo webinterface does have colors on labels for emails, and colors for categories on agenda, but the categories on the contacts are color-less.

**Comment by andryyy** [comment]
Okay, I don’t do SOGo support. If you use it commercially, you will need a support subscription. Else you can try to open a feature request on their public bug tracker.

ActiveSync has some limitations. I don’t really care personally.
