### ISSUE TITLE
Restart webserver

### ISSUE THREAD

**Issue by Individuum92** [mailcow/mailcow-dockerized#2049]
Hi There!

I currently installed mailcow for the first time. 
I have successfully installed mailcow and have configured it so that e-mails are working fine.

Now i wanna configure an Apache2 webserver as an VirtualHost to let e.g. run a website on this webserver. But first, i wanna to stop the webserver on which mailcow communicate. 

But i have no nginx webserver on running at the moment. How can i stop / restart the webserver?

> root@test:/opt/mailcow-dockerized# service nginx status
Unit nginx.service could not be found.

**Comment by hachre** [comment]
`docker-compose stop nginx-mailcow` 

You can get a list of all the names of the sub-services by running `docker-compose ps`.

Also there's good documentation on what you have to set up in Apache to allow Mailcow's server to be reachable through that here:
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

**Comment by mritzmann** [comment]
You can also bind nginx to another Port: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/
