### ISSUE TITLE
Can't delete emails on SOGo interface

### ISSUE THREAD

**Issue by wblondel** [mailcow/mailcow-dockerized#2050]
**Describe the bug**
I can't delete any email on SOGo interface.
In the browser console, there is this error:

```
DOMException: "Permission denied to access property "$mailboxController" on cross-origin object" angular.js:15536:15
	e/< angular.js:15536:15
	Ef/this.$get</< angular.js:11815:6
	$apply angular.js:19460:10
	compile/</< angular.js:28819:12
	og angular.js:3805:2
	d angular.js:3793:8
```
No network requests are made.

It happens since today, and I didn't update anything...

**How to reproduce the bug**
1. Open the SOGo interface.
2. Delete an email

**Expected behavior**
The email should be deleted.

**System**
 - OS: Antergos
 - Browser: Firefox 63.0.3

**Comment by andryyy** [comment]
Can neither confirm this nor help with SOGo. Please check your browser and file a bug with SOGo.

**Comment by hachre** [comment]
Could be a browser extension interfering.

**Comment by andryyy** [comment]
That's probably the problem. :)

**Comment by wblondel** [comment]
Today it works... and I didn't update anything... neither the browser nor the extensions .. :/

**Comment by thecooperative1** [comment]
I have run into this just now in Firefox 64, works as expected in Chromium... and yes, a SOGo thing rather than mailcow, but searching on the error in the console brought me here.
