### ISSUE TITLE
SMTP Service outages

### ISSUE THREAD

**Issue by entr0p1** [mailcow/mailcow-dockerized#2052]
Hi guys,

Having some trouble with the SMTP service on my MailCow instance, details below. As a side note, thanks for creating this awesome product. It's well thought out, lightweight and feature packed!

**Describe the bug**
I have external monitoring of the SMTP port (using StatusCake) and every couple of hours it detects a small outage of the SMTP service (shows up as connection timeout/connection refused). I'm now seeing log entries for Postfix that show this:
```
Temporary internal error (in reply to RCPT TO command))
```
I think these may be two separate issues though. I'm unable to receive mail when this message is being displayed in the logs, but when StatusCake registers an outage it's usually really brief (15 minutes or so) so I will receive the mail, just delayed.

**How to reproduce**
Generally the server will trigger a "Down" alert from StatusCake after being in operation for a few hours and will continue to flap every couple of hours or so.

**System**
 - OS: Oracle Linux Server 7.6
 - Memory: Dynamic memory (Hyper-V), maximum set to 6GB (it does reach this however the VM still has memory available when the issues occur)

**Comment by mkuron** [comment]
There should be a more specific message in the Postfix log right before the one you posted, please check. Probably something about DNS or the database.

**Comment by entr0p1** [comment]
Well, I'm a bit of a dunce. I've just worked out that my updates to MailCow haven't actually been installing because Docker needs exec access to /tmp, which I deny (for security reasons). For anyone else who stumbles upon this, I run these commands to temporarily point docker-compose elsewhere for the update:
```
set TMPDIR=/srv/compose-tmp
export TMPDIR=/srv/compose-tmp
```
That fixed the errors in the SMTP logs, but to answer your original question this is what I could find:
```
host dovecot[172.22.1.7] said: 451 4.3.0 <XXX@XXX.XXX> Temporary internal error (in reply to RCPT TO command)
to=<XXX@XXX.XXX>, orig_to=<YYY@XXX.XXX>, relay=dovecot[fd4d:6169:6c63:6f77::9]:24, delay=48957, delays=48957/0.11/0.19/0.06, dsn=4.3.0, status=deferred (host dovecot[fd4d:6169:6c63:6f77::9] said: 451 4.3.0 <XXX@XXX.XXX> Temporary internal error (in reply to RCPT TO command))
```
I'll keep an eye on the monitoring and see if it starts flapping again, I should have a pretty clear idea by tomorrow if it's going to play up again. So far, so good.
