### ISSUE TITLE
Disable ssl for pop3

### ISSUE THREAD

**Issue by billspills** [mailcow/mailcow-dockerized#2053]
Is it possible to disable only ssl for pop3 so that the authentication can be in plaintext？
If so what dovecot config would i change to restart the container ?

Thanks

**Comment by andryyy** [comment]
You could create a `data/conf/dovecot/extra.conf` file and add something like `login_trusted_networks = 1.1.0.0/16`. Or disable it all together with `disable_plaintext_auth = no`.

You'd need to restart with `docker-compose restart dovecot-mailcow`.

I don't know if you can disable it only for pop3 though. You may ask in #dovecot on Freenode.

**Comment by billspills** [comment]
Got it working, Thanks for the help.
