### ISSUE TITLE
Popup after update

### ISSUE THREAD

**Issue by pitah81** [mailcow/mailcow-dockerized#2060]
Hi

Firstly I just want to say that I love Mailcow, this is an absolut winner mail solution 👍

However I do have a small itch that has turned up some updates ago. When logging in as myself in the administration interface I get this orange popup telling me "Could not determine servers default spam score, assuming default". I tried resetting the spam rating to server default with the only result is that I get an green popup telling me it has been reset and also the same orange popup as before on-top of that one.

Have I missed some detail in an earlier update resulting in this or what could have gone wrong?

Best regards
Peter

**Comment by andryyy** [comment]
Hi,

Thank you! :)

Did you remove scores for "add_header" or "reject"?

If not, can you please check the mailcow UI logs for this event?

**Comment by pitah81** [comment]
The only thing I can think of that I've changed when it comes to spam, is that I've whitelisted and blacklisted some domains and mail addresses.

Which logs should I look at?

**Comment by andryyy** [comment]
The mailcow UI logs, you find them in /debug under Logs.

**Comment by pitah81** [comment]
I solved this by reverting git tree and dropping untracked files, don't know why this happened as I haven't changed the files manually. Anyway, I don't get the error message anymore thankfully.
