### ISSUE TITLE
NetFilter bans not working

### ISSUE THREAD

**Issue by theblains** [mailcow/mailcow-dockerized#2062]
**Describe the bug**
IP's go into the ban list correctly but does not seem to affect actually connecting to the services (it doesn't stop them)

**How to reproduce Reproduce**
Type in the incorrect username and password the required number of times get on the ban list according to logs but can still try logging in and using a correct password lets me in.

**Expected behavior**
Stop All login requests

**Logs**

02/12/2018, 13:36:21 | crit | Banning 92.40.249.0/24
02/12/2018, 13:36:21 | warn | 92.40.249.231 matched rule id 6
02/12/2018, 13:36:07 | crit | Banning 92.40.249.0/24
02/12/2018, 13:36:07 | warn | 92.40.249.231 matched rule id 6
02/12/2018, 13:35:56 | warn | 1 more attempts in the next 1200 seconds until 92.40.249.0/24 is banned
02/12/2018, 13:35:56 | warn | 92.40.249.231 matched rule id 6
02/12/2018, 13:35:48 | warn | 2 more attempts in the next 1200 seconds until 92.40.249.0/24 is banned
02/12/2018, 13:35:48 | warn | 92.40.249.231 matched rule id 6
02/12/2018, 13:35:34 | warn | 3 more attempts in the next 1200 seconds until 92.40.249.0/24 is banned
02/12/2018, 13:35:34 | warn | 92.40.249.231 matched rule id 6
02/12/2018, 13:35:17 | warn | 4 more attempts in the next 1200 seconds until 92.40.249.0/24 is banned
02/12/2018, 13:35:17 | warn | 92.40.249.231 matched rule id 6

**System**
Tried a few as you can see it bans the /24 but still allows the pages to load and login requests not sure if its a configuration error. Tried on my phone and a VM with different external IPs. Manually added /24 onto the blacklist but this also did not do anything.

**Comment by mkuron** [comment]
Please show us the output of `iptables --list` after an address has been banned. Do you by chance have an iptables-based firewall configured? If so, it's most likely incompatible with Docker.

**Comment by andryyy** [comment]
Make sure you are not using any firewall like ufw, firewalld etc.

Even if you don't, there are some rare cases it is possible to connect, even if a ban was applied.

One of these cases is testing **from the Docker node itself** with something like smtp-cli. Or possibly even from within a container on the same Docker node (not tested).
A failed authentication will be logged from your **remote IP**. This remote IP will be banned. Let's say "92.40.249.123". Now netfilter-mailcow creates a rule inside the MAILCOW chain to ban everything from src 92.40.249.0/24.
Trying smtp-cli again will still be able, because netfilter will not see you as 92.40.249.123, but something like 172.22.1.1.

**Comment by theblains** [comment]
Thanks for the responses ill take a look, the only other thing I can think of is the nginx reverse proxy in front of it although as you can see it's passing the real IP though.

Its ubuntu 18 and ufw is dissabled

@mkuron Do i need to type that in the docker containers or just on the host? thanks edit see below

`
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
MAILCOW    all  --  anywhere             anywhere

Chain FORWARD (policy DROP)
target     prot opt source               destination
MAILCOW    all  --  anywhere             anywhere
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.22.1.5           tcp dpt:submission
ACCEPT     tcp  --  anywhere             172.22.1.5           tcp dpt:urd
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:12345
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:mysql
ACCEPT     tcp  --  anywhere             172.22.1.5           tcp dpt:smtp
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:sieve
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:pop3s
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:imaps
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:imap2
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:pop3
ACCEPT     tcp  --  anywhere             172.22.1.10          tcp dpt:https
ACCEPT     tcp  --  anywhere             172.22.1.10          tcp dpt:http

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain MAILCOW (2 references)
target     prot opt source               destination
REJECT     all  --  92.40.249.0.threembb.co.uk/24  anywhere             reject-with icmp-port-unreachable

`

**Comment by theblains** [comment]
Thanks for the help seems it was the reverse proxy being funky sorted it now.
