### ISSUE TITLE
mobileconfig.php errors with both iOS 12.1 and macOS Mojave

### ISSUE THREAD

**Issue by bplein** [mailcow/mailcow-dockerized#2063]
**Describe the bug**
When attempting to import mobileconfig.php, both my iphone and my macOS desktop report errors and cannot complete.
**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Using a browser, go to the URL for mobileconfig.php per the instructions in the documentation.
2. System error differs based on IOS vs. macOS but reflects an inability to import the profile

**Expected behavior**
Should just import the configuration

**Screenshots**
iOS 12.1
![img_1841](https://user-images.githubusercontent.com/260078/49341977-4448bb80-f61a-11e8-9184-6431d70c2f34.PNG)
![unadjustednonraw_thumb_14af](https://user-images.githubusercontent.com/260078/49341979-46ab1580-f61a-11e8-83cb-497ec8f58534.jpg)
![unadjustednonraw_thumb_14b0](https://user-images.githubusercontent.com/260078/49341982-4874d900-f61a-11e8-88dc-539e29f40c7c.jpg)

macOS Mojave 10.14
<img width="476" alt="screenshot 2018-12-02 10 08 36" src="https://user-images.githubusercontent.com/260078/49341993-7823e100-f61a-11e8-8c8e-440529c33ae5.png">
<img width="780" alt="screenshot 2018-12-02 10 09 05" src="https://user-images.githubusercontent.com/260078/49341994-7a863b00-f61a-11e8-9b48-5c7be5573030.png">

**Logs**
client side error. No logs found in macOS Console.

**System**
 - OS: iOS 12.1, Mojave 10.14
 - Browser: iOS is Safari, macOS is Firefox
 - Other clients involved: None

**Additional context**
No additional context at this time.

**Comment by bplein** [comment]
Additional info: I have an old mobileconfig from July 23 2018 that I used to set this machine up (I think! I can't remember if I had issues then or not!). This old one from July results in the SAME error.

The diff between OLD and LATEST is this:

```
diff Mailcow.mobileconfig Mailcow-3.mobileconfig
41c41
< 			<string>Bill Plein</string>
---
> 			<string>bill</string>
```

Where that is the email account name:
`<key>EmailAccountName</key>
                        <string>Bill Plein</string>`

I found one that I downloaded on Aug 6 2018 and it's identical to the one generated today.

**Comment by mkuron** [comment]
I am getting a valid mobileconfig from my Mailcow. Please upload yours here so we can have a look why it's broken.

**Comment by bplein** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>CalDAVAccountDescription</key>
			<string>plein.email</string>
			<key>CalDAVHostName</key>
			<string></string>
			<key>CalDAVPort</key>
			<real></real>
			<key>CalDAVPrincipalURL</key>
			<string>/SOGo/dav/test@plein.email</string>
			<key>CalDAVUseSSL</key>
			<true/>
			<key>CalDAVUsername</key>
			<string>test@plein.email</string>
			<key>PayloadDescription</key>
			<string>Configures CalDAV account.</string>
			<key>PayloadDisplayName</key>
			<string>CalDAV (plein.email)</string>
			<key>PayloadIdentifier</key>
			<string>email.plein.iphoneprofile.mailcow.CalDAV</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.caldav.account</string>
			<key>PayloadUUID</key>
			<string>FC898573-EBA8-48AF-93BD-BFA0C9778FA7</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>EmailAccountDescription</key>
			<string>plein.email</string>
			<key>EmailAccountType</key>
			<string>EmailTypeIMAP</string>
			<key>EmailAccountName</key>
			<string>test mailbox</string>
			<key>EmailAddress</key>
			<string>test@plein.email</string>
			<key>IncomingMailServerAuthentication</key>
			<string>EmailAuthPassword</string>
			<key>IncomingMailServerHostName</key>
			<string>mailhost.plein.email</string>
			<key>IncomingMailServerPortNumber</key>
			<integer>993</integer>
			<key>IncomingMailServerUseSSL</key>
			<true/>
			<key>IncomingMailServerUsername</key>
			<string>test@plein.email</string>
			<key>OutgoingMailServerAuthentication</key>
			<string>EmailAuthPassword</string>
			<key>OutgoingMailServerHostName</key>
			<string>mailhost.plein.email</string>
			<key>OutgoingMailServerPortNumber</key>
			<integer>465</integer>
			<key>OutgoingMailServerUseSSL</key>
			<true/>
			<key>OutgoingMailServerUsername</key>
			<string>test@plein.email</string>
			<key>OutgoingPasswordSameAsIncomingPassword</key>
			<true/>
			<key>PayloadDescription</key>
			<string>Configures email account.</string>
			<key>PayloadDisplayName</key>
			<string>IMAP Account (plein.email)</string>
			<key>PayloadIdentifier</key>
			<string>email.plein.iphoneprofile.mailcow.email</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.mail.managed</string>
			<key>PayloadUUID</key>
			<string>00294FBB-1016-413E-87B9-652D856D6875</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>PreventAppSheet</key>
			<false/>
			<key>PreventMove</key>
			<false/>
			<key>SMIMEEnabled</key>
			<false/>
		</dict>
		<dict>
			<key>CardDAVAccountDescription</key>
			<string>plein.email</string>
			<key>CardDAVHostName</key>
			<string></string>
			<key>CardDAVPort</key>
			<integer></integer>
			<key>CardDAVPrincipalURL</key>
			<string>/SOGo/dav/test@plein.email</string>
			<key>CardDAVUseSSL</key>
			<true/>
			<key>CardDAVUsername</key>
			<string>test@plein.email</string>
			<key>PayloadDescription</key>
			<string>Configures CardDAV accounts</string>
			<key>PayloadDisplayName</key>
			<string>CardDAV (plein.email)</string>
			<key>PayloadIdentifier</key>
			<string>email.plein.iphoneprofile.mailcow.carddav</string>
			<key>PayloadOrganization</key>
			<string></string>
			<key>PayloadType</key>
			<string>com.apple.carddav.account</string>
			<key>PayloadUUID</key>
			<string>0797EF2B-B1F1-4BC7-ABCD-4580862252B4</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>IMAP, CalDAV, CardDAV</string>
	<key>PayloadDisplayName</key>
	<string>plein.email Mailcow</string>
	<key>PayloadIdentifier</key>
	<string>email.plein.iphoneprofile.mailcow</string>
	<key>PayloadOrganization</key>
	<string></string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>5EE248C5-ACCB-42D8-9199-8F8ED08D5624</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>

**Comment by bplein** [comment]
[Mailcow-5.mobileconfig.zip](https://github.com/mailcow/mailcow-dockerized/files/2637152/Mailcow-5.mobileconfig.zip)
Here is a test account I just created.

**Comment by bplein** [comment]
Is there any sort of validator I can use to look at my mobileconfig to see where it’s broken?

**Comment by mkuron** [comment]
Your CalDAV and CardDAV host and port are empty. You must have overwritten $autodiscover_config in vars.local.inc.php and set these to invalid values. Please see vars.inc.php for the correct values.

**Comment by bplein** [comment]
My vars.local.inc.php is exactly the same as the example shown on https://mailcow.github.io/mailcow-dockerized-docs/u_e-autodiscover_config/

Am I not understanding the instructions correctly? Is that page or example file incomplete?

**Comment by andryyy** [comment]
I think the docs are indeed deprecated.

Try it like this, please:

```
$autodiscover_config = array(
  'caldav' => array(
    'server' => $mailcow_hostname,
    'port' => $https_port,
  ),
  'carddav' => array(
    'server' => $mailcow_hostname,
    'port' => $https_port,
  ),
);
```

**Comment by andryyy** [comment]
That's the default array btw. => https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/vars.inc.php#L35

**Comment by bplein** [comment]
Thank your for the help.

If you use default ports on everything (as I do), you don't need this file at all. Editing it per your instructions still didn't work, but removing it completely did.

Thanks again, it would have worked fine if I never read the docs (grin)
