### ISSUE TITLE
Incorrect CardDAV/CalDAV URLs in SOGo web interface behind reverse proxy

### ISSUE THREAD

**Issue by mkuron** [mailcow/mailcow-dockerized#207]
I have configured Mailcow behind a reverse HTTP proxy as [documented](https://andryyy.github.io/mailcow-dockerized/first_steps/#optional-reverse-proxy). Everything works fine, except for that the SOGo web app is not aware of the proxy when it generates absolute URLs referring to itself. The only place where this matters seems to be in the CardDAV/CalDAV URL shown when clicking on the three dots next to a address book/calendar and selecting _Links to this Address Book_/_Calendar_. These are shown starting in _http://mail.example.org:8080/_ instead of _https://mail.example.org/_.

The issue is in the [nginx configuration](https://github.com/andryyy/mailcow-dockerized/blob/9633a34f9fa35a9b071fa591b599ec334f072243/data/conf/nginx/site.conf#L268) where `x-webobjects-remote-host`, `x-webobjects-server-name`, `x-webobjects-server-url`, `x-webobjects-server-port` are set without considering the environment variables (`HTTPS_PORT`, `HTTPS_BIND`, etc.). While these lines in the nginx configuration can be modified manually, it would be greatly preferred if they could be either automatically determined or set from appropriately-named headers inserted by the reverse proxy.

**Comment by andryyy** [comment]
They are not set without considering the env vars. It was a mess getting it to load after login as it is.
If you want to change how SOGo handles reverse proxies, you should open a ticket at inverse. :-)

I will consider using a more flexible Nginx container (thinking about using LUA to generate the variables). It is difficult for Nginx to use env vars.

**Comment by mkuron** [comment]
Ok, thanks. A simpler solution would be to set the `x-webobjects-*` headers on the reverse proxy and have nginx copy them from the request if the request is coming from the reverse proxy. I'll try that and report back.

**Comment by mkuron** [comment]
Fix was reverted in e4310cafb3a329958642327700d82425e026dc2c and 72a21e48bd1e603e5902978f3173f0d88df3bd37 due to problems (see #212). Issue remains unsolved.

**Comment by andryyy** [comment]
Unresolved in HAProxy, I cannot reproduce problems with Apache2 and Nginx right now.

**Comment by mkuron** [comment]
Fixed in edc41b48d16f2d67ce2d942cb2dc3ae4fc4abbe6 and 2f0129539b20da4387b965f533afea54850bd9be.
