### ISSUE TITLE
Quarantine release original

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#2070]
**Is your feature request related to a problem? Please describe.**
Currently when you release mail from quarantine instead of getting the original email you get a email with a copy of it attached as .eml which is fine if you the mail client your using support opening eml files.

But Its a bit of a inconvenience if the client your using dose not support eml E.g. SoGO and even more of a inconvenience if the email contains images or attachment you want. 
 
**Describe the solution you'd like**
The enhancement to release quarantine I think would be helpful is instead of getting it as a eml attachment is to release it as it is with original content and not as a eml file.

I Know some user will prefer the way its currently released what you could do is make it configurable via vars.local.inc.php.

**Comment by andryyy** [comment]
That would indeed be better.

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/49580071-598d5500-f94e-11e8-885b-38fdec85d1fa.png)

Will upload soon.

PS: Default will change to "raw".

**Comment by K2rool** [comment]
Thanks @andryyy for adding the feature I requested so quickly, the way you implemented it using fsockopen to send the raw mail directly to Postfix is a effectively way to do it without messing up any of the original header of email don't think I would of ever thought of doing it that way.
