### ISSUE TITLE
SNAT Not Working for IPv4

### ISSUE THREAD

**Issue by JustAB0x** [mailcow/mailcow-dockerized#2071]
**Describe the bug**
SNAT does not work correctly with IPv4. It sets the postrouting for IPv6 successfully but not for IPv4, so the default ip of eth0 is used.

**System**
 - OS: Debian

**Additional context**
The IPv6 is directly configured in eth0 while the ipv4 is configured over eth0:1.
The WebUI is reachable by the ip i tried to configure with SNAT.

**Comment by andryyy** [comment]
Don’t know. Works very fine on our installations.
Need netfilter logs, iptables ruleset dump etc. as I cannot reproduce it.

**Comment by JustAB0x** [comment]
Netfilter log:

> netfilter-mailcow_1  | Clearing all bans
> netfilter-mailcow_1  | Initializing mailcow netfilter chain
> netfilter-mailcow_1  | Blacklisting host/network 46.167.245.205
> netfilter-mailcow_1  | Blacklisting host/network 195.128.120.25
> netfilter-mailcow_1  | Subscribing to Redis channel F2B_CHANNEL
> netfilter-mailcow_1  | Added POSTROUTING rule for source network fd4d:6169:6c63:6f77::/64 to SNAT > target 2a01:dead:beef::233
IP is censored

iptables 

> -P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-N MAILCOW
-A INPUT -j MAILCOW
-A FORWARD -j MAILCOW
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o br-cb794f44eb24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-cb794f44eb24 -j DOCKER
-A FORWARD -i br-cb794f44eb24 ! -o br-cb794f44eb24 -j ACCEPT
-A FORWARD -i br-cb794f44eb24 -o br-cb794f44eb24 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 12345 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 4190 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 995 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 993 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 143 -j ACCEPT
-A DOCKER -d 172.22.1.3/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 110 -j ACCEPT
-A DOCKER -d 172.22.1.8/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 587 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 465 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-cb794f44eb24 -o br-cb794f44eb24 -p tcp -m tcp --dport 25 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i br-cb794f44eb24 ! -o br-cb794f44eb24 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o br-cb794f44eb24 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A MAILCOW -s 195.128.120.25/32 -j REJECT --reject-with icmp-port-unreachable
-A MAILCOW -s 46.167.245.205/32 -j REJECT --reject-with icmp-port-unreachable

**Comment by andryyy** [comment]
Can you post your mailcow.conf? 

Minues DBPASS, DBROOT etc. :)
