### ISSUE TITLE
Nextcloud - memory limit

### ISSUE THREAD

**Issue by irrweg** [mailcow/mailcow-dockerized#2075]
Greetings,

while after installing a fresh mailcow, I decided to install nextcloud, while the script is running I get this error:

> The current PHP memory limit is below the recommended value of 512MB.

any Ideas how to fix that?

**Comment by andryyy** [comment]
Hi, it just shows that while installing via php-cli, it is set to 512M in the web worker.

**Comment by irrweg** [comment]
The Nextcloud interface also showes 511MB, which is a bit strange.
