### ISSUE TITLE
Wildcard aliases

### ISSUE THREAD

**Issue by levinuss** [mailcow/mailcow-dockerized#2077]
**Is your feature request related to a problem? Please describe.**
I try to minimize the spam I get by using a separate mail address for each account I create on the internet. For example, I use archlinux@mydomain.tld for my archlinux account[s] and netflix@mydomain.tld for Netflix. I then manually create an alias for each of those mail addresses to my main account. That's not very comfortable because I have to log in to the admin panel (password + 2FA) and then manually go to the aliases to create a new one every time I register a new account on the internet.

**Describe the solution you'd like**
It would be very cool to be able to use wildcards in the aliases. That way I could keep my Catchall pointed to the 'trash' account and could also do this scheme (creating an additional alias for every account) with multiple persons on one domain. For example, I could set up *.levinus@mydomain.tld as an alias and then use archlinux.levinus@mydomain.tld for archlinux and the mail would automatically be forwarded to my main account. The next user could set up his own *.otheruser@mydomain.tld and so on.

**Additional context**
I don't know if this is actually possible, just wanted to ask. A problem could be that the * seems to be allowed in normal mail addresses, so we cannot use the asterisk as a wildcard.

Greetings,
Levin

**Comment by hachre** [comment]
You can address `*@example.com` by simply using `@example.com` as the alias name. What you suggest for multiple users isn't easily possible, but you could set up subdomains with MX records (one for each user) and then use `@user1.example.com` and `@user2.example.com` and so on. So something like `archlinux@levinus.example.com` would work.

**Comment by mkuron** [comment]
You can already use levinus+archlinux@mydomain.tld and levinus+netflix@mydomain.tld if you set up levinus@mydomain.tld. Anything else cannot easily be done due to the way Dovecot manages aliases.

**Comment by levinuss** [comment]
I know Cachalls and also the plus signs. The problem with the plus signs is that they could possibly get removed in a spammer database because they know of that possibility. A solution with subdomains is an interesting idea, I will try that. If my idea is not possible sad but I will have to accept that :)

**Comment by strarsis** [comment]
A wildcard alias like postmaster@* and abuse@* would be nice so emails to these aliases for all domains are send to the primary postmaster email address.

**Comment by SnejPro** [comment]
> Anything else cannot easily be done due to the way Dovecot manages aliases.

@mkuron Why is Dovecot involved in this? Aren't aliases handled by postfix?
In my personal postfix installation (which i want to migrate to mailcow), i use *.user@example.org as wildcard alias with a mysql user backend.

Unfortunally this prevents me from migrating to mailcow.

**Comment by SnejPro** [comment]
> > Anything else cannot easily be done due to the way Dovecot manages aliases.
> 
> @mkuron Why is Dovecot involved in this? Aren't aliases handled by postfix? In my personal postfix installation (which i want to migrate to mailcow), i use *[.user@example.org](mailto:.user@example.org) as wildcard alias with a mysql user backend.
> 
> Unfortunally this prevents me from migrating to mailcow.

Correction:
I don't use wildcard. When an aliases starts with an dot - e.g. `.user@example.de` then all mails to `*.user@example.de` will be forwarded to `aliasdest@example.org`

Here is my alias.cf file for postfix. (It also supports domain aliases)
```
query = SELECT DISTINCT concat(dst_username, '@', dst_domain) AS destinations
		FROM
			( 
				SELECT
					mailboxes.username AS src_username,
					d1.domain_name AS src_domain,
					mailboxes.username AS dst_username,
					d2.domain_name AS dst_domain
				FROM
					domains_aliases da
				JOIN
					mailboxes ON da.dst_domain = mailboxes.domain
				JOIN
					domains d1 ON da.src_domain = d1.id
				JOIN
					domains d2 ON da.dst_domain = d2.id
					
				UNION
					
				SELECT
					ma.src_username AS src_username,
					d1.domain_name AS src_domain,
					ma.dst_username AS dst_username,
					d2.domain_name AS dst_domain
				FROM
					mailboxes_aliases ma
				JOIN
					domains d1 ON ma.src_domain = d1.id
				JOIN
					domains d2 ON ma.dst_domain = d2.id
					
				UNION
				
				SELECT
					fa.src_username AS src_username,
					d1.domain_name AS src_domain,
					fa.dst_username AS dst_username,
					d2.domain_name AS dst_domain
				FROM
					domains_aliases da2				
				JOIN
					mailboxes_aliases fa  ON fa.src_domain = da2.dst_domain
				JOIN
					domains d1 ON da2.src_domain = d1.id
				JOIN
					domains d2 ON fa.dst_domain = d2.id
			) AS aliases
		WHERE 
			(
				src_username = SUBSTR( '%u', INSTR('%u', ".") )
				OR
				src_username = '%u'
			)
		AND
			src_domain = '%d'
		AND NOT EXISTS
			(
				SELECT
					mailboxes.id
				FROM
					mailboxes
				LEFT JOIN
					domains ON mailboxes.domain = domains.id
				WHERE
					username = '%u'
				AND
					domains.domain_name = '%d'
			);
```

I took a look at `/opt/postfix/conf/sql/mysql_virtual_alias_maps.cf` and modified it so it would work with my alias scheme:
```
SELECT goto FROM alias
WHERE (
    address = SUBSTR( '%s', INSTR('%s', ".") )
    OR
    address = '%s'
)
AND (active='1' OR active='2');
```

Could this be implemented in Mailcow?

**Comment by SnejPro** [comment]
Since mailcow does not yet allow aliases that begin with a dot, such a change should not break any existing installations.
