### ISSUE TITLE
SOGO_CONTACT overrules spam filter, when the spammer faked my recipients address into the sender address

### ISSUE THREAD

**Issue by clemenstyp** [mailcow/mailcow-dockerized#2079]
Recently there was a change, that added all sogo contacts into the rspamd settings map. But this change can lead into a spamming problem: I just received a Mail, where the spammer faked my recipients address into the sender address. But this change just overruled all other Anti-Spam features.

Is there a way of disabling this feature?

![spam](https://user-images.githubusercontent.com/1587123/49718979-15ef5f80-fc5c-11e8-8e28-fe558eaedbd3.png)

_Originally posted by @clemenstyp in https://github.com/mailcow/mailcow-dockerized/issue_comments#issuecomment-445727597_

**Comment by andryyy** [comment]
We could remove the From header check.

**Comment by mkuron** [comment]
The envelope from check is actually a problem too, at least in combination with forwarding hosts: if you have the forwarding address in your address book, spam forwarded by the forwarding host will never be tagged. So we should add a composite symbol `WHITELISTED_FWD_HOST & ~SOGO_CONTACT` to remove the score.

> You can btw. easily fix this by setting your SPF to "-all". :)

Doesn't SPF only apply to the envelope sender?

**Comment by andryyy** [comment]
No, also header from. I have seen some of these mails. Depending on the customers SPF, it was either rejected/marked or put in the inbox. :(

The composite rule is a good idea!

**Comment by andryyy** [comment]
Something like this should do it...

```
SOGO_CONTACT_EXCLUDE_FWD_HOST {
  expression = "WHITELISTED_FWD_HOST & ~SOGO_CONTACT";
}
SOGO_CONTACT_SPOOFED {
  expression = "(R_SPF_PERMFAIL | R_SPF_SOFTFAIL) & ~SOGO_CONTACT";
}
```

**Comment by andryyy** [comment]
It is hopefully fixed. Please let me know if it isn't, I will re-open then.

**Comment by protree** [comment]
@andryyy Is seems not to be fixed: See here: https://github.com/mailcow/mailcow-dockerized/issues/1983#issuecomment-453812142

(Sorry for double posting, I saw this issue after I replied to the linked issue)
