### ISSUE TITLE
Share option for calendars is missing

### ISSUE THREAD

**Issue by olsberg** [mailcow/mailcow-dockerized#2088]
Hi,

Intro
I've read some great things about the Mailcow project and did some extensive research before making the decision to migrate. One of the key features I need is calendar sharing between users on the same domain, where users can set their permissions (read, read/write and so on) for each user they share the calendar with.

**Bug description**
According to SoGo documentation found on several online sites, the "Sharing..." option is available when clicking on the three dots to the right of the calendar you'd like to share. However, the only option related to sharing that I see is viewing calendar links.

**How to reproduce Reproduce**
1. Clean install Ubuntu Server 18.04.1 LTS or 16.04 LTS.
2. Install Mailcow Dockerized
3. Create a couple of users and login to SoGo.
4. Go to Calendar and click on the three dots to the right of the calendar.

**Expected behavior**
From what I have learned, the option "Sharing..." should be present in the pop-up meny when klicking on the three dots to the right of a calendar in SoGo.

Expected look: https://www.dropbox.com/s/wccqt4urmtdm917/support-en1920-4.png?dl=0

**System**
 - OS: macOS 10.14.2
 - Browser: Safari, Chrome

Thank you for taking the time to read the bug report.

**Comment by andryyy** [comment]
Hi,

Check this, it is there: 

![grafik](https://user-images.githubusercontent.com/2972950/49860362-fbeb8380-fdf9-11e8-8817-31c762f197fa.png)

Maybe the scrollbar is not shown in your browser? You need to scroll down, it is at the very bottom.

**Comment by olsberg** [comment]
Hi andrry,

This is embarrassing, you are correct. Thank you for your reply. Confirming the scrollbars were not visible and that the sharing option indeed is there.

**Comment by marcofl** [comment]
This really is an epic usability fail :) I spent hours finding out why I don't have the Sharing option... 🤦

**Comment by theGitMichel** [comment]
_Unfortunately if you use apples calendar app and caldav, the shared calendard abonements aren't shown. in the webbrowser, ios, android etc. is all okay. only apple's calendar app seems to have problems._ 

Solved this: 
Open calendar, go to the settings, select 'accounts' and the appropriate account, then click on "delegation". There you can select each account you were entitled to and check it if you want to show it in the calendar.

I am new to this "delegation-method", so I didn't thought about this. Maybe this intuition helps others, too. :-)
