### ISSUE TITLE
Relay denied

### ISSUE THREAD

**Issue by soncemvo** [mailcow/mailcow-dockerized#2095]
Fresh install on fresh digitalocean server. 
After trying to send some test mails to mailcow server i got: 550 Relay denied for <domain_that_added_to_mailcow>

I can freely send mails from this "denied" domain from mailcow webmail, but for some reason mailcow didnt want to recieve mails.
`Reporting-MTA: dns; mail-40133.***.**
X-Postfix-Queue-ID: 4D4991000747
X-Postfix-Sender: rfc822; ***@***.com
Arrival-Date: Fri, 14 Dec 2018 14:19:58 +0000 (UTC)

Final-Recipient: rfc822; admin@***
Original-Recipient: rfc822;admin@***
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx.***
Diagnostic-Code: smtp; 550 Relay denied for <***>`

**Comment by mkuron** [comment]
Please check the postfix logs using `docker-compose logs postfix-mailcow`, perhaps they provide some additional information.
