### ISSUE TITLE
roundcube password change error

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#2097]
Hello, I follow all the documentation about integration of roundcube and password change. But when I try to change a password in roundcube I have this error : "Impossible to save password"

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
Go to rouncbue ans change the password.

**Logs**
I don't see anything in docker-compose logs. Perhaps another logs or debug ?

**System**
 - OS: Debian 9
 - Browser: firefox and brave

Thanks

**Comment by andryyy** [comment]
Hi,

You will need to enable debugging in Roundcube to find the error.

**Comment by guidtz** [comment]
Ok I have this : 

PHP Error in /web/rc/program/lib/Roundcube/rcube_plugin.php (157): Failed to load config from /web/rc/plugins/password/config.inc.php

**Comment by andryyy** [comment]
And the content of that file? :)

**Comment by guidtz** [comment]
Same as the documentation : https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

$config['password_driver'] = 'sql';
$config['password_algorithm'] = 'ssha256';
$config['password_algorithm_prefix'] = '{SSHA256}';
$config['password_query'] = "UPDATE mailbox SET password = %P WHERE username = %u";

**Comment by andryyy** [comment]
The syntax can still be wrong. Please upload the whole file.

**Comment by guidtz** [comment]
It's all the content of file web/rc/plugins/password/config.inc.php wich other file do you want ?

**Comment by andryyy** [comment]
Then it may be missing php tags.

**Comment by guidtz** [comment]
oulalalalala may be I'm a crazy cow with this stupid mistake :-(

**Comment by andryyy** [comment]
👍 
We are all just crazy cows, penguins and cats.

**Comment by guidtz** [comment]
Yes ! So you done a very cool job with mailcow. Thanks for you're help
