### ISSUE TITLE
Admin Panel Error 502

### ISSUE THREAD

**Issue by Happyfeet01** [mailcow/mailcow-dockerized#2098]
Hello,

today i run an Update with the Script.
After the update, i cant use the Admin Panel anymore. Error 502. The Webmail works under
https://mail.domain.tld/SoGo

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Update with the Updater Script
2. after all containers are restarted i get an 502 Error at the Admin Panel
3. the Mailclient under Sogo works.

**Screenshots**
Screenshots from the Console
![docker-container](https://user-images.githubusercontent.com/3295104/50046992-7a238080-00ad-11e9-9650-ca08cea020cc.PNG)

![mailcow-container](https://user-images.githubusercontent.com/3295104/50046994-7d1e7100-00ad-11e9-8d7f-83bc7be79047.PNG)

**Logs**
Mailcow Nginx Log:

``
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [15/Dec/2018:20:58:10 +0100] "HEAD /settings.php HTTP/1.1" 502 0 "-" "-"
nginx-mailcow_1      | 2018/12/15 21:00:05 [error] 18#18: *63 connect() failed (111: Connection refused) while connecting to upstream, client: fd4d:6169:6c63:6f77::1, server: _, request: "HEAD /forwardinghosts.php HTTP/1.1", upstream: "fastcgi://[fd4d:6169:6c63:6f77::c]:9001", host: "nginx"
nginx-mailcow_1      | 2018/12/15 21:00:05 [error] 18#18: *63 connect() failed (111: Connection refused) while connecting to upstream, client: fd4d:6169:6c63:6f77::1, server: _, request: "HEAD /forwardinghosts.php HTTP/1.1", upstream: "fastcgi://172.22.1.9:9001", host: "nginx"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [15/Dec/2018:21:00:05 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 502 0 "-" "-"
nginx-mailcow_1      | 2018/12/15 21:08:45 [error] 18#18: *67 connect() failed (113: Host is unreachable) while connecting to upstream, client: fd4d:6169:6c63:6f77::1, server: _, request: "HEAD /settings.php HTTP/1.1", upstream: "fastcgi://[fd4d:6169:6c63:6f77::c]:9001", host: "nginx"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [15/Dec/2018:21:08:56 +0100] "HEAD /settings.php HTTP/1.1" 499 0 "-" "-"
``

Mailcow PHP-FTPM Log:
``
php-fpm-mailcow_1    | Uptime: 30  Threads: 12  Questions: 9  Slow queries: 0  Opens: 21  Flush tables: 1  Open tables: 15  Queries per second avg: 0.300
php-fpm-mailcow_1    | MySQL applied an upgrade, restarting PHP-FPM...
php-fpm-mailcow_1    | Uptime: 56  Threads: 9  Questions: 7  Slow queries: 0  Opens: 19  Flush tables: 1  Open tables: 13  Queries per second avg: 0.125
php-fpm-mailcow_1    | MySQL applied an upgrade, restarting PHP-FPM...
php-fpm-mailcow_1    | Uptime: 63  Threads: 9  Questions: 9  Slow queries: 0  Opens: 20  Flush tables: 1  Open tables: 14  Queries per second avg: 0.142
php-fpm-mailcow_1    | MySQL applied an upgrade, restarting PHP-FPM...
php-fpm-mailcow_1    | Uptime: 62  Threads: 9  Questions: 9  Slow queries: 0  Opens: 20  Flush tables: 1  Open tables: 14  Queries per second avg: 0.145
php-fpm-mailcow_1    | MySQL applied an upgrade, restarting PHP-FPM...
``

Mysql Log

``
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] mysqld (mysqld 10.2.19-MariaDB-1:10.2.19+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql-mailcow_1      | 2018-12-15 21:09:06 140547106760640 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2018-12-15 21:09:06 140546363418368 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2018-12-15 21:09:07 140547106760640 [Note] InnoDB: Highest supported file format is Barracuda.
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] InnoDB: 5.7.24 started; log sequence number 7444189
mysql-mailcow_1      | 2018-12-15 21:09:09 140546194519808 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] Server socket created on IP: '::'.
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Warning] 'proxies_priv' entry '@% root@300eeab963fd' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2018-12-15 21:09:09 140546903729920 [Note] Event Scheduler: scheduler thread started with id 6
mysql-mailcow_1      | 2018-12-15 21:09:09 140546903422720 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:09:09 140546903422720 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:09:09 140547106760640 [Note] mysqld: ready for connections.
mysql-mailcow_1      | Version: '10.2.19-MariaDB-1:10.2.19+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mysql-mailcow_1      | 2018-12-15 21:09:11 140546194519808 [Note] InnoDB: Buffer pool(s) load completed at 181215 21:09:11
mysql-mailcow_1      | 2018-12-15 21:10:01 140546899822336 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:01 140546899822336 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:02 140546899822336 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:02 140546899822336 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:02 140546899515136 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:02 140546899515136 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] mysqld (initiated by: unknown): Normal shutdown
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] Event Scheduler: Killing the scheduler thread, thread id 6
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] Event Scheduler: Waiting for the scheduler thread to reply
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] Event Scheduler: Stopped
mysql-mailcow_1      | 2018-12-15 21:10:09 140546310944512 [Note] InnoDB: FTS optimize thread exiting.
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] Event Scheduler: Purging the queue. 0 events
mysql-mailcow_1      | 2018-12-15 21:10:09 140546302551808 [Note] InnoDB: Starting shutdown...
mysql-mailcow_1      | 2018-12-15 21:10:09 140546194519808 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2018-12-15 21:10:09 140546194519808 [Note] InnoDB: Buffer pool(s) dump completed at 181215 21:10:09
mysql-mailcow_1      | 2018-12-15 21:10:10 140546302551808 [Note] InnoDB: Shutdown completed; log sequence number 7444217
mysql-mailcow_1      | 2018-12-15 21:10:10 140546302551808 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql-mailcow_1      | 2018-12-15 21:10:10 140546302551808 [Note] mysqld: Shutdown complete
``

**System**
 - OS: Ubuntu 18.04 Server
 - Browser: Chrome

**Comment by andryyy** [comment]
Hi, can you please re-run update.sh?

**Comment by Happyfeet01** [comment]
thanks it works
