### ISSUE TITLE
Scanned emails from forward gateway while disabled in settings

### ISSUE THREAD

**Issue by ro78** [mailcow/mailcow-dockerized#2099]
Hello,

I run mailcow on an up to date Debian x64 system.

I use a SMTP gateway to filter spam of my incoming emails. All the hosts that can forward incoming emails to mailcow are registered in /admin#fwdhosts with spam filter disabled.

It works for most of the emails, but time to time, emails are seen from coming from 172.22.1.1 (docker internal IP) instead of my remote gateway, like here:

https://www.dropbox.com/s/3mdva5p4irpo5cd/2018-12-17_175033.png?dl=0

As a result, rspamd still scans & act on these emails.

Full headers of a sample scanned while coming from a forward host registered in mailcow admin with spam filtering disabled: https://pastebin.com/Gyj5Q589

Any idea, how to prevent this? 

Few seconds later, another email, and here the real public IP of the forward host is well detected: https://www.dropbox.com/s/slewfbqxc7lt1aa/2018-12-17_175339.png?dl=0

Thank you!

Best regards,
Romain

**Comment by mkuron** [comment]
Is the SMTP gateway running on the same machine (either in another Docker container or natively)?

Do you have IPv6 enabled on the Mailcow machine and manual `ip6tables` rules? These moght interfere with Mailcow's rules and cause the traffic to go through Docker's userland-proxy instead.

**Comment by ro78** [comment]
SMTP gateway is running on other hosts.

I have IPv6 on the host but I don't use it in mailcow (enable_ipv6: false in networks) because when mailcow starts, it kills the IPv6 connectivity on the host and I need to restart the OS to get it back (shutting down mailcow doesn't fix the issue).

In case it can change something, I use IPv4 "SNAT_TO_SOURCE".

**Comment by mkuron** [comment]
IPv6 is probably the culprit then. I assume your host has an A and an AAAA DNS record and the SMTP gateway connects to it via its hostname? Then it'll end up using v4 and v6 each about half the time.

If you disable IPv6 in docker-compose.yml, all incoming IPv6 traffic is proxied to IPv4 by Docker. Don't ever set `enable_ipv6: false` if your host has an IPv6 address.

**Comment by ro78** [comment]
I'll remove the AAAA in DNS (my gateway uses the hostname to connect), and let you know.
I would like to leave IPv6 enabled in the Dockerfile, but I can't, as it crashs the IPv6 on the host.

**Comment by ro78** [comment]
I confirm that it's OK without AAAA record on the host used by gateway to forward emails to mailcow.
Next step would be to find why enabling IPv6 breaks the IPv6 on the host until reboot, but that's another story :)
