### ISSUE TITLE
fuzzy_learn_error: No content to generate fuzzy for flag 11

### ISSUE THREAD

**Issue by patschi** [mailcow/mailcow-dockerized#2105]
**Describe the bug**
Error when learning quarantined mails as spam:
```
fuzzy_learn_error: No content to generate fuzzy for flag 11
```
(There was some text to scan in at least one mail, didn't checked others)

**How to reproduce Reproduce**
1. Go to "Quarantine"
2. Check multiple entries (in my test case 8 mails)
3. Click "Learn as spam and delete"

**Expected behavior**
No error.

**Additional context**
This may have worked before the last update earlier today - the last time it was working fine was around December 12, 2018. I'm not sure if that was any environment-specific or temporary error - is anyone able to reproduce that with latest available update & Docker images? (There might be a chance it's just a false-alarm and just problematic with mails I've learned this time.)

**Comment by andryyy** [comment]
This is not a bug. Just not enough content.
