### ISSUE TITLE
[question] Adding domain name same as mailcow domain

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2106]
I have installed mailcow using the domain mail.test.domain.tld. 

now I want to add that same domain on the add domain page in the mailcow UI and im getting an error. 
Is this not possible? 

I have configured A record domain mail.test.domain.tld to point to my server ip and MX record domain mail.test.domain.tld pointing to the same server ip. 

Im very new to this. hope someone can help. would really appreciate it.

**Comment by mkuron** [comment]
You can remove the check from the code and it will work. Details are in some ticket I couldn't find. The check mainly exists to discourage people from confusing their host name and domain -- barely anyone uses the domain as the mail server's host name. But there is no technical reason not to.

**Comment by andryyy** [comment]
There was a time we had the hostname in mydestination, I think. Not sure, but there could be something else I am missing now.

**Comment by ghost** [comment]
thanks for getting back to me @mkuron however, I couldn't find the code. could you tell me in which file the code is? that would be very helpful. i couldn't find the ticket with the details either.. please help. thanks!

**Comment by ghost** [comment]
never mind. found the code and removed it. its working now. much thanks!

**Comment by Coronon** [comment]
> never mind. found the code and removed it. its working now. much thanks!

This is not very useful to people that find this while they have the exact same problem... Does anyone know where to find these mysterious lines?

Edit: It seems the following `if` is responsible [in _functions.mailbox.inc.php_](https://github.com/mailcow/mailcow-dockerized/blob/e2b4b6f6bcb9b8f6d6a4d9b401896ad1c83de288/data/web/inc/functions.mailbox.inc.php#L540):
```php
if ($domain == getenv('MAILCOW_HOSTNAME')) {
  $_SESSION['return'][] = array(
    'type' => 'danger',
    'log' => array(__FUNCTION__, $_action, $_type, $_data_log, $_attr),
    'msg' => 'domain_cannot_match_hostname'
  );
  return false;
}
```

Maybe this should become a warning, not an error one needs to "fix" by changing the code?

**Comment by ciroiriarte** [comment]
Hello, can this be moved to an optional check?. I don't want to monkey patch my installation.
In my case, I use a mail-specific domain (mydomain.email), so it doesn't handle anything else appart from email service.

**Comment by Qwertylex** [comment]
I also feel it should be an optional check.
