### ISSUE TITLE
spam processing for catchall addresses and email aliases

### ISSUE THREAD

**Issue by burntout** [mailcow/mailcow-dockerized#2107]
It's not clear from the documentation or from the  user or domain management interface how  user configurable spam levels are applied to wildcard addresses or  administrator defined aliases ( *@example.org -> user@example.org, or alias@example.org -> user@example.org )

Does the spam settings  configurable by the user in their management interface affect the mail received by the catchall or other aliases.   I have a user who has a catchall  for their domain, and configured their a/c to never mark any mail as spam, however it appears that email to catchall address is getting marked as spam still.

Thanks in advance

**Comment by burntout** [comment]
I've been pointed at this screenshot
![wptsqd4](https://user-images.githubusercontent.com/7761234/50279610-1a78fc80-0442-11e9-8d54-62be90d3c00b.png)
I guess that a "Direct Alias" is an alias that only goes to a single mailbox, and a "Shared Alias" is an alias that goes to multiple mailboxes.  Is this correct ? 
Also how do catchall's fit in this scheme ? 

Thanks

**Comment by andryyy** [comment]
It is comparable with a shared alias.
