### ISSUE TITLE
Happy holidays and thank you so much!

### ISSUE THREAD

**Issue by jaltek** [mailcow/mailcow-dockerized#2109]
Dear @andryyy,

on behalf of all mailcow users I just want to say **thank you**.

Thank you (and also to all it's contributors) so much for your hard work for mailcow which has become the best open source mail solution for me. Keep up the good work!

Happy holidays for you and your family and a happy new year 2019.

**Comment by andryyy** [comment]
Thank you very much!

**Comment by ntimo** [comment]
Dear @andryyy,
I also wanted to wish you happy holidays and a good start into the new year 🙌

**Comment by MAGICCC** [comment]
Thanks :)
I will close the issue, since it's not a real one 
You can always join us in #mailcow @ freenode IRC
