### ISSUE TITLE
Sogo Shared Calendar & Active Sync Android

### ISSUE THREAD

**Issue by Icki153** [mailcow/mailcow-dockerized#2110]
Hello,

i have problems with Shared Calendar and Active Sync on Android. Personal Calendar are working fine. But if i share a calendar to other User the calendar is initial synced but no notifications on events. Also if the other User create an event its never uploaded to server. If the other User use Exchange or Sogo directly then the events created. Any Idea?

Best regards & Merry Christmas

**Comment by andryyy** [comment]
Hi,

Please open an issue with SOGo for SOGo-related questions. :)

**Comment by Icki153** [comment]
Hello,

sorry for late answer. Ok I make an issue report in Sogo Bug Tracker. I thinked some other User have always a problem so he can help me.

So issue is closed :)

**Comment by andryyy** [comment]
You probably want to play with

    //SOGoMaximumSyncWindowSize = 99;
    SOGoMaximumSyncResponseSize = 512;

in `data/conf/sogo/sogo.conf`. You can try to remove both for example. And restart SOGo after every change.
