### ISSUE TITLE
Git worker-controller-password.inc changed

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#2116]
**Describe the bug**
The file `data/conf/rspamd/override.d/worker-controller-password.inc` is modified when setting the rspamd passwords which breaks Ansibles git module. (local medications in repo)

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Change password in Mailcow WebUi
2. Do a `git status`
3. See that the file has been modified and that it is checked in

**Logs**
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   data/conf/rspamd/override.d/worker-controller-password.inc

no changes added to commit (use "git add" and/or "git commit -a")
```

**Solution**
The file should not be in the Git repo and should be created by the rspamd container when it starts this way git would see the file, but it would be untracked. Or we could add it to the .gitignore?

**Comment by andryyy** [comment]
There were some issues I run into. I will fix it in the future, don't know when exactly though... :/
