### ISSUE TITLE
Can't access sogo

### ISSUE THREAD

**Issue by benisoliver** [mailcow/mailcow-dockerized#2117]
Hello,

I have been using mailcow for about a year now, but I have an issue since yesterday. I can't open sogo in the browser (502 error, and I can't connect to 172.22.1.248:20000 on the server). The admin page and rspamd config work fine. Sogo is running according to the admin page, I tried the restart the whole server, restart sogo, run the update script but still nothing. In the docker-compose logs there are a lot of 
`sogo-mailcow_1       | Will retry to setup SOGo password update trigger in 3s`
`sogo-mailcow_1       | ERROR 1359 (HY000) at line 2: Trigger already exists`
line pairs. What should I do?

**Comment by andryyy** [comment]
Hi, check your SQL logs, please.

And: What's the output of `source mailcow.conf ; docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -B -e "SELECT TRIGGER_NAME FROM INFORMATION_SCHEMA.TRIGGERS"`?

Edit: Added source command.

**Comment by benisoliver** [comment]
[mysql.log](https://github.com/mailcow/mailcow-dockerized/files/2705153/mysql.log)
I don't really know what should I look for, but I attached the mysql docker compose log.

There isn't any output for this command (only this: `WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.` but I get this for every docker-compose command).

**Comment by andryyy** [comment]
Your sql is broken. I have seen this happening when you shut down SQL dirty. Can be fixed though. I think there is a file in the SQL datadir which needs to be deleted. You can mail me access or write me on Telegram via @diekuh - I will fix it for you.

**Comment by minimins** [comment]
I am also having this issue, can you elaborate on the procedure to fix?

**Comment by andryyy** [comment]
Try:

```
docker-compose down
rm /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/mailcow/sogo_update_password.TRN
docker-compose up -d
```

**Comment by minimins** [comment]
yes that is perfect thank you!

**Comment by andryyy** [comment]
Cool :) You are welcome!

**Comment by ghost** [comment]
> rm /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/mailcow/sogo_update_password.TRN
> docker-compose up -d

THANK YOU, IT FIXED MY PROBLEM!

**Comment by xLixon** [comment]
> rm /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/mailcow/sogo_update_password.TRN

Worked for me thanks !
