### ISSUE TITLE
Sogo logo not copied (fix included)

### ISSUE THREAD

**Issue by nicolaspernoud** [mailcow/mailcow-dockerized#2118]
There is an error in "/Dockerfiles/sogo/bootstrap-sogo.sh" : `cp /etc/sogo/sogo_full.svg` should be `cp /etc/sogo/sogo-full.svg` (hyphen in place of underline)

Thanks,

**Comment by andryyy** [comment]
Yes, I’ve seen this and fixed it in an untested image. Need a little bit more time.

**Comment by nicolaspernoud** [comment]
Thanks. I updated and everything works well now.
