### ISSUE TITLE
Sending/Receiving E-Mails does not work (like to /dev/null)

### ISSUE THREAD

**Issue by Krysztokowski** [mailcow/mailcow-dockerized#2119]
Hello,

first I searched in old issues but don't found any helping information.
I prepared my DNS and installed mailcow-dockerized on a clean Ubuntu 18.04 on my VPS, without a problem.

After the installation and adding a Domain/Mailbox and restarting SOGo I logged in and tried to send myself an Email to @gmail.com and @web.de. 

The modal window shows something like "Send successfully" and I received nothing on my gmail- and webadress.

If I try to send a Mail from my existing Mails(@gmail.com and @web.de) to my mailboxadress@mydomain.tld, it also looks working(but does not). If this wouldn't work, I would expect some Mail like "Mail delivery failed: returning message to sender".

Sounds like a DNS-Problem, but I have no clue what it could be:

A | @ | 82.165.112.237 | - |  
MX | @ | mail.mydomain.de | - |  
SPF (TXT) | @ | "v=spf1 mx ~all" | - |  
CNAME | autoconfig | mail.mydomain.de | - |  
CNAME | autodiscover | mail.mydomain.de | - |  
CNAME | imap | mail.mydomain.de | - |  
A | mail | 82.165.112.237 | - |  
CNAME | pop3 | mail.mydomain.de | - |  

Any idea? I spend hours in debugging.

Greets and merry Xmas

**Comment by hachre** [comment]
Why did you close this? Is it solved? How did you solve it?

**Comment by lazyfrosch** [comment]
If DNS settings are wrong during sending, the mail is usually deferred in the mail queue, until errors can be fixed.

A "return to sender" will happen if this error consists or it is a permanent/critical failure.

Check the queue manager of Mailcow.

**Comment by Krysztokowski** [comment]
@hachre Ehm, it's nearly solved. The problem: the vps firewall configuration, every port (except for 80/443) was blocked.. I only checked wheather the needed ports are in use for other programs..

I added the required ports to the firewall and I receive the Emails from @web.de and @gmail.com.

But I can not "send" Emails from Mailcow - I can send them without a error message, but they do not arrive.

@lazyfrosch I checked the queue manager of Mailcow with `docker-compose exec postfix-mailcow postqueue -p`
It shows -> `(address resolver failure)`. 

I'll debug further keep you up2date.

Any other ideas? (:

**Comment by lazyfrosch** [comment]
Depending on the Firewall it might block Docker communication, which is pretty bad...

First turn the firewall off, restart system, `docker-compose down`, `docker-compose up`.

Docker configures various firewall rules for the containers. If this works, find a better solution for the Firewall..

**Comment by andryyy** [comment]
You should use the DOCKER_USER chain for own and persistent rules. :)

Btw. thanks for the Icinga2 Telegram notifications script. :-D

**Comment by ntimo** [comment]
@andryyy could you share this Icinga2 Telegram notifications script with us :) Would be awesome.

**Comment by lazyfrosch** [comment]
@ntimo Check my GitHub :wink:
