### ISSUE TITLE
Redis ist not starting after update

### ISSUE THREAD

**Issue by DevQuandt** [mailcow/mailcow-dockerized#2120]
Hello,

after running the update.sh the redis container could not be started:

redis-mailcow_1      | 1:C 23 Dec 15:21:50.808 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-mailcow_1      | 1:C 23 Dec 15:21:50.808 # Redis version=4.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis-mailcow_1      | 1:C 23 Dec 15:21:50.808 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 * Running mode=standalone, port=6379.
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 # Server initialized
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis-mailcow_1      | 1:M 23 Dec 15:21:50.809 # Can't handle RDB format version 9
redis-mailcow_1      | 1:M 23 Dec 15:21:50.810 # Fatal error loading the DB: Invalid argument. Exiting.

**Comment by andryyy** [comment]
Use the Redis 5 image then. 

Old mailcows did not specify the Redis version. So you were using Redis 5 (latest) while the newer mailcow pins Redis to latest of v4.

When you upgraded mailcow, you downgraded Redis. 

Redis 5 should not be a problem any way.

**Comment by DevQuandt** [comment]
worked, thank you

**Comment by andryyy** [comment]
Maybe we can upgrade to 5.

Need to talk to Vsevolod to make sure nothing breaks.

**Comment by andryyy** [comment]
He said it is no problem, so we can upgrade to 5 very soon.
