### ISSUE TITLE
Redirect all matching domain to roundcube

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#2121]
Hello,
 I search how to redirect all subdomain https://webmail.domain.com to https://mail.domain.com/rc ? 
I want to make it generic for all domains managed on mailcow. How can I had this in nginx ?

Regards

**Comment by andryyy** [comment]
Hi,
add a file `data/conf/nginx/webmail.conf` with the following (untested) content:
```

server {
  include /etc/nginx/mime.types;
  charset utf-8;
  override_charset on;

  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;

  add_header Strict-Transport-Security "max-age=15768000;";
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Permitted-Cross-Domain-Policies none;
  add_header Referrer-Policy strict-origin;

  index index.php index.html;

  client_max_body_size 0;

  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;

  server_name webmail.*;

  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  root /web;
  return 301 https://mx.domain.com/rc/;
}
```

**Comment by guidtz** [comment]
Ok It seems to works with first test.

But how can I make this more flexible : return 301 https://mx.domain.com/rc/;

For example with domain domain1.com I create mail.domain1.com and I wants to redirect webmail.domain1.com to mail.domain1.com/rc

For domain2 : webmail.domain2.com to mail.domain2.com/rc

etc ...

**Comment by andryyy** [comment]
You need to check the Nginx docs. You can do that with rewrites.
