### ISSUE TITLE
Mailcow UI - Filter enhancements

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2122]
Hello everybody!
first of all, I wish you all a Merry Christmas.

I've have found two things to improve.

1. I have a domain like example.com and a subdomain test.example.com.
With both domains I would like to receive and send mails. If I select "test.example.com" in the dropdown filter under "Mail Setup" -> "Mailboxes." The UI displays only all mailboxes under test.example.com. If I select "example.com" all mailboxes with example.com and test.example.com would display. Is it possible to fix that?

2. If I use a filter (whether dropdown- or the textfilter) and click reload or go into the edit window and back to the overview the filter is reseted. It would be wonderful if the filter is persistent through this.

**Comment by beckzg** [comment]
Hi everybody,

  as vain90 mentioned the persistent filter would be very cool, it's annoying to set up the filter every single time when I click somewhere/anywhere.

  Keep up the good work!

**Comment by andryyy** [comment]
I fixed it with the upcoming commits.

**Comment by beckzg** [comment]
Thank's a lot andryyy, you're great!

**Comment by Adorfer** [comment]
Better support for "subdomain additional and separated from 2nd-level domain" would be great. 
(i have cases where single users got a subdomain inside the regular domain where many users are and they want to create sub-mailboxes etc, so they receive local admin rights for those subdomains. For them it's o.k, but for the "general admin" becomes a bit messy)

**Comment by vain90** [comment]
If you log into a mailbox as an admin or domain admin and change the tab (spam filter or sync jobs), then log out, then you end up in the tab "domains".

If you only log in and don't change the tab and log out, then you will be back in the tab "mailboxes" as desired.

I hope that was understandable.
