### ISSUE TITLE
Per-Alias Mapping to folders

### ISSUE THREAD

**Issue by itsbhanusharma** [mailcow/mailcow-dockerized#2123]
**Is your feature request related to a problem? Please describe.**
I am very fond of using aliases like fb@mydomain.com / twitter@mydomain.com for social media registration, Currently, I've set up catch-all alias for my domain which forwards mails to my existing account mails@mydomain.com. It'd be really nice to have an option to create aliases which automatically map to a folder e.g. all of the mails received on behalf of foo@mydomain.com shall go into the inbox folder foo for the account mails@mydomain.com. This kinda works while using subaddressing (e.g. mails+fb@mydomain.com) but not all websites accept such subaddressing emails by default. 

**Describe the solution you'd like**
A Possibility to define a folder-name while creating an alias or a global option to create a new folder based on the recipient address will be much appreciated. If that's already possible, I could not find it's documentation. 

**Additional context**
N/A

**Comment by andryyy** [comment]
You need to setup your own sieve filter for it. 
That’s pretty much it.

**Comment by itsbhanusharma** [comment]
Oh! Thanks!
I'd give it a try!
