### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by cryptolukas** [mailcow/mailcow-dockerized#2124]
**Notice (you can delete this paragraph)**
Please understand that we use GitHub as **bug tracker and for feature requests only**.
For general (community) support and other discussion, you are welcome to visit us @ Freenode, #mailcow
Answering may take from a few seconds to hours, please be patient. :-)
Immediate commercial support is available via info@servercow.de

**Describe the bug**
When you try to pull the images the first time you got this error.
I deleted the unsupported config options

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
```
1. root@host# /opt/mailcow-dockerized# docker-compose pull
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.dockerapi-mailcow: 'oom_kill_disable'
Unsupported config option for services.watchdog-mailcow: 'oom_kill_disable'
```

**Expected behavior**
No error ^^

**Screenshots**
-

**Logs**
-
**System**
 - OS: Ubuntu 18.04
 - Docker: docker --version
Docker version 18.09.0, build 4d60db4
 - Docker-Compose: docker-compose --version
docker-compose version 1.17.1, build unknown

**Additional context**

**Comment by andryyy** [comment]
Hi, update docker compose. :-) Your version is over a year old.
