### ISSUE TITLE
Mailcow API Documentation

### ISSUE THREAD

**Issue by zkryakgul** [mailcow/mailcow-dockerized#2127]
Hello, a few time ago when i check the web site and latest commit's i saw you write an mailcow api for adding or delete mailbox etc. I cant found anything about documentation. Do you have any point on roadmap for publish an documentation for this api?

**Comment by andryyy** [comment]
I close it as “not an issue“. 

No, there is no road map for this. I think next year January.

**Comment by fusioncore15** [comment]
Hello André,

Firstly, I want to thank you for all your job on mailcow, it's a wonderful tool.
I want to help you if it's possible, if you have some info about the API (url, schema, ...) I can write the doc for you.
Feel free to contact me in private if you want

Regards

**Comment by andryyy** [comment]
Hi, that would be nice. You can find a lot of info on Git. :) That will probably get you started. The api logs its request and data to the UI.

**Comment by fusioncore15** [comment]
Reverse enginering, it's not really helpful :-(

**Comment by andryyy** [comment]
There are even full commands for curl with examples and explanations. :)

**Comment by fusioncore15** [comment]
Did you have the full json somewhere ?

**Comment by feldsam** [comment]
Hi all, I du pull reuest #2547 with little changes, which allows us use json api with json in request body - more standard way in rest apis. Also there is draft of documentation in apiary https://feldhostmailhosting.docs.apiary.io/
