### ISSUE TITLE
Configuration Reverse DNS in setup with reverse proxy?

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#2128]
**Description**
Following your advise [here](https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/#reverse-dns-of-your-ip) is difficult if the mailserver is running behind a reverse proxy.

In my case I have one public IP and to serve multiple web services and therefore I configured a reverse proxy. But this means that I cannot configure a PTR record of my IP to match the FQDN of my mailcow host.

What do you suggest for this setup?
Should I change the hostname of the mailserver?

**Comment by mkuron** [comment]
The host name of a mail server needs to match its IP address's PTR record. There is no way around that. You can have multiple PTR records for a single IP address though, you can change your Mailcow's host name to match the PTR record, or you could change your PTR record (if you can only have one) to your Mailcow's host name. Mail servers are pretty much the only thing that relies on PTR records, so you might as well do the latter.
