### ISSUE TITLE
postfix network is unreachable

### ISSUE THREAD

**Issue by maxklock** [mailcow/mailcow-dockerized#2130]
**Describe the bug**
I've set up mailcow a few days ago. I can receive Mails, and using Exchange for Contacts and calendar. But when I try to send mails, the postfix gives me "Network is unreachable" or "Connection timed out" in the logs and the mail stays in the queue for 24h.
 Running telnet from my pc to my server on port 25 is successfull. I tried a ping from the postfix-container and it can resolve the domains and has no package lost.

**Logs**
postfix/smtp[369]: 69FDD3F0FD: to=<XXX>, relay=none, delay=1420, delays=1356/0.39/64/0, dsn=4.4.1, status=deferred (connect to XXX[<IPv6>]:25: Network is unreachable)
postfix/smtp[371]: 69FDD3F0FD: to=<YYY>, relay=none, delay=1422, delays=1356/0.49/65/0, dsn=4.4.1, status=deferred (connect to YYY[<IPv4>]:25: Connection timed out)

**System**
Server: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1036-azure x86_64)
Docker Client: 18.09.0
Docker Engine: 18.09.0
Mail-Clients: SOGos, Microsoft Outlook, Windows Mail

**Comment by andryyy** [comment]
IPv6?

**Comment by andryyy** [comment]
Outbound 25/tcp may be blocked. You will need to run telnet whatever.server.com 25 on your server, not on your client. Which ISP?

**Comment by K2rool** [comment]
Am guessing the ISP is Azure based on Kernel version a quote from Msdn Microsoft blog https://blogs...com/mast/2017/11/15/enhanced-azure-security-for-sending-emails-november-2017-update/


> For Pay-As-You-Go or Microsoft Partner Network subscriptions created after November 15, 2017, there will be technical restrictions blocking e-mail sent directly from VMs in these subscriptions.  Customers that need the ability to send e-mail from Azure VMs directly to external e-mail providers (not using an authenticated SMTP relay) can make a request to remove the restriction.  Requests will be reviewed and approved at Microsoft’s discretion and will be only granted after additional anti-fraud checks are performed.

**Comment by maxklock** [comment]
@K2rool thanks for the [link](https://blogs.msdn.microsoft.com/mast/2017/11/15/enhanced-azure-security-for-sending-emails-november-2017-update/).
My old mail Server in azure was able to send mails, but now, I have a newer one.
