### ISSUE TITLE
CRLF bug in autodiscover.theendlessweb.com

### ISSUE THREAD

**Issue by darknull** [mailcow/mailcow-dockerized#2131]
**Describe the bug**
CRLF in autodiscover.theendlessweb.com.

In a CRLF injection vulnerability attack, the attacker inserts carriage return, linefeed both of the characters into user input to trick the server, web application or the user into thinking that an object is terminated and another one has started.

**How to reproduce Reproduce**
Open the below link in the browser and capture the request using the proxy to verify that new header is created in the response.

```
http://autodiscover.theendlessweb.com/%0aSet-Cookie:crlf=injection
```

**Expected behavior**
No header should be set in the response. For more details please check:- https://www.netsparker.com/blog/web-security/crlf-http-header/

**Screenshots**
Attached
![crlf](https://user-images.githubusercontent.com/27420058/50484143-04a4a200-0a15-11e9-9d4f-0e00af7f7ddc.png)

**Comment by chriscroome** [comment]
Good find, I have confirmed this and also found that it works for the main Mailcow domain  name, for example:

```bash
curl -I http://mail.theendlessweb.com/%0aSet-Cookie:crlf=injection
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 27 Dec 2018 15:41:53 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://mail.theendlessweb.com/
Set-Cookie:crlf=injection
```
Perhaps these redirects to HTTPS would be better done using Nginx rather than PHP? Something like this?

```nginx
server {
  server_name: autoconfig.* autodiscover.*;
  listen 80;
  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type text/plain;
  }
  location / {
    return 301 https://$server_name$request_uri;
  }
}
```
Or perhaps I have misunderstood what was happening in the [main Nginx config file](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/nginx/site.conf)?

**Comment by mkuron** [comment]
It‘s not obvious to me how one could use this for XSS in our case. The issue only exists during the HTTPS redirect, where the body of the response does not matter.

We should still get it fixed though. Is there a way to have Nginx sanitize variables?

**Comment by andryyy** [comment]
You can do something like that https://stackoverflow.com/questions/44178354/avoid-crlf-characters-in-nginx

Good catch. :)

**Comment by andryyy** [comment]
I updated the docs. We can probably close this?

**Comment by itsbhanusharma** [comment]
I Just had a Question,

Do existing installs need to update something?

**Comment by andryyy** [comment]
When you added the http to https redirect as it was described in the docs, yes, you should check the docs for the change then.

**Comment by chriscroome** [comment]
The commit @andryyy is making reference to is [this one](https://github.com/mailcow/mailcow-dockerized-docs/commit/cdf1a436ca904186d78e391bab71f2747af2a1af) which updates [this documentation page](https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/).

**Comment by Electromaster232** [comment]
I believe this can be closed now (especially because I resolved the issue on the subdomain mentioned in the original issue post)

**Comment by MAGICCC** [comment]
closed then
