### ISSUE TITLE
Clear text Password in Mailcow UI logs!

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2135]
Today one of my domain admins changed his PW. Now I can see the clear text PW in the Mailcow UI Logs. In my opinion, this is absolutely not OK.
Maybe the same with normal User.

![bildschirmfoto 2018-12-29 um 14 40 07](https://user-images.githubusercontent.com/11925757/50538995-6c73fd80-0b79-11e9-897b-566dc2fde592.jpg)

**Comment by andryyy** [comment]
It is fixed. I missed the domain admin self-edit stuff.
