### ISSUE TITLE
SOGo not sending reminder mails for appointments

### ISSUE THREAD

**Issue by DatAres37** [mailcow/mailcow-dockerized#2136]
**Describe the bug**
SOGo is not sending reminder mails for appointments I created in the SOGo calendar.

**How to reproduce Reproduce**

1. Calendar -> Create a new event
2. I'm filling in the title, a description and a date
3. Activating the checkbox "Reminder" 
4. 10 minutes before the event starts
5. Change radio button to "Send an E-Mail"

**Expected behavior**
An mail is sent 10 minutes before the event starts.

**Logs**
SOGo log:
```
Dec 29 20:25:01 85a6f2b04e1d CRON[5548]: pam_unix(cron:session): session opened for user sogo by (uid=0)
Dec 29 20:25:01 85a6f2b04e1d CRON[5549]: pam_unix(cron:session): session opened for user sogo by (uid=0)
Dec 29 20:25:01 85a6f2b04e1d CRON[5552]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify 2>/dev/null)
Dec 29 20:25:01 85a6f2b04e1d CRON[5553]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
Dec 29 20:25:01 85a6f2b04e1d CRON[5548]: pam_unix(cron:session): session closed for user sogo
Dec 29 20:25:02 85a6f2b04e1d CRON[5549]: pam_unix(cron:session): session closed for user sogo
```
Postfix log:
```
Dec 29 20:25:01 mail postfix/smtpd[1317]: connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
Dec 29 20:25:01 mail postfix/smtpd[1317]: disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 quit=1 commands=2
```

**System**
 - OS: Ubuntu 18.04.1, Kernel 4.15
 - Browser: FF 64

**Additional context**
Apparently sending invitations for appointments isn't working either.

**Comment by andryyy** [comment]
When was your last update?

**Comment by DatAres37** [comment]
> When was your last update?

About a week ago. Either 22th or 23th December.

**Comment by andryyy** [comment]
Ah, I see. I broke it when I fixed SOGo.
