### ISSUE TITLE
Does not start in Docker for Windows

### ISSUE THREAD

**Issue by flexguse** [mailcow/mailcow-dockerized#2137]
**Describe the bug**
Mailcow does not start in my Docker Desktop community edition. Every time I try to start from WSL I get the error

`ERROR: for unbound-mailcow  Cannot start service unbound-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/i/Development/workspaces/docker/mailcow-dockerized/data/conf/unbound/unbound.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/21120e4f2b0dee0a491e21531e4ccf7fddcde13085c263881427bea84d45a317/merged\\\" at \\\"/var/lib/docker/overlay2/21120e4f2b0dee0a491e21531e4ccf7fddcde13085c263881427bea84d45a317/merged/etc/unbound/unbound.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

The unbound container crashes immediately. The .conf file exists in the mailcow git project. Unfortunately I'm not able to have a look into the container to check if the folder /etc/unbound exists.

The containers dovecot, nginx and rspamd are restarting permanently.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. install Docker for Desktop in your Windows 10
2. install WSL Ubuntu
3. install docker and docker-compose in WSL Ubuntu
4. configure docker-compose in WSL to use the Windows Docker installation
5. run `./generate_config.sh` in WSL
6. start mailcow with `docker-compose up -d`

**Expected behavior**
The unbound.conf file is mounted correctly and all mailcow containers are started correctly.

I do not want to run mailcow in production in Windows 10 but I would like to test my setup locally before I put it into my Linux production server.

**System**
 - OS: Windows 10 Pro, Docker Desktop Community 2.0.0.0-win81, Docker Engine 18.09.0, Docker Compose 1.23.2
 - WSL Ubuntu 18.04

**Comment by Braintelligence** [comment]
I think you will run into problems running overlay2 with WSL Ubuntu. Not sure, though.

**Comment by flexguse** [comment]
Well, maybe but in the docker-compose file there are several folders which are mounted into the containers and unbound.conf is the onliest docker-compose is complaining about.
If I run in overlay2 problems, do you know any workarounds?

**Comment by mkuron** [comment]
Duplicate of #326. Docker for Windows always runs a Linux VM, so most things could probably be made to work. However, the network connections always go through the Docker userland proxy, which means that you'll lose information about the source IP address. So your mail server will be an open relay, fail2ban will not work, etc.

**Comment by mkuron** [comment]
Oh, sorry, forget you were running inside WSL. Is that even officially supported by Docker?

**Comment by andryyy** [comment]
I think they use Windows’ Dockerd inside WLS. Not sure. Much easier to install Hyper-V or Vbox.

**Comment by flexguse** [comment]
Docker for Windows is the Hyper-V installation, Docker does not start any container in WSL. I just configured docker and docker-compose to use the remote docker in the Hyper-V machine.

I think I solved my problem. Here is what I did:

1. got rid of the .env symlink file and renamed mailcow.conf into .env
2. started `docker-compose up -d` in PowerShell
3. added the FQDN in my hosts file
4. opened UI using FQDN

So it seems I had some overlay issues in combination with the symlink file which does not work in PowerShell.

**Comment by jaroslavpsenicka** [comment]
thank you very much @flexguse 
my symptoms:
- cannot run `./generate_config.sh`, returns error `Cannot find Docker Compose.`
- cannot run `docker compose`, returns error `setenv: The parameter is incorrect.`

resolved by renaming mailcow.conf to .env

**Comment by NicksonYap** [comment]
> resolved by renaming mailcow.conf to .env

worked for me
