### ISSUE TITLE
Strange gmail delivery issue, due to cipher suite?

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#214]
I use glockapps to test deliverability and noticed something strange. I have two dedicated servers, 1.2.3.4 and 5.6.7.8. 

1.2.3.4 is listed on a blacklist because it is in a range that is listed. 5.6.7.8 has a sender score of 97 and no BL. DNS-wise they are both configured exactly the same way, with SPF, DKIM, DMARC, rDNS in place, a and mx records properly set. both have a score of 10/10 on mail-tester (although actually, the blacklisted one not, but it would have 10/10 without the BL)

Generally gmail is pretty easy to get INBOX. So i expected both to go in alright, maybe problems with the blacklisted server. to my surprise, the blacklisted server goes INBOX the other one to SPAM. i compared the results in glockapps and the only difference is the cipher suite shown in the 'Received'-field. now i don't understand much of why and where which cipher is used, but i wonder if this could be the reason? 

cipher shown when mail is sent from 1.2.3.4: `ECDHE-RSA-AES128-GCM-SHA256`
cipher shown when mail is sent from 5.6.7.8: `ECDHE-RSA-CHACHA20-POLY1305`

i actually tested this on a third server now and gmail puts it into spam also, and again it is the `ECDHE-RSA-CHACHA20-POLY1305` cipher

i am curious why mail sent from 1.2.3.4 is using a different cipher when 5.6.7.8 is configured the same way?

on all servers i tried with a pristine up-to-date mailcow-dockerized copy, 1.2.3.4 with the hostname mx.mydomain.com and 5.6.7.8 with my.mydomain.com. i switched the hostnames around out of curiosity but the problem stayed the same, 1.2.3.4 goes in box the other one not, no matter what the sender domain is. i started from scratch several times and 1.2.3.4

incidentally it is the other way around for AOL O_o I know hotmail is not even worth trying to get insbox, so I don't even bother :-P

anyway .. Any thoughts? It's driving me nuts and I'm so curious what the reasons could be :-D

![untitled-1](https://cloud.githubusercontent.com/assets/16366980/25292063/e52b0b96-26d4-11e7-8699-49371808f0a8.png)

**Comment by andryyy** [comment]
Hi,

This is not about the ciphers. Did you change DKIM records on these
domains lately?

Can you send me mails to andre.peters@debinux.de from these machines?


Am 21.04.2017 um 20:50 schrieb <haosbvnker:

**Comment by chaosbunker** [comment]
Yes, actually, I did change the DKIM records recently in the dns - but the TTL is only 300 .. so I assume that would not cause issues, or could it?

I just sent you emails from both - and I also verified that the issue still remains by sending new test mails to glockapps and attached the info i get from them

**Comment by andryyy** [comment]
AOL has a very strict inbox but they also have a nice system to get in touch with them and find ways to rule problems out. They probably tell you more about why they filter you to spam.

Anyways, your mails seem fine, it is just the IP reputation.

Also don't trust those testing apps and just send mail to a GMail address. :)

**Comment by chaosbunker** [comment]
Ok, good to know! Thanks for the advice! :-)
