### ISSUE TITLE
fail2ban/netfilter behind a external reverseproxy does not block 

### ISSUE THREAD

**Issue by rubinho76** [mailcow/mailcow-dockerized#2141]
Hi guys, I have the Mailcow behind an external ReverseProxy/Firewall (Pfsense) and as result Fail2ban/Netfilter will not work with the normal IP table rules.
There is already a solution, but it would have to be implemented.

https://centos.tips/fail2ban-behind-a-proxyload-balancer

greets rubinho

**Comment by andryyy** [comment]
If you cannot see the public IPs of clients connecting to postfix-mailcow, you should stop mailcow _now_. It may be an open relay. That's nothing we can control in mailcow, you need to make sure your firewall is working properly.

If you don't see public IPs in nginx-mailcow, you need to fix your reverse proxy. Follow the docs carefully, please. If you setup your reverse proxy as described in the docs, the correct IPs will be logged.

**Comment by rubinho76** [comment]
I see the public IPs, that's not the problem.
Fail2ban also blocks the public IP, but I arrive with the internal IP of my firewall (Gateway IP). This means that the LAN-IP still gets pass through.

**Comment by andryyy** [comment]
The provided link does not provide anything new. We already add the proxy headers and filter by the correct IPs.

If you see your gateways IP in postfix-mailcow when you send yourself a mail from outside, you have an open relay. That’s independently of the proxy headers. You should reconfigure your firewall then and stop mailcow before you do anything.

**Comment by mkuron** [comment]
> Fail2ban also blocks the public IP

I think your problem is that when an IP is banned only IMAP/SMTP/... are blocked but not web. To get that, you would need to modify fail2ban’s action to SSH to your reverse proxy and add a rule there too. There is no obvios generic solution that we could implement in Mailcow.

**Comment by mkuron** [comment]
The `iptables -I fail2ban-<name> 1 -p tcp --dport 80 -m string --algo bm --string 'X-Forwarded-For: <ip>' -j DROP` from your link only works if one doesn’t use SSL between Mailcow and the proxy.

**Comment by rubinho76** [comment]
Ich versuchs mal auf Deutsch, vielleicht versteht man das besser. 
Das Problem tritt wie oben schon geschrieben nur bei http respektive SOGO auf. Bei allen anderen Diensten (Imap, smtp usw.) habe ich ein direktes Portforwarding wo dann die echte Public IP auf den Server zugreift.
Bei den HTTP(S) Verbindungen verschleiert mein davorgelagerter ReverseProxy in der Firewall die tatsächliche IP. Es wird zwar über X-Forwarded-For die offizielle IP im Header mit übermittelt, jedoch findet keine ende zu ende Kommunikation mehr statt, da mein ReverseProxy dazwischen die Kommunikation aufbricht. Somit kommen die Http Pakete mit der Quelladresse der Firewall an und nicht mit der PublicIP des im Internet befindlichen Clients. Eine normale IP-Table Rule würde da nicht greifen.

Und ja, die von mir oben beschriebene Lösung würde nur mit einer unverschlüsselten Verbindung zwischen Firewall und Mailserver funktionieren. Was aber innerhalb meiner DMZ unkrittisch wäre. Die Kommunikation über das Internet ist weiterhin verschlüsselt.
Einen solchen Workaround hatte ich bereits erfolgreich an einem selbstgebauten Sogo Server am laufen gehabt. 

Ich wollte euch nur darauf aufmerksam machen, dass unter diesen Umständen Fail2ban keine Wirkung zeigt. 
Da ein vorgelagerter ReverseProxy keine Seltenheit ist, wird jeder der sowas betreibt auf das gleiche Problem stoßen. Es ist also kein spezifisches Problem meinerseits.

Achso nochwas, frohes neues Jahr :)

**Comment by mkuron** [comment]
Die meisten Leute scheinen reverse proxies auf dem selben Host wie Docker zu betreiben, da geht alles. Auch wenn deine Szenario natürlich möglich und sinnvoll ist, gibt es da keine sinnvolle Lösung für das Problem. Deine iptables-Lösung macht eine Volltextsuche in jedem Paket, was nicht sonderlich performant sein dürfte. Man könnte das Mailcow-Webinterface natürlich PHP-seitig selber auf blockierte IPs prüfen lassen, aber das schützt Sogo nicht. Und Nginx-seitig kann man nichts machen, weil es kein Redis-Modul für Nginx gibt.

**Comment by rubinho76** [comment]
@mkuron 
Danke für die Rückmeldung und ja viele nutzen natürlich auch den ReverseProxy aus diversen Gründen direkt auf der Maschine.

Ich habe jedoch nur eine offizielle IPv4 Adresse  und diese muss mehrere Websiten/Dienste versorgen. Ich wollte die Mailkuh dafür jetzt aber nicht als zentralen ReverseProxy missbrauchen, dafür ist der Server glaub ich auch nicht gedacht. 

Es sollte mehr oder weniger ein Hinweis sein. Ein zentraler Reverse Proxy/ Loadbalancer ist nunmal best practice und man sollte halt im Hinterkopf behalten, dass damit der Netfilter ausgehebelt wird.
Eine andere Lösung wäre ja das temporäre Sperren des Accounts bei mehrfacher Falscheingabe des Passworts. Wie auch immer das umsetzbar ist. (Bin nur ein Firewall-Admin und kein Programmierer)

Nochmals danke für die schnelle Rückmeldung.
