### ISSUE TITLE
autodiscover ssl fault

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#2143]
In the default configuration of nginx only TLS 1.2 is allowed and specific ciphers.
This breaks the autodiscover function of Outlook.

Replacing ssl_protocols and ciphers with the ones from below fixes these errors.
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#nginx

Seems location autodiscover need there own ssl settings?

Only thing it fails on now is the

Testing HTTP Authentication Methods for URL https://mail.<domain>/Microsoft-Server-ActiveSync.
--
  | The HTTP authentication test failed.

A 401 error was received from the server, but no authentication methods are supported.HTTP Response Headers:Connection: keep-aliveX-Frame-Options: SAMEORIGINContent-Length: 0Content-Type: text/plain; charset=utf-8Date: Wed, 02 Jan 2019 12:55:34 GMTServer: nginxWWW-Authenticate: basic realm="SOGo"Elapsed Time: 383 ms.
--

**Comment by andryyy** [comment]
It doesn’t break compatibility with Outlook. It may not work on Windows 7 though. 

Autodiscover is not broken at all. HTTP authentication is fine too. I don’t understand what you need help with exactly. :) 

If I’m not missing something, this can be closed?

**Comment by normanu** [comment]
Hi Andryyy,

Well Outlook 2019 for Mac doesn't autoconfigure.
But while searching for the reasons, I tried https://testconnectivity.microsoft.com
And Autodiscover doesn't pass those tests unless I did as mentioned above.
In the end it still failed the last test as mentioned.

**Comment by andryyy** [comment]
The test always fails with SOGo and mailcow. But it will work fine.

Don’t know if Office 19 with OS X works. Do you know if Office 19 uses the “new” autodiscover via JSON, @mkuron?

**Comment by normanu** [comment]
I guess so, as it doesn't work so I assumed it was de configuration.
The test does pass almost all tests with above ssl adjustments.
But I guess that wouldn't matter for the clients.

**Comment by andryyy** [comment]
I wonder if I could get a license off eBay to test on my wifes mac.

**Comment by mkuron** [comment]
Office for Mac 16 already used JSON (the old XML protocol was never supported on Mac), but it doesn't help with Mailcow because JSON doesn't do IMAP/SMTP and EAS still isn't supported on Mac. The only thing that autodiscovery did last time I checked a few months ago was configure "real" Exchange accounts. Until Outlook for Mac gets either EAS support or SMTP/IMAP autoconfigurability, there is no need to fix this issue.
