### ISSUE TITLE
Can i use check_recipient_access twice in smtpd_recipient_restrictions?

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#2146]
I need to configure pcre in smtpd_recipient_restrictions
but check_recipient_access is already used in mailcow "check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf"

I have not found exact information whether check_recipient_access can be used twice

**Comment by andryyy** [comment]
It can be used multiple times. :)

**Comment by proea** [comment]
@andryyy great to know, Thank you!
