### ISSUE TITLE
Can not access thirdparty sw

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2148]
Hello, I installed munin-node on server roning this dockerized mailcow, but I can not access it. It is running on port 4949, listening on 0.0.0.0. I can access via loopback, but not from remote. Looks like all remote access is catched by mailcow setup a nated somewhere.

Please help me ith this problem. Thank you!

**Comment by andryyy** [comment]
As long as it is not running in Docker and you try to access it from outside Docker, no. We (or Docker) do not block this.

**Comment by feldsam** [comment]
hmm, there are some iptables generated by docker, there is also same `nat` container...

**Comment by andryyy** [comment]
Yes. But nothing blocks other applications from being reachable. It only affects containers.
