### ISSUE TITLE
Update: From any version?

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#2149]
Hello,

I wan't to ask if i can update to the newest version from any version below?
No problems about that? ;)

Thanks.

**Comment by mkuron** [comment]
In general, you can upgrade from any version to any newer one. However, some upgrades migrate data (e.g. database schema changes, moving stuff from files to redis, etc.). While these migrations should also work between arbitrary versions, we don't test that beyond a certain age. So to be on the safe side, you should upgrade your Mailcow at least monthly. If you are making a bigger step: make a backup, check the logs after the upgrade and be prepared to do some minor manual work to fix things that break.
