### ISSUE TITLE
Unable to set up mailcow mailbox with Thunderbird

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2150]

**Comment by whalehub** [comment]
I think I know the cause of the issue now. The reverse proxy is only opening ports 80 and 443 on the subdomain **mail.datahoarder.xyz**, so it can't connect to the server on the right ports. I'll be correcting this momentarily and test it again.

**Comment by whalehub** [comment]
This problem seems to affect authentication with the smtp/imap servers in general, not just with Thunderbird. Any application that I try it with fails to authenticate properly.

**Comment by cheiff** [comment]
I don't understand how you do the reverse proxying of imap to 993 or smtp to 465. 
But anyway: why don't you use those ports in the thunderbird config? I have no problems with that, it works fine. Username should be the whole email address username@domain.tld.

It looks like the issue is related to that reverse proxying you say you are doing. How does that work? and why?

**Comment by mkuron** [comment]
At the bottom of that window, you need to set the user name to 9f301643bf@datahoarder.xyz. Thunderbird automatically put 9f301643bf there, which is not correct.

Also FYI, after multiple failed authentication attempts, Mailcow will block your IP address for an hour.

Reverse proxying the non-HTTP(S) ports is strongly discouraged as this breaks the automatic blocking after failed authentication attempts. I hope you are not reverse proxying port 25 as that will make your mail server an open relay and give you a serious spam problem.

**Comment by mkuron** [comment]
Also, I guess you are not reverse proxying autoconfig.datahoarder.xyz for HTTP port 80? That would be why Thunderbird guesses the configuration instead of asking the Mailcow server for it.

**Comment by whalehub** [comment]
@mkuron No, I'm not reverse proxying autoconfig.datahoarder.xyz for the HTTP port 80.

@cheiff My bad, I misunderstood how smtp and imap work on a fundamental level. I disabled the reverse proxying of those two ports, then tried it again with your suggestions regarding the ports and username but the issue remains the same. Here's another shot video:

![2019-01-07_23-04-18](https://user-images.githubusercontent.com/44198148/50796077-b1fa9e00-12d0-11e9-93ea-a870115c7b52.gif)

Any idea what else could be causing this problem?

**Comment by Braintelligence** [comment]
Did you find a solution?

**Comment by whalehub** [comment]
@Braintelligence I'm afraid not. I stopped using mailcow because I was unable to resolve this issue.

**Comment by mkuron** [comment]
Did you add the autoconfig domain to your reverse proxy? That should have fixed it.

**Comment by rohu2007** [comment]
Hallo Zusammen, leider stehe ich vor dem Selben Problem und kann keine Clients am Mailserver anmelden.
Intern, direkt auf die Interne IP-Adresse des Mailserver funktioniert es wunderbar, von Extern komme ich jedoch nicht drauf.

ich muss dazu sagen, dass der Mailserver hinter eine Sophos UTM hängt und Dort der Email Protection aktiviert ist. Versenden und Empfangen von Emails funktioniert...

Kann mir da jemand helfen?

**Comment by raako71** [comment]
@whalehub I have been able to get this to work, did a port scan on my server and found that it is not listening on 993, changed IMAP to port 143, which was on the dropdown in thunderbird for creating a new account. 
Also I created a new account, and selected manual config, then chose STARTTLS for IMAP and SMTP, which did the same thing, working ports 143 and 465

unsure as to the cause of this..
