### ISSUE TITLE
Unable to add additional SAN to acme-client with unknown reason

### ISSUE THREAD

**Issue by carlbennett** [mailcow/mailcow-dockerized#2151]
**Describe the bug**
The acme-client was able to renew SSL certificates just fine for about a dozen different items, but now that I've added an additional domain (mail.deltagaming.net), it's erroring out with just an exit code 1 and no other detail as to why.

The error from the log (attached below) is:

    acme-mailcow_1       | acme-client: bad exit: netproc(691): 1
    acme-mailcow_1       | acme-client: bad exit: challengeproc(694): 1

**How to reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Restart acme-client without new domain, renewal works fine, it sleeps for 1 day.
2. Add new domain to mailcow.conf under additional SANs.
3. Run docker-compose up -d to let acme-client container see new configuration.
4. Restart acme-client container.
5. Error occurs, see logs. It sleeps for 30 minutes before trying again.

**Expected behavior**
The additional SAN is added to the SSL certificate without issue and renewal then sleeps for 1 day.

**Logs**
[acme-mailcow_1.txt](https://github.com/mailcow/mailcow-dockerized/files/2729719/acme-mailcow_1.txt)

**System**
 - OS:
   - Server: CentOS 7.6.1810 (Linux kernel 3.10.0-957.1.3.el7.x86_64)
   - Client: Windows 10 Pro 64-bit 1803
 - Browser: Opera, Firefox, Vivaldi

**Additional context**
The domain in question is configured correctly to the best of my knowledge:

    mail.deltagaming.net.   300     IN      A       207.148.0.187
    mail.deltagaming.net.   300     IN      AAAA    2001:19f0:6401:371:5400:1ff:feb8:c055

**Comment by carlbennett** [comment]
The certificate has been successfully renewed with no changes to configuration. It seems that all this needed was further time, but I'm not sure why waiting was necessary.

**Comment by andryyy** [comment]
I couldn’t resolve any “redacted” Name a few hours ago. Not a single name retuned an IP. 

I wasn’t able to answer until now, sorry. It was probably DNS related.

**Comment by carlbennett** [comment]
I redacted those other names on purpose.

**Comment by carlbennett** [comment]
Anyway, no need to keep this open. It definitely was not DNS related as the records were in place for more than 12 hours and the TTL on all of them are 300 seconds.
