### ISSUE TITLE
Users blacklisting with wildcards

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2152]
Hi,
one of my User wants to blacklists multiple email address with this syntax:
*@example.*

The system translates this (in rspamd conf) to .*@example.*
But correct is .*@example\..*

**Comment by andryyy** [comment]
Hi, can you please post using markdown?

**Comment by vain90** [comment]
Sorry, I would have to use the preview function.

--

one of my User wants to blacklists multiple email address with this syntax:
`*@example.*`

The system translates this (in rspamd conf) to `.*@example.*`
But correct is `.*@example\..*`
Or something similar

**Comment by andryyy** [comment]
No problem. :) I'm working on it and probably already fixed it. But this needs more tests.
