### ISSUE TITLE
Microsoft Exchange Problem

### ISSUE THREAD

**Issue by volbrene** [mailcow/mailcow-dockerized#2153]
Hello, if I get a Mail from a Exchange Mail Account, The content look like chine Text.

But only on Ios. In Sogo it Looks fine.

Example:
㱨瑭氠摩爽≬瑲∾਼ And so on.

Can anyone help me?

**Comment by mkuron** [comment]
Please post the raw source of the message, including headers. Also, are you using IMAP or Exchange ActiveSync on iOS?

**Comment by volbrene** [comment]
Hello, thanks for this fast Support. I use imap.

**Comment by volbrene** [comment]
I think, that ios have a problem with specific html code. This Problem is on my gmail account on ios too. So, you can close this ticket, if you want.
