### ISSUE TITLE
Let's Encrypt via cloudflare plugin and Apache proxy_http

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#2155]
Hi folk,

I use an apache proxy with cloudflare plugin.

First installation from mailcow
Now I copy cp -L ........./fullchain.pem to data/assets/ssl/cert.pem the privkey too.
docker-compose up -d

All works fine ...

But what's when I make a renew from my Let's Encrypt certifivate?
Is it enough a new copy cp -L fullchain.pem to data/assets/ssl/cert.pem the privkey
docker-compose up -d

Or must I all containers restart?

regards
jm3west

**Comment by andryyy** [comment]
Hi,

You need to reload the services or restart the containers with a hook, like this: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#optional-post-hook-script-for-non-mailcow-acme-clients

"up -d" will not work.

Most clients (like certbot) are able to use a post-hook script. :)

**Comment by jm3west** [comment]
Danke André
