### ISSUE TITLE
Can't access subfolder

### ISSUE THREAD

**Issue by nnlt** [mailcow/mailcow-dockerized#2156]
When a specific user tries to access a folder and its subfolders he receives the message `An error occured while communicating with the mail server` in SOGo.

The SOGo log shows the following:
`notice | [59]: [ERROR] <0x0x55cd72eb8100[NGImap4Connection]> could not select URL: imaps://xyz%40xyz.de@dovecot/Auftr%26AOQ-ge%202018/0007/?tls=YES: {RawResponse = "{ResponseResult = {description = \"Mailbox doesn't exist: Auftr\\U00E4ge 2018/0007 (0.003 + 0.041 + 0.042 secs).\"; result = no; tagId = 7; }; }"; reason = "Mailbox doesn't exist: Auftr\U00E4ge 2018/0007 (0.003 + 0.041 + 0.042 secs)."; result = 0; }`

Is it possible to restore the affected folder?

**Comment by andryyy** [comment]
What does it look like in an IMAP client?

**Comment by andryyy** [comment]
Maybe it was created when we had the UTF8 flag enabled a while ago. Like... 1-2 months ago?

**Comment by nnlt** [comment]
Same issue. 
Yes, it was likely created 1-2 months ago.

**Comment by andryyy** [comment]
Best idea I have right now: create a new folder and move the old/broken maildir content to that new folder. You will find it in /var/lib/docker/volumes/mailcowdockerized-vmail-vol-1/_data/domain/username
The mailcowdockerized part can differ. I’m on mobile and just guessed the correct name.

**Comment by nnlt** [comment]
Do I understand you correctly that I should move the whole content of the /var/lib/docker/volumes/mailcowdockerized-vmail-vol-1/_data/domain/username to a new folder?
So the mailbox will be empty?

**Comment by andryyy** [comment]
No, just the content of that specific broken folder. Like `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/develcow.de/andre/.BrokenFolder/`. Move (and do not change permissions or the owner) its content to `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/develcow.de/andre/.MyNewFolder/` .

**Comment by nnlt** [comment]
Thank you very much!
Moved the content of the folder and it works like a charm again :)

**Comment by andryyy** [comment]
Nice. :)
