### ISSUE TITLE
Connection timed out on Azure VM

### ISSUE THREAD

**Issue by miguelurtado** [mailcow/mailcow-dockerized#2158]
**Describe the bug**
E-mail not send for external and internal mailbox.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Instal Mail Cow on Azure VM
2. Send new e-mail
3. Error log

**Logs**
`connect to alt1.gmail-smtp-in.l.google.com[64.233.166.27]:25: Connection timed out`

**Comment by andryyy** [comment]
Hi, like most cloud Providers they do probably block SMTP outgoing by default. I don't know about Azures policies regarding SMTP unlocking.

**Comment by mkuron** [comment]
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/2130. Please check existing issues before opening a new one.
