### ISSUE TITLE
Show real IP in dovecot/postfix etc. logs

### ISSUE THREAD

**Issue by bonanza123** [mailcow/mailcow-dockerized#2159]
When checking the postfix or dovecot logs, I only see IP addresses from the docker subnet such as

```
imap-login: Login: user=<user@domain.org>, method=PLAIN, rip=172.24.2.1, lip=172.24.2.6, mpid=173, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
```

Is there any way to let them show the IP?

**Comment by mkuron** [comment]
If that is happening, please shut down your Mailcow immediately. It will be acting as an open relay, allowing spammers to use your server to send messages.

The cause of this is usually a misconfigured firewall, either on the network or on the Docker host. It is either masquerading the remote IPs or prevented Docker from adding its own rules (thus falling back to the userland proxy).

**Comment by bonanza123** [comment]
Thanks for your reply.
This may be consistent with the weird logs I am seeing in mailcow:\
```

1/8/2019, 10:13:59 AM | info | 79C073070A1C: removed
-- | -- | --
1/8/2019, 10:13:58 AM | info | 79C073070A1C:  to=<2005191117@163.com>,  relay=163mx03.mxmail.netease.com[220.181.14.158]:25, delay=4.7,  delays=0.88/0/3.1/0.72, dsn=2.0.0, status=sent (250 Mail OK queued as  mx41,W8CowAAnS4zUaTRcSJ_NDw--.24884S3 1546938838)
1/8/2019, 10:13:57 AM | info | Trusted  TLS connection established to  163mx03.mxmail.netease.com[220.181.14.158]:25: TLSv1.2 with cipher  AES256-GCM-SHA384 (256/256 bits)
```
right?

Could you please elaborate a bit how to mitigate this problem?
I haven't done any changes to iptables and I am also not using anything like `ufw`.

**Comment by mkuron** [comment]
Please provide some details on your setup, e.g. NAT router in front of your Mailcow, iptables rules on the Docker host (`iptables --list`), etc.

**Comment by bonanza123** [comment]
Thanks for your response.
I am on hetzner (with their firewall disabled) and no further changes done after boot to iptables or docker config (There are no config files in `/etc/docker/*`). Please find the `iptables --list` and `iptables -S` output here:
https://pastebin.com/F71ZTdN3
https://pastebin.com/nfSUckGb

I also have not change any stuff (but passwords) for mailcow's docker-compose or the configs behind it.

**Comment by mkuron** [comment]
You have other Docker containers running and, for some reason, lots of duplicates in the rules. Please take down all Docker containers, reboot the host and start up only Mailcow. See if that changes anything about the IPs reported.

Also, what is 192.168.122.0? Do you by chance have a masquerade rule in place (`iptables -t nat --list`)?

This is not a Mailcow issue per se: either something is misconfigured on your host or your other Docker containers are causing it.

**Comment by bonanza123** [comment]
Thanks again for your help so far!

I have cleaned up some stuff (I found a old bride with for 192.168.122.x which I removed).
I upgraded docker to 18.x, disabled the autostart of docker and started only mailcow.

Before docker start and mailcow start
https://pastebin.com/tRe0rJkk
https://pastebin.com/2nybVJA2
https://pastebin.com/QrSQerCP

After mailcow start
https://pastebin.com/ei8eRFHR
https://pastebin.com/FRsFjnGK

NAT:
https://pastebin.com/TKiBcAc2
https://pastebin.com/S8AbFqnp

Where
`docker ps` shows only `mailcow_*` stuff

I guess the other docker subnets (`172.24.2.x` is the mailcow subnet) mentioned in the rules are created although the corresponding containers are not started.

I am also a bit confused right now whether theproblem still persists:
I see stil a lot of:
```

  | NOQUEUE:  reject: RCPT from unknown[113.103.120.225]: 504 5.5.2 <ckwtt>:  Helo command rejected: need fully-qualified hostname;  from=<user@domain.org> to=<787340860@qq.com>  proto=ESMTP helo=<ckwtt>
```

Which maybe is just blocked because I changed the postfix config as follows (git diff)
```
-smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
+smtpd_relay_restrictions = permit_sasl_authenticated defer_unauth_destination
```

**Comment by mkuron** [comment]
The problem is fixed as you are now seeing the correct IP. Your config change would have closed the open relay even if the problem was not fixed, but will likely have side effects, so you better revert it.

Most likely your old bridge had an unrestricted masquerade rule attached to it, like `-A POSTROUTING -j MASQUERADE`. That would apply to all interfaces and source addresses.

For some reason you still have way more rules than Docker would created for Mailcow. You might want to check and clean that up.
