### ISSUE TITLE
Force ActiveSync to Use SSL (vs STARTTLS)

### ISSUE THREAD

**Issue by philip-ulrich** [mailcow/mailcow-dockerized#216]
Hello there! 

Love this project and the support that it has. Probably the best complete mail solution I have found. Currently I have yet to get autodisover/autoconfig to work with Spark because it requires SSL and doesn't like STARTTLS for some reason. ActiveSync seems to be sending STARTTLS settings vs SSL. Is there a way to change what settings it sends out or force SSL over 465? I've reviewed the config files and haven't found a way.

Thanks!
- Phil

**Comment by andryyy** [comment]
Hi,
Thanks! :) ActiveSync pushes with XML over HTTP.
If disabled, it configures SMTP with SMTPS over 465/tcp (just updated the docs).

If you are talking about autoconfig (Thunderbird etc.), you can change the autoconfig service in `data/web/autoconfig.php` to use SMTPS.

**Comment by philip-ulrich** [comment]
Genius. Enabling http -> https redirect fixed the issue. Thanks for the quick and helpful reply!
