### ISSUE TITLE
Enable multiple 2FA

### ISSUE THREAD

**Issue by vbrandl** [mailcow/mailcow-dockerized#2161]
**Is your feature request related to a problem? Please describe.**

Currently only one 2FA mode can be selected. Either TOTP, U2F or Yubico 2FA

**Describe the solution you'd like**

It would be nice to enable e.g. U2F _and_ TOTP. I don't think this would compromise the security in any way.

**Comment by vain90** [comment]
Multiple TOTPs don't work either.
#735

**Comment by phenomax** [comment]
What's your opinion of this, @andryyy

**Comment by phenomax** [comment]
What's your opinion on this, @andryyy

**Comment by patschi** [comment]
I think that would be a nice improvement, specially being able to use 2x U2F sticks (e.g. one for a fallback). However I think it doesn't have that kind of high priority, and also might require quite a lot of work to rework the current code.

**Comment by Braintelligence** [comment]
Well you could create another Admin account and use a different key/totp

**Comment by phenomax** [comment]
@Braintelligence This would be a quite ugly workaround, but no solution.

**Comment by gromain** [comment]
Definitely interested in this feature too.

**Comment by HuntStarJonny** [comment]
it's not a nice to have and in my optionion not a feature request, but a bug(wrong implementation), only being able to to add one u2f key violates the authentication standard or at lest best practice.
Cause it's not possible to make backups of yubikey etc... it's a absolute must have.

**Comment by andryyy** [comment]
It does not violate anything. I talked to Yubi when we implemented it and they even sponsored some keys for a giveaway.

You can add multple keys without a problem, you just cannot mix with TOTP etc. - it is NO violation of anything to not being able to mix u2f with totp etc.

That's ridiculous, sorry. I don't know if that was just written to put pressure on us to work on something you want. :(

**Comment by HuntStarJonny** [comment]
well then my bad, i didn't test it correct with 2 different yubikey, works fine - sorry

**Comment by NoirPi** [comment]
Adding a second TOTP device is still a great idea
It would make administration much more handy if you have a password vault with TOTP feature and also will be able to get a TOTP on mobile if you are on the go.

**Comment by Braintelligence** [comment]
You can have the same TOTP secret on multiple devices.

**Comment by NoirPi** [comment]
You saved my day! @Braintelligence

**Comment by divadsn** [comment]
I don't have the money for a second YubiKey but would still have a backup method via TOTP or paper key.

**Comment by MAGICCC** [comment]
Closed in favor of https://github.com/mailcow/mailcow-dockerized/issues/4164 and we may see something soon
