### ISSUE TITLE
clamd seems to be broken with last update

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#2162]
I made an update some minutes before with the latest changes for clamav. Now i have the problem that in watchdog, clamd is not healthy and seems to restart. It comes up to a health level of 60% and the starts from the beginning.

**Comment by andryyy** [comment]
Can you please post logs of clamd-mailcow?

**Comment by lgusewski** [comment]
Can you help me please how to do this from clamd? Did not see logs in the UI. I saw that IPv6nat had also a problem after the update from 08.01.19

`sogo-mailcow (mailcow/sogo:1.49) (Started on Tue, 08 Jan 2019 22:37:28 +0100)
unbound-mailcow (mailcow/unbound:1.4) (Started on Tue, 08 Jan 2019 22:37:27 +0100)
php-fpm-mailcow (mailcow/phpfpm:1.29) (Started on Tue, 08 Jan 2019 22:37:29 +0100)
memcached-mailcow (memcached:alpine) (Started on Tue, 08 Jan 2019 22:37:25 +0100)
nginx-mailcow (nginx:mainline-alpine) (Started on Tue, 08 Jan 2019 22:37:28 +0100)
postfix-mailcow (mailcow/postfix:1.29) (Started on Tue, 08 Jan 2019 22:37:27 +0100)
dovecot-mailcow (mailcow/dovecot:1.52) (Started on Tue, 08 Jan 2019 22:37:29 +0100)
dockerapi-mailcow (mailcow/dockerapi:1.24) (Started on Tue, 08 Jan 2019 22:37:26 +0100)
clamd-mailcow (mailcow/clamd:1.16) (Started on Wed, 09 Jan 2019 06:35:02 +0100)
ipv6nat (robbertkl/ipv6nat) (Started on Wed, 09 Jan 2019 06:33:12 +0100)
netfilter-mailcow (mailcow/netfilter:1.21) (Started on Tue, 08 Jan 2019 22:37:22 +0100)
mysql-mailcow (mariadb:10.2) (Started on Tue, 08 Jan 2019 22:37:29 +0100)
redis-mailcow (redis:5-alpine) (Started on Tue, 08 Jan 2019 22:37:29 +0100)
acme-mailcow (mailcow/acme:1.45) (Started on Tue, 08 Jan 2019 22:37:25 +0100)
rspamd-mailcow (mailcow/rspamd:1.33) (Started on Tue, 08 Jan 2019 22:37:29 +0100)
watchdog-mailcow (mailcow/watchdog:1.32) (Started on Tue, 08 Jan 2019 22:37:28 +0100)`

**Comment by andryyy** [comment]
It says “not an error” in watchdog logs. The ipv6nat stuff is not an error. 

Please see the docs. docker-compose logs clamd-mailcow

**Comment by lgusewski** [comment]
Thanks, found and learned. Beginning by ipv6nat, this is what watchdog shows in the ui:

9.1.2019, 07:55:41 | IPv6 NAT | -1 | Health level: 0% (0/1)

Found in the clamav logs an missing file

clamd-mailcow_1      | 2019-01-09T06:50:18.685880811Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:50:18.699863847Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:50:18.717397934Z Wed Jan  9 07:50:18 2019 -> +++ Started at Wed Jan  9 07:50:18 2019
clamd-mailcow_1      | 2019-01-09T06:50:18.720640731Z Wed Jan  9 07:50:18 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:50:18.720913652Z Wed Jan  9 07:50:18 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:50:18.721180350Z Wed Jan  9 07:50:18 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:50:18.721406979Z Wed Jan  9 07:50:18 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:50:18.722005357Z Wed Jan  9 07:50:18 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:50:18.722253089Z Wed Jan  9 07:50:18 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:50:18.722481824Z Wed Jan  9 07:50:18 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:50:18.722714516Z Wed Jan  9 07:50:18 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:50:18.727162074Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:50:18.727431913Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:50:18.727657606Z Wed Jan  9 07:50:18 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:50:18.727856896Z Wed Jan  9 07:50:18 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:50:38.707475464Z /bootstrap.sh: line 66: kill: (20) - No such process
clamd-mailcow_1      | 2019-01-09T06:50:38.707778482Z Worker 20 died, stopping container waiting for respawn...
clamd-mailcow_1      | 2019-01-09T06:50:39.804803135Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:50:39.823886361Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:50:39.849849760Z Wed Jan  9 07:50:39 2019 -> +++ Started at Wed Jan  9 07:50:39 2019
clamd-mailcow_1      | 2019-01-09T06:50:39.856448167Z Wed Jan  9 07:50:39 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:50:39.856684034Z Wed Jan  9 07:50:39 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:50:39.856900153Z Wed Jan  9 07:50:39 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:50:39.857067294Z Wed Jan  9 07:50:39 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:50:39.858515411Z Wed Jan  9 07:50:39 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:50:39.858707962Z Wed Jan  9 07:50:39 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:50:39.858883863Z Wed Jan  9 07:50:39 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:50:39.859062889Z Wed Jan  9 07:50:39 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:50:39.866433590Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:50:39.866777454Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:50:39.867067560Z Wed Jan  9 07:50:39 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:50:39.867311443Z Wed Jan  9 07:50:39 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:50:59.837592015Z /bootstrap.sh: line 66: kill: (20) - No such process
clamd-mailcow_1      | 2019-01-09T06:50:59.838013547Z Worker 20 died, stopping container waiting for respawn...
clamd-mailcow_1      | 2019-01-09T06:51:01.111618654Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:51:01.122656657Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:51:01.137700583Z Wed Jan  9 07:51:01 2019 -> +++ Started at Wed Jan  9 07:51:01 2019
clamd-mailcow_1      | 2019-01-09T06:51:01.141451046Z Wed Jan  9 07:51:01 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:51:01.141665815Z Wed Jan  9 07:51:01 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:51:01.141874511Z Wed Jan  9 07:51:01 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:51:01.142142728Z Wed Jan  9 07:51:01 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:51:01.142605540Z Wed Jan  9 07:51:01 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:51:01.142813695Z Wed Jan  9 07:51:01 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:51:01.143001010Z Wed Jan  9 07:51:01 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:51:01.143186118Z Wed Jan  9 07:51:01 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:51:01.148113336Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:01.148290467Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:01.148495220Z Wed Jan  9 07:51:01 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:51:01.148689009Z Wed Jan  9 07:51:01 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:51:21.129870560Z /bootstrap.sh: line 66: kill: (19) - No such process
clamd-mailcow_1      | 2019-01-09T06:51:21.130104765Z Worker 19 died, stopping container waiting for respawn...
clamd-mailcow_1      | 2019-01-09T06:51:22.301436817Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:51:22.313662031Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:51:22.330291306Z Wed Jan  9 07:51:22 2019 -> +++ Started at Wed Jan  9 07:51:22 2019
clamd-mailcow_1      | 2019-01-09T06:51:22.333745774Z Wed Jan  9 07:51:22 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:51:22.333951864Z Wed Jan  9 07:51:22 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:51:22.334156537Z Wed Jan  9 07:51:22 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:51:22.334372966Z Wed Jan  9 07:51:22 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:51:22.334885241Z Wed Jan  9 07:51:22 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:51:22.335097725Z Wed Jan  9 07:51:22 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:51:22.335374957Z Wed Jan  9 07:51:22 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:51:22.335582840Z Wed Jan  9 07:51:22 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:51:22.339378666Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:22.339573869Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:22.339774389Z Wed Jan  9 07:51:22 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:51:22.339953497Z Wed Jan  9 07:51:22 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:51:42.321442087Z /bootstrap.sh: line 66: kill: (20) - No such process
clamd-mailcow_1      | 2019-01-09T06:51:42.321829391Z Worker 20 died, stopping container waiting for respawn...
clamd-mailcow_1      | 2019-01-09T06:51:43.743432981Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:51:43.769461918Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:51:43.798841554Z Wed Jan  9 07:51:43 2019 -> +++ Started at Wed Jan  9 07:51:43 2019
clamd-mailcow_1      | 2019-01-09T06:51:43.806636579Z Wed Jan  9 07:51:43 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:51:43.806939977Z Wed Jan  9 07:51:43 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:51:43.807145876Z Wed Jan  9 07:51:43 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:51:43.807448437Z Wed Jan  9 07:51:43 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:51:43.808016215Z Wed Jan  9 07:51:43 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:51:43.808264904Z Wed Jan  9 07:51:43 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:51:43.808436630Z Wed Jan  9 07:51:43 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:51:43.808658219Z Wed Jan  9 07:51:43 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:51:43.818613978Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:43.818843281Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:51:43.819069854Z Wed Jan  9 07:51:43 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:51:43.819277258Z Wed Jan  9 07:51:43 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:52:03.781173978Z /bootstrap.sh: line 66: kill: (19) - No such process
clamd-mailcow_1      | 2019-01-09T06:52:03.781450070Z Worker 19 died, stopping container waiting for respawn...
clamd-mailcow_1      | 2019-01-09T06:52:05.774976620Z The user `clamav' is already a member of `tty'.
clamd-mailcow_1      | 2019-01-09T06:52:05.790502472Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-09T06:52:05.805659168Z Wed Jan  9 07:52:05 2019 -> +++ Started at Wed Jan  9 07:52:05 2019
clamd-mailcow_1      | 2019-01-09T06:52:05.808543954Z Wed Jan  9 07:52:05 2019 -> Received 0 file descriptor(s) from systemd.
clamd-mailcow_1      | 2019-01-09T06:52:05.808756694Z Wed Jan  9 07:52:05 2019 -> clamd daemon 0.101.1 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
clamd-mailcow_1      | 2019-01-09T06:52:05.808957608Z Wed Jan  9 07:52:05 2019 -> Running as user clamav (UID 700, GID 700)
clamd-mailcow_1      | 2019-01-09T06:52:05.809157249Z Wed Jan  9 07:52:05 2019 -> Log file size limited to 1048576 bytes.
clamd-mailcow_1      | 2019-01-09T06:52:05.809606702Z Wed Jan  9 07:52:05 2019 -> Reading databases from /var/lib/clamav
clamd-mailcow_1      | 2019-01-09T06:52:05.809816103Z Wed Jan  9 07:52:05 2019 -> Not loading phishing signatures.
clamd-mailcow_1      | 2019-01-09T06:52:05.810016542Z Wed Jan  9 07:52:05 2019 -> Bytecode: Security mode set to "TrustSigned".
clamd-mailcow_1      | 2019-01-09T06:52:05.810230627Z Wed Jan  9 07:52:05 2019 -> Disabling URL based phishing detection.
clamd-mailcow_1      | 2019-01-09T06:52:05.814168573Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:52:05.814326834Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-09T06:52:05.814568917Z Wed Jan  9 07:52:05 2019 -> ERROR: Can't open file or directory
clamd-mailcow_1      | 2019-01-09T06:52:05.814725001Z Wed Jan  9 07:52:05 2019 -> !Can't open file or directory

**Comment by andryyy** [comment]
ipv6nat is not an error, it is okay, it checks the start date of ipv6nat and restarts it when it was not the last started container (+30s).

Don't know why this file is missing for you, but run `git checkout data/conf/clamav/whitelist.ign2`.

**Comment by lgusewski** [comment]
Thanks, that solves the problem. I also have no idea, because my latest update was from 02.01.2019. Only the changes for the backup files where not installed. And i made my update every time with the update.sh script from mailcow.

**Comment by lgusewski** [comment]
I had the problem again. Today i make an ./update.sh in my mailcow folder as root and after the restart of mailcow and the whole system, my clamd container was broken again. I had a look into the logs:

clamd-mailcow_1      | 2019-01-12T17:01:00.630567807Z dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | 2019-01-12T17:01:00.665174674Z Sat Jan 12 18:01:00 2019 -> !Can't open file or directory
clamd-mailcow_1      | 2019-01-12T17:01:00.665379761Z LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | 2019-01-12T17:01:00.665401326Z LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
root@pasture:/opt/mailcow-dockerized# cd data/conf/clamav/
root@pasture:/opt/mailcow-dockerized/data/conf/clamav# ls
clamd.conf  freshclam.conf  whitelist.ign2
root@pasture:/opt/mailcow-dockerized/data/conf/clamav# ls -l
insgesamt 12
-rw-r--r-- 1 root root 878 Jan 12 17:41 clamd.conf
-rw-r--r-- 1 root root 330 Jan 12 17:41 freshclam.conf
-rw-r--r-- 1 root root  27 Okt 14 16:28 whitelist.ign2
root@pasture:/opt/mailcow-dockerized/data/conf/clamav# ~

So the file was there. I made again the manual git checkout, but perhaps it was not really necessary. I also make again an ./update.sh and then after the restart of all containers, mailcow was health again.

Have nobody else the same problems? My cow was ok up to the changes 2019-01-02. After this the problem began. My OS is a Ubuntu 18.04.01 LTS with all updates applied. It based on the minimal server version and i only installed docker manually like in the mailcow docs written in the install process. Nothing else and no other changes of the system.

**Comment by andryyy** [comment]
No. I’m not seeing this on any machine.

**Comment by lgusewski** [comment]
Anything i can check before or after next update, to prevent that this problem comes up again?

**Comment by andryyy** [comment]
I have checked every single machine with mailcow and could only reproduce it on one. Strange. But it is indeed a permission error. O_O I have no idea why others don't fail.

**Comment by lgusewski** [comment]
I saw that you merged changes for clamd. I made the update and this time the container starts normal. I also tested a complete reboot of my server, and also this time it starts fine.
