### ISSUE TITLE
Error "Sender address rejected: not owned by user" in SOGo when sending via additional imap account.

### ISSUE THREAD

**Issue by Questlog** [mailcow/mailcow-dockerized#2164]
**Describe the bug**
I've added an imap account of an external mailbox with the SOGo interface.
Sending an email with this account will fail and SOGo shows this error message: "Sender address rejected: not owned by user".

It will only work if I disable the sender check completely in the mailcow UI.

**Postfix Logs**
The only logs I could find are in Postfix. Here, Mailcow/SOGo runs on "foo.de", the imap mailbox is "bar.de".
`
NOQUEUE: reject: RCPT from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]: 553 5.7.1 <me@bar.de>: Sender address rejected: not owned by user me@foo.de; from=<me@foo.de> to=<someone@baz.com> proto=ESMTP helo=<99151bf16618>`

**How to reproduce Reproduce**
1. Fresh installation, fresh mailbox, open SOGo
2. Add an external imap account to SOGo
3. Send a mail with this imap account

**Expected behaviour**
I would have expected to be able to send mails with an imap account that has been added in the SOGo interface. It's strange that it's doing a sender check at this place.

**Comment by andryyy** [comment]
SOGo always uses our SMTP. This is a known limitation of SOGo. You can only add IMAP accounts but not SMTP accounts.

**Comment by flixbi** [comment]
@andryyy do you know if an SMTP feature is planed for implementation i.F.? 
It's nice to receive mails from external accounts in one SOGo instance, 
but also sending them would fullfill the whole experience. (Like an self-hosted Web-Thunderbird)

**Comment by andryyy** [comment]
Don't know. :( But it would indeed be cool.

**Comment by theoneandonly-vector** [comment]
just having this issue. is there a way to allow my user to send from another user (on the same mailcow)?
Edit:
Just had to allow th euser to send from the other address in this users mailcow-settings

**Comment by MichaelSasser** [comment]
> @theoneandonly-vector:  Just had to allow th euser to send from the other address in this users mailcow-settings

I can confirm, this works with SOGo. Thanks for the workaround!

**Comment by colorprint** [comment]
> just having this issue. is there a way to allow my user to send from another user (on the same mailcow)? Edit: Just had to allow th euser to send from the other address in this users mailcow-settings

as external email addresses? But it requires import of DKIM as well in that case...
