### ISSUE TITLE
Update corrupt Roundcube documentation

### ISSUE THREAD

**Issue by aptly-io** [mailcow/mailcow-dockerized#2165]
The Roundcube installation documentation is corrupted (by a c 'n p of too long lines?) [here](https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/)
for the content of the file `data/web/rc/config/config.inc.php`  

Next when pointing to the install link `https://myserver/rc/installer`I get:  
```
Parse error: syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /web/rc/config/config.inc.php on line 7
```
At least lines 4 & 7 seem invalid:

```php
file_put_contents("/tmp/mime.types", fopen("http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/con$

$config['db_dsnw'] = 'mysql://' . getenv('DBUSER') . ':' . getenv('DBPASS') . '@mysql/' . getenv('DBNA$
```

**Comment by andryyy** [comment]
Oops. Will fix it in a bit. 

Edit: Fixed, thanks!
