### ISSUE TITLE
Kein Posteingang (IMAP)

### ISSUE THREAD

**Issue by YourGameSpace** [mailcow/mailcow-dockerized#2169]
Hallo,

ich habe bereits zwei Tage damit verbracht eine Lösung für das Problem zu finden, jedoch konnte ich diese bisher nicht finden. Daher hoffe ich das mir hier weitergeholfen wird.

Beschreibung des Problems:
Alle Konten (=Mailboxen) erhalten keine E-Mails, die von externen Anbietern (z.B. GMX, Google Mail, etc.) aus gesendet werden. Nachricht senden funktioniert ohne Probleme, jedoch der Empfang nicht.

Ich habe versucht eine E-Mail zu senden, und habe dann diese Fehlermeldung von dem externen Anbieter erhalten: http://prntscr.com/m5xwve

Dann habe ich das ganze erneut versucht und mir danach die Log-Datei (Postfix) angeschaut, dabei kam dies raus: 1. http://prntscr.com/m5xyeu 2. http://prntscr.com/m5xxv0

DNS-Einstellungen meiner Domain:

A - mail.XXX -> 207.180.243.XXX
MX - mail.XXX -> mail.XXX
TXT - @ -> v=spf1 mx ~all
TXT - dkim._domainkey -> v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjAXXXXXXXXXX
CNAME - autodiscover. -> mail.XXX
CNAME - autoconfig -> mail.XXX

**Comment by andryyy** [comment]
Die Logs sind so nicht brauchbar. Bitte alle Logs posten und auch einen vernünftigen Reject anhängen. 

Sieht aber auch so aus als fehle der MX für die Domain. Der MX scheint nur für die Subdomain mail.domain.tld gesetzt zu sein.

**Comment by YourGameSpace** [comment]
Wo genau finde ich die Log-Datein, damit ich alles kopieren kann?

Zu dem MX Eintrag in der Domain: Ich habe für meine Domain (mail.XXX.de) einen MX Eintrag gemacht, so wie ich es zumindest in der Anleitung gefunden habe. (Anleitung: https://www.bennetrichter.de/anleitungen/mailcow-dockerized/) Für die eigentliche Domain (ohne Subdomain) habe ich grade einen erstellt, jedoch ist es dann nicht mehr möglich E-Mails zu senden, was vorher möglich war. Dazu erhalte ich diesen Fehler: http://prntscr.com/m62fry

**Comment by hachre** [comment]
Der MX ist falsch eingetragen. Du benutzt scheinbar einen Anbieter mit einer Maske wo man am Ende hinter den Hostnamen im MX Eintrag einen `.` eingeben muss. Dieser fehlt.

**Comment by YourGameSpace** [comment]
Also mein MX Eintrag (mail.XXX.XX) sieht derzeit (siehe unten) so aus. Dieser leitet dann wieder an mail.XXX.XX

http://prntscr.com/m67ey1

Was genau muss ich dort jetzt ändern? Bzw. wo soll jetzt der . hin?

**Comment by andryyy** [comment]
Den Namen.

Bitte frag deinen ISP.

**Comment by YourGameSpace** [comment]
Ich habe nun folgendes gemacht (siehe Screenshot: http://prntscr.com/m67jfy) und warte nun ein wenig, bis die Änderungen übernommen wurden und teste das ganze dann erneut.

**Comment by weingaertnerit** [comment]
Unter Name des Eintrags sollte die gesamte Domain mit Punkt am Ende. Also laut dem Printscreen:
buildmine.net.

Prüfen kannst Du im Anschluß über mxtoolbox.com, ob ein MX gefunden wird, aktuell nicht. Oder über Deinen vServer mit dig MX buildmine.net

**Comment by hachre** [comment]
> Was genau muss ich dort jetzt ändern? Bzw. wo soll jetzt der . hin?

So wie der Fehler aussah, als ich geschaut habe, müsste er auf jeden Fall nach der Domain die du bei "Wert" eingestellt hast rein. Aber es könnte sein, dass er zusätzlich auch bei "Name" rein muss. In diesem Fall muss der Hostname aber ausgeschrieben sein: `mail.example.com.` nicht nur `mail.`. Das kann dir aber nur dein DNS Anbieter genau sagen.

Also du kannst versuchen folgende 2 MX Einträge anzulegen:
Name: `buildmine.net.`
Wert: `mail.buildmine.net.`
 und
Name: `mail.buildmine.net.`
Wert: `mail.buildmine.net.`
