### ISSUE TITLE
No Logon in Nextcloud after Update

### ISSUE THREAD

**Issue by Icki153** [mailcow/mailcow-dockerized#2172]
Hello,

new issue from me. After January update i noticed that you have build an -update switch for nextcloud helper script. I used it and update worked fine. But now i can not login. In nextcloud.log i found this error.

`message":"Login failed: 'user@testdomain.de' (Remote IP: '85.212.75.150')","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.2.0"}
{"reqId":"YmfTOTnxN2tIhVcDGYlb","level":3,"time":"2019-01-12T20:45:29+00:00","remoteAddr":"85.212.75.150","user":"--","app":"core","method":"GET","url":"\/index.phpr=user@testdomain.de","message":"User backend OC_User_IMAP not found.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.2.0"}
`

**Comment by andryyy** [comment]
The update did run without any errors?

Try:
```
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ --no-warnings app:install user_external"
```

**Comment by Icki153** [comment]
I reverted my snapshot and did it again. I have found following error.

> Disabled incompatible app: user_external

If i try the app install then it says 

> user_external already installed

**Comment by andryyy** [comment]
And
```
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ --no-warnings app:enable user_external"
```
?

**Comment by Icki153** [comment]
It also not working. Error is

> In Installer.php line 117:
> App "External user support" cannot be installed because it is not compatible with this version of the server.

So i looked at nextcloud issues and there i found at github that they releases a new version of the app "user_external" and the old is deprecated.

So i get it to work when i do 

` docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ --no-warnings app:remove user_external"
`

and then

`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ --no-warnings app:install user_external"
`

after that the login worked like before.

Is it possible to update the docs to include the parameters of nextcloud helper script and to give other users the hints of this issue?

**Comment by Icki153** [comment]
After login and look at the hints from nextcloud i decided to rollback to NC14 because there are to many issues and i have to wait for new update of nextcloud. Also there nginx related issues that i have always ignored. But they must fixed in the config. Also after every update i must update the indices in the database with following command

`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "/web/nextcloud/occ --no-warnings db:add-missing-indices"`

Here are the hints from nextcloud: (indices was fixed before screenshot)

![image](https://user-images.githubusercontent.com/36890363/51078823-e8169400-16bb-11e9-8ede-7c3565ec6a81.png)

**Comment by andryyy** [comment]
I removed the update functionality. Just update manually.

**Comment by andryyy** [comment]
Also there nginx related issues that i have always ignored. 

The Nginx X-Frame-Options header is set by Nginx _and_ Nextcloud. For whatever reason they want you to remove it from Nginx and set it via PHP. So we have it twice and Nextcloud complains. This does not happen when you install as subdomain.

The integrity check may fail when you have old/previous files in your nextcloud directory, remove them.

We use a correct referrer-policy, your site.conf is probably outdated, just git-checkout the correct/new site.conf.

I have seen the filecache stuff and added it to the install script. Will push it now. :)

**Comment by andryyy** [comment]
Btw: Upgrading to v15 is such a pita because they moved user_external. :(

**Comment by Icki153** [comment]
Ok i will check my nextcloud.conf.

The integrity fail appears only if i used the upgrade within the helper script.

Why did you remove updater folder? If i use the command line to manually upgrade with the updater.phar then the upgrade working. The only thing to do is to install the user_external addon, check indices and upgrade the db. We can check with update parameter which version is currently installed copy the updater folder from the version to nextcloud folder and then run the update with following command:

`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/updater/updater.phar"`

After that we check if version is 15 and when it is then install the user external app and run the command for db update. Indices update is always needed. After that we can remove the updater folder to remove update function from nextcloud.

When decided to do it this way then we definitely need to document it.

**Comment by MoritzWeber0** [comment]
Is it working now? Is it possible to update Nextcloud without problems?

**Comment by andryyy** [comment]
I think you should disable users_external before upgrading.

**Comment by Icki153** [comment]
Thats not really working because they replace the addon. So you can update but must deinstall the user-external and reinstall it. You can update it with the steps i describe 2 posts before.

**Comment by andryyy** [comment]
Yes, disable and remove. :)

**Comment by MoritzWeber0** [comment]
Thank you very much for your help. 

I ran into another problem. When I call the web interface an error message appears: 
"This version of Nextcloud is not compatible with > PHP 7.2.
You are currently running 7.3.1."

This means that I do not have access to the web based updater. How can I update nextcloud then?

**Comment by andryyy** [comment]
Try this https://github.com/mailcow/mailcow-dockerized/issues/2328#issuecomment-463785523

It contact me tomorrow. I can fix it for you.

**Comment by Braintelligence** [comment]
@TechMoritz @Icki153 Is your problem fixed?

**Comment by Icki153** [comment]
I did it the way i described few posts before.
But its not really fixed.
