### ISSUE TITLE
Show email subjects in quarantine tab in Mailcow UI

### ISSUE THREAD

**Issue by friedPotat0** [mailcow/mailcow-dockerized#2175]
It would be very useful to display the subjects of the mails quarantined directly in a separate column in the table of the Mailcow UI quarantine tab. This would make the selection of spams a lot easier. At the moment you have to open the details page of any mail to check if it's spam or not. If the subject would be displayed directly in the main table, many spam mails could be identified and marked without the need to open the details page.

**Comment by andryyy** [comment]
Yes, that would be better indeed.

I proposed a change to metadata_exporter. If it's merged, we can easily (without parsing the raw content) add it to the table.

**Comment by andryyy** [comment]
Fixed by d6efc2fcd3fd050f678dcb3392e43cc8ea0b750d
