### ISSUE TITLE
Roundcube password change results in login error `SSHA256 password is too short`

### ISSUE THREAD

**Issue by zeigerpuppy** [mailcow/mailcow-dockerized#2176]
I have enabled the password change plugin in Roundcube, following the instructions [here](https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/).
Roundcube reports `successfully saved` when changing the password, but after the password change, the user can no longer log in to the email address.

Is it possible that the hash/salt format has changed and not been updated in the docs?

Logs show the error:

```
mail dovecot: auth-worker(24384): Error: cache(user@serve.net,172.22.1.8,<cKFrwmN/sMKGGgEI>): Invalid password in passdb: SSHA256 password is too short
```

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. enable password change plugin as per docs
2. change password in Roundcube
3. attempt to log in to mail account with client (SoGo or Roundcube)

**Expected behavior**
Password change should report error if the password will be invalid

**System**
 - OS: Mailcow running in docker on Debian 9
 - Browser: Firefox

**Additional**
- [x] updating password from SoGo works fine
- [x] updating password from Mailcow UI works fine

**Comment by andryyy** [comment]
It is missing the SOGo static view refresh.

No time to add that to the docs.

**Comment by zeigerpuppy** [comment]
OK, not quite sure what that means.
I thought Roundcube would write the hashed password to the mysql DB and that dovecot would then test auth from there.  How is SOGo involved?

**Comment by andryyy** [comment]
```
  $stmt = $pdo->query("SELECT 'OK' FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'sogo_view'");
  $num_results = count($stmt->fetchAll(PDO::FETCH_ASSOC));
  if ($num_results != 0) {
    $stmt = $pdo->query("REPLACE INTO _sogo_static_view (`c_uid`, `domain`, `c_name`, `c_password`, `c_cn`, `mail`, `aliases`, `ad_aliases`, `kind`, `multiple_bookings`)
      SELECT `c_uid`, `domain`, `c_name`, `c_password`, `c_cn`, `mail`, `aliases`, `ad_aliases`, `kind`, `multiple_bookings` from sogo_view");
    $stmt = $pdo->query("DELETE FROM _sogo_static_view WHERE `c_uid` NOT IN (SELECT `username` FROM `mailbox` WHERE `active` = '1');");
  }
```

**Comment by zeigerpuppy** [comment]
thanks @andryyy 
Where should I place this code?

**Comment by andryyy** [comment]
That’s the part where it fails. But. We could try to change both tables in RC. I will check it.
