### ISSUE TITLE
Documentation: exampe http --> https redirect does not work

### ISSUE THREAD

**Issue by wedi** [mailcow/mailcow-dockerized#2177]
I tried the [http redirect example](https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/) from the docs but it causes an error.

```
nginx-mailcow_1      | nginx: [warn] conflicting server name "autodiscover.*" on 0.0.0.0:80, ignored
nginx-mailcow_1      | 2019/01/14 12:26:17 [warn] 1#1: conflicting server name "autoconfig.*" on 0.0.0.0:80, ignored
nginx-mailcow_1      | nginx: [warn] conflicting server name "autoconfig.*" on 0.0.0.0:80, ignored
nginx-mailcow_1      | 2019/01/14 12:26:17 [warn] 1#1: conflicting server name "autoconfig.*" on [::]:80, ignored
nginx-mailcow_1      | nginx: [warn] conflicting server name "autoconfig.*" on [::]:80, ignored
nginx-mailcow_1      | 2019/01/14 12:26:17 [warn] 1#1: conflicting server name "mail.example.com" on [::]:80, ignored
```
The reason is, that the example redeclares the domains to listen for on port 80 because 
The main `server` block includes all domains via `include /etc/nginx/conf.d/server_name.active;` and listens on port 80: `include include /etc/nginx/conf.d/listen_plain.active;`
Removing this line makes things better but there is still an error, as the second block of the example redeclares the first one as well by including `include /etc/nginx/conf.d/server_name.active;`.
Manually adding the server_name directive from `include /etc/nginx/conf.d/server_name.active;` without `autoconfig.*;` fixes everything.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
Follow the [http redirect example](https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/).

**System**
 - OS: Debian Stretch
 - Docker: 18.09.1
 - Mailcow: Latest master

**Comment by andryyy** [comment]
It still works, just annoying. :)
