### ISSUE TITLE
Question: How can I search logs older than the ones in memory (last 10k)?

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#2178]
Hello,
Maybe this is a silly question, but I'm still learning the ins and outs of docker, so any help is appreciated.

**How can I search logs older than the ones in memory (last 10k)?**
Or, where are the persistent log files?

Specifically, I'm looking for **postfix** logs and **rspamd**.

Thank you very much.

**Comment by mkuron** [comment]
There are no persistent log files, only the ones managed by Docker (`docker-compose logs`) that are cleared when a container is restarted. You can reconfigure Docker in /etc/docker/daemon.json to log to syslog or some other persistent storage.
