### ISSUE TITLE
Disable GAL for specific domain

### ISSUE THREAD

**Issue by kallenp** [mailcow/mailcow-dockerized#2179]
Can I disable a global directory for a specific domain? I do not want users to see each other within one domain.

**Comment by andryyy** [comment]
Search the issues please. You’d need to change the bootstrap.sh file of SOGo. So while it is possible, it is not upgrade-safe.

**Comment by kallenp** [comment]
OK, but when I change bootstrap.sh file, it will affect all my mailcow domains. But I am need it only for one domain only. Is it solvable ?

**Comment by andryyy** [comment]
You can change the bootstrap script to only skip it for some domains.
I think you would also need to disable auto complete in other places to completely hide other users.

**Comment by kallenp** [comment]
Requested feature was added to WebUI.

Thanks ! 👍
