### ISSUE TITLE
Outlook not syncing my addressbook

### ISSUE THREAD

**Issue by kallenp** [mailcow/mailcow-dockerized#2180]
Outlook (EAS) does not synchronize my contacts. 
Some idea ?

**Comment by andryyy** [comment]
No.

**Comment by kallenp** [comment]
Why  ? It does not work ? Or where is problem ? Emails and calendars works perfect.

**Comment by andryyy** [comment]
There is no information from your side. No OS, client info, logs, config changes etc. 

You can enable SOGos debugging for EAS and check the SOGo logs.

**Comment by kallenp** [comment]
Thanks for your time and patience with me. 

My problem is only with Outlook contacts / address book sync. My Environment is Windows 10 Prof with Outlook 2016 Professional installed. Not Office 365 version. I have a problem with synchronization of my addressbook and GAL. It's not working. Emails and Calendars works perfectly. My outlook is synchronized / connected to MailCow by EAS. In any other clients I don't have problem with synchronization. Problem is only Microsoft Outlook. Apple iOS, macOS and emClient works perfect too. 

Linux: Debian 9 Stretch
Docker version: 18.09.1, build 4c52b90
MailCow modifications: default installation without any modification

Please, any idea what I can try or how to troubleshoot (and solve) my problem ?

**Comment by andryyy** [comment]
SOGo logs for EAS (debugging enabled) would be interesting. We don't provide SOGo client support via GitHub, though. They have a dedicated bug tracker.

**Comment by kallenp** [comment]
The problem was in my application firewall and its cache. When I delete and restart it, everythings work well. This problem was local and it is not mailcow problem. Verry verry thanks for your response, time and patience with me and BIG thanks to golden_reciver on IRC channel for help with troubleshooting.

This issue may be closed.
