### ISSUE TITLE
Mailcow volumes in NFS?

### ISSUE THREAD

**Issue by fawzibr** [mailcow/mailcow-dockerized#2184]
Some time ago I asked about keeping [Mailcow volumes in other directory](https://github.com/mailcow/mailcow-dockerized/issues/1455) and the solution worked great.

Now tried the same but keeping the volumes in NFS, and it wasn't working. After trying a lot of things It seems mailcow does not like the mysql-vol-1 in NFS (getting lots of "Waiting for SQL" messages). All other volumes seem to work ok (at least it runs). I know it is possible to keep the data/log in NFS. 

Is there a way to do it or should I just keep the database in the disk.

**Comment by mkuron** [comment]
It‘s possible that MySQL (and Redis and Dovecot and Postfix) don‘t like to have their databases/datastores/queues on remote disks when in their default configuration. So check what the individual software‘s documentation says about NFS and adapt the configuration as necessary. For a start, have a look at Mailcow‘s log messages (`docker-compose logs mysql-mailcow`) to see why the database isn‘t coming up.

**Comment by lucianlazar1983** [comment]
Could also be a POSIX problem. Depending on how you setup your NFS server and hou you mount the share on your host, mysql container could not have the privileges for setting up correct ownership and permissions on objects/logs. Even if it's slower, most of the time mounting it with V3 instead of V4 could solve some issues. Otherwise see the list of available flags for V4.

**Comment by fawzibr** [comment]
I'm asking about this because I'm running mailcow in an Ubuntu VM and want to know which volumes actually store a lot of data to see if I can move only those to NFS.

I'm actually moving this volume to NFS since I guess this would be the largest one:
-   vmail-vol-1 - Maildir storage
-   vmail-attachments-vol-1 - (Edit: this one was missing, i guess this one is also large)

These I plan to keep on the VM since I imagine they are small:
-   mysql-vol-1 - Information about domains/users
-   redis-vol-1 - Settings
-   rspamd-vol-1 - spam/av stuff
-   postfix-vol-1 - smtp server (uses, vmail-vol-1 for storage, so rest is small?)
-   crypt-vol-1 - dont know about this, documentation says keeps keys for decrypting, so also small?

Correct me if any info about the volume sizes is wrong.
Thanks in advance

**Comment by badsmoke** [comment]
Hello, I'm just going to join in the conversation. At the moment I have a similar structure. Ubuntu VM and an NFS memory on the "vmail-vol-1" and  "vmail-attachments-vol-1" are stored.

This works 98% well, but there are always permission problems.

`imap(NAME@DOMAIN.com)<7038><nQKzUTCAzMysFgH4>: Error: Mailbox INBOX: open(/var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a) failed: Permission denied (euid=5000(vmail) egid=5000(vmail) missing +r perm: /var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a stat(/var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a) failed: Permission denied)`

But the permissions are set correctly:

`-rw-rw-rw- 1 vmail vmail    16135 Jan 24 07:11 1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a`

Usually the user can access it again after some time, but this can take different lengths of time. Of course this is annoying with important emails.

I have mounted the NFS and linked a softlink from `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1` to the mount item

The NFS share was mounted as follows: 
`IP:/volume1/Mail /mnt/mailv4 nfs nfsvers=4,minorversion=1,noac,rw 0 0`



I hope you can help me.

**Comment by lucianlazar1983** [comment]
> Hello, I'm just going to join in the conversation. At the moment I have a similar structure. Ubuntu VM and an NFS memory on the "vmail-vol-1" and "vmail-attachments-vol-1" are stored.
> 
> This works 98% well, but there are always permission problems.
> 
> `imap(NAME@DOMAIN.com)<7038><nQKzUTCAzMysFgH4>: Error: Mailbox INBOX: open(/var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a) failed: Permission denied (euid=5000(vmail) egid=5000(vmail) missing +r perm: /var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a stat(/var/vmail/DOMAIN.com/NAME/cur/1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a) failed: Permission denied)`
> 
> But the permissions are set correctly:
> 
> `-rw-rw-rw- 1 vmail vmail 16135 Jan 24 07:11 1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a`
> 
> Usually the user can access it again after some time, but this can take different lengths of time. Of course this is annoying with important emails.
> 
> I have mounted the NFS and linked a softlink from `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1` to the mount item
> 
> The NFS share was mounted as follows:
> `IP:/volume1/Mail /mnt/mailv4 nfs nfsvers=4,minorversion=1,noac,rw 0 0`
> 
> I hope you can help me.


Please try mounting the share if possible with: "nfsvers=3"

**Comment by badsmoke** [comment]
Thanks for the quick feedback, with NFS v3 the problem occurs the same way

**Comment by andryyy** [comment]
Check the NFS export. What does it look like?

**Comment by lucianlazar1983** [comment]
I think it has to do with the mapping of the UID and GID. In version 3, you can "trick" the NFS server and map an existing user UID and GID as anonymous, no matter which user writes into that NFS share.
The options for that export share would be: all_squash,anonuid=xxxx,anongid=xxxx (where xxxx is the uid/gid of the user to map to). 
In version 4, i think you must alter rpc.idmapd in order to correctly map and send the UID and GID to the server.

**Comment by badsmoke** [comment]
the NFS server is a synology NAS.
With Squash: none mapping
Security: sys
not asynchronous

On the NFS server directly the correct IDs are located (5000:5000)

**Comment by wedi** [comment]
I am using mailcow with NFSv3 (Google's Cloud Filestore) as well. I set `nordirplus,noatime` as aditional mount options.
* postfix: I decided to use local storage as it's ephemeral data only. Read http://www.postfix.org/NFS_README.html
* dovecot: I decided to mount the index files on local storage and the maildir files on nfs. I suggest reading https://wiki2.dovecot.org/NFS.

From my experience everything else should "just work".

**Comment by badsmoke** [comment]
I switched back to NFS v3 and made the settings you said. Unfortunately, there is no improvement and still the same error messages occur

**Comment by wedi** [comment]
> But the permissions are set correctly:
> 
> `-rw-rw-rw- 1 vmail vmail 16135 Jan 24 07:11 1548313880.M715669P1780.DOMAIN.com,S=37852,W=38429:2,a`

Something has definitely messed with permissions here. Per default this file would be 600, not world r/w. uid/gid should be 5000. Double check with `ls -n`.

> I have mounted the NFS and linked a softlink from `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1` to the mount item
> 
This sounds disturbing to me. Use a bind mount to the host dir instead of linking arround dockers named volume directories.

**Comment by andryyy** [comment]
Yes, the permissions are definitely broken. mailcow does not do that. Either the Synology is doing that or your server.

**Comment by badsmoke** [comment]
thanks for your help. The rights are automatically set to global r/w. It's really set to 5000:5000 I've already checked this several times.

Global r/w should not be the problem. 

Can you please explain how exactly you mean that?

> Use a bind mount to the host dir instead of linking arround dockers named volume directories.

**Comment by wedi** [comment]
> Global r/w should not be the problem.

No but it is a strong hint that something - which is not mailcow itself - messes with your permissions.


> Can you please explain how exactly you mean that?
> 
> > Use a bind mount to the host dir instead of linking arround dockers named volume directories.

Sure. Do not link the directory docker created under `/var/lib/docker/...` for the named volume listed in the `volume` section of your docker-compose.yml. Instead change the volume definition to a bind mount which points directly to your locally mounted nfs volume. Check [this SO answer](https://stackoverflow.com/a/49920624) to see how to do it.

**Comment by fawzibr** [comment]
> 
> 
> thanks for your help. The rights are automatically set to global r/w. It's really set to 5000:5000 I've already checked this several times.
> 
> Global r/w should not be the problem.
> 
> Can you please explain how exactly you mean that?
> 
> > Use a bind mount to the host dir instead of linking arround dockers named volume directories.

Check the original message in [Mailcow volumes in other directory](https://github.com/mailcow/mailcow-dockerized/issues/1455). It shows how to do it. The example does not have the vmail-attachments-vol-1 directory. Remember to add it.

**Comment by badsmoke** [comment]
thanks for your support, i have now integrated the nfs mount as described.

Unfortunately there is no improvement the bugs still occur.


I could now watch live what this looks like:

from the mail server:

```

?????????? ? ?    ?           ?            ? '1549125076.M336954P5631.DOMAIN.com,S=47589,W=48026:2,b'
?????????? ? ?    ?           ?            ? '1549134869.M321063P10644.DOMAIN.com,S=83410,W=85254:2,Sb'
?????????? ? ?    ?           ?            ? '1549185949.M849508P477.DOMAIN.com,S=66601,W=68145:2,b'
?????????? ? ?    ?           ?            ? '1549208434.M813339P10929.DOMAIN.com,S=11068,W=11229:2,Sb'
?????????? ? ?    ?           ?            ? '1549214850.M126662P14048.DOMAIN.com,S=9082,W=9245:2,Sb'


```

on the Synology nfs:


```
-rw-rw-rw- 1 5000 5000    15451 Feb  2 17:31 1549125076.M336954P5631.DOMAIN.com,S=47589,W=48026:2,b
-rw-rw-rw- 1 5000 5000    25984 Feb  2 20:14 1549134869.M321063P10644.DOMAIN.com,S=83410,W=85254:2,Sb
-rw-rw-rw- 1 5000 5000    23499 Feb  3 10:25 1549185949.M849508P477.DOMAIN.com,S=66601,W=68145:2,b
-rw-rw-rw- 1 5000 5000     8213 Feb  3 16:40 1549208434.M813339P10929.DOMAIN.com,S=11068,W=11229:2,Sb
-rw-rw-rw- 1 5000 5000     6491 Feb  3 18:27 1549214850.M126662P14048.DOMAIN.com,S=9082,W=9245:2,Sb
```
















I also tried several squash options on synology.
Unfortunately all options (Map root to admin, Map all users to admin Map root to guest,Map all users to guest ) except the active "no mapping" lead to the fact that dovercot cannot start because it has no rights:



`
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.com.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.com.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/global.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/jUSER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/global.sieve': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve/USER@DOMAIN.svbin': Operation not permitted
chown: changing ownership of '/var/vmail/sieve': Operation not permitted
`

**Comment by wedi** [comment]
Looks like the execute bit is missing.

**Comment by badsmoke** [comment]
> Looks like the execute bit is missing.

What problem now directly?

for the "Operation not permitted chown: changing ownership of " problem? there's the execution bit is set

**Comment by wedi** [comment]
> > Looks like the execute bit is missing.
> 
> What problem now directly?
> 
> for the "Operation not permitted chown: changing ownership of " problem? there's the execution bit is set

The question marks made me think it might be missing. No idea then.

**Comment by badsmoke** [comment]
after i set the mount option "noac" the errors became less again and i couldn't see the phenomenon that "no access rights" are set anymore.

But I gave it up now, the email storage will be saved locally as long as there is enough space.

Thanks again for your help.

**Comment by wedi** [comment]
One last idea: Does the user you are mounting the nfs volume with have the permissions to change file permissions on the share? Or might synology prevent these changes for child safety reasons?

**Comment by w1k1n9cc** [comment]
Maybe, you can do something similiar to me. This method adds a little bit of overhead but it should be okay.
I store the vmail and attachment volume of mailcow on a samba share. On a samba share is no real permission managment possible and so I created a sparse image with ext4 inside. There I created a directory and use this for mailcow. Some overhead is being added through the additional filesystem but I didn't noticed anything bad yet.
The database shouldn't be stored remotely for performance reasons.

**Comment by andryyy** [comment]
Funny idea... :) 

I just got my hands on Synology myself and it is indeed a mess regarding NFS. You can't even create a user with a custom UID/GID, it just creates users with a UID > 65xxx. 

Just use iSCSI or go for @w1k1n9cc's idea.

**Comment by feldsam** [comment]
https://anto.online/other/how-to-mount-an-nfs-share-into-a-container/
