### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by Zyplonox** [mailcow/mailcow-dockerized#2186]
Is it possible to give the containers static IPs? Its just one line of code and at least for the MySQL container it would be greate becaus 3rd apps like AfterLogic needs the MySQL connection. At the moment after every update you have to look wich new IP the container has and update the configuration files...

**Comment by ntimo** [comment]
You can simply use the container name ```mysql```. If you are using a external network you could use ```mysql-mailcow```. 

Docker will then give you the correct container ip back via DNS.

**Comment by Zyplonox** [comment]
Worked. Thank you.
