### ISSUE TITLE
clamd-mailcow stucks in reboot cycle

### ISSUE THREAD

**Issue by Xuxe** [mailcow/mailcow-dockerized#2187]
**Describe the bug**
clamd-mailcow seem's to stuck in a reboot cycle since clamd:1.18 due to permissions the same issue like here #2162 but indeed git checkout data/conf/clamav/whitelist.ign2 doesn't fix it and the permissions (applied at https://github.com/mailcow/mailcow-dockerized/commit/5619221ed034b9e595122df2d8d58fc26bf94b22) and files looking good. 

Already tried to restart the whole stack and multiple times with clamd alone. 

**How to reproduce Reproduce**
Not really an idea right now...

**Expected behavior**
clamd-mailcow is up & running without reboot cycles. 

**Logs**

root@mail:/opt/mailcow-dockerized# docker exec -it a7f2bb58d9a2 ls -la /var/lib/clamav
total 180368
drw-r--r-- 1 clamav clamav      4096 Jan 16 16:44 .
drwxr-xr-x 1 root   root        4096 Jan 13 10:18 ..
-rw-r--r-- 1 clamav clamav    931202 Jan 16 07:16 blurl.ndb
-rw-r--r-- 1 clamav clamav    199693 Jan 16 08:05 bytecode.cvd
-rw-r--r-- 1 clamav clamav  54069655 Jan 16 08:05 daily.cvd
-rw-r--r-- 1 clamav clamav   7236645 Jan  3 08:12 junk.ndb
-rw-r--r-- 1 clamav clamav    260034 Jan 16 07:16 jurlbl.ndb
-rw-r--r-- 1 clamav clamav 117892267 Jan 16 08:05 main.cvd
-rw------- 1 clamav clamav        64 Jan 16 08:10 mirrors.dat
-rw-r--r-- 1 clamav clamav   4074398 Jan 15 18:43 phish.ndb
-rw-r--r-- 1 clamav clamav        27 Jan 16 16:44 whitelist.ign2

/bootstrap.sh: line 58: kill: (13) - No such process
Worker 13 died, stopping container waiting for respawn...
dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
Wed Jan 16 16:45:01 2019 -> !Can't open file or directory
LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2

Docker ps logs (compressed, because all other containers are up & running since 9 hours): 
a7f2bb58d9a2        mailcow/clamd:1.18       "/sbin/tini -g -- /b…"   9 hours ago         Up 12 seconds  

**System**
 - OS: Ubuntu 18.04 / Docker Version: 18.09.0

**Comment by andryyy** [comment]
/var/lib/clamav should be 755. 
Looks like 644.

**Comment by Xuxe** [comment]
I have seen it also... hehe. Could it be here? https://github.com/mailcow/mailcow-dockerized/commit/5619221ed034b9e595122df2d8d58fc26bf94b22#diff-258087bd985c3f12ac58200995bb57abL58 /var/lib/clamav is not here for chmod. 

Update: applying chmod 750 /var/lib/clamav followed by a restart fixed it.

**Comment by andryyy** [comment]
750 or 755 is fine here. :-)

I will add it.
