### ISSUE TITLE
Email Tagging funktioniert nicht über Alias Adresse

### ISSUE THREAD

**Issue by bawe** [mailcow/mailcow-dockerized#2190]
Tagging  wie z.B. "ich+Facebook@example.org" klappt nicht wenn "ich@example.org" ein Alias für "ich@example.com" ist.

Die Mail hat dann einfach keinen [Facebook] Tag..

**Comment by andryyy** [comment]
Jap, bitte in die vorhandenen Issues schauen. :-) Da wird es auch irgendwo erklärt. Sorry, dass ich es einfach schließe, habe gerade keine Zeit, die Issue zu suchen.
