### ISSUE TITLE
Password generator ignoring password policy

### ISSUE THREAD

**Issue by DatAres37** [mailcow/mailcow-dockerized#2191]
Not sure if this is a bug or a feature request tbh, but if you manually change the password policy, the password generator for new accounts ignores those policies, thus generates invalid passwords.

**Comment by andryyy** [comment]
Oh. That's a good catch.

**Comment by Adorfer** [comment]
BTW: Would be nice to have xkdcpass as an option for those autogenerated passwords
https://github.com/redacted/XKCD-password-generator

for "every day use" i like something like
xkcdpass -v [a-z,A-Z] --max=8 -w /usr/share/dict/words -n 4

**Comment by JPaulMora** [comment]
Also, the default generator is very insecure 8 lowercase letters + 2 numbers.

**Comment by andryyy** [comment]
Not really. You gain nothing with unreadable passwords with a length of 16 chars. People will write them down or save them in a passwords.txt.

I learned it is much better to create easy-to-remember default passwords. You can **always** change the policy in vars.inc.php (or better vars.local.inc.php) or generate super long, special char passwords yourself.

**Comment by holzhannes** [comment]
Are there any efforts to fix this error yet? If not, is there any option to turn off the generator?

Currently, it is quite as described by @JPaulMora and the [mailcow article from heise.de](https://www.heise.de/ratgeber/Mailcow-Mailserver-einrichten-und-Spam-arm-betreiben-6021810.html?seite=all) "the built-in generator is a nice idea, but generates too short passwords".
Passwords that are written down on paper pose a significantly lower security risk than passwords that are too short. My grandma's password manager is a notebook. It is very secure for all online attacks ;-). She would be very happy about an xkcx generator.

**Comment by MAGICCC** [comment]
Well for now you can customize the password policy a bit in the UI
![image](https://user-images.githubusercontent.com/3279213/121237817-beb3bf80-c897-11eb-941b-567b6447d03d.png)

**Comment by tardar** [comment]
Yeah, you can.
But the policy has no changes to the "generate" button of a new password of a mailbox.
Would be great if this is possible.

**Comment by vermium** [comment]
@DerLinkman This is fixed in #4995
