### ISSUE TITLE
No valid let's encrypt certificate with autoconfig

### ISSUE THREAD

**Issue by ks98** [mailcow/mailcow-dockerized#2193]
Hello everybody,
I just found out that none of the created domains will include "autoconfig.domain.de" in the Let's Encrypt certificate.

Therefore Thunderbird does not find the correct mail server settings.

As soon as "autoconfig.domain.de" is added to ADDITIONAL_SAN in mailcow.conf, the certificate is valid and Thunderbird finds the correct mail server settings.

Greetings,
 Kevin

**Comment by andryyy** [comment]
Hi, yes, we dropped HTTPS for those domains. You may have an older HTTP -> HTTPS redirection enabled, which redirects _all_ requests to HTTPs. Could you check against https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/ ?

**Comment by ks98** [comment]
Yes, sorry my mistake but thank you very much for the very quick answer.

**Comment by ks98** [comment]
Unfortunately it does not work if the domain has preloaded HSTS activated.

**Comment by andryyy** [comment]
Schau in die gesamte Site Config. Wir haben HSTS für subdomains deaktiviert. 

Bedenke auch den Cache. 

Hier: https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/nginx/site.conf.

Vielleicht hast du fur HSTS noch die Subdomains drin. Denk noch einmal an den Cache. Thunderbird vergisst es nicht so schnell.
Testen am besten mit curl -v http://autoconfig.bla/etc

**Comment by ks98** [comment]
ja geht jetzt. 

Danke für die Hilfe.
