### ISSUE TITLE
IMAP Sync does not save new Jobs after update

### ISSUE THREAD

**Issue by ripkens** [mailcow/mailcow-dockerized#2195]
After updateing MailCow, i can not add any Synchronisation Jobs
The form looks ok, it gets send, but the jobs do not show up in the list.

I have no error messages in the docker compose logs

**Comment by ripkens** [comment]
Additionally, i can not change the Quarantine settings which arrived with the update i made.

Wenn i save the settings, no error occures but they get not saved.

Do i have a problem with the database maybe?

**Comment by ripkens** [comment]
docker-compose exec -T mysql-mailcow mysql_upgrade
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
FATAL ERROR: Upgrade failed

docker-compose exec -T mysql-mailcow mysql_upgrade -u${DBUSER} -p${DBPASS}
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1044 (42000): Access denied for user 'mailcow'@'%' to database 'mysql'
FATAL ERROR: Upgrade failed


How can i fix this?

**Comment by andryyy** [comment]
MySQL upgrade won’t work without user and password. 

Please clean your browsers cache completely. Close it and open it again. :)

**Comment by ripkens** [comment]
I GOT IT FIXED ...

The DBPASS in the env File did not match the Password in the Database. I dont know how the password got changed, but i changed the password in the mysql table and now it seems to work ...
