### ISSUE TITLE
SOGo Aliases

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#22]
I'm not sure if we can change the following behavior from the mailcow side or if we need to change SOGo itself. But the following case in a setup with multiple domains and users with aliases from multiple domains is not ideal:

When you have a user with the main address `user@domain1.de` and an alias `user@domain2.de` his default `From` field in SOGo will be `user@domain1.de <user@domain1.de>`. When SOGo's configuration allows the user to change his name he can set it to `User` for example which changes the SOGo `From` to `User <user@domain1.de>`. However SOGo only does this for the main address and leaves all alias addresses with a `From` field like `user@domain1.de <user@domain2.de>` and the user has no way to change this.
So his username is always revealed when sends from alias domains and most people don't want that. It would be better if the user defined name would be used for all aliases and not only the main domain. And it would be even better if it would be a freely editable field which can be changed for every outgoing mail.

How is this `username <alias>` list SOGo is using generated? And can we change it in mailcow?

Thanks for looking into it.

**Comment by andryyy** [comment]
Hi,

I will check this and come back to you, still a bit busy. :-(


Am 19.01.2017 um 03:32 schrieb Till:

**Comment by tehXor** [comment]
Thx and no worries, this is low priority and would be only nice to have. People who require it can use standalone clients meanwhile ;-)

**Comment by goacid** [comment]
Hi

I've set SOGoMailCustomFromEnabled = YES; into sogo.conf.

**Comment by andryyy** [comment]
You can also now delegate other users to send as you. Above the mailbox list, right to your mailbox name, you can open a menu and select "delegate". We still need to manually allow those users to send as user xy in mailcow though. Should be fixable.

**Comment by goacid** [comment]
I remarq that some aliases are present in Sogo, and some other not. Same kind of aliases.
And sometime when I try to send with an alias I have error message : 
"cannot send message: (smtp) all recipients discarded"
I can't explain this behaviour yet.
Thanks for delegate :+1:

**Comment by broedli** [comment]
can't reproduce this issue. do you still experience it?

**Comment by tehXor** [comment]
Our original issue, that the real username of users is revealed as name on all SOGo Aliases but the first one (only on the first one the custom name is used you can specify when SOGoMailCustomFromEnabled is enabled), still exists. 

Should it behave differently meanwhile? We merged from master 2 or 3 days ago so we should be quite up to date...

**Comment by broedli** [comment]
~~yes, @andryyy has fixed the issue today.~~

~~**Edit:** for reference: 489b1ff~~

**Comment by broedli** [comment]
Sorry I believe I've misread the whole issue. No your issue still persists. Only the seggragation between domains got fixed.

**Comment by stenub** [comment]
Hi there,
I have the same problem as tehXor describes in his first post. What is the correct way to fix the problem? Should i set SOGoMailCustomFromEnabled = YES; in sogo.conf?
It would be much nicer (and safer) to let the admin compose "Name - <FromEmail>" combinations in the Mailcow Alias Section and the user only chooses between the preconfigured sets.
Thanks!
