### ISSUE TITLE
[help needed] mail filtering & spamchecking at mailsync

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#220]
I have some questions: I hope you could help me.
Until now, I love mailcow!
But what I would really love is the feature to synchronize (or one-way-download regularly) my mails from different other mailservices, run them through Sieve and spamcheck and sort them on my server. In one or more accounts.
The feature I am using at the moment is "IMAP sync", but this way the mail is directly put into the account, without ever getting in the near or spam or sieve filtering.

So the question is: Is it possible to add filtering to "IMAP sync" or is there any other way to do this?

Thank you,
Felix

**Comment by andryyy** [comment]
Hmm, sieve rules should apply. But spam filtering does not. We can consider switching to fetchmail some time.

**Comment by mindsolve** [comment]
Sorry for the late answer, and thank you andryyy!
The idea of IMAPsync is perfect for moving from one service to another, but in the case of "I have 10 addresses and there are still mails coming in which I don't want to miss, but there are also many spam-mails coming in which I would like to sort out" it's not the perfect way ;)

So the question now is: how could I achieve the second scenario?

**Comment by chaosbunker** [comment]
I have a case we're this would be very useful also. If anyone knows how to achieve this, please let me/us know:)

**Comment by Braintelligence** [comment]
For the use-case of "I have 10 addresses and there are still mails coming in which I don't want to miss, but there are also many spam-mails coming in which I would like to sort out" couldn't you just put up a mail-forwarding?

**Comment by mindsolve** [comment]
@Braintelligence Yes, that would be possible. I was just thinking about a universal way of doing this, as those accounts are not at the same provider. Which means that I have to research for each provider how to forward mails (which may not even be possible at some freemail hosters).

**Comment by Braintelligence** [comment]
I never heard of freemail hosters that do not allow forwarding for vacation purposes.

**Comment by mkuron** [comment]
For a long time, Yahoo Mail didn't have forwarding on free accounts. I'm sure that even now there are other free email providers that don't allow forwarding because they only make money from people using the webmail and seeing ads there.

**Comment by Braintelligence** [comment]
Do you have an example of a popular freemail provider that doesn't support this?

**Comment by xpcone** [comment]
United internet Group:
gmx.net
gmx.com
gmx.de
web.de

t-online.de (german Provider)
Strato.com (Mails on Hosted Domains )
hotmail.de

**Comment by iNoels** [comment]
Why is this closed? Is there any solution I don't see?

**Comment by mindsolve** [comment]
My original reason for opening this ticket is partially gone, as the providers I use have an option for mail forwarding.

As far as I know, there is currently no real solution for this. If you have that problem now, I would suggest looking at fetchmail, as it may be what you are searching for (fetch mails from POP3/IMAP-accounts and push them via SMTP to some other mailserver, such as your mailcow instance). I would try and whitelist (forwarding host setting in mailcow) the server you run fetchmail on, as SPF/DMARC validation are not going to work (fetchmail is the last "mail server"/hop to touch the message, and it is almost guaranteed to not be allowed by the sender SPF settings).

If you find a solution, I would be very interested in hearing about it!
Best of luck,
MindSolve

**Comment by kisspandur** [comment]
I am not an expert, (not at all, in fact), but the situation is the same here. I really-really want a feature like this, because the original hosts spamfilter is a crap. I would do anything to make it work. We use Thunderbird, so that comes in too.

**Comment by mesca** [comment]
> Hmm, sieve rules should apply.

Well, unless I am missing something, user sieve rules are not applied either.

**Comment by lakemike** [comment]
I also have several email accounts, that I consolidate on a self-hosted mailcow server. Esp some of the free accounts don't allow forwarding, so this is not an option. 

I came up with the work-around to set up isbg (IMAP Spam Begone). Installation is very simple under Debian using packages. It does take some configuration to get SpamAssassin to perform, because the default isn't very effective. Once that is done, isbg does a very good job to remove >95% of spam from any of my inboxes. And with that scanning and filtering in place, imapsync can be used again to push eveyrthing to the mailcow account.
