### ISSUE TITLE
Solr should be disabled by default when using update.sh

### ISSUE THREAD

**Issue by protree** [mailcow/mailcow-dockerized#2202]
**Describe the bug**
When updating with helper script "update.sh" I expect new features like solr to be disabled by default, especially when "Unmonitored Solr setups are not recommended." To be clear I really appreciate how mailcow is getting better and better, but I think the local admin should be able to manually activate important new features.

**How to reproduce Reproduce**
- Update mailcow using update.sh
- solr is enabled by default in mailcow.conf

**Expected behavior**
- New features that can be configured through mailcow.conf should be disabled by default

**Comment by andryyy** [comment]
Yes, that’s true.

**Comment by protree** [comment]
You could check if a Config-Var starts with "SKIP" in line 226 and if yes set SKIP_XXX=y. Just an idea so not every new feature has to be manually thought about in updater.sh

**Comment by andryyy** [comment]
Hm, we may not want to skip every option in the future, but Solr should probably be disabled by default.

**Comment by lucianlazar1983** [comment]
Hi all, is there a way to safely disable active SOLR? After update i found it already enabled and i am not sure if and how to safley disable solr without compromising anything.
Thanks

**Comment by andryyy** [comment]
SKIP_SOLR=y :-) Then `docker-compose up -d`.

You can disable it without damaging anything. You may just see some warnings I am about to fix with the next commits.

**Comment by lucianlazar1983** [comment]
Thanks, nice to know it wont break :)). I will wait then for your next commits before disable it, just curious in the meantime how it handles memory wise :)

**Comment by PaoloVi** [comment]
My Vm has only 2Gb of memory, but solr is always running. This in mailcow.conf:

```
SKIP_SOLR=y
# SOLR_HEAP=1024
```
---------------- edit
Ah, ok. With "SKIP_SOLR=y" the service is disable, but the solr container were always installed

**Comment by andryyy** [comment]
Container is just up with a sleeping bash.
