### ISSUE TITLE
fix docker volume for  sogo-mailcow

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#2203]
**Describe the bug**
i use three mailcow instances and on all of them i had to realize that every time mailcow is restarted for sogo-mailcow a new folder is created under %docker_root%/volumes.

`docker inspect mailcowdockerized_sogo-mailcow_1`
```
            {
                "Type": "volume",
                "Name": "3474b9562a3c1b20024ea7c549727360969d6fa8b264e9f57a0719056da59e9f",
                "Source": "/data/docker_root/volumes/3474b9562a3c1b20024ea7c549727360969d6fa8b264e9f57a0719056da59e9f/_data",
                "Destination": "/usr/lib/GNUstep/SOGo",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
```
I mean the folder:
"/data/docker_root/volumes/3474b9562a3c1b20024ea7c549727360969d6fa8b264e9f57a0719056da59e9f/_data"

**How to reproduce Reproduce**
restart mailcow (`dc down && dc up -d`)
`docker volume ls -qf dangling=true `-> 1 new folder
restart mailcow (`dc down && dc up -d`)
`docker volume ls -qf dangling=true` -> 2 new folders

**Expected behavior**
no new folder after restart

**Additional context**
del unused folders
`docker volume ls -qf dangling=true | xargs -r docker volume rm`

**Comment by andryyy** [comment]
There is an open issue for that.

**Comment by christianbur** [comment]
What's the Github issue number?

here is the corresponding config line:
https://github.com/mailcow/mailcow-dockerized/blob/38391d2cc38c719b015ce9c00eb3edc94485ec22/data/Dockerfiles/sogo/Dockerfile#L55

**Comment by andryyy** [comment]
I know this line. Please search the issues.

#1751
