### ISSUE TITLE
How to increase client_limit?

### ISSUE THREAD

**Issue by folkevil** [mailcow/mailcow-dockerized#2210]
**Describe the bug**
How can i increase client_limit, currently my mailcow server keep stop running and imap_login get error, users cannot login

![Dovecot](https://i.imgur.com/tv7bSGi.png)

**Comment by Braintelligence** [comment]
I'd say this: https://github.com/mailcow/mailcow-dockerized/blob/38391d2cc38c719b015ce9c00eb3edc94485ec22/data/conf/dovecot/dovecot.conf#L381

But your limit looks way lower. I wonder why.

**Comment by Braintelligence** [comment]
Maybe this isn't even related for anvil?
There are other people with that issue tho: https://www.dovecot.org/list/dovecot/2010-November/054517.html

**Comment by andryyy** [comment]
We increased those limits a while ago. Checkout dovecot.conf from origin/master via git. :)
