### ISSUE TITLE
[FR] Mailinglist-Server

### ISSUE THREAD

**Issue by Adorfer** [mailcow/mailcow-dockerized#2214]
I would very much apprechiate the direct integration of a mailinglist-robot into mailcow (including some kind of webui for 

- setup
- monitoring 
- administration
- subscription-selfservice
- public/nonpublic archives

This could be some for of mailman2/3 (in know about it's problems), mlmmj 
or even something modern like sympa6

(why i am asking: https://docs.iredmail.org/upgrade.mlmmjadmin.html )

**Comment by mkuron** [comment]
Duplicate of #325 #462 #1303 #1567. About a year ago, Mailman was integrated into the development branch, but that feature was never completed. The dev branch is so far behind now that you shouldn't be using it though.

**Comment by andryyy** [comment]
It is not forgotten, just a pita to integrate.

**Comment by Adorfer** [comment]
this is not a duplicate, since it's not a request for a howto, nor it's a question explicitly for mailman. (I would prefer more modern mldeamons).
But I ca create a new FR-ticket explicitly exclude mailman, since it's such a messy piece of software.

**Comment by andryyy** [comment]
MM is strange, yes. :-(

**Comment by Limbolindi** [comment]
hey, is there any update about "anykind" of mailing-list ? 
Or at least some recommendations or a HowTo?

**Comment by freaknils** [comment]
Are there any updates on mailinglist in Mailcow?
Thanks!

**Comment by phipag** [comment]
I would really appreciate a mailing list integration of any kind.

**Comment by lenucksi** [comment]
There is also [Sympa](https://www.sympa.org/) have there been any efforts in that direction?

**Comment by Adorfer** [comment]
I am using Sympa6 in it's own VM. But despite Mailman being totally outdated (stable) or broken (dev): 
sympa is a feature monster. A really reduced feature set would be great. 

Since this topic is closed: Perhaps make a new one, explicitly stating "integrate Mailingslist, but not using mailman"
