### ISSUE TITLE
Block fraudulent relay attempts

### ISSUE THREAD

**Issue by bonanza123** [mailcow/mailcow-dockerized#2215]
I have a lot of log entries that look like

```

1/23/2019, 8:42:29 AM | info | NOQUEUE:  reject: RCPT from unknown[113.103.119.77]: 504 5.5.2 <rudnlztc>:  Helo command rejected: need fully-qualified hostname;  from=<aaa@bbb.de> to=<234933064@qq.com>  proto=ESMTP helo=<rudnlztc>
-- | -- | --
1/23/2019, 8:42:28 AM | info | connect from unknown[113.103.119.77]
1/23/2019, 8:42:28 AM | info | PASS OLD [113.103.119.77]:59409
1/23/2019, 8:42:28 AM | info | Look up 113.103.119.77 on whitelist, result 200 DUNNO
1/23/2019, 8:42:28 AM | info | CONNECT from [113.103.119.77]:59409 to [172.24.2.11]:25

```

To me (uneducated) it looks like someone is trying to send fraudulent mails via my server. However, fail2ban/netfilter does not seem to be triggered by this. It would be great if there would be filter rule for such kind of attemps as well.

**Comment by mkuron** [comment]
There is no harm to these attempts as Mailcow will not relay such messages. The only effect is the log message you observed. Fail2ban's purpose is preventing brute-force attempts at breaking an account's password. While it could be expanded to disallowed relaying attempts, there is no point to it as the spammers tend to go away after a few tries, i.e. you would just be bloating the ban table with IP addresses that aren't going to come back any time soon.

**Comment by bonanza123** [comment]
Thanks for your reply!
My observation is that this particular subnet is already trying to for at least 2 weeks (maybe he is not a clever spammer ;-) ).
Also, not blocking these guys after X attempts makes it really hard to find important stuff in the logs.
Moreover, my fail2ban list is almost empty, so (at least in my case) I don't think there would be a problem with bloated up ban lists.

**Comment by Adorfer** [comment]
Sometimes "attempt to relay" happens to legit mailservers due to slight misconfigurations. 
Blocking server's IPs after x failed relay attempts would cause a lot of false positives at least in some setups, eg. with older mailinglist-robots. 
when when they try to send valid/reworked) mails later, they would be not going through.

iow: if failed relays trigger blocking action, this should be configurable and disabled by default (just my 2 cents)

**Comment by mkuron** [comment]
> My observation is that this particular subnet is already trying to for at least 2 weeks

Just add that subnet to the blacklist in the admin UI.
