### ISSUE TITLE
Security access to some folder in "web" dir

### ISSUE THREAD

**Issue by jacyker** [mailcow/mailcow-dockerized#2216]
Hi

I want block access form web to some dir in "web" direcotry, eg:
/opt/mailcow-dockerized/data/web/PRIVATE-DIR

I tried using the standard Nginx rule, but it either does not work or the entire webserver off.
I think it would be best to add a file, e.g. private-dir.conf in /opt/mailcow-dockerized/data/conf/nginx, but I have no idea what to write in it.

Thank you in advance for all suggestions and ideas :-)
Jaco

**Comment by andryyy** [comment]
Hi,

create a file `data/conf/nginx/site.deny_rule.custom`, add:

```
location ~ /test {
   deny all;
   return 403;
}
```

...where "test" is your folder.

Restart Nginx: `docker-compose restart nginx-mailcow`

**Comment by jacyker** [comment]
Big thx. Work OK :-)

Best regards, Jaco
