### ISSUE TITLE
Dienste unter IPv6 nicht möglich

### ISSUE THREAD

**Issue by passi15** [mailcow/mailcow-dockerized#2217]
Hallo,
meine Dienste (IMAP etc) sind nicht per IPv6 erreichbar.
Meiner Meinung nach, fehlen die Einträge in der NAT Tabelle.:

```
# ip6tables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all      anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER     all      anywhere            !localhost            ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       all      fd4d:6169:6c63:6f77::/64 !fd4d:6169:6c63:6f77::/64  to:2a0a:51c0::2f2
MASQUERADE  all      fd4d:6169:6c63:6f77::/64  anywhere

Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all      anywhere             anywhere
```

Folgend der Auszug aus der Netfilter Log:

24.1.2019, 09:28:52 | info | Added POSTROUTING rule for source network fd4d:6169:6c63:6f77::/64 to SNAT target 2a0a:51c0:0:0:0:0:0:2f2
-- | -- | --

Wie kann ich die Dienste über IPv6 erreichbar machen? IPv6 SNAT wurde in der mailcow.conf eingerichtet.

System ist Debian 9.
# docker -v
Docker version 18.09.1, build 4c52b90
# docker-compose -v
docker-compose version 1.24.0-rc1, build 0f3d4dda

`docker-compose exec php-fpm-mailcow curl ip6.mailcow.email
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
2a0a:51c0::2f2`

Vielen Dank!

**Comment by mkuron** [comment]
Schau dir mal die FORWARD-Tabelle von `ip6tables -L` an, da müssten die fehlenden Regeln sein.

**Comment by passi15** [comment]
Auch nicht. Anbei der Auszug:

> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> MAILCOW    all      anywhere             anywhere
> DOCKER-ISOLATION  all      anywhere             anywhere
> DOCKER     all      anywhere             anywhere
> ACCEPT     all      anywhere             anywhere             ctstate RELATED,ESTABLISHED
> ACCEPT     all      anywhere             anywhere
> ACCEPT     all      anywhere             anywhere



Muss ich IPv6 für die Dienste noch irgendwo freischalten/konfigurieren?

**Comment by mkuron** [comment]
Ist in den anderen Tabellen was zu sehen? Wenn nicht, klingt das, als wäre der ipv6nat-Container nicht gestartet worden. Was siehst du bei `docker-compose logs ipv6nat`?

**Comment by passi15** [comment]
Nein die anderen Tabellen sind auch leer.
Dein Befehl ergibt:

> $ docker-compose logs ipv6nat
> WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
> Attaching to mailcowdockerized_ipv6nat_1

**Comment by passi15** [comment]
Ich habe Mailcow nun neuinstalliert. Wenn ich die Dienste in der mailcow.conf NICHT an eine IPv4 Adresse "binde", werden die Einträge in der IPv6 NAT Tabelle hinzugefügt.
Da ich aber mehrere IP-Adressen benutze, muss ich die Dienste an eine IP binden.

Wie bekomme ich es hin, dass die Dienste unter IPv4 und v6 erreichbar sind?

Anbei noch die aktuelle IPv6 NAT Tabelle:

> # ip6tables -t nat -L
> Chain PREROUTING (policy ACCEPT)
> target     prot opt source               destination
> DOCKER     all      anywhere             anywhere             ADDRTYPE match dst-type LOCAL
> 
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
> DOCKER     all      anywhere            !localhost            ADDRTYPE match dst-type LOCAL
> 
> Chain POSTROUTING (policy ACCEPT)
> target     prot opt source               destination
> SNAT       all      fd4d:6169:6c63:6f77::/64 !fd4d:6169:6c63:6f77::/64  to:2a0a:51c0::2f2
> MASQUERADE  all      fd4d:6169:6c63:6f77::/64  anywhere
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::a  fd4d:6169:6c63:6f77::a  tcp dpt:pop3s
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::a  fd4d:6169:6c63:6f77::a  tcp dpt:pop3
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::a  fd4d:6169:6c63:6f77::a  tcp dpt:imap2
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::a  fd4d:6169:6c63:6f77::a  tcp dpt:sieve
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::a  fd4d:6169:6c63:6f77::a  tcp dpt:imaps
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:urd
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:submission
> MASQUERADE  tcp      fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:smtp
> MASQUERADE  all      fd4d:6169:6c63:6f77::/64  anywhere
> MASQUERADE  all      fd4d:6169:6c63:6f77::/64  anywhere
> 
> Chain DOCKER (2 references)
> target     prot opt source               destination
> RETURN     all      anywhere             anywhere
> DNAT       tcp      anywhere             anywhere             tcp dpt:pop3s to:[fd4d:6169:6c63:6f77::a]:995
> DNAT       tcp      anywhere             anywhere             tcp dpt:pop3 to:[fd4d:6169:6c63:6f77::a]:110
> DNAT       tcp      anywhere             anywhere             tcp dpt:imap2 to:[fd4d:6169:6c63:6f77::a]:143
> DNAT       tcp      anywhere             anywhere             tcp dpt:sieve to:[fd4d:6169:6c63:6f77::a]:4190
> DNAT       tcp      anywhere             anywhere             tcp dpt:imaps to:[fd4d:6169:6c63:6f77::a]:993
> DNAT       tcp      anywhere             anywhere             tcp dpt:urd to:[fd4d:6169:6c63:6f77::3]:465
> DNAT       tcp      anywhere             anywhere             tcp dpt:submission to:[fd4d:6169:6c63:6f77::3]:587
> DNAT       tcp      anywhere             anywhere             tcp dpt:smtp to:[fd4d:6169:6c63:6f77::3]:25
