### ISSUE TITLE
SoGo Login not possible due 403 Forbidden

### ISSUE THREAD

**Issue by dunklesToast** [mailcow/mailcow-dockerized#222]
Hey,

just installed mailcow.
AdminUI works fine but sogo not. when i want to login it says wrong password or username :/
Chrome DevTools says `Failed to load resource: the server responded with a status of 403 (Forbidden) @ :81/SOGo/connect`.

I am using Port 81 for HTTP and 444 for HTTPS.

Hope u can help,

Tom

**Comment by dunklesToast** [comment]
So i just reinstalled my vserver and mailcow and its still not working.
MailcowUI works but sogo login fails because it cannot connect due an 403. the nginx process is started as root and ports are now normal.

Any Ideas how to solve?

**Comment by andryyy** [comment]
Same problem with ports 8080 and 8443?

**Comment by dunklesToast** [comment]
Yes :/
Is it because I am running it at root? Maybe nginx needs permission to read the files and is not showing them online.
If I open the page manually, I get `LDAPPasswordPolicyError:65535`
NGINX throws: `nginx-mailcow_1      | 87.173.XXX.XXX - - [30/Apr/2017:21:11:46 +0000] "POST /SOGo/connect HTTP/1.1" 403 34 "http://freefilming.de:8080/SOGo/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"`

(i removed some parts of ip)

**Comment by dunklesToast** [comment]
Any ideas?

**Comment by Braintelligence** [comment]
Just to make sure:
You are using the most current version of docker and docker-compose and the current master-branch of mailcow-dockerized?
Which OS are you using?
Did you change any of the conf-files?

**Comment by dunklesToast** [comment]
Yep. Newest docker and compose. Newest Mailcow.
I am using Ubuntu 16.04.2 LTS. No. Just changed the ports.

But it is now working - was something with the permissions

**Comment by goldsziggy** [comment]
@dunklesToast any chance you can mention what your fix was?  I am running into the same issue here.

**Comment by dunklesToast** [comment]
I forgot to add the TLD! You need to login with your complete email (name@domain.com) and not just with your name! But I also needed to add one or to write permissions to the SoGo Server for saving content

**Comment by goldsziggy** [comment]
Hmm, I have attempted logging in with the complete domain.  Can you elaborate on the write permissions?  seeing as SoGo is running via docker, is it one of the shared resources that need write permission?

**Comment by goldsziggy** [comment]
,,,
