### ISSUE TITLE
[Typo] [update.sh] that were now added -> that were NOT added

### ISSUE THREAD

**Issue by jay-to-the-dee** [mailcow/mailcow-dockerized#2220]
**Describe the bug**

Help text prints the following:
> You most likely added files to your local mailcow instance that were _now_ added.

 Surely should be _not_ added? :)

**How to reproduce Reproduce**
Just run `update.sh` with a modified mailcow instance ;)

**Comment by andryyy** [comment]
That's actually correct, but badly written. I meant to say "you added new files to your mailcow installation which didn't exist before the upgrade, but are now part of mailcow".

That's not always the case when an update fails. Git will return more useful information.

Did you run into such an error message when it was actually something else? Can you post the log?

**Comment by jay-to-the-dee** [comment]
Okay that makes more sense, thanks! I don't remember the details exactly now since I fixed it, but I do remember that Git didn't spit out much or any useful information. If I remember correctly, for some reason the remote master branch had become locally unset as I was experimenting with my own branch for the unbound patch.
