### ISSUE TITLE
Moving mail to subfolder with OS X forces creation of maildir with `\2e` instead of `.`

### ISSUE THREAD

**Issue by zeigerpuppy** [mailcow/mailcow-dockerized#2223]
A really strange bug which seems to be related to the interaction of OS X Mail (El Capitan and Mavericks tried).  I recently migrated mail from a previous dovecot based install to mailcow.  Emails were rsynced over and it all works well.
However, when OS X mail moves an email to a subfolder, it does a strange thing, creating a new folder with `\2e` instead of periods.

For instance if a maildir `.Testing.Testmails` exists and is readable and an email is moved to it, then dovecot creates a new folder called `.Testing\2eTestmails` and puts emails in that folder.  This then result in the emails in `.Testing.Testmails` being unreadable.

So far, I think this issue only arises if OS X mail was previously synchronized with the emails prior to the migration.  I wonder what's causing Dovecot to create the new folder?

Here's a quick fix if it occurs to anyone else:

```
mv .Testing\\2eTestmails/cur/* .Testing.Testmails/cur/
rm -r .Testing\\2eTestmails
```

**Comment by andryyy** [comment]
Migrating from another installation is not just copying the maildir. You need to make sure the namespaces and other options like the layout (like FS) are the same. This is not a bug. :)

**Comment by zeigerpuppy** [comment]
I agree this is probably more of an OS X mail issue than a mailcow bug.
The namespaces on the two servers were the same.  Still weird that mailcow can even create a folder like that though, it should be prohibited from creating anything apart from `.` indexed maildirs

**Comment by dkrebs** [comment]
@zeigerpuppy How did you solve the issue?

- SOGo shows the dirs with `.`
- Apple Mail shows the dirs with `\2e`

So I end up having different emails in different clients. Apple Mail shows the `.` folders without hierarchy and cannot load the mails.

**Comment by zeigerpuppy** [comment]
i just removed the accounts from os x mail and ran a full resync.
that seems to have solved the issue
