### ISSUE TITLE
Comment column for alias addresses

### ISSUE THREAD

**Issue by hoekki** [mailcow/mailcow-dockerized#2224]
Hi guys,

I'm using mailcow for my personal mail server for almost a year now. Great thing you have going here.

I am using alias addresses excessively, mostly for newsletters or services where I'm not sure whether it will turn into a spam account or not. For that to be more convenient, it would be nice to have a comment column in the alias address configuration area to be able to indicate what the individual alias address is intended for.
- for more convenient configuration of mail filters
- backtrace of compromised/illegally shared email addresses
- easily cut off spammers by selectively deleting alias addresses

For that, an additional simple text column in the alias addresses overview would suffice.
Showing that information as tooltip throughout mailcow would be the icing on the cake.

Cheers :)

**Comment by andryyy** [comment]
Hi,

Should be easy...

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/51808238-af68e400-2291-11e9-90db-dfb0d797f1f8.png)

![grafik](https://user-images.githubusercontent.com/2972950/51808256-e8a15400-2291-11e9-9ffd-e9f64a749f7a.png)

![grafik](https://user-images.githubusercontent.com/2972950/51808260-f2c35280-2291-11e9-9aea-e5207a5fb330.png)

**Comment by hoekki** [comment]
Perfect! :)
