### ISSUE TITLE
Selectively delegate permission to create alias addresses

### ISSUE THREAD

**Issue by hoekki** [mailcow/mailcow-dockerized#2225]
Hi,

Currently, only temporary alias addresses can be managed by the individual mail box user. Persistent/human readable alias addresses can only be managed by the mailcow admin. It would be nice to have the ability to delegate management of alias addresses to the individual mail box user. Maybe even set a quota for alias address count.

Cheers :)

**Comment by lkathke** [comment]
I would also be in favor of the feature

**Comment by aelnosu** [comment]
any update
