### ISSUE TITLE
use #!/usr/bin/env shebang instead of hardcoded paths

### ISSUE THREAD

**Issue by jficz** [mailcow/mailcow-dockerized#2226]
Scripts `generate_config.sh` and `update.sh` (and, perhaps, others) use non-portable shebang `#!/bin/bash`. 

One should not assume an arbitrary binary to be available in a specific location but rather should rely on `$PATH`.

With the hardcoded path the scripts will not work on installations where `bash` binary is unavailable in the assumed location but is still installed and available somewhere else in `$PATH` (for instance in `/usr/local/bin/bash`or anywhere else the system or admin sees fit).

A better approach is to use `#!/usr/bin/env bash` which is much more portable as `/usr/bin/env` will provide the correct path to the binary using `$PATH` and is historically available in virtually all distributions.

**Comment by andryyy** [comment]
Yes, that's a good idea.

**Comment by jficz** [comment]
great, I'll create a PR

**Comment by andryyy** [comment]
Oh, I already added it. :-) Just not pushed.

**Comment by jficz** [comment]
ahh, ok. I'll start with the PR the next time :)

**Comment by andryyy** [comment]
Sorry, but thank you very much for that great idea. :)
