### ISSUE TITLE
rspamd: undefined request

### ISSUE THREAD

**Issue by imxari** [mailcow/mailcow-dockerized#2228]
Fresh install of mailcow produces the result in the screenshot
![capture](https://user-images.githubusercontent.com/16465944/51790114-0767f380-2189-11e9-9e28-69c96e46d808.PNG)

**Comment by andryyy** [comment]
Can’t confirm. 

I will close issues without any information in the future. 

If you don’t provide ANY details, I can only respond with “no”. It works.

Don’t know when this error actually occurs for you, wether you set a password, if you use a RP etc.

**Comment by imxari** [comment]
Hi,

I've set a password and tried entering it into the RSPAMD ui but it didn't work it just gave me that error. See the logs below:

rspamd: https://pastebin.com/wkaueZtW
nginx: https://pastebin.com/HHh3E1gU

If you want anymore logs I can provide.

System details:
Centos 7
1 Core
1GB RAM

Running on Proxmox VE.

**Comment by andryyy** [comment]
Try the demo please. It is always max one hour old. I can’t do it right now. 

What’s the umask of your system? What’s in your browsers debug log? 1 GB is also probably not enough.

Is SELinux active?

**Comment by imxari** [comment]
Demo produces the exact same result SELinux is disabled

**Comment by andryyy** [comment]
Try a browser without any JS blocker. :)

Can anyone else try? I’m not home.

**Comment by imxari** [comment]
Same result even in Edge and Firefox.

**Comment by andryyy** [comment]
I am home now and can confirm this happens in the demo but not on my installations. O_O

I sadly don't have access to the demo installations. 

Can we both start a remote session?

**Comment by imxari** [comment]
Unfortunately I cannot right now, I could give you a user account that you can use on my mailcow installation?

**Comment by andryyy** [comment]
That's not enough. :-( Can you show the output of `cat data/conf/rspamd/override.d/worker-controller-password.inc`? Just set it to a random password before here. Ah, also `ls -la data/conf/rspamd/override.d/worker-controller-password.inc`.

This seems to happen when the password is "wrong". I get the same result then.

**Comment by andryyy** [comment]
No, wait, that's not true. It works here. My fucking password manager just always auto-filled the form.

When that happens (=> wrong password), it gives you that strange "undefined" alert box.

**Comment by imxari** [comment]
```
[root@dockerhost mailcow-dockerized]# cat data/conf/rspamd/override.d/worker-controller-password.inc
# Placeholder
```
```
[root@dockerhost mailcow-dockerized]# ls -la data/conf/rspamd/override.d/worker-controller-password.inc
-rw-r--r-- 1 101 101 15 Jan 26 16:07 data/conf/rspamd/override.d/worker-controller-password.inc
```

That isn't strictly true, I just set the password to "test" and typed it in exactly and still get the same error.

**Comment by andryyy** [comment]
Well, it is working here, even in the demo installation:

![grafik](https://user-images.githubusercontent.com/2972950/51791170-3f7a3100-219f-11e9-998f-f0678634ef26.png)

Your password file is empty, the password is never set. What does mailcow UI return when you set the password?

Which filesystem do you use? And `docker info`? Is it a KVM machine?

**Comment by imxari** [comment]
```
[root@dockerhost mailcow-dockerized]# docker info
Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 991.1 MiB
Name: dockerhost.lkeenan.co.uk
ID: O7CL:PVZS:CSEC:2D5D:OLRS:L7CA:I4N6:X4UA:LILX:IH3N:45TV:NQRI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 192.168.1.13:5000
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
[root@dockerhost mailcow-dockerized]#
```

Which container do you want the logs from? I can't figure out which is hosting the mailcow ui:
```
[[root@dockerhost mailcow-dockerized]# docker-compose ps
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
                Name                               Command               State                        Ports
--------------------------------------------------------------------------------------------------------------------------------
mailcowdockerized_acme-mailcow_1        /sbin/tini -g -- /srv/dock ...   Up
mailcowdockerized_clamd-mailcow_1       /sbin/tini -g -- /bootstrap.sh   Up
mailcowdockerized_dockerapi-mailcow_1   python2 -u /server.py            Up
mailcowdockerized_dovecot-mailcow_1     /docker-entrypoint.sh /bin ...   Up      0.0.0.0:110->110/tcp,
                                                                                 127.0.0.1:19991->12345/tcp,
                                                                                 0.0.0.0:143->143/tcp, 0.0.0.0:4190->4190/tcp,
                                                                                 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp
mailcowdockerized_ipv6nat_1             /docker-ipv6nat --retry          Up
mailcowdockerized_memcached-mailcow_1   docker-entrypoint.sh memcached   Up      11211/tcp
mailcowdockerized_mysql-mailcow_1       docker-entrypoint.sh mysqld      Up      127.0.0.1:13306->3306/tcp
mailcowdockerized_netfilter-mailcow_1   python2 -u /server.py            Up
mailcowdockerized_nginx-mailcow_1       /bin/sh -c envsubst < /etc ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
mailcowdockerized_php-fpm-mailcow_1     /docker-entrypoint.sh php- ...   Up      9000/tcp
mailcowdockerized_postfix-mailcow_1     /bin/sh -c exec /usr/bin/s ...   Up      0.0.0.0:25->25/tcp, 0.0.0.0:465->465/tcp,
                                                                                 0.0.0.0:587->587/tcp, 588/tcp
mailcowdockerized_redis-mailcow_1       docker-entrypoint.sh redis ...   Up      6379/tcp
mailcowdockerized_rspamd-mailcow_1      /docker-entrypoint.sh /usr ...   Up
mailcowdockerized_sogo-mailcow_1        /bin/sh -c exec /usr/bin/s ...   Up
mailcowdockerized_solr-mailcow_1        /docker-entrypoint.sh            Up      8983/tcp
mailcowdockerized_unbound-mailcow_1     /docker-entrypoint.sh /usr ...   Up      53/tcp, 53/udp
mailcowdockerized_watchdog-mailcow_1    /sbin/tini -g -- /bin/sh - ...   Up
[root@dockerhost mailcow-dockerized]#
```

**Comment by andryyy** [comment]
Which filesystem do you use? And docker info? **Is it a KVM machine?**

**Comment by andryyy** [comment]
I also asked about the umask and what the UI returns when you set the password...

I cannot reproduce it and need access to that machine, either SSH or AnyDesk.

**Comment by imxari** [comment]
Umask returns 0022
it's a KVM vm
LVM filesystem
I'm unsure of which docker container to get the logs from?
