### ISSUE TITLE
Domain and Mailbox Management for Large Systems

### ISSUE THREAD

**Issue by michacassola** [mailcow/mailcow-dockerized#2230]
Let's say I have two customers on a large VPS but one customers mailboxes become to big so I want to move the whole domain to another server. Can I do that? If not I would like to request this kind of feature.

Another use case might be if you want to have one domain on 2 servers, is that possible somehow?

**Comment by Adorfer** [comment]
Same situation for "customer 1 has domains a and b" and "customer splits up in company 1 and 2 and 2 takes domain b with it" (and 2 want's/needs to cut all relation from 1, e.g. independend VPS contract)

**Comment by Braintelligence** [comment]
Do a backup of the VPS, restore it on a bigger storage VPS, boot into Gparted, enlarge the partition, boot up the VPS and have fun?

**Comment by michacassola** [comment]
Why would I enlrage a partition? I do not plan to fiddle around with my VPS's partitions in the first place.

Also, of course I thought of that, to move the backup to a new server and simply delete domain1 that stays on the original server and delete domain2 from the original server after the successful migration. But that was exactly my point: Why not make it simpler to move a domain between two mailcow servers? Is that such a rare use case? I am surely not the only one thinking about offering mail accounts an a per account basis?!

My second question didn't get answered: 2 mailcow servers 1 domain possible?

**Comment by andryyy** [comment]
It is possible when you cluster it. That's not a feature of the open source mailcow. I offer clustered setups as projects planned with the customer.

Some commercial-like features will probably never make it to mailcow as long as they are not sponsored.

**Comment by andryyy** [comment]
There are so many ways to cluster mailcow. :) I will write docs for it someday. I'd always recommend a multi-redundant storage (a stable ceph cluster or something) with only SQL clustered via Percona/Galera. It is so much better than Dovecot replication (which breaks with shared namespaces anyway).

You could even drop the SQL cluster and store all redundant data (volumes, configs) on your storage system. You can start a new mailcow on any other node any time, you just need to add the mounts. This is update-safe but makes you lose the ability of load-balancing. 

I really recommend a very stable, redundant storage. :)
