### ISSUE TITLE
I cannot login to other mail clients such as Thunderbird or Outlook 

### ISSUE THREAD

**Issue by GabrielBes** [mailcow/mailcow-dockerized#2231]
Hello, 
I've read all the posts about this problem, but I still couldn't fix it.

Sending and receiving emails through the SoGo web interface works perfectly, but I can't do it in other email clients. 

Many greetings,
Gabriel

**Comment by andryyy** [comment]
And your settings in those other clients?

**Comment by GabrielBes** [comment]
Thunderbird found the settings directly: imap/smtp = fqdn with ssl/tsl

**Comment by andryyy** [comment]
And port, STARTTLS?

You are probably using port 25, which is wrong.

**Comment by GabrielBes** [comment]
993 and 465 are the ports

**Comment by andryyy** [comment]
Then you need to show postfix-mailcow logs when you login via Thunderbird. Do you use a Speedport Router?

**Comment by GabrielBes** [comment]
I dont know what you mean :) I used this guide to install mailcow on my server: https://www.bennetrichter.de/anleitungen/mailcow-dockerized/ 
Maybe you can see the mistake there :)

**Comment by andryyy** [comment]
Do you use a Speedport Router from Telekom?

**Comment by GabrielBes** [comment]
I use a normal cloud vps from "Hetzner"

**Comment by andryyy** [comment]
At home.

**Comment by GabrielBes** [comment]
I have unitymedia as an internet provider and Im using their router

**Comment by andryyy** [comment]
Can you mail me a test email account to info@servercow.de ?

**Comment by GabrielBes** [comment]
E-mail sent :-)

**Comment by andryyy** [comment]
Looks for another solution than mailcow because Cloudflare hides the real IP of the MX (which will not work, obviously, that's not related to mailcow).

So... I will close this, I guess.

Problem was indeed the hidden MX.
