### ISSUE TITLE
[FR] Implement support for fail2ban to automatically report IP addresses to AbuseIPDB

### ISSUE THREAD

**Issue by bipsendk** [mailcow/mailcow-dockerized#2232]
**Is your feature request related to a problem? Please describe.**
It would be nice, if IP addresses trying to gain unauthorized access to the system could automatically be reported to AduseIPDB (login attempts, attempts to relay, SMTP connections blocked by RBL servers and som on).

**Describe the solution you'd like**
It would require a bit of extra code in a normal fail2ban setup to support automatic reporting to AbuseIPDB - and of course an API key for AbuseIPDB (which the admin would enter).
It would also be desirable, if the admin had the option to adjust the ban-time for each time of attempt being caught by fail2ban.

**Comment by JOduMonT** [comment]
several [BanIPDB](http://iplists.firehol.org) exist
I was wondering why AbuseIPDB more than another ?

**Comment by CMiksche** [comment]
> several [BanIPDB](http://iplists.firehol.org) exist
> I was wondering why AbuseIPDB more than another ?

I know both list providers and BanIPDB is very useful on a firewall level.

But all the attackers which targeted my mailserver are already in the AbuseIPDB list so it seems like many mailserver already use AbuseIPDB and report to them ...

As described in #3302 mailcow probably won't integrate this as this should be done on a level outside of mailcow (e.g. firewall). 
That's btw the same mindset other software solutions like Mailu have too.
