### ISSUE TITLE
Alias not using domain relayhost

### ISSUE THREAD

**Issue by spmealin** [mailcow/mailcow-dockerized#2233]
**Describe the bug**
When a mail alias is set up using a domain with a configured relayhost, emails sent to that alias do not go through the relayhost.

**How to reproduce Reproduce**
1. Create a domain with a configured relayhost (example.com -> relayhost.com)
2. Create a mail alias for that domain, and set the target address to another domain (alias@example.com -> user@gmail.com)
3. Send an email to alias@example.com

**Expected behavior**
An email goes from the sender to alias@example.com, then through relayhost.com, and then to user@gmail.com.

**Actual behavior**
An email goes from the sender to alias@example.com, and then directly to user@gmail.com.

**Logs**
postfix-mailcow_1    | Jan 27 23:19:50 mail postfix/smtpd[523]: connect from mail-ed1-f47.google.com[209.85.208.47]
postfix-mailcow_1    | Jan 27 23:19:50 mail postfix/smtpd[523]: Anonymous TLS connection established from mail-ed1-f47.google.com[209.85.208.47]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SH
A384 (256/256 bits)
postfix-mailcow_1    | Jan 27 23:19:51 mail postfix/smtpd[523]: 4D6F56C01CC: client=mail-ed1-f47.google.com[209.85.208.47]
postfix-mailcow_1    | Jan 27 23:19:51 mail postfix/cleanup[527]: 4D6F56C01CC: message-id=<CAF_3r-Fwdt1JUtUqR3TLw1rjE4VZC3qnsWK0wn5xUmHbXRLS5Q@mail.gmail.com>
postfix-mailcow_1    | Jan 27 23:19:53 mail postfix/qmgr[337]: 4D6F56C01CC: from=<sender@somedomain.com>, size=3315, nrcpt=1 (queue active)
postfix-mailcow_1    | Jan 27 23:19:54 mail postfix/smtpd[523]: disconnect from mail-ed1-f47.google.com[209.85.208.47] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
postfix-mailcow_1    | Jan 27 23:19:54 mail postfix/smtp[528]: Trusted TLS connection established to gmail-smtp-in.l.google.com[64.233.177.27]:25: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POL
Y1305 (256/256 bits)      (*** Note that it is directly connecting to gmail, not the relayhost ***)
postfix-mailcow_1    | Jan 27 23:19:55 mail postfix/smtp[528]: 4D6F56C01CC: to=<user@gmail.com>, orig_to=<alias@example.com>, relay=gmail-smtp-in.l.google.com[64.233.177.27]:25, del
ay=4, delays=2.7/0.02/0.92/0.36, dsn=2.0.0, status=sent (250 2.0.0 OK 1548631195 s198si18777635ywg.402 - gsmtp)
postfix-mailcow_1    | Jan 27 23:19:55 mail postfix/qmgr[337]: 4D6F56C01CC: removed

**Additional context**
This is using a completely fresh install, pulled from git on Sunday Jan 27th.

**Comment by andryyy** [comment]
It’s called sender dependent transport map. 

In your described case the sender is not the alias address. The alias is just an alias. 

You can use sieve and forward the mail. The sender address would be correct for the sender dependent map.

You could probably work with transport maps, too (not sender dependent).

**Comment by spmealin** [comment]
Thanks for responding.  Just so I make sure that I understand my options (please correct me if I’m wrong)...

Using an email alias, the email will be forwarded directly to the specified email, without going through the domain’s configured sender dependent transport map.

If I want it to go through the sender dependent transport map, I need to have a locally configured user/mailbox, and use sieve to forward the mail.

My use case is that I want all mail, regardless of sender, to be forwarded to another email address.

**Comment by andryyy** [comment]
You don’t want to use sender dependent maps then. Use the transport maps on the table below.
