### ISSUE TITLE
generate_config.sh doesn't include ACL_ANYONE variable

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#2234]
Running `update.sh` script adds `ACL_ANYONE` variable, but generating new config file with `generate_config.sh` does not.

**Comment by andryyy** [comment]
I saw it yesterday and fixed it. Sorry. 

Will push soon.

**Comment by pschiffe** [comment]
Thanks, I should check also the dev branch, sorry. This is now fixed in https://github.com/mailcow/mailcow-dockerized/commit/c3d67805a1765b2c9ce04355449e117db896cce3
