### ISSUE TITLE
550 no mailbox by that name is currently available

### ISSUE THREAD

**Issue by tankersss** [mailcow/mailcow-dockerized#2237]
I'm kinda fresh to this, when I try to email myself from any other mail service I will now get 550 no mailbox, earlier I was getting 554/550 5.7.1 Relay access denied. 
I already did correct DKIM/DMARC configuration, and tested it with mail-tester.
I didn't set anything in forwarding hosts/routing/aliases, the domain I'm trying to mail, and mailbox are active, but backup MX have an x next to it. 
Also I'm using Cloudflare as my DNS thingie. 
I'm open to post anything that's needed to fix this issue.
What works:
 - Sending mails internally
 - Sending mails to outside

What don't work:
 - Receiving emails from outside

**Comment by DatAres37** [comment]
It would probably help if you could post logs of your dovecot and postfix container.

**Comment by tankersss** [comment]
Dovecot
`

28.01.2019, 19:20:38 | info | master: Dovecot v2.3.4 (0ecbaf23d) starting up for imap, sieve, lmtp, pop3
-- | -- | --
28.01.2019, 19:30:48 | info | pop3-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.8, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.8, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.8, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | pop3-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.8, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:49 | info | managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.1, lip=172.22.1.8, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:32:24 | info | imap(mail@mail)<344><lU7b5YiAUrCsFgH4>: Logged out in=153 out=1671 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:32:25 | info | imap(mail@mail)<352><fbL05YiAdrCsFgH4>: Logged out in=144 out=1556 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:32:25 | info | imap(mail@mail)<349><0xzp5YiAbLCsFgH4>: Logged out in=218 out=1728 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:32:26 | info | lmtp(354): Connect from 172.22.1.4
28.01.2019, 19:32:27 | err | indexer-worker(mail@mail)<356><oeqWOLpKT1xiAQAAIfZBbA:vbmYCLtKT1xkAQAAIfZBbA>: Error: Mailbox INBOX: Status lookup failed: Internal error occurred. Refer to server log for more information. [2019-01-28 19:32:27]
28.01.2019, 19:32:27 | err | indexer-worker(mail@mail<356><oeqWOLpKT1xiAQAAIfZBbA:vbmYCLtKT1xkAQAAIfZBbA>: Error: fts_solr: Lookup failed: connect(172.22.1.3:8983) failed: Connection refused (2 attempts in 0.010 secs)
28.01.2019, 19:32:27 | info | lmtp(354): Disconnect from 172.22.1.4: Client has quit the connection (state=READY)
28.01.2019, 19:32:27 | info | lmtp(mail@mail)<354><oeqWOLpKT1xiAQAAIfZBbA>: sieve: msgid=unspecified: stored mail into mailbox 'INBOX'
28.01.2019, 19:32:29 | info | imap(mail@mail)<358><vLwp5oiAlLCsFgH4>: Logged out in=319 out=2551 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=2 body_count=0 body_bytes=0
28.01.2019, 19:32:30 | info | imap(mail@mail)<361><fvo+5oiAmLCsFgH4>: Logged out in=319 out=2520 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=2 body_count=0 body_bytes=0
28.01.2019, 19:32:31 | info | imap(mail@mail)<364><nE9Q5oiAnLCsFgH4>: Logged out in=319 out=2512 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=2 body_count=0 body_bytes=0
28.01.2019, 19:32:34 | info | imap(mail@mail)<370><ioZ75oiAqrCsFgH4>: Logged out in=91 out=1202 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:32:34 | info | imap(mail@mail)<367><WQJ35oiApLCsFgH4>: Logged out in=91 out=1202 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:32:56 | err | indexer-worker(mail@mail)<356><MCWmLNhKT1xiAQAAIfZBbA:wKl6L9hKT1xkAQAAIfZBbA>: Error: Mailbox INBOX: Status lookup failed: Internal error occurred. Refer to server log for more information. [2019-01-28 19:32:56]
28.01.2019, 19:32:56 | err | indexer-worker(mail@mail)<356><MCWmLNhKT1xiAQAAIfZBbA:wKl6L9hKT1xkAQAAIfZBbA>: Error: fts_solr: Lookup failed: connect(172.22.1.3:8983) failed: Connection refused (2 attempts in 0.020 secs)
28.01.2019, 19:32:56 | info | lmtp(354): Disconnect from 172.22.1.4: Client has quit the connection (state=READY)
28.01.2019, 19:32:56 | info | lmtp(mail@mail)<354><MCWmLNhKT1xiAQAAIfZBbA>: sieve: msgid=unspecified: stored mail into mailbox 'INBOX'
28.01.2019, 19:32:56 | info | lmtp(354): Connect from 172.22.1.4
28.01.2019, 19:33:32 | info | imap(mail@mail)<389><gASr6YiADrGsFgH4>: Logged out in=1298 out=1822 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
28.01.2019, 19:33:32 | err | indexer-worker(mail@mail)<356><gASr6YiADrGsFgH4:MGrgFvxKT1xkAQAAIfZBbA>: Error: Mailbox Sent: Status lookup failed: Internal error occurred. Refer to server log for more information. [2019-01-28 19:33:32]
28.01.2019, 19:33:32 | err | indexer-worker(mail@mail)<356><gASr6YiADrGsFgH4:MGrgFvxKT1xkAQAAIfZBbA>: Error: fts_solr: Lookup failed: connect(172.22.1.3:8983) failed: Connection refused (2 attempts in 0.004 secs)
28.01.2019, 19:33:48 | info | imap(mail@mail)<393><nYjd6oiATLGsFgH4>: Logged out in=321 out=3262 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=4 body_count=0 body_bytes=0
28.01.2019, 19:35:06 | info | pop3-login: Disconnected (no auth attempts in 9 secs): user=<>, rip=104.131.146.54, lip=172.22.1.8, TLS handshaking: Connection closed
28.01.2019, 19:36:02 | info | imapmail@mail)<445><KlvZ8oiA7rGsFgH4>: Logged out in=321 out=3255 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=4 body_count=0 body_bytes=0

28.01.2019, 19:47:00 | info | imap(mail@mail)<612><1ccYGomAFLWsFgH4>: Logged out in=321 out=3263 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=4 body_count=0 body_bytes=0

`
Postfix
`

28.01.2019, 19:19:55 | info | To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
-- | -- | --
28.01.2019, 19:19:55 | info | See http://www.postfix.org/COMPATIBILITY_README.html for details
28.01.2019, 19:19:55 | info | Postfix is running with backwards-compatible default settings
28.01.2019, 19:19:58 | info | daemon started -- version 3.3.0, configuration /opt/postfix/conf
28.01.2019, 19:19:58 | info | starting the Postfix mail system
28.01.2019, 19:30:48 | info | disconnect from unknown[172.22.1.1] helo=1 starttls=1 commands=2
28.01.2019, 19:30:48 | info | lost connection after STARTTLS from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | connect from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | disconnect from unknown[172.22.1.1] commands=0/0
28.01.2019, 19:30:48 | info | lost connection after CONNECT from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | connect from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | disconnect from unknown[172.22.1.1] helo=1 starttls=1 commands=2
28.01.2019, 19:30:48 | info | lost connection after STARTTLS from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | Anonymous TLS connection established from unknown[172.22.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:30:48 | info | connect from unknown[172.22.1.1]
28.01.2019, 19:30:48 | info | WHITELISTED [172.22.1.1]:60974
28.01.2019, 19:30:48 | info | CONNECT from [172.22.1.1]:60974 to [172.22.1.4]:25
28.01.2019, 19:30:48 | info | cache proxy:btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries
28.01.2019, 19:32:23 | info | connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
28.01.2019, 19:32:24 | info | 2CB8F1036F8: message-id=<>
28.01.2019, 19:32:24 | info | 2CB8F1036F8: client=mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248], sasl_method=PLAIN, sasl_username=mail@mail
28.01.2019, 19:32:26 | info | 2CB8F1036F8: from=<mail@mail>, size=1070, nrcpt=1 (queue active)
28.01.2019, 19:32:26 | info | disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
28.01.2019, 19:32:27 | info | 2CB8F1036F8: removed
28.01.2019, 19:32:27 | info | 2CB8F1036F8: to=<mail@mail>, relay=dovecot[172.22.1.8]:24, delay=3, delays=2.7/0.06/0.09/0.15, dsn=2.0.0, status=sent (250 2.0.0 <mail@mail> oeqWOLpKT1xiAQAAIfZBbA Saved)
28.01.2019, 19:32:56 | info | 7C7801036F8: removed
28.01.2019, 19:32:56 | info | 7C7801036F8: to=<mail@mail>, relay=dovecot[172.22.1.8]:24, delay=0.35, delays=0.27/0.01/0.01/0.06, dsn=2.0.0, status=sent (250 2.0.0 <mail@mail> MCWmLNhKT1xiAQAAIfZBbA Saved)
28.01.2019, 19:32:56 | info | disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
28.01.2019, 19:32:56 | info | 7C7801036F8: from=<mail@mail>, size=1104, nrcpt=1 (queue active)
28.01.2019, 19:32:56 | info | 7C7801036F8: message-id=<>
28.01.2019, 19:32:56 | info | 7C7801036F8: client=mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248], sasl_method=PLAIN, sasl_username=mail@mail
28.01.2019, 19:32:56 | info | connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
28.01.2019, 19:33:27 | info | connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
28.01.2019, 19:33:28 | info | 24356103700: message-id=<3d-5c4f4b00-1-61be3680@107615767>
28.01.2019, 19:33:28 | info | 24356103700: client=mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248], sasl_method=PLAIN, sasl_username=mail@mail
28.01.2019, 19:33:32 | info | 24356103700: replace: header Received: from 080b315b2939 (mailcowdockerized_sogo-mailcow_: Received: from localhost (localhost [127.0.0.1]) (Authenticated sender: mail@mail)??by mail.domain (Postcow) with ESMTPA id 24356103700??for <test-18czl@mail-tester.com>; Mon, 28 Jan 2019 19:33:28 +0100 (CET)
28.01.2019, 19:33:32 | info | Anonymous TLS connection established to mail-tester.com[94.23.206.89]:25: TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits)
28.01.2019, 19:33:32 | info | disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
28.01.2019, 19:33:32 | info | 24356103700: from=<mail@mail>, size=1393, nrcpt=1 (queue active)
28.01.2019, 19:33:33 | info | 24356103700: removed
28.01.2019, 19:33:33 | info | 24356103700: to=<test-18czl@mail-tester.com>, relay=mail-tester.com[94.23.206.89]:25, delay=5.1, delays=4.1/0.12/0.55/0.32, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 644D69F886)
`

**Comment by andryyy** [comment]
In these Postfix logs are no errors. All mails were stored in inbox. :/

**Comment by tankersss** [comment]
Those were only sent mails, and two that are system ones (about callendar) but when I tried sending an email from my gmail account I only got message back saying
`
550 5.7.1 <mail@mail>: Relay access denied
`

**Comment by andryyy** [comment]
We need those logs. You need to send yourself a mail from GMail while you are logging.

If these are your actual logs, your MX is probably not correct.

**Comment by tankersss** [comment]
> We need those logs. You need to send yourself a mail from GMail while you are logging.
> 
> If these are your actual logs, your MX is probably not correct.

Ok, it was MX problem, I set it up to point at the mail.domain.zx and it was the only one on the list, and somehow now as I logged on secondary PC there were 5 records pointing to some weird exchanges. Thanks for pointing that up Kudos
