### ISSUE TITLE
Bad Gateway on fresh install

### ISSUE THREAD

**Issue by HorstNet** [mailcow/mailcow-dockerized#2240]
Hello there!
I would love to use mailcow but unfortunately sth. is driving me crazy.

Followed the installation steps from documentation but were not able to see anything than "bad gateway". For / and /SOGo using http and https

System is not behind proxy and it is fresh installed just for mailcow:
`Linux mail-server 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`
10Gb sys, 25Gb /docker and /opt as iscsi storage and 1Tb for Volumes as nfs
my mailcowversion was cloned yesterday last time.

No need for ipv6. System is internal server no root server or else. Private IP.
Letsencrypt is set to skip.

For storage i've created a docker-compose.override:

version: '2.1'
volumes:
  vmail-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/vmail
      o: bind
  mysql-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/mysql
      o: bind
  redis-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/redis
      o: bind
  rspamd-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/rspamd
      o: bind
  postfix-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/postfix
      o: bind
  crypt-vol-1:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/crypt
      o: bind
  rspamd-sock:
    driver_opts:
      type: none
      device: /mnt/MailCowDataDir/rspamd-sock
      o: bind

Seems to work without problems.

All containers are  starting.
Here are the logs:

- mysql https://pastebin.com/XpyFGq0X
- nginx https://pastebin.com/bfeqfVk0
- php-fpm only shows:
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...

Sogo says the same:
sogo-mailcow_1       | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...

mailcow.conf is standard generated with the cli command.

I've tried to disable ipv6 and oom_control seperate and together with no difference.
Netstat -tulpen: https://pastebin.com/728Vvu1N
docker ps : https://pastebin.com/M4ffQv8x

sysctl net.ipv4.conf.all.forwarding and sysctl net.ipv6.conf.all.forwarding are all fine
ip6tables -S https://pastebin.com/ncQ7YSTE
iptables -S https://pastebin.com/JDLwg9Zr
(looking okay to me)

172.22.1.1 - 172.22.1.13 are reachable from host (ping)

Gone through the whole bugtracker and google for any ideas but nothing.
deleting volumes, docker-compose down -v and so on done but with no effect. ( each conf change test cylce)

All is shouting "waiting for database". 
And i have no idea what to do next...

will send chocolate and bünting tee from ostfriesland as reward :)

**Comment by andryyy** [comment]
That's most likely a firewall issue. Do you use any netfilter rules?

**Comment by HorstNet** [comment]
Was also looking at the firewall. But it's a clean installed system only for mailcow.
No individual rules or config.

**Comment by andryyy** [comment]
Can you give me access? Curious what it is...

**Comment by HorstNet** [comment]
what do you need? ssh ?

**Comment by andryyy** [comment]
if it's okay and a fresh system with no other data, that would be great.

**Comment by HorstNet** [comment]
sure. will prepare and send you an email

**Comment by HorstNet** [comment]
Due to Server Test Setting NFS Share was mounted via FastEthernet Nic.
This seems to be too slow overall:

mysql-mailcow_1      | 2019-01-29 11:12:58 140623026767808 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2019-01-29 11:13:33 140623026767808 [Note] InnoDB: File './ibtmp1' size is now 12 MB

If init was not performed before the procedure breaks here.
mysql-mailcow_1      | MySQL init process in progress...
mysql-mailcow_1      | MySQL init process in progress...
mysql-mailcow_1      | MySQL init process failed.

(Storage is fast enough as the iscsi volumes are on the same zfs pool but connected via intel gigabit nic;
different nic and net for iscsi, nfs )

Thanks to @andryyy it's now running fine!

**Comment by andryyy** [comment]
We started SQL without mount, rsync'ed the initialized database to the share and reactivated the mount.
