### ISSUE TITLE
Dockerproblem at installation

### ISSUE THREAD

**Issue by Nononitas** [mailcow/mailcow-dockerized#2242]
Hello,

so I followed the introduction for the installation to this point:
`docker-compose pull`
As I typed it in it downloads the content but after that this happens
I don't know what to do. Please help me :)

Ubunut: 16.04
```
ERROR: for netfilter-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for nginx-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for memcached-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for acme-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for rspamd-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for ipv6nat  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for postfix-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for solr-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for mysql-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for redis-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for watchdog-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for unbound-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for sogo-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for dovecot-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for dockerapi-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for clamd-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied

ERROR: for php-fpm-mailcow  failed to register layer: Error processing tar file(exit status 1): permission denied
ERROR: failed to register layer: Error processing tar file(exit status 1): permission denied

```

**Comment by andryyy** [comment]
System info? :)

Permission denied?! Which user did you use?

LXC?

**Comment by Nononitas** [comment]
root user 
16 GB RAM
x86_64
it's a vserver

**Comment by andryyy** [comment]
KVM?

**Comment by Nononitas** [comment]
Virtualization:        VT-x
is this want you want to know?

**Comment by Nononitas** [comment]
> 
> 
> KVM?

Weißt du warum es nicht geht?

**Comment by Nononitas** [comment]
Kannst du mir helfen?

**Comment by andryyy** [comment]
Ich muss wissen, ob das ein Container oder eine VM ist. Das ist ein Docker Problem, in jedem Fall. Oder ist es vielleicht sogar ein OpenVZ Gedöns? Das verkaufen manche ja tatsächlich immer noch. 😢

**Comment by Nononitas** [comment]
Also fall es weiter hilft ich hoste bei gamed.de 
Und kann man das über ein Befehl rausfinden?

**Comment by andryyy** [comment]
Hm, was sagte er denn bei `uname -a`?

**Comment by Nononitas** [comment]
Linux Nono 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 x86_64 x86_64 GNU/Linux

**Comment by andryyy** [comment]
Ist ein Container. Finde es schade, wenn Hoster das nicht ausdrücklich hinschreiben. :-(

**Comment by Nononitas** [comment]
Also unmöglich das es geht?

**Comment by andryyy** [comment]
Glaube das ist abhängig vom Kernel. Am besten fragst du dort mal nach. :)

**Comment by Nononitas** [comment]
Ok, alles klar.
Dann danke erstmal für die Hilfel :)

**Comment by Nononitas** [comment]
Ok, alles klar.
Dann danke erstmal für die Hilfel :)

**Comment by JOduMonT** [comment]
my german is very poor but for what I could understand is @Nononitas try to run mailcow inside a container under proxmox

I succeed to run docker under container; but didn't try with mailcow
by executing this [script](https://github.com/extremeshok/xshok-proxmox/blob/master/pve-enable-lxc-docker.sh) which loose apparmor and cgroup on proxmox

**Comment by Braintelligence** [comment]
@jodumont Where did you spot anything about proxmox in this issue?

**Comment by JOduMonT** [comment]
@Braintelligence the **PVE** in the kernel 
[Linux Nono 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 x86_64 x86_64 GNU/Linux](https://github.com/mailcow/mailcow-dockerized/issues/2242#issuecomment-459373229)

**Comment by Braintelligence** [comment]
@jodumont Oh! Yeah that's right. Well actually I'm running Mailcow in a VM on Proxmox. Never had problems.

**Comment by paulwaldmann** [comment]
Does anyone have a solution to this problem? The script that @JOduMonT mentioned didn't work. Got also the same set up with Proxmox and PVE and it doesn't work.

**Comment by bbenjamin-sys** [comment]
> @JOduMonT Oh! Yeah that's right. Well actually I'm running Mailcow in a VM on Proxmox. Never had problems.
Hey, which version of proxmox ?

**Comment by Braintelligence** [comment]
Any version I've tried yet for the last years. Never had any problems.

**Comment by Adorfer** [comment]
the issue here looks more like "docker installed/ran with the wrong user/UID permissions".

**Comment by dokbua** [comment]
Looks like an LXC (CT). Make sure it's created with nesting=1 (under features).
