### ISSUE TITLE
Make Password Policy more user friendly

### ISSUE THREAD

**Issue by wedi** [mailcow/mailcow-dockerized#2243]
The current password strength policy is somewhat annoying as the user does not get any feedback about the actual password policy.
Per the well known xkcd comic I'd suggest to change the policy to length only, make it configurable and set a strong default length requirement instead. Gold plating: Check against username/localpart/domain and keep an aditional (optional) regex check and add a description text.

Any feedback on this? I'd be willing to implement it.

![xkcd Password Strength](https://imgs.xkcd.com/comics/password_strength.png)

**Comment by andryyy** [comment]
I think I reverted it but haven’t pushed yet.

**Comment by wedi** [comment]
What about an (optional) length requirement which can be explained easily to the average user?

**Comment by wedi** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/2191#issuecomment-456736509 😁
https://github.com/mailcow/mailcow-dockerized/issues/2163
https://github.com/mailcow/mailcow-dockerized/issues/1059
