### ISSUE TITLE
Sent emails going to spam, DNS showing that is configured correctly

### ISSUE THREAD

**Issue by colevan94** [mailcow/mailcow-dockerized#2244]
Can I send someone an email to test, preferably who has their own server setup as I am not seeing the issue when sending to gmail, yahoo, etc. but typically to other private servers.

**Comment by andryyy** [comment]
OVH/Online.net? New domain? New domain/IP combination?

**Comment by colevan94** [comment]
The domain, is not that old maybe 6 months and the domain ip combination is somewhat new I had a static block assigned a couple weeks ago.

**Comment by andryyy** [comment]
And which provider? Server provider. :)

**Comment by colevan94** [comment]
AT&T Fiber

**Comment by colevan94** [comment]
Oh server provider, I have my own servers

**Comment by andryyy** [comment]
What is your IP (if you want to tell)? This can be critical. Have you checked your IPs against blacklists?

**Comment by colevan94** [comment]
What do you mean if you want to dell?

**Comment by colevan94** [comment]
I have checked blacklists saw nothing

**Comment by colevan94** [comment]
can I send you the IP privately so I'm not broadcasting my address on the public forum

**Comment by colevan94** [comment]
Found out via GlockAPPS mail testing this is only when sending to outlook or hotmail mailboxes or private domains that use outlook. Do you know a fix for this @andryyy

**Comment by andryyy** [comment]
It is not related to mailcow but your reputation. You cannot force them to accept your mails. 

New domain/ip combo is always problematic. Outlook is very, very difficult. Just send more ham to them. Your reputation will increase. Don’t send a hundred test mails with nonsense. This will hurt your reputation. Just use your domain and make sure people move your mails from junk to inbox. 

It does NOT matter that your IP is not blacklisted.

**Comment by colevan94** [comment]
Ok, thats kinda what I figured thank you for your help.
