### ISSUE TITLE
Es startet nicht.

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#2249]
Ich hab ein Problem, meine Innstallation startet nicht mehr.
Ich kann leider nicht genau sagen, seid wann mein Server Offline ist.
Ubuntu 18.04.01 LTS

DAs ergebniss vom docker-compose logs -f --tail=1 postfix-mailcow zu posten, fällt mir schwer, weil es ständig was dazu kommt.
Aufs SOgo hab ich keinen zugriff.
Könntet ihr mir helfen, das alles wieder geht?

**Comment by andryyy** [comment]
Habe gerade ein paar Minuten, könntest mir einmal mailen an info@servercow.de

**Comment by Conan179** [comment]
Ok
