### ISSUE TITLE
PDOException when Domain have 2 or more Domain aliases

### ISSUE THREAD

**Issue by SemikolonDEV** [mailcow/mailcow-dockerized#225]
Hi Guys,

since the last commit, I had the problem, that I got a PDOException in the Domain part of the Adminpanel:
`MySQL: PDOException: SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 row in /web/inc/functions.inc.php:4303 Stack trace: #0 /web/inc/functions.inc.php(4303): PDOStatement->execute(Array) #1 /web/json_api.php(35): mailbox_get_domain_details('semikolon.cf') #2 {main}`

I've solved the problem manually, with this commands:
`
docker-compose exec mysql-mailcow bash
mysql -uroot -p
use mailcow;
delete from alias_domain where alias_domain='ONE OF YOUR DOMAIN-ALIAS';
`
Check if it works and you can quit the SQL-Container when you type at first `quit;` and then `exit`.

Best Regards
Jan-Lukas Pagel

**Comment by andryyy** [comment]
Hi,
Thanks! :)
