### ISSUE TITLE
Small Conflict after update.sh

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2250]
Hello,
with new update.sh i get a small conflict error that shows in log:

CONFLICT (rename/delete): data/conf/rspamd/custom/global_mime_from_whitelist.map deleted in HEAD and renamed in refs/remotes/origin/master. Version refs/remotes/origin/master of data/conf/rspamd/custom/global_mime_from_whitelist.map left in tree.
CONFLICT (rename/delete): data/conf/rspamd/custom/global_mime_from_blacklist.map deleted in HEAD and renamed in refs/remotes/origin/master. Version refs/remotes/origin/master of data/conf/rspamd/custom/global_mime_from_blacklist.map left in tree.
Automatic merge failed; fix conflicts and then commit the result.
Potenial conflict, trying to fix...
rm: missing operand
Try 'rm --help' for more information.

But all is working fine...

**Comment by andryyy** [comment]
Thanks, I fixed that a few minutes after the first push. :) Sorry.
