### ISSUE TITLE
CalDAV not working on EM Client

### ISSUE THREAD

**Issue by LightRO** [mailcow/mailcow-dockerized#2252]
Hello everybody,

I have a problem with the CalDAV. I keep getting the message that I'm not authorized to access the calendar. At least with EM Client. With Outlook 2010 and the webdav plugin the error comes, The IMAP protocol does not support folders with special function.

What can I do to make this work?
Many Greetings,
LightRO

**Comment by andryyy** [comment]
Are you sure you are pointing your DNS to mailcow? I am using it with em Client all the time. That we don't support special_use in IMAP is also not correct.

You need to post dovecot-mailcow logs and/or nginx-mailcow and sogo-mailcow for the time this happens. Just keep `docker-compose logs -f --tail=1 nginx-mailcow sogo-mailcow dovecot-mailcow` open while testing it. Paste the output then.

**Comment by LightRO** [comment]
yes, the DNS settings should actually all fit. Autodiscover works without any problems and the certificates are also integrated. For EM Client there is always the message: The subfolder of the folder "test" could not be synchronized: Not Allowed

and the log from your command:

```
on closed for user sogo
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:03 +0100] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:03 +0100] "GET /settings.php HTTP/1.1" 200 1223 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:36 +0100] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:36 +0100] "GET /settings.php HTTP/1.1" 200 1223 "-" "-"
dovecot-mailcow_1    | Jan 31 00:12:36 mail dovecot: imap(test@test.de)<1393><+kZIE7KACc5NBxn5>: Mailbox deleted: WebDAV
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:40 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:12:40 +0100] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "-"
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5497]: pam_unix(cron:session): session opened for user root by (uid=0)
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5500]: (root) CMD ( /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5498]: pam_unix(cron:session): session opened for user vmail by (uid=0)
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5502]: (vmail) CMD (/usr/local/bin/trim_logs.sh >> /dev/console 2>&1)
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5498]: pam_unix(cron:session): session closed for user vmail
dovecot-mailcow_1    | Jan 31 00:13:01 mail CRON[5497]: pam_unix(cron:session): session closed for user root
sogo-mailcow_1       | Jan 31 00:13:01 34b0dba6f84f CRON[2331]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jan 31 00:13:01 34b0dba6f84f CRON[2334]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Jan 31 00:13:01 34b0dba6f84f CRON[2332]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jan 31 00:13:01 34b0dba6f84f CRON[2336]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Jan 31 00:13:02 34b0dba6f84f CRON[2332]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Jan 31 00:13:02 34b0dba6f84f CRON[2331]: pam_unix(cron:session): session closed for user sogo
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:13:10 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::1 - - [31/Jan/2019:00:13:10 +0100] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "-"
```

**Comment by andryyy** [comment]
There is no connect to your server. I only see "Mailbox deleted", but that's all. No connect to DAV or other connections (from Outlook for example).

**Comment by LightRO** [comment]
here thats i get when i try to add the caldav 

dovecot-mailcow_1    | Jan 31 00:12:36 mail dovecot: imap(test@test.de)<1393><+kZIE7KACc5NBxn5>: Mailbox deleted: WebDAV

i see the connection to the server. When i try to open the path from DAV in the Webbrowser i can see the login mask for that.

**Comment by andryyy** [comment]
Why would it delete a mailbox called WebDAV? You misconfigured something. :( IMAP is not even related to DAV. Both are different services.

Nginx and SOGo would log that access. I guess you are using some reverse proxy setup?

em Client will work fine with a default installation. I just tested it again to be 100% sure. Check your reverse proxy and DNS, please. 

Which DAV path do you use?

**Comment by andryyy** [comment]
Autodiscovered:

![grafik](https://user-images.githubusercontent.com/2972950/52019673-d708b800-24ee-11e9-9a18-24b129ae7d9c.png)

**Comment by LightRO** [comment]
Yes, I use some reverse. Unfortunately, this is not possible to solve otherwise. I have as main installation PLESK this uses port 80,443,8443.
Then I gave Mailcow the ports 8080 and 4343.
I have also created and inserted all the certificates. So many configuration options you have not there. But as I said, I had to come up with something else and this read only with the proxys realize.

I go to the link: https://redxnet.de/SOGo/dav/

**Comment by andryyy** [comment]
The RP setup seems to be broken then.

You can post your config, but I am sure you will run into problems with Plesk on the server. Iirc Plesk also messes with iptables/netfilter rules.

**Comment by LightRO** [comment]
I can show the config tomorrow. In addition, I just noticed that Outlook 2010 can now connect to the CalDAV. Only EM client unfortunately not.

**Comment by LightRO** [comment]
So, today I am a little better receptive than last night. It is so, I want the configuration of CalDAV and CardDAV via Autodiscover included and configured. But I do not know if that's possible at all. Ansich the rest works very well. But exactly the 2 services like calendar and contacts are the ones I need. There is also a problem with the configuration on the iPhone. He does not want to connect.

My reverse looks like this:

`location /SOGo {
	rewrite ^/$ /SOGo;
	proxy_pass https://ipadress:4343;
	proxy_set_header Host $http_host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	client_max_body_size 100m;
}

location /autodiscover {
	rewrite ^/$ /autodiscover/;
	proxy_pass https://ipadress:4343;
	proxy_set_header Host $http_host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	client_max_body_size 100m;
}

location /Autodiscover {
	proxy_pass https://ipadress:4343/autodiscover/;
}`

**Comment by Braintelligence** [comment]
To be frank: I think this is not an issue that should be a ticket here but rather a support request. You should contact andryyy in the role of a paid consultant or wait for others to answer this.
Andryyy is really investing way too much of his free time in such support requests that are not real bugs but devops issues.

**Comment by LightRO** [comment]
i have resolve the most from this problem. EM Client ist working now, IPhone is working now and office 2010 is working now. but autodiscover is not working fine. As this reason i tryed a test from microsofts autodiscover page. i get following result: 


he Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://mail.test.de:4343/Autodiscover/Autodiscover.xml for user info@test.de.
--
  | The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
  | Additional Details 

None of the expected XML elements were found in the XML response.
HTTP Response Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Strict-Transport-Security: max-age=15768000;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin
Content-Type: application/xml
Date: Wed, 06 Feb 2019 21:09:41 GMT
Server: nginx
Elapsed Time: 1351 ms. 

I think that the generated XML File is not working for autodiscover
