### ISSUE TITLE
[Feature] Quarantine email enhancments, add direct actions /release/spam

### ISSUE THREAD

**Issue by extremeshok** [mailcow/mailcow-dockerized#2253]
Similar to how all the other quarantine reports work, the user will be presented by a list of quarantined messages there are buttons/links for them to directly mark an email as spam or release it.

This allows for an improved workflow, single click to release, 
Currently a user must open their browser, login to the admin interface, view their quarantine, find the message, then finally release the message.

I have attached sample email reports as an example from popular systems
Barracuda
![barracuda](https://user-images.githubusercontent.com/5957328/52030064-afc9df00-251e-11e9-8b1f-41f6905b2cfd.png)
Exchange
![exchange](https://user-images.githubusercontent.com/5957328/52030065-b0627580-251e-11e9-98ac-4fc1c187c70f.png)
Fortinet
![fortinet](https://user-images.githubusercontent.com/5957328/52030066-b0627580-251e-11e9-9a74-38a96d039643.png)
Mailcleaner
![mailcleaner](https://user-images.githubusercontent.com/5957328/52030067-b0627580-251e-11e9-9743-41047ac9f513.png)
Office365
![office365](https://user-images.githubusercontent.com/5957328/52030068-b0fb0c00-251e-11e9-8d0c-57bfd593f91b.png)

**Comment by extremeshok** [comment]
proofpoint
![proofpoint](https://user-images.githubusercontent.com/5957328/52033115-77c99880-252c-11e9-93b3-b8a561d01211.png)
ushark
![ushark](https://user-images.githubusercontent.com/5957328/52033122-8021d380-252c-11e9-8357-ffc3ebf92a24.png)

**Comment by andryyy** [comment]
There is another issue regarding this topic. :)

How do they handle the release? Click and release? Or click, login, release?

**Comment by extremeshok** [comment]
They are all click and release.

users email address with a salt + the message id in the url and the action

**Comment by andryyy** [comment]
Thanks

**Comment by andryyy** [comment]
I added release and delete. Was a bit tricky, we need to test wether or not a user is allowed quarantine actions by acl.

We could have printed the links no matter the acl, but I also don't want to give a user feedback wether a release/delete actually worked (it only writes to log). You know ... like the "forgot my password" links that give feedback wether or not an email address is actually in use. They are bad.
So, what I want to say... imagine you send those links to a user without that acl active, they would click on the link, get no feedback and think "yay, worked", but no action was actually taken.

Table looks like this now:

```
    <table>
    <tr><th>Subject</th><th>Sender</th><th>Arrived on</th><th>Actions</th></tr>
    {% for line in meta %}
    <tr>
    <td>{{ line.subject|e }}</td>
    <td>{{ line.sender|e }}</td>
    <td>{{ line.created }} {{ line.quarantine_acl }}</td>
    {% if line.quarantine_acl == 1 %}
    <td><a href="https://{{ hostname }}/qhandler/release/{{ line.qhash }}">release</a> | <a href="https://{{ hostname }}/qhandler/delete/{{ line.qhash }}">delete</a></td>
    {% else %}
    <td>not available</td>
    {% endif %}
    </tr>
    {% endfor %}
    </table>
```

We also derive the text part from html now.

**Comment by extremeshok** [comment]
Consider the following, hiding the action column if they have no ACL
Is it possible to list the spam score for the email ? It helps make informed decisions, ie if the users wants to raise the spam scores or lower them, or how risky an email is.
```
<table>
    <tr><th>Subject</th><th>Sender</th><th>Arrived on</th>{% if line.quarantine_acl == 1 %}<th>Actions</th>{% endif %}</tr>
    {% for line in meta %}
    <tr>
    <td>{{ line.subject|e }}</td>
    <td>{{ line.sender|e }}</td>
    <td>{{ line.created }} {{ line.quarantine_acl }}</td>
    {% if line.quarantine_acl == 1 %}
    <td><a href="https://{{ hostname }}/qhandler/release/{{ line.qhash }}">release</a> | <a href="https://{{ hostname }}/qhandler/delete/{{ line.qhash }}">delete</a></td>
    {% endif %}
    </tr>
    {% endfor %}
    </table>
```

**Comment by andryyy** [comment]
Your code will not work when line is called outside the loop. Need to change more code for that.

**Comment by andryyy** [comment]
Moved the acl stuff outside and added the score:

![grafik](https://user-images.githubusercontent.com/2972950/52328355-9679d480-29ef-11e9-95d7-20592c6f6a3b.png)

**Comment by extremeshok** [comment]
looks awesome, thank you

**Comment by cklabautermann** [comment]
This feature would be awesome! When will it be implemented in mailcow? Right now I can´t see it yet.

**Comment by andryyy** [comment]
It's in master. :) Admin UI.

**Comment by cklabautermann** [comment]
Thanks! Do I need to insert the table code in your comment above in my notification template?
