### ISSUE TITLE
[enhancement] "Sender Maps" in "Address Rewriting" via UI

### ISSUE THREAD

**Issue by soulsymphonies** [mailcow/mailcow-dockerized#2259]
In the UI in the "Mail Setup" in the "Address Rewriting" in the "Recipient Maps" section it ispossible to rewrite incoming email addresses, if I'm seeing it right, then this is accomplished via recipient_canonical_maps and recipient_canonical_classes in combination with the mysql database.

Would it be possible to implement the same for outgoing email adresses, a section called "Sender Maps" in the UI, maybe via the sender_canonical_maps and sender_canoncial_classes options of postfix.

Thank you ever so much.
Robert

**Comment by andryyy** [comment]
I did once and removed it.

Not sure why though. But there were problems. DKIM/ARC maybe?

**Comment by soulsymphonies** [comment]
thank you for the quick response, if there's been problemns, is there any way for me that I could manually implement it myself, for example in the main.cf of postfix, via these directives:

```
sender_canonical_maps = hash:/opt/postfix/conf/sender_canonical_maps
sender_canonical_classes = sender_envelope
```
Then place the file sender_canonical_maps in that folder and run

> postmap sender_canonical_maps

so that I get the sender_canonical_maps.db and then reload the postfix system or even restart the postfix container

Would that work, or am I missing something?

**Comment by andryyy** [comment]
Sounds perfectly fine. :)
