### ISSUE TITLE
Domain-Admins will not be listed after update and user has no domains assigned

### ISSUE THREAD

**Issue by SemikolonDEV** [mailcow/mailcow-dockerized#226]
Hi Guys,

since the last update, I've the problem, that my Domain-Admins will not be listed in the Admin-Panel, but I can log me in, in this Account, but I've no assigned domains and no mailboxes.

I got no Exception or something like that.

Best regards
Jan-Lukas Pagel

**Comment by andryyy** [comment]
Can you check your cache? Some JS code changed, this -may- be the problem. Do you see an alert box in your browser?

**Comment by SemikolonDEV** [comment]
Hi André,

I tried it with 3 different browsers and 2 computers. With all browsers and computers, the same problems.

Mit freundlichen Grüßen
Jan-Lukas Pagel

**Comment by andryyy** [comment]
Can you please try and remove the domain admin completly? => 

```
delete from admin where username='your-domain-admin';
delete from domain_admins where username='your-domain-admin';
```

Then recreate the domain admin.

No data of any domain will be lost.

**Comment by SemikolonDEV** [comment]
I had only to remove the Admin from the admin Table.
I recreated the User in the panel and that works fine.

Mit freundlichen Grüßen
Jan-Lukas Pagel

**Comment by andryyy** [comment]
My guess is you accidentally deleted "from domain_admins" instead of "domain_alias" in the other issue. :) Is it possible?

**Comment by SemikolonDEV** [comment]
I haven't deleted the Domain Administrator from the panel only after the update the Database entrys are deleted.

Regards
Jan-Lukas Pagel

**Comment by broedli** [comment]
@SemikolonDEV is your issue solved?

Can we close this issue?

**Comment by SemikolonDEV** [comment]
Last week after an Update the User was already deleted to the half in the Database.

Regards
Jan-Lukas Pagel
