### ISSUE TITLE
Open incoming mail in new window - printed email is empty

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#2261]
**Describe the bug**
When I open an incoming Mail in a new window and then try to print it the paper is empty expect from URL, Header title, page index and date/time. The content of the mail is missing though. That doesn't happen if you print the mail without opening it in a new window first.

**How to reproduce Reproduce**
1. Login to Webmailer
2. Open Inbox
3. Select Email
4. Klick Button "Open in new Mail Window" in the upper right corner
5. This emails opens up in a new browser window
6. Klick Menu Button (three dots in upper right corner)
7. Print
8. Empty page is printed

**Expected behavior**
The page printed should not be empty

**Screenshots**

**Logs**
no relevant logs found

**Client System**
- Linux Fedora and Windows 10 tried with same result
- Firefox 61.0.3

**Server System**
- CentOS 7.6.1810
- commit e090b1c648e891e3f5a255b6cb10de040c7c5aa3

**Comment by andryyy** [comment]
Hi, thanks, can you report that to SOGos bug tracker?

**Comment by imp1sh** [comment]
https://sogo.nu/bugs/view.php?id=4674

**Comment by imp1sh** [comment]
The upstream ticket had been closed but I don't know if it's already in Mailcow, please check.

**Comment by hachre** [comment]
I just tried to reproduce on the latest Mailcow and it seems fixed. Also it's showing we're using SOGo 4.0.7, which should have the bugfix. If you can still reproduce this on the latest Mailcow version, please let me know. Keeping it closed for now.
