### ISSUE TITLE
SOGo not available for NGINX (new installation)

### ISSUE THREAD

**Issue by muisklik** [mailcow/mailcow-dockerized#2264]
Mailcow is a new installation and all containers are up and running. NGINX is unable to connect to SOGo on port 20000.
From the NGINX-log: [error] 15#15: *417 connect() failed (111: Connection refused) while connecting to upstream, client: 11.22.33.44, server: xx.yy.zz, request: "GET /SOGo/ HTTP/1.1", upstream: "http://172.22.1.248:20000/SOGo/", host: "xx.yy.zz", referrer: "https://xx.yy.zz/"

From the SOGo-container (netstat -an):
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.11:46133        0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:20000         0.0.0.0:*               LISTEN     
tcp        0      0 172.22.1.248:42540      172.22.1.249:6379       ESTABLISHED
tcp        0      0 172.22.1.248:42538      172.22.1.249:6379       ESTABLISHED
udp        0      0 127.0.0.11:33088        0.0.0.0:*                          
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     234019609 /var/lib/syslog-ng/syslog-ng.ctl
unix  2      [ ACC ]     STREAM     LISTENING     234020279 /dev/log
unix  3      [ ]         STREAM     CONNECTED     234040974 
unix  3      [ ]         STREAM     CONNECTED     234040973 
unix  3      [ ]         STREAM     CONNECTED     234042204 /var/run/mysqld/mysqld.sock
unix  3      [ ]         STREAM     CONNECTED     234042203 

From the SOGo-container (ifconfig):
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.22.1.248  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::42:acff:fe16:1f8  prefixlen 64  scopeid 0x20<link>
        inet6 fd4d:6169:6c63:6f77::c  prefixlen 64  scopeid 0x0<global>
        ether 02:42:ac:16:01:f8  txqueuelen 0  (Ethernet)
        RX packets 38  bytes 2620 (2.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 39  bytes 2446 (2.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 52  bytes 3222 (3.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 52  bytes 3222 (3.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

From the SOGo-log:
Feb 05 10:40:45 sogod [392]: vmem size check enabled: shutting down app when vmem > 384 MB. Currently at 205 MB
Feb 05 10:40:45 sogod [392]: <0x0x555d1ebcf4b0[SOGoProductLoader]> SOGo products loaded from '/usr/lib/GNUstep/SOGo':
Feb 05 10:40:45 sogod [392]: <0x0x555d1ebcf4b0[SOGoProductLoader]>   ActiveSync.SOGo, AdministrationUI.SOGo, Appointments.SOGo, CommonUI.SOGo, Contacts.SOGo, ContactsUI.SOGo, MailPartViewers
.SOGo, Mailer.SOGo, MailerUI.SOGo, MainUI.SOGo, PreferencesUI.SOGo, SchedulerUI.SOGo
Feb 05 10:40:46 sogod [392]: All products loaded - current memory usage at 273 MB
Feb 05 10:40:46 sogod [392]: <0x0x555d1ecca5c0[WOWatchDog]> listening on 127.0.0.1:20000
Feb 05 10:40:46 sogod [392]: <0x0x555d1ecca5c0[WOWatchDog]> watchdog process pid: 392
Feb 05 10:40:46 sogod [392]: <0x0x7fea83d03ee0[WOWatchDogChild]> watchdog request timeout set to 10 minutes
Feb 05 10:40:46 sogod [392]: <0x0x555d1ecca5c0[WOWatchDog]> preparing 1 children
Feb 05 10:40:46 sogod [392]: <0x0x555d1ecca5c0[WOWatchDog]> child spawned with pid 393
Feb 05 10:40:46 sogod [393]: <0x0x555d1eaa5df0[WOHttpAdaptor]> notified the watchdog that we are ready

What is wrong in my setup?

**Comment by andryyy** [comment]
Probably firewall rules.

`docker-compose exec nginx-mailcow nc -z sogo 20000 && echo ok || echo nok`?

**Comment by muisklik** [comment]
Result is nok. How to add the firewall rule?

**Comment by andryyy** [comment]
Don't mess with Dockers rules and use DOCKER_USER for all other stuff only.

You need to disable your ruleset (aka disable your fw), restart Docker and use DOCKER_USER for your own rules. :)

**Comment by muisklik** [comment]
When I run the command: iptables -I DOCKER-USER -i ext_if ! -s 172.22.1.0/24 -j DROP I get an error message: iptables: No chain/target/match by that name.

**Comment by andryyy** [comment]
Yes. "_"

**Comment by muisklik** [comment]
Please explain what you mean. Replacing "_" with "-" in ext_if doesn't solve the error.

**Comment by andryyy** [comment]
DOCKER-USER != DOCKER_USER

**Comment by muisklik** [comment]
Still the same error message.

**Comment by muisklik** [comment]
Docker is running on a Synology NAS with DSM 6 latest version.

**Comment by andryyy** [comment]
You probably flushed all docker rules. Remove your firewall setup and restart the Docker service to recreate them.

I also don't know if it will work on a Synology NAS and have serious doubts. It probably has its own funny netfilter rules, NAT etc.

**Comment by muisklik** [comment]
The firewall is switched off in DSM. Does Docker use a firewall of its own?
Other containers are working (ie NGINX for Mailcow UI).

**Comment by muisklik** [comment]
Did some more digging and found the following:
ash-4.3# docker exec mailcowdockerized_sogo-mailcow_1 nc -z 127.0.0.1 20000 && echo ok || echo nok
ok
ash-4.3# docker exec mailcowdockerized_sogo-mailcow_1 nc -z 172.22.1.248 20000 && echo ok || echo nok
nok
Apparently SOGo listens on IP-address 127.0.0.1 and not on the external IP-address.
In SOGo.conf it reads WOPort = "0.0.0.0:20000" and changing to WOPort = "172.22.1.48:20000" doesn't resolve it (of course after restarting SOGo-container).

**Comment by andryyy** [comment]
No idea then, probably not possible to run it on Synology.

**Comment by muisklik** [comment]
Closing issue.
