### ISSUE TITLE
SOGo not accessible on external IP-address

### ISSUE THREAD

**Issue by muisklik** [mailcow/mailcow-dockerized#2265]
SOGo is not accessible on it's external IP-address.
ash-4.3# docker exec mailcowdockerized_sogo-mailcow_1 nc -z 127.0.0.1 20000 && echo ok || echo nok
ok
ash-4.3# docker exec mailcowdockerized_sogo-mailcow_1 nc -z 172.22.1.248 20000 && echo ok || echo nok
nok

Apparently SOGo listens on IP-address 127.0.0.1 and not on the external IP-address.
In SOGo.conf it reads WOPort = "0.0.0.0:20000" and changing to WOPort = "172.22.1.48:20000" doesn't resolve it (of course after restarting SOGo-container).

**Comment by andryyy** [comment]
Nah, it is listening inside the container von 0.0.0.0 2000/tcp and does that just fine. :)
