### ISSUE TITLE
No child available to handle incoming request!

### ISSUE THREAD

**Issue by PiCTaTe** [mailcow/mailcow-dockerized#2266]
Hi,

My logs are constantly with bellow error.

> sogo-mailcow_1       | Feb  4 18:15:31 05e81f192545 sogod [11]: [WARN] <0x0x557253cc7640[WOWatchDogChild]> pid 455 has been hanging in the same request for 6 minutes
 > sogo-mailcow_1       | Feb  4 18:15:31 05e81f192545 sogod [11]: [WARN] <0x0x557253c672c0[WOWatchDogChild]> pid 52 has been hanging in the same request for 8 minutes
 > sogo-mailcow_1       | Feb  4 18:15:41 05e81f192545 sogod [11]: [WARN] <0x0x557253c5b1c0[WOWatchDogChild]> pid 448 has been hanging in the same request for 13 minutes
> sogo-mailcow_1       | Feb  4 18:15:41 05e81f192545 sogod [11]: [WARN] <0x0x557253e0a630[WOWatchDogChild]> pid 72 has been hanging in the same request for 13 minutes

After some time, sogo locks with bellow error:

    > sogo-mailcow_1       | Feb  5 11:38:30 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:30 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:30 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:31 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!
    > sogo-mailcow_1       | Feb  5 11:38:32 05e81f192545 sogod [11]: [ERROR] <0x0x56396fb74f00[WOWatchDog]> No child available to handle incoming request!

I have 280 mailboxes.

My configuration:
 WOWorkersCount = "50";
 SxVMemLimit = 384;
 SOGoMaximumPingInterval = 3540;
 SOGoInternalSyncInterval = 45;
 SOGoMaximumSyncInterval = 60;

**Comment by andryyy** [comment]
Workers count needs to be increased. :)

**Comment by PiCTaTe** [comment]
You have any idea that how many workers I need to 280 mailboxes?

**Comment by andryyy** [comment]
Depends on the EAS usage. Start with 100 and watch the logs.

**Comment by PiCTaTe** [comment]
On this afternoon I had 100, but load of my server was between 90 and 110.. server was very slow!

What's the recommended memory for one sever with 100 workers?

I have 4gb.. with 2 cpus!

**Comment by andryyy** [comment]
That's not enough if you plan to keep EAS. I'd say 100-120 EAS workers need around 16-20 GB RAM and a lot of swap space, if you don't start a full EAS resync on all EAS device at the same time. I have seen machines with 20 GB and 300 workers running fine. That also depends on how sticky the workers are (lifetime => WOWatchDogRequestTimeout in minutes) and how intensive they are being used (100 resyncs at the same time => bad).
