### ISSUE TITLE
Minifying CSS breaks bootswatch theme

### ISSUE THREAD

**Issue by barry-smithjr** [mailcow/mailcow-dockerized#2267]
**Describe the bug**
If you set a custom Bootswatch theme in data/web/inc/vars.local.inc.php it will not load.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Define $DEFAULT_THEME in vars.local.inc.php to something other than lumen.
2. Load the webui and you will notice lumen is still displayed.

**Expected behavior**
For default theme elements to be displayed with the settings defined in the alternate theme.

**Logs**
No errors logged as all code is valid and nothing fails.

**System**
 - OS: Mac, Windows, Ubuntu
 - Browser: Chrome, Safari

**Additional context**
I was able to circumvent this problem by adding the line to include the darkly css file after the minify function in header.inc.php.

I have two instances. The most recent instance configured on 2019/02/04 has this issue. The older instance that was last updated on 2019/01/14 functions as expected. The latest commit has for the functional instance is 889b260b7df119190d9fa47d20bba43dbc7e7db4.

**Comment by andryyy** [comment]
Thanks, will be fixed with next push.
