### ISSUE TITLE
rspamd data for grafana

### ISSUE THREAD

**Issue by badsmoke** [mailcow/mailcow-dockerized#2268]
**Is your feature request related to a problem? Please describe.**

I don't like the rpsamd overview very much, I would like to visualize it myself in grafana

**Describe the solution you'd like**

i would like to have the possibility to retrieve/export the rspamd metric

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

there is already someone who did this with rspamd, but unfortunately it doesn't work with the mailcow dockerized version. Has the API been blocked there?

rspamd to influxdb to grafana:
https://github.com/thannaske/rspamd-influxdb

**Comment by andryyy** [comment]
It is not blocked. Which URL do you use?

**Comment by badsmoke** [comment]
https://domain.tld/rspamd/

**Comment by andryyy** [comment]
Ok. As long as you set a password you have your Rspamd endpoint ready. You can login, right?

**Comment by badsmoke** [comment]
yes exactly.

it all works

**Comment by ElishaDev** [comment]
@badsmoke you got fixed that?
