### ISSUE TITLE
Sync job issues ... accounts always resynced from zero

### ISSUE THREAD

**Issue by KGemini** [mailcow/mailcow-dockerized#2269]
Hi, I don't know if this is a problem of Mailcow of Imapsync; but I have a strange problem with Syncinc emails from two servers.
These are my configurations:

Single domain and 19 email account.
Server 1 production: Windows + Hmailserver 
Server 2 new production server:  Ubuntu + Mailcow dockerized

I have create manually the 19 accounts on the Server2 and create 19 sync jobs, for sync one-to-one accounts

My plan is to sync every night Server2 with Server1 until the switch in production.

Well, the sync have these parameters:
--delete2duplicates
--delete2
--automap
--skipcrossduplicates
--subscribeall
and, to speed up transfer I add two custom parameters: --usecache --useuid (that I've found on imapsync documentation)

The first sync is slow, because I have some accounts with 60gb of datas, but I expected next run will be more fast, but, everytime, the account contents is wiped out and email all resynced (I see the folder quota grow from 0 to 60gb)  ...

how (and where) can I found a solution?

thank you

**Comment by andryyy** [comment]
Hi, useuid with delete2 does pretty much what you describe. See https://imapsync.lamiral.info/FAQ.d/FAQ.Duplicates.txt

**Comment by KGemini** [comment]
Damn, you're absolutely right ... my fault. 
thank you very much
