### ISSUE TITLE
Can´t send Mails after rebooting the server

### ISSUE THREAD

**Issue by nielsq** [mailcow/mailcow-dockerized#227]
Hey,
1. I already read https://github.com/andryyy/mailcow/issues/770
2. I installed Mailcow and everthing works fine (great job andry). Now i want to restart the server (every week...) and i just can receive Mails. 
3. If I want to send a Mail i get a Timeout (Zeitüberschreitung der Anforderung).
Can someone help me pls.

**Comment by broedli** [comment]
1. o.k.
2. is everything running after your server restarted? `docker ps -a`.
3. A timeout can mean:
  A. Your local firewall is blocking you.
  B. A remote firewall is blocking you.
  C. The port is not open on your 'target'. (`netstat -tulpn`)

If you have any logs concerning this issue please provide them.

**Comment by nielsq** [comment]
sry.. i also opend one here https://github.com/andryyy/mailcow/issues/861
i´m new here ...
this is in the wrong one 
but ... with docker ps -a command not found (becouse i have the "nomal??" mailcow 


`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      5849/dovecot
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      5849/dovecot
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      5849/dovecot
tcp        0      0 127.0.0.1:10023         0.0.0.0:*               LISTEN      723/postgrey.pid --
tcp        0      0 127.0.0.1:10025         0.0.0.0:*               LISTEN      514/python
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      19675/mysqld
tcp        0      0 127.0.0.1:10026         0.0.0.0:*               LISTEN      5650/master
tcp        0      0 0.0.0.0:32330           0.0.0.0:*               LISTEN      703/ShooterGameServ
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      5650/master
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      5849/dovecot
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      5849/dovecot
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      5650/master
tcp        0      0 0.0.0.0:30033           0.0.0.0:*               LISTEN      1301/ts3server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      269/sshd
tcp        0      0 127.0.0.1:10040         0.0.0.0:*               LISTEN      382/opendkim
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      5650/master
tcp        0      0 0.0.0.0:10011           0.0.0.0:*               LISTEN      1301/ts3server
tcp6       0      0 0.0.0.0:25565           :::*                    LISTEN      1683/java
tcp6       0      0 :::4190                 :::*                    LISTEN      5849/dovecot
tcp6       0      0 :::993                  :::*                    LISTEN      5849/dovecot
tcp6       0      0 :::995                  :::*                    LISTEN      5849/dovecot
tcp6       0      0 :::587                  :::*                    LISTEN      5650/master
tcp6       0      0 :::110                  :::*                    LISTEN      5849/dovecot
tcp6       0      0 :::143                  :::*                    LISTEN      5849/dovecot
tcp6       0      0 :::80                   :::*                    LISTEN      706/apache2
tcp6       0      0 :::465                  :::*                    LISTEN      5650/master
tcp6       0      0 :::30033                :::*                    LISTEN      1301/ts3server
tcp6       0      0 :::25                   :::*                    LISTEN      5650/master
tcp6       0      0 :::10011                :::*                    LISTEN      1301/ts3server
tcp6       0      0 :::443                  :::*                    LISTEN      706/apache2
udp        0      0 0.0.0.0:9987            0.0.0.0:*                           1301/ts3server
udp        0      0 0.0.0.0:27015           0.0.0.0:*                           703/ShooterGameServ
udp        0      0 0.0.0.0:7778            0.0.0.0:*                           703/ShooterGameServ
udp6       0      0 :::9987                 :::* `

**Comment by broedli** [comment]
then please close this issue.
