### ISSUE TITLE
PHP errors are displayed

### ISSUE THREAD

**Issue by winks** [mailcow/mailcow-dockerized#2271]
**Describe the bug**
PHP errors are displayed in the browser in the default config (as of commit `0cd412d25b1b78df3cbf99cf749421520ea16455` )

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. generate a php error, (e.g. stop the redis container, but doesn't really matter)
2. access the web frontend
3. Fatal error: Uncaught RedisException

**Expected behavior**
Nothing should be shown (`display_errors=off`), error should be logged.

**System**
 - OS: doesn't matter, but Ubuntu 18.04

**Comment by andryyy** [comment]
Didn't change anything like that.

**Comment by andryyy** [comment]
Not sure what you mean. Fatal errors with exceptions have always been printed. See https://mailcow.github.io/mailcow-dockerized-docs/u_e-mailcow_ui-config/ - you could set error handler stuff here.

**Comment by winks** [comment]
Oh sorry for the ambiguous phrasing - I'm not saying something changed in that commit, just that I'm using mailcow checked out at this commit.

Also I'm not debating a regression, just that while this may always have been like this, it's not following best practices for PHP deployment.

Example (didn't check for other values that might be improved, I just  happened to notice this one): https://github.com/php/php-src/blob/master/php.ini-production#L99

Also this is not the "per-user" `error_reporting` setting regarding the link you posted, but I'm talking about a `php.ini` directive which I think should be changed.

**Comment by andryyy** [comment]
I don't really want to hide this.

You can add a `docker-compose.override.yml` and change the php-fpm command like...

```
version: '2.1'
services:
    php-fpm-mailcow:
      command: "php-fpm -d date.timezone=${TZ} -d expose_php=0 -d something"
```

...or change it in `data/conf/phpfpm/php-fpm.d/pools.conf`.

Either way, mailcow is not meant to be browsed public, I think the errors are actually helpful and don't do harm. If you don't know your users, you can hide them (edit: hide the errors, not the users :O)

**Comment by winks** [comment]
I don't see a real difference between private and public here, but anyway :)

Would you be open to some additions to https://mailcow.github.io/mailcow-dockerized-docs/u_e-mailcow_ui-config/ regarding PHP config settings along the lines of a copy-pastable override config? Then I'll check the config more closely and prepare a PR for the docs. Otherwise this can be closed.

**Comment by andryyy** [comment]
That would be awesome. I will soon start a prize draw for doc updates. 😄 Not joking. And you would totally qualify with that PR.
