### ISSUE TITLE
postfix-mailcow error

### ISSUE THREAD

**Issue by Afondevi** [mailcow/mailcow-dockerized#2273]
Hello, 
I have an error on postfix-mailcow when I run `docker-compose up -d`:

```
Creating mailcowdockerized_postfix-mailcow_1   ... error

ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (XXXXXXXXXX):
Error starting userland proxy: listen tcp 0.0.0.0:587: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Thanks to help :)

**Comment by cklabautermann** [comment]
looks as if there is another smtp running on that port. 
Verify with 
`netstat -antup | grep 587`

**Comment by Afondevi** [comment]
```
tcp        0      0 127.0.0.1:587           0.0.0.0:*               LISTEN      992/sendmail: MTA:  
```
Of course, 
Can I change the port of postfix-mailcow ?

**Comment by andryyy** [comment]
Do you want/need to keep that bind on port 587? You will not be able to use mailcow for submission, when the port is blocked.

**Comment by Afondevi** [comment]
@andryyy My other port is use in my website for chat item to send email.

Or can I change the port of sendmail ?

**Comment by Afondevi** [comment]
It's Ok I remove sendmail, my site web work again (for moment) and mail too :) thanks guys

**Comment by Lajpat29** [comment]
Mailcow OOTB uses host port 587 as submission port. 
You can change it if required in mailcow.conf SUBMISSION_PORT.
Then your mail client should use this new port in outgoing mails settings.

**Comment by EisLeisDE** [comment]
yes

**Comment by maverick85** [comment]
`yum remove -y postfix`
`docker-compose -d up`

This usually happens when postfix is installed with your OS and the service is running by default.
