### ISSUE TITLE
rspamd unencrypted password

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#2277]
Hi,

today i read the following in the logs:

`rspamd-mailcow_1     | 2019-02-08 15:42:35 #10(controller) <5bzcse>; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one`

I already tried to set the password new, but it seems to stored also unencrypted. Is that on purpose?

Greets

**Comment by Braintelligence** [comment]
As long as you're connected via HTTPS and no one suspicious has access to your server and you don't use that password anywhere else as well I can't think of a reason a hashed PW would have any advantage in this particular case.
Though, if it's not hard to implement it would be better to do it, just in case.

**Comment by andryyy** [comment]
It is stored hashed. Check the worker config in data/conf/rspamd/override.de

**Comment by Braintelligence** [comment]
@andryyy The https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/override.d/worker-controller-password.inc is empty tho

**Comment by lalaluuu** [comment]
@Braintelligence  Only here on github ..

If a password is set, it is stored hashed - already checked this here. So everything's fine - thanks ;-)
