### ISSUE TITLE
[Feature Request] Export Mailbox to PST

### ISSUE THREAD

**Issue by adambirds** [mailcow/mailcow-dockerized#2279]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to export mailboxes to PST format when they are nearing their quota, this will then allow them to open the PST up in Outlook quite easily. It can be done by Outlook, but would be great to be able to quickly do this for multiple mailboxes without having to set them all up in Outlook.
**Describe the solution you'd like**
The ability to be able to export the mailbox by PST from within the admin panel, for multiple users.

**Comment by andryyy** [comment]
I don't understand. Why would they open their exported PST in Outlook when they are nearing their quota?

I also don't support the Outlook stuff in any way. If you need to do anything Outlook related, do it in Outlook. I don't even think PST is an open format, sorry. :(
