### ISSUE TITLE
Email appearing in both blacklist and whitelist

### ISSUE THREAD

**Issue by xyphosbz** [mailcow/mailcow-dockerized#2283]
Hello, 

Recently we have started to use mailcow on a virtualized Ubuntu 18.04 server for our company. We use Vmware for virtualization. We have a domain wide blacklist/whitelist to filter out spam messages. For some months now it has working without any trouble and every few weeks I updated our blacklist/whitelist.

Recently I have began to notice that some of our whitelisted emails are being categorized as both MAILCOW_WHITE and MAILCOW_BLACK. I have went over our blacklist searching to see if maybe I accidentally added it to the blacklist but its not there. I then checked other incoming mails and there are a few other whitelisted email addresses that have both classifications. 

This is an image showing the issue
![image](https://user-images.githubusercontent.com/31674648/52506927-ad6a2380-2bb5-11e9-8886-d5ba9042d755.png)

Can anyone assist me with how I can fix this. At the moment the emails are not rejected since the values of the whitelist are greater than the blacklist. Thank you for your time and assistance.

**Comment by andryyy** [comment]
Hi, there is a rule that also matches the whitelist. You could send me your Rspamd settings map (from mailcow UI) to info@servercow.de and add the matching address. :)

**Comment by xyphosbz** [comment]
Okay I have sent over the information, thanks for the help. You might need to check your junk since we don't have rDNS yet.

**Comment by xyphosbz** [comment]
@andryyy thank you for the assistance, I will look out for the fix for the rspamd bug.

**Comment by andryyy** [comment]
Vsevolod already fixed it, just need to wait for the patch and make some slight changes to the code. :)
