### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#2284]
Hello,

currently i run the old mailcow version an want to upgrade.
But i dont understand why there is nextcloud in mailcow ?
I already run a nextcloud.... 

I use nextcloud to sync my contacts and calender, is it possible that sogo can disturb the sync ?

Btw. a version without sogo would be nice (or a version where you can disable sogo).

**Comment by andryyy** [comment]
Hi, 

There is no Nextcloud in mailcow by default. 

You can use whatever you want to sync your calendar and contacts.

A version without SOGo is not happening soon.

**Comment by UtechtDustin** [comment]
Oh okay.. i just saw the helper script..
Is the migration from the old version to the new one easy ?
Is there any Discord Server for Mailcow ? (or do you have discord?)
