### ISSUE TITLE
domain admin user

### ISSUE THREAD

**Issue by osidney** [mailcow/mailcow-dockerized#2287]
When I remove a domain that has an administrator user, the system automatically removes that user from the list, when I try to create the domain administrator user again, it informs that the object already exists, but the user does not appear in the list.

**Comment by andryyy** [comment]
Hi, this was fixed, you can remove the ghosted domain admins like this:

```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e 'delete from admin where username not in (select username from domain_admins) and superadmin != 1;'
```

**Comment by chriscroome** [comment]
If you want to check if you have any ghosted domain admins before you delete them you can run this command to list them:

```bash
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e 'select * from admin where username not in (select username from domain_admins) and superadmin != 1;'
```
I had four of them on one server&hellip; :roll_eyes:
