### ISSUE TITLE
How can I force a quota notification?

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2289]
I have reduced the quota of an email account until the account is 87% full.
But I don't get a notification.
How can I force one and how often is it checked if the quota has been exceeded?

**Comment by andryyy** [comment]
This will not work. You’d need to reduce it until it is close to the limit (79 % or something) and then receive a mail by lmtp.

It is not checked by a cronjob but triggered when a mail arrives by lmtp _and_ a limit was crossed.

**Comment by andryyy** [comment]
You can still enter the container and call the script manually. Just append “90 user@domain” as argument to quota_notify.py.

**Comment by vain90** [comment]
Thanks. Worked great!
