### ISSUE TITLE
ACME client adding and removing domains randomly

### ISSUE THREAD

**Issue by OpenLarry** [mailcow/mailcow-dockerized#2290]
**Describe the bug, try to make it reproducible**
Sometimes the acme script requests a new certificate after executing `docker-compose down && docker-compose up -d` although not necessary. Some domains are detected as new SANs or orphaned SANs randomly.

**System information and quick debugging**
ACME log shows e.g.:
```
10.2.2019, 13:09:27 | Certificate successfully deployed, removing backup, sleeping 1d
10.2.2019, 13:09:25 | Verified hashes.
10.2.2019, 13:09:25 | Deploying...
10.2.2019, 13:09:25 | Parsing account key... Parsing CSR... Found domains: mail.mailcow.de Getting directory... Directory found! Registering account... Already registered! Creating new order... Order created! Verifying mail.mailcow.de... mail.mailcow.de verified! Signing certificate... Certificate signed!
10.2.2019, 13:09:19 | Creating backups in /var/lib/acme/backups/2019-02-10_13_09_19/ ...
10.2.2019, 13:09:19 | Found orphaned SANs autodiscover.domain1.de autodiscover.domain2.de
10.2.2019, 13:09:19 | Confirmed AAAA record x:x:x:x::1
10.2.2019, 13:09:19 | Found AAAA record for mail.mailcow.de: x:x:x:x::1 - skipping A record check
10.2.2019, 13:09:18 | Confirmed AAAA record x:x:x:x::1, but HTTP validation failed
10.2.2019, 13:09:18 | Found AAAA record for autodiscover.domain2.de: x:x:x:x::1 - skipping A record check
10.2.2019, 13:09:18 | Confirmed AAAA record x:x:x:x::1, but HTTP validation failed
10.2.2019, 13:09:18 | Found AAAA record for autodiscover.domain1.de: x:x:x:x::1 - skipping A record check
```
Sometimes all HTTP validations succeed, sometimes only autodiscover.domain1.de fails, sometimes autodiscover.domain2.de fails as well. Looks like a race condition during `docker-compose up` to me. Maybe some netfilter / ipv6nat stuff is not setup properly when the acme script already starts validating domains? Or nginx is not fully ready? Did not dig further into this until now...

Maybe just waiting a few seconds at the beginning of the acme script before validating the domains would help? Had no issues before the newly introduced _verify_challenge_path_ method.

Further information:
 - Using SNAT and SNAT6
 - Ubuntu 18.04
 - QEMU (Hetzner Cloud)
 - Docker 18.09.1, Docker Compose 1.23.2
 - No important changes to the code

Aside from that Mailcow is great! I'm using it for a few months now and it works like a charm! 👍

**Comment by Geitenijs** [comment]
Same here! Now temporarily using Certbot with post-hooks.

**Comment by andryyy** [comment]
Oh no. Fixed it, sorry.
