### ISSUE TITLE
Tried to improve dns (PTR is correct, but shows wrong)

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#2292]
I clicked on the DNS Button to check my DNS entries.
In the gui got for the PTR an X, so i checked it with some online tootls e.g.
https://www.heise.de/netze/tools/dns/

This tootls shows me exact same name and value which is proposed by mailcow.
So where is the Problem, why i got an X instead of a tick ?

**Comment by andryyy** [comment]
DNS propagation? Restart unbound-mailcow.

**Comment by UtechtDustin** [comment]
No, i didnt changed the dns records/ptr since some weeks/months.
But a restart of the unbound-mailcow container fixed my issue.
