### ISSUE TITLE
How can I change my HELO to match my rDNS?

### ISSUE THREAD

**Issue by embluk** [mailcow/mailcow-dockerized#2294]
Hello,

My install of Mailcow went really well, however, I am having trouble on knowing where to set my HELO to match my PRT record for rDNS?

After using https://www.mail-tester.com I am told that sending from mail.mydomain.com is not my PTR record even though my host points to the PTR IP address?

Are you able to help me with this?

**Comment by DatAres37** [comment]
What happens if you run `nslookup 1.2.3.4 (your server IP)` from cmd or shell? It should be the same as your mail domain. If it's not you need to set a PTR record on the server you're hosting mailcow on. If you don't know how, you should contact your hoster.

**Comment by embluk** [comment]
If I perform a `nslookup` using the public server IP, I get back the correct PTR record but when sending emails, it uses what Mailcow asks for during setup, a FQDN which for example I used `mail.example.com`. But when running the test from mail tester, it says that the HELO does not match the PTR even though my domain name resolves to the PTR?

Basically my SMTP banner is not making my rDNS?

**Comment by andryyy** [comment]
The IPs PTR must match $MAILCOW_HOSTNAME. Does it? You can send me a mail from this system to info@servercow.de

**Comment by Adorfer** [comment]
so the answer to the question is: You have to setup the config-variable in file ...  MAILCOW_HOSTNAME to the respective FQDN.

**Comment by embluk** [comment]
@andryyy Thanks for the reply, unfortunally I could not send an email because I need to resolve my IP being on a blacklist; it is unlucky as I got this IP from shared hosting on a cloud service.

But I think I have something mixed up. My hosting provider has given me a PTR record and I've currently used my MAILCOW_HOSTNAME as `mail.example.com` and I should be using the PTR record instead? - If so, can I just change the  MAILCOW_HOSTNAME in the config and restart without any extra steps?

**Comment by mkuron** [comment]
> My hosting provider has given me a PTR record

You should ask them to change it to a value you specify, i.e. mail.example.com. Often that‘s even possible in the hosting company‘s web admin portal.

**Comment by embluk** [comment]
@mkuron Okay, I am actually able to change it myself, but is it not recommended to use the PTR record itself? As I wish to use multiple domains on this server?

**Comment by mkuron** [comment]
Set the PTR to your mail server‘s FQDN. Mail is basically the only thing that cares about PTRs, so the other domains don‘t matter.

 Of course you could do it the other way round and set your MAILCOW_HOSTNAME to your provider‘s default PTR, but that‘s usually not pretty.

**Comment by embluk** [comment]
Okay, that solved my problem. Thanks for the support.

**Comment by Adorfer** [comment]
Can you edit the subject please, because your actual question was "how to change the ptr record in your proviers DNS to match your ipaddress", "how to get an IPv4 that is not blacklisted".

**Comment by embluk** [comment]
@Adorfer I'm not sure I agree or understand your request? I feel the title reflects my issue and I resolved it by updating my PTR record. Other people who might have the same issue will be searching how to change their HELO and realise they should update their PTR record?
