### ISSUE TITLE
Broken mobileconfig

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2296]
Hi, me again! =)

First of all, everytime i tryed to test the mobileconfig for apple only for IMAP. They downloaded the version with CalDAV and CardDAV. I Think there is a problem with client_variables_unavailable and client_variables_available in the docs. I have no idea what the problem might be.

The main problem is, the "Fullversion" (IMAP, CalDAV & CardDAV) of the mobileconf seems to be broken.
When I try to install this "Full"mobileconfig on my iPhone or my Mac I got this error:

"**Profil konnte nicht geöffnet werden**
Beim Öffnen von „XYZ - Userinterface.mobileconfig“ ist ein Fehler aufgetreten. Weitere Informationen erhältst du von deinem Netzwerkadministrator."

When i use this url:

https://XYZ/mobileconfig.php?only_email

then I get the "onlymail" version.
This mobileconfig works as expected.

**Comment by andryyy** [comment]
Hi, when was your last update? Sounds like a problem we had in vars.inc.php. 

Do you use a vars.local.inc.php? And could you please mail me the output of mobileconfig.php (full) when called in a browser?

**Comment by vain90** [comment]
I update once a week. Last: yesterday AND today.
Mail is out

**Comment by andryyy** [comment]
For others: CalDAVPort and CardDAVPort are empty, we will check it tomorrow. :)

**Comment by vain90** [comment]
Problem solved. 
Thanks a lot to @andryyy

**Comment by mritzmann** [comment]
With which commit was this fixed?

**Comment by andryyy** [comment]
I think it was primarily this doc update: https://mailcow.github.io/mailcow-dockerized-docs/u_e-autodiscover_config/ - some stuff was missing. Also: d7aaa67e2e3ab8406b0825150506789fb401af45

**Comment by vain90** [comment]
And mainly [54dfb5c](https://github.com/mailcow/mailcow-dockerized/commit/54dfb5c4507a97eee915b102ba2b15ebe1ea30fb), too

**Comment by mritzmann** [comment]
Okay, thanks!

**Comment by vain90** [comment]
And heres the commit in the docs:
[b3cd97f](https://github.com/mailcow/mailcow-dockerized-docs/commit/b3cd97f7d4bd10eae4961b8551e4a1683e4d84d2)
