### ISSUE TITLE
Postfix SMTP Relay configuration

### ISSUE THREAD

**Issue by flexguse** [mailcow/mailcow-dockerized#23]
Hi Andre,

first of all I would like to thank you for your work putting mailcow into Docker containers!

I have some trouble configuring postfix to use a SMTP relay service.

In `data/conf/postfix/main.cf` I put the configuration

`relayhost = myrelayhost
:wqsmtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/opt/postfix/conf/sasl_passwd
smtp_sasl_security_options = noanonymous, noplaintext
smtp_sasl_tls_security_options = noanonymous`

The credentials are located in the given sasl_password file, I also used `postmap postmap /etc/postfix/sasl_passwd` and restarted everything.

Unfortunately in the logs is something like
`postfix-mailcow_1    | Jan 22 12:47:11 mailcow postfix/smtp[126]: Anonymous TLS connection established to smtp-ovhfr10.mailjet.com[5.196.43.129]:587: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bit                 s)
postfix-mailcow_1    | Jan 22 12:47:12 mailcow postfix/smtp[126]: warning: SASL authentication failure: No worthy mechs found`

I know this post is a copy of https://forum.mailcow.email/t/docker-smtp-relay-postfix-configuration/292 but I really need some guidiance here.

Thank you in advance,
Christoph

**Comment by andryyy** [comment]
Hi,
I rebuilt the Postfix container with SASL modules. Should be online @ Docker Hub within a few minutes. :)

**Comment by flexguse** [comment]
Hi andryyy,

thanks a lot, now everything work like a charm!

Cheers,
Christoph
