### ISSUE TITLE
Potential AutoDiscover issue with Outlook 2019.

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#2300]
**Describe the bug, try to make it reproducible**
I am trying to add a mailcow account to Outlook 2019 in exchange mode. It fails, so I've started investigating the issue.

First thing I see that can be a potential issue:
Outlook sends Autodiscoverv1 as discovery protocol:

Logs from nginx:
```
94.103.x.x- - [11/Feb/2019:12:36:50 +0100] "GET /autodiscover/autodiscover.json?Email=my%40emailch&Protocol=Autodiscoverv1&RedirectCount=1 HTTP/1.1" 400 182 "-" "Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.11231; Pro)"
```

If i try this url from a web browser:

```
{"ErrorCode":"InvalidProtocol","ErrorMessage":"The given protocol value \u0027Autodiscoverv1\u0027 is invalid. Supported values are \u0027ActiveSync,AutodiscoverV1\u0027"}
```

You can see it suggest AutodiscoverV1 (with capital V)

So if I try again the same url just uppercasing the v1 in the protocol, it returns:

```
{"Protocol":"AutodiscoverV1","Url":"https://mail00.whatever.com/Autodiscover/Autodiscover.xml"}
```

Not sure that's why I can't add the account to Outlook 2019, but I think the procotol string should be case insensitive...

**Comment by sriccio** [comment]
Thanks a lot for the fix for the json autodiscover from Outlook 2019. 

Unfortunately I still wasn't able to add a mailcow account to it. I'm still investigating.

I discovered that you can run autoconfiguration test from outlook by ctrl-right clicking the outlook icon on the systray.

![outlook2019_1](https://user-images.githubusercontent.com/5239282/52614239-56a06a80-2e91-11e9-8187-1410557917e4.png)

It says it can't get the settings despite it seems to attempt a lookup on the correct autodiscover host I'm doing my tests with.

![outlook2019_2](https://user-images.githubusercontent.com/5239282/52614290-8485af00-2e91-11e9-8f76-c709ea1bdc94.png)

So in order to have an idea of mailcow answer I've run the process again using Fiddler4 to capture the https calls:

![outlook2019_3](https://user-images.githubusercontent.com/5239282/52614330-a41cd780-2e91-11e9-9054-448eb7cc3226.png)

It looks to me that the answer sent to Outlook is correct. So I'm stuck here at the moment and I have no more idea.

- The autodiscover url is correct and answers with the data
- The SSL certificate for the autodiscover is valid (auto installed with mailcow's ACME)
- my Login/password is correct

What could be wrong?

**Comment by sriccio** [comment]
In order to be sure it at least still work with Outlook 2016 I did the same test with it. Same creditentials.
It add the account successfully in two clicks (only providing e-mail address and password)

![outlook2016_1](https://user-images.githubusercontent.com/5239282/52615546-dfb9a080-2e95-11e9-92d2-0fa4418e62c8.png)

I also check it via the autoconfigure test thing in outlook:

![outlook2016_2](https://user-images.githubusercontent.com/5239282/52615570-f3650700-2e95-11e9-80d7-d4bb9cc99ab4.png)

![outlook2016_3](https://user-images.githubusercontent.com/5239282/52615573-f5c76100-2e95-11e9-8eca-902df1665273.png)

![outlook2016_4](https://user-images.githubusercontent.com/5239282/52615582-fa8c1500-2e95-11e9-8a8a-a4e49a508efa.png)

Sorry for the french screenshot. I had no english version under the hand.
You can see it detects perfectly the settings, even that in the log windows there are almost the same errors we can see in O2019. 
Also the XML is returned in the XML windows. It isn't with O2019.

**Comment by andryyy** [comment]
See other issues. If it’s a Office 365 package, EAS is dropped. 

EAS on a desktop is never a good idea though. 

Last but not least I don’t have an Outlook to test. 

You will need to find out wether your version supports EAS before going ahead and debug it. 

Mit besten Grüßen
André Peters

**Comment by ChessSpider** [comment]
autodiscover does not work
manually adding does, even on office 2016, got it working through this on o365 couple of days ago

```
Steps:

    Right-Click on the Windows Start button
    Click on 'Run' (Uitvoeren in Dutch).

    Paste C:\Program Files (x86)\Microsoft Office\root\Office16\OLCFG.EXE
    Click 'yes' on the security prompt.

A new menu should open. [You may be asked/required to create a new profile.]

When you're there, click on the button
Email Accounts -> New

Choose manual setup -> Exchange ActiveSync -> enter the details -> done ! 
```

**Comment by sriccio** [comment]
Hello @ChessSpider and @andryyy,

I was successfully able to attach my test account on Outlook 2019 using the OLCFG.EXE method. 

Thank you for pointing this, I had completely forgot about it.

So yes using this method EAS still works, at least with my .iso version of Office 2019.

Cheers,
Sébastien

**Comment by MarcelFranken** [comment]
To enable the "old wizard" login, you can also follow the guide on https://support.microsoft.com/en-us/help/3189194/how-to-disable-simplified-account-creation-in-outlook

**Comment by mkuron** [comment]
Excellent find, @MarcelFranken. Could you please add this to the documentation at https://github.com/mailcow/mailcow-dockerized-docs/blob/master/docs/client/client-outlook.md?

**Comment by MarcelFranken** [comment]
Unfortunately i am not that good in writing documentation, sorry. :(
Can someone else do this part?

**Comment by mkuron** [comment]
https://github.com/mailcow/mailcow-dockerized-docs/commit/e3dd114a54bb607cd30bf03c5e05aab9db4cd6b3

**Comment by xdarkfirestorm** [comment]
This problem still exists. I was able to workaround with the link @MarcelFranken commented above.

Why can't this just be fixed so it's also working for Outlook 2019 and Office 365?

**Comment by andryyy** [comment]
Are you already working on it?

**Comment by xdarkfirestorm** [comment]
@andryyy 
I'm not

**Comment by pschiffe** [comment]
> EAS on a desktop is never a good idea though.

Hi @andryyy , could you elaborate? Is IMAP more efficient, or why? I like EAS b/c of simple configuration of mail, contacts and calendar.

**Comment by mkuron** [comment]
> Is IMAP more efficient, or why?

IMAP and CardDAV/CalDAV are the native protocols of Mailcow. EAS is provided by a translation layer inside SOGo, and it's a lossy translation (EAS only allows you to have certain attributes on contacts, the draft mail folder behaves weird, etc.). Also, it's rather inefficient because it keeps server-side sync state.
