### ISSUE TITLE
Urgent: No SMTP-Relaying sincs last update

### ISSUE THREAD

**Issue by Arkaniod** [mailcow/mailcow-dockerized#2301]
I have two customers which relay their outgoing Mails on my mailcow. One customer with Exchange 2010 (SBS 2011), the other with Exchange 2016 (Server 2016).

Since the last update (installed yesterday evening) both customers were not able to send (relay) outgoing Mails.

Postfix-Log (appears sometimes):
`warning: restriction `reject_authenticated_sender_login_mismatch' ignored: no SASL support`

Postfix-Log (appears after every connection from customer):
`11.2.2019, 12:33:02 | info | disconnect from host-xx-xxx-xxx-103.customer.m-online.net[xx.xxx.xxx.103] ehlo=2 starttls=1 quit=1 commands=4
-- | -- | --
11.2.2019, 12:33:02 | info | Anonymous  TLS connection established from  host-xx-xxx-xxx-103.customer.m-online.net[xx.xxx.xxx.103]: TLSv1 with  cipher ECDHE-RSA-AES256-SHA (256/256 bits)
11.2.2019, 12:33:02 | info | connect from host-xx-xxx-xxx-103.customer.m-online.net[xx.xxx.xxx.103]
11.2.2019, 12:33:02 | info | WHITELISTED [xx.xxx.xxx.103]:52890
11.2.2019, 12:33:02 | info | Look up xx.xxx.xxx.103 on whitelist, result 200 PERMIT
11.2.2019, 12:33:02 | info | CONNECT from [xx.xxx.xxx.103]:52890 to [172.22.1.6]:25`

The Exchange Send connector stats:
`451 4.4.0 Primary Target IP address responded with:" 451 5.7.3 Require basic authentication"`

Configuration of the Exchange Send connector is unchanged and worked without any problems until that last update.

Found out, that it has to do with [[Postfix] Disable auth on port 25 ](https://github.com/mailcow/mailcow-dockerized/commit/c57a544c52d1ae77b50567042efdaa5e1592b74b).

After uncommenting this and restarting Postfix, both clients were able to send outgoing Mails again.

This is just to inform others that are having the same problem.

Kind regards
Chris

**Comment by andryyy** [comment]
This should always be done over port 587/tcp. 

There were too many people trying submission over port 25 (which sometimes works, depending on RBL results and other Postscreen checks). So it is discouraged to use port 25 for authenticated submissions. :)

**Comment by Arkaniod** [comment]
Thanks, André... Yes, it's obvious that this is safer - but came a little bit surprisingly. Was a little bit in panic and had to find a solution for my Customers  (even "quick and dirty") to ensure mailtraffic.

Meanwhile all Exchange Send connectors are re-configured to use port 587 and everything runs well again.

**Comment by andryyy** [comment]
No problem. Check https://mailcow.email/ before updating. :)
