### ISSUE TITLE
ClamAV too aggressive

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2303]
Hello, I upgraded mailccow installation after one year and found, that clamAV is too aggressive and marks messages as virus  in case when it is legit message. Is there some setting to tune? Thanks

**Comment by feldsam** [comment]
another problems is forwarding message marked by clamav. It gets score 2000 and forwared by authentificated user withing sam edomain, it gets rejected, because auth user gets on score 20, so in final, message get score ~1980. I was meaning, that if send within domain, it is not rejected in any case, because  mailboxes on same domain are cross white listed, or no?

**Comment by feldsam** [comment]
I found this in clamd contaner log

```

Sun Feb 10 16:11:34 2019 -> Reading databases from /var/lib/clamav


LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/sigwhitelist.ign2


LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/sigwhitelist.ign2


Sun Feb 10 16:11:34 2019 -> !reload db failed: Can't open file or directory


Sun Feb 10 16:11:34 2019 -> Terminating because of a fatal error.


/bootstrap.sh: line 69: kill: (19) - No such process
```

**Comment by feldsam** [comment]
ah, after few restarts it is running without these errors, I think that problem is wit sanesecurity db. We have it used on old mail system and few months ago it returns many false positives.

**Comment by feldsam** [comment]
PUA.Win.Trojan.EmbeddedPDF-1(629d82ae156e6827460d3385f117a48c:443904)

http://lists.clamav.net/pipermail/clamav-users/2016-June/003062.html

**Comment by andryyy** [comment]
Whitelist it.

`data/conf/clamav/whitelist.ign2` => `PUA.Win.Trojan.EmbeddedPDF-1`

You can send a RELOAD to clam on port 3310 or restart the container.

It is intended that everything ClamAV detects is also blocked in internal communication. You can create a Rspamd settings map to disable that.

**Comment by feldsam** [comment]
thanks, I added and will see

**Comment by andryyy** [comment]
Some new rules are very useful, some are prone to fp.

**Comment by extremeshok** [comment]
Having the same issue with the sig causing massive volume of false flags. 

Maybe it should be added to the whitelist by default ?

**Comment by andryyy** [comment]
Can you create a PR? :) Would be nice.

**Comment by maltris** [comment]
Any way to disable the outgoing checks for a specific sender- and/or recipient-domain?
