### ISSUE TITLE
rspamd subject privacy

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2304]
Hi,

I want to hide the subject in the rspamd logs.
After a little googling I found a PR in the rspamd repo.
[#2093](https://github.com/rspamd/rspamd/pull/2093)

This feature can enabled by settings.
I edited the /data/conf/rspamd/local.d/history_redis.conf and added 

subject_privacy = true;

Now it works fine but isn't persistent during updates.
Is it possible to add a history_redis_local.conf or something like that?

**Comment by andryyy** [comment]
It should be "more persistent" now. We just added that file once and will probably not change it any time soon. You can try to set a +i attr on files you want to be sure are not overwritten. It will complain on updates, but you will know what to check for.

**Comment by vain90** [comment]
What if I use ./update.sh --ours ?

**Comment by andryyy** [comment]
That _can_ be dangerous. Some conflicts are better solved by theirs to prevent broken code. I recommend to set the +i flag. :)
