### ISSUE TITLE
Confirmed A record xx.xx.xx.xxx, but HTTP validation failed

### ISSUE THREAD

**Issue by rootifera** [mailcow/mailcow-dockerized#2305]
Hello, 

I'm having an SSL issue after I updated mailcow (with update.sh).

When I check my emails (with thunderbird) I'm getting wrong certificate error. I checked acme logs and I'm seeing the following. 

11/02/2019, 21:58:33 | Confirmed A record xx.xx.xx.xxx, but HTTP validation failed
11/02/2019, 21:58:33 | Found A record for mail.maildomain.net: xx.xx.xx.xxx

I checked the data/assets/ssl folder and when I decode cert.pem what I see is the certificate is generated for autodiscover.maildomain.co.uk instead of mail.maildomain.net, therefore mailclient complains. 

I have tried restarting, removing the cert and getting it re-generated. I'm getting the same result every time. 

I might have done something wrong, I checked the documentation but couldn't find anything.

At the moment I manually replaced the certificate from backup. 

OS: Debian 9 on AWS
Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01
git diff origin/master = nothing
Reverse proxy = I'm using reverse proxy but it was working until last update.

Please let me know if you require further information.

**Comment by andryyy** [comment]
It was an issue with his reverse proxy. :)

In case you want to check it:
```
cd /opt/mailcow-dockerized
source mailcow.conf
touch data/web/.well-known/acme-challenge/1
# For IPv4, should return 2xx or 3xx
docker-compose exec acme-mailcow curl -4 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
# For IPv6, should return 2xx or 3xx
docker-compose exec acme-mailcow curl -6 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
```

**Comment by rootifera** [comment]
Hello,

Thanks to golden_receiver on IRC, we resolved the issue. The problem was apache2 deciding not to redirect any more. After fixing the vhost config all worked fine.

**Comment by swaggi** [comment]
Hi,
I just started using mailcow and I'm really impressed. But sadly I have the same problem. I am also using a reverse proxy (nginx by jwilder, which recognizes new web containers by itself) and the acme container of mailcow is throwing the same error message. Other webservices like Nextcloud or simple webservers are running well with this reverse proxy.

Can you tell me how to handle it?

**Comment by andryyy** [comment]
Hi, please run the commands above and show their output.

If you place a reverse proxy in front of mailcow, you need to configure it by yourself. Jwilders proxy will not work without any configuration. The verification prevents broken setups to request names over and over again until they hit a rate limit.

**Comment by swaggi** [comment]
Hey, this is the output of the commands above:
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.13.10</center>
</body>
</html>
```


Do you have an idea in which way I have to configure jwilders proxy? http traffic is no problem, only this certificate issue :( Thanks for taking time so far!

**Comment by andryyy** [comment]
You always need to configure a reverse proxy. :o 

You cannot just place it in front of anything without configuration. That can actually be dangerous.

As you see your Nginx (I guess it's jwilders) doesn't proxy to mailcow. We do not expose the Nginx version. so it is an external Nginx.

**Comment by swaggi** [comment]
Yes I have to configure the proxy by adding environment variables to the container I want to reach from the outside. I did not know that I have to configure jwilders proxy any further :D Thanks for the advice! But in some kind jwilders does proxy to your nginx, otherwise I would not be able to reach mailcow via http :(

**Comment by riedoi** [comment]
I had the same issue with a running nginx proxy in docker in my homelab. I could solve it with a extra_hosts entry: 

    acme-mailcow:
      depends_on:
        - nginx-mailcow
      image: mailcow/acme:1.70
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      extra_hosts:
        - "${MAILCOW_HOSTNAME}:192.x.x.x" #my internal server IP
