### ISSUE TITLE
Ability to disable/enable SOGo's Active Sync for some users and or domains

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#2307]
**Is your feature request related to a problem? Please describe.**
Actually with mailcow I think there is no easy way to enable/disable ActiveSync for some users or some domains. In a beautiful world, we would like to be able to do so because we don't want to provide this feature to every user/domain.

**Describe the solution you'd like**
The ideal solution would be to have in the admin a checkbox when you add/edit a domain or a mailbox to enable or disable ActiveSync for this particular user/domain.

**Additional context**
But this is the ultimate goal. Actually I'm trying to do it "manually", so I did some research and found this:

In SOGoUserSources configuration (dynamically populated at sogo container start with bootstrap-sogo.sh) one can add this key:
```
ModulesConstraints (optional)
Limits the access of any module through a constraint based on an LDAP attribute; must be a dictionary with keys Mail, and/or Calendar, and/or ActiveSync for example:

---- ModulesConstraints = { Calendar = { ou = employees; }; }; ---
```

So okay but we are using SQL source so we're stuck. But wait, no!:

```
SOGo v4.0.0
[core] add support for module constraints in SQL sources
```

Yeha we're good to go. But I have no idea about the syntax. I would guess something like this for a test drive:

```
<key>ModulesConstraints</key>
<string>{ActiveSync = { uid = mysuper@account.com }}</string>
```

So I added it but it seems I can't get it to work. I have no idea about the syntax or what objects we can us as filter. I tried with uid because there was some examples for LDAP stuff but...

Maybe there is some SOGo wizard around that could help me achieving what we're trying to do ?

The best would be to have some tag or group of users that we can limit activesync for (or allow activesync for). Then if we want to have this configurable from the mailcow admin it would be a matter of adding the user/domain to this group and voila (am I too confident that it could work?).

Thanks a lot for your ideas/hints.

Cheers

**Comment by sriccio** [comment]
Out of topic: @andryyy I've sent you an e-mail yesterday. Did you receive it ? Just to be sure it went through :)

**Comment by andryyy** [comment]
Yes, thanks. I will come back to you today. 

I don’t plan to add that feature soon though. Either it is sponsored or added by a PR. 

Could also be better to manage it through Nginx to not restart SOGo.

**Comment by evilstiefel** [comment]
I fiddled around with it a bit, and it works if you add the line manually like this inside sogo-bootstrap.sh:

*snip*
````
<key>ModulesConstraints</key>
<dict>
  <key>ActiveSync</key>
  <dict>
    <key>mail</key>
    <string>user@domain.tld</string>
  </dict>
</dict>
````
*snip*

Obviously, replace user@domain.tld with something appropriate.

**Comment by evilstiefel** [comment]
Above is just a hack, since it will add this dictionary entry to every domain you add to mailcow through the UI.

Don't know how useful people would find this feature for adding support in the UI and properly handling it there.

**Comment by sriccio** [comment]
Hi @evilstiefel,

Thank you for your reply and example. I will try it out. Ideally it would be nice if we use some groupname or attribute instead of the mail address..
Maybe I can figure something out for this with your example.

About the usefullness, it's more about server resources. If I recall correctly using ActiveSync eats way more resources than the basic IMAP/SMTP/*Dav combo, maybe I am wrong.

So we would like for example only "premium" users to have this enabled.

**Comment by andryyy** [comment]
If you sell mailcow, consider sponsoring a feature. ;)

**Comment by sriccio** [comment]
@andryyy We are actually evaluating if mailcow could fit our needs to replace the current mail solution part of our website hosting packages. I sent your an e-mail about it :)
We're totally not against sponsoring some features development should we use it commercially in the future.

**Comment by sriccio** [comment]
@evilstiefel I was able to have the ActiveSync restriction working with your example. Thanks again. Now I'm going to find a way to have an attribute or flag that I can attach to user and constraint against.

There is also another point why people would want to disable activesync for some of their user. As far as I know you need to buy licenses to microsoft if they are using it... So you might not want all your users to have access to it...

**Comment by andryyy** [comment]
Share your changes, please. That’s all GPL actually asks for. :)

**Comment by sriccio** [comment]
I of course propose changes via PR when I think they are properly implemented and not just a workaround and can be of benefit for everybody. I already did :)
For example: https://github.com/mailcow/mailcow-dockerized/pull/1721

**Comment by affenrakete** [comment]
> I fiddled around with it a bit, and it works if you add the line manually like this inside sogo-bootstrap.sh:
> 
> 
> 
> *snip*
> 
> ````
> 
> <key>ModulesConstraints</key>
> 
> <dict>
> 
>   <key>ActiveSync</key>
> 
>   <dict>
> 
>     <key>mail</key>
> 
>     <string>user@domain.tld</string>
> 
>   </dict>
> 
> </dict>
> 
> ````
> 
> *snip*
> 
> 
> 
> Obviously, replace user@domain.tld with something appropriate.

Where do you put this little piece of code? My fiddling didn't quite work out.
