### ISSUE TITLE
suggestion: pigz and rsyncable for backups

### ISSUE THREAD

**Issue by ChojinDSL** [mailcow/mailcow-dockerized#2308]
The backup helper script creates tar.gz archives. One little optimization that might help is to use pigz instead of gzip. Pigz ist just a parallel implementation of gzip. This way the compression is done using multiple threads, rather than just one.

Secondly, you might want to consider to add the parameter --rsyncable to gzip or pigz. In my case, use borg as a backup tool to create backups of my systems. I also backup the mailcow backups this way. Borg deduplicates on a block level, even within a single backup session, so its very space efficient.
Unfortunately gzip and most other compression tools don't create deduplicatable archives per default. e.g. If you had one tar.gz archive that was 1GB in size and then immediately afterwards you made changes of 2kb and created another tar.gz archive which would result in 1.002GB size, the resulting backup of those two tar.gz archives would result in 2GB of data, even though there is only 2kb of actual difference between them.
By using --rsyncable the archives are written in such a manner that tools like borg would only backup 1.002GB of total data, rather than the redudant bits as well.
The --rsyncable parameter results in a slightly larger single backup archive, but is helpful for incremental backups.

I simply adapted the bash script like this (basically, anywhere where gzip was called):
/bin/tar --warning='no-file-ignored' --use-compress-program="gzip --rsyncable -v --best" -Pcvpf /backup/backup_vmail.tar.gz /vmail

Just a suggestion.

**Comment by extremeshok** [comment]
I disagree with the usage of pigz, besides the base-image not having support for it, it can cause your server to lag/stop responding during backup operations.

**Comment by andryyy** [comment]
Hm, that's true, pigz can be very heavy on your CPUs.

**Comment by Adorfer** [comment]
backup is not a high priority task. i even like to throttle it down. So "single thread" is perfect for a decent system. (at least for me)
If it goes multi-thead, please make it configurable.

**Comment by evilstiefel** [comment]
Even if pigz does not make it into the master branch, what about the other proposa with adding "--rsyncable"? I very much like the idea of having incremental backups instead of shuffling gigabytes of data to another server when using daily backups.
