### ISSUE TITLE
U2F with Firefox

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#231]
Hi there 😸.
I'm running mailcow-dockerized now in its own VM (until rancher is officially supported).

I try to setup U2F via Yubikey 4 in Mailcow but it isn't recognized even though I'm using the U2F support addon. I tried several U2F demos and all of them worked with my Yubikey but mailcow doesn't work :(.

Any ideas? 😺

**Comment by andryyy** [comment]
Do you use https? It is important.
What exactly does not work? What are the error messages etc.?

**Comment by Braintelligence** [comment]
Yup, I'm using HTTPS via Letsencrypt as described in the docs
I didn't check the dev console for errors yet but none were displayed.
It only said waiting for USB device.

**Comment by Braintelligence** [comment]
Some people said that some sites don't work with the addon as long as you don't switch to a chrome user agent.

Did you manage to get it working with Firefox, though? Or is it something on my end?

I'm using the current stable Firefox on Win 10 x64.

**Comment by andryyy** [comment]
Sorry, I broke it. Pushing a fix now!

**Comment by Braintelligence** [comment]
Alright!
I can test the upgrade path then :D. Thanks :).

**Comment by Braintelligence** [comment]
Hey, I'm trying to set it up now but it says:
U2F: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'key_id' in 'field list'

**Comment by andryyy** [comment]
Yes, sorry, please pull again. I used an older init.sql file when I changed to a new init db process. :( The field should be created now.

**Comment by Braintelligence** [comment]
No problem! :D Trying it out now.

**Comment by Braintelligence** [comment]
Works! Thanks a lot!
