### ISSUE TITLE
Explain quarantine learn as spam

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2310]
Hello, for what is "Learn as spam and delete" in quarantine? I suppose, that mesages goes to quarantine, because of high spam score, so system already knows that ara spammy, so why do marking as spam? I think, that mor eusefull will be opposit way, marking as ham.

**Comment by andryyy** [comment]
To mark it as ham, you will need to whitelist the sender. 

Problem about adding a link to whitelist the sender: What do you want to whitelist? Mime from? Envelope from? If you whitelist the envelope, you might end up whitelisting a random bounce envelope address. Mime can be dangerous, it can be spoofed much easier.

When a mail is rejected, its fuzzy hash is not learned. Other users may not want to block this mail content. A fuzzy hash is global. So you can optionally learn the msg as spam. Most of the times, this is not needed... It can be useful for some kind of spam though (to collect text patterns of specific spam like insurance spam).

Please ask this kind of stuff on IRC or via support ticket. :)
