### ISSUE TITLE
Catchall for all domains

### ISSUE THREAD

**Issue by igorakkerman** [mailcow/mailcow-dockerized#2312]
Hi,
Is it possible to set up a catchall for all registered domains instead of adding them one by one (`@domain1.com`, `@domain2.org`, ...) ?

**Comment by andryyy** [comment]
Hi and sadly not, no. :(

**Comment by igorakkerman** [comment]
Can I turn this into a feature request? ;)

**Comment by andryyy** [comment]
I don’t know if anyone will implement it. Seems easier to just create those catch all addresses per domain. :o

**Comment by igorakkerman** [comment]
It depends on the number of domains. Let's say it took me a while ;)

**Comment by joshghent** [comment]
Yeah this would be an amazing feature, what would it take to build it? I'd certainly have a crack at it
