### ISSUE TITLE
UI not responding

### ISSUE THREAD

**Issue by dereddy93** [mailcow/mailcow-dockerized#2314]
Hello,

I did a clean install on an Ubuntu 18.04 running on ESXi 6.7 with 4GB of RAM and 1 CPU.
Furthermore I installed docker version 18.09.2, build 6247962 and docker-compose version 1.23.2, build 1110ad01.

Setup process went just fine and I can log in to the Admin-UI just fine. Nevertheless nearly any button on the UI seems to be out of order.
E.g. I want to change the default administrator password. I can click on the "edit" button of the administrator account and I am getting forwarded to the change site. I enter the new password, hit submit and ... nothing happens. The button freezes in its "Please wait ..." state.
This also happens during creation of a new administrator account and generating DKIM keys. No domain can be added and so on.
Docker logs also tells me that there is no event happening if I click on the buttons.

This is highly frustrating since your product seems to be very intuitiv and easy to set up.

Do you have anything in mind other than "try rebooting system/docker etc"?

Thanks for your help. Keep up the good work!

**Comment by andryyy** [comment]
Check your browser. Dev console, js blocking extensions etc.

**Comment by dereddy93** [comment]
Hello @andryyy ,
thanks for your quick reply. Thanks for the tip with the dev console.
I did some further researching and as it turns out, the webserver is throwing a HTTP 403 return code.
Maybe to clear the fog for you:
I am running the mailserver behind a firewall which also does reverse proxying for me. If I try to change the password / create a new user connecting directly to the server (from within the subnet) everything works just fine.
I am happy to provide you any log files if this might help you with your investigations.

Looking forwards hearing from you.

**Comment by dereddy93** [comment]
Hello @andryyy ,
 I am so sorry, but this was due to a policy on my firewall restricting me from posting any data.
It is quite emberassing for me not thinking about this in the first place.
Again, so sorry for taking up your time unneccesary.
Keep up the good work and am happy to keep using your solution.

Kind regards,
@dereddy93

**Comment by andryyy** [comment]
Good to know. :) Thanks for your feedback.
