### ISSUE TITLE
How to define Server Default Spam Values?

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#2317]
Hello,

How can I set the defaults for:
![image](https://user-images.githubusercontent.com/1459530/52669157-4e861080-2f0d-11e9-9fd5-a5ea1cd708c1.png)

I see a Reset to Server Default, but I do not know where to set the 'default'
I'd like to change the default spam levels on all new accounts (and/or existing).

thank you very much.

**Comment by andryyy** [comment]
Hi,

youuuuu, can either change them in Rspamd UI or in `data/conf/rspamd/local.d/metrics.conf`.

**Comment by apintocr** [comment]
Oh... Dumb me. Sorry.

And is there any way to reset all accounts?

**Comment by andryyy** [comment]
You would need to delete the values from sql.

**Comment by andryyy** [comment]
```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "delete from filterconf where option='highspamlevel' or option='lowspamlevel';"
```

**Comment by apintocr** [comment]
Woooa @andryyy 
Thanks very much!
