### ISSUE TITLE
Auto Reply on Alias?

### ISSUE THREAD

**Issue by ssm3e30** [mailcow/mailcow-dockerized#2319]
**Is your feature request related to a problem? Please describe.**

The problem I am having is we are utilizing emails for a temporary period of time while we get new customers setup on our product, like a temp-help@xyz.com. So I create a new mailbox then will remove it after its purpose is done, however how can I alert people who email that now removed mailbox to contact us by another method?

**Describe the solution you'd like**

I see it working with an auto reply message to an alias. Essentially after removing that mailbox, I can create an alias that will discard the message, but auto reply a message saying "This accountno longer exists, contact HERE" or similar. That way it keeps the mailbox section clean instead of keeping the mailbox and setting an auto reply in SOGo.

Let me know if this is possible in some way. 

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

**Comment by Braintelligence** [comment]
To me, the job and definition of a mail alias is to act as an alternative address to a mailbox. Adding any more features to it would dilute its purpose and make it something between an alias and a mailbox.

That being said, I would welcome quality of life improvements like converting aliases to real mailboxes and getting some simple ways of implementing forwarding in the Mailcow UI without having to log in into SOGo.

I doesn't make sense to allow filtering for aliases to me, though. I don't even think this is an issue of something you only need to allow but isn't even technically implemented. You'd need a proper mailbox for those functions afaik.

**Comment by ssm3e30** [comment]
@Braintelligence Totally fair points. 

I've been playing with filters and Alias/Address rewriting. What I've learned is that the filters are only applied to messaged directly sent to that receipt, and I think thats what you were getting at the at bottom there with not being implemented. 

Message --> Intended Mailbox Address --> Filter (This works)

Message --> Intended Mailbox Address --> Forwarded Mailbox Address --> Filter (This does not work)

**Comment by Braintelligence** [comment]
Actually it seems I have confused the title with what you wrote.
You really had mailboxes and then deleted them. Instead of deleting them you can set the quota to a very low value, set the box to not accept mails anymore and auto-answer with a mail explaining the situation.

If you delete the mailbox, anyone writing it would receive an error report from your mailer daemon anyways.
