### ISSUE TITLE
MySQL-Error when creating sync job

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#232]
I did not know about the import/sync feature until you mentioned it in #228. Really cool. I just tried it because I am preparing moving from mailcow 0.14 to mailcow-dockerized and want to sync mailboxes - but I get an error message

```MySQL: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'delete1' in 'field list' in /web/inc/functions.inc.php:1089 Stack trace: #0 /web/inc/functions.inc.php(1089): PDO->prepare('INSERT INTO `im...') #1 /web/inc/triggers.inc.php(105): add_syncjob(Array) #2 /web/inc/prerequisites.inc.php(120): require_once('/web/inc/trigge...') #3 /web/user.php(2): require_once('/web/inc/prereq...') #4 {main}```

I just updated, hopefully in a proper way? i am always keeping the master branch untouched and have `myBranch` with all my customizations which i push to my private and self-hosted gogs git service - i update master and then rebase myBranch on top of master

`git fetch upstream master`
`git merge master`
`git checkout myBranch`
`git rebase master`
`docker-compose pull`
`docker-compose up -d`

could that have caused problems?

**Comment by andryyy** [comment]
Thanks, it is fixed. Sorry. A merge before broke the db layout of that table.
