### ISSUE TITLE
Forward special subjected emails?

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#2320]
Hello,

Is it somehow possible to forward an email to another adress if the subject contains something defined?

Thanks in advance.

**Comment by ssm3e30** [comment]
Read up on Sieve filters, and write a rule to forward based on the content.

https://p5r.uk/blog/2011/sieve-tutorial.html

**Comment by omexlu** [comment]
Hello,

Thank you, is there any part in the GUI to write into the rule (i can't look at this moment)?

**Comment by ssm3e30** [comment]
Configuration -> Mail Setup -> Filters

**Comment by omexlu** [comment]
Thanks, because that is exactly what i need:

> require ["copy"];
> if header :contains "Subject" "tiger"
> {
>     redirect :copy "other@example.net";
> }
> 

Maybe this filter is correct? :)

**Comment by evilstiefel** [comment]
You can also use SOGo to use a nice GUI to create these rules. No need to write the syntax yourself (those are per account though).

**Comment by omexlu** [comment]
> You can also use SOGo to use a nice GUI to create these rules. No need to write the syntax yourself (those are per account though).

In SOG i only see the option to redirect/move it to another INBOX/SUBFOLDER, but how to redirect to a different email-adress?

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/52710800-8aae8500-2f90-11e9-9098-0018adba5d3f.png)

**Comment by omexlu** [comment]
Haha, i tried the online demo from SOGO maybe that was deactivated there or old version, will test it @ home :)

EDIT: Forward also keep the email in the INBOX op receipt?

Thanks.

**Comment by andryyy** [comment]
No problem. :)

You need to add a second rule to “keep the message” just after the forwarding rule.
