### ISSUE TITLE
Rspamd history setting of 10000 lines

### ISSUE THREAD

**Issue by PaoloVi** [mailcow/mailcow-dockerized#2322]
After Foobruary updates rspamd history was changed from 200 lines to 10000 lines.
Maybe too much. My rspamd ui stop working after 120 pages (120x25=3000 lines). Not a very powerful Vm (1Cpu, 2GB ram), but enough for my work.
I think a more conservative default setting of 2000 lines (80 pages in rspamd ui, more or less 3 history days) can be enough and lower consumption of resources.

**Comment by andryyy** [comment]
Anyone else run into this problem? :O

**Comment by marrco** [comment]
On first access this morning i got a "Module loading error: timeout, module: jquery,d3pie,visibility,nprogress,app/stats,app/graph,app/config,app/symbols,app/history,app/upload,d3"  when trying to access /rspamd. Reloading the page cleared the error and offered the usual login form. Can't tell if that's related but getting to the history page it's slower here too.

**Comment by extremeshok** [comment]
Please post your specs..
My guess would be the users with the issues are running cheap low resource vm's
A swap file and/or zram would probably mitigate some of the issues.

**Comment by extremeshok** [comment]
16 000 results, no slowdown. current memory usage is  5.8GB with 40GB cached

![rspam_history_16000](https://user-images.githubusercontent.com/5957328/52770181-1aa90900-303b-11e9-810a-64433866d9ea.png)

**Comment by marrco** [comment]
Plenty of resources, load avg 0.0x and a few GB free ram here. Mailcow uses less than 2 GB, mostly for clamd.

```
 ...
 15.4 MiB + 100.5 KiB =  15.5 MiB       docker-containerd
 14.9 MiB +   1.0 MiB =  15.9 MiB       docker-proxy (12)
 17.2 MiB +   3.2 MiB =  20.4 MiB       docker-containerd-shim (17)
 25.3 MiB +  44.0 KiB =  25.4 MiB       redis-server
 24.3 MiB +   1.3 MiB =  25.5 MiB       supervisord (3)
 26.2 MiB + 443.0 KiB =  26.7 MiB       unbound
 37.6 MiB + 964.0 KiB =  38.6 MiB       python2.7 (2)
 45.7 MiB + 186.5 KiB =  45.9 MiB       dockerd
 40.1 MiB +  16.3 MiB =  56.4 MiB       php-fpm (11)
165.4 MiB + 141.0 KiB = 165.6 MiB       mysqld
158.4 MiB +  45.4 MiB = 203.9 MiB       rspamd (7)
199.6 MiB +  22.4 MiB = 222.1 MiB       sogod (21)
706.6 MiB + 369.0 KiB = 706.9 MiB       clamd
```

but still, when connecting to rspamd web interface and clicking to history tab there's a multi-second delay. I second changing to a smaller default value.

(about my issue this morning: that could be related to cold starting Google Chrome with a dozen background tabs, but it's the first time I receive that error. I know, yesterday was patch Tuesday so maybe there were some background jobs running on my computer, but -apart from that error- clicking to 'history' in rspamd web interface is much slower than it was last week)

**Comment by andryyy** [comment]
Hm, let's set it to 1000 for master... people can still change it. Anyone wants to update the docs? :-D
