### ISSUE TITLE
Cannot validate hostnames, skipping Let's Encrypt for 1 hour.

### ISSUE THREAD

**Issue by dtoenies** [mailcow/mailcow-dockerized#2323]
Hello,
yesterday I installed nextcloud via the helper script and added the SAN to mailcow.conf - everything worked fine.
Today my certificate isn't valid anymore and I am not able to regain a new certificate. The following is in the ACME log
`

13.2.2019, 13:52:24 | Certificate successfully deployed, removing backup, sleeping 1d
-- | --
13.2.2019, 13:52:22 | Verified hashes.
13.2.2019, 13:52:22 | Deploying...
13.2.2019, 13:52:22 | Parsing account key... Parsing CSR... Found domains: mail.domain.de Getting directory... Directory found! Registering account... Already registered! Creating new order... Order created! Verifying mail.domain.de... mail.domain.de verified! Signing certificate... Certificate signed!
13.2.2019, 13:52:15 | Creating backups in /var/lib/acme/backups/2019-02-13_13_52_15/ ...
13.2.2019, 13:52:15 | Found orphaned SANs autodiscover.domain.de nextcloud.domain.de domain.de www.domain.de
13.2.2019, 13:52:15 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 13:52:15 | Found A record for nextcloud.domain.de: 85.XXX.XXX.XXX
13.2.2019, 13:52:15 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 13:52:15 | Found A record for www.domain.de: 85.XXX.XXX.XXX
13.2.2019, 13:52:13 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 13:52:13 | Found A record for domain.de: 85.XXX.XXX.XXX
13.2.2019, 13:52:13 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 13:52:13 | Found A record for mail.domain.de: 85.XXX.XXX.XXX
13.2.2019, 13:52:13 | Confirmed AAAA record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 13:52:13 | Found A record for autodiscover.domain.de: 85.XXX.XXX.XXX
13.2.2019, 13:52:08 | OK
13.2.2019, 13:51:16 | Detecting IP addresses...

`

This is what I get if I try  to renew the certificate
`

13.2.2019, 18:23:13 | Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
-- | --
13.2.2019, 18:23:13 | Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
13.2.2019, 18:23:13 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 18:23:13 | Found A record for nextcloud.domain.de: 85.214.192.146
13.2.2019, 18:23:13 | Confirmed A record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 18:23:13 | Found A record for mail.domain.de: 85.214.192.146
13.2.2019, 18:23:13 | Confirmed AAAA record 85.XXX.XXX.XXX, but HTTP validation failed
13.2.2019, 18:23:13 | Found A record for autodiscover.domain.de: 85.XXX.XXX.XXX
13.2.2019, 18:23:13 | OK
13.2.2019, 18:22:28 | Detecting IP addresses...
13.2.2019, 18:22:28 | Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
13.2.2019, 18:22:28 | Using existing domain key /var/lib/acme/acme/key.pem
13.2.2019, 18:22:28 | Initializing, please wait...
13.2.2019, 18:22:28 | OK
13.2.2019, 18:22:28 | Waiting for domain table...
13.2.2019, 18:22:28 | OK
13.2.2019, 18:22:28 | Waiting for Nginx...
13.2.2019, 18:22:28 | OK
13.2.2019, 18:22:28 | Waiting for database...
13.2.2019, 18:22:28 | OK
13.2.2019, 18:22:28 | Waiting for Docker API...

`

I also tried it with disabled ufw but had no luck.

Any help is welcome cause I like my nextcloud :)
Chhers

**Comment by andryyy** [comment]
1. ufw is not supported. You need to remove it and restart Docker. 

2. Check other issues first, please:

```
cd /opt/mailcow-dockerized
source mailcow.conf
touch data/web/.well-known/acme-challenge/1
# For IPv4, should return 2xx or 3xx
docker-compose exec acme-mailcow curl -4 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
# For IPv6, should return 2xx or 3xx
docker-compose exec acme-mailcow curl -6 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
```

Could you please post the output of these command?

**Comment by dtoenies** [comment]
This is the output:

``<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>`

I also removed ufw but the output was the same

**Comment by andryyy** [comment]
Your reverse proxy is not configured correctly then. The HTTP request should not be proxied to a HTTPS port.

**Comment by dtoenies** [comment]
Well this is a new from scratch installation and I am pretty sure I didn't change anything. At least I changed nothing on nginx or installed an apache.

**Comment by andryyy** [comment]
Do you use a reverse proxy at all?

If not, can we check it together on your server via AnyDesk?

**Comment by dtoenies** [comment]
Sure, I never used but I think it will be easy!
I just left home so tomorrow would be fine for me. Should wie talk by mail about it?

**Comment by dtoenies** [comment]
Oh I forgot: I just installed mailcow and nothing else in this server

**Comment by andryyy** [comment]
Can you try to remove data/conf/nginx/nextcloud.conf, restart Nginx and try again?

**Comment by andryyy** [comment]
Should wie talk by mail about it? <- Yes, please. :) info@servercow.de

**Comment by philippnied** [comment]
Hi,
I'm having exactly the same error. I've installed nextcloud on a fresh installation and I'm getting the same error when trying to access with plain HTTP. Please tell me if I can help to solve this issue :-)

**Comment by andryyy** [comment]
Remove the site as previously said, please.

**Comment by philippnied** [comment]
Worked. Now I've got a valid certificate for my nextcloud.domain.tld :-)
I've copied the configurationfile for nextcloud back to its origin place now and nextcloud is also working with a valid certificate..

**Comment by andryyy** [comment]
Ah, I know what it is then, will fix it later, thanks!

**Comment by dtoenies** [comment]
> 
> 
> Can you try to remove data/conf/nginx/nextcloud.conf, restart Nginx and try again?

This also did it for me. But without copying the old nextcloud.conf the subdomain is redirectinng to the mailcow hostname.

Thanks for the quick and nice help :)

**Comment by andryyy** [comment]
It is still broken. :-( I will push a fix for this.
