### ISSUE TITLE
The current system configuration disables the quarantine functionality.

### ISSUE THREAD

**Issue by itsbhanusharma** [mailcow/mailcow-dockerized#2327]
I couldn't find documentation on how to enable it.

**Comment by andryyy** [comment]
Please ask this on IRC. 

![image](https://user-images.githubusercontent.com/2972950/52779634-d91f5a80-3048-11e9-9045-c1f90ee400ef.png)

**Comment by itsbhanusharma** [comment]
> Please ask this on IRC.

I tried asking on IRC and waiting for about 3 hours before I gave up and disconnected from there. 
can You please enlighten me on **retention per mailbox** and **maximum size in mb** 
I'm sorry, I'm seriously a noob at this, no prior experience on how it works. :(

**Comment by andryyy** [comment]
Retention: How many objects are stored in quarantine before it deletes the oldest. 

Maximum: Maximum size of a message in MiB. If it’s larger, it is dropped. 

:-) Hope that helps. 

You need to stay connected in IRC and ask your question from time to time if no one answers.

**Comment by itsbhanusharma** [comment]
> :-) Hope that helps.

Yes it definitely does :) Thank You very much :) :) . 
I'm not an avid IRC user and maybe that's why I couldn't understand it's lingo. :( my bad.

Shall I submit a PR for docs regarding this? I think it is kinda must have.
