### ISSUE TITLE
Nextcloud PHP version not compatible?

### ISSUE THREAD

**Issue by mitchellurgero** [mailcow/mailcow-dockerized#2328]
I get the following error after updating my Mailcow today:

When visiting https://domain.com/nextcloud AND when trying to use Nextcloud's OCC function:
```
This version of Nextcloud is not compatible with > PHP 7.2.
You are currently running 7.3.1.
```

Any ideas on how I can move forward for this? I'd mess around, but I don't want to mess anything up as I host multiple domains.

Edit 1: I tried `docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/updater/updater.phar"` however the update folder does not exist, how can I get it in there properly? Or where should I be looking to download an update for this?

Edit 2: Those looking for a quick resolution (might vary system-system, but for me the following works)

```bash
cd /opt/mailcow-dockerized/data/web/
mv nextcloud nextcloud_backup
wget https://download.nextcloud.com/server/releases/nextcloud-14.0.7.zip
unzip nextcloud-14.0.7.zip
cp -a nextcloud_backup/config/. nextcloud/config/ && cp -a nextcloud_backup/data/. nextcloud/data/
cd /opt/mailcow-dockerized/
docker exec -it $(docker ps -f name=php-fpm-mailcow -q) chown 82:82 -R /web/nextcloud/
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/updater/updater.phar"
```
Once this finished I had to load the Nextcloud home page, let that do its own update as well. When this step was done, it had disabled the external_users plugin. Updating to version 15 then reinstalling the plugin works as expected. Then once all that was said and done I updated to version 15 from 14.0.7 using the built-in updater in Nextcloud. So far all features tested work like a champ.

**Comment by andryyy** [comment]
Hm. You can download a copy of Nextcloud to `data/web/nextcloud2` (extract there), then copy your `data` and `config` directories from `data/web/nextcloud` to that new nextcloud2 folder. Move nextcloud to nextcloud_backup and move nextcloud2 to nextcloud. Then you will be able to upgrade NC.

**Comment by mitchellurgero** [comment]
phew that's a lot of moving around lol - I'll do that then. We can close this for now. Thanks @andryyy !

**Comment by andryyy** [comment]
Did it work? If not, mail me, I will fix it.

**Comment by mitchellurgero** [comment]
@andryyy sorry - I am super busy until Sunday. That's when I can do the update again. I will definitely let you know though!

**Comment by MoritzWeber0** [comment]
> Hm. You can download a copy of Nextcloud to `data/web/nextcloud2` (extract there), then copy your `data` and `config` directories from `data/web/nextcloud` to that new nextcloud2 folder. Move nextcloud to nextcloud_backup and move nextcloud2 to nextcloud. Then you will be able to upgrade NC.

I tried this. When running `docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/updater/updater.phar"` I get an error: 
`PHP Warning:  require_once(/web/nextcloud/config/config.php): failed to open stream: Permission denied in phar:///web/nextcloud/updater/updater.phar/lib/Updater.php on line 57
PHP Fatal error:  require_once(): Failed opening required '/web/nextcloud/updater/../config/config.php' (include_path='.:/usr/local/lib/php') in phar:///web/nextcloud/updater/updater.phar/lib/Updater.php on line 57`

When I try to access nextcloud via the webportal, I get an internal server error.

**Comment by andryyy** [comment]
"failed to open stream: Permission denied" of /web/nextcloud/config/config.php.

**Comment by andryyy** [comment]
Try `docker exec -it $(docker ps -f name=php-fpm-mailcow -q) chown 82:82 -R /web/nextcloud/config/`

**Comment by MoritzWeber0** [comment]
> Try `docker exec -it $(docker ps -f name=php-fpm-mailcow -q) chown 82:82 -R /web/nextcloud/config/`

Thank you. I should have thought of that myself ;) 
Nextcloud is working again perfectly :)

**Comment by andryyy** [comment]
Cool! :)

**Comment by mitchellurgero** [comment]
I ended up doing the following (Excuse the simple formatting):

```bash
mv nextcloud nextcloud_backup
wget https://download.nextcloud.com/server/releases/nextcloud-14.0.7.zip
unzip nextcloud-14.0.7.zip
cp -a nextcloud_backup/config/. nextcloud/config/ && cp -a nextcloud_backup/data/. nextcloud/data/
cd /opt/mailcow-dockerized/
docker exec -it $(docker ps -f name=php-fpm-mailcow -q) chown 82:82 -R /web/nextcloud/
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/updater/updater.phar"
```
Once this finished I had to load the Nextcloud home page, let that do its own update as well. When this step was done, it had disabled the external_users plugin. Updating to version 15 then reinstalling the plugin works as expected. Then once all that was said and done I updated to version 15 from 14.0.7 using the built-in updater in Nextcloud. So far all features tested work like a champ.

Also - Sorry for the late reply.
