### ISSUE TITLE
Handling of volumes with docker-compose down

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#233]
Hi there!
In the docs: https://andryyy.github.io/mailcow-dockerized/first_steps/#optional-log-to-syslog
it says to use `docker-compose down` but this way I would kill all my volumes, wouldn't it?.
Same with https://andryyy.github.io/mailcow-dockerized/install/#step-1-method-3 .

Is it mandatory to user `docker-compose down` here? If yes, what is the easiest method to backup and restore my volumes afterwards?

**Comment by mkuron** [comment]
As per the documentation (https://docs.docker.com/compose/reference/down/), the volumes are only deleted when you add the `-v` flag. So your volumes are safe. I have tested this once and my volumes were still there after `docker-compose down && docker-compose up` .

The volumes are stored in /var/lib/docker/volumes and you should be periodically backing up that folder anyway.

**Comment by chaosbunker** [comment]
i think you kill the volumes with `docker-compose down -v`, if by killing you mean wiping.

as far as i know, `docker-compose down` just takes them down, but keeps the data

**Comment by Braintelligence** [comment]
@mkuron Thanks a lot! I backup the whole VM daily, so the volumes are backed up as well 😜. Strange... from my experience volumes are killed by `docker-compose down`. I will try it out then after backing up.

Thank you, too @chaosbunker 😺.

**Comment by chaosbunker** [comment]
:-)

are you sure it killed your volumes? I used `docker-compose down` many times without any loss of data and just did it again to see what happens - and all good 😸

**Comment by Braintelligence** [comment]
I didn't try it with mailcow-dockerized yet, but with other containers. For some reason I believe that volumes were killed. *shrug*
