### ISSUE TITLE
FTS is case-sensitive

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized#2333]
Full text search is case-sensitive. Generally searches are expected to be case insensitive, so I would consider this a bug. I can't find an option to change it though.

**Comment by extremeshok** [comment]
correction, might be a bug, as the lowercase modifiers are specified in the 
function solr_config() {

**Comment by jhesketh** [comment]
Right, this is a feature-request then :-).

Would you mind sharing your solr-schema.xml?

Also I couldn't see where mailcow is placing the schema. Does it not need one?

**Comment by extremeshok** [comment]
@jhesketh https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/solr/docker-entrypoint.sh is where its generated

This is the dovecot recommended config
https://wiki2.dovecot.org/Plugins/FTS/Solr?action=AttachFile&do=view&target=solr-7.x-schema.xml

**Comment by jhesketh** [comment]
Ah neat, thanks (I was grepping for schema.xml!).

At a skim it appears to be attempting to set things to be case-insensitive, so perhaps this is a bug. (I've only skimmed it very quickly though as it's very late here and I've run out of time sorry)

**Comment by extremeshok** [comment]
Looks the same to me, hence my corrected comment ;P

To help with testing, was your search for the subject, sender or body ?

**Comment by jhesketh** [comment]
I tested subject and body. I was fiddling with other things (search across all-folders) so it wasn't very thorough and probably needs confirming.

**Comment by extremeshok** [comment]
confirmed, bug on my side too. 
@andryyy maybe we should just include the schema.xml and not configure via the json curl ?
I know the json is better for portability to new versions of solr

**Comment by andryyy** [comment]
We just need to configure it. :) Shouldn't be too hard.

**Comment by andryyy** [comment]
text_en_splitting seems to be a default field type. I will try it.

Seems to work. But it also looks like a rescan is needed.

**Comment by andryyy** [comment]
Was a bit more tricky... will push the change this evening.

**Comment by extremeshok** [comment]
Assume we need to flush all the solr data and let it reindex.

**Comment by andryyy** [comment]
Try without first. It should also work with fts rescan.

**Comment by andryyy** [comment]
A complete flush of data is not needed. Worst case is a rescan.

**Comment by jhesketh** [comment]
Thanks for the fix. It seems to be working now :-)
I had to do a rescan first though (`docker-compose exec dovecot-mailcow doveadm fts rescan -A`)

**Comment by feldsam** [comment]
Hello, is this fix in master or dev branch? I dont't see any refference to any commit in this issue...

**Comment by jhesketh** [comment]
The fix is in master.

**Comment by jpbaril** [comment]
$ docker-compose exec dovecot-mailcow doveadm fts rescan -A
Fatal: Unknown command 'fts', but plugin fts exists. Try to set mail_plugins=fts

I suppose I can instead try with this?
docker-compose exec dovecot-mailcow doveadm mail_plugins=fts rescan -A

EDIT: Well nevermind, I suppose it's because I have "SKIP_SOLR=y" in mailcow.conf file, which I had forgotten.

**Comment by andryyy** [comment]
Set SKIP_SOLR=n but make sure you have enough memory installed. It probably disabled itself because of low memory.

**Comment by leepfrog-ger** [comment]
I ran into this issue while evaluating mailcow for my use case (thanks for the great bundle btw andreyyy!) and updated using update.sh which worked without issues. 
After that I ran a rescan as described.
Yet I am still receiving different search results when changing the casing of the search term (e.g. different number of results for "Server" than for "server"). 

Any idea what else I could check? I've also rebuilt the index using `docker-compose exec dovecot-mailcow doveadm index -u user@domain '*'` but no change.

**Comment by andryyy** [comment]
Can you try this?

```
docker-compose stop solr-mailcow
docker-compose rm solr-mailcow # (confirm)
docker volume rm $(docker volume ls -qf name=solr-vol-1)
docker-compose up -d
```

Just want to make sure it happens on a clean index.

**Comment by leepfrog-ger** [comment]
Thanks for the quick reply. I've tried those steps and performed a rescan. No change in behaviour.

**Comment by andryyy** [comment]
You are on the latest image?

Need to run some more checks when I find time. Perhaps someone who cares more about Solr can chime in and test/fix? :)

![grafik](https://user-images.githubusercontent.com/2972950/53952056-2a62bd00-40d0-11e9-8e94-b8ef21f538a9.png)

This seems to work though. Strange. Which field is case-sensitive for you exactly?

**Comment by hachre** [comment]
I have a test case as well and can confirm that at least searching the "From" fields isn't *fully* case insensitive. 

In my test case searching for all lowercase yields only 2 results while searching with the first letter capitalized yields ~40. It may have to do with searching through all folders (my testcase depends on that). 

What's interesting is when I search with the first letter capitalized, I also get those 2 results (from the all lower-case search) added in, so some form of case insensitivity does indeed work.

**Comment by leepfrog-ger** [comment]
I've ran update.sh previously to posting and it didn't error out so it should be the most recent version at that time (yesterday evening).

From my testing it seems that all fields are behaving case sensitive (tested with "From", "Subject" and "Body"):
![2019-03-07 19_03_09- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979001-e4781a00-410c-11e9-9aaa-daad5a9a182a.png)
![2019-03-07 19_03_38- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979004-e5a94700-410c-11e9-95d8-4e1956cba708.png)
![2019-03-07 19_03_58- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979008-e6da7400-410c-11e9-89af-0638835293c7.png)
![2019-03-07 19_04_10- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979011-e80ba100-410c-11e9-9ed9-17dabd8df8a2.png)
![2019-03-07 19_04_22- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979014-e93cce00-410c-11e9-8d9f-faad1f64cdfd.png)
![2019-03-07 19_04_37- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979015-e9d56480-410c-11e9-93e6-9d666461d44a.png)
![2019-03-07 19_04_29- gmail _ sogo groupware](https://user-images.githubusercontent.com/10974885/53979018-eb069180-410c-11e9-8518-66e67e5c1574.png)

So now comes the strange part. I've just run update.sh and a rescan again to get to the most recent version and... the search behaves case-insensitive:

![image](https://user-images.githubusercontent.com/10974885/53979560-7e8c9200-410e-11e9-8c2d-ef1c7c7eb396.png)

Yesterday it was the same issue. I've updated, search seemd to work, and when testing further it stopped working and reverted back to the original case sensitive behaviour. At that time I attributed it to being tired but now that it has happened again I am sure that it wasnt just a product of my imagination.

Do you have any idea at all how something like this would come to happen? For now it seems to work, I'll keep an eye on it to see if/when it reverts back to being case sensitive.

**Comment by leepfrog-ger** [comment]
Today I checked again, case-insensitivity gone again. I did not perform any changes to the environment, in fact I did not even use it. Ran `docker-compose exec dovecot-mailcow doveadm fts rescan -A` and searches were case insensitive again.

The only thing that comes to mind is an IMAP sync job that runs regularly. Could that have some kind of effect on the index?

**Comment by andryyy** [comment]
No, something else is broken. I need to investigate. But time is so limited. :(

**Comment by hachre** [comment]
> Today I checked again, case-insensitivity gone again. I did not perform any changes to the environment, in fact I did not even use it. Ran `docker-compose exec dovecot-mailcow doveadm fts rescan -A` and searches were case insensitive again.

You're right, this works for me as well to temporarily restore complete case insensitivity. Wonder what makes it revert... Really strange!

**Comment by leepfrog-ger** [comment]
@andryyy rest assured that I really appreciate the time you are spending on this project. I wish I could help but my knowledge of java and docker is really limited, so the only thing I can do for now is try to isolate test cases which can reproduce the issue. 

I've done some more testing, and the following seems to be reproducible on my environment:

1. search is case insensitive
2. perform imapsync job via "schedule next"
3. wait for sync to finish. search is case sensitive
4. run `docker-compose exec dovecot-mailcow doveadm fts rescan -A`
5. search is case insensitive again

This was reproducible in 3 out of 3 attempts.

I noticed that towards the end of the imapsync run the CPU utilization of the solr java process as well as the dovecot/indexer-worker is increased (30-80%) for about a minute until it decreases back to < 1%. 
I was thinking that maybe there is some kind of post-sync index update taking place?

**Comment by hachre** [comment]
I can confirm that I also have an imapsync job set up and in my last test search reverted back to being case sensitive within 3 minutes which would match the imapsync job time frame roughly (I've set it to every 5 mins).

**Comment by andryyy** [comment]
Not related to imapsync. I can reproduce it in some weird ways.

If we switch to the files Dovecot recommends (unmanaged schema), @evilstiefel kills me.

**Comment by leepfrog-ger** [comment]
Just a heads up: since I updated to the March 10 commits I cannot reproduce this issue any more, so the new schema seems to work

**Comment by andryyy** [comment]
Can you check a down and up -d?

**Comment by leepfrog-ger** [comment]
Checked with down/up -d, re-run imapsync, re-run a rescan, performed test searches between all those steps.
The issue is gone

**Comment by hachre** [comment]
Issue is gone for me as well, so I'll close this. Thanks!
