### ISSUE TITLE
decrypt locally stored emails...

### ISSUE THREAD

**Issue by yves030** [mailcow/mailcow-dockerized#2337]
Hello everybody,
I am faced with the challenge of moving e-mails sent by the user "John" via an account "office@company.com" from the SENT folder of the account "office" to the SENT folder of the account "John". (Since Outlook and many other MailClients do not support sending alias emails, there are 2 accounts in the client for the user, one of which is only used to send to the alias email address "office". There are also really two different accounts and not the same account 2 times configured with different email sending address only, because I don't want the quite large mailboxes to be replicated twice on the clients).
On the server side I now want to examine the e-mails in the SENT folder via cron and move them to the "correct" send account of the respective user. The information I need to differentiate is in the FROM header. Problem: the e-mails are encrypted on the volume and decrypting with doveadm according to this "manual" (https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-mail-crypt/) doesn't work (the e-mails look different, but are still not in plaintext). What am I doing wrong?  Or is this a bug? How do I get to the email headers to see which user submitted the email?

Thank you

**Comment by andryyy** [comment]
They are lz4 compressed.

**Comment by yves030** [comment]
Hi,

if I only would have taken a closer look to the first line of the decrypted file I would have seen the header "Dovecot-LZ4"... and immediatle would have known, what to do.

Thank you very much for pointing me in the right direction. For anybody else having the similar needs, here is the one-liner to decrypt and store an eMail-Message file (from inside dockerized mailcow):

`doveadm fs get compress lz4:0:crypt:private_key_path=/mail_crypt/ecprivkey.pem:public_key_path=/mail_crypt/ecpubkey.pem:posix: <crypted_input_file> > <decrypted_output_file>`

regards,
Yves

**Comment by ckruijntjens** [comment]
> Hi,
> 
> if I only would have taken a closer look to the first line of the decrypted file I would have seen the header "Dovecot-LZ4"... and immediatle would have known, what to do.
> 
> Thank you very much for pointing me in the right direction. For anybody else having the similar needs, here is the one-liner to decrypt and store an eMail-Message file (from inside dockerized mailcow):
> 
> `doveadm fs get compress lz4:0:crypt:private_key_path=/mail_crypt/ecprivkey.pem:public_key_path=/mail_crypt/ecpubkey.pem:posix: <crypted_input_file> > <decrypted_output_file>`
> 
> regards, Yves

Hi Yves,

How coulde we restore a complete folder?

**Comment by waja** [comment]
Maybe it's a good idea to add this information to the documentation?

**Comment by Adorfer** [comment]
for the sake of completness: in case you have the credentials (PWs) of both accounts, i would recommend to use imapsync. 
Not only because it's used by mailcow already for remote-fetching, but since it's the standard tool for this. 

the benefit is that you do not run into any kind of risk killing index files, readcounter etc (if you decrpt/copy mails locally between user directores) 

https://github.com/imapsync/imapsync

**Comment by MAGICCC** [comment]
> Maybe it's a good idea to add this information to the documentation?

Like this? https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-mail-crypt/
