### ISSUE TITLE
Solr uninstall

### ISSUE THREAD

**Issue by king1979** [mailcow/mailcow-dockerized#2338]
I forgot to disable solr in the mailcow.conf because my server has only 2 GB Ram.
Is it possible to uninstall Solr later.

**Comment by MAGICCC** [comment]
Just disable SOLR in your mailcow.conf
~`SKIP_SOLR=n`~
`SKIP_SOLR=y`

**Comment by Braintelligence** [comment]
@magiccc you mean `SKIP_SOLR=y`?

**Comment by MAGICCC** [comment]
Yes lol

**Comment by andryyy** [comment]
Run `docker-compose up -d` then.

**Comment by king1979** [comment]
Thanks for your help.
Is it normal that the container `solr-mailcow` is still running after entering `docker-compose up -d`?

**Comment by MAGICCC** [comment]
Yes thats normal
