### ISSUE TITLE
Sieve Filter for outgoing eMails

### ISSUE THREAD

**Issue by yves030** [mailcow/mailcow-dockerized#2339]
Hi all,

Sieve Filters are a great way to do filtering on incoming eMails.
I am looking for an easy way to do similar things on outgoing eMails.

Or, as an alternative, how can I "hook" my own application onto the "send-queue", so that my applications gets started on each new message, that a user sends out?

thank you
yves

btw... 
I think submitting bugs and feature-requests is not the right way to ask for help... but I cound not
find an active mailing-list or forum to put those questions... can someone recommend me such a forum / list?

**Comment by Braintelligence** [comment]
Concerning your btw: Did you read the first section of the "new issue" - template?...

**Comment by andryyy** [comment]
IRC it is. :) Perhaps a mail list in the future, not sure.

But right now it is IRC (can take hours or days) or support subscription.

Back to topic: Something like a local alias (/etc/aliases) that pipes to a script (needs to be deployed inside the container) could work. That local alias would need to be the destination of a bcc map in mailcow UI.

**Comment by yves030** [comment]
@Braintelligence 
.. not sure, what you mean... should I have opened a "regular issue"?
As my request is something than cannot be done ootb I thought a feature request is the most adequate request... and the request itself... whats wrong with it? I cant follow you... maybe its due to my bad english?

@andryyy 
thank for your suggestion. I tried, but had no success as the command "newaliases" is missing...??

regards,
yves

**Comment by andryyy** [comment]
It is there...
```
docker-compose exec postfix-mailcow which newaliases
```
Braintelligence wants to say that this is not a channel for support. We use IRC for community support. Urgent stuff or commercial setups => https://www.servercow.de/mailcow#support

You can open a FR, but I personally don't have much (any?) free time over the next weeks.

**Comment by yves030** [comment]
hi,

unfortunately,

`docker-compose exec postfix-mailcow which newaliases`

becomes executed, but has no effect at all, it seems, as if any alias from /etc/aliases is ignored...?

ty,
yves
