### ISSUE TITLE
Working configuration for docker nginx-proxy

### ISSUE THREAD

**Issue by Glowmanek** [mailcow/mailcow-dockerized#2340]
Hi, Do you have any functional nginx-proxy configuration for mailcow setup please? I tried to set up with the help of documentation even with a local issue, but without success. nginx-proxy does not send anything to mailcow nginx and falls on "Service not available"

Thx

**Comment by andryyy** [comment]
The doc examples are working. 

This issue is providing zero information. :/ I will close it. Please recheck your configuration and ask for support in IRC. :)
