### ISSUE TITLE
when create email, email don't have directory

### ISSUE THREAD

**Issue by Afondevi** [mailcow/mailcow-dockerized#2341]
Hello, 

**Describe the bug, try to make it reproducible**
When I create email from domain, and go to Sogo to see my email content is empty.

Further information (where applicable):
 - Your OS : Debian 9
 - Your virtualization technology : VPS OVH
 - Docker and Docker Compose versions
```
Docker version 18.09.2, build 6247962
docker-compose version 1.23.1, build b02f1306
```
 - Browser : Chrome

Picture problem
<img width="1680" alt="capture d ecran 2019-02-17 a 17 47 06" src="https://user-images.githubusercontent.com/11740298/52916128-1d765900-32dc-11e9-89d2-127330a58a95.png">

**Comment by Braintelligence** [comment]
Are you really expecting help without filling out the issue template?

**Comment by Afondevi** [comment]
Sorry @Braintelligence  ?

**Comment by Braintelligence** [comment]
By editing your original issue post you got a higher chance of someone helping you with your problem, now. The original version was really, really lacking. Though you're still missing relevant logs...

**Comment by Afondevi** [comment]
@Braintelligence ahah ! I'm bad devops sorry ^^'
