### ISSUE TITLE
Let's encrypt stopped signing for ADDITIONAL_SAN

### ISSUE THREAD

**Issue by damdinsharav** [mailcow/mailcow-dockerized#2343]
Hello, I have server with following config.

ADDITIONAL_SAN=mail.server-a.com,mail.server-b.com,mail.server-c.com

It used work fine.

Now that I added another IP and added following config.

SNAT_TO_SOURCE=SECOND_IP

Now let's encrypt gives only certificate for mail.server-a.com.

- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Waiting for Nginx... OK
- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Waiting for domain table... OK
- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Initializing, please wait...
- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Using existing domain key /var/lib/acme/acme/key.pem
- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
- acme-mailcow_1       | Mon Feb 18 09:13:10 +08 2019 - Detecting IP addresses... OK
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Found A record for mail.server-a.com: FIRST_IP
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Cannot match your IP SECOND_IP against hostname mail.server-b.com (43.231.113.7)
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Found A record for mail.server-c.com FIRST_IP
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Cannot match your IP SECOND_IP against hostname mail.btv.mn (FIRST_IP)
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Found A record for mail.server-b.com: FIRST_IP
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Cannot match your IP SECOND_IP against hostname mail.server-b.com (FIRST_IP)
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
- acme-mailcow_1       | Mon Feb 18 09:13:31 +08 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.

**Comment by andryyy** [comment]
Hi, you need to disable the ip check in mailcow.conf in this case. Run up -d afterwards.

The HTTP verification should be enough.

**Comment by damdinsharav** [comment]
Thank you @andryyy . It worked.
