### ISSUE TITLE
Access from Reverse proxy .. 502 Bad Gateway

### ISSUE THREAD

**Issue by GlowManCZ** [mailcow/mailcow-dockerized#2344]
Hello, I use mailcow and reverse proxy to communicate with it but every 10 minutes there will be a minute failure with Bad Gateway 502 error. Below I attach log from proxy.

`Custom dhparam.pem file found, generation skipped
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2019/02/18 15:02:15 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2019/02/18 15:02:15 Watching docker events
dockergen.1 | 2019/02/18 15:02:16 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx.1    | 2019/02/18 15:07:38 [warn] 33#33: *16 upstream server temporarily disabled while reading response header from upstream, client: 37.188.246.192, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:07:38 [error] 33#33: *16 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 37.188.246.192, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:08:17 [warn] 33#33: *34 upstream server temporarily disabled while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:10:07 [warn] 33#33: *235 upstream server temporarily disabled while reading response header from upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:10:07 [error] 33#33: *235 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 31.31.77.95 177.241.244.214 - - [18/Feb/2019:15:12:52 +0000] "GET / HTTP/1.1" 503 615 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
nginx.1    | 2019/02/18 15:13:17 [warn] 33#33: *513 upstream server temporarily disabled while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | ntes-it.com"
nginx.1    | 2019/02/18 15:13:34 [warn] 33#33: *515 upstream server temporarily disabled while reading response header from upstream, client: 92.62.227.159, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=1KICM7QK391FT5I0T6TQ5R0STS&DeviceType=iPad&Cmd=Ping HTTP/1.1", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=1KICM7QK391FT5I0T6TQ5R0STS&DeviceType=iPad&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | g", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:14:54 [warn] 33#33: *527 upstream server temporarily disabled while reading response header from upstream, client: 92.62.228.139, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=tomas.marek@agentes-it.com&DeviceId=2TSKK1G3BP77B9ODT2V59IOE4G&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=tomas.marek@agentes-it.com&DeviceId=2TSKK1G3BP77B9ODT2V59IOE4G&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | ype=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:14:59 [warn] 33#33: *529 upstream server temporarily disabled while reading response header from upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | com"
nginx.1    | 2019/02/18 15:16:24 [warn] 33#33: *533 upstream server temporarily disabled while reading response header from upstream, client: 92.62.227.159, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=O868AML7V92IV8TJ3242QK357S&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=O868AML7V92IV8TJ3242QK357S&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | &Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:17:57 [warn] 33#33: *536 upstream server temporarily disabled while reading response header from upstream, client: 37.188.246.192, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?User=klara.kopecka@agentes-it.com&DeviceId=FJH8EBGIT175V4PBKNFLAVENRK&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | ing", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:18:17 [warn] 33#33: *538 upstream server temporarily disabled while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:18:17 [error] 33#33: *538 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:23:18 [warn] 33#33: *553 upstream server temporarily disabled while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:23:18 [error] 33#33: *553 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.22.1.1, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice HTTP/1.1", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?Cmd=Ping&User=vachta%40akvachta.cz&DeviceId=SEC1F6A7F0A27AC4&DeviceType=SamsungDevice", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:23:33 [warn] 33#33: *559 upstream server temporarily disabled while reading response header from upstream, client: 92.62.227.159, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=1KICM7QK391FT5I0T6TQ5R0STS&DeviceType=iPad&Cmd=Ping HTTP/1.1", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=vojtech.kacirek@agentes-it.com&DeviceId=1KICM7QK391FT5I0T6TQ5R0STS&DeviceType=iPad&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | TS&DeviceType=iPad&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:24:04 [warn] 33#33: *571 upstream server temporarily disabled while reading response header from upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://[fd4d:6169:6c63:6f77::e]:8080/Microsoft-Server-ActiveSync?User=fakturace@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | md=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:24:06 [warn] 33#33: *573 upstream server temporarily disabled while reading response header from upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://172.22.1.11:8080/Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | com"
nginx.1    | 2019/02/18 15:25:00 [error] 33#33: *585 no live upstreams while connecting to upstream, client: 46.135.5.83, server: mailadmin.agentes-it.com, request: "POST /Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping HTTP/2.0", upstream: "http://nginx/Microsoft-Server-ActiveSync?User=ucetni@agentes-it.com&DeviceId=GAG5J9CVN10IDALGL4776QA400&DeviceType=iPhone&Cmd=Ping", host: "mailadmin.agentes-it.com"
nginx.1    | 2019/02/18 15:25:02 [error] 33#33: *583 no live upstreams while connecting to upstream, client: 92.62.228.139, server: mailadmin.agentes-it.com, request: "GET /debug HTTP/2.0", upstream: "http://nginx/debug", host: "mailadmin.agentes-it.com"
`

**Comment by GlowManCZ** [comment]
Problem solved !

**Comment by mvthul** [comment]
> Problem solved !

How did you solved this?

**Comment by the-voidl** [comment]
@GlowManCZ I would also be interested in a solution
