### ISSUE TITLE
502 Bad Gateway nginx

### ISSUE THREAD

**Issue by dtoenies** [mailcow/mailcow-dockerized#2345]
Hello,
I am using mailcow with nextcloud installed. After a few hourd of using I am getting the following error while trying to connect via http
`502 Bad Gateway`

The Watchdog is giving me the following Information about the error but is not really able to restart the Service cause the messages are send every two minutes:
`Watchdog: php-fpm-mailcow hit the error rate limit
connect to address 172.22.1.10 and port 9001: Connection refused
`

So I had a look at the php-fpm logs and found the attatched entry
[php-fpm_log.txt](https://github.com/mailcow/mailcow-dockerized/files/2876388/php-fpm_log.txt)

Before this error occurred I took a look at the child processes and I had 9. After the error there was no child process left.

In my `data/conf/phpfpm/php-fpm.d/pools.conf` i increased the `pm.max_children` cause it seemed that php-fpm is failing less with a higher number of allowed children.

I really don't know why php-fpm is failing all the time. It seems it just happens when I use Nextcloud.

By the way:
I have neither reverse proxy nor ufw. Just a clean install ;)

Any help is welcome!

Best wishes =)

**Comment by GlowManCZ** [comment]
Are all containers running? Have you tried to restart the php-fpm container restart?

**Comment by andryyy** [comment]
What's in the redis-mailcow logs when that happens (same time)?

**Comment by dtoenies** [comment]
Yes all containers running until suddenly php-fpm is hittting the rate limit and I get an 502 error.
After a docker-compose down && docker-compose up -d everything is working fine again until the next error.

**Comment by dtoenies** [comment]
My redis log is empty for this time but it just happened again.
This is what the redis log said:
redis-mailcow_1      | 94:C 18 Feb 2019 20:53:03.199 * RDB: 0 MB of memo
ry used by copy-on-write
redis-mailcow_1      | 1:M 18 Feb 2019 20:53:03.259 * Background saving
terminated with success
redis-mailcow_1      | 1:M 18 Feb 2019 20:54:04.088 * 10000 changes in 6
0 seconds. Saving...
redis-mailcow_1      | 1:M 18 Feb 2019 20:54:04.092 # Can't save in back
ground: fork: Resource temporarily unavailable
redis-mailcow_1      | 1:M 18 Feb 2019 20:54:10.003 * 10000 changes in 6
0 seconds. Saving...
redis-mailcow_1      | 1:M 18 Feb 2019 20:54:10.005 * Background saving
started by pid 96
redis-mailcow_1      | 96:C 18 Feb 2019 20:54:10.107 * DB saved on disk
redis-mailcow_1      | 96:C 18 Feb 2019 20:54:10.108 * RDB: 0 MB of memo
ry used by copy-on-write


Sorry for the bad appearance, I am on mobile phone right now

**Comment by andryyy** [comment]
Try `echo 1 > /proc/sys/vm/overcommit_memory`, run `docker-compose down` and `docker-compose up -d` then. Curious if it's really Redis failing or if it's PHP-FPM (more likely).

**Comment by dtoenies** [comment]
My system is telling me following even I am root:
root@h2867:/opt/mailcow-dockerized# echo 1 > /proc/sys/vm/overcommit_
memory
bash: /proc/sys/vm/overcommit_memory: Keine Berechtigung

My Provider is strato and I am running Ubuntu 18.04 if this helps.

**Comment by dtoenies** [comment]
I opened it with nano and it is a 1 inside

**Comment by dtoenies** [comment]
Sorry for the huge amount of comments, but I had to disable oom_kill_disable: true in docker-compose.yml on installation cause I was not able to start the images with enabled.

**Comment by andryyy** [comment]
It’s probably an older container format. OpenVZ? At least not KVM. That’s not so good with mailcow. :(

**Comment by GlowManCZ** [comment]
We also use strato.de internally, and I'm sure that Hyper is using KVM, and that's what Virtuozzo is all about as an administration. I hope no provider no longer using OpenCZ technology :-)

**Comment by andryyy** [comment]
Doesn't look like KVM. He cannot change Kernel parameters. :/

OpenVZ is not dead. :O

**Comment by dtoenies** [comment]
Well yes, I tried to figure something out and found this link: https://www.strato.de/faq/server/welche-server-und-betriebssysteme-bei-strato-sind-docker-ready/

And cause I am running a V-Server Linux I am not able to run docker properly :(

Thank you for the fast help :)

**Comment by dtoenies** [comment]
Just to inform you what happened next: I ordered a root server from an other provider and everything is working like a charm :)
Very nice work!
