### ISSUE TITLE
Enable Vacation from mailcow administration 

### ISSUE THREAD

**Issue by GlowManCZ** [mailcow/mailcow-dockerized#2346]
It might be possible to add an automatic answer to the mailbox administration. With the possibility to enter the date from when to when and the message that writes it. I know now that this option is in Sogo but that requires a user login and most of my north users are not technically based so they ask me to turn on this answer. But I can not activate it without their passwords. If this could be added, it would be best.
Thx Tomas

**Comment by andryyy** [comment]
You can already add sieve filters from the UI.

Edit: Oh my, I didn't sleep at all last night, what did I just write?

**Comment by GlowManCZ** [comment]
Ohhhhh, I know that very well :-) It was just an option for people who are not technically capable of enabling them to turn people off IT support in administration. Our technical support can make the most of writing to excel: D: D: D therefore I created this issue: D

**Comment by extremeshok** [comment]
mailcow admin -> Configuration -> Mail Setup -> Filters
Click [add filter], 
username: user u want the responder for
Filter type: prefilter
Short description: autoresponder
Script:
```
require ["fileinto", "vacation"];
# Move spam to spam folder
if header :contains "X-Spam-Flag" "YES" {
  fileinto "spam";
  # Stop here so that we do not reply on spams
  stop;
}
vacation
  # Reply at most once a day to a same sender
  :days 1
  :subject "Out of office reply"
  :addresses ["*"]
"I'm out of office, please contact Joan Doe instead.
Best regards
John Doe";
```
Click [validate] then [add]

**Comment by andryyy** [comment]
Reminds me we need some sieve presets. :)

**Comment by GlowManCZ** [comment]
Thx 👍..... ohh yes presets will be good 🥇

**Comment by Adorfer** [comment]
I really like to see this as an (domain-) admin action for the users who just happen to forget to set it up themselves. (with the current lack of 2FA for users it's at least readable in sogo if they hand over a PW to the admin or colleague)

**Comment by andryyy** [comment]
You can create prefilter sieve scripts as admin. Just create such a sieve script for a given user and stop any further script execution. I think you need an explicit “keep”.
