### ISSUE TITLE
use remote vps as proxy and tunnel to send email

### ISSUE THREAD

**Issue by keramist** [mailcow/mailcow-dockerized#2347]
**Is your feature request related to a problem? Please describe.**
i can install mailcow on homelab machine
but when i send email , the sender ip shows local host isp ip.

i use nginx(haproxy) +frp(tunnel)  for remote vps ip and port redirect
but all sent email ,the postfix and mta shows local ip not the remote tunnel(proxy) ip
how can i resolve it? 

remote vps :   nginx(haproxy)+frps    
local homelab host:  frpc+mailcow

**Describe the solution you'd like**

how to modify all email sender ip as vps ip

**Additional context**
none

**Comment by henryclw** [comment]
Hi, I met with almost the same issue, I want to host the mailcow at home but using my VPS for all outgoing traffic. Would you mind providing more details about how you did it?
