### ISSUE TITLE
watchdog mishandles multiple ipv6nat containers

### ISSUE THREAD

**Issue by iiegn** [mailcow/mailcow-dockerized#2348]
I have a set-up where i use another [ipv6nat container](https://github.com/robbertkl/docker-ipv6nat). This works ok as long as the other container name does *not* contain `ipv6nat` in its name. However, if the name does contain the string, mailcow watchdog will restart mailcow's ipv6nat container every minute.

As far as i can tell
 - the watchdog [ipv6nat_checks()](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/watchdog/watchdog.sh#L353) are not sensitive enough `"select( .name | tostring | contains(\"ipv6nat\")) | .id"` 
 - the container name could be more specific than `ipv6nat` (like ipv6nat-mailcow)

**Comment by iiegn** [comment]
The `ipv6nat_checks()` seem to be fixable - but i was wondering whether there is a reason for the container name diverting from the `SOMETHING-mailcow` convention?

**Comment by andryyy** [comment]
Hi, we can change that. There is no reason actually.

**Comment by mkuron** [comment]
I guess the reason is that ipv6nat applies to all Docker containers, not just Mailcow‘s. But if its ok to run multiple, we might as well change the name.

**Comment by iiegn** [comment]
just for clarification, i run 2 docker-compose stacks on two different ip addresses; and i have ipv6nat handle each (network) individually. there _might_ be a way to have one ipv6nat handle both, but i haven't tried... in any case, my naive approach of spinning up another ipv6nat for another & unrelated docker-compose stack with `ipv6nat-SOMETHINGELSE` disrupted mailcow's watchdog.
