### ISSUE TITLE
Long mailbox name breaks width of mailcow web ui

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#235]
If you use "long" mailcow names (longer than firstname lastname) paired with long mail usernames the table rows get wider and it looks weird:
![grafik](https://cloud.githubusercontent.com/assets/6761196/25584538/c15c5f70-2e96-11e7-9ede-054a756b0cd5.png)

Maybe a word-break: break-all; or something might fix this. 😸

**Comment by andryyy** [comment]
Changed the style tag in footable. :)

**Comment by chaosbunker** [comment]
Not sure if this is ideal either - if the available space was used it would all fit ![untitled-3](https://cloud.githubusercontent.com/assets/16366980/25593718/2f049b88-2ebe-11e7-9818-f8127e9b047d.png)
