### ISSUE TITLE
Issue after restore : 502 Bad Gateway

### ISSUE THREAD

**Issue by amrnassar93** [mailcow/mailcow-dockerized#2353]
After freh install of mailcow on centOS 7 and tried to get my configurations through using the following command (./helper-scripts/backup_and_restore.sh restore all).

I can't login onto the UI, it gives me 502 Bad Gateway.

Also, i checked the logs for php-fpm-mailcow and i found that php-fpm-mailcow_1    | Waiting for SQL...

Any suggestions what could be the problem ?

Thanks in advance.

**Comment by gummipunkt** [comment]
mysql_mailcow_1 is up and running?

docker ps or docker stats should help you.

**Comment by alexsxb** [comment]
Did you also restore the mailcow.conf included in the backup folder? If not, try to copy the passwords at the top into you running config or replace the config by the one in the backup folder.

**Comment by amrnassar93** [comment]
Yes indeed, that was the problem.

Thanks alexsxb
