### ISSUE TITLE
[Question / Help Needed] Figuring out why this email got delievered

### ISSUE THREAD

**Issue by lajosbencz** [mailcow/mailcow-dockerized#2356]
Hello, I'm looking for some help to figure out how/why this email got through to my inbox.

[source.txt](https://github.com/mailcow/mailcow-dockerized/files/2894617/extortion-spam.txt)

[body.txt](https://github.com/mailcow/mailcow-dockerized/files/2894625/extortion-spam-body.txt)

I assume it's a phishing scam and no real harm was done, since the server only relayed the email from the IP of 81.3.154.235
Could someone confirm this assumption?

I know it's not strictly a mailcow related issue, but any tips/ideas are welcome!

**Comment by gummipunkt** [comment]
Hi,

just take a look into the email header:

X-Spamd-Result: default: False [4.41 / 15.00];
	 ARC_NA(0.00)[];
	 GREYLIST(0.00)[pass,body];
	 DMARC_POLICY_SOFTFAIL(0.10)[travelhood.com : No valid SPF, No valid DKIM,none];
	 RCPT_MAILCOW_DOMAIN(0.00)[travelhood.com];
	 IP_SCORE(0.03)[country: GB(0.14)];
	 MISSING_MIME_VERSION(2.00)[];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 MIME_GOOD(-0.10)[text/plain];
	 PREVIOUSLY_DELIVERED(0.00)[lajos.bencz@travelhood.com];
	 TO_DN_NONE(0.00)[];
	 HAS_LIST_UNSUB(-0.01)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 MX_GOOD(-0.01)[cached: mail.rsa-apps.com];
	 MIME_BASE64_TEXT(0.10)[];
	 FROM_NO_DN(0.00)[];
	 R_SPF_NA(0.00)[];
	 FORGED_SENDER(0.30)[lajos.bencz@travelhood.com,noreply@rsa-apps.com];
	 TO_EQ_FROM(0.00)[];
	 R_DKIM_NA(0.00)[];
	 RBL_SENDERSCORE(2.00)[207.58.56.176.bl.score.senderscore.com];
	 ASN(0.00)[asn:21396, ipnet:176.56.56.0/21, country:GB];
	 FROM_NEQ_ENVFROM(0.00)[lajos.bencz@travelhood.com,noreply@rsa-apps.com];
	 RCVD_TLS_ALL(0.00)[];
	 RCVD_COUNT_TWO(0.00)[2]

SPAM filtering is quite a big challenge in 2019. If you want the best SPAM solution, there's imho no way around gmail. After a few months with sorting emails into or outside your SPAM folder, you'll have a good SPAM filtering solution with RSPAMD, but it has to learn.

**Comment by lajosbencz** [comment]
Thank You!
