### ISSUE TITLE
Bug with new update

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2357]
Hello,

since new update i get an error with pulling watchdog:

Building watchdog-mailcow
Step 1/6 : FROM alpine:3.9
 ---> caf27325b298
Step 2/6 : LABEL maintainer "Andr? Peters <andre.peters@servercow.de>"
 ---> Using cache
 ---> b948af344994
Step 3/6 : RUN apk add --update   && apk add --no-cache nagios-plugins-smtp   nagios-plugins-tcp   nagios-plugins-http   nagios-plugins-ping   curl   bash   coreutils   jq   fcgi   nagios-plugins-mysql   nagios-plugins-dns   nagios-plugins-disk   bind-tools   redis   perl   perl-io-socket-ssl   perl-io-socket-inet6   perl-socket   perl-socket6   perl-mime-lite   perl-term-readkey   tini   tzdata   && curl https://raw.githubusercontent.com/mludvig/smtp-cli/v3.9/smtp-cli -o /smtp-cli   && chmod +x smtp-cli
 ---> Running in b21b775a6afa
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz

So now i am waiting since 1 hour... i dont think there comes Step 4/6.

**Comment by tobias992** [comment]
I manual edit the docker-compose.yml:

After Update: image: mailcow/watchdog:1.35
Fix: image: mailcow/watchdog:1.34

Now everything is running again.... at the moment.

**Comment by apoc4lyps** [comment]
currently there is not watchdog image with tag 1.35, https://hub.docker.com/r/mailcow/watchdog/tags

**Comment by apoc4lyps** [comment]
ok now it is online, I think Andre is currently updating the codebase etc.

**Comment by andryyy** [comment]
Check again please 

Mit besten Grüßen
André Peters

**Comment by tobias992** [comment]
haha, now its online xD
