### ISSUE TITLE
ClamAV Problem and some questions of understanding

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#2358]
Hi andryyy,
hi all,
I use mailcow-dockerized and actually have a problem with sending an excel sheet containing some makros. 
My mother-in-law wants to send this excel sheet to her boss (or to me, whatever recepient) and mail will not be send (something SMTP Error 5.7.1).

After searching here I found some similar bug reports
- ClamAV false positive #990
- ClamAV false positive with 5 PDF #1393 
- CLAMAV false positive #1548

The solution to this reports are like this:
```
So i set following in "data/conf/clamav/clamd.conf"

DetectPUA no
ExcludePua Packed
OLE2BlockMacros no
```
But for me this seems not to be a "good" solution, as it is degraded security (in my point of view).

In `ClamAV false positive #990` andryyy mentioned: `You can either whitelist the sender...`
But how to whitelist the sender? And where? I tried with logging in to mailcow-ui with the user account settings of my mother-in-law and within "Usersettings" - "Spamfilter" - "Whitelist" I added her email address... but this doesnt help, mail still not gets send, except sending to herself :-)

In RSPAMD Web-Gui History I found the following entries:
`3b-5c6f2c80-1f-664a5a80@36893537 | 172.22.1.248 | ulrike.sxxxxx@xxxxxxxxx.de | ulrike.sxxxxxxxx@xxxxxxxxxxxx.de | Test 12345
`
```
MAILCOW_WHITE (-1998)
MAILCOW_AUTH (-20)
MID_RHS_NOT_FQDN (0.5)
MIME_GOOD (-0.1) [multipart/mixed,multipart/alternative,text/plain]
TO_DN_ALL (0)
RCPT_MAILCOW_DOMAIN (0) [webunity.de]
TO_EQ_FROM (0)
RCVD_TLS_ALL (0)
CLAM_VIRUS (0) [Heuristics.OLE2.ContainsMacros]
```

If not send to herself but e.g. to my email address it looks like this:
```
VIRUS_FOUND (2000)
MAILCOW_AUTH (-20)
MID_RHS_NOT_FQDN (0.5)
MIME_GOOD (-0.1) [multipart/mixed,multipart/alternative,text/plain]
TO_DN_ALL (0)
RCPT_MAILCOW_DOMAIN (0) [webunity.de]
RCVD_TLS_ALL (0)
DKIM_SIGNED (0)
TO_DOM_EQ_FROM_DOM (0)
```

If I try to send this excel sheet I have no problem... RSPAMD Web-GUI looks like this:
```
VIRUS_FOUND (2000)
SOGO_CONTACT (-1998)
MAILCOW_AUTH (-20)
BAYES_HAM (-12.5) [100.00%]
MID_RHS_NOT_FQDN (0.5)
MIME_GOOD (-0.1) [multipart/mixed,text/plain]
TO_EQ_FROM (0)
RCVD_TLS_ALL (0)
TO_DN_ALL (0)
DKIM_SIGNED (0)
```

As you can see it detects the virus, but bypasses because it says next: SOGO_CONTACT (-1998)

So... my final questions after this much text (sorry for that):
- How to whiteliste a senders email address correctly so that excel sheets will not be false-positiv marked by clam av (aka: bypass clamav tests)
- What the heck is this SOGO_CONTACT, where can I configure it?

Thanks to all
Beste regards
Markus

**Comment by andryyy** [comment]
Didn’t https://github.com/mailcow/mailcow-dockerized/commit/260421448d564d60dfdbcdd1515d630a8ce0df29 disable that check? Do you know, @extremeshok ?

**Comment by andryyy** [comment]
Anyone wants to update the docs about how to whitelist a signature, please? :( Not sure if that’s missing.

**Comment by MarkusP** [comment]
So, andryyy, does this mean that updating my mailcow-dockerized to latest will solve my problem? The option is NO by default then and OLE/Macro objects will be bypassed? If so, I will give that a try.

What about that "SOGO_CONTACT" question of mine... any idea what that is? 

docs update: I would update the docs, with screenhots of latest mailcow-dockerized version but need to understand first how and where to do that whitelisting (and also testing if it works as expected)...

**Comment by MarkusP** [comment]
Update: did a backup of my installation and pulled new container versions and now I can send the excel file... so, it works now... is not my favourite solution (as written in my first comment) but for now i am fine with that... thanks!! :+1:

**Comment by andryyy** [comment]
The SOGO_CONTACT symbol indicates a message from a contact you have in SOGo. :)

**Comment by MarkusP** [comment]
ok ok... I see, dumb question... :-) but why does this reduces spam indicator by nearly 2000 points (SOGO_CONTACT (-1998))???

**Comment by andryyy** [comment]
Because you usually want mail from SOGo contacts. :)

**Comment by MarkusP** [comment]
So if I import lists of contacts in my SOGo all of these contacts can send me Office or whatever type of documents with "virus" in it and get somehow "whitelisted"??? isn't that dumb? contact/known person or not... if potentially virus within an email this must be filtered or marked...?!?!?

**Comment by andryyy** [comment]
Yes, if you import unknown users who send you viruses, you are dumb.

Instead of getting aggressive, create a PR to reduce it to 1000 or whatever.

**Comment by mkuron** [comment]
@markusp has a good point there. Virusses should be rejected even from contacts.

**Comment by andryyy** [comment]
Yes, should be reduced to 1000.

**Comment by andryyy** [comment]
Or less. That's the bug. It adds up to 1998 because it matches env and mime, I think.

We could reduce it to 200 or something like that.

Edit: 99 it is.

**Comment by MarkusP** [comment]
Wow... Lieber André, ich wechsel mal die Sprache, damit nicht meine mangelnden Englisch-Kenntnisse dazu führen, dass ich falsch verstanden werde... ich denke, dass das ok ist?!

1. Unbekannte Adressen zu importieren, die dadurch auf ein Whitelisting kommen (von diesem Verhalten wusste ich bis dato nichts, danke für die Aufklärung hier), ist leichtsinnig - da stimme ich zu. Dumm ist ein harter Begriff, zumal auch mir bekannte und vertraute Adressen durchaus
- von fremden/im falschen Namen Mails mit Virus drin an mich versenden können
- oder Clients von mir bekannten Personen/Adressen durch einen Virus verseucht sein können und daher eine mit einem Virus versehene Email an mich senden können

Stimmst Du mir hier eventuell (ein bisschen) zu?

2. Ich erkenne nicht, wo ich aggressiv geworden bin... meine Aussage mit dem Importieren war eine hypothetische auch hinsichtlich der Folgen. Ich hatte hier auf einen konstruktiven Austausch gehofft, mit jemandem, der sich offensichtlich sehr viel und sehr intensiv (weil beruflich bedingt??) mit diesem Thema auseinander setzt. Manchmal wundere ich mich über den Tonfall im Internet... Wenn ich irgendwas gesagt haben sollte, was Dich hat Aggressionen bei mir erkennen lassen, bitte ich hiermit förmlich um Entschuldigung. 

Ich wünsche noch einen schönen Abend und schönes Rest-Wochenende und danke für den Support, dass man Fragen stellen darf und das mailcow so ein tolles Produkt ist.

Gruß
Markus

**Comment by andryyy** [comment]
Habe es falsch verstanden. Bin genervt im Moment, sorry.

Klar ist das doof, er hat die 999 gleich 2x angewendet, dann konkurriert es mit ClamAVs 2000. Das habe ich nicht bedacht. Der Score für einen Kontakt ist jetzt nur noch -99.

**Comment by shaneonabike** [comment]
Could I confirm that by PR you meant to reduce the VIRUS_FOUND level down to 99... Or is there another variable I am missing. I just wanted to make sure and would be happy (if not now in default) to update the docs to help out.

**Comment by Braintelligence** [comment]
The above convo is about andryyy deciding to revalue the symbol SOGO_CONTACT from -1998 to -99 if I understood correctly. So as to not overvalue having someone in your contacts if a virus is present. I don't think any documentation change is necessary.

**Comment by andryyy** [comment]
It is reduced, yes. :)

**Comment by shaneonabike** [comment]
Thanks for clarifying!
