### ISSUE TITLE
Auestion about ARC

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2361]
Hello, I try to ask on irc, but no reply. Overall I have problems to get replies on irc, but on the other hand, on Slack it is better. I don't know why....

I like to ask about ARC signing and don't want openening issue on Github
According to what I read and understand, ARC seals are usefull when mailcow server is in the middle of way, when mail is forwarded to another domain and mta
so I setup some alias to forward mail to gmail and send test message, them opening messag esource on gmail
but no ARC seal by mailcow added
I see ARC seals only on messages sent from mailcow
I beleive, that there should be ARC seal with ARC auth results added to headers

**Comment by andryyy** [comment]
[10:29:21] <feldsam> I beleive, that there should be ARC seal with ARC auth results added to headers
[10:49:56] * feldsam (~Adium@) has left #mailcow

On a Sunday. You waited 20 minutes in IRC - on a Sunday.
The issue template you read and deleted also says "hours to days".

**Comment by feldsam** [comment]
hmm, I don't like irc, because there is no notification on answer (for ex. email), I think that Slack is better, why you dont use it? I like to ask, and be notified on reply, of course I can wait days....

**Comment by andryyy** [comment]
Highlights.

**Comment by andryyy** [comment]
Turns out the sender was not using ARC.
