### ISSUE TITLE
SOLR maintenance tasks

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#2363]
Hello!

Just tested SOLR, and I must say I'm impressed with the results.
To test it fully, first, I reindexed all mailboxes using: 
sudo docker-compose exec dovecot-mailcow doveadm -v index -A "*"
Then I tried searching from SOGo, and WOW that was fast and accurate....

I'm new to SOLR and I have done some digging, that its a good idea to set up maintenance tasks.

What i have dug up-

Dovecot 2.2.3 and newer do only soft commits to the Solr index to improve performance. You must run a hard commit once in a while or Solr will keep increasing its transaction log sizes. It's recommended to configure cron jobs: 

1) Commit changes every 10 minutes.
Is this already integrated into the present configuration? 
If no, how to execute this command?

I tried: 
`docker-compose exec solr-mailcow curl http://localhost:8983/solr/update?commit=true`
but it didn't work

2) Optimize database daily at night, also didn't work.. Maybe it is already done in the background also?
`curl "http://127.0.0.1:8983/solr/dovecot/update?optimize=true"`

3) Maybe it's a good idea to reindex once a week? 

I created a small script
```
#!/bin/bash
# Filename: dovecot-index.sh
# Path to mailcow-dockerized, e.g. /opt/mailcow-dockerized
cd /path/to/your/mailcow-dockerized

/usr/local/bin/docker-compose exec dovecot-mailcow doveadm -v index -A "*"
```
And make a cronjob for every saturday 
`0 0 * * SAT /bin/bash /path/to/dovecot-index.sh`

Any other maintenance suggestions ?

**Comment by andryyy** [comment]
Hi! :) 

It auto-commits after "so many" docs or after a given time: https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/solr/docker-entrypoint.sh#L360

There's only a cron for optimize: `/usr/bin/curl http://solr:8983/solr/dovecot/update?optimize=true` (runs daily).
