### ISSUE TITLE
ActiveSync - iOS Mailbox empty for some users - SOGo web access okay

### ISSUE THREAD

**Issue by vizion8-dan** [mailcow/mailcow-dockerized#2364]
Hi, I am on latest mailcow-dockerized. My server hosts one eMail domains for a total of nine Mailboxes. Everything works fine for quite a while now **except ActiveSync access for two out of the nine Mailboxes** does not work: 

- These two Mailbox can connect via ActiveSync but only see a blank/empty mailbox.
- Connecting these users via IMAP (with the help of the personalized iOS mobileconfig file) works perfectly and correctly shows all E-Mails in Mailbox.
- Loggin into the SOGo webinterface correctly displays all E-Mails
- I already removed the E-Mail configuration from the iOS devices and re-connected them afterwards. Problem persists.
- I restarted the SOGo container, updated mailcow, increased the `WOWorkersCount = "80";` and resetted the ActiveSync device cache (as the help file states: _In many cases a device cache reset will help to recover a broken ActiveSync profile. Attention: All elements will be redownloaded!_) - Problem persists...

Logging seems without findings (to me). Some of these WARNINGS only, which I suppose are okeeey...?

`[11]: [WARN] <0x0x561e94831af0[WOWatchDogChild]> pid 39879 has been hanging in the same request for 8 minutes`

Thank you for any help or ideas on this issue!

**Comment by andryyy** [comment]
Hi, you might need to enable EAS debugging in SOGo. But you are better off asking that on SOGos bug tracker.

Try to change a line in `data/conf/sogo/sogo.conf`:
```
# From
    SOGoMaximumSyncResponseSize = 512;
# To
    //SOGoMaximumSyncResponseSize = 512;
```
Restart SOGo, clean the device cache (again) and re-add the profiles to Nine.

Syncing a mailbox can also take a LONG time. So it might seem empty for a while.

**Comment by vizion8-dan** [comment]
Hi André, thanks a lot for your quick reply and help! 
I`ll give it a try.

**Comment by vizion8-dan** [comment]
Thanks again for the support.  I`ll close this issue  while checking logs.

**Comment by andryyy** [comment]
Did it work?
