### ISSUE TITLE
Main Backup Mailcow instances

### ISSUE THREAD

**Issue by amrnassar93** [mailcow/mailcow-dockerized#2365]
I need to implement hot spare instance for my existing Mailcow server. Could any one provide me with the needed steps to deploy something like that.

Thanks in advance.

**Comment by X1Aaron** [comment]
I also would like to know how to do this. I am guessing you have have to rsync some files/folders, but not sure if you could do that with the server in use.

I have created a backup script here:

https://github.com/aaronstuder/backup-scripts/blob/master/mailcow-backup

I'll try to add a restore section, and maybe we could do hourly backup/restore. Would not be in real time, but would be better then nothing :)

Also, take a look at this:

https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_migration/

Seems like we should be able to come up with something. Maybe I docker swarm? I will try to test somethings :)

**Comment by X1Aaron** [comment]
Based on this: https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_migration/

You should be able to:

1. Install Docker/Mailcow on the Backup Server
2. Make sure Docker is stopped.
3. Setup SSH Keys for easy rsync.
4. Run rsync.
5. Start Docker
6. Run docker-compose up -d

_What I don't know is if you could do this with the both servers running..._

I could write a script to do it every hour, no issue.

**Comment by X1Aaron** [comment]
Maybe a better solution would be to sync backups, and restore them on the backup server. I will test that as well.
