### ISSUE TITLE
ylmf-pc block

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#2366]
My maillog is completely overrun by entries like these,

`Feb 26 09:36:50 mail postfix/dnsblog[23401]: addr 103.114.106.144 listed by domain hostkarma.junkemailfilter.com as 127.0.0.2
Feb 26 09:36:50 mail postfix/dnsblog[23390]: addr 103.114.106.144 listed by domain zen.spamhaus.org as 127.0.0.4
Feb 26 09:36:50 mail postfix/postscreen[23383]: PREGREET 14 after 0.27 from [103.114.106.144]:55309: EHLO ylmf-pc\r\n
Feb 26 09:36:50 mail postfix/postscreen[23383]: DNSBL rank 9 for [103.114.106.144]:55309
Feb 26 09:36:50 mail postfix/postscreen[23383]: HANGUP after 0.55 from [103.114.106.144]:55309 in tests after SMTP handshake
Feb 26 09:36:50 mail postfix/postscreen[23383]: DISCONNECT [103.114.106.144]:55309
Feb 26 09:36:51 mail postfix/postscreen[23383]: CONNECT from [103.114.106.144]:55421 to [172.22.1.6]:25
`
In the pre-docker time I blocked these with a firewall rule, but it seems not to work here.
Would a HELO block like described here work?

https://b4d.sablun.org/blog/2018-10-25-use-fail2ban-and-postfix-postscreen-to-fight-cutwail-botnet/

**Comment by andryyy** [comment]
You can implement it like this:
```
echo 'ylmf-pc REJECT' > data/conf/postfix/helo_access
docker-compose exec postfix-mailcow postconf -e 'smtpd_helo_restrictions = check_helo_access hash:/opt/postfix/conf/helo_access'
docker-compose exec postfix-mailcow postmap /opt/postfix/conf/helo_access
```

**Comment by andryyy** [comment]
But ... they don't even pass Postscreen, so nothing to worry about (besides the annying logs).

Check https://blog.sys4.de/abwehr-des-botnets-pushdo-cutwail-ehlo-ylmf-pc-mit-iptables-string-recent-smtp-de.html (commands are self-explanatory, no need to translate :)). You'll need to use the FORWARDING chain though.
