### ISSUE TITLE
Multiple storage server

### ISSUE THREAD

**Issue by concooord** [mailcow/mailcow-dockerized#2367]
Hi there,
Is there any possible in MailCow to add the additional server to storage of mails? For example my VPS have now 20GB of storage and I want add more space by adding the another server to hand the storage of Mail content.

**Comment by hachre** [comment]
The mail is essentially stored in a normal path on your host `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data` and `/var/lib/docker/volumes/mailcowdockerized_vmail-attachments-vol-1/_data`

You can use `mount --bind` to place a different disk into that path. This has to be done while Mailcow is not running (`docker-compose down`). This would allow you to source the disk space for mails and their attachments from a different place. Of course you'll have to take care of copying the current contents in those mail paths onto that other disk first.

This is an advanced setup, and isn't supported by the Mailcow team. Also there's no feature in Mailcow that would directly allow you to attach external drives.

**Comment by concooord** [comment]
Thanks for the answer. I ask about it, because it stores a lot of attachments at the e-mail as well as I have a lot of messages that I do not want to delete and I just end up with disk space on VPS. It seems to me that it would be good to have the opportunity to connect an additional server to mails just as storage for emails. At this moment, you will try to follow the path you indicated.

**Comment by make-github-pseudonymous-again** [comment]
> You can use `mount --bind` to place a different disk into that path.

Am I correct that `ln -s` would not work since the containers have FS restrictions (chrooted for instance)?
