### ISSUE TITLE
mail dovecot: pop3-login: Aborted login

### ISSUE THREAD

**Issue by PiCTaTe** [mailcow/mailcow-dockerized#2369]
Clients can't login through port 110..

User and password are correct, but logs tell that authentication is failed.

mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs):

**Comment by andryyy** [comment]
Check their settings for TLS/SSL. I don't see a problem with mailcow. :/ I just tested it.

**Comment by PiCTaTe** [comment]
I'm trying on my computer without ssl/tls and can't login.

**Comment by hachre** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/client/client-manual/

"... no authentication is allowed to take place without TLS."

**Comment by PiCTaTe** [comment]
Ok, thanks ;) 

I have one person using windows xp with outlook 2003. He is getting errors using ssl. How i can debug it?

**Comment by andryyy** [comment]
XP was release

**Comment by andryyy** [comment]
XP was released in 2001. 18 years ago. Time to upgrade. \o/
Before you enable some very freaky ciphers, I'd recommend to check the Dovecot docs about how to allow unencrypted connections from a single IP. That's probably better than changing ciphers for all users.

**Comment by PiCTaTe** [comment]
Ok. thanks.

**Comment by PiCTaTe** [comment]
this issue can be closed
