### ISSUE TITLE
mailcow/netfilter exits and does not restart

### ISSUE THREAD

**Issue by TReZ42** [mailcow/mailcow-dockerized#2370]
Hi,

mailcow/netfilter is exiting with "Exit 0" with following log :
> netfilter-mailcow_1  | Error in FORWARD chain order, restarting container

However it does not restart because of restart policy is on-failure.

It appears ipv6nat is starting after netfilter and insert some rules before MAILCOW, that is no more the first one so netfilter exits.

Manually restarting netfilter is OK, so maybe netfilter could depend on ipv6nat, or restart policy could be changed to always?

Thanks.

**Comment by andryyy** [comment]
Hi,

      restart: always

It always restarts.

IPv6 NAT needs to start last.

**Comment by TReZ42** [comment]
My bad, docker-compose.yml was not up to date... it was still using:
`restart: on-failure:1`

Thanks again.

**Comment by andryyy** [comment]
Oh, that’s probably a very old compose file then. :) thanks for your feedback.
