### ISSUE TITLE
Catchall behaviour not as expected

### ISSUE THREAD

**Issue by chc-pr** [mailcow/mailcow-dockerized#2374]
I recently found mailcow and have set up a test VM to play with it with a view to moving my mailserver. I quite like it so far, but I am having some problems setting up the catchall to work as wanted.

I followed the instructions on setting up a catch all account, but it is copying EVERYTHING to the catchall account, not just emails for the domain without a registered user. I tried restarting the server after setting it up, but that had no effect.

Is this the expected behaviour? If so, can someone point me in the direction of how to set it up so only mail which doesn't match any existing account is sent to the catchall account?

Thank you.

**Comment by andryyy** [comment]
It is copying EVERYTHING to the catchall account, not just emails for the domain without a registered user 

I don't understand this.

Do the doc update clarify your question/concern? See https://github.com/mailcow/mailcow-dockerized-docs/pull/134

**Comment by chc-pr** [comment]
Thank you for teh very prompt reply, but I don't think that the update relates to the situation. Let me try to be more specific.

A domain is set up as my.domain.
Users usr1@my.domain, usr2@my.domain and usr3@my.domain are configured.
These can all send emails to each other correctly.
usr1@my.domain is then assigned as a catchall address for my.domain.

Now, when usr2 sends and email to usr3, as usr3 is defined and exists, I would not expect that email to appear at the inbox of usr1, but it does. While I can see this might be useful behaviour, I would not expect it to be default behaviour. I need to have the catchall account only receive emails which are directed to accounts which are not defined within the mailserver.

Specifically, what I want is given the same three accounts set up as above, any emails to usr1, usr2 or usr3 would only go to those accounts and not to the catchall account (usr1). However and email to usr4@my.domain (which does not exist) should go to usr1 (the catchall account).

Hope that clarifies.

Thank you.

**Comment by andryyy** [comment]
I cannot reproduce this behavior.

**Comment by chc-pr** [comment]
Your last comment caused me to experiment a little further, and I might have found a bug ...
I created usr1 initially and set it up as a catchall
I then created usr2 + usr3 in my test.

Following your last comment, I removed the catchall from usr1 and created a new usr4 which I then setup as a catchall.

This now works fine. As I type, I am wondering if a user5 was set up if any emails to that would be sent to the catchall account. I am not able to test that until next week due to commitments for the remainder of the week (but I might be able to do it one evening). I will test that and let you know if that reproduces the problem.

Thank you for the support and the product. I am liking it so far ... though I don't like Sogo much, it is OK.

**Comment by chc-pr** [comment]
Oops, sorry didn't mean to close this

**Comment by hachre** [comment]
I also cannot reproduce it.

You're saying you created one mailbox, let's call it `usr1@domain.example`
You then added an alias `@domain.example` forwarding to `usr1@domain.example`
You then created two more mailboxes, `usr2@domain.example` and `usr3@domain.example`
And now when you send mail from `usr2` to `usr3`, that mail also arrives in the mailbox of `usr1`?

Is that correct?

**Comment by chc-pr** [comment]
> 
> 
> I also cannot reproduce it.
> 
> You're saying you created one mailbox, let's call it `usr1@domain.example`
> You then added an alias `@domain.example` forwarding to `usr1@domain.example`
> You then created two more mailboxes, `usr2@domain.example` and `usr3@domain.example`
> And now when you send mail from `usr2` to `usr3`, that mail also arrives in the mailbox of `usr1`?
> 
> Is that correct?

Yes, that is correct.

Further, I then deleted the alias for usr1@domain.example and created a new user usr4@domain.example for which I then added the alias @domain.example. 

Now, when I send an email from usr2 to usr3, it does NOT erroneously get copied to usr4, but acts as expected.

What I will shortly then test is to add a new usr5 and see if an email to that account then wrongly appears at usr4 too. I will report back shortly on that.

**Comment by chc-pr** [comment]
I have now done the last test described in my last reply and it appears to be working perfectly. I am not sure why it failed before, but it seems to be sorted now, so I am closing this thread. I am nt sure what I did or didn't do before that caused the 'issue', but I seem to have resolved it somehow. Maybe it was the fact that a single account was opened whne the catchall was setup? I don't know ... but I appreciate your help anyway. I will go and play with some more tests. I am a bit concerned at the stuff that needs to be done to get Thunderbird working, and the prospect that suggests for getting servers to connect to the mailserver to send status reports - but those are other threads and I am a long way from anything re that yet as I haven't even begun to test that ...

Thanks again.

**Comment by andryyy** [comment]
Caching is a bit aggressive sometimes. That was probably the issue here. :/ Strange.

**Comment by chc-pr** [comment]
That would make sense
