### ISSUE TITLE
Automated backup to another FTP

### ISSUE THREAD

**Issue by concooord** [mailcow/mailcow-dockerized#2378]
Hi,
have anyone solution to run ./helper-scripts/backup_and_restore.sh backup all as a CRON and automatically send the backup files to another server (backup FTP) ?

I try add cron by this :
0 */6 * * * root BACKUP_LOCATION=/opt/backup /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all

to backup file's for every 6h hours. You have idea how send this backup files to the other server after finishing backup?

Thank you for any reply guys.

**Comment by MAGICCC** [comment]
You can use scp, ftpput, rsync to upload the files to another server/FTP

**Comment by JustAB0x** [comment]
I am using lftp to archive this (probably not the most effecient way, but its what i'm familiar with).
I am running a cronjob that executes a .sh with the following content:

```
lftp -c "set ftp:list-options -a;
open ftp://username:password@backupserverhost;
lcd /local/path/to/backup/dir;
cd /backupserver/backup/dir;
mirror --reverse --parallel=3"
```

It puts the content of the local backup dir to the backupserver with 3 connections.
This is one way, if an old folder gets deleted on the local (mailcow) host, it stays on the backupserver.

I also run a cronjob to delete all local backups that are older than 3 days and on my backup server all that are older than 3 months. The time you want to keep your backups ofc might differ in your usecase.

**Comment by concooord** [comment]
@Fytcher
This sounds Good. Thank you very much! :)
