### ISSUE TITLE
A Proper guide to transfer to another  server

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#2379]
Hi Guys,

I am having some troubles with stability on my VM running mailcow-dockerized.

I tried to find some guide, how to move all inboxes, their emails, DKIM keys, and everything used by my mailserver.

So I want to ask/add a feature: Is there any guide, how to move all the data to another server safely?

Thanks!

**Comment by hachre** [comment]
I can give you the gist of it. 

You can use rsync to copy the stuff over across the network using SSH. I recommend the following flags: `rsync -aHhP --numeric-ids --delete`. If the connection breaks you can run the same command again to continue and resume. You can run it again to update if things in the source have changed. It's very convenient.

This allows you to copy everything Mailcow needs by doing the following:
1. install docker-ce and docker-compose on the target machine, as described in the Mailcow guide
2. start and then stop docker on the target machine
3. run the following commands on the source machine (take care of adding the trailing slashes in the first path parameter as shown below!):
```
rsync -aHhP --numeric-ids --delete /opt/mailcow-dockerized/ root@some.other.machine.net:/opt/mailcow-dockerized
rsync -aHhP --numeric-ids --delete /var/lib/docker/volumes/ root@some.other.machine.net:/var/lib/docker/volumes
```
4. shut down Mailcow via `docker-compose down` and stop docker on the source machine
5. repeat step 3 with the same commands (this will be much quicker than the first time)
6. start docker on the target machine (don't run the rsync commands again after this, cause they will delete newly arrived mails on the target machine)
7. go into the `/opt/mailcow-dockerized` directory and run `docker-compose pull`
8. now run `docker-compose up -d` and everything should be fine
9. switch over the DNS settings

This guide assumes you're using Docker for nothing else but Mailcow. Please note that running these rsync commands will delete everything in the given target paths which might already exist. If you've installed other Docker things on the target machine, these rsync commands will delete those.

**Comment by DJIronic** [comment]
I know there was a problem with my installation once, so I know that the update script and so on is located in /root/mailcow-dockerized, but I admit that I am not experienced in docker, so I don't know, if the storage containers are somewhere else.

**Comment by DJIronic** [comment]
OK. Thank you for all the help @hachre , but I can't finish the last command.

`docker-compose up` -d will end on:

```
OK: 111 MiB in 85 packages
/bin/sh: /docker-entrypoint.sh: Text file busy
ERROR: Service 'solr-mailcow' failed to build: The command '/bin/sh -c apk --no-cache add su-exec curl tzdata   && chmod +x /docker-entrypoint.sh   && /docker-entrypoint.sh --bootstrap' returned a non-zero code: 2
root@MS20:/opt/mailcow-dockerized#
```

**Comment by andryyy** [comment]
You should pull the images with `docker-compose pull` before running up -d. :)

**Comment by DJIronic** [comment]
Oh I see, I missed the command somehow. Thanks :)

**Comment by DJIronic** [comment]
Great, it worked. But yes I must admit..I am tired of worse with linux than I thought. Port for postfix is taken (address already in use). 

I see exim4 listening there:
```
root@MS20:/opt/mailcow-dockerized# netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995'
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      755/exim4
tcp6       0      0 :::995                  :::*                    LISTEN      107329/docker-proxy
tcp6       0      0 :::110                  :::*                    LISTEN      107408/docker-proxy
tcp6       0      0 :::143                  :::*                    LISTEN      107359/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      109074/docker-proxy
tcp6       0      0 ::1:25                  :::*                    LISTEN      755/exim4
tcp6       0      0 :::443                  :::*                    LISTEN      109060/docker-proxy
tcp6       0      0 :::993                  :::*                    LISTEN      107345/docker-proxy
```
I know that it will not work, so I apt-get purged exim4 away, but the port is still occupied, so postfix does not start :/ Any idea what I am doing wrong?

**Comment by DJIronic** [comment]
lol, I forgot to disable the service. My fault. sorry guys!

**Comment by hachre** [comment]
You're welcome :)

**Comment by MAGICCC** [comment]
I added some migration guide to the docs:
https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_migration/

**Comment by hachre** [comment]
Thank you, @MAGICCC !

**Comment by DJIronic** [comment]
Awesome! Thank youuu!

**Comment by tacerus** [comment]
Thank you.

**Comment by wctsagoe** [comment]
For step 5. _repeat step 3 with the same commands (this will be much quicker than the first time)_...is this referring to source machine or target machine?

**Comment by MAGICCC** [comment]
```
3. Run the following commands on the source machine
```
