### ISSUE TITLE
Trying to setup relay for SMTP as my ISP has blocked outgoing mail

### ISSUE THREAD

**Issue by GiganteX** [mailcow/mailcow-dockerized#2380]
So I've received relay details from my ISP that I should use, an URI, a port and user/pw. But where to config that?

The documentation says "As of September 12th you can setup relayhosts as admin by using the mailcow UI. Edit a domain afterwards and assign a relayhost for it to use."

... which really doesn't help me at all. I can see no such option when editing the domain. Only the "relay domain" which is for backup?

Please advice... And yes, I'm a newbie trying out MailCow for the first time so it's surely something obvious that I have missed, but some quick googling didn't help me so I turn to you...

**Comment by hachre** [comment]
1. go to `Configuration` on the top bar of the admin screen and choose `Configuration & Details`
2. go to the `Routing` tab
3. in the `Sender-dependent transport` section (the one that comes first), enter the SMTP host, port, username and password and click the `Add` button
4. now go to `Configuration` on the top bar again and choose `Mail Setup`
5. go to the `Domains` tab
6. click the `Edit` button of the Domain you want to switch
7. choose your newly added SMTP in the `Sender-dependent transports` section
8. scroll down and click `Save changes`

Repeat 5-8 for every Domain you have.

Hope it helps!

**Comment by andryyy** [comment]
Or use a single relayhost as general transport instead of sender dependent.

**Comment by GiganteX** [comment]
Thank you very much for that detailed instructions! I found the place, will try it out!
I think it's a good idea if that text is also added to the documentation!

**Comment by GiganteX** [comment]
Well, it works now, but all outgoing emails are "From:" the user specified in the relay host settings, which was not the desired result. Maybe that's what "sender-dependent" means?
I want the From: field to be the actual address of the person sending it, I will have several people using the mailserver. What should I do? Is that the general transport you mentioned? How do I set it up? I haven't seen it in the UI...

**Comment by andryyy** [comment]
Because you are using GMail. You cannot relay from your domain with a GMail account. They rewrite your from address.

**Comment by GiganteX** [comment]
Hm you're right. Bad Google... I switched to using my local ISP's smtp-server. (It worked fine when using port 587 instead of 465), and it sent the emails using the correct From-address.
Thanks!!

**Comment by clairelim97** [comment]
hi may I know how you set up the Sender-dependent transport? I put my smtp host as in mail.domain.com:587 but it did not work. After these steps, I got the Error: too many hops (in reply to end of DATA command) @andryyy
