### ISSUE TITLE
Upgrade Bootstrap/ Bootswatch to 3.4.1

### ISSUE THREAD

**Issue by jay-to-the-dee** [mailcow/mailcow-dockerized#2381]
**Is your feature request related to a problem? Please describe.**
No. Just good software maintenance practice.

**Describe the solution you'd like**
We ideally use the 3.41 Bootswatch/ Bootstrap https://bootswatch.com/3/ Web Framework, as 3.3.7 is quite a few revisions behind the current 3.x maintenance release.

**Additional context**
I don't mind doing it myself and creating a PR, but don't want to unnecessarily interfere with your workflow or create unintended consequences in plug-in modules etc.! Please let me know if you want me to do this.

**Comment by andryyy** [comment]
Thanks. Will do it soon. I’d prefer to move to bs4 though. But one thing after the other.

**Comment by jay-to-the-dee** [comment]
Sure. It's quite different to 3 and requires quite a lot of changes in my experience. Whilst this should be just a direct drop in! :)

**Comment by andryyy** [comment]
Hehe, yes, we should also check some other libs. I will try to push some changes this evening.
