### ISSUE TITLE
Error while running update.sh

### ISSUE THREAD

**Issue by wtrdk** [mailcow/mailcow-dockerized#2382]
Hi,

When running update.sh I get this error:
```
Fetching new docker-compose version...
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```
Now I can't reach my portainer installation. Not sure if it's a coincident or if it's related.
Mailcow seems to work fine...

**Comment by andryyy** [comment]
Seems like your pip is broken. (heh.)

Try to reinstall pip or drop it completely and install docker-compose without pip.

**Comment by wtrdk** [comment]
Hmmm... Can't uninstall docker-compose because pip is broken :-(
Edit:
Fixed it:
```
sudo python -m pip uninstall pip && sudo apt install python-pip --reinstall
sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall
```
