### ISSUE TITLE
[Postfix] error: unsupported dictionary type: mysql

### ISSUE THREAD

**Issue by miclnl** [mailcow/mailcow-dockerized#2383]
**Describe the bug, try to make it reproducible**
After upgrading to commit ae51201 I received an error in the postfix container about mysql not loading (see below). I checked the container, and the mysql module was not loaded and the mysql.so file was missing from the lib folder. The postfix-mysql package was installed. Removing the package and re-installing it solved the problem.

**System information and quick debugging**
 | crit | fatal: too many errors - program terminated
 | err | error: unsupported dictionary type: mysql
 | warning | warning: unsupported dictionary type: mysql (/usr/lib/postfix/postfix-mysql.so: No such file or directory)

- Attaching the container and running `postconf -m` doesn't list mysql
- /usr/lib/postfix doesn't contain postfix-mysql.so
- postfix-mysql package was installed
- re-installing the postfix-mysql package fixed the problem

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?) **Alpine 3.10_alpha20190228**
 - Docker and Docker Compose versions **Docker version 18.09.1-ce, docker-compose version 1.23.2, build 1110ad0**
 - Output of `git diff origin/master`, any other changes to the code? **anonymized headers in postfix**

**Comment by andryyy** [comment]
But why would it be missing? The images are the same for all of us, as long as you don’t change them. :-/

Cannot find a reason for it.

**Comment by miclnl** [comment]
Hi Andre,

This is actually the 2nd time this has happened after an update recently. I didn't mention that in the report, but that was the reason I am reporting it. The only other thing running on the OS is a backup script. I'll check tomorrow if that's doing anything weird.

I didn't change the containers prior to solving the missing file, so I have no idea. 

"André Peters" <notifications@github.com> schreef op 2 maart 2019 00:51:38 CET:

**Comment by andryyy** [comment]
Ok, I'm sure something changes the container/the image itself. We all use the same base, so I cannot imagine why this file would be deleted after an update. It is not missing in the postfix-mailcow image.

**Comment by miclnl** [comment]
My backup script doesn't touch the postfix container either. 

It happens after every update, but manually bringing down & up the containers with docker-compose also fixes the missing files. I have no idea where to look for a possible cause, but as it appears to be something with my personal host I'll close the issue for now.
