### ISSUE TITLE
fts rescan "not recognized"

### ISSUE THREAD

**Issue by molaga** [mailcow/mailcow-dockerized#2384]
I've updated to the new mailcow version with solr, and followed the line that says to rescan -
`docker-compose exec dovecot-mailcow doveadm fts rescan -A`

When executing this, i get this error -
```bash
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Fatal: Unknown command 'fts', but plugin fts exists. Try to set mail_plugins=fts
```

Also tried to change the command to the hint i got, and no success as well -
`docker-compose exec dovecot-mailcow doveadm mail_plugin=fts rescan -A`

I think that it's related to the fact, that ATM when i receiving fresh new emails and in **SOGo UI**, they're being inserted below the old emails?

some info about my evnironment
```
docker-compose version 1.23.2, build 1110ad01
Docker version 17.12.0-ce, build c97c6d6

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by andryyy** [comment]
SKIP_SOLR seems to be y for you, that's wrong. Change it to n and run `docker-compose up -d`.

No, the other problem is not related.

**Comment by molaga** [comment]
@andryyy Thanks for the instant reply, works well. for others who will face it, I've run -
```
docker-compose down
SKIP_SOLR=n docker-compose up -d
docker-compose exec dovecot-mailcow doveadm fts rescan -A
```
