### ISSUE TITLE
SMTP ERROR: EHLO command failed: F

### ISSUE THREAD

**Issue by GiganteX** [mailcow/mailcow-dockerized#2386]
Hi!

Again I need some assistance. Trying to setup a relay for outgoing email. I have tried both my local ISP and smtp.googlemail.com, but I am running into some issue when testing:

No MX records for smtp.googlemail.com were found in DNS, skipping and using hostname as next-hop.
Connection: opening to smtp.googlemail.com:465, timeout=10, options=array (
    ↪ 'ssl' => 
    ↪ array (
    ↪ 'verify_peer' => false,
    ↪ 'verify_peer_name' => false,
    ↪ 'allow_self_signed' => true,
    ↪ ),
)
Connection: opened
SERVER -> CLIENT: 
CLIENT -> SERVER: EHLO mail.MYDOMAIN.com
SERVER -> CLIENT: F
    ↪ SMTP ERROR: EHLO command failed: F
    ↪ SMTP NOTICE: EOF caught while checking if connected
Connection: closed
    ↪ SMTP Error: Could not authenticate.
    ↪ SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Replaced the real domain name with MYDOMAIN as my boss is kind of secretive. I believe I have the DNS records set up proper. mail.MYDOMAIN.com is a CNAME pointing to MYDOMAIN.com

What's with that "F" response?

**Comment by andryyy** [comment]
It tries STARTTLS over port 465. Or tried. Should work now.

**Comment by GiganteX** [comment]
Hot damn, you made a fix for me? That's awesome! I will then try the update procedure! :)
Thanks a lot!!

**Comment by GiganteX** [comment]
I can confirm that it worked. Successful to and from communication during test of the google relay host.
But when sending an email from my mailcow account to my gmail account, I got this in the queue manager:

 (connect to smtp.googlemail.com[2a00:1450:4010:c0f::10]:465: Network is unreachable)

Is this error related to the previous one? smtp.googlemail.com should definitely be reachable....

**Comment by GiganteX** [comment]
Well, whaddaya know. I've been reading and trying things. I tried changing from port 465 to 587 and suddenly it just worked! The emails got delivered. But 465 should work, I'm using it to send email from my local Thunderbird client. So it really should work from mailcow as well.

**Comment by andryyy** [comment]
Your IPv6 connection seems broken. Don’t use digitalocean for mail (just a guess).

**Comment by GiganteX** [comment]
I'm not using digitalocean. Don't know much about ipv6 I'm afraid, wouldn't know where to start troubleshooting that. But I haven't had any other issues.... and I can send mail through port 465 with my local windows client, just not through mailcow...

**Comment by andryyy** [comment]
That’s not related. Your setup cannot connect to IPv6 addresses. It will try v6 first and fall back to v4. Mails will be sent then. 

You connecting to port 465 is not related.
