### ISSUE TITLE
Modify dockerapi to support Kubernetes

### ISSUE THREAD

**Issue by thecabinet** [mailcow/mailcow-dockerized#2387]
**Is your feature request related to a problem? Please describe.**
I would like to run mailcow on Kubernetes.  Currently this is not possible as _dockerapi_ is just exposing the Docker socket over HTTPS, and that cannot work "natively" under Kubernetes.  You can workaround as was done in #189, but I would like to do it properly.

**Describe the solution you'd like**
I would make the changes in three phases:

1. Rework the _dockerapi_ image to implement an API that is more functional, and not literally the Docker API.  For example, to reload the nginx config, instead of calling _https://<span></span>dockerapi/containers/json_ and then searching the response looking for the container named nginx to find the container's id to call the API again to exec _nginx reload_ command in the container, just call _https://<span></span>dockerapi/nginx/reload_

1. Rename the _dockerapi_ container to _orchestratorapi_ and update all the calls.

1. Add a new _kubernetesapi_  image that implements the API.  Maybe create a Helm chart, but I've never done that before, so probably just an example yaml spec for launching everything.

**Additional context**
#2342 is already working to convert _dockerapi_ to Python 3, so I wouldn't want to do anything until that is merged.

There is some discussion in that issue where @christianbur offered to simplify the API and [you said, "I didn't [simplify the api] to be more flexible..."](https://github.com/mailcow/mailcow-dockerized/pull/2342#issuecomment-467346074), so would you be receptive to such changes?

**Comment by andryyy** [comment]
There is more to do than changing dockerapi-mailcow. It would also not magically scale. There would be zero benefits over what we have now.
To make it scale, you'd need to change much more and also drop a lot of features. But there is another open/closed (?) issue about that.

**Comment by ntimo** [comment]
@andryyy do you mean https://github.com/mailcow/mailcow-dockerized/issues/241 ?

**Comment by andryyy** [comment]
Hm, no, there was another issue. :)

**Comment by thecabinet** [comment]
I’m not expecting a switch to k8s to make mailcow support 10k users.  I would like it to work on k8s because I run everything at home on k8s and not directly on Docker, and it looked to me like k8s support could be added without adversely impacting the project.

You are correct that there is not much benefit to current mailcow users and developers, although  the changes to the API would consolidate all Docker-related logic in one place, which might make future development easier.

If you hate this idea and it’ll happen over your dead body, it’s your project, and I’m happy not to waste my time.  If you’re willing to let me send you a PR and you’ll consider it, that’s all I can ask for.

I’d like to send you a PR with the API changes.  All I can ask is that you’ll consider it.

This is not my project, so if you hate the idea of changing the Docker API, that’s fine with me.

**Comment by NULLx76** [comment]
What's the status on this? Would like it to work on k8s for the same reason as @thecabinet .

**Comment by andryyy** [comment]
Not interested.

**Comment by LucaDev** [comment]
@andryyy have you given this any more thought? Kubernetes is becoming more and more popular - even for small companies or individuals. I'd suggest to slowly move away from using docker specifics and using things like tcp sockets instead of unix sockets. (is this even a thing anymore? Havent looked at the internals for quite a while)

This would allow us to slowly add support for kubernetes without breaking existing stuff

**Comment by andryyy** [comment]
Kubernetes is not an alternative to Docker. Don't think about it this way. It's a fatal misunderstanding I read so often...

**Comment by LucaDev** [comment]
That's not what I was trying to say. Of course Kubernetes is not Docker and not a Docker alternative per se. What I mean is to replace the Docker specific parts with generic ones, which allows support for running in clusters. Also, it would probably allow Mailcow to support other container runtimes. I understand the approach that Docker is most prioritized as the main runtime. But for me, that doesn't preclude supporting others as well. Especially in the long run it would probably give Mailcow a lot of added value. For example, scaling doesn't have to be supported from the beginning. In fact, it would be enough just to be able to run it (n=1).

**Comment by gerwim** [comment]
+1

I'm currently investigating options to switch from Exchange to a mailserver which is able to operate within k8s. I don't need scaling either, I just want to run it and have k8s' self healing capabilities.

**Comment by LucaDev** [comment]
The community could even do most of the work I guess.
We would just need to start changing the technical design of mailcow a bit (which should not have any major negative sideeffects) - like by using tcp sockets instead of unix sockets for mailcow internal communication.

**Comment by gimlichael** [comment]
> Kubernetes is not an alternative to Docker. Don't think about it this way. It's a fatal misunderstanding I read so often...

But it is an excellent alternative to Docker compose 😉

**Comment by andryyy** [comment]
But the k8s environment does not magically appear. :)

I will work on it later... Let's run through some prerequisites first.

**Comment by LucaDev** [comment]
What's the plan? Do you already know what needs to be changed?
Let me know if you can use some help.

**Comment by andryyy** [comment]
I will let you know. :) I need to get some other things done first.

**Comment by Berndinox** [comment]
... just to say, k8s installation is easier then docker nowaday.
```
curl -sfL https://get.k3s.io | sh -
# Check for Ready node,
takes maybe 30 seconds
k3s kubectl get node
```
Source: https://k3s.io/

**Comment by andryyy** [comment]
Maintaining a multi node cluster over multiple locations with different latencies and independent storages etc. is by far more complex. If you oversee all of these parameters you should not be running a cluster. No offense.

**Comment by Berndinox** [comment]
I was talking about a single node cluster. There is no "latency".
We just wanted to let you know, that some guys prefer to use k8s (kubectl) over docker commands, even on a single host.
And it would be awesome to run mailcow on top of it.

Regarding K8s, may i can help.... let me know. BR

**Comment by ghost** [comment]
Following all the discussions about kubernetes and docker was quite exhausting.
Nice to see that there is some movement in the right direction (cooperating to become better).
