### ISSUE TITLE
Queue Manager

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2389]
Hallo,

ich stelle meine Fragen mal auf deutsch, weil ich es in englisch bestimmt nicht sauber hinbekomme xD

Wenn Nachrichten im Queue Manager sind (Durch z.B. Greylisting beim Empfänger)...
1. Wie lange bleiben die dort gespeichert?
2. Versucht Mailcow es in bestimmten Abständen automatisch erneut, die Mail zu verschicken oder muss man es manuell über "deliver" anstoßen?

Was ist der Unterschied zwischen "Flush Queue" und beim "Aktionen-Feld (drop-down) "Entfernen"?

Danke :)

**Comment by evilstiefel** [comment]
Durch beispielsweise greylisting noch zu versendende Nachrichten werden automatisch erneut verschickt, da musst du nichts machen. Das gleiche gilt für alle anderen "temporären" Gründe, weshalb E-Mails noch nicht verschickt wurden.

Flush queue: erneut (sofort!) probieren, die E-Mails zu versenden
Entfernen: alle noch nicht versendeten E-Mails aus dem Queue löschen (die werden dann auch nicht mehr versendet).

Gerade mal in die Konfiguration geschaut: bei Mailcow verbleiben mails standardmäßig bis zu einem Tag im Queue, bevor aufgegeben und die E-Mail verworfen wird.

Das Setting dafür ist `maximal_queue_lifetime`.

**Comment by tobias992** [comment]
Danke für die schnelle Antwort.

Ich dachte "Flush Queue" löscht die mails auch aus dem System. Ist also die gleiche Funktion wie "deliver" im drop-down Feld...

**Comment by evilstiefel** [comment]
Fast - die Aktionen sind pro Mail auswählbar, `flush queue` operiert auf allen Einträgen.

**Comment by tobias992** [comment]
So schnell kann man einfache Dinge missverstehen - danke :)
