### ISSUE TITLE
Can't add other domains with custom web-content anymore?

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#239]
I am a bit confused by this .. on an older version of mailcow-dockerized I have added another nginx config file called `subdoimain.mailcow-domain.conf` in `data/conf/nginx/`, to add some custom web content. it worked fine and all i had to do was
remove the `include /etc/nginx/conf.d/server_name.active;` and 
replaced it with `server_name subdomain.mailcow-domain.com;`
created a directory for the webcontent `data/web/subdomain.mailcow-domain.com/`
and added the root `/web/subdomain.mailcow-domain.com` in my nginx config file

same procedure does not work anymore, with a clean install. tried now several times - am i missing something? O_o

every time i go to subdomain.mailcow-domain.com i see the mailcow UI pop up.

when i go into the nginx container, i see `subdomain.mailcow-domain.conf`in /etc/nginx/conf.d`, so I wonder why nginx does not apply the configuration?

did anything change?

my nginx config for the subdomain is as follows:
```
server {
    listen 80;
    server_name subdomain.mailcow-domain.com;
    return 301 https://$host$request_uri;
}

server {
  include /etc/nginx/conf.d/listen_ssl.active;
  include /etc/nginx/mime.types;
  charset utf-8;
  override_charset on;
  ssl on;
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA';
  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains";
  ssl_ecdh_curve secp384r1;
  index index.html index.php;
  server_name subdomain.mailcow-domain.com;
  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  root /web/subdomain.mailcow-domain.com;

  location ^~ /.well-known/acme-challenge/ {
	  allow all;
    default_type "text/plain";
  }

  # If behind reverse proxy, forwards the correct IP
  set_real_ip_from 172.22.1.1;
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9000;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param PHP_VALUE "max_execution_time = 1200
                             max_input_time = 1200
                             memory_limit = 64M";
    fastcgi_read_timeout 1200;
  }
}
```

(i know the certificate will not be valid for this domain, but it should work fine with the warning - the next step for me would have been to use certbot to get a certificate for that domain..that's how i did it in the past, without issues)

**Comment by Braintelligence** [comment]
This doesn't solve your issue, but after trying around a lot and weighing some options I decided to run a VM exclusively for mailcow-dockerized only and not use anything else on there.

This IMO is more secure, has less backdraws when backing up the whole VM as backup strategy and you can follow the documentation 1:1 for install and configuration and you can scale your VM as your mail demand rises or falls. Also you can move the VM to another server without moving everything else and/or create a failover VM.

I think an exclusive VM is also justified for something as important as mail.

**Comment by mkuron** [comment]
In a dockerized world, you don't need to modify mailcow's web server config. Just set up your custom web site in another docker container and put a reverse proxy in front of both sites (either in - you may have guessed it - one more docker container, or installed directly on the host).

**Comment by Braintelligence** [comment]
If you want to follow @mkuron suggestion I recommend using nginx-proxy and letsencrypt-nginx-proxy-companion for this endeavor.
Though I've heard of some issues trying to use all mailbox services behind a reverse proxy. (See tickets about this in this repo.)

**Comment by mkuron** [comment]
Reverse proxying Mailcow finally works as documented since last night.

**Comment by Braintelligence** [comment]
What is your recommended way of doing this via docker?

**Comment by chaosbunker** [comment]
I've been experimenting with this actually since I encountered my issue, managed to run gogs dockerized, with mailcow dockerized and SeafilePro dockerized with nginx as a reverse proxy on the host. But I prefer doing it with a nginx rp in a container, but it surpasses my brain capacities right now 😩 and had zero success with it. I would be super grateful for some ideas of a setup on how to achieve that
