### ISSUE TITLE
Installation & update on CoreOS

### ISSUE THREAD

**Issue by GiganteX** [mailcow/mailcow-dockerized#2391]
I am running mailcow on CoreOS and I had some troubles with the installation & update:

docker-compose would not install with the command:
curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose

not allowed to write there: "-bash: /usr/local/bin/docker-compose: Read-only file system"

I think it's supposed to go into /opt/bin on CoreOS, as detailed here:

https://www.vultr.com/docs/installing-docker-compose-on-coreos

I figured that out too late so I put it in my /home/core/ folder but that meant I had to modify the install & update scripts to get it to use it properly. I tried putting it in the PATH with the EXPORT command, but that didn't help because the script still tried to find docker-compose in /usr/local/bin so I had to modify the scripts.

Well, worth a mention in the documentation I think, and hopefully some magic scripting work by someone who knows what they're doing (ie not me)... ;)

**Comment by andryyy** [comment]
Hm, this should fix it, I think.

This does not fix the docs though. :-D
