### ISSUE TITLE
Empty sender addresses get accepted by Postfix

### ISSUE THREAD

**Issue by DomiStyle** [mailcow/mailcow-dockerized#2396]
**Describe the bug, try to make it reproducible**
I tried sending spoofed mails from a local SMTP server to my mailcow instance to see what happens. That mail obviously gets rejected with error code 554 5.7.1.

However, the delivery failure notification still gets sent to the actual address that was spoofed. Which probably is not supposed to happen since it means you can spam people with it.

To reproduce:

* Assign a non-existent FQDN to a local SMTP server (Mercury in XAMPP, or just plain Postfix in Linux)
  * e.g. mailcow-spoof.com
* Send a new mail from that SMTP server with following details:
  * From: "Test" <real-mail@mailcow-test.com>
  * To: "Test" <any-mail@mailcow-test.com>
  * Subject: Test
  * Body: Test

Where mailcow-test.com is a real mail server running mailcow.

The mail will bounce back but real-mail@mailcow-test.com will still receive the delivery failure notification from postmaster, even though the mail didn't originate from that account but from a foreign server.

**System information and quick debugging**
Should work on any mailcow instance with default configuration. Using the latest version (updated today).

Unfortunately I don't have a plain mail stack running to see if the issue is with the mailcow configuration or with Postfix itself.

**Comment by evilstiefel** [comment]
I cannot reproduce this - "fake"/spammy smtp-servers get immediately disconnected by postscreen with a 550 5.7.1 Service unavailable. No delivery notification is sent.

**Comment by DomiStyle** [comment]
> I cannot reproduce this - "fake"/spammy smtp-servers get immediately disconnected by postscreen with a 550 5.7.1 Service unavailable. No delivery notification is sent.

I just checked the logs, the delivery notification is sent from Mercury, not from Postfix. My bad.

However, not only does the delivery notifcation pass through, postscreen doesn't seem to care either.

\<mail server\> is the fake SMTP server
\<mail server hostname\> is the hostname of the fake SMTP server
example.org is the mail domain
mailcow-spoof.com is the FQDN of the fake SMTP server

Here' the spoof mail arriving:

```
postfix-mailcow_1    | Mar  8 12:16:14 mail postfix/postscreen[395]: CONNECT from [<mail server>]:22854 to [172.22.1.6]:25
postfix-mailcow_1    | Mar  8 12:16:17 mail postfix/postscreen[395]: PASS NEW [<mail server>]:22854
postfix-mailcow_1    | Mar  8 12:16:29 mail postfix/smtpd[417]: warning: hostname <mail server hostname> does not resolve to address <mail server>: Name or service not known
postfix-mailcow_1    | Mar  8 12:16:29 mail postfix/smtpd[417]: connect from unknown[<mail server>]
postfix-mailcow_1    | Mar  8 12:16:29 mail postfix/smtpd[417]: NOQUEUE: reject: RCPT from unknown[<mail server>]: 550 5.1.1 <test@example.org>: Recipient address rejected: User unknown in virtual mailbox table; from=<domi@example.org> to=<test@example.org> proto=ESMTP helo=<mailcow-spoof.com>
postfix-mailcow_1    | Mar  8 12:16:29 mail postfix/smtpd[417]: disconnect from unknown[<mail server>] ehlo=1 mail=1 rcpt=0/1 quit=1 commands=3/4
```

In this case I get User unknown because test@example.org doesn't actually exist. However, the same works with an existing address.

A short moment later Mercury delivers the delivery notification:

```
postfix-mailcow_1    | Mar  8 12:16:46 mail postfix/postscreen[395]: CONNECT from [<mail server>]:22809 to [172.22.1.6]:25
postfix-mailcow_1    | Mar  8 12:16:46 mail whitelist_forwardinghosts: Look up <mail server> on whitelist, result 200 DUNNO
postfix-mailcow_1    | Mar  8 12:16:46 mail postfix/postscreen[395]: PASS OLD [<mail server>]:22809
postfix-mailcow_1    | Mar  8 12:16:46 mail postfix/smtpd[417]: connect from <mail server hostname>[<mail server>]
postfix-mailcow_1    | Mar  8 12:16:47 mail postfix/smtpd[417]: A7840812D8: client=<mail server hostname>[<mail server>]
postfix-mailcow_1    | Mar  8 12:16:47 mail postfix/cleanup[428]: A7840812D8: message-id=<5D8803B9015A@localhost>
postfix-mailcow_1    | Mar  8 12:16:58 mail postfix/qmgr[345]: A7840812D8: from=<>, size=1927, nrcpt=1 (queue active)
postfix-mailcow_1    | Mar  8 12:16:58 mail postfix/smtpd[417]: disconnect from <mail server hostname>[<mail server>] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
postfix-mailcow_1    | Mar  8 12:16:58 mail postfix/lmtp[430]: A7840812D8: to=<domi@example.org>, relay=dovecot[fd4d:6169:6c63:6f77::7]:24, delay=11, delays=10/0.02/0.03/0.14, dsn=2.0.0, status=sent (250 2.0.0 <example.org> BfuSCSpPglwHAQAAPIZ5vg Saved)
postfix-mailcow_1    | Mar  8 12:16:58 mail postfix/qmgr[345]: A7840812D8: removed
```

The strange part is that an empty from address (<>) passes through without issues.

**Comment by andryyy** [comment]
Can you try the following? =>

Open `data/conf/postfix/master.cf` and change...

```
smtp       inet  n       -       n       -       1       postscreen
smtpd      pass  -       -       n       -       -       smtpd
  -o smtpd_helo_restrictions=permit_mynetworks,reject_non_fqdn_helo_hostname
  -o smtpd_sasl_auth_enable=no
  -o smtpd_sender_restrictions=permit_mynetworks,reject_unlisted_sender,reject_unknown_sender_domain
```
...to...
```
smtp       inet  n       -       n       -       1       postscreen
  -o postscreen_discard_ehlo_keywords=silent-discard,dsn
smtpd      pass  -       -       n       -       -       smtpd
  -o smtpd_helo_restrictions=permit_mynetworks,reject_non_fqdn_helo_hostname
  -o smtpd_sasl_auth_enable=no
  -o smtpd_sender_restrictions=permit_mynetworks,reject_unlisted_sender,reject_unknown_sender_domain
  -o smtpd_discard_ehlo_keywords=silent-discard,dsn
```

Restart postfix-mailcow and try again.

//edit: Sorry, updated once.

**Comment by DomiStyle** [comment]
```
index fcc99717..cedfaf89 100644
--- a/data/conf/postfix/master.cf
+++ b/data/conf/postfix/master.cf
@@ -1,8 +1,10 @@
 smtp       inet  n       -       n       -       1       postscreen
+  -o postscreen_discard_ehlo_keywords=silent-discard,dsn
 smtpd      pass  -       -       n       -       -       smtpd
   -o smtpd_helo_restrictions=permit_mynetworks,reject_non_fqdn_helo_hostname
   -o smtpd_sasl_auth_enable=no
   -o smtpd_sender_restrictions=permit_mynetworks,reject_unlisted_sender,reject_unknown_sender_domain
+  -o smtpd_discard_ehlo_keywords=silent-discard,dsn
 smtps    inet  n       -       n       -       -       smtpd
   -o smtpd_tls_wrappermode=yes
   -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
```

No change, empty mail address still passes through.

However, postscreen still has the IP cached. In case that would make a difference.

**Comment by andryyy** [comment]
There is not a good solution for this. If you are under attack, change the bounce service to "discard" and check the backscatter mail patterns, write header and body checks and wait until it is over. Also ban the senders IP(s).

**Comment by DomiStyle** [comment]
> There is not a good solution for this.

Is there really no way to discard all mails from an empty sender when they originate from foreign servers? Seems like an oversight.

I'm not under attack but I think this could be easily abused. You can even send a mail as ``PayPal <>`` or similar and it will be accepted.

**Comment by DomiStyle** [comment]
Another thing: Why is the MX record not being verified?

mailcow-spoof.com doesn't even exist and the mail is still accepted. Any way to change that?

edit: Just checked rspamd
I assume increasing the penalty for HFILTER_HELO_NORES_A_OR_MX should work.

**Comment by andryyy** [comment]
Some (actually many, and even bigger) websites/services send from subdomains without MX. 

You may also check RFC and Postfix docs why this is accepted. You are also talking about empty HEADER "From" fields. That's pretty easy to catch and I think Rspamd adds a symbol for this anyway...

**Comment by DomiStyle** [comment]
> Some (actually many, and even bigger) websites/services send from subdomains without MX.

You got an example I can test with? Looked through some rspamd entries from bigger newsletters but couldn't find one.

It seems like HFILTER_HELO_NORES_A_OR_MX and FROM_NO_DN is what I want.

I assume it's safe to increase the penalty for those? It's unlikely for a HELO not to resolve to either A or MX. It's also unlikely to not set any from address at all.

I can't think of a legitimate reason for either of these.

edit: FROM_NO_DN seems to only apply to the display name, empty addresses are not included. So not really safe to use that.

**Comment by andryyy** [comment]
I have seen a bunch of senders. Fiverr is one I remember.

As I said before: It happens, and it happens quite often. I don't care if you believe me, just set it to a higher score and see if you have ham mail being hit by that rule. :) If not, fine.

**Comment by DomiStyle** [comment]
> I don't care if you believe me

No worries, I believe you. :)

Just need some example data to test with.

**Comment by andryyy** [comment]
I searched but couldn't find examples. :(

**Comment by DomiStyle** [comment]
Did some more testing.

FROM_NO_DN occurs quite often since it's only the sender name, not address.

HFILTER_HELO_NORES_A_OR_MX only triggered with spam mails so far, so I'm keeping it for now. I'm probably locking out some badly configured mail servers with that but I don't mind.

In case the spoofed HELO uses an existing mail server instead of a made up one I also increased R_SPF_FAIL, DMARC_POLICY_REJECT and DMARC_POLICY_SOFTFAIL. Not sure about these yet but we will see.

I didn't find a way to block empty sender addresses but I'm living with that for now.

**Comment by andryyy** [comment]
Something like `Bla <>` you say? I can try to write a rule for that.

**Comment by DomiStyle** [comment]
> Bla <>

Yes, that would be perfect.

**Comment by Xenthys** [comment]
I know this issue is closed, but I also faced this problem.  
If you're reading this and in the same case, [this](http://postfix.1071664.n5.nabble.com/reject-empty-sender-address-for-authenticated-users-td83425.html) helped me.
