### ISSUE TITLE
Very High CPU on Postfix container

### ISSUE THREAD

**Issue by agottschling** [mailcow/mailcow-dockerized#2397]
I updated mailcow to 1.35 the other day, and this morning got an email that I had high (> 90%) CPU usage on my server. After logging in and looking at docker stats, the postfix container has very high cpu usage. Looking at the logs revealed this:

`
Mar  5 16:41:33 mail postfix/smtpd[510]: lost connection after STARTTLS from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[510]: disconnect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161] ehlo=1 starttls=0/1 commands=1/2
Mar  5 16:41:33 mail postfix/smtpd[510]: connect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[494]: connect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[494]: SSL_accept error from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]: -1
Mar  5 16:41:33 mail postfix/smtpd[494]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
Mar  5 16:41:33 mail postfix/smtpd[514]: SSL_accept error from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]: -1
Mar  5 16:41:33 mail postfix/smtpd[514]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
Mar  5 16:41:33 mail postfix/smtpd[514]: lost connection after STARTTLS from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[514]: disconnect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161] ehlo=1 starttls=0/1 commands=1/2
Mar  5 16:41:33 mail postfix/smtpd[514]: connect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[502]: SSL_accept error from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]: -1
Mar  5 16:41:33 mail postfix/smtpd[502]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
Mar  5 16:41:33 mail postfix/smtpd[502]: lost connection after STARTTLS from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[502]: disconnect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161] ehlo=1 starttls=0/1 commands=1/2
Mar  5 16:41:33 mail postfix/smtpd[502]: connect from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]
Mar  5 16:41:33 mail postfix/smtpd[505]: SSL_accept error from ec2-54-210-254-161.compute-1.amazonaws.com[54.210.254.161]: -1
Mar  5 16:41:33 mail postfix/smtpd[505]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
`
Any ideas? Thanks

**Comment by andryyy** [comment]
Report the IP that is flooding you and ban it in netfilter settings. :)

Any chance it is a service of your own, that accidentally got in a loop and spams you, because it cannot connect?

**Comment by agottschling** [comment]
It may be. I'll have to check with the developers of my email client. The weird thing is the `warning: TLS library problem: error:1417D102:SSL` error. What could that mean?

**Comment by andryyy** [comment]
Someone is connecting with an unsupported TLS protocol version to your cow.

**Comment by agottschling** [comment]
Gotcha. Thanks for the info.

**Comment by agottschling** [comment]
Gotcha. Thanks for the info.

**Comment by agottschling** [comment]
Now, I am using the Exchange connector. Could that be throwing an issue on my end with the client?

**Comment by andryyy** [comment]
The connection is coming from an AWS address. I doubt it. Or is this EXC stuff runnning on AWS? Then it’s quite possible. 

If you don’t know the IP, you should report and ban it. :)

Or .. ban it and check your EXC connector for functionality afterwards.

**Comment by DiEg0123** [comment]
I have the exact same problem at AWS. I'm using Newton mail client.

The IPs are coming from Newton mail client. I think it is trying to connect with unsupported TLS but the weird thing is that it works until I updated to latest cow this morning.

The weird thing is it works with other mail clients.

I also tried with port 25 and port 465 (SSL), but fail to work. Any solution quick fix for this please??

**Comment by andryyy** [comment]
This is not a matter of where the server is hosted.

This is a client connecting over and over again, coming from an AWS IP.

We changed mandatory protocols to only include TLSv1.2. Don’t know if that’s the problem here. But you can try and revert the changes found in main.cf.

You cannot switch to port 25 for authenticated clients. You can also not switch between 465 and 587 without modifications of the client config (one is STARTTLS and one is wrapped TLS).

**Comment by agottschling** [comment]
I may not have explained myself very well. 
I'm connecting to Mailcow USING exchange. My client (Newton Mail) speaks EAS to the server and works off of that standard. Also, this only started to happen when I updated to 1.35, but I can't remember what I was on before updating. 
EDIT: The thread just refreshed when I posted this, and I'm thinking that it's an issue with Newton not supporting a new enough TLS cipher suite. I'll shoot them a mail and anyone else having an issue with Newton should as well.

**Comment by andryyy** [comment]
But you posted Postfix logs with an AWS IP spamming it. What is this AWS IP now exactly? Do you know it?

ActiveSync does not use SMTP (directly).

**Comment by DiEg0123** [comment]
@andryyy Newton mail client (by Cloudmagic) uses its server in the middle to send emails because it adds email tracking code.

Newton mail client ----> Newton Server ----> Mailcow server

Newton Server is also hosted in AWS. That is why we are seeing AWS IP flooding to our Mailcow server due to TLS issue.

As @agottschling said, this is the issue with Newton Mail because they are not supporting TLSv1.2 yet for some reasons. Their support is slow and expect more from a paid mail client.

**Comment by andryyy** [comment]
Oh. Sounds strange. But they shouldn’t hammer a line when the connection fails.

And yes, TLSv1.2 should be supported. :/ 

Thanks for your information!

**Comment by DiEg0123** [comment]
No problem!

Hey thanks for awesome software @andryyy !
