### ISSUE TITLE
Problem with startTLS since update

### ISSUE THREAD

**Issue by nicolaspernoud** [mailcow/mailcow-dockerized#2398]
Hi,

Since last update, a mail send from the command line on the host system (ssmtp) fails.
The ssmtp conf is :
```bash
root=system@mydomain
mailhub=172.22.1.1:587

# Where will the mail seem to come from?
rewriteDomain=mydomain

# The full hostname
hostname=myhostname

# Are users allowed to set their own From: address?
# YES - Allow the user to specify their own From: address
# NO - Use the system generated From: address
FromLineOverride=YES
AuthUser=system@mydomain
AuthPass=*****
UseSTARTTLS=YES
```

The command line is :
```bash
echo "test" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "TEST" an.adress@email.com
```

The log is :
05/03/2019 à 18:51:48 | info | disconnect from unknown[172.22.1.1] ehlo=1 starttls=0/1 commands=1/2
-- | -- | --
05/03/2019 à 18:51:48 | info | lost connection after STARTTLS from unknown[172.22.1.1]
05/03/2019 à 18:51:48 | warning | warning:  TLS library problem: error:1417D102:SSL  routines:tls_process_client_hello:unsupported  protocol:../ssl/statem/statem_srvr.c:974:
05/03/2019 à 18:51:48 | info | SSL_accept error from unknown[172.22.1.1]: -1
05/03/2019 à 18:51:48 | info | connect from unknown[172.22.1.1]

Thanks,

**Comment by DiEg0123** [comment]
I have the same issue. I think it is related to this post as well.

https://github.com/mailcow/mailcow-dockerized/issues/2397

This error seems to be happening for only some email clients including the one I'm using.

**Comment by andryyy** [comment]
See my comment in this issue, please.

**Comment by andryyy** [comment]
My guess is, mandatory protocols and ciphers apply to the ports we ask for encryption.

So just change the lines back or switch to a client that supports TLSv1.2.

We can also reduce mandatory protocols to 1.0 for authenticated users. Hm.

**Comment by DiEg0123** [comment]
Thanks @andryyy 

Mailcow is awesome btw!

As @andryyy suggested, remove/reverting the mandatory TLSv1.2 works fine now. Until mail client is updated, this will be temporary fix.

For those who has the issue and wish to make changes, please check this commit

https://github.com/mailcow/mailcow-dockerized/commit/0375703198a77c66253c833fa8fc96bf2b834859#diff-dc3852510e4a52f06f0196219193c793

**Comment by nicolaspernoud** [comment]
Hi,
Thanks for your responses. Switching from ssmtp to **msmtp** does the trick !
Best regards, and thanks for all the hard work on mailcow...
