### ISSUE TITLE
Transport Maps; regex??

### ISSUE THREAD

**Issue by roswitina** [mailcow/mailcow-dockerized#2399]
Is it possible to use Regex to define the destination in the transport maps? Here I have an entry as target "*" This also forwards the local messages of the system, e.g. watchdog@invalid, null@localhost etc.. I only want to prevent such local redirects. How can I do that?

**Comment by andryyy** [comment]
I will probably push a fix to force-route localhost$ to local: in a few hours.

**Comment by andryyy** [comment]
Will push it tomorrow, there are too many changes I need to document.

**Comment by roswitina** [comment]
Seems to be working.  Thank you.

8.3.2019, 10:05:11 | info | 496757E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
-- | -- | --
8.3.2019, 10:04:55 | info | 3A2187E56E0:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:04:24 | info | 2BB497E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:04:14 | info | 1C2FA7E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:03:43 | info | 0DDAB7E56DE:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:03:28 | info | F22FD7E56DE:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:02:52 | info | E2B047E56DE:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:02:15 | info | D37047E56DE:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:01:51 | info | C47547E56DE:  to=<null@localhost>, relay=local, delay=0.02,  delays=0.01/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:01:21 | info | B02717E56DE:  to=<null@localhost>, relay=local, delay=0.04,  delays=0.03/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:01:07 | info | 9DD8D7E56DE:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:00:51 | info | 8DFCB7E56DE:  to=<null@localhost>, relay=local, delay=0.02,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 10:00:22 | info | 76A277E56DE:  to=<null@localhost>, relay=local, delay=0.04, delays=0.04/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 10:00:08 | info | 4E3D77E56DE:  to=<null@localhost>, relay=local, delay=0.06,  delays=0.05/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 09:59:36 | info | 30E047E56DE:  to=<null@localhost>, relay=local, delay=0.03, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 09:58:59 | info | 1D5677E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 09:58:32 | info | 0CA787E56E0:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 09:57:55 | info | EF02D7E56E0:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 09:57:16 | info | DCFD67E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 09:56:51 | info | C67F27E56E0:  to=<null@localhost>, relay=local, delay=0.03,  delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to file:  /dev/null)
8.3.2019, 09:56:14 | info | B502A7E56E0:  to=<null@localhost>, relay=local, delay=0.02, delays=0.02/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 09:55:46 | info | 9F3147E56E0:  to=<null@localhost>, relay=local, delay=0.06, delays=0.06/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)
8.3.2019, 09:55:26 | info | 7D2247E56E0:  to=<null@localhost>, relay=local, delay=0.03, delays=0.03/0/0/0,  dsn=2.0.0, status=sent (delivered to file: /dev/null)

Do these messages fit approx. every 20 seconds?

I hadn't noticed them before.

**Comment by irrweg** [comment]
I have the same issues. After the Update I get logs full of such " infos ".
Not sure, but maybe a issues with watchdog and SoGo?

![image(11)](https://user-images.githubusercontent.com/345180/54071833-91b87280-4272-11e9-90f3-0cf1133017d2.png)

![image(12)](https://user-images.githubusercontent.com/345180/54071835-93823600-4272-11e9-825a-d163c9ff7de8.png)

**Comment by andryyy** [comment]
The SOGo stuff has been there before. The Postfix stuff came with the localhost redirect to local: ... you could shutdown watchdog or live with it.

**Comment by irrweg** [comment]
Really? I didn't saw it before I updated the mailcow today. 
Lets see, if its not going to impact anything I let it on.

**Comment by andryyy** [comment]
No, it is fine. :) Just annoying. I will fix it soon.

**Comment by roswitina** [comment]
Is that still being done?
Basically no problem, only the LOG is filled to the brim.
