### ISSUE TITLE
Can send mail but cannot receive mail

### ISSUE THREAD

**Issue by gordanyang** [mailcow/mailcow-dockerized#24]
mailcow.conf
```
MAILCOW_HOSTNAME=mail.finogeeks.club
```
Jan 23 03:18:42 mail postfix/postscreen[110]: CONNECT from [220.181.15.61]:1201 to [172.22.1.6]:25
Jan 23 03:18:42 mail postfix/dnsblog[114]: addr 220.181.15.61 listed by domain hostkarma.junkemailfilter.com as 127.0.0.3
Jan 23 03:18:42 mail postfix/postscreen[110]: PASS OLD [220.181.15.61]:1201
Jan 23 03:18:42 mail postfix/smtpd[116]: connect from m15-61.126.com[220.181.15.61]
Jan 23 03:18:42 mail postfix/smtpd[116]: 8A05B52C: client=m15-61.126.com[220.181.15.61]
Jan 23 03:18:42 mail postfix/cleanup[107]: 8A05B52C: message-id=<6d1f587d.1177.159c9552c6d.Coremail.gordanyang@126.com>
Jan 23 03:18:46 mail postfix/qmgr[101]: 8A05B52C: from=<gordanyang@126.com>, size=2169, nrcpt=1 (queue active)
Jan 23 03:18:46 mail postfix/local[108]: 8A05B52C: to=<yangtao@mail.finogeeks.club>, relay=local, delay=4.4, delays=4.4/0/0/0, dsn=5.1.1, status=bounced (unknown user: "yangtao")
Jan 23 03:18:46 mail postfix/cleanup[107]: D797C52E: message-id=<20170123031846.D797C52E@mail.finogeeks.club>
Jan 23 03:18:46 mail postfix/bounce[109]: 8A05B52C: sender non-delivery notification: D797C52E
Jan 23 03:18:46 mail postfix/qmgr[101]: D797C52E: from=<>, size=4526, nrcpt=1 (queue active)
Jan 23 03:18:46 mail postfix/qmgr[101]: 8A05B52C: removed
Jan 23 03:18:46 mail postfix/smtpd[116]: disconnect from m15-61.126.com[220.181.15.61] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan 23 03:18:52 mail postfix/smtp[118]: Trusted TLS connection established to 126mx03.mxmail.netease.com[220.181.15.191]:25: TLSv1.2 with cipher AES256-GCM-SHA384 (256/256 bits)
Jan 23 03:18:52 mail postfix/smtp[118]: D797C52E: to=<gordanyang@126.com>, relay=126mx03.mxmail.netease.com[220.181.15.191]:25, delay=5.6, delays=0/0.02/5.2/0.37, dsn=2.0.0, status=sent (250 Mail OK queued as mx11,v8mowAAHexUadoVYpByGDA--.39512S3 1485141532)
Jan 23 03:18:52 mail postfix/qmgr[101]: D797C52E: removed

**Comment by andryyy** [comment]
Hi,
can you please use the just pushed main.cf? => https://github.com/andryyy/mailcow-dockerized/blob/master/data/conf/postfix/main.cf

**Comment by vivernet** [comment]
I have the same problem, what do not understand. Sending emails happens without problems, but on large problems. Moreover, rspamd no error is displayed.
But recently noticed that the letters reach in very rare cases, for example they go with gmail.com and yandex.ru and more is not from where you do not come
