### ISSUE TITLE
Mail log browser

### ISSUE THREAD

**Issue by SomeGeek** [mailcow/mailcow-dockerized#240]
Implement the ability to view the mail logs in mailcow.

A list of all sent / received mails, included with a quick overview of a transaction ID and status. For easy readability, include icons like a checkmark when a message has been received by the other server (like 250 OK). Maybe provide ways to filter them.

When clicking on a transaction ID, provide the advanced details. Other (generic) error messages should have their own overview.

**Comment by tehXor** [comment]
There's already a PR which shows the mail log and postfix-logwatch output (https://github.com/mailcow/mailcow-dockerized/pull/21). 
You could implement further filter and usability improvements on top of the postfix-logwatch output (and you would most certainly be welcomed to create a PR with such functionality ;-)) but judging on the complex and heterogene structure of a mail log and therefore also the postfix-logwatch output this is probably a somewhat bigger task and I'm not sure if it would be worth it. Maybe just some easy regex filter for both logs which only shows lines which match a certain pattern?

PS: The PR currently has conflicts but they should be easy to solve, maybe I find the time to update it at the weekend.
