### ISSUE TITLE
permission denied for several containers

### ISSUE THREAD

**Issue by sevsev9** [mailcow/mailcow-dockerized#2401]
**Describe the bug, try to make it reproducible**

While installing the following services failed to build:
```
ERROR: for mailcowdockerized_php-fpm-mailcow_1  cannot stop container: 32754ec959dc20957bc3e861daa8360626008fc1a25a42c51d1ed0bf5b8d65a6: Cannot kill container 32754ec959dc20957bc3e861daa8360626008fc1a25a42c51d1ed0bf5b8d65a6: unknown error after kill: runc did not terminate sucessfully: container_linux.go:387: signaling init process caused "permission denied"
: unknown

ERROR: for dockerapi-mailcow  cannot stop container: d87b945cbc13a77f5b15cd2389e4fa4f4ad51f7f2780787c43631909ec3d03ed: Cannot kill container d87b945cbc13a77f5b15cd2389e4fa4f4ad51f7f2780787c43631909ec3d03ed: unknown error after kill: runc did not terminate sucessfully: container_linux.go:387: signaling init process caused "permission denied"
: unknown

ERROR: for unbound-mailcow  cannot stop container: 2ce590458fff28354cfb0ec0e1f6db1585dd47a8448aabaa67531d04d75e05bf: Cannot kill container 2ce590458fff28354cfb0ec0e1f6db1585dd47a8448aabaa67531d04d75e05bf: unknown error after kill: runc did not terminate sucessfully: container_linux.go:387: signaling init process caused "permission denied"
: unknown

ERROR: for sogo-mailcow  cannot stop container: a8467d9bd41f92badb64c694a399ec6f0f338ef193d3ee97b9dd30dea098d0cd: Cannot kill container a8467d9bd41f92badb64c694a399ec6f0f338ef193d3ee97b9dd30dea098d0cd: unknown error after kill: runc did not terminate sucessfully: container_linux.go:387: signaling init process caused "permission denied"
: unknown

ERROR: for php-fpm-mailcow  cannot stop container: 32754ec959dc20957bc3e861daa8360626008fc1a25a42c51d1ed0bf5b8d65a6: Cannot kill container 32754ec959dc20957bc3e861daa8360626008fc1a25a42c51d1ed0bf5b8d65a6: unknown error after kill: runc did not terminate sucessfully: container_linux.go:387: signaling init process caused "permission denied"
: unknown
```

In short:
```
Recreating mailcowdockerized_dockerapi-mailcow_1 ... error
Recreating mailcowdockerized_unbound-mailcow_1   ... error
Recreating mailcowdockerized_watchdog-mailcow_1  ... done
Recreating mailcowdockerized_mysql-mailcow_1     ... done
Recreating mailcowdockerized_redis-mailcow_1     ... done
Recreating mailcowdockerized_sogo-mailcow_1      ... error
Recreating mailcowdockerized_memcached-mailcow_1 ... done
Creating mailcowdockerized_solr-mailcow_1        ... done
Recreating mailcowdockerized_clamd-mailcow_1     ... done
Recreating mailcowdockerized_postfix-mailcow_1   ... done
Recreating mailcowdockerized_php-fpm-mailcow_1   ... error
```

Measures taken:
Clean installed ubuntu and tried again
Tried to run services as root
tried to change volumes' directory permissions
tried to update to latest docker(-compose)
tried to downgrade to v1.18
watched other (related) issues
Googling around for simmilar encounters - result 0

**System information and quick debugging**
last 100 lines of each container:
[pastebin](https://pastebin.com/naMpAzmK)

Also:
I can provide the whole installation log (85.5 MB) if that would be useful.

Further information (where applicable):
Ubuntu 18.04.1 (LTS)
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01
VM Stats:
 - Cores: 4
 - RAM: 16GB
 - Running on: Windows Server 2016 DC Hyper-V

**Comment by hachre** [comment]
Did you use the `docker` package by Ubuntu instead of installing `docker-ce`? 
There errors in the logs look super strange. Maybe try rebooting the entire server.

**Comment by extremeshok** [comment]
Use my script on a fresh ubuntu install to correctly configure and optimised ubuntu with docker

https://github.com/extremeshok/xshok-docker

## Docker Optimization / Post Install Script for Ubuntu (xshok-ubuntu-docker-host.sh) *run once*
* Force APT to use IPv4
* Remove conflicting utilities
* Update and Install common system utilities
* Remove no longer required packages and purge old cached updates
* Detect if virtual machine and install guest agent (qemu/kvm, vmware, virtualbox)
* Detect cloud-init device and install cloud-init
* Disable portmapper / rpcbind (security)
* Disable SSH password logins (security) if Authorized_keys detected
* Disable local dns server, do not disable systemd-resolved as this breaks nameservers configured with netplan
* set-timezone UTC and enable timesyncd as nntp client
* Create an 8GB swapfile (configurable with SWAPFILE_SIZE)
* Bugfix: high swap usage with low memory usage
* Pretty MOTD BANNER (configurable with NO_MOTD_BANNER)
* Increase max user watches
* Increase max FD limit / ulimit
* Increase kernel max Key limit
* Set systemd ulimits
* Set ulimit for the shell user
* Enable unattended upgrades
* Install Docker-ce
* Install Docker-compose
* Enable TCP BBR congestion control, improves overall network throughput

```
wget https://raw.githubusercontent.com/extremeshok/xshok-docker/master/xshok-ubuntu-docker-host.sh -O xshok-ubuntu-docker-host.sh && chmod +x xshok-ubuntu-docker-host.sh && ./xshok-ubuntu-docker-host.sh
```
