### ISSUE TITLE
User with control over all mailboxes?

### ISSUE THREAD

**Issue by ciroiriarte** [mailcow/mailcow-dockerized#2402]
Is it possible to delegate mailbox control using the web UI?. The use case would be bulk multiaccount mail migration using IMAP, but would like to do it from the platform administration point of view, so asking for the user password is cumbersome & insecure.

In traditional installations with CyrusIMAP we just used a single "system" account that had access to the mailbox until migration end.

**Comment by andryyy** [comment]
Use Sync Jobs.

**Comment by mkuron** [comment]
To share a folder with another account, you can use IMAP ACLs. They can even be configured on the command line via `doveadm`. However, for your migration purpose, sync jobs are indeed better suited.

**Comment by ciroiriarte** [comment]
Hello!, my source are PST files (to be converted to MBOX), unluckily an IMAP source doesn't exist. Also, with Sync Jobs I still need the user's password.

**Comment by andryyy** [comment]
```
mailcow-node # cat data/conf/sogo/sieve.creds
n01gtdmjbppqstd0@mailcow.local:4eux6otbz4iqz9f9yzsstkmh

## Just an example:

mailcow-node # docker-compose exec dovecot-mailcow /bin/bash
dovecot-mailcow # apt-get update && apt-get install telnet
dovecot-mailcow # telnet 127.0.0.1 143
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
A1 LOGIN andre@develcow.de*n01gtdmjbppqstd0@mailcow.local 4eux6otbz4iqz9f9yzsstkmh
A1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk] Logged in
```
