### ISSUE TITLE
Shorten image names

### ISSUE THREAD

**Issue by svengo** [mailcow/mailcow-dockerized#2408]
**Is your feature request related to a problem? Please describe.**
The container names are really long because all names start with `mailcowdockerized_`. The names differ after the 18th character, the longest name consists of 37 characters. It is really hard if you need to type an image name manually.

I don't see any advantage in the naming scheme because containers are managed by docker-compose and don't need any prefix to be identified.

**Describe the solution you'd like**
The `mailcowdockerized_` prefix should be removed. 

**Additional context**

Effective image names used by `docker ps` or `docker-compose ps`:

    1234567890123456789012345678901234567
    mailcowdockerized_acme-mailcow_1
    mailcowdockerized_clamd-mailcow_1
    mailcowdockerized_dockerapi-mailcow_1
    mailcowdockerized_dovecot-mailcow_1
    mailcowdockerized_ipv6nat-mailcow_1
    mailcowdockerized_memcached-mailcow_1
    mailcowdockerized_mysql-mailcow_1
    mailcowdockerized_netfilter-mailcow_1
    mailcowdockerized_nginx-mailcow_1
    mailcowdockerized_php-fpm-mailcow_1
    mailcowdockerized_postfix-mailcow_1
    mailcowdockerized_redis-mailcow_1
    mailcowdockerized_rspamd-mailcow_1
    mailcowdockerized_sogo-mailcow_1
    mailcowdockerized_solr-mailcow_1
    mailcowdockerized_unbound-mailcow_1
    mailcowdockerized_watchdog-mailcow_1

Thank you!

**Comment by mkuron** [comment]
> The mailcowdockerized_ prefix should be removed.

This prefix is added by docker-compose. You can actually set it to something arbitrary by adding `COMPOSE_PROJECT_NAME=something` to your mailcow.conf. Be sure to run `docker-compose down` before you do that though.

**Comment by MAGICCC** [comment]
Or consider installing docker-compose command completion
https://docs.docker.com/compose/completion/

**Comment by svengo** [comment]
@mkuron: Okay, that's correct. I was irritated because I run mailcow from an `mailcow`-directory but changing `COMPOSE_PROJECT_NAME` works.
There is an `-mailcow` suffix in every Container name that isn't needed in my opinion.

@MAGICCC: command completion doesn't work with `sudo docker-compose ...` :-(

**Comment by mkuron** [comment]
The suffix is needed to identify container names in some scripts.
