### ISSUE TITLE
** Watchdog: sogo-mailcow hit the error rate limit

### ISSUE THREAD

**Issue by progbuchholz** [mailcow/mailcow-dockerized#2409]
Since one week i get this error (Watchdog: sogo-mailcow hit the error rate limit) every 3-4 Minutes

Logs:

> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.293 second response time |time=0.293230s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.008 second response time |time=0.008047s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.008 second response time |time=0.007993s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.008 second response time |time=0.007854s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.003 second response time |time=0.003262s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.012 second response time |time=0.011684s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.010 second response time |time=0.010145s;;;0.000000 size=2700B;;;0
> connect to address 172.22.1.248 and port 20000: Connection refused
> HTTP CRITICAL - Unable to open TCP socket
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.305 second response time |time=0.304999s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.031 second response time |time=0.031337s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.009 second response time |time=0.008678s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.004 second response time |time=0.004457s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.070 second response time |time=0.070271s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.004 second response time |time=0.003552s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.063 second response time |time=0.063429s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.003 second response time |time=0.002808s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.008 second response time |time=0.008287s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.007 second response time |time=0.007421s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.016 second response time |time=0.015634s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.003 second response time |time=0.003007s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.007 second response time |time=0.007459s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.010 second response time |time=0.010160s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.009 second response time |time=0.009232s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.003 second response time |time=0.003337s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.008 second response time |time=0.008437s;;;0.000000 size=2700B;;;0
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.082 second response time |time=0.082470s;;;0.000000 size=2700B;;;0
> HTTP CRITICAL - No data received from host
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.077 second response time |time=0.077156s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.010 second response time |time=0.010200s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.028 second response time |time=0.027722s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.010 second response time |time=0.009985s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 0.009 second response time |time=0.008676s;;;0.000000 size=2700B;;;0
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 7.003 second response time |time=7.002890s;;;0.000000 size=2700B;;;0
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> HTTP OK: HTTP/1.1 200 OK - 2700 bytes in 3.253 second response time |time=3.253475s;;;0.000000 size=2700B;;;0
> CRITICAL - Socket timeout
> CRITICAL - Socket timeout
> 

(IPv6 already disabled, no need to)

Can anyone help me? 

I will thank you so much 

Best wishes
Ben

**Comment by progbuchholz** [comment]
I already made a clean install of it (newest version)! Same! These errors appear when i sent the first Mail with "clean install"

**Comment by andryyy** [comment]
No logs and you deleted the issue template without reading it and adding any required info. :(

It doesn’t matter if it’s a clean install, when the node you install it on is not working correctly.

**Comment by progbuchholz** [comment]
Oh i'm sorry. My System Info: 5GB Ram; 64 Bit Debain 9; lastest updates

Advanced logs in Web interface for sogo:

> 

9.3.2019, 12:24:15 | notice | [11]: [WARN] <0x0x5644d3b03850[WOWatchDogChild]> pid 815 has been hanging in the same request for 4 minutes
-- | -- | --
9.3.2019, 12:24:14 | notice | [11]: [ERROR] <0x0x5644d3b15c80[WOWatchDog]> No child available to handle incoming request!
9.3.2019, 12:24:13 | notice | [3739]: <0x0x5644d4175300[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user premium@klassencloud.de in Ping...
9.3.2019, 12:24:12 | notice | [2347]: <0x0x5644d3e9dd10[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user temp2@klassencloud.de in Ping...
9.3.2019, 12:24:11 | notice | [4220]: <0x0x5644d3a3f040[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user sv-hts@klassencloud.de in Ping...
9.3.2019, 12:24:11 | notice | [11]: [WARN] <0x0x5644d3b03970[WOWatchDogChild]> pid 2347 has been hanging in the same request for 3 minutes
9.3.2019, 12:24:11 | notice | [3293]: <0x0x5644d3f56ed0[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user presse@klassencloud.de in Ping...
9.3.2019, 12:24:11 | notice | [367]: <0x0x5644d3fbe080[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user temp1@klassencloud.de in Ping...
9.3.2019, 12:24:10 | notice | [3841]: <0x0x5644d4119ad0[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user premium@klassencloud.de in Ping...
9.3.2019, 12:24:10 | notice | [367]: <0x0x5644d46e2ae0[NGImap4Client]> TLS started successfully.
9.3.2019, 12:24:10 | notice | [367]: 52.125.140.138 "POST /SOGo/Microsoft-Server-ActiveSync?User=temp1%40klassencloud.de&DeviceId=43AB42DFD8F46FD6&DeviceType=Outlook&Cmd=Ping HTTP/1.0" 200 13/248 316.272 - - 0
9.3.2019, 12:24:07 | notice | [11]: [WARN] <0x0x5644d3aece70[WOWatchDogChild]> pid 4215 has been hanging in the same request for 2 minutes
9.3.2019, 12:24:07 | notice | [3736]: <0x0x5644d38f57b0[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user protection@klassencloud.de in Ping...
9.3.2019, 12:24:03 | notice | [4394]: <0x0x5644d3a9c870[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user martinhellmich-of01@klassencloud.de in Ping...
9.3.2019, 12:24:02 | notice | [1910]: <0x0x5644d3894ab0[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user temp2@klassencloud.de in Ping...
9.3.2019, 12:24:01 | notice | [4318]: <0x0x5644d3f99e20[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user sv-hts@klassencloud.de in Ping...
9.3.2019, 12:24:01 | notice | [4318]: <0x0x5644d39f8b80[NGImap4Client]> TLS started successfully.
9.3.2019, 12:24:01 | notice | [815]: <0x0x5644d4085d30[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user finance@klassencloud.de in Ping...
9.3.2019, 12:24:01 | notice | [4318]: 95.223.34.112 "GET /SOGo/ HTTP/1.0" 200 8906/0 0.327 28994 69% 4M
9.3.2019, 12:24:01 | notice | [4318]: [ERROR] <0x0x5644d3ed8f40[WOHttpTransaction]> client disconnected during delivery of response for <WORequest[0x0x5644d3eee0a0]: method=GET uri=/SOGo/ app=SOGo rqKey=(null) rqPath=(null)> (len=8906): the socket was shutdown
9.3.2019, 12:24:00 | notice | [11]: [ERROR] <0x0x5644d3b15c80[WOWatchDog]> No child available to handle incoming request!
9.3.2019, 12:24:00 | notice | [4318]: <0x0x5644d3e77b20[SOGoWebAuthenticator]> tried wrong password for user 'giAE7Ko86MWKmcoDmtsa2Nymb4yRYfJbZr1O4fjAAqaNetmQIQKBf6wQxyFcn2usJ+DhnDozXt9f8hcVSUkjM24JryLEOPkPMNpYWLWvVMm+iHI8zV0/NoevWFWWoA3jIZHZ9P+tNIpR3YskpYucZTQiAtOVQbkQp2370U73SgyinOdShDISPMpGO5iFG3fuEJ1EPzj1EiuYFbd96g2AcA=='!
9.3.2019, 12:24:00 | notice | [4318]: <0x0x5644d3e77b20[SOGoWebAuthenticator]> Expired session received, redirecting to login page.
9.3.2019, 12:24:00 | notice | [4318]: 52.125.140.109 "POST /SOGo/Microsoft-Server-ActiveSync?User=sv-hts%40klassencloud.de&DeviceId=B25F5560CB995D0B&DeviceType=Outlook&Cmd=Ping HTTP/1.0" 200 13/248 316.407 - - 276K
9.3.2019, 12:23:57 | notice | [11]: [ERROR] <0x0x5644d3b15c80[WOWatchDog]> No child available to handle incoming request!
9.3.2019, 12:23:54 | notice | [11]: [WARN] <0x0x5644d3aecad0[WOWatchDogChild]> pid 3841 has been hanging in the same request for 2 minutes
9.3.2019, 12:23:54 | notice | [11]: [WARN] <0x0x5644d3aed150[WOWatchDogChild]> pid 367 has been hanging in the same request for 5 minutes
9.3.2019, 12:23:53 | notice | [4310]: <0x0x5644d3e97f80[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user presse@klassencloud.de in Ping...
9.3.2019, 12:23:51 | notice | [3868]: <0x0x5644d3f2f850[SOGoActiveSyncDispatcher]> Sleeping 45 seconds while detecting changes for user benbuchholz@klassencloud.de in Ping...
9.3.2019, 12:23:51 | notice | [11]: [WARN] <0x0x5644d3ae4650[WOWatchDogChild]> pid 3736 has been hanging in the same request for 2 minutes

**Comment by progbuchholz** [comment]
As it seems to me, Sogo needs more workers. I set the limit from 20 to 120. Now it works just fine. I'll wait again today. Every day, 2000-3000 emails are sent through the system. Is there a kind of list where you can see how many workers you would need. 

Many Thanks

**Comment by andryyy** [comment]
That's been the problem indeed.

No, you need to monitor the logs. :/ It depends on the active EAS devices.

**Comment by progbuchholz** [comment]
Ah interesting. That's good to know. Yes, the clients mostly use Active Sync. 
So a connection to an "email account" would be a "worker"? 

How can I enable logging? Are these logs not already saved in the web interface?

Oh, I'm glad that I can now export the data from my old installation.

Many Thanks

**Comment by andryyy** [comment]
A connection via EAS, yes.

You can change the Docker logging driver to syslog, use a facility like local1, write all stuff to a mailcow.log file and monitor this file for "no child available". :) That's pretty much it.

As you've seen, watchdog-mailcow also informs you.

**Comment by progbuchholz** [comment]
Thank you, for the effort. 
Yes, there are about 20 EAS clients logged in. I noticed where I registered my new phone. I shut down the phone for this reason, but the error has still been. 
Oh nooo now Watchdog sends me Dovecote error rate limit; (same issue?

**Comment by progbuchholz** [comment]
Now Postfix 

i think i will increase the Limit in every container

**Comment by progbuchholz** [comment]
Oops, my mistake my previous installation sent me these error messages. 
Without attachment right?
Excuse me

**Comment by andryyy** [comment]
Empty attachment _can_ be ok. But make sure your mailcows are up-to-date. I think I fixed something related to the empty attachment issue.

Oh, and yes, I recommend you use at least 30 EAS workers then.

**Comment by progbuchholz** [comment]
I think that it comes from the old installation, since also in the email no time is specified

**Comment by progbuchholz** [comment]
Thank you for your Support ??

___________________

Mit freundlichen Grüßen

Ben Buchholz

61440 Oberursel (Taunus)

Inhaber von Klassencloud – DE



eMail: benbuchholz@klassencloud.de

Tel.: +49 (0) 1525 5603650

Web: www.klassencloud.de<http://www.klassencloud.de>

Inhaber, CEO, Entwickler und Erfinder der Klassencloud


_____________________________



Hinweise zum E-Mail Verkehr


Haftung für Inhalte

Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte in dieser Email nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationenzu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.



Haftung für Links

Unser Angebot enthält Links zu externen Websites/Services Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten/Emails ist stets der jeweilige Anbieter oder Betreiber der Seiten/Emails verantwortlich. Die verlinkten Seiten/Emails wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten/Emails ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.



Urheberrecht

Die durch die Seitenbetreiber erstellten Inhalte und Werke in dieser Email unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichenZustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Email/Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte in dieser Email/Seite nicht vom Betreiber erstellt wurden, werden die UrheberrechteDritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.



Sonderrechte

Sofern spezifisch gekennzeichnet oder schriftlich eingereicht, können jegliche Sonderrechte eingeholt werden, welche jegliche Hinweise außer Kraft setzen können. Deshalb behalten wir als Diensteanbieter das Recht vor, nach Ihrer Legitimierung zu verifizierungszwecken anzufragen.



Datenschutzinformationen

Um Ihnen die bestmögliche Sicherheit zu bieten, verwenden unsere Server ausschließlich SSL & TSL Verschlüsselungen. Es ist jedoch nicht auszuschließen, dass auf dem Weg an Ihre Empfängeradresse Sicherheitslücken bestehen. Sobald der Cc Empfänger "protection@klassencloud.de" eingefügt wurde, wird der Versand der E-Mail verfolgt und stellt im Falle eines Richtlinienverstoßes einen Zeugen dar. Wird Ihnen als Anhang die Datei „*-protection.crt“ angehängt, somit wurde der Weg zu Ihrer Empfängeradresse zusätzlich verschlüsselt. Das System archiviert den E-Mail Verkehr für maximal 10 Jahre, zur Ihrer eigenen Sicherheit.



Letzte Änderung: 17.02.2019 um 14:44 Uhr

Datenschutzerklärung Online aufrufen

Impressum Online aufrufen

Kontakt aufnehmen

www.klassencloud.de<http://www.klassencloud.de>



Diese Email wurde ohne Grafiken versandt.


________________________________

**Comment by andryyy** [comment]
If we have a support contract, please use the official channel.

Nvm... why the hell did I post this here? It was not related to you. I don't even remember where it was supposed to be posted or mailed.
