### ISSUE TITLE
SASL AUTH relay problems for domain aliases

### ISSUE THREAD

**Issue by hank** [mailcow/mailcow-dockerized#2410]
I have configured mailcow using the following configuration:
Domains:
* domain1.com
** Sender-dependent transports: [mail.domain1.com]:587 (external postfix relay, uses user1@domain1.com as the SASL user)
* fundomain.com
** Sender-dependent transports: [mail.fundomain.com]:587 (external postfix relay, uses funuser@fundomain.com as the SASL user)

Various mailboxes exist under domain1.com and fundomain.com

Domain Aliases:
* domain2.com -> domain1.com, Active
Mail currently will arrive in domain1.com mailboxes when sent to that user at domain2.com. Great!

Sending mail from domain1.com works fine, authenticates from with configured relay. The AUTH PLAIN looks like so after base64 decoding:

\0user1@domain1.com\0user1password

This matches the spec and SASL works.

Now, if a recipient of said mail to domain2.com replies to an external email, it is sent to the relay with the following SASL PLAIN string (when base64 decoded):

\0user1@domain1.com\0user1password,funuser@fundomain.com:funuserpassword

Why is my PLAIN auth getting this appended to it for responses on the domain alias? How can I assign a domain alias a map for sender-dependent transports that works correctly? Thanks!!

dockerapi-mailcow (mailcow/dockerapi:1.26) 
unbound-mailcow (mailcow/unbound:1.5)   
rspamd-mailcow (mailcow/rspamd:1.34)     
watchdog-mailcow (mailcow/watchdog:1.34)  
solr-mailcow (mailcow/solr:1.0) 
redis-mailcow (redis:5-alpine)  
memcached-mailcow (memcached:alpine)   
netfilter-mailcow (mailcow/netfilter:1.22)
ipv6nat (robbertkl/ipv6nat)
sogo-mailcow (mailcow/sogo:1.51)  
dovecot-mailcow (mailcow/dovecot:1.60) 
nginx-mailcow (nginx:mainline-alpine)
clamd-mailcow (mailcow/clamd:1.21)  
php-fpm-mailcow (mailcow/phpfpm:1.34)
postfix-mailcow (mailcow/postfix:1.29)
mysql-mailcow (mariadb:10.2)  
acme-mailcow (mailcow/acme:1.47)

**Comment by andryyy** [comment]
Sounds fun. I will check it.

Nice, replicated the issue:
```
+-----------+
| auth_data |
+-----------+
| dsa:dsa   |
| asd:asd   |
+-----------+
```

I hopefully fixed it (tm). A close friend of "we need to add it to the docs". 😄 

Will push postfix/1.30 in a bit.

**Comment by hank** [comment]
Wow you're amazing. Thank you so much!

**Comment by andryyy** [comment]
Thank you for your report. :)

**Comment by hank** [comment]
Test 1 worked after updating; having another mail user verify, but I believe it's indeed fixed.
