### ISSUE TITLE
GMail Mailsync problem

### ISSUE THREAD

**Issue by haiopaiii** [mailcow/mailcow-dockerized#2411]
Hey, got a little GMail sync problem.
I want to move from GMail to mailcow in future.
I set up mailcow to my domain and created an Account for one of my email-adresses.
In the Sync tab, I created a sync job (see screenshot)
![syncjob](https://user-images.githubusercontent.com/48380888/54070398-d4248400-425f-11e9-8f7b-e16b1d779c6a.png)

The problem is now, that mailcow keeps on syncing until my mailcow mailbox is running out of space.
My GMail mailbox contains about 1.76GB of mails, mailcow mailbox got 5GB available.

Can anybody tell me why? Is it maybe a configuration issue?

**Comment by andryyy** [comment]
skipcrossduplicates should do it. :)

**Comment by hachre** [comment]
@haiopaiii If this fixed your issue, please let us know!

**Comment by haiopaiii** [comment]
works perfectly, thanks :)
