### ISSUE TITLE
Solr, Dovecot FTS partial word match searching

### ISSUE THREAD

**Issue by soulsymphonies** [mailcow/mailcow-dockerized#2412]
**Is your feature request related to a problem? Please describe.**
I'm not getting as much search results as required, only full words will be found, but not partials of a longer word, e.g. if I search for snow, I don't get snowball, even if I search for snowba, I don't get snowball from the fulltext engine of dovecot, no matter if I use SOGo or Rainloop to do an IMAP search

**Describe the solution you'd like**
I did do some research and it seems I found a possible way to do it, I'd welcome a way to activate partial word match keyword searching in Solr, as described in this article here:
https://hostedapachesolr.com/support/partial-word-match-solr-edgengramfilterfactory

**Additional context**
Unfortunately I have not found a way to reconfigure Solr, as it looks like it's all done in the entrypoint.sh script and I didn't want to mess around with the script, maybe you could offer some help, how I could activate partial word searching

Thank you ever so much

**Comment by andryyy** [comment]
I'm testing a fixed schema from dovecot/core with an EdgeNGramFilterFactory filter to catch words like "snowball" with at least 3 chars, e.g. "sno". NGramFilterFactory would probably oom-kill a Solr container very fast, as it matches "sno now owb wba bal all" etc.

**Comment by soulsymphonies** [comment]
Thank you for your response.

I, too, wouldn't use NGramFilterFactory, I'm not interested in blowing Solr, just to make search a little more convenient, for if we are honest, most of the time it is actually only about the first characters of a word.

Probably even an EdgeNGramFilterFactory of 4 letters would be sufficient.

**Comment by andryyy** [comment]
Looks good now, will try to push in a bit.

**Comment by andryyy** [comment]
Hmm, should be fixed. A rescan is enough, I switched the core names. It should auto-fix the index then.

**Comment by soulsymphonies** [comment]
Thank you, it actually works, but I had one mailbox with 3000+ elements, I had to do a reindex for this.

There is one thing to consider and I don't know yet why this is happening, if I now search for vitamin for example, I also get vitrine, vital, etc. even if I type the full word. Which means search,.returns matches of the first three characters even if I type more than three characters.

I'm not sure why this is but nonetheless search works a lot better now and has now become much more useful.

**Comment by soulsymphonies** [comment]
maybe it's the part in the query section that produces this somewhat unexpected behavior, as solr is doing further ngram analysis when the query is executed

```
<analyzer type="query">
  ......
  <filter class="solr.EdgeNGramFilterFactory" minGramSize="3" maxGramSize="20"/>
```
maybe it would be enough to use the solr.EdgeNGramFilterFactory in the index section

This part I got from the official documentation
https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.EdgeNGramFilterFactory

> Documentation at Edge N-Gram Filter.
> 
> This FilterFactory is very useful in matching prefix substrings (or suffix substrings if side="back") of particular terms in the index during query time. Edge n-gram analysis can be performed at either index or query time (or both), but typically it is more useful, as shown in this example, to generate the n-grams at index time with all of the n-grams indexed at the same position. At query time the query term can be matched directly without any n-gram analysis. Unlike wildcards, n-gram query terms can be used within quoted phrases.

**Comment by soulsymphonies** [comment]
I will try to test it

**Comment by soulsymphonies** [comment]
okay, I tested it with 
` <filter class="solr.EdgeNGramFilterFactory" minGramSize="3" maxGramSize="20"/>`
removed from the `query section`, but left in the` index section`,

It produces then the desired and expected outcome when a search is executed, it matches whatever part is typed with the index, but not partials of the search string :)

so vitamin returns only vitamin or vitamins, no longer vital, etc....

**Comment by andryyy** [comment]
You don't have to reindex for the query change, do you?

**Comment by soulsymphonies** [comment]
no, I didn't even have to rescan for the query change

**Comment by soulsymphonies** [comment]
by the way, with this change in the Solr config, searching for something in SOGo or any other webmailer, such as rainloop which I also use, is such a joy.

That's, because you now actually find almost in real time what you look for even if there are thousands of mails in your mailbox! :)

THUMBS UP, mailcow rocks! 👍

**Comment by andryyy** [comment]
Thanks for testing! Do you want to create a PR?
Am So., März 10, 2019 16:42 schrieb Robert Christian :by the way, with this change in the Solr config, searching for something in SOGo or any other webmailer, such as rainloop which I also use, is such a joy.
 That's, because you now actually find almost in real time what you look for even if there are thousands of mails in your mailbox! :)
 THUMBS UP, mailcow rocks! 👍

**Comment by soulsymphonies** [comment]
Thank you, I have created a PR
