### ISSUE TITLE
Mail Client - Failed To Connect

### ISSUE THREAD

**Issue by gino** [mailcow/mailcow-dockerized#2415]
Hi there,

I am trying to get my inbox working on my desktop and phone using Spark (an email client).
Unfortunately, it seems that it can't connect to the server. I have no idea why though. Everything should work. Sending and receiving emails in SOGo works fine as well. It might be because I have a `.dev` domain as 'host'. That requires valid SSL certificates everywhere. But I do have valid SSL certificates everywhere.

I hope that someone could help me. I could share more information to the DNS records and of the domain in a private message, in Discord, for example.

Thanks.

**Comment by gino** [comment]
Also: if I use [this](https://mxtoolbox.com/SuperTool.aspx) url to check with `smtp:<domain>`, I have the "Failed to connect" issues as well. I really don't get it.

If I use https://www.smtper.net/ to test my mail server, it gives me the following error: 
`The remote name could not be resolved: 'mail.<domain>.dev'`

**Comment by andryyy** [comment]
The remote name could not be resolved: 'mail.<domain>.dev'

Well, that's the problem?

Probably a not-fully propagated DNS.

**Comment by gino** [comment]
@andryyy 
Well, yeah I understand that as well. But that's the thing, the DNS records are there and are correct.

![](https://cdn-std.dprcdn.net/files/acc_723731/0GSLX1)

I do use CloudFlare but all the 'orange clouds' are turned off (so they're grey), so the IP's are correct and are not getting changed by CloudFlare.

**Comment by andryyy** [comment]
But the check said it couldn't resolve the name, how could we help? That's a DNS issue it compained about.

**Comment by gino** [comment]
Yeah I understand, I have no idea. I tried different ports already. Might be the issue.. no idea.

**Comment by andryyy** [comment]
You can send me the hostname via mail, but I don’t know when I’m back to check it. :(

**Comment by gino** [comment]
That’s fine, I’ll send it to your mail. Take your time, I appreciate your help.

To what mail address can I send it?

**Comment by hachre** [comment]
You can also contact me at hachre at gmail.com for having the DNS stuff checked if you'd like.

**Comment by gino** [comment]
@hachre Just sent a mail to you, thanks for your help.

**Comment by hachre** [comment]
I've checked everything and it's all set up correctly. I can also connect to your Postfix on port 25. 
It's also already propagated to Google's DNS, so I think the DNS you use is simply slow. 
You can switch your computer to using 8.8.8.8 and 1.1.1.1 for its DNS and you should then see the changes immediately.

**Comment by gino** [comment]
@hachre I could create a mailbox for you, to test it on. If I only enter the e-mail and password, and completely rely on autodiscover, it doesn''t work..

**Comment by hachre** [comment]
Spark connects to your mail server through their own server. They use their own DNS caching and it can take multiple days for it to work there.

**Comment by gino** [comment]
I just tried it with Windows Mail, same issue. It’s weird that the online checkers give errors as well.

**Comment by hachre** [comment]
I've tried MXToolBox, and it hasn't given me any errors, except for no MX record existing for your `mail.` host. (Which is how you've set it up, and shouldn't really be a problem, even though I usually put MX records on those too.)

Did you switch your PC to the DNS servers I recommended? Unless you do that, you'll be using your providers DNS, which will most likely also need at least a day to catch up to recent changes.

**Comment by gino** [comment]
I somehow managed to fix it. I have no idea why, but I was struggling with the ports and now it works fine over SSL. Unfortunately, I got a new issue now, whenever I enter incorrect credentials once or twice (didn't check after how many times) my whole IP got banned. Now I can't access my server via SSH and the Mailcow panel neither. 😞 

@andryyy

**Comment by gino** [comment]
Edit: just unbanned myself by restarting the Netfilter container. Still have to figure out how to force autodiscover to use port 465 instead of 587. Since that is the issue.

**Comment by hachre** [comment]
You can create a file `data/web/inc/vars.local.inc.php` and override certain values which can be taken from `vars.inc.php` through that. 

https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/vars.inc.php

But I'd wait for @andryyy's comment before overriding those settings, since it should not be required to do so.

**Comment by andryyy** [comment]
Autodiscover always promotes SMTPS and not submission.

![grafik](https://user-images.githubusercontent.com/2972950/54088601-00bfc500-4360-11e9-8809-77f0c8dde53a.png)

The marked port is 465. "tlsport" would be 587.

Auto**config** (Thunderbird etc.) promotes both services.

![grafik](https://user-images.githubusercontent.com/2972950/54088611-2947bf00-4360-11e9-9519-2e5382ce1319.png)

Why do you think that's the issue? How are you sure? :)

**Comment by gino** [comment]
Because when I do not use the autodiscover function in Spark and manually enter my server address and port 495, it works fine. So it must be a port issue. But it is hard to debug it since I keep getting banned, after one failed attempt already.

**Comment by hachre** [comment]
> But it is hard to debug it since I keep getting banned, after one failed attempt already.

Unban yourself, go to the Web UI (https://mail.example.com/admin#f2bparams) and set yourself up as whitelisted. 

Or `docker-compose stop netfilter-mailcow` while you're debugging.

**Comment by andryyy** [comment]
But you see we do not use that port in autodiscover, right? :/ No port, no wrong config.

What does Spark use? Autodiscover? Autoconfig? **What does it configure, when you let it auto-discover your settings?** Last question is very important.

We do not ban after a single failed auth attempt.

**Comment by gino** [comment]
Yeah I understand. I have no idea to be honest, the ban issue is fine, I could fix that later. But if I only enter my email and password into Spark (and rely on the autodiscover stuff) it doesn’t work. And when I change the settings and manually put the mailserver and ports, it works fine. I could create an inbox for you and you could try it.. I don’t get it.

**Comment by gino** [comment]
I think it works fine now! I did add a SRV record to override the standard SMTP port but I don’t think that fixed it, I’ll remove the record and try it again.

**Comment by hachre** [comment]
My theory is the eventual DNS propagation to Sparks' servers is what fixed it.
