### ISSUE TITLE
My IP matched rule id 2

### ISSUE THREAD

**Issue by androidseb25** [mailcow/mailcow-dockerized#2416]
Mailcow banned my IP after a try to log in with my e-mail client and i get for 30 min no response from my server. When i whitelist my IP it works everything.

10.3.2019, 11:50:13 | warn | 123.123.123.123 matched rule id 2
-- | -- | --
10.3.2019, 11:50:12 | crit | Banning 123.123.123.123/24
10.3.2019, 11:50:12 | warn | 123.123.123.123 matched rule id 2
10.3.2019, 11:50:06 | warn | 1 more attempts in the next 600 seconds until 123.123.123.123/24 is banned
10.3.2019, 11:50:06 | warn | 123.123.123.123 matched rule id 2
10.3.2019, 11:50:06 | warn | 2 more attempts in the next 600 seconds until 123.123.123.123/24 is banned
10.3.2019, 11:50:06 | warn | 123.123.123.123 matched rule id 2
10.3.2019, 11:50:00 | warn | 3 more attempts in the next 600 seconds until 123.123.123.123/24 is banned
10.3.2019, 11:50:00 | warn | 123.123.123.123 matched rule id 2
10.3.2019, 11:50:00 | warn | 4 more attempts in the next 600 seconds until 123.123.123.123/24 is banned

**Comment by andryyy** [comment]
RULES[2] = '-login: Disconnected \(auth failed, .+\): user=.*, method=.+, rip=([0-9a-f\.:]+),'

You should not login with wrong credentials then. :) I don't understand.

**Comment by androidseb25** [comment]
Yes i know that rule, but i installed mailcow new, i had on my email client the old login credentials saved and now i want change the settings, in this time i try to change, mailcow set my ip as banned.

**Comment by andryyy** [comment]
That's expected. It does not know that (how should it?). It will see failed attempts and count until it bans you. You need to whitelist your IP then until you fixed your client.  :)
