### ISSUE TITLE
Alias Funktionen

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2419]
Hallo,

ich habe mal eine Frage zu der Alias-Funktion im Adminbereich:

Das Anlegen Bereitet keine Probleme.
Der Alias info@testdomain.de leitet an die persönlichen Postfächer person1@testdomain.de und person2@testdomain.de weiter. Funktioniert auch alles soweit.

Was bedeuten allerdings die Optionen:
- Nachrichten sofort verwerfen (info@ ist ja eh nur ein Alias und besitzt kein eigenes Postfach - was wird also verworfen)
- Nachrichten als Spam lernen
- Nachrichten als Ham lernen

?

**Comment by tobias992** [comment]
PS:
Alternativ kann ich natürlich auch ein normales info@testdomain.de Postfach anlegen und über SOGo eine Weiterleitung einrichten...

**Comment by hachre** [comment]
Wenn du `Nachrichten sofort verwerfen` anmachst, werden alle Mails, die da hin gehen, direkt gelöscht und das Weiterleiten an deine 2 Ziele geht aus.

Wenn du eine der Spam Optionen anmachst, wird entsprechend jede Mail automatisch als Spam oder Nicht-Spam "gelernt". Das ist für deinen Einsatzzweck natürlich Unsinn.

**Comment by tobias992** [comment]
Danke für die schnelle Antwort.
Ich bin gerade blind und verstehe den "Sinn" dieser Funktion nicht. Ist nicht gerade dafür ein Alias da... warum sollte ich die Nachricht wieder verwerfen anstall sie weiterzuleiten...

**Comment by hachre** [comment]
In machen Situationen ist es sinnvoll, z.B. du hast dich mal irgendwo angemeldet mit einer speziellen Adresse wie z.B. `adobe@example.com`. Später wurde die Adresse geleakt, weil Adobe gehackt wurde und jetzt kommt da massenhaft Spam hin. Also kannst du ein Alias einrichten, das diese Mails direkt wegwirft und dennoch alles andere `@example.com` weiterhin empfangen.

**Comment by tobias992** [comment]
Danke...
