### ISSUE TITLE
rspamd cannot parse settings map: error while parsing

### ISSUE THREAD

**Issue by ElishaDev** [mailcow/mailcow-dockerized#2420]
Hey,

after the last mailcow update, the rspamd container is restarted every 2 minutes. In the logs I can find the following:

> rspamd-mailcow_1     | 2019-03-10 22:07:07 #12(controller) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:07 #16(normal) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:07 #9(fuzzy) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:07 #13(normal) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:09 #10(fuzzy) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:10 #14(normal) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:10 #15(normal) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2019-03-10 22:07:10 #11(rspamd_proxy) <88r87i>; lua; settings.lua:745: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'

Hope someone can help me :/

**Comment by andryyy** [comment]
Can you send me your settings map taken from the mailcow UI to info@servercow.de? The full "active settings map".

**Comment by lightweight** [comment]
I'm having the same problem after an update just now...  `lua; settings.lua:753: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'` 

Docker-ce on Ubuntu 18.04 with a 5.0.0 kernel...

**Comment by bodsch** [comment]
I have the same poblem after an update just now

```
rspamd-mailcow_1     | 2021-08-10 08:55:24 #48(normal) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:56:00 #47(controller) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:56:03 #48(normal) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:56:10 #47(controller) <71f319>; lua; arc.lua:668: signing failure: cannot make request to load DKIM selector for domain localhost: nil
rspamd-mailcow_1     | 2021-08-10 08:56:10 #47(controller) <71f319>; csession; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 3127 regexps total, 2385 regexps cached, 0B scanned using pcre, 102B scanned total
rspamd-mailcow_1     | 2021-08-10 08:56:53 #47(controller) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:56:54 #48(normal) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:57:17 #47(controller) <bdf54b>; lua; arc.lua:668: signing failure: cannot make request to load DKIM selector for domain localhost: nil
rspamd-mailcow_1     | 2021-08-10 08:57:17 #47(controller) <bdf54b>; csession; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 3127 regexps total, 2385 regexps cached, 0B scanned using pcre, 102B scanned total
rspamd-mailcow_1     | 2021-08-10 08:57:24 #47(controller) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'
rspamd-mailcow_1     | 2021-08-10 08:57:25 #48(normal) <dwzo9a>; lua; settings.lua:1056: cannot parse settings map: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '<'

```

**Comment by andryyy** [comment]
Any custom settings map entry?

**Comment by andryyy** [comment]
@feldsam 

```
# curl http://nginx:8081/settings.php
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function getEnvPort() in /web/inc/vars.inc.php:48
Stack trace:
#0 /dynmaps/vars.inc.php(2): require_once()
#1 /dynmaps/settings.php(8): require_once('/dynmaps/vars.i...')
#2 {main}
  thrown in <b>/web/inc/vars.inc.php</b> on line <b>48</b><br />

```
...

**Comment by andryyy** [comment]
Should be fixed @bodsch - thanks!

**Comment by feldsam** [comment]
this is all because you don't have a develop branch and everything is merged directly to master. So there is no space for testing changes.

**Comment by feldsam** [comment]
where is settings.php located in repo? looks like vars are loading before functions, so there is no prerequisites used

**Comment by bodsch** [comment]
the ist located here:
```
# find . -name settings.php 
./data/conf/rspamd/dynmaps/settings.php
```

**Comment by bodsch** [comment]
and .. the watchdog sends many, many mails to me ...
content like this:
```
Rspamd settings check failed, score returned: 15
Milter check succeeded
...
```

**Comment by andryyy** [comment]
Update please

**Comment by bodsch** [comment]
after insert a debug statement (LUA is not my prefered language) i found this in the logs:
```
2021-08-10 12:39:08 #51(main) <3acjr9>; lua; settings.lua:1049:  => <br />\x0A<b>Fatal error</b>:  Uncaught Error: Call to undefined function getEnvPort() in /web/inc/vars.inc.php:48\x0AStack trace:\x0A#0 /dynmaps/vars.inc.php(2): require_once()\x0A#1 /dynmaps/settings.php(8): require_once('/dynmaps/vars.i...')\x0A#2 {main}\x0A  thrown in <b>/web/inc/vars.inc.php</b> on line <b>48</b><br />\x0A
```

**Comment by andryyy** [comment]
I already told you it is fixed and asked you to update.

**Comment by bodsch** [comment]
> Update please
> […](#)
> Am 10.08.2021 um 11:47 schrieb Bo.Sch. ***@***.***>: ﻿ and .. the watchdog sends many, many mails to me ... content like this: Rspamd settings check failed, score returned: 15 Milter check succeeded ... 

Whatever you changed, it works! :)

**Comment by bodsch** [comment]
> I already told you it is fixed and asked you to update.

sorry for the overlap, i saw your entry only after sending it.
