### ISSUE TITLE
Aliases can not be disabled "allowed to send as"

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#2423]
When I have a mailbox and created several aliases with goto address to the mailbox address. Then I can not deselect these aliases in "Allowed to send as" in the mailbox configuration.
How can I solve this? Or is this a bug?
![Screenshot 2019-03-11 at 12 51 10](https://user-images.githubusercontent.com/5203309/54122477-6e6dfe80-43fd-11e9-8219-50c7bc3f4340.png)
The aliases are greyed out and can not be deselected.

**Comment by andryyy** [comment]
They are always allowed to send as an alias.

**Comment by hunter-nl** [comment]
How to prevent this?
I've several dozens of aliases assigned to a mailbox. In SOGo you get a very long pull down list when user wants to select different send address and it would be nice in this case to have only the ones which are enabled. But not all. Most of these aliases I have are just only incoming addresses and should not be usable by user in SOGo or other mail clients as sender address.

**Comment by andryyy** [comment]
You can't. We can add switch to show/hide them in SOGo, but I don't have much free time atm. :(

**Comment by mitchellurgero** [comment]
Does Mailcow / SOGo support using + tags on emails?

Example instead of an alias, the user can use the email "joe+facebook@example.com" would be delivered to joe@example.com's mailbox and would behave like an alias but will never show in an address list.

a la - https://en.wikipedia.org/wiki/Email_address#Sub-addressing

**Comment by hachre** [comment]
> Does Mailcow / SOGo support using + tags on emails?

Yes, it can be set up by logging in to the Mailcow UI with mailbox credentials

**Comment by mitchellurgero** [comment]
> Yes, it can be set up by logging in to the Mailcow UI with mailbox credentials

I am talking about sub-address tagging, not aliases.. Sub-addresses are not "setup" like aliases but are just added on to an email.

Are you saying there is a setting that would need to be enabled for sub-addressing to work?

**Comment by hachre** [comment]
> Are you saying there is a setting that would need to be enabled for sub-addressing to work?

It works by default, but it won't do anything special with those mails. They will arrive, though. Logging into the UI allows you to set up whether you want them in special folders or be marked as such through a subject change.

**Comment by mitchellurgero** [comment]
> Logging into the UI allows you to set up whether you want them in special folders or be marked as such through a subject change.

Ah I see - You meant logging into SOGo and setting up rules. I was over here thinking you mean log into the admin UI. 

Well, unless you can do this in both SOGo and Mailcow's UI. Which would be pretty nice.
