### ISSUE TITLE
Anonymization of headers doesn't work internally

### ISSUE THREAD

**Issue by fabianhick** [mailcow/mailcow-dockerized#2425]
As already written in issue #1776 the headers are not replaced in case the email has been sent internally.
(see https://github.com/mailcow/mailcow-dockerized/issues/1776#issuecomment-430133810).

How is it possible to mitigate that?

**Comment by fabianhick** [comment]
Hi,
this issue still persists.

**Comment by andryyy** [comment]
Need details and example in _this_ issue with a current mailcow.
