### ISSUE TITLE
mailcow.conf is world readable

### ISSUE THREAD

**Issue by leepfrog-ger** [mailcow/mailcow-dockerized#2429]
I notcied that the `mailcow.conf` file is world readable. 

As this contains the database user/passwords in cleartext it would allow to take over the whole mailcow instance.

Ideally `generate_config.sh` would set 640 oder 600 on the file after generating/updating it.

**Comment by andryyy** [comment]
Yes, will push a fix with the key file permission fix.

**Comment by andryyy** [comment]
Fixed in 5b8a983be2a302fda6a7b8f9b27fe0e8919e9353
