### ISSUE TITLE
SOGo groups

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#243]
Hi there!
Are SOGo groups supported in any way?
It looks like you need LDAP for this.

Would it be possible to incorporate a docker container for LDAP-functionality within mailbox-dockerized?

**Comment by ignitedPotato** [comment]
LDAP support would be great!

**Comment by andryyy** [comment]
LDAP will not be an option. We are completely relying on SQL. We would need to rewrite everything and then migrate all user data from SQL. 

As long as SOGo does not provide groups for SQL setups: no support for groups.

**Comment by Braintelligence** [comment]
How does it work for ressources, though?

**Comment by mkuron** [comment]
SOGo has an open ticket about SQL-based groups (https://sogo.nu/bugs/view.php?id=2325), but no progress so far.

**Comment by andryyy** [comment]
Would be nice to see inverse implementing it. :) @cgx @extrafu

**Comment by Braintelligence** [comment]
Yeah, I think it is a very needed option for groupware applications. It's strange how ressources work with what we've got but groups do not. I would have understood the other way round, though 😸 .

Please implement this, dear SOGo wizards!

**Comment by Braintelligence** [comment]
Just to clarify: Is this issue also the reason why this: https://sourceforge.net/p/outlookcaldavsynchronizer/wiki/Home/ doesn't synchronize contact groups?
It looks like I can create contact groups in contacts in SOGo, though...

**Comment by mkuron** [comment]
No, contact groups are something entirely different.

**Comment by Braintelligence** [comment]
@mkuron Any idea why groups created in Outlook do not synchronize to SOGo and also groups created in SOGo do not synchronize to Outlook with the above mentioned plugin?

EDIT: Actually it seems that this also doesn't work with the SOGo Connector in Thunderbird.

**Comment by mkuron** [comment]
Most likely cause: SOGo and the CalDAV synchronizer don't agree on what a group is. There are at least four ways how groups can be represented in the vCard standard:
1. A group is an entry with `KIND:group` and a `MEMBER` attribute for each member contact.
1. As above, but with `X-ADDRESSBOOKSERVER-KIND`/`X-ADDRESSBOOKSERVER-MEMBER`.
1. Groups themselves are not represented by an entry, but group membership is represented by adding to the contact a `CATEGORIES` attribute whose value is the group name.
1. A group is represented not as a `VCARD` entry but a `VLIST` entry with a `CARD` attribute for each member.

Variant 1 is the "new" way according to vCard 4 (RFC 6350). Variant 2 is a vendor-specific extension introduced by Apple when they designed CardDAV based on vCard 3 (RFC 2426). Variant 3 conforms to vCard 3 (RFC 2426), but using it for groups deviates from the original intention of the RFC where it was meant to be used for tags. Variant 4 seems like it's a proprietary SOGo solution, though it seems to conceptually be aimed at email distribution lists and not at groups.

This may be relevant for you: https://sourceforge.net/p/outlookcaldavsynchronizer/features/2/

**Comment by Braintelligence** [comment]
Thanks for clarifying :).

**Comment by Braintelligence** [comment]
Still nothing new here, right? =/
