### ISSUE TITLE
Unable to set task reminders in SOGo

### ISSUE THREAD

**Issue by leepfrog-ger** [mailcow/mailcow-dockerized#2430]
I am pretty certain that this is an issue in SOGo but I wanted to make sure that mailcow is not doing anything fancy here before creating an issue in the SOGo bugtracker.

Normally reminders can be set to tasks similar as with calendar items. It seems however that this is not possible in SOGo, there is simply no "Reminder" field when creating/editng tasks. 
When creating the task with an ActiveSync client with a reminder this is correctly synced and also shown in SOGo, but it just seems to be impossible to create/edit it in SOGo itself.

**Comment by andryyy** [comment]
Yes, can you open this @ SOGo? :)
