### ISSUE TITLE
php-fpm parse error

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2434]
Hello,
After my hoster switched my server's ip, my nginx won't start anymore, because there's something wrong with php-fpm.
I do not even know, wich file includes the mistake.

`parse error: Invalid numeric literal at line 1, column 10`

Can someone help me fixing this?

**Comment by andryyy** [comment]
Hi, can you mail me? I can check it.

**Comment by Agiger03** [comment]
> Hi, can you mail me? I can check it.
> […](#)
> Am 13.03.2019 um 20:33 schrieb Agiger03 ***@***.***>: Hello, After my hoster switched my server's ip, my nginx won't start anymore, because there's something wrong with php-fpm. I do not even know, wich file includes the mistake. parse error: Invalid numeric literal at line 1, column 10 Can someone help me fixing this? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ghost** [comment]
So what do you need to help me?
You're coming from germany, is that true? Could we write in german?

> Hi, can you mail me? I can check it.
> […](#)
> Am 13.03.2019 um 20:33 schrieb Agiger03 ***@***.***>: Hello, After my hoster switched my server's ip, my nginx won't start anymore, because there's something wrong with php-fpm. I do not even know, wich file includes the mistake. parse error: Invalid numeric literal at line 1, column 10 Can someone help me fixing this? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by andryyy** [comment]
Ja, schreib mir an info@servercow.de
