### ISSUE TITLE
SSL Cert of ADDITIONAL_SAN not working

### ISSUE THREAD

**Issue by 0xC1A551C** [mailcow/mailcow-dockerized#2435]
Having an issue. I've replaced the domains and IPs.

Main domain: mx.domain.com
Extra domain: mail.domain.com

The mail.main.com is not receiving an SSL cert for some reason. I just updated mailcow.

I have `ADDITIONAL_SAN=mail.domain.com` set in the mailcow.conf
I have also disabled IPv6 in the docker-composer.yml just in case. 

mail.domain.com has the correct IPv4 (same one as mx.domain.com) unsure what is going on.

```
acme-mailcow_1       | Wed Mar 13 23:26:15 EDT 2019 - Found AAAA record for autodiscover.domain.com: 2606:4700:30::6818:7537 - skipping A record check
acme-mailcow_1       | Wed Mar 13 23:26:15 EDT 2019 - Confirmed AAAA record 2606:4700:30::6818:7537, but HTTP validation failed
acme-mailcow_1       | Wed Mar 13 23:26:15 EDT 2019 - Found A record for mx.domain.com: 172.245.81.(retracted)
acme-mailcow_1       | Wed Mar 13 23:26:16 EDT 2019 - Confirmed A record 172.245.81.(retracted)
acme-mailcow_1       | Wed Mar 13 23:26:16 EDT 2019 - Found AAAA record for mail.domain.com: 2606:4700:30::6818:7437 - skipping A record check
acme-mailcow_1       | Wed Mar 13 23:26:16 EDT 2019 - Confirmed AAAA record 2606:4700:30::6818:7437, but HTTP validation failed
acme-mailcow_1       | Wed Mar 13 23:26:16 EDT 2019 - Found new SANs mx.domain.com
acme-mailcow_1       | Wed Mar 13 23:26:16 EDT 2019 - Creating backups in /var/lib
```

**Comment by 0xC1A551C** [comment]
It seems maybe something is up with cloudflare since it is running behind cloudflare, and it skips the IPv4 when it detects cloudflares IPv6.

**Comment by hachre** [comment]
Are these hostnames real or did you replace them? I'm getting totally different DNS results querying the IP for those hostnames than suggested in your logs.

**Comment by 0xC1A551C** [comment]
> 
> 
> Are these hostnames real or did you replace them? I'm getting totally different DNS results querying the IP for those hostnames than suggested in your logs.

I retracted the urls and replaced them with domain.com. The ipv6 is correct in the logs: 2606:4700:30::6818:7437 the IPv4 was changed for security. I have posted my cloudflare dns settings below - might not help very much.

![domains](https://user-images.githubusercontent.com/36227001/54390140-00287680-465f-11e9-9404-2086a27914df.png)

**Comment by 0xC1A551C** [comment]
I seem to be right with this one somehow. As you can see mx.domain.com is not protected by cloudflare, but mail.domain.com is protected by cloudflare even though mail.domain.com is just a sub domain for the webserver of mailcow.

Mailcow thinks the AAAA IPv6 IP that cloudflare has IS the IPv6 of the server, so it seems to skip checking the A record for the IPv4 which is very unfortunate. I got it working by disabled cloudflares protection on the mail subdomain even though I shouldn't have too.


It would be nice if you could disable IPv6 checking in the mailcow config or something as this also ruins the autodiscover feature since it thinks the autodiscover has an AAAA IPv6 as well.

**Comment by hachre** [comment]
I'm running a very similar setup. 

What you have as `mx.domain.com` is what I've set up as the `MAILCOW_HOSTNAME`, what you have as `mail.domain.com` is not set up at all in the config in my case. The `mx.domain.com` host is the only one that doesn't go through Cloudflare (just like in your setup), the others do. Creating the cert for the `mx.domain.com` works correctly, and the certs for the others aren't needed because they are handled by Cloudflare anyway. 

Autodiscover and Autoconfig work fine the way you've set them up, but Cloudflare needs to be set to the "Full" SSL mode instead of "Full (Strict)".
