### ISSUE TITLE
mailcow.farm :: the mailcow community forum

### ISSUE THREAD

**Issue by extremeshok** [mailcow/mailcow-dockerized#2436]
**https://mailcow.farm**

https://mailcow.farm/index.php?thread/1-welcome-to-the-mailcow-community-forum/#post1

I have set this up with the goal of advancing mailcow and to fulfill the wishes of the community. Actions speak louder than words.

https://github.com/mailcow/mailcow-dockerized/issues/2392

Why mailcow.farm ? Simple.... cows live on farms ;P

This entire site is not-for-profit. There will be no advertising, adverts, user tracking, etc. I personally can not stand it and I have enough resources to fund this.

A little about me: github.com/extremeshok
Forum experience: ran a 10 000+ member gaming forum for a long time.

As the site grows, I will allocate more resources, having a virtually unlimited capacity of dedicated servers, vm;s etc.

Site is hosted in Germany and is GDPR compliant, daily backups (encrypted), dns is anycast.

Server is setup on an optimized version of ubuntu lts running docker-compose, no control panels, no ftp, no email servers, no password logins.

Admin permissions will be given to andryyy (mailcow developer)

If requested all members of mailcow project (as per github) will be given moderator.

Forum software is a commercial (non-free/paid) version of wotlab, paid for by myself specifically for mailcow.farm.

I have attached a graphical representation of the topology of the docker-compose, most of the docker images used are on github.

![docker-vis-full](https://user-images.githubusercontent.com/5957328/54329665-465be680-461b-11e9-82b4-28f2b7b02fdc.png)

**Comment by extremeshok** [comment]
- [x] @andryyy
- [x] @hachre
- [x] @MAGICCC
- [x] @mkuron
- [x] @mritzmann
- [x] @ntimo
- [x] @PhoenixPeca
- [ ] @tkorves

Please can you register using the github connector and I will assign moderator/admin permissions to your accounts

- [x] @Braintelligence
- [x] @dekyfin

Please can you register would like assign you with moderator

**Comment by extremeshok** [comment]
DNS should have propogated,  https://dnsmap.io/#A/mailcow.farm

**Comment by Braintelligence** [comment]
Registered. I'd recommend setting the birthdate as optional input. Or is there a reason behind requiring it for registration?

**Comment by ntimo** [comment]
@extremeshok Thank you so much for creating this awesome forum :) I just created an account but my MailCow is not getting the activation email :(

**Comment by extremeshok** [comment]
@ntimo ive activted the account, ill manually activate accounts for the next 48hours. DNS has not fully propogated

@Braintelligence Birthdate, is to allow only 16year and older to register. I know there are legal issues with younger than 16. Please set it to epoch 01-01-1970 if its a problem, assuming your over 16

**Comment by extremeshok** [comment]
Please post your forum username here, and I will assign your permissions

**Comment by Braintelligence** [comment]
Should be identical

**Comment by PhoenixPeca** [comment]
Hi @extremeshok 

![image](https://user-images.githubusercontent.com/9730242/54341598-278a3e00-4675-11e9-90ff-4b1c555c5084.png)
Linking github to an existing account does not seem to work on me, so I created a new account using with github connector. Also, can't seem to find the option to delete the old account.

other than that everything look good! Good job by the way!

**Comment by apintocr** [comment]
Signed up!
Let me know if I can help (designer and web dev)

**Comment by apintocr** [comment]
@extremeshok , regarding the age, I'd just put a checkbox with something like: I confirm that I'm over 16 years old.

**Comment by hachre** [comment]
Thanks for creating this!

**Comment by andryyy** [comment]
Thanks! :) I created an account, too. Same name.

**Comment by MAGICCC** [comment]
Registered using GitHub auth and my nice is MAGIC there

**Comment by cklabautermann** [comment]
Thanks a lot @extremeshok - just one thing: the activation mail got moved to quarantine in my mailcow installation.

**Comment by mritzmann** [comment]
Maybe a bad IP reputation. Otherwise it looks good: https://www.mail-tester.com/test-hkp23

**Comment by cklabautermann** [comment]
Added a rspamd screenshot to the forum:
https://mailcow.farm/index.php?thread/2-we-need-your-input/&postID=27#post27

**Comment by extremeshok** [comment]
> Registered using GitHub auth and my nice is MAGIC there

added to mailcwow+moderators
@tkorves and @dekyfin please sign up , if your username differs, please let me know

**Comment by dekyfin** [comment]
I've signed up

**Comment by extremeshok** [comment]
Small heads up, server is currently offline to the public as Im redoing the configs to correctly optimise and load test the forum.

Will be back online later today and a little bit faster

**Comment by hachre** [comment]
Since that downtime the Github-based login no longer seems to be working. It shows me as not logged in, I click on Login, then select Github and then get a 404 page.

**Comment by extremeshok** [comment]
seems its a bit fragile when it comes to an optimising ;P

I will have everything perfect soon

**Comment by ntimo** [comment]
@extremeshok Is the forum still down? I am getting a `The page isn't redirecting properly` error when I try to access it.

**Comment by Braintelligence** [comment]
Maybe we should close this issue and instead point to the forum in the README?

**Comment by extremeshok** [comment]
please keep it open so long, busy working out some minor issues which could cause the site to afk

**Comment by extremeshok** [comment]
Finally finished the updates.

The most noticeable change is the new premium theme, besides the theme site has been heavily optimized. webpagetest.org = A A A A A

https://mailcow.farm/index.php?thread/23-new-style-and-more-speed/

**Comment by extremeshok** [comment]
Just a small heads up, all known forum errors have been resolved. Some users were experiencing constant error pop-ups due to a faulty notification plugin.

**Comment by pjssms** [comment]
the forum mailcow.farm is down again.

**Comment by extremeshok** [comment]
Hi, thanks its been going on/off randomly, but the admin still works.

Traced down to redis which needed vm.overcommit = 1
