### ISSUE TITLE
Roundcube database disapear ?

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#2437]
**Describe the bug, try to make it reproducible**
After the March upgrade I don't found the roundcube database. 

In config.inc I have this 
$config['db_dsnw'] = 'mysql://roundcube:@localhost/roundcubemail';

But I don't found the database.

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?) : Debian 9

 - Docker and Docker Compose versions : 18.09

Thanks

**Comment by ntimo** [comment]
Hello @guidtz You you maybe try using 
```
$config['db_dsnw'] = 'mysql://roundcube:@mysql/roundcubemail';
```
This should fix the issue, since the database is not running in phpfpm container but the mysql-mailcow container you have to use mysql as the host :)

**Comment by guidtz** [comment]
Ok but I don't understand why there is no database roundcubemail in volume :+1: 
```
ls /var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data/
aria_log.00000001  ib_buffer_pool  ib_logfile0  ibtmp1   multi-master.info  mysql_upgrade_info  tc.log
aria_log_control   ibdata1         ib_logfile1  mailcow  mysql              performance_schema
```

In facts users in roundcube have contacts adressbook and all adressbook is now empty of email adresses of contacts.

**Comment by andryyy** [comment]
The RC data is stored in the "mailcow" db. :)

Can you check this? =>
https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

Perhaps something messed with the config.

I can check it if you are now missing important elements. I am back in about 3 hours.

**Comment by guidtz** [comment]
In mailcow database ? In which tables ?

Before thursday all works with contacts in roundcube. So after last update thursday 12, contacts are empty in roundcube.

**Comment by guidtz** [comment]
Do you have the names of tables where roundcube contacts are store ? I want to see if informations are in database or are loosed and I have to restore old database backup.
Thanks

**Comment by andryyy** [comment]
I was actually waiting for you to contact me. I am busy the next days and cannot check.

**Comment by guidtz** [comment]
ok i'll go to scan the mailcow database and search where are roundcube contacts

**Comment by guidtz** [comment]
Ok I resolved the problems. Data are already in database in table "contacts" with all vcard informations ... ouf :-)
So I updated roudncube from 1.3.6 to 1.3.8 and now contacts informations are ok

we could close this issue.
