### ISSUE TITLE
Certificate expired - acme - default settings - logs says anything is fine

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#2438]
Hello,

my certificate (acme) is expired but the logs says `Certificate validation done, neither changed nor due for renewal, sleeping for another day.`.

Why, i didnt changed anything in the docker file, so the default mappings(`./data/assets/ssl:/etc/ssl/mail/:ro`) are active.

How i can fix that issue ?

**Comment by andryyy** [comment]
You are probably using a reverse proxy and didn't run a post-hook to copy the certs?

Check the certs in data/assets/ssl AND your reverse proxy certs with openssl for expiry.

**Comment by UtechtDustin** [comment]
I use apache as reverse proxy, but why is that an problem ?
Why the application dont write/copy the new cert to the directory ?

Is there a example how to configure the post-hook ?

Edit: `Optional: Post-hook script for non-mailcow ACME clients` from https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#optional-post-hook-script-for-non-mailcow-acme-clients.
I use the ACME client from mailcow, so why i need a post-hook ?

**Comment by andryyy** [comment]
The reverse proxy is using a different certificate, I think.

See https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#apache-24

Make sure your site has these lines included:
```
  SSLCertificateFile MAILCOW_PATH/data/assets/ssl/cert.pem
  SSLCertificateKeyFile MAILCOW_PATH/data/assets/ssl/key.pem
```
Read the info at the top: Apache2 is usually reloaded by logrotate, so it should be fine not to reload it manually. But it depends on the system. 

Is your problem solved by reloading Apache2? If not, do you find the lines mentioned about in your site config?

**Comment by UtechtDustin** [comment]
Oh okay i understand, i had an other acme client for the proxy.
I changed it to the MAILCOW_PATH/data/assets/ssl/*.pem, reloaded the server and it works fine.
