### ISSUE TITLE
Unablet to remove auto created ratelimit

### ISSUE THREAD

**Issue by xyphosbz** [mailcow/mailcow-dockerized#2439]
Hello good day, 

Recently I have come across a strange issue where I am unable to remove an automatically created ratelimit from mailcow. When I try to remove the has via the ratelimit section under logs it gives me Access denied or invalid form data error. I have attached an image of the error. Also, I keep getting emails from watchdog regularly stating that Watchdog: ratelimit hit the error rate limit. 

Where can I go to remove these ratelimits and fix this issue with the ratelimit hitting the error rate. Note that have never touched any ratelimit settings so everything should be default values. 

![image](https://user-images.githubusercontent.com/31674648/54373603-2dffc200-4643-11e9-95cd-420340a0b5ec.png)

**Comment by andryyy** [comment]
Hi,
Hm, the hash could already be vanished. Need to check that.

**Comment by andryyy** [comment]
Ah, no, the rate limit hash is just not correct.

You receive the mail, because a ratelimit was triggered.... that's wanted.

It doesn't store the hash in its correct form though.

Hm, I will try to replicate it.

**Comment by xyphosbz** [comment]
okay, is there anything you need from my end?

**Comment by andryyy** [comment]
Not yet. :)

**Comment by xyphosbz** [comment]
alright, thanks for the help

**Comment by andryyy** [comment]
The hashes are stored correctly. I think some files were not correctly updated in your installation.

Can I check this on your server?

**Comment by xyphosbz** [comment]
Okay, where can I send you the login details? Is it possible for teamviewer to be used?

**Comment by andryyy** [comment]
Yes, info@servercow.de

**Comment by xyphosbz** [comment]
Okay I sent you the information

**Comment by andryyy** [comment]
For some reason it saved a hash in its old format (`2222:blabla`). This was a hash from an older rspamd-mailcow image, which should not have been written to Redis. Don't know, must have been a strange conflict. I deleted the hash and checked it indeed saves correct hashes now (that was `1234:blabla -> RLabcdefghijkl123` you saw in the debug logs).

**Comment by xyphosbz** [comment]
okay yes see that those rate limits are gone, thank you very much for the assistance

**Comment by germanosbh** [comment]
Hi, 
I have a similar problem. 
If I try to "remove hash", I see the message "Hash not found" but messages continue to be listed in ratelimit.
![ratelimit](https://user-images.githubusercontent.com/43640016/57378989-46401900-717c-11e9-9f8e-640a524e13c9.png)

How can I solve this? Thank you !
