### ISSUE TITLE
dkim not working

### ISSUE THREAD

**Issue by nmahadkar** [mailcow/mailcow-dockerized#244]
I did a fresh install twice following the exact instruction in the docs.  Both occasions I the emails are not signed by DKIM.  I generated dkim keys using the admin panel.  I do not know where the issue is but I did notice that data/conf/rmilter/rmilter.conf lists 

`dkim {
        enable = false;
};`
How do I fix this so that outgoing emails are signed?

**Comment by chaosbunker** [comment]
Are you sure you added the dkim value in your dns?

under name put `dkim._domainkey`
type `txt`
value ` v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjAN...`

I checked my rmilter.conf and it also says enable = false, but my messages are signed as expected.

**Comment by nmahadkar** [comment]
----------------------------------------------------------
DKIM check details:
----------------------------------------------------------
`Result: neutral (message not signed)
ID(s) verified: 

NOTE: DKIM checking has been performed based on the latest DKIM specs
(RFC 4871 or draft-ietf-dkim-base-10) and verification may fail for
older versions. If you are using Port25's PowerMTA, you need to use
version 3.2r11 or later to get a compatible version of DKIM.`

`postfix-mailcow_1    | May  4 15:44:35 smtp4 postfix/smtp[367]: Untrusted TLS connection established to verifier.port25.com[38.95.xxx.xxx]:25: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
postfix-mailcow_1    | May  4 15:44:35 smtp4 postfix/smtp[367]: 42FD54A4: to=<check-auth@verifier.port25.com>, relay=verifier.port25.com[38.95.XXX.XXX]:25, delay=1.2, delays=0.24/0.1/0.66/0.21, dsn=2.6.0, status=sent (250 2.6.0 message received)
postfix-mailcow_1    | May  4 15:44:35 smtp4 postfix/qmgr[325]: 42FD54A4: removed
`

This is the postfix log

I have put the dkim into my DNS records but it looks like the outgoing messages are not signed.

**Comment by andryyy** [comment]
Need The Rspamd logs after sending a mail. Also: does the domain match the senders domain?

Beste Grüße 
André

**Comment by nmahadkar** [comment]
`rspamd-mailcow_1     | 2017-05-04 16:03:31 #11(normal) <4c1a2d>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
rspamd-mailcow_1     | 2017-05-04 16:03:31 #11(normal) <4c1a2d>; task; spf_symbol_callback: skip SPF checks for local networks and authorized users
rspamd-mailcow_1     | 2017-05-04 16:03:31 #11(normal) <4c1a2d>; lua; once_received.lua:78: Skipping once_received for authenticated user or local network
rspamd-mailcow_1     | 2017-05-04 16:03:31 #11(normal) <4c1a2d>; task; lua_dkim_sign_handler: cannot load dkim key /data/dkim/keys/mydomain.io.dkim: cannot map private key /data/dkim/keys/mydomain.io.dkim: No such file or director`

the sending domain is subdomain.mydomain.io and the keys have been generated using the panel and the sending domain matches the dkim key. 

also I noticed that the `mailcow-dockerized/data/dkim` directory does not exist.

**Comment by andryyy** [comment]
What is the output of `docker-compose exec rspamd-mailcow ls -la /data/dkim/keys`?

**Comment by nmahadkar** [comment]
`subdomain.mydomain.io.dkim` looks like the file exists
but the right file is not being used its looking for `mydomain.io.dkim`

**Comment by andryyy** [comment]
Can you please open `data/conf/rspamd/local.d/dkim_signing.conf` and set `use_esld` to false? :)
Edit: And restart rspamd-mailcow afterwards: `docker-compose restart rspamd-mailcow`

**Comment by nmahadkar** [comment]
that worked gmail says `DKIM:	PASS with domain subdomain.mydomain.io`.  :)

**Comment by andryyy** [comment]
Great! I will push it to the repo.

**Comment by Braintelligence** [comment]
@andryyy I try to follow this ticket but I don't understand the implications. Was it a problem with subdomains of a domain using DKIM as well?

**Comment by nmahadkar** [comment]
rspamd documentation states  ` # Whether to normalise domains to eSLD |
  use_esld = true;` esld = (second level domain parts)

**Comment by andryyy** [comment]
It was about subdomain signing and Rspamd not looking for key file "sub.domain.tld.dkim" but "domain.tld.dkim".

**Comment by Braintelligence** [comment]
So I need to update from master, if I want subdomains to work properly with DKIM key?

**Comment by andryyy** [comment]
If you don't change it, it will just use the parents domain DKIM key.

**Comment by Braintelligence** [comment]
After this update, is it also possible to just use the parent domain DKIM key or am I obligated to use subdomain DKIM key in DNS zone now?

**Comment by chaosbunker** [comment]
@andryyy 
 talking about domainkeys, i miss the option to choose the domainkey name myself or have more than one domainkey per domain, as it was possible in 0.14

it sometimes is useful, e.g. when i want to have a domain with two different mx servers, that both sign dkim ...

**Comment by andryyy** [comment]
You can just leave it as it is, @Braintelligence - if you have subdomains right now, they will need their own key files with the new setting.

@chaosbunker This may return.

**Comment by Braintelligence** [comment]
@andryyy Alright, thanks for clarifying! 😸

**Comment by Power-MTA** [comment]
🙌🙌🙌 latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1
