### ISSUE TITLE
Its possible to bypass SPF,DKIM if spoofed e-mail is sent to alias

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#2440]
Hello, 

I have set up SPF and DKIM keys for the domain.
In the long run, everything looks great, and spoofed senders get blocked.
But today one mailbox received a threatening e-mail from her own address, it was the classic "Im a hacker, give me your bitcoins..."

So I investigated and found out that the spoofed e-mail was sent to the person's alias e-mail
then it got forwarded to end recipient.

Any ideas how could this happen?

heres the email source:

Return-Path: <misawa@enshokai.or.jp>
Delivered-To: laima.bird@asd123.com
Received: from my.mailserver.com ([172.22.1.9])
	by my.mailserver.com with LMTP
	id 2DWUEkVwiVxeBwAAHnhJMA
	(envelope-from <misawa@enshokai.or.jp>)
	for <laima.bird@asd123.com>; Wed, 13 Mar 2019 23:04:05 +0200
Received: from my.mailserver.com (mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network [172.22.1.4])
	by my.mailserver.com (Postcow) with ESMTP id 36B3713C1A3C
	for <laima.bird@asd123.com>; Wed, 13 Mar 2019 23:04:05 +0200 (EET)
X-Sieve: Pigeonhole Sieve 0.5.4 (60b0f48d)
X-Sieve-Redirected-From: laima.aliassurname@asd123.com
Delivered-To: laima.aliassurname@asd123.com
Received: from my.mailserver.com ([fd4d:6169:6c63:6f77::1])
	by my.mailserver.com with LMTP
	id oPBaCkVwiVxeBwAAHnhJMA
	(envelope-from <misawa@enshokai.or.jp>)
	for <laima.aliassurname@asd123.com>; Wed, 13 Mar 2019 23:04:05 +0200
Received: from oogw1339.ocn.ad.jp (oogw1339.ocn.ad.jp [153.153.62.105])
	by my.mailserver.com (Postcow) with ESMTP id 21E7A13C1A2B
	for <laima.aliassurname@asd123.com>; Wed, 13 Mar 2019 23:03:52 +0200 (EET)
Received: from cmn-spm-mts-007c1.ocn.ad.jp (cmn-spm-mts-007c1.ocn.ad.jp [153.153.67.163])
	by oogw1339.ocn.ad.jp (Postfix) with ESMTP id 9DAF7A60C1E
	for <laima.aliassurname@asd123.com>; Thu, 14 Mar 2019 05:26:11 +0900 (JST)
Received: from mwb-vc-mts-001c1.ocn.ad.jp ([153.138.237.203])
	by cmn-spm-mts-007c1.ocn.ad.jp with ESMTP
	id 4AS2htTlxxayi4AS3hnD68; Thu, 14 Mar 2019 05:26:11 +0900
X-BIZ-RELAY: yes
Received: from sgs-vcgw117.ocn.ad.jp ([153.149.141.227])
	by mwb-vc-mts-001c1.ocn.ad.jp with ESMTP
	id 4AS3hKfShsU9L4AS3hCvbF; Thu, 14 Mar 2019 05:26:11 +0900
Received: from enshokai.or.jp (enshokai.or.jp [122.1.222.145])
	by sgs-vcgw117.ocn.ad.jp (Postfix) with ESMTP id 3193D24027A
	for <laima.aliassurname@asd123.com>; Thu, 14 Mar 2019 05:26:11 +0900 (JST)
Received: from [177-86-156-108.netecom.net.br] (177-86-156-46.netecom.net.br [177.86.156.46])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(Client did not present a certificate)
	by enshokai.or.jp (Postfix) with ESMTPSA id AEB80CFDEAFD
	for <laima.aliassurname@asd123.com>; Thu, 14 Mar 2019 05:25:51 +0900 (JST)
X-aid: 0372180482
From: <laima.aliassurname@asd123.com>
Organization: Nnujbho
X-Sender-Info: <misawa@enshokai.or.jp>
Errors-To: F10CA66CE505E7C1BA7D8455EE@mail.enshokai.or.jp
Date: Wed, 13 Mar 2019 21:25:51 +0100
List-Unsubscribe:
 <mailto:1214A981FA18A70AA37D1FF1E28540@unsubscribe.enshokai.or.jp>,
Subject: laima.aliassurname
Message-ID: <43tj6uw7-8ekw-u7ku-2joh-hjrj1ix48z48>
Content-Type: multipart/related;
 boundary="BDC7436094A5A4A751A-3CB75F03-DB07F3-AB014A362E0CE27-FFD5BEFE"
MIME-Version: 1.0
To: laima.aliassurname@asd123.com
Authentication-Results: my.mailserver.com
X-Spamd-Result: default: False [2.09 / 15.00];
	 ARC_NA(0.00)[];
	 MIME_GOOD(-0.10)[multipart/related,multipart/alternative,text/plain];
	 PREVIOUSLY_DELIVERED(0.00)[laima.aliassurname@asd123.com];
	 TO_DN_NONE(0.00)[];
	 HAS_LIST_UNSUB(-0.01)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 HAS_ORG_HEADER(0.00)[];
	 MIME_BASE64_TEXT(0.10)[];
	 FROM_NO_DN(0.00)[];
	 INVALID_MSGID(1.70)[];
	 FORGED_SENDER(0.30)[laima.aliassurname@asd123.com,misawa@enshokai.or.jp];
	 RCVD_NO_TLS_LAST(0.10)[];
	 TO_EQ_FROM(0.00)[];
	 MIME_TRACE(0.00)[0:+,1:+,2:+];
	 RCPT_MAILCOW_DOMAIN(0.00)[asd123.com];
	 FROM_NEQ_ENVFROM(0.00)[laima.aliassurname@asd123.com,misawa@enshokai.or.jp];
	 RCVD_COUNT_SEVEN(0.00)[8]
X-Rspamd-Queue-Id: 36B3713C1A3C

**Comment by andryyy** [comment]
Just curious why the SPF symbol is missing. But these mails are mostly SPF-clean - they avoid using your exact mail address in the "From" header.
I think the newest Rspamd handles Bitcoin stuff much better. :) You are probably on Rspadm 1.8.something.

**Comment by reinistihovs** [comment]
The spammer attached the text with an inline JPEG
![image](https://user-images.githubusercontent.com/33620345/54424412-7db1bc80-471b-11e9-84c8-a11279389042.png)

My cow is updated in Foobroary :)

docker-compose exec rspamd-mailcow rspamadm -V
**Rspamadm 1.8.3**

**Comment by reinistihovs** [comment]
Any thoughts about increasing the value of "FORGED_SENDER"?
What risks could this cause in normal scenarios?

**Comment by PeterHagen** [comment]
I just received a similar email, also to an alias email address.

```
Return-Path: <gaichu@asteer.co.jp>
Delivered-To: info@examenbureau-installatietechniek.nl
Received: from balder.willow-media.nl ([fd4d:6169:6c63:6f77::7])
	by balder.willow-media.nl with LMTP
	id HZIQMVI7klwEbwAA/edkMg
	(envelope-from <gaichu@asteer.co.jp>)
	for <info@examenbureau-installatietechniek.nl>; Wed, 20 Mar 2019 14:08:34 +0100
Received: from asteer.co.jp (asteer.co.jp [153.122.124.250])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by balder.willow-media.nl (Postcow) with ESMTPS id 2ED56240111
	for <r.gijsbertsen@examenbureau-installatietechniek.nl>; Wed, 20 Mar 2019 14:08:29 +0100 (CET)
Received: from [177-129-202-106.nnt.net.br] (177-129-202-106.nnt.net.br [177.129.202.106] (may be forged))
	(authenticated bits=0)
	by asteer.co.jp (8.14.5/8.13.1) with ESMTP id x2KD3wVK005286
	for <r.gijsbertsen@examenbureau-installatietechniek.nl>; Wed, 20 Mar 2019 22:08:00 +0900
X-Abuse-Reports-To: <abuse@mailer.asteer.co.jp>
Date: Wed, 20 Mar 2019 14:08:02 +0100
X-Complaints-To: abuse@mail.asteer.co.jp
Abuse-Reports-To: <abuse@mail.asteer.co.jp>
Subject: r.gijsbertsen
To: r.gijsbertsen@examenbureau-installatietechniek.nl
Feedback-ID: 19857:31664.4821773:s69:vo
List-Subscribe: <mailto:MEMBERS-subscribe-request@asteer.co.jp>
X-Priority: 1
X-Sender: gaichu@asteer.co.jp
List-Help: <mailto:{contact|info|abuse|aufaox@asteer.co.jp?subject=help>
From: <r.gijsbertsen@examenbureau-installatietechniek.nl>
List-ID: <089240379207.asteer.co.jp>
Message-ID: <lij30qy644w3$xlpum4oc$iphwgc3f$@asteer.co.jp>
User-Agent: Workspace Webmail 6.9.01
Content-Type: multipart/related;
 boundary="yf5iuf8471-y052hkyv9z-gog0ia09oq-lifxmoj6bm-pc4n7tv7tr"
MIME-Version: 1.0
Authentication-Results: balder.willow-media.nl;
	dkim=none;
	dmarc=fail reason="SPF not aligned (relaxed), No valid DKIM" header.from=examenbureau-installatietechniek.nl (policy=none);
	spf=pass (balder.willow-media.nl: domain of gaichu@asteer.co.jp designates 153.122.124.250 as permitted sender) smtp.mailfrom=gaichu@asteer.co.jp
X-Spamd-Result: default: False [-991.51 / 15.00];
	 R_SPF_ALLOW(0.00)[+ip4:153.122.124.250];
	 TO_DN_NONE(0.00)[];
	 MX_GOOD(-0.01)[asteer.co.jp];
	 MIME_BASE64_TEXT(0.10)[];
	 FORGED_SENDER(0.30)[r.gijsbertsen@examenbureau-installatietechniek.nl,gaichu@asteer.co.jp];
	 RCPT_MAILCOW_DOMAIN(0.00)[examenbureau-installatietechniek.nl];
	 TO_EQ_FROM(0.00)[];
	 R_DKIM_NA(0.00)[];
	 HAS_X_PRIO_ONE(0.00)[1];
	 ASN(0.00)[asn:131921, ipnet:153.122.112.0/20, country:JP];
	 FROM_NEQ_ENVFROM(0.00)[r.gijsbertsen@examenbureau-installatietechniek.nl,gaichu@asteer.co.jp];
	 MAILCOW_WHITE(-999.00)[];
	 ARC_NA(0.00)[];
	 RECEIVED_SPAMHAUS_XBL(3.00)[106.202.129.177.zen.spamhaus.org : 127.0.0.4];
	 RECEIVED_SPAMHAUS_CSS(1.00)[106.202.129.177.zen.spamhaus.org : 127.0.0.3];
	 MIME_TRACE(0.00)[0:+,1:+,2:+,3:~,4:~];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 MIME_GOOD(-0.10)[multipart/related,multipart/alternative,text/plain];
	 PREVIOUSLY_DELIVERED(0.00)[r.gijsbertsen@examenbureau-installatietechniek.nl];
	 RCPT_COUNT_ONE(0.00)[1];
	 BAD_REP_POLICIES(0.10)[];
	 RECEIVED_BLOCKLISTDE(3.00)[106.202.129.177.bl.blocklist.de];
	 RCVD_TLS_LAST(0.00)[];
	 FROM_NO_DN(0.00)[];
	 RCVD_IN_DNSWL_NONE(0.00)[250.124.122.153.list.dnswl.org : 127.0.10.0];
	 RCVD_COUNT_TWO(0.00)[2];
	 DMARC_POLICY_SOFTFAIL(0.10)[examenbureau-installatietechniek.nl : SPF not aligned (relaxed), No valid DKIM,none]
X-Rspamd-Queue-Id: 2ED56240111
```

**Comment by andryyy** [comment]
You could create Rspamd settings to reject on some of those symbols or even reject if stuff like DKIM, SPF is missing for your own domains. 

Rspamd is well documented. :)

**Comment by Viktova** [comment]
@reinistihovs the same exact thing is happening in our company.

I have DMARC policy set to reject and i have SPF for google & microsoft only also I have a valid DKIM signature still somehow they are able to bypass all that and bypass rspamd.

i'm on version **1.9.0**

**Comment by andryyy** [comment]
You need to post some logs. Or update mailcow. I think I added a new rule.
