### ISSUE TITLE
how das MAILCOW_AUTH work? 

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#2441]
I see in Rspamd that some mails get MAILCOW_AUTH (-20). 
First i see it when i send a mail from one account to another within the same mail server and this should be fine :) 

But how does this work over different Mail servers ? Supermicro.com as an example get this flag. 

I didnt find anything about that, so sry if i didnt find the docs for this.

**Comment by andryyy** [comment]
Hi,

I don't see this here with Supermicro. :/ Is this a forwarded message? Or relayed?

**Comment by wuast94** [comment]
nevermind. thats outgoing mails :D than another question. 

why get outgoing mails spam checked ?

**Comment by andryyy** [comment]
You mean "why wouldn't they"? :)

You can increase the MAILCOW_AUTH symbols score or check the Rspamd settings about how to disable outbound scanning.
