### ISSUE TITLE
apt-get update and apt-get upgrade inside containers

### ISSUE THREAD

**Issue by stAn47** [mailcow/mailcow-dockerized#2444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

**Comment by stAn47** [comment]
hello i would like to ask if it's a good idea to run 

apt-get update
apt-get upgrade

inside each docker container coming with mailcow on ubuntu. 

i see lot's of ubuntu core packages that need a security update but i am new to docker, so this is not really clear to me. 

should i set up a cron job to update them all at once?

thank you, 
best regards, stan

**Comment by mkuron** [comment]
@andryyy updates the Docker images regularly, so this shouldn't be necessary. Besides, we compile software like Postfix and SOGo from source, so updating the base operating system won't get you security updates for those.

**Comment by stAn47** [comment]
hello, thank you, i just updated all mailcow docker images and i see 
```
Inst base-files [9.9+deb9u6] (9.9+deb9u8 Debian:9.8/stable [amd64])
Conf base-files (9.9+deb9u8 Debian:9.8/stable [amd64])
Inst libc-bin [2.24-11+deb9u3] (2.24-11+deb9u4 Debian:9.8/stable [amd64])
Conf libc-bin (2.24-11+deb9u4 Debian:9.8/stable [amd64])
Inst libapt-pkg5.0 [1.4.8] (1.4.9 Debian:9.8/stable, Debian-Security:9/stable [amd64])
Conf libapt-pkg5.0 (1.4.9 Debian:9.8/stable, Debian-Security:9/stable [amd64])
Inst gpgv [2.1.18-8~deb9u3] (2.1.18-8~deb9u4 Debian:9.8/stable [amd64])
Conf gpgv (2.1.18-8~deb9u4 Debian:9.8/stable [amd64])
Inst apt [1.4.8] (1.4.9 Debian:9.8/stable, Debian-Security:9/stable [amd64])
Conf apt (1.4.9 Debian:9.8/stable, Debian-Security:9/stable [amd64])
Inst libsystemd0 [232-25+deb9u6] (232-25+deb9u9 Debian-Security:9/stable [amd64])
Conf libsystemd0 (232-25+deb9u9 Debian-Security:9/stable [amd64])
Inst multiarch-support [2.24-11+deb9u3] (2.24-11+deb9u4 Debian:9.8/stable [amd64])
Conf multiarch-support (2.24-11+deb9u4 Debian:9.8/stable [amd64])
Inst libudev1 [232-25+deb9u6] (232-25+deb9u9 Debian-Security:9/stable [amd64])
Conf libudev1 (232-25+deb9u9 Debian-Security:9/stable [amd64])
Inst tzdata [2018g-0+deb9u1] (2018i-0+deb9u1 Debian:9.8/stable, Debian:stable-updates [all])
Conf tzdata (2018i-0+deb9u1 Debian:9.8/stable, Debian:stable-updates [all])
```

maybe just security packages every day wouble be ok, enough and stable ? since maicow doesn't really want to be updated every day when there is a security update in system packages. 


```
apt-get install unattended-upgrades
```

thanks, stan
