### ISSUE TITLE
SOGo search bar not working

### ISSUE THREAD

**Issue by aronmgv** [mailcow/mailcow-dockerized#2446]
Recently noticed searchbar in sogo is not working.. just updated to the latest version and still.
None from the dropdown values are working:
![image](https://user-images.githubusercontent.com/6546231/54495767-3710bd80-48e7-11e9-80df-97b85bb2299d.png)

**Comment by andryyy** [comment]
Try `docker-compose exec dovecot-mailcow doveadm fts rescan -A`

**Comment by aronmgv** [comment]
thanks, that did the trick.. why so?

**Comment by andryyy** [comment]
I destroyed the index a few times. :(
