### ISSUE TITLE
Rspamd White-/Blacklisting not working anymore?

### ISSUE THREAD

**Issue by Arkaniod** [mailcow/mailcow-dockerized#2447]
I'm running two mailcow-installations (both on Debian Stretch):

No. 1 - primary MX - with installed Updates of Feb. 7th 2019

No. 2 - backup MX - with installed Updates of Mar. 10th 2019

Configuration ist nearly identical, the only difference is, that solr is deactivated on the backup MX (and - of course - it is configured as backup mx...).
On both servers there are identical white- & blacklists (global_smtp_from_whitelist.map & global_smtp_from_blacklist.map) for Rspamd. Took me a long time of experiments with the regex-syntax, but everything is working fine now.

On the primary MX (with installed Updates of Feb. 7th 2019) Rspamd white-/blacklisting works fine.

![mailcow_02](https://user-images.githubusercontent.com/25243946/54516049-1a639c80-495e-11e9-937c-63cfad0910fc.png)

![rspamd02](https://user-images.githubusercontent.com/25243946/54516065-264f5e80-495e-11e9-907e-b54603e967db.png)

On the backup mx (with installed Updates of Mar. 10th 2019) Rspamd white-/blacklisting seems to be ignored

![mailcow](https://user-images.githubusercontent.com/25243946/54516125-5565d000-495e-11e9-838c-07b8d7e00a78.png)

![rspamd](https://user-images.githubusercontent.com/25243946/54516133-5a2a8400-495e-11e9-9a5b-0f1c8db577a8.png)

Any ideas? Was/is a great feature for reducing spam that I'm hardly missing... Did I miss/oversee anything on the last update? How can this get reactivated?

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?)
    **Debian Stretch (Kernel 4.9.0.8-amd64) without Apparmor or SELinux**
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)
   **Proxmox VM**
 - Your server/VM specifications (Memory, CPU Cores)
  **8 GB RAM, 4 vCores on primary MX
   4 GB RAM, 2 vCores on backup MX**
 - Don't try to run mailcow on a Synology or QNAP NAS, do you?
   **No, for sure...**
 - Docker and Docker Compose versions
   **primary MX:
   Docker: 18.09.2 build 6247962
   Docker Compose: 1.23.2 build 1110ad01
   backup MX:
   Docker: 18.09.3 build 774a1f4
   Docker Compose: 1.23.2 build 1110ad01**

Thanks in advance.

Cheers

Chris

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/54528732-121b5980-497e-11e9-8955-9f6edf573f39.png)

This screenshot looks like the "envelope from" was "inxserver.com". You need to move that rule to global_mime_from. :)

**Comment by Arkaniod** [comment]
Hello André,

thanks for the quick reply and the hint... I understand, that whitelisted addresses sent from other domains or with different "envelope from" (like in the example with polo-motorrad.de) have to be in "global_mime_from_whitelist.map". Correct?

**Comment by andryyy** [comment]
global_mime matches the "From" header in a mail. global_smtp matches the envelope or "Return-Path" header of a mail.

Most (bulk) mails have a different "Return-Path" header to better analyze bounces.

**Comment by Arkaniod** [comment]
Great!
Thanks a lot for the enlightment.
