### ISSUE TITLE
Change Nextcloud config variables for external_user v0.6

### ISSUE THREAD

**Issue by dtoenies** [mailcow/mailcow-dockerized#2448]
**Describe the bug, try to make it reproducible**
I have updated the external_user plugin from 0.5.1 to 0.6. After this update a login with E-Mail was not possible. I reverted back to 0.5.1 and everything worked fine again.
In the external user_plugin is already an issue (https://github.com/nextcloud/user_external/issues/52) and it seems the config variables in the mailcow nextcloud installation need an update (https://github.com/nextcloud/user_external#imap).

**System information and quick debugging**

Further information:
- Nextcloud 15.0.4
- Last update of mailcow: right now

Regards,
Daniel

**Comment by violoncelloCH** [comment]
yes, the config values need to be updated! see nextcloud/user_external#49 for details...
this is because we can't use php-imap as a dependency, because it's deprecated (won't be shipped by distros in the future and has problems with TLS >1.0)
unfortunately the config was specific to php-imap, what is why we changed it...

cc @andryyy

**Comment by Schuermi7** [comment]
Can someone pls reopen this and look into this, because it doesnt seem to work with a changed config like this
`    array (
      array (
        'class' => 'OC_User_IMAP',
        'arguments' =>
        array (
          'dovecot', 143, 'tls', ''
        ),
      ),
    ),
`

**Comment by andryyy** [comment]
I removed the plugin from the installer, it failed too often.

I plan to write a plugin to authenticate against mailcow and read quotas etc.

**Comment by Schuermi7** [comment]
Thank you. 
Looking forward to this.
