### ISSUE TITLE
101: Network unreachable DNS Check

### ISSUE THREAD

**Issue by GlowManCZ** [mailcow/mailcow-dockerized#2449]
Hi, after the mailcow migration to the new server, I encountered a minor problem. I changed all DNS to a new IP address but the dns check writes unavailable TLSA records. Screenshot included.   

![Snímek obrazovky 2019-03-18 v 19 27 43](https://user-images.githubusercontent.com/23487345/54554491-d6e84d00-49b4-11e9-9d62-7db8bd43f289.png)

**Comment by andryyy** [comment]
Firewall issue. It cannot connect to its own hostname via tcp on these ports. Edit: Firewall or networking in general.

**Comment by GlowManCZ** [comment]
The server is at Hetzner DE and the Firewall is set to release everything and its a clear CentOS installation.

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#hetzner-cloud-and-probably-others

**Comment by GlowManCZ** [comment]
Yep, I found that before, but I have dedicated server. Without this cloud configuration :-(

**Comment by andryyy** [comment]
A fresh CentOS would come with SELinux and firewalld enabled. :)

**Comment by GlowManCZ** [comment]
I've been trying to find a setting in the CentOS Firewall that blocks it, but I don't know where to look. But the most strange thing is that the only records that don't work are TLSA. For others, the scan works.

**Comment by andryyy** [comment]
It is firewalld then.

No other check needs a tcp connection to the public hostname, only TLSA does. Could be a hair pinning issue.

**Comment by GlowManCZ** [comment]
Thx, With CentOS I am a beginner and can't figure out a way to enable it in firewalld. Could I please ask for help pleas? I wanted to use Debian for the first time, but because of the size of the disk and the raid I have to use Cent :-(

**Comment by extremeshok** [comment]
@GlowManCZ ubuntu LTS should work perfecly for your needs.

Use my script on a fresh ubuntu 18.04 install to correctly configure and optimised ubuntu with docker, once done run mailcow-docker and you will have a perfect setup.

https://github.com/extremeshok/xshok-docker

**Comment by GlowManCZ** [comment]
I have a little problem here. The system is already deployed sharply and it will not be possible to switch to Ubuntu. I have a completely clean CentOS installation with docker and mailcow only. And about 500GB email boxes.  Everything works fine except problem of not working with TLSA. And in the CentOS firewalld, I didn't find any rule that would block it.

**Comment by extremeshok** [comment]
Ok, have you tried disabling the caching dns of systemd  ( systemd-resolved ) and specifying namservers in /etc/resolv.conf ? (this will break setting  namservers via dhcp)

**Comment by GlowManCZ** [comment]
Thank you, I'll test. It is a dedicated server on Hetzner DE as I wrote and they assign IP addresses using DHCP :-) So it might be a little problem.

**Comment by extremeshok** [comment]
````
## Disable local dns server, do not disable systemd-resolved as this breaks nameservers configured with netplan
sed -i 's|#DNSStubListener=yes|DNSStubListener=no|g' /etc/systemd/resolved.conf
sed -i 's|DNSStubListener=yes|DNSStubListener=no|g' /etc/systemd/resolved.conf
sed -i 's|#DNSStubListener=no|DNSStubListener=no|g' /etc/systemd/resolved.conf
rm -rf /etc/resolv.conf
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
systemctl enable systemd-resolved.service
## reboot
````

@glowman, i have lots and lots servers with them in clusters. I run proxmox and then setup ubuntu vm;s for dockers. Easy migrations, backups, snapshots, all the benefits of ZFS
https://github.com/extremeshok/xshok-proxmox

**Comment by GlowManCZ** [comment]
I`m reinstall centos firewall and now its working :-)
