### ISSUE TITLE
DKIM key doesn't fit the message key

### ISSUE THREAD

**Issue by bumbalaga** [mailcow/mailcow-dockerized#245]
Hello, so i've been trying to find myself in the new mailcow gui and i can't seem to configure the DKIM keys properly. Not sure if its my fault, or there's something wrong with the mailcow itself.

My config looks like this:
[Mailcow config](https://ss.bumbalaga.net/2017-05-05_00-36-46.png)
[DNS settings](https://ss.bumbalaga.net/2017-05-05_00-39-27.png)

And the result i'm getting is this:
[mail test result](https://ss.bumbalaga.net/2017-05-05_00-43-25.png)

Am i doing something wrong?

Sorry for previous post in the wrong repo :cry:

**Comment by broedli** [comment]
Did you even follow the leads in #244?
Please provide your rspamd logs showing a signing of your outgoing mail: `docker-compose logs -f rspamd-mailcow`

**Comment by andryyy** [comment]
Or did you just replace an older key? Or corrected yourself? DNS propagation is slow. :)

**Comment by bumbalaga** [comment]
Sorry broedli, you were right. Its just that instead of "false" i've typed "falsec".

Sorry for the trouble, problem fixed.

**Comment by broedli** [comment]
I'm closing this, if your problem still exists or reoccurs please reopen this issue and report 🙂
