### ISSUE TITLE
Mailcow have high memory usage with netdata monitoring

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#2451]
I have netdata installed on several mailcow instances.
With older version of netdata I don't have any problem, but when I updated netdata last month problem was showing.
Netdata use much of memory and machine goes to SWAP.

I wrote to netdata on git, and after the testing they suggest me to write you here.

[Here is the netdata open issue from me on github:](https://github.com/netdata/netdata/issues/5601)

Mailcow version:
```
commit d3fc07be0d9a4bd02b634748a9c00cbbf8f8b6d2 (HEAD -> master)
Merge: 58122878 cf93910a
Author: moo <moo@cow.moo>
Date:   Wed Jan 16 21:28:12 2019 +0100
```

Netdata version:
`v1.12.2-4-geccf0b9e`

OS:

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

Output of this command:
`for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r `

Netdata was on top:

```
netdata 417412 kB
mysqld 206612 kB
```

Smem ouput:

```
smem -k | grep netdata
20914 root     grep --color=auto netdata          0   488.0K   780.0K     2.3M
29066 netdata  /usr/sbin/sogod                12.7M   776.0K   834.0K     3.3M
29064 netdata  /usr/sbin/sogod                12.7M   780.0K   838.0K     3.3M
29076 netdata  /usr/sbin/sogod                12.7M   784.0K   842.0K     3.3M
29065 netdata  /usr/sbin/sogod                12.7M   788.0K   846.0K     3.3M
29075 netdata  /usr/sbin/sogod                12.7M   788.0K   846.0K     3.3M
29070 netdata  /usr/sbin/sogod                12.7M   796.0K   854.0K     3.3M
29086 netdata  /usr/sbin/sogod                12.7M   808.0K   866.0K     3.3M
29081 netdata  /usr/sbin/sogod                12.7M   812.0K   870.0K     3.3M
29088 netdata  /usr/sbin/sogod                12.7M   812.0K   870.0K     3.3M
14335 netdata  /usr/sbin/sogod                82.6M   828.0K   885.0K     3.4M
29095 netdata  /usr/sbin/sogod                27.8M   848.0K   906.0K     3.4M
 5336 netdata  /usr/sbin/sogod                90.1M   832.0K   914.0K     3.9M
29094 netdata  /usr/sbin/sogod                28.9M   856.0K   914.0K     3.4M
22977 netdata  /usr/sbin/sogod                68.9M   884.0K   943.0K     3.5M
  740 netdata  /usr/sbin/sogod                35.7M   868.0K   950.0K     3.9M
28312 netdata  /usr/sbin/sogod                46.5M   892.0K   955.0K     3.5M
 6790 netdata  /usr/sbin/sogod                34.9M   880.0K   959.0K     3.9M
29110 netdata  /usr/sbin/sogod                49.3M   964.0K     1.1M     4.0M
14620 netdata  /usr/libexec/netdata/plugin   676.0K     1.5M     1.5M     1.5M
29010 netdata  /usr/sbin/sogod                10.4M     1.4M     1.6M     4.5M
29084 netdata  /usr/sbin/sogod                26.8M     2.4M     2.6M     5.4M
 4582 netdata  /usr/sbin/sogod                63.5M     7.5M     7.7M    10.5M
14614 netdata  /usr/bin/python /usr/libexe     5.7M    13.0M    13.7M    15.1M
12350 netdata  mysqld                        191.6M    21.5M    21.6M    22.0M
14532 netdata  /usr/sbin/netdata -P /run/n   407.5M     1.2G     1.2G     1.2G
```
There is too much sogod process.

**Comment by andryyy** [comment]
Hi, there aren't too many sogod procs. These are workers and wanted. If you don't care about EAS, you can reduce the workercount in sogo.conf to something like 3 or 4.

**Comment by petarkozic** [comment]
@andryyy 
Thanks for the reply.
Please, do you know, do you have that in the documentation?
What is the right way to configure that?

**Comment by andryyy** [comment]
It's in `data/conf/sogo/sogo.conf` -> `WOWorkersCount`

**Comment by petarkozic** [comment]
> It's in `data/conf/sogo/sogo.conf` -> `WOWorkersCount`

Can this affect users who use own mail client? I think of how many users can connect or similar?

**Comment by andryyy** [comment]
Depends on which interface they use. ActiveSync => yes, it will affect them. IMAP/SMTP => no.

**Comment by petarkozic** [comment]
@andryyy 
Thank you for your reply.
One more question, how can I prevent that this file not be overwritten with the update from git?

**Comment by andryyy** [comment]
You can check git logs, merge with strategy "ours" (see update.sh parameters) or set +i on that file.

**Comment by petarkozic** [comment]
Can someone check this comment from netdata dev which you have in issue link in the first post?

> VPS not having the issue as often may just be that they tend to be more 'purpose specific', and therefore don't have as many UID's already assigned.
> 
> As far as the issue of the UID's, that should be reported upstream. Hard-coding them like that is asking for trouble, not just with accounting like this, but with system security (duplicate UID's mean that you run the risk of access controls not being applied correctly), and the security aspect is what should be explicitly called out in the bug report because that's a bigger issue for the upstream developers (possibly mention the accounting issues as an aside).
> 
> There's not much we can do as a fix that will work reliably. On a per-instance basis, one approach would be to set up everything except Netdata, and then go through the process list and add entries to /etc/passwd for all UID's that don't already have entries. We're using standard methods to create the Netdata user, so it won't use a UID that's already listed in /etc/passwd.

**Comment by petarkozic** [comment]
@andryyy 
Decreased Sogo workers resolve problem temporary. Now again after a few days more netdata on mailcow server use more than 700MB RAM.

As you can see here on git issue mailcow have a problem because of use system UID, looks like hardcoded UID.
As you can see on my server that is Sogo use netdata UID, but on test Centos server mailcow use Policykit.
Can someone check this because this can be a high-security issue?
https://github.com/netdata/netdata/issues/5601
Thank you.

**Comment by K2rool** [comment]
The issue with Mailcow running services with the same uid as other user on the system isn't really just a Mailcow issue basically even docker image I've used over years has that issue unfortunate it's a side effect you have to live with when using docker.

**Comment by petarkozic** [comment]
That isn't issue. Docker shares UID with host machine because of works on the same kernel. I think here mailcow need to add users on the host during the installation and later can use that uid for docker also.

**Comment by mkuron** [comment]
> As you can see here on git issue mailcow have a problem because of use system UID, looks like hardcoded UID.
>As you can see on my server that is Sogo use netdata UID, but on test Centos server mailcow use Policykit.

This is not a problem. netdata and SOGo are not dealing with each other in any way. `top`, `ps`, etc. are simply reporting incorrect user names when you run Docker containers. If you want to see the correct user names, you need to run these commands inside the Docker container. From the host's perspective, the `sogod` processes may seem to be running as the `netdata` user's UID, but since one is running inside a container and the other one isn't, there is no way for the `netdata` user to interact with the `sogod` processes or the `sogod` processes to make use of the `netdata` user's permissions.

**Comment by petarkozic** [comment]
You are seriously close this big issue.
Then you don't understand the concept of layered security or you don't care about it.
This is a seriously big security and operations issue.

**Comment by mkuron** [comment]
Then I still don't see what the problem is. Please have a look at https://en.m.wikipedia.org/wiki/Linux_namespaces . These identical UIDs are not actually referring to the same user because they are in different namespaces.

There is no way from within a Docker container to detect which UIDs are already in use on the host, so collision-free UIDs are impossible in a Docker environment.

I tried to understand the discussion in the netdata issue tracker, but didn't get what the actual problem is.

**Comment by mamair** [comment]
Whats the solution to avoid that such a UID used by containers use the same UID as regulary users and use their permissions? I found UID 999, 401, 402 and 82 on my server. Would it make problems, if I add users with this UIDs to prevent such collisions of permission? When I discoverd the UIDs without unsernames I thought I was hacked or something was misconfigured ...

**Comment by mkuron** [comment]
> use their permissions

These colliding UIDs do not actually transfer any permissions. So this is mostly a cosmetic issue due to top, ps, etc. not supporting namespaces.

> I add users with this UIDs to prevent such collisions

We don't guarantee that they won't change. Of course, if they did change we might get permission issues on the Docker volumes. Also, different containers might use the same UID, so you can't give each container a distinct user name.
