### ISSUE TITLE
docker-compose issue regarding MAILDIR_SUB

### ISSUE THREAD

**Issue by CFuchs174** [mailcow/mailcow-dockerized#2452]
I tried to setup a new server for testing purposes using docker-compose as explained in the documentation with the newest version. I saw in the GIT history that parameter "MAILDIR_SUB" was added recently. However, it seems to cause problems when setting up a new server:

```
ERROR: Invalid interpolation format for "environment" option in service "dovecot-mailcow": "MAILDIR_SUB=${MAILDIR_SUB:-}
```

Any ideas on how to solve the issue? Thanks!

**Comment by andryyy** [comment]
Cannot replicate with latest compose. We cannot help if you guys skip the issue template, sorry.

**Comment by CFuchs174** [comment]
I have tried the setup on a fresh installation of the server and it worked... Seems to have been an issue with the old machine (despite of the latest docker-compose). Sorry for the inconvenience.

**Comment by omani** [comment]
> I have tried the setup on a fresh installation of the server and it worked... Seems to have been an issue with the old machine (despite of the latest docker-compose). Sorry for the inconvenience.

for those who find this issue when they search for this problem.
it can also happen when you run docker-compose without sudo rights!

**Comment by nathfreder** [comment]
@omani Hmm... that didn't seem to work for me.

**Comment by ghost** [comment]
you're using an old version of `docker-compose`. the new syntax was added in version `1.19.0` and older versions can't understand it.

how to update `docker-compose`: https://stackoverflow.com/a/49839172

**Comment by andryyy** [comment]
Which compose version?

**Comment by ghost** [comment]
well... when I was having the issue, I was on `1.17.0` but I upgraded to `1.24.1` and it started working
