### ISSUE TITLE
Unraid template(s)

### ISSUE THREAD

**Issue by angdigi** [mailcow/mailcow-dockerized#2454]
Hi, 

First, thank you, Andre, for your hard work on this!

I'd like to use this on my unraid server. Would you be willing to create a template for unraid?

Let me know if need anything from me.

Thanks,
Angelo

**Comment by Braintelligence** [comment]
Looks like a complete niche to me. What's the use-case of running a mail appliance on unRAID? What's the problem in creating a VM on unRAID and running docker-compose in there? Why do you need an extra "template" and why should André or the community do this for you?

Does anyone even run unRAID on anything else than a home server? You do know that you need a static IP for a proper mail server?

**Comment by extremeshok** [comment]
you do not need a template for unraid.
create an ubuntu vm,  setup the vm , run mailcow
![unraid net](https://user-images.githubusercontent.com/5957328/54610566-f1c2cc00-4a5d-11e9-9148-70a8a0614c98.png)

**Comment by extremeshok** [comment]
Got a few corporates running unraid for server consolidation. Like a bunch of legacy stuff on mismatched drives. Works perfectly.

Proxmox needs/wants enterprise hardware.

Unraid caters more to use what you have and its easier for client to manage on site.
Unraid is far far safer than a qnap / readynas /synology /thecus, their controller goes with their 3rd party "raid" and your data is nuked..

**Comment by Braintelligence** [comment]
I see. That makes sense.

**Comment by angdigi** [comment]
> Looks like a complete niche to me. What's the use-case of running a mail appliance on unRAID? What's the problem in creating a VM on unRAID and running docker-compose in there? Why do you need an extra "template" and why should André or the community do this for you?
> 
> Does anyone even run unRAID on anything else than a home server? You do know that you need a static IP for a proper mail server?

Can't aruge that unraid is niche, I suppose. I run all of my services on unraid and wanted to add mailcow to the list.

unraid utilizes dockerman, which is a gui front-end for docker management. I just wanted to continue to use that instead of running mailcow in a vm, which would be separate from all of my other containers.

I just run unraid on a home server :/ I have ddns setup so I thought that would suffice.

**Comment by Braintelligence** [comment]
Ddns won't work for many Mailservers who strictly don't accept mails coming from Mailservers without static IP.

**Comment by extremeshok** [comment]
a dedicated IP via a GRE/IPIP/TINC tunnel would do wonders, but this is way out of scope for this post ;P

**Comment by angdigi** [comment]
I can cross that bridge when I get there I suppose.

We can close this then I guess. Just thought I'd ask for assistance in getting this up and running on unraid without using a VM.

**Comment by Braintelligence** [comment]
I don't think anyone will do the work of creating an XML template for you if all you have to do is install a linux server on a VM and do some well-documented steps.
There are some upsides having mailcow in its own VM as well; very easy backup-strategies - just backup the whole VM 😀.

Ok, I'm gonna close this now per your permission.

**Comment by angdigi** [comment]
How can I run the post-hook script if the mailcow-docker is in a VM and the reverse proxy is on the host? Specifically referring to the docker commands to restart the specified containers..

`#!/bin/bash
cp /etc/letsencrypt/live/my.domain.tld/fullchain.pem /opt/mailcow-dockerized/data/assets/ssl/cert.pem
cp /etc/letsencrypt/live/my.domain.tld/privkey.pem /opt/mailcow-dockerized/data/assets/ssl/key.pem
# Either restart...
#postfix_c=$(docker ps -qaf name=postfix-mailcow)
#dovecot_c=$(docker ps -qaf name=dovecot-mailcow)
#nginx_c=$(docker ps -qaf name=nginx-mailcow)
#docker restart ${postfix_c} ${dovecot_c} ${nginx_c}
# ...or reload:
docker exec $(docker ps -qaf name=postfix-mailcow) postfix reload
docker exec $(docker ps -qaf name=nginx-mailcow) nginx -s reload
docker exec $(docker ps -qaf name=dovecot-mailcow) dovecot reload`
