### ISSUE TITLE
mysql-mailcow not found

### ISSUE THREAD

**Issue by leon88com** [mailcow/mailcow-dockerized#2456]
I'm getting following error:

/opt/mailcow-dockerized# docker-compose pull
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Pulling memcached-mailcow ... done
Pulling solr-mailcow      ... done
Pulling mysql-mailcow     ... pulling from library/mariadb
Pulling postfix-mailcow   ... done
Pulling sogo-mailcow      ... done
Pulling dockerapi-mailcow ... done
Pulling dovecot-mailcow   ... done
Pulling redis-mailcow     ... done
Pulling watchdog-mailcow  ... done
Pulling php-fpm-mailcow   ... done
Pulling netfilter-mailcow ... done
Pulling nginx-mailcow     ... done
Pulling rspamd-mailcow    ... done
Pulling clamd-mailcow     ... done
Pulling acme-mailcow      ... done
Pulling unbound-mailcow   ... done
Pulling ipv6nat-mailcow   ... done

ERROR: for mysql-mailcow  no matching manifest for unknown in the manifest list entries
ERROR: no matching manifest for unknown in the manifest list entries

Can you please help to solve the issue?

**Comment by zkryakgul** [comment]
Can you try use update.sh instead of pulling images manually?
