### ISSUE TITLE
Rspamd fails to block forged local recipients

### ISSUE THREAD

**Issue by lavdnone** [mailcow/mailcow-dockerized#2458]
This fresh wave of spam with forging local emails is passing and passing through Rspamd.
Is there a tweak to block when local recipient is in FORGED_SENDER or FROM_NEQ_ENVFROM like in example below. It is clearly an issue.

3/20/2019, 9:15:10 AM	**pkozely@fl.com**	**pkozely@fl.com**	soft reject	[ 11.35 / 15 ]	unknown
IP address	74.220.217.46
Subject	pkozely
Symbols	HAS_X_SOURCE (0)
FROM_NEQ_ENVFROM (0) [**pkozely@fl.com**,assistant@alkhair-coffee.com]
FORGED_SENDER (0.3) [**pkozely@fl.com**,assistant@alkhair-coffee.com]
MIME_BASE64_TEXT (0.1)
TO_EQ_FROM (0)
RECEIVED_SPAMHAUS_PBL (0) [106.153.79.114.zen.spamhaus.org : 127.0.0.10]
MIME_TRACE (0) [0:+,1:+,2:+]
RCVD_TLS_LAST (0)
FROM_NO_DN (0)
FORGED_MUA_MOZILLA_MAIL_MSGID_UNKNOWN (2.5)
TO_DN_NONE (0)
TO_MATCH_ENVRCPT_ALL (0)
HAS_ORG_HEADER (0)
RCVD_COUNT_THREE (0) [4]
MX_INVALID (0.5) [cached]
DKIM_TRACE (0) [alkhair-coffee.com:-]
RCVD_VIA_SMTP_AUTH (0)
RCVD_IN_DNSWL_NONE (0) [46.217.220.74.list.dnswl.org : 127.0.5.0]
RECEIVED_SPAMHAUS_CSS (1) [106.153.79.114.zen.spamhaus.org : 127.0.0.3]
GREYLIST (0) [greylisted,Wed, 20 Mar 2019 13:19:30 GMT,body]
PREVIOUSLY_DELIVERED (0) [pkozely@fl.com]
ARC_NA (0)
DMARC_NA (0) [fl.com]
RECEIVED_BLOCKLISTDE (3) [106.153.79.114.bl.blocklist.de]
HAS_X_ANTIABUSE (0)
R_DKIM_REJECT (1) [alkhair-coffee.com:s=default]
R_SPF_SOFTFAIL (0) [~all]
ASN (0) [asn:46606, ipnet:74.220.192.0/19, country:US]
RCPT_COUNT_ONE (0) [1]
RCPT_MAILCOW_DOMAIN (0) [fl.com]
RECEIVED_SPAMHAUS_XBL (3) [106.153.79.114.zen.spamhaus.org : 127.0.0.4]
MIME_GOOD (-0.1) [multipart/related,multipart/alternative,text/plain]
IP_SCORE (0.05382) [country: US(0.27)]

**Comment by andryyy** [comment]
Set your SPF to "-all", set higher scores for a combination of DKIM and SPF failures, increase blacklist records etc. Your mail example scored very high, it was soft rejected and put into junk. If that's not enough, I'd recommend to increase the R_DKIM_REJECT score or even force a reject with a combination of any SPF fail + any DKIM fail. Spamhaus should probably score higher, too. But I don't think you should reject every Spamhaus-listed sender.

Feel free to submit config changes and/or open an issue @ Rspamd, if you feel like Rspamd is not working correctly. Iirc those mails are images with text, it should be easy to detect them as mostly-text. You can also try to enable debugging for fuzzy and check wether a hash is generated for this/any image.

It is not an issue of mine to configure other peoples Rspamd. :/ All components are open-source, you are free to do whatever you like.

**Comment by K2rool** [comment]
You can do want Andre suggested set your SPF to -all and tweak Rspamd score a bit but actually the defaut scores work fine most of the time anyway, technically Rspamd did the job it meant to do it did not rejected it but the mail didn't ended up in your inbox it ending up in Junk.

**Comment by lavdnone** [comment]
Point here is that it thinks that email is sent from legitimate domain **alkhair-coffee.com** with totally fine SPF from user pkozely@fl.com,assistant@alkhair-coffee.com
Guess is to somehow make rspamd spot that sender has local user as part of SENDER
Might be the question for rspamd guys as a bug

FROM_NEQ_ENVFROM (0) [**pkozely@fl.com,assistant@alkhair-coffee.com**]
FORGED_SENDER (0.3) [pkozely@fl.com,assistant@alkhair-coffee.com]

R_DKIM_REJECT (1) [**alkhair-coffee.com**:s=default]
R_SPF_SOFTFAIL (0) [~all]

**Comment by lavdnone** [comment]
Guess the guys from rspamd answered it. All users (with domains) need somehow end up in multimap config so incoming email fields can be checked for forgery, hopefully with some divination like pkozely@fl.com against pkozely@fI.com (in first case f followed by "l" and in second by capital "i")

Funny thing is that Microsoft 365 mail allows those emails though as well.

**Comment by lavdnone** [comment]
I see there was some attempt to address it in the past to have users in redis

from data/conf/rspamd/local.d/multimap.conf

    #SPOOFED_SENDER {
    #  type = "rcpt";
    #  filter = "email:domain:tld";
    #  map = "redis://DOMAIN_MAP";
    #  require_symbols = "AUTH_NA | !RCVD_VIA_SMTP_AUTH";
    #  symbols_set = ["SPOOFED_SENDER"];
    #}

**Comment by andryyy** [comment]
You have all options available. We even have a mailcow domain symbol you can work with. Just add a composite rule for a mailcow domain + dkim/spf failure or something like this. 

This mail was marked as junk though, so I don’t really understand the problem. :( I guess you want it rejected?

**Comment by lavdnone** [comment]
It didn't go to junk for some reason
Comparing text FROM to all users will be a hard/slow task.

If someone can give example when username without domain part to have @ or FORGED_SENDER symbol might be assigned to legitimate email ...:

data/conf/rspamd/local.d/metrics.conf

    symbol "FORGED_SENDER" {
        score = 12.0;
    }

data/conf/rspamd/custom/email_forge.map

    /.*@.*@.*\..*$/

data/conf/rspamd/local.d/multimap.conf

    #Refuse bad address with @ in the username of email address
    FROM_REGEX {
        type = "from";
        map = [ "/etc/rspamd/custom/email_forge.map", ];
        action = "reject";
        prefilter = true;
        filter = "email:addr";
        symbol = "FROM_BADUSERS";
        description = "From user with AT symbol in name";
        regexp = true;
    }

For example this one didn't end up in spam:

    IP address	1.6.36.80
    Subject	serban
    Symbols	FROM_NEQ_ENVFROM (0) [serban@fl.com,desri@brlp.in]
    RCVD_COUNT_FIVE (0) [6]
    FORGED_SENDER (0.3) [serban@fl.com,desri@brlp.in]
    MX_GOOD (-0.01) [nmail.brlp.in]
    RCPT_MAILCOW_DOMAIN (0) [fl.com]
    TO_EQ_FROM (0)
    R_SPF_ALLOW (-0.2) [+mx]
    MIME_TRACE (0) [0:+,1:+,2:+]
    PREVIOUSLY_DELIVERED (0) [serban@fl.com]
    RCVD_TLS_LAST (0)
    ARC_NA (0)
    FROM_NO_DN (0)
    FORGED_MUA_MOZILLA_MAIL_MSGID_UNKNOWN (2.5)
    HAS_ORG_HEADER (0)
    R_DKIM_NA (0)
    MIME_GOOD (-0.1) [multipart/related,multipart/alternative,text/plain]
    TO_DN_NONE (0)
    RCPT_COUNT_ONE (0) [1]
    MIME_BASE64_TEXT (0.1)
    TO_MATCH_ENVRCPT_ALL (0)
    DMARC_DNSFAIL (0) [fl.com : query timed out]
    ASN (0) [asn:9583, ipnet:1.6.36.0/22, country:IN]

**Comment by lavdnone** [comment]
looks like FORGED_SENDER is useful thing - end up blocking aws alerts
(SPF failed as it was relayed through Microsoft smtp)

Maybe we can force it check SPF for all forged senders  From previous example FORGED_SENDER (0.3) [pkozely@fl.com,assistant@alkhair-coffee.com] SPF is good for alkhair-coffee.com but will fail for fl.com


    IP address	40.107.68.42
    Subject	ALARM: "drive0up-awsroute53-aa124337-0c61-44fd-b6f4-1f5cfd393f4-Low-He..." in US East (N. Virginia)
    Symbols	RCVD_COUNT_THREE (0) [4]
    FROM_NEQ_ENVFROM (0) [no-reply@sns.amazonaws.com,01000169b27d83fb-f7c45d05-1cbc-438d-88d2-a4c8648d34e5-000000@amazonses.com]
    DKIM_TRACE (0) [PL1ORG.onmicrosoft.com:+,sns.amazonaws.com:+,amazonses.com:+]
    RCPT_MAILCOW_DOMAIN (0) [mc.com]
    R_SPF_FAIL (10) [-all]
    MIME_TRACE (0) [0:+]
    BAYES_HAM (-3.424119) [85.06%]
    RCVD_TLS_LAST (0)
    ARC_NA (0)
    DMARC_NA (0) [amazonaws.com]
    R_DKIM_ALLOW (-0.2) [PL1ORG.onmicrosoft.com:s=selector1-PL1ORG-onmicrosoft-com,sns.amazonaws.com:s=nphhk4jzf3x47mony543xmwpeh5gx,amazonses.com:s=6gbrjpgwjskckoa6a5fwqkn67xbtw]
    FROM_HAS_DN (0)
    MIME_GOOD (-0.1) [text/plain]
    RCPT_COUNT_ONE (0) [1]
    TO_DN_NONE (0)
    RCVD_IN_DNSWL_NONE (0) [42.68.107.40.list.dnswl.org : 127.0.3.0]
    FORGED_SENDER (12) [no-reply@sns.amazonaws.com,01000169b27d83fb-f7c45d05-1cbc-438-88d2-a4c8648d34e5-000000@amazonses.com]
    FORGED_RECIPIENTS (1) [vlad@tk.nyc,vlad@mc.com]
    Msg size	7.9 KiB
    Scan time	5.010 / 0.018
    ID	01000169b27d83fb-f7c45d05-1cbc-438d-88d2-a4c8648d34e5-000000@email.amazonses.com
