### ISSUE TITLE
Unable to create a public Calendar

### ISSUE THREAD

**Issue by Xadagain** [mailcow/mailcow-dockerized#2460]
Hello there,

i have a problem creating public Calendars/address books for my company.
I'm only allowed to enable access for specific users.
I set the public-ACL in mailcow.conf to allow and i checked if i have the:
 SOGoEnablePublicAccess = YES; Flag in sogo.conf.

but nothing helps.
But i think it worked before i upgraded mailcow.
Was there a change about that? Or what can cause this problem?

**Comment by andryyy** [comment]
Did you run down and up -d after setting public ACL?

Can you please provide exact steps to reproduce? Best would be with screenshots for us to see where you expect what to show up etc.

**Comment by Xadagain** [comment]
@andryyy thank you very much. I did only docker-compose restart. down and up -d helped.
