### ISSUE TITLE
Netfilter periodical restart

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#2466]
Hi,
  I would like to ask if it is normal behavior that this CRIT error occurs every 5 minutes?

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/16578737/54853800-2601eb00-4cf1-11e9-8aeb-85d416b37e57.png">

  Kind regards,
Zoltan

**Comment by christianbur** [comment]
I have the same problem with two instances.

**Comment by andryyy** [comment]
You should check what changes the FORWARD chain order then.

**Comment by christianbur** [comment]
Okay, problem analyzed. 
I think it's normal for it to happen. 
Whenever a Conatiner is restarted and a "networks:" (e.g. br-50cc8bb1291c)  is created in docker-compose.yml it should happen. 

```
# iptables -vL FORWARD -t filter 
Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  868  376K DOCKER-USER  all  --  any    any     anywhere             anywhere            
  583  296K DOCKER-ISOLATION-STAGE-1  all  --  any    any     anywhere             anywhere            
    0     0 ACCEPT     all  --  any    br-50cc8bb1291c  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  any    br-50cc8bb1291c  anywhere             anywhere            
    0     0 ACCEPT     all  --  br-50cc8bb1291c !br-50cc8bb1291c  anywhere             anywhere            
    0     0 ACCEPT     all  --  br-50cc8bb1291c br-50cc8bb1291c  anywhere             anywhere            
 2886  800K MAILCOW    all  --  any    any     anywhere             anywhere            
    0     0 ACCEPT     all  --  any    br-e61bd491a13c  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  any    br-e61bd491a13c  anywhere             anywhere    
```        

Netfilter recognized that the MAILCOW chain is not at position 0 and restarts the container.

https://github.com/mailcow/mailcow-dockerized/blob/40500ae5b98a239f745d842fe9da38be574e76d6/data/Dockerfiles/netfilter/server.py#L86

**Comment by beckzg** [comment]
In my case it looks like not the same, because the services are running more then 2 days, except the rspamd (I've no idea why was restarted) and still the netfilter has that crit error:

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/16578737/54883676-620b8c00-4e68-11e9-8260-86080baafc5b.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/16578737/54883696-a72fbe00-4e68-11e9-9208-9d7974607713.png">

**Comment by andryyy** [comment]
And which rule/s are put before FORWARD in your case?

**Comment by beckzg** [comment]
Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
8414K 7850M MAILCOW    all  --  any    any     anywhere             anywhere
8415K 7850M DOCKER-USER  all  --  any    any     anywhere             anywhere
8415K 7850M DOCKER-ISOLATION-STAGE-1  all  --  any    any     anywhere             anywhere
6541K 7727M ACCEPT     all  --  any    br-b7d63470dbf0  anywhere             anywhere             ctstate RELATED,ESTABLISHED
74929 4568K DOCKER     all  --  any    br-b7d63470dbf0  anywhere             anywhere
1799K  118M ACCEPT     all  --  br-b7d63470dbf0 !br-b7d63470dbf0  anywhere             anywhere
74070 4521K ACCEPT     all  --  br-b7d63470dbf0 br-b7d63470dbf0  anywhere             anywhere
    0     0 ACCEPT     all  --  any    docker0  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  any    docker0  anywhere             anywhere
    0     0 ACCEPT     all  --  docker0 !docker0  anywhere             anywhere
    0     0 ACCEPT     all  --  docker0 docker0  anywhere             anywhere

**Comment by andryyy** [comment]
That's what it looks like, when it is in correct order.

Edit: Can you try to fetch the list, when it fails? Or fetch it every n seconds?

**Comment by beckzg** [comment]
I've two separate instance at two different site, both fresh new installs on Ubuntu 18.04 and the same problem with netfilter.

Do you mean the iptables list?

**Comment by andryyy** [comment]
So both share the same problem. It doesn’t mean that mailcow is broken.

I use 18.04 for most of my installations. This means nothing, sorry. 

You need to check when MAILCOW is actually not the first rule in the FORWARD chain.

**Comment by beckzg** [comment]
So this should be enough? And if we know the date what's the next step?

while (true); do date > /tmp/debug.log; iptables -vL FORWARD -t filter > /tmp/debug.log; sleep 1; done

**Comment by andryyy** [comment]
Just check which rules put themselves in front of MAILCOW.

Also post “docker ps -af” and the docker version, please.
