### ISSUE TITLE
Alias Problem

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2468]
Ein freundliches Moin Moin in die Runde...

Ich komme mal mit einem etwas speziellerem Problem.

Für eine Pizza Bestellseite benötigt der Laden 2 Bon-Ausdrucke. Daher habe ich bisher (beim alten Anbieter) über die info@ einen Alias angelegt und dem Bestellsystem gesagt, dass es an beide die selbe E-Mail (den Bon) schicken soll. Es kommen also 2 gleiche E-Mails an, welche dann automatisch von Thunderbird gedruckt werden... 2 Bons halt.

Mit Mailcow funktioniert dies leider nicht. Wenn ich eine E-Mail normal an den Alias sende kommt diese auch ohne Probleme bei info@ an.
Vom Bestellsystem aus, wird aber nur eine Empfangen. Es ist so als wenn Mailcow erkennt "2 gleiche Mails... einmal über info@ und einmal über den Alias.... lassen wir den Alias mal verschwinden".

Ich habe das jetzt erstmal mit einem 2. Postfach gelöst und den Alias weggelassen. So funktioniert es ja auch...

Ich hoffe Ihr versteht mein "Problem" und habt vielleicht einen Tipp wo ich falsch denke... :smile:

**Comment by tobias992** [comment]
Als kleiner Hinweis noch:
Vom Bestellsystem werden die E-Mails von der info@ über SMTP versandt.
Vielleicht kann sich das Postfach nicht selber was an den Alias schicken...

**Comment by andryyy** [comment]
Ist das ein Bug oder ein Feature Request? :)

Es lässt keine Mails verschwinden. Wird eine Mail an die Mailbox und eine an den Alias gesendet, landen auch zwei im Postfach.
Sowas ist etwas für das Forum, das IRC oder das Ticket-System (Support Paket).

In jedem Fall solltest du, wenn du das Issue Template schon löschst, wenigstens irgendwelche Logs vom Absender (bestenfalls ein maillog) und die Postfix Logs der mailcow anhängen.

**Comment by tobias992** [comment]
Wenn es funktionieren sollte handelt es sich um ein Bug.

In Postfix konnte ich lediglich folgendes finden:
9AFA363060: to=<info@domain-a.de>, orig_to=<bon2@domain-a.de>, relay=dovecot[xxxx:xxxx:6c63:6f77::a]:24, delay=0.16, delays=0.12/0.01/0.01/0.02, dsn=2.0.0, status=sent (250 2.0.0 <info@domain-a.de> MzzeLZ0ullxxAQAA4VSLVA Saved)

In Dovecot folgendes:
  | lmtp(info@domain-a.de)<369><MzzeLZ0ullxxAQAA4VSLVA>:  sieve:  msgid=<5131e75cb8094a2f08c4387a9c8eb2a3@domain-a.de>: stored  mail into mailbox 'INBOX'
-- | --

Der Rest sind connects und disconnects.

**Comment by tobias992** [comment]
Habe es eben auch nochmal selbst getestet:

Eine Nachricht über smtp von info@domain.de an info@domain.de und info-alias@domain.de gesendet.
Es kommt nur eine Nachricht im Postfach an.

**Comment by andryyy** [comment]
Dann sollten alle Logs vollständig von beiden Servern gepostet werden. Auch das Template nicht einfach löschen oder ignorieren. 

Kann das Problem (so) nicht nachvollziehen.

**Comment by andryyy** [comment]
Dann mach es über BCC Maps.

**Comment by tobias992** [comment]
"von beiden Servern"... ? Ich hab nur einen.

Über BCC funktioniert es auch nicht.

Kannst du denn an dich selber eine Mail plus an den Alias senden und es werden 2 Nachrichten im Posteingang angezeigt? (also an dich selber plus an den eigenen Alias)

**Comment by evilstiefel** [comment]
Hey, ich kann dein Problem nachvollziehen. Wenn auf meinem Postfix eine eingehende Mail in den Delivery Queue gelegt wird, kriegt sie eine ID zugewiesen. Dann wird auch nur eine Kopie an den Empfänger ausgeliefert, auch wenn der Absender explizit zwei Adressen eingetragen hat (und eine per Alias auf den gleichen Empfänger zeigt).

Allerdings erwarte ich es auch genau so - wenn auch dein Anwendungsfall dadurch natürlich nur über zwei Mailboxen unterstützt wird.

**Comment by andryyy** [comment]
Einfach zwei Mails senden. Einmal dahin, einmal dahin. 

BCC könnte klappen, aber bin da eher unsicher. Erste Methode funktioniert auf jeden Fall. 

Und nein, das ist kein Bug.

**Comment by tobias992** [comment]
Das System versendet leider nur eine Mail, wo man lediglich die E-Mail Adressen eingeben kann.

Aber jetzt funktioniert es ja auch... also alles bestens.

Hatte mich halt nur gewundert, weil es beim vorherigen Anbieter funktioniert hatte...
