### ISSUE TITLE
[Question] Trash settings

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#247]
Hi everyone!
Is there some setting regarding automatic deletion of trash folder contents after some time?

**Comment by broedli** [comment]
Currently there is no such setting inside of mailcow and as far as I know SOGo doesn't provide it as well. You could however try to do this with the dovecot plugin Expire: https://wiki2.dovecot.org/Plugins/Expire

**Comment by Braintelligence** [comment]
Thanks for answering! Actually I really want the trash bin to not cleanse by itself. So this is the ideal setting for me! 😸

**Comment by andryyy** [comment]
FYI: This can be done with doveadm like this...

```
# For all and older than 30 days
docker-compose exec dovecot-mailcow doveadm expunge -A mailbox Trash savedbefore 30d
# For a single user + older than 60 days
docker-compose exec dovecot-mailcow doveadm expunge -u me@example.org mailbox Trash savedbefore 30d
```

If you run these in a script, you may need to run `docker-compose exec -T xyz`.
