### ISSUE TITLE
Missing Email, Can Admin Find the Sender?

### ISSUE THREAD

**Issue by ssm3e30** [mailcow/mailcow-dockerized#2472]
**Describe the bug, try to make it reproducible**
A user reported that an email they had went missing after marking it unread. If thats true or not I don't know, but it made me think of a question. Can I as the admin track down the sender, via a log or some other way? We know the date the email was received and what account it was sent to, so we would just like to find the email address it came from to reply.

**System information and quick debugging**
General logs:
Let me know which log to post if applicable. 

Further information (where applicable):
 The latest image running docker on a Ubuntu installation.

**Comment by andryyy** [comment]
As long as the postfix container has not been restarted, you can grep through docker-compose logs postfix-mailcow 

If you want persistent logs, you may want to use the syslog driver in Docker or whatever other driver. :)

**Comment by ssm3e30** [comment]
Thanks @andryyy ! Quick response and got me right in the direction I needed. 

The number after the line identifying it as a postfix log, like  0A3B37E0ED, I am assuming identifies it to the related lines. So any log line with the same number is related to the same message?
