### ISSUE TITLE
mailcowdockerized_nginx-mailcow: unexpected end of parameter, expecting ";" in command line (fixed)

### ISSUE THREAD

**Issue by homlett** [mailcow/mailcow-dockerized#2474]
Hello there,

`mailcowdockerized_nginx-mailcow` is blocked in a boot loop... The logs are saying every 60 seconds:
```
2019/03/27 21:46:33 [emerg] 1#1: unexpected end of parameter, expecting ";" in command line,
nginx: [emerg] unexpected end of parameter, expecting ";" in command line
```
Also, the configured domain names don't respond since they are stuck in a 302 redirect loop.

Everything was working great before. Any ideas?

**Comment by andryyy** [comment]
Delete any `docker-compose.override.yml` and run `git checkout origin/master docker-compose.yml`. Does it work?

**Comment by homlett** [comment]
Thanks for your prompt reply! An `./update.sh` fixed my issue. More or less the same thing you suggested I guess, right? Anyway, thank you again!
