### ISSUE TITLE
Dockerapi Mysql Upgrade  Process fail.

### ISSUE THREAD

**Issue by zkryakgul** [mailcow/mailcow-dockerized#2475]
Dockerapi mysql upgrade process fails because of socket error. And if you make a fresh install db tables are not created. I call the api manually for the see results with this command:
`curl --insecure -XPOST https://dockerapi/containers/${CONTAINER_ID}/exec -d '{"cmd":"system", "task":"mysql_upgrade"}' -H 'Content-type: application/json'`

After that api stuck and not responding. So i added `tty=True, stream=True` parameters to the exec_run  command for see the output of the error:
`
sql_shell = container.exec_run(["/bin/bash"], stdin=True, socket=False, user='mysql', tty=True, stream=True)
`

and it's return:

`
{"msg":"'generator' object has no attribute 'sendall'","type":"danger"}
`

**Comment by andryyy** [comment]
I cannot reproduce this.

I remember you played with the DockerAPI on Py3 stuff, I guess that's the problem. :-/
The "sendall" error is what I definitely remember as Py3 error.

**Comment by zkryakgul** [comment]
i fix this i delete image restart my docker deamon rebuild image and up container. I dont know how but it works now :smiley:
