### ISSUE TITLE
Problem adding forwarding host ("Invalid host specified")

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#2479]
**Describe the bug, try to make it reproducible**
(All on a fresh mailcow instance, today installed)
I am trying to add web.de and gmx.net as forwarding hosts via the option in the mailcow UI.

*Steps to reproduce:*
- Go to mailcow UI, "Configuration & Details", tab "Configuration"
- Enter `mout.gmx.net` in the host field under "Add forwarding host"
- Select spam filter to be active
- Click "Add" button

*Expected result:*
IPs of mout.gmx.net added to forwarding host list

*Actual result:*
About 10 seconds nothing ("Please wait..."), then a red message stating "Invalid host specified: mout.gmx.net"

**System information and quick debugging**
General logs:
- `docker-compose logs -f` doesn't contain any error message while executing the request in the UI
- the "mailcow UI" log in the "Logs" tab contains no further information
![Screenshot of the mailcow UI log](https://user-images.githubusercontent.com/24863329/55281165-c4fd9700-5330-11e9-800e-df3a17e5a1ba.png)

**Further information (where applicable):**
 - *Your OS (is Apparmor or SELinux active?):*
Ubuntu 18.04.2 LTS, Kernel  4.15.0-46
uname -a: `Linux <hostname> 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Apparmor seems to be running, no SELinux

 - *Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)*
OpenStack & KVM (OVH VPS)

 - *Your server/VM specifications (Memory, CPU Cores)*
OVH VPS Cloud RAM 3: "4 vCores; >2Ghz; 24GB RAM; 100GB HDD"

 - *Don't try to run mailcow on a Synology or QNAP NAS, do you?*
Nope.

 - *Docker and Docker Compose versions*
`Docker version 18.09.4, build d14af54266`
`docker-compose version 1.24.0, build 0aa59064`
(installed today, 30 March 2019)

 - *Output of `git diff origin/master`, any other changes to the code?*
Only rspamd password

 - *All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `*
--> docker-ipv6nat is constantly restarting (at least docker-compose ps says so)
```
ipv6nat-mailcow_1    | 2019/03/30 20:32:52 running [/sbin/iptables -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER --wait]: exit status 2: iptables v1.6.2: Couldn't load target 'DOCKER':No such file or directory
ipv6nat-mailcow_1    | 
ipv6nat-mailcow_1    | Try `iptables -h' or 'iptables --help' for more information.
```
I do have firehol installed, but completely disabled (flushed all rules; firehol stop)
iptables command output: https://pastebin.com/Q9z5DgQH

 - *Reverse proxy? If you think this problem is related to your reverse proxy, please post your configuration.*
Yes, via reverse proxy, but I don't think this is the issue (everything else is working perfectly fine and I am using the example configuration for nginx)

 - *Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?*
Oh this is interesting:
```
root@<hostname>:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
;; connection timed out; no servers could be reached

root@<hostname>:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
;; connection timed out; no servers could be reached
```

How should I progress further?
Thanks for your time and effort,
Felix

**Comment by andryyy** [comment]
Nice, someone actually used the template. :-D

You also purged the Docker iptables rules. Try (with firehol is still disabled) to run `docker-compose down; systemctl restart docker; docker-compose up -d`

**Comment by mindsolve** [comment]
I am feeling so dumb right now :D 
Your solution fixed it. It is working now...

Maybe we can learn from this and make debugging a little easier (in the future):
Is it possible to check for working internet access in the image?
Maybe display a warning in the UI or just check this in the resolution process, so that instead of "invalid host" there is a more specific error message ("cannot connect to dns server", "resolution timed out", "no internet access").

Anyway, thank you so much for solving my problem... Should I leave it open for a few days for the suggestion, or should I open a feature request for it?

**Comment by andryyy** [comment]
It's absolutly okay, if you don't work with Docker everyday.

I think that's "just part of Docker". If you mess with and break Docker, we cannot help. They have docs explaining the need for those tables and various other things, that need to work.
