### ISSUE TITLE
Error with initialize database after update

### ISSUE THREAD

**Issue by rafix1989** [mailcow/mailcow-dockerized#248]
hi after update to latest version i have this error
Database initialisation failed: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'grouped_mail_aliases' already exists 

I've try download it again and rebuild containers but nothing help.
Does anybody may know the answer what should i do to repair it ??

**Comment by andryyy** [comment]
I wonder why that would fail.

What happens when you delete it manually? =>

```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "drop view if exists grouped_mail_aliases;delete from versions"
```

**Comment by rafix1989** [comment]
... and nothing happen. 
Commands was applied correctly (without errors), but still i have this notification.

![obraz](https://cloud.githubusercontent.com/assets/805762/25776188/0f57af8e-32b8-11e7-9032-caf9808d44a4.png)

**Comment by afzalarsalan** [comment]
Unfortunately I have this same issue and applying the above command also does nothing in my case. I looked through the logs and their doesn't seem to be any obvious error so I don't really know where to go from here. I'm using 2FA and I've noticed that I can still log in to my non 2FA accounts for some reason.

**Comment by afzalarsalan** [comment]
I went in and manually dropped the table from the mysql command prompt but it seems to recreate the table on restart and still throw this error.

**Comment by afzalarsalan** [comment]
Database initialisation failed: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'grouped_sender_acl' already exists

I'm also getting this error once logging in

**Comment by rafix1989** [comment]
Hi I've repaired the error.  The error was caused by the 

```
 $views = array(
    "grouped_mail_aliases" => "CREATE VIEW grouped_mail_aliases (username, aliases) AS
      SELECT goto, IFNULL(GROUP_CONCAT(address SEPARATOR ' '), '') AS address FROM alias
      WHERE address!=goto
      AND active = '1'
      AND address NOT LIKE '@%'
      GROUP BY goto;",
    "grouped_sender_acl" => "CREATE VIEW grouped_sender_acl (username, send_as) AS
      SELECT logged_in_as, IFNULL(GROUP_CONCAT(send_as SEPARATOR ' '), '') AS send_as FROM sender_acl
      WHERE send_as NOT LIKE '@%'
      GROUP BY logged_in_as;",
    "grouped_domain_alias_address" => "CREATE VIEW grouped_domain_alias_address (username, ad_alias) AS
      SELECT username, IFNULL(GROUP_CONCAT(local_part, '@', alias_domain SEPARATOR ' '), '') AS ad_alias FROM mailbox
      LEFT OUTER JOIN alias_domain on target_domain=domain GROUP BY username;"
    );
```

in 

> init_db.inc.php

Because I have table, and system want's to create view with the same name.

What i made:
1.Select Mailcow config -> source mailcow.conf
2.Log into database -> docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}
3.I check if it's empty -> select * from grouped_domain_alias_address;
4.and I drop it with command: drop table grouped_domain_alias_address;


step 3 and 4 i made for grouped_sender_acl and grouped_mail_aliases.
