### ISSUE TITLE
Disk space not being freed

### ISSUE THREAD

**Issue by solracsf** [mailcow/mailcow-dockerized#2483]
One of my (old) mailboxes was using about 10Gb, so I've decided to delete it.

But when I've checked available disk space on host, it remains the same after deletion so  nothing has been deleted from disk.

But when i check `/mnt/mailcow-data/volumes/mailcowdockerized_vmail-vol-1/_data/domain.com` i can't see the folder of the mailbox anymore...

I've also executed `./update.sh` and `docker system prune`, no effect.

**Comment by andryyy** [comment]
Hello cat,
Check `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/_garbage/`

**Comment by solracsf** [comment]
Thanks, it is there!
Should i manually delete that folder (isn't this handled by mailcow?)

**Comment by andryyy** [comment]
You can delete it, but it should be deleted after `MAILDIR_GC_TIME` (edit: **minutes**, not seconds) automatically.

**Comment by solracsf** [comment]
Of course, didn't think about that...thanks for your time answering this dumb question :p

```
# Garbage collector cleanup
# Deleted domains and mailboxes are moved to /var/vmail/_garbage/timestamp_sanitizedstring
# How long should objects remain in the garbage until they are being deleted? (value in minutes)
# Check interval is hourly

MAILDIR_GC_TIME=1440
```

**Comment by andryyy** [comment]
Not a dumb question. :)
