### ISSUE TITLE
Access mail.log for grepping?

### ISSUE THREAD

**Issue by RogerSik** [mailcow/mailcow-dockerized#2485]
Is there a way to access mail.log for grepping (or to get similar solution)? 

**docker logs postfix** gets very long and grep get ignored. Also older logs can't be viewed with this way.

**Comment by andryyy** [comment]
Hi, use another logging driver in Docker for persistent logs: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/

Grep is not ignored for docker-compose logs postfix. Perhaps you were using docker instead of docker-compose.

**Comment by sriccio** [comment]
You could also use portainer (a web based docker gui) and use it's log parsing windows on the container of your choice.

https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

![image](https://user-images.githubusercontent.com/5239282/55366932-1e112a80-54eb-11e9-8ac5-f9f59b9cc963.png)

**Comment by RogerSik** [comment]
Many thanks for your help @sriccio + @andryyy ! :) We use now Graylog for logging within mailcow. Additionally nice thing is that we added our other serves and now the logs are now central retrievable. :)
