### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by LongHopeFreedom** [mailcow/mailcow-dockerized#2486]
Will there be LDAP for this service in the future?

**Comment by andryyy** [comment]
No. There is an undocumented way to auth against LDAP. But that's it. We cannot mix our meta data sources.

**Comment by gmimietz** [comment]
> No. There is an undocumented way to auth against LDAP. But that's it. We cannot mix our meta data sources.

Hey andryyy, 

are there some hints (i know, it is undocumented) somewhere, to test this for another new project?
