### ISSUE TITLE
Best way to migrate from roundcube to dockerized mailcow with sogo?

### ISSUE THREAD

**Issue by pdarcos** [mailcow/mailcow-dockerized#2488]
Hi guys,

Great project!

I have an old roundcube installation that I would like to migrate to mailcow with sogo.

I know I can copy the old vmail folder to /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/ but what about the different account settings for the roundcube users (mainly concerned in maintaining same username/password combo)? I have an sql file dump from the old roundcube installation with user details (username, password, mailbox, etc) but I doubt I can just import that into mailcow. What container do I need to enter to examine the schema for mailcow with sogo to see if it's possible to just import the columns with username and password?

Any clues?

Thanks

**Comment by pdarcos** [comment]
Can anyone help? 
Anyone know where can I find the DB schema for sogo so I can compare it with the one in my roundcube installation?

**Comment by hachre** [comment]
You shouldn't directly manipulate the database. There's an undocumented Mailcow API that you can use to create Mailboxes in Mailcow from the Roundcube data you exported. I would recommend using that. 

Once you've added them through the API, just restart everything and you should be good to go!

You can find some sparse info on how to use it here:
https://github.com/mailcow/mailcow-dockerized/issues/1374#issuecomment-404868546

**Comment by pdarcos** [comment]
Thanks! Will checkout that thread.

**Comment by pdarcos** [comment]
I understand the bot considers this issue stale but there still isn’t any clear solution to this migration scenario.
