### ISSUE TITLE
Responsive Design Issues

### ISSUE THREAD

**Issue by felixoi** [mailcow/mailcow-dockerized#249]
Hey,

I found some responsive design issues:

![](https://i.gyazo.com/0c1a9eadfdc8a587915d0347d64e162b.png)
![](https://i.gyazo.com/cf7d84cbba1ee4d219e8fd3ea4bdfe14.png)

A fix would be nice 👍

**Comment by andryyy** [comment]
Will fix it, thanks! :)

**Comment by felixoi** [comment]
Still  an issue. Now also the "Logs"-Tab is not responsible. I figured out that the "table-responsive" class is not working.

**Comment by felixoi** [comment]
Mostly fixed by #407
