### ISSUE TITLE
Can't activate Time based OTP in new installation

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#2490]
Hello,

i have made saturday a fresh installation on a new Ubuntu 18.04.2 LTS vServer. The installation process works like i know from my private mailcow server. The only thing i can't activate is the Time based OTP for the admin account. The client is 1Password 6. I also use 1Password for the other instance, but actual it is version 7. It scans the code and generate a Number. When trying to save, name is chosen and password is set, the TOTP saving fails. Are there any logs about, which i can attach to find the error, and if, which logs do you need?
I saw the Date and Time section in the documentation, the output is a little bit different from timedatectl status then in the documentation, but time and date is ok.

`timedatectl status
Local time: Mo 2019-04-01 21:34:55 CEST
Universal time: Mo 2019-04-01 19:34:55 UTC
RTC time: Mo 2019-04-01 19:34:56
Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: no`

**Comment by andryyy** [comment]
Yes, looks like it is missing the secret in the QR code.
