### ISSUE TITLE
Fail2ban IP matching rule 2

### ISSUE THREAD

**Issue by Happyfeet01** [mailcow/mailcow-dockerized#2491]
**Describe the bug, try to make it reproducible**
My Server blocked my IP of my mobile and wifi network after ~15 Minutes. The server Information in Mailcow tells me that the IP matching fail2ban rule 2. I know that is an wrong password error. But the password is correct.

I delete the Mailbox on my Iphone and set it up again. In can send and recieve Emails. But i get this error again. 

What's wrong?

**System information and quick debugging**
General logs:
- Please take a look at the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Further information (where applicable):
 
`
sudo] password for sshadmin: 
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 259K   32M MAILCOW    all      *      *       ::/0                 ::/0                
3825K  500M ufw6-before-logging-input  all      *      *       ::/0                 ::/0                
3825K  500M ufw6-before-input  all      *      *       ::/0                 ::/0                
   33  2333 ufw6-after-input  all      *      *       ::/0                 ::/0                
   33  2333 ufw6-after-logging-input  all      *      *       ::/0                 ::/0                
   33  2333 ufw6-reject-input  all      *      *       ::/0                 ::/0                
   33  2333 ufw6-track-input  all      *      *       ::/0                 ::/0                

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 193K   32M MAILCOW    all      *      *       ::/0                 ::/0                
 721K  140M DOCKER     all      *      br-mailcow  ::/0                 ::/0                
 622K  133M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
34227 3475K ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0                
98389 7352K ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0                
2045K  302M DOCKER     all      *      br-59911341cccf  ::/0                 ::/0                
1720K  278M ACCEPT     all      *      br-59911341cccf  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
51830 5248K ACCEPT     all      br-59911341cccf !br-59911341cccf  ::/0                 ::/0                
 324K   24M ACCEPT     all      br-59911341cccf br-59911341cccf  ::/0                 ::/0                
 3322  243K DOCKER-ISOLATION  all      *      *       ::/0                 ::/0                
 3322  243K ufw6-before-logging-forward  all      *      *       ::/0                 ::/0                
 3322  243K ufw6-before-forward  all      *      *       ::/0                 ::/0                
 3153  234K ufw6-after-forward  all      *      *       ::/0                 ::/0                
 3153  234K ufw6-after-logging-forward  all      *      *       ::/0                 ::/0                
 3153  234K ufw6-reject-forward  all      *      *       ::/0                 ::/0                
 3153  234K ufw6-track-forward  all      *      *       ::/0                 ::/0                

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
3985K  581M ufw6-before-logging-output  all      *      *       ::/0                 ::/0                
3985K  581M ufw6-before-output  all      *      *       ::/0                 ::/0                
 124K   24M ufw6-after-output  all      *      *       ::/0                 ::/0                
 124K   24M ufw6-after-logging-output  all      *      *       ::/0                 ::/0                
 124K   24M ufw6-reject-output  all      *      *       ::/0                 ::/0                
 124K   24M ufw6-track-output  all      *      *       ::/0                 ::/0                

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::9  tcp dpt:110
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::9  tcp dpt:143
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::9  tcp dpt:4190
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::9  tcp dpt:993
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::9  tcp dpt:995
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::4  tcp dpt:25
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::4  tcp dpt:465
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::4  tcp dpt:587

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all      *      *       ::/0                 ::/0                

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-after-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-after-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ufw6-skip-to-policy-input  udp      *      *       ::/0                 ::/0                 udp dpt:137
    0     0 ufw6-skip-to-policy-input  udp      *      *       ::/0                 ::/0                 udp dpt:138
    0     0 ufw6-skip-to-policy-input  tcp      *      *       ::/0                 ::/0                 tcp dpt:139
    0     0 ufw6-skip-to-policy-input  tcp      *      *       ::/0                 ::/0                 tcp dpt:445
    0     0 ufw6-skip-to-policy-input  udp      *      *       ::/0                 ::/0                 udp dpt:546
    0     0 ufw6-skip-to-policy-input  udp      *      *       ::/0                 ::/0                 udp dpt:547

Chain ufw6-after-logging-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  207 14243 LOG        all      *      *       ::/0                 ::/0                 limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw6-after-logging-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   33  2333 LOG        all      *      *       ::/0                 ::/0                 limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw6-after-logging-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-after-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-before-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      *       ::/0                 ::/0                 rt type:0
    0     0 ACCEPT     all      *      *       ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 1
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 2
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 3
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 4
  169  9802 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 128
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 129
 3153  234K ufw6-user-forward  all      *      *       ::/0                 ::/0                

Chain ufw6-before-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
3561K  357M ACCEPT     all      lo     *       ::/0                 ::/0                
    0     0 DROP       all      *      *       ::/0                 ::/0                 rt type:0
93258  115M ACCEPT     all      *      *       ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
  120 10482 ufw6-logging-deny  all      *      *       ::/0                 ::/0                 ctstate INVALID
  120 10482 DROP       all      *      *       ::/0                 ::/0                 ctstate INVALID
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 1
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 2
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 3
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 4
  188 15018 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 128
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 129
 2438  137K ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 133 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 134 HL match HL == 255
21423 1542K ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 135 HL match HL == 255
22982 1471K ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 136 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 141 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 142 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 130
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 131
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 132
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 143
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 148 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 149 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 151 HL match HL == 1
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 152 HL match HL == 1
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 153 HL match HL == 1
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 144
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 145
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 146
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 147
    0     0 ACCEPT     udp      *      *       fe80::/10            fe80::/10            udp spt:547 dpt:546
 122K   24M ACCEPT     udp      *      *       ::/0                 ff02::fb             udp dpt:5353
    0     0 ACCEPT     udp      *      *       ::/0                 ff02::f              udp dpt:1900
 2176  169K ufw6-user-input  all      *      *       ::/0                 ::/0                

Chain ufw6-before-logging-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-before-logging-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-before-logging-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-before-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         
3561K  357M ACCEPT     all      *      lo      ::/0                 ::/0                
    0     0 DROP       all      *      *       ::/0                 ::/0                 rt type:0
 161K  183M ACCEPT     all      *      *       ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    8  1158 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 1
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 2
    1  1280 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 3
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 4
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 128
  186 14880 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 129
  152  8512 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 133 HL match HL == 255
21423 1372K ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 136 HL match HL == 255
23491 1691K ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 135 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 134 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 141 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 142 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 130
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 131
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 132
94489   12M ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 143
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 148 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       ::/0                 ::/0                 ipv6-icmptype 149 HL match HL == 255
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 151 HL match HL == 1
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 152 HL match HL == 1
    0     0 ACCEPT     icmpv6    *      *       fe80::/10            ::/0                 ipv6-icmptype 153 HL match HL == 1
 124K   24M ufw6-user-output  all      *      *       ::/0                 ::/0                

Chain ufw6-logging-allow (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 LOG        all      *      *       ::/0                 ::/0                 limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW ALLOW] "

Chain ufw6-logging-deny (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  107  8818 RETURN     all      *      *       ::/0                 ::/0                 ctstate INVALID limit: avg 3/min burst 10
   11  1408 LOG        all      *      *       ::/0                 ::/0                 limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw6-reject-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-reject-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-reject-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-skip-to-policy-forward (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      *       ::/0                 ::/0                

Chain ufw6-skip-to-policy-input (6 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      *       ::/0                 ::/0                

Chain ufw6-skip-to-policy-output (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 ::/0                

Chain ufw6-track-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-track-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-track-output (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 1870  150K ACCEPT     tcp      *      *       ::/0                 ::/0                 ctstate NEW
 122K   24M ACCEPT     udp      *      *       ::/0                 ::/0                 ctstate NEW

Chain ufw6-user-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-user-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:6680
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:6680
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:6880
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:6880
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:6800
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:6800
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:9980
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:9980
  187 14760 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:80 /* 'dapp_Nginx%20HTTP' */
 1940  151K ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:443 /* 'dapp_Nginx%20HTTPS' */
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:4444
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:4444
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:5601
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:5601
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:1194
    1    64 ACCEPT     tcp      *      *       ::/0                 ::/0                 multiport dports 20,21,10000:10100
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:65438
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:65438
    2   128 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:53
    2   156 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:53
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:143
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:143
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:993
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:993
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:110
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:110
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:995
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:995
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:587
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:587
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:465
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:465
    2   128 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:8080
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:8080
    9   720 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:8443
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:8443
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:80
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:443
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:5601
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:4433
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:8833
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:3000
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:3000
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:5432
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:5432
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:8001
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:8001
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:25
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:25
    0     0 ACCEPT     tcp      *      *       ::/0                 ::/0                 tcp dpt:4190
    0     0 ACCEPT     udp      *      *       ::/0                 ::/0                 udp dpt:4190

Chain ufw6-user-limit (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 LOG        all      *      *       ::/0                 ::/0                 limit: avg 3/min burst 5 LOG flags 0 level 4 prefix "[UFW LIMIT BLOCK] "
    0     0 REJECT     all      *      *       ::/0                 ::/0                 reject-with icmp6-port-unreachable

Chain ufw6-user-limit-accept (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 ::/0                

Chain ufw6-user-logging-forward (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-user-logging-input (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-user-logging-output (0 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain ufw6-user-output (1 references)
 pkts bytes target     prot opt in     out     source               destination `

`
4.2019, 01:59:42	warn	6 more attempts in the next 240 seconds until 109.41.128.0/24 is banned
2.4.2019, 01:59:42	warn	109.41.128.202 matched rule id 2
2.4.2019, 01:55:41	warn	5 more attempts in the next 240 seconds until 109.41.128.0/24 is banned
2.4.2019, 01:55:41	warn	109.41.128.202 matched rule id 2
`

The 109.41.128.0 is an Vodafone Germany Network.

**Comment by andryyy** [comment]
Check Dovecot. If it logs a "auth failed", a login failed.

**Comment by Happyfeet01** [comment]
Look here 


managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.7, lip=172.22.1.250
2.4.2019, 11:29:16	info	imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.7, lip=172.22.1.250
2.4.2019, 11:29:16	info	imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.7, lip=172.22.1.250, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)

Von meinem iPhone gesendet
