### ISSUE TITLE
Postfix external SMTP Relay 

### ISSUE THREAD

**Issue by oabegga** [mailcow/mailcow-dockerized#2494]
Hey guys,

I want to send my mails with 1und1 or google, because i cant set a RDNS entry for myself, and my ISP wont do it.

server: smtp.ionos.de
outgoing port: 587 (TLS must be activated)

I tried to set it up with transport maps but it didnt work.

I downloaded postfix and configured it there -> it worked

So how can I configure it with the mailcow postfix?

smtp.ionos.de
next hop: smtp.ionos.de:587
username: email address
password: my password 

Any solution?

Sebastian

**Comment by mkuron** [comment]
Don't use transport maps. They are for specific destination domains only.

Instead, enter the relayhost SMTP server as a sender-dependent transport. Then edit the domain and select the transport there.

**Comment by oabegga** [comment]
> ad, enter the relayhost SMTP server as a sender-dependent transport. Then edit the domain and select the transport there.

Sendet immer noch nicht über 1und1...
