### ISSUE TITLE
No option to send rspamd rejects to spam

### ISSUE THREAD

**Issue by JeffResc** [mailcow/mailcow-dockerized#2495]
Some valid emails are being rejected by rspamd and not being sent to my spam box, I’d like to congure all rejected emails to go to the junk/spam box so that I may review them without logging into the rspamd configuration page.

**Comment by mkuron** [comment]
By default, the minimum score for the spam folder is 5 and for rejection it is 15. You can log into the web UI as the user (not admin) and change the limits.

Usually though, there is some good reason if rspamd assigns a score of 15+, so you might want to check if there is something wrong on the sender side that makes it look spammy.
