### ISSUE TITLE
Watchdog restarting clamd

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2499]
There is problem with watchdog and clamd. When clamd updates databases, it takes some time and when thi sis issued

```
RELOADING
Fri Apr  5 10:40:16 2019 -> Reading databases from /var/lib/clamav
```

them clamd is for while unresponsive. In that case watchdog restarts clamd and it start from begin, when reach above point, watchdog restarts again and again....

I have to stop watchdog container and leave clamd to boot and load databases.

Reading databases takes 1minute and 14sec in my case.

**Comment by reinistihovs** [comment]
mee too, on all of my servers i have problems

**Comment by lucianlazar1983** [comment]
I have the same exact problem

**Comment by feldsam** [comment]
I see some commit in master, which should fix this issue.

https://github.com/mailcow/mailcow-dockerized/commit/794c2080ec8c9e16a4583ae0ad1a8ccd4ff82842

**Comment by flaviomeyer** [comment]
I have the same error for several months.

**Comment by feldsam** [comment]
I deployed latest version with linked fix and it is working now

**Comment by andryyy** [comment]
Thanks for your feedback.
