### ISSUE TITLE
Error in "mailcodockerized_mailcow-network" after ./update.sh - iptables

### ISSUE THREAD

**Issue by pbaeumel** [mailcow/mailcow-dockerized#2500]
Just have had run ./update.sh a few minutes ago (try to fix my last issue filed under #2498).

Unfortunately got the following error:
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-mailcow -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))

Best regards,
MacGyver

**Comment by andryyy** [comment]
Don’t delete the Docker chains in iptables

You need to fix that by restating the Docker service.

**Comment by pbaeumel** [comment]
@andryyy 
Didn`t delete anything in iptables.

The only thing I have done for issue #2498 has been:
systemctl disable firewalld

After that I have seen that a new error in ACME-Log occured:
"Cannot match your IP against hostname"

I then additionally only tried 
cd /opt/mailcow-dockerized
./update.sh

No more changes have been done from my side.

Do you mean "docker-compose down && docker-compose up -d" for restarting the Docker service?

**Comment by hachre** [comment]
This should do it:
```
docker-compose down
systemctl stop docker
iptables -F
systemctl start docker
docker-compose up -d
```

**Comment by pbaeumel** [comment]
Problem has been solved by issuing the above commands of @hachre

**Comment by alexandernst** [comment]
Hopefully only `systemctl restart docker` will fix it. Note that `docker-compose down` is a destructive command.

**Comment by andryyy** [comment]
No, down is fine. Containers are transient. Down -v is bad. Very bad.
