### ISSUE TITLE
Api tls_enforce_xx not function

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2502]
Hallo,

I think the new attributes are not reflect in the API correct.
When I change for example the attribute **sogo_access** - there is no problem.

`curl -X POST http://127.0.0.1:8880/api/v1/edit/mailbox/ -H "X-API-Key: D95209-D82428-C289C0-8B0B17-EEEAB" -d attr='{"sogo_access":1,"username":"test@readme.com"}'`

but with **tls_enforce_in** and **tls_enforce_out** I see no change. How can I change this or is it a bug?

`curl -X POST http://127.0.0.1:8880/api/v1/edit/mailbox/ -H "X-API-Key: D95209-D82428-C289C0-8B0B17-EEEAB" -d attr='{"tls_enforce_out":1,"username":"test@readme.com"}'`

Thank You

**Comment by andryyy** [comment]
Have you checked the API log when you change it via UI? What does it look like there?

**Comment by ghost** [comment]
Thank You I got it

`curl -X POST http://127.0.0.1:8880/api/v1/edit/tls_policy -H "X-API-Key: D95209-D82428-C289C0-8B0B17-EEEAB" -d attr='{"tls_enforce_out":1,"username":"test@readme.com"}'`

**Comment by andryyy** [comment]
Thanks for reporting back. I was on my mobile and couldn't check, sorry.
