### ISSUE TITLE
mailcow UI inaccessible after update of Ubuntu

### ISSUE THREAD

**Issue by LeoXIII** [mailcow/mailcow-dockerized#2505]
updated Ubuntu 18.04.02
sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y

after the update, all mailcow services are running fine but I can't access mailcow's UI:
admin login with 2FA – unknown TFA Method upon entering the TOTP
user login without 2FA – blank screen after login

updated mailcow – services fine but still no access to mailcow UI.

$ docker-compose logs --tail=100 sogo-mailcow
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 27, in project_from_options
  File "compose/config/environment.py", line 73, in from_env_file
  File "compose/config/environment.py", line 68, in _initialize
  File "compose/config/environment.py", line 43, in env_vars_from_file
  File "/code/.tox/py36/lib/python3.6/codecs.py", line 897, in open
PermissionError: [Errno 13] Permission denied: './.env'
[23842] Failed to execute script docker-compose

docker-compose version 1.24.0, build 0aa59064
/usr/local/bin/docker-compose is executable (permissions are set to 755)

lrwxrwxrwx 1 root root    12 Mar 16 19:31 .env -> mailcow.conf
-rw------- 1 root root  4258 Apr  5 17:00 mailcow.conf

Any idea?

**Comment by andryyy** [comment]
`$ ` <==

mailcow.conf is owned by root and can only be accessed by root.

Just work with root. Even if you allow an unprivileged user Docker access, the dockerd will still run as root, so it doesn't matter. We drop privileges inside the containers.

**Comment by LeoXIII** [comment]
Ok

Apr  6 13:53:01 4e62e35e6425 CRON[689]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:53:01 4e62e35e6425 CRON[688]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:53:01 4e62e35e6425 CRON[691]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Apr  6 13:53:01 4e62e35e6425 CRON[693]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Apr  6 13:53:02 4e62e35e6425 CRON[689]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:53:02 4e62e35e6425 CRON[688]: pam_unix(cron:session): session closed for user sogo

**Comment by LeoXIII** [comment]
Ok,

$ sudo docker-compose logs --tail=20 sogo-mailcow
Attaching to mailcowdockerized_sogo-mailcow_1
sogo-mailcow_1       | Apr  6 13:54:01 4e62e35e6425 CRON[697]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:54:01 4e62e35e6425 CRON[696]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[705]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[704]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[707]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[709]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[705]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:55:01 4e62e35e6425 CRON[704]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:56:01 4e62e35e6425 CRON[713]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:56:01 4e62e35e6425 CRON[712]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:56:01 4e62e35e6425 CRON[715]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Apr  6 13:56:01 4e62e35e6425 CRON[717]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Apr  6 13:56:02 4e62e35e6425 CRON[713]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:56:02 4e62e35e6425 CRON[712]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[721]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[720]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[723]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[725]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[721]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Apr  6 13:57:01 4e62e35e6425 CRON[720]: pam_unix(cron:session): session closed for user sogo

**Comment by andryyy** [comment]
Yes. So? Did I miss something?

**Comment by LeoXIII** [comment]
well, for sure I am missing something but my hope is that you could lead me on the way to find out, could you?

So, mailcow UI is not accessible. How should I proceed?
