### ISSUE TITLE
Regex in aliases

### ISSUE THREAD

**Issue by Athan1** [mailcow/mailcow-dockerized#2507]
Like in issue #1787. I would appreciate if add support for regex in alias addresses. Why is it needed? I'm using used postfix regex-maps for several years by now and switching to mailcow would be much easier, when I simply could use the same entries. What I always liked about the regex-aliases is, they are very flexible. e.g. special e-Mail addresses for every online login. Of course there is the recipient_delimiter, but every body knows that and if I use foo+bar@example.com everybody knows I'm foo@example.com. Okay I can switch the delimiter, but that's not a big bargain. With regex you can build nearly every pattern. Who to do it? I hope it shouldn't be a big deal to implement. Maybe replacing the normal query in /opt/postfix/conf/sql/mysql_virtual_alias_maps.cf (in the postfix container) by
 ```
SELECT goto FROM alias
  WHERE address='%s' REGEXP CONCAT('^',alias.address,'$') AND SUBSTRING(alias.address,1,1) != '@'     AND active='1';
```
 and allow entering REGEXP as aliases in the UI might do most of the job.

**Comment by timm0e** [comment]
+1

**Comment by timo-reymann** [comment]
+1

**Comment by axello** [comment]
+1 (also coming from self-hosted postfix server where I used the regex. Now I have to edit the regex file in the postfix docker container, which is sub-optimal.

**Comment by BorysVrublevskyi** [comment]
For everyone who was looking for a workaround with some limitations. This will allow you to match incoming mail by regex and redirect it to any other mail but **will break the Catch-ALL rule in the Aliases**.

(Assume that you are `root` and repo was cloned into the `/root/mailcow-dockerized`)

Override main.cf

```bash
nano /root/mailcow-dockerized/data/conf/postfix/extra.cf
```

Add new line

```
virtual_alias_maps = regexp:/opt/postfix/conf/aliases-regexp
```

Add regex rules

```bash
nano /root/mailcow-dockerized/data/conf/postfix/aliases-regexp
```

```
/^prefix1(.*)@mydomain.com$/    catch@mydomain.com
/^prefix2(.*)@mydomain.com$/  catch@mydomain.com
```

Restart postfix container
