### ISSUE TITLE
Folder sharing between users in SOGo

### ISSUE THREAD

**Issue by osidney** [mailcow/mailcow-dockerized#2511]
When trying to share folders between users of SOGo the folder is not being shared, I have verified that this has been happening in version 4.0.7 of SOGo, in version 4.0.5 does not happen this problem, someone would know how to solve it or downgrade to the version 4.0.5 " Thanks a lot for the help.
The shared folder does not appear, but I get the message that was shared successfully.
http://prntscr.com/n98d3v

**Comment by asifbacchus** [comment]
Seem to be having the same problem.  Works with my other server using mailcow/sogo:1.53.  I can't get shared folders to show up at all in SOGo with the the latest pull (mailcow/sogo:1.54).  Can I just change the compose file and pull 1.53?  Thanks in advance.
