### ISSUE TITLE
Backup Mailbox to S3 Storage

### ISSUE THREAD

**Issue by flaviomeyer** [mailcow/mailcow-dockerized#2513]
**Is your feature request related to a problem? Please describe.**
A nice feature would be to safe the mailboxes to an generic S3 Storage like AWS S3, Minio etc... 

**Describe the solution you'd like**
Backup Mailboxes to generic S3 Storage. 
Schedule Mailbox safes via WebUI.

**Comment by MB-Jan** [comment]
@meyerf99 I do not think it needs to be part of mailcow. You could simply create a cron job to create the backup and then sync the main backup folder with S3 via the S3 CLI [(S3 docs)](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html).
For full backups it could look like this:
`30 0 * * * root BACKUP_LOCATION=/opt/backup /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all && aws s3 sync /opt/backup/ s3://my-bucket/backups/`

If you want to backup just the emails, change "all" to "vmail" as explained here: [mailcow docs](https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/)

I hope this helps.

- Jan

**Comment by X1Aaron** [comment]
> @meyerf99 I do not think it needs to be part of mailcow. You could simply create a cron job to create the backup and then sync the main backup folder with S3 via the S3 CLI [(S3 docs)](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html).
> For full backups it could look like this:
> `30 0 * * * root BACKUP_LOCATION=/opt/backup /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all && aws s3 sync /opt/backup/ s3://my-bucket/backups/`
> 
> If you want to backup just the emails, change "all" to "vmail" as explained here: [mailcow docs](https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/)
> 
> I hope this helps.
> 
> * Jan

This is basicly what I do as well, however I am using rclone.

**Comment by X1Aaron** [comment]
This is what I am using:

https://github.com/aaronstuder/backup-scripts/blob/master/mailcow-backup

rclone supports Amazon S3, Wasabi, and many others.
