### ISSUE TITLE
error 450 4.7.1 Client host rejected after update

### ISSUE THREAD

**Issue by SDFka** [mailcow/mailcow-dockerized#2517]
Hello. After the last update, our multi-function printer cannot send an email to the user.
MFP: pr001@domain.ru
user: user@domain.ru
Users and printer are located in the same office.

xxx.xxx.xxx.xxx - external router ip
yyy.yyy.yyy.yyy - internal printer ip

postfix logs: postfix/smtpd[2717]: NOQUEUE: reject: RCPT from unknown[xxx.xxx.xxx.xxx]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [xxx.xxx.xxx.xxx]; from=<pr001@domain.ru> to=<user@domain.ru> proto=ESMTP helo=<[yyy.yyy.yyy.yyy]>

If I send a message from the same email (pr001@domain.ru) through an email client, no errors occur.
Any ideas what might have changed after the update?

**Comment by SDFka** [comment]
Problem solved.
The problem was in the device settings, before mailcow update the printer worked through port 25, but it was clearly not shown even when using TLS encryption.

**Comment by andryyy** [comment]
Yes, please use port 587 for submission. :) Authentication has been removed from port 25.

**Comment by abewartech** [comment]
How to add Authentication on port 25?
