### ISSUE TITLE
Email to local user aliases on the host server is failing

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2518]
I am struggling to get email from the local system into mailcow. I have followed the [local MTA docs](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/) but it is still failing, the logs (extract below) report the mailname being the same as the mailcow hostname. This used to be true but I recently updated the `MAILCOW_HOSTNAME` to fix this. 

This only happens when I am sending to an alias (/etc/aliases (root,postmaster,logcheck))
When I send direct to a normal email address it works fine. 

```
Apr 11 08:02:08 mail01 postfix/smtp[12965]: warning: host ex1.example.com[198.51.100.1]:25 greeted me with my own hostname mail01.mydomain.com
Apr 11 08:02:08 mail01 postfix/smtp[12965]: warning: host ex1.example.com[198.51.100.1]:25 replied to HELO/EHLO with my own hostname mail01.mydomain.com
Apr 11 08:02:08 mail01 postfix/smtp[12965]: 12C6517A66D: to=<logcheck@ex1.example.com>, relay=ex1.example.com[198.51.100.1]:25, delay=0.03, delays=0.01/0.01/0.01/0, dsn=5.4.6, status=bounced (mail for ex1.example.com loops back to myself)
```

Has anyone else got this working?
Perhaps something is missing from my set up?

**Comment by lazyfrosch** [comment]
Basically ensure the host is a different hostname and doesn't retrieve mail for the name of the mailcow system.

```
myhostname = notmailcow.mydomain.com
myorigin = notmailcow.mydomain.com
mydestination = $myhostname, localhost.lazyfrosch.de, localhost
relayhost = 172.22.1.1
```

My host is a Debian stretch with Postfix.
