### ISSUE TITLE
SOGo new folder issue

### ISSUE THREAD

**Issue by nessor** [mailcow/mailcow-dockerized#2519]
Hey guys,

it seems that my SOGo instance cannot create new folders. With a completely new mailbox, only the message that the creation was not possible appears at the attachment.
Also the logs are unfortunately not very helpful:

```
sogo-mailcow_1       | Apr 11 12:28:25 4f27fe2800a4 sogod [83]: <0x0x55a54bdbb400[NGImap4Client]> TLS started successfully.

nginx-mailcow_1      | [IPv6] - - [11/Apr/2019:12:28:25 +0200] "POST /SOGo/so/[MAILADRESSE]/Mail/0/folderINBOX/createFolder HTTP/1.0" 204 0 "[SERVER]/SOGo/so/[MAILADRESSE]/Mail/view" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36"

sogo-mailcow_1       | Apr 11 12:28:25 4f27fe2800a4 sogod [83]: [IPv6] "POST /SOGo/so/[MAILADRESSE]/Mail/0/folderINBOX/createFolder HTTP/1.0" 204 0/17 0.326 - - 0

dovecot-mailcow_1    | Apr 11 12:28:25 mail dovecot: imap([MAILADRESSE])<2550><fBdzpT6GfsGsFgH4>: Logged out in=165 out=1311 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

I tried the creation with Chrome and Firefox. In Firefox no error message appears at all. The folder is simply not created.
Can anyone reproduce this error with the current version?

**Comment by TitinDev** [comment]
exactly the same problem

**Comment by andryyy** [comment]
Cannot confirm. I can create folders below INBOX and in the root directory (Test123). I needed to refresh the browser, though.

![image](https://user-images.githubusercontent.com/2972950/57059692-b3543a00-6cb6-11e9-8682-ef03e7ff202d.png)

If you create folders below other folders (like "Posteingang" in the Screenshot above), you need to click the marked, grey folder icon to expand/open it.

When you click on it, it opens:

![image](https://user-images.githubusercontent.com/2972950/57059751-f1e9f480-6cb6-11e9-8e31-a28310727b92.png)

**Comment by TitinDev** [comment]
Yes shame that there is need to refresh ..

**Comment by andryyy** [comment]
Have you considered reporting it to SOGo?

They don’t owe you anything. They give you their software for free. Let them know about bugs and help them to improve their software. :)

**Comment by TitinDev** [comment]
> Have you considered reporting it to SOGo?
> 
> They don’t owe you anything. They give you their software for free. Let them know about bugs and help them to improve their software. :)

Yes !

**Comment by Braintelligence** [comment]
No news is good news.
