### ISSUE TITLE
SPF Record Syntax link not working

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#2522]
**Describe the bug, try to make it reproducible**
Open DNS records info popup for a domain, click the 'SPF Record Syntax' link.
Notice that the site refuses connection (http://www.openspf.org/SPF_Record_Syntax).

**Comment by HusseinMorsy** [comment]
website www.openspf.org is still not working
([google cacheversion](http://webcache.googleusercontent.com/search?source=hp&ei=egrRXOGrE4LTsAee2Ia4BA&q=cache%3Ahttp%3A%2F%2Fwww.openspf.org%2FSPF_Record_Syntax&btnK=Google+Search&oq=cache%3Ahttp%3A%2F%2Fwww.openspf.org%2FSPF_Record_Syntax&gs_l=psy-ab.3...1492.3506..4072...0.0..0.321.1758.2j3j2j2......0....1j2..gws-wiz.....0..0j0i10.vMOS9-wjtPc) is available)

Suggest Link to [wikipedia](https://en.wikipedia.org/wiki/Sender_Policy_Framework)

**Comment by NicoDreamzZ** [comment]
I read several time that openspf closed without any message why.

**Comment by patschi** [comment]
Solved in 59798357f776c237948c64ee3bd9d61bb79568f5 a while ago.
