### ISSUE TITLE
DNS-Records popup: _autodiscover._tcp value

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#2523]
The value for `_autodiscover._tcp.example.com` should be `mail.example.com 443` in DNS-Records popup.
A value with space between `mail.example.com` and `443` is not accepted by some registrars/DNS providers (like in my case). Is the proposed value correct? Should there really a space and then the port?

**Comment by hachre** [comment]
this is a record of type SRV and they always have a port field that you should use

**Comment by strarsis** [comment]
Right. There is a port field, and I had to specify the SRV record value with 
first the priority (0), then the port (443) and then finally the domain (mail.example.com):
`0 443 mail.example.com`
