### ISSUE TITLE
Mailcow-dockerized with CapRover

### ISSUE THREAD

**Issue by jarboz** [mailcow/mailcow-dockerized#2524]
I think that adding mailcow-dockerized to CapRover would be benificial. It allows for having a web based control panel and gives the users a excellent dashbord with monitoring of the system.

Has anyone gotten this to work?

**Comment by HiptJo** [comment]
i'm currently trying to run mailcow on caprover - it gets quite complicated...

**Comment by ghost** [comment]
I'm trying too.

**Comment by yassinebridi** [comment]
Has anyone succeded in setting it up?

**Comment by HiptJo** [comment]
I did just run it via docker compose next to caprover (mailcow http port 8080) and then i added redirects (301) from mailadmin.domain.net to domain.net:8080

The SSL certificate for my root domain is generated ba caprover and moved over to the mailcow folder using a cronjob task

I could provide those copy instructions on request.

It is for sure not the perfect solution, but it works perfectly fine for the last months.

**Comment by yassinebridi** [comment]
Thank you for the quick response.
> I could provide those copy instructions on request.

This would be really appreciated.

**Comment by HiptJo** [comment]
## certificate access

```bash
#bin/bash
cp $(find /home/ssl/caprover -type f -iname "cert*" | sort -n | tail -n 1) /home/ssl/mailcow/cert.pem -v
cp $(find /home/ssl/caprover -type f -iname "privkey*" | sort -n | tail -n 1) /home/ssl/mailcow/key.pem -v
# docker restart mailcowdockerized_postfix-mailcow_1
```

docker restart is not required in my usecase, however it can be used to reload the certificates immediately

## http proxy
Nginx is used as proxy service - as another redirect service is running on my server using nodejs for different permanent redirects, i added the redirect instructions there

```bash
webmail.domain.at -> 301 https://domain.at:8443/SOGo
mailadmin.domain.at -> 301 https://domain.at:8443/admin
```

**Comment by yassinebridi** [comment]
Thank you.

**Comment by SpaceIgniter** [comment]
> ## certificate access
> ```shell
> #bin/bash
> cp $(find /home/ssl/caprover -type f -iname "cert*" | sort -n | tail -n 1) /home/ssl/mailcow/cert.pem -v
> cp $(find /home/ssl/caprover -type f -iname "privkey*" | sort -n | tail -n 1) /home/ssl/mailcow/key.pem -v
> # docker restart mailcowdockerized_postfix-mailcow_1
> ```
> 
> docker restart is not required in my usecase, however it can be used to reload the certificates immediately
> 
> ## http proxy
> Nginx is used as proxy service - as another redirect service is running on my server using nodejs for different permanent redirects, i added the redirect instructions there
> 
> ```shell
> webmail.domain.at -> 301 https://domain.at:8443/SOGo
> mailadmin.domain.at -> 301 https://domain.at:8443/admin
> ```

Hi,

Could you possibly give clearer instructions on how to accomplish this?
I have Mailcow installed, including Caprover, both work as expected, but I am having trouble setting up SSL for Mailcow.
I attempted to follow your steps, including the Mailcow documentaion, but I am not winning.

Kindly provide a basic guide on how to set it up correctly.

Thank you,

**Comment by HiptJo** [comment]
> > ## certificate access
> > ```shell
> > #bin/bash
> > cp $(find /home/ssl/caprover -type f -iname "cert*" | sort -n | tail -n 1) /home/ssl/mailcow/cert.pem -v
> > cp $(find /home/ssl/caprover -type f -iname "privkey*" | sort -n | tail -n 1) /home/ssl/mailcow/key.pem -v
> > # docker restart mailcowdockerized_postfix-mailcow_1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > docker restart is not required in my usecase, however it can be used to reload the certificates immediately
> > ## http proxy
> > Nginx is used as proxy service - as another redirect service is running on my server using nodejs for different permanent redirects, i added the redirect instructions there
> > ```shell
> > webmail.domain.at -> 301 https://domain.at:8443/SOGo
> > mailadmin.domain.at -> 301 https://domain.at:8443/admin
> > ```
> 
> Hi,
> 
> Could you possibly give clearer instructions on how to accomplish this? I have Mailcow installed, including Caprover, both work as expected, but I am having trouble setting up SSL for Mailcow. I attempted to follow your steps, including the Mailcow documentaion, but I am not winning.
> 
> Kindly provide a basic guide on how to set it up correctly.
> 
> Thank you,

Hi, how far did you get already? Do you already have access to the http (non-ssl) services?

**Comment by HiptJo** [comment]
> > > ## certificate access
> > > ```shell
> > > #bin/bash
> > > cp $(find /home/ssl/caprover -type f -iname "cert*" | sort -n | tail -n 1) /home/ssl/mailcow/cert.pem -v
> > > cp $(find /home/ssl/caprover -type f -iname "privkey*" | sort -n | tail -n 1) /home/ssl/mailcow/key.pem -v
> > > # docker restart mailcowdockerized_postfix-mailcow_1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > docker restart is not required in my usecase, however it can be used to reload the certificates immediately
> > > ## http proxy
> > > Nginx is used as proxy service - as another redirect service is running on my server using nodejs for different permanent redirects, i added the redirect instructions there
> > > ```shell
> > > webmail.domain.at -> 301 https://domain.at:8443/SOGo
> > > mailadmin.domain.at -> 301 https://domain.at:8443/admin
> > > ```
> > 
> > 
> > Hi,
> > Could you possibly give clearer instructions on how to accomplish this? I have Mailcow installed, including Caprover, both work as expected, but I am having trouble setting up SSL for Mailcow. I attempted to follow your steps, including the Mailcow documentaion, but I am not winning.
> > Kindly provide a basic guide on how to set it up correctly.
> > Thank you,
> 
> Hi, how far did you get already? Do you already have access to the http (non-ssl) services?

Additional info: i had to update the crontask (.sh file)

```bash
#bin/bash
cp $(find /captain/data/letencrypt/etc/archive/ROOTDOMAINHERE.COM -type f -iname "cert*" | sort -V | tail -n 1) /opt/mailcow-dockerized/data/assets/ssl/cert.pem -v
cp $(find /captain/data/letencrypt/etc/archive/ROOTDOMAINHERE.COM -type f -iname "privkey*" | sort -V | tail -n 1) /opt/mailcow-dockerized/data/assets/ssl/key.pem -v
chmod a+rx /opt/mailcow-dockerized/data/assets/sslkey.pem
chmod a+rx /opt/mailcow-dockerized/data/assets/ssl/cert.pem
docker restart $(docker ps -qaf name=postfix-mailcow)
docker restart $(docker ps -qaf name=nginx-mailcow)
docker restart $(docker ps -qaf name=dovecot-mailcow)
```

**Comment by SpaceIgniter** [comment]
> Hi, how far did you get already? Do you already have access to the http (non-ssl) services?

Hi, yes. I have access via HTTP/HTTPS, but I'm unable to generate a Let's Encrypt Certificate, due to port 80 in use.
Concerning your updates to the crontask. I think that's a few steps ahead of where I'm supposed to be.
Do I need to setup a Nginx 1-Click App in Caprover? Steps from start to finish will be greatly appreciated.

Thanks, have a great week.
