### ISSUE TITLE
When need the TLSA records updating?

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#2525]
When need the TLSA records updating? 

- After adding extra domains to the server cert?
- When the ACME client renewed the certs (this probably has 
already been taken into account by mailcow-dockerized?)?
- When new domains are added?

What would be the consquences when the admin forgets to update the TLSA records?
Will MTAs deny further delivery? Only some MTAs?

**Comment by mkuron** [comment]
They only need to be updated when the private key changes. That is, when you delete the ssl directory and have it generate a new one. If the records are wrong, DANE-compliant mail servers will no longer deliver to you.

**Comment by strarsis** [comment]
@mkuron: Thanks.

Extra question: Can the TLSA records be kept unchanged when the FQDN of mail server is changed?

**Comment by mkuron** [comment]
We are using `3 1 1` TLSA records, so only the public key matters. The certificate is not checked.

If you change the host name, of course you need to add the TLSA record for the new name, but its value will be the same as before.
