### ISSUE TITLE
Could not add domain alias

### ISSUE THREAD

**Issue by littleplus** [mailcow/mailcow-dockerized#2526]
Error message: 
```
Alias domain xxx is invalid
```

The domain is in the domain list, and I could use it for email sending or receiving successfully.

Any other information should I provide?

**Comment by littleplus** [comment]
The domain I have tried is a second-level domain, xxx.com. But when I try to add a third-level domain, a.xxx.com, I succeed.

Couldn't I forward a secondary domain to another secondary domain?

**Comment by andryyy** [comment]
Can you add alias domains in the demo?

Don't add alias domains that exist as domains.


Am 12. April 2019 04:59:59 schrieb littleplus <notifications@github.com>:

**Comment by littleplus** [comment]
@andryyy Solved, could not add alias domain which exists as a domain.

Thank you for your help.
