### ISSUE TITLE
domain DNS check and ipv6

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#2527]
Hello,

While playing with our mailcow sandbox server, I've activated ipv6 on the machine in order to see how it supports it.

I can see in the admin, on DNS check page for a domain that it seems to say our ipv6 AAAA record doesn't match what it should be.

![ipv6_aaaa_check](https://user-images.githubusercontent.com/5239282/56013164-c5623e80-5cef-11e9-8564-61484b59d166.png)

However, our AAAA record seems correct and match our network interface:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 94.103.96.134  netmask 255.255.255.128  broadcast 94.103.96.255
        inet6 2a00:a500:0:96::134  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::215:5dff:fe37:9891  prefixlen 64  scopeid 0x20<link>
```

```
root@mail00:~# host mail00.swisscenter.com
mail00.swisscenter.com has address 94.103.96.134
mail00.swisscenter.com has IPv6 address 2a00:a500:0:96::134
```

Any idea why the result of the check returns a different value ? Could it be a bug with the code/library used to get the current value ?

Cheers,
Sébastien

**Comment by sriccio** [comment]
Additional info:

To be sure the result is the same in the php-fpm container I've checked the resolution result from inside it:

```
bash-4.4# ping -6 mail00.swisscenter.com
PING mail00.swisscenter.com (2a00:a500:0:96::134): 56 data bytes
64 bytes from 2a00:a500:0:96::134: seq=0 ttl=64 time=0.064 ms
64 bytes from 2a00:a500:0:96::134: seq=1 ttl=64 time=0.088 ms
64 bytes from 2a00:a500:0:96::134: seq=2 ttl=64 time=0.090 ms
```

Edit:
Actually it seems that both formats are valid for the same ipv6, so maybe the library returns it in a different formatting and a only a string comparaison is done, instead of a true "is it the same ipv6 address" comparator ?

```
root@mail00:~# ping 2a00:a500::96:0:0:0:134
PING 2a00:a500::96:0:0:0:134(2a00:a500:0:96::134)
```

**Comment by andryyy** [comment]
Correct data is current state. I see the same addresses here.

**Comment by sriccio** [comment]
Yeah, sorry I mean, I'm not sure if it should display a green check, like for ipv4 address.

The display here (in the attached screenshot on original post) makes me think mailcow thinks it's not the correct address :)

**Comment by andryyy** [comment]
I think we don't do that for v6

Am 12. April 2019 07:55:40 schrieb Sébastien RICCIO <notifications@github.com>:

**Comment by sriccio** [comment]
Okay then it's a non-issue. Sorry for the bothering. Closed :)

**Comment by andryyy** [comment]
No need to be sorry! :O
