### ISSUE TITLE
Admin UI: Aliases not shown

### ISSUE THREAD

**Issue by KarstenHahn** [mailcow/mailcow-dockerized#2528]
Hi,

thanks for this wonderful piece of software!

After migrating to another server accoding your migration docs I was able to show all alias definitions in the AdminUI. After deleting some aliases NO Alias definition is shown in the UI. But the aliases are working correctly. A server stop/start doesn't have any effect.

Have you got a hint for me?

Thanks Karsten

**Comment by andryyy** [comment]
Hi. :) You migrated from another mailcow dockerized installation?

Is there content in the alias table in the database? Any errors in your browser debug console when opening the alias tab?

**Comment by KarstenHahn** [comment]
Wow, very fast reaction :-)

Yes, migration from one mailcow-dockerized server to a newer.

The aliases shoud be in the table, if not a test mail to an alias cannot delivered to the target mailbox. Where I can find the alias table?

There are no errors in the browser debug window -- some warnings:
18:26:44.358 Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. mailbox:20:159
18:26:44.359 Unbekannte Eigenschaft 'orphans'.  Deklaration ignoriert. mailbox:20:2567
18:26:44.359 Unbekannte Eigenschaft 'widows'.  Deklaration ignoriert. mailbox:20:2576
18:26:44.359 Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. mailbox:20:3544
18:26:44.360 Fehler beim Verarbeiten des Wertes für 'outline'.  Deklaration ignoriert. mailbox:20:15466
18:26:44.363 Unbekannte Eigenschaft 'appearance'.  Deklaration ignoriert. mailbox:20:35336
18:26:44.363 Fehler beim Verarbeiten des Wertes für 'margin-top'.  Deklaration ignoriert. mailbox:20:35413
18:26:44.363 Fehler beim Verarbeiten des Wertes für 'outline'.  Deklaration ignoriert. mailbox:20:35876
18:26:44.363 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. mailbox:20:36516
18:26:44.363 Unbekannte Pseudoklasse oder Pseudoelement '-ms-expand'.  Regelsatz wegen ungültigem Selektor ignoriert. mailbox:20:36615
18:26:44.363 Fehler beim Verarbeiten des Wertes für 'margin-top'.  Deklaration ignoriert. mailbox:20:38204
18:26:44.364 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:20:44563
18:26:44.364 Fehler beim Verarbeiten des Wertes für 'outline'.  Deklaration ignoriert. mailbox:20:44678
18:26:44.364 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:44968
18:26:44.364 Fehler beim Verarbeiten des Wertes für 'border-top'.  Deklaration ignoriert. mailbox:20:53131
18:26:44.365 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:54401
18:26:44.365 Fehler beim Verarbeiten des Wertes für 'border-bottom'.  Deklaration ignoriert. mailbox:20:54951
18:26:44.368 Unbekannte Eigenschaft 'zoom'.  Deklaration ignoriert. mailbox:20:84062
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:101253
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:101362
18:26:44.369 Unbekannte Eigenschaft 'appearance'.  Deklaration ignoriert. mailbox:20:101496
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:102348
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:102401
18:26:44.369 Unbekannte Eigenschaft 'line-break'.  Deklaration ignoriert. mailbox:20:103326
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:103540
18:26:44.369 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:103586
18:26:44.369 Unbekannte Eigenschaft 'line-break'.  Deklaration ignoriert. mailbox:20:105145
18:26:44.370 Name einer Medienfunktion erwartet, aber 'transform-3d' gefunden. mailbox:20:107268
18:26:44.370 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:108554
18:26:44.370 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:108696
18:26:44.370 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:108964
18:26:44.370 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:20:109197
18:26:44.370 Fehler beim Verarbeiten des Wertes für 'background-color'.  Deklaration ignoriert. mailbox:20:110140
18:26:44.370 Unerkannte at-Regel oder Fehler beim Verarbeiten der at-Regel '@-ms-viewport'. mailbox:20:112422
18:26:44.371 Fehler beim Verarbeiten des Wertes für 'width'.  Deklaration ignoriert. mailbox:25:95
18:26:44.372 Fehler beim Verarbeiten des Wertes für 'outline'.  Deklaration ignoriert. mailbox:25:1053
18:26:44.372 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:25:3612
18:26:44.372 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:3044
18:26:44.372 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:3192
18:26:44.372 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:3425
18:26:44.372 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:3573
18:26:44.372 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:4020
18:26:44.372 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:4168
18:26:44.372 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:4509
18:26:44.372 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:4657
18:26:44.373 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:5081
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:5229
18:26:44.373 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:5686
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:5834
18:26:44.373 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:6558
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:6706
18:26:44.373 Fehler beim Verarbeiten des Wertes für 'background-image'.  Deklaration ignoriert. mailbox:65:7373
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:65:7521
18:26:44.373 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:73:266
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:73:2633
18:26:44.373 'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. mailbox:73:4242
18:26:44.373 Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. mailbox:73:7826
18:26:44.376 Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. mailbox:73:32695
18:26:44.376 Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. mailbox:73:32721
18:26:44.376 Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. mailbox:73:32743
18:26:44.376 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:73:32875
18:26:44.376 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:73:33266
18:26:44.376 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:73:33944
18:26:44.376 Regelsatz wegen ungültigem Selektor ignoriert. mailbox:73:34087
18:26:44.378 Unbekannte Eigenschaft 'user-select'.  Deklaration ignoriert. mailbox:81:20787
18:26:44.408 Fehler beim Verarbeiten des Wertes für 'display'.  Deklaration ignoriert. mailbox

​

**Comment by KarstenHahn** [comment]
Hi,

the major error sits in front of the computer. I'd filtered the Aliases with a blank. After pressing the x right from the filter box, all works fine. Sorry for that.

Karsten

**Comment by andryyy** [comment]
Oh. 😄 Happens.
