### ISSUE TITLE
[Question] HTML-Signature in SOGo

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#253]
In Settings -> IMAP-Accounts -> Signature you can set a rich text signature but I see no way to create a HTML-code signature.

The next-best-thing I found was entering HTML-code and start mails in plain text mode and switch to HTML to render the signature correctly.

Is there no other way? 😸

**Comment by broedli** [comment]
In principle I don't know any better way to set a HTML signature in sogo.

But just to make sure: if you switch the `Compose Message in` to 'Plaintext' on your Settings -> Mail -> General and copy your HTML signature into the (plaintext) field for your signature and switch `Compose Message in` back to HTML you should not need to start the mail in plaintext mode to render the html correctly. It should work directly ...

When I think about it, this could maybe be possible with the command `sogo-tool user-preferences set defaults 'youruser@domain.tld' SOGoMailSignature '{"SOGoMailSignature":"YOUR_SIGNATURE"}'`. But I'd guess that you will run into problems with sogo's json format and your html code and would need a lot of escaping - I've never tried that ...

And I'm closing this issue. The mailing list for SOGo might be a better place for this question :stuck_out_tongue:

Edit: corrected command.

**Comment by Braintelligence** [comment]
I feared the last sentence 😛 .
I disgust mailing lists ☹️ .
