### ISSUE TITLE
Emails rejected with 554 code are retried

### ISSUE THREAD

**Issue by Mydayyy** [mailcow/mailcow-dockerized#2532]
**Describe the bug, try to make it reproducible**
A remote MTA rejects the email with a 554 error. The rejected email will be queued for further retries, although 5xx errors are not supposed to be retried. Furthermore, the sender was not notified that the e-mail he sent was rejected. I was not able to find any settings which would correct this behavior.

**NOTE:** This issue is not about the the email being rejected, but about how mailcow handles the rejected e-mail

**System information and quick debugging**
General logs:
***@*** (host mx02.t-online.de[194.25.134.9] refused to talk to me: 554 IP=***.***.***.*** - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL))

**Comment by andryyy** [comment]
Cannot reproduce, we need the full logs from that queue id in Postfix.

**Comment by Mydayyy** [comment]
Hi,

thanks for your response.

Are you referring to these logs?:

> postfix-mailcow_1    | Apr 14 19:44:46 mail postfix/smtp[819]: 7DCA065C0A75: host mx01.t-online.de[194.25.134.72] refused to talk to me: 554 IP=* - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL)

> postfix-mailcow_1    | Apr 14 19:44:46 mail postfix/smtp[819]: 7DCA065C0A75: host mx00.t-online.de[194.25.134.8] refused to talk to me: 554 IP=* - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL)

> postfix-mailcow_1    | Apr 14 19:44:46 mail postfix/smtp[819]: 7DCA065C0A75: host mx02.t-online.de[194.25.134.9] refused to talk to me: 554 IP=* - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL)

> postfix-mailcow_1    | Apr 14 19:44:46 mail postfix/smtp[819]: 7DCA065C0A75: to=<*@*>, relay=mx03.t-online.de[194.25.134.73]:25, delay=5558, delays=5557/0.02/0.54/0, dsn=4.0.0, status=deferred (host mx03.t-online.de[194.25.134.73] refused to talk to me: 554 IP=* - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL))

I just like to clarify thats it not about the rejectment (I already notified t-online about that) but about the handling of rejected e-mails as they should not be queued for retry.

**Comment by andryyy** [comment]
All logs of Postfix. There must be a reason why it is not bounced. It works here.

Or at least all logs surrunding 7DCA065C0A75 :)

**Comment by Mydayyy** [comment]
https://i.imgur.com/w26B7At.png

I noticed some strange entries two minutes after my mail got rejected at 7:46. 
Also there seems to be a warning about a missing directory. Could either of those two prevent my mail from being bounced?

**Comment by andryyy** [comment]
Possible.

Please grep that queue ID via "docker-compose logs postfix".

Or just stop mailcow and remove the containers (`docker-compose down`), then remove the Postfix volume by running `docker volume rm mailcowdockerized_postfix-vol-1`. Start mailcow again (`docker-compose up -d`).

**Comment by Mydayyy** [comment]
Here's the grep:

http://paste.debian.net/1077602

I also restarted the service and removed the volume, wrote the email again:
https://i.imgur.com/59nt8jL.png
Still not bounced

But if this is a issue on my side and not, as I initially thought, wrong behavior on receiving a 554 I'll do a little more troubleshooting.

**Comment by andryyy** [comment]
Could be a permission issue, but I’m not sure. You could run a git diff against master for any local changes. 

I cannot reproduce this. If there is anybody reading this with some time to test, I would be happy. :) I blacklisted myself on various destinations and always received a bounce.

**Comment by K2rool** [comment]
I tested it on my server by blacklisted the server on a other mail server I control, it got rejected with 550 postfix defered it 7BAA53FC46: to=<ryan@****.******.uk>, relay=*******.uk[159.69.***.***]:25, delay=2.3, delays=1.2/0.84/0.24/0, dsn=4.0.0, status=deferred (host ****.***.uk[159.69.****.***] refused to talk to me: 550 Mail from 185.121.**.*** is blacklisted on this server.)

**Comment by andryyy** [comment]
Compare your main.cf and master.cf to the repository and post it here. 

Perhaps you have older code in these files. It is correctly bounced on my dev machine.

**Comment by andryyy** [comment]
Please also write how exactly this mail was sent. Over SOGo? Submission? SMTPS? TLS outgoing enforced?

**Comment by Ry3nlNaToR** [comment]
The mail was sent via Sogo but via Submission it dose the same, my Postfix config been changed a bit since I changed a few lines.

<pre>
smtpd_recipient_restrictions = reject_unknown_recipient_domain, check_recipient_mx_access cidr:/opt/postfix/conf/smarthost, permit_sasl_authenticated, permit_mynetworks, check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf, reject_invalid_helo_hostname, reject_unknown_reverse_client_hostname, reject_unauth_destination
smtpd_sender_restrictions = reject_unknown_sender_domain, permit_mynetworks, reject_non_fqdn_sender, reject_authenticated_sender_login_mismatch
smtp_sasl_password_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_sender_dependent.cf, hash:/opt/postfix/conf/smarthost_passwd
</pre>

The check_recipient_mx_access is there to force mail sent to certain ip range via a relay using filter in my case Outlook/Hotmail like this <pre>52.100.0.0/14 FILTER smtp:[email-smtp.eu-west-1.amazonaws.com]:587
....</pre>

p.s This is my 2nd account @K2rool is my other account.

**Comment by andryyy** [comment]
Can you post your complete master.cf and main.cf? :)

**Comment by Ry3nlNaToR** [comment]
main.cf
<pre>
biff = no
append_dot_mydomain = no
smtpd_tls_cert_file = /etc/ssl/mail/cert.pem
smtpd_tls_key_file = /etc/ssl/mail/key.pem
smtpd_use_tls=yes
smtpd_tls_received_header = yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 [fe80::]/10 [fc00::]/7
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
bounce_queue_lifetime = 1d
broken_sasl_auth_clients = yes
disable_vrfy_command = yes
maximal_backoff_time = 1800s
maximal_queue_lifetime = 1d
message_size_limit = 104857600
milter_default_action = accept
milter_protocol = 6
minimal_backoff_time = 300s
plaintext_reject_code = 550
postscreen_access_list = permit_mynetworks, cidr:/opt/postfix/conf/postscreen_access.cidr, tcp:127.0.0.1:10027
postscreen_bare_newline_enable = no
postscreen_blacklist_action = drop
postscreen_cache_cleanup_interval = 24h
postscreen_cache_map = proxy:btree:$data_directory/postscreen_cache
postscreen_dnsbl_action = enforce
postscreen_dnsbl_sites = b.barracudacentral.org=127.0.0.2*7 dnsbl.inps.de=127.0.0.2*7 bl.mailspike.net=127.0.0.2*5 bl.mailspike.net=127.0.0.[10;11;12]*4 dnsbl.sorbs.net=127.0.0.10*8 dnsbl.sorbs.net=127.0.0.5*6 dnsbl.sorbs.net=127.0.0.7*3 dnsbl.sorbs.net=127.0.0.8*2 dnsbl.sorbs.net=127.0.0.6*2 dnsbl.sorbs.net=127.0.0.9*2 zen.spamhaus.org=127.0.0.[10;11]*8 zen.spamhaus.org=127.0.0.[4..7]*6 zen.spamhaus.org=127.0.0.3*4 zen.spamhaus.org=127.0.0.2*3 hostkarma.junkemailfilter.com=127.0.0.2*3 hostkarma.junkemailfilter.com=127.0.0.4*1 hostkarma.junkemailfilter.com=127.0.1.2*1 wl.mailspike.net=127.0.0.[18;19;20]*-2 hostkarma.junkemailfilter.com=127.0.0.1*-2
postscreen_dnsbl_threshold = 8
postscreen_dnsbl_ttl = 5m
postscreen_greet_action = enforce
postscreen_greet_banner = $smtpd_banner
postscreen_greet_ttl = 2d
postscreen_greet_wait = 3s
postscreen_non_smtp_command_enable = no
postscreen_pipelining_enable = no
proxy_read_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_tls_policy_override_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_sender_dependent_default_transport_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_transport_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_sender_dependent.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_transport_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_sender_bcc_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_recipient_bcc_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_recipient_canonical_maps.cf,
  $local_recipient_maps,
  $mydestination,
  $virtual_alias_maps,
  $virtual_alias_domains,
  $virtual_mailbox_maps,
  $virtual_mailbox_domains,
  $relay_recipient_maps,
  $relay_domains,
  $canonical_maps,
  $sender_canonical_maps,
  $recipient_canonical_maps,
  $relocated_maps,
  $transport_maps,
  $mynetworks,
  $smtpd_sender_login_maps
queue_run_delay = 300s
relay_domains = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_relay_domain_maps.cf
relay_recipient_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_relay_recipient_maps.cf
sender_dependent_default_transport_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_sender_dependent_default_transport_maps.cf
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_cert_file = /etc/ssl/mail/cert.pem
smtp_tls_key_file = /etc/ssl/mail/key.pem
smtp_tls_loglevel = 1
smtp_dns_support_level = dnssec
smtp_tls_security_level = dane
smtpd_data_restrictions = reject_unauth_pipelining, permit
smtpd_delay_reject = yes
smtpd_error_sleep_time = 10s
smtpd_hard_error_limit = ${stress?1}${stress:5}
smtpd_helo_required = yes
smtpd_proxy_timeout = 600s
smtpd_recipient_restrictions = reject_unknown_recipient_domain, check_recipient_mx_access cidr:/opt/postfix/conf/smarthost, permit_sasl_authenticated, permit_mynetworks, check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf, reject_invalid_helo_hostname, reject_unknown_reverse_client_hostname, reject_unauth_destination
smtpd_sasl_auth_enable = yes
smtpd_sasl_authenticated_header = yes
smtpd_sasl_path = inet:dovecot:10001
smtpd_sasl_type = dovecot
smtpd_sender_login_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf
smtpd_sender_restrictions = reject_unknown_sender_domain, permit_mynetworks, reject_non_fqdn_sender, reject_authenticated_sender_login_mismatch
smtpd_soft_error_limit = 3
smtpd_tls_auth_only = yes
smtpd_tls_dh1024_param_file = /etc/ssl/mail/dhparams.pem
smtpd_tls_eecdh_grade = auto
smtpd_tls_exclude_ciphers = ECDHE-RSA-RC4-SHA, RC4, aNULL, DES-CBC3-SHA, ECDHE-RSA-DES-CBC3-SHA, EDH-RSA-DES-CBC3-SHA
smtpd_tls_loglevel = 1

smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_protocols = !SSLv2, !SSLv3

lmtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
lmtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1

smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtpd_tls_protocols = !SSLv2, !SSLv3

smtpd_tls_security_level = may
tls_preempt_cipherlist = yes
tls_ssl_options = NO_COMPRESSION
smtpd_tls_mandatory_ciphers = high
virtual_alias_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_alias_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_spamalias_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_alias_domain_maps.cf,
  proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_alias_domain_catchall_maps.cf
virtual_gid_maps = static:5000
virtual_mailbox_base = /var/vmail/
virtual_mailbox_domains = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_domains_maps.cf
recipient_bcc_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_recipient_bcc_maps.cf
sender_bcc_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_sender_bcc_maps.cf
recipient_canonical_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_recipient_canonical_maps.cf
recipient_canonical_classes = envelope_recipient
virtual_mailbox_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_virtual_mailbox_maps.cf
virtual_minimum_uid = 104
virtual_transport = lmtp:inet:dovecot:24
virtual_uid_maps = static:5000
smtpd_milters = inet:rspamd:9900
non_smtpd_milters = inet:rspamd:9900
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
mydestination = localhost.localdomain, localhost
#content_filter=zeyple
# Prefere IPv4, useful for v4-only envs
smtp_address_preference = ipv4
smtp_sender_dependent_authentication = yes
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_sender_dependent.cf, hash:/opt/postfix/conf/smarthost_passwd
smtp_sasl_security_options = 
smtp_sasl_mechanism_filter = plain, login
smtp_tls_policy_maps=proxy:mysql:/opt/postfix/conf/sql/mysql_tls_policy_override_maps.cf
smtp_header_checks = pcre:/opt/postfix/conf/anonymize_headers.pcre
mail_name = Postcow
transport_maps = pcre:/opt/postfix/conf/local_transport, proxy:mysql:/opt/postfix/conf/sql/mysql_transport_maps.cf
smtp_sasl_auth_soft_bounce = no
</pre>

master.cf
<pre>
smtp       inet  n       -       n       -       1       postscreen
smtpd      pass  -       -       n       -       -       smtpd
  -o smtpd_helo_restrictions=permit_mynetworks,reject_non_fqdn_helo_hostname
  -o smtpd_sasl_auth_enable=no
  -o smtpd_sender_restrictions=permit_mynetworks,reject_unlisted_sender,reject_unknown_sender_domain
smtps    inet  n       -       n       -       -       smtpd
  -o smtpd_tls_wrappermode=yes
  -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
  -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3
  -o tls_preempt_cipherlist=yes
submission inet n       -       n       -       -       smtpd
  -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
  -o smtpd_enforce_tls=yes
  -o smtpd_tls_security_level=encrypt
  -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3
  -o tls_preempt_cipherlist=yes
588 inet n      -       n       -       -       smtpd
  -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
  -o smtpd_tls_auth_only=no
  -o smtpd_sender_restrictions=check_sasl_access,regexp:/opt/postfix/conf/allow_mailcow_local.regexp,reject_authenticated_sender_login_mismatch,permit_mynetworks,permit_sasl_authenticated,reject_unlisted_sender,reject_unknown_sender_domain
590 inet n      -       n       -       -       smtpd
  -o smtpd_client_restrictions=permit_mynetworks,reject
  -o smtpd_tls_auth_only=no
  -o smtpd_milters=
  -o non_smtpd_milters=
smtp_enforced_tls      unix  -       -       n       -       -       smtp
  -o smtp_tls_security_level=encrypt
  -o syslog_name=enforced-tls-smtp
  -o smtp_delivery_status_filter=pcre:/opt/postfix/conf/smtp_dsn_filter
smtp_via_transport_maps      unix  -       -       n       -       -       smtp
  -o smtp_sasl_password_maps=proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_transport_maps.cf

tlsproxy   unix  -       -       n       -       0       tlsproxy
dnsblog    unix  -       -       n       -       0       dnsblog
pickup     fifo  n       -       n       60      1       pickup
cleanup    unix  n       -       n       -       0       cleanup
qmgr       fifo  n       -       n       300     1       qmgr
tlsmgr     unix  -       -       n       1000?   1       tlsmgr
rewrite    unix  -       -       n       -       -       trivial-rewrite
bounce     unix  -       -       n       -       0       bounce
defer      unix  -       -       n       -       0       bounce
trace      unix  -       -       n       -       0       bounce
verify     unix  -       -       n       -       1       verify
flush      unix  n       -       n       1000?   0       flush
proxymap   unix  -       -       n       -       -       proxymap
proxywrite unix  -       -       n       -       1       proxymap
smtp       unix  -       -       n       -       -       smtp
relay      unix  -       -       n       -       -       smtp
showq      unix  n       -       n       -       -       showq
error      unix  -       -       n       -       -       error
retry      unix  -       -       n       -       -       error
discard    unix  -       -       n       -       -       discard
local      unix  -       n       n       -       -       local
virtual    unix  -       n       n       -       -       virtual
lmtp       unix  -       -       n       -       -       lmtp
anvil      unix  -       -       n       -       1       anvil
scache     unix  -       -       n       -       1       scache
maildrop   unix  -       n       n       -       -       pipe flags=DRhu
    user=vmail argv=/usr/bin/maildrop -d ${recipient}

# start zeyple
zeyple    unix  -       n       n       -       -       pipe
  user=zeyple argv=/usr/local/bin/zeyple.py ${recipient}
127.0.0.1:10026 inet  n       -       n       -       10      smtpd
  -o content_filter=
  -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks,no_milters
  -o smtpd_helo_restrictions=
  -o smtpd_client_restrictions=
  -o smtpd_sender_restrictions=
  -o smtpd_recipient_restrictions=permit_mynetworks,reject
  -o mynetworks=127.0.0.0/8
  -o smtpd_authorized_xforward_hosts=127.0.0.0/8
# end zeyple

# start whitelist_fwd
127.0.0.1:10027 inet n n n - 0 spawn user=nobody argv=/usr/local/bin/whitelist_forwardinghosts.sh
# end whitelist_fwd

# start watchdog-specific
589 inet n      -       n       -       -       smtpd
  -o smtpd_client_restrictions=permit_mynetworks,reject
  -o syslog_name=watchdog
  -o syslog_facility=local7
  -o smtpd_milters=
  -o cleanup_service_name=watchdog_cleanup
  -o non_smtpd_milters=
watchdog_cleanup unix  n       -       n       -       0       cleanup
  -o syslog_name=watchdog
  -o syslog_facility=local7
  -o queue_service_name=watchdog_qmgr
watchdog_qmgr fifo  n       -       n       300     1       qmgr
  -o syslog_facility=local7
  -o syslog_name=watchdog
  -o rewrite_service_name=watchdog_rewrite
watchdog_rewrite    unix  -       -       n       -       -       trivial-rewrite
   -o syslog_facility=local7
   -o syslog_name=watchdog
   -o local_transport=watchdog_discard
watchdog_discard    unix  -       -       n       -       -       discard
   -o syslog_facility=local7
   -o syslog_name=watchdog

# end watchdog-specific

</pre>

**Comment by Ry3nlNaToR** [comment]
I found want is causing this issue Postfix by default will bounce it if its rejected after helo/from/rcpt/data but if it rejected right on smtp connect like this Postfix ignores the 5XX and defer it you can make it bounce it.

From Postfix man http://www.postfix.org/postconf.5.html#smtp_skip_5xx_greeting
<pre>
smtp_skip_5xx_greeting (default: yes)

    Skip remote SMTP servers that greet with a 5XX status code.

    By default, the Postfix SMTP client moves on the next mail exchanger. Specify "smtp_skip_5xx_greeting = no" if Postfix should bounce the mail immediately. Caution: the latter behavior appears to contradict RFC 2821.
</pre>

The manual says turning it appears to contradict RFC 2821 but server only 5XX when they reject mail so it should be fine.

**Comment by Mydayyy** [comment]
I will be able confirm this later in the evening but I guess thats pretty much the problem.

I also stumbled across the following documentation on t-online postmaster faq which would confirm it:

<br/>

> Why was the establishment of an SMTP connection rejected by the t-online.de server?
> --
> If the t-online.de server terminates an SMTP connection after outputting the message "554 IP=[SENDER-IP] - A problem occurred. [...]", the specified IP address is blocked from delivering e-mails. A block may be in place, in particular, if you want to use an IP address that you have not previously used for sending e-mails; this may therefore have been caused a long time ago.With some MTAs, the relevant error message may not appear on your system because the t-online.de server disables the connection immediately after outputting the message and older systems class this behavior as a temporary error, meaning that further delivery attempts will be made according to the configuration of these MTAs.If you have resolved the problem that caused the error or do not believe there is a problem, please contact the dedicated contact person specified in the error message. You can also reach this person via any of our listed systems. Alternatively, you can use our online form to contact us.

**Comment by andryyy** [comment]
It always bounces instantly here. That’s what it should do. Please checkout the whole postfix config folder in the repository.

**Comment by Ry3nlNaToR** [comment]
Andryyy how are you testing it postfix will bounce it normally but not if the remote server greets with 5xx banner.

You want me email on your servercow.de email address and I will give you test email address that reject with 5xx banner that postfix will defer.

**Comment by andryyy** [comment]
Caution: the latter behavior appears to contradict RFC 2821.

Better keep it the way it is. 

I understand the problem now. :)

**Comment by Ry3nlNaToR** [comment]
I don't see any real issue setting smtp_skip_5xx_greeting to no, the only time a remote server will return a 5xx banner is when they don't want to receive mail from your ip address server and a not even interested on from or receipt info it just seem a bit pointless keep retrying if the server returns a 5xx you only going to know the mail got rejected this way if you look at the logs or wait one day for maximal_queue_lifetime.

I've noticed a few mail provider and mail ISP server reject on greeting I tested it from a Spamhuas listed ip my home IP which is listed on Spamhuas PBL like most home IP are listed.

Gmx/1&1
T-mobile (Deutsche Telekom)
Liberty Global (Virgin Media, UPC)
Rackspace mail hosting
OpenSRS (Tucows)

**Comment by Mydayyy** [comment]
From my side this issue is resolved. Although I side with Ry3nlNaToR that the default should be to bounce those mails immediately, but in the end its something which can be solved with postfix configuration.

Thanks to both of you for your quick response (:
