### ISSUE TITLE
Relayhost for Domain Alias

### ISSUE THREAD

**Issue by jlelse** [mailcow/mailcow-dockerized#2536]
Currently it's possible to set a relayhost for domains. Do they also apply to alias domains for that domain? And is it possible to set a relayhost for some alias domains only?

**Comment by andryyy** [comment]
They apply to alias domains but you cannot apply them to alias domains only.

**Comment by jlelse** [comment]
Thank you for the quick reply!

**Comment by andryyy** [comment]
You are welcome. :)
