### ISSUE TITLE
"HANGUP after 0 in tests before SMTP handshake" Spam in Server Log

### ISSUE THREAD

**Issue by NoobKeksTV** [mailcow/mailcow-dockerized#2537]
Hello,

A few minutes ago my mailserver stopped working and i didn't received my xenforo messages wich are send using my mailcow server. I checked my Server Log and it Spammed something in the log as you can see in the screenshot:
https://cdn.egopvp.com/nextcloud/index.php/s/ooXP8PgxXmmttXt/preview

What is happening there? Its doing this stuff for over 30minutes now and it doesn't stop doing it.

**Comment by NoobKeksTV** [comment]
Important to know is that 194.59.207.61 is my Server's IP Adress!

**Comment by andryyy** [comment]
Do you know this IP? If not, you should ban it. Check the mailcow UI, find the Fail2ban section. 

Mit besten Grüßen
André Peters

**Comment by andryyy** [comment]
Ok, then you should really check why your server is flooding your mailcow.

**Comment by NoobKeksTV** [comment]
I just realized that i have a Discord bot running which check some services of mine if theire online. (Ping) the timestamps would fit because the bot ping all the selected services every 10seconds...
And after i stopped the bot the Spam stopped. 
silly me.... Sorry for any trouble! But thanks for the advice! Maybe it will become handy for me in the future.
