### ISSUE TITLE
Allow fields to be excluded from DKIM signing

### ISSUE THREAD

**Issue by 4ley** [mailcow/mailcow-dockerized#2538]
Using Amazon's SES SMTP interface as relay, I would like to have the option to sign the messages via mailcow.

Requirements stated in the AWS documentation on [Manual DKIM Signing](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/manual-dkim.html) are as follows
- messages should include two DKIM headers: one for your domain, and one for amazonses.com
- don't sign the following fields: Message-ID, Date, Return-Path, Bounces-To

In order to make this work, mailcow would need an option to exclude fields to be signed.

**Comment by mkuron** [comment]
You can configure that in https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/dkim_signing.conf. We can't make it an option in the admin GUI though because the config comes from a file, not the database.
