### ISSUE TITLE
Lets Encrypt for backup MX?

### ISSUE THREAD

**Issue by haukebruno** [mailcow/mailcow-dockerized#2539]
Hey there,

I noticed that all of the ACME LE magic isn't fired at all for domains configured as _Backup MX_.

So my question is, whether this is a bug or a feature :smiley_cat: 

My "use case" here is, that I use multiple domains on my mailcows and do not want to point the backup MX records to the _real_ servers name rather than to an A record (e.g. _bmx.example.org_) for the specific domain. And best case my backup MX cow also allows mailservers to connect to it via TLS.

`ADDITIONAL_SAN` is set up properly (it works without configuring the domain as backup MX)

**Comment by mkuron** [comment]
There is no point to generating the autodiscover SANs for backup domains, but `ADDITIONAL_SAN`s should still be respected. So this is definitely a bug.

**Comment by andryyy** [comment]
ADDITIONAL_SAN works. Check the mailcow.conf to .env symlink.

**Comment by haukebruno** [comment]
Sure, after disabling Backup MX the `ADDITIONAL_SAN` config works and the acme container creates the certs. But with a enabled Backup MX it doesn't.
