### ISSUE TITLE
how to send mail from host

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2543]
Hi
I installed mailcow dockerized. Is working very good for all external email.
However I can't send email from applications running in the same host server, for example from other docker containers or php applications running on the main host. terminal mail also does nott work.

Should I configure the SMTP with local host or with the IP from from mailcow? Thanks a lot!

**Comment by mkuron** [comment]
See https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/
