### ISSUE TITLE
Mem error with /usr/local/bin/quarantine notify.py

### ISSUE THREAD

**Issue by mister-man** [mailcow/mailcow-dockerized#2545]
**Describe the bug, try to make it reproducible**
A clear and concise description of what the bug is. How can it be reproduced? 
If applicable, add screenshots to help explain your problem. Very useful for bugs in mailcow UI.

I installed mailcow for a few days and configured 4 domains. After a few days the Server runs out of ram (8GB Ram and 8 GB Swap) and cpu time (4 cores 100%).

In htop it seems the ressources are blocked by "/usr/local/bin/quarantine notify.py"

![image](https://user-images.githubusercontent.com/8549816/56435530-0e5e5800-62d9-11e9-8e7c-a1c5b3cd005b.png)

If I run update.sh, the server runs a few days without errors.

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?)
Opensuse Leap 15

 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)
vServer, it seems KVM

 - Your server/VM specifications (Memory, CPU Cores)
4 Cores
8 GB Ram
8 GB Swap

 - Don't try to run mailcow on a Synology or QNAP NAS, do you?
No

 - Docker and Docker Compose versions

 - Output of `git diff origin/master`, any other changes to the code?
No

**Comment by andryyy** [comment]
Hm. Interesting bug. 

Can you try to find the script in the dovecot-mailcow log output?

What happens when you run the script inside the Docecot container as user vmail? Does it finish?
Something like that (in mobile rn):

docker-compose exec dovecot-mailcow /bin/bash
su -s /bin/bash vmail
/usr/local/blabla/quarantine_bla.py

**Comment by mister-man** [comment]
I try it later... the serevr is currently out of ressources. I can't connect via SSH :(
Most time after one or two h it workes

**Comment by mister-man** [comment]
Same error with 

docker-compose exec dovecot-mailcow /bin/bash
su -s /bin/bash vmail
/usr/local/blabla/quarantine_bla.py


Whre can I find the right log?

**Comment by mister-man** [comment]
@andryyy

Which log do you mean?

**Comment by laurent-so-1** [comment]
Maybe this can help anyone, I encountered the same issue on my installation.

Apart having the quarantine system enabled, I implemented _smtpd_helo_restrictions_ on Postfix (`data/conf/postfix/main.cf`) as below:
```
smtpd_helo_restrictions = permit_sasl_authenticated,
  reject_unknown_helo_hostname,
  reject_invalid_helo_hostname
```


As consequences, `quarantine_notify.py` is unable to sent any mail and goes on infinite loop.
I (temporarly) fixed it by adding the hostname in the `server.ehlo()` function within the script.
After a restart, no more issue :)

```
docker-compose exec dovecot-mailcow /bin/sed -i "s,server.ehlo(),server.ehlo(name='mail.example.com'),g"  /usr/local/bin/quarantine_notify.py
docker-compose restart dovecot-mailcow
```

**Comment by andryyy** [comment]
Thank you. We can also override the helo checks in master.cf for the quarantine smtpd service. Probably easier. :) You won't need to change the script to use your changes then, too.

**Comment by laurent-so-1** [comment]
I just made the changes in Postfix and revert back the script. Test is ok.
Indeed, better not to change the script, thank you!

**Comment by andryyy** [comment]
You are welcome. Sorry, forgot to reference this issue.

**Comment by maxxie85** [comment]
Hello,

I seem to run into a similar problem.
I have the quarantine system enabled en the first mail came in today that got moved to the quarantine. 

However I noticed extreem slowdown on my server and saw that the quarantine-notify.py was causing the issue.

Log output from dovecot
`Could not determine last notification for [email_adress], assuming never`
`Notifying [email-adress] about 1 new items in quarantine`

And then an infinite amount of
`(554, b'5.7.1 <mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[172.82.1.250]>: Client host rejected: Access denied'), '': (501, b'5.1.3 Bad recipient address syntax')}
`

When I'm looking at the script it looks like its using the user "quarantine" which is not active or excisting. 

I have run the update script and its still happening.

**Comment by JanMalte** [comment]
> I just made the changes in Postfix and revert back the script. Test is ok.
> Indeed, better not to change the script, thank you!

I had the quarantine_notify.py eating up all the memory today. Can you tell me a little more detailed what you've changed to fix the memory consumption of the script?

```
user@host /srv/mailcow-dockerized # docker-compose exec dovecot-mailcow /bin/bash
root@mail:/# su -s /bin/bash vmail 
vmail@mail:/$ /usr/local/bin/quarantine_notify.py --help
Could not determine last notification for mail@malte-gerth.de, assuming never
Could not determine last notification for testing@malte-gerth.de, assuming never
Notifying testing@malte-gerth.de about 2 new items in quarantine
{'testing@malte-gerth.de': (554, b'5.7.1 <mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[172.5.1.250]>: Client host rejected: Access denied')}

# ... 

{'testing@malte-gerth.de': (554, b'5.7.1 <mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[172.5.1.250]>: Client host rejected: Access denied')}
^CTraceback (most recent call last):
  File "/usr/local/bin/quarantine_notify.py", line 90, in notify_rcpt
    server.sendmail(msg['From'], str(rcpt), text)
  File "/usr/lib/python3.7/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'testing@malte-gerth.de': (554, b'5.7.1 <mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[172.5.1.250]>: Client host rejected: Access denied')}
vmail@mail:/$ 
```
