### ISSUE TITLE
ACME cannot connect

### ISSUE THREAD

**Issue by flopes89** [mailcow/mailcow-dockerized#2546]
Unfortunately I doubt this can be reproduced, but I'm at a loss right now.

Basically, the ACME container cannot connect to the server where mailcow is hosted.

The server is running, everything works, but for some reason ACME fails with `Confirmed A record 116.203.76.148, but HTTP validation failed`

This should demonstrate it quite nicely:

```
flopes@srv1:~/mailcow-dockerized$ curl -v -4 http://verdan.de
* Rebuilt URL to: http://verdan.de/
*   Trying 116.203.76.148...
* TCP_NODELAY set
* Connected to verdan.de (116.203.76.148) port 80 (#0)
> GET / HTTP/1.1
> Host: verdan.de
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Sat, 20 Apr 2019 10:53:00 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://verdan.de/
* Connection #0 to host verdan.de left intact
flopes@srv1:~/mailcow-dockerized$ sudo docker-compose exec acme-mailcow curl -v -4 http://verdan.de
*   Trying 116.203.76.148...
* TCP_NODELAY set
* connect to 116.203.76.148 port 80 failed: Operation timed out
* Failed to connect to verdan.de port 80: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to verdan.de port 80: Operation timed out
flopes@srv1:~/mailcow-dockerized$
```

So... it can resolve the domain to an IP which means DNS is working, but then fails to connect...?!

Now my first thought was that maybe ACME couldn't connect to the internet, but no, that works fine:

```
flopes@srv1:~/mailcow-dockerized$ sudo docker-compose exec acme-mailcow curl -v -4 http://google.de
[sudo] password for flopes:
*   Trying 172.217.16.131...
* TCP_NODELAY set
* Connected to google.de (172.217.16.131) port 80 (#0)
> GET / HTTP/1.1
> Host: google.de
> User-Agent: curl/7.63.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.de/
< Content-Type: text/html; charset=UTF-8
< Date: Sat, 20 Apr 2019 11:10:34 GMT
< Expires: Mon, 20 May 2019 11:10:34 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 218
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
<
```

So... No clue what to do here. Any creative ideas?

**Comment by andryyy** [comment]
See the other issues regarding similar problems. Check your firewall. 

Make sure you configure it accordingly. That’s not something mailcow handles for you. :) Probably ufw or firewalld. But you didn’t provide any iptables output, so I don’t know. 

It is absolutely possible that you can resolve a name but not connect. Both actions are independent of each other.

**Comment by flopes89** [comment]
Okay I'm sorry, this is a bit emberassing. I checked ufw and port 80 was indeed not opened.

I'm still confused as to why my `curl` check outside of docker worked though...?
