### ISSUE TITLE
Migrating Two Users into One

### ISSUE THREAD

**Issue by X1Aaron** [mailcow/mailcow-dockerized#2551]
I have 2 users:

alice@domain.com
bob@domain.com

I want to "merge" both users into hello@domain.com, but I can't figure out how to export\import emails from alice/bob so I can import them into hello.

**Comment by hachre** [comment]
You can use `doveadm` for this but it's not very straightforward.

If you haven't changed the mail format, this should work:

```
cd /opt/mailcow-dockerized
docker-compose exec dovecot-mailcow doveadm -v sync -1 -R -u hello@domain.com maildir:/var/vmail/domain.com/alice
docker-compose exec dovecot-mailcow doveadm -v sync -1 -R -u hello@domain.com maildir:/var/vmail/domain.com/bob
```

This should copy all mails into the `hello@domain.com` mailbox, while leaving them intact in the source mailboxes and also leaving currently existing mails intact in the destination mailbox.

**Comment by X1Aaron** [comment]
Thanks! I’ll try it when I get home in a couple hours :)

**Comment by X1Aaron** [comment]
I tried it, the commands seem to have run, but nothing has changed, and it seems like nothing happened.

No output even with verbose is on. Restarting Mailcow didn't help.

**Comment by X1Aaron** [comment]
Sometime the simplest solution, is the best solution. Connected all 3 accounts in Thunderbird, and move the mail over in Thunderbird :)

**Comment by hachre** [comment]
Strange, but glad you found a solution!
