### ISSUE TITLE
Automatic PGP Encryption for incomming Emails

### ISSUE THREAD

**Issue by frommMoritz** [mailcow/mailcow-dockerized#2552]
**Is your feature request related to a problem? Please describe.**
Given your laptop is encrypted, may be even your server, and you have a strong password in front of your Mailserver. This is cool, but won't help you much if an attacker is able to somehow sniff your password or simply steal your device while unlocked. This is threatening and you can't help it much if messages are simply decryptable by a password stored somewhere on your unlocked device (as proposed in #410 with the usage of the `tree` Plugin for dovecot) .
For me it is NOT an issue with trusting the person storing my E-Mail, but with the fact that  I have to trust in my Server not getting breached, my Provider not taking a look on my storage drive, not having an malicious Program sniffing the key for on Server en- and decryption of my Private E-Mails!

**Describe the solution you'd like**
I would like to see the option of encrypting all incoming, unencrypted, E-Mail via GPG/PGP to a user provided GPG/PGP key, because on device encryption offers (IMO) the highest degree of security because the decryption key never leaves your device.

**Comment by mkuron** [comment]
See #797 and #1791. zeyple lets you do that, but it‘s a very advanced feature that won‘t be available through the GUI in Mailcow.
