### ISSUE TITLE
Mail to mailbox rejected, one of two aliases is delivered

### ISSUE THREAD

**Issue by jaapvdv** [mailcow/mailcow-dockerized#2553]
Mail sent to active mailbox: helpdesk@domain.nl is rejected with a 550 error: Recipient address rejected: User unknown in virtual mailbox table

Mail sent to an alias (flowsparks@eisergon.nl) of helpdesk@domain.nl is also rejected.

A message sent to a second alias (e-campus@domain.nl)  of helpdesk@domain.nl does get delivered.

**System information and quick debugging**
 - Your OS: Ubuntu 18.0.4.2 LTS
 - Your virtualization technology : VM running on ProxMox 5.4.3
 - Your server/VM specifications: 5GB/2 Sockets / 2 Cores
 - Docker and Docker Compose versions: 
Docker version 18.09.5, build e8ff056
docker-compose version 1.24.0, build 0aa59064

**Comment by andryyy** [comment]
You need to post postfix-mailcow logs for each case, please. :)

**Comment by jaapvdv** [comment]
Hmm, further investigation showed only the mails addressed to e-campus@domain.nl in the postfix logs, the other addresses were not mentioned in the postfix logs.

That made me realize the issue was **not** a MailCow one. 

My (external) SPAM filter did not recognize the two rejected mail addresses as valid addresses. After adding them to the list of valid addresses everything is fine.

**Comment by andryyy** [comment]
Nice. :) Can we close this?
