### ISSUE TITLE
MailBox + Forward ?

### ISSUE THREAD

**Issue by ZARk-be** [mailcow/mailcow-dockerized#2554]
Hello,

I looked around the documentation and around the interfaces, but couldn't find an answer to my question. Seeing the database for the table "alias", i think it might be possible, but before attempting anything i thought i'd write something first...

Is it possible to have a mailbox with a forward ?
Ex: info@example.com which is a normal mailbox, but also forwards incoming mails to foo@example.com  ?

I know this isn't very good practice (better to put info@ as a straight-up alias, but for migrating an existing configuration this would be handy while things get cleaned up).

**Comment by andryyy** [comment]
Hi, use sieve. You can create a forwarder via sieve in SOGo, too.
