### ISSUE TITLE
GZIP Eroor while installation

### ISSUE THREAD

**Issue by den1982** [mailcow/mailcow-dockerized#2555]
Hello,

i get a gzip error during the docker-compose up -d installation phase:

`Processing triggers for ca-certificates (20161130+nmu1+deb9u1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   263  100   263    0     0   4534      0 --:--:-- --:--:-- --:--:--  4614

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Service 'dovecot-mailcow' failed to build: The command '/bin/sh -c apt-get update && apt-get -y --no-install-recommends install   automake   autotools-dev   build-essential   ca-certificates   cpanminus   curl   default-libmysqlclient-dev   dnsutils   gettext   jq   libjson-webtoken-perl   libcgi-pm-perl   libcrypt-openssl-rsa-perl   libdata-uniqid-perl   libhtml-parser-perl   libmail-imapclient-perl   libparse-recdescent-perl   libsys-meminfo-perl   libtest-mockobject-perl   libwww-perl   libauthen-ntlm-perl   libbz2-dev   libcrypt-ssleay-perl   libcurl4-openssl-dev   libdbd-mysql-perl   libdbi-perl   libdigest-hmac-perl   libexpat1-dev   libfile-copy-recursive-perl   libio-compress-perl   libio-socket-inet6-perl   libio-socket-ssl-perl   libio-tee-perl   libipc-run-perl   libldap2-dev   liblockfile-simple-perl   liblz-dev   liblz4-dev   liblzma-dev   libmodule-scandeps-perl   libnet-ssleay-perl   libpam-dev   libpar-packer-perl   libreadonly-perl   libssl-dev   libterm-readkey-perl   libtest-pod-perl   libtest-simple-perl   libtry-tiny-perl   libunicode-string-perl   libproc-processtable-perl   libtest-nowarnings-perl   libtest-deep-perl   libtest-warn-perl   libregexp-common-perl   liburi-perl   lzma-dev   python-html2text   python-jinja2   python-mysql.connector   python-redis   make   mysql-client   procps   supervisor   cron   redis-server   syslog-ng   syslog-ng-core   syslog-ng-mod-redis   && rm -rf /var/lib/apt/lists/*   && curl https://www.dovecot.org/releases/2.3/dovecot-$DOVECOT_VERSION.tar.gz | tar xvz    && cd dovecot-$DOVECOT_VERSION   && ./configure --with-solr --with-mysql --with-ldap --with-lzma --with-lz4 --with-ssl=openssl --with-notify=inotify --with-storages=mdbox,sdbox,maildir,mbox,imapc,pop3c --with-bzlib --with-zlib --enable-hardening   && make -j3   && make install   && make clean   && cd .. && rm -rf dovecot-$DOVECOT_VERSION   && curl https://pigeonhole.dovecot.org/releases/2.3/dovecot-2.3-pigeonhole-$PIGEONHOLE_VERSION.tar.gz | tar xvz    && cd dovecot-2.3-pigeonhole-$PIGEONHOLE_VERSION   && ./configure   && make -j3   && make install   && make clean   && cd ..   && rm -rf dovecot-2.3-pigeonhole-$PIGEONHOLE_VERSION   && cpanm Data::Uniqid Mail::IMAPClient String::Util   && groupadd -g 5000 vmail   && groupadd -g 401 dovecot   && groupadd -g 402 dovenull   && useradd -g vmail -u 5000 vmail -d /var/vmail   && useradd -c "Dovecot unprivileged user" -d /dev/null -u 401 -g dovecot -s /bin/false dovecot   && useradd -c "Dovecot login user" -d /dev/null -u 402 -g dovenull -s /bin/false dovenull   && touch /etc/default/locale   && apt-get purge -y build-essential automake autotools-dev default-libmysqlclient-dev libbz2-dev libcurl4-openssl-dev libexpat1-dev liblz-dev liblz4-dev liblzma-dev libpam-dev libssl-dev lzma-dev   && apt-get autoremove --purge -y   && rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2`

I think the problem is in the dovecot docker file. Does anyone have an idea why?

**Comment by andryyy** [comment]
The image should build fine, but please run "docker-compose pull" before 
you run "docker-compose up -d" to download the pre-built images.

------ Originalnachricht ------
Von: "DennisG" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 24.04.2019 12:22:33
Betreff: [mailcow/mailcow-dockerized] GZIP Eroor while installation 
(#2555)

**Comment by tha80** [comment]
#2556 is fixing that problem. Just needs to be merged :)

**Comment by den1982** [comment]
docker-compose pull worked, thank you!
