### ISSUE TITLE
include imprint link

### ISSUE THREAD

**Issue by BlackWolfDEsign** [mailcow/mailcow-dockerized#2558]
Hi is it possible to specify a link for an imprint on the Mailcow login page? Which file does this concern? Can you also tell me which file is responsible for the SOGo login? Thank you

**Comment by mkuron** [comment]
The logo change is documented at https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/#change-logo. To add links to the login page, log in as admin and scroll down to the "Customize" section.

**Comment by mkuron** [comment]
The logo change is documented at https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/#change-logo. To add links to the login page, log in as admin and scroll down to the "Customize" section.
