### ISSUE TITLE
Destination Format is Invalid

### ISSUE THREAD

**Issue by junelsolis** [mailcow/mailcow-dockerized#2559]
Hello everyone,

I'm trying to add a transport map for specific mailboxes. The problem is that when I try to add 'mailbox@example.org', I received an error 'Destination format is invalid'. Is there something I am missing here?

Additionally, if I create I transport map with just the domain example.org and then later edit it to say 'mailbox@example.org' then the entry is accepted and there is no error.

Further information (where applicable):
 - Ubuntu 18.04
 - Docker version 18.09.5, build e8ff056, Docker Compose version 1.24.0, build 0aa59064

**Comment by andryyy** [comment]
Thanks!

**Comment by junelsolis** [comment]
I see that commit https://github.com/mailcow/mailcow-dockerized/commit/3e3e526568d99d8899692ad7230e2593817bdea2 has fixed the issue in [functions.transports.inc.php](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.transports.inc.php)

In the future, maybe I can put in my own pull requests to fix small issues like this. Thank you very much @andryyy

**Comment by andryyy** [comment]
Sorry, forgot the reference. :)
