### ISSUE TITLE
Maildir_sub issue when migrating

### ISSUE THREAD

**Issue by papaganelli** [mailcow/mailcow-dockerized#2560]
I am trying to migrate my Mailcow to a new server by following: https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_migration/

My Mailcow is up to date.

On the new server, when doing docker-compose pull I keep getting:
```
docker-compose pull
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "dovecot-mailcow": "MAILDIR_SUB=${MAILDIR_SUB:-}"
```

Any ideas?

**Comment by andryyy** [comment]
Why did you remove the issue template?

The docker-compose version is probably too old.

**Comment by papaganelli** [comment]
Sorry for the template, my bad

Indeed, it was the docker-compose version. Thanks
