### ISSUE TITLE
Lets Encrypt Cert Expired and will not renew

### ISSUE THREAD

**Issue by colevan94** [mailcow/mailcow-dockerized#2562]
My cert just expired and will not renew automatically I have tried docker compose up down restart as well as restarting acme-mailcow logs are as follows:

`acme-mailcow_1_b773563d8930 | Thu Apr 25 23:21:40 UTC 2019 - Waiting for Docker API...OK

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:21:40 UTC 2019 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: mail.$$$$$.xyz

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:21:40 UTC 2019 - Waiting for database... 

acme-mailcow_1_b773563d8930 | Uptime: 606  Threads: 29  Questions: 1172  Slow queries: 0  Opens: 40  Flush tables: 1  Open tables: 32  Queries per second avg: 1.933

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:21:40 UTC 2019 - Initializing, please wait... 

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:21:40 UTC 2019 - Detecting IP addresses... OK

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:00 UTC 2019 - Waiting for domain table... OK

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:00 UTC 2019 - No A or AAAA record found for hostname autodiscover.##########.com

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - No A or AAAA record found for hostname autodiscover.$$$$$.xyz

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - No A or AAAA record found for hostname autodiscover.&&&&&&&&&.associates

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - Found A record for mail.$$$$$.xyz: 192.168.2.79

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - Cannot match your IP ###.##.###.## against hostname mail.$$$$$.xyz (192.168.2.79)

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.

acme-mailcow_1_b773563d8930 | Thu Apr 25 23:22:01 UTC 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.`

**Comment by mkuron** [comment]
> Found A record for mail.$$$$$.xyz: 192.168.2.79

Your DNS record points to a private IP address.

**Comment by colevan94** [comment]
How can I fix this? Mailcow has been working fine until the cert expired,,, how did it get the original one?

**Comment by colevan94** [comment]
Where is mailcow pulling that A record because I know my DNS servers are showing the proper public IP for mail.$$$$$.xyz @andryyy Could you help me with this?

**Comment by andryyy** [comment]
I don’t know. Check your DNS and hosts file. That’s not really related to mailcow. We don’t change these settings. :)

**Comment by colevan94** [comment]
Thank you!!! It was hosts file, at least as a work around, I have router addressing static block (including public IP for mailcow) through NAT so I had to change my hosts file temporarily to allow it to get a new cert. I have had the hosts file showing mail.$$$$$.xyz @ 192.168.2.79 to allow my internal machines to access the server without an SSL issue
