### ISSUE TITLE
nginx cert issues after update

### ISSUE THREAD

**Issue by xennialex** [mailcow/mailcow-dockerized#2563]
Hi!

After I updated my version today nginx keeps restarting.
The log files show endless errors like this:

```
nginx: [emerg] cannot load certificate "/etc/ssl/mail/cert.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: configuration file /etc/nginx/nginx.conf test failed
2019/04/26 23:59:09 [emerg] 13#13: cannot load certificate "/etc/ssl/mail/cert.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
```

Any hint how I could fix this problem? Thanks!

**Comment by xennialex** [comment]
I got it to start up again after removing the cert.pem file (which had 0 bytes) from
`/opt/mailcow-dockerized/data/assets/ssl`

Very strange... 🤔

Is there anything else I should do?

**Comment by andryyy** [comment]
Hm, strange indeed. I would need to see the logs of acme-mailcow...

I also added a 0 byte check.

**Comment by xennialex** [comment]
Sadly I can only see the logs from today after I removed the file. 
No logs available from before when I had the problem...

But since it seems to work again I guess we can close this issue 😉
