### ISSUE TITLE
Missed IMAP Configuration in sogo.conf

### ISSUE THREAD

**Issue by enlipos** [mailcow/mailcow-dockerized#2564]
Hello, 

why the configuration line in /data/conf/sogo/sogo.conf

SOGoIMAPServer = "imap://dovecot:143/?tls=YES";

was deleted?
After i did the update, i can login to sogo, but couldn´t access my imap-email accout.
If i add the line an restart the sogo-container it works again.

Is there a new way zu access the imap-accounts
or is it a bug?

Best regards
s.g.

**Comment by andryyy** [comment]
You didn’t provide any information about your setup and local changes. No diff for example. You probably use old images. 

See https://github.com/mailcow/mailcow-dockerized/blob/60fd955defc1155c8d9a58c7926bebb03aa89a9c/data/Dockerfiles/sogo/bootstrap-sogo.sh#L103

**Comment by enlipos** [comment]
Ah, ok. The configuration is done automaticliy by a skript. (didn´t konw that, good to know that).
In master the line i descript was deleted, so i wonder. I could fix i by my self.

https://github.com/mailcow/mailcow-dockerized/commit/57312ad605b1e0b2a996b07cde6280299ae8025c#diff-d23f74fc1089d3d7761d9ebc52dac4ef

best regards
s.g.
