### ISSUE TITLE
Question about netfilter source code: Why must insert snat rule to the first position?

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#2568]
First thanks to @mkuron , @andryyy , and all the mailcow contributors. Your works are awesome!
 
I'm checking the netfilter source code:
at https://github.com/mailcow/mailcow-dockerized/blob/91af3d5c5af4ae29dcd1c3c52d0cb20f0ef89404/data/Dockerfiles/netfilter/server.py#L281

```
      if get_snat4_rule() not in chain.rules:
           ....
          chain.insert_rule(get_snat4_rule())
          table.commit()
       else:
          for position, item in enumerate(chain.rules):
            if item == get_snat4_rule():
              if position != 0:
                chain.delete_rule(get_snat4_rule())
          table.commit()
        table.autocommit = True

```

May I ask why must let the Mailcow SNAT rule to be in the first position at the firewall's chain? 

With Python iptc package, the code `chain.insert_rule(get_snat4_rule())`
will only append the new rule to to the last position or the first position as default? I remember iptc can also set the inserted position, why not do it in this way?

Thank you guys.
danke sehr :)

**Comment by andryyy** [comment]
Thank you! :)

There was a reason I can’t remember (tm). On some systems NAT rules were inserted to the table and our post routing became useless. 

We could add a variable to the container to not check its position. We wouldn’t add it as default config parameter to mailcow. Just so you can set it yourself and be happy.
