### ISSUE TITLE
Tagging to subfolder doesn't work?

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#257]
Hi there!
I've set tagging to send to subfolder but it didn't work. I still get the mails to their own IMAP subfolder.

I've restarted SOGo in the mailcow UI just for ***** and giggles but it didn't help.

Do I need to restart the whole docker-compose for every time I change the tagging setting?

**Comment by andryyy** [comment]
No, but it may indeed take a few seconds (up to 1-2 mins) to reload the map.

The Rspamd logs would be of interest. I think the last 300 lines are fine. Just after you receive a mail which should be tagged.

We will move this map to Redis soon.

**Edit** -> Wait, you don't speak of tagged subjects, do you?

**Comment by Braintelligence** [comment]
Ah ok!
Then one question still remains:

If the subfolder that is tagged doesn't exist it is created in lower case.
If I create the subfolder beforehand and use upper case in it, will the tagging respect the existence of a folder with uppercase letters or will it create another subfolder with lower case only?

**Comment by Braintelligence** [comment]
Oh and also:
Is it possible to somehow incorporate whitespace in the tag? By using underscore perhaps?

**Comment by andryyy** [comment]
I doubt folders with whitespace will work, I actually never tested it. :) 

I changed the behaviour for the next dev => master merge: It will respect the existing folder if it matches 1:1, if not, it will create a folder with the first letter uppercase, others lowercase.

**Comment by Braintelligence** [comment]
Great! Thank you for the added functionality :). You're the best.
