### ISSUE TITLE
Postfwd

### ISSUE THREAD

**Issue by Hexaris** [mailcow/mailcow-dockerized#2572]
**Feature request**

Hi, it would be nice have a postfwd in mailcow. Now I use postfwd in external lxc container and set ip:port in postfix-mailcow. I use it for a couple of years to check outgoing spam (stolen password for mailbox).

Sorry, english is not my native lang.

**Comment by andryyy** [comment]
Hi, we use Rspamd which covers all postfwd seems to do.
