### ISSUE TITLE
FTS transaction commit failed(fts_solr: Indexing failed: 500 Server Error)

### ISSUE THREAD

**Issue by germanosbh** [mailcow/mailcow-dockerized#2573]
I see many errors in the Dovecot log like:

indexer-worker(user@mydomain)<26490><z5GyI9/8y1x1ZwAANoNW6w:vyblLd/8y1x6ZwAANoNW6w>: Error: fts_solr: Indexing failed: 500 Server Error

After reading: ht[tps://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-fts/

I tried reindexing all users with:
docker-compose exec dovecot-mailcow doveadm index -A '*'

but I keep getting many errors like the one below for all users:

doveadm(user@domain): Error: fts_solr: Indexing failed: 500 Server Error
doveadm(user@domain): Error: fts_solr: Indexing failed: 500 Server Error
doveadm(user@domain): Error: Mailbox Junk: Transaction commit failed: FTS transaction commit failed: backend deinit
doveadm(user@domain): Error: fts_solr: Indexing failed: 500 Server Error
doveadm(user@domain): Error: Mailbox INBOX: Transaction commit failed: FTS transaction commit failed: backend deinit

**System information:**
Intel Xeon E3-1270 V6 
32GB RAM
Ubuntu 18.04

Please, do you have any suggestions on how to solve this problem?

Thank you

**Comment by andryyy** [comment]
I’d say Solr died of RAM hunger. Check the solr-mailcow logs.

**Comment by germanosbh** [comment]
HI,
I believe you are right:) 
In Log I see lines like:

solr-mailcow_1       | Caused by: java.lang.OutOfMemoryError: Java heap space

I'm going to add more RAM memory

Thank you !

**Comment by andryyy** [comment]
Or increase the heap size. :) In mailcow.conf

**Comment by germanosbh** [comment]
Thank you ! This worked very well :)
