### ISSUE TITLE
imapsync jobs shown double in web ui

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#2575]
![image](https://user-images.githubusercontent.com/5203309/57177912-7da38280-6e69-11e9-9754-e9fb3ceaa53d.png)
Sometimes it will list twice the sync jobs list.

**Comment by andryyy** [comment]
What is "sometimes"? Logged in as which user?

**Comment by hunter-nl** [comment]
Logged in as "super" admin.
If you click multiple times on refresh button, then at random number of refresh clicks, the above situation happens. I need then to reload complete page to get it back normally.

**Comment by andryyy** [comment]
Ah, thanks, seems to be a JS issue then. I was checking the PHP code. :)

I can only force it when I keep "return" pressed and reload it like 20 times a second.

We could try to disable the button as long as it reloads. Or just disable it for a second.

**Comment by Adorfer** [comment]
I have seen this behaviour in the past as well. 
Some kind of "blocking" of repeated/unneccesary/counterproductive actions would be helpful.
