### ISSUE TITLE
UI: Renaming Mailalias & dropdown menu in "Mailboxes " and "Aliases"

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2578]
Hi,

first the renaming issue.
I had an alias with an uppercase at the beginning.
As an an example: Support@example.com
I wanted to change it to lowercase. But this failed with the error "this alias already exists".
First I had to erase the initial letter, save it and save it again with a small initial letter.

---

For the second one I've added a screenshot to explain.
If you select a domain or an alias in the respective tab, the dropdown menu will be cut off and you will have to scroll.
Looks like a frame issue. 

![Bildschirmfoto 2019-05-05 um 19 23 18](https://user-images.githubusercontent.com/11925757/57197988-f2f87b80-6f6d-11e9-9830-7857571059ae.jpg)

many Greetings

**Comment by andryyy** [comment]
Hi,

I fixed the first issue.

The second issue is a bit more difficult. I have seen this and already have it on my to-do, but no eta.
There is another issue with the object count (the black "1" in the table header). If you have 10 mailboxes, use a filter to only show 3 (or whatever) and reload the page, it will show 3 mailboxes in total.

**Comment by andryyy** [comment]
Both other mentioned issues _should_ be fixed now.

**Comment by vain90** [comment]
WOW! That was fast.
Special thanks to you! I just tested it. Works perfect.
