### ISSUE TITLE
[Question] SOGo task with members or as mail

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#258]
Hi everyone!
Sorry for asking so much about SOGo but you guys are so incredibly helpful! 👍 

Is it possible to create a task with members or send a mail with a task in it, so you can share tasks without giving access rights to your calendar?

**Comment by broedli** [comment]
Again, this question is best asked in SOGo's mailinglist: https://lists.inverse.ca/sogo/info/users

I personally don't know any way to share a single tasks with members of a domain.
