### ISSUE TITLE
mailcow-dockerized on raspberry pi3 b+

### ISSUE THREAD

**Issue by CharlyFive** [mailcow/mailcow-dockerized#2580]
hello i can install it on a raspberry 3 b+ ?

Thx

**Comment by mkuron** [comment]
You could try, but it‘s very tight on memory and you would need to build the Docker images yourself. Some images use binary packages (e.g. https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/sogo/Dockerfile#L35), which you need to switch to manually compiling those packages if they are not available for the ARM packages. Finally, a mail server needs a static, public IP address — so you usually can‘t run it at home.
