### ISSUE TITLE
502 Bad Gateway - Redbird Reverse Proxy

### ISSUE THREAD

**Issue by firstdorsal** [mailcow/mailcow-dockerized#2583]
i'm getting "502 Bad Gateway nginx"
im forwarding mail.firstdorsal.com through the nodejs reverse proxy redbird through to mailcow;

proxy forwards to 127.0.0.1:8080;
mailcow is setup to listen on this port and also to use https:

![eb31199263e60d32e77641f54d7d2998](https://user-images.githubusercontent.com/10563452/57408740-c3a07380-71e6-11e9-8e01-1465934b837a.png)

![6dcc6ce471bfb7ff0a9a665c5a97f83e](https://user-images.githubusercontent.com/10563452/57408554-35c48880-71e6-11e9-8a7a-975f30b3f2c3.png)

it also worked on my old/other server; 

thank you; mailcow is great as soon as it works;

**Comment by andryyy** [comment]
Hi, you should post some logs. Those of your reverse proxy and nginx-mailcow. Please limit the logs to the time the error occurs.

What about the issue template? Could you please post at least the active iptables rule set?

**Comment by firstdorsal** [comment]
0|proxy  | {"name":"redbird","hostname":"hostnamegoeshere","pid":7981,"level":30,"msg":"Proxying mail.firstdorsal.com/ to 127.0.0.1:8080/","time":"2019-05-09T12:51:51.584Z","v":0}

2019/05/09 14:55:34 [error] 17#17: *986 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:89.247.200.168, server: mail.firstdorsal.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.1.13:9002", host: "mail.firstdorsal.com"
::ffff:89.247.200.168 - - [09/May/2019:14:55:34 +0200] "GET / HTTP/1.1" 502 552 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3788.0 Safari/537.36"

-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-N MAILCOW
-A INPUT -j MAILCOW
-A FORWARD -j MAILCOW
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-4f5473808f9e -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-4f5473808f9e -j DOCKER
-A FORWARD -i br-4f5473808f9e ! -o br-4f5473808f9e -j ACCEPT
-A FORWARD -i br-4f5473808f9e -o br-4f5473808f9e -j ACCEPT
-A DOCKER -d 172.22.1.5/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 8443 -j ACCEPT
-A DOCKER -d 172.22.1.5/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.22.1.9/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 587 -j ACCEPT
-A DOCKER -d 172.22.1.9/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 465 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 12345 -j ACCEPT
-A DOCKER -d 172.22.1.9/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 25 -j ACCEPT
-A DOCKER -d 172.22.1.12/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 4190 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 995 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 993 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 143 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-4f5473808f9e -o br-4f5473808f9e -p tcp -m tcp --dport 110 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-4f5473808f9e ! -o br-4f5473808f9e -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-4f5473808f9e -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN




danke!!!

**Comment by firstdorsal** [comment]
same problem with only ip; without proxy or domain;

**Comment by andryyy** [comment]
It cannot connect to the PHP upstream. It is either not running, broken or unreachable for whatever reason.

You can check PHP FPM logs and recheck if you missed a running firewall like ufw or firewalld.

**Comment by firstdorsal** [comment]
just reinstalled...; didnt work; from one second to the other it started working again;
thank you anyway; i love mailcow
