### ISSUE TITLE
Exchange on Android

### ISSUE THREAD

**Issue by Zauberbutter** [mailcow/mailcow-dockerized#2584]
I ran into the same problem as [described here](https://security.stackexchange.com/questions/174136/microsoft-email-servers-require-remote-control-of-android-device-security-featu) but with my own mailcow instance.

I don't feel very comfortable giving GMail administrator permissions. So is there any way to avoid this?

**Comment by mkuron** [comment]
Remote wipe etc. is a standard feature of Exchange ActiveSync (EAS). The server can ask the client to reset itself to factory defaults, e.g. if the device was stolen. I expect the Gmail app asks for these permissions whenever you add an EAS account.

As far as I can tell, SOGo does not currently implement this functionality, so even if you grant the GMail app these permissions, your Mailcow cannot remotely wipe your device.
