### ISSUE TITLE
Watchdog: ratelimit hit the error rate limit

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#2585]
Hi, I getting email about ratelimit container "Watchdog: ratelimit hit the error rate limit", but when I look into logs, there is nothing usefull.

**Comment by andryyy** [comment]
Check rspamd-mailcow, it applied a ratelimit. Or check mailcow UI => Logs => Ratelimit.

**Comment by feldsam** [comment]
I see some ratelimits applied in UI => Logs => Ratelimit. So it reporst applied ratelimits as error?

**Comment by feldsam** [comment]
looks like ratelimits applied even if are not configured on domain/mailbox. So rspamd applied it?

**Comment by andryyy** [comment]
I dont know which were applied. It is possible "from_ip" etc. is applied. You see the "type" in the UI logs, I think. :)

**Comment by feldsam** [comment]
![Snímka obrazovky 2019-05-09 o 10 28 01](https://user-images.githubusercontent.com/951648/57438882-27f22000-7245-11e9-8331-fe8cd33b2aa9.png)

**Comment by andryyy** [comment]
data/conf/rspamd/override.d/ratelimit.conf (change it to 100/1s or something like that).

Anything in the browser debug console? Asking because of the empty sender.

**Comment by feldsam** [comment]
```
root@mail:/var/mailcow-dockerized# cat data/conf/rspamd/override.d/ratelimit.conf
rates {
    # Format: "1 / 1h" or "20 / 1m" etc. - global ratelimits are disabled by default
    to = "45 / 1m";
    to_ip = "360 / 1m";
    to_ip_from = "180 / 1m";
    bounce_to = "100 / 1s";
    bounce_to_ip = "100 / 1s";
}
whitelisted_rcpts = "postmaster,mailer-daemon";
max_rcpt = 5;
custom_keywords = "/etc/rspamd/lua/ratelimit.lua";
info_symbol = "RATELIMITED";    

root@mail:/var/mailcow-dockerized# cat data/conf/rspamd/lua/ratelimit.lua 
local custom_keywords = {}

custom_keywords.mailcow = function(task)
  local rspamd_logger = require "rspamd_logger"
  local dyn_rl_symbol = task:get_symbol("DYN_RL")
  if dyn_rl_symbol then
    local rl_value = dyn_rl_symbol[1].options[1]
    local rl_object = dyn_rl_symbol[1].options[2]
    if rl_value and rl_object then
      rspamd_logger.infox(rspamd_config, "DYN_RL symbol has value %s for object %s, returning %s...", rl_value, rl_object, "rs_dynrl_" .. rl_object)
      return "rs_dynrl_" .. rl_object, rl_value
    end
  end
end

return custom_keywords
```

**Comment by andryyy** [comment]
The browser debug console?

**Comment by feldsam** [comment]
![Snímka obrazovky 2019-05-09 o 10 43 00](https://user-images.githubusercontent.com/951648/57439887-3e00e000-7247-11e9-8126-8fb16d56694b.png)

looks like ratelimited by rspamd. I think it is not technical problem. It is soft rejected and message is received later. But why to send watchdog error mails about it?

**Comment by andryyy** [comment]
The browser debug console? I wonder why the sender is empty in the RL log list.

**Comment by feldsam** [comment]
It is empty in json reply.

![Snímka obrazovky 2019-05-09 o 11 24 31](https://user-images.githubusercontent.com/951648/57442825-114fc700-724d-11e9-834d-1d9bdd193b51.png)

**Comment by andryyy** [comment]
Ah, MAILER-DAEMON. :-) Thanks. That's ok.

I will push an updated ratelimit.conf in a sec. It will set the to to_ip etc. rate buckets to 100 / 1s. I don't think we can remove them completely. I need to test that.

**Comment by feldsam** [comment]
is there need to increase it? I am just confused about watchdog mails...

**Comment by andryyy** [comment]
Yes, we should more or less disable the to to_ip etc. rates. 

Watchdog sends these mails to inform you, that a ratelimit was applied by Rspamd. It was implemented to let you know as fast as possible, that a user is spamming.

In your case, it was not a "user" rate limit.

Yes, ratelimited mails are just soft-rejected with 4xx. When a sender retries after a while (depending on the limit), it will be delivered.
