### ISSUE TITLE
Statistics for TLS + none TLS SMTP connections 

### ISSUE THREAD

**Issue by RogerSik** [mailcow/mailcow-dockerized#2586]
**Is your feature request related to a problem? Please describe.**
I wanted to see how many non TLS SMTP connections are in use. 

**Describe the solution you'd like**
Like rspamd where you get a tart chart with blocked, probaly spam and allowed mails. The values could be: 
* TLS SMTP Connection
* Unecrypted SMTP Connection

**Additional context**
Example: Office 365 Statisctics Center
![825aa74c-413d-4141-8e3c-dfe68ae78eed](https://user-images.githubusercontent.com/165814/57460445-66073800-7275-11e9-8c72-f2593c331a50.png)

**Comment by mkuron** [comment]
That's an interesting idea. It would definitely help people considering turning on TLS enforcement. It could also show statistics on whether certificates could be validated, whether DANE was used, and give a list of mailservers that didn't use TLS.

We don't have that information in rspamd and I don't think it can even do custom statistics. However, one could create a cron job that pulls this information from the Postfix logs stored in redis. Or write a little Lua plugin for rspamd. Pull requests are welcome.

**Comment by andryyy** [comment]
Hm, would indeed be interesting.

As of today, you can use a custom logging driver like syslog and run pflogsum on it. Or any other (self-written) script.

**Comment by Braintelligence** [comment]
I'd be happy to have this feature in the Mailcow UI :)
