### ISSUE TITLE
Update script executes docker-compose up as root

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#2587]
Hello,

I'm trying to update my mailcow installation using the script and it seems now that the script requires root.

Why not, but then the scripts starts docker-compose up -d as root, which my installation is not set up to, and it basically wrecked my configuration (I lost my dkim key and crypts keys have been overriden).

I had to roll back to a previous backup.

I don't think the script should start docker-compose as root. Is this really needed?

**Comment by mkuron** [comment]
> Is this really needed?

Unless you manually added your user to the docker group, you need to run as root.

> which my installation is not set up to, and it basically wrecked my configuration

Please explain what happened so it can be fixed.

**Comment by etique57** [comment]
Yes, my user is in the docker group.

I don't exactly know what happened, I just now the result:
- DKIM key was gone
- crypt keys had been overwritten
- permissions were broken, and my attempt at fixing them probably didn't help.

My user is properly set up, the update script shouldn't impose to run it as a root as I don't know what will happen with the permissions.

The check should be:
- either root user
- or user belongs to docker group

What do you think?

**Comment by andryyy** [comment]
There is no way DKIM keys would be deleted or crypt keys are overwritten (!). That's just not possible (check the script).

You probably removed the old volumes and created new ones. Or you had a compose project name set and the symlink from mailcow.conf to .env was broken.
But it is technically not possible, that the key is overwritten, if it exists.

The script is meant to be run as root, I don't plan to change that. Some people clone the code as user X (root for example) and then try to run update.sh as user Y (non-root). Some modifications will fail.

It does not matter if you start Docker containers as root or as a user in the Docker group. After all, your unprivileged user triggers the Docker daemon, which then acts as root. We had issues describing that behavior.

We drop privileges inside the containers where possible and necessary after starting them. This does not change at all, when you start the containers as non-root user. Services like Postfix or Dovecot are never run as root...

**Comment by andryyy** [comment]
Oh, re-opening as you probably want to wait from someone to help with the update. Sorry.

**Comment by etique57** [comment]
Thanks @andryyy 

I'll try again, but I for sure did not invent the result above ;) Again I don't know whether it's related to the update script or not, and as I had a problem before I'm using local-persist volumes for all the important volumes (as during an update I once lost all volumes...)

After my first update trial, I really struggled to be able to spin up the docker-compose properly. I had permissions problems (tc.log) in the SQL volume, I couldn't connect to the Transmission port anymore, and as I stated, DKIM & crypt keys were gone or overwritten. This last point forced me to revert to my backup.

But what it also means is that mailcow-dockerized is intended to be run as root, not as another user. That should be written somewhere in the documentation.

**Comment by andryyy** [comment]
It does not overwrite they key EVER. Check the code. If it exists, it is not overwritten. It probably created new volumes. 

I won’t debug this, as it is not a mailcow issue.
