### ISSUE TITLE
Security Report: Docker-Images of Alpine-Linux using root-account without password [Source: Heise Security]

### ISSUE THREAD

**Issue by pbaeumel** [mailcow/mailcow-dockerized#2589]
Dear @andryyy,

I just stumbled upon an article of Heise Security regarding a possible Security Issue with Docker-Images of Alpine Linux.

See: https://www.heise.de/security/meldung/Kritische-Luecke-Docker-Images-von-Alpine-Linux-mit-Root-Zugang-ohne-Passwort-4418636.html

Didn`t know if this might affect also the Alpine-Docker-Image used within Mailcow.

But it is suggested to update the image to (for example) 3.9.2 [found in the news section that Alpine Version 3.9 is in use within Mailcow].

Best regards,
MacGyver

**Comment by mkuron** [comment]
As far as I can tell, it only matters if you use PAM authentication inside the container. Mailcow doesn‘t do that, so there is no attack vector. Of course, we‘ll still upgrade, but there is no urgent need to do so.
