### ISSUE TITLE
The helper scripts have #!/bin/bash as shebang

### ISSUE THREAD

**Issue by wucke13** [mailcow/mailcow-dockerized#2590]
As stated in the title there still is the hardcoded `#!/bin/bash` in the helper scripts. Please replace it by a valid shebang, like `#!/usr/bin/env bash`.

**Comment by wucke13** [comment]
@andryyy 
```
head -n1 helper-scripts/check_translations.rb
#!/usr/bin/ruby
```

**Comment by andryyy** [comment]
Feel free to create a PR. :)

**Comment by wucke13** [comment]
@andryyy Please see #2595

**Comment by hachre** [comment]
#2595 merged, thanks!
