### ISSUE TITLE
[Feature] Add ARC signing for inbound mails

### ISSUE THREAD

**Issue by Kraeutergarten** [mailcow/mailcow-dockerized#2598]
Is there a chance to add ARC signing for inbound Emails?

You only have to add

```
sign_inbound = true;
use_domain_sign_inbound = "recipient";
```

to data/conf/rspamd/local.d/arc.conf

I already tried it and it works ;)

Thanks.

**Comment by mkuron** [comment]
What‘s the purpose of this? I couldn’t find these options in the rspamd documentation and it‘s not obvious to me why one would want to sign inbound messages.

**Comment by Kraeutergarten** [comment]
It's useful for forwarded mails. Google does also inbound signing and checks for it.

See: https://github.com/rspamd/rspamd/issues/2245

**Comment by andryyy** [comment]
What exactly do we not do now? Or what do we different with ARC right now?
We check for ARC and rate it. We sign messages when they leave us. How do we profit from signing them inbound? It is not obvious to me either. :) Let us know.

**Comment by Kraeutergarten** [comment]
For example:
I receive a message from outlook.com and i redirect it to google. In this situation no ARC is added, because the message sender is outlook.com and i have no keys.
Inbound signing will prevent this, because it selects signing by the recipient.

**Comment by andryyy** [comment]
But we sign forwarded mail.

**Comment by Kraeutergarten** [comment]
Yeah but not the mails from outlook.com or google or xyz. RSpamd selects by the **envelope** domain -- for outlook.com i don't have any key to sign.

Inbound signing selects by the recipient and for the recipient i do have keys.

Try it.....

**Comment by mkuron** [comment]
> RSpamd selects by the envelope domain

But the envelope domain is not preserved during forwarding. It is replaced with the forwarder's domain.

**Comment by Kraeutergarten** [comment]
Ich switch mal auf Deutsch.

Ich hatte folgendes Problem.

Ich sende eine Email von meinem Outlook.com Account an einen Alias von der Mailcow Installation. Dieser Alias leitet die Email an einen googlemail Account weiter.

Was passiert:
Mailcow überprüft spf, dkim alles in Ordnung. -> ARC wird beim weiterleiten auf googlemail nicht gesetzt. Habe ich mehrfach geprüft.
Anschließend überprüft Google spf, dkim. SPF schlägt klarerweise fehl. ARC Header gibt's leider keinen. 

Nun habe ich nach einer Lösung gesucht, wie auch ARC bei diesem Szenario gesetzt wird.
Da bin ich auf das Inbound Signing gestoßen und damit wird in diesem Fall auch ein ARC Header gesetzt.

Beim Outbound signing, wird ja nur überprüft ob der User authentifiziert ist, ob da SPF, DKIM stimmen wird nicht verifiziert. 
ARC ist ja eigentlich dafür da das die SPF und DKIM Resultate dem nächsten Mailserver übergeben werden. 

Der ARC Header darf ja explizit mehrfach gesetzt werden. Das "i" wird dann hochgezählt.

**Comment by ntimo** [comment]
This has been added by: https://github.com/mailcow/mailcow-dockerized/commit/e43951331c6b6078e3e5847602e98fbd2bb9ed25

**Comment by georgyo** [comment]
@ntimo This may have been added in e439513, but those options don't actually exist in rspamd. -- https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/arc.lua

For people who end up here looking how to enable this in rspamd, as this time of writing it only supports signing of forwarded messages and does not have the ability to sign incoming messages.

**Comment by strarsis** [comment]
@georgyo: I set up DKIM + SPF for the domains in mailcow and DNS zone. Would this be sufficient to make ARC work? Or is additional configuration required? Is there an ARC-section in the current mailcow documentation?

**Comment by iodize6399** [comment]
@strarsis Not sufficient.

The key word here is redirect that gets confused with forward. Manual "forward" in a client such as Thunderbird/Outlook (classic) creates a new message from you. This distinction is crucial and often misunderstood.

ARC is different than SPF DKIM. It preserve the chain of authentication of a message bound to be redirected (from sieve filtering). By not having this, message being redirected will inadvertently contribute to spoofing. Our mail server when trying to redirect message that came from Gmail to a Outlook, will presents an email claiming to be from @gmail.com without having the correct DKIM and SPF alignment and that message lands either in Junk or dropped by Microsoft altogether. From Outlook's perspective, this looks exactly like yourdomain.com is trying to spoof gmail.com, even though it's just following your redirect rule. This also hurts the IP reputation of your server.
