### ISSUE TITLE
SSHA password hashes from LDAP

### ISSUE THREAD

**Issue by lukas085** [mailcow/mailcow-dockerized#2600]
Hi,
I have LDAP server with logins and passwords that are encrypted in SSHA. I would like to make a script which generate new accounts to mailcow database with passwords from LDAP server.

**My test login and pass:**
login: test@mail.com
password: 123456
hashed password: {SSHA}UxKwkCjwgaGpyVAis2QJZI7kTKj0+rbTpdPLlQ==

**Firstly I inserted new value into mailbox table:** 
`INSERT INTO `mailbox` VALUES ('test@test.com','{SSHA}UxKwkCjwgaGpyVAis2QJZI7kTKj0+rbTpdPLlQ==','test','/var/vmail/',104857600,'test','mail.com','{\"force_pw_update\": \"0\", \"tls_enforce_in\": \"0\", \"tls_enforce_out\": \"0\", \"sogo_access\": \"1\", \"mailbox_format\": \"maildir:\", \"quarantine_notification\": \"never\"}','',-1,'2019-04-10 08:29:30',NULL,1);`

**Now I noticed:**
MailcowUI: can't login (error)
SOGO: I **can** login and receive mails
SOGO: I can't send mails

What should I do next to make it work?
Thanks.

**Comment by mkuron** [comment]
Mailcow UI: hash method needs to be implemented at https://github.com/mailcow/mailcow-dockerized/blob/c612f7ee4c4e0c7c3d1e030ee853cc1c2287ccde/data/web/inc/functions.inc.php#L355-L362, please submit a pull request.

Sending: unclear. Postfix delegates authentication to Postfix, so both should work or none. Please check the Postfix and Dovecot logs while sending a message.

**Comment by lukas085** [comment]
Hi, I tried to submit a pool request, but I don't do that before and don't know what to select after clicking pull request.

I tried to add to functions.inc.php new elseif like that:

> elseif (preg_match('/^{SSHA}/i', $hash)) {
>     $hash = preg_replace('/^{SSHA}/i', '', $hash);
>     // Decode hash
>     $dhash = base64_decode($hash);
>     // Get first 20 bytes of binary which equals a SHA hash
>     $ohash = substr($dhash, 0, 20);
>     // Remove SHA hash from decoded hash to get original salt string
>     $osalt = str_replace($ohash, '', $dhash);
>     // Check single salted SHA hash against extracted hash
>     if (hash_equals(hash('sha', $password . $osalt, true), $ohash)) {
>       return true;
>     }
>   }

But it don't work. 
Could somebody look at this?

About sending: I noticed that option "Allow to send as" at mailsetup is selected as "nothing selected" so  mails are not sent. That's why I need to have access to mailcow-ui, to check if there is that option selected as sender who is configured.

**Comment by andryyy** [comment]
You are inserting stuff into the database manually, This will break when we change the table layout or add new mailbox_attributes etc.

You do also need a 1:1 alias table entry (same source as dest) for a mailbox to work. That's probably why it says "none selected". :)

**Comment by lukas085** [comment]
After inserting entry to alias database, sending works.
Still working on mailcow-ui SSHA support.

**Comment by lukas085** [comment]
Mailcow-UI SSHA (SHA-1) works.
There is a line of code I added to data/web/inc/functions.inc.php:

> elseif (preg_match('/^{SSHA}/i', $hash)) {
>     $hash = preg_replace('/^{SSHA}/i', '', $hash);
>     // Decode hash
>     $dhash = base64_decode($hash);
>     //echo $hash;
>     // Get first 20 bytes of binary which equals a SHA hash
>     $ohash = substr($dhash, 0, 20);
>     // Remove SHA hash from decoded hash to get original salt string
>     $osalt = str_replace($ohash, '', $dhash);
>     // Check single salted SHA hash against extracted hash
>     if (hash_equals(hash('sha1', $password . $osalt, true), $ohash)) {
>       return true;
>     }
>   }

Could somebody check and pull this?
