### ISSUE TITLE
Shared mail addresses like Kolab Server

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2602]
**Is your feature request related to a problem? Please describe.**
In Kolab Server, the user can define "shared" folders that are related to an email address (e.g. marketing@example.com) which are then put in a shared IMAP namespace (e.g. Shared Folders/marketing) and then define ACLs for the users that can access said folders (e.g. pete@example.com and joan@example.com can access marketing@ and send emails as marketing@)

In Kolab this is done at the IMAP level (for the namespace/folder) plus a virtual alias map in Postfix.  Basically the alias translates the folder (`marketing@`) to `shared+marketing@example.com` and then the MTA takes care of placing the mail in the correct folder.

As far as I can read from the documentation and the tests I've done in a VM it is not clear if mailcow can actually do this. From what I've seen, shared folders in SoGO belong to a user that shares them towards another, while in this case they don't really "belong" to a single user.

**Describe the solution you'd like**
Being able to define shared email addresses as per above. This is my only "blocker" for moving away from Kolab.

**Comment by andryyy** [comment]
Just create a mailbox and hook it into SOGo or share the inbox. I know that’s what you found out already, it is just that I don’t see the advantage of your desired solution. It is pretty much the same as sharing the folder. :)

I won’t implement this, but good PRs are welcome. That’s something very difficult to implement without some dirty hacks.

**Comment by lbeltrame** [comment]
I thought I can do that like this (I'm totally OK without you not doing it if it's such a niche case). I'm writing it down here if people are interested:

1. Create a public namespace in Dovecot
2. Create the maildirs there (e.g. "marketing")
3. Grant ACLs to only those who need to access them
4. Write a virtual alias map which will translate the address to whatever needed

I'll spin up a VM later and test this approach.

**Comment by andryyy** [comment]
Sounds good. :) I'm just unsure about the last step.

**Comment by lbeltrame** [comment]
"There was an attempt. ;)" My tests showed that you were, in fact, correct, and it's too much trouble for what is worth. A regular mailbox + proper delegation and sharing does the trick.
