### ISSUE TITLE
SOGo Mail forwarding error

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#2603]
I first had a mail adres as alias forwarding a gmail adres and all was good.
Then I changed the alias to a mailbox and set SOGo to do the forwarding instead.

Now when for example in this case, ebay sends a mail it gets rejected with,

`status=bounced (host gmail-smtp-in.l.google.com[74.125.143.27] said: 550-5.7.1 Unauthenticated email from ebay.nl is not accepted due to domain's 550-5.7.1 DMARC policy. Please contact the administrator of ebay.nl domain if 550-5.7.1 this was a legitimate mail. Please visit 550-5.7.1  https://support.google.com/mail/answer/2451690 to learn about the 550 5.7.1 DMARC initiative. t57si12321779edb.108 - gsmtp (in reply to end of DATA command))
May 14 16:25:23 mail postfix/bounce[9948]: D2A3D148088A: sender non-delivery notification: EE3831480889`

It seems there is a difference between the two, SOGo seems to forward in name of eBay.
While the alias just passes the message along.
Is this correct and also the correct behaviour?

**Comment by andryyy** [comment]
You can try to play with sieve_redirect_envelope_from

Example data would have been nice. Like an attached mail, what it looks like, when it is received.

**Comment by andryyy** [comment]
Please update and try again. I changed some values and could verify Google now checks against the correct domain.
