### ISSUE TITLE
Disable ipv6 without risking open relay

### ISSUE THREAD

**Issue by orangelynx** [mailcow/mailcow-dockerized#2605]
Hi,

so after reading up on the insufficiencies of docker when it comes to ipv6 and mailcow becoming an open relay if ipv6 is not handled properly, I am left wondering what ipv6 is needed for when running a mailcow server (since disabling is not recommended) and how to disable it (to use docker swarm) without risking an open relay. I'm hoping that maybe @mkuron might be able to provide some steps of action.

**Comment by mkuron** [comment]
I think if you don‘t have an IPv6  address on the host, you can disable the ipv6nat container. You might also want to disable the Docker userland proxy as that is usually the culprit responsible for the open relay.

Be sure to check your server for open relaying after you have set it up though.

**Comment by andryyy** [comment]
Swarm is not supported - in mailcow. You probably want to use it otherwhere on the same host.

**Comment by orangelynx** [comment]
@mkuron I have an assigned ipv6, which i do not use, there's also no AAAA record. Do you think it would suffice to install additional ip tables rules to suppress ipv6 traffic? I'm also still not sure if I stand to loose any important functionality by disabling ipv6, since it is "not recommended" to disable it.

@andryyy I know, my swarm is running on a single node only. I merely want to use swarm as I'm reading in between the lines that docker-compose is likely not getting much developer attention in the future. I've made relevant changes to the docker-file myself.

I also changed most of the bind mounts in the docker compose to named volumes, which I populate using a script, as the docker docs do not recommend bind mounts for this usecase.

**Comment by mkuron** [comment]
> I have an assigned ipv6, which i do not use

Just remove it to be safe.
