### ISSUE TITLE
Docker socket security issue

### ISSUE THREAD

**Issue by orangelynx** [mailcow/mailcow-dockerized#2606]
I was just wondering why mailcow needs access to the docker socket, as this is generally considered a big security risk, as a compromised container would give root access to the docker host.

looking at the docker compose file, it seems that only the docker-api container needs that access, however that container in turn is not linked to any other services via shared files. what is the purpose of the docker-api container and is it maybe possible to remove the dependency on the docker socket?

**Comment by mkuron** [comment]
It does things like restart certain other containers when necessary (e.g. new domain added), report the amount of used space in a mailbox, manage the postfix queue via the web UI, and a few other things that you can see in https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dockerapi/server.py.

I know it‘s not a particularly elegant solution, but the  only way to do these things is via the command line, so access to the socket is needed. The amount of things that https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dockerapi/server.py can do is very limited, so the potential attack surface is small.

**Comment by andryyy** [comment]
How is it not linked to any other container? It is in the mailcow network and available for all containers.

No, we cannot just remove it.

No, we don't pass the socket to any container, that is reachable on the internet. We don't even expose the socket to other containers, but - kind of - proxy it through another API (dockerapi-mailcow), to limit actions, as @mkuron already explained.

**Comment by orangelynx** [comment]
thanks for the clarification. I will have a look at the script as soon as I have mailcow itself set up.

@andryyy 
I know that the docker-api is reachable over the internal mailcow network, I was just saying it's not linked to other containers via shared files.

The current solution seems ok, but perhaps, if you have time, you may want to consider:
1) providing a branch where no docker socket access is given, at the cost of loosing the features provided by docker-api (and stating how to do docker-api's job manually)
2) remove network connectivity between docker-api and other networked containers, which is not needed for operation to further decrease the attack surface.
