### ISSUE TITLE
[Feature] Support hostnames for Fail2ban whitelist.

### ISSUE THREAD

**Issue by Kraeutergarten** [mailcow/mailcow-dockerized#2609]
Since i have a dynamic ip address i can not whitelist it. 
On my hosts where i use fail2ban i can add my dyndnsname to avoid blocking me out.
Is there a chance to get this added?

**Comment by mkuron** [comment]
It's not as easy as it sounds because the host name would need to be periodically re-resolved. If the IP changes, the old one needs to be removed from the whitelist and the new one needs to be added.

Pull requests for this feature are welcome. Since you are the first person to request it, I don't expect it would get implemented unless you do it yourself.

**Comment by Kraeutergarten** [comment]
Would it be OK if there is an extra "Domain Whitelist" and resolving is done ondemand in the python script with a localcache 1 Minute or more?

**Comment by andryyy** [comment]
I think it's easier to just append the IP to the Redis hash manually / 
with a script. You can even edit it via API, but there is no way to read 
Fail2ban data via API right now. :/

Edit: Now there is.

**Comment by Kraeutergarten** [comment]
What do you think about https://github.com/Kraeutergarten/mailcow-dockerized/commit/0f9a6e76f7e2b74dab1df0324e7bf0c34d740c4c

**Comment by mkuron** [comment]
You need to periodically re-resolve the host name anf remove the old IP if the DNS record changes. Please use the DNS TTL as the time interval.

**Comment by Kraeutergarten** [comment]
My version resolves the hostname on every ban action. 
So I guess that's bad?

I can add a memory cache to the script.

**Comment by mkuron** [comment]
Ah, I didn't see that. I forgot that it traverses the entire whitelist at every ban, so I guess your solution is sufficient. The DNS resolver does caching, so you don't need to.

**Comment by Kraeutergarten** [comment]
I do some renaming and reordering. Hope you like it.
If you have some advice please let me know.
