### ISSUE TITLE
Email sync cron not working

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#261]
Hi, the cronjob for the email sync dose not seem to be working.

This is only thing i can see about it in the log's
<pre>
dovecot-mailcow_1    | ==> /var/log/syslog <==
dovecot-mailcow_1    | May  9 18:07:01 mx-de cron[39]: (*system*) NUMBER OF HARD LINKS > 1 (/etc/crontab)
dovecot-mailcow_1    | May  9 18:07:01 mx-de cron[39]: (*system*imapsync) NUMBER OF HARD LINKS > 1 (/etc/cron.d/imapsync)
dovecot-mailcow_1    | May  9 18:07:01 mx-de cron[39]: (*system*dovecot-sync) NUMBER OF HARD LINKS > 1 (/etc/cron.d/dovecot-sync)
</pre>

I know imapsync work as i manually run it doing docker-compose exec dovecot-mailcow /usr/local/bin/imapsync_cron.pl

**Comment by andryyy** [comment]
I will push a new image in a few minutes to fix that. It is a problem with overlay fs and Cron.

**Comment by K2rool** [comment]
Thanks for getting back so quickly no need to rush to fix , it's only one user on my server that uses it, i got a temp fix anyway calling docker-compose exec dovecot-mailcow /usr/local/bin/imapsync_cron.pl via cron on the host node.
