### ISSUE TITLE
Running Web Server docker Container - on same server and domain with Mailcow docker container

### ISSUE THREAD

**Issue by elugadi** [mailcow/mailcow-dockerized#2612]
**Aknowlegment 
First of all thank your for creating such an friendly and easy to install product with MailCow.  The docker concept of sepation is also excellent for this application. 

**Describe the bug *  - Running Web Server- Wordpress Docker in same server as Mailcow

Web server  installation -Nginx - Wordpress - Mariadb (docker sepate from mailcow) - Fails to start since it show port 80 is used by Mailcow in Ubuntu 18. 04

Please describe:
-  Correct configuration for correctly creating this type of installation.
-  Problem previously described in bugs but no to explanation detailed.  

Further information (where applicable):
VPS:  4 Cores / 8 gig Ram / Xeon 2640
Os: Ubuntu 18.04

Mailcow working perfectly otherwise.

Thanks for your help,
Javier.

**Comment by MAGICCC** [comment]
Did you check https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/?

**Comment by elugadi** [comment]
Thanks Magicc I will try this and see it can make it work.

**Comment by amorfo77** [comment]
take a look here, i'm running mailcow and wordpress behind a reverse proxy.
[mailcow + wordpress](https://gist.github.com/amorfo77/e9d2a08cf76bf2cbaecce89c765f4763)
