### ISSUE TITLE
Logs -> Autodiscover hangs

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#2615]
Hi,

  in the last few days the Autodiscover log view doesn't works, just hangs forever, I tried to restart the docker services and the complete machine as well, but still hangs, all other log view works.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/16578737/57958161-1ec91900-78ff-11e9-8f26-88b96627ac23.png">

  Kind Regards,
Zoltan

**Comment by andryyy** [comment]
Hi, can you show the browsers debug console output when it hangs?

**Comment by beckzg** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16578737/57966312-64fa9880-7950-11e9-9c05-550ff756f751.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16578737/57966320-7a6fc280-7950-11e9-988d-f222c96efdae.png">

**Comment by andryyy** [comment]
Ah, UA is probably empty. Can you post the output of 
https://your_hostname/api/v1/get/logs/autodiscover ?

------ Originalnachricht ------
Von: "beckzg" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Comment" 
<comment@noreply.github.com>
Gesendet: 18.05.2019 09:37:05
Betreff: Re: [mailcow/mailcow-dockerized] Logs -> Autodiscover hangs 
(#2615)

**Comment by beckzg** [comment]
[
    {
        "time": 1557952011,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko\/20100101 Thunderbird\/60.6.1 Lightning\/6.2.6.1",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557910157,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "xxx@xxx",
        "service": "activesync"
    },
    {
        "time": 1557910157,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557910156,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "xxx@xxx",
        "service": "activesync"
    },
    {
        "time": 1557910155,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "xxx@xxx",
        "service": "activesync"
    },
    {
        "time": 1557910151,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557910151,
        "ua": "Microsoft Office\/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4738; Pro)",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557910148,
        "ua": "Outlook\/16.0 (16.0.4822.1000; MSI; x64)",
        "user": "xxx@xxx",
        "service": "activesync"
    },
    {
        "time": 1557909582,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    null,
    null,
    null,
    null,
    null,
    null,
    {
        "time": 1557909451,
        "ua": null,
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557909449,
        "ua": null,
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557909449,
        "ua": null,
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557909449,
        "ua": null,
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557611959,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557413672,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557410732,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557393929,
        "ua": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.109 Safari\/537.36",
        "user": "none",
        "service": "Error: must be authenticated"
    },
    {
        "time": 1557393873,
        "ua": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:60.0) Gecko\/20100101 Thunderbird\/60.6.1 Lightning\/6.2.6.1",
        "user": "xxx@xxx",
        "service": "imap"
    },
    {
        "time": 1557393873,
        "ua": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:60.0) Gecko\/20100101 Thunderbird\/60.6.1 Lightning\/6.2.6.1",
        "user": "none",
        "service": "Error: must be authenticated"
    }
]

**Comment by beckzg** [comment]
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/16578737/57970225-216b5300-797f-11e9-84b2-0a40efc96d63.png">

**Comment by andryyy** [comment]
Should be fixed.
