### ISSUE TITLE
No service on 465 available?

### ISSUE THREAD

**Issue by DasNerdwork** [mailcow/mailcow-dockerized#2616]
Hey there,

I swapped from an old server to a new one, couldn't copy the whole server over to the other one, so I had to manually reconfigure and reinstall my necessary services. I correctly set-up my website, sinusbot aswell as mailcow with a reverse proxy on mail.dasnerdwork.net. Everything works fine through SOGo. I can send mails, receive mails and redirect them, just like before.

Wordpresses SMTP services on the other hand won't work like before. Post SMTP says " Port 465 is open, but not to mail.dasnerdwork.net." and shows me this:

![post smtp](https://user-images.githubusercontent.com/49847819/57962496-9440e380-7917-11e9-94c1-d13cfd2e5de5.png)

Any idea why? It's probably just a tiny issue, but I can't figure out where and what lead to this.

[002-mailcow.txt](https://github.com/mailcow/mailcow-dockerized/files/3193481/002-mailcow.txt)

[mailcow.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/3193483/mailcow.conf.txt)

**Comment by foutrelis** [comment]
`openssl s_client -connect mail.dasnerdwork.net:465` shows that an invalid certificate is sent. Perhaps that's causing the issue you're seeing.

**Comment by Braintelligence** [comment]
No news is good news.
