### ISSUE TITLE
VPN Tunnel source IP - open relay struggle

### ISSUE THREAD

**Issue by Svarto** [mailcow/mailcow-dockerized#2618]
**Describe the bug, try to make it reproducible**
I have DigitalOcean (DO) VPS as a VPN Server that tunnels my mailcow traffic from my home network, providing my with a static IP and avoid ISP blocks on the necessary ports.

I can send email, but I cannot receive, and it is a NAT problem. If I NAT the incoming connections to the VPN Server IP, I can receive email but I essentially create an open relay. If I remove this NAT from eth0 -> tun0 in my DigitalOcean VPS - then I can still send email but I cannot receive anything. I can browse to the Mailcow UI though.

Is there anything I can do here, for example:
- Can I keep the NAT and somehow stop my Mailcow to run as an open relay?
- Would it work to SSH tunnel each port to my server, could this circumvent my NAT troubles?
- Can I use some sort of incoming relay or other way to get my email to arrive in my Mailcow server?

And I know it is not your problem, but I ask anyway just in case someone has solved this, what am I missing with my setup to allow source IP to be forwarded to my Mailcow VM? I thought this would be done when I exclude the incoming NAT rule, but somehow no connection to my Mailcow VM is established without it.

Information:

From the Mailcow server I can ping to the internet and DO VPN server IP. 
From the DO VPS I can ping to the Mailcow server IP.
> Routing works back and forth, but not when external IPs try to establish connections (AND I do not have the NAT eth0 > tun0 masquerade rule on DO VPS activated).

DO external IP: 1.1.1.1 (you for illustration of the networking)
DO VPN Server IP: 172.19.0.1
VPN Gateway IP: 192.168.255.1
(VPN client) pfSense subnet gateway: 172.16.30.3
Mailcow IP: 172.16.30.99

DigitalOcean IPTABLES RULES:
```
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 25 -j DNAT --to-destination 172.16.30.99:25
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 465 -j DNAT --to-destination 172.16.30.99:465
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 587 -j DNAT --to-destination 172.16.30.99:587
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 143 -j DNAT --to-destination 172.16.30.99:143
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 993 -j DNAT --to-destination 172.16.30.99:993
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 110 -j DNAT --to-destination 172.16.30.99:110
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 995 -j DNAT --to-destination 172.16.30.99:995
sudo iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 4190 -j DNAT --to-destination 172.16.30.99:4190
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 25 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 465 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 587 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 143 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 993 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 110 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 995 -j ACCEPT
sudo iptables -I FORWARD 1 -p tcp -d 172.16.30.99 --dport 4190 -j ACCEPT
```

Please let me know if any additional configurations can help? I don't want to overwhelm you with all the details if they won't help... Thanks so much for your help, I am completely lost here.

**Comment by mkuron** [comment]
That‘s a very unusual setup and not at all a Mailcow question. You would need to do packet captures at all stages and see where the source IP gets lost. It could even be happening on the pfSense. What do you mean when you say "VPN Gateway", i.e. why does that differ from "DO VPN Server"?
