### ISSUE TITLE
issue with ipv6 and ssl

### ISSUE THREAD

**Issue by daemon-byte** [mailcow/mailcow-dockerized#2619]
Hi,

I have read the other issues and unfortunately they haven't helped me. Everything has been running find for many months so I assume either a recent OS or mailcow update has broken it but I can't find anywhere else to look. I am using hetzner cloud (which is most likely my issue's root) and centos which means I do not have this file /etc/network/interfaces.d/50-cloud-init.cfg or even that folder. I have a couple of screen shots, one from booting up and one from the acme logs (shorted to remove all the domains). 

Oddly while this works from my debain hetzner cloud it does not from my mailcow one running centos. 

ping6 ipv6.google.com
connect: Network is unreachable

![image](https://user-images.githubusercontent.com/517787/57970333-5e841500-7980-11e9-9705-9790dd566717.png)

![image](https://user-images.githubusercontent.com/517787/57970339-78bdf300-7980-11e9-9c85-7d78a7e665f1.png)

**Comment by andryyy** [comment]
Hi,

I don't want to register with Hetzner, so if anybody (you?) is willing 
to grant me access, I could have a look. :)
Mail: info@servercow.de

------ Originalnachricht ------
Von: "daemon-byte" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 18.05.2019 15:23:42
Betreff: [mailcow/mailcow-dockerized] issue with ipv6 and ssl (#2619)

**Comment by daemon-byte** [comment]
I've since done some more digging and I'm 99% sure this is a pure hetzner issue so I'm going to see what their support says. If it's anything related to them and mailcow I will post it here otherwise I will remove this

**Comment by andryyy** [comment]
Have you tried stopping mailcow, stopping Docker, running `sysctl net.ipv6.conf.eth0.accept_ra=2` and restarting Docker/mailcow?

**Comment by daemon-byte** [comment]
yes. It seems, from what I can tell, it never assigns itself an ipv6 address. Where it's static address should be in ifconfig eth0 it's just missing. I've contacted there support but if I choose to move mailcow to a new debian instance how complicated will that be?

**Comment by foutrelis** [comment]
I recently deployed mailcow on a new centos7 hetzner cloud server. It works fine for me so perhaps your network configuration got messed up for some reason.

Here's mine:

`/etc/sysconfig/network-scripts/ifcfg-eth0` (only HWADDR changes between servers, find it with `ip link list dev eth0`)
```
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=dhcp
DEVICE=eth0
HWADDR=96:00:00:XX:XX:XX
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
```

`/etc/sysconfig/network-scripts/ifcfg-eth0:0` (put your own IPV6ADDR here, rest doesn't change)
```
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=none
DEFROUTE=yes
DEVICE=eth0:0
IPV6ADDR=2a01:4f8:c2c:XXXX::1/64
IPV6INIT=yes
IPV6_DEFAULTGW=fe80::1%eth0
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
```

**Comment by andryyy** [comment]
Ah, sounds fun. Perhaps I will order myself a VPS there to test. :) Thank you, @foutrelis

**Comment by daemon-byte** [comment]
Foutrelis, I'm not sure what's happened. It's been working great for months. Alas Hetzner support has still not even bothered to reply after 5 hours. Given their current level of support I am seriously considering taking this opportunity and trying somewhere else. 

That said I did notice one slight error. My file had just Device=eth0 and when I fixed it to match yours my server did start listening on it's ipv6 address. Alas it still can't seem to reach out. a ping6 of google just gives me Destination unreachable: Address unreachable. Been comparing it to my debian one but I can't see what's different anymore. Except one works :D

**Comment by andryyy** [comment]
How much do you pay for the 5 hour SLA on a Saturday?

**Comment by daemon-byte** [comment]
This is the first time I've really needed the support staff. Before now I used to use asmallorange (before they got bought out and went shit) and their support was always under an hour. Bytemark before them was just as fast. Hetzner promised 24/7 support but I guess they get you by not actually telling you how long you have to wait.

**Comment by svengo** [comment]
I switched from Hetzner to netcup because of such things.

**Comment by daemon-byte** [comment]
Svengo, I might check them out. They have good support?

**Comment by daemon-byte** [comment]
well disabling ipv6 in mailcow conf was the solution I went with for now to get the ssl back. We'll see what Monday brings but I suspect I will be moving to someone else. Just have to find another 100% green hosting company, European based (if not German) with ipv6 and 24/7 support. Should be easy :D Thanks all for the help

**Comment by svengo** [comment]
@daemon-byte, try it out. Netcup is a German company and uses [green energy] (https://www.netcup.eu/ueber-netcup/oekostrom.php).

**Comment by daemon-byte** [comment]
Svengo, I looked at them but their support is office hours only. I'm going to switch to comtrance (https://www.germanvps.com)  as they're also green and promise premium 24/7/365 support. I was talking to them at 1am and getting replies with half an hour
