### ISSUE TITLE
Vacation auto-replies are tagged with SPOOFED_UNAUTH

### ISSUE THREAD

**Issue by foutrelis** [mailcow/mailcow-dockerized#2620]
Fully updated mailcow running on Centos 7 with SELinux enabled on a Hetzner cloud server.

In a clean installation serving one domain, I have added a new mailbox with a vacation auto-reply configured via SOGo. In response to an email originating from a Gmail address, a vacation auto-reply is generated and sent by mailcow. However, the outbound message is tagged with SPOOFED_UNAUTH. (The same thing happens with forwards configured in SOGo.)

I believe Rspamd doesn't recognize mailcow-dovecot's IP (172.22.1.250) as authorized to send mail from my test domain (moo.foutrelis.com / "v=spf1 mx -all" / "v=DMARC1; p=none"). Any idea how this can be addressed or whether I'm missing some detail?

![mailcow-vacation-auto-reply-spoofed](https://user-images.githubusercontent.com/38810/57973930-0ddcde00-79b9-11e9-9c7c-7758dacda9d4.png)

**Comment by andryyy** [comment]
Thanks, yes, should indeed be trusted. I will try to add it tomorrow.

**Comment by andryyy** [comment]
Should be fixed. Looks good here, can you confirm?

**Comment by foutrelis** [comment]
Seems to be working well. Many thanks!
