### ISSUE TITLE
Initial misconfiguration prevents folder sharing

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2621]
**Describe the bug, try to make it reproducible**
This was referred in #2511 but there were no information provided, and in fact it has nothing to do with SOGo, so I'm opening a new issue.

The original configuration for Dovecot has:

```
mail_location = maildir:~/
[...]
 namespace {
     type = shared
     separator = /
     prefix = Shared/%%u/
    location = maildir:%%h/:INDEX=~/Shared/%%u;CONTROL=~/Shared/%%u
/Shared/%%u
     subscriptions = no
     list = children
 }
```

Reading this, one might be tempted to think that the mails for each user would end in `/var/vmail/example.com/mytestuser`. However this is *not* the case. Mails end up in `/var/vmail/example.com/mytestuser/Maildir` and related subfolders.

This means that the shared folder machinery will write things to the *wrong* folder (one level above) and thus they won't be even recorded as folders. Example from IMAP:

```
. OK Logged in
. list "" "*"
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
. OK List completed (0.008 + 0.000 + 0.007 secs).
```

If you fix it to add `Maildir` to the `location` configuration directive and restart dovecot:

```
. list "" "*"
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\Noselect \HasChildren) "/" Shared
* LIST (\Noselect \HasChildren) "/" Shared/testuser@example.com
* LIST (\HasNoChildren) "/" Shared/testuser@example.com/marketing
* LIST (\HasNoChildren) "/" INBOX
. OK List completed (0.008 + 0.000 + 0.007 secs).
```

Like this the folders also appear in SOGo, while before users set all the required permissions then scratched their heads while nothing happened.

IOW, this is required to make it work (`dovecot.conf`):

```diff
 namespace {
     type = shared
     separator = /
     prefix = Shared/%%u/
-    location = maildir:%%h/:INDEX=~/Shared/%%u;CONTROL=~/Shared/%%u
+    location = maildir:%%h/Maildir:INDEX=~/Maildir/Shared/%%u;CONTROL=~/Maildir/Shared/%%u
     subscriptions = no
     list = children
 }
```

**System information and quick debugging**
General logs:
There is no indication in the logs that anything is going wrong. Everything fails silently.

Further information (where applicable):
 - openSUSE Leap 15.0 and Ubuntu 18.04
 - KVM (Hetzner Cloud)
 - 8G / 2 vCores
 - Docker 18.09, docker-compose version 1.24.0

**Comment by andryyy** [comment]
You are correct and I was stupid. Fixed this. Give me a few secs

**Comment by andryyy** [comment]
Should be fixed by 922a8db7a5c6e9e28d23a67a8b31f92271d6aa5a

**Comment by lbeltrame** [comment]
Thanks, I'll try to spin a VM soon (I'm currently just using them as throwaways as I test migrations) and see if it's indeed fixed (but from what I read, it should indeed work).

**Comment by lbeltrame** [comment]
Forgot to close, but it is indeed fixed.
