### ISSUE TITLE
Public Calendar Sharing broken

### ISSUE THREAD

**Issue by jesse-osiecki** [mailcow/mailcow-dockerized#2625]
Setting up public calendar sharing seems to be broken. Curling `https://<host>/SOGo/dav/public/<name>@<domain>/Calendar/personal.ics` returns `object not found: public =&gt; <name>@<domain> =&gt; Calendar =&gt; personal% `

Steps I've taken

1. updated mailcow-dockerized to latest
2. Tried switching on `ACL_ANYONE=allow`
3. Ensured that `SOGoEnablePublicAccess = YES`
4. Run `docker-compose down && docker-compose up -d` to make sure changes take effect

The only line in sogo-mailcow I get in the logs from CUrl is:
`sogo-mailcow_1       | May 19 13:10:58 fc03bf60a4a8 sogod [73]: <ipaddr> "GET /SOGo/dav/public/<name>@<host>/Calendar/personal/ HTTP/1.0" 404 76/0 0.009 - - 0`

**Comment by andryyy** [comment]
When did it work last?

Oh, and where did you pull the URL from?

**Comment by jesse-osiecki** [comment]
It's never worked as far as I can tell
The URL is from the GUI under "Links to this Calendar"

**Comment by andryyy** [comment]
Hm, I think you can only open it with a CalDAV client.

**Comment by jesse-osiecki** [comment]
Wouldn't the CalDav client be making a GET request at that URI?

**Comment by andryyy** [comment]
It is not found, when you did not specify public access for this calendar:

![image](https://user-images.githubusercontent.com/2972950/58071248-4dafeb00-7b9c-11e9-97c0-f135e84b28ca.png)

Public read/WRITE access is not possible.

**Comment by jesse-osiecki** [comment]
I'm not asking about Public Write, just public read.
I do not have the same Access Rights options even with the aforementioned flags turned on in the configuration file. I DO have "Public Access" links under the "Links to this Calendar" menu
![2019-05-21-132305_681x212_scrot](https://user-images.githubusercontent.com/532841/58117058-c2e6e480-7bcb-11e9-8e9f-8598aa8bd33c.png)

**Comment by newlan29** [comment]
Hi,
I've the same problem, and I don't find any issue. I check the same parameters than stratosmacker

Someone have an idea ?

Thanks

**Comment by andryyy** [comment]
Works with ALLOW_ANY, but this is not always wanted. 

We should not apply `data/Dockerfiles/sogo/acl.diff`. _OR_ we need to exclude the removal from several cases like those mentioned above. 

I think it is better to remove the acl.diff at all and point to the docs. @mkuron ?

ALLOW_ANY should not affect public calendar sharing.

**Comment by mkuron** [comment]
I actually don‘t fully understand the issue here. I liked the diff solution (and it‘s better than asking people to manually rebuild the Docker image if they want ti change it), but I don‘t use it myself.

**Comment by andryyy** [comment]
Enabling ALLOW_ANY also enables any access in Dovecot. 

Adding public access for calendars does not make them visible for any other user on the mailcow instance. You cannot search them. You'd need to know the path.

So a public calendar should be possible without adding "any" access to Dovecot.

**Comment by mkuron** [comment]
Ah, I see. So should we have two different public options, one for Dovecot and one for the calendars?

**Comment by andryyy** [comment]
Hm. SOGo has an option to enable public folders.

**Comment by microchipster** [comment]
Hi, having exactly the same problem, which is that the access rights view looks like @stratosmacker's image above, so there's no way to share the calendar outside of SoGO. A bit confused by the discussion. Is there some setting "ALLOW_ANY" that can be set in some config file to make this work, or is public sharing actually broken?

**Comment by andryyy** [comment]
I think we should revert the ACL patch to create a public accessible calendar. Public calendars can be disabled in sogo.conf. 

The patch removes an option, that should not be hidden anyway.

**Comment by microchipster** [comment]
I've got 
```
SOGoCalendarDefaultRoles = (
        PublicViewer,
        ConfidentialDAndTViewer,
        PrivateDAndTViewer
    );
SOGoEnablePublicAccess = YES;
```
and it still seems to not show the ability to make the calendar public.
So if I were to remove this file `data/Dockerfiles/sogo/acl.diff` and rebuild the container, that would re-enable public calendar access?

**Comment by andryyy** [comment]
Yes
