### ISSUE TITLE
Can't setup a new instance of mailcow

### ISSUE THREAD

**Issue by ReptoxX** [mailcow/mailcow-dockerized#2626]
**Describe the bug, try to make it reproducible**
Just tried to setup a new mailcow server and the mysql server does not start.

mysql-mailcow_1      | Initializing database
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Plugin 'InnoDB' init function returned error.
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] mysqld: Got error 'Size of control file is smaller than expected' when trying to use aria control file '/var/lib/mysql/aria_log_control'
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Plugin 'Aria' init function returned error.
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Unknown/unsupported storage engine: InnoDB
mysql-mailcow_1      | 2019-05-19 23:18:22 140406785447232 [ERROR] Aborting
mysql-mailcow_1      | 
mysql-mailcow_1      | 
mysql-mailcow_1      | Installation of system tables failed!  Examine the logs in
mysql-mailcow_1      | /var/lib/mysql/ for more information.
mysql-mailcow_1      | 
mysql-mailcow_1      | The problem could be conflicting information in an external
mysql-mailcow_1      | my.cnf files. You can ignore these by doing:
mysql-mailcow_1      | 
mysql-mailcow_1      |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
mysql-mailcow_1      | 
mysql-mailcow_1      | You can also try to start the mysqld daemon with:
mysql-mailcow_1      | 
mysql-mailcow_1      |     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &
mysql-mailcow_1      | 
mysql-mailcow_1      | and use the command line tool /usr/bin/mysql
mysql-mailcow_1      | to connect to the mysql database and look at the grant tables:
mysql-mailcow_1      | 
mysql-mailcow_1      |     shell> /usr/bin/mysql -u root mysql
mysql-mailcow_1      |     mysql> show tables;
mysql-mailcow_1      | 
mysql-mailcow_1      | Try 'mysqld --help' if you have problems with paths.  Using
mysql-mailcow_1      | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
mysql-mailcow_1      |

**Comment by liquidat** [comment]
Are you using Docker on MaxOS, or on Windows, so inside a VM? Do you have other images besides the mailcow ones? If so, try remov not-needed images and try again.

Reason for my question: this error can come up when a disk runs out of space. The Docker on X VMs are - to the best of my knowledge - limited in size, and you might have hit that limit.

**Comment by ReptoxX** [comment]
I am using Docker on a LXC Virtual Machine (OS: Ubuntu 18.04.2).
And there are no other containers, just trying to install on a fresh server.

It could be possible, that i hit the maximum disk size. But i adjusted it and gave it 16GB more space and still having the same error.

**Comment by mkuron** [comment]
LXC and Docker are known not to work together too well. Just search for the issue tracker for "LXC". There's not much we can do about it.

**Comment by ReptoxX** [comment]
It's not the same issue. I am well known about that problem and i fixed it.
Ive ran this mailserver on an other lxc machine for well over a year.
