### ISSUE TITLE
Letsencrypt Certs only for Subdomains...?

### ISSUE THREAD

**Issue by schoebelh** [mailcow/mailcow-dockerized#2627]
How can i setup the system to got the certs made by acme-client also for the domain and not only for FQDN (subdomains)...?

Thanks...

...Hagen

**Comment by mkuron** [comment]
You can add additional domains via `ADDITIONAL_SAN` in mailcow.conf.

**Comment by schoebelh** [comment]
I alredy use this for alternate SAN Names - but what i asked for is a SAN attribute for the domain name ONLY (without subdomain in Front).

Not: Mail.domain.net
But: domain.net

Hope now it is better understandable.

...Hagen

**Comment by ntimo** [comment]
@schoebelh You can simply add domain.net to `ADDITIONAL_SAN` .

**Comment by schoebelh** [comment]
Perfect! Thank you for the tip - this was too simple for my over-complexed thinking...
