### ISSUE TITLE
Confirmed A record xx.xx.xx.xx, but HTTP validation failed, no reverse Proxy

### ISSUE THREAD

**Issue by Fvbor** [mailcow/mailcow-dockerized#2632]
**Describe the bug, try to make it reproducible**
A clear and concise description of what the bug is. How can it be reproduced? 
If applicable, add screenshots to help explain your problem. Very useful for bugs in mailcow UI.

**System information and quick debugging**
General logs:
- Please take a look at the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?): **CentOS 7.6.1810**
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.): **VMWare**
 - Your server/VM specifications (Memory, CPU Cores): **2 vCores, 2 GB vRAM**
 - Don't try to run mailcow on a Synology or QNAP NAS, do you?: **No**
 - Docker version: **18.09.6**
 - Docker Compose versions: **1.24.0**
 - Output of `git diff origin/master`, any other changes to the code? **Nothing**
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Reverse proxy? If you think this problem is related to your reverse proxy, please post your configuration: **No**
 - Browser (if it's a Web UI issue) - please clean your browser cache and try again, problem persists? **Chrome, bot no UI issue**
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
```
[root@mx1 mailcow-dockerized]# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.129.69
151.101.193.69
151.101.65.69
[root@mx1 mailcow-dockerized]# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.129.69
151.101.193.69
151.101.1.69
151.101.65.69
```

Problem: We have an Mailcow Dockerized system which can´t get an SSL Cert since a few weeks.
The old Cert is outdated and marked as insecure.
Between the VM and the internet is no other System, excepting Gateways.
Domain: mx1.grone-tec.de
IP: 62.112.51.21 (IP is an public IP)

[Cannot validate hostnames, skipping Let's Encrypt for 1 hour. #2323](https://github.com/mailcow/mailcow-dockerized/issues/2323#issuecomment-463295284)
```
[root@mx1 mailcow-dockerized]# cd /opt/mailcow-dockerized
[root@mx1 mailcow-dockerized]# source mailcow.conf
[root@mx1 mailcow-dockerized]# touch data/web/.well-known/acme-challenge/1
[root@mx1 mailcow-dockerized]# # For IPv4, should return 2xx or 3xx
[root@mx1 mailcow-dockerized]# docker-compose exec acme-mailcow curl -4 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
curl: (7) Failed to connect to mx1.grone-tec.de port 80: Host is unreachable
```

[But file is reachable and shows the content of the file](http://mx1.grone-tec.de/.well-known/acme-challenge/1)
```
[root@mx1 mailcow-dockerized]# vi data/web/.well-known/acme-challenge/1
ll
~
"data/web/.well-known/acme-challenge/1" 1L, 3C
```

ACME Log from the Mailcow GUI 
```
21.5.2019, 13:37:59	Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
21.5.2019, 13:37:59	Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
21.5.2019, 13:37:59	Confirmed A record 62.112.51.21, but HTTP validation failed
21.5.2019, 13:37:58	Found A record for mx1.grone-tec.de: 62.112.51.21
21.5.2019, 13:37:58	Confirmed AAAA record 62.112.51.21, but HTTP validation failed
21.5.2019, 13:37:57	Found A record for autodiscover.grone-tec.de: 62.112.51.21
21.5.2019, 13:37:57	No A or AAAA record found for hostname autodiscover.grone-controlling.de
21.5.2019, 13:37:55	Confirmed AAAA record 62.112.51.21, but HTTP validation failed
21.5.2019, 13:37:54	Found A record for autodiscover.fcc-hannover.de: 62.112.51.21
21.5.2019, 13:37:53	OK
21.5.2019, 13:37:33	Detecting IP addresses...
21.5.2019, 13:37:33	Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
21.5.2019, 13:37:33	Using existing domain key /var/lib/acme/acme/key.pem
21.5.2019, 13:37:33	Initializing, please wait...
21.5.2019, 13:37:33	OK
21.5.2019, 13:37:33	Waiting for domain table...
21.5.2019, 13:37:33	OK
21.5.2019, 13:37:33	Waiting for Nginx...
21.5.2019, 13:37:33	OK
21.5.2019, 13:37:33	Waiting for database...
21.5.2019, 13:37:33	OK
21.5.2019, 13:37:33	Waiting for Docker API...
```

- Have you tried it with reboot? **Yes, yesterday**
- Mailcow Updates? **Installed, last run: Today**

What can we do to get new valid Certificates?
Thank you

**Comment by andryyy** [comment]
The script cannot connect to itself from within the Docker network (mailcow-br to external interface). You can skip the http validation in mailcow.conf, but the DNS record validation will fail.

The iptables output would have been useful.

**Comment by Fvbor** [comment]
Here it is:
```
[root@mx1 ~]# iptables-save
# Generated by iptables-save v1.4.21 on Fri May 24 11:30:06 2019
*nat
:PREROUTING ACCEPT [158647:10055626]
:INPUT ACCEPT [8137:395114]
:OUTPUT ACCEPT [3545:269155]
:POSTROUTING ACCEPT [99056:6201079]
:DOCKER - [0:0]
:OUTPUT_direct - [0:0]
:POSTROUTING_ZONES - [0:0]
:POSTROUTING_ZONES_SOURCE - [0:0]
:POSTROUTING_direct - [0:0]
:POST_public - [0:0]
:POST_public_allow - [0:0]
:POST_public_deny - [0:0]
:POST_public_log - [0:0]
:PREROUTING_ZONES - [0:0]
:PREROUTING_ZONES_SOURCE - [0:0]
:PREROUTING_direct - [0:0]
:PRE_public - [0:0]
:PRE_public_allow - [0:0]
:PRE_public_deny - [0:0]
:PRE_public_log - [0:0]
-A PREROUTING -j PREROUTING_direct
-A PREROUTING -j PREROUTING_ZONES_SOURCE
-A PREROUTING -j PREROUTING_ZONES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -j OUTPUT_direct
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.22.1.0/24 ! -o br-mailcow -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -j POSTROUTING_direct
-A POSTROUTING -j POSTROUTING_ZONES_SOURCE
-A POSTROUTING -j POSTROUTING_ZONES
-A POSTROUTING -s 172.22.1.6/32 -d 172.22.1.6/32 -p tcp -m tcp --dport 587 -j MASQUERADE
-A POSTROUTING -s 172.22.1.6/32 -d 172.22.1.6/32 -p tcp -m tcp --dport 465 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 3306 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 12345 -j MASQUERADE
-A POSTROUTING -s 172.22.1.6/32 -d 172.22.1.6/32 -p tcp -m tcp --dport 25 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 4190 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 995 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 993 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 143 -j MASQUERADE
-A POSTROUTING -s 172.22.1.250/32 -d 172.22.1.250/32 -p tcp -m tcp --dport 110 -j MASQUERADE
-A POSTROUTING -s 172.22.1.10/32 -d 172.22.1.10/32 -p tcp -m tcp --dport 443 -j MASQUERADE
-A POSTROUTING -s 172.22.1.10/32 -d 172.22.1.10/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A DOCKER -i br-mailcow -j RETURN
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 587 -j DNAT --to-destination 172.22.1.6:587
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 465 -j DNAT --to-destination 172.22.1.6:465
-A DOCKER -d 127.0.0.1/32 ! -i br-mailcow -p tcp -m tcp --dport 13306 -j DNAT --to-destination 172.22.1.7:3306
-A DOCKER -d 127.0.0.1/32 ! -i br-mailcow -p tcp -m tcp --dport 19991 -j DNAT --to-destination 172.22.1.250:12345
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 25 -j DNAT --to-destination 172.22.1.6:25
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 4190 -j DNAT --to-destination 172.22.1.250:4190
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 995 -j DNAT --to-destination 172.22.1.250:995
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 993 -j DNAT --to-destination 172.22.1.250:993
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 143 -j DNAT --to-destination 172.22.1.250:143
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 110 -j DNAT --to-destination 172.22.1.250:110
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 443 -j DNAT --to-destination 172.22.1.10:443
-A DOCKER ! -i br-mailcow -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.22.1.10:80
-A POSTROUTING_ZONES -o ens160 -g POST_public
-A POSTROUTING_ZONES -g POST_public
-A POST_public -j POST_public_log
-A POST_public -j POST_public_deny
-A POST_public -j POST_public_allow
-A PREROUTING_ZONES -i ens160 -g PRE_public
-A PREROUTING_ZONES -g PRE_public
-A PRE_public -j PRE_public_log
-A PRE_public -j PRE_public_deny
-A PRE_public -j PRE_public_allow
COMMIT
# Completed on Fri May 24 11:30:06 2019
# Generated by iptables-save v1.4.21 on Fri May 24 11:30:06 2019
*mangle
:PREROUTING ACCEPT [3098289:1933845376]
:INPUT ACCEPT [190862:106465100]
:FORWARD ACCEPT [2914980:1827910117]
:OUTPUT ACCEPT [252546:17928624]
:POSTROUTING ACCEPT [3167526:1845838741]
:FORWARD_direct - [0:0]
:INPUT_direct - [0:0]
:OUTPUT_direct - [0:0]
:POSTROUTING_direct - [0:0]
:PREROUTING_ZONES - [0:0]
:PREROUTING_ZONES_SOURCE - [0:0]
:PREROUTING_direct - [0:0]
:PRE_public - [0:0]
:PRE_public_allow - [0:0]
:PRE_public_deny - [0:0]
:PRE_public_log - [0:0]
-A PREROUTING -j PREROUTING_direct
-A PREROUTING -j PREROUTING_ZONES_SOURCE
-A PREROUTING -j PREROUTING_ZONES
-A INPUT -j INPUT_direct
-A FORWARD -j FORWARD_direct
-A OUTPUT -j OUTPUT_direct
-A POSTROUTING -j POSTROUTING_direct
-A PREROUTING_ZONES -i ens160 -g PRE_public
-A PREROUTING_ZONES -g PRE_public
-A PRE_public -j PRE_public_log
-A PRE_public -j PRE_public_deny
-A PRE_public -j PRE_public_allow
COMMIT
# Completed on Fri May 24 11:30:06 2019
# Generated by iptables-save v1.4.21 on Fri May 24 11:30:06 2019
*security
:INPUT ACCEPT [163820:105116523]
:FORWARD ACCEPT [2914980:1827910117]
:OUTPUT ACCEPT [252546:17928624]
:FORWARD_direct - [0:0]
:INPUT_direct - [0:0]
:OUTPUT_direct - [0:0]
-A INPUT -j INPUT_direct
-A FORWARD -j FORWARD_direct
-A OUTPUT -j OUTPUT_direct
COMMIT
# Completed on Fri May 24 11:30:06 2019
# Generated by iptables-save v1.4.21 on Fri May 24 11:30:06 2019
*raw
:PREROUTING ACCEPT [3098289:1933845376]
:OUTPUT ACCEPT [252546:17928624]
:OUTPUT_direct - [0:0]
:PREROUTING_ZONES - [0:0]
:PREROUTING_ZONES_SOURCE - [0:0]
:PREROUTING_direct - [0:0]
:PRE_public - [0:0]
:PRE_public_allow - [0:0]
:PRE_public_deny - [0:0]
:PRE_public_log - [0:0]
-A PREROUTING -j PREROUTING_direct
-A PREROUTING -j PREROUTING_ZONES_SOURCE
-A PREROUTING -j PREROUTING_ZONES
-A OUTPUT -j OUTPUT_direct
-A PREROUTING_ZONES -i ens160 -g PRE_public
-A PREROUTING_ZONES -g PRE_public
-A PRE_public -j PRE_public_log
-A PRE_public -j PRE_public_deny
-A PRE_public -j PRE_public_allow
COMMIT
# Completed on Fri May 24 11:30:06 2019
# Generated by iptables-save v1.4.21 on Fri May 24 11:30:06 2019
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [191262:13454682]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:FORWARD_IN_ZONES - [0:0]
:FORWARD_IN_ZONES_SOURCE - [0:0]
:FORWARD_OUT_ZONES - [0:0]
:FORWARD_OUT_ZONES_SOURCE - [0:0]
:FORWARD_direct - [0:0]
:FWDI_public - [0:0]
:FWDI_public_allow - [0:0]
:FWDI_public_deny - [0:0]
:FWDI_public_log - [0:0]
:FWDO_public - [0:0]
:FWDO_public_allow - [0:0]
:FWDO_public_deny - [0:0]
:FWDO_public_log - [0:0]
:INPUT_ZONES - [0:0]
:INPUT_ZONES_SOURCE - [0:0]
:INPUT_direct - [0:0]
:IN_public - [0:0]
:IN_public_allow - [0:0]
:IN_public_deny - [0:0]
:IN_public_log - [0:0]
:MAILCOW - [0:0]
:OUTPUT_direct - [0:0]
-A INPUT -j MAILCOW
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j INPUT_direct
-A INPUT -j INPUT_ZONES_SOURCE
-A INPUT -j INPUT_ZONES
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j MAILCOW
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o br-mailcow -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-mailcow -j DOCKER
-A FORWARD -i br-mailcow ! -o br-mailcow -j ACCEPT
-A FORWARD -i br-mailcow -o br-mailcow -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -j FORWARD_direct
-A FORWARD -j FORWARD_IN_ZONES_SOURCE
-A FORWARD -j FORWARD_IN_ZONES
-A FORWARD -j FORWARD_OUT_ZONES_SOURCE
-A FORWARD -j FORWARD_OUT_ZONES
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OUTPUT -j OUTPUT_direct
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 587 -j ACCEPT
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 465 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 12345 -j ACCEPT
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 25 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 4190 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 995 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 993 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 143 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 110 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.22.1.10/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i br-mailcow ! -o br-mailcow -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o br-mailcow -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A FORWARD_IN_ZONES -i ens160 -g FWDI_public
-A FORWARD_IN_ZONES -g FWDI_public
-A FORWARD_OUT_ZONES -o ens160 -g FWDO_public
-A FORWARD_OUT_ZONES -g FWDO_public
-A FWDI_public -j FWDI_public_log
-A FWDI_public -j FWDI_public_deny
-A FWDI_public -j FWDI_public_allow
-A FWDI_public -p icmp -j ACCEPT
-A FWDO_public -j FWDO_public_log
-A FWDO_public -j FWDO_public_deny
-A FWDO_public -j FWDO_public_allow
-A INPUT_ZONES -i ens160 -g IN_public
-A INPUT_ZONES -g IN_public
-A IN_public -j IN_public_log
-A IN_public -j IN_public_deny
-A IN_public -j IN_public_allow
-A IN_public -p icmp -j ACCEPT
-A IN_public_allow -s 62.112.35.4/32 -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j ACCEPT
-A IN_public_allow -s 62.112.34.74/32 -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j ACCEPT
COMMIT
# Completed on Fri May 24 11:30:06 2019
[root@mx1 ~]#

```

**Comment by jazzcrack** [comment]
@Fvbor -> Any news/solution? I run into the same problem. :-(

**Comment by Fvbor** [comment]
@jazzcrack No :( Still waiting for some idea/solution

**Comment by jazzcrack** [comment]
@Fvbor My solution is now, just found it, to set following options in mailcow.conf:

SKIP_IP_CHECK=y
SKIP_HTTP_VERIFICATION=y

I am not sure wich was the magic one, but for the moment I am happy. :-)

**Comment by Fvbor** [comment]
@jazzcrack I testet skip_ip_check in the past with no effect. I Guess the point skip_http_verification is the work around. Thank you!

But now the question: Anyone an idea for a solution?

**Comment by andryyy** [comment]
Well, the solution is above:

    The script cannot connect to itself from within the Docker network (mailcow-br to external interface)

I will not write that rule for you. :) You want to use firewalld/ufw/whatever, you need to configure it. `br-mailcow` => `external-interface`

**Comment by Ashby666** [comment]
Hi there,

I run in the same problem.
Same configuration like in the example above from Fvbor. No Reverse Proxy. Port 80 is open and can be reached via telnet and Web.

I have already tried all possible solutions I found here, incl. disable HTTP-Verification and Skip IP-Check in mailcow.conf.
I also tried the workaround from dvzunderd out of issues 2504 (https://github.com/mailcow/mailcow-dockerized/issues/2504#issuecomment-485275490). Also disabling firewalld makes no change.

I have no more ideas, what I can do. And I run serveral Cows in this setup with no problmes like this.

Any more ideas?

**Comment by andryyy** [comment]
Just make sure the bridge can connect to the external interface.

If it fails, your network configuration is causing this. It is really as easy as this. If you don’t mind fixing this issue on your side, you need to disable that check.

There can be several reasons it cannot connect to itself. I have also seen accept_ra **other than** 2 in IPv6 configs causing this. But there is nothing we could change in mailcow. We can skip this check, as it can mostly still request the certificates (LE is connecting from WAN, it is not connecting from mailcow-br), but it’s just a workaround. Some DNS checks will still fail. Sometimes it is firewalld or ufw though. Disable it and reset the chains. Do this for iptables and ip6tables. Restart Docker. 

I think we can close this issue now, it is not a bug in mailcow causing this. 

You can still ask people on IRC to help you, give those guys some logs and time.

**Comment by SWHGroup** [comment]
Don't forget to forward port 80 to mailcow server on your firewall/router before running docker-compose restart acme-mailcow, not doing so will also present you with the http validation warning

**Comment by Adorfer** [comment]
> Don't forget to forward port 80 to mailcow server on your firewall/router

i can't see how this is possible if there is no (reverse) Proxy in front of mailcow.
(note: please do not move goal posts of issues. In plus: This is an issue tracker, not the install-support-forum.)

**Comment by philharmonie** [comment]
Any news here? Having the same issue

**Comment by HusseinMorsy** [comment]
Same problem since today

**Comment by strarsis** [comment]
Same issue, I get those warnings for all of these. But I can reach mailcow `nginx` on port 80 and 443.

**Comment by DerLinkman** [comment]
Did your machine has IPv6?

**Comment by strarsis** [comment]
> Did your machine has IPv6?

Yes, the mail server has IPv4 and IPv6.

**Comment by DerLinkman** [comment]
Then take a look if the NGINX is listening on IPv6 from the new update.

**Comment by strarsis** [comment]
@DerLinkman: Yes, `nginx` doesn't appear to listen on the `IPv6` address, only on the `IPv4` one:
````
wget -6 https://mail.example.com
--2022-06-15 15:29:25--  https://mail.example.com/
Resolving mail.example.com (mail.example.com)... <the correct IPv6 of server>::1
Connecting to mail.example.com (mail.example.com)|<the correct IPv6 of server>::1|:443... failed: Connection refused.
````

**Comment by DerLinkman** [comment]
Yes that is the problem i guess.

Please follow that guide: https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-ip_bindings/#ipv6-binding

Only add the NGINX Block and replace the mentioned IP in there with [::]

**Comment by strarsis** [comment]
@DerLinkman: Good point! The current `docker-compose.yml` is unchanged, `git diff docker-compose.yml` prints nothing.
This is good I think, because a `docker-compose.override.yml` should be used instead.
But there is no `docker-compose.override.yml` yet. Hadn't used that yet. 

That may be the explanation for why this doesn't work correctly, `nginx` requires extra Docker configuration for `IPv6`.
Shouldn't `mailcow` setup add this automatically? Sure, I need to RTFM more, but I think `mailcow` setup should really add this automatically or at least point this out in a warning.

**Comment by DerLinkman** [comment]
Yeah that is because of the dual compatibility between Compose v1 and Compose v2. That manual change is only temporary until December at latest.

When we´re removing the Docker-Compose v1 Support everything will work as it does now.

**Comment by strarsis** [comment]
@DerLinkman: So until this is changed in December, I would apply that change manually and it should work.

There are two other issues with `acme` though:
- Just restarting the `docker compose` setup didn't make `mailcow` `acme` use the new `acme` related configuration (`ADDITIONAL_SAN` and others) in `mailcow.conf`,
I had to use the `update.sh` script.
- `mailcow` `acme` uses more domains than listed in the `ADDITIONAL_SAN` field, which can amount to more than `100` extra domains, the current Let's Encrypt limit.

**Comment by DerLinkman** [comment]
> Just restarting the docker compose setup didn't make mailcow acme use the new acme related configuration (ADDITIONAL_SAN and others) in mailcow.conf

You have to docker compose up -d the Container instead of docker compose restart. In all my machines that work as expected.

> mailcow acme uses more domains than listed in the ADDITIONAL_SAN field, which can amount to more than 100 extra domains, the current Let's Encrypt limit.

You mean the autoconfig, autodiscover per Domain if you set a Mail-Domain right?

**Comment by strarsis** [comment]
@DerLinkman: Not only `autoconfig` and `autodiscovery` (which makes sense), but also just other domains that are not listed there but which are added to `mailcow` GUI (mailbox domains). Those domains should not be included as `mail.domain.tld` "vanity" mail server domains shouldn't be used for these and to be below the `100` SAN extra domain limit of Let's Encrypt.

`docker-compose up -d` is enough for applying the new `mailcow.conf` configuration? Next time I will try that and report back if it doesn't work.

**Comment by DerLinkman** [comment]
Can you open that Limit issue in a extra Issue? This one here might not be the right place for that.
