### ISSUE TITLE
Nginx can't connect to port 80, altough it isnt used by anything.

### ISSUE THREAD

**Issue by Chicken-DEV** [mailcow/mailcow-dockerized#2633]
Hey, I think my hosting provider rebooted my server and since then I can't start mailcow. It's always the same bug.
Please note: My installation was once working, I have updated mailcow using the script in the mailcow folder. I also regenerated my config file using some other script in the same folder.

**System information and quick debugging**
General logs: 
https://gist.github.com/Chicken-DEV/5bf981c7e7ff39f8e030d06d58072c03

Further information (where applicable):
 **- Your OS (is Apparmor or SELinux active?)** Ubuntu 16.04.6 LTS
 **- Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)** OpenVZ 7
 **- Your server/VM specifications (Memory, CPU Cores)** 4GB  Ram; Intel Processor(I think); 100GB
 **- Don't try to run mailcow on a Synology or QNAP NAS, do you?** Nope
 **- Docker and Docker Compose versions:** Docker version 18.09.4, build d14af54; docker-compose version 1.24.0, build 0aa59064
 **- Output of `git diff origin/master`, any other changes to the code?**
```
index 939e0ba..a0e1499 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -399,7 +399,6 @@ services:
       image: mailcow/dockerapi:1.28
       restart: always
       build: ./data/Dockerfiles/dockerapi
-      oom_kill_disable: true
       environment:
         - DBROOT=${DBROOT}
         - TZ=${TZ}
```
 **- All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `:**  https://gist.github.com/Chicken-DEV/a9c550ba30aac856e858dcc7b2a97454

 **- Reverse proxy? If you think this problem is related to your reverse proxy, please post your configuration.** Where can I find the config file?

**Comment by cklabautermann** [comment]
I see in your logs:
`listen tcp 0.0.0.0:80: bind: address already in use`
so for me something is running on port 80.
do a `netstat -tuanp | grep 80| grep -i listen` to see what is listening on Port 80

**Comment by andryyy** [comment]
Yes, something is listening on port 80.

**Comment by Chicken-DEV** [comment]
Sorry for the late reply.
This is the output:
```root@mail:~# netstat -tuanp | grep 80| grep -i listen
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3713/nginx -g daemo
tcp6       0      0 :::80                   :::*                    LISTEN      3713/nginx -g daemo

**Comment by MAGICCC** [comment]
Seems you already have a webserver running. Either use it as reserve proxy or delete it

**Comment by Chicken-DEV** [comment]
Hmmm, that's weird. On that server I only installed mailcow and the stuff that is required for it. How can I stop or delete the webserver?

**Comment by MAGICCC** [comment]
I guess it was preinstalled
Try `apt purge nginx`

**Comment by Chicken-DEV** [comment]
I did that, but I still get the same error.

**Comment by Chicken-DEV** [comment]
Ah. I used `systemctl disable nginx` and now it starts but I get this spammed in my sonsole

```
php-fpm-mailcow_1    | Waiting for SQL...
sogo-mailcow_1       | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
```
and I got this:


```
sogo-mailcow_1       | Jun  5 22:06:01 cb6bc6eb29da CRON[251]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jun  5 22:06:01 cb6bc6eb29da CRON[255]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 60)
sogo-mailcow_1       | Jun  5 22:06:01 cb6bc6eb29da CRON[252]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jun  5 22:06:02 cb6bc6eb29da CRON[256]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Jun  5 22:06:02 cb6bc6eb29da CRON[251]: (CRON) info (No MTA installed, discarding output)
sogo-mailcow_1       | Jun  5 22:06:02 cb6bc6eb29da CRON[251]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Jun  5 22:06:02 cb6bc6eb29da CRON[252]: pam_unix(cron:session): session closed for user sogo
```

```
clamd-mailcow_1      | rsync: failed to connect to 178.62.122.45 (178.62.122.45): Connection timed out (110)
clamd-mailcow_1      | rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
clamd-mailcow_1      |
sogo-mailcow_1       | Waiting for database to come up...
clamd-mailcow_1      | receiving incremental file list
clamd-mailcow_1      | ./
clamd-mailcow_1      | blurl.ndb
clamd-mailcow_1      | junk.ndb
dovecot-mailcow_1    | Waiting for database to come up...
clamd-mailcow_1      | jurlbl.ndb
clamd-mailcow_1      | phish.ndb
php-fpm-mailcow_1    | Waiting for SQL...
clamd-mailcow_1      | phishtank.ndb
clamd-mailcow_1      | rogue.hdb
sogo-mailcow_1       | Waiting for database to come up...
clamd-mailcow_1      | sanesecurity.ftm
clamd-mailcow_1      | scam.ndb
clamd-mailcow_1      | sigwhitelist.ign2
clamd-mailcow_1      | spamimg.hdb
clamd-mailcow_1      |
clamd-mailcow_1      | sent 420 bytes  received 19,306,068 bytes  5,516,139.43 bytes/sec
clamd-mailcow_1      | total size is 19,303,029  speedup is 1.00
clamd-mailcow_1      | RELOADING
dovecot-mailcow_1    | Waiting for database to come up...
clamd-mailcow_1      | Wed Jun  5 22:06:14 2019 -> Reading databases from /var/lib/clamav
```
