### ISSUE TITLE
Letsencrypt HTTP validation failed although it shouldn't 

### ISSUE THREAD

**Issue by simonszu** [mailcow/mailcow-dockerized#2634]
I, too, have a problem with obtaining Letsencrypt certificates. Since it doesn't fit into other issues, i'll describe.

Mailcow is running in a VM which has both IPv4 and IPv6. There exists a reverse proxy (HAproxy) on another VM. Mailcow has NAT for both IPv4 and IPv6 due to DNS wildcard issues, so the DNS records for mailcow, autodiscover and autoconfig point to the VM with HAproxy, and mailcow's outbound traffic passes this VM as well.

Therefore the DNS config for autodiscover does not match the local IPv6 of the mailcow VM, and neither does it for IPv4. So, i activated `SKIP_IP_CHECK=y`in mailcow.conf and retried the procedure.

To my surprise and maybe contrary to the documentation, this flag only disables IP check for IPv4. This seems reasonable since NATv6 is quite uncommon. To solve this problem one for all, i disabled IPv6 in the network config. This is the result i still have:

``` 
acme-mailcow_1 | OK 
acme-mailcow_1 | Wed May 22 13:59:17 CEST 2019 - Waiting for Nginx… OK 
acme-mailcow_1 | Wed May 22 13:59:21 CEST 2019 - Waiting for domain table… OK 
acme-mailcow_1 | Wed May 22 13:59:21 CEST 2019 - Initializing, please wait… 
acme-mailcow_1 | Wed May 22 13:59:21 CEST 2019 - Using existing domain key /var/lib/acme/acme/key.pem 
acme-mailcow_1 | Wed May 22 13:59:21 CEST 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem 
acme-mailcow_1 | Wed May 22 13:59:21 CEST 2019 - Detecting IP addresses… OK 
acme-mailcow_1 | Wed May 22 13:59:32 CEST 2019 - Found AAAA record for autodiscover.simonszu.de: 2a01:4f8:202:5467::1 - skipping A record check 
acme-mailcow_1 | Wed May 22 13:59:32 CEST 2019 - Confirmed AAAA record 2a01:4f8:202:5467::1, but HTTP validation failed 
acme-mailcow_1 | Wed May 22 13:59:32 CEST 2019 - Found AAAA record for mail.simonszu.de: 2a01:4f8:202:5467::1 - skipping A record check 
acme-mailcow_1 | Wed May 22 13:59:33 CEST 2019 - Confirmed AAAA record 148.251.84.126, but HTTP validation failed 
acme-mailcow_1 | Wed May 22 13:59:33 CEST 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
acme-mailcow_1 | Wed May 22 13:59:33 CEST 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently. 
acme-mailcow_1 | OK
 ``` 
Besides the minor bug that the container shows an IPv4 as an AAAA record, the detected IP addresses are the public addresses of the firewall/NAT VM. What bugs me is the problem that the HTTP validation failed.

I have configured the HAproxy that autodiscover and mail subdomain point to the mailcow VM. Accessing both domains via HTTP shows the mailcow admin interface.

I have completed @andryyy s check from https://github.com/mailcow/mailcow-dockerized/issues/2305#issuecomment-462530713 and can confirm that the IPv4 curl returns a 200 status code and the IPv6 curl cannot connect to server - so in my opinion everything should be okay.

But it isn't. So i could need some help.

Here are the obligatory system informations: 
- OS: Debian Stretch Stable
- Last time rebooted: Last weekend (around 4 days ago)
- Last time the update.sh script executed: Today 
- Firewall on the mailcow VM: None. Debian has no ufw, and i have no iptables added 
- Firewall on the firewall VM: OpnSense, with HAproxy. It is configured that autodiscover and mail subdomain can access the admin interface on both port 80 and 443. HTTP is _not_ automatically redirected to HTTPS for these subdomains. HAproxy is configured for both IPv4 and v6. 
- AppArmor or SElinux is disabled or not installed

**Comment by andryyy** [comment]
A 200 does not automatically indicate a working validation. It is still possible a web server is returning 200 when you try the snippet from #2305 

A `source mailcow.conf ; docker-compose exec acme-mailcow curl -4 -IL http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1` (same with -6) would be helpful.

**Comment by andryyy** [comment]
And thanks for reporting the "confirmed AAAA" stuff. :)

**Comment by simonszu** [comment]
Okay, here are the outputs:

```
# docker-compose exec acme-mailcow curl -4 -IL http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 23 May 2019 11:16:29 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Last-Modified: Wed, 22 May 2019 12:18:46 GMT
ETag: "5ce53e26-0"
Strict-Transport-Security: max-age=15768000;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin
Accept-Ranges: bytes
```

and 

```
# docker-compose exec acme-mailcow curl -6 -IL http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
curl: (7) Couldn't connect to server
```

I'm afraid i cannot interpret these results correctly since i do not know what they should be. I only see that curl is connecting to nginx, so i assume that my HAproxy is indeed configured correctly. 

One additional info: The problems occured at first after i had to completely reinstall the hypervisor and all VMs. I had a backup of the firewall VM config which i just re-applied. I did not have a backup of the mailcow.conf, so i recreated it by hand. The network config from the hypervisor itself is the same when it was before i had to reinstall. The previous installation had a working Letsencrypt setup. 

I did not have any problems with IPv6  in the previous install as well - unfortunately i do not remember if i did disable the IP checks or not.

**Comment by simonszu** [comment]
Any updates or hints on this? I am still struggling to track down this issue.

**Comment by andryyy** [comment]
You cannot connect to your own name via IPv6. This is a firewall issue I cannot help with.

If you are fine with the bridge not being able to access to the outer interface (external), you can skip the http verification check in mailcow.conf.

**Comment by simonszu** [comment]
Yeah, i am fine with that. It is strange that the acme container is trying to connect via v6 at all, since i disabled v6 in the network section of the compose file. I'm sorry i didn't see the HTTP check disabling option in the mailcow.conf file, i'll try this.  - OK, it worked. Thank you very much for helping.
