### ISSUE TITLE
Docker-compose error

### ISSUE THREAD

**Issue by notrurs** [mailcow/mailcow-dockerized#2635]
When I try

`docker-compose pull`

I get warning and error:

> WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.

> ERROR: Invalid interpolation format for "environment" option in service "dovecot-mailcow": "MAILDIR_SUB=${MAILDIR_SUB:-}"

What should be in MAILDIR_SUB?

**Comment by andryyy** [comment]
You need an up-to-date docker-compose. Don't delete the issue template, please. :)

**Comment by notrurs** [comment]
Omg! Thanks :)
