### ISSUE TITLE
logs in Redis don‘t get trimmed

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#2636]
Hey guys. I would like to ask a question regarding the importance of data stored in redis. For example, if I delete the content of `redis-vol-1` on production system and restart mailcow, what happens? I know logs and fail2ban data are stored there; rspamd should be using redis as well, but are the data more than temporary?

I'm asking b/c I'm thinking about turning off the redis snapshotting to save some IO. Currently in my setup, redis is saving it's database (~400mb) every 5 minutes to disk, which seems rather unnecessary, if it's only temporary data.

Thanks!

**Comment by mkuron** [comment]
DKIM keys, settings like the forwarding hosts, rspamd training data. If you disable the snapshots, you should manually dump the database daily as part of your backup procedure.

**Comment by pschiffe** [comment]
Hey @mkuron , thank you very much for your answer. I've configured redis to save the snapshot of the database every 3 hours, so it's still relatively up to date, without wasting too much IO.

I have one more question, regarding the size of the database, currently for me it's almost 400mb. Looking at the output of `redis-cli --bigkeys` I see that there is massive amount of logs, for example:
```
'DOVECOT_MAILLOG' with 1695784 items
'POSTFIX_MAILLOG' with 3334111 items
'SOGO_LOG' with 3719816 items
```
Is there a way how to trim old logs? For example, delete all logs older than a year, or something similar.

**Comment by mkuron** [comment]
Please use the variable `LOG_LINES` in mailcow.conf for that. By default, it‘s set to 9999. I guess you set that to a larger number if you have millions of log entries?

**Comment by andryyy** [comment]
That made me notice we didn't trim WATCHDOG_LOG, I fix that.

**Comment by pschiffe** [comment]
Interesting, I do have `LOG_LINES=9999` in my `mailcow.conf` file, but it seems ineffective. Some log from dovecot container:
```
# docker logs mailcowdockerized_dovecot-mailcow_1 | grep trim | tail -n 3
May 25 14:07:01 host CRON[10826]: (vmail) CMD (/usr/local/bin/trim_logs.sh >> /dev/console 2>&1)
May 25 14:08:01 host CRON[10847]: (vmail) CMD (/usr/local/bin/trim_logs.sh >> /dev/console 2>&1)
May 25 14:09:01 host CRON[10854]: (vmail) CMD (/usr/local/bin/trim_logs.sh >> /dev/console 2>&1)
```
However, the output from `redis-cli --bigkeys` is still the same as in the comment above. I have 2 instances of mailcow, and none of them have the logs in redis trimmed.

BTW, I see this cron config in dovecot container:
```
echo '* * * * *    vmail /usr/local/bin/trim_logs.sh >> /dev/console 2>&1' > /etc/cron.d/trim_logs
```
Instead of every minute, wouldn't it be enough to run it every 5 or 10 minutes? I don't know right now how costly is that operation, every minute just seems rather unnecessary.

**Comment by andryyy** [comment]
Don’t know. I cannot replicate it here. All logs are trimmed. 

Every minute is fine, these logs can blow up pretty fast. 

Try to run the script manually, please. Inside Dovecot.

**Comment by pschiffe** [comment]
I think I found a problem:
```
# docker exec -it mailcowdockerized_dovecot-mailcow_1 bash
root@host:/# su - vmail
$ whoami
vmail
$ /usr/local/bin/trim_logs.sh
$ /usr/local/bin/trim_logs.sh >> /dev/console
-su: 3: cannot create /dev/console: Permission denied
$ ls -lh /dev/console
crw-rw----. 1 root root 136, 2 May 25 13:28 /dev/console
```

I'm using centos 7 with selinux on. Is redirect to `/dev/console` necessary? Seems like any cronjob not running under `root` with `>> /dev/console` doesn't work for me.

**Comment by mkuron** [comment]
I cannot reproduce this with your commands, but I'm on Debian without SELinux enabled. Could you check the kernel log on the host to see whether it is SELinux blocking this?

The redirect should probably be using `>` instead of `>>`, but that's not the problem here. The purpose of the redirect is that any output should appear when you do `docker-compose logs`, so we should keep it.

**Comment by pschiffe** [comment]
OK, this is not selinux related; I've disabled selinux on host (Permissive mode), but it's still the same:
```
$ /usr/local/bin/trim_logs.sh >> /dev/console
-su: 2: cannot create /dev/console: Permission denied
$ /usr/local/bin/trim_logs.sh > /dev/console
-su: 3: cannot create /dev/console: Permission denied
```

Can you check `ls -lh /dev/console` from inside of your dovecot container? I think this is the reason. BTW I have:
```
# rpm -q docker
docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
```

**Comment by pschiffe** [comment]
Hm, output from `stdout` and `stderr` should be available in `docker(-compose) logs` by default, there shouldn't be a need to redirect that to a `/dev/console` inside of a container..

**Comment by mkuron** [comment]
That only applies to the output of the entrypoint. Cron jobs are running in the background.

**Comment by pschiffe** [comment]
I see. @mkuron what are the permissions of `/dev/console` inside of dovecot container in your case? is the `vmail` user able to write there?

**Comment by andryyy** [comment]
Checking it now. :)

**Comment by andryyy** [comment]
```
vmail@mx:/$ /usr/local/bin/trim_logs.sh >> /dev/console
vmail@mx:/$
```

It was an issue a while ago. Can you please make sure, you are using the latest compose file and Dovecot image?

**Comment by pschiffe** [comment]
Hm :/ yes, I have updated yesterday, now I have `image: mailcow/dovecot:1.72`. Could you show me your `ls -lh /dev/console` from inside of the dovecot container?

**Comment by pschiffe** [comment]
Hey guys, I'm sorry to bother, but can you @mkuron or @andryyy post here the output of `ls -lh /dev/console` from inside of dovecot container? I just want to make sure, that debian has different permissions than centos, before trying to somehow workaround this problem. Thanks!

**Comment by andryyy** [comment]
Sorry! Forgot.

```
root@mx:/opt/mailcow-dockerized# docker-compose exec unbound-mailcow ls -lh /dev/console
crw-rw----    1 root     tty       136,   0 May 29 05:52 /dev/console
root@mx:/opt/mailcow-dockerized# docker-compose exec dovecot-mailcow ls -lh /dev/console
crw-rw---- 1 root tty 136, 0 May 29 10:59 /dev/console
root@mx:/opt/mailcow-dockerized#
```

Both containers have the tty attached.

Do you run mailcow with SELinux enabled?

**Comment by pschiffe** [comment]
Hi @andryyy , thanks for your response and sorry for my delay. Basically the issue was that group of `/dev/console` file, in my case it was `root` and `vmail` user couldn't write there. However, this change fixed it for me, so thank you very much for that! https://github.com/mailcow/mailcow-dockerized/commit/395f0f7a3d0d58f584149eeb5d33991dd468cd10#diff-5f8ac4d652ab609372acf90f4ee4c618R196

**Comment by andryyy** [comment]
Nice, thanks for your feedback!
