### ISSUE TITLE
Update script: Pull images before stopping containers

### ISSUE THREAD

**Issue by DomiStyle** [mailcow/mailcow-dockerized#2637]
Currently the update.sh script will stop all containers before pulling the new images, as seen [here](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh#L295) and [here](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh#L351).

Wouldn't it be better to do it the other way around to minimize downtime during updates? Pull images and then stop the containers.

The separate stopping routine could even be skipped entirely if the files that are being changed do not interfere with the running instances.

**Comment by ntimo** [comment]
Hey,
I think this would be quite nice. I also can't think of a reason why pulling the imags before stopping mailcow would not work. Of course you would have to do that before the git pull.

**Comment by andryyy** [comment]
There is already an issue for this. :)

When the docker compose yml file changed, it can lead to strange errors when stopping the "old" stack with the new (changed) compose file.

We could checkout the new compose file to another location (`git show origin/master:docker-compose.yml > bla.yml` probably works) and pull the images independently, but it will still not reflect potential changes included with a docker-compose.override.yml or even local changes written directly into docker-compose.yml (you shouldn't do this anyway, but still...).

An idea: we run docker-compose pull **a second time** after merging the code to make sure we don't miss images in a override file. We'd run pull twice, but the down time is reduced.

**Comment by ntimo** [comment]
@andryyy I think we can simply checkout the docker-compose.yml since the only relevant part for stopping the containers are the service names. And then we can simply pull the images and start the container. I am working on a PR at the moment.

**Comment by andryyy** [comment]
No. Please read the potential problems and the other issues why I removed it previously. We cannot simply revert to something I told was broken and led to errors.

**Comment by ntimo** [comment]
Okay, I will change the PR later and checkout the file under a different name, then pull and then after stopping pull again. 👍 .

**Comment by DomiStyle** [comment]
> There is already an issue for this. :)

Sorry, only searched the open ones but I found it now: #524 

> When the docker compose yml file changed, it can lead to strange errors when stopping the "old" stack with the new (changed) compose file.

You mentioned the other issues in #524, you have a link for them or a way to reproduce this? I would like to take a look at what's happening.

> We'd run pull twice, but the down time is reduced.

A longer update procedure is ok if downtime is reduced in my opinion. Especially since the Docker Hub likes to slow to a crawl from time to time but at that point the containers are already stopped.

**Comment by christianbur** [comment]
I would simply add the following command [here](https://github.com/mailcow/mailcow-dockerized/blob/57d65535c9663265adf7337775684a7fefad657b/update.sh#L294) and the problem would be solved. The rest of the update script remains unchanged. 
I just tried this manually (execute "wget ..." before ./update.sh), it's running. 

```
wget -O - -nv https://raw.githubusercontent.com/mailcow/mailcow-dockerized/master/docker-compose.yml | grep "image:" | awk '{ gsub("image:","", $3); print $2 }' | xargs -L1 docker pull

```

**Comment by andryyy** [comment]
Yes, something like this is good, but it would be even more flexible to "git show" the file from its origin instead of reading the file from a fixed path. Think of forks and such.

**Comment by andryyy** [comment]
Ok, I see other references to the repo in this file, so we don't need to worry about it... 😄 

master should be replaced by the branch var.

**Comment by christianbur** [comment]
Like this?

`wget -O - -nv https://raw.githubusercontent.com/mailcow/mailcow-dockerized/${BRANCH}/docker-compose.yml | grep "image:" | awk '{ gsub("image:","", $3); print $2 }' | xargs -L1 docker pull`

The variable ${BRANCH} contains "master", so it should be correct.

**Comment by andryyy** [comment]
`git show origin/${BRANCH}:docker-compose.yml | grep "image:" | awk '{ gsub("image:","", $3); print $2 }' | xargs -L1 docker pull` is probably more universal.

I am changing the script right now.

**Comment by MaxXor** [comment]
Updating worked fine for me with these changes.

**Comment by DomiStyle** [comment]
Worked fine for me too, downtime is a lot shorter than it was before. Thanks!

**Comment by ntimo** [comment]
I think we can close this then :-)
