### ISSUE TITLE
Improve adding mailbox UI: auto-select domain and default to max quota

### ISSUE THREAD

**Issue by jas8522** [mailcow/mailcow-dockerized#264]
Hey there,

A couple really quick UI adjustments that would be great to have when adding a mailbox:

1. When there's only one domain (when logged in as mailbox admin) it'd be great to have it auto-select that domain in the dropdown box.
2.  Pre-fill the quota field with the max quota for the mailbox

Thanks! I'll see about adding this myself.

-Jordan

**Comment by andryyy** [comment]
Hi,
I just implemented it to dev. :)

**Comment by jas8522** [comment]
Hey, that's great, thanks!
