### ISSUE TITLE
SOGo Vacation Mails: From contains only the mail address

### ISSUE THREAD

**Issue by dominicpratt** [mailcow/mailcow-dockerized#2640]
Hi there,

I just installed mailcow-dockerized and I'm pretty happy with it.

One thing I can't fix is that when I enable a vacation answer on my account and send me a test mail, the From field contains only the mail address, not my Name.

Normal mails contain both: "Dominic Pratt <dominic@example.org>", only Vacation Mails don't contain my Name.

Is there a way to fix this?

Thanks!

**Comment by dominicpratt** [comment]
After some research it should be possible to change the template for "sogo.sieve" from

`if allof ( currentdate :value "le" "date" "2019-05-31" ) { vacation :days 7 :subject "Abwesenheit wegen Urlaub" :addresses ["xxx@example.org"] text:`

to something like

`if allof ( currentdate :value "le" "date" "2019-05-31" ) { vacation :days 7 :subject "Abwesenheit wegen Urlaub" :addresses ["xxx@example.org"] :from "My Name <xxx@example.org>" text:`

Of course "My Name" and the mail address should be filled in automatically. Is there any way to do this? I think this would be useful for other people too...

**Comment by andryyy** [comment]
Hi, this is something for https://sogo.nu/bugs/view_all_bug_page.php :)
