### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by justablob** [mailcow/mailcow-dockerized#2641]
**Describe the bug, try to make it reproducible**
When proxying Mailcow from NGINX on the host, i get a 504 Timeout. It only starts to happen if i set the following IPTables rules on the host: 
```

iptables -A INPUT -s 172.16.0.0/12 -j ACCEPT
iptables -I DOCKER -i ext_if ! -s 127.0.0.1 -j DROP
iptables -I DOCKER  -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I DOCKER -s 172.16.0.0/12 -d 0.0.0.0/0 -j ACCEPT
iptables -I DOCKER -j DROP

```
Those rules are necessary because otherwise all ports from Docker in my other containers will be publicly accessible. When i exec `ping google.com` in mailcow containers, it fails. It only works in the unbound and netfilter containers. All my other containers can ping any outside service. This leads me to believe that it's an issue with unbound-mailcow.

**System information and quick debugging**
I'm running Docker 18.09.6-481bc77 on an Ubuntu 18.04 host
General logs: https://pastebin.com/raw/mdSv8UBN

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?) Ubuntu 18.04 minimal, with apparmor
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.) Docker? It's a dedicated server
 - Your server/VM specifications (Memory, CPU Cores) Intel i7-7700 (4C8T at 4.2GHz), 64GB DDR4, 2x512GB NVMe in RAID0.
 - Don't try to run mailcow on a Synology or QNAP NAS, do you? No
 - Docker and Docker Compose versions: Docker 18.09.6-481bc77, Compose 1.24.0-0aa59064
 - Output of `git diff origin/master`, any other changes to the code? No changes to anything except mailcow.conf
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat ` I got these rules from the official Docker forums and they work in all containers except Mailcow so i don't think it's an issue. See above.
 - Reverse proxy? https://pastebin.com/raw/D3Szt9D0
 - Browser (if it's a Web UI issue) - please clean your browser cache and try again, problem persists? Problem persists
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout? Timeout on first, correct IPs on second.

I'm aware that it's mentioned that custom IPTables rules are not supported, however due to all other containers working it leads me to believe that it's actually an issue with Mailcow. I can not leave these ports exposed. I've grabbed these rules from the official Docker forums so they should be official?

**Comment by andryyy** [comment]
It works fine when Docker handles the rules itself. It is not related to mailcow as we don’t set or change the Docker ruleset. Well, we create a chain for blacklisting. But that’s it. :)

I personally cannot help you with this, but I will leave it open for others to have a look. 

You should post your whole iptables ruleset though.

**Comment by andryyy** [comment]
Please also keep in mind that you need to add many more rules than just the construct found in their docs.

**Comment by justablob** [comment]
It kinda has to be related to Mailcow, because all other containers on the same system work fine. Maybe my iptables configuration interferes with Mailcow, in which case it'd be nice to have someone who knows this stuff better than i do to reply.

**Comment by andryyy** [comment]
If you decide to disable iptables in Docker (I think you did this?) and want to configure them manually, you wil run into a lot of problems, if you are not absolutely aware of what you are doing.

You may want to enable automatic configuration and compare your ruleset. A manual configuration will be hard, as IPs are not fixed in mailcow.

**Comment by justablob** [comment]
No, i haven't disabled Docker iptables. I've just added my own rules as i don't want to expose all my containers to the public.
