### ISSUE TITLE
"Send only" addresses

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2643]
**Is your feature request related to a problem? Please describe.**
I created one alias which just discards mail (foo@xample.com) but I'd like to be able to *send* with that alias as From:. Currently this is not selectable among the aliases in the Web UI.

**Describe the solution you'd like**
Also use "discard" alias as sender.

**Additional context**
Use this to be a "from" for notification mails without wasting space creating a mailbox that won't get used.

**Comment by andryyy** [comment]
I added aliases to the sender_acl system with d5612cf6 and 5087d5ce96a7403792ab4f1bf669522bc04e2240

**Comment by lbeltrame** [comment]
It works if you have myalias@example.com aliased to myrealname@example.com. If you set an alias to silent discard, you can't (as far as I can see) set it to an allowed sender on any mailbox.
Is this intended?

**Comment by andryyy** [comment]
You can select them.

**Comment by mkuron** [comment]
> I created one alias which just discards mail but I'd like to be able to send with that alias

You should still monitor that alias for bounces. Also, silently discarding messages is usually not a good idea because people expect to be able to reply to emails.

**Comment by andryyy** [comment]
@lbeltrame - I just added it a few minutes ago. :) 

@mkuron is right, you should monitor for bounces.

**Comment by lbeltrame** [comment]
Well, the email address I want to use is not really "public". It's used by the notification scripts that collect a few things off the server and a couple other machines and mail it to specific Mailcow recipients. It's only meant to be internal.

Good point on monitoring for bounces, though.

EDI: Whoops, didn't notice the commits flying. ;) I'll update and check.

**Comment by lbeltrame** [comment]
Works as advertised, thanks a lot!

**Comment by ralfbergs** [comment]
I have a very, very similar requirement, but other than the requestor I would like all incoming messages to automatically classified as "spam" (I want to set up a "honeypot" or "spamtrap").

Exactly as the original behavior for silently discarding the message as described in original first comment, I can't select the "spamtrap" alias, even though I have explicitly allowed the mailbox to send mail using the alias as a sender address. I believe the "fix" done for the original issue also needs to be done for my slightly different use case...

Should I create a new issue?
