### ISSUE TITLE
Importing an existing DKIM private key fails with a misleading error if a domain already has a key defined

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2645]
**Describe the bug, try to make it reproducible**
As the subject says, importing a private key for a domain that has an already existing DKIM key defined will trigger an "Invalid DKIM domain or selector" error, which is extremely confusing because it does not reflect reality.

Steps to reproduce:

1. Create a DKIM record in the WebUI for domain example.com, selector "dkim"
2. Import an external private key for the same domain and selector

Actual result:
An error message saying "Invalid DKIM domain or selector"

Expected result:
Either an error telling about the existence of a DKIM record already, or (my expectation) the previous record would get overwritten.

**Comment by petrosmm** [comment]
I can confirm that this issue still exists. Can be reproduced by creating a key with a selector and then attempting a reimport. Upon reimport it will fail no matter what.

**Comment by andryyy** [comment]
I will fix it.

**Comment by andryyy** [comment]
I fixed it.

Will be pushed with the next update, ok? :)

There will be a better error message and a way to overwrite existing keys when running an import.

**Comment by petersmm** [comment]
Worked perfectly, thank you!

**Comment by petrosmm** [comment]
Worked perfectly, thank you!
