### ISSUE TITLE
External ClamAV Setting

### ISSUE THREAD

**Issue by tankerkiller125** [mailcow/mailcow-dockerized#2648]
**Is your feature request related to a problem? Please describe.**
The current ClamAV setup requires that ClamAV be running in a docker container that is setup by the docker-compose command. However some people (such has myself) have a single server that runs ClamAV for RAM and resource reasons for all of our applications.

**Describe the solution you'd like**
I would love to see a config option that allows us to change the RSPAMD ClamAV setting to point to whatever pre-existing network connected Clamd server I have operating.

**Comment by sriccio** [comment]
I did not test it, but I think you can do it already:

Have you tried to:

- Set `SKIP_CLAMD=y` in `mailcow.conf.` (should disable local clamd container)
- Set your clamd server ip or hostname in `data/conf/rspamd/local.d/antivirus.conf`  (should tell rspamd to use it instead of the local one)

**Comment by andryyy** [comment]
Exactly. :)

**Comment by tankerkiller125** [comment]
Could this maybe be better documented someplace for future users. This is very useful information for many people

**Comment by andryyy** [comment]
Go ahead and create a PR to add it to the docs: https://github.com/mailcow/mailcow-dockerized-docs/tree/master/docs
