### ISSUE TITLE
Sogo Alias confusion

### ISSUE THREAD

**Issue by ddeenniiss** [mailcow/mailcow-dockerized#2650]
In Sogo, an email sent on an alias produces a response (by default) from the alias. It's possible to change the From but nobody thinks about it.

So, it generates confusion: alias with the name of the user in the address book and so message send to the alias instead of the person. Is it possible to force the From on the user exclusively ?

**Comment by andryyy** [comment]
That’s something you should ask in our IRC channel or the SOGo devs. 

Check the imap account settings in SOGo. I think you can set a forced “from” value.
