### ISSUE TITLE
More than one SOGo instance possible?

### ISSUE THREAD

**Issue by Sailor1511** [mailcow/mailcow-dockerized#2651]
Hello.

I am really impressed how easy it is to set up mailcow and how well it works. So I am thinking about moving all my domains to mailcow. Since mailcow is dockerized, I was wondering if it is possible to run one instance of mailcow but several instances of SOGo, so that I can use a different domain name and logo for every specific project.

So what I am trying to do would be somethig like:

mailcow 1 -> mail.maildomain.de    ->  mailserver for all domains 
sogo 1  -> webmail.project1.de  ->  groupware for domain project1.de
sogo 2  -> webmail.project2.de  ->  groupware for domain project2.de
...

I would like to ensure, that users would only be able to log in on the correct sogo instance. In my opinion it would be the best to run all the instances one host. However, if that is not possible it would also be an option to run one centralized mailcow and put the sogo instances on another host. 

Marcus

**Comment by andryyy** [comment]
You will need one instance for each customer.

A single KVM node with small Alpine guest systems for each instance would do it. It’s even more isolated.
