### ISSUE TITLE
HowTo whitelist local IP for rspamd

### ISSUE THREAD

**Issue by schoebelh** [mailcow/mailcow-dockerized#2652]
Ich möchte das Backup-Script in einem Cron benutzen, was auch schon gut klappt. Im Anschluss möchte ich mir eine Status-Mail darüber schicken lassen, wofür ich auf dem Host ssmtp nutze und die Mail an die Kuh sende.

Leider wird sie dort immer als Spam abgewiesen, da sie offensichtlich zu meinem Trainigs-SPAM passt:
`BAYES_SPAM (8.499999) [99.99%]
SPOOFED_UNAUTH (5)
MISSING_MID (2.5)
MIME_GOOD (-0.1) [text/plain]
ARC_NA (0)
FROM_NO_DN (0)
TO_MATCH_ENVRCPT_ALL (0)
RCPT_MAILCOW_DOMAIN (0) [xxx.net]
RCVD_COUNT_ZERO (0) [0]
TO_DN_NONE (0)
RCPT_COUNT_ONE (0) [1]
MIME_TRACE (0) [0:+]
FROM_EQ_ENVFROM (0)`

Wie bekomme ich rspamd dazu überredet, für eine IP (hier: 172.22.1.1) KEINE Spam-Prüfung vorzunehmen?

Danke...

**Comment by mkuron** [comment]
Du kannst die IP-Adresse unter Forwarding Hosts eintragen, damit ist sie vom Filter ausgenommen. 

Abgesehen davon kannst du auch den Bayes-Filter trainieren, indem du die Nachricht aus dem Spam-Ordner in den Posteingang schiebst. Außerdem scheint dein Skript keinen Message-ID-Header in die Nachricht zu schreiben.

**Comment by mkuron** [comment]
Und `SPOOFED_UNAUTH` sollte weggehen, wenn du entweder authentifiziert über Port 587/465 sendest oder eine Absenderdomain nimmst, die nicht auch Mailcow-Domain  ist.

**Comment by schoebelh** [comment]
Der aktuell eingesetzte cmdline-Mailer ssmtp scheint keine MSG-ID zu generieren :-(

Den Bayes-Filter kann ich leider nicht trainieren, da ja die Mail gar nicht erst angenommen wird ;-). Zu AUTH schaue ich noch einmal - vielleicht reicht das ja schon...

Der Eintrag bei "Forwarding Host" (IP 172.22.1.1) scheint erstmal nicht hilfreich - die Mail geht trotzdem durch den rspamd. Ich prüf das aber noch einmal.

Danke!
