### ISSUE TITLE
Autodiscovery error

### ISSUE THREAD

**Issue by johann8** [mailcow/mailcow-dockerized#2653]
Hallo,
ich habe einen neuen Mailcow Server installiert. Nun habe ich ein Problem mit Autodiscovery. Es will einfach nicht.
Manuell funktioniert alles. Ich konnte erfolgreich ein Exchange Konto unter MS Outlook 2016-2019, Apple Mail, Android und iPhone erstellen und Mail-, Kalendar-, und Adressbuch-Funktion erfolgreich testen. Bei Outlook habe ich den alten Assistenten verwendet.
Bei Autodiscovery finde ich unter nginx-mailcow Logs:

> nginx-mailcow_1 [27/May/2019:15:14:38 +0200] "GET /autodiscover/autodiscover.json?Email=user1%40reduxxxx.de&Protocol=Autodiscoverv1&RedirectCount=1 HTTP/1.1" 200 103 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; Pro)"
>  nginx-mailcow_1 [27/May/2019:15:14:39 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 401 5 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; Pro)"
>  nginx-mailcow_1   user1@reduxxxx.de [27/May/2019:15:14:58 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 200 702 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; Pro)"
>  nginx-mailcow_1    [27/May/2019:15:14:58 +0200] "GET /autodiscover/autodiscover.xml HTTP/1.1" 401 5 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; Pro)"
>  nginx-mailcow_1  [27/May/2019:15:14:58 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 401 5 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; Pro)"
>  nginx-mailcow_1    user1@reduxxxx.de [27/May/2019:15:14:58 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 200 702 "-" "Microsoft Office/16.0 (Windows NT 10.0; MAPI 16.0.10344; ``Pro)"

Und Outlook informiert, dass angeblich keine verschlusselte Verbindung mit dem Server besteht.

![mailcow](https://user-images.githubusercontent.com/13717874/58425374-f4632280-8099-11e9-9eb1-988c5e2f8d73.png)
Unter mailcow.conf habe ich folgende einstellungen

>  HTTP_PORT=80
> HTTP_BIND=0.0.0.0
> HTTPS_PORT=443
> HTTPS_BIND=0.0.0.0
> ADDITIONAL_SAN=mx01.*,autodiscover.*,autoconfig.*
PS. Sternzeichen verschwindet?

DNS-Einträge

> mx01               IN A       1.2.3.4
> autodiscover        IN CNAME   mx01.reduxxxx.de.
> autoconfig          IN CNAME   mx01.reduxxxx.de.
> @                   IN MX 10   mx01.reduxxxx.de.
> _imap._tcp          IN SRV     0 1 143   mx01.reduxxxx.de.
> _imaps._tcp         IN SRV     0 1 993   mx01.reduxxxx.de.
> _pop3._tcp          IN SRV     0 1 110   mx01.reduxxxx.de.
> _pop3s._tcp         IN SRV     0 1 995   mx01.reduxxxx.de.
> _submission._tcp    IN SRV     0 1 587   mx01.reduxxxx.de.
> _smtps._tcp         IN SRV     0 1 465   mx01.reduxxxx.de.
> _sieve._tcp         IN SRV     0 1 4190  mx01.reduxxxx.de.
> _autodiscover._tcp  IN SRV     0 1 443   mx01.reduxxxx.de.
> _carddavs._tcp      IN SRV     0 1 443   mx01.reduxxxx.de.
> _caldavs._tcp       IN SRV     0 1 443   mx01.reduxxxx.de.

Konfigdatei data/web/inc/vars.local.inc.php habe ich aus Doku übernommen.
Der Aufruf von https://mx01.reduxxxx.de/Microsoft-Server-ActiveSync bringt nur eine leere Seite.
Folgende Ports sind von außen erreichbar:

> PORT     STATE SERVICE
> 25/tcp   open  smtp
> 80/tcp   open  http
> 110/tcp  open  pop3
> 143/tcp  open  imap
> 443/tcp  open  https
> 465/tcp  open  smtps
> 587/tcp  open  submission
> 993/tcp  open  imaps
> 995/tcp  open  pop3s
> 2222/tcp open  EtherNet/IP-1

Der Test mit MS Support and Recovery Assistant besteht alle Schritte außer letzten:
 

> A 401 error was received from the server, but no authentication methods are supported.
> HTTP Response Headers:
> Connection: keep-alive
> X-Frame-Options: SAMEORIGIN
> Content-Length: 0
> Content-Type: text/plain; charset=utf-8
> Date: Mon, 27 May 2019 14:44:29 GMT
> Server: nginx
> WWW-Authenticate: basic realm="SOGo"
> Elapsed Time: 601 ms.

 
Was habe ich übersehen? 
Vielen Dank

**Comment by ticevi** [comment]
SSL wird für autoconfig nicht unterstützt. siehe #2624

**Comment by johann8** [comment]
Besten Dank für den Hinweis!
Ich habe versucht die Lösung aus der Doku "Redirect HTTP to HTTPS", hat leider nichts außer Warnungen im Log gebracht. Outlook 2016-2019 wollen einfach kein Autoconfig unter W2k10 machen. Erstaunlicherweise funktioniert das mit Windows Mail Client einwandfrei.
