### ISSUE TITLE
php-fpm not started

### ISSUE THREAD

**Issue by philippnied** [mailcow/mailcow-dockerized#2656]
Helllo,

after installing one of the latest updates, I have the strange problem that php-fpm is not running. When visiting admin-page I'm getting this error:
`2019/05/29 08:18:09 [error] 18#18: *3625 connect() failed (111: Connection refused) while connecting to upstream, client: XX, server: XXX, request: "GET / HTTP/1.0", upstream: "fastcgi://[XXXX]:9002", host: "XXX"`

Executing
`docker exec -it -u root $(docker ps -f name=php-fpm-mailcow -q) bash -c "php-fpm"
`will start php-fpm and everything works fine. But this should not be the solution :-)

Any suggestions?

**Comment by andryyy** [comment]
Issue template missing, no logs. Cannot help.

php-fpm-mailcow logs would be useful. Also run "ps aux | grep -i php" when it hangs. It may just be busy upgrading the SQL structure.
