### ISSUE TITLE
Expunge all emails from quarantine older than X

### ISSUE THREAD

**Issue by webNpro** [mailcow/mailcow-dockerized#2657]
Is it possible to expunge all emails from quarantine older than X days with cron?

**Comment by andryyy** [comment]
```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DELETE FROM quarantine WHERE created < NOW() - INTERVAL 123 DAY"
```

Not written for cron, just an example.

I added this functionality right now :)

![image](https://user-images.githubusercontent.com/2972950/58752684-9e381a00-84b3-11e9-810c-5dedd6ef0faa.png)

**Comment by webNpro** [comment]
Hi André, I try to change the maximum age value but the mailcow doesn't save the changes...

**Comment by andryyy** [comment]
When did you update?

**Comment by webNpro** [comment]
15 minutes ago :-)

**Comment by andryyy** [comment]
I tested on two systems and can change the value on both, so I don't know. I don't see what could be wrong. I also don't know what "cannot change" means. No error? Error? What do you try to set it to? 

I also don't know how you update. If you do it manually, you might be missing some code.

**Comment by webNpro** [comment]
I made the update with the update.sh script. I try to change the max age value to 30 days and press the save changes button. No error and nothing changed. After page reload the max age value is 365 days again. I'll make the update once more.

**Comment by webNpro** [comment]
It's ok now. I just run the update.sh again. Thanks for your quick answer and help!

**Comment by andryyy** [comment]
Strange. :) It works now?

**Comment by webNpro** [comment]
:-) It works. Thanks again!
