### ISSUE TITLE
IMAPsync mark as seen - fetch only new

### ISSUE THREAD

**Issue by sut12** [mailcow/mailcow-dockerized#2661]
Hey,
is there any way to tell imapsync to fetch only  new messages? I would like to:

1: Fetch message from source (dont delete in source)
2: mark message as seen in source 

When i delete the message in the target system it gets fetched again with the next sync. Setting the sync time higher and the days to fetch lower is also no option for me since i want to sync every 2 minutes.

**Comment by Braintelligence** [comment]
Not 100% sure but maybe you can solve your issue about read/unread flags by using 

`--noresyncflags` as per the documentation from https://imapsync.lamiral.info/README :
```
Do not resync flags for already transferred messages.
May be useful when a user has already started to play
with its host2 account.
```

You can put this in custom parameters for your imapsync in the mailcow GUI.

**Comment by sut12** [comment]
Already tried that. It doesnt work. If i delete meesage on target it will be resynched from source.
