### ISSUE TITLE
Want to have reading panel below the unread panel...

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#2662]
My request is not related to any problem (so far).

I would like to be able to put the unread panel above the reading panel horizontally.

**Comment by andryyy** [comment]
Hm, you probably want to create a feature request with SOGo. :)

Perhaps this can be accomplished with some JavaScript injection.

**Comment by infracritical** [comment]
Um...so riddle me this then.  How can I do this on an active docker-composed container?

I've tried several times to make changes to change the reading panel from right...to bottom (below) the mail listed items.  So far, nothing.

MailCow development team has removed the abilities of making changes on an active docker-composed container; personally, I think that this has hindered some of the features.

**Comment by andryyy** [comment]
What did we remove?

You know we don’t maintain SOGo, right? :) That’s the fantastic @inverse-inc team. 

Create a PR in their repository. Or ask them to build it (be prepared that they won’t work for free). 

I don’t know if you can do it with plain JavaScript. It was just an idea. You can override template files iirc, too. That’s probably the way to go.

**Comment by infracritical** [comment]
Drat...and double drat.  OK, guess I need to approach them on this request then...

**Comment by infracritical** [comment]
FYI - have tried several times to get someone to take notice. But alas, no such luck.  :(
