### ISSUE TITLE
Anonymize Headers not working

### ISSUE THREAD

**Issue by Rattenschwanz** [mailcow/mailcow-dockerized#2663]
Unfortunately the anonymization of the header still doesn't work for me. I haven't changed anything and it's the current version. Ports 465 and 587 are also used to send mails. I have adopted the default settings, which roughly match those here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-anonym_headers/

**Comment by andryyy** [comment]
I just (edit: successfully) checked with port 587:

```
Return-Path: <andre@develcow.de>
Delivered-To: andre.peters@servercow.de
Received: from hosted-1.mailcow.de
	by hosted-1.mailcow.de with LMTP
	id APeuLP6G8VwyPgAAUwpk6w
	(envelope-from <andre@develcow.de>)
	for <andre.peters@servercow.de>; Fri, 31 May 2019 21:56:46 +0200
Received: from mx.mailcow.email (mx.mailcow.email [IPv6:2a00:f820:417:0:80:77:26:247])
	by hosted-1.mailcow.de (Postfix) with ESMTPS id A75BF5C117B
	for <info@servercow.de>; Fri, 31 May 2019 21:56:46 +0200 (CEST)
Received: from localhost (localhost [127.0.0.1])
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=develcow.de; s=dkim;
	t=1559332606;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding;
	bh=sFU3zNRWy6oc5QXqgLeMDEy6eBUrcuLSmtjgDBV05ho=;
	b=5TUQDnTdz0fpLgTyU+ShjKi5YaG7jMJRgcD8rZoKNkyNLp1h1vaH9OWTxd1msOTtP2vWxA
	qFF7vrEWK/jrLaisgUW3VyC4tbBqbUYhJAK78YZKqOHKRZsqNLe+gsWjEXeY8NDUv+kXQ1
	B+cKkzAW1pbsWzYyUC958khf8uenLs7VS9n+RBNva8vInndm9YLU8rDSqYABg/YuKefyMF
	fbl9yRPTvYk8f4bf6eYnPUhOOEVvzC8CasCa9psXeSk0G2rTE9AsKCw/11xjgv4I4pQffy
	xDBvsS3xORg5NC/pyU9h7B9g5s/8XM6nfo+sl8/9jzXNNwGZYqUr4lNAAZwhMA==
To: info@servercow.de
From: Andre <andre@develcow.de>
Subject: Testmail123
Message-ID: <af5d07a2-6a01-31c5-3700-0138a5362e5f@develcow.de>
Date: Fri, 31 May 2019 21:56:44 +0200
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=develcow.de;
	s=dkim; t=1559332606;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding;
	bh=sFU3zNRWy6oc5QXqgLeMDEy6eBUrcuLSmtjgDBV05ho=;
	b=o4R9oJCSFeX0HAGRoL2cg37yczjUYDS9F3fE8ofOVdi0lVRI2+89whUjLqgfmxbqvaxs3m
	s4mLAo/4M7NzjM+AatOKH/okr39xdQ4SMxl6ITlkMXHu6GsX7rbp8rfWT19kh1huNtG0Dr
	4j7Ef9khMtFPItLIp4WpUHiGghWpfbsLJ0zmZ2GVbIjxBrNFp7qpqBR8hMTxF1vpy//8Sj
	/BI+O3v24QV+LugBJ1m8ry6BlFeLiGbXNxzBiVWwRKYyTY864Alikd5u4YoaNhjw3WzQrT
	pebPwmoLAUDLJ/poeyaUWiz/YnPZk8Tdd8i1e/8C+MV4Y1TdGewMt6XDa/zF9Q==
ARC-Seal: i=1; s=dkim; d=develcow.de; t=1559332606; a=rsa-sha256; cv=none;
	b=vXdBdUG9EuJNSIyVS7m+xXvqkRRbpe3k2yFOwSr4l87A0izUmL7KT2JJ2IFnLefr0sZZ6+
	ZdxZHNi5N1PD7YfYBa5hRl2ygySK7ee7dAu8mnQ742KNZG1aGPSOZWiJRj9jOGczdMAfQ5
	jvoF5GOcMytJ9TcJ1U0/eRmqA/NYToxCet5iml2B2NVhEk75/P4VyaTs/RArLR8iLSXQNu
	SzCnvuV95npj/5m6dbpwfH/2KwXWlgRWq84oauDW11xO0h+pxt0WZ79koX/tqJ/ac5CQdk
	xw6uU+v1SJCtGk40Clyj6TKrYb4XCWT7vdC04voDdvrubw5oy4vFi4Z+o7bgvg==
ARC-Authentication-Results: i=1;
	mx.mailcow.email;
	auth=pass smtp.mailfrom=andre@develcow.de
Authentication-Results: hosted-1.mailcow.de;
	none
X-Spamd-Result: default: False [0.00 / 19.00];
	 PREFILTER_WHITELIST(0.00)[info@servercow.de]
X-Rspamd-Queue-Id: A75BF5C117B
```

You cannot remove the mail servers IP, that's not possible. The receiving server adds those headers. It will always know and see your IP by design (obviously) :).

**Comment by Rattenschwanz** [comment]
The anonymization of IP addresses works: 
`Received: from localhost (localhost [127.0.0.1])`

On my setup is adding the user string:
`(Authenticated sender: local@domain.tld)`

And the string "Postcow":
`by mailcow.domain.tld (Postcow) with ESMTPSA id 12BFB4228B
for <local@domain2.tld>; Fri, 31 May 2019 22:31:12 +0200 (CEST)`

Do you have the same main.cf config as the regular Mailcow installation?

Unfortunately not other parameters, like the Mail Agent: 
```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101
 Thunderbird/60.7.0
```
This is always sent along. Both port 465 or 587. What can I do? 
Which mail client do you use? Is there add an mail client string?

**Comment by andryyy** [comment]
I have tested on an unmodified default installation. The header checks are unchanged.

Please search the other issues. We decided not to remove the UA header as it might be signed by other MTAs, which then breaks ARC.

**Comment by Rattenschwanz** [comment]
1. Why is no User Agent displayed in your example?
2. Just isn't the user agent or all other parameters like X-Mailer X-Originating IP removed? 
3. Why did you comment out the User Agent in the anonymize_headers. pcre first today and removed the page in mailcow.github.io? 
4. How can I still remove the User Agent, even if there may be problems with the signature?

**Comment by andryyy** [comment]
1. It was not set
2. https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/anonymize_headers.pcre#L5-L8
3. I removed the page, because it was a ghost page without reference (the link was removed). The checks are enabled by default, the docs were obsolete (wrong file, wrong replacements etc).
4. I added the UA stuff to the file today, so you can simply uncomment the line to remove them. If you changed your main.cf and/or the header_checks, you need to revert these changes.
