### ISSUE TITLE
Cross-domain sharing in SoGO

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2665]
**Is your feature request related to a problem? Please describe.**
In the default configuration, SoGO does not allow to share mailboxes or calendars outside the domain the account is for. However, this may be desirable in some circumstances.

**Describe the solution you'd like**
Ability to share a calendar for user2@example1.com from user1@example1.com.

**Comment by lbeltrame** [comment]
I guess this needs changing in the `SOGoDomainVisibility` option, but I can't tell if this would get overwritten by updates.

**Comment by andryyy** [comment]
You can use the parameter you already found. It will not be overwritten. Perhaps - in the future - we will make this configurable via UI.

**Comment by lbeltrame** [comment]
That's good enough for me. Thanks a bunch for the pointer.

**Comment by dragoangel** [comment]
To info [bug]: `SOGoDomainVisibility` working in SOGo Web Client even it shows 404 on requests to another visible domains, but at CardDAV and EAS: GAL will not display emails from any other domain. I have open bug at SOGo https://sogo.nu/bugs/view.php?id=4896 but it not clear is this on mailcow side or on SOGo.

**Comment by dragoangel** [comment]
After discussion with SOGo looks like to have working GAL cross domain sharing SQL SOGo static view must be reworked to have dedicated static view per domain and sogo.plist must be changed as well. Now in mailcow this view return users for all domains.

**Comment by andryyy** [comment]
They said it might be the problem. They did not say it is the problem.

Do you plan to work on it?

**Comment by dragoangel** [comment]
I can try to test this, but I can't break my prod setup, need install some test VM.

**Comment by vermium** [comment]
@DerLinkman I think there is support for this inside of SoGo, not sure tho

**Comment by dragoangel** [comment]
It can be closed
