### ISSUE TITLE
SYSCTL_IPV6_DISABLED

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#2666]
When disabling IPv6 using `SYSCTL_IPV6_DISABLED`, the update script says

```
SYSCTL_IPV6_DISABLED was removed due to complications. IPv6 can be disabled by editing "docker-compose.yml" and setting "enabled_ipv6: true" to "enabled_ipv6: false".
This setting will only be active after a complete shutdown of mailcow by running "docker-compose down" followed by "docker-compose up -d".
```

Even the [docs](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-disable_ipv6/) are telling this.

However, `enabled_ipv6` doesn't exist (anymore) in the docker-compose.yml file.

What's the current, preferred way to disable IPv6?

**Comment by andryyy** [comment]
Hm? https://github.com/mailcow/mailcow-dockerized/blob/af46a93e768c889032c80f4cd14d2c8421d4d5c2/docker-compose.yml#L462

**Comment by SoftCreatR** [comment]
Okay, looks like I have an older version of that file. Doesn't the update script update it?

**Comment by andryyy** [comment]
It should. But you can try to run "git pull" to make sure it pulls all changes. This can result in some conflicts you may need to solve afterwards.

**Comment by SoftCreatR** [comment]
I see, where the problem is. It's in the warning message, that speaks of `enabled_ipv6` instead of `enable_ipv6` :)

**Comment by andryyy** [comment]
Oops. :) thanks
