### ISSUE TITLE
Netfilter Python error

### ISSUE THREAD

**Issue by bonanza123** [mailcow/mailcow-dockerized#2668]
**Describe the bug, try to make it reproducible**
netfilter keeps restarting

**System information and quick debugging**
```
# docker-compose logs -f --tail=100 netfilter-mailcow                                :(
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_netfilter-mailcow_1
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 1350, in _set_rule
netfilter-mailcow_1  |     m = Match(self, match=match)
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 547, in __init__
netfilter-mailcow_1  |     raise XTablesError("can't find match %s" % (name))
netfilter-mailcow_1  | iptc.errors.XTablesError: can't find match geoip
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 507, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 272, in clear
netfilter-mailcow_1  |     for rule in input_chain.rules:
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 1505, in _get_rules
netfilter-mailcow_1  |     return [self.table.create_rule(e, self) for e in entries]
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 1505, in <listcomp>
netfilter-mailcow_1  |     return [self.table.create_rule(e, self) for e in entries]
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 1821, in create_rule
netfilter-mailcow_1  |     return Rule(entry, chain)
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 954, in __init__
netfilter-mailcow_1  |     self.rule = entry
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 1350, in _set_rule
netfilter-mailcow_1  |     m = Match(self, match=match)
netfilter-mailcow_1  |   File "/usr/lib/python3.6/site-packages/iptc/ip4tc.py", line 547, in __init__
netfilter-mailcow_1  |     raise XTablesError("can't find match %s" % (name))
netfilter-mailcow_1  | iptc.errors.XTablesError: can't find match geoip
```

Further information (where applicable):
 - Debian 9
 - Docker
 - Root server with 16GB RAM and 4 cores
 - `Docker version 18.09.5, build e8ff056dbc` 
- `docker-compose version 1.24.0, build 0aa59064`
 - ```
git diff origin/master
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index b0fda8bb..cec59257 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -6,11 +6,11 @@ smtpd_use_tls=yes
 smtpd_tls_received_header = yes
 smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
 smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
-smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
+smtpd_relay_restrictions =  permit_sasl_authenticated defer_unauth_destination permit_mynetworks
 alias_maps = hash:/etc/aliases
 alias_database = hash:/etc/aliases
 relayhost =
-mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 [fe80::]/10 [fc00::]/7
+mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.23.0.0/16 192.168.0.0/16 [fe80::]/10 [fc00::]/7
 mailbox_size_limit = 0
 recipient_delimiter = +
 inet_interfaces = all
diff --git a/data/conf/rspamd/local.d/greylist.conf b/data/conf/rspamd/local.d/greylist.conf
index ee0220d7..5f697126 100644
--- a/data/conf/rspamd/local.d/greylist.conf
+++ b/data/conf/rspamd/local.d/greylist.conf
@@ -1 +1,2 @@
+enabled = false;
 whitelisted_ip = "http://nginx:8081/forwardinghosts.php";
diff --git a/data/conf/rspamd/local.d/milter_headers.conf b/data/conf/rspamd/local.d/milter_headers.conf
index d8d40258..8528c947 100644
--- a/data/conf/rspamd/local.d/milter_headers.conf
+++ b/data/conf/rspamd/local.d/milter_headers.conf
@@ -1,3 +1,4 @@
+extended_spam_headers = true;
 use = ["spam-header", "x-spamd-result", "x-rspamd-queue-id", "authentication-results"];
 skip_local = false;
 skip_authenticated = true;
```
 - Reverse proxy? Yes, nginx

**Comment by bonanza123** [comment]
Maybe related: https://github.com/ldx/python-iptables/issues/164

**Comment by marcvorwerk** [comment]
Found a solution and opend a PR: https://github.com/mailcow/mailcow-dockerized/pull/4426
