### ISSUE TITLE
Dovecot imap(nick@domain.ltd)<24166><>: Fatal: block_alloc(268435456): Out of memory

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#2669]
Hallo erst mal.
Mir ist vor ein paar wochen mein MAil prog. abgeschmirt und hat alle lokalen mails gelöscht, nach dem ich Opera Mail neu eingerichtet hatte, wird meine IMAP SSL Verbindung zu meinem Web server immer beendet.
Im Log vom Dovecot  steht immer diese 2 meldungen:
1.
 imap(nick@domain.ltd)<24166><>: Fatal: block_alloc(268435456): Out of memory
2.
imap(nick@domain.ltd)<24166><LTrk2liKb6EqAoBxAbJpAAAv5cd3voAa>: Error: Raw backtrace: /usr/local/lib/dovecot/libdovecot.so.0(+0xd7e21) [0x7ff35a807e21] -> /usr/local/lib/dovecot/libdovecot.so.0(+0xd7ec1) [0x7ff35a807ec1] -> /usr/local/lib/dovecot/libdovecot.so.0(i_error+0) [0x7ff35a76b550] -> /usr/local/lib/dovecot/libdovecot.so.0(+0xfac94) [0x7ff35a82ac94] -> /usr/local/lib/dovecot/libdovecot.so.0(+0xfaccb) [0x7ff35a82accb] -> /usr/local/lib/dovecot/libdovecot.so.0(p_strdup+0x42) [0x7ff35a83e742] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(maildir_uidlist_sync_next_uid+0x3f3) [0x7ff35ab3ec53] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(maildir_uidlist_sync_next+0x20) [0x7ff35ab3ee80] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(+0x7d257) [0x7ff35ab3c257] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(+0x7df38) [0x7ff35ab3cf38] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(+0x7e387) [0x7ff35ab3d387] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(maildir_storage_sync_force+0x39) [0x7ff35ab3d479] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(maildir_file_do+0xb1) [0x7ff35ab42221] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(+0x77b84) [0x7ff35ab36b84] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(mail_get_stream_because+0x70) [0x7ff35aafdae0] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(index_mail_prefetch+0x8e) [0x7ff35ab84b4e] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(mail_prefetch+0x3a) [0x7ff35aafd25a] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(+0xccd79) [0x7ff35ab8bd79] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(index_storage_search_next_nonblock+0x11c) [0x7ff35ab8c23c] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(mailbox_search_next_nonblock+0x2e) [0x7ff35ab0c4ae] -> /usr/local/lib/dovecot/libdovecot-storage.so.0(mailbox_search_next+0x3d) [0x7ff35ab0c51d] -> dovecot/imap(+0x1f5b4) [0x55f94358a5b4] -> dovecot/imap(imap_fetch_more+0x39) [0x55f94358b819] -> dovecot/imap(cmd_fetch+0x342) [0x55f94357bda2] -> dovecot/imap(command_exec+0x7c) [0x55f94358878c] -> dovecot/imap(+0x1b832) [0x55f943586832] -> dovecot/imap(+0x1b8c4) [0x55f9435868c4] -> dovecot/imap(client_handle_input+0x1a5) [0x55f943586ce5]

Was muss ich an meiner MAilcow innstallation ändern, das der fehler nicht mehr auftritt?
GRuss Conan

**Comment by ntimo** [comment]
Hallo, 
Wie viel RAM hat den dein server? Es scheint so als würde Dovecot in einen out of Memory laufen.

**Comment by Conan179** [comment]
Die VM ist eingestellt auf 6.5gb
free sagt:
                                         Gesamt        belegt           frei         gemns. Puffer/Cache verfügbar
Speicher                     :     6619916     2192956     2614332       11164     1812628     4131192
Auslagerungsspeicher:     8388604      618148     7770456

**Comment by andryyy** [comment]
Hast du Millionen von Mails?

Jedenfalls - data/conf/dovecot/dovecot.conf:
```
service imap {
  executable = imap imap-postlogin
  user = vmail
  vsz_limit = 1G <- den da, vllt. mal auf 2G
}
```

**Comment by Conan179** [comment]
Da ich mailcow als so eine art log server (fail2ban,logwatch) von insgesamt 5 vms, der Root Server steht bei Hetzner und es wird ständig versucht per ssh sich drauf inzuloggen um ihn als spammer, bot zu missbrauchen. als  ja momentan so um die 1mil mails. Ich lade mir aber nur die Kopfzeilen runter.
