### ISSUE TITLE
How to add commercial SSL/TLS certificates?

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#2673]
Will using using the technique here, https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#use-own-certificates, work for both the SOGo *and* the administrative portion of the domain?

The reason why I ask is this -- while attempting to use SOGo, it already has a self-signed certificate registered as 'mailcow'; however, while attempting to use the administrative portal, it shows no encryption.

If I utilize the techniques as outlined from the FAQ URL listed above, will this apply to both functions?

Any help is always useful.  TIA.

P.S.  I just *love* this distribution!!!  It's clean, fairly fast, and does decent processing of emails in a relatively short period of time.  Keep it up!!!

**Comment by infracritical** [comment]
Just an FYI, I did RTFM with the online documentation.  Seeing that I suddenly had errors from all sorts of places once the 'docker-compose up -d' was implemented.  I used the bundled CA for intermediate and root, and used the private key as well.  Nope.  Nothing worked.

I am using a commercially-available SSL certificate.

**Comment by MAGICCC** [comment]
Normally you just place your own SSL cert in `data/assets/ssl/` and restart the whole stack as said in the docs.
Can you say in which order you concentrate your cert.pem?

**Comment by infracritical** [comment]
OK...I am confused.  There is a web server certificate, and an intermediate certificate.  I had an original CSR file generated last year when the SSL certificates were generated.  I just was acknowledged, using the same CSR for new certificates.

In the //data/assets/ssl directory, there are several files: ca.pem, cert.pem, key.pem.

Which is what, and how do I implement the two certificates that I got from my SSL certificate provider?

**Comment by infracritical** [comment]
Also, do I keep key.pem alone, or do I use one of the 2 certificates for that?

**Comment by infracritical** [comment]
This whole process is very confusing to me.

**Comment by andryyy** [comment]
They usually give you a combined certificate and the private key. The combined certificate is cert.pem. CA can be ignored, you don’t need it. Key is, well, key.pem.

**Comment by infracritical** [comment]
They emailed me only the web certificate and the intermediate certificate.  I combined both - in that order - to create a single-filed .pem file called 'cert.pem'.  The 'key.pem' file was taken from the server certificate file that was part of the downloaded bundle; however, the ZIP file containing the web/intermediate certificates is different from the emailed web/intermediate certificates.

**Comment by infracritical** [comment]
OK...after several lengthy telephone calls, I've finally managed to get it working.  I will post a separate suite of instructions for the SSL certificate vendor that I've used as a job-aid for everyone.  OR....would you rather that I send you an email, and you could include this as part of your FAQ?

**Comment by MAGICCC** [comment]
You can always create a PR for the docs

**Comment by infracritical** [comment]
I have had to renew my certificate, and went through the painful process all over again.  To make matters worse, I *thought* that I had taken notes - apparently not.

They had me create a 2K key for 'server.csr' and 'server.key'.  Obviously the CSR file is what's used to generate the key.  I am suspecting that 'server.key' is the 'key.pem' - the private key - so I dup'd the file and copied 'server.key' to 'key.pem'.

They sent me a zip file.  Within it, it shows 3 files:

* the certificate authority CA file
* my certificate domain file
* the certificate trusted root file

If I use their online application, the only thing that I can do to match hashes with the private key (assuming 'key.pem') is my certificate domain file.  I can start and stop the docker instance with no issues.

However...upon going to the web browser (Firefox), it pukes with the HSTS exchange.

What am I doing wrong...again???

**Comment by infracritical** [comment]
ADDENDUM - it works with Chrome and Brave, just not Firefox.

**Comment by infracritical** [comment]
I've got it working!!!

Here's what I've done...

I use DigiCert, and go through a reseller called 'The SSL Store'.

- Login and go to your directory **/opt/mailcow-dockerized/data/assets/ssl**.
- Backup your existing keys (.pem, .crt, .csr files).
- Type "**openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr**"
- Type "**cp server.key key.pem**".
- Backup "server.key", "server.csr", and "key.pem". Mailcow uses "key.pem" (as outlined within nginx conf)
- Acquire your keys by providing the CA your CSR file (usually cut 'n paste works OK).
- They will need to validate your CSR before issuing your new key bundle.
- I chose HTTPS file validation; this would be "**_https:<your_domain>/.well_known/pki-validation/<filename>_**"
- For me, my validation filename is "fileauth.txt"; this will vary for each SSL cert provider.
- Once validated, they usually will send you a ZIP file via email to your account's email address.
- Download the ZIP file, and unpack its contents.

When the ZIP is unpacked, it should contain something like this:
- CA Bundle.txt
- [your_domain]-[unique_ID]DigiCertCA.txt
- [your_domain]-[unique_ID][your_domain].txt
- [your_domain]-[unique_ID]TrustedRoot.txt

The SSL cert provider will recommend using the CA bundle.  DO NOT use the bundle.  Most SSL cert providers only have 2 certs inside - the DigiCertCA and the TrustedRoot certs; essentially, the intermediate CA key, and the trusted root CA key.

To work with browsers wanting HSTS, you will need the following in this order:

- [your_domain] cert
- [DigiCert CA] cert
- [TrustedRoot CA] cert

Copy the certificates with "--- BEGIN CERTIFICATE ---" all the way down to "--- END CERTIFICATE ---".  No spaces.  Concat the keys one at a time into a file called "cert.pem".

That means you'd type "**cat [your_domain cert] [intermediate cert] [root cert] >> cert.pem**".

- Go back to your 'root' directory to restart Mailcow; type "**cd /opt/mailcow-dockerized**".
- Type "**docker-compose down**".
- Once down, type "**docker-compose up -d**".
- Check out your domain running against an SSL checker tool.

There are several online.  I am preferential to the Qualys one - (https://www.ssllabs.com/ssltest/).
HINT: If you're paranoid (like me), click on the checkbox before running your check; Qualys won't add your results to their ever-increasing database.

Do know that I've fought with this for several hours before realizing that there are specific steps that must be taken - in order - to accomplish your goal of using an external, legitimate SSL CA certificate provider.

Hope this helps...  ;)

-rad

**Comment by infracritical** [comment]
If there is interest, I plan on writing a step-by-step document for applying this technique for utilizing exterior SSL certificate providers.  Although I am doing this (mostly) for helping me remember how to do this again at renewal time, I think it would benefit the Mailcow community with this as well.  To those who moderate this repository, is there a location for end-user contributions?  And if so, what format should the document be using?

**Comment by andryyy** [comment]
Hi,

This is not a place for support. :)

We already describe how to add/replace the certificate/key pair in the docs. 

What you need to figure out yourself obviously: What is a cert, what is an intermediate, what is a key, how to order a certificate chain, how to validate a certificate in the process of ordering it (domain validated, dns validated). That's all absolutely not mailcow. We also don't provide guides how to assemble a server or install Debian. That's all happening besides mailcow. :)
