### ISSUE TITLE
Failed to authenticate on SMTP server using 2 possible authenticators 

### ISSUE THREAD

**Issue by Gittified** [mailcow/mailcow-dockerized#2674]
Hey,

I've just got a short question since I don't quite know how it works yet. So I've just finished installing everything and I connected my SMTP, in the first place it could not make connection but I used the wrong port. After I typed the correct port it worked but:

Swift_TransportException: Email to mail@example.com failed: Failed to authenticate on SMTP server with username "mail" using 2 possible authenticators 

I got this error on my XenForo site.
I think I just made a stupid mistake in configurating it in Mailcow.

**Comment by MAGICCC** [comment]
Try your email as username

**Comment by Gittified** [comment]
Thanks, it works now!
