### ISSUE TITLE
Errr...what happened with this?

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#2675]
Tried to access this URL from within the administrative portal:

![image](https://user-images.githubusercontent.com/11613524/58817475-6fc05900-85f1-11e9-8033-9299bf746401.png)

Got an error message for this URL:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/sieve_after

![image](https://user-images.githubusercontent.com/11613524/58817548-8f578180-85f1-11e9-87fe-e926d8109a38.png)

**Comment by MAGICCC** [comment]
Ah it got renamed in https://github.com/mailcow/mailcow-dockerized/commit/dcacf85a5d8bff7aee20147c4cccfc11d3757a76
If you want you can create a PR

**Comment by infracritical** [comment]
Um...forgive me for saying this, but I've never done a pull request before.  Never really had too, either.

**Comment by MAGICCC** [comment]
Ah nvm, its in https://github.com/mailcow/mailcow-dockerized/commit/5f8dd69a2d695746af9ac6379a98f86c1865c7d0 
Just update your installation

**Comment by infracritical** [comment]
OK.  Sorry for the 'noob' questions...

**Comment by andryyy** [comment]
There are no noob questions. :)

**Comment by infracritical** [comment]
I am going to investigate the notion of getting support to help me through this.  Is there an English version of the servercow.de?

Mein Deutsch ist nicht so gut und es ist Jahre her, seit ich es das letzte Mal gesprochen oder geschrieben habe. Dies wurde mit Google übersetzt. Ich entschuldige mich für die schreckliche Übersetzung. Jede Hilfe wird sehr geschätzt. Vielen Dank.

**Comment by andryyy** [comment]
The order form is still German, sorry. You can write us in English any time. You’d only need to go through the order process with a translator etc. - this needs to be changed in the future indeed.
