### ISSUE TITLE
Invalid password for autodiscover and iOS

### ISSUE THREAD

**Issue by rockhouse** [mailcow/mailcow-dockerized#2677]
Maybe I should start by saying that I already chatted with DeLord & gummipunkt on IRC to see if I missed something or did some obvious mistake. 

I get the following error message in the logs when I try to add an Exchange account on iOS via autodiscover:
`FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for xxx@xxxxx.ltd by xx.xx.xx.xx" while reading response header from upstream, client: yy.yy.yy.yy, server: mail.xxxxxxx.com, request: "GET /Autodiscover/Autodiscover.xml HTTP/1.0", upstream: "fastcgi://172.22.1.11:9002", host: "autodiscover.xxxx.ltd"`

I did a password reset just to be sure and set the password to '123456'. To make sure that this is actually what the PHP server receives, DeLord helped me with outputting the username and password to the logs by adding this statement:
`error_log('CHECK VARIABLES: username: ' . var_export($login_user, true) . ', password: ' . var_export($login_pass, true));
`here:
[autodiscover.php](https://github.com/mailcow/mailcow-dockerized/blob/797e97d61988ec72bfc4d364f0b5523852e96287/data/web/autodiscover.php#L56)
As expected the username and password were correct. 

I also tried not just resetting the account password but setting the option to ask the user to change passwords at next login. The DNS checks have all a green checkmarks (ignoring TLSA). Accessing the account via IMAP works! Restarted also all services just to be sure and I am running the latest release too (commit 797e97d). The mailbox was also removed and recreated just to be sure. 

If I open the browser at https://mail.XXX/Autodiscover/Autodiscover.xml I get an XML with `<ErrorCode>600</ErrorCode>` which is correct according to DeLord as I am not sending enough data for a correct request. When filling in wrong data it gives me no response at all (as expected). 

Anyone else any idea how to fix this? Thanks

**Comment by rockhouse** [comment]
ping

**Comment by andryyy** [comment]
Clients mostly try to connect without basic auth first. They fail and try with auth again. That's probably what you see here.

**Comment by rockhouse** [comment]
thanks @andryyy I indeed see two login attempts but both fail! so the problem still is there
