### ISSUE TITLE
Disappearing Text

### ISSUE THREAD

**Issue by mbh-dev** [mailcow/mailcow-dockerized#2679]
Hi all,
When composing an email within SOGo, text disappears within the address field, so fit example, when typing an email address to send to, then pressing enter or tab, the address typed disappears, the same happens when typing the body of the email, can anyone shed any light on this?

Thanks

**Comment by Braintelligence** [comment]
Can't reproduce this. Please provide more details as pointed out in the issue template. Provide also your OS and browser and so on.

**Comment by andryyy** [comment]
Probably a browser issue. Or magic.
