### ISSUE TITLE
Quarantine not working

### ISSUE THREAD

**Issue by darthdule** [mailcow/mailcow-dockerized#2680]
Hi, 

I have trouble with the quarantine feature. I have two VPS, each of them running mailcow on a ubuntu system. Both servers use nginx as a reverse proxy. ServerB functions as MX server to serverA. Everything works fine for the past 6 months or so. Now I wanted to check out rspamd and noticed that there is a quarantine feature. After setting the retention and size, I used emailsecuritycheck.net to delive some spam to a mailbox on ServerA. It gots rejected from rspamd but the quarantine field in mailcow is empty. Also, hourly delivery of a quarantine mail does not work. So I tested on serverB and it does not work either. So I updated both systems and mailcow container with update.sh script. So far so good but quarantine still does not work.
I tried to send a system mail to my mail domain. It worked. No problems with mail reception ot delivery so far.
Any ideas?

I will post a log wirh greped "quarantine". I can provide further logs if you need.
`

root@cencan:/opt/mailcow-dockerized# docker-compose logs |grep quarantine
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:05:16 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:05:28 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:05:35 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:06:36 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:11:58 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:11:59 +0200 "GET /quarantine.php" 200
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:16 +0200] "GET /quarantine HTTP/1.0" 200 683848 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:16 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:28 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:28 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:35 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:05:35 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:06:36 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:06:36 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:16:21 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:18:52 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:18:53 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:21:02 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:22:17 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:22:48 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:22:50 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:23:10 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:23:27 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:23:28 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:23:45 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:24:42 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:13:24:50 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:25:00 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:25:17 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:26:33 +0200 "GET /quarantine.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:13:31:15 +0200 "GET /quarantine.php" 200
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:11:58 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:11:58 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:11:59 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:11:59 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:02:46 +0200 "GET /quarantine.php" 200
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:16:21 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:16:21 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:18:52 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:18:52 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:18:53 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:18:53 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:21:03 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:21:03 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:17 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:17 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:40 +0200] "POST /api/v1/edit/quarantine_notification HTTP/1.0" 200 188 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:48 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:49 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:51 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:22:51 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:10 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:10 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:27 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:27 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:28 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:28 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:45 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:23:45 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:24:42 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:24:42 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:24:50 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:24:50 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:24:54 +0200] "POST /api/v1/edit/quarantine_notification HTTP/1.0" 200 189 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:25:00 +0200] "GET /quarantine HTTP/1.0" 200 677043 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:25:01 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:25:18 +0200] "GET /quarantine HTTP/1.0" 200 683848 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:25:18 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:26:33 +0200] "GET /quarantine HTTP/1.0" 200 683848 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:26:33 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:31:15 +0200] "GET /quarantine HTTP/1.0" 200 683848 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:13:31:15 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
dovecot-mailcow_1    | Jun  4 13:20:01 mail CRON[502]: (vmail) CMD (/usr/local/bin/quarantine_notify.py >> /dev/console 2>&1)
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:14:02:46 +0200] "GET /quarantine HTTP/1.0" 200 683848 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
nginx-mailcow_1      | 195.226.180.98 - - [04/Jun/2019:14:02:47 +0200] "GET /api/v1/get/quarantine/all HTTP/1.0" 200 2 "https://mail.cencan.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
dovecot-mailcow_1    | Jun  4 13:40:01 mail CRON[1235]: (vmail) CMD (/usr/local/bin/quarantine_notify.py >> /dev/console 2>&1)
dovecot-mailcow_1    | Jun  4 14:00:01 mail CRON[1873]: (vmail) CMD (/usr/local/bin/quarantine_notify.py >> /dev/console 2>&1)

`

**Comment by andryyy** [comment]
Can you run "docker-compose logs --tail=1 -f php-fpm-mailcow", leave it 
open and resend some spam?

Could you please also send a screenshot of the quarantine config?

------ Originalnachricht ------
Von: "darthdule" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 04.06.2019 14:10:05
Betreff: [mailcow/mailcow-dockerized] Quarantine not working (#2680)

**Comment by darthdule** [comment]
thanks for the reply, I will try it now.

**Comment by andryyy** [comment]
I tried to reproduce, but couldn't. That's good and bad. 😄

**Comment by darthdule** [comment]
here it is:

`
root@cencan:/opt/mailcow-dockerized# docker-compose logs --tail=1 -f php-fpm-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_php-fpm-mailcow_1
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:15:29 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:15:46 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:15:56 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:15:57 +0200 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:16:13 +0200 "HEAD /settings.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:16:13 +0200 "GET /settings.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  04/Jun/2019:14:16:26 +0200 "HEAD /forwardinghosts.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  04/Jun/2019:14:16:26 +0200 "GET /forwardinghosts.php" 200
`

![reject](https://user-images.githubusercontent.com/51367520/58878398-7b844c00-86d3-11e9-9308-0d2abbd0e4f4.png)

![quarantine](https://user-images.githubusercontent.com/51367520/58878465-9fe02880-86d3-11e9-909a-780b327e4cc9.png)


I also tried different settings.

**Comment by andryyy** [comment]
There is no request from Rspamd to pipe.php. What does Rspamd log when it happens? And what about git diff origin/master?

**Comment by darthdule** [comment]
pipe.php does not appear in the logs, neither does rspamd, except for webinterface GET calls etc.
git diff origin/master does not return anything when called from the mailcow directory.

**Comment by darthdule** [comment]
`
rspamd-mailcow_1     | 2019-06-04 15:27:43 #22(normal) <da89e9>; task; rspamd_task_write_log: id: <undef>, qid: <C03E73A109D>, ip: 149.202.232.193, from: <securitycheck@emailsecuritycheck.net>, (default: S (reject): [15.00/15.00] [ASN(0.00){asn:16276, ipnet:149.202.0.0/16, country:FR;},GTUBE(0.00){}]), len: 930, time: 4.000ms real, 3.624ms virtual, dns req: 1, digest: <9e51ea2ecee617af7dc29146ffdb12ec>, rcpts: <dusko@cencan.eu>, mime_rcpts: <dusko@cencan.eu>, forced: reject "Gtube pattern"; score=15.00 (set by GTUBE)
`

corrections, this is rspamd on the moment the message gets rejected.

**Comment by andryyy** [comment]
Doesn't apply to GTUBE as I wrote in the other issue. Gtube is not for testing these kind of things in Rspamd, it is handled differently.
