### ISSUE TITLE
Update Docker Hub Latest Tag

### ISSUE THREAD

**Issue by antoine-blanchard** [mailcow/mailcow-dockerized#2681]
Hi,

The latest tag in Docker Hub is outdated, so you need to put the version in the docker-compose.yml and always update this version.

Can you put in your travis file the latest tag ?

**Comment by ntimo** [comment]
Hello,
We are not publishing a latest Tag for reason, since it can lead to breaking setups when simply pulling the new images without pulling the latest configs with a git pull.

In order to update you can simply use the update.sh

**Comment by MAGICCC** [comment]
As @ntimo said, update your mailcow with the update script. I guess we don't even use Travis at the moment

**Comment by antoine-blanchard** [comment]
Are you planning on using the method "docker-compose pull && docker-compose up -d" in the futur ?

**Comment by MAGICCC** [comment]
Why?
You still need to pull the latest files from the git. The update script does everything automatically, even a docker-compose up -d

**Comment by antoine-blanchard** [comment]
Because the standard method to update a service with docker compose is this method, git pull and after launch a script to update a docker service is not a classic method.

**Comment by MAGICCC** [comment]
Who said you need to git pull on your own?
I know this isn't following docker-compose best practising on how to update, but to solve all merge conflicts, git pulls and on and on, using a single script is way much easier for tons of users

**Comment by mkuron** [comment]
You don't need to use the script if you don't want to. Advanced users can use `git pull` and `docker-compose up -d` instead.

But since you can't use the Docker images without the Git repo and both need to be at the same version, it makes no sense to use the latest tag.

**Comment by antoine-blanchard** [comment]
So I can't use your docker hub ? 😢
