### ISSUE TITLE
rspamd 1.9.3  history tab Envelope from/to gmail address shows incorrectly

### ISSUE THREAD

**Issue by mindas22** [mailcow/mailcow-dockerized#2682]
### rspamd 1.9.3  
history tab **[Envelope from]** and **[Envelope to] To/Cc/Bcc** **gmail** address shows incorrectly when the **dot** is in the gmail address. 

Example when address is firstname.lastname@gmail.com it shows firstnamelastname@gmail.com

**Describe the bug, try to make it reproducible**
A clear and concise description of what the bug is. How can it be reproduced? 
If applicable, add screenshots to help explain your problem. Very useful for bugs in mailcow UI.

**System information and quick debugging**
General logs:
- Please take a look at the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?)
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.) KVM
 - Your server/VM specifications (Memory, CPU Cores)
 - Don't try to run mailcow on a Synology or QNAP NAS, do you?
 - Docker and Docker Compose versions
 - Output of `git diff origin/master`, any other changes to the code? No changes
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Reverse proxy? If you think this problem is related to your reverse proxy, please post your configuration.
 - Browser (if it's a Web UI issue) - please clean your browser cache and try again, problem persists?
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?

**Comment by mkuron** [comment]
That‘s just what Gmail‘s servers do. Not related to rspamd.

**Comment by mindas22** [comment]
> That‘s just what Gmail‘s servers do. Not related to rspamd.

Outgoing email from mailcow to gmail accounts with dot in the name, always shown without dot in rspamd.

How it that related to gmail servers?

**Comment by andryyy** [comment]
Perhaps it strips them as they need to be handled as a single address/sender. That's clever.

**Comment by mkuron** [comment]
Rspamd does it: https://github.com/rspamd/rspamd/blob/7bf0031790ef9c4d1bb8765745044d7bbeb874ea/lualib/lua_util.lua#L173
