### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by DiEg0123** [mailcow/mailcow-dockerized#2683]
Hello,

We have been running several MailCow at AWS EC2 for few months already. But one of them decided to crash today. Since we cannot access to server, we had to reboot.

Now it is stuck at boot saying "[    5.042405] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00" I will paste the full log below.

Has anyone experience the problem? I can mount the Volume as secondary harddisk. I cannot run backup script at all because it is on secondary hard disk. Is there any other way we can backup all the data manually?

`[    4.837206] systemd: 25 output lines suppressed due to ratelimiting
[    4.847682] XFS (nvme0n1p1): Metadata CRC error detected at xfs_dir3_data_read_verify+0x5a/0x100 [xfs], xfs_dir3_data block 0x6fb20
[    4.847684] XFS (nvme0n1p1): Unmount and run xfs_repair
[    4.860684] XFS (nvme0n1p1): First 64 bytes of corrupted metadata buffer:
[    4.860687] ffff90b4f5135000: e8 b4 eb fc 14 7f 00 00 80 ee eb fc 14 7f 00 00  ................
[    4.860688] ffff90b4f5135010: 00 00 00 00 00 00 00 00 00 b0 eb fc 14 7f 00 00  ................
[    4.860689] ffff90b4f5135020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[    4.860690] ffff90b4f5135030: b0 bd 42 f8 06 56 00 00 50 be 42 f8 06 56 00 00  ..B..V..P.B..V..
[    4.860695] XFS (nvme0n1p1): metadata I/O error: block 0x6fb20 ("xfs_trans_read_buf_map") error 74 numblks 8
[    4.861054] XFS (nvme0n1p1): Metadata CRC error detected at xfs_dir3_data_read_verify+0x5a/0x100 [xfs], xfs_dir3_data block 0x6fb20
[    4.910010] XFS (nvme0n1p1): Unmount and run xfs_repair
[    4.913913] XFS (nvme0n1p1): First 64 bytes of corrupted metadata buffer:
[    4.918529] ffff90b4f5135000: e8 b4 eb fc 14 7f 00 00 80 ee eb fc 14 7f 00 00  ................
[    4.925590] ffff90b4f5135010: 00 00 00 00 00 00 00 00 00 b0 eb fc 14 7f 00 00  ................
[    4.932464] ffff90b4f5135020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[    4.939627] ffff90b4f5135030: b0 bd 42 f8 06 56 00 00 50 be 42 f8 06 56 00 00  ..B..V..P.B..V..
[    4.946655] XFS (nvme0n1p1): metadata I/O error: block 0x6fb20 ("xfs_trans_read_buf_map") error 74 numblks 8
[    4.954593] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    4.954593] 
[    4.963164] CPU: 0 PID: 1 Comm: systemd Not tainted 4.14.104-95.84.amzn2.x86_64 #1
[    4.969587] Hardware name: Amazon EC2 t3.small/, BIOS 1.0 10/16/2017
[    4.974179] Call Trace:
[    4.976936]  dump_stack+0x5c/0x82
[    4.980298]  panic+0xe4/0x252
[    4.983308]  do_exit+0xb94/0xba0
[    4.986457]  do_group_exit+0x3a/0xa0
[    4.989816]  SyS_exit_group+0x10/0x10
[    4.993208]  do_syscall_64+0x67/0x100
[    4.996541]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[    5.000360] RIP: 0033:0x7f9994685a88
[    5.003640] RSP: 002b:00007ffe9580f1b8 EFLAGS: 00000206 ORIG_RAX: 00000000000000e7
[    5.010062] RAX: ffffffffffffffda RBX: 00007ffe9580f610 RCX: 00007f9994685a88
[    5.014741] RDX: 000000000000007f RSI: 000000000000003c RDI: 000000000000007f
[    5.019485] RBP: 0000000000000000 R08: 00000000000000e7 R09: 0000000000000000
[    5.024303] R10: ffffffffffffffff R11: 0000000000000206 R12: 00007ffe9580f630
[    5.029006] R13: 00007f999468c488 R14: 0000000000000075 R15: 00007ffe9580f5c6
[    5.034287] Kernel Offset: 0x7000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[    5.042405] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    5.042405]`

**Comment by mkuron** [comment]
> `Metadata CRC error detected at xfs_dir3_data_read_verify`

That‘s a corrupted hard drive or a kernel bug. Nothing Mailcow-related.

> cannot run backup script at all because it is on secondary hard disk.

Just back up the Mailcow git directory and /var/lib/docker. That’s all the script does.

**Comment by DiEg0123** [comment]
Ahh apologies and thanks for your reply. I just managed to recover emails using rsync to new server.
