### ISSUE TITLE
Support for new Webauthn standard

### ISSUE THREAD

**Issue by JustAB0x** [mailcow/mailcow-dockerized#2686]
**Is your feature request related to a problem? Please describe.**
Currently if only U2F is used for TFA you can't use NFC secruity keys on Android.

**Describe the solution you'd like**
Implementation of the new webauthn standard

**Additional context**
It might also be that Firefox will have webauthn on by default but not u2f, if I read the Mozilla wiki ("Goal: permit use of U2F tokens via a user-controllable preference (not on by default) in Firefox 56 or 57 (Done in Firefox 57), and Web Authentication (on by default) in Firefox 59 or 60. "). Webauthn will likely replace u2f in the future.

**Comment by Braintelligence** [comment]
Would you consider making a PR for this? :)

**Comment by JustAB0x** [comment]
I lack the skills to implement it properly, so i'm afraid i can't :/

**Comment by andryyy** [comment]
I also like the idea. But I need to find time. 

I would also sponsor/pay someone to implement it. Let me know...

**Comment by mattnotmitt** [comment]
Hi @andryyy I've been using mailcow for a couple years now and I'd be happy to fill this (but I'd need to order a U2F key since I don't have one atm). Plus I've got a free summer before I start my graduate job in which to work on it and learn how to use the standard.

**Comment by andryyy** [comment]
Nice!
I would buy you a key for WebAuthn if you like.

**Comment by mattnotmitt** [comment]
That sounds great! My email address is on my website (check my profile) and I'll pass on my mailing address through that if you send me an email.

**Comment by andryyy** [comment]
Thanks. Btw. ... I just found CyberChef - that's exactly what I need right now for LoRaWAN. 😄 Nice.

**Comment by mattnotmitt** [comment]
Haha, if you need any help developing any operations for it that are missing to help with that give me a bell, but the repo wiki is pretty good at explaining that stuff.

**Comment by andryyy** [comment]
I just need base64 encoded binary to base16 and base2. :) It works like a charm there.

**Comment by giray** [comment]
Hi ... Any progress on this?

**Comment by mattnotmitt** [comment]
It's already implemented, isn't it @andryyy? Issue needs closing.

**Comment by giray** [comment]
@mattnotmitt it's implemented for the admin interface, not for SoGo, that only has TOPT.

**Comment by andryyy** [comment]
It's implemented in mailcow UI for all user roles. :) That's all _we_ can do.
