### ISSUE TITLE
2 Container on 1 Maschine fails

### ISSUE THREAD

**Issue by tituskurth** [mailcow/mailcow-dockerized#2687]
Hi, i have a problem to set up 2 Mailcow container on 1 maschine

My setup:

A : Bare metal server, no virtualisation 3 IP's
A1: Docker Container Mailcow #1 with IP #1
A2: Docker Container Mailcow #2 with IP #2

What happens:

Fire Up A1: all normal, can send, receive Mails, can Login to Panel and SOGo
Get Message from Watchdog: Watchdog startet

next step:

Fire Up A2:
Get 3 Mails from both Container ( = 6 ) per Minute "Watchdog startet"
Endless... until stop one of both container

get 502 from Nginx, ( php-fpm is not running on A2, get to run: #2656  )
after php-fpm is running, i can log in, configure, send, receive mail

Silly things:

It does not matter which container you start first, the same happens in a different order as well.

Further information (where applicable):
 - Your OS: Debian 9.8
 - Your virtualization technology: Bare Metal
 - Your server/VM specifications 32GB Ram, 8 Core Xeon
 - Don't try to run mailcow on a Synology or QNAP NAS, do you? No
 - Docker and Docker Compose versions: 
Docker version 18.09.6, build 481bc77
docker-compose version 1.24.0, build 0aa59064
 - Output of `git diff origin/master`, any other changes to the code?
A1 = [git_diff_b.log](https://github.com/mailcow/mailcow-dockerized/files/3261348/git_diff_b.log)
A2 = [git_diff_a.log](https://github.com/mailcow/mailcow-dockerized/files/3261342/git_diff_a.log)

 
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?

Output both:
151.101.129.69
151.101.193.69
151.101.1.69
151.101.65.69

**Comment by mkuron** [comment]
If you're running multiple Mailcows, you need to make sure that they bind to different IP addresses and have different docker-compose project names specified in mailcow.conf.

**Comment by andryyy** [comment]
Plus it could be a problem regarding netfilter-mailcow.

Better setup a minimal KVM hypervisor with Alpine guests.

**Comment by tituskurth** [comment]
> If you're running multiple Mailcows, you need to make sure that they bind to different IP addresses and have different docker-compose project names specified in mailcow.conf.

Both Container are bind to single IP on Ports
The Container names are different

**Comment by andryyy** [comment]
They share the same iptables rules on the host.

**Comment by Braintelligence** [comment]
No news is good news.
