### ISSUE TITLE
[FR] Mailinglist-Server (not Mailman)

### ISSUE THREAD

**Issue by Adorfer** [mailcow/mailcow-dockerized#2688]
I would very much apprechiate the direct integration of a mailinglist-robot into mailcow 
including some kind of webui for

 *   setup
 *   monitoring
 *   administration
 *   subscription-selfservice
 *   public/nonpublic archives

This could be some form of mlmmj or even something modern like sympa6
(this is no duplicate of #325 #462 #1303 #1567 #2214 since mailman is explicitly excluded here)

**Comment by andryyy** [comment]
I would love to integrate it. A simple mail list service should not be a big problem. But time is one. And I cannot afford to work on it for days or weeks at the moment.

That’s a feature that I _personally_ would need to be sponsored, but there are several other guys working on mailcow besides me, so I am fine with whoever is able to do this. 

I’d prefer to use most of mailcows current UI and not integrate some third party stuff with 20 new logins etc.

**Comment by mamair** [comment]
I just need a mailinglist solution too. Sympa seems to have great features, but not easy to install. I dont know how to install a (non dockerized) mailinglist beside mailcow :-( so it would be great to have a complete solution.

**Comment by Adorfer** [comment]
i am using Sympa6 right night, but for me it's totally over the top in terms of features.
But perhaps it just needs some kind of abstraction layer to make setup and maintenance more easily.

**Comment by Adorfer** [comment]
Would a bounty help for this? What would be the reasonable funding goal 
(perhaps we can gofundme that in the community)
