### ISSUE TITLE
IPv6 Router Advertisement breaks ACME

### ISSUE THREAD

**Issue by raoulbhatia** [mailcow/mailcow-dockerized#2689]
**Describe the bug, try to make it reproducible**
I configured my server with a static IP and to accept `IPv6AcceptRA=yes` (via systemd-networkd).
This IPv6 address came up first in `docker-entrypoint.sh` and verification failed with
```
Cannot match your IP 2a02:abc:10:27:5054:ff:fee6:6796 against hostname autodiscover.domain.tld (2a02:0abc:0010:0027:0000:0000:0000:1111)
```

Disabling `IPv6AcceptRA` resolved this issue.

**System information and quick debugging**
General logs:
- _(will provide if really requried)_

Further information (where applicable):
 - Ubuntu 18.04.2 LTS + apparmor 2.12-4ubuntu5.1
 - KVM/QEMU
 - 2 cores, 3GB RAM
 - docker-ce 5:18.09.6~3-0~ubuntu-bionic
 - docker-compose version 1.24.0, build 0aa59064
 - Output of `git diff origin/master`, any other changes to the code?
```diff
# git diff origin/master
diff --git a/data/conf/rspamd/override.d/worker-controller-password.inc b/data/conf/rspamd/override.d/worker-controller-password.inc
index 9a5984d1..3b002196 100644
--- a/data/conf/rspamd/override.d/worker-controller-password.inc
+++ b/data/conf/rspamd/override.d/worker-controller-password.inc
@@ -1 +1 @@
-# Placeholder
+enable_password = "$2$33agj48ctpz[...]";
```
 - No firewall active
 - No reverse proxy
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` 
```
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
 docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

**Comment by andryyy** [comment]
You need to set `accept_ra` to 2. :)

**Comment by raoulbhatia** [comment]
Honestly, I am new to systemd-networkd and a little bit confused ;-)

From the man page of systemd.network, `IPv6AcceptRA=yes` should set `accept_ra=2`
```
IPv6AcceptRA=
           Enable or disable IPv6 Router Advertisement (RA) reception support for the interface.
           Takes a boolean parameter. If true, RAs are accepted; if false, RAs are ignored,
           independently of the local forwarding state. When not set, the kernel default is used,
           and RAs are accepted only when local forwarding is disabled for that interface. When
           RAs are accepted, they may trigger the start of the DHCPv6 client if the relevant
           flags are set in the RA data, or if no routers are found on the link.

           Further settings for the IPv6 RA support may be configured in the "[IPv6AcceptRA]"
           section, see below.

           Also see ip-sysctl.txt[5] in the kernel documentation regarding "accept_ra", but note
           that systemd's setting of 1 (i.e. true) corresponds to kernel's setting of 2.
```

However, this does not correspond to the value that is set in /proc, which is
```
/proc/sys/net/ipv6/conf/enp1s0/accept_ra:0
```

**Comment by andryyy** [comment]
Can you set it to 2?

`echo 2 > /proc/sys/net/ipv6/conf/enp1s0/forwarding`

**Comment by raoulbhatia** [comment]
```
# cat /proc/sys/net/ipv6/conf/enp1s0/accept_ra
2
```

```
# docker log $(docker ps -qf name=acme-mailcow)
docker: 'log' is not a docker command.
See 'docker --help'
root@mailx:/opt/mailcow-dockerized# docker logs $(docker ps -qf name=acme-mailcow)
Tue Jun 11 09:29:07 UTC 2019 - Waiting for Docker API...OK
Tue Jun 11 09:29:08 UTC 2019 - Waiting for database... Uptime: 2  Threads: 9  Questions: 5  Slow queries: 0  Opens: 18  Flush tables: 1  Open tables: 12  Queries per second avg: 2.500
OK
Tue Jun 11 09:29:10 UTC 2019 - Waiting for Nginx... OK
Tue Jun 11 09:29:10 UTC 2019 - Waiting for domain table... OK
Tue Jun 11 09:29:11 UTC 2019 - Initializing, please wait...
Tue Jun 11 09:29:11 UTC 2019 - Using existing domain key /var/lib/acme/acme/key.pem
Tue Jun 11 09:29:11 UTC 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
Tue Jun 11 09:29:11 UTC 2019 - Detecting IP addresses... OK
Tue Jun 11 09:29:29 UTC 2019 - Found AAAA record for autodiscover.nem3d.net: 2a02:1b8:10:27::99 - skipping A record check
Tue Jun 11 09:29:29 UTC 2019 - Cannot match your IP 2a02:1b8:10:27:5054:ff:fee6:889f against hostname autodiscover.nem3d.net (2a02:01b8:0010:0027:0000:0000:0000:0099)
Tue Jun 11 09:29:29 UTC 2019 - Found AAAA record for mailx.bhatia.eu: 2a02:1b8:10:27::99 - skipping A record check
Tue Jun 11 09:29:29 UTC 2019 - Cannot match your IP 2a02:1b8:10:27:5054:ff:fee6:889f against hostname mailx.bhatia.eu (2a02:01b8:0010:0027:0000:0000:0000:0099)
Tue Jun 11 09:29:29 UTC 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
Tue Jun 11 09:29:29 UTC 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
```

**Comment by raoulbhatia** [comment]
IMHO the problem is not kernel related but that the match is done against the IPv6  address that gets discovered as the default outgoing IP via `curl --connect-timeout 3 -m 10 -L6s` against `IPV6_SRCS`.

IMHO there might be multiple IPv6 addresses on a host and an behavior could be either of the following.

1. Resolve AAAA record for autodiscover/autoconfig
2. Check if this IP address is bound to an interface and use `curl --interface` when verifying against `IPV6_SRCS`.

or alternatively
1. Get all IPv6 addresses that are bound to the interfaces
2. For each IPv6 address check if it is working / routable, i.e. `curl --interface`.
3. Then perform the match.

**Comment by raoulbhatia** [comment]
On a separate note, it seems that Debian and therefore Ubuntu disable the accept_ra functionality in systemd-networkd, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814667

```
   * networkd: Go back to letting the kernel handle IPv6 router advertisements,
     as networkd's own currently has too many regressions. Thanks to Stefan
     Lippers-Hollmann for investigating this! (Closes: #814566,
     #814667, #815586, #815884, #815793)
```

Additional details can be found here https://github.com/systemd/systemd/issues/8906

**Comment by andryyy** [comment]
Create a PR or just set IPv6 SNAT in mailcow.conf.

**Comment by andryyy** [comment]
Or ... just deactivate the checks.... ;)

**Comment by raoulbhatia** [comment]
Perhaps I'll give it a try then.  But it will likely take some time.
