### ISSUE TITLE
Postfix-Log: Mail an Ressource wird abgelehnt

### ISSUE THREAD

**Issue by dominicpratt** [mailcow/mailcow-dockerized#2691]
Hallo Leute,

einer meiner Kunden nutzt die Ressourcen-Funktion ziemlich exzessiv.

Nun sehe ich im Log, immer wenn ein Termin angelegt wird, diese Logeinträge:

`9CDA85A0673: reject: RCPT from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]: 550 5.1.1 <papageienzimmer@example.org>: Recipient address rejected: User unknown in virtual mailbox table; from=<me@example.org> to=<papageienzimmer@example.org> proto=ESMTP helo=<578944bce8f6>`

Ist das ein bedenkliches Problem, falls ja, was kann ich tun? Falls nicht: kann man die Logeinträge abschalten, damit die nicht das Log vollmüllen.

**Comment by andryyy** [comment]
Bedenklich nicht, aber nervig. Ich schaue mal, was ich da machen kann.

**Comment by andryyy** [comment]
Sollte gefixt sein, wenn nicht, bitte schreien. 👍
