### ISSUE TITLE
Link to the global sieve postfilter is incorrect on Filter tab

### ISSUE THREAD

**Issue by roland-d** [mailcow/mailcow-dockerized#2695]
**Describe the bug, try to make it reproducible**
1. Login to a mailbox
2. Click on Filters tab
3. Check the intro text:
![image](https://user-images.githubusercontent.com/359377/59158307-9cc0b000-8ab8-11e9-8a9a-8fe132d3baa5.png)
4. The `global sieve postfilter` is a link that points to `https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/sieve_after`
5. This link is broken.

The correct link is:
`https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/global_sieve_after`

As you can see from the commit message, this file has been renamed.

**Comment by andryyy** [comment]
Update your cow. :) The links changed.

Looks like this now, btw:

![image](https://user-images.githubusercontent.com/2972950/59158368-97179a00-8ab9-11e9-87d5-9686301cad45.png)
