### ISSUE TITLE
PDO php

### ISSUE THREAD

**Issue by jose123455587** [mailcow/mailcow-dockerized#2696]
I'm trying to develop a php page where people can create your own account.
The problem is in connect to DB. I searched a lot and found that I don't have mysql for php.
How can I download and active it?
Thanks,
José

**Comment by andryyy** [comment]
We use pdo. :) You could change the image, but it is much, much easier to just adopt to the few changes between mysqli and pdo.

**Comment by jose123455587** [comment]
I'm using PDO now but I'm getting this " Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory [...]" . 
My code  
  `$dsn = 'mysql:host=localhost;dbname=mailcow';
    $username = 'mailcow';
    $password = 'mypassword';
    $options = array(
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
    ); 

    $conn = new PDO($dsn, $username, $password, $options);
`
How can I solve this?
