### ISSUE TITLE
Beim updaten bekomme ich den hinweis, ich solle doch meine selbst hinzugefügen MAilcow datein endfernen, dadurch schlägt das update fehl.

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#2697]
Hallo erst mal.
Ich hab eben meine Mailcow Innstallation akt. dabei bekam ich diese Fehlermeldung vom Update script:
Removing network mailcowdockerized_mailcow-network
Committing current status...
Fetching updated code from remote...
Merging local with remote code (recursive, strategy: "theirs", options: "patience"...
error: Your local changes to the following files would be overwritten by merge:
        data/conf/rspamd/override.d/worker-controller-password.inc
Please commit your changes or stash them before you merge.
Aborting

Oh no, what happened?
=> You most likely added files to your local mailcow instance that were now added to the official mailcow repository. Please move them to another location before updating mailcow.

Ich verstehe nicht, was er da genau meckert, ich hab keine datein hinzugefügt.
Erneutes ausführen des Script ändern nichts, es kommt die selbe Fehlermeldung.
Ubuntu 18.04 server ohne gui.

**Comment by andryyy** [comment]
Kannst du die Datei data/conf/rspamd/override.d/worker-controller-password.inc löschen und dann normal updaten?

Falls ja, müsstest du das Passwort anschließend neu setzen.

**Comment by andryyy** [comment]
We probably need to run git rm to remove it from the index before updating. :/

**Comment by Conan179** [comment]
worker-controller-password.inc gelöscht und update.sh läuft wieder ohne probleme durch.
Fürs Protokoll, die datei hat, das Letzte bearbeitungsdatum, als ich Mailcow Innstalliert habe, sie ist also nicht neu.

**Comment by andryyy** [comment]
Ja, sie wurde gelöscht, aber wir sollten sie vermutlich vorher aus dem Index löschen.

Kannst du das Update probeweise noch einmal ausführen? Klappt es jetzt „normal“?

**Comment by Conan179** [comment]
Öhm, ICH hab sie eben gelöscht und ich schrieb doch schon, das es wieder geht.
Aber warum ist diese Datei plötzlich nicht merh gewollt? sie war doch schon immer bei mir da.

**Comment by andryyy** [comment]
Nein. Einfach noch einmal das Update ausführen. Das meinte ich.

**Comment by Conan179** [comment]
"und update.sh läuft wieder ohne probleme durch."
Ja und hab doch geschrieben, das es jetzt ging.

Ich frage mich aber, WARUM plötzlich diese Datei ärger macht.

**Comment by andryyy** [comment]
Egal. Ich wollte, dass du es jetzt trotzdem NOCH einmal ausführst. Obwohl es beim letzten Mal ging. Also NOCH einmal. Nach dem erfolgreichen Update könnte es beim nächsten Mal wieder kaputt sein. Deshalb. ;)

Warum das so ist? Weil wir die Datei im Upstream gelöscht haben. Eventuell muss sie vorher manuell aus dem Index entfernt werden.

**Comment by Conan179** [comment]
Hab es jetzt 3mal lauffen lassen, keine fehlermeldungen.

**Comment by andryyy** [comment]
Danke dir! Dann teste ich nachher die Änderung mit git rm

**Comment by Conan179** [comment]
Ich frage mich aber imer noch warum plötzliche eine, vom system angelegte Datei plötzlich als flasch erkannt wird.

**Comment by Adorfer** [comment]
dito hier... jede Menge Dateien, die ich nie selbst überhaupt angefasst habe...

     git rm data/conf/rspamd/override.d/worker-controller-password.inc
     git stash

und noch ein paar weitere Dinge.... 
sah teilweise etwas unübersichtlich aus. 
![grafik](https://user-images.githubusercontent.com/10302493/59203662-54c88880-8b9f-11e9-8514-8fd5aad58c60.png)

![grafik](https://user-images.githubusercontent.com/10302493/59203772-90635280-8b9f-11e9-9aa6-5e330a0399a3.png)


keine Ahnung, was ich alles gemacht habe, irgendwann lief das updatescript dann doch wieder druch.

**Comment by andryyy** [comment]
Bei den Dateien sollte und wird das eigentlich passieren. Wenn du da jetzt selber mit stash und co dran warst, kann das passieren. Es war zu Beginn bestimmt nur die eine Datei, bis du es dann manuell versucht hast. :) Jedenfalls würde es das erklären. 

Bitte auf Englisch weiter, sonst hat da kaum einer was von. 

Jedenfalls betrifft diese Änderung nur die Rspamd passwd Datei. Ich kann es erst heute Abend prüfen und fixen. Glaube git rm reicht. Vielleicht hat ja gerade jemand Zeit.

**Comment by Conan179** [comment]
Mein Eng Kenntnisse sind nicht so gut um eng zuschreiben lesen geht.
Ich hab die Datei nicht ein mal geöffnet ,bearbeiten geschweigenden berüht. 
Sie hatte noch datum von der erstellung damals.
Sie ist urplötzlich so erkannt worden.

**Comment by andryyy** [comment]
Das habe ich nicht behauptet und auch schon erklärt. Auch mit potentieller Lösung. Die Datei wurde aus dem Index entfernt, aber lokal durch mailcow modifiziert. Das gibt einen Konflikt. git rm VOR dem Update im Script, könnte das Problem beheben. Aber bin noch nicht am Computer, um es zu testen. Vielleicht legen wir die Datei auch einfach ganz woanders hin (nicht in einen Mount) und löschen Sie aus dem Verzeichnis.

**Comment by Conan179** [comment]
Ok, endschuldigung, das ich dich falsch verstanden habe.

**Comment by andryyy** [comment]
:P brauchst du dich nicht für entschuldigen.

**Comment by andryyy** [comment]
Looks good now.

Sieht gut aus.

Mir fällt noch ein Szenario ein, wo es klemmen könnte. Muss es gleich testen.

**Comment by byRoadrunner** [comment]
hey there, 
I am still getting this error:
`fatal: pathspec 'data/conf/rspamd/override.d/worker-controller-password.inc' did not match any files
`
The only thing i did was deleting the file. But now it exists again and it´s still showing the error. Or should I just ignore it?

**Comment by Adorfer** [comment]
How did you "delete" the file? as stated above via "git rm"?

**Comment by andryyy** [comment]
It is recreated, yes, that's ok. But it is not indexed. You probably see this error and it still updates, right?

**Comment by byRoadrunner** [comment]
Yes, the update proceeds as usual and everything is working. But the error shows in the console.

**Comment by andryyy** [comment]
Ah, thanks for the feedback. Yes, that's ok, if the file was not tracked (anymore). I fixed it by 2> null. 😄

**Comment by byRoadrunner** [comment]
Thats how you have to handle errors xD

**Comment by andryyy** [comment]
Felt bad and fixed it.
