### ISSUE TITLE
PDO php

### ISSUE THREAD

**Issue by jose123455587** [mailcow/mailcow-dockerized#2698]
I'm trying to develop a php page where people can create your own account.
The problem is in connection to DB. I'm using PDO now but I'm getting this " Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory [...]" .
My code
` $dsn = 'mysql:host=localhost;dbname=mailcow';
$username = 'mailcow';
$password = 'mypassword';
$options = array(
PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
);

$conn = new PDO($dsn, $username, $password, $options);
` 
How can I solve this?

**Comment by andryyy** [comment]
Check vars.inc.php and prerequisites.inc.php :) Use the socket or mysql as hostname.
