### ISSUE TITLE
Option to remove port assignment in docker-compose.yml

### ISSUE THREAD

**Issue by gloomytree** [mailcow/mailcow-dockerized#2699]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to use mailcow behind a reverse proxy that runs in a docker container itself. Example: [nginx-proxy](https://github.com/jwilder/nginx-proxy). The solution is to remove or comment out these lines:

    ports:
        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"

**Describe the solution you'd like**
Is it possible to change the docker-compose.yml in a way so the port assignment is optional? Nginx will not start if it can not bind the IP/Port because another service has already registered it. Port assignment is not needed, if docker networks are used and another container works as reverse proxy. 

**Additional context**
In my usecase, after commenting out the lines in i used docker-compose.override.yml to make everything work with nginx-proxy: 

    version: '2.1'

    services:

    nginx-mailcow:
      environment:
        - LETSENCRYPT_HOST=${MAILCOW_HOSTNAME}
        - LETSENCRYPT_EMAIL=mi.biermann@gmail.com
        - VIRTUAL_HOST=${MAILCOW_HOSTNAME}
        - VIRTUAL_PROTO=http
        - VIRTUAL_PORT=80
      networks:
        nginx:

    networks:
      nginx:
        external:
          name: nginx

**Comment by andryyy** [comment]
Hi,

Hm, you need to bind them to some unused port and to 127.0.0.1 then. :/ Hard to remove that option from mailcow.conf.

**Comment by gloomytree** [comment]
Hi, 

yeah, i supposed that.. It's generally really hard to configure the docker part of mailcow. Additionally, i'd love to store the volumes in a seperate folder, where i mount all the other docker volumes. I simply backup the volumes folder and am safe. Doesn't work without changing the docker-compose.yml.
