### ISSUE TITLE
Consider Squashing and Compressing your Images

### ISSUE THREAD

**Issue by tiredofit** [mailcow/mailcow-dockerized#270]
Lovely piece of work, very glad I moved over from the Baremetal version into the Dockerized version, and excited to see new features down the road.

One suggestion, as of Docker 1.13 (before they switched from CE and EE designations) they introduced an experimental series of flags during build of --squash and --compress.

Squash will take your images and crunch the layers down to as minimal as possible (3?) so that it is easier for downloading production level images. Compress will apply some sort of gzip compression to the image which will further assist in size. We're using it in production on approximately 80 self built images and while it's not suitable for Dockerfile Debugging, when we push it to our registry for production use the size differences are very visible. 

Just a thought!

**Comment by andryyy** [comment]
Hi,
I am working on reducing the image sizes now. I will try squashing! Have read about it but not yet used in production.
