### ISSUE TITLE
Moving mailcow to a new domain

### ISSUE THREAD

**Issue by itsbhanusharma** [mailcow/mailcow-dockerized#2700]
Hi @andryyy , 

I'd like to move my mailcow-dockerized instance from current domain e.g. `mail.example1.com` to another domain `mail.example2.email` 

what would be the easiest approach to achieve the same?

**Comment by andryyy** [comment]
You better mail me, when you want to ask me something. 😄 

You should be fine by running docker-compose down, change the name in mailcow.conf, delete the rspamd-mailcow container and run up -d.

**Comment by itsbhanusharma** [comment]
Thanks! 

I'll mail the next time onwards ;)

**Comment by itsbhanusharma** [comment]
Thanks!

What address shall I be emailing to?

**Comment by andryyy** [comment]
If you want to ask me personal questions, mail me to andre.peters@debinux.de.

I will not do mail support or something like that. If you need fast and reliable support, get a support subscription with Servercow. :) You **don't need to** buy anything. You can always join our IRC channel or use the board (if it's still active) to ask questions.

**Comment by MatejKovacic** [comment]
Hi, I would need a little help here.

You said: "You should be fine by running docker-compose down, change the name in mailcow.conf, delete the rspamd-mailcow container and run up -d."

So the procedure is: 
- `docker-compose down`
- `cd /opt/mailcow-dockerized`
- `nano mailcow.conf` and change `MAILCOW_HOSTNAME=`
- this is what I **DO NOT** know how to do: "**delete the rspamd-mailcow**"???
- and finally: `docker-compose up -d`

**Comment by itsbhanusharma** [comment]
>     * this is what I **DO NOT** know how to do: "**delete the rspamd-mailcow**"???


`docker rm rspamd-mailcow` this should do the trick
