### ISSUE TITLE
Do not show real IP in dovecot/postfix etc. logs in Windows Server 2016

### ISSUE THREAD

**Issue by littleplus** [mailcow/mailcow-dockerized#2703]
When I check the log, I found this:
```
2019/6/12 P.M. 4:51:09 | info | 9A4DA81D45: from=<xxx@xxx.com>, size=894, nrcpt=1 (queue active)
-- | -- | --
2019/6/12 P.M. 4:51:08 | info | 9A4DA81D45: client=unknown[172.22.1.1], sasl_method=LOGIN, sasl_username=xxx@xxx.com
```

At the same time, I also found my email hosting was used to send large amounts of junk emails, however, I could not find out where they enter my mail hosting and what mail address they use.

**Comment by mkuron** [comment]
Running Mailcow on Docker for Windows is not supported. It does not preserve the source IP address, as you have observed.
