### ISSUE TITLE
Random or bug: IP ban: 45.13.36.0/24?

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#2704]
I admin two mailcow installation and since the last updates with changes of watchdog, i get every some hours mails about an IP ban and RIPE information like this:

Subject: Wed Jun 12 01:05:37 CEST 2019 - IP ban: 45.13.36.0/24

"% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '45.13.36.0 - 45.13.36.255'

% Abuse contact for '45.13.36.0 - 45.13.36.255' is 'bphostru@yandex.com'

inetnum:        45.13.36.0 - 45.13.36.255
netname:        BPHOST-NET
org:            ORG-BA1209-RIPE
country:        NL
admin-c:        GJM76-RIPE
tech-c:         GJM76-RIPE
status:         ASSIGNED PA
mnt-by:         TAMATYA-MNT
mnt-by:         BPHOST-LTD
created:        2019-05-03T23:01:18Z
last-modified:  2019-06-05T11:34:54Z
source:         RIPE

organisation:   ORG-BA1209-RIPE
org-name:       BpHost LTD
org-type:       OTHER
address:        United Kingdom
address:        London
address:        2, Vernon Road, Ilford, London
phone:          +447425060133
abuse-c:        ACRO23975-RIPE
mnt-ref:        BPHOST-LTD
mnt-by:         BPHOST-LTD
created:        2019-04-18T10:12:25Z
last-modified:  2019-04-18T10:15:06Z
source:         RIPE # Filtered

person:         Galloway Joe Michael
address:        2,Vernon Road
phone:          +447425060133
nic-hdl:        GJM76-RIPE
mnt-by:         BPHOST-LTD
created:        2019-04-18T10:06:48Z
last-modified:  2019-04-18T10:06:48Z
source:         RIPE

% Information related to '45.13.36.0/24AS209282'

route:          45.13.36.0/24
origin:         AS209282
mnt-by:         BPHOST-LTD
created:        2019-05-20T09:25:31Z
last-modified:  2019-05-20T09:25:31Z
source:         RIPE

% This query was served by the RIPE Database Query Service version 1.94 (ANGUS)"

Sender is my watchdog email address. Is this all a random and this ip tries really to use/hack the installation or has this something to do with the latest changes? Up to know I got only from the first installation 15 emails with the above text nearly every hour.

**Comment by andryyy** [comment]
Neither random nor a bug. It is a report, that an IP was blocked.

**Comment by lgusewski** [comment]
Hmm, this massiv reports starts with this detail information directly after the last updates and it is every time the same ip range. On one installation i blocked the ip manually without a unban time. Is it possible to make the 30 minutes ban time longer per default?

**Comment by andryyy** [comment]
You can perm ban the IP range. Or increase the ban time, yes. All in the mailcow UI.

**Comment by Adorfer** [comment]
related question: How do i turn off these reports by mail? It's really bugging, more than 4 per hour since the update. 
![grafik](https://user-images.githubusercontent.com/10302493/59416123-101e3680-8dc5-11e9-9d73-bb60f92b642c.png)

**Comment by andryyy** [comment]
Drop them via sieve. I will add a config switch later.

**Comment by Adorfer** [comment]
systemmails of the mailsystem do not get to my email server, since this would be not helpful in case of outage... (what the watchdog is for). But i can filter in gmail off course.

**Comment by MAGICCC** [comment]
Added in https://github.com/mailcow/mailcow-dockerized/commit/8984240e44df9f3ed6e7ad5d84ade10c0e124e51#diff-bd6af8ddc3fbe4d221556680bc00048fR221

**Comment by TEFEdotCC** [comment]
Interessting.
Get the same ip range today.

Edit: First ban was on Fr. 05.07.2019


> % This is the RIPE Database query service.
> % The objects are in RPSL format.
> %
> % The RIPE Database is subject to Terms and Conditions.
> % See http://www.ripe.net/db/support/db-terms-conditions.pdf
> 
> % Note: this output has been filtered.
> %       To receive output for a database update, use the "-B" flag.
> 
> % Information related to '45.13.39.0 - 45.13.39.255'
> 
> % Abuse contact for '45.13.39.0 - 45.13.39.255' is 'bphostru@yandex.com'
> 
> inetnum:        45.13.39.0 - 45.13.39.255
> org:            ORG-BA1209-RIPE
> netname:        BPHOST-NET
> country:        GB
> admin-c:        GJM76-RIPE
> tech-c:         GJM76-RIPE
> status:         ASSIGNED PA
> mnt-by:         BPHOST-LTD
> created:        2019-05-03T23:02:06Z
> last-modified:  2019-05-05T19:24:31Z
> source:         RIPE
> 
> organisation:   ORG-BA1209-RIPE
> org-name:       BpHost LTD
> org-type:       OTHER
> address:        United Kingdom
> address:        London
> address:        2, Vernon Road, Ilford, London
> phone:          +447425060133
> abuse-c:        ACRO23975-RIPE
> mnt-ref:        BPHOST-LTD
> mnt-by:         BPHOST-LTD
> created:        2019-04-18T10:12:25Z
> last-modified:  2019-04-18T10:15:06Z
> source:         RIPE # Filtered
> 
> person:         Galloway Joe Michael
> address:        2,Vernon Road
> phone:          +447425060133
> nic-hdl:        GJM76-RIPE
> mnt-by:         BPHOST-LTD
> created:        2019-04-18T10:06:48Z
> last-modified:  2019-04-18T10:06:48Z
> source:         RIPE
> 
> % Information related to '45.13.39.0/24AS209282'
> 
> route:          45.13.39.0/24
> origin:         AS209282
> mnt-by:         BPHOST-LTD
> created:        2019-05-24T13:35:19Z
> last-modified:  2019-05-24T13:35:19Z
> source:         RIPE
> 
> % This query was served by the RIPE Database Query Service version 1.94 (WAGYU)

**Comment by altnd** [comment]
Strange... same range here too...
first showed up 06 July 10:10 CEST till 06 July 19:30 CEST 

than i have added it to the permanent Ban List and droped everything on the Firewall from this range

**Comment by TEFEdotCC** [comment]
Get next ban for  45.13.39.0 - 45.13.39.255 at 22:45.
Something is going on.

**Comment by andryyy** [comment]
I see this IP myself, too. Not on all systems, but a lot.

**Comment by andryyy** [comment]
https://www.abuseipdb.com/check/45.13.39.115

**Comment by PaoloVi** [comment]
The new watchdog mail alert for brute force attack is very nice.
These is my blacklisted ip in fail2ban after only one week.

141.98.80.67/32
185.211.245.170/32
185.211.245.198/32
185.222.209.40/32
185.222.209.61/32
185.222.209.79/32
197.58.29.42/32
45.227.253.211/32
45.227.253.212/32
45.227.253.213/32
78.128.113.66/32
78.128.113.67/32

**Comment by MAGICCC** [comment]
No need to report every single IP range
Welcome to the internet
