### ISSUE TITLE
Watchdog Notifications (from watchdog@mx.domain.tld) are marked as spam (DMARC Fail)

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#2705]
Email Notifications sent from Watchdog fail DMARC validation and are marked as spam by the email client (Gmail and Outlook at least).

I've added the mx.domain.tld DMARC dns entries and everything seems to be valid.

I can get around this easily by creating rules on Gmail/Outlook, however I believe there is a better way.

Any help is appreciated :)

```
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: best guess record for domain of watchdog@mx.domain.tld designates 11.22.33.44 as permitted sender) smtp.mailfrom=watchdog@mx.domain.tld;
       dmarc=fail (p=QUARANTINE sp=QUARANTINE dis=QUARANTINE) header.from=mx.domain.tld
```

**Comment by andryyy** [comment]
They fail when they don't fit your policy, yes. It just follows what you configure. Will probably work when you setup a DMARC policy for the FQDN (the subdomain watchdog sends from). Or just send to another host. We will not sign these mails in the future. I will close this, feel free to discuss, ask questions etc. etc.

**Comment by apintocr** [comment]
Thank you @andryyy 

Yes, adding `v=DMARC1; p=none` indeed solves the problem.
However I do not think this should be the only way.

Is there any reason you are planning to not auth those mails?

**Comment by andryyy** [comment]
They are sent via smtp-cli, not through Postfix. :)

**Comment by apintocr** [comment]
I understand.
It's more reliable in case of system failure.

Sorry if it was a stupid question 😊

**Comment by pneuschwander** [comment]
It might be sufficient to add a SPF record to the subdomain:

`mail.MYDOMAIN.de TXT "v=spf1 redirect=MYDOMAIN.de"`

The rest of the DNS setup:

`MYDOMAIN.de TXT "v=spf1 mx ~all"`

`MYDOMAIN.de      MX preference = 10, mail exchanger = mail.MYDOMAIN.de`

`_dmarc.MYDOMAIN.de TXT "v=DMARC1; p=quarantine; pct=100"`

At least for me this results in SPF pass and DMARC pass for the watchdog notifications sent to a GMail address.

**Comment by andryyy** [comment]
Yes, SPF is just as fine. 

Mit besten Grüßen
André Peters
