### ISSUE TITLE
2FA Problem

### ISSUE THREAD

**Issue by Ortner-IT** [mailcow/mailcow-dockerized#2707]
Hallo, 

hoffentlich passt es auch, wenn ich auf Deutsch schreibe. Ich habe letzte Woche noch die Funktion 2 FA Nutzen können, nun will ich mich im Admin Account einloggen und dort dementsprechend was konfigurieren. Wenn ich den Token am Handy bei Mailcow eingebe, sagt Mailcow: "TOTP Verifizierung fehlgeschlagen"

Jetzt müsste ich wissen: Kann man das in einer Konfig oder derartiges deaktivieren oder anderweitig. Wäre sehr Hilfreich, wenn mir jemand helfen könnte.

Mit freundlichen Grüßen
Michael

**Comment by Sarsum** [comment]
Hallo Michael,

ich denke, die Anleitung ganz am Ende dieser Seite sollte dir helfen! https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/

Viele Grüße,

Linus

**Comment by andryyy** [comment]
Stimmt die Zeit am Handy?

**Comment by Ortner-IT** [comment]
Hallo,

ja diese stimmt überein. Ich habe mal Sarsum seinen Link befolgt, jedoch vermute ich mal, dass dies ein Bug ist. Das Rechenzentrum hatte da mal Wartungsarbeiten ausgeführt, dadurch war der Server nicht erreichbar und wahrscheinlich auch Mailcow. Vermute also, dass beim Neustart oder derartiges irgendwas passiert ist, dass der 2FA nicht mehr funktionierte.

**Comment by Braintelligence** [comment]
Seems like you've solved your problem.
