### ISSUE TITLE
Add option for disabling watchdog startup mail

### ISSUE THREAD

**Issue by byRoadrunner** [mailcow/mailcow-dockerized#2708]
**Is your feature request related to a problem? Please describe.**
Currently everytime mailcow restarts you get an mail alert from watchdog, that it´s enabled and monitoring mailcow.

**Describe the solution you'd like**
I would suggest to add an config option to disable the sending of these startup mails, because it can be very annoying to get an email for example after every update. Also I would change the subject from "Watchdog ALERT: watchdog-mailcow" to "Watchdog INFO: watchdog-mailcow" in case of the startup mail, because it isn´t really a critical information.

**Comment by Adorfer** [comment]
we should be lucky that the watchdog is not as annoying as the one of sympa6-ML, that complains during every restart "loss of database" plus "reestablished database connection", in total at minimum 4 mails.

**Comment by andryyy** [comment]
The start mail is something I see as important information. You will also know when the stack was restarted (because of whichever error). 

The ban mails can be disabled as of yesterday. 

I hope you understand the reasoning behind the startup mail. :) I think @ntimo plans to add docs, we will add further information about watchdog then.

**Comment by byRoadrunner** [comment]
Okay, I understand this, but I think it wouldn´t be bad to add an option do disable it. Of course the default setting should still be enabled.

**Comment by XVII** [comment]
I want to turn this email off too. We regularly patch so it causes a lot of unnecessary emails each time :(

A central alerts console would be useful, i.e how particular errors/notices etc should be handled.

**Comment by XVII** [comment]
> The start mail is something I see as important information. You will also know when the stack was restarted (because of whichever error). 
> 
> The ban mails can be disabled as of yesterday. 
> 
> I hope you understand the reasoning behind the startup mail. :) I think @ntimo plans to add docs, we will add further information about watchdog then.

Appreciate the importance of it, but different setups have different thresholds when it comes to evaluating importance.
