### ISSUE TITLE
Tagging for mails from same domain does not work (BCC maps)

### ISSUE THREAD

**Issue by bonanza123** [mailcow/mailcow-dockerized#2709]
Tagging (and moving to folder/adding tag to subject) does not work for me in the following constellation:
For `userA@dom.org` I added a sending and receiving BCC map that sends the mails to `userB+sent@dom.org` and `userB+received@dom.org` respectively. 
For `userB`, the tagging does not work in this case? How to enable it?

I guess that this issue is similar to https://github.com/mailcow/mailcow-dockerized/issues/1445 but I don't know how to apply this.

**Comment by andryyy** [comment]
It does not pass the filter. 

You can write your own sieve script for user B, to sort even without X-Moo-Tag header. Just use the global sieve filter as template, but remove the check for the X header.

**Comment by bonanza123** [comment]
Thanks for the hint!
I did the following and it seems to work so far (comments/improvements are welcome!)

I created the user script `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/sieve/userB@domain.tld.sieve` with the content:
```
require ["fileinto", "envelope", "subaddress"];
if envelope :detail "to" "received"{
  fileinto "INBOX/received";
}
if envelope :detail "to" "sent"{
  fileinto "INBOX/sent";
}
```

The subfolders `sent` and `received` I created manually before.
More details can be found here: https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples

**Comment by andryyy** [comment]
You can also create them with mailcow UI. :) But it does not matter.
