### ISSUE TITLE
Domain admin list is emtpy

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#271]
Hi,

I've upgraded mailcow to the latest master version, and after restart all the containers because of errors I've noticed that domain admin list is empty but I'm not able to add them again because they exists on database.

I don't know if someone have the same issue.

Regards.

**Comment by felixoi** [comment]
I have the same problem with my dkim selectors.

**Comment by mcoreix** [comment]
Same issue :(

**Comment by ignitedPotato** [comment]
I've got the same problem. Domain admin list is empty.

**Comment by stevesbrain** [comment]
@axd was this resolved as per #272 ?

**Comment by pschiffe** [comment]
@stevesbrain no, this problem still persists.

**Comment by stevesbrain** [comment]
Oh, interesting :/ I'm on master and current at the moment, and added a domain administrator today without issue. Is it possible to temporarily remove the data store for domain admin list (which I'm guessing is mysql, so maybe temporarily drop contents of those tables after backing up), and try adding them fresh?

**Comment by pschiffe** [comment]
Adding new domain admins works, just the ones created before the weekend update are not shown.

**Comment by andryyy** [comment]
That's crazy. I try to reproduce it now!

**Comment by andryyy** [comment]
Okay, I updated mailcow. But you will need to recreate the domain administrators that are missing now. :(

**Comment by axd** [comment]
@andryyy I'll give it a try. Thank you.

**Comment by PhoenixPeca** [comment]
I believe this issue is resolved. I'm closing this for now.
