### ISSUE TITLE
Mailbox List suddenly doesn't load anymore

### ISSUE THREAD

**Issue by Maingron** [mailcow/mailcow-dockerized#2710]
### Hello,
Today I wanted to maintain my Server and add a new Mail domain to Mailcow. I was able to add the Domain and one test mail adress and it worked fine. When I wanted to remove the test address again, the mailbox list didn't show up anymore. I fiddled a bit around and ended up with restoring a mailcow backup. This also didn't help and I still can't see my mailboxes. I was not able to find anything interresting in the logs when using the browser, though in the console it reads this:
`mailbox:1189 Uncaught ReferenceError: $ is not defined
    at mailbox:1189
(anonymous) @ mailbox:1189`

`mailbox:1520 Uncaught ReferenceError: ALLOW_ADMIN_EMAIL_LOGIN is not defined
    at Object.<anonymous> (mailbox:1520)
    at Function.each (mailbox:1366)
    at Object.success (mailbox:1518)
    at i (mailbox:1366)
    at Object.fireWith [as resolveWith] (mailbox:1366)
    at y (mailbox:1366)
    at XMLHttpRequest.c (mailbox:1366)`

### System information:
Linux xxxxxxx.server.xxxxxxxx.org 4.9.0-9-amd64 `#1` SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

Docker version 18.09.6, build 481bc77

I should be on the latest Mailcow Version

### Check docker exec -it $...
~# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.65.69
151.101.129.69
151.101.193.69
151.101.1.69
~# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

![image](https://user-images.githubusercontent.com/47825439/59552842-1f9bac00-8f8c-11e9-9720-a02d52c48d5d.png)

**Comment by Maingron** [comment]
I should probably also mention, that everything else seems to work fine.

**Comment by andryyy** [comment]
And git diff origin master?

**Comment by Maingron** [comment]
Do you mean this? I'm sorry, yet I haven't worked much with git. 
[diff.txt](https://github.com/mailcow/mailcow-dockerized/files/3293291/diff.txt)

**Comment by andryyy** [comment]
Yes. You should run update. Or git pull and fix the conflicts. I don’t think all of your code is really up to date.

**Comment by Maingron** [comment]
I ran update.sh and docker-compose pull, but the git diff is still pretty long, probably nothing changed.

**Comment by MAGICCC** [comment]
You may run update.sh a second time, it may only updated the update script the first time

**Comment by Maingron** [comment]
I ran it multiple times already :(

**Comment by andryyy** [comment]
The script pulls the images. Run git pull and fix the conflicts.

**Comment by Maingron** [comment]
When I run git pull, it says I am already up to date.

```
root@b18lvn9:/opt/mailcow-dockerized# git pull
Already up-to-date.
```

**Comment by Maingron** [comment]
I ended up reinstalling Mailcow. Thank you.
