### ISSUE TITLE
Use INDEXPVT instead of INDEX for shared mailboxes (per-user \Seen flags)

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#2712]
**Is your feature request related to a problem? Please describe.**
Currently shared mailboxes use a shared \Seen flag, meaning that if multiple users access them, the first one who views a mail will also mark it read for everyone else who access it.

**Describe the solution you'd like**
Use `INDEXPVT` instead of `INDEX` in the shared mailbox configuration as mentioned in https://wiki.dovecot.org/SharedMailboxes/Shared.

**Comment by hopfe156** [comment]
It looks like that the docker-entrypoint.sh overrides the "shared_namespace.conf" on every restart. So local changes aren't possible. 

Maybe you create the file only if it doesn't exists, instead from overriding it on container restart.

**Comment by lbeltrame** [comment]
Still the case in recent mailcow (not pushing, just trying to make sure this isn't closed as stale).

**Comment by andryyy** [comment]
I preferred it this way tbh.
