### ISSUE TITLE
Prevent Creation of mailbox when domain Quota is full

### ISSUE THREAD

**Issue by DaemonF0rge** [mailcow/mailcow-dockerized#2713]
Hello, just started using Mailcow and I love it just noticed one thing not sure if it's on purpose but if a domains quota is fully distributed to other mailboxes it still allows mailboxes to be created with 0mb quote, which a 0mb quota seems to mean an unlimited quota(if im wrong please correct me). Not sure how that would work if all other mailboxes were full in regard to maintaining integrity for a domain quota.

But to my point, as a feature request, I'd like to see a feature where it could prevent more mailboxes from being created while there is a 0mb quota available in the domain. 

Thank you,

**Comment by andryyy** [comment]
Hi, I know it's kind of stupid, but this was a requested feature. 
A domain admin does not have the rights to create a new mailbox with unlimited quota, so this would be fine. You'd need to grant him access.
If we change it to "only allow to set unlimited quota when domain is not full", you could leave 1 M free and create unlimited mailboxes anyway.

Besides said domain admin restriction, we could add a feature to disable unlimited quota altogether. What do you think?

**Comment by Braintelligence** [comment]
+1 for option disabling unlimited quota

**Comment by DaemonF0rge** [comment]
Yeah that makes sense to me.
+1 for option disabling unlimited quotas
