### ISSUE TITLE
Use mailcow as an (authenticated) smarthost / SMTP-Relay

### ISSUE THREAD

**Issue by vizion8-dan** [mailcow/mailcow-dockerized#2715]
Hi,

**this is not at all an issue with mailcow-dockerized but with me.** Sorry for that! 

I am trying to use my lovely mailcow-dockerized to provide some kind of an authenticated smarthost / SMTP-relay for an elderly Exchange server (sitting on a fixed IP, provider range, which constantly gets/keeps blacklisted).

I assume a similar background scenario as @Arkaniod described here: https://github.com/mailcow/mailcow-dockerized/issues/2301 - **but how do I configure this with my mailcow?**

I am confused around "routing" but this seems to provide an upstteam smarthost TO mailcow-dockerized itself? Were do I set up the credentials and the settings to allow this authenticated relaying? 

Thanks for any help with this

**Comment by Arkaniod** [comment]
Hi vizion8-dan,

the following solution works perfect for smaller enviroments, if you have not too many mailboxes/users (~5-10, typical small business).

I configured one user (for example admin@domain.tld) to be allowed to send as all the other users from that domain. You can find that setting in the mailcow UI in the mailbox configuration ("Allow to send as"). 

In Exchange configure the send-connector pointing to your cow as smarthost. Use port 587 and credentials for that one special mailbox which is allowed to send as other users - voilá, should work.

If you plan to use the cow only as smarthost - don't forget to include in the domain's spf-policy

**Comment by vizion8-dan** [comment]
Hi Arkaniod, thanks a lot for your help with that! That makes the process a lot more transparent for me ;-) 

I made the corresponding setting in "Edit mailbox:" -> "Allow to send as:", set to "`my-dummy-relay@somedomain.tld, Disable sender check for domain * (+alias domains)`". Underneath the field is a small red note saying: `Sender check is disabled`. 

What still keeps unclear for me:

* Currently I intended to use an existing user from another domain for relaying: relay@somedomain.tld is from another domain than the domain it should allow relaying (exchangedomain.tld). In your example I suppose you have the same domain on Exchange also on the cow? Is this necessary? The UI seems unclear to me: `Disable sender check for domain * (+alias domains)` seems like "`*`" (any domain - no checks?) and the red `Sender check is disabled` so, if authenticated I could send as **any** domain? Or do i have to recreate the domains I want to allow relaying on the cow with only the new "relay" user inside?
* Or: Is a domain alias needed for the domain i want to relay for in my existing somedomain.tld?

Again, thanks a ton for any help with this!

**Comment by Arkaniod** [comment]
`Disable sender check for domain * (+alias domains)`
I haven't activated this, only the corresponding e-mail addresses. And i'm also not sure, what this exactly means. Perhaps @andryyy can explain?

`In your example I suppose you have the same domain on Exchange also on the cow?`
No, the domains are different. For Exchange an unofficial ".local"-domain is used, Exchange users have mailaddresses from the official "external" domain. Mails are polled from the cow into Exchange and Exchange uses the cow as smarthost. The cow is also the official mx for that domain(s) in DNS. Typical setup for MS SBS.

`Exchange server (sitting on a fixed IP, provider range, which constantly gets/keeps blacklisted)`
I suppose, the Exchange server is the mx in DNS?

General question: about how many users in Exchange do we talk?

**Comment by vizion8-dan** [comment]
> `Disable sender check for domain * (+alias domains)`
> I haven't activated this, only the corresponding e-mail addresses. And i'm also not sure, what this exactly means. Perhaps @andryyy can explain?

Okay.  
_Seems_ my setup works so far (after short tests) and `Disable sender check for domain * (+alias domains)` allows authenticated relaying for "exchangedomain.tld" without setting an alias domain for exchangedomain.tld in the mailcow-domain providing the "relay"-user.

> `In your example I suppose you have the same domain on Exchange also on the cow?`
> No, the domains are different. For Exchange an unofficial ".local"-domain is used, Exchange users have mailaddresses from the official "external" domain. Mails are polled from the cow into Exchange and Exchange uses the cow as smarthost. The cow is also the official mx for that domain(s) in DNS. Typical setup for MS SBS.
> 

Yeah, I remember those SBS installations.

> `Exchange server (sitting on a fixed IP, provider range, which constantly gets/keeps blacklisted)`
> I suppose, the Exchange server is the mx in DNS?

Yes, it is. And it used to have no smarthost at all as it is on a static IP. But this does not work so there was a provider based smarthost which I now try to replace by mailcow. 

> General question: about how many users in Exchange do we talk?

Around 20, with only around 5 heavy users.

Thank you for your help sorting this out!

**Comment by Arkaniod** [comment]
No problem, you are welcome.

Don't forget to include your cow in the spf-record

**Comment by madic-creates** [comment]
Is it possible to use mailcow as an unauthenticated smarthost, whitelist IP addresses? I've a few servers I would like to whitelist. I did configure the postfix mynetworks configuration but rspamd also requires some adjustment. Mails get blocked by the DMARC_POLICY_REJECT rule

**Comment by nightah** [comment]
@Madic- it absolutely is, having said that when it isn't authenticated said emails in question all will be subject to checks via rspamd etc.

Have you perhaps considered creating a single account as a "relay" for example `relay@example.com` and using that as your authenticated source for a smarthost?

**Comment by madic-creates** [comment]
@nightah That's the way I do it now, generic credentials which are allowed to send for every domain.

But how can I configure rspamd to ignore checks?
I've created a new settings map with the following content:
```
type = "ip";
prefilter = true;
map = "/${LOCAL_CONFDIR}/custom/ip_whitelist.map";
action = "accept";
```
And entered every needed IP address in the ip_whitelist.map

**Comment by andryyy** [comment]
You can disable checks for authenticated users in an Rspamd settings map. If you click to create a map (in mailcow UI, as admin), you will find the preset "skip all but dkim bla".

**Comment by alfonsrv** [comment]
> * [...] so, if authenticated I could send as **any** domain? Or do i have to recreate the domains I want to allow relaying on the cow with only the new "relay" user inside?

To anybody else stumbling upon this with the same question, which remained unanswered – it is indeed possible to relay over **any** domain that way, meaning domains don't have to be added to Mailcow explicitly.
