### ISSUE TITLE
Mailcow not Reciving Emails

### ISSUE THREAD

**Issue by Absenzium-Mirror** [mailcow/mailcow-dockerized#2717]
Hey, 

last night i installed MailCow, worked fine. The Probelm is that i can send Email but not recieve them. 

In RSpamd are the Mails visible an Tagged with no action. 

But neither in SOGO nor in Outlook / Thunderbird are the Mails visible. 

Further information (where applicable):
- Ubuntu 18.04 LTS
- KVM 
- 8gb Ram / 4 CPUs / 80gb HDD

**Comment by ghost** [comment]
Hello,
I have the same problem
rspamd - no_action
sieve: pipe action: piped message to program `rspamd-pipe-spam'
sieve: left message in mailbox 'Junk'

**Comment by andryyy** [comment]
@Absenzium-Mirror Check if you have set "Relay Domain" in the domain settings. Remove it.

**Comment by andryyy** [comment]
@MZemlyakov Probably checked "learn msg as spam" when you created the alias.

**Comment by ghost** [comment]
> @MZemlyakov Probably checked "learn msg as spam" when you created the alias.

No, this is not a alias, and not spam 100%. Problems appeared after the update.
Rspamd score -2034.50/15 - NO_ACTION 
MAILCOW_WHITE (-1998)
MAILCOW_AUTH (-20)
BAYES_HAM (-12.5) [100.00%]
REPLY (-4)
MIME_BASE64_TEXT (0.1)
MIME_GOOD (-0.1) [multipart/related,multipart/alternative,text/plain]
DYN_RL_CHECK (0)
ARC_SIGNED (0) [i=1]
TO_DN_ALL (0)
RCPT_MAILCOW_DOMAIN (0) [somedomain.ru]
MIME_TRACE (0) [0:+,1:+,2:+,3:~,4:~]
MID_RHS_MATCH_FROM (0)
DKIM_SIGNED (0)
TO_DOM_EQ_FROM_DOM (0)
ARC_NA (0)
FROM_NO_DN (0)
RCVD_COUNT_ZERO (0) [0]
RCPT_COUNT_ONE (0) [1]
FROM_EQ_ENVFROM (0)
TO_MATCH_ENVRCPT_ALL (0)
MAILCOW_DOMAIN_HEADER_FROM (0) [somedomain.ru]
ASN (0) [asn:39376, ipnet:some_network/24, country:RU]

**Comment by andryyy** [comment]
The msg is moved to Junk manually. Probably done by a "smart" mail client or a sieve script.

Rspamd is not even able to move a mail from * to Junk or somehow trigger a sieve action.

**Comment by ghost** [comment]
Sieve moves emails to spam. Only SOGO is used.

**Comment by ghost** [comment]
We did not add any scripts for the sieve. Problems appeared after the update.

**Comment by andryyy** [comment]
Only mails with "X-Spam-Flag" header are moved to Junk. Just like they were moved since mailcow 0.2 or something like that. :) So it has not changed for years.

Sorry.
