### ISSUE TITLE
Profile download for iOS not possible

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#2718]
**Describe the bug, try to make it reproducible**
I changed the ports in mailcow.conf to 8081 (HTTP) and 1443 (HTTPS). When I am trying  to download the Profile following url is called:

`https://(replaced domain):1443:1443/mobileconfig.php`

**System information:**

 - Ubuntu 18.04 LTS
 - Proxmox
 - 30 GB Ram 8 cores
 - Docker version 18.09.6, build 481bc77
 - docker-compose version 1.24.0, build 0aa59064

**Comment by mkuron** [comment]
Good catch. Could you please submit a pull request?

**Comment by mkapra** [comment]
Hi, I am new here. What do I have to select on the Pull request?

**Comment by mkapra** [comment]
No reactions anymore? @mkuron

**Comment by mkuron** [comment]
The easiest way would be to just click the edit button on https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/mobileconfig.php.

**Comment by mkapra** [comment]
@mkuron 
I'am not that fit in PHP but is the problem really in mobileconfig.php? This site is called and there is the error with the multiple ports in the url.

**Comment by mkuron** [comment]
Ah, sorry. Here is the actual place: https://github.com/mailcow/mailcow-dockerized/blob/f460600a4d8ff5439f946687f588742d7632254b/data/web/user.php#L80. You need to strip the port number from HTTP_HOST.

**Comment by Braintelligence** [comment]
I went ahead and created a PR for you @mkapra I hope that's alright with you. @mkuron please do check if my proposal is alright; I'm not super experienced with PHP.

**Comment by Braintelligence** [comment]
@mkapra Can you confirm that your issue is solved with this merge? Run update.sh and check if your issue is solved.

**Comment by mkapra** [comment]
[https://mailcow.github.io/mailcow-dockerized-docs/client/client-apple/]

There is the problem. I ran an update but it did not work.
Both options have the same problem.
@Braintelligence

**Comment by mkapra** [comment]
@Braintelligence 
anything new here?

**Comment by Braintelligence** [comment]
I don't know. I provided code for @mkuron suggestion. Maybe he has another idea.

**Comment by mkuron** [comment]
Could you please post the link to the client configuration page (feel free to anonymize the domain name)? Just want to make sure that it does not contain the port number twice.

**Comment by mkapra** [comment]
This is the link:
https://mailcow.github.io/mailcow-dockerized-docs/client/#host=host&email=mailaddress&name=myname&ui=domain%3A1443&port=1443&outlookEAS=1

I think the problem is, that in the ui option the port is also in there.

@mkuron

**Comment by mkapra** [comment]
https://github.com/mailcow/mailcow-dockerized/blob/83136c787645016d9c7afe16208038a77c044411/data/web/user.php#L80

@mkuron  from where is the $mailcow_hostname variable coming?

**Comment by mkapra** [comment]
@mkuron Can you review my solution? I think it could work.
