### ISSUE TITLE
Outlook und die Ressourcen

### ISSUE THREAD

**Issue by dominicpratt** [mailcow/mailcow-dockerized#2719]
Hi Leute,

ich habe heute von einem Kunden eine Rückmeldung zu Mailcow bekommen und weiß gerade nicht genau, wo ich ansetzen soll. Ich zitiere:

> Wollte nur kurz Bescheid sagen, dass es mit den Outlook-Besprechungen immer noch Probleme gibt. Ich habe schon mehrfach versucht, das Konferenzzimmer für Kundentelefonate zu reservieren. Ich lade konferenzzimmer@example.org als Besprechungsteilnehmer ein und verschicke die Einladung. Für ein paar Sekunden wird die Besprechung dann auch im Kalender des Konferenzzimmers angezeigt, kurz darauf verschwindet sie aber wieder von dort. Die Einladung hängt dann immer im Postausgang fest. Das Problem haben auch einige andere Kollegen.

Hat jemand eine Idee, wo man hier anfassen könnte?

Bin für jede Hilfe dankbar. :)

**Comment by andryyy** [comment]
Wieso immer noch? Habe keine nachvollziehbaren Probleme. :/

Und please try to keep it English.

It is quite possible that you are overbooking a resource. Depends on many factors.

If you think it is a bug, try to make it reproducible. From the very beginning to the point it does not accept the invitation.

**Comment by Braintelligence** [comment]
No news is good news.
