### ISSUE TITLE
Quarantine - Maximum age in days

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#2721]
Hi,

  I would like to ask what exactly means the "Maximum age in days" at Quarantine settings? I've the following settings, but in the Quarantine I have messages older then 2 months.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/16578737/59968851-0e7d0d00-9541-11e9-875a-9f515a7bd670.png">

  Kind Regards,
Zoltan

**Comment by andryyy** [comment]
Hi Zoltan,

My bad! Thanks for your report, will be fixed in a bit.

//Edit: Fixed in the next Dovecot image, please give me time until tomorrow (Berlin) to push.

**Comment by beckzg** [comment]
Thank you Andryyy, great news, so that option means that after the maximum age the mails are deleted from the quarantine?

**Comment by andryyy** [comment]
Yes. :)
