### ISSUE TITLE
ActiveSync notes synchronization

### ISSUE THREAD

**Issue by immanuelfodor** [mailcow/mailcow-dockerized#2723]
**Is your feature request related to a problem? Please describe.**
I tried out [Nine](https://play.google.com/store/apps/details?id=com.ninefolders.hd3&hl=en) with ActiveSync connecting to a mailcow-dockerized instance, and it works great!

However, there is a small annoyance, the app says the server doesn't support syncing notes which would be indeed a desirable feature to leave Google Keep behind.

![Screenshot_20190624-065313](https://user-images.githubusercontent.com/21174107/59992587-d8c54a80-964c-11e9-88c0-b2d86546ebfa.jpg)

**Describe the solution you'd like**
I would like to have the notes syncing feature working over ActiveSync even if there is no web interface to access them. There is a [feature request](https://sogo.nu/bugs/view.php?id=4369) open for SOGo but I can imagine we don't need to wait for them. Is it possible to add a new notes-supporting docker container to the compose file, linking them together, and then adding a new Nginx location to support it? I might be able to do a PR if you point me to the right direction. Please advise with an explanation why it can't be done otherwise. 

**Additional context**
For example, [Kopano](https://demo.kopano.com) supports notes. How they do it?

**Comment by mkuron** [comment]
This feature is still missing in SOGo. There is no way to connect SOGo and Kopano together because EAS is more than just different URLs, sorry.

**Comment by immanuelfodor** [comment]
@mkuron thanks for the quick reply. I don't want to connect SOGo and Kopano, and I wrote that I'm aware notes are missing in SOGo. I asked about how could I make notes work in Android app Nine through ActiveSync with mailcow-dockerized - is there a third party tool which I could integrate to have notes sync? I could make another Nginx server/location to proxy there the notes, or anything like that. I would be happy even if there is no frontend to it on the web interface, just the mobile sync works. Or SOGo is the only way to have notes sync because ... (insert explanation here)?

**Comment by immanuelfodor** [comment]
Here is the MS-ASNOTE protocol description, this is pure XML, I imagine there are other tools out there that are capable handling it. SOGo can do its thing with all other supported sync items in mailcow-dockerized, but maybe another tool can live besides it to handle only notes. Would it be possible to do such? If not, why? 
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-asnote/21801d6c-000e-413c-8591-50430a8e9fd9

**Comment by mkuron** [comment]
That's the payload, inside the EAS XML requests. You would need to write a proxy that reads the XML and distributes requests accordingly, manage the combined sync state, etc. Essentially you would write half an EAS server.

**Comment by immanuelfodor** [comment]
Okay, so it doesn't work like `/contacts` is handled by SOGo and `/notes` is by app X sharing the same `/auth` endpoint but with different payload schema on each endpoints. Thank you for the explanation, I can accept it then that we need to wait for SOGo support notes later.

**Comment by danbo** [comment]
> For example, [Kopano](https://demo.kopano.com) supports notes. How they do it?

It looks like they are using z-push. https://wiki.z-hub.io/display/ZP/Compatibility
