### ISSUE TITLE
Documentation on reverse proxy is not clear enough for beginners

### ISSUE THREAD

**Issue by dawoodjee** [mailcow/mailcow-dockerized#2725]
I'm facing 3 problems on this page https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

1. I don't know which files to edit when given told to modify nginx and apache configs. This is not specified. 

2. Do I need to do Apache then Nginx then Haproxy or just pick one method? I haven't guessed.

3. Should I install Nginx or Apache on the Host machine?

Help will be appreciated.

**Comment by dawoodjee** [comment]
Figured it out:

Start by installing one server on the host machine, whichever you're comfortable with (question 3). Then modify its default config file (question 1).

Question 2. One server is enough.

**Comment by dawoodjee** [comment]
Updated the docs 

https://github.com/mailcow/mailcow-dockerized-docs/pull/156

**Comment by andryyy** [comment]
You should not copy and paste a reverse proxy config. It depends on your setup. I think it's already very detailed.

You should not do this if you didn't understand fundamental techniques in use. :/ Do some tests internally or ask on IRC etc.
