### ISSUE TITLE
Netfilter TypeError in server.py

### ISSUE THREAD

**Issue by mnin** [mailcow/mailcow-dockerized#2726]
**Describe the bug, try to make it reproducible**
Netfilter occurs this error, after restarting it.

**System information and quick debugging**
```
netfilter-mailcow_1  | Exception in thread Thread-4:
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
netfilter-mailcow_1  |     self.run()
netfilter-mailcow_1  |   File "/usr/lib/python3.6/threading.py", line 864, in run
netfilter-mailcow_1  |     self._target(*self._args, **self._kwargs)
netfilter-mailcow_1  |   File "/server.py", line 379, in autopurge
netfilter-mailcow_1  |     if bans[net]['attempts'] >= MAX_ATTEMPTS:
netfilter-mailcow_1  | TypeError: '>=' not supported between instances of 'int' and 'str'
```

Further information (where applicable):
 - Debian 9
 - docker 18.09.6
 - docker-compose 1.24.1

**Comment by andryyy** [comment]
I just pushed an update, can you please retry with the latest image of netfilter-mailcow?

@Kraeutergarten any idea?

What does `docker-compose exec redis-mailcow redis-cli get "F2B_OPTIONS"` return? Did you use the API?

**Comment by mnin** [comment]
@andryyy thanks for your quick answer.

```docker-compose exec redis-mailcow redis-cli get "F2B_OPTIONS"``` returns:

```"{\"ban_time\": \"86400\", \"netban_ipv6\": \"64\", \"netban_ipv4\": \"24\", \"retry_window\": \"600\", \"max_attempts\": \"3\"}"```

I've never used the API before.

Your last changes seem to fix the problem by converting the values as expected, thank you!

**Comment by Kraeutergarten** [comment]
This should fix the issue. I will look for a smarter solution. 

PS: Sorry for the late response. This mail was marked as spam.

The json is wrong formatted.

```
"{\"ban_time\": \"86400\", \"netban_ipv6\": \"64\", \"netban_ipv4\": \"24\", \"retry_window\": \"600\", \"max_attempts\": \"3\"}"
```

```
"{\"ban_time\":3600,\"netban_ipv4\":32,\"netban_ipv6\":64,\"max_attempts\":5,\"retry_window\":600}"
```

Try to safe failban options again.
