### ISSUE TITLE
Any way to use Proxmox Mail Gateway with Mailcow?

### ISSUE THREAD

**Issue by marrobHD** [mailcow/mailcow-dockerized#2727]
Any way to use Proxmox Mail Gateway with Mailcow. What I have to configure?
Thanks
~Marlon

**Comment by Adorfer** [comment]
What do you want to accomplish? "Some way": Certainly. 
What is the setup you have in mind? How are roles split and does the additional benefit outperforms the more compliated maintenance of 2 systems which have to be kept in sync in some of the other way.

**Comment by andryyy** [comment]
Yep. Would be hard to maintain. But could work somehow.

**Comment by mkuron** [comment]
Duplicate of #1172.
