### ISSUE TITLE
Problem with Nginx rspamd configuration

### ISSUE THREAD

**Issue by TastaMax** [mailcow/mailcow-dockerized#2731]
When I start Docker, the following error messages come to Ngnix

nginx-mailcow_1      | 2019/06/27 21:11:33 [emerg] 13#13: host not found in upstream "rspamd" in /etc/nginx/conf.d/site.conf:135
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "rspamd" in /etc/nginx/conf.d/site.conf:135

How can I solve this problem? The configuration file was created via generate_config.sh

**Comment by TastaMax** [comment]
The problem has resolved itself. The service took longer to start.

**Comment by andryyy** [comment]
It can happen if Rspamd was not yet available when Nginx started. It will retry until the upstream is available. That's one of the advantages of running it in Docker. :)

**Comment by ntimo** [comment]
@andryyy What do you think about using in the nginx config? This would resolve rspamd via DNS and fix NGINX not being able to start when rspamd is not up yet.
```
    resolver 127.0.0.11 valid=30s;
    set $upstream rspamd:11334;
    proxy_pass       http://$upstream/;
```

**Comment by andryyy** [comment]
See docker-compose.yml, the checks are here. We could use a port check instead of a ping. But I'm not sure, it restarts anyway.
