### ISSUE TITLE
Why is it possible to send Email with wrong/no password on localhost?

### ISSUE THREAD

**Issue by w3hr** [mailcow/mailcow-dockerized#2732]
I have an website where im using a mailcow client, i send an email over smtp and set wrong credentials for this account. the email will send though, also with wrong credentials. 

is this only possible on localhost ?

**Comment by Braintelligence** [comment]
`is this only possible on localhost ?`
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/main.cf#L9
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/main.cf#L13
http://www.postfix.org/BASIC_CONFIGURATION_README.html
https://serverfault.com/questions/457895/allow-sending-mail-without-authentication

**Comment by andryyy** [comment]
The connection is probably seen from 172.

**Comment by w3hr** [comment]
@Braintelligence thank u
@andryyy Yes

I changed the config and now its telling me : Jun 28 12:25:31 mail postfix/smtpd[368]: NOQUEUE: reject: RCPT from unknown[172.22.1.1]: 554 5.7.1 <user@mail.com>: Relay access denied

But only on localhost by using ssl on port 25, from remote on another port i can send without problems.

**Comment by Braintelligence** [comment]
Well it certainly would help if you showed your config.
