### ISSUE TITLE
clamd bootstrap script throwing errors after update

### ISSUE THREAD

**Issue by fbcd4f50ea5350f051450323b5abfd0b** [mailcow/mailcow-dockerized#2733]
After updating today with the update.sh script, the clamd container throws the following errors:

https://pastebin.com/mWqNrqE8

Seems like the issue has been introduced in commit 39f95b82841da34d33b9b03dd7fce19394ce7046
To me it looks like the CE variable is always empty.

**Comment by Braintelligence** [comment]
Is this related to #2746?

**Comment by andryyy** [comment]
Fixed in master: https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/clamd/bootstrap.sh

CE was indeed empty.

**Comment by fbcd4f50ea5350f051450323b5abfd0b** [comment]
Btw. did you mean to do a chmod instead of a chown in line number 66 of the same script? There's no user with that ID in the container.

**Comment by andryyy** [comment]
:-D Yes. Thanks!

Edit: That's something I added as test, because in some strange cases the 755 was lost on the directory. So it is not critical, but still sucks.
