### ISSUE TITLE
Sync jobs authentication error

### ISSUE THREAD

**Issue by billy995** [mailcow/mailcow-dockerized#2734]
I set up a sync job in preparation to migrate my Google mail to my own server.

I have confirmed the setting are correct and that the credentials are correct in the mailcow.imapsync table. I have also connected manually using another tools and the same credentials and it connect without any issue.

I used the original imap settings from google https://support.google.com/mail/answer/7126229?hl=en

The error message I am getting is as follows:

Docker context detected with /.dockerenv
Changing current directory to /var/tmp/
Here is imapsync 1.937 on host mail.billmeier.ovh, a linux system with 1.8/5.7 free GiB of RAM
with Perl 5.24.1 and Mail::IMAPClient 3.38
Transfer started at Fri Jun 28 08:38:02 2019
PID is 17382 my PPID is 17372
Load is 0.04 0.11 0.15 1/662 on 4 cores
Current directory is /var/tmp
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.937 $ $Date: 2019/05/01 22:14:00 $ 
Command line used, run by /usr/bin/perl:
/usr/local/bin/imapsync --tmpdir /tmp --nofoldersizes --exclude (?i)spam|(?i)junk --delete2duplicates --subscribeall --automap --skipcrossduplicates --ssl1 --host1 imap.gmail.com --user1 my-mail@gmail.com --passfile1 /tmp/imapsync.Urh78rf --port1 993 --host2 localhost --user2 my-mail@mydomain.de*f4n2gmu5xjcbz1zb@mailcow.local --passfile2 /tmp/imapsync.It1aHDD --no-modulesversion --noreleasecheck
Temp directory is /tmp ( to change it use --tmpdir dirpath )
kill -QUIT 17382 # special behavior
kill -TERM 17382 # special behavior
kill -INT 17382 # special behavior
kill -HUP 17382 # special behavior
No variable pid_filename
PID file is unset ( to set it, use --pidfile filepath ; to avoid it use --pidfile "" )
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Host2: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe ) 
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 "SSL_verify_mode=0", meaning for host1 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host1: Use --sslargs1 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host1
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host2
Info: will act as --uidexpunge2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: IMAP server [imap.gmail.com] port [993] user [my-mail@gmail.com]
Host2: IMAP server [localhost] port [993] user [my-mail@mydomain.de*f4n2gmu5xjcbz1zb@mailcow.local]
Host1: connecting and login on host1 [imap.gmail.com] port [993] with user [my-mail@gmail.com]
Host1 IP address: 108.177.15.108
Host1 banner: * OK Gimap ready for requests from XXX.XXX.XXX.XXX x196mb56470103wmf
Host1 capability before authentication: IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
Host1 failure: Error login on [imap.gmail.com] with user [my-mail@gmail.com] auth [LOGIN]: 2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
Exiting with return value 16

**Comment by Braintelligence** [comment]
Are you using 2FA on your Google account?

**Comment by billy995** [comment]
No it's disabled

**Comment by andryyy** [comment]
Allow "insecure apps".

**Comment by billy995** [comment]
I thank you all for your quick help it was allow insecure apps from google security config
