### ISSUE TITLE
Running multiply instance on one host SOLUTION

### ISSUE THREAD

**Issue by gmarke** [mailcow/mailcow-dockerized#2739]
Hi,

I just need to run two instances of mailcow-dockerized on one host(please skip discussion why etc,.. just need) and this is possible by binding necessary ports to some address, changing project name to some custom name, override some network settings and .. there is one problem that is blocking.

in php-fpm entry point file in line 35 there is getting container ID and in case there is multiply mysql containers with name mysql-mailcow (this is when you have two projects or more) it come filanny to make string with multiply id's concatenated with space when as next there is check if string is only numbers and like this container did not start properly.

To solve this, please change line 35 to something like this:
CONTAINER_ID=$(curl --silent --insecure https://dockerapi/containers/json | jq -r ".[] | {project: .Config.Labels[\"com.docker.compose.project\"], name: .Config.Labels[\"com.docker.compose.service\"], id: .Id}" | jq -rc "select( .name | tostring | contains(\"mysql-mailcow\")) | select( .project == \"$COMPOSE_PROJECT_NAME\") | .id" 2> /dev/null)

this is solving the problem and container starting correctly..

**Comment by mkuron** [comment]
Looking at that line in the entrypoint, it does indeed seem to me like there should be a filter for `$COMPOSE_PROJECT_NAME`. Please submit a pull request for https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/phpfpm/docker-entrypoint.sh.

**Comment by andryyy** [comment]
Not sure. I mean, it doesn't hurt to add it. But there are other things you'd struggle with. The netfilter-mailcow implementation is - for example - not able to work like this. Probably more.

Doesn't make much sense unless we change everything else, too. Feel free to create a PR.

**Comment by gmarke** [comment]
I will try to add it tomorrow and will send pull request.
As you clearly mentioned is not possible to hurt with adding this and I my case by changing project name, adding to snat and binding ports to external address I managed to have two instances(I didn't test it but I think is now not limited to only two) working stable for last few days so I think it really worth to have it included.
