### ISSUE TITLE
CSRF violation on Admin Login

### ISSUE THREAD

**Issue by Dennis14e** [mailcow/mailcow-dockerized#274]
I got the error message "CSRF violation" when I tried to log in as admin.
I assume that this occurred because the file "csrfprotector.js" could not be loaded.
In the HTML code, the domain name is the DNS name of the mail server, but not the web server (I use nginx as a proxy with a different hostname).
I think the link in the HTML code should be a relative rather than an absolute path.

**Expectation 1:**
`<input type="hidden" id="csrfp_hidden_data_token" value="MAILCOW_CSRF">
<input type="hidden" id="csrfp_hidden_data_urls" value='[]'><script type="text/javascript" src="https://mailcow.example.com:443/inc/lib/vendor/owasp/csrf-protector-php/js/csrfprotector.js"></script>`

**Expectation 2:**
`<input type="hidden" id="csrfp_hidden_data_token" value="MAILCOW_CSRF">
<input type="hidden" id="csrfp_hidden_data_urls" value='[]'><script type="text/javascript" src="/inc/lib/vendor/owasp/csrf-protector-php/js/csrfprotector.js"></script>`

**Reality:**
`<input type="hidden" id="csrfp_hidden_data_token" value="MAILCOW_CSRF">
<input type="hidden" id="csrfp_hidden_data_urls" value='[]'><script type="text/javascript" src="https://mail.example.com:443/inc/lib/vendor/owasp/csrf-protector-php/js/csrfprotector.js"></script>`

**Comment by andryyy** [comment]
Is fixed, we omit the hostname now.

**Comment by Dennis14e** [comment]
Hm.. The file can now be loaded, but I get the error message anyway.

**Comment by hardoverflow** [comment]
Same issue here.

**Comment by chriscroome** [comment]
I also have this issue, the URL is now relative to the root:

```html
<input type="hidden" id="csrfp_hidden_data_token" value="MAILCOW_CSRF">
<input type="hidden" id="csrfp_hidden_data_urls" value='[]'><script type="text/javascript" src="/inc/lib/vendor/owasp/csrf-protector-php/js/csrfprotector.js"></script>
```

But still I get *"CSRF violation"* when I try to login.

**Comment by andryyy** [comment]
I can finally reproduce it and will fix it now! Sorry guys...

**Comment by andryyy** [comment]
I switched to a simpler CSRF protection. But it turns out the previous error was due to caching issues.

Clean your cache completly (!!) and restart the browser. You used 5 different browsers? Then clean all caches properly.
