### ISSUE TITLE
Lets Encrypt renewal fail?

### ISSUE THREAD

**Issue by MrUnknownDE** [mailcow/mailcow-dockerized#2740]
Hello,

Due to the fact that my Let's Encrypt certificate has expired, I can not control the web interface anymore. I have changed nothing on the system but the system does not require a new certificate.

System:
Debian 9.9
Dedicated server
updated 5 minutes ago

Yours sincerely
Johannes K. | MrUnknownDE

**Comment by MrUnknownDE** [comment]
In other words, no Let's Encrypt certificate is created.
Screenshots: [https://lauu.ch/io](https://lauu.ch/io)

**Comment by andryyy** [comment]
Check https://github.com/mailcow/mailcow-dockerized/issues/2736 :) 

Also always post logs, please.

**Comment by MrUnknownDE** [comment]
Docker-Logs(but 2mb Log data):https://lauu.ch/iq

Mailcow.conf

------------------------------
mailcow web ui configuration
------------------------------
example.org is _not_ a valid hostname, use a fqdn here.
Default admin user is "admin"
Default password is "moohoo"

MAILCOW_HOSTNAME=cp.johanneskr.de

------------------------------
SQL database configuration
------------------------------

DBNAME=mailcow
DBUSER=mailcow

Please use long, random alphanumeric strings (A-Za-z0-9)

DBPASS=xxx
DBROOT=xxx

------------------------------
HTTP/S Bindings
------------------------------

You should use HTTPS, but in case of SSL offloaded reverse proxies:

HTTP_PORT=80
HTTP_BIND=xxx

HTTPS_PORT=443
HTTPS_BIND=xxx

------------------------------
Other bindings
------------------------------
You should leave that alone
Format: 11.22.33.44:25 or 0.0.0.0:465 etc.
Do _not_ use IP:PORT in HTTP(S)_BIND or HTTP(S)_PORT

SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
DOVEADM_PORT=127.0.0.1:19991
SQL_PORT=127.0.0.1:13306

Your timezone

TZ=Europe/Berlin

Fixed project name

COMPOSE_PROJECT_NAME=mailcowdockerized

Garbage collector cleanup
Deleted domains and mailboxes are moved to /var/vmail/_garbage/timestamp_sanitizedstring
How long should objects remain in the garbage until they are being deleted? (value in minutes)
Check interval is hourly

MAILDIR_GC_TIME=1440

Additional SAN for the certificate

You can use wildcard records to create specific names for every domain you add to mailcow.
Example: Add domains "example.com" and "example.net" to mailcow, change ADDITIONAL_SAN to a value like:
ADDITIONAL_SAN=imap.*,smtp.*
This will expand the certificate to "imap.example.com", "smtp.example.com", "imap.example.net", "imap.example.net"
plus every domain you add in the future.

You can also just add static names...
ADDITIONAL_SAN=srv1.example.net
...or combine wildcard and static names:
ADDITIONAL_SAN=imap.*,srv1.example.com


ADDITIONAL_SAN=cp.johanneskr.de

Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n

SKIP_LETS_ENCRYPT=n

Skip IPv4 check in ACME container - y/n

SKIP_IP_CHECK=y

Skip ClamAV (clamd-mailcow) anti-virus (Rspamd will auto-detect a missing ClamAV container) - y/n

SKIP_CLAMD=n

Enable watchdog (watchdog-mailcow) to restart unhealthy containers (experimental)

USE_WATCHDOG=n

Send notifications by mail (no DKIM signature, sent from watchdog@MAILCOW_HOSTNAME)
Can by multiple rcpts, NO quotation marks

WATCHDOG_NOTIFY_EMAIL=a@example.com,b@example.com,c@example.com
WATCHDOG_NOTIFY_EMAIL=

Max log lines per service to keep in Redis logs

LOG_LINES=9999

Internal IPv4 /24 subnet, format n.n.n. (expands to n.n.n.0/24)

IPV4_NETWORK=172.22.1

Internal IPv6 subnet in fc00::/7

IPV6_NETWORK=fd4d:6169:6c63:6f77::/64

Use this IPv4 for outgoing connections (SNAT)

SNAT_TO_SOURCE=

Use this IPv6 for outgoing connections (SNAT)

SNAT6_TO_SOURCE=

Create or override API key for web uI
You _must_ define API_ALLOW_FROM, which is a comma separated list of IPs
API_KEY allowed chars: a-z, A-Z, 0-9, -

API_KEY=
API_ALLOW_FROM=127.0.0.1,1.2.3.4

Set this to "allow" to enable the anyone pseudo user. Disabled by default.
When enabled, ACL can be created, that apply to "All authenticated users"
This should probably only be activated on mail hosts, that are used exclusivly by one organisation.
Otherwise a user might share data with too many other users.
ACL_ANYONE=disallow
Solr heap size, there is no recommendation, please see Solr docs.
Solr is a prone to run OOM on large systems and should be monitored. Unmonitored Solr setups are not recommended.
Solr will refuse to start with total system memory below or equal to 2 GB.
SOLR_HEAP=1024
Solr is disabled by default after upgrading from non-Solr to Solr-enabled mailcows.
Disable Solr or if you do not want to store a readable index of your mails in solr-vol-1.
SKIP_SOLR=n
MAILDIR_SUB defines a path in a users virtual home to keep the maildir in. Leave empty for updated setups.
MAILDIR_SUB=Maildir
MAILDIR_SUB=
ALLOW_ADMIN_EMAIL_LOGIN=n
SKIP_HTTP_VERIFICATION=n
Notify about banned IP. Includes whois lookup.
WATCHDOG_NOTIFY_BAN=y

**Comment by andryyy** [comment]
Check the acme-mailcow logs.

There are lines like...

```
[32macme-mailcow_1       |[0m Sat Jun 29 19:23:03 CEST 2019 - Cannot match your IP 123 against hostname asd.asd.de (1234)
```

You could set SKIP_IP_CHECK or set the correct SNAT IP in mailcow.conf.

**Comment by MrUnknownDE** [comment]
despite "SKIP_IP_CHECK" he still makes IPv4 checks

**Comment by andryyy** [comment]
See the docs. Run up -d after changing that.

**Comment by MrUnknownDE** [comment]
Thanks. It`s Work.
