### ISSUE TITLE
DNS Cache Poisoned

### ISSUE THREAD

**Issue by hobbsAU** [mailcow/mailcow-dockerized#2741]
I have a mailcow server running for just over 24hrs and the DNS cache in unbound seems to have been poisoned.

Checking DNS cache for poisoning using the following command:
`$ cd /opt/mailcow-dockerized; sudo docker-compose exec unbound-mailcow unbound-control dump_cache >~/unbound.cache`

Found one suspicious entry "redmonddc.com" with high TTL. I've masked out the domain, it is legitimate and resolves to its regular nameservers when queried from other hosts.
`$ cat ~/unbound.cache |grep redmonddc.com`
DOMAINMASKED.com.	140212	IN	NS	**ns1.redmonddc.com.**
DOMAINMASKED.com.	140212	IN	NS	**ns2.redmonddc.com.**
DOMAINMASKED.com.	139849	IN	NS	**ns1.redmonddc.com.**
DOMAINMASKED.com.	139849	IN	NS	**ns2.redmonddc.com.**

Looking at the unbound config I have added the following enhancements on my server and restarted the container:
/opt/mailcow-dockerized/data/conf/unbound/unbound.conf
```yaml
server:
  extended-statistics: yes
  unwanted-reply-threshold: 10000
  harden-glue: yes
```

I'm keeping an eye on unwanted replies in unbound:
`$ cd /opt/mailcow-dockerized; sudo docker-compose exec unbound-mailcow unbound-control stats_noreset |grep unwanted`

@andryyy I'm wondering if there is anything else we could do to guard against DNS cache poisoning? 

Would it be worthwhile adding these changes in the unbound config? Let me know if you agree and I'll submit a PR.

**Comment by andryyy** [comment]
I'm curious about your network environment, previous changes and how that could have happened. I don't see a chance to poison the cache easily. How can I reproduce it?

**Comment by andryyy** [comment]
I can seriously not think of any way this would be possible. 

Do you redirect DNS queries with a local firewall or something like that?

@mkuron Do you have a glue (heh)?

**Comment by hobbsAU** [comment]
> I'm curious about your network environment, previous changes and how that could have happened. I don't see a chance to poison the cache easily. How can I reproduce it?

Clean install of mailcow (downloaded 24hrs ago). Using Hetzner cloud and no firewall. unbound (prior to my changes) would query root servers for all domains it hasn't cached. This was working normally on the poisoned container except for the cached domains such as the domain above.

Dig worked normally on the poisoned container.. tcpdump validates DNS query going to root server and traversing NS's. E.g.
`$ dig www.google.com @172.22.1.254`

Naturally I cannot reproduce - I'm keeping an eye on the stats above to see if there are any other attempts. I think the settings I applied should limit exposure to the unwanted replies and also cross check glue.

**Comment by andryyy** [comment]
How do you poison (how are you sure it was poisoned?) unbound it its current version?
You might want to tell them about this, if you are sure.

Edit: I am not saying you are wrong! I just want to understand how you are sure this happened, how you interpreted the logs/cache etc. :)

"unwanted-reply-threshold: 10000" does not makes sense to me. How does it help here? Is it consistent to unbound recommendations?

Yes, unwanted replies can be logged, but it does not mean that unbound accepted them. It even logs them as unwanted. We cannot tell others to stop this (wish we could).

"harden-glue" is on by default.

**Comment by hobbsAU** [comment]
Thanks andryyy, appreciate you looking into these options.

> How do you poison (how are you sure it was poisoned?) unbound it its current version?
> You might want to tell them about this, if you are sure.
> Edit: I am not saying you are wrong! I just want to understand how you are sure this happened, how you interpreted the logs/cache etc. :)

:-) I'm not saying I'm correct either, cache poisoning seems to be the most likely explanation - unless anyone has a better idea? Perhaps the upstream NS were poisoned? The DOMAINMASKED.com is a .com so it would be either be the root or gtld servers or someone in between. Also the poisoned entry (redmonddc) seems to host some suspicious stuff: https://ransomwaretracker.abuse.ch/nameserver/ns1.redmonddc.com/
https://securitytrails.com/list/ns/ns1.redmonddc.com

What I am certain of is that incorrect NS records were cached for a specific domain. Please refer to my first post on how I determined that through querying the live unbound cache. All other domains were caching NS records properly. Live dig tests on the host OS against the cloud provider DNS, the unbound container and 8.8.8.8, resulted in accurate answers and caching when querying the unbound container. Also note, this was a fresh mailcow server running on Debian latest stable with no changes to mailcow apart from the mailcow.conf and ingesting multiple mailboxes. I've been running mailcow for over a year on other cloud providers and have never come across this issue.

> unbound it its current version?

unbound was downloaded as part of mailcow starting and is version 1.8.3. Note: the latest unbound available is 1.9.2. It appears many changes were made since 1.8.3 according to unbound release notes here: https://nlnetlabs.nl/projects/unbound/download/. There seem to be more unbound bugfixes than security fixes, perhaps I can bump the unbound version anyway? Do you accept alpine edge or must this be a specific alpine release such as 3.10 (unbound 1.9.1)?

```shell
$ cd /opt/mailcow-dockerized; sudo docker-compose exec unbound-mailcow unbound-checkconf -h
Usage:	unbound-checkconf [file]
	Checks unbound configuration file for errors.
file	if omitted /etc/unbound/unbound.conf is used.
-o option	print value of option to stdout.
-f 		output full pathname with chroot applied, eg. with -o pidfile.
-h		show this usage help.
Version 1.8.3
BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl
```


**How did I discover this in the first place?**
I was receiving MX lookup errors and queued mails for **one domain only** in mailcow logs. All other domains were able to send and receive emails without issue.

Here is the Delayed Mail warning from Mail Delivery System..
```
This is the mail system at host email.myemaildomain.com.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 4 hour(s).
It will be retried until it is 5 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<mail@DOMAINMASKED.com>: Host or domain name not found. Name service error for
   name=DOMAINMASKED.com type=MX: Host not found, try again
```

> "unwanted-reply-threshold: 10000" does not makes sense to me. How does it help here? Is it consistent to unbound recommendations?
> 
> Yes, unwanted replies can be logged, but it does not mean that unbound accepted them. It even logs them as unwanted. We cannot tell others to stop this (wish we could).


I got the idea from here: [Unbound DNS Tutorial](https://calomel.org/unbound_dns.html)
```
  # If nonzero, unwanted replies are not only reported in statistics, but also
  # a running total is kept per thread. If it reaches the threshold, a warning
  # is printed and a defensive action is taken, the cache is cleared to flush
  # potential poison out of it.  A suggested value is 10000000, the default is
  # 0 (turned off). We think 10K is a good value.
    unwanted-reply-threshold: 10000
```
Also the unbound man page suggests 10M as a value:
```
       unwanted-reply-threshold: <number>
              If set, a total number of unwanted replies is kept track  of  in
              every thread.  When it reaches the threshold, a defensive action
              is taken and a warning is printed to  the  log.   The  defensive
              action  is  to  clear  the  rrset  and message caches, hopefully
              flushing away any poison.  A value of 10 million  is  suggested.
              Default is 0 (turned off).
```

My understanding of this option is that it can be interpreted as a warning that someone is attempting a cache poisoning attack through flooding with unwanted replies. The cache is cleared once the threshold is reached as a precaution. This seems to be one possible explanation - also there are  metasploit examples on how to execute this attack however with random unbound source ports I believe this is much harder. I'm going to keep this one on the basis that it's an additional safeguard and set it to something more in line with unbound's recommendation.


> "harden-glue" is on by default.

I just removed the option and right you are.
```shell
$ cd /opt/mailcow-dockerized; sudo docker-compose exec unbound-mailcow unbound-checkconf -o harden-glue
yes
```

**Comment by Braintelligence** [comment]
@hobbsAU So basically setting `unwanted-reply-threshold: 10000` and perhaps upgrading unbound is your recommendation?

**Comment by hobbsAU** [comment]
@Braintelligence yes that's correct. I've been running an updated unbound 1.9.1 without issue.

If anyone else is interested you can update unbound by:

1. Changing the Alpine base to 3.10 in the unbound Dockerfile: 
```
$ sudo vim /opt/mailcow-dockerized/data/Dockerfiles/unbound/Dockerfile
```
2. Rebuilding the container and cleaning up the old one:
```
$ cd /opt/mailcow-dockerized; sudo docker-compose up -d --no-deps --build unbound-mailcow
$ sudo docker system prune
```

**Comment by andryyy** [comment]
Can you show a changelog where they fixed that? Cannot seem to find it. 

I doubt it was posited at all. 

I mean.... better safe than sorry, right? I will build it and add `unwanted-reply-threshold: 10000`

**Comment by hobbsAU** [comment]
Yes just precautionary measures. 

The unbound 1.9.1 changelog seems to contain a few unrelated bugfixes so I thought it best to version bump.
