### ISSUE TITLE
Disable rspamd

### ISSUE THREAD

**Issue by jmthackett** [mailcow/mailcow-dockerized#2743]
Hey, I love mailcow and have been running it for a while now. I'd like to run my domain being a little more liberal with its spam rules (and perhaps using cheaper hosting) and think this would be feasible if I could turn off rspamd, which I gather uses more memory than anything else. 

I'd like to be able to set a flag somewhere in the UI to use greylisting only for spam filtering. Does this sound feasible?

**Comment by mkuron** [comment]
Rspamd does more than just spam filtering for Mailcow. It also does DKIM signing and rate limiting for outbound messages. That’s why we don’t provide a configuration option to disable it. Greylisting is also done by rspamd. If you are tight on memory, you could switch off the actual spam filtering modules though in the rspamd config files.

I‘m not sure how useful greylisting is nowadays; it seems like even the spammers retry after a few minutes. It‘s no big deal, however: I seem to catch almost all my spam with the DNSBLs already, and those are evaluated within Postfix.

**Comment by andryyy** [comment]
You should also check why a mail is greylisted in first place. There is always a reason.
