### ISSUE TITLE
Web calendars not shared over activesync 

### ISSUE THREAD

**Issue by Svarto** [mailcow/mailcow-dockerized#2744]
Hello, 

I have a problem where I have a gmail calendar that I have subscribed to in Sogo as a web calendar.. I can see it all fine inside Sogo calendar, so it syncs fine. However, when I connect my Android phone through Exchange ActiveSync then I only see my personal calendars and not my web calendars. They just don't show up in the DavDroid app.

Have I done anything wrong here, or is this a bug? What can I do to also sync my web calendars to my android phone calendar? 

Flowchart: 

Gmail calendar --- shared calendar URL (subscribe) ---> Sogo web calendar --- Exchange ActiveSync ---> Android DavDroid

Thanks so much for your help with this!

**Comment by mkuron** [comment]
That is a SOGo limitation. Calendar subscriptions are not synced over CalDAV or EaS. You can check the SOGo bug tracker and open a feature request there, if there isn‘t already one.

**Comment by daemon-byte** [comment]
This is something I have seen requested many times, for many years but SoGo seem to want to ignore it. Did you find a solution or a replacement for sogo that works?

**Comment by Svarto** [comment]
@daemon-byte unfortunately no, I simply subscribe to the gmail separately in my calendar app and pull both calendars in separately client side instead if doing it server side.

**Comment by leemind** [comment]
I would love this too, because in crappy Microsoft Calendar you cannot subscribe to external calendars.  How 1970's is that?

**Comment by immanuelfodor** [comment]
Sadly the very good Nine Android app is incapable of adding web calendars 😞

**Comment by 8ear** [comment]
@immanuelfodor I use for the ical calendar on Android: OneCalendar. But it is very bad.
Do you have something else?

I use normally also Nine.

**Comment by immanuelfodor** [comment]
I'm still with Nine since all the other features are really nice. I was thinking of adding a new personal calendar, then writing a script to copy the entries of a web calendar to that new calendar to enable sync or use https://vdirsyncer.pimutils.org/en/stable/partial-sync.html for this exact purpose. But I didn't have the time to implement it. Should you find a usable config, please share 😄

**Comment by Jenjen1324** [comment]
After checking through the SoGO mailing list I found this: https://www.mail-archive.com/users@sogo.nu/msg20099.html

Seems like the ActiveSync protocol itself doesn't allow for read-only calendars. Correct me if I'm wrong, but in SOGo Web Calendars are always read-only (at least from my small ics test). That probably means that SOGo will never have that capability.
