### ISSUE TITLE
Suspect clamd Log

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#2746]
Hello,
i dont know why but clamd log looks suspect... i dont know what these extra entries after "Database correctly reloaded" mean.

docker-compose logs clamd-mailcow

clamd-mailcow_1      | Sat Jun 29 23:14:17 2019 -> Database correctly reloaded (6169326 signatures)
clamd-mailcow_1      | receiving incremental file list
clamd-mailcow_1      | ./
clamd-mailcow_1      | blurl.ndb
clamd-mailcow_1      | junk.ndb
clamd-mailcow_1      | jurlbl.ndb
clamd-mailcow_1      | phish.ndb
clamd-mailcow_1      | phishtank.ndb
clamd-mailcow_1      | rogue.hdb
clamd-mailcow_1      | sanesecurity.ftm
clamd-mailcow_1      | scam.ndb
clamd-mailcow_1      | sigwhitelist.ign2
clamd-mailcow_1      | spamimg.hdb
clamd-mailcow_1      | 
clamd-mailcow_1      | sent 420 bytes  received 22,208,862 bytes  4,935,396.00 bytes/sec
clamd-mailcow_1      | total size is 22,205,478  speedup is 1.00
clamd-mailcow_1      | /bootstrap.sh: line 66: [: -eq: unary operator expected
clamd-mailcow_1      | receiving incremental file list
clamd-mailcow_1      | ./
clamd-mailcow_1      | blurl.ndb
clamd-mailcow_1      | jurlbl.ndb
clamd-mailcow_1      | phishtank.ndb
clamd-mailcow_1      | spamimg.hdb
clamd-mailcow_1      | 
clamd-mailcow_1      | sent 28,580 bytes  received 161,953 bytes  127,022.00 bytes/sec
clamd-mailcow_1      | total size is 22,188,355  speedup is 116.45
clamd-mailcow_1      | /bootstrap.sh: line 66: [: -eq: unary operator expected
clamd-mailcow_1      | 
clamd-mailcow_1      | receiving incremental file list
clamd-mailcow_1      | ./
clamd-mailcow_1      | blurl.ndb
clamd-mailcow_1      | jurlbl.ndb
clamd-mailcow_1      | phishtank.ndb
clamd-mailcow_1      | 
clamd-mailcow_1      | sent 28,349 bytes  received 175,433 bytes  407,564.00 bytes/sec
clamd-mailcow_1      | total size is 22,205,478  speedup is 108.97
clamd-mailcow_1      | /bootstrap.sh: line 66: [: -eq: unary operator expected

**Comment by andryyy** [comment]
Thanks!
