### ISSUE TITLE
acme-mailcow is not getting the right IP behind a pfsense router

### ISSUE THREAD

**Issue by 1998CC2** [mailcow/mailcow-dockerized#2749]
Hi,
I hope someone can help me.

I want to install a new mailserver based on mailcow, that works so far.
But letsencrypt is not getting the certificate because, during the verification process it gets the IP from my pfsense router. All other VMs behind this router do not have this issue.

My setup is as follows:
1 physical server with ESXi 6.7U2 installed.
The ESXI host have his own IP.
One VM is working as a router with another public IP.
Additional to this 2 public IPs, I have a /29 subnet with also public IPs.
The subnet is routed to the second public IP which is the WAN address of the pfsense.
The first usable IP of the subnet is the LAN IP of the pfsense, which is the GW address for the other VMs.
All VMs behind the router have public IPs from the /29 subnet.

So, 4 of the VMs running Ubuntu 18.04 are working fine getting letsencrypt certificates.
Only the mailcow server (base also Ubuntu 18.04, fresh installed) seems to have problems with this setup, letsencrypt is getting the WAN IP address from the router, not the mailcow server itself.

Mon Jul  1 13:39:56 CEST 2019 - Waiting for Docker API...OK
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Waiting for database... Uptime: 72399  Threads: 23  Questions: 247947  Slow queries: 0  Opens: 55  Flush tables: 1  Open tables: 47  Queries per second avg: 3.424
acme-mailcow_1       | OK
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Waiting for Nginx... OK
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Waiting for domain table... OK
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Initializing, please wait... 
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Using existing domain key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Mon Jul  1 13:39:56 CEST 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Mon Jul  1 13:40:40 CEST 2019 - Found A record for mail.xxxxxx.xx: xxx.xxx.xxx.xxx
acme-mailcow_1       | Mon Jul  1 13:40:40 CEST 2019 - Cannot match your IP x.x.xx.xxx against hostname mail.xxxxxx.xx (xxx.xxx.xxx.xxx)
acme-mailcow_1       | Mon Jul  1 13:40:40 CEST 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
acme-mailcow_1       | Mon Jul  1 13:40:40 CEST 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
acme-mailcow_1       | OK

What I'm doing wrong ?
Or: what do I have to reconfigure ?

Thanks in advance,
Alex

**Comment by andryyy** [comment]
You may need to SNAT in mailcow.conf to fit your external IP.

Or just disable the IP check.

**Comment by 1998CC2** [comment]
Thanks @andryyy , I have disabled the IP check in mailcow.conf, but still does ist !
Do I need to do anything after I changed the mailcow.conf ?

Thanks,
Alex

**Comment by 1998CC2** [comment]
OK, fixed - I forgot to do `docker-compose up -d` after I changed mailcow.conf.

Now it is working fine - Thanks !

**Comment by rt050** [comment]
Hey 1998CC2,

I seem to be having the same issue but the suggested doesn't seem to fix it for me :(

How did you force mailcow via a specific gateway on pfsense? I've added the NAT rules and firewall rules to go out via a specific gateway but still returning that it's the wrong IP compared to the A record on the public dns...

**Comment by tardar** [comment]
I got the same error - the SNAT setting in mallow.conf won't help/work for me
