### ISSUE TITLE
Redirect to Login on Invalid Session

### ISSUE THREAD

**Issue by felixoi** [mailcow/mailcow-dockerized#275]
Hello,

since the last update I sometimes get the error "Invalid Session". I think my session timed out. Currently, I have to close the browser and open it again (reload is not working) to get the login page again. It would be nicer to just redirect to login instead of throwing an invalid session error.

Thanks,
felixoi

**Comment by andryyy** [comment]
You probably use a user agent switcher. Do you?

**Comment by felixoi** [comment]
Nope, I had this issue now 3 times with Chrome. I tried to do something after I didn't used Chrome for ~3 hours

**Comment by andryyy** [comment]
It checks the IP and User-Agent. If that fails, the session becomes invalid.

**Comment by felixoi** [comment]
Hmm.. I think I used my mobile phone with the mailcow admin in these 3 hours that could be the problem. So the User-Agent changed, but normally users should be able to have different sessions on different devices, or?

**Comment by andryyy** [comment]
Or the session timed out. I changed that stupid exit("invalid session") to a logout now. :)
Yes, multiple sessions are fine.
You can also alter the new session timeout in vars.inc.php, I missed to ask you about that.
