### ISSUE TITLE
unbound is not resolving DNS requests

### ISSUE THREAD

**Issue by 1998CC2** [mailcow/mailcow-dockerized#2751]
Hi,
I have installed mailcow on a clean Ubuntu 18.04 system, so far so good.
It seems like everything is working as it should be except for the DNS resolver unbound.

In postfix I get the following messages:

postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for b.barracudacentral.org
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for bl.mailspike.net
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for zen.spamhaus.org
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for dnsbl.sorbs.net
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for dnsbl.inps.de
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for hostkarma.junkemailfilter.com
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/postscreen[5926]: warning: dnsblog reply timeout 10s for wl.mailspike.net
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[6007]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.bl.mailspike.net: Host or domain name not found. Name service error for name=33.226.57.216.bl.mailspike.net type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[5936]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.dnsbl.inps.de: Host or domain name not found. Name service error for name=33.226.57.216.dnsbl.inps.de type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[6004]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.b.barracudacentral.org: Host or domain name not found. Name service error for name=33.226.57.216.b.barracudacentral.org type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[5934]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.zen.spamhaus.org: Host or domain name not found. Name service error for name=33.226.57.216.zen.spamhaus.org type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[5933]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.dnsbl.sorbs.net: Host or domain name not found. Name service error for name=33.226.57.216.dnsbl.sorbs.net type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[5947]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.hostkarma.junkemailfilter.com: Host or domain name not found. Name service error for name=33.226.57.216.hostkarma.junkemailfilter.com type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:43 mail postfix/dnsblog[5937]: warning: dnsblog_query: lookup error for DNS query 33.226.57.216.wl.mailspike.net: Host or domain name not found. Name service error for name=33.226.57.216.wl.mailspike.net type=A: Host not found, try again
postfix-mailcow_1    | Jul  2 06:20:46 mail postfix/smtpd[5991]: connect from unknown[216.57.226.33]

When I try this: **docker-compose exec unbound-mailcow dig web.de**
I got this: **OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"dig\": executable file not found in $PATH": unknown**

When I try this: **docker-compose exec unbound-mailcow nslookup web.de**
**I got this: nslookup: can't resolve '(null)': Name does not resolve**

**nslookup: can't resolve 'web.de': Try again**

When I try to send me a message I got this:
postfix-mailcow_1    | Jul  2 06:52:02 mail postfix/smtpd[6227]: NOQUEUE: reject: RCPT from unknown[17.58.38.45]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [17.58.38.45]; from=<xxxxxxx@icloud.com> to=<info@xxxxxx.xx> proto=ESMTP helo=<ms11p00im-qufo17291601.me.com>

Looks for me that unbound isn't working.
I'm totally lost here - so help is much appreciated !

Thanks,
Alex

**Comment by andryyy** [comment]
The issue template is useful exactly for this.

**Comment by 1998CC2** [comment]
@andryyy sorry, I didn't see a template - where can I find it ?

**Comment by andryyy** [comment]
You deleted it when you created the issue.

I remember you are using a pfSense in front of mailcow. It will probably disallow these DNS requests as spoofed.

**Comment by 1998CC2** [comment]
@andryyy sorry again !

Thats right, the server is behind a pfsense, now I have to find out how this works 😉 ....

**Comment by 1998CC2** [comment]
Hi,
it was not a problem with the pfsense !
A fresh mailcow install in the same subnet works fine ...

Can it be that during the initial install, the host IP is used somewhere ?
I changed the IP of the system at one point.

**Comment by andryyy** [comment]
No

**Comment by unclesamwk** [comment]
i have the same problem ...

the setup:
digitalocean droplet, with two ips
1x droplet default ip, ptr works
1x floating ip set as snat, ptr dont set
mail.domain.com -> set to the droplet default ip

what can i do??? very urgent

**Comment by andryyy** [comment]
Does it work with SNAT disabled/removed from mailcow.conf? You need to 
run up -d after changing that.

To be sure: You cannot resolve names, right?

------ Originalnachricht ------
Von: "Samuel Warkentin" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Mention" 
<mention@noreply.github.com>
Gesendet: 05.07.2019 12:16:34
Betreff: Re: [mailcow/mailcow-dockerized] unbound is not resolving DNS 
requests (#2751)

**Comment by unclesamwk** [comment]
it looks like cannot resolve ... i dont why.
docker-compose up -d dont helps ...

**Comment by andryyy** [comment]
My question was if it works with SNAT disabled.

**Comment by unclesamwk** [comment]
yes, it works! hm ... why dont with snat ...

**Comment by andryyy** [comment]
Ah, hm. Perhaps we need to exclude port 53 from that SNAT rule. Not sure. I'd need a system to test that on.

**Comment by 1998CC2** [comment]
Hi,
I was not able to fix it, because it was a fresh server - I have done a fresh install and it works now like a charm !
