### ISSUE TITLE
Adress Rewrite for whole Domains

### ISSUE THREAD

**Issue by durnerj** [mailcow/mailcow-dockerized#2752]
Hi,

I tried to "Address Rewrite" a whole Domain. I knew Postfix is able to do that because a Friend of mine is also doing that. The Domain is fully Relayed to another Server so all the Mails need to be rewritten to another Domain.

Mailcow supports only rewrite to a single Mail Address in the UI, but Postfix supports also a rule like:
@example.com -> @new-example.com

I know it works as i then added this Rule to the SQL DB and all Mail gets Domain Rewritten.

**Comment by mkuron** [comment]
So you're saying that only the validation in the admin UI is too strict? In that case, please submit a pull request to fix it. It's probably in https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.address_rewriting.inc.php.

**Comment by durnerj** [comment]
Sorry, I am nowhere near a PHP Dev. I basically understand whats going on, but I would need 2 Weeks of PHP learning to rewrite this. ;)

**Comment by Braintelligence** [comment]
@mkuron I think this is the spot: https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.address_rewriting.inc.php#L281 do you agree?

EDIT: The actual error messages that we can see are here https://github.com/mailcow/mailcow-dockerized/blob/4220d5f4ba27ce1dfca31f1994805b0467a3c73c/data/web/inc/functions.address_rewriting.inc.php#L285 and here https://github.com/mailcow/mailcow-dockerized/blob/4220d5f4ba27ce1dfca31f1994805b0467a3c73c/data/web/inc/functions.address_rewriting.inc.php#L351 IMO.

EDIT2: Old addresses are checked first if they're valid domains here: https://github.com/mailcow/mailcow-dockerized/blob/4220d5f4ba27ce1dfca31f1994805b0467a3c73c/data/web/inc/functions.address_rewriting.inc.php#L267

then if they aren't, they're being checked if they are at least valid mail addresses here:
https://github.com/mailcow/mailcow-dockerized/blob/4220d5f4ba27ce1dfca31f1994805b0467a3c73c/data/web/inc/functions.address_rewriting.inc.php#L336

for new destinations this works differently; they are only being checked on if they're valid mail addresses:
https://github.com/mailcow/mailcow-dockerized/blob/4220d5f4ba27ce1dfca31f1994805b0467a3c73c/data/web/inc/functions.address_rewriting.inc.php#L347

Could we just refactor the pattern of the old destination to perform the same checks on the new destination and delete the old portion of the new destination @mkuron ?

**Comment by mkuron** [comment]
Yes, we need the same validation for both old and new. And we need to do it during adding and during editing.
