### ISSUE TITLE
Cannot validate hostnames

### ISSUE THREAD

**Issue by TEFEdotCC** [mailcow/mailcow-dockerized#2753]
Hello,

I know ... there is the x post to that topic, but I cann't find a solution. (ufw, iptables, fire... disabled / not installed)
.... But after writing that lines and reading the one hundread and one times the comment https://github.com/mailcow/mailcow-dockerized/issues/2323#issuecomment-463299354 I'm knowing where the mistake / issue is.

The nginx configuration example of mailcow for an reverse proxy, with 301 for http request to https, *is wrong*.
@see Line 5 of Nginx configuration at https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/
`return 301 https://$host$request_uri;`

Please rewrite the configuration to a valid state for an reverse proxy with acme-mailcow

> sudo docker-compose logs acme-mailcow                          
Attaching to mailcowdockerized_acme-mailcow_1
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Waiting for Docker API...OK
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Waiting for database... Uptime: 5  Threads: 14  Questions: 63  Slow queries: 0  Opens: 35  Flush tables: 1  Open tables: 27  Queries per second avg: 12.600
acme-mailcow_1       | OK
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Waiting for Nginx... OK
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Waiting for domain table... OK
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Initializing, please wait... 
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Using existing domain key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Tue Jul  2 20:25:48 CEST 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Tue Jul  2 20:25:50 CEST 2019 - No A or AAAA record found for ..... but HTTP validation failed
acme-mailcow_1       | Tue Jul  2 20:25:52 CEST 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
acme-mailcow_1       | Tue Jul  2 20:25:52 CEST 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
acme-mailcow_1       | OK

> docker-compose exec acme-mailcow curl -4 mail.thomas-enzinger.de/.well-known/acme-challenge/1 --write-out %{http_code}
...
301#

> docker-compose exec acme-mailcow curl -6 mail.thomas-enzinger.de/.well-known/acme-challenge/1 --write-out %{http_code} 
...
301#

**Comment by andryyy** [comment]
When you say it is wrong, why don't you provide a fix? :/

**Comment by andryyy** [comment]
I c/p the config just to be sure, it seems fine:

![image](https://user-images.githubusercontent.com/2972950/60540122-b8f9ea80-9d0e-11e9-8774-8f51930240e3.png)

**Comment by TEFEdotCC** [comment]
I do not have any skills to nginx configuration / understand the configuration in deep of mind.

The provieded mailcow reverse proxy configuration for the 80 port
> server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name CHANGE_TO_MAILCOW_HOSTNAME autodiscover.* autoconfig.*;
  return 301 https://$host$request_uri;
}

I do add the **proxy_pass** of the ssl configuration
> > server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name CHANGE_TO_MAILCOW_HOSTNAME autodiscover.* autoconfig.*;
  location / {
          proxy_pass http://127.0.0.1:8080/;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          client_max_body_size 0;
  }
}

**Comment by Braintelligence** [comment]
`No A or AAAA record found for` - did you miss this?
Am I confusing something here? How is nginx involved if there is no A/AAAA record for the domain you want to validate?

Also I'm super confused about that line. It doesn't find an A/AAAA record but still tried to HTTP validate? This makes no sense to me.

**Comment by Braintelligence** [comment]
No news is good news.
