### ISSUE TITLE
How can I add urlhaus signature db to clamav

### ISSUE THREAD

**Issue by heino-vdbh** [mailcow/mailcow-dockerized#2757]
Hi,

if I add DatabaseCustomURL https://urlhaus.abuse.ch/downloads/urlhaus.ndb to freshclam.conf I get ERROR: DatabaseCustomURL: Not supported protocol.

Is there another way to get this custom signature db into clamav and refresh it regularly?

**Comment by Braintelligence** [comment]
https://lists.gt.net/clamav/users/62788

**Comment by andryyy** [comment]
Guess you could reverse proxy it. :-D

The thread above is fun to read btw.

**Comment by heino-vdbh** [comment]
yes the thread is funny but still no https support since 2014 in freshclam...
I have modified the bootstrap.sh to curl the urlhaus.ndb

**Comment by Braintelligence** [comment]
@hniemann Can you provide your code changes?

**Comment by Schroeffu** [comment]
I guess a ClamAV Bugreport is the better place for this feature request, so I did it here: https://bugzilla.clamav.net/show_bug.cgi?id=12454

**Comment by Schroeffu** [comment]
> I guess a ClamAV Bugreport is the better place for this feature request, so I did it here: https://bugzilla.clamav.net/show_bug.cgi?id=12454

Feature Request closed there. Recently, ClamAV Freshclam stable 0.102 (2019-11-20) does support HTTPS DatabaseCustomURL. 

Release note https://blog.clamav.net/2019/10/clamav-01020-has-been-released.html
