### ISSUE TITLE
How to configure MX backup?

### ISSUE THREAD

**Issue by andrefelipe47** [mailcow/mailcow-dockerized#2758]
I'm newbie, I understand some things about DNS, Linux and Networks.

I found the relay this domain option in Mailcow Backup MX.

I would like to know how to properly set up the MX backup in Mailcow.

> I'm using the latest version of Mailcow Dockerized.

I use cloudflare DNS.

What settings do I configure in the DNS record?

What settings do I need to make on the primary and secondary server?

What are the requirements?

Is there any risk of spam when I enable Relay?

**Comment by dashohoxha** [comment]
I think that the best way to configure a backup server is this: http://www.junkemailfilter.com/spam/free_mx_backup_service.html

@andryyy what do you think about this backup service?
What about adding a hint here: https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/

**Comment by andrefelipe47** [comment]
> Eu acho que a melhor maneira de configurar um servidor de backup é esta: http://www.junkemailfilter.com/spam/free_mx_backup_service.html
> 
> @andryyy o que você acha sobre este serviço de backup? 
> Que tal adicionar uma dica aqui: https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/


For me this solution would not be interesting, as the emails would go to a server outside my domains (which could be a risk to the safety of my clients).

I would like to create a second server, where the first sends to the second, in case the first fails, the clients use the second until the first one is restored.

**Comment by TimurZanagar** [comment]
Is it possible to get the “old” wiki post about this subject?
