### ISSUE TITLE
ERROR: Network "mailcowdockerized_mailcow-network" needs to be recreated - enable_ipv6 has changed

### ISSUE THREAD

**Issue by vivernet** [mailcow/mailcow-dockerized#276]
After updating, when you run the command docker-compose up-d, the result is error: ERROR: Network "mailcowdockerized_mailcow-network" needs to be recreated - enable_ipv6 has changed.
Looking for how to solve this problem, but couldn't find, please tell me.
IPv6 address the server is available but not registered in the DNS, since before IPv6 was not supported, as far as I know.

**Comment by andryyy** [comment]
Hi, try `docker-compose down` and then `docker-compose up -d`. :)

**Comment by vivernet** [comment]
Thank you

**Comment by crimsonvspurple** [comment]
Hello.

I have the same problem but when I enter docker-compose down, I get this:

```
root@email:/opt/mailcow/mailcow-dockerized# docker-compose down
WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
WARNING: Found orphan containers (mailcowdockerized_rmilter-mailcow_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing network mailcowdockerized_mailcow-network
ERROR: network mailcowdockerized_mailcow-network has active endpoints
root@email:/opt/mailcow/mailcow-dockerized# docker-compose up -d --remove-orphans
WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
ERROR: Network "mailcowdockerized_mailcow-network" needs to be recreated - enable_ipv6 has changed
```

What to do?

**Comment by mkuron** [comment]
Run `docker-compose down` multiple times until the network error goes away. If it doesn't go away, reboot and try again.

**Comment by crimsonvspurple** [comment]
Have tried that for many times and even reboot the whole system :(

**Comment by mkuron** [comment]
Manually delete the network using `docker network`, then try again.

**Comment by crimsonvspurple** [comment]
Worked! Thanks.

**Comment by vietnguyen1989** [comment]
run `docker network prune ` helps

**Comment by jewelbdx** [comment]
> Hi, try `docker-compose down` and then `docker-compose up -d`. :)

This was the solution for me, But, could you explain a bit more? 
Thanks.
