### ISSUE TITLE
Redis container "RDB ERROR DETECTED"

### ISSUE THREAD

**Issue by sstevan** [mailcow/mailcow-dockerized#2760]
Hello,

I had some issues with Redis as stated in https://github.com/mailcow/mailcow-dockerized/issues/1454#issue-328529456 and solved by the https://github.com/mailcow/mailcow-dockerized/issues/1454#issuecomment-412515019.

However, after a while, mailcow kept crashing (not sure which part) so I have decided to update to the latest version. Now I am getting `502 Bad Gateway` when trying to open WebUI. I have discovered that Redis container is not starting properly due to corrupt `dump.rdb` file.
Here is the full log:
```
1:C 04 Jul 2019 11:42:23.016 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Jul 2019 11:42:23.016 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Jul 2019 11:42:23.016 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 04 Jul 2019 11:42:23.019 * Running mode=standalone, port=6379.
1:M 04 Jul 2019 11:42:23.019 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 04 Jul 2019 11:42:23.019 # Server initialized
1:M 04 Jul 2019 11:42:23.019 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 04 Jul 2019 11:42:23.019 # Short read or OOM loading DB. Unrecoverable error, aborting now.
1:M 04 Jul 2019 11:42:23.021 # Internal error in RDB reading function at rdb.c:2058 -> Unexpected EOF reading RDB file
[offset 0] Checking RDB file dump.rdb
[offset 26] AUX FIELD redis-ver = '5.0.5'
[offset 40] AUX FIELD redis-bits = '64'
[offset 52] AUX FIELD ctime = '1561988802'
[offset 67] AUX FIELD used-mem = '8574256'
[offset 83] AUX FIELD aof-preamble = '0'
[offset 85] Selecting DB ID 0
--- RDB ERROR DETECTED ---
[offset 24058] Invalid LZF compressed string
[additional info] While doing: read-object-value
[additional info] Reading key 'NETFILTER_LOG'
[additional info] Reading type 14 (quicklist)
[info] 4 keys read
[info] 0 expires
[info] 0 already expired
```

I don't mind losing anti-spam related stuff in there but I would like to know if it is safe to delete it and if yes, how to do it. 

EDIT:  Redis container keeps restarting all the time.

**Comment by sstevan** [comment]
Removing the  `/var/lib/docker/volumes/mailcowdockerized_redis-vol-1/_data/dump.rdb` did the trick.

**Comment by jeefbezos67** [comment]
> Removing the `/var/lib/docker/volumes/mailcowdockerized_redis-vol-1/_data/dump.rdb` did the trick.

worked for me, thx broo

**Comment by mkuron** [comment]
Note that dump.rdb should only be deleted as a last resort. If it is corrupted, better replace it with a backup. Otherwise you won't only lose anti-spam training, but also DKIM keys, forwarding hosts and some other configuration data.

**Comment by Meran25524** [comment]
worked for me too, thanks (Y)
