### ISSUE TITLE
[Feature] Add support for CRAM-MD5 passwords

### ISSUE THREAD

**Issue by tsfoer** [mailcow/mailcow-dockerized#2766]
When migrating from old setups with postfix+dovecot to mailcow, the original passwords can be hashed with CRAM-MD5

As the original passwords are unknown, i'd like to have support for the old CRAM-MD5 passwords to make the transition to mailcow much smoother for the admin and users as new passwords don't have to be created.

Is this feasible?

**Comment by mkuron** [comment]
All the necessary information is in #1019 and #2600. Please submit a pull request if you get this password scheme working. To import the old passwords, create the users first and then set the passwords directly in the database (the scheme is prefixed to the hash).
