### ISSUE TITLE
[Feature] Netfilter recidive bans

### ISSUE THREAD

**Issue by DatAres37** [mailcow/mailcow-dockerized#2767]
**Is your feature request related to a problem? Please describe.**
Netfilter keeps banning the same IP for half an hour for days or weeks now. It's now 2 pm and I've already received more than 21 watchdog mails about these bans today.

**Describe the solution you'd like**
A ban mechanism like recidive from Fail2Ban would be great to stop persistent abusers. This would be a safety and anti-annoyance feature. I know that I could just disable watchdog mails, but ignoring doesn't solve the problem I guess. 

**Additional context**
```
Causing log messages:
8.7.2019, 13:15:06	warning	warning: unknown[X.X.X.X]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
8.7.2019, 13:14:03	info	Anonymous TLS connection established from unknown[X.X.X.X]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
8.7.2019, 13:13:36	info	connect from unknown[X.X.X.X]
8.7.2019, 13:13:06	info	disconnect from unknown[X.X.X.X] ehlo=1 auth=0/1 rset=1 commands=2/3
8.7.2019, 13:13:06	info	lost connection after AUTH from unknown[X.X.X.X]
```

```
X.X.X.X matched rule id 1
Banning X.X.X.0/24 for 30 minutes
```

**Comment by andryyy** [comment]
Hi, you can already set a higher ban time. Or permban them. All in 
mailcow UI.
A link to permban them would be cool though. Hm. Enotime. :(

------ Originalnachricht ------
Von: "Daniel Ares" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 08.07.2019 14:42:35
Betreff: [mailcow/mailcow-dockerized] [Feature] Netfilter recidive bans 
(#2767)

**Comment by DatAres37** [comment]
Oh I thought fail2ban and netfilter would be two different things 😊 
Thanks.

Maybe recidive could still be an idea to automate this procedure, but I'm fine with this solution as well.

**Comment by benoitjpnet** [comment]
Fail2Ban has a recidive jail though. Would a PR to add the recidive jail to fail2ban be appreciated?

**Comment by dragoangel** [comment]
Sometimes your users is most abusing clients. People forget to add @domain.com and use only username. Other people change their password but forget to update their password on clients and last case - user was dropped but his client still try login. Automated permaban isn't good idea. The idea of netfilter to minimize risk of brute force, but not to permanently not allow people to login.

You as administrator based on reports can check if it is valid user which needs your  help or bot who trying to brute force you 2 days in raw. In result you will help poor guy or permaban abusers. There of course a place to enhance netfilter like:
- geoip analysis and dedicated rules based on client geoip
- storing client previous valid logins IPs and check that abusers not from same subnets - then ban them quicker for example
- storing summary history of failed authorizations for week/mouth period to have some report with usernames if any available (now you can get this from postfix logs mostly).

But such option is much harder to implement and even without such stuff netfilter working cool and most important - from the box :)

Also want to note my own observation:
From my experience when bots start to know that you have fail2ban like system then stopping any abusers brute force activities and start to use another way: they use many IPs but try guess password only once per day - per IP.
Also another observation:
Bots doesn't abusing IPv6 yet.

P.s. Not forget to whitelist your office/home IPs :D.
