### ISSUE TITLE
./generate_config.sh ERROR cp: invalid option -- 'n'

### ISSUE THREAD

**Issue by legraml** [mailcow/mailcow-dockerized#2769]
When I run ./generate_config.sh on a QNAP NAS TVS-871 with the latest firmware installed, I get the error "cp: invalid option -- 'n'" after setting the timezone.

A quick look into update.sh reveals the same option flag to be used in the code there, too.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/60834382-e6d4a880-a1c0-11e9-86bf-2cdc8270d88e.png)

:/

**Comment by legraml** [comment]
I don't want to run it on QNAP Linux itself but on docker. As I have many applications running  already like Nextcloud, Tvheadend, Portainer, Traefik and so on and the NAS is based on x86 and not ARM, it shouldn't be very hard to get Mailcow running once it passes the config generation script. By the way, many ordinary linux distributions don't support the "-n flag" either.

**Comment by andryyy** [comment]
I know. It won't work. It will either destroy your network configuration or not even start. 

You should create a KVM and install it there. :)

**Comment by legraml** [comment]
> 
> 
> I know. It won't work. It will either destroy your network configuration or not even start.
> 
> You should create a KVM and install it there. :)

Now you made me curious why Mailcow would be the first docker app that cannot be run on docker on a QNAP. As long as I can define seperate networks and routes it should be okay. I have 5 hardware network ports so I can even assign a dedicated network port to a certain docker application...

**Comment by mkuron** [comment]
These NAS devices (Synology, QNAP, ...) tend to have non-standard and/or very outdated Docker setups. If you search our issue tracker, you‘ll find a surprising number of issues that only occur on these devices. Mailcow uses some slightly exotic Docker features (IPv6, binding to specific IP addresses), makes heavy use of inter-container networking and creates its own iptables rules on the host (for fail2ban purposes), none of which these NASes tend to deal with too well. There is no technical reason why Mailcow can‘t work on a NAS, it‘s just that experience tells us that it doesn‘t work on most NASes.
