### ISSUE TITLE
Errors after SoGo Login/Outlook Sync

### ISSUE THREAD

**Issue by byRoadrunner** [mailcow/mailcow-dockerized#2770]
**Describe the bug, try to make it reproducible**
After the latest update the log gets spammed by SoGo errors, it does not really impact the usage of SoGo, but these errors seem not to be good. The same issue also occurs when syncing with Outlook.

**System information and quick debugging**
General logs:
```
sogo-mailcow_1       | Jul  8 23:26:45 3b70c68b22d1 sogod [70]: <0x0x558d1cd4b120[NGImap4Client]> TLS started successfully.
sogo-mailcow_1       | Jul  8 23:26:45 3b70c68b22d1 sogod [70]: [ERROR] <0x558d1dd927e0[SOGoMailAccount]:0> Could not get a valid IMAP connection
sogo-mailcow_1       | Jul  8 23:26:45 3b70c68b22d1 sogod [70]: [WARN] <0x558d1dd927e0[SOGoMailAccount]:0> IMAP connection is broken, trying to reconnect...
dovecot-mailcow_1    | Jul  8 23:26:45 mail dovecot: imap(user@removed-domain.de)<430><BbfiGTKNuNWsFgH4>: Connection closed (No commands sent) in=0 out=421 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

Further information (where applicable):
 - OS: Debian 9 (Issue also appears on a Debian 10 VM)
 - Virtualization: KVM
 - Docker 18.09.7 and Docker Compose 1.24.1, build 4667896b
 - Output of `git diff origin/master`, any other changes to the code? No

Thank you in advance, if there are any other files or logs needed, just tell, I´ll provide them.

**Comment by dsaard** [comment]
looks like https://sogo.nu/bugs/view.php?id=4757

**Comment by andryyy** [comment]
Merci

**Comment by mritzmann** [comment]
@dsaard Did you update your SOGo independently from Mailcow, or what was your solution?

**Comment by andryyy** [comment]
I think we worked this around by using IMAPS. But you can try and run `docker-compose build sogo-mailcow` followed by `up -d`.

**Comment by mritzmann** [comment]
Thanks, seems to be working.
