### ISSUE TITLE
Catchall alias still effective when disabled

### ISSUE THREAD

**Issue by jetkins** [mailcow/mailcow-dockerized#2771]
I created a catchall alias for one of the multiple alias domains that my server handles.

Subsequently, I decided to let those rogue emails get bounced, so I edited the catchall alias and deselected the Active box before saving it again.  I now see an X in the Active column for this alias, which would seem to confirm that it is not active.

However, emails to non-matched addresses in that domain are still being forwarded to the catchall mailbox, which suggests that the catchall alias is still in effect even though it's been marked as inactive.

I know there's an easy workaround - simply delete the catchall alias instead of disabling it - and I intend to do exactly that, but I though I should mention this behavior here since it would appear prima facie to be not working as designed (or described).

**Comment by andryyy** [comment]
No:

<maus1@develcow.de>: host mx.mailcow.email[2a00:f820:417:0:80:77:26:247] said:
550 5.1.1 < maus1@develcow.de>: Recipient address rejected: User unknown in
virtual mailbox table (in reply to RCPT TO command) 

Could have been the cache. It might take a few seconds to apply. The SQL map checks against "active", too. I am sure it will work if you wait a little bit longer. :)

**Comment by jetkins** [comment]
I had disabled it several days ago, and mail was still getting caught.  I don't recall whether I had restarted Mailcow, but I very much doubt it was still cached.  I had removed the disabled catchall alias since I wrote my original post, but in the interest of science, I'll add it back in and disable it again to see if I can recreate the problem.

**Comment by jetkins** [comment]
Sure enough, after creating a new "inactive" catchall rule last night, two more emails were delivered to the catchall mailbox this morning.

**Comment by jetkins** [comment]
```
postfix-mailcow_1    | Jul  9 10:00:19 mailcow postfix/smtpd[3703]: connect from mail-qt1-f170.google.com[209.85.160.170]
postfix-mailcow_1    | Jul  9 10:00:19 mailcow postfix/smtpd[3703]: Anonymous TLS connection established from mail-qt1-f170.google.com[209.85.160.170]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
postfix-mailcow_1    | Jul  9 10:00:22 mailcow postfix/smtpd[3703]: 78024804A9: client=mail-qt1-f170.google.com[209.85.160.170]
postfix-mailcow_1    | Jul  9 10:00:27 mailcow postfix/qmgr[366]: 78024804A9: from=<[myaliasdomain]+caf_=Wesley=[myaliasdomain].com@gmail.com>, size=57386, nrcpt=1 (queue active)
postfix-mailcow_1    | Jul  9 10:00:27 mailcow postfix/lmtp[3708]: 78024804A9: to=<catchall@[mybasedomain].net>, orig_to=<Wesley@[myaliasdomain].com>, relay=dovecot[172.22.1.250]:24, delay=7.2, delays=7.2/0.01/0.01/0.04, dsn=2.0.0, status=sent (250 2.0.0 <catchall@[mybasedomain].net> WKHXEAusJF3pTAAAl75pgg Saved)
postfix-mailcow_1    | Jul  9 10:00:27 mailcow postfix/qmgr[366]: 78024804A9: removed
postfix-mailcow_1    | Jul  9 10:00:27 mailcow postfix/smtpd[3703]: disconnect from mail-qt1-f170.google.com[209.85.160.170] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
```

**Comment by andryyy** [comment]
Hm. I cannot reproduce it anywhere, but I would love to check this. I'd need system access though. 

Any chance we can do this? Screen session via SSH?

**Comment by jetkins** [comment]
Certainly.  What's the best secure channel for me to reach out to you?

**Comment by andryyy** [comment]
We can talk/write about this by mail first: andre.peters@servercow.de or @diekuh in Telegram
