### ISSUE TITLE
No emails after migration

### ISSUE THREAD

**Issue by desigi** [mailcow/mailcow-dockerized#2772]
Hello,
I migrated to a new server by creating a backup with backup_and_restore.sh and running the restore on the new server. Everything seems to be working fine (emails coming in and going out), but I can't see all the previous emails from the inbox and sent folders.

Each mailbox shows that there are emails in the admin panel, but I can't see them on any client or if I log into SOGo.

Have I forgotten to do something in the migration?

**Comment by pkntl** [comment]
It appears everything was setup correctly. All that was needed was a server reboot.
