### ISSUE TITLE
ca.pem and ca-key.pem

### ISSUE THREAD

**Issue by SecT0uch** [mailcow/mailcow-dockerized#2773]
Hi,
Mailcow works flawlessly with my custom certificate, However I'm wondering what are ca.pem and ca-key.pem in the assets directory ?
My registrar gave me 4 files (the only way to get a wildcard with them:

- domain.cert.pem    =>    cert.pem
- private.key.pem    =>    key.pem
- intermediate.cert.pem
- public.key.pem

Can the two later ones be used with mailcow ?

I'm asking because when I check the TLS at https://www.checktls.com/, I encounter a fail on the certificate check : 
```
STARTTLS command works on this server
--
[002.785] |   | Connection converted to SSL
  |   | SSLVersion in use: TLSv1_3
  |   | Cipher in use: TLS_AES_256_GCM_SHA384
  |   | Certificate 1 of 1 in chain: Cert  VALIDATION ERROR(S): unable to get local issuer certificate; unable to  verify the first certificate
  |   | This may help: What Is An Intermediate Certificate
  |   | So email is encrypted but the recipient domain is not verified
  |   | Cert Hostname DOES NOT VERIFY (mail.sect0uch.world != mail.example.org)
  |   | So email is encrypted but the host is not verified
  |   | Not Valid Before: Dec 13 10:11:00 2016 GMT
  |   | Not Valid After: Nov 28 10:11:00 2019 GMT
  |   | subject= /O=mailcow/CN=mail.example.org
  |   | issuer= /O=mailcow
```
Should I replace your ca.pem with my intermediate.cert.pem ? What about ca-key.pem ?

Thanks,

**Comment by andryyy** [comment]
Hi,

They are not used at all. I just added them when creating a pseudo CA etc.

You can ignore them.

**Comment by SecT0uch** [comment]
So what about the fail on the certificate check ?

EDIT : My bad, a misconfiguration on my side

**Comment by mkuron** [comment]
You should append the contents of intermediate.cert.pem to cert.pem. That way, the server sends the entire chain and validation works. Your checktls result looks like it was using Mailcow's example certificate, so I guess that was your misconfiguration.
