### ISSUE TITLE
delete bulk ratelimit hashes

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#2775]
Hi,

  my problem is not relating to bug, but accidentally I've created a rate limit rule, how can I delete the hashes easily, because by hand would take hours even days.

  Kind Regards,
Zoltan

update: I tried to delete some of the hashes and imagined that they are identical for all the events, after I deleted the first one all other says that "Hash not found"

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/16578737/61051779-2cc08500-a3ea-11e9-9d9b-09c8412c25e8.png">

**Comment by andryyy** [comment]
Hi,

yes, it just keeps the logs. The hash can already be deleted but is still listed. The button should probably read "Delete hash, if available" or something like that.
