### ISSUE TITLE
Return Receipt

### ISSUE THREAD

**Issue by eduardosflores** [mailcow/mailcow-dockerized#2776]
Hi, 

I have configured mailcow on my job and every time a try to send a mail with return receipt enable, i can't get any confirmation report. I think that's a bug, but i'm not sure. 

How can i get this working?

**Comment by fm** [comment]
In SOGo, Return Receipt is a "Read Receipt" not a "Delivery Receipt", (it attaches the `Disposition-Notification-To:` header) and will only be sent if the recipient is configured to send you one (some opt to not send read receipts).

I don't believe SOGo has an option for Delivery Receipts. If you want a Delivery Receipt to confirm the recipient's server got the message instead of looking at postfix logs, you can install Roundcube, as they have an option for that. 

It's a super easy install that's documented here: https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

**Comment by eduardosflores** [comment]
In mailcow/SOGo, if i enable enable return receipt and The recipient open the message, should i receive a confirmation message? I think that the default configuration should at least ask me if i want to send a confirmation message. In our old mail system, Thunderbird/roundcube used to ask me If i want to send a confirmation message every time that i opened a message that was sent with this feature enabled.

On mailcow/SOGo, If i send a message with return receipt enabled, nothing happens when the receipt open The message, even in Thunderbird i can't get any confirmation with The messages that i used to test. 

Sorry for my poor english, but i can't get This working, is that the way SOGo Works?

**Comment by fm** [comment]
You will only get a read receipt if the recipient wants to send you one. If you're sending one to yourself, make sure your email provider and client settings are set to either ask you, or always send read receipts. There is no issues with mailcow, this is all on how the recipient processes the email and if they decide to adhere, there is no way you can force the recipient to send one.

**Comment by eduardosflores** [comment]
Anyway, The feature that FM described is exactly what i want that mine e-mail do. O don't know If a have made some mistake on configuration or If that is a bug.

**Comment by eduardosflores** [comment]
FM, ok i got your point, on mailcow/SOGo can i enable to send This confirmation?

**Comment by eduardosflores** [comment]
FM, I'm mine own mail provider, i have set up mailcow for this.

**Comment by eduardosflores** [comment]
On Sunday, July 14, 2019 18:59 -03, Faisal Misle <notifications@github.com> wrote:


You will only get a read receipt if the recipient wants to send you one. If you're sending one to yourself, make sure your email provider and client settings are set to either ask you, or always send read receipts. There is no issues with mailcow, this is all on how the recipient processes the email and if they decide to adhere, there is no way you can force the recipient to send one.

**Comment by fm** [comment]
But you are the sender, not the recipient. If you enable "Return Receipt" on SOGo, you will only get a read receipt if the person you sent an email to decide to send you one based on their settings. This is not a bug. It is up to the recipient's client to send a read receipt. Send yourself a test from mailcow to another account and try it out. I just did and I was asked _"The message sender has requested a response to indicate that you have read this message.  Would you like to send a receipt?"_ on the webmail interface, but I was not asked on Mac Mail. So, like I said, it will depend on the recipient's settings and options and even what email client they read it on. It is not a reliable way, and expect it to not work more than it will.

**Comment by eduardosflores** [comment]
Faisal, to test this, i'm The Sender and receipt. I have set up 2 accounts:eduardof@guarulhos.sp.leg.br and eduardo.flores@guarulhos.sp.leg.brI'm trying to send messages from one to another and i never was asked that "The message sender has requested a response to indicate that you have read this message. Would you like to send a receipt?" Or something like this on Mine web interface on SOGOI think that Mine mail system has a different behavior, maybe beacuse Mine configuration or some bug.Em 14 de jul de 2019 19:21, Faisal Misle <notifications@github.com> escreveu:But you are the sender, not the recipient. If you enable "Return Receipt" on SOGo, you will only get a read receipt if the person you sent an email to decide to send you one based on their settings. This is not a bug. It is up to the recipient's client to send a read receipt. Send yourself a test from mailcow to another account and try it out. I just did and I was asked "The message sender has requested a response to indicate that you have read this message.  Would you like to send a receipt?" on the webmail interface, but I was not asked on Mac Mail. So, like I said, it will depend on the recipient's settings and options and even what email client they read it on. It is not a reliable way, and expect it to not work more than it will.

**Comment by eduardosflores** [comment]
Faisal, to test this, i'm The Sender and receipt. I have set up 2 accounts:

eduardof@guarulhos.sp.leg.br and eduardo.flores@guarulhos.sp.leg.br

I'm trying to send messages from one to another and i never was asked that "The message sender has requested a response to indicate that you have read this message. Would you like to send a receipt?" Or something like this on Mine web interface on SOGO (in The receipt mail).

I think that Mine mail system has a different behavior, maybe beacuse configuration or some bug.

**Comment by fm** [comment]
After a quick Google search, SOGo by default never sends read receipts (https://sogo.nu/bugs/view.php?id=4484)

To find SOGo's settings for Read Receipts: 
Go to Settings -> Mail -> IMAP Accounts -> Click the pencil icon -> Scroll down to the bottom 

![image](https://user-images.githubusercontent.com/3654256/61191617-2c3a1f80-a672-11e9-9780-323416926877.png)

![image](https://user-images.githubusercontent.com/3654256/61191664-a5397700-a672-11e9-8e36-43c0f7e6aed4.png)

![image](https://user-images.githubusercontent.com/3654256/61191634-496eee00-a672-11e9-89b3-4a2cc91ee3c9.png)

**Comment by eduardosflores** [comment]
Oh! Thank you!

Do you know If o can change The default for ALL users?

**Comment by fm** [comment]
I don't see a way. You can ask their mailing list directly https://sogo.nu/support.html

**Comment by eduardosflores** [comment]
Thank you! I Will try with them.
