### ISSUE TITLE
Mailcow Network Adapter

### ISSUE THREAD

**Issue by kalosa** [mailcow/mailcow-dockerized#2777]
Hello,

We are facing a problem every 2-4 weeks and server becomes unreachable.
We use dedicated server with intel xeon 4 cores and 32gb of ram

IPv6 is disabled in mailcow.conf and docker-compose.yml

Please see the error logs we found

[   20.968716] eth0: renamed from veth6bce4ca
[   21.044590] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   21.047209] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   21.047260] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   21.292921] eth0: renamed from vethc2cd9e2
[   21.353180] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   21.355496] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   21.355546] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[47224.007773] eth0: renamed from vethd6a07f7
[57133.634876] vethd6a07f7: renamed from eth0

Why this is happening and the main adapter switch name with the docker adapter?

Looking forward,

Thank you

**Comment by Braintelligence** [comment]
Please do not expect an answer if you don't fill out the issue template.

Thank you

**Comment by patschi** [comment]
No further information provided, therefore closed. Beside that it seems for me like an issue independently from mailcow.
