### ISSUE TITLE
How to migrate all my emails from cpanel to mailcow

### ISSUE THREAD

**Issue by blueray453** [mailcow/mailcow-dockerized#2778]
Recently I decided to change my hosting provider.

When I asked the prospective providers to transfer my emails, they said and I quote -

> We offer free data migration service if you are using cPanel control panel with your current hosting company (most companies use cPanel, such as GoDaddy/HostGator/etc) and are planning to purchase any of our cPanel packages (Linux Shared, VPS/Cloud with cPanel control panel).

I have CPanel in my current hosting, however I am feeling a little locked down as the prospective provider is saying that I must have CPanel. 

Now, I want to migrate all my cpanel email to mailcow (installed in a VPS). How can I do that?

**Comment by dominicpratt** [comment]
The easiest way is to use [Sync Jobs](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-sync_jobs_migration/) in Mailcow.

Just put in your current mailserver configuration (e.g. imap.hosting.com, Username, Password) and let Mailcow do its magic.

**Comment by blueray453** [comment]
Thanks

**Comment by crosskpixel** [comment]
Some know how migrate mailcow to cpanel.
