### ISSUE TITLE
Which open source projects do mailcow use? 

### ISSUE THREAD

**Issue by blueray453** [mailcow/mailcow-dockerized#2779]
What is the technology stack of mailcow? For example modoboa uses -

- Database server (PostgreSQL or MySQL)
- Nginx and uWSGI
- Postfix
- Dovecot
- Amavis (with SpamAssassin and ClamAV)
- automx (autoconfiguration service)
- OpenDKIM
- Radicale (CalDAV and CardDAV server)

**Comment by dominicpratt** [comment]
Off the top of my head:

- Docker
- MariaDB as Database
- Dovecot as IMAP-Server
- Postfix as MTA
- NGINX
- PHP
- SOGo
- Unbound DNS
- RspamD
- Redis
- Memcached
- ClamD
- Solr
- Netfilter

Not sure if this is a complete list though.

**Comment by Braintelligence** [comment]
Did you read the docs before posting @blueray453 ? https://mailcow.github.io/mailcow-dockerized-docs/

Most if not everything from the stack is in there.
