### ISSUE TITLE
SOGo

### ISSUE THREAD

**Issue by SemikolonDEV** [mailcow/mailcow-dockerized#278]
Hey,

i have updated Mailcow yesterday since the Update the SOGo Webinterface redirects after the login to https://127.0.0.1:8463/SOG

Regards
Jan-Lukas Pagel

**Comment by andryyy** [comment]
Please see the docs for a proper reverse proxy setup. 

> Am 16.05.2017 um 16:34 schrieb Jan-Lukas Pagel <notifications@github.com>:
> 
> redirects
