### ISSUE TITLE
SSL Certificate wrong

### ISSUE THREAD

**Issue by mailcowissue** [mailcow/mailcow-dockerized#2780]
http://prntscr.com/oetbe5
^
Is my conf file, generated before installing / running

My problem is this, the SSL certificate has, and is being generated for mail.example.org not mail.anonmail.cc as it should be doing.

![image](https://user-images.githubusercontent.com/52883571/61183320-eceedd00-a637-11e9-870b-8eb5884e0d14.png)

**Comment by mkuron** [comment]
Please check the ACME container's log (`docker-compose logs acme-mailcow`) and make sure that your DNS record has fully propagated. The latter can take up to 24 hours.

**Comment by mailcowissue** [comment]
> Please check the ACME container's log (`docker-compose logs acme-mailcow`) and make sure that your DNS record has fully propagated. The latter can take up to 24 hours.

![image](https://user-images.githubusercontent.com/52883571/61183853-4528dd80-a63e-11e9-88d8-9257d198473c.png)
^ Log output

Also DNS is fully propagated, I use CF does almost instantly but even so it's been like 30+ hours.

**Comment by mkuron** [comment]
That's not the log output. These are the error messages `docker-compose` prints when mailcow.conf doesn't exist or .env is not a symlink to it. Please run the command in the top-level directory /opt/mailcow-dockerized. If the same error messages are printed, please check your config file.

**Comment by fm** [comment]
Also, you can restart the acme container with `docker-compose restart acme-mailcow` or via the admin UI -> System Information to force it to re-lookup and issue certs if needed

**Comment by patschi** [comment]
As there's no further reply from the author I'm closing this ticket now.
