### ISSUE TITLE
Has the Nextcloud Auto-Updater been deactivated?

### ISSUE THREAD

**Issue by lotg2020** [mailcow/mailcow-dockerized#2784]
It seems that the auto-updater has been deactivated. 

According to the security scan of the official website, the patch level is outdated. 

Is there a way to reactivate it permanently? I don't use the plugin "external User" anyway. 

Many thanks in advance.

**Comment by GrantZero** [comment]
It is all okay. 
![nextcloud](https://user-images.githubusercontent.com/46645526/61538334-76881b80-aa39-11e9-8ce1-658277d792ab.png)

**Comment by lotg2020** [comment]
Solved!
