### ISSUE TITLE
R_DKIM_PERMFAIL

### ISSUE THREAD

**Issue by lug-gh** [mailcow/mailcow-dockerized#2785]
**Describe the bug, try to make it reproducible**
If I recieve mails from a specific domain they always get headers added to the mails through rpsamd.

R_DKIM_PERMFAIL (10) [example.org:s=dkim]

I checked rspamd config and all I could do is to set this to another value, but that doesn't really solve the problem.

Strange thing is, the senders domain doesn't even use dkim, so I wonder why this error happens and the score is so high, as many (many many many) providers don't use dkim.

**System information and quick debugging**
General logs:
- I don't think they're needed here, if you need them I'll provide later.

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?)
ubuntu 18.04 (apparmor yes i guess)
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)
lxc
 - Your server/VM specifications (Memory, CPU Cores)
4GB and 4 cores
 - Don't try to run mailcow on a Synology or QNAP NAS, do you?
hell no
 - Docker and Docker Compose versions:
Docker version 18.09.1, build 4c52b90
docker-compose version 1.24.1, build 4667896b
 - Output of `git diff origin/master`, any other changes to the code?
```
diff --git a/data/conf/dovecot/dovecot.conf b/data/conf/dovecot/dovecot.conf
index cf6b5d12..fea6544c 100644
--- a/data/conf/dovecot/dovecot.conf
+++ b/data/conf/dovecot/dovecot.conf
@@ -32,6 +32,7 @@ ssl_min_protocol = TLSv1
 
 ssl_prefer_server_ciphers = yes
 ssl_cipher_list = ALL:!ADH:!LOW:!SSLv2:!SSLv3:!EXP:!aNULL:!eNULL:!3DES:!MD5:!PSK:!DSS:!RC4:!SEED:!IDEA:+HIGH:+MEDIUM
+#ssl_cipher_list = ALL:!LOW:!SSLv2:!EXP:!aNULL:!ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5
 
 # Default in Dovecot 2.3
 ssl_options = no_compression
diff --git a/data/conf/nginx/site.conf b/data/conf/nginx/site.conf
index ccb94fa0..9eac0d7a 100644
--- a/data/conf/nginx/site.conf
+++ b/data/conf/nginx/site.conf
@@ -7,6 +7,13 @@ map $http_x_forwarded_proto $client_req_scheme {
      https https;
 }
 
+server {
+  listen 8080 default_server;
+  listen [::]:80 default_server;
+  include /etc/nginx/conf.d/server_name.active;
+  return 301 https://$host$uri$is_args$args;
+}
+
 server {
   include /etc/nginx/mime.types;
   charset utf-8;
```

**Comment by andryyy** [comment]
They probably DO sign the headers with broken DKIM. 

The messages full source would be helpful.

**Comment by lug-gh** [comment]
Sorry my bad, they do use dkim to sign mails, but there's no dkim key in the dns zone.
Thanks!

**Comment by mkuron** [comment]
Actually, this is a valid bug report. I checked the DKIM RFC and it basically says that signatures should be ignored if their selector can't be resolved in DNS. So 
R_DKIM_PERMFAIL should have a zero score and the message should be treated as if it was unsigned.
