### ISSUE TITLE
Where do I find my mail attachments?

### ISSUE THREAD

**Issue by devandrea27** [mailcow/mailcow-dockerized#2793]
Hello everyone, I want to know, where does the attachments get saved on the server? I know it's something like "/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain/username"
But inside the folder I dont find any files that are let's say "human readable", can you guys provide any help on this, sorry for the inconvenice.

Thanks in advance

**Comment by andryyy** [comment]
We use maildir by default, they are inside the vmail volume as part of the message file. :)
