### ISSUE TITLE
Restore-Script: Option for "restore all"

### ISSUE THREAD

**Issue by simonszu** [mailcow/mailcow-dockerized#2794]
**Is your feature request related to a problem? Please describe.**
I am running Mailcow in an LXC container. Due to the recent Debian Upgrade from Stretch to Buster, i recreated the container, and wanted to import a backup to Mailcow. This worked fine, except: I had to execute the restore script 6 times, each time selecting a different backup dataset (SQL, Postfix, Redis, Rspamd, ...). I did not know the right order, so i selected the options from bottom-up. This seemed to work but was uncomfortable. 

**Describe the solution you'd like**
An option in the restore script to restore _all_ datasets, for setting up a Mailcow setup from scratch with the help of a previous backup. This option should restore all tools in the right order.

**Comment by timo-reymann** [comment]
@andryyy I created a pr for this one, i was not sure about the order, so if you have any better ideas for the order or some way to do this better, just tell me and i will fix that :)

**Comment by andryyy** [comment]
Can you change it to only select existing backups, when you choose "all"? :)
