### ISSUE TITLE
How to change sogo expire-session value

### ISSUE THREAD

**Issue by dokbua** [mailcow/mailcow-dockerized#2798]
I want to change the expire-session value in the sogo container. It is presently set to 60:

```
root@198603e06625:/etc/cron.d# cat sogo
* * * * *   sogo   /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null
* * * * *   sogo   /usr/sbin/sogo-tool expire-sessions 60
0 0 * * *   sogo   /usr/sbin/sogo-tool update-autoreply -p /etc/sogo/sieve.creds
```

I added a line in docker-compose.yml under php-fpm-mailcow:
        - ./data/conf/sogo-cron:/etc/cron.d/sogo
But it isn't created when I restart php-fpm-mailcow. 

What am I doing wrong?  Is there a better way to accomplish this?

**Comment by mkuron** [comment]
You need to modify the sogo-mailcow container, not the php-fpm-mailcow container. Then you should be able to put your crontab into the file ./data/conf/sogo-cron.

Maybe we should increase the limit to something more reasonable, like 8 hours. One hour is indeed a bit short if you just want to leave the webmail open so you can see new mails as they come in.

**Comment by dokbua** [comment]
I see. Just out of curiosity, why is there a /etc/cron.d/sogo in the php-fpm-mailcow container if it is not used? It is a bit confusing?
Anyway, I removed the line in php-fpm-mailcow, and added one for the sogo-mailcow container, like this:
        - ./data/conf/sogo-cron:/etc/cron.d/sogo

restarted it, but still no link under ./data/conf?

**Comment by andryyy** [comment]
This would create a new file ./data/conf/sogo-cron and mount it as /etc/cron.d/sogo.

You probably have that file in php-fpm-mailcow because of your tries to mount a file into the container.

Anyway, I made this configurable now (will push in a bit). Default is 8 hours.

**Comment by dokbua** [comment]
> This would create a new file ./data/conf/sogo-cron and mount it as /etc/cron.d/sogo.
> 
> You probably have that file in php-fpm-mailcow because of your tries to mount a file into the container.
> 
> Anyway, I made this configurable now (will push in a bit). Default is 8 hours.

Yes, I understand how volumes work, and that is what I expected, but as I explained before, nothing is created under ./data/conf where all the other volumes are present. That is what confuses me.

Regarding the php-fpm-mailcow it was the other way around. I looked in all the containers until i found the /etc/cron.d/sogo, and only after that did I try to add it as a volume.

**Comment by andryyy** [comment]
There is no `/etc/cron.d/sogo` in our default php-fpm-mailcow images.

```
# docker-compose exec php-fpm-mailcow /bin/bash -c "ls -la /etc/cron.d"
ls: /etc/cron.d: No such file or directory
```

**Comment by dokbua** [comment]
You're right, sorry. I must have mixed them up somehow. 

Still, it does exist in sogo-mailcow:
```
[root@vm3314 mailcow-dockerized]# docker-compose exec sogo-mailcow /bin/bash -c "cat /etc/cron.d/sogo"  
* * * * *   sogo   /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null
* * * * *   sogo   /usr/sbin/sogo-tool expire-sessions 60
0 0 * * *   sogo   /usr/sbin/sogo-tool update-autoreply -p /etc/sogo/sieve.creds
```
I added this in docker-compose.yml under sogo-mailcow:
```
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      volumes:
        - ./data/conf/sogo-cron:/etc/cron.d/sogo
        - ./data/conf/sogo/:/etc/sogo/
```
restarted sogo-mailcow, but still no sogo-cron under data/conf:
```
[root@vm3314 mailcow-dockerized]# docker-compose restart sogo-mailcow
Restarting mailcowdockerized_sogo-mailcow_1 ... done
[root@vm3314 mailcow-dockerized]# ls data/conf
clamav  dovecot  mysql  nginx  phpfpm  postfix  rspamd  sogo  unbound
```

**Comment by mkuron** [comment]
> still no sogo-cron under data/conf

The volume works the other way round. It makes ./data/conf/sogo-cron from outsider the container available as /etc/sogo inside the container. If the former is empty or doesn‘t exist, you‘ve just removed the cron jobs.

However, the latest version now has a configurable timeout option, so none of this should be needed.

**Comment by SDS1337** [comment]
> However, the latest version now has a configurable timeout option, so none of this should be needed.

@mkuron Do you mind sharing how? I can't find where to do that

**Comment by LovesTha** [comment]
Is it `$SESSION_LIFETIME` in `data/web/inc/vars.local.inc.php`? As I'd expect that to be the mailcow UI session timeout and I can't find a relevant setting in `data/conf/sogo/sogo.conf`, so like SDS1337 I'd love to know which setting is to be used.
