### ISSUE TITLE
Changing http binding port in Mailcow.conf  is not working

### ISSUE THREAD

**Issue by klient92** [mailcow/mailcow-dockerized#2799]
I would like to deploy Mailcow in a remote server and use Nginx to be a reverse proxy. After following the [instructions](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/) to change the port within mailcow.conf, it is not working. 

> ERROR: for mailcow-dockerized_nginx-mailcow_1  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcow-dockerized_nginx-mailcow_1 (64f9c4b2e22c8e43b0412598a71335776370e717a9cd79a85b62983d49eaad5a): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

>ERROR: for nginx-mailcow  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcow-dockerized_nginx-mailcow_1 (64f9c4b2e22c8e43b0412598a71335776370e717a9cd79a85b62983d49eaad5a): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

No matter what port number I changed, it always indicates that 0.0.0.0:443 is in use

**Comment by DatAres37** [comment]
Are you also changing the IP to 127.0.0.1 and are you recreating the containers?

What happens when you manually change the ports in the docker-compose file?

**Comment by klient92** [comment]
@DatAres37 I also set the IP to 127.0.0.1 and used `docker-compose up -d` to recreate the container and it was still not working.
It works when I change the docker-compose file, but I saw some people advised it is better not changing the configuration of this file.

**Comment by andryyy** [comment]
Perhaps .env is not a link to mailcow.conf.

**Comment by klient92** [comment]
May I ask where .env file is?

**Comment by andryyy** [comment]
In the root directory of mailcow-dockerized.

**Comment by infinitebayas** [comment]
https://www.bennetrichter.de/en/tutorials/mailcow-dockerized/ 
Will get you more clarity on the ports.
one of the best i came across.
