### ISSUE TITLE
Bind: address already in use

### ISSUE THREAD

**Issue by skupfer** [mailcow/mailcow-dockerized#28]
I didn't get attention on forums so I am going to open an issue about this here

I am running a debian 8 server with several services and pulled the most recent mailcow-dockerized. During the setup I encountered the following errors:

    ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external     connectivity on endpoint mailcowdockerized_postfix-mailcow_1: Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use

    ERROR: for nginx-mailcow  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_nginx-mailcow_1: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

Obviously exim4 is installed on the server blocking port 25. Easy to fix if I simply remove it (but what to use for internal mails then?)

For 443 nginx is installed on my server which I need as the reverse proxy for my services... I was hoping I could use the dockerized mailcow without having to mess with my existing system. This was one of the reasons I tried to dockerize it with a friend (but we didn't know about docker networks back then)...

Any ideas how to handle the 443 conflict? Thought about using a different port but I don't know if this would mess up something else.

I am looking forward to hearing from you.

Best regards

**Comment by psi-4ward** [comment]
Hey how. 

For Postfix you can either *open* mailcow-postfix to accept your "internal" mails or use exim4 to relay the mails via mailcow. I use a normal postfix installation on my hostsystem without port binding (comment smtp in master.cf) and forward the mails to mailcow.

For Nginx, just dont use the mailcow nginx container and configure your nginx to directly use the fpm container.

**Comment by skupfer** [comment]
hey there.

Could you guide me through this process or setup an wiki entry?

Also I would like to ask in which way the update/upgrade process would be hindered due to changes to the docker-compose to exclude the nginx-container. I guess the yml doesn't need changes that often but it could be an issue.

best regards

**Comment by mis4s** [comment]
In `mailcow.conf` change `HTTPS_PORT=443` to `HTTPS_PORT=127.0.0.1:4443` and now setup proxy in "natvie" nginx. Mailcow listen now on `localhost:4443`.

**Comment by skupfer** [comment]
Going to close this for now even if I am not able to get it to work. Cannot get a proper nginx.conf and not at all used to postfix/MTAs so I don't know what to change. Still in hope somebody could post a complete tutorial or wiki entry for this.
Btw. I understand the change in mailcow.conf but I guess you would still have to remove nginx from docker-compose?
EDIT: I guess there are others users who are running an already existent environment with nginx/apache in use and/or any MTA ...

**Comment by PhoenixPeca** [comment]
Hi @skupfer,
I'm sorry if i'm late in the party.
Postfix can't start its process because the port 25 is blocked by **exim4*** pre-installed email service in debian.

So a quick fix would be to purge exim4 with this command: `apt-get purge exim4*`

**Comment by mjapple** [comment]
Hi
I am using httpd and the ports are being used by httpd (both ports 80 and 443)
now i get the same errors 
`for nginx-mailcow  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_nginx-mailcow_1`

i did try the HTTPS_PORT=127.0.0.1:4443 
and i did try with adding virtual host to httpd/conf.d folder 


```
cat <<EOF | sudo tee -a /etc/httpd/conf.d/mailcow.conf
<VirtualHost *:8080>
ServerAdmin mail@domain.ltd
DocumentRoot /var/www/html/mail.domain.ltd/
ServerName mail.domain.ltd
ServerAlias www.mail.domain.ltd
<Directory /var/www/html/mail.domain.ltd/>
Options FollowSymLinks
AllowOverride All
Order allow,deny
allow from all
</Directory>
ErrorLog /var/log/httpd/mail.domain.ltd-error_log
CustomLog /var/log/httpd/mail.domain.ltd-access_log common
</VirtualHost>
EOF
```
but yet i cant load the page

**Comment by andryyy** [comment]
You need to read the docs about how to setup a reverse proxy. :)

https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

**Comment by ghost** [comment]
> HTTPS_PORT=127.0.0.1:4443

work it.

**Comment by ThinhVu** [comment]
> Going to close this for now even if I am not able to get it to work. Cannot get a proper nginx.conf and not at all used to postfix/MTAs so I don't know what to change. Still in hope somebody could post a complete tutorial or wiki entry for this. Btw. I understand the change in mailcow.conf but I guess you would still have to remove nginx from docker-compose? EDIT: I guess there are others users who are running an already existent environment with nginx/apache in use and/or any MTA ...

For one who still struggle with this issue. Here is a step by step guide:

1. edit mailcow.conf using `vi mailcow.conf`
```
HTTP_PORT=8080
HTTP_BIND=

HTTPS_PORT=8443
HTTPS_BIND=
```

2. add nginx config file for your mail server domain. For example if your mx domain is `mx.abc.com` then create a nginx config file at `/etc/nginx/sites-enabled/com.abc.mx` like so:
```
server {
  server_name mx.abc.com;
  location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}  
```

3. reload nginx: `nginx -s reload`

4. issue SSL/TLS using certbot using `certbot --nginx -d mx.abc.com --redirect`, a few lines will be added to the config file.

```
server {
  server_name mx.abc.com;
  location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mx.abc.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mx.abc.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mx.abc.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    
    server_name mx.abc.com;
       listen 80;
       return 404; # managed by Certbot
}
```

5. edit the file again, change `443` to `8443`
