### ISSUE TITLE
olefy-mailcow - errors im Logfile

### ISSUE THREAD

**Issue by johann8** [mailcow/mailcow-dockerized#2800]
**Describe the bug, try to make it reproducible**
Es gibt einen Fehler im Logfile von olefy Container und zwar:
dclogs olefy-mailcow:
olefy-mailcow_1      | olefy ERROR eof_received Protocol ERROR: no OLEFY/1.0 found)
olefy-mailcow_1      | olefy INFO eof_received ('172.22.1.3', 43176) response send: b'[ { "error": "Protocol error" } ]'
olefy-mailcow_1      | olefy INFO eof_received <> 0 bytes (stream size)

Diese drei Zeilen wiederholen sich alle ein paar Minuten. 
Im clamd Container selbst gibt es keine Fehlermeldungen. Wenn ich versuche von olefy container aus den clamd Container anzupingen, dann kommt folgendes:

dcexec olefy-mailcow ping 172.22.1.3
PING 172.22.1.3 (172.22.1.3): 56 data bytes
ping: permission denied (are you root?)

Von z.B nginx Container kann ich anpingen:
dcexec nginx-mailcow ping 172.22.1.3
PING 172.22.1.3 (172.22.1.3): 56 data bytes
64 bytes from 172.22.1.3: seq=0 ttl=64 time=0.358 ms

Der Dienst selbst im Conrtainer läuft:
dcexec olefy-mailcow netstat -tulpan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:43931        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:10055           0.0.0.0:*               LISTEN      1/python3
udp        0      0 127.0.0.11:60339        0.0.0.0:*  

Für einen Hinweis wäre ich sehr dankbar!

**System information and quick debugging**

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?) CentOS Linux release 7.6.1810, SELinux deaktiviert
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.) KVM
 - Your server/VM specifications (Memory, CPU Cores)30 GB. 8 Cores
 - Don't try to run mailcow on a Synology or QNAP NAS, do you? Nein
 - Docker and Docker Compose versions
docker -v : Docker version 1.13.1, build b2f74b2/1.13.1
dc -v : docker-compose version 1.24.1, build 4667896b
 - Output of `git diff origin/master`, any other changes to the code? Keine

**Comment by andryyy** [comment]
Hi,

Please try to keep it English.

The errors are "ok", as we run a very basic TCP check in watchdog-mailcow to monitor olefy.

You can ignore them until @c-rosenberg found time to integrate a "ping? pong!" event. :)

**Comment by johann8** [comment]
Hello andryyy,

thank you very match for the answer.
