### ISSUE TITLE
Clamav does not find viruses

### ISSUE THREAD

**Issue by lotg2020** [mailcow/mailcow-dockerized#2801]
Clamav doesn't seem to detect any viruses. 

To test I requested the Eicar virus from Heise:
https://m.heise.de/security/dienste/Mails-mit-Viren-Dummies-777839.html

In mailcow.conf clamav is active so skip =n. 

Are there any other files I can check?

Thank you.

**Comment by andryyy** [comment]
Eicar is not detected by Rspamd, it ignores it. You may find "JUST_EICAR" in the symbols.

**Comment by lotg2020** [comment]
Perfect, thanks for the quick info.

Closed!
