### ISSUE TITLE
solr image

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#2805]
Since the solr-mailcow image is the last image based on Alpine 3.9, I took a closer look.
As it looks, solr no longer offers the tag [solr:7.7-alpine](https://github.com/mailcow/mailcow-dockerized/blob/85f20a901db8aefd7cecfd61b32c4e99a9beb103/data/Dockerfiles/solr/Dockerfile#L1). Please update the image to a maintained tag.

[solr remove Alpine](https://github.com/docker-solr/docker-solr/commit/d6e4780449d3517718e794e59c46214ee3a79f50)
[maintained  solr tags ](https://hub.docker.com/_/solr/?tab=description&page=2)

**Comment by andryyy** [comment]
Thanks, yes, I have seen it. I don't know if I really want to keep Solr. :/

**Comment by christianbur** [comment]
Fixed https://github.com/mailcow/mailcow-dockerized/commit/fb22540f74379f5c99018b51526649a4780f99ea
