### ISSUE TITLE
RFC characters on emails

### ISSUE THREAD

**Issue by Fastidious** [mailcow/mailcow-dockerized#2807]
I was able to add an email like this, `~user/example@example.com` on the [Demo](https://demo.mailcow.email). That is great! I like—and want—the ability to create emails with `~`, and `/`, but that will break editing such user. So, a bug?

**Comment by Fastidious** [comment]
A workaround is not to create users like that, but instead use the `~user/example@example.com` as an alias. ~~On the demo it works like a charm~~. Sending an email to it, though, using Sogo, will not work.

**Comment by andryyy** [comment]
The failing edit is a "bug" in the rewrite in site.conf, I can confirm that. You could workaround this bug by using /edit.php?mailbox=blabla@blabla

Sending a mail to it: We would need postfix-mailcow and dovecot-mailcow logs.

Edit: Sending a mail in the demo might not work!

**Comment by Fastidious** [comment]
There are a few things at play. Dovecot has some default settings specifying certain allowed characters. Postfix will also choke with certain characters that are, per RFC, allowed (# is one of them). So, more than miss the eye.

I recommend you don’t allow the creation of emails with such characters. It is the safest way.
