### ISSUE TITLE
How to allow unencrypted SMTP mail delivery?

### ISSUE THREAD

**Issue by JulianZ98** [mailcow/mailcow-dockerized#2808]
I installed the latest version of Mailcow on my Debian 10 server and I need to be able to send emails using SMTP without encryption, so without SSL/TLS. The reason for this is, that I have several IP cameras outside my LAN that should send emails to an external email address using my Mailcow server and the firmware of some of these IP cameras is so old, that it doesn't support SMTP with encryption...

Is there a way to achieve this unencrypted SMTP mail delivery with Mailcow? I found no option in the webinterface and I already tried to change the Postfix main.cf, but then I still got "Relay access denied"... If I add my IP address to "mynetworks" in the Postfix main.cf, I can send an email, but then I often get "5.7.1 Spam message rejected". I guess, it should be also possible to disable the spam protection completely?

**Comment by fm** [comment]
You can add the IP as a forwarding host and have it skip spam filtering, then add the IP to "mynetworks" in Postfix's main.cf

Out of curiosity, have you tried port 25? That is usually the default unencrypted SMTP port. Unless you mean with no authentication (an open relay)

**Comment by JulianZ98** [comment]
Thanks for the answer, I'll try that out later. The problem is, that there are several IP cameras with normal home internet connections (dynamic, changing IP addresses) and I don't know which IP address they are using to send the mails.

And yes, I used port 25 for SMTP and there I'm getting the error message "Relay access denied". I've set up the SMTP server for my mail account in Thunderbird for testing purposes and I selected "None" as the "Connection security". I also selected "Password, transmitted insecurely" as "Authentication method".

If I use port 587 without encryption, I'm getting the error message "Must issue a STARTTLS command first".

**Comment by fm** [comment]
`Relay access denied` usually means the system did not authenticate properly to send emails (either with a mailbox credentials, or via IP whitelisting), and since mailcow is a closed-relay (as it should, or else you'd become a spam-sending magnet in seconds), it does not allow unauthenticated mail out. 

I want to make sure I understand you, are you using the credentials to a mailbox to authenticate to the SMTP server?

**Comment by JulianZ98** [comment]
Yes, I'm using the email address of the mailbox as the username and the password I defined. I've tested it with a tool called "SMTP Prober" as well as with Mozilla Thunderbird and I'm getting the error `5.7.1 <RecipientEmailAddressHere>: Relay access denied.` If I change the port in Thunderbird to 465 and select "SSL/TLS" in the dropdown called "Connection security" (same username and password), it works immediately.

The setting called "Authentication method" in Thunderbird automatically switches from "Password, transmitted insecurely" to "Password, normal" when I select SSL/TLS, but in both cases I'm using (and transmitting) the same username (email address) and password.

Another thing that I saw is, that, if I'm using port 25 without encryption, I'm getting the error message `5.7.1 Service unavailable; client [1.2.3.4] blocked using zen.spamhaus.org` where "1.2.3.4" is my dynamic public IP address that I got from my ISP. Of course, these dynamic IPs are often listed on mail blacklists, but when I'm using port 465 and SSL/TLS, it works fine without blocking... So there must be a difference when using port 25 too. Because of this, I had to set `postscreen_dnsbl_action` in Postfix's main.cf zu "ignore". After changing this setting, I was at least able to prevent this client blockage, but I then got the relay error message. I hope that changing this setting isn't causing the relay problem.

**Comment by JulianZ98** [comment]
When I'm using port 25 and no encryption/secured connection (now I've also used smtper.net to test), this appears between the connect and disconnect message in Postfix's log. I replaced the FQDN of my ISP's IP with "ipXXXXXXXXXX.dynamic.my-isp.com", my ISP's IP with "1.2.3.4", the recipient address (Gmail) with "mail@recipient-address.com" and my mailcow mail address that I'm using to send the emails with "mail@mailcow-address.com".

`postfix-mailcow_1    | Jul 28 14:30:23 mail postfix/smtpd[357]: NOQUEUE: reject: RCPT from ipXXXXXXXXXX.dynamic.my-isp.com[1.2.3.4]: 554 5.7.1 <mail@recipient-address.com>: Relay access denied; from=<mail@mailcow-address.com> to=<mail@recipient-address.com> proto=ESMTP helo=<[192.168.170.13]>`

But when I use port 465 with SSL/TLS, it looks like this:
`postfix-mailcow_1    | Jul 28 14:31:19 mail postfix/smtpd[350]: Anonymous TLS connection established from ipXXXXXXXXXX.dynamic.my-isp.com[1.2.3.4]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)`

`postfix-mailcow_1    | Jul 28 14:31:20 mail postfix/smtpd[350]: 30376981D3B: client=ipXXXXXXXXXX.dynamic.my-isp.com[1.2.3.4], sasl_method=PLAIN, sasl_username=mail@mailcow-address.com`

`postfix-mailcow_1    | Jul 28 14:31:20 mail postfix/cleanup[360]: 30376981D3B: message-id=<4333a5a4-c23b-5de2-e508-080c2e3f6f11@mailcow-address.com>`

`postfix-mailcow_1    | Jul 28 14:31:21 mail postfix/qmgr[333]: 30376981D3B: from=<mail@mailcow-address.com>, size=792, nrcpt=1 (queue active)`

And then, a few seconds later, there are more log entries for the connection to Gmail and so on.

**Comment by JulianZ98** [comment]
Okay, now I've finally got it working. I've set the value of the parameter `smtpd_tls_auth_only` in Postfix's main.cf from "yes" to "no". I also allowed SASL authentication for SMTP on port 25 in Postfix's master.cf file by changing the value for `smtpd_sasl_auth_enable` from "no" to "yes".

Now I can send e-mails (with a correct user authentication) via SMTP using port 25 without encryption as well as using e.g. port 465 with SSL/TLS. Thanks again for the quick answers!

**Comment by RickD123** [comment]
Hi, can you share your config? I tried to set both smtpd_tls_auth_only to no and smtpd_sasl_auth_enable to yes and it still does not work for me. Whenever I try to connect to port 25 with SSL or without, authentication via "password" and port 25 it does not work for me. Whenever I have a client sending mail, I am getting a "server does not support password authentication error".

**Comment by andryyy** [comment]
Postscreen is on port 25. Don't do that. There are two ports for submission available (465 wrapped, 587 starttls). :)

**Comment by JPaulMora** [comment]
Hi, I'm trying to do the same thing but @JulianZ98 's solution didn't work for me. I've read a bunch of blogs and documentation which seem to change the same parameters, yet port 25 doesn't let me do `AUTH PLAIN`

**Comment by dragoangel** [comment]
@JPaulMora because 25 port is designed for MTA to MTA . You need 587 port. Also I curious why at all people need plain auth? This provide 0 security. If you have some app/service/software/hardware that can't use ssl auth - add as Forward host via mailcow UI and send mail without credentials at all, just by IP. 

Note: you can do this safe only in case:

a) your device in same lan (or connected to vpn that route traffic to mailcow, eg: ipsec/openvpn, etc)

b) this device out of your lan but it has dedicated public ip where no other devices are served

**Comment by fxwgr** [comment]
@dragoangel
I've tried to add the hostname of my local device (same subnet) to that forward host without spam filter and also the IP of my local device, but both versions didn't work on port 25 without any user credentials. The only thing what changed was the result 200 from DUNNO to PERMIT.

Postfix-log:
<details>

```
20.07.2021, 00:26:37 | info | disconnect from unknown[192.168.0.6] helo=1 mail=1 rcpt=0/1 commands=2/3
20.07.2021, 00:26:37 | info | lost connection after RCPT from unknown[192.168.0.6]
20.07.2021, 00:26:37 | info | NOQUEUE:  reject: RCPT from unknown[192.168.0.6]: 504 5.5.2 <ipcamera>:  Helo command rejected: need fully-qualified hostname;  from=<myemail@provider.com>  to=<myemail2@provider.com> proto=SMTP  helo=<ipcamera>
20.07.2021, 00:26:37 | info | connect from unknown[192.168.0.6]
20.07.2021, 00:26:37 | info | WHITELISTED [192.168.0.6]:2290
20.07.2021, 00:26:37 | info | Look up 192.168.0.6 on whitelist, result 200 PERMIT
20.07.2021, 00:26:37 | info | CONNECT from [192.168.0.6]:2290 to [172.22.1.253]:25
```

</details>

How exactly do you mean to configure it?

**Comment by dragoangel** [comment]
@andi448 :
1. add `$your_ipv4/$your_ipv6` to forwarding hosts
2. configure postfix extra.cf file (adjust default subnets if you changed them):
`# Set my trusted networks
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.22.1.0/24 [fd4d:6169:6c63:6f77::]/64 $your_ipv4/32 $your_ipv6/128 ... so on ...`
3. restart postfix container

**Comment by fxwgr** [comment]
@dragoangel 
I just noticed that you can skip step 1, so you don't need to add a forwarding host.
