### ISSUE TITLE
DKIM signing fails

### ISSUE THREAD

**Issue by swdee** [mailcow/mailcow-dockerized#281]
Using commit 861ade77ab42f348dc4484491f946091af56115a (14th May) setting up mailcow with DKIM signing results in DKIM signature to fail upon verification.  

To reproduce the issue, setup mailcow, create DKIM keys, add DNS TXT record, then send test email to 	auth-results@verifier.port25.com or other mail testing provider.  Resulting report indicates DKIM check fails

```
==========================================================
Summary of Results
==========================================================
SPF check:          pass
DomainKeys check:   neutral
DKIM check:         fail
SpamAssassin check: ham
```

With reason;
```
----------------------------------------------------------
DKIM check details:
----------------------------------------------------------
Result:         fail (signature doesn't verify)
```

I have checked Redis keys DKIM_PRIV_KEYS and DKIM_SELECTORS to make sure they are populated with data (they are).   

I added debug config to data/conf/rspamd/override.d/logging.inc to cause rspamd to output DKIM signing debug with;
```
debug_modules = ["dkim"]
```

When sending mail it appears to sign it, but must calculate the wrong hash.  rspamd log output;

```
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; accept_socket: accepted connection from fd4d:6169:6c63:6f77::6 port 39880, task ptr: 00007F82A8B82130
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; rspamd_message_parse: loaded message; id: <1603319.bLJElE5Sn2@vm32>; queue-id: <F342B3DEAC>; size: 647; checksum: <1b673c983ef7b3a2922cec85ed88684d>
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; settings.lua:262: check for settings
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; fuzzy_generate_commands: <1603319.bLJElE5Sn2@vm32>, part is shorter than 100 bytes (3 bytes), skip fuzzy check
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; spf_symbol_callback: skip SPF checks for local networks and authorized users
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; once_received.lua:78: Skipping once_received for authenticated user or local network
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; ip_score.lua:297: skip IP Score for local networks and authorized users
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; dmarc.lua:101: skip DMARC checks for local networks and authorized users
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_relaxed_body_step: update signature with body buffer (2 size, 1 remain, 0 added)
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: from:SXXXXX DXXXXX <XXXXX@XXXXXX.com>
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: subject:email test
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: date:Tue, 16 May 2017 21:08:32 +1200
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: message-id:<1603319.bLJElE5Sn2@vm32>
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: to:autorespond+dkim@dk.elandsys.com, check-auth@verifier.port25.com
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: mime-version:1.0
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: content-type:text/plain; charset="us-ascii"
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: content-transfer-encoding:7bit
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; dkim; rspamd_dkim_signature_update: initial update hash with signature part: dkim-signature:v=1; a=rsa-sha256; c=relaxed/relaxed; d=coinbill.com; s=dkim; t=1494925714; h=from:subject:date:message-id:to:mime-version:content-type:content-transfer-encoding; bh=frcCV1k9oG9oKj3dpUqdJg1PxRT2RSN/XKdLCPjaYaY=; b=
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; antivirus.lua:430: CLAM_VIRUS [clamav]: message is clean
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; lua; replies.lua:101: storing message-id for replies check
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; rspamd_task_write_log: id: <1603319.bLJElE5Sn2@vm32>, qid: <F342B3DEAC>, ip: 172.22.1.1, from: <XXXXX@XXXXXX.com>, (default: F (no action): [0.40/15.00] [MID_RHS_NOT_FQDN(0.50){},MIME_GOOD(-0.10){text/plain;},DKIM_SIGNED(0.00){},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},HAS_ORG_HEADER(0.00){},RCPT_COUNT_TWO(0.00){2;},RCVD_COUNT_ONE(0.00){1;},RCVD_TLS_ALL(0.00){},TAGGED_RCPT(0.00){dkim;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 647, time: 313.334ms real, 11.166ms virtual, dns req: 0, digest: <1b673c983ef7b3a2922cec85ed88684d>, rcpts: <autorespond@dk.elandsys.com,check-auth@verifier.port25.com>, mime_rcpt: <autorespond@dk.elandsys.com>
rspamd-mailcow_1     | 2017-05-16 09:08:34 #8(normal) <f1bf04>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 3 regexps matched, 167 regexps total, 78 regexps cached, 0B bytes scanned using pcre, 648B bytes scanned total
```

Any thoughts on how to debug this further?

**Comment by swdee** [comment]
Note that recreating the rspamd container as suggested in ticket #160 does not fix anything and it shouldn't as I am using the lastest version.

**Comment by stevesbrain** [comment]
If you export a copy of your keys, remove the redis container, and create a fresh redis container (empty data volume as well), are you able to create new keys + have these keys used properly? I had a similar issue in the move between keys volume + redis store as per #272

**Comment by andryyy** [comment]
These verifiers do never help. 

So I see the mails are signed. It can also be a broken DKIM TXT record in your dns settings. Please send me a mail to info@servercow.de - I will check it then. :)

**Comment by swdee** [comment]
@andryyy thanks for your help the other day testing, our results were quite strange with some emails passing and others failing.

This morning I believe I have found the cause that may indicate where the problem lies. 

In mailcow I have two domains configured, lets call them domain1.com and domain2.com.

Using my mail client "kmail" I send an email to auth-results@verifier.port25.com with "From" address user@domain1.com, but the SMTP transport account used is user@domain2.com.  The DKIM verify report is returned showing DKIM signature as failed.

Using mail client "Thunderbird" I try the same thing above, however Thunderbird refuses to send the mail and gives error, "An error occurred while sending mail. The mail server responded:  
5.7.1 <user@domain1.com>: Sender address rejected: not owned by user user@domain2.com.".  

I reconfigure Thunderbird to send from user@domain1.com and use SMTP transport user user@domain1.com and the mail sends successfully.  The verify report returned says the DKIM signature is successful.


Based on the above experience I suspect that when sending using kmail,  rspamd is signing the email using the SMTP transport users domain DKIM key (ie: domain2.com's key).  However the email "From" address contained in the email is user@domain1.com, so when port25 does the DKIM signature check it fails as its loading domain1.com's key from DNS TXT records to verify against.

**Comment by regalstreak** [comment]
@andryyy I am having the same issue. The tester website says that email is not signed with DKIM. My domain is stadlerforms.com Can you help me out here? It's kind of urgent.

**Comment by regalstreak** [comment]
From https://github.com/mailcow/mailcow-dockerized/issues/244 I checked `docker-compose exec rspamd-mailcow ls -la /data/dkim/keys` and it is empty. I had generated the keys with the ui and added those to the dns records. How do i get them in /data/dkim/keys?

**Comment by regalstreak** [comment]
rpamd logs says: DKIM_SIGNED (0)

@Braintelligence @nmahadkar maybe yall could help me out

**Comment by andryyy** [comment]
The keys are now stored in Redis, the volume is deprecated and will be removed in a few days or weeks.

The current problem is a problem with the base64 hash in the DKIM signature. The line folding is not correct and some (and only some) rcpts fail to parse the hash correctly.

I will push the fix now.

**Comment by regalstreak** [comment]
Also, @andryyy I have a doubt which is a little off topic to this issue.
1] I have to use mailgun to escape being recieved in spam folder
For that I have to relay the mails via their smtp server.
2] But, I also have multiple domains. take hello.com and bye.com for an example. I have to add both separately on the mailgun page, and have to setup relay separately for both. They give separate relay auth username and password for hello.com and bye.com.

Is there a way I can use separate relay servers for separate domains added to mailcow?

**Comment by regalstreak** [comment]
https://community.rackspace.com/products/f/28/t/3897

**Comment by regalstreak** [comment]
Something like this is what i am trying to do, with mailcow though. How do i implement this in docker? @andryyy

**Comment by andryyy** [comment]
Something like this should work:

```
sender_dependent_relayhost_maps = hash:/opt/postfix/conf/sender_relay
```

Where data/conf/postfix/sender_relay:
```
@hello.com	[smtp.mailgun.com]
@bye.com	[smtp.mailgun.com]
```

You will already have smtp_sasl_password_maps, I guess:
```
@hello.com		user1@mailgun:password1
@bye.com		user2@mailgun:password1
```

You would need to postmap that file then.

You can check the docs for the relayhost chapter.
