### ISSUE TITLE
Anonymize header: main.cf

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#2811]
Hello, 

I updated mailcow today and I have seen that there is no definition of the anonymize header in the postfix main.cf.

I have now insert myself, but is is defined anywhere else because it don't worked before I have defined it myself. 

Thanks in advance.

**Comment by andryyy** [comment]
I don't understand. 

https://github.com/mailcow/mailcow-dockerized/blob/2061181d821694a502eff27b41b41f86ca910075/data/conf/postfix/main.cf#L137

**Comment by andryyy** [comment]
Plus you should not randomly remove headers or change them. You can break signatures. Replacing all received headers is bad practice.

The rule works as expected.
