### ISSUE TITLE
Thunderbird not accepting LE certificate

### ISSUE THREAD

**Issue by mcp-sh** [mailcow/mailcow-dockerized#2812]
Hi all, 

I set up mailcow migrated my old mailboxes over via imapsync and all seems to be running well when testing on macOS with Mail.app and on ios. 

Now I am trying to set up a windows client using Thunderbird. But the certificate is not accepted because the issuer is unknown. It shows Let's encrypt as the issuer. 

As port 80 is not available to me I am using ACME.sh DNS challenge to issue the certs and then deploy using ACME.shs' built in deploy hook. 
I verified that the certs are copied to /data/assets/ssl and the relevant containers are being restarted. 

As I said it works without porblems on Mail.app and ios, jsut Thunderbird does not want to play ball. 
Any ideas on how to get Thunderbird to accept the LE cert ? 

Thanks

**Comment by patschi** [comment]
I can imagine that Thunderbird uses the certificate storage from the OS. Is your Windows installation a more recent one and up-to-date?

**Comment by mcp-sh** [comment]
Yes it is an up to date windows 10 box, Thunderbird is the latest version downloaded today as well.

**Comment by mcp-sh** [comment]
Turns out after rolling it out on multiple clients only two out of about 20 had the issue, so it seems to have been an issue with these cleints and not related to mailcow or ACME.
