### ISSUE TITLE
Snyc of inbox not working 

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#2814]
Im not sure if this is really a bug or if i do something wrong.
I will transfer a domain to my server, so i created the mailboxes and added a sync job for a e-mail-address (only changed host, username and the password).

The folders Trash and send was successfully transfered to my mailserver, but the inbox not!
I try to transfer from 1&1 to my mail server.
Do you have any idea why the inbox is not transfered ?

**Comment by andryyy** [comment]
Have you checked the imapsync logs? Perhaps your inbox was transferred to a sub folder of mailcows inbox. In SOGo for example you need to click on the dark folder icon next to the folder name to show sub folders.

**Comment by UtechtDustin** [comment]
I removed the pattern (trash and the other one), did the sync again then the inbox was transfered :)

**Comment by andryyy** [comment]
Oh, okay. :) Nice.
