### ISSUE TITLE
New Mailbox has access for my inbox ?

### ISSUE THREAD

**Issue by UtechtDustin** [mailcow/mailcow-dockerized#2815]
As described in the last issue i create a new mailbox, the sync worked fine now.
But i have a other problem, if i login into SOGo with the new mailbox the mailbox has a folder "Other Users" in that is a Folder "INBOX" which has mails of MY mailbox.

I figured out you can grand access to a folder with a rightclick but i cant figure out how i can remove the permissions for users :o

**Comment by andryyy** [comment]
Hi, this is for issues and not for support actually. You can grant and remove access via IMAP ACL, yes. That's not a bug or a security issue, it is simply sharing IMAP permissions. :) You can use SOGo to remove it the same way you granted it.

**Comment by UtechtDustin** [comment]
Sorry i saw some minutes later that mailcow use irc too.
I tried to remove the permissions with SOGo but there is nothing to remove (i also never changed the permissions of the inbox)...

This is how it looks for the new mailboxes:
![Bildschirmfoto vom 2019-07-28 17-41-06](https://user-images.githubusercontent.com/13292481/62009401-0414eb00-b15f-11e9-895e-a9ffe154572e.png)

This are the options of the inbox of MY E-Mail-Adress:
![Bildschirmfoto vom 2019-07-28 17-41-32](https://user-images.githubusercontent.com/13292481/62009406-1000ad00-b15f-11e9-84c4-acdb14341516.png)

If i click on "user permissions", i got an modal to ADD users but i cant find a list with users which has access.
![Bildschirmfoto vom 2019-07-28 17-41-47](https://user-images.githubusercontent.com/13292481/62009412-23137d00-b15f-11e9-8602-7443426c5bcc.png)

**Comment by andryyy** [comment]
Perhaps you synced ACLs with imapsync. We never share INBOX by default. I mean, why would we?

You can show ACLs for all INBOX folders with `docker-compose exec dovecot-mailcow doveadm acl get -A 'INBOX'`

**Comment by UtechtDustin** [comment]
I know it makes no sense that mailcow will share inbox by default, but i dont understand how the acl was created :P

With your command i can see the acl
```
Username       ID   Global Rights                               
me@domain.de anyone     admin create insert lookup post read write write-deleted write-seen
```

I will try to figure out how i can delete it, thank you !

**Comment by andryyy** [comment]
Did you try "ACL_ANYONE" once? Hm.

You can delete it with doveadm acl something-something. Tell me if you need help with that.

**Comment by UtechtDustin** [comment]
Sorry i dont know what do you mean with `ACL_ANYONE`, where can i find it ?

Im already searching in the [manual](https://wiki2.dovecot.org/Tools/Doveadm) how i can do it.
If i need help i will ask :)

**Comment by MAGICCC** [comment]
Did you ever set `ACL_ANYONE` to `allow` in your mailcow.conf?

**Comment by UtechtDustin** [comment]
No its set to `disallow`.

**Comment by UtechtDustin** [comment]
Okay got it fixed with
```
docker-compose exec dovecot-mailcow doveadm acl delete -u <user> <mailbox> <id>
```
