### ISSUE TITLE
ACL unlimited Mailbox Quota not work

### ISSUE THREAD

**Issue by flo1212** [mailcow/mailcow-dockerized#2818]
The domain administrator can always set a "0" = "unlimited" when creating a mailbox.

![bug](https://user-images.githubusercontent.com/16955926/62053516-0b4bff80-b218-11e9-899c-e7197ae5df9a.png)

This attitude should be prohibited by the ACL, but dit not work

![bug2](https://user-images.githubusercontent.com/16955926/62053618-4bab7d80-b218-11e9-93ed-eff3792c1c6f.png)

**Comment by andryyy** [comment]
Thanks! Fixed it.

**Comment by flo1212** [comment]
good Job!
