### ISSUE TITLE
Client can't connect to the server

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#2819]
After updating to the latest version, my mail clients (Mailspringer, Thunderbird)
are unable to connect with the server.
Thunderbird says password is invalid and Mailspringer doesn't seem to want to connect at all.
The dovecot logs don't give a clear indication of what is wrong.
Tried it on the 143 IMAP port and 993, both same issue.
I'm thinking it might be something with encryption?

Has anything special changed to dovecot last couple of months?
Checking it manually with openssl works from remote.
SOGo also works, Outlook app on phone also works.
Mailspringer / Thunderbird do not.

**Comment by Braintelligence** [comment]
Why didn't you provide logs as the issue template says?
