### ISSUE TITLE
http to https redirect in combination with custom subdomain breaks cert validity

### ISSUE THREAD

**Issue by siggislim** [mailcow/mailcow-dockerized#2821]
Hi there,

I would like to use mailcow with a redirect from http to https and with the subdomain webmail like webmail.example.org. 
So I did the following from documentation: 
I added the webmail subdomain like described here: 
https://mailcow.github.io/mailcow-dockerized-docs/u_e-webmail-site/
which works fine. 

After that I added the redirect from http to https like describe here: 
https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

I restarted the services after the changes. Unfortunately this break validity of the SSL certificate obtained by the acme client. 

It seems like the cert for webmail.example.org is delivered but the cert for the server name itself (where I can access mailcow itself) should be delivered. How can i change this?

**Comment by andryyy** [comment]
I don't understand. Any logs from acme mailcow? Or perhaps you can tell us which names are currently in your certificate and which are missing. 

Mit besten Grüßen
André Peters

**Comment by siggislim** [comment]
Hi André,
thanks for your answer. After setting the redirect to https and restarting nginx and acme the acme client says: 
Tue Jul 30 13:56:49 CEST 2019 - Found orphaned SAN autoconfig.example.org autodiscover.example.org mail.example.org
The only domain name left is webmail.example.org and that's why I receive an error. 

In my mailcow.conf I have only one SAN which is webmail the rest is generated by default, isn't it? 
`ADDITIONAL_SAN=webmail.example.org`

any ideas?

**Comment by andryyy** [comment]
I will test it. :)

**Comment by andryyy** [comment]
Works fine here. I added the webmail stuff, worked fine, added the redirect (and kept the webmail stuff), worked fine.

```
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Validated CAA for parent domain mailcow.email
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Found AAAA record for autodiscover.develcow.de: 2a00:f820:417:0:80:77:26:247 - skipping A record check
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Confirmed AAAA record with IP 2a00:f820:417:0:80:77:26:247, adding SAN
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Found AAAA record for autoconfig.develcow.de: 2a00:f820:417:0:80:77:26:247 - skipping A record check
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Confirmed AAAA record with IP 2a00:f820:417:0:80:77:26:247, adding SAN
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Found AAAA record for mx.mailcow.email: 2a00:f820:417:0:80:77:26:247 - skipping A record check
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Confirmed AAAA record 2a00:f820:417:0:80:77:26:247
acme-mailcow_1       | Validated CAA for parent domain mailcow.email of webmail.mailcow.email
acme-mailcow_1       | Tue Jul 30 14:45:47 CEST 2019 - Found AAAA record for webmail.mailcow.email: 2a00:f820:417:0:80:77:26:247 - skipping A record check
acme-mailcow_1       | Tue Jul 30 14:45:48 CEST 2019 - Confirmed AAAA record with IP 2a00:f820:417:0:80:77:26:247
acme-mailcow_1       | Tue Jul 30 14:45:48 CEST 2019 - Found new SAN autoconfig.develcow.de autodiscover.develcow.de mx.mailcow.email webmail.mailcow.email
acme-mailcow_1       | Tue Jul 30 14:45:48 CEST 2019 - Creating backups in /var/lib/acme/backups/2019-07-30_14_45_48/ ...
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Found domains: autoconfig.develcow.de, autodiscover.develcow.de, webmail.mailcow.email, mx.mailcow.email
acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Directory found!
acme-mailcow_1       | Registering account...
acme-mailcow_1       | Registered!
acme-mailcow_1       | Creating new order...
acme-mailcow_1       | Order created!
acme-mailcow_1       | Verifying autoconfig.develcow.de...
acme-mailcow_1       | autoconfig.develcow.de verified!
acme-mailcow_1       | Verifying autodiscover.develcow.de...
acme-mailcow_1       | autodiscover.develcow.de verified!
acme-mailcow_1       | Verifying mx.mailcow.email...
acme-mailcow_1       | mx.mailcow.email verified!
acme-mailcow_1       | Verifying webmail.mailcow.email...
acme-mailcow_1       | webmail.mailcow.email verified!
acme-mailcow_1       | Signing certificate...
```

Can you post your site.conf and webmail.conf? 

Aaand do you use a reverse proxy?

**Comment by siggislim** [comment]
site.conf: 
`server {
  listen 80 default_server;
  listen [::]:80 default_server;
  include /etc/nginx/conf.d/server_name.active;
  if ( $request_uri ~* "%0A|%0D" ) { return 403; }
  return 301 https://$host$uri$is_args$args;
}

server_tokens off;
proxy_cache_path /tmp levels=1:2 keys_zone=sogo:10m inactive=24h  max_size=1g;
server_names_hash_bucket_size 64;

map $http_x_forwarded_proto $client_req_scheme {
     default $scheme;
     https https;
}

server {
  include /etc/nginx/mime.types;
  charset utf-8;
  override_charset on;

  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;

  add_header Strict-Transport-Security "max-age=15768000;";
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Permitted-Cross-Domain-Policies none;
  add_header Referrer-Policy strict-origin;

  index index.php index.html;

  client_max_body_size 0;

  listen 127.0.0.1:65510;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  include /etc/nginx/conf.d/server_name.active;

  gzip on;
  gzip_disable "msie6";

  gzip_vary on;
  gzip_proxied off;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_min_length 256;
  gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;

  location ~ ^/(fonts|js|css|img)/ {
    expires max;
    add_header Cache-Control public;
  }

  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  absolute_redirect off;
  root /web;

  location / {
    try_files $uri $uri/ @strip-ext;
  }

  location /qhandler {
    rewrite ^/qhandler/(.*)/(.*) /qhandler.php?action=$1&hash=$2;
  }

  location /edit {
    rewrite ^/edit/(.*)/(.*) /edit.php?$1=$2;
  }

  location @strip-ext {
    rewrite ^(.*)$ $1.php last;
  }

  location ~ ^/api/v1/(.*)$ {
    try_files $uri $uri/ /json_api.php?query=$1;
  }

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  # If behind reverse proxy, forwards the correct IP
  set_real_ip_from 10.0.0.0/8;
  set_real_ip_from 172.16.0.0/12;
  set_real_ip_from 192.168.0.0/16;
  set_real_ip_from fc00::/7;
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;

  rewrite ^/.well-known/caldav$ /SOGo/dav/ permanent;
  rewrite ^/.well-known/carddav$ /SOGo/dav/ permanent;

  location ^~ /principals {
    return 301 /SOGo/dav;
  }

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_read_timeout 1200;
  }

  location /rspamd/ {
    proxy_pass       http://rspamd:11334/;
    proxy_set_header Host      $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
  }

  location ~* ^/Autodiscover/Autodiscover.xml {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autodiscover.php =404;
  }

  location ~* ^/Autodiscover/Autodiscover.json {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autodiscover-json.php =404;
  }

  location ~ /(?:m|M)ail/(?:c|C)onfig-v1.1.xml {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autoconfig.php =404;
  }

  # auth_request endpoint if ALLOW_ADMIN_EMAIL_LOGIN is set
  location /sogo-auth-verify {
    internal;
    proxy_set_header  X-Original-URI $request_uri;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  Host $http_host;
    proxy_set_header  Content-Length "";
    proxy_pass        http://127.0.0.1:65510/sogo-auth;
    proxy_pass_request_body off;
  }

  location ^~ /Microsoft-Server-ActiveSync {
    include /etc/nginx/conf.d/sogo_proxy_auth.active;
    include /etc/nginx/conf.d/sogo_eas.active;
    proxy_connect_timeout 4000;
    proxy_next_upstream timeout error;
    proxy_send_timeout 4000;
    proxy_read_timeout 4000;
    proxy_buffer_size 8k;
    proxy_buffers 16 64k;
    proxy_temp_file_write_size 64k;
    proxy_busy_buffers_size 64k;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
    proxy_set_header x-webobjects-remote-host $remote_addr;
    proxy_set_header x-webobjects-server-name $server_name;
    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
    proxy_set_header x-webobjects-server-port $server_port;
    client_body_buffer_size 128k;
    client_max_body_size 0;
  }

  location ^~ /SOGo {
    include /etc/nginx/conf.d/sogo_proxy_auth.active;
    include /etc/nginx/conf.d/sogo.active;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
    proxy_set_header x-webobjects-remote-host $remote_addr;
    proxy_set_header x-webobjects-server-name $server_name;
    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
    proxy_set_header x-webobjects-server-port $server_port;
    client_body_buffer_size 128k;
    client_max_body_size 0;
    break;
  }

  location /SOGo.woa/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location /.woa/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location /SOGo/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location (^/SOGo/so/ControlPanel/Products/[^/]*UI/Resources/.*\.(jpg|png|gif|css|js)$) {
    alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
  }

  include /etc/nginx/conf.d/site.*.custom;`

webmail.conf: 

`server {
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  index index.php index.html;
  client_max_body_size 0;
  root /web;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  server_name webmail.def7.net;

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  location / {
    return 301 https://mail.example.org/SOGo;
  }
}`

I'm not using a reverse proxy.

**Comment by siggislim** [comment]
I'm not using a reverse proxy.

**webmail.conf:** 

```
server {
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  index index.php index.html;
  client_max_body_size 0;
  root /web;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  server_name webmail.def7.net;

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  location / {
    return 301 https://mail.example.org/SOGo;
  }
}
```

**site.conf:**

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  include /etc/nginx/conf.d/server_name.active;
  if ( $request_uri ~* "%0A|%0D" ) { return 403; }
  return 301 https://$host$uri$is_args$args;
}

server_tokens off;
proxy_cache_path /tmp levels=1:2 keys_zone=sogo:10m inactive=24h  max_size=1g;
server_names_hash_bucket_size 64;

map $http_x_forwarded_proto $client_req_scheme {
     default $scheme;
     https https;
}

server {
  include /etc/nginx/mime.types;
  charset utf-8;
  override_charset on;

  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;

  add_header Strict-Transport-Security "max-age=15768000;";
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Permitted-Cross-Domain-Policies none;
  add_header Referrer-Policy strict-origin;

  index index.php index.html;

  client_max_body_size 0;

  listen 127.0.0.1:65510;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  include /etc/nginx/conf.d/server_name.active;

  gzip on;
  gzip_disable "msie6";

  gzip_vary on;
  gzip_proxied off;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_min_length 256;
  gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;

  location ~ ^/(fonts|js|css|img)/ {
    expires max;
    add_header Cache-Control public;
  }

  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
  absolute_redirect off;
  root /web;

  location / {
    try_files $uri $uri/ @strip-ext;
  }

  location /qhandler {
    rewrite ^/qhandler/(.*)/(.*) /qhandler.php?action=$1&hash=$2;
  }

  location /edit {
    rewrite ^/edit/(.*)/(.*) /edit.php?$1=$2;
  }

  location @strip-ext {
    rewrite ^(.*)$ $1.php last;
  }

  location ~ ^/api/v1/(.*)$ {
    try_files $uri $uri/ /json_api.php?query=$1;
  }

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  # If behind reverse proxy, forwards the correct IP
  set_real_ip_from 10.0.0.0/8;
  set_real_ip_from 172.16.0.0/12;
  set_real_ip_from 192.168.0.0/16;
  set_real_ip_from fc00::/7;
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;

  rewrite ^/.well-known/caldav$ /SOGo/dav/ permanent;
  rewrite ^/.well-known/carddav$ /SOGo/dav/ permanent;

  location ^~ /principals {
    return 301 /SOGo/dav;
  }

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_read_timeout 1200;
  }

  location /rspamd/ {
    proxy_pass       http://rspamd:11334/;
    proxy_set_header Host      $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
  }

  location ~* ^/Autodiscover/Autodiscover.xml {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autodiscover.php =404;
  }

  location ~* ^/Autodiscover/Autodiscover.json {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autodiscover-json.php =404;
  }

  location ~ /(?:m|M)ail/(?:c|C)onfig-v1.1.xml {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files /autoconfig.php =404;
  }

  # auth_request endpoint if ALLOW_ADMIN_EMAIL_LOGIN is set
  location /sogo-auth-verify {
    internal;
    proxy_set_header  X-Original-URI $request_uri;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  Host $http_host;
    proxy_set_header  Content-Length "";
    proxy_pass        http://127.0.0.1:65510/sogo-auth;
    proxy_pass_request_body off;
  }

  location ^~ /Microsoft-Server-ActiveSync {
    include /etc/nginx/conf.d/sogo_proxy_auth.active;
    include /etc/nginx/conf.d/sogo_eas.active;
    proxy_connect_timeout 4000;
    proxy_next_upstream timeout error;
    proxy_send_timeout 4000;
    proxy_read_timeout 4000;
    proxy_buffer_size 8k;
    proxy_buffers 16 64k;
    proxy_temp_file_write_size 64k;
    proxy_busy_buffers_size 64k;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
    proxy_set_header x-webobjects-remote-host $remote_addr;
    proxy_set_header x-webobjects-server-name $server_name;
    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
    proxy_set_header x-webobjects-server-port $server_port;
    client_body_buffer_size 128k;
    client_max_body_size 0;
  }

  location ^~ /SOGo {
    include /etc/nginx/conf.d/sogo_proxy_auth.active;
    include /etc/nginx/conf.d/sogo.active;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
    proxy_set_header x-webobjects-remote-host $remote_addr;
    proxy_set_header x-webobjects-server-name $server_name;
    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
    proxy_set_header x-webobjects-server-port $server_port;
    client_body_buffer_size 128k;
    client_max_body_size 0;
    break;
  }

  location /SOGo.woa/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location /.woa/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location /SOGo/WebServerResources/ {
    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
  }

  location (^/SOGo/so/ControlPanel/Products/[^/]*UI/Resources/.*\.(jpg|png|gif|css|js)$) {
    alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
  }

  include /etc/nginx/conf.d/site.*.custom;
}
```

**Comment by siggislim** [comment]
@andryyy any ideas what's wrong with my config? That config is pretty much default except the changes regarding https redirect und webmail. But this changes are from documentation. Sorry for asking but I'm only familiar with Apache but not with Nginx. 
Of course webmail.example.org and mail.example.org is replaces by the actual hostnames in the original files.

**Comment by andryyy** [comment]
No, I don't know. 

Is this a private setup? You can mail me and we take a look at it via SSH. But I seriously don't know when I'm available.

**Comment by siggislim** [comment]
@andryyy I'm not exactly sure but it works now. I did a comment for the IPv6 conf of Nginx because I don't use IPv6. I restarted the entire docker engine and now I can have the redirect and the webmail subdomain. 
Thanks for your help. 
The server is just for private purposes (me & family). Great work with this project btw. I appreciate the efforts you put into this. Thank you André!

**Comment by siggislim** [comment]
this problem is solved.

**Comment by andryyy** [comment]
Strange. Where did you comment it out? You can contact me anytime, I will have a look at it.

**Comment by siggislim** [comment]
In the file: data/conf/nginx/site.conf 
But maybe there was just the restart of the docker engine missing. I'm on Debian 10.
