### ISSUE TITLE
Vacation API

### ISSUE THREAD

**Issue by mirkomassarutto** [mailcow/mailcow-dockerized#2822]
Hi, I'm using Mailcow API to manage accounts and it's working fine.. 

I'm using documentation found here:
https://feldhostmailhosting.docs.apiary.io

But, is there a "vacation" API command?
Where can I find API docs?

Thanks

**Comment by andryyy** [comment]
You can use the API, but there are no docs. 

API is limited to pre and postfilters though.

![image](https://user-images.githubusercontent.com/2972950/62167060-a5986a00-b322-11e9-8b3e-88f0cd294b2d.png)

Create a filter and check the API logs.

**Comment by patschi** [comment]
As there's no more reply by the author I assume this is solved. Closing.

**Comment by mirkomassarutto** [comment]
not really.. have u any suggest for the script to use?
