### ISSUE TITLE
No Mailcow login page

### ISSUE THREAD

**Issue by GrantZero** [mailcow/mailcow-dockerized#2823]
Hi there,

i have installed mailcow, then i installed nextcloud. Befor installing nextcloud, i came on the login page from mailcow. After installing nextcloud, it will be all forworded to nextcloud - no chance to came on the login page from mailcow. What is still wrong?

**Comment by andryyy** [comment]
You seem to be using a reverse proxy, but even if not, we need more 
information to help you. :)

------ Originalnachricht ------
Von: "GrantZero" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 31.07.2019 08:51:08
Betreff: [mailcow/mailcow-dockerized] No Mailcow login page (#2823)

**Comment by GrantZero** [comment]
No, no reverse Proxy. Pls tell me, what information do you need?

**Comment by andryyy** [comment]
Well, what did you change exactly.

**Comment by GrantZero** [comment]
nothing...i installed mailcow normaly without config (domain etc.) and then i installed nextcloud via helper script

**Comment by andryyy** [comment]
And "git diff origin/master"?

------ Originalnachricht ------
Von: "GrantZero" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Comment" 
<comment@noreply.github.com>
Gesendet: 31.07.2019 09:54:45
Betreff: Re: [mailcow/mailcow-dockerized] No Mailcow login page (#2823)

**Comment by Knot3n** [comment]
Hi,

im faceing a similiar problem .. i did not changeing anything on the nginx config since few months and now the page for the UI is loading without a process. 

In my nginx logs nothing happens - i tried restarting docker and the container nothing helped here. 
I checked the nginx-mailcow logs and the requests are coming thru ...all other nginx pages are working ( standalone websites )

cant find any error logs which shows the problem. 

* IMAP is working

**Comment by andryyy** [comment]
You are using a reverse proxy, right? That's different from this issue. Any nginx-mailcow or php-fpm-mailcow logs would be helpful. Sounds more like a firewall issue, if the reverse proxy times out while connecting to the backend. If the backend was broken, it would return a bad gateway or some other errors.

**Comment by Knot3n** [comment]
Hey @andryyy ,

thanks for the hint .. got an ip conflict in mailcow.conf ... thanks for the help, its working again.

**Comment by liquidat** [comment]
@GrantZero We need way more info here.

- First things first - what is the output of `sudo ss -tlpn` on the machine?
- Next - can you shortly describe the architecture? Do you use a reverse proxy, for example?
- Just to be sure: how did you install nextcloud? Also as a container?
- What is the output of `sudo docker ps -a` or `sudo docker-compose ps`?

Those info should give us a first idea of what might have happened.
