### ISSUE TITLE
Mails gone after server change

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#2824]
Hi,

it's not the first time i move to another server.

Today, since i restore my backup und installed every thing as the same way as always - if you open my thunderbird, ALL e-mails except 2 ones were deleted from the directories.

I already tried a "force-resync" restore again - without success.

Were there some changes that can cause this?
The Mailcow GUI shows me the correct count of mails in the accounts.

If i move back to the old server all mails were immediately loaded to their directories.

I'm sure that i did everything right.

Regards

**Comment by andryyy** [comment]
No info about your setup, or how you moved mails or any logs. No one will be able to help. GitHub support is self-service, you need to provide all information and wait for someone to help. Keep in mind, this is not a support or ticket system. :)

**Comment by lalaluuu** [comment]
I think it does not really matter in this case cause there is absolutely nothing special in my setup.

My Setup:

Debian Stretch (old (minimal)) > Debian Stretch (new (minmal (blank))
Old Mailcow up-to-date.

Backup on the old machine (helper script).
Install curl/git/docker/docker-compose and mailcow on the new (keeped it blank)
Just changed the sql credentials from the old machine cause otherwise the restore will fail.
Restore from backup (helper script).

Everything went fine, no error, nothing - but it only shows me mails that were received since the new server started, no old ones. All old ones gets deleted from the inboxes of the mail client with the first connect.

I'm installing everything new at this moment and will see if it happens again ;)

**Comment by lalaluuu** [comment]
Second try - no problems. Very suspicious - but thanks ..
