### ISSUE TITLE
Sieve not marking emails as read

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2825]
Hello all,

I installed Roundcube 1.3.9 and created a filter on the webmail settings to move receipts from Uber to a folder and mark them as read. 

Now, the sieve is moving the messages to the folder, but it's leaving them unread. 

The _Show active sieve filter_ on the mailcow user portal shows what I believe to be a correct sieve. Any ideas would be appreciated.

```require ["fileinto","imap4flags"];
# rule:[Uber/Lyft Receipts]
if anyof (header :contains "subject" "trip with Uber", header :contains "subject" "Your ride with")
{
	fileinto "Receipts";
	setflag "\\Seen";
	stop;
}

**Comment by ghost** [comment]
Fixed it by setting the flag first, then sorting into the folder

**Comment by andryyy** [comment]
Thanks for coming back. :)
