### ISSUE TITLE
Multiple BCC destination

### ISSUE THREAD

**Issue by damdinsharav** [mailcow/mailcow-dockerized#2826]
**Is your feature request related to a problem? Please describe.**
I'd like to forward one particular e-mail's address to multiple emails. However BCC destination won't allow multiple email addresses. I've tried adding another instance with different BCC destination but it gives "A BCC for ***@*** exist" error.  

**Describe the solution you'd like**
Allow multiple BCC destination

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

**Comment by fm** [comment]
What if you create an alias that has all the email address and create a BCC map to the alias?

**Comment by andryyy** [comment]
That's the way to go. :)

**Comment by damdinsharav** [comment]
This is working. Thanks
