### ISSUE TITLE
[Question] Disable SPAM folder for POP3-only-mailboxes

### ISSUE THREAD

**Issue by TimurZanagar** [mailcow/mailcow-dockerized#2828]
I've got domains / mailboxes which are just used as POP3-only-mailboxes. I just realized that mails marked as SPAM are in SoGo SPAM folder. Is it possible to disable this rule (?) for just these domains / mailboxes?

JFYI the "Grant access to SOGo" was enabled. I just disabled for every mailbox which is POP3-only-mailboxes.

How can I delete the SOGo profile manually?

P.S.: Should I enable quarantine functionality?

**Comment by fm** [comment]
You can enable the quarantine, but it will only show messages that were rejected, if it was marked as SPAM, it will still deliver to the Junk folder. Creating a sieve filter to override it should help

**Comment by TimurZanagar** [comment]
@fm Is this really the only option? Creating a sieve filter for every mailbox? Maybe globally?

**Comment by andryyy** [comment]
You can create a prefilter for POP3 users in mailcow UI with a content like

```
require ["fileinto"];
fileinto "INBOX";
stop;
```
