### ISSUE TITLE
Can't login to the mailcow ui

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#283]
Hello, I'm currently not able to login to the mailcow ui. I've reset admin user with provided script, but it didn't help. No error message is displayed. Only logs I get are:
```
...
2..ext_ip...10 - - [17/May/2017:11:22:44 +0200] "GET /inc/languages.png HTTP/1.1" 200 45164 "https://xxx/inc/languages.min.css" "Mozilla/5.0 xxx Firefox/53.0"
172.22.1.251 -  17/May/2017:11:22:53 +0200 "POST /index.php" 302
2..ext_ip...10 - - [17/May/2017:11:22:53 +0200] "POST / HTTP/1.1" 302 5 "https://xxx/" "Mozilla/5.0 xxx Firefox/53.0"
172.22.1.251 -  17/May/2017:11:22:53 +0200 "GET /admin.php" 302
2..ext_ip...10 - - [17/May/2017:11:22:53 +0200] "GET /admin.php HTTP/1.1" 302 5 "https://xxx/" "Mozilla/5.0 xxx Firefox/53.0"
172.22.1.251 -  17/May/2017:11:22:53 +0200 "GET /index.php" 200
2..ext_ip...10 - - [17/May/2017:11:22:53 +0200] "GET / HTTP/1.1" 200 12785 "https://xxx/" "Mozilla/5.0 xxx Firefox/53.0"
```

**Comment by andryyy** [comment]
Don't know. Need more information. Last update? Broken after update? Please pleas your cache (completely!) and restart the browser. It needs to delete all cookies and caches.

**Comment by pschiffe** [comment]
Yes, git is latest master branch, all images are updated. It worked before the bigger update during the weekend. I've cleared browser cache (and cookies), also tried different browser. Today when I've opened the mailcow ui for the first time, I was logged in, but when I tried to do something, I only got `Form token invalid or timed out`. I couldn't log out or anything, so I've recreated all containers, and also rebooted the vm. After that I was logged out, but can't log in. From the quick glimpse over the code, I got a feeling that the session is not in the clean state or something, but I did recreate all containers, so I'm not sure how to clean it. Is something stored in redis or so?

**Comment by Dennis14e** [comment]
Has the mailcow ui (web server) another hostname as your mail server?
Then maybe https://github.com/mailcow/mailcow-dockerized/commit/0d3d9b8c15843a8d10008a4f461aec54733325b8 is the solution.

**Comment by pschiffe** [comment]
Yes, this is it! Thanks @Dennis14e . I'm using different url than the hostname of the vm. I can log in via the vm hostname.

**Comment by stevesbrain** [comment]
@pschiffe If this is what I think you're talking about, then it's the CSRF protection - you need to be accessing it via the URL that corresponds to the hostname specified in your config file :)

**Comment by pschiffe** [comment]
Well, shouldn't the commit https://github.com/mailcow/mailcow-dockerized/commit/0d3d9b8c15843a8d10008a4f461aec54733325b8 fix it once it's merged?

**Comment by stevesbrain** [comment]
Looks like it; but I haven't tested this circumstance specifically :)

**Comment by pschiffe** [comment]
Hi all, I've cherry-picked the https://github.com/mailcow/mailcow-dockerized/commit/0d3d9b8c15843a8d10008a4f461aec54733325b8 commit and I can confirm, that now it works even with the different url than the vm hostname. Thanks.
