### ISSUE TITLE
set password for rpamd fail

### ISSUE THREAD

**Issue by unclesamwk** [mailcow/mailcow-dockerized#2831]
Hey,

set rspamd password in mailcow UI fails with error message

'An unknown error occured'

In logs i dont see any entry.

youve an idea?

greetings
Sam

**Comment by christianbur** [comment]
I just successfully changed the password for Rspamd in the Mailcow UI.
I've even tried it on two independent Mailcow instances, I can't find a bug with the current version of Mailcow.

**Comment by andryyy** [comment]
I cannot reproduce, too. :(

Logs would be very helpful.

**Comment by unclesamwk** [comment]
i dont see anything more, but this i see ... 
```
==> /var/lib/docker/containers/1a35fb11ba7c5c5eb0e994b555111875186e02814d0dd6b75254a5a1c3eed5a4/1a35fb11ba7c5c5eb0e994b555111875186e02814d0dd6b75254a5a1c3eed5a4-json.log <==
{"log":"olefy INFO eof_received \u003c\u003e 0 bytes (stream size)\n","stream":"stdout","time":"2019-08-03T12:51:20.658560201Z"}
{"log":"olefy ERROR eof_received Protocol ERROR: no OLEFY/1.0 found)\n","stream":"stdout","time":"2019-08-03T12:51:20.65869316Z"}
{"log":"olefy INFO eof_received ('172.22.1.2', 45344) response send: b'[ { \"error\": \"Protocol error\" } ]'\n","stream":"stdout","time":"2019-08-03T12:51:20.658704108Z"}

```

**Comment by unclesamwk** [comment]
can i set the password on other way?

**Comment by christianbur** [comment]
OLEFY (the logs shown above) has nothing to do with the dockerapi. 
This [method ](https://github.com/mailcow/mailcow-dockerized/blob/1ad1413d086e05c9178cfee3cfe71786f25ccfd3/data/Dockerfiles/dockerapi/server.py#L283)is used to change the rspamd password.

**Comment by unclesamwk** [comment]
is there a supported uncomplicated way to print debug output for flask api?

**Comment by christianbur** [comment]
delete the file (...../mailcow-dockerized/data/conf/rspamd/override.d/worker-controller-password.inc ) and try again, maybe the Docker container is not allowed to create the file. However, it must have something to do with your local Docker host machine, because it's not the Docker image.

**Comment by unclesamwk** [comment]
i delete the file and restart the container and then the file was create again.
```# Autogenerated by mailcow```

**Comment by andryyy** [comment]
That's fine.

**Comment by unclesamwk** [comment]
but it doesn't works ... 
is there a supported uncomplicated way to print debug output for flask api?

**Comment by andryyy** [comment]
You should post full logs, but cherry pick them.
