### ISSUE TITLE
SOGo Select all Mails for Deletion

### ISSUE THREAD

**Issue by macskay** [mailcow/mailcow-dockerized#2832]
An option to select all emails at once to bulk delete them would be very nice. At the moment I need to select every email separately and then delete them one by one, which can get quite annoying when I get 20+ emails delievered to me daily.

**Comment by andryyy** [comment]
Hi, that's the wrong tracker. We are mailcow. :)

**Comment by sriccio** [comment]
Actually this is possible, but not really intuitive to be honest.

![select_all_1](https://user-images.githubusercontent.com/5239282/62424760-970bd300-b6d3-11e9-99b9-22045c228bef.png)

![select_all_2](https://user-images.githubusercontent.com/5239282/62424763-98d59680-b6d3-11e9-8fd6-1ff8642d15da.png)

**Comment by ghost** [comment]
Unreleated, but @macskay, the domain on your profile does not exist... did you forget to renew it?
