### ISSUE TITLE
dovecot: auth: Fatal: sql

### ISSUE THREAD

**Issue by stAn47** [mailcow/mailcow-dockerized#2834]
hello, i just updated my mailcow and i got fatals in my logs: 

```
dovecot: auth: Fatal: sql /usr/local/etc/dovecot/sql/custom.sql.conf: Can't open configuration file /usr/local/etc/dovecot/sql/custom.sql.conf: No such file or directory
```

i must had remove "/usr/local" prefix from extra.conf which i was using within data/conf/dovecot/  directory. 

it's possible there was a change in dovecot image which now uses purely /etc/dovecot instead of /usr/local/etc/dovecot directories

best regards, stan

**Comment by andryyy** [comment]
Yes, there was indeed a change and I expected no one was using an extra.conf file anyway. :) We could add a check for that in update.sh

**Comment by stAn47** [comment]
thank you, i thought it would be useful for anybody else using the overrides. 

i am using exra.conf and other overrides to scale up ram and processes. maybe a generic guide for scaling up resources for hundreds of concurrent connections would be nice as well, especially if there is anything that needs to be done with docker tuning to provide maximum performance if server uses mailcow only. all systems got their limits and it's quite complicated to find if such a limit was hit (mysql connections, fpm connections, auth connections, etc.. )

thank you, best regards, stan

**Comment by andryyy** [comment]
Can you share your extra.conf with us? Might be interesting for some users.
