### ISSUE TITLE
rspamd container died without warning. how to check for cause?

### ISSUE THREAD

**Issue by tamerax** [mailcow/mailcow-dockerized#2836]
Sorry if this is an obvious question but my rspamd container just stopped accepting mail and went to "red" in the System status.  During that time, no mail was received apparently according to my clients.
What might cause this to happen and how what log would I check so I can make sure it doesn't happen again?
Side note, is some sort of notification system to let an admin know one of the containers is failing or failed?
Thanks!

**Comment by tamerax** [comment]
Also...if the notification system is the Watchdog...apparently it's not working.

**Comment by andryyy** [comment]
This is not a support system. You need provide logs, when you report something you think is a bug, please. :)

There are multiple reasons it might have failed. Most likely it was not enabled in the config file. I don't see a reason it would return "ok" for a Rspamd check if it was down. But again, I don't know about your config.
