### ISSUE TITLE
SMTP slow, no connection via extern mail program

### ISSUE THREAD

**Issue by Nowustec** [mailcow/mailcow-dockerized#2837]
Hi guys,

hope you can help out (english or german is ok).

Situation:
Testserver:
Linux Server (can do Debian 9 or Ubuntu 18.04), 
Full root rights
16GB RAM
8 Cores
3 TB Space
1 GBIT redudant connection

I installed mailcow now several times but something goes wrong or something is wrong 30cm in front of the monitor :D
Set up with description, no errors.
Hostname mail 
No IPV6 (outcommented in hosts file also)

Issues:

- Cannot reach mail.domain.de......only webmail.domain.de
- Cannot connect to mailboxes by external clients (SOGO working fine)
- DNS looks fine
- SMTP needs around 10 Seconds

So maybe someone can help me out to set it up as a stable server.  
When you need screens let me know which i should provide :)

Thanks in Advance
Michael

**Comment by TimurZanagar** [comment]
Hi @Nowustec,

I've got a less powerfull machine and got no problems. Seems your configuration. How fast is you network speed? Can you test this?

**Comment by patschi** [comment]
Is the SMTP connection indeed "10s slow"? mailcow does use `postscreen_greet_wait` which delays incoming SMTP requests for about 3 seconds. AFAIK this helps minimizing spamming a bit as they usually have a shorter timeout and don't deliver spam at the end. So this sort of delay is intended and isn't because of the machine speed.

https://github.com/mailcow/mailcow-dockerized/blob/3c3bcf8c82afa867a98ae1b4f2c0017470f0a82b/data/conf/postfix/main.cf#L41

**Comment by Nowustec** [comment]
> 
> 
> Hi @Nowustec,
> 
> I've got a less powerfull machine and got no problems. Seems your configuration. How fast is you network speed? Can you test this?

Testing download speed........................................
Download: 88.52 Mbit/s
Testing upload speed..................................................
Upload: 9.58 Mbit/s

**Comment by Nowustec** [comment]
> 
> 
> Is the SMTP connection indeed "10s slow"? mailcow does use `postscreen_greet_wait` which delays incoming SMTP requests for about 3 seconds. AFAIK this helps minimizing spamming a bit as they usually have a shorter timeout and don't deliver spam at the end. So this sort of delay is intended and isn't because of the machine speed.
> 
> https://github.com/mailcow/mailcow-dockerized/blob/3c3bcf8c82afa867a98ae1b4f2c0017470f0a82b/data/conf/postfix/main.cf#L41

Yeah I understand and the time is not the issue at moment. I know is wanted by Mailcow now. But is still not reachable go crazy since 2 days I try with several installs but outlook cannot connect thundermail also, also exchange and and and but sogo work fine miau

**Comment by Nowustec** [comment]
OK Now I am fully confused.

When I use mail.domain.de as imap or smtp nothing work

Now I tried a for me unusual way and set CNAME for imap.domain.de and smtp.domain.de wit Data mail.domain.de it works.....

But now I get no Mails. I test, it send and in SOGO can see them. But not in clients, seems that no delivery.

Any hints?

**Comment by Nowustec** [comment]
Hey guys, can be closed. Found the mistake. 
Wrong TLD so the problem was 30cm in front of the monitor
