### ISSUE TITLE
Why does SOGo display user password in plaintext in the page source?

### ISSUE THREAD

**Issue by G2G2G2G** [mailcow/mailcow-dockerized#2838]
When you have more users added under the IMAP in settings, where you can add more mailboxes.. Once they're added they're all in plaintext. Including the password.

`"encryption": "ssl", "isNew": 1, "port": 993, "name": "", "password": "", "serverName": "172.22.1.250", "userName":`

Those are all plaintext fields. I'm not going to even touch on the subject of storing any information at all in JSON when that isn't a thing that is needed... anywhere, ever. 
SOGo is painful to use and look at, the client itself is extremely slow for what it is, I can't even figure out why it is so badly made or how you can make something so slow on loading. 

I can't submit a bug to their git repo, probably for many of the reasons above. I'm just letting you guys know since you do very nice work on this suite. 

P.S. my client sent an email to the servercow.de contact looking to pay for assistance 2 months ago and nobody responded, so they asked me to help (and you have no english on the page). 

Thanks & good luck, if I find where it is in their terrible mess of code I'll post here.

**Comment by Nowustec** [comment]
Hi,

at first the mailcow.de support is not really fast hehe better go here.

SOGO ist not the best webamiler that´s true but you also can use other on it. Roundcube is a good and there is a documentation to set it up fine.

So can fix a lot of problems in one step.

**Comment by andryyy** [comment]
mailcow support is not fast?

Can you please tell me a ticket ID where I did not respond fast enough, @Nowustec ?

If you mailed me to my mail address without support contract and ask for support, guess why I didn't respond. 

For this issue: yes, it needs to store credentials. How else would it be able to login? 
Easy workaround: Share folders via IMAP. Problem solved.

**Comment by G2G2G2G** [comment]
>For this issue: yes, it needs to store credentials. How else would it be able to login?

A session token... It isn't 1990s anymore.

**Comment by andryyy** [comment]
Why don't you tell inverse this? How are we developing SOGo?

 `SOGoMailAuxiliaryUserAccountsEnabled = NO;` - done.

**Comment by Nowustec** [comment]
Yes can tell you 2 mails to you still no respond...... so better is to ask here is even faster. 

But was not an attack to you, just telling is even faster to ask the community here, true story. No need to pull out the razorblades 👯‍♂

**Comment by G2G2G2G** [comment]
> Why don't you tell inverse this? How are we developing SOGo?
> 
> `SOGoMailAuxiliaryUserAccountsEnabled = NO;` - done.

Set that as default? You're packaging this to unknowing people, you probably didn't know either.
Put it in the docs? 
SOGo is terrible, can't even submit a bug as I said. I'm posting it where at least someone who doesn't know, will see it.

**Comment by andryyy** [comment]
Which support?

You send me two mails, ok, but this is not how the support works. There is a support package. :) I do not offer support via mail. I don't understand you. The servercow.de support package _is_ fast. And you _will_ get a response. So please don't tell people we are responding slowly. :)

**Comment by andryyy** [comment]
@G2G2G2G https://sogo.nu/bugs/view_all_bug_page.php

**Comment by G2G2G2G** [comment]
He's clearly some random spam account, 
>made 11 hours ago.

**Comment by andryyy** [comment]
I think it is a very valid bug/feature request @G2G2G2G - can you open an issue there?

We could also change the default to NO and add a warning in the config file.

**Comment by G2G2G2G** [comment]
I was already there and tried but apparently I'm too retarded to figure it out. It has a login as anonymous button but idk
Then I looked around their github and gave up. 
If I find it I'll just submit a pull request for the pass w/e

**Comment by andryyy** [comment]
A PR is probably very welcome. Yes, the repo is strange, but I hope you will figure it out. :)

Did your client ask for an English translation? Not sure if that was the request I missed. If so: I am working on it, sorry.

**Comment by Nowustec** [comment]
André, mal im Ernst ich habe auf die Nachricht des eröffnenden geantwortet und ihm lediglich zugestimmt, dass es langsam ist wenn man dort anfragt. Warum gehst Du mir gleich an die Wäsche wenn Du doch sagst das es stimmt......Aus welchem Grund auch immer.
Somit teilte ich mit besser hier anfragen, die subscription habe ich gar nicht erwähnt, weil ich dachte es ist selbsterklärend, dass ein Entwickler nicht jedem schreiben kann......War eigentlich zu Deinen Gunsten aber jeder steht mal oder öfter mal mit dem falschen Fuß auf.
Herrgott wenn ich die Probleme hätte....
Da frage ich mich doch direkt ob das hier das richtige für mich ist mit den Projekten die wir planen...Kriege ich gleich Angst überhaupt zu fragen...

**Comment by andryyy** [comment]
Da es ziemlicher Mist ist zu sagen, dass der mailcow Support langsam ist und man lieber hier fragen sollte. Das ist einfach falsch. Wenn du eine Anfrage an servercow.de meinst, ok, da brauche ich teilweise wirklich lange. Aber es entsteht der Eindruck, dass der verkaufte Support langsam ist und man lieber hier nachfragen sollte. _Das_ ist eben nicht korrekt und ruiniert den Ruf des Supports.

Wenn jemand erwägt den Support zu kaufen und das liest, ist das kein kleines Problem, sondern ein größeres. 

Ich denke, ich habe "mailcow.de support" in dem Fall falsch interpretiert. Bei Anfragen an servercow.de bin ich in der Regel auch schnell, aber da gibt es Ausnahmen. Diese Ausnahmen gibt es beim offiziellen Support nicht.

Ich habe recht häufig Supportanfragen via Mail, auf die ich nicht reagiere oder auf das Paket verweise und dann angeschnauzt werde, warum ich "nicht so" helfe. Das Thema reizt mich schon eine Weile. Wollte dir nicht doof kommen, bin einfach ein gebranntes Kind. Sorry.

**Comment by Nowustec** [comment]
Ok, dann haben wir wirklich aneinander vorbei gesprochen, wenn es so dämlich ankam entschuldige ich mich natürlich in aller Form.

Mir ging es eher darum, dass es selbstverständlich sein sollte, dass man hier oder eben bezahlt fragt.
Ich habe fälschlicherweise impliziert, dass auch andere das als selbstverständlich ansehen.

Da ich selbst entsprechende Backgrounds habe kenne ich da zu gut. Wurde zuletzt angemault weil ich auf das Ticketsystem verweise und nicht "mal eben" eine Kernel Panic per Zuruf beheben kann.

Also liebe Leser, es war keineswegs ein diskreditieren des Supports, lediglich ein Hinweis darauf, dass der Weg der gewählt wurde nicht zwingend der richtige war. Wollte damit nur darlegen die richtigen Wege einzuhalten. 
Denn im Grundsatz ist das hier ein mega tolles Teil was da in den Asphalt gebrannt wurde und als unpaid System gibt es nichts vergleichbares. Wenn ich dies damit ins falsche Licht gerückt habe sorry.

Peace

**Comment by G2G2G2G** [comment]
> A PR is probably very welcome. Yes, the repo is strange, but I hope you will figure it out. :)
> 
> Did your client ask for an English translation? Not sure if that was the request I missed. If so: I am working on it, sorry.

I already handled it, they were asking for someone to help them setup an email server. They paid me to do it instead. They have a lot of issues with the current provider not making their inboxes any bigger even with them offering more money per month lol.. Not worth it, I told them just buy a hard drive.

**Comment by mkuron** [comment]
To get this discussion back on topic: SOGo stores additional account passwords in the user preferences. Since some of them are needed by javascripts, they are exposed as a JSON object. Of course, the password could (and probably should) be masked out there. This can be reported to SOGo at www.sogo.nu/bugs.

The reason why SOGo is still the best solution for Mailcow is that we need a CalDAV/CardDAV server and a webmail client that integrates well with it (e.g. it can manage delegation, create new calendars, etc.). That typically means that webmail and server should be part of the same software project. The DAV plugins for Roundcube are, in my experience, not particularly reliable or well maintained, so Roundcube as the standard webmail for Mailcow is not really an option.
Only SOGo, Horde Groupware and NextCloud fulfill the above requirements. However, people tend to dislike Horde even more than SOGo, and NextCloud Mail was far from feature-complete the last time I tried it. Also, SOGo serves as Mailcow's EAS gateway, which some people need.

**Comment by G2G2G2G** [comment]
Yea I know the caldav issues with roundcube and I'm well familiar with horde, it is ugly. Nextcloud still has issues like folders etc that have problems so unusable. 
I'll probably make everyone use thunderbird instead of web browser anyway. Unfortunately it's very buggy and laggy on windows 10, haven't seen any issues on linux though. 

Just FYI she (boss) said she contacted you via this page: https://servercow.de/anfrage
Also your site has no way to be "English" do you guys need translations for it or something? Google translate makes it look pretty bad

**Comment by andryyy** [comment]
As always it is an issue of "enotime". :) I am working on the translation now, though. Really.

**Comment by andryyy** [comment]
@G2G2G2G Have a look at em Client.

**Comment by G2G2G2G** [comment]
Lol if you put some stuff on git I'll translate it.

Thanks for em client never heard of it before, looks nice I'll have the office girls see if they like it. I don't even use email hahaha
