### ISSUE TITLE
ClamAV serious DoS attack through ZIP mailbomb

### ISSUE THREAD

**Issue by Power2All** [mailcow/mailcow-dockerized#2840]
There is a known issue out for ClamAV, which can make the mailserver go broke.
Details can be found here: https://bugzilla.clamav.net/show_bug.cgi?id=12356

ClamAV's ZIP handling is inefficient and creates trouble with ZIP bombs.
They released a patch for this, but it's still able to crash on ZIP mail bombs.

This issue post is just a heads-up for everybody.

**Comment by Braintelligence** [comment]
This is related to #2839 - did you check before submitting this issue? The repo is not only aware of this but also merged the patch.

**Comment by Power2All** [comment]
No I forgot, my bad.
But the patch is not a fix, as the issue is still there, as commented on that URL I pasted.

**Comment by Braintelligence** [comment]
Yeah, the URL is also contained in the PR. The bug itself is strangely marked as fixed, though. Can't do much more than wait for a reaction, I guess.

**Comment by Power2All** [comment]
Alright, then I'll close this one, as it's related to #2839

**Comment by mkuron** [comment]
The patch supposedly only solves part of the problem. So once they release a new patch, we'll need to update again. But until then, there is nothing we can do.

**Comment by Power2All** [comment]
I understand, just trying to give some heads up, but it seems it's addressed, so I'm happy enough :)

**Comment by ntimo** [comment]
You could probably set. This way the container can not get bigger then 10 GB in its rootfs
storage_opt:
  size: '10G'
