### ISSUE TITLE
rspamd "request failed"

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#2841]
Hello,

now I noticed a problem with my rspamd as you can see here:

![image](https://user-images.githubusercontent.com/9658012/62640843-bc524880-b942-11e9-9796-8092f2bcb820.png)

I updated the server to the latest version (both packages and Mailcow itself).

I also tried to reset my rspamd password. I checked that after getting more SPAM into mail mailbox.

Server details:

Debian Jessie 64-bit,  6 threads, 4 GB RAM (VMware VM on OVH dedicated).

Any idea how to fix this? Thank you!

**Comment by andryyy** [comment]
Hi, this message typically appears when you enter a wrong password. Reset the password again, try something more generic for testing. Like 123456.

**Comment by DJIronic** [comment]
I already tried, but I will restart the server, re-run update and we will see. Last time it timed out the request.

**Comment by DJIronic** [comment]
OK, it fixed the issue. Thank you!
