### ISSUE TITLE
Redis - stop-writes-on-bgsave-error

### ISSUE THREAD

**Issue by sstevan** [mailcow/mailcow-dockerized#2842]
I have encountered Redis error again, displayed on the mailcow frontpage.
I had this issue before on the other server and solved it somehow with the https://github.com/mailcow/mailcow-dockerized/issues/1454#issuecomment-412515019

Applying this issue caused many troubles for me with updates, etc. https://github.com/mailcow/mailcow-dockerized/issues/2760
Might be unrelated, but who knows :)

I would like to know why is this happening (server is not low on RAM) and what is the best way to permanently apply this patch.

```
Fatal error: Uncaught RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in [no active file]:0 Stack trace: #0 {main} thrown in [no active file] on line 0
```

**Comment by mkapra** [comment]
I've also read about having full disks which cause the issue. 

> Might be unrelated, but who knows :)

I would try to unset the option and try to make the update. If it works you know it isn't related.

**Comment by andryyy** [comment]
"but it is currently not able to persist on disk"

That's nothing we could fix. Check your machine. :)

**Comment by sstevan** [comment]
@andryyy @mkapra you were completely correct. There was no free space available on this machine, which was not the case with the previous problem. This server is bearly used and it is not under monitoring.

However, I solved the issues just by restarting the containers (down/up). Just by doing so I got 75% of free space.

Before, closing this issue, would you mind giving me an advice, how to detect what is filling up the disk, in case this happens again?

Thanks for your help!

**Comment by mkapra** [comment]
@sstevan
I would try the command `df -h` to see where the large files are.
After that I would try the command `ls -Slh` to get the largest files on top of the list
to delete it or inspect it.
