### ISSUE TITLE
SoGo 502 Bad Gateway

### ISSUE THREAD

**Issue by unze** [mailcow/mailcow-dockerized#2844]
Using mailcow-dockerized under Ubuntu 18.04

Updated today via updater script and SoGo is not working anymore.

docker-compose logs nginx-mailcow
`2019/08/10 13:02:36 [error] 20#20: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:ea:2734:7000:a038:11d0:XXXX:XXXX, server: XXXX, request: "GET /SOGo/ HTTP/2.0", upstream: "http://172.22.1.248:20000/SOGo/", host: "XXXX", referrer: "https://XXXX/"`

curl http://172.22.1.248:20000
`curl: (7) Failed to connect to 172.22.1.248 port 20000: Connection refused`

**Comment by unze** [comment]
Already tried resetting the firewall, still no success :(

`docker-compose down`
`iptables -P INPUT ACCEPT`
`iptables -P FORWARD ACCEPT`
`iptables -P OUTPUT ACCEPT`
`iptables -t nat -F`
`iptables -t mangle -F`
`iptables -F`
`iptables -X`
`service docker restart`
`docker-compose up -d`

**Comment by andryyy** [comment]
Check the SOGo container logs.

**Comment by unze** [comment]
docker-compose logs sogo-mailcow

> sogo-mailcow_1       | 2019-08-10 15:39:40,617 CRIT Set uid to user 0
sogo-mailcow_1       | 2019-08-10 15:39:40,619 INFO supervisord started with pid 1
sogo-mailcow_1       | 2019-08-10 15:39:41,621 INFO spawned: 'processes' with pid 8
sogo-mailcow_1       | 2019-08-10 15:39:41,622 INFO spawned: 'syslog-ng' with pid 9
sogo-mailcow_1       | 2019-08-10 15:39:41,622 INFO spawned: 'cron' with pid 10
sogo-mailcow_1       | 2019-08-10 15:39:41,623 INFO spawned: 'bootstrap-sogo' with pid 11
sogo-mailcow_1       | Waiting for database to come up...
sogo-mailcow_1       | Aug 10 15:39:41 ed47dd7ee67a syslog-ng[9]: syslog-ng starting up; version='3.8.1'
sogo-mailcow_1       | 2019-08-10 15:39:42,633 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | 2019-08-10 15:39:42,633 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | 2019-08-10 15:39:42,633 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | 2019-08-10 15:39:42,633 INFO success: bootstrap-sogo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | Uptime: 0  Threads: 8  Questions: 1  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 0.000
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | Waiting for schema update...

**Comment by unze** [comment]
Previously i had portainer running separately in a docker network with port mapped 9000->20002.
Just to be sure i deleted portainer with
```
docker-compose down
docker rm -f $(docker ps -a -q)
docker-compose up -d
```
unfortunately still no success

**Comment by andryyy** [comment]
Can you please run the update again?

**Comment by NickUfer** [comment]
Had the same error now its working with your recent commits

**Comment by unze** [comment]
It's working again after the update.

Many thanks!

**Comment by andryyy** [comment]
Sorry and thanks. :)
