### ISSUE TITLE
Function to config a mailbox only for receiving

### ISSUE THREAD

**Issue by Johnnii360** [mailcow/mailcow-dockerized#2848]
**Is your feature request related to a problem? Please describe.**
Not really but maybe though. ;)

**Describe the solution you'd like**
I want a function to config a specific mailbox only for internal communication or just receiving only. The mailbox shall not be able to send in the internet or to other internal recipients.

I googled and looked into the documentation but didn't find any useful informations.

**Comment by andryyy** [comment]
Try this:

![image](https://user-images.githubusercontent.com/2972950/62831895-560d4480-bc26-11e9-8936-61ba87aec8b8.png)

```
from = "andre@develcow.de";
rcpt = "/.*/";
apply "default" {
  MAILCOW_BLACK = 999.0;
}
symbols [
  "MAILCOW_BLACK"
]
```

**Comment by Johnnii360** [comment]
Thank you, @andryyy !
Is there a documentation about rules where I can learn more of it?

**Comment by patschi** [comment]
That configuration is added automatically to the rspamd config file. You can find more details about that here: https://rspamd.com/doc/configuration/settings.html#settings-structure

**Comment by Johnnii360** [comment]
All right, thank you!
My issue/request is solved so I close now.
