### ISSUE TITLE
Backup mailcow-dockerized vmail

### ISSUE THREAD

**Issue by dixquatre** [mailcow/mailcow-dockerized#285]
Hi,

Trying to backup my vmail with the backup instruction on the documentation but this is the error that I get when I run the last command:

`docker: Error response from daemon: create \\\\mailcowdockerized_vmail-vol-1\: "\\\\\\\\mailcowdockerized_vmail-vol-1\\" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

Can someone explain how to fix it?

Thanks

**Comment by ignitedPotato** [comment]
You need to remove the `\` from the docker run command at `{{ range .Mounts }}\{{ if eq .Destination "/var/vmail" }}`

**Comment by dixquatre** [comment]
Thanks!
