### ISSUE TITLE
502 Bad Gateway  "Waiting for database to come up..."

### ISSUE THREAD

**Issue by targor** [mailcow/mailcow-dockerized#2854]
After "docker-compose down" and restarting with "docker-compose up" i cannot reach the web interface anymore. It shows me an 502 Bad Gateway error.

When i watch the logs of the "mailcowdockerized_sogo-mailcow_1" container, it says "Waiting for database to come up...".

Going into the sh script tells me that it trys to check the status of the mysql database:

mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${DBUSER} -p${DBPASS} --silent;

when i test this line, then i see that the database will reject any login with the given username and password.

The system variables are set, but the database rejects the user. Also when i go directly into the container and try to login.. it does not work either. Has anyone a clue why after a restart the database seem to reject any login?

**Comment by andryyy** [comment]
This happens when you change any of DBROOT, DBNAME or DBPASS. You should also make sure ".env" is a symlink to "mailcow.conf".

**Comment by patschi** [comment]
Works fine here. Might it be possible you're executing the command 1) within the container (e.g. dovecot), 2) in the top-level folder of mailcow (usually /opt/mailcow-containerized)?

```
$ docker-compose exec dovecot-mailcow sh
# mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${DBUSER} -p${DBPASS} --silent;

Uptime: 48392  Threads: 32  Questions: 140551  Slow queries: 0  Opens: 54  Flush tables: 1  Open tables: 48  Queries per second avg: 2.904
# #
```

**Comment by targor** [comment]
root@c855d48bff8d:/# echo $DBUSER
mailcow
root@c855d48bff8d:/# echo $DBPASS
eQdq1TByQPgXmVYBzTjSj7tddXNZ
root@c855d48bff8d:/# mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${DBUSER} -p${DBPASS};
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'mailcow'@'localhost' (using password: YES)'


The variables werent changed but the server just dont let me in.. it seems that the server does not hold any data anymore.. is it possible that the mysql volume gets wiped at restart or something?

**Comment by patschi** [comment]
Are you executing those commands in a mailcow container?

```
$ cd /opt/mailcow-dockerized
$ docker-compose exec dovecot-mailcow bash
$ mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${DBUSER} -p${DBPASS} --silent
```

The hostname `c855d48bff8d` is confusing me a bit, as it should have the hostname of the mailserver (so e.g. mail.domain.tld). The MySQL isn't get wiped by mailcow itself, the data should be persistent.

**Comment by targor** [comment]
Yes, i executed the commands directly in the "mailcowdockerized_mysql-mailcow_1" container.
Maybe i just remove everything and retry installing.. its currently only a test setup.

**Comment by patschi** [comment]
That's why I suggested trying this in the dovecot container, to have similar test cases on your and my end. Within the MySQL container the environment variables are different:
```
$ docker-compose exec mysql-mailcow bash
root@d8dd13b4abed:/# mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${MYSQL_USER} -p${MYSQL_PASSWORD}
Uptime: 49822  Threads: 32  Questions: 144741  Slow queries: 0  Opens: 54  Flush tables: 1  Open tables: 48  Queries per second avg: 2.905
root@d8dd13b4abed:/#
```

**Comment by targor** [comment]
I also tried in the dovecot container, but with the same result.. i now deleted everything and try it again with an all clean setup.. no other containers active i hope the error wont come again.. if so, ill come back to you :).

**Comment by simonvizzini** [comment]
I'm having the same problem, but in my case it's not after an update but right after a fresh installation. This is the first time I'm trying out mailcow, so I followed the official docs closely. I'm trying to run it with Proxmox inside an unpriviledged LXC container running Debian 10.1.

I execute the commands as suggested by patschi above:

MySQL container:
````
root@mailcow:/opt/mailcow-dockerized# docker-compose exec mysql-mailcow bash
root@2c8d944bb026:/# mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${MYSQL_USER} -p${MYSQL_PASSWORD}
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'mailcow'@'localhost' (using password: YES)'
root@2c8d944bb026:/# echo $MYSQL_USER
mailcow
root@2c8d944bb026:/# echo $MYSQL_PASSWORD
--REDACTED--
````

Dovecot container:
````
root@mailcow:/opt/mailcow-dockerized# docker-compose exec dovecot-mailcow bash
root@mailcow:/# mysqladmin status --socket=/var/run/mysqld/mysqld.sock -u${DBUSER} -p${DBPASS};
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'mailcow'@'localhost' (using password: YES)'
root@mailcow:/# echo $DBUSER
mailcow
root@mailcow:/# echo $DBPASS
--REDACTED--
````

Password in both cases is same as the one in mailcow.conf
I even started all over with `docker system purge`, but still same problem.

Here are the mysql-mailcow logs:
````
mysql-mailcow_1      | 2019-09-15 18:49:59 139624817976640 [Note] mysqld (mysqld 10.2.27-MariaDB-1:10.2.27+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql-mailcow_1      | 2019-09-15 18:50:00 139624817976640 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2019-09-15 18:50:00 139624093579008 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2019-09-15 18:50:01 139624817976640 [Note] InnoDB: Highest supported file format is Barracuda.
mysql-mailcow_1      | 2019-09-15 18:50:01 139624817976640 [Note] InnoDB: Starting crash recovery from checkpoint LSN=6701542
mysql-mailcow_1      | 2019-09-15 18:50:02 139624817976640 [Note] InnoDB: Starting final batch to recover 11 pages from redo log.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: Waiting for purge to start
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] InnoDB: 5.7.27 started; log sequence number 6702035
mysql-mailcow_1      | 2019-09-15 18:50:03 139623791576832 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] Recovering after a crash using tc.log
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] Starting crash recovery...
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] Crash recovery finished.
mysql-mailcow_1      | 2019-09-15 18:50:03 139623791576832 [Note] InnoDB: Buffer pool(s) load completed at 190915 18:50:03
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] Server socket created on IP: '::'.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Warning] 'user' entry 'root@3675b0cc6b78' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Warning] 'proxies_priv' entry '@% root@3675b0cc6b78' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2019-09-15 18:50:03 139624181278464 [Note] Event Scheduler: scheduler thread started with id 6
mysql-mailcow_1      | 2019-09-15 18:50:03 139624817976640 [Note] mysqld: ready for connections.
mysql-mailcow_1      | Version: '10.2.27-MariaDB-1:10.2.27+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
````

I'm a bit lost, any ideas?

**Comment by simonvizzini** [comment]
Looks like its not a problem on my end but a problem with the current mailcow version, I just saw this issue: https://github.com/mailcow/mailcow-dockerized/issues/2939
