### ISSUE TITLE
Multimap.map again :ro after upgrading

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#2856]
it could be the same issue @andryyy already fixed here: https://github.com/mailcow/mailcow-dockerized/issues/1805 maybe that issue was reintroduced but some recent change.

after modifying an additional multimap file I get an error when saving it:` local> Save map error  / request failed`

![](https://i.imgur.com/zj3BYnm.png)
![](https://i.imgur.com/hRKusX5.png)

**Comment by andryyy** [comment]
Nothing changed, rights look ok. 

What does Rspamd log?

**Comment by marrco** [comment]
Hi andryyy nothing gets logged on

`docker-compose logs --tail=100 -f rspamd-mailcow `

in the "History" tab under error after a failed save this  error appears:


```
8/12/2019, 2:52:38 PM | controller | 21 | csession | 549cfa | http error occurred: Not found
-- | -- | -- | -- | -- | --

```


![](https://i.imgur.com/jHKjdvf.png)

the relevant part of nginx log is:

```

nginx-mailcow_1      | fd4d:6169:6c63:6f77::b - - [12/Aug/2019:14:57:25 +0200] "GET /forwardinghosts.php?host=124.156.173.134 HTTP/1.1" 200 19 "-" "curl/7.64.0"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:57:25 +0200] "GET /rspamd/neighbours HTTP/2.0" 200 2 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:57:25 +0200] "POST /rspamd/undefined HTTP/2.0" 404 9 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:57:30 +0200] "GET /rspamd/getmap HTTP/2.0" 200 275 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::b - - [12/Aug/2019:14:57:34 +0200] "GET /forwardinghosts.php?host=111.118.129.195 HTTP/1.1" 200 19 "-" "curl/7.64.0"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:57:40 +0200] "GET /rspamd/neighbours HTTP/2.0" 200 2 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:57:40 +0200] "POST /rspamd/undefined HTTP/2.0" 404 9 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
[...]
nginx-mailcow_1      | fd4d:6169:6c63:6f77::b - - [12/Aug/2019:14:59:13 +0200] "GET /forwardinghosts.php?host=46.37.29.213 HTTP/1.1" 200 19 "-" "curl/7.64.0"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:59:17 +0200] "GET /rspamd/getmap HTTP/2.0" 200 117 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::b - - [12/Aug/2019:14:59:19 +0200] "GET /forwardinghosts.php?host=177.12.191.30 HTTP/1.1" 200 19 "-" "curl/7.64.0"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:59:30 +0200] "GET /rspamd/getmap HTTP/2.0" 200 51 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:59:33 +0200] "GET /rspamd/neighbours HTTP/2.0" 200 2 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 123.456.57.82 - - [12/Aug/2019:14:59:33 +0200] "POST /rspamd/undefined HTTP/2.0" 404 9 "https://webmail.mydomain.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36"
nginx-mailcow_1      | 172.22.1.13 - - [12/Aug/2019:14:59:35 +0200] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "rspamd-1.9.4"
nginx-mailcow_1      | 172.22.1.13 - - [12/Aug/2019:14:59:35 +0200] "GET /forwardinghosts.php HTTP/1.1" 200 68 "-" "rspamd-1.9.4"

```

**Comment by marrco** [comment]
Issue found: some old (?) cached script in my browser memory. Opening rspamd interface in chrome incognito mode solved the issue. So a browser cache forced deletion was needed to have my setup fully functional again.

I don't close the issue because andryyy could modify some expiry timings in Nginx config.

**Comment by patschi** [comment]
@andryyy Could probably the `etag` header help here?

**Comment by andryyy** [comment]
Not sure if that's related to the UI. Hm. I will try to reproduce it.

**Comment by marrco** [comment]
it still does NOT work on my browser normal mode, even after a F12 + Empty Cache and Hard Reload.

In incognito window mostly works, but sometimes when closing and opening different maps a strange 'composite' panel appears:

![](https://i.imgur.com/98KsvsZ.png)

**Comment by andryyy** [comment]
Can you also report this to Rspamd? :)

------ Originalnachricht ------
Von: "marrco" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Mention" 
<mention@noreply.github.com>
Gesendet: 13.08.2019 15:20:59
Betreff: Re: [mailcow/mailcow-dockerized] Multimap.map again :ro after 
upgrading (#2856)

**Comment by marrco** [comment]
I really don't know if that's a rspamd bug or some caching default we use in Nginx. If you think it is I certainly will report there too.

Mine is a really old installation (migrated a few times from different servers) so I'm quite dubious about the origin of this issue.

Am I the only one here experiencing similar issues?

**Comment by patschi** [comment]
Can you switch browser and disable the server-side cache in your nginx setup to validate this? I've never seen similar issues myself, also not on my own installation.

Any messages in the browsers' DevConsole?

**Comment by marrco** [comment]
same issue with Microsoft Edge browser. 

only when saving maps files, other options are fine. Easy to reproduce here. Open a map, click save, open a different map, save etc.

Another additional (minor) issue is that clicking "save" on an empty map file gives an error. Same if we delete everything from a map file. No errors in chrome dev tools console. 

I use a few more maps file than default setup. Here my additions to multimap.conf: https://pastebin.com/qnmW13m3 

Right now I did not yet test modified Nginx config. Do I have to change it inside the Nginx container or it's duplicated somewhere in /opt/mc-d/data/conf ?
