### ISSUE TITLE
Relaying local mails trough exim4 to Mailcow dockerized

### ISSUE THREAD

**Issue by Johnnii360** [mailcow/mailcow-dockerized#2859]
**Is your feature request related to a problem? Please describe.**
Yes. Want to relay mails from/trough local MTA exim4 to Mailcow dockerized.

**Describe the solution you'd like**
Is there any tutorial of this? I only found a tutorial for postfix in the documentation.

And I already googled but didn't found anything useful.

**Comment by andryyy** [comment]
If someone is able to help, we will add it to the docs.

**Comment by marrco** [comment]
on a Debian server:

```
# /etc/exim4/update-exim4.conf.conf
dc_eximconfig_configtype='smarthost'
dc_smarthost='12.34.56.78'
```

and 

```
# /etc/exim4/exim4.conf.localmacros
MAIN_RELAY_TO_DOMAINS = lsearch;/etc/exim4/relay_domains
```

with 

```
#/etc/exim4/relay_domains
locadomainone.com
localdomaintwo.org
```

#/etc/exim4/hubbed_hosts
locadomainone.com: my.mailcowone,com::2525:my.mailcowtwo,com::2525
localdomaintwo.org: my.mailcowone,com::25

hubbed hosts are referenced inside /etc/exim4.conf.template  
`# router/150_exim4-config_hubbed_hosts`

inside mailcow, you have to define Forwarding Hosts in Configuration & Details.

hth

**Comment by MarkOnDuty** [comment]
I'm trying to do the same thing, but with Postfix on the satellite system. My goal is just to be able to send from the command-line, or from daemons, via `mail` .

At the moment, I'm getting `Client host rejected: Access denied` in the satellite system's `mail.log`.

I was able to get this working on a MIAB system a couple of days ago, for whatever that is worth.

I'd switch to Exim in a heartbeat if it were simpler than Postfix.

**Comment by MarkOnDuty** [comment]
Exim4 is the cat's pajamas.

Following [this guide](http://varju.org/kt_569) for Ubuntu 16.04 worked perfectly. I only had to complete up to and including step 5.

**Comment by Johnnii360** [comment]
Thank you, @marrco ! It's working like a charm. :)
