### ISSUE TITLE
502 gateway error 

### ISSUE THREAD

**Issue by roelofz** [mailcow/mailcow-dockerized#2860]
Hi, 

After a lot of syncing I was ready to start using the server, but….

I tried sunday to change the nginx config (redirect of webmail url as documented in https://mailcow.github.io/mailcow-dockerized-docs/u_e-webmail-site/) and after that I ran docker-compose up -d accidentally not from /opt/mailcow-dockerized I got a bad 502 gateway on all url's. Removing the added conf did not have effect, updating also did not help, as also rerunning docker-compose up -d from the right folder. I can see using portainer that sogo is waiting for a schema update, but don't know why. It looks have some containers double (including sogo), I tried to switch activity, but this also had no effect.
 

How to get this back up and running?

**Comment by patschi** [comment]
What does the fox... eeeh, logs say?
```
$ docker-compose logs --tail=200 nginx-mailcow
$ docker-compose logs --tail=200 php-fpm-mailcow
```

**Comment by roelofz** [comment]
php-fpm:
Uptime: 1  Threads: 9  Questions: 5  Slow queries: 0  Opens: 18  Flush tables: 1  Open tables: 12  Queries per second avg: 5.000

Nginx (last rows showing my attempt to connect to ipadress):

2019/08/13 20:38:55 [error] 18#18: *417 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.252, server: mc01.xxxx.nl, request: "GET / HTTP/1.1", upstream: "fastcgi://[fd4d:6169:6c63:6f77::10]:9002", host: "192.168.0.21"

2019/08/13 20:38:55 [error] 18#18: *417 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.252, server: mc01.xxx.nl, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.1.12:9002", host: "192.168.0.21"

192.168.0.252 - - [13/Aug/2019:20:38:55 +0200] "GET / HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"

2019/08/13 20:38:56 [error] 18#18: *417 no live upstreams while connecting to upstream, client: 192.168.0.252, server: mc01.xxx.nl, request: "GET / HTTP/1.1", upstream: "fastcgi://phpfpm", host: "192.168.0.21"

192.168.0.252 - - [13/Aug/2019:20:38:56 +0200] "GET / HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"

**Comment by andryyy** [comment]
You can also try to stop all containers and recreate them...

```
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker rm -f $(docker ps -a -q)
cd /opt/mailcow-dockerized
docker-compose up -d
```

**Comment by roelofz** [comment]
So this only affects the containers, not the data?

Found it, volumes will stay, I'll get onto it.

**Comment by roelofz** [comment]
I'm looking at a admin login again, moohoo!

I'll start checking the config!

Thanks for your help!!!!

**Comment by roelofz** [comment]
Again thanks for your help.

Everything seems to be working again and I have managed to redirect the sogo site to a domain name. Still I have one question left.

I know the admin site is also for users. Still it would be better for me that only the SoGo site is accessible from the outside.

Changing the port to an only internally accessible port would be the easiest solution, but how to accomplish that?

Hope this can be configured, so port forwarding will be the easy way to block this.

Thanks again for the help!

**Comment by roelofz** [comment]
Fixed last question with MFA, seems this is not by design to block the admin interface. 
With MFA it has enough boundaries for me.

I went live with my (home private) server yesterday and I am impressed by the simplicity of Mailcow, docker is more difficult for me to understand, but Mailcow has made creating a mailserver a simple task.

Big Thanks and respect for that!

**Comment by Braintelligence** [comment]
You could enable basic HTTP auth or change the nginx conf in another way to block access to the Web GUI.
Though some features for users are only available there, so to me it wouldn't make sense to block it entirely.

It's not only an admin interface; it's also a user interface.
