### ISSUE TITLE
How to train RSpamD with existing spam after migration

### ISSUE THREAD

**Issue by 1998CC2** [mailcow/mailcow-dockerized#2861]
Hi,
I just migrated to MailCow and I love it.
Because I'm (not yet) familiar with Docker, I'm not sure how to do it !

I have migrated email accounts with over 15 years of spam mails in the junk folders.
So I like that RSpamD learn from all this emails.
So the email folders are within the dovecot-mailcow container and RSpamD in the rspamd-container - how can I now use RSpamD to learn the emails from the dovecot-mailcow container ?

I found this in the MailCow wiki: `for file in /my/folder/.Junk/cur/*; do docker exec -i $(docker-compose ps -q rspamd-mailcow) rspamc learn_spam < $file; done`
But I have no idea how to get it working with the docker container ...

Thanks in advance,
Alex

**Comment by mkuron** [comment]
That command should just work. It executes `rspamc` inside the Docker container and pipes `$file` from outside the container into it. Just make sure to `cd` to your `mailcow-dockerized` directory, otherwise the `docker-compose` command won‘t work.

**Comment by 1998CC2** [comment]
Thanks,
But which path should I use ?
The directories with the emails inside another (dovecot-mailcow) container ?

**Comment by mkuron** [comment]
If you‘re coming from Mailcow, you might as well import the redis database and rspamd volume. You can‘t use the above command with the stuff inside the dovecot-mailcow volume because messages are compressed and encrypted. The command is primarily for when migrating from another server.

**Comment by 1998CC2** [comment]
Now it makes sense !
No I migrated some weeks ago, but didn't trained RSpamD with the old data ...
So I guess I have no chance now.
