### ISSUE TITLE
Update OpenSSL version in Dovecot Container for supporting TLSv1.3

### ISSUE THREAD

**Issue by saldru** [mailcow/mailcow-dockerized#2864]
Hi everyone.

First of all, I would like to say thank you for the great work you make ! 👍 

I have a question and I want to know if it's possible to correct it. :)

I was setting up a mailcow instance on my server and I was configuring it with different SSL parameters. 

I used the famous tool testssl.sh to check my parameters for my Postfix and Dovecot configuration and I didn't knew why Postfix allow TLSv1.3 connections but Dovecot no.

So I checked the OpenSSL version on each docker container and I found that they don't use the same version of OpenSSL : 

`docker exec mailcowdockerized_postfix-mailcow_1 openssl version`
> OpenSSL 1.1.1c  28 May 2019

`docker exec mailcowdockerized_dovecot-mailcow_1 openssl version`
> OpenSSL 1.1.0k  28 May 2019

So now I know why Dovecot don't allow TLSv1.3 connections. It's because OpenSSL 1.1.0 don't support TLSv1.3.

I checked on DockerHub the Dockerfiles of Mailcow/Postfix and Mailcow/Dovecot and both are based on Ubuntu 18.04 (Xenial) so I don't know why the both don't use the same version of OpenSSL. 

So, my question is that is it possible to update the version of OpenSSL on the Dovecot container to the latest one (1.1.1c) that is the same as the Postfix container to allow TLSv1.3 with Dovecot for IMAP connections ?

Thank you for your time !
Saldru

**Comment by andryyy** [comment]
Hi :)

Postfix is based on Buster. Let's wait a bit for Dovecot to update their repos. :)

We used to build Dovecot, but I think we should stick with the official repos.

**Comment by saldru** [comment]
Hi, 

Thank you for your reply ! 

Yeah now I just saw that Postfix container is based on Debian Buster and Dovecot container is still based on Debian Stretch. :)

Just need to try ! :)

**Comment by xetorixik** [comment]
@andryyy and @saldru Great idea to support TLSv1.3 on Mailcow.
+1 For both of you :)

**Comment by saldru** [comment]
Hi everyone, 

I saw that you updated the dockerfile of the dovecot image and now it's based on Debian Buster so the OpenSSL version is updated to 1.1.1d and Dovecot now support TLSv1.3 and it works fine :)

So I close my case because it's not an issue anymore. Thank you for your job ! :)

**Comment by andryyy** [comment]
Thanks for coming back and closing the issue! :)
