### ISSUE TITLE
Windows 7 and Outlook 2019

### ISSUE THREAD

**Issue by cchris-org** [mailcow/mailcow-dockerized#2866]
Hi!

Windows 7, Outlook 2019, cant add mail user.
Log: Error: must be authenticated
Windows 10, Outlook 2019, works

before i post all logs etc ..
Is there a known problem about?

**Comment by andryyy** [comment]
Yes, Windows 7. 😄 

I don't know what you try to setup, but I guess EAS. You need to upgrade your client or allow TLS 1.0 in Nginx.

**Comment by cchris-org** [comment]
setup?
activesync=yes, eas=yes

win:
exchange, login, password-> have fun
the way it should go :)
https://testconnectivity.microsoft.com -> Exchange ActiveSync:

> Testing HTTP Authentication Methods for URL https://xxxx/Microsoft-Server-ActiveSync.
 The HTTP authentication test failed.
  Additional Details
 	
> A 401 error was received from the server, but no authentication methods are supported.
 HTTP Response Headers:
 Connection: keep-alive
 X-Frame-Options: SAMEORIGIN
 Content-Length: 0
 Content-Type: text/plain; charset=utf-8
 Date: Sun, 18 Aug 2019 09:29:49 GMT
 Server: nginx
 WWW-Authenticate: basic realm="SOGo"
 Elapsed Time: 389 ms.

**Comment by andryyy** [comment]
Don't use that test, it will fail with SOGo.

Just enable TLS 1.0 and upwards in Nginx.

**Comment by cchris-org** [comment]
ok, win7 -> enable tls 1.1 and 1.2, works :)

howto on win7
https://support.microsoft.com/de-at/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi#easy

thank you so much :)

**Comment by andryyy** [comment]
That's even much better than enabling 1.0 in Nginx. :) Thanks for coming back and posting the link!
