### ISSUE TITLE
Clamd restarting every minute

### ISSUE THREAD

**Issue by Majusch** [mailcow/mailcow-dockerized#2870]
**Describe the bug :**
Clamd seems to be restarting every 50 seconds - 1 minute. From reading the logs I can't seem to figure out whats the problem and where to go from here, i tried changing the permissions on all files in /var/lib/clamav but that didnt change anything. 

**How to reproduce :**
No Idea, happens everytime clamd is supposed to be running

**Expected behaviour :**
Clamd isnt restarting and is running like its supposed to be 

**System :**
Ubuntu 18.04.03 LTS | Docker Version 19.03.1

**Logs :**
clamd-mailcow_1      | Copying non-empty whitelist.ign2 to /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | Stating whitelist.ign2
clamd-mailcow_1      |   File: /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      |   Size: 27               Blocks: 8          IO Block: 4096   regular file
clamd-mailcow_1      | Device: 67h/103d Inode: 375374      Links: 1
clamd-mailcow_1      | Access: (0644/-rw-r--r--)  Uid: (  700/  clamav)   Gid: (  700/  clamav)
clamd-mailcow_1      | Access: 2019-08-19 16:41:10.707417076 +0200
clamd-mailcow_1      | Modify: 2019-08-19 16:42:03.016128089 +0200
clamd-mailcow_1      | Change: 2019-08-19 16:42:03.028128252 +0200
clamd-mailcow_1      |  Birth: -
clamd-mailcow_1      | dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | /bootstrap.sh: line 81:    18 Killed                  nice -n10 clamd
clamd-mailcow_1      | /bootstrap.sh: line 82: kill: (18) - No such process
clamd-mailcow_1      | Worker 18 died, stopping container waiting for respawn...

**Comment by andryyy** [comment]
Hi, how much RAM? :)

**Comment by Majusch** [comment]
> Hi, how much RAM? :)

Hey, currently its running at 4GB

**Comment by Majusch** [comment]
@andryyy Any ideas?

**Comment by andryyy** [comment]
Depending on wether or not Solr is used, it might run out of memory. Is swap active?

**Comment by Majusch** [comment]
Just figured out from looking at the Syslogs that it is actually being killed because it runs out of memory. How can I fix that?

**Comment by andryyy** [comment]
Moooore RAM. :)

**Comment by andryyy** [comment]
You can also disable ClamAV by setting SKIP_CLAMD in mailcow.conf

**Comment by Majusch** [comment]
So I see that that are two very nice options, but whats wondering me is that a colleague of mine is running Mailcow on basically the same system, and for him it's running fine, maybe there are any options i can change?

**Comment by andryyy** [comment]
Different size of Redis, different amount of mail (with Solr), different usage (you use EAS, they use IMAP) etc. 
All those are reasons why it - perhaps - does not work out for you, but for them.

**Comment by Majusch** [comment]
Well that sounds like a reason. However thank you very much 👍 :)

**Comment by Majusch** [comment]
Update : Fixed it with raising the memory settings in docker-compose.yml

**Comment by Braintelligence** [comment]
@Majusch Can you please elaborate more on what you mean by "memory settings in docker-compose.yml"?

**Comment by Majusch** [comment]
I changed those values in docker-compose.yml : 
"mem_limit: 1000m                                                                                                                                                                                                                                                                                                           
mem_reservation: 400m
memswap_limit: 200m
"

**Comment by Braintelligence** [comment]
Did you mean "add" instead of "change"? Where are those settings from, they shouldn't be from the base mailcow setup.

@andryyy Is that actually part of the current docker-compose.yml?

**Comment by MAGICCC** [comment]
@Braintelligence He means add, see here the docs for docker-compose: https://docs.docker.com/compose/compose-file/#resources

I wonder why it helps when you set it to a specific limit in the compose file. Normally all containers have the available server RAM assigned if I am not wrong

**Comment by andryyy** [comment]
You don't gain RAM by doing that, other containers will be killed eventually.

**Comment by Majusch** [comment]
> He means add, see here the docs for docker-compose:

I actually meant add, I didnt remember adding these in the first place, but I did so to fix some other problems in the past. However, Mailcow seems to be running peacefully, all containers have been up since 16 hours, so for me it seems fixed.
