### ISSUE TITLE
Sogo crashes the whole VServer if wrong password is entered

### ISSUE THREAD

**Issue by TheMatzy** [mailcow/mailcow-dockerized#2873]
Hey, 

I have a weird mistake. If someone enters his account email data wrong 2 times at Sogo, the Docker container crashes with a memory error and then also crashes the Ubuntu 18.04 V-Server. What can I do about it? I have installed the latest version of Mailcow.

Thanks matzemagkekse

Here my log outputs from the Syslog

`Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 systemd-networkd[187]: veth93e9043: Gained IPv6LL
Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 dockerd[821]: time="2019-08-19T22:28:44+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:44 h2840170 systemd-networkd[187]: veth6e8c5cb: Gained IPv6LL
Aug 19 22:28:44 h2840170 systemd-networkd[187]: vethedd49e6: Gained IPv6LL
Aug 19 22:28:45 h2840170 systemd-networkd[187]: vethe7af4a1: Gained carrier
Aug 19 22:28:46 h2840170 systemd-networkd[187]: veth2d4ad1b: Gained carrier
Aug 19 22:28:46 h2840170 containerd[805]: time="2019-08-19T22:28:46.869403672+02:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/847762cdb2f2de935b575b5fac706a72dec6637a0ecd863015d104d59bd5f1d3/shim.sock" debug=false pid=4364
Aug 19 22:28:47 h2840170 containerd[805]: time="2019-08-19T22:28:47.456910664+02:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/02c6b5cfe6b427d925134c10ed736757a35bab833f26230f0cd3291a78ebabd7/shim.sock" debug=false pid=4408
Aug 19 22:28:47 h2840170 systemd-networkd[187]: vethce93549: Gained carrier
Aug 19 22:28:47 h2840170 systemd-networkd[187]: vethe7af4a1: Gained IPv6LL
Aug 19 22:28:47 h2840170 systemd-networkd[187]: veth2d4ad1b: Gained IPv6LL
Aug 19 22:28:48 h2840170 dockerd[821]: time="2019-08-19T22:28:48+02:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:48 h2840170 dockerd[821]: time="2019-08-19T22:28:48+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:48 h2840170 dockerd[821]: time="2019-08-19T22:28:48+02:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:48 h2840170 dockerd[821]: time="2019-08-19T22:28:48+02:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.15.0/modules.builtin.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.15.0`, error: exit status 1"
Aug 19 22:28:49 h2840170 systemd-networkd[187]: veth869f2c4: Gained carrier
Aug 19 22:28:49 h2840170 systemd-networkd[187]: vethce93549: Gained IPv6LL
Aug 19 22:28:50 h2840170 systemd-networkd[187]: vethb25f06f: Gained carrier
Aug 19 22:28:50 h2840170 systemd-networkd[187]: veth869f2c4: Gained IPv6LL
Aug 19 22:28:51 h2840170 systemd-networkd[187]: vethb25f06f: Gained IPv6LL
Aug 19 22:28:51 h2840170 dockerd[821]: time="2019-08-19T22:28:51.793221727+02:00" level=info msg="Loading containers: done."
Aug 19 22:28:51 h2840170 dockerd[821]: time="2019-08-19T22:28:51.827131231+02:00" level=warning msg="failed to retrieve runc version: unknown output format: runc version spec: 1.0.1-dev\n"
Aug 19 22:28:52 h2840170 dockerd[821]: time="2019-08-19T22:28:52.848550605+02:00" level=info msg="Docker daemon" commit=2d0083d graphdriver(s)=overlay2 version=18.09.7
Aug 19 22:28:52 h2840170 dockerd[821]: time="2019-08-19T22:28:52.860097727+02:00" level=info msg="Daemon has completed initialization"
Aug 19 22:28:53 h2840170 dockerd[821]: time="2019-08-19T22:28:53.390942177+02:00" level=info msg="API listen on /var/run/docker.sock"
`

**Comment by djdomi** [comment]
for me it looks more as a configuration issue on the base system as it tells that i.e. 
* Module nf_nat not found in directory /lib/modules/4.15.0
so fix your base system :-)

**Comment by andryyy** [comment]
Also looks like OpenVZ, but I don't know anything about their system.

**Comment by TheMatzy** [comment]
Sorry for my incompleteness. I have an VServer by a Hoster and they use Virtuozzo for there virtualisation. I rebuilt the containers several times and even reinstalled the server, nothing helps :(

**Comment by patschi** [comment]
Well, Virtuozzo is based on OpenVZ and this virtualization technique does cause many issues, also because some hosters/providers can easily overprovision hosts and limit the RAM in bad ways. I'd recommend using a different provider without OpenVZ or similar.

**Comment by djdomi** [comment]
@TheMatzy i aint know but if you like i can give you a good address for a vserver that works fine :)

**Comment by MAGICCC** [comment]
There's
Hetzner
netcup
vultr
digitalocean 
and much more
