### ISSUE TITLE
Backup, reinstall and restore creates "dummy mails" in SoGo

### ISSUE THREAD

**Issue by simonszu** [mailcow/mailcow-dockerized#2874]
**Describe the bug, try to make it reproducible**
. Backup all Mailcow Data. 
2. Delete all containers and data
3. Reinstall mailcow
4. Restore all data
5. Open SoGo and look at your inbox
6. Strange dummy emails are shown, which aren't clickable nor deleteable

For a screenshot, check this upload i made to imgur: https://imgur.com/a/gAmYLlC

**System information and quick debugging**
No logs available, i have made this import a few days ago and have no persistent logging available for docker. If needed, i'll try to reproduce

Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?): Debian 10
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.): Docker, running in a privileged LXC container
 - Your server/VM specifications (Memory, CPU Cores): 4096MB RAM, 20GB Storage, 2 CPU Cores
 - Don't try to run mailcow on a Synology or QNAP NAS, do you? No
 - Docker and Docker Compose versions 
```
root@lxmail:~# docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
root@lxmail:~# docker-compose --version
docker-compose version 1.24.1, build 4667896
 - Browser (if it's a Web UI issue) - please clean your browser cache and try again, problem persists? Chrome, problem persists
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout? No

**Comment by mkapra** [comment]
@simonszu Hi,
after I moved my mailserver to another server I also had this problem. Could you please post some logs of your environment?
In my case the messages weren't dummy messages. They were non-decipherable mails. 
This was my issue: #2395 
Because there was no important data and I needed my mailserver very fast available again I installed the mailserver without the backup.

**Comment by simonszu** [comment]
@mkapra hi. In the meantime I accessed my mailcow via IMAP to check if the mails appeared there as well. They did, and they had a content there. It was a hard time deleting them, since they "reappeared" from trash each time I moved them there. However, after a few attempts I was successful.

Now there are not a bunch of mails in my inbox, but only a single one which isn't viewable via IMAP, but also not selectable via SoGo. Clicking the checkbox behind the people-silhouette-icon simply does nothing, not even placing the mark in the box.

This last mail isn't showing up when accessing the mailcow via IMAP.

I'll gather logs tomorrow, and also poke around in dovecot's data volume as well.

But, I have to note, I do not really use my mailcow as a "full" Mailserver, but rather as a means to use Gmail with my own domain, so I have created a rule that each mail should be forwarded to Gmail and removed from my inbox. Therefore I am a little more surprised that there are any mails in my inbox at all.

**Comment by mkapra** [comment]
@simonszu So then I think it has nothing to do with my linked issue. 
How did you made the backup?

**Comment by simonszu** [comment]
Like this: https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/

I restored all the data step by step, beginning at the very bottom of the list, and working my way to the top, since I assumed that they depend on each other.

There must be another issue I created some time ago where I made a feature request in this script to have a "restore all" step, which applies each step in the right order, but that's another story for now.

Also, my mailcow setup is working fine, as intended, and I seldom look at Sogo, since it's just a forwarder, but it still nags me a little bit that these mails appear. However, they do not block proper operation or anything.

**Comment by mkapra** [comment]
@simonszu I would have tried to don't restore the vmail backup (If you only forward your mails to gmail)

**Comment by simonszu** [comment]
Yeah, but it happened now... Maybe you're right, maybe just a little hint in the documentation is enough. However, I'll figure out how to remove the last of these mails ;)

**Comment by mkapra** [comment]
@andryyy Any idea on this?

**Comment by oleggtro** [comment]
Any update on this? I migrated to a new server yesterday and imap works fine but i also got those dummy mails showing up in sogo

**Comment by andryyy** [comment]
Did you use the migration guide?

https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_migration/
