### ISSUE TITLE
IDN issues

### ISSUE THREAD

**Issue by kunago** [mailcow/mailcow-dockerized#2875]
**Describe the bug, try to make it reproducible**
A clear and concise description of what the bug is. How can it be reproduced? 
If applicable, add screenshots to help explain your problem. Very useful for bugs in mailcow UI.

I have been having problems with IDN domains since the last time I updated. I own a domain name "xn--abrahm-tta.eu", which is properly set in the mailcow admin. I have mailboxes created and all seemed to work until just recently. So far I was able to notice the problem with gmail. When I send an email and the recipient is to reply, he replies to the "xn--"domain, however the server returns an error from the "umlauted" domain name "abrahám.eu" and the following message:

![image](https://user-images.githubusercontent.com/460971/63375257-b9684680-c38b-11e9-86b6-2c1c571aab7b.png)

There is nothing more useful information in the postfix log, basically an identical message.

Further information (where applicable):
 - OS: Debian 9
 - Virtualization technology: PROXMOX, QEMU container
 - Server/VM specifications: 1 CPU, 8 GB RAM
 - Don't try to run mailcow on a Synology or QNAP NAS, do you? - NO
 - Docker and Docker Compose versions - docker-compose
 - Output of `git diff origin/master`, any other changes to the code? - NO

**Comment by kunago** [comment]
Can I expect this issue to be looked at? Thanks.

**Comment by andryyy** [comment]
```
Postfix currently does not convert internationalized domain names from UTF-8 into ASCII (or from ASCII into UTF-8) before using domain names in SMTP commands and responses, before looking up domain names in lists such as mydestination, relay_domains or in lookup tables such as access tables, etc., before using domain names in a policy daemon or Milter request, or before logging events.
```

You should set the reply-to header to the ASCII formatted address, I think.

**Comment by kunago** [comment]
I have everything properly decoded and there are no UTF-8 characters in the address. I assume it is Google that does the translation and tries to send the email to the encoded address. I have not done anything in a few months now and it started happening all by itself.

**Comment by andryyy** [comment]
Try to set `smtputf8_enable = yes` in `data/conf/postfix/extra.cf` and restart Postfix.

Does it work?

**Comment by kunago** [comment]
Thank you for a fast suggestion. It worked. What I did:

1. sent an email from gmail to xn-- domain
2. sent a reply from xn-- to gmail
3. sent a reply from gmail back to xn--

All messages passed fine, so this seems to have done the job. Should I keep the extra.cf or is it going to be part of the general configuration?

**Comment by andryyy** [comment]
It does not work correctly in some cases. LMTP via Dovecot does for example not accept these messages. I need to do further checks.

**Comment by andryyy** [comment]
Could you please also post your older postfix-mailcow logs containing "relay access denied" and the lines around it? :) Would be very helpful!

Edit: Or just set it to "no", restart Postfix, test again etc.

**Comment by kunago** [comment]
Sorry for my late reply.

Don't ask me why, only if I knew, but it does not seem to happen anymore. The error is gone and I did nothing about it.

**Comment by akaSyntaax** [comment]
Sorry for opening this thread again but I'm experiencing the same issue.

> Could you please also post your older postfix-mailcow logs containing "relay access denied" and the lines around it? :) Would be very helpful!
> 
> Edit: Or just set it to "no", restart Postfix, test again etc.

Here are the corresponding log lines:

- disconnect from mail-qv1-xf2c.google.com[2607:f8b0:4864:20::f2c] ehlo=2 starttls=1 mail=1 rcpt=0/1 bdat=0/1 quit=1 commands=5/7

- NOQUEUE: reject: RCPT from mail-qv1-xf2c.google.com[2607:f8b0:4864:20::f2c]: 554 5.7.1 <user@idndomain>: Relay access denied; from=<user@gmail.com> to=<user@idndomain> proto=ESMTP helo=<mail-qv1-xf2c.google.com>

- Anonymous TLS connection established from mail-qv1-xf2c.google.com[2607:f8b0:4864:20::f2c] to mail.predatormc.net: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256

- connect from mail-qv1-xf2c.google.com[2607:f8b0:4864:20::f2c]

- WHITELISTED [2607:f8b0:4864:20::f2c]:38347

- CONNECT from [2607:f8b0:4864:20::f2c]:38347 to [fd4d:6169:6c63:6f77::e]:25

**Comment by andryyy** [comment]
Try `smtputf8_enable = no`

**Comment by akaSyntaax** [comment]
Thank you for your fast reply! It works now, does this configuration have any downsides?

**Comment by akaSyntaax** [comment]
Thank you for your fast reply! It works now, does this configuration have any downsides?
