### ISSUE TITLE
rspamd Module loading error

### ISSUE THREAD

**Issue by c0by85** [mailcow/mailcow-dockerized#2879]
rspamd displays an error message and doesn't work. problem exists since last update. tested browsers: chrome, firefox.

![Bildschirmfoto vom 2019-08-22 22-32-24](https://user-images.githubusercontent.com/25707747/63547636-d9833b80-c52c-11e9-94ab-88d6eb5351a3.png)

`Module loading error: timeout, module: d3pie,d3,humanize,d3evolution,footable,bootstrap`

`lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
`

`Linux mail 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by 0x766C70** [comment]
Hello @c0by85, did you fix this ? I am facing the same issue since  ! tks

**Comment by ledufakademy** [comment]
same issue but only with firefox, any  fix  or workaround ?

**Comment by Lecquio** [comment]
If it only happens with one browser just clear cookies and cache for rspamd site and it will work again
