### ISSUE TITLE
SOGo E-Mail forwarding

### ISSUE THREAD

**Issue by SemikolonDEV** [mailcow/mailcow-dockerized#288]
Hey,

since the Update yesterday the E-Mail forwarding from SOGo doesn't work.

Regards
Jan-Lukas

**Comment by andryyy** [comment]
I think this is about mynetworks. Can you run "git pull" to get the latest changes of data/conf/postfix/main.cf? Or just add the new mynetworks line by hand. Run `docker-compose restart postfix-mailcow` then.

**Comment by SemikolonDEV** [comment]
Yes, i have updated the line and it works
