### ISSUE TITLE
DNS resolution does not work after change IPV4_NETWORK

### ISSUE THREAD

**Issue by Nekmo** [mailcow/mailcow-dockerized#2882]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:
DNS resolution from containers does not work if IPV4_NETWORK is changed:

```
IPV4_NETWORK=172.200.1 docker-compose up -d
```

I access inside a container (like postfix) but the DNS resolution does not work. resolv.conf in container:

```
# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

Changing the resolv.conf file to `8.8.8.8` fix the problem. It also works without changing `IPV4_NETWORK`.

**Comment by andryyy** [comment]
Please do not change resolve.conf inside the container. Docker always uses 127.0.0.11, no matter the DNS in the "run" parameter, to act as kind of proxy.

It does not work, when changing the subnet to a public network. 172.200 is not a private network range.

**Comment by Nekmo** [comment]
I'm sorry, my mistake :( I will try using another range :+1: thanks!
