### ISSUE TITLE
Replace password in imapsync logs

### ISSUE THREAD

**Issue by maxmeyer** [mailcow/mailcow-dockerized#2884]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I configured "imap sync". When a job is run, a log similar to this is reported:

~~~
/usr/local/bin/imapsync --tmpdir /tmp --nofoldersizes --exclude (?i)spam|(?i)junk --delete2duplicates --subscribeall --delete --automap --ssl1 --host1 imap.example.net --user1 userxxx --passfile1 /tmp/imapsync.DYYaqyR --port1 995 --host2 localhost --user2 user@example.org*mypassword@mailcow.local --passfile2 /tmp/imapsync.1P72gYZ --no-modulesversion --noreleasecheck
~~~

I expect the log not to contain any passwords or at least a proper replacement.

~~~
/usr/local/bin/imapsync --tmpdir /tmp --nofoldersizes --exclude (?i)spam|(?i)junk --delete2duplicates --subscribeall --delete --automap --ssl1 --host1 imap.example.net --user1 userxxx --passfile1 /tmp/imapsync.DYYaqyR --port1 995 --host2 localhost --user2 user@example.org*xxxx@mailcow.local --passfile2 /tmp/imapsync.1P72gYZ --no-modulesversion --noreleasecheck
~~~

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.
- [x] I do run mailcow on Docker/Docker-Compose in a VM

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | CentOS 7.x |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM, ProxMox |
| Server/VM specifications (Memory, CPU Cores) | 4 GiB,  1 CPU, 1 Core|
| Docker Version (`docker version`) |  19.03.1 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.18.0, build 8dd22a9  |
| Reverse proxy (custom solution) | Traefik |

My setup should look like this:

~~~
[ Mailcow ] -> SMTP with TLS encryption -> [ External Mail Provider ]:587
~~~

I'm using the latest "docker-compose" setup with some minor modifications due to my local environment. I'm using these container images:

~~~
ipv6nat-mailcow (robbertkl/ipv6nat) (Started on Tue, 20 Aug 2019 00:47:55 +0200)
rspamd-mailcow (mailcow/rspamd:1.45) (Started on Mon, 19 Aug 2019 23:32:32 +0200)
acme-mailcow (mailcow/acme:1.61) (Started on Mon, 19 Aug 2019 23:32:31 +0200)
netfilter-mailcow (mailcow/netfilter:1.28) (Started on Mon, 19 Aug 2019 23:32:28 +0200)
nginx-mailcow (nginx:mainline-alpine) (Started on Mon, 19 Aug 2019 23:32:29 +0200)
php-fpm-mailcow (mailcow/phpfpm:1.43) (Started on Mon, 19 Aug 2019 23:32:26 +0200)
olefy-mailcow (mailcow/olefy:1.1) (Started on Mon, 19 Aug 2019 23:32:25 +0200)
mysql-mailcow (mariadb:10.2) (Started on Mon, 19 Aug 2019 23:32:25 +0200)
clamd-mailcow (mailcow/clamd:1.27) (Started on Mon, 19 Aug 2019 23:32:24 +0200)
redis-mailcow (redis:5-alpine) (Started on Mon, 19 Aug 2019 23:32:25 +0200)
watchdog-mailcow (mailcow/watchdog:1.56) (Started on Mon, 19 Aug 2019 23:32:24 +0200)
dovecot-mailcow (mailcow/dovecot:1.85) (Started on Mon, 19 Aug 2019 23:32:24 +0200)
memcached-mailcow (memcached:alpine) (Started on Mon, 19 Aug 2019 23:32:20 +0200)
solr-mailcow (mailcow/solr:1.6) (Started on Mon, 19 Aug 2019 23:32:23 +0200)
dockerapi-mailcow (mailcow/dockerapi:1.32) (Started on Mon, 19 Aug 2019 23:32:18 +0200)
postfix-mailcow (mailcow/postfix:1.37) (Started on Mon, 19 Aug 2019 23:32:22 +0200)
unbound-mailcow (mailcow/unbound:1.8) (Started on Mon, 19 Aug 2019 23:32:19 +0200)
sogo-mailcow (mailcow/sogo:1.58) (Started on Tue, 20 Aug 2019 00:45:28 +0200)
~~~

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
We use passfiles. What am I missing?

**Comment by maxmeyer** [comment]
when you have a look at the imap sync logs, it records a password in the log file or at least it looks like a password

~~~
--user2 user@example.org*mypassword@mailcow.local
~~~

**Comment by andryyy** [comment]
That's just the master user. :) both are random strings. 

The master user and password are regenerated when you restart Dovecot.

**Comment by maxmeyer** [comment]
Ok. That's fine for me. Thanks.
