### ISSUE TITLE
Dovecot DOV-3278 (bump version)

### ISSUE THREAD

**Issue by Adorfer** [mailcow/mailcow-dockerized#2889]
Please check for https://www.openwall.com/lists/oss-security/2019/08/28/3 if mailcow is affected.

Internal reference: DOV-3278
Vulnerability type: Improper input validation (CWE-20)
Vulnerable version: All versions prior to 2.3.7.2 and 2.2.36.

**Comment by chibacityblues** [comment]
I just ran update.sh and dovecot got bumped to 2.3.7.2 (it has been 2.3.6 prior):

```
$ docker exec mailcow_dovecot-mailcow_1 dovecot --version
2.3.7.2 (3c910f64b)
```

**Comment by chibacityblues** [comment]
Sidenote: Pigeonhole / Managesieve prior to 0.5.7.2 is affected also. After updating, Pigeonhole is fine too:
```
docker exec mailcow_dovecot-mailcow_1 dovecot -n |grep Pigeonhole
# Pigeonhole version 0.5.7.2 (7372921a)
```

**Comment by Adorfer** [comment]
checked: 

```
 docker exec  mailcowdockerized_dovecot-mailcow_1 dovecot --version
2.3.7.1 (0152c8b10)
```
update.sh, check again

```
 docker exec  mailcowdockerized_dovecot-mailcow_1 dovecot --version
2.3.7.2 (3c910f64b)
```


issue resolved, can be closed, i assume.
