### ISSUE TITLE
License

### ISSUE THREAD

**Issue by strugee** [mailcow/mailcow-dockerized#289]
This project needs a license.

https://choosealicense.com/

**Comment by andryyy** [comment]
Done. :-)

**Comment by Hillside502** [comment]
@andryyy 
So what does:-

> Done. :-)

mean?

**Comment by Braintelligence** [comment]
It means there's a license in the codebase now.

**Comment by Hillside502** [comment]
@Braintelligence 
A link would be useful.

**Comment by mkuron** [comment]
RIght where you'd expect to find it: https://github.com/mailcow/mailcow-dockerized/blob/master/LICENSE

**Comment by Braintelligence** [comment]
Really? Please click on Code and then on the file named LICENSE. It's the standard location on most Github projects. I'm on mobile right now.

**Comment by Hillside502** [comment]
@mkuron @Braintelligence 
Your defensiveness is glaringly obvious --- clearly this project is anything but **OPEN**.

**Comment by Braintelligence** [comment]
I'm not sure what's going on here. You wanted a license and it was created in a short timeframe. You were demanding a link to the license even though you can find it in the standard location or in the related commit. We helped you out with each demand in time and the code is completely open. 

I don't understand the reason for your rude and demanding behaviour here.

**Comment by andryyy** [comment]
I mentioned it in a previous issue: mailcow itself will stay licensed under GPLv3. I would have prefered having a list of licenses used by the great software projects mailcow makes use of (thanks to ALL of you!). I hope to add it someday.

**Comment by Braintelligence** [comment]
@andryyy no sweat! You're doing great work. Just keep it coming. 😸

**Comment by Hillside502** [comment]
> demanding ... each demand --- rude and demanding behaviour

What a bunch of retentives!

Don't call me, I'll call you.

**Comment by strugee** [comment]
@Hillside502 stop. Seriously. Just stop.

I've persistently seen you being rude and abusive to other people in GitHub issue threads, to the point where I've had to delete comments because they contained offensive slurs. You consistently engage in personal attacks that contribute nothing to technical matters, and the demands and allegations you're making in this thread are pretty unreasonable and, frankly, border on arrogant.

This isn't PRISM Break's issue tracker so it isn't governed by PRISM Break's Code of Conduct, but I'll say that this kind of aggressive, personal attack wouldn't be tolerated there. You need to calm down.

In the end, please remember that everyone here is a real person. The fact that this is the internet isn't an excuse for being an ass to other people. [It's easier to be an asshole to words than to people:](https://www.xkcd.com/438/)

[![It's easier to be an asshole to words than to people.](https://imgs.xkcd.com/comics/internet_argument.png)](https://www.xkcd.com/438/)

**Comment by Hillside502** [comment]
@strugee 
As I said:-

> Don't call me, I'll call you.

**Comment by PhoenixPeca** [comment]
I don't like where this is going.
I believe this issue has been resolved. I'm locking this now.
