### ISSUE TITLE
"Spam filtering gateway" mode 

### ISSUE THREAD

**Issue by jonprocter** [mailcow/mailcow-dockerized#2892]
Hi! I've pretty much fallen in love with Mailcow - you've done an amazing job on it. Have a feature idea/request though, a kind of spam filtering gateway mode.

I currently use a Postfix server that grabs lists of domains from other hosting servers and then imports that and makes transport rules based on it, but it's pretty basic. The ability to do that with Mailcow and still be able to use the quarantine feature would be super useful.

**Comment by Adorfer** [comment]
Spam filtering depending on user preferences just works with a setting "per user" (known to your MTA). 
In plus: Without the knowlede if a mailbox/localpart is valid or not, you can not bounce/greylist in a responsible way.
