### ISSUE TITLE
Please update Dovecot to 2.3.7.2

### ISSUE THREAD

**Issue by udoL** [mailcow/mailcow-dockerized#2893]
Hi,
due an critical security vulnerability provide an docker dovecot-container with dovecot 2.3.7.2 please.

See here: https://www.openwall.com/lists/oss-security/2019/08/28/3

Best regards

Udo

**Comment by patschi** [comment]
That's already fixed. Duplicate of #2890 and #2889.

**Comment by Adorfer** [comment]
@udoL
please check before raising false alarms
