### ISSUE TITLE
Dovecot update

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#2897]
Ich hab gerade das hier bei Heise gesehen:
https://www.heise.de/security/meldung/Sicherheitsupdate-Mail-Server-Dovecot-fuer-Schadcode-Attacken-anfaellig-4510408.html

Ist das Dovecot von Mailcow schon geupdatet?

**Comment by Braintelligence** [comment]
1. Please keep it in English.
2. Next time please put at least minimum effort in finding the duplicates of your issue.
3. This is already patched.

EDIT for protocol: Duplicate of #2893 and #2890 and #2889.
