### ISSUE TITLE
Public shared mailboxes

### ISSUE THREAD

**Issue by Hackebein** [mailcow/mailcow-dockerized#2898]
**Is your feature request related to a problem? Please describe.**
I'm searching for a feature that allow users to have multiple mailbox with one login. Not the "Shared by another user" function. The goal is a shared collaboration mailbox for all users or for a group of users (ex. a department).

**Describe the solution you'd like**
I find this functionality in the wiki of dovecot.
https://wiki.dovecot.org/SharedMailboxes/Public

**Additional context**
I can make a PR, if this functionality is desired.

**Comment by Winteriver** [comment]
For me it would be also fine to add this manually to dovecot, but to make it "updateproof"...
As far as I can remember this feature was part of the "non-dockerized mailcow" version.

Thanks, Markus

**Comment by andryyy** [comment]
You can create a new file extra.conf in data/conf/dovecot/ and add a public namespace. Should work.

**Comment by Hackebein** [comment]
> You can create a new file extra.conf in data/conf/dovecot/ and add a public namespace. Should work.

It's not a question about how can "I" do it. The question is about "Are you fine with a PR for that?"
> I can make a PR, if this functionality is desired.

**Comment by andryyy** [comment]
Can you elaborate that? :) Do you also want to create a switch for that in mailcow UI? Or just a mailcow.conf entry?

**Comment by Hackebein** [comment]
> Can you elaborate that?

yes

> Do you also want to create a switch for that in mailcow UI?

yes, with every functionality that is needed for an easy setup.
Do you have any idea or recommendation where to place it?
Anything special that i need to care about?

I should definitely write more questions in an issue next time.

**Comment by andryyy** [comment]
/admin -> Config? :)

Would be nice if we could reload Dovecot from the UI then, dockerapi-mailcow has an endpoint for that. so I can also add it to the UI API to trigger it like `/api/v1/reload/dovecot` or something like that.

**Comment by Winteriver** [comment]
Sorry, Hackebein!
I did not read your first message completely...

Would be great to have this feature inside mailcow!!!

What about to put it to \configuration\email-setup\public folder?
It would be great to choose the users from mailcow UI for ACLs.

**Comment by Hackebein** [comment]
I was just in the UI looking for a suitable place. Isn't it rather a mix of resource [/mailbox#tab-resources] and an alias [/mailbox#tab-mbox-aliases]? Is it something for it own or something that belongs to one of the two?

> /admin -> Config? :)

@andryyy Configuration [/admin#tab-config] looks more like general configuration options expect ARC/DKIM keys (Is the place right for ARC/DKIM keys? Shouldn't it be in the Mailbox Domain configuration edit [/edit/domain/sld.tld]? Sorry for the random question).

> Would be nice if we could reload Dovecot from the UI then, dockerapi-mailcow has an endpoint for that. so I can also add it to the UI API to trigger it like /api/v1/reload/dovecot or something like that.

@andryyy Isn't it already implemented at this point? [/data/Dockerfiles/dockerapi/server.py#L88-L92](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dockerapi/server.py#L88-L92) or did i miss something?

> What about to put it to \configuration\email-setup\public folder?

@birduser Unfortunately I don't know this place. Could you please explain that a bit more?

> It would be great to choose the users from mailcow UI for ACLs.

Sounds a very good idea. I'll try to add this.

**Comment by Winteriver** [comment]
@Hackebein 
Sorry, my setup was in German language.

Just to suggest where to put a settings tab:
Configuration > Mail setup (> Public Folders)
I attach a screenshot of the menu, I was thinking of.

![20190902-Screenshot 002](https://user-images.githubusercontent.com/35183090/64125947-21675580-cdac-11e9-98bc-fc76d1161764.png)

**Comment by Hackebein** [comment]
Unfortunately, I have to disappoint you. So far there is no progress. It looked easier in the beginning. I am unable to create a public mailbox in dovecot. I think it's because of my little experience how dovecot works and that I overlook anything in the preconfigured Mailcow. Can someone help me how to customize a freshly installed mailcow to get a single public mailbox?

**Comment by CodeNinja1337** [comment]
> Unfortunately, I have to disappoint you. So far there is no progress. It looked easier in the beginning. I am unable to create a public mailbox in dovecot. I think it's because of my little experience how dovecot works and that I overlook anything in the preconfigured Mailcow. Can someone help me how to customize a freshly installed mailcow to get a single public mailbox?

I would love to help you out as i also need this feature. Unfortunately my dovecot knowledge is almost 0 :(
