### ISSUE TITLE
mysql_virtual_sender_acl.cf SQL leads to "Sender address rejected: not owned by user" for alias domains

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#29]
We're once again seeing a problem where I'm not sure if it has something to do with our local configuration or is a Mailcow issue. In case it is Mailcow related I'll post it anyways:

The primary domain of a user (mailcow login "user@primary-domain.com") has a couple of alias domains. For the alias domains the user now also has some aliases (one of it is "nickname@alias-domain.com"). In the user's mailbox "Do not check sender for domain primary-domain.com" is checked. There are no entries for alias-domain.com which could be checked (as expected as they should behave like the primary domain). Grayed out but checked there also is an entry "nickname@alias-domain.com".
However, when the users tries to send as "nickname@alias-domain.com" postfix won't let him with "Sender address rejected: not owned by user user@primary-domain.com".
I'm not sure if there are some entries missing in `sender_acl` or something but when I try to recreate the user there is the same problem.

Therefore I looked at the SQL in `mysql_virtual_sender_acl.cf` and that looked to me as it cannot work when the user tries to send with "nickname@alias-domain.com" and only "user@alias-domain.com" could work (but again, I'm not sure if there should be some other SQL besides `mysql_virtual_sender_acl.cf` which should take care of that...).
So the current SQL looks like this

```sql
SELECT goto
FROM alias
WHERE address='%s'
  AND active='1'
  AND domain IN
    (SELECT domain
     FROM domain
     WHERE domain='%d'
       AND active='1')
UNION
SELECT logged_in_as
FROM sender_acl
WHERE send_as='@%d'
  OR send_as='%s'
  AND logged_in_as NOT IN
    (SELECT goto
     FROM alias
     WHERE address='%s')
UNION
SELECT goto
FROM alias,
     alias_domain
WHERE alias_domain.alias_domain = '%d'
  AND alias.address = CONCAT('%u', '@', alias_domain.target_domain)
  AND alias.active ='1'
  AND alias_domain.active='1'
```
When I add two sub selects for the alias domains in the union select from `sender_acl` everything works for me. Here the now working SQL:

```sql
SELECT goto
FROM alias
WHERE address='%s'
  AND active='1'
  AND domain IN
    (SELECT domain
     FROM domain
     WHERE domain='%d'
       AND active='1')
UNION
SELECT logged_in_as
FROM sender_acl
WHERE send_as='@%d'
  OR send_as='%s'
  OR send_as IN
    ( SELECT CONCAT ("@",target_domain)
     FROM alias_domain
     WHERE alias_domain = '%d' )
  OR send_as IN
    ( SELECT CONCAT ("%u", "@",target_domain)
     FROM alias_domain
     WHERE alias_domain = '%d' )
  AND logged_in_as NOT IN
    (SELECT goto
     FROM alias
     WHERE address='%s')
UNION
SELECT goto
FROM alias,
     alias_domain
WHERE alias_domain.alias_domain = '%d'
  AND alias.address = CONCAT('%u', '@', alias_domain.target_domain)
  AND alias.active ='1'
  AND alias_domain.active='1'
```

The strange thing is the user with the problem is using GMail and was able to setup the problematic alias two or three weeks ago. So I guess this means it was working with the old SQL at some point but I also don't know how the GMail alias configuration is working...

// Edit: looking at the working SQL a second time I think it would ignore inactive aliases currently so I guess it would need a polishment regarding that matter ;-)

**Comment by andryyy** [comment]
Good catch. :-)

Thanks for reporting it. I was about to create some tests for these selects.

I made alias domains selectable now. But I am struggling wether or not to make them act like the assigned primary domain.

**Comment by tehXor** [comment]
> But I am struggling wether or not to make them act like the assigned primary domain.

For me it would seem logical that an alias domain acts like the primary domain. Would I want different configuration than the primary domain I'd add a new primary domain ;-)
