### ISSUE TITLE
acme CA problem

### ISSUE THREAD

**Issue by oehTie** [mailcow/mailcow-dockerized#2900]
Hi,

Today my certificates expired. Wondering why letsencrypt stopped working, i finally tried the following:

docker-compose exec acme-mailcow curl -4 -IL -v https://<MAILCOWHOSTNAME>/.well-known/acme-challenge/1
*   Trying x.x.x.x:443...
* TCP_NODELAY set
* Connected to xxxxx.xx (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@server:/home/user/mailcow-dockerized#

as in..... anyone have a clue what is going on? I can't seem to get this to life again...  When i restart the acme container the log fills up with:

Confirmed A record with IP x.x.x.x, but HTTP validation failed.... and no certificate is created for them.

looks like the mailcow CA in the acme client is expired or otherwise invalid...

can anyone please help? 

Thanks in advance.

**Comment by oehTie** [comment]
just checked and verified, my ca file is the same as 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/assets/ssl-example/ca.pem

**Comment by oehTie** [comment]
i'm happy to provide more info, please let me know what you need.

**Comment by andryyy** [comment]
You should run the curl check with --insecure :)

Nevertheless, acme-mailcow logs would be great. Or more info about your setup in general (reverse proxy?).

**Comment by oehTie** [comment]
with --insecure the check works, thanks for that hint. 

just a bit from the logs:


1-9-2019 23:45:19 | Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
1-9-2019 23:45:19 | Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
1-9-2019 23:45:19 | Confirmed A record with IP x.x.x.x, but HTTP validation failed
1-9-2019 23:45:19 | Found A record for mail.domain.com: x.x.x.x

i get the "validation failed" and the "Found a record" message for almost every domain i have on the server. A few domains do not have the autodiscover and autoconfig A-records but i cannot acces those DNS settings so i can accept for now that these are skipped.



a little bit about my setup: pfsense firewall with public IP. NAT is used to route traffic to an internal 10.x.x.x ip where the mailserver runs. Server is a VM on VMware 6.7, 8 GB ram, 4 CPU and 500 GB ssd storage. I do not use proxy's, just the NAT, and i relay mail to the outside world via a smarthost which is configured in mailcow.

I hope this helps :)

**Comment by patschi** [comment]
> docker-compose exec acme-mailcow curl -4 -IL -v https:///.well-known/acme-challenge/1

You'll need to test with HTTP, not with HTTPS. Furthermore check if port 80 is forwarded correctly.

**Comment by oehTie** [comment]
the forward should be correct... but the acme-challenge/1 file stays empty. 

i followed this post: https://github.com/mailcow/mailcow-dockerized/issues/2498#issuecomment-480145397 and touched the 1 file to create it.

the checks in this post:

root@hostname:/home/user/mailcow-dockerized# docker-compose exec acme-mailcow curl -4 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
301
root@hostname:/home/user/mailcow-dockerized# docker-compose exec acme-mailcow curl -4 https://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
000
root@hostname:/home/user/mailcow-dockerized# docker-compose exec acme-mailcow curl -4 https://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code} --insecure
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
404
root@hostname:/home/user/mailcow-dockerized#

**Comment by andryyy** [comment]
Im sure it does not route correctly from within the containers. pfSense probably sees the connection from within the container as something ... else. Don't know.

Please post the output of

```
echo 1 > data/web/.well-known/acme-challenge/test
source mailcow.conf
docker-compose exec acme-mailcow curl --insecure -I https://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
```

**Comment by oehTie** [comment]
that seems to work:

root@hostname:/home/user/mailcow-dockerized# echo 1 > data/web/.well-known/acme-challenge/test
root@hostname:/home/user/mailcow-dockerized# source mailcow.conf
root@hostname:/home/user/mailcow-dockerized# docker-compose exec acme-mailcow curl --insecure -I https://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
HTTP/2 404
server: nginx
date: Sun, 01 Sep 2019 22:06:29 GMT
content-type: text/html
content-length: 162

root@hostname:/home/user/mailcow-dockerized#

**Comment by oehTie** [comment]
within the containers shouldn't go via pfsense, as that is al internal traffic. Only traffic between the 10.x.x.x network and the outside world should hit pfsense as its gateway. Or am i wrong in this sense?

**Comment by oehTie** [comment]
i have portainer running and i'm willing to give you access to the server if that would be easier for further testing....

**Comment by oehTie** [comment]
i do see now that i get errors in my firewall log. 

nginx: 2019/09/02 00:21:37 [error] 51015#100100: *1856 open() "/usr/local/www/.well-known/acme-challenge/109903239822710" failed (2: No such file or directory), client: 10.x.x.x, server: , request: "GET /.well-known/acme-challenge/109903239822710 HTTP/2.0", host: "mail.domain.com"

looks like mailcow is asking pfsense for the challange while it has it on its own server... this is a new for me.  (just fyi, the whole setup has been running fine for more than a year including letsencrypt)

**Comment by andryyy** [comment]
Check the routing. That's what I meant. Your pfSense catches the request and answers it. It does not pass it. Probably a NAT reflection helps.

Cannot resolve this in mailcow. We don't touch your internal routing.

You can disable the HTTP verification and ignore this routing error, as it does not affect external traffic routed to the cow. It only affects hair pinned connections - that's what it looks like at least. DNS checks will not work though (some). 

I guarantee you we cannot change or manipulate the routing of your firewall. :) This probably worked before the HTTP checks were implemented. They should not fail.

**Comment by oehTie** [comment]
looks like you're right, thanks for pointing me in the right direction here. pfsense was responding, but not with the right answers hence the failed validations...

I have set the skip-http-verification to yes and now it does generate certificates...

at least everything is back online now with working certificates. It's past midnight here, when i'm more awake tomorrow i'll have a look if i can get pfsense to stop interfering. It shouldn't in this case.

Thank you for your help. I owe you a beer. Really appreciate it.

**Comment by oehTie** [comment]
This probably worked before the HTTP checks were implemented.

note to self: check changelogs better when updating... i must have missed this one.

**Comment by andryyy** [comment]
You're welcome :)
