### ISSUE TITLE
No Login possible on Mailcow

### ISSUE THREAD

**Issue by Nowustec** [mailcow/mailcow-dockerized#2901]
Hey guys,

after setting up the Mailcow correctly I try to login there now after around 10 days.
Can type in my Name and password and after that it load load load but don´t let me in.

Is this a known issue or I am only to stupid to login :D 

Thought maybe wrong credentials, so changed to standard by console and still not working this login.
But is a damn problem have to deliver more than 200 Mailboxes in short time.

Thanks in advance.

**Comment by andryyy** [comment]
Have you tried to reset your login?

**Comment by Nowustec** [comment]
Hey Patrick,Ja habe ich getan, hatte n edit reingepackt. Habe auch den kompletten Server mit Update beglückt und dann den kompletten Server neu gestartet. Nun komme ich zumindest über Firefox rein, Chrome und ie lädt der sich leider tot. Dies an mehreren Rechnern die auch nicht an einem Router hängen. Bin ein wenig irritiert 😅Herzliche Grüße Michael Am 02.09.2019 09:44 schrieb André Peters <notifications@github.com>:Have you tried to reset your login?
