### ISSUE TITLE
Update Dovecot due to potential Security hole

### ISSUE THREAD

**Issue by ClundXIII** [mailcow/mailcow-dockerized#2903]
Hello,

just a ping to the developer, please update Dovecot to the newest version.

https://www.openwall.com/lists/oss-security/2019/08/28/3

Regards,
Simon

**Comment by Conan179** [comment]
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/2897

**Comment by Adorfer** [comment]
Duplicate of #2893 and #2890 and #2889.
