### ISSUE TITLE
Watchdog ALERT: unbound-mailcow "DNSSEC failure"

### ISSUE THREAD

**Issue by abmiller99** [mailcow/mailcow-dockerized#2906]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:

I'm receiving a watchdog email every 7-8 minutes with report of:

>DNS OK: 7.046 seconds response time. stackoverflow.com returns 151.101.1.69,151.101.129.69,151.101.193.69,151.101.65.69|time=7.045764s;;;0.000000
>DNSSEC failure

Approx 15 lines like the above in each email
[Watchdog ALERT.txt](https://github.com/mailcow/mailcow-dockerized/files/3575233/Watchdog.ALERT.txt)

In the Watchdog logs the service Unbound reports "Health level: 0% (0/5)", "Health level: 20% (1/5)" etc..

---

**System information**

I'm running up-to-date, dedicated mailcow dockerized on:

Host: Amazon EC2 
Spec: EC2 (t2.small) [1 cpu | 2 GB ram | 4GB swap]
OS: Debian 9 (stretch)
Kernel: 4.9.0-9-amd64

docker version: 19.03.2
docker-compose version 1.24.1

Reverse proxy: no.

---

**Further notes:**
 - Output of `git diff origin/master` [git-diff.txt](https://github.com/mailcow/mailcow-dockerized/files/3575208/git-diff.txt)
 - `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
[$ iptables -L -vn.txt](https://github.com/mailcow/mailcow-dockerized/files/3575211/iptables.-L.-vn.txt)
[$ ip6tables -L -vn.txt](https://github.com/mailcow/mailcow-dockerized/files/3575241/ip6tables.-L.-vn.txt)
[$ iptables -L -vn -t nat.txt](https://github.com/mailcow/mailcow-dockerized/files/3575213/iptables.-L.-vn.-t.nat.txt)
[$ ip6tables -L -vn -t nat.txt](https://github.com/mailcow/mailcow-dockerized/files/3575216/ip6tables.-L.-vn.-t.nat.txt)

**$ docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254**
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

**$ docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1**
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

**Comment by AikoAppeldorn** [comment]
The same problem occurs to me.
I think Stackoverflow has dropped dnssec support:
![image](https://user-images.githubusercontent.com/6564899/64287561-4f8d9680-cf60-11e9-9c96-ab1d3f7a8bdf.png)
https://dnssec-debugger.verisignlabs.com/stackoverflow.com

**Comment by andryyy** [comment]
It should be the missing dns flag in watchdog. Fixed in a bit.

**Comment by AikoAppeldorn** [comment]
It works now. Thanks.

**Comment by T0biii** [comment]
Update Fixed it for me! Thanks.

**Comment by abmiller99** [comment]
Updated and everything is OK again - thanks

**Comment by robetus** [comment]
This is happening again.
