### ISSUE TITLE
User for sending from specific mail addresses

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#2907]
**Is your feature request related to a problem? Please describe.**
A website has a form. The form data should also be sent via email.
The email that should send the form submission data should also be usable for a mailbox user.

**Describe the solution you'd like**
Users that can send from specific mail addresses (e.g. forms of websites).

**Additional context**
Going further, these users should also be selectively able to receive mail to specific addresses.

**Comment by FingerlessGlov3s** [comment]
I'm confused, What are you trying to achieve?

**Comment by strarsis** [comment]
@FingerlessGlov3s: User with IMAP client should be able to access mailbox (e.g. info@example.com).
Website should be able to send forms from mail address info@example.com using different username + password.

**Comment by patschi** [comment]
Mailcow does only send mails you instruct the mailserver to send. It can't do magic. If you would like to send mails using a different account, you should simply setup your application/server accordingly to use different SMTP credentials. That's nothing mailcow will do for you.

**Comment by strarsis** [comment]
@patschi: Can I create a new user in mailcow-docker UI and allow it only to send mail from a specific email address?

**Comment by FingerlessGlov3s** [comment]
> @patschi: Can I create a new user in mailcow-docker UI and allow it only to send mail from a specific email address?

You create a mailbox (basicly a user) and by default its only allowed to send from that one address.

**Comment by strarsis** [comment]
@FingerlessGlov3s: So the requested feature would be the ability to create (mailbox-less?) users that can send email that belong to other mailboxes.

**Comment by patschi** [comment]
When editing a mailbox you can already specify under which email addresses the user is allowed to send ("Allow to send as").

**Comment by strarsis** [comment]
@patschi: So I can create a 2nd user with a "dummy" mailbox and assign the email address of the other mailbox (user) under "Allow to send as"?

**Comment by patschi** [comment]
Yes, exactly.
