### ISSUE TITLE
is anonymize_headers.pcre is broken??? "Authenticated sender" leaked

### ISSUE THREAD

**Issue by FingerlessGlov3s** [mailcow/mailcow-dockerized#2909]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

My issue is when I send an email via SMTP using Thunderbird. In the email headers the recipient can the "Authenticated sender". Which is abit of a security risk in some ways.
From the looks of it we've removing the senders IP, but shouldn't we be removing the "Authenticated sender" as well? 

https://gist.github.com/FingerlessGlov3s/6aecc2da9900cfa1b30777e7fa27242b

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3|
| Is Apparmor, SELinux or similar active? | shall check later |
| Virtualization technlogy (KVM, VMware, Xen, etc) | I believe Scaleway use VMware |
| Server/VM specifications (Memory, CPU Cores) | 3 cores, 4GB Ram |
| Docker Version (`docker version`) | 19.03 |
| Docker-Compose Version (`docker-compose version`) | v1.24.1 |
| Reverse proxy (custom solution) | NOPE |

**Comment by patschi** [comment]
The `Authenticated sender` is required for ARC: https://github.com/mailcow/mailcow-dockerized/issues/1971#issuecomment-525976884

**Comment by FingerlessGlov3s** [comment]
I've read up on it a bit and I'm confused now, how come provides like, Gmail, Protonmail, even Cloudflare emails, don't include it in their Received header?

Surely Gmail and Protonmail would want ARC to work for their customers/users? Especially Protonmail, their whole thing is based around encryption and security.

**Comment by FingerlessGlov3s** [comment]
Did some reading up since my last comment and have now commented in the referenced issue.

I've read ietf documents and other websites explaining how it works. ietf, is the best place as it's the Standards organization.

**Comment by FingerlessGlov3s** [comment]
Just trying to edit my anonymize_headers.pcre, but I've broke it somehow?
https://regex101.com/ show's my regex as correct

I've gotten the regex and replace as follows now, but it doesn't REPLACE it at all.
Using the following command in the postfix docker container, works and shows the replaced header, so postmap says its ok but doesn't actually work when you come to send an email.
`postmap -q "insert header from failed test email" regexp:/opt/postfix/conf/anonymize_headers.pcre`

```
/^\s*Received:.*Authenticated sender:.*\) by(.+)/
  REPLACE Received: from localhost (localhost [127.0.0.1]) by$1
```

tested heder

```
Received: from [192.168.xx.xx] (Remove.com [78.144.xx.xx]) (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (4096 bits)) (No client certificate requested) (Authenticated sender: FingerlessGloves@Remove.com) by mail.Remove.com (Postcow) with ESMTPSA id 68C29A1713 for <testgmailaccount@gmail.com>; Thu,
  5 Sep 2019 18:29:31 +0100 (BST)
```

**Comment by FingerlessGlov3s** [comment]
After some trial and error I've got a working! Authenticated user is now removed from the "Received:" header. I don't see why we need the if statement either anymore either.

Did some testing and ARC works, so no worries there.


```
/^\s*(Received: from).*Authenticated sender.*by(.*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2

/^\s*X-Enigmail/        IGNORE
/^\s*X-Mailer/          IGNORE
/^\s*X-Originating-IP/  IGNORE
/^\s*X-Forward/         IGNORE
# Not removing UA by default, might be signed
#/^\s*User-Agent/        IGNORE
```

**Comment by andryyy** [comment]
So you just removed it, because you don't understand it? :(

It is _very_ important to keep it. I don't want to remove other headers besides the Postcow hop.

The regex is also not optimal, can be done a little bit easier.

**Comment by FingerlessGlov3s** [comment]
> So you just removed it, because you don't understand it? :(

I removed it because when I want to send as another address, I'd rather not tell people what my main mailbox is for when I'm using a throw away address.

So if you only want to do the Postcow hop, we can only apply to the header if it also contains "(Postcow)". This would work as long as your not chaining mailcow email servers, but if they all had this regex then it wouldn't be an issue.
If there's a way to add the mail server's DNS name to regex via a variable that would work a treat. As it would then only ever effect your mail server. But I doubt that exists, unless you were to generate the anonymize_headers.pcre file to put in the DNS hostname when you setup mailcow.

```
/^\s*(Received: from).*Authenticated sender.*by(.*\(Postcow\).*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2
```
Or a version of this with the hostname as well of looking for the mail system name.
```
/^\s*(Received: from).*Authenticated sender.*by(.*mail\.example\.com.*\(Postcow\).*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2
```
Also I know the Regex can be made smaller, etc. I can do regex but I'm no master at it 😆 


If the reason to keep it is to make sure your not modifying someone else's Received header, I fully understand, unless there's something else your trying to tell me. 😄 

If you don't want to mess with other people's installs I'll just hardcode in my DNS name instead of Postcow, and that would solve my issue without effecting other headers right? 🤔

**Comment by mkuron** [comment]
> If the reason to keep it is to make sure your not modifying someone else's Received header, I fully understand

That‘s exactly the purpose of the `if`. I don‘t understand why removing it fixes your problem though.

**Comment by FingerlessGlov3s** [comment]
Are you talking about removing the if or the whole Removing "Authenticated Sender: user@domain.com"  that fixes my problem? 

I removed the if because I just made it part of the regex, don't see why it's needed, if the regex

**Comment by FingerlessGlov3s** [comment]
Yeah I shouldn't of removed the if. I was trying so many combinations of regex to get it picking up correctly. Now I've slept now and I see what I did, didn't need to be removed. Sorry about that.

If I put the original if back in it still works, but if I've put the (Postcow) in my regex REPLACE, then doesn't that make the if no longer required?

```/^\s*(Received: from).*Authenticated sender.*by(.*\(Postcow\).*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2```

**Comment by FingerlessGlov3s** [comment]
I'm closing this issue, as I don't believe anything will be changed, reopen if I'm wrong 😄 

I've set my "anonymize_headers.pcre" as follows, so if anyone comes across this page and wanting to do this, then they can replace theirs with the below. This will only target Received headers with "Authenticated sender" and "(Postcow)" in it.

```
/^\s*(Received: from).*Authenticated sender.*by(.*\(Postcow\).*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2

/^\s*X-Enigmail/        IGNORE
/^\s*X-Mailer/          IGNORE
/^\s*X-Originating-IP/  IGNORE
/^\s*X-Forward/         IGNORE
# Not removing UA by default, might be signed
#/^\s*User-Agent/        IGNORE
```


This one below has an extra check in the REGEX to make sure its got your mail server's domain in it.
This will only target Received headers with "Authenticated sender", "(Postcow)" and your mail server's domain in it.

**NOTE:** Make sure you replace the mail.domain.com bit with your mail server's domain, otherwise the REGEX won't match 😄 

```
/^\s*(Received: from).*Authenticated sender.*by(.*mail\.domain\.com.*\(Postcow\).*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1]) by$2

/^\s*X-Enigmail/        IGNORE
/^\s*X-Mailer/          IGNORE
/^\s*X-Originating-IP/  IGNORE
/^\s*X-Forward/         IGNORE
# Not removing UA by default, might be signed
#/^\s*User-Agent/        IGNORE
```

**Comment by FingerlessGlov3s** [comment]
Didn't see the Commit - https://github.com/mailcow/mailcow-dockerized/commit/8608ded0ed4c87f40960751c9ad7a9b9eca029e6

Thank you ;-) not sure why you put more regex in. I don't see why its needed but there must be a valid reason, to why you did this. 

EDIT: Not sure Postcow was replaced with Mailerdaemon and mail server is now localhost?
