### ISSUE TITLE
Adding an domain into SSL cert

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#291]
Hi,

I have problem with adding domain to my LE SSL cert. I run this inside the mailcow-dockerized folder:

```
source mailcow.conf
certbot certonly \
    --webroot \
    -w ${PWD}/data/web \
    -d ${MAILCOW_HOSTNAME} \
    -d mail.fusionolomouc.cz \
    -d mail.lfczradio.eu \
    -d mail.olimpex.eu \
    -d mail.spsgo.cz \
    --email cechacek@olimpex.eu \
    --agree-tos 
```
It was without any problem - I got my certs generated.
Then I did this:

```
mv data/assets/ssl/cert.{pem,pem.backup}
mv data/assets/ssl/key.{pem,pem.backup}
ln $(readlink -f /etc/letsencrypt/live/${MAILCOW_HOSTNAME}/fullchain.pem) data/assets/ssl/cert.pem
ln $(readlink -f /etc/letsencrypt/live/${MAILCOW_HOSTNAME}/privkey.pem) data/assets/ssl/key.pem
```

Also without andy problem. Then I just restarted the dockers with command:

`docker-compose restart postfix-mailcow dovecot-mailcow nginx-mailcow`

Restart was too without any problem, but I am still getting old certificate from the website, so the new added domain https://mail.spsgo.cz is still with unvalid cert.

Can you help me with that? Thanks

**Comment by andryyy** [comment]
Can you show the content of your folder "/etc/letsencrypt/live/"?

**Comment by DJIronic** [comment]
Here it is: https://i.imgur.com/TLoCvk8.png

**Comment by andryyy** [comment]
Should work with...

```
mv data/assets/ssl/cert.{pem,pem.backup}
mv data/assets/ssl/key.{pem,pem.backup}
ln $(readlink -f /etc/letsencrypt/live/${MAILCOW_HOSTNAME}-0001/fullchain.pem) data/assets/ssl/cert.pem
ln $(readlink -f /etc/letsencrypt/live/${MAILCOW_HOSTNAME}-0001/privkey.pem) data/assets/ssl/key.pem
```

...then.

Do not forget to restart the containers.

**Comment by DJIronic** [comment]
Yes, it´s working now. Thanks 👍
