### ISSUE TITLE
Can't add alias domain when no relay domains exist.

### ISSUE THREAD

**Issue by fretb** [mailcow/mailcow-dockerized#2910]
Hi

I just configured an up-to-date mailcow-dockerized on an up-to-date Debian Buster system. I only added one domain, which works perfectly. However, when trying to add an alias domain for this domain, I get a warning that the main domain is in fact, a relay domain. Thus unable to add an alias domain to that domain.

I noticed, I think, a little bug in the validation of that functionality, [and referenced the code to this issue](https://github.com/mailcow/mailcow-dockerized/blob/1be5caf168a1b6d8e56f56047b88391b58a07872/data/web/inc/functions.mailbox.inc.php#L718).

When I locally adjust

```
WHERE `domain`= :target_domain AND `backupmx` = '1'");
```

to

```
WHERE `domain`= :target_domain AND `backupmx` = '0");
```

... adding the alias domain works, and when testing delivery everything works as expected.

Should this be changed? Or am I missing something?

**Comment by andryyy** [comment]
Thank you!! It is fixed.
