### ISSUE TITLE
Name does not resolve

### ISSUE THREAD

**Issue by aixtreme84** [mailcow/mailcow-dockerized#2915]
Hello,

Since the last update I get occasionally - but not always - the error message that a name can not be resolved:

e.g.:

0 - php_network_getaddresses: getaddrinfo failed: name does not resolve

Any idea?

**Comment by DatAres37** [comment]
Use the issue template please. You're not even mentioning where the error occurs.

**Comment by patschi** [comment]
Create a new issue following the template with attached logs please. Closed as not used the issue template.
