### ISSUE TITLE
Force Password Update breaks SOGo login

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#2917]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
When I try forcing the user to change his password on the next SOGo login it breaks the login with the following error message:
`Unhandled error response`
When I uncheck the box and save the changes the login on the webmail client is possible again.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
1. Go to https://mail.domain.de/edit/mailbox/user%40domain.de / Edit the user
2. Check the Box 'Force password update at next login'
3. Save the Changes

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.

**System information**
Found this in the logs from SOGo:
```
sogod[70:70] EXCEPTION: <NSException: 0x5606b0f138b0> NAME:NSRangeException REASON:Range location + length too great INFO:(null)
```

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Proxmox |
| Server/VM specifications (Memory, CPU Cores) | 8 cores, 30GB memory |
| Docker Version (`docker version`) | 19.03.1 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |

**Comment by andryyy** [comment]
The user needs to login to mailcow UI, to reset their password. :-) won't work on SOGo.

**Comment by mkapra** [comment]
@andryyy 
Ah sure sorry.
But why is sogo failing with that?

**Comment by andryyy** [comment]
Not too sure. The resulting query is probably garbage for SOGo. I can try to check this.

**Comment by andryyy** [comment]
Best I can do is set a valid but useless SSHA256 hash as pseudo password. It was "invalid" before.
Now it returns "password invalid". Not pushed yet, but I'll close this issue.
