### ISSUE TITLE
Name does not resolve

### ISSUE THREAD

**Issue by aixtreme84** [mailcow/mailcow-dockerized#2918]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Since the last update I get occasionally - but not always - the error message that a name can not be resolved:

e.g.:

> Connection to Redis failed.
> 
> The following error was reported:
> 
> 0 - php_network_getaddresses: getaddrinfo failed: name does not resolve

After pressing F5 the site works again

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

To reproduce the bug, i login as admin and go to "E-Mail-Setup".
If the Site "E-Mail-Setup" will load, i t ll try it a second  or third time to reproduce the bug.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen,  etc) | I DONT KNOW |
| Server/VM specifications (Memory, CPU Cores) | 8GB RAM, 4 Core |
| Docker Version (`docker version`) | Docker version 19.03.1, build 74b1e89 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | no custom solution |

Further notes:
no changes to code

**Comment by andryyy** [comment]
I think your redis-mailcow container is flapping, can you please post logs?

**Comment by aixtreme84** [comment]
Thanks for quick reply

**Starting**

redis-mailcow_1      | 1:C 05 Sep 2019 16:59:26.604 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-mailcow_1      | 1:C 05 Sep 2019 16:59:26.604 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis-mailcow_1      | 1:C 05 Sep 2019 16:59:26.604 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-mailcow_1      | 1:M 05 Sep 2019 16:59:26.606 * Running mode=standalone, port=6379.
redis-mailcow_1      | 1:M 05 Sep 2019 16:59:26.606 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-mailcow_1      | 1:M 05 Sep 2019 16:59:26.606 # Server initialized
redis-mailcow_1      | 1:M 05 Sep 2019 16:59:26.606 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.


**from then** 

redis-mailcow_1      | 1:M 06 Sep 2019 20:17:01.804 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:17:01.809 * Background saving started by pid 200
redis-mailcow_1      | 200:C 06 Sep 2019 20:17:01.926 * DB saved on disk
redis-mailcow_1      | 200:C 06 Sep 2019 20:17:01.928 * RDB: 2 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:17:02.021 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:22:35.294 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:22:35.299 * Background saving started by pid 201
redis-mailcow_1      | 201:C 06 Sep 2019 20:22:35.360 * DB saved on disk
redis-mailcow_1      | 201:C 06 Sep 2019 20:22:35.362 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:22:35.399 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:27:36.057 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:27:36.060 * Background saving started by pid 202
redis-mailcow_1      | 202:C 06 Sep 2019 20:27:36.116 * DB saved on disk
redis-mailcow_1      | 202:C 06 Sep 2019 20:27:36.117 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:27:36.161 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:32:37.071 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:32:37.075 * Background saving started by pid 203
redis-mailcow_1      | 203:C 06 Sep 2019 20:32:37.142 * DB saved on disk
redis-mailcow_1      | 203:C 06 Sep 2019 20:32:37.143 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:32:37.176 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:39:01.265 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:39:01.268 * Background saving started by pid 204
redis-mailcow_1      | 204:C 06 Sep 2019 20:39:01.333 * DB saved on disk
redis-mailcow_1      | 204:C 06 Sep 2019 20:39:01.334 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:39:01.369 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:44:02.006 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:44:02.013 * Background saving started by pid 205
redis-mailcow_1      | 205:C 06 Sep 2019 20:44:02.132 * DB saved on disk
redis-mailcow_1      | 205:C 06 Sep 2019 20:44:02.133 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:44:02.219 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:50:57.271 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:50:57.277 * Background saving started by pid 206
redis-mailcow_1      | 206:C 06 Sep 2019 20:50:57.344 * DB saved on disk
redis-mailcow_1      | 206:C 06 Sep 2019 20:50:57.345 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:50:57.378 * Background saving terminated with success
redis-mailcow_1      | 1:M 06 Sep 2019 20:55:58.050 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Sep 2019 20:55:58.057 * Background saving started by pid 207
redis-mailcow_1      | 207:C 06 Sep 2019 20:55:58.120 * DB saved on disk
redis-mailcow_1      | 207:C 06 Sep 2019 20:55:58.121 * RDB: 0 MB of memory used by copy-on-write
redis-mailcow_1      | 1:M 06 Sep 2019 20:55:58.158 * Background saving terminated with success

**Comment by aixtreme84** [comment]
Same after fresh installation

**Comment by aixtreme84** [comment]
next to 'name does not resolve' there is this error

> Connection to dockerapi container failed.
> 
> The following error was reported:
> 111 - Connection refused

**Comment by andryyy** [comment]
Can you dump the dockerapi-mailcow logs or show the kernel version with uname -a?

**Comment by aixtreme84** [comment]
Kernel:  5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


Syslog looks strange:


Sep  6 23:38:55 servername kernel: [  573.909825] br-mailcow: port 9(vethbbcdca7) entered disabled state
Sep  6 23:38:55 servername kernel: [  573.916899] device vethbbcdca7 left promiscuous mode
Sep  6 23:38:55 servername kernel: [  573.916906] br-mailcow: port 9(vethbbcdca7) entered disabled state
Sep  6 23:38:55 servername kernel: [  573.983645] br-mailcow: port 9(veth67923ca) entered blocking state
Sep  6 23:38:55 servername kernel: [  573.983648] br-mailcow: port 9(veth67923ca) entered disabled state
Sep  6 23:38:55 servername kernel: [  573.983794] device veth67923ca entered promiscuous mode
Sep  6 23:38:55 servername networkd-dispatcher[851]: WARNING:Unknown index 62 seen, reloading interface list
Sep  6 23:38:55 servername systemd-udevd[14588]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep  6 23:38:55 servername systemd-udevd[14587]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep  6 23:38:55 servername systemd-udevd[14587]: Could not generate persistent MAC address for veth645bd6f: No such file or directory
Sep  6 23:38:55 servername systemd-udevd[14588]: Could not generate persistent MAC address for veth67923ca: No such file or directory
Sep  6 23:38:55 servername kernel: [  573.985018] br-mailcow: port 9(veth67923ca) entered blocking state
Sep  6 23:38:55 servername kernel: [  573.985020] br-mailcow: port 9(veth67923ca) entered forwarding state
Sep  6 23:38:55 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:38:55 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:38:55 servername containerd[2389]: time="2019-09-06T23:38:55.599695113+02:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/f9a494729893cdf66332eff02d4d981ff7264c6a87c85e002ad893ba8c160afd/shim.sock" debug=false pid=14595
Sep  6 23:38:55 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:38:56 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:38:56 servername kernel: [  574.521064] eth0: renamed from veth645bd6f
Sep  6 23:38:56 servername systemd-networkd[712]: veth67923ca: Gained carrier
Sep  6 23:38:56 servername kernel: [  574.596684] IPv6: ADDRCONF(NETDEV_CHANGE): veth67923ca: link becomes ready
Sep  6 23:38:56 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:38:57 servername systemd-networkd[712]: veth67923ca: Gained IPv6LL
Sep  6 23:38:57 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:38:57 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:43:18 servername containerd[2389]: time="2019-09-06T23:43:18.902325762+02:00" level=info msg="shim reaped" id=f9a494729893cdf66332eff02d4d981ff7264c6a87c85e002ad893ba8c160afd
Sep  6 23:43:18 servername dockerd[2538]: time="2019-09-06T23:43:18.916773246+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Sep  6 23:43:18 servername systemd-networkd[712]: veth67923ca: Lost carrier
Sep  6 23:43:18 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:43:18 servername kernel: [  837.371745] br-mailcow: port 9(veth67923ca) entered disabled state
Sep  6 23:43:18 servername kernel: [  837.372014] veth645bd6f: renamed from eth0
Sep  6 23:43:18 servername systemd-udevd[15263]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep  6 23:43:18 servername networkd-dispatcher[851]: WARNING:Unknown index 61 seen, reloading interface list
Sep  6 23:43:19 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:43:19 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:43:19 servername kernel: [  837.570550] br-mailcow: port 9(veth67923ca) entered disabled state
Sep  6 23:43:19 servername kernel: [  837.575670] device veth67923ca left promiscuous mode
Sep  6 23:43:19 servername kernel: [  837.575676] br-mailcow: port 9(veth67923ca) entered disabled state
Sep  6 23:43:19 servername networkd-dispatcher[851]: WARNING:Unknown index 64 seen, reloading interface list
Sep  6 23:43:19 servername kernel: [  837.640028] br-mailcow: port 9(veth8be7074) entered blocking state
Sep  6 23:43:19 servername kernel: [  837.640031] br-mailcow: port 9(veth8be7074) entered disabled state
Sep  6 23:43:19 servername kernel: [  837.640185] device veth8be7074 entered promiscuous mode
Sep  6 23:43:19 servername kernel: [  837.640349] br-mailcow: port 9(veth8be7074) entered blocking state
Sep  6 23:43:19 servername kernel: [  837.640351] br-mailcow: port 9(veth8be7074) entered forwarding state
Sep  6 23:43:19 servername systemd-udevd[15285]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep  6 23:43:19 servername systemd-udevd[15285]: Could not generate persistent MAC address for veth9b1fe8b: No such file or directory
Sep  6 23:43:19 servername systemd-udevd[15286]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Sep  6 23:43:19 servername systemd-udevd[15286]: Could not generate persistent MAC address for veth8be7074: No such file or directory
Sep  6 23:43:19 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:43:19 servername containerd[2389]: time="2019-09-06T23:43:19.243532449+02:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/f9a494729893cdf66332eff02d4d981ff7264c6a87c85e002ad893ba8c160afd/shim.sock" debug=false pid=15293
Sep  6 23:43:19 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.
Sep  6 23:43:19 servername kernel: [  838.035127] eth0: renamed from veth9b1fe8b
Sep  6 23:43:19 servername systemd-networkd[712]: veth8be7074: Gained carrier
Sep  6 23:43:19 servername kernel: [  838.111605] IPv6: ADDRCONF(NETDEV_CHANGE): veth8be7074: link becomes ready
Sep  6 23:43:19 servername systemd-timesyncd[699]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
Sep  6 23:43:20 servername systemd-networkd[712]: veth8be7074: Gained IPv6LL
Sep  6 23:43:20 servername systemd-timesyncd[699]: Network configuration changed, trying to establish connection.

**Comment by timo-reymann** [comment]
Got the exact same behaviour.

Same happens with the Lets Encrypt container:
`acme-mailcow_1       | Could not connect to Redis at redis:6379: Name does not resolve`

I also tried executing
 `docker-compose exec php-fpm-mailcow php -r "echo gethostbyname('dockerapi');"`
It looks like most of the time the ip is resolved correctly, but sometimes it just wont resolve ...

**Comment by continga** [comment]
I can confirm this, this happens e.g. approximately every 20th till 30th request when trying to open the front page of the Mailcow UI via https (the login formular).

Error message is either: 
```
Connection to Redis failed.

The following error was reported:
php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

or:
```
Connection to dockerapi container failed.

The following error was reported:
111 - Connection refused
```

I left `docker-compose logs -f` running when doing those 20-30 requests, until the error message appeared, but the logs do not show anything suspicious, the dockerapi-mailcow container is not logging anything, even that "error page" is giving a 200 http status code.

I am on kernel `5.2.11-arch1-1-ARCH` and on mailcow commit 229b18c93fbb4332adf1cc4593aba16a29cdac32

**Comment by andryyy** [comment]
I have not yet seen this happening. @aixtreme84 Your logs look strange. Is any container flapping up/down? What about unbound-mailcow logs? When exactly were these lines written to syslog? Just after you started mailcow?

Cannot check this, as it is not happening on any installation of mine. :/

**Comment by timo-reymann** [comment]
@andryyy It seems this is only the case on newly installed systems ... i got 2 instances, one is a bit "older" and works fine without the issue. 
A new one has the same behavior, adding the dns keys for the php-fpm container again fixed the problem. Maybe it got lost with the quick fix #2683  for the kernel panic?

**Comment by aixtreme84** [comment]
@timo: can you Share your Solution?
How to add dns keys for the php-fpm Container ?

**Comment by timo-reymann** [comment]
@aixtreme84 I placed it in the docker-compose.yml under php-fpm-mailcow, you can simply search for that keyword, than place the following under that key:
```
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
```
Than a simple `docker-compose up -d` will apply the new dns server for php-fpm container.

**Comment by andryyy** [comment]
Can you try and verify it works for you, @aixtreme84 ?

**Comment by aixtreme84** [comment]
Since I made the changes which timo described, I have no problems like "Name does not resolve".

**Comment by nils-kt** [comment]
Hi, I have the same problem with Ubuntu 19.04 (GNU/Linux 5.0.21-1-pve x86_64).  
Unfortunately, the solution by @timo-reymann did not help.

**Comment by Treverr** [comment]
I also am having this issue, DNS line is in my docker compose and did not resolve the issue.
