### ISSUE TITLE
Backup script - file permissions

### ISSUE THREAD

**Issue by FingerlessGlov3s** [mailcow/mailcow-dockerized#2919]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

My issue is when you do a Postcow backup, the file permissions used for the backup are 755, which allows anyone on the system to view the backup (Includes the encryption keys for the encrypted at rest mail).

In the script the main backup folder is create with 755 and then backup folders are also created with 755, the backup files, file permissions are 644.

Permissions should be 700 (or 750) for folders and 600 (or 640) for files, so only root:root can access these backups.

*** root or the user who runs the backup

**Reproduction of said bug**: yes, its a script issue.

```
root@Mailcow:/opt/backup# ls -la
total 16
drwxr-xr-x 4 root root 4096 Sep  6 07:24 .
drwxr-xr-x 5 root root 4096 Sep  6 22:58 ..
drwxr-xr-x 2 root root 4096 Sep  5 12:53 mailcow-2019-09-05-12-51-01
drwxr-xr-x 2 root root 4096 Sep  5 18:52 mailcow-2019-09-05-18-51-01
```

```
root@Mailcow:/opt/backup# ls -la mailcow-2019-09-05-12-51-01/
total 874284
drwxr-xr-x 2 root root      4096 Sep  5 12:53 .
drwxr-xr-x 4 root root      4096 Sep  6 07:24 ..
-rw-r--r-- 1 root root       487 Sep  5 12:52 backup_crypt.tar.gz
-rw-r--r-- 1 root root    792362 Sep  5 12:53 backup_mysql.gz
-rw-r--r-- 1 root root       774 Sep  5 12:53 backup_postfix.tar.gz
-rw-r--r-- 1 root root   1135135 Sep  5 12:52 backup_redis.tar.gz
-rw-r--r-- 1 root root   1968879 Sep  5 12:52 backup_rspamd.tar.gz
-rw-r--r-- 1 root root 891333103 Sep  5 12:52 backup_vmail.tar.gz
-rw------- 1 root root      4261 Sep  5 12:51 mailcow.conf
```
Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3|
| Is Apparmor, SELinux or similar active? | shall check later |
| Virtualization technlogy (KVM, VMware, Xen, etc) | I believe Scaleway use VMware |
| Server/VM specifications (Memory, CPU Cores) | 3 cores, 4GB Ram |
| Docker Version (`docker version`) | 19.03 |
| Docker-Compose Version (`docker-compose version`) | v1.24.1 |
| Reverse proxy (custom solution) | NOPE |

**Comment by andryyy** [comment]
Just set the permissions yourself, if you need to.

Sometimes you need to do things yourself. If you use a multi-user system as a backup destination, you can always copy the script and modify it for your needs. I don't even know why we chmod mailcow.conf. You usually backup to a sane remote location anyway. Samba, NFS, whatever. All may or may not care about your set permissions.

This is a helper script I wrote once as a !helper! - Use it or don't use it. Modify it, delete it, do whatever your feel with it.

**Comment by FingerlessGlov3s** [comment]
I already set 700 on the backup folder, when I noticed this, and disabled the permissions check. backups up perfectly fine. 😊

You can leave it if you want, but it should be hardened to start with and if you need to open up the permissions you do so.

I'm going to close this issue, as it's really up to you. I'm just looking at it from a security point of view where it should be secure to start with. 🙂

**Comment by clauso** [comment]
I just ran into this issue as well. I created a backup dir with permissions set to 700 and got the error message. It was helpful to know that that error is nonsens. The script works very fine once line 44-48 are commented, that check is not needed. So I would suggest updating the script to not push users to make dirs world-writable if not needed.

**Comment by FingerlessGlov3s** [comment]
Indeed :-)
