### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by eddiejibson** [mailcow/mailcow-dockerized#2920]
Hi,

Just wondering where API documentation actually is? I haven't seen it around but can see clearly you can generate credentials. I know if this is fully implemented I'll definitely contribute some money because of how much it'd help me.

Thanks.

**Comment by andryyy** [comment]
Hi, search for @feldsam in the issues, he already documented a lot and even fixed a few API errors.

**Comment by feldsam** [comment]
Hi, API docs are here https://mailcow.docs.apiary.io, I will be happy if you contribute to docs.

**Comment by MAGICCC** [comment]
Totally need to add it to the docs as reference link!
