### ISSUE TITLE
Top-level tagged mail subfolders

### ISSUE THREAD

**Issue by mamash** [mailcow/mailcow-dockerized#2921]
**Is your feature request related to a problem? Please describe.**

Apple Mail (on both macOS and iOS) doesn't support INBOX subfolders. If created elsewhere, they don't show up and can't be accessed. Any tagged mail filed in a subfolder is as good as gone.

**Describe the solution you'd like**

INBOX subfolders annoy me immensely, but I can see how someone else likes them. I'd like the behaviour to be at least configurable to mimic Dovecot's `lmtp_save_to_detail_mailbox=yes`, so that such subfolder can be created and used on the top level too.

**Comment by andryyy** [comment]
It is supported and working fine. Perhaps I'm not understanding the issue correctly. Can you explain? :)

**Comment by mamash** [comment]
Ah. Yes, it does indeed.

Apparently both mail clients got confused by the fact there was already a folder of the same name on the top level (created by Dovecot in my pre-mailcow times).

I just never understood that someone would want INBOX subfolders and got misled by a bunch of early google entries.

Closing.

**Comment by mamash** [comment]
Actually, I spoke too soon. Apple Mail on macOS will show the INBOX subfolders in the folder tree, but will refuse to fetch any mail from them. They simply show up empty. Mail on iOS does work in that regard, but I'm running a public beta of iOS on my iPhone, which could be related.

Anyway, I realised that I need subfolder tagged mail handling for BCC maps too, which bypasses the mailcow rspamd/sieve handling, so I had to put lmtp_save_to_detail_mailbox in extra.conf to let Dovecot deal with this instead.

**Comment by andryyy** [comment]
You should check your Maildirs then. Or Dovecot. It is absolutly normal to have subfolders under INBOX, this is not at all breaking iOS or macOS clients. Perhaps something broke, when you migrated? 

Subfolders under INBOX is **in no way** something, that was added in a new iOS version. It is totally common and nothing special.

I'm sure you will find your answer in dovecot-mailcow logs, when you try to open a subfolder on these clients.

**Comment by mamash** [comment]
> I'm sure you will find your answer in dovecot-mailcow logs, when you try to open a subfolder on these clients.

That's what I thought, but nope. Quit Mail, start tailing logs, start Mail, see normal connections being open by my client, but no sign of anything wrong. I even created a new folder in Thunderbird, but no luck in Mail.
