### ISSUE TITLE
Scarce api documentation 

### ISSUE THREAD

**Issue by jose123455587** [mailcow/mailcow-dockerized#2925]
Hey,
When I was reading [api documentation ](https://mailcow.docs.apiary.io/#) I noticed that there was no documentation regarding limiting outgoing email, tls enforce etc.
I would like to know how you will be able to submit these values via api.
Thank you again,
Jose

**Comment by andryyy** [comment]
You can easily track down these fields from the API logs in mailcow UI. :)

Add it to the docs, create a PR, when you found it, please. Share your new knowledge with our cow friends and keep this project alive.
