### ISSUE TITLE
TLSv1 support

### ISSUE THREAD

**Issue by georgygoshin** [mailcow/mailcow-dockerized#2926]
Hi

Would be great to have a possibility still to support v1 protocol because there is a lot of clients still use and will use W7 and switch to newer TLS on each client is little bit difficult...

**Comment by andryyy** [comment]
I plan to disable TLSv1 completely in 2020. Windows 7 is EOL then. But even with Windows 7, TLS 1.2 is possible.

https://www.greengeeks.com/tutorials/article/how-to-enable-tls-1-1-and-1-2-in-outlook-windows-7/

You can change ciphers and protocols here:

```
data/conf/postfix/main.cf (perhaps master.cf, too)
data/conf/nginx/site.conf
data/conf/dovecot/dovecot.conf
```

**Comment by georgygoshin** [comment]
I've placed into data/conf/nginx/site.conf

ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

but ssl checker shows only 1.3 and 1.2 are supported.

**Comment by andryyy** [comment]
fyi, he commented out the ciphers and it worked.
