### ISSUE TITLE
ACME cannot match hostname

### ISSUE THREAD

**Issue by nnlt** [mailcow/mailcow-dockerized#2932]
Unfortunately ACME fails to match the hostname to the IP

Error messages are:

`Cannot match your IP 104.xxx.46.xxx against hostname autoconfig.xxxxx-xxxxxxx.de (127.0.1.1)`
`Found A record for autoconfig.xxxxxxxx-xxxx.de: 127.0.1.1`

I already tried to change the nameservers in /etc/resolv.conf without success.

Any ideas?

**Comment by unclesamwk** [comment]
Please check your A-Record for autoconfig.xxxxx-xxxxxxx.de.
It musst be your public ip

**Comment by nnlt** [comment]
The records are correctly set for all domains. It worked fine for over a year. Now suddenly all A records are resolved to 127.0.0.1

**Comment by nnlt** [comment]
My problem is comparable to this issue: https://github.com/mailcow/mailcow-dockerized/issues/850
Expect, that if I do nslookup in the acme container it resolves every IP to 127.0.0.1.
