### ISSUE TITLE
Filter :matches does not work for envelope

### ISSUE THREAD

**Issue by piegamesde** [mailcow/mailcow-dockerized#2933]
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**

In a Sieve filter, matching the content of an envelope does not yield the expected results. My minimal filter example is:

```
require ["fileinto", "variables", "mailbox", "envelope"];
if envelope :localpart :matches "to" "*" {
  if mailboxexists "INBOX/${0}" {
    fileinto "INBOX/${0}";
  } else {
    fileinto :create "INBOX/${0}";
  }
}
```

If I send a mail to `foo@domain.com`, it will land at `INBOX/foo`. If I send a mail to `foo+tag@domain.com`, it will land at `INBOX/foo+tag`. But if I send it to `foo-bar+tag@domain.com`, it will simply be put into `INBOX/foo`. In comparison, the line `if address :localpart :matches "to" "*"` will move it into the correct folder.

----

What I try to do in the long run is to match against the tag in an email address to automatically put it into that folder. (The built-in functionality to do this does not work with catchall.) It worked well with `address` instead of `envelope`, but this would not work for mails with a custom "to" field (e.g. GitHub notification mails).

**Reproduction of said bug**

1. Add this filter to the account
2. Add a catchall to that account
3. Send mails to different addresses on that domain and see if they land in a folder with the same name as "to". Test addresses containing "+", "-" and "." characters.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

OS: Arch Linux
Mail client: Evolution

**Comment by piegamesde** [comment]
Okay, I found out that the catchall is causing this behavior. It will redirect all emails to the specified account and thus add another entry to the envelope. I resolved this by disabling the catchall.

**Comment by andryyy** [comment]
Yep, that's expected with catch all. You can also match the To field here.
