### ISSUE TITLE
Sender-dependent transports not working?

### ISSUE THREAD

**Issue by YannKr** [mailcow/mailcow-dockerized#2937]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Hello,

I have a mail server that receives multiple ISP emails into one mailbox, on a custom domain. I have tried the Sender-dependent transports setup under Routing tab (the test works fine) and added it to the domain. However, when sending from my ISP email via mailcow, it seems to ignore the Sender-dependent transports setting and just goes directly.

I'm unsure if this is expected or not. I'm also wondering if it's possible to have multiple Sender-dependent transports per domain.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Have email user@isp.com
2. Have mailcow host custom.com
3. Create mailbox under custom.com, i.e. user@custom.com
4. Disable sender check for user@custom.com
5. Setup Sender-dependent transports under "Routing" with user@isp.com credentials
6. Add the created Sender-dependent transport to domain custom.com
7. Send email from user@isp.com using mailcow
8. Check source and clearly see that isp.com mail servers haven't been used

Note that, I used the WebUI tester and it works fine setting user@isp.com as From. I also checked logs and it doesn't mention anything about isp.com except that the From email is user@isp.com (like any normal email being processed).

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | VM from cloud provider |
| Server/VM specifications (Memory, CPU Cores) | 2 core, 2GB RAM |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | No |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Using it in multiple cows without a problem. Is the map active?

Screenshots of the config and logs may help.

**Comment by YannKr** [comment]
@andryyy yes the map is active and also marked as "in use by" custom.com (following the initial example).

Happy to take screenshots etc., which pages would be helpful?
