### ISSUE TITLE
Sieve filter not working with alias in bcc

### ISSUE THREAD

**Issue by hobbsAU** [mailcow/mailcow-dockerized#2945]
**Description of the bug**: 

My issue about Sieve filtering on a **mailbox alias in bcc field**. 

For example take the following setup:
alias@example.com --> mailbox@example.com

A typical Sieve filter on the To: address will not trigger as the recipient is not listed here (they are BCC'd) and anything could be in the To: field. A Sieve filter on the Delivered-To message header will not work either as this contains the mailbox recipient mailbox@example.com not the alias@example.com address.

The intended recipient (alias@example.com) can be seen in the postfix logs as orig_to=\<alias@example.com\> address however this field does not seem to flow through to any fields in the final email message header. 

A Google search shows some references to "X-Delivered-To" and "X-Original-To" message headers however neither of these headers are present in the message. As suggested here [http://www.postfix.org/MAILDROP_README.html](http://www.postfix.org/MAILDROP_README.html), I've tried adding the "O" to the pipe options in the maildrop transport in master.cf however this did not work, for some reason the header was still not added to the final message.

I'm thinking if these headers were available this would be a simple way to implement a Sieve filter..

``` 
if header :matches ["X-Original-To"] ["alias@example.com"] 
{
    fileinto :create "Personal";
}
```
OR
```
require ["envelope", "fileinto", "mailbox"];
if envelope "To" "alias@example.com"
{
    fileinto :create "Personal";
}
```
<BR><BR>

**Is there a better way to implement this Sieve filtering? Can I add the headers somehow?**
<BR><BR><BR>
 
**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Create a mailbox alias
2. Create a Sieve filter to file all emails To: the alias address
3. Send an email bcc'ing the alias address
4. Email is delivered to the mailbox INBOX as opposed to the filing folder in the Sieve filter.

**System information**
| Question | Answer |
| --- | --- |
| My operating system | Debian 9 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 4 Cores |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | N/A |

**Comment by andryyy** [comment]
Hi, you _should_ not set the BCC rcpt as X header. I mean, if you don't care or no privacy policy applies, you can always do so. :)

Iirc you are German, right? There is something you can do to add it for only _some_ transports, but remove it for smtp and lmtp: https://www.debinux.de/2015/03/sichere-e-mail-archivierung-mit-piler/

**Comment by hobbsAU** [comment]
Hi andryyy

Good point, you shouldn't expose the BCC as X header. However would this matter if you set the maildrop_destination_recipient_limit = 1 as suggested in the Postfix Maildrop link above?

I looked at the Piler link and you seem to be injecting X-Envelope-To what looks like a similar way to achieve the same thing albeit for a different purpose.

BCC is not the only use case. I'm just trying to comprehensively filter _inbound email to an alias_.

For example, the alias does not always need to be BCC'd - i.e. the To: or Cc: field may be set to any address and the alias is only used in the SMTP RCPT TO. Unfortunately in this case the alias is still dropped from all header fields and only the mailbox address remains by the time it hits the Sieve filter.
