### ISSUE TITLE
hook during receive email

### ISSUE THREAD

**Issue by mhf-ir** [mailcow/mailcow-dockerized#2946]
1. Can set when email recive for special user:
`user@domain.tld` run `hook.php` or `hook.python` with mail data
2. and for domain `*doman.tld`
`user@domain.tld` run `domain-hook.python` or `domain-hook.python` with mail data
3. Even generally hooks for all mails:
  `all-hooks.php` or   `all-hooks.python`

**Describe the solution you'd like**
Special path to insert hooks any sample will be good for that.

**Additional context**
https://thecodingmachine.io/triggering-a-php-script-when-your-postfix-server-receives-a-mail
http://www.postfix.org/FILTER_README.html

**Comment by Braintelligence** [comment]
I wonder if one could actually achieve IMAP push by combining manual IMAP sync and webhooks. :D

**Comment by andryyy** [comment]
We can actually do that with Rspamds meta_exporter. Or Dovecots LUA API.

**Comment by Tokukarin** [comment]
Sorry for bringin this up again but this has not really been a solution and more a wacky workaround. 

Is there something concrete that we can use that triggeres a webhook on an incoming email that triggers a script?

**Comment by bb** [comment]
If you’re looking for Rails ActionMailbox, check out https://github.com/bb/action-mailbox-docker-relay (disclosure: self-plug). 

If you need something else, you could fork it and put your hook-calling logik [here (replacing the selected lines)](https://github.com/bb/action-mailbox-docker-relay/blob/1052bc55a4d7f23bc29d0485f5d113030a718d5d/lib/action_mailbox_relay.rb#L26-L36).
