### ISSUE TITLE
Cannot start service solr-mailcow - address already in use

### ISSUE THREAD

**Issue by phillipplum** [mailcow/mailcow-dockerized#2951]
**Prior to placing the issue, please check following:** 
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: 

After updating to the current master, i get this error messagen:
`ERROR: for solr-mailcow  Cannot start service solr-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_solr-mailcow_1 (141d51450ea200f9f2842791d2ce5b82b8b8925c4a47a07be6f560a3ade60bb8): Error starting userland proxy: listen tcp 127.0.0.1:8983: bind: address already in use`

**Reproduction of said bug**: 

1. Run `./update.sh`
2. Try to fix with:
3. `docker-compose down`
4. `docker-compose up -d`

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian GNU/Linux 8 (jessie) |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Xen |
| Server/VM specifications (Memory, CPU Cores) | 10GB Memory, 1 CPU |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | NO |

**Comment by andryyy** [comment]
Try update.sh again :)

A solr instance seems to be running on your server. I added a default binding to 127.0.0.1:8983 previously to access solr UI. Changed it to 18389 now.

**Comment by phillipplum** [comment]
Thank you for the fast update! Now everything is working perfect.
Have a nice day :)
