### ISSUE TITLE
relay to aspmx.l.google.com

### ISSUE THREAD

**Issue by vinacc** [mailcow/mailcow-dockerized#2953]
I have a problem with the delivery of my mail to servers managed by aspmx.l.google.com.

From Postfix Log the message is sent, but on the other side it is not received. This happens only if the relay is made to aspmx.l.google.com.

This is the log:

> BC7F0205C4: client=hostxxx-xxx-dynamic.xxx-xxx-r.retail.telecomitalia.it[xxx.xxx.xxx.xxx], sasl_method=PLAIN, sasl_username=myusername@mydomain.it
> 
> BC7F0205C4: message-id=<81569D16-D0A4-4491-9774-B41658DC1556@mydomain.it>
> 
> BC7F0205C4: from=<myusername@mydomain.it>, size=812, nrcpt=1 (queue active)
> 
> BC7F0205C4: to=<support@curve.app>, relay=aspmx.l.google.com[173.194.76.27]:25, delay=8.3, delays=0.41/0.04/7.5/0.35, dsn=2.0.0, status=sent (250 2.0.0 OK 1568808780 a17si1603973wmb.98 - gsmtp)
> 
> BC7F0205C4: removed

How can I correct it?

**Comment by andryyy** [comment]
That's a working mail flow. "removed" means removed from queue.

**Comment by vinacc** [comment]
In fact it seems that everything works correctly from my side, but the destination server does not receive the email. This happens with all the domains managed by aspmx.l.google.com.

**Comment by andryyy** [comment]
Perhaps in Junk?

**Comment by vinacc** [comment]
I have no way to verify unfortunately. It seems strange to me that delivery problems occur only with this server.

**Comment by andryyy** [comment]
It is fine on your side. It is queued by Gmail.

You could send me a mail to apeters87@gmail.com

**Comment by vinacc** [comment]
I wrote you ... let me know.

**Comment by andryyy** [comment]
It is moved to Junk

AS16276

You are sending mail from AS16276 (OVH), that's not a good idea. You should not use OVH for mailing.

**Comment by vinacc** [comment]
I have always relied on this service ...
https://www.mail-tester.com/test-m30lb

**Comment by patschi** [comment]
But most likely Google has a different (and way more complex) setup and doesn't use the same as mail-tester. mail-tester.com should only be taken as suggestions/recommendations.

**Comment by andryyy** [comment]
They also only check DKIM, SPF etc. - all that is working fine, your mail is fully valid. But OVH has a very high spam rate, so bigger providers rate them poorly.

**Comment by vinacc** [comment]
Thank you all. I will evaluate other ISPs to migrate my mail server

**Comment by marrco** [comment]
relay mail to those domains via Amazon SES or an IP with better reputation

**Comment by andryyy** [comment]
Very easy to migrate with a dockerized cow. :)

**Comment by chessw** [comment]
> relay mail to those domains via Amazon SES or an IP with better reputation

I use Amazon SES. I find that delivery is very good and so far (after almost a year) I have not had any cost, but my users are not heavy outbound email users. If it was me that is the way I'd go.

**Comment by vinacc** [comment]
Hello.  I too have no big claims.  my mail server handles less than 1000 emails a month.  in that sense you have not had costs.

Inviato da iPhone

> Il giorno 19 set 2019, alle ore 22:14, chessw <notifications@github.com> ha scritto:
> 
> I use Amazon SES. I find that delivery is very good and so far (after almost a year) I have not had any cost, but my users are not heavy outbound email users. If it was me that is the way I'd go.

**Comment by discofris** [comment]
> Thank you all. I will evaluate other ISPs to migrate my mail server

Very good experience with linode.com & hetzner.com

**Comment by vinacc** [comment]
I have set up Amazon SES with a limit of 50,000 submissions per day (free) and I have solved the problem of Google spam. Thank you all for your help.
