### ISSUE TITLE
Cannot match your IP NO_IPV6_LINK against hostname

### ISSUE THREAD

**Issue by 80kk** [mailcow/mailcow-dockerized#2955]
I have configured reverse DNS for IPv4 and IPv6. IPv4 works fine, but if I set AAAA and then PTR for the domain, then Let's Encrypt (acme) has problem with it. The error message is:

`root@mail:/opt/mailcow-dockerized# docker-compose logs --tail=200 -f acme-mailcow`
`WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.`
`Attaching to mailcowdockerized_acme-mailcow_1`
`acme-mailcow_1       | Fri Sep 20 00:15:04 CEST 2019 - Waiting for Docker API...OK`
`acme-mailcow_1       | Fri Sep 20 00:15:04 CEST 2019 - Waiting for database... Uptime: 14` 
`Threads: 28  Questions: 264  Slow queries: 0  Opens: 37  Flush tables: 1  Open tables: 29  Queries per second avg: 18.857`
`acme-mailcow_1       | OK`
`acme-mailcow_1       | Fri Sep 20 00:15:04 CEST 2019 - Waiting for Nginx... OK`
`acme-mailcow_1       | Fri Sep 20 00:15:05 CEST 2019 - Waiting for domain table... OK`
`acme-mailcow_1       | Fri Sep 20 00:15:05 CEST 2019 - Initializing, please wait... `
`acme-mailcow_1       | Fri Sep 20 00:15:05 CEST 2019 - Using existing domain key /var/lib/acme/acme/key.pem`
`acme-mailcow_1       | Fri Sep 20 00:15:05 CEST 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem`
`acme-mailcow_1       | Fri Sep 20 00:15:05 CEST 2019 - Detecting IP addresses... OK`
`acme-mailcow_1       | Validated CAA for parent domain domain.net`
`acme-mailcow_1       | Fri Sep 20 00:15:41 CEST 2019 - Found A record for autoconfig.domain.net: 1.2.3.4`
`acme-mailcow_1       | Fri Sep 20 00:15:41 CEST 2019 - Confirmed A record 1.2.3.4, adding SAN`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Found A record for autodiscover.domain.net: 1.2.3.4`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Confirmed A record 1.2.3.4, adding SAN`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Found A record for autodiscover.domain.net: 1.2.3.4`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Confirmed A record 1.2.3.4, adding SAN`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Found AAAA record for autoconfig.domain.net: 2001:123:45:12e::4 - skipping A record check`
`acme-mailcow_1       | Fri Sep 20 00:15:42 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname autoconfig.domain.net (2001:...4)`
`acme-mailcow_1       | Fri Sep 20 00:15:43 CEST 2019 - Found AAAA record for mail.domain.net: 2001:123:45:12e::4 - skipping A record check`
`acme-mailcow_1       | Fri Sep 20 00:15:43 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname mail.domain.net (DNS returned 2001:...4)`
`acme-mailcow_1       | Certificate will not expire`
`acme-mailcow_1       | Fri Sep 20 00:15:44 CEST 2019 - Certificate validation done, neither changed nor due for renewal, sleeping for another day.`
`
where any DNS server in the internet can see PTR properly for both A and AAAA records.

`# curl -6v ip6.mailcow.email
* Rebuilt URL to: ip6.mailcow.email/
*   Trying 2a00:f820:417::4...
* TCP_NODELAY set
* Connected to ip6.mailcow.email (2a00:f820:417::4) port 80 (#0)
> GET / HTTP/1.1
> Host: ip6.mailcow.email
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 19 Sep 2019 22:33:12 GMT
< Server: Apache
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host ip6.mailcow.email left intact
2001:123:45:678::4`

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS  |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 4CPU |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | MAilcow Nginx |

I went through that:
https://github.com/mailcow/mailcow-dockerized/issues/1029#issuecomment-385514013
https://github.com/mailcow/mailcow-dockerized/issues/1628
https://github.com/mailcow/mailcow-dockerized/issues/489
https://github.com/mailcow/mailcow-dockerized/issues/325
https://github.com/mailcow/mailcow-dockerized/issues/1737

with no luck

ifconfig output:
`br-mailcow: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.1.1  netmask 255.255.255.0  broadcast 172.22.1.255
        inet6 fe80::42:91ff:fedb:9ae8  prefixlen 64  scopeid 0x20<link>
        inet6 fd4d:6169:6c63:6f77::1  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::1  prefixlen 64  scopeid 0x20<link>
        ether 02:42:91:db:9a:e8  txqueuelen 0  (Ethernet)
        RX packets 33260  bytes 5058881 (5.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 39533  bytes 190695509 (190.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:76:e8:da:ef  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens18: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        inet 192.168.101.5  netmask 255.255.255.0  broadcast 192.168.101.255
        inet6 2001:123:45:678::4  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::b00f:2bff:fe0e:5759  prefixlen 64  scopeid 0x20<link>
        ether b2:0f:2b:0e:57:59  txqueuelen 2500  (Ethernet)
        RX packets 347396  bytes 1159431493 (1.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 245529  bytes 33915664 (33.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 14  bytes 414 (414.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 414 (414.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth6345984: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::9038:3dff:fe36:6bf5  prefixlen 64  scopeid 0x20<link>
        ether 92:38:3d:36:6b:f5  txqueuelen 0  (Ethernet)
        RX packets 13  bytes 1086 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 347  bytes 28338 (28.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth7333803: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::7c20:70ff:fe8c:cb1a  prefixlen 64  scopeid 0x20<link>
        ether 7e:20:70:8c:cb:1a  txqueuelen 0  (Ethernet)
        RX packets 16505  bytes 1101183 (1.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25455  bytes 3719204 (3.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth00cc9d3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c095:48ff:fe9f:a947  prefixlen 64  scopeid 0x20<link>
        ether c2:95:48:9f:a9:47  txqueuelen 0  (Ethernet)
        RX packets 30216  bytes 1690165 (1.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 37124  bytes 189854170 (189.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth028dbbd: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fcbd:d7ff:fe46:b95e  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::fcbd:d7ff:fe46:b95e  prefixlen 64  scopeid 0x20<link>
        ether fe:bd:d7:46:b9:5e  txqueuelen 0  (Ethernet)
        RX packets 19  bytes 1446 (1.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 340  bytes 27370 (27.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth078da07: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e8ff:8ff:feca:11b  prefixlen 64  scopeid 0x20<link>
        ether ea:ff:08:ca:01:1b  txqueuelen 0  (Ethernet)
        RX packets 1807  bytes 184575 (184.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1643  bytes 202552 (202.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth44b5e87: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::1482:bdff:fe0f:ebf  prefixlen 64  scopeid 0x20<link>
        ether 16:82:bd:0f:0e:bf  txqueuelen 0  (Ethernet)
        RX packets 1070  bytes 145756 (145.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 965  bytes 692051 (692.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth486e088: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::8be:2eff:fe3f:2086  prefixlen 64  scopeid 0x20<link>
        ether 0a:be:2e:3f:20:86  txqueuelen 0  (Ethernet)
        RX packets 115  bytes 9971 (9.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 404  bytes 44386 (44.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth533929e: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::70bb:9cff:fefb:d20  prefixlen 64  scopeid 0x20<link>
        ether 72:bb:9c:fb:0d:20  txqueuelen 0  (Ethernet)
        RX packets 13  bytes 1086 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 309  bytes 24618 (24.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth5420d2b: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::6476:2eff:fe2a:455e  prefixlen 64  scopeid 0x20<link>
        ether 66:76:2e:2a:45:5e  txqueuelen 0  (Ethernet)
        RX packets 27220  bytes 3485689 (3.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19775  bytes 1408657 (1.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth6fc57ef: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b467:37ff:fe4e:6540  prefixlen 64  scopeid 0x20<link>
        ether b6:67:37:4e:65:40  txqueuelen 0  (Ethernet)
        RX packets 13  bytes 1086 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 335  bytes 27130 (27.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth7f83ef5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a003:b1ff:fe05:9fe2  prefixlen 64  scopeid 0x20<link>
        ether a2:03:b1:05:9f:e2  txqueuelen 0  (Ethernet)
        RX packets 2843  bytes 3842379 (3.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2919  bytes 3639543 (3.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth982c1a4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::d09c:28ff:fe0f:7aef  prefixlen 64  scopeid 0x20<link>
        ether d2:9c:28:0f:7a:ef  txqueuelen 0  (Ethernet)
        RX packets 74  bytes 6626 (6.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 334  bytes 25721 (25.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethcda9fd0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::1032:50ff:feee:9842  prefixlen 64  scopeid 0x20<link>
        ether 12:32:50:ee:98:42  txqueuelen 0  (Ethernet)
        RX packets 1715  bytes 3511067 (3.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1718  bytes 298839 (298.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethd42ef7f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::18a2:86ff:fe08:7249  prefixlen 64  scopeid 0x20<link>
        ether 1a:a2:86:08:72:49  txqueuelen 0  (Ethernet)
        RX packets 186  bytes 540946 (540.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 592  bytes 51776 (51.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethea9718c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ecd9:daff:fef5:8307  prefixlen 64  scopeid 0x20<link>
        ether ee:d9:da:f5:83:07  txqueuelen 0  (Ethernet)
        RX packets 13  bytes 1086 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 326  bytes 26296 (26.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethed52ac2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b447:a3ff:fe42:74a1  prefixlen 64  scopeid 0x20<link>
        ether b6:47:a3:42:74:a1  txqueuelen 0  (Ethernet)
        RX packets 237  bytes 31678 (31.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 526  bytes 40328 (40.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `

 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
`# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.129.69
151.101.65.69
151.101.1.69
151.101.193.69`

**Comment by patschi** [comment]
At least from my side I'm having no ideas what might be wrong here. Everything seems to be fine. Just a random guess... where's your mailcow hosted at? It might have something to do with the MTU of 9000.

**Comment by 80kk** [comment]
The problem was with separate ipv6 firewall running on the host.
