### ISSUE TITLE
quota 

### ISSUE THREAD

**Issue by cchalifo999** [mailcow/mailcow-dockerized#2956]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to...
2. And then to...
3. But once I do...

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [x] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | fedora 30 server|
| Is Apparmor, SELinux or similar active? | disable |
| Virtualization technlogy (KVM, VMware, Xen, etc) | vmware|
| Server/VM specifications (Memory, CPU Cores) | 8GB ram   |
| Docker Version (`docker version`) |current |
| Docker-Compose Version (`docker-compose version`) |current |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).
the is for my second user in the user setting
Quota (MiB)
max. 0 MiB
0 = ∞

the first user setting 

Quota (MiB)
max. 10240 MiB
0 = ∞

and here is the setting for the default quota
Max. aliases 400
Max. possible mailboxes 10
Default mailbox quota 10240
Max. quota per mailbox (MiB) 10240
Domain quota 10240

**Comment by andryyy** [comment]
Unlimited quota means unlimited and thus no quota is applied
Unlimited is not "unlimited but apply max mailbox quota and add up all users usage, but only those with no limit set". If you need a limit, you set a limit. :) We cannot mix quota usages and calculate a shared usage.
There's another issue describing this.

**Comment by cchalifo999** [comment]
> 
> 
> Unlimited quota means unlimited and thus no quota is applied
> Unlimited is not "unlimited but apply max mailbox quota and add up all users usage, but only those with no limit set". If you need a limit, you set a limit. :) We cannot mix quota usages and calculate a shared usage.
> There's another issue describing this.

so the 0 = ∞ mean Unlimited quota

**Comment by cchalifo999** [comment]
![Screenshot The 2nd acount (57)_LI](https://user-images.githubusercontent.com/2941510/65300213-b73b0880-db40-11e9-8bc9-8c896711cc49.jpg)
![Screenshot THE FIRST-account when i installed mailcow (58)](https://user-images.githubusercontent.com/2941510/65300214-b73b0880-db40-11e9-9f0c-41942ee51413.png)

**Comment by cchalifo999** [comment]
> 
> 
> Unlimited quota means unlimited and thus no quota is applied
> Unlimited is not "unlimited but apply max mailbox quota and add up all users usage, but only those with no limit set". If you need a limit, you set a limit. :) We cannot mix quota usages and calculate a shared usage.
> There's another issue describing this.

ty i thoug there was someting worng  ty agane

**Comment by andryyy** [comment]
No problem. :) no, it is fine. Max quota per mailbox is just what you can assign to a mailbox at max.
