### ISSUE TITLE
multiple SoGo addons for Thunderbird

### ISSUE THREAD

**Issue by raako71** [mailcow/mailcow-dockerized#2957]
I have tried to add a second SoGo integration to Thunderbird, but it failed. As it stands there is only one address book that can be synchronized with mailcow?
- very impressive feature as it stands! :D

**Comment by mkuron** [comment]
You can only install the plugins once. Integrator always manages the primary account, but you can manually add other accounts‘ clendars and address books via their CalDAV/CardDAV URLs.
