### ISSUE TITLE
Unable to create / delete calendars in client app

### ISSUE THREAD

**Issue by ghosttrax** [mailcow/mailcow-dockerized#2958]
Creating or deleting a calendar creates the calendar multiple times
SOGo behaviour is correct

![Screenshot 2019-09-20 at 08 51 16](https://user-images.githubusercontent.com/8159051/65305739-3140b100-db84-11e9-97a2-9f98096d276c.png)

**Comment by ghosttrax** [comment]
What info do you want?

**Comment by patschi** [comment]
Use the mandatory bug report template when opening a github issue. It does exist for a reason.
