### ISSUE TITLE
[Community Request] Gitter or some other chatroom

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#296]
Hi everyone!
I'd really dig having a chatroom for us mailcow-users 👍 .

Is there something available?

**Comment by ecdsa521** [comment]
There is IRC channel `#mailcow` on Freenode

**Comment by Braintelligence** [comment]
Is there some kind of logging or archiving of the chats with a full-text search? I almost have no use for IRC anymore, because most of the projects I contribute to or use do have modern chatrooms =/...

**Comment by stevesbrain** [comment]
IRC is still modern in the sense that there are many modern projects that make use of it :D

**Comment by Braintelligence** [comment]
@stevesbrain Aw come on you know what I mean :D

**Comment by stevesbrain** [comment]
Haha, I do yeah :P I think either way though, you're probably going to split the community a bit. There's a portion of users who'll never jump if it's IRC, and there's a portion who'll never jump on if it's a more modern alternative. In that case, it'd probably come down to what fits best into dev's workflow, both for daily routine, as well as tools etc.

**Comment by Braintelligence** [comment]
I would never want to split the community or try to win over people from IRC to somewhere else. Rather I'd like to have an alternative where at least the contributors may be available for questions :)

**Comment by chriscroome** [comment]
There is a [web interface to freenode](https://webchat.freenode.net/) and although there are no logs I have found the developers to be super helpful, for example, I wanted to know how to generate a hashed password to use in a modified version of the `mailcow-reset-admin.sh` and I got an almost instant answer, `doveadm pw -s SSHA256 -p PASSWD`, so IRC works well for me.

But having said that it's a shame the Discourse forum no longer exists, there were some things I was searching for that returned links to the now non-existent forum.

**Comment by Braintelligence** [comment]
I would very like something like a Flarum discuss platform or something like Slack/Gitter/Discord.

**Comment by mablae** [comment]
I like IRC much love, close this already! ❤️

**Comment by michacassola** [comment]
Why resist modern tools?

**Comment by michacassola** [comment]
Why resist modern tools? Slack has become an industry standard.
@andryyy I will gladly hand over this slackchannel to you: https://mailcow.slack.com/

**Comment by ecdsa521** [comment]
Adding ads and corporate overlords does not make it modern.

IRC is as modern as your client of choice.

**Comment by Adorfer** [comment]
a tool discussion! Yay!

**Comment by michacassola** [comment]
It is used a lot, that's why it is the standard.
When I googled IRC Client only horrible looking 1995 stuff came up, but of course that is a matter of taste.

Also last I checked mailcow was built with docker now, so extremist open source arguments that the "corporate overlords" shall be avoided at all cost don't count.
Also I just checked the online interface of slack: No ads. And the offline app I have installed: No ads.

**Comment by lenucksi** [comment]
Without going into detail on tool discussions, I'd like to highlight the existence of https://github.com/42wim/matterbridge/ . It syncs various comms tools rather seamlessly (such as Gitter, Slack, IRC, Discord, Matrix, ...)
It works rather nice across a variety of chat-tools. Maybe that'd be worth a consideration.

**Comment by andryyy** [comment]
That sounds interesting.
