### ISSUE TITLE
Nginx Bad Gateway

### ISSUE THREAD

**Issue by AuxiliumCDNG** [mailcow/mailcow-dockerized#2961]
Hi!

My issue is that after the installation i cannot open the admin panel because nginx returns "502 Bad Gateway".

[configs and versions](https://cloud.itechnious.com/index.php/s/KBTbkmXXfnb4j6s)

I exactly followed the instructions in the documentation.

Of course I cleared the browser cache, reinstalled the software multiple times and rebooted the server. But because I'm new to this docker mailserver thing, I was unable to try anything else.

**System information**
My operating system: **Debian 9**
Virtualization technlogy (KVM, VMware, Xen, etc) **It's a VPS hosted by Contabo; software doesn't run in a VM**
Server/VM specifications: **2 Cores (speed not known) and 4gb ram""
Docker Version (`docker version`): **(See link)**
Docker-Compose Version (`docker-compose version`): **(See link)**
Reverse proxy (custom solution): **I'm using apache2 as a ReverseProxy but I already tried without it with same results**

Further notes:
 `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254`:
```
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

 `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
```
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

PS: This is my first issue and if that wasn't enough I'm from Germany! So if you have any criticisms about this, feel free to let me know!

**Comment by AuxiliumCDNG** [comment]
After a complete reinstall of both docker and docker-compose and a few minutes waiting after install has completed, mailcow works now!
Would be great if you could add this in the troubleshooting section of your documentation!
But because of SOGo issues I will probably open another issue regarding this (if I can't fix it myself of course).
Thanks and bye!

**Comment by andryyy** [comment]
Why? The installation docs are complete. If you stop mailcow without checking the logs, I cannot help. If you feel like information is missing, create a pull request with your changes. 

For your SOGo question: This is not a ticket system, please don't use it for support related questions. Visit us on Telegram or IRC.

**Comment by Adorfer** [comment]
My suspicion: people really underestimate the time it takes to populate and getting the docker containers to be fully functional. not only during first install, but as well after update or just reboot. 
Especially if your VM does not come as dualcore, 16GB RAM, SSD it may not only take 4, but 30+ minutes. (those figures are not a joke, i have seen such overbooked/overprovisioned VPS hostings) 
In other words: in case of doubt (and if you think you have done everything right during setup): do something else for an hour and then recheck. If it's your hosting that's slow: you have probably options. 
one of them: Not using a mailsystem with rspamd and solr ;-)

**Comment by AuxiliumCDNG** [comment]
That might be true. But in my case I left the containers over night with no luck. After the complete reinstall the containers were fully functional (except SOGo) after seconds. I still don't understand how pulling the dependencies again made any difference but anyway, it works now. Like I said: It would be a nice idea to make such small changes to nginx and the docs to make setup for anyone much easier. Don't get me wrong! Mailcow is a great software! But such small things can ruin the experience!
