### ISSUE TITLE
IPv6 works but not exchanging emails using it.

### ISSUE THREAD

**Issue by 80kk** [mailcow/mailcow-dockerized#2962]
I have working IPv6 in my Mailcow instance, but I found that it won't exchange mail using this protocol. Is there anything else I should enable to make Postfix talking to other servers (Gmail) using IPv6?

**Comment by andryyy** [comment]
```
echo smtp_address_preference = ipv6 > data/conf/postfix/extra.cf
docker-compose restart postfix-mailcow
```

**Comment by 80kk** [comment]
I changed `smtp_address_preference = ipv4` to ipv6 in main.cf instead of adding extra.cf as it was complaining in logs:
`warning: /opt/postfix/conf/main.cf, line 197: overriding earlier entry: smtp_address_preference=ipv4`
However it is still not talking using IPv6.

**Comment by patschi** [comment]
Just in case: `ping -6 ip6.mailcow.email` works fine on your mailcow server?

**Comment by andryyy** [comment]
Ping from within the container. I don't think IPv6 is working then.

**Comment by 80kk** [comment]
> Just in case: `ping -6 ip6.mailcow.email` works fine on your mailcow server?

It works well. However the only container having ping or traceroute binaries is acme, so:
`root@mail:~# docker exec -it 64b bash`
`bash-5.0# ping -6 ip6.mailcow.email`
`PING ip6.mailcow.email (2a00:f820:417::4): 56 data bytes`
`64 bytes from 2a00:f820:417::4: seq=0 ttl=56 time=32.925 ms`
`64 bytes from 2a00:f820:417::4: seq=1 ttl=56 time=32.158 ms`
`64 bytes from 2a00:f820:417::4: seq=2 ttl=56 time=29.576 ms`
`--- ip6.mailcow.email ping statistics ---`
`3 packets transmitted, 3 packets received, 0% packet loss`
`round-trip min/avg/max = 29.576/31.553/32.925 ms`

`bash-5.0# traceroute -6 ip6.mailcow.email`
`traceroute to ip6.mailcow.email (2a00:f820:417::4), 30 hops max, 72 byte packets`
 `1  fd4d:6169:6c63:6f77::1 (fd4d:6169:6c63:6f77::1)  0.011 ms  0.010 ms  0.007 ms`
 `2  2001:470:71:12e::1 (2001:470:71:12e::1)  0.182 ms  0.159 ms  0.035 ms`
` 3  tunnel492613.tunnel.tserv28.waw1.ipv6.he.net (2001:470:70:12e::1)  8.892 ms  9.327 ms  7.524 ms`
 `4  10ge3-19.core1.waw1.he.net (2001:470:0:222::1)  6.825 ms  13.837 ms  7.951 ms`
 `5  100ge11-2.core1.vie1.he.net (2001:470:0:280::1)  19.188 ms  18.472 ms  21.374 ms`
 `6  100ge9-2.core1.muc1.he.net (2001:470:0:41d::2)  24.260 ms  24.420 ms  24.565 ms`
`7  100ge14-2.core1.fra2.he.net (2001:470:0:2ef::1)  29.604 ms  30.070 ms  29.324 ms`
 `8  meerfarbig.dwh.kleyrex.net (2001:7f8:33::a103:4549:1)  29.914 ms  31.658 ms  29.414 ms`
 `9  *  *  *`
`10^C`

gmail:
`bash-5.0# traceroute -6 gmail.com`
`traceroute to gmail.com (2a00:1450:401b:806::2005), 30 hops max, 72 byte packets`
 `1  fd4d:6169:6c63:6f77::1 (fd4d:6169:6c63:6f77::1)  0.010 ms  0.009 ms  0.007 ms`
 `2  2001:470:71:12e::1 (2001:470:71:12e::1)  0.124 ms  0.045 ms  0.083 ms`
 `3  tunnel492613.tunnel.tserv28.waw1.ipv6.he.net (2001:470:70:12e::1)  9.948 ms  9.206 ms  7.780 ms`
 `4  10ge3-19.core1.waw1.he.net (2001:470:0:222::1)  6.029 ms  6.345 ms  6.162 ms`
 `5  google.ip6.epix.net.pl (2001:7f8:5b::134)  6.025 ms  2001:7f8:60::1:5169:1
(2001:7f8:60::1:5169:1)  6.133 ms  google.ip6.epix.net.pl (2001:7f8:5b::134)  5.953 ms`
 `6  2001:4860:0:1184::1 (2001:4860:0:1184::1)  5.976 ms  6.860 ms  2001:4860:0:1185::1 (2001:4860:0:1185::1)  7.301 ms`
 `7  2001:4860:0:1::fc1 (2001:4860:0:1::fc1)  7.260 ms  2001:4860:0:1::e07 (2001:4860:0:1::e07)  7.309 ms  2001:4860:0:1::fc1 (2001:4860:0:1::fc1)  7.339 ms`
 `8  waw02s16-in-x05.1e100.net (2a00:1450:401b:806::2005)  6.067 ms  6.013 ms  6.254 ms`

**Comment by tkorves** [comment]
You're using IPv6 via a HE tunnel, am I right? Have you thought about asking them to enable outgoing traffic for port 25/TCP originating from your node? If not, it's as far as I remember blocked by default to protect their networks reputation.

**Comment by 80kk** [comment]
> You're using IPv6 via a HE tunnel, am I right? Have you thought about asking them to enable outgoing traffic for port 25/TCP originating from your node? If not, it's as far as I remember blocked by default to protect their networks reputation.

That was the case, thanks. I had to pass SAGE certification process and then ask to unblock SMTP and IRC. It works now.
