### ISSUE TITLE
IMAP eMail Login nicht möglich / IMAP eMail Login not possible

### ISSUE THREAD

**Issue by projektug24** [mailcow/mailcow-dockerized#2963]
<-English see below->

Hallo,

ich habe den aktuellen Mailcow Docker auf einem Debian 9 System installiert.
Per Active Sync funktioniert der eMail Abruf Problemlos, allerdings ist kein Login per IMAP möglich. der Server läuft zwar (telnet server.tld 143): * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.
Unter dem SSL Port (993) kommt jedoch keine Antwort
Versuche ich mit IMAPSize mein Postfach inhalt zu übertragen kommt beim Port 143 Benutzername / Kennwort falsch und bei 993 das dieser Port nicht erreichbar ist.

Als Login habe ich die vollständige eMail Adresse verwendet, die über SoGo und Active Sync funktioniert.
Eine Idee?

---
Hi,

I've installed the latest Mailcow Docker on a Debian 9 system.
With the help of Active Sync, the eMail retrieval works without problems, however, no login via IMAP is possible. The server is running (telnet server.tld 143): * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL + STARTTLS LOGINDISABLED] Dovecot ready.
However, there is no answer under the SSL port (993)
I try with IMAPSize to transfer my mailbox content comes with the port 143 username / password wrong and 993 that this port is not available.

As login I used the complete email address that works with SoGo and Active Sync.
An idea?

**Comment by patschi** [comment]
I guess something is wrong with your SSL setup when 993 doesn't work. Maybe ACME fails requesting a certificate. Beside that: The bug report template is here for a reason, and you also didn't attached any logs.

**Comment by projektug24** [comment]
Hallo, ein Zertifikat fordert er an. Die Domain ist mit einem lets encrypt Zertifikat grundsätzlich gesichert. Welches Logfile wird genau benötigt?

—-

Hello, he asks for a certificate. The domain is basically secured with a lets encrypt certificate. Which log file is needed exactly?
