### ISSUE TITLE
Kontakte über Active Sync / Contacts via Active Sync

### ISSUE THREAD

**Issue by projektug24** [mailcow/mailcow-dockerized#2964]
<-English see below->

Hallo,

wenn ich ein Kontakt am iPhone erstelle synchronisiert er diesen per Active Sync in Outlook (Office365) sowie in das Webinterface (SoGo). Lege ich am Outlook (Office365) einen Neuen Kotnakt an, sehe ich diesen auf dem iPhone und im Webinterface (SoGo). Lege ich jedoch im Webinterface (SoGo) einen Neuen Kontakt an, zeigt er am iPhone einen Kontakt an "Kein Namen" und es ist hier auch kein Inhalt vorhanden (keine Nummer, o.ä.), gleiches Gilt für Outlook (Office365). Ist dies ein bekannter fehler?

---

Hi,

when I create a contact on iPhone he synchronizes it via Active Sync in Outlook (Office365) as well as in the web interface (SoGo). I put on the Outlook (Office365) a new Kotnakt, I see this on the iPhone and in the web interface (SoGo). However, if I put a new contact in the web interface (SoGo), it shows a contact on the iPhone to "No name" and there is no content (no number, etc.), the same applies to Outlook (Office365). Is this a known bug?

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/#get-support (and in this case https://sogo.nu/support.html)

Please also only write in English and use the issue template, whenever you report a **bug**. :)
