### ISSUE TITLE
Question about name

### ISSUE THREAD

**Issue by ShemamAmir** [mailcow/mailcow-dockerized#2968]
Hi, 
I am wondering why Mailcow is called mailcow... is this name relates to any meaning that describes the service?

**Comment by andryyy** [comment]
I love me some cows.

**Comment by irgendwr** [comment]
A secret source tells me that it might get renamed to Mailcat due to andre's obsession with cats 😺

**Comment by andryyy** [comment]
I also love me some cats. Hm.
