### ISSUE TITLE
Update to MariaDB 10.3 went wrong.

### ISSUE THREAD

**Issue by cl445** [mailcow/mailcow-dockerized#2970]
After an update which included MariaDB 10.3 I got several SQL related errors:

fpm: 
```DB initialization failed: PDOException Object
php-fpm-mailcow_1    | (
php-fpm-mailcow_1    |     [message:protected] => SQLSTATE[HY000]: General error: 1577 Cannot proceed, because event scheduler is disabled
...
```
and sogo:
```
sogo-mailcow_1       | Waiting for schema update...
```
I looks like that the update doesn't work properly. 

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to...
2. And then to...
3. But once I do...

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 16.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | No, just Docker |
| Server/VM specifications (Memory, CPU Cores) | 16GB, 8 Cores |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) |  1.18.0 |
| Reverse proxy (custom solution) | yes |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by JAC2703** [comment]
+1 I'm getting this too, after an update this morning.

**Comment by andryyy** [comment]
Stop (down) and start (up -d) mailcow, wait. Or apply the upgrade to mysql manually, if it fails. There is no more I can do to help without access to the server. This issue is also missing logs. Cherry-picking some lines does not help.

Join the Telegram group for support, please.

**Comment by cl445** [comment]
Since the update script is not working as intended and leave the user with a broken system, I think this is not a support issue, but a serious bug.  
For all those who have encountered the same problem, here is a workaround:

1. Open the shell of the MariaDB docker: `docker-compose exec mysql-mailcow sh`
2. Then start the update script manually: `mysql_upgrade -p` 
You need to enter the root password for your database that you will find in your `mailcow.conf`.

**Comment by andryyy** [comment]
I have upgraded like ... 35? mailcows since we upgraded MariaDB to 10.3 and did not have trouble. If you have trouble upgrading mailcow, see the mentioned support methods. You just say it exists, but I don't see it. I cannot replicate it and have big trouble finding someone with a broken installation.

Join the Telegram group and provide information. I think at this point everyone in the group upgraded mailcow and no one had a problem with it.

**Comment by MaxXor** [comment]
No upgrade problems here on Debian 9.

**Comment by JoeRu** [comment]
i can add a +1. Also the performance of the webfrontend is really slooow.

This is from the error-log of the maria-db image:


2019-09-23 21:19:20 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALU


2019-09-23 21:19:20 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.

----

i was successfully with this tipp 👍 
> Open the shell of the MariaDB docker: docker-compose exec mysql-mailcow sh
> Then start the update script manually: mysql_upgrade -p
> You need to enter the root password for your database that you will find in your mailcow.conf.

and afterwards a 
`docker-compose up -d  --force-recreate`

**Comment by andryyy** [comment]
The upgrade failed on "slow" machines. One guy joined Telegram and helped me to troubleshoot it.

**Comment by Wqrld** [comment]
mhh, we are already running the newest mariadb but im still getting the same error

```
This installation of MySQL is already upgraded to 10.3.18-MariaDB, use --force if you still need to run mysql_upgrade
```
