### ISSUE TITLE
Update dovecot > 2.2.19

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#2971]
I want to enable push notifications on my server. But the plug in required dovecot 2.2.19 or higher which enables notifications. 

https://github.com/st3fan/dovecot-xaps-daemon

**Comment by andryyy** [comment]
We are using Dovecot 2.3.

**Comment by wuast94** [comment]
I updated a 2 weeks ago (timestamp) and run on 1.54:
dovecot-mailcow (mailcow/dovecot:1.54) (Started on Fri, 06 Sep 2019 08:59:45 +0200)

In this repo in docker-compose: 
image: mailcow/dovecot:1.89

Did I something wrong? I didn't see a version 2.3 :/

**Comment by mkuron** [comment]
1.54 is the name of the image, not the Dovecot version. If you‘re still running that and not 1.89, you haven‘t updated in a long time.

**Comment by wuast94** [comment]
I updated on 06 September 2019

**Comment by mkuron** [comment]
Please show us the first couple of lines that the command `git log` displays.

**Comment by wuast94** [comment]
`    [Rspamd] Updated bad_word maps
commit e34427ca1a65af41520712a9443848a776a78017
Merge: f297dacd 3ed76901
Author: moo <moo@cow.moo>
Date:   Sat Sep 21 16:51:47 2019 +0200

    After update on 2019-09-21_16_48_51

commit 3ed7690115d67809a2b1d084cd676009352de531
Merge: 1207c6e8 fe38275c
Author: André Peters <andre.peters@debinux.de>
Date:   Sat Sep 21 14:17:08 2019 +0200

    Merge pull request #2960 from mailcow/revert-2941-domain-name-fi
x
    
    Revert "Make is_valid_domain_name more strict"

commit fe38275cb5521c9a8c52b7fe42e97c002dffe39b
Author: André Peters <andre.peters@debinux.de>
Date:   Sat Sep 21 14:16:50 2019 +0200

    Revert "Make is_valid_domain_name more strict"

commit 1207c6e86541e07baae38df2598a7ea7a7998acc
Author: andryyy <andre.peters@debinux.de>
Date:   Sat Sep 21 10:44:08 2019 +0200

    [Web] Do not check hostname is is_valid_domain_name

commit 2738a7f46c42bf648976efeb322536ed6e5d334d
Merge: 3bd32072 0dbc03a4
Author: andryyy <andre.peters@debinux.de>
Date:   Fri Sep 20 22:59:17 2019 +0200

:
`

**Comment by wuast94** [comment]
[Rspamd] Updated bad_word maps
commit e34427ca1a65af41520712a9443848a776a78017
Merge: f297dacd 3ed76901
Author: moo <moo@cow.moo>
Date:   Sat Sep 21 16:51:47 2019 +0200

    After update on 2019-09-21_16_48_51

commit 3ed7690115d67809a2b1d084cd676009352de531
Merge: 1207c6e8 fe38275c
Author: André Peters <andre.peters@debinux.de>
Date:   Sat Sep 21 14:17:08 2019 +0200

    Merge pull request #2960 from mailcow/revert-2941-domain-name-fi
x
    
    Revert "Make is_valid_domain_name more strict"

commit fe38275cb5521c9a8c52b7fe42e97c002dffe39b
Author: André Peters <andre.peters@debinux.de>
Date:   Sat Sep 21 14:16:50 2019 +0200

    Revert "Make is_valid_domain_name more strict"

commit 1207c6e86541e07baae38df2598a7ea7a7998acc
Author: andryyy <andre.peters@debinux.de>
Date:   Sat Sep 21 10:44:08 2019 +0200

    [Web] Do not check hostname is is_valid_domain_name

commit 2738a7f46c42bf648976efeb322536ed6e5d334d
Merge: 3bd32072 0dbc03a4
Author: andryyy <andre.peters@debinux.de>
Date:   Fri Sep 20 22:59:17 2019 +0200

:

**Comment by pictosun** [comment]
As far as I know you need an Apple server license (and of course hardware) to connect dovecot with apples push service.

**Comment by wuast94** [comment]
> As far as I know you need an Apple server license (and of course hardware) to connect dovecot with apples push service.

That's true...would be an option to use pushover for private purpose
