### ISSUE TITLE
Aliases don't show up in SOGo as selectable FROM address.

### ISSUE THREAD

**Issue by itsbhanusharma** [mailcow/mailcow-dockerized#2975]
Seems like it's broken since I updated mailcow this evening. 

I;m running latest mailcow version. 

I had a few aliases set up in mailcow (to make them selectable from address). The old aliases are showing up just fine, even removing the old aliases by deleting them from mailcow works but adding new aliases makes no difference in sogo. 

As troubleshooting, I've tried the following:
1. Restart SOGo
2. Reset SOGo Profile
3. Restarted Mailcow (docker-compose down and docker-compose up -d) 

I've also made sure that aliases show up in the USER mailcow profile next to Direct Alias Addresses so it seems like something is preventing SOGo from showing the new addresses. 

I'd really appreciate any help, Need to figure this out since I have to send a few emails from one such address and don't really want to have two separate mailboxes.

**Comment by andryyy** [comment]
Thanks!

**Comment by wuast94** [comment]
i have the same problem. I have multiple aliases for my catchall adress but only one showing up. I double checkt the config but it don't work
