### ISSUE TITLE
update script does full re-run each time

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#2976]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

The update script (`update.sh`) always updates, re-pulling the images, even after just completed update.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Invoke `update.sh` and use it to update.
2. Invoke `update.sh` again, notice that the update script will not just notify you that there are no updates, instead, it will ask to process (`y/N`) and when confirming, it will re-pull the docker images, etc. The whole process seems to be idempotent though.

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS |
| Is Apparmor, SELinux or similar active? | AppArmor is active, SELinux doesn't seem to be installed |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Cloud instance |
| Server/VM specifications (Memory, CPU Cores) | 2vCPUs, 8 GB RAM, 80 GB disk |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | None. |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
Only HTTP->HTTPS redirection in `nginx.conf`.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
No special firewall or NAT rules.
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? IPs are listed, no timeouts.

**Comment by andryyy** [comment]
You can use `--check` as parameter. :)

**Comment by strarsis** [comment]
@andryyy: So this is normal, intended behaviour then?

**Comment by andryyy** [comment]
Yes, it ins intended as of today.
