### ISSUE TITLE
Certificate for domain and subdomain?

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#2977]
I have My mail under mail.domain.de and the certificate is fine
Under domain.de I get the same output as mail.domain.de but with an invalid certificate. 

Some apple device seems to get stuck on this. I configured the exact same settings on multiple devices all set with mail.domain.de and some working just fine..some Devices throws errors from time to time and then weeks all is good.

So it seems that acme don't obtain a certificate for domain.de? Can I configure that? So that acme obtain a certificate for mail.domain.de and domain.de? 

And mail.domain.de get forced to ssl connection...domain.de not

**Comment by amorfo77** [comment]
you can configure your additional domains/subdomains in the file _mailcow.conf_, if you check that file, you will see:
>\# Additional SAN for the certificate
>\#
>\# You can use wildcard records to create specific names for every domain you add to mailcow.
>\# Example: Add domains "example.com" and "example.net" to mailcow, change ADDITIONAL_SAN >to a value like:
>\#ADDITIONAL_SAN=imap.*,smtp.*
>\# This will expand the certificate to "imap.example.com", "smtp.example.com", "imap.example.net", "imap.example.net"
>\# plus every domain you add in the future.
>\#
>\# You can also just add static names...
>\#ADDITIONAL_SAN=srv1.example.net
>\# ...or combine wildcard and static names:
>\#ADDITIONAL_SAN=imap.*,srv1.example.com
>\#
>ADDITIONAL_SAN=

Aditionally, in the official [SSL documentation:](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/)

> The "acme-mailcow" container will try to obtain a LE certificate for ${MAILCOW_HOSTNAME}, autodiscover.ADDED_MAIL_DOMAIN and autoconfig.ADDED_MAIL_DOMAIN.

**Comment by wuast94** [comment]
The First part don't work. Mailcow hostname must be a FQDN. So I can't enter there domain.de and enter in additional San "Mail". This fails becouse mailcow hostname is no FQDN

The second part is the slightly the same. I can't say to obtain and server a valid certificate for just domain.de and mail.domain.de

**Comment by andryyy** [comment]
You can set `ADDITIONAL_SAN=domain.tld` and run `docker-compose up -d`. Check the `acme-mailcow` logs afterwards.

**Comment by wuast94** [comment]
I did and in the logs there only shows up autodiscover.domain.tld and mail.domain.tld In the logs. Autodiscover is added per San.
I rebooted the whole server becouse I can't stop or start via docker-compose becouse I get this error:

`➜  mailcow-dockerized git:(master) ✗ docker-compose up -d 
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: Pool overlaps with other one on this address space`

**Comment by wuast94** [comment]
ok i have reinstall all and I add the additional san but It didn't work. in acme log the same as before

**Comment by andreas-emrich** [comment]
Did anyone have a solution for that?

**Comment by andryyy** [comment]
See my previous answer. And check the logs, if it could not acquire a certificate.
