### ISSUE TITLE
Explanation of how to setup a Backup Server

### ISSUE THREAD

**Issue by thestevexyz** [mailcow/mailcow-dockerized#2978]
Hello,

I have multiple VPS and I want to use a Backup Mailserver if my first VPS with Mailcow installed is offline. There are some options in the Mailcow Admin Panel, but I didn't find an explanation.

**Comment by andryyy** [comment]
There is no cluster option and there will never be an option on the open source mailcow. 

You can create a PR or sponsor it. 

Git is not meant for support. Please check the docs.

**Comment by thestevexyz** [comment]
Okay, thank you nevertheless.
