### ISSUE TITLE
[feature request] logs folder at docker host

### ISSUE THREAD

**Issue by pgollor** [mailcow/mailcow-dockerized#298]
Hi,
first of all: mailcow is a great project. ;)

But i want to ask for a feature with the mailcow docker container.
It is possible to link all log files from each container (postfix, dovecot, etc.) on a local logs folder?
It could useful in different ways:
- using logrotate for each logfile
- using a central fail2ban instance at the host

Thanks.

**Comment by andryyy** [comment]
Hi,
Docker can log to Syslog. :-) You can find it in the docs. I also added a howto for Fail2ban there.

**Comment by pgollor** [comment]
It was my fault. I was to stupid to found the logging section in the documentation. Sorry for that.
But works it with roundcube or any third party app inside the container which only logs to a file and not to syslog?

**Comment by stevesbrain** [comment]
@pgollor You could always use a log collector to send those on to syslog/rsyslog :)
