### ISSUE TITLE
Postfixs accepts mails for non existing recipients in a relay domain

### ISSUE THREAD

**Issue by Clevero** [mailcow/mailcow-dockerized#2981]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is that for relay domains mails are accepted regardless if their recipient exists on the actual mail server (Exchange Server 2016) or not. Mailcow accepts the mail (```250 2.0.0 Ok: queued as ...```) and fails when relaying the mail to the actual mailserver. This leads to cases where the sender miswrites the adress of the recipient, sends it to mailcow and does not get any reject at SMTP level that the recipient does not exist and therefor cannot be accepted. In cases where the mail is urgent (think of call-out service for example) this can make problems because the sending mail server assumes now that the mail was delivered and does not know that the address is maybe miswritten

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Create and configure domain.de as a relay domain in mailcow (no catch all alias configured)
2. Create a user (alice.smith@domain.de) on the actual mailserver where mailcow forwards mails to domain.de
3. Create a user in mailcow (alice.smith@domain.de) so that alice has access to her personal quarantine. Other mails should be delivered as usal to the actual mailserver
4. Send an email to alice.smith@domain.de, email should be accepted and delivered to the actual mailserver
5. Send an email to alice.smit@domain.de (non existing on the acutual mailserver), email should be accepted and should create a MAILER-DAEMON message in the mailcow Queue-Manager since mailcow tries to forward the mail to the actual mailserver and fails because the user alice.smit@domain.de does not exist

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian GNU/Linux 9.9 (stretch) |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | VMware vSphere |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 8 vCPUs |
| Docker Version (`docker version`) | client & server 18.09.7 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | Does this inlcude having mailcow as a gateway between internet and actual mailserver? |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? [git diff mailcow.txt](https://github.com/mailcow/mailcow-dockerized/files/3656625/git.diff.mailcow.txt) Summary: Modified version of /etc/rspamd/custom/sa-rules-heinlein to include other sources of rules (needs to be developed ruther and testeted and is planned to result in a PR); lower message_size_limit; added own DNS RBLs; some test things with clamav; rspamd autolearn with bayes to true; modifocations in ```smtpd_recipient_restrictions``` of postfix at main.cf where not added when the problems started to appear and are part of my fix (in testing).
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
[iptables output.txt](https://github.com/mailcow/mailcow-dockerized/files/3656651/iptables.output.txt)
[iptables6 output.txt](https://github.com/mailcow/mailcow-dockerized/files/3656652/iptables6.output.txt)
[iptables nat output.txt](https://github.com/mailcow/mailcow-dockerized/files/3656653/iptables.nat.output.txt)
[iptables6 nat output.txt](https://github.com/mailcow/mailcow-dockerized/files/3656656/iptables6.nat.output.txt)

 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
```
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```
and 
```
151.101.193.69
151.101.1.69
151.101.65.69
151.101.129.69
```
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

## Possible Solution
Let postfix check if the recipient address exists so that mails with non existing recipients can be rejected at SMTP level. For example with 450 Recipient address rejected: unverified address

## Possible Implementation
In postfixs main.cf add ```reject_unverified_recipient``` (maybee also ```reject_unknown_recipient_domain```) to ```smtpd_recipient_restrictions```
For example: 
```smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf, reject_invalid_helo_hostname, reject_unknown_reverse_client_hostname, reject_unauth_destination, reject_unknown_recipient_domain, reject_unverified_recipient```

Postfix now checks after receiving the recipient via ```RCPT TO:``` on SMTP dialog if the recipient exists. For that, postfix looks up the recipient address on the actual mailserver.
Postfix caches those lookups in a database. That means not for every mail the lookup is done which would result in a slower performance for all mails.

More information: http://www.postfix.org/ADDRESS_VERIFICATION_README.html#recipient

Example SMTP dialog with swaks:
```
=== Trying exchange.domain.de:25...
=== Connected to exchange.domain.de.
<-  220 mailcow-srv.domain.local ESMTP Postcow
 -> EHLO mytestserver.example.com
<-  250-mailcow-srv.domain.local
<-  250-PIPELINING
<-  250-SIZE 26214400
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 DSN
 -> MAIL FROM:<test@mytestserver.example.com>
<-  250 2.1.0 Ok
 -> RCPT TO:<alice.smit@domain.de>
<** 450 4.1.1 <alice.smit@domain.de>: Recipient address rejected: undeliverable address: host 10.241.1.27[10.241.1.27] said: 550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup (in r
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
```

## Tested use cases with Possible Implementation:
* Existing user receives her mails alice.smith@domain.de ✅
* Alice received her mails via her alias alice@domain.de -> alice.smith@domain.de ✅
* Miswritten address alice.smit@domain.de results in a 450 Recipient address rejected ✅

**Note:** Cases with a Catch-All alias were not tested yet, will test it in a bit. 

@mkuron

**Comment by andryyy** [comment]
@mkuron What's your opinion on this?

**Comment by mkuron** [comment]
So far, of course we recommend unchecking "Relay all recipients" and creating dummy accounts on Mailcow. I think setting `reject_unverified_recipient` defeats the point of a backup MX (it will then tempfail the message if the primary MX is unreachable, at least that's how I understand the documentation), but makes sense for relaying. For relaying, you would also also want to set `unverified_recipient_reject_code = 550` to permfail it, but you definitely don't want to do that on a backup MX.

**Comment by Clevero** [comment]
So this is more likely a thing for the documentation as a note?
