### ISSUE TITLE
PDF false positive (VIRUS_FOUND vs. clamscan)

### ISSUE THREAD

**Issue by mamash** [mailcow/mailcow-dockerized#2982]
**Prior to placing the issue, please check following:**
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:

I just got spam rejected while trying to send a simple email with a PDF attached. Investigating, I found that rspamd attached the known VIRUS_FOUND macro. It is a perfectly fine PDF though, actually of the Czech government tax forms. The only difference is that it's an interactive PDF. Furthermore, clamscan run directly on the file returns a happy OK status.

I do not understand why clamscan claims the file is fine, but rspamd claims that ClamAV reported a virus inside (and there's no virus in fact). What am I missing?

**Reproduction of said bug**:

1. Get this tax form from the Czech tax office:

https://www.financnisprava.cz/assets/cs/prilohy/dt-upozorneni-mf-k-tiskopisum/IF_5457_26.pdf

2. Attach the file to an email
3. Send it through mailcow with stock rspamd config

**Further notes:**

> 2019-09-27 15:21:29 #22(normal) <95e753>; lua; metadata_exporter.lua:268: got unexpected http status: 505
> 2019-09-27 15:21:29 #22(normal) <95e753>; task; rspamd_task_write_log: id: <3AB25FCA-5415-4A33-9AB7-280BE65C0C7C@hajny.net>, qid: <070494050E>, ip: x.x.x.x, user: xxx@xxx, from: <xxx@xxx>, (default: T (reject): [1980.40/15.00] [VIRUS_FOUND(2000.00){},MAILCOW_AUTH(-20.00){},MV_CASE(0.50){},MIME_GOOD(-0.10){multipart/mixed;text/plain;},ARC_NA(0.00){},ARC_SIGNED(0.00){i=1;},ASN(0.00){asn:13036, ipnet:93.153.0.0/17, country:CZ;},DKIM_SIGNED(0.00){},DYN_RL_CHECK(0.00){},FREEMAIL_ENVRCPT(0.00){centrum.cz;},FREEMAIL_TO(0.00){centrum.cz;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MAILCOW_DOMAIN_HEADER_FROM(0.00){hajny.net;},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;1:~;2:+;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},TO_DN_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 498021, time: 236.674ms real, 101.855ms virtual, dns req: 2, digest: <d379fb0a890d843d6f327d93771a9d93>, rcpts: <xxx>, mime_rcpts: <xxx>

```
root@5082d9c8b88b:/# clamscan IF_5457_26.pdf
IF_5457_26.pdf: OK

----------- SCAN SUMMARY -----------
Known viruses: 6482203
Engine version: 0.101.4
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 1.76 MB
Data read: 0.34 MB (ratio 5.11:1)
Time: 50.384 sec (0 m 50 s)
```

**Comment by mkuron** [comment]
If you look at your clamd logs (`docker-compose logs clamd-mailcow`), you'll see something like this:
```
PUA.Pdf.Trojan.EmbeddedJavaScript-1(14e1245b2c5a4af58d142f495a707194:278447) FOUND
```

The way we configure ClamAV, all PDFs with embedded javascripts are rejected. Similarly, we reject all Microsoft Office documents containing macros. This is a security measure as these macros are almost always used for nefarious purposes. ClamAV cannot reliably detect dangerous macros and scripts, so we (and many other mail servers nowadays) just err on the safe side and block all macros and scripts. Also, PDF javascripts are not supported by most PDF viewers besides Adobe Acrobat, so only very few people (unfortunately including the Czech government) even use them.

**Comment by mamash** [comment]
Ah, got you. I'll need to override that on my installation. I find interactive PDFs quite useful and need to use them a couple of times a year (and not just with the government). Entirely agree with you on the MS Office side of things though.

**Comment by andryyy** [comment]
This is something for the support channels mentioned in the docs. :)

Search data/conf/clamav/whitelist.ign2 please and create a PR for the docs, if you don't mind.

**Comment by MAGICCC** [comment]
Done with https://github.com/mailcow/mailcow-dockerized-docs/pull/164

**Comment by andryyy** [comment]
Thank you!!
