### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#2983]
Hello,

I have two questions:
1. My VPS is 50% full although I only have a few mails stored on the server, can it be that old data from old updates are stored somewhere? Is it possible to delete them somehow without destroying anything on the current system?
2. I created a file '/opt/mailcow-dockerized/data/conf/postfix/extra.cf' where my manual configurations are embedded, is this content automatically embedded at the end of '/opt/mailcow-dockerized/data/conf/postfix/main.cf' after every update?

Thanks in advance.

**Comment by MAGICCC** [comment]
1.) Depends what 50% is. Also try to run `docker system prune -a` when **every** container is running. It will remove all old container and images.

2.) Yes it will prepend it to main.cf, see here for the script https://github.com/mailcow/mailcow-dockerized/blob/5987079cca4576e2d47a4bb6be6fe56046a1a691/data/Dockerfiles/postfix/postfix.sh#L298-L299

**Comment by omexlu** [comment]
1) 50% of 21 GB, all container are running as i can see on mailcow UI, i can't damage anything with this command `docker system prune -a` ?

2) Ok cool :), so on every update / restart / rebuild of postfix main.cf it will be prepended?

Thanks a lot.

**Comment by andryyy** [comment]
ncdu /var/lib/docker ?

**Comment by omexlu** [comment]
Sorry i am not so that profi :D is that a command? And what do it? (without risk?)

**Comment by MAGICCC** [comment]
Yes its a comand, you may need to install it first
https://linux.die.net/man/1/ncdu

**Comment by omexlu** [comment]
Okay, thank you very much :)

How can I be sure that all containers are up and running before I execute the command that is displayed after the update (look in the UI to see if everything is green)?:
https://github.com/mailcow/mailcow-dockerized/blob/8c26371d6dbb0eea6e01b6de97c768092985e6df/update.sh#L89

Thanks in advance.

**Comment by MAGICCC** [comment]
Yes either this or login into your server, jump into the mailcow folder and execute `docker-compose ps` and check if everything is up

**Comment by omexlu** [comment]
Thank you very much.

As soon as I have checked that all containers are running and up I can free myself from all residual waste (without risk) with the following command?:
`docker system prune`

Thank you in advance.

**Comment by mesudip** [comment]
@omexlu  I don't get why all containers should be running.
Usually when I need to clean my docker machine, I stop and remove all containers, prune all images and then start fresh containers. When theres' a container that logs a lot of content, those logs will also be cleared. Once all the containers are up and running I prune all the unused volumes.

**Comment by andryyy** [comment]
Older versions of docker did. remove all dangling items when running prune. If you stopped mailcow and removed the containers, the volumes were dangling, as no container is using them at this point. Prune then kills these volumes. 

I think they changed that behavior in recent versions.

**Comment by omexlu** [comment]
As i understand, all new contrainers of mailcow must be running and the i can prune with the command:
`docker system prune`

So all will be cleaned :)

**Comment by Adorfer** [comment]
note: "2 questions" feels a little clickbaity for an issue. But i was not disappointed.

**Comment by omexlu** [comment]
> note: "2 questions" feels a little clickbaity for an issue. But i was not disappointed.

clickbait(y) on github, all right, very smart comment :D
PS. Thanks to all helpers.

**Comment by MAGICCC** [comment]
Did it work?

**Comment by omexlu** [comment]
> Did it work?

Not yet, but i will give it a try on the next mailcow update, but i think it will work to prune if all needed containers are up/running :)

PS. I make a snapshot of the vserver before to be sure :)

**Comment by jessicana** [comment]
`sudo docker-compose ps`  does not work with docker compose (v2) and it returns `sudo: docker-compose: command not found`

What similar command I can use after upgrading to docker compose (v2)?

**Comment by ghost** [comment]
> `sudo docker-compose ps` does not work with docker compose (v2) and it returns `sudo: docker-compose: command not found`
> 
> What similar command I can use after upgrading to docker compose (v2)?

You need to use `docker ps -a` to show the state of all containers.

Warning! `ps` without `-a` will show **only** running containers, and even if you know every one of them by heart you risk a big mistake.
