### ISSUE TITLE
Postfix - hide sender IP/User-Agent in headers

### ISSUE THREAD

**Issue by 80kk** [mailcow/mailcow-dockerized#2985]
Not really feature request but more as enhancement. I'd like to hide sender IP address + User-Agent and other more or less private information you can get from headers.

Will it work if I add in `/opt/mailcow-dockerized/data/conf/postfix/extra.cf`:
`header_checks = regexp:/etc/postfix/header_checks`
and then create `/opt/mailcow-dockerized/data/conf/postfix/header_checks` file containing:
`/^Received:/ IGNORE`
`/^X-Originating-IP:/ IGNORE`
`/^X-Mailer:/ IGNORE`
`/^Mime-Version:/ IGNORE`
`/^User-Agent:/ IGNORE`

or the path for regexp should be different?

**Comment by mkuron** [comment]
We already do that in https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/anonymize_headers.pcre. Removing the User-Agent header is not recommended though as it is also applied to incoming messages and this header might be part of the DKIM/ARC signature.

**Comment by pictosun** [comment]
Hi. 
I would rewrite it instead of removing it. 

Set it to: MIME-Version: 1.0

So nobody knows what kind of agent you’re using and you still have the MIME Header within your Mails. 

Fastmail is doing the same since for a long time.

**Comment by pictosun** [comment]
> We already do that in https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/anonymize_headers.pcre. Removing the User-Agent header is not recommended though as it is also applied to incoming messages and this header might be part of the DKIM/ARC signature.

Hi.
I would rewrite it instead of removing it.

Set it to: MIME-Version: 1.0

So nobody knows what kind of agent you’re using and you still have the MIME Header within your Mails.

Fastmail is doing the same since for a long time.

**Comment by andryyy** [comment]
If it's signed, it is broken after changing it.

**Comment by pictosun** [comment]
Ok. But how does for example fastmail.com managed it, to sign it even with changing it into: MIME-Version: 1.0

Looks like it is possible? Or are they just breaking the signature and don't care about?
