### ISSUE TITLE
Spamhaus DNSBL return codes: technical update

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#2987]
FYI https://www.spamhaus.org/news/article/788/

I know that at setup time there's a check that public DNS don't get used for mailcow. Now we have new error codes and a policy update.

> Failure to correctly parse these return codes will render the query results meaningless and detrimental for the querier!

**Comment by mkuron** [comment]
Interesting. As far as I can tell from its source code, postscreen does not support it, so Mailcow can‘t either. I don’t think this behavior is standard per RFC 5782, so you can‘t really blame Postfix for not supporting it. I don‘t know why Spamhaus has decided to encode this in a response instead of sending DNS error codes like SERVFAIL or REFUSED.

**Comment by mkuron** [comment]
RFC 5782:

> A client MUST interpret any returned A record as meaning that an
>   address or domain is listed in a DNSxL.

So Spamhaus is non-compliant here. The only solution here is to stop querying Spamhaus, which I don‘t think is a good idea because it‘s an excellent blacklist. That means we‘ll just have to ignore these special return codes.

**Comment by mkuron** [comment]
http://www.postfix.org/postconf.5.html#postscreen_dnsbl_sites: 


> **postscreen_dnsbl_sites** (default: empty)
> [...]
> 
> Specify a list of domain=filter*weight entries, separated by comma or whitespace.
> 
> When [...] "=filter" is specified, [...] postscreen(8) uses only DNSBL replies that match the filter. The filter has the form d.d.d.d, where each d is a number, or a pattern inside [] that contains one or more ";"-separated numbers or number..number ranges.

We already use these filters (see https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/main.cf#L66), so Mailcow will ignore the two invalid return codes. It won‘t react to them in any special way, but the way I read the Spamhaus page, that‘s not required. So Mailcow does not need to take any action.
