### ISSUE TITLE
mailcow/postfix keeps restarting

### ISSUE THREAD

**Issue by raddup** [mailcow/mailcow-dockerized#2990]
Hello all, i have this problem 
0c79366f13b7        mailcow/postfix:1.40     "/bin/sh -c 'exec /u…"   6 minutes ago       Restarting (0) 53 seconds ago  
the container just keeps restarting i tried this with 4 different kernel 

Operating system Centos 7
Kernel: 3.10.0-1062.1.1.el7.x86_64
Selinux Disabled
Firewalld, Disabled
No smtp 25 port is being used by another service.

[root@localhost mailcow-dockerized]# netstat -anlp | grep -w LISTEN
tcp        0      0 127.0.0.1:19991         0.0.0.0:*               LISTEN      1412/docker-proxy
tcp        0      0 127.0.0.1:13306         0.0.0.0:*               LISTEN      560/docker-proxy
tcp        0      0 127.0.0.1:18983         0.0.0.0:*               LISTEN      582/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1732/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      2809/docker-proxy
tcp6       0      0 :::4190                 :::*                    LISTEN      1435/docker-proxy
tcp6       0      0 :::993                  :::*                    LISTEN      1465/docker-proxy
tcp6       0      0 :::995                  :::*                    LISTEN      1449/docker-proxy
tcp6       0      0 :::110                  :::*                    LISTEN      1514/docker-proxy
tcp6       0      0 :::143                  :::*                    LISTEN      1491/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      2826/docker-proxy
tcp6       0      0 :::21                   :::*                    LISTEN      12709/vsftpd
tcp6       0      0 :::22                   :::*                    LISTEN      1732/sshd

output of the logs:    docker-compose logs --tail=200 postfix-mailcow

postfix-mailcow_1    | 2019-10-01 22:05:12,174 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:05:12,178 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:05:13,180 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:05:13,182 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:05:13,184 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 610  Threads: 29  Questions: 1272  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 2.085
postfix-mailcow_1    | Oct  1 22:05:13 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:05:14,728 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:05:14,728 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:05:14,728 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:05:16 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:05:17,595 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:05:18,598 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:05:18,600 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:05:18,600 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:05:18 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 615  Threads: 29  Questions: 1273  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 2.069
postfix-mailcow_1    | 2019-10-01 22:05:18,703 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:05:19,757 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:05:19,758 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:06:21,105 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:06:21,107 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:06:22,109 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:06:22,111 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:06:22,113 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 679  Threads: 29  Questions: 1406  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 2.070
postfix-mailcow_1    | Oct  1 22:06:22 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:06:23,644 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:06:23,645 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:06:23,645 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:06:25 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:06:26,512 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:06:27,516 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:06:27,517 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:06:27,517 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:06:27 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 684  Threads: 29  Questions: 1407  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 2.057
postfix-mailcow_1    | 2019-10-01 22:06:27,620 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:06:28,674 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:06:28,675 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:07:30,053 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:07:30,056 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:07:31,059 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:07:31,061 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:07:31,063 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 748  Threads: 29  Questions: 1486  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.986
postfix-mailcow_1    | Oct  1 22:07:31 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:07:32,560 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:07:32,560 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:07:32,560 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:07:34 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:07:35,426 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:07:36,429 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:07:36,430 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:07:36,430 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:07:36 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 753  Threads: 29  Questions: 1487  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.974
postfix-mailcow_1    | 2019-10-01 22:07:36,533 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:07:37,588 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:07:37,588 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:08:38,987 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:08:38,991 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:08:39,994 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:08:39,996 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:08:39,998 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 817  Threads: 29  Questions: 1558  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.906
postfix-mailcow_1    | Oct  1 22:08:40 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:08:41,474 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:08:41,474 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:08:41,474 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:08:43 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:08:44,642 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:08:45,645 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:08:45,647 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:08:45,647 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:08:45 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 822  Threads: 29  Questions: 1621  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.972
postfix-mailcow_1    | 2019-10-01 22:08:45,750 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:08:46,803 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:08:46,804 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:09:48,160 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:09:48,164 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:09:49,167 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:09:49,169 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:09:49,171 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 886  Threads: 29  Questions: 1692  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.909
postfix-mailcow_1    | Oct  1 22:09:49 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:09:50,677 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:09:50,677 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:09:50,677 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:09:52 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:09:53,544 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:09:54,547 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:09:54,549 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:09:54,549 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:09:54 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 891  Threads: 29  Questions: 1693  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.900
postfix-mailcow_1    | 2019-10-01 22:09:54,652 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:09:55,706 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:09:55,706 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:10:57,021 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:10:57,023 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:10:58,026 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:10:58,028 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:10:58,030 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 955  Threads: 29  Questions: 1764  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.847
postfix-mailcow_1    | Oct  1 22:10:58 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:10:59,531 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:10:59,531 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:10:59,531 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:11:01 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:11:02,397 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:11:03,400 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:11:03,401 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:11:03,402 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:11:03 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 960  Threads: 29  Questions: 1773  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.846
postfix-mailcow_1    | 2019-10-01 22:11:03,505 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:11:04,557 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:11:04,557 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:12:05,893 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:12:05,897 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:12:06,899 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:12:06,901 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:12:06,903 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 1023  Threads: 29  Questions: 1906  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.863
postfix-mailcow_1    | Oct  1 22:12:06 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:12:08,415 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:12:08,415 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:12:08,415 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:12:10 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:12:11,582 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:12:12,585 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:12:12,586 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:12:12,587 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:12:12 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 1029  Threads: 29  Questions: 1907  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.853
postfix-mailcow_1    | 2019-10-01 22:12:12,689 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:12:13,739 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:12:13,740 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:13:15,119 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:13:15,121 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:13:16,124 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:13:16,125 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:13:16,127 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 1093  Threads: 29  Questions: 2040  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.866
postfix-mailcow_1    | Oct  1 22:13:16 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
postfix-mailcow_1    | 2019-10-01 22:13:17,641 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:13:17,641 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2019-10-01 22:13:17,641 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | /usr/sbin/postconf: warning: valid_hostname: numeric hostname: 82.79.56.27
postfix-mailcow_1    | /usr/sbin/postconf: fatal: unable to use my own hostname
postfix-mailcow_1    | Postfix configuration error, refusing to start.
postfix-mailcow_1    | Oct  1 22:13:19 82 postfix/postfix-script[250]: fatal: the Postfix mail system is not running
postfix-mailcow_1    | 2019-10-01 22:13:20,507 INFO exited: postfix (exit status 1; not expected)
postfix-mailcow_1    | 2019-10-01 22:13:21,510 INFO spawned: 'postfix' with pid 252
postfix-mailcow_1    | 2019-10-01 22:13:21,511 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-10-01 22:13:21,512 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Oct  1 22:13:21 82 syslog-ng[10]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | Uptime: 1098  Threads: 29  Questions: 2041  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.858
postfix-mailcow_1    | 2019-10-01 22:13:21,615 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-10-01 22:13:22,669 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:13:22,669 INFO stopped: processes (terminated by SIGTERM)
postfix-mailcow_1    | 2019-10-01 22:14:23,995 INFO Set uid to user 0 succeeded
postfix-mailcow_1    | 2019-10-01 22:14:23,999 INFO supervisord started with pid 1
postfix-mailcow_1    | 2019-10-01 22:14:25,002 INFO spawned: 'processes' with pid 8
postfix-mailcow_1    | 2019-10-01 22:14:25,004 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2019-10-01 22:14:25,006 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Uptime: 1162  Threads: 29  Questions: 2112  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 33  Queries per second avg: 1.817
postfix-mailcow_1    | Oct  1 22:14:25 82 syslog-ng[10]: syslog-ng starting up; version='3.19.1'
postfix-mailcow_1    | chown: cannot access '/usr/share/man/man1/mailq.1.gz': No such file or directory
[root@localhost mailcow-dockerized]#

**Comment by SkazochnikZlodey** [comment]
warning: valid_hostname: numeric hostname: 82.79.56.27
fatal: unable to use my own hostname

have to be  FQDN like: mail.example.com

**Comment by raddup** [comment]
> warning: valid_hostname: numeric hostname: 82.79.56.27
> fatal: unable to use my own hostname
> 
> have to be FQDN like: mail.example.com

yea. thx for the help. I allready fixed and now is up and running :) you can close this thread :)

**Comment by ghost** [comment]
> 
> 
> > warning: valid_hostname: numeric hostname: 82.79.56.27
> > fatal: unable to use my own hostname
> > have to be FQDN like: mail.example.com
> 
> yea. thx for the help. I allready fixed and now is up and running :) you can close this thread :)

Can you tell me where you fixed it? I changed the "hostname" statement in mailcow.conf but the same error occurs.

@raddup

**Comment by andryyy** [comment]
Did you run up -d afterwards?

**Comment by ghost** [comment]
No, but I restarted postfix via portainer and I also restarted the whole server. 
So now I am searching in all files in my system for the IP shown in the logs.

**Comment by andryyy** [comment]
You should do it. Restarting containers or the server does not rebuild the container with the new variable. :)

**Comment by ghost** [comment]
Ah, this makes sense. I must say I am new to docker but I needed a new Mailserver, so... ;)

Now it works! Thank you andryyy! My Problem is solved.

For the following people out there that have the same problem, here is what I did. 
1. In "mailcow.conf" under "MAILCOW_HOSTNAME=" there need to be a full blown adress like "blabla.com" under which the server available. 
2. And after that I run "docker-compose up -d" and that's it.

**Comment by andryyy** [comment]
No problem at all! :)

Yes, the hostname should be a FQDN.
