### ISSUE TITLE
Solr container is pulled even when Solr is disabled

### ISSUE THREAD

**Issue by kravemir** [mailcow/mailcow-dockerized#2992]
**Description of the bug**: What kind of issue have you *exactly* come across?

I'm trying/testing mailcow on smallish VPS, and I'm following document. I've disabled ClamAV and Solr. However, solr docker image gets pulled.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Have Solr disabled in configuration:

```
# Skip ClamAV (clamd-mailcow) anti-virus (Rspamd will auto-detect a missing ClamAV container) - y/n

SKIP_CLAMD=y

# Skip Solr on low-memory systems or if you do not want to store a readable index of your mails in solr-vol-1.

SKIP_SOLR=y
```

Pull images:

```
docker-compose pull
```

**Comment by andryyy** [comment]
It is pulled and started with an idling bash shell. Nothing else. :) That's intended.

**Comment by kravemir** [comment]
> It is pulled and started with an idling bash shell. Nothing else. :) That's intended.

The consequence of pulling docker image for an unused software is unnecessary disk usage. So, is it intended, that unnecessary disk space is occupied?

**Comment by mkuron** [comment]
> So, is it intended, that unnecessary disk space is occupied?
 
docker-compose does not let you selectively disable containers(https://github.com/docker/compose/issues/1896, https://github.com/docker/compose/issues/6742 ), so from our side this is intentional. If you are really tight on storage, you could delete that container from docker-compose.yml, but then you will occasionally run into merge conflicts during updates. Generally, that's not worth it for a few dozen/hundred megabytes.

**Comment by hugmypc** [comment]
My solution to this is to execute the following bash script after each docker-compose up -d. You could also run this on a schedule using crontab.

The script below essentially just finds any containers with "clamd" and "solr" as string in the name, and does 3 things:

1) Updates container restart policy to OFF (optional and useful command if you need it)
2) Stop the containers (required before deleting)
3) Delete containers

Here's the script. 

```
#!/usr/bin/env bash

docker update --restart no $(docker container ls -q -f "name=clamd")
docker update --restart no $(docker container ls -q -f "name=solr")

docker container stop $(docker container ls -q -f "name=clamd")
docker ps -a | grep "clamd" | awk '{print $1}' | xargs docker rm

docker container stop $(docker container ls -q -f "name=solr")
docker ps -a | grep "solr" | awk '{print $1}' | xargs docker rm
```

To return everything back to normal, simply just run:

`docker-compose up -d`
