### ISSUE TITLE
SOGo authentication not possible

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#3]
Since one of the more recent updates (probably somewhen between 22. Dec till now) SOGo authentication isn't possible anymore. I'm not sure what the problem is. This is are the warnings and errors from the sogo.log:

```
sogo-mailcow_1       | ==> /var/log/sogo/sogo.log <==
sogo-mailcow_1       | Dec 28 15:58:38 sogod [53]: [ERROR] |SOGo| No value specified for 'SOGoProfileURL'
sogo-mailcow_1       | Dec 28 15:58:38 sogod [53]: <0x0x562923661910[WOHttpAdaptor]> notified the watchdog that we are ready
sogo-mailcow_1       | Dec 28 15:58:38 sogod [60]: [ERROR] |SOGo| No value specified for 'SOGoProfileURL'
sogo-mailcow_1       | Dec 28 15:58:38 sogod [60]: <0x0x562923661910[WOHttpAdaptor]> notified the watchdog that we are ready
sogo-mailcow_1       | Dec 28 15:58:38 sogod [55]: [ERROR] |SOGo| No value specified for 'SOGoProfileURL'
sogo-mailcow_1       | Dec 28 15:58:38 sogod [55]: <0x0x562923661910[WOHttpAdaptor]> notified the watchdog that we are ready
sogo-mailcow_1       | Dec 28 15:58:38 sogod [56]: [ERROR] |SOGo| No value specified for 'SOGoProfileURL'
sogo-mailcow_1       | Dec 28 15:58:38 sogod [54]: [ERROR] |SOGo| No value specified for 'SOGoProfileURL'
sogo-mailcow_1       | Dec 28 15:58:38 sogod [56]: <0x0x562923661910[WOHttpAdaptor]> notified the watchdog that we are ready
sogo-mailcow_1       | Dec 28 15:58:38 sogod [54]: <0x0x562923661910[WOHttpAdaptor]> notified the watchdog that we are ready
sogo-mailcow_1       | 2016-12-28 15:58:40,542 INFO success: sogo-syslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

sogo-mailcow_1       | ==> /var/log/sogo/sogo.log <==
sogo-mailcow_1       | 2016-12-28 15:59:09.791 sogod[47] Warning ... someone broke our lock (/var/lib/sogo/GNUstep/Defaults/.lck/.GNUstepDefaults.lck) ... and may have interfered with updating defaults data in file.

sogo-mailcow_1       | ==> /var/log/sogo/sogo.log <==
sogo-mailcow_1       | Dec 28 16:01:27 sogod [54]: <0x0x562923734780[SOGoCache]> Cache cleanup interval set every 300.000000 seconds
sogo-mailcow_1       | Dec 28 16:01:27 sogod [54]: <0x0x562923734780[SOGoCache]> Using host(s) 'memcached' as server(s)
sogo-mailcow_1       | Dec 28 16:01:27 sogod [54]: [WARN] <0x0x7f6945e26820[WOxElemBuilder]> could not locate builders: WOxExtElemBuilder,WOxExtElemBuilder
sogo-mailcow_1       | Dec 28 16:01:27 sogod [54]: [ERROR] <0x0x562923a5c990[SOGoUserManager]> No authentication sources defined - nobody will be able to login. Check your defaults.
sogo-mailcow_1       | Dec 28 16:01:27 sogod [54]: [ERROR] <0x0x562923a4ec40[SOGoSQLUserProfile]> failed to acquire channel for URL: (null)

```

There is a `/var/lib/sogo/GNUstep/Defaults/sogod.plist` file in the container which seems to have the correct entries but I'm not sure if they have the correct format/are used correctly:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//GNUstep//DTD plist 0.9//EN" "http://www.gnustep.org/plist-0_9.xml">
<plist version="0.9">
<dict>
    <key>OCSAclURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_acl</string>
    <key>OCSCacheFolderURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_cache_folder</string>
    <key>OCSEMailAlarmsFolderURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_alarms_folder</string>
    <key>OCSFolderInfoURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_folder_info</string>
    <key>OCSSessionsFolderURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_sessions_folder</string>
    <key>OCSStoreURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_store</string>
    <key>SOGoProfileURL</key>
    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_user_profile</string>
    <key>SOGoTimeZone</key>
    <string>"Europe/Berlin"</string>
    <key>domains</key>
    <dict>
        <key>testdomain.de</key>
        <dict>
            <key>SOGoMailDomain</key>
            <string>testdomainpde</string>
            <key>SOGoUserSources</key>
            <array>
                <dict>
                    <key>MailFieldNames</key>
                    <array>
                        <string>aliases</string>
                        <string>ad_aliases</string>
                        <string>senderacl</string>
                    </array>
                    <key>KindFieldName</key>
                    <string>kind</string>
                    <key>MultipleBookingsFieldName</key>
                    <string>multiple_bookings</string>
                    <key>IMAPLoginFieldName</key>
                    <string>c_uid</string>
                    <key>canAuthenticate</key>
                    <string>YES</string>
                    <key>displayName</key>
                    <string>GAL</string>
                    <key>id</key>
                    <string>testdomain.de</string>
                    <key>isAddressBook</key>
                    <string>YES</string>
                    <key>type</key>
                    <string>sql</string>
                    <key>userPasswordAlgorithm</key>
                    <string>ssha256</string>
                    <key>viewURL</key>
                    <string>mysql://mailcow:myTestPw@mysql:3306/mailcow/sogo_view_testdomainpde</string>
                </dict>
            </array>
        </dict>
    </dict>
</dict>
</plist>
```

The file `/var/lib/sogo/GNUstep/Defaults/.lck/.GNUstepDefaults.lck` doesn't seem to exist in the container.

Any ideas?

PS: I thought packing stuff like that in issues here is meanwhile probably better then using https://github.com/andryyy/mailcow/issues/68 ;-)

**Comment by tehXor** [comment]
ooops, this may very well be a duplicate of https://github.com/andryyy/mailcow-dockerized/issues/2 ; checking if I find something usefull there...

**Comment by tehXor** [comment]
okay, so it is probably not a real duplicate of https://github.com/andryyy/mailcow-dockerized/issues/2, there was no password change in my case and to me it looks like `reconf-domains.sh` is writing the correct entries to `sogod.plist`...

**Comment by andryyy** [comment]
It is multi domain enabled now and some stuff changed. Just repull the images and recreate the containers. It will work then. 

I noted that stuff will probably change until an official announcement. :-)

I will only add a script to generate a config file later today. This should be the last change.

**Comment by andryyy** [comment]
Oh! I also changed to the new table format in SOGo. THAT is your problem. :/ Please try to reset the config files and export the user data. Or try to run the upgrade script SOGo includes. But I'm not sure this will work. I can help you recover your data in case it is very important.

**Comment by tehXor** [comment]
Maybe that is the problem, I did try to reuse the old DB (it's not very old though, probably 8 days or so). The config files should be nearly fresh (expect some postfix and dovecot additions I always use the current versions from this repo). 
Simply dropping the sogo tables shouldn't be a problem but would they get recreated properly? 
Dropping the whole DB and reimporting my test setup into the "mailcow-non-sogo-tables" would be slightly more effort but no problem either. However, using a completely fresh pull and changing nothing but the PWs in the mailcow.conf currently fails. The DB does not get initialized and I get a
```
SQLSTATE[HY000] [1045] Access denied for user 'mailcow'@'172.22.1.5' (using password: YES)
``` 
error. I'll probably have time to troubleshoot more in couple of hours. Could you point me to the SOGo upgrade script in the meantime if you find the time, so I can try that, too? However I'm still not sure if that's the problem, I don't see anything conflicting in the commits from the 22. Dec till now which would be SQL-related.

Edit: forget the initialization problem, the other testserver had outdated images. Still the re relevant SOGo upgrade script would be nice ;-)

**Comment by tehXor** [comment]
Still not sure what caused my problem but after some more trial and error it's working now.

The images are the same as earlier today (and up to date) and the DB scheme already was an exact match to the current scheme. I did drop all sogo views and they do get recreated automatically on a sogo restart. But immediately afterwards I still had the same problem. A couple of restarts later without changing anything else it worked though. So maybe it was related to the views or to the restart/recreate order or both.

Anyways, this most probably wasn't a general issue and thanks for all the effort you @andryyy are putting into this project! 👍

**Comment by andryyy** [comment]
I will stop making changes like these now. :-) Thanks for you report and sorry for not be very helpful.
