### ISSUE TITLE
rspamd: IO write error

### ISSUE THREAD

**Issue by hardoverflow** [mailcow/mailcow-dockerized#300]
In the logs of rspamd i always find the following error message:

`map; http_map_error: connection with http server terminated incorrectly: IO write error: Connection refused`

**Comment by rebek86** [comment]
Hi,
I have the same problem. Can someone help?

`rspamd-mailcow_1     | 2017-07-31 12:52:11 #11(controller) <oxhd99>; map; http_map_error: error reading http://nginx:8081/settings.php(172.22.1.251:8081): connection with http server terminated incorrectly: IO write error: Connection refused`

**Comment by andryyy** [comment]
Sounds like a firewall issue. If Nginx is up, it should be able to query it. What about "docker-compose exec php-fpm-mailcow ping nginx"?

**Comment by rebek86** [comment]
it is working...

`--- nginx ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.104/0.137/0.214 ms`

**Comment by rebek86** [comment]
After restarting the Docker host, everything works fine for me.

**Comment by cklabautermann** [comment]
@andryyy  I came over the same message right now and restarting whatever does not help at all:
`http_map_error: error reading http://nginx:8081/settings.php([fd4d:6169:6c63:6f77::c]:8081): connection with http server terminated incorrectly: IO write error: Connection refused`

BTW: I am on the latest mailcow release.
 ```
#docker-compose exec php-fpm-mailcow ping nginx
PING nginx (172.22.1.10): 56 data bytes
64 bytes from 172.22.1.10: seq=0 ttl=64 time=1.302 ms
64 bytes from 172.22.1.10: seq=1 ttl=64 time=0.178 ms
```
```
#docker-compose exec php-fpm-mailcow ping fd4d:6169:6c63:6f77::c
PING fd4d:6169:6c63:6f77::c (fd4d:6169:6c63:6f77::c): 56 data bytes
64 bytes from fd4d:6169:6c63:6f77::c: seq=0 ttl=64 time=0.166 ms
64 bytes from fd4d:6169:6c63:6f77::c: seq=1 ttl=64 time=0.212 ms

```
so the host nginx is reachable via v4 and v6 address.
Can you please help (and maybe reopen the issue)?

Thank you in advance
Claudio

**Comment by andryyy** [comment]
This is a network issue. You should also not run a ping6 from php-fpm-mailcow, when rspamd reports this error. Try to ping from rspamd-mailcow (install iputils-ping if missing) or even curl -6 to http://nginx:8081/settings.php

**Comment by cklabautermann** [comment]
Thanks, @andryyy I just took the line you mentioned above without thinking. My fault :-). 
Trying to ping, curl or wget I noticed that none of these binaries exist on the rspamd container.
Can you please point me at how to install packages in rspamd-mailcow? An 'apt install curl iputils-ping' didn´t do the trick.

**Comment by andryyy** [comment]
Try
docker-compose exec rspamd-mailcow /bin/bash
apt-get update
apt-get install curl
👍

**Comment by cklabautermann** [comment]
*shame on me* ;-) I missed the update. 
curl to v4 and v6 nginx:8081/settings.php works. 
I think the log entry occurred due to a docker restart. Maybe the nginx still wasn´t available when rspamd requested it.
Thanky you again @andryyy!

**Comment by andryyy** [comment]
Yes, that's possible.
Or PHP was dead for a sec?
You can run the command in a loop for a while.

**Comment by andryyy** [comment]
You can try:

```
while true; do if ! curl --connect-timeout 3 -m5 -s6 http://nginx:8081/settings.php > /dev/null; then echo ERROR; fi; sleep 1; done
```
