### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by PluginYML** [mailcow/mailcow-dockerized#3000]
If I run "docker-compose up -d"

it returns a error: https://hasteb.in/ufihipim.yaml

Please help

**Comment by SkazochnikZlodey** [comment]
Looks like issue with br-mailcow 
shutdown run containers with mailcow
execute:
$docker system prune -a -f 
It will delete unused networks and etc.
next:
$docker-compose pull
$docker compose up -d

**Comment by PluginYML** [comment]
> 
> 
> Looks like issue with br-mailcow
> shutdown run containers with mailcow
> execute:
> $docker system prune -a -f
> It will delete unused networks and etc.
> next:
> $docker-compose pull
> $docker compose up -d

Same error

**Comment by Braintelligence** [comment]
If you ignore the issue template, I'll ignore your issue 🤷‍♂
