### ISSUE TITLE
Need more  config futures.

### ISSUE THREAD

**Issue by SkazochnikZlodey** [mailcow/mailcow-dockerized#3004]
Hello All.

I want ask to make some changes and add some futures some of them minor some of them may take time to deploy.
1. Simple future:
  in generate_config.sh add please:
# Docker containers restart mode
# https://docs.docker.com/compose/compose-file/#restart
# no ; always ; on-failure ; unless-stopprestart: ${RESTART_MODE}ed ;
RESTART_MODE=always
 in docker-compose.yml
 change from :
  restart: .... 
to 
 restart: ${RESTART_MODE}
2.in generate_config.sh add please: 
   VOLUMES_ROOT_PATH
        example:  VOLUMES_ROOT_PATH=./
   and in top of script check availability/set(copy) ./data folder like for time zone.  
  in docker-compose.yml
   change from :
      ./data/
    to 
     ${VOLUMES_ROOT_PATH}/data/
 3. Add redis ip in generate_config.sh
     REDISIP=172.22.1.249
    and use REDISIP in code (data/Dockerfiles/netfilter/server.py):
         r = redis.StrictRedis(host=os.getenv('IPV4_NETWORK', '172.22.1') + '.249', decode_responses=True, port=6379, db=0)
   change to 
         r = redis.StrictRedis(host=os.getenv('REDISIP'), decode_responses=True, port=6379, db=0)
     need for external REDIS
  4. add databas(mysql) ip in generate_config.sh
      DATABASEIP=172.22.1.247 
   and use DATABASEIP  in code as host instead  of socket 
    need for external MYSQL

  5. Create start.sh to run project in docker swarm:
     example:
 # /bin/bash

mkdir -p /external/services/mail_server/{data,helper-scripts}
cp ./data /external/services/mails_server/data/postfix/custom.conf

cp ./helper-scripts /external/services/mails_server/helper-scripts
#echo "Create the overlay network that will be used for our stack (mailnetwork):"
docker network create --ip-range=172.22.1.0/24 --attachable --ipv6  --subnet fd4d:6169:6c63:6f77::/64 --driver=bridge mailcowdockerized_mailcow-network

echo Deploy the Mail_server Stack:

docker-compose pull

env $(cat .env | grep ^[A-Z] | xargs) docker stack deploy --compose-file mailserver-compose.yml mail_server

#docker-compose up -d 

echo Waiting 5 sec.
sleep 5

echo Stacks review:

docker stack ls

echo ..Done ?..

**Comment by andryyy** [comment]
We cannot change mailcow to fit your needs, that's not how it works. You need to change mailcow to fit _your_ needs. You can fork it and add your changes, to make it work with your environment.

The way you are trying to use it, will break mailcow in different ways, pretty sure that's how you also end up with an open relay over IPv6. netfilter-mailcow is completly useless. There is much, much more, that will not work anymore.

**Comment by andryyy** [comment]
I don't want to sound like a jerk, sorry. It has been discussed several times. There is currently no swarm config, that will not kill features, that are eseential. We cannot change the whole concept and layout for a semi-working swarm config. :( You can already use external SQL sockets with some workarounds. Redis would be nice in the future, too. That's something we can work on, yes. :) Let's make external Redis work.

**Comment by SkazochnikZlodey** [comment]
Thank for information.  What kind of features can be killed by swarm ? Maybe i make fork and start work on swarm edition.  But i `ll need help with connections in code to mysql by hostname (or to external mysql).
