### ISSUE TITLE
Get complete backup

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3006]
I use mailcow dockerized for months and also get backup in several days. but [backup] (https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/) in this link is just incremental. how can i get a complete backup of all mail from the beginning?

**Comment by roelofz** [comment]
Hi,

As I have understood the documentation, and also looking at the date folders (look at the vmail backup file for instance), the backups are NOT incremental, but full. For me reason to remove older date folders to save diskspace (they are backupped beforehand to a cloud backup, so it is save to remove them locally).

I haven't tested restoring, but assume only one date folder is needed to complete a full restore.

**Comment by timo-reymann** [comment]
@mahlarht, @roelofz 
one backup is enough to restore everyhting. Every backup contains all data you specified creating the backup.
So if you specify all you should get a full backup. I am doing this that way quite some time now, and had to use the backup several times for migration to new server etc. and it works well.
