### ISSUE TITLE
Cannot login to admin after install

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#301]
Hello,

I just installed the dockerized mailcow but I couldn't login using admin/moohoo.

I had to reset the password using ./mailcow-reset-admin.sh to get through it.

**Comment by RobinFlikkema** [comment]
I also had to do this as the default admin:moohoo didn't work by default

**Comment by andryyy** [comment]
Oh, argh, sorry. It is fixed. :-)
