### ISSUE TITLE
Mx backup server - avoiding backscatter

### ISSUE THREAD

**Issue by SimplyCorbett** [mailcow/mailcow-dockerized#3014]
I want to setup a couple mx servers using both postfix and mailcow. How would I go about syncing the email accounts between the servers to avoid backscatter?

Iirc mailcow uses MySQL and I'd prefer not to use MySQL on the postfix servers.

**Comment by ntimo** [comment]
Hello @tsalwierz,
HA setups for mailcow are out of scope for this project. You would need to make redis and mariadb HA as well as to configure dovecot for vmail replication. I would simply suggest that you setup a secondary mx as a fallback backup mx that caches emails if you main mx is down and then sends them to the main mx once its back online again.

**Comment by tsalwierz** [comment]
Alright. And how do you go about configuring a mx server in general with mailcow, as I have both relay all domains and mx selected and mail is not being delivered.
