### ISSUE TITLE
[feature request] allow arbitrary subdomain and subpath for hosting the web applications (mailcow UI, sogo, rspamd)

### ISSUE THREAD

**Issue by karthanistyr** [mailcow/mailcow-dockerized#3015]
**Is your feature request related to a problem? Please describe.**
At the moment, it seems only possible to serve the Mailcow UI at the root of $MAILCOW_HOSTNAME, e.g. `https://mail.mydomain.com/`.

As I host several services on my server, I have come to place sensitive admin web panels under a specific path in a secure apache zone. For mailcow it could have looked like e.g. `admin.mydomain.com/secure/mailcow`, where `admin.mydomain.com/secure` enforces strict authentication rules.

$MAILCOW_HOSTNAME should still be like mail.mydomain.com for all emailing purposes (not web).

With some apache tweaking I can make it somewhat work but there doesn't seem to be any satisfactory solution yet for having Mailcow UI under a subpath.

**Describe the solution you'd like**
A configuration setting allowing to specify the path leading to the mailcow UI application.

Grafana (the web graphing software) solves it in the config: https://grafana.com/docs/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-grafana

Such settings would be modifying all URLs inside the mailcow UI to accommodate for the subpath.

Caveat: SOGo and rspamd; both these applications should be able to be configured to be served under arbitrary subdomains/subpaths too.

**Comment by tlaguz** [comment]
+1 for this. Exactly my issue here.
Changing path using reverse proxy doesn't work because mailcow uses absolute paths everywhere. Why is that?

**Comment by andryyy** [comment]
It is not a sensitive admin panel. It is a portal for MAILBOX USERS, admins, domain admins etc. This is getting a bit annoying, to be honest.

It is the mailcow portal. People change their mailcow stuff there. It is not a "sensitive admin panel". If you want a jumping point to your webmailer (which is an app in your mailcow), you can check the docs and create a custom site to redirect to SOGo.
