### ISSUE TITLE
Integrate PLAIN-MD5 authentication to ease migration from old servers

### ISSUE THREAD

**Issue by evilMouse** [mailcow/mailcow-dockerized#3017]
**Is your feature request related to a problem? Please describe.**
I have to migrate users from an old server, where passwords are stored in plain 32 characters hexadecimal MD5. I've created users through API, and migrated passwords with SQL. Now they look like:
{PLAIN-MD5}058ef3a0d1812383bdad58552be0eb44

I can login to SoGo, but can't to Mailcow UI

**Describe the solution you'd like**
I've read #2600 so I tried to implement PLAIN-MD5 verification and updated verify_hash with:

  elseif (preg_match('/^{PLAIN-MD5}/i', $hash)) {
    $hash = preg_replace('/^{PLAIN-MD5}/i', '', $hash);
    if (md5($password) == $hash) {
      return true;
    }
  }

It seems to work, so it would be nice to include this in future updates.

**Comment by andryyy** [comment]
Thanks, will integrate it.

**Comment by evilMouse** [comment]
I see it's not integrated after last update. Is this for a reason?

**Comment by andryyy** [comment]
https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.inc.php#L389

It is still there. :)

**Comment by evilMouse** [comment]
Oh, I feel stupid. I just looked after last if with MD5-CRYPT.

**Comment by andryyy** [comment]
No problem!
