### ISSUE TITLE
Mailcow UI font is not multilingual friendly.

### ISSUE THREAD

**Issue by evilMouse** [mailcow/mailcow-dockerized#3018]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Some national (accented) characters in Mailcow UI look distinctly different than non-accented characters.
SoGo is not affected.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Just change UI language to Czech or Polish - you will see that accented characters are notably different: a little bolder and bigger.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Hyper-V |
| Server/VM specifications (Memory, CPU Cores) | 4GB,2 |
| Docker Version (`docker version`) |  18.09.1 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | No |

As a side note: I'd like to contribute to Polish translation. How can I do this?

**Comment by andryyy** [comment]
Hi, thank you. I will try to fix that. :)

You can find the lang files in data/web/lang.

**Comment by andryyy** [comment]
Any idea for an alternative font, free to use, compatible etc?

**Comment by evilMouse** [comment]
I'm not much UI guy, but maybe the one used in SOGo would be OK?

**Comment by evilMouse** [comment]
> You can find the lang files in data/web/lang.

I know, I've already updated mine. :)
I'm asking if I should just paste new lines here or submit them somewhere (I'm also new to github :) ).

**Comment by andryyy** [comment]
You should be able to edit the file on Github browsing the repo. It will 
create a PR then.

------ Originalnachricht ------
Von: "evilMouse" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Comment" 
<comment@noreply.github.com>
Gesendet: 09.10.2019 12:47:32
Betreff: Re: [mailcow/mailcow-dockerized] Mailcow UI font is not 
multilingual friendly. (#3018)

**Comment by evilMouse** [comment]
I've created PR.
Two things: 
- I cannot find "Check against haveibeenpwned.com" in lang.en. Is it image?
- Is it possible to localize documentation under "[Show configuration guides for email clients and smartphones]"?

**Comment by heavygale** [comment]
"Check against haveibeenpwned.com" is currently [hard coded in JavaScript](https://github.com/mailcow/mailcow-dockerized/blob/c3be04560b9026770a27233a73b95c44b6920a15/data/web/js/build/014-mailcow.js#L70). We need to change the way this textbox is added to the page, so we can translate it.

For the documentation, there's currently no translation implemented. I don't know what might be the way to go for translation with mkdocs.

**Comment by evilMouse** [comment]
> Any idea for an alternative font, free to use, compatible etc?

OK, my colleagues told me to use Roboto or Open Sans from Google Fonts - they are clean, multilingual and free. I like second one better - it has more air.

**Comment by evilMouse** [comment]
> "Check against haveibeenpwned.com" is currently [hard coded in JavaScript](https://github.com/mailcow/mailcow-dockerized/blob/c3be04560b9026770a27233a73b95c44b6920a15/data/web/js/build/014-mailcow.js#L70). We need to change the way this textbox is added to the page, so we can translate it.

Is it the same for "All domains" in combobox in Mailboxes view?
> 
> For the documentation, there's currently no translation implemented. I don't know what might be the way to go for translation with mkdocs.

I would happily translate it to Polish if you find a way to make it multilingual.

**Comment by mamash** [comment]
What OS/browser are you using? Czech chars display just fine for me on MacOS (any browser really).

**Comment by evilMouse** [comment]
@mamash 
Sorry, I missed your reply.
It's Windows Firefox/Edge

**Comment by mamash** [comment]
I can reproduce this on Edge/W10. However, I believe this has nothing to do with the font selection, as [PT Sans](https://fonts.google.com/specimen/PT+Sans) seems to have full Unicode support. Maybe not all the files have been bundled in data/web/fonts or Windows/Edge does/needs something funny regarding embedded fonts?

**Comment by andryyy** [comment]
Looks good in Firefox:

![image](https://user-images.githubusercontent.com/2972950/67288387-2b205600-f4dd-11e9-98aa-0bae8e6514ef.png)

And Edge:

![image](https://user-images.githubusercontent.com/2972950/67288418-3d01f900-f4dd-11e9-942a-5b54e3960295.png)

Can you give me an example?

**Comment by mamash** [comment]
> Looks good in Firefox:
> 

Actually, it's not OK. See how the accented 'z' is bigger? It means that Firefox opted to pick a fallback font for this char.

**Comment by andryyy** [comment]
Ah, I see, thanks.

**Comment by andryyy** [comment]
I think we would need to switch fonts to cover these chars.

**Comment by mamash** [comment]
> I think we would need to switch fonts to cover these chars.

I don't know where did you get the PT Sans fonts as included with mailcow, but when I download PT Sans e.g. from Google Fonts, they work for me fine in Czech & Russian.

<img width="272" alt="test" src="https://user-images.githubusercontent.com/228279/67290259-2ad58a00-f4e0-11e9-9980-41d7dc784043.png">

**Comment by andryyy** [comment]
Do you have woff files?

**Comment by mamash** [comment]
> Do you have woff files?

No, but looks like you can download here: https://www.fontsquirrel.com/fonts/pt-sans

Also found [here](https://github.com/sawmac/css_mm_4e/tree/master/06/css/fonts).

Just don't have time to test today.

**Comment by andryyy** [comment]
Hm, are these different from those we already use? Perhaps I only made a mistake in the css?

**Comment by mamash** [comment]
The problem is that the PT Sans fonts bundled with Mailcow do not have the "Latin Extended" language support included (Cyrillic support is a different subset). I did a brief test using the [Google Fonts entry](https://fonts.google.com/specimen/PT+Sans) for PT Sans: configured the font with the "Latin Extended" support included, then converted to WOFF using the [first online converter I found](https://andrewsun.com/tools/woffer-woff-font-converter/). That fixed the issue in both Edge and Firefox under Windows 10.

Even macOS knows the difference, as when you preview the TTF variant, it will show some extended characters in the preview (e.g. 'č' instead of 'c') for a Latin Extended supporting font, and just plain ASCII chars for the one bundled with Mailcow. Yet the browser (Safari, Firefox, Chrome...) is happy to use the plain font and renders the extended characters just fine.

You can confirm by using the Firefox Inspect Element feature. When you inspect header rendered with PT Sans, the "Fonts" tab of the inspect pane should only list "PT Sans" under fonts used. On Windows, Arial also shows up, and it shouldn't.

**Comment by andryyy** [comment]
Cool, could you please create a PR for that?
