### ISSUE TITLE
API: List mailboxes for a single given domain

### ISSUE THREAD

**Issue by nahanil** [mailcow/mailcow-dockerized#3020]
**Is your feature request related to a problem? Please describe.**
I want to be able to get a list of all mail accounts for a _single_ domain.

**Describe the solution you'd like**
Perhaps something like [what happens around here (json_api.php#L566)](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/json_api.php#L566) but which doesn't loop through all domains in the system.

**Additional context**
I'm happy to try hacking this into the existing API if it's something you're interested in. If this is already a feature I've overlooked sorry for being annoying!

**Comment by MAGICCC** [comment]
Looks you can only see all mailboxes by using GET on `/api/v1/get/mailbox/all`
But you could write some script to extract 'usernames' ending with example.org


> I'm happy to try hacking this into the existing API if it's something you're interested in. If this is already a feature I've overlooked sorry for being annoying!

Sure would be nice of course!
You can always make a PR

**Comment by andryyy** [comment]
Yes. A nice and universal way, that can be easily expanded over the API would be nice. :) 

A hacky workaround not so much. :(

**Comment by nahanil** [comment]
Not sure if I'm way off track with this, but asking here before making a PR
https://github.com/nahanil/mailcow-dockerized/commit/093a24874f550529c8db6b098766124dcc146f8f?diff=split

**Comment by nahanil** [comment]
🤷‍♂
