### ISSUE TITLE
Quirk in address rewriting UI? the counters of bcc and recipient maps are always the same.

### ISSUE THREAD

**Issue by jol64** [mailcow/mailcow-dockerized#3022]
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

The counters of bcc and recipient maps are always the same.

Reproduction:
in mailcow webui for administration, configuration / mail setup, address rewriting I defined
3 (sender) bccs and 2 recipient rewrites. 
Then clear cache, visit the page again, then the small white-on-black numbers both read 2. When I refresh the bcc maps using the button on the same line, both read 3, when I refresh the recipient maps, it is back to 2.
To me looks like a quirk in the UI using the same variable for both counters.

- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS |
| Is Apparmor, SELinux or similar active? | apparmor is active |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Hyper-V 2019 |
| Server/VM specifications (Memory, CPU Cores) | host: 32GB, mailcow roundabout 8GB but dynamic, 4 virtual cores |
| Docker Version (`docker version`) |  18.06.1-ce, build e68fc7a |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) |  |

Further notes:
 - please advise whether this is relevant to the issue.
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Merci, can replicate and will fix. :)
