### ISSUE TITLE
Failed migration from Dovecot server

### ISSUE THREAD

**Issue by vooxo** [mailcow/mailcow-dockerized#3025]
Hello,

Hello, I'm trying to migrate from an older cPanel server to the new mailcow-dockerized - but can't make it to work.

I've done the following:

1. copied emails from the old server; directory structure is as described here: https://www.thecpaneladmin.com/understanding-courier-imap-and-maildir/
2. put files to:
3. `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/`
so that the structure is `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/example.com/username`
4. chown'd everything to 5000:5000
5. ran `docker-compose exec dovecot-mailcow doveadm quota recalc -A`
7. restarted docker

Nothing works...

**Question 1:**
How do I actually associate the password data from old server's `/home/username/etc/shadow` ?

**Question 2:**
Where do I get private and public`*.pem` keys which are required in the [encrypt](https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-mail-crypt/) script ?

What am I missing?

Thank you!

**Comment by evilMouse** [comment]
I'm afraid nothing works is too generic. You have to be more specific. 

I'm just migrating old server and it works. **But** I've created domains in Mailcow, I've added users through API and I've only migrated e-mails from Cur directories.

https://mailcow.docs.apiary.io/#reference/mailboxes/create-mailbox/create-mailbox

**Q1**: You have to update passwords in database adding hash type in the beginning. Like: {PLAIN-MD5}058ef3a0d1812383bdad58552be0eb44

**Q2**: You **don't have to** encrypt old e-mails - they are visible without it.

**Comment by vooxo** [comment]
> I've added users through API

Using what passwords?

> Q1: You have to update passwords in database adding hash type in the beginning. Like: {PLAIN-MD5}058ef3a0d1812383bdad58552be0eb44

So, how have you actually transferred passwords from the `/home/username/etc/shadow` file to the new server and associated them with users?

**Comment by evilMouse** [comment]
> 
> 
> > I've added users through API
> 
> Using what passwords?

Just the same generic password for everyone - it's overwritten later.
> 
> > Q1: You have to update passwords in database adding hash type in the beginning. Like: {PLAIN-MD5}058ef3a0d1812383bdad58552be0eb44
> 
> So, how have you actually transferred passwords from the `/home/username/etc/shadow` file to the new server and associated them with users?

I had my passwords in the old mail server database already, but I think it doesn't really matter - you can generate update script from a file.

**Comment by vooxo** [comment]
Thank you for these tips, I'll try it out.
