### ISSUE TITLE
Domain-Administrator kann nicht gelöscht werden

### ISSUE THREAD

**Issue by flo1212** [mailcow/mailcow-dockerized#3027]
Wenn eine Domain einem Domain-Administrator zugewiesen wurde und dann die Domain gelöscht wird, wird der Domain-Administrator nicht mehr in der mailcow UI angezeigt. Man kann ihn also auch nicht mehr löschen, aber er existiert dennoch. Man kann den Benutzrname nicht erneut verwenden, weil er noch existiert. Auch kann man sich sogar noch einloggen.

Dies scheint mir ein Bug zu sein, denn es gibt keine nun keine Möglichkeit mehr den Domain-Administrator zu löschen.

**Comment by andryyy** [comment]
Hi,  danke ist gefixt.

**Comment by flo1212** [comment]
Ich habe es geprüft.  Wenn nun eine Mailbox-Domain gelöscht wird, kann sich der "leere" Domain-Admin nicht mehr einloggen, aber der Datenbankeintrag des Domain-Admin gibt es wohl noch. 
Man kann zwar jetzt noch mal denselben Domain-Admin wieder einrichten, aber es kommt diese Fehlermeldung: (K00001 ist der Benutzername des Domain-Admins)

![err](https://user-images.githubusercontent.com/16955926/66631885-801fba80-ec07-11e9-843f-8734ebaf7fe0.png)

Beim Löschen der Domain sollte auch der zugehörige Domain-Admin tatsächlich entfernt werden (sofern er keine weiteren Domains verwaltet).
