### ISSUE TITLE
mobileconfig.php not accessible

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#3029]
Hi there, i am unable to use https://${MAILCOW_HOSTNAME}/mobileconfig.php as per documentation, whenever i access that file from mobile i get redirected to the normal mailcowUI login window and from there nothing happens. should i set something in the config in order to allow that config page? 
Thank you in advance

**Comment by mkapra** [comment]
Please login to your webUI and then follow the link: "[Show configuration guides for email clients and smartphones]".
There are some steps between the Login and the Download of the Profile.
When you only call /mobileconfig.php the server doesn't know for which user you'd like to have the configuration profile.

**Comment by lucianlazar1983** [comment]
Thank you, but after login nothing happens. I will investigate further from logs.

**Comment by mkapra** [comment]
user_verbosity = 10

What do you mean with 'nothing happens'?

**Comment by lucianlazar1983** [comment]
I mean what I wrote before, after login I see the default index page like I would normally want to login to mailcow. mailcow. php simply redirects to index

**Comment by mkapra** [comment]
And what happens when you log in?

**Comment by mkapra** [comment]
Directly calling mobileconfig.php is not possible.

**Comment by lucianlazar1983** [comment]
This is what happens. Nothing. Please see screenshot. 
![Screenshot_20191011-195626_Chrome](https://user-images.githubusercontent.com/3727896/66669979-55fae680-ec61-11e9-90ec-564fa1f86af9.jpg)

**Comment by lucianlazar1983** [comment]
> Directly calling mobileconfig.php is not possible.

OK, Then maybe I'm stupid but I can't figure it out how  should I do.

**Comment by mkapra** [comment]
you cannot call this option as administrator. You have to do it with the user you'd like to configure on your device.

**Comment by lucianlazar1983** [comment]
Aha! So that was the problem. thank you, you clarified well. Can I suggest adding this info on the documentation? Thanks again

**Comment by mkapra** [comment]
Why should it be in the documentation? The admin user has no mail address so it doesn't need to get configured on a device.

**Comment by andryyy** [comment]
Should be fixed
