### ISSUE TITLE
extend smarthost (SMTP-relay) configuration for local recipients

### ISSUE THREAD

**Issue by Dentlonistka** [mailcow/mailcow-dockerized#3032]
**Is your feature request related to a problem? Please describe.**
I use ciphermail for encryption and signing. Therefore i configured ciphermail as smarthost (smtp-relay) for my domain. Everything works well for outgoing mails / external recipients. If i send mails to recipients, which are on my cow too, mails will be delivered directly, without useing the smarthost.

**Describe the solution you'd like**
I'd like to have the option, sending mails for local recipients also via smarthost (SMTP-relay).

**Additional context**
Is there a workaround i didn't see?

**Comment by andryyy** [comment]
That's a question you should better ask on Telegram or IRC. :)

How did you setup the smarthost? Via UI?

**Comment by Dentlonistka** [comment]
Hey @andryyy, thanks a lot for your reply. 

Yes, i setup the smarthost via UI and configured the smarthost (smtp-Server) under the Sender-dependent transports section. Last i set the sender-dependent transports option in the domain-config. 

Cheers!

**Comment by mkuron** [comment]
Postfix will always deliver messages to local domains locally. This cannot be disabled. #630 discusses essentially the same problem and I suggested a workaround there that consists of modifying Mailcow to run two Postfix instances side-by-side.
