### ISSUE TITLE
smtpd_tls_mandatory_protocols multiple times defined

### ISSUE THREAD

**Issue by madic-creates** [mailcow/mailcow-dockerized#3033]
- [ X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

In the postfix configuration smtpd_tls_mandatory_protocols is defined in main.cf and master.cf. This makes it impossibel to overwrite smtpd_tls_mandatory_protocols via extras.cf because it gets overwritten for port 465 and 587.

Is there a reason why smtpd_tls_mandatory_protocols is also defined in master.cf?

**Comment by andryyy** [comment]
Yes, that's what we want. 

smtpd services, that only allow for authenticated users, should have a more compatible setting to not exclude too many older clients. 

I will try to change the merge behavior in the future and perhaps this will include changes to master.cf as well.

**Comment by madic-creates** [comment]
So this is by design. Than I will close the issue. Thank you for the clarification
