### ISSUE TITLE
DNS Lookup Check not working correct

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#3034]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
For domains there is the option to check the DNS records. So I checked the records and there are some entries which doesn't work. For example this entry is marked as missing:
```
MY_IP.in-addr.arpa | PTR | MY_DOMAIN |  
```
So I tested the following:
```
Server:		172.20.10.1
Address:	172.20.10.1#53

Non-authoritative answer:
MY_IP.in-addr.arpa	name = MY_DOMAIN
```
So why is the manual verification successful and the automatic in the webUI not? I set the PTR entry already a few weeks ago so caching cannot be the problem.
Maybe there's something going wrong in the script?

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
Explained above.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Proxmox |
| Server/VM specifications (Memory, CPU Cores) | 8 cores, 30GB RAM |
| Docker Version (`docker version`) | 19.03.3 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | |

**Comment by andryyy** [comment]
I have no idea what you tested. 

I have no idea which IP is checked for its PTR in the UI. 

If some checks fail, there might be a firewall issue. It should not detect the Docker gateway as WAN IP, does it? Don't know about your firewall rules. 

Please show exactly which checks fail, what they return and which exact command you run to check the PTR.

**Comment by mkapra** [comment]
@andryyy 
First question:
The webUI shows the configured public IP which gets checked (MY_IP.in-addr.arpa).

From internal to external there aren't any firewall rules. Only from external to internal.

Last question: I tried it with nslookup:
```
nslookup MY_IP_ADDRESS
```

**Comment by andryyy** [comment]
The correct PTR would be your mailcow hostname (fqdn), not a domain name. Perhaps that's the issue? :)

Which firewall?

**Comment by mkapra** [comment]
@andryyy No I've set the PTR to the mailcow hostname.
My firewall is 'ufw'

**Comment by Adorfer** [comment]
If understand correct: the issue is more like 
"DNS lookup on docker hosts fails, for the fqdn of the machine's reverse-lookup"?

if this is really the case: 
Are we discussing a randomly weired testing case or
 is this just a method to hide the fqdn of that host in a public ticket (here)?

**Comment by mkapra** [comment]
Sorry for the late response. I've been busy the last days.
No idea why but now it is working.
