### ISSUE TITLE
Problem reply icon Outlook app Android using Exchange

### ISSUE THREAD

**Issue by silverblade** [mailcow/mailcow-dockerized#3035]
Hello,
I have this problem, I have more phones with android and I always have this problem. I install Outlook and configure Exchange for my mailbox, all mails, even those to which I have not answered are marked as answers. Is it something that was reported? Thank you

**Comment by andryyy** [comment]
Hi, did you get in contact with SOGo about this? :) I have not seen this happening, but they might be interested in this: https://sogo.nu/bugs/my_view_page.php
