### ISSUE TITLE
nc: occ cmd, how?

### ISSUE THREAD

**Issue by BlackWolfDEsign** [mailcow/mailcow-dockerized#3040]
Hi I use your nextcloud. I manually updated it to version 17. Now I have to do the following:

`occ db: add-missing-indices`

My question: how can I run this cmd? Which container is it?

**Comment by andryyy** [comment]
```
docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/occ db:add-missing-indices"
```

**Comment by BlackWolfDEsign** [comment]
it was still necessary to adjust the chmod for occ ;)

**Comment by andryyy** [comment]
Thanks, modified the command, should work now. :)
