### ISSUE TITLE
nc: after update(16 to 17) X-Frame-Options HTTP is not configured to match "SAMEORIGIN"

### ISSUE THREAD

**Issue by BlackWolfDEsign** [mailcow/mailcow-dockerized#3043]
Hi iam again... ;)

after update, i get this warning from nc:
`The "X-Frame Options" HTTP header is not configured to match "SAMEORIGIN". This is a potential security risk and it is recommended that you change this setting.`

i changed something in the data/assets/nextcloud/nextcloud.config.
my changes: 
```
server {
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Download-Options "noopen" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Permitted-Cross-Domain-Policies "none" always;
    add_header X-Robots-Tag "none" always;
    add_header X-XSS-Protection "1; mode=block" always;

location ~ ^\/nextcloud\/.+[^\/]\.(?:css|js|woff2?|svg|gif|map)$ {
            try_files $uri /nextcloud/index.php$request_uri;
            add_header Cache-Control "public, max-age=15778463";
            add_header Referrer-Policy "no-referrer" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-Download-Options "noopen" always;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Permitted-Cross-Domain-Policies "none" always;
            add_header X-Robots-Tag "none" always;
            add_header X-XSS-Protection "1; mode=block" always;
            access_log off;
        }
```
the error still exists...
whats wrong?

edit: 
mailcow and nextcloud running behind a reverse proxy

**Comment by andryyy** [comment]
Please use Telegram or IRC for these kind of questions. :)

You can also remove "X-Frame-Options" from the site config (as we do ourself in `data/assets/nextcloud/nextcloud.conf`) to let NC add this header. If you don't you end up with duplicate X-Frame-Options and NC spawns that fancy error.

**Comment by BlackWolfDEsign** [comment]
OH sry! Telegram and IRC exists? Nice, sry my bad :(  It will not happen again.
