### ISSUE TITLE
Quarantine Messagesize?

### ISSUE THREAD

**Issue by AndyX90** [mailcow/mailcow-dockerized#3047]
**Is your feature request related to a problem? Please describe.**
Hi, as i read here:
https://github.com/mailcow/mailcow-dockerized/blob/09d12c8f7ed592871f3a34595126ff5f257d1938/data/conf/rspamd/meta_exporter/pipe.php#L2

and here:
https://github.com/mailcow/mailcow-dockerized/blob/09d12c8f7ed592871f3a34595126ff5f257d1938/data/conf/nginx/meta_exporter.conf#L8

The messagesize for Quarantine is limited to 10MB.
Can someone please explain why this is fixed to this size?

**Describe the solution you'd like**
It would be nice if the messagesize for quarantine-objects could be adjustable in the Mailcow-UI.

By the way, thanks for this awesome project!❤️

EDIT: I see that it is already adjustable in the UI and the Code:
https://github.com/mailcow/mailcow-dockerized/blob/09d12c8f7ed592871f3a34595126ff5f257d1938/data/conf/rspamd/meta_exporter/pipe.php#L67-L70
uses it.
But the startcomment confuses me...

**Comment by AndyX90** [comment]
Sorry, stupid...

**Comment by andryyy** [comment]
No worries. :)
