### ISSUE TITLE
DNS Problem

### ISSUE THREAD

**Issue by sinuscosinustan** [mailcow/mailcow-dockerized#305]
Hi Guys,

I've currently the problem, that I can't get any mails, because Postfix can't get the hostname.

Error:
NOQUEUE: reject: RCPT from unknown[CENSCORED]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [CENSCORED]; from= to= proto=ESMTP helo=

How can I fix it?

Regards
Tom S.

**Comment by chriscroome** [comment]
Have you set up reverse DNS so your IP address resolves to your domain name?

**Comment by sinuscosinustan** [comment]
sure.

**Comment by RobinFlikkema** [comment]
Well, the error states that the receiving mailserver couldn't find a reverse DNS for your IP. Are you sure it is setup correctly, and have you tried verifying your reverse DNS by using a website like https://db-ip.com/

**Comment by sinuscosinustan** [comment]
I tested it and the reverse dns is setted.
I sended an email to my mailserver and the same (It was a GMAIL.com address)

**Comment by RobinFlikkema** [comment]
I'm sorry but I do not get what you are saying.

The receiving mailserver is checking the PTR record which is associated with your IP-address. And it cannot find that PTR record. Therefore it rejects your email.

**Comment by Braintelligence** [comment]
Go here: https://remote.12dt.com/
Check if **the IP address of your mail server** shows your mailcow domain as reverse dns lookup.

**Comment by RobinFlikkema** [comment]
Also, this problem also occurs when the EHLO/HELO is different than the PTR

**Comment by etique57** [comment]
Hello,

I think I see the same behavior. To me it seems that the POSTFIX sitting in the mailcow docker is unable to perform any DNS related query.

Here's what I get when I telnet my mailcow postfix from internet:

> 450 4.7.1 Client host rejected: cannot find your reverse hostname, [212.47.xxx.yyy]

Of course, the reverse dns of the server 212.47.xxx.yyy is properly setup.

Also, from the mailcow postfix logs:

> warning: dnsblog_query: lookup error for DNS query 134.227.20.64.wl.mailspike.net: Host or domain name not found. Name service error for name=134.227.20.64.wl.mailspike.net type=A: Host not found, try again

I'm running mailcow from a 16.04 Ubuntu installation.

**Comment by etique57** [comment]
Another proof from a test mail sent from gmail (which is properly configured :))

> Jun  4 10:20:59 myserver postfix/smtpd[430]: NOQUEUE: reject: RCPT from unknown[209.85.218.45]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [209.85.218.45]; from=<dominique.xyz@gmail.com> to=<domi@myserver.net> proto=ESMTP helo=<mail-oi0-f45.google.com>
> Jun  4 10:20:59 myserver postfix/smtpd[430]: disconnect from unknown[209.85.218.45] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7

**Comment by andryyy** [comment]
When the resolver fails, we need logs from bind, not Postfix. I can show you logs with a proper resolving Postfix. :)

I think some IPs are blacklisted, that's the only reason that comes to my mind,

**Comment by andryyy** [comment]
So if it works when you add a forwarder to your bind config and it works, you may be (!) blocked by the root-servers. :/

**Comment by etique57** [comment]
ah ok I didn't notice it was using bind and didn't do anything from that point of view.

How can I access the logs from bind?

Essentially: I didn't add a "forwarder" to my bind config, how would I do that?

Do I need to nat forward the 53 port through my router?

**Comment by andryyy** [comment]
docker-compose logs -f bind9-mailcow

Or even better, change docker-compose.yml =>

```
...
    bind9-mailcow:
      ...
      command: "named -c /etc/bind/named.conf -g -u named -d 4"
      ...
```

Run docker-compose up -d afterwards + check the logs.

**Comment by etique57** [comment]
ok, done.

It's pretty verbose, what should I look for?

I think the problem is that the bind requests are not forwarded to our router DNS server.

I see a lot of failed DNSSEC queries.

**Comment by etique57** [comment]
Working!!

Needed to add a forwarders in the options tag:

```
        forwarders {
                192.168.0.1;
        };
```

**Comment by andryyy** [comment]
Well, you need to show your logs...

A forwarder or especially a public resolver will result in non-working blacklist lookups due to rate limits.

**Comment by etique57** [comment]
can I send them directly to you?
