### ISSUE TITLE
Nextcloud Authentication Failure

### ISSUE THREAD

**Issue by neilfrndes** [mailcow/mailcow-dockerized#3051]
I setup nexcloud using the helper script. According to this reply: https://github.com/mailcow/mailcow-dockerized/issues/1626#issuecomment-410003112 nextcloud is supposed to authenticate using mailcow. However, all my authentication attempts using a mailcow username and password fail. I could not find any documentation for authentication to troubleshoot the issue.

**Comment by andryyy** [comment]
It is disabled by default. You can install and  configure the external users plugin to use IMAP as authenticator. 

I will probably write an extension for mailcow in the future...

**Comment by neilfrndes** [comment]
Great, thank you!

**Comment by mritzmann** [comment]
@neilfrndes As a hint: https://github.com/mailcow/mailcow-dockerized/issues/3046#issuecomment-543700766
