### ISSUE TITLE
Calendar in RC

### ISSUE THREAD

**Issue by xFilosofx** [mailcow/mailcow-dockerized#3056]
**Is your feature request related to a problem? Please describe.**
I use mailcow with a roundcube and would like to see a calendar and tasks in it. Sogo does not suit my users on UI and the lack of a context menu.

**Describe the solution you'd like**
Add backward compatibility with kolab plugins for calendar and tasks in the roundcoube. Or any another plugins with this functionality.

**Additional context**
If Sogo has the ability to add a right-click context menu or the ability to install themes, this would also solve the problem.

**Comment by mkuron** [comment]
The only CalDAV plugin for Roundcube is https://github.com/texxasrulez/caldav_calendar, and my experience with that one is rather mixed. Stability wasn‘t particularly good. So there is no good way to get syncable calendars into Roundcube.

**Comment by xatage** [comment]
What about this one (though I didn't test it)?
https://github.com/Offerel/roundcube_caldavzap
