### ISSUE TITLE
Moving to subfolder by tags doesn't work

### ISSUE THREAD

**Issue by vbrandl** [mailcow/mailcow-dockerized#306]
Hi
I just installed mailcow and sending and receiving mails works fine. Now I want to use tagging into subfolders by using different aliases. So I created some aliases, e.g. `me+testtagging@domain.tld` and tried the feature by sending an email to the newly created alias. The mail appeared in my inbox but it wasn't copied into the corresponding subfolder.
Am I missing anything here?

**Comment by andryyy** [comment]
Hi,
You don't create that alias. me@domain.tld must be a mailbox, the tag is then added by the sender. It must not be an alias address.

**Comment by vbrandl** [comment]
Ah thank you very much. I somehow didn't get that from the documentation. It is working now.

**Comment by andryyy** [comment]
I was actually wondering what would happen if that alias exists. So you did me a favor! :)

**Comment by vbrandl** [comment]
Is there a way to flag specific tags as spam or drop these mails? I'm thinking of creating an alias `register@domain.tld` and use `register+<service>@domain.tld` for each service so if one of them sells or "loses" my email address, I can see who it was and eventually just flag them as spam. Another idea would be to create an actual alias for the specific tag I want to flag as spam and send it to a sinkhole mailbox since the alias overwrites the tag. But staying in the same mailbox and flagging some tags as spam would be nicer.

**Comment by Braintelligence** [comment]
I think you could use a filter in SOGo for this.

EDIT: You could combine the subject tagging and subject filter.
