### ISSUE TITLE
Autoconfig for email accounts on other domains

### ISSUE THREAD

**Issue by SagnikSRHUSE** [mailcow/mailcow-dockerized#3060]
Let's say I have my mailcow hosted on mail.xyz.net and I have xyz.net and abc.net on my mailcow. Now for email@xyz.net, it uses the server mail.xyz.net, and it gets a valid certificate. 

But for the email abc@abc.net, it tries to use mail.abc.net, which either doesn't exist, or is just a CNAME to mail.xyz.net. How should this be ideally dealt with/ or is there any option in mailcow to change this behaviour and have it autoconfig to only mail.xyz.net for all domains?

**Comment by andryyy** [comment]
Autoconfig always and only uses MAILCOW_HOSTNAME

Your autoconfig is not working then _or_ your client does not read it.

**Comment by SagnikSRHUSE** [comment]
Turns out my Thunderbird was being weird for whatever reason.
