### ISSUE TITLE
Emails are not encrypted (No tls)

### ISSUE THREAD

**Issue by KaktusWasser** [mailcow/mailcow-dockerized#3066]
Hi there,
I have just set up mailcow on my new server and it works fine. I can receive and send emails.
But my outgoing emails are not encrypted. There is no standard TLS encryption:

![chrome_4nx4bmeZQB](https://user-images.githubusercontent.com/25563847/67159311-01332c00-f343-11e9-9632-0505e7f4aad5.png)

I really don't know why the email isn't encrypted. btw. Ports are forwarded correctly.

**Comment by mhofer117** [comment]
Did you set up any Sender-dependent transports / Transport maps?
Which server receives the mail, does it support TLS or do you somehow forward them to gmail?
Should be working to any @gmail.com addresses

**Comment by KaktusWasser** [comment]
No I did not set up any transport maps.
The vps supports TLS.

**Comment by mhofer117** [comment]
Mailcow supports TLS, it's the recipient server that needs TLS support too.
Try sending directly to an @gmail.com address.

**Comment by KaktusWasser** [comment]
![chrome_TwXkJu2mmi](https://user-images.githubusercontent.com/25563847/67163295-83384a80-f36d-11e9-9d56-df73fdd9e6e5.png)

**Comment by mhofer117** [comment]
What do the postfix logs in mailcow show?
```
Trusted TLS connection established to gmail-smtp-in.l.google.com[74.125.140.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
```

**Comment by KaktusWasser** [comment]
```
15F471623EF: to=<roman.kotov04@gmail.com>, relay=gmail-smtp-in.l.google.com[74.125.140.26]:25, delay=3.5, delays=1.2/0.09/1.5/0.78, dsn=2.0.0, status=sent (250 2.0.0 OK 1571591490 d3si10385117wrn.459 - gsmtp)
15F471623EF: replace: header Received: from [10.8.0.2] (unknown [91.236.116.189])??(using: Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPSA id 15F471623EF??for <roman.kotov04@gmail.com>; Sun, 20 Oct 2019 17:11:26 +0000 (UTC)
disconnect from unknown[91.236.116.189] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
15F471623EF: from=<admin@yee.to>, size=795, nrcpt=1 (queue active)
15F471623EF: message-id=<e29aa305-0739-1384-b47e-cc59a60b63a3@yee.to>
15F471623EF: client=unknown[91.236.116.189], sasl_method=PLAIN, sasl_username=admin@yee.to
Anonymous TLS connection established from unknown[91.236.116.189]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
connect from unknown[91.236.116.189]
```

**Comment by mhofer117** [comment]
Can temporarily set `smtp_tls_loglevel = 2` in `data/conf/postfix/main.ch` and then restart postfix with `docker-compose restart postfix-mailcow`.
Maybe it will log a reason why the tls handshake with gmail fails?

**Comment by andryyy** [comment]
And TLS maps? Git diff? Own certificate?
You seem to run it behind VPN too.

**Comment by KaktusWasser** [comment]
I didn't set up any TLS maps. The certificate is default (letsencrypt).
This is not a VPN on my server,  I'm just connected to a VPN on my home PC

Logs with loglevel 2 (email sent with SOGO):
```
0C47716240A: removed
info	0C47716240A: to=<roman.kotov04@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.166.27]:25, delay=2.5, delays=0.32/0.06/1.4/0.75, dsn=2.0.0, status=sent (250 2.0.0 OK 1571595503 p125si10164255wmp.74 - gsmtp)
info	0C47716240A: replace: header Received: from 891b062f915c (mailcowdockerized_sogo-mailcow_: Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPA id 0C47716240A??for <roman.kotov04@gmail.com>; Sun, 20 Oct 2019 18:18:20 +0000 (UTC)
info	initializing the client-side TLS engine
info	disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
info	0C47716240A: from=<admin@yee.to>, size=1050, nrcpt=1 (queue active)
info	0C47716240A: message-id=<45-5daca500-1-33fc9b0@40403511>
info	0C47716240A: client=mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248], sasl_method=PLAIN, sasl_username=admin@yee.to
info	connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
```

**Comment by mhofer117** [comment]
unfortunately the logs don't seem to be useful...

Maybe you have some success with other values for [smtp_tls_security_level](http://www.postfix.org/postconf.5.html#smtp_tls_security_level) and/or even higher loglevel. Would be interesting to see why it's not using tls on your system
