### ISSUE TITLE
SOGo contains duplicates in calendar_category_labels in Polish lang

### ISSUE THREAD

**Issue by kawasoft** [mailcow/mailcow-dockerized#3067]
I found a duplicate in:
/var/lib/docker/volumes/mailcowdockerized_sogo-web-vol-1/_data/PreferencesUI.SOGo/Resources/Polish.lproj/Localizable.strings:252:"calendar_category_labels" = "Rocznica,Urodziny,Biznes,Telefony,Klienci,Konkurencja,Klient,Ulubione,Nawiązanie,Podarunki,Święta,Idee,Spotkania,Problemy,Różne,Osobiste,Projekty,Święta,Status,Dostawcy,Podróż,Wakacje";

word: "Święta" (en:holidays) is twice, instead of "Święta, Święta publiczne" (en:holidays, public holidays)

this causes an error in every new mailbox when trying to save the parameters:
"Error
Calendar categories must have unique names. "

**Comment by andryyy** [comment]
Thanks, but please report it to SOGo. :)

**Comment by dallascao** [comment]
This is very annoying. It's 2025 now and the issue is still there. I just cannot save any settings.

**Comment by dallascao** [comment]
For anyone who has this issue.
Go to Setup -> Calendar -> Categories and delete duplicate categories there.
