### ISSUE TITLE
rspamd error log spam

### ISSUE THREAD

**Issue by CookieCr2nk** [mailcow/mailcow-dockerized#3069]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

In the rspamd error logs, every minutes it spams following "errors": ```signing failure: cannot make request to load DKIM selector for domain localhost: nil``` and ```clamav: failed to scan, maximum retransmits exceed```

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1.   At the rspamd webinterface in the section History the error logs at the bottom of the page.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.1 |
| Is Apparmor, SELinux or similar active? | Yes |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 1 Core, 2GB RAM, 2048 Swap|
| Docker Version (`docker version`) | 19.03.3 |
| Docker-Compose Version (`docker-compose version`) |1.24.1, build 4667896b |
| Reverse proxy (custom solution) | NO |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
I will check it. Thanks.

**Comment by CookieCr2nk** [comment]
I suppose the error ```clamav: failed to scan, maximum retransmits exceed``` is, because i had disabled clamav.

**Comment by andryyy** [comment]
Should be fixed now. :)
