### ISSUE TITLE
Dont Recive mails

### ISSUE THREAD

**Issue by MineTech13** [mailcow/mailcow-dockerized#307]
I dont recive mails i send from gmail an email to my mailcow server but i dont get the email but from the mailcow server i can send a mail to gmail when you need infos just ask i try to answer so fast i can

**Comment by MineTech13** [comment]
okay problem has solved by hisself

**Comment by stevesbrain** [comment]
For future reference, if you'd just set up DNS, it can take a while to propagate (i.e. a while before remote domains can send to you), but you will be able to send out straight away. Worth keeping in mind :)
