### ISSUE TITLE
mailcow on Google Cloud Compute Engine

### ISSUE THREAD

**Issue by webdeveloper0429** [mailcow/mailcow-dockerized#3073]
I have installed this mailcow(dockerized) on google cloud compute engine.
Btw Google always block 25 port outbound. so can't send any email.

Any solution on Google cloud server?

**Comment by patschi** [comment]
Reach out to Google Cloud support and get the port unblocked. We can't help you with that, as it is not related to mailcow itself.

**Comment by webdeveloper0429** [comment]
Google doesn't open it.

```
Note: Port 25 is always blocked and can't be used, even through an SMTP relay using G Suite.
```

**Comment by patschi** [comment]
Then you'll have to switch to a different provider.
