### ISSUE TITLE
autodiscovery doesn`t work for macos mail client

### ISSUE THREAD

**Issue by drMARTINS13** [mailcow/mailcow-dockerized#3074]
Hi,
i have fresh install of mailcow. I have all dns records. Autodiscovery works great in thunderbird or mail app in ios where i use exchange. But when i want to set email in mail app in macos it doesn`t work and show me Name or password cannot be authenticated and want some internal and external url.
And now i dont know where can be a problem when in another application, even on ios works everything well.
i have latest macos 10.15 and it is same on older macos

**Comment by chriscroome** [comment]
My understanding is that Thunderbird uses `autoconfig.*`, Outlook uses `autodiscover.*` and Mac / iOS Mail clients use DNS SRV records, but I could be wrong&hellip;

**Comment by andryyy** [comment]
Yes, I think Mac only understands SRV records while iOS also reads autodiscover.

**Comment by drMARTINS13** [comment]
and how should srv records looks? This is what mailcow show me to set up in dns and it is what i have
<img width="885" alt="Snímek obrazovky 2019-10-22 v 14 32 47" src="https://user-images.githubusercontent.com/56875538/67286053-f7dbc800-f4d8-11e9-9109-88b2e50c0ca8.png">

https://mxtoolbox.com/SuperTool.aspx?action=srv%3a_autodiscover._tcp.linuxhelp.cz&run=networktools

it is probably some problem in macos mail client becouse everything look normaly

https://testconnectivity.microsoft.com/#&&Whq8NN1sLcxOD2kSoWcFMQr9u4dv7HtNzGdBy5n2KRdbKtHAh+Oj5lx1cqRqVBNMxpOh+A7S052zpEJsZ2zDZn3RSig6wY+HTEad9d0a4wxNDwM8gSi1kk+Fi6D8YDmarzsEfhl+eX/JFh+lweGLNCr9E9A+e0eUrXg6X4cL66NcJgcOr41eCfs1PU4fF8mNMeG4Kvo92JqMu48cEBTnr9Qsn5g=

when i try to add account in macos i can find this in autodiscover log
<img width="933" alt="Snímek obrazovky 2019-10-22 v 16 11 25" src="https://user-images.githubusercontent.com/56875538/67294922-c23ddb80-f4e6-11e9-87fe-f25c96390d72.png">
but when i add acount in ios there is nothing in autodiscover log but i can see something in sogo log
<img width="914" alt="Snímek obrazovky 2019-10-22 v 16 13 43" src="https://user-images.githubusercontent.com/56875538/67295135-07faa400-f4e7-11e9-968d-0a8abdaa7b16.png">

**Comment by mkuron** [comment]
> it doesn`t work and show me Name or password cannot be authenticated and want some internal and external url.

You're setting up an Exchange account. Mailcow only supports Exchange ActiveSync, which macOS does not support. Use IMAP instead.

> I think Mac only understands SRV records while iOS also reads autodiscover.

I don't think macOS supports RFC 6186-style SRV records (_imaps._tcp.example.com etc.). iOS only uses autodiscover for Exchange accounts.

> https://testconnectivity.microsoft.com

That has never worked reliably with Mailcow.

Summary: for Apple Mail, use IMAP, CalDAV and CardDAV. And don't configure it manually, but log into Mailcow as the user and download a .mobileconfig profile from the client guides page.
