### ISSUE TITLE
Add posibility to turn off built in CKEditor dictionary.

### ISSUE THREAD

**Issue by evilMouse** [mailcow/mailcow-dockerized#3075]
**Is your feature request related to a problem? Please describe.**
CKEditor builtin spellchecker doesn't support many languages so I'd like to turn it off and use native (browser) one.

**Describe the solution you'd like**
I've read that you can achieve above using setting 

`config.browserContextMenuOnCtrl = false;`

in /UI/WebServerResources/js/vendor/ckeditor/config.js
https://sogo.nu/bugs/view.php?id=3704

I think it would be nice to have this in one of mailcow config files so it doesn't get overwritten after update. 

Besides where do I find this file (/ckeditor/config.js) now?

**Comment by andryyy** [comment]
You can try adding this to `data/conf/sogo/custom-sogo.js`. But I highly doubt "browserContextMenuOnCtrl" is responsible for the spellchecker. oO

```
CKEDITOR.config.browserContextMenuOnCtrl = false;
```
In `data/conf/sogo/custom-sogo.js` you will find a commented `//CKEDITOR.config.scayt_autoStartup`. Uncomment it and set it to false.

**Comment by evilMouse** [comment]
Sorry it's obvious mistake :)
It should be:
`config.disableNativeSpellChecker = false;`
I'll try that and let you know.

**Comment by andryyy** [comment]
Also try scayt_autoStartup :) And please restart sogo-mailcow and memcached-mailcow

**Comment by evilMouse** [comment]
Gr8 it works with CKEDITOR prefix. So full path is:

`CKEDITOR.config.disableNativeSpellChecker = false;`

BTW, Scayt is off by default.

Thank you very much.

**Comment by andryyy** [comment]
You are welcome. :)
