### ISSUE TITLE
UI Problems with Brave Web Browser (linux)

### ISSUE THREAD

**Issue by mamair** [mailcow/mailcow-dockerized#3077]
After updaten yesterday if i login as admin in configuration -> e-mail-setup in domains and mailbox submenu / view i cant edit domains and (login in) users any more, the butons on the right sides are missing.

During update process i didnt see any error message.

At the bottom ther is still the actions ("Aktionen") button, but there i only can delete e-mail-boxes, but not change passwords and so on or log into the email account

Very strange ...

**Comment by andryyy** [comment]
Can you please clear your browsers cache?
Could you please post a screenshot of your browsers debug console?

@tinect can this be related to your change?

**Comment by mamair** [comment]
Yes, seems to be mostly a browser problem. In firefox it works. Brave Web Browser on linux is the trouble maker. Last update i had no problem ...

Fortunately i am not a commercia web designer since many years, too much stress ;-)

**Comment by tinect** [comment]
I'm on tour, but will try to check this afternoon with some more browsers in browserstack.

**Comment by andryyy** [comment]
Brave on Windows seems fine. Strange. Could you please delete your cache?

**Comment by tinect** [comment]
Yes, please try to kill the cache.
Tested on manjaro in "Brave Version 0.68.141 Chromium: 77.0.3865.90 (Offizieller Build) unknown (64-Bit)" with no problems.

**Comment by DatAres37** [comment]
No problems as well. Version 0.69.135 Chromium: 77.0.3865.120.
Do your shields block anything?

**Comment by mkapra** [comment]
Same problem here with the Brave Browser on MacOS. But the problem is only there when I resize the browser window so that the buttons wouldn't have space on the right side (see on screenshot).

![Screenshot 2019-11-04 at 21 13 03](https://user-images.githubusercontent.com/34742358/68154626-31d0b380-ff48-11e9-990b-48aa957b0ce2.png)

**Comment by tinect** [comment]
Could you please check, if the buttons will be there, when you click on the "+" - this would be intentionally.
![image](https://user-images.githubusercontent.com/135993/68155458-064ec880-ff4a-11e9-8b87-c7722fc98eaf.png)

**Comment by mkapra** [comment]
@tinect Ahhhh sorry. I didn't see the '+' sign. Yes the actions are there. So it is also working fine for me. :)

**Comment by tinect** [comment]
@mamair same on your side?
