### ISSUE TITLE
Any plans for DANE

### ISSUE THREAD

**Issue by sbroekhoven** [mailcow/mailcow-dockerized#308]
Any plans for DANE support in the Postfix config?

**Comment by andryyy** [comment]
Postfix already verifies TLSA records. You can find those connections as "Verified connection..." while non-DANE connections are listed as "Trusted connection...".

**Comment by sbroekhoven** [comment]
http://www.postfix.org/TLS_README.html#client_tls_dane

**Comment by sbroekhoven** [comment]
Nice, let me install and try that.

**Comment by Braintelligence** [comment]
@binaryfigments Please close this issue if your problem is solved.
