### ISSUE TITLE
Nextcloud DB -> Files are locked

### ISSUE THREAD

**Issue by GrantZero** [mailcow/mailcow-dockerized#3081]
A few files are locked via nextcloud. I found a solution, but it won't work in mailcow-docker.

> put Nextcloud in maintenance mode: edit config/config.php and change this line:
'maintenance' => true,
Empty table oc_file_locks: Use tools such as phpmyadmin or connect directly to your database and run (the default table prefix is oc_, this prefix can be different or even empty):
DELETE FROM oc_file_locks WHERE 1
disable maintenance mode (undo first step).

How can i execute this?

**Comment by BlackWolfDEsign** [comment]
`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/occ maintenance:mode --on"
`

try: 

`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/occ db:add-missing-indices"`

or:

`docker exec -it -u www-data $(docker ps -f name=php-fpm-mailcow -q) bash -c "php /web/nextcloud/occ files:scan -all"`
