### ISSUE TITLE
After update mailcow UI not working

### ISSUE THREAD

**Issue by pva29** [mailcow/mailcow-dockerized#3087]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I've today updated the mailcow installation on my host, which went fine without an visible issue.
SoGo and other features seems to work, but the Mailcow UI looks strange and for 2 /cache/ Files - *.js and *.css I get an 404.
In the developer tools following is visible:
**Console**:
`Das Skript von "https://hostname/cache/819004fe61ef03dc667caed48d2593d7a7a06200.js" wurde geladen, obwohl sein MIME-Typ ("text/html") kein für JavaScript gültiger MIME-Typ ist.
Laden fehlgeschlagen für das <script> mit der Quelle "https://hostname/cache/819004fe61ef03dc667caed48d2593d7a7a06200.js"
ReferenceError: $ is not defined hostname:126:1
    <anonym> https://hostname:126`
**Network:**
Getting 404 for /cache/++++++++.js and /cache/+++++.css (see attached image)
![Screen Shot 2019-10-23 at 23 19 31](https://user-images.githubusercontent.com/56939256/67435075-ae2fd200-f5eb-11e9-85fd-c8d45dfb2ea3.png)
![Screen Shot 2019-10-23 at 23 10 17](https://user-images.githubusercontent.com/56939256/67435076-aec86880-f5eb-11e9-810f-df99d1579ce3.png)

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to...mailcow UI
2. And then to... the scrren looks weird (see attachment) and missing files.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc) | ? |
| Server/VM specifications (Memory, CPU Cores) | 2 GB, 1 Core |
| Docker Version (`docker version`) | 18.09.7 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | no |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
Output is same, no timeout or error.
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Further notes:

**Output of git diff origin/master**, any other changes to the code? If so, please post them.

After posting the git diff: Does "git checkout origin/master data/conf/nginx data/web" followed by "docker-compose restart nginx-mailcow" fix it?

**Comment by pva29** [comment]
Hi - sorry forgot it.

Here the git diff origin/master:
`commit 8a4706f8f2d131384f028c6d9f551a2deaad513c (HEAD -> master)
Merge: 8c016682 bfb000b2
Author: moo <moo@cow.moo>
Date:   Wed Oct 23 22:50:29 2019 +0200

    After update on 2019-10-23_22_49_36

commit bfb000b2c0545c93ec7ca2b8dd11aa0007c89452 (origin/master, origin/HEAD)
Merge: ccd9d934 74e8dad1
Author: André Peters <andre.peters@debinux.de>
Date:   Wed Oct 23 22:13:12 2019 +0200

    Merge pull request #3086 from tinect/cleanupCode

    small cleanup

commit 74e8dad13197f7304672c91a090e5d16573c569c
Author: tinect <s.koenig@tinect.de>
Date:   Wed Oct 23 22:09:10 2019 +0200

    small cleanup

commit 8c01668218e59b465f7fde22b221cfeaeb818bf4
Merge: 13074d4c ccd9d934
Author: moo <moo@cow.moo>
Date:   Wed Oct 23 22:00:52 2019 +0200

    After update on 2019-10-23_21_57_07

commit 13074d4caaed850bed4e03880f3992c03f3fc168
Author: moo <moo@cow.moo>
Date:   Wed Oct 23 22:00:51 2019 +0200

    Before update on 2019-10-23_21_57_07

commit ccd9d934d6350df4a98ce8d67433e7b36fc49b74
Author: andryyy <andre.peters@debinux.de>
Date:   Wed Oct 23 21:41:19 2019 +0200

    [Helper] New parameter --delete-days to delete backups older than n days

commit cd6594df01347e467fb378aae075c266b5c9c111
Author: andryyy <andre.peters@debinux.de>
Date:   Tue Oct 22 21:30:45 2019 +0200

    [Clamd] Run freshclam before starting ClamAV

commit a4ef22729c61a4a1be0736e6845c7dae4076a334
Merge: c10749c3 e0486ea5
Author: andryyy <andre.peters@debinux.de>
Date:   Tue Oct 22 21:29:30 2019 +0200

    Merge branch 'master' of https://github.com/mailcow/mailcow-dockerized

commit e0486ea5a590a8ece197ec28e61784b157ace044
Merge: 6fb856cb eccbb980
Author: André Peters <andre.peters@debinux.de>
Date:   Tue Oct 22 21:00:20 2019 +0200

    Merge pull request #3080 from mkuron/oauth

    OAuth improvements

commit eccbb980023c0acdedbdc1e8f5c666441435831b
Author: Michael Kuron <mkuron@users.noreply.github.com>
Date:   Tue Oct 22 20:23:00 2019 +0200

    OAuth: show reduced login screen

commit c10749c39e08216fc75c22ed68692ef2da48f93a
Merge: 5259f14a 6fb856cb
Author: andryyy <andre.peters@debinux.de>
Date:   Tue Oct 22 20:22:31 2019 +0200

    Merge branch 'master' of https://github.com/mailcow/mailcow-dockerized

commit 5259f14abf3711003473427bffb381a3220e001a
Author: andryyy <andre.peters@debinux.de>
Date:   Tue Oct 22 20:22:29 2019 +0200
ubuntu@v22019093587997964:/docker/mailcow-dockerized$ git diff
ubuntu@v22019093587997964:/docker/mailcow-dockerized$ git diff origin/master
diff --git a/data/conf/nginx/site.conf b/data/conf/nginx/site.conf
index d6e6b136..979ebd7b 100644
--- a/data/conf/nginx/site.conf
+++ b/data/conf/nginx/site.conf
@@ -7,4 +7,217 @@ map $http_x_forwarded_proto $client_req_scheme {
      https https;
 }

-include /etc/nginx/conf.d/sites.active;
+server {
+  include /etc/nginx/mime.types;
+  charset utf-8;
+  override_charset on;
+
+  ssl_certificate /etc/ssl/mail/cert.pem;
+  ssl_certificate_key /etc/ssl/mail/key.pem;
+  ssl_protocols TLSv1.2 TLSv1.3;
+  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
+  ssl_prefer_server_ciphers on;
+  ssl_session_cache shared:SSL:50m;
+  ssl_session_timeout 1d;
+  ssl_session_tickets off;
+
+  add_header Strict-Transport-Security "max-age=15768000;";
+  add_header X-Content-Type-Options nosniff;
+  add_header X-XSS-Protection "1; mode=block";
+  add_header X-Robots-Tag none;
+  add_header X-Download-Options noopen;
+  add_header X-Frame-Options "SAMEORIGIN" always;
+  add_header X-Permitted-Cross-Domain-Policies none;
+  add_header Referrer-Policy strict-origin;
+
+  index index.php index.html;
+
+  client_max_body_size 0;
+
+  listen 127.0.0.1:65510;
+  include /etc/nginx/conf.d/listen_plain.active;
+  include /etc/nginx/conf.d/listen_ssl.active;
+  include /etc/nginx/conf.d/server_name.active;
+
+  gzip on;
+  gzip_disable "msie6";
+
+  gzip_vary on;
+  gzip_proxied off;
+  gzip_comp_level 6;
+  gzip_buffers 16 8k;
+  gzip_http_version 1.1;
+  gzip_min_length 256;
+  gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;
+
+  location ~ ^/(fonts|js|css|img)/ {
+    expires max;
+    add_header Cache-Control public;
+  }
+
+  error_log  /var/log/nginx/error.log;
+  access_log /var/log/nginx/access.log;
+  absolute_redirect off;
+  root /web;
+
+  location / {
+    try_files $uri $uri/ @strip-ext;
+  }
+
+  location /qhandler {
+    rewrite ^/qhandler/(.*)/(.*) /qhandler.php?action=$1&hash=$2;
+  }
+
+  location /edit {
+    rewrite ^/edit/(.*)/(.*) /edit.php?$1=$2;
+  }
+
+  location @strip-ext {
+    rewrite ^(.*)$ $1.php last;
+  }
+
+  location ~ ^/api/v1/(.*)$ {
+    try_files $uri $uri/ /json_api.php?query=$1;
+  }
+
+  location ^~ /.well-known/acme-challenge/ {
+    allow all;
+    default_type "text/plain";
+  }
+
+  # If behind reverse proxy, forwards the correct IP
+  set_real_ip_from 10.0.0.0/8;
+  set_real_ip_from 172.16.0.0/12;
+  set_real_ip_from 192.168.0.0/16;
+  set_real_ip_from fc00::/7;
+  real_ip_header X-Forwarded-For;
+  real_ip_recursive on;
+
+  rewrite ^/.well-known/caldav$ /SOGo/dav/ permanent;
+  rewrite ^/.well-known/carddav$ /SOGo/dav/ permanent;
+
+  location ^~ /principals {
+    return 301 /SOGo/dav;
+  }
+
+  location ~ \.php$ {
+    try_files $uri =404;
+    fastcgi_split_path_info ^(.+\.php)(/.+)$;
+    fastcgi_pass phpfpm:9002;
+    fastcgi_index index.php;
+    include /etc/nginx/fastcgi_params;
+    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
+    fastcgi_param PATH_INFO $fastcgi_path_info;
+    fastcgi_read_timeout 1200;
+  }
+
+  location /rspamd/ {
+    proxy_pass       http://rspamd:11334/;
+    proxy_set_header Host      $http_host;
+    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+    proxy_set_header X-Real-IP $remote_addr;
+    proxy_redirect off;
+  }
+
+  location ~* ^/Autodiscover/Autodiscover.xml {
+    fastcgi_split_path_info ^(.+\.php)(/.+)$;
+    fastcgi_pass phpfpm:9002;
+    include /etc/nginx/fastcgi_params;
+    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
+    try_files /autodiscover.php =404;
+  }
+
+  location ~* ^/Autodiscover/Autodiscover.json {
+    fastcgi_split_path_info ^(.+\.php)(/.+)$;
+    fastcgi_pass phpfpm:9002;
+    include /etc/nginx/fastcgi_params;
+    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
+    try_files /autodiscover-json.php =404;
+  }
+
+  location ~ /(?:m|M)ail/(?:c|C)onfig-v1.1.xml {
+    fastcgi_split_path_info ^(.+\.php)(/.+)$;
+    fastcgi_pass phpfpm:9002;
+    include /etc/nginx/fastcgi_params;
+    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
+    try_files /autoconfig.php =404;
+  }
+
+  # auth_request endpoint if ALLOW_ADMIN_EMAIL_LOGIN is set
+  location /sogo-auth-verify {
+    internal;
+    proxy_set_header  X-Original-URI $request_uri;
+    proxy_set_header  X-Real-IP $remote_addr;
+    proxy_set_header  Host $http_host;
+    proxy_set_header  Content-Length "";
+    proxy_pass        http://127.0.0.1:65510/sogo-auth;
+    proxy_pass_request_body off;
+  }
+
+  location ^~ /Microsoft-Server-ActiveSync {
+    include /etc/nginx/conf.d/sogo_proxy_auth.active;
+    include /etc/nginx/conf.d/sogo_eas.active;
+    proxy_connect_timeout 4000;
+    proxy_next_upstream timeout error;
+    proxy_send_timeout 4000;
+    proxy_read_timeout 4000;
+    proxy_buffer_size 8k;
+    proxy_buffers 16 64k;
+    proxy_temp_file_write_size 64k;
+    proxy_busy_buffers_size 64k;
+    proxy_set_header X-Real-IP $remote_addr;
+    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+    proxy_set_header Host $http_host;
+    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
+    proxy_set_header x-webobjects-remote-host $remote_addr;
+    proxy_set_header x-webobjects-server-name $server_name;
+    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
+    proxy_set_header x-webobjects-server-port $server_port;
+    client_body_buffer_size 128k;
+    client_max_body_size 0;
+  }
+
+  location ^~ /SOGo {
+    include /etc/nginx/conf.d/sogo_proxy_auth.active;
+    include /etc/nginx/conf.d/sogo.active;
+    proxy_set_header X-Real-IP $remote_addr;
+    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+    proxy_set_header Host $http_host;
+    proxy_set_header x-webobjects-server-protocol HTTP/1.0;
+    proxy_set_header x-webobjects-remote-host $remote_addr;
+    proxy_set_header x-webobjects-server-name $server_name;
+    proxy_set_header x-webobjects-server-url $client_req_scheme://$http_host;
+    proxy_set_header x-webobjects-server-port $server_port;
+    client_body_buffer_size 128k;
+    client_max_body_size 0;
+    break;
+  }
+
+  location /SOGo.woa/WebServerResources/ {
+    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
+  }
+
+  location /.woa/WebServerResources/ {
+    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
+  }
+
+  location /SOGo/WebServerResources/ {
+    alias /usr/lib/GNUstep/SOGo/WebServerResources/;
+  }
+
+  location (^/SOGo/so/ControlPanel/Products/[^/]*UI/Resources/.*\.(jpg|png|gif|css|js)$) {
+    alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
+  }
+
+  include /etc/nginx/conf.d/site.*.custom;
+
+  error_page 502 @awaitingupstream;
+  location @awaitingupstream {
+    rewrite ^(.*)$ /_status.502.html break;
+  }
+
+  location ^~ /rainloop/data {
+    deny all;
+  }
+
+}
diff --git a/data/web/inc/vars.inc.php b/data/web/inc/vars.inc.php
index 8a853cd3..82fa7609 100644
--- a/data/web/inc/vars.inc.php
+++ b/data/web/inc/vars.inc.php
@@ -77,14 +77,16 @@ $DETECT_LANGUAGE = true;
 $DEFAULT_LANG = 'en';

 // Available languages
-$AVAILABLE_LANGUAGES = array('ca', 'cs', 'de', 'en', 'es', 'fi', 'fr', 'it', 'lv', 'nl', 'pl', 'pt', 'ru');
+//$AVAILABLE_LANGUAGES = array('cs', 'de', 'en', 'es', 'fr', 'lv', 'nl', 'pl', 'pt', 'ru', 'it', 'ca');
+$AVAILABLE_LANGUAGES = array('cs', 'de', 'en');

 // Change theme (default: lumen)
 // Needs to be one of those: cerulean, cosmo, cyborg, darkly, flatly, journal, lumen, paper, readable, sandstone,
 // simplex, slate, spacelab, superhero, united, yeti
 // See https://bootswatch.com/
 // WARNING: Only lumen is loaded locally. Enabling any other theme, will download external sources.
-$DEFAULT_THEME = 'lumen';
+//$DEFAULT_THEME = 'lumen';
+$DEFAULT_THEME = 'simplex';

 // Password complexity as regular expression
 // Min. 6 characters
@@ -100,8 +102,12 @@ $SHOW_DKIM_PRIV_KEYS = false;
 // mailcow Apps - buttons on login screen
 $MAILCOW_APPS = array(
   array(
-    'name' => 'Webmail',
+    'name' => 'SOGo',
     'link' => '/SOGo/',
+  ),
+  array(
+    'name' => 'Rainloop',
+    'link' => '/rainloop/',
   )
 );

diff --git a/docker-compose.yml b/docker-compose.yml
index 8118d2ed..e547a7be 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -305,6 +305,9 @@ services:
       ports:
         - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
         - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
+      expose:
+        - 80/tcp
+        - 443/tcp
       restart: always
       networks:
         mailcow-network:`

The command "git checkout origin/master data/conf/nginx data/web" show no result.
Nginx restart was not successfull, anyhow a whole restart of all container helped.

**Comment by markschultz** [comment]
i'm getting this exact same issue. git checkout as above as well as machine reboot did not help.

**Comment by mitakjakub** [comment]
Same here, js and css in cache are not accessible

**Comment by andryyy** [comment]
You should at least post _something_. Like ... git diff.

It works with the correct site. Run `git fetch ; git checkout origin/master data/conf` and run `docker-compose down ; docker-compose up -d`.

**Comment by markschultz** [comment]
git diff showed no changes. i did a `git reset --hard origin/master` and that worked although i'm not sure how.
