### ISSUE TITLE
Clamd didnt load?

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3088]
Hello,
since update from today looks like clamd didnt load.

clamd-mailcow Log:
`clamd-mailcow_1      | Wed Oct 23 23:23:49 2019 -> Database updated (6519028 signatures) from database.clamav.net (IP: 104.16.218.84)
clamd-mailcow_1      | Wed Oct 23 23:23:49 2019 -> ^Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.sock: No such file or directory`

Complete Log:
`clamd-mailcow_1      | Cleaning up tmp files...
clamd-mailcow_1      | Copying non-empty whitelist.ign2 to /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      | Stating whitelist.ign2
clamd-mailcow_1      |   File: /var/lib/clamav/whitelist.ign2
clamd-mailcow_1      |   Size: 27        	Blocks: 8          IO Block: 4096   regular file
clamd-mailcow_1      | Device: 2dh/45d	Inode: 2625642     Links: 1
clamd-mailcow_1      | Access: (0644/-rw-r--r--)  Uid: (  700/  clamav)   Gid: (  700/  clamav)
clamd-mailcow_1      | Access: 2019-10-23 23:22:11.133975965 +0200
clamd-mailcow_1      | Modify: 2019-10-23 23:22:11.133975965 +0200
clamd-mailcow_1      | Change: 2019-10-23 23:22:11.137976001 +0200
clamd-mailcow_1      |  Birth: -
clamd-mailcow_1      | dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
clamd-mailcow_1      | Running freshclam...
clamd-mailcow_1      | Wed Oct 23 23:22:11 2019 -> ClamAV update process started at Wed Oct 23 23:22:11 2019
clamd-mailcow_1      | Wed Oct 23 23:22:25 2019 -> Downloading main.cvd [100%]
clamd-mailcow_1      | Wed Oct 23 23:22:32 2019 -> main.cvd updated (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
clamd-mailcow_1      | Wed Oct 23 23:22:33 2019 -> *Can't query main.58.105.1.0.6810DA54.ping.clamav.net
clamd-mailcow_1      | Wed Oct 23 23:22:33 2019 -> Downloading daily.cvd [100%]
clamd-mailcow_1      | Wed Oct 23 23:23:44 2019 -> daily.cvd updated (version: 25611, sigs: 1952685, f-level: 63, builder: raynman)
clamd-mailcow_1      | Wed Oct 23 23:23:45 2019 -> *Can't query daily.25611.105.1.0.6810DA54.ping.clamav.net
clamd-mailcow_1      | Wed Oct 23 23:23:45 2019 -> Downloading bytecode.cvd [100%]
clamd-mailcow_1      | Wed Oct 23 23:23:45 2019 -> bytecode.cvd updated (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
clamd-mailcow_1      | Wed Oct 23 23:23:46 2019 -> *Can't query bytecode.331.105.1.0.6810DA54.ping.clamav.net
clamd-mailcow_1      | Wed Oct 23 23:23:49 2019 -> Database updated (6519028 signatures) from database.clamav.net (IP: 104.16.218.84)
clamd-mailcow_1      | Wed Oct 23 23:23:49 2019 -> ^Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.sock: No such file or directory
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: Global time limit set to 120000 milliseconds.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: Global size limit set to 52428800 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: File size limit set to 26214400 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: Recursion level limit set to 5.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: Files limit set to 200.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxPartitions limit set to 50.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxIconsPE limit set to 100.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: MaxRecHWP3 limit set to 16.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: PCREMatchLimit limit set to 100000.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: PCRERecMatchLimit limit set to 2000.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Limits: PCREMaxFileSize limit set to 26214400.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Archive support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> AlertExceedsMax heuristic detection disabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Heuristic alerts enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Portable Executable support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> ELF support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Mail files support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> OLE2 support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> PDF support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> SWF support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> HTML support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> XMLDOCS support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> HWP3 support enabled.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Heuristic: precedence enabled
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Self checking every 3600 seconds.
clamd-mailcow_1      | Wed Oct 23 23:25:10 2019 -> Set stacksize to 8454144`

**Comment by andryyy** [comment]
Hi,

if you have a question, you can always ask in Telegram or IRC. If it's a bug report, always use the template, please.

This is fine though. Clam is not running when we first fetch the signatures. It is started right after the first signature update.
