### ISSUE TITLE
How fast spam and ham is learning?

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#3089]
I moved Mails to spam for quit time know and all the mails get to my main folder. I don't see any progress in learning for now :/ 

Funny thing about that is that there are some Mails that comes in repeatet. So the spam server is sending me the same mail again and again every day and everyday I move those in spam manually.

**Comment by andryyy** [comment]
This is NOT a white or blacklisting. Use white and blacklists in mailcow UI. 

If you message is total crap, it will always be filed into Junk. Learning mail is not a whitelisting tool. It just slightly changes a mail reputation.

**Comment by wuast94** [comment]
I know that is not a black or white listing tool.
But in rspamd logs I don't see see Bayes spam score (wich should be the learning scoring? And should be there?) and at any time while learning this filter should take affect and should be affect the score to make thinks spam or ham. But this doesn't seems to happen on my server. 

And it's just that 1 email adresse that only gets heavy spam so I can just disable it and all good but I want to use this for the learning algorithm.

**Comment by andryyy** [comment]
You also completely removed the issue template. If it does not apply, join the support channels, please.

If the mail reputation is either crap or too good, Bayes does not change too much. If it doesn't even show a score, it has not learned enough. But we don't know, you don't post logs or headers of a mail, that should have been learned or filtered. Or Rspamd logs, when you move a mail to Junk or out of Junk.

Bayes does not work like this. Analyze the headers of the spam mails and adjust your filter. 

If you move 20 mails to Junk, you cannot expect it to detect a 21st message, when its content is not pretty much the same as the previous spam. You can also not move 100 newsletters to Junk and expect it know what exactly a newsletter is.

Post headers of missed spam, join the Telegram channel and adjust scores and symbols by yourself. :)
