### ISSUE TITLE
send to same domain, but on diffrenet server

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#3092]
Hello,

Scenario:

domain.tld MX record is on original.server.com

I also set up domain.tld on my Mailcow server

I need to get it to work, that i can send from my mailcow server from mailbox@domain.tld to all mailboxes located at original.server.com 

This scenario probably has a name, but i cant find it.
Please help :)

**Comment by andryyy** [comment]
Hi, as long as the domain is part of mailcow (locally), it will not work.

**Comment by reinistihovs** [comment]
Sad to hear :(
I have only this stupid idea, to setup all mailboxes on mailcow server, and then create sync jobs to the mailboxes on "original.server.com"

**Comment by mkuron** [comment]
Duplicate of #630.
