### ISSUE TITLE
Some Postfix headers are not anyonymized

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#3093]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

I stumbled across the problem in subject when trying to create a mail using temporary addresses to help fixing a bug in other software. 

Basically, the `Authenticated sender` line is not removed from Postfix (domain names changed):

```
(Authenticated sender: name@my.domain)
        by mailcow.server (Postcow) with ESMTPSA id BB172302FC54D
        for <grhbnvajlm5qpz18sx27c9iw@my.domain>; Fri, 25 Oct 2019 12:10:51 +0200 (CEST)
````

There's also the envelope-from in the `Received` header which contains the actual address, but I assume that one can't be removed.

The `Authenticated sender` issue had been present before, I guess the regexp is not catching it anymore.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Generate a temporary mail address
2. Send to yourself with the same temporary address as From and To
3. Inspect headers.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | openSUSE Leap 15.1 |
| Is Apparmor, SELinux or similar active? | AppArmor |
| Virtualization technlogy (KVM, VMware, Xen, etc) | None |
| Server/VM specifications (Memory, CPU Cores) | 16G RAM, Intel Xeon E31245, 8 cores|
| Docker Version (`docker version`) | 18.09.6 |
| Docker-Compose Version (`docker-compose version`) | version 1.24.0, build 0aa59064 |
| Reverse proxy (custom solution) |Not applicable |

Further notes:
 - No changes to setup for this issue.

**Comment by andryyy** [comment]
What do you want to hide if you send from yourself to yourself?

It works as intended when I send a mail from me@mailcow-domain to me@gmail.com

:/

**Comment by lbeltrame** [comment]
Probably the authenticated sender.

That said, I filed this because I thought it didn't work in general. If that only happens in me->me scenarios, I'm fine with this bug being closed: it's arguably a very small niche and not worth the effort.
