### ISSUE TITLE
Updating Roundcube

### ISSUE THREAD

**Issue by xatage** [mailcow/mailcow-dockerized#3094]
I'm just curious how to update Roundcube, if there is a new version available. Just removing the whole folder and install from scratch like described in the documentation or is there a more elegant solution?

**Comment by mamash** [comment]
Have you checked the [official UPGRADING doc](https://github.com/roundcube/roundcubemail/blob/master/UPGRADING) yet? There are always better ways than to re-install from scratch.

You could also just git clone Roundcube into your installation and use 'git checkout TAG' to lock at specific releases.

**Comment by xatage** [comment]
@mamash 
Thanks! Didn't really thought about checking Roundcube's repo 😨 Maybe it's a good idea to add this link into the Mailcow Documentation?

I think now, I'd be good to go with using the update script and if something fails, re-installing from scratch.

**Comment by MAGICCC** [comment]
Feel free to create a PR for this in the docs repo :)
IMHO for the reinstallation when something is failing is not a good idea...
