### ISSUE TITLE
DKIM Not Working When Sent From Phone

### ISSUE THREAD

**Issue by cbritton1978** [mailcow/mailcow-dockerized#3096]
I installed mailcow last night, and I've been testing it out. I imported the DKIM signature that I have been using on another mail server. 

I sent a test email to check-auth@verifier.port25.com using SOGo and it returned:
DKIM check:         pass 

I then setup an exchange account on on my Pixel phone and sent the same email and it returned:
DKIM check:         none

I sent two emails to may gmail account and had the same results.

Any suggestions? Not sure why it would work in Webmail but not from my phone.

**Comment by cbritton1978** [comment]
Not sure why but it's working now. I didn't change any settings.

![Capture1](https://user-images.githubusercontent.com/54037773/67641123-13c6db80-f8d6-11e9-814e-35a1a1dc4c8f.PNG)

![Capture2](https://user-images.githubusercontent.com/54037773/67641130-1cb7ad00-f8d6-11e9-98e5-50f57f166e47.PNG)

**Comment by wblondel** [comment]
Surely related to DNS propagation, which depends on the TTL value. Not a problem then
