### ISSUE TITLE
Is it safe to run Mailcow without a firewall on the host ?

### ISSUE THREAD

**Issue by JOduMonT** [mailcow/mailcow-dockerized#3097]
Hi;

I had a hard time to have a proper SSL via Let's Encrypt
I succeed mainly by skipping 
- SKIP_IP_CHECK=y
- SKIP_HTTP_VERIFICATION=y

But now, even my SSL is there
when I navigate to https://mail.glibre.net it still saying I'm not secure
Why?

![screenshot_10](https://user-images.githubusercontent.com/5204724/67657574-bee49d00-f989-11e9-8748-ec31b4309e20.png)

NOTE: The SSL is valid for IMAP and SMTP

**Comment by andryyy** [comment]
Close the tab and open it again. It seems valid.

Regarding your issues obtaining a certificate, you probably have other firewall related problems, you now - kind of - ignore.
If you need help, use the issue template, please.

**Comment by JOduMonT** [comment]
I was using chrome in private mode, but apparently, closing the tab was'nt enough
But your right everything is good now :)

**Comment by JOduMonT** [comment]
@andryyy ;

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

- [x] I do run mailcow on:
KVM @Hetzner; PhotonOS with AppArmor which have IPTables is by default

What I think
1. my IPv6 take over my IPv4 which is why I have to SKIP IP CHECK
2. IPTables don't relay/open port for IPv6 like it happen for IPv4 which is why I have to SKIP HTTP CHECK

While I'm able to ping ipv6.google.com from the host
![image](https://user-images.githubusercontent.com/5204724/67668049-c1eb8780-f9a1-11e9-963a-d04901f3f770.png)

````
Chain` INPUT (policy DROP)
target     prot opt source               destination         
MAILCOW    all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
MAILCOW    all  --  anywhere             anywhere            
DOCKER-USER  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.22.1.6           tcp dpt:8983
ACCEPT     tcp  --  anywhere             172.22.1.11          tcp dpt:https
ACCEPT     tcp  --  anywhere             172.22.1.11          tcp dpt:http
ACCEPT     tcp  --  anywhere             172.22.1.13          tcp dpt:submission
ACCEPT     tcp  --  anywhere             172.22.1.13          tcp dpt:urd
ACCEPT     tcp  --  anywhere             172.22.1.13          tcp dpt:smtp
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:italk
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:4190
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:pop3s
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:imaps
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:imap
ACCEPT     tcp  --  anywhere             172.22.1.250         tcp dpt:pop3
ACCEPT     tcp  --  anywhere             172.22.1.8           tcp dpt:mysql

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain MAILCOW (2 references)
target     prot opt source               destination         
````

So it's work if I disable iptables
## but it is safe to run mailcow without a firewall on the host ?

**Comment by MAGICCC** [comment]
Yes mailcow is safe to run without firewall when you have everything up2date on your system

**Comment by JOduMonT** [comment]
@MAGICCC just by curiosity; do you know howto make IPtables interacting with IPv6 like it does for IPv4 ? Because I had ipv6 : true in my docker/daemon.json and it didn't

**Comment by dragoangel** [comment]
@JOduMonT did your mailcow.conf have correctly configured SNAT for IPv6? If you turn off firewall service did you get opened ports on ipv6? If - yes, then you simply need how-to on how iptables work, there a lot of samples on web. If - no, did you server in lan or it have wan access?

**Comment by JOduMonT** [comment]
@dragoangel my server is directly on the the net
from my understanding, docker need iptables, but iptables on my host is disable.
Since everything is behind nginx-mailcow
I relay on netfilter-mailcow for my firewall
