### ISSUE TITLE
Message # does not account for imported mail

### ISSUE THREAD

**Issue by MadMooAU** [mailcow/mailcow-dockerized#310]
I have ~2000 messages in one of my mailboxes, but because much of that was imported, the server only shows the number as 81 (New install).

**Comment by andryyy** [comment]
This auto-fixes the next time the cronjob is run.

But you can fix it by running `docker-compose exec dovecot-mailcow doveadm quota recalc -A`

Edit: I will add this to the perl script to run when mail was pulled.

**Comment by lazyfrosch** [comment]
I guess this is bc the cronjob is broken:

```
Subject: Cron <vmail@mail>  /usr/bin/doveadm quota recalc -A
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/var/vmail>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=vmail>
Message-Id: <E1dc1P7-0005mx-FX@mail.lazyfrosch.de>
Date: Mon, 31 Jul 2017 03:30:01 +0000

/bin/sh: 1: /usr/bin/doveadm: not found
```

This can be found in `/var/mail/vmail` on dovecot

**Comment by andryyy** [comment]
Good catch! :-) Thanks.
