### ISSUE TITLE
Watchdog alert improvements

### ISSUE THREAD

**Issue by SamuelNitsche** [mailcow/mailcow-dockerized#3100]
**Is your feature request related to a problem? Please describe.**
The current implementation of the watchdog service, unfortunately, is not helpful. In my specific case, watchdog sent an alert for acme-mailcow but there was no log entry to identify the problem watchdog noticed.

**Describe the solution you'd like**
Alerts sent from watchdog should contain a short description of the problem.

**Comment by andryyy** [comment]
It is as helpful as it can be. 

It sends you failed checks as attachment.

You need to debug WHY something failed by yourself. Watchdog cannot do that for you.

In case of ACME it just notifies you, that something went wrong and quit non-zero. Again, you need to debug that on the server anyway. 

I don't plan to change it. :/
