### ISSUE TITLE
Queue manager monitor

### ISSUE THREAD

**Issue by damdinsharav** [mailcow/mailcow-dockerized#3101]
**Is your feature request related to a problem? Please describe.**
One of email address holder lost hist account information and his address sent roughly 5000 SPAM. When I noticed there were about another 3000 emails deferred in email queue. 

**Describe the solution you'd like**
It would be wonderful to send email to given email address(admin) if emails in queue reached over certain number.

**Comment by andryyy** [comment]
Set a (high) rate limit and you will be informed if a clients triggers it.

Everything else would need to be implemented.

**Comment by damdinsharav** [comment]
> Set a (high) rate limit and you will be informed if a clients triggers it.
> 
> Everything else would need to be implemented.

I set 50 rate limit per hour on domain. However, I never been informed when user sent such lot emails. What other config need to be done?

**Comment by andryyy** [comment]
Dont' know, works fine here. Do you receive ANY notification mail at 
all? Do you receive a mail when you restart watchdog-mailcow?

------ Originalnachricht ------
Von: "dsh" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Comment" 
<comment@noreply.github.com>
Gesendet: 28.10.2019 12:19:27
Betreff: Re: [mailcow/mailcow-dockerized] Queue manager monitor (#3101)

**Comment by damdinsharav** [comment]
> Dont' know, works fine here. Do you receive ANY notification mail at all? Do you receive a mail when you restart watchdog-mailcow?

Thank you. I was missing very useful feature. I've looked up watchdog and it's disabled in conf.

This will do.

**Comment by andryyy** [comment]
Ahhhh, alright. :) We really need to enable it by default...
