### ISSUE TITLE
Dovecot starting up but failing with SSL initialisation failure

### ISSUE THREAD

**Issue by Schuermi7** [mailcow/mailcow-dockerized#3104]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
I updated mailcow-dockerized and expected it to work afterwards.
After updating, every container comes up as expected, but no new mail can be obtained by mail-clients, because dovecot has an internal error message.

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
1, Nothing changed on the files, that are maintained by the git or the update script.
2. Did an update with update.sh and expected it to work
3. Dovecot stopped working with internal error message

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian Stretch |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | vServer on KVM |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 6 vCores |
| Docker Version (`docker version`) |  19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | no |

Further notes:
 
General logs:
A lot of the same internal error
`imap-login: Error: Failed to initialize SSL server context: Can't load DH parameters: error:1408518A:SSL routines:ssl3_ctx_ctrl:dh key too small: user=<>, rip=xxx.xxx.xxx.xxx, lip=172.22.1.250
--`

**Comment by andryyy** [comment]
git diff and git diff origin/master? ls -la data/assets/ssl/dhparams.pem?

**Comment by Schuermi7** [comment]
git diff on the master brings up the sample ca-key.pem and the sample ca.pem. 
ls on the file gives 
`-rw-r--r-- 1 root root 465 Apr 30  2018 data/assets/ssl/dhparams.pem`

**Comment by andryyy** [comment]
It shouldn't show data/assets/ssl/* 

Why is ca.pem modified anyway?

None of this should happen on an unchanged installation. Perhaps someone on Telegram can help you debug this. :)

**Comment by Schuermi7** [comment]
I have not changed anything on this files, so i am curious, how any of this can happen.
It worked flawlessly like until one week ago and now there is this error message.

**Comment by Schuermi7** [comment]
Okay. I found a solution for this. 
It seems to me like the auto-generated dhparams were 1024bit long, whereas dovecot needs a 2048bit dh-param to work flawlessly. 
I regenerated a 2048bit dhparams.pem and restarted dovecot and now it's working
