### ISSUE TITLE
rspamd/sa-rules "cannot approximate  . . .  to hyperscan" - unmasked $

### ISSUE THREAD

**Issue by MatthisB** [mailcow/mailcow-dockerized#3106]
**Is your feature request related to a problem?**

Sometimes it happens that the $ character in the sa-rules is not properly masked.
This at least leads to unsightly logs:  _"cannot approximate  . . .  to hyperscan"_

![grafik](https://user-images.githubusercontent.com/341922/67794252-a30df380-fa7c-11e9-803e-a375f20aac95.png)
( In this example the rules of schaal-it )

The entries from external sources are taken without any filtering and written to `/opt/mailcow-dockerized/data/conf/rspamd/custom/sa-rules`.

**Describe the solution you'd like**
We could create a filter for at least $ signs.

A simple `sed -i -e 's/\([^\\]\)\$\([^\/]\)/\1\\$\2/g' /tmp/sa-rules-heinlein/*cf` before appending the rules with `cat /tmp/sa-rules-schaal/*cf >> /etc/rspamd/custom/sa-rules` would do.

The command (applied to the file `/opt/mailcow-dockerized/data/conf/rspamd/custom/sa-rules` ) also helps with already existing entries.

**Comment by andryyy** [comment]
Can you create a PR?

**Comment by andryyy** [comment]
I added it, will push later. Thanks.

**Comment by MatthisB** [comment]
Thanks :)

( https://github.com/mailcow/mailcow-dockerized/commit/2f3f70dd004e94ac80f5ea1704113d90d7f922a5 )
