### ISSUE TITLE
Listed or regexp transport map destinations

### ISSUE THREAD

**Issue by mamash** [mailcow/mailcow-dockerized#3107]
When defining a new transport map entry, the UI hint suggest that comma-separated values are accepted as destination, but that is not true. At the end, the SQL query uses a plain `destination = '%s'` comparison, so anything comma-separated will not match.

regexp-based (to use with with _REGEXP_ operator) or comma-separated (_FIND_IN_SET_ could be used) destinations should be accepted.

Context: I'm working around problems with delivery to domains using the Symantec RBL service, which has been blacklisting servers for a long time, never provide any evidence, never communicate back and don't respond to removal requests in a timely manner (or ever). The idea is to use e.g. Amazon SES for such destinations, but managing anything but one or two such entries quickly becomes a nightmare in the current UI.

Does this sound like a good feature enhancement? I can prepare a PR for review.

**Comment by andryyy** [comment]
It does accept multiple comma-separated destinations **and will create one transport rule for each destination**.

REGEXP would need a bunch of modifications to the validation system in the UI and may or may not break existing installations.

Just replacing the map with REGEXP in a PR will not be accepted. I don't think a regexp map would justify the work that needs to be done.

**Comment by mamash** [comment]
> It does accept multiple comma-separated destinations **and will create one transport rule for each destination**.

Ah. It does so at creation time only. That's why it didn't work for me, because I tried one destination, then added a dozen more.

I'll give it some more thought then. Currently, it's too complicated to add a different destination for an existing nexthop, as I need to look up the login credentials again and enter them correctly in order for the UI to let me through.

How about storing transports in one place and referring them from either sender-dependent transports and transport maps? Ultimately a single transport may be utilised in either of the scenarios.

**Comment by andryyy** [comment]
That should not take longer than 10s with a password manager. :)

But that's something we can implement though. I cannot give you an ETA...
