### ISSUE TITLE
Rspamd terminated with code 137

### ISSUE THREAD

**Issue by Roguyt** [mailcow/mailcow-dockerized#3108]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is the rspamd container terminated himself blocking the receiving of email on the mailcow instance.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
This happened twice in the last few months for no apparent reason.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**
```
2019-10-30 01:30:27 #1(main) <bd8186>; main; rspamd_term_handler: catch termination signal, waiting for children
2019-10-30 01:30:36 #1(main) <bd8186>; main; wait_for_workers: fuzzy process 21 terminated softly
2019-10-30 01:30:36 #1(main) <bd8186>; main; wait_for_workers: rspamd_proxy process 22 terminated softly
2019-10-30 01:30:36 #1(main) <bd8186>; main; wait_for_workers: controller process 23 terminated softly
2019-10-30 01:30:36 #1(main) <bd8186>; main; wait_for_workers: normal process 24 terminated softly
2019-10-30 01:30:36 #1(main) <bd8186>; main; wait_for_workers: fuzzy process 20 terminated softly
2019-10-30 01:30:36 #1(main) <bd8186>; main; main: terminating...
```

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 9.9 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Proxmox KVM |
| Server/VM specifications (Memory, CPU Cores) | 4Gb, 2vCPU |
| Docker Version (`docker version`) | 19.03.1 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | No |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
137 is oom.

Which image version of Rspamd is it?

**Comment by Roguyt** [comment]
It was 1.46, and I just updated it to the last version

**Comment by andryyy** [comment]
Keep on eye on it. Could be fixed in the latest Rspamd image.

**Comment by MAGICCC** [comment]
@Roguyt You may want to upgrade again, since https://github.com/mailcow/mailcow-dockerized/commit/7f8b13434dff6c636e6312ee98d98edffe149243 reduces the load even more hopefully :)

**Comment by Roguyt** [comment]
@MAGICCC I'll do the upgrade when the office is closed, and I'll let you know if it happens again or not :)
