### ISSUE TITLE
ipv6nat-mailcow recreation failed, system messed up

### ISSUE THREAD

**Issue by g0rbe** [mailcow/mailcow-dockerized#3109]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
Failed to recreate `ipv6nat`.

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
While updating with `./update.sh --ours`:
 ```
Recreating mailcowdockerized_ipv6nat-mailcow_1 ... error

ERROR: for mailcowdockerized_ipv6nat-mailcow_1  You cannot remove a running container 905668c51b3daeb6846234f4f04fa37ecaea299a21086cd2729bcf2a2c45a6e1. Stop the container before attempting removal or force remove
```

The `ipv6nat` successfully stopped, but in the `removing` stage, `ipv6nat` missing:

```
Stopping mailcowdockerized_ipv6nat-mailcow_1   ... done
Stopping mailcowdockerized_acme-mailcow_1      ... done
Stopping mailcowdockerized_rspamd-mailcow_1    ... done
Stopping mailcowdockerized_netfilter-mailcow_1 ... done
Stopping mailcowdockerized_nginx-mailcow_1     ... done
Stopping mailcowdockerized_php-fpm-mailcow_1   ... done
Stopping mailcowdockerized_dovecot-mailcow_1   ... done
Stopping mailcowdockerized_memcached-mailcow_1 ... done
Stopping mailcowdockerized_solr-mailcow_1      ... done
Stopping mailcowdockerized_sogo-mailcow_1      ... done
Stopping mailcowdockerized_postfix-mailcow_1   ... done
Stopping mailcowdockerized_watchdog-mailcow_1  ... done
Stopping mailcowdockerized_unbound-mailcow_1   ... done
Stopping mailcowdockerized_clamd-mailcow_1     ... done
Stopping mailcowdockerized_mysql-mailcow_1     ... done
Stopping mailcowdockerized_olefy-mailcow_1     ... done
Stopping mailcowdockerized_redis-mailcow_1     ... done
Stopping mailcowdockerized_dockerapi-mailcow_1 ... done
Removing mailcowdockerized_acme-mailcow_1      ... done
Removing mailcowdockerized_rspamd-mailcow_1    ... done
Removing mailcowdockerized_netfilter-mailcow_1 ... done
Removing mailcowdockerized_nginx-mailcow_1     ... done
Removing mailcowdockerized_php-fpm-mailcow_1   ... done
Removing mailcowdockerized_dovecot-mailcow_1   ... done
Removing mailcowdockerized_memcached-mailcow_1 ... done
Removing mailcowdockerized_solr-mailcow_1      ... done
Removing mailcowdockerized_sogo-mailcow_1      ... done
Removing mailcowdockerized_postfix-mailcow_1   ... done
Removing mailcowdockerized_watchdog-mailcow_1  ... done
Removing mailcowdockerized_unbound-mailcow_1   ... done
Removing mailcowdockerized_clamd-mailcow_1     ... done
Removing mailcowdockerized_mysql-mailcow_1     ... done
Removing mailcowdockerized_olefy-mailcow_1     ... done
Removing mailcowdockerized_redis-mailcow_1     ... done
Removing mailcowdockerized_dockerapi-mailcow_1 ... done
Removing network mailcowdockerized_mailcow-network
```
While trying to debug:

The update script script mess **everything** on my Gentoo.

`portage`  (package manager) and `etc-update` symlinked to docker-compose.
And i don't know the others...

**System information**

| Question | Answer |
| --- | --- |
| My operating system | Gentoo |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Hosted on a VPS that uses QEMU |
| Server/VM specifications (Memory, CPU Cores) | 2 core, 4GB RAM, 40GB storage |
| Docker Version (`docker version`) | 19.03.4 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | no |

**Comment by andryyy** [comment]
Create a PR to fix your Gentoo issues or don't use Gentoo. :)

Why would it mess with portage? And "etc-update"? Sym link to docker-compose? I don't think we do that.

For the container stuff:

```
docker-compose down
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -q)
systemctl restart docker # (or whatever init system Gentoo uses)
docker-compose up -d
```

**Comment by g0rbe** [comment]
> Why would it mess with portage? And "etc-update"? Sym link to docker-compose? I don't think we do that.

Yeah, thats seems pointless to me too.
Investigating what messed my system.
Anyway, creating `ipv6nat` with `update.sh` now works without my intervention :smiley:
