### ISSUE TITLE
Cannot start TLS: handshake failure (a new variation)

### ISSUE THREAD

**Issue by tzeejay** [mailcow/mailcow-dockerized#3110]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
Sending E-Mails to a specific domain fails all of a sudden. The receiving domain has received many E-Mails from my server, basically multiple every day, but just now it stopped working with TLS error as the stated reason.

**My issue is...**
I get a error email with this content:

```
This is the mail system at host [my email server].

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<example@test.com>: Cannot start TLS: handshake failure
Reporting-MTA: dns; [my email server]
X-Postcow-Queue-ID: 3D7F22602A0
X-Postcow-Sender: rfc822; [my email address]
Arrival-Date: Thu, 31 Oct 2019 16:15:29 +0100 (CET)

Final-Recipient: rfc822;example@test.com
Original-Recipient: rfc822;example@test.com
Action: failed
Status: 5.7.5
Diagnostic-Code: X-Postcow; Cannot start TLS: handshake failure
```

The only server where this has ever happened is this single one and it only started a couple of hours ago. I do think that they changed something on their end which causes this behavior but I wanted a sanity check before I go and blame them.

I noticed that the TLS cert has renewed a couple of hours ago. It's a Let's Encrypt one (I use one as well) but it may have auto renewed and is not the root of this issue, which I think it isn't.

In the logs I found this:

```
31.10.2019, 17:05:07 | warning | warning: TLS library problem: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../ssl/statem/statem_lib.c:1929:
31.10.2019, 17:05:07 | info | SSL_connect error to mail.test.com[ipv4 address]:25: -1
```

I tried probing their email server with openssl like so:

```
$ openssl s_client -starttls smtp -crlf -connect mail.test.com:25 -tls1
$ openssl s_client -starttls smtp -crlf -connect mail.test.com:25 -tls1_1
$ openssl s_client -starttls smtp -crlf -connect mail.test.com:25 -tls1_2

$ openssl s_client -starttls smtp -crlf -connect mail.test.com:587 -tls1
$ openssl s_client -starttls smtp -crlf -connect mail.test.com:587 -tls1_1
$ openssl s_client -starttls smtp -crlf -connect mail.test.com:587 -tls1_2
```

Everything on port 25 returned nothing for any version which I kind of expected and port 587 did everything exactly right. I get a certificate but only if I use TLS1. They don't support any of the newer, more secure TLS versions.

If I understand correctly in issue #2185 that it was noted at the very bottom that the security has been turned up by default, which is good IMO but maybe my issue here?

Could the issue be that my server wants to use TLS1.1 or TLS1.2 on port 587, their server doesn't support it though and so it tries to fall back to port 25 which also doesn't give my server anything useful to work with and so it errors out?

**System information**
Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Runs bare metal |
| Server/VM specifications (Memory, CPU Cores) | 16GB, 4 Cores |
| Docker Version (`docker version`) | 18.09.6 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | No reverse proxy or anything else setup. |
| OpenSSL version (`openssl version`) |  OpenSSL 1.1.1  11 Sep 2018 |

Further notes:
- I do run pfSense in front of it with all mandatory ports forwarded. Service has never been interrupted because of the firewall (at most due to misconfiguration, but I haven't touched it in months, so not applicable here).
- I verified that I could connect to the desired email server on both port 25 and 587 from my E-Mail server

Thank you very much for any help or input. Always happy to provide more information! This project is great

**Comment by tzeejay** [comment]
Alright after desperately requiring a fix for this today I read through all sorts of Postfix, OpenSSL & mailcow documentation and I finally found the issue. mailcow by default forces outgoing TLS *for all accounts*, which is the right default to have in my opinion.
As it turns out though, the other servers my E-Mail server was trying to communicate with are simply very badly configured and do not support the latest encryption cyphers.

This can be turned off on an account by account basis in the mailcow UI by going to `E-Mail Setup` -> `Mailboxes` -> Actions -> Enforce Outgoing TLS -> Deactivate.

The status for incoming and outgoing TLS enforcement can be check on by selecting the little + next to the account.

**Comment by andryyy** [comment]
It does not. 

This needs to be enabled per mailbox. Or set as default in vars.inc.php

**Comment by tzeejay** [comment]
@andryyy Could you specify what part exactly I'm wrong about with my message? I was thinking about submitting docs for this

**Comment by andryyy** [comment]
New mailboxes are created without TLS enforcements.

You can change the settings for new mailboxes in `data/web/inc/vars.inc.php`:

```
// Force incoming TLS for new mailboxes by default
$MAILBOX_DEFAULT_ATTRIBUTES['tls_enforce_in'] = false;

// Force outgoing TLS for new mailboxes by default
$MAILBOX_DEFAULT_ATTRIBUTES['tls_enforce_out'] = false;
```

**Comment by tzeejay** [comment]
That is good to know, thank you! Maybe I set it a while back and had forgotten that I did.

Anyways, the problem is solved for sure and I hope this helps somebody in the future if they run into the same issue.
