### ISSUE TITLE
mail forwarding, DKIM signing?

### ISSUE THREAD

**Issue by tchwpkgorg** [mailcow/mailcow-dockerized#3116]
I'm not sure how to set up this basic thing with mailcow-dockerized. On the other hand, I was able to set it up with old mailcow (before it became dockerized) with ease.

Prerequisites:

- mailcow-dockerized server up and running
- domain "some.example.com" added via mailcow-dockerized webgui
- a webserver (on a different host/IP) running a very simple MTA (no DKIM signing etc.)
- webserver has MTA set to relay mail through mailcow-dockerized (i.e. "relayhost = mailcow-dockerized-IP" in its Postfix config), sends mail from www-data@some.example.com to me@mydomain.tld
- mailcow-dockerized accepts the mail from the webserver, signs with DKIM, sends to the world (to me@mydomain.tld)

With mailcow-dockerized, I'm confused. I've tried adding webserver IP in "Forwarding hosts" ("Incoming messages are unconditionally accepted from any hosts listed here") - but messages are rejected.

If I add the webserver IP to mynetworks in main.cf, the message is accepted, but not signed with DKIM.

**Comment by mkuron** [comment]
Create a mailbox on Mailcow, disable sender verification for that mailbox, and use it to configure an authenticated relayhost on your web server. Don‘t use forwarding hosts/mynetworks here.
