### ISSUE TITLE
Opening folder "Other Users" fails in SOGo

### ISSUE THREAD

**Issue by wucke13** [mailcow/mailcow-dockerized#312]
Hello, I have on user how needs to interact with multiple Emailadresses. To do so, I set them up and configured a delegation to the users main Emailadress in SOGo. So far, sending in the name of other Mailboxes works like a charm. But when clicking on the "Other Users" Folder to read the Emails of the slave Mailboxes, SOGo shows `An error occured while communicating with the mail server`. The only thing I could find in the logs of SOGo is the following:
```
[ERROR] <0x0x55e2ed1a6b60[NGImap4Connection]> could not select URL: imaps://user%40domain.com@dovecot/Shared/?tls=YES: {RawResponse = "{ResponseResult = {description = \"Mailbox doesn't exist: Shared (0.001 + 0.042 + 0.042 secs).\"; result = no; tagId = 9; }; ok = {CLOSED = \"Previous mailbox closed.\"; }; }"; reason = "Mailbox doesn't exist: Shared (0.001 + 0.042 + 0.042 secs)."; result = 0; }
```

Why is that?

I have to add, that all of these Mailboxes are on different domains, so to make them aware of each other I had to add the following to the sogo.conf:
```
SOGoDomainsVisibility = (
        (domain.com, other-domain.de, yet-more-domain.tk ),
    );
```

Also worth mentioning is, that I had to disable sendercheck on the master Mailbox for the slave Mailboxes domains (there is no other users on these domains, that's why I disable the sendercheck per domain).

So, what needs to be changed, so that the Master Mailbox is able to see the slaves Mailboxes folder under "Other Users" folder?

**Comment by andryyy** [comment]
You need to share the mailboxes with that user. The username will appear in "Shared" then. 

"Shared" is a shared namespace, it is listed as mailbox but it isn't a real mailbox itself.

**Comment by wucke13** [comment]
I just saw the User Privilegs menu in the contextmenu of folders. However, even after allowing everything for the master user for one folder of a slave user, the error while clicking on "Other Users" folder from the master user persists. Was it that what you meant by sharing the Mailbox?

**Comment by andryyy** [comment]
It is still a shared namespace. It is listed, but not a mailbox. It just provides the shared items. It cannot be opened.

**Comment by Braintelligence** [comment]
@andryyy So you are saying that mailboxes will appear as "subfolders" there but the parent folder can never be used?

**Comment by andryyy** [comment]
Yes, it is just a dummy. A shared namespace that is not an inbox. :)

**Comment by Braintelligence** [comment]
Kinda weird, though, that you can click on it and trigger an error =/...

**Comment by wucke13** [comment]
I am sorry to say, but I still did not understand what I have to do to be able to open a folder in account from another account?

**Comment by andryyy** [comment]
![1](https://i.imgur.com/B9Qoqk8.png)
![2](https://i.imgur.com/WRgsOn5.png)
![3](https://i.imgur.com/GhJJTt7.png)
![4](https://i.imgur.com/uZVbjIf.png)

> Also worth mentioning is, that I had to disable sendercheck on the master Mailbox for the slave Mailboxes domains (there is no other users on these domains, that's why I disable the sendercheck per domain).

That's part of the docs. :)

**Comment by wucke13** [comment]
So then my issue really is an issue. I wasn't sure whether I read you instructions correct, but I did tick all of the boxes you did for the regarding master user on the regarding folder in slaves mailbox, and indeed the behavior is exactly as described, popping up `An error occured while communicating with the mail server` when clicking on "Other Users" from the master mailbox. The same error pops up when a user, who has never been mentioned on any shares by other users clicks on "Other Users" folder. Furthermore it might be worth mentioning that this does happen even if both master and slave mailbox are on the same domain, which implicates that this is not depended on `SOGoDomainsVisibility = (
        (domain.com, other-domain.de, yet-more-domain.tk ),
    );` setting.

**Comment by andryyy** [comment]
Click on the folder icon.

**Comment by wucke13** [comment]
Now I feel dumb. This is not the first time that "clicking on the label doesn't do anything but clicking on the icon does" fools me. Thanks for your patience!

**Comment by andryyy** [comment]
Naaa, no problem at all. Happens to a lot of users. This icon should have at least a plus symbol. :)

**Comment by Braintelligence** [comment]
Actually this is a brilliant idea. SOGo people should add a + icon to the folder...
