### ISSUE TITLE
Nextcloud Installation: Wrong SSL certificate

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#3121]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I installed nextcloud with the nextcloud.sh script from the helper-scripts. The nextcloud should run on the same IP address on the server but on a different subdomain (mailserver: mail.my.domain, nextcloud: cloud.my.domain). After installation I tried to reach the nextcloud instance. Everything is working fine. The only problem is a certificate warning. The nextcloud.sh script sets the certificate of the mailserver (mail.my.domain) and is not generating a new one for the domain cloud.my.domain. I think this is a problem that should be fixed. Is it possible to get a letsencrypt certificate for cloud.my.domain from the acme container?

So I also tried another thing: To avoid a certificate error I purged the present nextcloud and installed a new one with the domain mail.my.domain/nextcloud. While trying to reach this subdomain I got an 404 error code. But I can see that the webserver tries to reach the login page from nextcloud (https://mail.my.domain/nextcloud/index.php/login)  I don't know what is going wrong there. Where can I start with debugging? 
 (This problem is not so important then the first one. I'd like to have the nextcloud at cloud.my.domain. If there isn't any solution for it I want to debug the second solution which failed)

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*

Install nextcloud with the nextloud.sh helper-script.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |

The rest of this table should be not important for my problem I think.

**Comment by mkapra** [comment]
Beside my problem I found the following section in the 'nextcloud.sh' script. I don't find any variable like 
'$NC_UPDATE'. Is this a feature which is not fully implemented?

https://github.com/mailcow/mailcow-dockerized/blob/a3b4c3176362c856574f4e3647f431f4dbd64fba/helper-scripts/nextcloud.sh#L56-L83

**Comment by andryyy** [comment]
The update feature was removed. You should do them via UI or manually. :)

This is a simple helper scripts. They only help. You can add the new hostname to ADDITIONAL_SAN and run "up -d". 

If you are redirected incorrectly, you probably have a cached redirect in your browser. Try with "curl bla.bla.com -I" and check what happens server side.

**Comment by mkapra** [comment]
@andryyy 

> The update feature was removed. You should do them via UI or manually. :)

I already thought that and was a little bit confused while reading the script :D.

> This is a simple helper scripts. They only help. You can add the new hostname to ADDITIONAL_SAN and run "up -d".

Thank you that worked.
