### ISSUE TITLE
Attachment file not found

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#3122]
Dear team,

  yesterday I faced a strange problem and did not found a solution yet. Somehow the attachments  are not found, in the log I see the following:

imap(my@address)<5712><5jC77YOWjddeFQdW>: Error: Mailbox INBOX: UID=130387: read(attachments-connector(zlib())) failed: read(/var/attachments/4b/25/4b25e2dc9c052c594052ef5273dd6f5ff5f55b97-40c51913c35e825d94710000e3f897e6[base64:19 b/l]) failed: open(/var/attachments/4b/25/4b25e2dc9c052c594052ef5273dd6f5ff5f55b97-40c51913c35e825d94710000e3f897e6) failed: No such file or directory (FETCH BODY[])

The dir /var/attachments is not empty, there are files, but I can not figure out how to correct the links?

Any idea what should be the problem? I tried to restart the docker, the VM as well.

  Kind Regards,
Zoltan

**Comment by andryyy** [comment]
Hi, we use maildir. There should never be content. If you modified it to mdbox and need support, try the Telegram channel. :)

**Comment by Viktova** [comment]
Please post your configuration,
What have you done in terms of installation

**Comment by beckzg** [comment]
I use this on all of our installs and never had any errors:

[shared_namespace.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/3805472/shared_namespace.conf.txt)
[extra.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/3805473/extra.conf.txt)
[dovecot.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/3805474/dovecot.conf.txt)
