### ISSUE TITLE
Run an init inside the container 

### ISSUE THREAD

**Issue by rockhouse** [mailcow/mailcow-dockerized#3125]
Docker and the PID 1 zombie reaping problem is known and well [documented](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/). Aside from properly handling zombie processes, it also means that signals are properly passed to the container process.

Turns out that Docker actually ships with tini [now](https://docs.docker.com/compose/compose-file/#init). So all it needs is a little adjustment in the docker-compose scripts and add: `init: true`, are you guys open to such a change?

**Comment by ntimo** [comment]
This is not going to work for us, since we sill use a older compose version 2.1 and we would need to update the compose file for this. And for now I personally see no reason to do so. I am also not quite sure if all compose 2.1 features we use are present in 3.1.

**Comment by rockhouse** [comment]
One of the reasons to update would be obviously to support init ;) Having worked with newer and older versions of compose they normally are pretty much compatible, only some features might be deprecated and if they are then this is a good reason to migrate those as well of course.

**Comment by rockhouse** [comment]
So a quick check revealed that only the option `oom_kill_disable` is not supported by the new 3.x versions of docker-compose. The rest works just fine it seems. And after reading [this](https://stackoverflow.com/questions/48618431/what-does-oom-kill-disable-do-for-a-docker-container) and [this](https://www.reddit.com/r/devops/comments/9pc5qu/disable_oom_killer_in_compose/) I would actually argue that option should be removed. 

Quoting: "First of all, you don’t want to do this to a non-system process (e.g. your application) bc it’s potentially risky as this can hang up your container completely. Leave the restarting process to the systemd inside your container and optimize your app so it would not consume that much memory."

**Comment by OpenLarry** [comment]
Is the `enable_ipv6` network option supported by docker-compose 3? In my opinion, the IPv6 option is still not available in docker swarm and therefore not available in docker-compose 3. 😕

That's the reason why I'm also using docker-compose 2 almost everywhere.

**Comment by MAGICCC** [comment]
@OpenLarry 
Nope, `enable_ipv6` is not supported on v3
https://docs.docker.com/v17.09/compose/compose-file/#enable_ipv6

**Comment by andryyy** [comment]
Most resource controlling features are only available in v2. 

v3 seems to be adjusted for swarm and cluster usage.

**Comment by rockhouse** [comment]
Closing this now as v3 is not supporting ipv6 but I would still argue we should get rid of `oom_kill_disable`.

**Comment by andryyy** [comment]
Why? Because of a SO and Reddit post? :/

The option is not pure evil. It has a reason it exists. It can be dangerous to run every application with this flag. But we just want the API wrapper to die last. There are plenty of procs to sacrifice. There's never been a problem for anyone with dockerapi-mailcow eating all memory and suddenly killing the machine. The advantages of running it with this flag overweight the possible problems.

If you really want to change code so bad, search for feature requests. :)

**Comment by rockhouse** [comment]
It is not evil but having an API running while the rest of the system is un-usable also makes no sense at all. You might argue the nginx proxy is even more important to actually be able to query the api? Also the OOM killer is only enabled if the host has memory overcommit enabled, the mailcow project has no control over that. 

How about the official docker documents hope that is convincing enough: "You should not try to circumvent these safeguards by manually setting ... `--oom-kill-disable` on a container." (https://docs.docker.com/config/containers/resource_constraints/)

On top of that as I understand the docs `--oom-kill-disable` actually requires also `-m`, I do not see that set either. 

And yes I want it disabled so I forked the project and removed it in my version, but I believe in contributing back so that is why I still make an effort to get it merged upstream. I am also willing to provide a PR, this issue was just to gauge interest first ;)

**Comment by andryyy** [comment]
We want to have dockerapi-mailcow still working until the server fails. In a worst-case scenario we are able to restart failing services until admins are able to get their hands on it. It has worked for me several times.

There is a reason it exists and I explained why we use it. Again: I understand what it does and what not.

It does not help to google for reasons to confirm your opinion. Try to understand why **we** use it and why **we** might want to have dockerapi-mailcow killed last.

You don't see "-m" because it's not an option of docker-compose...

```
# docker inspect $(docker ps -qf name=dockerapi) | grep -i oom
            "OOMKilled": false,
            "OomScoreAdj": 0,
            "OomKillDisable": true,
```

**Comment by rockhouse** [comment]
I get your point why and when you use it, I am just saying it doesn't work. 

> The host can run out of memory with or without the -m flag set. But it's also irrelevant as --oom-kill-disable does nothing unless -m is passed." [Source](https://github.com/moby/moby/issues/14440#issuecomment-119243820)

So as you confirmed the image is running without the `-m` flag passed, it will not do anything. 
Again just trying to help if you are not interested fine by me.
