### ISSUE TITLE
JAN/2020 - Planned deactivation of TLS1.0 and TLS1.1 in Dovecot (affects POP3 and IMAP)

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#3127]
TLS1.0 and TLS1.1 is an obsolete encryption standard and [should no longer be used ](https://tools.ietf.org/id/draft-moriarty-tls-oldversions-diediedie-00.html).
Currently only TLS 1.2 and TLS1.3 are recommended. 

**Dovecot:**
For Dovecot the change was already made but then [reverted.](https://github.com/mailcow/mailcow-dockerized/commit/69f54b99a1bd026ec24b36fbfbee83c2652f2ffa) 
The change was made on 3 March, if the corresponding programs (e.g. nextcloud user_external plugin) have not been updated until now, the programs are simply obsolete and should no longer be considered. 

**Therefore "ssl_min_protocol" (under data/conf/dovecot/dovecot.conf) should be set to "TLSv1.2" again.** This also corresponds to the recommendations here: https://cipherli.st/

You can use the following tools for testing: 
- https://tls.imirhil.fr/, -
- https://www.immuniweb.com/ssl/, -
- https://testssl.sh/

**Nginx:**
For Nginx [TLS1.0/1.1 have already been deactivated.](https://github.com/mailcow/mailcow-dockerized/blob/a3b4c3176362c856574f4e3647f431f4dbd64fba/data/conf/nginx/includes/site-defaults.conf#L6) 

**Postfix**
[Even Postfix still uses TLS1.0/1.1](https://github.com/mailcow/mailcow-dockerized/blob/a3b4c3176362c856574f4e3647f431f4dbd64fba/data/conf/postfix/main.cf#L149), but here you have to be happy if smtp is encrypted at all. So a bad encryption is better than none at all.

**Comment by andryyy** [comment]
Yes, should be removed. I planned this for Windows 7 EOL.

**Comment by christianbur** [comment]
OK, that should be on [14 January 2020](https://support.microsoft.com/de-de/help/4057281/windows-7-support-will-end-on-january-14-2020).

**Comment by andryyy** [comment]
Hope that's fine for you guys. :) I don't see any reason to keep it afterwards besides older devices, that poll via imap/pop3. It is quite easy to revert manually, so ... should work.

**Comment by Braintelligence** [comment]
@andryyy Up to which Microsoft Outlook version will we experience repercussions for not providing TLS 1.0/1.1 anymore? 🙈 I'm not against it, just wanting to assess possible problems with current clients. 😭

**Comment by MAGICCC** [comment]
Even Office 2010 will be EoL end of October 2020, so people who are still using this acient version should upgrade!

**Comment by Braintelligence** [comment]
@MAGICCC I know companies with four digit number of employees still running on Office 2010, so albeit I agree with you it's just reality that it still is being used.

Again, I don't disagree with this step, I'm just asking if anyone can tell for sure what the minimum compatible Outlook will be then.

**Comment by andryyy** [comment]
Do most of your clients use EAS or IMAP? For EAS TLS 1.2 is required since we pushed the changes to Nginx a while ago. If they didn't complain until today, they are probably fine. 

Not sure about IMAP. I think you can patch Windows 7 to use TLS 1.2 anyway. There should be tutorials for that. 

Can you check the compatibility online and report back, @Braintelligence ? I think we should at least mention it here.

**Comment by christianbur** [comment]
For Outoook (under Windows 7) TLS1.2 can be activated as well. 

- https://blogs.technet.microsoft.com/schrimsher/2016/07/08/enabling-tls-1-1-and-1-2-in-outlook-on-windows-7/
- https://www.greengeeks.com/tutorials/article/how-to-enable-tls-1-1-and-1-2-in-outlook-windows-7/
- https://www.admin-enclave.com/en/articles/windows/402-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in-winhttp.html
- https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

with Dovecot as example:
- http://www.rainingforks.com/blog/2015/how-to-allow-outlook-to-connect-with-tlsv1-1tlsv1-2.html

**Comment by Braintelligence** [comment]
None use EAS, only IMAP. Windows 7 is not really the problem; I know even one person using Office 2003 for some reasons on a Windows 10 machine 🙈 .

**Comment by christianbur** [comment]
Could we also upgrade the [Postfix submission port (587 and 465)](https://github.com/mailcow/mailcow-dockerized/blob/a8a71d2d42d8917f4cd3a464c66d26059d9e350f/data/conf/postfix/master.cf#L20) to min. TLS 1.2?

current: `smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3`
future:   `smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,!TLSv1,!TLSv1.1`

also "[smtpd tls-wrapped (smtps) on 465/tcp](https://github.com/mailcow/mailcow-dockerized/blob/a8a71d2d42d8917f4cd3a464c66d26059d9e350f/data/conf/postfix/master.cf#L12)"

**Comment by andryyy** [comment]
It is :)

https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/main.cf#L143

**Comment by andryyy** [comment]
Oops, it is not. Deleted my previous post. We can and should. 

Edit: yes, smtps and submission

**Comment by christianbur** [comment]
Another suggestion, currently there is an extra.cf to make custom changes to the postfix config (main.cf), but for the master.cf this doesn't work. 
I used to define my own variables in the main.cf and then use them in the master.cf. 

```
main.cf
port_587_smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,!TLSv1,!TLSv1.1

master.cf
...
-o smtpd_tls_mandatory_protocols=$port_587_smtpd_tls_mandatory_protocols
...
```
like here in [the example](https://thomas-leister.de/mailserver-debian-stretch/ ) with $mua_client_restrictions, $mua_sender_restrictions, $mua_relay_restrictions

so you should be able to change the parameter port_587_smtpd_tls_mandatory_protocol s in extra.cf by yourself, right? 
This would be useful, since there may be some systems with old clients that need TLS1/1.1.

**Comment by andryyy** [comment]
That's a good idea, I will add it.

**Comment by christianbur** [comment]
Maybe you could already make the changes now with "port_587_smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3" (No change of the system behavior), so it would be possible to change the TLS setting now as a custom change in extra.cf.

**Comment by andryyy** [comment]
Yes, I added it for smtps and submission. I also added a filter for syslog-ng to not be annoying with overrides.

Testing it now.

**Comment by andryyy** [comment]
Looks good. Can you also run a test?

**Comment by christianbur** [comment]
So the[ two new variables](https://github.com/mailcow/mailcow-dockerized/commit/4a36eb014ca09b57ef67f5d257a090cc36ffd598#diff-dc3852510e4a52f06f0196219193c793R198) work for me (test with testssl.sh). 

Question:
 - Why is "smtputf8_enable = no" a fixed custom variable in main.cf?
 - didn't you want to set values for syslog in the master.cf ? I must have misunderstood. 
      -o syslog_name=postfix/submission
      -o syslog_name=postfix/smtps

**Comment by andryyy** [comment]
The smtputf8 option was a mistake.

I added your options, that's a good idea, thanks. Will push in a bit.

**Comment by mkuron** [comment]
> The smtputf8 option was a mistake.

It‘s actually still there:

https://github.com/mailcow/mailcow-dockerized/blob/d57e2b58c19645a9b12489a76df4cce470fbf46e/data/conf/postfix/main.cf#L190

I thought Dovecot LMTP didn‘t support UTF8 and we thus actually need to disable this option?

**Comment by andryyy** [comment]
Yes, it's difficult. Setting it to no will completely disable Umlaut domains. Even the rewritten domains were rejected. I have no glue so far. We could switch to LDA.

**Comment by christianbur** [comment]
But LDA is outdated, nowadays you should use LMTP.
same problem: https://gehirn-mag.net/das-xn-mrchen-bua-vom-punycode/
                         https://www.virtualmin.com/node/59765

**Comment by andryyy** [comment]
Yes, indeed. But without full UTF8 support, it is a bit tricky. They are working on it... :/

**Comment by andryyy** [comment]
We should create a blame list. 😄 

I just found out Acronis True Image **2020** is not able to initiate a TLS 1.2 connection.

**Comment by lucianlazar1983** [comment]
Also some Pop-collector software for exchange servers will simply cease to work but hey, they might just start ditching exchange for mail cow 😊 Jokes aside, everyone should support new, safer  standards

**Comment by ghost** [comment]
@andryyy The Windows 7 EOL date is today.

**Comment by whalehub** [comment]
@andryyy Any update on this?

**Comment by technophobia** [comment]
i have lots of issues with SMTPUTF8 set to yes. I disabled it and all the mails are going through.
Is it needed for anything else beside the umlaut domains feature?

**Comment by andryyy** [comment]
That's really strange. We need to keep an eye on it. I have seen it the other way round, too. If someone wants to dig deeper into it, go ahead. :) It would be very welcome!

TLS 1.0 and 1.1 will be deactivated shortly.

**Comment by andryyy** [comment]
Aaaand it's gone.

**Comment by marrco** [comment]
sorry to ask. Does it mean that anyone using Windows 7 (default configuration) is now not able to use the mail server (webmail, pop3 and imap) anymore?

I know Windows 7 is EOL, But Google first result suggests that in 2020 it's market share is about 30% among desktop OS

**Comment by christianbur** [comment]
And what’s about Postfix (submission) and an info in the blog and in the documentation how to reactivate Tls 1.0 and Tls 1.1 via the custom files?

**Comment by andryyy** [comment]
That info is about to come.

**Comment by andryyy** [comment]
https://mailcow.email/2020/02/12/tls-1-0-and-1-1-is-now-disabled-for-pop3-s-imap-s-smtps-and-submission/

**Comment by andryyy** [comment]
And https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/

Thank you guys. I will close this issue, which does not mean it is closed for discussion. :)

**Comment by Conan179** [comment]
I have a problem with reeanble the TLS 1.0 and TLS 1.1.
I use Opera Mail on Win10 (Didn't find a mail client that works like this old one.)
The files:
/opt/mailcow-dockerized/data/conf/postfix/extra.cf
and
/opt/mailcow-dockerized/data/conf/dovecot/extra.cf
make it, with the content
submission_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
and
ssl_min_protocol = TLSv1
after restarting, i cand connect with oepra mail.

**Comment by andryyy** [comment]
extra.conf for Dovecot

**Comment by Conan179** [comment]
-.-
I'm sorry...

i found a another error on my settings.

I'm starting to feel like I'm being kidnapped by my system.

my secnd error was 
ssl_min_protocol = TLSv1ssl_min_protocol = TLSv1
in the /opt/mailcow-dockerized/data/conf/dovecot/extra.conf

But I still get a connection.

**Comment by andryyy** [comment]
What about `git diff origin/master data/conf/dovecot/ data/conf/postfix/`? Did you restart the services?

**Comment by Conan179** [comment]
No problem:

```
diff --git a/data/conf/dovecot/dovecot.conf b/data/conf/dovecot/dovecot.conf
index b1aea4de..7ac64cca 100644
--- a/data/conf/dovecot/dovecot.conf
+++ b/data/conf/dovecot/dovecot.conf
@@ -272,7 +272,7 @@ service pop3-login {
 service imap {
   executable = imap imap-postlogin
   user = vmail
-  vsz_limit = 1G
+  vsz_limit = 3G
 }
 service managesieve {
   process_limit = 256
@@ -315,6 +315,7 @@ plugin {
   acl = vfile
   fts = solr
   fts_autoindex = yes
+  fts_autoindex_exclude = \fail2ban
   fts_solr = url=http://solr:8983/solr/dovecot-fts/
   quota = dict:Userquota::proxy::sqlquota
   quota_rule2 = Trash:storage=+100%%
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index d31702e7..30b884ef 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -200,3 +200,5 @@ smtpd_client_recipient_rate_limit = 50
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #

+submission_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
+smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
``` 

I have restaret with
docker-compose restart postfix-mailcow dovecot-mailcow
and try it witch
docker-compose down && docker-compose up -d

**Comment by andryyy** [comment]
What's the output for `docker-compose exec dovecot-mailcow doveconf ssl_min_protocol`? 

And what does dovecot-mailcow log, when you try to connect with Opera Mail?

I'm installing it myself right now. You can also send me the server name to info@servercow.de, please, so I can check wether 1.0 is available.

**Comment by andryyy** [comment]
Try this in `data/conf/dovecot/extra.conf` and restart dovecot-mailcow afterwards:

```
ssl_min_protocol = TLSv1
ssl_cipher_list = ALL:!kRSA:!SRP:!kDHd:!DSS:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH
```

I installed Opera Mail for this to test. :-D

**Comment by Conan179** [comment]
`root@hostname:/opt/mailcow-dockerized# docker-compose exec dovecot-mailcow doveconf ssl_min_protocol
ssl_min_protocol = TLSv1
`
I have send a mail to you.

i know, opera mail is old, unsecured. but unfortunately I have not found any other mail client that is like the opera mail client...

**Comment by christianbur** [comment]
For all those who want to get rid of even more weak crypto, you can also disable the CBC Cipher Suites. For Dovecote this is very easy:

```
# cat ../mailcow-dockerized/data/conf/dovecot/extra.conf 
ssl_cipher_list = HIGH:!RSA:!PSK:!LOW:!aNULL:!eNULL:!SHA1:!SHA256:!SHA384
```
You could check it with [testssl.sh: ](https://testssl.sh/)   (https://github.com/drwetter/testssl.sh/issues/1157)
`"Obsolete: SEED + 128+256 Bit CBC cipher    --------   not offered"`


https://www.ssllabs.com also classifies CBC as weak (only HTTPS test, no imaps).


**UPDATE:**


To disable CBCs also in Postfix, changes to mailcow would be necessary. 

```
# docker exec mailcowdockerized_postfix-mailcow_1 postconf |grep tls_high_cipherlist
tls_high_cipherlist = aNULL:-aNULL:HIGH:@STRENGTH
```


data/conf/postfix/master.cf 
```
  #-o smtpd_tls_mandatory_protocols=$smtps_smtpd_tls_mandatory_protocols
  -o tls_high_cipherlist=$submission_tls_high_cipherlist


  #-o smtpd_tls_mandatory_protocols=$submission_smtpd_tls_mandatory_protocols
  -o tls_high_cipherlist=$smtps_tls_high_cipherlist
```

data/conf/postfix/main.cf 
```
submission_tls_high_cipherlist = aNULL:-aNULL:HIGH:@STRENGTH
smtps_tls_high_cipherlist = aNULL:-aNULL:HIGH:@STRENGTH

#INFO: "smtps_tls_high_cipherlist = $tls_high_cipherlist" is not working. 
```

data/conf/postfix/extra.cf 
```
submission_tls_high_cipherlist = HIGH:!RSA:!PSK:!LOW:!aNULL:!eNULL:!SHA1:!SHA256:!SHA384
smtps_tls_high_cipherlist = HIGH:!RSA:!PSK:!LOW:!aNULL:!eNULL:!SHA1:!SHA256:!SHA384
```

**Comment by christianbur** [comment]
@andryyy 

[In the current c't (2/2022)](https://www.heise.de/select/ct/2022/2/2011113555115048413), the cipher-suites for TLS are explained and recommendations are given. Maybe we should adapt Mailcow to the recommendations. 


Nginx:
https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1k&guideline=5.6

Dovecot:
https://ssl-config.mozilla.org/#server=dovecot&version=2.3.9&config=intermediate&openssl=1.1.1k&guideline=5.6

Postfix (only submission):
https://ssl-config.mozilla.org/#server=postfix&version=3.4.8&config=intermediate&openssl=1.1.1k&guideline=5.6


---
I have checked port 587 (Postrix submission), the cipher used does not match the recommendations (e.g. SHA -> SHA1).

Test-command: testssl --starttls smtp mx1.example.de:587

```
...
 Cipher order
    TLSv1.2:   ECDHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-CHACHA20-POLY1305 DHE-RSA-CHACHA20-POLY1305 DHE-RSA-AES256-CCM8 DHE-RSA-AES256-CCM ECDHE-ARIA256-GCM-SHA384 DHE-RSA-ARIA256-GCM-SHA384
               ECDHE-RSA-AES256-SHA384 DHE-RSA-AES256-SHA256 ECDHE-RSA-CAMELLIA256-SHA384 DHE-RSA-CAMELLIA256-SHA256 ECDHE-RSA-AES256-SHA DHE-RSA-AES256-SHA DHE-RSA-CAMELLIA256-SHA AES256-GCM-SHA384 AES256-CCM8 AES256-CCM
               ARIA256-GCM-SHA384 AES256-SHA256 CAMELLIA256-SHA256 AES256-SHA CAMELLIA256-SHA ECDHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-CCM8 DHE-RSA-AES128-CCM ECDHE-ARIA128-GCM-SHA256
               DHE-RSA-ARIA128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 DHE-RSA-AES128-SHA256 ECDHE-RSA-CAMELLIA128-SHA256 DHE-RSA-CAMELLIA128-SHA256 ECDHE-RSA-AES128-SHA DHE-RSA-AES128-SHA DHE-RSA-CAMELLIA128-SHA AES128-GCM-SHA256
               AES128-CCM8 AES128-CCM ARIA128-GCM-SHA256 AES128-SHA256 CAMELLIA128-SHA256 AES128-SHA CAMELLIA128-SHA 
    TLSv1.3:   TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 
...
```

**Comment by andryyy** [comment]
I agree. Would you like to create a tested PR? I can review it. Currently in hospital.

**Comment by christianbur** [comment]
I'll take care of it the next few days.
Get well soon.

**Comment by andryyy** [comment]
That would be amazing. Thank you!
