### ISSUE TITLE
Accessing pop3 with plaintext auth

### ISSUE THREAD

**Issue by dreganism** [mailcow/mailcow-dockerized#3130]
I did the dockerized install an it works well, but I need to use plaintext to login to port 110 to verify it's available using an outside tool the checks on a pulse. I set disable_plaintext_auth = no, but I still can't' logon with a plaintext username and password.

Did I miss some other configuration step?

Thanks,
Dave

**Comment by andryyy** [comment]
Did you restart Dovecot? 

Better use

```
remote 1.2.3.4/32 {
   disable_plaintext_auth = no
}
```
