### ISSUE TITLE
JMAP support / Dovecot update

### ISSUE THREAD

**Issue by alexanderadam** [mailcow/mailcow-dockerized#3133]
**Is your feature request related to a problem? Please describe.**
Well, it's basically [how email should be delivered in 2019](https://jmap.io/).

**Describe the solution you'd like**

An upgrade to Dovecot `2.3.x`. The [_current_ stable release is `2.3.8`](https://www.dovecot.org/download#c69).
See also [this announcement](https://www.dovecot.org/list/dovecot-news/2016-March/000313.html).

There's more on jmap [on jmap.io](https://jmap.io/).

**Comment by mkuron** [comment]
We are already running Dovecot 2.3: https://github.com/mailcow/mailcow-dockerized/blob/b9aa1bf3729a493ab5b8a281ba3896aabe875cda/data/Dockerfiles/dovecot/Dockerfile#L81. I don't think JMAP made it into the 2.3 release though. I can't find mention of it anywhere in Dovecot's source code and https://jmap.io/software.html still lists Dovecot as planned. https://dovecot.org/pipermail/dovecot/2019-January/114489.html and https://dovecot.org/list/dovecot/2019-July/116415.html confirm that. So there is not much we can do for now. Of course, one _could_ use a proxy like https://github.com/jmapio/jmap-perl, but that project hasn't been touched in more than a year and may be dead. Is there any specific reason you need JMAP, other than "it is nicer than the traditional protocols"? Judging by https://jmap.io/software.html, client and server support for JMAP is still very limited.

**Comment by Braintelligence** [comment]
Just to add a statement to your linked announcement: https://dovecot.org/pipermail/dovecot/2019-May/115972.html

**Comment by alexanderadam** [comment]
Sorry, my fault. I guess I misinterpreted the Docker tag ([1](https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml#L178) / [2](https://hub.docker.com/r/mailcow/dovecot/tags)).

Are those two Dockerfiles related?

- [docker hub](https://hub.docker.com/r/mailcow/dovecot/dockerfile)
- [github](https://github.com/mailcow/mailcow-dockerized/blob/b9aa1bf3729a493ab5b8a281ba3896aabe875cda/data/Dockerfiles/dovecot/Dockerfile#L81)

**Comment by ntimo** [comment]
@alexanderadam The Dockerfile here https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/Dockerfile on GitHub is the one that is used to build the container. The one on the Docker Hub seems quite old and probably is a left over from old times.

**Comment by alexanderadam** [comment]
Good to know, in that case someone should probably update or remove the `Dockerfile` to avoid more confusion. :wink: 

I find it already confusing that the tag / version of the dovecot container doesn't represent the included dovecot version.

**Comment by andryyy** [comment]
We change the scripts and functions of the containers quite often. It does not make sense to tag the image versions equal to the Dovecot version. You can also rebuild an image anytime. This would upgrade Dovecot (if a new version was available in the meantime). So... no.

**Comment by alexanderadam** [comment]
⬇️⬇️⬇️⬇️⬇️
> someone should probably update or remove the Dockerfile to avoid more confusion. :wink:

⬆️⬆️⬆️⬆️⬆️

**Comment by andryyy** [comment]
I think it is read from the repo, if not: don't care. We don't use that to maintain code or provide a Dockerfile.
