### ISSUE TITLE
Zeyple integration

### ISSUE THREAD

**Issue by alexanderadam** [mailcow/mailcow-dockerized#3134]
**Is your feature request related to a problem? Please describe.**
This is more or less the continuation of the feature [that was once already integrated](https://github.com/mailcow/mailcow-dockerized/issues/1791#issuecomment-427524642).
[It didn't support python 3 and was not working well with mailcow](https://github.com/mailcow/mailcow-dockerized-docs/pull/60#issuecomment-552107773) and was therefore removed ([1](https://github.com/mailcow/mailcow-dockerized/commit/3136e020f6c0afed83feaddddbd05fff2029fc92), [2](https://github.com/mailcow/mailcow-dockerized/commit/abf33b75f44dff7b60c020ca8a350309786afc92)).

**Describe the solution you'd like**
A working Zeyple integration (= encryption for outgoing emails) (or maybe a similar replacement).

**PS:** Support for [MailCrypt user encryption mode](https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/#encrypted-user-keys), maybe even in combination with [Userli](https://github.com/systemli/userli), would be nice as well, but I guess this would be another issue. :wink:

**Comment by dragoangel** [comment]
@alexanderadam did you read about efail?

**Comment by alexanderadam** [comment]
I did but I'm not sure how it is related to this issue here.

<details>
  <summary>But you can click here to read my opinion on that.</summary>

AFAIR it is only possible to decrypt an encrypted email, if the attacker is able to modify this email and also only if the email client is configured to show HTML email as default **AND** loads external content by default.
IMHO email clients like [Thunderbird](https://support.mozilla.org/en-US/kb/remote-content-in-messages) or [Outlook](https://support.office.com/en-us/article/automatically-download-pictures-from-the-internet-in-outlook-for-mac-3e61c1fe-02f7-4280-9aef-9bc0233b564c) won't load external content by default and show something like this in such cases:
![Screenshot_20191123_112826](https://user-images.githubusercontent.com/372620/69477279-88f9d380-0de4-11ea-98ff-d36bd818f8a4.png)
In general [most (or even all?) email clients support this](https://www.imore.com/how-disable-image-loading-gmail-apple-mail-outlook-and-more).

So encrypting emails it is basically like having a seat belt, airbags and other security features in a car.
Meaning: it definitely won't automatically avoid any crash or injuries. Driving a car will stay dangerous, so is sending an email. But it will _improve_ the security anyway.

Claiming that you don't have to use seat belts, airbags, a maintained car etc. because you could die anyway doesn't make much sense. Because avoiding them will simply _increase_ the chances of dying in an accident.

Similarly claiming that you shouldn't encrypt your emails because an attacker could decrypt emails under certain conditions does not make sense either.
Because the emails are still more secure if the necessary conditions for the attack cannot be fulfilled.

What's the point in skipping all security mechanisms because some insecurities still stay?
Sending _unencrypted_ emails is probably still worse than any other way of communicating.
</details>

**Comment by shumink** [comment]
https://protonmail.com/blog/pgp-vulnerability-efail/
