### ISSUE TITLE
Can't receive emails: Recipient address     rejected: User unknown in local recipient table (in reply to RCPT TO     command)

### ISSUE THREAD

**Issue by linuxgoose** [mailcow/mailcow-dockerized#3138]
Hello, I just installed mailcow-dockerized and set up my DNS records. I can send emails just fine. However, whenever I try to send an email (from outside Mailcow) to the mailbox on Mailcow I receive this error. 

Recipient address
    rejected: User unknown in local recipient table (in reply to RCPT TO
    command)

Any ideas or where to start? I am spinning wheels.

**Comment by tinect** [comment]
DNS records on nameservers needs up to 48hours to get your new record. Sounds like the mails arr sent to server you had before?

**Comment by linuxgoose** [comment]
Nope, was a brand new server/never used before. I thought I had a local postfix, but I didn't.

Honestly not sure what was going on. I did a clean install of mailcow and now it's working though!

Thanks for replying.
