### ISSUE TITLE
mailcow behind loadbalancer can't update ACME

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#3139]
I have mailcow www behind a loadbalancer forwarding on ips.
This is no problem for IPv4, but it is hanging on the IPv6 and won't renew.

I have set SNAT6_TO_SOURCE to the local ip not the loadbalancer.
All mail ports are directed directly to the mailserver, is this correct?

is SKIP_IP_CHECK also possible for IPv6?

**Comment by andryyy** [comment]
Please ask this in the support channels. Issues without template and logs will be closed, too.

If a AAAA record exists, it validates against the IPv6. "SKIP_IP_CHECK" affects IPv4 and IPv6, but it does obviously not change how ACME validates your domain. :) We cannot tell ACME to skip the validation for a protocol. You can only change that by removing the AAAA record.

I don't see any logs so I can only assume it fails on HTTP validation. You can disable that in mailcow.conf, too. :)
