### ISSUE TITLE
mysql_tzinfo_to_sql Unable to load '/usr/share/zoneinfo/leap-seconds.list'

### ISSUE THREAD

**Issue by kokspflanze** [mailcow/mailcow-dockerized#3143]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

i updated today to the latest version, and the `php-fpm-mailcow``takes long time to start.
in the log i found

````
rspamd-mailcow_1     | Waiting for PHP on port 9001... (much of them)
php-fpm-mailcow_1    | MySQL mysql_tzinfo_to_sql - debug output: 
php-fpm-mailcow_1    | {"msg":"mysql_tzinfo_to_sql: command completed successfully","text":"Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.\n","type":"info"}
php-fpm-mailcow_1    | Running DB init... 
````

after the warning everything running correctly

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

update to the latest version

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Centos7|
| Is Apparmor, SELinux or similar active? | SeLinux enforcing |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM Node |
| Server/VM specifications (Memory, CPU Cores) | 4Cores, 8GB Ram |
| Docker Version (`docker version`) | 19.03.4|
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | default install |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Can be ignored, not a bug.

------ Originalnachricht ------
Von: "Oliver" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 11.11.2019 23:06:34
Betreff: [mailcow/mailcow-dockerized] mysql_tzinfo_to_sql Unable to load 
'/usr/share/zoneinfo/leap-seconds.list' (#3143)

**Comment by kokspflanze** [comment]
really? it take like 5 min, to start the php image. i was bit shocked.

**Comment by andryyy** [comment]
Yes. It should not do that every start though. And 5 minutes is an indicator your systems disk is much too slow.

Will change this soon (tm). No, really, soon.

**Comment by kokspflanze** [comment]
okay thanks, its just the test-server to test all updates.

**Comment by andryyy** [comment]
Fixed. :)
