### ISSUE TITLE
Mailcow requests cert only for base domain not mail domains

### ISSUE THREAD

**Issue by StiviiK** [mailcow/mailcow-dockerized#3144]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:
I have setup mailcow-dockerized successfully and everything but ACME works fine.
My mailcow hostname is `mail.domain.tld`. (running behind Traefik, it requests a wildcard certificate `CN=*.domain.tld SAN=domain.tld`). Mailcow and the DNS records are configured that my mail domain is `domain.tld`. Mailing works fine but I have to skip certificate verification as the ACME container only requests a Domain for `mail.domain.tld` but not for `domain.tld` so is the CN invalid for a SSL connection (e.g. Roundcube error: `Peer certificate CN=mail.domain.tld did not match expected CN=domain.tld`)

`echo "Q" | openssl s_client -starttls smtp -crlf -connect mx.domain.tld:587` outputs:
```
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = mail.domain.tld
verify return:1
---
Certificate chain
 0 s:CN = mail.domain.tld
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

Log output of ACME container:
```
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Waiting for Nginx... OK
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Waiting for domain table... OK
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Initializing, please wait...
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Using existing domain key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Tue Nov 12 09:54:28 GMT 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Tue Nov 12 09:54:58 GMT 2019 - Found A record for autodiscover.domain.tld: CORRECT_IP
acme-mailcow_1       | Tue Nov 12 09:54:58 GMT 2019 - Confirmed A record with IP CORRECT_IP, but HTTP validation failed
acme-mailcow_1       | Tue Nov 12 09:54:59 GMT 2019 - Found A record for autoconfig.domain.tld: CORRECT_IP
acme-mailcow_1       | Tue Nov 12 09:54:59 GMT 2019 - Confirmed A record with IP CORRECT_IP, but HTTP validation failed
acme-mailcow_1       | Tue Nov 12 09:54:59 GMT 2019 - Found A record for mail.domain.tld: CORRECT_IP
acme-mailcow_1       | Tue Nov 12 09:54:59 GMT 2019 - Confirmed A record CORRECT_IP
acme-mailcow_1       | Certificate will not expire
acme-mailcow_1       | Tue Nov 12 09:54:59 GMT 2019 - Certificate validation done, neither changed nor due for renewal, sleeping for another day. 
```

| Question | Answer |
| --- | --- |
| My operating system | `Ubuntu 19.10` |
| Virtualization technlogy (KVM, VMware, Xen, etc) | `ESXi` |
| Docker Version (`docker version`) | `Docker CE 19.03.3` |
| Docker-Compose Version (`docker-compose version`) | `docker-py version: 3.7.3` |
| Reverse proxy (custom solution) | `Traefik` |

**Comment by ntimo** [comment]
You can use ADDITIONAL_SAN=domain.tld in your mailcow config this will then add it to the mailcow cert. Please also note custom reverse proxy setups are not supported.

**Comment by StiviiK** [comment]
>ADDITIONAL_SAN=domain.tld    

Did not fix the issue. I do not think this is an issue because I'm using a custom reverse proxy, as the certificates get successfully orderd and signed but using the wrong Common Name.

```
Tue Nov 12 11:01:14 GMT 2019 - Creating backups in /var/lib/acme/backups/2019-11-12_11_01_14/ ...
Parsing account key...
Parsing CSR...
Found domains: mail.domain.tld
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying mail.domain.tld...
mail.domain.tld verified!
Signing certificate...
Certificate signed!
Tue Nov 12 11:01:26 GMT 2019 - Deploying...
Tue Nov 12 11:01:26 GMT 2019 - Verified hashes.
Reloading Nginx...
Reloading Dovecot...
Reloading Postfix...
Tue Nov 12 11:01:27 GMT 2019 - Certificate successfully deployed, removing backup, sleeping 1d
```

**Comment by ntimo** [comment]
Sorry, then I don't understand the issue. mailcow by default only requests a certficate for your mailcow_hostname mail.domain.tld and for autodiscover.domain.tld and autoconfig.domain.tld.

**Comment by andryyy** [comment]
You need to run up -d. You also need to post full logs, that may show why a domain was skipped for validation.

**Comment by StiviiK** [comment]
>mailcow by default only requests a certficate for your mailcow_hostname mail.domain.tld and for autodiscover.domain.tld and autoconfig.domain.tld

Okay, why only these and none for domain.tld?

Following use case:
My Domain is `stivik.domain`. I host mailcow following your documentation, mailcow ui is available under `mail.stivik.domain`, the MX record for `stivik.domain` points to `mail.stivik.domain`. I add as domain in mailcow `stivik.domain` and create a Mailbox for e.g. `info@stivik.domain`. Mail sending and receiving works fine. 
But If I try to add the Mailbox via IMAP/SMTP SSL to a Mail Client (e.g. Outlook, GMail) i get an error that the certificate could not be verfied and I have to skip verfication to add it. If I try to use Roundcube I get the Error `Peer certificate CN=mail.stivik.domain did not match expected CN=stivik.domain`, so in my understanding the certificate for IMAP/SMTP SSL connections should be issued for `stivik.domain` instead of `mail.stivik.domain`. Or did I missunderstand or -configure something?
I hope its now clearer what my Problem is.

**Comment by andryyy** [comment]
You should just use the correct hostname for IMAP and SMTP. :)

Use MAILCOW_HOSTNAME.

**Comment by StiviiK** [comment]
>You should just use the correct hostname for IMAP and SMTP. :)

Oh thats embarrassing, I feel kinda dumb now 😅 Thanks.

**Comment by andryyy** [comment]
Noooo, no problem at all. :)
