### ISSUE TITLE
Allocate quota to domain administrators

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#3145]
When you have a domain admin with rights over several domains it would be nice if they had the ability to adjust the quotas of different domains under their control up to a maximum quota total for all their domains.

For example, if Sam was allocated 5G then they could split it how they wish across their domains, `example.com`, `example.org` and `example.co.uk`, they could set the variables for **Default mailbox quota**, **Max. quota per mailbox (MiB)** and **Domain quota** as they want, for each domain, up to the maximum of the total space allocated to their admin account.

**Comment by andryyy** [comment]
User A is assigned to example.com and example.de, User B to example.com and example.co.uk.

How does this work?

Just asking. I will not work on this feature, but someone else might and they need that info.

**Comment by chriscroome** [comment]
Yes, I realise that in cases such as you describe a more complex solution would be needed :slightly_smiling_face: .

Perhaps something like the ability to add *Organisations* and assign a total quota to an organisation and then *Organisation Admins* could have the ability to allocate space between the domains governed by an organisation (of course there would perhaps need to be a restriction to say that an organisation admin could only be a member of one organisation).

I'm afraid I'm also not in a position to work on such a feature but would be happy to discuss it and thanks @andryyy for leaving this up in case there are some others interested in it.

**Comment by ravinayag** [comment]
I think this may override the feature of when you have multiple domain admins. 
Probably this can be an additional role as super domain admin with a minimum of two domains. but How can we vary with the default admin(mailcow) role of and super domain admins?
