### ISSUE TITLE
TLS library problem after update - key values mismatch

### ISSUE THREAD

**Issue by netuddmeg** [mailcow/mailcow-dockerized#3146]
hi there,

After the update from repo last night postfix has got some problem with key:

postfix-mailcow_1    | Nov 13 16:09:50 mail postfix/smtpd[1346]: warning: TLS library problem: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:294:

How can I fix it?

main.cf:

...
smtpd_tls_cert_file = /etc/ssl/mail/cert.pem
smtpd_tls_key_file = /etc/ssl/mail/key.pem
tls_server_sni_maps = hash:/opt/postfix/conf/sni.map
smtpd_use_tls=yes
smtpd_tls_received_header = yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_relay_restrictions = permit_mynetworks,
  permit_sasl_authenticated,
  defer_unauth_destination
...

ls -la data/assets/ssl/

drwxr-xr-x 2 root root 4096 Nov 13 14:54 acme
-rw-r--r-- 1 root root 1675 Nov 13 14:54 ca-key.pem
-rw-r--r-- 1 root root 1034 Nov 13 14:54 ca.pem
-rw-r--r-- 1 root root 1107 Nov 13 14:54 cert.pem
-rw-r--r-- 1 root root  424 Nov 13 14:54 dhparams.pem
-rw------- 1 root root 3243 Nov 13 15:56 key.pem
drwxr-xr-x 2 root root 4096 Nov 13 14:55 mail.humanlabor.hu

ls -la data/assets/ssl/mail.humanlabor.hu/
-rw-r--r-- 1 root root 1870 Nov 13 15:56 acme.csr
-rw------- 1 root root 3243 Nov 13 14:55 key.pem

**Comment by andryyy** [comment]
```
docker-compose down
mv data/assets/ssl data/assets/ssl_backup
cp -rp data/assets/ssl-example/ data/assets/ssl
docker-compose up -d
```

Don't know, but this will reset the certs. Make sure you remove any TLSA records and recreate them in DNS afterwards.

**Comment by netuddmeg** [comment]
Its the same, but there is more error message:
docker-compose logs --tail=200 -f  acme-mailcow

acme-mailcow_1       | Wed Nov 13 17:14:46 CET 2019 - Waiting for Docker API...OK
acme-mailcow_1       | Wed Nov 13 17:14:46 CET 2019 - Waiting for database... Uptime: 15  Threads: 38  Questions: 370  Slow queries: 0  Opens: 50  Flush tables: 1  Open tables: 42  Queries per second avg: 24.666
acme-mailcow_1       | OK
acme-mailcow_1       | Wed Nov 13 17:14:46 CET 2019 - Waiting for Nginx... OK
acme-mailcow_1       | Wed Nov 13 17:14:51 CET 2019 - Waiting for domain table... OK
acme-mailcow_1       | Wed Nov 13 17:14:51 CET 2019 - Initializing, please wait... 
acme-mailcow_1       | Wed Nov 13 17:14:51 CET 2019 - Generating missing domain private rsa key...
acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
acme-mailcow_1       | ........................................................................................................................................................................................................................................................++++
acme-mailcow_1       | ..............++++
acme-mailcow_1       | e is 65537 (0x010001)
acme-mailcow_1       | Wed Nov 13 17:14:56 CET 2019 - Generating missing Lets Encrypt account key...
acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
acme-mailcow_1       | ..................................................................++++
acme-mailcow_1       | .............................................++++
acme-mailcow_1       | e is 65537 (0x010001)
acme-mailcow_1       | Wed Nov 13 17:14:58 CET 2019 - Detecting IP addresses... OK
acme-mailcow_1       | Wed Nov 13 17:15:22 CET 2019 - No A or AAAA record found for hostname autodiscover.1cv.hu
acme-mailcow_1       | Wed Nov 13 17:15:22 CET 2019 - No A or AAAA record found for hostname autoconfig.1cv.hu
acme-mailcow_1       | Wed Nov 13 17:15:22 CET 2019 - No A or AAAA record found for hostname autodiscover.49er.hu
acme-mailcow_1       | Wed Nov 13 17:15:22 CET 2019 - No A or AAAA record found for hostname autoconfig.49er.hu
acme-mailcow_1       | Wed Nov 13 17:15:23 CET 2019 - No A or AAAA record found for hostname autodiscover.barpult.com
acme-mailcow_1       | Wed Nov 13 17:15:23 CET 2019 - No A or AAAA record found for hostname autoconfig.barpult.com
acme-mailcow_1       | Wed Nov 13 17:15:24 CET 2019 - No A or AAAA record found for hostname autodiscover.hamy.hu
acme-mailcow_1       | Wed Nov 13 17:15:24 CET 2019 - No A or AAAA record found for hostname autoconfig.hamy.hu
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Found A record for autodiscover.humanlabor.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Found A record for autoconfig.humanlabor.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Found A record for autodiscover.humanpolitika.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Found A record for autoconfig.humanpolitika.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - No A or AAAA record found for hostname autodiscover.humlab.hu
acme-mailcow_1       | Wed Nov 13 17:15:25 CET 2019 - No A or AAAA record found for hostname autoconfig.humlab.hu
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Found A record for autodiscover.jobbing.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Found A record for autoconfig.jobbing.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Found A record for mail.humanlabor.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Found A record for humanlabor.hu: 86.101.226.93
acme-mailcow_1       | (skipping check, returning 0)
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Confirmed A record 86.101.226.93
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Certificate /var/lib/acme/mail.humanlabor.hu/cert.pem missing or changed domains 'mail.humanlabor.hu autoconfig.humanlabor.hu autoconfig.humanpolitika.hu autoconfig.jobbing.hu autodiscover.humanlabor.hu autodiscover.humanpolitika.hu autodiscover.jobbing.hu humanlabor.hu' - start obtaining
acme-mailcow_1       | Wed Nov 13 17:15:26 CET 2019 - Copying shared private key for this certificate...
acme-mailcow_1       | Parsing account key...
acme-mailcow_1       | Parsing CSR...
acme-mailcow_1       | Found domains: autodiscover.humanlabor.hu, autodiscover.humanpolitika.hu, autoconfig.humanlabor.hu, autoconfig.jobbing.hu, autoconfig.humanpolitika.hu, autodiscover.jobbing.hu, mail.humanlabor.hu, humanlabor.hu
acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 194, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 106, in get_crt
acme-mailcow_1       |     directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 46, in _do_request
acme-mailcow_1       |     raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
acme-mailcow_1       | ValueError: Error getting directory:
acme-mailcow_1       | Url: https://acme-v02.api.letsencrypt.org/directory
acme-mailcow_1       | Data: None
acme-mailcow_1       | Response Code: None
acme-mailcow_1       | Response: <urlopen error [Errno -3] Try again>
acme-mailcow_1       | Wed Nov 13 17:15:32 CET 2019 - Failed to obtain certificate /var/lib/acme/mail.humanlabor.hu/cert.pem for domains 'mail.humanlabor.hu autoconfig.humanlabor.hu autoconfig.humanpolitika.hu autoconfig.jobbing.hu autodiscover.humanlabor.hu autodiscover.humanpolitika.hu autodiscover.jobbing.hu humanlabor.hu'
acme-mailcow_1       | OK
acme-mailcow_1       | cp: can't stat '/var/lib/acme/mail.humanlabor.hu/cert.pem': No such file or directory
acme-mailcow_1       | Wed Nov 13 17:15:32 CET 2019 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK

**Comment by mhofer117** [comment]
From the error it appears acme-tiny cannot connect to the acme servers.
Is this issue persistent across acme container restarts?
Can you issue ``curl -I https://acme-v02.api.letsencrypt.org/directory`` on the host?

**Comment by netuddmeg** [comment]
It says:

HTTP/2 200 
server: nginx
date: Wed, 13 Nov 2019 19:54:17 GMT
content-type: application/json
content-length: 658
cache-control: public, max-age=0, no-cache
replay-nonce: 0101o0mm5BmhB3-N7FyLKGHPZRp59ab6_gHy4PgyBLKZvNo
x-frame-options: DENY
strict-transport-security: max-age=604800

**Comment by mhofer117** [comment]
And from within the acme container?
```
docker-compose exec acme-mailcow bash
bash-5.0# curl -I https://acme-v02.api.letsencrypt.org/directory
HTTP/2 200
server: nginx
date: Wed, 13 Nov 2019 19:56:28 GMT
content-type: application/json
content-length: 658
cache-control: public, max-age=0, no-cache
replay-nonce: 0101IRcxEbN3Y27DmYLJjNCvlCaPOo6lsjw5aVsUMZfeua4
x-frame-options: DENY
strict-transport-security: max-age=604800

```

**Comment by netuddmeg** [comment]
No! Sorry! 

This is from container:

bash-5.0# curl -I https://acme-v02.api.letsencrypt.org/directory 
HTTP/2 200 
server: nginx
date: Wed, 13 Nov 2019 20:01:02 GMT
content-type: application/json
content-length: 658
cache-control: public, max-age=0, no-cache
replay-nonce: 0102xURx62-O05vcOm5-4KWNmug_cH5Pcnp0czghm6tMsgs
x-frame-options: DENY
strict-transport-security: max-age=604800


It is very interesting, because I already have ran it multiple times, and it could not been finished successfully:

 acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Directory found!
acme-mailcow_1       | Registering account...
acme-mailcow_1       | Registered!
acme-mailcow_1       | Creating new order...
acme-mailcow_1       | Order created!
acme-mailcow_1       | Verifying autoconfig.1cv.hu...
acme-mailcow_1       | autoconfig.1cv.hu verified!
acme-mailcow_1       | Verifying autoconfig.49er.hu...
acme-mailcow_1       | autoconfig.49er.hu verified!
acme-mailcow_1       | Verifying autoconfig.barpult.com...
acme-mailcow_1       | autoconfig.barpult.com verified!
acme-mailcow_1       | Verifying autoconfig.hamy.hu...
acme-mailcow_1       | autoconfig.hamy.hu verified!
acme-mailcow_1       | Verifying autoconfig.humanlabor.hu...
acme-mailcow_1       | autoconfig.humanlabor.hu verified!
acme-mailcow_1       | Verifying autoconfig.humanpolitika.hu...
acme-mailcow_1       | autoconfig.humanpolitika.hu verified!
acme-mailcow_1       | Verifying autoconfig.jobbing.hu...
acme-mailcow_1       | autoconfig.jobbing.hu verified!
acme-mailcow_1       | Verifying autodiscover.1cv.hu...
acme-mailcow_1       | autodiscover.1cv.hu verified!
acme-mailcow_1       | Verifying autodiscover.49er.hu...
acme-mailcow_1       | autodiscover.49er.hu verified!
acme-mailcow_1       | Verifying autodiscover.barpult.com...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 194, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 147, in get_crt
acme-mailcow_1       |     authorization = _poll_until_not(auth_url, ["pending"], "Error checking challenge status for {0}".format(domain))
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 70, in _poll_until_not
acme-mailcow_1       |     result, _, _ = _send_signed_request(url, None, err_msg)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 52, in _send_signed_request
acme-mailcow_1       |     new_nonce = _do_request(directory['newNonce'])[2]['Replay-Nonce']
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 46, in _do_request
acme-mailcow_1       |     raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
acme-mailcow_1       | ValueError: Error:
acme-mailcow_1       | Url: https://acme-v02.api.letsencrypt.org/acme/new-nonce
acme-mailcow_1       | Data: None
acme-mailcow_1       | Response Code: None
acme-mailcow_1       | **Response: <urlopen error [Errno 104] Connection reset by peer>**
acme-mailcow_1       | Wed Nov 13 21:00:24 CET 2019 - Failed to obtain certificate /var/lib/acme/mail.humanlabor.hu/cert.pem for domains 'mail.humanlabor.hu autoconfig.1cv.hu autoconfig.49er.hu autoconfig.barpult.com autoconfig.hamy.hu autoconfig.humanlabor.hu autoconfig.humanpolitika.hu autoconfig.jobbing.hu autodiscover.1cv.hu autodiscover.49er.hu autodiscover.barpult.com autodiscover.hamy.hu autodiscover.humanlabor.hu autodiscover.humanpolitika.hu autodiscover.jobbing.hu mail.1cv.hu mail.49er.hu mail.barpult.com mail.hamy.hu mail.humanpolitika.hu mail.humlab.hu mail.jobbing.hu'
acme-mailcow_1       | OK
acme-mailcow_1       | cp: can't stat '/var/lib/acme/mail.humanlabor.hu/cert.pem': No such file or directory
acme-mailcow_1       | Wed Nov 13 21:00:24 CET 2019 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK



Interesting part is:  **Response: <urlopen error [Errno 104] Connection reset by peer>**

**Comment by netuddmeg** [comment]
Another try, but it seems like another error:

acme-mailcow_1       | Getting directory...
acme-mailcow_1       | Directory found!
acme-mailcow_1       | Registering account...
acme-mailcow_1       | Already registered!
acme-mailcow_1       | Creating new order...
acme-mailcow_1       | Order created!
acme-mailcow_1       | Verifying autoconfig.1cv.hu...
acme-mailcow_1       | autoconfig.1cv.hu verified!
acme-mailcow_1       | Verifying autoconfig.49er.hu...
acme-mailcow_1       | autoconfig.49er.hu verified!
acme-mailcow_1       | Verifying autoconfig.barpult.com...
acme-mailcow_1       | autoconfig.barpult.com verified!
acme-mailcow_1       | Verifying autoconfig.hamy.hu...
acme-mailcow_1       | autoconfig.hamy.hu verified!
acme-mailcow_1       | Verifying autoconfig.humanlabor.hu...
acme-mailcow_1       | autoconfig.humanlabor.hu verified!
acme-mailcow_1       | Verifying autoconfig.humanpolitika.hu...
acme-mailcow_1       | autoconfig.humanpolitika.hu verified!
acme-mailcow_1       | Verifying autoconfig.jobbing.hu...
acme-mailcow_1       | autoconfig.jobbing.hu verified!
acme-mailcow_1       | Verifying autodiscover.1cv.hu...
acme-mailcow_1       | autodiscover.1cv.hu verified!
acme-mailcow_1       | Verifying autodiscover.49er.hu...
acme-mailcow_1       | autodiscover.49er.hu verified!
acme-mailcow_1       | Verifying autodiscover.barpult.com...
acme-mailcow_1       | autodiscover.barpult.com verified!
acme-mailcow_1       | Verifying autodiscover.hamy.hu...
acme-mailcow_1       | autodiscover.hamy.hu verified!
acme-mailcow_1       | Verifying autodiscover.humanlabor.hu...
acme-mailcow_1       | autodiscover.humanlabor.hu verified!
acme-mailcow_1       | Verifying autodiscover.humanpolitika.hu...
acme-mailcow_1       | autodiscover.humanpolitika.hu verified!
acme-mailcow_1       | Verifying autodiscover.jobbing.hu...
acme-mailcow_1       | autodiscover.jobbing.hu verified!
acme-mailcow_1       | Verifying mail.1cv.hu...
acme-mailcow_1       | Traceback (most recent call last):
acme-mailcow_1       |   File "/usr/bin/acme-tiny", line 8, in <module>
acme-mailcow_1       |     sys.exit(main())
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 194, in main
acme-mailcow_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
acme-mailcow_1       |   File "/usr/lib/python3.7/site-packages/acme_tiny.py", line 149, in get_crt
acme-mailcow_1       |     raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
acme-mailcow_1       | ValueError: Challenge did not pass for mail.1cv.hu: {'identifier': {'type': 'dns', 'value': 'mail.1cv.hu'}, 'status': 'invalid', 'expires': '2019-11-20T19:59:19Z', 'challenges': [{'type': 'http-01', 'status': 'invalid', 'error': {'type': 'urn:ietf:params:acme:error:unauthorized', 'detail': 'Invalid response from http://mail.1cv.hu/.well-known/acme-challenge/YN305YAXmrtDn5kVNf9V9VW6JVxP-EQmd6x3z-_S7tk [86.101.226.93]: "<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n"', 'status': 403}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/1224238202/rynZCA', 'token': 'YN305YAXmrtDn5kVNf9V9VW6JVxP-EQmd6x3z-_S7tk', 'validationRecord': [{'url': 'http://mail.1cv.hu/.well-known/acme-challenge/YN305YAXmrtDn5kVNf9V9VW6JVxP-EQmd6x3z-_S7tk', 'hostname': 'mail.1cv.hu', 'port': '80', 'addressesResolved': ['86.101.226.93'], 'addressUsed': '86.101.226.93'}]}, {'type': 'dns-01', 'status': 'invalid', 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/1224238202/G6mntQ', 'token': 'YN305YAXmrtDn5kVNf9V9VW6JVxP-EQmd6x3z-_S7tk'}, {'type': 'tls-alpn-01', 'status': 'invalid', 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/1224238202/H8hOsw', 'token': 'YN305YAXmrtDn5kVNf9V9VW6JVxP-EQmd6x3z-_S7tk'}]}
acme-mailcow_1       | Wed Nov 13 21:18:19 CET 2019 - Failed to obtain certificate /var/lib/acme/mail.humanlabor.hu/cert.pem for domains 'mail.humanlabor.hu autoconfig.1cv.hu autoconfig.49er.hu autoconfig.barpult.com autoconfig.hamy.hu autoconfig.humanlabor.hu autoconfig.humanpolitika.hu autoconfig.jobbing.hu autodiscover.1cv.hu autodiscover.49er.hu autodiscover.barpult.com autodiscover.hamy.hu autodiscover.humanlabor.hu autodiscover.humanpolitika.hu autodiscover.jobbing.hu mail.1cv.hu mail.49er.hu mail.barpult.com mail.hamy.hu mail.humanpolitika.hu mail.humlab.hu mail.jobbing.hu'
acme-mailcow_1       | OK
acme-mailcow_1       | cp: can't stat '/var/lib/acme/mail.humanlabor.hu/cert.pem': No such file or directory
acme-mailcow_1       | Wed Nov 13 21:18:19 CET 2019 - Some errors occurred, retrying in 30 minutes...
acme-mailcow_1       | OK

**Comment by mhofer117** [comment]
Are you using a reverse proxy?
Maybe you should have filled the issue template instead of deleting it...

**Comment by andryyy** [comment]
It is still missing the part where acme-mailcow verifies the IP and HTTP path. You probably skip it. This does not mean, that Let's Encrypt does not run any check to verify the challenge (which fails as seen in the logs posted above).

I cannot open `http://mail.1cv.hu/.well-known/acme-challenge` from my computer, too. It is refused.
