### ISSUE TITLE
Can't add mailbox to iOS Mail App

### ISSUE THREAD

**Issue by karkaaa** [mailcow/mailcow-dockerized#3147]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Not working this: https://mailcow.github.io/mailcow-dockerized-docs/client/client-apple/

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to https://demo.mailcow.email/ and https://demo.mailcow.email/SOGo
2. And then to login with demo user.
3. But once I do i did not get profile.

iPhone 6s Plus with iOS 13.2.2

**System information**

Your demo system.

**Comment by ntimo** [comment]
Hey,
I just tested it with my up to date mailcow installation and it works without a problem. What error message do you get? What exactly is not working. Please provide more insights.

**Comment by karkaaa** [comment]
I get redirect to https://demo.mailcow.email/ and nothing.

**Comment by ntimo** [comment]
This is a demo installation of mailcow, you should setup your own mailcow on your own server. And there this will work. I am not sure why it might not be working in the demo. But this could be on purpose.

**Comment by karkaaa** [comment]
I want to trie and then install on my own server. But not working on
demo... Maybe posible to fix that?

**Comment by ntimo** [comment]
I would suggest that you just install mailcow to test it out for yourself this way you will be able to get the best experience :)

**Comment by mkuron** [comment]
After the log in, you don't always get redirected back to /mobileconfig.php. I guess that's what happened here. Just manually navigate to /mobileconfig.php after you log in.

**Comment by karkaaa** [comment]
Install but not working. Redirect to /index.php. 

p.s. i can not use 443 port and change to other.

Maybe i can test on laptop with /mobileconfig.php and find more information about error because in logs nothing...

**Comment by mkuron** [comment]
Log in, which redirects you to /index.php. Then manually navigate to /mobileconfig.php.

**Comment by karkaaa** [comment]
Then manually navigate to /mobileconfig.php.
