### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function add() on null in /web/inc/header.inc.php

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#3149]
When attempting to go to the regular domain, **https://icmail.us** OR **https://icmail.us/** ...this should redirect the user to **https://icmail.us/SOGo/so/**

However, after the recent upgrade from v4.0.8 to v4.1.1, I get this error:  _**Fatal error: Uncaught Error: Call to a member function add() on null in  /web/inc/header.inc.php:30 Stack trace: #0 /web/index.php(22):  require_once() 0000001 {main} thrown in /web/inc/header.inc.php on line 30**_

Interesting to note is that if I enter **https://icmail.us/SOGo/so/** ...it works.

Ticket opened with sogo.nu support; https://sogo.nu/bugs/view.php?id=4884.
If anyone has any knowledge of a workaround, would appreciate it.  Danke.

**Comment by infracritical** [comment]
UPDATE: Unable to restore/downgrade to prior version.  Am stuck on v4.1.1.

**Comment by infracritical** [comment]
Found a workaround...

* Saved off **index.php** as **orig_index.php**.
* Create a new **index.php** file containing 4 lines of code:

`<?php

header("Location: https://icmail.us/SOGo/so/");
exit();

?>`

NOTE: This problem DID NOT exist when upgrading from v4.0.7 to v4.0.8; this problem ONLY occurred when upgrading from v4.0.8 to v4.1.1.

**Comment by andryyy** [comment]
The location directive you added is not supported by us. 

The SOGo image is also not involved. It does not matter which SOGo image version you use. This is a PHP error. 

Please don't remove the template. If you think it is useless for your request, you should visit the Telegram channel instead.
