### ISSUE TITLE
caddy server

### ISSUE THREAD

**Issue by pixelyo** [mailcow/mailcow-dockerized#315]
caddy server is an alternative for nginx and apache

it would make proxies and ssl way easier to configure.

https://caddyserver.com/

**Comment by Braintelligence** [comment]
Yeah, it would also let you automatically use letsencrypt. I use it for some of my containers.

**Comment by andryyy** [comment]
But Nginx is already configured right now. You can still use caddy as reverse proxy in front of mailcow. It is not intended to modify the mailcow site itself.

**Comment by Braintelligence** [comment]
The point of caddy is the inbuilt letsencrypt retrieval and renewal. This way you could remove the burden of running letsencrypt outside of the docker environment and creating symlinkstuff via cron all the time.

**Comment by andryyy** [comment]
But not everyone wants to use LE. It's also pretty much unattended and they write in their docs, that they don't know wether or not LE wants that to be disabled at some point in the future.

The EAS connections are also very sensitive, I don't think Caddy is stable enough to handle a lot of these. 
I run some managed instances for a few customers, I don't really want to risk it (and I also don't want to split mailcow in multiple web server branches).

Maybe you can try it and report back, I can run some tests then, too. :)

**Comment by Braintelligence** [comment]
Caddy is weak with ActiveSync?

**Comment by pixelyo** [comment]
@andryyy that is true, not everyone wants to use LE, and caddys main goal is to use LE. I thought it would be just generally useful for people which use mailcow personally.
I really like mailcow because it has a great admin ui and sogo integrated.

**Comment by andryyy** [comment]
I'm not sure. Last time I tried Caddy it was very new. Not too sure about the current state.

**Comment by Braintelligence** [comment]
Maybe a container with both nginx and caddy could be used while the mailcow.conf decides which of them will be used. 
Then again some way of optional inbuilt LE automatism would defeat caddys purpose completely and maybe this would be a possible route?

**Comment by andryyy** [comment]
I will never again start implementing multiple services to choose from, sorry. This did not work out for "standard" mailcow at all. :/
You can still run Caddy in front of mailcow, this is perfectly fine. The official LE client already works great with mailcow, too.

**Comment by Braintelligence** [comment]
What about including optional automatism for LE in the nginx container?

**Comment by pixelyo** [comment]
> What about including optional automatism for LE in the nginx container?

That would make the first access to the web interface smoother too, if it is enabled from the beginning

**Comment by bebehei** [comment]
After reading the thread, I think #328 is at least related.
