### ISSUE TITLE
mySQL: Shrink settings on tiny server?

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3150]
Hello,

Is it perhaps possible for a future version of MailCow to shrink the mysql settings so that not so much memory is used if the server has less than for example 3 GB RAM?

In connection with this problem:
https://github.com/mailcow/mailcow-dockerized/issues/3054

Had also made a request on ServerFault about this see:
https://serverfault.com/questions/992090/docker-mysql-mailcow-2002-connection-refused

PS. There are some users like me who only run MailCow as an external mail server on a small servers.

Thank you in advance.

**Comment by andryyy** [comment]
This channel is not meant for support. Please ask these kind of questions in the Telegram group. 

You can modify the my.cnf file any time to fit your needs.
