### ISSUE TITLE
Rspamd ignores ASN blacklist file: /etc/rspamd/custom/bad_asn.map

### ISSUE THREAD

**Issue by carlbennett** [mailcow/mailcow-dockerized#3151]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

The rspamd container seems to be ignoring the ASN blacklist. Specifically, when I configure the file `/etc/rspamd/custom/bad_asn.map` and add an ASN with a score of 99999 for example, rspamd ignores that when applying rules to incoming email, and the bad ASN still gets through.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I received bad email from an ASN.
2. I recorded the ASN and put it in the `/etc/rspamd/custom/bad_asn.map` file with a very high score so it should be always rejected.
3. The ASN sends email to my Mailcow installation another time.
4. The email was not rejected and the custom score didn't take effect.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | CentOS 7.7.1908 x86_64 |
| Is Apparmor, SELinux or similar active? | SELinux is in permissive mode |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM/Vultr |
| Server/VM specifications (Memory, CPU Cores) | 2 vCPU, 4G RAM, 1G swap, 80G SSD |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | N/A - Uses nginx container from mailcow directly |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
   ```diff
   [root@mail mailcow-dockerized]# git diff origin/master
   diff --git a/data/conf/rspamd/custom/bad_asn.map b/data/conf/rspamd/custom/bad_asn.map
   index ffd9af0..89c52b6 100644
   --- a/data/conf/rspamd/custom/bad_asn.map
   +++ b/data/conf/rspamd/custom/bad_asn.map
   @@ -2,20 +2,20 @@
    # ASN:SCORE DESC
    # Remove comment to enable score
    #201942:5 #Soltia Consulting SL - ipinfo.io
   -#16276:2 #OVH
   -#12876:2 #ONLINE S.A.S
   +16276:999 #OVH
   +12876:999 #ONLINE S.A.S
    #31034:5 #ARUBA-ASN, IT
    #12874:5 #FASTWEB, IT
    #30823:3 #PKV spam
    #42831:5 #UK Dedicated Servers Ltd
    #29119:5 #Aire Networks del Mediterraneo S.L.U.
   -#13335:5 #Cloudflare
   -#28753:5 #Leaseweb
   +13335:99 #Cloudflare
   +28753:99 #Leaseweb
    #61272:5 #Informacines sistemos ir technologijos
    #53755:5 #Input Output Flood LLC
    #29422:5 #FICIX Helsinki
    #62255:4 #Asmunda New Media Ltd
   -#14061:4 #Digitalocean
   +14061:4 #Digitalocean
    #55293:4 #A2 Hosting
    #63018:4 #US Dedicated
    #197518:2 #RACKMARKT
   @@ -28,3 +28,18 @@
    #43146:2
    #49100:4
    #39364:4
   +17444:999 #New World Telecom Inc. (Hong Kong)
   +4713:999 #NTT Communications Corporation (Japan/OCN)
   +26101:999 # Yahoo-3
   +23724:99999 # IDC, China Telecommunications Corporation
   +42926:99999 # Radore Veri Merkezi Hizmetleri A.S.
   +4808:99999 # China Unicom Beijing Province Network
   +17816:99999 # China Unicom IP network China169 Guangdong province
   +15169:5 # Google LLC
   +6057:15 # Administracion Nacional de Telecomunicaciones
   +58397:99999 # PT Infinys System Indonesia
   +8075:999 # Microsoft
   +4816:999999 # China Telecom
   +37963:999999 # Hangzhou Alibaba Advertising Co.,Ltd. (China)
   +133054:99999 # Reasonable Software House Limited (Hong Kong)
   +134542:99999 # China Unicom IP network
   \ No newline at end of file
   diff --git a/data/conf/rspamd/custom/global_smtp_from_blacklist.map b/data/conf/rspamd/custom/global_smtp_from_blacklist.map
   index 3c87288..033e9bc 100644
   --- a/data/conf/rspamd/custom/global_smtp_from_blacklist.map
   +++ b/data/conf/rspamd/custom/global_smtp_from_blacklist.map
   @@ -1 +1,3 @@
    # /.+example\.com/i
   +/126\.com/i
   +/163\.com/i
   ```
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptables output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Seems to be indeed broken with a map value like `12345:10`. Works with `12345` though. Can you test/verify this?

**Comment by andryyy** [comment]
We need to remove the `:` and replace it by a whitespace :)

That probably changed a while ago. Sorry. Fixed it in the repository.
