### ISSUE TITLE
Slow performance from host when mailcow running

### ISSUE THREAD

**Issue by entr0p1** [mailcow/mailcow-dockerized#3153]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:
Hi guys, I'm having some interesting performance issues with the VM I run my Mailcow instance on. It may not necessarily be a bug with Mailcow, but it seems to have occurred after an update of either Mailcow or the system (I usually do them at the same time) and I'm wondering if maybe you've seen anything like this.

The web interface is really slow to click through, clients take a very long time to refresh mailboxes (using ActiveSync), and even the VM itself seems to be performing badly (e.g. if I run a "yum update" it will sit at the blinking cursor for a good couple of minutes before it even starts reaching out to servers). The CLI itself is fairly responsive, just any sort of commands that take any "thought".

The VM runs under Hyper-V 2019 and has the following specs:
CPU cores: 2 (Intel Xeon X5650)
RAM: 8GB
Disk: /var is 50GB (15% used) and /opt is 20GB (1% used)

So the strange thing is, I can't pinpoint what the exact cause is. CPU looks fine and load averages are low; `0.00, 0.04, 0.02`. 

There is plenty of free memory:
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.6G        3.0G        3.4G        8.8M        1.1G        4.5G
Swap:          4.0G        203M        3.8G
```
Disk IO seems to be fine too:
```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    1.49    0.02    94.37     0.31   125.55     0.02   10.67   10.75    3.14   2.13   0.32
sdb               0.00     0.00    0.03    0.00     1.10     0.22    87.35     0.00    3.61    3.29    6.15   2.66   0.01
sdc               0.02     0.18    2.78    2.08   150.25    27.05    72.93     0.03    5.76    7.50    3.41   1.98   0.96
sdd               0.00     0.00    0.08    0.02     1.43     0.40    36.29     0.00    6.51    6.10    8.48   4.59   0.05
sde               0.16    15.90    1.60    0.36     7.62    65.01    74.24     0.05   25.53    1.47  133.14   1.00   0.19
sdf               0.00     0.00    0.08    0.00     5.23     0.22   125.80     0.00    3.58    3.52    5.06   1.42   0.01
sdg               0.00     0.00    0.04    0.05     2.09     4.55   146.74     0.00    4.28    5.12    3.68   1.85   0.02
sdh               0.00     0.01    0.06    0.17     1.68     1.50    27.42     0.00    3.66    2.13    4.16   2.98   0.07
```
Disks are laid out as:
```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdf      8:80   0    5G  0 disk 
├─sdf1   8:81   0  200M  0 part /boot/efi
└─sdf2   8:82   0  4.8G  0 part /boot
sdd      8:48   0   20G  0 disk 
└─sdd1   8:49   0   20G  0 part /opt
sdb      8:16   0   30G  0 disk 
└─sdb1   8:17   0   30G  0 part /home
sr0     11:0    1 1024M  0 rom  
sdg      8:96   0    8G  0 disk 
└─sdg1   8:97   0    8G  0 part /tmp
sde      8:64   0    4G  0 disk 
└─sde1   8:65   0    4G  0 part [SWAP]
sdc      8:32   0   50G  0 disk 
└─sdc1   8:33   0   50G  0 part /var
sda      8:0    0   40G  0 disk 
└─sda1   8:1    0   40G  0 part /
sdh      8:112  0   15G  0 disk 
├─sdh1   8:113  0   10G  0 part /var/log
└─sdh2   8:114  0    5G  0 part /var/log/audit
```

If I stop the mailcow processes, everything is snappy and responsive again (commands run quickly, VM performs well). As soon as I start them again, everything is back to a crawl.

Here's where it gets really weird. There are about 20 VMs on this host, all of which are performing really well and don't display any of these symptoms. The host itself is specced with:

* 2x Intel Xeon X5650 CPUs
* 144GB DDR3 ECC Registered memory
* 8x 10K 300GB SAS disks in RAID-10

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to...
2. And then to...
3. But once I do...

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Oracle Linux 7.7 (similar to CentOS/RHEL) |
| Is Apparmor, SELinux or similar active? | SELinux (tried permissive mode, no difference. No denies in /var/log/audit/audit.log)  |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Hyper-V |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 2 cores |
| Docker Version (`docker version`) | 19.03.5, build 633a0ea |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | NGINX |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
```
# git diff origin/master
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 65f5301..2505b4d 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );
 
-    WOWorkersCount = "20";
+    WOWorkersCount = "50";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
```
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
```
# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client https imaps smtp smtp-submission smtps ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 ```
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```
```
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.129.69
151.101.193.69
151.101.1.69
151.101.65.69
```
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Any input or guidance greatly appreciated, thanks!

**Comment by andryyy** [comment]
Hm, which procs do the high cpu usage then? And when? I only see 0.x. :)

**Comment by entr0p1** [comment]
That’s the thing, it’s always practically in a state of idle (Load averages 0.x) and I can’t work out why. 

I wish the solution were as simple as throwing more resources at it :)

**Comment by andryyy** [comment]
Hm. Even when it becodes slow/laggy? That's strange indeed. Does it show a high "wa" (io wait) in top?

**Comment by entr0p1** [comment]
Yeah, the slowness is constant but any CPU spikes are usually short-lived and associated with some sort of task (like the ClamAV updates). Here's the heading from `top` right now:
```
top - 23:34:06 up  3:43,  2 users,  load average: 0.06, 0.16, 0.17
Tasks: 377 total,   1 running, 278 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.8 us,  2.5 sy,  0.0 ni, 94.1 id,  0.0 wa,  0.0 hi,  0.5 si,  0.0 st
KiB Mem :  7944772 total,  3135608 free,  3454208 used,  1354956 buff/cache
KiB Swap:  4192252 total,  3986428 free,   205824 used.  4550248 avail Mem 
```

**Comment by andryyy** [comment]
But the server is fine as long as these spikes are not there?

I could think of a sudden high io wait. :/ ClamAV is heavy on the CPU and disk when reloading signatures.

Can you further monitor it? Did you run update.sh recently?

**Comment by entr0p1** [comment]
Nope, the slowness is constant :/ so for an example I've just loaded a random section of the admin interface and it's showing the loading spinner (in screenshot). The second screenshot is of the `top` command 1 minute later. The interface is still loading, but the VM doesn't seem to be doing a whole lot...

![Screenshot 2019-11-18 23 44 07](https://user-images.githubusercontent.com/1475255/69053356-5a36d280-0a5d-11ea-9cef-6ea89ab920dc.png)
![Screenshot 2019-11-18 23 43 07](https://user-images.githubusercontent.com/1475255/69053361-5e62f000-0a5d-11ea-87a3-97c43330e9b9.png)

**Comment by andryyy** [comment]
Does it log anything in the browser dev console?

**Comment by entr0p1** [comment]
Nothing of interest, just warning me that the XSS header is bad so its being ignored 
![image](https://user-images.githubusercontent.com/1475255/69054041-e09fe400-0a5e-11ea-9603-108b7e758226.png)

**Comment by entr0p1** [comment]
I'm wondering if maybe we start turning containers off one-by-one would that help us find a culprit perhaps?

**Comment by andryyy** [comment]
I have seriously no idea. I thought about it, too. Can you start with netfilter-mailcow?

**Comment by entr0p1** [comment]
Okay I tried stopping them all one-by-one and it didn't settle for some reason. Any ideas?

**Comment by andryyy** [comment]
I doubt it is mailcow then. It didn't stop when you stopped all containers?
