### ISSUE TITLE
Stuck at 502 | Fresh Install | Debian 10

### ISSUE THREAD

**Issue by xDevyz** [mailcow/mailcow-dockerized#3154]
Hello, i was setting up a fresh mailcow dockerized installation on a fresh installed debian 10 but i can't seem to get past the 502 even after over an hour

here is the log

> php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Uptime: 1  Threads: 8  Questions: 7  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 7.000
php-fpm-mailcow_1    | OK
php-fpm-mailcow_1    | OK
php-fpm-mailcow_1    | MySQL @ 7107dcadea5d955362f6b0c52a9bd2f96bab86a973e650b642888d0fce3dd0c8
php-fpm-mailcow_1    | SQL upgrade iteration #1
php-fpm-mailcow_1    | MySQL applied an upgrade, debug output:
php-fpm-mailcow_1    | {"msg":"mysql_upgrade: upgrade was applied","text":"Phase 1/7: Checking and upgrading mysql database\nProcessing databases\nmysql\nmysql.column_stats OK\nmysql.columns_priv OK\nmysql.db OK\nmysql.event OK\nmysql.func OK\nmysql.gtid_slave_pos OK\nmysql.help_category OK\nmysql.help_keyword OK\nmysql.help_relation OK\nmysql.help_topic OK\nmysql.host OK\nmysql.index_stats OK\nmysql.innodb_index_stats OK\nmysql.innodb_table_stats OK\nmysql.plugin OK\nmysql.proc OK\nmysql.procs_priv OK\nmysql.proxies_priv OK\nmysql.roles_mapping OK\nmysql.servers OK\nmysql.table_stats OK\nmysql.tables_priv OK\nmysql.time_zone OK\nmysql.time_zone_leap_second OK\nmysql.time_zone_name OK\nmysql.time_zone_transition OK\nmysql.time_zone_transition_type OK\nmysql.transaction_registry OK\nmysql.user OK\nPhase 2/7: Installing used storage engines... Skipped\nPhase 3/7: Fixing views\nPhase 4/7: Running 'mysql_fix_privilege_tables'\nPhase 5/7: Fixing table and database names\nPhase 6/7: Checking and upgrading tables\nProcessing databases\ninformation_schema\nmailcow\nperformance_schema\nPhase 7/7: Running 'FLUSH PRIVILEGES'\nOK\n","type":"warning"}
php-fpm-mailcow_1    | Uptime: 2  Threads: 8  Questions: 8  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 4.000
php-fpm-mailcow_1    | SQL upgrade iteration #2
php-fpm-mailcow_1    | MySQL is up-to-date - debug output:
php-fpm-mailcow_1    | {"msg":"mysql_upgrade: already upgraded","text":"This installation of MySQL is already upgraded to 10.3.20-MariaDB, use --force if you still need to run mysql_upgrade\n","type":"success"}
php-fpm-mailcow_1    | Restarting Postfix
php-fpm-mailcow_1    | command completed successfully
php-fpm-mailcow_1    | Sleeping 5 seconds...<

it looks like that even after a reboot or a docker-compose down -v and up

**Comment by xDevyz** [comment]
i checked the docker compose without -d and this is what keeps like repeating

> dockerapi-mailcow_1  | api call: container_post__restart, container_id: cdc35b2976b78004253e8f7dca9c802df2aa34f921729803fa51ba79ff7e4ef5
postfix-mailcow_1    | 2019-11-18 21:37:59,992 WARN received SIGTERM indicating exit request
postfix-mailcow_1    | 2019-11-18 21:37:59,992 INFO waiting for postfix, processes, syslog-ng to die
postfix-mailcow_1    | Nov 18 21:37:59 mail syslog-ng[16]: syslog-ng shutting down; version='3.19.1'
postfix-mailcow_1    | 2019-11-18 21:38:00,094 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2019-11-18 21:38:00,118 INFO reaped unknown pid 375
postfix-mailcow_1    | 2019-11-18 21:38:00,119 INFO reaped unknown pid 376
postfix-mailcow_1    | 2019-11-18 21:38:00,119 INFO reaped unknown pid 377
postfix-mailcow_1    | 2019-11-18 21:38:00,120 INFO reaped unknown pid 378
postfix-mailcow_1    | 2019-11-18 21:38:00,120 INFO reaped unknown pid 380
postfix-mailcow_1    | 2019-11-18 21:38:00,122 WARN received SIGQUIT indicating exit request
postfix-mailcow_1    | 2019-11-18 21:38:00,124 INFO stopped: postfix (terminated by SIGTERM)
postfix-mailcow_1    | 2019-11-18 21:38:00,125 INFO stopped: processes (terminated by SIGTERM)
mailcowdockerized_postfix-mailcow_1 exited with code 0
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
dockerapi-mailcow_1  | 172.22.1.10 - - [18/Nov/2019 21:38:04] "POST /containers/cdc35b2976b78004253e8f7dca9c802df2aa34f921729803fa51ba79ff7e4ef5/restart HTTP/1.1" 200 -
php-fpm-mailcow_1    | command completed successfully
php-fpm-mailcow_1    | Sleeping 5 seconds...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
dockerapi-mailcow_1  | api call: container_post__exec__system__mysql_tzinfo_to_sql, container_id: ce4a5be664333412357a4c8a52a6424eb8ba52050f87534e0f6b7fdcc828b908
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
rspamd-mailcow_1     | Waiting for PHP on port 9001...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...

**Comment by coresh** [comment]
# Same issue

```
$ sudo docker-compose logs --tail=50 php-fpm-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_php-fpm-mailcow_1
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
./mailcow-dockerized__2019_11_22__02_54_07][master]
```
```
$ sudo docker-compose logs --tail=1000 mysql-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_mysql-mailcow_1
mysql-mailcow_1      | 2019-11-22 04:22:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
mysql-mailcow_1      | 2019-11-22 04:22:21+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql-mailcow_1      | 2019-11-22 04:22:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] mysqld (mysqld 10.3.20-MariaDB-1:10.3.20+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Initializing buffer pool, total size = 8M, instances = 1, chunk size = 8M
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Waiting for purge to start
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: 10.3.20 started; log sequence number 2601520; transaction id 14083
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] Server socket created on IP: '::'.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Warning] 'proxies_priv' entry '@% root@69ad52d97b5c' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALU
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] mysqld: ready for connections.
mysql-mailcow_1      | Version: '10.3.20-MariaDB-1:10.3.20+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mysql-mailcow_1      | 2019-11-22  4:22:22 0 [Note] InnoDB: Buffer pool(s) load completed at 191122  4:22:22
./mailcow-dockerized__2019_11_22__02_54_07][master]
```

```
$ git log
$ commit 79bcbe5a517a8abd61cce652493854cd2507c6f2 (HEAD -> master, origin/master, origin/HEAD)

```

**Comment by coresh** [comment]
```
sudo docker-compose exec mysql-mailcow mysql -u mailcow -p
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Enter password: 
ERROR 1045 (28000): Access denied for user 'mailcow'@'localhost' (using password: YES)
```
```
sudo docker-compose exec mysql-mailcow mysql -u root -p
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
[1]    32626 exit 1     sudo docker-compose exec mysql-mailcow mysql -u root -p
```

### DBPASS and DBROOT entered properly

**Comment by andryyy** [comment]
You say it is a fresh install, so run this:

```
docker-compose down -v
docker-compose up -d
```

**Comment by coresh** [comment]
### multiple times.
The result -> same:
```
sudo docker-compose logs --tail=50 php-fpm-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_php-fpm-mailcow_1
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
```

> You say it is a fresh install, so run this:
> 
> ```
> docker-compose down -v
> docker-compose up -d
> ```

**Comment by danielpo** [comment]
I have the exact same issue, debian 10,

**Comment by dahabakuk** [comment]
im expierencing the very same. completly new debian 10 kvm guest with everything installed according to the install guide.
looks like has todo with this:
https://github.com/docker-library/mariadb/issues/262

**Comment by BlackWolfDEsign** [comment]
skip_lets_encrypt=n in your mailcow.conf

**Comment by dahabakuk** [comment]
hm i restarted from scratch (delete containers and volumes) and retried.
after reading lots of logs etc i was stuck at:
php-fpm-mailcow_1    | Restarting Postfix
php-fpm-mailcow_1    | command completed successfully
php-fpm-mailcow_1    | Sleeping 5 seconds...

this will stay there for 3-5 minutes.
in the meanwhile i connected to mysql - and after a while php-fpm-mailcow_1 
logged:
php-fpm-mailcow_1    | MySQL mysql_tzinfo_to_sql - debug output:
php-fpm-mailcow_1    | {"msg":"mysql_tzinfo_to_sql: command completed successfully","text":"Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.\n","type":"info"}
php-fpm-mailcow_1    | Running DB init...
php-fpm-mailcow_1    | Cleaned up memcached

i could watch single tables be created with "show tables" so this just seems to be awfully slow.... so just wait and bleed... last time i did restart it too soon.. maybe this interrupted the whole setup?

for me it seems to be fixed.

**Comment by kid4git** [comment]
I had the exact same issue as xDevyz, seeing constant 502 errors from nginx after it worked fine for me before.

I also got this:
```
$ docker logs -f mailcowdockerized_sogo-mailcow_1
Waiting for schema update...
ERROR 1146 (42S02) at line 1: Table 'mailcow.versions' doesn't exist
```

And I tracked it down to phpfpm's docker-entrypoint.sh:
```
# Check mysql_upgrade (master and slave)
CONTAINER_ID=
until [[ ! -z "${CONTAINER_ID}" ]] && [[ "${CONTAINER_ID}" =~ ^[[:alnum:]]*$ ]]; do
  CONTAINER_ID=$(curl --silent --insecure https://dockerapi/containers/json | jq -r ".[] | {name: .Config.Labels[\"com.docker.compose.service\"], id: .Id}" 2> /dev/null | jq -rc "select( .name | tostring | contains(\"mysql-mailcow\")) | .id" 2> /dev/null)
done
echo "MySQL @ ${CONTAINER_ID}"
```
I found that multiple "mysql-mailcow" container IDs were returned by that API call leading to an endless loop. The reason was that I had another stopped mysql-mailcow container lying around from when I used "mailcow-dockerized" instead of "mailcowdockerized" as folder name:
```
$ docker ps -a|grep mysql
deec079f87c2     mariadb:10.3    "docker-entrypoint.s…"   33 hours ago Exited (128) 33 hours ago     mailcow-dockerized_mysql-mailcow_1
...
```
So I guess the API should just return or be queried running containers which should fix the issue.

Related issue: #3265

UPDATE: Just saw that the folder name right now is indeed "mailcow-dockerized", but the COMPOSE_PROJECT_NAME is "mailcowdockerized". Not sure how I ended up with "mailcow-dockerized" as project name before.

**Comment by andryyy** [comment]
We need the full list of offline and online containers in some places.

The easiest fix is to monitor for duplicate containers. :) It should not happen.

Furthermore you will run into problems in other scripts, too. There should not be duplicate containers. :/

**Comment by alejandrobalderas** [comment]
I had the same issue with Debian 10. This happened after I updated my FQDN by running the generate_config script again. Before that I did a docker system prune -a.

**Comment by MAGICCC** [comment]
Probably you re-generated a fully fresh mailcow.conf with new passwords :/
You may need to change the mysql passwords or try to use the mailcow.conf_backup file

**Comment by DontPanicO** [comment]
May the disk is full

**Comment by iamdroppy** [comment]
Same issue is happening here

**Comment by pravynandas** [comment]
What @BlackWolfDEsign suggested worked great for me. I did not set the flag on a fresh installation and got this error. When I changed the flag in mailcow.conf and re-created the containers, everything worked like a magic.

Update `skip_lets_encrypt=n` in your mailcow.conf

`sudo docker-compose down -v`
`sudo docker-compose up -d`

All the very best!!
