### ISSUE TITLE
rename "whitelist/blacklist" in spam settings to "allowlist/blocklist"

### ISSUE THREAD

**Issue by burntout** [mailcow/mailcow-dockerized#3155]
Use of the words "whitelist" to denote "good" and "blacklist" to denote bad has negative connotations, and does not describe very well what the actual action is.  

please can you replace them with "Allow list" to signify email addresses that will always be allowed, and "block list" or "deny list" for email addresses that will always be blocked or denied. 

This will improve usability.

**Comment by andryyy** [comment]
I don't know. In mailing whitelist and blacklist are established terms.

**Comment by marrco** [comment]
> This will improve usability.

No, it won't.

Postmasters already know what a blacklist and a whitelist are. Do not invent new terms.

**Comment by alexanderadam** [comment]
> In mailing whitelist and blacklist are established terms.

Racism was once widely established as well. I'm very sure that we all can agree that 'but it is established' shouldn't be used as an argument to avoid any improvements.

> Postmasters already know what a blacklist and a whitelist are. Do not invent new terms.

If those Postmasters won't be able to adapt to 2 (I repeat: **two**!) 'new' words they will probably have a bad time.

Just a few examples why postmasters (or any other person in IT) will probably encounter replacements anyway:

* have a look on [this document the IETF recently published](https://tools.ietf.org/html/draft-knodel-terminology-01), which argues
  > that certain obviously offensive terms be avoided and replaced with alternatives. These sets of terms are "master-slave" and "white-blacklist" for their racist and race-based meanings.

* or see [what scientists think about it](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/)
* or [what Microsoft thinks about it](https://www.theregister.co.uk/2019/09/03/chromium_microsoft_offensive/) and [what they changed in the Chromium engine](https://bugs.chromium.org/p/chromium/issues/detail?id=981129) (you know, one of the popular browser engines)
* what [the Ruby on Rails members think about it](https://github.com/rails/rails/issues/33677#issuecomment-482582749) (also [this tweet](https://twitter.com/dhh/status/1032050325513940992))
* or the folks at the [graphite project](https://github.com/graphite-project/graphite-web/pull/1700)
* the [HTML standard specification on whatwg](https://github.com/whatwg/html/commit/cb3316db45e369ba31d97c5ee2dcd9c353a3cb5d)
* [Rack attack](https://github.com/kickstarter/rack-attack/pull/181)
* [Roslyn](https://github.com/dotnet/roslyn/pull/3507/files)
* or the folks at [GitLab](https://gitlab.com/gitlab-org/gitlab/issues/7554)

So my impression is, that if a company like Microsofts doesn't believe that those terms have to be established and manages to remove it for a code base like Chromium, it is _probably_ possible for others as well.

**Comment by mkuron** [comment]
I don't think Mailcow is the right place for political discussions like this. While the intent may be laudable, it comes at a price in terms of clarity, brevity and unambiguity.

For example, replacing "whitelist" with "allow list" is ambiguous and unclear (you don't need to be on that list to be allowed to send mail) and "spam filter bypass list" is lengthy and not completely clear either.

There do not appear to be alternative terms in widespread use (Exchange has "safe senders", Gmail doesn't even have that feature), and as a small mail server platform, we are not in the position to define new terms. We need to make it as easy as possible for people migrating from other platforms. Once Exchange, Yahoo, Gmail, etc. converge on a new name, we will happily adopt it.
