### ISSUE TITLE
Disable SGO

### ISSUE THREAD

**Issue by kr19dev** [mailcow/mailcow-dockerized#3159]
Mail-Cows SGO is great. But what if you like to use different software for caldav and carddav. Is there a way to disable sgo before spawn the container the first tine? An option in mailcow.cfg?

**Comment by MAGICCC** [comment]
No there's no option to disable SOGo yet. You can either stop the container (but please let it start after an update first) or you can decrease the workercount to 1 for example to let it run with min. RAM usage

**Comment by PSandro** [comment]
Is there any update on this? As #3345 shows, there is demand on this option to disable SOGo completely.
As a workaround: How do I properly let mailcow stop SOGo _automatically_ after it started? :thinking:

**Comment by andryyy** [comment]
You can create a proper pull request if you need this option. :)

**Comment by ghost** [comment]
@kr19dev @PSandro It looks like this feature was recently added in this commit: https://github.com/mailcow/mailcow-dockerized/commit/200167458e4025e4fc5d4317382760ffa9fb05a3#diff-bd6af8ddc3fbe4d221556680bc00048f

After changing `SKIP_SOGO=n` to `SKIP_SOGO=y` in my `mailcow.conf` file and restarting Mailcow, SOGo is gone from the list of apps and its container only consumes 2MB of RAM.

**Comment by navossoc** [comment]
The Memcached container can also be disabled, right? At least, looks like so.

[]'s
