### ISSUE TITLE
Editing Password Policy in mailcow UI

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#3161]
**Is your feature request related to a problem? Please describe.**
This is feature request. Currently default password policy can be changed via `data/web/inc/vars.local.inc.php`, but user hint will not feet changed policy - it simply says that password must be more then 6 characters long. New password generation function not respect password policy too. Additionally - writing correct Regex can be complicated for some one.

**Describe the solution you'd like**
It will be really helpful to add this settings to mailcow UI for system administrators. It can be preset of 3 or 4 policies or better fully customized policy (with enable|disable options with editable values) for:
_[can't be disabled]_ Password minimum chapters total - `value`, for example default `6`
_[customize]_ Password complexity requirements:
[✓|✗] must contain mixed lower and upper case characters (`a-z` and `A-Z`), for example default `✗`
[✓|✗] must contain numbers, for example default `✓`
[✓|✗] must contain special symbols (any of `*'":;!-+_` and so on), for example default `✗`

_Note:_
[✓|✗] is bool **true** of **false**
**Additional context**
This will give fully managed password policy and possibility to give correct hint as well as generate correct passwords for mailcow users when they change their passwords or add new App Passwords.

**Comment by chotaire** [comment]
Since this feature is missing there are currently outstanding major issues that cannot be bypassed: https://github.com/mailcow/mailcow-dockerized/issues/4053 and https://github.com/mailcow/mailcow-dockerized/issues/4054

**Comment by andryyy** [comment]
Issues were fixed, the password policy via UI was implemented.

**Comment by vermium** [comment]
@DerLinkman  This is implemented and should be closed I tihnk
