### ISSUE TITLE
Missing Style on admin Pages

### ISSUE THREAD

**Issue by c0deisme** [mailcow/mailcow-dockerized#3164]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
After an update using the update script now the complete styling is missing on the admin pages including login, but sogo and everything else looks normal
even when bypassing my reverse proxy it still is like that

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
1. I updated to the latest version
2. And then the styling was gone

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu Server 19.10 with Kernel 5.3.0-19 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4G of ram and 4 Cores |
| Docker Version (`docker version`) | 19.03.3 |
| Docker-Compose Version (`docker-compose version`) | 1.25.0 |
| Reverse proxy (custom solution) | nginx |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Attaching to mailcowdockerized_nginx-mailcow_1
nginx-mailcow_1      | 2019/11/23 14:35:56 [emerg] 17#17: host not found in upstream "rspamd" in /etc/nginx/conf.d/site.conf:119
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "rspamd" in /etc/nginx/conf.d/site.conf:119
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 172.22.1.12 - - [23/Nov/2019:14:36:02 +0100] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.66.0"
nginx-mailcow_1      | fd4d:6169:6c63:6f77::11 - - [23/Nov/2019:14:36:07 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "rspamd-2.1"
nginx-mailcow_1      | 172.22.1.13 - - [23/Nov/2019:14:36:07 +0100] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "rspamd-2.1"
nginx-mailcow_1      | 172.22.1.13 - - [23/Nov/2019:14:36:07 +0100] "HEAD /settings.php HTTP/1.1" 304 0 "-" "rspamd-2.1"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:29 +0100] "POST /rl/?/Ajax/&q[]=/_B3CMSKWNJKzt-st0UvXCWao5aN7LVE5jRwsB4iAd_dhaKaM2s6NYe8EZZkYI4Hugr2gFU2LluOfNVeJAmefGL9dIGkQh5m4u9HmW4ivRWJWLz9h-wo1l1oxDROlDzf0i1vsJ-hg9OoF_jJLflJ5DUIwGc
46XR7LSiWYoae2O2SBlAkb6EG4H1Rh-iJ4VpkW7PPWyYFCO1YY8YohixdSdyqKGg5bcGCiHsjKWLvQwACO-hOQQyWvcpynhDe8MR_lTqvMgKozJEXWhtpHUrXKnfO0E-9x4SzvODozLR1HixN3uzcxA0kklGveuIaX8SNX-SyIDeCOoEL3smJl7NpjD2votktgsmX4hpzWnHqg6cUi_OswN/ HTTP/1.0" 200 234 "https://mail.c0bra.dev/" "Mozilla/5
.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:32 +0100] "GET / HTTP/1.0" 200 16373 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:32 +0100] "GET /cache/4b6c9777eb9cb6038f1e5eed97807d8ee9d0465a.css HTTP/1.0" 404 146 "https://mail.c0bra.dev/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/7
0.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:32 +0100] "GET /cache/da5c62ea255439baef2f8a45c834f0b9c941c0cb.js HTTP/1.0" 404 146 "https://mail.c0bra.dev/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70
.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:34 +0100] "GET / HTTP/1.0" 200 16373 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:35 +0100] "GET / HTTP/1.0" 200 16373 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - - [23/Nov/2019:14:36:47 +0100] "GET / HTTP/1.0" 200 16373 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - mailadress [23/Nov/2019:14:36:59 +0100] "POST /Microsoft-Server-ActiveSync?jQAHBBAcR/zO+dN/KxMUS/mJKORuBAAAAAALV2luZG93c01haWw= HTTP/1.0" 200 0 "-" "-"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - mailadress [23/Nov/2019:14:36:59 +0100] "POST /Microsoft-Server-ActiveSync?jQAHBBAcR/zO+dN/KxMUS/mJKORuBAAAAAALV2luZG93c01haWw= HTTP/1.0" 200 12 "-" "-"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - mailadress [23/Nov/2019:14:37:59 +0100] "POST /Microsoft-Server-ActiveSync?jQAHBBAcR/zO+dN/KxMUS/mJKORuBAAAAAALV2luZG93c01haWw= HTTP/1.0" 499 0 "-" "-"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - mailadress [23/Nov/2019:14:38:00 +0100] "POST /Microsoft-Server-ActiveSync?jQAHBBAcR/zO+dN/KxMUS/mJKORuBAAAAAALV2luZG93c01haWw= HTTP/1.0" 200 0 "-" "-"
nginx-mailcow_1      | 2003:d1:53df:8400:5d1a:ea6a:cfdf:63ad - mailadress [23/Nov/2019:14:38:00 +0100] "POST /Microsoft-Server-ActiveSync?jQAHBBAcR/zO+dN/KxMUS/mJKORuBAAAAAALV2luZG93c01haWw= HTTP/1.0" 200 12 "-" "-"

**Comment by andryyy** [comment]
Try `docker-compose down`, followed by `git fetch ; git checkout origin/master data/conf/nginx ; docker-compose up -d`

**Comment by c0deisme** [comment]
unfortunately that didn't solve it

**Comment by andryyy** [comment]
You didn't post a git diff, so I assume there are no changes: Try `git pull` after running down and fix merge conflicts, if any.

**Comment by c0deisme** [comment]
oh, forgot to mention that there were no changes, sry

git pull says its up to date

but the nginx log says 404 to a /cache where supposedly js and css are inside

**Comment by andryyy** [comment]
You can try to run down and delete data/conf/nginx completly, then check it out again. If that does not work, I don't know what does.

**Comment by c0deisme** [comment]
hm, thats odd
i moved the nginx conf folder somewhere else, started it up again and now it said bad gateway

after moving the nginx folder back to conf now it works perfectly fine again even with stylesheet

thanks for the suggestion

**Comment by andryyy** [comment]
Crazy. :)
