### ISSUE TITLE
Postfix parameter "mail_name" allows a simple identification of a Mailcow system

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#3167]
With the [commit (16.10.2018)](https://github.com/mailcow/mailcow-dockerized/commit/d99b8aaf6952170218bb8c3b73f0025d0fdf32b6) the Postfix parameter "mail_name" was set to "Postcow" ([default "Postfix"](http://www.postfix.org/postconf.5.html)). 

Thus, the SMTP greeting banner of every Mailcow system now displays "Postcow". This allows a simple identification of all Mailcow systems.
If we now have a vulnerability in the system, the Mailcow systems can be more easily attacked because they do not get lost in the mass.  

[I currently find 15,251 Mailcow systems worldwide (8,676 are in Germany).](https://www.shodan.io/search?query=Postcow) 

If we would use the standard "Postfix", the Mailcow systems would be listed under the [3,049,901 Postfix systems. ](https://www.shodan.io/search?query=Postfix)

I know it's security by obscurity, but every little thing helps make a system more secure. 
How do you think about that?

**Comment by andryyy** [comment]
It was implemented to only change our own headers when anonymizing to not break signatures. 

I understand your point but prefer to keep it.

**Comment by mkuron** [comment]
You could just check the HTTPS server for each Postfix instance found by Shodan. If it exists and the page contains "mailcow UI", it's a Mailcow. Of course that's more work than actually searching for _Postcow_ on Shodan, but it's perfectly possible to do that for all 3 million Postfix servers.

**Comment by christianbur** [comment]
What if we only change "smtpd_banner"?

current:
smtpd_banner = $myhostname ESMTP $mail_name

Future (example):
smtpd_banner = $myhostname ESMTP Postfix

Info: postscreen adopts the smtpd_banner setting through the already existing config line "postscreen_greet_banner = $smtpd_banner".

http://www.postfix.org/postconf.5.html

**Comment by christianbur** [comment]
@mkuron 
Correct, but some (like me, for example) use a proxy for port 80/443 and the website doesn't listen to the MX record names.

**Comment by mkuron** [comment]
> What if we only change "smtpd_banner"?

That would work.

**Comment by patschi** [comment]
Wouldn't that still break the anonymization? 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/anonymize_headers.pcre

**Comment by christianbur** [comment]
With mail_name this should be the case with smtpd_banner it should work without problems.

**Comment by christianbur** [comment]
I just tested smtpd_banner successfully.

```
data/conf/postfix/extra.cf
+ smtpd_banner = $myhostname ESMTP Postfix
```
- smtp banner was changed (test with `telnet mx1.example.com 25`) 
- In the Emal header I see the following: 

```
Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPSA id 1C69E120042
	for <xxxxxxxxxxxx>; Sun, 24 Nov 2019 12:20:29 +0100 (CET)
```

**Comment by andryyy** [comment]
I don't think that test covers all possible scenarios.

I still do not support it.

**Comment by christianbur** [comment]
ok, since you can change the behavior in extra.cf yourself and a change is not desired, the ticket can be closed.

**Comment by gpz1100** [comment]
Sorry to bump up a years old thread.

I ran into this the other day trying to change mine as well.

@christianbur 

Mailcow v2023-05a on debian12 with whatever docker version is current as of 2023-07

Applying the change to ``data/conf/postfix/extra.cf`` yields in the file (and change) getting overwritten when the container is restarted.

Same result when applying it to the bottom of ``data/conf/postfix/main.cf`` .  It sticks only when applying to the top of the main.cf file.  Not sure why this is.  I'm quite new to docker and didn't realize parameter positioning in the conf file has such significance.  I can only assume something else is overriding this causing the behavior above.

Any thoughts why this is happening?
