### ISSUE TITLE
Can't seem to find way to block catchall alias address

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3169]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I've got a catch-all email alias which forwards the mails to postmaster@mydomain.com . One mail I used to register at a specific site once (lets say abc@mydomain.com ) is now receiving a lot of spam. I've used a catchall approach since with other systems, I was easily able to create a rule over a GUI that would allow me to block incoming mails to a specific alias address (in my case, abc@mydomain.com ). However, whilst I can train Rspamd to identify these mails as spam, I wasn't able to find a way on simply blocking all mail traffic to this catch-all alias. Here's what I tried before:

1. Sign in to the mailcow UI with my postmaster@mydomain.com catch-all address and add abc@mydomain.com with scope postmaster@mydomain.com to the blacklist, as to be seen below:
[Edited screenshot of mailcow UI configuration](https://imgur.com/a/AWffKn5 "Attempt 1")

2. Sign in to the mailcow UI with the admin account and try to find a way to classify/block incoming mail to that address as spam.
[Dead link, no idea what this is](https://imgur.com/a/SFYdD4f "Attempt 2")
[Here?](https://imgur.com/a/iRMOwhH "Attempt 3")

Since the documentation on especially these sections of the UI is non-existant and the section descriptions themselves include dead links, I have no idea where to create such a rule nor what syntax I should write it in.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

As to be seen above

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

This issue is not system related

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian |
| Is Apparmor, SELinux or similar active? | Nope |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Running on KVM |
| Server/VM specifications (Memory, CPU Cores) | 8 GB RAM, 4 cores |
| Docker Version (`docker version`) | 18.09.6 |
| Docker-Compose Version (`docker-compose version`) | 1.24.0-rcl |
| Reverse proxy (custom solution) | Jup, nginx reverse proxy configuration |
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/)....
-> I did, but sadly it wasn't helpful at all.

**Comment by andryyy** [comment]
Either create an alias to route it to null (silently discard) or use the 
global filter maps:


There are multiple ways.

If it's neither a bug nor a feature request, it is most likely a 
question: You can reach us on Telegram.

------ Originalnachricht ------
Von: "GitGangGuy" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 24.11.2019 22:02:23
Betreff: [mailcow/mailcow-dockerized] Can't seem to find way to block 
catchall alias address (#3169)

**Comment by ghost** [comment]
Alright, thanks a lot!
