### ISSUE TITLE
change postcow

### ISSUE THREAD

**Issue by karkaaa** [mailcow/mailcow-dockerized#3170]
Hello,

It is possible change this (Postcow)?:

```
telnet domain.com 25
Trying 8.8.8.8...
Connected to domain.com.
Escape character is '^]'.
220-domain.com ESMTP Postcow
```

**Comment by MAGICCC** [comment]
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/3167

**Comment by karkaaa** [comment]
i edit:
data/conf/postfix/main.cf

this line:
mail_name = Postfix

i hope everthing will be ok :)

**Comment by mkuron** [comment]
This will break header anonymization (and if you change the header anonymization to _Postfix_ too, it will break ARC signatures). Please read #3167 more carefully and use the solution with `smtp_banner`.
