### ISSUE TITLE
Different domain names for MX and MAILCOW_HOSTNAME with reverse proxy

### ISSUE THREAD

**Issue by saldru** [mailcow/mailcow-dockerized#3172]
Hi everyone,

I search how to configure well my mailserver with mailcow with the configuration I want but I have some issues to make everything to work well. 

Actually, I have a VM with one mailcow instance with one public IPv4 and one public IPv6 that is used for SMTP/IMAP/POP/SIEVE. For the HTTP/HTTPS part, I use a reverse HTTP Proxy with Nginx on another VM. 

The issue I have is that my mailcow server FQDN is like vm-mail-01.domain.tld and my MX DNS entry is like :

> **_domain.tld IN MX 10 smtp.domain.tld_**

and the A/AAAA DNS entry for smtp.domain.tld use the public IPs of the mailcow server directly and with that I'm not able to use the Autodiscover/Autoconfig of Active Sync because the email clients want to reach **_https://vm-mail-01.domain.tld:443_** instead of **_https://autodiscover.domain.tld:443_** so there is no HTTP/HTTPS listening directly on the mailcow VM so it don't work. And on the mailcow VM if I let 0.0.0.0 for HTTP and HTTPS, the email clients say that the SSL certificate is not valid because it don't pass by the HTTP Reverse Proxy. 

So someone know how to configure well Mailcow and Nginx (Reverse Proxy) to be able to have everything to work well (IMAP/SMTP) and WebUI and ActiveSync with Reverse Proxy as I want so like, SMTP/IMAP/POP/SIEVE use the direct IP address of the Mailcow VM and the HTTP/HTTPS use the IP of the HTTP Reverse Proxy.

Thank you in advance for your time and your help. :)
Saldru

**Comment by mkuron** [comment]
I don‘t quite understand your problem, but here are a few comments:
- Make sure the host name in your MX record and MAILCOW_HOSTNAME in mailcow.conf match. You currently have different ones, which is not supported.
- Make sure your reverse proxy has SSL certificates and virtual hosts configured for all autoconfig.*, autodiscover.* and $MAILCOW_HOSTNAME domains. See the Mailcow documentation for suggestions how to set up your reverse proxy.

**Comment by saldru** [comment]
Hi @mkuron,

With what you said, what is the goal of the HTTP reverse proxy if you have to define the MX entry name and the $MAILCOW_HOSTNAME to be the same ? 
The IPs will must have to point to the HTTP reverse Proxy and SMTP/IMAP/POP/SIEVE requests will not pass because they will reach the HTTP Reverse Proxy because MX entry will point to vm-mail-01.domain.tld. 

My problem is that I want to reach the HTTP/HTTPS WebUI of Mailcow via mail.domain.tld via my HTTP Reverse Proxy and my SMTP/IMAP/POP/SIEVE via smtp.domain.tld and my $MAILCOW_HOSTNAME to be vm-mail-01.domain.tld. 

You just told that I must configure my MX entry and my $MAILCOW_HOSTNAME to be the same but it's what I made since 6 months and, sometimes I receive error as "Diagnostic-Code: X-Postcow; mail for domain.tld loops back to myself". 

I don't know if you can understand better my problem !
Thank you for your time and your help ! 
Saldru

**Comment by saldru** [comment]
Hi @mkuron,

I solved my problem. I just put the $MAILCOW_HOSTNAME to point to the HTTP Reverse Proxy and everything work well with a $MAILCOW_HOSTNAME that is different from the MX entry. 

Thank you for your help.
Saldru
