### ISSUE TITLE
Be able to create a user but don't allow outgoing emails

### ISSUE THREAD

**Issue by ro78** [mailcow/mailcow-dockerized#3174]
Hello,

It would be great to be able to create a user only allowed to receive emails, not to send anything.
Usecase: a mailbox where anyone can drag&drop emails from another account (to keep headers).

What do you think?

**Comment by mkuron** [comment]
Just use ACLs to share that mailbox with the other users. Then you don't need to give them the password and they won't be able to send from that account.

**Comment by ro78** [comment]
I forgot to say that the person who will drop emails inside this « receive only » account won’t have any other account on my mailhost.

**Comment by mkuron** [comment]
You could try either rate limiting (set it to zero messages per hour, not sure if that works) or putting the address on the global blacklist.

**Comment by andryyy** [comment]
The global blacklist is a good idea. You can also work with Rspamd settings maps.

**Comment by ro78** [comment]
May I ask you where is the global blacklist?
