### ISSUE TITLE
Latest update broke ClamAV and IPV6_NAT

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#3176]
Hi there,
After updating to latest version ClamAV container it's not working anymore, it keeps restarting itself. The same is happening with IPV6_NAT container.
In logs i see every 30 seconds this:

`Nov 29 16:39:54 b8ea728b036b[1172]: /clamd.sh: line 92: kill: (20) - No such process
Nov 29 16:39:55 b8ea728b036b[1172]: Copying non-empty whitelist.ign2 to /var/lib/clamav/whitelist.ign2
Nov 29 16:39:55 b8ea728b036b[1172]:   File: /var/lib/clamav/whitelist.ign2
Nov 29 16:39:55 b8ea728b036b[1172]: Access: (0644/-rw-r--r--)  Uid: (  700/  clamav)   Gid: (  700/  clamav)
Nov 29 16:39:55 b8ea728b036b[1172]: dos2unix: converting file /var/lib/clamav/whitelist.ign2 to Unix format...
Nov 29 16:39:55 b8ea728b036b[1172]: Running freshclam...
Nov 29 16:39:55 b8ea728b036b[1172]: WARNING: Ignoring deprecated option ScanOnAccess at /etc/clamav/clamd.conf:44
Nov 29 16:39:55 b8ea728b036b[1172]: LibClamAV Error: cli_load(): Can't open file /var/lib/clamav/whitelist.ign2
Nov 29 16:39:55 b8ea728b036b[1172]: LibClamAV Error: cli_loaddbdir(): error loading database /var/lib/clamav/whitelist.ign2
Nov 29 16:39:55 b8ea728b036b[1172]: LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
Nov 29 16:40:07 4dd44084b519[1172]: 2019-11-29 16:40:07 #52(normal) <af5430>; lua; clamav.lua:119: clamav: failed to scan, maximum retransmits exceed`

If it helps, also IPV6_NAT is not starting.
I have tried to stop and start everything including a full system reboot without luck.
What should i check/do?
Thank you!

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 16.04 |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4 Cores, 16GB Ram |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | NO |

**Comment by andryyy** [comment]
ipv6nat-mailcow is not able to start clamd? What is happening with ipv6nat exactly?

It did not break. I don't see this on any system, sorry.

**Comment by lucianlazar1983** [comment]
After updating today (never happened before), both IPv6 NAT and ClamAV containers are not starting. I have tried to disable ClamAV in mailcow.conf and after that IPv6 NAT is starting correctly. If i enable ClamAV again, it will break both ClamAV and IPV6NAT. For IPv6 NAT there is no log other that the one start/stop. The ClamAV errors are the one i attached before. Could ClamAV failure be related also to IPv6 NAT? what can i do to fix ClamAV?
Thank you.

**Comment by lucianlazar1983** [comment]
Any clues on how can i restore che ClamAV container? is there a safe way to "delete" and recreate the container? I don't know what is the relation but as i mentioned in my previous comment, if i let Clamav as disabled then IPV6_NAT container starts just fine. Otherwise it does not, and nor is Clamav. So this is why i suppose IPV6_NAT is related to Clamav failure.
Thank you all in advance

**Comment by lucianlazar1983** [comment]
I am closing this issue because the problem is with the current kernel update 4.4 in Ubuntu 16.04 that broke overlayfs. (Thanks Andy!) See the announcement in mail cow for more info. Downgrading to 4.15 resolves the issue.
