### ISSUE TITLE
Dovecot in bootloop

### ISSUE THREAD

**Issue by brandoningli** [mailcow/mailcow-dockerized#3178]

**Comment by brandoningli** [comment]
Update: I reverted dovecot to an older version (1.79) via the compose file, then back to the latest without deleting the old tags (I deleted them when updating last time) and it's stable so far.

**Comment by jwhb** [comment]
Same problem here. I got dovecot back to work by reverting to 1.88 which was active before the update.

**Comment by andryyy** [comment]
Make sure it has the correct config files. Reset `data/conf/dovecot` to origin/master (delete it, run git fetch and git checkout origin/master data/conf/dovecot).

No problem here on my machines or those I support.

**Comment by jwhb** [comment]
@andryyy thanks for the reply.
Unfortunately that didn't solve it for me.

```
[root@x mailcow-dockerized]# rm -rf data/conf/dovecot/
[root@x mailcow-dockerized]# git fetch
[root@x mailcow-dockerized]# git checkout origin/master data/conf/dovecot
[root@x mailcow-dockerized]# ls data/conf/dovecot/
dovecot.conf  global_sieve_after  global_sieve_before  ldap

[root@x mailcow-dockerized]# docker-compose up --force-recreate dovecot-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Recreating mailcow_unbound-mailcow_1 ... done
Recreating mailcow_mysql-mailcow_1   ... done
Recreating mailcow_dovecot-mailcow_1 ... done
Attaching to mailcow_dovecot-mailcow_1
dovecot-mailcow_1    | Uptime: 1  Threads: 8  Questions: 1  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 1.000
dovecot-mailcow_1    | Adding user `vmail' to group `tty' ...
dovecot-mailcow_1    | Adding user vmail to group tty
dovecot-mailcow_1    | Done.
dovecot-mailcow_1    | doveconf: Error: t_readlink(/var/run/dovecot/dovecot.conf) failed: readlink() failed: No such file or directory
dovecot-mailcow_1    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow_1    |                                  Dload  Upload   Total   Spent    Left  Speed
```

I also noticed that with image version 1.88 the link does exist and dovecot comes up, although it does display the error message as shown above.
With 1.97 I get the readlink error, the link does not exist and dovecot won't come up.

**Comment by jwhb** [comment]
In my configuration I noticed that DNS resolution didn't work from at least the Dovecot container and that made the curl call in the entrypoint fail.
The broken DNS resolution was my fault, since I moved the Mailcow network to 172.80.0.0/24 which is not in the 172.16.0.0/12 range.
Moving Mailcow back to a valid private network fixed DNS resolution and my Dovecot now works as intended.
I do still see the readlink error, but this doesn't seem to be important at all.

@brandoningli seems to be in a different situation, since in the logs the curl call does work.

**Comment by ProfFan** [comment]
Just updated my system and encountering the same error (`t_readlink failed`). I am still trying to recover from it...

**Comment by andryyy** [comment]
It is not important at all. It happens when calling doveconf without Dovecot running.

**Comment by ProfFan** [comment]
@andryyy Thank you for the help! However I am still stuck at the `No mailbox selected` in SoGo...

**Comment by ProfFan** [comment]
@andryyy Attached is my Dovecot log:

```
sudo docker-compose logs --tail=200 dovecot-mailcow
Attaching to mailcowdockerized_dovecot-mailcow_1
dovecot-mailcow_1    | Uptime: 3  Threads: 8  Questions: 2  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 0.666
dovecot-mailcow_1    | Adding user `vmail' to group `tty' ...
dovecot-mailcow_1    | Adding user vmail to group tty
dovecot-mailcow_1    | Done.
dovecot-mailcow_1    | doveconf: Error: t_readlink(/var/run/dovecot/dovecot.conf) failed: readlink() failed: No such file or directory
dovecot-mailcow_1    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow_1    |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
100    43  100    43    0     0     94      0 --:--:-- --:--:-- --:--:--    94
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
```

SoGo log says:
```
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 host=172.22.1.250, user=i@xxxxx.me, pwd=yes
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 url=imaps://i%40xxxxx.me@172.22.1.250/
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 base=(null)
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 base-class=(null))
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 = <0x0x55a26e0fd220[NGImap4Client]: login=i@xxxxx.me(pwd) address=<0x0x55a26e12c320[NGInternetSocketAddress]: host=172.22.1.250 port=993>>
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 sogod [70]: [ERROR] <0x55a26e314c60[SOGoMailAccount]:0> Could not connect IMAP4
sogo-mailcow_1       | Jan 20 03:57:13 f7f37ef91117 sogod [70]: 69.222.133.119 "POST /SOGo/so/i@xxxxx.me/Mail/unseenCount HTTP/1.0" 200 21/31 0.031 - - 0
sogo-mailcow_1       | Jan 20 03:58:02 f7f37ef91117 CRON[79]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jan 20 03:58:02 f7f37ef91117 CRON[80]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jan 20 03:58:02 f7f37ef91117 CRON[82]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 480)
sogo-mailcow_1       | Jan 20 03:58:02 f7f37ef91117 CRON[83]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Jan 20 03:58:03 f7f37ef91117 CRON[80]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Jan 20 03:58:03 f7f37ef91117 CRON[79]: pam_unix(cron:session): session closed for user sogo
```

**Comment by andryyy** [comment]
I cannot help. Looks like the whole network stack is broken. 

I don't know about your iptables rules, your OS or anything. Try to get support in the mailcow channel via Telegram, please. :) We moved community support to this location.

**Comment by brandoningli** [comment]
The error here is that there's no dovecot.conf file.

How I solved this in the interim:
>I reverted dovecot to an older version (1.79) via the compose file, then back to the latest without deleting the old tags (I deleted them when updating last time) and it's stable so far.

**Comment by andryyy** [comment]
Nope. As said previously, it complains about the missing symlink, which does not exist as long as Dovecot is not running. A doveconf command is run before Dovecot is active (to get a path).

The curl timeouts indicate a network problem.

**Comment by ProfFan** [comment]
@andryyy I think it is some kind of configuration issue: curl is trying to get some strange names...
```
dovecot-mailcow_1    | curl: (6) Could not resolve host: ;
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 512 seconds. 1 retries left.
dovecot-mailcow_1    | curl: (6) Could not resolve host: <<>>
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.
```

**Comment by ProfFan** [comment]
@andryyy I think it is some kind of configuration issue: curl is trying to get some strange names...
```
dovecot-mailcow_1    | curl: (6) Could not resolve host: ;
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 512 seconds. 1 retries left.
dovecot-mailcow_1    | curl: (6) Could not resolve host: <<>>
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
dovecot-mailcow_1    | Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.
```

**Comment by andryyy** [comment]
It is a network issue. It is not able to resolve anything.

You should stop all containers, restart Docker and run up -d again.

Please also see my hint how to get support, thanks. :)

**Comment by brandoningli** [comment]
> It is a network issue. It is not able to resolve anything.
> 
> You should stop all containers, restart Docker and run up -d again.

Not necessarily. It's trying to resolve a host whose name is the empty string or `<<>>`. That's a configuration issue in my eyes, not a network one. Even properly configured networks will not be able to resolve those. In that case, it's a bug report, and belongs here.

**Comment by ProfFan** [comment]
@andryyy Running `curl "<<>>"` on my local machine returns `curl: (6) Could not resolve host: <<>>` immediately, so I think something is still wrong other than the network.

**Comment by ProfFan** [comment]
Also, `sudo docker exec -it $(sudo docker ps -qf name=dovecot-mailcow) curl google.com` returns:
```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by andryyy** [comment]
Please post everything that is asked in the issue template, @ProfFan - it is probably easier to open a new issue, if you think it is a bug (tell us exactly how to replicate it, please). Also post the output of `ls -la mailcow_folder` and where you installed mailcow to (folder location).

If you are absolutly sure it is not your machine, mail me to info@servercow.de so I can have a look remote.

**Comment by brandoningli** [comment]
Remote access to the machine? That's overkill and not necessary.

**Comment by andryyy** [comment]
Okay, I will just send a prayer then.

**Comment by brandoningli** [comment]
That's an absolutely horrible mindset to have. You can debug an issue with the codebase/configuration without having remote access to someone's server.

**Comment by andryyy** [comment]
I also never offered you remote hands, @brandoningli, so what is your anger about? :) A TeamViewer session is nothing unnecessary, when you cannot replicate an issue.

**Comment by brandoningli** [comment]
As someone studying software engineering, I have an issue with a developer immediately resorting to taking remote control of someone's server instead of working through the codebase. It is an invasion of the user's privacy let alone security.

A TeamViewer session on servers running this is either not possible (as there's no GUI running), or an insane security risk. Depending on the environment this is deployed in, having a stranger remote in is a big no-no. I don't know who you are or how reputable you are, and I certainly wouldn't trust an internet stranger with full access to my machine.

Ask for the information you need. Don't resort to taking it via remote control.

And to anyone else reading this: In general, don't allow a stranger remote access to your machine, ever. It may be benign and someone with good intentions, but it could also be someone looking to completely destroy your machine and all data within.

**Comment by brandoningli** [comment]
@ProfFan please create a new issue, as this seems unrelated to what I was facing originally. And whatever you do, don't give remote access.

**Comment by patschi** [comment]
Well, then you probably never raised a case/ticket with larger firms where "strangers" help you.  If you raise a case with VMware, just an example, they won't search years in the billions of codelines to find out any specific bug you might encounter. And in the most cases it was even a infrastructure issue not related to the product code anyway. Remote Session is often the way to go. More efficient - often takes less time for a helpful outcome.

It's your decision if you don't want to do a remote session with @andryyy. Fine. I've seen him helping many other peoples just for a simple "Thank you" in return. Your decision if you don't trust him.

Downvoting all his comments because... he's developing mailcow mostly alone and offering help at no cost in his free-time? Well played.

**Comment by patschi** [comment]
Just to add: Andre is not just a random "stranger". He's helping to many people over the last years, and offering paid support (e.g. with remote hands) with his own company and doing that for a living.

I do agree that remote session/control with random "strangers" hiding behind some anonymous acronyms isn't the best idea, but that's not the case here.

And beside that you always have the chance doing a TeamViewer session over the computer of the guy which requested help, so you can follow what's being done exactly and can prevent bad stuff from happening.

Andre is in the mailserver-space for years and he's very well experienced based on what I've seen. If he thinks that's any specific error in your setup, there's a high chance he's right.

**Comment by brandoningli** [comment]
Let it be known that the downvotes are not for offering help at no cost. They're for responding with comments like 

>Okay, I will just send a prayer then.

instead of working towards obtaining the diagnostic information needed to determine where the fault lies.

And yes, I've many an experience with filing tickets with larger corporations. Never have they resorted immediately to remote control before first gathering diagnostic information to try and determine where the issue lies. No such attempt was made here, other than resorting to calling a failure to resolve `<<>>` a "major network stack failure."
