### ISSUE TITLE
Open relay

### ISSUE THREAD

**Issue by phreakazoid** [mailcow/mailcow-dockerized#3179]
Hi since one Week my Server is used for Spamming. I have updated Mailcow but still ... 
I don't find whats wrong. I don't know how the Spammer gets a mail to Postfix without Auth of a User. 

```
Received: from mail.XXX.XX ([XXX.XXX.XXX.XXX]:38316)
by webprod01.geektoast.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
(Exim 4.92)
(envelope-from )
id 1iZlOd-0008Lz-VW
for mary.thomas@unicitynetwork.com; Tue, 26 Nov 2019 17:41:38 -0700
Received: from [x.xxx.xxx.xxx] (unknown [xxx.xx.x.x])
by mail.XXX.XX (Postcow) with ESMTP id 0FFE4260430;
Tue, 26 Nov 2019 23:51:47 +0100 (CET)
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Description: Mail message body
Subject: Glad Tidings.
To: Recipients
From: lawrenpierre@gmail.com
Date: Wed, 27 Nov 2019 06:50:19 +0800
Reply-To: lawrence44pierre@gmail.com
Authentication-Results: mail.XXX.XX;
none
X-Spamd-Result: default: False [7.51 / 15.00];
ARC_NA(0.00)[];
HAS_REPLYTO(0.00)[lawrence44pierre@gmail.com];
BAYES_SPAM(1.11)[90.30%];
FREEMAIL_FROM(0.00)[gmail.com];
REPLYTO_DN_EQ_FROM_DN(0.00)[];
MIME_GOOD(-0.10)[text/plain];
FREEMAIL_REPLYTO(0.00)[gmail.com];
REPLYTO_DOM_EQ_FROM_DOM(0.00)[];
TO_DN_RECIPIENTS(2.00)[];
FREEMAIL_ENVRCPT(0.00)[yahoo.com,sbcglobal.net,juno.com,comcast.net,cox.net,bellsouth.net,att.net,cs.com,excite.com,yahoo.com.mx,gmail.com,rocketmail.com,verizon.net,adelphia.net];
RCPT_COUNT_ONE(0.00)[1];
MISSING_MID(2.50)[];
TO_DN_ALL(0.00)[];
FROM_NO_DN(0.00)[];
FREEMAIL_TO(0.00)[gmail.com];
RCVD_COUNT_ZERO(0.00)[0];
FROM_EQ_ENVFROM(0.00)[];
TO_EQ_FROM(0.00)[];
MIME_TRACE(0.00)[0:+];
FREEMAIL_ENVFROM(0.00)[gmail.com];
FORGED_RECIPIENTS(2.00)[lawrenpierre@gmail.com,marv2mends@yahoo.com ...]
X-Rspamd-Queue-Id: 0FFE4260430
X-Spam-Subject: ***SPAM*** Glad Tidings.
X-Spam-Status: Yes, score=15.1
X-Spam-Score: 151
X-Spam-Bar: +++++++++++++++
X-Spam-Report: Spam detection software, running on the system "webprod01.geektoast.com",
has identified this incoming email as possible spam. The original
message has been attached to this so you can view it or label
similar future email. If you have any questions, see
root\@localhost for details.
Content preview: Dear Sir/Madam, I am Lawrence Pierre , financial assistant
to late Jeffrey Epstein Financier owner, an American billionaire who died
recently in new York prison. Two days before his death he instructed me to
give $10 [...]
Content analysis details: (15.1 points, 5.0 required)
pts rule name description
---- ---------------------- --------------------------------------------------
1.7 DEAR_SOMETHING BODY: Contains 'Dear (something)'
0.0 URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was
blocked. See
http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
for more information.
[URIs: nymag.com]
0.0 DKIM_ADSP_CUSTOM_MED No valid author signature, adsp_override is
CUSTOM_MED
0.0 FREEMAIL_FROM Sender email is commonly abused enduser mail
provider (lawrenpierre[at]gmail.com)
1.5 SPF_SOFTFAIL SPF: sender does not match SPF record (softfail)
1.1 DCC_CHECK Detected as bulk mail by DCC (dcc-servers.net)
0.0 KAM_SHORT Use of a URL Shortener for very short URL
0.6 FSL_BULK_SIG Bulk signature with no Unsubscribe
0.0 LOTS_OF_MONEY Huge... sums of money
1.0 FREEMAIL_REPLYTO Reply-To/From or Reply-To/body contain
different freemails
1.2 NML_ADSP_CUSTOM_MED ADSP custom_med hit, and not from a mailing
list
2.0 SPOOFED_FREEMAIL No description available.
2.0 SPOOFED_FREEM_REPTO Forged freemail sender with freemail
reply-to
0.0 T_FILL_THIS_FORM_SHORT Fill in a short form with personal
information
2.1 MONEY_FORM_SHORT Lots of money if you fill out a short form
1.9 MONEY_FRAUD_3 Lots of money and several fraud phrases
0.0 FORM_FRAUD_3 Fill a form and several fraud phrases
X-Spam-Flag: YES
```

**Comment by mkuron** [comment]
> `Received: from [x.xxx.xxx.xxx] (unknown [xxx.xx.x.x])`
> `by mail.XXX.XX (Postcow) with ESMTP id 0FFE4260430;`

I assume `mail.XXX.XX` is your Mailcow server? Is the `x.xxx.xxx.xxx` by chance an RFC 1918 IP address (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)? If so, the spam is being sent either by someone on your internal network or your router/firewall is NATing incoming connections to your Mailcow. These internal network addresses are trusted by Postfix by default and thus don't require authentication.

**Comment by phreakazoid** [comment]
The x were done by my hoster or by the people who mailed my hoster. I have edited the big Xs. How can I deactivate the NATing? I have updated to Debian Buster a week or 2 ago. Maybe there has been changed something by the system.

**Comment by mkuron** [comment]
This doesn‘t happen on a default install of Mailcow on a clean system. Are you running **anything** else on this server (VMs, VPN server, ...)? Also, if you have IPv6 enabled, check whether the ipv6nat container is running and whether its rules are in the right place in ip6tables.

Check your Postfix logs to see if any unexpected messages are being relayed and if private IP addresses appear there. Also you can check rspamd‘s web UI (have a look into the Mailcow documentation if you don‘t know it); it will also show the sending IP addresses for the past ~1000 messages.

**Comment by Adorfer** [comment]
Looks like "another case of running mailcow together with other containers/modified docker bridge network/firewall". 
Perhaps there needs a more strict warning in the docs and perhaps even in the installer itself.

**Comment by phreakazoid** [comment]
There are some other docker container. And there is an Installed "Outline VPN" Installation with uses Docker. How can I get rid of this Problem?

**Comment by andryyy** [comment]
Other containers or even Docker networks are not a problem.

This is probably a NAT issue and/or any external software messing with the iptables rules. I don't think we can help you, as we don't know your network, your network settings and the other software, that messes with iptables. Outline is such a software to mess with/change iptables rules.

I don't think we need to add a warning. We cannot watch the local network config (or even the routers behind that) of every server for everyone who uses mailcow. This doesn't only relate to mailcow, every network service can break or do bad things, if the network is messed with.

I recommend you run `docker-compose down`, stop the VPN stuff, restart the docker service (`systemctl restart docker` for example), run `docker volume rm mailcowdockerized_postfix-vol-1`  and restart the stack by running `docker-compose up -d`.

**Comment by phreakazoid** [comment]
I've done what u have said.
here are my iptables -S rules. Maybe somebody can see something

> -P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-USER
-N DOCKER-ISOLATION-STAGE-2
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-mailcow -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-mailcow -j DOCKER
-A FORWARD -i br-mailcow ! -o br-mailcow -j ACCEPT
-A FORWARD -i br-mailcow -o br-mailcow -j ACCEPT
-A FORWARD -o br-05727160b95a -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-05727160b95a -j DOCKER
-A FORWARD -i br-05727160b95a ! -o br-05727160b95a -j ACCEPT
-A FORWARD -i br-05727160b95a -o br-05727160b95a -j ACCEPT
-A FORWARD -o br-c181c46be239 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-c181c46be239 -j DOCKER
-A FORWARD -i br-c181c46be239 ! -o br-c181c46be239 -j ACCEPT
-A FORWARD -i br-c181c46be239 -o br-c181c46be239 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 30033 -j ACCEPT
-A DOCKER -d 172.22.1.2/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 10011 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p udp -m udp --dport 9987 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 8983 -j ACCEPT
-A DOCKER -d 172.18.0.5/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 12345 -j ACCEPT
-A DOCKER -d 172.18.0.7/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 8448 -j ACCEPT
-A DOCKER -d 172.18.0.8/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 30033 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 4190 -j ACCEPT
-A DOCKER -d 172.18.0.7/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.18.0.8/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 10011 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.18.0.7/32 ! -i br-c181c46be239 -o br-c181c46be239 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.18.0.8/32 ! -i br-c181c46be239 -o br-c181c46be239 -p udp -m udp --dport 9987 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 995 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 993 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 143 -j ACCEPT
-A DOCKER -d 172.22.1.250/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 110 -j ACCEPT
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 587 -j ACCEPT
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 465 -j ACCEPT
-A DOCKER -d 172.22.1.6/32 ! -i br-mailcow -o br-mailcow -p tcp -m tcp --dport 25 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-mailcow ! -o br-mailcow -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-c181c46be239 ! -o br-c181c46be239 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-05727160b95a ! -o br-05727160b95a -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-USER -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-mailcow -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-c181c46be239 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-05727160b95a -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN

Mailcow Network is "172.22.1.0/24"

**Comment by phreakazoid** [comment]
I set up a new server for mailcow only and migrated my volumes and configs. No Open Relay after install. Thx for help.

**Comment by LinAGKar** [comment]
>These internal network addresses are trusted by Postfix by default and thus don't require authentication.

Why does it do that anyway? Allowing relaying from any unauthenticated users, regardless of source IP, seems like a pretty bad idea, that serves no purpose other than allowing it to inadvertently be turned into a relay.
