### ISSUE TITLE
Error 502 After Cleaninstall

### ISSUE THREAD

**Issue by basti2s** [mailcow/mailcow-dockerized#3180]
Hello,

i hope you could help me. I am new in using mailcow and i got this problem:

after starting it with: `docker-compose up -d`
Ive got this as Output: 
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
mailcowdockerized_memcached-mailcow_1 is up-to-date
mailcowdockerized_unbound-mailcow_1 is up-to-date
mailcowdockerized_redis-mailcow_1 is up-to-date
mailcowdockerized_sogo-mailcow_1 is up-to-date
mailcowdockerized_watchdog-mailcow_1 is up-to-date
mailcowdockerized_solr-mailcow_1 is up-to-date
mailcowdockerized_dockerapi-mailcow_1 is up-to-date
mailcowdockerized_olefy-mailcow_1 is up-to-date
mailcowdockerized_clamd-mailcow_1 is up-to-date
mailcowdockerized_mysql-mailcow_1 is up-to-date
mailcowdockerized_php-fpm-mailcow_1 is up-to-date
Starting mailcowdockerized_postfix-mailcow_1 ...
mailcowdockerized_dovecot-mailcow_1 is up-to-date
mailcowdockerized_nginx-mailcow_1 is up-to-date
mailcowdockerized_rspamd-mailcow_1 is up-to-date
Starting mailcowdockerized_postfix-mailcow_1 ... done
mailcowdockerized_netfilter-mailcow_1 is up-to-date
mailcowdockerized_ipv6nat-mailcow_1 is up-to-date

When i am now trying to go on the Interface via http://domain:PORT ive got the Error :"502"

This is my docker-compose log telling:
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_php-fpm-mailcow_1
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...
php-fpm-mailcow_1    | Waiting for SQL...

Ive allready disabled my ufw.
I hope you could help me, and i am sorry if some informations are missing.

**Comment by varunsridharan** [comment]
I am also having the same issue

**Comment by andryyy** [comment]
Probably related to https://github.com/docker-library/mariadb/issues/262 and slow machines. We already skip the TZ data. If you machine is slow as fuck, it will still not work.

I have not seen this on spinning disks anymore after we skipped the TZ data. But it is quite possible, it is still happening. I don't have a slow enough machine in support, so I cannot test it.

**Comment by varunsridharan** [comment]
@andryyy i am installing this in a freenas VM so if you want i can help in any way i could.

**Comment by andryyy** [comment]
Hmmm, not sure if that's a good idea. What hardware is it installed on?

**Comment by varunsridharan** [comment]
@andryyy 
FREENAS Config is

1. Core i5 9th GEN
2. 64GB RAM

**Comment by basti2s** [comment]
and i am using an v-server

**Comment by andryyy** [comment]
I'd need full ssh access to that server to check why this happens.

**Comment by varunsridharan** [comment]
@andryyy i can give. but not here. let me know how we can move from here.
My email : varunsridharan23@gmail.com
Skype : varunsridharan23

**Comment by varunsridharan** [comment]
@andryyy  Below is the output when i run `docker-compose up`

```
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
dovecot-mailcow_1    | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
nginx-mailcow_1      | 2019/12/03 10:51:54 [error] 18#18: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.3, server: mail.sva.run, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.1.8:9002", host: "10.0.100.245"
nginx-mailcow_1      | 2019/12/03 10:51:54 [error] 18#18: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.3, server: mail.sva.run, request: "GET / HTTP/1.1", upstream: "fastcgi://[fd4d:6169:6c63:6f77::b]:9002", host: "10.0.100.245"
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:54 +0530] "GET / HTTP/1.1" 502 1076 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:54 +0530] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 146 "http://10.0.100.245/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:54 +0530] "GET /favicon.ico HTTP/1.1" 404 146 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:58 +0530] "GET / HTTP/1.1" 502 1076 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 2019/12/03 10:51:58 [error] 18#18: *1 no live upstreams while connecting to upstream, client: 10.0.0.3, server: mail.sva.run, request: "GET / HTTP/1.1", upstream: "fastcgi://phpfpm", host: "10.0.100.245"
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:58 +0530] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 146 "http://10.0.100.245/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
nginx-mailcow_1      | 10.0.0.3 - - [03/Dec/2019:10:51:58 +0530] "GET /favicon.ico HTTP/1.1" 404 146 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
sogo-mailcow_1       | Waiting for database to come up...
php-fpm-mailcow_1    | Waiting for SQL...
dovecot-mailcow_1    | Waiting for database to come up...
postfix-mailcow_1    | Waiting for database to come up...
rspamd-mailcow_1     | Waiting for PHP on port 9001...
```

**Comment by andryyy** [comment]
Is it a KVM VM?

**Comment by varunsridharan** [comment]
@andryyy i am not that good of a server person. but i believe its a VM inside FreeNAS (FreeBSD)

**Comment by basti2s** [comment]
does anybody know something about my problem?

**Comment by g0rbe** [comment]
I have the same issue.

```
502

Please do not stop the stack, while we are initializing the database or do other preparations.
```
Edit:
A restart solved my problem

**Comment by eliasdistrict** [comment]
Most probably it is a RAM problem, increase your server's RAM to at least 6 GB RAM with using it on Ubuntu
