### ISSUE TITLE
latest update broke language files?

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#3183]
Hi there, i have update today hoping to fix the ClamAV problem but i have seen that now the English language is not working anymore, please see screenshot.
I have tested on 3 different instances all have the same problem. What should i do?
Thanks
<img width="1435" alt="Screen Shot 2019-12-02 at 16 57 43" src="https://user-images.githubusercontent.com/3727896/69969496-3081af00-1525-11ea-86d1-b5a745a542b6.png">

**Comment by andryyy** [comment]
Thank you. 

Fixed with 24e97e50575360cc1c06771557b044a4febb8436
