### ISSUE TITLE
Catchall doesn't work for alias domains

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#3184]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I have multiple domains. All domains are domain aliases of the main domain.
On the main domain, I have a catchall rule.
This catchall rule only works for the alias domains, if the sending server is a whitelisted relayhost.
Otherwise postfix rejects the message with 
`550 5.1.1 <domain@MY-ALIAS-DOMAIN>: Recipient address rejected: User unknown in virtual mailbox table;`

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

*(see above for situation)*
1. Send an e-mail to any address on my aliased domain
2. And then the mail gets rejected.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | `Ubuntu 18.04.3 LTS`; Kernel: `4.15.0-46-generic` |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | OVH VPS, most probably KVM |
| Server/VM specifications (Memory, CPU Cores) | OVH VPS Cloud RAM 3 |
| Docker Version (`docker version`) | `19.03.4` |
| Docker-Compose Version (`docker-compose version`) | `1.24.1, build 4667896b` |
| Reverse proxy (custom solution) | no |

Further notes:
- Except for custom rspamd rules, nothing changed
 
 General logs:

```
postfix-mailcow_1    | Dec  2 15:41:09 mail postfix/postscreen[17958]: CONNECT from [85.158.142.XXX]:50786 to [172.22.1.8]:25
postfix-mailcow_1    | Dec  2 15:41:09 mail postfix/postscreen[17958]: WHITELISTED [85.158.142.XXX]:50786
postfix-mailcow_1    | Dec  2 15:41:10 mail postfix/smtpd[17961]: connect from mail1.bemta26.DOMAIN.com[85.158.142.XXX]
postfix-mailcow_1    | Dec  2 15:41:10 mail postfix/smtpd[17961]: Anonymous TLS connection established from mail1.bemta26.DOMAIN.com[85.158.142.XXX]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
postfix-mailcow_1    | Dec  2 15:41:10 mail postfix/smtpd[17961]: NOQUEUE: reject: RCPT from mail1.bemta26.DOMAIN.com[85.158.142.XXX]: 550 5.1.1 <domain@MY-ALIAS-DOMAIN.ga>: Recipient address rejected: User unknown in virtual mailbox table; from=<EXTERNAL-MAILADDRESS> to=<domain@MY-ALIAS-DOMAIN> proto=ESMTP helo=<mail1.bemta26.DOMAIN.com>
postfix-mailcow_1    | Dec  2 15:41:15 mail postfix/smtpd[17961]: disconnect from mail1.bemta26.DOMAIN.com[85.158.142.XXX] ehlo=2 starttls=1 mail=1 rcpt=0/1 quit=1 commands=5/6
```

**Comment by andryyy** [comment]
You need to create catch-all addresses for alias domains, too.

**Comment by mindsolve** [comment]
Thank you for the response.
Is there maybe a way to achieve this without creating aliases for each and every domain?

**Comment by mindsolve** [comment]
As this is no bug report (anymore ;) and no feature request, I am closing this to not further pollute the issue tracker.
Thanks again for the response!
