### ISSUE TITLE
migrate mailboxes from ispconfig?

### ISSUE THREAD

**Issue by mnooblet** [mailcow/mailcow-dockerized#3185]
I just setup mailcow and I'm trying to migrate mailboxes from an ispconfig installation, I think the passwords there are stored with crypt.

I created the mail account in sogo and updated the password using "update mailbox set password='{MD5-CRYPT}$1$poL.....' where username='mailbox@test.com'"

I've also tried to pefix SHA512-crypt.

However I can't login with the password I had on the ispconfig installation.

The hash for the password testtest is $1$poLjctfX$nSxwhTLffAVUyYTUewFAq/ in the old ispconfig database.

**Comment by andryyy** [comment]
Hi, after changing the hashes, run docker-compose down and up -d ... the view needs to be updated. That should do it.

**Comment by mnooblet** [comment]
okay great, thank you it works with md5-crypt after restarting the containers.

could you explain why it doesn't work without a restart? Is sogo caching the passwords somehow?

thank you
