### ISSUE TITLE
Last upgrade rendered web interface unusable

### ISSUE THREAD

**Issue by maffo999** [mailcow/mailcow-dockerized#3188]
**Description of the bug**:  After last upgrade of my instance of mailcow-dockerized, the web interface is not usable since no text is displayed. SoGo however works fine.

**Reproduction of said bug**:  
1) Upgraded mailcow through upgrade script but diff file is empty after upgrade
`root@host:/opt/mailcow-dockerized# ./update.sh
Checking internet connection... OK
Checking for newer update script...
remote: Enumerating objects: 591, done.
remote: Counting objects: 100% (591/591), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 1215 (delta 527), reused 558 (delta 504), pack-reused 624
Receiving objects: 100% (1215/1215), 641.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (832/832), completed with 124 local objects.
From https://github.com/mailcow/mailcow-dockerized
   726235e9..3ea8996d  master     -> origin/master
update.sh changed, please run this script again, exiting.`
2) Went to https://my.domain.tld
3) logged in
4) found no text displayed almost anywhere (buttons, labels, tabs, etc.)
Have tried accessing via different browsers both in normal and incognito mode after clearing cache and cookies.

`root@host:/root# cat /etc/issue
Debian GNU/Linux 9 \n \1

root@host:/root# docker -v
Docker version 19.03.5, build 633a0ea838

root@host:/root# docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

SELinux/AppArmor: not used
`

screenshot of the issue: https://imgur.com/a/tsRXpCx
 
 General logs:
I am willing to provide logs but I feel the standard log collection is way too big for the need so I would like to know which specific container(s) need to be collected

**Comment by lucianlazar1983** [comment]
yesterday evening @andryyy updated the repo with fixes for the language strings in the json file, that was the problem. Are you sure you updated to the latest version? Otherwise you can browse the github repo on the latest version and copy/paste the content of data/web/lang/lang.en.json overwriting your local copy.
Hope it helps

**Comment by maffo999** [comment]
I guess I have updated before @andryyy updated the repo, ran another update now and all looks good!
