### ISSUE TITLE
IMAP search not working

### ISSUE THREAD

**Issue by sndrsnk** [mailcow/mailcow-dockerized#3189]
First off, thank you for Mailcow, I've been an extremely happy user for a number of months now. 

Everything is working great... aside from my email search. I have only one mailbox set up under one primary domain. Here's my issue: 

1. Set up my iOS mail app to synchronise email via IMAP. 
2. Search "All Mailboxes" for the word "Australia" -- this should return an email I received way back from 2007 where the word is contained in the body of the message. 
3. Only one result from 2015 which is not said message is appearing. 

Here are some steps/notes during my troubleshooting of the issue: 

* When I search mail via SoGo Groupware it's working fine -- the issue is limited to IMAP search. 
* I've been able to replicate in Thunderbird with 'Search Server' selected. 
* Once I first noticed the issue I tried to enable Solr (4GB VPS) and performed both commands to rescan and re-index. The logs indicated `hits=0` for all my search results when searched via IMAP. 
* I'm also (primarily) able to replicate the issue with Solr disabled. 
* Side note which may be related to the issue: My iOS device says "This message has not been downloaded from the server" for older messages. 
* I updated my Mailcow last week; however, I do not know if the issue was occurring prior to this time (I think it was). 

| My operating system | Debian |
| Is Apparmor, SELinux or similar active? | No |
| Server/VM specifications (Memory, CPU Cores) | 4GB |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | No |

Thanks in advance.

**Comment by mkuron** [comment]
> When I search mail via SoGo Groupware it's working fine

SOGo uses IMAP too. So I suspect the different clients encode their search queries slightly differently and only the one by SOGo actually leads to the correct result.

Could you please enable verbose logging for Dovecot and then show us the log entries corresponding to the searches from the different clients?

**Comment by sndrsnk** [comment]
I've attempted to enable verbose logging by setting `mail_debug=yes` in `dovecot.conf` and running `docker logs mailcowdockerized_dovecot-mailcow_1` but when I search I can't find any string that matches the word "australia".

**Comment by andryyy** [comment]
Can you post the logs of both searches when debug is enabled?

Both use IMAP search indeed.

**Comment by sndrsnk** [comment]
Apologies for the delay, here are the logs: 

IMAP search working via SoGo: 
	https://pastebin.com/NanpswsP

IMAP search NOT working via iOS:
	https://pastebin.com/H1ktKHiq

Thank you

**Comment by mkuron** [comment]
The working one prints messages like the following:
```
Debug: Mailbox Personal: UID 1: Opened mail because: search
```

I suspect that this is the message that Dovecot prints while it is performing a non-Solr fulltext search through a message. So perhaps iOS does not do a server-side search?

For further debugging, we need logs of the raw IMAP protocol. Could you please enable that as per https://wiki.dovecot.org/Debugging/Rawlog and show us the IMAP search commands that the different clients send?

**Comment by sndrsnk** [comment]
Thanks @mkuron. I've obtained `.in` and `.out` raw logs; however, they appear to be binary files. I've attempted to use `doveadm` (as per https://wiki.dovecot.org/Tools/Doveadm/Dump) to view them but none of the types match. Can you advise how I can read these logs?

**Comment by mkuron** [comment]
Unfortunately I haven't done this before either. If you do figure it out, please write down how you did it.

**Comment by mkuron** [comment]
I don't think doveadm is the right tool here. Are you sure you can't just read these files in a hex editor?

**Comment by sndrsnk** [comment]
Note: Still in progress -- I haven't had a chance to look at the logs again since.

**Comment by wblondel** [comment]
Searching with the Gmail app on Android doesn't work neither. It loads indefinitely. How could I help debugging the issue?

**Comment by mkuron** [comment]
We need a full log of the IMAP protocol conversation, both with a good and a bad client. I don’t know how to configure Dovecot to write that to a file though.  https://serverfault.com/a/981502 might be a good start.

**Comment by andryyy** [comment]
Tested and looks good.

So we really need some logs of yours.

**Comment by wblondel** [comment]
I will have a look at it this Saturday.

**Comment by sndrsnk** [comment]
Thanks. Let me know if you need anything from my end.

**Comment by mkuron** [comment]
We still need an IMAP packet log for a good and a bad search so we can identify the difference.

**Comment by sndrsnk** [comment]
I'll try and take a look at this over the weekend using the steps outlined in mkuron's link.

**Comment by sndrsnk** [comment]
Tried again today and where I was able to obtain *.in and *.out dovecot logs, they're all in binary format -- either that or they're encrypted.
