### ISSUE TITLE
SOGo and Refresh View Interval

### ISSUE THREAD

**Issue by zolthar** [mailcow/mailcow-dockerized#3190]
How can I enforce or set a default whereby SOGo View (ie Web View) refresh interval is every_minute?

I have followed the guide here:
https://sogo.nu/files/docs/SOGoInstallationGuide.html

I have attempted to set these variables in the following conf file:
/opt/mailcow-dockerized/data/conf/sogo.conf
SOGoRefreshViewIntervals = 1;
SOGoRefreshViewCheck = every_minute:
Restarted SOGo Container

However if any of the above are listed, within the preference of a mailbox it is set to Manual.

This is in a fresh install with only 1 Mailbox as I am testing and seeing how it compares with traditional Exchange features (which so far are almost identical which is awesome).

This issue is not related to PUSH feature on mobile devices as they are working well - ie. emails are pushed to mobile devices through MS ActiveSync EAS.

**NOTE:** I have enough knowledge in Ubuntu/Mailcow to cause problems and not enough to fix them 😃 so this is my own learning curve to force me to learn - even if I have to format and restart for the many times so far to get it right - so please be gentle when you are roasting me!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/70123634-574dfb80-1673-11ea-8e45-d6c1a68b91fb.png)

It is a user setting, it does not work in sogo.conf. You can set it with sogo-tool or use the UI. :)

**Comment by andryyy** [comment]
You can set it like this:

```
docker-compose exec -u sogo sogo-mailcow /usr/sbin/sogo-tool user-preferences set defaults andre@develcow.de SOGoRefreshViewCheck '{"SOGoRefreshViewCheck":"every_minute"}'
```

**Comment by zolthar** [comment]
Thank you Andre, I will try that and then will try to create a script for all users default to x minutes instead of the default manual. Thanks heaps for the quick reply.

**Comment by frost8321** [comment]
> Thank you Andre, I will try that and then will try to create a script for all users default to x minutes instead of the default manual. Thanks heaps for the quick reply.

Were you able to write a script for that? I'd be grateful if you could help me with it.
