### ISSUE TITLE
[Postfix] Delegation: Cannot send message: all recipients are invalid.

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3193]
**Prior to placing the issue, please check following:**
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

FYI I check #380 and no option helps regarding the issue here.

---

**Description of the bug**: 

When I setup delegation from an address A to another (address B) on the server I can't send e-mail from address B using A "From:"

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
1. I login to address A
2. Setup delegation to address B
3. Logout from address A
4. Login to address B
5. Try to send an email using address A as "From:"
6. Get the "Cannot send message: all recipients are invalid." error

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | No |
| Server/VM specifications (Memory, CPU Cores) | 2 cores, 8GiB RAM |
| Docker Version (`docker version`) |19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | No |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
```
$ git diff origin/master
diff --git a/data/conf/rspamd/local.d/spamassassin.conf b/data/conf/rspamd/local.d/spamassassin.conf
deleted file mode 100644
index d091af63..00000000
--- a/data/conf/rspamd/local.d/spamassassin.conf
+++ /dev/null
@@ -1 +0,0 @@
-ruleset = "/etc/rspamd/custom/sa-rules";
```
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
100% stock, not relevant
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 100% stock, not relevant

General logs:
Available upon request, I don't want to share them publicly. Anyway, here is the exact issue:
```
postfix-mailcow_1    | Dec  4 12:31:44 mail postfix/sogo/smtpd[356]: connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]
postfix-mailcow_1    | Dec  4 12:31:44 mail postfix/sogo/smtpd[356]: NOQUEUE: reject: RCPT from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]: 553 5.7.1 <REDACTED>: Sender address rejected: not owned by user REDACTED; from=<REDACTED> to=<REDACTED> proto=ESMTP helo=<9dd66cbcd172>
postfix-mailcow_1    | Dec  4 12:31:44 mail postfix/sogo/smtpd[356]: disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=4/5
```

**Comment by andryyy** [comment]
I know this is stupid. But you need to allow it in mailcow, too. 

Edit the mailbox you want to send mail as, change the Sender ACL and allow the user, who wants to use this mailbox.

**Comment by ghost** [comment]
Hey @andryyy 

> I know this is stupid. But you need to allow it in mailcow, too. Edit the mailbox you want to send mail as, change the Sender ACL and allow the user, who wants to use this mailbox.

Thanks for answering and don't worry, it makes perfectly sense! SOGo alone can't tell Postfix that address B is allowed sending emails from address A!

Your suggestion indeed works, it's perfect. Many thanks!
