### ISSUE TITLE
rspamd 1.56 not updated to 

### ISSUE THREAD

**Issue by mamair** [mailcow/mailcow-dockerized#3196]
Moovember Update announcement says, "rspamd has been updated to version 2.12" but updating with script i get following message:

> 1.56: Pulling from mailcow/rspamd
> Digest: sha256:f5af36c7402a7e6c15d150236aca1da17637df43a7b960788c69022af5b6343c
> Status: Image is up to date for mailcow/rspamd:1.56
Something wrong with my installation (on debian 10) ???

**Comment by patschi** [comment]
`mailcow/rspamd:1.56` is the container version, and not the rspamd version. 1.56 ships with rspamd 2.1.

**Comment by andryyy** [comment]
It is actually 2.2 already. :)

```
# docker-compose exec rspamd-mailcow rspamd --version
Rspamd daemon version 2.2
```
