### ISSUE TITLE
Gui after update not really visible/usable anymore

### ISSUE THREAD

**Issue by k3v1n-eu** [mailcow/mailcow-dockerized#3197]
Hi,

after i did the November Update i cant use my gui anymore. It looks like there is some kind of transparent overlay. I can't click on any button.
Screenshot: [https://i.ibb.co/thd2ZWt/Bildschirmfoto-2019-12-05-um-00-11-41.png](url)

Thanks in advance!

**Comment by phillipplum** [comment]
Too bad that you have deleted the bug template, then we would have more information. But please try to clear the browser cache.

**Comment by andryyy** [comment]
Run ./update.sh again

**Comment by k3v1n-eu** [comment]
Hey guys. I tried now to run update.sh again but still the same issue. Also i tried to clean Browser cache. :-(
