### ISSUE TITLE
(with work-around) Dovecot and Postfix not working after Update to ff53dd5

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#3198]
## Description of the issue
Updated on 30/11 (moovember update).
Updated again today (05/12) to https://github.com/mailcow/mailcow-dockerized/commit/ff53dd58fb2756651b7c455a58c1a5b8edd9e894 and just after the update got a errors on Dovecot and Postfix.

## WORK-AROUND
For anyone facing the same issue, here is what I did (after talking with very helpful mailcow community members on Telegram):

_Quick steps_

- Reverted dovecot image to 1.99;
- Reverted /data/conf/dovecot/dovecot.conf to https://github.com/mailcow/mailcow-dockerized/commit/2e35da681674c250238519f4a9e3e581393f50f2
- Restarted mailcow;

_Full steps_
If you are like me and never reverted an docker image before, follow the full steps bellow:

1. edit [docker-compose.yml on line 175](https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml#L175) (from commit https://github.com/mailcow/mailcow-dockerized/commit/ff53dd58fb2756651b7c455a58c1a5b8edd9e894) to `image: mailcow/dovecot:1.99`
1. revert [/data/conf/dovecot/dovecot.conf](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/dovecot/dovecot.conf) from commit https://github.com/mailcow/mailcow-dockerized/commit/ff53dd58fb2756651b7c455a58c1a5b8edd9e894 to [/data/conf/dovecot/dovecot.conf](https://github.com/mailcow/mailcow-dockerized/blob/2e35da681674c250238519f4a9e3e581393f50f2/data/conf/dovecot/dovecot.conf) from commit https://github.com/mailcow/mailcow-dockerized/commit/2e35da681674c250238519f4a9e3e581393f50f2#diff-02b27738b10d34a92288ed447735ccfa
1. Shutdown the containers with `docker-compose down`
1. Pull the images with `docker-compose pull`
1. Start the containers with `docker-composer up -d`

Hope this helps!

## Logs
Here are the logs I believe are relevant.

### Dovecot Logs
```
12/5/2019, 12:46:15 AM | info | imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 25 secs): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
-- | -- | --
12/5/2019, 12:46:15 AM | info | imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 29 secs): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
12/5/2019, 12:46:15 AM | err | master: Error: service(auth): command startup failed, throttling for 60.000 secs
12/5/2019, 12:46:15 AM | crit | auth: Fatal: passdb-lua: initialization failed: lua_load(/var/lib/dovecot/app-passdb.lua) failed: error loading file
12/5/2019, 12:46:12 AM | info | pop3-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 30 secs): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250
12/5/2019, 12:46:12 AM | err | pop3-login: Error: auth-client: conn unix:login (pid=112,uid=0): Timeout waiting for handshake from auth server. my pid=211, input bytes=0
12/5/2019, 12:46:08 AM | info | imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 30 secs): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
12/5/2019, 12:46:08 AM | err | imap-login: Error: auth-client: conn unix:login (pid=112,uid=0): Timeout waiting for handshake from auth server. my pid=210, input bytes=0
12/5/2019, 12:46:00 AM | warning | imap-login: Warning: Auth process not responding, delayed sending initial response (greeting): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
12/5/2019, 12:46:00 AM | warning | imap-login: Warning: Auth process not responding, delayed sending initial response (greeting): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
12/5/2019, 12:46:00 AM | warning | imap-login: Warning: Auth process not responding, delayed sending initial response (greeting): user=<>, rip=XXX.XXX.XXX.XXX, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
```

### Postfix Watchdog email
```
12/5/2019, 12:50:00 AM | warning | warning: process /usr/lib/postfix/sbin/smtpd pid 436 exit status 1
-- | -- | --
12/5/2019, 12:49:39 AM | warning | warning: process /usr/lib/postfix/sbin/smtpd pid 434 exit status 1
12/5/2019, 12:49:21 AM | info | disconnect from engine6.uptimerobot.com[69.162.124.227] commands=0/0
12/5/2019, 12:49:21 AM | info | lost connection after CONNECT from engine6.uptimerobot.com[69.162.124.227]
12/5/2019, 12:49:21 AM | info | connect from engine6.uptimerobot.com[69.162.124.227]
12/5/2019, 12:49:16 AM | warning | warning: process /usr/lib/postfix/sbin/smtpd pid 432 exit status 1
12/5/2019, 12:49:15 AM | crit | fatal: no SASL authentication mechanisms
12/5/2019, 12:49:14 AM | warning | warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
12/5/2019, 12:49:14 AM | warning | warning: process /usr/lib/postfix/sbin/smtpd pid 431 exit status 1
12/5/2019, 12:49:13 AM | crit | fatal: no SASL authentication mechanisms
12/5/2019, 12:49:10 AM | info | Anonymous TLS connection established from unknown[XXX.XXX.XXX.XXX]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
12/5/2019, 12:49:08 AM | info | connect from unknown[XXX.XXX.XXX.XXX]
12/5/2019, 12:49:03 AM | info | Anonymous TLS connection established from unknown[XXX.XXX.XXX.XXX]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
12/5/2019, 12:49:01 AM | info | connect from unknown[XXX.XXX.XXX.XXX]
12/5/2019, 12:48:52 AM | warning | warning: process /usr/lib/postfix/sbin/smtpd pid 427 exit status 1
```

**Comment by patschi** [comment]
Just to add: This is more a temporary workaround for the "Socket timeout" issue. No one should run a older dovecot version with different docker image versions for a longer time. Might cause unexpected issues/problems in a longer run.

But as far as I know from @andryyy, this specific issue should be fixed?

**Comment by mthax** [comment]
Definetly not just a testing problem, my mailbox on 22.04 lts did the same, while @ work and won't start anymore. Restore won't work cause of dovecot not starting Sadly mailcow doesn't really say you what it expects or dislikes there
