### ISSUE TITLE
warning: hostname domain.domain does not resolve to address x.x.x.x say the ip was wrong

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#3201]
Hi.
I have this "error" massang in my log:
warning: hostname domain.domain does not resolve to address x.x.x.x 

This domain has 2 ips.
One are from Hetzner to connect directly 
the another are from my subnet.

The ip in the error masage are, the from the supnet, the domain are have the dna record for the first ip (dirctly connect to hetzner)

How can i make to fix the massage?
I hove i make this rieght.

**Comment by ghost** [comment]
Hi,

Such a shame you removed the issue template, not nice of you.

Anyway, here is the solution to your problem, read the documentation here to specify SNAT IPs: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-snat/

**Comment by Conan179** [comment]
Wait a minute, i have a root server, with vmware esxi.
https://wiki.hetzner.de/index.php/VMware_ESXi/en#Network_Configuration_2
"To use a subnet (IPv4 as well as IPv6) in ESXi, at least one additional single IP is required as a router VM, since ESXi itself cannot route. When ordering a subnet, please make sure to note that it is required for ESXi and should be routed on the additional single IP."

The domain with the 2 ips, are for the router vm.
Mailcow is not running on this.
Its on a vm, who connect to the router vm.
Its not a snat config, all my vms, on esxi has a public ipv4 (and public ipv6) and directly from internet reachable.

on the router vm, donst run mailcow, only postman to send (not receive) Emails.
i dont think ist a bug in mailcow.
I was hoping that I could give a tip on how to hide the message.

**Comment by mkuron** [comment]
I see two possible causes:
- your router VM and your Mailcow have the same hostname
- you have an internal DNS server on the router VM that contains incorrect records for the mailcow hostname or IP

**Comment by andryyy** [comment]
And the locally installed Postfix (or really Postman?) sends mail to your mailcow, which runs on the same machine?

I think writing in german is fine in this issue, as we seem to have trouble understanding the issue. :)

**Comment by Conan179** [comment]
Wunderbar mein English ist nicht das beste.
@mkuron
-  Die Hostname sind verschieden, habe ich eben kontrolliert
-  auf der RouterVM ist zwar dnsmasq innstalliert, aber alle vms sind drauf eingestellt das sie google dns nutzten sollen, dnsmaq wollte ich nutzten damit es per dhcp ips verteilt, wen ich mal eine vm starte ohne die ip addresse manuell eintippen zu müssen, habs nicht hinbekommen und dhcp abgeschalten.

Es ist Postfix, das muste ich nachschauen.
Auf allen VMs, die auf dem root server laufen (kein nat, alle öffentliche ipv4 und v6) läuft postfix, auch auf  der VM wo mailcow innstalliert worden ist.
Die RouterVM ist nicht die vm wo mailcow innstalliert ist.

Die RouterVM hat 2 netzwerkkarten (eth0 & eth1), die erste ist mit Hetzner verbunden.
Die 2te mit einem virtuellen software switch von esxi verbunden, alle anderen VMs sind mit dem Switch verbunden.
eth0 hat eine ip und eht1 hat eine andere.
Ich greife immer nur auf die eth0 ip zu.
RouterVM hat eine domain und dort ist die ip von eth0 hinterlegt.
Mailcow sagt, die ip der RouterVM domain müsse die von eth1 sein, stats die eth0 wo ich hinterlegt habe.
Ich geht stark davon aus, das es kein bug von mailcow ist, ich hab es hier eröffnet, weil ich dachte, hier bekämme ich support, weil mailcow die meldung ausspuckt.
