### ISSUE TITLE
Getting "not found" on SOGo when replying or forwarding e-mail

### ISSUE THREAD

**Issue by nicolaspernoud** [mailcow/mailcow-dockerized#3202]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

On some (but not all) mailboxes in SOGo, I get a mail not found error in the opened window :
The faulty mailbox has delegation from an other box...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I log to SOGo
2. And then select a mail and click reply
3. But the opened window's sender, object, content, (all) fields are empty and an (!) Not found is displayed on the bottom of the window

What is very strange is if I copy the opened window URL (like https://mail.*******.fr/SOGo/so/******@******.fr/Mail/UIxMailPopupView#!/Mail/0/INBOX/6632/reply) and paste it in a new tab : it works !!!

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.
- [X] Restart the all mailcow stack (docker-compose down and docker-compose up)

**System information**

No particular configuration

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10|
| Is Apparmor, SELinux or similar active? | No|
| Virtualization technlogy (KVM, VMware, Xen, etc) | VPS at Scaleway |
| Server/VM specifications (Memory, CPU Cores) | 2Go VCPU|
| Docker Version (`docker version`) | 19.03.3 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | webfront |

Further notes:

I would seems at some point the opened window make an xhr request to an Not A Number mail : 
"https://mail.******.fr/SOGo/so/******@*******.fr/Mail/0/folderINBOX/NaN/reply", 

 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Hi,

Can you update mailcow and try again? If it doesn't work, please open a bug at https://sogo.nu/bugs/

**Comment by nicolaspernoud** [comment]
Hi,

Updating solved the problem : thanks a lot.

Best regards, and thanks for your amazing work !
