### ISSUE TITLE
Removed because non-issue

### ISSUE THREAD

**Issue by dollhaus** [mailcow/mailcow-dockerized#3203]
Removed because non-issue

**Comment by MAGICCC** [comment]
`<domain>.international` is not a FQDN, thats a domain name
You would need to use `foo.bar.international` - see also [here](https://serverfault.com/questions/269838/what-is-the-difference-between-a-hostname-and-a-fully-qualified-domain-name)

>My suggestion would be to avoid validating the TLD altogether, and just look for the presence of one or more dots (.), to simplify this process, since new TLDs are fairly frequent.

The script checks basicly for two dots, https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L45

**Comment by andryyy** [comment]
You cannot make the suggestion to avoid it, when you don't know why the check exists. :/ :)

It should be indeed more strict and check for inputs like `bla.com.tw`, too. But anyway, just use a FQDN to be safe - as the script asks you for. :)

**Comment by dollhaus** [comment]
> 
> 
> `<domain>.international` is not a FQDN, thats a domain name
> You would need to use `foo.bar.international` - see also [here](https://serverfault.com/questions/269838/what-is-the-difference-between-a-hostname-and-a-fully-qualified-domain-name)
> 
> > My suggestion would be to avoid validating the TLD altogether, and just look for the presence of one or more dots (.), to simplify this process, since new TLDs are fairly frequent.
> 
> The script checks basicly for two dots, https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L45

I'm sorry, I had a complete wet brain moment. I thought the script prompt was specifically asking me *not* to use my domain, when in fact it was the opposite in this case, since my domain is my server's hostname. I then presumed the script was evaluating the TLD. I feel very silly now, and I'm sorry for wasting time.
