### ISSUE TITLE
Catchall E-Mail Adress forwarding with umlaut domain is not (more?) working

### ISSUE THREAD

**Issue by RogerSik** [mailcow/mailcow-dockerized#3205]
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:  When sending to a catchall adress with umlauts in the domain the mailserver responds with "554 5.7.1 <info@xxxx>: Relay access denied." This seems to happen after newest update installation last week. To be safe I updated today and this issue still happens. Searching shows that someone else had this issue with an inactive domain. Domain is active. For safety disabled and enabled. Still happens. 

**Reproduction of said bug**: Sending the mails to said domain. When sending to another catchal domain without umlauts the issue doens't happen. So im sure it is a bug in the newer version. 

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | AWS |
| Server/VM specifications (Memory, CPU Cores) | 4 CPU, 16 GB RAM|
| Docker Version (`docker version`) | 19.03.5|
| Docker-Compose Version (`docker-compose version`) | 1.24.1|
| Reverse proxy (custom solution) | none, using only mailcow |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
` NOQUEUE: reject: RCPT from mail-wm1-x32e.google.com[2a00:1450:4864:20::32e]: 554 5.7.1 <info@xxx>: Relay access denied; from=<r.sikorski@xxx.de> to=<info@xxx> proto=ESMTP helo=<mail-wm1-x32e.google.com>`

**Comment by andryyy** [comment]
Hi,

What's the output for `docker-compose exec postfix-mailcow postconf smtputf8_enable`?

**Comment by RogerSik** [comment]
The output is 

`smtputf8_enable = yes`

**Comment by andryyy** [comment]
Can you set it to "no" in `data/conf/postfix/main.cf`? Just for testing... edit: and restart Postfix! `docker-compose restart postfix-mailcow`

**Comment by RogerSik** [comment]
Yes it works with the setting 
`smtputf8_enable = no`

**Comment by andryyy** [comment]
You can send and receive mails to and from umlaut domains with `smtputf8_enable = no`?

**Comment by RogerSik** [comment]
With `smtputf8_enable = no` I can send emails to the catchall umlaut domains. Its only used as catchall forwarder so we only had this situation / setup.

**Comment by andryyy** [comment]
Ok, thank you. :)

**Comment by RogerSik** [comment]
Should i put this in the extra main.cf file or will this be in a future commit included? :) 

Strange it shouldn't be a problem with smtputf8_enable  or?
