### ISSUE TITLE
Sync Jobs Not Removing

### ISSUE THREAD

**Issue by stevesbrain** [mailcow/mailcow-dockerized#321]
Hi all,

When I got to remove a sync job (tick it, quick actions, remove) it doesn't remove from the list. I can deactivate it, but I cannot remove it (plus, when I try, a very non-descriptive "_Are you sure you want to remove the following items?: *1_ is shown - this could probably have a better label/title). Cheers :)

**Comment by andryyy** [comment]
Hi,

Is this the master branch?

**Comment by stevesbrain** [comment]
@andryyy Yeah, this is master branch. I'm a couple of commits behind (was at 49bb816a1cf883d8ee317d0f6a8c168ee26801d9 ) but will pull and update now to check.

Edit: Can confirm as of de9e398cc2e55f1d41795d7f7928cb6edf59fe6f I am still experiencing this issue (also using latest images from ```docker-compose pull```)

**Comment by andryyy** [comment]
I will push to master asap. :) I fixed a lot of code in the UI over the past days.

**Comment by stevesbrain** [comment]
Awesome, thanks so much for your hard work on all this @andryyy :) I'll keep donating as funds permit!
