### ISSUE TITLE
update.sh not executing after update first runtime 

### ISSUE THREAD

**Issue by MElhagaly** [mailcow/mailcow-dockerized#3210]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is: Yesterday I decided to install the Moovember updates but first I upgraded my kernel (i.e. installed the one recommended  [here](https://mailcow.email/2019/12/05/update-your-kernel-if-you-are-on-ubuntu-16-04/))

Next I went ahead and executed the `.\update.sh` script to start the update. The first execution was successful and the latest commit was pulled. I was instructed to re-run the script to start the update. Unfortunately upon running `.\update.sh` not much is happening. 

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Update kernel:
```
apt-get update
apt-get install --install-recommends -y linux-generic-hwe-16.04
reboot
```
2. Run `.\update.sh`
Run `.\update.sh` to pull latest commit
3.  But once I reran: `.\update.sh` I notice that nothing is happening (no errors and no output/echo's in the terminal). 

I have tried to retrace the problem and came across the following:
Even though the `apt-get install --install-recommends -y linux-generic-hwe-16.04` command was executed successfully and after a reboot running `uname -r` results in: `4.4.127-mainline-rev1`  meaning that the kernel installed isn't configured as default.  

This is the first "sub"issue. 

Keeping in mind commit:  https://github.com/mailcow/mailcow-dockerized/commit/7e2aa425788c745f646d07d73799f741f037dec5 the first if-statement is true and the second if-statement is verified. Since not much is happening I decided to check the command myself. 

Running `uname -a` results in: `Linux **hostname** 4.4.127-mainline-rev1 #1 SMP Sun Apr 8 10:38:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` Since you are `grep`ing for Ubuntu in https://github.com/mailcow/mailcow-dockerized/commit/7e2aa425788c745f646d07d73799f741f037dec5#diff-25e6ad8ebc5d26ba06d2bcb0b220149cR16 I think the fact that I am missing Ubuntu in my output is the second issue I face. 

Expected behavior:

Since I am still running kernel v4.4 (even though I updated) I expect to receive the output from lines 17-18 https://github.com/mailcow/mailcow-dockerized/commit/7e2aa425788c745f646d07d73799f741f037dec5#diff-25e6ad8ebc5d26ba06d2bcb0b220149cR17-R18

But since my `uname -a` results in an output not containing the keyword `Ubuntu` the update script exits without raising any errors. 

Steps needed to fix the sub issues:
1. Get the installed kernel to be recognized as default
2. Workaround the missing `Ubuntu` keyword

And finally update. 

Could anyone help me out?

Further information:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 16.04.6 LTS (Xenial Xerus) |
| Is Apparmor, SELinux or similar active? | - |
| Virtualization technlogy (KVM, VMware, Xen, etc) | - |
| Server/VM specifications (Memory, CPU Cores) | 16GB/ 6 cores |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | - |

**Comment by MElhagaly** [comment]
@andryyy is it fine to use kernel 4.19 instead of linux-generic-hwe-16.04‘ 4.15?

Or will I still face issues?

**Comment by andryyy** [comment]
Hi, sorry, I missed this. Yes, should be fine.

What we cannot do: check why Ubuntu does not work Kernel xy. You may want to ask that in the Telegram channel. :)

I added a warning for 4.4

**Comment by andryyy** [comment]
Feel free to report back if it worked fine. :)

**Comment by MElhagaly** [comment]
@andryyy 

I have located the reason why I wasn't able to update. Now I have version 4.19 running but unfortunately dockers breaks because kernel 4.19 doesn't support the `aufs` filesystem out of the box. I have now reverted back to 4.4 until I can get confirmation that there are no problems with running mailcow containers/images using `OverlayFS`

Can you confirm that I can safely upgrade? :) 

P.S. I added the Telegram channel in the meanwhile.
