### ISSUE TITLE
IPv6 Default route gets removed during docker-compose up

### ISSUE THREAD

**Issue by Takios** [mailcow/mailcow-dockerized#3213]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Hello,
I'm moving my mailcow instance to another VPS but am facing an issue regarding IPv6. When I start mailcow using docker-compose, the IPv6 default route gets removed, leading to losing connectivity over IPv6. This is happening the very first time I start mailcow and every time after. The issue happens even if `enable_ipv6` is set to `false`.

My network interfaces (IPv4 is NATed while IPv6 is a global IP):
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:57:93:c3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.135/24 brd 192.168.100.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe57:93c3/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:a8:af:67 brd ff:ff:ff:ff:ff:ff
    inet6 2a01:4f8:162:61a4::18e/64 scope global noprefixroute dynamic 
       valid_lft 165sec preferred_lft 165sec
    inet6 fe80::5054:ff:fea8:af67/64 scope link 
       valid_lft forever preferred_lft forever
```
`ip -6 r` before `docker-compose up -d`:

```
2a01:4f8:162:61a4::/64 dev eth1 proto kernel metric 256 expires 3575sec pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
default via fe80::249e:a6ff:fefe:901a dev eth1 proto ra metric 1024 expires 1775sec hoplimit 64 pref medium
```

`ip -6 r` after `docker-compose up -d`:
```
2a01:4f8:162:61a4::/64 dev eth1 proto kernel metric 256 expires 3206sec pref medium
fd4d:6169:6c63:6f77::/64 dev br-mailcow proto kernel metric 256 pref medium
fd4d:6169:6c63:6f77::/64 dev br-mailcow metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
fe80::/64 dev br-mailcow proto kernel metric 256 pref medium
fe80::/64 dev vethb4f00d7 proto kernel metric 256 pref medium
fe80::/64 dev vetheab9e0b proto kernel metric 256 pref medium
fe80::/64 dev vethad62658 proto kernel metric 256 pref medium
fe80::/64 dev vethfa9e9cd proto kernel metric 256 pref medium
fe80::/64 dev veth91c2bdd proto kernel metric 256 pref medium
fe80::/64 dev veth43e4b09 proto kernel metric 256 pref medium
fe80::/64 dev veth436e1bc proto kernel metric 256 pref medium
fe80::/64 dev veth9f5f086 proto kernel metric 256 pref medium
fe80::/64 dev veth599f82e proto kernel metric 256 pref medium
fe80::/64 dev veth9fb2dde proto kernel metric 256 pref medium
fe80::/64 dev vethff02cf9 proto kernel metric 256 pref medium
fe80::/64 dev veth115fe06 proto kernel metric 256 pref medium
fe80::/64 dev veth0af6c5a proto kernel metric 256 pref medium
fe80::/64 dev veth2fd21e1 proto kernel metric 256 pref medium
fe80::/64 dev vetheae1fa6 proto kernel metric 256 pref medium
fe80::/64 dev vethcc0b8bb proto kernel metric 256 pref medium
```

This issue is not happening on my old VPS. I see two differences that might have something do with it: The old VPS has a global IPv4 instead of being NATed and both the IPv4 and IPv6 address are on eth0 instead of being split to eth0 and eth1.

After adding the route manually, I can reach the nginx server, but it's only delivering a 502 "Please do not stop the stack, while we are initializing the database or do other preparations." Checking the logs, I see these two messages being logged continuously:

```
rspamd-mailcow_1     | Waiting for PHP on port 9001...
sogo-mailcow_1       | Waiting for schema update...
```

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. `docker-compose up -d`

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | openSUSE Leap 15.1 |
| Is Apparmor, SELinux or similar active? | Apparmor is active |
| Virtualization technlogy (KVM, VMware, Xen, etc) | The VPS is a qemu-kvm guest. |
| Server/VM specifications (Memory, CPU Cores) | 4GB RAM, 2 CPU cores |
| Docker Version (`docker version`) | Docker version 19.03.1, build 74b1e89e8ac6 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.17.0, build unknown |
| Reverse proxy (custom solution) | No |

**Comment by christianbur** [comment]
Based on the IP (2a01:4f8:162:61a4::/64) I can see that your provider is Hetzner. I also had the problem with Hetzner for a long time. It has nothing to do with Mailcow, only with the definition of the IPv6 address/gateway of the server.  
What exactly I changed in /etc/netplan/01-netcfg.yaml or /etc/network/interfaces I don't know anymore. 

https://wiki.hetzner.de/index.php/Netzkonfiguration_Debian


my netplan config
```
# cat /etc/netplan/01-netcfg.yaml 
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: no
      dhcp6: no        
      addresses: [185.163.x.x/22, "2a03:4000:x:x::1/64"]
      gateway4: 185.163.x.1
      gateway6: fe80::1
      nameservers:
        addresses: [x.x.x.53, 1.1.1.1, "2606:4700:4700::1111", 1.0.0.1, "2606:4700:4700::1001"]
```

**Comment by Takios** [comment]
I have a bare metal server at Hetzner and wanted to put mailcow in a virtual machine running on it. I have two libvirt networks defined, one NATed for IPv4 (because I only have one IPv4 address, but multiple VMs running on this host) and one Forwarded for IPv6 (this uses the /64 IPv6 network I've got from Hetzner). Attaching these two to a virtual machine leads to having two interfaces in the virtual machine. Putting both IPs on one interface obviously doesn't work because in libvirt, one interface is only for either IPv4 or IPv6, not both.
IMHO mailcow should be able to handle this situation. But then it might also be that either docker or docker-compose is the culprit here. Sadly, I am not really well versed in docker things, so I cannot tell.

**Comment by andryyy** [comment]
Hm, it shouldn't be s problem to habe both on one Interface.
