### ISSUE TITLE
zen.spamhaus.org timeout

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3215]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**:

Two errors related to zen.spamhaus.org are thrown in the Postfix logs.

**Reproduction of said bug**:

1. I go to https://URL/debug
2. And then to Logs > Postfix
3. See these happens very often

**System information**

Here is the full log:
```
16/12/2019, 19:04:08	warning	warning: dnsblog_query: lookup error for DNS query 210.218.234.185.zen.spamhaus.org: Host or domain name not found. Name service error for name=210.218.234.185.zen.spamhaus.org type=A: Host not found, try again
16/12/2019, 19:04:07	warning	warning: dnsblog reply timeout 10s for zen.spamhaus.org
```

**Comment by dariusateik** [comment]
I have the same problem and cant find the answer 
 continues in postfix log:
 warning: dnsblog_query: lookup error for DNS query .........zen.spamhaus.org: Host or domain name not 
 found. Name service error for name=........zen.spamhaus.org type=A: Host not found, try again

**Comment by andryyy** [comment]
Can happen when you hit their ratelimit. Are you using an external DNS or do you have a busy mail system?

**Comment by ghost** [comment]
No external DNS here, but yes, busy mail system.

**Comment by dariusateik** [comment]
> Can happen when you hit their ratelimit. Are you using an external DNS or do you have a busy mail system?
my system - testing only, not real working mail server; no external dns; no touch ratelimit;

**Comment by andryyy** [comment]
Does your DNS work at all?

**Comment by dariusateik** [comment]
> Does your DNS work at all?
yes, work.  I have tried flush iptables; ip6tables; nat ; docker-compose down; up again; nothing helps; 
I found one old post with the tip; now I have tried to add to file unbound.conf
forward-zone:
  name: "zen.spamhaus.org."
  forward-addr: 8.8.8.8
  forward-addr: 8.8.4.4
as it is not busy working no to many request, so I will wait for the results and will update if it helped

**Comment by andryyy** [comment]
No, why would you do that? Do not use a public resolver! 

Do not flush iptables without restarting Docker. Do not use firewalld or ufw.

Test with `docker-compose exec acme-mailcow dig google.com @unbound`.

The RBLs are useless with a public resolver.

This is also not a general issue, cannot confirm on any server, that does not have a subscription. You can try the Telegram channel.

**Comment by dariusateik** [comment]
> Telegram channel.

I am not using firewald / no ufw; For sure I flushed iptables after down mailcow; after docker service stop;
docker-compose exec acme-mailcow dig google.com @unbound
; <<>> DiG 9.14.7 <<>> google.com @unbound
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6304
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		300	IN	A	172.217.22.14

;; Query time: 31 msec
;; SERVER: 172.22.1.254#53(172.22.1.254)
;; WHEN: Fri Dec 20 16:16:13 EET 2019
;; MSG SIZE  rcvd: 55
