### ISSUE TITLE
Solr logs directory is not writable bootloop

### ISSUE THREAD

**Issue by xdarkfirestorm** [mailcow/mailcow-dockerized#3216]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Updating mailcow/solr from version 1.6 to 1.7 led to an infinite boot loop printing "ERROR: Logs directory /opt/solr/server/logs is not writable. Exiting".

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. In docker-compose file set version of solr to 1.7
2. docker-compose up -d
3. Container is in state restarting printing error again and again

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu Server 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Hyper-V |
| Server/VM specifications (Memory, CPU Cores) | Memory dynamic (atm 5GB), Single core |
| Docker Version (`docker version`) | 18.09.7 build:2d0083d |
| Docker-Compose Version (`docker-compose version`) | 1.25.0 build:0a186604 |
| Reverse proxy (custom solution) | Traefik |

**Comment by andryyy** [comment]
Hm, we don't touch that directory or mount it.

Can you please post full logs? It is always useful to see when things happen.

What does `docker-compose exec solr-mailcow ls -la /opt/solr/server/logs` return?

**Comment by xdarkfirestorm** [comment]
Cannot exec anything as the solr container is restarting over and over

**Comment by andryyy** [comment]
You need to wipe the Solr volume then. I cannot do more debugging without remote hands I'm afraid. :(

**Comment by andryyy** [comment]
But it's useless anyway. This directory is not mounted. It is always newly created. Hm.

**Comment by xdarkfirestorm** [comment]
I thought this may be a known issue with 1.7 since 1.6 is working. Maybe you have an idea how to find out what's wrong. Let me know. 

I'll send additional info when i moved the additional stuff into an override file so we can find out if theres something wrong with my volumes or bind-mounts.

**Comment by andryyy** [comment]
I have absolutly no free time on my hands, I'm sorry. I tried to replicate it in a hurry, but couldn't.

**Comment by andryyy** [comment]
If **anybody reading this** could please try to replicate, that would be nice. We need all logs.
