### ISSUE TITLE
ActiveSync repeated notifications (Android)

### ISSUE THREAD

**Issue by SenorLAN** [mailcow/mailcow-dockerized#3217]
I have an android device, running the gmail client that connects to two email accounts on my MC server. 
I will receive notifications of new mail in notifications. I then acknowledge them in notifications (but do not "read" the mail). At some point later my phone will again notify me of a number of unread messages that came in, sometimes these are messages that are up to a week old. 
I just recently migrated from a Zimbra setup running ActiveSync and everything worked as expected on this same device. 
I am not sure what is causing this event to trigger and show me the same unread mail time and time again as if it is new, but I am willing to do any troubleshooting/debugging. 
I am running Android 8 and the Gmail client via an "Exchange" account.no luck.

**Comment by andryyy** [comment]
You could habe started with posting any information. Logs. System. :)

Check if a sync job is active. It might be pushing old mail.

**Comment by SenorLAN** [comment]
Solid point @andryyy 
Here are some recent SOGo logs, with domains replaced for privacy. 
https://pastebin.com/tgZ3hQeg

OS is Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-50-generic x86_64)
I believe I am running the Nov 30 update which was a recent update before which the problem was also occurring.  Here are versions.

mailcow/clamd       1.34                 c3192b05ad91        3 days ago          214MB
mariadb             10.3                 8aece987d521        4 days ago          343MB
mailcow/sogo        1.65                 0b960e168060        10 days ago         478MB
mailcow/solr        1.7                  e264ea01b3a9        11 days ago         620MB
mailcow/dovecot     1.104                48cb728e1f08        11 days ago         402MB
mailcow/watchdog    1.65                 d8a3aa1fa5ec        12 days ago         103MB
robbertkl/ipv6nat   latest               f46f4d37caac        13 days ago         21.5MB
mailcow/phpfpm      1.55                 e8583b4a5767        2 weeks ago         336MB
mailcow/unbound     1.10                 f7664193951a        2 weeks ago         20.8MB
mailcow/postfix     1.44                 c36e57487bb7        2 weeks ago         269MB
mailcow/rspamd      1.56                 1dd6d1e8d6e3        3 weeks ago         159MB
solr                7.7-slim             2192e0c41d19        3 weeks ago         613MB
debian              stretch-slim         2b343cb3b772        3 weeks ago         55.3MB
debian              buster-slim          2dbffcb4f093        3 weeks ago         69.2MB
php                 7.3-fpm-alpine3.10   3fc70c6602c0        3 weeks ago         76.7MB
redis               5-alpine             a49ff3e0d85f        3 weeks ago         29.3MB
nginx               mainline-alpine      a624d888d69f        3 weeks ago         21.5MB
mailcow/netfilter   1.31                 6f60cb57e77b        5 weeks ago         79.2MB
memcached           alpine               319607c5f2b0        5 weeks ago         9.08MB
mailcow/dockerapi   1.36                 fa0346bf1a94        5 weeks ago         74.3MB
mailcow/olefy       1.2                  aef37faae9cf        6 weeks ago         86.2MB
mailcow/acme        1.63                 7e442b101608        6 weeks ago         113MB
alpine              3.10                 965ea09ff2eb        8 weeks ago         5.55MB

**Comment by SenorLAN** [comment]
How do I check for an active sync job and kill it? I see as a user I have a button to reset ActiveSync profile, but no access to do so and I do not see any admin setting for this. 

![image](https://user-images.githubusercontent.com/8877311/71024229-4d87b780-20b9-11ea-897a-1308972a6ffb.png)
