### ISSUE TITLE
ClamAV virus definitions can't update?

### ISSUE THREAD

**Issue by mjhd** [mailcow/mailcow-dockerized#3218]
Not sure if this is a Mailcow or CLamAV container bug, or if I'm misunderstanding, but I can't find any information about how to keep the ClamAV container's virus definitions up to date...

I tried freshclam in the container but got this message:

```
Tue Dec 17 23:33:27 2019 -> ClamAV update process started at Tue Dec 17 23:33:27 2019
Tue Dec 17 23:33:27 2019 -> !Can't create temporary directory /var/lib/clamav/clamav-c26e827a5e0268a7eb58225c2d909d41.tmp
Tue Dec 17 23:33:27 2019 -> Hint: The database directory must be writable for UID 700 or GID 700
```

Obviously I could change the directory permissions, but I feel like I shouldn't without understanding what's going on...

Also, I found no cron's that appear to deal with this, does Mailcow keep these definitions up to date automatically or is this meant to be done through the web UI or something?

Thanks in advance - MJHd

**Comment by andryyy** [comment]
Please post more information. Deleting the issue template does not help getting a response. :(

Check your clamd-mailcow image version, please, because =>

```
drwxr-xr-x 2 clamav clamav      4096 Dec 19 07:14 .
# and in the script
chown clamav:clamav -R /var/lib/clamav /run/clamav
```

The signatures are updated, yes. No cron, but a bash script with looping sub scripts.
