### ISSUE TITLE
After updating mail is not going through rspamd

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#322]
Yesterday evening, I updated mailcow using the documentation (Method 1) and while doing so, there were no errors whatsoever.
But today I noticed that none of the mails had the Spamfilter-header in it, and that I received a massive amount of spam. So I looked in the Rspamd webinterface and the status told me "0 scanned, 0 clean".

In the "History" tab, there are tons of messages like this:
`cannot get FANNS list from redis: timeout while connecting the server`
and
`connection with http server terminated incorrectly: IO write error: No route to host`.
and
`rspamd_monitored_propagate_error: timeout on resolving public.sarbl.org, disable object`

What should I do now?

Thank you so much,
mindsolve

**Comment by andryyy** [comment]
These errors don't stop Rspamd from working. 

The fann worker will exist with the next release (we just don't use that module right now).

The second error happens with internal IPv6 connections, the maps are read nevertheless.

The third timeout may be a rate limit you hit with sarbl.org.

Can you check the Postfix container, please?

**Comment by mindsolve** [comment]
@andryyy  
The Postfix container is running and accepting mails.
See log here: https://pastebin.com/P16FDWZG
This is the startup and a successfully delivered mail. (Where I included as much "spammy" words as possible to see any reaction from rspamd)
This is the log from rspamd (every message with "fann" is filtered out via grep): https://pastebin.com/WiXfDQv8
I do not believe that 

> may be a rate limit you hit with sarbl.org.

is true, as this seems to apply to all services...

**Comment by andryyy** [comment]
Are the containers up to date? (docker-compose pull)

Any errors when updating the repo? Like merge conflicts?

**Comment by andryyy** [comment]
This is also bad: `connect to dovecot[fd4d:6169:6c63:6f77::8]:24: No route to host`

Looks like something overwrites your iptables/ip6tables settings. firewalld, ufw etc.? Can you try and restart the Docker service? But don't restart any fw service afterwards.

**Comment by stevesbrain** [comment]
For what it's worth, I'm also at current master + current images, and I am not having this issue @mindsolve, so I would expect this is to do with a local config or firewall/iptables issue as per above

**Comment by mindsolve** [comment]
Thank you @stevesbrain and @andryyy, this seems to have been a problem with my firewall, fireHOL.

Since this is not a problem of mailcow alone, I am closing this here.
