### ISSUE TITLE
[FR] Quaratine-Manager

### ISSUE THREAD

**Issue by AndyX90** [mailcow/mailcow-dockerized#3220]
**Is your feature request related to a problem? Please describe.**
If i host a mailsystem with multiple domains and quarantine functionality and want a user to manage the quarantine for one or more domains, then i have to create an additional admin user.
But these users are not always able to distinguish between critical settings and quarantine management.

**Describe the solution you'd like**
I would like to have the possibility to define a quarantine-manager for one or more domains.
This person should only be able to see the mailquarantine for his, previously selected domains.

**Comment by andryyy** [comment]
Hm, you can remove a lot of rights from a domain administrator account via ACL. :)

**Comment by AndyX90** [comment]
You're right, thanks! But maybe it would be possible in the future to make a dedicated Quarantine-View if the user only has the quarantine right.
