### ISSUE TITLE
SOGo UI: change default filter criterion

### ISSUE THREAD

**Issue by ThomDietrich** [mailcow/mailcow-dockerized#3221]
Hey guys!
Nice-to-have feature request to solve a usability issue.

It would be nice if the SOGo search function would search by "Subject or Sender" instead of only "Subject" by default.

A ticket with a comment with a solution which I did not test does exist: https://sogo.nu/bugs/view.php?id=4555 Is this request something you would consider? Who should be mentioned with code ownership for SOGo?

I'm not sure why "subject only" would even be the default as this is clearly not what a typical user would expect. If any I'd suspect "sender only" to be the more favorable among the two individual ones - with the combination being the intuitive one.

**Comment by andryyy** [comment]
Hi :) We can try to implement that.

**Comment by dragoangel** [comment]
Hi @ThomDietrich after SOGo Docker Image will be updated the issue will solved and changed to subject_or_from.

**Comment by ThomDietrich** [comment]
You've improved this upstream. Big thumb up for the effort! Thanks ;)
