### ISSUE TITLE
ACME: Wrong certificate for WebGUI

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#3222]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

A few days before I added an IPv6 address to my VPS. On my reverse proxy I forgot to enable that the Webserver listens also on IPv6. I think the acme mail container tried to renew the certificate and got no HTTP Verification. So he set the certificate of a ADDITIONAL_SAN as the current SSL. So I fixed the problem with the reverse proxy so he's listening also for IPv6 now. After that I restarted the complete mailcow mailserver. The certificate for IMAP is working again now.

My problem: 
When I try to access the mailcow Web UI I get a SSL error. The SSL certificate which the Web UI tries to use is from a domain which is set in ADDITIONAL_SAN. So I looked at the acme logs:

```
mv: can't rename '/var/lib/acme/cloud.mydomain': No such file or directory
Thu Dec 19 21:43:12 CET 2019 - Found orphaned certificate: webmail.mydomain - archiving it at /var/lib/acme/backups/webmail.mydomain/
mv: can't rename '/var/lib/acme/webmail.mydomain': No such file or directory
Restarting 7a7c22ef9d3b06cbc8123519a1f65edc99c483b1f46d25b038dd773f3b226b71...
command completed successfully
Restarting 6ca88e0f7b6efbedbd640029d97731df293c155621776bcb674317a09c93b399...
command completed successfully
Restarting aa75bdad8c3dbd58c3fb61c101eee4b352c46bba595a6398b4feb864e7cfdcae...
command completed successfully
Thu Dec 19 21:43:20 CET 2019 - Certificates successfully requested and renewed where required, sleeping one day
```

I am also running nextcloud within the mailcow mailserver. This certificate is set right. Why are the errors appearing?
What is the acme container trying? I also looked at the directory at /var/lib/acme and the above mentioned directories are existing. This is a little bit confusing.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Proxmox |
| Server/VM specifications (Memory, CPU Cores) | 32GB Ram 8 cores |
| Docker Version (`docker version`) | 18.09.7 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | Not a custom solution. It's the same as in the documentation. |

**Comment by andryyy** [comment]
Hi :) You did remove the most important part of the acme-mailcow logs: the part, where it logs why or it couldn't verify a name.

If you use a reverse proxy and you are sure, the challenge will be solved, you can set stuff like SKIP_IP_CHECK=y and (more important here) SKIP_HTTP_VERIFICATION=y in mailcow.conf.

Run up -d afterwards.

**Comment by mkapra** [comment]
@andryyy The HTTP verifications are not failing anymore. I only mentioned it so that you know what I did before.
The only problem is, that the Web UI uses the wrong certificate.

**Comment by andryyy** [comment]
I don't know wether the reverse proxy does serve the wrong certificate or mailcow does. Did you copy the certificate to your reverse proxy? If you use ENABLE_SNI, did you copy the correct cert?

**Comment by mkapra** [comment]
@andryyy  My Reverse Proxy serves this certificate: `/opt/mailcow-dockerized/data/assets/ssl/cert.pem`

**Comment by mkapra** [comment]
I don't know what `ENABLE_SNI` so I don't have it enabled.

**Comment by mkapra** [comment]
Anyone has an idea what is going wrong here? It seems that the container tries to move the new certificates to the directories but some dirs are missing. The problem is that they are not missing in the acme Container. So where tries the acme container also to put the certificates?

The biggest problem: Every time the acme container tries to refresh our smartphones complain about a wrong server identity.

**Comment by andryyy** [comment]
I cannot guess what your acme container logs exactly, when it tries to obtain a certificate.

It seems to fail to validate a/multiple name/s and drops these names from the SAN  

The failing mv command is most likely a cosmetic bug in the script. @mhofer? :)

**Comment by mkapra** [comment]
I tried another thing. I copied the certificate of the mailcow domain and gave it nginx to serve it. the WebUI is working now.
So the only problem is the warning about the wrong server identity on smartphones. This error occurs when the acme container is renewing the certificates.

**Comment by andryyy** [comment]
Then you are doing something wrong. If you **copied** the certificate mailcow is supposed to use (from `data/assets/ssl` to your RP), then it is obviously the correct one. You **always** need to copy that certificate OR point Nginx to this location for the certificate, if you use a reverse proxy. Your reverse proxy needs to terminate SSL. Where would the certificate come from if you didn't copy it? :) I prefer to point ssl_certificate to `/opt/mailcow-dockerized/data/assets/ssl/cert.pem` (obviously same with the key file), if it's the same server and if mailcow should be handling TLS.

mailcow uses this exact same certificate for all services (smtp, imap, etc.). So the certificate in `data/assets/ssl` needs to be the correct one. If you request a certificate externally (which I don't think you do) you _would_ need to copy it to mailcow.

Please use the TG channel for support questions. Please post logs if you are asked to, don't cut lines you think are not important. I still don't know why the request failed. I don't even know your reverse proxy config.  I cannot help here, sorry.

**Comment by mhofer117** [comment]
Hey @andryyy I think you pinged the wrong mhofer here :)
I just noticed a similar problem and created a PR with the fix.

**Comment by mkapra** [comment]
@andryyy  Sorry for replying so late but I was really busy for the last weeks.

> Then you are doing something wrong.

This is only a workaround to get it working again.

**Comment by mhofer117** [comment]
Can you update and check if your problem resolves?

**Comment by mkapra** [comment]
Seems to work again. Thank you!
