### ISSUE TITLE
iOS Configuration File Download from Web UI

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#3224]
I am wondering why I first need to go to the mailcow configuration guide to download the configuration file for the mail account on IOS devices. 

<img width="1138" alt="Screenshot 2019-12-20 at 20 03 12" src="https://user-images.githubusercontent.com/34742358/71284830-f6593f80-2363-11ea-96b3-db39478c9b7c.png">

Firstly It is more difficult to download the profile. Also it would be better to send less data to other server, in this case the mailcow documentation server. Also a configuration over `mailcow.conf` would then be possible. With configuration options I mean that one can set another domain for IMAP and SMTP (e.g. imap.mydomain.xy, smtp.mydomain.xy).

I think this should be not difficult to implement? I could try to implement it :)
What are your thoughts about this idea?

**Comment by ntimo** [comment]
That is actually possible. Is your mailcow up to date? 

![7E82D8C2-3BED-47FB-B245-B9485A9122E6](https://user-images.githubusercontent.com/6145026/71287108-b72ced80-2367-11ea-96a7-00ec812a6ab7.jpeg)

**Comment by mkapra** [comment]
Is this feature new? I did not see that option. After updating my mailcow I also have these options now.

**Comment by mkuron** [comment]
> Also it would be better to send less data to other server

That data is not actually sent to the other server. It is contained in a URL anchor, which is handed over on the client side and only accessible to JavaScript.
