### ISSUE TITLE
Automatic Backup Cleanup

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#3225]
when I use crontab for automatic backups described here: #896 I have the problem to hat old backups stayes at they are and would over time max out disk space.

would be nice to have a flag "-delete n" to delete all backups expected the last "n" backups.

**Comment by andryyy** [comment]
--delete-days

https://github.com/mailcow/mailcow-dockerized-docs/blob/master/docs/b_n_r_backup.md
