### ISSUE TITLE
Only allow specific sender domains

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#3226]
I would like to have the possibility to block incoming emails from all domains except those i whitelist. Is this already possible? If not, would you consider adding this feature? For my case, it would already be enough, if i could modify a configuration file or something, to achieve this.

The reason for this is, that i only want to allow emails from internal domains/hosts. All others should be discarded.

EDIT:

I forgot to mention, that i would need this for aliases.

EDIT:

Would that work?

![image](https://user-images.githubusercontent.com/81188/71299857-451cce80-2390-11ea-9cb5-9ae1e3c3aed6.png)

EDIT:

Doesn't seem so. All mails are being rejected: `smtp; 554 5.7.1 Matched map: GLOBAL_MIME_FROM_BL`

![image](https://user-images.githubusercontent.com/81188/71300263-47345c80-2393-11ea-9556-5c9278c474fe.png)

**Comment by andryyy** [comment]
b822818c

PRs for presets are welcome.

**Comment by SoftCreatR** [comment]
@andryyy That might be a neat solution, but either it doesn't work or i'm just too stupid. Let's assume, that i've configured a domain in Mailcow `foo.tld` and i want to accept incoming mails from `bar.tld` and `baz.bar.tld`. My configuration would look like this:

```
priority = 10;
rcpt = "*@foo.tld";
from = "/^((?!.*@(baz\.)?bar\.tld).)*$/";
apply "default" {
  MAILCOW_BLACK = 9999.0;
}
symbols [
  "MAILCOW_BLACK"
]
```

The regex is a negative lookahead, so it should match everything but `*@bar.tld` nor `*@baz.bar.tld`. Is this configured properly for my case?

**Comment by andryyy** [comment]
Have you checked your regex against a tester?

It doesn't look like the preset, iirc.

**Comment by andryyy** [comment]
```
from = "/^((?!(.*@allowed-domain\.tld|.*@other-allowed-domain\.tld)).)*$/";
```

**Comment by SoftCreatR** [comment]
It's a valid regex and I've tested it against regex101

**Comment by andryyy** [comment]
It is valid regex, but does it match what you need? ".*" is also valid regex, but will not be useful.

I tested your regex and it does not seem to match what you need. Just use https://regex101.com/ for example. 

And: Why don't you just use the preset I added for you?

**Comment by SoftCreatR** [comment]
That IS the preset. The only difference is the optional subdomain.

**Comment by andryyy** [comment]
It isn't. I posted the correct regex above.

**Comment by SoftCreatR** [comment]
I tried your regex (even if i'm confident, that mine should have worked as expected). Unfortunately, it doesn't change anything. Just sent a mail from a Yahoo account and it has been successfully delivered.

**Comment by andryyy** [comment]
t may take a little while (up to 3 minutes) and - very important - an updated mailcow. Some map updates didn't work as expected before.

**Comment by SoftCreatR** [comment]
> Why don't you just check it?

I did:

![image](https://user-images.githubusercontent.com/81188/71392809-c0d58000-2609-11ea-9ded-bb8b171641b4.png)

And the result your screen is correct, because your test string is "incorrect" (missing the local part and the @).

Nevermind, i'll perform an update and see, if that works.

**Comment by andryyy** [comment]
Your regex did indeed work for the domain and subdomain. My example says multiple allowed hosts. I thought you wanted to match baz itself. 

If it doesn't work, you need to debug the settings module in Rspamd and see if it updates the settings cache. I tested it last evening, looked good.

Make sure you are using an updated mailcow and Nginx logs a 200 http code, when the map is accessed by Rspamd **after a change of that map**. It will log 304 as long as its content did not change. Doesn't work? Update mailcow. Updated mailcow? Post logs.

**Comment by SoftCreatR** [comment]
Mailcow is up to date. Just removed the old map and created a new one. Waited 5 minutes and tried to send another mail. Still the same result:

```
DMARC_POLICY_ALLOW (-0.5) [yahoo.de,reject]
R_PARTS_DIFFER (0.5) [100.0%]
R_SPF_ALLOW (-0.2) [+ptr:yahoo.com]
R_DKIM_ALLOW (-0.2) [yahoo.de:s=s2048]
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
MX_GOOD (-0.01) [cached: mx-eu.mail.am0.yahoodns.net]
SPAMHAUS_FAIL (0) [77.238.177.147:query timed out]
ARC_SIGNED (0) [i=1]
DKIM_TRACE (0) [yahoo.de:+]
RCPT_MAILCOW_DOMAIN (0) [foo.bar]
RCVD_IN_DNSWL_NONE (0) [77.238.177.147:from]
FREEMAIL_ENVFROM (0) [yahoo.de]
FREEMAIL_FROM (0) [yahoo.de]
MIME_TRACE (0) [0:+,1:+,2:~]
TO_DN_EQ_ADDR_ALL (0)
RCVD_TLS_LAST (0)
RCVD_COUNT_TWO (0) [2]
ARC_NA (0)
FROM_EQ_ENVFROM (0)
DBL_FAIL (0) [yahoo.de:query timed out]
FROM_HAS_DN (0)
RCPT_COUNT_ONE (0) [1]
RWL_MAILSPIKE_POSSIBLE (0) [77.238.177.147:from]
TO_MATCH_ENVRCPT_ALL (0)
ASN (0) [asn:34010, ipnet:77.238.176.0/22, country:GB]
```

> Nginx logs a 200 http code, when the map is accessed by Rspamd after a change of that map. It will log 304 as long as its content did not change.

Where? Just checked `docker logs mailcowdockerized_nginx-mailcow_1` but i'm not sure, what to look for. All it accesses is `forwardinghosts.php` and `settings.php`

> debug the settings module in Rspamd and see if it updates the settings cache

Are there any instructions how to do so?

**Comment by SoftCreatR** [comment]
After updating the map:

```
nginx-mailcow_1      | xxx - - [24/Dec/2019:05:44:11 +0100] "HEAD /settings.php HTTP/1.1" 200 0 "-" "rspamd-2.2"
nginx-mailcow_1      | xxx:11 - - [24/Dec/2019:05:44:11 +0100] "GET /settings.php HTTP/1.1" 200 736 "-" "rspamd-2.2"
nginx-mailcow_1      | xxx::11 - - [24/Dec/2019:05:44:32 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "rspamd-2.2"
nginx-mailcow_1      | xxx - - [24/Dec/2019:05:44:32 +0100] "GET /forwardinghosts.php HTTP/1.1" 200 171 "-" "rspamd-2.2"
nginx-mailcow_1      | xxx::11 - - [24/Dec/2019:05:44:53 +0100] "HEAD /settings.php HTTP/1.1" 304 0 "-" "rspamd-2.2"
```

**Comment by andryyy** [comment]
I checked with my regex just now. It auto detected the change and applied my rule correctly. 

![image](https://user-images.githubusercontent.com/2972950/71394178-a521a800-2610-11ea-9302-e4adadb3fda4.jpg)

The accepted mail came from debinux, the rejected mail from Servercow. 

![image](https://user-images.githubusercontent.com/2972950/71394192-b8347800-2610-11ea-9835-f3d301618364.jpg)

Check the Rspamd docs or join the Telegram channel. If it is not a commercially used system (as in you sell it), I can check it on the server.

**Comment by andryyy** [comment]
The Nginx map looks fine. It detected the change and later kept it in the cache (not-modified header).

**Comment by SoftCreatR** [comment]
Well, we are getting closer but i've noticed two things:

1. The main problem here is, that i've set `*@domain.tld` as rcpt in the map. That doesn't seem to work. If i enter a full mail address, it works (finally, yay!).

2. When sending from a forged address (e.g. when using Amazon SES), the sender address wont be recognized (i'm not sure, but i guess it detects eu-west-1.amazonses.com instead).

**Comment by andryyy** [comment]
Just use regex for the rcpt or "@domain" without *.

Match an authenticated user as "from" or a mime header.

Closing this, not a bug but a support question. Let us keep that in the TG channel or ticket system. :)

Oops. Already closed. Didn't have enough sleep.

**Comment by SoftCreatR** [comment]
I'll soon join you in TG.

Just FYI: 

> Just use regex for the rcpt or "@Domain" without *.

That seems to work, ty.

> Match an authenticated user as "from" or a mime header.

That won't work in my case, because the allowed sender is not registered within the Mailcow instance.

**Comment by konfiv** [comment]
@SoftCreatR
What was your solution than for "Only allow specific sender domains"?
Thanks
