### ISSUE TITLE
Sogo login broken on update

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#323]
Hi, today i decided to preform a update to the current master branch. 

I did it via method 1 after i run docker-compose up -d --remove-orphans it rebuild all the containers which is fine.

After all the containers rebuild and everthing is started everthing worked fine expect Sogo as it dose not accept any login.

All i can find helpful in the log is
<pre>
2017-5-31 14:32:06	notice	<0x0x7f68ba3dcd30[SOGoDAVAuthenticator]> tried wrong password for user 'ryan@.be'!
2017-5-31 14:32:06	notice	[ERROR] <0x0x7f68ba49cb30[SOGoUserManager]> No authentication sources defined - nobody will be able to login. Check your defaults.
</pre>

I did manage to fix by restarting sogo via the web-ui.

I updated 3 Mailcow server today all on stock config and had the same issue on all of them.

**Comment by elvirdz** [comment]
Has you tried after update
`docker-compose restart sogo-mailcow`

**Comment by K2rool** [comment]
I don't any of my server in that state as anymore, as i fixed it via restarting it via the web-ui.

**Comment by andryyy** [comment]
What happens when you restart SOGo via web interface? 
I cannot reproduce the error here.

**Comment by andryyy** [comment]
Hi, I will have a look into it. Thanks.

**Comment by K2rool** [comment]
@andryyy I try to reproduce it my self again but i was unable, your free to close this issue if you can't reproduce it.

Many thanks Ryan.

**Comment by stevesbrain** [comment]
I've updated mine via the standard
```shell
git pull
docker-compose pull
docker-compose down
docker-compose up -d
```

without issue - didn't have to restart anything :)

**Comment by kunago** [comment]
+1 for having to do the sogo restart after update the same way @stevesbrain did it. If not, sogo would not log me in.

**Comment by andryyy** [comment]
I will fix it, it is a race condition when restarting containers. `down` and `up` is the safer way to "restart" the containers.
