### ISSUE TITLE
API: /get/dkim/{domain} Doesn't respect $SHOW_DKIM_PRIV_KEYS  

### ISSUE THREAD

**Issue by cybersholt** [mailcow/mailcow-dockerized#3231]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

While testing out the API I noticed that the private key is transmitted back regardless of $SHOW_DKIM_PRIV_KEYS value. 

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Make an API request to /get/dkim/domain.tld 

**System information**

Amazon Linux AMI 2018.03.0.20190826 x86_64 HVM

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Amazon Linux AMI 2018.03.0.20190826 x86_64 HVM |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc) | NO |
| Server/VM specifications (Memory, CPU Cores) | Amazon EC2 t2 Micro |
| Docker Version (`docker version`) | 18.09.9-ce, 039a7df |
| Docker-Compose Version (`docker-compose version`) | 1.22.0 |
| Reverse proxy (custom solution) | NONE |

docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by andryyy** [comment]
Thanks

**Comment by cybersholt** [comment]
@andryyy no problem, thanks for such a cool project, on an off topic question, what's the best way to contribute to the API docs? I found one on apiary.io that has some of the basics in the but is missing all the DKIM stuff for example.

**Comment by andryyy** [comment]
Thank you! :)

Checkout the official apiary at https://mailcow.docs.apiary.io/#

@ntimo does the API doc work at https://github.com/mailcow/mailcow-apiblueprint - Apiary docs are automatically rebuilt.

The docs can also be found on every installation by browsing to /api (like this => https://mx.mailcow.email/api/ )

André

**Comment by cybersholt** [comment]
@andryyy Thanks a ton! You're a lifesaver, Merry Christmas.

Best,
Sean

**Comment by ntimo** [comment]
@cybersholt Going to add the missing GET route to the API docs in a minute.
