### ISSUE TITLE
googlemail.de / gmail.de Connection timed out

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3238]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

There are multiple email items in queue (Queue Manager) to gmail.de and googlemail.de email addresses that failed to send with a connection time out.
One thing that stands out is that all these are IPv6 addresses:
````
gmail.de[2a00:1450:4001:816::2005]:25: Connection timed out)
googlemail.de (connect to googlemail.de[72.52.10.14]:25: Connection timed out)
````

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
Send an email to either googlemail.de or gmail.de.
Use a docker-mailcow server with public IPv6 address, e.g. host on Hetzner Cloud.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS |
| Is Apparmor, SELinux or similar active? | Should be on by default on Ubuntu |
| Virtualization technlogy (KVM, VMware, Xen, etc) | Cloud hoster uses KVM (Hetzner) |
| Server/VM specifications (Memory, CPU Cores) | 8 GB, 2 vCPU |
| Docker Version (`docker version`)  | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1, build 4667896b |
| Reverse proxy (custom solution) | None. |

**Comment by Conan179** [comment]
Why 
gmail**.de**
googlemail**.de**
?
gmail and googlemail have .com tld.

**Comment by strarsis** [comment]
@Conan179: Right, gmail.de and googlemail.de both redirect to googlemail.com, hence one can get the illusion that these domains are also working for receiving email, but this is not the case, they just redirect as websites.
