### ISSUE TITLE
Mailbox User Can't Login

### ISSUE THREAD

**Issue by noceboo** [mailcow/mailcow-dockerized#324]
Hi,
I have instantiated the master branch of this repo and set things up accordingly. However, I have encountered some issues. **Could this be a bug or just my technical error?** I'm new to this project and I can't figure things out. I have already rebooted/restarted SOGo and the entire server after adding the new domain and mailbox. Did I miss something? 😄 
Here's what I encountered:
* **mailbox users can't log-in to mailcow UI**
* **autodiscover login doesn't work**
* admins can login to mailcow UI
* mailbox users can login via SOGo

Thanks!!!!!

**Comment by andryyy** [comment]
Hi,
Do you use a password manager in your browser? Can you disable it or use another browser to **create the mailbox**?

**Comment by noceboo** [comment]
Thanks!!! It worked now.
