### ISSUE TITLE
How to switch to SHA512-Crypt

### ISSUE THREAD

**Issue by RickD123** [mailcow/mailcow-dockerized#3241]
Hi,

I have existing users whose password is encrypted using SHA512-CRYPT. How can I change mailcow (dockerized) so that is makes use of SHA512-CRYPT instead of SSHA256?

Thanks.

Kind regards
RickD

**Comment by andryyy** [comment]
Hi,

This is not a ticket system. :) Join the Telegram group, please.

mailcow can read/understand SHA512-CRYPT hashes. It just does not set new passwords with this hashing method.

André
