### ISSUE TITLE
ERROR: manifest for mailcow/watchdog:1.67

### ISSUE THREAD

**Issue by forall** [mailcow/mailcow-dockerized#3243]
Hi,
I try update a mailcow-dockerized but I ger error...

WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Pulling watchdog-mailcow (mailcow/watchdog:1.67)...
ERROR: manifest for mailcow/watchdog:1.67 not found: manifest unknown: manifest unknown

**Comment by andryyy** [comment]
Hi, it is fixed, sorry.

**Comment by forall** [comment]
Thanks for quickly resolve problem :-) :+1:
