### ISSUE TITLE
RSPAMD rejects even though from address is clearly whitelisted

### ISSUE THREAD

**Issue by gtmadev** [mailcow/mailcow-dockerized#3245]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

RSPAMD rejecting emails that are whitelisted

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Whitelist a from address globally and send an email to it. RSPAMD will still reject it.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ x] I do run mailcow on a Synology, QNAP or any other sort of NAS.

![3cU7EsrHwf](https://user-images.githubusercontent.com/30833539/71718300-be6af580-2e55-11ea-88bf-dc303f29e0c2.png)

**Comment by andryyy** [comment]
The global smtp from blacklist is a prefilter action. The score does not matter, when a prefilter symbols returns "reject".

**Comment by gtmadev** [comment]
So.. you're saying that I blacklisted the from address somewhere? I don't recall ever doing that. Is there some way to receive this email?

**Comment by andryyy** [comment]
Yes, check `global_smtp_from_blacklist.map` in mailcow UI /admin -> global filter maps or - alternatively - `data/conf/rspamd/custom/global_smtp_from_blacklist.map`.

**Comment by gtmadev** [comment]
Yeah. I checked those before. But they are all empty. Just a remarked out example. So I don't know why it thinks the sender is blacklisted.

**Comment by andryyy** [comment]
Perhaps there was content a while ago and Rspamd did not catch it. Are you absolutely sure it is empty?

Can you restart Rspamd and test again?

**Comment by gtmadev** [comment]
Yeah, I can restart it. But I can't test it now because now Google is no longer allowing me to re-send the verification email. Which really sucks. Because now I am really stuck. No way to get to the email, and no way to re-send the verification. And even if I could, there's no guarantee that I will be able to receive it. I REALLY REALLY wish Mailcow had a way to retrieve filtered email, or release filtered (rejected) emails. 

Is the email sitting somewhere that I can easily just go get it? Why doesn't the UI have a button that says "override" or "release email", or something to that affect?

**Comment by andryyy** [comment]
You can enable the quaratine by configuring it in /admin

![image](https://user-images.githubusercontent.com/2972950/71727287-0e3bc380-2e3a-11ea-8114-eb0ed9aa3219.png)

Retentions per mailbox and Maximum size in MiB need to be setup.

malicow does not accept and quarantine, it rejects and quarantines. So if a mail is rejected, the sender will not think their mail was delivered. I never liked that conecept, so we changed it... :)

**Comment by gtmadev** [comment]
Okay, I enabled quarantine, set it to 10 retentions, and 50mb limit. I was able to send one more verification email. It got rejected. But... quarantine did not work. It did nothing. No notifications. Not even in the quarantine screen.

This is so frustrating. All I want to do is receive this verification email, and its literally impossible to receive the email. Is there some way to just disable anti-spam. The system is WAY overkill.. removing emails that I actually want and very much need. Why doesn't it just send the email to my SPAM folder like other mail systems do?

Can I get to the email? Is it sitting in a folder or directory somewhere? Is it logged? Is there any way to get to the code that I need???

**Comment by gtmadev** [comment]
I am running the update script to see if that might cause the false blacklisting to go away. I did check the physical blacklist file. It is empty. But I will have to see what happens after the update and all the containers have restarted.

**Comment by gtmadev** [comment]
That did it. Restarting all the containers seems to have fixed the blacklist issue. Still not sure how or why that rule was in there. And I had restarted RSPAMD earlier. But anyway... it is working now. Message delivered this time. Thanks for the assistance.

**Comment by andryyy** [comment]
Quarantine is skipped when a global smtp from (prefilter) reject triggers, forgot that.
