### ISSUE TITLE
502 direkt nach der Installation !

### ISSUE THREAD

**Issue by dennisdaa** [mailcow/mailcow-dockerized#3249]
Moin,

Auf einem Frisch installierten System, mehrmals probiert auch mit Debian 9/10 jedoch erhalte ich nach der Installation, beim Aufruf der Interfaces folgende Meldung:

>  🐄 - we are on our way.
> 
> 502
> 
> Please do not stop the stack, while we are initializing the database or do other preparations.
> 
> What is happening? - Nginx cannot connect to an upstream server.
> This is fine, if mailcow was just installed or updated and can take a few minutes to complete.
> Please check the logs or contact support, if the error persists.
> 
> docker-compose logs --tail=200 php-fpm-mailcow

Die php-fpm-mailcow sagt folgendes:

> php-fpm-mailcow_1    | Uptime: 3  Threads: 8  Questions: 1  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 0.333
> php-fpm-mailcow_1    | MySQL @ eda7537c20a6f0413942c51eba65e0ffb63d579b056a2ad87e4e2ac4888bfedc
> php-fpm-mailcow_1    | SQL upgrade iteration #1
> php-fpm-mailcow_1    | MySQL is up-to-date - debug output:
> php-fpm-mailcow_1    | {"msg":"mysql_upgrade: already upgraded","text":"This installation of MySQL is already upgraded to 10.3.21-MariaDB, use --force if you still need to run mysql_upgrade\n","type":"success"}

Ich kann aktuell keinen Fehler in der Log finden bzw. sehen. Wo könnte man die Sache noch angreifen ? Scheint doch ein generelles Problem zu sein ?

Gruß
Dennis

**Comment by ntimo** [comment]
Hey,
das ganze ist normal wenn du mailcow gerade erst installiert hast. Da die Datenbank initiiert wird. Warte einfach ein paar Minuten und dann wird auch der 502 weg sein.

**Comment by dennisdaa** [comment]
Danke für deine Nachricht ... Jetzt geht es komischerweise ... Hatte zweitweise auch mehrer Stunden damit verbraucht zu warten -.- Danke dir und schönes erst Wochenende !

**Comment by Adorfer** [comment]
sounds like the usual "mailcow with rspamd installed on underpowered vps"
