### ISSUE TITLE
Mailinglist [Howto]

### ISSUE THREAD

**Issue by pgollor** [mailcow/mailcow-dockerized#325]
Is there any plan to integrate a mailinglist in mailcow dockerized?
There was a discussion in the old mailcow repository https://github.com/mailcow/mailcow/issues/305?_pjax=%23js-repo-pjax-container

**Comment by Braintelligence** [comment]
You could achieve close functionality with a SOGo group which doesn't work yet due to LDAP necessity...

**Comment by andryyy** [comment]
Or an alias. Or a redirect rule in sieve. SOGo groups are not needed for it. :)

A mailman implementation may be described as how to. But it's not really part of a "normal" mail server. Or we start writing a mail list service on or own? :P

**Comment by Braintelligence** [comment]
Maybe a script that achieves the same functionality via the routes you described would be enough. 
You'd just need to be able to create and delete such lists.

**Comment by pgollor** [comment]
It would be great to get an howto how to integrate mailman into a running mailcow docker installation.

**Comment by stirch** [comment]
Some correction in Sympa integration manual would be more than enough.

**Comment by Tcharl** [comment]
Even integrating it directly within mailcow

**Comment by alexgleason** [comment]
Hey I'm trying to set up Mailcow with a mailing list for an activist group I manage. It's really important to us that we not rely on Google Groups or services like Facebook, so we're working around it with email. If anyone could create a guide on how to integrate a mailing list with Mailcow Dockerized that would be really helpful to me. I feel a bit stuck and our group isn't able to proceed since there doesn't seem to be a solution right now.

**Comment by stevesbrain** [comment]
@alexgleason Are your members part of your mailcow server, or do they live on their own mail servers?

**Comment by alexgleason** [comment]
@stevesbrain we'll have organizers with accounts on the Mailcow server and mailing lists with hundreds of people for email campaigns (outreach and events). The latter will have emails on a variety of platforms.

**Comment by stevesbrain** [comment]
@alexgleason Although it's not automated, I've had success with "Aliases". I.e. in mailcow admin portal, go to Configuration > Mailboxes > Aliases > Aliases. Create a new alias (list@domain.com for example), and enter all the email addresses you would like to be part of your list in there. Obviously, this is a manual process, so it's not ideal, but you could have them email listrequest@domain.com which would come to you, and then you can enter them. 

That'll probably be the easiest way to go about it anyway :)

**Comment by alexgleason** [comment]
@stevesbrain I'll look into this; thanks! Any clue if I can limit only some people to send to the alias? My only concern is that I don't necessarily want someone outside our organizers emailing the whole list which I why I felt I needed a traditional mailing list in the first place. Thank you for your help.

**Comment by stevesbrain** [comment]
Hmm, unfortunately I don't think so. You could make it a full mailbox, then set up a sieve filter to forward based on "send is X or sender is Y", however, the sieve filter doesn't really have a nice layout for entering multiple email addresses (i.e. if you had 100's of users). Someone else may have a better idea, but unfortunately I don't :( 

I was thinking along the lines of maybe making it a full mailbox, and making it a "if senders is not X or Y then reject", with a second rule for forwarding. But again, we come to the issue of multiple email addresses to forward to :(

**Comment by alexgleason** [comment]
It looks like @royalterra already set up a [wiki page on integrating with Sympa](https://github.com/mailcow/mailcow/wiki/Install-Sympa-with-Mailcow---Ubuntu-14x), it just doesn't take the dockerized version into account. If anyone with a decent knowledge of this and of Docker took a look I'd guess this guide could be adapted.

**Comment by stevesbrain** [comment]
@alexgleason Should be able to follow that guide in the sense that all postfix configs that you have to modify are located under mailcow-dockerized/data/conf/postfix :)

**Comment by alexgleason** [comment]
I'm giving it a shot. Thanks!

**Comment by stevesbrain** [comment]
No worries - let us know how you go :D

**Comment by phipag** [comment]
Any news about mailing lists in mailcow dockerized? I don't have success installing sympa

**Comment by alexgleason** [comment]
I gave up and used Mailinabox instead, then followed a tutorial to set up Mailman 2 alongside it.

After a MIAB update, my config broke. Not sure I can recommend even trying this unless you're an email expert or intend to become one.

**Comment by Braintelligence** [comment]
I trink it won't be long until someone implements this as linked docker container.

**Comment by phipag** [comment]
Would be great if someone implements it since mailcow works really great and this is the only thing that is missing a bit.

**Comment by andryyy** [comment]
I added it to my todo .. this and sender/rcpt bcc maps.

**Comment by phipag** [comment]
Thank you, I'd love to see this in mailcow 👍

**Comment by Braintelligence** [comment]
@andryyy is just the best :D

**Comment by pgollor** [comment]
It would be great to integrate Mailman or another system into the mailcow project. I tested https://github.com/maxking/docker-mailman with mailcow successfully but the docker Mailman project is like a overkill because i don't need user registration and a web archive for Mailinglists. It is not so easy to disable the features. But maybe the project could help?

**Comment by carlbennett** [comment]
Any update on this feature request? I'd also like to have distribution groups/mailing lists set up through Mailcow. Thanks!

**Comment by djesionek** [comment]
@pgollor that is an good idea. I'm now also successfully using docker-mailman in combination with mailcow-dockerized (although getting them work together was a bit of pain in the b***). 
It would be nice to integrate only mailman-core into mailcow, managing lists over the mailcow interface and also allowing public subscriptions that way.

**Comment by cklabautermann** [comment]
I also would love to have an integrated - maybe optional mailinglist tool  installation in mailcow.

**Comment by Shadowghost** [comment]
If anyone is still interested in this, I combined mailcow and mailman3 in one docker-compose project:
https://github.com/Shadowghost/mailcow-mailman3-dockerized
(Currently) It's no more than combining both projects and changing the configs a bit.

**Comment by seefood** [comment]
what are the chances mailcow will integrate with @Shadowghost? is it a simple PR?

I prefer to get the functionality in the widely supported branch rather than an obscure one with fewer eyes debugging.

**Comment by mamair** [comment]
I#m just looking for such a solution too. I dont know how to install an extra mailinglist beside mailcow dockerized. Why not set up fundraising for extra features?

**Comment by mamair** [comment]
@phipag sympa feature list looks great, but I too cant install it. debian has a package, but documentation seems to be very outdatet and doesnt fit to sympaś documentation ... :-(

**Comment by FrancescMiV** [comment]
Hi, I have tried to create aliases as groups for forwarding but without success. :(
I add an alias for example: testgruppe@domain.com (Alias Adesse) and put forward (target) to user1@domain.com, user2@domain.com but I always receive message from Mail Delivery System.

Has anyone managed to do so?... :o 
Thanks

**Comment by pgollor** [comment]
> Hi, I have tried to create aliases as groups for forwarding but without success. :(
> I add an alias for example: [testgruppe@domain.com](mailto:testgruppe@domain.com) (Alias Adesse) and put forward (target) to [user1@domain.com](mailto:user1@domain.com), [user2@domain.com](mailto:user2@domain.com) but I always receive message from Mail Delivery System.
> 
> Has anyone managed to do so?... :o
> Thanks

I think this is not the right thread to discuss your problem.

**Comment by FrancescMiV** [comment]
> > Hi, I have tried to create aliases as groups for forwarding but without success. :(
> > I add an alias for example: [testgruppe@domain.com](mailto:testgruppe@domain.com) (Alias Adesse) and put forward (target) to [user1@domain.com](mailto:user1@domain.com), [user2@domain.com](mailto:user2@domain.com) but I always receive message from Mail Delivery System.
> > Has anyone managed to do so?... :o
> > Thanks
> 
> I think this is not the right thread to discuss your problem.

it's like a mailing list, i think that it's the same problem and i tried to make the answers. i thought i'd comment here so as not to open a new issue, although this one is from 2017 and has been inactive for two years. excuse me.

**Comment by escape0707** [comment]
This is the top result of my Google search. Sadly, this is closed by the stale bot. Can we reopen it?
