### ISSUE TITLE
Global quarantine notifications

### ISSUE THREAD

**Issue by Geitenijs** [mailcow/mailcow-dockerized#3250]
**Is your feature request related to a problem? Please describe.**
I manage a mailcow instance for friends & family who don't have any technological knowledge, so I would like to be notified of *any* quarantine message, not just from my own mailbox.

**Describe the solution you'd like**
I'd like a *global* quarantine notification system where you can pick one or more email addresses to which quarantine notifications of all mailboxes are sent.

**Comment by andryyy** [comment]
Hi,
You always update the translations, I think I owe you this.

**Comment by Geitenijs** [comment]
@andryyy Would be great! If you have time, of course. :)

**Comment by andryyy** [comment]
Done. Can you test?

**Comment by Geitenijs** [comment]
Looks good, thanks! Does it also work when quarantine notifications are set to 'Never' for a mailbox? Because I prefer most mailbox owners not to receive the notifications themselves.

**Comment by andryyy** [comment]
No, that does not work. But you can create filters in mailcow ("Filter" tab in /mailbox) to drop their quarantine mails.

**Comment by Geitenijs** [comment]
Ok that should work for me. Thank you so much for implementing this!
