### ISSUE TITLE
Disable reject on Rspamd 

### ISSUE THREAD

**Issue by paolopoletti** [mailcow/mailcow-dockerized#3257]
Hi, i would like do disable reject on rspamd at all. I would like to leave only postfix to perform reject on dnsbl level. I've found this 

https://serverfault.com/questions/912318/do-not-reject-mails-with-rspamd-1-7

but it's not clear how to apply in the correct way.

**Comment by andryyy** [comment]
Is this a bug report or a feature request?

Change `data/conf/rspamd/local.d/actions.conf` in an updated cow. Set reject to something very high. Some forced actions are still applied. Like global blacklist matches.

Use the support channels for support questions, please.
