### ISSUE TITLE
Externer SMTP Versand fehlerhaft bzw. nicht möglich ?!

### ISSUE THREAD

**Issue by dennisdaa** [mailcow/mailcow-dockerized#3258]
Moin,

seid ein paar Tagen, komme ich nicht klar. Bin  nach dieser Anleitung: https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-disable_sender_verification/ gegangen, weil es Probleme gab.

Jedoch funktioniert auch diese Anleitung nicht. Beim Befehl ( docker-compose exec postfix-mailcow postmap /opt/postfix/conf/check_sasl_access) bekomme ich per Console diese Meldung angezeigt:

```
WARNING: The TZ variable is not set. Defaulting to a blank string.
WARNING: The DBROOT variable is not set. Defaulting to a blank string.
WARNING: The DBNAME variable is not set. Defaulting to a blank string.
WARNING: The DBUSER variable is not set. Defaulting to a blank string.
WARNING: The DBPASS variable is not set. Defaulting to a blank string.
WARNING: The MAILCOW_HOSTNAME variable is not set. Defaulting to a blank string.
WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: No container found for postfix-mailcow_1
```

Sind erstmal "Nur" Warnungen.. bis auf den Error, habe ich aber erstmal ignoriert. Dann habe ich getestet ob es den nun geht aber in der Log über der Mailcow GUI findet sich dieser Eintrag:

```
err | error: open database /opt/postfix/conf/check_sasl_access.db: No such file or directory
-- | --
8.1.2020, 12:39:26 | warning | warning: dnsblog reply timeout 10s for zen.spamhaus.org
8.1.2020, 12:39:26 | warning | warning: dnsblog_query: lookup error for DNS query 110.219.234.185.zen.spamhaus.org: Host or domain name not found. Name service error for name=110.219.234.185.zen.spamhaus.org type=A: Host not found, try again
```

Nun stehe ich vor der Wand. Kann es sein das ich was übersehen habe ? Über sogo gibt es keinerlei Probleme. Mir fehlen auch mit dieser Software und Docker die Erfahrungen. Wie wo könnte man das Problem noch angehen ?

Gruß
Dennis

**Comment by andryyy** [comment]
Please use Telegram for support, especially in German.

Please do not blindly select a bug report template and remove all content to post a support question.
