### ISSUE TITLE
DKIM no longer working if using external mail client

### ISSUE THREAD

**Issue by MyUncleSam** [mailcow/mailcow-dockerized#3262]
Hi there,

I have a strange problem. I was on holiday for about 14 days. Now I came back and updated my mailcow environment without any problems. I also did all updates which I think included some kernel updates (no idea if that could be a problem).

After that I added a new domain, set everything up (including dkim, dmarc, spf, ...) and checked everything - even the DNS button inside the webinterface which says "all fine".

As I wanted to test it every test page told me that there is no DKIM provided. I tried everything and then tested an old domain which already was working. But it seems that no sent mail gets a dkim signature. So I tried to figure out why. But the only thing I found was:
If I log into SOGo and send an E-Mail there is a DKIM signature which is valid. But if I use my E-Mail client (tried emClient and Thunderbird) there is no DKIM signature. But as far as I understand the DKIM signature should be set by the server and not the mail client (no matter if it is the webmail or a standalone mail client).

I restarted the server but it was not changing anything. I am sorry but I have no deep knowledge of mailcow so I cannot tell you more. I was not able to find any log files for that. If you need one - please tell me.

Can someone please check and verify that? Or tell me if I made any mistakes?

Details about my virtual server:
It is standalone only for mailcow. There are no proxies or something else - I set it up using your documentation.

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.08 |
| Is Apparmor, SELinux or similar active? |  |
| Virtualization technlogy (KVM, VMware, Xen, etc) | I think it is KVM (vserver at netcup) |
| Server/VM specifications (Memory, CPU Cores) | Dualcore, 8GB Ram |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.25.1, build a82fef07 |
| Reverse proxy (custom solution) | no |

**Comment by christianbur** [comment]
I have exactly the same problem.
@andryyy please reopen the ticket.

I use Roundcoude as webmailer, it accesses Mailcow via IMAP/SNMP (but has an internal 172.22.x.x IP), so DKIM works fine with it.
But if I create an account on Thunderbird with exactly the same IMAP/SNMP credentials, and then send an email (now external IP), DKIM does not work. 
The problem occurs with multiple accounts.

**Comment by MyUncleSam** [comment]
The last changes by @andryyy fixed that for me. Thx!

**Comment by andryyy** [comment]
This was closed with a commit. I think I just the wrong keyword...

The last commit also signes sieve rejects and forwards correctly (no re-sign, arc only). Google marks forwarded mail as DKIM, SPF valid.
