### ISSUE TITLE
Unable to release email from Quarantine, invalid SMTP Command: unsubscribe

### ISSUE THREAD

**Issue by remkolodder** [mailcow/mailcow-dockerized#3263]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is that advertisement emails (per request of the user) that contain an "Unsubscribe:" line (it appears in the message that this is after a signature, so perhaps the end of a body regularly seen) is marked as invalid smtp command in postfix and therefor not released.

The log message states:
 warning: non-SMTP command from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.28.1.6]: Unsubscribe:

The mail might be send given the postfix info, however it is not removed from quarantine, which gives a postfix error.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

I have a EML file that you can see in private that exhibits this issue. In the past these kind of emails were not triggered on a postfix level, so I suspect this to be in the Quarantine code that reinjects the email. 

Sadly I do not have the original unmodified version so that I Can compare it.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | n/a directly on the hardware |
| Server/VM specifications (Memory, CPU Cores) | 64gb quad core machine |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.18.0 |
| Reverse proxy (custom solution) | n/a |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Please let me know if you need additional info. I am willing to share the EML that I get from the quarantine system in private since it contains private information. Thanks

**Comment by remkolodder** [comment]
![Screenshot 2020-01-13 at 12 09 53](https://user-images.githubusercontent.com/695440/72251186-ab96b480-35fd-11ea-882c-05be082861ea.png)

Screenshot of the UI error that is seen. This is related to the message:
 warning: non-SMTP command from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.28.1.6]: Unsubscribe:

**Comment by andryyy** [comment]
Please post your git diff, I cannot reproduce it. We also need to the the quarantine line in the UI, please. Sender, Rcpt etc.

**Comment by remkolodder** [comment]
Hello,

Attached is the gitdiff. I have added a few RBL's, tried to work around the command filtering in postfix (but that does not work and is effectively not being used) and added a sasl workaround for an account (beyond the scope of this request).

Is there a way I Can give you access to the Quarantine in private or show this in private? It is not my personal email it's from someone else and I cannot publicly share it obviously.

I "hacked" a bit around this by anonymizing the plaintext email part from the quarantine:

&nbsp;

&copy; 2020 Decovry.com 

Om deze nieuwsbrief altijd in je inbox te ontvangen, voeg
newsletter@news.decovry.com  toe aan
je contacten. Decovry.com  is een members-only
website. U ontvangt deze nieuwsbrief omdat u zich ingeschreven heeft met
<destemail>. Om onze aanbiedingen niet meer te ontvangen, Klik hier
.
_________________

Sent to <destemail>

Unsubscribe:
http://decovry.emlnk1.com/proc.php?nl=<id>&c=<id>&m=<id>&s=<id>&act=unsub

A Growing Three, Ottergemsesteenweg Zuid 808 bus 300, 9000 Gent, Belgium

It starts with the unsubscribe: part which is no longer being parsed. I think that postfix thinks the email is "done" and starts processing commands after the body.
[diff_github.txt](https://github.com/mailcow/mailcow-dockerized/files/4063484/diff_github.txt)

**Comment by andryyy** [comment]
Can you dump the quarantine ID?

```
source mailcow.conf; docker-compose exec mysql-mailcow mysqldump -u$DBUSER -p$DBPASS $DBNAME quarantine --where 'id=1';
```

Replace 1 by whatever ID that item has.

You can mail me the result to info@servercow.de
