### ISSUE TITLE
Best way to migrate server to new IP?

### ISSUE THREAD

**Issue by alexander-rieder** [mailcow/mailcow-dockerized#3264]
Hey everyone,

what is the best way to migrate a mailcow server to a new public ip?

Any ideas or experience?

Greetings,

Alex

**Comment by ghost** [comment]
Hi,

There is nothing much to do on the Mailcow level, just change your IPs on your server, update your DNS entries, and it works.

Best,

Mathilde

**Comment by ntimo** [comment]
This is not a support channel, feel free to join the Telegram group to ask for advise. https://t.me/mailcow :)

**Comment by mkuron** [comment]
I would do roughly this:

1. Set the TTL on your DNS records to one hour or less. Wait 48 hours.
2. If moving to a new server: stop your old Mailcow and back it up. Restore to your new server and start Mailcow.
3. Change your DNS records to the new server and set the TTL back to its original value.

Done. Mails should start flowing to your new server within one hour. And no messages will be lost as long as you take less than ~3 days to complete all three steps.
