### ISSUE TITLE
Remove "Add Domain" button from the domain admin login

### ISSUE THREAD

**Issue by ravinayag** [mailcow/mailcow-dockerized#3267]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think maybe interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x ] I understand that not following the below instructions might result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is to remove unnecessary buttons, to be greyed out or removed from WebUI page.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
This is to remove the "AddDomain" button from the WebUI interface when you logged in as a Domain administrator. because there is no use of AddDomain Button over there when i  don't have access to create new domains. 

1. From Superadmin, i create a new domain user and assigned the domain to him.
2. Then i logged in as domain admin user and clicked domain tab, right corner of the tab i have "+AddDomain" button(Colour: green)  next to "Refresh" Button.
3. Since this button is not needed to be visible (webUI) for Domain admins as per their ACL rights.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

**Comment by andryyy** [comment]
Thanks.

**Comment by ravinayag** [comment]
Hi , is the request taken in?

**Comment by andryyy** [comment]
Yes, it is fixed.

**Comment by ravinayag** [comment]
cool, t y
