### ISSUE TITLE
Add RSpamd phishing module

### ISSUE THREAD

**Issue by alexanderadam** [mailcow/mailcow-dockerized#3268]
**Is your feature request related to a problem? Please describe.**

I just stumbled over [caesonia which seems to have various security related features integrated](https://github.com/mailcow/mailcow-dockerized/issues/2762#issuecomment-574139842).

One feature is the activated [Phishing module of rspamd](https://rspamd.com/doc/modules/phishing.html) which [integrates](https://github.com/vedetta-com/caesonia/blob/c844d12ab97c00e376eba50de2ddedcbede5732b/src/etc/rspamd/local.d/phishing.conf#L1) a list of known phishing sites at [OpenPhish](https://www.openphish.com/).

So I thought it might be useful to integrate it in Mailcow as well.

**Describe the solution you'd like**

Integrate the module and [a useful configuration](https://github.com/vedetta-com/caesonia/blob/c844d12ab97c00e376eba50de2ddedcbede5732b/src/etc/rspamd/local.d/phishing.conf#L1).

**Comment by andryyy** [comment]
Rspamds phishing module has always been a bit heavy on resources. We integrated a phishing detection into Clam. 

You can enable the module in your config any time.

**Comment by alexanderadam** [comment]
> We integrated a phishing detection into Clam.

Ah I didn't know that. Thank you for pointing me [into the right direction](https://github.com/mailcow/mailcow-dockerized/blob/dfd40500b4da97dce21dab4778635834e6c52f23/data/Dockerfiles/clamd/clamd.sh#L69-L70).

I will close this issue then.
