### ISSUE TITLE
confusing to add a resource in Mailcow UI

### ISSUE THREAD

**Issue by CookieCr2nk** [mailcow/mailcow-dockerized#3269]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is...

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. go to E-Mail Setup in the Mailcow UI
2. And then to go to the ressource tab and click to "add a new ressource"
3. When i add a description with a space, it not creating the ressource. Its confusing, so my opinium is to give a note, so that special character and spaces are not supported.

<img width="677" alt="uc" src="https://user-images.githubusercontent.com/38990807/72373374-6c08bf00-3708-11ea-8ed6-260604e4ea98.png">

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**Comment by andryyy** [comment]
It does work with a space. You need to select a domain and "kind" of resource.

**Comment by CookieCr2nk** [comment]
Yes, it works

Thanks
