### ISSUE TITLE
SOGo Login Issue behind Reverse Proxy (nginx)

### ISSUE THREAD

**Issue by chaosbunker** [mailcow/mailcow-dockerized#327]
I have a fresh install of mailcow, followed the instructions in the docs to set up behind a RP and when I try to log into SOGo, it does not work because it tries to go to _https://127.0.0.1:8080/SOGo/so/me@example.org/Mail_

I have run mailcow-dockerized behind nginx RP successfully before with the same procedure.
I do remember having this problem before and back then it was a bug, but what's a bit confusing: I have another mailcow-instance on another server which was not behind a RP, and i just tested how it would behave if i set it behind an nginx RP and copy&pasted the nginx config of the server where it did not work and for some reason SOGo login works fine. I thought it might be because it was running an old version of mailcow-dockerized, so I updated it, but it still worked fine. 

I'm confused. How can I troubleshoot this?

**Comment by chaosbunker** [comment]
Seems to be a bug. I could reproduce it on a clean install. I have the issue with the current version of mailcow-dockerized, but don't with an older version that I still have from a month ago or so. I

**Comment by andryyy** [comment]
We need at least your RP config to help. :)

**Comment by chaosbunker** [comment]
> server {
>     listen 80 default_server;
>     server_name mx.example.org autodiscover.example.org autoconfig.example.org;
>     return 301 https://$host$request_uri;
> }
> server {
>     listen 443;
>     server_name mx.example.org autodiscover.example.org autoconfig.example.org;
>     ssl on;
>     ssl_certificate /happycow/mailcow-dockerized/data/assets/ssl/cert.pem;
>     ssl_certificate_key /happycow/mailcow-dockerized/data/assets/ssl/key.pem;
>         ssl_session_cache shared:SSL:10m;
>         ssl_session_timeout 10m;
>     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>     ssl_prefer_server_ciphers on;
>     ssl_ciphers 'EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA';
>         ssl_dhparam ssl/dhparam.pem;
>     add_header Strict-Transport-Security "max-age=15768000; includeSubDomains";
>         add_header X-Frame-Options DENY;
>         add_header X-Content-Type-Options nosniff;
>     ssl_ecdh_curve secp384r1;
>         gzip off;
>     location / {
>         proxy_pass http://127.0.0.1:8080/;
>         proxy_redirect http://127.0.0.1:8080/ $scheme://$host:$server_port/;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> }

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#nginx

Please check the link and set it up accordingly. Should work. :)

**Comment by chaosbunker** [comment]
Haha, oh my...

There is always something silly I overlook.

So of course that part changed in the last month and I was just copying and pasting from the old version, without thinking to double check. That explains why it worked fine with the old version I tried.

Oh well, thanks for pointing it out and sorry for not checking that part before opening the issue  👻

**Comment by andryyy** [comment]
No problem!

The configuration changed a few times a month back. :/
