### ISSUE TITLE
Dovecot is ignoring all sieve configurations that are not generated from SOGo. 

### ISSUE THREAD

**Issue by nk-87** [mailcow/mailcow-dockerized#3274]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Dovecot is ignoring all sieve configurations that are not generated from SOGo. Once a filter is added on SOGo, a sogo.sieve configuration file is generated. This can be edited by sieve editors and custom scripts will work as normal. Issue is that it gets deleted by SOGo. 

On the server, there are no difference in file permission and manually creating "sogo.sieve" does not work. It _has_ to be generated by SOGo. 

This was not the case in previous versions of Mailcow - custom sieve scripts worked fine in the past.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Use a sieve editor to add a new script. 
2. If the editor can show whether the script is active or not, it should show inactive. If not, test by sending self email. Sieve filter will be ignored.
3. Create a filter in SOGo - these filters are not ignored.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) |3GB, 1vCPU |
| Docker Version (`docker version`) | 19.03.5  |
| Docker-Compose Version (`docker-compose version`) | 1.25.0 |
| Reverse proxy (custom solution) | Caddy (tested without it as well) |

Further notes:

 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Hi,

Please use a dedicated sieve script for your own filters. SOGo does in recent versions (>=4.2.0) detect external, active scripts and shows a hint in the UI. It was never a good idea to mess with the SOGo scripts. :)

**Comment by nk-87** [comment]
Hi @andryyy, can you elaborate? I was already using a dedicated sieve script- they no longer work. I am currently forced to edit a SOGo generated sieve script as the ones I upload do not work (they are ignored). 

I have the same sieve script on the server (same directory as where the SOGo one goes), and it doesn't detect it, and there are no indication on SOGo's frontend. 

I named my sieve script `main.sieve`, and I see this in my USER.sieve:

```
require ["include"];

include :personal "main";
```

But `main.sieve` cannot be activated. 

EDIT: 

I added a filter via SOGo, then renamed `sogo.sieve` into `main.sieve` - when I did this, SOGo finally recognized it as an external filter, and a notification appeared on SOGo. 

It seems like the server is only recognizing the scripts that are first generated by SOGo.

**Comment by karthanistyr** [comment]
[redacted, off-topic -- original comment in history]

**Comment by nk-87** [comment]
There appears to be a bit of misunderstanding. The issue is not that SOGo is _overwriting_ anything, it's that Dovecot no longer recognizes any script that is not generated by SOGo. SOGo also does not recognize any scripts uploaded as a foreign script unless you first generate it with SOGo. 

The issue with overwriting is that it affects a work around to the original issue, but it is not the core issue. 

To be clear - I am already uploading my own script that is not generated or related to SOGo. These scripts are not being recognized _at all_ in any form by either Dovecot or SOGo. It used to in a previous version but I am unsure when it stopped. 

A workaround that is currently working is to create a filter in SOGo then rename the created `sogo.sieve`. At that point, SOGo finally recognizes the foreign script.

**Comment by karthanistyr** [comment]
Sure thing, apologies, I'll redact my comment then.

**Comment by danielmorlock** [comment]
I can confirm this issue as any script except `sogo.sieve` is ignored by Dovecot:

If I add an invalid sieve rule to sogo.sieve, I get the following (correct) validation error when I try to activate it:

```
# doveadm sieve activate -u$u sogo
doveadm(....): Error: sieve: sogo: line 6: specified header 'from-envelope' is not allowed for the address test
doveadm(...): Error: sieve: sogo: validation failed
```

If I rename sogo.sieve to custom.sieve, errors are just ignored since the script is ignored at all:

```
# cp sogo.sieve custom.sieve
# doveadm sieve activate -u$u custom
#
```

Are there any fixes or workarounds or an explanation for this behavior?

**Comment by hugalafutro** [comment]
I don't understand the more technical aspects of the issue, but from the symptoms I seem to experience the same (I apologize if I am wrong). 

I use roundcube 1.5.2 mail client (installed according to mailcow docs), I also tried Rainloop inside my Nextcloud, but any filter I create in them gets ignored and incoming mail remains in inbox. If I create the same filter in sogo, mail gets filed to where I chose in the filter as expected.

**Comment by karthanistyr** [comment]
In roundcube (which I also use), you may have to select which set of rules is loaded on the server
![2022-01-13_13-07-52_capture](https://user-images.githubusercontent.com/7722196/149327751-2d786c6a-43cb-43b5-9aa5-eebe164cbbec.png)
 In my screenshot, sogo was already existing (created by sogo itself), i created the "local" set and set my rules there. As long as I don't interact with sogo, the local set stays enforced, but sogo will revert to the "sogo" set if I interact with it.

**Comment by hugalafutro** [comment]
I see I thought all of the filters would be active. Does the name of the filter set matter, ie does it have to be named `local`? By default the set from rc got named `roundcube` and the sogo one is `sogo`. Should I rename the rc one to `local` ?

I also noticed, although both the filters show identical in the rc web ui, editing them shows a difference:

the filter created in sogo has this line `if allof (address :contains "from" "@github.com")`
but filter created in rc has this instead: `if allof (header :contains "from" "@github.com")`
not really sure how much (if any) difference that makes though

**Comment by karthanistyr** [comment]
i think you can name them however you want; the set I wanted to use had to be selected (like on my screenshot), but that's all I needed to do.
The rules created through the sieve clients (e.g. sogo or roundcube) are formatted as the specific client intends (not all clients show the same options or use the same labels for things), you'll find what suits you by trial and error. Usually, though, mature sieve clients like roundcube get it right.
