### ISSUE TITLE
Send emails from different domains on a single domain

### ISSUE THREAD

**Issue by osidney** [mailcow/mailcow-dockerized#3277]
I have a facility where you have several domains, but I want to send emails from all these domains by just one, is it possible to do this this way? If so how? Thanks.

**Comment by MarkusP** [comment]
what do you mean "by just one"?
do you mean one authenticated user should be able to send mails for different sender addresses, like

first.name@firstdomain.com
first.name@seconddomain.com
first.name@thirddomain.com

MP

**Comment by osidney** [comment]
What I want to do is that all users of the domains
one@domain.com
two@domain.com
three@domain.com
do the authenticated sending by another domain mydomain.com

**Comment by MarkusP** [comment]
Ok, this can be done the following way...

Login to the mailcow ui as global admin, not as domain-admin

![image](https://user-images.githubusercontent.com/1380385/72933851-e073db80-3d62-11ea-8522-462536314b81.png)

go to "configuration => mail setup"

![image](https://user-images.githubusercontent.com/1380385/72934017-29c42b00-3d63-11ea-9700-3d287056f247.png)

there select the "mailboxes" tab and for the user you want to enable to send as a different email address click the "edit" button at the right...

![image](https://user-images.githubusercontent.com/1380385/72934292-a0f9bf00-3d63-11ea-8cbf-bb32c8aa6595.png)

within this section you will find "External sender addresses" and in this field you have to enter all the email addresses under which the account should be able to send emails...

![image](https://user-images.githubusercontent.com/1380385/72934532-1bc2da00-3d64-11ea-8bb4-722e4b61d04e.png)

*REMEMBER*
you have to do this for every user seperately...

Best greetings
Markus

**Comment by andryyy** [comment]
Thank you for answering this, @MarkusP :)

**Comment by MarkusP** [comment]
sure :-)
