### ISSUE TITLE
API: Add > Mailbox > {MD5-CRYPT} password

### ISSUE THREAD

**Issue by cybersholt** [mailcow/mailcow-dockerized#3282]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following: ** *(fill out each checkbox with a `X` once done)*
- [ X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

While working with the API to import users from our previous server, I noticed an issue when migrating the user’s old dovecot password which is stored as a md5 style encrypted string. I read on #1665 that the system supports these types of passwords, however even with known accounts I was unable to login to an imported account.

I checked the MySQL database and noticed that the passwords were stored as "{SSHA256}RS+Jucfz/mw2+.......", checking further it looks like the API always calls the mailbox function which in turn tries to encrypt the string see https://github.com/mailcow/mailcow-dockerized/blob/2db8610c5e1d0331c20dfc72c7795181c72a6e61/data/web/inc/functions.mailbox.inc.php#L913 

To fix this issue just need a simple if copied from: https://github.com/mailcow/mailcow-dockerized/blob/2db8610c5e1d0331c20dfc72c7795181c72a6e61/data/web/inc/functions.inc.php#L419

`
if(preg_match('/^{MD5-CRYPT}/i', $password)) {
    $password_hashed = $password;
} else {
    $password_hashed = hash_password($password);
}
`

This solved the issue and I was able to import accounts successfully

**Comment by mkuron** [comment]
Can you provide a pull request? That way, everyone can benefit from your fix. Also, you could easily support all password schemes, not just MD5-CRYPT.

**Comment by cybersholt** [comment]
@mkuron sure no problem. I'll reference and close this when it's pushed.

**Comment by cybersholt** [comment]
fixed with pull request #3283
