### ISSUE TITLE
Fresh install, 'Waiting for database to come up...'

### ISSUE THREAD

**Issue by spoetnik** [mailcow/mailcow-dockerized#3285]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, your issue is either closed or ignored, too. :( This is (not only) because we are evil. Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. :) Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

After a fresh install, mallow doesn't come up. docker-compose logs -f fills up with the message 'Waiting for database to come up...'.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

I have a fresh VPS with Ubuntu 18.04 LTS 64bit

Installed Docker, docker-compose. Check, and adjusted umask, git clone the project, and followed the instructions.
First Error during docker-compose up -d is `ERROR: for dockerapi-mailcow  Cannot start service dockerapi-mailcow: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write 1 to memory.oom_control: write /sys/fs/cgroup/memory/docker/8346fd4d5b5ffca8742b8513aab53f9cc561871a9187a68c3397e213baa44a90/memory.oom_control: permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.`
I removed the `oom_kill_disable: true` from the docker-compose. 
The a docker-compose up -d gives no errors, but the database won't come up.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS 64bit |
| Is Apparmor, SELinux or similar active? | not that I am aware of |
| Virtualization technlogy (KVM, VMware, Xen, etc) | openvz |
| Server/VM specifications (Memory, CPU Cores) | CPU vCores, 4 RAM guaranteed, 8 GB |
| Docker Version (`docker version`) | Version:           19.03.5 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.1, build a82fef07 |
| Reverse proxy (custom solution) | non |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
git diff origin/master
diff --git a/docker-compose.yml b/docker-compose.yml
index f18b3549..977d3546 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -404,7 +404,6 @@ services:
     dockerapi-mailcow:
       image: mailcow/dockerapi:1.36
       restart: always
-      oom_kill_disable: true
       dns:
         - ${IPV4_NETWORK:-172.22.1}.254
       environment:

 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout? No timeouts, they resolve
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by tkorves** [comment]
As you're using OpenVZ, maybe have a look here:

https://github.com/mailcow/mailcow-dockerized/issues/329#issuecomment-306073847

**Comment by spoetnik** [comment]
> As you're using OpenVZ, maybe have a look here:
> 
> [#329 (comment)](https://github.com/mailcow/mailcow-dockerized/issues/329#issuecomment-306073847)

Thanks, but Docker is running on the machine. The link issue has to do with Docker not running.

**Comment by spoetnik** [comment]
`docker-compose logs mysql-mailcow
Attaching to mailcowdockerized_mysql-mailcow_1
mysql-mailcow_1      | 2020-01-22 11:11:11+01:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.21+maria~bionic started.
mysql-mailcow_1      | 2020-01-22 11:11:12+01:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql-mailcow_1      | 2020-01-22 11:11:12+01:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.21+maria~bionic started.
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] mysqld (mysqld 10.3.21-MariaDB-1:10.3.21+maria~bionic) starting as process 1 ...
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Initializing buffer pool, total size = 8M, instances = 1, chunk size = 8M
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Waiting for purge to start
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: 10.3.21 started; log sequence number 1625520; transaction id 21
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] Server socket created on IP: '::'.
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] InnoDB: Buffer pool(s) load completed at 200122 11:11:13
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Warning] 'proxies_priv' entry '@% root@1d84c6f0444d' ignored in --skip-name-resolve mode.
mysql-mailcow_1      | 2020-01-22 11:11:13 6 [Note] Event Scheduler: scheduler thread started with id 6
mysql-mailcow_1      | 2020-01-22 11:11:13 0 [Note] mysqld: ready for connections.
mysql-mailcow_1      | Version: '10.3.21-MariaDB-1:10.3.21+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
`

**Comment by andryyy** [comment]
https://github.com/mailcow/mailcow-dockerized-docs/commit/aa47b85afbe1013f2cc298ed9710adc436db5e89

OpenVZ is nor supported, sorry.
