### ISSUE TITLE
"Invalid Transport"

### ISSUE THREAD

**Issue by rt050** [mailcow/mailcow-dockerized#3286]
Hi there,

I have an issue that is really killing me at the moment.

In order to try and beat 365/Outlook spam I'm trying to send via Mailjet/Mailgun/Whatever works.

No matter what I do, I try to test the connection and all I get is "Invalid Transport" when I click "run test".

Has anybody got any pointers as to what I may have done wrong. This is my fourth fresh install. Same issue. I really like this product so would be a shame to fail here.

Thanks in advance,
Ryan

**Comment by andryyy** [comment]
It was probably fixed a few seconds ago. Do use "[]" anyway! Like [bla]:587.

**Comment by rt050** [comment]
Oh my good lord. Thank you for your prompt on that, brackets fixed the issue.

It's weird because I tested via a different smtp server when I was first looking into it (without brackets) and it worked.

Thank you!
