### ISSUE TITLE
RSPAMD "MIME_BAD_EXTENSION (20) [doc]" error in RSPAMd Log

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#3287]
Hi everyone,

fresh install of mailcow-dockerized on Ubuntu 18.04LTS. Production environment.

The following happens:
Someone sends email with .doc Attachment to mailbox on this mailcow.
Email gets rejected due to SPAM Score.
RSPAMd shows the following in the gui => history tab

MIME_BAD_EXTENSION (20) [doc]

![20200122-150735](https://user-images.githubusercontent.com/1380385/72900868-f2d12380-3d28-11ea-9973-82a86c6e9918.png)

The same happens, but without rejecting the email, if someone sends email with .doc attachment from/thru this mailcow instance to someone on the internet.

MAILCOW_AUTH (-20)
MIME_BAD_EXTENSION (20) [doc]
BAYES_HAM (-5.5) [100.00%]
MIME_GOOD (-0.1) [multipart/mixed,text/plain]
DYN_RL_CHECK (0)
TO_DN_ALL (0)
MIME_TRACE (0) [0:+,1:+,2:-,2:~]
MID_RHS_MATCH_FROM (0)
DKIM_SIGNED (0)

![20200122-150851](https://user-images.githubusercontent.com/1380385/72900951-1e540e00-3d29-11ea-94f8-86638ba651ac.png)

Anyone any idea? 

thanks in advance
best greetings
Markus

**Comment by mkuron** [comment]
Are you sure you're on the latest version? We actually fixed that in #3273 a few days ago.

**Comment by MarkusP** [comment]
Here the actual versions...

```bash
root@mailserver:/opt/mailcow-dockerized# docker-compose images
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
              Container                    Repository             Tag           Image Id       Size  
-----------------------------------------------------------------------------------------------------
mailcowdockerized_acme-mailcow_1        mailcow/acme        1.63              8878902820a0   116.5 MB
mailcowdockerized_clamd-mailcow_1       mailcow/clamd       1.35              d4b6c6f2c344   213.9 MB
mailcowdockerized_dockerapi-mailcow_1   mailcow/dockerapi   1.36              037253cd4815   74.27 MB
mailcowdockerized_dovecot-mailcow_1     mailcow/dovecot     1.108             dec8e7f18607   401.8 MB
mailcowdockerized_ipv6nat-mailcow_1     robbertkl/ipv6nat   latest            f46f4d37caac   21.47 MB
mailcowdockerized_memcached-mailcow_1   memcached           alpine            319607c5f2b0   9.084 MB
mailcowdockerized_mysql-mailcow_1       mariadb             10.3              b2445052feca   342.9 MB
mailcowdockerized_netfilter-mailcow_1   mailcow/netfilter   1.31              2dcc9faf2749   82.36 MB
mailcowdockerized_nginx-mailcow_1       nginx               mainline-alpine   36189e6707f4   21.46 MB
mailcowdockerized_olefy-mailcow_1       mailcow/olefy       1.2               961926f178c1   89.67 MB
mailcowdockerized_php-fpm-mailcow_1     mailcow/phpfpm      1.55              766f3ca7155c   339.1 MB
mailcowdockerized_postfix-mailcow_1     mailcow/postfix     1.44              5a97b4f937a4   269.4 MB
mailcowdockerized_redis-mailcow_1       redis               5-alpine          8af6a13284bf   32.98 MB
mailcowdockerized_rspamd-mailcow_1      mailcow/rspamd      1.59              b7c165384522   158.6 MB
mailcowdockerized_sogo-mailcow_1        mailcow/sogo        1.65              a3fe21bd23d6   478.1 MB
mailcowdockerized_solr-mailcow_1        mailcow/solr        1.7               df537896e541   619.9 MB
mailcowdockerized_unbound-mailcow_1     mailcow/unbound     1.10              421ae97b1278   20.85 MB
mailcowdockerized_watchdog-mailcow_1    mailcow/watchdog    1.67              76adb2d8768b   103.2 MB

This is after the update

```bash
root@mailserver:/opt/mailcow-dockerized# docker-compose images
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
              Container                    Repository             Tag           Image Id       Size  
-----------------------------------------------------------------------------------------------------
mailcowdockerized_acme-mailcow_1        mailcow/acme        1.64              e54800828a5b   116.5 MB
mailcowdockerized_clamd-mailcow_1       mailcow/clamd       1.35              d4b6c6f2c344   213.9 MB
mailcowdockerized_dockerapi-mailcow_1   mailcow/dockerapi   1.36              037253cd4815   74.27 MB
mailcowdockerized_dovecot-mailcow_1     mailcow/dovecot     1.108             dec8e7f18607   401.8 MB
mailcowdockerized_ipv6nat-mailcow_1     robbertkl/ipv6nat   latest            f46f4d37caac   21.47 MB
mailcowdockerized_memcached-mailcow_1   memcached           alpine            319607c5f2b0   9.084 MB
mailcowdockerized_mysql-mailcow_1       mariadb             10.3              1632679210bd   342.9 MB
mailcowdockerized_netfilter-mailcow_1   mailcow/netfilter   1.31              2dcc9faf2749   82.36 MB
mailcowdockerized_nginx-mailcow_1       nginx               mainline-alpine   764297b381cc   21.78 MB
mailcowdockerized_olefy-mailcow_1       mailcow/olefy       1.2               961926f178c1   89.67 MB
mailcowdockerized_php-fpm-mailcow_1     mailcow/phpfpm      1.55              766f3ca7155c   339.1 MB
mailcowdockerized_postfix-mailcow_1     mailcow/postfix     1.44              5a97b4f937a4   269.4 MB
mailcowdockerized_redis-mailcow_1       redis               5-alpine          b68707e68547   29.78 MB
mailcowdockerized_rspamd-mailcow_1      mailcow/rspamd      1.59              b7c165384522   158.6 MB
mailcowdockerized_sogo-mailcow_1        mailcow/sogo        1.70              63f74bc43045   477.6 MB
mailcowdockerized_solr-mailcow_1        mailcow/solr        1.7               df537896e541   619.9 MB
mailcowdockerized_unbound-mailcow_1     mailcow/unbound     1.10              421ae97b1278   20.85 MB
mailcowdockerized_watchdog-mailcow_1    mailcow/watchdog    1.67              76adb2d8768b   103.2 MB

Ok, did some tests and now **it seems correct...  thanks** and sorry if bothering you!

**Comment by PiotrEsse** [comment]
After Update MAilcow few days ago this issue reappear. I am getting 40 points hit only for sending plaintext .doc 

Ive lower rspamd Symbols&rules  - MIME_BAD_EXTENSION to 0,001

Many people cand send and recieve mails - they getting error: 554 5.7.1 "This message does not meet our delivery requirements"

**Comment by andryyy** [comment]
New Emotet variants are being sent and mostly hidden in .doc. 

Please use a newer and less dangerous container format for office files. :)

**Comment by PiotrEsse** [comment]
Dear Andry, 
Thank You Very much!!

**Comment by andryyy** [comment]
You are welcome!

**Comment by mkuron** [comment]
> New Emotet variants are being sent and mostly hidden in .doc.

But even without explicitly blocking .doc, they should still be caught by the oletools check for macros, right? Or are there now variants that don‘t need macros at all?

**Comment by andryyy** [comment]
No macros were detected. :(

**Comment by mkuron** [comment]
Oh, that‘s bad. Now I wonder whether it‘s an oletools bug or they found a new infection vector that doesn‘t require macros. Have you had a chance to inspect the file more closely?

**Comment by andryyy** [comment]
I will give it a try when I find time today.

**Comment by PiotrEsse** [comment]
In my case it was simple plain DOC file beeing blocked. 

I am attaching it as ZIP file because GIT prevent DOC upload- coincidence? I do not think.. ()
[littlelovesforsrtnew.zip](https://github.com/mailcow/mailcow-dockerized/files/5193510/littlelovesforsrtnew.zip)

**Comment by andryyy** [comment]
It is correct that we block plain .doc files. What @mkuron meant was an infected .doc, that slipped through Oletools and ClamAV. No need to attach the doc. :)

**Comment by andryyy** [comment]
@mkuron There was a bug in oletools that prevents oletools to work with olefy. C-R provided me a fix. :) Now it is detected.

@ntimo Can you work on a test for macros? :)

**Comment by Haves1001** [comment]
I saw the same issue appear when one of my accounts received a mail with an atteched .doc file. 

It got rated with MIME_BAD_EXTENSION (40) [doc], while rspamd states that the symbol MIME_BAD_EXTENSION has a score of 2. Shouldn't this email then being rated with (2)?
