### ISSUE TITLE
Instalation error 

### ISSUE THREAD

**Issue by Dad-Ju** [mailcow/mailcow-dockerized#329]
when i use this **_docker-compose pull docker-compose up -d_** commands i get an error : 
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@mail:~/mailcow-dockerized# docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@mail:~/mailcow-dockerized# docker-compose pull
Pulling mysql-mailcow (mariadb:10.1)...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

what can i do to fix this :/
GW Ju

**Comment by chriscroome** [comment]
Is Docker running?

You can check using `ps -lA | grep docker`

**Comment by Dad-Ju** [comment]
no feedback from console
when i use this command

**Comment by chriscroome** [comment]
@Dad-Ju in that case it appears that Docker isn't running?

**Comment by Dad-Ju** [comment]
how can i bring it to run :)

**Comment by andryyy** [comment]
Yes, it is not running. How did you install it? On which distro? You can also ask in #docker on IRC.

**Comment by Dad-Ju** [comment]
i use this introduction https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by TBK** [comment]
Which Linux distro are you using?

**Comment by Dad-Ju** [comment]
This is everything i have of information :) **http://prntscr.com/ffqpnx**

**Comment by TBK** [comment]
Try to follow the official guide for Debian:
https://docs.docker.com/engine/installation/linux/debian/#install-docker-ce

**Comment by K2rool** [comment]
Since your vps is OpenVZ the issue why docker is not running might be due to the vps host server settings or out dated kernel version.

Prerequisites
Kernel 042stab105.4 or later version
Kernel modules tun, veth and bridge loaded on host (not required since vzctl 4.9 as it loads it automatically)

More infomation at https://openvz.org/Docker_inside_CT

That might be the issue or it could be sometime else.

I got Mailcow docker running on a few vps fine but they are all Kvm vps's.

**Comment by stevesbrain** [comment]
Fairly sure OpenVZ relies on the host OS's kernel, and you cannot run Docker unless you've got kernel support for it (which I believe OpenVZ hosts typically steer clear of). Particularly in your case, as you're using RamNode (pretty sure I tried this with them in the past).

**Comment by Dad-Ju** [comment]
So how can I bring it finaly to Run in need The Mailserver for my TS3 Npl and so on So Please help my I'm not a very Good Geek :D

**Comment by K2rool** [comment]
Have you try to start up docker daemon by running.

<pre>service docker start</pre>

**Comment by Dad-Ju** [comment]
My host say docker Can't run on OpenSV
So I need an KVM Server instead a v-Server. 
This id the answer. 
A Good Thing is when mailcow can run without docker ;D

LG Ju

**Comment by stevesbrain** [comment]
@Dad-Ju There was a version of mailcow that runs without docker (mailcow/mailcow) - but, that's updated far less often (and deprecated for now), so you'd be better off grabbing a KVM VPS (i.e. Linode or something similar).

**Comment by TBK** [comment]
There are also Scaleway, Joyent Triton, packet, DigitalOcean...

**Comment by andryyy** [comment]
And don't forget Servercow. 👍

**Comment by Dad-Ju** [comment]
Thx for help have a Nice Day :) 

#close
