### ISSUE TITLE
Set quarantine notification rate on mailbox creation 

### ISSUE THREAD

**Issue by jonprocter** [mailcow/mailcow-dockerized#3291]
Hi all - using the API to create mailboxes on my Mailcow server, but the quarantine notifications are being sent hourly and users are finding this a bit annoying.

How can I set the default to daily on creation?

Closed the last once since I didn't use a template to make it :)

**Comment by andryyy** [comment]
Hi, 

If it is not a bug report or FR, see the support channels, please. :)

I think what you search can be found in data/web/inc/vars.inc.php

**Comment by jonprocter** [comment]
Ah yep sorry - will do! Thank you :)
