### ISSUE TITLE
Reverse Proxy with Apache2

### ISSUE THREAD

**Issue by PWNYYY** [mailcow/mailcow-dockerized#3292]
Hi,
i use Apache2 and i followed this https://prnt.sc/qshpfb and i dont know how and where to edit this. An Website runs at the main Domain and some other Stuff on different Subdomains. On "mail.myadomain.de" should run MailCow.

What ive done:

I enabled the following Apache2 modules: "a2enmod rewrite proxy proxy_http headers ssl"
and i changed these Ports

HTTP_PORT=**8080**
HTTP_BIND=0.0.0.0

HTTPS_PORT=**8443**
HTTPS_BIND=0.0.0.0

would be great if someone has another tip for me

**Comment by MAGICCC** [comment]
You may need to create a new VHost config in your apache2 sites-available folder

**Comment by PWNYYY** [comment]
> You may need to create a new VHost config in your apache2 sites-available folder

If i copy the code and replace the hostname i cant restart the apache2 server...

i got this error https://prnt.sc/qsi8m0

**Comment by MAGICCC** [comment]
Since this is a bug/issue tracker and not a real help forum I invite you to join our [Telegram ](https://t.me/mailcow)chat or you may read the error logs.
Did you also change the cert path?
