### ISSUE TITLE
External checks in mailcow.conf

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3294]
Good evening,

today i did an update on my mailcow and noticed that there are new external checks.
I already got a SAL, so my question is how to activate those external checks in my mailcow.
After reading through the code i notices an remark that checks - or the addition ob the new option - will only work an unmodified mailcow.conf.

```
# Checks if mailcow is an open relay. Requires a SAL. More checks will follow.
# No data is collected. Opt-in and anonymous.
# Will only work with unmodified mailcow setups.
WATCHDOG_EXTERNAL_CHECKS=y
```

Can i add this option to mailcow.conf by myself?

**Comment by andryyy** [comment]
Hi,

Yes, sorry, I forgot to add it to the config array (as always). :)

Just add it, change it to "y" and run `docker-compose up -d`.

Thank you!!

Edit: It was fixed a few minutes ago.
