### ISSUE TITLE
Invalid key on dkim authentication (apparently only on gmail)

### ISSUE THREAD

**Issue by chmanie** [mailcow/mailcow-dockerized#3296]
When sending emails from my mailcow server to google mail addresses the mails are regarded as spam and always have this header:

```
Authentication-Results: mx.google.com;
       dkim=neutral (invalid public key) header.i=@[my-domain] header.s=dkim header.b=GdGn+mrP;
       arc=fail (invalid key);
       spf=pass (google.com: domain of [my-domain] designates [my-ip-address] as permitted sender) smtp.mailfrom=[my-email];
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=[my-domain]
```

Both https://www.mail-tester.com/ and https://dkimvalidator.com/ state that my dkim signature is fine (and do not lower the score due to that). Is there anything I need to setup for google to not discard my mails? I'm not on any spam list either (but the error saying "invalid public key" doesn't really point to that anyways).

I'm asking here because I couldn't find help anywhere else.

**Comment by andryyy** [comment]
Perhaps your DNS record is not fully propagated. Send me a mail to andre.peters@debinux.de and apeters87@gmail.com, please.

For the future: try to keep support questions in the support channels, please. :)

**Comment by chmanie** [comment]
Sorry for misusing the issue tracker for this. Won't happen again!

**Comment by chmanie** [comment]
The issue apparently was propagation in combination with OVH not allowing 2048 bit keys.

**Comment by andryyy** [comment]
I think you need to manually add it with their wizard. Don't know why, but it works that way. :-D

Thanks for using moocow. :)
