### ISSUE TITLE
Allow sending email with different "From"...

### ISSUE THREAD

**Issue by Balls0fSteel** [mailcow/mailcow-dockerized#3298]
So I have searched the Issue Tracker for clues what happened and why I cannot do this.

Found this ticket:
https://github.com/mailcow/mailcow-dockerized/issues/342
But then I found this commit/reference:
https://github.com/mailcow/mailcow-dockerized/commit/073c6c6e7352a4fa9a1d4b67429e99a0a61998ca
So I was like, phew, it should work. But it doesn't.. :/

Basically what I usually do is...
- I have my sub-domain set up my mail stack, or at any provider.
- I use the log in as SMTP details in my IOT, deployed devices, servers.
- And I use the "From" segment to show where the email is from. Ie.: I can have 5 servers using the same login, but I can mark each. This allows for easy INBOX search, easy Gmail filters, etc. Just great feature. AND you still just have one credential/email account. No need to create 50.

**No clue if I missed an option in the Mailcow UI settings, or Mailcow just handles a standard email setting differently... if it does handle things somehow else, I don't know why it would do that.**

And this works/worked at any shared hosting, any hosting panel, a regular email stack, everywhere. But not on Mailcow. If I try to pull this off, I get the following error:

```
Error Code: 65
Server Response: 553 5.7.1 (custom_from_email@a.domain.com): Sender address rejected: not owned by user iot@a.domain.com
Error Message: recipient address target@receiver.com not accepted by the server
```

I hope my ticket didn't come off as rude or anything - I am just confused/lost.
Thank you.

**Comment by Balls0fSteel** [comment]
Update: I have tried setting the following in mailcow.conf:
`ACL_ANYONE=allow`

But it doesn't help. I found some post online saying it's Postfix's `reject_sender_login_mismatch` directive. But I couldn't find that in `main.cf` either. So I am kinda at a loss.

Please help? :)

**Comment by MAGICCC** [comment]
I suppose you mean this: https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-disable_sender_verification/

`Edit a mailbox and select "Allow to send as *".`

**Comment by Balls0fSteel** [comment]
Man am I stupid... I could swear I went through all the options 5 times already. But I totally missed this. Don't know how. Like I haven't even seen these options, I have no idea how. 😁

Thank you for the swift reply, much appreciated! 
Ps.: At least the ticket will be here if some other silly user can't find it either.
