### ISSUE TITLE
hourly repeating ACME error: Cannot validate any hostnames, skipping Let's Encrypt for 1 hour.

### ISSUE THREAD

**Issue by MarkusP** [mailcow/mailcow-dockerized#3299]
Hi all,
checking the logfiles of my 12 days ago freshly installed mailcow-dockirizes I found this hourly repeating error messages in the ACME logfiles:

![image](https://user-images.githubusercontent.com/1380385/73304999-9898fc80-4219-11ea-831e-7302b3844e18.png)

As you can see in the screenshot the ACME client tells that the A records for the mailservers hostname, the autoconfig and the autodiscover are found on the DNS.
But validation of any of these hostnames isnt possible.

If I try to check DNS information for that hostnames I see this:

![image](https://user-images.githubusercontent.com/1380385/73305486-7b186280-421a-11ea-875b-d59bb5556244.png)

The same for the other hostnames:

![image](https://user-images.githubusercontent.com/1380385/73305613-be72d100-421a-11ea-841f-d8829ca177c3.png)

I am also able to "grep" the mailservers address via http / https with curl, as you can see here in the screenshot:

**http://mailserver....**
![image](https://user-images.githubusercontent.com/1380385/73305855-478a0800-421b-11ea-85c4-1475f7dfb435.png)

**https://mailserver....**
![image](https://user-images.githubusercontent.com/1380385/73305991-933cb180-421b-11ea-8d8d-c865c871d777.png)

My mailcow.conf file looks like this:

```

root@mailserver:/opt/mailcow-dockerized# more mailcow.conf 
# ------------------------------
# mailcow web ui configuration
# ------------------------------
# example.org is _not_ a valid hostname, use a fqdn here.
# Default admin user is "admin"
# Default password is "moohoo"

MAILCOW_HOSTNAME=mailserver.*****-*****.de

# ------------------------------
# SQL database configuration
# ------------------------------

DBNAME=mailcow
DBUSER=mailcow

# Please use long, random alphanumeric strings (A-Za-z0-9)

DBPASS=****************************
DBROOT=****************************

# ------------------------------
# HTTP/S Bindings
# ------------------------------

# You should use HTTPS, but in case of SSL offloaded reverse proxies:
# Might be important: This will also change the binding within the container.
# If you use a proxy within Docker, point it to the ports you set below.

HTTP_PORT=80
HTTP_BIND=0.0.0.0

HTTPS_PORT=443
HTTPS_BIND=0.0.0.0

# ------------------------------
# Other bindings
# ------------------------------
# You should leave that alone
# Format: 11.22.33.44:25 or 0.0.0.0:465 etc.
# Do _not_ use IP:PORT in HTTP(S)_BIND or HTTP(S)_PORT

SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
DOVEADM_PORT=127.0.0.1:19991
SQL_PORT=127.0.0.1:13306
SOLR_PORT=127.0.0.1:18983

# Your timezone

TZ=Europe/Berlin

# Fixed project name

COMPOSE_PROJECT_NAME=mailcowdockerized

# Set this to "allow" to enable the anyone pseudo user. Disabled by default.
# When enabled, ACL can be created, that apply to "All authenticated users"
# This should probably only be activated on mail hosts, that are used exclusivly by one organisation.
# Otherwise a user might share data with too many other users.
ACL_ANYONE=disallow

# Garbage collector cleanup
# Deleted domains and mailboxes are moved to /var/vmail/_garbage/timestamp_sanitizedstring
# How long should objects remain in the garbage until they are being deleted? (value in minutes)
# Check interval is hourly

MAILDIR_GC_TIME=1440

# Additional SAN for the certificate
#
# You can use wildcard records to create specific names for every domain you add to mailcow.
# Example: Add domains "example.com" and "example.net" to mailcow, change ADDITIONAL_SAN to a value like:
#ADDITIONAL_SAN=imap.*,smtp.*
# This will expand the certificate to "imap.example.com", "smtp.example.com", "imap.example.net", "imap.example.
net"
# plus every domain you add in the future.
#
# You can also just add static names...
#ADDITIONAL_SAN=srv1.example.net
# ...or combine wildcard and static names:
#ADDITIONAL_SAN=imap.*,srv1.example.com
#

ADDITIONAL_SAN=

# Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n

SKIP_LETS_ENCRYPT=n

# Create seperate certificates for all domains - y/n
# this will allow adding more than 100 domains, but some email clients will not be able to connect with alternat
ive hostnames
# see https://wiki.dovecot.org/SSL/SNIClientSupport
ENABLE_SSL_SNI=n

# Skip IPv4 check in ACME container - y/n

SKIP_IP_CHECK=n

# Skip HTTP verification in ACME container - y/n

SKIP_HTTP_VERIFICATION=n

# Skip ClamAV (clamd-mailcow) anti-virus (Rspamd will auto-detect a missing ClamAV container) - y/n

SKIP_CLAMD=n

# Skip Solr on low-memory systems or if you do not want to store a readable index of your mails in solr-vol-1.

SKIP_SOLR=n

# Solr heap size in MB, there is no recommendation, please see Solr docs.
# Solr is a prone to run OOM and should be monitored. Unmonitored Solr setups are not recommended.

SOLR_HEAP=1024

# Enable watchdog (watchdog-mailcow) to restart unhealthy containers (experimental)

USE_WATCHDOG=n

# Allow admins to log into SOGo as email user (without any password)

ALLOW_ADMIN_EMAIL_LOGIN=n

# Send notifications by mail (no DKIM signature, sent from watchdog@MAILCOW_HOSTNAME)
# Can by multiple rcpts, NO quotation marks

#WATCHDOG_NOTIFY_EMAIL=a@example.com,b@example.com,c@example.com
#WATCHDOG_NOTIFY_EMAIL=

# Notify about banned IP (includes whois lookup)
WATCHDOG_NOTIFY_BAN=y

# Max log lines per service to keep in Redis logs

LOG_LINES=9999

# Internal IPv4 /24 subnet, format n.n.n (expands to n.n.n.0/24)

IPV4_NETWORK=172.22.1

# Internal IPv6 subnet in fc00::/7

IPV6_NETWORK=fd4d:6169:6c63:6f77::/64

# Use this IPv4 for outgoing connections (SNAT)

#SNAT_TO_SOURCE=

# Use this IPv6 for outgoing connections (SNAT)

#SNAT6_TO_SOURCE=

# Create or override API key for web ui
# You _must_ define API_ALLOW_FROM, which is a comma separated list of IPs
# API_KEY allowed chars: a-z, A-Z, 0-9, -

#API_KEY=
#API_ALLOW_FROM=172.22.1.1,127.0.0.1

# mail_home is ~/Maildir
MAILDIR_SUB=Maildir

# SOGo session timeout in minutes
SOGO_EXPIRE_SESSION=480
```

I have no idea what is going wrong... anyone can help me?

Thanks in advance!
Markus

**Comment by andryyy** [comment]
Issue template.

```
echo test > data/web/.well-known/acme-challenge/test ; source mailcow.conf ; docker-compose exec acme-mailcow curl -4L http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
```

What's the output?

I will start to close invalid issues, so please use the template. Always. :) If it is a support question, don't open a bug report, but join the support channels. :) Thanks.

**Comment by MarkusP** [comment]
Good morning, I am really sorry for bothering... and not filling out this the correct way... will do better in the future!

I did what you asked for in your comment and here is the output:

![image](https://user-images.githubusercontent.com/1380385/73336720-dc6c2000-4272-11ea-9b70-7c4b61e9a524.png)

If I do manually what your little snippet does, the output looks like this:

![image](https://user-images.githubusercontent.com/1380385/73336852-3c62c680-4273-11ea-9355-f9d0793d99d6.png)

any idea?

**Comment by MarkusP** [comment]
here are some additional informations... sorry for not delivering them with the last post...

```
root@mailserver:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
root@mailserver:/opt/mailcow-dockerized# 
root@mailserver:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
root@mailserver:/opt/mailcow-dockerized# 

```

In the next console you can see that doing the curl directly the test file can be accessed.
But doing the curl command with docker-compose exec acme-mailcow the command failed due to time out
```
root@mailserver:/opt/mailcow-dockerized# 
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; curl -4L http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
test


root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; docker-compose exec acme-mailcow curl -4L http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
curl: (7) Failed to connect to mailserver.******-****.de port 80: Operation timed out
root@mailserver:/opt/mailcow-dockerized# 

```

**Comment by andryyy** [comment]
Could be a NAT reflection issue then. I don't know if you use ufw or firewalld etc. :)

**Comment by MarkusP** [comment]
Hi André, dont know why this should be a NAT reflection issue... can you please explain what the "docker-compose exec acme-mailcow" command does that stands "in front" of the curl command? the plain curl command works as expected as you can see in my last post...

I am a little bit lost...:-(

TIA
Markus

**Comment by andryyy** [comment]
It is a firewall blocking these requests. I cannot help with that, sorry. You can try the channel and post all information asked in the issue template. I still don't know wether or not you use ufw, firewalld or your iptables rules. All that is asked in the issue template.

**Comment by MarkusP** [comment]
Hi all, as mentioned, I am really really sorry for starting this ticket at the wrong place, as wrong type and with missing informations!!! :-( :-( I will do better next time!

Maybe one last chance to get some help from you? I think I found the reason... but dont know how to solve this...

Here is what I found out in the meanwhile... (shame shame shame on me, that I didnt see that earlier)

If I am doing a classical dig command to resolve the A Record of the mailservers FQDN I do get this information back to the shell:
```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; dig ${MAILCOW_HOSTNAME}

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> mailserver.*****-*****.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54768
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mailserver.*****-*****.de.	IN	A

;; ANSWER SECTION:
mailserver.*****-*****.de. 59 IN	A	172.16.10.115  <<<<<==== local ip - correct

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)  <<<<<===== unbound dns service?
;; WHEN: Wed Jan 29 12:32:55 CET 2020
;; MSG SIZE  rcvd: 73

root@mailserver:/opt/mailcow-dockerized# 

```

But when I do the same dig command with that "docker-compose exec acme-mailcow" in front of it, the result of the returned A Record is different... it gives me the externel public ip address... also the DNS server that answers this request is not 127.0.0.53#53 (as above) but it is 127.0.0.11#53

```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; docker-compose exec acme-mailcow dig ${MAILCOW_HOSTNAME}

; <<>> DiG 9.14.8 <<>> mailserver.*****-*****.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31742
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mailserver.*****-*****.de.	IN	A

;; ANSWER SECTION:
mailserver.*****-*****.de. 54094 IN	A	195.xxx.yyy.37  <<<<==== public ip gets returned

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)  <<<<===== this is not unbound?!
;; WHEN: Wed Jan 29 12:29:14 CET 2020
;; MSG SIZE  rcvd: 73

root@mailserver:/opt/mailcow-dockerized# 
```

The problem with that public ip address is, that a connection to the mailserver thru its public ip address from within the internal network is "von hinten durch die brust ins auge" (as we say in german) - means: the companies firewall does not allow requests from internal network to internal services thru the corresponding external ip addresses...

**Comment by MarkusP** [comment]
What I found out in the meanwhile is that the whole magic happens in the two files `acme.sh` and `functions.sh` within path `/opt/mailcow-dockerized/data/Dockerfiles/acme`.

All depends, in the end, on the function `verify_challenge_path()` which does a curl to check the presence of one file and return 0 or 1 depending on if the file can be retrieved or not.

```
  if [[ "$(curl --insecure -${2} -L http://${1}/.well-known/acme-challenge/${RANDOM_N} --silent)" == "${RANDOM_N}"  ]]; then
    rm /var/www/acme/${RANDOM_N}
    return 0
  else
    rm /var/www/acme/${RANDOM_N}
    return 1
  fi
```

What I do not understand is: curl needs to resolve $1, what is e.g. equal to ${MAILCOW_HOSTNAME}. When I do the curl command manually from a bash shell logged in into the mailserver as root-user, the command completed correct:
```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; curl --insecure -4 -L http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test --silent
test
```

But doing the same curl command with the leading `docker-compose exec acme-mailcow` the curl command fails.
```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; docker-compose exec acme-mailcow curl -4L http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/test
curl: (7) Failed to connect to mailserver.****-*****.de port 80: Operation timed out

```
This is because the acme container seems to resolve the DNS information for ${MAILCOW_HOSTNAME} to a different IP, the public ip, of the mailserver, while the 'normal' dig command resolves the internal private IP of the mailserver.
```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; docker-compose exec acme-mailcow dig A ${MAILCOW_HOSTNAME} +short
195.xxx.yyy.37
```
```
root@mailserver:/opt/mailcow-dockerized# source mailcow.conf ; dig A ${MAILCOW_HOSTNAME} +short
172.16.10.115
```

I do not understand why the acme container resolves the mailserver FQDN to a different IP address than the normal dig command from a root bash shell.

Please help! Any kind of tip or hint is really(!) appreciated!
Thanks!
Markus

**Comment by MarkusP** [comment]
Hi André,
I "solved" the problem with a workaround (for me it is a workaround, you, maybe, will call it a solution :-) ).

What I have done is to create a so called "busines application rule" in my sophos xg firewall cluster with DNAT/Full NAT profile and configured it so, that the internal clients (here the acme container running on the mailserver vm) are allowed to access the mailserver on port 80 but thru the external ip address (its still "vor hinten durch die brust ins auge").

I think the function verify_challenge_path() should be modified to catch such situations

**Comment by darksnakezero** [comment]
Stumbled in the same error and the solution is now to disable the check by setting 
`SKIP_HTTP_VERIFICATION=y`.

After a `docker compose up -d`, getting the LE certificates worked like a charm.

Be careful, this only solves the problem, when your acme path IS actually reachable from the internet, but your internal routing does not work 100% correctly and it is not reachable internally.
