### ISSUE TITLE
Questions about updates

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#33]
Hi, 

first, thank you for your great work!

Can I always update without hesitation, if I stick to your rules (https://mailcow.email/dockerized/?c=I.%20Installation&p=Update_mailcow_dockerized.md)? Or do I have to pay attention to something?

Thanks!

**Comment by marrco** [comment]
i tried to update but no luck: 

```
root@myserver:~/mailcow-dockerized# git pull
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 54 (delta 14), reused 8 (delta 8), pack-reused 22
Unpacking objects: 100% (54/54), done.
From https://github.com/andryyy/mailcow-dockerized
   c9d44a6..830510f  master     -> origin/master
   2738686..432246b  dev        -> origin/dev
Updating 5fa7941..830510f
error: Your local changes to the following files would be overwritten by merge:
        data/conf/postfix/main.cf
        data/web/inc/header.inc.php
        data/web/lang/lang.en.php
Please, commit your changes or stash them before you can merge.
Aborting

```

There's also a forum,mailcow but none answered to me there. It looks like the dockerized version is quite new, so we still have to learn how to use it.

**Comment by rebek86** [comment]
@marrco I think you have made changes to the main.cf, header.inc.php, and lang.en.php. I have made no changes to files from the git repository and get no error with a git pull...

My question: What happens after a git pull and container update. Is it possible that paths are changed and then, e.g. old Mails are in the wrong folder, etc.?

**Comment by marrco** [comment]
@rebek86 you're absolutely right. But now i have no idea about how to merge changes and update my mailcow.dockerized.

i followed the example here: https://mailcow.email/dockerized/?c=IV.%20Usage%20and%20Examples&p=Anonymize_mail_header.md and modified that file. 

Same for the 2 other files. I'm still trying to learn how (mailcow.)docker works. How to change files, backup config and data, or move my installation to a different host,

**Comment by andryyy** [comment]
Hi, I updated the manual: https://mailcow.email/dockerized/?c=I.%20Installation&p=Update_mailcow_dockerized.md :)

**Comment by rebek86** [comment]
@andryyy What happens after a git pull and container update. Is it possible that paths are changed and then, e.g. old Mails are in the wrong folder, etc.?

**Comment by andryyy** [comment]
No, this won't happen.

**Comment by marrco** [comment]
but other problems may happen. It looks like i'm missing a step somewhere: connecting to the updated site i don't see exptected webpage (the one with the modified header.inc - lang.inc) but the original page after the following lines:

```
<<<<<<< HEAD ======= >>>>>>> 9423e9e89e5c74d643904a40bdccf228476241ad <<<<<<< HEAD ======= >>>>>>> 9423e9e89e5c74d643904a40bdccf228476241ad <<<<<<< HEAD
=======
>>>>>>> 9423e9e89e5c74d643904a40bdccf228476241ad

```

my guess is that before starting the dockerized image i have an additional step to follow. I'm still trying to learn, this is my first dockerized setup and i have very little experience with git too.

(as a 'fix' i just manually fixed the 3 modified files, and deleted the .git directory, so i can start clean next time. I still guess i have to commit the changes i did to the updated config)

**Comment by rebek86** [comment]
@andryyy Thanks! :-)

**Comment by andryyy** [comment]
@marrco Your changes were not merge-able. Did it work for you?

**Comment by marrco** [comment]
@andryyy yes, no problems, i had backups. Changes were really minor ie. in language_en "Open SOGo -> Open WEBMAIL SOGo" then i changed the favicon.png to ico and finally i tried to follow the example in the manual to anonymize postfix mail headers. Just experimenting on a test computer. But that's quite an issue because (until i fully understand that part) i finished with a not-working server.
