### ISSUE TITLE
 Could not connect to Redis at redis-mailcow:6379: Host is unreachable

### ISSUE THREAD

**Issue by fiercedMonkey** [mailcow/mailcow-dockerized#3300]
I'm getting the following offer after a clean setup of mailcow by using
`docker-compose logs --tail=200 php-fpm-mailcow` which results in 502 in the frontend:

` Could not connect to Redis at redis-mailcow:6379: Host is unreachable`

![grafik](https://user-images.githubusercontent.com/15922918/73311825-b66d5e00-4227-11ea-83d5-212c4b69b1d3.png)

Already deleted all containers and repeated the setup, according to the official docs. Same result.

Seems like the redis-container is running at all.

![grafik](https://user-images.githubusercontent.com/15922918/73311796-a190ca80-4227-11ea-8899-b70757269131.png)

**Comment by Adorfer** [comment]
no unbound-mailcow_1? no netfilter-mailcow_1?
so probablly not DNS, no routing between the containers.
