### ISSUE TITLE
Block IPs from AbuseIPDB Blacklist

### ISSUE THREAD

**Issue by MalteKiefer** [mailcow/mailcow-dockerized#3302]
Good morning,
It would be nice if there is a way to block the IP addresses on the [AbuseIPDB](https://www.abuseipdb.com/) blacklist. To do so you have to have a field in the admin interface where you can enter the API code.

Then maybe a cronjob that fetches the list once a week in plaintext format and puts it into the firewall and blocks it.

**Comment by andryyy** [comment]
Do this server-side or on a firewall, please. :)

**Comment by dragoangel** [comment]
pfSense with pfblockerNG for example allow you create self updating firewall aliases and use them later in your deny/allow rules.

**Comment by Ganzjahresgriller** [comment]
No one interested in doing this?
