### ISSUE TITLE
Recover from bad update - relink mailbox with previous vmail data

### ISSUE THREAD

**Issue by aurixtech2** [mailcow/mailcow-dockerized#3303]
Hey,

I'm trying to recover from what seems to be a borked update. At a guess, it looks like some images/volumes got pruned while some containers were stopped when they shouldn't have been.

From what i can tell, all my domain and mailbox data has been deleted. I can recreate the domains and mailboxes, but i'm concerned about losing the existing mailbox data.

Is there any way to recreate the domains and mailboxes and then populating them with the existing mails stored in the vmail volume?

I'm having some other issues, but will list them separately.

**Comment by andryyy** [comment]
Please don't use the issue tracker for support questions. 

The update process does not prune or delete volumes. Ever.

**Comment by aurixtech2** [comment]
What is the procedure for support questions please?

**Comment by marrco** [comment]
> What is the procedure for support questions please?

I'd suggest https://www.servercow.de/mailcow?lang=en#support  or the Telegram channel

**Comment by HthSolid** [comment]
> Hey,
> 
> I'm trying to recover from what seems to be a borked update. At a guess, it looks like some images/volumes got pruned while some containers were stopped when they shouldn't have been.
> 
> From what i can tell, all my domain and mailbox data has been deleted. I can recreate the domains and mailboxes, but i'm concerned about losing the existing mailbox data.
> 
> Is there any way to recreate the domains and mailboxes and then populating them with the existing mails stored in the vmail volume?
> 
> I'm having some other issues, but will list them separately.

I think this would be of general interest to know how such data can be recovered
