### ISSUE TITLE
Wrong (incomplete) ip address within the logs

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#3305]
Hi,

It seems the last digits of the ip address all over the (static/in-memory) logs is "0" - anytime.
Is this on purpose for some privacy reasons or so?

Regards

**Comment by andryyy** [comment]
Hi,

Where?

**Comment by andryyy** [comment]
You mean like that? => `104.248.250.0`

Check `data/web/inc/vars.inc.php` and `ANONYMIZE_IPS`. :)

**Comment by lalaluuu** [comment]
Yeah, that's it - thanks ;-)
