### ISSUE TITLE
Local MTA on Docker host: Relay incoming mail to local MTA (instruction missing)

### ISSUE THREAD

**Issue by mamair** [mailcow/mailcow-dockerized#3306]
I just installed sympa as mailing list server.

Outgoing mail work well with the instruction at ["Local MTA on Docker host"](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/)

If I want to send mail to sympa mailinglist I get mails back with "mail for lists.xxx.xx loops back to myself

I cant find any instruction how mailcow relays mail to local mta.

Plaese help!

Martin

**Comment by Adorfer** [comment]
i guess this not supported to install a second mta on the same VM as mailcow.

**Comment by dragoangel** [comment]
You can set next hop in transport maps if I understand your question correctly

**Comment by mamair** [comment]
If I can send mails from a second MTA via mailcow I should be able to receive mails with the second MTA via mailcow.

At  "Routing" /admin?lang=en#tab-routing I find following information:

"Define sender-dependent transports to be able to select them in a domains configuration dialog." But nothing about receiver-dependent transports.

There is also a file  data/conf/postfix/local_transport

There is short info about "custom transport maps" - only for outgoing mails?

https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-custom_transport/

If routing of incoming mails to a second MTA is not supported yet, then my issue should be a feature request!

If its not supported via mailcow webinterface there should be a way to route (or however the right term is) incoming mails of specific domains or subdomains (all mailinglists have list.domain subdomain) with the postfix settings of the postifx container. If I have more time, I will take a look into postfix manuals ...

**Comment by mamair** [comment]
Hm, as I read, "transport maps" are only for outgoing mails. So there should be something else for distributing incoming mails ...

**Comment by andryyy** [comment]
I think there is a better chance to get an answer in the Telegram channel. :) This is for bugs and feature requests.

**Comment by mamair** [comment]
Missing documentation is a feature request (for me). 

OK, I will try out telegram

**Comment by rkl110** [comment]
To get it work, I used Transport-Maps, Routing and local postfix mta ([Help for Local MTA-Setup](https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-local_mta/)).

Routing -> Transport-Maps

| Destination  | Nexthop |
| ------------- | ------------- |
| lists.example.org  | 172.22.1.1:2525  |

Configuration -> Forwarding Hosts
| Host | Spamfilter |
| ------------- | ------------- |
| External IP  | Disabled  |
