### ISSUE TITLE
Docker for Mac: user-defined bridge network -> postfix no outbound connection?

### ISSUE THREAD

**Issue by chatelp** [mailcow/mailcow-dockerized#3310]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

Mailcow-dockerized is deployed on Docker for Mac. All services are running correctly. But the postfix service is not able to send any mail (connection timeout). It can receive though. Since all services are connected on a user-defined bridge network (mailcow-network) and networking in Docker for Mac is very different from linux platform (due to the virtualization layer), what could be the root of the problem?

I already checked this previous bug report that looks similar (https://github.com/mailcow/mailcow-dockerized/issues/282) but solution only applies to linux (no docker0 interface on the mac nor iptables).

I connected busybox to the aforementioned bridge network and ping is OK. So it looks the bridge has outside connectivity:
docker run -it busybox sh --network=mailcowdockerized_mailcow-network
-> ping 8.8.8.8 -> OK

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | OSX |
| Docker Version (`docker version`) | Docker version 19.03.5, build 633a0ea |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019 |
| Reverse proxy (custom solution) | Using traefik on the nginx service |

**Comment by mkuron** [comment]
I have no idea how networking works in Docker for Mac these days. It's a Linux VM running on macOS and probably either NATs the Linux VM (in addition to the NAT done by Docker) or relies on the userland proxy. In the former case, IPv6 will never work, while in the latter case the source IP doesn't get passed through and DNSBLs won't work, your server will be an open relay, etc.

If you really want to run Mailcow on a Mac, don't use Docker for Mac. Instead, set up a Linux VM in Virtualbox/VMWare/Parallels and use bridged networking so that your VM gets an IP address on your real network.

**Comment by chatelp** [comment]
thanks for the feedback @mkuron
