### ISSUE TITLE
Postfix whitelist if domain or ip is listed in sorbs

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#3313]
Hello,

  I have sender whom are blacklisted because wanadoo dsl ip is listed in sorbs list. So when I read this https://help.endian.com/hc/en-us/articles/218144758-RBL-Whitelisting-in-Postfix I think it is possible to whitelist domain or IP of the client.

How could I do that whith mailcow ?

Regards

**Comment by andryyy** [comment]
Added data/conf/postfix/custom_postscreen_whitelist.cidr :)

**Comment by mkuron** [comment]
Is this IP address in a `Received` header? If so, we should probably do the same as for Spamhaus in #3311.

**Comment by andryyy** [comment]
Postscreen does not check that. It is the connecting IP. :)

**Comment by guidtz** [comment]
Thanks does it needs to restart postfix container ?

**Comment by andryyy** [comment]
I don't think so.

**Comment by guidtz** [comment]
For information it's not needed to restart postfix.

Thanks
