### ISSUE TITLE
Option to skip restart mailcow after running update.sh

### ISSUE THREAD

**Issue by jaltek** [mailcow/mailcow-dockerized#3317]
It would be nice to have an option (e.g. parameter or environment variable) to skip the restart of mailcow after running the updates via [update.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh).

Line: https://github.com/mailcow/mailcow-dockerized/blob/a177499130b3b86586113aee860de45a80d1e45a/update.sh#L473

Use case: Sometimes I combine updates for mailcow with updates for the OS which require a reboot, so I simply would update mailcow without restarting the containers because they will be started automatically at boot.

**Comment by mkuron** [comment]
If you just reboot the system (or restart the Docker daemon), it will still use the old images. You actually need to do `docker-compose up` for it to use the freshly-pulled images.

**Comment by jaltek** [comment]
@mkuron Hi. I think you misunderstood that. If you combine a OS update (which requires a reboot sometimes) with an update of mailcow, the case will be the following:

- Run update.sh which stops all mailcow containers and restart them after the update
- Run OS updates, shutdown/reboot (which **again** stops the containers that have just been started)
- Bootup which starts **again** mailcow.

An optimized way would be:
- Run update.sh with "--dont-restart" so that the mailcow containers will no be restarted (no "docker-compose up -d")
- Run OS updates, reboot
- Bootup starts automatically the new docker containers/images.

**Comment by andryyy** [comment]
Some files, that are mounted, may be removed or replaced, so mailcow needs to be stopped, when it is upgraded.
Before applying code changes, mailcow always needs to be stopped.
Do not run updated code with outdated images!

**Comment by jaltek** [comment]
Which is okay :)
Again: Mailcow **will** be stopped and started **during the reboot.**
I just want to prevent multiple restarts of mailcow.

**Comment by andryyy** [comment]
Ah, it will be stopped but just not started after the upgrade process? That's pretty easy to implement.

**Comment by andryyy** [comment]
And https://github.com/mailcow/mailcow-dockerized-docs/commit/ee781d9f07f4673c9a08cd1e1c0475fed1bd44e1

**Comment by jaltek** [comment]
Awesome :+1: :1st_place_medal:

**Comment by mkuron** [comment]
> Bootup starts automatically the new docker containers/images.

That's not true. When the Docker daemon restarts, it always restarts the containers as they were running previously. That is, with the old image. To get the new images, you have to do `docker-compose up` at some point.

**Comment by jaltek** [comment]
> That's not true. When the Docker daemon restarts, it always restarts the containers as they were running previously. That is, with the old image. To get the new images, you have to do `docker-compose up` at some point.

Absolutely right, sorry. Nevertheless with the new option you save a needless startup of mailcow as you plan to reboot the machine.
