### ISSUE TITLE
SOGo shows _$notjunk flags

### ISSUE THREAD

**Issue by dofl** [mailcow/mailcow-dockerized#3318]
Within SOGo there are two very large __$notjunk_ and _notjunk_ flags in e-mails that come from outside of the mailserver domains. Internal e-mail does not have this flag. I haven't done any customization on the server.

I don't know when it happend, I haven't seen it earlier. Here is a screenshot to clearify:

<img width="833" alt="Screenshot 2020-02-07 at 19 04 12" src="https://user-images.githubusercontent.com/8161021/74054139-b286cc00-49dd-11ea-87e6-f011bfdebea9.png">

I've Googled to find a solution, but I only found a [post](https://lists.inverse.ca/sogo/arc/users/2016-10/msg00141.html) from 2016 with no solution. 

Anyone has the same issue?

**Comment by andryyy** [comment]
An IMAP client is setting these flags.

**Comment by dofl** [comment]
Thanks for the quick answer

**Comment by wryfi** [comment]
@dofl did you ever learn any more about where these came from?  I'm migrating from zimbra and seeing the same tags appear in SoGo, but I can't see any evidence in any of my IMAP clients or the message headers to suggest why.

**Comment by dofl** [comment]
In my case I think they are Outlook flags as all my clients where Outlook / Exchange users before.
