### ISSUE TITLE
Certificate Validation, via https rather than http

### ISSUE THREAD

**Issue by psyciknz** [mailcow/mailcow-dockerized#3321]
**Is your feature request related to a problem? Please describe.**
I have port 443 open on my firewall running through caddy to my mailcow instance.

I'm trying to get cert validation working via mailcow directly (it's working through caddy for mail.mydomain.com and autoconfig/autodiscover - and if I manually copy the certs over for one of my domains its, happy.  And I would be happy to do that automatically, but I haven't found instructions for merging the two domains into one cert which is what mailcow seems to expect).

So the flip side is I've got dns validation working, but it fails on the: 
```
'http://mail.mydomain.com/.well-known/acme-challenge/wITvagPyNaYgnPKwvS04VxxBt8mULTHMxYDymExhsbs
```
As port 80 is not open.  Is there an option for getting the acme client to try and get this url via https?

**Comment by andryyy** [comment]
Aloha, you will need to open port 80. :/

André

**Comment by psyciknz** [comment]
Thanks.   I found a way around it with the reverse proxy.

**Comment by andryyy** [comment]
:) Just to not confuse anybody reading this: you will still need to have port 80 available somewhere. Using a reverse proxy with port 80 and forward to your mailcow does work indeed.
