### ISSUE TITLE
Disable internal emails

### ISSUE THREAD

**Issue by rowangg** [mailcow/mailcow-dockerized#3322]
On my mailcow server I have my domain name (for this purpose I shall say example.com)

I only want to use it to send mail for this particular domain and am not using it to receive mail and use gsuite to receive emails.

Mailcow sends email fine to all domain, except my own, it gets stuck saying

NOQUEUE: reject: RCPT from ws1.xxxxxx.technology[77.68.xx.xxx]: 550 5.1.1 <rowan@example.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<noreply@example.com> to=<rowan@example.com> proto=ESMTP helo=<example.com>
before it can reach gsuite.

before it goes to gsuite.

Can I disable it internally emailing it?

**Comment by mkuron** [comment]
I guess this is a duplicate of #630.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/74130357-298cb200-4be2-11ea-9812-8130f5565975.png)

This?

**Comment by rowangg** [comment]
> ![image](https://user-images.githubusercontent.com/2972950/74130357-298cb200-4be2-11ea-9812-8130f5565975.png)
> 
> This?

Would this make it so that when noreply@domain.com tried to email rowan@domain.com it will not send locally and will preform an MX lookup and deliver it?

**Comment by mkuron** [comment]
No, to get MX lookups on local domains, you would need to disable local delivery, which #630 asks about. That's not currently implemented in Mailcow as it requires running two Postfix instances.

**Comment by rowangg** [comment]
> No, to get MX lookups on local domains, you would need to disable local delivery, which #630 asks about. That's not currently implemented in Mailcow as it requires running two Postfix instances.

Would this work for me? On there they are different domains, I have one

**Comment by mkuron** [comment]
This would work for one. For example, if you have the same domain on a secondary mail server (Mailcow) and a primary mail server (Google/Exchange/Zoho/...) and want everything to be delivered to the primary server. That's called dual delivery or split delivery and you usually use it if you have users divided between both servers and the primary server is configured to redirect messages for certain users to the secondary server.

**Comment by rowangg** [comment]
Okay, thanks.

Is there a guide on how to do this?

**Comment by mkuron** [comment]
No, but #630 has some links. If you figure it out, please write up documentation and/or submit a pull request.

**Comment by rowangg** [comment]
I have fixed the issue without setting up an additional postifx server

In /opt/mailcow-dockerized/data/conf/postfix/custom_transport.pcre I simply added zentorahoting.com smtp:[aspmx.l.google.com

**Comment by mkuron** [comment]
Ah yes, that would work since you don't need any local delivery.
