### ISSUE TITLE
Tagged mails filed into folder, but not respecting upper-/lower-case tag

### ISSUE THREAD

**Issue by Miyamoto72** [mailcow/mailcow-dockerized#3323]
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I set Mailcow to file tagged mails into the folder given by the tag. I use a folder name containing uppercase letter only - but instead of filing the mail into folder "ABC" it gets filed into a new folder "Abc"

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Send a mail tagged with the name of an strictly uppercase folder and check where it gets filed.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.3 |
| Is Apparmor, SELinux or similar active? | AppArmor is enabled, SELinux is not |
| Virtualization technlogy (KVM, VMware, Xen, etc) | none |
| Server/VM specifications (Memory, CPU Cores) | E5640  @ 2.67GHz, 16 Cores, 19GB RAM |
| Docker Version (`docker version`) | Docker version 19.03.5, build 633a0ea838 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.4, build 8d51620a
| | docker-py version: 4.1.0 |
| | CPython version: 3.7.5 |
| | OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019 |
| Reverse proxy (custom solution) | ports NATted by router, webinterface proxied by NGinX following mailcow docs |

Further notes:
 - Output of `git diff origin/master` is empty
 ```
root@mail:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
root@mail:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.65.69
151.101.129.69
151.101.193.69
151.101.1.69 
```
 General logs:

**Postfix**:
```
postfix-mailcow_1    | Feb 10 12:13:09 mail postfix/submission/smtpd[392]: connect from i577AFDC9.versanet.de[87.122.253.201]
postfix-mailcow_1    | Feb 10 12:13:09 mail postfix/submission/smtpd[392]: Anonymous TLS connection established from i577afdc9.versanet.de[87.122.253.201]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
postfix-mailcow_1    | Feb 10 12:13:09 mail postfix/submission/smtpd[392]: F120024068C: client=i577AFDC9.versanet.de[87.122.253.201], sasl_method=PLAIN, sasl_username=user@example.com
postfix-mailcow_1    | Feb 10 12:13:10 mail postfix/cleanup[397]: F120024068C: message-id=<1702ecd8da0.27f6.b82469358ea0dfc66cf15413b48d62e5@example>
postfix-mailcow_1    | Feb 10 12:13:10 mail postfix/qmgr[346]: F120024068C: from=<user@example.com>, size=974, nrcpt=1 (queue active)
postfix-mailcow_1    | Feb 10 12:13:10 mail postfix/submission/smtpd[392]: disconnect from i577AFDC9.versanet.de[87.122.253.201] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
postfix-mailcow_1    | Feb 10 12:13:10 mail postfix/lmtp[398]: F120024068C: to=<user+ABC@example.com>, relay=dovecot[fd4d:6169:6c63:6f77::10]:24, delay=0.55, delays=0.17/0.02/0.02/0.34, dsn=2.0.0, status=sent (250 2.0.0 <user+ABC@example.com> ui6hCcY6QV5WAQAAmHdZUA Saved)
postfix-mailcow_1    | Feb 10 12:13:10 mail postfix/qmgr[346]: F120024068C: removed
```
Dovecot:
```
dovecot-mailcow_1    | Feb 10 12:17:02 mail dovecot: lmtp(461): Connect from 172.22.1.12
dovecot-mailcow_1    | Feb 10 12:17:02 mail dovecot: lmtp(user@example.com)<461><2volFa47QV7NAQAAmHdZUA>: sieve: msgid=<1702ed117e0.27f6.b82469358ea0dfc66cf15413b48d62e5@schorers.org>: fileinto action: stored mail into mailbox 'INBOX/Abc'
dovecot-mailcow_1    | Feb 10 12:17:02 mail dovecot: lmtp(461): Disconnect from 172.22.1.12: Client has quit the connection (state=READY)
dovecot-mailcow_1    | Feb 10 12:17:02 mail dovecot: indexer-worker(user@example)<464><2volFa47QV7NAQAAmHdZUA:oI0kJK47QV7QAQAAmHdZUA>: Indexed 1 messages in INBOX/Gmx (UIDs 8..8)
dovecot-mailcow_1    | Feb 10 12:17:03 mail dovecot: indexer-worker(user@example.com)<464><aG/bvjaeqtJXev3J:qLUNOq47QV7QAQAAmHdZUA>: Indexed 1 messages in Sent (UIDs 6161..6161)
```

**Comment by Miyamoto72** [comment]
Mailcow has been updated to latest version to submitting the issue.

**Comment by andryyy** [comment]
Yes, that's intended. 

https://github.com/mailcow/mailcow-dockerized/blob/9d04d0ee4a0b368df5d90b0d8f989bd71767e483/data/conf/dovecot/global_sieve_after#L18

You can remove that line, should fix it. :)
Probably a bad idea to change it globally. That would break many setups.

**Comment by Miyamoto72** [comment]
Maybe this could be a checkbox in the webinterface? Generally speaking this should be mentioned in the docs somewhere appropriate, I'd say.

**Comment by andryyy** [comment]
Too complex for this little line. :/

Can you create a PR for this change in the docs? That would be very welcome. :)

André

**Comment by Miyamoto72** [comment]
I'll try my best to do a PR.

One more thing: 
I removed that line, but now the sieve script execution fails for reasons I don't understand:

```
dovecot-mailcow_1    | Feb 10 12:47:04 mail dovecot: lmtp(182): Connect from fd4d:6169:6c63:6f77::f
dovecot-mailcow_1    | Feb 10 12:47:05 mail dovecot: lmtp(user@example.com)<182><yJ06ALlCQV62AAAAmHdZUA>: Error: sieve: msgid=<1702eec8b38.27f6.b82469358ea0dfc66cf15413b48d62e5@example.com>: fileinto action: failed to store into mailbox 'INBOX/': Invalid mailbox name: Ends with hierarchy separator
dovecot-mailcow_1    | Feb 10 12:47:05 mail dovecot: lmtp(user@example.com)<182><yJ06ALlCQV62AAAAmHdZUA>: sieve: msgid=<1702eec8b38.27f6.b82469358ea0dfc66cf15413b48d62e5@example.com>: stored mail into mailbox 'INBOX'
dovecot-mailcow_1    | Feb 10 12:47:05 mail dovecot: lmtp(user@example.com)<182><yJ06ALlCQV62AAAAmHdZUA>: Error: sieve: Execution of script /var/vmail/sieve/global_sieve_after.sieve failed, but implicit keep was successful
dovecot-mailcow_1    | Feb 10 12:47:05 mail dovecot: lmtp(182): Disconnect from fd4d:6169:6c63:6f77::f: Client has quit the connection (state=READY)
```

git diff origin/master yields this diff:
```
diff --git a/data/conf/dovecot/global_sieve_after b/data/conf/dovecot/global_sieve_after
index e047136e..da3dc78d 100644
--- a/data/conf/dovecot/global_sieve_after
+++ b/data/conf/dovecot/global_sieve_after
@@ -15,7 +15,6 @@ if allof (
   envelope :detail :matches "to" "*",
   header :contains "X-Moo-Tag" "YES"
   ) {
-  set :lower :upperfirst "tag" "${1}";
   if mailboxexists "INBOX/${1}" {
     fileinto "INBOX/${1}";
   } else {
```

**Comment by andryyy** [comment]
Oh, sorry, use `set "tag" "${1}";` instead of removing it!

**Comment by Miyamoto72** [comment]
Yep, works as I expected now. Thanks for the quick answer.
PR is created, I hope it's to your liking.
