### ISSUE TITLE
mailcow (docker?) brings the entire server down

### ISSUE THREAD

**Issue by andreas-it-dev** [mailcow/mailcow-dockerized#3324]
Hi guys,

i had mailcow running on a server with some other things (a forum, a rocket chat instance, postgres, the usual stuff) and my server died every now and then. i didnt know what was causing the issues and was sick'n'tired of it so i decided to split it all up into several vservers.
so i created a new ubuntu instance, moved everything from my old to my new server, rewired the dns entries and boom, the server died again.

after a reset it held for a couple minutes and died again.

there is nothing in the logs but mailcow dockerized is the only thing running there right now.

i am somewhat stuck as i never could've imagined that a docker container can bring down the entire server but thats what happens..
anyone an idea?

thanks!

**Comment by andreas-it-dev** [comment]
for completeness sake i just did an update via update.sh - same thing - server completely dies after maybe 10min

**Comment by andryyy** [comment]
You are probably banned by netfilter-mailcow for a wrong password.

**Comment by andreas-it-dev** [comment]
i mean not just mailcow.. the entire thing.. ssh, webserver, everything is dead..

and i have not put in any password.. am not even that far right now coz i dont even have the time to configure apache (proxy) in between the crashes..

am i missing something?

**Comment by mkuron** [comment]
fail2ban adds firewall rules, so even SSH would be blocked. But if you never attempted to enter a password, that's probably not the cause.

How much memory does your server have? If it has less than 2 GB, it will end up swapping itself to death and seem to go down.

I assume you are using some kind of cloud virtual server. These usually provide some kind of VNC or text console, so you could check whether it's the network or the system that goes down.

**Comment by SimplyCorbett** [comment]
Bumping this. Same issue here and I just restored from a backup and completely reinstalled mailcow.

**Comment by andryyy** [comment]
It didn't bring the entire server down. Netfilter banned him.

**Comment by jeremystucki** [comment]
Happened to me as well. How can I avoid this?

Edit: I had a look at iptables and whitelisted our IP address

**Comment by mkuron** [comment]
Log into the VNC console of your virtual server after its network goes down and check `iptables --list` and the Mailcow logs.

**Comment by Adorfer** [comment]
this happens when people install mailcow in non dedicated machines (VMs).

**Comment by andreas-it-dev** [comment]
@Adorfer , i‘d be carefull jumping to conclusions without details...

In my case it was a dedicated Server and it died completely so it would‘ve been impossible to ssh into to check any iptables. I had to hard reset to bring it back up.

The ironic part of it is, that i moved everything in a vServer and it runs smoothly since.

**Comment by andryyy** [comment]
@jeremystucki check which rule triggered your ban. You can find the user and rule, that matched by using the logs. :)

**Comment by mkuron** [comment]
> so it would‘ve been impossible to ssh into to check any iptables

Don‘t use SSH. Use the BMC remote console or remote KVM if it‘s a physical server or the VNC console provided by your hoster or virtualization solution if it‘s a vietual server. Those are independent of the operating system‘s network connection.

**Comment by andreas-it-dev** [comment]
@mkuron yeah, i can do that with the vserver now, my dedicated server didnt have any of this.. (you get what you pay for...)

its a good heads up nonetheless, so thx!
