### ISSUE TITLE
Add dropdown for filtering how many rows are displayed

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#3325]
**Is your feature request related to a problem? Please describe.**
Would be nice to add a dropdown with eg '10, 50, 100, All' to all sites where we have a table with multiple rows (Quarantine, Mailboxes, Domains, Logs)

**Describe the solution you'd like**
We can then select e.g. ALL to see all Quarantine entries and we don't need select all entries, delete and go to the next page.

**Comment by andryyy** [comment]
Please update and check the implementation. :)

**Comment by MAGICCC** [comment]
Yep looks nice, possible to add this also to /quarantine?

**Comment by andryyy** [comment]
Du verlangst zu viel, Peter.

Naah, I will add it. :-D Makes more sense there anyway.

**Comment by andryyy** [comment]
Can you check it?

**Comment by MAGICCC** [comment]
Yep looks fine, merci
