### ISSUE TITLE
Feature request: Quarantine release also relearns as 'ham'?

### ISSUE THREAD

**Issue by remkolodder** [mailcow/mailcow-dockerized#3327]
**Is your feature request related to a problem? Please describe.**

The issue is not perse related to a problem. We are receiving some mailinglists from advertisement hosts which people requested. They get listed in the Quarantine with a high score everytime. Since there is no retraining from Quarantine (As I see it).

**Describe the solution you'd like**

I could configure something in rspamd, but that makes me the manager of the issue. I would rather have my users select the quarantined messages and either release them (no learning occurs) or release them and relearn the system (fuzzy hash gets deleted or demoted, bayes gets a notification that it's not spam). That makes the user the manager of the problem :-)

**Comment by andryyy** [comment]
It has almost not affect on a mail that scored SO high, that it was rejected.

If it was received via mailing list, it is probably flagged as broken SPF or DKIM. You should check these symbols and create rules accordingly.

I will probably add auto-learn as ham, when releasing a message anyway. Better remove any learned statistics.

**Comment by remkolodder** [comment]
Sadly that isn't the case. It's a combination of 'phising', 'bayes' , uribl_grey.
Retraining the bayes score for this message would likely drop it under
the 15..

And this is an official email from one of my clients, not even an advertisement.



<img width="864" alt="Screenshot 2020-02-12 at 09 39 19" src="https://user-images.githubusercontent.com/695440/74317400-a4d59b80-4d7b-11ea-90c0-e33f077285a7.png">

**Comment by andryyy** [comment]
From one of your clients? It does not have a MAILCOW_AUTH symbol, this was not sent from mailcow itself.

You should check what triggers the PHISHING symbol. The URIBL_GREY is also critical.

**Comment by andryyy** [comment]
It is also a bad idea to learn URIBL_GREY and PHISHING tagged mails as ham.

**Comment by remkolodder** [comment]
Thank you very much !! Much appreciated!
