### ISSUE TITLE
Sync jobs subfolder

### ISSUE THREAD

**Issue by levinuss** [mailcow/mailcow-dockerized#333]
Hi,
I just installed Mailcow dockerized on a fresh Ubuntu 16.04.
I want to migrate my mails from my old account to mailcow, I tried to use the Sync Jobs.
But: Leaving the subfolder field emtpy doesn't cause that no subfolder is used, instead, a "INBOX" is placed in the empty field, so that all synchronized folders are subfolders of INBOX.
This isn't the intended behaviour.
It would be great if this could be fixed.

**Comment by stevesbrain** [comment]
If you're just looking to migrate, is it possible they're currently stored in Maildir format? If so, you could just rsync over + change ownership (which is what I did) :)

**Comment by levinuss** [comment]
I tried it, but it didn't work for some reason.

**Comment by stevesbrain** [comment]
Main issue I had was with file ownership - after changing ownership it worked fine. However, if you're using the recommending backup + restore scripts/one liners, I have had issues with those. I simply rsync'd to the docker volume location instead (maybe this is frowned upon, but it worked fine for me). Which approach did you take?

**Comment by levinuss** [comment]
I tried what you suggested but it didn't work. Now, I think it was because I copied the whole `/path/to/vmail/domain/user` folder but changed only the permission for mails in `cur`.
Now, I'm using the sync jobs and let them sync into a subfolder where I have to copy my complete mail collection to INBOX.
It would be great it the "Leave empty and no subfolder is used" option could be fixed. :)

**Comment by stevesbrain** [comment]
Yeah, you would have to change permissions recursively :) But glad you've got it sorted either way!

**Comment by levinuss** [comment]
Looks like this works now.
