### ISSUE TITLE
SMTP Connection / Slow sending Mails

### ISSUE THREAD

**Issue by Bjoern1234** [mailcow/mailcow-dockerized#3330]
I have a problem with my mailcow installation.

We use the following installation
Debain 9
2 CPU
8 GB RAM
Last Mailcow installation
10 smartphones, each with an ActiveSync account
2 computers with 8 ActiveSync accounts each (same Accounts on both computers)
A total of approx. 20-30 mailboxes

The load on the server is 1% CPU, around 4GB RAM and little network load. As soon as the two computers are switched on and used, the sending of messages slows down. It takes between 5 and 10 minutes to send a message. If one of the two computers is switched off, sending will be faster. If both are off, the emails will be sent within a few seconds.

During the time when the computers are switched on, the connection to SOGO is very slow and sometimes I get error message 504. I only see the connection between the problems in port 443.

Does anyone have a similar problem or idea how I can solve this? My guess is that there are too many connections on port 443 and therefore there are timeouts.

**Comment by andryyy** [comment]
Have you seen the support options in the documentation? :) Please check them out.
