### ISSUE TITLE
Mailcow as primary MX for Spam and virus filtering

### ISSUE THREAD

**Issue by emmemarco** [mailcow/mailcow-dockerized#3331]
Hi! 
It's possible to use mailcow as primary MX server and forward all filtered email (from spam and virus without check recipients) to other private mail server without antivirus and antispam system?
Now I can set mailcow as Backup MX for all recipients and set routing transport to other system but email are not filtered, correct?
Thanks

Marco

**Comment by andryyy** [comment]
Please see the documentation about how to get support. :)

The Telegram channel is probably what you are looking for.
