### ISSUE TITLE
How to customize your login page...

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#3332]
If it hasn't been stated yet, I have found a simplistic method of making changes to your login page, with minimal to little issues.  As a result of my findings, I wanted to share this with everyone.

For starters, ensure that you are 'root'.  ;)

Next, enter <code><b>find / -name SOGoRootPage.wox -print</b></code>.  You will notice several places.  From what I've been able to ascertain, it looks like 3 spots where the file exists.

One point of interest is the *first* and *last* listed directory; the middle directory is a redundant one, and is not really necessary.

Once you're in the temporary directory (usually the last/second <code><b>overlay2</b></code> directory, enter <code><b>vi SOGoRootPage.wox</b></code>. 

We're going to make changes in TWO (2) locations:

LOCATION #1: Login disclaimer/disclosure statement.

To add a security/general liability disclaimer/disclosure statement, make the following changes.  Look for the ".svg" file within the file.  It should look like this:

<code><b>`
      <div class="sg-logo" flex-gt-md="50">
        <div layout="row" class="md-padding">
          <div class="md-flex hide show-gt-md"></div>
          <img const:alt="*" class="md-margin" rsrc:src="img/sogo-full.svg"/><br/><br/>
        </div>
      </div>`
</b></code>

Add onto that section to view it like this, along with the disclaimer/disclosure statement:

<code><b>`
      <div class="sg-logo" flex-gt-md="50">
        <div layout="row" class="md-padding">
          <div class="md-flex hide show-gt-md"></div>
          <img const:alt="*" class="md-margin" rsrc:src="img/sogo-full.svg"/><br/><br/>
        </div>
        <div layout="row" class="md-padding">
          <div class="md-flex hide show-gt-md"></div>
          <div class="md-flex hide show-gt-md" style="font-size:80%;text-align:right;">
            Unauthorized access to this system is forbidden and will be prosecuted by law. By accessing this system, you agree that your actions may be monitored if unauthorized usage is suspected.
          </div>
        </div>
      </div>`
</b></code>

LOCATION #2: Remove the (i) function.

Look for this part in the code: "CONNECT BUTTON".  Adjust the text of that <div> section to look something similar to this:

<code><b>`
            
            <div layout="row" layout-align="space-between center">
              <md-button><md-icon></md-icon></md-button>
              <md-button class="md-fab md-accent md-hue-2" type="submit"
                         label:aria-label="Connect"
                         ng-disabled="loginForm.$invalid" sg-ripple-click="loginContent">
                <md-icon>arrow_forward</md-icon>
              </md-button>
`</b></code>

Once done, save the file.  Then copy this file to the first identified location:

<code><b>cd SOGoRootPage.wox /var/lib/docker/volumes/mailcowdockerized_sogo-web-vol-1/_data/Templates/MainUI/</b></code>

Once done, re-enter back into the $HOME directory where you've install the Docker container; for this application, I believe that it is <code><b>/opt/mail-containerized</b></code>.

Stop then restart Docker.

<code><b>docker-compose down</b></code>

<code><b>docker-compose up -d</b></code>

Review your login page.

**Comment by infracritical** [comment]
![image](https://user-images.githubusercontent.com/11613524/74503320-2598b280-4eb6-11ea-92fd-569fed8a4c10.png)

**Comment by infracritical** [comment]
I will see about uploading the code snippets onto the infracritical repository (if anyone is interested).

**Comment by andryyy** [comment]
I received 8 mails for this. 😄 

It is much butter to to it like described [here](https://sogo.nu/support/faq/how-to-customize-the-html.html) and mount (edit: or copy) the desired file to the correct path via docker-compose.override.yml.
