### ISSUE TITLE
The server responded with“504”to operation CalDAVAccountRefreshQueueableOperation.

### ISSUE THREAD

**Issue by bluewalk** [mailcow/mailcow-dockerized#3340]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---
Syncing the calendar on MacOS via CalDav results in the following error: `The server responded with“504”to operation CalDAVAccountRefreshQueueableOperation.`

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Setup sync in MacOs
2. Wait

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | VMware |
| Server/VM specifications (Memory, CPU Cores) | 2 core 6gb mem |
| Docker Version (`docker version`) | latest |
| Docker-Compose Version (`docker-compose version`) | latest |
| Reverse proxy (custom solution) | haproxy |

Adding the following to `data/conf/nginx/includes/site-defaults.conf` to the `location ^~ /SOGo` configuration block resolves the issue
```
proxy_send_timeout 300;
proxy_read_timeout 300;
``` 

Question is, will these changers be overwritten upon the next update-run?

**Comment by andryyy** [comment]
Hi,

I don't see a problem adding this to the default site conf. It will actually not hurt. :)

**Comment by bluewalk** [comment]
Ok cool, so with the next update it will be default? As in, I don't have to edit the `site-defaults.conf` after every update? :)

**Comment by andryyy** [comment]
Yes. :)

**Comment by bluewalk** [comment]
Great, I'll be closing this issue then :) thnx!
