### ISSUE TITLE
Cannot add more domains in Mailcow UI...clicking button doesn't do anything...

### ISSUE THREAD

**Issue by fleiflei** [mailcow/mailcow-dockerized#3341]
Hello,
I cannot add a second domain to my list of domains in Mail Setup in the Mailcow admin UI...

When I fill in the form and click "Add domain only" or "Add domain and restart SOGo" nothing happens. In dev tools the Console and Network window don't show any errors or activity either...

Tried FF and Chrome...

Using current version, updated today...

Any ideas how to fix this? 

Thanks and best regards!

**Comment by andryyy** [comment]
Hi, can you provide a screenshot of the form, when the click does not 
work? Including all values?

------ Originalnachricht ------
Von: "Florian Eickhorst" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 20.02.2020 12:59:57
Betreff: [mailcow/mailcow-dockerized] Cannot add more domains in Mailcow 
UI...clicking button doesn't do anything... (#3341)

**Comment by fleiflei** [comment]
I was just going to prepare the screenshot when i filled out the field "Description" for the first time when then the form was processed and the new domain was added. I wasn't aware that the "Description" field is a mandatory field and there is no info shown that it is (nor were there any validation errors shown). Maybe an extra info and/or validation notice could help there...thanks for your help!

**Comment by andryyy** [comment]
Thanks. :) It gives you a red border around the "wrong"/missing form content. I will set the default desc == domain name, when it is missing.

**Comment by fleiflei** [comment]
> It gives you a red border around the "wrong"/missing form content.

There was no red border shown in my case.
