### ISSUE TITLE
Backup MX only mode. Less containers.

### ISSUE THREAD

**Issue by FingerlessGlov3s** [mailcow/mailcow-dockerized#3343]
**Is your feature request related to a problem? Please describe.**
You can setup a second Mailcow to use as a Backup MX.
I think it would be really nice, if there was a way to do this with a miniual amount of docker containers. No SoGO, etc.

This would allow people to run the backup MX on a lower spec'd VPS instance, 1GB of ram maybe. Which will save money, as 99% of the time the backup mx won't be needed.

**Describe the solution you'd like**
Variable change in the conf file, to operate in Backup MX mode only.

**Comment by andryyy** [comment]
You can install a Postfix standalone with Rspamd or something like that. Not working on it, sorry. :( Some providers also offer backup mx as a service.

**Comment by FingerlessGlov3s** [comment]
Yeah I didn't think you'd want to work on it but I thought no harm in asking.

Maybe one day ay.

Any providers you reccomend?

**Comment by andryyy** [comment]
Besides hosted mailcow? :)

Don't know. Someone created a small script for Postfix using the API. But I think it was lacking the Rspamd part, which would be very important.

I will close this. It should be handled by everyone on their own. :) Note if you try to build something: Slaving to the Redis master in mailcow is important.
