### ISSUE TITLE
Resolving internally before going to WAN when sending an e-mail

### ISSUE THREAD

**Issue by Reiasa** [mailcow/mailcow-dockerized#3344]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ x ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I have setup mailcow on one of my servers inside our network - mailcow works perfectly when sending to/receiving from external email addresses, but when I send an e-mail to one of my postfix servers which has certain aliases (not related to mailcow setup) it cannot reach the server, it turns out this is because it tries to resolve my WAN IP from the LAN, which isn't allowed in our network as we don't have NAT reflection or any of the sort.

A port scan on my network from the LAN will only return SSH port on my postfix server, so no port 25 to send e-mails from mailcow to said server. 

My issue here is that I need mailcow to resolve internally before it tries resolving the public DNS, so it doesn't go throw my WAN address, but rather directly goes to postfix's server LAN IP, that way it can find SMTP port open. 

| Question | Answer |
| --- | --- |
| My operating system | Linux |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | VMware |
| Server/VM specifications (Memory, CPU Cores) | Enough |
| Docker Version (`docker version`) | Docker version 19.03.5, build 633a0ea838 |
| Docker-Compose Version (`docker-compose version`) |docker-compose version 1.24.1, build 4667896b |

**Comment by mkuron** [comment]
I assume you have split DNS? Mailcow comes with its own recursing DNS resolver and won't use the internal DNS server. To work around this, you can either modify the unbound configuration to refer your internal domain to your internal DNS server or you can use a transport map in the admin UI to deliver messages to your internal domain straight to the other server's IP address.

**Comment by Reiasa** [comment]
@mkuron  Hey, I apologize for sending again here, but could you elaborate more on how to "transport map in the admin UI to deliver messages to your internal domain straight to the other server's IP address."?

**Comment by mkuron** [comment]
Log into the Mailcow UI as admin, go to "Routing", scroll down to "Transport Maps"  and add a new entry like destination "internal.example.com", next hop "192.2.0.2", check "Active", and click "Add".

**Comment by Reiasa** [comment]
@mkuron that worked! Can we have an explanation as to why mailcow uses its own recursing DNS resolver instead of using the internal DNS first then using the external one (which could be then mailcow's)?

**Comment by mkuron** [comment]
DANE mail encryption needs trustworthy DNS results. DNSSEC unfortunately does not protect the path between the resolver and the application (e.g. Mailcow), so the only way to be safe is to put the resolver on the same machine as Mailcow.

**Comment by andryyy** [comment]
Plus everyone seems to use a public resolver or a forwarder pointing to a public resolver. No blacklist lookup will work like this. :/ These resolvers are either banned or rate limited heavily.

**Comment by Reiasa** [comment]
Ah, that makes sense. Thanks!
