### ISSUE TITLE
php-fpm und dovecot-mailcow fehler

### ISSUE THREAD

**Issue by Alphaputin** [mailcow/mailcow-dockerized#3348]
root@vps-zap490052-1:/opt/mailcow-dockerized# docker-compose pull
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank st                                                                                                                                                             ring.
Pulling unbound-mailcow   ... done
Pulling mysql-mailcow     ... done
Pulling redis-mailcow     ... done
Pulling clamd-mailcow     ... done
Pulling php-fpm-mailcow   ... extracting (100.0%)
Pulling sogo-mailcow      ... done
Pulling dovecot-mailcow   ... extracting (100.0%)
Pulling postfix-mailcow   ... done
Pulling memcached-mailcow ... done
Pulling nginx-mailcow     ... done
Pulling rspamd-mailcow    ... done
Pulling acme-mailcow      ... done
Pulling netfilter-mailcow ... done
Pulling watchdog-mailcow  ... done
Pulling dockerapi-mailcow ... done
Pulling solr-mailcow      ... done
Pulling olefy-mailcow     ... done
Pulling ipv6nat-mailcow   ... done

ERROR: for dovecot-mailcow  failed to register layer: no space left on device

ERROR: for php-fpm-mailcow  failed to register layer: ApplyLayer exit status 1 s                                                                                                                                                             tdout:  stderr: write /usr/lib/libssl.a: no space left on device
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write                                                                                                                                                              /usr/lib/libssl.a: no space left on device
root@vps-zap490052-1:/opt/mailcow-dockerized# ERROR: for dovecot-mailcow  failed to register layer: no space left on device

ERROR: for php-fpm-mailcow  failed to register layer: ApplyLayer exit status 1 s                                                                                                                                                             tdout:  stderr: write /usr/lib/libssl.a: no space left on device
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write                                                                                                                                                              /usr/lib/libssl.a: no space left on device
-bash: ERROR:: command not found

**Comment by ntimo** [comment]
I would guess your disk is full: „ no space left on device“

**Comment by Alphaputin** [comment]
may be I only have 4.90GB free
