### ISSUE TITLE
Auto empty trash

### ISSUE THREAD

**Issue by raako71** [mailcow/mailcow-dockerized#3349]
Is there a function to auto expunge mail from a folder after a specified time? for example trash folder or promo mail folder
EDIT: found [this](https://github.com/mailcow/mailcow-dockerized/issues/247) post. Would be great if this could be implemented in the mailcow releases for the less docker knowledgeable

**Comment by MAGICCC** [comment]
We could add it into the docs

**Comment by raako71** [comment]
Yas, in a way the was persistent through upgrades would be 👌

**Comment by fbcd4f50ea5350f051450323b5abfd0b** [comment]
It's actually in the documentation, isn't it?
https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-expunge/

**Comment by MAGICCC** [comment]
Ah you are right :)
