### ISSUE TITLE
Cant send Mails

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#335]
Hi, after update (git pull, docker-compose pull, docker-compose up -d --remove-orphans) I can not send mails.
In the logs I have found the following:
`bind9-mailcow_1      | 05-Jun-2017 10:23:34.958 no valid RRSIG resolving 'net/DS/IN': 198.41.0.4#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.959 validating ./NS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.959 no valid RRSIG resolving './NS/IN': 198.41.0.4#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.964 validating net/DS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.964 no valid RRSIG resolving 'net/DS/IN': 199.7.91.13#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.965 validating ./NS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.965 no valid RRSIG resolving './NS/IN': 199.7.91.13#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.969 validating net/DS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.969 no valid RRSIG resolving 'net/DS/IN': 192.33.4.12#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.970 validating ./NS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.970 no valid RRSIG resolving './NS/IN': 192.33.4.12#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.974 validating net/DS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.974 no valid RRSIG resolving 'net/DS/IN': 192.203.230.10#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.975 validating ./NS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.975 no valid RRSIG resolving './NS/IN': 192.203.230.10#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.979 validating net/DS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.979 no valid RRSIG resolving 'net/DS/IN': 192.36.148.17#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.980 validating ./NS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.980 no valid RRSIG resolving './NS/IN': 192.36.148.17#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.987 validating net/DS: no valid signature found
bind9-mailcow_1      | 05-Jun-2017 10:23:34.987 no valid RRSIG resolving 'net/DS/IN': 192.5.5.241#53
bind9-mailcow_1      | 05-Jun-2017 10:23:34.988 validating ./NS: no valid signature found
`

**Comment by rebek86** [comment]
I can not receive emails unfortunately.

I hope you can help me. Many thanks in advance

**Comment by rebek86** [comment]
Puhh, now all is ok again. :-)

I've tried it with docker-compose down and docker-compose up -d but this has not shown any effect.

Then I rebooted the host system (Ubuntu 16.04). After that everything has worked again. Does anyone know what could have been the problem here? :eyes:

**Comment by stevesbrain** [comment]
Possible a kernel update which prevented docker from starting properly? Have had that before!

**Comment by rebek86** [comment]
Hi 
I have the same problem again. I do not know what I can still make to get the server back to run. Maybe you can help me? Thank you in advance

**Comment by elvirdz** [comment]
service docker restart

**Comment by stevesbrain** [comment]
Or, `systemctl restart docker` if you are using systemd tools :)

**Comment by rebek86** [comment]
Thanks for your help! Restart Docker did not help. Also a rebbot of the whole system did not help. I use a KVM V-Server and the only thing that has worked for me was a complete "power off" and than "power on" over the backend of my hoster. How can that be? Do you have an idea?

**Comment by stevesbrain** [comment]
A reboot should really be the same as that! Only thing I could think would be if you are using the host's kernel, instead of your own, and you don't get the "new" host kernel until you power the system off, then on? Are you definitely using your system kernel (which host is this)?

**Comment by rebek86** [comment]
I dont know... :confused:

My kernel is: 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rebek86** [comment]
Hello, I wanted to thank you at this point for the great work and the fast support. You do a really great job! Many Thanks :-)
