### ISSUE TITLE
Only Docker volumes are backed up

### ISSUE THREAD

**Issue by wblondel** [mailcow/mailcow-dockerized#3356]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

After restoring a backup of a previous Mailcow server to a freshly installed Mailcow server, I couldn't login to the Rspamd Web Interface. The password was always incorrect. I needed to go to the Mailcow admin panel and set the password again.

I read issue #898 and it seems that the bug was solved at the time.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Backup and restore using the helper script.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | No virtualization, baremetal |
| Server/VM specifications (Memory, CPU Cores) | source: 2GB/2cores, dest: 8GB/4cores |
| Docker Version (`docker version`) | 19.03.6 on both |
| Docker-Compose Version (`docker-compose version`) | 1.25.4 on both |
| Reverse proxy (custom solution) | No |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by mkuron** [comment]
None of the modifications you make to the git repository are backed up, so custom config files etc. are lost too. The only thing that is backed up besides the Docker volumes is mailcow.conf.

**Comment by wblondel** [comment]
> None of the modifications you make to the git repository are backed up, so custom config files etc. are lost too. The only thing that is backed up besides the Docker volumes is mailcow.conf.

I didn't know I made modifications to the git repository. 
If I understand correctly, the Rspamd password isn't stored in a Docker volume so it isn't backed up?

**Comment by MAGICCC** [comment]
The file with the password is named `worker-controller-password.inc` and can be found in `mailcow-dockerized/data/conf/rspamd/override.d` which is linked into the Docker container (https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml#L86)

Maybe it's not a bad idea to include it in the backup script too.

**Comment by wblondel** [comment]
Okay, I didn't know that! I assumed that the password was somewhere in the volumes.
I expected it to be backed up, just like the Mailcow dashboard credentials are.
