### ISSUE TITLE
Starting mailcow-ui for the first time always redirects to SOGo

### ISSUE THREAD

**Issue by rr-appadaptive** [mailcow/mailcow-dockerized#3358]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ x] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My issue is...

calling the website as described in the instructions https://${MAILCOW_HOSTNAME} always redirects the browser to https://${MAILCOW_HOSTNAME} /SOGo even if I explicitly try to open
https://${MAILCOW_HOSTNAME} /admin

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [x ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

| My operating system |Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) |I suppose VMWare (its a Strato-V-Server |
| Server/VM specifications (Memory, CPU Cores) | 48GB 10Cores |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) |1.21 |
| Reverse proxy (custom solution) | Traefik 2.1 |

**Comment by andryyy** [comment]
There is no way a default installation would do this. Please just revert all your changes to your reverse proxy or other code. :)

You can run `git checkout origin/master` on some of the configs to fix it. Or just post a `git diff origin/master` output. :)
