### ISSUE TITLE
Log retention

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3359]
When the mailcow-dockerized docker-compose setup is updated using the `update.sh` script, 
the whole docker-compose setup is taken DOWN and UP.
It seems that the folders of the old docker containers in `/var/lib/docker/containers/` are removed as the newly created docker containers are new and different ones, with different IDs.
Are the old log files still retained somewhere or can I ensure these are stored so they can be still queried after such a restart?

**Comment by andryyy** [comment]
Check the Docker logging drivers and redirect them somewhere else (default is json, I think). This can be syslog, gelf etc.

LOG_LINES# is stored in Redis.

**Comment by strarsis** [comment]
@andryyy: IMHO adding a mention to the docker-mailcow setup docs for configuring `docker-compose` to log to `journald` (https://docs.docker.com/compose/compose-file/compose-file-v2/#logging) would be a nice addition!
When an update of docker-mailcow is performed (using the `update.sh` script) using the default docker settings, the existing logs would be cleaned up. A sysadmin/postmaster should have set up proper logging, backups, etc anyway, but a little hint can still be helpful.

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/#logging-drivers

**Comment by strarsis** [comment]
Note:
I use this configuration to let Docker globally use `journald` (what is used by default with `systemd`):
`/etc/docker/daemon.json`:
```json
{
  "log-driver": "journald"
}
````

(And with IPv6 enabled there would be also other entries of course)
```json
{
  "log-driver": "journald",
  "ipv6": true,
  "fixed-cidr-v6": "fd00:dead:beef:c0::/80",
  "experimental": true,
  "ip6tables": true
}
````

After restarting Docker to make the new configuration effective,
the mailcow container logs can be accessed via `journalctl`, like this:
````
journalctl CONTAINER_NAME=mailcowdockerized_postfix-mailcow_1
````
