### ISSUE TITLE
Not able to save Quarantine settings

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#3363]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [ X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [ X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I'm not able to change the "maximum age in days" for quarantine. I would like to change it from 14 days to 7 days. Whenever I try to save the "Send a copy of all notifications (BCC) to this recipient" get a red border. It seems I cannot leave this field blank. But the description says: Leave empty to disable

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I go to "Configuration and Details"
2. And then to Configuration
3. And than to Quarantine
5. Change the "maximum age in days" and leave "Send a copy of all notifications (BCC) to this recipient" empty.
6. Hit save.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ X ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Debian 9  |
| Is Apparmor, SELinux or similar active? | Nope |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 30 GB RAM, 8 Cores |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4 |
| Reverse proxy (custom solution) | Nope |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.

```
diff --git a/data/conf/rspamd/local.d/history_redis.conf b/data/conf/rspamd/local.d/history_redis.conf
index 68a59b0c..0abc45c8 100644
--- a/data/conf/rspamd/local.d/history_redis.conf
+++ b/data/conf/rspamd/local.d/history_redis.conf
@@ -1 +1,2 @@
 nrows = 1000;
+subject_privacy = true;
diff --git a/data/conf/rspamd/rspamd.conf.override b/data/conf/rspamd/rspamd.conf.override
index d033e8e2..a07c09d7 100644
--- a/data/conf/rspamd/rspamd.conf.override
+++ b/data/conf/rspamd/rspamd.conf.override
@@ -1,2 +1 @@
 # rspamd.conf.override
-
```

 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**Comment by andryyy** [comment]
Thank you! :)
