### ISSUE TITLE
Auto-save email addresses

### ISSUE THREAD

**Issue by rt050** [mailcow/mailcow-dockerized#3364]
Hi there,

My apologeis if this has been covered, I've searched around!

Does mailcow have the option to auto-save emails that have been sent in the past?

Eg xyz@example.com has been sent an email in the past so is now stored for quick recall when starting to type "xyz" into recipient bar?

Thanks

**Comment by mkuron** [comment]
I don't think SOGo has a previous recipients feature, so there is nothing we could do about this.
