### ISSUE TITLE
blacklisted sender floods quarantine

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#3367]
**Is your feature request related to a problem? Please describe.**

The mailboxes of one of my domains on the cow get a lot of SPAM from one sender.
I've blacklisted this dumba** but now the quarantine will flooded.

**Describe the solution you'd like**
It would be very helpful if blacklisted senders did not appear in the quarantine.
Perhaps optional selectable per domain or mailbox.

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

**Comment by andryyy** [comment]
A global filter map blacklist will block it.
