### ISSUE TITLE
nextcloud helper script

### ISSUE THREAD

**Issue by DopeDealers** [mailcow/mailcow-dockerized#3368]
Hey so im using the helper script to install nextcloud **obviously** 
And everything goes perfect right up until it restarts nginx

"This can take up to hours, depending on the number of files in your instance!
cp: cannot stat './data/assets/nextcloud/nextcloud.conf': No such file or directory
sed: can't read ./data/conf/nginx/nextcloud.conf: No such file or directory"
it seems that the files for nextcloud on nginx settings arent getting created? i dont know

I didnt know where else to contact about this or get the correct things to put inside of the
nextcloud.conf files.

**Comment by mritzmann** [comment]
Please see the documentation about how to get support.
The Telegram channel is probably what you are looking for.

**Comment by andryyy** [comment]
\o/

Also make sure to run it like this: `bash helper-scripts/nextcloud.sh`
