### ISSUE TITLE
One specific email failing to send

### ISSUE THREAD

**Issue by rt050** [mailcow/mailcow-dockerized#3370]
Hi all,

I was wondering if somebody could help me on an issue I have. I send via mailgun so I keep out of Outlook spam. For some reason the SMTP password I had on file wasn't working with something else that I use it with so I changed it. Now, testing all works fine etc but one email address that I used for testing is failing with an error code that I don't understand! Tests to other emails work fine. It was working before I changed the PW.

Errors from postfix as follows:

E1838C2B9A: removed

E1838C2B9A: to=<ryan@ryantolley.co.uk>, relay=dovecot[fd4d:6169:6c63:6f77::2]:24, delay=1.1, delays=0.94/0.03/0.02/0.12, dsn=2.0.0, status=sent (250 2.0.0 <ryan@ryantolley.co.uk> eoQ/Ms30V14iAQAAHoFrww Saved)

disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6

Thanks in advance :)

**Comment by rt050** [comment]
Nope. I'm such a tit.

The recipient address is on Google and I created another for syncing over. STUPID ME!

I'll close.

**Comment by andryyy** [comment]
A tit? 😄

**Comment by rt050** [comment]
You know when common sense prevails through the cussing of "why's it not working?!"..

**Comment by cklabautermann** [comment]
> A tit? 😄

https://forum.wordreference.com/threads/tit-stupid.1532071/

Didn´t know that, too. Sorry, completely OT

**Comment by andryyy** [comment]
"Again what learned."

http://ithinkispider.com/
