### ISSUE TITLE
Virus .doc received. Spamd error: clamav: failed to scan, maximum retransmits exceed

### ISSUE THREAD

**Issue by dofl** [mailcow/mailcow-dockerized#3371]
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
I have received a suspicious offer.doc file in a e-mail, which tested positive as a virus on the website virustotal.com as a trojan. I wanted to know why ClamAV didn't pick it up, 

I logged in on spamd and saw an error at the exact moment the mail was received that the module 'lua' gave an error: clamav: failed to scan, maximum retransmits exceed

**Reproduction of said bug**: How *exactly* do you reproduce the bug?
I've send the same file from a protonmail account which gave the same clamav error.

**System information**
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2 CPU, 4 GB RAM, enough free space |
| Docker Version (`docker version`) | 19.03.6  |
| Docker-Compose Version (`docker-compose version`) | 4.1.0 |
| Reverse proxy (custom solution) | No |
 
ClamAV is enabled in the mailcow.conf. 

Any idea how I can debug this further? I can send the same mail to anyone who wants to test it on their own mailcow.

**Comment by andryyy** [comment]
Check if Clam has died or your firewall, if any. I cannot really assist you here. You should try a telnet from the Rspamd container to clamd:3310

It is not a general mailcow error I'm afraid. 

4 GB might be not enough, Clam may have run out of memory. Check your syslog. That's all support I'm able to provide here. :) Also enable watchdog in mailcow.conf and configure a mail alert.

André

**Comment by dofl** [comment]
There is no firewall enabled on the server. I have enabled watchdog, which did not respond to any container failures (never have in the past as well). 

I connected to the docker container with the [mailcow manual](https://mailcow.github.io/mailcow-dockerized-docs/debug-attach_service/), unfortunatly telnet is not available in the rspamd container. I couldn't test the connection to clamd.

I tested the file against a couple of virusscanners and even then clamav wouldn't even matter. I checked the date of the virus engine and this was yesterday. So it's not really clear how good clamav even is.
<img width="1151" alt="Screenshot 2020-02-29 at 11 19 17" src="https://user-images.githubusercontent.com/8161021/75605728-84c90a80-5ae5-11ea-952f-e690ac45d06b.png">

**Comment by andryyy** [comment]
We use multiple third party signatures for ClamAV. Your check result is pretty much useless. It may apply to a default Clam DB. 

Furthermore this is not about detection rate but a failed container. It probably died because it ran out of memory. 

You should monitor your server yourself for running services or at least use watchdog-mailcow. It would have detected the failed service. 

Again, this is NOT about detection rates.

**Comment by dofl** [comment]
It is unknown if the container failed. I had no watchdog notices and the docker container had a green icon in the system information page in de mailcow admin. There is always 1 GB of memory free, so I doubt that it is a memory issue.

**Comment by andryyy** [comment]
Clam is working fine. Please enable watchdog and watch your memory usage.
