### ISSUE TITLE
Problem sending emails after update

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3372]
@MAGICCC @andryyy

Again i have this error after updating:
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

warning: TLS library problem: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1661:
```

At this point i can send emails from example from my woltlab-forum, what could this problem be?
This time a reboot does not solve the problem?
Before the update everything ran without problems

EDIT:
I have now created the two extra.conf's and they work again:
https://mailcow.email/2020/02/12/tls-1-0-and-1-1-is-now-disabled-for-pop3-s-imap-s-smtps-and-submission/

But what exactly is the solution to my problem?

Thanks

**Comment by mkapra** [comment]
You are using a insecure TLS version (1.0) to connect. So this is a client problem. My client connects with TLSv1.2.

**Comment by omexlu** [comment]
It's not my mail client that doesn't work here but several scripts (Woltlab & osTicket and more) that couldn't connect here.

I do not know what the settings depend on?

Anyway with the changes as mentioned above it works again.

Maybe somebody can explain it to me or provide an alternative solution :)

**Comment by mkapra** [comment]
On which port are the clients/scripts/programs connecting?
