### ISSUE TITLE
Docker error on start Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by dgtlmoon** [mailcow/mailcow-dockerized#3373]
I'm a first time user.

I'm on c1907063e1b2fe4dad3bd4ecbf9ff02382d567b0 current HEAD

I followed the installation instructions https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_install/

Attached is my mailcow.conf file [mailcow.conf.txt](https://github.com/mailcow/mailcow-dockerized/files/4270154/mailcow.conf.txt)

At `docker-compose up` I get..

```dgtlmoon@acer:/tmp/mailcow/mailcow-dockerized$ docker-compose up
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: Pool overlaps with other one on this address space
```

Nothing is running already in `docker ps`

`docker-compose version 1.25.4, build 8d51620a` (latest) tried also `docker-compose version 1.21.2, build a133471`

`Docker version 18.09.7, build 2d0083d`

**Comment by mkapra** [comment]
Hi,
Do you have other projects/containers running in docker already. If you have
try setting the `IPV4_NETWORK` variable to another IP address. Then `docker-compose up -d` again.

**Comment by dgtlmoon** [comment]
@mkapra as stated in my original report "Nothing is running already in `docker ps`" ..

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by dgtlmoon** [comment]
@mkapra Must be some bug in the config build system...

```$ grep -i ipv4 mailcow.conf
# Skip IPv4 check in ACME container - y/n
# Internal IPv4 /24 subnet, format n.n.n (expands to n.n.n.0/24)
IPV4_NETWORK=172.22.1
# Use this IPv4 for outgoing connections (SNAT)
```

because 172.xxx is usually used by my other docker projects, which are absolutely not running at the moment but I see it in `ifconfig`, what todo?

**Comment by andryyy** [comment]
Why should it be a bug in the config build system? You just need to make sure the subnet is not used by another Docker **network**, not container (so running `docker ps` is useless, it won't show you networks).

**Comment by dgtlmoon** [comment]
@andryyy it is a bug, looking at `generate_config.sh` , it seems that the script is installing a default network range in the config file, which in my 25 years of dealing with opensource software always is going to provide pain somehow.

Probably I will not be the only one to encounter this bug.

- It is NOT mentioned on the installation instructions in the link I provided to check the network settings.

- This issue WILL be encountered by other people in the future.

- Bugs in software are not limited to logical, coding errors, bugs are also poor/lacking documentation, inadequate expectations and preset configuration variables.

I did look at the config file carefully before I filed this bug, and that `IPV4_NETWORK` config variable did not stand out to me (otherwise I would have not burnt my personal time on a weekend filing this bug), I really did not expect it to be a default variable - I should NOT be expected to read the shell script (`generate_config.sh`) prior to being able to run this software.

Since you are assuming in the installation instructions that people wills start "from zero" by giving them Docker installation instructions, you should also be giving them any other "from zero" instructions such as setting the IPV4_NETWORK variable

I have reviewed dozens of OpenSource mail projects over the last 10 years, and I can absolutely say that the ones that grow always have the best documentation.

I've created a pull request here https://github.com/mailcow/mailcow-dockerized-docs/pull/193

**Comment by andryyy** [comment]
How is it a bug if you went with the default network range and did not check the config for overlapping networks? I mean.. if you start the stack, it literally says it is overlapping. 

A misconfiguration is not a bug, that's ridiculous.

It is unbelievable it gave you HOURS of headache, when it literally says "hey, there are overlapping networks". 

That's not a bug, you **just had overlapping networks in Docker**.
