### ISSUE TITLE
Is it possible to merge two mailcow installations without loosing all the mails?

### ISSUE THREAD

**Issue by reschandreas** [mailcow/mailcow-dockerized#3379]
Hi there,

a friend of mine and I are currently running a setup on a root server where we both run our own instance of mailcow in a different LXC-Container. To improve our setup we are searching for ways to merge our mailcows together, but haven't found a way yet. Is there a documentation somewhere that we didn't find that makes that possible?
Thanks!

**Comment by andryyy** [comment]
Hi,

pleeeease use the support channels for these questions. :)

Nevertheless, don't use LXC, you will experience fancy errors. 

Two mailcows on a host is tricky, as both will fight for iptables rules. It is better to have both in separate KVMs. You can install a ClamAV externally and point them to it. This will save a lot of resources. 

Closing this as support question, feel free to join our Telegram channel or, in the near future, our Flarum board.
