### ISSUE TITLE
ACME fails to fetch cert

### ISSUE THREAD

**Issue by StiviiK** [mailcow/mailcow-dockerized#3381]
**Prior to placing the issue, please check following:**
- [X] I understand, that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the problem**:
Updating of the Cert fails. The acme-challenge times out, accessing `http://autodiscover.stivik.de/.well-known/acme-challenge/TOKEN` is never loading. Accessing `autodiscover.stivik.de`, `autoconfig.stivik.de`, `mail.stivik.de` works normally.

**Docker container logs of affected containers**:
![image](https://user-images.githubusercontent.com/8115642/75792659-940eb900-5d6e-11ea-90ae-2ec344256309.png)

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 19.10 |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | ESXi |
| Docker Version (`docker version`) | 19.03.3 |
| Docker-Compose Version (`docker-compose version`) | 1.25.2, build 698e2846 |
| Reverse proxy (custom solution) | Traefik |

- Output of `git diff origin/master`, any other changes to the code? 
```diff
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 65f5301f..8264c3fe 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );

-    WOWorkersCount = "20";
+    WOWorkersCount = "3";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
diff --git a/data/web/inc/vars.inc.php b/data/web/inc/vars.inc.php
index 9b9705fd..541ceab6 100644
--- a/data/web/inc/vars.inc.php
+++ b/data/web/inc/vars.inc.php
@@ -101,7 +101,7 @@ $SHOW_DKIM_PRIV_KEYS = false;
 $MAILCOW_APPS = array(
   array(
     'name' => 'Webmail',
-    'link' => '/SOGo/',
+    'link' => '//inbox.stivik.de',
   )
 );

diff --git a/docker-compose.yml b/docker-compose.yml
index f18b3549..12af6c07 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -306,11 +306,27 @@ services:
         - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
         - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
         - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
-      ports:
-        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
-        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
+      #ports:
+      #  - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
+      #  - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
+      labels:
+        # Docker
+        - traefik.enable=true
+        - traefik.docker.network=mailcow-network
+
+        # Routing
+        - traefik.http.routers.mail.rule=Host(`mail.stivik.de`) || Host(`autodiscover.stivik.de`) || Host(`autoconfig.stivik.de`) || Host(`_autodiscover._tcp.stivik.de`)
+        - traefik.http.routers.mail.tls.certresolver=letsencrypt
+        - traefik.http.routers.mail.tls.domains[0].main=*.stivik.de
+        - traefik.http.routers.mail.tls.domains[0].sans=stivik.de
+        - traefik.http.routers.mail.entrypoints=websecure
+        - traefik.http.services.mail.loadBalancer.server.port=${HTTP_PORT:-80}
+        - traefik.docker.network=traefik
       restart: always
       networks:
+        traefik:
+          aliases:
+            - nginx
         mailcow-network:
           aliases:
             - nginx
@@ -480,6 +496,8 @@ services:
         - /lib/modules:/lib/modules:ro

 networks:
+  traefik:
+    external: true
   mailcow-network:
     driver: bridge
     driver_opts:
```

**Comment by MAGICCC** [comment]
Seems your traefik does not route the LE traffic correctly.
You may wait here until somebody is responding or you can ask in the mailcow Telegram group: https://t.me/mailcow

**Comment by StiviiK** [comment]
Were able to resolve my issue following this documentation: https://github.com/mailcow/mailcow-dockerized-docs/pull/187.
