### ISSUE TITLE
User password change from roundcube doesn't work

### ISSUE THREAD

**Issue by laymonk** [mailcow/mailcow-dockerized#3389]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [x] I understand, that not following below instructions might result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

User changed password from RoundCube, and afterwards neither the new password nor the old password works.

I shouldn't be opening this as a bug report, but I really have searched but cannot find the officially recommended way for users to change their passwords:  
* mail client on desktop?
* RC or SOGo web client?
* Other?

**Docker container logs of affected containers**:
n/a

**Reproduction of said bug**:
n/a

**System information**:
n/a

**Comment by mkuron** [comment]
Roundcube is not an official part of Mailcow, so we probably can't help you much. The official way to change your password is via the mailcow UI, but SOGo should work too.
That being said: how did you configure the RC change password plugin? What does it end up writing to the Mailcow user database?

**Comment by andryyy** [comment]
You need to use the mailcow UI. :) Users can log into mailcow UI to change their settings. You can restrict it via ACL as admin, when editing a mailbox.
