### ISSUE TITLE
allow only one cipher

### ISSUE THREAD

**Issue by karkaaa** [mailcow/mailcow-dockerized#3398]
Hello,

How to allow only this  TLSv1 with cipher AES256-SHA (256/256 bits)?

After this update https://mailcow.email/2020/02/12/tls-1-0-and-1-1-is-now-disabled-for-pop3-s-imap-s-smtps-and-submission/

Thank you.

**Comment by MAGICCC** [comment]
You can enable TLSv1 again with the snippets which are in the news or here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/

**Comment by andryyy** [comment]
Hi,

https://wiki.dovecot.org/SSL/DovecotConfiguration

Check extra.conf in data/conf/dovecot

Please do not use the bug tracker for support questions, thanks. :)
