### ISSUE TITLE
502 php-fpm-mailcow_1 Waiting for SQL...

### ISSUE THREAD

**Issue by hovrashko** [mailcow/mailcow-dockerized#3399]
Today after running ./update.sh started getting **"502" waiting to connect to mysql.** 
 Before opening this ticket  here is what i have tried:

- **checked the password still the same**
> docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}

> "ERROR 1045 (28000): Access denied for user 'mailcow'@'localhost' (using password: YES)"

- **reset containers manually**
> docker-compose restart mysql-mailcow nginx-mailcow dovecot-mailcow solr-mailcow postfix-mailcow netfilter-mailcow php-fpm-mailcow redis-mailcow watchdog-mailcow

- **recreated config**
> ./generate_config.sh

And many other things on github as well as on the web. 

Is that he bug or there something preventing containers to connect to mysql (mariadb)? 

*It's not fresh install, i need to backup all the data before starting fresh

Thank you!

**Comment by hovrashko** [comment]
![mailcow_isssue1](https://user-images.githubusercontent.com/61986752/76244299-06601d00-61f7-11ea-9b12-59eb8113c15a.PNG)

**Comment by andryyy** [comment]
This is **not** a ticket system.

[image](https://user-images.githubusercontent.com/2972950/76246422-f3bd0680-623d-11ea-9c25-5b5a312146b6.png)

:)

**Comment by hovrashko** [comment]
Why waste time on all this? Should allow to post issue in the first place, weird..
