### ISSUE TITLE
key unused

### ISSUE THREAD

**Issue by daemon-byte** [mailcow/mailcow-dockerized#3401]
All my dkim keys are showing up as find except for one but I don't understand the message. What does "key unused" specifically mean?

![image](https://user-images.githubusercontent.com/517787/76296388-5fdb5100-62b6-11ea-99d4-d28d1df1b698.png)

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/76296666-cf514080-62b6-11ea-846b-6654683fb4ec.png)

It is not used by a domain then. No domain with that key, but key exists == unused key.
