### ISSUE TITLE
Backup script fail, mysqldump: Error 2020

### ISSUE THREAD

**Issue by kozicpetar** [mailcow/mailcow-dockerized#3402]
**Description of the bug**:
In the process of backup whole mail server with bacup_and_restore.sh script process failed with error:
`mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' when dumping table `sogo_cache_folder` at row: 15`

**Reproduction of said bug**:
`MAILCOW_BACKUP_LOCATION=/mnt/backup/ /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all --delete-days 7`

**System information**:
Mailcow the latest version from git
Ubuntu 18.04.3 LTS
On the server is about 13GB of data in mailboxes

**Comment by andryyy** [comment]
We don't use mysqldump anymore, please update. 

The backup HELPER is also just a helper script. You are responsible for your backups. :)
