### ISSUE TITLE
Nginx Reverse Proxy Problem

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3403]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
I have the following problem. I want to run mailgin with docker on a running server with nginx. Mailcow runs in advance and also seems to work. E-mails can be sent and received. Unfortunately I get the redirection to the configuration page, i.e. the connection to the other Nginx instance. I set the following values in mailcow.conf:

HTTP_PORT = 8082
HTTP_BIND = 127.0.0.1

HTTPS_PORT = 8443
HTTPS_BIND = 127.0.0.1

According to the manual, the rest should work automatically.

The following configuration was stored in Nginx:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name mail.*********.de autodiscover.********** autoconfig.**********;
  server_name mail.*********.de;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name mail.********.de autodiscover.********** autoconfig.**********;

  ssl_certificate /opt/mailcow-dockerized/data/assets/ssl/cert.pem;
  ssl_certificate_key /opt/mailcow-dockerized/data/assets/ssl/key.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location /Microsoft-Server-ActiveSync {
    proxy_pass http://127.0.0.1:8082/Microsoft-Server-ActiveSync;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 75;
    proxy_send_timeout 3650;
    proxy_read_timeout 3650;
    proxy_buffers 64 256k;
    client_body_buffer_size 512k;
    client_max_body_size 0;
  }

  location / {
      proxy_pass http://127.0.0.1:8082;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 0;
  }
}
```

Maybe someone can help me?

**System information**:
| Question | Answer |
| --- | --- |
| My operating system | ArchLinux |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 3x CORE INTEL, 4GB RAM |
| Docker Version (`docker version`) | Docker version 19.03.7-ce, build 7141c199a2 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.4 |
| Reverse proxy (custom solution) | NGINX |

**Comment by MAGICCC** [comment]
Not a bug with mailcow, you may join our Telegram group @ http://t.me/mailcow to get support

**Comment by andryyy** [comment]
Please also keep your Nginx reverse config by hand. :) Perhaps you just forgot to reload?
