### ISSUE TITLE
NGINX Ports lassen sich nicht ändern, externer Nginx

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#3404]
Ich versuche gerade einen externen NGINX als reverse proxy einzurichten. 
soweit ich das verstanden habe muss ich dazu in der mailcow.conf die ports abändern .. das config script starten und dann den mailcow-nginx container neu starten.
allerdings schlagen die ports nicht durch, der mailcow-nginx versucht nach wie vor port 80 und 443 zu nehmen und ich verstehe nicht wo da mein fehler ist. 

und was ich auch noch nicht so ganz rausgefunden habe ist wie die conf vom externen nginx auszusehen hat? der muss ja alles relevante für mailcow weiterleiten nur die frage was

Hab versucht der Doku zu folgen aber bin immer mehr verwirrt mittlerweile.

**Comment by shiz0** [comment]
Hi,
this issue tracker in NOT a support channel.
Please join our Telegram Group for community support: https://t.me/mailcow
