### ISSUE TITLE
SSL error when receiving mails from Google

### ISSUE THREAD

**Issue by normanu** [mailcow/mailcow-dockerized#3407]
I get the following when receiving mails from gmail.
All other sites indicate no problem with my SSL certificates and I can send and receive mail (to non-gmail addresses) also without an issue.

`
Mar 11 14:02:29 mail postfix/smtpd[571]: connect from mail-lj1-x231.google.com[2a00:1450:4864:20::231]

Mar 11 14:02:29 mail postfix/smtpd[571]: warning: key at index 1 in SNI data for mail.<domain>.nl does not match next certificate

Mar 11 14:02:29 mail postfix/smtpd[571]: warning: TLS library problem: error:1426D121:SSL routines:ssl_set_cert_and_key:not replacing certificate:../ssl/ssl_rsa.c:1107:

Mar 11 14:02:29 mail postfix/smtpd[571]: warning: error loading private keys and certificates from: SNI data for mail.<domain>.nl: aborting TLS handshake

Mar 11 14:02:29 mail postfix/smtpd[571]: SSL_accept error from mail-lj1-x231.google.com[2a00:1450:4864:20::231]: -1

Mar 11 14:02:29 mail postfix/smtpd[571]: warning: TLS library problem: error:1422E0EA:SSL routines:final_server_name:callback failed:../ssl/statem/extensions.c:1007:

Mar 11 14:02:29 mail postfix/smtpd[571]: lost connection after STARTTLS from mail-lj1-x231.google.com[2a00:1450:4864:20::231]

Mar 11 14:02:29 mail postfix/smtpd[571]: disconnect from mail-lj1-x231.google.com[2a00:1450:4864:20::231] ehlo=1 starttls=0/1 commands=1/2
`

**Comment by mboogert** [comment]
Why is this issue closed without any comments? Currently I'm experiencing exactly the same. All e-mail is received correctly, except e-mail from google.

**Comment by andryyy** [comment]
https://github.com/mailcow/mailcow-dockerized/issues/new?template=Bug_report.md

Check the template.

You certificate is probably invalid/broken. That's not a bug in mailcow.

**Comment by normanu** [comment]
It was a postfix setting which fixed it for me.
I'll look it up.

**Comment by normanu** [comment]
I commented out,
tls_server_sni_maps

In main.cf, that fixed it for me.
Was not a certificate problem.

**Comment by andryyy** [comment]
It was. This parameter should not be commented out. You have a broken installation and should fix it instead of commenting it out. 

Marcel Hofer may help you with this.

**Comment by andryyy** [comment]
@mhofer117 :)

**Comment by mhofer117** [comment]
Yes i'd also say it looks like a broken installation. Would need some more details / domain name to test.
However if you don't need the SNI feature just leave it disabled in the mailcow config instead of editing individual service configs.

**Comment by normanu** [comment]
I will gladly send you my config, where and how shall I send it?
