### ISSUE TITLE
Cannot start TLS: handshake failure with GMail

### ISSUE THREAD

**Issue by dstapp** [mailcow/mailcow-dockerized#3408]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
I set up a new mailcow instance a few days ago and whenever I try to communicate with GMail or GMX, I get the following errors, although the mail is still delivered after being deferred for some time, see below. 

I already had a look at existing tickets and it is not related to MTU (using the 1500 default, also set on the interface). The only change in my main.cf is that I allow SSLv3 for smtp_tls_protocols for incoming mail, but this should not affect this at all. I also turned off IPv6 since it's not configured on my interface.

It looks like there's one problem in still trying to connect using IPv6 (which should not happen because it's turned off, right?) and the second one seems to be that my instance and GMail cannot negotate the protocol to use which is strange since I think it should at least be able to use the most recent TLS.

I also verified that I have the same issue on another mailcow setup that I maintain (also updated to current state).

**Docker container logs of affected containers**:

```
postfix-mailcow_1    | Mar 11 15:47:46 mail postfix/smtp[368]: connect to alt1.gmail-smtp-in.l.google.com[2a00:1450:4010:c0d::1b]:25: Cannot assign requested address
postfix-mailcow_1    | Mar 11 15:47:48 mail postfix/smtp[368]: SSL_connect error to alt2.gmail-smtp-in.l.google.com[172.253.118.27]:25: -1
postfix-mailcow_1    | Mar 11 15:47:48 mail postfix/smtp[368]: warning: TLS library problem: error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1113:
postfix-mailcow_1    | Mar 11 15:47:48 mail postfix/smtp[368]: 57330E8224B: to=<xyz@gmail.com>, relay=alt2.gmail-smtp-in.l.google.com[172.253.118.27]:25, delay=3, delays=0.16/0.01/2.8/0, dsn=4.7.5, status=deferred (Cannot start TLS: handshake failure)
```

**Reproduction of said bug**:
Setting up from scratch and trying to send a email to Gmail with TLS enforcement enabled should be enough.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 19.10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Running on a VPS with Contabo, I guess it's KVM |
| Server/VM specifications (Memory, CPU Cores) | 6 Cores, 16 GB mem |
| Docker Version (`docker version`) | 19.03.7, build 7141c199a2 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4, build 8d51620a |
| Reverse proxy (custom solution) | none |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.

```
root@vmd49458:/opt/mailcow-dockerized# git diff origin/master
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index f09dbfb6..aaca6e29 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -146,7 +148,7 @@ lmtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 smtpd_tls_mandatory_ciphers = high

-smtp_tls_protocols = !SSLv2, !SSLv3
+smtp_tls_protocols = !SSLv2, SSLv3
 lmtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 smtpd_tls_protocols = !SSLv2, !SSLv3

diff --git a/docker-compose.yml b/docker-compose.yml
index 1fd96e54..b2979ed8 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -521,12 +524,15 @@ networks:
     driver: bridge
     driver_opts:
       com.docker.network.bridge.name: br-mailcow
-    enable_ipv6: true
+    enable_ipv6: false
     ipam:
       driver: default
       config:
         - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
         - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

 volumes:
   # Storage for email files
```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.

It's a completely fresh system without any additional firewall or anything set up, ufw is inactive. Rules installed by Docker by default are set up without any change.

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

```
root@vmd49458:/opt/mailcow-dockerized# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

**Comment by andryyy** [comment]
Hi,

Can you try to set `do-ip6: no` in `data/conf/unbound/unbound.conf` and restart `unbound-mailcow`?
Postfix is set to prefer IPv4, that's a bit strange. I guess it is trying v6 as result of the broken TLS handshake.

Regarding the TLS problem:

```
smtp_tls_protocols = !SSLv2
```

That's what you want. `!SSLv2 SSLv3` is "just enable SSLv3", iirc. :)

Remove your changes from main.cf, please, and create a file `data/conf/postfix/extra.cf` with the following content:

```
smtp_tls_protocols = !SSLv2
```

You can remove your changes to

**Comment by dstapp** [comment]
Stupid me :-) Solved! Thanks so much @andryyy and also for making this great project :-) Moved all my mail servers to mailcow setups and it works like a charm!

**Comment by andryyy** [comment]
Aww, thank you. :) Closing this. :)
