### ISSUE TITLE
Email Clients Cannot Connect to the Mail server

### ISSUE THREAD

**Issue by Viktova** [mailcow/mailcow-dockerized#3409]
I have never had issues with mailcow and if so I would normally figure out a way and solve it, but recently after an update from ~a month or so everything broke and non of the email clients out there is able to connect to the mailing server.

a simple start is when I trigger this inside the mailing server:

`echo "Q" | openssl s_client -starttls smtp -crlf -connect mail.example.com:465
`

it just returns:
`CONNECTED(00000005)
`
and hangs forever.

the only port that is working is 587 and nothing else.

doing docker ps -a shows that all containers are up and running

doing `netstat -tuplen` shows all the right ports binded 143,993,995,587 etc...

What am i missing here?

Nothing is showing in the docker logs when an email client tries to connect as it automatically refuses or says wrong username or password. I'm pretty sure it's not a password or username issue.
I work in a company and I use mailcow there as a company mailing server with no issues for tens of employees.

I tried to renew the certbot certificate as I have a different setup. I can assure you it's not a certificate or nginx issue, i can goto the admin panel normally, and i can login to SOGo with the account just fine but not on email clients.

I tried it on Mail.app for iOS and thunderbird for linux and windows

**Comment by andryyy** [comment]
Hey, I am sorry, but we don't use Github for support questions anymore. Something is broken, but it does not seem to be a bug.

If I am wrong and **it is** a bug, you can file a report (with all information asked in the template you deleted). Please use the official support channels, I cannot do support here anymore.

It is either community support via Telegram or official support via Servercow.de. :-)

André

**Comment by Viktova** [comment]
thanks! noted <3
