### ISSUE TITLE
[FR] Automated Spam Reporting to Spamcop (or any other)

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#3410]
In mailcow already have 2 options to report spam to local fuzzy storage:
- Spam traps via Spam Alias delivered to spam@localhost
- Quarantine - > Learn as spam and delete

Adding option to allow automatically report this mail to Spamcop will great help to all with endless fight with spam.

To do this additional field in mailcow UI and logic to FWD mail from 2 options mentioned above needed:
- send reports "From" address, _note to UI_: this **must** be real address of administrator or alias to real person, so he can read and reply on mail by this email)
- send report "To" address, e.g.: submit.SECRET@spam.spamcop.net (cool to have multiple emails separated by comma to have possibility report to multiply systems)
_Note:_ this mail must be signed by DKIM.
In case this impossible - there must be notice about it and "From" will be any-user-wanted@${MAILCOW-HOSTNAME} and DMARC policy for ${MAILCOW-HOSTNAME} domain that not deny mail without DKIM. And in addition there must be 3rd field to create alias for any-user-wanted@${MAILCOW-HOSTNAME}  to real person/s separated by comma.

**Comment by andryyy** [comment]
Thanks, I will consider reporting to the mailcow fuzzy.
