### ISSUE TITLE
Run Wordpress within Mailcow Installation

### ISSUE THREAD

**Issue by rusagent** [mailcow/mailcow-dockerized#3414]
Hey - i know this is probably not the place to ask but maybe someone can answer me.

I want to install some wordpress homepages behind the mailcow. 

I created a database and user inside the mysql db. Then i also downloaded wordpress to the data/web/domain.xyz folder and edited the config. Now i can't access the page. How can i achieve some wordpress pages running on the same server as mailcow with using mailcows nginx? Or should i do that somehow else? I can't afford multiple servers for that setup yet so that's out of question. 

Hope someone can help me <3 

btw - awesome package you created there @andryyy

**Comment by andryyy** [comment]
Hi, thanks for your kind words! :)

Unfortunately this is not the right place to ask these questions. It is a bug tracker only. 

Please check the support channels, there will be an official forum soon, too. 

What you want is a reverse proxy. The docs contain examples for that. 

André
