### ISSUE TITLE
Disable ipv6

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#3415]
Hi guys,

your tutorial (github wiki) for disable ipv6 is without function!

I do create the file docker-compose.override.yml
I do write  the content in the file ...
...
docker-compose down
docker-compose up -d
.... and nothing happens!

ipv6 is still enable.

Now I do manually edit the file docker-compose.yml
Now is ipv6 disable

**Comment by andryyy** [comment]
That's something to mention in the docs repo.

Furthermore: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-disable_ipv6/

The docs mention to edit docker-compose.yml and disable IPv6.

Edit: I just simplified the docs a bit by removing some lines, I did not change any text.

The docs are the official documentation. Not a tutorial. :)
