### ISSUE TITLE
New Nginx container / virtual host/custom site - unable to integrate with PHPFPM

### ISSUE THREAD

**Issue by RickD123** [mailcow/mailcow-dockerized#3416]
Hi,

I am trying to integrate a new site (virtual host, custom site) into Nginx as part of mailcow dockerized. For my existing mailcow dockerized installation PHP support works fine (including for phpmyadmin). I also have imported/mounted the root folder of the virtual host below into the Nginx configuration as part of my docker-compose.yml file.

Here is my config from data/conf/nginx/mydomain.conf:

server {
        listen 80;
        listen [::]:80;

        root /home/abc/wwwroot/htdocs;
        index index.html index.php index.htm;

        server_name my.domain.tld;

 location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass phpfpm:9002;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

When I do leave the location statements out, accessing any PHP file (e.g. index.php) results in the browser downloading the PHP file (rather than it being interpreted by the web server). Then I added the location code above and when accessing a PHP file, I am getting an error message in the log of Nginx:

`php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::10 -  14/Mar/2020:13:41:01 +0100 "GET /index.php" 404
nginx-mailcow_1      | 2020/03/14 13:41:01 [error] 21#21: *15 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 178.203.A.B, server: abc.mydomain.tld, request: "GET / HTTP/1.1", upstream: "fastcgi://[fd4d:6169:6c63:6f77::d]:9001", host: "abc.mydomain.tld"
`

Any ideas on how to fix this?

Kind regards
RickD

**Comment by Adorfer** [comment]
This is not the support site. Ticket invalid due to "template not used for issue reporting"
