### ISSUE TITLE
Acme Breaks when nginx listen address != host outbound address 

### ISSUE THREAD

**Issue by 707Alex707** [mailcow/mailcow-dockerized#3418]
In short mailcow won't generate an ssl certificate because it's checking the wrong address
![image](https://user-images.githubusercontent.com/23481284/76708997-a32c2a00-66d1-11ea-8227-8de75693ece5.png)

I have the following ip's on my server
2607:5300:60:4b5c::4
2607:5300:60:4b5c::3
2607:5300:60:4b5c::2
2607:5300:60:4b5c::1
192.99.36.92

Now in mailcow.conf I have the following set
HTTP_PORT=80
HTTP_BIND=2607:5300:60:4b5c::3
HTTPS_PORT=443
HTTPS_BIND=2607:5300:60:4b5c::3
SNAT_TO_SOURCE=192.99.36.92
SNAT6_TO_SOURCE=2607:5300:60:4b5c::3

Whats interesting is the acme.sh script is trying to authenticate against 2607:5300:60:4b5c::4 but there is no webserver there, it's on 2607:5300:60:4b5c::3 as set by the HTTP(S)_BIND address in mailcow.conf

In my few minutes of debugging I discovered that the acme.sh uses the function get_ipv6 declared in /data/Dockerfiles/acme/functions.sh in there it uses curl to connect to ip6.mailcow.email which returns your outbound address. Which is where the issue comes from,  as my outbound address is not my web server listening address. 

Now I am not familiar with the inner workings of mailcow but why not use the HTTP(S)_BIND addresses set in mailcow.conf instead of the get_ipv6 function in functions.sh?

I think I got everything.....I hope

EDIT:
**ip6tables -L -vn -t nat**
![image](https://user-images.githubusercontent.com/23481284/76711480-d3ca8e80-66e6-11ea-820e-48031a421ca5.png)

**ip6tables -L -vn**
![image](https://user-images.githubusercontent.com/23481284/76711530-53f0f400-66e7-11ea-9d3a-bf3286b32cd7.png)

**Comment by andryyy** [comment]
Please DO NOT delete this template or use it for support questions.
  You are welcome to visit us on our community channels listed at https://mailcow.github.io/mailcow-dockerized-docs/#community-support
  For official support, please check https://mailcow.github.io/mailcow-dockerized-docs/#commercial-support

I will not close it. I am aware of this, just set SKIP_IP_CHECK=y as workaround.

Considering this is about NAT, the issue template would have been very helpful (nat table).

**Comment by andryyy** [comment]
I just re-checked, it is a race between acme and netfilter-mailcow being too slow to inject its rule. :/ I will probably skip that check for SNAT'ed setups.

**Comment by 707Alex707** [comment]
> Considering this is about NAT, the issue template would have been very helpful (nat table).

Added, though I think you pinpointed the issue.

**Comment by andryyy** [comment]
Thanks. :) Yes. I thought it was better to skip the IP check at all, when SNAT is active. Checking wether A == SNATv4 could be wrong, too. As long as the HTTP verification does not fail, it is ok. SNAT is not critical for that.

Thanks for your report! (see 03f173905ef9523d91af8655ead4e05c7ed46c3b)
