### ISSUE TITLE
Global Sieve Filter from webui

### ISSUE THREAD

**Issue by thomisus** [mailcow/mailcow-dockerized#3419]
Hi all,

a nice feature to have is the possibility to add a global sieve filter directly from the webui.
At the moment from the webui it is only possible to add per user sieve filters.
To add a global filter we need to edit /opt/mailcow-dockerized/data/conf/dovecot/global_sieve_after and /opt/mailcow-dockerized/data/conf/dovecot/global_sieve_before

The best way i think is to add and "extra" conf file that will be merged to existing global filters.

**Comment by andryyy** [comment]
Added.
