### ISSUE TITLE
Problem install mailcow on Debian 9

### ISSUE THREAD

**Issue by edding93** [mailcow/mailcow-dockerized#3423]
I installed Mailcow after the steps in the installation guide of mailcow. 
I installed docker and docker-compose after the steps in the installation guide of docker.

But after the installation I get some problems and Google don´t helped me.

My System:
Debian 9 
Kernel version: 4.9.0
Docker version 19.03.8, build afacb8b7f0
4gb RAM

After starting mailcow with the following command: "docker-compose up -d"
I got the following errors

ERROR: for mailcowdockerized_dovecot-mailcow_1  Cannot start service dovecot-mailcow: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: 

ERROR: for dockerapi-mailcow  Cannot start service dockerapi-mailcow: OCI runtime start failed: fork/exec /usr/bin/runc: resource temporarily unavailable: : unknown

ERROR: for dovecot-mailcow  Cannot start service dovecot-mailcow: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"fork/exec /proc/272/exe: resource temporarily unavailable\\\"\"": unknown

**Comment by felixklauke** [comment]
This usually indicates that some ressources are not available due to some limits of systemd are exceeded (e.g. pids / cgroups ). 
```
systemctl status docker | grep Tasks
```

Further information:
https://success.docker.com/article/how-to-reserve-resource-temporarily-unavailable-errors-due-to-tasksmax-setting

**Comment by edding93** [comment]
Thanks. 

This information helped me.

But now I have new errors:



`ERROR: for mailcowdockerized_nginx-mailcow_1  Cannot start service nginx-mailcow: read unix @->@/containerd-shim/moby/7cCreating mailcowdockerized_netfilter-mailcow_1 ... done`

`ERROR: for nginx-mailcow  Cannot start service nginx-mailcow: read unix @->@/containerd-shim/moby/7cc65240a3f7ae274f9ae25a7d92532ed0dfa0b667b079710f356ac175c5ece3/shim.sock: read: connection reset by peer: unknown`
`ERROR: Encountered errors while bringing up the project.`

**Comment by edding93** [comment]
Output of 

` systemctl status docker | grep Tasks`

```
  └─50-TasksMax.conf
    Tasks: 37

```

**Comment by CDaut** [comment]
I have this issue as well. How did you resolve it?

**Comment by edding93** [comment]
I installed it on a other Hostingprovider. It is a very dump solution but it worked.

**Comment by CDaut** [comment]
Unfortunately that's no option for me.
