### ISSUE TITLE
Working Docker-Swarm.yml

### ISSUE THREAD

**Issue by bf8392** [mailcow/mailcow-dockerized#3424]
Hi =)

Would it be possible to provide a working/safe swarm example? I really want to deploy Mailcow as it is the most feature-rich and experienced Mailserver I've heard about =). I use Swarmpit.io for easy server managing...so I really want to use it in swarmmode =)

Thanks for all the effort in this cool Docker-Set =)

**Comment by MAGICCC** [comment]
Not so easy to do as you may think
You need to edit a lot of things before it may work e.g. netfilter,  IPv6-NAT, SQL and other things. Also you would need to sync your data or do you want a shared storage which needs to be redundant too otherwise your SPOF is your storage.

This topic has been discussed in other issues and in our telegram group, which you can always join. 
If you have a big setup where you need a cluster solution, then you may ask @andryyy for a commercial setup.

**Comment by bf8392** [comment]
The data is not the problem...also mysql is already solved as I have a running instance...I only have problems with netfilter and Ipv6 nat, because it uses the privileged mode which is not supported in swarm...are they used to manipulate the iptables only? Because I use iptables on the docker-user chain manually...I never used mailcow before...I also would combine it with a reverseproxy (traefik) and a certdumper solution...is this possible? can you link me to the conversation please? =) thanks for all the help =)

**Comment by mkuron** [comment]
It‘s spread around between multiple issues, including #1956 #1806 #1004 #669 #479. The dockerapi container will also have problems (it doesn‘t use iptables, but the Docker socket).

**Comment by bf8392** [comment]
Ok thank you :-)

**Comment by sebastiansterk** [comment]
I would also really like to see a Docker Swarm compatible version of Mailcow.

**Comment by neben** [comment]
Now that Docker Swarm supports IPv6Nat, do you think it would make sense to reevaluate docker swarm support?

https://github.com/robbertkl/docker-ipv6nat/issues/65#issuecomment-819802613

**Comment by drsect0r** [comment]
It would be great if mailcow could work towards Docker Swarm and even Kubernetes support. It is a wonderful product but without it, it will be a limitation. I'd love to have this running on a bigger scale with multiple hosts and provide this service to clients.

**Comment by spammads** [comment]
+1
Same here.

**Comment by ghost** [comment]
+1 this feature will be great if you impalement  it

**Comment by Lin2mars** [comment]
+1 same as above.
Very usefull config.
