### ISSUE TITLE
How i instal a older Version of z.b. Sogo?

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#3425]
| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 1804 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VM esxi |
| Server/VM specifications (Memory, CPU Cores) | 10752MB ram 5 Cores |
| Docker Version (`docker version`) | 18.06.0-ce |
| Docker-Compose Version (`docker-compose version`) | 1.25.4, build 8d51620a |
| Reverse proxy (custom solution) | no |

Hello@all. I have a question, how can I get an older version of a part of Mailcow e.g. sogo, install? If I paid attention to an update a few days ago, my sogo spins around so that my VM completely freezes. Apart from the MAilco update, I have not changed anything on the VM.

**Comment by andryyy** [comment]
Hi,

try the Telegram channel or the forum. :)

You should not mix old images with newer ones. I think you have a device with wrong credentials trying to authenticate against mailcow and thus blocking your IP via netfilter-mailcow. Check netfilter-mailcow logs.

**Comment by Conan179** [comment]
No, the logging credentials are correct on the admin panel.
The Sogo site give this massage:
🐄 - we are on our way.

502
Please do not stop the stack, while we are initializing the database or do other preparations.

What is happening? - Nginx cannot connect to an upstream server.
This is fine, if mailcow was just installed or updated and can take a few minutes to complete.
Please check the logs or contact support, if the error persists.

docker-compose logs --tail=200 php-fpm-mailcow

Need support?

the watchdog mail says:
connect to address 172.22.1.248 and port 20000: Connection refused
HTTP CRITICAL - Unable to open TCP socket
connect to address 172.22.1.248 and port 20000: Connection refused
HTTP CRITICAL - Unable to open TCP socket
connect to address 172.22.1.248 and port 20000: Connection refused
HTTP CRITICAL - Unable to open TCP socket
connect to address 172.22.1.248 and port 20000: Connection refused
HTTP CRITICAL - Unable to open TCP socket
connect to address 172.22.1.248 and port 20000: Connection refused
HTTP CRITICAL - Unable to open TCP socket

sogo is not the problem, I have found so many in the meantime. i have some problem with the ip allocation.

**Comment by andryyy** [comment]
Perhaps not enough SOGo workers then.

Try 

```
docker-compose logs --tail=20000 sogo-mailcow | grep -i "no child"
```

**Comment by Conan179** [comment]
It came this:

root@"hostname":/opt/mailcow-dockerized# docker-compose logs --tail=20000 sogo-mailcow | grep -i "no child"
root@"hostname":/opt/mailcow-dockerized#
nothing.

**Comment by andryyy** [comment]
Check older logs then. 

Please do not use the bug tracker for support questions. Use the forum or the Telegram channel. :)

It is just running out of workers. Edit `data/conf/sogo/sogo.conf` and increase `WOWorkersCount`.

**Comment by Conan179** [comment]
With this
https://github.com/mailcow/mailcow-dockerized/issues/1720#issuecomment-529190093
My Sogo is running, without errors.
