### ISSUE TITLE
Quarantänesystem: Postfix returned SMTP code 554 5.7.1 : Client host rejected: Access denied , expected 250

### ISSUE THREAD

**Issue by JonnyFPV** [mailcow/mailcow-dockerized#3431]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

**Docker container logs of affected containers**:

25.3.2020, 13:24:07 | info | disconnect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c] helo=1 mail=1 rcpt=0/1 commands=2/3
-- | -- | --
25.3.2020, 13:24:07 | info | lost connection after RCPT from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]
25.3.2020, 13:24:07 | info | NOQUEUE: reject: RCPT from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]: 554 5.7.1 <mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]>: Client host rejected: Access denied; from=<g-43004890950-8827-4300107908-1585134875176@bounce.info.bonprix.de> to=<xxxxxx@meinedomain.de> proto=SMTP helo=<quarantine>
25.3.2020, 13:24:07 | info | connect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]

**Reproduction of said bug**:
Ich versuche im Quarantänesystem eine email freizugeben und erhalte diese oben genannte Fehlermeldung.  Postfix returned SMTP code 554 5.7.1 : Client host rejected: Access denied , expected 250

**- Löschen und Spam lernen funktioniert.** 

**System information**:
Neu installiertes Mailcow. Backup über das helperscript eingepielt. 

| Question | Answer |
| --- | --- |
| My operating system | Debian 10
| Virtualization technlogy KVM,
| Server/VM specifications 4gb memory, 2 cores
| Docker Version (`docker version`) 19.03.8
| Docker-Compose Version (`docker-compose version`) 1.25.4,
| Reverse proxy (custom solution) nicht in benutzung

- Output of `git diff origin/master`, any other changes to the code? nein keine änderungen.
- Neuste Version von Mailcow über das update script installiert. 
-Reboot des Servers bereits durchgeführt. 

---------------------------------------------------------------

Zweite Warnung die ich im Postfix Log sehe sporadisch: 

25.3.2020, 13:18:05 | warning | warning: symlink leaves directory: /etc/postfix/./makedefs.out

Wi oben gesagt hatte ich die Kuh in Debian 10 neu installiert. Dann das Backup aus dem Helperscript zurück gespielt. Läuft auch eigentlich soweit alles nur die 2 Fehler sind mir aufgefallen.

Vielleicht kann mir ja jemand helfen :-) Gern auch per Anydesk.

PS: Ansonsten bin ich sehr zufrieden und unterstütze das Projekt mit einer mailcow Stay-Awesome-License :-)

Gruß
Jan

**Comment by andryyy** [comment]
connect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]

2a03:4000:27:88::c?

**Comment by JonnyFPV** [comment]
> connect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]
> 
> 2a03:4000:27:88::c?

Das ist die IPv6 adresse des Servers.... Mehr kann ich damit auch nicht anfangen.

**Comment by JonnyFPV** [comment]
> connect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[2a03:4000:27:88::c]
> 
> 2a03:4000:27:88::c?

Alles klar. Läuft wieder. in der Mailcow.conf war ein IPv6 netzwerk eingetragen.  WOhl noch aus dem alten Server. Hab den Wert rausgenommen. :-D

und dazu: 25.3.2020, 13:18:05 | warning | warning: symlink leaves directory: /etc/postfix/./makedefs.out 

nehme ich mal das als Antwort : https://github.com/mailcow/mailcow-dockerized/issues/2846 

Danke vielmals!
