### ISSUE TITLE
FR: force/reencode Content-Transfer-Encoding: base64

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#3432]
Hello guys,

May I ask how can I make every email to be encoded with base64? 

Right now I find mailcow send email with original text.

Thank you.
Best regards

**Comment by mkuron** [comment]
I don't think Postfix supports re-encoding messages, and it is not generally a good idea as it would break ARC signatures. What is the problem you are trying to solve by re-encoding? Usually the client is responsible for doing some reasonable kind of encoding, and that does not necessarily have to be base64.

**Comment by pyy** [comment]
I've checked source text of emails from gmx.de etc, they use base64.  So I'm thinking, refering to privacy, if it would be safer to use base64 other than original text.

**Comment by andryyy** [comment]
It does not any privacy nor security.

Furthermore your client is responsible for message encoding. You won't gain security by using b64.

**Comment by pyy** [comment]
because all communication between different servers are using SSL at ports?

**Comment by andryyy** [comment]
You can enforce a tls policy for some servers. You can also edit your mailbox and enforce it to use TLS incoming (and/or outgoing).

**Comment by pyy** [comment]
Good idea!
Thank you guys :)

**Comment by Adorfer** [comment]
I still do not see any point behind by this issue. Certainly i do not catch the point, since it sounds for me like _"make Rot13 mandantory for enhanced security"_ 
(which is certainly not what was meant, hopefully.)
