### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TimoHD12** [mailcow/mailcow-dockerized#3434]

**Comment by ntimo** [comment]
You can use the API for this. The docs can be found at https://mailcow-hostname/api . Since this is not a issue I am going to close this.

**Comment by timo235** [comment]
How can i do that?

**Comment by andryyy** [comment]
Open https://MAILCOW_HOSTNAME/api

We are not going to implement this. It would lead to spam machines. :/

**Comment by timo235** [comment]
I did opened This
But still nothing That can really Help me
:/

**Comment by tkorves** [comment]
So, what do you expect?! There's a full documentation of the mailcow API - if you tend to create a spam-sending monster, go ahead, code your stuff upon the API - but don't bother us with that. If YOU want to create new code, YOU'RE free to do so - on YOUR own!

**Comment by timo235** [comment]
Its fine i am sorry
