### ISSUE TITLE
E-Mail address not found

### ISSUE THREAD

**Issue by msadcenko** [mailcow/mailcow-dockerized#3435]
Hi guys,

here's the problem. When I try to send an email from e.g. gmail to my mailcow address, I get the error message 'address not found + The answer from the remote server is: 550 5.2.0 No such mailbox'.
I don't know what the problem could be. Any ideas?

**Comment by Adorfer** [comment]
Please be aware, that this is an issue tracker, NOT a support channel!
For community support, please join our Telegram Channel: https://t.me/mailcow, or board: https://community.mailcow.email/
Furthermore, it's invalid due to the template beeing ignored/discarded.
So I'm closing this, sorry.
