### ISSUE TITLE
Unable to enable older TLS protocols with the tutorial

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#3436]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Hello,

I have an issue with postfix and enabling old TLS protocols as described here: https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/

Unfortunately, my client runs his software on PHP 5.4 and he is unwilling to update it. So th eonly chance for me to get his server working with the SMTP is to enable these protocols.

I did what is said in the tutorial (extra.conf files did not exist, so I made them). But unfortunately I am still ending on the same error (I tried the code on my server with PHP 7 and it worked)

**Docker container logs of affected containers**:
```
connect from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:05 mail postfix/submission/smtpd[346]: SSL_accept error from wl31-f205.wedos.net[46.28.105.83]: -1
postfix-mailcow_1    | Mar 30 07:15:05 mail postfix/submission/smtpd[346]: warning: TLS library problem: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1661:
postfix-mailcow_1    | Mar 30 07:15:05 mail postfix/submission/smtpd[346]: lost connection after STARTTLS from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:05 mail postfix/submission/smtpd[346]: disconnect from wl31-f205.wedos.net[46.28.105.83] ehlo=1 starttls=0/1 commands=1/2
postfix-mailcow_1    | Mar 30 07:15:47 mail postfix/submission/smtpd[346]: connect from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:48 mail postfix/submission/smtpd[346]: SSL_accept error from wl31-f205.wedos.net[46.28.105.83]: -1
postfix-mailcow_1    | Mar 30 07:15:48 mail postfix/submission/smtpd[346]: warning: TLS library problem: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1661:
postfix-mailcow_1    | Mar 30 07:15:48 mail postfix/submission/smtpd[346]: lost connection after STARTTLS from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:48 mail postfix/submission/smtpd[346]: disconnect from wl31-f205.wedos.net[46.28.105.83] ehlo=1 starttls=0/1 commands=1/2
postfix-mailcow_1    | Mar 30 07:15:53 mail postfix/submission/smtpd[346]: connect from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:53 mail postfix/submission/smtpd[346]: SSL_accept error from wl31-f205.wedos.net[46.28.105.83]: -1
postfix-mailcow_1    | Mar 30 07:15:53 mail postfix/submission/smtpd[346]: warning: TLS library problem: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1661:
postfix-mailcow_1    | Mar 30 07:15:53 mail postfix/submission/smtpd[346]: lost connection after STARTTLS from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:53 mail postfix/submission/smtpd[346]: disconnect from wl31-f205.wedos.net[46.28.105.83] ehlo=1 starttls=0/1 commands=1/2
postfix-mailcow_1    | Mar 30 07:15:54 mail postfix/submission/smtpd[346]: connect from wl31-f205.wedos.net[46.28.105.83]
postfix-mailcow_1    | Mar 30 07:15:54 mail postfix/submission/smtpd[346]: SSL_accept error from wl31-f205.wedos.net[46.28.105.83]: -1
```

**Reproduction of said bug**:
PHPmailer script on server with PHP 5.4

**System information**:

| Question | Answer |
| --- | --- |
| My operating system |Debian 10 64-bit|
| Is Apparmor, SELinux or similar active? |NO|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | probably VMaware
| Server/VM specifications (Memory, CPU Cores) |16GB RAM, 4cores, 200GB SSD|
| Docker Version (`docker version`) |19.03.8|
| Docker-Compose Version (`docker-compose version`)  |1.25.4|
| Reverse proxy (custom solution) | |NO|

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
**NONE**

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output. **No issue here, communication works, there is an SSL issue.**

**Comment by andryyy** [comment]
It works and they are re-enabled just fine. You can confirm it with openssl s_client. I close this as not-a-bug, because it _does_ re-enable older protocols.

Perhaps you created extra.conf in Postfix instead of extra.cf.

Please use the forum for community support. :)
