### ISSUE TITLE
LE certificate expired

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3438]
**Prior to placing the issue, please check following:**
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
The TLS/HTTPS certificates of the mail server expired for Chrome/Apple email app.
The certificate expired 29. Juni 2020 01:33:29.
According to browser certificate status:
````
Valid from Tuesday, March 31st 2020 01:33:29
Valid until Monday, June 29th 2020 01:33:29
````

Also restarting the `acme` container and even forcing a renewal results in the certificate not being updated and the container logging (see the logs below). What is also interesting/looks wrong is the path of the `cert.pem`. The domain folder is not the same as `MAILCOW_HOSTNAME` set in `mailcow.conf` but one of the additional SAN domains. However, it seems that the acme script just uses the first (`[0]`) item of the list as name.

The `force_renew` file is in place but the `acme` container still doesn't renew the certificates and deems them to be still valid, the `force_renew` file is not cleaned up.

**Docker container logs of affected containers**:
`mailcow-acme`:
````
[...]
Cannot match your IP NO_IPV6_LINK against hostname mail.[...] (DNS returned [...])
[...]
Confirmed A record [...]
Found A record for mail.[...]: [...]
[...]
Certificate /var/lib/acme/mail.[...]/cert.pem validation done, neither changed nor due for renewal.
Certificates were successfully validated, no changes or renewals required, sleeping for another day.
````

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.4 LTS |
| Is Apparmor, SELinux or similar active? | Ubuntu 18.04 LTS default |
| Virtualization technlogy | The cloud provider uses KVM. |
| Server/VM specifications (Memory, CPU Cores) | 8GB RAM, 2 (v)CPUs |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4, build 8d51620a |
| Reverse proxy (custom solution) | No proxies in front of mail server. |

**Comment by roswitina** [comment]
Letsencrypt certificates generally have a validity of 90 days to my knowledge.

**Comment by strarsis** [comment]
@roswitina: Ah, it seems to be different, the expiry duration is indeed 6 months.
It seems that the certificate is not valid for `MAILCOW_HOSTNAME`, only for the domains in `ADDITIONAL_SAN`.

For the mail server FQDN I get a `NET::ERR_CERT_COMMON_NAME_INVALID` error (HTTP and TLS).

**Comment by andryyy** [comment]
It is not a bug, acme-mailcow is working properly.

The challenge just fails for your mailcow_hostname.

The force_renew only works - as described - with an updated mailcow.

If your IPv6 in mailcow fails, but you have an AAAA record for your mailcow_hostname in DNS, it will not validate.

Please use the community channels for support. :)

**Comment by strarsis** [comment]
@andryyy: You are right! It is a known IPv6 issue.
