### ISSUE TITLE
Installing roundcube  next to the SOGo (system with SOGo already installed)

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#344]
Hi, 

I am running Mailcow dockerized on our company server, I use SOGo and I am happy with that. But many of our workers say that they hate it and they want to add roundcube, so, is it possible?

And, can you help me...how to do it? I tried to find some tutorial, but I failed.

Thanks for you time :)

**Comment by PhoenixPeca** [comment]
Hi,
Yes, it is possible and it is in the docs: https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

### Update:
I think setting up roundcube the way that it is mentioned in the docs makes updating (a little-bit) harder. IMHO, it would be more efficient to create a LAMP/LEMP server locally to host roundcube in an alias URL like `https://example.com/roundcube/` that is accessible in the web. Then set the mailcow-dockerized to run behind Apache or NGINX via reverse proxy.

**Comment by DJIronic** [comment]
Thanks,  it works :)
