### ISSUE TITLE
Sync Job displays 320 transferred e-mails. But Mailcow does not show them

### ISSUE THREAD

**Issue by Nothingtoloose** [mailcow/mailcow-dockerized#3441]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Mailcow indicates that it has imported 230 emails. These can neither be viewed via webmail (SOGo) nor via IMAP.
However, the disk space is used (see SOGo).

![sogo-1](https://user-images.githubusercontent.com/10338835/78052863-024f9700-7380-11ea-8389-00d6c76f2848.png)
![sogo-2](https://user-images.githubusercontent.com/10338835/78052868-04195a80-7380-11ea-9e63-0874050dc417.png)

**Sync Job Log:**
Here is imapsync 1.977 on host mail.xxxxx.de, a linux system with 0.0/1.9 free GiB of RAM
with Perl 5.28.1 and Mail::IMAPClient 3.42
Transfer started at Tue Mar 31 16:27:04 2020
PID is 351 my PPID is 340
Load is 0.00 0.87 1.38 1/663 on 1 cores
Current directory is /var/tmp
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 1.977 $ $Date: 2019/12/23 20:18:02 $ 
Command line used, run by /usr/bin/perl:
/usr/local/bin/imapsync --tmpdir /tmp --nofoldersizes --subfolder2 eis --subscribeall --automap --tls1 --host1 yyyy.de --user1 eis@yyyy.de --passfile1 /tmp/imapsync.m2rrm4i --port1 143 --host2 localhost --user2 test@xxxxx.de*7fx64dd9kd8k806g@mailcow.local --passfile2 /tmp/imapsync.t321NUd --no-modulesversion --noreleasecheck
Temp directory is /tmp ( to change it use --tmpdir dirpath )
Under docker context so installing only signals to exit
kill -INT 351 # special behavior: call to sub catch_exit
kill -QUIT 351 # special behavior: call to sub catch_exit
kill -TERM 351 # special behavior: call to sub catch_exit
No variable pid_filename
PID file is unset ( to set it, use --pidfile filepath ; to avoid it use --pidfile "" )
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Host2: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe ) 
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: IMAP server [yyyy.de] port [143] user [eis@yyyy.de]
Host2: IMAP server [localhost] port [993] user [test@xxxxx.de*7fx64dd9kd8k806g@mailcow.local]
Host1: connecting and login on host1 [yyyy.de] port [143] with user [eis@yyyy.de]
Host1 IP address: 37.221.xxx.xxx
Host1 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready.
Host1 capability before authentication: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED
Host1: Socket successfuly converted to SSL
Host1: yyyy.de says it has CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [yyyy.de] with user [eis@yyyy.de] auth [LOGIN]
Host2: connecting and login on host2 [localhost] port [993] with user [test@xxxxx.de*7fx64dd9kd8k806g@mailcow.local]
Host2 IP address: ::1
Host2 banner: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host2 capability before authentication: IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH
Host2: localhost says it has CAPABILITY for AUTHENTICATE LOGIN
Host2: success login on [localhost] with user [test@xxxxx.de*7fx64dd9kd8k806g@mailcow.local] auth [LOGIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability once authenticated: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE THREAD I18NLEVEL CONTEXT
Host2 capability once authenticated: IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE LITERAL+ NOTIFY METADATA SPECIAL-USE COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk THREAD I18NLEVEL CONTEXT SNIPPET PREVIEW STATUS COMPRESS RIGHTS

Host1: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid
Sending: 6 ID ("name" "imapsync" "version" "1.977" "os" "linux" "vendor" "Gilles LAMIRAL" "support-url" "https://imapsync.lamiral.info/" "date" "23-Dec-2019 20:18:02 +0000" "side" "host1")
Sent 181 bytes
Read: 	* ID ("name" "Dovecot")
  	6 OK ID completed (0.000 + 0.000 secs).

Host2: found ID capability. Sending/receiving ID, presented in raw IMAP for now.
In order to avoid sending/receiving ID, use option --noid
Sending: 4 ID ("name" "imapsync" "version" "1.977" "os" "linux" "vendor" "Gilles LAMIRAL" "support-url" "https://imapsync.lamiral.info/" "date" "23-Dec-2019 20:18:02 +0000" "side" "host2")
Sent 181 bytes
Read: 	* ID ("name" "Dovecot")
  	4 OK ID completed (0.001 + 0.000 secs).

Host2: found quota, presented in raw IMAP
Sending: 5 GETQUOTAROOT INBOX
Sent 22 bytes
Read: 	* QUOTAROOT INBOX Userquota
  	* QUOTA Userquota (STORAGE 2 3145728)
  	5 OK Getquotaroot completed (0.003 + 0.000 + 0.002 secs).

Host2: Quota current storage is 2048 bytes. Limit is 3221225472 bytes. So 0.00 % full
Host1: found 6 folders.
Host2: found 6 folders.
Host1: guessing separator from folder listing: [/]
Host1: separator given by NAMESPACE: [/]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [/]
Host1: guessing prefix from folder listing: []
Host1: prefix given by NAMESPACE: []
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1: separator and prefix: [/][]
Host2: separator and prefix: [/][]
Turning off automapping folders because of --subfolder2
Sanitizing subfolder2: [eis] => [eis]
Including all folders found by default. Use --subscribed or --folder or --folderrec or --include to select specific folders. Use --exclude to unselect specific folders.
Host1: Checking wanted folders exist. Use --nocheckfoldersexist to avoid this check (shared of public namespace targeted).
Host1: Checking wanted folders are selectable. Use --nocheckselectable to avoid this check.
Turned off automapping folders ( use --automap to turn on automapping )

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the utf8 output just printed for convenience, to recognize it.

Host1: folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren) "/" INBOX
17 OK List completed (0.000 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Host2: folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \Archive) "/" Archive
* LIST (\HasNoChildren \UnMarked \Sent) "/" Sent
* LIST (\HasNoChildren \UnMarked \Drafts) "/" Drafts
* LIST (\HasNoChildren \Trash) "/" Trash
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" INBOX
10 OK List completed (0.001 + 0.000 secs).

[Archive]
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

++++ Looping on each one of 6 folders to sync
Folder     1/6 [Archive]                           -> [eis/Archive]                      
Host1: folder [Archive] has 0 messages in total (mentioned by SELECT)
Creating folder [eis/Archive] on host2
Creating folder [eis] on host2
Created folder [eis] on host2
Created folder [eis/Archive] on host2
Host2: folder [eis/Archive] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/Archive] permanentflags: 
Host2: Subscribing to folder eis/Archive
Host1: folder [Archive] considering 0 messages
Host2: folder [eis/Archive] considering 0 messages
Host1: folder [Archive] selected 0 messages, duplicates 0
Host2: folder [eis/Archive] selected 0 messages, duplicates 0
Folder     2/6 [Drafts]                            -> [eis/Drafts]                       
Host1: folder [Drafts] has 0 messages in total (mentioned by SELECT)
Creating folder [eis/Drafts] on host2
Created folder [eis/Drafts] on host2
Host2: folder [eis/Drafts] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/Drafts] permanentflags: 
Host2: Subscribing to folder eis/Drafts
Host1: folder [Drafts] considering 0 messages
Host2: folder [eis/Drafts] considering 0 messages
Host1: folder [Drafts] selected 0 messages, duplicates 0
Host2: folder [eis/Drafts] selected 0 messages, duplicates 0
Folder     3/6 [INBOX]                             -> [eis/INBOX]                        
Host1: folder [INBOX] has 228 messages in total (mentioned by SELECT)
Creating folder [eis/INBOX] on host2
Created folder [eis/INBOX] on host2
Host2: folder [eis/INBOX] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/INBOX] permanentflags: 
Host2: Subscribing to folder eis/INBOX
Host1: folder [INBOX] considering 228 messages
Host2: folder [eis/INBOX] considering 0 messages
Host1: folder [INBOX] selected 228 messages, duplicates 0
Host2: folder [eis/INBOX] selected 0 messages, duplicates 0
msg INBOX/1 {575}             copied to eis/INBOX/1          0.23 msgs/s  0.131 KiB/s 0.562 KiB copied 
msg INBOX/2 {3598}            copied to eis/INBOX/2          0.46 msgs/s  0.941 KiB/s 4.075 KiB copied 
msg INBOX/3 {61196}           copied to eis/INBOX/3          0.69 msgs/s  14.619 KiB/s 63.837 KiB copied 
msg INBOX/4 {61322}           copied to eis/INBOX/4          0.91 msgs/s  28.101 KiB/s 123.722 KiB copied 
...
...
msg INBOX/225 {61988}         copied to eis/INBOX/225        13.27 msgs/s  1.472 MiB/s 24.966 MiB copied 
msg INBOX/226 {62000}         copied to eis/INBOX/226        13.27 msgs/s  1.470 MiB/s 25.025 MiB copied 
msg INBOX/227 {61968}         copied to eis/INBOX/227        13.30 msgs/s  1.470 MiB/s 25.084 MiB copied 
msg INBOX/228 {61874}         copied to eis/INBOX/228        13.31 msgs/s  1.468 MiB/s 25.143 MiB copied 
Folder     4/6 [Junk]                              -> [eis/Junk]                         
Host1: folder [Junk] has 0 messages in total (mentioned by SELECT)
Creating folder [eis/Junk] on host2
Created folder [eis/Junk] on host2
Host2: folder [eis/Junk] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/Junk] permanentflags: 
Host2: Subscribing to folder eis/Junk
Host1: folder [Junk] considering 0 messages
Host2: folder [eis/Junk] considering 0 messages
Host1: folder [Junk] selected 0 messages, duplicates 0
Host2: folder [eis/Junk] selected 0 messages, duplicates 0
Folder     5/6 [Sent]                              -> [eis/Sent]                         
Host1: folder [Sent] has 2 messages in total (mentioned by SELECT)
Creating folder [eis/Sent] on host2
Created folder [eis/Sent] on host2
Host2: folder [eis/Sent] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/Sent] permanentflags: 
Host2: Subscribing to folder eis/Sent
Host1: folder [Sent] considering 2 messages
Host2: folder [eis/Sent] considering 0 messages
Host1: folder [Sent] selected 2 messages, duplicates 0
Host2: folder [eis/Sent] selected 0 messages, duplicates 0
msg Sent/1 {7330}            copied to eis/Sent/1          13.17 msgs/s  1.446 MiB/s 25.150 MiB copied 
msg Sent/2 {2339}            copied to eis/Sent/2          13.21 msgs/s  1.444 MiB/s 25.152 MiB copied 
Folder     6/6 [Trash]                             -> [eis/Trash]                        
Host1: folder [Trash] has 0 messages in total (mentioned by SELECT)
Creating folder [eis/Trash] on host2
Created folder [eis/Trash] on host2
Host2: folder [eis/Trash] has 0 messages in total (mentioned by SELECT)
Host2: folder [eis/Trash] permanentflags: 
Host2: Subscribing to folder eis/Trash
Host1: folder [Trash] considering 0 messages
Host2: folder [eis/Trash] considering 0 messages
Host1: folder [Trash] selected 0 messages, duplicates 0
Host2: folder [eis/Trash] selected 0 messages, duplicates 0
++++ End looping on each folder
++++ Statistics
Transfer started on                     : Tue Mar 31 16:27:04 2020
Transfer ended on                       : Tue Mar 31 16:27:24 2020
Transfer time                           : 20.3 sec
Folders synced                          : 6/6 synced
Messages transferred                    : 230 
Messages skipped                        : 0
Messages found duplicate on host1       : 0
Messages found duplicate on host2       : 0
Messages found crossduplicate on host2  : 0
Messages void (noheader) on host1       : 0  
Messages void (noheader) on host2       : 0
Messages found in host1 not in host2    : 0 messages
Messages found in host2 not in host1    : 0 messages
Messages deleted on host1               : 0
Messages deleted on host2               : 0
Total bytes transferred                 : 26373806 (25.152 MiB)
Total bytes skipped                     : 0 (0.000 KiB)
Message rate                            : 11.3 messages/s
Average bandwidth rate                  : 1268.9 KiB/s
Reconnections to host1                  : 0
Reconnections to host2                  : 0
Memory consumption at the end           : 176.5 MiB (started with 159.9 MiB)
Load end is                             : 0.23 0.86 1.36 2/662 on 1 cores
Biggest message                         : 3125327 bytes (2.981 MiB)
Memory/biggest message ratio            : 59.2
The sync looks good, all 230 identified messages in host1 are on host2.
There is no unidentified message
The sync is strict, all 230 identified messages in host2 are on host1.
Detected 0 errors

Check if a new imapsync release is available by adding --releasecheck
Homepage: https://imapsync.lamiral.info/
Exiting with return value 0 (EX_OK: successful termination) 0/50 nb_errors/max_errors

**Docker container logs of affected containers**:

**Reproduction of said bug**:
I have tried several times with different accounts (mailcow) and import accounts and never emails are displayed.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 64bit |
| Is Apparmor, SELinux or similar active? | no|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** |  |
| Server/VM specifications (Memory, CPU Cores) |2 Core, 2 GB |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4, build 8d51620a |
| Reverse proxy (custom solution) | Traefik v2 |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Hi,

click the dark grey folder icon to the left of "eis". :)

André

**Comment by Nothingtoloose** [comment]
> Hi,
> 
> click the dark grey folder icon to the left of "eis". :)
> 
> André

it works.

thanks a lot :)
