### ISSUE TITLE
imaps dose not work

### ISSUE THREAD

**Issue by yousifAlkha** [mailcow/mailcow-dockerized#3443]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**: hello,
I've installed a new mailcow instance , create a domain and a mailbox , I've tried to login to the email with imaps 993 and smtp starttls 587 , the problem is imaps is not working when , selinux disabled and port 993 is reachable though telnet   

**Docker container logs of affected containers**:
imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.31.0.56, lip=172.22.1.250, TLS handshaking: SSL_accept() failed: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca: SSL alert number 48

**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | CentOS 7 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 16GB , 10 cores  |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4, |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Hi,

Looks like you are using STARTTLS on Port 993 (which should be TLS/SSL wrapped) or your client is too old and cannot talk TLS => 1.2 (see https://mailcow.email/2020/02/12/tls-1-0-and-1-1-is-now-disabled-for-pop3-s-imap-s-smtps-and-submission/)

Please use the community channels for support questions. :) Thanks for filling out the issue template anyway! 😄

**Comment by yousifAlkha** [comment]
Hi Andry,
Thanks for your quick response , and i'm sorry for posting the question here.

I've update my client, enabled the weak protocols, fixed the keys and restart the dockers.
but i still face the same issue , the logs are also the same.

Thanks in advance.

**Comment by andryyy** [comment]
Did you restart the services? Is your client using even weaker protocols or ciphers?

**Comment by yousifAlkha** [comment]
Yes i restarted the service , as for the client i'm using Thunderbird 68.6.0 which should not have this problem because i have another mail system using TLSv1 and it's working fine, also i have another mailcow instance it's not a very new version, it's based on Docker version 18.09.3 and it's also working fine on the same client, lastly I've tried it on outlook 2016 , but still i can't log in

**Comment by andryyy** [comment]
Not sure then. Verify the ports. Make sure you use STARTTLS on 143 OR SSL on port 993.
