### ISSUE TITLE
Quota used, unlimited only hint

### ISSUE THREAD

**Issue by itkfm** [mailcow/mailcow-dockerized#3444]
**Is your feature request related to a problem? Please describe.**
#2713 

I'm always confused when my mailcow is forcing me to create an unlimited mailbox because a domain’s quota is exceeded.

**Describe the solution you'd like**
Mailcow could show me a short hint what’s going on and why.

**Comment by andryyy** [comment]
Thanks, I added it and will push it soon.

**Comment by itkfm** [comment]
neat, thanks :ok_hand:

**Comment by andryyy** [comment]
fd73bbc201119b45d13597a01fbb6cae2885a225 :)
