### ISSUE TITLE
14gb in use - fresh server

### ISSUE THREAD

**Issue by rt050** [mailcow/mailcow-dockerized#3454]
Hi there,

I'm about to sync over mail from old servers when I noticed a high amount of disk space in use for what is basically a fresh server.

/var/vmail on /dev/sda2
14G / 64G (23%)

I've not really touched much on this server yet apart from 2 transports and 2 mailboxes for testing. I've noticed there's 3.8 swap.img too.

This is my second mailcow install and I've not seen high storage like this when the server is sat doing nothing. Any ideas?

Thanks

**Comment by andryyy** [comment]
Please use the community for these questions. :)

We don't create swap files.

We provide a fully featured mail suite, this takes some bytes. We mostly use the same base imags, so overlayfs will re-use most layers.

It does not use 14 though. Not even 10. You might want to run `ncdu /`.
