### ISSUE TITLE
Not required die in backup script

### ISSUE THREAD

**Issue by mkapra** [mailcow/mailcow-dockerized#3456]
**Is your feature request related to a problem? Please describe.**
I get the following error when using the backup_and_restore.sh script:
`/backup/mail is not write-able for others, that's required for a backup.`

**Describe the solution you'd like**
I commented out the following if-condition and the script was working.
So my question is why the directory has to be write-able for others?

https://github.com/mailcow/mailcow-dockerized/blob/59b38c1111ff52036084ae5039605f6651041348/helper-scripts/backup_and_restore.sh#L43-L46

**Comment by andryyy** [comment]
Some backups need this. Not everything is written as the user you are running the script.

I implemented it for a good reason. I should have documented it, but my lack of memory today does not mean it isn't there for a good reason. 😄

**Comment by mkapra** [comment]
Hm okay. A diff on a directory with the write permissions for others enabled and without this permissions and without the check said there are no missing files or something.
But if there were some errors I will only comment this out in my repository.
It is essential for me, that not everybody can read the backup.

**Comment by clauso** [comment]
I made a pull request for this and put some time into the reasoning there, why this check should be removed: https://github.com/mailcow/mailcow-dockerized/pull/4148
