### ISSUE TITLE
Please help i am stuck at kernel panic 5.3.0-18-generic

### ISSUE THREAD

**Issue by DeadlyMars** [mailcow/mailcow-dockerized#3459]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

**Docker container logs of affected containers**:

**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by DeadlyMars** [comment]
I can’t wait

**Comment by fionera** [comment]
Wat?

**Comment by patschi** [comment]
Mailcow != Kernel. Not gonna comment further on that.

**Comment by DeadlyMars** [comment]
> Wat?Can you help me please
I am sorry but my father will kill me if he knows that

**Comment by patschi** [comment]
It has nothing to do with mailcow. It's the kernel from your operating system what blows up.
Beside that: You successfully ignored the first three checkboxes.

**Comment by DeadlyMars** [comment]
No I didn’t ignored it i cant tick the boxes

**Comment by DeadlyMars** [comment]
I am so sorry please help me

**Comment by Braintelligence** [comment]
Don't feed the troll guys 🤣

**Comment by patschi** [comment]
Issue not mailcow-related. Locking.
