### ISSUE TITLE
Scheduled ClamAV Scan rather than on all the time

### ISSUE THREAD

**Issue by RealOrangeOne** [mailcow/mailcow-dockerized#346]
The ClamAV container uses over half the available memory on my VPS, for something I don't necessarily want, or at least not all the time.

What's the best solution for not using ClamAV? Looking through the source briefly shows a link between that and rspamd, which i very much need. This makes me think simply stopping the container isnt the right solution?

Alternatively, is it possible to set the container up in a way that it only does a weekly scan of emails, rather than needing to be on all the time? So the container is only using that amount of memory for a short period of time before sleeping again. This would be a really nice feature, especially if it were editable in the admin!

**Comment by mkuron** [comment]
You can remove/comment out the entire clamav container and the row in the rspamd container that links it to the clamav container. Rspamd will give up trying to connect to ClamAV after a few seconds. It also remembers that ClamAV is unreachable and doesn't try connecting to it again for a while. So you don't even need to change anything in Rspamd's config if you disable ClamAV.

I wouldn't consider a weekly scan of emails very useful. It would leave a very large time window during which you might be reading harmful messages in your mailbox.

**Comment by RealOrangeOne** [comment]
Aha, perfect! Solves my issue. Thanks!
