### ISSUE TITLE
Automatic backup mail queue processing

### ISSUE THREAD

**Issue by robetus** [mailcow/mailcow-dockerized#3463]
I recently added a backup/relay mail server using this fantastic tutorial: https://autoize.com/backup-mx-configuration-for-mailcow/ and it's working as long as I log in to the backup server and flush the queue manually. I created a cron job on the backup server to run a flush every 30 minutes:
`*/30 * * * * cd /opt/mailcow-dockerized && docker-compose exec postfix-mailcow postqueue -p`
just in case my primary server goes down. Is there any way in the GUI to have the queue processed automatically or is the backup mail server just to store the mail while the primary is down and not do anything with it until you login and flush it manually? It would be great if this could be done automatically somehow.

**Comment by herbetom** [comment]
The queue does get automatically processed. At least for me. No need for a cronjob.

**Comment by andryyy** [comment]
That's true. I will close it, please use the community for questions. :) Edit: There are queue lifetimes and periods defined in postconf. Sooner or later it will flush the queue. You can also add a transport for your relayed domains to the "transport maps" table in mailcow UI, so it does not say "loops back to myself", while the primary is offline. It is just a cosmetic error.
