### ISSUE TITLE
Error by ./helper-scripts/backup_and_restore.sh restore allways "

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#3464]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
I wanted to restore a backup using the script "./helper-scripts/backup_and_restore.sh restore"
The problem is, no matter which of my backups I take, I always get the error message:
"Selected backup location has no subfolders"

**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Vmware ESXi |
| Server/VM specifications (Memory, CPU Cores) | 4xcores 5gb RAM |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) |  1.25.4, build 8d51620a |
| Reverse proxy (custom solution) | no |

**Comment by capps1994** [comment]
Just for info as I ran into this. say you back up directory is in folder like /root/docker-compose/mailcow-dockerized-old/backups/mailcow-2020-12-14-23-47-50 you need to go back a directory to  /root/docker-compose/mailcow-dockerized-old/backups/

hope this helps someone :)

**Comment by antonstech** [comment]
@capps1994 Thanks :D

**Comment by gh0stwolf** [comment]
@capps1994 Still helping people. Give credit to where it goes!
