### ISSUE TITLE
Prefilter changes do not restart dovecot container

### ISSUE THREAD

**Issue by realizelol** [mailcow/mailcow-dockerized#3466]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**: Postfilter change will restart dovecot but prefilter won't.

**Docker container logs of affected containers**:
dovecot-mailcow_1    | global_sieve_before: line 4: warning: no newline (CRLF) at end of hash comment at end of file.
dovecot-mailcow_1    | global_sieve_after: line 26: warning: no newline (CRLF) at end of hash comment at end of file.
dovecot-mailcow_1    | The user `vmail' is already a member of `tty'.
dovecot-mailcow_1    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow_1    |                                  Dload  Upload   Total   Spent    Left  Speed
100   98k  100   98k    0     0   534k      0 --:--:-- --:--:-- --:--:--  534k
dovecot-mailcow_1    | 20_blatspammer.cf
dovecot-mailcow_1    | 70_HS_body.cf
dovecot-mailcow_1    | 70_HS_header.cf
dovecot-mailcow_1    | 2020-04-12 14:41:25,844 INFO Set uid to user 0 succeeded
dovecot-mailcow_1    | 2020-04-12 14:41:25,847 INFO supervisord started with pid 1
dovecot-mailcow_1    | 2020-04-12 14:41:26,852 INFO spawned: 'processes' with pid 110
dovecot-mailcow_1    | 2020-04-12 14:41:26,857 INFO spawned: 'cron' with pid 111
dovecot-mailcow_1    | 2020-04-12 14:41:26,862 INFO spawned: 'dovecot' with pid 112
dovecot-mailcow_1    | 2020-04-12 14:41:26,868 INFO spawned: 'syslog-ng' with pid 113
dovecot-mailcow_1    | [2020-04-12T14:41:26.986350] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
dovecot-mailcow_1    | Apr 12 14:41:26 ~hostname~ syslog-ng[113]: syslog-ng starting up; version='3.19.1'
dovecot-mailcow_1    | Apr 12 14:41:27 ~hostname~ dovecot: master: Dovecot v2.3.10 (0da0eff44) starting up for imap, sieve, lmtp, pop3
dovecot-mailcow_1    | 2020-04-12 14:41:28,013 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2020-04-12 14:41:28,013 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2020-04-12 14:41:28,013 INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2020-04-12 14:41:28,013 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Reproduction of said bug**: Enter some dashes to file and validate check it. (pre-|postfilter)

**System information**: Xeon E3-1230L v5 | 16GB RAM | 256GB SSD + 1TB SSD

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | Apparmor |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare |
| Server/VM specifications (Memory, CPU Cores) | 6GB, 3 Cores |
| Docker Version (`docker version`) | 19.03.6 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | NO |

- No changes at all. Just the code below for testing purpose.

The code
```
              $restart_reponse = json_decode(docker('post', 'dovecot-mailcow', 'restart'), true);
              if ($restart_reponse['type'] == "success") {
                $_SESSION['return'][] = array(
                  'type' => 'success',
                  'log' => array(__FUNCTION__, $_action, $_type, $_data_log, $_attr),
                  'msg' => 'dovecot_restart_success'
                );
              }
              else {
                $_SESSION['return'][] = array(
                  'type' => 'warning',
                  'log' => array(__FUNCTION__, $_action, $_type, $_data_log, $_attr),
                  'msg' => 'dovecot_restart_failed'
                );
              }
```
should also be added between line [99 and 100](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.mailbox.inc.php#L99-L100)

best regards
realizelol

**Comment by andryyy** [comment]
Thanks, will fix it.
