### ISSUE TITLE
U2F with USB Dongle not working

### ISSUE THREAD

**Issue by herbetom** [mailcow/mailcow-dockerized#3468]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**: Since i just updated mailcow to the latest Version i can't login with my U2F YubiKey.
Chrome and Firefox both output something like this in the console:

```
(index):213 Uncaught ReferenceError: appId is not defined
    at (index):213
```
This Issue seems similar to #936 and #937 from 2 years ago. 

If i had to guess i would say that it has soemthing to do with 8f4540d5d9f1c85fbb1c9697ccb9653f8744779d from 2 days ago.

Since it is a JS Problem i will now stop filling out this template and hope that is okay.

**Comment by tobimori** [comment]
Got the same issue.

**Comment by andryyy** [comment]
Hi, I will check and fix it in a bit.

**Comment by andryyy** [comment]
Thanks. :)

**Comment by herbetom** [comment]
Thank you for the really fast fix! It works for me. I didn't even had to disable 2FA temporarily! :+1:

**Comment by andryyy** [comment]
Thanks for our feedback!

Forgot my Yubi in the office. :)
