### ISSUE TITLE
sender-dependent Transport maps

### ISSUE THREAD

**Issue by guardiande** [mailcow/mailcow-dockerized#3472]
**Is your feature request related to a problem? Please describe.**
I just stumbled upon Mailcow and like the project very much.

My current setup is Exim and Dovecot to consolidate mail from many accounts at standard mail providers like gmx.de, let's say I have addresses a@gmx.de and b@gmx.de. To be clear I don't own the gmx.de domain. The addresses have different login credentials at gmx. I'd like to implement that setup with Mailcow.

To be able to send mails originating from a@gmx.de and b@gmx.de through Mailcow and then relay to gmx I would need to have multiple sender-dependent routings - individually for a und b instead of just one per domain.

**Describe the solution you'd like**
Provide mailbox based smart hosts.

**Comment by mkuron** [comment]
I checked years ago and Exim had such a feature while Postfix did not. http://www.postfix.org/postconf.5.html#sender_dependent_default_transport_maps looks like it might work.

**Comment by andryyy** [comment]
I don't think we should support such scenarios. You can always use the GMX SMTP to relay your GMX mail.

Furthermore we already have sender dependent transport maps in the UI. I don't know, how GMX handles your "from" command. You probably need to force an envelope + header. Quick Google result: https://serverfault.com/questions/147921/forcing-the-from-address-when-postfix-relays-over-smtp

**Comment by guardiande** [comment]
Thanks for your comments. I think my mail paradigm does not fit Mailcow because it's a very individual ways of consolidating multiple mail accounts in a single smtp/imap account.

I will dockerize Exim and Dovecot myself and will stick with the paradigm I currently have.

Good luck with your great product!
