### ISSUE TITLE
Split long DKIM TXT records

### ISSUE THREAD

**Issue by stv0g** [mailcow/mailcow-dockerized#3473]
I now ran into a pretty annoying issue when configuring my DKIM DNS resource records.
According to the RFC TXT RRs are not allowed to contain strings with a length of more than 255 characters.

See: https://kb.isc.org/docs/aa-00356

However 2048bit DKIM keys produce a DKIM record which is longer than that.

I propose to split the TXT RRs at a 255 character boundary:

### Before

```
v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1qIDAYDu0MnLWfTLcr7N+VAfsLkUjKIvZqJTkntbH5hU5wYJHpCmKDlpA1PnBHmcSY7vgtM9T3dpsy/IIkAbGQ3L66OzRI0GF4on3Vb5OL0reiUKULM/9M1GJzrmJfuegHqMN1EeR/NG6MDqey5gBxbAL7jjIsNBvp0T+YylrYh+h5w3ppgI8caaD7Fph1itOT317S4/SZ42qOLPy5nRCsorkUb/tBU7JUq9lva/XV9hTz3tdeCBf1oOPC/gF9UiNS2jEgNra1xMuOkiEsrg75sv7ZkZerzgpuXF6/Q4L1Z2DOZxZnXw8A/cTaYO+qLrNU6sqT/EdeAbY6CK9WwNBwIDAQAB
```

### After

```
"v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1qIDAYDu0MnLWfTLcr7N+VAfsLkUjKIvZqJTkntbH5hU5wYJHpCmKDlpA1PnBHmcSY7vgtM9T3dpsy/IIkAbGQ3L66OzRI0GF4on3Vb5OL0reiUKULM/9M1GJzrmJfuegHqMN1EeR/NG6MDqey5gBxbAL7jjIsNBvp0T+YylrYh+h5" "w3ppgI8caaD7Fph1itOT317S4/SZ42qOLPy5nRCsorkUb/tBU7JUq9lva/XV9hTz3tdeCBf1oOPC/gF9UiNS2jEgNra1xMuOkiEsrg75sv7ZkZerzgpuXF6/Q4L1Z2DOZxZnXw8A/cTaYO+qLrNU6sqT/EdeAbY6CK9WwNBwIDAQAB"
```

I see this problem is propably very dependent on the DNS interface of the particular provider.
In my case it was FreeIPA. But the problem also arises when people editing their Zonefiles by hand.

We should at least show a warning..

Possibly related: #2246

**Comment by andryyy** [comment]
Hi, I see and I am aware. But every sane API is able to handle that today. Not planning to change that, but I could add a vars.inc.php setting to change it globally.

**Comment by stv0g** [comment]
I agree. I should probably file a bug report with FreeIPA then...

**Comment by andryyy** [comment]
Let's make it optional. :)

**Comment by chriscroome** [comment]
Thanks @andryyy it'll save me from having to use `255|` in vim to find where to split the line for Bind 9.

**Comment by andryyy** [comment]
\o/
