### ISSUE TITLE
MS Exchange ActiveSync throwing an error on Android

### ISSUE THREAD

**Issue by physanus** [mailcow/mailcow-dockerized#3479]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
After installing my own instance of Mailcow I tried adding the account to my Android phone using MS Exchange ActiveSync, but it did throw an error. After some troubleshooting I tried to add the demo account `demo@440044.xyz` / `moohoo` as mentioned [here](https://mailcow.email), but it also failed.
1. I strictly followed [this](https://mailcow.github.io/mailcow-dockerized-docs/client/client-android) tutorial. [First step](https://i.imgur.com/shmfU8b.jpg), [second step](https://i.imgur.com/fHE3XZd.jpg), [error](https://i.imgur.com/0cnlfZn.jpg)
2. I tried adding the account via my Calendar app. Same error, but however, it's also the same UI
3. I also tried adding the account via the Gmail app, it also [errors out](https://i.imgur.com/uqnvhcM.jpg)

Changing the exchage server (`440044.xyz` => `mailcow.email`) also did not help. So I assume either the documentation is wrong and I'd have to enter some additional values which I do not know about or the MS Exchange ActiveSync is actually broken ATM. 
I read through some other issues concerning this topic but they are either pretty old/outdated or do not cover that topic.

Tbh, I do not really care about the way email/calendar/contacts get synchronized, I just want them to be synced. So if there's another way, please tell me (which, however, would not change this issue).

**Docker container logs of affected containers**:
None

**Reproduction of said bug**:
- Follow the [doc](https://mailcow.github.io/mailcow-dockerized-docs/client/client-android) and try to set up the demo-account using MS Exchange ActiveSync in Samsung Email or Gmail (Android).

**System information**:
- Official demo account
- Samsung S8+ / latest updates / w/ and w/o VPN

| Question | Answer |
| --- | --- |
| My operating system | Android |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | --- |
| Server/VM specifications (Memory, CPU Cores) | --- |
| Docker Version (`docker version`) | --- |
| Docker-Compose Version (`docker-compose version`) | --- |
| Reverse proxy (custom solution) | --- |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

Thanks for your help.

**Comment by andryyy** [comment]
A) It is docs, not a tutorial :)

B) That's not a correct server name. Use MAILCOW_HOSTNAME as server name or let it autodiscover the correct settings (we don't set an autodiscover for the demo).

mailcow.email is _never_ used as server anywhere, there is no mailcow installation on this URL.

I don't know if EAS is enabled anway, you could try demo.mailcow.email as server name. Always use the FQDN. It does not say "use the domain name here". :)

If you need support, use the community, please.

**Thank you** for using the template anyway! :) Appreciated.

**Comment by physanus** [comment]
Well, with https://autodiscover.mailcow.email/mail/config-v1.1.xml being accessible I assumed that'd be working :D
Thanks for the answer, it was never meant to be a support ticket.

**Comment by andryyy** [comment]
Oh, sorry, that's my test installation. :-D A bit confusing. :-(
