### ISSUE TITLE
Can't create a specific filter in SOGo

### ISSUE THREAD

**Issue by omittedcoder** [mailcow/mailcow-dockerized#348]
Even after filling all blanks out, the OK-Button does not get activated. I already tried different combinations on multiple systems, but on none of them it worked. Presumably an issue of the auto-correction check, which checks if every blank is filled out, but never activates the button.

I don't know if this is fixed in a newer release of SOGo, maybe the image just needs to be updated?

![screenshot_20170611_140340](https://user-images.githubusercontent.com/22686398/27011015-3807046e-4eb2-11e7-855e-12a23505a60b.png)

**Comment by chaosbunker** [comment]
I guess you are using the most recent version of mailcow? I updated earlier today and just checked and I can create filters without any issues...

**Comment by omittedcoder** [comment]
Hi @chaosbunker,
yeah I am using the latest version of the master branch and pulled the latest images from Docker Hub.
Then I added a domain and mailbox-user, but can not create a sieve filter with SOGo for this user.
Maybe my settings are wrong?

**Comment by chaosbunker** [comment]
Did you Restart SOGo via the mailcow Admin UI after adding domain and mailbox?
<img width="297" alt="screen shot 2017-06-12 at 12 10 00" src="https://user-images.githubusercontent.com/16366980/27029329-2245ba56-4f68-11e7-9d1e-9508bc86c3b6.png">

**Comment by omittedcoder** [comment]
@chaosbunker sure, could I login if I didn't?
Also thanks for trying to help me!

**Comment by omittedcoder** [comment]
I have no idea how to solve this or what could cause this issue.
Does anyone have this issue too?
SOGo-logs are not helpful either.

**Comment by andryyy** [comment]
Have not seen this issue. You should ask this @ SOGo.

**Comment by omittedcoder** [comment]
I found a work around for my problem. I can create filters now, but for the specific configuration, like in my image above, I need to do the following:

1. define a rule with a condition
2. add a condition
3. select the rule without any conditions(all messages), then OK gets activated
4. add actions

I could create some filters, so my issue title is actually wrong and I changed it. Sorry for any confusion.
But this is still a strange behaviour, it looks like it is checking if there are any conditions even if there are not needed.

**Comment by andryyy** [comment]
That's strange.

Can you create an issue @ SOGos bug tracker?

**Comment by omittedcoder** [comment]
@andryyy Sure, there it is: [https://sogo.nu/bugs/view.php?id=4200](https://sogo.nu/bugs/view.php?id=4200)

**Comment by omittedcoder** [comment]
Got fixed in: inverse-inc/sogo@6c654e0f900025d811e975e96a66cd125ae6f73d
So we will probably see it in a future release.

**Comment by andryyy** [comment]
Thanks! :) Cool.
