### ISSUE TITLE
Dovecot can't run

### ISSUE THREAD

**Issue by forall** [mailcow/mailcow-dockerized#3480]
Hi,

I setup a clean install and the latest version, but I see some problem with dovecot, it can't run properly... this is from doceker coitainer log

docker logs 9b58920139d2
Waiting for database to come up...
Waiting for database to come up...
Waiting for database to come up...
Uptime: 1  Threads: 8  Questions: 7  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 7.000
Adding user `vmail' to group `tty' ...
Adding user vmail to group tty
Done.
Waiting for versions table to be created...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Waiting for versions table to be created...
Waiting for versions table to be created...
Waiting for versions table to be created...
Waiting for versions table to be created...
Waiting for versions table to be created...
Waiting for versions table to be created...
Waiting for versions table to be created...
doveconf: Error: t_readlink(/var/run/dovecot/dovecot.conf) failed: readlink() failed: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.

Environment:
- debian 10.3
- docker info
Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 19.03.8
 Storage Driver: overlay2

**Comment by andryyy** [comment]
Please use the issue template.

Your DNS is not working, check your firewall etc.

**Comment by forall** [comment]
The problem occurs when I use my dns, others are blocked. Are other dns, e.g. google, used stiffly somewhere in the configuration? After changing to google dns, 8.8.4.4 or 8.8.4.4 everything works fine.
Docker host with my dns works correctly.

**Comment by andryyy** [comment]
No, check your firewall. See other issues regarding this. It is always a firewall issue. Do **not** use public DNS.

**Comment by yuriipaneiko** [comment]
Are you resolved this problem? Because i have same problem too

**Comment by dragoangel** [comment]
@Fufe1ok mailcow service use own unbound container as caching DNS resolver for all other containers inside mailcow service. You must allow mailcow host to access ANY outbound traffic on TCP/UDP port 53 - otherwise it wouldn't work. The point of why it so is due to any public DNS will not allow you to access dnsbl request with mailcow need to access. Unbound in mailcow use root dns servers to get data, not public dns. So please listen to what Ande said: configure your firewall/gateway correctly.

**Comment by ReSyncc** [comment]
@dragoangel I am having the same issue on my Ubuntu machine, I have tried allowing port 53 but no luck, what would be the best way to allow mailcow to access any outbound traffic on port 53 with UFW as my firewall? Thanks!

**Comment by dragoangel** [comment]
@robotdjman such network configuration issues (broken network) is out of mailcow scope and also too big to discuss on github. If we speak about any local firewall - it never block outbound traffic till you explicitly not block it, so I guess your issue outsite of your host and there could be 10001 reason why it broken: your firewall on gateway, your isp, your country government, etc and so on...

**Comment by ReSyncc** [comment]
@dragoangel I totally understand, I guess my only question is all of my containers but unbound are able to connect to the internet (or get their DNS requests resolved), I have disabled my firewall, flushed iptables and restarted, but still not luck. Any chance you could point me in the right direction so I can try and research this further, if not I totally understand and thank you for your help!
