### ISSUE TITLE
Mailcow UI don't work

### ISSUE THREAD

**Issue by kallemarc** [mailcow/mailcow-dockerized#3483]
Hey,

Wir haben Mailcow frisch installiert.
Haben aber das Problem das die Mailcow UI ein Overlay hat mit dem man sich nicht mehr anmelden kann.
Wir haben bereits Update.sh ausgeführt.

[](url)
<img width="1990" alt="image-EtPYEPP9sG" src="https://user-images.githubusercontent.com/46725076/79612458-03612200-80fd-11ea-953e-96aa74dd9c5a.png">

**Comment by patschi** [comment]
Bug report template ignored, closing.
