### ISSUE TITLE
Netfilter fail to start

### ISSUE THREAD

**Issue by avvhq** [mailcow/mailcow-dockerized#3488]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
If i want to start the container some apps (netfilter and ngnix) constantly hang in the restart (docker-compose ps).
mailcowdockerized_netfilter-mailcow_1   python3 -u /server.py            Restarting
mailcowdockerized_nginx-mailcow_1       /bin/sh -c envsubst < /etc ...   Restarting

**Docker container logs of affected containers**:
 I have manually stopped and started the netfilter service and found the following from the log:
netfilter-mailcow_1  |   File "/usr/lib/python3.7/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.7/site-packages/iptc/ip4tc.py", line 1621, in refresh
netfilter-mailcow_1  |     self.strerror()))
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'Address family not supported by protocol'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 491, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 264, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.7/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.7/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.7/site-packages/iptc/ip4tc.py", line 1621, in refresh
netfilter-mailcow_1  |     self.strerror()))
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'Address family not supported by protocol'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):

**Reproduction of said bug**:
Fresh installation on empty VM, no IPv6, proceed according to installation instructions

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Amazon EC2 |
| Server/VM specifications (Memory, CPU Cores) | 1GB, 1 Core (t2.micro) |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | No|

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Is this even a fully virtualized system?

Which kernel? Direct kernel access? No iptables?

Whatever, 1 GB is not enough anyway.

**Comment by avvhq** [comment]
Its a hardware virtual machine according to amazon.

Kernel: 4.15.0-1065-aws (it should be adapted by AWS), UFW Status is inactive

even to start the system without virusscan just to test a bit?

**Comment by patschi** [comment]
3 GB is, as of now, the recommended minimum RAM, without solr - see [docs at Prerequisites](https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/).I think 2 GB is absolute minimum without clamav und solr, and 4 GB when said both are enabled.

**Comment by avvhq** [comment]
Then I guess I'll have to find a bigger machine. Thanks for the quick help.

**Comment by patschi** [comment]
You're welcome! Thanks for honoring the bug report template! Not everyone does that, unfortunately :)

**Comment by avvhq** [comment]
The template is very useful because all important information can be retrieved even for beginners. ;)
