### ISSUE TITLE
Update the base image from backup_and_restore.sh (stretch-slim -> buster-slim)

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#3489]
**Is your feature request related to a problem? Please describe.**
Since I regularly check the up-to-dateness of my used docker images I noticed that the helper-[scripts/backup_and_restore.sh ](https://github.com/mailcow/mailcow-dockerized/blob/a63bad41bf671610c0b748590ba69bae4d10fecf/helper-scripts/backup_and_restore.sh)still uses base image "debian:stretch-slim" but the other mailcow images use "debian:buster-slim".

**Describe the solution you'd like**
I would suggest to change the base image of the backup script to "debian:buster-slim". 

**Additional context**
no

**Comment by andryyy** [comment]
Yep, I plan to do that every day. :(

Do you want to provide a PR?

**Comment by christianbur** [comment]
OK, I create a PR.

**Comment by christianbur** [comment]
PR create  https://github.com/mailcow/mailcow-dockerized/pull/3490/commits/88083757201d96359de09bd2b046e91711409c21
