### ISSUE TITLE
Allow advanced virus screening using Virus Total API

### ISSUE THREAD

**Issue by JPaulMora** [mailcow/mailcow-dockerized#3497]
**Problem** (not really a problem)
Sometimes its tedious and error prone to train Rspamd for spam filtering.

**Solution**
It would be great if we could insert our VT API key as to check for spam emails, we could then use this score as training data for Rspamd

**Additional context**
Virus Total API docs: https://developers.virustotal.com/v3.0/reference

**Comment by Braintelligence** [comment]
Before anyone actually thinks about doing this: You do realize that virustotal freely provides all uploaded files to security experts if you don't use the premium service?

**Comment by andryyy** [comment]
I also don't know what exactly is error prone.

You still need to administrate the server. We cannot do that for you. Check the symbols, the scores, your spam, your ham, all that.

Rspamd is very straightforward with this. Scanning files with VT does not provide additional anti **spam**. :(

You can easily activate VT in Rspamd, but keep in mind what @Braintelligence wrote. https://rspamd.com/doc/modules/external_services.html

**Comment by JPaulMora** [comment]
Okay thank you both. This solves it.
