### ISSUE TITLE
SCAYT spell check is a bug

### ISSUE THREAD

**Issue by raako71** [mailcow/mailcow-dockerized#3499]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Have tried to disable SCAYT spell check as described [here](https://github.com/mailcow/mailcow-dockerized/issues/3075). The discussion linked doesn't help to enable right click for browser spell check. I don't feel comfortable using this dictionary, which appears to be cloud based, exporting my emails for checking. This is quite an issue for me, haven't had this issue with any other web page.

**Docker container logs of affected containers**:
NA

**Reproduction of said bug**:
I have tried the various custom JS linked above

**System information**:
ubuntu 18.04

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No (t sure) |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | x64 4GB |
| Docker Version (`docker version`) |latest update |
| Docker-Compose Version (`docker-compose version`) |latest updateE |
| Reverse proxy (custom solution) | no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
We are not SOGo. 

I also don't understand, how it can be a bug. :/ Can you explain how the spell check is a big?

**Comment by wblondel** [comment]
https://ckeditor.com/docs/ckeditor4/latest/features/spellcheck.html

By default, SCAYT is available, but isn't automatically turned on when the editor loads.
If you want to completely disable SCAYT, disable the `scayt` plugin using the [CKEDITOR.config#removePlugins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins) configuration setting.

You may also want to disable the WebSpellChecker Dialog plugin.

Add the following lines in `/opt/mailcow-dockerized/data/conf/sogo/custom-sogo.js`:
> CKEDITOR.config.removePlugins = 'scayt,wsc';
> CKEDITOR.config.disableNativeSpellChecker = false;

Restart the SoGo container. 

This will make CKEditor (the HTML editor used by SoGo) use the browser native spell checker only.

**Comment by raako71** [comment]
all cool thankyou, only thing is still dont have access to right click for normal spellcheck

**Comment by wblondel** [comment]
@raako71 ctrl + right click :wink:

**Comment by raako71** [comment]
perfect thank you

**Comment by wblondel** [comment]
> perfect thank you

I modified my instructions, there was a typo: I typed `msc` instead of `wsc`.

**Comment by AprendendoLinux** [comment]
Friends, good morning! Has anyone managed to remove the right mouse click and have access to the options offered by the browser? Sorry if something wasn't explained well. I'm Brazilian and I'm not very familiar with English.
