### ISSUE TITLE
Getting blank (white) start page after today update

### ISSUE THREAD

**Issue by eldrik** [mailcow/mailcow-dockerized#3502]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Did an update.sh that ran without complaining on errors.

After trying to got to the main logon page, the page is just white, no input elements etc. using the roundcube  and Sogo sites works without an error.

Also other services are working fine under the hood just the mailcow login site is pure white.

- Started and stopped all containers  does not change anything
- Reboot of server - no change
- ran update.sh a second time - no change

Regards
eldrik

**Docker container logs of affected containers**:

No error reported while using docker-compose logs --tail=10

**Reproduction of said bug**:
ran update.sh 
try to open the mailcow login site --> blank window no error messages

**System information**:
Linux mailstation 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

| Question | Answer |
| --- | --- |
| My operating system | Linux mailstation 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
| Is Apparmor, SELinux or similar active? | ? |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare |
| Server/VM specifications (Memory, CPU Cores) | 2vcpu 2GB RAM |
| Docker Version (`docker version`) |  |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019 |
| Reverse proxy (custom solution) | HAProxy setup - but reverse and  local login same behavior |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.

diff --git a/data/web/inc/vars.inc.php b/data/web/inc/vars.inc.php
index c7e2174f..64bd5a3b 100644
--- a/data/web/inc/vars.inc.php
+++ b/data/web/inc/vars.inc.php
@@ -102,7 +102,11 @@ $MAILCOW_APPS = array(
   array(
     'name' => 'Webmail',
     'link' => '/SOGo/',
-  )
+  ),
+array(
+    'name' => 'Roundcube',
+    'link' => '/rc/'
+   )
 );
 
 // Rows until pagination begins

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.

No fw enabled

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

**Comment by CMiksche** [comment]
I have the same problem

Because the error seems to only occur today there is maybe a bug in 1db85df0db7c1dc6a5377cf871c6134496b6da03 ? (Also the CI tests didn't succeed in that commit ...)

**Comment by dIELERx** [comment]
I can confirm that issue.. I updated today and got the same problems. I did the same steps as eldrik did.

**Comment by kallenp** [comment]
I can confirm problem with blank/white screen too after today update.

**Comment by ghost** [comment]
Same here with a fresh installation.

**Comment by CMiksche** [comment]
Okay. I reverted 1db85df0db7c1dc6a5377cf871c6134496b6da03 and can confirm this commit creates this bug. @andryyy

**Comment by kallenp** [comment]
@CMiksche Please, how can I revert too ?

**Comment by kallenp** [comment]
@andryyy Works, thanks.

**Comment by ghost** [comment]
Can confirm this. Thanks, @andryyy!

**Comment by andryyy** [comment]
Thank YOU guys. :)

**Comment by pjv** [comment]
Just updated this morning (May 5) and I am seeing this issue again - white screen.

UG! sorry! I did not realize this issue was 2 years old. I just read April 25 and thought it was last month. I’ll create a new ticket.

**Comment by SsNiPeR1** [comment]
> Just updated this morning (May 5) and I am seeing this issue again - white screen.
> 
> UG! sorry! I did not realize this issue was 2 years old. I just read April 25 and thought it was last month. I’ll create a new ticket.

same over here
