### ISSUE TITLE
Suspend / Inactive account

### ISSUE THREAD

**Issue by thomisus** [mailcow/mailcow-dockerized#3506]
One feature that I miss from other email systems, is the ability to deactivate account but still receive emails. Why? Because some of our employees are seasonal and we want to retain the ability to receive emails but disable access during non working periods. Changing password in order to lock out users is not an option because every employee ( 150+ ) use thunderbird as email client and that means change manually every password.

Currently if we deactivate email accounts in mailcow, they don't receive emails anymore.

I have two ideas how to implement this:
- another flag near "Active" that permits to continue receiving emails ( this is the fastest to implement )

- a "Suspend" flag with an optional date ( from - to ) that lock out users in that period but still receive emails.

Best regards

**Comment by andryyy** [comment]
I have some features in the queue and already implemented the "disable login" (2) function besides "active" (1) and "inactive" (0). (edit: not yet pushed)

You could use the API and a small script to toggle that.

**Comment by andryyy** [comment]
Somewhere in the last commits.
