### ISSUE TITLE
Error when adding several alias domain's at once

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#351]
The Mailcow web interface for adding an *Alias domain* is a multi-line textarea with the following advice:

> *Valid domain names only (comma-separated).*

When you add more than one domain however there is an error, *Alias domain is invalid*.

I have tried comma seperated with no white space, with a space and also with a carriage return, but it appears to only accept one at a time?

**Comment by andryyy** [comment]
Thanks! I will check it.

**Comment by andryyy** [comment]
I close this. :) Checked the fix on dev, will "release" it soon. Thanks!
