### ISSUE TITLE
DNS not working for containers other than unbound

### ISSUE THREAD

**Issue by WBPlumb** [mailcow/mailcow-dockerized#3513]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Following a fresh install of Debian and mailcow (not changing any of the defaults) DNS does not work fully (works for unbound but not any other container). It does begin to work but we have to allow all UDP traffic on the VPS providers external firewall. 

Please can you help as we don't want to have an allow all rule on the external firewall and its odd that unbound works but the other containers don't.

**Docker container logs of affected containers**:

unbound with external firewall UDP rule off
```
$ docker-compose exec unbound-mailcow nslookup mailcow.email 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 dns.google

Name:      mailcow.email
Address 1: 5.1.76.57 web.servercow.de
Address 2: 2a00:f820:417::e12:892d web.servercow.de
```
other containers with external firewall UDP rule off
```
$ docker-compose exec acme-mailcow nslookup mailcow.email 8.8.8.8
;; connection timed out; no servers could be reached
```
other containers with external firewall UDP rule on
```
$ docker-compose exec acme-mailcow nslookup mailcow.email 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   mailcow.email
Address: 5.1.76.57
Name:   mailcow.email
Address: 2a00:f820:417::e12:892d
```
**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.1 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8Gb |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5, build 8a1c60f6 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/u_e-why_unbound/

We use our own recursor. Don't use 8.8.8.8 for testing. All containers (other than ubound - obviously) will query unbound-mailcow for DNS.

Your VPS providers external firewall must allow those queries from unbound to the root servers. If you want to use your own, external recursor (NOT (!) a caching DNS server like dnsmasq forwarding queries to any public resolver!), use `helper-scripts/docker-compose.override.yml.d/EXTERNAL_DNS/docker-compose.override.yml`.
