### ISSUE TITLE
Admin 2FA reset - no connection possible 

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3515]
Hi.
I've got 2FA problem. From one day to the other I couldn't use mit 2FA with my Yubikey on my admin account anymore. Maybe the problem is my https connection, but that's not the point. I use these two command strings 
```

1. source mailcow.conf

2. docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DELETE FROM tfa WHERE username='YOUR_USERNAME';"
```

and now I could not connect to my mailserver at all. No IMAP, no https, no nothing. :(
In portainer I see that the dockers are running.

In the log files of nginx ist see this error, but I don't know if this has a relation to this problem now?

`2020/05/03 17:02:07 [emerg] 13#13: SSL_CTX_use_PrivateKey("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch) nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

In the dovecot log files is see also errors:

```
May  3 17:25:45 pboenig dovecot: imap-login: Error: Failed to initialize SSL server context: Can't load SSL private key: Key is for a different cert than ssl_cert: user=<>, rip=192.168.178.66, lip=172.22.1.250

May  3 17:25:45 pboenig dovecot: imap-login: Disconnected: TLS initialization failed. (no auth attempts in 0 secs): user=<>, rip=192.168.178.66, lip=172.22.1.250
```

I also used the helper script to reset the admin account but no success.

I don't know what to do. :(

**Comment by andryyy** [comment]
You have a non matching key/cert combination. The SQL command is not related at all.

**Comment by andryyy** [comment]
And PLEASE read the issue template. We really make it as obvious as possible, that this tracker is not for support. :(

**Comment by ghost** [comment]
Oh, sorry for that! I did not read read the issue template. I will don't do it in the future, sorry!

I wil now post the soloution for others that maybe come across. 
Here ist what I did based on this (https://github.com/mailcow/mailcow-dockerized/issues/417)

`sudo rm * -R /opt/mailcow-dockerized/data/assets/ssl

sudo cp /opt/mailcow-dockerized/data/assets/ssl-example/* /opt/mailcow-dockerized/data/assets/ssl`

I really like this mailserver!
Have a nice day!
