### ISSUE TITLE
E-Mail Setup Page unavailable

### ISSUE THREAD

**Issue by webermar** [mailcow/mailcow-dockerized#3521]
Hello, 

I did an update via update.sh script. 
Now I can't open E-Mail Setup Page in Admin Interface.

In Detail: 
Log In as admin on server. Now admin Page opens, I am able to configure the server.
On the upper left Edge, I go on configuration, dropdown, last item "E-Mail Setup".
Page loads but is completely greyed out via overlay. I can't do anything there.

Attached is the console output of Firefox when the E-Mail Setup Page is opened.
![grafik](https://user-images.githubusercontent.com/19824578/81182388-02aa0600-8fae-11ea-8e7a-543781950a81.png)

EDIT: Tip of andryyy already resolved problems. I ran said command and did bash update.sh.

**Comment by andryyy** [comment]
Hi,

Please read the issue template and follow the steps about how to get support. :)

Small tip: `git fetch ; git checkout origin/master data/web` - should fix it. Remember your local changes, if any.
