### ISSUE TITLE
Dns for each domain 

### ISSUE THREAD

**Issue by rbernardes** [mailcow/mailcow-dockerized#3522]
How can i set all dns configs for each domain? If my principal domain going offline, all domains will stop work.

**Comment by mkuron** [comment]
What do you mean when you say principal domain? `$MAILCOW_HOSTNAME`? Basically any DNS provider has redundant servers and gives your near-100% availability, so this is nothing you need to worry about in practice.

**Comment by shiz0** [comment]
You ignored the template, please don't do that!
Also this is not a bug or issue with Mailcow, but normal behavior with any Mailserver, as they all run under a "primary" Domain. You can point the mx of each domain directly to you mailservers IP, but the server will still need a domain to run under, fqdn to announce and matching rdns.
For support, please join our community channels, either on Telegram: https://t.me/mailcow, oder the Board: https://community.mailcow.email/
Closing.
