### ISSUE TITLE
What DNS servers do the mailcow containers use?

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3526]
Although the new DNS records propagated (for `mail.example.com`, `autoconfig.example.com`, `autodiscover.example.com`) and `dig` on the mailcow docker host system resolve to the new IP, the `dig` command inside the acme container still resolves to the old IP address.

What DNS server do these mailcow containers use?
And are there DNS servers that are more reliable and less caching that a mailserver could rely on for validation? 
Apparently [Let's Encrypt uses Google DNS servers for lookups](https://community.letsencrypt.org/t/is-there-a-lets-encrypt-dns-propagation-check/69528).
Does it make sense to configure the mailcow services/host system/docker container, notably the acme mailcow container to use the Google DNS servers for lookups (like checking IPs of extra domains for ACME), too?

**Comment by strarsis** [comment]
After switching all containers default DNS to Google Public DNS, 
the validation then works correctly without caching delays.
`/etc/docker/daemon.json`:
```json
{
  "dns": ["8.8.8.8", "8.8.4.4"]
}
````

**Comment by andryyy** [comment]
Using public resolvers is for documented reasons bad. 

The containers do not care about your hosts DNS anyway. All containers use unbound as DNS anyway. That's why it exists. 

Read the issue template. If you ignore it, your issue will be locked, closed or deleted. 
No support here.
