### ISSUE TITLE
Add Cyrus IMAP as alternative option instead of the Dovecot IMAP server

### ISSUE THREAD

**Issue by CMiksche** [mailcow/mailcow-dockerized#3529]
**Is your feature request related to a problem? Please describe.**
I want to use JMAP (JSON Meta Application Protocol) on my mailcow instance. Dovecot has support for JMAP on the roadlist but the devs haven't got time to implement it yet.

**Describe the solution you'd like**
Cyrus IMAP has a strong connection with JMAP because the Fastmail staff contribute to Cyrus IMAP (as far as i get from Wikipedia Fastmail seems to use Cyrus). And Fastmail also were involved with the creation of the JMAP protocol.

**Additional context**
I think support for multiple IMAP servers would improve this project and would allow simple switches if someone has problems with a specific IMAP server.

Also this would difference this project more to other solutions like Mail-in-a-Box (i searched for mailcow-alternatives with Cyrus support but seems like all use Dovecot?!). 

I want to create JMAP clients and because mailcow is built on Dovecot i have to switch to another solution if i wanna run my own JMAP server.

**Comment by andryyy** [comment]
Thanks for properly filling out the FR. 

I don't plan it. It would fragment everything. I like the development and community of Dovecot better.

Maintaining both servers would be a nightmare. Sorry.
