### ISSUE TITLE
BIND removed on dev: DNSSEC validation and DNSBL support?

### ISSUE THREAD

**Issue by mkuron** [mailcow/mailcow-dockerized#353]
I saw that 92e2999 removed the Bind9 recursive DNS server on the dev branch. This means that all queries now go through the system's default DNS server. While I agree that a DNS recursor shouldn't be considered part of a mailserver infrastructure, we needed it for two reasons: DNSSEC validation and to get around some recursors' issues with DNSBLs (e.g. Google's 8.8.8.8 supposedly cannot be used for querying DNSBLs).

What's the plan going forward? Are you replacing Bind with some more lightweight piece of software?

**Comment by andryyy** [comment]
It worked unreliable, just as PowerDNS. I don't want to keep it included then.

Any idea for a replacement?

**Comment by Braintelligence** [comment]
@andryyy Can you elaborate a bit about why you chose Bind9 and now don't want to use it anymore?

EDIT: What about this paragraph then? https://mailcow.github.io/mailcow-dockerized-docs/u_e-why_bind9/

**Comment by andryyy** [comment]
Many users run into problems with non-working name resolution after some time. I could reproduce this issue but was not able to find a fix. It happened sporadic.

**Comment by Braintelligence** [comment]
What are the negative consequences of not using Bind9 anymore? In my case I would be using the OVH DNS servers for example.

**Comment by andryyy** [comment]
DNS blacklist lookups will fail when the IP querying the BL is rate limited. That's not good for spam detection.

**Comment by Braintelligence** [comment]
What would be the easiest way to solve this after Bind9 was removed?

**Comment by mkuron** [comment]
The other consequence is that you now depend on that your server hoster's DNS server performs proper DNSSEC validation. Furthermore, you now need to trust that the network between your server, i.e. that there is no man in the middle that might alter DNS responses. The DNSSEC standard suggests using IPSec between your DNS server and your host, but such setups are not widely deployed (I am not aware of any hosting company that offers this).

Here's a suggestion: we could use [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) to do the DNSSEC validation. It's not a fully-blown recursor (it only forwards queries to a recursive DNS server), but it can do DNSSEC validation of results. dnsmasq is really small, so we can either run it in its own container or, if that turns out to have the same issues as Bind9 and PowerDNS, put it into the Postfix container.

I don't have time right now to set up a dnsmasq image, but the config would probably look like this:

```
# Don't fork to background
no-daemon

# Directly query the DNSBLs
server=/b.barracudacentral.org/geons01.barracudacentral.org
server=/b.barracudacentral.org/geons02.barracudacentral.org
server=/dnsbl.inps.de/ovh1.inps-jung.net
server=/dnsbl.inps.de/vsrv4.inps-jung.net
server=/mailspike.net/ns1.mailspike.net
server=/mailspike.net/ns2.mailspike.net
server=/mailspike.net/ns3.mailspike.net
server=/dnsbl.sorbs.net/ns0.sorbs.net
server=/dnsbl.sorbs.net/ns2.sorbs.net
server=/dnsbl.sorbs.net/ns3.sorbs.net
server=/dnsbl.sorbs.net/ns4.sorbs.net
server=/dnsbl.sorbs.net/ns5.sorbs.net
server=/dnsbl.sorbs.net/ns6.sorbs.net
server=/dnsbl.sorbs.net/ns7.sorbs.net
server=/dnsbl.sorbs.net/ns8.sorbs.net
server=/dnsbl.sorbs.net/ns9.sorbs.net
server=/dnsbl.sorbs.net/ns10.sorbs.net
server=/dnsbl.sorbs.net/ns11.sorbs.net
server=/dnsbl.sorbs.net/ns2.mydyndns.org
server=/dnsbl.sorbs.net/ns3.mydyndns.org
server=/dnsbl.sorbs.net/ns4.mydyndns.org
server=/dnsbl.sorbs.net/ns5.mydyndns.org
server=/zen.spamhaus.org/0.ns.spamhaus.org
server=/zen.spamhaus.org/2.ns.spamhaus.org
server=/zen.spamhaus.org/3.ns.spamhaus.org
server=/zen.spamhaus.org/4.ns.spamhaus.org
server=/zen.spamhaus.org/5.ns.spamhaus.org
server=/zen.spamhaus.org/7.ns.spamhaus.org
server=/zen.spamhaus.org/8.ns.spamhaus.org
server=/zen.spamhaus.org/b.ns.spamhaus.org
server=/zen.spamhaus.org/c.ns.spamhaus.org
server=/zen.spamhaus.org/d.ns.spamhaus.org
server=/zen.spamhaus.org/f.ns.spamhaus.org
server=/zen.spamhaus.org/g.ns.spamhaus.org
server=/zen.spamhaus.org/h.ns.spamhaus.org
server=/zen.spamhaus.org/i.ns.spamhaus.org
server=/zen.spamhaus.org/k.ns.spamhaus.org
server=/zen.spamhaus.org/o.ns.spamhaus.org
server=/zen.spamhaus.org/q.ns.spamhaus.org
server=/zen.spamhaus.org/t.ns.spamhaus.org
server=/zen.spamhaus.org/x.ns.spamhaus.org
server=/hostkarma.junkemailfilter.com/rbl1.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl2.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl3.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl4.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl5.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl6.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl7.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl8.junkemailfilter.com
server=/hostkarma.junkemailfilter.com/rbl9.junkemailfilter.com

# validate DNSSEC; anchors from https://data.iana.org/root-anchors/root-anchors.xml
trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
dnssec
dnssec-check-unsigned
```

This causes it to read /etc/resolv.conf and use that as the upstream server. Replies are validated with DNSSEC. The `server` lines should cause it to not go to the upstream server for DNSBL queries, but instead directly contact the DNSBL's nameserver. I had to include the actual name servers there, which may change over time, but we could pull them from DNS through a script instead of hard-coding them.

**Comment by mkuron** [comment]
Alternatively, we could try [Unbound](https://unbound.net), which is considered smaller and more modern and is only a recursor and not a full DNS server like Bind9. As I have never run into the Bind9 issues @andryyy mentioned, I can't tell whether Unbound would exhibit them too.

**Comment by K2rool** [comment]
I removed bind out of my private repo of Mailcow a number of weeks ago due to it hanging the mail server due to dns lookup failing or crazy lookup time of many secs.

How i handle the dns lookup is like how i did it when i used the non docker version was to run dnsmasq with my provider dns and a few public dns as the upstream how i got around the DNSBL limit was to set the dnsbl i had issue with to query  using a less common public dns server using server setting in dnsmasq.

**Comment by mkuron** [comment]
Using public DNS servers as upstream servers isn't scalable. Other people are doing it too, so you will occasionally hit the DNSBL's rate limit. For Mailcow, we should either run a recursor to directly query the DNSBL or forward to our providers' servers, which are probably only shared by a few hundreds or thousands of customers.

**Comment by andryyy** [comment]
I've setup a unbound image and will push it in a few minutes.

**Comment by K2rool** [comment]
Ok @mkuron  i do agree public dns as a upstream might not be scalable, but running a recursor dns server in my own opinion is not rely needed, using a public or the server provider dns server in most case will be faster in dns lookup as it's a good chance it will already be cached.

I think the best way is just use dnsmasq to forward all the dns lookup to server provider/public dns or what ever the user has set in /etc/resolv.conf that way you can leverage the already cached dns lookup and just forward the dnsbl lookup directly to the nameserver of them.

That way you get faster dns lookup and dnsbl lookups don't get rate limited.

**Comment by marrco** [comment]
I never had a single issue with pdbs-recursor (nor with bind that i use for more than 20 years). MC-D setup was fine, so i suppose issue was somewhere else. That said +1 for using just a resolver. If not pdns-resolver (that i like) also unbound is ok

**Comment by andryyy** [comment]
```
...
server=/b.barracudacentral.org/geons01.barracudacentral.org
...
````
dnsmasq does not accept fqdns on the right hand (here: geons01.barracudacentral.org). You would need to use the IPs.
It also is very inconsistent to define nameservers like this.

We finally use unbound, which auto-reloads trusted zones.
