### ISSUE TITLE
Option to remove published ports of nginx-mailcow

### ISSUE THREAD

**Issue by snake-4** [mailcow/mailcow-dockerized#3540]
**Is your feature request related to a problem? Please describe.**
I was setting up mailcow with traefik as reverse proxy and then I've noticed something, nginx-mailcow container has 2 published ports which can't be disabled from mailcow.conf or docker-compose.override.yml therefore it tries to use the port which is already in use by traefik and it fails.

**Describe the solution you'd like**
It'd be nice if there was an option in mailcow.conf to remove published ports of nginx-mailcow.

**Comment by shiz0** [comment]
When I am looking at the nginx-mailcow container on my server, it publishes the ports set in mailcow.conf on the IP set in mailcow.conf. 
I myself did not change the ports, just the public IP, but it should work for the ports as well. No need for using compose.override for that, as the docker compose reads the ports to be published from the config.
Have a look at the docs for examples how to run mailcow with traefik:
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

**Comment by snake-4** [comment]
What I'm saying is that for Traefik to work the only requirement is that the container must be connected to network specified in Traefik configuration, there is no need to publish any ports. So an option to remove all published ports from nginx-mailcow without editing docker-compose.yml would be nice.

**Comment by shiz0** [comment]
Ok. I misunderstood, sorry.
Unfortunately, it's really not possible to  remove stuff in override, as it merges. The docker compose is pulled from GitHub, so I cannot think of an easy way to implement this, without changing loads of other stuff.
Maybe @andryyy might have an idea, but I personally think, that publishing it to 127.0.0.1 (additionally on some arbitrary high port, if you like) provides a good workaround for that.
I personally do so for unused components/protocols (POP, POPS, Sieve).

**Comment by Adorfer** [comment]
> Ok. I misunderstood, sorry.

perhaps reopen?

**Comment by andryyy** [comment]
We cannot remove ports with an override. He may ask in the compose repository. :)
