### ISSUE TITLE
SoGo forwarded mails to non existing domains will result in local bounce -> No Bounce message original sender and mail get lost

### ISSUE THREAD

**Issue by Pjirlip** [mailcow/mailcow-dockerized#3541]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

If you (by accident) use a mailbox with an non existing domain for forwarding in SOGO, then bounce messages will be stuck in mailqueue because postfix tries to send them to the forwarding mailbox. (Bounce message should be delivered to original sender.). After a while bounce and original messages will be lost forever.

**Docker container logs of affected containers**: 
See following messages

Rspamd
![rspamd_log](https://user-images.githubusercontent.com/9822378/81955521-7d0c0300-960a-11ea-9173-f555e2979e3e.png)

**Reproduction of said bug**:

1. Create Mailbox "user@example.com"
2. Login into SOGO for created mailbox. 
3. Set Mail forwarding to an recipient of an non existing Domain for example "recipient@gfhtwzfhdghwdh.fantasy" and don't check "keep copy of forwarded mail" 
4. Now send mail to "user@example.de" from "user@sender.com" --> Postfix tries to forward mail to "recipient@1234.fantasy" --> Lookup of Domain goes wrong and message bounce --> Recipient for bounce message is "user@example.de" instead of "user@sender.com" 
5. After time bounce message and original message will be lost. It isn't in the queue anymore nor is the message in de Inbox of "user@example.de"

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu Server 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VM running on Xen Hypervisor |
| Server/VM specifications (Memory, CPU Cores) | 4 Cores, 8 GB RAM, 16GB SWP |
| Docker Version (`docker version`) | Docker version 19.03.8, build afacb8b7f0 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4 |
| Reverse proxy (custom solution) | No |

**Comment by andryyy** [comment]
Nope. We change the sender to not break SPF. That has much higher priority than the bounce.

**Comment by Pjirlip** [comment]
Thanks for your quick response! 

Sorry if don't understand it correctly, but how does this break SPF? If the bounce happens on the mailcow server because he can't deliver the mail, then sender policy is correct if the mailserver answers the original sender with his own bounce message. I can understand the point if the bounce happened on the third party server, but here the mail can't leave the server because of the lookup fail of the domain. Also wouldn't SRS solve the problem of forwarding bounces messages from third party servers? 

The combination of no bounce message and deleting of the mails from the postqueue after time is really unlucky :-(

**Comment by andryyy** [comment]
You can forward bounces back to your primary account etc. :) Just another filter. It is more important to deliver forwarded mail, than having them bounced every time due to policy failures.

You can play around with sieve_redirect_envelope_from and set it back to "sender". You should not set the "envelope from" to an address, that you don't own. And that will happen with "sender". We can also not sign those mails.

**Comment by mkuron** [comment]
It‘s generally bad to send bounces to other servers. They might erroneously get flagged as spam and harm your reputation. But sending out bounces that just get stuck in the queue that nobody ever sees is obviously not intended either.

Is there a way to get the Sieve scripts to be executed synchronously, i.e. while the incoming SMTP session is still connected? An error occurring during forwarding then could be reported as an SMTP error instead of as a bounce.

**Comment by Pjirlip** [comment]
> You can forward bounces back to your primary account etc. :) Just another filter. It is more important to deliver forwarded mail, than having them bounced every time due to policy failures.
> 
> You can play around with sieve_redirect_envelope_from and set it back to "sender". You should not set the "envelope from" to an address, that you don't own. And that will happen with "sender". We can also not sign those mails.

Thanks for your suggestion, i will look into sieve filters. :-) Do you maybe know if theres an easy way to change the default behaviour of the mailqueue, so mails wouldn't be deleted from the queue if sending fails multiple times. (At best set them on "hold"). Then at least I have the possibility to recognise the problem, rescue mails with postcat etc.
