### ISSUE TITLE
Update update.sh

### ISSUE THREAD

**Issue by beckzg** [mailcow/mailcow-dockerized#3542]
Hi,

  I've a strange problem, my server is at UK and since a week the 9.9.9.9 is not reachable. I tried to open a case at my hosting company, they checked and said that the packets are going out from the hosting network, the problem is at 9.9.9.9. I wrote to quad9 as well, but didn't get any answer from them. The 1.1.1.1 and 8.8.8.8 are working fine, only 9.9.9.9.

  I tried to replace the 9.9.9.9 in the update.sh but doesnt works.

  Is there a way to add multiple ips to check?

root:~# ping -c 1 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=51 time=7.05 ms

--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 7.052/7.052/7.052/0.000 ms

root:~# ping -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=1.14 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.138/1.138/1.138/0.000 ms

root:~# ping -c 1 9.9.9.9
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.

--- 9.9.9.9 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

**Comment by ghost** [comment]
Same problem here, they got some BGP routing issues. But in general I'm asking why to check the update script to a service which can be unrouteable. Preferably connection should be checked against multiple target imho.

**Comment by andryyy** [comment]
Fixed
