### ISSUE TITLE
Deactivate Domain (addresses still active)

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3546]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [?] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
I dont know if there is a Bug or an feature request. When i deactivate a Domain the email addresses are still active. In my opinion the email addresses also have to deactivate.

**Docker container logs of affected containers**:
nothing

**Reproduction of said bug**:
Deactivate a Domain -> look at the email addresses (still active).

**System information**:
KVM-Instance
Debian 10.4
System is up-to-date

**Comment by andryyy** [comment]
Because you deactivated a domain and not a mailbox. 

Try to login as a mailbox user or send a mail to it. Does not work.

**Comment by andryyy** [comment]
Users could still login to the UI though. Fixed that now.
