### ISSUE TITLE
Send mail as alias address

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#355]
On my mailcow server, there is only one account, and every e-mail gets redirected to it.
But now I have to write an e-mail in the name of an alias.

The alias name is mail@abc, the account that actually exists is together@abc.
What should I do now?

(For this one mail I am going to delete the alias, create a mailbox, send the mail, delete the mailbox, recreate the alias.)
I would like to have a _official_ way of doing so...

**Comment by mkuron** [comment]
You can disable sender address verification. It's explained in the documentation.
Alternatively, you might be able to explicitly add that one alias to your mailbox before setting up the catch-all.

**Comment by mindsolve** [comment]
Thank you so much! That was what I was searching for.
