### ISSUE TITLE
Overwork *** error pages

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3558]
Hello,

It would be great if you would ovework the standard error pages a bit (e.g. 404) that looks ugly :D

Thanks in advance.

**Comment by andryyy** [comment]
I'm fine with them. :) I don't see a 404 with regular usage anyway. 

A PR would be merged. Should fit in the current design.

**Comment by omexlu** [comment]
Normally they are not shown no, but there are always those who want to try something out, then at least they see something nice :D

Also it would be more consistent.
