### ISSUE TITLE
Using a separate ip and hostname for each domain

### ISSUE THREAD

**Issue by elec3c** [mailcow/mailcow-dockerized#3559]
If several mail domains are running on the same server and the server ip falls into the spamlist, this affects the operation of the entire server. I would like to be able to assign each domain a separate IP that is assigned to the server and a separate hostname. Thus, spamming one ip will not affect the delivery of mail from other domains.

In Mdaemon, this is decided as in the screenshot.
![image](https://user-images.githubusercontent.com/54912007/82534308-9999c500-9b4d-11ea-94cb-8d5ec424042f.png)

In postfix, this is solved:

In main.cf add:
sender_dependent_default_transport_maps = hash:/etc/postfix/sender_transport

In sender_transport
@domain1 group1
@domain2 group2

In master.cf add:
group1 unix - - n - 10 smtp -o smtp_bind_address = server_ip1 -o myhostname = hostname-1
group2 unix - - n - 10 smtp -o smtp_bind_address = server_op2 -o myhostname = hostname-2

As far as I understand in mailcow, the problem can be solved by creating custom files as indicated in the documentation:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-custom_transport/
https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-extra_cf/

Perhaps there is an easier way?

**Comment by andryyy** [comment]
See the issue template, please. :)
