### ISSUE TITLE
Also allow IPv6 for delivering mail

### ISSUE THREAD

**Issue by MyIgel** [mailcow/mailcow-dockerized#3560]
**Is your feature request related to a problem? Please describe.**
After testing mailcow i noticed that outgoing mail never gets transported over IPv6 and I think thats a bad default.

**Describe the solution you'd like**
A solution is to set
```
smtp_address_preference = any
```
in `data/conf/postfix/main.cf` instead of `ipv4` which would allow postfix to at least try to submit the email over ipv6

**Comment by andryyy** [comment]
Hi,

We added it as workaround for setups with IPv6 disabled. So they don't have to wait for a retry. But I have to agree we should set it to "any" and add it to the docs (=> "disable ipv6" section).

**Comment by MyIgel** [comment]
I created the above mentioned PRs with the required changes :)
