### ISSUE TITLE
Add custom ip and hostname fields for domain/

### ISSUE THREAD

**Issue by elec3c** [mailcow/mailcow-dockerized#3562]
**Is your feature request related to a problem? Please describe.**
If several mail domains are running on the same server and the server ip falls into the spamlist, this affects the operation of the entire server.

**Describe the solution you'd like**
I would like to be able to assign each domain a separate IP that is assigned to the server and a separate hostname. On the add / edit domain page, add 2 fields: ip and hostname. These fields override the basic server values.

**Comment by andryyy** [comment]
You can easily create tiny postfix listeners on the host and bind the smtp services to different IPs, then add them under the "Routing" tab in mailcow. This way you can have different IPs for different domains. 

You can also bind multiple IPs on the host and change SNAT, when an IP is banned. Probably the easiest method. 

Anyway, you should add rate limits and monitor your server. This does usually not happen, when you keep an eye on your server... 

This is not necessary to be included in the UI. If you need it for commercial use, you can think about sponsoring it or create a PR.

**Comment by elec3c** [comment]
I found solution, like you write, using additional smtp service.
> This is not necessary to be included in the UI. If you need it for commercial use, you can think about sponsoring it or create a PR.

I think about it. If i want sponsoring this feature , how can i do it?
