### ISSUE TITLE
API Endpoint for getting all emails

### ISSUE THREAD

**Issue by kierandrewett** [mailcow/mailcow-dockerized#3564]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I can't use a API key for grabbing emails with the `/SOGo/so/[email]/Mail/0/folderINBOX/view` url. You need to use a SOGo key and some other cookies which is annoying.

**Describe the solution you'd like**
I would like the following endpoint to be added to the API: 

`GET /api/v1/get/mail/:email/:folder?`

**Additional context**
N/A

**Comment by andryyy** [comment]
Just use IMAP?
