### ISSUE TITLE
Export DNS entries as .txt file

### ISSUE THREAD

**Issue by jacboy** [mailcow/mailcow-dockerized#3567]
**The problem**
When setting up new domains, my workflow is the following:

1. register domain
2. create & configure DNS
3. create domain in Mailcow
4. switch to server configuration page to create DKIM keys
5. get back to domain, open DNS config
6. copy each of the entries manually to my DNS zone file
7. get back to 2.

**Describe the solution you'd like**
In the DNS page / modal, there should be a button to export all the needed DNS entries in a e. g. BIND-compatible format. It can be downloaded as .txt file (automatically) or just a deactivated text input to copy it straight away.

**Additional context**
DNS recoreds files are widely used in professional domain management tools like [AutoDNS](https://www.internetx.com/domains/autodns/), [Hetzner DNS](https://wiki.hetzner.de/index.php/DNS_Overview#Features), [Cloudflare](https://api.cloudflare.com/#dns-records-for-a-zone-import-dns-records) and many more.

**Comment by nogweii** [comment]
Being able to query that export via the API would be awesome as well. I have a bunch of scripts to manage my DNS records across my infrastructure, so being able to integrate Mailcow with those would be very nice. (Instead they currently  are saved as YAML files.)

**Comment by jacboy** [comment]
Yep, you're right.

**Comment by andryyy** [comment]
We should add an input field for a DMARC and SPF record to be shown before the export happens.

**Comment by andryyy** [comment]
@mkuron Feel like working on it? 😄

**Comment by jacboy** [comment]
@mkuron looks like you're not far away from town, would honor it with a beer or more :D 🍻
