### ISSUE TITLE
NO_IPV6_LINK problem workaround

### ISSUE THREAD

**Issue by walkinlake** [mailcow/mailcow-dockerized#3568]
**Is your feature request related to a problem? Please describe.**
While installing mailcow (which is very awesome! :)) i came across the NO_IPV6_LINK problem which avoided the cert creation. I read through all related issues about this problem, but nothing served me.

Then i tried to locate the problem and checked whether the container can ping/curl outside ip6s with following code like the one being used to retireve the ip6 in acme/functions.sh.
`sudo docker exec -i {container-id} curl --connect-timeout 3 -m 10 -L6s ip6.mailcow.email | grep "^\([0-9a-fA-F]\{0,4\}:\)\{1,7\}[0-9a-fA-F]\{0,4\}$"`

No reponse was received. Then i used following double command.
`sudo docker exec -i {container-id} ip -6 addr show dev eth0 >/dev/null; curl --connect-timeout 3 -m 10 -L6s ip6.mailcow.email | grep "^\([0-9a-fA-F]\{0,4\}:\)\{1,7\}[0-9a-fA-F]\{0,4\}$"`

Suddenly the ip6 was shown correctly. I have absolutely no idea why it works. I googled what the 'ip' command could activate/engage that the curl command works properly, but found nothing.

If someone has an explanation this would be great.

**Describe the solution you'd like**
It would be nice to alter acme/functions.sh that it includes that double command. Maybe it would serve other people as well.

**Comment by andryyy** [comment]
There is something else broken with your installation.
The "ip" command does not change anything in your network. I think you just cannot always resolve ip6.mailcow.email, or you need more than one try (which is wrong in itself). That's a huge problem there you should debug.

I have not seen this happen on any of many installations. You should really check when the curl command fails and why. Check your network setup (firewalls, routers etc.) and use tcpdump, try to replicate it and watch the traffic. 

I cannot help you with that I'm afraid. :(

**Comment by walkinlake** [comment]
Ah i didn't make it clear: Mailcow itself works perfectly retrieving certs and mailing around :) I just had to skip the ip(6)-check with SKIP_IP_CHECK=y

Just tried ping6 on google:
`sudo docker exec -i {container_id} ping6 google.com`

gave me this output: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"ping6\": executable file not found in $PATH": unknown

But again with ip command in front:
`sudo docker exec -i {container_id} ip -6 addr show dev eth0 >/dev/null; ping6 google.com`
PING google.com(par10s27-in-x0e.1e100.net) 56 data bytes
64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=1 ttl=54 time=4.68 ms
64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=2 ttl=54 time=4.70 ms
64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=3 ttl=54 time=4.67 ms
64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=4 ttl=54 time=4.68 ms
...

**Comment by JiiPee74** [comment]
> Ah i didn't make it clear: Mailcow itself works perfectly retrieving certs and mailing around :) I just had to skip the ip(6)-check with SKIP_IP_CHECK=y
> 
> Just tried ping6 on google:
> `sudo docker exec -i {container_id} ping6 google.com`
> 
> gave me this output: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: "ping6": executable file not found in $PATH": unknown
> 
> But again with ip command in front:
> `sudo docker exec -i {container_id} ip -6 addr show dev eth0 >/dev/null; ping6 google.com`
> PING google.com(par10s27-in-x0e.1e100.net) 56 data bytes
> 64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=1 ttl=54 time=4.68 ms
> 64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=2 ttl=54 time=4.70 ms
> 64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=3 ttl=54 time=4.67 ms
> 64 bytes from par10s27-in-x0e.1e100.net: icmp_seq=4 ttl=54 time=4.68 ms
> ...

You are running that ip command inside container and then your running ping6 command from host, not inside container. Is that what your trying to do?
