### ISSUE TITLE
config for: mailcow behind traefik without skipping let's encrypt 

### ISSUE THREAD

**Issue by walkinlake** [mailcow/mailcow-dockerized#3569]
**Is your feature request related to a problem? Please describe.**
I wanted to share my configuration for the case if mailcow is used behind traefik with traefik handling cert creation for the user interface and mailcow handles the cert creation for mail related stuff.

The configuration provided on https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ was not sufficent because i wanted to automatically create certs for new domains used in mailcow.
If the certs are only created by traefik (and then pushed to mailcow with humenius/traefik-certs-dumper) i still have to let traefik know which certs to create. And if the certs aren't used by traefik directly, it doesn't check whether they are due for renewal.
But because mailcow ui is behind traefik, traefik has to handle tls for this.

So:
- traefik gets cert for user interface like https://mail.domain.com
- mailcow gets certs for all used mail domains like mail.domain.com, autodiscover.domain.com, autoconfig.domain.com, mail.domain2.com, autodiscover.domain2.com, autoconfig.domain2.com

**Describe the solution you'd like**
So i keep the setting SKIP_LETS_ENCRYPT=n and create a docker-compose.override.yml like this:

`version: '2.1'

services:
  nginx-mailcow:
    networks:
      # add traefik's network
      - traefik_default
    labels:
      # Expose container to traefik
      - traefik.enable=true

      # Set communication network for traefik<->container
      - "traefik.docker.network=traefik_default"

      # Http router for mail related acme challenge
      # Catches: mail or autodiscover or autoconfig.*.tld/.well-known/acme-challenge/{token}
      - "traefik.http.routers.mailcow-acme-challenge.rule=HostRegexp(`{domain:(mail|autodiscover|autoconfig)\\.(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]}`) && Path(`/.well-known/acme-challenge/{token:[a-zA-Z0-9-_]+}`)"
      ## Define entrypoint which uses no ssl cert
      - "traefik.http.routers.mailcow-acme-challenge.entrypoints=web"
      ## Define service: route to port 80 internal
      - "traefik.http.services.mailcow-acme-challenge.loadbalancer.server.port=80"
      ## Assign service to router
      - "traefik.http.routers.mailcow-acme-challenge.service=mailcow-acme-challenge"

      # Http router for user interface
      # Redirects to https user interface using middleware (not handled in entrypoint!)
      ## Catch host name
      - "traefik.http.routers.mailcow-ui-redirect.rule=Host(`${MAILCOW_HOSTNAME}`)"
      ## Define entrypoint which uses no tls/ssl cert
      - "traefik.http.routers.mailcow-ui-redirect.entrypoints=web"
      ## Define middleware
      - "traefik.http.middlewares.redirect-to-websecure.redirectscheme.scheme=https"
      ## Assign middleware to router
      - "traefik.http.routers.mailcow-ui-redirect.middlewares=redirect-to-websecure"    
      ## Define service: route to port 80 internal
      - "traefik.http.services.mailcow-ui-redirect.loadbalancer.server.port=80"
      ## Assign service to router
      - "traefik.http.routers.mailcow-ui-redirect.service=mailcow-ui-redirect"

      # Https router for user interface
      # Traefik will handle cert creation (uses wildcard)
      ## Catch host name
      - "traefik.http.routers.mailcow-ui.rule=Host(`${MAILCOW_HOSTNAME}`)"
      ## Define entrypoint which uses tls/ssl cert
      - "traefik.http.routers.mailcow-ui.entrypoints=websecure"
      ## TLS / SSL certificate
      - "traefik.http.routers.mailcow-ui.tls=true"
      - "traefik.http.routers.mailcow-ui.tls.certResolver=domain.com-dns-resolver"
      - "traefik.http.routers.mailcow-ui.tls.domains[0].main=domain.com"
      - "traefik.http.routers.mailcow-ui.tls.domains[0].sans=*.domain.com"
      ## Define service: route to port 80 internal
      - "traefik.http.services.mailcow-ui.loadbalancer.server.port=80"
      ## Assign service to router
      - "traefik.http.routers.mailcow-ui.service=mailcow-ui"

networks:
  traefik_default:
    external: true
`

Here a wildcard cert will be created used the dns acme challenge, which mail.domain.com can use as well. If you want to use another cert resolver, see https://docs.traefik.io/https/acme/ for details.

If you handle http to https redirects on entrypoints in traefik.yml static config, you have to remove/comment out that as well like:
`  web:
    address: ":80"
    ## Redirects to websecure (https) if not handled by middleware
    #http:
      #redirections:
        #entryPoint:
          #to: websecure
          #scheme: https
          ##permanent = true`

**Comment by andryyy** [comment]
Hm,

@mkuron We should add a "user contributed how-tos" section to the docs. 

Also triggering @ntimo

**Comment by ovizii** [comment]
@walkinlake this is exactly the issue I was facing: using mailcow behind traefik and the current how-to: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#traefik-v2-community-supported does not seem to reflect the situation that we might add additional domains to mailcow so those are lacking certificates if I understand the difference between your solution and the one I linked to.


Do you have your solution somewhere as a gitlab gist so its nicely formatted and can be commented on? I'm still struggling to completely understand your solution.

**Comment by vamidi** [comment]
Is there a location where I can find this as well? I am really struggling assigning the ssl certificates to the domains. Cert dumpers works, because I can see all my certificate, but it is not picked up by mailcow when I use it in my mail apps
