### ISSUE TITLE
Can't do spam scan

### ISSUE THREAD

**Issue by lwl12** [mailcow/mailcow-dockerized#357]
rmilter-mailcow_1    | Jun 13 09:40:11 00f626f18e1b rmilter[7]: <32dd5a65bf>; mlfi_eom: tempfile=/tmp/msg.XXmfDdkk, size=14753
rmilter-mailcow_1    | Jun 13 09:40:11 00f626f18e1b rmilter[7]: <32dd5a65bf>; spamdscan: start scanning message on rspamd
rmilter-mailcow_1    | Jun 13 09:40:11 00f626f18e1b rmilter[7]: <32dd5a65bf>; rspamd: write (rspamd), Connection refused
rmilter-mailcow_1    | Jun 13 09:40:11 00f626f18e1b rmilter[7]: <32dd5a65bf>; spamdscan: finish scanning message on rspamd
rmilter-mailcow_1    | Jun 13 09:40:11 00f626f18e1b rmilter[7]: <32dd5a65bf>; rspamdscan: failed to scan, retry, rspamd, /tmp/msg.XXmfDdkk
rmilter-mailcow_1    | Jun 13 09:40:12 00f626f18e1b rmilter[7]: <32dd5a65bf>; spamdscan: start scanning message on rspamd
rmilter-mailcow_1    | Jun 13 09:40:12 00f626f18e1b rmilter[7]: <32dd5a65bf>; rspamd: write (rspamd), Connection refused
rmilter-mailcow_1    | Jun 13 09:40:12 00f626f18e1b rmilter[7]: <32dd5a65bf>; spamdscan: finish scanning message on rspamd
rmilter-mailcow_1    | Jun 13 09:40:12 00f626f18e1b rmilter[7]: <32dd5a65bf>; rspamdscan: failed to scan, retry, rspamd, /tmp/msg.XXmfDdkk

**Comment by andryyy** [comment]
Is rspamd-mailcow not running? What does Rspamd log?

**Comment by lwl12** [comment]
![snipaste20170613_174916](https://user-images.githubusercontent.com/10279535/27076768-b006c8e6-5060-11e7-85ab-40427401d3f0.png)
Is seems worked - -

**Comment by andryyy** [comment]
Can you run this, please?

```
docker-compose down
docker-compose pull
docker-compose up -d
```

**Comment by lwl12** [comment]
Thanks.
