### ISSUE TITLE
Mail from relay host being denied after migrating Mailcow to another VM.

### ISSUE THREAD

**Issue by LickABrick** [mailcow/mailcow-dockerized#3571]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
After migrating to a new VM (I migrated with the backup and restore script method) mails from my relay are no longer accepted. I use a relay (Proxmox Mail Gateway) since my own IP is blacklsited due to residental IP.

I have checked that the forwarding host setting is still there but mails from my relay still get denied.

**Docker container logs of affected containers**:

Postfix error:
`NOQUEUE: reject: RCPT from mail-gateway.mydomain.com[ip.of.relay.host]: 554 5.7.1 <mail-gateway.mydomain.com[ip.of.relay.host]>: Client host rejected: Access denied; from=<mygmail@gmail.com> to=<mymailcow@mydomain.com> proto=ESMTP helo=<Mail-Gateway.mydomain.com>`

Error shown on my relay:
`Client host rejected: Access denied (in reply to RCPT TO command))`

WAN and LAN IP's have stayed the same.

**Reproduction of said bug**:
Send mail from e.g. gmail to mailcow hosted domain.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 latest |
| Is Apparmor, SELinux or similar active? | nope |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare |
| Server/VM specifications (Memory, CPU Cores) | 1 Core, 4GB memory |
| Docker Version (`docker version`) |19.03.9 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | Yes, Nginx |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Please don't use the bug tracker as support platform. 

The "Reproduction of said bug" is also not plausible. 

Do not use a filter in front of mailcow. It is useless and will break spam filtering. :/

Please use the forum or Telegram.

**Comment by LickABrick** [comment]
> Please don't use the bug tracker as support platform. The "Reproduction of said bug" is also not plausible. Do not use a filter in front of mailcow. It is useless and will break spam filtering. :/ Please use the forum or Telegram.


Sorry for using the wrong platform for this.
I have disabled the filter in front of mailcow and mail is delivered again, I will use the relay only for outgoing mail from now on. Still not sure why mail is being denied though.
