### ISSUE TITLE
Quarantine email recovery does not work after update

### ISSUE THREAD

**Issue by RomanFokin** [mailcow/mailcow-dockerized#3573]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

After update.
Quarantine email recovery does not work.

/quarantine -> show items -> actions - release

gives an error: SMTP code 554 5.7.1: Client host rejected: Access denied, expected 250

**Docker container logs of affected containers**:

postfix-mailcow_1    | May 25 15:41:30 mail01 postfix/quarantine/smtpd[5782]: NOQUEUE: reject: RCPT from mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:6169:6c63:6f77::11]: 554 5.7.1 <mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:XXXX:XXXX:6f77::11]>: Client host rejected: Access denied; from=<quarantine@localhost> to=<sale@XXXXXX.ru> proto=ESMTP helo=<quarantine>

**Reproduction of said bug**:

/ quarantine -> show items -> actions - release

**System information**:

| My operating system | Ubuntu 18.04.4 LTS |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 4core |
| Docker Version (`docker version`) | 19.03.9 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

**Comment by andryyy** [comment]
You changed something in main.cf or extra.cf, I guess. It would not reject the client host on that listener.

**Comment by RomanFokin** [comment]
Thank.

We had a mistake was in extra.cf

I apologize :(

**Comment by andryyy** [comment]
\o/ :) No worries.
