### ISSUE TITLE
[Rspamd] Multimap - Bad words (de)

### ISSUE THREAD

**Issue by realizelol** [mailcow/mailcow-dockerized#3575]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Bad words are counted twice if mail is sent in text and html. Which is mostly the default on mail clients.

**Docker container logs of affected containers**:

_none_

**Reproduction of said bug**:

Sent mail with bad words to yourself in html+text / text only / html only.
_Haven't tested the rtf format of MS Outlook. Maybe someone could test it._

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | Apparmor |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare |
| Server/VM specifications (Memory, CPU Cores) | 6GB, 3 Cores |
| Docker Version (`docker version`) | 19.03.9 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | NO |

- No changes at all. Just the code below for testing purpose.

```
BAD_WORDS {
  type = "content";
  filter = "rawtext";
  map = "$LOCAL_CONFDIR/custom/bad_words.map";
  regexp = true;
  score = 0.1;
}

BAD_WORDS_DE {
  type = "content";
  filter = "rawtext";
  map = "$LOCAL_CONFDIR/custom/bad_words_de.map";
  regexp = true;
  score = 0.1;
}
```
should be replaced in line [130-140](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/multimap.conf#L130-L144) so it's counted only once.
Source information: [Rspamd-Multimap-Content-Filters](https://rspamd.com/doc/modules/multimap.html#content-filters)

BTW:
FISHY_TLDS, BAD_WORDS, BAD_WORDS_DE and BAD_LANGUAGES do have curly brackets `{`/`}` in map which aren't set in the other multimaps.
By default it's without these brackets for example:
[Rspamd-Basic-Configuration](https://rspamd.com/doc/configuration/#rspamd-basic-configuration)
or all other configuration files. But this shouldn't be a big deal as you can see here:
[Rspamd-Variables](https://rspamd.com/doc/configuration/#rspamd-variables)

best regards
realizelol

**Comment by andryyy** [comment]
We could also rate it 0.0 and just have it "there".

Is it recommended to use rawtext? What would me miss potentially, if we changed it? :) Nothing?

The curly bracket stuff is a good catch, it triggered my Monk.

**Comment by realizelol** [comment]
Hmm sorry andryyy,

it must be something else which triggered it while I was changing sth else in rspamd.
You're absolutely right, sorry!!

best regards
realizelol

**Comment by andryyy** [comment]
Oh, okay :) No problem at all! I fixed the {} and will push it later.
