### ISSUE TITLE
Setting quarantine notifications from address causes warnings in the postfix logs

### ISSUE THREAD

**Issue by tellytart** [mailcow/mailcow-dockerized#3576]
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Setting a from e-mail address in the form quarantine@mailserv.redactedhostname.com results in quarantine e-mails being sent from this address and delivered to the recipient ok, but also causes warnings in the postfix logs.

**Docker container logs of affected containers**:
Postfix
````
May 26 08:00:02 mailserv postfix/quarantine/smtpd[8443]: connect from mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:6169:6c63:6f77::e]
May 26 08:00:02 mailserv postfix/quarantine/smtpd[8443]: 9D1D5C827B3: client=mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:6169:6c63:6f77::e]
May 26 08:00:02 mailserv postfix/quarantine/smtpd[8443]: warning: Illegal address syntax from mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:6169:6c63:6f77::e] in RCPT command: <>
May 26 08:00:02 mailserv postfix/cleanup[8445]: 9D1D5C827B3: message-id=<>
May 26 08:00:02 mailserv postfix/qmgr[345]: 9D1D5C827B3: from=<quarantine@mailserv.redactedhostname.com>, size=3668, nrcpt=1 (queue active)
May 26 08:00:02 mailserv postfix/quarantine/smtpd[8443]: disconnect from mailcowdockerized_dovecot-mailcow_1.mailcowdockerized_mailcow-network[fd4d:6169:6c63:6f77::e] ehlo=1 mail=1 rcpt=1/2 data=1 quit=1 commands=5/6
May 26 08:00:02 mailserv postfix/lmtp[8446]: 9D1D5C827B3: to=<richard@redactedhostname.com>, relay=dovecot[172.22.1.250]:24, delay=0.21, delays=0.05/0.07/0.02/0.06, dsn=2.0.0, status=sent (250 2.0.0 <richard@redactedhostname.com> YIInLXK+zF4YAwAA9J9BAA Saved)
May 26 08:00:02 mailserv postfix/qmgr[345]: 9D1D5C827B3: removed
````
Dovecot
````
May 26 08:00:02 mailserv CRON[798]: pam_unix(cron:session): session closed for user root
Notifying richard@redactedhostname.com about 1 new items in quarantine
May 26 08:00:02 mailserv dovecot: lmtp(792): Connect from 172.22.1.11
May 26 08:00:02 mailserv CRON[800]: pam_unix(cron:session): session closed for user vmail
May 26 08:00:02 mailserv dovecot: lmtp(richard@redactedhostname.com)<792><YIInLXK+zF4YAwAA9J9BAA>: sieve: msgid=unspecified: stored mail into mailbox 'INBOX'
May 26 08:00:02 mailserv dovecot: lmtp(792): Disconnect from 172.22.1.11: Client has quit the connection (state=READY)

````
**Reproduction of said bug**:
Set a from address in the quarantine configuration then have a quarantined items notification sent.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | CentOS 7 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | AWS Lightsail machine |
| Server/VM specifications (Memory, CPU Cores) | 4GB RAM, 1 CPU core |
| Docker Version (`docker version`) | 19.03.9 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
diff --git a/data/conf/rspamd/custom/global_mime_from_blacklist.map b/data/conf/rspamd/custom/global_mime_from_blacklist.map
index 3c87288..15fabcf 100644
--- a/data/conf/rspamd/custom/global_mime_from_blacklist.map
+++ b/data/conf/rspamd/custom/global_mime_from_blacklist.map
@@ -1 +1,3 @@
-# /.+example\.com/i
+# /.+example\.com/i
+/.+@igain-mail\.co\.uk/i
+/.+rikybonus\.com/i

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
Firewall rules appear not relevant for this case.

**Comment by andryyy** [comment]
Thanks, it always throws that warning. I fixed it and will push it later. :)
