### ISSUE TITLE
Pushover Integration: Allow definition of devices that recieve notifications

### ISSUE THREAD

**Issue by protree** [mailcow/mailcow-dockerized#3577]
**Is your feature request related to a problem? Please describe.**
If I enable Pushover Integration a notification is sent to every device that was added to my Pushover Account.

**Describe the solution you'd like**
It would be nice if I could define which devices should recieve Pushover Notifications. The Pushover API supports setting of parameter "device" that accepts a list of devices that should recieve a notification (See https://pushover.net/api ).

**Comment by andryyy** [comment]
Iirc I setup groups in my PO account and added only devices, I want to receive the notification for.

**Comment by protree** [comment]
Thanks for the hint! I didn‘t know this feature. This is an even better solution :)... Closing...

**Comment by andryyy** [comment]
You are welcome. :)
