### ISSUE TITLE
Duplicating DKIM record results in storing invalid key type

### ISSUE THREAD

**Issue by amjadkamali** [mailcow/mailcow-dockerized#3578]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Emails are not signed with a DKIM key which is duplicated from an existing one.

The key looks valid on the configuration/DKIM keys page but does not get used. The duplicated key seems to be stored using key type "4" instead of whatever it's meant to be.

Workaround is to delete the key and manually copy/paste it under "Import Private Key"

**Docker container logs of affected containers**:

rspamd logs when sending an email with a duplicated key:

`2020-05-27 18:03:36 #969(normal) <4cafb1>; task; dkim_module_load_key_format: cannot load dkim key : invalid key type to load: 4`

**Reproduction of said bug**:

Duplicate key from one domain to another which has doesn't have one, then send an email.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB/4CPU |
| Docker Version (`docker version`) | 19.03.9 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | Nginx |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Thank you!

**Comment by amjadkamali** [comment]
No, thank you!
