### ISSUE TITLE
Add support for spamhaus content

### ISSUE THREAD

**Issue by 5731la** [mailcow/mailcow-dockerized#3579]
**Is your feature request related to a problem? Please describe.**
Spam is bad (not really a specific problem)
**Describe the solution you'd like**
Implement Spamhaus data: https://github.com/spamhaus/rspamd-dqs

**Additional context**
Add any other context or screenshots about the feature request here or remove this section
N/A

**Comment by andryyy** [comment]
Hi,

I cannot do that. You need a key. But you can very, very easily implement their configs in your cow. :)
