### ISSUE TITLE
Throughput monitoring

### ISSUE THREAD

**Issue by treed593** [mailcow/mailcow-dockerized#3581]
**Is your feature request related to a problem? Please describe.**
It is a pain point for me to be able to monitor email volume being sent from a specific Mailcow domain. 

**Describe the solution you'd like**
I would like an API endpoint that can provide me with information on the total volume (throughput) by domain

**Comment by dragoangel** [comment]
Please read docs how configure pflogsumm: https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-pflogsumm/ which is quite fine for most people with small to medium setups.
If this is not enough for you and you want to see nice graphs, multiple periods statistics and so on: you can configure docker to use remote syslog and separate server which will catch & post logs to graylog or logstash, etc. Mailcow use Postfix as SMTP server, so any solutions to monitor/analyze postfix logs will work with Mailcow.
