### ISSUE TITLE
MailCow Migration

### ISSUE THREAD

**Issue by NoobKeksTV** [mailcow/mailcow-dockerized#3583]
Hi,

I used the official migration tutorial to copy my old installation of mailcow to a new server. After i started it there i realized it didnt shot me any old email in sogo. But when checking mailbox setup in the mailcow ui it says i have around 800. 

Is this information stored somewhere else or am i doing something wrong?

Both systems are running the newest docker & mailcow versions on Debian 10

**Comment by NoobKeksTV** [comment]
why is this invalid?

**Comment by NoobKeksTV** [comment]
ok. i redone the whole thing today and now its working.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/83352995-c6b95500-a34f-11ea-99f6-7e53908759c8.png)

![image](https://user-images.githubusercontent.com/2972950/83352998-cc169f80-a34f-11ea-8748-16fb9603ad30.png)

![image](https://user-images.githubusercontent.com/2972950/83353010-e0f33300-a34f-11ea-8628-bfb6b2df741e.png)
