### ISSUE TITLE
UTF8 encoding error when using special chars in comments at aliases

### ISSUE THREAD

**Issue by pahy** [mailcow/mailcow-dockerized#3585]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

E.g. list of aliases will not be shown, when using special chars (like umlauts) in the comment field. The json_encode gives an utf-8-error, so API call will result with empty response.
I suppose this affects several other places.

**Docker container logs of affected containers**:

**Reproduction of said bug**:

E.g. comment an alias with "Mülltermine"

**System information**:

Standard installation without changes.

**Comment by andryyy** [comment]
"I suppose this affects several other places."

Which?

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/83392311-2a498e00-a3f5-11ea-806c-03107e4b3892.png)

Seems to work fine.

![image](https://user-images.githubusercontent.com/2972950/83392656-beb3f080-a3f5-11ea-9c97-07ad001c8e33.png)

**Comment by pahy** [comment]
> "I suppose this affects several other places."
> 
> Which?

I assumed it could be a general error with comment fields.

**Comment by pahy** [comment]
> ![image](https://user-images.githubusercontent.com/2972950/83392311-2a498e00-a3f5-11ea-806c-03107e4b3892.png)
> 
> Seems to work fine.

I will verify it with a clean installation at my site. The current installation is running for a year and just doing the usual updates with update.sh.
I will get back with the results these days.

**Comment by andryyy** [comment]
Ah, okay. :)
I misunderstood.

Do you use an external SQL?

**Comment by pahy** [comment]
No, everything as out of the box.

**Comment by andryyy** [comment]
That's strange.

Could you please run...

```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -uroot -p$DBROOT mailcow -e "SHOW VARIABLES LIKE '%version%';"
```

Which browser do you use? And which OS?

**Comment by pahy** [comment]
OS is latest Arch. Sorry, i did not tell this in OP.

+-----------------------------------+------------------------------------------+
| Variable_name                     | Value                                    |
+-----------------------------------+------------------------------------------+
| in_predicate_conversion_threshold | 1000                                     |
| innodb_version                    | 10.3.23                                  |
| protocol_version                  | 10                                       |
| slave_type_conversions            |                                          |
| system_versioning_alter_history   | ERROR                                    |
| system_versioning_asof            | DEFAULT                                  |
| version                           | 10.3.23-MariaDB-1:10.3.23+maria~bionic   |
| version_comment                   | mariadb.org binary distribution          |
| version_compile_machine           | x86_64                                   |
| version_compile_os                | debian-linux-gnu                         |
| version_malloc_library            | system                                   |
| version_source_revision           | 607467bd63db2c6ca64610eb9f4e703711f4dfc6 |
| version_ssl_library               | OpenSSL 1.1.1  11 Sep 2018               |
| wsrep_patch_version               | wsrep_25.24                              |
+-----------------------------------+------------------------------------------+

**Comment by andryyy** [comment]
That's indeed very strange.

**Comment by andryyy** [comment]
A dump of the alias table would be nice. If you don't mind sharing it, let me know @ info@servercow.de

**Comment by pahy** [comment]
I updated this weekend to the latest commit and tested again. It seems to be fine now :thumbsup:
As i reported the error, the only way to get back to work was to add JSON_INVALID_UTF8_IGNORE to json_decoding (or edit the database, which I have not done)

**Comment by andryyy** [comment]
:) And you removed the JSON_INVALID_UTF8_IGNORE part?

**Comment by pahy** [comment]
of course. i am professional :innocent: but i do not have an explanation for the behaviour

**Comment by andryyy** [comment]
Me neither. 😄

**Comment by pahy** [comment]
Oh no. It is back again.
This time i was looking in the database.
I changed it via the gui - no modifications of the database.
![grafik](https://user-images.githubusercontent.com/20403536/84005729-e105bb00-a96d-11ea-9e98-c621aa65b5bb.png)
![grafik](https://user-images.githubusercontent.com/20403536/84005740-e4994200-a96d-11ea-9a27-d737058c03fb.png)

**Comment by andryyy** [comment]
I can't replicate it. Perhaps your browser uses weird encodings?
Arch and Firefox?
I can try it in a vm.

**Comment by pahy** [comment]
desktop is latest manjaro. i also tried with chrome looking good.
Firefox:
![grafik](https://user-images.githubusercontent.com/20403536/84011486-7c029300-a976-11ea-87fe-0a8f4414fde6.png)
Chrome:
![grafik](https://user-images.githubusercontent.com/20403536/84011531-8d4b9f80-a976-11ea-9c0e-6d73067b8ca9.png)
In the database it is still buggy.
![grafik](https://user-images.githubusercontent.com/20403536/84011842-fc28f880-a976-11ea-9c76-e02edf5d0028.png)
I keep trying to find the cause.

**Comment by pahy** [comment]
I don't know. I am not able to replicate it, too. A test installation is working without hesitation.
Seems to be just within my first installation. All i did with it was running the update.sh regularly. Everything else was done with the gui.
Then please do not bother with it, it seems to concern only this one installation. And thank you very much for the help!

**Comment by andryyy** [comment]
If you like to, you could mail me a dump of the alias table. :)
