### ISSUE TITLE
mailcow two upstream gateways, one backup

### ISSUE THREAD

**Issue by badsmoke** [mailcow/mailcow-dockerized#3587]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | ubuntu 18.04 server  |
| Is Apparmor, SELinux or similar active? | default ubuntu 18.04 settings |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I Virtualbox |
| Server/VM specifications (Memory, CPU Cores) | 6 cores 32Gb RAM |
| Docker Version (`docker version`) | 19.03.6 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | nginx |

Hello, this is not a specific mailcow problem as docker seems to be the problem.
But still, I think the scenario will happen to someone else.

We have connected the server running mailcow to two different internet providers.

One is the primary and the other is the backup mx entry.
This is to ensure that even if one internet connection is lost, the mail server is still reachable.

In both firwalls the port sharing is configured correctly, but I can only connect via the primary isp. But I can access non-docker specific ports like ssh from both isp.

Is there a solution for this problem? 
You could put dovecot and postfix into network_mode: host but that's not very nice

**Comment by andryyy** [comment]
Hi,

This is a bug tracker and not for support.

The DOCKER-USER chain in iptables can be used to filter fwd traffic and the INPUT chain to filter input traffic.
SSH can also be filtered using tcp wrappers hosts.allow/deny.

Please check the channels for community support and servercow.de for commercial support. :)
