### ISSUE TITLE
SSL wrong domain

### ISSUE THREAD

**Issue by mikeleord** [mailcow/mailcow-dockerized#3588]
Hi
I have a problem with ssl certificates.
I set up 2 domains a.com and b.ro, everything was fine until yesterday evening.
today the a.com domain is not recognized by both webUI and email clients.
Any request is made on the second certificate.
SNI is enabled.
what can i check?
many thanks in advance

**Comment by mikeleord** [comment]
update,
the acme container does not find the domain A record, and does not ping.
I put a nameserver in /etc/resolv.conf but on restart it is removed.
same for the unbound container.
how can i solve?

**Comment by remkolodder** [comment]
Please use:
https://community.mailcow.email/
or
https://t.me/mailcow
for support questions. This is something related to your setup. Mailcow uses the unbound container for resolving which is done automatically. Either this was changed on your end, or there is a firewall issue preventing the unbound container to do lookups.

**Comment by mikeleord** [comment]
Hi,
thanks a lot anyway I solved it by inserting in the .conf file 
nameserver - 8.8.8.8 
in the container acme now it goes.
the outbound container worked.
