### ISSUE TITLE
smtpd_tls_cafile should be empty?

### ISSUE THREAD

**Issue by mbrgm** [mailcow/mailcow-dockerized#3589]
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

I found this while trying to setup client certificate authentication with mailcow.

Postfix docs on [`smtpd_tls_CAfile`](http://postfix.cs.utah.edu/postconf.5.html#smtpd_tls_CAfile) say it should be empty when no client certificate authentication is used. As `smtpd_tls_ask_ccert = no` for mailcow, this should be the case. As far as I understand, while `smtp_tls_CAfile` is used for checking remote smtpd's certificates (which is why it is correctly set to the system CA certificates), `smtpd_tls_CAfile` is used for checking client certificates. Setting it to the system CA certificates could lead to a situation where any certificate signed by an official CA is accepted as an client. The more realistic use case would be to let admins set `smtpd_tls_CAfile` to their internal CA cert, which would then allow to `permit_tls_all_clientcerts` for sending.

I would appreciate to have your feedback on this and could send a PR if this should be fixed.

**Docker container logs of affected containers**:

Not relevant.

**Reproduction of said bug**:

See the configuration at e.g. https://github.com/mailcow/mailcow-dockerized/blob/6a95d217b4e2d0efbb4449e2ecc3aed7148f1533/data/conf/postfix/main.cf#L107.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.4 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2 Cores, 8GB Memory |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | - |

**Comment by andryyy** [comment]
Hi,
Yes, the line can be removed or set to empty.
You cannot authenticate with a signed certificate. It is not a security flaw, as no certificate is needed at all. 
I don't know why it was added, but it is indeed useless... :) Thanks.

**Comment by mbrgm** [comment]
One thing I noticed after removing the line was that the logs now say 'untrusted connection from ...' instead of 'trusted connection from ...' on incoming connections. Do you know if this has any impact on e.g. spam score?

**Comment by andryyy** [comment]
It will say anonymous.

Outbound it will be trusted, untrusted, verified etc. - inbound (fixed) should always be anonymous. It looks good here.

**Comment by mbrgm** [comment]
Ok, seems like I got this wrong. Thanks! Keep up the great work. :)

**Comment by andryyy** [comment]
(:
