### ISSUE TITLE
CardDAV issue?

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#359]
Hi,

I'm having problems with CardDAV.
Client:  MacOS 10.12.5, iOS 10.

<img width="393" alt="1" src="https://user-images.githubusercontent.com/24925548/27124952-60c0232c-50fb-11e7-9338-59480fb1db76.png">
<img width="394" alt="2" src="https://user-images.githubusercontent.com/24925548/27124960-698fd0a6-50fb-11e7-9f40-e8952bbbccec.png">

Login and Pass are correct.

`docker-compose log -f`
Only this:
```
nginx-mailcow_1      | IP - - [14/Jun/2017:09:15:03 +0000] "PROPFIND /.well-known/carddav HTTP/1.1" 405 173 "-" "Mac OS X/10.12.5 (16F73) AddressBook/1756.20"
nginx-mailcow_1      | IP - - [14/Jun/2017:09:15:03 +0000] "PROPFIND / HTTP/1.1" 405 173 "-" "Mac OS X/10.12.5 (16F73) AddressBook/1756.20"
nginx-mailcow_1      | IP - - [14/Jun/2017:09:15:03 +0000] "PROPFIND /principals/ HTTP/1.1" 405 173 "-" "Mac OS X/10.12.5 (16F73) AddressBook/1756.20"
```

**Comment by elvirdz** [comment]
You have to login into SOGo 
`https://mail.domain.com/SOGo/dav/user@domain.com/Contacts/personal/` Adressbook
`https://mail.domain.com/SOGo/dav/user@domain.com/Calendar/personal/` Calendar

**Comment by ghost** [comment]
Autodiscovery does not work.

`/.well-known/carddav -> https://mail.domain.com/SOGo/dav/`

Also i get an error:

`CoreDAVHTTPStatusErrorDomain error 405`

**Comment by andryyy** [comment]
Hi, thanks, I fixed it in dev.
