### ISSUE TITLE
Fail2Ban/Netfilter extension

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3596]
Hello,

In times of "malware" on the internet (bots etc.) it would be useful to extend your Fail2Ban or Netfilter to all services like the panel, nginx etc.

I would like that if you can implement that.

I have installed Fail2Ban on my system but it only covers SSH.

Thanks in advance.

**Comment by andryyy** [comment]
Hi,

It is already enabled for all services. Even the Rspamd UI. :)

**Comment by omexlu** [comment]
Ah okay, thank you :)

**Comment by MAGICCC** [comment]
See here for the rules, https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/netfilter/server.py#L36-L44

**Comment by omexlu** [comment]
Maybe offer even more security as it is also possible with Fail2Ban, with botsearch etc.

The current one is not the most necessary one, but it does not cover all rides :)

**Comment by andryyy** [comment]
It covers all failed logins. That's enough. No need to filter more. 
Postscreen filters some malicious crap, too.
