### ISSUE TITLE
Alias target with tag

### ISSUE THREAD

**Issue by pahy** [mailcow/mailcow-dockerized#3597]
An alias could be forwarded to an tagged email-address. E.g.
support@domain -> name+support@domain
So it is handled like the configured tag behaviour, e.g. placed in a subfolder.

**Comment by andryyy** [comment]
There is an open issue for this. We need to include aliases to a redis key. I will close it. :) An issue was opened by @skupfer

**Comment by pahy** [comment]
#2487
