### ISSUE TITLE
.onion service?

### ISSUE THREAD

**Issue by jon-bit** [mailcow/mailcow-dockerized#3601]
**Is your feature request related to a problem? Please describe.**
this is just for security, privacy and anonymity. But can we get a guide on how to set this up as a onion service

**Describe the solution you'd like**
Just how Do I set it up as a hidden service. Is there a guide in the docs (if so I didn't see it) but I have my own hidden service and it works just fine. It will probably provide many grate fetchers for things such as oppressive regime cidacins getting what they mite need. Also before you say you can just use tor it's not the same.  A hidden service and using the tor browser is different.
(sorry for the spelling. I'm dyslexic)

**Comment by mkuron** [comment]
This is way beyond the scope of Mailcow. Your best starting point for this is probably the Tor documentation. You would set it up on the Linux host and publish your Mailcow services from there. You would need to pay special attention to not create an open SMTP relay and not bypass fail2ban though.
