### ISSUE TITLE
vmail-Restore restores nothing

### ISSUE THREAD

**Issue by Ashby666** [mailcow/mailcow-dockerized#3602]
Hi

I try to migrate my mailcow from one host to another. I have done this multiple times before with the helper-scripts without problems, but this time I'm struggeling.

Same OS (CentOS 7), same FQDN, same locations (/opt/mailcow-dockerized), all up-to-date (incl OS and Mailcow). I took a backup before migration with closed SMTP-Ports and copied it to the new host. Here I restored all files, which seems to worked perfectly incl. Domains and Mailboxes. But even though I see every email on the console every time I restore "Mail directory", the mailboxes are still empty.

I tried the option to restore "all" and also "Mail directory".

Has anyone got an idea?

Thank you!

EDIT: SOGo displays, that the mailbox ist to 22.2% full... so the mails incl. subfolder seems to be somewhere, but not visible?

**Comment by andryyy** [comment]
Hi,

Please don't use the issue tracker like this. Do not remove the template. Ask for support in the community. :)

Issue: Is `MAILDIR_SUB` in both mailcow.conf (old and new) the same? Both `MAILDIR_SUB=` or `MAILDIR_SUB=Maildir`?

**Comment by Ashby666** [comment]
Oh, I'm sorry :-)

Got a solution: I had to use the old mailcow.conf, which was backuped, but noch restored. Now everything works fine...

Thank you and sorry once again!
