### ISSUE TITLE
Add/Edit Mailbox dialogs susceptible to wrong password manager fill-in

### ISSUE THREAD

**Issue by ThomDietrich** [mailcow/mailcow-dockerized#3610]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Hey all!

This seems to be a serious issue, at least for a group of users. The error is probably dependent on the browser setup and the use of a password manager or management service. In my case it is Firefox + Bitwarden Password Manager Add-on.

Both the "Add Mailbox" as well as "Edit Mailbox" dialogs mark the "Full name" input field as `name="name"` and the password fields as `type="password" name="password"` and `type="password" name="password2"`.

This use of input field attributes results in Bitwarden **filling in login credentials** in these fields. This is clearly not supposed to happen.
**Worse:** When editing an existing user (e.g. changing their quota) the password is **replaced** by my personal password **unnoticed**. The user suddenly can't login any more. This is serious...

I am not an expert on how to design input forms nowadays but the way fields are specified atm I can only assume that other password managers beside Bitwarden show similar behavior.

This is imho a critical bug. Please let me know how I can help, whichever way possible.

Best!

(I believe the rest of the template does not fit the kind of bug and removed it. Please let me kindly know if further details are missing).

**Comment by andryyy** [comment]
I don't have this problem with KeePass and common auto-fillers. 

I don't understand how this is critical. :/ You could only inject new passwords when you are able to inject something into Bitwarden in the first place. If you had access to Bitwarden you wouldn't need to inject a new password to mailcow. You already had all passwords. 

I seriously cannot reproduce this with any auto-filling tool. If it annoys you and it is only Bitwarden, you may want to ask them. :)
