### ISSUE TITLE
nextcloud missing php modules

### ISSUE THREAD

**Issue by Oratorian** [mailcow/mailcow-dockerized#3611]
after running nextcloud.sh and opening the cloud nextcloud greets me with a messages that it is missing php modules bcmath and gmp

is there a way to install them and how.

**Comment by andryyy** [comment]
Can you update mailcow and try again?

**Comment by Oratorian** [comment]
Thx fixed now.

PS: nextcloud.conf in nginx needs

add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
otherwise nextcloud will also complain with a security warning.
