### ISSUE TITLE
docker: invalid reference format. running backup_and_restore.sh

### ISSUE THREAD

**Issue by Mycah** [mailcow/mailcow-dockerized#3613]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When running `/opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all` I get several errors:

```
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
docker: invalid reference format.
See 'docker run --help'.
```

**Docker container logs of affected containers**:

Running bash -x backup_and_restore.sh backup all i see the following:

```
+ docker run --name mailcow-backup --rm -v /tmp/tmp.gDxN11xJxQ/mailcow-2020-06-14-00-00-01:/backup -v mailcowdockerized_vmail-vol-1:/vmail:ro /bin/tar --warning=no-file-ignored '--use-compress-program=gzip --rsyncable --best' -Pcvpf /backup/backup_vmail.tar.gz /vmail
docker: invalid reference format.
See 'docker run --help'.
++ docker volume ls -qf name=mailcowdockerized_crypt-vol-1
+ docker run --name mailcow-backup --rm -v /tmp/tmp.gDxN11xJxQ/mailcow-2020-06-14-00-00-01:/backup -v mailcowdockerized_crypt-vol-1:/crypt:ro /bin/tar --warning=no-file-ignored '--use-compress-program=gzip --rsyncable --best' -Pcvpf /backup/backup_crypt.tar.gz /crypt
docker: invalid reference format.
See 'docker run --help'.
++ docker ps -qf name=redis-mailcow
+ docker exec e60157cc7d87 redis-cli save
++ docker volume ls -qf name=mailcowdockerized_redis-vol-1
+ docker run --name mailcow-backup --rm -v /tmp/tmp.gDxN11xJxQ/mailcow-2020-06-14-00-00-01:/backup -v mailcowdockerized_redis-vol-1:/redis:ro /bin/tar --warning=no-file-ignored '--use-compress-program=gzip --rsyncable --best' -Pcvpf /backup/backup_redis.tar.gz /redis
docker: invalid reference format.
See 'docker run --help'.
++ docker volume ls -qf name=mailcowdockerized_rspamd-vol-1
+ docker run --name mailcow-backup --rm -v /tmp/tmp.gDxN11xJxQ/mailcow-2020-06-14-00-00-01:/backup -v mailcowdockerized_rspamd-vol-1:/rspamd:ro /bin/tar --warning=no-file-ignored '--use-compress-program=gzip --rsyncable --best' -Pcvpf /backup/backup_rspamd.tar.gz /rspamd
docker: invalid reference format.
See 'docker run --help'.
++ docker volume ls -qf name=mailcowdockerized_postfix-vol-1
+ docker run --name mailcow-backup --rm -v /tmp/tmp.gDxN11xJxQ/mailcow-2020-06-14-00-00-01:/backup -v mailcowdockerized_postfix-vol-1:/postfix:ro /bin/tar --warning=no-file-ignored '--use-compress-program=gzip --rsyncable --best' -Pcvpf /backup/backup_postfix.tar.gz /postfix
docker: invalid reference format.
See 'docker run --help'.
```

**Reproduction of said bug**:

Every time I run backup it shows these errors.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu |
| Is Apparmor, SELinux or similar active? | Apparmor Yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 16gb RAM 4 core 3.5ghz |
| Docker Version (`docker version`) | Docker version 19.03.11, build 42e35e61f3 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.26.0, build d4451659 |
| Reverse proxy (custom solution) | caddy |

**Comment by andryyy** [comment]
Can't confirm. 

Im either blind or you are missing the docker image in the run commands. 

Please use the unmodified default script from the repository, if you changed it.

**Comment by Mycah** [comment]
I didn't change anything.  It's all default.

**Comment by andryyy** [comment]
I cannot reproduce it, sorry.

**Comment by torsten-online** [comment]
Hi Mailcow Users,

I want to leave a note here: 

Please dont run mailcow backup_and_restore.sh without a running mailcow.

When the mailcow is down over docker compose, then for me it happens, that for example the network settings can not be listed, so you will get the error "docker: invalid reference format." because for example the parameter --network will be empty.

kind regards
Torsten

**Comment by perryflynn** [comment]
In my case the error was cause because I renamed the `mailcow-network`  network inside of the docker-compose file.

I also observed, that `docker compose` will create containers and networks with a `-` as separator in the names, but `docker-compose` will use a `_`. Maybe this can also be a problem.
