### ISSUE TITLE
[Feature Request ] Show encryption method used

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#3614]
Would be nice to see which encryption method was used when sending/receiving an email :) in mailcow web ui :) 

I think this would be a nice place for that :) external logs rspamd: 

![BF2ECFAF-BAC2-4254-AA49-71C0BF384CB6](https://user-images.githubusercontent.com/16965460/84862813-24e67780-b074-11ea-805c-7034d91339e2.png)

**Comment by mkuron** [comment]
rspamd doesn't have that information. It is present in the Postfix logs though:
![Screen Shot 2020-06-17 at 09 24 19](https://user-images.githubusercontent.com/1748330/84868057-61b66c80-b07c-11ea-869b-8efd2750e1c4.png)
Postfix only logs the message ID and not the subject line though, so you'll need to manually figure out which line corresponds to which message. The best place to look for encryption information is in the message headers once it has been stored in your inbox:
![Screen Shot 2020-06-17 at 09 27 24](https://user-images.githubusercontent.com/1748330/84868343-d4274c80-b07c-11ea-867b-a55676fc9853.png)

**Comment by ghost** [comment]
@wuast94 This isn't an optimal solution, but there's a plugin for Roundcube which exposes this information in the webmail client: https://github.com/GermanCoding/Roundcube_TLS_Icon
