### ISSUE TITLE
[SOGo] can't setup TRANSFER address to automatically forward email

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3616]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When we try to modify the TRANSFER preferences section we can't save it, everything is fine with other tabs. Nothing interesting seems to be printed on the SOGo log file.

Here is a short screen recording depicting the problem:
![Screen Recording 2020-06-22 at 11 14 37](https://user-images.githubusercontent.com/41020854/85270744-0d472e80-b47a-11ea-8a13-46a31d3e4f8d.gif)

**Docker container logs of affected containers**:

```
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23567]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23568]: pam_unix(cron:session): session opened for user sogo by (uid=0)
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23569]: (sogo) CMD (  /usr/sbin/sogo-tool expire-sessions 480)
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23570]: (sogo) CMD (  /usr/sbin/sogo-ealarms-notify -p /etc/sogo/sieve.creds 2>/dev/null)
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23567]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Jun 22 11:09:01 ddbee9faa48e CRON[23568]: pam_unix(cron:session): session closed for user sogo
sogo-mailcow_1       | Jun 22 11:09:06 ddbee9faa48e sogod [586]: 2a03:2c40:10:461::1 "GET /SOGo/ HTTP/1.0" 200 29497/0 0.021 - - 0
sogo-mailcow_1       | Jun 22 11:09:17 ddbee9faa48e sogod [11]: [WARN] <0x0x5650720610c0[WOWatchDogChild]> pid 16688 has been hanging in the same request for 14 minutes
sogo-mailcow_1       | Jun 22 11:09:20 ddbee9faa48e sogod [11]: [WARN] <0x0x565072063bd0[WOWatchDogChild]> pid 79 has been hanging in the same request for 6 minutes
```

**Reproduction of said bug**:

I checked the `data/conf/sogo/sogo.conf` file but didn't modified a thing since the initial deploy. The problem occurs on every domain added in Mailcow.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 2 cores, 8GiB RAM |
| Docker Version (`docker version`) | 19.03.11 |
| Docker-Compose Version (`docker-compose version`) | 1.26.0, build d4451659 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

No modifications regarding these last 3 points, everything is fine.

**Comment by andryyy** [comment]
Check the browsers dev console and better create an issue at SOGo/inverse.. :)

**Comment by ghost** [comment]
> Check the browsers dev console and better create an issue at SOGo/inverse.. :)

Thanks for your input, there is indeed an error:
```
Failed to load resource: the server responded with a status of 404 ()         https://mail.domain.lol/SOGo/so/test@test.net/activeExternalSieveScripts
```

I'll create an issue at Inverse right away.

**Comment by ghost** [comment]
There is even a bug report already open for this: https://sogo.nu/bugs/view.php?id=5053

**Comment by jacboy** [comment]
Is there a way to manually create forwarding rules?

**Comment by andryyy** [comment]
I updated the image this afternoon, can you check it again?

@jacboy Yes, in the UI, /mailbox -> Filters. :)

**Comment by ghost** [comment]
> I updated the image this afternoon, can you check it again?

Many thanks, the bug is indeed fixed.
Closing! 🎉
