### ISSUE TITLE
[Question] MAILER-DAEMON sends replies on every successful outgoing mail - Why?

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#362]
On one of my instances the mailer daemon sends a reply for every successful outgoing mail. I don't know why, though, I didn't set it up like this.

Any idea why this is happening and how I could change this?

I want to wait a bit longer until the next git pull, to see if everything's working alright for others.

**Comment by mkuron** [comment]
That's certainly not supposed to happen and Mailcow isn't set up to do that on purpose. To find out why this is happening, you'd need to provide one of these mailer daemon messages and the corresponding lines from the Postfix log.

**Comment by Braintelligence** [comment]
The postfix log says something like:
`"OPTIONS /SOGo/dav/username%40mydomain.de/ HTTP/1.0" 200 0/0 0.002 - - 0`

While the MAILER-DAEMON says 
```
This is the mail system at host mail.mydomain.de.

Your message was successfully delivered to the destination(s)
listed below. If the message was delivered to mailbox you will
receive no further notifications. Otherwise you may still receive
notifications of mail delivery errors from other systems.

The mail system

<someuser@somedomain.de>: delivery via
   mail.somedomain.de[some.ip.add.ress]:25: 250 ok:  Message 4333344 accepted
<Delivery report>
yada yada yada
```

EDIT: Wait, the above is not the postfix but the SOGo log. Let me get the real one real quick.

**Comment by mkuron** [comment]
I think you looked at the SOGo or Nginx log, we need the Postfix log though.

It seems like your email client is configured to request a Delivery Status Notification from the SMTP server. That's why Postfix sends them. There should by a client-side option for this. What email client are you using? Do these messages also get sent when you use SOGo?

**Comment by Braintelligence** [comment]
They get sent by Outlook I think.
I already edited my original message saying that I accidentally copied the SOGo log. I'm trying to get a postfix log now, because the log file got too large and doesn't contain the latest example anymore. Will post in a sec.

**Comment by Braintelligence** [comment]
Well yeah, I tried to generate another such mail from the MAILER-DAEMON by sending a mail from a smartphone but it didn't happen.
So it seems that only Outlook is triggering this behaviour.
Will try to find this option now.

EDIT: Totally forgot: THANKS @mkuron :).

**Comment by mkuron** [comment]
See https://support.office.com/en-us/article/Add-and-request-read-receipts-and-delivery-notifications-a34bf70a-4c2c-4461-b2a1-12e4a7a92141 for the option to enable delivery notifications in Outlook.

**Comment by Braintelligence** [comment]
That's very courteous, thank you 👍 .

**Comment by Braintelligence** [comment]
For anyone, that's interested in the German version:
https://support.office.com/de-de/article/Hinzuf%C3%BCgen-und-Anforderung-lesen-Belege-und-%C3%9Cbermittlung-Benachrichtigungen-a34bf70a-4c2c-4461-b2a1-12e4a7a92141
