### ISSUE TITLE
hi everyone , im new for this mailcow :)  my problem is after start sogo my system slows down

### ISSUE THREAD

**Issue by yusufceng** [mailcow/mailcow-dockerized#3620]
when i start mailcow there is a no problem my system is very good working, but in mailbox add domain and restart sogo containers after this my system is freeze every think is freezeing, even my vps server i can't do anything. and i read your step you said before down sogo version. and i did but this time sogo not working.

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template.
GitHub is not a support forum. Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
