### ISSUE TITLE
Alias not available in SOGo since last update

### ISSUE THREAD

**Issue by nicolaspernoud** [mailcow/mailcow-dockerized#3621]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Since last SOGo update, when creating a mail, the alias are not shown in the sender dropdown... 
Alias works fine when using an IMAP Client.

**Docker container logs of affected containers**:
Not relevant (UI)

**Reproduction of said bug**:
Create an alias and try to send a mail with it from SOGo...

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Linux Debian 10 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VPS at scaleway |
| Server/VM specifications (Memory, CPU Cores) | 2/2 |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.26.0 |
| Reverse proxy (custom solution) | Vestibule 4.3 https://github.com/nicolaspernoud/Vestibule |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by nicolaspernoud** [comment]
It would seems that in the new version of SOGo, identities can be set with customs signatures etc. So maybe this behavior is normal. Is it safe to create custom identities associated with alias mails or will it mess up the sync between the mailcow stack and SOGo ?

**Comment by andryyy** [comment]
I think they indeed changed that to push using identities. You can set custom full names now though. That's a plus. Perhaps they should add a button to jump to the identity box though. I will try to sponsor that feature.

**Comment by andryyy** [comment]
I created a ticket, asked if they liked the idea and will sponsor it. I also asked to add a "+" sign to the dark, expandable folder icons.

**Comment by nicolaspernoud** [comment]
Ok, thanks a lot. Since the behaviour is normal, I'm closing the issue.
