### ISSUE TITLE
SOGo save icon greyed out and cannot be used when adding a email forward incoming messages addresses

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#3625]
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

After creating a new email mailbox and logging into the SOGo web interface for the account and adding a email address for forwarding the save icon is greyed out:

![Screenshot of the problem](https://docs.webarch.net/w/images/f/ff/Screenshot_2020-06-28_SOGo_Groupware.png)

I have looked at the logs of the SOGo POST and GETs and there doesn't appear to be anything of interest there.

To reproduce the bug I created a test account, `testing@test.webarch.co.uk` and loged into SOGo as that user and tried to add a forwarding address.

| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Xen |
| Server/VM specifications (Memory, CPU Cores) | 42GiB RAM 12 CPU cores |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.0 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code?

This appears to be the only SOGo result in the diff:

```diff
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 65f5301f..0cda1080 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );

-    WOWorkersCount = "20";
+    WOWorkersCount = "120";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
diff --git a/data/web/img/cow_mailcow.svg b/data/web/img/cow_mailcow.svg
index 6ba98e46..b41f7b4f 100644
--- a/data/web/img/cow_mailcow.svg
+++ b/data/web/img/cow_mailcow.svg
@@ -9,6 +9,9 @@
    xmlns="http://www.w3.org/2000/svg"
    xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
    xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
+   width="270"
+   height="240"
+   id="svg2907"
    version="1.1"
    id="layer1"
    x="0px"
@@ -27,11 +30,8 @@
      id="defs75" /><sodipodi:namedview
      pagecolor="#ffffff"
      bordercolor="#666666"
-     borderopacity="1"
-     objecttolerance="10"
-     gridtolerance="10"
-     guidetolerance="10"
-     inkscape:pageopacity="0"
+     borderopacity="1.0"
+     inkscape:pageopacity="0.0"
      inkscape:pageshadow="2"
      inkscape:window-width="1721"
      inkscape:window-height="1177"
```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

I don't believe that this issues is related to a firewall or DNS.

**Comment by andryyy** [comment]
But we are not SOGo. :/

**Comment by chriscroome** [comment]
Thanks @andryyy I'll look at raising it with them.

**Comment by andryyy** [comment]
Try the next nightly, sec, I will upload it. :) Give me 2 minutes. I think they fixed that.

**Comment by chriscroome** [comment]
Thanks, I'll do that in a bit.

This looks like the upstream issue, I'll post a comment there:

https://sogo.nu/bugs/view.php?id=4953

**Comment by chriscroome** [comment]
Cheers @andryyy that fixed it!

![Screenshot of problem resolved](https://docs.webarch.net/w/images/7/70/Screenshot_2020-06-28_SOGo_Groupware%281%29.png)

**Comment by ghost** [comment]
FYI duplicate #3616

**Comment by beckzg** [comment]
Hi,

  today we updated our mailcow and the same issue occured, do I need to open a new issue?

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4 vCPU and 16GB RAM |
| Docker Version (`docker version`) | 20.10.11 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | HAProxy |

In the browsers web development tools I see the following error:

Failed to load resource: the server responded with a status of 404 ()
https://\<mailcow server\>/SOGo/so/\<account\>/activeExternalSieveScripts
