### ISSUE TITLE
Basic Authentication 

### ISSUE THREAD

**Issue by Reiasa** [mailcow/mailcow-dockerized#3628]
Hello, I'd like to add Nginx Basic HTTP Authentication on the main Mailcow interface (not the SOGo one). I looked into the nginx files and tried a few things but it doesn't seem to hit the right mark. Can anyone help me in finding the right file to edit and what to add exactly?

**Comment by shiz0** [comment]
Hello.
Please do not ignore the template!
Also this is not an issue, but more a support question. Please use our community support channels for that.
Board: https://community.mailcow.email/
Or on Telegram: https://t.me/mailcow
Besides, you should think about if you really want to edit mailcow's internal files and potentially having to track your changes across updates. I'd suggest maybe putting a reverse proxy in front (as described in the docs: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/) an doing http auth there, if that's required.
Closing.
