### ISSUE TITLE
nginx-mailcow not processing logins to EAS with external userdb settings, SoGo works

### ISSUE THREAD

**Issue by osnet** [mailcow/mailcow-dockerized#3630]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Logging in from outside with EAS / ActiveSync, gets passed through the following steps:
mailcow_nginx > mailcow_php_fpm > mailcow_dovecot 
With dovecot using external userdb settings in extra.conf ( providing passwords via LDAP ) there is no chance to use EAS.
EAS needs the proper user/password combination from the "mailcow UI".

Since dovecot and sogo are working fine with external LDAP auth, the usage of other auth_methods should be enabled in the UI.

**Docker container logs of affected containers**:

nginx-mailcow_1      | 2020/07/03 14:34:34 [error] 18#18: *2520 FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for dummyduck@xxxx by 127.0.0.1" while reading response header from upstream, client: 127.0.0.1, server: xxxxx, request: "GET /sogo-auth HTTP/1.0", upstream: "fastcgi://172.22.1.9:9002", host: "xxxxx"

**Reproduction of said bug**:

switching to lokal pw, everything works fine. 

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Centos7|
| Is Apparmor, SELinux or similar active? | mope, permissive |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Xen, XCPv8 |
| Server/VM specifications (Memory, CPU Cores) | 8vCPU |
| Docker Version (`docker version`) | docker-ce :latest |
| Docker-Compose Version (`docker-compose version`) | latest |
| Reverse proxy (custom solution) | nginx as in documentation |

**Comment by andryyy** [comment]
EAS is provided by SOGo and therefore uses the SOGo domain dict for authentication.
We do not provide LDAP interfaces.

Please read the issue template, we do not provide any support over GitHub, sorry. :(
