### ISSUE TITLE
[Feature Request] find marked messages in the archive

### ISSUE THREAD

**Issue by dermitdemdino** [mailcow/mailcow-dockerized#3634]
**Is your feature request related to a problem? Please describe**
You will not find any marked messages in the archive with the search

**Describe the solution you'd like**
It should be possible to find marked messages also in the archive

**Comment by mkuron** [comment]
I don‘t understand the problem. Please give a step-by-step guide how to reproduce it, including screenshots.

**Comment by dermitdemdino** [comment]
The problem concerns "Webmail Pro":

Mark an e-mail ...
![exam1](https://user-images.githubusercontent.com/6813869/86536627-558a3600-bee9-11ea-9bf0-52b5f19efa0d.png)

... and this is shown in the "Marked" folder
![exam2](https://user-images.githubusercontent.com/6813869/86536628-56bb6300-bee9-11ea-9d5a-7a2e8653834b.png)

After the email has been archived, it is no longer in the "Marked" folder, and you cannot find marked emails with the search function unless you browse through the entire email archive, which is very tedious.

**Comment by mkuron** [comment]
Afterlogic‘s Webmail Pro Is not part of Mailcow. We could only help you with SOGo. In any mail client, the "Flagged" folder is a virtual folder that is populated by the client. Usually it includes at least Inbox and Sent, and other folders may or may not be configurable.

**Comment by dermitdemdino** [comment]
OK, I didn't know that. Thanks for the info!

**Comment by andryyy** [comment]
Hi Dino,

You are talking about the hosted mailcow, right? :)
Please open a ticket with us on Servercow. :)

André
