### ISSUE TITLE
postfix check in expiry-date.sh not checking postfix cert

### ISSUE THREAD

**Issue by fherbert** [mailcow/mailcow-dockerized#3636]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
expiry-date.sh script doesn't check postfix service, instead it checks the dovecot service.

**Reproduction of said bug**:
run `bash helper-scripts/expiry-dates.sh`, the check for postfix uses the same port (143) and starttls protocol (imap) as dovecot, so doesn't actually check the postfix certificate.

**Comment by andryyy** [comment]
Thanks!
