### ISSUE TITLE
I really need your help(Mailcow change volume to a different network local storage)

### ISSUE THREAD

**Issue by rexkyle** [mailcow/mailcow-dockerized#3638]
Good day,
i really need help regarding changing volume for mailcow, beacuse i have only limited hardrive on my ubuntu 18.04. 
i followed this instruction https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-vmail-volume/ and the error came with this Starting mailcowdockerized_dovecot-mailcow_1 ... error ERROR: for mailcowdockerized_dovecot-mailcow_1  Cannot start service dovecot-mailcow: error while mounting volume '/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data': failed to mount local volume:

ERROR: for dovecot-mailcow  Cannot start service dovecot-mailcow: error while mounting volume '/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data': failed to mount local volume:

in my fstab
# automount from synology box
192.168.1.4:/volume1/MailServer /home/mail nfs nouser,rsize=8192,wsize=8192,atime,auto,rw,dev,exec,suid 0 0

Please help me

**Comment by patschi** [comment]
1. This is a Docker issue as it even fails before starting any container from mailcow
2. Synology is not supported from us, as it causes different strange behaviors and should not be used anything but testing
3. You ignored the issue template. (Well done.)
4. Issues are not for support/questions. That's what the [community forum](https://community.mailcow.email/) was built for.

Closing.

**Comment by rexkyle** [comment]
what if i will buy another hardrive with a large capacity to make another slave.. is it possible?

**Comment by andryyy** [comment]
? This is a bug tracker. :(

**Comment by rexkyle** [comment]
sir @andryyy what do you mean?
may ubuntu 18.04 only have 240gb
and if have extra hardive on my computer with 2tb.. is it possible to transfer the volume in my 2tb drive?

**Comment by shiz0** [comment]
He means: Please don't abuse this bug tracker as a support channel.
Join the board https://community.mailcow.email/ or Telegram Channel https://t.me/mailcow for this.
Yes, it's possible to use another hard drive or nfs target for volume storage, but that won't be discussed here.

**Comment by rexkyle** [comment]
I am really sorry..
