### ISSUE TITLE
Webui Postfix log not showing email address

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#364]
The Postfix log readout on the webui dose not seem to display the email address for from= and to=.

![image](https://user-images.githubusercontent.com/14151000/27190488-83295bf8-51ec-11e7-91f7-7fbdd89c9110.png)

But if you check the log via docker-compose logs postfix-mailcow the email address is in the log, i had a quick look at the code for getting the log and can't see anything that is causing this issue

**Comment by andryyy** [comment]
Thanks!
