### ISSUE TITLE
No mailbox selected

### ISSUE THREAD

**Issue by yuriipaneiko** [mailcow/mailcow-dockerized#3640]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Hello, i have problem with "No mailbox selected". Previously it worked fine, but unfortunately i deleted all containers from system. So i install it again, and have this. I try to reinstall several times. I know that it can appear if dovecot is not working, but it working! So what i can do to fix it?

**Docker container logs of affected containers**:

**Reproduction of said bug**:
  Fresh install on Ubuntu 18.04

**System information**:

| Question | Answer |
| --- | --- |
| My operating system |Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) |Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 64GB |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**. 

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by Braintelligence** [comment]
You closed this issue. Does this mean you solved your problem? Mind to share how you solved it?
