### ISSUE TITLE
Mailcow problem with disabled ipv6

### ISSUE THREAD

**Issue by yuriipaneiko** [mailcow/mailcow-dockerized#3641]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Mailcow working only with ipv6 enabled. When i disable it i have "No mailbox selected". It work fine previously, but i need to reset my server. After fresh reinstall it stopped working with ipv4.

**Docker container logs of affected containers**:

**Reproduction of said bug**:
Fresh reinstall with disabled ipv6.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system |Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | No|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | i7-7700, 64 gb|
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
`-  do-ip6: yes`
`+  do-ip6: no`
`-    enable_ipv6: true`
`+    enable_ipv6: false`
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
`;; connection timed out; no servers could be reached
`

**Comment by MrHappy** [comment]
I've the same issue/ Fresh install, disabled ipv6.
The logging of dovecot fills up with
`curl: (6) Could not resolve host: <<>>`
`Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.`
`curl: (28) Resolving timed out after 15000 milliseconds`

**Comment by yuriipaneiko** [comment]
Close this issue, because it was my mistake, i don't disable ipv6 on server
