### ISSUE TITLE
[IMPROVEMENT] Increase Sync Job Interval

### ISSUE THREAD

**Issue by WeWin55** [mailcow/mailcow-dockerized#3642]
HI,

im switching from a self made postfix, dovecot and imapsync server to mailcow now.

What im wondering about is, why the sync job interval is limited to 3600 mins (2,5 days) per job.
It would be nice if the interval between the jobs could be defined in a higher range.

I would start a pull request, but im not familiar with coding.
Here is the part from the web gui:
https://github.com/mailcow/mailcow-dockerized/blob/becc50591d7092b387725707c314e9675f12e143/data/web/modals/user.php

**Comment by andryyy** [comment]
Hi,

I set it to 1 month now.

**Comment by WeWin55** [comment]
Thank you very much!

Super fast answer :)

**Comment by andryyy** [comment]
You are welcome. :)
