### ISSUE TITLE
SOGo attachement size

### ISSUE THREAD

**Issue by Oratorian** [mailcow/mailcow-dockerized#3653]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

I cannot upload any attchement lagrer then 1mb.

I set message_size_limit in main.cnf and restarted postfix
I also tried to set SOGo`s own configuration WOMaxUploadSize
but everytime the file is larger then 1mb SOGo just responds with Error while uploading ....

I tried to check nginx, phpfpm, sogo and all other logfiles but none of them gave me any help.

php-fpm is set to 2GB uploadsize since i am running nextcloud.

**Docker container logs of affected containers**:

**Reproduction of said bug**:

-

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 LTS |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | no |
| Server/VM specifications (Memory, CPU Cores) | I7-7700 6 cores 32GB Ram |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

Output of git diff
[https://pastebin.com/xxTDdh1p](https://pastebin.com/xxTDdh1p)

**Comment by andryyy** [comment]
Please don't delete the issue template without reading it. :(

If you use a reverse proxy, check it please.

**Comment by Oratorian** [comment]
I am not running any reverse proxies.

i installed mailcow as shown in your wiki and calling SOGo with https://hotname/SOGo

**Comment by Oratorian** [comment]
i finally got some logfiles which could maybe show what is going on

nginx-mailcow_1      | 2020/07/13 21:15:07 [error] 21#21: *53 client intended to send too large body: 1332309 bytes,

i checked and saw that "client_max_body_size" is already set to 0 in all nginx config files.

this problem also only persists in sogo and emails sent whith pop/imap/activesync

just tried uploading the same file in my nextcloud which was installed with the helperscript works just fine.

**Comment by andryyy** [comment]
I tested it and cannot replicate it. 

Have you tried the demo? Can you test it there, please?

**Comment by Oratorian** [comment]
I just deleted my mailcow-dockerized folder with all contents and cloned it new.

i dont know why but somehow everything just works fine now.
