### ISSUE TITLE
can Pull  mailcow/sogo:1.79,

### ISSUE THREAD

**Issue by n1ck-unikat** [mailcow/mailcow-dockerized#3654]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

update can not pull  mailcow/sogo:1.79

docker.io/mailcow/phpfpm:1.64
Error response from daemon: manifest for mailcow/sogo:1.79 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.79, retrying...
Error response from daemon: manifest for mailcow/sogo:1.79 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.79, retrying...
Error response from daemon: manifest for mailcow/sogo:1.79 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.79, retrying...
Error response from daemon: manifest for mailcow/sogo:1.79 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.79, retrying...

Too many failed retries, exiting

**Docker container logs of affected containers**:

**Reproduction of said bug**:

i run update.sh and manually docker pull mailcow:sogo:1.79

**System information**:
<!--
  In this stage we would kindly ask you to attach general system information about your setup.
  Please carefully read the questions and instructions below.
--

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8Gb 4CPU |
| Docker Version (`docker version`) | Docker version 19.03.12, build 48a66213fe |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.26.2, build eefe0d31 |
| Reverse proxy (custom solution) | NGINX |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by bstaeheli** [comment]
Same error here :(

**Comment by andryyy** [comment]
Fixed. :)
