### ISSUE TITLE
Problem mit Let´s Encrypt

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3658]
Hallo leider erstellt Mailcow kein Let´s Encrypt Zertifikat beim installieren.

Im Log steht folgendes:
Attaching to mailcowdockerized_acme-mailcow_1
acme-mailcow_1       | Wed Jul 15 13:40:26 UTC 2020 - Waiting for Docker API...OK
acme-mailcow_1       | Wed Jul 15 13:40:26 UTC 2020 - Waiting for database... Uptime: 0  Threads: 8  Questions: 7  Slow queries: 0  Opens: 17  Flush tables: 1  Open tables: 11  Queries per second avg: 0.000
acme-mailcow_1       | OK
acme-mailcow_1       | Wed Jul 15 13:40:28 UTC 2020 - Waiting for Nginx... OK
acme-mailcow_1       | Wed Jul 15 13:40:29 UTC 2020 - Waiting for domain table... OK
acme-mailcow_1       | Wed Jul 15 13:40:49 UTC 2020 - Initializing, please wait...
acme-mailcow_1       | Wed Jul 15 13:40:49 UTC 2020 - Generating missing domain private rsa key...
acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
acme-mailcow_1       | ................................................++++
acme-mailcow_1       | ...............................................................................................................................++++
acme-mailcow_1       | e is 65537 (0x010001)
acme-mailcow_1       | Wed Jul 15 13:40:50 UTC 2020 - Generating missing Lets Encrypt account key...
acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
acme-mailcow_1       | ................................................................................................++++
acme-mailcow_1       | ..............++++
acme-mailcow_1       | e is 65537 (0x010001)
acme-mailcow_1       | Wed Jul 15 13:40:52 UTC 2020 - Detecting IP addresses... OK

Das hier hatte ich auch schon probiert ändert allerdings nichts.
cd /opt/mailcow-dockerized
mv data/assets/ssl data/assets/ssl_backup
cp -rp data/assets/ssl-example/ data/assets/ssl
docker-compose restart acme-mailcow

**Comment by shiz0** [comment]
Hi,
sonst steht in dem Log nichts? Müsste doch noch weiter gehen, oder?

**Comment by ghost** [comment]
Moin,
hatte diesen Befehl genutzt: `docker-compose logs -f --tail=200 acme-mailcow`

**Comment by shiz0** [comment]
Hi.
Also erstmal: Bitte nicht das Template ignorieren!
Es müsste aber noch mehr in dem Log stehen. Was du gepostet hast ist nur die Initialisierung, aber ich sehe da keinen Versuch, ein Cert zu holen.
Das hier ist ein reiner Bugtracker. Für Community Support nutze bitte die entsprechenden Kanäle: https://mailcow.github.io/mailcow-dockerized-docs/#community-support
Ich mach hier erstmal zu.
