### ISSUE TITLE
redis high memory consumption

### ISSUE THREAD

**Issue by sfinke0** [mailcow/mailcow-dockerized#366]
Hi there,

I noticed after a few days of running mailcow that the memory consumption of redis is quite high

```
# Memory
used_memory:710800336
used_memory_human:677.87M
used_memory_rss:737562624
used_memory_rss_human:703.39M
used_memory_peak:711850752
used_memory_peak_human:678.87M
total_system_memory:4143362048
total_system_memory_human:3.86G
used_memory_lua:51200
used_memory_lua_human:50.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.04
mem_allocator:jemalloc-4.0.3

```

Since this machine only has 4 gigs of ram and also other services are running here, redis once got killed by the oom killer. 
Also the prerequisites say only 1 gig ram is required to run mailcow, which is definitly not enough when clamav requires ~800megs and redis also ~800megs of ram. 

Is this intended behaviour?

**Comment by andryyy** [comment]
Redis is an in-memory storage. A large Bayes database will result in high memory usage. You want these hashes to be stored in RAM.

You could disable Bayes. Or reconfigure Redis. But I don't recommend doing either. 

Please let services use your available memory!

**Comment by sfnke** [comment]
Thanks for that quick reply and clarification.

Just wanted to clarify if this was intended, which it is :)

**Comment by stAn47** [comment]
hello, how do i limit memory for redis ? i prefere syslog for any logging and redis is now at 100GB RAM !!! 
thank you, best regards, stan

**Comment by patschi** [comment]
Please don't necrobump 8 year old GitHub issues. redis is not related to syslog in any way, these are different things. Open a post in the community forum for assistance from the community.
