### ISSUE TITLE
Waiting for SQL... And no start of webserver

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3663]
I restarted my VPS and now, running this command (`docker-compose logs --tail=200 php-fpm-mailcow`), I always get this message and nothing happens:
```
Attaching to mailcowdockerized_php-fpm-mailcow_1
php-fpm-mailcow_1    | Waiting for SQL...
```
The last line is send more and more (like in a loop).

I also get this error, when attempting to connect:
![2020-07-17_18h35_09](https://user-images.githubusercontent.com/44708000/87809801-3fbb3000-c85c-11ea-82f1-409526514878.png)

**Comment by chris2deuce** [comment]
Please check with netstat command if port 25 is used by another MTA

# netstat -tulpena | grep 25

**Comment by ghost** [comment]
~~Where can I find netstat? (I run Ubuntu)~~ Found

**Comment by shiz0** [comment]
You ignored the template when opening the issue. PLEASE DON'T DO THAT.
Also, this is a bug tracker, please do not use it for support questions.
Use the appropriate channels for that: Telegram: https://t.me/mailcow or the board: https://community.mailcow.email/
Thanks for understanding.
Closing.

**Comment by ghost** [comment]
Sorry.

**Comment by ghost** [comment]
BTW: Changing the port didn't work, I think I'll register in the forum.
