### ISSUE TITLE
How to Reset stats in RSpamd. 

### ISSUE THREAD

**Issue by nrajivvarma** [mailcow/mailcow-dockerized#3665]
Hi,

I have moved my mailcow to new server. 
Want to reset Rspamd like it is was new. 

Also, how to prevent emails going into spam in gmail.

**Comment by MAGICCC** [comment]
See here how to reset learned data: https://mailcow.github.io/mailcow-dockerized-docs/u_e-rspamd/#reset-learned-data-bayes-neural

Also for your GMail problem:
Be sure SPF and all the other stuff is fine and working. If everything is fine then gmail is the problem, they tend to mark mails to mark as spam and nobody know why - like for Microsoft :/

**Comment by MAGICCC** [comment]
Also closed due to GitHub not being a support channel.
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
