### ISSUE TITLE
Goto says invalid address (but it's valid)

### ISSUE THREAD

**Issue by gdelbergue** [mailcow/mailcow-dockerized#3667]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When I try to create an alias with a Goto valid address, I get a Goto address invalid error whereas email is valid and working : 

`aws+topic-sales-customer-345-4rt0poi4vtl0sqgfk0a2gfb7l-ticket@example.com`

I guess the issue is related to email length.

**Docker container logs of affected containers**:

Nothing relevant.

**Reproduction of said bug**:

![Screenshot 2020-07-19 at 17 37 30](https://user-images.githubusercontent.com/4040959/87878750-86d52c80-c9e6-11ea-8e99-4873e3c78b03.png)

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 4 CPUs |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.0 |
| Reverse proxy (custom solution) | No custom solution |

**Comment by andryyy** [comment]
Hi,

I can create `aws+topic-sales-customer-345-4rt0poi4vtl0sqgfk0a2gfb7l-ticket@example.com`.

![image](https://user-images.githubusercontent.com/2972950/87909750-1de2c880-ca69-11ea-93f6-b00a9960316f.png)

Can you help me reproduce it? :-)

You may also try another browser, just for testing...

**Comment by gdelbergue** [comment]
> Hi,
> 
> I can create `aws+topic-sales-customer-345-4rt0poi4vtl0sqgfk0a2gfb7l-ticket@example.com`.
> 
> ![image](https://user-images.githubusercontent.com/2972950/87909750-1de2c880-ca69-11ea-93f6-b00a9960316f.png)
> 
> Can you help me reproduce it? :-)
> 
> You may also try another browser, just for testing...

Hi @andryyy,

Here is one not working : `aws+topic-sales-customer-very-long-345-4rt0poi4vtl0sqgfk0a2gfb7l-ticket@example.com`

A bad copy/paste/replace.

Thanks

**Comment by gdelbergue** [comment]
@andryyy I don't think we should close this issue, I can reproduce the issue.
