### ISSUE TITLE
Circular DNS dependency between nginx and rspamd

### ISSUE THREAD

**Issue by monsterry** [mailcow/mailcow-dockerized#3668]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

The nginx and rspamd containers have a circular DNS dependency as they access their counterpart via the respective docker DNS name. Docker uses a linear spawning and dependency mechanism, where the containers name is inserted into DNS when the container startet successfully.  At the moment this bug is mitigated via the restart policy of nginx. If you override the restart policy, nginx cannot be started successfully because rspamd is created after nginx:

**Docker container logs of affected containers**:

```
Attaching to a_nginx-mailcow_1
nginx-mailcow_1      | 2020/07/21 13:08:42 [emerg] 14#14: host not found in upstream "rspamd" in /etc/nginx/conf.d/includes/site-defaults.conf:102
nginx-mailcow_1      | nginx: [emerg] host not found in upstream "rspamd" in /etc/nginx/conf.d/includes/site-defaults.conf:102
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Reproduction of said bug**:

Override nginx restart policy:
```
   nginx-mailcow:
      restart: "no"
```
**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB / 4 vCPU  |
| Docker Version (`docker version`) | CE 19.03.12  |
| Docker-Compose Version (`docker-compose version`) | 1.26.0, build d4451659 |
| Reverse proxy (custom solution) | I no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by dragoangel** [comment]
Doesn't have issues with this. Restart on containers if normal practice. If this container was build on haproxy - there is option available to not fail on dns resolving and try resolve it later. On nginx I not see such option. Your resolution to configure nginx to wait for rspamd or to insert in config IP?

**Comment by andryyy** [comment]
I think I know what they mean and will check it. :) I am moving atm and have very limited time, sorry. :(
