### ISSUE TITLE
Outlook und SSL

### ISSUE THREAD

**Issue by Moepchi** [mailcow/mailcow-dockerized#367]
Hi, hab 2 Probleme.
1) Die Verbindung von Outlook über SMTP funktioniert nicht. Der Port 587 ist frei. Muss man vorher noch was einstellen, bevor das funktioniert? Über IMAP klappt die Verbindung.

2) Ich hab ein eigenes SSL Zertifikat für meine Domain. Gibt es eine Möglichkeit dies zu nutzen, da ich das per LetsEncrypt nicht benötige?

**Comment by omittedcoder** [comment]
Hallo @Assassins88,

Für das 1. Problem bräuchte ich mehr informationen:
- Kannst du emails über IMAP empfangen?
- Welche Einstellungen hast du in deinem Client(Outlook)?
- Wie und Wo hostest du mailcow?

Und für das 2. kannst du hier vorbei schauen: [firststeps-ssl](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/)
Also einfach dein Zertifikat und Key in _data/assets/ssl_ kopieren und in cert.pem und key.pem umbennenen

An sich wenn du die [Dokumentation](https://mailcow.github.io/mailcow-dockerized-docs/) noch nicht gelesen hast, kann ich dir das nur empfehlen. In Englisch, aber dafür sehr ausführlich.

**Außerdem ist es zwar schön das du Deutsch kannst, aber versucht bitte in Englisch zu schreiben, damit dich auch mehr Leute verstehen können.**

**Comment by andryyy** [comment]
Vermutlich fehlt da nur das TLS? =>
![image](https://user-images.githubusercontent.com/2972950/27255244-b4b0acda-539a-11e7-8fde-a8a415003c4e.png)

**Comment by Moepchi** [comment]
@P0ly 

1. Ja, dass geht
2. SMTP auf Port 587 mit TLS. SMPT Erfordert Authentifizierung und als Domainadresse die gleiche wie beim Eingangsserver
3. Bei mir aufm Root

Ja, die Doku kenne ich und ausführlich finde ich die jetzt nicht unbedingt. Ich werd das aber mal versuchen wie du das schreibst.

@andryyy 

Ist so eingestellt in Outlook

**Comment by andryyy** [comment]
Und die Postfix Logs?

**Comment by Moepchi** [comment]
@andryyy 

https://hastebin.com/ozifaretob.swift

**Comment by andryyy** [comment]
Laut Logs verbindest du dich auf Port 25.

**Comment by Moepchi** [comment]
@andryyy 

Das ist definitiv nicht der Fall. Ich bin mir zu 100% sicher, dass ich bei Outlook 587 auf TLS angegeben hab und hab es gerade noch mal versucht mit den Einstellungen und das ist das Log davon:

https://hastebin.com/afawamihel.swift

Und wie gesagt. Es ist zu 100% 587 als Port mit TLS in Outlook eingestellt.

**Comment by andryyy** [comment]
Ich kann dir nicht helfen, wenn ich dort keinen Verbindungsversuch auf Port 587 sehe.

Kannst du noch einmal die Logs pasten? Habe mich mit Telnet verbunden.

**Comment by Moepchi** [comment]
@andryyy 

Wie mit Telnet verbunden?

@P0ly

Läuft mit den Zertifikaten. :)

**Comment by omittedcoder** [comment]
@andryyy will einfach nur testen, ob man eine Verbindung zu dem Port aufbauen kann.
Das würde man dann in den Logs sehen.

**Comment by Braintelligence** [comment]
Sorry für den Offtopic, aber:
Ist es eigentlich ok hier auf Deutsch zu schreiben?
Wenn ein Englischsprachiger ein ähnliches Problem hat, wird er mit dem Issue hier wahrscheinlich nichts anfangen können :(.

Soweit ich weiß soll GitHub eine rein englischsprachige Plattform sein:
https://github.com/blog/679-github-in-your-language (siehe Update)

**Comment by omittedcoder** [comment]
@Braintelligence Das habe ich auch schon bereits erwähnt, aber für @andryyy scheint das ok zu sein.
Zumal ich glaube das @Assassins88 ein spezielles Problem hat, welches nur Ihn betrifft.

**Comment by Moepchi** [comment]
@P0ly vermute ich auch mal, dass das Problem nur mich betrifft. Hab jetzt noch mal geschaut ob der Port auch wirklich offen ist und er ist es. Also muss auf dem Port auf jeden Fall was reingehen also muss es an der Config von irgendwas liegen.

Ich hab da auch schon ne Idee, was es sein könnte, kann nur gerade nicht schauen, da ich nicht daheim bin.
