### ISSUE TITLE
Moved email not reflected in GUI

### ISSUE THREAD

**Issue by jetkins** [mailcow/mailcow-dockerized#3673]
I followed the suggestions found in [this thread](https://github.com/mailcow/mailcow-dockerized/issues/865) to rename a mailbox.  All appears well from the user's end - he can log in with the new name and see all the previous mail.  However, the Mailcow admin GUI still shows the mail count and quota usage under the old account.  Is there an easy way to resolve this, or would it be easier to put things back to how they were and use something like imapsync to move the mails over?

**Comment by JonasPed1** [comment]
You might need to run below command:
```docker-compose exec dovecot-mailcow doveadm quota recalc -A```

**Comment by jetkins** [comment]
That appears to have done the trick.  Thanks!
