### ISSUE TITLE
update.sh - line 424 (iptables)

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3674]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Today i started an update with update.sh. After the "Checking for conflicting bridges..." i get the line:
update.sh: line 424: iptables: command not found

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 20 GB, 4 |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |

A simple change from "iptables" to "/usr/sbin/iptables" would maybe fix the problem. But when i want to change that, update.sh every times update his code to the "iptables" version.

**Comment by andryyy** [comment]
Why is /usr/sbin/iptables not in your path?

If you use sudo, use roots env.

**Comment by tobias992** [comment]
Hi,
sorry but i dont know what you mean. Updates i do in SU Mode. When i use only iptables command then i get "command not found". I have to use "/usr/sbin/iptables" - then all is working fine.

**Comment by andryyy** [comment]
How do you switch to su? It is missing the /usr/sbin path in the $PATH.

**Comment by tobias992** [comment]
After login with normal User account i switch to SU easy with "su" - then type in the password - finish.

**Comment by andryyy** [comment]
Probably related: https://unix.stackexchange.com/questions/466373/setting-the-root-path-for-su

Does it work with --login?

**Comment by tobias992** [comment]
"su --login" - works fine. Thank you.
