### ISSUE TITLE
php-fpm - Warning - pspell.so

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3675]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Today i started an update with update.sh. After checking some logs i found some PHP Warnings in php-fpm-mailcow.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 20 GB, 4 |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |

**docker-compose logs php-fpm-mailcow**:
`php-fpm-mailcow_1    | PHP Warning:  PHP Startup: Unable to load dynamic library 'pspell.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so (Error loading shared library libaspell.so.15: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so.so: No such file or directory)) in Unknown on line 0`
`php-fpm-mailcow_1    | Fixed _sogo_static_view`
`php-fpm-mailcow_1    | Cleaned up memcached`
`php-fpm-mailcow_1    | Rebuilding domain map in Redis...`
`php-fpm-mailcow_1    | [25-Jul-2020 01:37:55] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'pspell.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so (Error loading shared library libaspell.so.15: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so.so: No such file or directory)) in Unknown on line 0`

**Comment by heldernunes** [comment]
seems like you have the extension twice
library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/pspell.so.so
