### ISSUE TITLE
Quota (doch nicht) wertlos

### ISSUE THREAD

**Issue by flo1212** [mailcow/mailcow-dockerized#3676]
Sorry. Mein Fehler

**Comment by Braintelligence** [comment]
Nur zum Verständnis: Ist das ein Duplikat von https://github.com/mailcow/mailcow-dockerized/issues/71#issuecomment-478268829 ?

EDIT: Nevermind <_>.

**Comment by flo1212** [comment]
Bitte löschen.

**Comment by Adorfer** [comment]
Wäre ja schon praktisch nachzuvollziehen, was das schiefgelaufen ist. Könnte ja die Doku verbessern. Aber dann halt nicht.

**Comment by flo1212** [comment]
Hallo!

es ging darum das ein Domain-Administratror unlimted Quota-mailboxen anlegen konnte, obwohl dies gem,äß der ACLs verboten ist.
Das war fatal, denn dann kann ein Endkunde einfach jegliches Quoto umgehen.

Wir haben fegestellt, das dies nur geht, wenn man sich als Server-Administrator umloggt in einen Domain-Administrator.
Wenn man sich direkt als Domain-Administratror einloggt wirken die ACLs.

Warum das so ist, das man mehr Rechte hat, sobald man sich als Server-Administrator in einem Domain-Administrator innerhlab der GUI umloggt, kann ich nicht ganz nachvollziehen. Vielloeicht ist es ein Bug oder so gewollt?
Auf jeden Fall hat dies für erhebliche Irretationen gesorgt.

-- 
Mit freundlichen Grüßen
Uwe Flottemesch




am Dienstag, 28. Juli 2020 um 13:45 schrieben Sie:


Wäre ja schon praktisch nachzuvollziehen, was das schiefgelaufen ist. Könnte ja die Doku verbessern. Aber dann halt nicht.
