### ISSUE TITLE
postfix cant connect to ips

### ISSUE THREAD

**Issue by eliteSchwein** [mailcow/mailcow-dockerized#3688]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Postfix gets the ip from the mail hoster, but cant route to the ip
i cant receive any email or sent....

**Docker container logs of affected containers**:

postfix-mailcow_1    | 2020-08-01T20:18:29.548112825Z Aug  1 22:18:29 mail postfix/smtp[469]: connect to mx-ha02.web.de[212.227.17.8]:25: No route to host
postfix-mailcow_1    | 2020-08-01T20:18:29.549080035Z Aug  1 22:18:29 mail postfix/smtp[469]: 6B6C96A0DEF: to=<cubier.crafter@web.de>, relay=none, delay=7969, delays=7964/0.02/4.8/0, dsn=4.4.1, status=deferred (connect to mx-ha02.web.de[212.227.17.8]:25: No route to host)

**Reproduction of said bug**:
not sure how...

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | ufw is active |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4096MB,4Cores |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | nginx |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by eliteSchwein** [comment]
i have also 2 networks, 1 with a public ip and 1 for the internal network

**Comment by dragoangel** [comment]
Hi @eliteSchwein, did you:
1. set correct `SNAT_TO_SOURCE` in `mailcow.conf`?
2. tried to temporary 1) `ufw disable` and 2) `docker-compose down` 3) `systemctl restart docker` 4) `docker-compose up -d` to exclude ufw miss configuration case

To note right in template of issue you was been asked to provide `iptables` output, without it impossible to tell anything. Also you can get help in telegram community more quickly maybe.

**Comment by eliteSchwein** [comment]
I fixed it somehow, i cant detail how
