### ISSUE TITLE
Lets Encrypt Certificate more 100 records error

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#3689]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
I had some new domains to my mailcow, so I have a problem to generate new certificates for those domains, when I list logs I have those errors : 

**Docker container logs of affected containers**:
```
Aug  3 08:40:38 localhost.localdomain docker/mailcowdockerized_acme-mailcow_1/5c5e7eea3852[30599]: Response Code: 400
Aug  3 08:40:38 localhost.localdomain docker/mailcowdockerized_acme-mailcow_1/5c5e7eea3852[30599]: Response: {'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Error creating new order :: Order cannot contain more than 100 DNS names', 'status': 400}
```

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** |KVM |
| Server/VM specifications (Memory, CPU Cores) | 4 |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | None |

Regards

**Comment by guidtz** [comment]
NB : do I need autoconfig and autodiscover ssl ?

```
ADDITIONAL_SAN=imap.*,smtp.*,webmail.*,mail.*,autodiscover.*,autoconfig.*
```

**Comment by mkuron** [comment]
> do I need autoconfig and autodiscover ssl ?

You need them for automatic account setup on Outlook and Thunderbird and for Exchange ActiveSync.

> Order cannot contain more than 100 DNS names

I thought we fixed that a while ago, but maybe it doesn’t take into account `ADDITIONAL_SAN`? Or did you forget to set `ENABLE_SSL_SNI=y` in mailcow.conf?

**Comment by guidtz** [comment]
Ok I haven't seen this configuration before. I set ENABLE_SSL_SNI to y and now It seems to work

**Comment by patschi** [comment]
> Ok I haven't seen this configuration before. I set ENABLE_SSL_SNI to y and now It seems to work

Please notice not all email clients are supporting SNI: see https://wiki.dovecot.org/SSL/SNIClientSupport.

> ```
> Aug  3 08:40:38 localhost.localdomain docker/mailcowdockerized_acme-mailcow_1/5c5e7eea3852[30599]: Response Code: 400
> Aug  3 08:40:38 localhost.localdomain docker/mailcowdockerized_acme-mailcow_1/5c5e7eea3852[30599]: Response: {'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Error creating new order :: Order cannot contain more than 100 DNS names', 'status': 400}
> ```

There's also a page in the documentation you could have read: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#the-lets-encrypt-subjectaltname-limit-of-100-domains

**Comment by guidtz** [comment]
Ok I understand ! 
So with this configuration Postfix not have SAN Certificate like it specified in documentation? For the Postfix certificate I have only one domain in it those wich is referenced in MAILCOW_HOSTNAME
