### ISSUE TITLE
Add mail deeplink to pushover notifications

### ISSUE THREAD

**Issue by protree** [mailcow/mailcow-dockerized#3693]
**Is your feature request related to a problem? Please describe.**
I really like the pushover api integration, but to get to the mail after receiving  the push notification you have to open the mail app manually (e.g. on iOS).

**Describe the solution you'd like**
The pushover api allows to set a „url“ that can be sent together with the notification. iOS allows deep links to the mail app in the format „message://messageID“. In combination this can be used to open new mails by opening the push message. I don‘t know how android behaves, but it may be similar.

It would be really nice if there would be an „URL“ field to mailcow‘s pushover-api GUI to set URL Scheme + a var for messageID like the ones for {SUBJECT} and {SENDER} to be able to set up deep links for the mail app.

**Additional context**
Further reading: https://medium.com/@vijaysundaram/how-to-deep-link-to-ios-7-mail-6c212bc79bd9

**Comment by mkuron** [comment]
That blog post says

> The only requirement for this to work as advertised is that the target email must be downloaded and available in Mail.

So if you tap the deep link right when you get the notification, it won‘t work. You would need to wait until Mail.app‘s next sync, which even at the shortest interval could be 15 minutes away.

I agree, this feature sounds useful, but it‘s probably going to be quite frustrating in practice.

**Comment by protree** [comment]
You would at least get straight to the Mail App, which would still be faster than open it manually. I tested this with custom push messages that just had „message://test“ as URL.

EDIT: Found another Post that claims something different:

„ If you open a message: URL on iOS and the linked message is readily accessible from the inbox of one of your accounts, Mail will launch immediately to that message. If the message isn’t found, the app will launch and asynchronously load the message in the background, opening it once it’s available.“


https://nshipster.com/message-id/

**Comment by dragoangel** [comment]
If this behavior in Android not same then this future will also be strange.

**Comment by protree** [comment]
> 
> 
> If this behavior in Android not same then this future will also be strange.

Not if the user can configure url scheme to match his/her Operating system's scheme... Would be quite universal.

**Comment by andryyy** [comment]
Or... fiddly.
I would implement a universal solution.
