### ISSUE TITLE
CSS / Javascript not working with reverse proxy.

### ISSUE THREAD

**Issue by DavidPHH** [mailcow/mailcow-dockerized#3699]
My goal with this reverse proxy is for `mywebsite.com` to go to `myip:3000` and `mywebsite.com/mail/` to go to `myip:8080/admin`

I got this from https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#nginx and edited it to look like this

```nginx
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name mail.mywebsite.com autodiscover.* autoconfig.*; 
  return 301 https://$host$request_uri;                                                          
}
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name mail.mywebsite.com autodiscover.* autoconfig.*;                                                                                                                                 
  ssl_certificate /opt/mailcow-dockerized/data/assets/ssl/cert.pem;
  ssl_certificate_key /opt/mailcow-dockerized/data/assets/ssl/key.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;

  # See https://ssl-config.mozilla.org/#server=nginx for the latest ssl settings recommendations
  # An example config is given below
  ssl_protocols TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5:!SHA1:!kRSA;
  ssl_prefer_server_ciphers off;

  location /Microsoft-Server-ActiveSync {
    proxy_pass http://myip:8080/Microsoft-Server-ActiveSync;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 75;
    proxy_send_timeout 3650;
    proxy_read_timeout 3650;
    proxy_buffers 64 256k;
    client_body_buffer_size 512k;
    client_max_body_size 0;
  }

 location /mail {
    proxy_pass http://myip:8080/;                                                          
    proxy_set_header Host $http_host;                                                               
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;                                                      
    client_max_body_size 0;                                                                       
 }
 location / {
    proxy_pass http://myip:3000/;
}
````

When i go to `mywebsite.com`  it shows my app that's running on port 3000 fine, but when I go to `mywebsite.com/mail/` it seems all the mailcow css and javascript are missing? this is what I see https://i.imgur.com/N4HhDkq.png

I'm very new at this and I've spent a lot of time reading up on nginx and other issues trying to set this up, before giving up and coming here to ask for help. Almost all the issues I've read of similar questions here eventually lead me to #393.

I've managed to do what that issue wanted of swapping SOgo and admin, but trying anything else to change the directory I always end up with the missing css problem.<br>
Any help would be greatly appreciated, please.

**Comment by asifbacchus** [comment]
Change your location directive to:

```nginx
location ^~ /mail/ {
    ...
}
```

That should work.

**Comment by DavidPHH** [comment]
Hi, thank you for the reply. I changed it to that and still the same problem of no css.

**Comment by asifbacchus** [comment]
Just looking at your NGINX config, this setup is for *mail.mywebsite.com* and not for *mywebsite.com/mail*. I'm assuming this is a typo? If not, then are you having this problem when you actually visit *mail.mywebsite.com/mail*?
