### ISSUE TITLE
Alias receipt not working

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [mailcow/mailcow-dockerized#3700]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

I created an alias (info@test.de) for the mailbox person1@test.de. Sending from the Mailbox as the alias works fine, but i am not receiving any mails sent to info@test.de.

**Docker container logs of affected containers**:

There are no errors or warnings in the logs.

**Reproduction of said bug**:

I created another alias on the same mailbox. Same problem.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian GNU/Linux 9 (stretch) |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM i think |
| Server/VM specifications (Memory, CPU Cores) | 32GB RAM, 10 CPU Cores |
| Docker Version (`docker version`) | Docker version 19.03.12, build 48a66213fe|
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.26.2, build eefe0d31|
| Reverse proxy (custom solution) | None|

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
diff --git a/data/conf/nginx/site.conf b/data/conf/nginx/site.conf
index d6e6b136..48108b97 100644
--- a/data/conf/nginx/site.conf
+++ b/data/conf/nginx/site.conf
@@ -1,3 +1,11 @@
+server {
+  listen 80 default_server;
+  listen [::]:80 default_server;
+  include /etc/nginx/conf.d/server_name.active;
+  if ( $request_uri ~* "%0A|%0D" ) { return 403; }
+  return 301 https://$host$uri$is_args$args;
+}
+
 server_tokens off;
 proxy_cache_path /tmp levels=1:2 keys_zone=sogo:10m inactive=24h  max_size=1g;
 server_names_hash_bucket_size 64;

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
151.101.65.69
151.101.193.69
151.101.129.69
151.101.1.69

**Comment by andryyy** [comment]
Can't reproduce. Receiving works just fine.
You may want to post logs when you receive mail to the Telegram channel.
