### ISSUE TITLE
Need some help with email client Outlook from a Microsoft 365 subscription

### ISSUE THREAD

**Issue by ovizii** [mailcow/mailcow-dockerized#3701]
Basically, this how-to is no longer up to date as far as I can see: https://mailcow.github.io/mailcow-dockerized-docs/client/client-outlook/ 

I open Outlook, enter my email address, click next and then I can select the type of account. Neither Exchange nor Exchange 2013 or earlier work, both times I see the error "something went wrong" setting it up manually obviously works. 

If I visit my mailcow admin dashboard and go to configuration => mail setup then check the DNS, all those setting have a green check mark.

What could I be missing?

![image](https://user-images.githubusercontent.com/837902/89769653-c54d9b00-dafd-11ea-8bb8-9a6a9b989f7e.png)

![image](https://user-images.githubusercontent.com/837902/89769725-edd59500-dafd-11ea-8a5f-536511e406a0.png)

**Comment by Adorfer** [comment]
this is a bug issue tracker, not support (-forum)

**Comment by ovizii** [comment]
> this is a bug issue tracker, not support (-forum)

Sorry about that, I really did not find the community forum before posting here :-(
