### ISSUE TITLE
Question about adding multiple domains to a mailcow instance

### ISSUE THREAD

**Issue by ovizii** [mailcow/mailcow-dockerized#3702]
I have mailcow running fine, currently only setup with 1 domain, the same one that is used for the mailcow-hostname and everything. All DNS records setup and showing green in the mailcow dashboard at configuration => mail setup => DNS  (i.e. maindomain.tld)

Now I am just curious, if i add additional domains (i.e. clientdomain.tld) and also setup all DNS records from A-record to MX to every single record shown, how will clients access this mailcow instance? 

should they still use maindomain.tld for accessing sogo, smtp/pop3/imap, their mailcow dashboards or clientdomain.tld? 

sorry if this has been asked but I couldn't find an answer as the question seems to generic :-/

**Comment by mkuron** [comment]
> should they still use maindomain.tld for accessing sogo, smtp/pop3/imap, their mailcow dashboards or clientdomain.tld?

All domains will use whatever you configured as $MAILCOW_HOSTNAME in mailcow.conf. #528 was a feature request to allow using a different host name for each domain, but that is not a fully supported configuration.

**Comment by asifbacchus** [comment]
I have a setup very similar to this for several domains where they can go to webmail.clientdomain.tld and be redirected to mailcow.maindomain.tld. However, it is only possible (as far as I know) if you are running a reverse proxy in front of your mailcow containers. If that's the case, and you need help with your config, let me know. Maybe private message to avoid polluting the thread. Cheers.

**Comment by ovizii** [comment]
Thanks for clarifying, I am happy with the default behavior described above, I just wanted to make sure what the default is. 

So if I get this right additional domains don't even have to point say mail.clientdomain.tld to this mailcow instance, I can simply set the mx of all domains to $MAILCOW_HOSTNAME and be done with it? Same for autodiscover|autoconfig.clientdomain.tld pointing towards $MAILCOW_HOSTNAME I guess?

**Comment by asifbacchus** [comment]
Yup. Use a cname for autodiscover/autoconfig and map it your mailcow hostname. MX points directly to mailcow also. For example:

```dns
autodiscover.clientdomain.tld IN CNAME mailcow.maindomain.tld
autoconfig.clientdomain.tld IN CNAME mailcow.maindomain.tld
@ IN MX 10 mailcow.maindomain.tld
```

HTH

**Comment by dragoangel** [comment]
@ovizii yes, cname is best way to go. Please use DNS check tool under Domains tab in Mailcow admin UI, or ask help in telegram or community forum. Docs are good to read also. GitHub isn't best place for asking confirmation support.

**Comment by ovizii** [comment]
Sorry about that, I didn't even know about the community forum but now that you mentioned it I found it and will definitely use that for this type of questions: https://community.mailcow.email/
