### ISSUE TITLE
enoded/rotated mail address in Hint text with ROT13

### ISSUE THREAD

**Issue by CookieCr2nk** [mailcow/mailcow-dockerized#3706]
**Is your feature request related to a problem? Please describe.**
No, its a nice to have feature, but this feature was already implementet in the footer

**Describe the solution you'd like**
That mail addresses enoded/rotated with ROT13 in the Hint text

**Comment by andryyy** [comment]
Hi,

Where exactly? The info box? :)

**Comment by CookieCr2nk** [comment]
I mean the Alert Box on the Login Screen <img width="1160" alt="Mo7prFjMJij27Z7" src="https://user-images.githubusercontent.com/38990807/90331586-04746400-dfb6-11ea-8ae5-30d4b37c7037.png">

**Comment by andryyy** [comment]
The announcement box?

**Comment by CookieCr2nk** [comment]
Yes, exactly.

**Comment by andryyy** [comment]
Implemented with d3d929222f1d328d253660da1e45e0dd7cf1b460
