### ISSUE TITLE
Only FQDN gets SSL after Nginx Reverse Proxy

### ISSUE THREAD

**Issue by HDS-Admin** [mailcow/mailcow-dockerized#3707]
I followed the guide for setting up a reverse proxy with nginx.  Everything seems to work except now all domains other than that FQDN do not have ssl.   Firefox warning says its and HSTS issue.    I checked the nginx confs and tried adding the other server names in where i thought appropriate but not luck also restarted the stack multiple times after making changes.  

Just need someone to point me in the right direction please.

**Comment by andryyy** [comment]
Please read the read the issue template. The bug tracker is not meant for support. :) Thanks.
