### ISSUE TITLE
SOGo email forwarding

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#371]
If I create a brand new email account and set up email forwarding in SOGo then it works without a problem.

If I import a a lot of email from a Cyrus IMAP server using [this script](https://github.com/a-schild/cyrus2dovecot) and then add SOGo forwarding to an account with a lot of imported email it doesn't work, the email simply stays on the server and isn't forwarded.

How exactly does SOGo email forwarding work? Could it be that the imported data somehow prevents forwarding rules being properly created or something? Any suggestions how I could debug this?

**Comment by chriscroome** [comment]
The answer is to delete and then recreate the SOGo filter -- the sieve file hadn't been created for some reason, even though in the SOGo web interface it looked like it had been, but after it has been removed and recreated then it does exist.

I don't know if this issue worth keeping open as there is an issue with SOGo, you shouldn't have to create a forward and then delete it and then recreate it for it to exist...?

**Comment by omittedcoder** [comment]
Hello @chriscroome,
you can commit a bug report on [https://sogo.nu/bugs](https://sogo.nu/bugs).

**Comment by chriscroome** [comment]
Thanks @P0ly but I now think I caused this problem myself, the wrapper script I wrote to run the [cyrus2dovecot](https://github.com/a-schild/cyrus2dovecot) script was deleting the sieve file, sorry for the noise.
