### ISSUE TITLE
iOS Profile does not work with App Passwords

### ISSUE THREAD

**Issue by pahy** [mailcow/mailcow-dockerized#3710]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When using app-passwords and installing a profile including mail and cal/carddav on an ios-device, the app-password is only accepted when entered at mail. it is not accepted, when entering at cal/carddav. there it must be the original account-password.

**Docker container logs of affected containers**:

**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | iOS 13.6.1 |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/90502001-821ea800-e14d-11ea-9bd0-7f1934938ab3.png)

**Comment by pahy** [comment]
Better as feature request? #3711

**Comment by mkuron** [comment]
This cannot be fixed by Mailcow alone as this is a limitation of SOGo. Wrapping https://github.com/inverse-inc/sogo/blob/f0980a9cbd14e0fab163be71e4e260bde67d7ee9/SoObjects/SOGo/SQLSource.m#L303-L306 into a loop would probably do it. The same problem was discussed in https://github.com/mailcow/mailcow-dockerized/issues/740#issuecomment-562106958.
