### ISSUE TITLE
[SOGo] Cannot reply or transfer some emails

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3719]
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Hi,

SOGo 5.0.0 introduced a bug where we cannot reply or transfer some emails received from various senders. I opened [a bug report upstream](https://sogo.nu/bugs/view.php?id=5142) but as we'll need to update the SOGo image in Mailcow I think a report here is appropriate too.

**Docker container logs of affected containers**:

Here is the logs from sogod when we try to reply:

```
[119]: XXX.YYY.AAA.BBB "GET /SOGo/so/REDACTED@some.domain/Mail/UIxMailEditor HTTP/1.0" 200 3265/0 0.007 15295 78% 0 - 13
10:07:32.706 sogod[113:113] EXCEPTION: <NSException: 0x56433a6eaa00> NAME:NSInvalidArgumentException REASON:[GSMutableString -compare:options:range:] nil string argument INFO:(null)
```

**Reproduction of said bug**:

1. Open the SOGo Mail panel
2. Find an email in the list
3. Open it, you can read it without problem
4. Click the reply icon
5. Nothing happens

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 2 vCPU, 8GiB RAM |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | No |

**Comment by andryyy** [comment]
Hi,

Can you post the dev console logs there, too? :)

**Comment by ghost** [comment]
> Can you post the dev console logs there, too? :)

Thank you for the suggestion, added to the bug report at sogo.nu

**Comment by ghost** [comment]
4 days and no answer from Inverse, are some Mailcow users impacted by this too?

**Comment by ghost** [comment]
Fixed by https://github.com/inverse-inc/sope/commit/579f73e6dec22f05f9e2a2e96f9d87e22b788419, we'll need to update the SOGo image to v5.0.1
