### ISSUE TITLE
Mailcow connect from unknown

### ISSUE THREAD

**Issue by philippkayser** [mailcow/mailcow-dockerized#3722]
In front of Mailcow we use Proxmox Mailgateway. The Domain relays to Mailcow but i just can see the following in logs

Mailcow:

26.8.2020, 00:58:47 | info | E25F544142: client=unknown[192.168.200.7]
-- | -- | --
26.8.2020, 00:58:47 | info | connect from unknown[192.168.200.7]
26.8.2020, 00:58:47 | info | WHITELISTED [192.168.200.7]:37762
26.8.2020, 00:58:47 | info | CONNECT from [192.168.200.7]:37762 to [172.22.1.8]:25

Proxmox:

queued/accepted
--

It will not relay anymore to Mailcow.

**Comment by Adorfer** [comment]
this is tue bug tracker, this is not the support forum.
