### ISSUE TITLE
Transport maps are not working

### ISSUE THREAD

**Issue by quartznets** [mailcow/mailcow-dockerized#3724]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Transport maps are not working

**Docker container logs of affected containers**:

There are no errors regarding relaying. There are no logs **at all** regarding relaying/transport!

**Reproduction of said bug**:

Whatever record I add, should it be `mailbox@mydomain.com` or `mydomain.com`, don't affect the email routing. I send a sample email to `mailbox@mydomain.com` which doesn't exist on my instance and should be routed to the MX server I set up in the transport map, it won't reroute the email and return the error to the sender.

I have also tried adding a record `.* error:test` to `data/conf/postfix/custom_transport.pcre` and restarting postfix, which also seem to be ignored, the email continue to work normally instead of returning a custom error to each received email.

There is also no mailcow documentation regarding transport maps that would describe a sample setup in details, so in case I am missing something there would be an answer.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian GNU/Linux 10 |
| Is Apparmor, SELinux or similar active? | Distribution's default settings |
| Virtualization technlogy | KVM |
| Server/VM specifications | 4 cores, 4gb ram |
| Docker Version  | 18.09.1 |
| Docker-Compose Version  | 1.26.2 |
| Reverse proxy (custom solution) | n/a |

**Comment by andryyy** [comment]
Looks good, actually.

Are you sure your transport map is active?

Please don't delete the issue template and post at least _some_ infos.

![image](https://user-images.githubusercontent.com/2972950/91399291-07851500-e83e-11ea-90f1-1c10cfe28ce2.png)

![image](https://user-images.githubusercontent.com/2972950/91399284-0227ca80-e83e-11ea-9063-e205c41a64a5.png)

**Comment by quartznets** [comment]
Yes it's active.

![Screenshot_2020-08-27_14-04-37](https://user-images.githubusercontent.com/69655801/91452925-b17c9580-e86e-11ea-879d-1ca3c4df548d.png)

In this case anything sent to the email boxes (existent and non-existent) don't get routed to `mx.zohomail.com`. Non existent accounts return 'User unknown in virtual mailbox table' and everything else goes normal.

Sorry I didn't post the template because I am using the default settings from a fresh mailcow container that was set up yesterday, so there are no deviations to highlight.

**Comment by andryyy** [comment]
We still need logs etc.

I do also use a plain mailcow to test. :)

Try `[mx.zohomail.com]:25` as next hop.

**Comment by quartznets** [comment]
Please remove the "invalid" tag as I edited the OP and inserted the template.

I can't find anything related to relaying in logs.

With the map active there is a normal protocol handshake happening without any relaying, when I send from Yandex to my MX, which is supposed to be relayed to Zoho.

```
postfix-mailcow_1    | Aug 31 04:08:59 mx whitelist_forwardinghosts: Look up 5.45.198.243 on whitelist, result 200 PERMIT
postfix-mailcow_1    | Aug 31 04:08:59 mx postfix/postscreen[348]: WHITELISTED [5.45.198.243]:34743
redis-mailcow_1      | 455:C 31 Aug 2020 03:50:03.342 * DB saved on disk
redis-mailcow_1      | 455:C 31 Aug 2020 03:50:03.342 * RDB: 4 MB of memory used by copy-on-write
postfix-mailcow_1    | Aug 31 04:09:00 mx postfix/smtpd[355]: connect from forward102j.mail.yandex.net[5.45.198.243]
postfix-mailcow_1    | Aug 31 04:09:00 mx postfix/smtpd[355]: Anonymous TLS connection established from forward102j.mail.yandex.net[5.45.198.243]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
redis-mailcow_1      | 1:M 31 Aug 2020 03:50:03.404 * Background saving terminated with success
postfix-mailcow_1    | Aug 31 04:09:00 mx postfix/trivial-rewrite[358]: warning: pcre map /opt/postfix/conf/custom_transport.pcre, line 1: no closing regexp delimiter ".": ignoring this rule
postfix-mailcow_1    | Aug 31 04:09:00 mx postfix/smtpd[355]: NOQUEUE: reject: RCPT from forward102j.mail.yandex.net[5.45.198.243]: 550 5.1.1 <*****.**@mydomain.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<*******@yandex.com> to=<*****.**@mydomain.com> proto=ESMTP helo=<forward102j.mail.yandex.net>
postfix-mailcow_1    | Aug 31 04:09:00 mx postfix/smtpd[355]: disconnect from forward102j.mail.yandex.net[5.45.198.243] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

 Everything I need is 1-2 users on the same domain to be relayed to zoho and everything else on the same domain to be received normally on my MX.

Also I don't understand why putting something like `.* error:test` to `/opt/mailcow-dockerized/data/conf/postfix/custom_transport.pcre` don't give any effect.

**Comment by quartznets** [comment]
Ok there were 2 problems:

1. I didn't know that .pcre files require perl-style regex delimiters, `/.*/ error:test` work for `custom_transport.pcre`

2. It's not very intuitive that accounts should exist in order to be relayed to other MX. According to this answer https://talk.plesk.com/threads/5-1-1-recipient-address-rejected-user-unknown-in-virtual-mailbox-table.341956/#post-820249 
**I was trying to relay non-existent accounts and it was the main reason why transport was not working.**
