### ISSUE TITLE
Frage: Aufbau yml Datei

### ISSUE THREAD

**Issue by KodaCHC** [mailcow/mailcow-dockerized#3726]
Hallo und Danke für diese tolle Software. Da ich auch wissen möchte was alles passiert beim Ausführen bin ich im Moment alles am anschauen. Schon sehr Interessant. Nun hätte ich aber eine Verständnisfrage.

Du verwendest z.B: in diesem Teil zwei Schreibweisen:
```
volumes:
        - mysql-vol-1:/var/lib/mysql/
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
```

Was ist hier der Unterschied mit "./" und ohne? Ist doch beides im "root" Verzeichnis vom Projekt.

Ich habe dazu auch in der Dockerhilfe https://docs.docker.com/compose/compose-file/#volume-configuration-reference nichts konkretes gesehen.

Koda

**Comment by patschi** [comment]
https://docs.docker.com/compose/compose-file/#volumes
`Mount host paths or named volumes, specified as sub-options to a service.`

- `mysql-vol-1` ist ein Docker Volume
- `./data/conf/mysql/` ein Mount Path am Host der in den Container gemountet wird.

Zudem: Wie bei der Erstellung angemerkt, sind GitHub Issues Bugtracker nur fuer Bugs. Fuer anderweitige Fragen gerne [im community forum](https://community.mailcow.email/) oder in der [Telegram Gruppe](https://t.me/mailcowOfftopic).
