### ISSUE TITLE
Mailcow Installation with small storage footprint

### ISSUE THREAD

**Issue by KarstenDE** [mailcow/mailcow-dockerized#3728]
**Is your feature request related to a problem? Please describe.**
I want to use Mailcow as a backup Mx server on a very small vps (10GB file storage). I already skipped SOLR, SOGO and clamAV. This helps me with the small RAM but the images are downloaded and containers get created.

**Describe the solution you'd like**
Skip the creation of the non-relevant containers (and not download the images)￼.

**Additional context**
Is this already possible with an easy config?
Sure I can remove them from the docket-compose file. But ...
- How does this work in case of a Mailcow update?￼
- Is there a reason why the containers gets created when they are not used (configured as skip)?

I use Mailcow at Ubuntu 20.04  
The small RAM is no problem (until now)

**Comment by patschi** [comment]
You should not disable clamav or rspamd on the BackupMX, as all mails going through the BackupMX are delivered without any further scanning to the Primary MX - including all spam mails and viruses. So, in the best case, rspamd configuration should be synced as well.

**Comment by KarstenDE** [comment]
@patschi That is a Good hint.
Therefore I just talk Solr for search and SOGo as Webmail and clamAV which does not run with small RAM anyway.

**Comment by patschi** [comment]
For both, SOGo and Solr, there's an option in the mailcow.conf to disable the services. The containers still run, but the actual application don't. This might help for your scenario.

**Comment by KarstenDE** [comment]
No this does not help me:

I used all options to disable/skip the named containers and this helps me for the small RAM. So Mailcow runs.

But my Problem is the consumption of file storage. The named containers are created and the images are downloaded. If I could delete the images it would be fine and enough disk storage would be free ...

**Comment by MAGICCC** [comment]
Theoretically you could remove some images from the compose file, but actually I am quite sure if they are somehow depended by other containers.
So the best thing would be to implement a solution that we can select some 'minimal' installation, but that would mean to support another thing.. (Changing some dependencies so they don't fail when a container is not present)

**Comment by KarstenDE** [comment]
That sounds awesome :-)

Minimal Setup is interesting, because it is already possible to *skip* this components and that works fine. So a more strict interpretation of this *skipping* would be very cool!

I already checked the compose file and saw such dependencies as you named. Between the containers it self and sometimes from containers to other volumes too.

Do you know if there are dependencies additionally to the compose file between the containers? Or in the applications itself?

Other idea:  
Would it be possible/helpful to use a "placeholder" image instead of the full size images in such a case? Then the containers are available but do not consume the full size.

**Comment by mkuron** [comment]
If you look at the skipped components‘ docker entrypoint scripts, you‘ll see that they do nothing when the variable is set to skip them. So you should be able to safely remove these components from docker-compose.yml. Or use an override file to set use a smaller image that does nothing.

**Comment by KarstenDE** [comment]
What happens exactly in the default config with the different components skipped?

Because especially without the Sogo container (not created) I get the following error
`nginx-mailcow_1      | ping: bad address 'sogo'`

Can the container be pinged in the default skipped configuration? I expact yes, because it is running ...

**Comment by KarstenDE** [comment]
With the SOGO Container created (and skipped) everything works :-)

**Comment by patschi** [comment]
I'm not sure how much demand and how beneficial it might be for the most users. But I get the benefit when disabling SOGo indeed. If you want to feel free to share your setup or how you solved this, in case someone else comes in similar situation! :)
