### ISSUE TITLE
Can't generate new API Key

### ISSUE THREAD

**Issue by firstdorsal** [mailcow/mailcow-dockerized#3731]
When generating a new API Key in the UI nothing returns aside from the popup that the API settings have changed.
Tried in Brave/Chromium and Firefox.

Mailcow is awesome! Keep it up!

**Comment by andryyy** [comment]
Hi,

Hm, I just tried and it worked fine. :/

Thank you. :)

Can anyone else try and replicate the issue? Perhaps @ntimo ?

**Comment by andryyy** [comment]
Did you activate the API first with the checkbox and saved the changes?

**Comment by firstdorsal** [comment]
that was the problem ^^
thank you!
some ideas:
i think this is not intuitive at all :p
shouldnt the api key only be visible the one time you generate it? and if you forget it only can be made visible through generating a new one.
it works like this for most applications like cloudflare etc.

**Comment by andryyy** [comment]
I will disable the button when no key exists. 

You cannot regenerate a key that not exists. :)

Edit: Fixed and will be pushed soon.
