### ISSUE TITLE
Enable 2FA for regular (mailbox) users in mailcow UI to be used by remote login

### ISSUE THREAD

**Issue by Gielovic** [mailcow/mailcow-dockerized#3736]
Currently running into the issue to use mailcow as a OAuth2 provider for a Nextcloud instance as documented (https://mailcow.github.io/mailcow-dockerized-docs/third_party-nextcloud/). However, the oauth login bypasses 2FA from Nextcloud, and I'm unable to add 2FA to the mailcow (regular) user logon. 

Having the option to do the latter would eliminate the (forced) choice between auth-integration and security.

**Comment by dragoangel** [comment]
Blocked by #3698
Related to #1348

In short:
SOGo now have not enough secure working 2FA, after they fix some gaps - mailcow can try reuse SOGo 2FA secret for usual user login.
But want to note that 2FA for usual user will not protect:
- IMAP/POP3/SMTP
- CalDAV & CardDAV
- Exchange ActiveSync
- Sieve

So in result it now protect:
- SOGo UI but nothing that SOGo actually provide

So in result if mailcow implement SOGo 2FA inside mailcow UI, it will protect:
- Same SOGo UI without any protection
- mailcow OAuth
- mailcow User settings

P.S.:
Maybe mailcow AppPassword can have option to set SOGo password once to not same as mailcow User password, so mailcow User password will be not same as needed to access SOGo\EAS\CalDAV\CardDAV, but this looks little paranoid.

**Comment by cjohn001** [comment]
Hello @Gielovic, I am currently running into the same problem. I configured oauth for nextcloud login as well and the 2fa option for my default users was gone (for admin still possible). I delete the oauth client in mailcow but could not get the 2fa option back for default users. Have you found a way to achive this?

**Comment by dragoangel** [comment]
Hi @cjohn001, not have nextcloud right now to test this and help you, sorry

**Comment by cjohn001** [comment]
@dragoangel thanks for your answer

**Comment by Gielovic** [comment]
@dragoangel 

Thanks for the extensive reply, sorry for my late one.
I agree on the fact that it will not provide that much additional protection when it comes to the e-mail/cal/exchange as itself. The added benefit will mainly be experienced in providing additional protection when authenticating for external application using the OAuth option.

As 2FA is available for admin users, I guessed re-using that functionality for default users would be possible (instead of using the SOGO option).

**Comment by dragoangel** [comment]
@Gielovic the point is to not create many mfa per user to not create confusion, I think you understand what I mean.
