### ISSUE TITLE
mailq API endpoint returns empty JSON object

### ISSUE THREAD

**Issue by j6s** [mailcow/mailcow-dockerized#3738]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When using the API, the `/api/v1/get/mailq/all` endpoint returns an empty object `{}` instead of an empty array `[]` if there are no queued items.

**Docker container logs of affected containers**:

n/a

**Reproduction of said bug**:

Accessing the `/api/v1/get/mail1/all` endpoint when there are queued items:

```bash
$ curl 'https://mail.domain.tld/api/v1/get/mailq/all' -H 'X-Api-Key: YOUR-API-KEY-HERE'
[
  {
    "queue_name": "deferred",
    "queue_id": "0E348C0104",
    "arrival_time": 1599158539,
    "message_size": 22076,
    "sender": "foo@mail.domain.tld",
    "recipients": [
      "..."
    ]
  }
]
```
Accessing the `/api/v1/get/mail1/all` endpoint when there are no queued items:

```bash
$ curl 'https://mail.domain.tld/api/v1/get/mailq/all' -H 'X-Api-Key: YOUR-API-KEY-HERE'
{}
```

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Not sure what exactly my provider uses for the vservers |
| Server/VM specifications (Memory, CPU Cores) | 2 cores, 4GB RAM |
| Docker Version (`docker version`) | `19.03.12` |
| Docker-Compose Version (`docker-compose version`) | `1.24.1` |
| Reverse proxy (custom solution) | nginx |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
    - no changes
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
    - No custom firewall rules
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
    - No DNS issues

Related issue: https://github.com/j6s/mailcow-exporter/issues/1

**Comment by andryyy** [comment]
Thanks. :)
