### ISSUE TITLE
rspamd endless loop until crash

### ISSUE THREAD

**Issue by daniel-hamm** [mailcow/mailcow-dockerized#374]
Hi,
I've got this Problem:

`rspamd-mailcow_1     | 2017-06-19 18:31:42 #6(main) rspamd_file_lock: lock on file failed: Bad file descriptor
rspamd-mailcow_1     | 2017-06-19 18:31:42 #6(main) <84df4b>; main; main: cannot write pid file /run/rspamd/rspamd.pid
`

rspamd crashes with an error (247) after multiple loops.
I've tried multiple new installations and even set up a new server and I've always got the same problem.

**Comment by andryyy** [comment]
You built the image yourself I guess. Just use the mailcow image from Docker hub until a new version is released.

**Comment by daniel-hamm** [comment]
Ah, yes, i used the --built command, thanks :)

**Comment by mkuron** [comment]
@andryyy, what's the difference between the current master and the version on Docker Hub? Is the latter newer in some way? The lack of automated builds makes it difficult to correlate GitHub versions with published images...

**Comment by andryyy** [comment]
The current image @ hub is still using 1.5.x while a self built image uses 1.6.x. The lock file location changed in this version.
