### ISSUE TITLE
Redis Failover

### ISSUE THREAD

**Issue by wedi** [mailcow/mailcow-dockerized#3740]
Hi,

right now, mailcow supports clustered Redis via `REDIS_SLAVEOF_IP` and `REDIS_SLAVEOF_PORT` which is pretty cool.

I am wondering how to handle failover with this configuration. I only see two ways to go on from here but probably I have overlooked something:

1. Pointing REDIS_SLAVEOF_IP to a load balancer that handles failover
2. Ignore writes during a failure and fix/fail over once detected.

If I have not overlooked something: would you welcome support for Redis Sentinel? Rspamd has it build in, PHP and Python usage would need some changes.

Sneaking a slightly off topic question in here: Do you know of any problems when pointing more than one mailcow instance to the same redis instance to share config, rspamd learning and more?

**Comment by patschi** [comment]
I'm not sure if I understand the question. The failover is done on Redis-level. Each mailcow instance uses the local redis instance, when syncs the data between the nodes. If a mailcow instance fails, the other mailcow instance has their own redis with their own local data.

**Comment by wedi** [comment]
Thank you for your response! I'll elaborate on my use case and reword my question.

I'd like to achieve two things:

1. A shared Redis setup for two mailcow instances to share rspamd state and other configuration.
2. Seamless failover in case the local (`redis`) or remote (`REDIS_SLAVEOF_IP`) Redis instance fails for some reason.

At the moment, the local hostname `redis` is used at all places where a service needs to read something. If some action needs write access and `REDIS_SLAVEOF_IP` is specified, it's always this IP that is used to connect. In the background, the local redis is mirroring the server behind `REDIS_SLAVEOF_IP`. So mailcow is using a Redis cluster setup.

The problem I'd like to solve is, that the Redis cluster concept, as far as I know, does not / cannot include failover on it's own. It's the client that needs to know an IP where a (writable) redis node answers. I know of two ways to achieve this in Redis: either a loadbalancer that knows which Redis instance the current master is or the client itself asking Redis Sentinel who the current master is prior to establishing a connection.

My questions are  
a) whether I overlooked something? Maybe you could elaborate on _"The failover is done on Redis-level."_?  
b) if you would be interested in a pull request adding Redis failover (aka Redis Sentinel) support in mailcow (in case I have not overlooked something)?  
c) if you know of any problems to look for or configuration to change when two mailcow instances share a common redis database (slighly off topic).

**Comment by mrj1987** [comment]
I’m quite interested in the concept of maintaining quorum between multiple instances as well. Would love to see this supported!
