### ISSUE TITLE
Scheduling Send

### ISSUE THREAD

**Issue by dl-lim** [mailcow/mailcow-dockerized#3743]
**Is your feature request related to a problem? Please describe.**
Does mailcow currently support scheduled sends? i.e. delay delivery until a certain time and the email will automatically go off to its destination.

What webclient supports this? Sogo doesn't.

**Describe the solution you'd like**
Would be great to allow scheduling emails and have a suitable mail client to manage it too.

**Comment by dragoangel** [comment]
Hi, mailcow currently have sogo (which doesn't have such option) and doesn't think mailcow will change sogo to something else in near future as it good groupware actually. You can check sogo bug tracker and try to find such request. If there no such request you can create it, or upvote to existing one and put link here to existing/created issue.
Additionally mailcow has helper script to install roundcube, unfortunately I not using it, so can't say it has such future or not.
As last option you can use imap desktop client to do such stuff or write own script to send scheduled mail.

**Comment by dl-lim** [comment]
I see, that's client-side scheduling, and if I understand correctly, scheduling needs to be available on both client-side and server-side? Correct me if I'm wrong! :)

If I can find a suitable client, does mailcow inherently have this feature built-in?

I was using rainloop as a client to connect to mailcow - love the simple interface, but alas, that too, does not have scheduling.

**Comment by dragoangel** [comment]
Scheduling is client side. Server isn't matter. Mail web services actually also is clients for SMTP and IMAP or Sieve :)

**Comment by alfonsrv** [comment]
@dragoangel no it's not. If you schedule a mail in Exchange and close your Outlook, it's still sent. Scheduling should be a server-side feature, just like auto-reply is.

**Comment by mkuron** [comment]
There is no standardized way to request delayed send via SMTP, so no client or server supports it as far as I know and Mailcow thus can‘t implement it. I‘ve only ever seen it in Exchange/Outlook, which uses a proprietary protocol and not IMAP/SMTP.

**Comment by dragoangel** [comment]
Sogo can actually add this option as said before or any other groupware, but again from client server side it client :). Sieve 100% not have such option and not think it possible add such there. Guy simply don't understand what here client and server and compare full proprietary outlook to many opensource projects which in complex creates mail server.

**Comment by artjomsimon** [comment]
To add some context for others who will find this thread (just as I did during my search for a GMail alternative)

Someone created a bug ticket over at the SOGo bug tracker: https://www.sogo.nu/bugs/view.php?id=4951

GMail, Outlook and Yandex Mail all support scheduled mail sending nowadays, so it has gained some popularity in the meantime. I'm looking for a GMail alternative that supports this and stumbled upon this feature request here.

**Comment by Lennix** [comment]
Maybe we can push sogo to implement this? Currently I have to tell my clients to leave their thunderbird (with send later plugin) running during the time they want to send their scheduled mails. Thats quite the uncomfortable workaround and it would be awesome if that could be integrated directly.

**Comment by dragoangel** [comment]
> Maybe we can push sogo to implement this? Currently I have to tell my clients to leave their thunderbird (with send later plugin) running during the time they want to send their scheduled mails. Thats quite the uncomfortable workaround and it would be awesome if that could be integrated directly.

Don't know if push would help, but donation could.
