### ISSUE TITLE
DNS Problem - MX not found

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3746]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Hello,
my Mailcow is running fine but i have a Problem with one Domain. All other Mails from Mailcow are fine - only this one Domain make problems.
I get following Error-Message:
(Host or domain name not found. Name service error for name=xxx.it type=MX: Host not found, try again)
I checked the Domain DNS Settings but all looks fine. When i send Mail to this Domain from my german "gmx" provider - also all is fine. Only Mailcow has problems. A "dig" check from Mailserver also was fine.

**Systeminformation**:
| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 20 GB, 4 |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.27.0 |

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - it's not a bug report
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

Also giving us your domain can help checking the DNS records.

**Comment by tobias992** [comment]
hahaha, nice job. Thanks for nothing!!!
