### ISSUE TITLE
Cant install with fresh Debian10 

### ISSUE THREAD

**Issue by thomasmax-97** [mailcow/mailcow-dockerized#3749]
when i run docker-compose up i get this error with a fresh debian10:
/opt/mailcow-dockerized# docker-compose up
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
mailcowdockerized_watchdog-mailcow_1 is up-to-date
mailcowdockerized_unbound-mailcow_1 is up-to-date
mailcowdockerized_olefy-mailcow_1 is up-to-date
mailcowdockerized_solr-mailcow_1 is up-to-date
mailcowdockerized_dockerapi-mailcow_1 is up-to-date
mailcowdockerized_sogo-mailcow_1 is up-to-date
mailcowdockerized_clamd-mailcow_1 is up-to-date
mailcowdockerized_redis-mailcow_1 is up-to-date
mailcowdockerized_memcached-mailcow_1 is up-to-date
mailcowdockerized_mysql-mailcow_1 is up-to-date
mailcowdockerized_php-fpm-mailcow_1 is up-to-date
mailcowdockerized_dovecot-mailcow_1 is up-to-date
mailcowdockerized_postfix-mailcow_1 is up-to-date
mailcowdockerized_nginx-mailcow_1 is up-to-date
mailcowdockerized_rspamd-mailcow_1 is up-to-date
Starting mailcowdockerized_netfilter-mailcow_1 ... 
Starting mailcowdockerized_netfilter-mailcow_1 ... error

ERROR: for mailcowdockerized_netfilter-mailcow_1  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"a *:* rwm\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/docker/58e8562c98a868c7400d7bc51562ab4bd3c80f1a8af852028c997e830d8070e6/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/docker/58e8562c98a868c7400d7bc51562ab4bd3c80f1a8af852028c997e830d8070e6/devices.allow: operation not permitted\\\"\"": unknown

ERROR: for netfilter-mailcow  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"a *:* rwm\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/docker/58e8562c98a868c7400d7bc51562ab4bd3c80f1a8af852028c997e830d8070e6/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/docker/58e8562c98a868c7400d7bc51562ab4bd3c80f1a8af852028c997e830d8070e6/devices.allow: operation not permitted\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by andryyy** [comment]
Please use the issue template, thanks. 

To make it short: you are running it on an unsupported platform.

**Comment by MAGICCC** [comment]
Also see the docs: https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/

Furthermore GitHub ain't a support forum either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
