### ISSUE TITLE
Additional_SAN error, Acme - Missing Maildomain

### ISSUE THREAD

**Issue by hansism** [mailcow/mailcow-dockerized#3750]
Can you remove this and restart Nginx and ACME by running `docker-compose restart nginx-mailcow ; sleep 3 ; docker-compose restart acme-mailcow`?

```
server {
  listen 80;
  listen [::]:80;
  server_name autoconfig.*;
  root /web;
  location / {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9002;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/autoconfig.php;
    try_files /autoconfig.php =404;
  }
}
```

_Originally posted by @andryyy in https://github.com/mailcow/mailcow-dockerized/issues/2736#issuecomment-506942739_

I have same problem so I tried remove above codes but, site.conf file has changed.
Current site.conf is

```
server_tokens off;
proxy_cache_path /tmp levels=1:2 keys_zone=sogo:10m inactive=24h  max_size=1g;
server_names_hash_bucket_size 64;

map $http_x_forwarded_proto $client_req_scheme {
     default $scheme;
     https https;
}

include /etc/nginx/conf.d/sites.active;
```
What I should change in order to fix this problem?

**Comment by B-Interactive** [comment]
Just something to note for folk who find this issue.  I had the same error today and it was due to the external **firewall for my VPS blocking port 80**.

I'd blocked the port (among others) while getting things set up and it slipped my mind that Let's Encrypt needs it open to do its validation.
