### ISSUE TITLE
[Feature] Newsletter/mailing list support?

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3758]
**Is your feature request related to a problem? Please describe.**
Managing newsletter/mailing list subscriptions/sending newsletters seems to belong to the scope of an email server.
Users should be able to opt-in/unsubscribe from newsletters.

**Describe the solution you'd like**
A newsletter subscription and mailing list service (optional?) for mailcow.

**Comment by MAGICCC** [comment]
There was a discussion about this topic some months/years ago and I believe we denied it due to its 'complexity' and actually it's somewhat out of scope
But there's an active dev working on mailman and mailcow integration:
https://github.com/Shadowghost/mailcow-mailman3-dockerized

**Comment by strarsis** [comment]
@MAGICCC: Would it make sense to run that on the same server as the mail server?

**Comment by MAGICCC** [comment]
Hm seems this repo is mailcow + mailman.
I guess it's better to use https://github.com/maxking/docker-mailman as separate stack on your host. I never used it though.

**Comment by dragoangel** [comment]
Or separate stack on dedicated VM even if you have enough resources  =)

**Comment by Adorfer** [comment]
just for reference: 

https://github.com/mailcow/mailcow-dockerized/issues/462
https://github.com/mailcow/mailcow-dockerized/issues/1567
https://github.com/mailcow/mailcow-dockerized/issues/2214
https://github.com/mailcow/mailcow-dockerized/issues/2688

**Comment by g4rf** [comment]
I wrote [a guide](https://github.com/g4rf/dockerized-mailcow-mailman) to install and config [mailcow-dockerized](https://github.com/mailcow/mailcow-dockerized) with [docker-mailman](https://github.com/maxking/docker-mailman). It's now in a kind of beta state, but may help to get it working. Help and bug reports are appreciated.

Repo: [github.com/g4rf/dockerized-mailcow-mailman](https://github.com/g4rf/dockerized-mailcow-mailman)

**Comment by MAGICCC** [comment]
Nice, maybe you can also push it to the docs?
