### ISSUE TITLE
Multiple Hosts in sender-dependent transport maps

### ISSUE THREAD

**Issue by Jimmi123** [mailcow/mailcow-dockerized#3759]
**Is your feature request connected with a problem? Please describe.**
A clear and concise description of the problem. For example, I am always frustrated when [...]

I have two mail gateways if one fails. Therefore I don't have the option to enter multiple servers in the sender-dependent transport maps.

**Describe the solution you would like to have**
A clear and concise description of what you want to achieve.

An option to include multiple hosts for the same domain in the sender-dependent transport maps.

**Comment by dragoangel** [comment]
It sounds as a good idea, but at http://www.postfix.org/postconf.5.html#sender_dependent_default_transport_maps doesn't clearly described if it will works with multiply hosts or not.

**Comment by SkanderHelali** [comment]
I was going to open a similar feature request, is this possible in any way?

I'd like to assign multiple relay hosts for the same domain, that way if I disable a relay (or it goes offline) the domain switches to the second one automatically. Maybe even randomly select one when sending if both are enabled & functional.

**Comment by andryyy** [comment]
You need to balance them via DNS or a proxy, there is no such implementation in Postfix. Correct my if I'm wrong. :)
