### ISSUE TITLE
temporary alias of certain domain for all users

### ISSUE THREAD

**Issue by Jimmi123** [mailcow/mailcow-dockerized#3760]
**Is your feature request connected with a problem? Please describe.**
A clear and concise description of the problem. For example, I am always frustrated when [...]

Is it possible that every user can add a temporary alias to a certain domain, even if they don't actually have a mailbox on that domain?
I would like to use it to create disposable addresses like "affdsfasdf@no-spam.tld" or something like that.

**Comment by MAGICCC** [comment]
Yes it's possible
https://mailcow.github.io/mailcow-dockerized-docs/u_e-mailcow_ui-spamalias/

**Comment by Jimmi123** [comment]
Thank you very much for the answer!
But I meant an additional domain that all users can use for the temporary address. I can always choose the domain of the mailbox, but not a dedicated one, which is only for spam. 
Example:
User with the mailbox test@test.tld wants to create a temporary alias. He can do this only for the domain test.tld, but not for a dedicated spam domain, because you cannot select the domain.
Is that somehow understandable?

**Comment by dragoangel** [comment]
@Jimmi123 yes, clear, but what a point in general? What a profit own dedicated domain only for "spam" which will not be really spam? I mean that in any case there will be valid notifications if user will use temp aliases to register on any good website.

The point of temporary alias is:
- they will not work after `n`hours/days/weeks
- not display real users email
- allow to register at online system multiply times without creating bunch of emails

You wouldn't ever cross real email with temporary alias and for end user no matter what domain will be used for temporary alias (at least I doesn't see any really). Also from security point allow user generate temporary aliases only on his domain is logical and at same time easy solution. It easy not only to develop, it easier to support from system administrator view also.

**Comment by Jimmi123** [comment]
@dragoangel 
First of all, thank you for your answer! 

I would like to have it a bit more secure:

- The correct email address is not displayed
- Not even the correct domain is displayed

Is that possible somehow?
Thanks a lot!

**Comment by dragoangel** [comment]
Totally not understand what you mean, no username and no domain - equal to no email.

**Comment by Jimmi123** [comment]
I'll try to explain it with an example:
My mail address: name@domain.com

With the existing temp aliases I can hide my name like for example: aertraethjn@domain.com.
Unfortunately my domain is still seen here (In my case my domain consists of my name). 
So the solution would be if I could give myself a temporary alias with another domain, something like aertraethjn@otherdomain.com.
Thanks a lot for your effort!

**Comment by dragoangel** [comment]
I already answered on this question 😅. You can create static alias for user on any domain, but not temporary ones.

**Comment by Jimmi123** [comment]
All right, thank you very much!
