### ISSUE TITLE
[HELP] How to use with Dokku?

### ISSUE THREAD

**Issue by vndre** [mailcow/mailcow-dockerized#3765]
Hello, I don't have much knowledge of Docker so am looking for a guidance over the installation.

Dokku manages its own Nginx configuration, and Mailcow creates its own, so I thought it would be possible to manage Mailcow through Dokku, but it seems it doesn't (?) support docker-compose files. I did a little research and a possible solution would be to create a Dockerfile which installs all the dependencies.

Is this possible? Could I have an example on how to achieve this, or at least how to make Dokku and Mailcow coexist? thanks.

**Comment by wblondel** [comment]
Hello,

As stated in this pinned issue, https://github.com/mailcow/mailcow-dockerized/issues/3694#issue-673055174 : 

"Please notice that the GitHub issues are not a support platform and are exclusively for filing bugs or feature requests. For Community Support or exchange of knowledge among other great mailcow users, please head over [to the official mailcow community forum under community.mailcow.email instead.](https://community.mailcow.email) See you there!"

Thank you

**Comment by OKNoah** [comment]
Can someone post he relevant discussion?

**Comment by wblondel** [comment]
Sorry, I couldn't find it on the forum :/ No result for "dokku".

**Comment by patschi** [comment]
As @wblondel told earlier, this is not a support forum. Beside that mailcow should be used on a dedicated host 1) for security reasons, 2) to not interfere with any other settings/applications or magic on the same host. Locking discussion to prevent further unnecessary bumps of this issue.
