### ISSUE TITLE
how can I add TLSA records in namecheap dns?

### ISSUE THREAD

**Issue by gh-hassan** [mailcow/mailcow-dockerized#3768]
I have added all the records but don't know how to add tlsa records in my namecheap dns is there anyway I can add it there or is it very necessary?

**Comment by gh-hassan** [comment]
here is the screenshot of DNS details required https://ibb.co/NmwcL4G

**Comment by mkuron** [comment]
That's more of a question for Namecheap's support (and this issue tracker is not for Mailcow support requests either, only for bugs and feature requests). Namecheap actually answers this question at https://www.namecheap.com/support/knowledgebase/article.aspx/535/51/what-type-of-dns-records-can-i-manage and says that they don't support TLSA. That means you cannot use DANE encryption with Mailcow.
