### ISSUE TITLE
Managesieve no longer authenticating correctly as of the latest (2020-09-18) git state

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#3769]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

Since the latest update, managesieve login is failing, simply reporting an authentication failure on part of dovecot. Login with IMAP and SMTP works normally. Was this a side effect of the "allow login only from {SMTP,IMAP,POP3}" change?

**Docker container logs of affected containers**:

From dovecot-mailcow, the only relevant line is

```
dovecot-mailcow_1    | Sep 19 18:48:03 HOSTNAME dovecot: managesieve-login: Disconnected (auth failed, 2 attempts in 12 secs): user=<einar@DOMAIN>, method=PLAIN, rip=172.22.1.248, lip=172.22.1.250
```

**Reproduction of said bug**:

1. Update to latest git master state
2. Access managesieve, either with a mail client or with SoGO 
3. The above line is printed in the log and either an error or nothing is displayed in the client. Errors all refer to failed authentication.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | openSUSE Leap 15.2 |
| Is Apparmor, SELinux or similar active? | Not active |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Bare metal |
| Server/VM specifications (Memory, CPU Cores) | 16G RAM, Intel i7 (8 cores) |
| Docker Version (`docker version`) | Docker version 19.03.11, build 42e35e61f352 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.25.1, build a82fef0 |
| Reverse proxy (custom solution) | nginx on the host |

- Output of `git diff origin/master`, any other changes to the code? Not applicable
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*.  Not applicable
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output. Not applicable

**Comment by lbeltrame** [comment]
To rule out client problems I've tested three different clients:

- KDE Kontact
- Roundcube
- SoGO

All fail to authenticate with managesieve.

**Comment by andryyy** [comment]
Hm, I will check it now, thanks.

**Comment by lbeltrame** [comment]
From my untrained eye, d9b91fc04f286eaba4266ca60254a02dc5e91867 and the one that precedes it in dovecot (09ec4fcd8101c348129c06252d8ea9751e733920) do an explicit check: managesieve not being included means that dovecot will not authenticate.

**Comment by andryyy** [comment]
Fixed. :)

**Comment by lbeltrame** [comment]
Confirmed working, thanks a lot!
