### ISSUE TITLE
Move dovecot.index.* files to a Different Volume

### ISSUE THREAD

**Issue by dl-lim** [mailcow/mailcow-dockerized#3773]
**Is your feature request related to a problem? Please describe.**

Every now and again, usually when an interaction is made, such as receiving a mail, sending one too quickly, refreshing too often etc., dovecot index file cache/log throws errors. See log below:

![image](https://user-images.githubusercontent.com/69715968/93737204-24322400-fc15-11ea-9b41-b6c7662bccdd.png)

When this happens, on Rainloop, I'd get the "Can't get message list" error.

I'm able to fix this by doing `rm docecot.index.*` but this wouldn't be feasible in production, unless I run a cron script on every folder of every user to remove those files, every minute, which isn't practical.

**Describe the solution you'd like**

This appears to be a problem with the fs, as discussed on Telegram :)
Moving the index to another volume would allow the flexibility to mount the larger emails and attachment files externally, with the smaller index files mounted locally, for this setup.

**Additional context**

- My vmail and attachment docker volumes are mounted on an external ZFS drive bind-mounted onto mailcow's host VM via virtio-9p - **ZFS or virtio could be key suspects in this scenario.**
- Other docker volumes are mounted locally in the VM (ext4). This is minimally required to allow mailcow to run normally. In trying to keep a lean VM image, vmail and attachment volumes are mounted externally. Works well so far except the dovecot errors. #3737 
- Dovecot works well usually, but on occasion, this error occurs. Doing  `rm docecot.index.*` fixes it.

Thanks @andryyy - do let me know if you need debugging logs :)

**Comment by andryyy** [comment]
We already found this to be a problem with your virtio setup. And even a mail list topic in Dovecot from 2017 (not mailcow related). 

I also asked you to not open this FR.

**Comment by dl-lim** [comment]
> I also asked you to not open this FR.

Sorry! Thought it'd be easier to keep it tracked out here :(

**Comment by Adorfer** [comment]
1) if we talk about the inconsistency of dovecot-indexes in the given setup: 
https://dovecot.org/pipermail/dovecot/2017-December/110185.html
Looks like "should be fixed upstread". Either in virtio-fs (bit-rot?) or in dovecot. I assume that the inconsistence not only affects index files, but as well the messages themselvsel, just not discovered instantly.

  2) if we talk about "moving indices to a different storage location": That would be indeed an enhancement. it may be perhaps as well offer performance boost for systems with mixed HDD/SSD setup.

**Comment by patschi** [comment]
For completeness, this was done in https://github.com/mailcow/mailcow-dockerized/commit/3e457e03eef4a73ad748965db8d2097288ec006d and https://github.com/mailcow/mailcow-dockerized/commit/2df661a91e0b5facbfcaa2c39e874f162f3fcd0e. Therefore now closing this issue. As always, kudos to @andryyy!
