### ISSUE TITLE
eMail delivery stopped working after upgrade

### ISSUE THREAD

**Issue by snhrdt** [mailcow/mailcow-dockerized#378]
I upgraded to the latest commit in the repo as of Monday, June 19.

Since then, I cannot reliably receive mail, and I see a lot of the following when I do `docker-compose logs -f`:

```
postfix-mailcow_1    | Jun 21 12:16:15 mail postfix/spawn[1391]: warning: command /usr/local/bin/whitelist_forwardinghosts.sh exit status 1
postfix-mailcow_1    | Jun 21 12:16:16 mail postfix/master[352]: warning: process /usr/lib/postfix/sbin/postscreen pid 1390 exit status 1
postfix-mailcow_1    | Jun 21 12:16:16 mail postfix/master[352]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling

bind9-mailcow_1      | 21-Jun-2017 10:45:29.287 REFUSED unexpected RCODE resolving 'b.ns.dnswl.org/AAAA/IN': 62.75.191.6#53
bind9-mailcow_1      | 21-Jun-2017 11:02:34.941 connection refused resolving 'facebook.com.public.sarbl.org/A/IN': 91.194.60.170#53
bind9-mailcow_1      | 21-Jun-2017 11:43:21.754 managed-keys-zone: Unable to fetch DNSKEY set 'dlv.isc.org': SERVFAIL
```

Everything worked just fine before then, but I had not updated in about 4-6 weeks and thought I should catch up.

Every piece of advice and/or help is appreciated. If you need more data, please let me know.

Thanks!

**Comment by K2rool** [comment]
Not sure why bind9 is still running that been removed and replaced with unbound,

**Comment by andryyy** [comment]
Just today. :)

**Comment by snhrdt** [comment]
It looks like at least the postfix image was damaged on my box; I re-pulled it, and that solved the issue.

Oh, and looking forward to unbound.
