### ISSUE TITLE
Aktuelle Version und Update Anzeige

### ISSUE THREAD

**Issue by Ice-Cue** [mailcow/mailcow-dockerized#3785]
Hallo miteinander,

Ich habe jedes mal das Problem um herauszufinden ob ein update verfügbar ist oder nicht. Ich möchte nicht extra bei einem laufendem System das update Script ausführen um herauszufinden ob überhaupt ein Update verfügbar ist. 

Meine Idee, was ist wenn man im Admininterface eine Benachrichtungung erhällt wenn eine neue Version 
Verfügbar ist?  zB in der Systeminformation

Oder noch besser direkt beim Einloggen eine Benachrichtigung.

Würde mich sehr über diese Feature freuen. 
Grüße,

Caspar

**Comment by andryyy** [comment]
Hi,

./update.sh -c

**Comment by flo1212** [comment]
Ja, aber damit wird nur angezeigt:
"Updated code is available."

Schön wäre es, wenn angezeigt wird, welche Version welches Dienstes/Scriptes als Update bereit steht.
Aktuell warten wir auf SOGo 5.0.1, welches vor kurzem offiziell freigegeben wurde und gravierende Fehler behebt.  Wenn ich sehe, das ein mailcow-dockerized-Update genau auch dies mit updated, wäre das SEHR hilfreich.

**Comment by andryyy** [comment]
There are a bunch of configurations and mailcow-related applications without a "version". We don't just add new versions of the components, there is a lot of code and logic by mailcow itself that changes regularly.

A diff to origin/master may help. Or just the comments of the commits pretty-printed.

**Comment by MAGICCC** [comment]
Now you have a button/hint in the UI if a new version is available and its changelog
