### ISSUE TITLE
[Solved] Exchange Activesync Problem with one account

### ISSUE THREAD

**Issue by roswitina** [mailcow/mailcow-dockerized#3786]
I'm running a mailcow server in an internal network, which I synchronize with imapsync several external mail addresses, so that I can access them with several computers.

I use Outlook 2019 and access the mailbox with Exchange Activesync. I have set up several such accesses. 

So far everything works. 

I noticed now that if I have a mail address (e.g. max.mustermann@gmx.at) in Outlook from mid-September 2020 on I don't get the mails displayed anymore. But when I log in to SoGo I see all mails. So the synchronization obviously worked. A test installation of Thunderbird and access via IMAP also works.

It's also interesting that the other accounts I access with Exchange Activesync work normally and show all synchronized mails.

I have already created the account several times in Outlook, but that didn't help either.

What else could I try?

**Comment by roswitina** [comment]
I have now rebuilt the index of the mailbox. It works again. Thanks.

**Comment by andryyy** [comment]
Hi, did you reset the EAS cache?
