### ISSUE TITLE
mailcow/rspamd:1.72 is broken

### ISSUE THREAD

**Issue by leifnel** [mailcow/mailcow-dockerized#3789]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

mailcow/rspamd:1.72 can't be downloaded

**Docker container logs of affected containers**:

**Reproduction of said bug**:

docker pull mailcow/rspamd:1.72
1.72: Pulling from mailcow/rspamd
bf5952930446: Pulling fs layer
8c7fa2881c79: Pulling fs layer
47d94f22544a: Pulling fs layer
07ac1229126b: Waiting
error pulling image configuration: unknown blob

**System information**:

Tried on different hosts, same problem,
| Question | Answer |
| --- | --- |
| My operating system | linux |
| Is Apparmor, SELinux or similar active? | no|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by onek24** [comment]
I can second this - same issue...
Reverting to commit 4234cc027bfc5c911f248b1012c83f07f0308ef3 fixes it for me.
Therefore i assume the error is within dd62030ce2bf3faedf0075c6c8516c719886f615.

**Comment by EnriqCG** [comment]
Happening to me too.
![image](https://user-images.githubusercontent.com/38569176/95014102-ed143780-0644-11eb-9c14-3332607343c2.png)

**Comment by andryyy** [comment]
Hm, it pushed without an error. I just re-uploaded it. Can you try again?

**Comment by leifnel** [comment]
That fixed it

**Comment by andryyy** [comment]
Thanks for the info. I need to add a check to my scripts.
