### ISSUE TITLE
Enhancement: Add spam-trap support

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#379]
In the new Rspamd release 1.6.0 the module "spamtrap" has been added.
It would be quite interesting to have a web interface possibility to configure these rules, add new spamtrap adresses, etc.

Here is the documentation: https://rspamd.com/doc/modules/spamtrap.html

**Comment by K2rool** [comment]
It dose look like a quite cool feature of Rspamd, saying that i highly doubt it's going to get added to Mailcow as 99.99% of users don't need a Spam trap feature.

**Comment by mkuron** [comment]
Yeah, it's probably mainly useful to spam filter developers, maintainers of DNSBLs and people who run really large mailservers. For the average Mailcow user, the current way of training the Bayes filter should be sufficient.

**Comment by andryyy** [comment]
You can enable it for yourself and use a local fuzzy worker to learn the hashes. :) It is a cool feature but I agree with @K2rool and @mkuron

**Comment by mindsolve** [comment]
Ok, thanks @K2rool and @mkuron for the feedback.
I am closing this now.

**Comment by extremeshok** [comment]
@mindsolve @andryyy Could we please re-open this.

Everyone would benefit from the spam trap as its by far the most effective way to kill day zero spam which will get through rspamd.

Also by having a catchall's for webonly domains set to the spamtrap address results in a steady steam of day zero spam being trained on rspamd. This reduces the server load (storage, io, etc) and burden on users checking their junk.

With regards to the current way of training, this is fully automated continual training, set once, enjoy the benefits and forget about it.

Currently my spamtrap is training rspamd with 200-300 messages a day.

Example: 
one of my spamtrap addresses is spam@mailshok.com

Placing the spamtrap address hidden in the login form, allows all web-scrapers and bots to poison their lists. Most spam now originates from outlook.com/gmail.com/gmx.com/yahoo.com and one can not ban those servers

**Comment by mkuron** [comment]
Feel free to add submit a pull request that adds it to the documentation. I still think this is a niche feature that few Mailcow users need.

Also, I assume rspamd‘s rules are created from such spamtraps run by the developer, so rspamd users don‘t really need to run their own (unless they get lots of exotic spam).

**Comment by andryyy** [comment]
No, not everyone needs a spam trap...

It is easy to solve with a very few lines. This repo is not a clone for your installation. Fork it and add it to your fork, done.

**Comment by savek-cc** [comment]
Comment: I use Mailcow for a personal Mailserver (hand full of users) - but all of them are using aliases/extensions for emails (user-amazon, user-mailingxyz etc) - when one of those addresses start getting spam, it would be nice to just redirect them to a spam trap.
Got the hint about DIY though..

**Comment by patschi** [comment]
That's already possible by simply checking "Learn as spam" on the alias:
![image](https://user-images.githubusercontent.com/2029878/63523403-6660d180-c4fa-11e9-9211-0831ebb90065.png)
