### ISSUE TITLE
lua; dkim_signing.lua:104: signing failure: cannot make request to load DKIM selector for domain

### ISSUE THREAD

**Issue by jzt308** [mailcow/mailcow-dockerized#3792]
When checking my mailcow Rspam container logs I found the following line on every mail that the server recieves.
lua; dkim_signing.lua:104: signing failure: cannot make request to load DKIM selector for domain
This happens with all domains (for example google.com)

I verified that there are no ports being blocked from the server.

Searching the internet or this github gave no results into fixing this problem.
Running Rspam 2.6 (pulled latest mailcow version on 3rd of Oktober 2020)

**Comment by mkuron** [comment]
This question should go on one of our support channels and not on the bug tracker. I certainly don't see this issue on my Mailcow instance. The issue template contains instructions how to check your firewall rules and your DNS resolver, which are a good starting point for solving this kind of issue. The log file of the unbound container might also contain some clues.
