### ISSUE TITLE
Sogo instance - own Domain

### ISSUE THREAD

**Issue by maxileith** [mailcow/mailcow-dockerized#3795]
Hello,

I would like to give the SOGO instance its own domain (subdomain), so that instead of https://mail.example.com/SOGo I have https://webmail.example.com as URL to the SOGO instance.

I think the best way to do this is via a reverse proxy. Is this done in the NGINX inside the Docker Container?

How does it work? I have no experience with NGINX, only with apache2.

Thanks for the help in advance.

**Comment by lotg2020** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/u_e-webmail-site/

**Comment by DimentR** [comment]
> https://mailcow.github.io/mailcow-dockerized-docs/u_e-webmail-site/

301 redirect not proxy to sogo.
