### ISSUE TITLE
New index volume breaks mdbox and attachment deduplication

### ISSUE THREAD

**Issue by ivonoppen** [mailcow/mailcow-dockerized#3799]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

With the newest change to a separate index volume, current installations break that were using mdbox with attachment deduplication. The new volume is in placed instead of the vmail-attachments volume and therefore, dovecot is not able to find attachments. Furthermore, the index volume breaks mdbox indexes and marks all mail as unread.

**Docker container logs of affected containers**:

Dovecot

**Reproduction of said bug**:

Existing installation with:
- install any previous version from approx. max. August 2020
- mdbox in mailbox_format in the database
- send some mails with attachment
- upgrade to current version
--> result, mail does not load in sogo or in any mail client because of read failures on /var/attachments
--> on closer inspection, attachments dir is removed from docker-compose
--> when reinstating the attachments volume, mail works, but because current index volume, all mail is shown as unread in any client and not all mails show up in the right folder (in my case, the past two years of mail is again in the inbox instead of the archive folder).

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Linux |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Openstack |
| Server/VM specifications (Memory, CPU Cores) | 2 CPU, abundant memory (8G) |
| Docker Version (`docker version`) | 19.03.12 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | yes (not the problem though) |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
-- none
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
-- n/a
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
-- n/a

**Comment by andryyy** [comment]
We don't support mdbox officially. You need to track master commits and make sure your setup keeps compatible with it.

**Comment by ivonoppen** [comment]
In that case I'd like to point out that you have incompatible settings in your dovecot.conf file in the main repo. mail_attachment_dir = /var/attachments is only valid if you do SIS. And this directory also was just removed so if anyone anywhere uses this they will run into a problem.
