### ISSUE TITLE
[Bug: NginX] listen.active missing in repository

### ISSUE THREAD

**Issue by lgleim** [mailcow/mailcow-dockerized#38]
You include the nginx config file `/etc/nginx/conf.d/listen.active` here https://github.com/andryyy/mailcow-dockerized/blob/master/data/conf/nginx/site.conf#L3 but it is actually not in the repository, leading to errors like
```
31.1.2017 17:24:052017/01/31 16:24:05 [emerg] 1#1: open() "/etc/nginx/conf.d/listen.active" failed (2: No such file or directory) in /etc/nginx/conf.d/site.conf:3
31.1.2017 17:24:05nginx: [emerg] open() "/etc/nginx/conf.d/listen.active" failed (2: No such file or directory) in /etc/nginx/conf.d/site.conf:3
```

**Comment by andryyy** [comment]
It is created. Do you use the latest compose file?

Beste Grüße 
André

**Comment by lgleim** [comment]
Ah my... no, I have a customized rancher setup. Thanks for the pointer. I certainly missed that change to the compose file. Closing ;)
