### ISSUE TITLE
Cannot send message: all recipients are invalid. CLOSE

### ISSUE THREAD

**Issue by DrTrills** [mailcow/mailcow-dockerized#380]
Hello,

I am using Google's G-Suite and today setup split routing so when someone emails googleuser@company.com it goes to their gmail inbox. But when some one email mailcowemail@company.com google pushes the email to my mailcow server as it doesn't have this user.

I have SPF, DKIM, DMARC all setup and am able to send/receive from my personal gmail to my mailcow server.

I am unable to send from my google@company.com account to mailcow@company.com as well as from my mailcow@company.com to google@company.com

i am getting the error

> Cannot send message: all recipients are invalid. CLOSE

in SOGo and in gmail I get a bounceback message with:

> The response from the remote server was:
> 550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser i12si6826984otc.196 - gsmtp

Any help would be much appreciated!

**Comment by DrTrills** [comment]
Update:

Was able to solve the issue from Mailcow to G-suite address. I checked off the backup MX options and it works like a charm.

I am however still unable to receive emails from the same domain coming from Google server to Mailcow. After contacting support they were able to determine the response is: 

> rejected by the relay (ip address)

From google support email:
> The error that the other server returned was: 550 5.1.0 : Sender address rejected: User unknown in virtual mailbox table

Any advice on how to make it so I can send on the same domain name from google to mailcow is greatly appreciated.

Thank you

**Comment by catcun** [comment]
I have set up split domain routing with Office 365 and MailEnable (at the same time for the same domain, Postfix is awesome). 
I do not remember how I solved the specific problem that you have but I remember that I had to setup an alias domain in Mailcow (mycompany.auxdomain.com), set a forward mbox@mycompany.com -> mbox@ mycompany. auxdomain.com and had to play with Postfix transport_maps and smtpd_sender_restrictions. I also had to instruct the other SMTP server to relay to Mailcow, and that step is different for every email server.
Also, I had to create every account in MailCow when MailCow is the secondary server. More than anything, what you want to do is possible!

**Comment by DrTrills** [comment]
@catcun Thanks for replying.

I've made some progress but still stuck.

I can confirm that my DNS settings are good. I looked into domain alias but was unable to get far with that.

What I found is when I select the options below in UI. I cants end/receive emails. When they are de-selected (as shown below) I am able to send/receive from my gmail but not to my account on samedomain/google.

Backup MX options


- [ ] Relay all recipients
If you choose not to relay all recipients, you will need to add a ("blind") mailbox for every single recipient that should be relayed.
- [ ] Relay domain 

The issue must be with the MX/relay. If you can think of anything that would be great. I've seen on forums many people talking about virtual address in postfix but haven't made it super far on how to apply that to my usecase.

Thank you

**Comment by andryyy** [comment]
I don't think I can follow you.

But .. have you tried to create a catch-all alias in mailcow?

**Comment by DrTrills** [comment]
Hi @andryyy 
I created a small diagram that hopefully explains it clearer.

1. someone email ID@comapny.com which is sent to google. If google finds the address it delivers to the gmail inbox and everyone is happy.
2. If google is unable to locate ID@company.com it then pushes the email to my mailcow server via IP address.
3. Mailcow see an incoming message to ID@company.com and delivers the message to that inbox.
4. Everyone is happy

![untitled diagram](https://user-images.githubusercontent.com/1430005/27434675-cae99b52-5759-11e7-88c6-d851c0a9daa2.png)

Currently I am able to to send/receive from mailcow to emails on the same domain, and outside domainds (gmail).

- anyone@example.com to user@mailcowserver works fine
- user@mailcowserver to anyone@example.com works fine
- user@mailcowserver to user at same domain hosted on google works fine
- user@same domain as mailcow, hosted on google is being rejected from mailcow 


But mailcow is rejecting incoming mail from google (same domain name)
This is the error:

> The response from the remote server was:
> 550 5.1.0 <me@samedomainasmailcow.com>: Sender address rejected: User unknown in virtual mailbox table

It seems mailcow is looking for the same user as it thinks it's on that server, but as that user only exists on google and now mailcow it's rejecting it? Is there a way to have it not reject mail based off virtual mailbox?

Thank you Andre

**Comment by lazyfrosch** [comment]
The problem is the From/Sender address.

I have a similar problem when sending a mail from `me@mydomain.de` to `me@test.mydomain.de`

Since the sender is also in local recipient list, the address is verified against the sender list.

Solution would be to only check sender if the user is authenticated...

**Comment by DrTrills** [comment]
Thanks for the reply @lazyfrosch 

I will check it out and update.

Thank you

**Comment by andryyy** [comment]
I'm on mobile right now, so my instructions are a bit vague:

Search data/conf/postfix/main.cf for "reject unauthenticated sender mismatch" and remove it. 

Restart the stack and it should work. 



Beste Grüße 
André

**Comment by DrTrills** [comment]
@andryyy Thank you, that did it!

So on the line: smtpd_sender_restrictions =

removing **reject_unlisted_sender,** makes it so I can now accept emails from the same domain sent from gmail.

Thank you!

Now I am unable to send from Mailcow to Google :/. Will play around with it and update when I solve it before flooding with errors.

**Comment by DrTrills** [comment]
**Solution** 

1 domain, 2 hosts (google G-suite & mailcow). When someone emails mydomain.com it goes to google first. If google can't find the mailbox it is then pushed to Mailcow to be delivered.

Issues
1. Mailcow/Postfix rejects incoming messages from the google server with the same domains.
2. Mailcow/Postfix will not send messages to google server with same domain. 

Solutions (in postfix main.cf)
1. Allow google to send/deliver to mailcow server with same domain. On line: `smtpd_sender_restrictions =` **remove** `reject_unlisted_sender`
2. Allow mailcow to send to google server, same domain. Comment out the following:
`#virtual_mailbox_domains = `
`#virtual_alias_maps = `
`#virtual_mailbox_maps = `

`docker-compose restart postfix-mailcow` to restart and you should be all set.

**Comment by ww7** [comment]
@DrTrills 
This workflow still works? Do you shortly describe how setup split routing on G Suite?

**Comment by DrTrills** [comment]
@ww7 sadly I wasn't successful in my attempts and now use mailcow for our .net domain and g-suite for our .com.

**Comment by PublicByte** [comment]
It's also not working for me, but I've done some tests.

**Send**
Comment out the following lines:
- [x] virtual_alias_maps
- [x] virtual_mailbox_domains
- [ ] virtual_mailbox_maps

So, here's my theory why Postfix is unable to receive an email. The Postfix server is unable to map all mailboxes due we commented it out, in conclusion, the server will now reject every email because there're no existing mailboxes.

**Receive**
Comment out the following lines:
- [ ] virtual_alias_maps
- [ ] virtual_mailbox_domains
- [x] virtual_mailbox_maps

So, here's my theory why Postfix is unable to send an email to a G-Suite account. First of all, the Postfix server knows which user exists, or is non-existent. If you're trying to send an email to a G-Suite account, the Postfix server will check if the recipient exists, and it'll quickly notice that this mailbox doesn't exist, and will not deliver your email to the actual G-Suite account.

Do you have any news on how to fix this problem? I require Mailcow & G-Suite for different use cases, so it would be useful to know.
