### ISSUE TITLE
Check if SELinux compatibility can be added to backup-and-restore.sh as well

### ISSUE THREAD

**Issue by shiz0** [mailcow/mailcow-dockerized#3800]
**Is your feature request related to a problem? Please describe.**
https://github.com/mailcow/mailcow-dockerized/pull/3766 added SELinux compatibility to the docker-compose.yml by adding labeling info to the volume mounts.
backup-and-restore.sh misses such info and running the script with SELinux enforcing will produce errors.

**Describe the solution you'd like**
Add labeling info to the script (and test!) to make in SELinux compatible as well, or at least add a note to the docs to temporarily set SELinux non-enforcing to run the script (which is what I am currently doing as a workaround whenever I want to use the script).

**Comment by amishtechie** [comment]
+1 for this.
