### ISSUE TITLE
Invalid reference for SQL container in backup script on Debian

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3808]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

The SQL database is not backed up when running the backup script on a Debian 10.6 instance.

**Docker container logs of affected containers**:

Content of backup_mailcow.sh 'wrapper script':
```bash


#!/usr/bin/env bash
echo Mailcow backup script - `date`
echo
# mount certificates folder
mount -t cifs -o credentials=/home/username/.smbcredentials,vers=2.0 //192.168.X.X/backup_mailcow /mnt/backup_mailcow
# create backup
MAILCOW_BACKUP_LOCATION=/mnt/backup_mailcow /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all --delete-days 7
# unmount backup folder
umount /mnt/backup_mailcow
echo
echo
```

This is a (shortened version) of the stdout when the backup script ran
```bash
root@mail:/home/username# /home/username/backup_mailcow.sh
Mailcow backup script - Thu 15 Oct 11:41:21 CEST 2020

Using /mnt/backup_mailcow as backup/restore location.

Found project name mailcowdockerized
/vmail/
/crypt/
/crypt/ecprivkey.pem
/crypt/ecpubkey.pem
Error: No such container: redis-cli
/redis/
/redis/dump.rdb
/rspamd/
/postfix/
/postfix/maildrop/
Using SQL image mariadb:10.4, starting...
docker: invalid reference format.
See 'docker run --help'.


root@mail:/home/username#
```
**Reproduction of said bug**:

The bug is reproducible. Research in prior tickets has shown that running mailcow-dockerized on Debian switches the containers to debian:buster-slim containers, so I assume that the reference to the database container is incorrect when run on Debian.
The bug is _not_ reproducible on a Ubuntu instance.
**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.6 minimal install - Docker and Docker-Compose installed via Docker webpage instructions - latest updates run on system (apt update/upgrade) and mailcow. The backup has run after mailcow was migrated from Ubuntu using the backup restore script. |
| Is Apparmor, SELinux or similar active? | Apparmor active (unaltered Debian bare-minimal installation) |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Debian running on ESXi 7.0 |
| Server/VM specifications (Memory, CPU Cores) | 5 GB / 1 core |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.27.4, build 40524192 |
| Reverse proxy (custom solution) | not applicable |

- Output of `git diff origin/master`, any other changes to the code? If so, please post them. - **No changes made to any Mailcow code.**
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Can you post `docker ps -a` output?

**Comment by andryyy** [comment]
Does it work when you cd into the mailcow directory (like `cd /opt/mailcow-dockerized`) and run `bash helper-scripts/backupbla.sh backup etc.pp.`?

**Comment by ghost** [comment]
Hi Andre,

You are right, my wrapper script for the crontab is to blame. It works using your command.
Sorry for bothering you!

**Comment by andryyy** [comment]
No problem at all. :)
