### ISSUE TITLE
Calendar invitation does not show up in IOS calendar inbox

### ISSUE THREAD

**Issue by jacotec** [mailcow/mailcow-dockerized#3809]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

User A creates an event in the calendar and adds user B as an ivitee. User B has an IOS devices (iPad, iPhone) connected via Active Sync.

As soon as user A stores the new entry, user B gets the email with the .ics file as expected.

The issue is that IOS does not interprete this incoming mail as a calendar invitation. With other groupware solutions, the iDevice parses the email and automatically shows the invitation as a calendar event, the invitation is in the Inbox of the calendar app. Unfortunately this does not happen here.

Instead, the user B must open the email and tap on the .ics attachment to see the event information and to accept/decline the invitation.

**Docker container logs of affected containers**:

Not a container misbehavior, I guess it's an incorrect formatting of the invitation notification email so the iDevice does not recognize it as an invitation when it receives the email.

**Reproduction of said bug**:

- Have 2 users A and B, user B with an iPad / iPhone attached via Active Sync
- User A creates a calendar entry (i.e. in SOGo) and adds user b as an invitee
- User B gets the eMail with the invitation (attachment as .ics file)
*Expected:* The calendar notification on the iPhone should pop up and the invitaiton should be in the calendar inbox
*Current:* Nothing happens, user B must manually open the email and tap on the .ics attachment

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare ESXi 6.7U3 |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 6 Cores |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4, build 40524192 |
| Reverse proxy (custom solution) | HAPROXY |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Hi,

Can you please post this to SOGo? 👍 

Thanks
André

**Comment by jacotec** [comment]
Done!
