### ISSUE TITLE
Add support for Traditional Chinese (Hong Kong)

### ISSUE THREAD

**Issue by JasonHK** [mailcow/mailcow-dockerized#3812]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

I would like to help with translating the project to Traditional Chinese (Hong Kong).

**Comment by dragoangel** [comment]
Hi @JasonHK you can create PR with new file at https://github.com/mailcow/mailcow-dockerized/tree/master/data/web/lang 😸
