### ISSUE TITLE
Add rspamd header to quarantined messages

### ISSUE THREAD

**Issue by ShiroDN** [mailcow/mailcow-dockerized#3819]
**Is your feature request related to a problem? Please describe.**
I just got an order confirmation from a eshop and a message was rejected and quarantined by rspamd mainly because of FUZZY_DENIED (10.514324). So I wanted to report a hash for removal (https://bl.rspamd.com/) but I can't find fuzzy hash anywhere. I looked for it in the log (docker logs rspamd) and for header in released mail (X-Rspamd-Fuzzy).

**Describe the solution you'd like**
Is it possible to add X-Rspamd-Fuzzy header to quarantined messages, or add all other headers like X-Spamd-Result etc?

**Comment by andryyy** [comment]
I was working on this a while ago. I will implement it.

**Comment by andryyy** [comment]
We should probably add a delisting feature for the mailcow fuzzy, too.

**Comment by andryyy** [comment]
Implemented with 0165c9d26b71b696a848ca1145e105b6a66b55c0
