### ISSUE TITLE
Need parameter "--useuid" for imapsync to avoid duplicates

### ISSUE THREAD

**Issue by bawe** [mailcow/mailcow-dockerized#382]
Hi,
my source server is "zarafa-gateway version 7,1,14,51822 (51822)"
the option delete2duplicates is not enough - every run all mails are duplicated.

If I run with "--useuid" inside the container the sync works as expected.

Regards
Bastian

PS. Nice work.

**Comment by mkuron** [comment]
That option can safely be added. It only affects messages that do not have a Message-ID header, which will then automatically have one generated for them by imapsync. Can you post a pull request that edits https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/imapsync_cron.pl accordingly?

**Comment by bawe** [comment]
sorry, since I am unfortunately somewhat overstrained, since I have no git experience. :-/

 
-----Ursprüngliche Nachricht-----
Von:Michael Kuron <notifications@github.com>
Gesendet:Mi 21.06.2017 20:41
Betreff:Re: [mailcow/mailcow-dockerized] Need parameter "--useuid" for imapsync to avoid duplicates (#382)
An:mailcow/mailcow-dockerized <mailcow-dockerized@noreply.github.com>; 
CC:Weber, Bastian <bastian@weber-bastian.de>; Author <author@noreply.github.com>; 
 

That option can safely be added. It only affects messages that do not have a Message-ID header, which will then automatically have one generated for them by imapsync. Can you post a pull request that edits https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/imapsync_cron.pl accordingly?

**Comment by mkuron** [comment]
Please disregard my previous comment, now deleted. I was thinking about `--addheader`, which is safe as it adds a `Message-ID` header to messages that don't have one. `--useuid` is bad though as I don't think IMAP UIDs are guaranteed to be stable. Even worse, the UIDs are cached by imapsync in a file that is not persistent across docker pulls. So you need a different solution.

Do your emails have `Message-ID` headers? That's what imapsync needs and they have been standard for at least a decade.

**Comment by bawe** [comment]
yes e.g.: Message-ID: <1043714374.17537.149XXXXXXXXXX.JavaMail.root@server1>

I have also tested to add "--addheader" before but no effect. Do I need more?

**Comment by mkuron** [comment]
With these Message-IDs it should work fine. Try putting two or three messages into a folder and imapsync just that folder. Then run imapsync again in verbose mode and post the logs here. That should tell us why the messages are duplicated. Somehow, it's evidently not using the Message-ID header, or Zarafa randomly changes that header.

**Comment by catcun** [comment]
To sync accounts for migration I have successfully used --nosyncacls --subscribe --syncinternaldates --nofoldersizes --skipsize --fast --addheader --delete2 --delete2duplicates for both MailEnable and Office 365.

Then just changed the IMAP/SMTP servers on Outlook, Thunderbird and MacOS Email without sync problems.

**Comment by bawe** [comment]
I now have moved thre mail with an temp cronjob:

   --tmpdir /var/vmail/_tmp_imapsync 
   --subfolder2 External 
   --maxage 6400   
   --delete2duplicates 
   --useuid 
   --delete2

Thanks
