### ISSUE TITLE
Nignx Blocks because of FastCGI

### ISSUE THREAD

**Issue by flixbi** [mailcow/mailcow-dockerized#3834]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
The problem is, this "non-available" upstream blocks nginx from starting up and serving the Admin-Panel.
I restartet docker as a whole, to simulate an power off szenario and test wheter the containers all come up and running again or some of them block. Nginx did, the rest is fine.

**Docker container logs of affected containers**
The Logs say:
```
2020/11/01 13:32:35 [emerg] 18#18: host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: [emerg] host not found in upstream "phpfpm" in /etc/nginx/conf.d/dynmaps.conf:13
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Reproduction of said bug**:
I restarted my stack, where Nginx has no direct access to the host ports (it's behind an reversed proxy)
and Nginx blocked with the error seen in the upper log.

**System information**

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20 LTE |
| Is Apparmor, SELinux or similar active? | Apparmor active and running |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Docker |
| Server/VM specifications (Memory, CPU Cores) | 32 GB RAM, 12 CPU-Cores (AMD Ryzen) |
| Docker Version (`docker version`) |  |
| Docker-Compose Version (`docker-compose version`) | 19.03.12 |
| Reverse proxy (custom solution) | With Caddy |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
I added the nginx container to an DMZ 
+ it has been left the "mailcow-network" after the restart, thats maybe an useful fact - an problem with the override of the docker-compose.yml file ?! - I wrote it like that:
```yml
nginx-mailcow:
      # Ports are commented out in the original
      expose:
        - "80"
        - "443"
      networks:
        mailcow-network:
          aliases:
            - nginx
        dmz_01:
            ipv4_address: 172.22.0.10
```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`. 
=> My firewall is properly configured (all ports needed can be used)
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by flixbi** [comment]
The failure is bigger than I thought.. all other containers started without any problem, but they all left their networks (only the mailcow containers) ... I'm searching on

**Comment by andryyy** [comment]
I don't quite understand how that's a bug in mailcow. 

Your phpfpm container is not reachable/online. That can have multiple issues, but that's not a general bug. 

Please use the community support channels or describe what BUG you encounter. If it's a support question, we can close the issue here.
