### ISSUE TITLE
Full Name with Umlaute is not displayed correctly in SOGO and E-Mail From field

### ISSUE THREAD

**Issue by Vespasian** [mailcow/mailcow-dockerized#3835]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
If i create a user with a Full Name containing Umlaute (ÖÜÄ, etc) it does not get displayed (and sent) correctly in SOGO.

![grafik](https://user-images.githubusercontent.com/7491275/97809260-2784ea80-1c6c-11eb-8ce8-7fc64e78084f.png)
![grafik](https://user-images.githubusercontent.com/7491275/97809274-3370ac80-1c6c-11eb-9a5d-fc686987f08c.png)

It works fine when sending mails with an external programm such as Thunderbird.

**Docker container logs of affected containers**:
None

**Reproduction of said bug**:
- Create a new mailbox.
- Use "Müller" as the Full name.
- Open SOGO and look at the Full Name / send an e-mail

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.1 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** |- |
| Server/VM specifications (Memory, CPU Cores) | 4 vcores, 16GB |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) |  1.23.2 |
| Reverse proxy (custom solution) | custom nginx within a Docker container |

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/97810028-3f12a200-1c71-11eb-955c-d2e477198af0.png)

**Comment by Vespasian** [comment]
Alright seems to be an issue with my installation then.

**Comment by andryyy** [comment]
Hmm. 

Do you use an external SQL? Which browser on which OS?

**Comment by Vespasian** [comment]
Thanks for your reply.

I use the default database and did not make any changes.

I tested firefox Firefox and Chrome on Windows 10.

**Comment by andryyy** [comment]
That's really strange then. :( Is it a new setup?

**Comment by Vespasian** [comment]
Yes. Fresh from the press. 

If I figure this out I will add another comment with the cause.

Thanks for your help nevertheless :)
