### ISSUE TITLE
DNS-Challenge for domains

### ISSUE THREAD

**Issue by axiades** [mailcow/mailcow-dockerized#3836]
**Describe the solution you'd like**
Hallo,

Da mein Englisch mies ist heute mal auf Deutsch.

Ich würde mir wünschen dass man die SSL-Zertifikate auch per DNS Challenge anfordern kann.
Um Wildcard Zertifikate Anzufordern über DNS-Challenge.

z.b. indem man die DNS-Variablen in der mailcow.conf einträgt für z.b. in meinem fall OVH ^^

MFG

**Comment by patschi** [comment]
Duerfte man fragen, welchen Mehrwert dies gegen die HTTP-Verifizierung hat? Fuer die WebUI und die Weiterleitung von HTTP auf HTTPS wird ohnehin Port 80 benoetigt, welches auch fuer die HTTP-Challenge verwendet wird. Ein Wildcard-Zertifikat wird technisch fuer die mailcow nicht benoetigt.

**Comment by andryyy** [comment]
Ich würde auch eher davon absehen. Ich habe mal überlegt es als Gimmick für Servercow Kunden einzubauen (über die eigene API bei uns). :)

**Comment by cl445** [comment]
Dann mache ich mal weiter auf deutsch: Bei mir ist es z.B. so, dass Mails (aus Kompatibilitätsgründen) über Domains abgerufen werden, die nicht per http auf Mailcow verweisen. Aktuell löse ich das über einen Certdumper, aber eine DNS-Challenge wäre hier schon eleganter.

**Comment by DWiskow** [comment]
You can easily setup a reverse-proxy in front of mailcow using something like DNSroboCert & Nginx (I run these in docker) and then copy the multi-domain/wildcard certificate generated by DNSroboCert across to mailcow to authenticate its specific domain.
