### ISSUE TITLE
Backup helper scripts failed for DB backup

### ISSUE THREAD

**Issue by 8ear** [mailcow/mailcow-dockerized#3838]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
It looks like the backup helper-script does not create finished backup-all backup. It looks like the DB backup fails.

**Docker container logs of affected containers**:
```
Using SQL image mariadb:10.4, starting...
[00] 2020-11-03 22:11:37 Connecting to MySQL server host: mysql, user: root, password: set, port: 3306, socket: /var/run/mysqld/mysqld.sock
[00] 2020-11-03 22:11:37 Failed to connect to MySQL server: Unknown MySQL server host 'mysql' (-3).
mariabackup based on MariaDB server 10.4.15-MariaDB debian-linux-gnu (x86_64)
mariabackup: Can't change dir to '/backup_mariadb/' (errno: 2 "No such file or directory")
[00] 2020-11-03 22:11:37 can't my_setwd /backup_mariadb/
chown: cannot access '/backup_mariadb': No such file or directory
/bin/tar: /backup_mariadb: Cannot stat: No such file or directory
/bin/tar: Exiting with failure status due to previous errors
```

**Reproduction of said bug**:
```
sudo MAILCOW_BACKUP_LOCATION=/backup/mailcow /opt/git/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all
```

**System information**:
```
~$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

~$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

| Question | Answer |
| --- | --- |
| My operating system | Debian Buster|
| Is Apparmor, SELinux or similar active? | Not really |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) |8 CPUs, 32GB RAM |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) |1.27.4 |
| Reverse proxy (custom solution) | Traefik |

**Comment by ValeriySh** [comment]
It looks like you have your mailcow.conf generated by an older script, while the author has introduced some changes in the container naming. Check my solution here: https://github.com/mailcow/mailcow-dockerized/issues/2692#issuecomment-731897011

**Comment by 8ear** [comment]
Thanks.
