### ISSUE TITLE
IPv6Nat is not able to start after update.sh is run

### ISSUE THREAD

**Issue by 2mt-hillen** [mailcow/mailcow-dockerized#3839]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
After running the update-script the ipv6nat-container is not able to be started.

**Docker container logs of affected containers**:
As the container can't start, there are no logs of this container. So here are the logs of the update-script

```
Creating mailcowdockerized_ipv6nat-mailcow_1   ... error

ERROR: for mailcowdockerized_ipv6nat-mailcow_1  Cannot start service ipv6nat-mailcow: endpoint with name mailcowdockerized_ipv6nat-mailcow_1 already exists in network host

ERROR: for ipv6nat-mailcow  Cannot start service ipv6nat-mailcow: endpoint with name mailcowdockerized_ipv6nat-mailcow_1 already exists in network host
ERROR: Encountered errors while bringing up the project.
```

**Reproduction of said bug**:
run the update script.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10|
| Is Apparmor, SELinux or similar active? | No|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM|
| Server/VM specifications (Memory, CPU Cores) | 4GB Ram, 2 Cores|
| Docker Version (`docker version`) | 19.03.13|
| Docker-Compose Version (`docker-compose version`) | 1.27.4|
| Reverse proxy (custom solution) | No|

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
```
diff --git a/data/conf/nginx/templates/server_name.template b/data/conf/nginx/templates/server_name.template
index 261a1ece..5ce2de99 100644
--- a/data/conf/nginx/templates/server_name.template
+++ b/data/conf/nginx/templates/server_name.template
@@ -1 +1 @@
-server_name ${MAILCOW_HOSTNAME} autodiscover.* autoconfig.*;
+server_name ${MAILCOW_HOSTNAME} autodiscover.* autoconfig.* mail.*;
```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
i have nothing changed on the firewall

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
I did run the update script several times and don't have this problem, please check your OS and Docker installation. :)

**Comment by 2mt-hillen** [comment]
So `service docker restart` seemed to fix it ^^
