### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by PhoenixPeca** [mailcow/mailcow-dockerized#384]
Hi Andre,
I have just updated my setup with your latest commit in the master branch. I have followed the instructions as it was stated in the [new update routine](https://mailcow.github.io/mailcow-dockerized-docs/install-update/) in the documentation. But I am getting these issues.

---

1 . SOGo shows a blank mailbox
![untitled](https://user-images.githubusercontent.com/9730242/27419435-8e8b116e-5753-11e7-982e-2c70ea150230.png)

---

2. I can't log-in to roundcube
![sdgdfg](https://user-images.githubusercontent.com/9730242/27419523-f52f44c6-5753-11e7-9c88-a760ead4b308.jpg)

---

3. rspamd says it has learnt nothing and the history is empty despite the fact that the server has been operating and is receiving emails for over a month already 
![sdgdfg](https://user-images.githubusercontent.com/9730242/27419568-3521d896-5754-11e7-8695-2b1db98b2005.jpg)

---

So far these were the only issues that I have encountered. I'll update as soon as I find a new one. But for now, I'm seeking for possible solution. I would be glad if you can help me with this. Thanks!!!!

**Comment by andryyy** [comment]
I think this is an issue with the ssl ceritifcates. Can you check for them in data/assets/ssl? cert, key and dhparams?

**Comment by PhoenixPeca** [comment]
I can confirm. This is indeed an issue regarding the ssl certs!! Thanks!! The validation failed because my setup is in a reverse proxy.

**Comment by PhoenixPeca** [comment]
@andryyy  one more question though, If I wan't to replace the letsencrypt cert with a certificate that I acquired from a third-party CA, which file should I replace it with? I can't seem to find a doc about this.

Here's the directory tree list of my setup. I am confused which file should I replace. 😕  
![01](https://user-images.githubusercontent.com/9730242/27420725-cc9b55e4-5759-11e7-8836-52d67aad2fb0.png)

**Comment by PhoenixPeca** [comment]
I also presume that the folders with dated names inside the private folder are "backups". and that these files can be deleted without producing issues if I don't need them anymore. Am I right?

**Comment by andryyy** [comment]
Oh, I will add it to the docs.
Just put it in data/assets/ssl: the combined certificate with its intermediate CA/CA as cert.pem and the key as key.pem.
It will not be overwritten by acme-mailcow as long as the issuer is not LE.

**Comment by PhoenixPeca** [comment]
ok thanks!
