### ISSUE TITLE
Manually learning spam deletes fuzzy hashes

### ISSUE THREAD

**Issue by Clevero** [mailcow/mailcow-dockerized#3844]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When manually learning email(s) from quarantine it also adds and deletes blacklist/whitelist fuzzy hashes on rspamd side. This process is in the wrong order, which results in actual deleting those blacklisting fuzzy hashes when manually learning spam.
The current behaviour is:
1. Adding it to the blacklist (flag 11)
2. deleting it from the whitelist (flag 13)

The issue occurs when executing step 2. Deleting fuzzy hashes via the HTTP endpoint ```fuzzydel``` does not respect the given flag, even if the flag specified != the flag from the database/redis.
So, the current behaviour is adding a blacklisting fuzzy hash and afterwards also deleting it (and all other fuzzy hashes related to the message).

[One comment](https://github.com/rspamd/rspamd/issues/489#issuecomment-175195935) in an issue of the rspamd repo states, that the rspamc command ```fuzzy_del``` ignores the given flag, which would reflect my current debugging results with the HTTP endpoint ```fuzzydel```

The [author of rspamd also says](https://github.com/rspamd/rspamd/issues/489#issuecomment-173009533) that the recommended workflow would be to delete it in the first place and then adding it afterwards.

To check my understanding I asked in the rspamd Telegram Chat and someone kindly looked into this and came to the same result, [that ```fuzzy_del``` is deleting hashes regardless of the flag](https://t.me/rspamd/13808).

I could see that the issue occurs in: https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.quarantine.inc.php#L678

I tred to fix this bug by myself, but since I'm not a PHP developer all attempts failed and resulted in a blank white page when opening the quarantine in mailcow.
When switching just the commands fuzzyadd<-->fuzzydel and leaving the error handling code to the wrong command, everything is fine and the bug seems to be fixed. Bu I think this would not be the best option since the error handling would not reflect the new order.

If you think that this is really a bug and I can do something for you (e.g. testing), please let me know!

Thank you for your hard work and I wish you a pleasant weekend with your family :)

**Docker container logs of affected containers**:

There are no error logs associated to this bug. 

**Reproduction of said bug**:

1. Add or search an email in quarantine that does not have any fuzzy hashes from rspamd.
2. Check that it really does not have any stored fuzzy hashes using the Scan/Learn feature from the rspamd GUI.
3. Upload/add a fuzzy hash for that message using the rspamd GUI, flag=11, wieght=10
4. Rescan the message to check that the fuzzy hash was added successfully (maybe wait for the rspamd sync job to take place)
5. Go to the mailcowe quarantine panel and manully learn this one message.
6. Go to Scan/Learn in rspamd again and check if the fuzzy hash was deleted

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4GB, 1vCores |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Oh, interesting. Thanks for that. I will work on it later or tomorrow. :)

**Comment by andryyy** [comment]
Thank you, should be fixed. Can you confirm?

**Comment by dragoangel** [comment]
Also one question: if we delete fuzzy from any flag and then add it back, what will be with votes(score multiplayer)? It will be staying at low point or they will still growing?

**Comment by andryyy** [comment]
It will be fully removed and added back. 

We could stop deleting it, but I'm not sure I like that idea.

**Comment by dragoangel** [comment]
So if I manually learn up to maximum one fuzzy and someone else get such fuzzy email in quarantine he click learn as spam and badooms my 15 score changes to 8? If I understand correctly. This sounds not right.

**Comment by Clevero** [comment]
I do think we should remove the old hashes as the first step. E.g. maybe its currently on the whitelist for whatever reason and shold now blacklisted.

Also to answer the question from @dragoangel : In my personal understanding, deleting and then adding would allow to further increase the amount of fuzzy hashes.
For example:
message1 consists of the fuzzy hashes A, B, C
message2 consists of the fuzzy hashes D, B, E
So, 1 would be different from header (A) and footer(C) but the middle (B) is the same.

Deleting the message2 and his fuzzy hashes would leave A and C from message1.
After that it would regenerate the hashes for message2 (D, B, E) and add it back.

Learning message3 (consisting of X, Y, Z) would just remove his fuzzy hashes and then adding it to the DB.
The hashes for the steps adding and deleting sould be created on the fly since you pass the full message and not the hashes you want to add/delete.


@andryyy I can confirm that this fixed the bug. Thanks 🙏
