### ISSUE TITLE
dovecot build on arm64 returns E: Unable to locate package dovecot-lua

### ISSUE THREAD

**Issue by guysoft** [mailcow/mailcow-dockerized#3845]
Hey, I am trying to build an arm64 bit build, this is the only container so far I am stuck with.

The issue is that dovecode only provide amd64 build on this repo:
https://repo.dovecot.org/ce-2.3.11.3/debian/buster/dists/buster/main/

**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ X ] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [ X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

When building for arm64 I get the error:

```
Executing: /tmp/apt-key-gpghome.STnxd4Mzts/gpg.1.sh --fetch-keys https://repo.dovecot.org/DOVECOT-REPO-GPG
gpg: requesting key from 'https://repo.dovecot.org/DOVECOT-REPO-GPG'
gpg: key 18A348AEED409DA1: public key "Dovecot Community Edition <dovecot-ce@dovecot.org>" imported              
gpg: Total number processed: 1                                                                                   
gpg:               imported: 1                                                                                   
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://repo.dovecot.org/ce-2.3.11.3/debian/buster buster InRelease [1745 B]
Fetched 1745 B in 1s (1290 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dovecot-lua
The command '/bin/sh -c groupadd -g 5000 vmail   && groupadd -g 401 dovecot   && groupadd -g 402 dovenull   && groupadd -g 999 sogo   && usermod -a -G sogo nobody   && useradd -g vmail -u 5000 vmail -d /var/vmail   && useradd -c "Dovecot unprivileged user" -d /dev/null -u 401 -g dovecot -s /bin/false dovecot   && useradd -c "Dovecot login user" -d /dev/null -u 402 -g dovenull -s /bin/false dovenull   && touch /etc/default/locale   && apt-get update   && apt-get -y --no-install-recommends install   apt-transport-https   ca-certificates   cpanminus   cron   curl   dnsutils   dirmngr   gettext   gnupg2   jq   libauthen-ntlm-perl   libcgi-pm-perl   libcrypt-openssl-rsa-perl   libcrypt-ssleay-perl   libdata-uniqid-perl   libdbd-mysql-perl   libdbi-perl   libdigest-hmac-perl   libdist-checkconflicts-perl   libencode-imaputf7-perl   libfile-copy-recursive-perl   libfile-tail-perl   libhtml-parser-perl   libio-compress-perl   libio-socket-inet6-perl   libio-socket-ssl-perl   libio-tee-perl   libipc-run-perl   libjson-webtoken-perl   liblockfile-simple-perl   libmail-imapclient-perl   libmodule-implementation-perl   libmodule-scandeps-perl   libnet-ssleay-perl   libpackage-stash-perl   libpackage-stash-xs-perl   libpar-packer-perl   libparse-recdescent-perl   libproc-processtable-perl   libreadonly-perl   libregexp-common-perl   libsys-meminfo-perl   libterm-readkey-perl   libtest-deep-perl   libtest-fatal-perl   libtest-mock-guard-perl   libtest-mockobject-perl   libtest-nowarnings-perl   libtest-pod-perl   libtest-requires-perl   libtest-simple-perl   libtest-warn-perl   libtry-tiny-perl   libunicode-string-perl   liburi-perl   libwww-perl   lua-sql-mysql   mariadb-client   procps   python3-pip   redis-server   supervisor   syslog-ng   syslog-ng-core   syslog-ng-mod-redis   && apt-key adv --fetch-keys https://repo.dovecot.org/DOVECOT-REPO-GPG   && echo "deb https://repo.dovecot.org/ce-${DOVECOT}/debian/buster buster main" > /etc/apt/sources.list.d/dovecot.list   && apt-get update   && apt-get -y --no-install-recommends install   dovecot-lua   dovecot-managesieved   dovecot-sieve   dovecot-lmtpd   dovecot-ldap   dovecot-mysql   dovecot-core   dovecot-pop3d   dovecot-imapd   dovecot-solr   && pip3 install mysql-connector-python html2text jinja2 redis   && apt-get autoremove --purge -y   && apt-get autoclean   && rm -rf /var/lib/apt/lists/*   && rm -rf /tmp/* /var/tmp/* /etc/cron.daily/* /root/.cache/' returned a non-zero code: 100
```
**Reproduction of said bug**:

Run on an arm64 ``docker build`` for the dovecot container
**System information**:

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
Using latest master
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

-- Irrelevant

**Comment by mkuron** [comment]
We need up-to-date Dovecot packages, so we use the Dovecot repo instead of the packages from Ubuntu/Debian. As long as Dovecot doesn‘t build arm64 packages, Mailcow cannot run on arm64.

There may be other pieces of Mailcow that don‘t currently work on non-amd64. We don‘t consider this a huge issue as arm64 cloud servers are typically not much cheaper to rent than amd64. It‘s still difficult to buy arm64 servers for your own datacenter, and you probably shouldn’t be running your mailserver on a Raspberry Pi on your home DSL line. Once arm64 actually becomes useful and available in the market, we would consider building our Docker images for that architecture too.

**Comment by 5hanth** [comment]
any plans for arm64 builds to run on hetzner arm64 servers.

**Comment by MAGICCC** [comment]
> any plans for arm64 builds to run on hetzner arm64 servers.

Yes arm64 is supported since one year https://mailcow.email/posts/2024/release-2024-01/
