### ISSUE TITLE
 Mailchimp: Prevent SPOOFED_UNAUTH

### ISSUE THREAD

**Issue by ddeenniiss** [mailcow/mailcow-dockerized#3846]
Describe the bug
Despite a dns configuration that seems to be correct, my mailing sent from mailchimp are rejected for @domain.tld addresses .

The mailing is sent with

From: xxx@domain.tld
Reply-To: us10-e309f52506-131f943aea@inbound.mailchimp.com

[75.79/15.00] [SPOOFED_UNAUTH(50.00){},POLICY_FAILURE(10.00){},NEURAL_SPAM_LONG(3.70){1.000;},FORGED_W_BAD_POLICY(3.00){},BAYES_SPAM(2. 50){100.00%;},BAD_REP_POLICIES(2.00){},DMARC_POLICY_SOFTFAIL(2.00){domain.tld: SPF not aligned (relaxed), DKIM not aligned (relaxed);none;

My dns config for domain.tld

SPF
v=spf1 a mx a:domain.tld ip4:xx.xx.xx.xx ip6:xx:xx:xx:xx::x include:servers.mcsv.net ?all

CNAME
k2._domainkey dkim2.mcsv.net.
k3._domainkey dkim3.mcsv.net.

DMARC
_dmarc v=DMARC1; p=none; rua=mailto:info@xxx.xx; pct=100; ruf=mailto:xxx.xx; fo=0:d:s; aspf=r; adkim=r;

**Comment by MangoCubes** [comment]
You do have DKIM TXT record up, right?

**Comment by ddeenniiss** [comment]
My setup:

k2._domainkey 	CNAME - Name Alias 	dkim2.mcsv.net. 	DKIM Mailchimp
k3._domainkey 	CNAME - Name Alias 	dkim3.mcsv.net. 	DKIM Mailchimp

As requested here: https://mailchimp.com/en/help/set-up-custom-domain-authentication-dkim-and-spf/

**Comment by vnukhr** [comment]
Hard to tell if it's the same issue but more weird, or eerily similar. 

Mandrill emails for a domain hosted on mailcow are being received normally, except from one sender (client server, not Mandrill server). I've had to reduce score (disable) SPOOFED_UNAUTH to avoid disruption. 

Example of email bounce
![bounced](https://user-images.githubusercontent.com/7805987/100428787-aff08280-3094-11eb-87c1-179976c47d6b.png)

Example of email accepted 
![not-bounced](https://user-images.githubusercontent.com/7805987/100428825-bda60800-3094-11eb-8716-abe7c67a2985.png)

**Comment by andryyy** [comment]
SPOOFED_UNAUTH would not have triggered if DKIM_REJECT was not inserted. It triggers only because of a positive score in the policy group (spf, dkim, etc.).

**Comment by vnukhr** [comment]
Does that mean Mandrill is doing something wrong with DKIM signing? I can grab headers for the bounced mail on gmail if that'll help?

**Comment by andryyy** [comment]
You need to setup the DKIM according to their docs.

**Comment by vnukhr** [comment]
How can DKIM setup for a domain (informacija.hr) be wrong and correct at the same time? Two emails 10 seconds apart, one passes DKIM one doesn't? 

I receive about a hundred emails daily from Mandrill to this domain, only one mail gets bounced. Only difference (that I can tell) is that email is sent (via Mandrill) from a host that triggers RECEIVED_SPAMHAUS_CSS.

**Comment by andryyy** [comment]
There can be various reasons. I cannot help you here with that. Recheck it again. Could be a DNS propagation delay for example etc.

**Comment by vnukhr** [comment]
Thanks for your help, I've whitelisted all Mandrill/Mailchimp IPs for now, hopefully we'll figure out source of this behaviour in the future.

Mandrill on the domain in question is couple of years old and definitely not the issue here. 
Only thing that's changed recently is mailcow as recipient.

**Comment by andryyy** [comment]
I'm not saying they have a broken signature.

The mail is probably modified on its way.

We don't include mail support with mailcow (obviously), but you can contact us at info@servercow.de for hands-on support.
