### ISSUE TITLE
quarantine show item display issue

### ISSUE THREAD

**Issue by mightyBroccoli** [mailcow/mailcow-dockerized#3847]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Clicking the "Show Item" button for a specific item in the quarantine sometimes does not show the email contents or displays the summary of another email in the quarantine.
When that happens all emails I try to view the details to, display the same info.

## Logs

There are no loglines regarding this issue.

## System information

| Question | Answer |
| --- | --- |
| My operating system | ArchLinux |
| Is Apparmor, SELinux or similar active? | yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | no |
| Server/VM specifications (Memory, CPU Cores) | 4 |
| Docker Version (`docker version`) | 19.03.13-ce |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Hi, when did you last update?
Can you write me to info@servercow.de and let me check the UI? Probably an easy fix.

**Comment by andryyy** [comment]
Or can you post the output of...

```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u$DBUSER -p$DBPASS $DBNAME -e "select fuzzy_hashes from quarantine;"
```

...first?

**Comment by mightyBroccoli** [comment]
I currently run on the b7956d8a commit, which I pulled yesterday.

The output of the query you asked for is this:
```
+--------------------------------------------------------------------------------------------------------------------------------------+
| fuzzy_hashes                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------+
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| []                                                                                                                                   |
| ["9a462bc271d7e796cd40364ad67201443f73371cf7d945cc1a9a811d3ed454f772305a23eb75cfd150e2898b80caad0e9d61718daca3f5b046e2cd3fb109547e"] |
| ["9a462bc271d7e796cd40364ad67201443f73371cf7d945cc1a9a811d3ed454f772305a23eb75cfd150e2898b80caad0e9d61718daca3f5b046e2cd3fb109547e"] |
+--------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by andryyy** [comment]
Hm. Okay, can I check the UI?

**Comment by andryyy** [comment]
You can also send me a dump of the table, if you like. And if there is no sensible data in it.

**Comment by mightyBroccoli** [comment]
I sent you an Email with the subject Github Issue 3847.
