### ISSUE TITLE
PostFix using IPV6 address from DNS

### ISSUE THREAD

**Issue by clemenko** [mailcow/mailcow-dockerized#3852]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [ X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Sending to Comcast I am getting the IPV6 DNS when i have ipv6 disabled on the host AND within mailcow. 

## Logs

`(connect to mx2.comcast.net[**2001:558:fe21:2a::6**]:25: Cannot assign requested address)`

All other mail is flowing correctly with ipv4.

```
root@mail:/opt/mailcow-dockerized# git diff origin/master
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index e8da7947..460b3bd2 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -172,7 +172,6 @@ smtpd_milters = inet:rspamd:9900
 non_smtpd_milters = inet:rspamd:9900
 milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
 mydestination = localhost.localdomain, localhost
-smtp_address_preference = any
 smtp_sender_dependent_authentication = yes
 smtp_sasl_auth_enable = yes
 smtp_sasl_password_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_sasl_passwd_maps_sender_dependent.cf
@@ -199,3 +198,4 @@ smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
 
+smtp_address_preference = ipv4
diff --git a/data/conf/unbound/unbound.conf b/data/conf/unbound/unbound.conf
index 27110c04..90c16ee0 100644
--- a/data/conf/unbound/unbound.conf
+++ b/data/conf/unbound/unbound.conf
@@ -4,7 +4,7 @@ server:
   interface: ::0
   logfile: /dev/console
   do-ip4: yes
-  do-ip6: yes
+  do-ip6: no
   do-udp: yes
   do-tcp: yes
   do-daemonize: no
diff --git a/docker-compose.yml b/docker-compose.yml
index d9251a28..71f32adf 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -550,7 +550,7 @@ networks:
     driver: bridge
     driver_opts:
       com.docker.network.bridge.name: br-mailcow
-    enable_ipv6: true
+    enable_ipv6: false
     ipam:
       driver: default
       config:
```

## Reproduction
Not sure the best way to reproduce. 

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | N/A - DigitalOcean |
| Server/VM specifications (Memory, CPU Cores) | 1 core x 3gb ram |
| Docker Version (`docker version`) |  19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | N/A |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

```
root@mail:~# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.65.69
151.101.129.69
151.101.193.69
151.101.1.69
```

```
root@mail:~# docker exec -it $(docker ps -qf name=postfix-mailcow) dig +short mx2.comcast.net @172.22.1.254
68.87.20.5
root@mail:~# docker exec -it $(docker ps -qf name=postfix-mailcow) dig +short mx1.comcast.net @172.22.1.254
96.114.157.80
```

Diff is above.

**Comment by clemenko** [comment]
Disabling IPV6 on the host breaks all the containers and they won't start.

**Comment by andryyy** [comment]
Regarding disabling IPv6 on the host: yes, that's expected. 

Can you try `inet_protocols = ipv4` in extra.cf?

**Comment by clemenko** [comment]
Much better results. on to to the next problem. thanks
