### ISSUE TITLE
Apple Configuration Profile damaged

### ISSUE THREAD

**Issue by thomas126** [mailcow/mailcow-dockerized#3853]
Hi guys,

I am struggling to get my setup working on my iPad. Especially the mail/contacts/calendar option. Tried to use the Apple profiles from within the web interface of mailcow. Which seems to be damaged. At least I get that error output. When trying to set a calendar manually I also get an error.

**Comment by patschi** [comment]
Ignored all templates, therefore closing issue. Use the [community forum](https://community.mailcow.email/) instead.
