### ISSUE TITLE
Sender-dependent transport ignored when "Relay this domain" is active

### ISSUE THREAD

**Issue by ruffy91** [mailcow/mailcow-dockerized#3854]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Set a Sender-dependent transport and Relay this domain as well as Relay all recipients and then send an authenticated SMTP mail to a recipient in this domain the Sender-dependent transport is not used but the mail is sent out using the MX record for this domain instead.
![image](https://user-images.githubusercontent.com/344634/99049070-b19b5000-2596-11eb-9f91-dcd2efe503fe.png)

This is on commit bafbbe1fe18b69fc32f481a41f06929abb785abe (October 12th)

## Logs

11/13/2020, 09:11:46 AM	info	6446630070C: to=<userb@example.com>, relay=mx.example.com[<anonymized>]:25, delay=2.7, delays=2.5/0/0.08/0.11, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 5806410003087)
11/13/2020, 09:11:45 AM	info	6446630070C: replace: header Received: from RB16PRT201 (<anonymized>.static.wline.lns.s: Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPSA id 6446630070C??for <userb@example.com>; Fri, 13 Nov 2020 09:11:43 +0100 (CET)
11/13/2020, 09:11:45 AM	info	6446630070C: from=<usera@example.com>, size=390457, nrcpt=1 (queue active)
11/13/2020, 09:11:43 AM	info	6446630070C: message-id=<bd9bG.0000@da00c73b-2587-11eb-8000-9c934e90b08c>
11/13/2020, 09:11:43 AM	info	6446630070C: client=<anonymized>.static.wline.lns.sme.cust.swisscom.ch[<anonymized>], sasl_method=LOGIN, sasl_username=usera@example.com

## Reproduction

1. Add a domain example.com (example.com has an MX record of mx.example.com)
Set a sender dependent transport to [transport.example.com]:25
Set Relay this domain and Relay all recipients on example.com
Send a mail from usera@example.com authenticated via SMTP (exists on this mailcow) to userb@example.com (does not exist)
The mail is sent to mx.example.com instead of tranport.example.com

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.1 LTS |
| Is Apparmor, SELinux or similar active? | apparmor Ubuntu default profiles |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware |
| Server/VM specifications (Memory, CPU Cores) | 2 Cores, 4 GB RAM |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) |  1.27.4 |
| Reverse proxy (custom solution) | none |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
-    enable_ipv6: true
+    enable_ipv6: false
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by vista0815** [comment]
Confirm - the bug is still there.
I can not mirgrate to mailcow because I have some accounts on web.de and gmx.de, with differnet users.
Wehen the domain web.de is added and Sender-dependent transport for a user is activated mails will still send with the "default" server mx and not via Sender-dependent transport (web.de account)

**Comment by andryyy** [comment]
Not really a bug. I don't see the use case here.

You are relaying a domain and using web.de or gmx.de (!) as relays? You should never use these servers as relay for your personal domains.

**Comment by blitzdesigner** [comment]
this is actually still not working. I have the same situation.
@andryyy we do not want to use the gmx/web.de SMTP for other personal domains, but for the actual gmx adress.
So the process should be Client -> Mailcow -> SMTP of GMX/WEB.de -> mx of receiving domain
Idea is that the client never has direct contact with GMX/WEB.de, all mail is handeled on the cow circumventing storage limitations and makes setup easier. 

But it actually is a general issue, as mailcow obviously completely ignores the settings in sender depenedet transport maps. It is just not using them at all and tries to send irectly to the mx of the receiving domain what obviously fails (SPF hard fail).
right now I have to use the GMX/WEB.de SMTP directly in the client, that works, true, but as there is the option of smarthosts, they should work, right?

**Comment by andryyy** [comment]
If you want to use the actual gmx/web address, use their SMTP directly. :)

Alternatively you need to properly rewrite the envelope and header of course. Per sender.
I hope you **did not** (!) setup gmx.de in your mailcow.

If you didn't my previous point stands: You are authenticating to your mailcow with a mailcow domain, then forwarding that message to the (hopefully authenticated against) GMX server. You need to rewrite the header and envelope from.

There are options to use smarthosts, yes, but that doesn't mean all rules don't apple anymore. :)
