### ISSUE TITLE
Watchdog ALERT: certcheck - Message is repeated several times in the body

### ISSUE THREAD

**Issue by jaltek** [mailcow/mailcow-dockerized#3855]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
The message about the expiration in the mail body from the watchdog certcheck is repeated several times.
Screenshot from the email inside Thunderbird:
![grafik](https://user-images.githubusercontent.com/359552/99061474-e7920180-25a1-11eb-9d2d-958bca88c52e.png)

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.5 LTS |
| Is Apparmor, SELinux or similar active? | Apparmor active |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2 GB, 1 core |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4, build 40524192 |

**Comment by jaltek** [comment]
Just as a small follow-up: This seems not only related to certcheck:

![Selection_066](https://user-images.githubusercontent.com/359552/101165439-f4e95b80-3636-11eb-886e-496b65c962a6.png)

**Comment by andryyy** [comment]
That's wanted. It inserts the last n results of the check.

**Comment by jaltek** [comment]
Oh...well...ok, thanks for the clarification ;)
