### ISSUE TITLE
rspamd UI: Throughput stats cannot be read

### ISSUE THREAD

**Issue by snhrdt** [mailcow/mailcow-dockerized#386]
The throughput stats data cannot be read from the rrd db anymore:

![screen shot 2017-06-22 at 12 04 16](https://user-images.githubusercontent.com/21608/27432761-e0c4738c-5751-11e7-8026-86eef1f61284.png)

I see the following line in the rspamd log file:
```
rspamd-mailcow_1     | 2017-06-22 11:54:14 #10(controller) <01bc3a>; csession; rspamd_controller_handle_graph: no rrd configured
```

The system has been updated to the latest commit on master, images re-pulled: 98e77fe791b27bcca60eaf1cd8951de3af31bcaf

I checked `generate_config.sh`whether there is a new configuration item to be set, and I grep'ed the `/data` folder to see whether there is a setting somewhere related to rrd but could not find one.
 
If you need more information, please let me know.

**Comment by andryyy** [comment]
Sorry, I merge the fix to master now.
