### ISSUE TITLE
docker pull rate limit

### ISSUE THREAD

**Issue by MyUncleSam** [mailcow/mailcow-dockerized#3863]
Docker limited the pull rate of containers. (https://www.docker.com/increase-rate-limit)

Today I wanted to do an update and it seems like mailcow is pulled too often:

> Prefetching images...
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 
> Error pulling mailcow/unbound:1.12, retrying...
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 
> Error pulling mailcow/unbound:1.12, retrying...
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 
> Error pulling mailcow/unbound:1.12, retrying...
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> 
> Error pulling mailcow/unbound:1.12, retrying...
> 
> Too many failed retries, exiting

If I see it correctly this only can be fixed by an paid plan which starts at 5$ per month.

Time of the error was at 09:20 o'clock german time.

**Comment by andryyy** [comment]
That's a feature request? 

I think the limit is fair: "250 per six hours"

You can pull mailcow quite often before hitting that limit. If you pull more than 250 images per six hours, you might want to pay them the 5 USD for their service. :)

**Comment by MAGICCC** [comment]
Also please reread the article you linked. mailcow itsself is not ratelimited, it's your IP
You may setup a caching for your setup

**Comment by MyUncleSam** [comment]
Yes I read it wrong. In my scenario watchdog pulled too often for other containers (not mailcow).
