### ISSUE TITLE
Error after trying to save any regex map

### ISSUE THREAD

**Issue by Gabriel-Guimaraes** [mailcow/mailcow-dockerized#3876]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After updating the mailcow instance today, 28-11-2020 in commit ba20db2e086aeaaffbd101f37c056b25dfb3d2d4 every time I try to save a regex map after validating it shows the following error message: 

![image](https://user-images.githubusercontent.com/36351804/100528054-27b6ce00-31b7-11eb-8563-de63a9d431bd.png)

## Logs

  | "An  unknown error occured: Error Object\n(\n    [message:protected] =>  Call to undefined function rspamd()\n    [string:Error:private] => \n     [code:protected] => 0\n    [file:protected] =>  \/web\/json_api.php\n    [line:protected] => 1553\n     [trace:Error:private] => Array\n        (\n        )\n\n     [previous:Error:private] => \n)\n"
-- | --

## Reproduction
It happens every time trying to save any regex map

## System information

| Question | Answer |
| --- | --- |
| My operating system | ubuntu server 20.04 |
| Is Apparmor, SELinux or similar active? |no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** |no|
| Server/VM specifications (Memory, CPU Cores) | 4 GB 2 Vcpu |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | - |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Thank you! I will fix it later. Need a coffee first. :) Overlooked this.
