### ISSUE TITLE
API documentation errors for Edit Domain Ratelimits

### ISSUE THREAD

**Issue by karimelc** [mailcow/mailcow-dockerized#3880]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
There are som errors in the Api documentation at https://mailcow.docs.apiary.io/#reference/ratelimits

In the Edit Domain Ratelimits section, I have found the following errors in order to use this API call (I'm using the cURL example):

--request should be POST instead of GET
--data-binary section is not formatted correctly, it should look like this (note the placement of [] and {}):

`     --data-binary "{
      \"attr\":
        {
          \"rl_value\": \"10\",
          \"rl_frame\": \"h\"
        },
      \"items\":[\"info@domain.tld\"]
}" \
`

My mailcow instance is on commit a739440 from Nov 6, 2020.

## Logs
Using the API as documented yields: {"type":"error","msg":"only POST method is allowed"}
Changing method to POST yields: {"type":"success","msg":"Task completed"} but the mailbox ratelimit is not updated.
Using the API with the changes above yields: [{"type":"success","log":["ratelimit","edit","mailbox",{"object":["info@domain.tld"],"rl_value":"10","rl_frame":"h"}],"msg":["rl_saved","info@domain.tld"]}] and the mailbox ratelimit is updated correctly.

## Reproduction
Simply use the API Edit Domain Ratelimits as documented with cURL.

## System information

| Question | Answer |
| --- | --- |
| My operating system | CentOS Linux 7 |
| Is Apparmor, SELinux or similar active? | Yes, SELinux |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware |
| Server/VM specifications (Memory, CPU Cores) | 4GB RAM, 2 vCPU |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 build 40524192 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Thank you. :)

Ping @ntimo

**Comment by ntimo** [comment]
It should now be fixed :)
