### ISSUE TITLE
alias persistent after deletion

### ISSUE THREAD

**Issue by Tupsi** [mailcow/mailcow-dockerized#3881]

**Comment by Tupsi** [comment]
of course AFTER opening that issue I found the issue, which in fact was just my bad self, so I deleted it. Sorry for that.

**Comment by MAGICCC** [comment]
Maybe don't delete the bug template which were given to you?

EDIT: okie
You may want to explain what you did

**Comment by andryyy** [comment]
Sometimes aliases are lazy cached. :) May take a few moments for Postfix to catch up.

**Comment by Tupsi** [comment]
no guys, its fine, it was my own stupidity, nothing from the server end. It did exactly what I told it todo I just found out only AFTER posting this, so sorry for stealing your time. Turned out I had an entry under address rewriting, even though I wasn't even aware trying that option!

**Comment by andryyy** [comment]
No worries! :)
