### ISSUE TITLE
No documentation for time limited aliases API calls

### ISSUE THREAD

**Issue by nogweii** [mailcow/mailcow-dockerized#3889]
## Summary

There is no documentation in the OpenAPI YAML about `time_limited_alias`. Because of that, I thought there wasn't an API at all but investigating the HTML did reveal there is one.

## Motivation

I was hoping to build a Firefox extension that can generate and inject a temporary email into a form field from the context menu. Making it super easy to use the feature.

**Comment by gacott** [comment]
I need this as well.

**Comment by andryyy** [comment]
Can you check that, @ntimo ? :)

**Comment by gacott** [comment]
@ntimo any chance you could just leave it here? I see in an update of last year that you worked on this and it is working. We just need some specifics of what is required to pull it off with the API. Thanks VERY much!

**Comment by ankitkumarlalan** [comment]
@ntimo 
Till the time you finish creating those documents, could you just share the endpoint with the request body that we need to pass? This is urgent for us to get done. Appreciate your response.

**Comment by andryyy** [comment]
If it's urgent you can also check the API/UI logs in the mailcow UI.

**Comment by ankitkumarlalan** [comment]
Hello @andryyy, Thanks for your response. Looking at the logs, I made a following POST request and returns me an error. Can you suggest something?

![image](https://user-images.githubusercontent.com/47514573/112192592-337b4400-8c2f-11eb-807f-2f8f7335f197.png)
![image](https://user-images.githubusercontent.com/47514573/112192623-3c6c1580-8c2f-11eb-9da7-58c873362809.png)
