### ISSUE TITLE
acme is unable to detect my ipv6 address

### ISSUE THREAD

**Issue by heino-vdbh** [mailcow/mailcow-dockerized#3897]
OS: CentOs Stream 8
docker 20.10
containerd 1.4.3

Today I updated my system (yum update) and mailcow (update.sh)
Both runs without problems but when I start mailcow I get the following errors from the acme container.

Fri Dec 11 23:46:53 CET 2020 - OK: 85.235.64.174, 0000:0000:0000:0000:0000:0000:0000:0000
Fri Dec 11 23:46:53 CET 2020 - Found AAAA record for autodiscover.purzel.net: 2a03:4000:32:639:d4e2:74ff:fe1d:b70b - skipping A record check
Fri Dec 11 23:46:53 CET 2020 - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autodiscover.purzel.net (DNS returned 2a0
3:4000:0032:0639:d4e2:74ff:fe1d:b70b)

**Comment by heino-vdbh** [comment]
IP detection on host works but not in the container

**Comment by Zipdox2** [comment]
How did you solve it?

**Comment by ghost** [comment]
@heino-vdbh any hints ?

**Comment by hydrandt** [comment]
I also have this problem.

**Comment by Goury** [comment]
hello?
