### ISSUE TITLE
greylist.conf overwritten after update

### ISSUE THREAD

**Issue by karimelc** [mailcow/mailcow-dockerized#3898]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

After performing an update today to the latest: fd38df4 from: a739440 changes to the file data/conf/rspamd/local.d/greylist.conf were lost (I had greylisting disabled via enabled = false;). Greylisting was disabled according to the section "Disable Greylisting " in the documentation. 

## Logs
Output from the update.sh script:

Auto-merging data/conf/rspamd/local.d/greylist.conf
Auto-merging data/conf/dovecot/dovecot.conf
Merge made by the 'recursive' strategy.
 .github/FUNDING.yml                                                              |     1 +
 .github/ISSUE_TEMPLATE/Bug_report.md                                             |    23 +-
 .github/ISSUE_TEMPLATE/Feature_request.md                                        |    33 +-
 .github/ISSUE_TEMPLATE/config.yml                                                |     8 +
 .gitignore                                                                       |     1 -
 data/Dockerfiles/clamd/clamd.sh                                                  |     1 +
 data/Dockerfiles/dovecot/docker-entrypoint.sh                                    |     3 +-
 data/Dockerfiles/dovecot/quarantine_notify.py                                    |    35 +-
 data/Dockerfiles/postfix/postfix.sh                                              |     8 +-
 data/Dockerfiles/sogo/bootstrap-sogo.sh                                          |     3 +-
 data/conf/dovecot/dovecot.conf                                                   |     5 +
 data/conf/nginx/includes/site-defaults.conf                                      |     4 +-
 data/conf/rspamd/local.d/composites.conf                                         |     8 +-
 data/conf/rspamd/local.d/greylist.conf                                           |     4 +-
...

My changes to dovecot.conf were correctly merged after the update.

## Reproduction
Run update.sh

## System information

| Question | Answer |
| --- | --- |
| My operating system | CentOS Linux 7 |
| Is Apparmor, SELinux or similar active? | Yes, SELinux |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware |
| Server/VM specifications (Memory, CPU Cores) | 4GB RAM, 2 vCPU |
| Docker Version (`docker version`) | 20.10.0, build 7287ab3 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4, build 40524192 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Use the update.sh script with "ours" policy on your own risk. We cannot handle every possible change of every component that each user may have implemented, sorry.

**Comment by karimelc** [comment]
Got it, thank you!

**Comment by andryyy** [comment]
Sorry there is no better solution. :(
