### ISSUE TITLE
Error if I update Domains

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#39]
Hi,

I've added a domain via the admin panel. Everything looked good. Then I wanted to increase the quota for this domain and I received the following error message:

`MySQL: PDOException: SQLSTAE[HY093]: Invalid parameter number in /web/inc/functions.inc.php:3452 Stack trace: #0 /web/inc/functions.inc.php(3452): PDOStatement->execute(Array) #1 /web/inc/triggers.inc.php(143): mailbox_edit_domain(Array) #2 /web/inc/prerequisites.inc.php(95): require_once('/web/inc/trigge...') #3 /web/mailbox.php(2): require_once('web/inc/prereq...') #4 {main}`

If I now want to change any Domain, a white page appears with only the number 3072.

Thanks for your help.

**Comment by andryyy** [comment]
Hi,
Just fixed it. :-) Am 03.02.2017 um 08:44 schrieb rebek86:
Hi,
I've added a domain via the admin panel. Everything looked good. Then I wanted to increase the quota for this domain and I received the following error message:
MySQL: PDOException: SQLSTAE[HY093]: Invalid parameter number in /web/inc/functions.inc.php:3452 Stack trace: #0 /web/inc/functions.inc.php(3452): PDOStatement->execute(Array) #1 /web/inc/triggers.inc.php(143): mailbox_edit_domain(Array) #2 /web/inc/prerequisites.inc.php(95): require_once('/web/inc/trigge...') #3 /web/mailbox.php(2): require_once('web/inc/prereq...') #4 {main}
If I now want to change any Domain, a white page appears with only the number 3072.
Thanks for your help.

**Comment by rebek86** [comment]
Thanks :-)
