### ISSUE TITLE
Improve API for rl_frame and add option "d"

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3906]
## Summary

I checked this domain - https://mailcow.docs.apiary.io/#reference/domains/create-domain/create-domain - for creating and optimizing my server scripts. I can see, there are limits per Second, Minute and Hour. But in WebGUI i also have the "per Day" Option. This is missing in API or the docs are not up-to-date?

## Motivation

With this the API has the same functions as the WebGUI and we can use the API to create good scripts with full functions.

**Comment by andryyy** [comment]
@ntimo Can you add it? :)

**Comment by ntimo** [comment]
Sure I will add it 👨‍💻

**Comment by ntimo** [comment]
Hey,
I have now added the missing flag to the API docs :) 
https://github.com/mailcow/mailcow-apiblueprint/commit/9d41ebc665361636fac258db76cc6063fe7a5a34

**Comment by tobias992** [comment]
Cool, thank you very much.

**Comment by andryyy** [comment]
Danke, Timo!!!
