### ISSUE TITLE
name=dovecot type=AAAA: Host not found

### ISSUE THREAD

**Issue by stAn47** [mailcow/mailcow-dockerized#3910]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## System information

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

hello, after the last update my nginx did not want to start, so i enabled watchdog and it all started well. but now i see lot's of refused delivered emails in mailqueue with these:

```
<user@{somehting}.com>: Host or domain name not found. Name service error for
    name=dovecot type=AAAA: Host not found
```

this email address receives up to 1000 emails per minute and it is possible it got rate limited somewhere at the system. 
the domain did not use IPv6 at all, but i now enabled it as part of the problem fixing. There is a new line between for and name, so it possibly is missing something. 

i would like to know where to locate all rate-limiting which could produce this error. my best guess is that the DNS system is rate limited within ubound itself. 

why would a failed DNS for localdomain refuse the delivery of the email ? this email address uses purely spam-skip IP addresses (can receive only whitelisted IPs and networks) as it is used to collect alerts from different servers. 

generally i would be very glad if there was a documentation that lists limits. i don't think same configuration can be used for mail system with 10 active connections and with 200 active connections. also the way it utilizes nginx + php + spamd and many other remote calls it is possible that each received email does up to 20 connections of which 10 is DNS calls/

thank you, 
best regards, stan

**Comment by andryyy** [comment]
Hi,

If you want to report a bug, post logs, fill out the issue template and tell us how to reproduce it. 

Imo this is more a question. This is not the correct place for support or questions I'm afraid. 

Please attach logs, nobody will be able to help without information.

**Comment by stAn47** [comment]
hello andryy, thank you for you fast reply and good job on this project. i now purchased your support subscription even though german checkout is quite tricky and i would like to see a VAT free invoice so i don't need to pay VAT twice (as i pay VAT from all received invoices locally)

we can have a look on my rate-limit problem in january, it only concerns one of my accounts which is under heavy load. 

i cannot really post the logs here as i am not sure how to anonymize them, but i'll have a few questions and maybe i can help you with a few aspects of the system as PHP/JS developer and linux admin. 

the failed upgrade which left nginx not working is not a problem at the moment as i must had it fixed in 10 minutes so it is working all ok as the logs were complaining about the watchdog missing as far as i remember and i furthermore adjusted all configs to use the new docker IPs. 

thank you, best regards, stan

**Comment by andryyy** [comment]
Hi,

No problem. The watchdog warning is not related, it was probably just coincidence it started working when you run "up -d" again.

I removed the tax, the ID was not properly validated at first.

This is not really a rate limit problem. The "host not found" warning happened when Dovecot was not yet ready but Postfix tried to deliver mail. This kind of warning is a temp. reject, so Postfix will try to deliver again a few minutes later. There was probably a bunch of mail in the queue.

Just open a ticket when you are ready. 👍🏼 

André
