### ISSUE TITLE
API Points to edit Domain-Admin Functions (ACL)

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3911]
## Summary

At the moment only with WebUI its possible to edit the ACL from Domain Admins. Would be nice to also add API Points for this.
In my case for example i create Domain-Admins with API but i dont want allow to change the Rate Limit of this Domain. For now, for each new Domain in Mailcow i have to edit these Setting manual.

## Motivation

API is cool and very useful :)

**Comment by ntimo** [comment]
Hey,
There already is a API endpoint for this, here is a link to the docs:
https://demo.mailcow.email/api/#/Domain%20admin/Edit%20Domain%20Admin%20ACL

You can also open the docs on your on cow by opening https://< cow domain >/api/

**Comment by tobias992** [comment]
Thank you very much. I only checked this Domain:  https://mailcow.docs.apiary.io/#reference/domain-admin

Please can you check my cURL example?
Like this:  https://mailcow.docs.apiary.io/#reference/domains/update-domain/update-domain

https://ibb.co/fkJ4Ljd

And when i activate features i replace 0 with 1?

**Comment by ntimo** [comment]
```
curl -X POST "https://demo.mailcow.email/api/v1/edit/da-acl" -H "accept: application/json" -H "X-API-Key: apikey123456" -H "Content-Type: application/json" -d "{\"items\":[\"testadmin\"],\"attr\":{\"da_acl\":[\"syncjobs\",\"quarantine\",\"login_as\",\"sogo_access\",\"app_passwds\",\"bcc_maps\",\"pushover\",\"filters\",\"ratelimit\",\"spam_policy\",\"extend_sender_acl\",\"unlimited_quota\",\"protocol_access\",\"smtp_ip_access\",\"alias_domains\",\"domain_desc\"]}}"
```

**Comment by ntimo** [comment]
No you don't use 0 and 1 you just add or remove the acl from the array.

**Comment by tobias992** [comment]
Thank you. Got it.
