### ISSUE TITLE
Small Bug in Domain-Admin ACL (Sync)

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#3912]
This is a small bug -> there is really no template needed.
For a Domain-Admin i deleted the "Sync" functions.

When i login as Domain-Admin and go to tab "Sync" i see the lower "create new sync job" Button is disabled (by rule) and the upper one is still active and usable. So this Button also have to be disabled. Thats all. Attached one Picture.

https://ibb.co/mHjpDjb

Edit: The same problem has the "Domain Alias", "Filter" and "BCC-Map" Tab.

**Comment by andryyy** [comment]
Thank you. :) That's indeed more than enough.

**Comment by tobias992** [comment]
Hi,
thank you. But only the "Sync" Tab is fixed.

"Domain Alias", "Filter" and "BCC-Map" Tab has the same Bug.

**Comment by andryyy** [comment]
Oh, yes, didn't see your edit.

**Comment by tobias992** [comment]
Hi,
should i open an new issue for the last Tabs?

**Comment by andryyy** [comment]
Sorry, didn't push... :-( Fixed it.
