### ISSUE TITLE
ACME failing after updating to Docker 20.10

### ISSUE THREAD

**Issue by patschi** [mailcow/mailcow-dockerized#3915]
# Symptoms
- Your mailcow instance is based on code before 9th of December 2020.
- You have recently updated to Docker 20.10 on your system.
- ACME might fail requesting certificates, therefore resulting in expired certificate.
- In ACME log you see that `MAILCOW_HOSTNAME` is resolved to internal IP (where the public IP should be used):
```
acme-mailcow_1       | Wed Dec  9 06:29:57 CET 2020 - Cannot match your IP $PUBLIC_IP against hostname MAILCOW_HOSTNAME (DNS returned fd4d:6169:6c63:6f77:0000:0000:0000:000e)
```

# Explanation

This is caused due to changes in Docker 20.10.

# Resolution

1. Update your mailcow instance using `update.sh` (just as usual).
2. Check if new certificates are being issued. If not [you can force this](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#force-renewal).

The fix was implemented with commit 1311066089d523957e5906387b852fc12242b2b9 on Dec 9, 2020, 8:16 AM GMT+1.

# Additional information

The symptoms might be similar when having DNS issues, so not all issues with expired certificates are caused by this particular circumstances. If you use Docker 20.10, an up-to-date mailcow instance and still experience issues with renewing certificates, it's most likely something different.

As always, GitHub issues are used for bugs and not for support. For support [read this](https://mailcow.github.io/mailcow-dockerized-docs/#get-support).

---
FYI, this is for informational purposes and awareness as users might come across this particular trending issue in the future, specially when updating to Docker 20.10 and not updating mailcow in a timely manner. This is **NOT** a support thread.

**Comment by AudiWolf** [comment]
This issue is happening in my case too. The example error message is like this: sub.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname sub.domain.tld (real IPv6 address)

**Comment by ghost** [comment]
Can confirm I have the same issue. Disabled IPv6 for now and it works. But the issue issue is I have to identical mail-cow instance on the 2nd one is works with out any issues. Both Hetzner VPS behind the same firewall rules in Hetzner cloud.

**Comment by chriscroome** [comment]
Docker is now on [version 23.0.5](https://github.com/moby/moby/releases/tag/v23.0.5), why do you need to run such old versions?

**Comment by ghost** [comment]
> Can confirm I have the same issue. Disabled IPv6 for now and it works. But the issue issue is I have to identical mail-cow instance on the 2nd one is works with out any issues. Both Hetzner VPS behind the same firewall rules in Hetzner cloud.

Oops, my bad on my previous reply! 😅 There were quite a few grammatical errors in it. So, here's what actually happened:

I was running the latest version of Docker (when I posted the reply), but still had the same problem as mentioned earlier. I suspect that changing the external IPv4 and IPv6 addresses of my HETZNER VPS might have caused the issue. To fix it, I simply migrated my instance to a new VPS. I didn't take any logs or anything because I just wanted to get it sorted out quickly.

Hope that clears things up! Let me know if you have any other questions.
