### ISSUE TITLE
Error pulling mailcow/watchdog:1.86

### ISSUE THREAD

**Issue by hohlerde** [mailcow/mailcow-dockerized#3916]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Last update was on: 2020-11-14-19-42-45

Error pulling mailcow/watchdog:1.86, retrying...
Error response from daemon: manifest for mailcow/watchdog:1.86 not found: manifest unknown: manifest unknown

## Logs

The error happens while using update.sh.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.1 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4gb, 2 cores |
| Docker Version (`docker version`) | 20.10.1 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | yes |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by TimonZ98** [comment]
I'm facing the same problem at the moment and when I check the latest version of mailcow/watchdog that's available on Docker hub at https://hub.docker.com/r/mailcow/watchdog/tags?page=1&ordering=last_updated, I see that it's version 1.85. So, I guess it's just the version 1.86 which is missing on Docker hub. It would be nice if this version could be uploaded there, thanks in advance!

**Comment by andryyy** [comment]
Give it a minute. :)
