### ISSUE TITLE
Request to update the SOGo image

### ISSUE THREAD

**Issue by seanfarley** [mailcow/mailcow-dockerized#3919]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
There is a bug in SOGo where carddav (address book) doesn't work in MacOS 11 Big Sur. It has already been fixed in this commit: https://github.com/inverse-inc/sogo/commit/b9e19c2cc4c0918bf59d8180fbe9a3cc56dc21a3

But I was hoping to request (mostly because I'm not sure how the images are generated) a dev to bump the sogo image to include this fix. Hopefully, this is straight-forward since SOGo has already fixed the issue.

**Comment by andryyy** [comment]
Hi, that's already included for a while.

**Comment by mkuron** [comment]
Fixed since #3883

**Comment by seanfarley** [comment]
You were right, apologies for the noise. It seems it took a few runs of `update.sh` to pull the new image for me. Works now!
