### ISSUE TITLE
Add another domain to mailcow for send/recives mails

### ISSUE THREAD

**Issue by hatembentayeb** [mailcow/mailcow-dockerized#3922]
I have some trouble in adding another domain to mailcow, i did all configs (MX, DKIM, SPF .. etc) i can send mails but i cant recieve in the inbox, i think there is somthing wrong. i need help guys; is there any steps provided to add another domain ?
thanks in advance

**Comment by andryyy** [comment]
You already found the forum. :)

**Comment by hatembentayeb** [comment]
Yes i posted there but still have conflicts about the correct dns for an additional domain 
i already did the config like this : 

i have mail.domain.com configured properly then i create a domain2.com and added it to mailcow “add domain” and got the dkim key in the domain provider i made this setup
```
SPF : “v=spf1 ip4:<server-ip> all”
DKIM: dkim._domainkey with the value from mailcow UI
autoconfig CNAME points to mail.domain.com
autodiscover CNAME points to mail.domain.com
domain2.com MX 10 mail.domain.com
```
I can send emails with the new domain but i cant recieve
