### ISSUE TITLE
sogod throws errors of type: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by karimelc** [mailcow/mailcow-dockerized#3925]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
I'm seeing errors from the sogo container of type "could not run SQL" due to "REASON:You have an error in your SQL syntax". I'm not noticing any impact from these errors so they might be totally harmless. The errors come in bursts (~4 bursts per 24h). Every burst contains an error for each domain I have.

My mailcow instance is on commit 0846013 from Dec 11, 2020.

## Logs
Jan  6 13:23:41 6bf8415753dc sogod [96]: [ERROR] <0x0x5563a1134190[SQLSource]> could not run SQL 'SELECT * FROM _sogo_static_view WHERE (domain = 'domainX') AND ((c_uid = '\"http:\') OR (mail = '\"http:\') OR (aliases =\
 '\"http:\') OR (ad_aliases = '\"http:\') OR (ext_acl = '\"http:\'))': <MySQL4Exception: 0x5563a112da30> NAME:ExecutionFailed REASON:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server ve\
rsion for the right syntax to use near '\"http:\') OR (aliases = '\"http:\') OR (ad_aliases = '\"http:\') OR (ext_acl...' at line 1
Jan  6 13:23:41 6bf8415753dc sogod [96]: [ERROR] <0x0x5563a1339660[SQLSource]> could not run SQL 'SELECT * FROM _sogo_static_view WHERE (domain = 'domainY') AND ((c_uid = '\"http:\') OR (mail = '\"http:\') OR (aliases = '\"http:\'\
) OR (ad_aliases = '\"http:\') OR (ext_acl = '\"http:\'))': <MySQL4Exception: 0x5563a19f5bf0> NAME:ExecutionFailed REASON:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for t\
he right syntax to use near '\"http:\') OR (aliases = '\"http:\') OR (ad_aliases = '\"http:\') OR (ext_acl...' at line 1
Jan  6 13:23:41 6bf8415753dc sogod [96]: [ERROR] <0x0x5563a1339ea0[SQLSource]> could not run SQL 'SELECT * FROM _sogo_static_view WHERE (domain = 'domainZ') AND ((c_uid = '\"http:\') OR (mail = '\"http:\') OR (aliases = '\"http\
:\') OR (ad_aliases = '\"http:\') OR (ext_acl = '\"http:\'))': <MySQL4Exception: 0x5563a22ae180> NAME:ExecutionFailed REASON:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version fo\
r the right syntax to use near '\"http:\') OR (aliases = '\"http:\') OR (ad_aliases = '\"http:\') OR (ext_acl...' at line 1

## Reproduction
I don't know how to reproduce the error but it happens regularly on my instance.

## System information

| Question | Answer |
| --- | --- |
| My operating system | CentOS Linux 7 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 4 vCPU |
| Docker Version (`docker version`) | 20.10.1 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4, build 40524192 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Hi, 

There seems to be a broken/invalid element in the mailbox table containing "http". Can you search the docs for "attach sql" and run "select * from mailbox", please? Also "select * from sogo_view". Any "http"?

Since you have a support subscription iirc, feel free to open tickets. :)

**Comment by karimelc** [comment]
Thanks @andryyy, I thought this was a bug so therefore I opened an issue, but I'm happy to open a ticket instead. I did a complete csv dump of the mailcow database and did a grep -i http but came up blank.

**Comment by karimelc** [comment]
I think I have found the error, I have a custom-sogo.js that seems to be causing this. It does a `SSO.$inject = ['$http', 'Authentication'];`. Sorry for wasting your time!

**Comment by karimelc** [comment]
After digging deeper I found that every time the MySQL4Exception happens, a large amount of requests are made towards SOGo similar to this:

GET /SOGo/SOGo/%5C%22http:%5C/%5C/www.sogo.nu%5C/en%5C/support%5C/%5C%22http:%5C/%5C/gnu.org%5C/licenses%5C/%5C%22http:%5C/%5C/gnu.org%5C/licenses%5C/%5C%22http:%5C/%5C/gnu.org%5C/licenses%5C/%5C%22http:%5C/%5C/gnu.org%5C/licenses%5C/gpl.html%5C%22 HTTP/1.0

So I'm guessing some sort of sql inject attack or similar? So not a bug that has anything todo with mailcow but still interesting if anyone else is experiencing this. The requests so far are all coming from different IP's in amazonaws.com.

**Comment by andryyy** [comment]
Hmm, is this still happening?

**Comment by karimelc** [comment]
Yes, it is. I believe that I can reproduce it now. I took the GET requests from the sogo log and put into a script performing curl requests and it triggers the MySQL4Exception. Could of course still be just my installation that this happens on.

**Comment by karimelc** [comment]
I just tested the script towards a test server without my custom-sogo.js and it triggers the MySQL4Exception.

**Comment by karimelc** [comment]
To trigger the exception it's enough by sending a request like this:

curl "https://mailcowinstance.com/SOGo/SOGo/%5C%22http:%5C/%5C/gnu.org%5C/licenses%5C/gpl.html%5C%22"

This triggers one exception. To trigger another exception a docker restart memcached is needed unless you wait X min.
