### ISSUE TITLE
mailbox not created when creating more than one mailbox

### ISSUE THREAD

**Issue by daw87** [mailcow/mailcow-dockerized#3926]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

in the mail setup screen it is not possible to add a mailbox if the password contains special characters

## Reproduction

1. Log in as admin
2. Create a domain
3. Create a mailbox for this domain where the mailbox password contains an "@", e.g. "qwertz@"
Expected behaviour: mailbox is created
What really happens: the new mailbox dialog disappears. no new mailbox is created. if you click on "add mailbox" again, the information for the new mailbox are still there.

## System information

The issue can be reproduced in the demo setup (demo.mailcow.email)

**Comment by andryyy** [comment]
Nope, cannot confirm. Also works in the demo.

**Comment by daw87** [comment]
Ok, I just tried it again on different clients.... it is very strange, it is working if you have set the language to German but it is not working in the English setting. Could you try again with language English active?

**Comment by mindsolve** [comment]
Hi! I have tried to replicate this, but couldn't.
Neither in the demo system, nor in my own mailcow instance, even with mailcow language set to English.

If you can still replicate this, are there errors in the browser console? And what kind of browser/system are you using?

**Comment by daw87** [comment]
Ok guys, I think I was completely wrong about the way how to replicate the issue. Hence, I also changed the topic's title.
Please try to replicate the issue by **adding two mailboxes** in sequence without leaving the mailcow mailbox config page. I was under the impression that it had to be the password because for example after adding the first account without special characters i was not able to add another with special chars. But I guess I could not add the second account at all...
I am trying to create a screen recording later to show you the issue.
It happend on all my clients (Android tablet + Chrome, Windows Laptop + Firefox,...).

**Comment by mindsolve** [comment]
I can partially replicate this with Firefox 84.0.2 on Windows.
Though in my experiments it is not specific to two mailboxes in sequence. On the demo system, my first try failed with your described symptoms, on my instance I was able to create multiple test accounts in one go before getting the same error.


In all failed attempts, this is the JS error in the browser console, as far as I can see, the `$domainSelect` variable is empty, as the dropdown-menu for the domain selection is not there yet and as such the JQuery selector `$('#mailbox_table select')` returns nothing (but that's just a guess, I am no JS expert).
```
jQuery.Deferred exception: $domainSelect[0] is undefined

@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:130:73
dispatch@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:42571
add/v.handle@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:40572
trigger@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:70627
trigger/<@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:71222
each@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:2777
each@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:1419
trigger@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:71198
c.prototype.show@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:9:14684
b/<@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:9:13963
each@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:2777
each@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:1419
b@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:9:13794
window.mailcow_alert_box@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:102:82361
@https://demo.mailcow.email/mailbox:1663:22
e@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:29453
l/</t<@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:29755
setTimeout handler*l/<@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:29964
c@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:27742
fireWith@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:28487
fire@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:28523
c@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:27742
fireWith@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:28487
ready@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:31460
B@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:31239
EventListener.handleEvent*@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:31608
@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:220
@https://demo.mailcow.email/cache/06e71ead5ef4fadd309d7f97107cc2b7af0ef414.js:2:225
```


This is the surrounding JS code:

```javascript
$('#addMailboxModal').on('show.bs.modal', function (e) {
    if (addMailboxModalShown) {
      return
    }
    addMailboxModalShown = !0;
    var $domainSelect = $('#mailbox_table select');
    if ($domainSelect[0].selectedIndex > 0) {
      $('#addSelectDomain').val($domainSelect.val()).change().selectpicker('render')
    }
  });
```

**Comment by andryyy** [comment]
Thank you guys. That's a race condition added with commit 36f296d9d63112db4218cef39f1eebc8a61c785d, I removed it as I don't want to waste too much time figuring it out. If anyone feels like fixing it, **please** do not hesitate. :)
