### ISSUE TITLE
Update SOGo image: Missing FileAs field in syncronisation results in missing names in synced addressbook

### ISSUE THREAD

**Issue by mlq** [mailcow/mailcow-dockerized#3928]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
A bug in SOGo resulted that the Display Name of contacts has not been synchronized over ActiveSync. Thus, Thunderbird showed empty names in the contacts that have been downloaded with TBSync.

I've reported this issue [upstream](https://sogo.nu/bugs/view.php?id=5239) and it has been [fixed](https://github.com/inverse-inc/sogo/commit/2826c83fc52f6aae5a90e02ca9bc166baf3057e2). 

I've rebuild the mailcow/sogo image manually and verified that the issue is fixed. Thus, it would be great if the upstream image could be updated to a newer SOGo version as well.

## Reproduction
* Sync addressbook using SOGo-ActiveSync
* Thunderbird does not show the names in the addressbook

## System information

Latest mailcow version

**Comment by andryyy** [comment]
I pushed an updated image. 👍🏼
