### ISSUE TITLE
update.sh breaks docker-compose installation.

### ISSUE THREAD

**Issue by Mr-Bubbles** [mailcow/mailcow-dockerized#3945]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Updating of docker-compose in current update.sh fails resulting in a broken docker-compose file.
## Reproduction

Run the current ./update.sh script:
`
root@NewHope:/storage/docker/mailcow/mailcow-dockerized# ./update.sh
Checking internet connection... OK
Checking for newer update script...
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Validating docker-compose stack configuration...
Checking for conflicting bridges...
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Prefetching images...
1.12: Pulling from mailcow/unbound
Digest: sha256:822bbaac6129f0f2735b25cf8dcebbbe21b84444cd3f2fb7dde66c7e5d311db9
Status: Image is up to date for mailcow/unbound:1.12
docker.io/mailcow/unbound:1.12
10.4: Pulling from library/mariadb
Digest: sha256:b6d48e55556ef9f9fe66d2cf7c8c69badca70de5fe25c4e018e4a15851dbdf66
Status: Image is up to date for mariadb:10.4
docker.io/library/mariadb:10.4
5-alpine: Pulling from library/redis
Digest: sha256:cab1de051c243a956749397af796d50bf235c7183e88bc4667259f66cad4f748
Status: Image is up to date for redis:5-alpine
docker.io/library/redis:5-alpine
1.38: Pulling from mailcow/clamd
Digest: sha256:e614ea1ede9f5cc18483c07db10ab69cd28ac0415f46628f90a1e05d387a8036
Status: Image is up to date for mailcow/clamd:1.38
docker.io/mailcow/clamd:1.38
1.76: Pulling from mailcow/rspamd
Digest: sha256:93111aaae854beb4dd62babe6e8ebf84e799e92dc32c6388d70ac0ad5fa7ef53
Status: Image is up to date for mailcow/rspamd:1.76
docker.io/mailcow/rspamd:1.76
1.69: Pulling from mailcow/phpfpm
Digest: sha256:ecf6f71756f87c11470ae2556146fd8a58f99c1e124c12fa49e598a5cd371052
Status: Image is up to date for mailcow/phpfpm:1.69
docker.io/mailcow/phpfpm:1.69
1.94: Pulling from mailcow/sogo
Digest: sha256:f3dd5f8500cf254e6ce0517e5b0b8f0614682ae9b8d9b36f7a6024bc7fe17e43
Status: Image is up to date for mailcow/sogo:1.94
docker.io/mailcow/sogo:1.94
1.139: Pulling from mailcow/dovecot
Digest: sha256:3bd98a1c48c0aa55b9aa9f6cde1dc292c5f2c0c5ce69f003318dd881993f8fc7
Status: Image is up to date for mailcow/dovecot:1.139
docker.io/mailcow/dovecot:1.139
1.59: Pulling from mailcow/postfix
Digest: sha256:9049768cf549460d3cf9b4b58e14fd6f8216751fddc8ebe47d8e188f7cfa218f
Status: Image is up to date for mailcow/postfix:1.59
docker.io/mailcow/postfix:1.59
alpine: Pulling from library/memcached
Digest: sha256:61acea4fcc074152e3656fb9848da31da271413fbceaa8b4cd74b47c675eb4fe
Status: Image is up to date for memcached:alpine
docker.io/library/memcached:alpine
mainline-alpine: Pulling from library/nginx
Digest: sha256:c2ce58e024275728b00a554ac25628af25c54782865b3487b11c21cafb7fabda
Status: Image is up to date for nginx:mainline-alpine
docker.io/library/nginx:mainline-alpine
1.76: Pulling from mailcow/acme
Digest: sha256:b5863931f492e20b9e397f1c41335e7cc18b4b8b30e7d472604668c5a6cb5d83
Status: Image is up to date for mailcow/acme:1.76
docker.io/mailcow/acme:1.76
1.38: Pulling from mailcow/netfilter
Digest: sha256:ccd5b68f1f5e992e2fb81480842986198eb700bca987feb8ce3171d97033179f
Status: Image is up to date for mailcow/netfilter:1.38
docker.io/mailcow/netfilter:1.38
1.86: Pulling from mailcow/watchdog
Digest: sha256:d878f5d9c51aa2457cba4a96c5f4b784889ddf8466e7a492d80d30f5bd56e117
Status: Image is up to date for mailcow/watchdog:1.86
docker.io/mailcow/watchdog:1.86
1.37: Pulling from mailcow/dockerapi
Digest: sha256:30d08e62b4ee08e7e2ce242fe42ac93ce98ca0abb5a6f72476497bd0ba6f30c9
Status: Image is up to date for mailcow/dockerapi:1.37
docker.io/mailcow/dockerapi:1.37
1.7: Pulling from mailcow/solr
Digest: sha256:bfb8ea63d20ba65408fbf0f648f8b3810dfe84e26fba9704c5803021622241a9
Status: Image is up to date for mailcow/solr:1.7
docker.io/mailcow/solr:1.7
1.5: Pulling from mailcow/olefy
Digest: sha256:14cb004f0d59b914842c13b3d5bc9d8bf0c18bacf07a839f6a8ef485d2851250
Status: Image is up to date for mailcow/olefy:1.5
docker.io/mailcow/olefy:1.5
Using default tag: latest
latest: Pulling from robbertkl/ipv6nat
Digest: sha256:fab186763aaf3e2c13b13fd4f33885a14ec2dc6419a08e1ed67bf22d647f3c38
Status: Image is up to date for robbertkl/ipv6nat:latest
docker.io/robbertkl/ipv6nat:latest
Stopping mailcow...
Removing network mailcowdockerized_mailcow-network
WARNING: Network mailcowdockerized_mailcow-network not found.
Checking for remaining containers...
Committing current status...
Fetching updated code from remote...
Merging local with remote code (recursive, strategy: "theirs", options: "patience"...
Already up to date.
Fetching new docker-compose version...
#=#=-  #      #
#################################################################################################################################################################################################################################### 100.0%
Fetching new images, if any...
/usr/local/bin/docker-compose: line 1: Not: command not found
Checking IPv6 settings...
Starting mailcow...
/usr/local/bin/docker-compose: line 1: Not: command not found
Collecting garbage...
Further cleanup...
If you want to cleanup further garbage collected by Docker, please make sure all containers are up and running before cleaning your system by executing "docker system prune"
root@NewHope:/storage/docker/mailcow/mailcow-dockerized#
`
## Workaround
runt update.sh with --no-update-compose

## Bugifx
change update.sh to update docker-compose as described in dockers documentation here: [Install Docker Compose](https://docs.docker.com/compose/install/)
eg: ´´curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose´´

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 10.7 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Host is KVM Guest (Portainer Host) |
| Server/VM specifications (Memory, CPU Cores) | 12Gb RAM, 2 Cores |
| Docker Version (`docker version`) | 20.10.2 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**. - No
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

P.S.: How do I insert Code Snippets in Git Issues??

**Comment by andryyy** [comment]
I fixed it. :)

I will also add a check for wether the OS supports docker-compose 1.28. As long as I have not added a routine to check for the OS, we will stick to 1.27.x.

Please run...

```
curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

...for a quick fix and start update.sh again.

**Comment by Mr-Bubbles** [comment]
Yepp. it works again.
Damn that was fast!

Thx!

**Comment by MAGICCC** [comment]
Fixed in https://github.com/mailcow/mailcow-dockerized/commit/5b4d2e5c6551fb548a2940930fbdd936f0ed3372
