### ISSUE TITLE
Suspend user access to server, but still receive mesasges

### ISSUE THREAD

**Issue by jacboy** [mailcow/mailcow-dockerized#3948]
## Summary

E-mail accounts should be able to be _suspended_. In the _suspended_ state they

- still receive all incoming e-mail, apply filtering and anti-spam policies
- won't be able to log in to SOGo webmail interface
- won't be able to log in with SMTP or IMAP / POP3 to send and / or receive messages
- won't be able to log in to mailcow user interface
-  Additional: Allow login to mailcow user interface, but let the root of the mailcow instance set a custom mesasge why the account is blocked and how e. g. customer support can be contacted. If the root prefers not to enter anything, something like "your e-mail account has been suspended" shall be displayed

## Motivation

Many people run e-mail servers with the background of capitalism. Pay server rent, support mailcow development, have something to live from. Some customers stop to pay after a few weeks and don't react to friendly e-mail, snail mail, etc. - if a direct action is taken and their mail is suspended, the motivation to pay for the service mostly will come back.

Nonetheless no incoming message shall be gone, because we're ~~cows🐄 ~~ humans, not assholes. As ISP, it's our job to provide infrastructure and bring data from A to B. That shall continue even if the customer doesn't want to pay at the moment, it's not the senders fault.

**Comment by andryyy** [comment]
Hi,

There is already this when editing a mailbox:

![image](https://user-images.githubusercontent.com/2972950/105283577-0d92de00-5bb1-11eb-926b-6292ee9a043f.png)

:)

And thanks for supporting mailcow.

**Comment by jacboy** [comment]
True thing. Thanks for letting me know. I will try that soon.
