### ISSUE TITLE
Rspamd map download errors 

### ISSUE THREAD

**Issue by lbeltrame** [mailcow/mailcow-dockerized#3951]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

When checking by chance the rspamd logs, I found the following repeated every minute:

```
2021-01-23 19:04:01 #50(controller) <fdp86m>; map; http_map_error: error reading https://maps.rspamd.com/freemail/free.txt.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
```

I checked connectivity from the container:

```
root@rspamd:/# curl https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst -o temp.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1233  100  1233    0     0   9632      0 --:--:-- --:--:-- --:--:--  9632
```

So it can reach the URL just fine.

## Logs

```
rspamd-mailcow_1     | 2021-01-23 19:07:47 #50(controller) <dyatkr>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/spf_dkim_whitelist.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:47 #50(controller) <u9r7uu>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/redirectors.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <o33omj>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/mime_types.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <qamb1r>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/dmarc_whitelist_new.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <fdp86m>; map; http_map_error: error reading https://maps.rspamd.com/freemail/free.txt.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <qbq3yk>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/surbl-whitelist.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <7n3qic>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/mid.inc.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
rspamd-mailcow_1     | 2021-01-23 19:07:50 #50(controller) <k8f914>; map; http_map_error: error reading https://maps.rspamd.com/freemail/disposable.txt.zst(135.181.149.121:443): connection with http server terminated incorrectly: ssl connect error: syscall fail: Connection refused
```

## Reproduction

Happens all the time by starting mailcow-rspamd.

## System information

| Question | Answer |
| --- | --- |
| My operating system | openSUSE Leap 15.2 |
| Is Apparmor, SELinux or similar active? | AppArmor, docker is however unconstrained |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | bare metal |
| Server/VM specifications (Memory, CPU Cores) | 16G RAM, 8 cores |
| Docker Version (`docker version`) | 19.03.11 |
| Docker-Compose Version (`docker-compose version`) | 1.25.1 |
| Reverse proxy (custom solution) | nginx on host |

**Comment by lbeltrame** [comment]
From a quick skim it *does* look like https://github.com/rspamd/rspamd/issues/3616.
EDIT: It is. 

https://github.com/rspamd/rspamd/commit/b78731fa8a8c4b27e669897df1610db772ed3c84 is needed, or alternatively mucking with the container `/etc/hosts` (like suggested in the upstream issue), or alternatively with unbound.

**Comment by lbeltrame** [comment]
For those ending up here, until it is fixed you can add this to your override file:

```yaml

  rspamd-mailcow:
    extra_hosts:
      - "maps.rspamd.com:151.115.41.123"
```

**Comment by omexlu** [comment]
Same. I wait official fix or fix by @andryyy :)

**Comment by andryyy** [comment]
That's a problem upstream and I think Vsevolod already fixed it with a workaround. 

It's a network issue with Hetzner. Probably the load balancer of theirs or the IDS ...

**Comment by omexlu** [comment]
This is the fix?:
https://github.com/rspamd/rspamd/commit/b78731fa8a8c4b27e669897df1610db772ed3c84

So there is no reason to change anything on the system just wait until the rspam image is updated?

**Comment by lbeltrame** [comment]
I had to put the override or the logs would get flooded with errors. After that, I can wait for an eventual update.

**Comment by omexlu** [comment]
But again for stupid like me :D

I actually do not need to do something now, the whole thing will be fixed in the next rspam release?

The files are downloaded anyway (later) then, right? There is just an error (until now)?

**Comment by andryyy** [comment]
That's to prevent the flood of logs, but the http connection will be fixed in the backend, so no need to do anything right now.

**Comment by omexlu** [comment]
Ok, I'll leave everything as it is for now, I hope the files can be downloaded despite the error message.
