### ISSUE TITLE
failed to create dockerapi container

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#3953]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] (partly, no real answer was found) I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
On a fresh virtuozzo hosted Ubuntu 18.04 VM with nothing changed beside installing the necessary tools (curl nano git apt-transport-https ca-certificates gnupg2 software-properties-common) and docker as instructed in the docs.

mailcowdockerized_dockerapi-mailcow_1 failed to create

## Logs

```Starting mailcowdockerized_dockerapi-mailcow_1 ... error
:422: setting cgroup config for procHooks process caused: resulting devices cgroup doesn't match target mode: unknown

ERROR: for mailcowdockerized_dockerapi-mailcow_1  Cannot start service dockerapi-mailcow: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: failed to write "1" to "/sys/fs/cgroup/memory/docker/f28086172c9c8a822b30fce31ee6279352befb58fc9cd70201160d974571beb3/memory.oom_control": write /sys/fs/cgroup/memory/docker/f28086172c9c8a822b30fce31ee6279352befb58fc9cd70201160d974571beb3/memory.oom_control: permission denied: unknown

ERROR: for netfilter-mailcow  Cannot start service netfilter-mailcow: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: resulting devices cgroup doesn't match target mode: unknown

ERROR: for dockerapi-mailcow  Cannot start service dockerapi-mailcow: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: failed to write "1" to "/sys/fs/cgroup/memory/docker/f28086172c9c8a822b30fce31ee6279352befb58fc9cd70201160d974571beb3/memory.oom_control": write /sys/fs/cgroup/memory/docker/f28086172c9c8a822b30fce31ee6279352befb58fc9cd70201160d974571beb3/memory.oom_control: permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```

## Reproduction
Like I said, freshly installed

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 |
| Is Apparmor, SELinux or similar active? | I don't know, ubuntu should have Appamor by default, right? |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Virtuozzo |
| Server/VM specifications (Memory, CPU Cores) | 8 GB 4 vCPU |
| Docker Version (`docker version`) | 20.10.2 |
| Docker-Compose Version (`docker-compose version`) | 1.28.2, build 67630359 |
| Reverse proxy (custom solution) | not yet |

**Comment by andryyy** [comment]
Virtuozzo is the problem here. :( sorry.

**Comment by ghost** [comment]
> Virtuozzo is the problem here. :( sorry.

Ok :( I will try to install it on KVM.

**Comment by andryyy** [comment]
KVM should work fine. I will help you if you run into problems with it.
