### ISSUE TITLE
Big Thanks

### ISSUE THREAD

**Issue by CrazyLinuxNerd** [mailcow/mailcow-dockerized#3955]
Hi,

Just writing this to say a big thanks to everyone who helps create/develop/support mailcow :)

I switched over from Zimbra, which - imo - has gotten worse over recent times and simply dropped any thought of true open sourceness.

In my search for a replacement I found Mailcow - and having been using it for around two weeks now I've just got to say:
It's awesome!

So I want to say a big thank you to the developers and that you're doing a great job! :)

Seriously, thank you!

**Comment by andryyy** [comment]
Thank you very, very much! :)

We really have such a great community, it is so much fun to work on mailcow!

**Comment by MAGICCC** [comment]
:) I'll close it
