### ISSUE TITLE
SOLR disabled but use memory

### ISSUE THREAD

**Issue by prohand** [mailcow/mailcow-dockerized#3962]
Hello,

I have disable SOLR in the mailcow.conf.
But the container is running and get more ram :
![image](https://user-images.githubusercontent.com/20227162/106656954-ad7e3d80-659b-11eb-9e27-5e69463892cb.png)

I read it was normal here:  #2338 but why is it using RAM?

Is there a possibility that the container does not use RAM?

Thank you

**Comment by MAGICCC** [comment]
You could do a `docker-compose stop solr-mailcow` to stop the whole container so it doesnt run a mininmal container

**Comment by prohand** [comment]
Ok thank you.

When restarting the server, will it restart? 

If so, how to block its launch at startup?

**Comment by patschi** [comment]
Yes, it will. The container will always restart, but when you have disabled SOGo, it simply won't load SOGo inside the container. Ensure that you have restarted the whole stack completely after changing the config option. The memory usage of 400 MB for the SOGo container feels like SOGo is still working at this point.

**Comment by prohand** [comment]
Thanks, but I'm not talking about SOGO but SOLR :)

**Comment by prohand** [comment]
I find SOgo much faster since the extinction of SOLR.

It only remains to see how not to restart the SOLR machine after a reboot :)

I have test for restart all stack, but the SOLR still running

Thank you

**Comment by omexlu** [comment]
Give attention if running docker prune when stopping a container 😊
