### ISSUE TITLE
Feature: option for eternal "temporary" alias

### ISSUE THREAD

**Issue by trick77** [mailcow/mailcow-dockerized#3966]
I'd love to have another option for the validity for temporary aliases: "for ever". I realize this is not temporary anymore, I'd just be able to manually delete them once I no longer want them but can reuse them for as long as I want without having to care about its validity.

Cheers!

**Comment by monofox** [comment]
Thanks for your contribution @trick77 . There is already a ticket raising your idea. ref #3892
Kindly consider to close this one.

**Comment by trick77** [comment]
Duplicate
