### ISSUE TITLE
Removing obsolete images

### ISSUE THREAD

**Issue by kunago** [mailcow/mailcow-dockerized#397]
After the last update (while I installed Mailcow a few weeks ago) contained a few more images but also seems to have delivered tags.

Now I am running this set of images:

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

mailcow/acme        1.3                 94ebd1aba6e4        13 hours ago        48.4MB
mailcow/rspamd      1.1                 161662209957        28 hours ago        162MB
mailcow/sogo        1.0                 8d66ca24cced        3 days ago          408MB
mailcow/fail2ban    1.0                 39a69d3e0a66        3 days ago          86.4MB
mailcow/phpfpm      1.0                 53ad50f46a16        3 days ago          141MB
mailcow/unbound     1.0                 5885b387b69e        3 days ago          18.5MB
mailcow/clamd       1.0                 6de995c0b8ad        3 days ago          173MB
mailcow/postfix     1.0                 eea99f8ada04        3 days ago          154MB
mailcow/dovecot     1.0                 60218cae5ea0        3 days ago          415MB
redis               alpine              bc63a40c7cd7        3 days ago          19.8MB
robbertkl/ipv6nat   latest              24c47013b0c7        4 days ago          19.6MB
mailcow/phpfpm      latest              0542cb8bd7a4        11 days ago         140MB
memcached           alpine              75f00ac55055        2 weeks ago         6.91MB
mariadb             10.1                ea0322bb4096        3 weeks ago         395MB
resystit/bind9      latest              e79e3978692b        3 weeks ago         10.1MB
nginx               mainline-alpine     7ebd6770d0d6        3 weeks ago         15.5MB
mailcow/rspamd      latest              9556f9ba6c32        5 weeks ago         213MB
mailcow/sogo        latest              97872cdf262a        5 weeks ago         401MB
mailcow/dovecot     latest              83782ad18b71        6 weeks ago         597MB
mailcow/postfix     latest              0375ba36892d        6 weeks ago         210MB
mailcow/clamd       latest              373826ec8c5c        2 months ago        314MB
mailcow/rmilter     latest              71b212e4655b        2 months ago        128MB

Which ones can be safely removed? I tried all standard commands like `docker ps -a -q` etc but all of these images seem to be just fine and in production.

**Comment by chaosbunker** [comment]
To keep things clean, I do:

docker system prune -a

This will remove all unused containers, volumes, images and networks! So be careful 😊

Without the -a it only removes dangling images

**Comment by kunago** [comment]
Thanks. :-) So you say this _is_ or _is not_ a safe command? I am carefully asking because the last thing I want is to remove my database. Files seem to be fine being stored somewhere else.

**Comment by kunago** [comment]
So using "docker system prune -a" is the only solution here?

**Comment by chaosbunker** [comment]
It is safe as long as all containers (and their volumes and networks) you want to keep are running. Do 

docker ps

And make sure all mailcow containers are booted up .. if you have other docker containers, e.g. A wordpress site or something else, make sure those containers are running before executing 'docker system prune -a' ..

All the command does is remove everything that is not connected to a running "docker system"
