### ISSUE TITLE
Default SOGo Web interface Title 

### ISSUE THREAD

**Issue by aimanssh** [mailcow/mailcow-dockerized#3972]
Hello,

I have an issue with updating Default SOGo Web interface Title, the title do not appear correctly

[](https://mailbox.mailer.ma/SOGo/)

i have updated SOGoPageTitle = "Mailer Mailbox"; in the data/conf/sogo/sogo.conf 

and docker-compose up -d

**Comment by dragoangel** [comment]
This bug with debug enabled in sogo.

**Comment by aimanssh** [comment]
> This bug with debug enabled in sogo.

How to debug it

**Comment by dragoangel** [comment]
this now enabled by default to get custom themes working, if you not use custom theme you can disable debug in sogo.conf settings by adding // to start of line ;)

Note: you need restart sogo after this

**Comment by aimanssh** [comment]
> this now enabled by default to get custom themes working, if you not use custom theme you can disable debug in sogo.conf settings by adding // to start of line ;)
> 
> Note: you need restart sogo after this

Perfect, it's fixed now.
Thank you

**Comment by chriscroome** [comment]
I have a problem with this, in `data/conf/sogo/sogo.conf` I have:

```
SOGoPageTitle = "SOGo Groupware";
```

And [the result](https://webarch.email/) is:

```html
        <title></title>
````
Prior to a Mailcow update today the title was rendered, does anyone have a suggestion regarding how to fix this?

**Comment by aimanssh** [comment]
> I have a problem with this, in `data/conf/sogo/sogo.conf` I have:
> 
> ```
> SOGoPageTitle = "SOGo Groupware";
> ```
> 
> And [the result](https://webarch.email/) is:
> 
> ```
>         <title></title>
> ```
> 
> Prior to a Mailcow update today the title was rendered, does anyone have a suggestion regarding how to fix this?

As @dragoange said, if you not use custom theme you can disable debug in sogo.conf settings by adding // to start of line ;)

Note: you need restart sogo after this

**Comment by chriscroome** [comment]
Thanks @aimanssh commenting this line:

```
\\SOGoUIxDebugEnabled = YES;
```

And a restart did the job:

```bash
docker-compose restart sogo-mailcow
```
