### ISSUE TITLE
SoGo Password Issue with older Backup

### ISSUE THREAD

**Issue by banshy** [mailcow/mailcow-dockerized#3973]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
I tried to setup a fresh mailcow server using a older backup. Everything seems to work as expected, at least until i create new accounts or change passwords. Then I can still login to mailcow using the new/updated user credentials, but the SoGo login fails. I suspect this has something todo with the change in password schemes, but changing the scheme to SSHA256 doesnt fix the problem.

## Logs
SOGoRootPage Login from 'xxx' for user 'xxx' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
xxx "POST /SOGo/connect HTTP/1.0" 403 34/90 0.003 - - 0 - 12

sogo/connect returns:
{"LDAPPasswordPolicyError": 65535}

## Reproduction
1. Setup mailcow.
2. Restore old backup.
3. Setup new mail account or change password of old mail account.
(Restart SoGo/Memcache ...)
4. Login to SoGo.

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 2 Cores |
| Docker Version (`docker version`) | 20.10.3 |
| Docker-Compose Version (`docker-compose version`) | 1.28.2 |
| Reverse proxy (custom solution) | no |

**Comment by banshy** [comment]
Okay, i tried changing the password scheme. It fails regardless of the used password scheme. The password seems to be correctly updated within the sql mailbox table.

**Comment by banshy** [comment]
Okay, i further narrowed the issue down: The table _sogo_static_view somehow is not updated and Sogo's auth-query returns zero rows. Any reason why this might be the case?

**Comment by banshy** [comment]
The table structure of sogo_view somehow was faulty:

```
MariaDB [mailcow]> describe sogo_view;
+-------------------+------------+------+-----+---------+-------+
| Field             | Type       | Null | Key | Default | Extra |
+-------------------+------------+------+-----+---------+-------+
| c_uid             | tinyint(4) | NO   |     | NULL    |       |
| domain            | tinyint(4) | NO   |     | NULL    |       |
| c_name            | tinyint(4) | NO   |     | NULL    |       |
| c_password        | tinyint(4) | NO   |     | NULL    |       |
| c_cn              | tinyint(4) | NO   |     | NULL    |       |
| mail              | tinyint(4) | NO   |     | NULL    |       |
| aliases           | tinyint(4) | NO   |     | NULL    |       |
| ad_aliases        | tinyint(4) | NO   |     | NULL    |       |
| ext_acl           | tinyint(4) | NO   |     | NULL    |       |
| kind              | tinyint(4) | NO   |     | NULL    |       |
| multiple_bookings | tinyint(4) | NO   |     | NULL    |       |
+-------------------+------------+------+-----+---------+-------+
```

After I dropped sogo_view and restartet the container everything was generated and works.

**Comment by andryyy** [comment]
Thanks for posting the solution. :)

**Comment by twixi** [comment]
> The table structure of sogo_view somehow was faulty:
> 
> ```
> MariaDB [mailcow]> describe sogo_view;
> +-------------------+------------+------+-----+---------+-------+
> | Field             | Type       | Null | Key | Default | Extra |
> +-------------------+------------+------+-----+---------+-------+
> | c_uid             | tinyint(4) | NO   |     | NULL    |       |
> | domain            | tinyint(4) | NO   |     | NULL    |       |
> | c_name            | tinyint(4) | NO   |     | NULL    |       |
> | c_password        | tinyint(4) | NO   |     | NULL    |       |
> | c_cn              | tinyint(4) | NO   |     | NULL    |       |
> | mail              | tinyint(4) | NO   |     | NULL    |       |
> | aliases           | tinyint(4) | NO   |     | NULL    |       |
> | ad_aliases        | tinyint(4) | NO   |     | NULL    |       |
> | ext_acl           | tinyint(4) | NO   |     | NULL    |       |
> | kind              | tinyint(4) | NO   |     | NULL    |       |
> | multiple_bookings | tinyint(4) | NO   |     | NULL    |       |
> +-------------------+------------+------+-----+---------+-------+
> ```
> 
> After I dropped sogo_view and restartet the container everything was generated and works.

how to drop sogo_view?
