### ISSUE TITLE
XMPP: Administrator badge is always displayed

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3977]
Hello @andryyy 

I just played around with the new feature in the Mailcow demo and saw that the administrator badge is always displayed even if the user is not an admin:
![Bildschirmfoto vom 2021-02-12 19-52-41](https://user-images.githubusercontent.com/3801660/107810666-54699300-6d6d-11eb-997c-d135305c2a12.png)

Thanks in advance.

**Comment by omexlu** [comment]
@andryyy

Thanks for fixing, I don't want to open a another issue but on debug page is written invalidate date if the xmpp hasn't be setup maybe you can catch this little make-up issue 😅

**Comment by andryyy** [comment]
Will do that tomorrow. :)

**Comment by omexlu** [comment]
Sure no hassle, I'm not updating right now so for me that has time 😅

Another question not related to this, it exists clients (Linux/Android) for xmpp where I can add multiple accounts at once and all is together in one messenger for chatting with multiple accounts?

**Comment by andryyy** [comment]
Gajim should be able to do that.

Furthermore: fixed the date stuff now.

**Comment by omexlu** [comment]
Yeah maybe gajim but it doesn't exist for android 🤔 I need an all-rounder that run on both android and Linux  and can sync messages with multiple accounts 🙈

Maybe someone knows a good alternative 😊

**Comment by omexlu** [comment]
Are the messages stored on the xmpp servers? If yes all client should work with syncing, don't know how it works.

Dino.im for Linux 
And any other for android

I think that must work? Don't know how xmpp works exactly 😅

Edit: and where is the admin-area for xmpp on the mailcow panel? Or is it managed by the clients 🤔

**Comment by Neustradamus** [comment]
@andryyy: Have you seen last comment from @omexlu?

**Comment by omexlu** [comment]
https://mailcowhost.tld/xmpp
