### ISSUE TITLE
Make XMPP/ejabberd optional

### ISSUE THREAD

**Issue by F3nr1s** [mailcow/mailcow-dockerized#3978]
Please make XMPP/ejabberd optional. I'm already running my own XMPP-Server (with Prosody instead of ejabberd, because I had some bad memories with ejabberd) on the same hardware as mailcow.
I now changed the public ports for the ejabberd container, but I don't see, why it should even run, if I don't want/need it. It has nothing to do with an email setup.

Also this will break the setup for other users, who have their own XMPP-Server or running for example a Jitsi-Server (Jitsi uses Prosody in the background for the management of the rooms etc.).

**Comment by andryyy** [comment]
It is not even starting the daemon when you don't enable XMPP for a domain. It won't hurt or bite you. 

Ask Thunderbird and em client why they include a chat function. It's part of collaboration. A Groupware. 

Just bind it to another port or whatever. It is not spawning a new service until enabled. The port binding is truly something you can live with, right? :)

If your server cannot stand another idling bash, it is probably not a good idea to rely on it for mail. :)

Just rebind the port and you are fine. \o/

**Comment by F3nr1s** [comment]
Okay, didn't look up the entrypoint script, if it doesn't start any ejabberd, no problem from me here. I already changed the port binding.

And you are right if the server couldn't survive an idle docker container, it shouldn't try to be an mail-server ;-)

So, closed for me.

**Comment by zmiguel** [comment]
Just want to add to this. Because I also run an XMPP server on the same system as mailcow, the ejabberd update made it so mailcow wouldn't start until I went to the config file and changed the ports.

Would have been a good idea to not have this enabled by default, at least on previous installs.

**Comment by andryyy** [comment]
It is not enabled by default. See my response above. :)

**Comment by ValdikSS** [comment]
@andryyy, please in the future write detailed commit description/forum post about such major features and how do they work. Since mailcow uses rolling git model without releases, the overall fact of ejabberd server for the mail server was unexpected for me during the update, and I found no indications of XMPP in the documentation.

By documenting and posting about this feature prior to commiting it would prevent tickets as this.

**Comment by andryyy** [comment]
There is already documentation.

The issue tracker is not meant for "support tickets". Please get a subscription with us at servercow.de if you need detailed help and information about upcoming releases etc. - I think that's more than fair. Or simply join the Telegram channel. If you don't like Telegram, that's up to you. :) I don't think I need to be available on every channel on this planet to waste 12 hours a day for free support (I have been at that point).

Communication does not happen on Github. We use it for bug tracking only. :)
