### ISSUE TITLE
Implicit TLS (2018 RFC recommandation)

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#3979]
## Summary
There is a 2018 RFC that now recommends the usage of implicit TLS over the previously best-practice STARTLS approach for SMTP, notably for mail submission. Would it therefore make sense to change the default configuration (including autoconfiguration) of Docker mailcow to now prefer implicit TLS? This would include SMTP submission, but also IMAP and (when enabled) POP3.

## Motivation
[2018 RFC](https://tools.ietf.org/html/rfc8314) that recommends implicit TLS mentioned in a [Wikipedia article about STARTLS](https://translate.google.com/translate?sl=de&tl=en&u=https://de.wikipedia.org/wiki/STARTTLS).

**Comment by mkuron** [comment]
We support both implicit TLS (port 465 for SMTP, 993 for IMAP, 995 for POP3) and STARTTLS (ports 587/143/110). We do not allow unencrypted logins, so there is no potential for downgrade attacks.

The only disadvantage of STARTTLS in our case is that the connection setup takes an extra packet back and forth, which should be quite negligible. Our autodiscover uses the implicit TLS ports and our autoconfig places them above the STARTTLS ports, so clients should already be preferring implicit TLS and I don't think any action is required here.

**Comment by strarsis** [comment]
@mkuron: So the default autodiscovery settings in mailcow already favor/use implicit TLS?

**Comment by mkuron** [comment]
Yes. Even our configuration profiles for Apple devices use implicit TLS (ports 465 and 993).
