### ISSUE TITLE
can't add any domain admin

### ISSUE THREAD

**Issue by burn79** [mailcow/mailcow-dockerized#398]
A few days ago I added a domain admin for some domains and it works fine. Today, with the latest version of mailcow-dockerized, I failed to add another domain admin.
I filled out the form with username, password and selected the domain, but after klicking on the '+add' button, the admin page is refreshing, but there is no new domain admin in the list.
I tried to remove the domain admin I createt some days ago and this worked, but create it again failed.

**Comment by andryyy** [comment]
Thanks!
