### ISSUE TITLE
SMTP connection failed - Wordpress WP SMTP

### ISSUE THREAD

**Issue by aimanssh** [mailcow/mailcow-dockerized#3982]
Hi Everyone,

There is an issue when I try to use a mallow mailbox in my wordpress website (hosted in another server)

I use plugin WP mail SMTP

`Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\SMTP' not found
in /home/site/sites/current/public/wp-includes/PHPMailer/PHPMailer.php on line 1821

Call stack:

PHPMailer\P\PHPMailer::getSMTPInstance()
wp-includes/PHPMailer/PHPMailer.php:1942
PHPMailer\P\PHPMailer::smtpConnect()
wp-includes/PHPMailer/PHPMailer.php:1858
PHPMailer\P\PHPMailer::smtpSend()
wp-includes/PHPMailer/PHPMailer.php:1601
PHPMailer\P\PHPMailer::postSend()
wp-content/plugins/wp-mail-smtp/src/MailCatcher.php:88
WPMailSMTP\MailCatcher::send()
wp-includes/pluggable.php:498
wp_mail()
wp-content/plugins/smtp-mailer/main.php:134
SMTP_MAILER::test_email_settings()
wp-content/plugins/smtp-mailer/main.php:105
SMTP_MAILER::options_page()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-admin/admin.php:259
require_once()
wp-admin/options-general.php:10`

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
