### ISSUE TITLE
Please remove uceprotect from rbls

### ISSUE THREAD

**Issue by hase77** [mailcow/mailcow-dockerized#3985]
## Summary
Please remove uceprotect from the rbsl-list mailcow is using.

## Motivation
uceproctect is the only rbl thats lists wide ranges of ips which are not reputed spammers. They are block servers that are not even capable of sending emails. They want money to delist you. There is no possibility to contact the responsible persons behinde uceprotect.

Nobody loves spam and everyone hate spammers, I too. But support such a business conduct does not sound right to me.

And yes, mailcow is not using the l3 list. But using the l1 and l2 lists gives them a creditabilty which they don't deserve. To prevent such anoying conduct it makes it neccessary to ignore and not to use such questionable services.

So please remove or replace it with another service. Please. Or at least think about it. I myself removed both uceprotect lists from my config with no negative impact.

https://blog.sucuri.net/2021/02/uceprotect-when-rbls-go-bad.html
https://twitter.com/mailbox_org/status/1360343017022980100
https://forum.netcup.de/netcup-intern/technik/13742-as197540-netcup-auf-uceprotect-level3-gelistet/

**Comment by andryyy** [comment]
We don't use it anymore. :)

**Comment by patschi** [comment]
FYI, it was removed as part of commit https://github.com/mailcow/mailcow-dockerized/commit/38e5dc37d2a3b56b5bb2cdd246442cbe2bbe24f7#diff-2ddcc31f5c527a3fcadb72a6d446d28c6f7cfc5362a6c38c6229c7cd07c40f3d.

**Comment by hase77** [comment]
Thx for the info! I searched the issues before but I found no topic about that. But I didn't checked the latest commits.
