### ISSUE TITLE
Make dovecot read certificate from fullchain.pem

### ISSUE THREAD

**Issue by Enteee** [mailcow/mailcow-dockerized#3989]
## Summary

Dovecot reads its certificate from a file called `cert.pem`.

https://github.com/mailcow/mailcow-dockerized/blob/5eb2df542bffccb7c99d088ea145fd609295a778/data/conf/dovecot/dovecot.conf#L442

For that to work in the real world `cert.pem` has to contain the server certificate and the full certificate chain. Most ACME tools I know of generate two files `fullchain.pem` and `cert.pem`. I suggest that we change the acme client to generate a file `fullchain.pem` and to change the default file read by dovecot to `fullchain.pem`

## Motivation

What are you about to solve or improve with this idea?

Easier integration with other ACME tools.

What would be the benefit for most users?

No need to write post ACME hooks which copy files around or manually patching dovecot configuration.

## Additional context

[The doc also copies `fullchain.pem` to `cert.pem`](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#optional-post-hook-script-for-non-mailcow-acme-clients)

**Comment by andryyy** [comment]
It's just a name. Cert.pem containers the full chain.

**Comment by Enteee** [comment]
yes. But every other acme tool generates a `cert.pem` which contains just the cert and a `fullchain.pem`. Tricky enough, dovecot will happily accept a cert without a chain and will then just deliver that.

Call me stupid, but I just spent like 60 minutes trying to find out why users got cert issues while the certificate displayed was the correct one. Finding out that mailcow does `cert.pem` and `fullchain.pem` different than the rest of the world was unexpected.

If you don't think this is an issue and there is no value to change this, feel free to just close this ticket.

**Comment by andryyy** [comment]
That's true, I understand.

But changing it will need some extra work like adding backwards compatibility. And doc updates.

I think we will keep it for now. :)
