### ISSUE TITLE
update.sh Internet connection validation fails

### ISSUE THREAD

**Issue by jpbaril** [mailcow/mailcow-dockerized#399]
Hi,
I just ran the update script on a local VM running CoreOS and the script returns this error:

`Checking internet connection... bash: /dev/tcp/8.8.8.8/53: No such file or directory`

If I delete the Internet connection validation part in the script (and the updated script validation), then I can update.

**Comment by andryyy** [comment]
Oh, maybe Bash is compiled without "enable-net-redirections". I will switch this to a curl check.

**Comment by andryyy** [comment]
This will auto-close on dev => master. :-)
