### ISSUE TITLE
XMPP-Webclient

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3990]
Hello,

It would be cool if some kind of web client like the following could be built in:
https://conversejs.org/

Thanks in advance.

**Comment by omexlu** [comment]
We and our community really need something like this because the older people have trouble to get in with clients 🙈 or don't have the calm to read in the Thema...

**Comment by Neustradamus** [comment]
+1

**Comment by theoneandonly-vector** [comment]
I think there should be a switch added to easily disable xmpp alltogether so it won't download any xmpp dockers at all.

**Comment by omexlu** [comment]
> I think there should be a switch added to easily disable xmpp alltogether so it won't download any xmpp dockers at all.

Nothing to do with this feature-request 😊

See docs about that:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-xmpp-faq/

**Comment by theoneandonly-vector** [comment]
thx for the link.. I should have found this myself.

**Comment by mritzmann** [comment]
JSXC has a SOGo integration, [see screenshots on there page](https://www.jsxc.org/).

**Comment by andryyy** [comment]
That's cool!

**Comment by MarcelWaldvogel** [comment]
[JSXC](https://jsxc.org) did have a [SOGo integration](https://github.com/jsxc/jsxc.sogo) quite some time ago. As nobody had been using it, it fell into disrepair. But I seem to remember that the integration was rather easy, at least for SOGo 2. It had the advantage of reducing the media barrier. Maybe @sualko can comment on the expected complexity or reviving JSXC for SOGo?

**Comment by MarcelWaldvogel** [comment]
@andryyy JSXC assumes by default mail domain and XMPP domain match, which I also consider to be best practice. What needs to be done to create [ACME DNS requests mentioned here](https://mailcow.github.io/mailcow-dockerized-docs/u_e-xmpp-enable/)? [acme.sh](https://github.com/acmesh-official/acme.sh) already includes lots of DNS backends (which might also be helpful in automating the creation of the `_xmpp*` RRs).

(We can move that to a different issue, if you prefer.)

**Comment by sualko** [comment]
Not sure if there are any breaking changes in Sogo the last few years, but I had it also running in [Sogo 3](https://github.com/jsxc/jsxc.sogo/tree/sogo-v3). The main issue was the integration into the login form. Since Sogo is using react or vue or something, that was not as easy as in v2. If someone is able to make that part work and update the plugin to potential changes, I can upgrade the JSXC part. Also access to the repo is no problem.

**Comment by dragoangel** [comment]
@andryyy I found JSXC https://www.jsxc.org/ that could be integrated directly in SOGo https://github.com/jsxc/jsxc.sogo
It really will be cool to add it.

**Comment by omexlu** [comment]
This client can only be used by people who have an account in the cow, I also wanted to allow access to people with XMPP accounts with other providers.

**Comment by dragoangel** [comment]
@omexlu people who don't have account in the mailcow, can't use mailcows ejabberd, they can use another xmpp server to send or recieve mail from ejabberd still. Please check how xmpp works and what is XMPP webclients in general - this static JS files that can be hosted by any webserver. If I would like to get Converse,js I can run it out of mailcow and point it to mailcow XMPP, but I can't do it directly in SOGo ;). I don't understand what you mean maybe, so sorry if something unclear.

**Comment by omexlu** [comment]
I want to have a general web client where anyone from various XMPP servers can connect to it regardless of the cow, I have many older people who have an XMPP account somewhere but can't cope with the native software, so a general web client would be good where anyone can connect to it to chat together.

**Comment by dragoangel** [comment]
@omexlu then you can install it out of the cow, what a problem?:D Or even configure existing mailcow nginx to host it. This should be peace of a cake.

**Comment by omexlu** [comment]
There must be made here a few interfaces in the cow otherwise this does not quite work, tried it, am not able to install it :D

Therefore I have yes give that converse.js is integrated into the cow :)

**Comment by dragoangel** [comment]
@omexlu from my personal view: integration directly in sogo looks more like "good colab platform all in one" so I vote for a  https://github.com/jsxc/jsxc.sogo

You can simply modify docker-compose.yml.override to add additional https://github.com/conversejs/converse.js-docker Docker file and configure additional site in nginx. Add additional SAN name in mailcow.conf. Don't see really any blocker.

**Comment by dragoangel** [comment]
@omexlu also big plus to JSXC that it support audio, video calls and screen sharing https://www.jsxc.org/features.html, while converse.js is pure chat. I think it plays out well to choose JSXC.

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack
