### ISSUE TITLE
misconfigured volumes in ejabberd ?

### ISSUE THREAD

**Issue by psychowood** [mailcow/mailcow-dockerized#3994]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Fresh install (as of today), docker-compose.yaml shows this volumes for ejabberd:

```
        - ./data/conf/ejabberd/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:z
        - xmpp-vol-1:/home/ejabberd/database:z
        - xmpp-upload-vol-1:/var/www/upload:z
        - ./data/assets/ejabberd/sqlite:/sqlite:z
        - ./data/conf/ejabberd/autogen:/ejabberd/:z
        - mysql-socket-vol-1:/var/run/mysqld/:z
        - ./data/assets/ssl:/ssl:ro,z
```
After install, I see three more volumes created that aren't either binded to a local directory nor mapped to a named volume, moreover it looks like there may be some overlaps (upload, conf):

<img width="923" alt="image" src="https://user-images.githubusercontent.com/115389/108611557-d39b3e80-73df-11eb-876e-5843acd3c467.png">

I thought this could be related to the recent update to [mailcow/ejabberd:1.4](https://github.com/mailcow/mailcow-dockerized/commit/f301e99095491c4855df6a091ac04886b637c928) but a quick test with 1.3 and 1.2 showed the same behaviour.

Considering there are no other unnamed volumes in the whole project, I suppose this could be filed as a bug.

## Logs

I'm not sure which logs could be useful, there are no explicit errors.

## Reproduction

Just follow the instructions for a new install of mailcow, after spinning up the containers with `docker-compose up -d` you'll see the unnamed volumes created.

## System information

| Question | Answer |
| --- | --- |
| My operating system | BurmillaOS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | BurmillaOS is running inside of ESXi |
| Server/VM specifications (Memory, CPU Cores) | 16Gb, i5 quad core |
| Docker Version (`docker version`) | 19.03.15 |
| Docker-Compose Version (`docker-compose version`) | 1.28.2, build 67630359 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.

No changes besides certificates and hostname.

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.

No firewall active, this is not not a networking issue anyway.

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

No DNS problems, not a networking issue anyway.

**Comment by qy117121** [comment]
Unnamed volumes do not require persistent storage

**Comment by andryyy** [comment]
https://github.com/processone/docker-ejabberd/blob/eca259c24f0a35a65966e2eb3faf1e02d6516883/ecs/Dockerfile#L93

The volume definitions exist in upstream.

**Comment by psychowood** [comment]
@andryyy correct, that's why I was asking. Wouldn't be better to map them either in /data or add named volumes? if they are present, I suppose they should  be preserved...

**Comment by andryyy** [comment]
I see.

No that's fine. We use a different upload path (we cannot use the homedir of ejabberd), mount the config file from data/conf/ejabberd and have a named volume for the database.

Perhaps we can auto-prune these volumes in the future.
