### ISSUE TITLE
Bei der Fail2ban Benachrichtigung fehlt inhalt.

### ISSUE THREAD

**Issue by Conan179** [mailcow/mailcow-dockerized#3997]
Hallo erst mal.

Ich hab da ein kleines Problem, wen eine v4 Ip gesperrt wird, bekomme ich zwar eine Email, aber die info, zu welchen Anbieter sie gehötz, steht immer das:
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf
 
% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.
 
% Information related to '0.0.0.0 - 255.255.255.255'
 
% No abuse contact registered for 0.0.0.0 - 255.255.255.255
 
inetnum:        0.0.0.0 - 255.255.255.255
netname:        IANA-BLK
descr:          The whole IPv4 address space
country:        EU # Country field is actually all countries in the world and not just EU countries
org:            ORG-IANA1-RIPE
admin-c:        IANA1-RIPE
tech-c:         IANA1-RIPE
status:         ALLOCATED UNSPECIFIED
remarks:        This object represents all IPv4 addresses.
remarks:        If you see this object as a result of a single IP query, it
remarks:        means that the IP address you are querying is currently not
remarks:        assigned to any organisation.
mnt-by:         RIPE-NCC-HM-MNT
mnt-lower:      RIPE-NCC-HM-MNT
created:        2002-06-25T14:19:09Z
last-modified:  2018-11-23T10:30:34Z
source:         RIPE
 
organisation:   ORG-IANA1-RIPE
org-name:       Internet Assigned Numbers Authority
org-type:       IANA
address:        see http://www.iana.org
remarks:        The IANA allocates IP addresses and AS number blocks to RIRs
remarks:        see http://www.iana.org/numbers
admin-c:        IANA1-RIPE
tech-c:         IANA1-RIPE
mnt-ref:        RIPE-NCC-HM-MNT
mnt-by:         RIPE-NCC-HM-MNT
created:        2004-04-17T09:57:29Z
last-modified:  2013-07-22T12:03:42Z
source:         RIPE # Filtered
 
role:           Internet Assigned Numbers Authority
address:        see http://www.iana.org.
admin-c:        IANA1-RIPE
tech-c:         IANA1-RIPE
nic-hdl:        IANA1-RIPE
remarks:        For more information on IANA services
remarks:        go to IANA web site at http://www.iana.org.
mnt-by:         RIPE-NCC-MNT
created:        1970-01-01T00:00:00Z
last-modified:  2001-09-22T09:31:27Z
source:         RIPE # Filtered
 
% This query was served by the RIPE Database Query Service version 1.99 (HEREFORD)
Das letzte mail, wo die anfrage korrekt war war am 17.12.20

Kann man das wieder reparieren?

**Comment by mathieupotier** [comment]
Hi @Conan179 can you please translate in english ? it will help community to find a solution.
