### ISSUE TITLE
Matrix.org synapse integration

### ISSUE THREAD

**Issue by axpdreamer** [mailcow/mailcow-dockerized#3998]
If it would be possible to integrate synapse (https://hub.docker.com/r/matrixdotorg/synapse) into mailcow this would be a huge step towards communication freedom :)

**Comment by dumprop** [comment]
I think this will be superfluous since many people need only email 
But I would like matrix integration, especially for [dendrite](https://matrix.org/blog/2020/10/08/dendrite-is-entering-beta)

**Comment by andryyy** [comment]
We went with XMPP.
