### ISSUE TITLE
rspamd error spam on fresh install

### ISSUE THREAD

**Issue by Bitti09** [mailcow/mailcow-dockerized#4]
fresh mailcow docker install (pulled  from git 1/2h ago) gets this log spam:

https://hastebin.com/uxexuqigit.go

any missing ssl flag  in rspamd config? (didn't enabled the rspam webui )

**Comment by andryyy** [comment]
Sorry, will be fixed with the new images that are built right now: https://hub.docker.com/r/andryyy/mailcow-dockerized/builds/
