### ISSUE TITLE
Can not log in to Sogo

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#40]
Hi,

I can not log in to Sogo anymore, a few days ago it still worked. I get the message "Wrong username or wrong password". Both are definitely correct.

Sogo Log:
`Feb 03 14:30:37 sogod [2092]: SOGoRootPage Login from '188.117.155.136' for user 'user@domain.de' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0`

Thanks

**Comment by niklasfyi** [comment]
Same here...

```SOGoRootPage Login from '80.152.243.114' for user 'niklas@ro0kie.de' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0```

**Comment by andryyy** [comment]
Updated containers but not Git files?
Restarted all containers?

Beste Grüße 
André

**Comment by niklasfyi** [comment]
Good point. Containers where all up-to-date but Git has changed. That fixed it for me :+1:

**Comment by andryyy** [comment]
Great! :-)

**Comment by rebek86** [comment]
It worked! Thank you! :-)
