### ISSUE TITLE
Clicking the refresh button during page load causes implosion

### ISSUE THREAD

**Issue by daniele-athome** [mailcow/mailcow-dockerized#4006]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

In practically every page of mailcow admin UI, clicking the refresh button while data is still being loaded causes the list to be somewhat loaded twice, however the list comes up empty (thus the "implosion").
It's not a big deal really, but I thought I would report it anyway. If I find the time I could even work up a pull request.

## Logs

No logs necessary.

## Reproduction

1. load any admin page, e.g. "Mailboxes"
2. click "Refresh" while data is still being loaded
3. watch the loading spinner displayed twice
4. and watch the data list appearing for a second and then being emptied

## System information

I've removed the rows that doesn't really apply to this bug.

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Reverse proxy (custom solution) | None - using native nginx in mailcow directly exposed to the Internet |

**Comment by daniele-athome** [comment]
I don't know what to do with that. I mean if no one looks at it of course it's gonna be stale. 🤔

**Comment by andryyy** [comment]
It is just to clean up a bit and check which issue is still open. It is not a great move, I know, but it helps a bit. :) I will assign this to myself.
