### ISSUE TITLE
Major Problems with acme Container

### ISSUE THREAD

**Issue by brunick** [mailcow/mailcow-dockerized#401]
I cannot update nor restore my installation, caused by this error while docker-compose pull
```
Pulling acme-mailcow (mailcow/acme:1.4)...
ERROR: manifest for mailcow/acme:1.4 not found

```
current head, already removed everything and tried on a clean system

**Comment by mkuron** [comment]
Confirmed. @andryyy hasn't pushed that version yet to https://hub.docker.com/r/mailcow/acme/tags/. You can run `docker-compose build acme-mailcow` in the meantime or replace that container with version 1.3 in docker-compose.yml.

**Comment by brunick** [comment]
all right, i sorta found out, that i could ignore the pull of acme by "--ignore-pull-failures" and my server could be recreated - i also got some problems with rspamd, the whitelist from the mailcow does not work anymore...

**Comment by andryyy** [comment]
And that's why you automate these tasks. :P Sorry.

**Comment by andryyy** [comment]
When was your last update? Are the whitelists still present? Can you run `docker-compose exec php-fpm-mailcow curl http://nginx:8081/settings.php` and post the output (censored)?

**Comment by brunick** [comment]
this is the output, i've received a couple of mails from hardwareluxx, these mails did get the following header: "X-Spamd-Result: default: False [6.20 / 15.00]"
```
root@mx:~/mailcow-dockerized# docker-compose exec php-fpm-mailcow curl http://nginx:8081/settings.php
settings {
        score_info###### {
                priority = low;
                from = "/^((?!.*@########.de|.*@#########.de|.*@########.de|.*@#########.com|.*@hardwareluxx.de).)*$/";
                rcpt = "/info\+.*@######.de/";
                rcpt = "info@######.de";
                apply "default" {
                        actions {
                                reject = 15;
                                greylist = 5.5;
                                "add header" = 6.5;
                        }
                }
        }
        whitelist_info###### {
                from = "/(.*@########.de|.*@#########.de|.*@########.de|.*@#########.com|.*@hardwareluxx.de)/";
                priority = high;
                rcpt = "/info\+.*@######.de/";
                rcpt = "info@######.de";
                apply "default" {
                        MAILCOW_WHITE = -999.0;
                }
                symbols [
                        "MAILCOW_WHITE"
                ]
        }
```

**Comment by andryyy** [comment]
Can you forward this email to info@servercow.de ? 

And can you grep the message-id in the Rspamd logs? Like `docker-compose logs rspamd-mailcow | grep -i message-id -n10`


Does `docker-compose logs --tail=100 rspamd-mailcow | grep -i settings` return a lot of lines like `loaded n elements of settings`?

**Comment by mkuron** [comment]
> And that's why you automate these tasks.

I know you don't want to use Docker Hub for this, @andryyy. But how about doing automatic builds on Travis? You could use a custom script there to avoid unnecessary rebuilds by doing `docker-compose pull --ignore-pull-failures` first, the `docker-compose build` and finally `docker-compose push` to push to the correct tags. There is also documentation on how you can securely store the Docker Hub credentials in Travis.

**Comment by brunick** [comment]
> Does docker-compose logs --tail=100 rspamd-mailcow | grep -i settings return a lot of lines like loaded n elements of settings?

yes, it does, i've send the mail just now

**Comment by andryyy** [comment]
It should build the container when it hits docker-compose up -d. But you are right, this should finally be automated.
