### ISSUE TITLE
very slow SoGo Webinterface

### ISSUE THREAD

**Issue by theoneandonly-vector** [mailcow/mailcow-dockerized#4011]
## Summary
very slow SoGo Webinterface when starting to scroll 20-30 E-Mails of about 3K E-Mails in the inbox.

## Logs
```
I don't see errors in my log
```
## Reproduction
Setup a fresh mailcow, create 5 users, sync e-mails of one users -> disable sync. Login to SoGo -> scroll through inbox.

## System information
there are only 5 users. and only one of them has E-Mails in his inbox/outbox.

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 Server |
| Is Apparmor, SELinux or similar active? | Nope |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware ESXi |
| Server/VM specifications (Memory, CPU Cores) | The server has (for testing only) 24 cores, 16GB RAM and runs on SSD.  |
| Docker Version (`docker version`) | 
```
Client: Docker Engine - Community
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        d3cb89e
 Built:             Thu Feb 25 07:05:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Thu Feb 25 07:03:23 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
| Docker-Compose Version (`docker-compose version`) |
```
docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
| Reverse proxy (custom solution) | nope |

- Output of `git diff origin/master`, any other changes to the code? If so,
only this is different:
```
/data/assets/ssl-example/key.pem
```

**Comment by mritzmann** [comment]
SOGO uses a lot of Javascript. So it can also be a client (browser) problem. Which browser do you use? Does the problem also occur in Google Chrome and Mozilla Firefox? A known problem is e.g. Internet Explorer, there SOGo lags enormously, but IE is end of life anyway.

**Comment by theoneandonly-vector** [comment]
It occurs in Google Chrome. The problem is that it loads the whole inbox at once.. Is there a way to limit this globally.. so it only loads 250 emails, then the next 250 emails etc. (by scrolling down)?

**Comment by dragoangel** [comment]
Hi, first of all, please not add bug tag to issue which not a bug. Second: if you want help much easier to get this in telegram group. Many people use mailcow and many of them use SOGo as main client for mail and they not have such issues. If you open sogo logs do you see "no child" in logs? If yes you need set more workers in sogo.conf. But I do not think this the case with 5 test users.

P.s. Also if you will even find real bug in sogo :) you need open issue in sogo bug traker, not in mailcow.

**Comment by Daniel15** [comment]
Try Roundcube and see how you go: https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

I have a mailbox with 250k emails and SOGo is basically unusable (locks up the browser tab for over a minute every time I load it, locks up for several seconds when I scroll down, often takes over 10 seconds to load an email when I click on it). The difference between SOGo and Roundcube is night and day - Roundcube loads the inbox within a few seconds, scrolling down doesn't lag at all, and clicking an email takes less than a second to load it. RaInloop is similar, but slightly slower than Roundcube.

**Comment by andryyy** [comment]
Wouldn't it be better to post that in the SOGo tracker? :)

**Comment by Daniel15** [comment]
> Wouldn't it be better to post that in the SOGo tracker? :)

It would be, but my hope was that @theoneandonly-vector would try Roundcube, say "wow, this is much faster, I'd better file a bug with SOgo instead!" and close this issue 😄

Of course, if Roundcube is also slow, then the issue is likely elsewhere.

**Comment by theoneandonly-vector** [comment]
Using Roundcube "fixes" it.
And I don't have a "no child" in my logs.
Do you know if this was better on an older version?

**Comment by SirFitz** [comment]
Hi @Daniel15 , I'm trying to switch to roundcube as I'm having the same issue with the load of thousands of emails. However, I'm unable to access the page that should be at https://myserver/rc/installer . I'm getting a 404 error, is there something I'm missing?

Thanks in advance!

Here's my sample config 

```sh
<?php
error_reporting(0);
if (!file_exists('/tmp/mime.types')) {
file_put_contents("/tmp/mime.types", fopen("http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types", 'r'));
}
$config = array();
$config['db_dsnw'] = 'mysql://' . getenv('DBUSER') . ':' . getenv('DBPASS') . '@mysql/' . getenv('DBNAME');
$config['default_host'] = 'tls://dovecot';
$config['default_port'] = '143';
$config['smtp_server'] = 'tls://postfix';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '';
$config['product_name'] = 'Roundcube Webmail';
$config['des_key'] = '2cc5eb10-8ff6-4169-92e0-0c0bd4342a96';
$config['log_dir'] = '/dev/null';
$config['temp_dir'] = '/tmp';
$config['plugins'] = array(
  'archive',
  'managesieve'
);
$config['enable_spellcheck'] = false;
$config['mime_types'] = '/tmp/mime.types';
$config['imap_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
$config['enable_installer'] = true;
$config['smtp_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
$config['db_prefix'] = 'mailcow_rc1';
```
https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

**Comment by Daniel15** [comment]
@SirFitz I didn't follow Mailcow's instructions; instead I just installed Roundcube using the Debian package (`apt install roundcube`).
