### ISSUE TITLE
Rainloop instead of SoGO

### ISSUE THREAD

**Issue by dylanjamesdev** [mailcow/mailcow-dockerized#4017]
## Summary

I would love to see rainloop an option instead of SoGO. 

## Motivation
Rainloop is very easy to work with and is very plug and play.

## Additional context

N/A

**Comment by mkuron** [comment]
See #2375. SOGo does more than just webmail in Mailcow (e.g. EAS, CardDAV, CalDAV), so it‘s not currently possible to disable it. Of course, you can install any other webmail side-by-side without official support.
