### ISSUE TITLE
Mailcow ignoring root certificate in cert.pem

### ISSUE THREAD

**Issue by justandras** [mailcow/mailcow-dockerized#4019]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

I installed the latest mailcow yesterday (2021/03/08) and got it up and running but faced an issue when I tried to add email addresses in gmail and thunderbird.

## Logs

```
Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: connect from host-46-251-21-116.kabelnet.hu[46.251.21.116]


Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: TLS SNI mail.justandras.com from host-46-251-21-116.kabelnet.hu[46.251.21.116] not matched, using default chain


Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: SSL_accept error from host-46-251-21-116.kabelnet.hu[46.251.21.116]: -1


Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1544:SSL alert number 48:


Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: lost connection after CONNECT from host-46-251-21-116.kabelnet.hu[46.251.21.116]


Mar  9 11:41:28 f65af3f009f0 postfix/smtps/smtpd[711]: disconnect from host-46-251-21-116.kabelnet.hu[46.251.21.116] commands=0/0
```

## Reproduction

Part of my troubleshooting process was turning off Let's encrypt in the config and trying with a certificate generated from cloudflare. After restarting the containers, using thunderbird I downloaded the certificates and compared them to the one I had set on the server and could see that the root certificate is not what I pasted at the end of the cert.pem file instread it appears to be the same as the top one. 
![QBGOPcj0ow](https://user-images.githubusercontent.com/32372119/110461171-6241d800-80cf-11eb-9688-273955bfaeae.png)

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu LTS 18.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM and Proxmox |
| Server/VM specifications (Memory, CPU Cores) | 8 Gb ram, 4 CPU cores |
| Docker Version (`docker version`) | 19.03.6 |
| Docker-Compose Version (`docker-compose version`) | 1.28.5 build c4eb3a1f |
| Reverse proxy (custom solution) | Nginx Proxy Manager |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by dragoangel** [comment]
I think your issue that you have issues with getting certificate from lets encrypt. Provided details not help to check this. Please use telegram channel or forum to get help, and not put bug where bug not exist.

P.s. clodflare not generate publicly trusted certificates, only origin one which work with their proxy. Any service that utilities not only http like mailserver can't run behind cloudflare proxy.
