### ISSUE TITLE
Sync jobs: Set --addheader Flag by Default

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#4025]
## Summary

Moved dozens of mailboxes to Mailcow. The data was transferred with sync jobs. A few days later we noticed that the sync jobs sometimes (this was not always the case) did not transfer the emails in the sent folder. The error message in the log was:

```
Host1 Sent/1234 ignored (no wanted headers so we ignore this message. 
   To solve this: use --addheader)
```

Turns out: This is a normal behavior if messages do not have a `Message-Id:`-header.  
FAQ entry: https://imapsync.lamiral.info/FAQ.d/FAQ.Use_addheader.txt

## Motivation

Missing emails are annoying, especially if the problem is not noticed immediately, so data loss could happen.

## Additional context

I'm not quite sure why there is a flag for this, why Imapsync doesn't enable it by default. If this has no negative effects (I can't think of any) I would find it useful to enable `--addheade` by default.

**Comment by andryyy** [comment]
Hi,

Thanks. I wondered about the downsides. But tbh I don't see any. This can probably be implemented.

Edit: Implemented it. :) Will be pushed soon!
