### ISSUE TITLE
There's a way to customize URLs?

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#403]
I'm wondering if there's a -good- way to customize the URL for access the admin panel and webmail to something more standardized, like: 

`admin.domain.com` or `domain.com/admin` --> Shows you admin panel
`mail.domain.com` or `domain.com/mail` --> Shows you SOGo

I'm asking this because SOGo for example uses many rules in nginx config and I didn't want to break up things, also if I change the config file it will be more complicated the updates of MC.

I was thinking if is possible to add al this stuff in mailcow.conf file so you don't need to change main files.

Thanks.

**Comment by PhoenixPeca** [comment]
actually this is possible by using reverse proxy. you may want to take a look at issue #393. With reverse proxy, you can get all the customizations that you want, even setting custom error pages.

**Comment by axd** [comment]
@PhoenixPeca Thank you for your solution, but I'm wondering if it is possible to implement this options in the mailcow.conf and leave everything to the installer.

Cheers.

**Comment by PhoenixPeca** [comment]
@axd, at this point in time. There is no option to do that with mailcow.conf.

**Comment by axd** [comment]
@PhoenixPeca Thanks for clear the things out, I'm using a reverse proxy to achieve this, then. Closing this for now.

**Comment by axd** [comment]
@PhoenixPeca Thanks for clear the things out, I'm using a reverse proxy to achieve this, then. Closing this for now.
