### ISSUE TITLE
Mailcow uses all cpu capacity until the server is not responsive (4GB RAM)

### ISSUE THREAD

**Issue by kolaente** [mailcow/mailcow-dockerized#4034]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Mailcow (or rather, some part of it) uses all CPU capacity until the server is completely unusable. Unable to receive email, access the admin panel or even logging into the server through ssh.

The only way to resolve this is a hard reboot of the server. Until it happens again...

In my vps provider's panel it looks like this:

![image](https://user-images.githubusercontent.com/13721712/111906794-b004fb80-8a52-11eb-8036-f5739cd80ee4.png)

My server is not particular powerful. However, I did not have any problems with the cpu usage in the last 3 years running mailcow, it usually stayed well below 20%.

## Logs

I can't get any logs when this happens since I'm unable to access the server in that case.

## Reproduction

I can't really reproduce it. It happens seemingly at random. Not even sure how to debug this, happy to take any suggestions.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 9.13 |
| Is Apparmor, SELinux or similar active? | I did not explicitly enable it, so I guess no. |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | kvm |
| Server/VM specifications (Memory, CPU Cores) | 1 core, 2GB Ram |
| Docker Version (`docker version`) | 19.03.13 |
| Docker-Compose Version (`docker-compose version`) | 1.28.5 |
| Reverse proxy (custom solution) | none |

Mailcow Commit: 3255c08813b2ce6c30b03898d45b522ad8f75622

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by Adorfer** [comment]
what did you disable/modify of mailcow in order to make it run with 1/3 of the recommended RAM?

**Comment by mkuron** [comment]
> with 1/3 of the recommended RAM

You can actually run Mailcow reasonably well with 2 GB if you disable ClamAV and SOLR and have absolutely nothing else running on the server. My guess would be that @kolaente did not do that and the server just ends up hitting swap so much that it goes to 100% load. If that's not it or you actually have more memory than you said, please watch `docker stats` and see if one of the memory or CPU numbers grows before your server becomes unusable.

**Comment by andryyy** [comment]
Perhaps there is no swap at all.

**Comment by omexlu** [comment]
The screenshot looks to me like a cloud from Hetzner.

Here 2GB is really very little, Hetzner does not have SWAP configured in the clouds by default.

I would therefore set up a SWAP file, so you could possibly counteract the problem somewhat:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

However, better to switch to the next possible larger cloud.

I had a similar problem also 1 year ago, I have a SWAP file set up and after the problem still existed a stronger cloud taken.

**Comment by kolaente** [comment]
> what did you disable/modify of mailcow in order to male it run with 1/3 of the recommended RAM?

@Adorfer  @mkuron I have solr and clamAV disabled and maybe 3 really used mailboxes on the server.

> Perhaps there is no swap at all.

@andryyy @omexlu Correct, there is (was) no swap configured at all. I've set it up, lets see if that helps. Right after setting it up it instantly jumped to 700mb usage so this might have been it.

By chance I was able to observe one such spike in cpu usage with `docker stats` and it turned out to be the rspamd container  which was using up almost all of the cpu. The logs of that container looked fine to me during that time, it wasn't blasting with log messages every second as I would kind of expected it to. However, there were a few messages each minute like these:

```
2021-03-23 20:28:55 #343(normal) <523ebd>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 2 regexps matched, 3097 regexps total, 2785 regexps cached, 0B scanned using pcre, 1.58KiB scanned total
2021-03-23 20:29:37 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type rspamd_proxy with pid 43, last beat on: 2021-03-23 20:29:02.55078 (1 beats received previously)
2021-03-23 20:29:37 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type hs_helper with pid 46, last beat on: 2021-03-23 20:29:02.34510 (1 beats received previously)
2021-03-23 20:29:37 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type controller with pid 344, last beat on: 2021-03-23 20:29:01.34281 (1 beats received previously)
2021-03-23 20:29:37 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type fuzzy with pid 42, last beat on: 2021-03-23 20:29:01.29307 (1 beats received previously)
2021-03-23 20:29:37 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type normal with pid 343, last beat on: 2021-03-23 20:29:01.13068 (1 beats received previously)
2021-03-23 20:29:37 #344(controller) <waugaw>; lua; neural.lua:540: cannot train ANN SHORT:default : Worker has died without reply
2021-03-23 20:29:48 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: received heartbeat from worker type rspamd_proxy with pid 43, last beat on: 2021-03-23 20:29:47.08656 (1 beats lost previously)
2021-03-23 20:29:48 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: received heartbeat from worker type fuzzy with pid 42, last beat on: 2021-03-23 20:29:47.07847 (1 beats lost previously)
2021-03-23 20:29:48 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: received heartbeat from worker type normal with pid 343, last beat on: 2021-03-23 20:29:47.21454 (1 beats lost previously)
2021-03-23 20:29:48 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: received heartbeat from worker type controller with pid 344, last beat on: 2021-03-23 20:29:47.26655 (1 beats lost previously)
2021-03-23 20:29:48 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: received heartbeat from worker type hs_helper with pid 46, last beat on: 2021-03-23 20:29:47.20645 (1 beats lost previously)
2021-03-23 20:30:40 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type fuzzy with pid 42, last beat on: 2021-03-23 20:30:07.08250 (1 beats received previously)
2021-03-23 20:30:40 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type hs_helper with pid 46, last beat on: 2021-03-23 20:30:07.20247 (1 beats received previously)
2021-03-23 20:30:40 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type controller with pid 344, last beat on: 2021-03-23 20:30:07.26678 (1 beats received previously)
2021-03-23 20:30:40 #1(main) <4a0551>; main; rspamd_main_heartbeat_cb: lost heartbeat from worker type normal with pid 343, last beat on: 2021-03-23 20:30:07.21511 (1 beats received previously)
2021-03-23 20:30:40 #344(controller) <waugaw>; lua; neural.lua:540: cannot train ANN SHORT:default : Worker has died without reply

**Comment by Adorfer** [comment]
My experience is: even with methods (ClamAV off, Solr off), hdd swap plus zram enabled: 3GB is the bare minimum. 
But perhaps there is additional tweaking possible.

**Comment by cowl0ver** [comment]
Same experience here: 1vCore of Hetzner's Cloudservers can't handle mailcow from what I saw in the past. Btw. I tried this since the start of Hetzner Cloud(2017). FYI: Check the vCore Benchmark - even a vCore from like  4th to current Gen. Intel-CPU's has way more power. After I virtualized Mailcow on Proxmox with the same specs = no issues at all.

If u still wanna use Hetzner Cloud, go for a CX21 at least!

**Comment by gsugambit** [comment]
My daily.cld files inside the container are growing until they take up all memory on the server

**Comment by Adorfer** [comment]
this is not a bug, it's just "using mailcow on system below specified minimum hardware requirements"

**Comment by kolaente** [comment]
I have upgraded the system since I've initially opened this issue and for a while it was running fine. However, the system started to lock up again recently. This resulted in some interesting graphs from my monitoring (which I have since deployed) this time:
![image](https://user-images.githubusercontent.com/13721712/117779168-b3408a80-b23e-11eb-8ec7-c60e7ebe1577.png)

You can see there hasn't been anything recorded past 2:40 which seems to be the time when the system locked up and got unresponsive. The green spike around midnight was the backup job.

It looks like sogo was eating all available ram: 
![image](https://user-images.githubusercontent.com/13721712/117779600-1df1c600-b23f-11eb-9573-c2b7cb7b7110.png)

The cpu spike seems to have been caused by sogo and dovecot first, only to be then joined by postfix as well: 
![image](https://user-images.githubusercontent.com/13721712/117779921-6c06c980-b23f-11eb-9180-5b0e654e93fb.png)

These are the usages per container where 100% is all cpu, so if three containers are each taking up 32% of that cpu that's pretty much all cpu on the system used by these three containers.

General system usage seems to paint a similar picture:

![image](https://user-images.githubusercontent.com/13721712/117780460-ee8f8900-b23f-11eb-9c90-088af4904ff9.png)

You can see it using only a bit of cpu + ram most of the time and then suddenly 100%. The network traffic does not seem to suggest the mail server had to deal with a lot of incoming/outgoing mails all of a sudden which _would_ explain a sudden rise in resource usage.

 Wouldn't an underspec'd system run on constantly more load instead of spiking like this? [The docs](https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#minimum-system-resources) seem to suggest a small cpu won't be the issue but ram + swap is more important. Yet it seems to eat up all cpu _first_ and then all the ram.

**Comment by andryyy** [comment]
You seem to have upgraded it to a value still below the requirement.

**Comment by kolaente** [comment]
@andryyy It's at 4GB + Swap with solr and clamAV disabled. As far as I understood it that should be fine?

**Comment by mkuron** [comment]
How many concurrent web and EAS users do you have in SOGo? My mailcow runs just fine with 4 GB, but its SOGo consumes significantly less memory because it is not heavily used. Once your RAM fills up and you start hitting swap, CPU load increases significantly, so that explains why the CPU usage of the other containers appears to go up when SOGo consumes all available RAM.

**Comment by kolaente** [comment]
@mkuron I have 3 accounts which are actually used by people and I think two of those are using the sogo web ui, the others the usual mobile and desktop clients. There's a few other accounts which are used in some software tools to send mails via smtp only. All are in my time zone so they don't start using it heavily at 3 in the morning.

I'm not sure if the sogo usage only depends on how much the web interface is used or the rest of it?

**Comment by kolaente** [comment]
Most of the time the sogo RAM usage is ~300mb: 
![image](https://user-images.githubusercontent.com/13721712/117802330-a4190700-b255-11eb-9cbc-52820b8a3097.png)

**Comment by andryyy** [comment]
It is 6 GB.

You can decrease the SOGo worker count and try.

**Comment by kolaente** [comment]
@andryyy Is that the `WOWorkersCount` variable in `data/conf/sogo/sogo.conf`?

**Comment by kolaente** [comment]
> @andryyy Is that the `WOWorkersCount` variable in `data/conf/sogo/sogo.conf`?

I've changed the value from 20 to 10, let's see if that fixes the issue. Memory usage of the sogo container already halved.

**Comment by andryyy** [comment]
Yes :) This should fix it. Try 5-7 if it doesn't. Don't go below that with watchdog active.

**Comment by kolaente** [comment]
@andryyy Awesome, thanks!

**Comment by andryyy** [comment]
Perhaps it will even work with 2 GB RAM then... :) You are welcome!

**Comment by kolaente** [comment]
Last night this happened again with sogo workers count set to 10: - My idea why it happened at the bottom.

(you may notice the green spike in ram and cpu at midnight, that's the backup job)

![image](https://user-images.githubusercontent.com/13721712/122019198-d6bd9e80-cdc3-11eb-99dc-a175d267781b.png)

![image](https://user-images.githubusercontent.com/13721712/122019530-28662900-cdc4-11eb-862b-9f2db799e96f.png)

The pattern of cpu + ram usage is pretty much the same [as before](https://github.com/mailcow/mailcow-dockerized/issues/4034#issuecomment-838036920) when the SoGo worker count was set to 20.

There's a bunch of theses error messages from dovecot during the high cpu usage:

![image](https://user-images.githubusercontent.com/13721712/122020528-218be600-cdc5-11eb-998f-47012c6dad28.png)

However, it looks like these messages started at 00:08, while the cpu spike happened at 00:28 with this error message:
![image](https://user-images.githubusercontent.com/13721712/122021215-c3abce00-cdc5-11eb-9e19-89f49a54604e.png)

and from then on, the log is full of these messages until the server wasn't responsive anymore: 
![image](https://user-images.githubusercontent.com/13721712/122021545-0b325a00-cdc6-11eb-81f3-28c3fd16192a.png)

Starting at around 00:09, postfix starts to have some timeout issues: 
![image](https://user-images.githubusercontent.com/13721712/122021858-5e0c1180-cdc6-11eb-9000-8c573c33c103.png)

And then when it spiked, it got more and more issues:
![image](https://user-images.githubusercontent.com/13721712/122022062-8a279280-cdc6-11eb-86c7-476a47358522.png)

I guess that's to be expected if SoGo got unresponsive at that time.

Now, talking about SoGo whose memory usage starts to go up at around 00:07:

![image](https://user-images.githubusercontent.com/13721712/122022593-07530780-cdc7-11eb-9270-817c934736d3.png)
![image](https://user-images.githubusercontent.com/13721712/122022431-dd014a00-cdc6-11eb-93ac-45a83586f92c.png)

Here's my theory about what happened:

* The backup job ran at 0:00 and used some resources for that.
* This caused some SoGo process to hang and was restarted by the SoGo watchdog (is that a thing, or is there some other SoGo daemon doing this?)
* Now there's more SoGo workers running than there should be since a few are hanging and a few new ones are started at their place.
* Dovecot + Postfix processes time out because SoGo is unresponsive for their authentication requests. Because of this, more new Processes are started because requests to theses services come in nevertheless. Total process count rises.
* Now there's not only more SoGo processes than there should be, but also more Dovecot + Postfix ones.
* The system starts to get unresponsive, because all Ram and CPU is used by processes waiting on each other. The OS starts to randomly OOM kill processes. The watchdog service notices processes going away due to them being OOM killed and restarts services. This causes more ressources to be used.

Does that sound plausible? What could I do about it?
