### ISSUE TITLE
mailbox_quota_left_exceeded when editing a mailbox 

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#4036]
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

There is no other mailbox for the same domain.

```
# Settings

domain: example.com
Default mailbox quota: 3072
Max. quota per mailbox (MiB): 3072
Domain quota: 4018
```

In my understanding I should be able to increase the mailbox quote to `3072`. When I edit the mailbox, it also shows me this (blue badge with `max. 3072 MiB`). But as soon as I change the quota to `3072`, a `mailbox_quota_left_exceeded`-message appears.

> Not enough space left (space left: 4018 MiB)

Short Summary so far:

* When editing the mailbox it says that I can increase to `3072`, in my understanding this is correct
* But as soon as I want to do that, it does not work

I create a second domain and mailbox with the same settings, the problem does not occur. So far I can only reproduce the problem with this one domain and mailbox. Then i looked in the source code where `mailbox_quota_left_exceeded` occurs and found the following commit: https://github.com/mailcow/mailcow-dockerized/commit/64264767d7a0cc232fe11159aa4b1b9d5745b04f

And bingo, as soon as I undo this change it works.

## Logs

There is no error message which is logged.

```shell
$ tail -f -n0 /var/log/syslog | grep 2c846bd13e6e
Mar 24 10:28:31 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:31 +0100 "GET /forwardinghosts.php" 200
Mar 24 10:28:32 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:32 +0100 "HEAD /settings.php" 200
Mar 24 10:28:32 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:32 +0100 "GET /settings.php" 200
Mar 24 10:28:32 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:32 +0100 "GET /forwardinghosts.php" 200
Mar 24 10:28:32 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:32 +0100 "POST /json_api.php" 200
Mar 24 10:28:33 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:32 +0100 "GET /edit.php" 200
Mar 24 10:28:33 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:33 +0100 "GET /json_api.php" 200
Mar 24 10:28:33 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:33 +0100 "GET /json_api.php" 200
Mar 24 10:28:33 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:33 +0100 "GET /forwardinghosts.php" 200
Mar 24 10:28:34 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:34 +0100 "GET /forwardinghosts.php" 200
Mar 24 10:28:35 localhost.localdomain 2c846bd13e6e[1921]: fd4d:6169:6c63:6f77::1 -  24/Mar/2021:10:28:35 +0100 "GET /forwardinghosts.php" 200
Mar 24 10:28:36 localhost.localdomain 2c846bd13e6e[1921]: 172.22.1.11 -  24/Mar/2021:10:28:36 +0100 "GET /forwardinghosts.php" 200
```

## Reproduction

Unfortunately, I cannot reproduce the problem with a new domain and mailbox. Thus, I can unfortunately not provide a reproducible issue. Thought I'd create an issue anyway, maybe someone else has the same problem, and joins in with a reproduction.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4 GB, 2vCPU |
| Docker Version (`docker version`) | n/a |
| Docker-Compose Version (`docker-compose version`) | n/a |
| Reverse proxy (custom solution) | NGINX |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**: https://gist.github.com/mritzmann/72b83e461154aad216e2b665b2275cbd
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Is there an unlimited mailbox in the domain where this happens?

**Comment by mritzmann** [comment]
The domain itself has no value set to unlimited (except for send limit/rate limit). There is also no value set to unlimited for the mailbox in question (except for send limit/rate limit) and there is only one mailbox for the domain.

![Screenshot 2021-03-24 at 12 08 06](https://user-images.githubusercontent.com/4533780/112300871-9f929200-8c99-11eb-9615-9d5bb283e645.png)

**Comment by mritzmann** [comment]
I also find this Strange 🤔

**Comment by andryyy** [comment]
I will figure this out, but enotime right now. :( I will fix it in the next 1-2 days.

**Comment by mritzmann** [comment]
No problem, is not urgent. I know how to fix the problem temporarily :-)

**Comment by kev-ac** [comment]
@andryyy or @mritzmann Did you find a solution for this problem? We are having the exact same problem with a domain on our server.
The domain is allowed to allocate 15GB but we cannot allocate more than 7GB to the single mailbox for this domain.

**Comment by andryyy** [comment]
No, couldn't replicate it yet. Can you send me a SQL dump without passwords?

**Comment by kev-ac** [comment]
Sure, where can I send it to?

**Comment by andryyy** [comment]
***@***.*** :)

**Comment by kev-ac** [comment]
That didn't work out so well. Your mail address was truncated by GitHub.

**Comment by andryyy** [comment]
Ups. Try Info at servercow.de

**Comment by andryyy** [comment]
Should be fixed. Thank you guys!
