### ISSUE TITLE
Dovecot NegativeUIDs

### ISSUE THREAD

**Issue by theoneandonly-vector** [mailcow/mailcow-dockerized#4038]
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues]

## Summary
I get:
https://wiki.dovecot.org/Clients/NegativeUIDs
which results in e-mails not showing up when using EAS.
I don't get how to re-create the ID's to fix this.

Version -> latest (today)

## Reproduction
I cannot reproduce this on any other user but this one.
on this user it happens everytime when I re-create the mailbox and th efirst e-mail is in the inbox.

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | nope |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMware ESXi |
| Server/VM specifications (Memory, CPU Cores) | 32GB RAM, 16cores, 5 users less than 5GB Mailbox (combined) |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) | 1.28.5, build c4eb3a1f |
| Reverse proxy (custom solution) | - |

**Comment by theoneandonly-vector** [comment]
I'm not able to find the mbox file as described here: https://wiki.dovecot.org/Clients/NegativeUIDs (I'm searchign for it inside the dovecot container)

**Comment by andryyy** [comment]
I don't understand the bug. Is this a question? Could you please use the proper support channels then? :)

We use maildir by the way. From your link: "This should really never be a problem with Maildir. If however you have managed to cause it somehow (by receiving 2 billion mails?), you can recreate the UIDs by deleting dovecot-uidlist file. "

**Comment by theoneandonly-vector** [comment]
With this one user it always happens.. even when I delete the whole account.
I just deleted dovecot-uidlist -> doesn't fix it.

**Comment by theoneandonly-vector** [comment]
I don't find the exact command anymore, which was able to fix it.. but I had to delete more stuff than I thought from /var/mail/domainname

**Comment by andryyy** [comment]
Thank you. :)
