### ISSUE TITLE
MySQL can't start after upgrade

### ISSUE THREAD

**Issue by ReptoxX** [mailcow/mailcow-dockerized#4039]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

I updated mailcow through the update script today and the mysql server doesn't start up again.
During the update my diskspace ran out and the pulling process was aborted due to to many retries.
After i figured out the problem and solved it (by adding another tb storage) the script did pull all images perfectly fine, but the mysql server got stuck. 
## Logs

```
mysql-mailcow_1      | 2021-03-25 13:18:26+01:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.9+maria~focal started.
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] mysqld (mysqld 10.5.9-MariaDB-1:10.5.9+maria~focal) starting as process 1 ...
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Uses event mutexes
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Number of pools: 1
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Using Linux native AIO
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Initializing buffer pool, total size = 25165824, chunk size = 25165824
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.17.
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: Starting shutdown...
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] Plugin 'InnoDB' init function returned error.
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mysql-mailcow_1      | 2021-03-25 13:18:26 0 [ERROR] Aborting
```

## Reproduction

Update mailcow with the update script and let the space run out?

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Docker Version (`docker version`) | 18.09.6 |
| Docker-Compose Version (`docker-compose version`) | 1.28.6 |

**Comment by mritzmann** [comment]
This does not sound like a bug to me, since Mailcow has nothing to do with running out of disk space during an update... Could imagine that now your database is broken. Maybe you can repair the database with MySQL own tools, otherwise rollback. 

But what one could conclude from your ticket: Feature Request, check diskspace in update script.

**Comment by MaxXor** [comment]
Don't forget to manually clean your old containers regularly with `docker system prune`.

**Comment by Daniel15** [comment]
> InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.17.

As the error says, MySQL requires you to use the same database version for crash recovery. It doesn't support upgrading and recovering at the same time. If you downgrade just the MySQL container to the old version and start it once, it should be able to recover (assuming the binlogs are intact), at which point you can shut it down and upgrade it to the newer version again.

If that doesn't work, then deleting the binlogs may clear the error, but you'll likely suffer some data loss (the last updates performed before it aborted may be lost)

If all else fails, I'd recommend restoring the MySQL database from backups (you do have backups, right? 😅)

**Comment by andryyy** [comment]
Thanks for your explanation. :)

**Comment by ReptoxX** [comment]
@Daniel15 Thats exactly how i got around that issue. Thanks.

The Improvement would be to check for available storage before running the script, it's just an extra layer of security to prevent such issues.

Thank you guys.

**Comment by xurizaemon** [comment]
If you want to execute MySQL's startup repair to get the data dir into a state which the updated MySQL will handle, you can try doing this:

```
docker run -v /path/to/local/data:/var/lib/mysql -ti mariadb:10.4.17
```

This would bring up a temporary container with MariaDB 10.4.17 (version based on output above), which will try the repair / redo log. You can then terminate that container, and try starting your MailCow instance with current MariaDB.

If _that_ fails, I'd try the same approach but with an additional `-v /path/to/local/mysql-backups:/backup` for a local backup mount to bring up a temporary MariaDB 10.4.17, then use `docker exec` into that container and `mysqldump` the DBs you want to preserve to that `/backup/dbname.sql` location, terminate container, wipe / relocate the data in `mysql-vol-1` from MailCow, start MailCow again, let it bring up a clean DB state, and then load in the DBs from `/backup`.

HTH 😁
