### ISSUE TITLE
Updating Mailcow on the 25th at 18:30 GMT, caused my RSpamd stats.ucl to reset

### ISSUE THREAD

**Issue by FingerlessGlov3s** [mailcow/mailcow-dockerized#4042]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
On 25th of March 21st, around 18:30GMT, I updated my mailcow server (dedicated VM), The update worked fine no errors were reported to my knowledge, but 2 days later I noticed the RSpamd stats.ucl file had been reset, but not the history. After looking at the new count on the stats and comparing it to the history going back 106 emails in the history I found the stats reset after I updated Mailcow.

I have now restored the original stats.ucl file from a backup made before the update on the 25th (just restore the ). I then added on the new stats count to the totals are now what they are expected to be.
````
docker-compose down
copied in stats.ucl from backup, and added on the extra missing stats (the 106 etc)
docker-compose up -d.
````
Stats now restored.

## Logs
I have since updated Mailcow again since, so the containers will have been deleted. Issue was noticed after updating again on 27th, but clearly looking at the stats count it actually happened when I updated on the 25th of march. I usually only update when something big happens, but because of the OpenSSL CVE, I wanted to make sure mailcow was up to date.

## Reproduction
Unfortunately I've not been able to reproduce the problem

## System information
| Question | Answer |
| --- | --- |
| My operating system | Debian 10.8 |
| Is Apparmor, SELinux or similar active? | NONE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM on Proxmox |
| Server/VM specifications (Memory, CPU Cores) | 4 cores (Full Host instruction set passed though), 5GB Memory |
| Docker Version (`docker version`) |  20.10.5 |
| Docker-Compose Version (`docker-compose version`) | 1.28.6, build 5db8d86f |
| Reverse proxy (custom solution) | NONE |

- Output of `git diff origin/master`, any other changes to the code? If so, https://paste.aes.pm/?10eaa75f10d8ed3e#FYGkBm6UdnqWUHhr5mvSwYcEXgYkjqHbok1f5nHtFLgV.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`. https://paste.aes.pm/?ba011e0107eb1451#Bvw9DFXvB6i61wrmgVBJETJXa8vt7keMMotLgX6eVgNR
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
```
docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.193.69
151.101.129.69
151.101.65.69
```

**Comment by andryyy** [comment]
It's quite possible to happen when we changed the hostname of a container. So no worries. Copy back the old stats file and you are fine.

Check the docs for external logging, this will allow you to not rely on the stats system of Rspamd.

This happened before when you changed the MAILCOW_HOSTNAME variable. It will not happen again because we don't rely on the MAILCOW_HOSTNAME anymore.

**Comment by FingerlessGlov3s** [comment]
Oh I see, if it won't happen again, I'm happy, for this bug log to be closed.

Which docs are you referring too? I can't find external logging in the Mailcow docs, at least not with the search at the top searching external. Do you mean the rspamd docs?

**Comment by andryyy** [comment]
Oh, sorry, forgot the link: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/

**Comment by FingerlessGlov3s** [comment]
Cool thanks for the link.
When I setup Graylog I shall do this, thanks for the link.

Closing issue since it was off one.
