### ISSUE TITLE
BUG: ejabberd-mailcow, three volumes are not defined 

### ISSUE THREAD

**Issue by christianbur** [mailcow/mailcow-dockerized#4045]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

In the ejabberd-mailcow container config (docker-compose.yml), three volumes are not defined, so three new directories are created each time the container is restarted. 
The three volumes are defined in the [ejabberd Dockerfile](https://github.com/processone/docker-ejabberd/blob/bf395e9f9573cfcad81ed8dcd6d1d936bf44089c/ecs/Dockerfile#L96)

Volumes:
  - /home/ejabberd/logs
  - /home/ejabberd/conf
  - /home/ejabberd/upload

ToDo:
  - Please define three volumes in docker-compose.yml.
  - Please check why there are two "upload" volumes (/var/www/upload and /home/ejabberd/upload). 

Clean up:
  - With the following command the unnecessary volumes can be deleted (ALL containers should be stared, otherwise important data will be deleted)
  - Command: docker volume rm $(docker volume ls -qf dangling=true)

```

# docker inspect $(docker ps -qaf name=ejabberd-mailcow) |more
...
    "Mounts": [
...
            {
                "Type": "volume",
                "Name": "f4d121f32175eb9d046de0866a9c86f1d2e6ec384ad21826c6067a8b7ce26695",
                "Source": "/data/docker_root/volumes/f4d121f32175eb9d046de0866a9c86f1d2e6ec384ad21826c6067a8b7ce26695/_data",
                "Destination": "/home/ejabberd/logs",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
...
            {
                "Type": "volume",
                "Name": "mailcowdockerized_xmpp-upload-vol-1",
                "Source": "/data/docker_root/volumes/mailcowdockerized_xmpp-upload-vol-1/_data",
                "Destination": "/var/www/upload",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "ddee955119a2e00a1836e37aa3024459208c5a7957fc38b4d78fb77e9903aa01",
                "Source": "/data/docker_root/volumes/ddee955119a2e00a1836e37aa3024459208c5a7957fc38b4d78fb77e9903aa01/_data",
                "Destination": "/home/ejabberd/upload",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "f8cf37ed722297951466a3d00e9496632e41f881634eb1f001910cd68fb0db38",
                "Source": "/data/docker_root/volumes/f8cf37ed722297951466a3d00e9496632e41f881634eb1f001910cd68fb0db38/_data",
                "Destination": "/home/ejabberd/conf",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

# docker volume ls
DRIVER    VOLUME NAME
local     ddee955119a2e00a1836e37aa3024459208c5a7957fc38b4d78fb77e9903aa01
local     f4d121f32175eb9d046de0866a9c86f1d2e6ec384ad21826c6067a8b7ce26695
local     f8cf37ed722297951466a3d00e9496632e41f881634eb1f001910cd68fb0db38
local     mailcowdockerized_xmpp-upload-vol-1
local     mailcowdockerized_xmpp-vol-1
...
```

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.2 LTS |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM, VMWare |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) |1.28.6, build 5db8d86f |
| Reverse proxy (custom solution) | yes |

**Comment by andryyy** [comment]
We simply don't need them. They are defined upstream. 

I can try to get rid of them

**Comment by christianbur** [comment]
Unfortunately, it is defined in the base image, so you can't choose it. 
It is probably not possible to [override volume directive](https://stackoverflow.com/questions/61595224/undo-dockerfile-volume-directive-from-a-base-image) of the base image.

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack
