### ISSUE TITLE
X-Moo-Tag not applied to mails, Mails won't get tagged anymore

### ISSUE THREAD

**Issue by SephGER** [mailcow/mailcow-dockerized#4048]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [ x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [ x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After updating Mailcow to the latest version the automatic tagging is not working with the default settings anymore. If I change the global sieve postfilter and remove the line with "X-Moo-Tag" it works.

## Reproduction
Send an email with a tag (mail+TAG@domain.com). Mail should receive the X-Moo-Tag header and be sorted into the TAG-folder.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu Server 20.04 |
| Is Apparmor, SELinux or similar active? | Yes |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Docker |
| Server/VM specifications (Memory, CPU Cores) | Memory: 63743MB , Processor: i7-3930K |
| Docker Version (`docker version`) |19.03.8|
| Docker-Compose Version (`docker-compose version`) | 1.28.6 |
| Reverse proxy (custom solution) |traefik |

```git
diff --git a/data/conf/dovecot/global_sieve_after b/data/conf/dovecot/global_sieve_after
index cf12543a..c9f553cc 100644
--- a/data/conf/dovecot/global_sieve_after
+++ b/data/conf/dovecot/global_sieve_after
@@ -13,8 +13,8 @@ if header :contains "X-Spam-Flag" "YES" {
 }
 
 if allof (
-  envelope :detail :matches "to" "*",
-  header :contains "X-Moo-Tag" "YES"
+  envelope :detail :matches "to" "*"#,
+ # header :contains "X-Moo-Tag" "YES"
   ) {
   set :lower :upperfirst "tag" "${1}";
   if mailboxexists "INBOX/${1}" {

```

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by dragoangel** [comment]
Check that your emails for user actually have header `X-Moo-Tag`. This header is set by rspamd via per user settings maps. Maybe you broke your rspamd integration somehow or simply not enabled this setting for desired user?

**Comment by dragoangel** [comment]
Also tested function just now by sending email to `myself+Test@examle.com` - it works. `X-Moo-Tag: YES` is in place and both `[Test] Subject` and `Test folder` cases works.
