### ISSUE TITLE
Mailcow user UI does not show correct password policy

### ISSUE THREAD

**Issue by thenktor** [mailcow/mailcow-dockerized#4049]
## Summary
The Mailcow user UI (mailbox details -> change password) does not show correct password policy. As policy there is always shown: "minimum length 6 chars, contains letters and numbers". This does not match the default policy in `data/web/inc/vars.inc.php`. which is 
```
// Password complexity as regular expression
// Min. 6 characters
$PASSWD_REGEP = '.{6,}';
```

Even worse when policy is changed in `data/web/inc/vars.local.inc.php` to something longer.

![2021-04-06 10_12_05-mailcow UI](https://user-images.githubusercontent.com/371714/113679946-a4efd380-96c0-11eb-9133-6a3d834bd0d8.png)

**Comment by andryyy** [comment]
It does indeed not reflect what you set as regex. We cannot translate the regex. It's planned to make it configurable via UI, so you are able to set a text and a policy.

**Comment by thenktor** [comment]
As it currently also does not reflect the default setting in `vars.inc.php` I'd suggest to remove that message completely as long as there is no UI option.

**Comment by andryyy** [comment]
![grafik](https://user-images.githubusercontent.com/2972950/114175820-b5ab7e00-993a-11eb-8867-dec2372614c8.png)

Edit: Fixed chars => characters
