### ISSUE TITLE
Unable to edit mailbox with unaltered password (password policy applies)

### ISSUE THREAD

**Issue by chotaire** [mailcow/mailcow-dockerized#4053]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Following today’s mailcow-dockerized update (ran update.sh on 2021-04-13) coming from a version dating back to probably December or January, under “Configuration -> Mail Setup -> Mailboxes -> Edit User” I can no longer edit a user’s mailbox as an admin without receiving the message “Password does not meet the policy”. The only way to edit the mailbox is by setting a new password for the user, leaving the password blank triggers the aforementioned issue. If trying to edit the mailbox after setting a new password for the user, the same bug still applies. I double-checked no password manager was active trying to fill a password.

In simple words: Password policy is being applied when it shouldn't (password left unchanged).

## Logs
```
php-fpm-mailcow_1    | 172.22.1.11 -  13/Apr/2021:19:17:20 +0200 "POST /json_api.php" 200
nginx-mailcow_1      | 1.2.3.4 - - [13/Apr/2021:19:17:20 +0200] "POST /api/v1/edit/mailbox HTTP/2.0" 200 88 "https://mail "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  13/Apr/2021:19:17:20 +0200 "GET /edit.php" 200
nginx-mailcow_1      | 1.2.3.4 - - [13/Apr/2021:19:17:21 +0200] "GET /edit/mailbox/user%40domain.com HTTP/2.0" 200 17065 "https://mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
php-fpm-mailcow_1    | 172.22.1.11 -  13/Apr/2021:19:17:21 +0200 "GET /json_api.php" 200
nginx-mailcow_1      | 1.2.3.4 - - [13/Apr/2021:19:17:21 +0200] "GET /api/v1/get/passwordpolicy/html HTTP/2.0" 200 97 "https://mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::e -  13/Apr/2021:19:17:21 +0200 "GET /json_api.php" 200
nginx-mailcow_1      | 1.2.3.4 - - [13/Apr/2021:19:17:21 +0200] "GET /api/v1/get/policy_wl_domain/* HTTP/2.0" 200 22 "https://mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
php-fpm-mailcow_1    | 172.22.1.11 -  13/Apr/2021:19:17:21 +0200 "GET /json_api.php" 200
nginx-mailcow_1      | 1.2.3.4 - - [13/Apr/2021:19:17:21 +0200] "GET /api/v1/get/policy_bl_domain/* HTTP/2.0" 200 22 "https://mail/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
sogo-mailcow_1       | Apr 13 19:17:22 95bb85f3eb1f sogod [110]: mailcowdockerized_watchdog-mailcow_1.mailcowdockerized_mailcow-network "GET /SOGo.index/ HTTP/1.1" 200 2527/0 0.008 - - 0 - 13
```

## Reproduction

- Configuration -> Mail Setup -> Mailboxes -> Edit User
- Edit Mailbox, change quota
- Save changes

## System information

| Question | Answer |
| --- | --- |
| My operating system | 20.04.2 LTS (Focal Fossa) |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 3 cores, 5GB Ram, 6GB Swap |
| Docker Version (`docker version`) | Docker version 20.10.6, build 370c289 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.0, build 07737305 |
| Reverse proxy (custom solution) | no |

**Comment by MAGICCC** [comment]
Will close it in favor of https://github.com/mailcow/mailcow-dockerized/issues/4054
Will be fixed soonish :)

**Comment by andryyy** [comment]
`git fetch ; git checkout origin/master data/web/inc/func*` should fix it.

**Comment by chotaire** [comment]
Fix confirmed working, thanks for the fast response.
