### ISSUE TITLE
Cannot create Admin account

### ISSUE THREAD

**Issue by Aragur** [mailcow/mailcow-dockerized#4054]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Admin User creation fails with a password policy error.  
(Password seen in screenshot is used) (Also a autogenerated password isn't working either)

![image](https://user-images.githubusercontent.com/11004008/114605708-a7db5d00-9c9a-11eb-8515-f8f4ffadf51e.png)

## Logs

There are no logs only from PHP for the page access.

## Reproduction

I don't have a clue -> Upgraded from some older version

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 12GB RAM 2 CPU Cores |
| Docker Version (`docker version`) | 20.10.0 |
| Docker-Compose Version (`docker-compose version`) | 1.29.0 |
| Reverse proxy (custom solution) | Traefik |

- Output of `git diff origin/master`, any other changes to the code? No diff only certificates.
- All third-party firewalls and custom iptables rules are unsupported. Nothing here
- DNS problems? No

**Comment by chotaire** [comment]
See https://github.com/mailcow/mailcow-dockerized/issues/4053.

**Comment by andryyy** [comment]
`git fetch ; git checkout origin/master data/web/inc/func*` should fix it.

**Comment by Aragur** [comment]
@andryyy Thanks a lot!
Working now as expected :)
