### ISSUE TITLE
Skip Rspamd for Forwarding hosts

### ISSUE THREAD

**Issue by stAn47** [mailcow/mailcow-dockerized#4057]
## Summary

I see that emails sent from my forwarding hosts IPs and IPv6s into mailcow MX server is subject for Rspamd filters which sometimes leads to the email being rejected. (mostly due to HFILTER_HOSTNAME_UNKNOWN (8.5) even when IPv6 PTR is correct while the domain doesn't have own AAAA record )

## Motivation

When i configured the forwarding hosts IPs i would expect that absolutely no email can be rejected for no reason and i would suggest to add

smtpd_milter_maps

per http://www.postfix.org/postconf.5.html#smtpd_milter_maps

from the list of these IPs. 

## Additional context

My forwarding hosts are webservers that send emails without authentication to own domains. (authentication is done by IP address at sender and receiver - listing in forwarding hosts)

I got spam filter disabled for all forwading hosts, but it still goes through the Rspamd. 

best regards, stan

**Comment by mkuron** [comment]
Could you please post the full set of symbols assigned to these messages? As you saw, you can switch spam filtering on or off for forwarding hosts (the latter adds the _KEEP_SPAM_ symbol to the message). In both cases, the message is still processed by rspamd, but with _KEEP_SPAM_ (almost) all processing should be disabled.

**Comment by stAn47** [comment]
hello, 
no the log is already gone, i lowered HFILTER_HOSTNAME_UNKNOWN and raised valid DKIM and SPF symbols so sort this out temporarily. (so that HFILTER_HOSTNAME_UNKNOWN plus valid SPF is about zero since both assume working DNS )

BUT my feature request is to completely skip all milters per IP addresses listed in forwarding hosts + "no spam filter" as there are hosts sending a thousand emails per minute which causes troubles when they are to be checked with rspamd + nginx + php etc... which is not needed at all. 

my idea was to: 
- create a php script to export forwardning hosts or see how to use the API URls from bash  (need the list of forwarding IPs into below file)
- adjust extra.cf for postix (the path may be different - i need to find out inside the container how it maps the conf dir)
```
 smtpd_milter_maps = cidr:/opt/postfix/conf/smtpd_milter_map
```
- create a file (on host) in my /opt/mailcow-dockerized/data/conf/postfix with content per docucmentaion
```
# Disable Milters for local clients  per http://www.postfix.org/postconf.5.html#smtpd_milter_maps
    127.0.0.0/8    DISABLE
    192.168.0.0/16 DISABLE
    ::/64          DISABLE
    2001:db8::/32  DISABLE
```
- postmap 
- run from cron every X minutes/day or find how/if mailcow supports any event triggerers

so the discussion here i believe is not about if rspamd failed (which it possibly did since it seems it gave this error only during the very busy times due to timeout on some of the system like nginx,php,dns, else) but how to skip it completely when you know that the email is from authenticated source and none of it can be marked as spam. 

let me know if my aproach is worth it, and/or if i would get no results from this since mailcow uses both 
smtpd_milters = inet:rspamd:9900
non_smtpd_milters = inet:rspamd:9900

best regards, stan

**Comment by andryyy** [comment]
I don't think we want to support fully disabling the milter.

If you want this, you can simple apt install postfix, dpkg-reconfigure for internet host, setup sane and validated names, setup tls and add your hosts to mynetworks.

**Comment by stAn47** [comment]
hello andryy, 
i only would like to not run rspamd for registered IPs via the forwarding hosts (registred IP + antispam=inactive) because they must not be subject for any sort of antispam scans due to performance and upgrade issues which had caused some emails to be rejected, upon changing rspamd configuration, which is a huge problem. 

furthermore the forwarding hosts here are considered trusted sources (possibly my networks) and they sometimes send thousands emails in very short time (cron reports, error reports, antispam reports from websites, etc... )

my goal is not to disable rspamd completely, but only selectively because at the moment it does not work when the server is under stress (i.e. timeout on milter now gives accept) which is caused only by the forwarding hosts. (when server is understress it is possible nginx/php/dns gives timeouts and thus it is skipped)

i don't know what you mean by postfix installation - we have postfix installed on all of our servers and we hoped to use mailcow as the management solution for easy adding of new domains and accounts which works well for last two years even though every ugprade to mailcow needs manual action (manual restart of fpm docker or other containers that were run in wrong order during the updates). 

best regards, stan

**Comment by stAn47** [comment]
possibly one thing why rspamd had rejected a host which was listed in forwading list was that we used IPv6/64 network within forwarding hosts and rspamd maybe did not pick it up properly for whitelist. i now added the IPv6 to forwarding list without the network range suffix and i did not see any more rejected emails in rspad history and those shown have no symbols, so this seems to work OK.

**Comment by andryyy** [comment]
Hm, but why relay that mass mail over mailcow?
Rspamd is not able to compare something like 2001::beef::1 against 2001:0000::beef::1 for example. You need to add it in the format you configured it on the host sadly.

**Comment by stAn47** [comment]
hello andryy, no this, this is misunderstanding - i do not want to relay them, i want to *receive* them only - i.e. mailcow is the final receiver MX for my domains: 

- you make an ecommerce order on my site (webserver1)
- webserver1 uses localhost relay with own authentication to: 
- - send email to cutomer (webserver1 to customer)
- - send email to vendor (me) webserver1 to mailcow-mx
the IP of webserver1 is configured as "forwarding hosts IP" at mailcow as i hoped that it would be unconditionally received. 

now mailcow-mx server checks emails from my webserver1 via rspamd which is not ideal solution due to performance and due to email not being delivered in marginal cases. 

most of the emails are ecommerce orders and generated invoices which got some level of spam nature per the content itself, but some emails are also security alerts like sql injection alerts or mod_security, or error alerts which are important to receive into mailcow-mx for forensic analysis and they can cause huge performance issues on mailcow. 

we do not send emails via mailcow which originate at websites because once a few months some website gets hacked or is outdated (and sends outgoing spam) and we do not want to alter reputation of the maicow-smtp+mx server with this. (unless i figure out how to use different IP for outgoing emails per sender origin + per authenticated user + per relay ) 

best regards, stan

**Comment by dragoangel** [comment]
You need add such forwarding host to postfix mynetworks as well. I have 4 or 5 such IPs and they works fine. All of them enabled to be scanned by rspamd and never faced any rejects as they never had `HFILTER_HOSTNAME_UNKNOWN`
