### ISSUE TITLE
UNKNOWN READ FAILURE in SoGo log

### ISSUE THREAD

**Issue by bbushong** [mailcow/mailcow-dockerized#4058]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Since an update done 2 weeks ago, our SoGo log file has been inundated with the following types of errors:
Apr 14 14:14:43 6e0e91c11eb0 sogod [1079]: <0x0x55cca5d8f480[SOGoCache]> an error occurred when caching value for key 'USER1+defaults': "UNKNOWN READ FAILURE"
Apr 14 14:14:43 6e0e91c11eb0 sogod [1079]: <0x0x55cca5d8f480[SOGoCache]> an error occurred when caching value for key 'USER1+settings': "UNKNOWN READ FAILURE"
Apr 14 14:14:44 6e0e91c11eb0 sogod [1055]: <0x0x55cca5f14eb0[SOGoCache]> an error occurred when caching value for key '/Users/USER2/Calendar/personal': "UNKNOWN READ FAILURE"
Apr 14 14:14:44 6e0e91c11eb0 sogod [1055]: <0x0x55cca5f14eb0[SOGoCache]> an error occurred when caching value for key '/Users/USER2/Calendar/personal': "UNKNOWN READ FAILURE"
Apr 14 14:14:44 6e0e91c11eb0 sogod [1775]: <0x0x55cca5e4d8b0[SOGoCache]> an error occurred when caching value for key '/Users/USER3/Calendar/personal': "UNKNOWN READ FAILURE"
Apr 14 14:14:44 6e0e91c11eb0 sogod [1775]: <0x0x55cca5e4d8b0[SOGoCache]> an error occurred when caching value for key '/Users/USER3/Calendar/personal': "UNKNOWN READ FAILURE"

I have since updated again, and no changes to this. Functionality doesn't seem to be impacted by this error message, it's just unexpected.

ubuntu@mail:/opt/mailcow-dockerized$ git show
commit 08cc49bd2581a2a21d8baa5bfeb546935afb605a (HEAD -> master)
Merge: dd3d9d63 2b2e139d
Author: moo <moo@cow.moo>
Date:   Wed Apr 14 13:34:32 2021 -0400

    After update on 2021-04-14_13_31_25

## Logs

See above for log entries.

## Reproduction

Can't reproduce as it is persistent. We have tried:
* Reboot
* Updates

## System information

| Question | Answer |
| --- | --- |
| My operating system | Linux mail 5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None (AWS) |
| Server/VM specifications (Memory, CPU Cores) | Memory: 32GB; Swap: 32GB, CPU: 8 |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) | 1.29.0, build 07737305 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
**data/conf/dovecot/dovecot.conf**
max-connections         = 700
log-warning = 1
innodb_flush_log_at_trx_commit = 2

**data/conf/nginx/includes/site-defaults.conf**
override_charset off;

**data/conf/phpfpm/php-fpm.d/pools.conf**
pm.max_children = 50

**data/conf/sogo/sogo.conf**
WOWorkersCount = "1500";
SxVMemLimit = 512;

**docker-compose.yml**
enable_ipv6: false

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by bbushong** [comment]
Just an update - I *think* I figured this out. Seems like memcached was maxed out!

I'm realizing this is now not a bug, but a capacity issue on my server. In case it helps anyone, here is what I ended up doing:

1) confirm current settings, and any issues:
```
sudo docker-compose exec -u root memcached-mailcow sh
echo stats | nc localhost 11211
echo stats | nc localhost 11211 | grep connections
```

2) Increase number of connections (Nervous about this one - I have a feeling it should be in the override file, but haven't played enough with that yet to know...) by adding "command" line shown below:
```
memcached-mailcow:
      image: memcached:alpine
      restart: always
      environment:
        - TZ=${TZ}
      command: -c 2048  #this is the added line
      networks:
        mailcow-network:
          aliases:
            - memcached
```

I have not tested if my problem is gone yet, but this feels right :)

Thanks, and sorry for the "bug"

**Comment by andryyy** [comment]
That's a very good information, thank you! :)

------ Originalnachricht ------
Von: "bbushong" ***@***.***>
An: "mailcow/mailcow-dockerized" ***@***.***>
Cc: "Subscribed" ***@***.***>
Gesendet: 15.04.2021 21:49:43
Betreff: Re: [mailcow/mailcow-dockerized] UNKNOWN READ FAILURE in SoGo 
log (#4058)
