### ISSUE TITLE
Future of mailcow

### ISSUE THREAD

**Issue by HannesKannes00** [mailcow/mailcow-dockerized#4062]
This issue is a mirror [of a community post](https://community.mailcow.email/d/828-future-of-mailcow). All discussion should be done there instead of here.

Food for thought for anyone who commits any amount of free time to work on mailcow:

Mailcow has recently been sold to "The Infrastructure Company GmbH". The details and implications of that deal are not being disclosed transparently, and there's NO commitment to keep a community edition of mailcow publicly available and free forever. The only one cashing in on all your free work is André Peters, and he or the company can pull the plug at any time. This is not meant to be a personal attack, it's just the facts.

As someone who has seen this happen over and over, here's free advice: If this thread doesn't get deleted, use it as a starting point to discuss the future of mailcow as a free and open source piece of software. If that does not happen, it should be seen as a big red flag and get you to look elsewhere (or create a fork) before committing any more free time towards the project.

Here's the original announcement as reference ([source](https://mailcow.email/2021/03/31/feature-and-future/)):

> mailcow, including me, will be part of "The Infrastructure Company GmbH". No, mailcow will not be discontinued. No, I will not stop to work on mailcow.
You will probably not notice the change at all. Hopefully we will be able to finally implement more features soon as there will be more time to work on mailcow.

> We still rely heavily on your support (support contacts, SAL etc.) to continue mailcow as it is. As long as we don’t have a commercial plan or "paid version" of mailcow, that’s the only way for us to finance the work on mailcow.

**Comment by andryyy** [comment]
How is this a bug or a FR?

**Comment by andryyy** [comment]
I will lock this as non-sense. Neither did we change anything nor do we plan to. Read the announcement again, please.

**Comment by andryyy** [comment]
I don't want to repeat it over and over. Nothing changes. Or did it? Where? When?

Please don't be a drama queen. It's not that MS bought mailcow. We are still just a simple, small team of a hand full of people. We have been working together in the past 2 years. Has anything changed in the past two years? I don't think so. 

I get less of the cake but will have a team to help me with mailcow. I will have a little bit more time and you better support. That's it.
