### ISSUE TITLE
Converse.js

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4071]
Hello, 

I put in a feature-request for a Webclient for ejabberd:
https://m.conversejs.org/

Thanks in advance.

**Comment by mritzmann** [comment]
duplicate of https://github.com/mailcow/mailcow-dockerized/issues/3990

**Comment by omexlu** [comment]
Nice, but does not help anyone 😂

**Comment by mritzmann** [comment]
Then you have not understood how issue tracking and open source works.

**Comment by andryyy** [comment]
Why did you open two FR?

**Comment by omexlu** [comment]
Because I wanted to draw attention to it again but is not considered anyway, so can actually both be closed 🙈😬

Thanks in advance.

**Comment by andryyy** [comment]
Please don't do that.
