### ISSUE TITLE
acme-tiny contact value from mailcow.conf

### ISSUE THREAD

**Issue by lars-hubrich** [mailcow/mailcow-dockerized#4074]
Hello,

I put in a feature-request for an additional value in the mailcow.conf file for the acme container.
The acme-tiny dependency with gets used in this project has the option to define a contact address.
Is it possible to set this value via the mailcow.conf file?

The following except from the acme-tiny executable lists the contact option:
```
usage: acme-tiny [-h] --account-key ACCOUNT_KEY --csr CSR --acme-dir ACME_DIR
                 [--quiet] [--disable-check] [--directory-url DIRECTORY_URL]
                 [--ca CA] [--contact [CONTACT [CONTACT ...]]]

[...]
  --contact [CONTACT [CONTACT ...]]
                        Contact details (e.g. mailto:aaa@bbb.com) for your
                        account-key
```

Thanks in advance.

**Comment by andryyy** [comment]
Thanks, it's almost implemented. I also fixed the CAA checks for \*config domains.

Need to add something related to the docs, adjust update.sh and then we can push it to master.

**Comment by lars-hubrich** [comment]
0cbd4ec273b9546f8a2fa247b698665a3f745109
