### ISSUE TITLE
Can't renew LE certificate behind Nginx proxy manager

### ISSUE THREAD

**Issue by rwjack** [mailcow/mailcow-dockerized#4075]
Heyo,

I'm self hosting mailcow-dockerized on a home server.

I just realized that my cert expired today because there was no way for it to renew itself, since I'm running inside docker and the only ports that are open on my router are the mail ports, meaning there was no way for LE to work. 

I'm guessing I should open port 80 on my router and forward it to the home server, but that doesn't fully bridge the gap into the docker network.

Perhaps I could add a proxy host inside Nginx Proxy Manager, but I don't know what port to point it to, does the acme container automatically bind to port 80 when requesting a cert or do I need to connect it to the "outside world" manually?

What else am I missing here?

Should I be looking into manually renewing outside docker and copying the certs into `/opt/mailcow-dockerized/data/assets/ssl`? Seems like an easier option as far as my knowledge level goes.

Here are the `acme` container logs: https://pastebin.com/4mLvKFjL

**Comment by andryyy** [comment]
Please check the issue template. :(

**Comment by cysea** [comment]
I can't seem to find it.

Mind linking to it?
