### ISSUE TITLE
Whitelisted hosts unable to send because of other smtpd_xxxx_restrictions 

### ISSUE THREAD

**Issue by pquan** [mailcow/mailcow-dockerized#4076]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Whitelisted host is not allowed to send mail because of other smtpd_xxx_restrictions failure (i.e. helo hostname, fqdn name etc).
## Logs
postfix-mailcow_1    | Apr 29 10:37:45 a4759f44ac3f postfix/smtpd[372]: NOQUEUE: reject: RCPT from unknown[192.168.10.7]: 554 5.7.1 <info@destination.domain.com>: Relay access denied; from=<source@source.domain.com> to=<info@destination.domain.com> proto=ESMTP helo=<sender_host_name>
postfix-mailcow_1    | Apr 29 10:37:45 a4759f44ac3f postfix/smtpd[372]: generic_checks: name=reject_unauth_destination status=2
postfix-mailcow_1    | Apr 29 10:37:45 a4759f44ac3f postfix/smtpd[372]: >>> END Recipient address RESTRICTIONS <<<

## Reproduction
After update from unknown mailcow to postfix mailcow version mailcow/postfix 1.61 I started experiencing the problem.

## System information
Generic debian-buster with docker updated
| Question | Answer |
| --- | --- |
| My operating system | ubuntu focal |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | no |
| Server/VM specifications (Memory, CPU Cores) | irrelevant |
| Docker Version (`docker version`) | docker-ce 20.10.6~3 |
| Docker-Compose Version (`docker-compose version`) | 1.29.1 |
| Reverse proxy (custom solution) |  irrelevant |

- Output of `git diff origin/master`, any other changes to the code? 
none, except for mynetworks fix (see below).

## Temporary FIX:
I have to add the relevant host ip addresses to the mynetworks macro. Then postfix will use the "permit_mynetworks" part of the smtpd restrictions and accept the mail.

It seems that the whitelisted hosts are not allowed to send in smtpd_xxx_restrictions and those restrictions come into effect because of other issues (like invalid helo hostname etc).

My understanding: If a host is in whitelist it must be allowed to send, on the par of the mynetworks hosts (they are trusted).

Let me know if you need more info

**Comment by andryyy** [comment]
Whitelisted forwarding hosts are not hosts that relay through your malicow. These are hosts that send mail from domains that are handled by mailcow. If you don't add them, mailcow will complain that some other server sends in its name. :)

So adding it to the mynetworks is the correct path to go. You added them to `data/conf/postfix/extra.cf`, right? If not, move it there and restart postfix-mailcow.

We removed RFC1918 networks and only allow for the internally used IPv4 and IPv6 networks now.

**Comment by pquan** [comment]
The logs say "relay access denied", however, this is strange.

The hosts that send mail are outside hosts that need to send to a local domain handled by mailcow. They do not relay mail trough mailcow and mailcow is the MX server for the domains that those hosts send mail to. These hosts are cloud servers without a proper mailserver setup (running on private ip addresses). The mails contain log/debug information about the status of the hosts and are often trapped by rspamd. 

Ideally what I need is a whitelist on IP address directly. I can put the mynetworks data/conf/postfix/extra.cf but, is that going to be overwritten with different docker networks on each update/network creation?

**Comment by andryyy** [comment]
Are they sending from a domain that mailcow handles? Like bla@sender.com whereas mailcow handles sender.com as local domain?

You can put the IP back there, check https://mailcow.github.io/mailcow-dockerized-docs/firststeps-trust_networks/ please. That's the change that caused your trouble. Add `192.168.10.0/24` or whichever subnet you need. If you didn't change the IP4_NETWORK nor IP6_NETWORK vars, your line would look like this:

```
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 [fe80::]/10 172.22.1.0/24 [fd4d:6169:6c63:6f77::]/64 192.168.10.0/24
```

Run `docker-compose restart postfix-mailcow` afterwards.

The change is persistent over updates!

**Comment by pquan** [comment]
> Are they sending from a domain that mailcow handles? Like [bla@sender.com](mailto:bla@sender.com) whereas mailcow handles sender.com as local domain?

I got your point.  Yes, all mail is from <server-id>@ourdomain.ext towards notice@ourdomain.ext  even when coming from outside servers. 

> ```
> mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 [fe80::]/10 172.22.1.0/24 [fd4d:6169:6c63:6f77::]/64 192.168.10.0/24
> ```

Ok, I think I'll have to live with this. Thank you.

It would be nice to be able to do something like mynetwork  = $mynetworks a.b.c.d 1.2.3.4 (as dovecot does).
