### ISSUE TITLE
Syntax error in update.sh after running it once

### ISSUE THREAD

**Issue by aponert** [mailcow/mailcow-dockerized#4081]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Today I wanted to update my mailcow-dockerized instance via _./update.sh_ as always. On first run, it updated itself. On second run, it gave me syntax error:

```
./update.sh: line 563: syntax error near unexpected token `('
./update.sh: line 563: `    GLIBC_V=$(ldd --version | grep -E '(GLIBC|GNU libc)' | rev | cut -d ' ' -f1 | rev | cut -d '.' -f2)'
```

Last update before was - according to _update_diffs/_ on 2021-04-01-16-31-55
My current revision according to _git log_ is _87713ba055583238b267df6c8b98e36c317f8818_
## Logs

no logs given, since issue is not directly related to the containers running

## Reproduction

All I did was running the _update.sh_ script once.

## System information

```
Linux mail 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
Docker version 20.10.6, build 370c289
docker-compose version 1.28.6, build 5db8d86f
```
- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
^---- is attached
[git-diff.txt](https://github.com/mailcow/mailcow-dockerized/files/6423397/git-diff.txt)

**Comment by OhSoooLucky** [comment]
+1

**Comment by berkaycagir** [comment]
Yep, having the same issue with Debian 10.

**Comment by MAGICCC** [comment]
https://github.com/mailcow/mailcow-dockerized/blame/master/update.sh#L439
Can be changed to for example
```diff
- echo '# Let\'s Encrypt registration contact information' >> mailcow.conf
+ echo '# Let'\''s Encrypt registration contact information'>> mailcow.conf
```

**Comment by andryyy** [comment]
Give me a sec.

**Comment by xenion1987** [comment]
I'd use
```sh
~ $ echo '# Let'"'"'s Encrypt registration contact information'
# Let's Encrypt registration contact information
```
instead of
```sh
~ $ echo '# Let\''s Encrypt registration contact information'
# Let\s Encrypt registration contact information
```

---

```sh
~ $ bash --version
GNU bash, Version 5.0.3(1)-release (x86_64-pc-linux-gnu)
```

**Comment by andryyy** [comment]
Because of this fuckery I decided to go with "Lets Encrypt". :)

**Comment by MAGICCC** [comment]
> 
> 
> I'd use
> 
> ```shell
> ~ $ echo '# Let'"'"'s Encrypt registration contact information'
> # Let's Encrypt registration contact information
> ```
> 
> instead of
> 
> ```shell
> ~ $ echo '# Let\''s Encrypt registration contact information'
> # Let\s Encrypt registration contact information
> ```
> 
> ```shell
> ~ $ bash --version
> GNU bash, Version 5.0.3(1)-release (x86_64-pc-linux-gnu)
> ```

Ah yes this works fine, or `echo '# Let'\''s Encrypt registration contact information'`
```
echo '# Let'\''s Encrypt registration contact information'
# Let's Encrypt registration contact information
```

**Comment by aponert** [comment]
Commit https://github.com/mailcow/mailcow-dockerized/commit/834fb8a99d56715ecfd415ba7fe8cfd7df7c70da fixes the issue, thank you.

If anyone else is stuck, these are the steps to fix your mailcow-dockerized:

`git reset update.sh`

`git checkout update.sh`

The first command will take the faulty script out of the git staging area, if it is there (was the case for me)
The second command reverts the update script to the version before it was faulty.

Afterwards, run _./install.sh_ again and it will correctly update itself.
Run again to finally update mailcow-dockerized.

For me this issue is considered done.
