### ISSUE TITLE
QR Code for Outlook App

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#4083]
## Summary
Would it be possible to offer a QR code for logging in with the Outlook App - as in the user page of Docker mailcow?

## Motivation
Being able to log in with the Outlook App using a QR code would be a great feature.

**Comment by mkuron** [comment]
I don‘t think the format of these QR codes is documented. They contain a temporary token, probably for OAuth purposes. We might be able to map that to app-specific passwords, but right now we don‘t know how to encode such a QR code.

Note that the Outlook app is somewhat questionable from a privacy perspective. Unlike a few years ago, it does not store your password on Microsoft‘s servers anymore, but your password and your messages still temporarily exist on Microsoft‘s servers in clear text.
