### ISSUE TITLE
Change SSL handling for Jabber to acme-mailcow

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#4084]
## Summary

Using acme-mailcow will allow easier to maintain Jabber SSL certificates and to understand what is going on inside.
Also it will allow to add 311 TLSA and know for sure that it will break by itself after renewing certificate.

## Motivation

If something goes bad with Jabber SSLs mailcow will have option to care about notifications, allow utilize acme contact, etc.

**Comment by andryyy** [comment]
Thanks for the FR.

**Comment by waja** [comment]
It would be great to have https://letsencrypt.org/de/docs/challenge-types/#dns-01-challenge implemented, this would enable the option to use the domain origin with jabber.

**Comment by dragoangel** [comment]
@waja it will be hard to get in reality of mailcow, will add to much complexity and require too much support unfortunately (dns acme have tentation to break after time) :(

P.s. also people could have many domains on many NS which has own API, methods etc. How you will handle such common cases?:)

**Comment by waja** [comment]
@dragoangel acme.sh [offers](https://github.com/acmesh-official/acme.sh/wiki/dnsapi) a lot of API providers. Yes that might be a more sophisticated setup, but maybe configuring a provider can be done by config file and each of them can be selected to dns validation with the correct API provider.

**Comment by andryyy** [comment]
That's so much hassle. Absolutely not worth it. 

I don't want people to setup 20 config files for different domains etc.

Just use it on front of mailcow and be happy. :)

I will perhaps start a vote which providers besides Servercow people want to have implemented. :)

**Comment by waja** [comment]
> Just use it on front of mailcow and be happy. :)

@andryyy no worry about doing it on a (https)-proxy for web ... but I'm looking into xmpp without prefix (https://mailcow.github.io/mailcow-dockerized-docs/u_e-xmpp-enable/#why-cant-we-use-no-prefix) and dns api implementation. :)

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack
