### ISSUE TITLE
Support fail2ban handling of Jabber XMPP

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#4085]
## Summary

At current state XMPP not send logs to redis so netfilter not have option to check them and create blocking rules. It allow target bruteforce of XMPP users to reuse their passwords on SMTP later as example. People who close to mailcow will know that user@xmppPrefix.example.com have same password as user@example.com.

## Motivation

Prevent bruteforce attacks

## Additional context

It will consumer additional resources to handle logging forwarding to redis from ejabber-mailcow container, so this topic for discussion. From my personal view share some additional RAM better then not have ability block targeted bruteforce.

**Comment by andryyy** [comment]
That's not as easy, we would need to add a supervisor or change the whole logging system. But let's see.

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack
