### ISSUE TITLE
XMPP writes users password to log in plaintext in logfile

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#4087]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
When users authenticate to the XMPP contianer the [custom authtication script](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/ejabberd/authenticator) does write the users password in plaintext to a logfile on the container, the password is written to this location: /var/www/authentication/auth.log on the xmpp container. When I do a cut on that file I do see all users password in plaintext.

Line of intrest in /data/Dockerfiles/ejabberd/authenticator:
`$stdoutHandler = new Monolog\Handler\StreamHandler('/var/www/authentication/auth.log', Logger::DEBUG);`

I really don't like to have xmpp auth script log my users password in plain text like that. Maybe the best would be for this logging be turn off. 

## Logs
From XMPP container (inside):

These four lines of code is written to log when a user authnticates, /var/www/authentication/auth.log
I have replaced the plain text information with `<USER>` and `<PLAIN TEXT PASSWORD HERE>` for my own privacy.
```
[2021-05-06T10:31:29.390379+00:00] ejabberdAuth.DEBUG: Input detected, reading 37 bytes... [] []                                                                                                                                                                                
[2021-05-06T10:31:29.390522+00:00] ejabberdAuth.DEBUG: Input read was: auth:<USER>:<PLAIN TEXT PASSWORD HERE> [] []                                                                                                                                                              
[2021-05-06T10:31:29.592977+00:00] ejabberdAuth.DEBUG: Successfully wrote output [1] to stdout [] []                                                                                                                                                                            
[2021-05-06T10:31:29.593103+00:00] ejabberdAuth.DEBUG: Clearing previous command data [] [] 
```
The information in log file is persistent as long as the container isn't stop, restarted or killed. And add more, and more users as they authticate on there xmpp clients.

## Reproduction
1. Open xmpp client and logon with a user
2. ssh to the xmpp/jabber container
3. issue the command: cat /var/www/authentication/auth.log
4. Sensetive information is now vissible on screen in plain text

## System information

| Question | Answer |
| --- | --- |
| My operating system | Linux |
| Server/VM specifications (Memory, CPU Cores) | 8GB/dual-core |
| Docker Version (`docker version`) | 20.10.3 |
| Docker-Compose Version (`docker-compose version`) | 1.27.4 |

**git diff origin/master**
(My setup has ipv6 turned off, acourding to the guide in the documentation, but this is inrelevant to this issue)
```
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf

+smtp_address_preference = ipv4
+inet_protocols = ipv4

diff --git a/data/conf/unbound/unbound.conf b/data/conf/unbound/unbound.conf

-  do-ip6: yes
+  do-ip6: no
```

**Comment by andryyy** [comment]
That's a good catch. Can you try to modify the authenticator to Logger::INFO and check if it persists?

I can't check it right now.

**Comment by ghost** [comment]
Did some testing with Logger::INFO, and it looks like it then stopps logging user information. 

Tested inside the contianer, changed to INFO and killed the process so that it re-loaded the script with new settings, and it then stopped logging the sensetive degug loggs, changed it back to DEBUG just to verifiy, so  it stared logg again, changed to _INFO and repeated the change, and it stopped again.

So looks like this change is fixing the problem. I will prepair a PR, with the fix.

**Comment by andryyy** [comment]
Thanks again. :)
