### ISSUE TITLE
Privacy: email address, name and server ports get sent to mailcow.github.io

### ISSUE THREAD

**Issue by Korkman** [mailcow/mailcow-dockerized#4088]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Clicking the link "Show configuration guides for email clients and smartphones" in the mailcow interface transmits information some may consider private via anchor parameters to the guide. Unfortunately, the information is stored in cookies, which then get sent to the server (mailcow.github.io).

Although I would consider github.io trustworthy, a much better practice would be storing the information in sessionStore or localStore (sessionStore is per tab and will not share data when 'open in new tab' is used), which is kept client side and never gets sent to the server.

(even then, it would be nice to give the server admin or user an option to use placeholder data instead)

Filing this as a bug, not a feature request, because it's a privacy issue - hope that's ok.

**Comment by andryyy** [comment]
They don't

@mkuron

**Comment by mkuron** [comment]
@Korkman is right. They get sent to the server with later requests, which I wasn't aware of when I implemented this. Apparently there is no such thing as Javascript-only cookies, only HTTP-only cookies. We'll have to change it to HTML5 storage.

**Comment by andryyy** [comment]
Oh, alright. Thanks. :)

And thanks for the issue!!!

**Comment by Korkman** [comment]
Thanks for the swift implementation!
