### ISSUE TITLE
mailcow now only available as a docker container?

### ISSUE THREAD

**Issue by ovizii** [mailcow/mailcow-dockerized#409]
I found mailcow a long time ago and now I was in need of something like this but when I visited the website it seems mailcow is now only available as a docker container? 

Am I missing something? 

Also, where is the list of features i.e. to see what exactly is built-in in terms of apps?

**Comment by PhoenixPeca** [comment]
Actually, the standard mailcow is still available, but its **development is under suspension until further notice**. Andre's time is fairly limited at this time.

**Comment by andryyy** [comment]
Yes, sadly there has not yet been time for this. The dockerized versions works like a charm, try it! :-)

You can find out more about it in the docs. I will need to add new screenshots soon.

**Comment by ovizii** [comment]
ah, ok, thanks. I guess I'll have to use the dockerized version or look for alternatives.

**Comment by andryyy** [comment]
Try it and feel free to ask if you need help. :-)

**Comment by ovizii** [comment]
I will, thanks. Its just that for this specific project I want to use mailcow for Docker is not required or helpful so I guess I'll end up installing docker and using exactly 1 container namely mailcow :-/

**Comment by andryyy** [comment]
It is pretty much like installing each application in its own chroot'ed environment. You will have a container for each application and the configuration files in data/conf/x

It is much easier to maintain mailcow and guarantee a working environment this way. You will not get in conflict with packages installed on this host etc.

**Comment by ovizii** [comment]
ah, I see, every app is in its own container, I had simply assumed that you'd packed mailcow into 1 container. OK, makes sense, I'll try it out :-)
