### ISSUE TITLE
Error with WebDav: "no WebDAV GET support"

### ISSUE THREAD

**Issue by leetxyz** [mailcow/mailcow-dockerized#4091]
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
I use Home-Assistant with the Caldav-Integration (https://www.home-assistant.io/integrations/caldav/) to display a calendar hosted in my mailcow-instance. This calendar wasn't updated so i started investigating and found this message (screenshot is from the official demo instance, where this issue also exists)

![webdav01](https://user-images.githubusercontent.com/46599191/117553772-ba577500-b053-11eb-8f74-6092cd13af82.png)

This used to work about a month ago.

## Logs
`[75]: 192.168.1.2 "GET /SOGo/dav/mail@example.org/Calendar/personal/ HTTP/1.0" 501 191/0 0.003 - - 0 - 13`

## Reproduction

1. Login to SOGO, switch to calendar view
2. Press on the 3 dots next to any calendar -> "Links to this calendar"

![webdav02](https://user-images.githubusercontent.com/46599191/117554111-c6dccd00-b055-11eb-946f-ab0442a6f547.png)

3. Open the marked URL and login with your account credentials

![webdav03](https://user-images.githubusercontent.com/46599191/117554160-11f6e000-b056-11eb-8dbf-74b9ded6187d.png)

4. Enjoy the error message.

## System information

Ubuntu 18.04 and mailcow are fully patched (last update about 30 mins before opening this issue.)
In front of mailcow is a selfmanaged nginx, but since this exists on the demo instance, it's probably not relevant.
Error also exists if using the local ip adress.

**Comment by andryyy** [comment]
Hi,

We are not SOGo, please keep that in mind.

Furthermore the HTTP GET on a \*DAV path did never work, it is not implemented in the protocol. :) 

Valid methods:

![grafik](https://user-images.githubusercontent.com/2972950/117554286-f213ec00-b056-11eb-9fd9-f3f63ebe25ce.png)
