### ISSUE TITLE
Editing Sieve via Thunderbird not possible because of SSL error

### ISSUE THREAD

**Issue by Cyberknight234** [mailcow/mailcow-dockerized#4092]
Hello all.

The following problem: I would like to edit Sieve through Thunderbird, which unfortunately is not possible. Mails retrieve/send everything works. just Sieve not. If more logs are needed, let me know. Would be happy if someone could help me

Error message: 
`dovecot-mailcow_1 | May 9 02:47:16 04888203e1b5 dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=92.123.123.123, lip=123.123.123.123, TLS handshaking: SSL_accept() failed: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate: SSL alert number 42`

Thunderbird Sieve: 
`Server
imap.xxxxxx.eu: 4190 (Secured connection)
Username
my@fancydomain.eu`

Mailcow:
OS: Ubuntu 20.04
Mailcow Versions:
 acme-mailcow (mailcow/acme:1.78)
clamd-mailcow (mailcow/clamd:1.39)
dockerapi-mailcow (mailcow/dockerapi:1.38) 
dovecot-mailcow (mailcow/dovecot:1.145)
ejabberd-mailcow (mailcow/ejabberd:1.5)
ipv6nat-mailcow (robbertkl/ipv6nat) 
memcached-mailcow (memcached:alpine)
mysql-mailcow (mariadb:10.5) 
netfilter-mailcow (mailcow/netfilter:1.41) 
nginx-mailcow (nginx:mainline-alpine)
olefy-mailcow (mailcow/olefy:1.7)   
php-fpm-mailcow (mailcow/phpfpm:1.74)
postfix-mailcow (mailcow/postfix:1.61) 
redis-mailcow (redis:5-alpine)
rspamd-mailcow (mailcow/rspamd:1.76)
sogo-mailcow (mailcow/sogo:1.98)
solr-mailcow (mailcow/solr:1.7)
unbound-mailcow (mailcow/unbound:1.13)
watchdog-mailcow (mailcow/watchdog:1.91)

**Comment by Cyberknight234** [comment]
no one? :/

**Comment by waja** [comment]
managesieve (and starttls) works without issues here. Did you test `gnutls-cli --starttls -p 4190 imap.xxxxxx.eu` (see https://wiki.dovecot.org/Pigeonhole/ManageSieve/Troubleshooting#Manual_TLS_Login)?

**Comment by dragoangel** [comment]
Sieve over TB working ok. Do you use correct hostname? As by default mailcow will not request cert for not mailcow_fqdn+autodiscovery.*

**Comment by Cyberknight234** [comment]
> 
> 
> managesieve (and starttls) works without issues here. Did you test `gnutls-cli --starttls -p 4190 imap.xxxxxx.eu` (see https://wiki.dovecot.org/Pigeonhole/ManageSieve/Troubleshooting#Manual_TLS_Login)?

Hello:) 
The output is:

Processed 129 CA certificate(s).
Resolving 'imap.xxxxxxxxx.eu:4190'...
Connecting to '2a03:4000:34:522:981b:xxxx:xxxx:xxxx:4190'...

- Simple Client Mode:

"IMPLEMENTATION" "Dovecot Pigeonhole"
"SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext vacation-seconds editheader imapflags notify imapsieve vnd.dovecot.imapsieve"
"NOTIFY" "mailto"
"SASL" ""
"STARTTLS"
"VERSION" "1.0"
OK "Dovecot ready."

**Comment by Cyberknight234** [comment]
> 
> 
> Sieve over TB working ok. Do you use correct hostname? As by default mailcow will not request cert for not mailcow_fqdn+autodiscovery.*

Hello:)

my mail account is integrated in thunderbird. The Sieve plugin uses the same imap settings to connect (?). So imap.xxxxxx.eu is as described above.

**Comment by waja** [comment]
> The output is:
> 
> ```
> Processed 129 CA certificate(s).
> Resolving 'imap.xxxxxxxxx.eu:4190'...
> Connecting to '2a03:4000:34:522:981b:xxxx:xxxx:xxxx:4190'...
> 
> Simple Client Mode:
> "IMPLEMENTATION" "Dovecot Pigeonhole"
> "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext vacation-seconds editheader imapflags notify imapsieve vnd.dovecot.imapsieve"
> "NOTIFY" "mailto"
> "SASL" ""
> "STARTTLS"
> "VERSION" "1.0"
> OK "Dovecot ready."
> ```

So your connection via StartTLS is working well. I see no issue on the server side.

**Comment by Cyberknight234** [comment]
thanks for the help. i have contacted the sieve developers to find out what the problem could be.
