### ISSUE TITLE
Process external calendar invite or invite response messages in the backend

### ISSUE THREAD

**Issue by mkrecek234** [mailcow/mailcow-dockerized#4094]
## Summary

In order to have mailcow as a full-fledged Exchange or Google Mail/Calendar replacement, the only thing missing is proper handling of calendar invitation logic. Responses on sent external email invitations are not processed automatically, and depend on the email client (e.g., Apple Mail will not update the calendar invitation status). Google and Exchange are capable of handling this by processing incoming emails automatically (invitation accepts, rejects, etc.).

## Motivation

Make mailcow be the complete replacement for Exchange Mail/Calendar or Google Mail/Calendar and thus get a much broader user base, as there are not other alternatives where mail + calendar work integrated.

## Additional context

Situation 1: 
- You invite someone via a CalDAV client with mailcow connected. Mails are sent properly, and e.g., an Exchange recipient can accept it out of the email or calender.
- Mailcow meeting organizer will receive an "Accepted" email, but this will not be reflected in the CalDAV calendar. (same with rejects) - example: Apple Mail

Situation 2:
- An external person invites a mailcow user to a meeting
- The calendar invite will not be shown automatically in the calendar, but only as an email. (e.g. Apple iOS will not show the invitation in the calendar, nor will it allow to respond to the invitation from the mail program)
- You can add the ICS manually to a calendar, but this will not render a "Accept" email to the organizer of the event.

PLEASE think of parsing calendar invitation/response emails automatically - MAILCOW has the great benefits that it could integrate Mail and CalDAV, no meaningful other project could do this.

I would be happy to support this project in development.

**Comment by mkuron** [comment]
Duplicate of #3639. As long as SOGo doesn‘t provide the necessary infrastructure for this, Mailcow won‘t have this feature.
