### ISSUE TITLE
API: quarantine/all returns empty JSON object instead of array

### ISSUE THREAD

**Issue by max-baz** [mailcow/mailcow-dockerized#4096]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Very similar to https://github.com/mailcow/mailcow-dockerized/issues/3738, `/api/v1/get/quarantine/all` returns `{}` instead of `[]` when there are no objects.

If I'm right, the request comes here:

https://github.com/mailcow/mailcow-dockerized/blob/8f52068523ca597c98e4c0e03fc128987ff081f7/data/web/json_api.php#L1168-L1172

And I believe here returns `{}`:

https://github.com/mailcow/mailcow-dockerized/blob/8f52068523ca597c98e4c0e03fc128987ff081f7/data/web/json_api.php#L322-L323

This function is used in many many places, and I'm sure it's often desirable to return `{}`.

Do you think it's possible somehow to make it detect if the function needs to return `[]` if the passed argument is an array?

## Reproduction

Call `/api/v1/get/quarantine/all` when there are no quarantine objects.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Linux 5.10.32 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 8 cores, 16GB |
| Docker Version (`docker version`) | 19.03.15 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | Traefik |

No changes, no custom iptables rules or DNS issues.

**Comment by andryyy** [comment]
Hi,

Thank you, will be fixed in a bit.

**Comment by andryyy** [comment]
Should be fixed. :) Can you confirm and close?

**Comment by max-baz** [comment]
Confirmed, thanks!
