### ISSUE TITLE
Error in prerequisites.inc.php after reinstall

### ISSUE THREAD

**Issue by niklasfyi** [mailcow/mailcow-dockerized#41]
I deleted all images and the git folder and installed it again. Don't ask why ;)

Now I get this error:

> Warning: Cannot modify header information - headers already sent by (output started at /web/inc/prerequisites.inc.php:46) in /web/inc/prerequisites.inc.php on line 51
> 
> Fatal error: Uncaught Error: Call to a member function prepare() on null in /web/inc/functions.inc.php:68 Stack trace: #0 /web/inc/prerequisites.inc.php(96): init_db_schema() #1 /web/index.php(2): require_once('/web/inc/prereq...') #2 {main} thrown in /web/inc/functions.inc.php on line 68
> 

Does anyone know why I get this?

**Comment by andryyy** [comment]
Have you also deleted the volumes? docker-compose down -v (this will delete all mail etc.)

**Comment by niklasfyi** [comment]
Thanks. That fixed it :+1:
