### ISSUE TITLE
Deploy dovecot with riseup's `trees` plugin

### ISSUE THREAD

**Issue by vbrandl** [mailcow/mailcow-dockerized#410]
[Riseup](https://riseup.net) wrote a dovecot plugin to encrypt mailboxes in a way that the administrator cannot access the users mail anymore. The plugin is called `trees` and can be found [here](https://0xacab.org/riseuplabs/trees).

It would be great to have this plugin pre-compiled in the dovecot docker container so it can be easily activated or deactivated via the dovecot configfile.

**Comment by andryyy** [comment]
Right now mailcow is built with the mail crypt plugin by Dovecot itself. It even creates a key pair, but the plugin is not activated. You can find all parameters in data/conf/dovecot/dovecot.conf commented out. 

It is intended to be used when the vmail volume is an external storage like AWS storage etc. 
The key remains on the Docker host and is never readable from the vmail volume. 

Iirc Posteo wrote such a plugin, too. But it is not useable for newer Dovecot versions. And, well, it is third party after all. 

The Dovecot mail crypt plugin is great! The single key configuration is actually very stable. I recommend using it on EWS storage etc. But obviously not needed when the storage is the same machine as the Docker host. :-)



Beste Grüße 
André

**Comment by vbrandl** [comment]
That's a pretty useful plugin but if I got it right, it is still possible for the administrator to access a users mailbox since he is in control of the encryption keys.

The plugin I posted makes it impossible for the administrator to access the mail even if he wanted to (as long as he doesn't have the users password). This is a nice privacy feature when offering mailboxes to other users. So I think both plugins serve different purposes.

**Comment by andryyy** [comment]
You can try to compile it against mailcows Dovecot. But it is a very strange setup in which the administrator has absolutely no access to those files. An admin can still just read the TCP stream, too. I don't really see a use case for this. 

I'm not even sure if we could fix an index with this plugin (just an example) or learn message as ham/spam. :/ And after all we would still be able to sniff the stream as mentioned above. 

Do you know who supports this plugin or what to do if something crashes? Is data lost on a crash?

I see no possible use for this in production. :/  It is a very rare setup in my opinion.

**Comment by vbrandl** [comment]
Fair enough. This really is a rare usecase.

The plugin is developed and used in production by riseup.net. Their usecase is that they do not want to obey court orders that ask for a user's mail. Using this plugin it is technically impossible for them so they cannot be forced to spy on users.

I will close this issue and maybe try compiling it on my own.

**Comment by K2rool** [comment]
I quick look at the plugin you on it says 
<pre>
 How it works:

On IMAP log in, the user's cleartext password is passed to the plugin.
The plugin creates an argon2 digest from the password.
</pre>

It look's like a nice plugin but if the argon2 digest is based on the password wont it break if user changes his password

**Comment by andryyy** [comment]
I just asked the cmouse on IRC, he confirmed we can do this with the built-in mail_crypt plugin, too. I only tested the global mail_crypt though.

**Comment by jaltek** [comment]
To catch this one up:
https://wiki.dovecot.org/Plugins/MailCrypt


> There can be a single encryption key for the whole system or each user can have a key of their own. The used cryptographical methods are widely used standards and keys are stored in portable formats, when possible. 


and

> This feature is available in v2.2.27+. Using per-folder keys is not considered production quality, but global keys are fine. 

The encryption keys still resides on the host machine, sure. But by using the "per-folder keys" the password to the keys will be passed during the IMAP login.
Did you had the time to test the per-folder keys functionality in the meantime?
