### ISSUE TITLE
Small visual display errors in UI (horizontal scrollbars)

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4106]
Hello,

The new UI looks (icons and font) quite nice, but there are a few visual display errors.

In several tables there are horizontal scrollbars.

For example here:
![82e52b4c-874a-4d84-825b-f066b708f226](https://user-images.githubusercontent.com/3801660/119293115-0b6d8880-bc52-11eb-835a-d3818a9c9db7.png)

But it could also be that there are other places in the UI where this occurs.

Thanks in advance.

**Comment by andryyy** [comment]
The overflow scrolls have always been there.

**Comment by omexlu** [comment]
Never remarked :) looks not nice but OK for me.

Thanks for the answer.
