### ISSUE TITLE
importing dkim keys?

### ISSUE THREAD

**Issue by strowi** [mailcow/mailcow-dockerized#411]
Hi,

is there a way to import existing dkim-keys? i'm still working through the dockerized-documentation and configs..

regards,
strowi

**Comment by andryyy** [comment]
Hi,
There is no such feature yet. It would be easiest to just create a new selector and add it to your DNS.

**Comment by stevesbrain** [comment]
It would theoretically be possible to create all relevant redis entries if someone had, say, 50 existing DKIM keys to import - may be quicker to script redis entries than change DNS? (unless I'm mistaken)

**Comment by andryyy** [comment]
Yes, that's possible. :)

**Comment by strowi** [comment]
thx, i will look into that... my current dns-provider has issues.. so i can't get in contact with him..;\

**Comment by andryyy** [comment]
I will close this, it is implemented now. :)
