### ISSUE TITLE
Local sending throw Temporary lookup failure

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#4113]
Hi guys, 

I'm facing a problem when sending emails with local addresses. The error appears when some user is sending mails, the error is:

`Server error: 451 4.3.0 <mail@domain.com>: Temporary lookup failure`

Below is the log from Postfix:

![image](https://user-images.githubusercontent.com/205403/120036550-8c63b180-bfbd-11eb-8677-beb6f6cb20f0.png)

If you have any idea what's going please let me know.

Regards.

**Comment by patschi** [comment]
Bug template ignored. Therefore closing,.
