### ISSUE TITLE
Can send with unauthorized FROM using msmtp

### ISSUE THREAD

**Issue by brandoningli** [mailcow/mailcow-dockerized#4115]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

When sending mail via MSMTP from another server on the network, an authorized user can send mail with any address in the From header, as if it's not checked. When trying the same from Thunderbird, an error is returned. This allows for impersonation. The message headers have a return-path to the authenticated user. MXToolbox confirms that the server is not an open relay.

The following addresses are used below:
+ `auser@mydomain.com` is the server user sending mail via MSMTP
+ `noexist@mydomain.com` is the address it is trying to send mail as, which isn't a valid mailbox nor a valid alias
+ `me@anotherdomain.com` is my inbox where it is sending mail to.

Both `mydomain.com` and `anotherdomain.com` are run on the same mailcow server.

```bash
$ git rev-parse HEAD
e6304ab9dd63ed4b6d5d4072a92ea47729979c92
```

## Logs

```
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/submission/smtpd[197369]: connect from unknown[internalIP]
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/submission/smtpd[197369]: TLS SNI mydomain.com from unknown[internalIP] not matched, using default chain
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/submission/smtpd[197369]: Anonymous TLS connection established from unknown[internalIP]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/submission/smtpd[197369]: 73B50580E30: client=unknown[internalIP], sasl_method=PLAIN, sasl_username=auser@mydomain.com
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/cleanup[197374]: 73B50580E30: replace: header Received: from localhost (unknown [internalIP])??(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)?? key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA2 from unknown[internalIP]; from=<auser@mydomain.com> to=<me@otherdomain.com> proto=ESMTP helo=<localhost>: Received: from [127.0.0.1] (localhost [127.0.0.1]) by localhost (Mailerdaemon) with ESMTPSA id 73B50580E30??for <me@anotherdomain.com>; Sat, 29 May 2021 15:47:12 -0500 (CDT)
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/cleanup[197374]: 73B50580E30: message-id=<>
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/qmgr[378]: 73B50580E30: from=<auser@mydomain.com>, size=359, nrcpt=1 (queue active)
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/submission/smtpd[197369]: disconnect from unknown[localIP] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/lmtp[197470]: 73B50580E30: to=<me@anotherdomain.com>, relay=dovecot[anIPv6Address]:24, delay=0.16, delays=0.1/0.01/0.01/0.04, dsn=2.0.0, status=sent (250 2.0.0 <me@anotherdomain.com> aA3PIlCosmC70iQARgDJPA Saved)
postfix-mailcow_1    | May 29 15:47:12 f9ed38f6ad9b postfix/qmgr[378]: 73B50580E30: removed

```

## Reproduction

Send a message via `msmtp` like below:
```
printf "Subject: Test
To: me@anotherdomain.com
From: Test <noexist@mydomain.com>

This is a test.
" | sudo /usr/bin/msmtp me@anotherdomain.com

```

`/etc/msmtprc` configuration
```
account default
port 587
tls on
tls_certcheck off
auth on
host myserver.mydomain.com
user auser@mydomain.com
from auser@mydomain.com
password mysupersecretpasswordgoeshere
```

`/etc/aliases` file
```
# See man 5 aliases for format
postmaster: root
web: root
www-data: root
root: auser@mydomain.com
```

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu Server 20.04.2 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VMWare ESXi |
| Server/VM specifications (Memory, CPU Cores) | 2 Core, 3GB memory |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) | 1.29.1, build c34c88b2 |
| Reverse proxy (custom solution) | N/A |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by Adorfer** [comment]
> connect from unknown[internalIP]

Please fix your network setup. 
This has NOTHING to do with msmtp, since the logs already show during connection setup: the IP is seen as in "own networks"->totally whitelisted.

**Comment by brandoningli** [comment]
> > connect from unknown[internalIP]
> 
> Please fix your network setup.

The network setup is irrelevant. It connects fine. The issue lies in validating that a user is able to send from a particular address once connected.

**Comment by Adorfer** [comment]
No, it's coming from "own networks", which is trusted. Do not put untrusted machines in the "my networks" ip range!
Please read: 
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-trust_networks/

**Comment by brandoningli** [comment]
You're going to have to be a bit more specific about what setting you're referring to. Like I said, trying the same thing from Thunderbird in the same IP range yields vastly different results, unless I set up this range to be the one IP address of this server.

**Comment by brandoningli** [comment]
> No, it's coming from "own networks", which is trusted. Do not put untrusted machines in the "my networks" ip range!
> Please read:
> https://mailcow.github.io/mailcow-dockerized-docs/firststeps-trust_networks/

The only thing in `extra.cf` is a declaration for `myhostname`. There is no declaration for `mynetworks`.

**Comment by brandoningli** [comment]
> No, it's coming from "own networks", which is trusted. Do not put untrusted machines in the "my networks" ip range!
> Please read:
> https://mailcow.github.io/mailcow-dockerized-docs/firststeps-trust_networks/

I've set `mynetworks_style` to host and `mynetworks` to `127.0.0.0/8`, restarted the postfix container, and the logs look identical when attempting to send from an unauthorized address. Previously, both entries were non-existent.

`localIP` is in the 192.168.0.0/16 range

**Comment by brandoningli** [comment]
For what it's worth, I just tried the same thing with both my personal account via msmtp on this server and providing bogus authentication information. On my personal account, I was also able to use unauthorized aliases in the `From` field just fine. When providing bogus authentication information, it returned with an error as expected.

**Comment by geektoor** [comment]
Well, i think you mix smtp protocol "from" user and "data" from user:
The user set as from on SMTP level (the envelope, "MAIL FROM:<bla@bla.mail>") is usually checked against normal sender rules. The smtp data is not. So as long as you set the right user at the envelope, postfix checks will be fine.
Normal mail clients configure the same envelope and the SMTP data. If your client would allow it to be different, it would work the same way.
This is not an issue with mailcow, you might see this as a limitation of postfix (or the login mismatch blocking feature from Postfix). If you really need to get your headers checked, you most likely need a milter or filter thats capable of doing such checks.

So "works as designed" (and you as the owner of the server would still be able to trace the correct user as your logs will tell your what account was used to logon and send the email).

**Comment by brandoningli** [comment]
Well in that case, can we transition this issue into being a feature request to add such a filter into mailcow? Or should I start a new issue for that?

**Comment by geektoor** [comment]
Well, you can of course add an issue for that (I would recommend to create a new one, with a clean statement what and why). There are milter examples available, like https://github.com/magcks/milterfrom, but i don't see this to be generally implemented as there are reasons why envelope and header must not match all times. So this is a somewhat special case that you might want to solve for your setup (and maybe share a doc about it if others need it), but most of the users, at least to my guess, will not need it (and turning it on in general would most likely break other things).
