### ISSUE TITLE
Add filter to check data From field is authorized for current user

### ISSUE THREAD

**Issue by brandoningli** [mailcow/mailcow-dockerized#4116]
## Summary

Currently, only the envelope `From` field is checked to see if the user can send as that address. Therefore, users can still spoof other users by setting the `From` header in the body of the message. Such a filter would check to make sure the `From` header email is also okay for the sender to send mail as.

## Motivation

I'm sure I'm not alone when I think that this check is already being done. The threat of someone with authentication information being able to impersonate any address they want is scary, especially since the mailcow settings make it seem as though it's impossible.

See #4115

**Comment by andryyy** [comment]
Sven already explained it. It's not scary.

This would break many, many setups. 

You can provide a PR with a checkbox to force a match against smtp envelope when authenticated (to highlight it again: that's only possible when authenticated). 

If you want to change it for yourself, create a composite rule, find the forged sender symbol and the authenticated flag. Combine them to a reject. 

You may want to read into envelope from and mime from before proceeding though. :)

**Comment by brandoningli** [comment]
I'm not asking to check `envelope == header`. I'm asking for a check that the address in the header is one the user is authorized to send as, much like how the envelope address is checked that way.

Edit: apologies if I'm getting terms mixed up; the inner workings of SMTP are not my specialty.

**Comment by brandoningli** [comment]
For clarification, in the UI, each mailbox has an "Allow to send as" field. To my understanding, only the envelope from address is checked against this, but not the from address in the data/headers of the message. My request is to add an option to perform this same check (that the address is in the "Allow to send as") against the address in the data/headers.

My point is that right now, with the way things are worded, it seems impossible that mail could appear in one's inbox as from anyone other than the addresses in that list, which is apparently incorrect. At the very least, it'd be worth a clarification there.
