### ISSUE TITLE
Mail from forwarding host rejected/greylisted

### ISSUE THREAD

**Issue by mindsolve** [mailcow/mailcow-dockerized#412]
I have added the mailservers of gmx.net and web.de as forwarding hosts, but mailcow is still greylisting and/or rejecting mails coming from them.

The rspamd log of this example mail over web.de:
![Here is the rspamd log of this example mail over web.de](https://user-images.githubusercontent.com/24863329/27600156-4fb316d2-5b6b-11e7-8b88-b5bda1faaca5.png)

The listing of forwarding hosts inside mailcow
![Here is the listing of forwarding hosts inside mailcow](https://user-images.githubusercontent.com/24863329/27600157-4fb758f0-5b6b-11e7-8d33-86f9276b9070.png)

I already restarted all the services.

Thanks,
mindsolve

**Comment by mkuron** [comment]
Thanks for reporting. That's odd, zero score but still getting greylisted. Could you please post the rspamd logs for that message (`docker-compose logs rspamd-mailcow`)? I'll investigate.

**Comment by andryyy** [comment]
There is no WHITELISTED_FWD_HOST symbol, so a forward host was not matched by the ip.

Score is zero when greylisting happens, it would be reject plus score for the next try.

**Comment by mkuron** [comment]
@mindsolve, are you on current master? Also, what do you see in the Postfix whitelist log output per `docker-compose logs postfix-mailcow | grep whitelist_forwardinghosts`? Restarting services after adding hosts to the list should not be necessary as I don't think they are cached anywhere.

**Comment by mindsolve** [comment]
@mkuron 
1.: Here are the logs from Rspamd: https://pastebin.com/sKCa96iy
2.: Most possibly not on latest master, as I have not updated for ~4weeks (if that is what you mean)
   -> with the command `docker-compose logs postfix-mailcow | grep whitelist_forwardinghosts | grep " 212\."`, the sender ip is not on the list. (see first screenshot), or have a look at the paste here: https://pastebin.com/qszFc5sh
(Thats the output of your command, cut at ~17:30 until now)

**Comment by mkuron** [comment]
Could you try updating first? The forwarding hosts database was moved to redis about a month ago. Perhaps your rspamd image is newer than your git.

**Comment by mindsolve** [comment]
@mkuron Sorry for the long time, I just updated everything, and will report back if emails are still getting greylisted.

**Comment by mindsolve** [comment]
I FOUND OUT WHY!

For all others finding this: If a server of 1&1 thinks a outbound mail is spam, it will get send out by the servers here: 82.165.159.40/31. Those adresses are blacklisted in every existing list & do not belong to the list of MX'es of gmx.net/ gmx.de/ web.de.

As such, they are not added to the forwarding rule. If you want to bypass the blacklisting from 1&1, you manually have to add 82.165.159.40/31 to your forwarding hosts.

Sorry for causing this much headache.

**Comment by mkuron** [comment]
Turns out this was actually a bug, but it's fixed on rspamd master: https://github.com/vstakhov/rspamd/pull/1753. Forwarding host entries that were networks have been broken since d64ed65575e3a287a78ba7f976b96dd1006f7a9a. So this issue will be fixed once Mailcow updates to the next rspamd version.

**Comment by mindsolve** [comment]
Yessss. THANK YOU!
