### ISSUE TITLE
Dovecot container restarting every few seconds, because of missing file "/etc/dovecot/last_login"

### ISSUE THREAD

**Issue by Yoshi-081** [mailcow/mailcow-dockerized#4121]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
On Fresh install, dovecot restarting every few seconds because of missing file "/etc/dovecot/last_login:".

If the file is created manually, dovecot works.

touch /opt/mailcow-dockerized/data/conf/dovecot/last_login

## Logs
root@mail:/opt/mailcow-dockerized/data/conf/dovecot# docker logs mailcowdockerized_dovecot-mailcow_1
Waiting for database to come up...
Waiting for database to come up...
Uptime: 1  Threads: 2  Questions: 6  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 6.000
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 3  Threads: 2  Questions: 9  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 3.000
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 5  Threads: 3  Questions: 87  Slow queries: 0  Opens: 39  Open tables: 27  Queries per second avg: 17.400
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 7  Threads: 3  Questions: 126  Slow queries: 0  Opens: 55  Open tables: 24  Queries per second avg: 18.000
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 9  Threads: 3  Questions: 170  Slow queries: 0  Opens: 79  Open tables: 24  Queries per second avg: 18.888
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 11  Threads: 3  Questions: 276  Slow queries: 0  Opens: 124  Open tables: 14  Queries per second avg: 25.090
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 1  Threads: 2  Questions: 1  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 1.000
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 9  Threads: 2  Questions: 14  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 1.555
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 23  Threads: 3  Questions: 2807  Slow queries: 0  Opens: 25  Open tables: 14  Queries per second avg: 122.043
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 49  Threads: 3  Questions: 8505  Slow queries: 0  Opens: 25  Open tables: 14  Queries per second avg: 173.571
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 101  Threads: 13  Questions: 9929  Slow queries: 0  Opens: 110  Open tables: 49  Queries per second avg: 98.306
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 162  Threads: 13  Questions: 10824  Slow queries: 0  Opens: 119  Open tables: 58  Queries per second avg: 66.814
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 485: plugin/6/last_login_dict: Can't open file /etc/dovecot/last_login: No such file or directory
Uptime: 223  Threads: 10  Questions: 10847  Slow queries: 0  Opens: 119  Open tables: 58  Queries per second avg: 48.641
Adding user `vmail' to group `tty' ...
Adding user vmail to group tty
Done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  101k  100  101k    0     0   936k      0 --:--:-- --:--:-- --:--:--  936k
20_blatspammer.cf
70_HS_body.cf
70_HS_header.cf
{"msg":"command completed successfully","type":"success"}
2021-06-04 19:20:02,926 INFO Set uid to user 0 succeeded
2021-06-04 19:20:02,929 INFO supervisord started with pid 1
2021-06-04 19:20:03,931 INFO spawned: 'processes' with pid 161
2021-06-04 19:20:03,932 INFO spawned: 'dovecot' with pid 162
2021-06-04 19:20:03,935 INFO spawned: 'syslog-ng' with pid 163
[2021-06-04T19:20:03.996209] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
Jun  4 19:20:04 f153d95ee4a0 syslog-ng[163]: syslog-ng starting up; version='3.19.1'
Jun  4 19:20:04 f153d95ee4a0 dovecot: master: Dovecot v2.3.14 (cee3cbc0d) starting up for imap, sieve, lmtp, pop3
2021-06-04 19:20:05,026 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-06-04 19:20:05,026 INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-06-04 19:20:05,027 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Jun  4 19:20:10 f153d95ee4a0 dovecot: lmtp(180): Connect from 172.22.1.4
Jun  4 19:20:10 f153d95ee4a0 dovecot: lmtp(180): Disconnect from 172.22.1.4: Client has quit the connection (state=READY)
Jun  4 19:20:10 f153d95ee4a0 dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
Jun  4 19:20:10 f153d95ee4a0 dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250
Jun  4 19:20:10 f153d95ee4a0 dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250
Jun  4 19:20:49 f153d95ee4a0 dovecot: lmtp(180): Connect from 172.22.1.4
Jun  4 19:20:49 f153d95ee4a0 dovecot: lmtp(180): Disconnect from 172.22.1.4: Client has quit the connection (state=READY)
Jun  4 19:20:49 f153d95ee4a0 dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
Jun  4 19:20:49 f153d95ee4a0 dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250
Jun  4 19:20:49 f153d95ee4a0 dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250
Jun  4 19:21:23 f153d95ee4a0 dovecot: lmtp(180): Connect from 172.22.1.4
Jun  4 19:21:23 f153d95ee4a0 dovecot: lmtp(180): Disconnect from 172.22.1.4: Client has quit the connection (state=READY)
Jun  4 19:21:23 f153d95ee4a0 dovecot: imap-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=172.22.1.4, lip=172.22.1.250, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)

## Reproduction

- New VM
- install docker and docker-compose
- Clone the github repository
- genearte config
- docker-compose up -d
- docker logs mailcowdockerized_dovecot-mailcow_1 shows error and container is restarting everey few seconds

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4096 MB, 2 Cores |
| Docker Version (`docker version`) | 20.10.7 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |

**Comment by andryyy** [comment]
Thanks!
