### ISSUE TITLE
Make ejabberd (xmpp) service optional

### ISSUE THREAD

**Issue by jman-schief** [mailcow/mailcow-dockerized#4123]
## Summary

In 21bc7d02d2f3279a87cc09c14f1b9e8d4ff11198 the ejabberd service was introduced to the docker compose recipe. No option to disable it (afaics). 

Would it make sense to add a `SKIP_EJABBERD` option instead of working my way to manually disabling it from the `docker-compose.yml` file? 

## Motivation

I tried to track down a discussion about the rationale on why introducing ejabberd to mailcow but could not find any, I've just found a mention in this [forum thread](https://community.mailcow.email/d/651-commits-on-feb-11-2021-jabber/15). I'd like to fully understand why it is needed.

thanks!

**Comment by andryyy** [comment]
It is not started by default for any domain. Not even a service is 
launched.

There will not be a discussion, sorry. :)

------ Originalnachricht ------
Von: "jman-schief" ***@***.***>
An: "mailcow/mailcow-dockerized" ***@***.***>
Cc: "Subscribed" ***@***.***>
Gesendet: 05.06.2021 12:10:15
Betreff: [mailcow/mailcow-dockerized] Make ejabberd service optional 
(#4123)

**Comment by jman-schief** [comment]
@andryyy I appreciate your quick reply but I feel that my points are still unanswered. I'll try to clarify my questions.

1) The service looks to be launched indeed, I see ports TCP/5443,5222,5269 listening (but not exposed to the internet)

2) Why having ejabberd service starting if by default if it is not used (if I understand your reply)?

3) "There will not be a discussion" only partially answers my question: why embeddding an XMPP service in mailcow?

In my (humble) point of view, a sysadmin would probably prefer an unused service **not running**.

**Comment by mkuron** [comment]
The container is running because docker-compose does not allow selectively disabling containers. However, there is [nothing running inside the container](https://github.com/mailcow/mailcow-dockerized/blob/d7ecf899c86a4cf6377185562239f0e41a9c906d/data/Dockerfiles/ejabberd/docker-entrypoint.sh#L95-L98) but a `sleep` command, so it is consuming pretty much zero resources and doesn't expose anything to the network. We do the same with the optional SOLR container.
```
# docker-compose exec solr-mailcow ps axu
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   5488   208 ?        Ss   May26   0:00 /bin/bash /solr
root         7  0.0  0.0   4048    60 ?        S    May26   0:00 sleep 365d
root        15  0.0  0.0   9392  3160 pts/0    Rs+  23:50   0:00 ps axu
# docker-compose exec ejabberd-mailcow ps axu
PID   USER     TIME  COMMAND
    1 ejabberd  1:04 tini -g -- sleep 365d
   74 ejabberd  0:00 sleep 365d
   99 ejabberd  0:05 /home/ejabberd/bin/epmd -daemon
  133 root      0:00 ps axu
```
Hmm, there is an `epmd` process running in there for some reason. @andryyy, any ideas why that gets started?

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack

**Comment by jman-schief** [comment]
reference to commit https://github.com/mailcow/mailcow-dockerized/commit/f078a514f000a918868c73a5d409e2953a6499fe

thanks to all maintainers for taking into consideration the community feedback, really appreciated :+1:
