### ISSUE TITLE
BAD_SUBJECT_00 - fp if brackets in subject

### ISSUE THREAD

**Issue by realizelol** [mailcow/mailcow-dockerized#4125]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

If the subject contains brackets, the rule "BAD_SUBJECT_00" will be fired.
What I found is that the file - "http://nullnull.org/bad-subject-regex.txt" - contains "\d+"..
as I removed these lines, the rule wasn't fired. So I was trying to find out what this "\d+" is.
But I didn't found the correct meaning. But in [rspamd/headers.lua](https://github.com/rspamd/rspamd/blob/master/rules/regexp/headers.lua) this is always "\\d+" and if I download and sedded these lines:

```
curl http://nullnull.org/bad-subject-regex.txt > /etc/rspamd/custom/bad-subject-regex.txt
sed -i "s/\\d+/\\\\d+/g" /etc/rspamd/custom/bad-subject-regex.txt
```
I can sent subject for e.g. `Alwin Moin Moin` and the subject was recognized as "BAD_SUBJECT_00" by rspamd
as it should be and if I sent something correct with brackets the email won't get recognized by "BAD_SUBJECT_00"
as before.

## Logs

Subject: Unraid Status: Alert [UNRAID] - Disk 1 is low on space (91%)
Subject: Re: [mailcow/mailcow-dockerized] Make ejabberd (xmpp) service optional (#2)
Both mails were moved to spam folder.

## Reproduction

Send an email with brackets "( )" in the subject your mailcow mail account.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 - Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4GB, 4 Cores |
| Docker Version (`docker version`) | 20.10.7 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | - |

**Comment by andryyy** [comment]
Thank you once again @realizelol :)

Can you check if it's fixed now?

**Comment by christianbur** [comment]
I had the same problem with two emails. 


BAD_SUBJECT_00 (20) [XXXX24 - Eingangsbestätigung Bestellung Nr. 444444444 vom 06.06.2021]

BAD_SUBJECT_00 (20) [Corona Besuchermanagement_Reservierung Naturbad xxxxxx_#5555->Nachname, Vorname  xPers 2021-06-04 13:30:00]

**Comment by weyhmueller** [comment]
It seems to me that the regex `[0-9]+.+e.+[0-9]+` is problematic in general.

It checks for:
- One or more digits
- followed by at least one char
- followed by an 'e'
- followed by at least one  char
- followed by one or more digits

That matches the first subject of @realizelol as well as both of @christianbur and also some of mine as well:
Unraid Status: Alert [UNRAID] - Disk **1 is low on space (91**%)
XXXX**24 - Eingangsbestätigung Bestellung Nr. 444444444** vom 06.06.2021
Corona Besuchermanagement_Reservierung Naturbad xxxxxx_#**5555->Nachname, Vorname xPers 2021**-06-04 13:30:00
Check_MK: xxxxxx.example.com/Interface br-4ff6f**54ef82**a OK -> CRIT
[Fail**2Ban] sshd: banned 209**.XXX.XXX.XXX from xxxxxx.example.com

**Comment by waja** [comment]
Here it matched `Bug#989515: ITP: golang-github-jinzhu-copier -- Deepcopy for golang, copy value from struct to struct and more` ... this is a common format on a Debian mailinglist.

**Comment by andryyy** [comment]
Can you attach an eml?

**Comment by andryyy** [comment]
@weyhmueller I don't see `[0-9]+.+e.+[0-9]` there.

**Comment by waja** [comment]
> Can you attach an eml?

As it was rejected (cause to high score), but it is basically
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989514;mbox=yes;msg=5.

Taken from Rspamd history:
```
BAD_SUBJECT_00 (20) [Bug#989515: ITP: golang-github-jinzhu-copier -- Deepcopy for golang, copy value from struct to struct and more]
MISSING_MIME_VERSION (2)
AUTH_NA (1)
BAYES_HAM (-5.49988) [99.99%]
IP_REPUTATION_HAM (-0.60331) [asn: 16316(-0.16), country: DE(-0.00), ip: 217.145.99.35(-0.44)]
RCVD_IN_DNSWL_MED (-0.2) [2001:41b8:202:deb:216:36ff:fe40:4002:received]
MAILLIST (-0.1875) [generic]
RCVD_IN_DNSWL_LOW (-0.1) [2607:f8f0:614:1::1274:39:received]
MIME_GOOD (-0.1) [text/plain]
MX_GOOD (-0.01) []
HAS_LIST_UNSUB (-0.01)
MID_RHS_MATCH_FROMTLD (0)
RCVD_TLS_LAST (0)
RCPT_COUNT_ONE (0) [1]
R_SPF_NA (0) [no SPF record]
R_DKIM_NA (0)
HAS_REPLYTO (0) [siretart@tauware.de]
FORGED_RECIPIENTS_MAILLIST (0)
FORGED_SENDER_MAILLIST (0)
WHITELISTED_FWD_HOST (0) [217.145.99.35]
DMARC_NA (0) [tauware.de]
RCVD_COUNT_SEVEN (0) [7]
REPLYTO_DN_EQ_FROM_DN (0)
WL_FWD_HOST (0)
MIME_TRACE (0) [0:+]
TO_DN_NONE (0)
FORGED_SENDER_VERP_SRS (0)
BCC (0)
FROM_HAS_DN (0)
FROM_NEQ_ENVFROM (0) [siretart@tauware.de, bounce-debian-devel=user=test.org@lists.debian.org]
ARC_NA (0)
RCPT_MAILCOW_DOMAIN (0) [test.org]
ASN (0) [asn:16316, ipnet:217.145.96.0/20, country:DE]
REPLYTO_ADDR_EQ_FROM (0)
```

**Comment by weyhmueller** [comment]
> @weyhmueller I don't see `[0-9]+.+e.+[0-9]` there.

@andryyy: I don't know how the list  at  `http://nullnull.org/bad-subject-regex.txt`  is generated, but I received a file starting with:
```
/[0-9]+.+1Sie.+erhalten.+2x.+Mastercard.+bezahlen.+1x/i
/[0-9]+.+8m.+Release.+Final.+Notice/i
/[0-9]+.+Ack.+Mail.+Packing.+List.+Ref/i
/[0-9]+.+Akupressurpunkten.+bekommen.+Migräneattacke.+ganz.+schnell.+Griff/i
/[0-9]+.+Ästhetik.+Seminare.+Juni.+Fadenlifting.+Mesotherapie.+u.+Faltenunterspritzung/i
/[0-9]+.+Ausgaben.+[0-9]+.+Prämie/i
/[0-9]+.+Ausgaben.+lesen.+[0-9]+.+Stick.+gratis.+sichern/i
/[0-9]+.+Ban.+Sunglasses.+[0-9]+.+Special.+Sale.+Shop/i
/[0-9]+.+beim.+Kredit.+Smava.+sparen/i
/[0-9]+.+Bettzimmer.+Krankenhaus.+plus.+[0-9]+.+Euro.+Gutschein/i
/[0-9]+.+Bettzimmer.+Krankenhaus.+plus.+[0-9]+.+Gutschein/i
/[0-9]+.+Cent.+CoV.+Speichel.+Schnelltest/i
/[0-9]+.+Cent.+helfen.+gerade/i
/[0-9]+.+Cent.+Pflichtmasken/i
/[0-9]+.+Cent.+Schnelltest.+[0-9]+.+bzw.+[0-9]+.+St.+Einfacher.+Speichel.+Test/i
/[0-9]+.+Cent.+Sonderposten.+Atemschutzmasken/i
/[0-9]+.+Darlehensangebot.+bewerben/i
/[0-9]+.+Dinge.+krumme.+Zehen.+verursachen.+zeigen.+Lösung/i
/[0-9]+.+Dinge.+Zehen.+deformieren.+Lösung/i
/[0-9]+.+e.+[0-9]+/i
```
just now.

**Comment by andryyy** [comment]
Indeed, I have missed that. O_O

**Comment by realizelol** [comment]
between 11:20 and 12:12 (german local time) this was fixed, then it reappeared again. But this seems to be that regex what @weyhmueller already mentioned.  The last comment of you here ([855375796](https://github.com/mailcow/mailcow-dockerized/issues/4125#issuecomment-855375796)) don't tagged as "BAD_SUBJECT_00(6.00)" again.

So this issue seems to be solved. Thank you.

**Comment by andryyy** [comment]
For some reason it was not filtered, I need to check why. Must be a race condition in my script.

**Comment by pquan** [comment]
I can paste another problematic subject: Gitlab notifications like the one below:

`Re: Kiss | Bug #24067: Some irrelevant message here. (!1974)`

I wonder how this would even make it in. `[0-9]+.+e.+[0-9]+` : Two numbers with some text inside containing the e vowel will match very easily on most notifications with some data in the subject! It should be removed flat out.

**Comment by andryyy** [comment]
? It's not in there anymore. :)

**Comment by pquan** [comment]
I updated mailcow on June-5th 2021. When was this removed?

I sure am getting new blocked mail today. This morning:
`Fwd: Re: Analyzer O2/He S/N 4839432`
This was a forwarded mail for an issue.

**Comment by realizelol** [comment]
about 23 hours ago.

The relevant part is in this text file: [http://nullnull.org/bad-subject-regex.txt](http://nullnull.org/bad-subject-regex.txt)
So there was no need to add a commit.

best regards
realizelol

**Comment by pquan** [comment]
Lol. how do I update only the rspamd container?

**Comment by pquan** [comment]
thank you. I found an unrelated ipv6 connection problem to that site, so I was not updated. all is good.

**Comment by realizelol** [comment]
Is this really invoked by BAD_SUBJECT_00 ?

Can't reproduce it:
```
for NULLNULL in $(curl -s http://nullnull.org/bad-subject-regex.txt); do
  echo '/Fwd: Re: Analyzer O2/He S/N 4839432/i' | grep -iE "$NULLNULL"
done
```
as example this would result a match `/warwick spencer sent personal message/i`
```
for NULLNULL in $(curl -s http://nullnull.org/bad-subject-regex.txt); do
  echo '/warwick spencer sent personal message/i' | grep -iE "$NULLNULL"
done
```

**Comment by pquan** [comment]
That is because I was using an old version of that file (due to ipv6 connectivity issues to the same site). It's ok now.
