### ISSUE TITLE
Adding comments for temporary email aliases

### ISSUE THREAD

**Issue by waja** [mailcow/mailcow-dockerized#4132]
## Summary

It would be very helpful to have the possibility to add a (optional) comment when creating temporary email aliases.

## Motivation

When using temporary email aliases there is no connection for it's purpose, as the user part is 'non speaking'. With comments added to the addresses users would be able to link the purpose to the addresses and so they can be deleted or extended if needed. This is hardly possible without knowing what those addresses are used for by themself.

**Comment by waja** [comment]
Is this something that sounds useful for you?

**Comment by marekfilip** [comment]
I would also love to see such feature. Think there is also a duplicate for this issue #4407

**Comment by MAGICCC** [comment]
Indeed, I close this one then
