### ISSUE TITLE
Support for ARM64 on AWS, OCI, etc.

### ISSUE THREAD

**Issue by magnetic6** [mailcow/mailcow-dockerized#4136]
## Summary

Now that high performance and reliable ARM64 servers are readily available at cloud providers, mailcow should provide builds to support this architecture.

## Motivation

ARM64 servers are available at some providers at a lower cost than AMD64.

In many situations, ARM64 servers use less electricity and can be better for the environment. 

## Additional context

We can use the Oracle Cloud free tier to begin supporting ARM64. They will provide up to 4 instances totaling 24GB RAM and 200GB block storage for free without a time limit.

**Comment by andryyy** [comment]
That's a duplicate.

**Comment by MAGICCC** [comment]
Indeed of https://github.com/mailcow/mailcow-dockerized/issues/879

**Comment by magnetic6** [comment]
Why are both issues closed? Does this mean mailcow will not support ARM64?

**Comment by mkuron** [comment]
@magnetic6, please read https://github.com/mailcow/mailcow-dockerized/issues/879#issuecomment-849912531 and some of my earlier comments there. Summary: There is currently no reason to get an ARM64 cloud server instead of an Intel cloud server. Presently there is no price or performance advantage (and you shouldn't depend on Oracle's free tier to run production services), but I am certain there will be within approximately two years. Only once that is the case, and once one of the Mailcow core developers actually runs Mailcow on an ARM64 server themselves, will it start making sense to support Mailcow there.

**Comment by magnetic6** [comment]
It is worth noting that not all ARM solutions are free, in fact I do pay for the vast majority our ARM infrastructure. If you think ARM is only given away for free, that is not true.

**Comment by mkuron** [comment]
That is not what I said. I am not aware of any ARM solution that is significantly cheaper than x86 at equal Mailcow performance. And since we strongly encourage running Mailcow on a dedicated (virtual) server because of the complexity of its Docker stack, just get one with x86 even if all your other systems are ARM64.

**Comment by peddaahh** [comment]
As you now can run a 4 Core 24GB RAM arm vm always free on oracle, it would be great if there would be an arm image
[
![Screenshot_5](https://user-images.githubusercontent.com/37550489/127030909-0ce36eae-d07b-4b1d-b436-2460af76bd6e.png)
](url)

**Comment by peddaahh** [comment]
This compute and memory hours are equal to 31.25 days per month
![image](https://user-images.githubusercontent.com/37550489/127031150-ca2b6b2f-9cf4-4978-ab81-e9d84061d00e.png)

**Comment by peddaahh** [comment]
@mkuron :)

**Comment by waja** [comment]
But you need to use Oracle Linux on arm, cause there is no other OS available for arm there yet. :)

**Comment by mkuron** [comment]
That certainly is an interesting offer. Nevertheless I strongly discourage everyone to run production servers on a free service. You won‘t get good (or any) customer support from your provider unless you pay them, and there is always the risk they might shut down the free service on short notice.

Really, if you are going to invest the time to set up your own mail server, do it in a place where you can be reasonably sure that it can stay for the next 5 years. Migrating your server elsewhere will be a time-consuming process, and if your time is worth any money to you, the migration will probably cost you an amount of time similar to what money you saved over the course of a few years.

I still stand by what I said a while ago, and I am still convinced that we will get there:

> I am certain there will be within approximately two years. Only once that is the case, and once one of the Mailcow core developers actually runs Mailcow on an ARM64 server themselves, will it start making sense to support Mailcow there.

**Comment by peddaahh** [comment]
> But you need to use Oracle Linux on arm, cause there is no other OS available for arm there yet. :)

Nope I am using Ubuntu 20.04, runs perfectly fine.

**Comment by magnetic6** [comment]
I can confirm. Ubuntu 20.04 has been available since day 1.

Their UI pushes you to Oracle Linux. I had to open a support ticket to figure out how to use Ubuntu. The trick is you need to select the regular, non-minimal Ubuntu image.

**Comment by peddaahh** [comment]
> That certainly is an interesting offer. Nevertheless I strongly discourage everyone to run production servers on a free service. You won‘t get good (or any) customer support from your provider unless you pay them, and there is always the risk they might shut down the free service on short notice.
> 
> Really, if you are going to invest the time to set up your own mail server, do it in a place where you can be reasonably sure that it can stay for the next 5 years. Migrating your server elsewhere will be a time-consuming process, and if your time is worth any money to you, the migration will probably cost you an amount of time similar to what money you saved over the course of a few years.
> 
> I still stand by what I said a while ago, and I am still convinced that we will get there:
> 
> > I am certain there will be within approximately two years. Only once that is the case, and once one of the Mailcow core developers actually runs Mailcow on an ARM64 server themselves, will it start making sense to support Mailcow there.

Well, reading ur answer tells me this won't happen soon... I mean it would be cool, and tbh I know it's not kinda the best solution running a mail server on such cloud instances. But not everyone can or want to afford monthly cost of a VM with the needed resources your service needs.

**Comment by peddaahh** [comment]
And hosting @ Home is kinda complicated due to dynamic IP...

**Comment by peddaahh** [comment]
Additionally there's also the raspberry pi 4 with 8GB of RAM. It would be interesting too, to run your service on that and more.. as arm is now becomming more and more popular (Windows 10 on ARM, with Qualcomm processors, the Microsoft SQ1 and SQ2 processors...)

**Comment by sohsatoh** [comment]
... Well, why you guys don't build images yourself instead of pulling built images?

**Comment by peddaahh** [comment]
> ... Well, why you guys don't build images yourself instead of pulling built images?

Tell me how? As I assumed this time not all docker images which are used were open source or did I miss something?

**Comment by sohsatoh** [comment]
@Peddaahh 

https://github.com/mailcow/mailcow-dockerized/blob/master/helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml

https://github.com/mailcow/mailcow-dockerized/tree/master/data/Dockerfiles

**Comment by peddaahh** [comment]
> @Peddaahh
> 
> https://github.com/mailcow/mailcow-dockerized/blob/master/helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml
> 
> https://github.com/mailcow/mailcow-dockerized/tree/master/data/Dockerfiles

I tried but this is pain in the ass and need much troubleshooting
Problems I have found:
Mailcow depends on docker-compose v1 --> hard to install on ARM but I managed to do it
Solr bootstrap does not run when building the container on ARM
...

**Comment by sohsatoh** [comment]
@Peddaahh 
Hmm...
I was able to get the image to build and work on my own about six months ago, but I deleted the repository itself so I'm not sure.

Personally, I recommend docker-mailserver for the arm environment such as OCI.
It's a very lightweight image, but if you don't need a web control panel, I think it's sufficient.

**Comment by nikitasius** [comment]
Personally i run **debian 11 arm64** image on **Oracle A1 free** instance 4core/24Gb ram.

Those images works perfectly: https://cloud.debian.org/images/cloud/

All you need is:
* add your ssh key inside, if key named `ed25519.pub` it will be `virt-customize -a debian-11-generic-arm64-20211011-792-root-ssh.qcow2 --ssh-inject root:file:ed25519.pub`
* and tell deb to generate ssh encryption keys on 1st run `virt-customize -a debian-11-generic-arm64-20211011-792-root-ssh.qcow2 --firstboot-command '/usr/bin/ssh-keygen -A'`
After this you install this image on Oracle and choose PV mode except:
![image](https://user-images.githubusercontent.com/3670331/144434285-66f8af1e-7b71-4b4b-82e2-601adb937a22.png)

So image looks like this:
![image](https://user-images.githubusercontent.com/3670331/144434514-9df9679e-37d2-4eee-bbd2-bccb0f87e8dc.png)

And, sure, edit details to allow install on A1:
![image](https://user-images.githubusercontent.com/3670331/144434608-8c5c7766-e1d4-4092-9833-88a2fd73e2c4.png)

And one more step:
* when you install it DISABLE SSH keys generation from oracle and DISABLE oracle plugins (due oracle can mess your deb).



And a small bonus:
when you install in case if you use only 1 VPS, make boot volume 200Gb. Once installed stop the instance, detatch the boot volume from an instance menu, edit it to maximize your IOPS, cause it's free and attach it back _from an instance menu_ and **not from boot volume menu** :)
![image](https://user-images.githubusercontent.com/3670331/144435127-8b1dce2a-776f-45a5-ae45-876b81805258.png)

![image](https://user-images.githubusercontent.com/3670331/144435226-c422e64d-7b25-48e4-bf91-3a1f08c65550.png)

**Comment by luckdam** [comment]
@nikitasius Excellent guide. Thank you.
