### ISSUE TITLE
Link from IPv6 successful connections to virustotal

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#4138]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Virustotal not doing analysis of IPv6 addresses so link pointed to `https://www.virustotal.com/gui/ip-address/2000:dead:beef::/detection` at current (and at far future I think) will lead to `https://www.virustotal.com/gui/item-not-found`

## Reproduction
1. Login to mailcow from IPv6 address via IMAP/POP or SMTP
2. Login to mailcow UI as user that done step 1
3. Follow the IPv6-link

**Comment by dragoangel** [comment]
I think it will be fine to put for IPv6 link to `https://bgp.he.net/ip/2000:dead:beef::` as it will display whois data at least :)

**Comment by MAGICCC** [comment]
I asked VirusTotal via bugtracker today:
```
Hello,

Thank you for reaching out to VirusTotal.

Unfortunately we do not support IPv6 in VirusTotal searches at the moment, we are working on it but we do not have any estimation date.

Regards,
```

**Comment by dragoangel** [comment]
@MAGICCC I will say you truth: nobody from zoomeye, shodan, censys, virustotal, etc  will not start to support ipv6 in near future (and near future this not less then 5 years). The way they all scan all web by brute force in ipv4 - useless for ipv6. That why I said, lets provide link to just whois :)

**Comment by andryyy** [comment]
We should revert to https://bgp.he.net/ip indeed. :)

**Comment by andryyy** [comment]
It is fixed, thanks!

**Comment by MAGICCC** [comment]
> @MAGICCC I will say you truth: nobody from zoomeye, shodan, censys, virustotal, etc  will not start to support ipv6 in near future (and near future this not less then 5 years). The way they all scan all web by brute force in ipv4 - useless for ipv6. That why I said, lets provide link to just whois :)

yes I know :) Just for the sake of documention I asked them.

**Comment by dragoangel** [comment]
@andryyy I was think that you leave virustotal link for ipv4, but for ipv6 will return bgp.he.net :D. Can it be possible?
