### ISSUE TITLE
IP apparently banned even if whitelisted

### ISSUE THREAD

**Issue by NeverVane** [mailcow/mailcow-dockerized#4139]
Hi,
in the past two weeks I twice had a problem connecting to the mailcow server via an email client, ssh and web interface was refusing connection too. 
The ip used for connection is whitelisted and not appearing in the banned ip list.
Sending&Receiving from other ip (my phone i.e.) was fine.
I saved the logs of all containers before restarting all.
After a restart everything works just fine, and logs seems fine too.

any idea on what could have gone wrong and what I could check next time it happens?

I run Ubuntu 20.04

**Comment by waja** [comment]
When ssh is also banned, this has nothing to do with mailcow.

**Comment by NeverVane** [comment]
I thought could be something related to f2b settings. what could I check?

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
