### ISSUE TITLE
configure show_user_unknown_table_name = no

### ISSUE THREAD

**Issue by geektoor** [mailcow/mailcow-dockerized#4143]
## Summary

I'd like my systems to be less disclosing, so i usually set show_user_unknown_table_name = no to my systems.
The default in postfix is yes, as it also helps the user to see which table/transport might reject the user, but this should
be not needed for mailcow at all. So in my point of view its a good default to set it to no for production systems.

## Motivation

It doesn't need to disclose where the user might be get not found in and it also makes errors much more simple to
understand as it will shorten the error message for unknown users like so:
With = yes:
> User unknown in virtual mailbox table

With = no:
> User unknown

But before simply doing so i would like to see if there might be reasons for others to not do it? Did i miss any? and yes,
i'm aware i can set it in the extra.cf, but i would like to have it as a default for all :)

**Comment by andryyy** [comment]
Not sure. It can help debugging problems with local/non local users and transport maps. I'd recommend to leave it as it is per default. 

This maaaay help debugging.

**Comment by geektoor** [comment]
No prob, i just will add it to my extra.cf :)
