### ISSUE TITLE
Admin WebUI slowness with newest update

### ISSUE THREAD

**Issue by bbushong** [mailcow/mailcow-dockerized#4145]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

I update using ./update.sh about every 2 weeks. Since 1 week ago, the interface has become very slow on the admin WebUI with the mailbox listing taking up to 15 minutes to show. This was not happening before. I have doubled the ram to 64GB as a test to see if I hit a threshold on memory or something. There are 2066 mailboxes. I was getting ~13 minutes or so with 32GB of RAM, and now am getting ~11 minutes (See screenshot:)
![WebConsole](https://user-images.githubusercontent.com/4721547/122156517-212c3300-ce37-11eb-85c7-a93cf9dc6fbf.jpg)

## Logs

Nothing shows anything odd - I have checked MySQL and others to try and find this...

## Reproduction

By logging into admin WebUI -> configuration -> Mail Setup. The domains come up pretty quickly, but the mailbox tab (and I suspect others based on Network results screen shot) takes much longer.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Amazon AWS EC2 - R52xLarge (Was xLarge before an hour ago) |
| Server/VM specifications (Memory, CPU Cores) | 64GB, 8 |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) | version 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | N/A |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
/data/conf/dovecot/dovecot.conf:
service_count = 0
process_limit = 10000

/data/conf/mysql/my.cnf:
max-connections         = 66666650
innodb_flush_log_at_trx_commit = 2

data/conf/phpfpm/php-fpm.d/pools.conf:
pm.max_children = 50

data/conf/sogo/sogo.conf:
WOWorkersCount = "1500";
GCSChannelCollectionTimer = 25;
GCSChannelExpireAge = 15;
SxVMemLimit = 384;

docker-compose.yml:
- MEMCACHED_MAX_CONNECTIONS=2000
- command: -c 2048
enable_ipv6: false

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by itkfm** [comment]
same here. Already noticed similar behavior a while ago… 

![image](https://user-images.githubusercontent.com/53079668/123959464-7c6d3200-d9ae-11eb-94aa-f2385c8248c6.png)

Unfortunately, this renders the admin UI hardly usable.

**Comment by itkfm** [comment]
MariaDB appears to cause very high CPU load while those requests are being processed.

**Comment by andryyy** [comment]
It’s fixed. You need to update.

**Comment by itkfm** [comment]
Hi, I've updated an hour ago and the issue persists

**Comment by andryyy** [comment]
I don’t know. Which API endpoint is slow?

Do you have a “success” column in the sasl_logs table?

**Comment by itkfm** [comment]
Hard to tell which one causes the slow down because those incidents seem to block all PHP workers

It’s probably `/api/v1/get/mailbox/reduced` or `/api/v1/get/resource/all`.

**Comment by itkfm** [comment]
No, there's no success column:

```
MariaDB [mailcow]> describe sasl_logs;
+--------------+--------------+------+-----+---------------------+----------------+
| Field        | Type         | Null | Key | Default             | Extra          |
+--------------+--------------+------+-----+---------------------+----------------+
| id           | int(11)      | NO   | PRI | NULL                | auto_increment |
| service      | varchar(32)  | NO   | MUL |                     |                |
| app_password | int(11)      | YES  |     | NULL                |                |
| username     | varchar(255) | NO   | MUL | NULL                |                |
| real_rip     | varchar(64)  | NO   | MUL | NULL                |                |
| datetime     | datetime     | NO   | MUL | current_timestamp() |                |
+--------------+--------------+------+-----+---------------------+----------------+
```

**Comment by andryyy** [comment]
Is opening the URLs (the API endpoints) in the browser slow, too?

**Comment by andryyy** [comment]
I think I can still access the server, right? If you like to, I can have a check. :)

**Comment by bbushong** [comment]
If needed, I can provide access as well - I am still having the issue as well. I just tried /api/v1/get/mailbox/reduced, and it is still going as we speak... so my guess is that it will take 15 minutes. Let me know best way to get you remote access if you are willing. If remoting into itkfm's setup is easier, that is fine as well

**Comment by andryyy** [comment]
It's fixed now. :) 

We only log unique combinations of username, ip and service now.

**Comment by bbushong** [comment]
It's fixed!! Thank you so much @andryyy ! This saves us a LOT of time :)
