### ISSUE TITLE
XMPP certificate renewal

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4149]
Good day, it seems as if the XMPP-Cert cronjob does not run if one makes ex. every week a Mailcow update the cronjob is reinitialized again and according to how his update strategy is (with me Weekly, Mondays) this cronjob is never executed, this can of course other cronjobs also affected which do not run so often.

In my logs to the XMPP I find for example only this entry:
ofelia-mailcow_1 | 2021-06-14T03:03:26.234383468Z 2021-06-14T03:03:26.234Z scheduler.go:34 ▶ NOTICE New job registered “ejabberd_certs” - “/sbin/su-exec ejabberd /home/ejabberd/bin/ejabberdctl –node ejabberd@${MAILCOW_HOSTNAME} request-certificate all” - “@every 168h”

**Comment by andryyy** [comment]
Template. :/ !

**Comment by omexlu** [comment]
Hi,

Am not at home to provide all the data.

But Ubuntu 20.04 everything up to date also mailcow.

Ps.sorry but can not do otherwise at the moment.

But the problem seems to lie in the procedure of olefia, as mentioned above because all other short cronjobs runs successfully.

**Comment by omexlu** [comment]
@andryyy 

As I suspected, the cronjob is then not executed and with every container restart or update the cronjob is reinitialized.

Today the cronjob ran through, however, this also does not work correctly, the certs were not renewed:
```
ofelia-mailcow_1     | 2021-06-21T03:03:26.101795969Z 2021-06-21T03:03:26.101Z  common.go:125 ▶ NOTICE [Job "ejabberd_certs" (9be50e9eb360)] Started - /sbin/su-exec ejabberd /home/ejabberd/bin/ejabberdctl --node ejabberd@${MAILCOW_HOSTNAME} request-certificate all
ofelia-mailcow_1     | 2021-06-21T03:03:27.924598315Z 2021-06-21T03:03:27.924Z  common.go:121 ▶ ERROR [Job "ejabberd_certs" (9be50e9eb360)] StdOut: Failed RPC connection to the node 'ejabberd@${MAILCOW_HOSTNAME}': nodedown
ofelia-mailcow_1     | 2021-06-21T03:03:27.924639850Z Commands to start an ejabberd node:
ofelia-mailcow_1     | 2021-06-21T03:03:27.924646129Z   start      Start an ejabberd node in server mode
ofelia-mailcow_1     | 2021-06-21T03:03:27.924653236Z   debug      Attach an interactive Erlang shell to a running ejabberd node
ofelia-mailcow_1     | 2021-06-21T03:03:27.924660623Z   iexdebug   Attach an interactive Elixir shell to a running ejabberd node
ofelia-mailcow_1     | 2021-06-21T03:03:27.924667645Z   live       Start an ejabberd node in live (interactive) mode
ofelia-mailcow_1     | 2021-06-21T03:03:27.924674679Z   iexlive    Start an ejabberd node in live (interactive) mode, within an Elixir shell
ofelia-mailcow_1     | 2021-06-21T03:03:27.924681982Z   foreground Start an ejabberd node in server mode (attached)
ofelia-mailcow_1     | 2021-06-21T03:03:27.924695651Z Optional parameters when starting an ejabberd node:
ofelia-mailcow_1     | 2021-06-21T03:03:27.924702904Z   --config-dir dir   Config ejabberd:    /home/ejabberd/conf
ofelia-mailcow_1     | 2021-06-21T03:03:27.924710045Z   --config file      Config ejabberd:    /home/ejabberd/conf/ejabberd.yml
ofelia-mailcow_1     | 2021-06-21T03:03:27.924717239Z   --ctl-config file  Config ejabberdctl: /home/ejabberd/conf/ejabberdctl.cfg
ofelia-mailcow_1     | 2021-06-21T03:03:27.924724696Z   --logs dir         Directory for logs: /home/ejabberd/logs
ofelia-mailcow_1     | 2021-06-21T03:03:27.924731845Z   --spool dir        Database spool dir: /home/ejabberd/database/ejabberd@${MAILCOW_HOSTNAME}
ofelia-mailcow_1     | 2021-06-21T03:03:27.924739454Z   --node nodename    ejabberd node name: ejabberd@${MAILCOW_HOSTNAME}
ofelia-mailcow_1     | 2021-06-21T03:03:27.924753107Z 2021-06-21T03:03:27.924Z  common.go:121 ▶ ERROR [Job "ejabberd_certs" (9be50e9eb360)] Finished in "1.822136097s", failed: true, skipped: false, error: error
``` 

Running following command from the container works without problems, so i think there is a bug in ofelia cronjob-syntax:
`/usr/local/bin/docker-compose exec -T -u ejabberd ejabberd-mailcow /home/ejabberd/bin/ejabberdctl --node ejabberd@MAILCOW_HOST request-certificate all`

**Comment by omexlu** [comment]
Hi, Is this bug at least confirmed?

**Comment by MAGICCC** [comment]
I'll close it since XMPP got removed from the stack
