### ISSUE TITLE
Deactivate SOGo

### ISSUE THREAD

**Issue by poldixd** [mailcow/mailcow-dockerized#415]
Is it possible to deactivate SOGo? Is the solution to delete the SOGo block in the `docker-compose.yml`?

**Comment by PhoenixPeca** [comment]
**I really recommend you not to remove it.** Unlike the non-dockerized mailcow, SOGo is deeply integrated to mailcow-dockerized. So theoretically, disabling it would cause you more trouble than leaving it as is.

But, if you insist, I guess your assumptions are correct; I never really tried it myself.

**Comment by poldixd** [comment]
Ok, thanks. Better i don't deactivate/remove SOGo.

**Comment by andryyy** [comment]
You can set `WOWorkersCount = "3";` in `data/conf/sogo/sogo.conf`. SOGo shouldn't use much RAM then.
