### ISSUE TITLE
[Cosmetic] Icons not loading in Oauth2 authorize window

### ISSUE THREAD

**Issue by dawid-woitaschek** [mailcow/mailcow-dockerized#4151]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
I know, it is a small "issue", because it's a cosmetic one... But maybe it is quickly fixable. :)
I connected Mailcow via Oauth2 with my Nextcloud setup and saw, that the icons in the "Authorize" windows aren't loading properly:
![image](https://user-images.githubusercontent.com/34062137/122613297-e8819900-d084-11eb-9175-fa373e05ce13.png)

I would expect the following icons there:
![image](https://user-images.githubusercontent.com/34062137/122613496-3a2a2380-d085-11eb-81eb-1b8e2506ac73.png)

## Logs
I guess this isn't important in this case... I couldn't find appropriate lines in the log as well (or I was just blind :)).
If you think I can gather some specific logs, please tell me, so I will get them asap.

## Reproduction
Connect a service via Oauth2 and login via Mailcow. In the "Authorize application" (German: "Anwendung authorisieren") you should see, that the icons aren't loading properly.
I couldn't see any difference via browser's dev tools... But well, I'm no web dev. :)

I'm using Traefik as reverse proxy, but couldn't see any problems apart of this one.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.2 LTS|
| Is Apparmor, SELinux or similar active? | No.|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM @Netcup (vRoot)|
| Server/VM specifications (Memory, CPU Cores) | 16 GB, 4 cores|
| Docker Version (`docker version`) | Docker version 19.03.6|
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.2|
| Reverse proxy (custom solution) | Traefik v2, ACME enabled; disabled the HTTP/S bindings in Mailcow|

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Thank you. :) I will fix it tomorrow.
