### ISSUE TITLE
manifest for mailcow/watchdog:1.92 not found: manifest unknown

### ISSUE THREAD

**Issue by NoirPi** [mailcow/mailcow-dockerized#4153]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

latest available Watchdog Image is 1.91 so 1.92 wasnt pushed!

Error response from daemon: manifest for mailcow/watchdog:1.92 not found: manifest unknown: manifest unknown

Prevois Issues had the same with postfix but there was no quick solution mentioned!

## Logs
Error response from daemon: manifest for mailcow/watchdog:1.92 not found: manifest unknown: manifest unknown

## Reproduction
Just run the ./update.sh

## System information
| Question | Answer |
| --- | --- |
| My operating system | Debian Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 8GB RAM , 4 Cores |
| Docker Version (`docker version`) | 20.10.7 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | nginx |

**Comment by geektoor** [comment]
Just as an information for now: the image is not yet on docker hub, so currently updates don't work. If you're stuck, you have at least the following option (this one was discussed in the telegram channel already):

```
git stash push --include-untracked
git stash drop
git checkout 9773d3549e954c1bb89a280294cdfb57f593e254
docker-compose pull
docker-compose up -d
```
(Thanks to Lukas D for it)
This will revert the last changes back and you should be back in business.

As long as the image is not there, please do not run updates right now.

**Comment by patschi** [comment]
@andryyy has been pinged and should be aware of it. So once he wakes up from his nap, he's going to fix it for sure. In the meanwhile go for the workaround provided by @geektoor. (Thanks for that!)

**Comment by MAGICCC** [comment]
Available on docker hub now: https://hub.docker.com/layers/mailcow/watchdog/1.92/images/sha256-ab8d43cb2301fbfef2169d2de4bbe18cefdc9c30c2a7b6331af1d1a426b6ddb0?context=explore
