### ISSUE TITLE
Issue adding hostname to forwarding hosts

### ISSUE THREAD

**Issue by maverick85** [mailcow/mailcow-dockerized#4158]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Unable to add forwarding host using the FQDN.
When I add the FQDN to "Add forwarding host" I get an error message saying `Invalid host specified: host.domain.tld`

## Logs
I ran `docker-compose logs -t | egrep FQDN` and got results from the `postfix-mailcow_1` container.

```
postfix-mailcow_1    | 2021-06-23T12:40:04.163286624Z Jun 23 13:40:04 53f0cb6cc4c0 postfix/smtpd[111110]: warning: hostname host.domain.tld does not resolve to address 1.2.3.4: Temporary failure in name resolution
postfix-mailcow_1    | 2021-06-23T12:40:04.334347284Z Jun 23 13:40:04 53f0cb6cc4c0 postfix/smtpd[111110]: NOQUEUE: reject: RCPT from unknown[1.2.3.4]: 450 4.1.8 <cpanel@host.domain.tld>: Sender address rejected: Domain not found; from=<cpanel@host.domain.tld> to=<webmaster@domain.tld> proto=ESMTP helo=<host.domain.tld>
```

I restarted the postfix container and the unbound container.
I entered the unbound container and pinged host.domain.tld, it pinged the correct address.
I entered the postfix container and pinged as above, but it returned a `bash: ping: command not found`
I ran `host 1.2.3.4` inside the postfix container, and it returned the correct FQDN.

Ran the command `docker-compose down; systemctl restart docker; docker-compose up -d` as per instructions of [Issue #2479](https://github.com/mailcow/mailcow-dockerized/issues/2479) - didn't fix it

## Reproduction
Mailcow UI > Configuration > Configuration & Details > (dropdown) Configuration > Forwarding Hosts

Under "Add forwarding host" I enter the FQDN of the host, under `Spam filter` I select `Inactive` and press `+ Add`

An error message is returned, in red, on the lower right corner saying `Invalid host specified: host.domain.tld`

## System information

| Question | Answer |
| --- | --- |
| My operating system | Oracle Linux 8.4 |
| Is Apparmor, SELinux or similar active? | Permissive |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Xen hypervisor/KVM |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 2 CPU Cores |
| Docker Version (`docker version`) | 20.10.6 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | No |

```
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.193.69
151.101.65.69
151.101.129.69
151.101.1.69
```

**Comment by maverick85** [comment]
hello? some more recent issues get response and others are simply ignored?? What gives?

**Comment by ghost** [comment]
> hello? some more recent issues get response and others are simply ignored?? What gives?

From the Postfix logs you share it looks like your issue isn't related to Mailcow, but a bad domain configuration from the host you're trying to add. This issue must be closed and if needed you should ask for help on the community forum: https://community.mailcow.email

**Comment by maverick85** [comment]
> > hello? some more recent issues get response and others are simply ignored?? What gives?
> 
> From the Postfix logs you share it looks like your issue isn't related to Mailcow, but a bad domain configuration from the host you're trying to add. This issue must be closed and if needed you should ask for help on the community forum: https://community.mailcow.email

I am sorry but based on what do you get that there is a bad domain configuration from the host I'm trying to add? You are both wrong as it can be easily proven, as the domain and DNS configuration are working perfectly fine, mailcow is throwing an error due to some issue with its system. The mailcow host resolves the domain perfectly, the upstream DNS resolver also resolves the domain perfectly, being the upstream resolver an unbound resolver, I'm sure you know how it works. There are ZERO issues with the domain configuration, so exactly where do you get that there is a bad domain configuration?? If the 18 days it took to get an answer are hard to swallow, your reply is unbelievably brutal.

**Comment by ghost** [comment]
@maverick85 wow dude, my message was short but in no way brutal. You may want to check those fragility issues.

I'll let you be with your business developper manager entrepreneur skills. Unsubscribing to this non-issue.

**Comment by maverick85** [comment]
Of course, I'm still waiting for your evidence of the `bad domain configuration` you mentioned. While I can clearly prove there is no issue with the domain configuration, you came here babbling sh*t cause you're oblivious, yet suffering some Dunning-Kruger syndrome... unfortunately a disease that today rivals with the numbers of COVID.

**Comment by andryyy** [comment]
Sigh, you again, @maverick85?
