### ISSUE TITLE
[Feature] Seperate SOgo and DAV

### ISSUE THREAD

**Issue by seniorm0ment** [mailcow/mailcow-dockerized#4159]
Requesting SOgo as DAV be seperate components so the user can choose to disable SOgo but not have to sacrafice DAV support through Mailcow.

**Comment by mthld** [comment]
@seniorm0ment what do you suggest to replace it? DAV support isn't coming from nowhere...

**Comment by seniorm0ment** [comment]
I'm not currently familiar with what options currently exist for FLOSS, Self-hosted DAV software, however my suggestion was to simply use an alternative DAV software to handle DAV.
I can look more into software options later if needed, or if someone has suggestions feel free to comment. I am a bit busy currently.

**Comment by andryyy** [comment]
Well, we use SOGo for that.

**Comment by mkuron** [comment]
If you use SOGo for DAV alone (not webmail and especially not EAS), its memory consumption is actually rather reasonable. I guess memory is the main reason why some people don't want SOGo. In terms of the quality of the DAV implementation, it is actually really good, better than many others I have tried over the years. If you wanted something standalone, you would probably end up with Radicale or something built on top of SabreDAV, the latter of which I have had rather mixed experiences with.

**Comment by seniorm0ment** [comment]
>If you use SOGo for DAV alone (not webmail and especially not EAS), its memory consumption is actually rather reasonable.

Are you actually able to disable SOgo except for it's DAV functionality?
It is a waste of resources for users who don't use it, also having stuff running that you don't need is just extra potential security vulnerabilities. 
I don't disagree that SOgo's DAV implementation is good, however the above.

**Comment by waja** [comment]
> It is a waste of resources for users who don't use it, also having stuff running that you don't need is just extra potential security vulnerabilities.

Then turn it off, if you don‘t like to use it. If you like to use another DAV implementation, just add another container and authenticate with OAuth.

**Comment by seniorm0ment** [comment]
That doesn't answer my question.
