### ISSUE TITLE
ADDITIONAL_SAN not working

### ISSUE THREAD

**Issue by hixlabs** [mailcow/mailcow-dockerized#416]
In my installation conf has ADDITIONAL_SAN="cloud.hixlabs.com" . SSL certificate is not getting generated for the ADDITIONAL_SAN. 

A record is properly set and resolving but acme-mailcow logs show the below error. 

_acme-mailcow_1       | Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: autoconfig.hixlabs.com autodiscover.hixlabs.com mail.hixlabs.com
acme-mailcow_1       | Found A record for autoconfig.hixlabs.com: 137.74.63.168
acme-mailcow_1       | Confirmed A record autoconfig.hixlabs.com
acme-mailcow_1       | Found A record for autodiscover.hixlabs.com: 137.74.63.168
acme-mailcow_1       | Confirmed A record autodiscover.hixlabs.com
**acme-mailcow_1       | No A record for "cloud.hixlabs.com" found**
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-mailcow_1       | acme-client: adding SAN: autoconfig.hixlabs.com
acme-mailcow_1       | acme-client: adding SAN: autodiscover.hixlabs.com
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 85 days left
acme-mailcow_1       | ACME certificate validation done. Sleeping for another day._

Can you please point me to what I'm missing.

**Comment by andryyy** [comment]
I fixed it. You need to use ADDITIONAL_SAN=cloud.hixlabs.com or for multiple names  ADDITIONAL_SAN=cloud.hixlabs.com,bla2.example.org

Without quotes. Will push the update in a bit.

**Comment by hixlabs** [comment]
Hi Andryyy,

Thanks you very much. 
And thanks for mailcow.
