### ISSUE TITLE
urlhaus.abuse.ch/downloads

### ISSUE THREAD

**Issue by ivanfaltum** [mailcow/mailcow-dockerized#4160]
=============================
URLhaus Database File Updates
=============================
Checking for urlhaus updates...
Checking for updated urlhaus database file: urlhaus.ndb
-----------------------------------------------------------------------------------------------------
WARNING: Failed connection to https://urlhaus.abuse.ch/downloads - SKIPPED urlhaus urlhaus.ndb update
-----------------------------------------------------------------------------------------------------
No updated urlhaus urlhaus.ndb database file
--------------------------------
No urlhaus database file updates

**Comment by MAGICCC** [comment]
Why did you delete the template? Please follow the template when filling in issues.

**Comment by ivanfaltum** [comment]
SORRY!!! YOU CAN HELP ME

**Comment by wblondel** [comment]
On your Mailcow server, try to download the file manually, ie. :
```
wget https://urlhaus.abuse.ch/downloads/urlhaus.ndb
```

If it works, the error you got was just temporary (short network outage from your end or their end) and it will correctly update at the next update task.

**Comment by ivanfaltum** [comment]
I used pfsense  with this script https://github.com/extremeshok/clamav-unofficial-sigs maybe you can help me THANKS!!!

**Comment by wblondel** [comment]
No link with Mailcow then.

See this issue: https://github.com/extremeshok/clamav-unofficial-sigs/issues/385

**Comment by ivanfaltum** [comment]
THANKS!!!
