### ISSUE TITLE
community.mailcow (confirmation email to @mailbox.org) not working?

### ISSUE THREAD

**Issue by konfiv** [mailcow/mailcow-dockerized#4168]
Hello,

14 hours ago I sign up for https://community.mailcow.email/ but get no confirmation email.
I used 5-8 times the resend option and changed my ***@temp.mailbox.org address. (may mailcow don't like subdomains?)

Also made second account today, same issue, just used a usual ***@mailbox.org mail address.
`We've sent a confirmation email to ***@mailbox.org. If it doesn't arrive soon, check your spam folder.`
Resend confirmation email option is not helping too.
Thanks

**Comment by andryyy** [comment]
@patschi Can you check this? There is no incoming connection from the forums IP on our mail server when I test the settings. It just runs into an error. :/ Perhaps there are server-side logs.

Could be related to Flarum 1.0

**Comment by andryyy** [comment]
I activated your users @konfiv

**Comment by konfiv** [comment]
Ok thanks. The user from yesterday can also start discussion now.
 The user from today (until now) can only reply. Just for the feedback. For me ok.

**Comment by patschi** [comment]
Will check today evening. Strange part is that discussion-related emails seems to be sent? However, checking today. Could be indeed related to Flarum 1.0 update on last weekend or on the redis queue worker in the background. Thanks for letting me know!

**Comment by patschi** [comment]
I think I might have found the issue. Ironically it seems to be related to Sentry's backend performance monitoring. Please report back if there're still issues. Can please somewhen check?
