### ISSUE TITLE
container not working after restart

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#417]
Hey guys, I've been testing dockrized mailcow with no issues lately, but after this sunday or so, I can no longer restart with docker-compose down && docker-compose up -d or rebooting because it won't come back, mailcow website is gone.

I tested with a fresh install using ubuntu 16.04 LTS then if I restart services or reboot the server its gone. You can't access  mailcow panel, even if I do "docker-compose restart nginx-mailcow" 

I tried a few times.

Can anyone tell me what to do or how to fix it without starting from scratch?  thanks.

**Comment by burn79** [comment]
I think, I had the same problem on this weekend.
Look, if the nginx container is running.
`docker ps | grep ngnix`
On my system it was restarting and restarting again.

Change in your mailcow-dockerized directory and type this to view the log form the nginx container
`docker-compose logs --tail="100" nginx-mailcow`

In my case, the files cert.pem and key.pem were the problem.

**Comment by andryyy** [comment]
Can you please check `docker-compose ps` (run from within the mailcow-dockerized folder) and post the output?

**Comment by alyzrazor** [comment]
Sure this is what I get:

mailcowdockerize   /srv/docker-       Exit 1
d_acme-mailcow_1   entrypoint.sh
mailcowdockerize   /bootstrap.sh      Up                 3310/tcp
d_clamd-
mailcow_1
mailcowdockerize   /docker-           Up                 10001/tcp, 0.0.0
d_dovecot-         entrypoint.sh                         .0:110->110/tcp,
mailcow_1          /bin ...                              0.0.0.0:143->143
                                                         /tcp, 24/tcp, 0.
                                                         0.0.0:4190->4190
                                                         /tcp, 0.0.0.0:99
                                                         3->993/tcp, 0.0.
                                                         0.0:995->995/tcp
mailcowdockerize   python2 -u         Up
d_fail2ban-        /logwatch.py
mailcow_1
mailcowdockerize   /docker-ipv6nat    Up
d_ipv6nat_1        --retry
mailcowdockerize   docker-            Up                 11211/tcp
d_memcached-       entrypoint.sh
mailcow_1          memcached
mailcowdockerize   docker-            Up                 3306/tcp
d_mysql-           entrypoint.sh
mailcow_1          mysql ...
mailcowdockerize   /bin/sh -c         Restarting
d_nginx-           envsubst < /etc
mailcow_1          ...
mailcowdockerize   /docker-           Up                 9000/tcp
d_php-fpm-         entrypoint.sh
mailcow_1          php- ...
mailcowdockerize   /bin/sh -c exec    Up                 0.0.0.0:25->25/t
d_postfix-         /usr/bin/s ...                        cp, 0.0.0.0:465-
mailcow_1                                                >465/tcp, 0.0.0.
                                                         0:587->587/tcp,
                                                         588/tcp
mailcowdockerize   docker-            Up                 6379/tcp
d_redis-           entrypoint.sh
mailcow_1          redis ...
mailcowdockerize   /docker-           Up
d_rspamd-          entrypoint.sh
mailcow_1          /bin ...
mailcowdockerize   /bin/sh -c exec    Up
d_sogo-mailcow_1   /usr/bin/s ...
mailcowdockerize   /docker-           Up                 53/tcp, 53/udp
d_unbound-         entrypoint.sh
mailcow_1          /usr ...

**Comment by andryyy** [comment]
Can you check docker-compose logs --tail=100 nginx-mailcow? Or just use ./update.sh :)

**Comment by alyzrazor** [comment]
^_^ here is what you asking:

Attaching to mailcowdockerized_nginx-mailcow_1
nginx-mailcow_1      | 2017/06/28 18:15:13 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:15 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:15 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:16 [emerg] 11#11: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:17 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:19 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:23 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:30 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:15:43 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:16:09 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:17:01 [emerg] 11#11: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:18:01 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:19:01 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:20:02 [emerg] 11#11: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:21:02 [emerg] 9#9: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:22:02 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:23:03 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:24:03 [emerg] 9#9: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:25:03 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:26:04 [emerg] 9#9: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:27:04 [emerg] 10#10: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:28:04 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | 2017/06/28 18:29:05 [emerg] 8#8: SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx-mailcow_1      | nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by andryyy** [comment]
Do you use your own certificates and forgot to copy the key?

You can fix it by deleting everything in data/assets/ssl and run `cp data/assets/ssl-example/* data/assets/ssl`.

**Comment by jpbaril** [comment]
I also had this problem. I had to delete "data/assets/ssl" on host and restart containers.

**Comment by alyzrazor** [comment]
No, I didn't do anything, just started a new server, installed mailcow for reference then restarted that's all I did.

hopefully this works for you so you can apply a fix.

**Comment by alyzrazor** [comment]
Another thing to consider:

After deleting files in: data/assets/ssl it worked 
then run cp data/assets/ssl-example/* data/assets/ssl  

So I restarted container to make sure  and... The same problem returned.

Perhaps I repeated the same process but in this test I didn't run "cp data/assets/ssl-example/* data/assets/ssl"

after restarting container again the same happend again website down.
ty

**Comment by burn79** [comment]
Do you use reverse proxy?
If you did, but only for https, not for http, then you got this error.
The acme client ist looking for a temporary file to verify the domain and create a new ssl certificate at the url http://domain.tld/.well-known/acme-challenge/
When you not reverse proxy the http connection to the nginx container, the verification failes.

**Comment by andryyy** [comment]
I am looking to fix this bug. Can you give me access via SSH or TeamViewer? I saw it sometimes today but could not reproduce. Please mail me to info@servercow.de

**Comment by andryyy** [comment]
And: What's in the acme logs? => `docker-compose logs --tail=200 acme-mailcow` - that info would help me, too! :)

**Comment by andryyy** [comment]
And please run ./update.sh now again.

**Comment by alyzrazor** [comment]
Thanks for answering, sry my job is a bitch  I was using a VPS server and Deleted that server until an official fix, hopefully I will try it again today and the whole weekend :) this is very good solution nicely done, I really appreciate your work.
