### ISSUE TITLE
Mail server unresponding + emails received multiple times

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#4172]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
Yesterday the mailcow server instance first was quite sluggish in afternoon, then in the evening became unresponsive, and connections timed out. SSH connections also timed out.
I had to connect via system console and reboot it. After reboot the mail server was normally responsive again.
A disk space issue was suspected, but there is still plenty of disk space.
I updated mailcow to fix potential bugs that could cause these kind of issues.
Now the server looks fine - however, in the period in the evening yesterday some mailcow postboxes received emails multiple times (like four times instead just one time).
How is this caused? Has dovecot delivered the inbound mail too often because of some process hanging or some of its states nor correctly saving?

Could it be that `dovecot` hanged, hence the connection time outs and it also delivered mails multiple times (unexpected race-condition)?

## Logs
After updating a mailcow setup, the docker logs are cleared. I can try to extract the logs from the last snapshot. But of course it would be easier and simpler to just get all logs from the current system state.

## Reproduction
The mailcow server just ran happily for some months and everything works great until connections to it became sluggish.
In the late evening most of the connections timed out, even SSH.

## System information
| Question | Answer |
| --- | --- |
| My operating system | `Ubuntu 18.04.5 LTS` |
| Is Apparmor, SELinux or similar active? | `apparmor` module enabled, used by docker apparently |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | `kvm` used by provider for the clodud instances |
| Server/VM specifications (Memory, CPU Cores) | `8 GB memory`; `2 CPU cores` |
| Docker Version (`docker version`) | `20.10.7` |
| Docker-Compose Version (`docker-compose version`) | `1.29.2, build 5becea4c` |
| Reverse proxy (custom solution) | `No` |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
````
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 00eb8a93..5d200356 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,8 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = mail.<redacted>
+# Older encryption used by legacy applications
+submission_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
+smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
````
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
````
151.101.193.69
151.101.129.69
151.101.1.69
151.101.65.69
````

**Comment by ghost** [comment]
How much RAM did you allocated to this VM? It's specifically asked on the issue template.

**Comment by strarsis** [comment]
@mthld: You are correct. I added the information (`8 GB` of memory).
