### ISSUE TITLE
acme-mailcow ERROR 1045 (28000)

### ISSUE THREAD

**Issue by dixquatre** [mailcow/mailcow-dockerized#418]
I've just updated my mailcowdockerized with the new images and I can get my LE certificate for my domain.
When I check the log for acme-mailcow I've got this error message:

`ERROR 1005 (28000): Access denied for user 'mailcow'@'172.22.1.7' (using password: YES)`

Any suggestion?

Thanks

Matt

**Comment by andryyy** [comment]
This is more an issue of wrong credentials for the database. Did you run generate_config.sh after updating? You should _not_ do this.

All containers with SQL access should actually fail.

**Comment by dixquatre** [comment]
yes I did it and realize too late my mistake, try to flush the database volume but still get the same error.

I don't care if I have to recreate my domain/user/aliases, I just don't want to lose my email folder.

**Comment by andryyy** [comment]
docker-compose down -v, then check the containers are gone. Afterwards docker-compose up -d

**Comment by mkuron** [comment]
But won't that delete all volumes, including @dixquatre's email folders?

**Comment by andryyy** [comment]
Yes, I read it like he already flushed the volumes. Or only the database, @dixquatre ?

**Comment by dixquatre** [comment]
only the database volume

Can I copy the mail volume somewhere else, do the big flush and recopy the old mail volume to the new one?

**Comment by dixquatre** [comment]
I've recreated from scratch, saving my vmail volume somewhere else and copy everything back to the new vmail volume. Just had to recreate my domain/mailbox/aliases.
