### ISSUE TITLE
Is it possible to merge incoming and reply emails in inbox?

### ISSUE THREAD

**Issue by anthienvu** [mailcow/mailcow-dockerized#4184]
## Summary

Currently, incoming and reply emails in the same conversation are separated in the Inbox and Sent folder (see image 1). And the sign that an email has been replied is just a small arrow in the right corner.

![1](https://user-images.githubusercontent.com/54502713/125151195-87bf1b00-e16f-11eb-8517-03c574f86396.png)

Thus, I can't see the latest replies in the Inbox folder. 

Is there a way to merged them into a conversation or something like that (see image 2 and 3). Thanks.

![2](https://user-images.githubusercontent.com/54502713/125151201-8988de80-e16f-11eb-9962-c984c676beba.png)
![3](https://user-images.githubusercontent.com/54502713/125151203-8a217500-e16f-11eb-9dbc-a2cbfe582524.png)

**Comment by mkuron** [comment]
That is a SOGo question, not a Mailcow issue. I couldn’t find anything on thread view in the SOGo documentation, but there are bug reports on it (https://www.sogo.nu/bugs/view.php?id=4796, https://www.sogo.nu/bugs/view.php?id=4735) that confirm that the feature you‘re looking for does exist.
