### ISSUE TITLE
DMARC best practice

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#419]
Hi everyone!
I'm getting a lot of DMARC report mails and I'm fed up with handling them manually.
Is there some kind of docker service I could set up, that would handle them automatically and only notify me when DMARC reports are troublesome?

**Comment by K2rool** [comment]
I don't think there is a docker service for that when you say you get a lot of report what reporting you got setup ruf  or rua or both.

Rua is good if you what to see what ip are sending your emails and dkim/spf status of each email, but it will give you report even on DMARC passed email.

Ruf is the most helpful report as it a forensic report of just email that fail DMARC.

How i do DMARC  on my domain is set rua to free DMARC Weekly Digests by Postmark and set ruf to my email address that way i just get the aggregate data ever week in a readable format and i get the forensic on failed email right away to check.

**Comment by Braintelligence** [comment]
My DKIM key is set like this:
"v=DMARC1; p=none; sp=none; rua=mailto:spam-reports@mydomain.de"

So what I am getting are weekly reports... But I get those from several providers.
Also I've set up several mail servers, so I get one report for each of them.

Do I have to read through every XML each time? =/

EDIT: Wait, so I'm not getting the weekly version but the "each mail" version?

**Comment by K2rool** [comment]
Sorry not had my coffee today, rua is got going to report one per email, you might get report for a number of email per report how offen you get it is set up by ri in DMARC dns record which default to 1 day.

**Comment by Braintelligence** [comment]
What should I do to only get reports of faulty emails?

**Comment by K2rool** [comment]
If you change it to "v=DMARC1; p=none; sp=none; ruf=mailto:spam-reports@mydomain.de" then you will only get a report of email that failed SPF&DKIM

**Comment by Braintelligence** [comment]
Awesome, I'll try this!
Thanks for helping out! 😸

**Comment by luxflux** [comment]
@Braintelligence Postmarkapp provides a nice reporting every week. You may use it without having a subscription or something: https://dmarc.postmarkapp.com/.
