### ISSUE TITLE
vnd.dovecot.execute

### ISSUE THREAD

**Issue by RudySixOw** [mailcow/mailcow-dockerized#4191]
Hello, sorry for my english and if this question has already been asked.
I am looking to run a script (bash) with a condition.
But as soon as I put: require "vnd.dovecot.filter"or "vnd.dovecot.execute" or "vnd.dovecot.pipe", I have an error: quoted string "vnd.dovecot.filter" where require string expected.
Example:
require "variables";
require "subaddress";
require "envelope";
require "vnd.dovecot.filter";

if allof (address: contains "to" "mail@domain.com") {

 filter "script.sh";

}

I think there is no module in /usr/lib/dovecot/sieve/ or /usr/lib/dovecot/modules/sieve/ like sieve-execute

**Comment by andryyy** [comment]
Hi, please check the issue template. :)

**Comment by RudySixOw** [comment]
Hello, thank you for your answer but I did not understand. what issue template? I already asked this question a while ago thinking I solved the problem, I did not repeat. But I am faced with this problem again.
