### ISSUE TITLE
SOGO - Filter - Aktionen - funktionieren nicht

### ISSUE THREAD

**Issue by PWNYYY** [mailcow/mailcow-dockerized#4193]
Hey,
ich möchte bei einer noreply Mail Adresse das Empfangen von Mails verweigern, was auch funktioniert, aber leider nicht der Punkt mit den Aktionen. Ich habe alle einmal durchprobiert, jedoch funktioniert keiner der Aktionen. Ich habe nichts großartiges verändert/angepasst. Mir geht es Primär nur um den Punkt mit dem "Sende eine Ablehnungsnachricht". Jemand eine Idee woran dies liegen könnte? 

![image](https://user-images.githubusercontent.com/44307473/126414915-605ebe43-be6f-4dba-8966-a6ffdfa71fc7.png)

**Comment by mritzmann** [comment]
Unklar ob Dir das weiterhilft, löse das bei mir jeweils mit einem Sieve Filter.  
Deine im Screenshot gezeigten Einstellungen habe ich nicht getestet.

`/mailbox#tab-filters`

```sieve
require "vacation-seconds";
if true
{
  # Only send once every 300 seconds:
  vacation :seconds 300 text:
This mailbox is not monitored. E-mails will not be answered.
.
;
discard;
}
```

* Beantwortet jedes E-Mail mit: `This mailbox is not monitored. E-mails will not be answered.`
* Maximal alle 5 Minuten, damit kein E-Mail Pingpong entsteht.
* E-Mails werden mit `discard;` gelöscht.
