### ISSUE TITLE
Question about smtp encryption

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#42]
I found in my logs many entries about rejected connections.

`Feb  7 07:04:38 mail postfix/smtpd[4113]: NOQUEUE: reject: RCPT from r67.web.sophos.com[207.211.34.67]: 550 5.7.1 Session encryption is required; from=<no-reply@sophos.com> to=<bla@example.com> proto=ESMTP helo=<r67.web.sophos.com>`

I'm absolutely for encryption! But is it meaningful to prescribe the smtp encryption mandatory, if the mailserver is used productive?

Could I solve this problem by simply changing the following value in _smtp_tls_security_level = may_?

Thanks!

**Comment by andryyy** [comment]
Hi,  you just used the toggle "enforce incoming encryption" in the mailbox settings.

**Comment by rebek86** [comment]
Thanks!

Sorry, I'm an blockhead :confused:

**Comment by sonicsharp** [comment]
Hi, Sorry to reopen the issue, I need to know where "enforce incoming encryption" in mailbox settings.. I cannot find it in my mailcow. Please help.

**Comment by mkuron** [comment]
That's in the user's settings. It cannot be set server-wide. Also, be careful turning it on as it will quite likely cause some messages to be rejected.

**Comment by metalcated** [comment]
I updated to the most current image and I am not seeing this setting under "User Settings" Maybe I am missing something?
