### ISSUE TITLE
ACME & ECS

### ISSUE THREAD

**Issue by Xeroxxx** [mailcow/mailcow-dockerized#420]
Setup:
- VM running in Aliyun Cloud ECS

Problem:
IP Address on eth0 is: 172.x.x.x/20
Public Address (not seen by vm): 47.x.x.x

So this results in not matching with the ip address found by the container, as its an internal address. Any chances to skip the check in the third row or modify it to get the public address from http://api.ipify.org ?

acme-mailcow_1       | ERROR 1146 (42S02) at line 1: Table 'mailcow.domain' doesn't exist
acme-mailcow_1       | Found A record for mail.xxx.de: 47.x.x.x
acme-mailcow_1       | Cannot match your IP against hostname mail.xxx.de
acme-mailcow_1       | Cannot validate hostnames, skipping Let's Encrypt...

Can anyone confirm this issue?

**Comment by andryyy** [comment]
Is your source IP != your servers IP? Can you check this, please => 

```
docker-compose exec acme-mailcow curl -4s mailcow.email/ip.php
```

**Comment by Xeroxxx** [comment]
SourceIP = ServerIP

ERROR: No container found for acme-mailcow_1

**Comment by Xeroxxx** [comment]
However "curl mailcow.email/ip.php" results in my public ip that points to the domain (A record) above.

**Comment by Xeroxxx** [comment]
No issue

**Comment by unixfox** [comment]
I had the same issue and restarting the contenair resolved the issue.
