### ISSUE TITLE
Timing problem between acme-mailcow and ipv6nat-mailcow

### ISSUE THREAD

**Issue by purejava** [mailcow/mailcow-dockerized#4208]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
On installing mailcow on Arch linux on a Hetzer cloud server generating the Let's encrypt cert fails on startup of the containers with `Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000`.

This is due `ipv6nat-mailcow` not being ready.

## Details and Reproduction
First of all let me thank you for providing mailcow!

I set up mailcow on Arch linux following the documentation. Having the A and AAAA DNS records set up for `mail.plawetzki.com` as well as a MX record, starting the containers with `docker-compose up -d` results in generating the Let's encrypt cert failing with:
```
31.07.2021, 19:27:37  mail.plawetzki.com - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
31.07.2021, 19:27:37  mail.plawetzki.com - Cannot validate any hostnames, skipping Let's Encrypt for 1 hour.
31.07.2021, 19:27:37  mail.plawetzki.com - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname mail.plawetzki.com (DNS returned 2a01:04f8:1c17:51ec:0000:0000:0000:0002)
31.07.2021, 19:27:37  mail.plawetzki.com - Found AAAA record for mail.plawetzki.com: 2a01:4f8:1c17:51ec::2 - skipping A record check
31.07.2021, 19:27:36  mail.plawetzki.com - OK: 138.201.244.42, 0000:0000:0000:0000:0000:0000:0000:0000
31.07.2021, 19:26:57  mail.plawetzki.com - Detecting IP addresses...
```

Working my way through #1737 and for testing purposes I installed a different OS ISO image on the Hetzner server: Ubuntu 20.10., which does generate the cert:
```
31.07.2021, 20:12:08  mail.plawetzki.com - Certificate /var/lib/acme/mail.plawetzki.com/cert.pem missing or changed domains 'mail.plawetzki.com' - start obtaining
31.07.2021, 20:12:08  mail.plawetzki.com - Confirmed AAAA record with IP 2a01:04f8:1c17:51ec:0000:0000:0000:0002
31.07.2021, 20:12:08  mail.plawetzki.com - Found AAAA record for mail.plawetzki.com: 2a01:4f8:1c17:51ec::2 - skipping A record check
31.07.2021, 20:12:08  mail.plawetzki.com - OK: 138.201.244.42, 2a01:4f8:1c17:51ec::2
31.07.2021, 20:12:08  mail.plawetzki.com - Detecting IP addresses...
```
Side note: this did not require the configuration changes in `/etc/network/interfaces.d/50-cloud-init.cfg` described [here](https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/).

First I though there is something wrong with the IPv6 setup of the Arch image, installed this OS again and did some testing. For this, I looked into the acme Dokerfiles `acme.sh` and `functions.sh` and found the IPv6 testing code.

https://github.com/mailcow/mailcow-dockerized/blob/8ccf529936c438a1ccc812e86ae809f68676c6a1/data/Dockerfiles/acme/acme.sh#L219-L220
https://github.com/mailcow/mailcow-dockerized/blob/8ccf529936c438a1ccc812e86ae809f68676c6a1/data/Dockerfiles/acme/functions.sh#L61

Running `curl --connect-timeout 3 -m 10 -L6s "ip6.mailcow.email" | grep "^\([0-9a-fA-F]\{0,4\}:\)\{1,7\}[0-9a-fA-F]\{0,4\}$"` on the CLI while the containers were running returned the required IPv6 address correctly, whereas starting all the containers together `ipv6nat-mailcow` logs:
```
ipv6nat-mailcow_1    | 2021/08/01 08:21:01 running [/sbin/ip6tables -t filter -S --wait]: exit status 3: modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
ipv6nat-mailcow_1    | ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
ipv6nat-mailcow_1    | Perhaps ip6tables or your kernel needs to be upgraded.
````
And running `/sbin/ip6tables -t filter -S --wait` while the containers are running does work.

This looks like a timing problem between the two containers. 

On starting all the containers together (and thus Let's encrypt cert generation failing) restarting `acme-mailcow` does generate the cert.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Arch linux rolling release, Ubuntu 20.10., both on the same Hetzner Cloud server with unchanged DNS |
| Is Apparmor, SELinux or similar active? |No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 16 GB, 4 VCPU |
| Docker Version (`docker version`) | 1:20.10.7-1 (Arch linux) |
| Docker-Compose Version (`docker-compose version`) | 1.29.2-1 (Arch linux) |
| Reverse proxy (custom solution) | No |

**Comment by andryyy** [comment]
Hi and thanks, are you using IPv6 SNAT?

**Comment by purejava** [comment]
> Hi and thanks, are you using IPv6 SNAT?

No.

**Comment by andryyy** [comment]
Hm. I will check and fix it. :)

**Comment by andryyy** [comment]
Hm, is there a test installation you can give me access to? I tried to replicate it but can't.

**Comment by purejava** [comment]
> Hm, is there a test installation you can give me access to? I tried to replicate it but can't.

Sure. I did a fresh install of the mentioned Arch linux Hetzner cloud server and installed mailcow on it:
```
[root@mail mailcow-dockerized]# history
    1  pacman -Syy docker docker-compose which git
    2  cd /opt
    3  git clone https://github.com/mailcow/mailcow-dockerized
    4  cd mailcow-dockerized/
    5  ./generate_config.sh
    6  vim /etc/hostname
    7  reboot
    8  systemctl enable docker
    9  systemctl status docker
   10  systemctl start docker
   11  cd /opt/mailcow-dockerized/
   12  docker-compose up -d
   13  history
[root@mail mailcow-dockerized]# 
```

And I sent you an email with the credentials for the server to: André Peters <andre.peters@debinux.de>

**Comment by purejava** [comment]
Great news!
mailcow offered me an update today that included the IPv6 changes. After the update, the issue is fixed. Nice work!
Now, restarting the containers with `docker-compose down && docker-compose up -d` does work, as well as restarting the whole server. IPv6 detection is working in both cases.

Log:
```docker
acme-mailcow_1       | Fri Aug  6 09:11:40 CEST 2021 - Waiting for resolver...
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Resolver OK
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Waiting for domain table...
acme-mailcow_1       | OK
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Initializing, please wait...
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 139775623035720:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | unable to load certificate
acme-mailcow_1       | 140200926485320:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Using existing domain rsa key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Detecting IP addresses...
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - OK: 23.88.33.100, 2a01:4f8:c010:8a35::2
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Found AAAA record for autodiscover.plawetzki.net: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:41 CEST 2021 - Found AAAA record for autoconfig.plawetzki.net: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Found AAAA record for autodiscover.purejava.org: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Found AAAA record for autoconfig.purejava.org: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Found AAAA record for mail.plawetzki.net: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:42 CEST 2021 - Found AAAA record for plawetzki.net: 2a01:4f8:c010:8a35::2 - skipping A record check
acme-mailcow_1       | Fri Aug  6 09:11:43 CEST 2021 - Confirmed AAAA record with IP 2a01:04f8:c010:8a35:0000:0000:0000:0002
acme-mailcow_1       | Fri Aug  6 09:11:43 CEST 2021 - Certificate /var/lib/acme/mail.plawetzki.net/cert.pem validation done, neither changed nor due for renewal.
acme-mailcow_1       | Fri Aug  6 09:11:43 CEST 2021 - Certificates were successfully validated, no changes or renewals required, sleeping for another day.
```
Thank you very much!

**Comment by eddiewebb** [comment]
@purejava - what do you mean "offered you" is it something patched for others or a config change I am not clear.

**Comment by purejava** [comment]
@eddiewebb It was just a regular update installed via `update.sh`, that fixed the issue.
