### ISSUE TITLE
Redo prefetch_images() to exlude ipv6nat container if native IPv6 NAT is active

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#4218]
## Summary

At the moment [prefetch_images()](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh#L61-L73) will download the ipv6nat container even when native IPv6 NAT is active, since it uses the docker-compose.yml on the git for getting the images.

## Motivation

No need for the ipv6nat container when native IPv6 NAT is active and thus saving 18MB of space :)
Can be 'fixed' using the local compose file or checking if native IPv6 NAT is active which would be the better solution in my eyes

## Additional context
```
[...]
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Great! Native IPv6 NAT is active.
[...]
Prefetching images...
[...]
latest: Pulling from robbertkl/ipv6nat
5843afab3874: Already exists
ec57c29612a1: Pull complete
c281b84f853c: Pull complete
8b0d3f64dab0: Pull complete
Digest: sha256:0cf4971efbe9df3c39f6b11666bece782891856598c6d3649e900afc88f76c00
Status: Downloaded newer image for robbertkl/ipv6nat:latest
docker.io/robbertkl/ipv6nat:latest
Stopping mailcow...
[...]
```

**Comment by andryyy** [comment]
Merci, I will fix it. :)
