### ISSUE TITLE
Autoconfig ports broken

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#4221]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Hi, after latest php8 changes, there is bug with autoconfig ports. You added some substr for extracting ports grom env vars, but in mailcow.conf is just this

```
SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
```

it looks like you have for ex. this `IMAPS_PORT:-993` on your system, so you tried to extract port from it.

https://github.com/mailcow/mailcow-dockerized/commit/cf8fdae2773e96b7b1753c38f011d77cd2f25448#diff-e27671f283e93d0f8cab7769916665b2b3b085dc540999b3a4dee9651a202656

data/web/inc/vars.inc.php

## Logs

```
[imap] => Array ( [server] => mail.mailcow.email [port] => 93 [tlsport] => 10 ) [pop3] => Array ( [server] => mail.mailcow.email [port] => 95 [tlsport] => 10 ) [smtp] => Array ( [server] => mail.mailcow.email [port] => 65 [tlsport] => 87
```

## Reproduction

Open DNS diag modal and scroll to end

## System information

Ubuntu 18.04.2 LTS, Docker version 18.09.6, build 481bc77

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment]
Oh no. Sorry. Will fix it in a bit.

**Comment by feldsam** [comment]
not fixed, you forgot POP_PORT in IMAP, but I also refactored it in pr #4223
