### ISSUE TITLE
netfilter restarts after update

### ISSUE THREAD

**Issue by bodsch** [mailcow/mailcow-dockerized#4227]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After an update today, the netfilter and ipv6nat container are permanently restarting.

## Logs
```
mailcow-dockerized]# docker-compose logs  netfilter-mailcow                   
Attaching to mc_netfilter-mailcow_1
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 525, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 286, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
netfilter-mailcow_1  | Clearing all bans
netfilter-mailcow_1  | Traceback (most recent call last):
netfilter-mailcow_1  |   File "/server.py", line 525, in <module>
netfilter-mailcow_1  |     clear()
netfilter-mailcow_1  |   File "/server.py", line 286, in clear
netfilter-mailcow_1  |     filter6_table = iptc.Table6(iptc.Table6.FILTER)
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip6tc.py", line 589, in __new__
netfilter-mailcow_1  |     obj._init(name, autocommit)
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip6tc.py", line 606, in _init
netfilter-mailcow_1  |     self.refresh()
netfilter-mailcow_1  |   File "/usr/lib/python3.8/site-packages/iptc/ip4tc.py", line 1634, in refresh
netfilter-mailcow_1  |     raise IPTCError("can't initialize %s: %s" % (self.name,
netfilter-mailcow_1  | iptc.ip4tc.IPTCError: can't initialize filter: b'iptables who? (do you need to insmod?)'
```

## Reproduction
i just call the update script.

## System information

```
cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

uname -a
Linux mail 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux
```

| Question | Answer |
| --- | --- |
| My operating system | Arch Linux  (see above)|
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | kvm |
| Server/VM specifications (Memory, CPU Cores) |RAM: 8GiB RAM, CPU: 2 Intel Xeon Cores |
| Docker Version (`docker version`) | Docker version 20.10.8, build 3967b7d28e|
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | no |

**Comment by bodsch** [comment]
i removed all IPv6 konfigurations and the container starts successfully

**Comment by bodsch** [comment]
I think, this Issue can be close.?

**Comment by MAGICCC** [comment]
If its ok for you now, yes I can close it
