### ISSUE TITLE
Editing App password throws exception

### ISSUE THREAD

**Issue by alfonsrv** [mailcow/mailcow-dockerized#4239]
<details>
    <summary>Disclaimer</summary>
<b>Prior to placing the issue, please check following:</b>
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).
</details>

## Summary

Creating and then editing an App token causes the following error in the frontend, making it impossible to edit. Using `docker-compose logs`, nothing shows up on the server-side.

```
An unknown error occured: TypeError Object ( [message:protected] => 
Cannot access offset of type string on string [string:Error:private] => 
[code:protected] => 0 [file:protected] => /web/inc/functions.app_passwd.inc.php [line:protected] => 
192 [trace:Error:private] => Array ( [0] => Array ( [file] => /web/edit.php [line] => 
1569 [function] => app_passwd [args] => Array ( [0] => details [1] => 1 ) ) ) [previous:Error:private] => )
```

On another note – while it is not an issue currently, I think having the app passwords serializable (1, 2, 3, 4, ...) could pose a serious security risk in the future. E.g. with an unforeseen change to the codebase

## Reproduction

Create app password.  
Click edit app password.

## System information

Mailcow version 7ab1405b0032dcf50698a357ea4a1378540b9ddc

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc | Docker on HyperV |
| Server/VM specifications (Memory, CPU Cores) | 12GB, 6 vCPU |
| Docker Version (`docker version`) | `20.10.7` |
| Docker-Compose Version (`docker-compose version`) | ` 1.25.0` |
| Reverse proxy (custom solution) | Traefik |

**Comment by niiyankee** [comment]
I can confirm this issue.

**Comment by andryyy** [comment]
Fixed in staging
