### ISSUE TITLE
Roundcube error 500

### ISSUE THREAD

**Issue by aboogerd** [mailcow/mailcow-dockerized#4240]
Hi there, 

Roundcube isn't available after last update commit 50c90ba. It shows html error 500.

SoGo is available and the RC folder is still there and seems untouched by the update.

Cheers, Alexander

**Comment by bessone** [comment]
Hello,

you need to update Roundcube to 1.5 RC (at least) because of PHP 8.x compatibility.

See updated guide here: https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

Be careful if you use CardDav plugin as it could cause other problems.

**Comment by bessone** [comment]
After updating Roundcube to 1.5 RC and keeping CardDAV v3.0.3 as per the documentation the error 500 persists, with this message: 

```fatal error: unparenthesized `a ? b : c ? d : e` is not supported. use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /web/rc/plugins/carddav/carddav.php on line 352```

I think related to compatibility with PHP 8, updating CardDAV to the latest release available ([v4.1.2](https://github.com/mstilkerich/rcmcarddav/releases/tag/v4.1.2)) the error is gone, the contact book seems to work, more in-depth tests would be needed to confirm and update the documentation.

**Comment by MAGICCC** [comment]
If you could do a Pullrequest for the docs that would be nice!

**Comment by andryyy** [comment]
Perhaps what @FingerlessGloves run into?

**Comment by bessone** [comment]
Hey @MAGICCC , done with the PR [297](https://github.com/mailcow/mailcow-dockerized-docs/pull/297)

**Comment by MAGICCC** [comment]
Nice, I added a comment there and will close here
