### ISSUE TITLE
DKIM signature does not corespond with DKIM record generated

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#4247]
I went to Mailcow dockerized admin and generated a DKIM key for a domain. Then I took the DNS record it shows and I applied it to my Cloudflare (as always). That worked and DNS record is showed correctly in mail-teste.com, but it reports that emails sent from the server are signed by a different, not corresponding/valid key, so my score is way lower than it should be.

I tried to restart the server to apply the new key, but no progress. Any idea how to fix this issue?

You can spot the diference easile here: https://www.mail-tester.com/test-bh0qqvpyx&reloaded=1 (the public key is what mailcow provided)

I posted this to the forum also, but no anser after a few days..and as this issue is pretty urgent, I am force to put it here also. Here is the forum post: https://community.mailcow.email/d/1058-dkim-signature-does-not-corespond-with-dkim-record-generated

**Comment by MAGICCC** [comment]
I replied to your thread, will close it then here
