### ISSUE TITLE
millions of dns queries for mailcow.email

### ISSUE THREAD

**Issue by kernchr** [mailcow/mailcow-dockerized#425]
I see every 2 seconds a dns-query from mailcow for mailcow.email (on ipv4 and ipv6).
What causes this? Is this a normal behaviour?

Jul  1 08:36:14 dnsmasq[1263]: query[AAAA] mailcow.email from 192.168.1.101
Jul  1 08:36:14 dnsmasq[1263]: cached mailcow.email is NODATA-IPv6
Jul  1 08:36:14 dnsmasq[1263]: query[A] mailcow.email from 192.168.1.101
Jul  1 08:36:14 dnsmasq[1263]: cached mailcow.email is 5.1.76.4
Jul  1 08:36:14 dnsmasq[1263]: query[PTR] 4.76.1.5.in-addr.arpa from 192.168.1.101
Jul  1 08:36:14 dnsmasq[1263]: cached 5.1.76.4 is www.servercow.de
Jul  1 08:36:17 dnsmasq[1263]: query[AAAA] mailcow.email from 192.168.1.101
Jul  1 08:36:17 dnsmasq[1263]: cached mailcow.email is NODATA-IPv6
Jul  1 08:36:17 dnsmasq[1263]: query[A] mailcow.email from 192.168.1.101
Jul  1 08:36:17 dnsmasq[1263]: cached mailcow.email is 5.1.76.4
Jul  1 08:36:17 dnsmasq[1263]: query[PTR] 4.76.1.5.in-addr.arpa from 192.168.1.101

**Comment by andryyy** [comment]
Hi,
this is reduced now and fixed with the next push.

**Comment by kernchr** [comment]
perfect, thx!
