### ISSUE TITLE
Keine Mailbox ausgewählt

### ISSUE THREAD

**Issue by Moepchi** [mailcow/mailcow-dockerized#426]
Hallo,

ich musste heute meinen Root neu starten (updates). Jetzt nach dem Neustart hab ich Mailcow per docker-compose up -d gestartet. Alle seiten gehen nur wird mir bei SoGo angezeigt, dass keine Mailbox ausgewählt ist und das bei allen eingerichteten Adressen.

Hab es dann noch mal beendet und wieder gestartet aber hat leider nicht geholfen.
Was kann ich jetzt machen, dass es wieder funktioniert?

**Comment by andryyy** [comment]
Vermutlich baut Dovecot die dhparams neu. Das dauert einen Moment. `docker-compose logs dovecot-mailcow`.

**Comment by Assassins88** [comment]
dovecot-mailcow_1    | 2017-07-02 07:44:44,059 CRIT Supervisor running as mailcow (no user in config file)
dovecot-mailcow_1    | 2017-07-02 07:44:44,063 INFO supervisord started with pid 1
dovecot-mailcow_1    | 2017-07-02 07:44:45,065 INFO spawned: 'cron' with pid 36
dovecot-mailcow_1    | 2017-07-02 07:44:45,066 INFO spawned: 'dovecot' with pid 37
dovecot-mailcow_1    | 2017-07-02 07:44:45,068 INFO spawned: 'syslog-ng' with pid 38
dovecot-mailcow_1    | 2017-07-02 07:44:45,070 INFO spawned: 'logfiles' with pid 39
dovecot-mailcow_1    | 2017-07-02 07:44:45,076 INFO exited: logfiles (exit status 1; not expected)
dovecot-mailcow_1    | 2017-07-02 07:44:46,099 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2017-07-02 07:44:46,099 INFO success: dovecot entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2017-07-02 07:44:46,099 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | 2017-07-02 07:44:46,100 INFO spawned: 'logfiles' with pid 52
dovecot-mailcow_1    | Jul  2 07:44:45 mail syslog-ng[38]: syslog-ng starting up; version='3.8.1'
dovecot-mailcow_1    | Jul  2 07:44:45 mail dovecot: master: Dovecot v2.2.29.1 (e0b76e3) starting up for imap, sieve, lmtp, pop3
dovecot-mailcow_1    | Jul  2 07:44:45 mail dovecot: ssl-params: Generating SSL parameters
dovecot-mailcow_1    | 2017-07-02 07:44:47,104 INFO success: logfiles entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1    | Jul  2 07:45:01 mail CRON[53]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:45:01 mail CRON[55]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:45:01 mail CRON[53]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:45:13 mail dovecot: ssl-params: SSL parameters regeneration completed
dovecot-mailcow_1    | Jul  2 07:46:01 mail CRON[59]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:46:01 mail CRON[61]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:46:01 mail CRON[59]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:47:01 mail CRON[64]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:47:01 mail CRON[66]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:47:01 mail CRON[64]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:47:16 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=71, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:47:17 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=75, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:47:17 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1962
dovecot-mailcow_1    | Jul  2 07:47:17 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=79, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:47:17 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1505
dovecot-mailcow_1    | Jul  2 07:47:17 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1962
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=83, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=87, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1962
dovecot-mailcow_1    | Jul  2 07:48:01 mail CRON[91]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:48:01 mail CRON[92]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=94, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1505
dovecot-mailcow_1    | Jul  2 07:48:01 mail CRON[91]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:48:01 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1962
dovecot-mailcow_1    | Jul  2 07:48:09 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=97, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:09 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=100, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:10 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1954
dovecot-mailcow_1    | Jul  2 07:48:10 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1505
dovecot-mailcow_1    | Jul  2 07:48:10 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=103, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:48:10 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1954
dovecot-mailcow_1    | Jul  2 07:49:01 mail CRON[105]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:49:01 mail CRON[107]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:49:01 mail CRON[105]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:49:32 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=112, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:49:32 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1505
dovecot-mailcow_1    | Jul  2 07:50:01 mail CRON[116]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:50:01 mail CRON[118]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:50:01 mail CRON[116]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:50:13 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=121, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:50:13 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=125, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:50:13 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1962
dovecot-mailcow_1    | Jul  2 07:50:14 mail dovecot: imap-login: Login: user=<info@gsg-chemnitz.de>, method=PLAIN, rip=172.22.1.252, lip=172.22.1.6, mpid=129, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Jul  2 07:50:14 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1505
dovecot-mailcow_1    | Jul  2 07:50:14 mail dovecot: imap(info@gsg-chemnitz.de): Logged out in=144 out=1954
dovecot-mailcow_1    | Jul  2 07:51:01 mail CRON[132]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:51:01 mail CRON[134]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:51:01 mail CRON[132]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:52:01 mail CRON[137]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:52:01 mail CRON[139]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:52:02 mail CRON[137]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:53:01 mail CRON[141]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:53:01 mail CRON[143]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:53:01 mail CRON[141]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:54:01 mail CRON[145]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:54:01 mail CRON[147]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:54:01 mail CRON[145]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:55:01 mail CRON[150]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:55:01 mail CRON[152]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:55:01 mail CRON[150]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:56:01 mail CRON[154]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:56:01 mail CRON[156]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:56:01 mail CRON[154]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:57:01 mail CRON[158]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:57:01 mail CRON[160]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:57:01 mail CRON[158]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:58:01 mail CRON[162]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:58:01 mail CRON[164]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:58:01 mail CRON[162]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 07:59:01 mail CRON[167]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 07:59:01 mail CRON[169]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 07:59:01 mail CRON[167]: pam_unix(cron:session): session closed for user mailcow
dovecot-mailcow_1    | Jul  2 08:00:01 mail CRON[171]: pam_unix(cron:session): session opened for user mailcow by (uid=0)
dovecot-mailcow_1    | Jul  2 08:00:01 mail CRON[173]: (mailcow) CMD (  /usr/local/bin/imapsync_cron.pl)
dovecot-mailcow_1    | Jul  2 08:00:01 mail CRON[171]: pam_unix(cron:session): session closed for user mailcow

**Comment by Moepchi** [comment]
https://hastebin.com/uvokuxiwuj.rb

**Comment by andryyy** [comment]
Da sind doch sogar IMAP Logins zu sehen. Wird wohl jetzt gehen?

**Comment by Moepchi** [comment]
Ja das Einloggen über SoGo an sich geht nur wird mir dann da angezeigt, dass keine Mailbox ausgewählt ist (siehe Bild). https://ibb.co/eeVKKa

**Comment by andryyy** [comment]
Vermutlich baut Dovecot die dhparams neu. Das dauert einen Moment. Wie gesagt. Laut Logs tat es auch genau das.

IMAP ist da. SOGo hast du ja ganz bestimmt mal im Browser neu geladen...

**Comment by Moepchi** [comment]
Ja, hab ich gemacht. Hab auch da versucht nen neuen Ordner zu erstellen aber da kommt dann auch ein Fehler. Na ich werd mal noch ein wenig warten und dann schauen wir mal. Sollte es dann immer noch nicht  gehen, melde ich mich noch mal.

**Comment by andryyy** [comment]
Sonst einfach mal docker-compose down + docker-compose up -d ausführen und dann einen Moment _warten_. Sonst auch mal vorher die dhparams aus data/assets/ssl-example nach data/assets/ssl kopieren _bevor_ du down und up -d ausführst.

**Comment by Moepchi** [comment]
Den Ordner data/assets/ssl-example hab ich da nicht drin. Sind nur 2 einmal passwd und einmal ssl

**Comment by Assassins88** [comment]
Geht leider immer noch nicht.

**Comment by Moepchi** [comment]
Ok, nach nem neustart von dovecot und postfix geht es jetzt :)
