### ISSUE TITLE
Pushover Feedback

### ISSUE THREAD

**Issue by Maximilian1021** [mailcow/mailcow-dockerized#4265]
## Summary

A clear and concise description of what the problem is.
For example: I'm always frustrated when [...]

**I am always frustrated when Pushover sends me a notification, but then there is no mail in the inbox because it is rejected again in rspamd.**

## Motivation

What are you about to solve or improve with this idea?
What would be the benefit for most users?

**The problem could be solved by only firing the notification if the message is allowed with "No Action" or if it just came into the mailbox.

No waiting until the sending mail server starts a new attempt to deliver the mail.**

## Additional context

Add any other context or screenshots about the feature request.

**Thank you for bringing a great product to the market!**

**Comment by andryyy** [comment]
Thanks!

Hm, this should not happen:

```
  mailcow_rcpt = <<EOD
return function(task)
  local action = task:get_metric_action('default')
  if task:has_symbol('NO_LOG_STAT') or (action == 'reject' or action == 'add header' or action == 'rewrite subject') then
    return false
  else
    if task:get_symbol("RCPT_MAILCOW_DOMAIN") then
      return true
    end
    return false
  end
end
EOD;

```

Let me run some tests.

**Comment by andryyy** [comment]
Can you try this? => https://github.com/mailcow/mailcow-dockerized/commit/5e5ab6cf40901840ad3f865f8852b7f3c0b8e20b

**Comment by Maximilian1021** [comment]
Sorry for the late reply.

It looks like it will work.

Thanks a lot 

//CLOSE
