### ISSUE TITLE
Disclaimer To ALL Outgoing Emails

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#4267]
I'd like to place a footer disclaimer on ALL outgoing emails.  I know that Postfix works with a package called "altermime".

Does Mailcow currently support this feature, and if not, could we make this a feature request?

-rad

**Comment by MAGICCC** [comment]
Dupe of https://github.com/mailcow/mailcow-dockerized/issues/1485

**Comment by infracritical** [comment]
Nuts...OK.
