### ISSUE TITLE
Please log in via your web browser on sync jobs with gmail

### ISSUE THREAD

**Issue by aliceinwire** [mailcow/mailcow-dockerized#4277]
I'm trying to copy mails from a gmail account and got stuck in the following message.
Error login on [imap.gmail.com] with user [xxxxxxxxxxxxx@gmail.com] auth [LOGIN]: 2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)

I have less secure apps turned on

**Comment by ghost** [comment]
It seems like a classic Imapsync issue. Have you tried to login and go to the following page? https://www.google.com/accounts/DisplayUnlockCaptcha

You may want to try following the official documentation here: https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
