### ISSUE TITLE
your connection not secure mailcow :(

### ISSUE THREAD

**Issue by Ahmed-imamm** [mailcow/mailcow-dockerized#4279]
when i try to access mailcow UI brawser say your connection not secure mailcow :( what i can do 
O.s ubuntu 20 
path : opt/mailcow-dockerized

**Comment by dellarte** [comment]
Are you using a custom reverse proxy ? Did-you enabled acme-container ? do you own the domain you're using ?
Here are some useful links :

https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

IMO, it's not a bug but a misconfiguration. Read the doc ;-)

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

**Comment by Ahmed-imamm** [comment]
???

**Comment by Ahmed-imamm** [comment]
its send and receive normally but when i try tto access it via web its says not secure whyyyyyyyyyyyyyyyyyyyyy

**Comment by Ahmed-imamm** [comment]
any one can join me at any desk ?

**Comment by Ahmed-imamm** [comment]
> Are you using a custom reverse proxy ? Did-you enabled acme-container ? do you own the domain you're using ? Here are some useful links :
> 
> https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/ https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/
> 
> i cant understand :D

**Comment by MAGICCC** [comment]
> Closed due not respecting the issue template - not a bug
> We don't provide support here on GitHub
> Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

We dont give support here!
Either have some basic knowledge or stop hosting a mailserver
