### ISSUE TITLE
Update archlinux docker-compose error: * error decoding 'Ports': Invalid ip address :: address ::: too many colons in address

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#4285]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

After updating ArchLinux today and restarting the system, docker-compose command in the mailcow-dockerized folder doesn't work. The moment before the update, everything was working great. But now it gives this error when running any docker-compose command in the mailcow-dockerized folder:
`[root@mail mailcow-dockerized]# docker-compose ps`
`1 error(s) decoding:`
`* error decoding 'Ports': Invalid ip address :: address ::: too many colons in address`

It shouldn't be docker's problem. Running the plain docker command works just fine. And tested docker-compose not on mailcow works just fine.

p.s. I didn't shut down the docker-compose containers before the restart, they start up automatically after boot, have done this a couple times, but no problems like this have been encountered. 

## Logs

The only log I could find for now is the terminal output, that is stated above.

## Reproduction

No firewall enabled
Bare minimum archlinux install: + docker, docker-compose, vim, git, curl, wget 
The version of git mailcow: the commit - 4066666c707857c3bfd9f62841e0e2dc072e76a9
(After update on 2021-08-29_17_01_37)
Mailcow.conf / docker-compose config file all done by the book.

## System information

| Question | Answer |
| --- | --- |
| My operating system | ArchLinux |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | NO |
| Server/VM specifications (Memory, CPU Cores) | 2 cores, 2 GB |
| Docker Version (`docker version`) | Docker version 20.10.8, build 3967b7d28e |
| Docker-Compose Version (`docker-compose version`) | Docker Compose version 2.0.1 |
| Reverse proxy (custom solution) | none |

**Comment by MAGICCC** [comment]
Can you try to downgrade to 1.x docker-compose?

**Comment by ghost** [comment]
Yes, downgrading to docker-compose:1.29.2-1 worked. (that was the version I had before)

What do you think the problem might be?

Is it something to do with the docker-compose file, the setup?

Do you suggest to update mailcow-dockerized?

Just at the moment my mail server is mission critical...

**Comment by MAGICCC** [comment]
It's because docker-compose v2 changed a lot.
I guess somewhat related to https://github.com/docker/compose/issues/8721

**Comment by GivouDev** [comment]
Is there any solution to this without downgrading docker? Also using arch and having the same problem now.

**Comment by andryyy** [comment]
You don't need to downgrade Docker. You need to use docker-compose v1.

**Comment by GivouDev** [comment]
Yes i meant that, so i need to downgrade docker-compose v1?
Thats confusing...here a quote from the official installation documentation: "Docker Compose (a version <= 2.0 is required)." Do i need to downgrade docker-compose, upgrade mailcow and upgrade docker-compose again?

**Comment by MAGICCC** [comment]
Yes indeed, best would be remove 2.x and download a 1.x version.

I'll change the docs, `<=` is a bit confusing, since it includes a `=`

**Comment by GivouDev** [comment]
Is there in plan to make 2.x full working with mailcow?
I dont want to run into problems in near future with other containers that requires 2.x then.

I will downgrade for now. Thanks :)

**Comment by GivouDev** [comment]
This gets really annoying, everytime i run pacman -Syu i need to downgrade Docker again.
And i have many Container that could profit from the newer Version :(

Looks like i need to install mailcow on bare metal....
Or i create a container and let mailcow run in container in a container with an older docker-compose version...

**Comment by andryyy** [comment]
Just use a different version for mailcow then. Place it somewhere else. 

And nothing benefits from the new compose. The containers are still the same.

**Comment by aminvakil** [comment]
> This gets really annoying, everytime i run pacman -Syu i need to downgrade Docker again. And i have many Container that could profit from the newer Version :(
> 
> Looks like i need to install mailcow on bare metal.... Or i create a container and let mailcow run in container in a container with an older docker-compose version...

Just put `docker-compose` in `IgnorePkg` in `/etc/pacman.conf`.

**Comment by spantaleev** [comment]
Looks like the problematic port mapping is for the `nginx-mailcow` service: https://github.com/mailcow/mailcow-dockerized/blob/89fdd1986d922aa7ae87d589859cd3d483beaa23/docker-compose.yml#L376-L378

With empty `HTTP_BIND` and `HTTPS_BIND`, the `ports` mapping becomes something like:

```yaml
ports:
  - "::80:80"
  - "::443:443"
```

.. which likely told docker-compose v1 "ignore this" (or "expose this port on all interfaces"?), but is something that Compose v2 doesn't like.

Looking at the docker-compose spec about [ports](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports), I don't see an example syntax like the one used here. It's probably better to fix the syntax, so that Compose v2 (which is less forgiving about breaking the spec) is made happy.

------

As a workaround, I've tried redefining the `nginx-mailcow` service's `ports` in `docker-compose.override.yml`, but that didn't seem to work -- the `ports` definition from the main `docker-compose.yml` file was still used (or parsed, at least).

Defining non-empty `HTTP_BIND` / `HTTPS_BIND` in `.env` (`mailcow.conf`) works as a workaround. With that, I've managed to get mailcow-dockerized services working with Compose v2 + `compose-switch`.

**Comment by aminvakil** [comment]
How about setting both `HTTP_BIND` and `HTTPS_BIND` by default to `0.0.0.0`?

**Comment by Zapfmeister** [comment]
Could the default HTTP_BIND and HTTPS_BIND port be set to 0.0.0.0? That would make the issue go away per default

**Comment by aminvakil** [comment]
@Zapfmeister I have brought this up here https://github.com/mailcow/mailcow-dockerized/issues/4315#issuecomment-1083034329, please follow there.
