### ISSUE TITLE
Fail2Ban dies after few hours

### ISSUE THREAD

**Issue by Xeroxxx** [mailcow/mailcow-dockerized#429]
Hello,
my fail2ban instance is dying after few hours. Its not stopping but its not monitoring the containers and does not write any logs anymore.

> fail2ban-mailcow_1   | Watching mailcowdockerized_postfix-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_dovecot-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_sogo-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_php-fpm-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_postfix-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_dovecot-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_sogo-mailcow_1
fail2ban-mailcow_1   | Watching mailcowdockerized_php-fpm-mailcow_1
fail2ban-mailcow_1   | 9 more attempts in the next 600 seconds until xx.xx.xx.xx/24 is banned
fail2ban-mailcow_1   | Traceback (most recent call last):
fail2ban-mailcow_1   |   File "/logwatch.py", line 179, in <module>
fail2ban-mailcow_1   |     clear()
fail2ban-mailcow_1   |   File "/logwatch.py", line 127, in clear
fail2ban-mailcow_1   |     r.lpush("F2B_LOG", json.dumps(log, ensure_ascii=False))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1227, in lpush
fail2ban-mailcow_1   |     return self.execute_command('LPUSH', name, *values)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
fail2ban-mailcow_1   |     connection.send_command(*args)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
fail2ban-mailcow_1   |     self.send_packed_command(self.pack_command(*args))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
fail2ban-mailcow_1   |     self.connect()
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
fail2ban-mailcow_1   |     raise ConnectionError(self._error_message(e))
fail2ban-mailcow_1   | redis.exceptions.ConnectionError: Error 111 connecting to 172.22.1.249:6379. Connection refused.
fail2ban-mailcow_1   | Error in atexit._run_exitfuncs:
fail2ban-mailcow_1   | Traceback (most recent call last):
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
fail2ban-mailcow_1   |     func(*targs, **kargs)
fail2ban-mailcow_1   |   File "/logwatch.py", line 127, in clear
fail2ban-mailcow_1   |     r.lpush("F2B_LOG", json.dumps(log, ensure_ascii=False))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1227, in lpush
fail2ban-mailcow_1   |     return self.execute_command('LPUSH', name, *values)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
fail2ban-mailcow_1   |     connection.send_command(*args)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
fail2ban-mailcow_1   |     self.send_packed_command(self.pack_command(*args))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
fail2ban-mailcow_1   |     self.connect()
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
fail2ban-mailcow_1   |     raise ConnectionError(self._error_message(e))
fail2ban-mailcow_1   | ConnectionError: Error 111 connecting to 172.22.1.249:6379. Connection refused.
fail2ban-mailcow_1   | Error in sys.exitfunc:
fail2ban-mailcow_1   | Traceback (most recent call last):
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
fail2ban-mailcow_1   |     func(*targs, **kargs)
fail2ban-mailcow_1   |   File "/logwatch.py", line 127, in clear
fail2ban-mailcow_1   |     r.lpush("F2B_LOG", json.dumps(log, ensure_ascii=False))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1227, in lpush
fail2ban-mailcow_1   |     return self.execute_command('LPUSH', name, *values)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
fail2ban-mailcow_1   |     connection.send_command(*args)
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
fail2ban-mailcow_1   |     self.send_packed_command(self.pack_command(*args))
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
fail2ban-mailcow_1   |     self.connect()
fail2ban-mailcow_1   |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
fail2ban-mailcow_1   |     raise ConnectionError(self._error_message(e))
fail2ban-mailcow_1   | redis.exceptions.ConnectionError: Error 111 connecting to 172.22.1.249:6379. Connection refused.
fail2ban-mailcow_1   | python2: can't open file '/logwatch.py': [Errno 11] Resource temporarily unavailable

**Comment by mkuron** [comment]
That looks like the redis container is down. Can you check that? If redis is down, things like the forwarding hosts or dkim keys in the web interface should be empty as well. What does `docker-compose logs redis-mailcow` say? Does restarting the fail2ban container suffice to get things working again, or do you actually need to restart redis?

**Comment by Xeroxxx** [comment]
I completely redeployed my env. Now it works. Not sure what happened there. Sry for confusion.
