### ISSUE TITLE
Mailcow Watchdog not sending notifications

### ISSUE THREAD

**Issue by Spartex** [mailcow/mailcow-dockerized#4298]
Mailcow-Watchdog is stating that it is sending notifications in the logs but no notification is being received via email. No errors are shown in the server logs either. The mailcow.conf USE_WATCHDOG=y so not sure why this is happening?

**Comment by MAGICCC** [comment]
Can you update to the lastest version of mailcow and set WATCHDOG_VERBOSE=y in your mailcow.conf?
Then you can restart the watchdog-mailcow container and check the logs.

**Comment by Spartex** [comment]
Hello,

Thank you for your reply and time.
I have updated the image and now in the UI logs it is stating " Error while
sending a notification email to [email address]"

Now I can see with the verbose logs enabled in mailcow.conf on the server when running docker-compose logs --tail=200 watchdog-mailcow that the issue is caused by Microsoft blacklisting the server IP. Thank you, this was very helpful in narrowing down the cause :)
