### ISSUE TITLE
Disable services

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#43]
How can i disable unnecessary services: imap_143, pop3_110, pop3s_995, smtps_465 ? 
I only need the following services: smtp_25, submission_587, imap_993.

**Comment by mkalus** [comment]
You could either block those services with your firewall (which is easier IMHO) or shut them down completely, as follows:

For smtps comment out (prefix each line with #) the following lines in `/etc/postfix/master.cf`:

```
smtps    inet  n       -       n       -       -       smtpd
  -o smtpd_tls_wrappermode=yes
  -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
  -o smtpd_proxy_filter=127.0.0.1:10025
  -o smtpd_client_connection_count_limit=10
  -o smtpd_proxy_options=speed_adjust
```

As for dovecot: I believe you have to search the file  `/etc/dovecot/conf.d/10-master.conf` and comment out the listeners e.g. `inet_listener imap`.

**Comment by andryyy** [comment]
Or use the mailconf.conf to bind them to 127.0.0.1.

**Comment by ghost** [comment]
Thanks
