### ISSUE TITLE
Empty configuration mailboxes pages

### ISSUE THREAD

**Issue by zu4lu** [mailcow/mailcow-dockerized#430]
Hi, what's wrong, i dont get any information on all the config mailboxes pages, only that spinning arrow?
Logged in as admin. See attached picture.
lg Michael
![bildschirmfoto-20170704225855-1339x565](https://user-images.githubusercontent.com/29902262/27842772-309dd398-610d-11e7-8235-8b9060dba24c.png)

**Comment by PhoenixPeca** [comment]
Hi,
Is your mailcow setup in a reverse proxy? This might be something related to issue #400. This could happen when a proxy is configured in such a way that it broke the necessary links to communicate to the mailcow API.

Anyway, we would love to know some information about your setup, because we can't to reproduce your issue. 😉

**Comment by zu4lu** [comment]
Hi, no reverse proxy, this is the section in my mailcow.conf:

# ------------------------------
# HTTP/S Bindings
# ------------------------------

# You should use HTTPS, but in case of SSL offloaded reverse proxies:
HTTP_PORT=80
HTTP_BIND=0.0.0.0

HTTPS_PORT=443
HTTPS_BIND=0.0.0.0

**Comment by zu4lu** [comment]
Hi,
it looks like the "config-website" isn't aloud to read the db-files. Where can i get more information(which logs?)
lg Michael

**Comment by andryyy** [comment]
What do you mean?
Do you block any resources? Any errors in the browser console? Should open with Ctrl + Shift + C.

**Comment by zu4lu** [comment]
it's only a guess. Whenever (in the webinterface) information from the databases is required, there is only the turning arrow, no information. Exemple: logged in as user, showing whitelist, blacklist - no Text, only that turning arrow.
Sorry, i can't describe it any better.

**Comment by zu4lu** [comment]
another example: admin can create a new user, though it doesn't show the existing ones. If the user already exists, it gives an error.

**Comment by zu4lu** [comment]
by the way, no errors in the browser console

**Comment by andryyy** [comment]
It just does not load the ajax request. But then it should log an error. Did you open the "console" window in the debugger?

**Comment by zu4lu** [comment]
![bildschirmfoto-20170714151053-1920x1054](https://user-images.githubusercontent.com/29902262/28213535-c32768aa-68a6-11e7-88f8-4b24235fab7a.png)
