### ISSUE TITLE
SOGo Not Starting Automatically After Reboot

### ISSUE THREAD

**Issue by PhoenixPeca** [mailcow/mailcow-dockerized#431]
This issue might be related to #417

---

Hi @andryyy,

SOGo does not seem to start automatically after executing the `reboot` command in the terminal. 😕 This happened in a test mailcow-dockerized setup I have created yesterday.

* executing `docker ps -a` shows that SOGo container is Up:
![screenshot 2](https://user-images.githubusercontent.com/9730242/27848452-dc619a74-6177-11e7-9a38-194e42f8ec57.png)

* It's just that the SOGo web interface failed to start so Nginx can't RP to it and just reports 502 HTTP error code:
![screenshot 3](https://user-images.githubusercontent.com/9730242/27848525-4351ca88-6178-11e7-9d1f-d5b051ec52a7.png)

* A temporary solution to this issue is to log-in to the mailcow web UI and manually click the  `Restart SOGo` button:
![screenshot 1](https://user-images.githubusercontent.com/9730242/27848383-482f68ae-6177-11e7-9fe9-c7321e0aa0c3.png)

😄

**Comment by stevesbrain** [comment]
If it helps any @PhoenixPeca I'm on the latest update available on master (as per `./update.sh`) and I cannot replicate this - everything starts fine for me straight away.

**Comment by PhoenixPeca** [comment]
Oh!! Thanks @stevesbrain. I have just retested it again on the same machine with all other services disabled, and it worked. It must be a memory error on my end. Thanks! I'm closing this now.
