### ISSUE TITLE
I can't see webmail messages.

### ISSUE THREAD

**Issue by lucas1** [mailcow/mailcow-dockerized#4310]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
I migrated of server, I install like in https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_install/, after I restored backup.
the admin worked fine, but when I opened my email it has the messages but I can't open them, I sent an email and it worked, but I can't see it either.

## Logs

[WARN] <0x55e5840b2840[SOGoMailFolder]:folderINBOX> IMAP connection is broken, trying to reconnect...
[ERROR] <0x0x55e5840ad010[NGImap4Connection]> Error fetching 100 uids for url: imap://lucas%40mydomail.com@172.22.1.250/INBOX/?tls=NO&tlsVerifyMode=none

## Reproduction

![Screenshot at 2021-11-01 17-02-04](https://user-images.githubusercontent.com/784699/139734241-9cfec163-09b0-4084-abf7-f84c699f0a86.png)

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 11 |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB / 4 Cores |
| Docker Version (`docker version`) | 20.10.9 |
| Docker-Compose Version (`docker-compose version`) | I1.29.2|
| Reverse proxy (custom solution) | nginx |

**Comment by andryyy** [comment]
That’s not enough Dovecot logs I’m afraid. 
Also missing a bunch of other information that we ask for.

**Comment by lucas1** [comment]
## Dovecot

11/01/2021, 04:34:47 PM	info	imap(lucas@mydomain.com)<286><r1r9RL/P02+q6T39>: Disconnected: FETCH failed: Mailbox INBOX: UID=486: read() failed: read(/var/vmail/mydomain.com/lucas/Maildir/cur/1635794497.M581604P718.413a94738817,S=1339,W=1372:2,) failed: Decryption error: no private key available (read reason=14/14 headers not cached (first=BCC) (Mail has other cached fields, reset_id=1635793166)) in=327 out=19056 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
11/01/2021, 04:34:47 PM	err	imap(lucas@mydomain.com)<286><r1r9RL/P02+q6T39>: Error: Mailbox INBOX: UID=486: read() failed: read(/var/vmail/mydomain.com/lucas/Maildir/cur/1635794497.M581604P718.413a94738817,S=1339,W=1372:2,) failed: Decryption error: no private key available (read reason=14/14 headers not cached (first=BCC) (Mail has other cached fields, reset_id=1635793166))
11/01/2021, 04:34:46 PM	info	imap-login: Login: user=<lucas@mydomain.com>, method=PLAIN, rip=170.233.61.253, lip=172.22.1.250, mpid=286, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)

**Comment by andryyy** [comment]
You didn’t restore the crypt volume. :)

**Comment by lucas1** [comment]
Thank you very much and congratulations for the excellent work.

**Comment by andryyy** [comment]
You are welcome \o/ Thank you :)
