### ISSUE TITLE
Invalid URL in mailcow.conf

### ISSUE THREAD

**Issue by ctrl-i** [mailcow/mailcow-dockerized#4322]
Whilst trying to debug why my Postfix and Dovecot TLS certificates were not being automatically updated I came across this URL in mailcow.conf.  It no longer points to the correct location in the mailcow documentation.

https://mailcow.github.io/mailcow-dockerized-docs/debug-reset-tls/
https://github.com/mailcow/mailcow-dockerized/blob/85454d34063670a4d537f37a467f304aa889e4f2/generate_config.sh#L344

**Comment by andryyy** [comment]
Merci :)

**Comment by MAGICCC** [comment]
Also added a redirect in the docs :)
https://github.com/mailcow/mailcow-dockerized-docs/commit/5f45275409d9fe292b5215a7ec4f526a33b5bf6e
