### ISSUE TITLE
Apache reverse proxy on another host not working with Sogo

### ISSUE THREAD

**Issue by hb9fxq** [mailcow/mailcow-dockerized#433]
Using Apache reverse proxy on another host, (e.g. Apache 192.168.90.2, mailcow dockerized 192.168.90.4) the mail folder subject/sender information is missing. 
Chrome network log show all requests are Status=200 OK 

![sogo_reverse_proxy_empty_inbox](https://user-images.githubusercontent.com/1089689/27883674-a4fd9d1c-61d1-11e7-9f17-563ba535f956.png)

Anything / mailcow gui / sending & reading mails with sogo working all fine.

**Comment by andryyy** [comment]
Hi,

Have you changed _all_ IPs in the code accordingly? It is not enough to only change the network in the compose file.

If so: Does it work as expected without RP?

**Comment by hb9fxq** [comment]
Without RP, by using the IP direct everything is working fine (also tried from other PCs / empty cache, empty local storage)I've tried: 

HTTP_PORT=8080
HTTP_BIND=192.168.90.4

HTTPS_PORT=4433
HTTPS_BIND=192.168.90.4


AND: 


HTTP_PORT=8080
HTTP_BIND=0.0.0.0

HTTPS_PORT=4433
HTTPS_BIND=0.0.0.0

+ tried to proxy to http and https, both with the same result
