### ISSUE TITLE
SOGo: Uploaded attachments can't be deleted

### ISSUE THREAD

**Issue by max06** [mailcow/mailcow-dockerized#4331]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).
---

- [X] I'm here to report an issue, not to spend precious time collecting all the data. Feel free to close this issue if you don't like this.

## Summary
Installed today. Default installation, nothing changed. 
Deleting uploaded attachments (in SOGo) is not possible, might cause unvoluntary data leaks.

## Reproduction
- Log into SOGo
- Draft a new Mail
- Upload an attachment
- Delete the attachment (by clicking on the X right of the attachment name in the draft modal)
- Close the draft.
- Switch to the drafts-folder and open that draft again.
- Find the "deleted" attachment in the draft modal.

Steps 4-7 can be repeated at will, result is always the same.

## System information

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by MAGICCC** [comment]
Sounds like a SOGo issue, you may ask in their issue tracker https://www.sogo.nu/bugs/view_all_bug_page.php

**Comment by max06** [comment]
You're probably right - feel free to forward this issue.
I'm not gonna create an account with their bugtracker just to report one issue. (Not cocky, just too much stuff to work on)

**Comment by MAGICCC** [comment]
done, https://www.sogo.nu/bugs/view.php?id=5432

**Comment by max06** [comment]
Thank you very much! 👍🏼

**Comment by MAGICCC** [comment]
Fixed in https://github.com/inverse-inc/sogo/commit/6ef99a5ec4a655323ddbc9da8955239a432e5180 and then present in 5.3.1 once released
