### ISSUE TITLE
http validation failure while using custom site template

### ISSUE THREAD

**Issue by igregma** [mailcow/mailcow-dockerized#4341]
I'm using a site configured as ADDITIONAL SAN with the custom nginx template mentioned here:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-nginx/

My problem, because of the http redirect block (which I want to use)
` location / {
    return 301 https://$host$uri$is_args$args;
  }
}`

the HTTP validation for Let's encrypt always fail ("_Confirmed A record with IP X.X.X.X, but HTTP validation failed_"). Removing the redirect - instant success.
Any idea how to fix this?

**Comment by andryyy** [comment]
Hey, please don't skip the issue template.

Check mailcow.conf for ADDITIONAL_SERVER_NAMES and add the additional SAN there.

**Comment by igregma** [comment]
My mistake, you're right with the template - sorry :-(

Your idea does not change anything, still validation failure. Think the redirect to https works before anything else, so no chance to validate http?

**Comment by andryyy** [comment]
Did you run up -d after changing the file?

**Comment by andryyy** [comment]
Oh and please also run `docker-compose restart acme-mailcow`. Do you have a reverse proxy in front of your mailcow?

**Comment by igregma** [comment]
yes, did everything.. up -d, restart nginx and acme :-/
No, no proxy.
Configured are 4 domains (with subdomains), all working like charme. Just the one I want to use with own nginx config / own root is the troublemaker.

**Comment by andryyy** [comment]
Can you post the config? 🙂

Am Freitag, dem 26.11.2021 um 14:18 -0800 schrieb igregma:

**Comment by igregma** [comment]
```
`
# Additional SAN for the certificate
#
# You can use wildcard records to create specific names for every domain you add to mailcow.
# Example: Add domains "example.com" and "example.net" to mailcow, change ADDITIONAL_SAN to a value like:
#ADDITIONAL_SAN=imap.*,smtp.*
# This will expand the certificate to "imap.example.com", "smtp.example.com", "imap.example.net", "imap.example.net"
# plus every domain you add in the future.
#
# You can also just add static names...
#ADDITIONAL_SAN=srv1.example.net
# ...or combine wildcard and static names:
#ADDITIONAL_SAN=imap.*,srv1.example.com
#

ADDITIONAL_SAN=www.*,autoconfig.*,autodiscover.*,webmail.MYDOMAIN1.net,MYDOMAIN2.de,MYDOMAIN1.net

# Additional server names for mailcow UI
#
# Specify alternative addresses for the mailcow UI to respond to
# This is useful when you set mail.* as ADDITIONAL_SAN and want to make sure mail.maildomain.com will always point to the mailcow UI.
# If the server name does not match a known site, Nginx decides by best-guess and may redirect users to the wrong web root.
# You can understand this as server_name directive in Nginx.
# Comma separated list without spaces! Example: ADDITIONAL_SERVER_NAMES=a.b.c,d.e.f

ADDITIONAL_SERVER_NAMES=webmail.MYDOMAIN1.net,MYDOMAIN1.com,www.MYDOMAIN1.com

# Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n

SKIP_LETS_ENCRYPT=n

# Create seperate certificates for all domains - y/n
# this will allow adding more than 100 domains, but some email clients will not be able to connect with alternative hostnames
# see https://wiki.dovecot.org/SSL/SNIClientSupport
ENABLE_SSL_SNI=n

# Skip IPv4 check in ACME container - y/n

SKIP_IP_CHECK=n

# Skip HTTP verification in ACME container - y/n

SKIP_HTTP_VERIFICATION=n

`
```

**Comment by andryyy** [comment]
Oh, sorry. I mean the Nginx site you added. 

Can you check the current docs for the HTTPS redirect, too? Make sure you aren’t using an older version of that redirect config. Any other sites or modifications on mailcows Nginx?

**Comment by igregma** [comment]
Oh ok, here we go... think that is the right redir conf?!

```
server {
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
  ssl_ecdh_curve X25519:X448:secp384r1:secp256k1;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;
  index index.php index.html;
  client_max_body_size 0;
  root /web/domain1;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  server_name MYDOMAIN1.com www.MYDOMAIN1.com;
  server_tokens off;

  # This allows acme to be validated even with a different web root
  location ^~ /.well-known/acme-challenge/ {
    default_type "text/plain";
    rewrite /.well-known/acme-challenge/(.*) /$1 break;
    root /web/.well-known/acme-challenge/;
  }



  if ($scheme = http) {
    return 301 https://$server_name$request_uri;
  }
}

```

**Comment by igregma** [comment]
Testing a little bit...
Without the https redirect for the custom site I get an 404 while testing with
`docker-compose exec acme-mailcow curl -4 http://MYDOMAIN1.com/.well-known/acme-challenge/1 --write-out %{http_code}`

With the redirect it's a 301.
Have no clue why... the nginx conf seems to be fine?!

Nginx Log shows the 301 for acme too:

`nginx-mailcow_1      | 172.22.1.1 - - [28/Nov/2021:13:45:07 +0100] "GET /.well-known/acme-challenge/1584023223678 HTTP/1.1" 301 162 "-" "curl/7.79.1" "-"
`

**Comment by andryyy** [comment]
Can you try with „ root /web;“ instead of „ root /web/.well-known/acme-challenge/;“ in the location?

I am on mobile, cannot format it better.

**Comment by igregma** [comment]
Did not change anything, the custom site still gets an Redirect 301 for the acme dir :-(

`172.22.1.1 - - [28/Nov/2021:14:39:33 +0100] "GET /.well-known/acme-challenge/166621389424339 HTTP/1.1" 301 162 "-" "curl/7.79.1" "-"
`

**Comment by igregma** [comment]
I debug the nginx config a little bit and was able to fix the problem! The trick is to wrap the https redirect with a "location" reference:

`
    location ^~ /.well-known/acme-challenge/ {
    default_type "text/plain";
    rewrite /.well-known/acme-challenge/(.*) /$1 break;
    root /web/.well-known/acme-challenge/;
  }
  location / {
    root /web/xyz;
    if ($scheme = http) {
    return 301 https://$server_name$request_uri;
  }
  }
}
`
