### ISSUE TITLE
plz custom port

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#4348]
custom port for who cant use port 25

**Comment by andryyy** [comment]
That’s not how mail works.

**Comment by ghost** [comment]
i was just fucking asking

**Comment by MAGICCC** [comment]
You need port 25 to communicate from server to server. If you change your port to e.g. 26 then every server in the world needs to send to your server on port 26 and and that's impossible to ask for every mailserver out there.
