### ISSUE TITLE
Relay access denied (in reply to RCPT TO command)

### ISSUE THREAD

**Issue by NiclasPe** [mailcow/mailcow-dockerized#4350]
Hello, I have a mailcow dockerized instance running with the IP 192.103.4.1. Before that there is a proxmox mail gateway with the IP 192.103.4.2, which accepts the emails, filters them and forwards them to mailcow. Outgoing emails are sent as requested via the Proxmox mailgatewy. Incoming will be rejected by Mailcow with the error message: Relay access denied (in reply to RCPT TO command) 

I hope one of you can help me, I just don't know what to do next.

**Comment by NiclasPe** [comment]
Update: 

This Issue also happends if I use Mailcow as standalone Server.

**Comment by andryyy** [comment]
You cannot relay unauthenticated to a domain not managed on your mailcow. 

This is not a bug but a question regarding the configuration for a specific scenario. Please move it to the correct place. :)

**Comment by NiclasPe** [comment]
But I just tried a VPS that was set up from scratch (Mailcow only) and it happens there too. A slightly older instance, which I set up a month ago, received the emails without any problems. (regardless of whether via the gateway or directly!)

**Comment by andryyy** [comment]
Yes, you are probably setting it up wrong. Like checking „relay domain“.

**Comment by NiclasPe** [comment]
in the new mailserver isn´t set any relay domain, becurse its mailcow only and it wont work. I set it up like the other by the tutorial: https://apfelcast.com/proxmox-festplatte-an-vm-und-lxc-durchreichen-hdd-passthrough-home-server-selbst-bauen-teil-16-2/

**Comment by NiclasPe** [comment]
This issue happens if I will send an email to the mailcow address. No relaying ore something just receiving emails.

**Comment by NiclasPe** [comment]
Ok i solved the Error by grand rights 777 to the /opt/mailcow_dockerized und /var/lib/docker/volumes directory.

Maybe that is something to add in the documents.
so thanks for your help!
