### ISSUE TITLE
[SOGO 1.103 ] Hyperlinks in emails are erroneously converted to all lowercase characters

### ISSUE THREAD

**Issue by jortkoopmans** [mailcow/mailcow-dockerized#4355]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Thanks for this great project, I really love it! :smile: 
There is a problem with SOGo since the recent 5.3.0 upgrade, which causes all hyperlinks to be displayed in all lowercase characters. Note that the actual email (when read through other clients) does contain Uppercases, it is merely a display formatting issue. However this breaks many workflows, mainly activation/registration links (with complex id's etc), as the user will not end up on the intended URL.

## Probable solution
I'm fairly sure this issue is directly linked to the upstream SOGo bug; https://www.sogo.nu/bugs/view.php?id=5434
The issue seems to be fixed already, but not yet released (slated for 5.3.1).
Given how the mailcow SOGo Dockerfile is arranged, I think simply rebuilding the image (and publishing it to dockerhub) after the upcoming SOGo release, should fix this.

## Logs

There are no relevant logs or errors (silent)

## Reproduction

1. Send an email to an emailbox located in mailcow, with a hyperlink that contains one or more uppercase characters. E.g. https://www.youtube.com/user/YouTube .
2. Open this email in SOGo, the link will be converted to all lowercase.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2vcpu/4GB mem |
| Docker Version (`docker version`) | 20.10.11 |
| Docker-Compose Version (`docker-compose version`) | 1.29 |
| Reverse proxy (custom solution) | None |

**Comment by dragoangel** [comment]
Fixed some time ago

**Comment by jortkoopmans** [comment]
@dragoangel ; Yes and no, the issue has been fixed upstream, but it has not yet been released. It should be included in 5.3.1. https://www.sogo.nu/bugs/changelog_page.php
They seem to be on a ~monthly cadence.
I'm pretty sure Mailcow is still affected by this.

**Comment by dragoangel** [comment]
Sogo stable is requires paid subscription. Mailcow use sogo nightly which is free to use and have a fix, just update your cow...

**Comment by jortkoopmans** [comment]
Apologies, you're right, pulling the latest 1.104 image did resolve this. Thanks!
