### ISSUE TITLE
SOGO 2FA Authentication unavailable

### ISSUE THREAD

**Issue by thebub** [mailcow/mailcow-dockerized#4357]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After the last update of mailcow to mailcow/sogo:1.103 SOGo no longer supports 2FA. Prior to the update, SOGo was supporting 2FA.
User accounts who previously had 2FA activated, do no longer ask for the second factor during login.
Also the settings panel within the SOGo settings is gone.

I know the SOGo has the option to compile it with or without 2FA/MFA support. (https://github.com/inverse-inc/sogo/blob/02f541c43c0e963ef535759e108bafa16ffbc622/configure#L28)
It appears, that 2FA was disabled per default during the nightly build used by mailcow.
## Logs
N/A

## Reproduction
1. Open SOGo
2. Login with a 2FA enabled user
3. The mailbox will be opened, without asking for the second factor.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-81-generic x86_64) |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 1vcpu/4GB mem |
| Docker Version (`docker version`) | I_DO_REPLY_HERE |
| Docker-Compose Version (`docker-compose version`) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by MAGICCC** [comment]
We install the package from their repo: https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/sogo/Dockerfile#L5
If they introduced a bug on their side, you need to ask on their issue tracker. Also the argument is set to 0 since 2 years

**Comment by MAGICCC** [comment]
I created a ticket on their side https://www.sogo.nu/bugs/view.php?id=5438

**Comment by musikpirat** [comment]
Is it possible to switch back to something 

> We install the package from their repo: https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/sogo/Dockerfile#L5 If they introduced a bug on their side, you need to ask on their issue tracker. Also the argument is set to 0 since 2 years

I was not aware that mailcow is based on nightly builds of something. I considered it to be based on stable builds. Is it possible to switch manually to stable builds?

**Comment by MAGICCC** [comment]
Yes if you pay atleast 750$ https://www.sogo.nu/download.html

**Comment by musikpirat** [comment]
> Yes if you pay atleast 750$ https://www.sogo.nu/download.html

Ouch, that's pretty expensive. Maybe for future release it would be possible not to pick a "random" nightly build but store a copy of a proven stable build?

**Comment by abysso2** [comment]
For those who had no time to follow the bug-report on sogo.nu (https://www.sogo.nu/bugs/view.php?id=5438): SoGo 5.3.1 solves the issue - we just have to wait, that this version finally makes it to the mailcow docker container ...

**Comment by MAGICCC** [comment]
Also with sogo 1.104 image

**Comment by abysso2** [comment]
Sorry, i dont get it: i have sogo-mailcow (mailcow/sogo:1.104) installed - this is still 5.3.0 with the bug - why is this thread here closed?

**Comment by MAGICCC** [comment]
Because 1.104 is built on 5.3.0 with nightly builts and I have 2FA now again. Can you recheck?

**Comment by abysso2** [comment]
Ok, now i got it - i had to update the container. Spooky, because ...

[me@mail mailcow-dockerized]# ./update.sh --check
Checking remote code for updates...
No updates available.

But ./update.sh (without --check) pulled a lot of new containers, e.g. mailcow/sogo.

And ... tadaaaaaaaaaaa ... 2fa is back!

The only remaining question: Why hasn`t' the minor-version of the container been changed? Same version but it works now ...


BUUUUUTTTTTT: Thanks a lot for your support!!!!!!!!!!!!!!!!!

Regards,
A.
