### ISSUE TITLE
Password policy - SoGo not working

### ISSUE THREAD

**Issue by pantunes87** [mailcow/mailcow-dockerized#4376]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [*] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [*] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [*] I have understood that answers are voluntary and community-driven, and not commercial support.
- [*] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
The password policy doesn't work in SoGo.

In GUI I have set the policy below (as can see in the image):

- Password length: 9
- Must contain at least one alphabetic character
- Must contain special characters
- Must contain lowercase and uppercase characters
- Must contain at least one number

<img width="826" alt="Screenshot 2021-12-12 at 19 06 34" src="https://user-images.githubusercontent.com/78144692/145726084-63ee0262-7066-4110-afcb-34b5f4871244.png">

In SGo, I change the password to "123456" and was changed with success.

<img width="1341" alt="Screenshot 2021-12-12 at 19 07 46" src="https://user-images.githubusercontent.com/78144692/145726081-cfb732bb-aefe-418d-a5ab-9e541c6f532b.png">

**Comment by MAGICCC** [comment]
You can disable the password change ability in SOGo using `SOGoPasswordChangeEnabled = NO;` in `data/conf/sogo/sogo.conf`

Since SOGo is not fully integrated in mailcow DBs and such that would be the best solution and your users can use their userinterface to change their passwords
