### ISSUE TITLE
Cold standby helper-script uses hardcoded root user for rsync

### ISSUE THREAD

**Issue by bavarialogy** [mailcow/mailcow-dockerized#4378]
## Summary

Using the most recent git (as of 13 Dec 2021), the helper-script for cold standby server creation uses root hard-coded as the user name for the target machine. This may be unwanted due to having to enable SSH root login on the target machine (PermitRootLogin yes). I propose to implement an env variable REMOTE_SSH_USER (maybe defaulting to root if not set) to enable admins to use custom, unprivileged users instead of root.

## Motivation

Improved security and usability in hardened setups without having to run a fork

## Additional context

n/a

**Comment by andryyy** [comment]
How do you expect to map the correct users and file permissions with an unprivileged user exactly?

**Comment by bavarialogy** [comment]
I'd use a dedicated, unprivileged user on the target system (e.g. syncmail), chown /opt/mailcow-dockerized to that user, have the cold standby script do its work (maybe even without intrusive steps like restarting the docker daemon). In case of warming up the cold standby, there would be additional steps to take though. Maybe it'd be better to have an argument "copy-only" so that only data gets transferred in a consistent manner and everything else (restarting dockerd, ensuring fs permissions are correct, image pulling&cleanup) has to be done on the target side? The main goal is to not use root for the transfer.

**Comment by andryyy** [comment]
The script is intended to create a fully working copy on the target without further steps. 

You can probably limit the key file usage on the target. Everything else sounds a bit pseudo secure and overcomplicated. 

You can modify the script for your needs. Shouldn't be too much effort. I will not support it though.

**Comment by shiz0** [comment]
I'd suggest doing something like this, maybe? (Adjust to your needs):
```
Match Address x.x.x.x
    PubkeyAuthentication yes
    PasswordAuthentication yes
    PermitRootLogin yes
```
https://www.cyberciti.biz/faq/match-address-sshd_config-allow-root-loginfrom-one_ip_address-on-linux-unix/
This would prevent opening up remote root logins for everyone without overcomplicating the script/process.

**Comment by bavarialogy** [comment]
Ah, that's some good advice - thanks!
