### ISSUE TITLE
Disable relaying via smtp not working

### ISSUE THREAD

**Issue by regalstreak** [mailcow/mailcow-dockerized#439]
How do i disable relaying? I have disabled it in domains> unchecked relay all domains and relay all recipients. But when i send an email, in postfix logs its still relayed. I have tried restarting several times but it doesnt work. 

CC: @andryyy

**Comment by regalstreak** [comment]
Okay I had to run
`./mailcow-setup-relayhost.sh reset`
But we need to have a better way as this would delete the credentials and the settings for the existing domains.

**Comment by K2rool** [comment]
What relaying are you trying to disable, Relay domain and Relay all recipients is for if you got Mailcow server setup as a backup mx for a domain and relaying the email's to the primary mail server.

mailcow-setup-relayhost.sh control the configuration of a relayhost in Postfix which allows you to send outgoing email via other smtp server helpful if you got ip reputation issues on your mail server ip.

**Comment by regalstreak** [comment]
Aah now i understood. Thanks a lot. I was confused between relay domain and relay all reciepients thing and relayhost. Thanks.

**Comment by regalstreak** [comment]
Also, is there any way to use mailcow-setup-relayhost.sh and setup relaying on multiple domains?

**Comment by mkuron** [comment]
Can now be configured via the web GUI.
