### ISSUE TITLE
Can't login to SOGo after first installation

### ISSUE THREAD

**Issue by 7olstoy** [mailcow/mailcow-dockerized#4391]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [ x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

After first setup your mail domain and first mail you can't login to SOGo with your credentials. After restart services - you can. 
Tried at 3 different domains / servers
 
## Reproduction

1) ```docker-compose up -d``` with your [docs](https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_install/)
2) Login to /mailbox and add new domain
3) Add new mail address with this domain and generated password
4) Go to /SOGo and try to login with credentials which you get from step 3 (you will see wrong password/login error)
5) ```docker-compose down && docker-compose up -d``` and try to login again. Everything will be ok.
## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS|
| Is Apparmor, SELinux or similar active? | not active |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4Gb, 2Cores |
| Docker Version (`docker version`) | 20.10.12, build e91ed57|
| Docker-Compose Version (`docker-compose version`) | 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | not used |

**Comment by MAGICCC** [comment]
The dialog even asks you for restarting the sogo container and you have two buttons to either restart the container or not
```
 The SOGo container, "sogo-mailcow", needs to be restarted after adding a new domain!
```

**Comment by 7olstoy** [comment]
> two buttons to either restart the container or not

Your truth and my friday! 
But the text is not at all obvious to beginners, especially those who do not really understand that the domain is responsible for authorization (not adding mailbox with credentials).
