### ISSUE TITLE
Sogo: Two Factor Authentication not available any more

### ISSUE THREAD

**Issue by Basti-Fantasti** [mailcow/mailcow-dockerized#4395]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
After updating mailcow dockerized the two factor authentication (TOTP) in Sogo is gone.
Actual running SoGo Version **5.3.0**

Even worse is, that a login is now possible without the pre-configured second factor.

## Reproduction
Hard to tell, I just ran the included update script...

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian Bullseye|
| Is Apparmor, SELinux or similar active? | No|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None|
| Server/VM specifications (Memory, CPU Cores) | 1 CPU, 8 Cores, 32GB RAM |
| Docker Version (`docker version`) | 20.10.11|
| Docker-Compose Version (`docker-compose version`) | 1.29.2|
| Reverse proxy (custom solution) | Nginx |

**Comment by andryyy** [comment]
Hey, thanks. But please report it upstream.

**Comment by MAGICCC** [comment]
If you used 5.2.0 before then its normal. SOGo changed private salts and revoked all TFA keys for 5.3.0

**Comment by Basti-Fantasti** [comment]
Yes updating mailcow again and re-enabling the 2FA did the trick. 
It now works again.
