### ISSUE TITLE
Security Exception in Thunderbird with Let's Encrypt

### ISSUE THREAD

**Issue by niklasfyi** [mailcow/mailcow-dockerized#44]
I get an exception for `imap.ro0kie.de:143`. Do I need to add smtp and imap to the certbot script aswell? So they are covered by the certificate.

Thanks

**Comment by andryyy** [comment]
You need to add each name you want to cover. The docs are meant to one-name-for-all-service. :)

**Comment by niklasfyi** [comment]
Okay. But it says:

```
certbot certonly \
        --standalone \
        --standalone-supported-challenges http-01 \
        -d ${MAILCOW_HOSTNAME} \
        -d autodiscover.example.org \
        -d autoconfig.example.org \
        --email you@example.org \
        --agree-tos
```

And `MAILCOW_HOSTNAME` is `mail.ro0kie.de`.

What is this Hostname for? I can also use `ro0kie.de` to get into the admin and mailbox view.

**Comment by andryyy** [comment]
You can just add another `-d imap.domain.tld` to it.

**Comment by niklasfyi** [comment]
Okay I did this and it worked :+1: 

I'll try to figure out the nginx stuff so that I can use `https://ro0kie.de` for something else. Right now it also points to the mailcow login screen

Thanks
