### ISSUE TITLE
Feature suggestion: Rate limiting

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#440]
Hey guys I'm pretty much happy with Mail Cow, so I'd like to ask you about something I find useful to prevent users from abusing.

**How about:** 
"**Mail Sending Limit** per domain" something like hourly rate or daily rate.
"**Incoming Mails** per hours per domain" also not being override by custom white listing already existing in Mail Cow.

**Examples:** 
DOMAIN.TLD: Max Mail Sending per hours cap  =  **300**
DOMAIN.TLD: Max Incoming Mails per hours cap = **1,000** 

What you guys think? and if its possible to implement such feature? TY.

**Comment by mkuron** [comment]
Postfix supports rate limiting, so your suggestion could be added to Mailcow reasonably easy. I don't see a point in limiting incoming emails per hour, but it does make sense to limit outgoing emails per hour to prevent abuse of hijacked accounts.

**Comment by andryyy** [comment]
We have a nice ratelimit feature in Rspamd, too. It can be customized with LUA. Worth a try?

This is a question often asked by commercial hosters to prevent abuse. I thought about doing a good integration, but that's pretty much (unpaid) work for a feature only hosters profit from. :-) I hope I don't sound greedy or arrogant by saying this... But remember this is all free work from _every_ contributor here.

**Comment by alyzrazor** [comment]
haha I get your point @andryyy however if you ever feel bored enough that feature is gonna be awesome :)

**Comment by k0nsl** [comment]
Ratelimiting outgoing e-mails makes sense and is a feature which I wouldn't mind having. I do not use mailcow for commercial purposes, but I do provide e-mail hosting for family, friends and various projects and to keep it nice and cool, it makes sense to ratelimit outoing e-mails (per hour).

**Comment by andryyy** [comment]
I wrote a ratelimit for outgoing mails in LUA. Will test it over the next days.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/28141014-0a68dc96-675b-11e7-800a-ef10ce12145f.png)

Need to implement this for users. But it works as expected.

**Comment by alyzrazor** [comment]
Oh my gooodness @andryyy you did it 🥇 I'm hoping to see it in action soon :)

**Comment by mkuron** [comment]
Has been implemented in the mean time.

**Comment by DJIronic** [comment]
Hello, just a small question about this rate limit. It will just reject to send all the emails posted to SMTP by the client, or it will delay them and send them once the time will be over. I want to enable it to send emails in waves, as the SMTP server is used by our e-shop and we want to eliminate SPAM warnings when sending AGREED newsletters.

Thanks
Simon

**Comment by zeluspudding** [comment]
> ![image](https://user-images.githubusercontent.com/2972950/28141014-0a68dc96-675b-11e7-800a-ef10ce12145f.png)

Where is this UI? I can't seem to find it to save my life, hehe

**Comment by MAGICCC** [comment]
Configuration > Mail setup > Domains/Mailboxes > Edit > Ratelimit

A mailbox rate limit overrides a domain-wide rate limit.
