### ISSUE TITLE
Using Alias in Admin UI for external email addresses

### ISSUE THREAD

**Issue by jonathanmmm** [mailcow/mailcow-dockerized#4406]
Hi,

I read the text that says:
`Please use a sieve filter to redirect mail to an external mailbox (see tab "Filters" or use SOGo -> Forwarder).`
But I don't know why, opened a request in the community forum, but still don't know completely why, as it works.
https://community.mailcow.email/d/1233-external-email-forwarding-why-not-alias/3

If there is a real problem to not use the alias page, I would like to propose a feature request about exactly this feature.
I have multiple email aliases that are send to multiple people, but most of them have no email account.
Creating an email account for every alias email, just because it is send to external email addresses, is a lot of work.

Maybe the alias could recognize if there is an external email and create an email account automatically and putting the emails into the SoGO interface or something?

Using the filters, was not really working and is also not easy (will not be the only person managing the alias lists).
A Mailbox has the advantage that somebody else can manage the list of emails where it is forwarded, but not all will do it.

**Comment by chriscroome** [comment]
I'm not clear why this advice exists, what is the functional difference between an alias and a filter to forward emails, do they result in different headers?

> Creating an email account for every alias email, just because it is send to external email addresses, is a lot of work.

In addition mailboxes requite a quota to be allocated whereas with an alias none is needed as there is no mailbox.

**Comment by sriccio** [comment]
The issue I could see using an alias for external redirects is that you will have no control on relaying SPAM to other servers and your server can then quickly become flagged as a source of SPAM.

AFAIK the aliases are only "blind" mail routing without any filtering rules processing. While it's not a problem when the destination is a local mailbox, it can become an issue for external mailboxes.

Using a local mailbox with forward enabled will let you define what you don't want to forward (for example SPAM) by creating a filter rule to catch them and stop the processing (as the forward rule is added at the very end) and avoid to realy it externally.

If I'm getting it right of course.

**Comment by jonathanmmm** [comment]
@sriccio thanks, do you know if this happens automatically (spam filtering before redirecting)? Could be that pre filter is not doung it, post filter should and SoGo filtering, don't know?!

**Comment by markovendelin** [comment]
Stumbled on this issue. I wonder whether emails to aliases pointing to external email addresses in Mailcow would get delivered or not? In Mailinabox we could define such aliases just fine and they work without a problem, from what I could see.

**Comment by markovendelin** [comment]
Tested and can see that emails are forwarded to outside aliases just fine. As for spam score, that is up to users to decide whether to risk with it or not.
