### ISSUE TITLE
DKIM, SPF and the domains

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#443]
Good morning everybody,

I've got a question to the DNS 

Who gets which listings in the DNS for DKIM, SRV, SPF and _dmarc?

My mailcow-server running under "mail.maildomain.de"
My email-domain is "other.de"

Kind regards
jm3west

**Comment by PhoenixPeca** [comment]
Hi @jm3west!

**It's the latter.** You will need to add the MX ,DKIM, SPF, SRV and DMARC records for every domain you add in mailcow admin web ui. eg.(other.de, example.com, example1.com, ...) for email delivery and domain validation/verification for spam detection. 😉

Have a nice day!

**Comment by mkuron** [comment]
@jm3west, if you are unsure about whether your DNS records are correct and complete, you can try merging #451 into your local repository. This adds a DNS diagnostics page that shows you which records you are currently missing. Note that DNS can have a significant delay (typically up to 24 hours) before the data is shown as up-to-date.

```
git fetch origin pull/451/head
git merge FETCH_HEAD
```

**Comment by jm3west** [comment]
Sorry, I don't understand :-(

the address "mail.maildomain.de" is only the MX and A record.
Under this domain/host isn't no email account in mailcow-ui and in mailcow-ui is only the domain "other.de"

The IP-address is different

My DNS-Setup
The mailserver has the IP "111.222.333.444" with the domain "maildomain.de" and A record
"mail.maildomain.de" and MX record "mail.maildomain.de"

e.g.
vHost-machine 1
maildomail.de          86400 | A | 0 | 111.222.333.444
mail.maildomail.de  86400 | A | 0 | 111.222.333.444
maildomail.de          86400 | MX | 10 | mail.maildomail.de

vHost-machine 2
other.de          86400 | A | 0 | 444.333.222.111
other.de          86400 | MX | 10 | mail.maildomail.de

The vHost-machine 1 (mailserver) need a DKIM, SPF, SRV, ...?

The sender/recipient is only mail@other.de over mailserver "mail.maildomain.de"


Boarr, this is madness

Kind regards
jm3west

**Comment by PhoenixPeca** [comment]
Hi @jm3west,
> The vHost-machine 1 (mailserver) need a DKIM, SPF, SRV, ...?

Yes, you need to add those records for `maildomail.de`. Additionally, if you intend to receive emails in `other.de`, you may need to add those records as well. Please refer to the overview below.

---

As an overview, here's the DNS configuration that you may follow for your setup:
**vHost-machine 1:**
````
# Name                            # Type      # Priority   Weight   Port     # Value
maildomail.de.                    IN A                                       111.222.333.444
mail.maildomail.de.               IN A                                       111.222.333.444
autodiscover.maildomail.de.       IN CNAME                                   mail.maildomail.de.
autoconfig.maildomail.de.         IN CNAME                                   mail.maildomail.de.
@                                 IN MX       10                             mail.maildomail.de.
@                                 IN TXT                                     "v=spf1 mx ~all"
dkim._domainkey.maildomail.de.    IN TXT                                     "v=DKIM1; k=rsa; t=s; s=email; p=..."
_dmarc.maildomail.de.             IN TXT                                     "v=DMARC1; p=reject; rua=mailto:mailauth-reports@maildomail.de"
_imap._tcp.maildomail.de.         IN SRV      0   1   143                    mail.maildomail.de.
_imaps._tcp.maildomail.de.        IN SRV      0   1   993                    mail.maildomail.de.
_pop3._tcp.maildomail.de.         IN SRV      0   1   110                    mail.maildomail.de.
_pop3s._tcp.maildomail.de.        IN SRV      0   1   995                    mail.maildomail.de.
_submission._tcp.maildomail.de.   IN SRV      0   1   587                    mail.maildomail.de.
_smtps._tcp.maildomail.de.        IN SRV      0   1   465                    mail.maildomail.de.
_autodiscover._tcp.maildomail.de. IN SRV      0   1   443                    autodiscover.maildomail.de.
````

**vHost-machine 2:**
````
# Name                            # Type      # Priority   Weight   Port     # Value
other.de.                         IN A                                       444.333.222.111
autodiscover.other.de.            IN CNAME                                   mail.maildomail.de.
autoconfig.other.de.              IN CNAME                                   mail.maildomail.de.
@                                 IN MX       10                             mail.maildomail.de.
@                                 IN TXT                                     "v=spf1 mx ~all"
dkim._domainkey.other.de.         IN TXT                                     "v=DKIM1; k=rsa; t=s; s=email; p=..."
_dmarc.other.de.                  IN TXT                                     "v=DMARC1; p=reject; rua=mailto:mailauth-reports@maildomail.de"
_imap._tcp.other.de.              IN SRV      0   1   143                    mail.maildomail.de.
_imaps._tcp.other.de.             IN SRV      0   1   993                    mail.maildomail.de.
_pop3._tcp.other.de.              IN SRV      0   1   110                    mail.maildomail.de.
_pop3s._tcp.other.de.             IN SRV      0   1   995                    mail.maildomail.de.
_submission._tcp.other.de.        IN SRV      0   1   587                    mail.maildomail.de.
_smtps._tcp.other.de.             IN SRV      0   1   465                    mail.maildomail.de.
_autodiscover._tcp.other.de.      IN SRV      0   1   443                    autodiscover.maildomail.de.
````

😄

**Comment by jm3west** [comment]
OK, thank you very very much!!!

**Comment by PhoenixPeca** [comment]
You're welcome! @jm3west, Just tell me if you're all set so we can close this issue.

**Comment by jm3west** [comment]
OK, I've got a further question.

Must the domain "maildomail.de" in mailcow-ui as domain and must I create a DKIM key for this domain or I need only the DKIM key for "other.de"

**Comment by PhoenixPeca** [comment]
You will need to generate a new dkim key for every domain that you added to mailcow. So every domain must have unique keys of their own.

**Comment by jm3west** [comment]
OK, then not!!!
I use only "other.de" for send and receive
The domain "maildomail.de" isn't in mailcow-ui
Then is DKIM for "maildomail.de" unnecessary. Correctly ?

**Comment by PhoenixPeca** [comment]
That's right.
