### ISSUE TITLE
Release cycle/versioning

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#4434]
Basicly for @DerLinkman and @andryyy

A quick idea from me I shared with @andryyy.

Since we now have our [first GitHub release](https://github.com/mailcow/mailcow-dockerized/releases/tag/major-release) we can somewhat release every month(?) with a tag like Docker does (YY.MM).
Also we can use [Milestones](https://github.com/mailcow/mailcow-dockerized/milestones) and since some users already asked us to implent a small hint in the Web UI which version they are on we can do it too.
https://github.com/mailcow/mailcow-dockerized/issues/2902
https://github.com/mailcow/mailcow-dockerized/issues/971
https://github.com/mailcow/mailcow-dockerized/issues/340

**Comment by DerLinkman** [comment]
Good idea! Especially the one with the versioning in the Mail UI.

Would that pack directly on the login screen? Or what do you think?

The versioning MM-YYYY also sounds reasonable.

**Comment by DerLinkman** [comment]
You mean a Versioning (example for the next release):

2022.02? And if a hotfix Update is needed would I suggest then 2022.02a <-- the letter would be the number of the hotfix.

**Comment by MAGICCC** [comment]
> Would that pack directly on the login screen? Or what do you think?

Optionally yes. I am sure some users don't want to show their version in public for security reasons. When logged in as admin then maybe in the footer somewhere

> The versioning MM-YYYY also sounds reasonable.

Yes, as long as its clear we can also use this type.

 
> 2022.02? And if a hotfix Update is needed would I suggest then 2022.02a <-- the letter would be the number of the hotfix.

Yes looks fine with appending a letter

**Comment by DerLinkman** [comment]
> Optionally yes. I am sure some users don't want to show their version in public for security reasons. When logged in as admin then maybe in the footer somewhere

Yes true, in the footer (after the login screen) sounds even better actually :)

**Comment by waja** [comment]
> 2022.02? And if a hotfix Update is needed would I suggest then 2022.02a <-- the letter would be the number of the hotfix.

or just "2022.02-1" or "2022.02.1". Hotfix number can be just incremented. For more inspiration, have look into https://semver.org/

**Comment by jpbaril** [comment]
Will the update script allow us to choose to which release/tag/commit we want to update to?

**Comment by DerLinkman** [comment]
> Will the update script allow us to choose to which release/tag/commit we want to update to?

No (at least not now). It will ever use the latest release on the GitHub Page.

The reason we don't enable this is that there may be potential problems with the containers as they go up and down with the version.

**Comment by jpbaril** [comment]
> It will ever use the latest release on the GitHub Page

So the "releases" are more a reference to indicate what was the state of mailcow at some point, as opposed to identify "stable" builds?

**Comment by DerLinkman** [comment]
> > It will ever use the latest release on the GitHub Page
> 
> So the "releases" are more a reference to indicate what was the state of mailcow at some point, as opposed to identify "stable" builds?

Half yes, half no. So far, we've just pushed all commits/pull requests directly into the master branch. Since many (including us) wished for versioning in order to recognize whether there is something new, we have this active since January. We are aiming for a monthly release.

Occasionally there'll be minor bugfix updates in the form of the formats above (2022-01a for example)

**Comment by MAGICCC** [comment]
Since we use now YYYY-MM + a prefix letter for (hot)fixes and https://github.com/mailcow/mailcow-dockerized/pull/4437 is merged I'll close this
