### ISSUE TITLE
SOGo tags keep showing after deletion

### ISSUE THREAD

**Issue by blaluc** [mailcow/mailcow-dockerized#4435]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

If you add tags to an email and then remove the tags or even if you completely delete each tagged email, the search filter keeps showing the deleted tags. 

![image](https://user-images.githubusercontent.com/4599417/150801986-aa0337ee-dcd4-40b2-b592-69c2e36b3112.png)

It seems to be the call to ```folderINBOX/labels``` API.

I didn't catch to see where these custom tags are stored (I searched in both MySQL ad Redis with no luck).

I'm pretty sure that the problem is releated to SOGo but since the SOGo team is unreachable and there's no way to submit them an issue, I'm opening the issue here hoping you can address this problem that, in a way, affects also mailcow.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.0.4|
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** |KVM |
| Server/VM specifications (Memory, CPU Cores) | i9, 16GB, 8cores |
| Docker Version (`docker version`) | latest |
| Docker-Compose Version (`docker-compose version`) | latest|
| Reverse proxy (custom solution) | none |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by blaluc** [comment]
after investigating seems to be a problem related to dovecot and how manage the dovecot-keyword file

**Comment by blaluc** [comment]
After investigating it seems to be a problem related to dovecot and how manage the dovecot-keyword file

**Comment by japinto1** [comment]
hello @blaluc, I'm having this very same issue. Were you able to resolve it?

**Comment by Mulder42** [comment]
Why is this bug marked as fixed / closed, even though the problem still exists? There's also no easy solution to be found on Google, and this bug report ranks very high on Google. So it would make sense and be helpful to paste a solution to the problem here!

**Comment by mickenorlen** [comment]
This seems to be related to a stale dovecot index. I'm using docker-mailserver and managed to refresh my labels by forcing a rebuild.

```bash
# First find the right folder path to dovecot.index of the affected account. 
# Then see if you find any mention of your stale label
doveadm dump /var/mail/your.domain/your_user/dovecot.index | grep -i my_label
# These are basically file cache files that supposedly are fine to delete. I'm no expert. 
# After deleting them they rebuilt instantly and my labels were refreshed
find /var/mail/your.domain/your_user/ -name "dovecot.index*" -delete
```

**Comment by Mulder42** [comment]
@mickenorlen Thanks, sounds interesting, but also like a workaround.

If this is working, shouldn't it be done automatically by Mailcow and / or SOGo? Can't be that complicated and as mentioned, users are talking about this issue for years already, without it being solved.

**Comment by Mulder42** [comment]
This bug is still unsolved.

Furthermore, tags are frequently assigned wrongly, even if filters (incl. tag assignations) are defined correctly.
