### ISSUE TITLE
SOGO Image (cron): run update-autoreply every 5 minutes 

### ISSUE THREAD

**Issue by jmber** [mailcow/mailcow-dockerized#4436]
See SOGO commit:
[(cron): run update-autoreply every 5 minutes ](https://github.com/inverse-inc/sogo/commit/e8d7faf6f4ddca19469c2cd2851f0000bc62fddd)

**Comment by DerLinkman** [comment]
Hi, is this solved in a nightly build?

So if we rebuild the image it is solved?

**Comment by DerLinkman** [comment]
Nevermind. It is already in the current mailcow version.

Do you have problems with that? If so, what is the problem?

**Comment by jmber** [comment]
Hi, i checked the actual image of mailcow/sogo:

/etc/crond/sogo:
`* * * * *   sogo   /usr/sbin/sogo-ealarms-notify 2>/dev/null
* * * * *   sogo   /usr/sbin/sogo-tool expire-sessions 60
0 0 * * *   sogo   /usr/sbin/sogo-tool update-autoreply -p /etc/sogo/sieve.creds`

**Comment by jmber** [comment]
Sorry, but now i understand the way, how the cron jobs of sogo are done:
[compose.yml Line 203-204](https://github.com/mailcow/mailcow-dockerized/blob/5a1ef72b8225837d63aa668beb421503c5a30b44/docker-compose.yml#L203-L204)

So i think you have to change here the cronjob from 24h to every 5 min

**Comment by DerLinkman** [comment]
Will merge it into the 2022-01a Patch, which will be released soon.

**Comment by DerLinkman** [comment]
Is merged now. Thanks for the reminder.
