### ISSUE TITLE
SOGo: Web UI - Different colors for multiple calendard

### ISSUE THREAD

**Issue by mr-manuel** [mailcow/mailcow-dockerized#4444]
## Summary

I would love to be able to set a color for every single calendar in the SOGo Web UI like in the Windows Mail Client, Microsoft Outlook, Android Calendar, iOS Calendar, ...
This would help to understand which event is from which calendar, if you are displaying multiple calendars at once.

I'm not sure if this is the right place to post this, but I found no possibility to create a FR directly in the SOGo repository. If someone know the right way, please let me know.

## Motivation

It would be much clearer which event is from which calendar, when you only use the Web UI.

## Additional context

SOGo Web UI

![grafik](https://user-images.githubusercontent.com/12592765/151970514-a329dfb6-5d03-4f9a-8b22-492eb184eb04.png)

Windows Calendar

![grafik](https://user-images.githubusercontent.com/12592765/151970544-155aa37b-ea0c-44cf-b651-f12c8123d187.png)

## Not requested

This request is not for syncing calendar colors like https://github.com/mailcow/mailcow-dockerized/issues/2501

**Comment by mthld** [comment]
Wrong place for this request, Mailcow doesn't develop SOGo, check https://sogo.nu

**Comment by ghost** [comment]
You can already set a a specific color on calendars. But GitHub isn't a place to get support, it's not a bug.

**Comment by mr-manuel** [comment]
So can you also tell me where I can set the color if you know it already?

**Comment by SkanderHelali** [comment]
> So can you also tell me where I can set the color if you know it already?

<img src="https://user-images.githubusercontent.com/2225618/151987203-8e228d54-3c4e-433c-a1dd-9de030af68e9.png" width="400">
<img src="https://user-images.githubusercontent.com/2225618/151987237-a294343b-1d00-4e5f-8747-8eac4dad39b2.png" width="400">
<img src="https://user-images.githubusercontent.com/2225618/151987253-acf45ef8-b574-40f1-9c02-969e8ceb172b.png" width="400">
<img src="https://user-images.githubusercontent.com/2225618/151987274-9359cbc1-46f9-415f-a946-348958051453.png" width="400">

**Comment by mr-manuel** [comment]
Thanks... I searched for a the word color

**Comment by calvinrw** [comment]
> You can already set a a specific color on calendars. But GitHub isn't a place to get support, it's not a bug.

Maybe not a bug per se, but I do believe there's an issue with the UI. Like @mr-manuel, I couldn't figure out how to change the color without searching online and ending up in this thread. The button to bring up the color picker is very subtle, especially with the default theme colors. I'd argue the picker button should be in the main area of the calendar properties window, and not in the titlebar.

**Comment by kostrzewa** [comment]
>  I'd argue the picker button should be in the main area of the calendar properties window, and not in the titlebar.

+1
