### ISSUE TITLE
Mailcow does not work UNLESS disabling IPv6

### ISSUE THREAD

**Issue by Hukuma1** [mailcow/mailcow-dockerized#4447]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

I get these errors with the default install of mailcow-dockerized. I need to follow the directions from https://mailcow.github.io/mailcow-dockerized-docs/firststeps-disable_ipv6/ to be able to use it. The WebUI loads and I can click around and save some configs, but it fails in the background on the majority of stuff. If I disable IPv6 as per the guide, mailcow works flawlessly.

I believe IPv6 is blank/disabled on my host machine, as well as my router. Right now I don't mind making the `docker-compose.override.yml`, but I'm afraid the other 3 changes I have to make in other files will be lost upon any future updates to mailcow, right?

## Logs

```
watchdog-mailcow_1   | Wed Feb 2 20:44:43 PST 2022 Dovecot health level: 0% (0/12), health trend: -10
watchdog-mailcow_1   | Wed Feb 2 20:44:44 PST 2022 Dovecot hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000183s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000168s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | Wed Feb 2 20:44:54 PST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Wed Feb 2 20:44:54 PST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:44:54 PST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:44:54 PST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:44:54 PST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Wed Feb 2 20:44:59 PST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:00 PST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:01 PST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:08 PST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:12 PST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:14 PST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:18 PST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:18 PST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:19 PST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:19 PST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Feb 2 20:45:22 PST 2022 Postfix health level: 25% (2/8), health trend: -3
watchdog-mailcow_1   | Wed Feb 2 20:45:31 PST 2022 Olefy health level: 100% (5/5), health trend: 0
```

I'm able to login to SOGO WebUI, but it errors out when trying to show mailbox, etc.
```
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 sogod [69]: [ERROR] <0x0x560d57e601c0[NGImap4ConnectionManager]> IMAP4 login failed:
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 host=172.22.1.250, user=USER@MYDOMAIN.COM, pwd=yes
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 url=imap://USER%40MYDOMAIN.COM@172.22.1.250/?tls=NO&tlsVerifyMode=none
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 base=(null)
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 base-class=(null))
sogo-mailcow_1       | Feb  2 20:49:44 816ea9677ab8 = <0x0x560d57ea4370[NGImap4Client]: login=USER@MYDOMAIN.COM(pwd) address=<0x0x560d57ea4b10[NGInternetSocketAddress]: host=172.22.1.250 port=143>>Feb 02 20:49:44 sogod [71]: [ERROR] <0x0x560d581ce530[NGImap4ConnectionManager]> IMAP4 login failed:
```

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 11
| Is Apparmor, SELinux or similar active? | Apparmor (Debian 11 default install)
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM
| Server/VM specifications (Memory, CPU Cores) | 6GB, 2 core
| Docker Version (`docker version`) | 20.10.12
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | NGinx Proxy Manager |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

Should I post the `iptables` from my host machine? The ones in the VM where mailcow is running are untouched.

**Comment by blacksocket** [comment]
I am having the same issue with Ubuntu 18.04 LTS even after disabling IPv6.

**Comment by blacksocket** [comment]
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Clamd health level: 87% (13/15), health trend: -2
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Postfix health level: 50% (4/8), health trend: -4
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Primary certificate expiry check health level: 43% (3/7), health trend: -4
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:01 CEST 2022 Unbound health level: 40% (2/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:11:11 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:26 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:27 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:33 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:41 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:43 CEST 2022 Postfix health level: 13% (1/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 Dovecot health level: 0% (0/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:11:48 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:48 CEST 2022 Dovecot hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.001 sec. response time|time=0.001260s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000084s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:12:00 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:01 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:05 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:06 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:09 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:09 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:13 CEST 2022 Unbound health level: 0% (0/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Clamd health level: 73% (11/15), health trend: -2
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Unbound hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:25 CEST 2022 Postfix health level: 0% (0/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:26 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:26 CEST 2022 Postfix hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.253 and port 589: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000123s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.253 and port 589: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000046s;;;0.000000
watchdog-mailcow_1   | SMTP OK - 0.048 sec. response time|time=0.047927s;;;0.000000
watchdog-mailcow_1   | SMTP UNKNOWN - Cannot read EHLO response via TLS.
watchdog-mailcow_1   | SMTP OK - 0.029 sec. response time|time=0.028536s;;;0.000000
watchdog-mailcow_1   | SMTP UNKNOWN - Cannot read EHLO response via TLS.
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:37 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:37 CEST 2022 Postfix health level: 63% (5/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:38 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:46 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:50 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:51 CEST 2022 Unbound health level: 40% (2/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:01 CEST 2022 Dovecot health level: 0% (0/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:13:02 CEST 2022 Dovecot hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.001 sec. response time|time=0.001260s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000084s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000082s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000064s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:13:22 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:23 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:30 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:34 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:39 CEST 2022 Postfix health level: 25% (2/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:41 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:45 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:47 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:53 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:53 CEST 2022 Unbound health level: 0% (0/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:54 CEST 2022 Unbound hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498851] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:9f::42 port 53
unbound-mailcow_1    | [1649498851] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:dc3::35 port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:a8::e port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:dc3::35 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%

**Comment by Hukuma1** [comment]
Upgraded to May 2022 update and it seems to work for me? Not sure if this was fixed in the April update or May, but I don't need any `docker-compose-override.yml` tasks anymore and it works out-of-the-box.
