### ISSUE TITLE
doveadm import over ssh

### ISSUE THREAD

**Issue by cklabautermann** [mailcow/mailcow-dockerized#445]
First of all I´d like to thank for the great work! I would love to import my actual dovecot via doveadm into mailcow. unfortunately I´m no docker guru and it seems to me that the dovecot container misses ssh, so I can´t import the mail accounts from the remote server.

Can you give me a hint how to achieve this?

what I have tried until now:
`docker-compose exec dovecot-mailcow doveadm sync -u user@host.tld ssh root@<remote_ip> doveadm dsync-server -u user@host.tld`
Here the error is Fatal: execvp(ssh) failed: No such file or directory
and
`docker-compose exec dovecot-mailcow doveadm sync -u user@host.tld remote:<remote_ip`
Here the error is the same as above:

Thanks in advance
Claudio

**Comment by falkzilm** [comment]
This is because "ssh" is not installed in this container environment - i encountered the same problem. I started a Bash Shell via https://mailcow.github.io/mailcow-dockerized-docs/debug-attach_service/ and installed manually via apt-get openssh-client.

But somehow i cannot sync my dovecot accounts either :/

**Comment by andryyy** [comment]
Hi, are you able to use Doveadms TCP interface? You would need to enable the doveadm listener like this (on the remote site):

```
service doveadm {
  inet_listener {
    port = 19998 # or whatever
  }
}
```

Add a shared secret to both sites (same password):

```
doveadm_password = shared-secret-on-both-sides-identical
```

The run `docker-compose exec dovecot-mailcow doveadm sync -u user@host.tld tcp:remote-ip:19998`

**Comment by cklabautermann** [comment]
Hi,

thanks for this information – that did it for me ☺!

I added exactly

service doveadm {
  inet_listener {
    port = 19998
  }
}
doveadm_password = shared-secret-on-both-sides-identical



and afterwards was able to sync mailboxes from one server to another without need of ssh:


docker-compose exec dovecot-mailcow doveadm sync -u user@domain.tld tcp:<remote_ip>:19998

Great work – again many thanks for it!

Best regards
Claudio

**Comment by cklabautermann** [comment]
sorry, another reply - now via github. Only this way I can close the issue :-)
