### ISSUE TITLE
Login to SoGo not possible with app passwords

### ISSUE THREAD

**Issue by MrKrisKrisu** [mailcow/mailcow-dockerized#4452]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
It is not possible for me to log into SoGo with app passwords. The main password works.
The error message is simply `Wrong username or password.`.

## Logs
_not useful for this issue_

## Reproduction

1. Login as enduser
2. Create App password (with all protocols allowed)
3. Try to login to SoGo with this Password
4. `Wrong username or password.`

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS |
| Is Apparmor, SELinux or similar active? | nope |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | - |
| Server/VM specifications (Memory, CPU Cores) | - |
| Docker Version (`docker version`) | Docker Engine - Community 20.10.11 |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | traefik |

- Output of `git diff origin/master`, any other changes to the code? -> nope

**Comment by mkuron** [comment]
That's actually intentional. You can't log into the mailcow UI either. As the app passwords page says:

> App passwords are alternative passwords for your IMAP, SMTP, CalDAV, CardDAV and EAS login. The username remains unchanged. SOGo webmail is not available through app passwords.
