### ISSUE TITLE
DNS challage fore certs

### ISSUE THREAD

**Issue by kc2vrj** [mailcow/mailcow-dockerized#4454]
I run behind a reverse proxy how can i use a dns challage or manually add certs to mailcow?

**Comment by MAGICCC** [comment]
See here: https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-ssl/#how-to-use-your-own-certificate

Also for support you can ither ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

**Comment by kc2vrj** [comment]
thank you sir i was about to close this and found you did as my goolge skills were lacking
