### ISSUE TITLE
"Show configuration guides for email clients and smartphones" link 404 

### ISSUE THREAD

**Issue by omueller** [mailcow/mailcow-dockerized#4459]
Hi, just a small but still important thing: I just noticed this after setting up a new mailcow installation: 

Clicking on the "Show configuration guides for email clients and smartphones" Link sends the user to:
https://mailcow.github.io/mailcow-dockerized-docs/client/#host=mailbox.example.org&email=test%40example.org&name=test&ui=mailbox.example.org&port=443  -> 404. 

It seems it should send the user to:  (.../client/client/...) to make it work. 
https://mailcow.github.io/mailcow-dockerized-docs/client/client/#host=mailbox.example.org&email=test%40example.org&name=test&ui=mailbox.example.org&port=443

Most probably this is something that could/should be fixed on the _mailcow.github.io_ host ?   I tested this with Safari/Opera/Firefox/Chrome under OS X. 

Otherwise and as usual, everything is working as expected, even with a 10/10 under www.mail-tester.com just a few minutes after setup. Great work!  

Best regards, Olivier

**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Fresh mailcow install (Version: 2022-01a), test account created, clicked on the **[Show configuration guides for email clients and smartphones]** link as user -> 404. 

## Logs

No log (Client-Side, 404 in browser).  

## Reproduction

Setup new mailcow with default settings and one mail-domain including all required DNS entries, create test user, login as user, go to the /user page, click on the "Show configuration guides for email clients and smartphones" link. 

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu LTS 20.04 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 16GB RAM, 6vCPU |
| Docker Version (`docker version`) | 20.10.12 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | n/a |

**Comment by MAGICCC** [comment]
Yep, fixed in https://github.com/mailcow/mailcow-dockerized/pull/4458

Will be available in the next release

**Comment by omueller** [comment]
Perfect, thanks a lot @MAGICCC, and I really checked previous *issues*, but not PRs.  Will do next time of course :).
