### ISSUE TITLE
POP server does not work

### ISSUE THREAD

**Issue by shirobachi** [mailcow/mailcow-dockerized#4473]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*

- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

After installation all work fine, including connecting via IMAP (on some app for android), but when I try to let Gmail importing my mail via POP (because by my knowledge IMAP is not supported by Google) it says that login and/or password is/are wrong. 
Indeed, password is correct, I am sure that because:

1. I let Gmail send mails as and same password worked just fine.
2. I reset password to be sure

According to the [documentation,](https://mailcow.github.io/mailcow-dockerized-docs/client/client-manual/) POP port is 110/995 and I for those Gmail say that sth is wrong. ([Screenshot](https://i.imgur.com/IMvfxh7.png))

I would like to see on Gmail all my mails, I think that POP protocol should work just fine. 
The mail has POP protocol turned on: https://i.imgur.com/AT6tfK9.png
But was never used: https://i.imgur.com/iGW6zgH.png

## Logs
Please have a look [here](https://pastebin.com/Nteenxb6) there was so much lines so that why is's on pastebin.

## System information

| Question                                                                               | Answer                                 |
| -------------------------------------------------------------------------------------- | -------------------------------------- |
| My operating system                                                                    | Ubutnu 20.04 LTS                       |
| Is Apparmor, SELinux or similar active?                                                | No                                     |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | N/A                                    |
| Server/VM specifications (Memory, CPU Cores)                                           | memory: 2G+0, cores: 1                 |
| Docker Version (`docker version`)                                                      | 20.10.12, build e91ed57                |
| Docker-Compose Version (`docker-compose version`)                                      | 1.29.2, build 5becea4c                 |
| Reverse proxy (custom solution)                                                        | Yes, 8080 -> 80, 8443 -> 443 via nginx |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
  
  Those two certs: **a/data/assets/ssl-example/cert.pem** and **a/data/assets/ssl-example/key.pem** and
  
  ```shell
  diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
  index a445b60c..536bd524 100644
  --- a/data/conf/postfix/main.cf
  +++ b/data/conf/postfix/main.cf
  @@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
  
   # DO NOT EDIT ANYTHING BELOW #
   # User overrides #
  +
  +myhostname = mail.hryszko.dev
  +
  ```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
  
  **iptable has not been touched, firewall like following**
  
  ![](https://i.imgur.com/WlDYDfA.png)

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
  **N/A**

**Comment by ValdikSS** [comment]
Works fine for me. Just tested with close-to-stock settings. Check your configuration/firewall. Also if you host your server on some kind of cloud hosting, check its firewall.

**Comment by shirobachi** [comment]
Can you provide your firewall settings? I think that mine is fine I use hetzner
![image](https://user-images.githubusercontent.com/16509749/154699133-63f3ea14-c7b4-481e-bf93-1174fe635638.png)

**Comment by ValdikSS** [comment]
I don't have any specific firewall settings. At first I thought that gmail may not support TLS 1.1, but no, it works just fine with stock mailcow configuration.


Wait, you don't have port 995 in your firewall settings opened, according to your screenshot. Use port 995 with "always use a secure connection (SSL)" checkbox in gmail settings.

**Comment by shirobachi** [comment]
You are right
1. I added port 995 to hetzner's firewall
2. Added mail to gmail with port 995 and SSL checked

Thanks a lot <3
