### ISSUE TITLE
User password change

### ISSUE THREAD

**Issue by DrTrills** [mailcow/mailcow-dockerized#448]
Hi all, again thank you for such a wonderful project. The deeper I get into it the more excited I am to be implementing it. Great community so far!

I have a question regarding user passwords, how do I enable this for users to change their own PW?

I found this for roundcube https://github.com/mailcow/mailcow/wiki/Configuring-Roundcube-Mailbox-Password-change

Any tips for SOGo on the dockerized version?

Also, wanted to report that things work perfectly on Debian 9 and don't require any kernel changes as mentioned in Deb 8.

Thank you

**Comment by janxb** [comment]
Users can change their passwords in the mailcow webinterface. Just log in with your email and current password. SOGo can change the user passwords through LDAP or in the database too, but mailcow uses a readonly database view for SOGo, so directly changing it in SOGo is currently not supported.

**Comment by DrTrills** [comment]
Awesome thank you!

**Comment by measwel** [comment]
I keep getting authentication errors from dovecot and postfix in mailcow-dockerized:
`pop3-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<marek@mymail.com>, method=PLAIN, rip=184.73.218.144, lip=172.22.1.3, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)`

Can somebody help me please diagnose the problem?
