### ISSUE TITLE
Remove political banner

### ISSUE THREAD

**Issue by nrdsp** [mailcow/mailcow-dockerized#4508]
### Summary

There is a banner stating that the project stands for Ukraine in the readme file. Either we start putting banners for every war there is in the world right now and in the future, or it may be understood as ideological and political capture.

### Motivation

The banner is uncalled for as it politicizes the project, polarizing current and potential community members and users.

**Comment by tkorves** [comment]
This is not, in any way, any ideological or political capture. It's a war, directly in our neigborhood - and if the team thinks, they should send a protest note this way, it's totally fine.

If you find yourself polarized by this, it's not intended - but I wouldn't remove it at all to make the world aware of this warcrime comitted by Russia / Putin.
