### ISSUE TITLE
Change Some expression that not contribute with inclusive language or antiracist language

### ISSUE THREAD

**Issue by nikolehn** [mailcow/mailcow-dockerized#4524]
### Summary

Hi community!

In the view Spam Filter when you are editing a domain.

change words 
White List for Enabled
Black List for Disabled

In Spanish 
Lista Blanca: Habilitada
Lista Negra:  Deshabilitada

![Captura de pantalla de 2022-03-25 20-23-59](https://user-images.githubusercontent.com/8575947/160221444-a23d7158-2617-4c12-b10b-e1293b2feead.png)

![Captura de pantalla de 2022-03-25 20-22-02](https://user-images.githubusercontent.com/8575947/160221452-d53d1ac0-19ed-4b92-baa0-e89ee4207ea2.png)

### Motivation

contribute to a non-racist language

**Comment by ghost** [comment]
I fear Mailcow maintainers aren't really sensitive to this, but maybe if you prepare a pull request with the newly translated strings it has better chances?

**Comment by MAGICCC** [comment]
Dupe of https://github.com/mailcow/mailcow-dockerized/issues/3155

Also Enabled and Disabled (which btw is also a 'racist' word against disabled people) doesn't fit at all.
