### ISSUE TITLE
can not log into sogo after april update

### ISSUE THREAD

**Issue by badsmoke** [mailcow/mailcow-dockerized#4537]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

after the update I can no longer log in via sogo.

imap/smtp goes like before

`Unbehandelte Fehlerantwort`

### Logs

```bash
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  06/Apr/2022:08:23:30 +0200 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [06/Apr/2022:08:23:30 +0200] "GET /sogo-auth HTTP/1.0" 200 0 "https://webmail.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
sogo-mailcow_1       | Apr  6 08:23:30 a2af9ce8daa0 sogod [63]: SOGoRootPage successful login from 'MASKED_IP' for user 'admin@domain.tld' - expire = -1  grace = -1
sogo-mailcow_1       | Apr  6 08:23:30 a2af9ce8daa0 sogod [63]: MASKED_IP "POST /SOGo/connect HTTP/1.0" 200 43/94 0.286 - - 0 - 14
nginx-mailcow_1      | MASKED_IP - - [06/Apr/2022:08:23:30 +0200] "POST /SOGo/connect HTTP/1.0" 200 43 "https://webmail.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
```

### Steps to reproduce

1. install april update
2. login in sogo
3. `Unbehandelte Fehlerantwort`

### System information

| Question | Answer |
| --- | --- |
| My operating system | ubuntu 20.04  |
| Is Apparmor, SELinux or similar active? | default |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | no |
| Server/VM specifications (Memory, CPU Cores) | 8 cores, 16gb |
| Docker Version (`docker version`) | 20.10.13 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | nginx/swag |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
YOUR OUTPUT GOES HERE
```

**Comment by qupfer** [comment]
Hi, I can confirm this. 
Also coudn't find any information from the logs 

```
nginx-mailcow_1      | 127.0.0.1 - - [06/Apr/2022:09:52:24 +0200] "GET /sogo-auth HTTP/1.0" 200 0 "https://mail.server.de/" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
sogo-mailcow_1       | Apr  6 09:52:24 db96c9d0dff9 sogod [77]: SOGoRootPage successful login from '2a02:810a:bc0:2ea:1e0d:b992:64a2:477d' for user 'info@mydomain.de' - expire = -1  grace = -1
nginx-mailcow_1      | 2a02:810a:bc0:2ea:1e0d:b992:64a2:477d - - [06/Apr/2022:09:52:24 +0200] "POST /SOGo/connect HTTP/1.0" 200 50 "https://mail.server.de/" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
sogo-mailcow_1       | Apr  6 09:52:24 db96c9d0dff9 sogod [77]: 2a02:810a:bc0:2ea:1e0d:b992:64a2:477d "POST /SOGo/connect HTTP/1.0" 200 50/95 0.222 - - 0 - 13
watchdog-mailcow_1   | Wed Apr 6 09:52:26 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
rspamd-mailcow_1     | 2022-04-06 09:52:27 #41(controller) <a079ee>; csession; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 3222 regexps total, 2424 regexps cached, 0B scanned using pcre, 102B scanned total
watchdog-mailcow_1   | Wed Apr 6 09:52:27 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Apr 6 09:52:27 CEST 2022 Redis health level: 100% (5/5), health trend: 0
dovecot-mailcow_1    | Apr  6 09:52:27 caadac67806c dovecot: imap-login: Login: user=<other@other.de>, method=PLAIN, rip=77.21.209.57, lip=172.22.1.250, mpid=360, TLS, TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
dovecot-mailcow_1    | Apr  6 09:52:27 caadac67806c dovecot: imap(other@other.de)<360><OdWKpPfbFuZNFdE5>: Disconnected: Logged out in=45 out=974 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
watchdog-mailcow_1   | Wed Apr 6 09:52:31 CEST 2022 Postfix health level: 100% (8/8), health trend: 0
redis-mailcow_1      | 1:M 06 Apr 2022 09:52:32.063 * 100 changes in 300 seconds. Saving...
redis-mailcow_1      | 1:M 06 Apr 2022 09:52:32.099 * Background saving started by pid 14
```

**Comment by cajus** [comment]
Same here. That's what I see in my nginx reverse proxy:

```
2022/04/06 12:15:09 [error] 502963#502963: *1 upstream sent too big header while reading response header from upstream, client: 188.192.42.39, server: webmail.mymailcow.net, request: "POST /SOGo/connect HTTP/2.0", upstream: "http://127.0.0.1:8080/SOGo/connect", host: "webmail.mymailcow.net", referrer: "https://webmail.mymailcow.net/"
```

**Comment by chriscroome** [comment]
Perhaps a fix [like this](https://stackoverflow.com/a/25762701) is needed?

**Comment by cajus** [comment]
Already tried this one, but the message doesn't go away.

**Comment by soulsymphonies** [comment]
It is probably because you are using a reverse proxy in front of mailcow, as I do, in my example nginx

like this here: https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-rp/#nginx

Because of the changes in SoGo 5.5.1 and in the configuration in the nginx mailcow container, you have to increase the proxy buffer size in your reverse proxy also, or you can't log into SoGo anymore

The Active Sync location directive has to be changed:
You need to replace `proxy_buffers 64 256k;` with `proxy_buffers 64 512k;`

```
location /Microsoft-Server-ActiveSync {
    proxy_pass http://127.0.0.1:8080/Microsoft-Server-ActiveSync;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 75;
    proxy_send_timeout 3650;
    proxy_read_timeout 3650;
    proxy_buffers 64 512k;
    client_body_buffer_size 512k;
    client_max_body_size 0;
  }
```

You also need to add the following to the root location directive
```
proxy_buffer_size 128k;
proxy_buffers 64 512k;
proxy_busy_buffers_size 512k;
```

It looks like this then:
Note: I use port 8080 for my nginx container, yours may be different

```
  location / {
    proxy_pass http://127.0.0.1:8080/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 0;
    proxy_buffer_size 128k;
    proxy_buffers 64 512k;
    proxy_busy_buffers_size 512k;
  }
```

took me a while to figure this out, hope it helps ;)

after these changes it worked for me

**Comment by cajus** [comment]
@soulsymphonies hehe - turned out that I placed it in the config when trying it, but forgot that I added an additional domain for sogo itself. Which in turn didn't have the proxy_buffer adjustments. After I added them additionally at this place, it works again. Thanks for making me look again ;-)

**Comment by badsmoke** [comment]
thanks ist works also for me

**Comment by MAGICCC** [comment]
I merged the docs PR https://github.com/mailcow/mailcow-dockerized-docs/pull/390

**Comment by tome9111991** [comment]
not working for me.
any idea?

ok solved.
i use sogo with a subdomain
this will fix

```
location /SOGo {
    proxy_pass http://127.0.0.1:8080/SOGo;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 0;
    proxy_buffer_size 128k;
    proxy_buffers 64 512k;
    proxy_busy_buffers_size 512k;
    }
```

thanks

**Comment by ghost** [comment]
I have the same problem, but all the workarounds don't work. I'm using mailcow with traefik (yes i know why don't use the buildin ingress but i love traefik) all is working but after the latest update sogo produces this fault, any solution/hints much appreciated


--update--

So i discussed this issue with my coworker and he told me that i have to look into stripping the headers in traefik or in nginx.
Had no time or energy to test this out......
I will spin up another instance to test this out and share the results.

**Comment by wombiegit** [comment]
Since changing NPM advanced NGINX config didn't work for me, I had to do the following in my NPM machine:

docker exec into NPM container
vim /data/nginx/proxy_host/THE_PROXY_HOST_ID_SHOWN_IN_NPM_WEB_PAGE
add the above with exceptions:

```
  location / {
    client_max_body_size 0;
    proxy_buffer_size 128k;
    proxy_buffers 64 512k;
    proxy_busy_buffers_size 512k;
```

then still inside - nginx -s reload

**Comment by SuperGaleb** [comment]
I also had same problem. Added in NPM Advanced:

proxy_buffer_size 128k;
proxy_buffers 64 512k;
proxy_busy_buffers_size 512k;

It all works fine now.

**Comment by robert-hedler** [comment]
worked for me thanks man

**Comment by muelleraschheim** [comment]
> I also had same problem. Added in NPM Advanced:
> 
> proxy_buffer_size 128k; proxy_buffers 64 512k; proxy_busy_buffers_size 512k;
> 
> It all works fine now.

Did it for me too in NginxProxyManager - Thanks a lot!

**Comment by natmac21007** [comment]
@soulsymphonies I have this issue, but I'm not sure where I should be making these edits? Sorry total noob to docker, mailcow, nginx and homelabs.

**Comment by soulsymphonies** [comment]
@natmac27001: the changes have to be made in your nginx reverse proxy configuration. The configuration normally is found either  under /etc/nginx/conf.d/your-site.conf or under /etc/nginx/sites-enabled/your-site on the machine where you run your reverse proxy

your-site.conf is just a generic name and will have a unique name

Se nt from MailDroid

-----Original Message-----

**Comment by alienfrenZyNo1** [comment]
> I also had same problem. Added in NPM Advanced:
> 
> proxy_buffer_size 128k; proxy_buffers 64 512k; proxy_busy_buffers_size 512k;
> 
> It all works fine now.

Thanks so much! Using Nginx Proxy Manager and this was it.

**Comment by socketpair** [comment]
Please explain how buffer size influence ability to login?

**Comment by ArchMatt-GraveKeeper** [comment]
> It is probably because you are using a reverse proxy in front of mailcow, as I do, in my example nginx
> 
> like this here: https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-rp/#nginx
> 
> Because of the changes in SoGo 5.5.1 and in the configuration in the nginx mailcow container, you have to increase the proxy buffer size in your reverse proxy also, or you can't log into SoGo anymore
> 
> The Active Sync location directive has to be changed: You need to replace `proxy_buffers 64 256k;` with `proxy_buffers 64 512k;`
> 
> ```
> location /Microsoft-Server-ActiveSync {
>     proxy_pass http://127.0.0.1:8080/Microsoft-Server-ActiveSync;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_connect_timeout 75;
>     proxy_send_timeout 3650;
>     proxy_read_timeout 3650;
>     proxy_buffers 64 512k;
>     client_body_buffer_size 512k;
>     client_max_body_size 0;
>   }
> ```
> 
> You also need to add the following to the root location directive
> 
> ```
> proxy_buffer_size 128k;
> proxy_buffers 64 512k;
> proxy_busy_buffers_size 512k;
> ```
> 
> It looks like this then: Note: I use port 8080 for my nginx container, yours may be different
> 
> ```
>   location / {
>     proxy_pass http://127.0.0.1:8080/;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     client_max_body_size 0;
>     proxy_buffer_size 128k;
>     proxy_buffers 64 512k;
>     proxy_busy_buffers_size 512k;
>   }
> ```
> 
> took me a while to figure this out, hope it helps ;)
> 
> after these changes it worked for me

i just set-up in nginx-proxy-manager for domain xyz.mailcow.com (domain name where you installed mailcow) in section advanced:

proxy_buffer_size 128k;
proxy_buffers 64 512k;
proxy_busy_buffers_size 512k;

then sogo works for me, but should i do somewhere else also edit ? (sorry iam newbie so can be hard for me understand everything from start :) )

**Comment by xdubx** [comment]
```
        - "traefik.http.middlewares.custom-buffering.buffering.maxRequestBodyBytes=131072"
        - "traefik.http.middlewares.custom-buffering.buffering.memRequestBodyBytes=131072"
        - "traefik.http.middlewares.custom-buffering.buffering.maxResponseBodyBytes=524288"
        - "traefik.http.middlewares.custom-buffering.buffering.memResponseBodyBytes=524288"
```
My traefik setup but it still not works.
