### ISSUE TITLE
Cannot upload attachments

### ISSUE THREAD

**Issue by DiEg0123** [mailcow/mailcow-dockerized#454]
Hi,

I am using latest Mailcow Dockerized version with CentOS 7. Its an awesome software and thank you very much! Everything works fine for past 3 weeks but beginning from last 3 days ago, I couldn't upload attachments from my office anymore. I can send mail but it takes a few seconds. However, when I tried to upload attachment, it fails. If I use VPN or try from different IP, it works perfectly.

Both SMTP and SOGo fails to upload any attachments from office IP.

Is there any where I can check if my office IP is banned from Docker Fail2ban?  Thank you very much in advanced!

**Comment by phillipplum** [comment]
I think you can check Fail2ban in the logs. In mailcow UI -> Logs -> Fail2Ban.

**Comment by DiEg0123** [comment]
Thanks! I tried to see the log and I don't see my IP being banned. In fact I don't see any IP getting ban. System automatically unban all IPs in specific time frame. Even if I try after unbanning all, I still cannot upload attachment. Sometimes I can't even send mails. Any other suggestions please?
