### ISSUE TITLE
TLS1.0 + TLS1.1 still enabled on port 25/smtp (via STARTTLS)

### ISSUE THREAD

**Issue by raoulbhatia** [mailcow/mailcow-dockerized#4547]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Per #3127 and https://mailcow.email/2020/02/12/tls-1-0-and-1-1-is-now-disabled-for-pop3-s-imap-s-smtps-and-submission/ 
TLS1.0 and TLS1.1 were disabled in mailcow.

However, there is a difference between port 25/SMTP (TLS1.0 + TLS1.1 enabled) and port 587/Submission (TLS1.0 + TLS1.1 disabled).

You can validate this either via sslscan,
or via https://internet.nl/mail/

```
sslscan --starttls-smtp --no-ciphersuites --no-heartbleed --no-groups --no-check-certificate --no-compression mx.domain.tld:25
Version: 2.0.13-static
OpenSSL 1.1.1n  15 Mar 2022

Connected to 77.244.245.211

Testing SSL server mx.domain.tld on port 25 using SNI name mx.domain.tld

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   enabled
TLSv1.1   enabled
TLSv1.2   enabled
TLSv1.3   enabled

  TLS Fallback SCSV:
Server supports TLS Fallback SCSV

  TLS renegotiation:
Secure session renegotiation supported
```

```
sslscan --starttls-smtp --no-ciphersuites --no-heartbleed --no-groups --no-check-certificate --no-compression mx.domain.tld:587
Version: 2.0.13-static
OpenSSL 1.1.1n  15 Mar 2022

Connected to 77.244.245.211

Testing SSL server mx.domain.tld on port 587 using SNI name mx.domain.tld

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled

  TLS Fallback SCSV:
Server supports TLS Fallback SCSV

  TLS renegotiation:
Session renegotiation not supported
```

To me, there seems to be a difference in configuration between `postscreen` on port 25 and `smtpd` running on submission.

### Logs

```bash
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[405]: connect from somehost.domain.tld[1.2.3.4]
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[405]: SSL_accept error from somehost.domain.tld[1.2.3.4]: -1
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[405]: warning: TLS library problem: error:14209175:SSL routines:tls_early_post_process_client_hello:inappropriate fallback:../ssl/statem/statem_srvr.c:1767:
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[405]: lost connection after STARTTLS from somehost.domain.tld[1.2.3.4]
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[405]: disconnect from somehost.domain.tld[1.2.3.4] ehlo=1 starttls=0/1 commands=1/2
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/postscreen[399]: CONNECT from [1.2.3.4]:61945 to [172.22.1.253]:25
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/postscreen[399]: WHITELISTED [1.2.3.4]:61945
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[401]: connect from somehost.domain.tld[1.2.3.4]
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[401]: Anonymous TLS connection established from somehost.domain.tld[1.2.3.4] to mx.domain.tld: TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits)
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[401]: lost connection after STARTTLS from somehost.domain.tld[1.2.3.4]
postfix-mailcow_1    | Apr 17 19:54:20 959e5e9b42f1 postfix/smtpd[401]: disconnect from somehost.domain.tld[1.2.3.4] ehlo=1 starttls=1 commands=2
```
```


### Steps to reproduce

1. `sslscan --starttls-smtp --no-ciphersuites --no-heartbleed --no-groups --no-check-certificate --no-compression mx.domain.tld:25`
2. `sslscan --starttls-smtp --no-ciphersuites --no-heartbleed --no-groups --no-check-certificate --no-compression mx.domain.tld:587`
3. `sslscan --no-ciphersuites --no-heartbleed --no-groups --no-check-certificate --no-compression mx.domain.tld:465`

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 LTS |
| Is Apparmor, SELinux or similar active? | apparmor 2.13.3-7ubuntu5.1 |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4 cores / 8GB memory |
| Docker Version (`docker version`) | docker-ce 5:20.10.14~3-0~ubuntu-focal |
| Docker-Compose Version (`docker-compose version`) | docker-compose version 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | n/a |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
YOUR OUTPUT GOES HERE
```

**Comment by andryyy** [comment]
It is enabled on port on port 25 for a simple reason: if it is not, old mail servers will fall back to no encryption at all.

It would be bad to enforce TLS 1.3 with the most secure ciphers on port 25 and watch half of the connections fall back to plain connections.

So it is very much wanted on that port. That's also why Postfix has config parameters for mandatory and opportunistic TLS settings.

When you enforce TLS for a mailbox or domain, mandatory settings apply (see [here](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/postfix/main.cf#L141-L146=)).

So you want to give old servers the chance to use at least "some encryption", even if it is half-assed and broken. A plain connection is always worse. You can work with TLS policies to catch important connections etc.

I will close the issue. :)

André

**Comment by benoitjpnet** [comment]
Protonmail has chosen to enable TLS 1.2 and 1.3 only.
TLS 1.0 and 1.1 are being phased out... And will have to be disabled someday by Mailcow as well. The question is when?

**Comment by mkuron** [comment]
That is a good question, and to answer it, we need to find out how prevalent TLS 1.0 and 1.1 still is for mail delivered to port 25. Someone operating a very large Mailcow instance should check their Postfix logs and gather some statistics. While all Linux distributions limited to TLS 1.1 are probably out of support by now, there are other mail servers to consider, e.g. Microsoft Exchange. Judging by https://learn.microsoft.com/en-us/Exchange/exchange-tls-configuration?view=exchserver-2016, TLS 1.2 has to be manually enabled on Microsoft Exchange 2013 and 2016, so there may still be Exchange servers on the internet that have it disabled even though they are on the latest updates.

I just checked my very small Mailcow instance and all TLSv1/TLSv1.1 connections are either closed immediately after opening or are coming from spammers testing for open relays (i.e. the next log entry is "relay access denied"). So I think I could safely turn off TLS 1.0 and 1.1 on my server. But that may be different for you depending on whom you exchange mails with.

**Comment by chriscroome** [comment]
I could grep our logs if you could give me an idea of what to grep for exactly?

**Comment by mkuron** [comment]
Here's the command I ran: `for t in TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; do docker compose logs postfix-mailcow | grep "postfix/smtpd.*$t " | awk '{print "'$t' "$13}' | sort | uniq -c; done`. It gives you a list similar to this:
```
     38 TLSv1.2 everycloudtech.us[107.170.168.72]:
      1 TLSv1.2 out-19.smtp.github.com[192.30.252.202]:
      2 TLSv1.3 mout.gmx.net[212.227.15.15]
```

**Comment by andryyy** [comment]
It is disabled for ports other than 25, mainly because of authentication. For obvious reasons. It is still enabled for 25 inter-MX. It should be disabled and plain text not offered as fallback. It would be stupid to let servers fall back to plain when all they talk is <= 1.1.„They do, so we do“ never worked for anyone. Am 07.03.2023 um 13:38 schrieb Benoît ***@***.***>:﻿
Protonmail has chosen to enable TLS 1.2 and 1.3 only.
TLS 1.0 and 1.1 are being phased out... And will have to be disabled one day by Mailcow as well. The question is when?
