### ISSUE TITLE
ARC fails for secondary domains

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#455]
First of all I haven't looked into the concept of ARC further than the first paragraph of wikipedia, yet :( I'll try to catch up soon.

But meanwhile I noticed two things with the latest mailcow version:

1) When I send a mail from a mailbox/user `user@primary-domain.de` but I use an alias `some-alias@secondary-domain.de` ARC fails with `arc=fail (signature failed)` (tested on a Google mailbox as receiver). However when I use `some-random-other-alias@primary-domain.de` ARC passes. In the failed try `ARC-Seal` and `ARC-Message-Signature` look correct to me in the sense that both are correctly using `d=secondary-domain.de`. However and this is

2) `ARC-Authentication-Results` stats `smtp.auth=user@primary-domain.de`. Now I'm not sure if this relevant for the ARC failure as the `smtp.auth` domain obviously mismatches the sender and signature domain when using an alias domain. In any case this also is a bit much information. I don't really want that every user always reveals his full login name regardless with domain he uses. Something like `smtp.auth=authenticated-user@primary-or-alias-domain.de` where `authenticated-user` is fixed and always replaces the real login name would be preferable if doable ;-)

**Comment by andryyy** [comment]
Hi, I disabled the login mismatch for ARC for now. I will have a closer look into it. :-)
