### ISSUE TITLE
accept message “authorize application” once and/or longer period of time

### ISSUE THREAD

**Issue by Danne-J** [mailcow/mailcow-dockerized#4551]
### Summary

got a discussion going in the forum

https://community.mailcow.email/d/1549-how-to-speed-up-nextcloud-login-with-mailcow-as-auth-provider

### Motivation

annoying step always have this on trusted application, source, network and so on :)

**Comment by BigMichi1** [comment]
same #4478 ?

**Comment by Danne-J** [comment]
> same #4478 ?

Yes seems like it

**Comment by DerLinkman** [comment]
Duplicate of: https://github.com/mailcow/mailcow-dockerized/issues/4478
