### ISSUE TITLE
FR: Option in update script to ignore Checking for internet connection

### ISSUE THREAD

**Issue by tpihl** [mailcow/mailcow-dockerized#4552]
### Summary

Checking for internet connection assumes that mailserver is allowed to ping dns-servers. That's not true, at least not for me.
Another solution would be to allow override (cmd arg or env var) what IP's to ping (so i could point it somewhere i don't block).

BR/T

### Motivation

First of all, I think it's a redundant check while it has the benefit of a nicer error message, and could result in a warning instead of exit the script.

The bigger issue for me is that i use internal dns (think pihole) so my firewall is blocking all known dns servers from anything except the internal dns server. 

Also (trying) to block all DOH servers for same reason (i am not afraid of what my isp can learn since my dns-server will query many servers and i live in a country where my isp is at least slightly restricted to sell my information, i.e. in EU).

So every time i want to upgrade mailcow-dockerized, i have to hack the install.sh to not ping public DNS servers.

**Comment by DerLinkman** [comment]
Possible but only with a --skip-ping-check parameter I think since not all have these concerns.
