### ISSUE TITLE
Using custom Redis/MariaDB/Memcached instances

### ISSUE THREAD

**Issue by phenomax** [mailcow/mailcow-dockerized#456]
I've got the following feature request:
It would be quite nice, if existing MariaDB, Redis or Memcached servers could be used by providing their credentials. 
Currently I see no other way than creating the full stack of all shipped containers - or not?

I'm looking forward to the implementation! :)

**Comment by andryyy** [comment]
You would need to fulfil some requirements like Barracuda engine and a default row_format which is compressed or dynamic.

It is not planned in near future. But I will keep it in mind. :-)

**Comment by mkuron** [comment]
Partial duplicate of #190

**Comment by Keyzmo** [comment]
+1 for this
