### ISSUE TITLE
Add Piler to archive emails

### ISSUE THREAD

**Issue by phillipplum** [mailcow/mailcow-dockerized#457]
I would like to add the following Docker (https://github.com/heri16/docker-piler-php) and then also configure Postfix so that the e-mails are archived. How do I customize docker-compose and postfix?

Can someone help me? Thanks!

**Comment by catcun** [comment]
I would love to have piler integrated with mailcow. But I guess it is way out of the scope of mailcow.

**Comment by phillipplum** [comment]
Yes, i think this too @catcun. But maybe someone can help to integrate it. I'm new with docker compose and I don't know how I have to adjust the network, for example.

**Comment by Braintelligence** [comment]
Actually servercow is selling piler as optional service to mailcow 😸 
I'd understand if @andryyy wouldn't want to implement this special feature into the open-source docker-compose.
![grafik](https://user-images.githubusercontent.com/6761196/28753611-420e70b8-7537-11e7-9c7d-7356ebc1a12a.png)

**Comment by andryyy** [comment]
Archiving should be done on dedicated  hardware. Besides only a very small number of users who need it, I don't see any good reason to ship it with mailcow on the same machine. If you want it, go ahead and include it into your installations. :-)

**Comment by Braintelligence** [comment]
Maybe we could create a chapter in the documentation on how to run a dockerized piler on another machine and connect it to mailcow?

**Comment by andryyy** [comment]
Sure, go ahead.

**Comment by Braintelligence** [comment]
Now I only have to read up on piler 😸.

**Comment by Braintelligence** [comment]
@andryyy I've send you a little "Aufmerksamkeit" for all your hard work 😺.

**Comment by kwisatz** [comment]
Was any progress made on this? (@Braintelligence ?) If so, could the documentation be updated with that information? If not, I'll have to give it a spin myself.

**Comment by andryyy** [comment]
Install Piler on another host, add bcc maps, profit. 👍

**Comment by kwisatz** [comment]
Sounds easy enough ;)

**Comment by Braintelligence** [comment]
@kwisatz Sorry I didn't have the time to do this yet ☹️ . I'd be very happy to hear about your steps to success on doing this, though!

@andryyy Thanks for the hint! I should try it out on FreeNAS 😸.

**Comment by andryyy** [comment]
I can create a new install guide.

**Comment by ghost** [comment]
@andryyy 
This is a great idea!

**Comment by ghost** [comment]
@andryyy 
Is there some kind of "How to".
I'm really interested in this ...
Perhaps I can help you writing this install guide?

**Comment by lucianlazar1983** [comment]
I am too very interested in this, for now i will creaste a separate VM for Mailpiler and modify manually postfix main.cf including: always_bcc = bcc@mydomain.com
On Piler i would run a cron this way: 01 20 * * * /usr/local/bin/pilerimport –K mailcowserver.com -u bcc@emailaddress -p bccpassword
Would be nice to have it automated somehow...
Any clues?

**Comment by ghost** [comment]
I would like to ask if there are plans to write an install guide.
As i mentioned before i am very interested in using piler.

**Comment by Braintelligence** [comment]
@andryyy Is there any progress on this? I'd really like to test this out, but would rather follow your educated knowledge.

**Comment by andryyy** [comment]
No. It is basically installing Piler and setting up BCC maps in mailcow. :)

**Comment by Braintelligence** [comment]
Do you recommend running an isolated Piler for each mailcow instance or do you run one for all? And do you rather recommend a bare-metal/vm install or a dockerized install? (Last questions, gonna try it after knowing the answers :P)
