### ISSUE TITLE
WebAuthn does not accept Android devices

### ISSUE THREAD

**Issue by snevas** [mailcow/mailcow-dockerized#4579]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

If you try to do enrollment of a Android FIDO2 device, you get error 114 on your Android device.

It does work with the demo @ https://webauthn.io/ (feel free to test a correct flow here) and on my Nextcloud environment with the Two-Factor WebAuthn plugin.

### Logs

```bash
nginx-mailcow_1      | x.x.x.x - - [09/May/2022:10:21:41 +0200] "GET /api/v1/get/fido2-registration/username HTTP/1.0" 200 771 "https://hostname/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
```

### Steps to reproduce

0. Startup Chrome
1. Login to mailcow UI
2. Register FIDO2 device
3. Choose to use a Android device
4. Scan the QR with a Android 7+ device
5. Approve the register on device
6. Get error 114

### System information

| Question | Answer |
| --- | --- |
| My operating system | Debian Bullseye |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 6Gb, 4 cores |
| Docker Version (`docker version`) | 20.10.14 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | nginx |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
Other certs & no ipv6nat-mailcow (switched with update.sh)
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
No alterations
```

ip6tables -L -vn:
```
No alterations
```

iptables -L -vn -t nat:
```
No alterations
```

ip6tables -L -vn -t nat:
```
No alterations
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
151.101.193.69
151.101.129.69
151.101.65.69
151.101.1.69
```

**Comment by FreddleSpl0it** [comment]
Do you mean Two-factor authentication or Login with FIDO2.
Login in with FIDO2 should work with Android.

I think that there are currently some complications with android devices regarding WebAuthn.
Android needs a specific parameter (require user interaction) which is unnessaecary for Two-factor authentication. So we didn't use it.

**Comment by snevas** [comment]
Both flows do not work correctly:
- Passwordless login cannot register
- TFA can only register, but cannot login

I've tested with User Verification set to Discouraged at https://webauthn.io/ . Android still works with that set.

**Comment by FreddleSpl0it** [comment]
For tfa i cant reproduce as it works for me on Android.

Could you try:
create `data/web/inc/vars.local.inc.php`
```
<?php


// UV flag handling in FIDO2/WebAuthn - defaults to false to allow iOS logins
// bool
// true = required
// false = preferred
//
// string 
// 'required' 'preferred' 'discouraged'

$WEBAUTHN_UV_FLAG_REGISTER = false;
$WEBAUTHN_UV_FLAG_LOGIN = false;
$WEBAUTHN_USER_PRESENT_FLAG = true;

$FIDO2_UV_FLAG_REGISTER = 'preferred';
$FIDO2_UV_FLAG_LOGIN = 'preferred'; // iOS ignores the key via NFC if required - known issue
$FIDO2_USER_PRESENT_FLAG = true;

?>
```

and play with those vars. i would say for tfa try setting `$WEBAUTHN_UV_FLAG_REGISTER` `$WEBAUTHN_UV_FLAG_LOGIN` to true and restart with `docker-compose down` `docker-compose up -d` 

We are using lbuchs\Webauthn library and this is the demo page where you can try different parameters.
[https://webauthn.lubu.ch/_test/client.html](https://webauthn.lubu.ch/_test/client.html)

Also always make sure you are using a https connection and a hostname as url instead of a ip adress.

**Comment by snevas** [comment]
Good to see that if I test against the library, I get the same error and it's not by-passable by configuration tweaks.
Probably it's the new Titan M2 chip combined with the library. Hopefully they will fix it and it will go downstream to moocow soon.

Tested with:
- Chrome on Windows / Ubuntu 20.04
- Pixel 6 phone

**Comment by snevas** [comment]
Found this at https://docs.hypr.com/integratinghypr/docs/sdk-fido2-webauthn-browser :
>name: NotSupportedError
>
>Message: Either the device has received unexpected request parameters, or the device cannot support this request.
>
>Explanation: If you see this error, it most likely means that you are trying to register a device with the resident key value set to true in the create credentials request.
>
>To overcome the issue, you should set the isResidentKeyRequired parameter to false when creating the FIDO credential.

Looks there is a requireResidentKey boolean in mailcows library as well.

**Comment by FreddleSpl0it** [comment]
I just tested it again and for TFA neither "Supports resident keys" nor "Supports user verification" is needed.
Normally it should work.


For the FIDO2 registration the situation is different.
Here "Supports user verification" is required, according to [https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.html.](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.html)

However, "Supports resident keys" is not required and is still set to true. Normally we could set this to false.
According to [https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html) "Supports resident keys" is only needed for username-less and password-less logins. The Mailcow FIDO2 flow is password-less only.

But I doubt that this will solve the problem.



Here are the lines where requireResidentKey is specified.

`getCreateArgs($userId, $userName, $userDisplayName, $timeout=20, $requireResidentKey=false, $requireUserVerification=false, $crossPlatformAttachment=null, $excludeCredentialIds=array())`

### TFA Webauthn
https://github.com/mailcow/mailcow-dockerized/blob/43d2a6e13538e7d507bdbd3714e3a6dd741d24d6/data/web/json_api.php#L441

### FIDO2
https://github.com/mailcow/mailcow-dockerized/blob/43d2a6e13538e7d507bdbd3714e3a6dd741d24d6/data/web/json_api.php#L404

**Comment by snevas** [comment]
I see you are working on a feature-branch for TFA, if you need me to test something regarding the above, let me know.

Off-topic:
I was waiting for [this](https://github.com/mailcow/mailcow-dockerized/commit/49c506eed956fdc985f3b64e82336c27fca68e52) feature for quite some while now. Kudo's for implementing this!

**Comment by FreddleSpl0it** [comment]
Would be great to get some more test reports, so feel free to test it :). Just pull from the `feature/tfa-flow` branch for testing purpose.
It should be ready to go but @DerLinkman has reported some problems using WebAuthn with his Yubico 5 after this patch.
I don't know exactly why because all of them work for me. @MAGICCC has also tested the whole thing and after a few fixes everything worked too.

This is currently the problem, which is why the whole thing has not yet been patched

**Comment by snevas** [comment]
Tested 2FA! I am able to WebAuthn register with:
- Windows Hello
- Android phone
- Yubikey 5 NFC

I am only able to WebAuthn login with:
- Windows Hello
- Yubikey 5 NFC

So, the sadly the Android phone part is only partly fixed (register only).

Also tested FIDO2 (usernameless/passwordless) and you can successfully register and login with Windows Hello / Yubikey 5 NFC, but not with an Android phone.

**Comment by FreddleSpl0it** [comment]
Thanks for testing. Could you also test 2FA in combination with other authentication methods like TOTP.
Did you test with admin and user accounts or only admin accounts?

**Comment by snevas** [comment]
Will follow up on that testing. Do you have a idea why we can use Webauthn 2fa to register, but not to authenticate with Android?

I've done all my testing with a user account.

**Comment by FreddleSpl0it** [comment]
> Do you have a idea why we can use Webauthn 2fa to register, but not to authenticate with Android?

I just saw something on the lbuchs github page. **Please try this...**
Go to [https://webauthn.lubu.ch/_test/client.html](https://webauthn.lubu.ch/_test/client.html) and try these settings:
![webauthn error](https://user-images.githubusercontent.com/75116288/171990047-f1b9f5f5-ed3e-49cb-967c-7e24057ec7cd.png)

This should lead to the error, that you can register your android phone but cannot use it for login.
Now try the whole thing with these settings:
![webauthn success](https://user-images.githubusercontent.com/75116288/171990090-e821703a-ccd2-4d4a-ad54-9e8176836d4f.png)

Does it work?

**Comment by snevas** [comment]
Both register and login worked with the suggested settings in the demo client.

**Comment by FreddleSpl0it** [comment]
I adapted these settings in the feature/tfa-flow branch. The Android bug should be fixed and hopefully we can merge this branch for the 2022-07 update

**Comment by snevas** [comment]
New situation is as follows.

2FA WebAuthn:
Android register and login success
Yubikey register and login success
Hello register success, login failed (only usb/android allowed)


FIDO2 passwordless:
Android register fail
Yubikey register and login success
Hello register and login success

Just a question out of curiosity: Why is password required for adding 2FA, but not for FIDO2?

**Comment by andryyy** [comment]
> Just a question out of curiosity: Why is password required for adding 2FA, but not for FIDO2?

🐛 

Should be looked into.

**Comment by FreddleSpl0it** [comment]
> New situation is as follows.
> 
> 2FA WebAuthn: Android register and login success Yubikey register and login success Hello register success, login failed (only usb/android allowed)
> 
> FIDO2 passwordless: Android register fail Yubikey register and login success Hello register and login success
> 
> Just a question out of curiosity: Why is password required for adding 2FA, but not for FIDO2?

After some testing i can say that windows hello works for me.
but i have encountered a few problems. The first was that my mailcow was running with a self-signed certificate and the second problem was that Windows Hello was not responding because I had the mailcow open in a Chrome incongnito tab.

**Comment by FreddleSpl0it** [comment]
> FIDO2 passwordless:
> Android register fail

It seems that this is a bug on chrome android. could you try this with another browser like firefox?

**Comment by snevas** [comment]
FIDO2 android register failed chrome/android/library bug confirmed with the demo above. Using an Android device for WebAuthn is a Chrome feature, so you cannot test with another browser.
Found the issue with Hello: if you enabled Hello for FIDO2 as well, it does not work for 2FA anymore. Even when you remove FIDO2, it still does not work. If you reregister 2FA it works again. Seems to be an issue with Hello, so no need to investigate.

So nice work @FreddleSpl0it, looks like everything is fixed with WebAuthn compatibilty.

Should I make a new issue for(?):
> > Just a question out of curiosity: Why is password required for adding 2FA, but not for FIDO2?
> 
> 🐛
> 
> Should be looked into.

**Comment by DerLinkman** [comment]
Yes please :)

Thanks for your help.

**Comment by snevas** [comment]
Done https://github.com/mailcow/mailcow-dockerized/issues/4623

Looking forward to the 2022-07 update with this merged in!
