### ISSUE TITLE
Caching mail bugs to protect privacy of the users

### ISSUE THREAD

**Issue by MatejKovacic** [mailcow/mailcow-dockerized#4584]
### Summary

Mailcow server should have an option to download all images inserted in emails before you open them. This will prevent tracking of users with so called mail bugs - small, invisible images inserted into e-mails by e-mail newsletters or people who want to track mail recipients. When e-mail is opened, the adversary's server keeps track when this image was opened and by which IP address.

### Motivation

This would prevent tracking with mail bugs and improve user's privacy.

### Additional context

I have [read the news, that Apple Mail started to block email trackers by default](https://www.schneier.com/blog/archives/2022/05/apple-mail-now-blocks-email-trackers.html).

Most email newsletters you get include an invisible “image,” typically a single white pixel, with a unique file name. The server keeps track of every time this “image” is opened and by which IP address. This quirk of internet history means that marketers can track exactly when you open an email and your IP address, which can be used to roughly work out your location.

So, how does Apple Mail stop this? By caching. Apple Mail downloads all images for all emails before you open them. Practically speaking, that means every message downloaded to Apple Mail is marked “read,” regardless of whether you open it. Apples also routes the download through two different proxies, meaning your precise location also can’t be tracked.

**Comment by ghost** [comment]
That's sometimes to submit to Inverse, SOGo's developers.

**Comment by MAGICCC** [comment]
Indeed you may ask SOGo/[insert you client here] devs
