### ISSUE TITLE
No protocols when adding app password by api submitted.

### ISSUE THREAD

**Issue by 10erNetzwerk** [mailcow/mailcow-dockerized#4588]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Today I found out that our in-house script for creating app passwords is no longer working.
We create an app password for each mailbox for our external archiving via IMAP.
In February, when creating via API, all protocols still added automatically.
Since the April update, this no longer works. The APP password is stored but no protocol.

Request body:
active= '1'
  username = 'abx@xyz.com'
  app_name = 'Archiv'
  app_passwd = 'Password'
  app_passwd2 = 'Password'

Post Powershell Script:
Invoke-WebRequest -Uri https://mail.example.com/api/v1/add/app-passwd -Body $body -ContentType application/json -Headers @{ 'x-api-key' ='APIKEY' } -Method Post

Attached are a few screenshots:
Full Powershell Script:
https://imgur.com/ipfsTxF
Before Update:
https://imgur.com/OpQO5dW
After Update 2022-04
https://imgur.com/E8tLd2A
After Update 2022-05c
https://imgur.com/3XGVsdn

### Logs

```bash
StatusCode        : 200
StatusDescription : OK
Content           : [{"type":"success","log":["app_passwd","add",{"username":"abx@xyz.com","active":"1","app_name":"Archiv","app_passwd":"*","app_passwd2":"*"}],"msg":"app_passwd_added"}]
RawContent        : HTTP/1.1 200 OK
                    Vary: Accept-Encoding
                    Pragma: no-cache
                    Strict-Transport-Security: max-age=15768000;
                    X-Content-Type-Options: nosniff
                    X-XSS-Protection: 1; mode=block
                    X-Robots-Tag: none
                    X-Download...
Forms             : {}
Headers           : {[Vary, Accept-Encoding], [Pragma, no-cache], [Strict-Transport-Security, max-age=15768000;], [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 182
```

### Steps to reproduce

...

### System information

| Question | Answer |
| --- | --- |
| My operating system |  Ubuntu 20.04.4 LTS |
| Is Apparmor, SELinux or similar active? |NO |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | NO |
| Server/VM specifications (Memory, CPU Cores) |CPU AMD EPYC™ 7702 / DDR4 ECC 64GB RAM |
| Docker version (`docker version`) | 20.10.16 |
| docker-compose version (`1.29.2`) | I_DO_REPLY_HERE |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-05C |
| Reverse proxy (custom solution) | nothing |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
151.101.65.69
151.101.1.69
151.101.193.69
151.101.129.69

**Comment by FreddleSpl0it** [comment]
Interesting that this worked before. I looked at the code and your request should be like that.
Add/Remove the access you want from the protocols array.

```
{
  "active": "1",
  "username": "info@domain.tld",
  "app_name": "App",
  "app_passwd": "pass",
  "app_passwd2": "pass",
  "protocols": [
    "imap_access",
    "dav_access",
    "smtp_access",
    "eas_access",
    "pop3_access",
    "sieve_access"
  ]
}
```

**Comment by 10erNetzwerk** [comment]
Hello,

Thank you very much! **It works.** I only need the IMAP service, is this solution **MUCH** better!!!


Will you include this case in the Swagger documentation? I think that would be interesting for others too.

**Comment by DerLinkman** [comment]
Marked as solved in support 🙂
