### ISSUE TITLE
CPU running on 100 % and unaccessible server

### ISSUE THREAD

**Issue by kunago** [mailcow/mailcow-dockerized#459]
It has already happened to me twice that the server running solely mailcow started running some process on 100 % and overloaded the server which became unaccessible via any means (like SSH).

First time it happened around 23:30 on one day, second time it was this morning at 5:07.

It seems to have no apparent reason and currently it is unknown to me which process does it. There is no cron task that should be run at these times so I am guessing it could be one of the containers. I am investigating the logs and will post them later on when I may have some clue.

My question is whether this has happened to anyone already? It is a production server and I have not done any modifications whatsoever.

**Comment by andryyy** [comment]
Hi,

I have not seen this happening... ClamAV can use some cpu time when updating, but not _that_ much.

Couldn't you see the process? This will ultimately help. :-)

**Comment by kunago** [comment]
I saw something happening there; unfortunately I don't have the previous log as I assumed it could have been some cron task. This is now not the case.

It drove the server unaccesible and I saw errors in various containers which is hard to debug as some do not log the time. I am posting what I found interesting in logs cutting out the unimportant and useless older or newer logs:

[mailcow-clamd.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147624/mailcow-clamd.log.txt)
[mailcow-dovecot.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147628/mailcow-dovecot.log.txt)
[mailcow-fail2ban.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147627/mailcow-fail2ban.log.txt)
[mailcow-mysql.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147625/mailcow-mysql.log.txt)
[mailcow-php-fpm.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147629/mailcow-php-fpm.log.txt)
[mailcow-postfix.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147626/mailcow-postfix.log.txt)
[mailcow-redis.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147630/mailcow-redis.log.txt)
[mailcow-rspamd.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147631/mailcow-rspamd.log.txt)
[mailcow-unbound.log.txt](https://github.com/mailcow/mailcow-dockerized/files/1147632/mailcow-unbound.log.txt)

**Comment by kunago** [comment]
Oh and no, I could not see the process. There was no way for me to enter the server.

**Comment by andryyy** [comment]
I don't see anything indicating the **start** of a problem. Though there was a problem - obviously.

Maybe the server run out of memory? Looks like it took Redis way to long to write to memory.

**Comment by kunago** [comment]
As for the resources, I am posting CPU and memory usage.

![cpu usage](https://user-images.githubusercontent.com/460971/28202920-c7f7fcca-6877-11e7-99e4-8b5b65669a12.jpg)
![memory usage](https://user-images.githubusercontent.com/460971/28202921-c7fd229a-6877-11e7-9652-d00049d4f574.jpg)

I am running PROMOX and the server is virtualized so it is simple to see these resources but as with any other locked server, it is still locked when it is locked.

**Comment by kunago** [comment]
I also found interesting in the log there are various errors around that time:

- clamav started an update with some dn_expand errors (which I have not figured out what they mean)
- redis memory usage
- mysql crashed

So it may be either clamav or redis.

**Comment by kunago** [comment]
dn_expand seem to be a DNS test, by the way.

**Comment by andryyy** [comment]
Hm, you shouldn't assume this by the logs. Processes can die or stuck and stop further logging. Other innocent processes then log strange errors due to being low on resources  (CPU, memory).

Can you install some kind of process logging?

**Comment by kunago** [comment]
I tried looking for some monitoring software. The thing is what to monitor? I found a nice command "docker stats". Would that be good to start with?

**Comment by kunago** [comment]
I set up my own monitoring script so once I have some news about the CPU usage, I will post more details.

**Comment by elvirdz** [comment]
Do you use Debian 9 and have some snapshots on your Proxmox

**Comment by kunago** [comment]
So here it goes.

![console](https://user-images.githubusercontent.com/460971/28243596-0d245488-69d1-11e7-8522-e8b8d5e2c9fd.jpg)

Seems to be some kernel issue. It was also happening on another server of mine but I tought it was the VPS provider issue. It was not apparently.

I am using Debian 8 by the way.

**Comment by elvirdz** [comment]
Kernel Version ? uname -a

**Comment by kunago** [comment]
It turns out this is an already documented issue and the solution is to upgrade the kernel.
If it happens to somebody else, please see this page in the docs: [Prepare Your System](https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-system/).

I must have missed this notice since I was updating mailcow since a few versions back and even though this was a quite important one, I saw it nowhere.

**Comment by kunago** [comment]
@elvirdz : It must me the case with kernel, right now working on the update.

**Comment by kunago** [comment]
As healthchecks were an on-the-fly change and kernel upgrade means to change the storage drive to anything but _aufs_ as it is not supported in Kernel 4.9, could anyone point me to a safe way to migrate everything?

**Comment by elvirdz** [comment]
ok u have to change docker on overlay2 on 4.9 kernel

docker-compose down
service docker stop
rm -r /var/lib/docker/aufs
nano /etc/docker/daemon.json 
```
{
  "storage-driver": "overlay2"
}
```
service docker start
docker-compose up -d

**Comment by kunago** [comment]
Will that affect any data, such as email storage?

**Comment by elvirdz** [comment]
no just docker-compose down

**Comment by andryyy** [comment]
That's right, the driver is used by the containers. Just run "down" to drop all containers (and every other container that may be running on this host, too).

**Comment by kunago** [comment]
Nice, guys. Thank you very much for your help. It was just how @elvirdz wrote down, fairly easy. It would be good to leave this topic here for the reference.
