### ISSUE TITLE
Virtual environment pip

### ISSUE THREAD

**Issue by Phil12n** [mailcow/mailcow-dockerized#4603]
### Summary

Hello Christianbur,

Thanks for your package which is very useful.

During installation i have a warning message concerning virtual environment :

Successfully installed pip-22.1.2
Collecting imapclient
  Downloading IMAPClient-2.2.0-py2.py3-none-any.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 9.9 MB/s eta 0:00:00
Collecting configparser
  Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from imapclient) (1.15.0)
Installing collected packages: imapclient, configparser
Successfully installed configparser-5.2.0 imapclient-2.2.0
**WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv**

I'm not a specialist and don't know if this warning is important.

### Motivation

Including virtual environment could prevent conflicts
I had an issue with my mailcow-dockerized installation.
Getmail was ko so maybe this new feature could avoid conflicts.

Thanks!
Phil

**Comment by DerLinkman** [comment]
Hi,

where does this occur?
On your local machine?

If so: That is not a mailcow problem.

Since you don´t need pip as a requirement. You can install docker-compose with that but it is not advised by us.

**Comment by Phil12n** [comment]
Hi Niklas,

It occurs both on OVH-VPS (Debian 11) and on self-hosting NAS (Proxmox + Debian 11)
With mailcow-dockerized last update.

Thanks for your help ;-)

**Comment by DerLinkman** [comment]
Inside a container? Or on your local machines?

mailcow does not use pip on your local machine. Only Docker and Docker-Compose.

**Comment by Phil12n** [comment]
Sorry both inside containers:
- Docker version : 20.10.16
- Docker-compose version:  1.29.2

**Comment by DerLinkman** [comment]
Which one? When does it happen? What do you do that this happen?

**Comment by Phil12n** [comment]
It happends during a fresh installation:
command line : docker-compose built getmail
Messages : 
.../...
Successfully installed configparser-5.2.0 imapclient-2.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
.../...
I tried on another fresh installation right now => same warning !?

**Comment by DerLinkman** [comment]
Hm.

Getmail is not mailcow :)

So that is not a mailcow issue.

**Comment by MAGICCC** [comment]
Indeed, maybe you can ask @christianbur directly or in [our forum](https://community.mailcow.email/)

**Comment by christianbur** [comment]
@Phil12n Please open an issue here https://github.com/christianbur/docker_projects/issues

**Comment by Phil12n** [comment]
@christianbur Done ! Thanks
