### ISSUE TITLE
Ldap in the WEB UI

### ISSUE THREAD

**Issue by Raffael93** [mailcow/mailcow-dockerized#4625]
### Summary

Hello, 

Is-it planned to get a connector ldap with SOGo mail ?

### Motivation

It will be easier to create any account on the ldap ( openldap / IPA ) for making groups of rights ( admin, user .... )

**Comment by DerLinkman** [comment]
Hi,

that´s the most anticipated feature and we know about that.
If my informations are correct the development will (at least) start this year (finally).

It will be the next big milestone of the mailcow Suite.

**Comment by DerLinkman** [comment]
Duplicate of: https://github.com/mailcow/mailcow-dockerized/issues/2316

**Comment by MAGICCC** [comment]
Also we dont develop SOGo directly

**Comment by Raffael93** [comment]
Thx for your replies :)

**Comment by andryyy** [comment]
My plan a while ago was to write a controller in LUA in dovecot for maximum flexibility regarding the authentication process. Could also be a HTTPS endpoint for even more connectors to use it.

Let’s see…
Simple LDAP synchronizers —> mailcow already exist.

**Comment by Raffael93** [comment]
I test the ldap sync of Programmierus, and it didn't work.

So if you have another ldap sync.
