### ISSUE TITLE
Add CORS headers to API responses

### ISSUE THREAD

**Issue by firstdorsal** [mailcow/mailcow-dockerized#4636]
### Summary

Currently it looks like CORS is not supported when using the API resulting in it not beeing usable from the browser if the origin of the site is different from the mailcow domain.

### Motivation

It would be awesome if a browser UI could directly contact the mailcow API without setting up a reverse proxy solution to add the missing headers.

**Comment by andryyy** [comment]
Hi, can you elaborate on „ if the origin of the site is different from the mailcow domain“?

Perhaps an example?

**Comment by firstdorsal** [comment]
I have a web UI hosted at `some-ui.example.com` and a mailcow instance with the domain `mx.example.com` and want to use the mailcow API directly from the browser UI located at `some-ui.example.com`. This is as far as I can see not possible because the cross origin request is blocked because no  `Access-Control-Allow-Origin` header is set by the mailcow API.

Following headers would be required for a cross origin request to work:

`Access-Control-Allow-Origin: *`
`Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT`
`Access-Control-Allow-Headers: X-Api-Key, Content-Type`


Thank you for creating mailcow <3

**Comment by andryyy** [comment]
Thanks, we will look into it. :)
