### ISSUE TITLE
Colorblind enhancement

### ISSUE THREAD

**Issue by zugazagoitia** [mailcow/mailcow-dockerized#4639]
### Summary

The green dots indicating container status are pretty hard to differentiate from the red ones for people suffering from deuteranomaly.

https://github.com/mailcow/mailcow-dockerized/blob/5d14baa43a433638dc9500866039eea1546ed926/data/web/templates/debug.twig#L94

 A posible solution would be to display a red cross symbol when they're down and a green checkmark when they're up. Leveraging shapes/patterns instead of colors is the easiest solution to improve accesibility.

### Motivation

People with color deficiencies such as myself will be able to differentiate container status.

**Comment by DerLinkman** [comment]
Hi there,

Thanks for that report! That is a good idea, but it will probably included in the Bootstrap 5 Update im July/August Not prior since this will overhaul the UI anyways.

@FreddleSpl0it is the man for this here 😉

**Comment by zugazagoitia** [comment]
Sure, no rush, just something to keep in mind while designing. I understand it can be easily overlooked by someone who does not have any color vision deficiency. Let me know if you need some help with it @FreddleSpl0it .

**Comment by MAGICCC** [comment]
What about a toggle in the UI to enable  colorblindmode to all kinds of buttons/sliders? Like in videogames

**Comment by zugazagoitia** [comment]
> What about a toggle in the UI to enable  colorblindmode to all kinds of buttons/sliders? Like in videogames

I believe the best solution would be to use a different icon for different states. Changing colors is more complex due to the different palettes required for different kinds of color blindness. 

Also, it would not be quite visual, we are used to green for success and red for failure, any different combination would be a little weird. 

That said, this feature could be toggled, but I see no point in doing that if regular colors are unchanged.

**Comment by FreddleSpl0it** [comment]
I'm with @zugazagoitia. The easiest way is to find the spots that are hard to see for colorblind people and tweak them.
In this case a icon is the better choice than a color to signal a status.

If you have more spots like this, feel free to post them here and I'll adjust the UI accordingly :)

**Comment by zugazagoitia** [comment]
> I'm with @zugazagoitia. The easiest way is to find the spots that are hard to see for colorblind people and tweak them.
> In this case a icon is the better choice than a color to signal a status.
> 
> If you have more spots like this, feel free to post them here and I'll adjust the UI accordingly :)

Haven't found any more so far, but I'll let you know if I do. Thanks :)

**Comment by MAGICCC** [comment]
> > What about a toggle in the UI to enable  colorblindmode to all kinds of buttons/sliders? Like in videogames
> 
> I believe the best solution would be to use a different icon for different states. Changing colors is more complex due to the different palettes required for different kinds of color blindness.


Actually I was refering to the spam rating slider
![image](https://user-images.githubusercontent.com/3279213/175825214-d4c9ff93-e87b-4f7b-bccf-46a7da881be5.png)

**Comment by zugazagoitia** [comment]
Fixed in #4910
