### ISSUE TITLE
syncjob: existence of account should be also tested against imap hostname

### ISSUE THREAD

**Issue by asirinelli** [mailcow/mailcow-dockerized#464]
At the moment, you cannot add 2 IMAP Sync tasks with the same username on 2 different servers.

If I add the sync job for username joe on server imap.server1.org, I cannot add a new sync job for username joe on server imap.server2.org. This is coming from inc/functions.mailbox.inc.php at line 138 (https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.mailbox.inc.php#L138):
```
$stmt = $pdo->prepare("SELECT `user2`, `user1` FROM `imapsync`
     WHERE `user2` = :user2 AND `user1` = :user1");
$stmt->execute(array(':user1' => $user1, ':user2' => $username));
```

Only the username is checked for duplicate. host1 should also be included in the WHERE statement.

**Comment by andryyy** [comment]
Thanks!
