### ISSUE TITLE
[Sync Jobs] Remove default selection for target mailbox

### ISSUE THREAD

**Issue by RafaelKr** [mailcow/mailcow-dockerized#4642]
### Summary

Please remove the default selection for the Username-field when creating a new sync job.

### Motivation

It should never happen that a sync job accidentally syncs to a wrong mailbox because someone forgets to select the correct target mailbox.

### Additional context

![image](https://user-images.githubusercontent.com/14234815/175284751-8357edfc-7245-448b-a04e-e44a99bf2578.png)

The username should have no pre-selection. The user should be forced to select it manually.
Currently all fields are also remembered when the Modal is closed and opened again, also after creating a new sync job. I think the Username-field should always be cleared when the modal is opened.
Remembering the other fields is fine, this is helpful when creating Sync Jobs for multiple mailboxes from the same source system.

**Comment by andryyy** [comment]
```
diff --git a/data/web/templates/modals/mailbox.twig b/data/web/templates/modals/mailbox.twig
index 4097145f..17e06ed2 100644
--- a/data/web/templates/modals/mailbox.twig
+++ b/data/web/templates/modals/mailbox.twig
@@ -435,11 +435,11 @@
       </div>
       <div class="modal-body">
         <p class="help-block">{{ lang.add.syncjob_hint }}</p>
-        <form class="form-horizontal" data-cached-form="true" role="form" data-id="add_syncjob">
+        <form class="form-horizontal" data-cached-form="false" role="form" data-id="add_syncjob">
           <div class="form-group">
             <label class="control-label col-sm-2" for="username">{{ lang.add.username }}</label>
             <div class="col-sm-10">
-              <select data-live-search="true" name="username" required>
+              <select data-live-search="true" name="username" title="{{ lang.add.select }}" required>
                 {% for mailbox in mailboxes %}
                   <option>{{ mailbox }}</option>
                 {% endfor %}
```

This should work.

**Comment by RafaelKr** [comment]
@andryyy Works good for me :+1: 

@FreddleSpl0it if you want I can create an PR for that. Just let me know.

**Comment by FreddleSpl0it** [comment]
@RafaelKr would be nice if you could do that

**Comment by andryyy** [comment]
Closed by https://github.com/mailcow/mailcow-dockerized/pull/4661
