### ISSUE TITLE
Cannot find docker-compose

### ISSUE THREAD

**Issue by Robin-Marquardt** [mailcow/mailcow-dockerized#4646]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

After update to 2022-6b i see the following error

|18:45:17|root@mail01:[mailcow-dockerized]> ./generate_config.sh
Cannot find docker-compose, exiting...

### Logs

```bash
|18:45:17|root@mail01:[mailcow-dockerized]> ./generate_config.sh
Cannot find docker-compose, exiting...
```

### Steps to reproduce

git pull newest repository

### System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 11 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB 4Cores |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | no version |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-06b |
| Reverse proxy (custom solution) | no |

**Comment by DerLinkman** [comment]
What did you did to solve it?

**Comment by Robin-Marquardt** [comment]
i install docker-compose like:
curl -L https://github.com/docker/compose/releases/download/v$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

the new docker compose command is not supported

**Comment by DerLinkman** [comment]
Yeah not anymore. It is needed to let mailcow run the internal commands.
