### ISSUE TITLE
Problems with letsencrypt

### ISSUE THREAD

**Issue by rucksman** [mailcow/mailcow-dockerized#465]
Finally I managed to get the Docker version up and running. But there is a problem with letsencrypt. If I want to open mail.mydomain.com I get a warning that it is an insecure connection. If I look at the certificate in Firefox, it says that it is issued for (CN) "mail.example.org" and the organization (O) is "mailcow". Obviously this is wrong. Starting the container shows no errors. Where can I check what went wrong?

**Comment by andryyy** [comment]
Can you check `docker-compose logs acme-mailcow` and post the (censored) output?

**Comment by rucksman** [comment]
Sorry, my bad. Was a silly error in my server configuration. Everthing works fine now. Only problem is that this version will not work on some/most (paravirtualized OpenVZ) vserver as usually the host uses an older custom kernel with patches which is not compatible with docker.
