### ISSUE TITLE
Last update.sh changes and compose v2 fail

### ISSUE THREAD

**Issue by SecT0uch** [mailcow/mailcow-dockerized#4650]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

See https://github.com/mailcow/mailcow-dockerized/commit/5d14baa43a433638dc9500866039eea1546ed926#commitcomment-76922504

### Logs

```bash
$ sudo ./update.sh
checking docker compose version...
Found Compose v2!
Checking internet connection... OK
Checking for newer update script...
remote: Enumerating objects: 1271, done.
remote: Counting objects: 100% (1110/1110), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 1271 (delta 926), reused 1089 (delta 917), pack-reused 161
Receiving objects: 100% (1271/1271), 1.67 MiB | 0 bytes/s, done.
Resolving deltas: 100% (992/992), completed with 87 local objects.
From https://github.com/mailcow/mailcow-dockerized
   5d14baa..a835419  master     -> origin/master
 * [new branch]      feature/bootstrap5 -> origin/feature/bootstrap5
 * [new branch]      feature/dovecot-2.3.19.1 -> origin/feature/dovecot-2.3.19.1
 * [new branch]      feature/imapsync -> origin/feature/imapsync
   e1db347..a49305f  hotfix     -> origin/hotfix
 * [new branch]      sogo-5.7.0 -> origin/sogo-5.7.0
   5d14baa..a835419  staging    -> origin/staging
 * [new branch]      weblate-translated -> origin/weblate-translated
 * [new tag]         2022-06b   -> 2022-06b
From https://github.com/mailcow/mailcow-dockerized
 * [new tag]         2022-06a   -> 2022-06a
update.sh changed, please run this script again, exiting.
```

```
$ sudo ./update.sh
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
Cannot find docker-compose Standalone. Installing...
######################################################################## 100.0%
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
Cannot find docker-compose Standalone. Installing...
######################################################################## 100.0%
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
Cannot find docker-compose Standalone. Installing...
######################################################################## 100.0%
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
Cannot find docker-compose Standalone. Installing...
######################################################################## 100.0%
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
Cannot find docker-compose Standalone. Installing...
######################################################################## 100.0%
Checking internet connection... OK
Checking for newer update script...
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Great! Native IPv6 NAT is active.
Fetching new docker-compose version...
Trying to determine GLIBC version...
which: no pip in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
######################################################################## 100.0%
./update.sh: line 258: docker-compose: command not found
which: no docker-compose in (/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin)
WARNING:  is not writable, but new version 2.6.0 is available (installed: )
Validating docker-compose stack configuration...
./update.sh: line 663: docker-compose: command not found

Oh no, something went wrong. Please check the error message above.
```

### Steps to reproduce

* Update to docker compose v2.
* Get rid of v1
* run `update.sh`

### System information

| Question | Answer |
| --- | --- |
| My operating system | Centos 7 |
| Is Apparmor, SELinux or similar active? | No |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose (v1) version (`docker-compose version`) | Not installled |
| docker compose (v2) version (`docker compose version`) | v2.6.0 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-06b |
| Reverse proxy (custom solution) | nginx |

**Comment by DerLinkman** [comment]
Please tell us any System Informations at least...

**Comment by DerLinkman** [comment]
You know need docker-compose to run mailcow as we rollback the previously option to choose which docker-compose you can install.

**Comment by DerLinkman** [comment]
```
curl -L https://github.com/docker/compose/releases/download/v$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by SecT0uch** [comment]
Why this rollback from v2 to v1 ? Is there a technical reason ?

I've updated the system details accordingly.

**Comment by DerLinkman** [comment]
There is no rollback it is 2.6.0 its only the old installation type.

**Comment by SecT0uch** [comment]
Indeed, it seems there is now a standalone `docker-compose` v2.

I think your update.sh is missing the `ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose` command.

Thanks
