### ISSUE TITLE
netfilter-mailcow endlessly adding NAT rules

### ISSUE THREAD

**Issue by beerlao** [mailcow/mailcow-dockerized#4658]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I noticed that server.py from netfilter-mailcow causes high CPU load on my system which seems to be caused by netfilter-mailcow endlessly adding the same POSTROUTING rule over and over.

❯ docker compose exec netfilter-mailcow sh
/ # iptables -L -vn -t nat | wc -l
36043
/ # iptables -L -vn -t nat | less
Chain PREROUTING (policy ACCEPT 36 packets, 2297 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 10 packets, 542 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 8 packets, 942 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 24 packets, 1970 bytes)
 pkts bytes target     prot opt in     out     source               destination
    4   247 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
    6   480 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
    0     0 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
  300 26237 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
    7   530 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
    1    60 SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:[MY_PUBLIC_IP#]
[36.000 rules following...]

### Logs

```bash
❯ docker-compose logs netfilter-mailcow
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
mailcowdockerized-netfilter-mailcow-1  | Added POSTROUTING rule for source network 172.22.1.0/255.255.255.0 to SNAT target [MY_PUBLIC_IP#]
[...]
```

### Steps to reproduce

Just start mailcow.

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 22.04 LTS |
| Is Apparmor, SELinux or similar active? | AppArmor |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | 32GB, 8 CPU |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | v2.6.0 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-06b |
| Reverse proxy (custom solution) | NGINX |

**Comment by ghost** [comment]
Same issue here. :)

**Comment by beerlao** [comment]
It seems that only the IPV4 part is affected. While (from server.py)

`if get_snat4_rule() not in chain.rules:`

doesn't find a rule (although the POSTROUTING chain is flooded with the same rule)

`if get_snat6_rule() not in chain.rules:`

works as intended: Only 1 rule present.

**Comment by stAn47** [comment]
hmm, same issue here

**Comment by stAn47** [comment]
i've added a quick fix for now: 
```
iptables-save | uniq | iptables-restore
```

**Comment by Shuro** [comment]
> i've added a quick fix for now:
> 
> ```
> iptables-save | uniq | iptables-restore
> ```

Thanks for the work around, my iptables blocked new entries, due to the ~190k entries from mailcow.

**Comment by beerlao** [comment]
> i've added a quick fix for now:
> 
> ```
> iptables-save | uniq | iptables-restore
> ```

server.py keeps adding this rule every 10 seconds, so you have to this regularly. I added a cronjob to my system:
```
*1      *       *       *       *       cd $MAILCOW_DIR; /usr/bin/docker compose exec -T netfilter-mailcow sh -c "/sbin/iptables-save | uniq | /sbin/iptables-restore"
```

So this one runs every minute. YMMW. Really a dirty workaround, but my python knowlegde is too bad to figure out why this rule is not catched by the server.py script.

**Comment by MAGICCC** [comment]
I'll close this issue in favor of https://github.com/mailcow/mailcow-dockerized/issues/4697
