### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#466]
Hello,
where can i change, that mailcow use apache and not nginx.
Fabian

**Comment by andryyy** [comment]
Hi,
Just use a reverse proxy. The mailcow Nginx is just meant for mailcow. There is a chapter in the docs for it. :-)
André

**Comment by ghost** [comment]
Hello,
thank you very much for your respone. But sorry i don't really understand what you mean. While i installed mailcow he brings me an error while do "docker-compose up -d". There was something with nginx. And becouse of i dont have nginx on my server [atm i use apache] i think this is the error an i must use nginx. What must i do for using apache?  =D

**Comment by Tcharl** [comment]
Hi,
@andryyy said that you can configure your Apache server to redirect requests and response from the mailcow nginx server: your apache will act as a passthrough between the web and mailcow (the nginx frontend). This is called [reverse proxying](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension).

**Comment by levinuss** [comment]
@DapeDope To use a reverse proxy you have to get the nginx container running. Did you change the ports nginx binds to? What was the exact error message?

**Comment by ghost** [comment]
The error ist becouse the port 80 is alredy in use. Should i chnace the port for mailcow gnix?

**Comment by ghost** [comment]
@levinus As soon as apache or nginx is installed, it causes an error in the mailcow installation. With this command: [docker-compose up -d]

**Comment by andryyy** [comment]
That's part of said documentation.

**Comment by ghost** [comment]
@andryyy Yea i understand but which file must i edit in apache for [this](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#apache-24)?

**Comment by DapeDope** [comment]
![1](https://user-images.githubusercontent.com/30322395/28475255-d211b56e-6e4b-11e7-94c4-50cb47af05ec.PNG)
![2](https://user-images.githubusercontent.com/30322395/28475257-d24070de-6e4b-11e7-8715-74b949082550.PNG)
![3](https://user-images.githubusercontent.com/30322395/28475256-d23bd0c4-6e4b-11e7-8c95-1eb24f9787c0.PNG)

This is, what i done.

**Comment by levinuss** [comment]
Usually the file mentioned in the docs is located in (at least on every debian-based system I saw at this point)
```
/etc/apache2/sites-available/
```
You can create a new file in that directory and enable it (say that apache should actually read the conf) with 
```
a2ensite YOUR-CONF-NAME
```
or you can use the default site file (something like 000-default.conf on my system) and add the lines there.

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/30322395/28475518-e0ba651a-6e4c-11e7-860b-6bfa6e2e4b93.PNG)
![2](https://user-images.githubusercontent.com/30322395/28475520-e0be8a3c-6e4c-11e7-9b33-1f07e6b9334d.PNG)
![3](https://user-images.githubusercontent.com/30322395/28475519-e0bd7bf6-6e4c-11e7-9d61-b5ae3d1679ac.PNG)

Okay, I did this but now he brings me another error. And the apache server is no longer accessible via the internet. @levinus

**Comment by levinuss** [comment]
@DapeDope First, you should edit the content of the config file you copied. This is NOT just a copy-paste conf. You have to adjust it to fit your needs. For example ```example.org``` should be replaced by your real domain and you should insert your SSL config and remove the ```[...]``` chars. 
Second, it seems like you have a local MTA running that blocks port 25. MC-Postfix will need port 25 to work.

**Comment by ghost** [comment]
<VirtualHost *:443>
    ServerName mail.mydomain.de
    ServerAlias autodiscover.mydomain.de
    ServerAlias autoconfig.mydomain.de

    # You should proxy to a plain HTTP session to offload SSL processing
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/

    ProxyPreserveHost On
    ProxyAddHeaders On

    # This header does not need to be set when using http
    # RequestHeader set X-Forwarded-Proto "https"

    your-ssl-configuration-here

    # If you plan to proxy to a HTTPS host:
    #SSLProxyEngine On

    # If you plan to proxy to an untrusted HTTPS host:
    #SSLProxyVerify none
    #SSLProxyCheckPeerCN off
    #SSLProxyCheckPeerName off
    #SSLProxyCheckPeerExpire off
</VirtualHost>


@levinus ty for your answer. =D If i don't want to use https is this configuration right?

**Comment by levinuss** [comment]
@DapeDope Not using HTTPS is not recommended! All your passwords, cookies and also Mails if you don't use TLS in Postfix and Dovecot (in the latest version mailcow uses TLS automatically for postfix and dovecot, you can use the generated certificate for your webserver).
If you really want to use unencrypted HTTP you will have to adjust the port in the ```<VirtualHost *:443>```. It has to be ```*:80``` because thats the default port for unencrypted HTTP. Also, you will have to remove the line with ```your-ssl-configuration-here```. The rest should work if you don't forget the closing tag.

**Comment by ghost** [comment]
@levinus Okay, after I changed the apache conf as in the screen, I get no more error. But the mailcow subdomain [mail.mydomain.de] does not work. Do you know what this is? And by the way, thank you for helping me. ^^

![1](https://user-images.githubusercontent.com/30322395/28489149-abe0b6cc-6ebb-11e7-8f36-32dfed01d735.PNG)
![2](https://user-images.githubusercontent.com/30322395/28489151-ac0cfdcc-6ebb-11e7-8464-c6b8cd924b05.PNG)

**Comment by levinuss** [comment]
@DapeDope It looks like you didn't made the changed I requested. Please change the port and remove the line as I said above. You could also but a '#' before the line above ```your-ssl-conf...```.
Does apache run without errors when the config is like this?

**Comment by ghost** [comment]
@levinus Okay, I've removed the line. Should I now copy content of <VirtualHost *: 443> to <VirtualHost *: 80> and relet the <VirtualHost *: 443> tag? Or do I understand the wrong? And apache doesn't run without errors. The webpage isn't reachable.
![1](https://user-images.githubusercontent.com/30322395/28489289-0aff2f9e-6ec1-11e7-8849-601546bf6e39.PNG)
![2](https://user-images.githubusercontent.com/30322395/28489291-0b059e38-6ec1-11e7-94dc-5a98245ee18f.PNG)
![3](https://user-images.githubusercontent.com/30322395/28489290-0b01c1b4-6ec1-11e7-94fe-cf727e728cff.PNG)
![4](https://user-images.githubusercontent.com/30322395/28489292-0b06eaea-6ec1-11e7-8ec9-e254401e417f.PNG)

**Comment by levinuss** [comment]
@DapeDope You can just change the 443 in the tag to 80. If apache runs into errors again please run ```systemctl status apache2``` and send the output.

**Comment by ghost** [comment]
@levinus Okay i done it like this and here is the log.

![1](https://user-images.githubusercontent.com/30322395/28489437-2da28084-6ec4-11e7-8339-950c52a90a77.PNG)
![2](https://user-images.githubusercontent.com/30322395/28489438-2da3e078-6ec4-11e7-9bfc-2fd197b5ba45.PNG)

**Comment by levinuss** [comment]
@DapeDope Looks like your apache proxy module isnt enabled. Try ```a2enmod proxy``` and then start again.

**Comment by ghost** [comment]
@levinus Okay ^^ yea now i can acces my webserver again via web but with mail.mydomain.de is a i think it was 500 bad gateway error. Is it possible for you to talk @ discord an have a look with anydesk to my server? o.O

**Comment by ghost** [comment]
@levinus This is now the error. My normal webserver is reachable.

![1](https://user-images.githubusercontent.com/30322395/28490408-a577cdd4-6ed9-11e7-8b33-f6c2b271c9ce.PNG)

**Comment by levinuss** [comment]
I don't think I can join you for a talk today, maybe tomorrow if the problem isn't solved until them. What does ```/var/apache2/error.log``` say?

**Comment by ghost** [comment]
@levinus In the first screen you see again my apache configuration. In the second you see the output after [docker-compose up -d] and [here](https://ghostbin.com/paste/qk5oc) is the apache error log.

![1](https://user-images.githubusercontent.com/30322395/28491269-7bd44e3e-6eee-11e7-96e5-05f42d4ed140.PNG)
![2](https://user-images.githubusercontent.com/30322395/28491270-7bd87bee-6eee-11e7-8ebd-ecb964f717c5.PNG)

**Comment by cwildfoerster** [comment]
I don't like to sound rude or something like that, but not understanding basic apache configuration and networking are not a good start to host something as important and security-relevant as a mailserver.

**Comment by Braintelligence** [comment]
@cwildfoerster On the other side of the coin I guess that many of us learned by doing and by trial and error, though. 
I agree that playing around with setting up something like WordPress in a docker environment with a reverse proxy should be no problem before starting a mailcow instance.

**Comment by ghost** [comment]
@cwildfoerster For me mailcow is only for fun and learning. I don't want to use mailcow for important emails or something like that. ^^

**Comment by ghost** [comment]
@levinus Can you help me by anydesk? I'm despairing. ^^
