### ISSUE TITLE
Update broke nginx instance 

### ISSUE THREAD

**Issue by dawid-woitaschek** [mailcow/mailcow-dockerized#4663]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Hi,

I do have an urgent problem right after a mailcow update today... Seems like it broke nginx ports:

```ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx-mailcow.ports contains an invalid type, it should be a number, or an object
services.nginx-mailcow.ports contains an invalid type, it should be a number, or an object

Oh no, something went wrong. Please check the error message above.```



REDACTED FOR PRIVACY AND SECURITY
```

**Comment by dawid-woitaschek** [comment]
Okay guys, I just set HTTP_BIND to "0.0.0.0" as it was emtpy before and now it's working again - sorry!

**Comment by NoobKeksTV** [comment]
oh ye just got the same issue, and i changed it to say

`${HTTP_BIND:-0.0.0.0}`
`${HTTPS_BIND:-0.0.0.0}`

instead of

`${HTTP_BIND:-}`
`${HTTPS_BIND:-}`

now it works
