### ISSUE TITLE
create_cold_standby.sh not executable by default

### ISSUE THREAD

**Issue by markus-gitdev** [mailcow/mailcow-dockerized#4668]
### Summary

The script to create a cold standby (`create_cold_standby.sh`) is missing the executable permission by default.

### Motivation

If it was executable by default, it would "_just work_".

### Additional context

It's not a big deal, since everyone can change that with `chmod +x create_cold_standby.sh`, but it'd be nice if it was executable by default.

**Comment by MAGICCC** [comment]
PR done :)

**Comment by DerLinkman** [comment]
When did this happen? I guess it was executable by default previously but i don´t know when and where it stopped working ;)

**Comment by MAGICCC** [comment]
No idea, cant see a real commit history here on GitHub, maybe it was for `helper-scripts/_cold-standby.sh`?

**Comment by DerLinkman** [comment]
Oh wait, i just saw that this is about create-cold-standby XD I read: generate_config.sh.

But yeah. It´s fine anyways.

**Comment by andryyy** [comment]
I did it intentionally for people not to run it by accident.

See docs: https://mailcow.github.io/mailcow-dockerized-docs/backup_restore/b_n_r-coldstandby/#prepare

I wrote `bash blabla.sh`

Some people tend to use ./[tab] way to often. :)

But anyways, if you already merged, adjust the docs, please.
