### ISSUE TITLE
YubiKey and new TFA

### ISSUE THREAD

**Issue by markus-gitdev** [mailcow/mailcow-dockerized#4683]
### Summary

With the new TFA (that is also available for users, which is a great feature!) you now have to select which YubiKey to use to authenticate.
Before the TFA update, it was only needed to touch any of the registered YubiKeys to authenticate.

It'd be great if there was just an option called "YubiKey" and this works as before (without the need of selecting the right key).

### Motivation

Makes it easier to use.

**Comment by andryyy** [comment]
Yes, that should not have been changed. Can you check this @FreddleSpl0it

**Comment by FreddleSpl0it** [comment]
@markus-gitdev do you mean Yubikey with Webauthn or Yubikey OTP?

For Yubikey with Webauthn: The thing is, the Browser needs to see some real user interaction to allow the call to `navigator.credentials.get()`. Before the update a user had to click on start validation.

**Comment by markus-gitdev** [comment]
I meant YubiKey OTP. Webauthn still works as before.

![grafik](https://user-images.githubusercontent.com/82206269/179175730-4def75ab-3ac3-4ba7-8406-ff7934307612.png)

As you can see there are 2 YubiKeys registered, but it would be great if it was merged with just "YubiKey", so you don't have to select a specific YubiKey - just like it was before.

**Comment by MAGICCC** [comment]
I'll close this since https://github.com/mailcow/mailcow-dockerized/pull/4685 got merged and available in the latest update (2022-08)
