### ISSUE TITLE
Question: Update check to use in checkmk?

### ISSUE THREAD

**Issue by markus-gitdev** [mailcow/mailcow-dockerized#4686]
### Summary

It's possible to have an update check in [checkmk](https://checkmk.com/) (or similar monitoring solutions based on Nagios) for mailcow.

Here's what it can look like in checkmk:
- _No updates available_
  ![grafik](https://user-images.githubusercontent.com/82206269/179226402-dc442091-1be3-45e9-8e04-f35deff54822.png)
- _Updates available_
  ![grafik](https://user-images.githubusercontent.com/82206269/179226848-fae9aa6d-fd32-4b80-8aa9-79b9f8f1eab5.png)
- _Long check output_
  ![grafik](https://user-images.githubusercontent.com/82206269/179227005-1fd99509-150f-4965-ae39-d74bc25bddf9.png)
  _that contains ..._
  - _a link to the GitHub commits of mailcow (https://github.com/mailcow/mailcow-dockerized/commits/master), if updates are available_
  - _metrics (1 for updates available and 0 for no updates available_

So, my question: Is it in the interest of mailcow to implement such a functionality?
If yes, I'd create a pull request to get it merged and also create a short documentation on how to enable it on the system.

My idea:
Create the check in the folder helper-scripts and let the users, that want to use it, create a soft link in the needed checkmk folder on the system (could even be expanded like: if the checkmk folder exist on the system let the user decide during an update, if they want to enable such a functionality - not planned for now, but possible in the future).

### Motivation

As I monitor my servers and services, I wanted to know if there are updates available for them.
Since there is no check for mailcow so far, I decided to create my own and if others can profit from it too, they are welcome to use it.

**Comment by MAGICCC** [comment]
You can run update.sh script with --check parameter and see if theres an update available
https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh#L308-L322

**Comment by markus-gitdev** [comment]
I know, based on that I created this check and enhanced it by metrics, so it can be used in checkmk.

**Comment by andryyy** [comment]
This could be added to the docs.

**Comment by MAGICCC** [comment]
> I know, based on that I created this check and enhanced it by metrics, so it can be used in checkmk.

Sorry then I misunderstood you. But thanks for the PR in the docs
