### ISSUE TITLE
Postfix on host with relayhost not working

### ISSUE THREAD

**Issue by steffenabel** [mailcow/mailcow-dockerized#469]
Hi,

I'm trying to get mail from my host delivered via the mailcow containers, but I always get an error: "warning: relayhost configuration problem" and "mail for 172.22.1.1 loops back to myself".

I just installed postfix with no configuration and followed this instructions:
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/

Do you have any idea what's going wrong?

Thanks & Cheers
Steffen

**Comment by andryyy** [comment]
Hi,

I updated the docs. You need to remove the Docker interface from inet_interfaces.

**Comment by steffenabel** [comment]
Hi,
thanks for the quick reply. Now I'm getting an "5.0.0 bounced (172.22.1.1)" error when trying to send mails from the host. You got any ideal?

Thanks
Steffen

**Comment by lazyfrosch** [comment]
Have the same problem. The local Postfix does not even try to connect, but somehow assumes that the target would be a loop

**Comment by lazyfrosch** [comment]
Debian seems to install the following lines, when you decide not to configure Postfix:

    default_transport = error
    relay_transport = error

When I remove them the error looks like:

    <markus@lazyfrosch.de>: mail for 172.22.1.1 loops back to myself

Now Postfix found a loop, in my case bc `mail.lazyfrosch.de` is also the hostname/mailname of the Docker host. When you change the Postfix hostname (not origin), he will forward the mail to the relay host:

    myhostname = localhost.mail.lazyfrosch.de

**Comment by steffenabel** [comment]
@lazyfrosch: the removal of these two lines fixed my problems, thanks.

**Comment by mamair** [comment]
I have a problem too.

I installed sympa. Sending mail with the changes in postfix described above works fine. But I cant receive E-Mails in sympa. I only get mail back with "mail for lists.xxxxxxx.at loops back to myself".

Mailcow Server domain is lists.xxxxxxx.at and wosks fine too.

How does mailcow know to relay which incoming mails to the local mta?
