### ISSUE TITLE
More `SRV` records (`RF 6186`)

### ISSUE THREAD

**Issue by strarsis** [mailcow/mailcow-dockerized#4700]
### Summary

`RFC 6186` lists multiple DNS `SRV` records, one for each mail protocol:
- `_autodiscover._tcp`
- `_imaps._tcp`
- `_imap._tcp`
- `_pop3s._tcp`
- `_pop3._tcp`
- `_submission._tcp`

`_autodiscover._tcp` is already proposed by Mailcow as recommended `SRV` record, but not the other ones, as `_imap._tcp`?

### Motivation

E-Mail clients may not all support `autodiscovery` or `autoconfig`, but the email-protocol-specific `SRV` records instead.
Also adding these records can increase the compatibility for these email clients to properly auto-configure.

### Additional context
https://mailcow.github.io/mailcow-dockerized-docs/manual-guides/u_e-autodiscover_config/

**Comment by accolon** [comment]
The SRV records you are mentioning are already recommended here:
https://mailcow.github.io/mailcow-dockerized-docs/prerequisite/prerequisite-dns/#the-advanced-dns-configuration

**Comment by strarsis** [comment]
That's great! Could those records also be added to the DNS check window in the mailcow UI?

**Comment by andryyy** [comment]
No, they are barely used. We moved it to the docs for this reason.
