### ISSUE TITLE
user-friendly url structure

### ISSUE THREAD

**Issue by KiaraGrouwstra** [mailcow/mailcow-dockerized#4702]
### Summary

right now, the url structure appears to be:

- `$DOMAIN` for the admin login, which then directs to `$DOMAIN/admin`
- `$DOMAIN/SOGo/` for the end-user login

### Motivation

generally end-users will outnumber administrators.

as such, i would argue it might make more sense to design the url structure user-first, rather than admin-first.
to that end, i would rather see the urls as:

- `$DOMAIN/admin` for the admin interface/login
- `$DOMAIN/` for the end-user login, for migration purposes perhaps with a redirect from `$DOMAIN/SOGo/`

**Comment by MAGICCC** [comment]
Its not an [admin only login](https://github.com/mailcow/mailcow-dockerized/issues/393#issuecomment-582562480). Users should also login to the UI to be able to change some settings.
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/393

Also see https://mailcow.github.io/mailcow-dockerized-docs/manual-guides/Nginx/u_e-nginx_webmail-site/
