### ISSUE TITLE
ACME failing after updating

### ISSUE THREAD

**Issue by AudiWolf** [mailcow/mailcow-dockerized#4709]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

After updating to the current version, the acme container is not able to issue a certificate becaus he cant solve my dens to my ipv6 adress. 

### Logs

```bash
10.08.2022, 23:41:12 mail.domain.tld - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
10.08.2022, 23:41:12 mail.domain.tld - Cannot validate any hostnames, skipping Let's Encrypt for 1 hour.
10.08.2022, 23:41:12 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname mail.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:12 mail.domain.tld - Found AAAA record for mail.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:12 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autoconfig.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:12 mail.domain.tld - Found AAAA record for autoconfig.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:12 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autodiscover.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:12 mail.domain.tld - Found AAAA record for autodiscover.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:12 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname mta-sts.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:12 mail.domain.tld - Found AAAA record for mta-sts.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:12 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autoconfig.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:11 mail.domain.tld - Found AAAA record for autoconfig.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:11 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autodiscover.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:11 mail.domain.tld - Found AAAA record for autodiscover.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:11 mail.domain.tld - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname mta-sts.domain.tld (DNS returned XXXX:YYYY:XXXX:YYYY:0000:0000:0000:0001)
10.08.2022, 23:41:11 mail.domain.tld - Found AAAA record for mta-sts.domain.tld: 2a01:4f8:1c1e:d0ba::1 - skipping A record check
10.08.2022, 23:41:11 mail.domain.tld - OK: abc.def.efg.hij, 0000:0000:0000:0000:0000:0000:0000:0000
10.08.2022, 23:40:32 mail.domain.tld - Detecting IP addresses...
10.08.2022, 23:40:32 mail.domain.tld - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
10.08.2022, 23:40:32 mail.domain.tld - Using existing domain rsa key /var/lib/acme/acme/key.pem
10.08.2022, 23:40:32 mail.domain.tld - Initializing, please wait...
10.08.2022, 23:40:32 mail.domain.tld - OK
```

### Steps to reproduce

open ssh
docker-compose logs --tail=200 -f acme-mailcow
read the log

### System information

Debian 11 on Hetzner server.
Current Stable version of Mailcow

**Comment by speedmann** [comment]
Same here, the hostname resolves to a link local address and therefore does not match the DNS record

**Comment by andryyy** [comment]
There are logs of which some line indicates the IP address detection failure.
Please also post full outputs. :)

If it would return a link local address, the internal DNS is not used, or you put a link local address in the zone which would be not… ideal.

So both of you face different problems.

Please also always use the whole issue template. This is incomplete and might have been solved with all information. 👍

**Comment by speedmann** [comment]
> There are logs of which some line indicates the IP address detection failure. Please also post full outputs. :)
> 
> If it would return a link local address, the internal DNS is not used, or you put a link local address in the zone which would be not… ideal.
> 
> So both of you face different problems.
> 
> Please also always use the whole issue template. This is incomplete and might have been solved with all information. 👍

oh sorry, you're right. i will open a new issue for that

**Comment by AudiWolf** [comment]
Sorry that I have not given a proper description. In my case it is solved, there was a mistake in my Network configuration. Now it is working again.
