### ISSUE TITLE
554 Failed

### ISSUE THREAD

**Issue by alaarihan** [mailcow/mailcow-dockerized#471]
We have an issue, we can't send emails to some addresses but the other addresses receive our email normally 

this is the report we receive when we try to send 
This is the mail system at host mail.bravocontrols.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<andyevans@summitmechanical.net>: host
    summitmechanical.net.mx1.inddc.rcimx.net[208.80.204.98] said: 554 Failed:
    Malformed MIME field: ARC-Message-Signature: i=1; a=rsa-sha256;
    c=relaxed/relaxed [0x0D] ... (in reply to end of DATA command)

**Comment by RobinFlikkema** [comment]
I'm not really sure but my guess is that the receiving mailserver doesn't know what ARC Message Signature is and fails because of that.

**Comment by alaarihan** [comment]
I think it was SPF record mistake, It has fixed now, thank you
