### ISSUE TITLE
[French-related] Javascript error leading to frozen page when editing an alias

### ISSUE THREAD

**Issue by ro78** [mailcow/mailcow-dockerized#4718]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Hello,

When I edit an alias with Mailcow GUI in French, after clicking on Save, I'm blocked on the edit page.
If I check the console log, I have:
`Uncaught SyntaxError: missing ) after argument list (at 20:469:27)`

If I open this line:
`mailcow_alert_box('Le changement de l'adresse alias [myalias] a été sauvegardée', 'success');`

The ' in "l'adresse" is breaking the behavior of the "save" redirection. It might not be the only place. We should "addslashes" to the value of the translation.

### Logs

```bash
N/A
```

### Steps to reproduce

1. Put Mailcow GUI in French
2. Edit an existing alias
3. Press Save

### System information

| Question | Answer |
| --- | --- |
| My operating system | N/A |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | No |
| Server/VM specifications (Memory, CPU Cores) | N/A |
| Docker version (`docker version`) | N/A |
| docker-compose version (`docker-compose version`) | N/A |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-07a |
| Reverse proxy (custom solution) | N/A |

**Comment by ghost** [comment]
Nice one!

I can reproduce this on my instance (v2022-07a). Here is the interface right after saving the modifications:
https://user-images.githubusercontent.com/41020854/184909867-a415ace9-6f71-4f4d-928c-e4b78cbc6f5d.mov

**Comment by MAGICCC** [comment]
I guess the better fix would be to fix it in the main files and not in the translation files. Maybe something for @FreddleSpl0it?

**Comment by ro78** [comment]
Yes I think it should be fixed in the code (like with a "addslashes" function for quotes), French translation files must be able to contain this caracter without having to escape him like \'

**Comment by ro78** [comment]
Nobody?

**Comment by ro78** [comment]
I found how to fix it, I'll try to do a commit.
Else, in data\web\templates\base.twig line 175:
`mailcow_alert_box('{{ alert_msg|raw|e("js") }}', '{{ alert_type }}');`

**Comment by ro78** [comment]
@milkmaker can you try to make this added?

**Comment by ro78** [comment]
@DerLinkman

**Comment by DerLinkman** [comment]
Jup can confirm as well!

**Comment by DerLinkman** [comment]
Will be fixed in 2022-10a
