### ISSUE TITLE
Increase nginx server_names_hash_bucket_size

### ISSUE THREAD

**Issue by abyssox** [mailcow/mailcow-dockerized#472]
Hello,

i'm running mailcow on ubuntu 16.04 and i get this error when i restart nginx-mailcow:
`nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32`

Problem is that nginx can't build the server hash table if there are large numbers of server names and this value is too low.

http://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_bucket_size

Regards
calis2002

**Comment by abyssox** [comment]
No comment on this or how to fix this?

**Comment by andryyy** [comment]
It is strange it defaults to 32. I will increase it in a few mins!

**Comment by mwarth** [comment]
Sorry but i still get the same error message :/

**Comment by andryyy** [comment]
It is in dev. :-) Can you merge that new line in site.conf from dev? =>

``` 
server_names_hash_bucket_size 64;
```

As very first line in `data/conf/nginx/site.conf`.

**Comment by mwarth** [comment]
Ouch ouch ouch, sorry my fault. Edited the wrong site.conf the whole time. Of course it won't work then ^^
Works now ;)

**Comment by andryyy** [comment]
Nice! :-)
