### ISSUE TITLE
update.sh does incorrectly show newer docker-compose releases as older releases

### ISSUE THREAD

**Issue by GuidoDr** [mailcow/mailcow-dockerized#4721]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

the update.sh script does incorrectly show an older version of docker-compose as a newer release when a newer release of docker-compose is already installed on the server.
There should not be offered a downgrade as an upgrade ;-)

### Logs

```bash
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Great! Native IPv6 NAT is active.
#=#=-#    #
A new docker-compose Version is available: 2.9.0
Your Version is: 2.10.0
Do you want to update your docker-compose Version? It will automatic upgrade your docker-compose installation (recommended)? [y/N] N
```

### Steps to reproduce

just run the update.sh when you do already have installed the 2.10.0 docker-compose release on the server

### System information

Ubuntu 20.04 server with latest docker-compose installed

**Comment by DerLinkman** [comment]
This is not a bug so to say :)

Since it pulls the information from our hidden webserver.

We´ll probably automate this in the next few weeks.
