### ISSUE TITLE
Comments for temporary mail addresses

### ISSUE THREAD

**Issue by WEBDIENSTE** [mailcow/mailcow-dockerized#4728]
### Summary

It will be great if the feature "temporary mail adresses" have an opportunity to add comments, so the user will be able to notice to which one was a temporary mail address was given.

Thank you! 

### Motivation

This feature is a small change, but have a great impact for the user experience.

**Comment by MAGICCC** [comment]
I'll close this in favor of https://github.com/mailcow/mailcow-dockerized/issues/4730
