### ISSUE TITLE
White/blacklisting emails in mailcow UI has no effect

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#473]
I have whitelisted and backlisted a few addresses via the mailcow UI, but I still receive emails from the blacklisted addresses, and the whitelisted ones still get stuck in the spam filter after getting "soft rejected" by rspamd.

**Comment by andryyy** [comment]
Hi,
Can you please restart Rspamd by running `docker-compose restart rspamd-mailcow`?
Does it fix your problem?

If not: Please forward a mail that should be blacklisted to info@servercow.de and also send me the output of `docker-compose exec php-fpm-mailcow curl http://nginx:8081/settings.php` and `docker-compose logs --tail=1000 rspamd-mailcow`.
