### ISSUE TITLE
Add labels / description to 'temporary email addresses'

### ISSUE THREAD

**Issue by snevas** [mailcow/mailcow-dockerized#4730]
### Summary

Add action button to edit / add labels.

### Motivation

If you use a alias for a service (signup or purchase), you want to know **where** it leaked when you start to receive spam for that certain alias.
You could easily do the 'investigation' when you add the names of the services you've used the alias for.

### Additional context

I would not make it required or change the flow how you generate a alias. The way it works now is quick in making it, adding the description / label should not impact this.

**Comment by MAGICCC** [comment]
Also related to https://github.com/mailcow/mailcow-dockerized/issues/3947 and dupe of https://github.com/mailcow/mailcow-dockerized/issues/4728

**Comment by marekfilip** [comment]
Think #4407 is also about the same feature?

**Comment by snevas** [comment]
> Think #4407 is also about the same feature?

Right! Closing this one
