### ISSUE TITLE
docker compose doesn't support

### ISSUE THREAD

**Issue by neupaneanish** [mailcow/mailcow-dockerized#4735]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I have install docker and docker compose in rocky Linux from its official site. i.e https://docs.rockylinux.org/it/gemstones/docker/ 
and it has docker compose not docker-compose. While installing mailcow it show error.

### Logs

```bash
./generate_config.sh
/usr/bin/which: no docker-compose in (/root/.local/bin:/root/bin:/home/anish/.local/bin:/home/anish/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
```

### Steps to reproduce

1. Install Docker with new version of docker compose
2. Try to  generate and it will produce error

### System information

| Question | Answer |
| --- | --- |
| Docker version (`docker version`) | 20.10.17, build 100c701 |
| docker-compose version (`docker compose version`) |v2.6.0 |

**Comment by DerLinkman** [comment]
Template not used.

Please use the complete Template.
