### ISSUE TITLE
Dovecot is not running

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#474]
I have problem with IMAP (and maybe SMTP) containers. 

Today I came and RounCube says Connection to IMAP failed last message from Dovecot in log is: 

`Jul 26 15:45:01 mailserver CRON[113]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)` 

before restart, dovecot said: 
`Fatal: Dovecot is already running with PID 32 docker.`

Here are last 10 commands of every service in the log:

https://pastebin.com/GAS6Dkcw

HDD is not full, I tried to restart every single container and even the whole virtual mashine. I didn't touch the server last month at all.

Thanks for you help

**Comment by mkuron** [comment]
I also had that a few days ago after an unclean shutdown. The dovecot log will also mention a .pid file, near that "already running" line, which you need to delete manually before dovecot can be started again.

**Comment by DJIronic** [comment]
and what about the: 
dovecot-mailcow_1    | Jul 26 16:24:01 mailserver CRON[233]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)
 ? Now It´s not talking about any PID file after server restart.

and postfix is responding:


postfix-mailcow_1    | Jul 26 16:26:35 mailserver postfix/smtpd[395]: warning: SASL: Connect to inet:dovecot:10001 failed: Connection refused

**Comment by mkuron** [comment]
The imapsync message is fine, that runs periodically.

Postfix shows that message when it tries to deliver a message to Dovecot and fails to connect because Dovecot isn't running.

**Comment by DJIronic** [comment]
But when I restart the dovecot container, I will not get the PID error again. Just the CRON one and the POSTFIX error.

**Comment by andryyy** [comment]
Hm, I will add a check for it. You can also just run "docker-compose down" followed by "docker-compose up -d"

Beste Grüße 
André

**Comment by DJIronic** [comment]
Thanks, btw I found the log line:


dovecot-mailcow_1    | 2017-07-26 16:32:45 master: Fatal: Dovecot is already running with PID 32 (read from /var/run/dovecot/master.pid)

but the file /var/run/dovecot/master.pid does not exist in the folder it said...and it is not in the /home/mailcow-dockerized/data/Dockerfiles/dovecot folder so where can I find it?

**Comment by DJIronic** [comment]
//OK help form andryy worked. Thank you.

**Comment by andryyy** [comment]
You would need to remove it from the container. Either recreate the container (that's what you did) or run docker-compose exec dovecot-mailcow rm /var/something/file.pid

Containers are short-lived and can always be recreated from their image. All permanent data is stored outside in volumes.
