### ISSUE TITLE
Mailcow installation failed (docker-ce)

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#475]
Hello, i try to install mailcow with the documentation of mailcow.
i run this command: `curl -sSL https://get.docker.com/ | sh`

and the output is the following:
`OK:1 ftp://ftp.stratoserver.net/pub/linux/ubuntu xenial InRelease
OK:2 ftp://ftp.stratoserver.net/pub/linux/ubuntu xenial-updates InRelease
OK:3 ftp://ftp.stratoserver.net/pub/linux/ubuntu xenial-security InRelease
OK:4 ftp://ftp.stratoserver.net/pub/plesk/ubuntu/PSA_17.5.3 xenial InRelease
OK:5 https://download.docker.com/linux/ubuntu xenial InRelease
Paketlisten werden gelesen... Fertig
+ sh -c apt-get install -y -q apt-transport-https ca-certificates curl software-properties-common
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.20).
curl is already the newest version (7.47.0-1ubuntu2.2).
software-properties-common is already the newest version (0.96.20.7).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
docker-ce (17.06.0~ce-0~ubuntu) wird eingerichtet ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Do 2017-07-27 11:41:40 CEST; 4ms ago
     Docs: https://docs.docker.com
  Process: 25712 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 25712 (code=exited, status=1/FAILURE)
dpkg: Fehler beim Bearbeiten des Paketes docker-ce (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)`

I have an Ubuntu Server 16.04.2 and doesnt have an docker installation before

**Comment by andryyy** [comment]
`Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`

Did you do this?

Is it a OpenVZ machine?

**Comment by ClepToManix** [comment]
Yes the output is the following:
`docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: inactive (dead) (Result: exit-code) since Do 2017-07-27 11:47:04 CEST
     Docs: https://docs.docker.com
  Process: 25911 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAIL
 Main PID: 25911 (code=exited, status=1/FAILURE)
`

and from the journal there are only plesk, postfix and smtpd messages

Its a VPS Server from Strato.de

**Comment by andryyy** [comment]
You need to run journal -xe after systemctl restart docker.service

Also: Is it a OpenVZ machine?

**Comment by ClepToManix** [comment]
`Jul 27 12:27:16 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:16.650823793+02:00" level=info msg="libcontainerd: new containerd process, pid: 26111"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.656724182+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.657953352+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.666299390+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668839009+02:00" level=warning msg="Your kernel does not support oom control"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668861093+02:00" level=warning msg="Your kernel does not support memory swappiness"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668871135+02:00" level=warning msg="Your kernel does not support kernel memory limit"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668876522+02:00" level=warning msg="Unable to find cpu cgroup in mounts"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668904734+02:00" level=warning msg="Unable to find cpuset cgroup in mounts"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: time="2017-07-27T12:27:17.668936918+02:00" level=warning msg="mountpoint for pids not found"
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26104]: Error starting daemon: Devices cgroup isn't mounted
Jul 27 12:27:17 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:17.970815872+02:00" level=info msg="libcontainerd: new containerd process, pid: 26137"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.978041106+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.979287922+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.989823320+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992132255+02:00" level=warning msg="Your kernel does not support oom control"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992150077+02:00" level=warning msg="Your kernel does not support memory swappiness"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992159231+02:00" level=warning msg="Your kernel does not support kernel memory limit"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992164725+02:00" level=warning msg="Unable to find cpu cgroup in mounts"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992192105+02:00" level=warning msg="Unable to find cpuset cgroup in mounts"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: time="2017-07-27T12:27:18.992228171+02:00" level=warning msg="mountpoint for pids not found"
Jul 27 12:27:18 h2710636.stratoserver.net dockerd[26128]: Error starting daemon: Devices cgroup isn't mounted
Jul 27 12:27:19 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:19.469506641+02:00" level=info msg="libcontainerd: new containerd process, pid: 26155"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.477023024+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.478478715+02:00" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.483883831+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485488581+02:00" level=warning msg="Your kernel does not support oom control"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485505608+02:00" level=warning msg="Your kernel does not support memory swappiness"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485515070+02:00" level=warning msg="Your kernel does not support kernel memory limit"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485521259+02:00" level=warning msg="Unable to find cpu cgroup in mounts"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485548556+02:00" level=warning msg="Unable to find cpuset cgroup in mounts"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: time="2017-07-27T12:27:20.485597652+02:00" level=warning msg="mountpoint for pids not found"
Jul 27 12:27:20 h2710636.stratoserver.net dockerd[26149]: Error starting daemon: Devices cgroup isn't mounted
`
Thanks for your fast answear 👍

**Comment by ClepToManix** [comment]
edit: sorry dont read the last part :o 
i think its a OpenVZ Machine because the virtualization of Strato is with virtuozzo
@andryyy du kannst auch gerne deutsch schreiben ;)

**Comment by andryyy** [comment]
The kernel seems not to be able to handle Docker. Can you ask Strato if it does? :)

**Comment by stevesbrain** [comment]
Generally speaking, if it's an OpenVZ host you're probably out of lock (most don't include Docker support in their Kernels). Can confirm I've got Docker running on both Digital Ocean, and Linode VM's, if that helps at all :)

**Comment by ClepToManix** [comment]
I will create a ticket by strato. I dont know if it helps, but i have the option to install docker over my plesk. Is there an option to install mailcow over this docker-application?

**Comment by ClepToManix** [comment]
Have found an answear from strato
`Ein für den Betrieb notwendiges Kernel Modul steht auf den Virtual Server Kerneln leider nicht zur Verfügung und wird nach aktueller Planung in Zukunft auch nicht nachinstalliert werden. Daher ist für den Betrieb von Docker ein Dedicated Root Server notwendig.`

This mean that docker is not supported and wont be supported in future -.-

**Comment by ClepToManix** [comment]
I absolutely want to stay with mailcow, I simply install the 0.14. This I have also on my old server in use and runs super;)
Anyway thanks for the quick help and the great software @andryyy 👍
