### ISSUE TITLE
manifest for mailcow/sogo:1.111 not found @ Amoogust Update 2022 Revision B

### ISSUE THREAD

**Issue by snevas** [mailcow/mailcow-dockerized#4750]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

https://github.com/mailcow/mailcow-dockerized/releases/tag/2022-08b pulls mailcow/sogo:1.111, but is doesn't exist:
https://hub.docker.com/r/mailcow/sogo/tags

### Logs

```bash
Detecting which build your mailcow runs on...
You are receiving stable updates (master).
To change that run the update.sh Script one time with the --nightly parameter to switch to nightly builds.
Checking for newer update script...
Updated 0 paths from 5d584954
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Great! Native IPv6 NAT is active.
Validating docker-compose stack configuration...
Checking for conflicting bridges...
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Saving diff to update_diffs/diff_before_update_2022-09-08-13-12-18...
Prefetching images...
1.16: Pulling from mailcow/unbound
Digest: sha256:ff118ee2658b56ce5dab5d3bfdc2b652ef7fba732f634a78a99267d9aa60f41d
Status: Image is up to date for mailcow/unbound:1.16
docker.io/mailcow/unbound:1.16
10.5: Pulling from library/mariadb
Digest: sha256:cb223c17bab451f086e863be6c0ae044d91a475c2e0986a576fddc5ebd8b03c2
Status: Image is up to date for mariadb:10.5
docker.io/library/mariadb:10.5
6-alpine: Pulling from library/redis
Digest: sha256:fad643c78fadb65fdfe79e19a37b0923ae48e69b4a1e7c6be2e94e080f2554b4
Status: Image is up to date for redis:6-alpine
docker.io/library/redis:6-alpine
1.54: Pulling from mailcow/clamd
Digest: sha256:32b950276296f65bef38d95cd97e98b40aad4418c68523bba9749002cdfdef30
Status: Image is up to date for mailcow/clamd:1.54
docker.io/mailcow/clamd:1.54
1.90: Pulling from mailcow/rspamd
Digest: sha256:310b22157820e8e021f6c4f711f81f13ad012b185fd468e2d4a6d008da2855db
Status: Image is up to date for mailcow/rspamd:1.90
docker.io/mailcow/rspamd:1.90
1.79: Pulling from mailcow/phpfpm
Digest: sha256:d9d21292d125c256128bdddb4610f3d349967887f6592f03b801083091c01bff
Status: Image is up to date for mailcow/phpfpm:1.79
docker.io/mailcow/phpfpm:1.79
Error response from daemon: manifest for mailcow/sogo:1.111 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.111, retrying...
Error response from daemon: manifest for mailcow/sogo:1.111 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.111, retrying...
Error response from daemon: manifest for mailcow/sogo:1.111 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.111, retrying...
Error response from daemon: manifest for mailcow/sogo:1.111 not found: manifest unknown: manifest unknown

Error pulling mailcow/sogo:1.111, retrying...

Too many failed retries, exiting
```

### Steps to reproduce

1. Run update.sh

### System information

| Question | Answer |
| --- | --- |
| My operating system | I_DO_REPLY_HERE |
| Is Apparmor, SELinux or similar active? | I_DO_REPLY_HERE |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I_DO_REPLY_HERE |
| Server/VM specifications (Memory, CPU Cores) | I_DO_REPLY_HERE |
| Docker version (`docker version`) | I_DO_REPLY_HERE |
| docker-compose version (`docker-compose version`) | I_DO_REPLY_HERE |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | I_DO_REPLY_HERE |
| Reverse proxy (custom solution) | I_DO_REPLY_HERE |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
YOUR OUTPUT GOES HERE
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
YOUR OUTPUT GOES HERE
```

**Comment by snevas** [comment]
Pinging: https://github.com/mailcow/mailcow-dockerized/pull/4747

**Comment by wornet-aer** [comment]
We've just been running into the same error message. Is there any quick-fix or workaround yet?

**Comment by snevas** [comment]
update.sh leaves the current version running until everything is successfully pulled. Just keep using this version.
The whole point for this version was the new SoGo, there is no quick-fix until they release it.

**Comment by wornet-aer** [comment]
Update: just retried and now the pull of `mailcow/sogo:1.111` was successful. Seems like we've been updating just toooo fast. ;-)

**Comment by snevas** [comment]
Confirmed!
