### ISSUE TITLE
Sogo filters no longer work

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4751]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Sogo filters no longer work, since when I unfortunately do not know but have seen that there were problems with Sogo and have tested that times.

SEE SCREENSHOT:
https://imgur.com/a/0ZJLm7B

PS. Version: [2022-08b](https://github.com/mailcow/mailcow-dockerized/releases/tag/2022-08b)

### Logs

```bash
-
```

### Steps to reproduce

-

### System information

-

**Comment by DerLinkman** [comment]
Please use the whole template and don´t delete it...

It contains relevant system informations.

**Comment by omexlu** [comment]
DONE:
https://github.com/mailcow/mailcow-dockerized/issues/4752
