### ISSUE TITLE
Disable nginx default host

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#476]
Hey,

just installed mailcow and everything works so far. However, i would like to disable the display of the mailcow login page, when accessing a domain that points to the server, where mailcow is running.

I've set up mailcow with the domain mail.domain.tld, but i also see the login page when opening the server ip for example. I could modify the index.php in /mailcow-dockerized/data/web, but i guess, that's not how it should be done.

**Comment by andryyy** [comment]
Well, what else should be shown? :-) This is mailcows Nginx.

You can use a reverse proxy or add a custom site like `data/conf/nginx/my-site.conf`.

**Comment by SoftCreatR** [comment]
> Well, what else should be shown? :-)

It's expected to find the mailcow ui on the domain at `MAILCOW_HOSTNAME` and not on every domain that points to the server.

**Comment by RobinFlikkema** [comment]
Can I say that I like this? This makes sure that you can access mailcow by using the IP itself, for examples when DNS still propagates.

**Comment by SoftCreatR** [comment]
@RobinFlikkema 

Possibly, yes ;)

However, thank you @andryyy for the hint. I've just created a file `data/conf/nginx/default.conf`:

```
server {
  listen 80;
  listen [::]:80;
  server_name _;
  
  return 301 https://www.whatever.tld;
}
```

and it works as expected.
