### ISSUE TITLE
GUID Feld ist leer

### ISSUE THREAD

**Issue by philipp-s06** [mailcow/mailcow-dockerized#4768]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Die Mailkuh :) zeigt mir im Admin Interface keine GUID an. Ich habe eine SAL gekauft und wollte nun die GUID eintragen, aber das Feld ist irgendwie leer.

### Logs

```bash
Es steht nichts als Fehler in den Logs - alle Container starten normal und funktionieren einwandfrei.
```

### Steps to reproduce

1. Admininterface öffnen
2. Zu der GUID wechseln

### System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 11 |
| Is Apparmor, SELinux or similar active? | Nein |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 16GB RAM, 6 Kerne |
| Docker version (`docker version`) | 20.10.18 |
| docker-compose version (`docker-compose version`) | 2.10.0 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-08a-110-g84886963 |
| Reverse proxy (custom solution) | Nginx |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
index a445b60c..0232e9fe 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
 
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = Hostname meines Servers
+
diff --git a/docker-compose.yml b/docker-compose.yml
index 9052caf5..6fb4578e 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -582,36 +582,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

**Comment by DerLinkman** [comment]
Hey,

kannst du uns eine E-Mail an info@servercow.de mit deiner Kundennummer schicken?

Hier auf GitHub bitte immer in Englisch schreiben. Ausnahmsweise lasse ich das jetzt mal durchgehen.

Danke

Niklas vom Servercow Team

**Comment by philipp-s06** [comment]
Klar, Mail geht noch raus.
Sorry für das Deutsch :(
