### ISSUE TITLE
Blocked a frame with origin "..." from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#477]
When accessing SOGo, the error 

`Blocked a frame with origin "..." from accessing a cross-origin frame.`

comes up in the console. Actions like delete mails, etc. are not available / working.

I'm using the default nginx and it's configuration, that is shipped with Mailcow.

**Comment by andryyy** [comment]
Cannot confirm. Anyone?

Sounds like you made changes to site.conf.
