### ISSUE TITLE
Anmeldung über FIDO2 - nach September Update

### ISSUE THREAD

**Issue by SteffnVo** [mailcow/mailcow-dockerized#4771]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Nach dem Update Version: 2022-09 läuft eine Anmeldung mit FIDO2 + eine Neuregistrierung FIDO2 (TouchID auf Apple M1) auf Fehler und ist nicht mehr möglich. Vorher ging dies problemlos.

### Logs

```bash
-
```

### Steps to reproduce

login-Seite - Anmelden Pfeil - FIDO2/WebAuthn
oder 
Anmelden - Registrieren FIDO2

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.5 LTS |
| Docker version (`docker version`) |  20.10.18 |
| docker-compose version (`docker-compose version`) | v2.10.2 |

**Comment by DerLinkman** [comment]
Firstly only english here on GitHub.

Secondly is the template not completely filled/some parts were removed.
