### ISSUE TITLE
Suche bei Domain und Mail-Accounts 

### ISSUE THREAD

**Issue by Jerome2103** [mailcow/mailcow-dockerized#4776]
### Summary

Domain suche funktioniert nicht genau.

Wenn man zum Beispiel 2 Domains hat

- 1234.com
- testing1234.com

Und wenn man sucht nach 1234.com
Werden beide Domain angezeigt. Dies auch bei den Mail-Accounts so. 

### Motivation

Cool wäre, wenn mann dies irgendwie Einschränkung könnte.

**Comment by DerLinkman** [comment]
Please only in english here on GitHub.
