### ISSUE TITLE
fail2ban - excessive bans

### ISSUE THREAD

**Issue by stevesbrain** [mailcow/mailcow-dockerized#478]
Hey all,

Just wondering what the criteria are for having fail2ban lock you out? I find myself exceedingly regularly ending up on the ban list both at home, and at work, and I'm not sure why :) If you can give some indication of what criteria trigger bans, I may be able to narrow it down. Thanks!

**Comment by andryyy** [comment]
What's shown in the Fail2ban log tab in the UI?

**Comment by lazyfrosch** [comment]
I guess he wanted to know this:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/fail2ban/logwatch.py#L24

**Comment by lazyfrosch** [comment]
I had to whitelist my monitoring server, because "exzessive" connects without authentication will also block the source.

**Comment by stevesbrain** [comment]
@andryyy Unfortunately the IP addresses in question never seem to appear in that log (at this stage anyway) - only other addresses. 

@lazyfrosch Thanks for that - I'll take a look through there and see if anything looks like it could cause the issue

**Comment by stevesbrain** [comment]
I am now getting bans with rule ID 3, and it seems to follow my K9-mail. I guess it's time to track down why that's happening! Not a mailcow issue, but I do appreciate you providing the necessary info :D Thanks @lazyfrosch and @andryyy :)

**Comment by rebek86** [comment]
@stevesbrain can you tell me the solution if you could solve the problem? I have the same problem with K9-Mail :-/
Thanks :-)

**Comment by lazyfrosch** [comment]
The problem seems to be that K9-Mail pings the IMAP port without actually logging in.

@andryyy how about removing this line? It is not really an illegal connection, more a detection pattern for port scans...

    RULES[3] = '-login: Disconnected \(no auth .+\): user=.+, rip=([0-9a-f\.:]+), lip.+'
