### ISSUE TITLE
Thunderbird 102.3.2 cannot find CalDav calendars

### ISSUE THREAD

**Issue by ymarkus** [mailcow/mailcow-dockerized#4787]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

When trying to connect accounts in Thunderbird, it does connect to the mail account & the address books fine, but it won't find any calendars, Thunderbird is stuck with "Kalender werden abgerufen...", same when I try to add them manually.

### Logs

```bash
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:18 47364cd75c87 sogod [51]: 179.1.4.48 "HEAD /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:18 47364cd75c87 sogod [51]: 179.1.4.48 "GET /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:18 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/314 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:18 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/203 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:23 47364cd75c87 sogod [51]: 179.1.4.48 "HEAD /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:23 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/314 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:30 47364cd75c87 sogod [51]: 179.1.4.48 "HEAD /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:30 47364cd75c87 sogod [51]: 179.1.4.48 "GET /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:30 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/314 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:30 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/203 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:32 47364cd75c87 sogod [51]: 179.1.4.48 "HEAD /SOGo/dav/ HTTP/1.0" 401 0/0 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:32 47364cd75c87 sogod [51]: 179.1.4.48 "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/314 0.001 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:52:33 47364cd75c87 sogod [51]: mailcowdockerized-watchdog-mailcow-1.mailcowdockerized_mailcow-network "GET /SOGo.index/ HTTP/1.1" 200 2593/0 0.004 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:53:50 47364cd75c87 sogod [51]: mailcowdockerized-watchdog-mailcow-1.mailcowdockerized_mailcow-network "GET /SOGo.index/ HTTP/1.1" 200 2593/0 0.004 - - 0 - 12
mailcowdockerized-sogo-mailcow-1  | Oct  9 15:54:56 47364cd75c87 sogod [51]: mailcowdockerized-watchdog-mailcow-1.mailcowdockerized_mailcow-network "GET /SOGo.index/ HTTP/1.1" 200 2593/0 0.004 - - 0 - 12
```

### Steps to reproduce

1. Add Thunderbird account with the new account wizard
2. Try to connect calendar

### System information

| Question | Answer |
| --- | --- |
| My operating system | NixOS 22.05.20220915.178fea1 (Quokka) |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 64GB, 32 Cores |
| Docker version (`docker version`) | Docker version 20.10.17, build v20.10.17 |
| docker-compose version (`docker-compose version`) | Docker Compose version 2.5.1 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-09a |
| Reverse proxy (custom solution) | nginx, set up as in documentation |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
Only hostname & SSL cert changes

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn:
```
YOUR OUTPUT GOES HERE
```

iptables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

ip6tables -L -vn -t nat:
```
YOUR OUTPUT GOES HERE
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
151.101.129.69
151.101.65.69
151.101.1.69
151.101.193.69
```

**Comment by Braintelligence** [comment]
This is not necessarily related to mailcow itself. Thunderbird has changed it's Cal/CardDAV compatibility with v102.

For tbsync you have to update the addon from GitHub because the official update on the Mozilla addon hub isn't online yet, for example.

Everything works fine for me that way.

EDIT: I use this addon-combo for Cal-/CardDAV and everything works fine for me. If you used it before you might need to delete old address books first, because their format changed in v102.

https://github.com/jobisoft/TbSync/releases/tag/v4.1

https://github.com/jobisoft/DAV-4-TbSync/releases/tag/v4.1

**Comment by ymarkus** [comment]
Yes, I know. Before I always used TBSync and it always worked fine, but the new built-in doesn't for me...

**Comment by Braintelligence** [comment]
You can still use tbsync (which I do just fine), download and import the .xpi-files from the links I gave you above.

**Comment by ymarkus** [comment]
my _tcp DNS:
```
_autodiscover   Dienstidentifizierung (SRV)     [0][1][443] mail.example.org.   Static
_caldavs        Text (TXT)      path=/SOGo/dav/ Static
_caldavs        Dienstidentifizierung (SRV)     [0][1][443] mail.example.org.   Static
_carddavs       Text (TXT)      path=/SOGo/dav/ Static
_carddavs       Dienstidentifizierung (SRV)     [0][1][443] mail.example.org.   Static
_imap   Dienstidentifizierung (SRV)     [0][1][143] mail.example.org.   Static
_imaps  Dienstidentifizierung (SRV)     [0][1][993] mail.example.org.   Static
_pop3   Dienstidentifizierung (SRV)     [0][1][110] mail.example.org.   Static
_pop3s  Dienstidentifizierung (SRV)     [0][1][995] mail.example.org.   Static
_sieve  Dienstidentifizierung (SRV)     [0][1][4190] mail.example.org.  Static
_smtps  Dienstidentifizierung (SRV)     [0][1][465] mail.example.org.   Static
_submission     Dienstidentifizierung (SRV)     [0][1][587] mail.example.org.   Static
```

**Comment by ymarkus** [comment]
Ok, thank you for the recommendation. I still think this might be a bug, either in mailcow or the new Thunderbird built-in DAV.

**Comment by Braintelligence** [comment]
Not sure; I'm using Thunderbird fine both ways. The client I am currently on still hasn't got the manuel .xpi-update. The calendar is running on built-in DAV and calendar works fine.

**Comment by ymarkus** [comment]
Ok, I've found the issue! Our Group Policy Settings had "Save Passwords" set to deactivated and that seems to have messed with it finding the calendars. After setting all password settings in the GPO to "not configured" and running `gpupdate /force`, everything works fine! Still thanks, @Braintelligence for the quick response.

**Comment by Braintelligence** [comment]
Thanks for sharing your case and solution 👍
