### ISSUE TITLE
Ability to change the default quota settings for new domains

### ISSUE THREAD

**Issue by kimdre** [mailcow/mailcow-dockerized#4794]
### Summary

Similar to what is possible for new mailboxes, it wouldn't be bad if you could also set default quotas for new domains, e.g. to change the default 10GB total domain quota.

### Motivation

If you manage a lot of domains, it is annoying that you have no possibility to change the domain quotas to your liking.

**Comment by DerLinkman** [comment]
Hello,

good idea.

We thought about a UI integration with the upcoming BS5 Update.

The current idea is a seperate Dropdown entry for Domains and Mailbox:
![grafik](https://user-images.githubusercontent.com/62480600/196697246-f8890246-cc67-4977-a421-0b958ccbea1d.png)

But what settings we want to include there has not been decided yet. Default Quota definately though.

**Comment by kimdre** [comment]
I will close this topic as it has already been implemented.
