### ISSUE TITLE
http to https redirect

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#48]
Hi

How to enable "redirect http to https"?

**Comment by andryyy** [comment]
mailcow only listens on HTTPS.

**Comment by andryyy** [comment]
You can try and add a new site like `data/conf/nginx/redirect.conf` and add:

```
server {
	listen 80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
```

Next open docker-compose.yml and change the nginx-mailcow service:

```
    nginx-mailcow:
    [...]
     ports:
        - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        - 80:80
```

**Comment by ghost** [comment]
@andryyy 

Thank you!

**Comment by jayphizzle** [comment]
Why not configure the https redirect as default behaviour?

**Comment by andryyy** [comment]
This will not be standard.
Custom systems, Let's Encrypt etc. - I will add it to the docs now.

**Comment by Braintelligence** [comment]
@andryyy Hey 😸. When accessing the site via Firefox it is accessed via http, even though Letsencrypt is set up. I have to manually prepend https://
Other browsers, like Chrome and Opera, seem to do it by themselves.

Did I miss it in the docs how to enable "prefer" or "force" https? 😸

**Comment by chaosbunker** [comment]
Yes, you did miss that in the docs :-)

`Usage & Examples` > `Redirect port 80 to 443`

**Comment by Braintelligence** [comment]
@chaosbunker Duh :D Thanks!
