### ISSUE TITLE
Installing from dev

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#481]
Hey guys, I'm trying to install from DEV but I'm getting this silly message:

`WARNING: The DBROOT variable is not set. Defaulting to a blank string.`
`WARNING: The DBNAME variable is not set. Defaulting to a blank string.`
`WARNING: The DBUSER variable is not set. Defaulting to a blank string.`
`WARNING: The DBPASS variable is not set. Defaulting to a blank string.`
`WARNING: The MAILCOW_HOSTNAME variable is not set. Defaulting to a blank string.`
`WARNING: The TZ variable is not set. Defaulting to a blank string.`
`WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.`
 and cannot continue.

The installation already generates `mailcow.conf` and everything seems to be fine inside the file, perhaps it doesn't work.

any tip? thanks.

**Comment by andryyy** [comment]
Run docker-compose from within the mailcow folder. Or specify the path in command line.

**Comment by alyzrazor** [comment]
I did that, perhaps there is something more. I downloaded the file manually, because I don't know the dev's link for cloning like:  `git clone https://github.com/mailcow/mailcow-dockerized && cd mailcow-dockerized`

I tried `git clone https://github.com/mailcow/mailcow-dockerized-dev && cd mailcow-dockerized` and nothing happens. =(

**Comment by andryyy** [comment]
ln -s mailcow.conf .env should be enough then. :-)

Dev may not be stable.

**Comment by alyzrazor** [comment]
I didn't quite get what you say @andryyy :P sorry
I tried renaming mailcow.conf to mailcow.env  but no luck =(

this is what I get at the very end and everything freezes up:
`:/home/ubuntu/mailcow-dockerized-dev# docker-compose up -d`

> WARNING: The DBROOT variable is not set. Defaulting to a blank string.
> WARNING: The DBNAME variable is not set. Defaulting to a blank string.
> WARNING: The DBUSER variable is not set. Defaulting to a blank string.
> WARNING: The DBPASS variable is not set. Defaulting to a blank string.
> WARNING: The MAILCOW_HOSTNAME variable is not set. Defaulting to a blank string.
> WARNING: The TZ variable is not set. Defaulting to a blank string.
> WARNING: The ADDITIONAL_SAN variable is not set. Defaulting to a blank string.
> Creating network "mailcowdockerizeddev_mailcow-network" with driver "bridge"
> Creating volume "mailcowdockerizeddev_crypt-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_redis-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_vmail-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_postfix-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_rspamd-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_mysql-vol-1" with default driver
> Creating volume "mailcowdockerizeddev_dkim-vol-1" with default driver
> Creating mailcowdockerizeddev_mysql-mailcow_1 ...
> Creating mailcowdockerizeddev_clamd-mailcow_1 ...
> Creating mailcowdockerizeddev_ipv6nat_1 ...
> Creating mailcowdockerizeddev_clamd-mailcow_1
> Creating mailcowdockerizeddev_mysql-mailcow_1
> Creating mailcowdockerizeddev_clamd-mailcow_1 ... done

**Comment by andryyy** [comment]
Naa, you need to create a link, not rename that file. :-) `ln -s mailcow.conf .env`

**Comment by alyzrazor** [comment]
Thanks @andryyy Finally I managed to install Dev version today.
There was another error while installing: RED_COLOR  `Dovecot 1.6 doesn't exist` or something like that, then it took way longer than usual to install though.

**Comment by andryyy** [comment]
Yes, I have not pushed this image yet. It builds it then.
