### ISSUE TITLE
option to keep volumes inside of the mailcow directory for easy remote backups

### ISSUE THREAD

**Issue by ayushin** [mailcow/mailcow-dockerized#4832]
### Summary

Right now you need to separately backup mailcow folder and the docker volumes, however one should be able to choose to keep mailcow data inside the mailcow folders, e.g.:

`        - ./data/vmail:/var/vmail` instead of `- vmail-vol-1:/var/vmail`

This does not have any performance penalties.

### Motivation

Keep all the mailcow data in one place for easy remote backup.

### Additional context

Will this break anything?

**Comment by DerLinkman** [comment]
You can do this for your own installation. But for the general basic installation it won´t be included:

If we would implement this to the normal mailcow instances (especially all running instances right now) we´d have to make sure that the docker named volumes content is copied/moved over to the new place. But there can go a lot wrong if we do that automatically without monitoring.

**Comment by andryyy** [comment]
I chose named volumes back then because you benefit from all options and extensions. You can also bind mount them to the mailcow directory with an update proof compose override.

**Comment by diginfo** [comment]
The other benefit of this is for portability, it would make it trivial to move mailcow from one host to another.

If you use the method of symlinking the `/var/lib/docker/volumes/mailcowdockerized*` to the '/data' folder then when moving to a different host you would still have to re-install mailcow and re-symlink the folders again.

If the mountpoint could be specified in the compose file, then you could achieve true portability ?
