### ISSUE TITLE
Delay forwarding email

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#484]
I setup mailcow-dockerized with standard configuration yesterday. All DNS setup as recommended on documents including dkim.

I find the delay forwarding in this new dockerized email system.

1. First, I set a aliases (a@mailcow.de will forward to b@gmail.com) 
2. I use a@gmail.com to set two emails to a@mailcow.de (which will forward all emails to b@gmail.com ),  at 6:55am and 15:23am. But it check b@gmail.com for several times, until 15:30am I received these two test emails at b@gmail.com together.

The first email delay almost 9 hours.

Before this, I use mailcow non-dockerized 0.14 final, and the forwarding happened instantly.

This is the screenshot from Rspamd history.

![1](https://user-images.githubusercontent.com/4225935/28781488-83a43598-760a-11e7-9f42-e710cd1dc6df.jpg)

Thank you.

**Comment by pyy** [comment]
After I disable the hardware firewall from the server's provider, I got the missed email soon. But it delays 99945 seconds.

The firewall configuration is the same as before moving to dockerized version which works well before. I'm confused.

![1](https://user-images.githubusercontent.com/4225935/28799566-6c566aca-7649-11e7-94a9-835b284c21d7.jpg)

**Comment by andryyy** [comment]
The forward chain in netfilter is important. You should also make sure your firewall script does not mess with Dockers netfilter rules.
