### ISSUE TITLE
mailcow freeze

### ISSUE THREAD

**Issue by phillipplum** [mailcow/mailcow-dockerized#485]
Hello,
we have the problem, that mailcow freeze after a random time. The UI, dovecot, postfix etc. are not available. I also lost connection over ssh and reconnecting is not possible. 

We have a VM with XEN only with mailcow running. After the freeze i only have access over the host and console over xen. When i shutdown mailcow and start again, everything is fine!

**Systeminfos**: 
Virtualization: xen
Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64

**Comment by andryyy** [comment]
Upgrade your Kernel from jessie-backports and everything works fine! :-)
3.16 panics with Docker health checks.

**Comment by h4llm3n** [comment]
Check: https://github.com/mailcow/mailcow-dockerized/issues/309

**Comment by phillipplum** [comment]
Thanks! I upgrade our kernel and we're monitoring it.

**Comment by PhoenixPeca** [comment]
I'm closing this as it is a duplicate of #309
