### ISSUE TITLE
Keep sent mails when using app password

### ISSUE THREAD

**Issue by kvdb** [mailcow/mailcow-dockerized#4853]
### Summary

When I sent regular email through my mail login, the sent mails are kept in the "Sent" folder.
When sending mail through the app password login, sent mails are properly delivered, but can not be seen in the "Sent" folder.
This might be intentional, but it'd be great if there was an option to treat them the same way. 

### Motivation

Coming from GSuite recently, I was used to seeing no difference in the way the sent mails were treated except for a difference in login.

**Comment by mkuron** [comment]
How are you sending the mails? It's up to the client to send it via SMTP and to also store a copy of it into the Sent folder via IMAP. And that works with app passwords just like it does with regular passwords. I suspect your client is not configured to store a copy into the Sent folder, which unfortunately the server cannot automatically do for you.

**Comment by kvdb** [comment]
Thanks for enlightening me @mkuron, I didn't know that. I suppose I've been in the Google ecosystem for too long as I assumed that behavior to be a default (https://stackoverflow.com/questions/30501826/how-to-send-an-email-using-gmails-smtp-without-writing-it-in-sent-mail).
