### ISSUE TITLE
make update.sh proxy ready

### ISSUE THREAD

**Issue by mitch-geht-ab** [mailcow/mailcow-dockerized#4858]
### Summary

You check in update.sh/check_online_status() for only a direct online connection with ping.
But you use only git for an https connection, maybe curl (you only check if binary is available).
I use mailcow in a seperate VLAN with no direct internet access. But https connections (e.g. for updates) are possible through a proxy. 
So change check_online_status to an proxy capable way, with the assumption that https_proxy env is set.
```
mailcow-dockerized$ diff update.sh update2.sh
6,8c6,8
<   CHECK_ONLINE_IPS=(1.1.1.1 9.9.9.9 8.8.8.8)
<   for ip in "${CHECK_ONLINE_IPS[@]}"; do
<     if timeout 3 ping -c 1 ${ip} > /dev/null; then
---
>   CHECK_ONLINE_DOMAINS=('https://github.com')
>   for domain in "${CHECK_ONLINE_DOMAINS[@]}"; do
>     if timeout 3 curl --head --silent --output /dev/null ${domain}; then
928c928
< # echo "Use \"git reset --hard hash-on-the-left\" and run $COMPOSE_COMMAND up -d afterwards."
\ No newline at end of file
---
> # echo "Use \"git reset --hard hash-on-the-left\" and run $COMPOSE_COMMAND up -d afterwards."
```

BR
mitch

### Motivation

make update.sh usable behind proxy.

**Comment by DerLinkman** [comment]
Maybe a pr with your changes would be good?

Looks and sounds good to me at least.

**Comment by mitch-geht-ab** [comment]
okay
https://github.com/mailcow/mailcow-dockerized/pull/4859
