### ISSUE TITLE
SNI mode without letsencrypt certificates

### ISSUE THREAD

**Issue by mrschyte** [mailcow/mailcow-dockerized#4867]
### Summary

Currently mailcow only sets up SNI mode if both ENABLE_SSL_SNI=y and SKIP_LETS_ENCRYPT=n are set in the configuration file.

I'd like to enable SNI mode with manually created certificates i.e. without enabling the acme-mailcow service.

I was able to set up SNI mode with custom certificates by manually copying them to /opt/mailcow-dockerized/data/assets/ssl/${domain} and creating the /opt/mailcow-dockerized/data/assets/ssl/${domain}/domains file, however SSL/TLS services fail after a while. I suspect that this is because acme-mailcow gives up trying to obtain the certificates and the dependent services are killed.

Mailcow should allow enabling SNI mode even if SKIP_LETS_ENCRYPT=y is set.

### Motivation

In some environments it is not possible to utilize letsencrypt certificates.

**Comment by cero1988** [comment]
I have tried like you to create the folder /opt/mailcow-dockerized/data/assets/ssl/${domain} and inside that folder the files:
- domains
- cert.pem
- key.pem

now sni is working, and seems to remain functional even after hours
I think that this problem should be resolved, maybe the documentation of mailcow should include the procudure to manually load custom certificates

**Comment by mrschyte** [comment]
Thanks, it looks good! I no longer need to use the workaround of scaling down the acme-mailcow service.

**Comment by marcelschmidtdev** [comment]
@mrschyte I have the same problem getting SNI working without Mailcow ACME. What exactly goes into the `domains` file? Does it work for you with Postfix and Dovecot?
Postfix has this additional check which is not present in the Dovecote script: 
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/postfix/postfix.sh#L28

**Comment by mrschyte** [comment]
The domains file should contain the host names for that particular domain.

Let's say you want to host example1.com and example2.com. You would have the following in mailcow-dockerized:
```
$ ls ./data/assets/ssl/example1.com/
cert.pem domains key.pem
$ cat ./data/assets/ssl/example1.com/domains
mx.example1.com
example1.com
$ ls ./data/assets/ssl/example2.com/
cert.pem domains key.pem
$ cat ./data/assets/ssl/example2.com/domains
mx.example2.com
example2.com
```
And in `mailcow.conf` you should set the following:
```
# Skip running ACME (acme-mailcow, Let's Encrypt certs) - y/n
SKIP_LETS_ENCRYPT=y

# Create seperate certificates for all domains - y/n
# this will allow adding more than 100 domains, but some email clients will not be able to connect with alternative hos
tnames
# see https://wiki.dovecot.org/SSL/SNIClientSupport
ENABLE_SSL_SNI=y
```
With the above config, I'm getting the correct certificates for each domain I serve; `openssl s_client -starttls smtp -connect mx.example1.com:587 -showcerts` returns the correct certificate.

If this doesn't work for you, could you try running with `SKIP_LETS_ENCRYPT=n` and then `docker compose up -d --scale acme-mailcow=0` to scale down the acme container?

**Comment by marcelschmidtdev** [comment]
Thank you for clarifying, it works now

**Comment by disgustipated** [comment]
Is this still the correct way to set up additional domains with their individual certs with SNI? 
I have ENABLE_SSL_SNI=y, SKIP_LETS_ENCRYPT=y 
I have the directory with my certs set up ./data/assets/ssl/mydomain.com/ with the cert.pem and key.pem
my ./data/assets/ssl/mydomain.com/domains file lists
mx.mydomain.com
mydomain.com
mail.mydomain.com

all containers are then restarted

and when i run the openssl connect it returns the MAILCOW_HOSTNAME cert. am i missing something else with the SNI setup? I noticed there was a folder in the ssl folder with the mailcow_hostname, so i tried also setting the folder in ssl with mail.mydomain.com too and that didnt work either. i also couldnt find mention in the docs how the domains file is used as detailed here

edit:
i fixed my issue after looking at the link above how postfix sni.map is built(thank you for that link!). i looked in the postfix container under 
/opt/postfix/conf/sni.map
Here the entry for my domain was first starting with mx.mydomain.com (which is what i used for my mx dns but i also have the mail.mydomain.com which is where the mx record is pointing), i then checked my domains file in the ./data/assets/ssl/mydomain.com/ folder and the first entry there was the mx.mydomain.com entry, i changed that first entry in the domains file to mail.mydomain.com and now the sni.map is correct and i got the correct cert from the openssl showcerts
