### ISSUE TITLE
Apache Reverse Proxy

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#487]
![1](https://user-images.githubusercontent.com/30322395/28882367-4fb4f18a-77ab-11e7-8113-f98080d033fb.PNG)
Hello,
I have a problem with the apache configuration. I want to use apache as webspace and the mailcow nginx only for mail.mydomain.de. Now I have edited my apache config as in the picture [/etc/apache2/sites-available/000-default.conf]. Now apache can't start or reload anymore. Is the configuration correct as it is in the picture?

**Comment by andryyy** [comment]
The last four SSLblabla parameters can be removed. Add a ";" after every line (ServerName, Alias etc.)

**Comment by ghost** [comment]
@andryyy 
![1](https://user-images.githubusercontent.com/30322395/28884360-d1b0f2e6-77b1-11e7-8b4f-195fd59d2132.PNG)
 Is it correkt now? Or must i add the ";" after every line?

**Comment by andryyy** [comment]
Oh, my mind was set to Nginx. You don't need those ; as line endings. Sorry.

**Comment by andryyy** [comment]
But still... just look in Apaches error log. And understand what you are doing. Why did you enable those last four SSL parameters?

**Comment by DapeDope** [comment]
Becouse of i dont want to renew everytime the certbot certificate.

**Comment by Braintelligence** [comment]
I don't see how you would achieve that by doing what you did, though.

**Comment by ghost** [comment]
wtf. After a new installation of debian he brings me an error while during "curl -sSL https://get.docker.com/ | sh". I'm sick of this. ^^

**Comment by RobinFlikkema** [comment]
What's the error you're getting now?

**Comment by ghost** [comment]
Here you can see, what happens, if i want to install docker [curl -sSL https://get.docker.com/ | sh].
@RobinFlikkema 

root@vps:~# curl -sSL https://get.docker.com/ | sh
Executing docker install script, commit: 29533f9
+ sh -c apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Hit http://ppa.launchpad.net trusty InRelease
Ign http://ftp.debian.org jessie InRelease
Get:2 http://ftp.debian.org jessie-updates InRelease [145 kB]
Hit http://ftp.debian.org jessie Release.gpg
Hit http://ftp.debian.org jessie Release
Hit http://ppa.launchpad.net trusty/main Sources
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Hit http://security.debian.org jessie/updates/non-free amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://security.debian.org jessie/updates/non-free Translation-en
Get:3 http://ftp.debian.org jessie-updates/main amd64 Packages/DiffIndex [8392 B]
Hit http://ftp.debian.org jessie-updates/contrib amd64 Packages
Get:4 http://ftp.debian.org jessie-updates/non-free amd64 Packages/DiffIndex [736 B]
Hit http://ftp.debian.org jessie-updates/contrib Translation-en
Get:5 http://ftp.debian.org jessie-updates/main Translation-en/DiffIndex [3196 B]
Get:6 http://ftp.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Hit http://ftp.debian.org jessie/main amd64 Packages
Hit http://ftp.debian.org jessie/contrib amd64 Packages
Hit http://ftp.debian.org jessie/non-free amd64 Packages
Hit http://ftp.debian.org jessie/contrib Translation-en
Hit http://ftp.debian.org jessie/main Translation-en
Hit http://ftp.debian.org jessie/non-free Translation-en
Fetched 221 kB in 3s (64.3 kB/s)
Reading package lists... Done
+ sh -c apt-get install -y -q apt-transport-https ca-certificates curl software-properties-common
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version.
curl is already the newest version.
The following extra packages will be installed:
  apt-utils dh-python gir1.2-glib-2.0 iso-codes libapt-inst1.5 libcurl3-gnutls libdbus-glib-1-2 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libmpdec2 libpython3-stdlib libpython3.4-stdlib python-apt-common python3 python3-apt
  python3-dbus python3-gi python3-minimal python3-software-properties python3.4 shared-mime-info unattended-upgrades xdg-user-dirs
Suggested packages:
  isoquery python3-doc python3-tk python3-venv python3-apt-dbg python-apt-doc python-dbus-doc python3-dbus-dbg python3.4-venv python3.4-doc bsd-mailx mail-transport-agent
The following NEW packages will be installed:
  apt-transport-https apt-utils dh-python gir1.2-glib-2.0 iso-codes libapt-inst1.5 libcurl3-gnutls libdbus-glib-1-2 libgirepository-1.0-1 libglib2.0-0 libglib2.0-data libmpdec2 libpython3-stdlib libpython3.4-stdlib python-apt-common
  python3 python3-apt python3-dbus python3-gi python3-minimal python3-software-properties python3.4 shared-mime-info software-properties-common unattended-upgrades xdg-user-dirs
0 upgraded, 26 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.5 MB of archives.
After this operation, 52.4 MB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ jessie/main libapt-inst1.5 amd64 1.0.9.8.4 [169 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main libcurl3-gnutls amd64 7.38.0-4+deb8u5 [252 kB]
Get:3 http://ftp.debian.org/debian/ jessie/main libglib2.0-0 amd64 2.42.1-1+b1 [2401 kB]
Get:4 http://ftp.debian.org/debian/ jessie/main libdbus-glib-1-2 amd64 0.102-1 [201 kB]
Get:5 http://ftp.debian.org/debian/ jessie/main libmpdec2 amd64 2.4.1-1 [85.7 kB]
Get:6 http://ftp.debian.org/debian/ jessie/main libpython3.4-stdlib amd64 3.4.2-1 [2088 kB]
Get:7 http://ftp.debian.org/debian/ jessie/main apt-utils amd64 1.0.9.8.4 [368 kB]
Get:8 http://ftp.debian.org/debian/ jessie/main apt-transport-https amd64 1.0.9.8.4 [138 kB]
Get:9 http://ftp.debian.org/debian/ jessie/main python3.4 amd64 3.4.2-1 [204 kB]
Get:10 http://ftp.debian.org/debian/ jessie/main python3-minimal amd64 3.4.2-2 [34.7 kB]
Get:11 http://ftp.debian.org/debian/ jessie/main libpython3-stdlib amd64 3.4.2-2 [18.1 kB]
Get:12 http://ftp.debian.org/debian/ jessie/main python3 amd64 3.4.2-2 [21.2 kB]
Get:13 http://ftp.debian.org/debian/ jessie/main dh-python all 1.20141111-2 [66.4 kB]
Get:14 http://ftp.debian.org/debian/ jessie/main libgirepository-1.0-1 amd64 1.42.0-2.2 [95.7 kB]
Get:15 http://ftp.debian.org/debian/ jessie/main gir1.2-glib-2.0 amd64 1.42.0-2.2 [141 kB]
Get:16 http://ftp.debian.org/debian/ jessie/main iso-codes all 3.57-1 [2265 kB]
Get:17 http://ftp.debian.org/debian/ jessie/main libglib2.0-data all 2.42.1-1 [2173 kB]
Get:18 http://ftp.debian.org/debian/ jessie/main python-apt-common all 0.9.3.12 [89.9 kB]
Get:19 http://ftp.debian.org/debian/ jessie/main python3-apt amd64 0.9.3.12 [169 kB]
Get:20 http://ftp.debian.org/debian/ jessie/main python3-dbus amd64 1.2.0-2+b3 [189 kB]
Get:21 http://ftp.debian.org/debian/ jessie/main python3-gi amd64 3.14.0-1 [454 kB]
Get:22 http://ftp.debian.org/debian/ jessie/main unattended-upgrades all 0.83.3.2+deb8u1 [52.9 kB]
Get:23 http://ftp.debian.org/debian/ jessie/main python3-software-properties all 0.92.25debian1 [41.4 kB]
Get:24 http://ftp.debian.org/debian/ jessie/main shared-mime-info amd64 1.3-1 [634 kB]
Get:25 http://ftp.debian.org/debian/ jessie/main software-properties-common all 0.92.25debian1 [79.3 kB]
Get:26 http://ftp.debian.org/debian/ jessie/main xdg-user-dirs amd64 0.15-2 [52.1 kB]
Fetched 12.5 MB in 1s (11.3 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libapt-inst1.5:amd64.
(Reading database ... 15487 files and directories currently installed.)
Preparing to unpack .../libapt-inst1.5_1.0.9.8.4_amd64.deb ...
Unpacking libapt-inst1.5:amd64 (1.0.9.8.4) ...
Selecting previously unselected package libcurl3-gnutls:amd64.
Preparing to unpack .../libcurl3-gnutls_7.38.0-4+deb8u5_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.38.0-4+deb8u5) ...
Selecting previously unselected package libglib2.0-0:amd64.
Preparing to unpack .../libglib2.0-0_2.42.1-1+b1_amd64.deb ...
Unpacking libglib2.0-0:amd64 (2.42.1-1+b1) ...
Selecting previously unselected package libdbus-glib-1-2:amd64.
Preparing to unpack .../libdbus-glib-1-2_0.102-1_amd64.deb ...
Unpacking libdbus-glib-1-2:amd64 (0.102-1) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../libmpdec2_2.4.1-1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.1-1) ...
Selecting previously unselected package libpython3.4-stdlib:amd64.
Preparing to unpack .../libpython3.4-stdlib_3.4.2-1_amd64.deb ...
Unpacking libpython3.4-stdlib:amd64 (3.4.2-1) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.0.9.8.4_amd64.deb ...
Unpacking apt-utils (1.0.9.8.4) ...
Selecting previously unselected package apt-transport-https.
Preparing to unpack .../apt-transport-https_1.0.9.8.4_amd64.deb ...
Unpacking apt-transport-https (1.0.9.8.4) ...
Selecting previously unselected package python3.4.
Preparing to unpack .../python3.4_3.4.2-1_amd64.deb ...
Unpacking python3.4 (3.4.2-1) ...
Selecting previously unselected package python3-minimal.
Preparing to unpack .../python3-minimal_3.4.2-2_amd64.deb ...
Unpacking python3-minimal (3.4.2-2) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../libpython3-stdlib_3.4.2-2_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.4.2-2) ...
Selecting previously unselected package python3.
Preparing to unpack .../python3_3.4.2-2_amd64.deb ...
Unpacking python3 (3.4.2-2) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../dh-python_1.20141111-2_all.deb ...
Unpacking dh-python (1.20141111-2) ...
Selecting previously unselected package libgirepository-1.0-1:amd64.
Preparing to unpack .../libgirepository-1.0-1_1.42.0-2.2_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.42.0-2.2) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../gir1.2-glib-2.0_1.42.0-2.2_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.42.0-2.2) ...
Selecting previously unselected package iso-codes.
Preparing to unpack .../iso-codes_3.57-1_all.deb ...
Unpacking iso-codes (3.57-1) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../libglib2.0-data_2.42.1-1_all.deb ...
Unpacking libglib2.0-data (2.42.1-1) ...
Selecting previously unselected package python-apt-common.
Preparing to unpack .../python-apt-common_0.9.3.12_all.deb ...
Unpacking python-apt-common (0.9.3.12) ...
Selecting previously unselected package python3-apt.
Preparing to unpack .../python3-apt_0.9.3.12_amd64.deb ...
Unpacking python3-apt (0.9.3.12) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../python3-dbus_1.2.0-2+b3_amd64.deb ...
Unpacking python3-dbus (1.2.0-2+b3) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../python3-gi_3.14.0-1_amd64.deb ...
Unpacking python3-gi (3.14.0-1) ...
Selecting previously unselected package unattended-upgrades.
Preparing to unpack .../unattended-upgrades_0.83.3.2+deb8u1_all.deb ...
Unpacking unattended-upgrades (0.83.3.2+deb8u1) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../python3-software-properties_0.92.25debian1_all.deb ...
Unpacking python3-software-properties (0.92.25debian1) ...
Selecting previously unselected package shared-mime-info.
Preparing to unpack .../shared-mime-info_1.3-1_amd64.deb ...
Unpacking shared-mime-info (1.3-1) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../software-properties-common_0.92.25debian1_all.deb ...
Unpacking software-properties-common (0.92.25debian1) ...
Selecting previously unselected package xdg-user-dirs.
Preparing to unpack .../xdg-user-dirs_0.15-2_amd64.deb ...
Unpacking xdg-user-dirs (0.15-2) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for systemd (215-17+deb8u7) ...
Setting up libapt-inst1.5:amd64 (1.0.9.8.4) ...
Setting up libcurl3-gnutls:amd64 (7.38.0-4+deb8u5) ...
Setting up libglib2.0-0:amd64 (2.42.1-1+b1) ...
No schema files found: doing nothing.
Setting up libdbus-glib-1-2:amd64 (0.102-1) ...
Setting up libmpdec2:amd64 (2.4.1-1) ...
Setting up libpython3.4-stdlib:amd64 (3.4.2-1) ...
Setting up apt-utils (1.0.9.8.4) ...
Setting up apt-transport-https (1.0.9.8.4) ...
Setting up python3.4 (3.4.2-1) ...
Setting up python3-minimal (3.4.2-2) ...
Setting up libpython3-stdlib:amd64 (3.4.2-2) ...
Setting up libgirepository-1.0-1:amd64 (1.42.0-2.2) ...
Setting up gir1.2-glib-2.0:amd64 (1.42.0-2.2) ...
Setting up iso-codes (3.57-1) ...
Setting up libglib2.0-data (2.42.1-1) ...
Setting up python-apt-common (0.9.3.12) ...
Setting up shared-mime-info (1.3-1) ...
Setting up xdg-user-dirs (0.15-2) ...
Setting up dh-python (1.20141111-2) ...
Setting up python3 (3.4.2-2) ...
running python rtupdate hooks for python3.4...
running python post-rtupdate hooks for python3.4...
Setting up python3-apt (0.9.3.12) ...
Setting up python3-dbus (1.2.0-2+b3) ...
Setting up python3-gi (3.14.0-1) ...
Setting up unattended-upgrades (0.83.3.2+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up python3-software-properties (0.92.25debian1) ...
Setting up software-properties-common (0.92.25debian1) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
+ curl -fsSl https://download.docker.com/linux/debian/gpg
+ sh -c apt-key add -
OK
+ sh -c add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian jessie edge"
+ [ debian = debian ]
+ [ jessie = wheezy ]
+ sh -c apt-get update
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.debian.org jessie InRelease
Hit http://ftp.debian.org jessie-updates InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ftp.debian.org jessie Release.gpg
Hit http://ftp.debian.org jessie Release
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Get:1 https://download.docker.com jessie InRelease [20.2 kB]
Get:2 http://ftp.debian.org jessie-updates/main amd64 Packages/DiffIndex [8392 B]
Hit http://security.debian.org jessie/updates/non-free amd64 Packages
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://ftp.debian.org jessie-updates/contrib amd64 Packages
Hit http://security.debian.org jessie/updates/non-free Translation-en
Get:3 http://ftp.debian.org jessie-updates/non-free amd64 Packages/DiffIndex [736 B]
Hit http://ppa.launchpad.net trusty/main Sources
Hit http://ftp.debian.org jessie-updates/contrib Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:4 http://ftp.debian.org jessie-updates/main Translation-en/DiffIndex [3196 B]
Hit http://ppa.launchpad.net trusty/main Translation-en
Get:5 http://ftp.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Hit http://ftp.debian.org jessie/main amd64 Packages
Get:6 https://download.docker.com jessie/edge amd64 Packages [1703 B]
Hit http://ftp.debian.org jessie/contrib amd64 Packages
Hit http://ftp.debian.org jessie/non-free amd64 Packages
Hit http://ftp.debian.org jessie/contrib Translation-en
Hit http://ftp.debian.org jessie/main Translation-en
Hit http://ftp.debian.org jessie/non-free Translation-en
Get:7 https://download.docker.com jessie/edge Translation-en [582 B]
Get:8 https://download.docker.com jessie/edge Translation-en [582 B]
Get:9 https://download.docker.com jessie/edge Translation-en [582 B]
Get:10 https://download.docker.com jessie/edge Translation-en [582 B]
Get:11 https://download.docker.com jessie/edge Translation-en [582 B]
Ign https://download.docker.com jessie/edge Translation-en
Fetched 34.9 kB in 2s (14.4 kB/s)
Reading package lists... Done
+ sh -c apt-get install -y -q docker-ce
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  aufs-tools cgroupfs-mount git git-man less libdrm2 liberror-perl libltdl7 libpopt0 mountall patch plymouth rsync
Suggested packages:
  git-daemon-run git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn diffutils-doc desktop-base plymouth-themes
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount docker-ce git git-man less libdrm2 liberror-perl libltdl7 libpopt0 mountall patch plymouth rsync
0 upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
Need to get 26.4 MB of archives.
After this operation, 123 MB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ jessie/main libpopt0 amd64 1.16-10 [49.2 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main libdrm2 amd64 2.4.58-2 [29.9 kB]
Get:3 http://ftp.debian.org/debian/ jessie/main libltdl7 amd64 2.4.2-1.11+b1 [45.4 kB]
Get:4 http://ftp.debian.org/debian/ jessie/main plymouth amd64 0.9.0-9 [189 kB]
Get:5 https://download.docker.com/linux/debian/ jessie/edge docker-ce amd64 17.06.0~ce-0~debian [20.4 MB]
Get:6 http://ftp.debian.org/debian/ jessie/main mountall amd64 2.54 [68.3 kB]
Get:7 http://ftp.debian.org/debian/ jessie/main less amd64 458-3 [124 kB]
Get:8 http://ftp.debian.org/debian/ jessie/main patch amd64 2.7.5-1 [109 kB]
Get:9 http://ftp.debian.org/debian/ jessie/main aufs-tools amd64 1:3.2+20130722-1.1 [92.9 kB]
Get:10 http://ftp.debian.org/debian/ jessie/main cgroupfs-mount all 1.1 [4572 B]
Get:11 http://ftp.debian.org/debian/ jessie/main liberror-perl all 0.17-1.1 [22.4 kB]
Get:12 http://ftp.debian.org/debian/ jessie/main git-man all 1:2.1.4-2.1+deb8u3 [1268 kB]
Get:13 http://ftp.debian.org/debian/ jessie/main git amd64 1:2.1.4-2.1+deb8u3 [3583 kB]
Get:14 http://ftp.debian.org/debian/ jessie/main rsync amd64 3.1.1-3 [390 kB]
Fetched 26.4 MB in 2s (12.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 14.)
debconf: falling back to frontend: Readline
Selecting previously unselected package libpopt0:amd64.
(Reading database ... 17466 files and directories currently installed.)
Preparing to unpack .../libpopt0_1.16-10_amd64.deb ...
Unpacking libpopt0:amd64 (1.16-10) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../libdrm2_2.4.58-2_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.58-2) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../libltdl7_2.4.2-1.11+b1_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.2-1.11+b1) ...
Selecting previously unselected package plymouth.
Preparing to unpack .../plymouth_0.9.0-9_amd64.deb ...
Unpacking plymouth (0.9.0-9) ...
Selecting previously unselected package mountall.
Preparing to unpack .../mountall_2.54_amd64.deb ...
Unpacking mountall (2.54) ...
Selecting previously unselected package less.
Preparing to unpack .../archives/less_458-3_amd64.deb ...
Unpacking less (458-3) ...
Selecting previously unselected package patch.
Preparing to unpack .../patch_2.7.5-1_amd64.deb ...
Unpacking patch (2.7.5-1) ...
Selecting previously unselected package aufs-tools.
Preparing to unpack .../aufs-tools_1%3a3.2+20130722-1.1_amd64.deb ...
Unpacking aufs-tools (1:3.2+20130722-1.1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../cgroupfs-mount_1.1_all.deb ...
Unpacking cgroupfs-mount (1.1) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_17.06.0~ce-0~debian_amd64.deb ...
Unpacking docker-ce (17.06.0~ce-0~debian) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17-1.1_all.deb ...
Unpacking liberror-perl (0.17-1.1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.1.4-2.1+deb8u3_all.deb ...
Unpacking git-man (1:2.1.4-2.1+deb8u3) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.1.4-2.1+deb8u3_amd64.deb ...
Unpacking git (1:2.1.4-2.1+deb8u3) ...
Selecting previously unselected package rsync.
Preparing to unpack .../rsync_3.1.1-3_amd64.deb ...
Unpacking rsync (3.1.1-3) ...
Processing triggers for systemd (215-17+deb8u7) ...
Processing triggers for mime-support (3.58) ...
Setting up libpopt0:amd64 (1.16-10) ...
Setting up libdrm2:amd64 (2.4.58-2) ...
Setting up libltdl7:amd64 (2.4.2-1.11+b1) ...
Setting up plymouth (0.9.0-9) ...
update-initramfs: deferring update (trigger activated)
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up mountall (2.54) ...
Setting up less (458-3) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Setting up patch (2.7.5-1) ...
Setting up aufs-tools (1:3.2+20130722-1.1) ...
Setting up cgroupfs-mount (1.1) ...
Setting up docker-ce (17.06.0~ce-0~debian) ...
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up liberror-perl (0.17-1.1) ...
Setting up git-man (1:2.1.4-2.1+deb8u3) ...
Setting up git (1:2.1.4-2.1+deb8u3) ...
Setting up rsync (3.1.1-3) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
Processing triggers for initramfs-tools (0.120+deb8u3) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@vps:~#

**Comment by RobinFlikkema** [comment]
Check systemctl and journalctl to see what the cause of this is.

**Comment by ghost** [comment]
systemctl error:
<E2><97><8F> docker.service loaded failed failed Docker Application Container Engine
@RobinFlikkema
