### ISSUE TITLE
Enable Gmail-like E-Mail Aliasses with a "+"

### ISSUE THREAD

**Issue by jdockwarder** [mailcow/mailcow-dockerized#4885]
### Summary

I propose to add a feature, that allows for enabling infinite automated e-mail address aliases with a "+", similar to how Gmail does it. For example if my e-mail address ist `julius@mailcow.email`, I would be able to seamlessly create an alias by adding a "+" to my address when signing up anywhere like this: `julius+netflix@mailcow.email`. All mail sent to that alias would still land in my inbox at `julius@mailcow.email`. Interesting would also be I could see a list of all my aliases and block single ones, in case they become compromised.

### Motivation

I am currently a Google Workspace user as a single freelancer. I would like to switch to using Mailcow also professionally.

**Comment by MAGICCC** [comment]
Yes that works already, see https://docs.mailcow.email/manual-guides/mailcow-UI/u_e-mailcow_ui-sub_addressing/

> Interesting would also be I could see a list of all my aliases and block single ones, in case they become compromised.

maybe via blacklisting

**Comment by jdockwarder** [comment]
Wow, I didn't know that, thanks for pointing it out! I will just close this then...
