### ISSUE TITLE
reactivate Sync Job by cronjob

### ISSUE THREAD

**Issue by t-lie** [mailcow/mailcow-dockerized#4886]
### Summary

Because of an issue one of my sync jobs (where I sync mails from external IMAP account) regulary stops because of "bad login". So I need to activate the job again by hand all few days.

So it would be great to create a cron job which activate a specific sync job by command, db entry or anything else.
This would be really helpful.

Alternatively, it would of course also be a helpful function if the sync job is not automatically deactivated directly, but if an error occurs, the job will try again at the next inverall.

### Motivation

please see summary.

**Comment by MAGICCC** [comment]
Also somewhat related to https://github.com/mailcow/mailcow-dockerized/issues/4711

**Comment by feldsam** [comment]
Closing this, issue from #4711 is solved in staging now.
