### ISSUE TITLE
How to properly move to another server?

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#490]
Hey,

i had to move the server and most things worked so far. However, imported mails are not being shown in SOgo nor local mail clients.

What i did was:

1. Change DNS record for mail.domain.tld to the new ip address
2. Backup maildir:

```
cd /path/to/mailcow-dockerized

docker run --rm -i -v $(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/vmail" }}{{ .Name }}{{ end }}{{ end }}' $(docker-compose ps -q dovecot-mailcow)):/vmail -v ${PWD}:/backup debian:stretch-slim tar cvfz /backup/backup_vmail.tar.gz /vmail
```

3. Backup database:

```
source mailcow.conf

DATE=$(date +"%Y%m%d_%H%M%S")

docker-compose exec -T mysql-mailcow mysqldump --default-character-set=utf8mb4 -u${DBUSER} -p${DBPASS} ${DBNAME} > backup_${DBNAME}_${DATE}.sql
```

4. Transferred the backup files to the new server.
5. Installed mailcow-dockerized on the new server
6. Imported the backups:

```
cd /path/to/mailcow-dockerized

docker run --rm -it -v $(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/vmail" }}{{ .Name }}{{ end }}{{ end }}' $(docker-compose ps -q dovecot-mailcow)):/vmail -v ${PWD}:/backup debian:stretch-slim tar xvfz /backup/backup_vmail.tar.gz

source mailcow.conf

docker exec -i $(docker-compose ps -q mysql-mailcow) mysql -u${DBUSER} -p${DBPASS} ${DBNAME} < backup_file.sql
```

---

What i had to do after this process was creating new DKIM keys (the domains where listed in the admin control panel. but no keys) and renew the ssl certs:

`docker-compose restart acme-mailcow`

What i see now is, that all mailboxes are there and also the correct quota and even the aliases. But as said, there are no mails.

Did i miss a step?

**Comment by SoftCreatR** [comment]
Okay, after running `docker-compose exec dovecot-mailcow doveadm quota recalc -A` it turned out, that the mails have not been imported for some reason?

**Comment by SoftCreatR** [comment]
Nevermind - Just imported again and now, everything's there. A re-calculation of the quota returned errors, i hope, that nothing is lost:

```
doveadm(xxx@yyy): Error: Index file /var/vmail/yyy/xxx/dovecot.index: indexid changed: 1501736639 -> 1501220468
doveadm(xxx@yyy): Error: Corrupted transaction log file /var/vmail/yyy/xxx/dovecot.index.log seq 3: indexid changed: 1501736639 -> 1501220468 (sync_offset=304)
doveadm(xxx@yyy): Error: Transaction log file /var/vmail/yyy/xxx/dovecot.index.log: marked corrupted
doveadm(xxx@yyy): Error: Index /var/vmail/yyy/xxx/dovecot.index: Lost log for seq=3 offset=18448: Missing middle file seq=3 (between 3..4294967295, we have seqs 2): Requested newer log than exists: Log inode is unchanged (initial_mapped=0, reason=Index mapped)
doveadm(xxx@yyy): Warning: fscking index file /var/vmail/yyy/xxx/dovecot.index
doveadm(xxx@yyy): Error: Fixed index file /var/vmail/yyy/xxx/dovecot.index: log_file_seq 3 -> 2
```

**Comment by andryyy** [comment]
Hi, Dovecot has a great self-healing index. :-) Should be fine.
