### ISSUE TITLE
Nextcloud is incompatible to PHP 8.1

### ISSUE THREAD

**Issue by master2die** [mailcow/mailcow-dockerized#4907]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```text
I have freshly installed mailcow step-by-step as instructed in the docs. I used the helper script to install Nextcloud. After installing, when I try to access the nextcloud web app, it shows this error:

This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.13.
```

### Logs:

```text
I think it is not neccesary, as the issue speaks to itself.
```

### Steps to reproduce:

```text
1. Use helper-script to install nextcloud
2. Visit nextcloud page in your browser
3. Error message is shown:
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.13.
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.02 LTS

### Server/VM specifications:

2 Cores, 8GB RAM, 80GB SSD

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-11b

### Reverse proxy:

Nginx (as delivered out of box by setup script)

### Logs of git diff:

```text
no
```

### Logs of iptables -L -vn:

```text
not neccesary to resolve issue (I suppose)
```

### Logs of ip6tables -L -vn:

```text
not neccesary to resolve issue (I suppose)
```

### Logs of iptables -L -vn -t nat:

```text
not neccesary to resolve issue (I suppose)
```

### Logs of ip6tables -L -vn -t nat:

```text
not neccesary to resolve issue (I suppose)
```

### DNS check:

```text
not neccesary to resolve issue (I suppose)
```

**Comment by DerLinkman** [comment]
Will be fixed in 2022-12.

It´s due to the Old Nextcloud Version which is installed (22/23 if i´m correctly informed).
