### ISSUE TITLE
I dont know how to setup the dns stuff

### ISSUE THREAD

**Issue by JohniClark** [mailcow/mailcow-dockerized#491]
hello, could someone explain me how to set up all the dns stuff for the hoster chronobit

**Comment by ghost** [comment]
I do not know how the whole thing looks at your host, but you have to direct the subdomain mail.yourdomain.com with an A record to the ip of your server. Then you still have autodiscover.yourdomain.com and autoconfig.yourdomain.com as cname entry on mail.yourdomain.com. And the mx entry you also on mail.yourdomain.com as far as I know.

**Comment by chaosbunker** [comment]
I recommend to submit a [ticket](https://int.chronobit.net/submitticket.php?step=2&deptid=1) to chronobit, they should be able to answer the question.

As soon as you know where to go, head to the mailcow-docs and follow [the instructions](https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/) on how to set up dns
