### ISSUE TITLE
Minor blemish in the UI

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4913]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
If SOLR was disabled should be adjusted:
- Something is missing in the brackets next to "solr-mailcow" or should be hidden.
- Disk I/O and Net I/O should be hidden because nothing is displayed here.
- "Started on", should be hidden because it is not started, this also results in the "Invalid Date".

See screenshot:
https://i.imgur.com/F1quP6B.png

PS. Otherwise it looks quite nice.

Thanks in advance.
```

### Logs:

```plain text
Not needed here...
```

### Steps to reproduce:

```plain text
Login and see when SOLR is deactivated :)
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04.5 LTS

### Server/VM specifications:

VM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12

### Reverse proxy:

NO

### Logs of git diff:

```plain text
Not needed here...
```

### Logs of iptables -L -vn:

```plain text
Not needed here...
```

### Logs of ip6tables -L -vn:

```plain text
Not needed here...
```

### Logs of iptables -L -vn -t nat:

```plain text
Not needed here...
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Not needed here...
```

### DNS check:

```plain text
Not needed here...
```

**Comment by DerLinkman** [comment]
Thanks for your feedback!

**Comment by DerLinkman** [comment]
Will fixed in: https://github.com/mailcow/mailcow-dockerized/commit/3281b97ea9123bcda388c261013e96aa7bdaf6a4
