### ISSUE TITLE
update_compose.sh broken - Moocember Update 2022

### ISSUE THREAD

**Issue by BigMichi1** [mailcow/mailcow-dockerized#4917]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
after upgrading to 2022-12 the helper script to update docker-compose does not work anymore


 ✘ ⚡ root@v2202202168392178883  /opt/mailcow-dockerized   master  ./helper-scripts/update_compose.sh
./helper-scripts/update_compose.sh: line 75: syntax error: unexpected end of file
```
```


### Logs:

```plain text
./helper-scripts/update_compose.sh: line 75: syntax error: unexpected end of file
```

### Steps to reproduce:

```plain text
1. clone master
2. run `./helper-scripts/update_compose.sh`
3. syntax error appears
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

32GB, 6 Cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

2.14.0

### mailcow version:

2022-12

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
diff --git a/data/conf/phpfpm/php-conf.d/opcache-recommended.ini b/data/conf/phpfpm/php-conf.d/opcache-recommended.ini
index 3c51e11b..ee5763be 100644
--- a/data/conf/phpfpm/php-conf.d/opcache-recommended.ini
+++ b/data/conf/phpfpm/php-conf.d/opcache-recommended.ini
@@ -1,7 +1,7 @@
 opcache.enable=1
 opcache.enable_cli=1
-opcache.interned_strings_buffer=16
-opcache.max_accelerated_files=10000
-opcache.memory_consumption=128
+opcache.interned_strings_buffer=32
+opcache.max_accelerated_files=20000
+opcache.memory_consumption=256
 opcache.save_comments=1
 opcache.revalidate_freq=1
diff --git a/docker-compose.yml b/docker-compose.yml
index b940b336..5f6c4110 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -583,36 +583,6 @@ services:
           aliases:
             - ofelia

-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by DerLinkman** [comment]
Will be fixed in 2022-12a
