### ISSUE TITLE
Worse UX for editing mailboxes

### ISSUE THREAD

**Issue by markus-gitdev** [mailcow/mailcow-dockerized#4919]
### Summary

With the new update (Bootstrap 5), the UX is slightly worse for editing mailboxes.

If you edit a mailbox at the bottom, there is a big area, which doesn't show context by default.
It only shows content if you select "ACL (Permission)" or "Rate limit" at the top.

This is kind of confusing since it seems like a tab, but doesn't open as a separate page ...

Even worse: You can click within this empty space and hit a hidden field or button.

### Motivation

Prevent users from accidental changes of settings, that are hidden and improve UX by either:

1. Display the settings by default and disable the tabs for "ACL (Permission)" and "Rate limit".
2. Don't let the settings be active (but hidden) and implement it as tab-functionality (new site for chosen option).

**Comment by FreddleSpl0it** [comment]
There is definitely something broken. With the new pushover variable a `</code>` tag got lost, which broke the layout.

Will be fixed in 2022-12a
