### ISSUE TITLE
UI BUG - Footer not centered

### ISSUE THREAD

**Issue by kcastner** [mailcow/mailcow-dockerized#4929]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
If I write my own text to mailcow footer, I can center it via a class called "text-center".
This class got centered in older versions until upgrade to bootstrap 5.
```

### Logs:

```plain text
no logs according to UI-BUG
```

### Steps to reproduce:

```plain text
1. Set custom footer
2. Set it like the end of this block
3. Got .e.g to login page
4. Take a ruler and recheck :D

Footer:
<div class="jumbotron text-center">
        <ul class="text-center" style="list-style-type: none;">
<li><h1 style="color:red;">!!! Privater Mailserver !!!</h1></li>
<li><h3>Impressum</h3></li>
<li><h4>Angaben gemäß § 5 TMG:</h4></li>
<li>NAME</li>
<li><h4>Postanschrift:</h4></li>
<li>STRAßE</li>
<li>PLZ/ORT</li>
<li><h4>Kontakt:</h4></li>
<li>E-Mail: CONTACTME</li>
        </ul>
</div>
```

### Which branch are you using?

master

### Operating System:

Debian GNU/Linux 11 (bullseye)

### Server/VM specifications:

8GB, 4 Core

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### DNS check:

```plain text
151.101.65.69
151.101.1.69
151.101.193.69
151.101.129.69
```

**Comment by tomudding** [comment]
This is because Bootstrap 5 has this new default style:

```css
ol,
ul {
    padding-left: 2rem;
}
```

You should add the class `list-unstyled` to the `<ul>` tag. This removes the padding and it also removes the list style (so you don't need `style="list-style-type: none;"`).

**Comment by kcastner** [comment]
> This is because Bootstrap 5 has this new default style:
> 
> ```css
> ol,
> ul {
>     padding-left: 2rem;
> }
> ```
> 
> You should add the class `list-unstyled` to the `<ul>` tag. This removes the padding and it also removes the list style (so you don't need `style="list-style-type: none;"`).

I tried your suggestion - still not centered

**Comment by tomudding** [comment]
> > This is because Bootstrap 5 has this new default style:
> > ```css
> > ol,
> > ul {
> >     padding-left: 2rem;
> > }
> > ```
> > You should add the class `list-unstyled` to the `<ul>` tag. This removes the padding and it also removes the list style (so you don't need `style="list-style-type: none;"`).
> 
> I tried your suggestion - still not centered

![Screenshot 2022-12-27 at 15-34-44 Mailcow Footer](https://user-images.githubusercontent.com/4983571/209681568-95c95e8f-3383-4368-8275-c09f7db405d1.png)

This instance is on 2022-12b without any modifications, using your code and my suggestion I get the following footer. I measured the pixels from the red text to both sides of the image (which is the whole page) and in both instances I get exactly 721 pixels, suggesting that the footer is properly centred.

**Comment by kcastner** [comment]
> > > This is because Bootstrap 5 has this new default style:
> > > ```css
> > > ol,
> > > ul {
> > >     padding-left: 2rem;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You should add the class `list-unstyled` to the `<ul>` tag. This removes the padding and it also removes the list style (so you don't need `style="list-style-type: none;"`).
> > 
> > 
> > I tried your suggestion - still not centered
> 
> ![Screenshot 2022-12-27 at 15-34-44 Mailcow Footer](https://user-images.githubusercontent.com/4983571/209681568-95c95e8f-3383-4368-8275-c09f7db405d1.png)
> 
> This instance is on 2022-12b without any modifications, using your code and my suggestion I get the following footer. I measured the pixels from the red text to both sides of the image (which is the whole page) and in both instances I get exactly 721 pixels, suggesting that the footer is properly centred.

After a restart of mailcow it works - i think it was regarding to the cache of the webserver. 

Okay, i got it. Its not a real mailcow bug - its related to the new bootstrap ui.

Looks great now, thank you!
