### ISSUE TITLE
Set Volume Storage On Another directory

### ISSUE THREAD

**Issue by Bersam** [mailcow/mailcow-dockerized#493]
How can i set mailcow storage on another directory? should i change docker-compose yaml file or i can set it somewhere in configs?

**Comment by mkuron** [comment]
You can change the main docker configuration file (/etc/default/docker on Debian) to add `--data-root=/path/to/somewhere`. Alternatively, you can mount another filesystem or symlink another directory to /var/lib/docker/volumes.

**Comment by Bersam** [comment]
@mkuron Thank you :+1:
