### ISSUE TITLE
Server IPs via Admin Panel got sent to another server

### ISSUE THREAD

**Issue by kcastner** [mailcow/mailcow-dockerized#4930]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
If you log in to the new UI your IP will be shown there; as I understood, script in background queries another server to show the right ip of the current mailcow server.

according to this - will the SAL be checked without of a license set? if yes, this is a problem too

```

### Logs:

```plain text
NO LOGS - i dont know how to log this special issue
```

### Steps to reproduce:

```plain text
1. Login to a mailcow instance as admin
2. The server will query a other server which will output the currently used ip.
```

### Which branch are you using?

master

### Operating System:

NOT RELEVANT

### Server/VM specifications:

NOT RELEVANT

### Is Apparmor, SELinux or similar active?

NOT RELEVANT

### Virtualization technology:

NOT RELEVANT

### Docker version:

NOT RELEVANT

### docker-compose version or docker compose version:

NOT RELEVANT

### mailcow version:

2022-12b

### Reverse proxy:

NOT RELEVANT

### Logs of git diff:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### DNS check:

```plain text
NOT RELEVANT
```

**Comment by h4ndi** [comment]
On the login page there is although a call to:
"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,700;1,400&display=swap"

**Comment by kcastner** [comment]
> 

On what site do you see this request? my local installation and some productiv used ones dont connect to it - maybe you can provide steps to reproduce it, please?

**Comment by h4ndi** [comment]
I use Mailcow 2022-12b
I could reproduce it in Firefox 108.0.1 and Chromium 108

Open private browsing mode (clear cache) and press F12, go to network analyse and call the Mailcow login page (you have to be logged off):

![2022-12-29-191230_770x361_scrot](https://user-images.githubusercontent.com/3900533/209992710-5c636dc9-e103-427e-aaab-516cf32d103e.png)

**Comment by kcastner** [comment]
> I use Mailcow 2022-12b I could reproduce it in Firefox 108.0.1 and Chromium 108
> 
> Open private browsing mode (clear cache) and press F12, go to network analyse and call the Mailcow login page (you have to be logged off):
> 
> ![2022-12-29-191230_770x361_scrot](https://user-images.githubusercontent.com/3900533/209992710-5c636dc9-e103-427e-aaab-516cf32d103e.png)

Ok - got it! It was cached by a plugin on my browser

**Comment by speedmann** [comment]
I'm pretty sure GDPR can't be applied on a server.

```
This Regulation lays down rules relating to the protection of *natural persons* with regard to the processing of personal data and rules relating to the free movement of personal data.
```

Otherwise i hope you disabled *all* blacklist checks as you yourself are breaking GDPR rules here...

**Comment by kcastner** [comment]
> I'm pretty sure GDPR can't be applied on a server.
> 
> ```
> This Regulation lays down rules relating to the protection of *natural persons* with regard to the processing of personal data and rules relating to the free movement of personal data.
> ```
> 
> Otherwise i hope you disabled _all_ blacklist checks as you yourself are breaking GDPR rules here...

The Problem there is, that the IP of an user will be transmitted to another Server; the blacklist checks will only transmit my server's address to another server - this is my problem, not the senders one. 

Regarding to your suggestion: an sender adress normaly is "well known". A user's IP isnt. Thats the difference.

**Comment by mritzmann** [comment]
> The Problem there is, that the IP of an user will be transmitted to another Server

I don't think so. As far as I can see, this is done on the server side. The user's browser requests the IP address from your server at an API endpoint of your own mailcow (`<YOUR-MAILCOW-DOMAIN>/api/v1/get/status/host/ip`). The server may then use an external service for this, but at the same time serves as an middleman. When I look at my browser's developer tools, I don't see where my IP address is supposed to be transmitted to an external service.

Here is the corresponding position in the code. The user/browser contacts your own(!) server:

https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/js/site/debug.js#L1228-L1230

The server then makes the query on the server side:

https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/json_api.php#L1548-L1554

In this way, the IP address of the end user is not transmitted to an external service.

**Comment by kcastner** [comment]
We are talking about two issues here...

The first one, is like i mentioned at the topic: "Server IPs via Admin Panel got sent to another server" - if its DSGVO im not sure anymore.

As you wrote:
> [...] API endpoint (`<YOUR-MAILCOW-DOMAIN>/api/v1/get/status/host/ip`). The server may then use an external service for this, [...]

Thats right - according to the source, the official mailcow server gets queried (http://ipv4.mailcow.email, http://ipv6.mailcow.email) at loading the page from my servers backend. Side-Note: its http - no https
Im not sure if everybody wants to connect to a third-party server, only to get the current ips without any notice of.
Maybe some users dont want to connect to a third-party server.

Regarding to @DerLinkman there should be a no-log-policy at the remote server.


The second problem like @h4ndi wrote, is a client based one - there will be a query to google without user consent at opening the mailcow ui.

This issue should be at a new GH-issue

**Comment by mritzmann** [comment]
> The first one, is like i mentioned at the topic: "Server IPs via Admin Panel got sent to another server" - if its DSGVO im not sure anymore. (..) Maybe some users dont want to connect to a third-party server.

Mailcow connects to external services at various points, some of which seem unavoidable to me. For example:

* rspamd checks against various blacklists
* clamav updates the database regularly
* the update script first checks whether an internet connection exists
* the docker images are loaded from docker hub
* if you build the imagas yourself you download packages from debian
* and new: to display your servers ip address

But I agree with you that the new ip-check reveals a problem:

Theoretically, Mailcow (the owner of `ipv4.mailcow.email` and `ipv6.mailcow.email`) now sees how often an admin of a Mailcow instance logs in. Looks to me like a feature without bad intentions but I now also understand your concerns.

> will be a query to google without user consent at opening the mailcow ui. (..) This issue should be at a new GH-issue

I think so too. Here is the corresponding position in the code:

https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/css/themes/lumen-bootstrap.css#L14

**Comment by mritzmann** [comment]
> will be a query to google without user consent at opening the mailcow ui. (..) This issue should be at a new GH-issue

created an issue: #4959

**Comment by kcastner** [comment]
> [...] which seem unavoidable to me [...]

For my site im fine to it.
I dont use clamav. some of my instances neither use clamav nor rspamd either - it would be nice if there would be a toggle too.

> But I agree with you that the new ip-check reveals a problem:
> 
> Theoretically, Mailcow (the owner of ipv4.mailcow.email and ipv6.mailcow.email) now sees how often an admin of a Mailcow instance logs in. Looks to me like a feature without bad intentions but I now also understand your concerns.

It could be tracked, but as you mentioned i dont think they have bad intentions to. A clarification of this via a hint/consent etc. would be okay to me. 
What about the case law? Do you know something about it?


Thx for opening a new issue - I would have done it myself right away

**Comment by mritzmann** [comment]
> What about the case law? Do you know something about it?

As a Swiss citizen, I don't know the German laws. And I am not an expert. I only know that there will be a new [data protection law](https://www.fedlex.admin.ch/eli/cc/2022/491/de) here in Switzerland from September 2023 (we are slowly adapting to the EU). However, Switzerland is less strict than Germany or the EU. We are allowed to use "Personendaten" (not to be confused with "besonders schützenswerte Personendaten") without user consent, as long as this is indicated in a Datenschutzerklärung. 

But outsourcing "Personendaten" (sending it on to third parties) is another thing. However, I would argue that the IP address of a server does not fall under "Personendaten". But again, I am not an expert. I don't know anything about that.

**Comment by kcastner** [comment]
Ah okay. I dont know the deep difference between both. Maybe there is someone who can clarify this.

**Comment by kcastner** [comment]
> But outsourcing "Personendaten" (sending it on to third parties) is another thing. However, I would argue that the IP address of a server does not fall under "Personendaten". But again, I am not an expert. I don't know anything about that.

The IP of a server AFAIK wont fall under "Personendaten" - the law is changing - im not sure if this would be a problem right now.

As you mentioned: as you said - neither you nor i are experts in the subject area

I hope the concern of my opened issue is now clarified - lets wait for an professional

**Comment by maxcodeshere** [comment]
I would agree with @mritzmann on the issue because of a number of reasons. The first one being that you could argue that a server IP is not personal data (Art. 4 (1) GDPR). According to the European Court of Justice [on that matter](https://curia.europa.eu/juris/document/document.jsf?docid=184668&mode=req&pageIndex=1&dir=&occ=first&part=1&text=&doclang=EN&cid=314387), an IP address, in this case dynamic, can only be considered personal data if the receiver of the IP address has the technical _and_ legal means to reveal the natural person behind the IP address. To my knowledge The Infrastructure Company GmbH does not log any access to the aforementioned URLs, which means that the technical means are not present. Although I have to be honest and say that most of my fellow data protection nerds would probably not agree to me :P


The second reason, and the stronger at that, is that, once you host mailcow yourself, you yourself are the controller of the processing of personal data with regards to the GDPR. It would be your responsibility as the controller to take care of the means of data processing. The consequence is that you yourself would need to decide if you want your cow to access TINC's URLs. If not, you yourself would be responsible to block the connection or customize the code. 


Seeing that I'm a little late to the discussion: @FreddleSpl0it already took care of that in #4966 and gave admins the means to decide when a connection is being made to TINC's URLs.

I think this issue can be closed now.

**Comment by DerLinkman** [comment]
Oh yeah. i missed that issue because i've closed several issues which will be fixed within 2023-01 this midday.
