### ISSUE TITLE
Admin UI - Protocol - select one - Action - fold/unfold is displayed continuously although it is not necessary

### ISSUE THREAD

**Issue by kcastner** [mailcow/mailcow-dockerized#4933]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Under following path
Admin UI - Protocol - select an item - Action
you can fold/unfold all items in the list. Some lists like postfix, dovecot and sogo wont expand anything. As I get, its not necessary there.

Maybe items like fold/unfold can be removed there - otherwise these buttons should be fixed.
```

### Logs:

```plain text
NO LOGS
```

### Steps to reproduce:

```plain text
1. Login to Admin UI
2. Go to Protocol - 
3. Select e.g. postfix
4. Click Action
5. Click fold/unfold
```

### Which branch are you using?

master

### Operating System:

NOT RELEVANT

### Server/VM specifications:

NOT RELEVANT

### Is Apparmor, SELinux or similar active?

NOT RELEVANT

### Virtualization technology:

NOT RELEVANT

### Docker version:

NOT RELEVANT

### docker-compose version or docker compose version:

NOT RELEVANT

### mailcow version:

2022-12b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### DNS check:

```plain text
151.101.65.69
151.101.129.69
151.101.1.69
151.101.193.69
```

**Comment by FreddleSpl0it** [comment]
Keep in mind that the tables will adjust when resizing. On mobile for example there will be child rows that you can expand

**Comment by FreddleSpl0it** [comment]
will be added in 2023-01 https://github.com/mailcow/mailcow-dockerized/commit/8782304e8dea57fc7991af0654f3f89c48ba2792
