### ISSUE TITLE
UI Bug - loading email configuration will not automaticly set Domains-Tab active

### ISSUE THREAD

**Issue by kcastner** [mailcow/mailcow-dockerized#4938]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
If you log in to the Admin UI and click E-Mail - Configuration the first tab will not be set as active
```

### Logs:

```plain text
NO LOGS
```

### Steps to reproduce:

```plain text
1. Login to Admin UI
2. Click E-Mail
3. Click Configuration
4. Check the Tabs of current page - nothing will be active
```

### Which branch are you using?

master

### Operating System:

NOT RELEVANT

### Server/VM specifications:

NOT RELEVANT

### Is Apparmor, SELinux or similar active?

NOT RELEVANT

### Virtualization technology:

NOT RELEVANT

### Docker version:

NOT RELEVANT

### docker-compose version or docker compose version:

NOT RELEVANT

### mailcow version:

2022-12b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn:

```plain text
NOT RELEVANT
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT RELEVANT
```

### DNS check:

```plain text
151.101.65.69
151.101.129.69
151.101.1.69
151.101.193.69
```

**Comment by DerLinkman** [comment]
Will be fixed in 2023-01
