### ISSUE TITLE
SSL Cert expired

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#494]
Hi, my SSL Cert is expired....
What should I do?

**Comment by RobinFlikkema** [comment]
If you're using the built-in Let's encrypt, check the log of the letsencrypt container.

**Comment by stevesbrain** [comment]
If I understand correctly, the acme container handles the renewal at the appropriate time - have you tried running an update/restart?

**Comment by Braintelligence** [comment]
I guess the acme container is unable to serve the well-known stuff to the certificate checking process. Did you somehow change the nginx settings or make your own?
