### ISSUE TITLE
UI - Sync Jobs - wrong sorting

### ISSUE THREAD

**Issue by Xotetb** [mailcow/mailcow-dockerized#4942]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After update from 2022-11b to 2022-12b on Sync Jobs page
Table sorting set by default (after refresh page) by Onwer, not by ID.
The first column selector is weird, it doesn't match anything and will disappear after sorting by another column.
```

### Logs:

```plain text
NO LOGS
```

### Steps to reproduce:

```plain text
1. Login to Admin UI
2. Go to E-Mail - Configuration - Sync jobs
3. Look at sync jobs table, is sorted by Name and the first column selector is redundant
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04

### Server/VM specifications:

4CPU/8GB

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

VMware

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.13.0

### mailcow version:

2022-12b

### Reverse proxy:

no

### Logs of git diff:

```plain text
NO LOGS
```

### Logs of iptables -L -vn:

```plain text
NO LOGS
```

### Logs of ip6tables -L -vn:

```plain text
NO LOGS
```

### Logs of iptables -L -vn -t nat:

```plain text
NO LOGS
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NO LOGS
```

### DNS check:

```plain text
NO LOGS
```

**Comment by Xotetb** [comment]
![image](https://user-images.githubusercontent.com/54398257/209968081-1b939de8-05f4-483c-bfbb-6960d6b29910.png)
![image](https://user-images.githubusercontent.com/54398257/209968114-22f24501-34d3-452c-9661-d6b56e6b3447.png)

**Comment by tomudding** [comment]
This is because DataTables always marks the first column as the primary sorting column (and thus adds sorthing thingy). This column does not have any data and will therefore not sort anything.
