### ISSUE TITLE
Readability issues in Mailcow UI Quarantine view (dark mode)

### ISSUE THREAD

**Issue by accolon** [mailcow/mailcow-dockerized#4944]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When enabling Dark Mode, some fields in the Quarantine view in Mailcow UI are difficult to read, namely "Recipients" and the two "Sender" fields.

(See screenshot below, the form doesn't allow attaching images...)
```

### Logs:

```plain text
n/a
```

### Steps to reproduce:

```plain text
1. Enable Dark Mode.
2. Go to E-Mail / Quarantine.
3. Click "Show item" next to a quarantined item.
```

### Which branch are you using?

master

### Operating System:

n/a

### Server/VM specifications:

n/a

### Is Apparmor, SELinux or similar active?

n/a

### Virtualization technology:

n/a

### Docker version:

n/a

### docker-compose version or docker compose version:

n/a

### mailcow version:

2022-12b

### Reverse proxy:

n/a

### Logs of git diff:

```plain text
n/a
```

### Logs of iptables -L -vn:

```plain text
n/a
```

### Logs of ip6tables -L -vn:

```plain text
n/a
```

### Logs of iptables -L -vn -t nat:

```plain text
n/a
```

### Logs of ip6tables -L -vn -t nat:

```plain text
n/a
```

### DNS check:

```plain text
n/a
```

**Comment by accolon** [comment]
<img width="333" alt="quarantine" src="https://user-images.githubusercontent.com/126886/210009173-550e7459-1ffb-4a44-8587-f683dea2f476.png">

**Comment by DerLinkman** [comment]
Will be fixed in 2023-01
