### ISSUE TITLE
Move Mailboxes Between Domains

### ISSUE THREAD

**Issue by Bersam** [mailcow/mailcow-dockerized#495]
Hi there, I've created a domain with mail2.sample.co. I want to create another one with mail.sample.co and move all mailboxes in mail2.sample.co to mail.sample.co, is it possible?

**Comment by janxb** [comment]
I think the GUI has no option for this. Maybe you can move the mailboxes manually in the MySQL Database. You also have to move the physical mail files in the vmail docker volume.

Questions like this you can also post in our forum at https://forum.mailcow.email/ :)

**Comment by Braintelligence** [comment]
That's why I run mailcow in its own VM. I can just backup the whole VM and move it to another hypervisor. 
It takes about 5-10 minutes to get it running on another location this way.

**Comment by Bersam** [comment]
@janxb Thanks, I saw tables and physical mail files and it's easy task to do. I just need to test it with an account so it doesn't broke connectivity of my mail accounts.
@Braintelligence That doesn't solve my problem, I don't want to move mailcow to another hypervisor, i want to move mailboxes between domains (subdomains actually) of one mailcow instance.

**Comment by Braintelligence** [comment]
@bersam Maybe you could do this via domain alias without moving?
