### ISSUE TITLE
Quarantine list "Show n entries" and table sorting not persisted across delete-actions

### ISSUE THREAD

**Issue by skyschub** [mailcow/mailcow-dockerized#4951]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
This is a regression from the MUH-I update. Previously, the value for the select field persisted across multiple actions, now it doesn't.
```

### Logs:

```plain text
n/a
```

### Steps to reproduce:

```plain text
1. Have lots of emails in quarantine.
2. Select "Show 100 entries" in the quarantine view.
3. Scroll down, toggle all, and select the "Learn as spam and delete" action.

Expected:

The mails get deleted, and the list shows 100 mails again.

Actual:

The list has now switched back to showing only 10 emails.
```

### Which branch are you using?

master

### Operating System:

n/a

### Server/VM specifications:

n/a

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

n/a

### Docker version:

n/a

### docker-compose version or docker compose version:

n/a

### mailcow version:

2022-12b

### Reverse proxy:

n/a

### Logs of git diff:

```plain text
n/a
```

### Logs of iptables -L -vn:

```plain text
n/a
```

### Logs of ip6tables -L -vn:

```plain text
n/a
```

### Logs of iptables -L -vn -t nat:

```plain text
n/a
```

### Logs of ip6tables -L -vn -t nat:

```plain text
n/a
```

### DNS check:

```plain text
n/a
```

**Comment by skyschub** [comment]
Just realized that this also affects the table's sorting.

**Comment by BombusAlpinus** [comment]
quarantaine log is currently really hard to use. especially time based sorting doesnt work properly. 
here's an example which should be sorted descending:

![image](https://user-images.githubusercontent.com/28042236/210211657-4042e303-6601-4e09-a151-1946677c5be8.png)

and there are also differences depending on the amount of entries choosen (10, 25, 50, 100)

**Comment by DerLinkman** [comment]
Will fixed in 2023-01
