### ISSUE TITLE
Unable to donate to mailcow by buying a SAL (unable to register)

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#4955]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I am attempting to donate to the project by purchasing a mailcow Stay-Awesome-License (SAL), but I am being redirected to a login page (https://cp.servercow.de/client/login/) that does not offer an option to register. Is there a way for me to create an account and complete the donation process?

### Logs:

```plain text
N/A
```

### Steps to reproduce:

```plain text
1. On the admin interface, I click on the "Register your GUID here" button.
2. I choose the mailcow Stay-Awesome-License (SAL) option.
3. I click on the "Order now" button.
4. On the https://cp.servercow.de/client/login/ page, there is no option to register.
```

### Which branch are you using?

master

### Operating System:

Debian GNU/Linux 11 (bullseye) x86_64

### Server/VM specifications:

7767MiB, Intel Xeon (Skylake, IBRS) (2) @ 2.294GHz

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by DerLinkman** [comment]
The Links to buy the SAL have been changed but we still used the old ones. Thanks for noticing!
