### ISSUE TITLE
Mailbox quota sorting sorts alphabetically, not numerically

### ISSUE THREAD

**Issue by skyschub** [mailcow/mailcow-dockerized#4957]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
In the mailbox setup, with the MUH-I update, sorting the list of mailboxes by quota results in an alphabetical sort, instead of sorting by value. I.e., the table is sorted "1 megabyte, 2 byte, 3 gigabyte"
```

### Logs:

```plain text
n/a
```

### Steps to reproduce:

```plain text
1. Open the mailbox list
2. Sort by quota
```

### Which branch are you using?

master

### Operating System:

n/a

### Server/VM specifications:

n/a

### Is Apparmor, SELinux or similar active?

n/a

### Virtualization technology:

n/a

### Docker version:

n/a

### docker-compose version or docker compose version:

n/a

### mailcow version:

2022-12b

### Reverse proxy:

n/a

### Logs of git diff:

```plain text
n/a
```

### Logs of iptables -L -vn:

```plain text
n/a
```

### Logs of ip6tables -L -vn:

```plain text
n/a
```

### Logs of iptables -L -vn -t nat:

```plain text
n/a
```

### Logs of ip6tables -L -vn -t nat:

```plain text
n/a
```

### DNS check:

```plain text
n/a
```

**Comment by tomudding** [comment]
Can be fixed similarly to the score attribute for Rspamd in #4914. It requires a hidden attribute with a normalized value that is used for the actual sorting.

**Comment by FreddleSpl0it** [comment]
> Can be fixed similarly to the score attribute for Rspamd in #4914. It requires a hidden attribute with a normalized value that is used for the actual sorting.

@tomudding tried this but somehow it is not gonna work. i think datatables still thinks sortBy and orderBy is a string and not a number. Setting `type: "num"` also dont work. I ended up creating a hidden cell which shows the plain `item.quota` and then set orderData to this cell.

**Comment by tomudding** [comment]
> > Can be fixed similarly to the score attribute for Rspamd in #4914. It requires a hidden attribute with a normalized value that is used for the actual sorting.
> 
> @tomudding tried this but somehow it is not gonna work. i think datatables still thinks sortBy and orderBy is a string and not a number. Setting `type: "num"` also dont work. I ended up creating a hidden cell which shows the plain `item.quota` and then set orderData to this cell.

I have not fully tested this and it is a bit difficult to determine the best way to sort*. But if you use

```js
createdCell: function(td, cellData) {
  cellData = cellData.split("/");
  $(td).attr({
    "data-order": cellData[0],
    "data-sort": cellData[0]
  });

  $(td).html(humanFileSize(cellData[0]) + " / " + (cellData[1] == 0 ? "∞" : humanFileSize(cellData[1])));
}
```

instead of

https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/js/site/mailbox.js#L936-L940

you can sort on the `quota_used` attribute. This sorting is on the number of bytes, an example sorting would be (ascending):

- 0 B / 10.0 GB
- 0 B / 512.0 MB
- 10 B / ∞
- 20.0 MB / 2.0 GB
- 25.0 MB / 1.5 GB
- 1.0 GB / 1.0 GB

Clearly, (*) you ideally also want to so some sorting based on the `qouta` attribute (the 512MB should come before 10GB imho), but I do not think there is a proper way of doing this.

**Comment by FreddleSpl0it** [comment]
that's what i did. the result is the following (tried sorting by max_quota)
after a bit of try and error i ended up using a hidden col with the plain value (max_quota) for sorting
![dt_sort_issue](https://user-images.githubusercontent.com/75116288/211030220-e52f9967-fd25-4afc-aca6-70ba328ba003.png)

**Comment by DerLinkman** [comment]
Will fixed in 2023-01
