### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#4959]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Mailcow loads Google Fonts from Google servers.

* This can be a problem for privacy reasons.
* This can be a problem for legal reasons.
```

### Logs:

```plain text
Doesn't matter for this issue
```

### Steps to reproduce:

```plain text
1. Open https://demo.mailcow.email/
2. Open Developer Tools of your Browser
3. Navigate to the "Network"-Tab of your Developer Tools
4. Filter for `fonts.googleapis.com`
5. Reload Page

You will see a GET request to Google.

See also:

https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/css/themes/lumen-bootstrap.css#L14
```

### Which branch are you using?

master

### Operating System:

Doesn't matter for this issue

### Server/VM specifications:

Doesn't matter for this issue

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.21

### docker-compose version or docker compose version:

Doesn't matter for this issue

### mailcow version:

2022-12b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
Doesn't matter for this issue
```

### Logs of iptables -L -vn:

```plain text
Doesn't matter for this issue
```

### Logs of ip6tables -L -vn:

```plain text
Doesn't matter for this issue
```

### Logs of iptables -L -vn -t nat:

```plain text
Doesn't matter for this issue
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Doesn't matter for this issue
```

### DNS check:

```plain text
Doesn't matter for this issue
```

**Comment by DerLinkman** [comment]
Will fixed in 2023-01
