### ISSUE TITLE
oauth2: authorization POST request being redirected (302)

### ISSUE THREAD

**Issue by beerlao** [mailcow/mailcow-dockerized#4963]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I'm running nextcloud and mailcow on 2 distinct servers in separated networks. I'm trying to authorize nextcloud against mailcow, but no luck. It seems that the authorization request on Mailcloud's end (oauth/authorize) is being redirected (HTTP status 302) which causes the POST payload to be lost (https://rtfm.co.ua/en/http-redirects-post-and-get-requests-and-lost-data/). It seems that the 302 comes from

`header('Location: ' . $response->getHttpHeader('Location'));`

in

`data/web/oauth/authorize.php`

Mailcow is bound directly to my external IP (so no reverse proxy), Nextcloud is running as fpm on docker behind a nginx proxy.

Social Login on Nextcloud's end shows 

`Unable to exchange code for API access token. HTTP error 405. Raw Provider API response: .`

### Logs (docker logs mailcowdockerized-nginx-mailcow-1):

```plain text
xx.xx.xx.xx - - [04/Jan/2023:11:32:52 +0100] "GET /oauth/authorize?response_type=code&client_id=008084b445be&redirect_uri=https%3A%2F%2Fnc.xxx.net%2Fapps%2Fsociallogin%2Fcustom_oauth2%2FMailcow&scope=profile&state=HA-U8L2D47IOTXC516RQHYWS09PNMVFK3EGBZAJ HTTP/2.0" 200 115996
xx.xx.xx.xx - - [04/Jan/2023:11:32:53 +0100] "GET /api/v1/get/passwordpolicy/html HTTP/2.0" 200 97
xx.xx.xx.xx - - [04/Jan/2023:11:32:54 +0100] "POST /oauth/authorize?response_type=code&client_id=008084b445be&redirect_uri=https%3A%2F%2Fnc.xxx.net%2Fapps%2Fsociallogin%2Fcustom_oauth2%2FMailcow&scope=profile&state=HA-U8L2D47IOTXC516RQHYWS09PNMVFK3EGBZAJ HTTP/2.0" 302 0
```

### Steps to reproduce:

```plain text
1. Install Nextcloud on a different server and in a different network.
2. Connect Nextcloud to Mailcow via oauth 2 according to https://docs.mailcow.email/third_party/nextcloud/third_party-nextcloud/#configure-nextcloud-to-use-mailcow-for-authentication
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

64GB

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

-

### Docker version:

20.10.21

### docker-compose version or docker compose version:

2.12.2

### mailcow version:

-

### Reverse proxy:

-

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by beerlao** [comment]
Sorry, was a misconfiguration on my end. Closed this.

**Comment by amour86** [comment]
> Sorry, was a misconfiguration on my end. Closed this.

would you please tell me what was the issue

**Comment by beerlao** [comment]
> > Sorry, was a misconfiguration on my end. Closed this.
> 
> would you please tell me what was the issue

My DNS was misconfigured, assigned the wrong IP for my Nextcloud instance.
