### ISSUE TITLE
dns not working inside container

### ISSUE THREAD

**Issue by maydaylive** [mailcow/mailcow-dockerized#497]
I finished today installing mailcow and when testing delivery i found that all containers other then unbound do not have working dns.

It seems the -dns option is not being taken into account and all instances have the dns set to 127.0.0.11 rather then 172.22.1.254

Centos 7
docker -v
Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.15.0, build e12f3b9

Postfix Log

804FE6641633: to=<x@tutanota.com>, relay=none, delay=3613, delays=3588/5.1/20/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=tutanota.com type=MX: Host not found, try again)

docker exec -it 62b53245e61d  bash
root@zeus:/# cat /etc/resolv.conf
search mailcow-network
nameserver 127.0.0.11
options ndots:0

**Comment by K2rool** [comment]
Dns being set to nameserver 127.0.0.11 is normal in the containers the request still gets sent to Unbound at 172.22.1.254.

Is unbound container running.

**Comment by rafix1989** [comment]
I Have the same problem, log from postfix 

> C5BAC5C0028: to=<email@adress.com>, relay=none, delay=88277, delays=88257/0.02/20/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=adress.com type=MX: Host not found, try again)



```
27b9500f7dee        mailcow/rspamd:1.3      "/docker-entrypoin..."   17 minutes ago      Up 17 minutes                                                                                                                                                                             mailcowdockerized_rspamd-mailcow_1
bac664953882        nginx:mainline-alpine   "/bin/sh -c 'envsu..."   17 minutes ago      Up 17 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                                                                                        mailcowdockerized_nginx-mailcow_1
24f421aa6e19        mailcow/fail2ban:1.5    "python2 -u /logwa..."   17 minutes ago      Up 17 minutes                                                                                                                                                                             mailcowdockerized_fail2ban-mailcow_1
aa4f08f8de64        mailcow/phpfpm:1.0      "/docker-entrypoin..."   17 minutes ago      Up 17 minutes             9000/tcp                                                                                                                                                        mailcowdockerized_php-fpm-mailcow_1
8027a088f948        mailcow/postfix:1.2     "/bin/sh -c 'exec ..."   17 minutes ago      Up 17 minutes             0.0.0.0:25->25/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:587->587/tcp, 588/tcp                                                                                         mailcowdockerized_postfix-mailcow_1
d0dba3ef0bcf        mailcow/sogo:1.3        "/bin/sh -c 'exec ..."   17 minutes ago      Up 17 minutes                                                                                                                                                                             mailcowdockerized_sogo-mailcow_1
4e5ee8252881        redis:alpine            "docker-entrypoint..."   17 minutes ago      Up 17 minutes             6379/tcp                                                                                                                                                        mailcowdockerized_redis-mailcow_1
3892ae44a0cd        memcached:alpine        "docker-entrypoint..."   17 minutes ago      Up 17 minutes             11211/tcp                                                                                                                                                       mailcowdockerized_memcached-mailcow_1
56ca9cc70377        mailcow/dovecot:1.4     "/docker-entrypoin..."   17 minutes ago      Up 17 minutes             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 24/tcp, 10001/tcp, 0.0.0.0:4190->4190/tcp, 127.0.0.1:19991->12345/tcp   mailcowdockerized_dovecot-mailcow_1
e7a200ae4091        mailcow/unbound:1.0     "/docker-entrypoin..."   17 minutes ago      Up 17 minutes (healthy)   53/tcp, 53/udp                                                                                                                                                  mailcowdockerized_unbound-mailcow_1
8c635a52953b        mariadb:10.1            "docker-entrypoint..."   17 minutes ago      Up 17 minutes (healthy)   3306/tcp                                                                                                                                                        mailcowdockerized_mysql-mailcow_1
cf858e9f1432        mailcow/clamd:1.1       "/bootstrap.sh"          17 minutes ago      Up 17 minutes             3310/tcp                                                                                                                                                        mailcowdockerized_clamd-mailcow_1
4135420b000c        robbertkl/ipv6nat       "/docker-ipv6nat -..."   17 minutes ago      Up 17 minutes                                                                                                                                                                             mailcowdockerized_ipv6nat_1

```

**Comment by rafix1989** [comment]
I test my mailserver and it's not working on specific domains. Most of messages goes ok , but several of them shows this error.

> C5BAC5C0028: to=email@adress.com, relay=none, delay=88277, delays=88257/0.02/20/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=adress.com type=MX: Host not found, try again)


This is very strange. What do you think andryyy ???

**Comment by askanhesse** [comment]
I got into the same issue - unbound is actually not able to resolve any DNS request. 
No matter what I try there, I getting on `nslookup google.com 127.0.0.1` an:
```
;; connection timed out; no servers could be reached
```

Only way for me to getting currently around it is by setting an forward-zone in unbound config file:
```
  forward-zone:
    name: "."
    forward-addr: 127.0.0.11
    forward-addr: 2a01:4f8:0:a0a1::add:1010
    forward-addr: 2a01:4f8:0:a111::add:9898
    forward-addr: 2a01:4f8:0:a102::add:9999
```
Which will lead to docker dns recursor and then to the dns recursor of my hoster. But probably this is not an good solution.

After that change for sure mails were able to get in and out again as in usual behavior.

**Comment by mkuron** [comment]
Does your hoster block DNS requests (UDP port 53) to any server but his own resolvers? Do you have iptables rules on the host that limit DNS traffic?

**Comment by askanhesse** [comment]
The hoster in this situation is Hetzner, as far as I know other resolvers are not blocked. For example I can also use OpenDNS without any problems while Google DNS seems to block requests from the IP range. 
I have not configurated any IPTables rules that can affect DNS requests to the outside world.

**Comment by snc** [comment]
I also had DNS issues on a Hetzner server, did not had the time to analyze it in detail, but the cause was the enabled firewall. After disabling the firewall in the Hetzner robot, it works like expected. Unfortunately Hetzner does not provide any firewall logs :-(

**Comment by askanhesse** [comment]
@snc Oh, thats interesting. I will take a look the next couple days if this could be the issue for me since I am currently also use the Hetzner Firewall. Thanks! 👍

**Comment by askanhesse** [comment]
@snc I tested this behavior and you're right. After disabling the Hetzner Service Firewall there is no problem anymore with resolving DNS over unbound even without changing the default config. 
This could be in general just an environment problem. Thank you for your Help!

**Comment by chermsen** [comment]
For all who are struggling with the Hetzner firewall:

Port 53 unimportant for the firewall configuration in this case. According to the documentation unbound uses the port range 1024-65535 for outgoing requests.
Since the Hetzner Robot Firewall is a static firewall (each incoming packet is checked isolated) - the following rules must be applied:

### For TCP
```
SRC-IP:       ---
DST IP:       ---
SRC Port:    ---
DST Port:    1024-65535
Protocol:    tcp
TCP flags:   ack
Action:      Accept
```

### For UDP
```
SRC-IP:       ---
DST IP:       ---
SRC Port:    ---
DST Port:    1024-65535
Protocol:    udp
Action:      Accept
```

If you want to apply a more restrictive port range you have to change the config of unbound first:

{mailcow-dockerized}/data/conf/unbound/unbound.conf:
`outgoing-port-avoid: 0-32767`

Now the firewall rules can be adjusted as follows:

```
[...]
DST Port:  32768-65535
[...]
```

**Comment by andryyy** [comment]
Nice. Should add this to the docs (tm).

**Comment by andryyy** [comment]
Is anybody willing to create a PR? 😄 Pleeeease.

**Comment by andryyy** [comment]
I added it to the prereqs, thank you, @chermsen !!! Very important note I totally forgot about. :(

**Comment by GwynethLlewelyn** [comment]
Hiya, Hetzner customer here as well — thanks @chermsen for catching this issue!

For those who, like me, need to run BIND9 (`named`), the configuration is similar to `unbound`.

Wherever you have the `options` section (under Debian/Ubuntu it should be `/etc/bind/named.conf.options`), add the following two lines inside that section (see https://bind9.readthedocs.io/en/latest/reference.html#query-address):

```zone
use-v4-udp-ports { range 32768 65535; };
use-v6-udp-ports { range 32768 65535; };
```

The basic idea is the same — prevent `named` from using any ports in the 1024-32767 range, and keep them in sync with what the Hetzner firewall wants...

**Comment by bonsaibauer** [comment]
I have configured the Hetzner Firewall as follows:

Incoming:
Any IPv4, Any IPv6 TCP 22
Any IPv4, Any IPv6 TCP 25
Any IPv4, Any IPv6 TCP 465
Any IPv4, Any IPv6 TCP 587
Any IPv4, Any IPv6 TCP 143
Any IPv4, Any IPv6 TCP 993
Any IPv4, Any IPv6 TCP 110
Any IPv4, Any IPv6 TCP 995
Any IPv4, Any IPv6 TCP 4190
Any IPv4, Any IPv6 TCP 80
Any IPv4, Any IPv6 TCP 443
Any IPv4, Any IPv6 ICMP

Outgoing:
Any IPv4, Any IPv6 TCP 22
Any IPv4, Any IPv6 TCP 80
Any IPv4, Any IPv6 TCP 443
Any IPv4, Any IPv6 TCP 25
Any IPv4, Any IPv6 TCP 465
Any IPv4, Any IPv6 TCP 587
Any IPv4, Any IPv6 TCP 143
Any IPv4, Any IPv6 TCP 993
Any IPv4, Any IPv6 TCP 110
Any IPv4, Any IPv6 TCP 995
Any IPv4, Any IPv6 TCP 4190
Any IPv4, Any IPv6 ICMP
Any IPv4, Any IPv6 TCP 1024-65535
Any IPv4, Any IPv6 UDP 1024-65535

However, it's not working as no mailbox is selected in SOGo. Can anyone please help?

**Comment by mplattner** [comment]
@chermsen, I just saw your comment about the Hetzner firewall and two questions came to mind:

1. You are referring to outgoing connections only, right? (No need to open incoming ports.)
2. You are pointing out its a static (=stateless) firewall. It should be the same for a stateful firewall, as the connection originates from unbound (server-side) → outside, so IF the firewall filters outgoing packets, the ports need to be opened regardless of the type of firewall, I guess.

I think the docs might be confusing for some users in that they might open incoming ports instead of outgoing.

Sidenote (as of writing this): while Hetzner's firewalls for dedicated servers are state_less_ [1], Hetzner's firewalls for cloud servers are state_ful_ [2].

[1] https://docs.hetzner.com/robot/dedicated-server/firewall/
[2] https://docs.hetzner.com/cloud/firewalls/faq/#are-cloud-firewalls-stateful

**Comment by chermsen** [comment]
@mplattner 
In case of a static/stateless firewall both directions are relevant. If you open only outgoing ports, you'll never receive an answer to your request, because there is no relation between outgoing and incoming packages. Hetzner does mention this point it in the docs:

> "A stateless firewall only makes decisions about packets by inspecting individual packets. Therefore, the firewall doesn't "keep track of" whether or not an incoming packet belongs to an established connection. For this reason, unless you enter an additional rule, all outgoing connections from the server, and if you filter outgoing pakets all incoming connections to the server, will not work, because the respective answer packets in the opposite direction can no longer pass the filter."

When i wrote the post, there was (as far as I remember) no cloud service at hetzner, but with a firewall capable of stateful packet inspection, you can (and should!) of course set up much more restrictive rules.
