### ISSUE TITLE
Add RoundCube officially, a lot of people would enjoy it I think

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#4971]
### Summary

Adding an container for RoundCube that uses SOGo Calendar and Contacts and postfix/dovecot containers for mail.

### Motivation

One reason might be that SOGo doesn't have dark mode as far as I have found. It could also potentially bring more users to mailcow who are familiar with RoundCube and/or doesn't like SOGo interface. Reason why I would like this as an official integration is due to no netfilter support for the roundcube third party solution (if there are an solution I would like to know how to make roundcube use netfilter)

**Comment by DerLinkman** [comment]
Like the idea. The question is how to implement it though.

I should precise here: It's not the HOW??, it's more like how could we integrate it seamless.

As we have to use SOGos DAV functions for CalDAV we have to look wheter SOGo is enabled or not. And what about those who've already installed Roundcube seperately.

If you have good ideas to think about please tell us.

**Comment by vermium** [comment]
I think it would be great if you could by any chance migrate all data from SoHo's DAVs and run the DAVs in separate containers. This will also make it more flexible so people can skip running DAVs if they dont want.
I hope SoGo lets you choose external DAVs and that will be awesome

**Comment by vermium** [comment]
For those who have it seperarly, just ask them to move their config to the new solution or remove the old one. I think it will improve their workflow either way. Since then roundcube is automatically updated too

**Comment by mkuron** [comment]
> I hope SoGo lets you choose external DAVs

SOGo does not support that. It can only use its internal DAV server. It's a pretty good, standards-compliant DAV server, so why not keep using it.

> RoundCube that uses SOGo Calendar and Contacts

What's the current state of CalDAV and CardDAV support in Roundcube? I tried it a few years ago and back then it required one plugin for CalDAV and a completely separate one for CardDAV. They were both not particularly reliable and the CardDAV plugin was not really well maintained. Has that situation improved?

**Comment by vermium** [comment]
> > I hope SoGo lets you choose external DAVs
> 
> SOGo does not support that. It can only use its internal DAV server. It's a pretty good, standards-compliant DAV server, so why not keep using it.
> 
> > RoundCube that uses SOGo Calendar and Contacts
> 
> What's the current state of CalDAV and CardDAV support in Roundcube? I tried it a few years ago and back then it required one plugin for CalDAV and a completely separate one for CardDAV. They were both not particularly reliable and the CardDAV plugin was not really well maintained. Has that situation improved?

Sounds like how it is today too, but I would really enjoy atleast having the RoundCube as official just for mail (with Netfilter then of-course!) I think CardDAV works pretty good tho, but haven't got into CalDAV yet!

**Comment by SnailShea** [comment]
I think this would be much better as helper script like Nextcloud. I also use Roundcube with mailcow and it is not difficult to set up, but automation would still make things easier + leave less room for errors. Roundcube container seems excessive, since nginx and php-fpm are already provided, but download/untar/default config in a bash script could be nice.

**Comment by vermium** [comment]
I really want roundcube to have fail2ban too, that is mostly why I want it officially so it can be integrated with Netfilter by them

**Comment by SnailShea** [comment]
netfilter is what is actually used, not fail2ban, but as long as the logs are available to the netfilter container it can be used. Does not need to be a standalone roundcube container for this to work.

**Comment by DerLinkman** [comment]
> I think this would be much better as helper script like Nextcloud. I also use Roundcube with mailcow and it is not difficult to set up, but automation would still make things easier + leave less room for errors. Roundcube container seems excessive, since nginx and php-fpm are already provided, but download/untar/default config in a bash script could be nice.

Yeah would higher vote for that too as it is still optional and bit hidden like nextcloud is then.

**Comment by ALFAMAS** [comment]
+1

**Comment by mstilkerich** [comment]
netfilter for failed roundcube logins works if you follow the instructions, specifically the part about forwarding the real client ip to dovecot.

https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/#forward-the-client-network-address-to-dovecot

Failed logins then show up in the dovecot logs with the actual client ip, so it will be handled just like direct failed login attempts to dovecot.

**Comment by DerLinkman** [comment]
Won't add this sorry... we don't like roundcube that much...

**Comment by patschi** [comment]
Roundcube doesn't provide CardDAV, CalDAV nor ActiveSync. If you want Roundcube, feel free to add a corresponding container using `docker-compose.override.yaml` file. There are no plans to ship multiple webmail solutions.

**Comment by AlexW85** [comment]
I think SOGo is not bad, a dark mode or some Themes would be great, because this colors are not nice. My big Problem is Nextcloud! I must use Nextclouds DAV Servers, but SOGo don't let me. Why is THIS such a big problem? Mailcow with Nextcloud together is a complete Groupware, but with separate CalDAV and CardDAV Servers useless.
