### ISSUE TITLE
Nextcloud AutoUpdater

### ISSUE THREAD

**Issue by xLixon** [mailcow/mailcow-dockerized#4973]
### Summary

The Update-Script doesnt update Nextcloud to the latest Version (as far as i seen).
It would be usefull, because my Nextcloud Installation is hung up right now and i am not sure what i should do (i am working on it)

### Motivation

The Installation of Nextcloud woulnd break after beeing outdated (as it is at my case)

**Comment by DerLinkman** [comment]
Not a enhancement more a bug.

Can you provide us any informations about the logs etc. when trying to update nextcloud within the stack?

**Comment by NicoDreamzZ** [comment]
[update.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh) doesn't touch your nextcloud installation. The update sould be possible with the webupdater in nextcloud itself when logged in as an administrator. Im not shure if its a good idea to integrate the update into the mailcow update mechanism.

**Comment by xLixon** [comment]
@DerLinkman (Geht es auch auf Deutsch?)
It think it is an enhancement of the script because then that wont fail agian on other ones installations...
Or there could be a script in the helper-scripts folder to upgrade nextcloud with required php and files and stuff...

**Comment by DerLinkman** [comment]
> [update.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh) doesn't touch your nextcloud installation. The update sould be possible with the webupdater in nextcloud itself when logged in as an administrator. Im not shure if its a good idea to integrate the update into the mailcow update mechanism. 

Oh I missed read that. Yes you can also update your Nextcloud within the Nextcloud install script located in helper script.

The update.sh is not responsible for that.

**Comment by xLixon** [comment]
So you mean in helper script i execute the nextcloud script with the -i parameter?

**Comment by DerLinkman** [comment]
Noooo! That would overwrite your current nextcloud installation.

Actually in the code there is a update function which is unused (i don´t know why). This will be implemented for 2023-01 then.

**Comment by MAGICCC** [comment]
> Actually in the code there is a update function which is unused (i don´t know why). This will be implemented for 2023-01 then.

Seems it was added in https://github.com/mailcow/mailcow-dockerized/commit/a2a963c840e5efc284d5c8a390334d47e42cbb57 and partially removed in https://github.com/mailcow/mailcow-dockerized/commit/0920bccb05e0a811f51590141fbeed78f390df9a



> [update.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/update.sh) doesn't touch your nextcloud installation. The update sould be possible with the webupdater in nextcloud itself when logged in as an administrator. 

Indeed, see their official guides https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html

**Comment by DerLinkman** [comment]
In https://github.com/mailcow/mailcow-dockerized/commit/9c55d46bc6335505cb0c03b3eb303dd3664a50cd i've improved and reimplemented the -u (update) functionality as this is now using Nextcloud's build in CLI Updater function instead of a manual one.

So yeah, in 2023-01 this will be implemented.
