### ISSUE TITLE
Containerausfall wird nicht angezeigt

### ISSUE THREAD

**Issue by flo1212** [mailcow/mailcow-dockerized#4974]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Ich bin davon ausgegangen, das im Backend auf der Startseite (System -> Information) der Status alle Container angezeigt wird (läuft / läuft nicht). Wenn ein Container nicht mehr läuft, wird er jedoch schlicht nicht anzeigt. Damit bekommt man also auf einem Blick nicht angezeigt, welche Container nicht mehr läuft. Im Screenshot ein Beispiel, bei dem der Postfix-Container abgestürzt ist. Er ist einfach nicht mehr gelistet. Man kann ihn in der GUI somit auch nicht neu starten.
Mit dem Portainer kann man den Status der Portainer schnell erkenne und bei Bedarf neu starten.

Screenshot:
flotte24.de/mailcow/screenshot.png
```

### Logs:

```plain text
keine Logs für diesen Bug verfügbar
```

### Steps to reproduce:

```plain text
siehe Beschreibung
```

### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

32 GB, 8 Cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

Docker Compose version v2.7.0

### mailcow version:

2022-12b

### Reverse proxy:

nein

### Logs of git diff:

```plain text
na
```

### Logs of iptables -L -vn:

```plain text
na
```

### Logs of ip6tables -L -vn:

```plain text
na
```

### Logs of iptables -L -vn -t nat:

```plain text
na
```

### Logs of ip6tables -L -vn -t nat:

```plain text
na
```

### DNS check:

```plain text
na
```

**Comment by DerLinkman** [comment]
Please only in english here on GitHub!

**Comment by flo1212** [comment]
I assumed that the status of all containers (running / not running) is displayed in the backend on the start page (System -> Information). If a container is no longer running, however, it is simply not displayed. This means that you can't see at a glance which containers are no longer running. In the screenshot an example where the postfix container crashed. It's just not listed anymore. You can't restart it in the GUI either.
With the Portainer you can quickly see the status of the Portainer and restart it if necessary.

Screenshot:
flotte24.de/mailcow/screenshot.png
