### ISSUE TITLE
Change password do not work for domain administrators

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#4977]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
The change password doesn't work it just says please wait when trying to change as a domain administrator
```

### Logs:

```plain text
No logs are outputted when trying to save
```

### Steps to reproduce:

```plain text
1. Add an domain administrator
2. Login as the domain administrator
3. Try to change password
```

### Which branch are you using?

master

### Operating System:

Don't want to say

### Server/VM specifications:

Don't want to say

### Is Apparmor, SELinux or similar active?

I don't know

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12b

### Reverse proxy:

Non

### Logs of git diff:

```plain text
Nothing important changed just some mail delivery fixes in postfix
```

### Logs of iptables -L -vn:

```plain text
Too much questions
```

### Logs of ip6tables -L -vn:

```plain text
Too much questions
```

### Logs of iptables -L -vn -t nat:

```plain text
Too much questions
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Too much questions
```

### DNS check:

```plain text
151.101.65.69
151.101.1.69
151.101.193.69
151.101.129.69
```

**Comment by MAGICCC** [comment]
Should be fixed in https://github.com/mailcow/mailcow-dockerized/pull/4966 already and fixed in 2023-01

**Comment by vermium** [comment]
@MAGICCC This still doesn't seem to work on 2023-01.

**Comment by vermium** [comment]
I can atleast say that I get
```
Uncaught ReferenceError: csrf_token is not defined
```
in the Web Console when pressing on "change password"

**Comment by MAGICCC** [comment]
I will reopen the issue again, maybe @FreddleSpl0it can check it again?

**Comment by FreddleSpl0it** [comment]
javascript was broken because a twig variable was missing. https://github.com/mailcow/mailcow-dockerized/commit/9ba65a572e1e22d89d75130f0ee609ec1f9f6d70

will be fixed in new release
