### ISSUE TITLE
Domain administrators can add tags but not remove

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#4978]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Domain administrators can add tags but not remove. I think they should not be able to add tags since they cant remove.
```

### Logs:

```plain text
No interesting stuff here
```

### Steps to reproduce:

```plain text
1. Create a domain administrator
2. Login as domain administrator
3. Try to add tags to domain and try to remove tags
```

### Which branch are you using?

master

### Operating System:

Don't want to say

### Server/VM specifications:

Don't want to say

### Is Apparmor, SELinux or similar active?

I don't know

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-12b

### Reverse proxy:

Non

### Logs of git diff:

```plain text
No interesting stuff here
```

### Logs of iptables -L -vn:

```plain text
No interesting stuff here
```

### Logs of ip6tables -L -vn:

```plain text
No interesting stuff here
```

### Logs of iptables -L -vn -t nat:

```plain text
No interesting stuff here
```

### Logs of ip6tables -L -vn -t nat:

```plain text
No interesting stuff here
```

### DNS check:

```plain text
No interesting stuff here
```

**Comment by FreddleSpl0it** [comment]
will be fixed in 2023-01 https://github.com/mailcow/mailcow-dockerized/commit/36fa5dc6330102da68425fda09670c25be548bce
