### ISSUE TITLE
Performance: account creation gets considerably slower, the more users are in mailcow

### ISSUE THREAD

**Issue by missytake** [mailcow/mailcow-dockerized#4980]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

We stress-tested mailcow with a script - it creates 4000 users, and every 100 users it reports on the time it took to create the users. It came out that every additional user in mailcow makes the request take longer significantly. This puts a limit to mailcow's performance with many users.

### Logs:

```plain text
Cleaning up first...
Request took 4.23 seconds.
Cleaned up 0 users.
Creating 4000 users - continue?
Created 0 accounts; the last 100 accounts took 0.00 seconds
Created 100 accounts; the last 100 accounts took 14.25 seconds
Created 200 accounts; the last 100 accounts took 16.05 seconds
Created 300 accounts; the last 100 accounts took 18.02 seconds
Created 400 accounts; the last 100 accounts took 20.19 seconds
Created 500 accounts; the last 100 accounts took 23.26 seconds
Created 600 accounts; the last 100 accounts took 26.67 seconds
Created 700 accounts; the last 100 accounts took 29.43 seconds
Created 800 accounts; the last 100 accounts took 34.02 seconds
Created 900 accounts; the last 100 accounts took 38.61 seconds
Created 1000 accounts; the last 100 accounts took 40.74 seconds
Created 1100 accounts; the last 100 accounts took 45.32 seconds
Created 1200 accounts; the last 100 accounts took 51.28 seconds
Created 1300 accounts; the last 100 accounts took 56.69 seconds
Created 1400 accounts; the last 100 accounts took 61.37 seconds
Created 1500 accounts; the last 100 accounts took 67.01 seconds
Created 1600 accounts; the last 100 accounts took 92.26 seconds
Created 1700 accounts; the last 100 accounts took 77.72 seconds
Created 1800 accounts; the last 100 accounts took 83.52 seconds
Created 1900 accounts; the last 100 accounts took 90.72 seconds
Created 2000 accounts; the last 100 accounts took 96.31 seconds
Created 2100 accounts; the last 100 accounts took 104.23 seconds
Created 2200 accounts; the last 100 accounts took 125.52 seconds
Created 2300 accounts; the last 100 accounts took 174.80 seconds
Created 2400 accounts; the last 100 accounts took 123.55 seconds
Created 2500 accounts; the last 100 accounts took 169.84 seconds
Created 2600 accounts; the last 100 accounts took 156.14 seconds
Created 2700 accounts; the last 100 accounts took 168.73 seconds
Created 2800 accounts; the last 100 accounts took 175.47 seconds
Created 2900 accounts; the last 100 accounts took 180.27 seconds
Created 3000 accounts; the last 100 accounts took 185.32 seconds
Created 3100 accounts; the last 100 accounts took 188.98 seconds
Created 3200 accounts; the last 100 accounts took 209.38 seconds
Created 3300 accounts; the last 100 accounts took 206.27 seconds
Created 3400 accounts; the last 100 accounts took 220.92 seconds
Created 3500 accounts; the last 100 accounts took 232.14 seconds
Created 3600 accounts; the last 100 accounts took 242.23 seconds
Created 3700 accounts; the last 100 accounts took 265.88 seconds
Created 3800 accounts; the last 100 accounts took 268.94 seconds
Created 3900 accounts; the last 100 accounts took 290.78 seconds
Created 4000 accounts; in total it took 4994.76 seconds
```

### Steps to reproduce:

1. Get an API token from a mailcow test instance of your choice
2. git clone https://git.0x90.space/missytake/mailcow-scripts
3. Run the test script `MAILCOW_TOKEN=6XXXX9-CXXXXE-CXXXX7-FXXXXB-7XXXX3 python3 mailcow-scripts/create-mailcow-accounts.py`
  - check that the test script doesn't do anything malicious before executing it, like a responsible person. But you rather might want to run this on a test server anyway.

This will produce something similar to the log output above.
If you want to clean up the excess users afterwards, just re-run the script and press ctrl+c when it asks you if you want to continue creating the users.

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

I don't know exactly, tested it with dc.develcow.de

### Is Apparmor, SELinux or similar active?

I don't have SSH access to dc.develcow.de, it should not matter though.

### Virtualization technology:

I don't have SSH access to dc.develcow.de, it should not matter though.

### Docker version:

I don't have SSH access to dc.develcow.de, it should not matter though.

### docker-compose version or docker compose version:

I don't have SSH access to dc.develcow.de, it should not matter though.

### mailcow version:

2022-12b

### Reverse proxy:

I don't have SSH access to dc.develcow.de, it should not matter though.

### Logs of git diff:

```plain text
None afaik
```

### Logs of iptables -L -vn:

```plain text
I don't have SSH access to dc.develcow.de, it should not matter though.
```

### Logs of ip6tables -L -vn:

```plain text
I don't have SSH access to dc.develcow.de, it should not matter though.
```

### Logs of iptables -L -vn -t nat:

```plain text
I don't have SSH access to dc.develcow.de, it should not matter though.
```

### Logs of ip6tables -L -vn -t nat:

```plain text
I don't have SSH access to dc.develcow.de, it should not matter though.
```

### DNS check:

```plain text
I don't have SSH access to dc.develcow.de, it should not matter though.
```

**Comment by link2xt** [comment]
`add/mailbox` API endpoint does a lot of things, this request in particular looks suspicious:
https://github.com/mailcow/mailcow-dockerized/blob/3f1a5af88bf4e36fd12904df25ca27c5042aaaa0/data/web/inc/functions.mailbox.inc.php#L1173-L1175

`WHERE` contains `username` column comparison, but `mailbox` table does not have an index for `username`, resulting in linear scan of the table.

This is just a guess, ideally request handler and database should be profiled on a server to figure out all the places where processing time grows with the number of mailboxes.

**Comment by FreddleSpl0it** [comment]
username is the primary key in the table mailbox, so there should be an index by default, or am i wrong?

**Comment by link2xt** [comment]
My bad, this has an index indeed.

Then probably quota calculation is slowing it down, because it selects all the mailboxes for this domain. But this needs to be profiled, I am just guessing looking at the code.

**Comment by FreddleSpl0it** [comment]
im running some tests with the script provided by @missytake.
commented every sql statement out except this:

```
          $stmt = $pdo->prepare("INSERT INTO `mailbox` (`username`, `password`, `name`, `quota`, `local_part`, `domain`, `attributes`, `active`)
            VALUES (:username, :password_hashed, :name, :quota_b, :local_part, :domain, :mailbox_attrs, :active)");
          $stmt->execute(array(
            ':username' => $username,
            ':password_hashed' => $password_hashed,
            ':name' => $name,
            ':quota_b' => $quota_b,
            ':local_part' => $local_part,
            ':domain' => $domain,
            ':mailbox_attrs' => $mailbox_attrs,
            ':active' => $active
          ));
```


Result:

```
Cleaning up first...
Request took 0.04 seconds.
Cleaned up 0 users.
Creating 4000 users - continue? (if no, press ctrl+c) 
Created 0 accounts; the last 100 accounts took 0.00 seconds
Created 100 accounts; the last 100 accounts took 9.29 seconds
Created 200 accounts; the last 100 accounts took 9.47 seconds
Created 300 accounts; the last 100 accounts took 10.39 seconds
Created 400 accounts; the last 100 accounts took 11.52 seconds
Created 500 accounts; the last 100 accounts took 12.66 seconds
Created 600 accounts; the last 100 accounts took 14.63 seconds
Created 700 accounts; the last 100 accounts took 16.09 seconds
Created 800 accounts; the last 100 accounts took 18.75 seconds
Created 900 accounts; the last 100 accounts took 20.96 seconds
Created 1000 accounts; the last 100 accounts took 23.85 seconds
Created 1100 accounts; the last 100 accounts took 30.75 seconds
Created 1200 accounts; the last 100 accounts took 32.74 seconds
```


i have removed domain and kind as keys from mailbox table so there is only the username index. Also tried to set `key_buffer_size = 1GB` and `bulk_insert_buffer_size = 1GB`

**Comment by link2xt** [comment]
Is it the SQL statement which takes the time at all? Maybe the problem is `update_sogo_static_view()` call at the end of `inc/functions.mailbox.inc.php`?

**Comment by FreddleSpl0it** [comment]
You are right. I completely overlooked this function at the end. update_sogo_static_view() is the cause of the poor performance. I'll see if it can be optimized

**Comment by link2xt** [comment]
> You are right. I completely overlooked this function at the end. update_sogo_static_view() is the cause of the poor performance. I'll see if it can be optimized

Couldn't it be done in the background? I'm not familiar with the architecture of mailcow, isn't there some task queue like what [Celery](https://docs.celeryq.dev/) is for flask?

**Comment by FreddleSpl0it** [comment]
since this function is only needed when sogo is enabled, I will add a skip if SOGO_SKIP=y is set in mailcow.conf
