### ISSUE TITLE
IP addresses requested in ACME container even though `SKIP_IP_CHECK=y`

### ISSUE THREAD

**Issue by tomudding** [mailcow/mailcow-dockerized#4984]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When setting `SKIP_IP_CHECK=y` the IP checks are "disabled" in the ACME container. However, I would expect that this means that no IPs are retrieved. This is not the case as both `get_ipv4()` and `get_ipv6()` are still called.

https://github.com/mailcow/mailcow-dockerized/blob/10b1be7f6b5e1f8cbe477b35b5601755db0717e2/data/Dockerfiles/acme/acme.sh#L216-L220

https://github.com/mailcow/mailcow-dockerized/blob/10b1be7f6b5e1f8cbe477b35b5601755db0717e2/data/Dockerfiles/acme/functions.sh#L40-L66
```

### Logs:

```plain text
> [REDACTED] - Certificates were successfully validated, no changes or renewals required, sleeping for another day.
> [REDACTED] - Certificate /var/lib/acme/[REDACTED]/cert.pem validation done, neither changed nor due for renewal.
> [REDACTED] - Confirmed AAAA record with IP [REDACTED]
> [REDACTED] - Found AAAA record for [REDACTED]: [REDACTED] - skipping A record check
> [REDACTED] - OK: [REDACTED], [REDACTED]
> [REDACTED] - Detecting IP addresses...
```

### Steps to reproduce:

```plain text
1) Set `SKIP_IP_CHECK` to `y` (or an equivalent value)
2) (re)start the mailcow instance and check the ACME logs
```

### Which branch are you using?

master

### Operating System:

N/A

### Server/VM specifications:

N/A

### Is Apparmor, SELinux or similar active?

N/A

### Virtualization technology:

N/A

### Docker version:

N/A

### docker-compose version or docker compose version:

N/A

### mailcow version:

2022-12b

### Reverse proxy:

N/A

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by DerLinkman** [comment]
Sort of right. Yes the message "Detecting IP Adresses" is not correct that it appear.

But however this SKIP_IP_CHECK Variable is not a bypass action to get Certs without the proper IP Confirmation though. As far as i know is that check only for getting the Server IPs (similarily to the IP Opt-In of the UI knowadays).

I've implemented the bypass option to exclude the check.

**Comment by DerLinkman** [comment]
Will fixed in 2023-01

**Comment by tomudding** [comment]
5c57df466943580d77c44ff8af22fe4115eb058a was not merged into staging/master for 2023-01, I assume that this will be released in a minor release or 2023-2.

**Comment by DerLinkman** [comment]
Yes i'm very sorry. Don't know how i could oversee this...

If we release a Revision A it will be part of that.

Else 2023-02 then
