### ISSUE TITLE
Mailpiler 1.4.x not working with Mailcow Integration 

### ISSUE THREAD

**Issue by simatec** [mailcow/mailcow-dockerized#4987]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I updated Mailpiler from version 1.3.11 to 1.4.2.  Now it is no longer possible to login to Mailpiler as admin or auditor.
  Only a login with the mail addresses from Mailcow Api is possible.  

The Piler developer says I should open an issue here.
```

### Logs:

```plain text
No logs
```

### Steps to reproduce:

```plain text
Login in Mailpiler with http error 500
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22

### Server/VM specifications:

8

### Is Apparmor, SELinux or similar active?

No

### Virtualization technology:

KVM

### Docker version:

20.10.21

### docker-compose version or docker compose version:

v.2.12.2

### mailcow version:

2022.11

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
No logs
```

### Logs of iptables -L -vn:

```plain text
No logs
```

### Logs of ip6tables -L -vn:

```plain text
No logs
```

### Logs of iptables -L -vn -t nat:

```plain text
No logs
```

### Logs of ip6tables -L -vn -t nat:

```plain text
No logs
```

### DNS check:

```plain text
No logs
```

**Comment by MAGICCC** [comment]
Probably something for @patschi as he wrote https://docs.mailcow.email/third_party/mailpiler/third_party-mailpiler_integration/ + https://github.com/patschi/mailpiler-mailcow-integration or even here https://t.me/mailpiler

**Comment by patschi** [comment]
Issue for this integration is here: https://github.com/patschi/mailpiler-mailcow-integration/issues/3. Closing this as it's not related to mailcow directly.

**Comment by ckruijntjens** [comment]
i have the same issue.

is this ever resolved?

**Comment by patschi** [comment]
Yes. Read comment above.
