### ISSUE TITLE
sogo: Duplicate entry  for key 'PRIMARY' error

### ISSUE THREAD

**Issue by Bitti09** [mailcow/mailcow-dockerized#5]
steps done:

1. fresh pulled  docker images. recreated container&volumes
2. added domain & restarted sogo via webui
3. added test mailbox (no sogo restart)
4. logged 1st time into sogo
log shows:

sogo-mailcow_1       | Dec 29 21:48:17 sogod [85]: [ERROR] <0x0x55fff2699d00[SOGoSQLUserProfile]> could not run SQL 'INSERT INTO sogo_user_profile            (c_uid, c_settings)     VALUES ('test@domain.de', '{"Calendar": {}}')': <MySQL4Exception: 0x55fff28e48a0> NAME:ExecutionFailed REASON:Duplicate entry 'test@domain.de' for key 'PRIMARY'

sogo restart required after adding a mailbox too ? (instead of   "after domain adding " only )

edit: even after  "add mailbox  & restart sogo" the error is still present  in sogo log

**Comment by andryyy** [comment]
That's fine and can be ignored. See SOGo mail list somewhere. :-) 

No restart required.

**Comment by Bitti09** [comment]
thanks for the info :+1:
