### ISSUE TITLE
SOGo Connection error

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#50]
When I try to save the settings in Sogo. I get an : _"Connection error"_

<img width="1041" alt="1" src="https://cloud.githubusercontent.com/assets/24925548/22945747/542f009a-f306-11e6-87b1-247ad250af27.png">

<img width="1041" alt="3" src="https://cloud.githubusercontent.com/assets/24925548/22945776/66c9ac82-f306-11e6-90e6-a9306472f0fb.png">

**Comment by andryyy** [comment]
What is the last output of "docker-compose logs sogo-mailcow" and 
"docker-compose logs dovecot-mailcow"?


Am 14.02.2017 um 20:39 schrieb aekv:

**Comment by ghost** [comment]
@andryyy 

**docker-compose logs sogo-mailcow**
The latest information at 11 am.  
`sogo-mailcow_1  | Feb 14 11:41:39 sogod [182]: 'IP' "POST /SOGo/so/user@domain.com/Mail/0/folderJunk/view HTTP/1.0" 200 259/48 0.544 - - 0`
After nothing, clean file. 

But if
docker exec -i -t `id` bash
cat /var/log/sogo/sogo.log

`Feb 14 22:53:36 sogod [143]: <0x0x55915c79b510[NGSieveClient]> TLS started successfully.`
`Feb 14 22:53:36 sogod [143]: **[ERROR]** <0x0x55915ba8a180[SOGoSieveManager]> Sieve generation failure: Action with invalid flag argument '_$label2'`

**Comment by andryyy** [comment]
Can you remove the custom label TEST?

**Comment by ghost** [comment]
I deleted
It seems there is a problem here

<img width="645" alt="2" src="https://cloud.githubusercontent.com/assets/24925548/22947769/5446cec6-f30d-11e6-9281-f655395107e0.png">

**Comment by andryyy** [comment]
Can you report it to SOGo, please?

**Comment by ghost** [comment]
Ok
