### ISSUE TITLE
OomKillDisable warunung still present

### ISSUE THREAD

**Issue by Tealk** [mailcow/mailcow-dockerized#5001]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I still get the message '⠏ dockerapi-mailcow Your kernel does not support OomKillDisable. OomKillDisable discarded.                        0.0s'

But that should be fixed in the current version?

              Will be fixed in 2023-01

_Originally posted by @DerLinkman in https://github.com/mailcow/mailcow-dockerized/issues/4902#issuecomment-1376940294_
```

### Logs:

```plain text
-
```

### Steps to reproduce:

```plain text
update from 2022-12b to 2023-01
```

### Which branch are you using?

master

### Operating System:

Debian cat /etc/debian_version

### Server/VM specifications:

4 Cores, 10GB RAM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22, build 3a2c30b

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2023-01

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by DerLinkman** [comment]
Did i missed that?

Oops. Sorry.

Will implement it

(Simply run update.sh again then)

**Comment by Tealk** [comment]
Is fixed, thank you
