### ISSUE TITLE
DOCKER_COMPOSE_VERSION not correctly set in mailcow.conf

### ISSUE THREAD

**Issue by colincameron** [mailcow/mailcow-dockerized#5004]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I ran update.sh for the first time for almost a year and (after updating to docker compose v2) got the error "./update.sh: line 752: config: command not found". From checking the update.sh script, COMPOSE_COMMAND is set in detect_docker_compose_command() line 178. Lines 183 and 196 incorrectly set the variable COMPOSE_VERSION instead of DOCKER_COMPOSE_VERSION, so that when added to mailcow.conf in line 425, DOCKER_COMPOSE_VERSION is blank instead of "native".

Subsequently running update.sh reads this blank line, so line 752 tries to run the command "config" instead of "docker compose config".

Suggested fix - update.sh lines 183 and 196 should set the variable DOCKER_COMPOSE_VERSION instead of COMPOSE_VERSION.

### Logs:

```plain text
N/A
```

### Steps to reproduce:

```plain text
1. Run update.sh without "DOCKER_COMPOSE_VERSION" in mailcow.conf
2. Run update.sh again now that mailcow.conf has been incorrectly updated.
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04

### Server/VM specifications:

N/A

### Is Apparmor, SELinux or similar active?

N/A

### Virtualization technology:

N/A

### Docker version:

20.10.22

### docker-compose version or docker compose version:

2.14.1

### mailcow version:

2023-01

### Reverse proxy:

N/A

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by FreddleSpl0it** [comment]
I have reverted the latest changes regarding the docker compose check. Can you update and try again?

**Comment by colincameron** [comment]
I removed the entry from my mailcow.conf and ran the new script and it appears to be working correctly now.
