### ISSUE TITLE
Rspamd UI Password change dont work

### ISSUE THREAD

**Issue by bigbear1988** [mailcow/mailcow-dockerized#5007]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Rspamd UI Password Change 

 command did not complete

on Version 2023-01

Issue tested on 

debian10 and 11
```

### Logs:

```plain text
no
```

### Steps to reproduce:

```plain text
typ password
klick save
```

### Which branch are you using?

master

### Operating System:

debian

### Server/VM specifications:

4 

### Is Apparmor, SELinux or similar active?

np

### Virtualization technology:

kvm

### Docker version:

20.10.21

### docker-compose version or docker compose version:

v21.2

### mailcow version:

 2023-01

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
kp
```

### Logs of iptables -L -vn:

```plain text
kp
```

### Logs of ip6tables -L -vn:

```plain text
kpü
```

### Logs of iptables -L -vn -t nat:

```plain text
kp
```

### Logs of ip6tables -L -vn -t nat:

```plain text
kp
```

### DNS check:

```plain text
kp
```

**Comment by DerLinkman** [comment]
Which version of the dockerapi and rspamd image is used in your docker-compose.yml?

**Comment by bigbear1988** [comment]
image: mailcow/rspamd:1.92
docker 2.1

The issue happened also on a complete new Server and installation

**Comment by DerLinkman** [comment]
docker = dockerapi? there is no image 2.1 for dockerapi

**Comment by bigbear1988** [comment]
mailcow/dockerapi:2.0

**Comment by DerLinkman** [comment]
Can't reproduce it. Neither on my running config nor on a freshly installed one.

**Comment by FreddleSpl0it** [comment]
can you open the docker logs of the dockerapi and then try to set the rspamd password? If an error is the cause, this will appear in the logs

**Comment by bigbear1988** [comment]
can you tell me the command for it. I have this issue since 2023.1

**Comment by bigbear1988** [comment]
![err](https://user-images.githubusercontent.com/123119409/213703433-0eb9d8f1-d9dc-4747-a3fa-94cfa525d81e.PNG)

**Comment by DerLinkman** [comment]
> can you tell me the command for it. I have this issue since 2023.1

`docker-compose logs -f --tail=200 dockerapi-mailcow` inside the mailcow root folder.

**Comment by bigbear1988** [comment]
![ett24](https://user-images.githubusercontent.com/123119409/213705788-8722cbb7-3b89-42ae-b4fe-c25b97e8eda8.PNG)

**Comment by HAZeug** [comment]
Same Problem here! 
System Specs identical only the RAM is 32GB

**Comment by DerLinkman** [comment]
Can't reproduce till today. Please share us more logs which we can Analyse.

**Comment by bigbear1988** [comment]
what logs do you need

**Comment by MAGICCC** [comment]
Have the same issue, will check today in the evening

**Comment by MAGICCC** [comment]
It's strange, couldnt see bad logs on my system

**Comment by FreddleSpl0it** [comment]
I noticed strange behavior since the docker api uses the aiodocker python library. 
Especially in the queue table the number of mails is always fluctuating strongly
So i partially rolled back to use the old docker library.

**Comment by DerLinkman** [comment]
Will fixed in 2023-01a
