### ISSUE TITLE
Changing postfix/extra.cf to IPv6-only makes errors for SMTP

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#5008]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
It seems like the Docker net not wants to talk with postfix (atleast) over IPv6. Not quite sure why, but I could post most info if needed
```

### Logs:

```plain text
I couldn't seem to find any logs for this problem
```

### Steps to reproduce:

```plain text
1. Edit extra.cf
smtp_address_preference = ipv6
inet_protocols = ipv6
2. Restart container (or whole compose)
3. You get SMTP error (don't remember the number, can't test on my current system since it's in production)
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04

### Server/VM specifications:

Privacy

### Is Apparmor, SELinux or similar active?

Privacy

### Virtualization technology:

Privacy

### Docker version:

20.10.23

### docker-compose version or docker compose version:

v2.15.1

### mailcow version:

2023-01

### Reverse proxy:

No

### Logs of git diff:

```plain text
Privacy
```

### Logs of iptables -L -vn:

```plain text
Privacy
```

### Logs of ip6tables -L -vn:

```plain text
Privacy
```

### Logs of iptables -L -vn -t nat:

```plain text
Privacy
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Privacy
```

### DNS check:

```plain text
Not needed
```

**Comment by DerLinkman** [comment]
Not enough informations:

- No Hardware Specs given
- No Virtualization Technique given

**Comment by vermium** [comment]
> Not enough informations:
> 
>     * No Hardware Specs given
> 
>     * No Virtualization Technique given

KVM, what type of hardware specs do you need? Are RAM, CPU important?
