### ISSUE TITLE
Using MariaDB and not MySQL

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#501]
Hello!
I intend to migrate from single host installation (running in LXC) to mailcow-dockerized.
However, I prefer to user MariaDB and not MySQL.

Can you please share instructions setting up MariaDB?

THX

**Comment by K2rool** [comment]
The docker version of Mailcow does not use Mysql it already uses MariaDB, the version it uses is 10.1.

**Comment by cmonty14** [comment]
Hi!
The container name was misleading... I can confirm that the DB container is: MariaDB 10.1

However, I have another general question:
Should I use a dedicated DB container for any application?
In my previous setup I created multiple databases on a single DB-host for different applications.

THX

**Comment by RobinFlikkema** [comment]
Personally i would say yes. It is easier to know which container does what, and you can just delete all containers associated with, for example, mailcow is you don't need it anymore

**Comment by lazyfrosch** [comment]
The whole concept of Docker and containers is to split stuff up.

Use multiple databases for multiple purposes.
