### ISSUE TITLE
Using Roundcube

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#502]
Hi!
I intend to migrate to mailcow-dockerized.
However I prefer to use Roundcube and not SOGo.

Could you please share some instructions for setting up Roundcube with mailcow-dockerized?

THX

**Comment by K2rool** [comment]
The Mailcow documentation got a guide how to setup Roundcube.

https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

**Comment by cmonty14** [comment]
Hi,

in the [instructions](https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/) it is advised to change the value for des_key to a 24ByteDESkey.

Question:
Can you confirm that the the value should be the key only: _$config['des_key'] = '<24ByteDESkey>';_?
Or should the value use the prefix _rcmail-_?
How can I generate the recommended 24byte DES key?

THX

**Comment by RobinFlikkema** [comment]
Hi,

It has to be a string of 24 characters. The prefix is not needed AFAIK.

Robin

**Comment by RobinFlikkema** [comment]
Hi,

How is installing Roundcube going? Are you still having problems? Do you need any help?

Robin

**Comment by fenio** [comment]
So I've just did that and first thing that definitely needs to be changed is config file included in howto.
It definitely can't have:

$config['enable_installer'] = false;

Cause this way you won't be able to actually run installer and initialize RC database. I spent 2 hours to figure this out ;)

Now I'm trying to figure out why RC can't manage sieve filters. Work in progress ;)
