### ISSUE TITLE
ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot start service postfix-mailcow

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#503]
Hi,

when starting mailcow-dockerized with _docker-compose up -d_ I get this error:
`Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
Creating volume "mailcowdockerized_crypt-vol-1" with default driver
Creating volume "mailcowdockerized_redis-vol-1" with default driver
Creating volume "mailcowdockerized_vmail-vol-1" with default driver
Creating volume "mailcowdockerized_postfix-vol-1" with default driver
Creating volume "mailcowdockerized_rspamd-vol-1" with default driver
Creating volume "mailcowdockerized_mysql-vol-1" with default driver
Creating volume "mailcowdockerized_dkim-vol-1" with default driver
Creating mailcowdockerized_clamd-mailcow_1 ...
Creating mailcowdockerized_ipv6nat_1 ...
Creating mailcowdockerized_mysql-mailcow_1 ...
Creating mailcowdockerized_clamd-mailcow_1
Creating mailcowdockerized_ipv6nat_1
Creating mailcowdockerized_mysql-mailcow_1 ... done
Creating mailcowdockerized_unbound-mailcow_1 ...
Creating mailcowdockerized_unbound-mailcow_1 ... done
Creating mailcowdockerized_postfix-mailcow_1 ...
Creating mailcowdockerized_dovecot-mailcow_1 ...
Creating mailcowdockerized_postfix-mailcow_1
Creating mailcowdockerized_memcached-mailcow_1 ...
Creating mailcowdockerized_dovecot-mailcow_1
Creating mailcowdockerized_memcached-mailcow_1
Creating mailcowdockerized_sogo-mailcow_1 ...
Creating mailcowdockerized_redis-mailcow_1 ...
Creating mailcowdockerized_redis-mailcow_1
Creating mailcowdockerized_postfix-mailcow_1 ... error

ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (04ea30ac76a87e44e05d671a87787afe7b032023b1bf1e27df0836eca6f3aCreating mailcowdockerized_redis-mailcow_1 ... done
Creating mailcowdockerized_php-fpm-mailcow_1 ...
Creating mailcowdockerized_php-fpm-mailcow_1 ... done
Creating mailcowdockerized_nginx-mailcow_1 ...
Creating mailcowdockerized_nginx-mailcow_1 ... done
Creating mailcowdockerized_rspamd-mailcow_1 ...
Creating mailcowdockerized_acme-mailcow_1 ...
Creating mailcowdockerized_acme-mailcow_1 ... done
Creating mailcowdockerized_rspamd-mailcow_1 ... done

ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (04ea30ac76a87e44e05d671a87787afe7b032023b1bf1e27df0836eca6f3a87f): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use
ERROR: Encountered errors while bringing up the project.
root@pc4-svp:/home/thomas/mailcow-dockerized#
Message from syslogd@pc4-svp at Aug  9 23:14:02 ...
 kernel:[252519.821006] unregister_netdevice: waiting for lo to become free. Usage count = 1`

How can I fix this issue?
Is this related to existing mailcow installation on dedicated host (LXC)?

THX

**Comment by K2rool** [comment]
The line <pre> Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use</pre> tell you what the issue is, a another process is listening on port 25 mostly likey it's Exim or Postfix is running you need to stop it or edit it config to not bind port 25.

**Comment by skupfer** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/

**Comment by cmonty14** [comment]
I didn't restart postfix service after applying [recommendation](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/) regarding local MTA on Docker host.
The issue is solved after _systemctl restart postfix.service_.
