### ISSUE TITLE
Rspamd mime type

### ISSUE THREAD

**Issue by grosbedos** [mailcow/mailcow-dockerized#505]
Hi,

i try to setup rspamd to recognize .bat with their mime type (application/x-msdownload).
So in the file "data/conf/rspamd/local.d/mime_types.conf" i have added :

`extension_map = {
  bat = 'application/x-msdownload'
};`

I have restarted my rspamd-mailcow container. But rspamd don't treat my file of type application/x-msdownload as bat file to score the spam.

Did you know what i have to do for this to work ?

Best regard.

**Comment by grosbedos** [comment]
And in the mail source, we see :
`MIME_UNKNOWN(0.10)[application/x-msdownload]`

**Comment by andryyy** [comment]
Do you still have this problem?
