### ISSUE TITLE
Ubuntu 18,20 and 22.04 lTS supported?

### ISSUE THREAD

**Issue by KlavsKlavsen** [mailcow/mailcow-dockerized#5050]
### Summary

Landing page of docs https://mailcow.github.io/mailcow-docs/ shows max supported is Ubuntu 16.04 LTS (which is EOL)
I assume docs, should be updated to reflect what is hopefully reality - that newer Ubuntu LTS editions is supported?
I could not find Dockerfile - so I assume you build some other way - so I could not which base image you build on today to verify that you're using an actually supported FROM image - but having such outdated version in first page on docs is.. not great :)

### Motivation

use supported LTS

**Comment by mkuron** [comment]
That is the documentation page for the old (non-dockerized) mailcow. It's been discontinued for years and probably never worked on Ubuntu 18.04. mailcow-dockerized should work on more or less every distribution supported by Docker, details at https://docs.mailcow.email/prerequisite/prerequisite-system/ (the current documentation page).

**Comment by KlavsKlavsen** [comment]
a note should probably be put on top then - to not confuse those pour souls,  trying to learn about mailcow :)
