### ISSUE TITLE
Cannot add given DKIM record

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#507]
Hello, my fresh installed mailcow says while creating an dkim record:
Cannot add given DKIM record:q

Following errors are displayed if i try to create a key

syslog:
`Aug 11 15:35:56 h2710636 sudo: Password converation failed: NULL password
Aug 11 15:35:59 h2710636 postfix/pickup[26137]: 4E36B8D20C4E: uid=10001 from=<philipp>
Aug 11 15:35:59 h2710636 postfix/cleanup[26658]: 4E36B8D20C4E: message-id=<20170811133559.4E36B8D20C4E@mail.it-streubel.de>
Aug 11 15:35:59 h2710636 postfix/qmgr[26138]: 4E36B8D20C4E: from=<philipp@mail.domain.de>, size=637, nrcpt=1 (queue active)
Aug 11 15:35:59 h2710636 postfix/local[26689]: 4E36B8D20C4E: to=<root@mail.domainl.de>, orig_to=<root>, relay=local, delay=0.03, delays=0.02/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Aug 11 15:35:59 h2710636 postfix/qmgr[26138]: 4E36B8D20C4E: removed
`
mail.log
`Aug 11 15:38:22 h2710636 postfix/pickup[26137]: CC0118D20C4E: uid=10001 from=<philipp>
Aug 11 15:38:22 h2710636 postfix/cleanup[26658]: CC0118D20C4E: message-id=<20170811133822.CC0118D20C4E@mail.it-streubel.de>
Aug 11 15:38:22 h2710636 postfix/qmgr[26138]: CC0118D20C4E: from=<philipp@mail.domainl.de>, size=637, nrcpt=1 (queue active)
Aug 11 15:38:22 h2710636 postfix/local[26689]: CC0118D20C4E: to=<root@mail.domain.de>, orig_to=<root>, relay=local, delay=0.02, delays=0.01/0/0/0.01, dsn=2.0.0, status=sent (delivered to mailbox)
Aug 11 15:38:22 h2710636 postfix/qmgr[26138]: CC0118D20C4E: removed`

Serverinformation:
Ubuntu 16.04 LTS
mailcow 0.14 non dockerized

**Comment by andryyy** [comment]
Sorry, but that's not dockerized.

**Comment by udozockt** [comment]
+1
