### ISSUE TITLE
Pushover support for the Watchdog

### ISSUE THREAD

**Issue by osos** [mailcow/mailcow-dockerized#5079]
### Summary

The idea is simply to enable Watchdog to send notifications via Pushover or similar.

The pushover notification could vary in "priority" based on threshold or whether it is for "information" or "critical", e.g. the watchdog-is-starting notification could be priority "normal", whereas issue-in-some-container could be priority "+1 high".

### Motivation

Watchdog is looking out for the various services, herunder the postfix and dovecot servers.

Is an issue arises in the postfix or dovecot servers it is not sure the notifications can be send to the ones needing the notifications.

Further, while emails may not be read immediately, must people check their phones often. Pushover to the phone will enable immediate attention for system critical issues.

**Comment by MAGICCC** [comment]
Maybe also related to https://github.com/mailcow/mailcow-dockerized/pull/4968.
What I can see is that Pushover also accepts webhooks https://pushover.net/api

I will try to test the PR in some days...

**Comment by MAGICCC** [comment]
https://github.com/mailcow/mailcow-dockerized/pull/4968 got merged, so you can use webhooks to pushover
