### ISSUE TITLE
https redirect not working

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#508]
Hello,

i make the changes in the data/conf/nginx/site.conf file:

```nginx
server {
    listen 80 default_server;
    include /etc/nginx/conf.d/server_name.active;
    return 301 https://$host$request_uri;
}
```

I restart the docker:

`docker-compose restart nginx-mailcow`

I restart the server itself, but nothing working http is not directed to https

Why?

**Comment by madic-creates** [comment]
Have you tried the redirect from the official documentation?
https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

Your server configuration only listens on IPv4. If you also have IPv6, it will not work if you connect with IPv6.

**Comment by heavygale** [comment]
Doesn't the HTTP to HTTPS redirect as described in the official documentation break the acme-mailcow functionality as acme-challenge requests must work with HTTP?

**Comment by andryyy** [comment]
It follows the redirect. :-)
