### ISSUE TITLE
[netfilter] Incremental banning similar to fail2ban

### ISSUE THREAD

**Issue by th-joerger** [mailcow/mailcow-dockerized#5086]
### Summary

Introduce mechanism to incrementally increase ban times, similar to [fail2ban's bantime.increment](https://github.com/fail2ban/fail2ban/blob/bc075ea682a3e3678ac5449cb1baeb0420655e8d/fail2ban/server/jail.py).

### Motivation

I see some IPs failing to authenticate over weeks at a time. They currently are banned for the standard time of 30 minutes, but come back 30 minutes later. I increased this to 24h, but cannot extend it further, because it will exclude some legitimately failed authentication attempts. I also don't want to manually add them to a blacklist. This should be automated and configured as a standard setting.

### Additional context

- If the IP was banned previously, the next bantime should be doubled each time. This can be achieved on two ways.
    * Get the last ban from the logs (➕ works without database, ➖  bans get deleted after each container update/restart)
    * Get the last ban from a database (➕ works between restarts, ➖ additional database implementation required)
- Optional: Respect a maximum bantime (let's say 365 days).
- Optional: Let the user set the settings.

**Comment by martinjgrunwald** [comment]
I am not sure this is working correctly. There are several IPs that are spamming me non-stop. I attached my Fail2Ban settings and the mails I receive from my mailcow. From my understanding it should block 24 hours at first but more than that afterwards. This IP address (among several others) however is never banned for more than 48 hours as you can see from the mails I get. 
I am on version 2024-04
<img width="1365" alt="Bildschirmfoto 2024-05-14 um 12 00 37" src="https://github.com/mailcow/mailcow-dockerized/assets/69245880/34a5f0bb-c14d-43e0-bfac-d2c1af54d38e">
<img width="294" alt="Bildschirmfoto 2024-05-14 um 12 01 50" src="https://github.com/mailcow/mailcow-dockerized/assets/69245880/da40c71e-17d0-4f19-bb84-20c97d8cc3ee">
