### ISSUE TITLE
Bug in database

### ISSUE THREAD

**Issue by m0bYczE** [mailcow/mailcow-dockerized#509]
Helo, i have installed mailcow: dockerized, but i have'nt any tables in database ? It's bug ?

**Comment by andryyy** [comment]
Hi, you need to open the web UI. It will be initialized then.

**Comment by m0bYczE** [comment]
Yes I open it, but it's bugged too. I can't change password or create new account or create new domain. I use reverse proxy with apache.

**Comment by mkuron** [comment]
Most likwly, your reverse proxy is misconfigured if that is happening. Please follow https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ for the official instructions.

**Comment by m0bYczE** [comment]
I have this in apache: 
```
<VirtualHost *:80>
	ServerSignature off
	TraceEnable off
	AddDefaultCharset utf-8
	ServerName mail.domain.com
	ServerAlias autodiscover.domain.com 	
	ServerAlias autoconfig.domain.com
	RewriteEngine On
	RewriteCond %{HTTPS} !=on
	RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [L,R,NE]
</VirtualHost>
```

```
<VirtualHost *:443>
    ServerName mail.domain.com   	
    ServerAlias autodiscover.domain.com  	
    ServerAlias autoconfig.domain.com

    # You should proxy to a plain HTTP session to offload SSL processing
    ProxyPass / https://127.0.0.1:8443/
    ProxyPassReverse / https://127.0.0.1:8443/

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyAddHeaders On

    # This header does not need to be set when using http
    RequestHeader set X-Forwarded-Proto "https"

    SSLEngine on
    SSLProxyEngine On
    SSLCertificateFile /home/md/mailcow-dockerized/data/assets/ssl/cert.pem
    SSLCertificateKeyFile /home/md/mailcow-dockerized/data/assets/ssl/key.pem
</VirtualHost>
```

**Comment by ChessSpider** [comment]
```
    # You should proxy to a plain HTTP session to offload SSL processing
    ProxyPass / https://127.0.0.1:8443/
    ProxyPassReverse / https://127.0.0.1:8443/
```

you seem to be redirectiong to the ssl service,
try 
```
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
```

**Comment by m0bYczE** [comment]
Ok, it's working, but i want to use ssl. In database is still nothing.

**Comment by andryyy** [comment]
It does still use SSL.

The database is not empty if the panel works correctly.

**Comment by m0bYczE** [comment]
I've set everything up without a reverse proxy, but it's empty now via apache. There is still nothing in the database after configuration. Maily is already working.

Apache2:
![image](https://user-images.githubusercontent.com/11786896/29352639-c415509e-8267-11e7-9b43-9de22cdb559d.png)
![image](https://user-images.githubusercontent.com/11786896/29352644-cbd133de-8267-11e7-852e-23a65bb239cc.png)

Nginx:
![image](https://user-images.githubusercontent.com/11786896/29352758-374c310e-8268-11e7-8803-9bb109540850.png)
![image](https://user-images.githubusercontent.com/11786896/29352771-40406c58-8268-11e7-856d-ddf86fdabc7a.png)

**Comment by ChessSpider** [comment]
@m0bYczE The "problem" with the reverse-proxy configuration as you showed it in post https://github.com/mailcow/mailcow-dockerized/issues/509#issuecomment-322404179 is that your reverse proxy starts another SSL connection to 127.0.0.1.

That's a waste of resources and you can safely change it to http://127.0.0.1:8080 without losing security or functionality.  It is likely unrelated to your current problems.

Using SSL over the LAN may have security benefits, just ask google&nsa&xkeyscore. But that depends on your threat-model. 

==

About your current problems, I don't really understand your problem. What happens if you add your current domain (e.g. example.com) in the configuration, add a user (bob) to that domain with password 'supersecurepassword', and login via bob@example.com with password 'supersecurepassword' ?

**Comment by m0bYczE** [comment]
OK, i changed it:
```
<VirtualHost *:80>
	ServerSignature off
	TraceEnable off
	AddDefaultCharset utf-8
	ServerName mail.differment.cz    	
	ServerAlias autodiscover.differment.cz    	
	ServerAlias autoconfig.differment.cz
	RewriteEngine On
	RewriteCond %{HTTPS} !=on
	RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [L,R,NE]
</VirtualHost>

<VirtualHost *:443>
    ServerName mail.differment.cz    	
    ServerAlias autodiscover.differment.cz    	
    ServerAlias autoconfig.differment.cz
    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    # You should proxy to a plain HTTP session to offload SSL processing
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyAddHeaders On
    SSLProxyEngine On

    # This header does not need to be set when using http
    RequestHeader set X-Forwarded-Proto "https"

    SSLEngine on
    SSLCertificateFile /home/md/mailcow-dockerized/data/assets/ssl/cert.pem
    SSLCertificateKeyFile /home/md/mailcow-dockerized/data/assets/ssl/key.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
</VirtualHost>
```
Apache data is still hidden, not shown.

If I add a domain or account, it will be added. I do not know how, because there is nothing in the database over x mails. Maily work, I accept and send them.

**Comment by ChessSpider** [comment]
Ok so basically you're wondering why everything works if it doesn't get added in the database?

I don't know. When I have time I'll check my database, I also only just started setting everything up :)

**Comment by ChessSpider** [comment]
I can confirm I do actually have database entries!

```bash
docker-compose exec mysql-mailcow /bin/bash
mysql -umailcow -pthisisnotmyactualpassword
MariaDB [(none)]> use mailcow
MariaDB [mailcow]> select * from mailbox;
[results here]
```

**Comment by m0bYczE** [comment]
Ok, it's fixed for me. I move to my second server and it's working great. Thanks.
