### ISSUE TITLE
Autodiscover does not work

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#510]
Hi,

I am trying to setup Mailcow, and I'm running in issues concerning autodiscover. And the errors I get are not really useful unfortunately.

I see this in the docker-compose logs:

I have haproxy as a front-end proxy for example.nl  I requested my own LE certificate and placed it in the assets. 

The mailcow hostname is ```MAILCOW_HOSTNAME=webmail.example.nl```

I really don't have a clue what is wrong, can anyone help? ☹️

**Comment by ChessSpider** [comment]
Oh and this is my 

data/web/inc/vars.local.inc.php:

```php
<?php

$autodiscover_config = array(
  // Enable the autodiscover service for Outlook desktop clients
  'useEASforOutlook' => 'yes',
  // General autodiscover service type: "activesync" or "imap"
  'autodiscoverType' => 'activesync',
  // Please don't use STARTTLS-enabled service ports here.
  // The autodiscover service will always point to SMTPS and IMAPS (TLS-wrapped services).
  'imap' => array(
    'server' => $mailcow_hostname,
    'port' => getenv('IMAPS_PORT'),
  ),
  'smtp' => array(
    'server' => $mailcow_hostname,
    'port' => getenv('SMTPS_PORT'),
  ),
  'activesync' => array(
    'url' => 'https://'.$mailcow_hostname.'/Microsoft-Server-ActiveSync'
  ),
  'caldav' => array(
    'url' => 'https://'.$mailcow_hostname
  ),
  'carddav' => array(
    'url' => 'https://'.$mailcow_hostname
  )
);

```

**Comment by PhoenixPeca** [comment]
From your screenshot, with the 401 http status code, you seem to have entered an incorrect email-address and/or password.
![image](https://user-images.githubusercontent.com/9730242/29357535-7ca6e0f4-82aa-11e7-9a26-b6cde636d1db.png)

**Comment by ChessSpider** [comment]
.

**Comment by PhoenixPeca** [comment]
maybe that 401 wasn't a result of a failed autodiscover login and maybe it's the activesync server that's reponding that status code. Can you login to SOGo with the same credentials?

if not, please login with the superadmin account and click on the `Restart SOGo` option in the navbar:
![image](https://user-images.githubusercontent.com/9730242/29358309-2bdd027c-82ad-11e7-9809-49b702bc41c5.png)
Then click `Restart now`:
![image](https://user-images.githubusercontent.com/9730242/29358328-3ad549a6-82ad-11e7-86da-0240b528766a.png)

Then try logging in again with your autodiscover tester or open via sogo.

I suspect that you forgot to restart SOGo after adding a new domain.

**Comment by ChessSpider** [comment]
.

**Comment by PhoenixPeca** [comment]
I cannot seem to reproduce your problem with the information you have provided. Maybe it is indeed a certificate problem. For the mean time, you can find the logs in the superadmin's `Administration Page`:
![image](https://user-images.githubusercontent.com/9730242/29358959-85f7b796-82af-11e7-8925-e0bc5b334dd4.png)
Just click on the `Logs tab` and you shall see a dropdown menu for the specific service you want to troubleshoot.

**Comment by PhoenixPeca** [comment]
Sorry, I accidentally closed. Reopening..

**Comment by ChessSpider** [comment]
.

**Comment by ChessSpider** [comment]
.

**Comment by PhoenixPeca** [comment]
I have instantiated a fresh install and I can't reproduce your problem.
---
![image](https://user-images.githubusercontent.com/9730242/29364698-f138b19c-82c6-11e7-8c2c-59bad95304e8.png)
Have you've been experiencing the same issue with [Microsoft Remote Connectivity Analyzer](https://testconnectivity.microsoft.com/)? As per my tests, it should look something like this:
![image](https://user-images.githubusercontent.com/9730242/29364750-21bf779c-82c7-11e7-995d-237cf48baff7.png)

**Comment by ChessSpider** [comment]
.

**Comment by ChessSpider** [comment]
![errors](https://user-images.githubusercontent.com/2168372/29367957-b2f40ac6-829e-11e7-88ab-af6a7a27333e.png)

**Comment by ChessSpider** [comment]
Great news! I fixed it!
The problem lies with the haproxy, i's SSL settings were too strict. I'll do a full write up

**Comment by ChessSpider** [comment]
Right, so, tl;dr is:
The SSL certificate check on https://testconnectivity.microsoft.com/ failed due to my haproxy only allowing connections on TLS1.2. 
I have enabled TLS1.0 and 1.1 and the testconnectictivity test is now happy. 

Unfortunately the autoconfig for Outlook 2016 still does not work!! 😠 

I do not get any errors in the SOGo directory or anything. They are happy with a HTTP code 200.

Error code in the Test Email AutoConfiguration of Outlook 2016 (right click icon in taskbar) is still  0x800c8203 .. I get this error with or without valid credentials.

**Comment by ChessSpider** [comment]
ohw.. wow,  I only just noticed
When I do 
 Outlook Autodiscover on https://testconnectivity.microsoft.com
test on that site I do get errors..  It's just the Exchange Autodiscover that works. 

Is there a difference? Is Outlook not supported? How does that work?

**Comment by ChessSpider** [comment]
autodiscovery does not work. 
AEX does.

For future reference, other people having this issue on Outlook 2016, bypass the autodiscovery of outlook!

Open this menu:
![mailsetup](https://user-images.githubusercontent.com/2168372/29407292-3e96cdde-8344-11e7-96f9-6c6b61bb9191.png)


**Short route**:  try and open ```C:\Program Files (x86)\Microsoft Office\root\Office16\OLCFG.EXE```
**Long route**:
Outlook 2016 -> Account Settings -> Manage Profiles -> (UAC Prompt) New screen Mail Setup 

When you're there, click on the button
Email Accounts -> New

You should end up in this screen:

![here](https://user-images.githubusercontent.com/2168372/29407188-e43bc2d6-8343-11e7-862b-ea79b87091a3.png)

Choose manual setup -> Exchange ActiveSync -> enter the details -> done -> 🎉
