### ISSUE TITLE
SSL issues with SNI

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#5101]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
About every 2 week some domain loses their valid SSLs, then I need to reboot the machine and force renew SSLs. Is there something I might done wrong?
```

### Logs:

```plain text
Can't look at them right now.
```

### Steps to reproduce:

```plain text
1. Change to SNI in mailcow.conf
2. Add some domains
3. Check SSL validity of the domains
4. Some domains might fail at some point
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04

### Server/VM specifications:

Privacy

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.23

### docker-compose version or docker compose version:

v2.15.1

### mailcow version:

2023-02a

### Reverse proxy:

No

### Logs of git diff:

```plain text
Can't post right now.
```

### Logs of iptables -L -vn:

```plain text
Can't post right now.
```

### Logs of ip6tables -L -vn:

```plain text
Can't post right now.
```

### Logs of iptables -L -vn -t nat:

```plain text
Can't post right now.
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Can't post right now.
```

### DNS check:

```plain text
Can't post right now.
```

**Comment by vermium** [comment]
Can this be fixed?

**Comment by vermium** [comment]
Hello?

**Comment by FLYBYME** [comment]
I think you need to give more information.

**Comment by vermium** [comment]
I don't know what else I can give them, they would need to ask me for more information then, like I stopped using mailcow due to this issue

**Comment by dragoangel** [comment]
Issue can be deleted as you not following instructions. You not providing any details of your setup, logs or anything to help, speaking like anybody owed you something, while you `can't post right now` anything even after I marked issue as `incomplite`. This not leading for providing any help. Sni is working for many people out of the box and this is tested functionality so it's not much fit issue on github without any details. You need be more polite and firstly try ask & help in community over creating meaningless issues on Github.

P.s. personally I after seeing your comments on project in community not have any mood to helping you personally.
