### ISSUE TITLE
Problems after migrating from mailcow 0.14 with le certificates

### ISSUE THREAD

**Issue by topelrapha** [mailcow/mailcow-dockerized#511]
Hello,

i tried to migrate from non dockerized mailcow to dockerized mailcow.
I had a lot of Backup MXs for high availability of other domains.

The acme container or better the LetsEncrypt script inside fails a lot of times. The rate limit for failed requests is reached because the backup mxs have no matching A records.

A quick view in code shows that there is no limit and it tries to create certificates for all domains. No matter if its backup mx or not.

**Comment by ChessSpider** [comment]
Hi, you can disable the build-in LetsEncrypt container and just place the correct certificate in the assets/ssl folder as described here: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/
