### ISSUE TITLE
vmail directories don't get deleted if account is deleted

### ISSUE THREAD

**Issue by missytake** [mailcow/mailcow-dockerized#5112]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
**Expected Behavior**

If I delete a mailbox, the mails of that mailbox are deleted as well.

**Actual Behavior**

Even 9 months after a mailbox was deleted (over the API, more specifically [mailadm](https://mailadm.readthedocs.io/)), the vmail directory still exists.

**Suggested Solution**

Delete the vmail directories some days after the mailbox was deleted, to account for admin error. Offer an option over the API to delete the vmail directories right away, in case an application (like mailadm) wants to ensure that the data is gone (e.g. for compliance reasons).
```

### Logs:

```plain text
I don't have logs, just this example for an account which was deleted long ago, but the vmail directory still exists:

root@managed:~# ls -la  /var/lib/docker/volumes/mailcowdockerized_vmail-index-vol-1/_data/tmpy.rrw34@testrun.org
insgesamt 348
drwx------    8 5000 5000   4096  6. Jun 2022  .
drwxr-xr-x 5672 5000 5000 274432  5. Mär 23:42 ..
drwx------    2 5000 5000   4096  6. Jun 2022  .Archive
drwx------    2 5000 5000   4096  6. Jun 2022  .DeltaChat
-rw-------    1 5000 5000    568  6. Jun 2022  dovecot.list.index
-rw-------    1 5000 5000  36256  6. Jun 2022  dovecot.list.index.log
-rw-------    1 5000 5000   2496  6. Jun 2022  dovecot.mailbox.log
drwx------    2 5000 5000   4096  6. Jun 2022  .INBOX
drwx------    2 5000 5000   4096  6. Jun 2022  .Junk
drwx------    2 5000 5000   4096  6. Jun 2022  .Sent
drwx------    2 5000 5000   4096  6. Jun 2022  .Trash
```

### Steps to reproduce:

```plain text
1. Delete an account over the API
2. Wait for 7 days
3. check if the vmail directory of the account still exists
```

### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

6GB RAM, 2 CPUs

### Is Apparmor, SELinux or similar active?

apparmor I think.

### Virtualization technology:

no idea

### Docker version:

23.0.1

### docker-compose version or docker compose version:

1.29.2

### mailcow version:

2023-03

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
nope, this contains certificates for some reason.
```

### Logs of iptables -L -vn:

```plain text
not useful here.
```

### Logs of ip6tables -L -vn:

```plain text
not useful here.
```

### Logs of iptables -L -vn -t nat:

```plain text
not useful here.
```

### Logs of ip6tables -L -vn -t nat:

```plain text
not useful here.
```

### DNS check:

```plain text
151.101.65.69
151.101.1.69
151.101.193.69
151.101.129.69
```

**Comment by FreddleSpl0it** [comment]
It seems like the Docker API moves the maildir to /_garbage to let the garbage collector take care of it, but it is missing the vmail_index of the mailbox.

https://github.com/mailcow/mailcow-dockerized/blob/229303c1f877d505a636352b0613b0d957343e0e/data/Dockerfiles/dockerapi/dockerapi.py#L379-L385

https://github.com/mailcow/mailcow-dockerized/blob/229303c1f877d505a636352b0613b0d957343e0e/data/Dockerfiles/dovecot/maildir_gc.sh#L1-L2
