### ISSUE TITLE
Mailcow in Docker

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#513]
Hi
Could you maybe containerize the mailcow webinterface in the same way as you do the other images? 

I automatically re-build all the Mailcow containers every week and push them to my private repository to make sure their dependencies don't get too outdated. But the PHP sourcecode is mounted into a container as opposed to copied. 

I'd like the mailcode PHP-code out of my Ansible script into a Docker container 🥇

**Comment by schulluk** [comment]
Maybe you can provide a pull request solving this problem?

**Comment by ChessSpider** [comment]
im currently working on that.
I am also looking into dropping privileges where possible. I noticed some services were still running as root

A pull request will appear automagically.

**Comment by andryyy** [comment]
Which and where?

**Comment by ChessSpider** [comment]
oh dear you're putting me on the spot here.. i remember seeing a CRIT warning in one of the logs at some point that there was no user available to drop privs.. 

oh wait

```
root@whatever:/somedir# docker-compose logs | grep CRIT
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
dovecot-mailcow_1    | 2017-09-04 07:40:44,976 CRIT Supervisor running as root (no user in config file)
sogo-mailcow_1       | 2017-09-04 09:40:43,892 CRIT Supervisor running as root (no user in config file)
sogo-mailcow_1       | 2017-09-04 09:40:43,914 CRIT Server 'inet_http_server' running without any HTTP authentication checking
postfix-mailcow_1    | 2017-09-04 07:40:46,560 CRIT Supervisor running as root (no user in config file)
postfix-mailcow_1    | 2017-09-04 07:40:46,582 CRIT Server 'unix_http_server' running without any HTTP authentication checking
sogo-mailcow_1       | 2017-09-05 13:34:31,226 CRIT Supervisor running as root (no user in config file)
sogo-mailcow_1       | 2017-09-05 13:34:31,250 CRIT Server 'inet_http_server' running without any HTTP authentication checking
```

**Comment by andryyy** [comment]
The inet_http_server is for reaching the API internal (port is not exposed!). We also need to be able to run some services from the supervisor daemon, I don't see how we could do that without root. The apps do drop their privileges, that's where it matters. I don't understand why an init system complains about root permissions. :-/ Maybe @mkuron knows it.

**Comment by ChessSpider** [comment]
btw my personal preference is adding a  USER statement to the Dockerfile to drop privs right from the start, and do a  ```setcap``` where required, e.g. Together with the ```no-extra-privileges``` security feature you can literally drop a suid /bin/sh in there and it will never escalate to root  ❤️  

```
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx
USER nginx 
CMD /usr/bin/nginx -g 'daemon off' or w/e
```

to allow nginx to start on port 80/443 without starting nginx as root. I think this works for postfix too.

I dont know about supervisor needing root, or any of the services, it was on my todo-list. I finally have a workable solution with the rspamd and black/whitelist. For some reason rspamd default doesnt think failure of DMARC is a reason to drop emails. I could spoof my way right into mailcow by default.. but not anymore 🎆 .. and this was next on the list :)

**Comment by ChessSpider** [comment]
@andryyy  
supervisord complaints due to no 'user' declaration present in the config
```user root```
in the supervisord.conf will null the error. See  https://github.com/Supervisor/supervisor/issues/308#issuecomment-243774550

Anyway, you'll see a pull request appear.. we can discuss the changes I propose at that stage further. First I have to do a bit more research how everything works and is interconnected :)

**Comment by andryyy** [comment]
Postfix already spawns procs as the correct users:
```
postfix    356  0.0  0.0  83404  3972 ?        S    Sep03   0:01 qmgr -l -t fifo -u
root       357  0.0  0.0   4188   324 ?        S    Sep03   0:00 sleep 126144000
postfix    373  0.0  0.1  87452  4512 ?        S    Sep03   0:01 tlsmgr -l -t unix -u
postfix  20155  0.0  0.0  83220  3916 ?        S    09:36   0:00 pickup -l -t fifo -u
postfix  20177  0.0  0.0  83216  3932 ?        S    09:41   0:00 spawn -z -n 127.0.0.1:10027 -t inet user=nobody argv
root     20231  0.0  0.0  18176  2048 ?        Ss   09:53   0:00 /bin/bash
postfix  20495  0.2  0.1  87632  4184 ?        Ss   09:54   0:00 postscreen -l -n smtp -t inet -u -s 2
postfix  20496  0.0  0.1  83220  4192 ?        Ss   09:54   0:00 proxymap -l -n proxywrite -t unix -u
nobody   20497  0.0  0.0  17948  1580 ?        Ss   09:54   0:00 /bin/bash /usr/local/bin/whitelist_forwardinghosts.s
postfix  20502  0.2  0.0  85296  3928 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20503  0.2  0.0  85296  3924 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20504  0.0  0.0  85296  3932 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20505  0.0  0.0  85296  3928 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20506  0.0  0.0  85296  3932 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20507  0.2  0.0  85296  3928 ?        S    09:54   0:00 dnsblog -z -t unix -u
postfix  20508  0.5  0.1  89996  5724 ?        S    09:54   0:00 smtpd -t pass -u -o stress= -o smtpd_helo_restrictio
postfix  20509  0.5  0.1  93592  4404 ?        S    09:54   0:00 proxymap -t unix -u
postfix  20511  1.0  0.0  83220  3924 ?        S    09:54   0:00 anvil -l -t unix -u
```

So does Nginx:
```
    9 nginx      0:26 nginx: worker process
   10 nginx      0:02 nginx: cache manager process
```

You will break things when you force master processes to use a specific user. Some procs in the containers _need_ root privileges. A public exposed proc is never run as root in mailcow (correct me if I'm wrong).

You could also open a PR @ Nginx. :-)

**Comment by ChessSpider** [comment]
@andryyy  nginx doesn't need root to start with at least. The root process of nginx does two things afaik; create a pid in /var/run/ and open port 80 and 443. I chowned a directory, assigned a privilege to /usr/sbin/nginx and nginx starts as a non-root user happily.  I don't think the pid is used anyway as nginx is ran in the foreground. 

The same is true for php-fpm, starts as root for no valid reason that I can see.  Don't know yet about other services. I am aware e.g. postfix already does chrooting etc and not giving root may actually make it less secure.  [insert '[yo dawg i heard you like compartmentalization](https://memegenerator.net/instance/80311795)' meme here]

I personally like these 'defense in depth' things and enable them whenever I can. I like the idea of being able to drop a root owned /bin/sh in there and any person with a reverse-shell causing mayhem still not being able to escalate privileges.  Hopefully that limits the person's ability to escape out of docker container. Making the entire docker image ```read-only``` with the exception of mountpoints if required, ```no-extra-privileges``` flag, mount tmpfs with ```noexec```, ```nosuid````, ```size```.. Principle of least privilege. fun fun fun. 

Thanks for the suggestion of opening a PR at nginx. I assume they're aware of the security enhancements Docker offers and have made an educated decision for compatibility, but we all know what they say about assumptions. I agree these security options may possibly be a niche. Maybe I'll post an issue there. 

Feel free to let me know if you're not interested in the 'hardening' PR. But I can still offer a PR for the /web dir in a Dockerfile😄

**Comment by andryyy** [comment]
I'm fine with it as long as you don't just put a USER in the dockerfiles. :-) Sometimes we bootstrap an environment before spawning the final proc (see SOGo for example). This may not work for those. I think it also breaks Postfix (postfix.sh). 

Afaik it is not possible for a worker to fall back to a master. But as long as you test your changes and nothing breaks, I will gladly merge it!

> Am 06.09.2017 um 12:49 schrieb ChessSpider <notifications@github.com>:
> 
> not
