### ISSUE TITLE
fetch Gmail or Gmx mail like foreign accounts to own account

### ISSUE THREAD

**Issue by schnurzli** [mailcow/mailcow-dockerized#514]
Hi folks,

is there a possibility to sync all emails from - for example - an gmail account to my domain account running on mailcow server?

I've tested the option IMAP in sogo - but this is only a view to manage my gmail mailbox in a separate folder. It would be great to sync mails directly to my user@maildomain.tld account.

How would you manage this instead of me? :-)

bg richard

ps: after some google search - is getmail4 the best way to fetch mails continiously from foreign email accounts?

**Comment by mkuron** [comment]
imapsync is built into Mailcow and can be configured by each user by logging into the Mailcow web interface. imapsync serves a similar purpose as getmail4 or fetchmail.

**Comment by schnurzli** [comment]
Hi,

thanks for your help. It works like a charm. :-) It was too easy to find :-)

Have a nice evening.

BG Richard
