### ISSUE TITLE
Fail2Ban using so much CPU

### ISSUE THREAD

**Issue by m0bYczE** [mailcow/mailcow-dockerized#515]
Hello, i have a problem. Fail2Ban uses so much cpus. I reinstall it and updated to the newst version, but it's not working. I use update.sh in mailcow and it's gone back to standart version and it's not working too. Can you help me, please?

**Comment by mkuron** [comment]
Can you provide logs for the fail2ban container?

**Comment by m0bYczE** [comment]
How will I get there ? :D

**Comment by andryyy** [comment]
`docker-compose logs --tail=500 fail2ban-mailcow` for example.

What is the difference between newest version and "back to standard"?

**Comment by m0bYczE** [comment]
This is log: 
![image](https://user-images.githubusercontent.com/11786896/29494357-ebba7d6a-85a8-11e7-952c-918a6d2ecffb.png)

And this is status:
![image](https://user-images.githubusercontent.com/11786896/29494358-f4d3e486-85a8-11e7-9e99-e951a93ad019.png)

Ok now i have a newest version: 
![image](https://user-images.githubusercontent.com/11786896/29494372-3d6dfe34-85a9-11e7-8e33-d667856b1c5d.png)

**Comment by mkuron** [comment]
The status looks like you are looking at fail2ban running on your host. Mailcow does not interfere with that in any way, it has its own custom fail2ban-like script running in the fail2ban-mailcow container. Are you referring to CPU usage by fail2ban on your host, or in that container? We can probably only help in the latter case.

**Comment by m0bYczE** [comment]
Oh, thanks. So all mailcow services are in the docker?

**Comment by mkuron** [comment]
Yes

**Comment by m0bYczE** [comment]
Ok, can i uninstall this ? 
![image](https://user-images.githubusercontent.com/11786896/29494681-c5155200-85af-11e7-93df-1f8a56002247.png)

**Comment by stevesbrain** [comment]
You can theoretically uninstall anything extra that you installed on the host except for docker, yes :)
