### ISSUE TITLE
Nextcloud support missing sysvsem + "X-Robots-Tag" HTTP header is not set to "noindex, nofollow".

### ISSUE THREAD

**Issue by paperle** [mailcow/mailcow-dockerized#5150]
### Summary

Nextcloud best practice says, that my installation (mailcow + nextcloud(installed via helper script)) missing two things:
- This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
    **sysvsem**
- The "X-Robots-Tag" HTTP header is not set to "noindex, nofollow". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

### Motivation

Privacy, performance and compatibility with nextcloud should be increased...

### Additional context

Dont know adding this mods will fit into mailcow policy. If not, maybe you have some hints for achieving this?

**Comment by DerLinkman** [comment]
Hi there,

sysvsem will be installed with the next update for mailcow.

For the other thing we have to see if it's possible or not.

**Comment by DerLinkman** [comment]
The robot tag is also fixed in the next update but it won't be for existing users:

To fix it edit the nextcloud.conf file in data/conf/nginx/ (mailcow-dockerized directory) and change the value in line 27 from none to noindex, nofollow within the "" then restart the nginx container and the error should disappear.

**Comment by paperle** [comment]
hi DerLinkman,

thanks for fast responding.

To fix it edit the nextcloud.conf file in data/conf/nginx/ (mailcow-dockerized directory) and change the value in line 27 from none to noindex, nofollow within the "" then restart the nginx container and the error should disappear.
-> works as expected, thanks!

I going to wait for the next update of mailcow, i'll close the ticket right now...

Greets
