### ISSUE TITLE
Nextcloud All In One

### ISSUE THREAD

**Issue by dalferth** [mailcow/mailcow-dockerized#5161]
### Summary

> Nextcloud AIO stands for Nextcloud All In One and provides easy deployment and maintenance with most features included in this one Nextcloud instance.

It would be nice if mailcow uses the new Nextcloud AIO docker image.

### Motivation

It would be nice if mailcow uses the new Nextcloud AIO docker image.

**Comment by DerLinkman** [comment]
mailcow does not use any nextcloud docker image at all.

It installs nextcloud into the webserver directory and creates the needed files for it.

The nextcloud installation also use the mariadb from mailcow to create a new nextcloud Database + users inside.
