### ISSUE TITLE
Growing database table sasl_log 

### ISSUE THREAD

**Issue by goodygh** [mailcow/mailcow-dockerized#5167]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Mailcows `sasl_log` is growing limitless without cleanup and slowing down the admin UI.

* As far as i understood in the code, this table never gets cleaned up and is growing limitless over time, i know environments with over 1 million records.
* And usually only the last entry is used, or at most the last seven days.
  * https://github.com/mailcow/mailcow-dockerized/blob/df8775d4c9662d80039caad5688c13893e5a60bf/data/web/inc/functions.inc.php#L261
  * https://github.com/mailcow/mailcow-dockerized/blob/df8775d4c9662d80039caad5688c13893e5a60bf/data/web/inc/functions.mailbox.inc.php#L4256

In my opinion we should implement a clean up task or adjust the code / database structure to prevents that the table is growing limitless.

Am i missing something?
Or any other suggestions?

### Logs:

```shell
# row count of sasl_log
docker-compose exec mysql-mailcow mysql -u root -p$DBROOT $DBNAME -e 'select count(datetime) from sasl_log;'
+-----------------+
| count(datetime) |
+-----------------+
|         3434496 |
+-----------------+

# messure time for getting mailboxes via api
time curl --silent --header 'X-API-Key: ...' 'http://mail.mailcow.localhost/api/v1/get/mailbox/reduced' --output /dev/null
0.03s user 0.03s system 0% cpu 57.893 total

# truncate sasl_log table, and count rows again to verify
docker-compose exec mysql-mailcow mysql -u root -p$DBROOT $DBNAME -e 'truncate sasl_log;'
docker-compose exec mysql-mailcow mysql -u root -p$DBROOT $DBNAME -e 'select count(datetime) from sasl_log;'
+-----------------+
| count(datetime) |
+-----------------+
|               0 |
+-----------------+

# measure time to get the mailboxes again
time curl --silent --header 'X-API-Key: ...' 'http://mail.mailcow.localhost/api/v1/get/mailbox/reduced' --output /dev/null
0.01s user 0.01s system 0% cpu 6.833 total
```

### Steps to reproduce:

```plain text
1. Mailcow installation with many users
2. A big sasl_log table
3. open `/mailbox` the tab mailboxes, which gets slow when there are many entries in the sasl_log table
```

### Which branch are you using?

master

### Operating System:

NixOS master

### Server/VM specifications:

local dev machine, 8GB, 4 Cores, NVME

### Is Apparmor, SELinux or similar active?

not relevant

### Virtualization technology:

none

### Docker version:

20.10.23

### docker-compose version or docker compose version:

2.16.0

### mailcow version:

2023-03

### Reverse proxy:

None

### Logs of git diff:

```diff
diff --git a/data/assets/ssl-example/cert.pem b/data/assets/ssl-example/cert.pem
index 96d16bec..3c5dd1a5 100644
--- a/data/assets/ssl-example/cert.pem
+++ b/data/assets/ssl-example/cert.pem
@@ -1,19 +1,33 @@
 -----BEGIN CERTIFICATE-----
...
 -----END CERTIFICATE-----
diff --git a/data/assets/ssl-example/key.pem b/data/assets/ssl-example/key.pem
index cedf35a0..d32336af 100644
--- a/data/assets/ssl-example/key.pem
+++ b/data/assets/ssl-example/key.pem
@@ -1,27 +1,52 @@
------BEGIN RSA PRIVATE KEY-----
...
+-----END PRIVATE KEY-----
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index a445b60c..f228ba3b 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = mail.mailcow.localhost
+
```

### Logs of iptables -L -vn:

```plain text
not relevant
```

### Logs of ip6tables -L -vn:

```plain text
not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
not relevant
```

### DNS check:

```plain text
not relevant
```

**Comment by goodygh** [comment]
I wrote a [small script](https://gist.github.com/goodygh/39250013fba9d8d02e4b78ca74e28737#file-gc-sasl_log_class-php) to clean up the `sasl_logs` table

-  by defaults remove all logs older then 31 days
- keeps the last entry per services, even if its older then 31 days
- remove all entries older then 31 days, if no corresponding user in the mailbox table exists

tested like the follwoing

```shell
docker exec -i db mysql -u root -p"root" mailcow -e 'select * from sasl_log order by datetime' > full_table
php -f gc-sasl_log_class.php
mailbox1@example.com: Deleted 3 log entries.
mailbox2@example.com: Deleted 5 log entries.
mailbox3@example.com: Deleted 7 log entries.

docker exec -i db mysql -u root -p"root" mailcow -e 'select * from sasl_log order by datetime' > cleaned
```
```diff
git diff full_table cleaned | cat
diff --git a/full_table b/cleaned
index 46b640c..e9ad6b0 100644
--- a/full_table
+++ b/cleaned
@@ -1,12 +1,5 @@
 service    app_password    username    real_rip    datetime
-IMAP   NULL    mailbox3@example.com    1111:152:1111:0:1111:1111:1111:1111 2021-04-04 13:03:36
-EAS    NULL    mailbox1@example.com    1111:164:1111:0:1111:1111:1111:1111 2022-02-04 13:01:36
-SMTP   NULL    mailbox2@example.com    1111:162:1111:0:1111:1111:1111:1111 2022-02-04 13:03:36
-SMTP   NULL    mailbox2@example.com    1111:161:1111:0:1111:1111:1111:1111 2022-02-04 13:04:36
 SMTP   NULL    mailbox2@example.com    1111:156:1111:0:1111:1111:1111:1111 2022-02-04 13:11:37
-IMAP   NULL    mailbox3@example.com    1111:153:1111:0:1111:1111:1111:1111 2022-04-04 13:02:36
-EAS    NULL    mailbox1@example.com    1111:165:1111:0:1111:1111:1111:1111 2023-02-04 13:01:36
-EAS    NULL    mailbox1@example.com    1111:166:1111:0:1111:1111:1111:1111 2023-03-04 13:01:36
 EAS    NULL    mailbox1@example.com    1111:167:1111:0:1111:1111:1111:1111 2023-04-04 13:01:36
 IMAP   NULL    mailbox3@example.com    1111:154:1111:0:1111:1111:1111:1111 2023-04-04 13:01:36
 EAS    NULL    mailbox1@example.com    1111:168:1111:0:1111:1111:1111:1111 2023-04-05 13:01:36
```

Maybe this could help someone and if you agree i could try to implement this as a cronjob for the mailcow docker container.

**Comment by mkuron** [comment]
The preferred way to do this would probably be with a database EVENT (or maybe a TRIGGER) instead of a cronjob. I'll give it a try.

**Comment by goodygh** [comment]
True, this would be way better, thanks for trying.

**Comment by goodygh** [comment]
@mkuron i took a look at MySQL events and triggers, but they seem to be not that flexible, but it depends on what solution you have in mind.

If it is enough to delete entries older then, lets say 1 month, this would be an easy solution.

**Comment by mkuron** [comment]
I was thinking about something along the lines of
```sql
CREATE TRIGGER cleanup_sasl_log
BEFORE INSERT
ON sasl_log
FOR EACH ROW
DELETE FROM sasl_log
WHERE service = NEW.service AND username = NEW.username AND datetime < DATE_SUB(NOW(), INTERVAL 31 DAY)
```
It's not exactly the same as what your script does, bit it's close. Haven't had time to test it yet though.

**Comment by mkuron** [comment]
A TRIGGER turns out to not work here: `ERROR 1442 (HY000): Can't update table 'sasl_log' in stored function/trigger because it is already used by statement which invoked this stored function/trigger`. I guess I will have to use an EVENT then, or a cronjob like you did.

**Comment by mkuron** [comment]
This seems to work:
```sql
DROP EVENT IF EXISTS clean_sasl_log;
CREATE EVENT clean_sasl_log
ON SCHEDULE EVERY 1 DAY DO
DELETE sasl_log.* FROM sasl_log
LEFT JOIN (
  SELECT username, service, MAX(datetime) AS lastdate
  FROM sasl_log
  GROUP BY username, service
) AS last
ON sasl_log.username = last.username AND sasl_log.service = last.service
WHERE datetime < DATE_SUB(NOW(), INTERVAL 31 DAY) AND datetime < lastdate;
```

I'm going to test it for a few days and then submit a pull request. I think I should be able to put it here: https://github.com/mailcow/mailcow-dockerized/blob/428b917579f9f12236fbf1655edbbf5da300969f/data/Dockerfiles/phpfpm/docker-entrypoint.sh#L154-L176

Also, for future reference, if you want to know how many log entries there are per user and service, use this:
```sql
SELECT username, service, COUNT(*) AS num_entries, MAX(datetime) AS max_date, MIN(datetime) AS min_date
FROM sasl_log
GROUP BY username, service
ORDER BY username, service;
```

**Comment by goodygh** [comment]
Great work, this looks very nice and clean! I would suggest to delete also entries which have no more account and are older then 31 Days. I've done it like this, maybe this could be integrated in your event?

```sql
DELETE FROM sasl_log
WHERE username NOT IN
  (SELECT username FROM mailbox) AND
  datetime < DATE_SUB(NOW(), INTERVAL 31 DAY);
```
