### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#517]
I wonder, if there's any possiblity to set-up multiple domains for a single mailcow instance, e.g.

mail.domain1.tld
mail.domain2.tld

I've already set it up this way, however, i can't more than one domain in `MAILCOW_HOSTNAME` (it would break postfix).

Or do i have to set-up a 2nd mailcow instance in order to achieve this?

**Comment by mkuron** [comment]
You have to use a single MAILCOW_HOSTNAME (the name under which the server is reachable), but you can have any number of domains hosted on that machine. These are configured via the web interface. Typically, you'd use mail.domain1.tld for MAILCOW_HOSTNAME and just point domain1.tld's and domain2.tld's MX records at it.

**Comment by SoftCreatR** [comment]
That's what i have atm. Also the autoconfig and autodiscover entries for domain2.tld point to domain1.tld. However, clients like Outlook complain about the certificate, because the certificate is issued for domain1.tld.

EDIT:

I just discovered the option `ADDITIONAL_SAN`, which seems to be, what i'm looking for.

**Comment by mkuron** [comment]
You need a certificate with SANs for the autoconfig/autodiscover domains, then Outlook won't complain. E.g. mail.domain1.tld, autodiscover.domain1.tld, autoconfig.domain1.tld, autodiscover.domain2.tld, autoconfig.domain2.tld. Mailcow's integrated Let's Encrypt support can get them for you.

**Comment by SoftCreatR** [comment]
Yeah, just found the `ADDITIONAL_SAN` option and already playing around with it. Maybe, that's what i'm looking for.

**Comment by mkuron** [comment]
These domains should automatically have been added to the list of SANs. You shouldn't need to modify any variables manually as your setup is exactly what Mailcow is made for.

**Comment by SoftCreatR** [comment]
domain2.tld isn't a domain that is set-up in mailcow. All other domains are listed in the certificate, which is completely fine.

And according to the acme log, setting the domain as `ADDITIONAL_SAN` did the trick. A quick test via Outlook 2016 confirms it.

Thank you for your help :)

**Comment by jiapei100** [comment]
Facing the same issue today... What if I need a single **mailcow-dockerized** mail server, but mutliple domains connect to it???

@SoftCreatR @mkuron Anyway, can you provide a details summary? Say:
- How many files to be modified? Is it **ONLY** `mailcow.conf` to be modified?
- What content/variables inside `mailcow.conf` is to be modified?
- Should I add any other certificate? 
- Do I need to register some other `mail.domain1.com`, and `mail.domain2.com` ??? I think the answer to this particular question should be **NO**.

**Comment by CRK1918** [comment]
> Facing the same issue today... What if I need a single **mailcow-dockerized** mail server, but mutliple domains connect to it???
> 
> @SoftCreatR @mkuron Anyway, can you provide a details summary? Say:
> 
> * How many files to be modified? Is it **ONLY** `mailcow.conf` to be modified?
> * What content/variables inside `mailcow.conf` is to be modified?
> * Should I add any other certificate?
> * Do I need to register some other `mail.domain1.com`, and `mail.domain2.com` ??? I think the answer to this particular question should be **NO**.

I make a reply to your post in the Community forum: 

https://community.mailcow.email/d/137-multiple-domains-dns-setup/5
