### ISSUE TITLE
Mail Storage Flexibility

### ISSUE THREAD

**Issue by botsarenthuman** [mailcow/mailcow-dockerized#5170]
### Summary

If I'm hosting on a provider that only offers small volume disks, it would be nice to be able to tell mailcow that I've attached a new volume and to balance the mail storage between the 2 volumes. 

### Motivation

Storage flexibility on small providers

**Comment by kev-ac** [comment]
This sounds like a huge operational overhead, just to prevent data inconsistencies. More than that I don't see why this should be the job of Mailcow to manage. All Cloud providers I know of (explicitly excluding the hyperscalers like AWS or gcloud) support some sort of volumes / attached storage up to terabytes. 

If your cloud provider does only support small attached disks maybe you should build a storage pool with some kind of RAID / JBOD. Keep in mind to always have backups ;-)

**Comment by botsarenthuman** [comment]
Thanks, there's also the possibility of using multiple volumes in some sort of ZFS setup.
