### ISSUE TITLE
How to change or update the default "admin-moohoo" credentials?

### ISSUE THREAD

**Issue by cocky-punch** [mailcow/mailcow-dockerized#5173]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
How to change or update the default "admin-moohoo" credentials?
```

### Logs:

```plain text
.fds
```

### Steps to reproduce:

```plain text
.fdsfd
```

### Which branch are you using?

master

### Operating System:

fdsfds

### Server/VM specifications:

fdsfds

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

fdsfds

### Docker version:

343

### docker-compose version or docker compose version:

.

### mailcow version:

.

### Reverse proxy:

.

### Logs of git diff:

```plain text
.
```

### Logs of iptables -L -vn:

```plain text
.
```

### Logs of ip6tables -L -vn:

```plain text
.
```

### Logs of iptables -L -vn -t nat:

```plain text
.
```

### Logs of ip6tables -L -vn -t nat:

```plain text
.
```

### DNS check:

```plain text
.
```

**Comment by MAGICCC** [comment]
You can edit this line before you install mailcow
  
https://github.com/mailcow/mailcow-dockerized/blob/428b917579f9f12236fbf1655edbbf5da300969f/data/web/inc/init_db.inc.php#L1273

**Comment by cocky-punch** [comment]
@MAGICCC how would I edit it? I install mailcow in docker, not via the source code.

**Comment by MAGICCC** [comment]
You are downloading the source code when you are installing mailcow

**Comment by cocky-punch** [comment]
How will then I change them now, after having installed mailcow? How to connect to Postgresql?

**Comment by MAGICCC** [comment]
You can change the passwort in the UI, if you want to change the default password before then edit the file as I said.

mailcow does not support postgres officially


I don't know what you want to accomplish with this but that's not bug nor enhancement
