### ISSUE TITLE
only_email mobileconfig contains DAV too

### ISSUE THREAD

**Issue by gitterdoneplease** [mailcow/mailcow-dockerized#5175]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Using https://${MAILCOW_HOSTNAME}/mobileconfig.php?only_email per the documentation produces a mobileconfig file that contains DAV information.
```

### Logs:

```plain text
no error logs produced
```

### Steps to reproduce:

```plain text
1. go to https://${MAILCOW_HOSTNAME}/mobileconfig.php?only_email
2. login
3. open mobileconfig file produced
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04.2 LTS

### Server/VM specifications:

E5-2697 v4, 768GB RAM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Proxmox

### Docker version:

 23.0.1

### docker-compose version or docker compose version:

v2.16.0

### mailcow version:

2023-04a

### Reverse proxy:

no

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by goodygh** [comment]
I tried to look into it but can't reproduce it, i am doing something wrong?

```shell
# without only_email i am getting dav settings
curl -s 'http://mail.mailcow.localhost/mobileconfig.php' -H 'Cookie: PHPSESSID=6dc02d40e85169728d9c7ed60070c8b3' | grep -i caldavacc
        <key>CalDAVAccountDescription</key>

# with only_email i get no hits for any dav keys
curl -s 'http://mail.mailcow.localhost/mobileconfig.php?only_email' -H 'Cookie: PHPSESSID=6dc02d40e85169728d9c7ed60070c8b3' | grep -i dav
```

**Comment by gitterdoneplease** [comment]
Thanks for looking into this. How do I find my session ID? I'll try with curl.

**Comment by goodygh** [comment]
Its not your session id, i am testing on my local mailcow testsetup with my own sessionid.

**Comment by gitterdoneplease** [comment]
I get that; I wanted to test against my own mailcow setup using my own sessionid. I just didn't know if there was a simple way to find it.

That said, poking at this more when I go to https://mailcowhost/mobileconfig?only_email without first logging in the server rewrites to https://mailcowhost/index.php?mobileconfig&only_email. If you run:

`curl -s 'http://mail.mailcow.localhost/index.php?mobileconfig&only_email' -H 'Cookie: PHPSESSID=6dc02d40e85169728d9c7ed60070c8b3' | grep -i dav`

What do you get?

FWIW I just updated to [2023-04b] as well.

**Comment by goodygh** [comment]
I usually open the network tab in the developer toolbar (mostly F12) in my browser make the request i like to test and copy it as curl.

With your command i get redirected to `/user` and therefore get the login page (html).

You can also tell how you can reproduce it, it does not have to be with curl.

**Comment by gitterdoneplease** [comment]
Thanks! I figured it out too. I get the same thing. I wanted to check with curl to see if it was something else going on.

The steps to reproduce remain the same. If I follow the documentation and go to https://${MAILCOW_HOSTNAME}/mobileconfig.php?only_email the server will rewrite to https://${MAILCOW_HOSTNAME}/index.php?mobileconfig&only_email. From there the login produces a mobileconfig with CalDAV information included.

The workaround is to first go to https://${MAILCOW_HOSTNAME}/, login and then go to https://${MAILCOW_HOSTNAME}/mobileconfig.php?only_email. This is painful to explain to users and is not the way the documentation is written.

On your setup, using a regular web browser and not being logged in, does http://mail.mailcow.localhost/mobileconfig.php?only_email get rewritten to http://mail.mailcow.localhost/index.php?mobileconfig&only_email?

**Comment by goodygh** [comment]
Perfect, thanks, like this its reproducible, i hope i find some time to look further into it.
