### ISSUE TITLE
Nextcloud - Mailcow - This version of nextcloud is not compatible with PHP>=8.2. You are currently running 8.2.4

### ISSUE THREAD

**Issue by anothergoodguy** [mailcow/mailcow-dockerized#5185]
the issue [#5163](https://github.com/mailcow/mailcow-dockerized/issues/5163) with same info is closed as complete. But I don't have a backup to restore and do version to version upgrade. Can you please help upgrading to latest / compatible version of Next cloud?

I have even tried the option mentioned in [2328](https://github.com/mailcow/mailcow-dockerized/issues/2328#issuecomment-467957066)
Below is my original message on a closed issue. 

             
 I don't think it's completed. I still get the same error on our installation after mailcow upgrade...

With webupgrader it updates only till 22.2.10; during this upgrade, the nextcloud web upgrader is not running OCC with the following error :

```
f4a0fefebec4:/opt$ php /web/nextcloud/occ upgrade
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.2.4.f4a0fefebec4:/opt$
```

_Originally posted by @anothergoodguy in https://github.com/mailcow/mailcow-dockerized/issues/5163#issuecomment-1507165527_

**Comment by MAGICCC** [comment]
Can you try to execute the nextcloud.sh helperscript? Maybe multiple times

**Comment by anothergoodguy** [comment]
thank you for quick response...

this is teh error I am getting: root@ip-172-31-21-65:/opt/mailcow-dockerized# helper-scripts/nextcloud.sh -u
Found all prerequisites! Continuing...
Are you sure you want to update Nextcloud (with Nextclouds own updater)? [y/N] y
Error: Nextcloud seems not to be installed.

**Comment by MAGICCC** [comment]
Could you try to use this version of the script?
https://github.com/mailcow/mailcow-dockerized/pull/5187

**Comment by anothergoodguy** [comment]
WoW!!! Awesome!!

It took a set of reruns, but worked finally !!!

@MAGICCC thank you very much !!
