### ISSUE TITLE
Support for Arm64

### ISSUE THREAD

**Issue by kimdre** [mailcow/mailcow-dockerized#5189]
### Summary

I would love to see builds form ARM-based processors.

### Motivation

All popular cloud providers now support ARM-based systems and cost less than x64. Mailcow builds for ARM would open great oppurtunities to safe some bucks on server hosting costs. 
Hetzner for example now has them too. And a 4 vCPU 8GB RAM system there costs over €3 less than the x64 equivalent, which only has 2 vCPU.

**Comment by MAGICCC** [comment]
You may want to look into https://github.com/mailcow/mailcow-dockerized/issues/879
