### ISSUE TITLE
How to change login page webmail button url

### ISSUE THREAD

**Issue by tbswork1** [mailcow/mailcow-dockerized#5206]
### Summary

Currently it is linked to SoGo mail which has been ditched and we are using rc. Can we change the button url? 

### Motivation

We don't like Sogo and use another. This saves typing in url for webmail.

**Comment by benedict1337** [comment]
You should just read the documentation. :)

"Optionally, you can add Roundcube's link to the mailcow Apps list. To do this, open or create data/web/inc/vars.local.inc.php and add the following code-block:"

```
$MAILCOW_APPS = array(
  array(
    'name' => 'SOGo',
    'link' => '/SOGo/'
  ),
  array(
    'name' => 'Roundcube',
    'link' => '/rc/'
   )
);
```

[Docs](https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/#integrate-carddav-addressbooks-in-roundcube)
