### ISSUE TITLE
Reverse proxy and ACME

### ISSUE THREAD

**Issue by schnurzli** [mailcow/mailcow-dockerized#522]
Hi,

I configured my dns to handle mailcow via **mail.mydomain.com**
i have activated additional sans:
```
# Additional SAN for the certificate
ADDITIONAL_SAN=mail.mydomain.com,autodiscover.mydomain.com,autoconfig.mydomain.com
```
Everything works except mail server certificate (mail.domain.com has my own certificate)
Here mailcow provides his own certificate for **mail.example.org** - which leads to error: server principal name ist wrong...

Where should i start? I thought, mailcow initializes **mail.mydomain.com** on his own. Do i have to assign it anywhere?

BG Richard

**Comment by mkuron** [comment]
If the example certificate is still being served, the most likely the acme container hasn't run yet (try `docker-compose restart acme-mailcow`) or has failed (check the logs using `docker-compose logs acme-mailcow`).

You actually don't need any of the additional SANs you specified. `$MAILCOW_HOSTNAME` is automatically added to that list, just like autodiscover and autoconfig for all domains that you have created using the web admin UI.

**Comment by schnurzli** [comment]
thanks for fast reply.

i will try a rerun acme-mailcow. actually i am locked out because of too many tries :-)
`Error creating new authz: Too many invalid authorizations recently`

Another error in this log - is this a hint for a solution?
`acme-mailcow_1       | acme-client: transfer buffer: 
[{ "type": "http-01", "status": "invalid", "error": 
{ "type": "urn:acme:error:unauthorized", 
"detail": "Invalid response from http://autoconfig.domainA.com/.well-known/acme-challenge/dm...: \
"\u003c!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"\u003e\n\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003e404 
Not Found\u003c/title\u003e\n\u003c/head\u003e\u003cbody\u003e\n\u003ch1\u003eNot Found\u003c/h1\u003e\n\u003cp\"", "status": 403 }, 
"uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/IuHeJ--41X.../18...", "token": "dm...", 
"keyAuthorization": "dm...", "validationRecord": [ 
{ "url": "https://www.domainA.com/.well-known/acme-challenge/dm...", 
"hostname": "www.domainA.com", "port": "443", "addressesResolved": [ "1.2.3.4" ], "addressUsed": "1.2.3.4", 
"addressesTried": [] }, { "url": "http://autoconfig.domainA.com/.well-known/acme-challenge/dmn...", 
"hostname": "autoconfig.domainA.com", "port": "80", "addressesResolved": [ "1.2.3.4" ], "addressUsed": "1.2.3.4", "addressesTried": [] } ] }] (1473 bytes)
`


So next try without beeing locked out tomorrow - now i'll try to sleep :-)

**Comment by schnurzli** [comment]
Hi,
here a full entry of another try. It seems to work at the beginning (Found A record...)
then acme ads default subdomains to san and after that it requests auth at letsencrypt.org.
This is the point where it goes wrong (my opinion).
Need some advice.

[acme.txt](https://github.com/mailcow/mailcow-dockerized/files/1240939/acme.txt)

**Comment by ChrisEgem** [comment]
Hi i have the same problem here that my cert is already on mail.example.org instead of mail.mydomain.com. And also the same output as @schnurzli 
The problem appears when i want to add my Mail Account to a mail client.

**Comment by HesselTjeerdsma** [comment]
Has this error already been resolved?

**Comment by mkuron** [comment]
This is not a Mailcow error and not related to Outlook. Mailcow only uses the example certificate when it was unable to obtain one. Check the acme containers log and fix any issues it reports. If you have a reverse proxy, make sure it passes the challenge.

**Comment by HesselTjeerdsma** [comment]
@mkuron Thanks for your reply. I don't see any errors in my acme log. Could the problem be that I set the ssl certificates on the reverse proxy? How can I make sure my reverse proxy passes the challenge?

**Comment by mkuron** [comment]
If you have a reverse proxy, it is your own responsibility to create and configure certificates for it. Mailcow can‘t do that for you. The challenge path is /.well-known/acme-challenge. If you use the acme container, that needs to be passed through to Mailcow from your proxy. If you want to request certificates for your proxy, you obviously can‘t do that.

**Comment by xiaoveiti** [comment]
So how do I use a reverse proxy with ssl and still use letsencrypt to generate the files for mailcow?

**Comment by mkuron** [comment]
You let the reverse proxypass /.well-known/acme-challenge to Mailcow. Of course, this means that the reverse proxy can’t itself get Let’s Encrypt certificates, so ideally you use the ones generated by Mailcow for the reverse proxy too.

**Comment by xiaoveiti** [comment]
I also thought about to let mailcow handle the ssl settings, so I guess this would be enough?

    # Letsencrypt
    location ~ /.well-known {
        proxy_pass http://127.0.0.1:8080/.well-known;
        allow all;
        auth_basic off;
    }

Just figured out, I cannot use proxy_pass here :/ Any suggestions?

**Comment by xiaoveiti** [comment]
my fail, ... its enough to proxy_pass the whole location, .. it's getting late 💃 

just include the certificates:

```
    ssl_certificate /opt/mailcow-dockerized/data/assets/ssl/cert.pem;
    ssl_certificate_key /opt/mailcow-dockerized/data/assets/ssl/key.pem;
    ssl_dhparam /opt/mailcow-dockerized/data/assets/ssl/dhparams.pem;
```
