### ISSUE TITLE
The error message show blew and how to fix?

### ISSUE THREAD

**Issue by qnmlgdsb** [mailcow/mailcow-dockerized#523]
root@RobustRound-VM:~/mailcow-dockerized# ls
CODE_OF_CONDUCT.md  docker-compose.yml  mailcow.conf                README.md
CONTRIBUTING.md     generate_config.sh  mailcow-reset-admin.sh      update.sh
data                LICENSE             mailcow-setup-relayhost.sh
root@RobustRound-VM:~/mailcow-dockerized# docker-compose up -d
mailcowdockerized_mysql-mailcow_1 is up-to-date
mailcowdockerized_clamd-mailcow_1 is up-to-date
mailcowdockerized_ipv6nat_1 is up-to-date
Creating mailcowdockerized_unbound-mailcow_1 ...
Creating mailcowdockerized_unbound-mailcow_1 ... done
Creating mailcowdockerized_redis-mailcow_1 ...
Creating mailcowdockerized_postfix-mailcow_1 ...
Creating mailcowdockerized_redis-mailcow_1
Creating mailcowdockerized_postfix-mailcow_1
Creating mailcowdockerized_memcached-mailcow_1 ...
Creating mailcowdockerized_sogo-mailcow_1 ...
Creating mailcowdockerized_dovecot-mailcow_1 ...
Creating mailcowdockerized_memcached-mailcow_1
Creating mailcowdockerized_sogo-mailcow_1
Creating mailcowdockerized_postfix-mailcow_1 ... error

ERROR: for mailcowdockerized_postfix-mailcow_1  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (912e8c70d2894e6ca5f45df1caab0707d92333a39a769f0a871c50ab07e59bbb): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address alCreating mailcowdockerized_dovecot-mailcow_1 ... done
Creating mailcowdockerized_php-fpm-mailcow_1 ...
Creating mailcowdockerized_php-fpm-mailcow_1 ... done
Creating mailcowdockerized_nginx-mailcow_1 ...
Creating mailcowdockerized_nginx-mailcow_1 ... error

ERROR: for mailcowdockerized_nginx-mailcow_1  Cannot start service nginx-mailcow: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"process_linux.go:322: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-08-22T02:02:00-04:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth5c6c8c3 to sandbox: error setting interface \\\\\\\\\\\\\\\"veth5c6c8c3\\\\\\\\\\\\\\\" IPv6 to fd4d:6169:6c63:6f77::a/64: failed to enable ipv6: reexec to set IPv6 failed: fork/exec /proc/self/exe: cannot allocate memory\\\\\\\" \\\\n\\\"\""

ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_postfix-mailcow_1 (912e8c70d2894e6ca5f45df1caab0707d92333a39a769f0a871c50ab07e59bbb): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use

ERROR: for nginx-mailcow  Cannot start service nginx-mailcow: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"process_linux.go:322: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-08-22T02:02:00-04:00\\\\\\\" level=fatal msg=\\\\\\\"failed to add interface veth5c6c8c3 to sandbox: error setting interface \\\\\\\\\\\\\\\"veth5c6c8c3\\\\\\\\\\\\\\\" IPv6 to fd4d:6169:6c63:6f77::a/64: failed to enable ipv6: reexec to set IPv6 failed: fork/exec /proc/self/exe: cannot allocate memory\\\\\\\" \\\\n\\\"\""

ERROR: Encountered errors while bringing up the project.

**Comment by chriscroome** [comment]
`cannot allocate memory` would suggest to me that perhaps your server doesn't have enough RAM?
