### ISSUE TITLE
Proposition Improvement : update.sh docker pull before docker stop

### ISSUE THREAD

**Issue by JOduMonT** [mailcow/mailcow-dockerized#524]
Hi;

Would be better if the docker pull the new version before stopping all service ?
Such as yesterday I did a ./update.sh
and during the pull something when wrong
- my connection was super slow
- the pull stop in the middle of SOGo

It's only a proposition ;)

Thanks for you're support and your awesome compilation of software

**Comment by mkuron** [comment]
Sounds reasonable as it helps in keeping the downtime as short as possible. You should submit a pull request with that change.

**Comment by JOduMonT** [comment]
I hope I did well ;)

**Comment by normanu** [comment]
This would be preferable, but is still not the case.
As we speak I'm updating and it pulled down the stack.
Dovecot image was not available so it is building the image itself, this takes a long time.
Would have been better if the services where not down in the mean time.

**Comment by andryyy** [comment]
See the other issues, this led to problems and was reverted.

The images are all online and available: https://hub.docker.com/r/mailcow/dovecot/tags 

Please check your compose file against origin/master.
