### ISSUE TITLE
Greek Localization

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#5243]
### Summary

I would like to request the addition of Greek localization support for the project. As a fluent Greek speaker, I am willing to contribute by translating the project into Greek.

### Motivation

 This will enable users who prefer or require Greek as their primary language to use the project more effectively and comfortably.

**Comment by MAGICCC** [comment]
Hello,

that's very nice!
I created a new translation project on our Weblate: https://translate.mailcow.email/projects/mailcow-dockerized/translation/gr-gr/

Do note that you can't validate any string just adding suggestions! There's an issue with weblate that validated strings will go in the live project even when nobody checked them. I will trust everyone that they enter valid things, but that's to avoid unnessary pushs on the main repo.

**Comment by ghost** [comment]
Hey,

I 'll create an account and start working on it during the weekends.

> Do note that you can't validate any string just adding suggestions
ok : )

Should I close the issue or provide updates here about my progress from time to time?

**Comment by MAGICCC** [comment]
I can close the issue yes. No need to update on the status. Once in a while I check if there are new suggestions and approve them. If the language is not fully done, mailcow will use the english strings.

**Comment by ghost** [comment]
Should I go for a full translation? For instance in Greek e-mail -> electronic-email -> ηλεκτρονικό-ταχυδρομίο. So a user that does not speak English at all will be able to use mailcow? Or I should assume some level of familiarity with some basic vocabulary? I 'm worrying that some translationσ will not fit in the UI boxes correctly. What do you suggest?

**Comment by MAGICCC** [comment]
I would go with a translation that almost everybody would understand. My grandparents do know what an E-Mail is so I guess you don't need to translate electronic-mail word by word
