### ISSUE TITLE
Sogo disable user lookup

### ISSUE THREAD

**Issue by botsarenthuman** [mailcow/mailcow-dockerized#5245]
### Summary

For a particular domain, I'd like to tell Sogo that users on that domain cannot see each other in Sogo.

### Motivation

Certain domains needs to have separate users for the domain, unlike other domains where the users should be able to see each other.

**Comment by FreddleSpl0it** [comment]
You can edit the Domain via mailcow UI and uncheck "Global Address List".
The GAL contains all objects of a domain and cannot be edited by any user. Free/busy information in SOGo is missing, if disabled! Restart SOGo to apply changes.

**Comment by botsarenthuman** [comment]
Bingo this worked, thanks!
