### ISSUE TITLE
mailcow/dovecot - undefenitly restarting

### ISSUE THREAD

**Issue by GVA-Guillaume** [mailcow/mailcow-dockerized#5255]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Threads: 12  Questions: 15786  Slow queries: 0  Opens: 52  Open tables: 43  Queries per second avg
```

### Logs:

```plain text
sed: -e expression #1, char 111: unknown option to `s'
Uptime: 1568  Threads: 10  Questions: 1412  Slow queries: 0  Opens: 49  Open tables: 40  Queries per second avg: 0.900
sed: -e expression #1, char 111: unknown option to `s'
Uptime: 1628  Threads: 10  Questions: 1453  Slow queries: 0  Opens: 49  Open tables: 40  Queries per second avg: 0.892
sed: -e expression #1, char 111: unknown option to `s'
Uptime: 1689  Threads: 9  Questions: 1474  Slow queries: 0  Opens: 49  Open tables: 40
```

### Steps to reproduce:

```plain text
1. no idea...
```

### Which branch are you using?

master

### Operating System:

20-Ubuntu

### Server/VM specifications:

8 Cores @ 2%-4%/7.55GB @ 46%

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

.

### Docker version:

23.0.6

### docker-compose version or docker compose version:

v2.18.1

### mailcow version:

2023-04b

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
diff --git a/LICENSE b/LICENSE
deleted file mode 100644
index 9cecc1d4..00000000
--- a/LICENSE
+++ /dev/null
@@ -1,674 +0,0 @@
-                    GNU GENERAL PUBLIC LICENSE
-                       Version 3, 29 June 2007
-
- Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
- Everyone is permitted to copy and distribute verbatim copies
- of this license document, but changing it is not allowed.
-
-                            Preamble
-
-  The GNU General Public License is a free, copyleft license for
-software and other kinds of works.
-
-  The licenses for most software and other practical works are designed
-to take away your freedom to share and change the works.  By contrast,
-the GNU General Public License is intended to guarantee your freedom to
-share and change all versions of a program--to make sure it remains free
-software for all its users.  We, the Free Software Foundation, use the
-GNU General Public License for most of our software; it applies also to
```

### Logs of iptables -L -vn:

```plain text
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```

### Logs of ip6tables -L -vn:

```plain text
ip6tables v1.8.7 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```

### Logs of iptables -L -vn -t nat:

```plain text
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```

### Logs of ip6tables -L -vn -t nat:

```plain text
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```

### DNS check:

```plain text
151.101.193.69
151.101.129.69
151.101.65.69
151.101.1.69
```

**Comment by MAGICCC** [comment]
Seems your current user doesn't have enough access to perform such things. Did you try to run it as root?

**Comment by GVA-Guillaume** [comment]
nop, do i have to give any root access into the container ?

**Comment by GVA-Guillaume** [comment]
Maybe an important information, I tried with the official dovecot image, and it was ok, nothing happen except I was not synced with the user database, in this situation, the problem is, I am not able to access to the bootstrap ui

**Comment by MAGICCC** [comment]
No but you need to run the stack with root access or in general with elevated rights
 +we don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

**Comment by GVA-Guillaume** [comment]
I understood that this kind of blurry message can concern many many cases, in my side the problem was the passphrase format of privileged account, for any reasons I can't understand, you are not able to use some special characters, I did not make the test about which ones ? all ? somes ? I am not able to answer, but I finally find a normal situation changing the passphrase. Thank you MAGICCC.
