### ISSUE TITLE
Reduce default `MAILDIR_GC_TIME` value (to zero)

### ISSUE THREAD

**Issue by link2xt** [mailcow/mailcow-dockerized#5274]
### Summary

Default `MAILDIR_GC_TIME` which determines the garbage retention time should be zero. There is no need to keep garbage on the disk and take space if it is not used. Maybe the whole setting should be removed.

### Motivation

I have recently had a server run out of disk space. After running `ncdu` I found that 3GB out of 20GB are taken by `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/_garbage/`.

I found a garbage-collection script https://github.com/mailcow/mailcow-dockerized/blob/e691d2c78216c2628d9a08abe6f6f63c45802f87/data/Dockerfiles/dovecot/maildir_gc.sh which is supposed to be run hourly according to the comment in the generated config, actually it is configured to run `@every 30m`.

This garbage-collection script runs every 30 minutes, but only deletes files that are older than 7200 minutes (5 days) by default. I do not see any reason to keep garbage for 5 days instead of deleting it immediately and not checking its age over and over.

**Comment by MAGICCC** [comment]
So you are saying that you are fine to lose mails    after deleting mailboxes without any chance to recover them? Yes you should have backups but when is the last run?
If you dont like the setting set it to 0 for you

**Comment by link2xt** [comment]
I have looked at the code (grep for `_garbage) and did not see any code for restoring a mailbox from _garbage or otherwise using it. Also looked in the web UI and API at https://demo.mailcow.email/api/, but do not see a restore option.

Is it documented anywhere how to restore a mailbox or domain from garbage?

There is a related issue at #2483

**Comment by DerLinkman** [comment]
> Is it documented anywhere how to restore a mailbox or domain from garbage?

It's documented in the Documentation how to:

https://docs.mailcow.email/backup_restore/b_n_r-accidental_deletion/#mail
