### ISSUE TITLE
sieve filter does not work

### ISSUE THREAD

**Issue by cjw0202** [mailcow/mailcow-dockerized#5285]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
i have writen a sieve script
redirect "dest@email.com";

and i send an email to source@email.com, the email cannot redirect to dest@email.com
```

### Logs:

```plain text
Jun 14 13:40:39 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.250
Jun 14 13:41:35 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.250
Jun 14 13:42:01 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.250
Jun 14 13:42:52 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.250
Jun 14 13:43:38 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>, rip=172.22.1.9, lip=172.22.1.250
Jun 14 13:44:22 0b10bd82d601 dovecot: managesieve-login: Disconnected: Connection closed (no auth attempts in 0 secs): user=<>,
```

### Steps to reproduce:

```plain text
nothing
```

### Which branch are you using?

master

### Operating System:

CentOS Linux release 7.6.1810 (Core)

### Server/VM specifications:

8C8G

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

VMware

### Docker version:

24.0.2

### docker-compose version or docker compose version:

 v2.18.1

### mailcow version:

2023-05a

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
nothing
```

### Logs of iptables -L -vn:

```plain text
nothing
```

### Logs of ip6tables -L -vn:

```plain text
nothing
```

### Logs of iptables -L -vn -t nat:

```plain text
nothing
```

### Logs of ip6tables -L -vn -t nat:

```plain text
nothing
```

### DNS check:

```plain text
nothing
```

**Comment by EricThi** [comment]
Hello,

Can you detail more about your rule sieve ? on dovecot directly or via webui ?

Here, via webui : 
Here is just an example of Sieve rule.

on your /mailbox, Tab "Filters".

You can create "Add filter" and Select domain.tld and Prefilter.

## Rule Example for matches To and redirect mail, mark as read and move mail on subfolder

```
require "fileinto";
require "mailbox";
require "variables";
require "subaddress";
require "envelope";
require "duplicate";
require "imap4flags";

if header :matches "To" "*mail@domain.tld*" {
   redirect "anothermail@anotherdomain.tld";
   setflag "\\seen"; /* Mark mail as read */
   fileInto "INBOX/SubFolder"; /* Move mail on subfolder after */
} else {
  # The rest goes into INBOX
  # default is "implicit keep", we do it explicitly here
  keep;
}
```
Keep Warning about From/To : if on source of your mail, you see firstname name <mail@domain.tld> : Your "if header" need to match all data
If you use ":is" to replace ":matches", you need to set the exact patern.

[Examples rules Sieve](https://doc.dovecot.org/configuration_manual/sieve/examples/)
[IETF : Draft with examples](https://datatracker.ietf.org/doc/html/draft-happel-sieve-filter-rule-metadata-00)

---
On parallel, I search many time to create rules Sieve on my side, I proposal this information on the Doc via this PR : 
https://github.com/mailcow/mailcow-dockerized-docs/pull/584

Regards,
Eric.

**Comment by cjw0202** [comment]
@EricThi Thanks a lot
