### ISSUE TITLE
Anti-Abuse for servers at authentication time

### ISSUE THREAD

**Issue by denji** [mailcow/mailcow-dockerized#530]
The goal of 'wforce' is to detect brute forcing of passwords across many
servers, services and instances.  In order to support the real world, brute
force detection policy can be tailored to deal with "bulk, but legitimate"
users of your service, as well as botnet-wide slowscans of passwords.
* https://github.com/PowerDNS/weakforced

wforce is aimed to receive message from services like:

 * IMAP
 * POP3
 * Webmail logins
 * FTP logins
 * Authenticated SMTP
 * Self-service logins
 * Password recovery services

**Comment by mkuron** [comment]
Partial duplicate of #529?

If there is a different piece of software that fulfils all our requirements and has major advantages over the existing fail2ban-like solution, feel free to submit a pull request. I don't see any reason to replace the current solution though.
