### ISSUE TITLE
on webmail inbox page,  the searchInput do not support chinese language 

### ISSUE THREAD

**Issue by cjw0202** [mailcow/mailcow-dockerized#5305]
### Summary

on webmail inbox page,  the searchInput do not support chinese language 

### Motivation

support chinese language

**Comment by tomy0000000** [comment]
You have two options to contribute to translation:

1. The easy way: Registered in [weblate](https://translate.mailcow.email/engage/mailcow-dockerized/) and make the edit

2. Fork this repo, make changes to [data/web/lang/lang.zh-tw.json](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/lang/lang.zh-tw.json) and submit PR for review.

**Comment by cjw0202** [comment]
it's an issue

**Comment by tomy0000000** [comment]
> it's an issue

Of course, it's obvious.

And my humble response implies that you should try to be helpful instead of asking someone to do something for you.

If you try something and bump into problems, post what you've tried, and I and other contributors are very willing to help.
