### ISSUE TITLE
Can send emails but can't receive any

### ISSUE THREAD

**Issue by slice3984** [mailcow/mailcow-dockerized#531]
Hi,
sending mails work fine but can't receive any.
My domain: sebastian.network
Mail server IP: 146.0.47.187 

i used this tutorial: https://mailcow.github.io/mailcow-dockerized-docs/install/ to install it on a fresh debian vserver.

**Comment by phillipplum** [comment]
You must set a MX record for your domain!

**Comment by slice3984** [comment]
Hi, 
had the wrong MX record format, works fine now.
