### ISSUE TITLE
 shared_namespace.conf changeable

### ISSUE THREAD

**Issue by 2ec98lwlhimflzx2** [mailcow/mailcow-dockerized#5327]
### Summary

Hi, 

I would like to suggest to make the shared_namespace.conf for dovecot changeable. 
Right now the file is hardcoded created, any changes will be overwritten. 

Reason is, that we want an user based seen flag, not an message based. 
Had tried to make the changes via extra.conf but had no luck.

kind regards
rc

### Motivation

Use :INDEXPVT=~ 
Seen Flags are userbased.

**Comment by MAGICCC** [comment]
You could add a script in /data/hooks/dovecot with your edits, because it will be executed when you start the container
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/dovecot/docker-entrypoint.sh#L423

**Comment by 2ec98lwlhimflzx2** [comment]
Does Work. Thanks for the hint. 

kind regards
rc
