### ISSUE TITLE
Mailpush don't work

### ISSUE THREAD

**Issue by fibis** [mailcow/mailcow-dockerized#534]
I switched to mailcow-dockerized a while ago and I think mailpush don't work for me. Could it be possible the the firewall of the server is blocking it? With port is used for this feature?

**Comment by andryyy** [comment]
Do you use ActiveSync? Or IMAP?

As long as your ActiveSync account succeeds to create, you should be fine. It uses https. IMAP push needs to be supported by your client.

**Comment by TiiFuchs** [comment]
I have also huge problems with push. It just doesn't seem to work. I have ActiveSync configured on my iPhone and it verifies correctly but after a while push does not work anymore. I don't know why.

**Comment by andryyy** [comment]
Can you grep `docker-compose logs sogo-mailcow` for "no child"?

**Comment by TiiFuchs** [comment]
That does not return any line. :(

**Comment by TiiFuchs** [comment]
I will try updating and resetting that ActiveSync cache, but in productive use it is very annoying to tell every user to "check" every now and then if it is still working and resetting that else... :/

Maybe I just back up to IMAP than...

**Comment by andryyy** [comment]
If that does not return a line, logging is either turned off or something else is wrong. But this is Docker-related and not mailcow. You should really check why it does not return any data.

I have not seen that push error happening with enough SOGo workers available. You can try to increase the workers after fixing Docker.

Edit: Best would be to run `docker-compose down`, followed by `systemctl restart docker` and `docker-compose up -d`.

**Comment by TiiFuchs** [comment]
It does return a ton of mails. But no line containing "no child".
The grep is filtering anything. That's what I meant. Sorry.

**Comment by andryyy** [comment]
Ah, I see. You can check your logs (SOGo logs) what happens when a mail arrives and if it tries to push it to your iPhone.
