### ISSUE TITLE
Spamhaus DQS domain server in dns_blocklists.cf

### ISSUE THREAD

**Issue by KiwiActinidia** [mailcow/mailcow-dockerized#5344]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After seeing the new Spamhaus policy, I register myself to new service and in the login account
reading the first manual rows I find this message:
"Caution: the datafeed query service uses the domain spamhaus.NET and not spamhaus.ORG. Do not confuse them as they are not interchangeable."

In the new file dns_blocklists.cf /postfix.sh the list contain these wrong settings:

${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.org=127.0.0.[10;11]*8
${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.org=127.0.0.3*4
${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.org=127.0.0.2*3

Moooooo
Alessandro
```

### Logs:

```plain text
N/A
```

### Steps to reproduce:

```plain text
N/A
```

### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

8G, 2cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Contabo

### Docker version:

24.0.2

### docker-compose version or docker compose version:

v2.6.1

### mailcow version:

2023-07

### Reverse proxy:

N/A

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by mrclschstr** [comment]
Related? https://github.com/mailcow/mailcow-dockerized/issues/5340#issuecomment-1657937457

**Comment by DocFraggle** [comment]
I created the above PR to fix the issue, you can close the issue.
