### ISSUE TITLE
dns_blocklists.cf made a fatal error

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#5351]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Just wanted to let you know, I fixed the problem myself by deleting the file after the error and running update.sh again.

After today's update there was a fatal error with the file "dns_blocklists.cf".

It said me that i have modified or created that file "dns_blocklists.cf" but i had never. but the update.sh sayed me to move or delete the file, so i did and run update.sh again and it fixed it. This is only for info maybe you need to do something :)
```

### Logs:

```plain text
-
```

### Steps to reproduce:

```plain text
-
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04.5 LTS

### Server/VM specifications:

VM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2023-07a

### Reverse proxy:

NO

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by kwisatz** [comment]
Same here

```
Merging local with remote code (recursive, strategy: "theirs", options: "patience"...
error: The following untracked working tree files would be overwritten by merge:
	data/conf/postfix/dns_blocklists.cf
Please move or remove them before you merge.
Aborting
```

**Comment by ghost** [comment]
Same here. Fixing by rename the File

**Comment by DocFraggle** [comment]
The problem is that before [this commit](https://github.com/mailcow/mailcow-dockerized/commit/0f337971ff12b89805bb58b14b858c74e8fdb7dd) the postfix.sh script created the file dns_blocklists.cf while starting up the postfix container for the first time, it wasn't part of the git repository. With the mentioned commit this file was added to the repo itself and is appended only if Spamhaus blocklists apply for your system. That's the reason why git is complaining, and deleting it before running update.sh is the proper way to go.

The next update should now run without problems.

**Comment by brunick** [comment]
i would guess that a lot of people will see this message, maybe you should add it to breaking changes?
or update the update script to check for the file and delete it?

**Comment by DocFraggle** [comment]
@DerLinkman any thoughts about how this kind of issue was addressed in the past? Let update.sh check if dns_blocklists.cf is already Git controlled and delete it otherwise before checking out or something like this?

**Comment by DerLinkman** [comment]
> i would guess that a lot of people will see this message, maybe you should add it to breaking changes? or update the update script to check for the file and delete it?

That is gonna be very hard to fix i guess. As it would delete the file everytime the update script is run.
If you have a idea to fix it then please let me know how.

We could check the creation age of the file if it is older then today and check the file out as a precaution. But i don't know yet if it might cause false positives in case of last modified dates.

**Comment by brunick** [comment]
i'm not sure about this, but i wouldn't search for a date as it seems a bit unreliable. i'm sure there was a similar issue a couple of years ago, where the update script stashed the changes and reapplied them afterwards.
not sure if this would work here - but i'd say a info somewhere on the repo/release page should be helping some folks, that are not thinking about searching the issues here.

**Comment by DocFraggle** [comment]
You could do something like this before pulling:
```
if [ -f data/conf/postfix/dns_blocklists.cf ]
then
  if git status -s data/conf/postfix/dns_blocklists.cf | grep "??" >/dev/null
  then
     rm -f data/conf/postfix/dns_blocklists.cf
  fi
fi
```
Untracked files are marked with ?? by 'git status -s'

```
# touch data/conf/postfix/testfile
# git status -s data/conf/postfix/testfile
?? data/conf/postfix/testfile
```
