### ISSUE TITLE
Can not disable or remove some DNSBLs from postscreen_dnsbl_sites

### ISSUE THREAD

**Issue by sriccio** [mailcow/mailcow-dockerized#5355]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Some changes were made recently to the postfix configuration about DNSBls and they are kinda forced into the postfix config.

I guess some people don't want all of these DNSBLs to be used or even, none at all at the postcreen level, as one could want to let rspamd rbl module to handle this (it can for example help training SPAM/HAM).

My original thought was that we could possibly do this by overriding the `postscreen_dnsbl_sites` in `extra.cf`, but I had not much success doing it.

Actually the `main.cf` merging order seems to place the content of `extra.cf` BEFORE the postscreen dnsbl stuff, so no way to overrid it in `extra.cf` 😢  IMHO it should be reversed.

EDIT: Submitted this as a bug, because I guess the merging order IS a bug :)
EDIT2: Submitted a PR for merging order change - https://github.com/mailcow/mailcow-dockerized/pull/5356

### Logs:

```plain text
Not relevant
```

### Steps to reproduce:

```plain text
Not relevant
```

### Which branch are you using?

master

### Operating System:

Debian 12

### Server/VM specifications:

32G, 16 cores

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

KVM (proxmox)

### Docker version:

24.0.5

### docker-compose version or docker compose version:

v24.0.5

### mailcow version:

2023-07a

### Reverse proxy:

None (yet)

### Logs of git diff:

```plain text
Not relevant
```

### Logs of iptables -L -vn:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn:

```plain text
Not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Not relevant
```

### DNS check:

```plain text
Not relevant
```

**Comment by Shargann** [comment]
Don't you're supposed to change Postfix RBL's in `data/conf/postfix/dns_blocklists.cf`?

**Comment by sriccio** [comment]
I think that it is not a problem anymore, since the whole DNSBL config thing has been reworked a few days ago.
