### ISSUE TITLE
Ist dass wichtig? - Url not Ip

### ISSUE THREAD

**Issue by kxmoAPI** [mailcow/mailcow-dockerized#537]
Ist dass wichtig? ` * Login to https://mail.*******.net (pease use the full URL and not your IP address)`
MfG

**Comment by tbsbckr** [comment]
Man sollte sich immer über die FQDN am Server anmelden damit alle Konfigurationen passen. Meldet man sich nur über die IP an funktionieren verschiedene Dinge wie z.B. SSL-Zertifikate und Domain-Konfigurationen nicht mehr.
tl;dr: Ja, das ist wichtig.

**Comment by Braintelligence** [comment]
@mkuron Is on a closing rampage. My mailbox is crying 😸.
Do we have a Gitter chat or something for mailcow?

**Comment by mkuron** [comment]
@Braintelligence, I‘m done for today... there are just so many issues that were either resolved but never closed or where the original poster never followed up. We don‘t have a chat, but prefer to keep it all in the issue tracker.

**Comment by Braintelligence** [comment]
@mkuron Other projects tend to act rather stuck-up when the issue tracker is used for the slightest hint of smalltalk. I'd love having a place to hang out with mailcow-guys 🙁
