### ISSUE TITLE
ARM64 version not starting due to acme-mailcow Let's encrypt client

### ISSUE THREAD

**Issue by mokkin** [mailcow/mailcow-dockerized#5380]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After `docker compose up -d` all containers are starting except:
 ! acme-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                         0.0s
```

### Logs:

```plain text
mailcowdockerized-postfix-mailcow-1    | exec /docker-entrypoint.sh: exec format error
```

### Steps to reproduce:

```plain text
1. create VM with docker compose on Hetzner Cloud
2. Install mailcow
3. start containers
```

### Which branch are you using?

nightly

### Operating System:

Ubuntu 22.04

### Server/VM specifications:

2 Cores, 4 GB RAM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Hetzner Cloud

### Docker version:

23.0.3

### docker-compose version or docker compose version:

v2.17.2

### mailcow version:

2023-08

### Reverse proxy:

no

### Logs of git diff:

```plain text
no
```

### Logs of iptables -L -vn:

```plain text
no
```

### Logs of ip6tables -L -vn:

```plain text
no
```

### Logs of iptables -L -vn -t nat:

```plain text
no
```

### Logs of ip6tables -L -vn -t nat:

```plain text
no
```

### DNS check:

```plain text
Error response from daemon: Container e67764f3e851263d3380af91c5a20f4bbd304436d66e65cede4a4689aae98282 is restarting, wait until the container is running
```

**Comment by bundyland** [comment]
I had a similar problem and solved it with `./update.sh --nightly`. Hope this helps.

**Comment by mokkin** [comment]
Indeed, that helped! Thank you!

Otherwise the acme client seems to rely on the x86 image.
