### ISSUE TITLE
ARM setup fails

### ISSUE THREAD

**Issue by pfrancks** [mailcow/mailcow-dockerized#5384]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I tried to follow the instructions from the blog post:
https://mailcow.email/de/posts/2023/arm64-open-beta/

Apparanetly, selecting the nightly branch in the installation tool does not change the git branch used:


root@mail:/opt/mailcow-dockerized# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   data/assets/ssl-example/cert.pem
        modified:   data/assets/ssl-example/key.pem

no changes added to commit (use "git add" and/or "git commit -a")
```
```


### Logs:

```plain text
root@mail:/opt# git clone https://github.com/mailcow/mailcow-dockerized
Cloning into 'mailcow-dockerized'...
remote: Enumerating objects: 48389, done.
remote: Counting objects: 100% (1757/1757), done.
remote: Compressing objects: 100% (750/750), done.
remote: Total 48389 (delta 1167), reused 1509 (delta 995), pack-reused 46632
Receiving objects: 100% (48389/48389), 43.74 MiB | 29.18 MiB/s, done.
Resolving deltas: 100% (31673/31673), done.

root@mail:~# cd /opt/mailcow-dockerized/

root@mail:/opt/mailcow-dockerized# ./generate_config.sh
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You´ll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: mail.mydomain.tld
Timezone [Etc/UTC]:
Which branch of mailcow do you want to use?

Available Branches:
- master branch (stable updates) | default, recommended [1]
- nightly branch (unstable updates, testing) | not-production ready [2]
Choose the Branch with it´s number [1/2] 2
Your branch is up to date with 'origin/master'.
Generating snake-oil certificate...
[REMOVED OUTPUT]
Copying snake-oil certificate...
Detecting if your IP is listed on Spamhaus Bad ASN List...
Check completed! Your IP is clean

root@mail:/opt/mailcow-dockerized# nano mailcow.conf # Changed SKIP_SOGO=y

root@mail:/opt/mailcow-dockerized# docker compose pull
[REMOVED OUTPUT]

root@mail:/opt/mailcow-dockerized# docker compose up -d
 ✔ Container mailcowdockerized-redis-mailcow-1                                                                                                                      Started1.2s
 ✔ Container mailcowdockerized-unbound-mailcow-1                                                                                                                    Started1.9s
 ✔ Container mailcowdockerized-dockerapi-mailcow-1                                                                                                                  Started1.1s
 ✔ Container mailcowdockerized-olefy-mailcow-1                                                                                                                      Started1.5s
 ✔ Container mailcowdockerized-memcached-mailcow-1                                                                                                                  Started1.2s
 ✔ Container mailcowdockerized-solr-mailcow-1                                                                                                                       Started1.1s
 ✔ Container mailcowdockerized-watchdog-mailcow-1                                                                                                                   Started1.8s
 ✔ Container mailcowdockerized-sogo-mailcow-1                                                                                                                       Started1.4s
 ! solr-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested            0.0s
 ! watchdog-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested        0.0s
 ! unbound-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested         0.0s
 ! dockerapi-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested       0.0s
 ✔ Container mailcowdockerized-php-fpm-mailcow-1                                                                                                                    Started1.7s
 ! olefy-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           0.0s
 ✔ Container mailcowdockerized-clamd-mailcow-1                                                                                                                      Started3.1s
 ✔ Container mailcowdockerized-mysql-mailcow-1                                                                                                                      Started2.6s
 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested            0.0s
 ! clamd-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested           0.0s
 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested         0.0s
 ✔ Container mailcowdockerized-nginx-mailcow-1                                                                                                                      Started3.7s
 ✔ Container mailcowdockerized-postfix-mailcow-1                                                                                                                    Started4.7s
 ✔ Container mailcowdockerized-dovecot-mailcow-1                                                                                                                    Started4.8s
 ! dovecot-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested         0.0s
 ✔ Container mailcowdockerized-rspamd-mailcow-1                                                                                                                     Started6.1s
 ✔ Container mailcowdockerized-ofelia-mailcow-1                                                                                                                     Started5.9s
 ! postfix-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested         0.0s
 ✔ Container mailcowdockerized-netfilter-mailcow-1                                                                                                                  Started5.2s
 ✔ Container mailcowdockerized-acme-mailcow-1                                                                                                                       Started5.2s
 ! rspamd-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested          0.0s
 ! netfilter-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested       0.0s
 ! acme-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested            0.0s
 ✔ Container mailcowdockerized-ipv6nat-mailcow-1                                                                                                                    Started6.3s
```

### Steps to reproduce:

```plain text
see under logs.
```

### Which branch are you using?

master

### Operating System:

Debian 12

### Server/VM specifications:

8 GB, 4 cores, Hetzner CAX21

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

Hetzner cloud

### Docker version:

24.0.5

### docker-compose version or docker compose version:

v2.20.2

### mailcow version:

2023-08

### Reverse proxy:

none

### Logs of git diff:

```plain text
no changes
```

### Logs of iptables -L -vn:

```plain text
not relevant
```

### Logs of ip6tables -L -vn:

```plain text
not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
not relevant
```

### DNS check:

```plain text
not relevant
```

**Comment by pfrancks** [comment]
If I manually switch to the nightly branch with git checkout nightly, everything works.

**Comment by l0tzi** [comment]
same here. running `generate_config.sh` isn't enough, I had to manually switch to the nightly branch. I think it's best to update the blogpost.

**Comment by Ascar699** [comment]
I am trying to deploy and test on Oracle Cloud (Ampere instance).
When I clone and install from the main branch (Nightly) half of containers restart every like 20-30 seconds rendering the whole system unusable. 

When I try cloning from the ARM64 branch with 
`git clone https://github.com/mailcow/mailcow-dockerized -b /feat/arm64-cow` 
I get error
```
Cloning into 'mailcow-dockerized'...
fatal: Remote branch /feat/arm64-cow not found in upstream origin
```
Is this temporary?
Anyone knows what ARM processors are used in Hertzner?

Thanks

**Comment by Ascar699** [comment]
> same here. running `generate_config.sh` isn't enough, I had to manually switch to the nightly branch. I think it's best to update the blogpost.

@I0tzi Can you tell me how to change the branch manually?  Thanks

**Comment by 2nistechworld** [comment]
> > same here. running `generate_config.sh` isn't enough, I had to manually switch to the nightly branch. I think it's best to update the blogpost.
> 
> @I0tzi Can you tell me how to change the branch manually? Thanks

git clone -b nightly https://github.com/mailcow/mailcow-dockerized

**Comment by Ascar699** [comment]
> > > same here. running `generate_config.sh` isn't enough, I had to manually switch to the nightly branch. I think it's best to update the blogpost.
> > 
> > 
> > @I0tzi Can you tell me how to change the branch manually? Thanks
> 
> git clone -b nightly https://github.com/mailcow/mailcow-dockerized

@l0tzi 
Hm, why may I be getting this error message?  Thanks in advance

```
Cloning into 'mailcow-dockerized'...
fatal: Remote branch remotes/origin/nightly not found in upstream origin
```

**Comment by heseifert** [comment]
use 
`git checkout nightly`
inside  /opt/mailcow-dockerized and than update the setup with ./update.sh

**Comment by ptC7H12** [comment]
> use `git checkout nightly` inside /opt/mailcow-dockerized and than update the setup with ./update.sh

This worked to set up the container, while trying to set it up like mentioned here: [https://mailcow.email/posts/2023/arm64-open-beta/](url) didn't work (most container were restarting)

**Comment by Coven82** [comment]
Hi, I installed Mailcow today on a Hetzner ARM VM according to the instructions. Some Docker containers use AMD64 architecture instead of ARM64. Is this a known problem?

sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by MAGICCC** [comment]
Are you sure you are using the nightly branch?
The tag used in nightly for the sogo image have arm64 support: https://hub.docker.com/layers/mailcow/sogo/nightly-1.119/images/sha256-19d0e1c8b7fbac87c7e6a272acf2b1ad3285d071c5abbf8fcf9aa76a0b81d7b6?context=explore

Or am I missing something here? If yes, we can repush it

**Comment by Coven82** [comment]
Hi, thank you for the quick feedback. Yes, I am using the nightly branch. Most containers are for ARM64 but not this one.

✔ Network mailcowdockerized_mailcow-network                                                                                                                   Created                                                                   0.2s 
 ✔ Container mailcowdockerized-redis-mailcow-1                                                                                                                 Started                                                                   0.0s 
 ✔ Container mailcowdockerized-sogo-mailcow-1                                                                                                                  Started                                                                   0.1s 
 ✔ Container mailcowdockerized-memcached-mailcow-1                                                                                                             Started                                                                   0.1s 
 ✔ Container mailcowdockerized-solr-mailcow-1                                                                                                                  Started                                                                   0.0s 
 ✔ Container mailcowdockerized-olefy-mailcow-1                                                                                                                 Started                                                                   0.1s 
 ✔ Container mailcowdockerized-dockerapi-mailcow-1                                                                                                             Started                                                                   0.1s 
 ✔ Container mailcowdockerized-unbound-mailcow-1                                                                                                               Started                                                                   0.1s 
 ✔ Container mailcowdockerized-watchdog-mailcow-1                                                                                                              Started                                                                   0.1s 
 ✔ Container mailcowdockerized-php-fpm-mailcow-1                                                                                                               Started                                                                   0.0s 
 ✔ Container mailcowdockerized-clamd-mailcow-1                                                                                                                 Started                                                                   0.0s 
 ✔ Container mailcowdockerized-mysql-mailcow-1                                                                                                                 Started                                                                   0.0s 
 ! sogo-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                           0.0s 
 ✔ Container mailcowdockerized-nginx-mailcow-1                                                                                                                 Started                                                                   0.0s 
 ✔ Container mailcowdockerized-dovecot-mailcow-1                                                                                                               Started                                                                   0.1s 
 ✔ Container mailcowdockerized-postfix-mailcow-1                                                                                                               Started                                                                   0.0s 
 ✔ Container mailcowdockerized-acme-mailcow-1                                                                                                                  Started                                                                   0.1s 
 ✔ Container mailcowdockerized-rspamd-mailcow-1                                                                                                                Started                                                                   0.0s 
 ✔ Container mailcowdockerized-ofelia-mailcow-1                                                                                                                Started                                                                   0.0s 
 ✔ Container mailcowdockerized-netfilter-mailcow-1                                                                                                             Started                                                                   0.0s

**Comment by EmPiFree** [comment]
I am also on the nightly build. For me those images cant be started:

 ! watchdog-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ! postfix-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ! acme-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by ptC7H12** [comment]
When I pulled the nightly 3 weeks ago, all worked!
https://github.com/mailcow/mailcow-dockerized/issues/5384#issuecomment-1725401414

**Comment by EmPiFree** [comment]
Works now with the latest commit 45717ccdfa8995d5eeea4bc8794cb023e4401c4c
The images are now pulled correctly and every container starts up.

Thanks @DerLinkman :)

**Comment by DerLinkman** [comment]
Yes i've updated it as it would collide with the current staging images.

Still no ETA! So please don't get to excited.

**Comment by ptC7H12** [comment]
@DerLinkman I tried to update  my Mailcow Server and did a docker comose pull.
But now I'm getting this errors:

✔ Container mailcowdockerized-redis-mailcow-1                                                                                                                     Started0.1s
 ✔ Container mailcowdockerized-solr-mailcow-1                                                                                                                      Started0.1s -mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s
 ✔ Container mailcowdockerized-memcached-mailcow-1                                                                                                                 Started0.1s fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
 ✔ Container mailcowdockerized-sogo-mailcow-1                                                                                                                      Started0.1s
 ✔ Container mailcowdockerized-unbound-mailcow-1                                                                                                                   Started0.1s
 ✔ Container mailcowdockerized-dockerapi-mailcow-1                                                                                                                 Started0.1s
 ✔ Container mailcowdockerized-olefy-mailcow-1                                                                                                                     Started0.1s
 ✔ Container mailcowdockerized-watchdog-mailcow-1                                                                                                                  Started0.1s
 ! watchdog-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s  ✔ Container mailcowdockerized-php-fpm-mailcow-1                                                                                                                   Started0.1s fix-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
 ✔ Container mailcowdockerized-clamd-mailcow-1                                                                                                                     Started0.1s
 ✔ Container mailcowdockerized-mysql-mailcow-1                                                                                                                     Started0.1s -mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s
 ! clamd-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested    0.0s
 ! php-fpm-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
 ✔ Container mailcowdockerized-nginx-mailcow-1                                                                                                                     Started0.0s
 ✔ Container mailcowdockerized-postfix-mailcow-1                                                                                                                   Started0.0s
 ✔ Container mailcowdockerized-dovecot-mailcow-1                                                                                                                   Started0.0s
 ✔ Container mailcowdockerized-ofelia-mailcow-1                                                                                                                    Started0.1s
 ✔ Container mailcowdockerized-rspamd-mailcow-1                                                                                                                    Started0.1s
 ✔ Container mailcowdockerized-acme-mailcow-1                                                                                                                      Started0.1s
 ! postfix-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
 ✔ Container mailcowdockerized-netfilter-mailcow-1                                                                                                                 Started0.1s
 ! rspamd-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s
 ! acme-mailcow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s
