### ISSUE TITLE
4.7.1 Ratelimit "user" exceeded

### ISSUE THREAD

**Issue by Yaknar** [mailcow/mailcow-dockerized#539]
Hallo,

wir versenden über einen Foren Account einiges an Mail und bekommen deshalb oft die Fehlermeldung:
4.7.1 Ratelimit "user" exceeded

Ich habe gesehen das man die Limits hier anpassen kann:
mailcow-dockerized/data/conf/rspamd/local.d/ratelimit.co

Aber ist es auch möglich diese Änderung nur für den einen Benutzer vorzunehmen?
Oder wie wäre hier das vorgehen und ist es auch über die Weboberfläche möglich?
Reicht es den Spam Filter für die IP zu deaktivieren?

**Comment by ghost** [comment]
Hallo Yaknar,

Ich hatte das selbe Problem nur IP-basiert daher kann ich es nicht genausagen wie es bei benutzern ist aber hier mal mein Versuch.
Das Whitelisten eines Accounts sollte über "whitelisted_user" in der von dir genannten Datei funktionieren.
Der Aufbau ist wie bei dem Standard-Eintrag whitelisted_rcpts = "postmaster,mailer-daemon"; .
Hier der Link zur offiziellen Dokumentation https://rspamd.com/doc/modules/ratelimit.html

**Comment by Yaknar** [comment]
Das hat geklappt danke :)
