### ISSUE TITLE
Change solr base image to alpine

### ISSUE THREAD

**Issue by seidler2547** [mailcow/mailcow-dockerized#5393]
### Summary

I want to suggest to change the solr-mailcow base image  from `solr:7.7-slim` to `solr:7.7-alpine`. That would actually simplify the Dockerfile to:
```
FROM solr:7.7-alpine

USER root

COPY solr.sh /
COPY solr-config-7.7.0.xml /
COPY solr-schema-7.7.0.xml /

RUN apk update && apk upgrade && apk add --no-cache \
  tzdata \
  bash \
  zip \
  && chmod +x /solr.sh \
  && sync \
  && bash /solr.sh --bootstrap
  
RUN zip -q -d /opt/solr/server/lib/ext/log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class

RUN apk del zip

CMD ["/solr.sh"]
```
because gosu is already contained in this image.

### Motivation

Apart from the simpler Dockerfile and probably smaller image, the most important reason for me is that the `-slim` Debian-based image cannot be run in unprivileged LXC. The error is `failed to register layer: unlinkat /tmp/gnupg_home/crls.d: invalid argument` when pulling or building the docker image. It is a commonly known error when running this combination.

### Additional context

Even though running docker in LXC might sound like a strange idea, it is a common use case for VPS providers that provide VMs without subvirtualization support. Management software like Proxmox can still be used very well on these VPS by using LXC to separate environments.

**Comment by DerLinkman** [comment]
Hey there,

mailcow is not supported on LXC at all though!
But if you have ideas on how to make it compatible feel free to do so.

As we are planning to remove solr soon anyways i think it won't be necessary to change it now.

**Comment by DomiStyle** [comment]
In case anyone comes here from their favorite search engine, in order to get mailcow to start inside of an unprivileged LXC (without solr):

Add a `docker-compose.override.yml` in the mailcow root directory with the following content:

```
version: '2.1'

services:
  solr-mailcow:
    image: alpine:3.18
    command: sleep infinity
  redis-mailcow:
    sysctls: !reset []
```

Make sure `net.core.somaxconn` is set to 4096 or more on the host like the docker-compose requests.
