### ISSUE TITLE
Please provide a way to use a remote MySQL server

### ISSUE THREAD

**Issue by yvan-algoo** [mailcow/mailcow-dockerized#5395]
### Summary

I would like use a remote Mariadb server instead of the one bundled in mailcow. By default, all services seem to connect through the “mysql socket” Docker volume. Is there a way to specify a remote MySQL, better than manually changing the database path in every configuration file of all other containers?

Also, why does the Mariadb container listen by default on port 13306 on the host?

Regards,
Yvan

### Motivation

Using another server for the database enable the use of appropriate hardware like SSD/NVMe, useful for this type of workload.

**Comment by yvan-algoo** [comment]
This seems a duplicate of #1774

**Comment by MAGICCC** [comment]
Yes indeed, mailcow is a complete package with everything, own mysql would be a hell to support
