### ISSUE TITLE
cidr_map support for Postfix

### ISSUE THREAD

**Issue by bcdoglet** [mailcow/mailcow-dockerized#5396]
### Summary

Postfix supports cidr_map files that can be used for smtpd_client_restrictions and so forth. It would be useful to have access to this type of map file for spam/phishing abatement, as well as site policy enforcement.

### Motivation

I currently maintain several lists of IPs/netblocks that I would like to use with mailcow. I'm not looking to firewall off the bad actors (so using fail2ban doesn't seem like the right approach), but rather reject the mail with a message (55x).

One example of a use case is a list I have created in response to a harassment campaign with email messages proxied through mobile devices. It would be useful to be able to express to valid users in those netblocks who also happen to send email to the domain that their messages can't be delivered, rather than just hanging up the connection or not responding.

### Additional context

Thank you!

**Comment by MAGICCC** [comment]
Not sure but can't you just add the files to the extra.cf?

**Comment by bcdoglet** [comment]
Yep -- I hadn't run across that yet, but that looks like the right thing.

I tried to include a link to the relevant docs for future readers, but GH wouldn't let me post it -- "You can't comment at this time". Instead, to find it, go do docs dot mailcow dot email, and in the left navigation column select Manuals/Guides/Examples | Postfix | Customize/Expand main.cf.

Thank you!
