### ISSUE TITLE
Strange NGINX log after container unhealthy

### ISSUE THREAD

**Issue by nlubello** [mailcow/mailcow-dockerized#540]
I have a lot of this row in my STDERR logs:

2017/08/29 12:46:12 [error] 9#9: *189 no "charset_map" between the charsets "iso-8859-1" and "utf-8" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: abc.company.it, request: "PROPPATCH /SOGo/dav/andrea%company.it/Calendar/ HTTP/1.1", upstream: "http://172.22.1.252:20000/SOGo/dav/andrea%company.it/Calendar/", host: "abc.company.it"

And it's every 30 seconds from 3 of 5 users of that domain.

How can I fix it?
Anybody with the same issue?

**Comment by djmaze** [comment]
@nlubello Having the same problem. Can you tell what was the reason in your case? Was it fixed?

**Comment by nlubello** [comment]
@djmaze unfortunately many things has changed, we moved to another VPS and the user changed Mobile and Laptop, after that no more log entries like this appeared AFAIK.
I'm sorry I can't help you further
