### ISSUE TITLE
user sync of keycloak IDP crashes

### ISSUE THREAD

**Issue by tja-X** [mailcow/mailcow-dockerized#5408]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
we configured a keycloak/ldap IDP and activated "Periodic Full Sync" and "Import Users".
nothing gets imported and the logs (see below) will throw a fatal every few minutes.
```

### Logs:

```plain text
mailcowdockerized-ofelia-mailcow-1     | 2023-09-04T07:39:49.574+02:00  common.go:125 ▶ NOTICE [Job "phpfpm_keycloak_sync" (5d7e1d235c62)] StdOut: 
mailcowdockerized-ofelia-mailcow-1     | Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /crons/keycloak-sync.php:158
mailcowdockerized-ofelia-mailcow-1     | Stack trace:
mailcowdockerized-ofelia-mailcow-1     | #0 {main}
mailcowdockerized-ofelia-mailcow-1     |   thrown in /crons/keycloak-sync.php on line 158
mailcowdockerized-ofelia-mailcow-1     | 2023-09-04T07:39:49.574+02:00  common.go:125 ▶ NOTICE [Job "phpfpm_keycloak_sync" (5d7e1d235c62)] Finished in "571.07256ms", failed: false, skipped: false, error: none
```

### Steps to reproduce:

```plain text
configure an keycloak/LDAP IDP
acitivate "Periodic Full Sync" and "Import Users"
```

### Which branch are you using?

nightly

### Operating System:

Debian GNU/Linux 12

### Server/VM specifications:

8GB / 2 cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.5

### docker-compose version or docker compose version:

v2.20.2

### mailcow version:

2023-08

### Reverse proxy:

--

### Logs of git diff:

```plain text
--
```

### Logs of iptables -L -vn:

```plain text
--
```

### Logs of ip6tables -L -vn:

```plain text
--
```

### Logs of iptables -L -vn -t nat:

```plain text
--
```

### Logs of ip6tables -L -vn -t nat:

```plain text
--
```

### DNS check:

```plain text
--
```

**Comment by FreddleSpl0it** [comment]
The crash should be fixed, but I think the main problem in your case is that some users have attributes in Keycloak but no `mailcow_template` attribute
