### ISSUE TITLE
Mail sometimes gets refused 

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#541]
Hi, can someone explain this:

( a real log, but anonymized hostnames, company names and some IPs)
````
8/30/2017, 9:55:53 AM	info	disconnect from mail-it0-f46.google.com[209.85.214.46] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
8/30/2017, 9:55:53 AM	info	2FC185E4155: removed
8/30/2017, 9:55:53 AM	info	2FC185E4155: to=<myself@mysupercoolcompany.com>, relay=dovecot[172.22.1.6]:24, delay=0.72, delays=0.65/0.01/0.01/0.06, dsn=2.0.0, status=sent (250 2.0.0 <myself@mysupercoolcompany.com> yLiOMYlvpllXdQAAprHitA Saved)
8/30/2017, 9:55:53 AM	info	2FC185E4155: from=<mypersonalemailaddress@gmail.com>, size=2591, nrcpt=1 (queue active)
8/30/2017, 9:55:53 AM	info	2FC185E4155: message-id=<DDD7uUX=5yJUD7jea3-ZTf32+mYjQg1h56s0TTZ0n0_MDFsreDD@mail.gmail.com>
8/30/2017, 9:55:53 AM	info	2FC185E4155: client=mail-it0-f46.google.com[209.85.214.46]
8/30/2017, 9:55:52 AM	info	Anonymous TLS connection established from mail-it0-f46.google.com[209.85.214.46]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
8/30/2017, 9:55:52 AM	info	connect from mail-it0-f46.google.com[209.85.214.46]
8/30/2017, 9:55:52 AM	info	WHITELISTED [209.85.214.46]:37766
8/30/2017, 9:55:52 AM	info	CONNECT from [209.85.214.46]:37766 to [172.22.1.2]:25
8/30/2017, 9:54:05 AM	info	disconnect from mail112.example.net[13.33.33.37] ehlo=2 starttls=1 mail=1 rcpt=0/1 quit=1 commands=5/6
8/30/2017, 9:54:00 AM	info	NOQUEUE: reject: RCPT from mail112.example.net[13.33.33.37]: 550 5.1.0 <other.user@example.com>: Sender address rejected: User unknown in virtual mailbox table; from=<other.user@example.com> to=<myself@mysupercoolcompany.com> proto=ESMTP helo=<mail112.example.net>
8/30/2017, 9:54:00 AM	info	Anonymous TLS connection established from mail112.example.net[13.33.33.37]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
8/30/2017, 9:54:00 AM	info	connect from mail112.example.net[13.33.33.37]
8/30/2017, 9:54:00 AM	info	PASS NEW [13.33.33.37]:64107
```` 

Can someone explain why sending to myself@mysupercoolcompany.com fails from Company example, but succeeds when I send from gmail.com?? 
It's literally less then 2 minutes later and I didn't change anything.

**Comment by chriscroome** [comment]
I can't explain it but I have seen something like this, or perhaps exactly the same thing, happen when sending from `oneaccount@example.org` to `anotheraccount@example.org`, getting a error like *"User unknown in virtual mailbox table"* then retrying a moment later and the email is sent without a problem. If it happens again I'll look at the logs and try to provide more details.

**Comment by ChessSpider** [comment]
Hi,

This is not acceptable for me, as we're using it in a corporate environment. I will see if I can reproduce this problem consistently. 

Uhm, what logs or debugging should i check/enable when this happens again?

**Comment by roswitina** [comment]
That's very little information about your configuration.
One option could be in the following RFC [https://tools.ietf.org/html/rfc2606](url)
But that's just crystal ball reading........

Rosi

**Comment by ChessSpider** [comment]
Hi thx for respond. 
I understand it is very little to go on but I don't know what to look for/what to give. 

It is a non-forwarded domain using the default postfix settings as they come with Mailcow. 

I'm interested to hear what I should change so i can provide all of us with more information

**Comment by ChessSpider** [comment]
It seems I can persistently reproduce the error with the company ('example.net'). And I can ask a co-worker at that company at any time to send me an email for testing, so someone please let me know what to do 👍

**Comment by ChessSpider** [comment]
hmm, i think it was due to misconfiguration on my end -- in previous tests I actually added example.net as a domain to Mailcow. That caused the fail to check. It just hit me the Postfix error is with the sender 

```Sender address rejected: User unknown in virtual mailbox table```
