### ISSUE TITLE
SOGo redirects to local hostname if NGINX reverse Proxy has QUIC/HTTP3 enabeld

### ISSUE THREAD

**Issue by schleyk** [mailcow/mailcow-dockerized#5411]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
If running nginx/1.25.2 as reverse Proxy for Mailcow with QUIC/HTTP3 enabeld.
SOGo redirects you to internal sogo Container Name after Login.
If disable QUIC/HTTP3 no issue on redirects present.

Reverse proxy settings were taken from wiki:
https://docs.mailcow.email/post_installation/reverse-proxy/r_p/
```

### Logs:

```plain text
Browser DevConsole Network:
https://mail.example.org/SOGo/mail@example.org/view -> 302 -> https:///SOGo/so/mail@example.org/Mail
```

### Steps to reproduce:

```plain text
# NGINX reverse Proxy Configuration

server {
        server_name autodiscover.example.org mail.example.org;
        listen 443 quic;
        listen 443 ssl;
        listen [::]:443 quic;
        listen [::]:443 ssl;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
        ssl_certificate /demo/server.crt;
        ssl_certificate_key /demo/server.key;
	
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM";
        ssl_ecdh_curve secp384r1;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Alt-Svc 'h3=":443"; ma=86400';

  location /Microsoft-Server-ActiveSync {
    proxy_pass https://10.0.3.25/Microsoft-Server-ActiveSync;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 75;
    proxy_send_timeout 3650;
    proxy_read_timeout 3650;
    proxy_buffers 64 512k; # Needed since the 2022-04 Update for SOGo
    client_body_buffer_size 512k;
    client_max_body_size 0;
  }

  location / {
    proxy_pass https://10.0.3.25/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 0;
  # The following Proxy Buffers has to be set if you want to use SOGo after the 2022-04 (April 2022) Update
  # Otherwise a Login will fail like this: https://github.com/mailcow/mailcow-dockerized/issues/4537
    proxy_buffer_size 128k;
    proxy_buffers 64 512k;
    proxy_busy_buffers_size 512k;
  }
}
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

8 GB / 4 vCores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

VMware

### Docker version:

24.0.5

### docker-compose version or docker compose version:

v2.10.2

### mailcow version:

2023-08

### Reverse proxy:

NGINX

### Logs of git diff:

```plain text
no
```

### Logs of iptables -L -vn:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn:

```plain text
Not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
Not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Not relevant
```

### DNS check:

```plain text
Not relevant
```

**Comment by bersierj** [comment]
I have found a solution. The problem is with the reuseport.
Without reuseport it works for me.
See link
https://stackoverflow.com/questions/76348128/enabling-quic-http-3-on-multiple-domains-with-nginx-1-25

**Comment by schleyk** [comment]
But I dont use "reuseport" because the other vhosts provided by this reverse Proxy.
Can you post your vhost config?

**Comment by schleyk** [comment]
I have now found the reason!
if you remove the following "proxy_set_header"  inside the NGINX location block "/" at reverse Proxy site:

proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-Proto $scheme;

**Comment by raldone01** [comment]
I replaced `proxy_set_header Host $http_host;` with `proxy_set_header Host $host;` to make it work.

See: https://trac.nginx.org/nginx/ticket/2468

**Comment by mdfahadhossain** [comment]
From `proxy_set_header Host $http_host;` to `proxy_set_header Host $host;`.
worked for me.
