### ISSUE TITLE
Size of logs in redis

### ISSUE THREAD

**Issue by VladimirBorisov** [mailcow/mailcow-dockerized#542]
Hello,

Can somebody points me to any options related with size of logs stored in redis?

Documentation (https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/) say "The Redis keys are persistent and will keep up to 5000 lines of logs for the web UI."
But executing "LRANGE POSTFIX_MAILLOG 0 -1" shows much more lines.
Also I am not able to find any option that related with this.

Is it possible to change this?

Thanks

**Comment by andryyy** [comment]
Thanks, I fixed it in dev. :-) Totally forgot about it. Need to change the docs, though. Using 10000 (or 10001) lines now.

**Comment by VladimirBorisov** [comment]
Thanks.
I made a quick test and it seems that it works not as expected. I made a full test lately to be sure.
But I found that syslog-ng documentations ( https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-redis.html ) say "Currently you can use only one command in a redis() destination".

Can you please check this.

**Comment by andryyy** [comment]
I did not even check it, lazy me...

Will fix it then.

**Comment by VladimirBorisov** [comment]
Thanks, now everything looks good.
