### ISSUE TITLE
Migration from iredmail

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#545]
Hi,
i'm migrating a business server from iredmail to mailcow. I'm not sure on how to transfer actual /var/vmail folder (that seems to have different schema) and MySQL db for email accounts. Can you give me some advice please? Do you have any guide for that?

Thanks

**Comment by chaosbunker** [comment]
Would it maybe be possible to setup mailcow-dockerized, create all mailboxes and then for each mailbox create a sync-job in mailcow and move all emails to mailcow from the old system.
after that's done you can then verify that everything is there, then change mx of the domain(s) in your dns settings and keep the sync-job running until the changes are propagated?

**Comment by cklabautermann** [comment]
I had several mailboxes migrated from a dovecot standalone box to mailcow via the following way:

  * provide doveadm-server config on both systems (source and destination):


`service doveadm {`
 ` inet_listener {`
`    port = 19998 # or whatever`
`  }`
`}`

`doveadm_password = shared-secret-on-both-sides-identical`


In mailcow dovecot.conf is located in ~mailcow-dockerized/data/conf/dovecot. 

* restart dovecot on both systems

  * sync mailbox command on mailcow box:

`cd /path/to/mailcow`
`source mailcow.conf`
`docker-compose exec dovecot-mailcow doveadm sync -u user@domain.tld tcp:<remote_ip>:19998`

Maybe this is helpful?

BR Claudio

**Comment by samuelebistoletti** [comment]
that's perfect, thank you!

**Comment by Krapulat** [comment]
@cklabautermann I get:
doveadm(xxx@yyy.com): Fatal: connect(ZZZZ:19998) failed: Interrupted system call

**Comment by pmdevita** [comment]
> @cklabautermann I get: doveadm([xxx@yyy.com](mailto:xxx@yyy.com)): Fatal: connect(ZZZZ:19998) failed: Interrupted system call

I'm getting this error as well, were you able to solve this? Prior to this, I also had to create the mailbox manually in the UI, it did not create the mailbox during the sync like I expected it to

EDIT: I ended up just resetting everyone's passwords on iRedMail to get imap access. Let me know if you do have a smoother solution though
