### ISSUE TITLE
Don‘t deliver internally when DNS record is missing

### ISSUE THREAD

**Issue by botsarenthuman** [mailcow/mailcow-dockerized#5452]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When a user is migrating on the mailcow server, an account is first created, but DNS changes may come later. While the DNS has not switched over to THIS mailcow server, mailcow should deliver the mail to the external server, not locally.
```

### Logs:

```plain text
N/A
```

### Steps to reproduce:

```plain text
Create active account locally
Send email to that address, even though the domain DNS is not pointing to this server
The email is not delivered to the proper server
```

### Which branch are you using?

master

### Operating System:

Debian

### Server/VM specifications:

8GB

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.21

### docker-compose version or docker compose version:

2.12.2

### mailcow version:

latest

### Reverse proxy:

Traefik

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by botsarenthuman** [comment]
Is there a way to have mailcow route to the other server?

**Comment by mkuron** [comment]
The problem is that Postfix always performs local delivery. To avoid that, Mailcow would need two separate Postfix instances, one for incoming and one for outgoing emails. So there is a way to do what you are asking for, it’s just not implemented. There is an old feature request for this in #630, but it was closed automatically after it wasn‘t implemented in years. Please do feel free to submit a pull request against #630 if you can implement this yourself.
