### ISSUE TITLE
Translation into Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#5457]
### Summary

Hello, I would like to translate all of mailcow into pt-br (Brazilian Portuguese). However, there is no option for pt-br in Weblate. Could you please create the language so that I can begin the translation process?

### Motivation

Language translation included for Brazilian users.

**Comment by MAGICCC** [comment]
I created a new translation for it: https://translate.mailcow.email/projects/mailcow-dockerized/translation/pt-br/
Do note that you can't validate any string just adding suggestions! There's an issue with weblate that validated strings will go in the live project even when nobody checked them. I will trust everyone that they enter valid things, but that's to avoid unnessary pushs on the main repo.

While you are on it, maybe you can also take a look into the normal portuguese translation? I assume it's almost the same?
https://translate.mailcow.email/projects/mailcow-dockerized/translation/pt-pt/

**Comment by ghost** [comment]
Thank you. I will handle the translation carefully to ensure accuracy and quality.

I understand the caution regarding validating strings and will be mindful of it. I'll be translating the content diligently and will not suggest any validations without proper review.

Additionally, I'll also take a look at the Portuguese (Portugal) translation to identify any differences and make necessary adjustments if needed. Collaboration between different Portuguese variants is crucial for a comprehensive translation.

I'll get to work on this promptly and will keep you updated on my progress.

Best regards,
Pedro Lucca S.C
