### ISSUE TITLE
Watchdog reports via clamd-mailcow

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#5462]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Since the update to "Mooctober 2023 Update Revision A" the watchdog container sends "connect to address 172.22.1.12 and port 3310: Connection refused" clamd-mailcow
```

### Logs:

```plain text
In the email I receive it says

connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
connect to address 172.22.1.12 and port 3310: Connection refused
```

### Steps to reproduce:

```plain text
1. Update to Mooctober 2023 Update Revision A
2. Start Mailcow an wait 5 Minutes
3. There is an email in my inbox from Watchdog via Clamd-mailcow "connect to address 172.22.1.12 and port 3310: Connection refused"
4. These emails now come every 10 minutes
```

### Which branch are you using?

master

### Operating System:

Ubuntu 22.04 LTS

### Server/VM specifications:

8GB RAM, 6 CORE

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

no

### Docker version:

20.10.21

### docker-compose version or docker compose version:

v2.12.2

### mailcow version:

2023-10A

### Reverse proxy:

no

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by DerLinkman** [comment]
Did you checked if clamav is running correctly?

I cannot reproduce that on any of my maschines

**Comment by ghost** [comment]
> Did you checked if clamav is running correctly?
> 
> I cannot reproduce that on any of my maschines

Yes, i checked. 
Both Containers are running.
The messages have been gone since two restarts. Weird thing

**Comment by camodebw** [comment]
I have the same Problem after updating to Mooctober 2023 Update Revision A

a reboot, hasn't fixed the Problem

watchdog-mailcow (mailcow/watchdog:1.98) is running

**Update:** with the second reboot the Notification has not longer appeared
