### ISSUE TITLE
Implement Separation of Mailcow into Backend and Frontend Components for Improved Readability, Security, and Productivity

### ISSUE THREAD

**Issue by vermium** [mailcow/mailcow-dockerized#5463]
### Summary

I believe that it is essential to restructure mailcow into two distinct components: a backend and a frontend. This separation is imperative for several reasons, including readability, security, and productivity enhancements. I'm happy to help out with contribution to this, but can't do it alone. Moreover, this separation will likely simplify the integration of Keycloak and streamline the development process.

### Motivation

I believe it's a compelling proposition to consider rewriting the backend code from PHP to languages like Rust or TypeScript, or any comparable alternatives. This shift is crucial as retaining PHP for the backend can introduce security concerns, primarily due to the excessive length of certain files. For instance, consider the file at this link: https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/functions.mailbox.inc.php, which spans an astonishing 5409 lines. This transition not only streamlines development by eliminating the need to navigate through unwieldy files but also enhances performance by leveraging a language purpose-built for backend operations.

Furthermore, the migration to a language specialized for backend development simplifies the process of adding new features to the stack. By transitioning to an API-driven architecture, the WebUI can facilitate the development of alternative user interfaces, such as those built on ReactJS or similar technologies, resulting in improved performance and flexibility.

### Additional context

To initiate this process effectively, consider commencing by launching a backend container and gradually migrating smaller features. You might even begin without implementing authentication initially, as it's primarily intended for internal use within mailcow's early development stages to expedite progress. Emphasizing the importance of transitioning the WebUI to an API-driven approach, this will significantly enhance the development process, making it more developer-friendly for performing CRUD (Create, Read, Update, Delete) operations on data. Instead of manual database searches, this approach facilitates tasks such as user deletion on a specific domain or removing users with specific tags within a given domain.

**Comment by DerLinkman** [comment]
Yeah but that won't happen any time soon. We have 1 primary dev (Freddle) and my self as a secondary operator more to say and the idea you're opened will basically rewrite all of mailcows core...

So... yeah nice idea but not in the near future due to dev resources.

**Comment by vermium** [comment]
I see! I have started a fork now based upon mailcow's source code since I really think this project is a great start point, my idea is to rewrite basicly whole source to another direction since for my usecase I need to change quite some stuff. Feel free to check into it and take inspiration and such. I wasn't able to make it a real fork on GitHub tho, due to how github limits forks permissions to do stuff, such as changing visibility, pages and stuff. Thanks for maintaining an amazing project such as mailcow!
