### ISSUE TITLE
No new build of dockerapi image in 2023_10

### ISSUE THREAD

**Issue by mstilkerich** [mailcow/mailcow-dockerized#5469]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
The main.py script of the dockerapi image was changed to fix constant occupation of the CPU. But apparently no new version of the image was published. The compose file still refers to the previous version. So the issue is still present.
```

### Logs:

```plain text
not relevant
```

### Steps to reproduce:

```plain text
Upgrade to 2023_10 / 2023_10a
```

### Which branch are you using?

master

### Operating System:

not relevant

### Server/VM specifications:

not relevant

### Is Apparmor, SELinux or similar active?

not relevant

### Virtualization technology:

not relevant

### Docker version:

not relevant

### docker-compose version or docker compose version:

not relevant

### mailcow version:

2023-10a

### Reverse proxy:

not relevant

### Logs of git diff:

```plain text
not relevant
```

### Logs of iptables -L -vn:

```plain text
not relevant
```

### Logs of ip6tables -L -vn:

```plain text
not relevant
```

### Logs of iptables -L -vn -t nat:

```plain text
not relevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
not relevant
```

### DNS check:

```plain text
not relevant
```

**Comment by DerLinkman** [comment]
Thanks for noticing!

Will update it and it will be merged within the next update.
