### ISSUE TITLE
Way to change primary DNS for SSL certificate?

### ISSUE THREAD

**Issue by tbsbckr** [mailcow/mailcow-dockerized#547]
Hi there,

I have a lot of domains on my mailcow instance and they are all having their respective DNS records for the SSL certificate. Mailcow now seems to sort these alphabetically, is there a way to change this?
Would like to have the main server FQDN as primary DNS for the cert and all others as subject alternative names

As an example:

Mailserver ist named mx01.srv.example.com
Other domains are mail.example.net and mail.example.org

Certificate should then be

Primary: mx01.srv.example.com
SAN: mail.example.net, mail.example.org

Thanks for any advice!

**Comment by mkuron** [comment]
I believe you need to edit https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh as follows to reorder the domain names and then run `docker-compose build acme-mailcow && rm -r data/assets/ssl/* && docker-compose up -d`:

```diff
@@ -126,6 +126,9 @@ while true; do
 	fi
 
 	for SAN in "${ADDITIONAL_SAN_ARR[@]}"; do
+		if [[ ${SAN} == ${MAILCOW_HOSTNAME} ]]; then
+			continue
+		fi
 		A_SAN=$(dig A ${SAN} +short | tail -n 1)
 		if [[ ! -z ${A_SAN} ]]; then
 			echo "Found A record for ${SAN}: ${A_SAN}"
@@ -141,7 +144,7 @@ while true; do
 	done
 
   # Unique elements
-	ALL_VALIDATED=($(echo ${VALIDATED_MAILCOW_HOSTNAME} ${VALIDATED_CONFIG_DOMAINS[*]} ${ADDITIONAL_VALIDATED_SAN[*]} | xargs -n1 | sort -u | xargs))
+	ALL_VALIDATED=(${VALIDATED_MAILCOW_HOSTNAME} $(echo ${VALIDATED_CONFIG_DOMAINS[*]} ${ADDITIONAL_VALIDATED_SAN[*]} | xargs -n1 | sort -u | xargs))
 	if [[ -z ${ALL_VALIDATED[*]} ]]; then
 		echo "Cannot validate hostnames, skipping Let's Encrypt..."
 		exit 0
```

Once you have checked whether this works, please submit a pull request with the changed script.

**Comment by tbsbckr** [comment]
Thanks for the code, I tested it and confirm that it is indeed working as expected!
I will submit a pull request so that this can be integrated in to the master build.

**Comment by andryyy** [comment]
Can you submit this to dev? :) Or @mkuron ?

**Comment by tbsbckr** [comment]
Done just moments ago :) @andryyy https://github.com/mailcow/mailcow-dockerized/pull/549
