### ISSUE TITLE
update.sh spits error: Unknown subcommand: get-url

### ISSUE THREAD

**Issue by JiiPee74** [mailcow/mailcow-dockerized#5473]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When I run update.sh script, I get error below in logs section.

git --version
git version 1.8.3.1
```

### Logs:

```plain text
--- Snip ---
Checking for remaining containers...
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand

The Repository currently used is not the default Mailcow Repository.
Currently Repository:
Default Repository:   https://github.com/mailcow/mailcow-dockerized
Should it be changed back to default? [y/N] y
Committing current status..
--- Snip ---
```

### Steps to reproduce:

```plain text
Happens now every time when I run update.sh. Few months ago when I made last update, all worked fine.
```

### Which branch are you using?

master

### Operating System:

CentOS Linux release 7.9.2009 (Core)

### Server/VM specifications:

4GB, 2 cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.6

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2023-10a

### Reverse proxy:

No

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
104.18.22.201
104.18.23.201
```

**Comment by SecT0uch** [comment]
See #5459

**Comment by MAGICCC** [comment]
Handled in https://github.com/mailcow/mailcow-dockerized/pull/5459
Will be available in the next release
