### ISSUE TITLE
API - Get Mailboxes - missing spam_score response

### ISSUE THREAD

**Issue by tobias992** [mailcow/mailcow-dockerized#5477]
### Summary

With "get mailboxes" it's not possible to get the actual spam_score. We only have the "update mailbox spam score" to process. It would be nice to add the spam_score as a response to the get mailboxes api request.

### Motivation

At the moment it's not possible to get the mailbox spam_score using the API. I think it's a missing feature to work nicely with the API.

**Comment by FreddleSpl0it** [comment]
I have added an extra endpoint to retrieve the spam score
PR: https://github.com/mailcow/mailcow-dockerized/pull/5482

**Comment by tobias992** [comment]
Cool, thank you. Will test in next stable release.
