### ISSUE TITLE
Delete.php error

### ISSUE THREAD

**Issue by Dad-Ju** [mailcow/mailcow-dockerized#548]
Hello,
I Have some Problems...
_Number One:_
I can`t delete User etc with the error:
**404 Not Found**
when i execute:
**https://mail.*.de/delete.php?mailbox=flexmann@*.de**
_Number Tow:_
I can`t select a Email while Creating an Mailbox or i can`t set the Space.
_Number Three:_
If a Mailbox will send an Mail (like flexmann@*.de) the error:
**cannot send message: (smtp) originator not accepted**
But if I send a mail from my Mailbox (Ju@*.de) I get no error (I create this Mailbox at first).

_sry for my bad english xD_

Thx for help if so and have a nice Day :)

**Comment by Dad-Ju** [comment]
Can anyone help me Please :)

**Comment by ChessSpider** [comment]
i wouldn't know honestly. 
Did you just recently set mailcow up or did you had it running for a while before these errors appeared?

I also noticed your [previous question](https://github.com/mailcow/mailcow-dockerized/issues/329). Are you now running mailcow-dockerized or the deprecated Mailcow?

**Comment by Dad-Ju** [comment]
I use the dockerized version an i set it up with the new jessie-backports Kernel
I didn't change anything after seting it up
I got the errors from start up

**Comment by Avalarion** [comment]
Cannot reproduce this, has to be your settings.

Did you pull the newest version with:

```
docker-compose pull && docker-compose down && docker-compose up -d
```

And tried again?

About the other problems. You are only allowed to send Emails from the specific account unless you edit this mailbox and allow the mailbox to send from other domains or mails explict.

Greetings from Bochum, Germany,

Bastian

**Comment by Dad-Ju** [comment]
I did and Nothing work i locked in the data/web Folder and there is no Delete.php file so there is the Problem number one an 2 i dont know why ih have this Problems i can Only send mails via my First Crated Mailbox?! 

Good Wishes Ju

**Comment by Dad-Ju** [comment]
Ah Thank you ist Worked I did this 2Times and it works :)

Thank you very much
