### ISSUE TITLE
sogo

### ISSUE THREAD

**Issue by ryanflynn211** [mailcow/mailcow-dockerized#5481]
### Summary

rewrite the sogo page and make it look really nice dark theme like black or blue nad make the side bar a little nice 

### Motivation

it would make the ui look alot cleaner

**Comment by MAGICCC** [comment]
mailcow devs are not responsible for SOGo since this is managed by the Alinto team. You can ask on their bugtracker to improve the login site https://bugs.sogo.nu
For a SOGo theme you can check https://docs.mailcow.email/manual-guides/SOGo/u_e-sogo/?h=theme#apply-custom-sogo-theme
