### ISSUE TITLE
Autodiscover failed (nightly)

### ISSUE THREAD

**Issue by philippderdiedas** [mailcow/mailcow-dockerized#5490]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Autodiscover fails in latest nightly.

functions.inc.php misses check_login function called in autodiscover.php
```

### Logs:

```plain text
-
```

### Steps to reproduce:

```plain text
-
```

### Which branch are you using?

nightly

### Operating System:

-

### Server/VM specifications:

-

### Is Apparmor, SELinux or similar active?

-

### Virtualization technology:

-

### Docker version:

-

### docker-compose version or docker compose version:

-

### mailcow version:

2023-10a

### Reverse proxy:

-

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by philippderdiedas** [comment]
pasted the function from master branch, seems to work

**Comment by FreddleSpl0it** [comment]
Should be fixed https://github.com/mailcow/mailcow-dockerized/commit/db9003b0eb0a876023025321616d2cf29938d629

**Comment by philippderdiedas** [comment]
seems to work in gmail (and when using curl).
is autoconfig outlook compatible?
