### ISSUE TITLE
Domain wide footer - custom variables

### ISSUE THREAD

**Issue by t3cneo** [mailcow/mailcow-dockerized#5496]
### Summary

IMO Domain wide footer is great, beeing able to add custom variables like user's phone number or position would make it amazing!

Beeing able to grab those custom variables through the upcomming SSO feature would be a killer feature!

### Motivation

Domain wide footer would then be full featured

**Comment by VocalZero** [comment]
Would be great to have this in Mailcow for Domain Wide Footer. This would allow you to personalize even more in the footer for the specific mailbox / user.

**Comment by nils-kt** [comment]
I also require this feature, or the ability to integrate tags into the footer. This would be very useful.

**Comment by FrancescMiV** [comment]
this would be great for me too!

**Comment by 53c70r** [comment]
This ticket should be closed.

**Comment by MAGICCC** [comment]
indeed
