### ISSUE TITLE
nginx entry /ocm-provider/ in nextcloud panel shows warning

### ISSUE THREAD

**Issue by paperle** [mailcow/mailcow-dockerized#5497]
### Summary

I currently get following Warning in my Admin Panel in Nextcloud(via mailcow installed):
```
Your web server is not properly set up to resolve "/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's documentation page ↗. On Nginx those are typically the lines starting with "location ~" that need an update.
```
Documentation Page linked to the warning:
https://docs.nextcloud.com/server/27/admin_manual/installation/nginx.html

This seemed not to help for ocm-provider. Here is another poste which addresses the prob better:
https://help.nextcloud.com/t/with-nextcloud-update-not-properly-set-up-to-resolve-ocm-provider-and-ocs-provider-on-nginx-server/158528/2

Post of Laurent seems to fix the problem:
```
Hello
my config looks like yours and I managed to remove the warning message by modifying…

in your line:
location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34]).php(?:$|/) {

replace ocs-provider/ by oc[ms]-provider/

and in your line:

location ~ ^/(?:updater|ocs-provider)(?:$|/) {
try_files $uri/ =404;
index index.php;

replace ocs-provider by oc[ms]-provider

then reload nginx
sudo systemctl reload nginx.service
```

greets

### Motivation

nextcloud admin panel looks cleaner

**Comment by MAGICCC** [comment]
The current master branch have the right configs set
https://github.com/mailcow/mailcow-dockerized/blob/master/data/assets/nextcloud/nextcloud.conf

**Comment by MAGICCC** [comment]
HI @paperle 
Could you try https://github.com/mailcow/mailcow-dockerized/pull/5498? This should fix the issue

**Comment by paperle** [comment]
Hi @MAGICCC,
thanks for taking focus on that prob. Cant get it to work.....looks like there a lot of other ppl having issues on this, see nextcloud-server github:
https://github.com/nextcloud/server/issues?q=ocm-provider

Greets

**Comment by MAGICCC** [comment]
Yes I know @paperle 
Normally my changes should resolve that. Are you sure you also change the running config in data/conf/nginx/nextcloud.conf and restarted the nginx container?
