### ISSUE TITLE
change "Twitter" to "𝕏 (Twitter)" in README.md in Cowmunity Section

### ISSUE THREAD

**Issue by BandhiyaHardik** [mailcow/mailcow-dockerized#5506]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
change "Twitter" to "𝕏 (Twitter)" in README.md in Cowmunity Section.

The badge is already updated to 𝕏.

Check PR more Screenshots
```

### Logs:

```plain text
-
```

### Steps to reproduce:

```plain text
-
```

### Which branch are you using?

master

### Operating System:

Windows 10

### Server/VM specifications:

-

### Is Apparmor, SELinux or similar active?

-

### Virtualization technology:

-

### Docker version:

-

### docker-compose version or docker compose version:

-

### mailcow version:

-

### Reverse proxy:

-

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by inson1** [comment]
@BandhiyaHardik Why it isnt closed?

**Comment by BandhiyaHardik** [comment]
Sorry i forgot to close it I thought it would be automatically get closed once the PR is merged.

**Comment by inson1** [comment]
@BandhiyaHardik You would need to link it to the PR.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by BandhiyaHardik** [comment]
Oh sorry i will do it

**Comment by BandhiyaHardik** [comment]
Closed https://github.com/mailcow/mailcow-dockerized/issues/5506 as completed via https://github.com/mailcow/mailcow-dockerized/pull/5508
