### ISSUE TITLE
SoGo: Multiple reminders per event

### ISSUE THREAD

**Issue by MarcoWue** [mailcow/mailcow-dockerized#551]
I know this is not directly mailcow related, but as this is an important missing feature I still add it here:
SoGo does not allow to set more than one reminder per event in the calendar (e.g. remind 1 day, 1 hour and 10min in advance).

Probably there is a possibility to add this functionality in the future.

**Comment by stevesbrain** [comment]
~~Be better off opening a feature request over at [SOGo's Github](https://github.com/inverse-inc/sogo) :)~~

Edit: Scratch that - apparently they don't allow issues :P

**Comment by andryyy** [comment]
But they have a bug tracker: https://sogo.nu/bugs

I will close this. 👍 Don't get me wrong, it is a good idea, but I sadly cannot help with that.
