### ISSUE TITLE
Exclude certain mailboxes from Domain Wide Footer

### ISSUE THREAD

**Issue by VocalZero** [mailcow/mailcow-dockerized#5511]
### Summary

The Domain Wide Footer in Mailcow works quite well so far, but it lacks the ability to exclude certain mailboxes from it. For example, on a noreply email where emails are automatically sent out, you don't want a footer.

### Motivation

I benefit from this feature so that I can use Domain Wide Footer at my Mailcow environment without automated mailboxes (which mostly send HTML emails and don't need a footer) getting a footer attached. I'm sure there are other Mailcow users who have encountered the same problem.

**Comment by alexgn100** [comment]
Good idea!
