### ISSUE TITLE
Display UTF-8 Email Addresses in Human-Readable Format in Mailcow UI

### ISSUE THREAD

**Issue by hatsadin09** [mailcow/mailcow-dockerized#5515]
### Summary

**Description**
Current Behavior: When a domain with UTF-8 characters is added to Mailcow, the domain is displayed in its punycode (ACE) version on the domain management page (e.g., "xn--72czi1dxb.com" instead of "ทดลอง.com"). This can make domain management confusing and error-prone, as the encoded version is not easily recognizable.

**Suggested Feature**: Add a new column on the domain management page to display UTF-8 email addresses in their original, human-readable format alongside their punycode representations. This feature would enhance usability for administrators by allowing them to view and manage UTF-8 domains and addresses more intuitively.

![image](https://github.com/mailcow/mailcow-dockerized/assets/21187872/53667d5d-ebb3-475c-adfa-625b8fbc0439)

### Motivation

This feature is particularly beneficial for administrators who handle multiple domains, including those with UTF-8 characters. It will make it easier to identify and manage domains at a glance, without having to mentally convert punycode or use external tools to understand what each encoded string represents.

### Additional context

The enhancement is intended to improve the Mailcow administrative interface's usability. Displaying domains in both punycode and UTF-8 formats caters to the technical requirements of the system and the readability needs of the administrators, facilitating better domain management and a more user-friendly experience.

**Comment by AskinSavascisi** [comment]
+1

**Comment by hatsadin09** [comment]
suggest 2 more position
![image](https://github.com/mailcow/mailcow-dockerized/assets/21187872/41a7bd4c-0385-4e59-aa21-65a23c9d3419)
![image](https://github.com/mailcow/mailcow-dockerized/assets/21187872/e89a70d0-08bf-4bbf-ae64-67c05ed7d3f5)
