### ISSUE TITLE
Offline Support for Mailcow

### ISSUE THREAD

**Issue by ayman-93** [mailcow/mailcow-dockerized#5516]
### Summary

I propose the addition of a feature that allows Mailcow to operate fully in an offline environment. This includes starting up and running without requiring an active internet connection.

### Motivation

This feature would be beneficial for users who operate in environments with intermittent or no internet connectivity. It would allow for greater flexibility in how and where Mailcow can be used, and could potentially expand the user base to include those in remote or restricted network environments.

### Additional context

Currently, Mailcow works fine when it is started while the server is connected to the internet. It continues to work even after the internet is disconnected. However, if the server is restarted while it is not connected to the internet, Mailcow fails to start up properly. This suggests that Mailcow might be trying to connect to the internet during startup for certain operations. Being able to run Mailcow in a completely offline environment would be a great addition to its features.

**Comment by DerLinkman** [comment]
Sorry, your enhancement does not make any sense in my eyes. You know that mailcow is depending on several external sources such as our fuzzy store, docker hub, github, heinlein support, spamhaus the list goes on. So i don't think this is a good idea in general at all...

**Comment by INSIinc** [comment]
### 

> Sorry, your enhancement does not make any sense in my eyes. You know that mailcow is depending on several external sources such as our fuzzy store, docker hub, github, heinlein support, spamhaus the list goes on. So i don't think this is a good idea in general at all...

I spent several days deploying and debugging mailcow, only to find that it couldn't operate after migrating it into an intranet environment. Can mailcow be modified to support offline operation?

**Comment by Choppel** [comment]
There is a case were a temporary offline mode might be sensible. We have a Mailcow instance running in a Debian VM running on a Proxmox Hypervisor. At night the whole node is backed up by shutting down all VMs and restarting them (so-called "Stop mode"). If at that point no internet connection is active (for whatever reason e.g. forced disconnect by the ISP) the mailcow does not start, although minutes later the internet connection might establish on its own. This happens irregularly once per month on 1 of about 80 hosts.
