### ISSUE TITLE
The ability to sell individual mailboxes through a platform like WordPress/Woocommerce

### ISSUE THREAD

**Issue by mbh-dev** [mailcow/mailcow-dockerized#5517]
### Summary

Hi,

We have a requirement whereby we need to sell individual mailboxes through a platform like WordPress/WooCommerce on a subscription basis.

Does anyone have experience in using the Mailcow API to do this.
We have experimented with WP Email Manager, however it requires a user to create domain accounts before being able to create mailboxes.

If anyone has experience with this please could you advise.

Many thanks

### Motivation

This would help us and other to provide an alternative to the big email providers.

**Comment by awsumco** [comment]
Hi, 

You're welcome to reach out to me privately from some advice on this and yes it can be done ;)

**Comment by mbh-dev** [comment]
Hey @awsumco 

Thanks for your quick response, what's the best way to reach you

**Comment by awsumco** [comment]
Oops, I forgot GitHub has no DM capabilities "awsumco AT gmail.com" :D
