### ISSUE TITLE
Dovecot Container Memory Usage

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#552]
There appears to be an issue with the memory usage of the Dovecot container? Following is a Munin docker memory graph for the last month to illustrate this:

![Mailcow container memory usage](https://docs.webarch.net/w/images/7/72/Docker_memory-month.png)

It's not a big issue for this server as it has plenty of RAM but this could cause issues on servers with less RAM.

The drops in memory usage correspond to the container being restarted. It is also worth noting that this server isn't running the latest version of Mailcow (it is still using a bind9 container rather than unbound).

**Comment by Braintelligence** [comment]
My hunch is that the container will use RAM if RAM is available to speed up some processes. Maybe you could try and run the container with restricted amount of RAM?

**Comment by ChessSpider** [comment]
Could it maybe be that you were under attack ?

**Comment by hachre** [comment]
I've looked into this a bit and came to the conclusion that `imap-login` may be taking over the process-count limit set up for `imap` which is 1024. There's a memory limit for `imap-login` set to 64 MB in mailcow's dovecot.conf. This together with the 1024 process limit results in a 64 GB maximum possible memory usage for `imap-login` tasks. That being said 64 is the maximum, and it's more likely that most `imap-login` sessions need far less than that. 

Having been under attack seems to be the most likely case here.

**Comment by chriscroome** [comment]
Here is the latest monthly graph (I updated Mailcow this morning):

![Docker container memory usage by month](https://docs.webarch.net/w/images/f/fe/Docker_memory-month_April_2018.png)

And this is how it looks for the year:

![Docker container memory usage by year](https://docs.webarch.net/w/images/9/9a/Docker_memory-year.png)

And the graph for the server overall for this month (it has 16GB of RAM allocated overall):

![Server memory usage by month](https://docs.webarch.net/w/images/d/d1/Memory-month.png)

And for the year:

![Server memory usage by year](https://docs.webarch.net/w/images/6/60/Memory-year.png)

I still think there must be some issue causing Dovecot to use so much RAM?

**Comment by chriscroome** [comment]
Updating this issue, some weeks ago the virtual server running Mailcow was given a lot more RAM so the memory committed isn't greater than the memory available:

![Mailcow memory usage by year](https://docs.webarch.net/w/images/f/f1/Docker-Mailcow-memory-year.png)

But Dovecot is still using a lot of RAM:

![Mailcow memory usage by container by week](https://docs.webarch.net/w/images/8/89/Mailcow-docker_memory-week.png)

**Comment by chriscroome** [comment]
I realise that this is a old issue, which has been closed, but, for what it is worth, I still have no good understanding why the Dovecot container still peaks at around 19GB of RAM usage (I'm not sure why there is a gap in this graph):

![Mailcow memory usage by container](https://docs.webarch.net/w/images/8/8b/Mailcow_docker_memory-month.png)

But the two IMAP processes tracked in this graph, `imap` and `imap-login`, don't add up to that much, they peak at around 6GB of RAM:

![Mailcow memory usage by process](https://docs.webarch.net/w/images/1/1c/Docker_multips_memory-month.png)

**Comment by andryyy** [comment]
Don't know, I cannot reproduce it on any machine.

You should check the procs _inside_ the container.
