### ISSUE TITLE
Whitelist IP from any checks whatsoever.

### ISSUE THREAD

**Issue by bumbalaga** [mailcow/mailcow-dockerized#553]
Hello,

I have a couple of servers that regularly do cron jobs and they should be sending me an e-mail notification with a result of the job.

I am having problem with mailcow, as it is trying to check on domains that simply do not exist (localhost, server1, etc): Sender address rejected: Domain not found (in reply to RCPT TO command)

Is there any way i could exclude an IP from any check, to make sure it always gets delivered to the inbox?

**Comment by andryyy** [comment]
You can add the IP to mynetworks in Postfix.

**Comment by bumbalaga** [comment]
For some reason, mails have started to go through without any change. I don't know why, but i guess it's fine. Thanks for your help.
