### ISSUE TITLE
Insert image for imprint

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [mailcow/mailcow-dockerized#5543]
### Summary

I want to insert a picture with my adress which is reachable via webui for all. Which container is nessecary to modify?

### Motivation

Some mailproviders only accept your mails, when you have a imprint on your website.

**Comment by MAGICCC** [comment]
Upload your picture somewhere to the www and edit your footer with HTML code in Configuration -> Options -> Customize
