### ISSUE TITLE
Plans on integrating xmpp/jabber?

### ISSUE THREAD

**Issue by strowi** [mailcow/mailcow-dockerized#555]
Hi,

i was wondering if there are any plans on integration a xmpp-server like ejabberd into the setup?
Shouldn't be too hard getting ejabberd to auth against dovecot or mysql..?

greetings,
strowi

**Comment by mkuron** [comment]
It's nothing that would be integrated into Mailcow itself because it's not email-related at all, but if you figure out how to set it up, you can submit a tutorial for inclusion into the documentation by creating a pull request in https://github.com/mailcow/mailcow-dockerized-docs .

**Comment by andryyy** [comment]
Yes, that's the way it should be done. :)
