### ISSUE TITLE
Domain spam filter rating higher than 30

### ISSUE THREAD

**Issue by cataldoc** [mailcow/mailcow-dockerized#556]
Hello

Rspamd web interface allows to set (in the action section) higher scores for spam/reject actions.
But despite changing values there, for instance spam score to 999 to avoid rejecting messages as I have to keep everything (i need the spam to go in the junk folder, but I can't reject any email), the domain limits are still the default ones and I cannot go over 30 in mailcow ui

There's a way to tweak those values, or perhaps even better to make mailcow ui read default values from rspamd ?

Those are my settings:

**RSPAM**
![rspamd](https://user-images.githubusercontent.com/2877659/30173952-ad215dda-93f9-11e7-9227-cc7c14225b33.PNG)

<br/>

**MAILCOW**

![mailcow](https://user-images.githubusercontent.com/2877659/30173954-b11a108a-93f9-11e7-9779-aa74415788d3.PNG)

<br/><br/>
But I still get mail rejected when the score is above 30

![mailcow_log](https://user-images.githubusercontent.com/2877659/30173964-bc9e21b2-93f9-11e7-969e-b549fe7ed5e6.PNG)

**Comment by andryyy** [comment]
I updated the code to allow a score up to 2000. This happens logarithmic, so it still looks "ok":

![image](https://user-images.githubusercontent.com/2972950/30178628-ec149e48-9409-11e7-8974-ffc70335176c.png)

**Comment by mkuron** [comment]
The values set in the rspamd web interface are overridden by any user-specific values configured. So you can't do it like that, but you could in principle achieve what you're trying to do with rspamd's force_action module.

> i need the spam to go in the junk folder, but I can't reject any email

Before we try to find a technical solution to your problem, we should first discuss whether that's actually what you want... rspamd is not the only thing that might reject emails -- Postfix uses DNSBLs to determine whether an incoming connection should be rejected. And you definitely don't want to disable that as it keeps out hundreds of spam messages per hour on a typical mail server.

If you are trying to disable rejection for legal reasons or the like: that typically isn't necessary (in fact, it's not even reasonable nowadays where 80% of all email is spam). Rejection doesn't mean that an email is silently discarded. Instead, it is never accepted from the delivering mail server, resulting in an immediate error message being reported to the sender.

If you only want to exempt certain senders from filtering, you can use the per-user whitelist. If you only want to exempt certain delivering servers, you can use the admin-level "forwarding hosts" list.

**Comment by cataldoc** [comment]
Hi @andryyy , tnx for the quick fix :-)

I have been postmaster for years for the biggest ISP in my country and currently working for an ESP (moved to the dark side!!! :-P ). I am working quite closely with dnsbl and many worldwide ISP at the moment. I'm not a developer myself but I have quite good experience with email and deliverability and I am happy to help with the project if this can be useful :-)

@mkuron there are many scenarios where rejecting is not a good idea, for instance the most commons ones are postmaster and abuse desk related emails. It's a bad practice to reject those emails and actually bouncing spam reports will most probably make your mail server and domain being blacklisted.
DMARC reports and feedback loop are also on the same boat.

Also, there are emails coming from automated systems (iot, legitimate bots, payments systems, etc.) which often are not able to handle a reject event. But even when those systems are able to handle a reject event you are missing an important notification in case you reject it. 
Not to mention you can have an IP being blacklisted by mistake and start rejecting legitimate emails.

Only secure way to block using a dnsbl is to do it only if the IP is present in multiple blacklists at once. 

Here's an implementation of this method using postscreen: 

```
postscreen_access_list =
        permit_mynetworks, cidr:/etc/postfix/postscreen_access.cidr
postscreen_blacklist_action = drop
postscreen_dnsbl_action = enforce
postscreen_dnsbl_reply_map =
        pcre:$config_directory/postscreen_dnsbl_reply_map.pcre
postscreen_dnsbl_sites = zen.spamhaus.org*2
        bl.spameatingmonkey.net*2
        bl.spamcop.net
        dnsbl.sorbs.net
        psbl.surriel.com
        bl.mailspike.net
        swl.spamhaus.org*-4
        list.dnswl.org=127.[0..255].[0..255].0*-2
        list.dnswl.org=127.[0..255].[0..255].1*-3
        list.dnswl.org=127.[0..255].[0..255].[2..255]*-4
postscreen_dnsbl_threshold = 3
postscreen_greet_action = enforce
postscreen_whitelist_interfaces = XXX.XXX.XXX.XXX !XXX.XXX.XXX.XXX/XX
        !XX.XX.XX.XX/XX static:all
postscreen_dnsbl_whitelist_threshold = -1

```
An email is rejected by postfix ONLY if it's present in more than one dnsbl, unless is in a whitelist.

dnsbl are perfect for scoring, if you tag an email by mistake you can still fix it (and you have your email in the junk folder)... once you reject it it's lost forever.

**Comment by mkuron** [comment]
@cataldoc, ok, I'm glad you thought this through. It didn't sound like a good idea when you requested it, but you clearly know what you are doing.

> there are many scenarios where rejecting is not a good idea, for instance the most commons ones are postmaster and abuse desk related emails. It's a bad practice to reject those emails and actually bouncing spam reports will most probably make your mail server and domain being blacklisted.

Even there, some moderate filtering (high rejection score) may be acceptable nowadays. Abuse reports are not supposed to be sent out in an automated fashion, so there is always a sender who can deal with a rejection.

> Also, there are emails coming from automated systems (iot, legitimate bots, payments systems, etc.) which often are not able to handle a reject event.

That may be better handled by explicitly whitelisting these senders. At least that's what I do.
