### ISSUE TITLE
Newly-created users can't access to mailcow-ui after upgrading to latest version

### ISSUE THREAD

**Issue by misl6** [mailcow/mailcow-dockerized#557]
Newly-created users can't access to mailcow-ui after upgrading to latest version.
SoGo & IMAP login works well.

**Comment by andryyy** [comment]
Hm, what is the latest version? :-) There has not been an update to master in a while. But I will push some new files today. 

What happens when you reset the passwords?

**Comment by misl6** [comment]
Upgrading to current master fixed the issue.
