### ISSUE TITLE
Add a switch to ignore memory verification

### ISSUE THREAD

**Issue by sidewinder94** [mailcow/mailcow-dockerized#5572]
### Summary

Add a configuration varable to allow skipping the minimum memory check for services.
Alternatively a variable to set the memory available on the machine.

### Motivation

I run my mailcow instance in a VM with dynamic memory (allocated memory grows, and shrinks based on actual usage).

When the services start, the memory load on the VM is nonexistent and thus, the allocated memory is < 1Gb, 

When solr starts, it reads the current allocated memory of the VM. Meaning it thinks there is < 2Gb if RAM, and thus do not start,

This would allow the memory hungry services to start in those scenarios.

**Comment by MAGICCC** [comment]
Hm I don't understand, but the memory check is in the generate_config script only. Nowhere else it checks how much RAM you have

**Comment by sidewinder94** [comment]
See here :
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/solr/solr.sh#L9-L17

AFAIK this is the script that is called at the start of the solr container.

**Comment by MAGICCC** [comment]
Ah I see, I wonder why it does check there again... Maybe we could remove it from there @DerLinkman 
PS: I wish dovecot native indexer would be available...

**Comment by DerLinkman** [comment]
Won't add this as solr will be removed in 2024 anyways from mailcow.
