### ISSUE TITLE
Domain Wide Footer - Option to avoid Footer on Forwards or Answers

### ISSUE THREAD

**Issue by q16marvin** [mailcow/mailcow-dockerized#5588]
### Summary

Hi,

this new Domain Wide Footer is absolut killer feauter for use. It works near 100% as expacted. Only one last Option we missing: Is there any way to "not add" Footer if mail is answerd or forwarded mail?

### Motivation

For example if you have a "discussion" via mail with someone else and everytime footer will add if you answer the mail gots longer and longer with many "signatures" :)

**Comment by FreddleSpl0it** [comment]
Skipping the domain wide footer on reply emails was easy as I could check if an `In-Reply-To` header is set. However, for forwarding emails, it's not as straightforward. The only method I can think of is to check if the subject contains `FW:` or `FWD:` at the beginning. Not sure if this is a good approach.

**Comment by q16marvin** [comment]
ohhh thats looks awesome! thx! setting the "postition" of the footer its not possible or? So above the quote but below the answer like thunderbird?

![2018-10-08-08-49-15-e4f6a9](https://github.com/mailcow/mailcow-dockerized/assets/19844709/84bc1579-6c2c-429d-bc3a-2bd248bbc062)

**Comment by FreddleSpl0it** [comment]
i don't think this is possible. We use a built-in rspamd lua function to add the footer. We would need to extend the built-in function in order to do that

https://rspamd.com/doc/lua/lua_mime.html#fa3d82
https://github.com/rspamd/rspamd/blob/40a0a9674d7058b6b0392badeaaa74020456a1d5/lualib/lua_mime.lua#L92-L379

**Comment by MAGICCC** [comment]
https://github.com/mailcow/mailcow-dockerized/pull/5612 got merged and in https://github.com/mailcow/mailcow-dockerized/releases/tag/2024-01
