### ISSUE TITLE
Migrate mailcow to CPanel

### ISSUE THREAD

**Issue by crosskpixel** [mailcow/mailcow-dockerized#5607]
### Summary

I need migrate my mailcow dockerized to my cpanel, i searching some one that know help me solve that issue, my custoumer uses the IMAP mode. i need to migrate all mails to cpanel.

### Motivation

I need do this by customer request and i don't undertand how do that step.

### Additional context

I found some ideas in the past, but dont seems worth to me

**Comment by MAGICCC** [comment]
If CPanel do not have an integrated imapsync solution you can still use imapsync on your own.
And this is out of scope from mailcow 'support' anyway
