### ISSUE TITLE
Plus addressing (email tagging) with slash

### ISSUE THREAD

**Issue by YeapGuy** [mailcow/mailcow-dockerized#5609]
### Summary

Currently, users have to pick between putting plus addressed / tagged mail in a subfolder, or putting the tag in the subject. This is the setting I mean:
![image](https://github.com/mailcow/mailcow-dockerized/assets/43749899/8cf8f0da-6afc-4433-8ad9-709ea5dcc127)
It would be great if one could use both options. For example by putting emails 'tagged' with a slash in a subfolder, and with a plus in the subject.
`address+tag@example.com` -> would result in an email with "tag" in the subject, as if _"Set handling for tagged mail:"_ was set to _"In subject"_
`address/tag@example.com` -> would result in the email being put in subfolder "tag", as if _"Set handling for tagged mail:"_ was set to _"In subfolder"_

### Motivation

The option to put the tag _in subject_ is very useful, as for many plus addressed emails, I don't need a separate folder for them. But for some emails (such as newsletters), I'd like to put them in a separate folder.
So while it's awesome you can configure _handling for tagged mail_, I can't settle on either of the options.

### Additional context

Using plus addressing with symbols different than a plus isn't that common, but there's no issue with it. [SimpleLogin](https://simplelogin.io/) already does it for [their "Directories" feature](https://simplelogin.io/blog/alias-directory/):
![image](https://github.com/mailcow/mailcow-dockerized/assets/43749899/b4a873b6-2cd5-4772-bfa4-5cb76b0a5726)

**Comment by s-renz** [comment]
I actually looked into this a while ago, so it's fun to see this request here. 

While you can easily add other characters as tag-delimiters for dovecot and postfix by adding 

`recipient_delimiter = +/`

to the `data/conf/postfix/extra.conf` and `data/conf/dovecot/extra.cf` files for mailcow this only works when you have the option to "Do nothing" and the mails will end up at the correct recipient. 

However the actual tag filtering is done by rspamd (see https://github.com/rspamd/rspamd/blob/33d3295d80519c38aa70c34a78465925f4c8b7ff/rules/misc.lua#L519) which only checks for plus signs (as per this script: https://github.com/rspamd/rspamd/blob/master/lualib/lua_util.lua#L204).

Also you'd need to change this mailcow script, which removes the tags to get the actual recipient(s) and only applies to plus signs aswell: 

https://github.com/mailcow/mailcow-dockerized/blob/cb0b0235f01a8e4102ece9540fe0aa3bb2b60d72/data/conf/rspamd/dynmaps/aliasexp.php#L54

The extracted tags from rspamd are saved into the TAGGED_RCPT spamd symbol and are then used in a mailcow rspamd plugin to either rewrite the subject 

https://github.com/mailcow/mailcow-dockerized/blob/cb0b0235f01a8e4102ece9540fe0aa3bb2b60d72/data/conf/rspamd/lua/rspamd.local.lua#L281-L289

or set the "X-Moo-Tag" Header to "YES":

https://github.com/mailcow/mailcow-dockerized/blob/cb0b0235f01a8e4102ece9540fe0aa3bb2b60d72/data/conf/rspamd/lua/rspamd.local.lua#L259-L262

which then prompts the sieve script to sort the mail into a subfolder:
 
https://github.com/mailcow/mailcow-dockerized/blob/cb0b0235f01a8e4102ece9540fe0aa3bb2b60d72/data/conf/dovecot/global_sieve_after#L15-L25 
 
Altough dovecot actually can do this on their own, but then it wouldn't be a configurable thing I guess.

So to accomplish this feature you'd need to change how rspamd works to include other delimiters and then possibly also return the used delimiter so you can change the `rspamd.local.lua` to process mails differently based on the used delimiter.

I'm not sure if one could overwrite the core rspamd EMAIL_PLUS_ALIASES symbol function within the mailcow configuration? That would certainly help. Maybe some dev can shed a light on this as I would love this feature too.

**Comment by YeapGuy** [comment]
Why?

**Comment by DerLinkman** [comment]
You can modify it by your own, we wont support this.
