### ISSUE TITLE
Multiple containers unhealthy

### ISSUE THREAD

**Issue by oneiros66** [mailcow/mailcow-dockerized#561]
Hi,

i fresh installed the mailcow on a fresh debian 9 server.
I installed docker, docker compose as in the documentation and cloned from the git - so far so good. The docker-compose pull will run through without problems. 
But starting the cow with docker-compose up -d brings the following: 

ERROR: for dovecot-mailcow  Container "7dc06d3b3675" is unhealthy.
ERROR: for memcached-mailcow  Container "7dc06d3b3675" is unhealthy.
ERROR: for sogo-mailcow  Container "7dc06d3b3675" is unhealthy.
ERROR: for redis-mailcow  Container "7dc06d3b3675" is unhealthy.
ERROR: for postfix-mailcow  Container "7dc06d3b3675" is unhealthy.
ERROR: Encountered errors while bringing up the project.

I checked all the ports via netstat - every needed port is free. 
Also, i stopped all the docker containers, removed all docker images, re-cloned mailcow and repeatet the docker-compose pull. 
No change, also, a reinstallation of docker and docker-compose didn't help. docker system prune -a didn't and start over didn't fix the problem either.

Docker and docker-compose are running fine so far, docker version is 17.07.0-ce; docker-compose version is 2.16.1 build 6d1ac21, docker-py version 2.5.1 and cpython version 2.7.13; openssl version is openssl 1.0.1t 3 may 16.

Docker and docker-compose hello world examples work flawless, also a collabora office. 
Do you have an idea, what I'm doing wrong or what's wrong with my system?

Thanks a lot guys!

Greetings

**Comment by andryyy** [comment]
Hi,

What's getting logged in 7dc06d3b3675? => `docker logs 7dc06d3b3675`

Maybe `docker-compose down -v` (deletes all volumes!) fixes it.

Which time zone do you use?

**Comment by oneiros66** [comment]
Hi, it's returning:

Receiving anchor key...
Receiving root hints...
curl: (6) Couldn't resolve host 'www.internic.net'
[1504893783] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
[1504893783] unbound[1:0] notice: init module 0: validator
[1504893783] unbound[1:0] notice: init module 1: iterator
[1504893784] unbound[1:0] info: start of service (unbound 1.6.2).

(I executed it as root). 
I'm using Europe/Berlin.

Edit: removing volumes didn't fix it...

**Comment by carlbennett** [comment]
I suspect this might be an issue with SELinux. I had a similar issue while troubleshooting #546.

If you have SELinux, set it to permissive mode temporarily: `sudo setenforce 0` and restart mailcow. If that doesn't work, try re-creating the containers with SELinux in permissive mode.

If this succeeds, you'll need to set `SELINUX=permissive` in `/etc/selinux/config` to make it persist on reboot.

**Comment by oneiros66** [comment]
Not using SELinux, so this shouldn't be the problem... ^-^
Edit: Just pulled the containers another time today. All are coming up so far - just can't reach the webinterface...
Edit2: ERR_CONNECTION_TIMED_OUT on http and https. 
docker ps | grep nginx : ec19e35732ec   nginx:mainline-alpine       "/bin/sh -c 'envsu..."   4 minutes ago       Up 4 minutes   0.0.0.0:4444->4444/tcp, 80/tcp, 0.0.0.0:8888->8888/tcp mailcowdockerized_nginx-mailcow_1

--> nginx looks ok...
