### ISSUE TITLE
Display error in mailcow UI 'Configuration' tab

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#562]
<img width="272" alt="bildschirmfoto 2017-09-08 um 20 39 33" src="https://user-images.githubusercontent.com/11010788/30226314-dcd9e3bc-94d5-11e7-9510-961ea7af8881.png">

Please see attached file. Error appears in Safari and Chrome. Others not tested.

**Comment by ghost** [comment]
Can confirm this appears with Firefox 52.3.0.

**Comment by cwildfoerster** [comment]
Seems to have something todo with https://github.com/mailcow/mailcow-dockerized/blob/c6d461382cba82cf1459843f4af21d87f3392398/data/web/js/admin.js#L584
If you reload the page with the configuration tab already selected, the width will be correct. Maybe the JS code should be run on tab selection?

**Comment by cwildfoerster** [comment]
I just opened a PR #572
