### ISSUE TITLE
Error with NGINX container

### ISSUE THREAD

**Issue by rafix1989** [mailcow/mailcow-dockerized#563]
Hello after upgrade to newest version, my nginx container is in the restarting state.  How to repair it. 

I stop it , and start this container and nothing help me . Issue cannot allow me to access to ui.

![obraz](https://user-images.githubusercontent.com/805762/30231083-85715be6-94e9-11e7-806c-337e5330ce40.png)

**Comment by andryyy** [comment]
What does it log? `docker-compose logs nginx-mailcow`

**Comment by rafix1989** [comment]
it shows me something like this 

![obraz](https://user-images.githubusercontent.com/805762/30238791-bd17d8da-954e-11e7-85d9-f2d8b7cde4d4.png)

**Comment by rafix1989** [comment]
I repair it . Sorry for my inconvince
