### ISSUE TITLE
Multiple DKIM signing keys per domain

### ISSUE THREAD

**Issue by wege2003** [mailcow/mailcow-dockerized#5637]
### Summary

Hi together,

i just want to request the following feature:

My Domain: example.com
DKIM Keys:
 selector1._domainkey 
selector2._domainkey

Is it possible to create two DKIM keys for one Domain in mailcow. I think with postfix and opendkim should it possible or?

Can someone help me?

### Motivation

Reduancy for the DKIM Keys

**Comment by DerLinkman** [comment]
Possible (if we implement it) @dragoangel?

**Comment by dragoangel** [comment]
What a point just currios? You will always sign with only one key. Usually you just not dropping instantly old key after adding new one. We can add "switch button" to place only actual keys in redis and store them in MySQL db permanently

**Comment by DerLinkman** [comment]
Yeah you're right. I misread the issue...

**Comment by dragoangel** [comment]
@wege2003 just to clarify - you can achieve it by adding additional mail domains aka `dkim-reductancy-s1.example.com` and `dkim-reductancy-s2.example.com` (with Global Address List turned off) and adding `selector1` and `selector2` to domains accordingly. Then you can utilize `Duplicate DKIM record` to override at some point `selector1` by coping key from `dkim-reductancy-s1.example.com` to `example.com` or if you want change to `selector2` - duplicate key from `dkim-reductancy-s2.example.com` to `example.com`.

Sounds hacky? Yep, but doing what you need and without any change or harm to system.
