### ISSUE TITLE
Backups directly to S3, problem with space when more than 50% is full.

### ISSUE THREAD

**Issue by godlesowned** [mailcow/mailcow-dockerized#5638]
### Summary

Example:
Server is 70% full, it can't create backup file and then move to S3 because there will be no free disc space.

### Motivation

Free disk space of our servers.

**Comment by czssf** [comment]
S3 backup needs to be cached locally and then uploaded to the bucket in parts, you can't backup if you local disk is not enough space.

**Comment by dragoangel** [comment]
As @czssf said. Plus backups is something not regulated by mailcow, if you do not like default backup script, no problem, do it in another way.
