### ISSUE TITLE
Update script not stopping mailcow

### ISSUE THREAD

**Issue by cataldoc** [mailcow/mailcow-dockerized#564]
Hi,

the update.sh script (my last update.sh just pulled a newer version) is not stopping mailcow during the update, which makes the update process failing.

I opened the script and I saw this part commented, which may be the root cause

```
#echo -e "Stopping mailcow... "
#sleep 2
#docker-compose down

```

**Comment by andryyy** [comment]
Hi, why does it fail then?

**Comment by cataldoc** [comment]
Mhmm, sadly I don't have the output anynore since I manually stopped all containers and updated but it was hanging a bit after pulling containers and giving a strange timeout at the end of the procedure.

Sorry I can't replicate now since if I run it again it doesn't have anything to update, but I'll report back with the error (if any).

My bad, I should have collected the output (sorry, I had a n00b moment)

If the 

`docker-compose down `

is intended to be commented out then it should have been something else. I was sure it was the culprit 'cause the update script was stopping everything before the latest update.

**Comment by cataldoc** [comment]
Bah, can't replicate it anymore. You may want to close this issue, I'll get back to you when (if) it happens again.
