### ISSUE TITLE
Should ARM64/AARCH64 still be marked as WIP in debug page?

### ISSUE THREAD

**Issue by yanbreu** [mailcow/mailcow-dockerized#5644]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Currently if you check the debug page on ARM64/AArch64 systems, next to "Architecture" you get "aarch64 ⚠️" and if you hover above it, the tool tip shows "Currently Work in Progress".

Is this currently after the arm64 release still wanted or just "left behind"?

I guess its because:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/js/site/debug.js#L1297-L1299

Otherwise big thanks for supporting arm systems!
```

### Logs:

```plain text
-
```

### Steps to reproduce:

```plain text
1. Open debug page
```

### Which branch are you using?

master

### Operating System:

Rocky Linux 9

### Server/VM specifications:

8GB ram, 4 cpu

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

Hetzner Cloud

### Docker version:

24.0.7

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2024-01

### Reverse proxy:

-

### Logs of git diff:

```plain text
diff --git a/docker-compose.yml b/docker-compose.yml
index 26a0cfe1..503ae3b2 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -604,36 +604,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
172.64.155.249
104.18.32.7
```

**Comment by DerLinkman** [comment]
Yes.  Until the next 1-2 releases as small bugs still exist.

**Comment by yanbreu** [comment]
Ok. Understandable. 

Thanks for the clarification!
