### ISSUE TITLE
mailcow database not created

### ISSUE THREAD

**Issue by cwildfoerster** [mailcow/mailcow-dockerized#566]
hi, i just tested the new update on a fresh system, waited couple of minutes after `docker-compose up -d` to let everything come alive, but still get an error on login.

`Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mailcow.mailbox' doesn't exist in /web/inc/functions.inc.php:197 `

It seems that the database wasn't created as stated in the documentation after the first visit.
`The database will be initialized right after a connection to MySQL can be established.`

**Comment by andryyy** [comment]
It will be created after you first visit the UI. 
Try to delete your web cache.

**Comment by cwildfoerster** [comment]
i already tried everything, forced reload, different browser, `docker-compose down && docker-compose up -d`. the routine to create the database seems to have not run just yet

**Comment by ukozi** [comment]
Interestingly enough, I'm having this exact issue. Fresh Ubuntu 16.04 install, followed all the directions, everything went perfectly but the DB doesn't seem to be generating. I visited the website from a computer/browser that has never been to the site before (no cache) and still no dice. Do you have way of manually initiating the DB?

**Comment by ukozi** [comment]
Pulled this error out of a web inspector:     `mailcow_alert_box("Database initialisation failed: SQLSTATE[HY000]: General error: 1005 Can't create table `mailcow`.`user_acl` (errno: 150 "Foreign key constraint is incorrectly formed")",  "danger");
`

**Comment by mkuron** [comment]
Then it's a bug in https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/init_db.inc.php . The _user_acl_ table is the only one that has a foreign key, so likely the code that creates foreign keys has a bug somewhere.

**Comment by ukozi** [comment]
I agree. I'm not a mySQL expert, so I was just pouring through some SE posts about it.

**Comment by henry-spanka** [comment]
+1

**Comment by andryyy** [comment]
Will fix it in a few minutes.

**Comment by andryyy** [comment]
Damn. All new installations, right? Should be fixed. The user_acl table was created before the mailbox table.

Should not have happened when upgrading, since the table mailbox already exists.

**Comment by henry-spanka** [comment]
@andryyy thank you very much. The issue is now fixed and migration does complete successfully.

**Comment by cwildfoerster** [comment]
Can confirm that it worked after running the update script. Upon first visit, the message `Database initialisation completed` was also shown.

**Comment by henry-spanka** [comment]
Fixed by 3ab6fc2

**Comment by aquac** [comment]
I guess I have a similar problem like this.
The main problem could be that I cannot visit the main page "https://mail.example.com" as it gives 404. However, "https://mail.example.com/SOGo" works fine.

When running `# docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}`
I only see:

> MariaDB [mailcow]> show tables;
> +------------------------+
> | Tables_in_mailcow      |
> +------------------------+
> | sogo_acl               |
> | sogo_cache_folder      |
> | sogo_folder_info       |
> | sogo_quick_appointment |
> | sogo_quick_contact     |
> | sogo_sessions_folder   |
> | sogo_store             |
> | sogo_user_profile      |
> +------------------------+

And some

> php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.mailbox' doesn't exist
> php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.domain' doesn't exist
> php-fpm-mailcow_1    | ERROR 1146 (42S02) at line 1: Table 'mailcow.alias_domain' doesn't exist

**Comment by andryyy** [comment]
Check your reverse proxy. The page shouldn't return a 404. That's why the tables are missing.

**Comment by aquac** [comment]
@andryyy Thanks for your reply. I would be glad if you could help me with that.

I copied the nginx reverse proxy settings from the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/) page:

```
server {
        listen 80;
        server_name mail.xx.de autodiscover.xx.de;
            location / {
                proxy_pass http://127.0.0.1:10080/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                client_max_body_size 100m;
            }
}
```

In mailcow.conf, I configured the HTTP(S) ports to be 10080 and 10443:

```
 # netstat -tulpn | grep -E -w '25|80|110|143|443|465|587|993|995|10080|10443'
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2570/nginx: master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2570/nginx: master
tcp        0      0 127.0.0.1:10080         0.0.0.0:*               LISTEN      26076/docker-proxy
tcp        0      0 127.0.0.1:10443         0.0.0.0:*               LISTEN      26065/docker-proxy
tcp6       0      0 :::110                  :::*                    LISTEN      24838/docker-proxy
tcp6       0      0 :::143                  :::*                    LISTEN      24823/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      2570/nginx: master
tcp6       0      0 :::465                  :::*                    LISTEN      24248/docker-proxy
tcp6       0      0 :::25                   :::*                    LISTEN      24267/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      2570/nginx: master
tcp6       0      0 :::993                  :::*                    LISTEN      24810/docker-proxy
tcp6       0      0 :::995                  :::*                    LISTEN      24797/docker-proxy
tcp6       0      0 :::587                  :::*                    LISTEN      24235/docker-proxy
```

From the docker host (where I added "127.0.0.1 mail.xx.de" to /etc/hosts) I get:
```
# curl -Is http://mail.xx.de:10080
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sun, 15 Oct 2017 14:12:18 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 162
Connection: keep-alive

# curl -Is http://mail.xx.de:10080/SOGo
HTTP/1.1 302 Found
Server: nginx
Date: Sun, 15 Oct 2017 14:12:12 GMT
Content-Type: text/plain
Content-Length: 0
Connection: keep-alive
Location: /SOGo/index
```

The reverse proxy should then not play a role, right?
