### ISSUE TITLE
Global E-Mail Address

### ISSUE THREAD

**Issue by JustinBack** [mailcow/mailcow-dockerized#5666]
### Summary

Not sure if this is implemented already but is there a way to have a catch-all for the domain part of an email?

We currently have over 100 domains and use aliases for each domain to redirect all `postmaster@domain.tld` and `abuse@domain.tld` to our `support@provider.tld` email.

We tried setting a global pre sieve filter to redirect all abuse@ and postmaster@ emails to our support mail however it seems that dovecot checks first if the recipient is in the table before sending it to a sieve. So that fails with a recipient not found.

```
if header :contains ["To", "Cc", "Bcc"] "abuse@" {
    redirect "support@provider.tld";
}
```

Is there a way to define an alias like `abuse@*`-> `support@provider.tld` just like we can with the catch-all? `*@domain.tld`

### Motivation

Makes it easier to maintain abuse and postmaster mails or catch-all addresses

**Comment by DerLinkman** [comment]
Sounds like a good idea. We'll see what we can do

**Comment by fritzw** [comment]
Looks like this is almost a duplicate of #4507

**Comment by JustinBack** [comment]
Looks like it is an exact duplicate and requests the same thing, since this issue has the investigating label I'm not closing it, feel free to do so though.

**Comment by DerLinkman** [comment]
Duplicate of #4507

**Comment by kaystrobach** [comment]
my try in the prefilter, but it seams, that the mail is not delivered, as there is no entry in the virtual user table.

```sieve
# Redirect system emails to support
if address :is :localpart "to" ["hostmaster", "postmaster", "abuse", "webmaster"] {
    redirect "support@domain.tld";
    stop;
}
```
