### ISSUE TITLE
DMARC & TLSRPT Report parser and viewer

### ISSUE THREAD

**Issue by bundyland** [mailcow/mailcow-dockerized#5669]
### Summary

Hi Niklas, 

I just found and installed a very simple (but nice) parser/viewer for DMARC and TLS-RPT reports:

**[DMARC-SMTPTLS-Reports](https://github.com/antedebaas/DMARC-SMTPTLS-Reports)**

I wonder if we maybe could implement this (or something similar) to manage all the report stuff directly within Mailcow without using any third-party service? I know there are "nicer" tools available like parseddmarc, but these are kinda complicated to setup and need a powerful machine. The tool mentioned above is easy to set up and requires few resources. A corresponding Docker image is also available.

Just an idea....

Thank you!

### Motivation

to have everything "in one place" without being dependent on third-party providers.

**Comment by DerLinkman** [comment]
Other software but duplicate of: https://github.com/mailcow/mailcow-dockerized/issues/1341
