### ISSUE TITLE
Update breaks nginx container

### ISSUE THREAD

**Issue by RosaEinhorn** [mailcow/mailcow-dockerized#569]
Hi everbody,

when I try to update mailcow-dockerized (sing the update.sh) nginx breaks and keeps restarting after performing the update.
The error is:

> sudo docker logs f1154278bbe8
2017/09/10 08:31:33 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:36 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:38 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:39 [emerg] 11#11: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:42 [emerg] 9#9: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:44 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:48 [emerg] 9#9: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:53 [emerg] 9#9: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:54 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:55 [emerg] 9#9: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:56 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:31:58 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:32:00 [emerg] 11#11: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:32:04 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:32:12 [emerg] 9#9: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable
2017/09/10 08:32:25 [emerg] 10#10: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable

Any idea on how to fix that?

**Comment by andryyy** [comment]
We don't use the a connection_upgrade variable anywhere, must be related to a custom change.

**Comment by RosaEinhorn** [comment]
I haven't changed (or modified) any part of mailcow so far.

Edit: Found out that this is part of portainer: https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

Will try to fix it.

**Comment by andryyy** [comment]
But we don't use that variable. There was a How-To somewhere in the issues where this var was used. Have you applied these changes?

**Comment by RosaEinhorn** [comment]
No, I have just followed the steps from https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

**Comment by andryyy** [comment]
Well, then you know what breaks it. :-) You have tried to remove the upgrade part?

**Comment by RosaEinhorn** [comment]
I have just re-added

>upstream portainer {
  server portainer-mailcow:9000;
}

>map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

to  data/conf/nginx/site.conf.
Sorry for the confusion. Issue is resolved. :-)
