### ISSUE TITLE
Sogo CKEditor 4.22.1 version is not secure. Erorr.

### ISSUE THREAD

**Issue by sisska** [mailcow/mailcow-dockerized#5725]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When opening the CKEditor editor when writing a letter in the sogo web interface. An error message appears: This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.24.0-lts.
```

### Logs:

```plain text
--
```

### Steps to reproduce:

```plain text
1. go to mydomain.xxx\sogo
2. click write a message.
3. In the text editing field, an error message will appear on the tap frame This CKEditor 4.22.1 version is not secure. Consider upgrading to the latest one, 4.24.0-lts.
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Debian 12

### Server/VM specifications:

32Gb/24CPU

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

dedicated server

### Docker version:

25.0.3

### docker-compose version or docker compose version:

docker-compose version 1.25.0

### mailcow version:

2024-01e

### Reverse proxy:

no

### Logs of git diff:

```plain text
-- --
```

### Logs of iptables -L -vn:

```plain text
-- --
```

### Logs of ip6tables -L -vn:

```plain text
---
```

### Logs of iptables -L -vn -t nat:

```plain text
--- -
```

### Logs of ip6tables -L -vn -t nat:

```plain text
--- -
```

### DNS check:

```plain text
- --
```

**Comment by chriscroome** [comment]
See this issue for a work-around: https://github.com/mailcow/mailcow-dockerized/issues/5713

**Comment by MAGICCC** [comment]
WIll close due to dupe
