### ISSUE TITLE
Improve GUI by adding help 

### ISSUE THREAD

**Issue by cwildfoerster** [mailcow/mailcow-dockerized#574]
I think for unexpierienced users it would be a great extension to add some kind of help or tipps to any given setting, just like the guys at OPNsense did in their web GUI.

![advanced](https://user-images.githubusercontent.com/333214/30250958-6e33aece-9657-11e7-8523-e2a14ac96029.png)
As you may see from the screenshot, almost every setting has some kind of help or extended description, so you know what the setting is for or what it will do. If the little `I` is orange, that means you can click on it to see this help or use the `full help` action on the top right.

![info](https://user-images.githubusercontent.com/333214/30250960-7399e52c-9657-11e7-8e33-169a7d847810.png)
Thats how it look when you click the little `I` or the `full help` action.

Extending the the code to provide that kind of feature should be pretty easy, bootstrap already has some elements for help blocks. The big problem i see is getting all the content together, especially in all languages. I'm pretty fluent in english and german as my mother tongue, so if you guys think this is a good idea, then i would start and create a PR.

Also i would like to see a link to the offical documentation somewhere on the web ui :)

**Comment by K2rool** [comment]
That might be quite helpful, but saying that you probably shouldn't be hosting your own email's anyways if you need help tips to config it.

P.s this just my own personal opinion.

But i do think the idea of adding extendable help info is a good one.

**Comment by mkuron** [comment]
Mailcow doesn't have that many detailed options. So I think the purpose could already be served by enhancing the descriptive texts (or adding ones where they are missing) above each configuration section. Tips and more details can go into the Mailcow documentation. In cases where it is useful, cross-references to the documentation could be added.
