### ISSUE TITLE
Backup and restore script not working

### ISSUE THREAD

**Issue by Dominik9798** [mailcow/mailcow-dockerized#5749]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After running the "backup_and_restore.sh" with parameters "backup" and "all" following error occured

root@mailserver:/opt/mailcow-dockerized# sh helper-scripts/backup_and_restore.sh backup all
helper-scripts/backup_and_restore.sh: 5: helper-scripts/backup_and_restore.sh: [[: not found
helper-scripts/backup_and_restore.sh: 9: helper-scripts/backup_and_restore.sh: Syntax error: "(" unexpected (expecting "then")
```

### Logs:

```plain text
root@mailserver:/opt/mailcow-dockerized# sh helper-scripts/backup_and_restore.sh backup all
helper-scripts/backup_and_restore.sh: 5: helper-scripts/backup_and_restore.sh: [[: not found
helper-scripts/backup_and_restore.sh: 9: helper-scripts/backup_and_restore.sh: Syntax error: "(" unexpected (expecting "then")
```

### Steps to reproduce:

```plain text
1. Login to mailserver
2. go to folder "cd /opt/mailcow-dockerized"
3. execute "sh helper-scripts/backup_and_restore.sh backup all"
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Debian GNU/Linux 10 (buster)

### Server/VM specifications:

8 GB memory / ~6,5 GB used

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.2

### docker-compose version or docker compose version:

1.29.2

### mailcow version:

2024-02

### Reverse proxy:

nginx for port 80 and 443

### Logs of git diff:

```plain text
-
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
-
```

**Comment by climba03003** [comment]
The scripts requires to be `bash` not `sh`.
You can try to directly run the script without `sh`.
