### ISSUE TITLE
Rspamd log not loading in mailcow ui

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#575]
Hi,

have a strange problem (that existed already before the last update).

In the mailcow UI the rspamd log is not loading (it is loading forever and not showing). All other logs are loading fine.

Any idea or somebody with the same error?

<img width="951" alt="bildschirmfoto 2017-09-11 um 07 12 09" src="https://user-images.githubusercontent.com/11010788/30259598-67883412-96c2-11e7-86c4-7be48628eeb4.png">

**Comment by andryyy** [comment]
Hi, must be a JSON parsing error. Can you open your browsers debug console (Ctrl + Shift + C) and see what it is logging there?

**Comment by phillipplum** [comment]
Same problem here. The response from /api/v1/get/logs/rspamd-history is empty. 

<img width="731" alt="bildschirmfoto 2017-09-11 um 08 48 00" src="https://user-images.githubusercontent.com/6051483/30261659-0b3bc258-96ce-11e7-9ebc-6bf685085ced.png">

**Comment by Skydiver84de** [comment]
Does this output help?:

[Log] Cannot draw rspamd history table (admin.js, line 424)

[Error] FooTable: unhandled error thrown during initialization.
Error: Rows ajax request error: 200 (HTTP/2.0 200)
(anonyme Funktion) — footable.min.js:955
(anonyme Funktion) — jquery-1.12.4.min.js:1306
i — jquery-1.12.4.min.js:1241
fireWith — jquery-1.12.4.min.js:1279:99
y — jquery-1.12.4.min.js:3454:624
c — jquery-1.12.4.min.js:3634
	(anonyme Funktion) (footable.min.js:8:19745)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28894)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28894)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28894)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28774)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28894)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:29193)
	(anonyme Funktion) (footable.min.js:9:1341)
	(anonyme Funktion) (jquery-1.12.4.min.js:2:28774)
	i (jquery-1.12.4.min.js:2:27455)
	fireWith (jquery-1.12.4.min.js:2:28215)
	y (jquery-1.12.4.min.js:4:22757)
	c (jquery-1.12.4.min.js:4:26927)

**Comment by cataldoc** [comment]
Hi

I'm having the same issue... in addition to the above mentioned logs I see this in the console:

**Cannot draw rspamd history table**

from admin.js line 561

**Comment by axd** [comment]
I'm getting this error, it seems that the request gets trunked and it doesn't load the entire log.

> SyntaxError: JSON.parse: unterminated string at line 1 column 1060611 of the JSON data

**Comment by Skydiver84de** [comment]
Seems to be solved in the meantime.
