### ISSUE TITLE
Send mail over smtps(tcp 465)

### ISSUE THREAD

**Issue by allegrox** [mailcow/mailcow-dockerized#5767]
### Summary

My ISP disables connections where the destination port is 25, and I'd like to be able to get mailcow to send mail over the smtps protocol, i.e., tcp port 465.

### Motivation

This makes deploying mailcow much easier.

**Comment by mkuron** [comment]
That's not possible. Other mail servers won't accept your messages over ports other than 25, which is defined as the port over which server-to-server exchange of messages takes place. Ports 587 and 465 are used only for (authenticated) client-to-server message submission.

If your ISP's firewall doesn't allow outgoing connections over port 25, you will need to either ask them to grant you an exception, or configure Mailcow to use a relayhost for all outgoing messages -- i.e. another mail server on which you haven an account that lets you log into port 587 and that accepts your messages without sender address checks or too much rate limiting.

**Comment by ripkens** [comment]
This is not fully true

Port 465 is the SSL SMTP Port, it accepts mails just as Port 25 does
Port 587 is the Submission Port and only allows authenticated connections

For ISPs blocking Port 25, there should be an option to send outgoing mails on Port 465 if Port 25 is not available.

More and more MSP switch to Port 465 to only allow SSL SMTP Connections
