### ISSUE TITLE
Why oh why are mailservers so painful to install?

### ISSUE THREAD

**Issue by andymarden** [mailcow/mailcow-dockerized#5768]
### Summary

Tried modoboa and because I am stupid) I installed it on my proxmox host instead of an lxc by mistake. No uninstall script and god knows what it has installed so backing it out was horrendous. And there's an error in the web page at initial logon so switching to mailcow to try that:

Docker - nice - but then I see I can't install with portainer, it automates things via a script to an extent where you can't really use bind mounts and workarounds talk about symbolic links from /var/lib/docker and there are installation requirements on teh docker host it seems.

I get that running your own mailserver is challenging but why can't this installation be as simple as other docker stack installations in portainer for example?

I have a VM with docker installed and an LXC with disconnected services but this leads me to put mailcow with docker on its own lxc because of all the monkeying around.

### Motivation

Ease of installation with familiar patterns

**Comment by DerLinkman** [comment]
??
