### ISSUE TITLE
Message size Limit not working with Round Cube

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#578]
Hey guys, I hope you all are doing great! 
I have an issue I installed RoundCube with your guide but it only allows me to add 2M attachments max.

You actually have a guide:
`Open data/conf/postfix/main.cf and set the message_size_limit accordingly in bytes.`

But after restarting container these changes doesn't affect Round Cube. 

Any tip?

**Comment by twixi** [comment]
how to edit this in docker?
