### ISSUE TITLE
Autodeletion / Autoexpunge of Trash and Junk Folder

### ISSUE THREAD

**Issue by shephirt** [mailcow/mailcow-dockerized#5782]
### Summary

I would like to see a setting in the mailcow UI, to set an expiry date for mails in the trash and junk folder of inboxes.
It took me personally some time to notice, that those are not getting auto-deleted but my mailbox quota is getting less and less.

This setting should be at least a server-wide setting, but domain-wide or individual settings per mailbox would be also helpful in some usecases.

### Motivation

Unfortunatley there's no hint in the documentation that per default there's not auto-deletion of these folder. But this is normally an expected behaviour from a mailbox, that the Junk and Trash folder are regularly emptied.

Of course this could also be resolved via a hint and a manual in the documantation how to change that behaviour and certainly there is already. But it took me almost one year to notice that and find that article.

I think a setting possibility within the UI would be highly beneficial, as said, this is usually an expected behaviour we all know from public mailbox providers.

### Additional context

My current solution to this is an entry in the extra.conf file for dovecot looking like this

```
namespace inbox {
  mailbox "Trash" {
    autoexpunge = 30d
  }
  mailbox "Junk" {
    autoexpunge = 30d
  }
}
```

**Comment by DerLinkman** [comment]
Hello,

yes i agree that there is a missing docs entry which we can add. But not the feature itself for all. Escpecially not for the Junk folder as the Rspamd system is automatically learning the mails which are left inside the junk folder overtime.

**Comment by DerLinkman** [comment]
I just saw: There is already a guide on howto configure autopurging of the desired folders, see:
https://docs.mailcow.email/manual-guides/Dovecot/u_e-dovecot-expunge/

**Comment by shephirt** [comment]
Hi @DerLinkman 

may i understand the reasons why this feature can’t be implemented? Is there some technical reasons?

And i understand the Rspamd argument, but your linked article is also adding some deletion rules for the junk folder? What’s the difference?
