### ISSUE TITLE
can't start docker containers - docker containers are "unhealthy"

### ISSUE THREAD

**Issue by d-koppenhagen** [mailcow/mailcow-dockerized#579]
Hi guys,
I recently tried to upgrade mailcow to the newest version using the script update.sh.
During this it happens that my containers aren't starting anymore. I got the message that they are unhealthy.
Also manually starting a single container doesn't work anymore (e.g. docker-compose up acme-mailcow).
Here is a screenshot of this:
![screen shot 2017-09-11 at 21 07 54](https://user-images.githubusercontent.com/4279702/30292587-0beeb14c-9737-11e7-92fb-7c4973c25aed.png)
How can I solve this problem?

**Comment by mkuron** [comment]
Try `docker-compose down`, then check with `docker ps` if there are any leftover containers. Sometimes docker-compose leaves containers in undefined states when recreating them.

**Comment by d-koppenhagen** [comment]
Hey, i tried this but it's unfortunately still not working:
```bash
dannyk@sheldon:~/mailcow-dockerized$ docker-compose down
Stopping mailcowdockerized_unbound-mailcow_1 ... done
Stopping mailcowdockerized_mysql-mailcow_1   ... done
Stopping mailcowdockerized_clamd-mailcow_1   ... done
Stopping mailcowdockerized_ipv6nat_1         ... done
Removing mailcowdockerized_unbound-mailcow_1 ... done
Removing mailcowdockerized_mysql-mailcow_1   ... done
Removing mailcowdockerized_clamd-mailcow_1   ... done
Removing mailcowdockerized_ipv6nat_1         ... done
Removing network mailcowdockerized_mailcow-network
dannyk@sheldon:~/mailcow-dockerized$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
dannyk@sheldon:~/mailcow-dockerized$ docker-compose up
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
Creating mailcowdockerized_mysql-mailcow_1 ...
Creating mailcowdockerized_ipv6nat_1 ...
Creating mailcowdockerized_mysql-mailcow_1
Creating mailcowdockerized_clamd-mailcow_1 ...
Creating mailcowdockerized_ipv6nat_1
Creating mailcowdockerized_clamd-mailcow_1 ... done
Creating mailcowdockerized_unbound-mailcow_1 ...
Creating mailcowdockerized_unbound-mailcow_1 ... done

ERROR: for dovecot-mailcow  Container "9b802df583fd" is unhealthy.

ERROR: for postfix-mailcow  Container "9b802df583fd" is unhealthy.

ERROR: for memcached-mailcow  Container "9b802df583fd" is unhealthy.

ERROR: for redis-mailcow  Container "9b802df583fd" is unhealthy.

ERROR: for sogo-mailcow  Container "9b802df583fd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by andryyy** [comment]
While it tries to start mailcow, can you check the logs in a second terminal with `docker logs 9b802df583fd`?

**Comment by d-koppenhagen** [comment]
Sorry for late response. I was very busy. I recently changed to using mailcow.server as a service and I am also not able to reproduce this problem currently I think it was an error on my server. I will close this issues as it's not really replicable anymore. Thanks anyway
