### ISSUE TITLE
AntiVirus Integration?

### ISSUE THREAD

**Issue by apoc4lyps** [mailcow/mailcow-dockerized#58]
Hi, are there any plans for ClamAV integration or some sort of diffrent antivirus?

**Comment by broedli** [comment]
I don't know @andryyy plans for this but here would be a rundown of a similar question and @andryyy reasoning for not including it:
https://github.com/andryyy/mailcow/issues/41

**Comment by sfnke** [comment]
Hi,

I think ClamAV itself won't be implemented as rmilter/rspamd does support this as well (see https://rspamd.com/rmilter/ and https://rspamd.com/doc/modules/antivirus.html).

And since the dockerized version is already running on rmilter/rspamd this might be easy to implement.

cheers,
carazzim0

**Comment by apoc4lyps** [comment]
so it should be possible to use the local clanav binarys inside the rspamd container or create an seperate clamav container for av scanning

**Comment by andryyy** [comment]
We can add a ClamAV container which is optional. But I am not sure how to handle that in Rspamd. Maybe we can use an entrypoint in Rspamds Dockerfile to check wether or not a socket is up and then link/write a config for it.

**Comment by apoc4lyps** [comment]
Rspamd and Rmilter can use ClamAV TCP Socket (https://rspamd.com/rmilter/configuration.html#clamav-section and https://rspamd.com/doc/modules/antivirus.html)

**Comment by andryyy** [comment]
I know. I mean handling wether or not a socket is up. I do not want to have a timeout in the av module of Rspamd.

**Comment by marrco** [comment]
as i wrote on forum.mailcow.email i'd love to have it on a different VPS so to keep ram and cpu use low on mailcow.dockerized server. So it would be great to have an option to define an host:port instead of a local container. ClamAV (including optional sanesecurity signatures) is a great tool, bot not low on resources

**Comment by andryyy** [comment]
You can already do it very easily. Just see Rspamd docs for antivirus. I think I will add it to the mailcow docs now, too.

**Comment by marrco** [comment]
Thanks andryyy. I guess all I need is proper documentation. I'm still not sure about what i can modify, how to save (git) the list of modification and merge them back, what will survive a mailcow upgrade and what won't. I'll try to link rspamd-dockerized to my Clamd running on a different server, and git commit that change to my local repository in hope that change will stay even after an upgrade. You're teaching an old dog new tricks.

**Comment by denji** [comment]
https://github.com/extremeshok/clamav-unofficial-sigs

**Comment by Braintelligence** [comment]
Yeah, a step-by-step guide would be great!

**Comment by mkuron** [comment]
It's recently been added to the dev branch. You only need to uncomment a few lines in docker-compose.yml to enable it.

I think this issue can now be closed.

**Comment by andryyy** [comment]
I even uncommented it for further releases.

I try to test some things tomorrow and rebase master on dev then. :)
