### ISSUE TITLE
Accepted redundancy in unbound healthcheck.sh

### ISSUE THREAD

**Issue by B-Interactive** [mailcow/mailcow-dockerized#5808]
### Summary

As is highlighted in https://github.com/mailcow/mailcow-dockerized/issues/5649,  currently `data/Dockerfiles/unbound/healthcheck.sh` strictly requires that _all three_ ping tests to the three major DNS services are successful:
- 1.1.1.1 (Cloudflare)
- 8.8.8.8 (Google)
- 9.9.9.9 (Quad9)

Failure to pass _any_ of the three tests, results in an "unhealthy" status, which in turn degrades other Mailcow services (such as SMTP in my brief testing).  In essence, if only 2 out of 3 DNS providers are 100% fine, Mailcow breaks.

Disabling this test entirely (https://github.com/mailcow/mailcow-dockerized/pull/5652) circumvents the issue, but at the cost of being left in the dark about more serious DNS issues.

To address this, the healthcheck might build in a degree of tolerance.

### Motivation

I would like to suggest, that passing just 2 of the 3 DNS provider ping tests, particularly given they are targeting entirely different providers, is sufficient to satisfy "healthy".  Two should fall within tolerance.  Three is for redundancy sake.

It should not be assumed Cloudflare, Google or Quad9 will never be a fault for failing a ping test, nor the chance that something in-between (hosting etc) may trip it up, and yet the working state of Mailcow hinges on this test.

I would still like to receive a warning of a failed ping test, in case it's something that could be addressed, but I don't believe a degraded mail server should be the outcome of a failed ping test to just 1 of the 3 DNS providers.

**Comment by thejordanclark** [comment]
I agree this should be 2 of 3.  This actually happened to me this morning as my mailcow instance is failing to ping the Quad9 name server.  The other two passed.

**Comment by DerLinkman** [comment]
This is fixed with a patch a few month prior already.
