### ISSUE TITLE
unbound log error

### ISSUE THREAD

**Issue by VladimirBorisov** [mailcow/mailcow-dockerized#585]
On each start I can see the docker log message from unbound container like 
`unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied`
Not sure how this affects on the logs itself because I can see few lines of log just after
```
unbound-mailcow_1    | [1505165580] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1505165580] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1505165581] unbound[1:0] info: start of service (unbound 1.6.2).
```
Same situation I can see in issue #434 (but it is not related with issue itself)
Probably same described in #496 (and solution suggested)

The main question - is this situation can "hide" some logs? Or unbound will use "stdout" for logs in case logfile (/dev/stdout) cannot be opened and thus logs are ok in any case?

**Comment by Bersam** [comment]
I'm seeing this too, after moving docker to another host seems there's some problems with /dev/stdout missing.
