### ISSUE TITLE
priority and weight for SRV record

### ISSUE THREAD

**Issue by mamacodosacoazul** [mailcow/mailcow-dockerized#5853]
whats the priority and weight for SRV record?

**Comment by mamacodosacoazul** [comment]
![Screenshot 2024-04-22 180346](https://github.com/mailcow/mailcow-dockerized/assets/167721595/94663db5-2bc3-4b26-88da-5e49e370dd0b)
![Screenshot 2024-04-22 180318](https://github.com/mailcow/mailcow-dockerized/assets/167721595/84a6d92f-2470-4d84-9f31-7073b8064dc1)

**Comment by chriscroome** [comment]
Any positive numbers should be fine.

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)
