### ISSUE TITLE
New PTR: Change MAILCOW_HOSTNAME

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#586]
Hi! I change my hoster and now have a new IP address with a new hostname (PTR). I have changed the `MAILCOW_HOSTNAME` in `mailcow. conf`.

What else do I have to do? Is there any official documentation for this problem?

**Comment by andryyy** [comment]
Try a `docker-compose down` followed by `docker-compose up -d`. Rspamd stats will be gone, is that important for you?

**Comment by mritzmann** [comment]
> Rspamd stats will be gone, is that important for you?

Is not important.

> Try a `docker-compose down` followed by `docker-compose up -d`.

Thanks, it works! (I tried `docker-compose restart`, but that doesn't work...)
