### ISSUE TITLE
PTR Records

### ISSUE THREAD

**Issue by mamacodosacoazul** [mailcow/mailcow-dockerized#5861]
are these PTR records really needed? my mailcow works fine without them... do i need to add them to my Cloudflare DNS records? they already have the green checkmark showing even tho i never added them to my Cloudflare DNS records...

and btw, i have reverse dns set for my server ipv6 and ipv4 if that matters, literally everything is working fine without those records, i just wonder what are they for
![image](https://github.com/mailcow/mailcow-dockerized/assets/167721595/b628c47e-2227-4bff-bb27-032c8bf383b2)

**Comment by patschi** [comment]
Issues are not used for any support, please use our dedicated [forum](https://community.mailcow.email/) for this.
And yes - they are strongly recommended, as without proper PTRs your mails might get bad rating at best or be rejected straight away at worst.

Not followed PR template, closing.
