### ISSUE TITLE
OIDC Support Stable Branch

### ISSUE THREAD

**Issue by MXNPD** [mailcow/mailcow-dockerized#5867]
### Summary

When can we expect to see the OIDC implementation in the stable branch of Mailcow? I use Mailcow for our company email and my boss was insistent on us using OIDC for login, but that is currently on Nightly, as are we. Is there perhaps a timeline we can expect OIDC to be moved to stable or offer a toggle in the Stable branch to enable OIDC as a Beta? Just would love to get off of the Nightly branch and back onto the Stable branch. 

### Motivation

This would benefit others by allowing for a wider range of users to test and use the OIDC implementation in production Environments.

**Comment by DerLinkman** [comment]
Simply when it's ready. No ETA here!
