### ISSUE TITLE
Not posssible to create a domain alias with an "Umlaut"

### ISSUE THREAD

**Issue by DuerrComputer** [mailcow/mailcow-dockerized#5874]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
When you want to create a domain alias with a "Umlaut" and save it, the "Umlaut" gets encoded wrong and ends up in a mess. More Details see Steps to reproduce
```

### Logs:

```plain text
No Error Log
```

### Steps to reproduce:

```plain text
1. Go to "Aliasse" --> "Domain Aliasse" and Press the Button "add domain alias"
2. Enter one of  the following example alias names:
täst
töst
tüst
3. Select a destination Domain (which one doesn't matter)
4. Press Save/Add/Hinzufügen
5. See the result. For Example "täst" is encoded to "xn--tst-qla"
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Debian 12

### Server/VM specifications:

12GB RAM, 10 Cores

### Is Apparmor, SELinux or similar active?

No

### Virtualization technology:

VM

### Docker version:

26.0.2

### docker-compose version or docker compose version:

v2.26.1

### mailcow version:

2024-04

### Reverse proxy:

NGINX

### Logs of git diff:

```plain text
No Code changes
```

### Logs of iptables -L -vn:

```plain text
I use uwf and it has nothing to do with the error
```

### Logs of ip6tables -L -vn:

```plain text
I use uwf and it has nothing to do with the error
```

### Logs of iptables -L -vn -t nat:

```plain text
I use uwf and it has nothing to do with the error
```

### Logs of ip6tables -L -vn -t nat:

```plain text
I use uwf and it has nothing to do with the error
```

### DNS check:

```plain text
Working
```

**Comment by MAGICCC** [comment]
That's IDN style and it's correct for täst - see https://dnschecker.org/idn-punycode-converter.php
