### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#5891]
### Summary

Hello,

No updates or info since months the project is dead?

### Motivation

.

### Additional context

.

**Comment by chriscroome** [comment]
Nononono, no, no! 'E's resting!

**Comment by omexlu** [comment]
Ah ok :D

**Comment by patschi** [comment]
The last update was yesterday 9am CEST: https://github.com/mailcow/mailcow-dockerized/commits/nightly/. So, no it isn't.

**Comment by omexlu** [comment]
That the nightly so not an offical stable update :)
Also: [SOGo] Update to 5.10.0 is not really a big thing.

**Comment by DerLinkman** [comment]
Nope, not dead just not enough time to updating mailcow monthly. That's why we leaving the monthly update routine for now i think we'll discuss this on a blog/social media post too.
