### ISSUE TITLE
Need help with php.ini

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#590]
How can I edit some values in PHP.INI it is because I'm triyng to setup a higher attachment limit in RoundCube with your guide  but it doesn't work for me.

I tried with your guide editing postfix/main.cf restarted containers but RoundCube still says 2MB attachments. 
Tried htaccess in RC  folder and nothing seems to be working.

Thanks.

**Comment by mkuron** [comment]
.htaccess doesn't work because this isn't Apache/mod_php. The FCGI interface supports a [.user.ini](http://php.net/manual/en/configuration.file.per-user.php) file though. The global php.ini is inside of the php-fpm container and cannot be modified outside of the Dockerfile.

**Comment by alyzrazor** [comment]
Ok thanks for helping, so how can I just increase 2mb attachment in Round Cube =( ? I'm stuck

**Comment by mkuron** [comment]
Put the parameter into a .user.ini file in the data/web directory. We use FCGI.

**Comment by alyzrazor** [comment]
Thanks so much @mkuron  I also had to use client_max_body_size in ngnix conf. But finally it worked out!  /beers for you
