### ISSUE TITLE
ImapSync sync out to other IMAP server 

### ISSUE THREAD

**Issue by worryboy** [mailcow/mailcow-dockerized#5906]
### Summary

as discussed under https://community.mailcow.email/d/1102-imapsync-to-migrate-from-mailcow-to-other-provider currently its only possible to sync into the mallow mailbox. On the form only a "source" can be defined . 

It would be great to extend the form and the code to enable the switch of using map sync. 

https://github.com/mailcow/mailcow-dockerized/blob/36b5cccd186090d726de62b6b00d1e842e67aacd/data/Dockerfiles/dovecot/imapsync_runner.pl#L148

in example 
>> implement an switch button to decide between source an target 

### Motivation

it enables 
- bidirectional sync 
- extra backup strategies (eg sync only folder abroad, sync more than on mailbox into on target) 
- compliant email archiving (eg https://www.ionos.com/digitalguide/e-mail/technical-matters/email-archiving-laws-and-practices-you-should-know/)

### Additional context

current gui (only source can be defined)
![image](https://github.com/mailcow/mailcow-dockerized/assets/21039983/ab6db6ee-25ce-4342-aa50-d042bc8b6241)

**Comment by DerLinkman** [comment]
Hello,

no we won't implement this... sorry why would we? This tool is a handy addition to move to mailcow in a easy way, if you move somewhere else you have to see how you migrate your mails into that on your own (e.g run a own imapsync instance)

**Comment by worryboy** [comment]
Oh , that bad news and not understandable (from my point of view) .. 

mostly you did not understood the one of the main focus 
Snip 
> compliant email archiving (eg https://www.ionos.com/digitalguide/e-mail/technical-matters/email-archiving-laws-and-practices-you-should-know/)
Snap 

but anyway , your answer is clear 
like 
- we open any away to join the mailcow land 
- we will not enable any way to possible move away from mailcow.. (like all others) 

Have a nice day

**Comment by gpz1100** [comment]
@worryboy Why not have your external imap target connect to mailcow imap for message import?

Mailcow doesn't block any imap connections.  What are you trying to replicate to?
