### ISSUE TITLE
make it easier to make emails as spam / teach rspamd

### ISSUE THREAD

**Issue by G2G2G2G** [mailcow/mailcow-dockerized#5931]
### Summary

So I've noticed in the alias category you have a button to auto teach rspamd that something is spam?

![image](https://github.com/mailcow/mailcow-dockerized/assets/50514477/78165409-e9f6-4567-9b7a-4d3cd44d3b82)

### Motivation

Rspamd is pretty bad interface for teaching what is good/bad there is no easy button you have to copy the email source into it. Not easy for many users system

### Additional context

I think just on the logs page for rspam if you have a button that just says "this is spam" and it auto-teaches rspamd that message?

**Comment by MAGICCC** [comment]
rspamd is not developed by mailcow
You may ask @ https://github.com/rspamd/rspamd

**Comment by G2G2G2G** [comment]
Who said it was?
Are you claiming rspamd team developed mailcow's alias system with the two buttons I screenshotted?

**Comment by G2G2G2G** [comment]
Can you reopen this since it has nothing to do with adding anything to rspamd and you just didn't read it?
Or do you really want me to bother rspamd devs and have them send me back here just to prove to you that adding stuff to mailcow's UI isn't part of their job? @MAGICCC

**Comment by MAGICCC** [comment]
Maybe I misunderstood you yes.
Just to confirm where do you want to have a button?
On https://mail.example.org/rspamd/#history or somewhere like https://mail.example.org/debug?

**Comment by G2G2G2G** [comment]
Yea I wasn't sure it was possible that is why I asked how they are added on the "mailcow alias page"

and my motivation is because rspamd kinda sucks to use..

But yea those pages you linked, the rspamd one does not have it that is for them to add but they won't. I asked like 5+ years ago.

On the mailcow page if it is possible I think it should be added:

![image](https://github.com/mailcow/mailcow-dockerized/assets/50514477/8bdec8f5-9f39-4438-a69f-b5bca45bc5a4)


maybe a second button? "mark as spam" or "take action" and it pops up with mark spam / mark ham
![image](https://github.com/mailcow/mailcow-dockerized/assets/50514477/00f72757-c9d0-4d9b-b7a3-c6eef07c1685)

maybe like this?
![image](https://github.com/mailcow/mailcow-dockerized/assets/50514477/7808cac1-1992-4fa6-aede-32528a7eefa2)

```
<td>
<div class="badge fs-6 bg-danger">Mark Spam</div>
<div class="badge fs-6 bg-success mt-1 w-100">Mark Ham</div>
</td>
```


---

I have these same people spamming the server for 2 years, like 1 email per week. They're pretty similar emails however the domain changes.

I have tried to "learn spam" in the rspamd idk if I am using it correctly or not.
There doesn't seem to be any tutorials at all so if it's that "straight forward" I would guess it is working?
But it doesn't send them to spam lol... I've "taught" the emails to it many times.
I haven't tried the alias ones because they send to random people on our company and some of the emails are legit -.-

So I'd just like to have a button to manually do it.

**Comment by G2G2G2G** [comment]
I copied some of this from the other admin button so it is not fully correct
```html
<td>

<a class="btn btn-sm btn-xs-half d-block d-sm-inline btn-success dropdown-toggle show" data-bs-toggle="dropdown" href="#" aria-expanded="true">no action</a>
    <ul class="dropdown-menu show" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(1096px, 761px, 0px);" data-popper-placement="bottom-start">
        <li>
            <a class="dropdown-item" data-action="edit_selected" data-id="admins" data-api-url="edit/admin" data-api-attr="{&quot;active&quot;:&quot;1&quot;}" href="#">
                <span class="badge bg-danger">Mark Spam</span>
            </a>
    </li>
    <li>
        <a class="dropdown-item" data-action="edit_selected" data-id="admins" data-api-url="edit/admin" data-api-attr="{&quot;active&quot;:&quot;0&quot;}" href="#">
            <span class="badge bg-success">Mark Ham</span>
        </a>
    </li>
</ul>

</td>
```

![image](https://github.com/mailcow/mailcow-dockerized/assets/50514477/c2deda9c-c4f4-4e6d-a5af-32e5f17d6beb)

but it has a nice outcome

**Comment by DerLinkman** [comment]
Hi,

your idea is not easy (if not impossible) to add.

Because the things you mapped the mark... dropdown to are only the logs we grab from rspamd when the mails already have been scanned by the server. A fuzzy training (spamhash storage) with this style (marking the mails content as bad/good content) is only possible once the server reads the mail.

The quarantine feature follows a different approach, it is caching a mail inside the Mysql DB to later on project the contents into a file rspamd can work with. But that is only been done for a few mails reaching the "spam score" area and not for all.

The quarantine is not enabled by default how ever.

**Comment by G2G2G2G** [comment]
Yea that's what I wondered in my original question. Because I didn't even think interfacing with rspamd was possible at all however I saw it in the alias section so I thought maybe it now was.
If it is a pain then you can just close it
