### ISSUE TITLE
Nginx, Dovecot and Postfix automatic restart after new certificate detected

### ISSUE THREAD

**Issue by liamriley1** [mailcow/mailcow-dockerized#5933]
### Summary

I am currently having to create an external cron job to continually check whether the mailcow certificates have been renewed, and then manually restart the affected containers (nginx, dovecot and postfix). Is there any chance that the functionality could be added so that these services detect that the certificate has changed and restart themselves automatically?

### Motivation

Would make it much easier for use of external certificates and renewal. With this approach, one could simply use another container like DNSRoboCert to generate certificates and mount the /data/assets/ssl/ directory onto the DNSRoboCert container so that the renewed certificates could be copied straight into the correct location, after which mailcow would restart automatically. Currently, users have to either create external cronjobs to check if the certificate has been changed, or make systemd services to continually monitor the files and restart containers if required.

**Comment by DerLinkman** [comment]
We do something like this when acme is renewing/expanding the certificates. It is triggering a docker api restart of the containers. However with external Cert Providers we won't add this... would change to much internally

**Comment by liamriley1** [comment]
Understandable :(

Thanks for the great project so far though, it's been great moving things away from Google!

**Comment by DerLinkman** [comment]
Thanks for leaving the big contestants and hosting your emails on your own!
