### ISSUE TITLE
backup and restore cannot use "10" threads

### ISSUE THREAD

**Issue by G2G2G2G** [mailcow/mailcow-dockerized#5938]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
backup/restore if you use "THREADS=10" you get "Thread input is not a number!"

I tried backup on bash shell and restore on fish shell (different machines)
I don't think the shell matters
```

### Logs:

```plain text
MAILCOW_BACKUP_LOCATION=/mnt/4tbhdd/mailcow/ THREADS=10 /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all
Thread input is not a number!
```

### Steps to reproduce:

```plain text
https://docs.mailcow.email/backup_restore/b_n_r-backup/
just use "THREADS=10"
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

debian 10 and 12

### Server/VM specifications:

8gb and 32gb of ram, 12 and 20 cpu cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

none on 1 system and kvm/qemu on other

### Docker version:

newest

### docker-compose version or docker compose version:

v2.28.1 and v2.7.0

### mailcow version:

newest

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
unrelated
```

### Logs of iptables -L -vn:

```plain text
unrelated
```

### Logs of ip6tables -L -vn:

```plain text
unrelated
```

### Logs of iptables -L -vn -t nat:

```plain text
unrelated
```

### Logs of ip6tables -L -vn -t nat:

```plain text
unrelated
```

### DNS check:

```plain text
unrelated
```

**Comment by mrclschstr** [comment]
I think the regex in the [script](https://github.com/mailcow/mailcow-dockerized/blob/master/helper-scripts/backup_and_restore.sh#L58) is wrong as it allows no zeroes at all: `^[1-9]+$`

To allow numbers from 1 to 99 without a leading zero you could use something like this ([source](https://stackoverflow.com/a/27991015)): `^([1-9][0-9]?)$`

**Comment by G2G2G2G** [comment]
I think the [[:digit]] or just 0-9 is enough. don't think anyone is going to be trying decimal points for amount of threads lol

**Comment by MAGICCC** [comment]
Hm there is https://github.com/mailcow/mailcow-dockerized/pull/5634
Can we get this merged @DerLinkman?

**Comment by G2G2G2G** [comment]
Good find.. man stale bots kill a lot of useful stuff.

**Comment by DerLinkman** [comment]
Merged and will be part of next update (sorry missed to write that yesterday)
