### ISSUE TITLE
"Shared" folder in SOGo doesn't work

### ISSUE THREAD

**Issue by evilstiefel** [mailcow/mailcow-dockerized#594]
When opening the SOGo interface, the link to "Other users" in the folder list doesn't work. An error-message pops up stating that the communication with the mailserver failed.

Upon inspecting the SOGo-logs, the following entries appear:

`Sep 13 23:28:29 02ac4130b9e5 sogod [100]: [ERROR] <0x0x5654e6779810[NGImap4Connection]> could not select URL: imaps://mail%40*censored*@dovecot/Shared/?tls=YES: {RawResponse = "{ResponseResult = {description = \"Mailbox doesn't exist: Shared (0.001 + 0.040 + 0.039 secs).\"; result = no; tagId = 7; }; }"; reason = "Mailbox doesn't exist: Shared (0.001 + 0.040 + 0.039 secs)."; result = 0; }`

It seems to me that either 
1. the "Shared" folder for new users isn't created properly
2. SOGo shouldn't be showing the link when no folders are shared

The second option seems unlikely, since even after sharing a folder, the recipient of the share still cannot click the folder and the same error is produced.

**Comment by andryyy** [comment]
You need to click the folder icon left to "Other users".

**Comment by evilstiefel** [comment]
Not to sound too offensive, but, did you even read my issue report?

I know that  that's a common UI problem people have with SOGo, this is **not** the case here. 

There is an issue the way folder sharing is handled right now in the backend. We discussed it last night on Freenode and multiple people reproduced it on their setups.

**Comment by andryyy** [comment]
It is a shared namespace, not a real folder. SOGo still shows it as a folder. You can report that to SOGo.

**Comment by mkuron** [comment]
@evilstiefel, you need to click on the folder icon next to "Shared" to expand it to see the shared folders. If you click on "Shared", you get that error because SOGo doesn't know the difference between a folder and a namespace.

**Comment by andryyy** [comment]
Damn it. This was a strange problem related to inbox sharing. :/
