### ISSUE TITLE
Temporary link for creating a calendar entry

### ISSUE THREAD

**Issue by Choppel** [mailcow/mailcow-dockerized#5942]
### Summary

A customer of ours uses a software that lets him create a temporary link to his calendar for creating a single calendar entry. He gives this link to his customers so that they can create an appointment. Obviously the other calendar entries are not shown in full. The time is only occupied.

Is something like this possible with Mailcow / Sogo?

### Motivation

This could be used e.g. in dental offices for the patients to create appointments.

**Comment by mkuron** [comment]
This is a bit out of scope for Mailcow. You would have to connect an external service to your SOGo calendar via CalDAV, ideally using a separate application-specific password. I know there are a few commercial services (https://www.apptoto.com, https://calenso.com, https://simplymeet.me, ...) for this purpose, but a quick search on Github also revealed https://github.com/alextselegidis/easyappointments, which might be just what you need. Running it in an extra docker container should be easy.

**Comment by Choppel** [comment]
Thanks for the quick reply. I will give https://github.com/alextselegidis/easyappointments a shot.
