### ISSUE TITLE
Just a little something in the UI

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#5954]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Hi,

If you click on "Version -> 2026-06b" in debug, a new tab opens on Github + modal in the debug, this was not the case before, probably a bug crept in, not dramatic just wanted to mention it.
```

### Logs:

```plain text
NOT NECESSARY
```

### Steps to reproduce:

```plain text
NOT NECESSARY
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 20.04.5 LTS

### Server/VM specifications:

VM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.10.2 / v2.25.0

### mailcow version:

2026-06b

### Reverse proxy:

NO

### Logs of git diff:

```plain text
NOT NECESSARY
```

### Logs of iptables -L -vn:

```plain text
NOT NECESSARY
```

### Logs of ip6tables -L -vn:

```plain text
NOT NECESSARY
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT NECESSARY
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT NECESSARY
```

### DNS check:

```plain text
NOT NECESSARY
```

**Comment by DerLinkman** [comment]
Will be fixed with the next update
