### ISSUE TITLE
Cannot start mailcow anymore: ERROR: open /media/VirtualDisks/overlay/b45*520/lower-id

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#596]
Hello,

After update this morning (using the script), I cannot start mailcow-dockerized anymore. I get the following error:
ERROR: open /media/VirtualDisks/overlay/b4598f6b1b15ff48936a8abbc4679a761a0d3597ce431004e9a7f66e47268520/lower-id: no such file or directory

I tried to cleanup, update manually, but to no avail.

Do you know where this could come from?

Thanks!

**Comment by andryyy** [comment]
Can you please try and run `docker-compose down` before starting the update script?

Are these the only Docker containers? Then you may also try to stop and remove all running containers with...

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

**Comment by etique57** [comment]
Ok, the dockers restarted, but now my domain is gone... I hope I didn't lose my emails :dagger: 
Can I just recreate the domain and the mailbox ?

**Comment by andryyy** [comment]
You should not have lost any volumes. You did not run "down -v", did you? That would delete your volumes as well.

**Comment by etique57** [comment]
no, I did only the --remove orphans and the dangling stuff from the doc page.

And at a point I did a docker-compose --build (by mistake...)

I have backups (every 4hrs) so I'm no worried, but if I can avoid to go through the hassle... :D

**Comment by andryyy** [comment]
The dangling command would remove volumes as well, as long as the containers are not present. :/ I hope you did not lose data. I updated the docs.

**Comment by etique57** [comment]
Whoops. Then I lost everything since I moved to maildock a couple of months back. No big deal :)

I didn't backup the volumes (thought everything was stored in the maildock-dockerized). I'm still new to all of this...

Any way for me to copy my former maildir into one of the volumes directly? (found it :))

I added the volumes to my rsnapshot.

**Comment by etique57** [comment]
Ok, backup loaded.

Just wondering (sorry I'm very new to dockers), where can I specify where the vmail volume points? (I want to backup this one at the very least).

Thanks!
