### ISSUE TITLE
dovecot-mailcow (mailcow/dovecot:1.30) restarts every 7-10minutes

### ISSUE THREAD

**Issue by euDominic** [mailcow/mailcow-dockerized#5960]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Mailcow version 2024-06c
Architecture x86_64
Proxmox VM 12GB RAM 6vCPUs
Utilization ~17% CPU, 44% RAM

16.07.2024, 19:39:04 Dovecot -2 Health level: 17% (2/12)

I have the problem that the dovecot container restarts every 7 to 10 minutes.

---
1User Mailbox with ~40K mails
---

----
mailcow.conf
SKIP_LETS_ENCRYPT=y 
-----

ipV6= disabled

-----
ls -lha data/assets/ssl

total 20K
drwxr-xr-x 2 root root 4.0K Jul 16 17:35 .
drwxr-xr-x 8 root root 4.0K Jul  9 18:10 ..
-rw-r--r-- 1 root root 3.9K Jul 10 10:29 cert.pem
-rw-r--r-- 1 root root  424 Jul  9 18:10 dhparams.pem
-rw-r--r-- 1 root root  288 Jul 10 09:42 key.pem
------------


-----
docker exec -ti mailcowdockerized-dovecot-mailcow-1 ls -lha /var/run/

total 44K
drwxr-xr-x 1 root  root  4.0K Jul 16 19:42 .
drwxr-xr-x 1 root  root  4.0K Jul 16 18:57 ..
drwxr-xr-x 5 root  root  4.0K Jul 16 19:42 dovecot
drwxrwxrwt 2   999 sogo  4.0K Jul 16 18:57 mysqld
drwxr-xr-x 2 redis redis 4.0K Jun 27 11:22 redis
-rw-r--r-- 1 root  root     2 Jul 16 19:42 supervisord.pid
srwxr-xr-x 1 root  root     0 Jul 16 19:42 syslog-ng.ctl
-rw------- 1 root  root   16K Jul 16 19:42 syslog-ng.persist
-rw-r--r-- 1 root  root     4 Jul 16 19:42 syslog-ng.pid
----------
```

### Logs:

```plain text
docker compose logs -t dovecot-mailcow

----
dovecot-mailcow-1  | 2024-07-16 19:35:20,117 WARN received SIGTERM indicating exit request
dovecot-mailcow-1  | 2024-07-16 19:35:20,119 INFO waiting for processes, dovecot, syslog-ng to die
dovecot-mailcow-1  | Jul 16 19:35:20 bff1cf1ae9b6 syslog-ng[121]: syslog-ng shutting down; version='4.7.1'
dovecot-mailcow-1  | 2024-07-16 19:35:20,238 INFO stopped: syslog-ng (exit status 0)
dovecot-mailcow-1  | 2024-07-16 19:35:22,242 INFO stopped: dovecot (exit status 0)
dovecot-mailcow-1  | 2024-07-16 19:35:22,242 WARN received SIGQUIT indicating exit request
dovecot-mailcow-1  | 2024-07-16 19:35:22,243 WARN stopped: processes (terminated by SIGTERM)
dovecot-mailcow-1  | Uptime: 2285  Threads: 37  Questions: 167630  Slow queries: 0  Opens: 87  Open tables: 78  Queries per second avg: 73.361
dovecot-mailcow-1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow-1  |                                  Dload  Upload   Total   Spent    Left  Speed
100  115k  100  115k    0     0   321k      0 --:--:-- --:--:-- --:--:--  321k
dovecot-mailcow-1  | 20_blatspammer.cf
dovecot-mailcow-1  | 70_HS_body.cf
dovecot-mailcow-1  | 70_HS_header.cf
dovecot-mailcow-1  | 2024-07-16 19:35:24,610 INFO Set uid to user 0 succeeded
dovecot-mailcow-1  | 2024-07-16 19:35:24,612 INFO supervisord started with pid 1
dovecot-mailcow-1  | 2024-07-16 19:35:25,614 INFO spawned: 'processes' with pid 119
dovecot-mailcow-1  | 2024-07-16 19:35:25,616 INFO spawned: 'dovecot' with pid 120
dovecot-mailcow-1  | 2024-07-16 19:35:25,618 INFO spawned: 'syslog-ng' with pid 121
dovecot-mailcow-1  | Jul 16 19:35:25 bff1cf1ae9b6 syslog-ng[121]: syslog-ng starting up; version='4.7.1'
dovecot-mailcow-1  | Jul 16 19:35:25 bff1cf1ae9b6 dovecot: master: Dovecot v2.3.21 (47349e2482) starting up for imap, sieve, lmtp, pop3
```

### Steps to reproduce:

```plain text
.
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

DDebian 12

### Server/VM specifications:

12GB / 6cpu

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

Proxmox VM

### Docker version:

27.0.3

### docker-compose version or docker compose version:

2.28.1

### mailcow version:

2024-06c

### Reverse proxy:

HaProxy

### Logs of git diff:

```plain text
diff --git a/data/assets/ssl-example/cert.pem b/data/assets/ssl-example/cert.pem
index 96d16bec..95533232 100644
--- a/data/assets/ssl-example/cert.pem
+++ b/data/assets/ssl-example/cert.pem
@@ -1,19 +1,33 @@
 -----BEGIN CERTIFICATE-----
-MIIDBDCCAe6gAwIBAgIQeJMoL/3dxhxhT9EwuRTL/DALBgkqhkiG9w0BAQswEjEQ
-MA4GA1UEChMHbWFpbGNvdzAeFw0xNjEyMTMxMDExMDBaFw0xOTExMjgxMDExMDBa
-MC0xEDAOBgNVBAoTB21haWxjb3cxGTAXBgNVBAMTEG1haWwuZXhhbXBsZS5vcmcw
-ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRg0xT3At9DSb3H5OMp3K1
-MpXAgYyotSK6TS61fC0QEHy2fMXiws7Agcye6Ln7CG63Fe1eN2jkdlefy9xJivS8
-y5w0M8i168v5znzC8fnylL2iOiSYfK/B/oEqfU7YH4RcegO53oDDIUZmi4Frgnu7
-39VVOU1ZyHEVqGJ2H2aAIkoZRjGzumD9Ym4LWGidtKJzBgFt/qmhUeWXipM8w281
-XkQnJU79+x2ywnJSvEZ3r/ZVJC7kbjiVw+/k15k9Cxk6Ik8wmJ0X/+xWxoZomHQI
-1LM0VKAS/iaU95dn2bplvL6jTiiyWAbrMjSKs4XbPt/fIbOicNkj6+CFy0MVfyyH
-AgMBAAGjPzA9MA4GA1UdDwEB/wQEAwIAqDAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
-KwYBBQUHAwEwDAYDVR0TAQH/BAIwADALBgkqhkiG9w0BAQsDggEBAI/jBJa1P8nB
-eHUN5muQmjBVDVOYyWAAEapOe2HYsBcpjaB2H8Iw3DQzJtz6peYeYSCmHRVqFLCm
-VPrq36l9mPUotyPDPlQQAxCj9R2+WbGaJO+N/E1F8FQ94dr3jqwUyfjVPoqEjmIH
-NFkvbA0RJOeBm9oYGdhM0wjOBV9c9MTHFG82nQ/zQeTuPb7GXuKIOXYCxoLNOZMw
-UJ02Cqjv5ImrgOhcstAKX3Ip0urSvZUGvtPla4CGh+M6yDFJ08GzX6OiMIH207RW
-jAbUXXERSUv/7hysdDjGo5HZjCeMzVu9KAxoZXqnmvkk8g2swKWtWBRcoeU1VGx0
-Bx4Q4KMjuYQ=
+MIIFtTCCA52gAwIBAgIUZAUVM6mMdRfsbw0mrDQ1DTWpNdMwDQYJKoZIhvcNAQEL
+BQAwajELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05SVzEQMA4GA1UEBwwHV2lsbGlj
+aDEQMA4GA1UECgwHbWFpbGNvdzEQMA4GA1UECwwHbWFpbGNvdzEXMBUGA1UEAwwO
+bWFpbC5wdXJuZXIuZXUwHhcNMjQwNzA5MTYxMDQyWhcNMjUwNzA5MTYxMDQyWjBq
+MQswCQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMRAwDgYDVQQHDAdXaWxsaWNoMRAw
+DgYDVQQKDAdtYWlsY293MRAwDgYDVQQLDAdtYWlsY293MRcwFQYDVQQDDA5tYWls
+LnB1cm5lci5ldTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAO1fhRbG
+KhD6emlsucZMTr+kGlIzwEiRQ7I+J3rd2XylhhkP4kDnbClDaTyLjR7q2bFNbdxV
+Pe2mJm4wCeD+QD3iPvxgV9R3REGWOujKkTuMxkG8MPF/Gv5tWbVjwctvtQjhOCOt
+JCaU74e73+X09oGxLlCarIUa9QYR9EhsrU3w/OT4vR8vm8oOCkyerK5Yqb8AcXe7
+UanzW/bnkBwBEzTPbqsVU0fQ9Ec8ENWWBNo3TplshCzKuUkq+9i6+iwdSW5eJB3o
+Q75cpcj2pWRbpAKu89rNfsaiOmYnuDLmR/WiWCUGmgMqKdDL4nbdSQwOyNzFTSB+
+oV8nZqm6vWnVq2Zhi516ZQcgfGw1nSI+hK+HEIKnNmAO72+NUJ5/lhDLSsnmCaXq
```

diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf

index 63ce875d..bdcc503d 100644
--- a/data/conf/postfix/master.cf
+++ b/data/conf/postfix/master.cf
@@ -11,6 +11,7 @@ smtpd      pass  -       -       n       -       -       smtpd
 # smtpd tls-wrapped (smtps) on 465/tcp
 # TLS protocol can be modified by setting smtps_smtpd_tls_mandatory_protocols in extra.cf
 smtps    inet  n       -       n       -       -       smtpd
+  -o smtpd_upstream_proxy_protocol=haproxy
   -o smtpd_tls_wrappermode=yes
   -o smtpd_client_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
   -o smtpd_tls_mandatory_protocols=$smtps_smtpd_tls_mandatory_protocols
diff --git a/data/conf/rspamd/custom/global_mime_from_whitelist.map b/data/conf/rspamd/custom/global_mime_from_whitelist.map
index 3c872889..d286a810 100644
--- a/data/conf/rspamd/custom/global_mime_from_whitelist.map
+++ b/data/conf/rspamd/custom/global_mime_from_whitelist.map
@@ -1 +1,3 @@
-# /.+example\.com/i
+# /.+example\.com/i^M
+/.+pmg\.dmz.lan/i^M
+/.+purner\.eu/i
diff --git a/data/conf/rspamd/local.d/antivirus.conf b/data/conf/rspamd/local.d/antivirus.conf
index c8d31d1e..1908ba9b 100644
--- a/data/conf/rspamd/local.d/antivirus.conf
+++ b/data/conf/rspamd/local.d/antivirus.conf
@@ -7,5 +7,5 @@ clamav {
   type = "clamav";
   log_clean = true;
   servers = "clamd:3310";
-  max_size = 20971520;
+  max_size = 52428800;
 }
diff --git a/data/conf/rspamd/local.d/external_services.conf b/data/conf/rspamd/local.d/external_services.conf
index 2b091ff2..dcc4fe3e 100644
--- a/data/conf/rspamd/local.d/external_services.conf
+++ b/data/conf/rspamd/local.d/external_services.conf
@@ -6,7 +6,7 @@ oletools {
   # mime-part regex matching in content-type or filename
   # block all macros
   extended = true;
-  max_size = 3145728;
+  max_size = 52428800;
   timeout = 20.0;
   retransmits = 1;
 }
diff --git a/data/conf/rspamd/local.d/greylist.conf b/data/conf/rspamd/local.d/greylist.conf
index c43c907f..6b2ed8b8 100644
--- a/data/conf/rspamd/local.d/greylist.conf
+++ b/data/conf/rspamd/local.d/greylist.conf
@@ -2,3 +2,4 @@ whitelisted_ip = "http://nginx:8081/forwardinghosts.php";
 ipv4_mask = 24;
 ipv6_mask = 64;
 message = "Greylisted, please try again later";
+enabled = false;
diff --git a/data/conf/rspamd/local.d/options.inc b/data/conf/rspamd/local.d/options.inc
index 105bbdcd..89c4b4a5 100644
--- a/data/conf/rspamd/local.d/options.inc
+++ b/data/conf/rspamd/local.d/options.inc
@@ -7,3 +7,4 @@ disable_monitoring = true;
 # instead of silently accepting the message without further processing.
 soft_reject_on_timeout = true;
 local_addrs = /etc/rspamd/custom/mailcow_networks.map;
+max_message = 50Mb
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index d398eb05..b4e7b95c 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );

-    WOWorkersCount = "20";
+    WOWorkersCount = "120";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
@@ -50,7 +50,7 @@

     SOGoMaximumPingInterval = 3540;

-    SOGoInternalSyncInterval = 45;
+    SOGoInternalSyncInterval = 30;
     SOGoMaximumSyncInterval = 3540;

     // 100 seems to break some Android clients
diff --git a/data/conf/unbound/unbound.conf b/data/conf/unbound/unbound.conf
index 27110c04..10beed8a 100644
--- a/data/conf/unbound/unbound.conf
+++ b/data/conf/unbound/unbound.conf
@@ -4,7 +4,7 @@ server:
   interface: ::0
   logfile: /dev/console
   do-ip4: yes
-  do-ip6: yes
+  do-ip6: no
   do-udp: yes
   do-tcp: yes
   do-daemonize: no
@@ -43,3 +43,8 @@ remote-control:
   server-cert-file: "/etc/unbound/unbound_server.pem"
   control-key-file: "/etc/unbound/unbound_control.key"
   control-cert-file: "/etc/unbound/unbound_control.pem"
+
+#forward-zone:
+#  name: "."
+#  forward-addr: 127.0.0.11
+#  forward-addr: 172.30.30.1
diff --git a/data/web/inc/vars.inc.php b/data/web/inc/vars.inc.php
index 830b2180..ddb5a5a7 100644
--- a/data/web/inc/vars.inc.php
+++ b/data/web/inc/vars.inc.php
@@ -16,7 +16,7 @@ $database_pass = getenv('DBPASS');
 $database_name = getenv('DBNAME');

 // Other variables
-$mailcow_hostname = getenv('MAILCOW_HOSTNAME');
+$mailcow_hostname =  getenv('MAILCOW_HOSTNAME');
 $default_pass_scheme = getenv('MAILCOW_PASS_SCHEME');

 // Autodiscover settings
diff --git a/docker-compose.yml b/docker-compose.yml
index ece85026..43c9c45b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -646,7 +646,7 @@ networks:
     driver: bridge
     driver_opts:
       com.docker.network.bridge.name: br-mailcow
-    enable_ipv6: true
+    enable_ipv6: false

----

diff --git a/data/conf/postfix/master.cf b/data/conf/postfix/master.cf

 # DO NOT EDIT ANYTHING BELOW #
 # Overrides #
+
+postscreen_dnsbl_sites = wl.mailspike.net=127.0.0.[18;19;20]*-2
+  hostkarma.junkemailfilter.com=127.0.0.1*-2
+  list.dnswl.org=127.0.[0..255].0*-2
+  list.dnswl.org=127.0.[0..255].1*-4
+  list.dnswl.org=127.0.[0..255].2*-6
+  list.dnswl.org=127.0.[0..255].3*-8
+  ix.dnsbl.manitu.net*2
+  bl.spamcop.net*2
+  bl.suomispam.net*2
+  hostkarma.junkemailfilter.com=127.0.0.2*3
+  hostkarma.junkemailfilter.com=127.0.0.4*2
+  hostkarma.junkemailfilter.com=127.0.1.2*1
+  backscatter.spameatingmonkey.net*2
+  bl.ipv6.spameatingmonkey.net*2
+  bl.spameatingmonkey.net*2
+  b.barracudacentral.org=127.0.0.2*7
+  bl.mailspike.net=127.0.0.2*5
+  bl.mailspike.net=127.0.0.[10;11;12]*4
+  zen.spamhaus.org=127.0.0.[10;11]*8
+  zen.spamhaus.org=127.0.0.[4..7]*6
+  zen.spamhaus.org=127.0.0.3*4
+  zen.spamhaus.org=127.0.0.2*3
+
+# User Overrides
+myhostname = mailcow.purner.eu
+mynetworks = 127.0.0.0/8 172.22.1.0/24 172.30.30.15/32
+
+
+smtp_tls_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+smtp_tls_mandatory_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+smtpd_tls_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+lmtp_tls_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+lmtp_tls_mandatory_protocols = !SSLv2, !SSLv3,!TLSv1,!TLSv1.1
+# SSL/TLS supported ciphers
+smtp_tls_ciphers = high
+smtp_tls_mandatory_ciphers = high
+smtpd_tls_ciphers = high
+smtpd_tls_mandatory_ciphers = high
+tls_high_cipherlist = tls_high_cipherlist = ECDHE-ECDSA-AES256-GCM-SHA384:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES256-GCM-SHA384:TLS_AES_256_GCM_SHA384:ECDHE-RSA-CHACHA20-POLY1305:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:TLS_AES_128_GCM_SHA256
+smtpd_tls_eecdh_grade = ultra
+
+postscreen_upstream_proxy_protocol = haproxy
+proxy_interfaces = 172.30.30.1
+#smtpd_upstream_proxy_protocol = haproxy
+
+
+message_size_limit = 52428800
+smtpd_banner = cm194-59.liwest.at ESMTP $mail_name
+
+
+smtp_address_preference = ipv4
+inet_protocols = ipv4

-------
diff --git a/data/conf/dovecot/dovecot.conf  b/data/conf/dovecot/dovecot.conf 

index df1aa1e1..035d0809 100644
--- a/data/conf/clamav/clamd.conf
+++ b/data/conf/clamav/clamd.conf
@@ -38,7 +38,7 @@ HeuristicScanPrecedence yes
 ScanHTML yes
 ScanArchive yes
 MaxScanSize 50M
-MaxFileSize 25M
+MaxFileSize 50M
 MaxRecursion 5
 MaxFiles 200
 Bytecode yes
diff --git a/data/conf/dovecot/dovecot.conf b/data/conf/dovecot/dovecot.conf
index c230c349..805e7316 100644
--- a/data/conf/dovecot/dovecot.conf
+++ b/data/conf/dovecot/dovecot.conf
@@ -10,8 +10,11 @@
 auth_mechanisms = plain login
 #mail_debug = yes
 #auth_debug = yes
-#log_debug = category=fts-flatcurve # Activate Logging for Flatcurve FTS Searchings
+#log_debug =  category=fts-flatcurve # Activate Logging for Flatcurve FTS Searchings
 log_path = syslog

------

### Logs of iptables -L -vn:

```plain text
bash: ip6tables: command not found
```

### Logs of ip6tables -L -vn:

```plain text
bash: ip6tables: command not found
```

### Logs of iptables -L -vn -t nat:

```plain text
bash: ip6tables: command not found
```

### Logs of ip6tables -L -vn -t nat:

```plain text
bash: ip6tables: command not found
```

### DNS check:

```plain text
docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254

104.18.32.7
172.64.155.249
```

**Comment by DerLinkman** [comment]
Can you show me the watchdog logs?

`docker compose logs --tail=200 watchdog-mailcow`

**Comment by euDominic** [comment]
I switched from Debian 12 to Ubuntu and now everything works.
