### ISSUE TITLE
Feature Request: Implement Password Reset Functionality for Mailcow (paid)

### ISSUE THREAD

**Issue by youth-foundation-bw** [mailcow/mailcow-dockerized#5961]
### Summary

I am working on a project that requires a "Forgot Password" feature for Mailcow. This feature should adhere to the pre-defined password policy. Specifically, each mailbox should have a new field for an alternative email address. When a user clicks "Forgot Password," a reset link should be sent to this alternative email address.

### Motivation

Context:
We are a non-profit foundation based in Southern Germany, planning to use Mailcow for a school project. We are willing to compensate for this development work and believe that this feature will be highly beneficial for Mailcow in the future.

Benefits:

- Enhances security and user experience by providing a robust password recovery option.
- Increases Mailcow's usability in educational and non-profit organizations.

We appreciate your consideration of this feature request and look forward to potential collaboration.

Thank you.

### Additional context

Details:

- New Field Requirement: Add an alternative email address field to each mailbox.
- Password Reset Mechanism: Upon clicking "Forgot Password," a reset link should be sent to the alternative email address.
- Password Policy Compliance: Ensure the new password meets the pre-defined password policy criteria.

**Comment by DerLinkman** [comment]
Hi,

we were thinking about this feature a few times as i read this here and there... but the feature was more a feature for the long run, not for the near future (planned by us).

However, if you want to sponsor this development, we will highly appreciate this!

Can you write us a email to `info at servercow.de` <-- written like this to prevent crawlers...

Then we can discuss and plan the development of this feature. I think it is also a nice addition as many more people are wishing this!

**Comment by DerLinkman** [comment]
The feature will be part of 2024-08 for everyone! Thanks to @youth-foundation-bw for this

**Comment by youth-foundation-bw** [comment]
thank you @DerLinkman for this feature!
