### ISSUE TITLE
Docs: show demo information

### ISSUE THREAD

**Issue by a0m0rajab** [mailcow/mailcow-dockerized#5965]
### Summary

I wanted to try mailcow and entered the website, then went to the demos immediately, I faced the issue of not having the username and password, which required me to dig a little bit in the code base to find them: 

https://github.com/mailcow/mailcow-dockerized/blob/987a027339e1b91e75df608252d1e61d33803a04/generate_config.sh#L226-L232C24

it would be great if it was written in the login page somewhere or prefilled. 

### Motivation

Think about someone who wants a quick overview about the product, what would you do to make it easier for them?

**Comment by DerLinkman** [comment]
@ntimo Possible to add into the Ansible Playbook?

**Comment by ntimo** [comment]
@DerLinkman We currently don't have a docs page that contains the demo user names and passwords. If we could add one, I can create the link on the demo login pages :)

**Comment by DerLinkman** [comment]
We have...

https://docs.mailcow.email/#interested-try-it-out-right-away

**Comment by ntimo** [comment]
Added, will be live when the demo is next rebuild.

**Comment by DerLinkman** [comment]
Merci!
