### ISSUE TITLE
Adding server_name aka using nginx as a reverse proxy

### ISSUE THREAD

**Issue by JOduMonT** [mailcow/mailcow-dockerized#597]
Hi everyone;

in the section : third_party
I saw the explaination how to add portainer and roundcube
and I was wondering if it's possible to explain to me:
how to add a generic domain or subdomain; something like by adding a

server {
server_name mywebsite.com;
...
}

which I will declare inside nginx with this mount : ./data/conf/nginx/:/etc/nginx/conf.d/

Regards!

**Comment by mkuron** [comment]
You can modify the files in ./data/conf/nginx if you want to. It is not recommended though -- the better variant is to set up a reverse proxy yourself which then defers requests to either Mailcow's nginx or your own additional services.

**Comment by JOduMonT** [comment]
you means as mailcow mention here >> https://mailcow.github.io/mailcow-dockerized-docs/install/  
```
4. Change configuration if you want or need to.
 
 nano mailcow.conf
 
 If you plan to use a reverse proxy, you can, for example, bind HTTPS to 127.0.0.1 on port 8443 and HTTP to 127.0.0.1 on port 8080.

```
