### ISSUE TITLE
Send a copy of outgoing emails in Sent folder for certain accounts

### ISSUE THREAD

**Issue by albertodega** [mailcow/mailcow-dockerized#598]
Hi guys, i'm trying to setup postfix to send a copy of an outgoing mail to the Sent folder of the sender account.
to do this, i've added the following line in main.cf:
`sender_bcc_maps = hash:/opt/postfix/conf/sender_bcc`
with the stated file added like this:
`user@example.com user+sent@example.com`
followed by 
`postmap /opt/postfix/conf/sender_bcc`
in the container to update the hash.

i'm facing 2 problems:

1. When a mail arrives from external address to user+sent@example.com it is saved in a subfolder of inbox instead of the sent folder itself
2. when a mail is sent from user@example.com it is actually bcced to user@example.com, ignoring the +sent statement which should at least copy the mail in the sent folder inside inbox

how could i acheive my objective?
thank you in advance!

**Comment by andryyy** [comment]
Hi, the first issue is solved by changing `data/conf/dovecot/sieve_after` to...

```
require "fileinto";
require "mailbox";
require "variables";
require "subaddress";
require "envelope";

if header :contains "X-Spam-Flag" "YES" {
  fileinto "Junk";
}

if allof (
  envelope :detail :matches "to" "*",
  header :contains "X-Moo-Tag" "YES"
  ) {
  set :lower :upperfirst "tag" "${1}";
  if mailboxexists "${1}" {
    fileinto "${1}";
  } else {
    fileinto :create "${tag}";
  }
}
```
... and restarting Dovecot with `docker-compose restart dovecot-mailcow`.

The second would need some debugging. :/

**Comment by albertodega** [comment]
Thank you very much andryyy, is it possible that this chain is called only for mails coming from outside the domain? how could i apply this also for mails sent from the mailserver itself?

**Comment by stAn47** [comment]
i am indeed trying to do the same thing - i.e. the use-case is: a manager wants to have a control of some employees that are sending outgoing emails to their clients and he wants to see the copy of the outgoing email within a separate mailbox. 

mailcow configuration allows us to set up sender bcc per whole domain, but it does not seem to allow this per mailbox. (i.e. managers outgoing emails should not be stored in common mailbox, other mailboxes listed should allow sender bcc)

is there any way to get it done via mailcow configuration, or should we rather adjust configs via extra.conf ? 

thanks, best regards, stan
