### ISSUE TITLE
nginx Container Error after update via update.sh

### ISSUE THREAD

**Issue by denis-ev** [mailcow/mailcow-dockerized#599]
Hey @andryyy,
just updated via the update.sh and everything works, but the websites.

this one container throws an error.
$docker ps
nginx:mainline-alpine   "/bin/sh -c 'envsu..."   22 seconds ago       Restarting (1) 5 seconds ago

this is part of the log, just repeating this one line
$docker logs mailcowdockerized_nginx-mailcow_1
2017/09/14 21:46:29 [emerg] 8#8: unknown "connection_upgrade" variable
nginx: [emerg] unknown "connection_upgrade" variable

Hope there is a fix, soon.

Thank you for the amazing work.

Freundliche Grüße,
Denis

**Comment by andryyy** [comment]
Hi, you need to remove that line from your Nginx site. I guess that's coming from portainer.

**Comment by denis-ev** [comment]
Worked, thanks.
