### ISSUE TITLE
No default admin is created anymore

### ISSUE THREAD

**Issue by evilstiefel** [mailcow/mailcow-dockerized#600]
Commit 71070fb unfortunately breaks creating a default admin when the table is empty.

`SELECT 'admin', '{SSHA256}K8eVJ6YsZbQCfuJvSUbaQRLr0HPLz5rC9IAp0PAFl0tmNDBkMDc0NDAyOTAxN2Rk', 1, NOW(), NOW(), 1 FROM admin;`

The previous command just returns an empty set, so the insert doesn't actually do anything.

**Comment by andryyy** [comment]
Thanks, fixed. 👍
