### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by hivokas** [mailcow/mailcow-dockerized#601]
I want to configure several domains in mailcow.
For example, I have:
- server with IP 1.2.3.4, mailcow, website on this server with domain example.com and e-mail with mask like *@example.com
- server with IP 2.3.4.5, website on this server with domain example2.com

What DNS records should I type for second domain if I have site on main domain (example2.com) and want to have e-mail mask like *@example2.com (mailcow is on another one server)?

**Comment by Avalarion** [comment]
Hey @hivokas,

you need to to set the [MX Record](https://en.wikipedia.org/wiki/MX_record) of your second Domain to your first Domain. Important: Don't set an IP there, only this format is allowed:

`${PRIORITY} ${HOSTNAME}.`

So for example

`10 example.com.`

The last "." is important!

Also you should set the mail subdomain of the second Domain to point onto your mailcow server.

Greetings from Germany,

Bastian

**Comment by hivokas** [comment]
@Avalarion, thanks!
