### ISSUE TITLE
No Agenda/Addressbook created in SOGO. Quota not in Sync with IMAP

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#602]
Hello,

After my botched upgrade, I'm facing new issues:
- I have not calendar created for my users, and when I try to create one, I get a SOGO error (but nothing in the log that I can see)
- probably related, in SOGO the addressbook page is completely white (though ther are things behind).
- maybe not unrelated, I moved my complete backup maildir directly in the vmail-1 volume, but the SOGo quota is not showing the real number

It's probably a database problem, any clue how I can reinitialize it? Or just reinitialise SOGo?

Thanks!

**Comment by andryyy** [comment]
Can you update and try again, please?

**Comment by andryyy** [comment]
Ah, forgot the quota part: `docker-compose exec dovecot-mailcow doveadm quota recalc -A`

**Comment by etique57** [comment]
Hello Andry,

Thanks for your feedback.

I did try to update again (using the script) when I wrote the issue a few hours agoi, you think I need to redo it?

I'll do the command.

Thanks!
Etienne

**Comment by andryyy** [comment]
Yes, just fixed it.

**Comment by etique57** [comment]
Ok, thanks.

I just did, but unfortunately the calendar is still not possible to create.

**Comment by andryyy** [comment]
Open your mailcow UI, log out and wait for it to init the db.

**Comment by etique57** [comment]
It's back indeed, thanks!
