### ISSUE TITLE
mysqladmin is deprecated in dovecot docker-entrypoint use mysql-admin

### ISSUE THREAD

**Issue by bersierj** [mailcow/mailcow-dockerized#6023]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
mysqladmin command is deprecated in dovecot docker-entrypoint.sh
```

### Logs:

```plain text
dovecot-mailcow-1     | mysqladmin: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-admin' instead
dovecot-mailcow-1     | Waiting for database to come up...
```

### Steps to reproduce:

```plain text
restart dovecot and see logs
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

rocky linux 9

### Server/VM specifications:

16 GB / 4 Core

### Is Apparmor, SELinux or similar active?

yes

### Virtualization technology:

kvm

### Docker version:

27.1.2

### docker-compose version or docker compose version:

v2.29.1

### mailcow version:

2024-08

### Reverse proxy:

N/A

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by DerLinkman** [comment]
Yes i saw this in my tests regarding the phpfpm Alpine issue too, but was not expecting this in dovecot already...
