### ISSUE TITLE
Update Mialcow

### ISSUE THREAD

**Issue by tutods** [mailcow/mailcow-dockerized#6024]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Hi everyone
I'm trying to update my mailcow, but isn't working
```

### Logs:

```plain text
Syntax error: "(" unexpected (expecting "}")
```

### Steps to reproduce:

```plain text
1. run `sh /opt/mailcow-dockerized/update.sh`
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Debian 12

### Server/VM specifications:

4

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

none

### Docker version:

27.1.2

### docker-compose version or docker compose version:

27.1.2

### mailcow version:

2022-07

### Reverse proxy:

Traefik

### Logs of git diff:

```plain text
none
```

### Logs of iptables -L -vn:

```plain text
none
```

### Logs of ip6tables -L -vn:

```plain text
none
```

### Logs of iptables -L -vn -t nat:

```plain text
none
```

### Logs of ip6tables -L -vn -t nat:

```plain text
none
```

### DNS check:

```plain text
none
```

**Comment by DerLinkman** [comment]
Can you run the script with bash -x again?

**Comment by tutods** [comment]
It works, thanks 🙏

**Comment by DerLinkman** [comment]
bash -x is a debug command... so you changed something which maked it working. Bash -x was not the resolution of it.
