### ISSUE TITLE
how to build mail sink "noreply" account with mailcow?

### ISSUE THREAD

**Issue by cklabautermann** [mailcow/mailcow-dockerized#604]
I have been using db-backed mailing in unix/linux Systems for quite some years - unfortunately none of them had an answer to this. I want to have an email address acting as a mail sink.

Is there an answer to my question in mailcow?

Sorry, I know this issue belongs more into a/the forum, but I didn´t receive an answer to my question there.

**Comment by andryyy** [comment]
Hi,
I recently added a null receiver to the Postfix image. You can go ahead and create an alias with a goto "null@MAILCOW_HOSTNAME" or give me a few minutes to implement it in the UI.

**Comment by cklabautermann** [comment]
I choose the 2nd option - thanks ;-)

**Comment by andryyy** [comment]
It is hopefully implemented. :P

**Comment by cklabautermann** [comment]
Thanks, but I´m not sure if I did it right. 
I chose the window for aliases and inserted an email alias address and checked the button to discard emails to the alias. When I do that the target address window becomes grey but still seems to demand content. However I can´t add this alias.

![2017-09-15 12_56_56-mailcow ui](https://user-images.githubusercontent.com/25175654/30479445-950938a4-9a15-11e7-9599-dbd5b4cbd8da.png)

**Comment by andryyy** [comment]
It is possible that you still have a cached api.js. Can you clear your cache?

**Comment by cklabautermann** [comment]
Sorry, don´t know how to clear the cache...I simply rebooted the machine ;-)
Unfortunately this doesn´t seem to be enough, as the behaviour didn´t change...
Can you please tell me how to clear the cache?

**Comment by andryyy** [comment]
Your browser cache. ;-)

**Comment by cklabautermann** [comment]
Oh! That did the trick! It´s working :-)
Thanks a lot!
