### ISSUE TITLE
Creating additional docker containers: e.g. Reverse Proxy - General questions

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#605]
Hi!
Currently I'm running mailcow 0.14 in LXC with a dedicated DB (MariaDB) in another LXC.
I'm considering to migrate to mailcow-dockerized.
However, I need to add another service in order to have a working environment: Reverse Proxy.

Question:
If I want to run this service in a docker container, what is the best approach for the deployment?
Installing Debian (via deboostrap) and install the software (=HAProxy)?
Or simply setup a container with HAProxy only, means no Debian?
How do you setup mailcow-dockerized containers? Is there a "Debian layer" inside every container?

THX

**Comment by mkuron** [comment]
> However, I need to add another service in order to have a working environment: Reverse Proxy.

This is not a Mailcow-specific question, so it's probably best asked elsewhere. HAProxy, Nginx and Apache all provide official docker images, which you could use for that purpose.

> How do you setup mailcow-dockerized containers? Is there a "Debian layer" inside every container?

Some of the containers run their services on top of a Debian userland, while most now use Alpine Linux instead.
