### ISSUE TITLE
Changing subdomain

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#606]
When I was setting up mailcow, I didn't intend to use it as my main email server straightaway, so I set it up on "mail2.mydoma.in". Since then, I've scrapped my old email server which was on "mail.mydoma.in".

I'd like to change the subdomain for mailcow, so its on "mail.mydoma.in".

What would be the procedure for doing this properly?

**Comment by andryyy** [comment]
Run `docker-compose down`, change the hostname in in `mailcow.conf`, run `docker-compose up -d`. 👍

**Comment by MrSuttonmann** [comment]
That's great! Thanks
