### ISSUE TITLE
Contactform or Contactlink on start page of webinterface

### ISSUE THREAD

**Issue by mamair** [mailcow/mailcow-dockerized#6069]
### Summary

Include a contact form to mailcow webinterface or a link to a contact-page so that requests relating the mailserveradmin can be done. A big telecom company in germany requires this, to set back a "bad reputation" of the mailserver.

### Motivation

A big telekom company refused to receive mails from my mailcow server beause of "bad reputation". There was a mail to set back the "bad reputation". I got a answer, that they reset bad reputation only if there is a contact form on my mailserver or a link to a webpage with contact form to contact the server administrator.

### Additional context

Vielen Dank für Ihre Nachricht.

Von der genannten IP Nummer war lange Zeit keine Aktivität bei uns
feststellbar. Aus Sicherheitsgründen nehmen unsere Systeme von solchen
IP Nummern erst nach Prüfung und Reset der Reputation E-Mails entgegen.

Voraussetzung für eine Rücksetzung der Reputation ist eine
Konfiguration, die sich nach den in unserer "Postmaster-FAQ"(*)
beschrieben Punkten richtet. Bitte beachten Sie dort den Abschnitt 4.1
("Voraussetzungen für einen reibungslosen Zugang zu unseren
Mail-Exchanges").

Für "(http(s)://)(mail.)aay.at" ist dies bisher leider noch
nicht gegeben. Eine Webweiterleitung oder ein Link von dort zu einer
Website mit entsprechend direkter Kontaktmöglichkeit zur für den Versand
von E-Mail von diesem System verantwortlichen Person wäre hierfür
ausreichend, damit diese im Störungs- oder Missbrauchsfall unmittelbar
erreichbar wäre.

(*) [<https://postmaster.t-online.de/#t4>](https://postmaster.t-online.de/#t4)

Mit freundlichen Grüßen
Andreas Kunz

Deutsche Telekom AG
E-Mail Engineering
Deutsche-Telekom-Allee 9
D-64295 Darmstadt
E-Mail: [tosa@rx.t-online.de](mailto:tosa@rx.t-online.de)
[www.telekom.de](http://www.telekom.de/)

Guten Tag,

eine Mail via bcc an ca. 100 Emfpänger (Mitglieder) kam nicht an wegen folgender Rückmeldung:

[<peter.smets@t-online.de>](mailto:peter.smets@t-online.de): host mx00.t-online.de[194.25.134.8] refused to talk
    to me: 554 IP=95.216.112.3 - None/bad reputation. Ask your postmaster for
    help or to contact [tobr@rx.t-online.de](mailto:tobr@rx.t-online.de) for reset. (NOWL)

Bitte um  Korrektur bzw. Aufnahme in eine Whitelist oder was auch immer, damit unsere Mails an unser Mitglied zugestellt werden kann. Bzw. um Rückmeldung, was bei unserem DNS oder was auch immer korrigiert werden könnte.

mfg

Martin Mair

**Comment by apio-sys** [comment]
You could customize that in System > Configuration > Options > Customize where there are options to change texts, help text, footer, etc.

**Comment by DerLinkman** [comment]
Won't add this. Just like @apio-sys said use the Customize function to create a imprint on your own.
