### ISSUE TITLE
Apple mail configuration guide

### ISSUE THREAD

**Issue by rkcreation** [mailcow/mailcow-dockerized#6086]
### Summary

In configuration guide for Apple Mail, a step is missing : after opening .mobileconfig, system needs an extra step.

### Motivation

Better user configuration guides

## After .mobileconfig download

1. Double click on the .mobileconfig file to begin installation.  A notification will appear stating to open System Preferences to install the Profile.
2. Open System Settings
  a. In the left pane, click Privacy & Security
  b. In the right pane, scroll down to the Others section
  c. Click the Profiles option
3. In the left pane, ensure the "EMAIL_ADDRESS Profile" (the name of the Profile may differ) is selected under the "Downloaded" section.  From the right hand pane, you can review the configurations that are contained in the Profile.  After reviewing the configurations, click the indicated "Install" button in the right pane.
4. Next a prompt confirming the Profile install will appear, select "Continue" to install it.
5. Next a prompt requesting the authentication credentials for your email will appear.
  a. For the username, enter your email
  b. For the password, enter the password associated with your email account
6. (Optional) A final prompt will appear asking for local administrator credentials to be able to install the Profile.  Enter the required credentials and click OK.

**Comment by pinpolhoxx** [comment]
download
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by MAGICCC** [comment]
Maybe you can create a PR in the https://github.com/mailcow/mailcow-dockerized-docs repo

**Comment by DerLinkman** [comment]
Wrong repo
