### ISSUE TITLE
Support OAuth2.0 for POP, IMAP and SMTP authentication

### ISSUE THREAD

**Issue by kvdb** [mailcow/mailcow-dockerized#6088]
### Summary

Another step in the evolution of authentication methods around POP, IMAP and SMTP is pushed by at least Google and Microsoft. It'd be great if mailcow also supported this feature of authenticating these protocols using OAuth2.

### Motivation

- Microsoft is [deprecating](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online) SMTP Auth in september 2025. They link to a [talk](https://www.youtube.com/watch?v=Db_OYLXJQF4&list=PLxdTT6-7g--2POisC5XcDQxUXHhWsoZc9&index=4) for the reasoning behind this.
- Google is [also pushing](https://developers.google.com/gmail/imap/xoauth2-protocol) XOAUTH2 as the authentication mechanism for their POP, IMAP and SMTP connections.

I'm not a security expert, but I assume they would have good reasons for it.

### Additional context

There has already been a [forum post](https://github.com/mailcow/mailcow-dockerized/issues/4509) on this topic in a context of forwarding.

**Comment by DerLinkman** [comment]
If Dovecot and Postfix support this, sure but they don't right know. Both have to, not only one part!

**Comment by kvdb** [comment]
I see.

Just in case it'll be reopened at some point in the future, I found information that looks like [both](https://documentation.open-xchange.com/7.10.4/middleware/mail/dovecot/oauth_2.0_with_postfix_and_dovecot.html 
) projects [support](https://doc.dovecot.org/main/core/config/auth/databases/oauth2.html) it.

**Comment by DerLinkman** [comment]
Maybe but it requires the whole mailcow project basically to be redeveloped in case of auth. We can add this onto our sponsored goals, but that will not be done in the near future by two people only under respecting all current mailcow users :)

**Comment by roswitina** [comment]
I have used oauth2_imap for Micorosft accounts. The complete instructions can be found here.

`https://imapsync.lamiral.info/oauth2/oauth2_imap/README_oauth2.txt`

 I entered the additional data required for retrieval in the Mailcow web interface. I also created a new cron job that renews the token(s) every 30 minutes. The retrieval of emails now works.

**### In a short summary, this is how I proceeded:**

Download the file “oauth2_imap.zip” from `https://imapsync.lamiral.info/oauth2/`

After unpacking the ZIP file, I ran a first test under Windows with the command 

oauht2_imap.exe <mail address> 

made. This opens a Microsoft login page in the browser. After logging in with the user data of the mail address, you are asked whether you want to give access to the Thunderbird app (the script identifies itself as such). If you confirm this, the first token is generated and saved. This must be done once for each e-mail address.

In Linux, I have created my Mailcow config files in` /opt/mailcow-dockerized` and all further details refer to this directory.

In the directory /opt/mailcow-dockerized/data/conf/dovecot/ I have unpacked the ZIP file oauth2_imap.zip again. I then copied the opposing token files (in the directory of the same name) from the Windows computer to the Linux computer in the same folder.

In “Edit Sync Jobs” I entered the following additional parameter under Custom Parameters

`--oauthaccesstoken1=/etc/dovecot/oauth2_imap/tokens/oauth2_tokens_real-mailadress.txt`

(The specified path must be accessible within the container and is therefore written as such. It can be accessed externally under` /opt/mailcow-dockerized/data/conf/dovecot/`)

Create a Cron.sh in the oauth2_imap directory with the following content:

```
#!/bin/bash
# Renewal of the token
cd /opt/mailcow-dockerized/data/conf/dovecot/oauth2_imap/
#./oauth2_imap real-mailaddress
./oauth2_imap real-mailadress1 >/dev/null 2>&1
./oauth2_imap real-mailadress2 >/dev/null 2>&1
```

`chmod +x cron.sh`

Then just crontab -e and insert the following content:

`*/30 * * * * * /opt/mailcow-dockerized/data/conf/dovecot/oauth2_imap/cron.sh >/dev/null 2>&1`

That's actually it ;-)

**Comment by DatNoHand** [comment]
> Maybe but it requires the whole mailcow project basically to be redeveloped in case of auth. We can add this onto our sponsored goals, but that will not be done in the near future by two people only under respecting all current mailcow users :)

Can you provide any information on what happened with this announcement?: https://mailcow.email/posts/2023/mailcow-idp/
The feature is in nightly since 2023. Do you know when it will reach prod? @DerLinkman

When this feature reaches prod the whole auth flow would be oauth. I assume that then the oauth token could be used for postfix and dovecot -> not so many problems after all

**Comment by DerLinkman** [comment]
Nothing, it's still in development. But still needs testing.

As we don't know how long it will still take, we don't give a ETA anymore.

**Comment by AnthonyLloydDotNet** [comment]
> I have used oauth2_imap for Micorosft accounts. The complete instructions can be found here.
> 
> `https://imapsync.lamiral.info/oauth2/oauth2_imap/README_oauth2.txt`
> 
> I entered the additional data required for retrieval in the Mailcow web interface. I also created a new cron job that renews the token(s) every 30 minutes. The retrieval of emails now works.
> 
> **### In a short summary, this is how I proceeded:**
> 
> Download the file “oauth2_imap.zip” from `https://imapsync.lamiral.info/oauth2/`
> 
> After unpacking the ZIP file, I ran a first test under Windows with the command
> 
> oauht2_imap.exe
> 
> made. This opens a Microsoft login page in the browser. After logging in with the user data of the mail address, you are asked whether you want to give access to the Thunderbird app (the script identifies itself as such). If you confirm this, the first token is generated and saved. This must be done once for each e-mail address.
> 
> In Linux, I have created my Mailcow config files in` /opt/mailcow-dockerized` and all further details refer to this directory.
> 
> In the directory /opt/mailcow-dockerized/data/conf/dovecot/ I have unpacked the ZIP file oauth2_imap.zip again. I then copied the opposing token files (in the directory of the same name) from the Windows computer to the Linux computer in the same folder.
> 
> In “Edit Sync Jobs” I entered the following additional parameter under Custom Parameters
> 
> `--oauthaccesstoken1=/etc/dovecot/oauth2_imap/tokens/oauth2_tokens_real-mailadress.txt`
> 
> (The specified path must be accessible within the container and is therefore written as such. It can be accessed externally under` /opt/mailcow-dockerized/data/conf/dovecot/`)
> 
> Create a Cron.sh in the oauth2_imap directory with the following content:
> 
> ```
> #!/bin/bash
> # Renewal of the token
> cd /opt/mailcow-dockerized/data/conf/dovecot/oauth2_imap/
> #./oauth2_imap real-mailaddress
> ./oauth2_imap real-mailadress1 >/dev/null 2>&1
> ./oauth2_imap real-mailadress2 >/dev/null 2>&1
> ```
> 
> `chmod +x cron.sh`
> 
> Then just crontab -e and insert the following content:
> 
> `*/30 * * * * * /opt/mailcow-dockerized/data/conf/dovecot/oauth2_imap/cron.sh >/dev/null 2>&1`
> 
> That's actually it ;-)

this solution was perfect for my wifes email, thanks for the simple instructions

**Comment by intrdp** [comment]
Since mailcow-idp feature is now officially released, it would be great if this feature request could be reopened and get implemented in Mailcow.

**Comment by mfuryto** [comment]
Ref #6673 - I now have a working implementation with an opt-in mail scope and XOAUTH2/OAUTHBEARER support in Dovecot. It has been tested end-to-end with Roundcube, including token revocation and failure cases.
I’ll wait for #7434 before opening the follow-up PR.
