### ISSUE TITLE
Fail2Ban API Banlist Error 

### ISSUE THREAD

**Issue by daygle** [mailcow/mailcow-dockerized#6089]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
api/v1/get/fail2ban/banlist/ not working.

Error - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
![Uploading image.png…]()

### Logs:

```plain text
No logs available for this error.
```

### Steps to reproduce:

```plain text
1. Login to mailcow with your administrator account.
2. Navigate to System > Configuration > Options > Fail2ban parameters
3. Scroll down to the bottom of the page and locate https://mail.domain.net/api/v1/get/fail2ban/banlist/5297f53f-8fe2-4890-9ca0-f93753137e41
4. Copy link and paste in to browser.
5. Error - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 22.04

### Server/VM specifications:

10GB

### Is Apparmor, SELinux or similar active?

Yes

### Virtualization technology:

Proxmox

### Docker version:

Latest

### docker-compose version or docker compose version:

Latest

### mailcow version:

2024-08a

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by daygle** [comment]
![Screenshot 2024-09-25 145657](https://github.com/user-attachments/assets/7138bbad-bbcb-40b8-9fea-61919e7b55f7)

**Comment by apio-sys** [comment]
This is usually the case when you currently have no banned IPs, hence the json is empty and returns this error in a browser. If you curl the URL, you will just get an empty response as expected if now hosts banned. Can you confirm that in your UI it says _No active bans_ just above the URL? That will confirm it is not a bug but just expected behaviour.

**Comment by daygle** [comment]
Thanks @apio-sys - See attached screenshot, although I have one banned IP is still throws the error :(

![image](https://github.com/user-attachments/assets/71ac96e6-65cc-4452-b984-35f04cc43786)

**Comment by apio-sys** [comment]
And if you curl the URL do you get any output?

**Comment by daygle** [comment]
> And if you curl the URL do you get any output?

@apio-sys Sure do.

![image](https://github.com/user-attachments/assets/8f320bdf-27d9-4e56-9037-923190e64047)

**Comment by apio-sys** [comment]
OK so data is there then. Maybe something to do with formatting. I don't see curly brackets around the data. Have you tried different browsers to open the URL? If you go to "raw data" don't you see the same output as in curl? Sorry out of ideas otherwise.

**Comment by daygle** [comment]
Thanks @apio-sys - Yeah, tried other browsers. Raw data shows the error. I suspect all users have the same issue.

**Comment by apio-sys** [comment]
I think you are right. I'll try to confirm this as soon as I catch an IP in fail2ban, currently have none. The data is there, it's just the formatting which doesn't seem proper json.

**Comment by GeistFighter** [comment]
Hello,

I also have the same problems with version 2024-08a, and the problem occurs whether the banlist is empty or has more than 300 active bans. (Trying to retrieve the content via curl works fine)
![image](https://github.com/user-attachments/assets/04c95a08-e509-4165-9b8d-e4f585e4021f)
![image](https://github.com/user-attachments/assets/e5f168b1-593c-4a9c-8d43-e1977e955ec6)

**Comment by daygle** [comment]
@andryyy Just wondering if there was any progress on this one?

**Comment by andryyy** [comment]
Me? Did you by chance ping the wrong guy? :)

**Comment by daygle** [comment]
Oh sorry @andryyy.

**Comment by foorschtbar** [comment]
> Thanks @apio-sys - See attached screenshot, although I have one banned IP is still throws the error :(
> 
> ![image](https://private-user-images.githubusercontent.com/5925233/371426805-71ac96e6-65cc-4452-b984-35f04cc43786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTM4NjUsIm5iZiI6MTczMTMxMzU2NSwicGF0aCI6Ii81OTI1MjMzLzM3MTQyNjgwNS03MWFjOTZlNi02NWNjLTQ0NTItYjk4NC0zNWYwNGNjNDM3ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDgyNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljZGUxMzc1OWM0NTIyODQ1OTBlZjZhOGQ1MWZkY2FlNWUzZjJkNThiYjA2YzdjMThmOGQ2MWY3NDIwMDE2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0ha_ORMgO85Z1LPirG--muJ9aei8S6dt0r7Qom7fH2o)

Same here. Error with one entry or without any. No change after recreating the API URL/token

**Comment by daygle** [comment]
@foorschtbar Not sure if anyone from mailcow is looking at this? Would love to see it get fixed soon so that I am able to manage blocked IP addresses via OPNsense.

**Comment by DerLinkman** [comment]
We'll take a look at this soon.

**Comment by FreddleSpl0it** [comment]
The endpoint returns a simple list not json.
I will move the endpoint to a different location, away from `json_api.php`.

**Comment by daygle** [comment]
Thanks team :)
