### ISSUE TITLE
How can I use nginx/php/etc after installing mailcow?

### ISSUE THREAD

**Issue by hivokas** [mailcow/mailcow-dockerized#609]
How can I use and configure nginx/php/etc after installing mailcow? Honestly, I didn't have an experience with docker yet, so can't understand it.

**Comment by mkuron** [comment]
There are some guides in the documentation how you can integrate third party tools. However, we do not recommend you modify the configuration to accommodate other services. Instead, set them up in separate docker containers (independently of Mailcow) and put a reverse proxy instead of everything.

**Comment by hivokas** [comment]
@mkuron, I want to build my website. And I need to send mail from it, so I decided to use mailcow. Did I understand correctly, that I need to create a second docker and build my website there? Will I have opportunity to send mail from the second docker?

**Comment by mkuron** [comment]
Yes, you should put your website in a separate Docker container (or run it on the host). To send mail from a website, you don't even need a mail server -- just install Postfix on the web server and it will deliver all messages directly to the recipients. You only need to Mailcow if you actually want to host mailboxes and calendars etc.

**Comment by hivokas** [comment]
@mkuron, I want to:
- keep the sent and received mail;
- sign each letter with DKIM (!);
- be able to send mail from several domains on one server (!);
- be able to set aliases.

I didn't find any solution (tutorial) to do things listed above.

**Comment by andryyy** [comment]
You can also use a reverse proxy setup and use whichever webserver you prefer. 

You'd then mail via smtp, authenticated. All auth. senders are signed.

You can send from all domains mailcow knows/handles and add a DKIM key for each.

**Comment by hivokas** [comment]
@andryyy, can you share any link, where I can read about this?

**Comment by andryyy** [comment]
Btw: You can also just create a Nginx site as `data/conf/nginx/my_site.conf` or `whatever.conf`. It will not be overwritten by updates.

If you need help setting up a reverse proxy: You can find it in the docs. 

When you decide to use a reverse proxy, just use "172.22.1.1" on port 25 as mail server address in your web app. When you create a new site in `data/conf/nginx`, use "postfix" as server name (yes, just "postfix") on port 588. 👍

**Comment by hivokas** [comment]
@andryyy, so it will be best if I do like this?

- create **mysite-dockerized**
- configure nginx/php/mysql/etc there
- use reverse proxy in nginx config of _mysite_ like you said above

Sorry if I understand something wrong, because I just started to delve into the essence of the docker.
