### ISSUE TITLE
Forwarding / spam filtering behaviour change broke Mailcow usage

### ISSUE THREAD

**Issue by adamathefrog** [mailcow/mailcow-dockerized#6100]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I've used Mailcow for a while as:

1) domain email server
2) forwarding relay for virtual machines

Some recent change in the past couple of months broke all of the mail forwarding, and made the mail receipt behaviour so obnoxious it has rendered us unable to receive mails from our own ticketing system.

The instructions in the documentation for enabling relaying don't seem to work properly, the spam filtering still just blocks everything.

The changes now make the system reject any emails from the ticketing system to our domain, because the ticketing system's placeholder "from" address doesn't exist.

This all worked before. It's behaviour change. It's not good. The only real responses I saw google for this stuff were people telling others complaining about this that it's how it's meant to be.

If you're going to make major changes like this, you need to provide documentation on how to restore the original behaviour that people have configured their platforms around.

As it stands I'm probably going to remove Mailcow because life is too short to use a platform which pushes major breaking changes to existing installations.
```

### Logs:

```plain text
gfhds
```

### Steps to reproduce:

```plain text
dsfhg
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

sgdf

### Server/VM specifications:

gd

### Is Apparmor, SELinux or similar active?

sdgf

### Virtualization technology:

sgdf

### Docker version:

sdgf

### docker-compose version or docker compose version:

sgdf

### mailcow version:

sdg

### Reverse proxy:

dsgf

### Logs of git diff:

```plain text
dsgf
```

### Logs of iptables -L -vn:

```plain text
sgdf
```

### Logs of ip6tables -L -vn:

```plain text
sgdf
```

### Logs of iptables -L -vn -t nat:

```plain text
sdgf
```

### Logs of ip6tables -L -vn -t nat:

```plain text
sgdf
```

### DNS check:

```plain text
gdfs
```

**Comment by itsafire** [comment]
This report is basically just a rant with no logs provided to elaborate on the problem at hand.
