### ISSUE TITLE
mail for domain.de loops back to myself

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#614]
Hello, currently my hoster has a nameserver failure. My mailserver is not available. I have a second Backup MX (also Mailcow). If an attempt is now made to send mail, I always get the following error message: `Diagnostic Code: X-Postfix; mail for domain.de loops back to myself`

What have I configured incorrectly?

Many thanks for your help!

**Comment by RobinFlikkema** [comment]
Do you have the relay option on in the main mailserver? Can you try it without that option on?
