### ISSUE TITLE
Issues with Docker IPv6 on NixOS

### ISSUE THREAD

**Issue by font44** [mailcow/mailcow-dockerized#6167]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I installed mailcow on NixOS. The base system is NixOS but I installed the project as per the official documentation (meaning, I didn't try to model the Docker Compose containers as NixOS modules or anything). The NixOS part is bare-bones: it simply installs Docker, adds a non-root user and sets up IPv6; nothing fancy.

I enabled IPv6 on Docker through NixOS. Relevant parts:


  virtualisation.docker = {
    enable = true;
    daemon.settings = {
      ipv6 = true;
      fixed-cidr-v6 = "fd00::/80";
    };
  };
  users.users.${user}.extraGroups = [ "docker" ];


I also use `nftables` instead of `ip6tables`.

When I run `sudo ./update.sh`, I see the following:

```
Working on IPv6 NAT, please wait...                                                                                                                                                                         
./update.sh: line 117: /etc/docker/daemon.json: No such file or directory                                                                                                                                   
./update.sh: line 118: ip6tables: command not found                                                                                                                                                         
Great! Native IPv6 NAT is active.                                                                                                                                                                           
Validating docker-compose stack configuration...                                                                                                                                                            
Checking for conflicting bridges...                                                                                                                                                                         
./update.sh: line 966: iptables: command not found                                                                                                                                                          
```

As per the `./update.sh` file, it seems like the code is hard-coded to use `iptables`. However, it's not just that - the code is hard-coded to use a `/etc/docker/daemon.json` but NixOS manages that separately and that file doesn't exist.

Is this expected behavior? What's unclear to me is whether IPv6 is setup correctly or not? Anything I can do to make the error message go away?
```

### Logs:

```plain text
Working on IPv6 NAT, please wait...                                                                                                                                                                         
./update.sh: line 117: /etc/docker/daemon.json: No such file or directory                                                                                                                                   
./update.sh: line 118: ip6tables: command not found                                                                                                                                                         
Great! Native IPv6 NAT is active.                                                                                                                                                                           
Validating docker-compose stack configuration...                                                                                                                                                            
Checking for conflicting bridges...                                                                                                                                                                         
./update.sh: line 966: iptables: command not found
```

### Steps to reproduce:

```plain text
1. Install NixOS.
1. Run `./update.sh` on a working setup.
```

### Which branch are you using?

master

### Which architecture are you using?

ARM64 (aarch64)

### Operating System:

NixOS 24.11 (Vicuna)

### Server/VM specifications:

4 GB, 2 cores.

### Is Apparmor, SELinux or similar active?

No.

### Virtualization technology:

KVM.

### Docker version:

27.3.1

### docker-compose version or docker compose version:

2.30.0

### mailcow version:

2024-11a-4-g82c6861e

### Reverse proxy:

Default one.

### Logs of git diff:

```plain text
diff --git a/docker-compose.yml b/docker-compose.yml
index b0324521..a876cd89 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -614,36 +614,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
```

### Logs of iptables -L -vn:

```plain text
sudo: iptables: command not found
```

### Logs of ip6tables -L -vn:

```plain text
sudo: iptables: command not found
```

### Logs of iptables -L -vn -t nat:

```plain text
sudo: iptables: command not found
```

### Logs of ip6tables -L -vn -t nat:

```plain text
sudo: iptables: command not found
```

### DNS check:

```plain text
104.18.32.7
172.64.155.249
```

**Comment by DerLinkman** [comment]
You read the docs did you?

No? Please use supported os only!

**Comment by font44** [comment]
I did read the docs which say:

> Basically, mailcow can be used on any distribution that is supported by Docker CE

Anyway, I'll try another distribution.

**Comment by DerLinkman** [comment]
Then we need to rewrite this in the docs actually.

Technically it is possible wherever docker is runnable but we support only the platforms we noted down inside the docs.

**Comment by DerLinkman** [comment]
See updated docs: https://docs.mailcow.email/getstarted/prerequisite-system/#supported-os

Thanks for noticing (even if indirectly :D)
