### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by nieselregencom** [mailcow/mailcow-dockerized#617]
After update I get:

ERROR: Version in "./docker-compose.yml" is unsupported.

**Comment by nieselregencom** [comment]
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0", "3.1", "3.2") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

docker -v
Docker version 17.07.0-ce, build 8784753

docker-compose -v
docker-compose version 1.14.0, build c7bdf9e

**Comment by JackThursby252** [comment]
<s>Well, what versions are you running?
I'm currently on docker-compose version 1.16.1, build 6d1ac21 which suppoterts ...</s> there's your edit...

Update your docker-compose version to the latest (1.16.1) and try it again. Should work instantly :)
The docker-compose.yml is in Version 2.3, which requires at least docker-compose 1.16.0-rc2

**Comment by nieselregencom** [comment]
Do I have to rerun the following command to update docker-compose?

curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by nieselregencom** [comment]
At least it worked for me so.

Many thanks for the help!
