### ISSUE TITLE
ACME "Waiting for Nginx..."

### ISSUE THREAD

**Issue by alexsalex** [mailcow/mailcow-dockerized#6170]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
1f70f884a894:/# ping dockerapi.mcd_mailcow-network
ping: bad address 'dockerapi.mcd_mailcow-network'

1f70f884a894:/# ping dockerapi
PING dockerapi (172.22.1.3): 56 data bytes
64 bytes from 172.22.1.3: seq=0 ttl=64 time=0.079 ms
64 bytes from 172.22.1.3: seq=1 ttl=64 time=0.069 ms
64 bytes from 172.22.1.3: seq=2 ttl=64 time=0.061 ms
^C
--- dockerapi ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.061/0.069/0.079 ms

1f70f884a894:/# ping nginx
PING nginx (172.22.1.13): 56 data bytes
64 bytes from 172.22.1.13: seq=0 ttl=64 time=0.096 ms
64 bytes from 172.22.1.13: seq=1 ttl=64 time=0.105 ms
^C
--- nginx ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.096/0.100/0.105 ms

1f70f884a894:/# ping nginx.mcd_mailcow-network
ping: bad address 'nginx.mcd_mailcow-network'
1f70f884a894:/#
```

### Logs:

```plain text
No logs, DNS
```

### Steps to reproduce:

```plain text
https://github.com/mailcow/mailcow-dockerized/issues/5962
```

### Which branch are you using?

nightly

### Which architecture are you using?

x86

### Operating System:

Debian 12

### Server/VM specifications:

VPS

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

OpenStack

### Docker version:

27.3.1

### docker-compose version or docker compose version:

2.29.7

### mailcow version:

Nightly: dc379267

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
No logs
```

### Logs of iptables -L -vn:

```plain text
No logs
```

### Logs of ip6tables -L -vn:

```plain text
No logs
```

### Logs of iptables -L -vn -t nat:

```plain text
No logs
```

### Logs of ip6tables -L -vn -t nat:

```plain text
No logs
```

### DNS check:

```plain text
# docker exec -it $(docker ps -qf name=mcd-acme) dig +short stackoverflow.com @172.22.1.254
104.18.32.7
172.64.155.249
```

**Comment by alexsalex** [comment]
Any comment on this issue? UP

**Comment by dragoangel** [comment]
You not follow docs about setup, you not follow instructions how to fill up the bug, you not done basic troubleshooting from your side. Please ask for a support in a proper way. Github issues is not a help center. I explained what your issue in Mailcow community telegram.

**Comment by alexsalex** [comment]
> You not follow docs about setup

What are you talking about? Deployed by the docs, only changes is:
COMPOSE_PROJECT_NAME=mcd

Based on the discussion in https://github.com/mailcow/mailcow-dockerized/issues/5962 (which I mentioned), you merged the PR where you changed all hostnames for curl (?) from **hostname** to **hostname_mailcow-network**, and I can't resolve new hostnames in my docker but can resolve the old names.

Could you show me the documents which resolve this issue? Or help me on how to resolve it?
