### ISSUE TITLE
Will updating Mailcow affect data/web?

### ISSUE THREAD

**Issue by DougBeney** [mailcow/mailcow-dockerized#618]
I modified the files in data/web in these ways:
- I moved `index.php` and made the regular MailCow homepage available at the URL, /admin
- I created a new `index.php` that redirects to my RainLoop (webmail client) directory.

I'm wondering if running `update.sh` could mess up my current setup.

**Comment by mkuron** [comment]
You'll immediately get a merge conflict with updates that changed anything inside data/web. So you should undo your changes, update, and redo them. Or better yet, don't make the changes and use a reverse proxy to present non-Mailcow content on the same domain.

**Comment by andryyy** [comment]
Most conflicts are auto-solved in favor for mailcow. This only happens when we both changed the same lines. :)

**Comment by Braintelligence** [comment]
@andryyy But he could stash before update and pop after update, right?

**Comment by mkuron** [comment]
@Braintelligence, stashing is no different than committing. If there is a conflict, that will need to be resolved after the `git stash pop` too.

**Comment by Braintelligence** [comment]
I see. Thanks for clarifying @mkuron :).
