### ISSUE TITLE
check docker version fail in  generate_config.sh

### ISSUE THREAD

**Issue by i-curve** [mailcow/mailcow-dockerized#6187]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
The docker version cannot be less than 24 in the generate_config.sh script. An error will occur in the if statement. docker_version is a multi line value.


docker_version=$(docker -v | grep -oP '\d+\.\d+\.\d+' | cut -d '.' -f 1)

if [[ $docker_version -lt 24 ]]; then
  echo -e "\e[31mCannot find Docker with a Version higher or equals 24.0.0\e[0m"
  echo -e "\e[33mmailcow needs a newer Docker version to work properly...\e[0m"
  echo -e "\e[31mPlease update your Docker installation... exiting\e[0m"
  exit 1
fi
```
```


### Logs:

```plain text
generate_config.sh: line 31: [[: 26
26
24: syntax error in expression (error token is "26
24")
Found Docker Compose Plugin (native).
Setting the DOCKER_COMPOSE_VERSION Variable to native
Notice: You'll have to update this Compose Version via your Package Manager manually!
Press enter to confirm the detected value '[value]' where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: ^
```

### Steps to reproduce:

```plain text
1. run `bash generate_config.sh`
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 24.04

### Server/VM specifications:

16GB, 16vCPU

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

kvm

### Docker version:

26.1.3

### docker-compose version or docker compose version:

v2.27.1

### mailcow version:

2024-11b

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
N/A
```

### Logs of iptables -L -vn:

```plain text
N/A
```

### Logs of ip6tables -L -vn:

```plain text
N/A
```

### Logs of iptables -L -vn -t nat:

```plain text
N/A
```

### Logs of ip6tables -L -vn -t nat:

```plain text
N/A
```

### DNS check:

```plain text
N/A
```

**Comment by DerLinkman** [comment]
Just merged, will be live with 2024-12
