### ISSUE TITLE
Add Japanese language support

### ISSUE THREAD

**Issue by kotaroman** [mailcow/mailcow-dockerized#6191]
### Summary

This update adds Japanese language support to mailcow. 

The implementation includes:
1. A new `lang.ja-jp.json` file containing complete Japanese translations for all existing strings.
2. Updates to `vars.inc.php` to integrate `ja-jp` as a selectable language in the system.

This enhancement ensures that mailcow can be used effectively by Japanese-speaking users and aligns with the goal of expanding language support in the project.

<img width="886" alt="スクリーンショット 2024-12-01 223448" src="https://github.com/user-attachments/assets/090e97be-782a-482f-bed0-6a7ad4630014">

### Motivation

Adding Japanese language support will make mailcow more accessible to users in Japan, where demand for localized software is high. This change will benefit not only Japanese-speaking users but also increase the global usability of mailcow. As mailcow already supports multiple languages, incorporating Japanese aligns with the project's goal of inclusivity.

### Additional context

This feature branch (`feat/add_japanese_lang`) was created from the `staging` branch to ensure compatibility with the latest development changes. 

### Files included in the attached ZIP:
1. `lang.ja-jp.json`:
   - Contains complete Japanese translations for mailcow.
   - Structured similarly to existing language JSON files for seamless integration.

2. `vars.inc.php`:
   - Updated to include `ja-jp` (Japanese) as a selectable language in the supported languages array.

### How to apply these changes:
1. Extract the ZIP file.
2. Place `lang.ja-jp.json` in the `data/lang` directory.
3. Replace or merge the provided `vars.inc.php` with your existing file.
4. Restart the mailcow stack to apply the changes.

[japanese.zip](https://github.com/user-attachments/files/17969089/japanese.zip)

**Comment by DerLinkman** [comment]
Hello!

Thanks!

But you opened up a issue not  a pr for this... this pr can be based upon your origin branch though.

**Comment by kotaroman** [comment]
@DerLinkman 

Hello,

Thank you for your guidance!

I noticed that I don’t have push access to the repository, so I will fork the repository and create a Pull Request from my fork. Please wait while I prepare and submit it.

Best regards,

**Comment by DerLinkman** [comment]
Yeah you cannot push directly into the repo, that is actually a common way to do it here on GH. Always create a PR based upon your fork which is then merged (depending on quality etc.)

**Comment by kotaroman** [comment]
Thank you for the clarification!
I have created a PR based on my fork as you suggested. Here is the link to the PR: [#6198](https://github.com/mailcow/mailcow-dockerized/pull/6198).
Please let me know if there are any issues or further changes needed.
@DerLinkman
