### ISSUE TITLE
Symlink certificates for Dovecot/Postfix

### ISSUE THREAD

**Issue by jaimbo** [mailcow/mailcow-dockerized#620]
I have Nginx running on the host VM and a reverse proxy to mailcow, and this works perfectly. Nginx on the host gets all the SSL certificates I need through Certbot and everything works. The only issue I am having is the certificates used by Dovecot/Postfix in /data/assets/SSL will work if they are manually replaced, but if I try and symlink the certificates from /etc/letsencrypt/live/example.com they are replaced whenever I restart mailcow.

**Comment by andryyy** [comment]
Hi cat, this is cow. I think you will be fine hard-linking them with "ln here there" instead of sym-linking them with "ln -s here there". Sym-links are expected to fail.

**Comment by jaimbo** [comment]
Hi cow, this is cat.
That seems to work. I had to link to the physical files in the /etc/letsencrypt/archive folder, instead of the symlinks that exist in the /etc/letsencrypt/live folder, this seems to work now, not sure if it will cause problems after renewal.

Thanks!
