### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#621]
I recently switched my hostname, which appeared to work (at least at first). I changed the mail.conf file, and all my relevant DNS records to match. I also ran an mailcow update.

However, I noticed yesterday I could no longer connect to the server via web. The actual mail server appears to work though. I've logged into the server via SSH, and restarted the docker processes. I've even rebooted the entire server. I've double checked all the config files I can think of (mail.conf, nginx). No joy.

I have noticed that the CPU is running very high, since the change. 
![image](https://user-images.githubusercontent.com/7480500/30632974-ddbe378c-9de1-11e7-810f-3cd042831817.png)

Mailcow is the only process running on the server. The drop is when I rebooted the server, so something in mailcow must be eating CPU time.

MXToolbox reports the following on the SMTP test:
![image](https://user-images.githubusercontent.com/7480500/30633065-3c9b21ca-9de2-11e7-8256-1955cfed52a0.png)

**Comment by MrSuttonmann** [comment]
On closer inspection, I have a couple of issues showing in the logs:
![image](https://user-images.githubusercontent.com/7480500/30633602-2a1d9fd0-9de4-11e7-970f-87974c30e4de.png)

![image](https://user-images.githubusercontent.com/7480500/30633608-34d21a78-9de4-11e7-831c-3e6650aa52c5.png)

**Comment by andryyy** [comment]
Unknown connection_upgrade variable. You enabled portainer. Delete this line from portainers site config.

**Comment by MrSuttonmann** [comment]
Thanks.

I actually couldn't find a reference to "connection_upgrade" in the conf file, but I did notice the following lines were missing:
![image](https://user-images.githubusercontent.com/7480500/30634501-3db763e8-9de7-11e7-8292-6c1e5b587b79.png)

I added them back in, and it now works.
