### ISSUE TITLE
Division by zero when quota is set to 0

### ISSUE THREAD

**Issue by trick77** [mailcow/mailcow-dockerized#622]
Since quota can be 0 (when migrating from a earlier, non-Docker version), this calculation leads to a division by zero:

`$mailboxdata['percent_in_use'] = round((intval($row['bytes']) / intval($row['quota'])) * 100);`

Eventually, this leads to an empty mailbox list in the admin UI with no error logged (HTTP RC is 200 from the mailbox/all API call).

**Comment by trick77** [comment]
This is a var_dump before it happens:

`array(9) {
  ["max_new_quota"]=>
  int(134217728)
  ["username"]=>
  string(17) "admin@domain.net"
  ["is_relayed"]=>
  int(0)
  ["name"]=>
  string(5) "admin"
  ["active"]=>
  string(8) "&#10004;"
  ["active_int"]=>
  int(1)
  ["domain"]=>
  string(11) "domain.net"
  ["quota"]=>
  int(0)
  ["quota_used"]=>
  int(63571)
}
`

Not sure where in the calculation the quota = 0 comes from, it's not 0 in database.

**Comment by andryyy** [comment]
Hi, not 0 in the db? Is it unset? intval makes it a 0 then.

We should fix the docs/guide then, thanks.

**Comment by trick77** [comment]
Actually, I may have looked at the wrong table and the value was indeed set to 0 (which may have indicated "unlimited" in the old version). I would also include a protection around the calculate method to prevent this from happening.

I have a few suggestions for the migration guide as migration was more complex than I initially assumed:
- Please show how to migrate the legacy-vmail folder structure to the vmail Docker volume in the migration guide. Took me a while to figure this out and for someone without Docker know-how this is virtually impossible to achieve.
- All non-SSHA256 passwords have to be reset throuth the admin UI. Dovecot and SOGo will work with the old passwords but the admin UI won't let you log in to the users mailbox control panel.
- If the user_acl table is empty (which it is with the current migration guide) a user won't be able to set things like TLS in/out enforcement.

All is up an running now and it's awesome. Thank you for your work!
