### ISSUE TITLE
Single Sign On feature for external apps broken

### ISSUE THREAD

**Issue by dirkpauli** [mailcow/mailcow-dockerized#6226]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
I use mailcow as a single sign on provider for nextcloud. with the latest release, the oauth2-authentification of mailcow seems to be broken. instead of showing the page "authorize application" it redirects to the config page of the user, making a web login to nextcloud impossible.

This is how it behaves in 2024-11b. Reverting to git commit 9f7d965ea14035966a284082602655c3c3252e92 will make it work again, but blocking other updates.
```

### Logs:

```plain text
/
```

### Steps to reproduce:

```plain text
1) set up mailcow in commit 9f7d965ea14035966a284082602655c3c3252e92 and nextcloud in version 30
2) set up oauth authentification between mailcow and nextcloud as described in https://docs.mailcow.email/third_party/nextcloud/third_party-nextcloud/
3) check the authentification works in nextcloud web interface using mailcow oauth2
4) update mailcow to 2024-11b
5) try to authentificate in nextcloud using mailcow oauth
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Debian 12

### Server/VM specifications:

8 GB, 4 cores

### Is Apparmor, SELinux or similar active?

irrelevant

### Virtualization technology:

Docker

### Docker version:

27.4.1

### docker-compose version or docker compose version:

v2.32.1

### mailcow version:

2024-11b

### Reverse proxy:

nginx

### Logs of git diff:

```plain text
irrelevant
```

### Logs of iptables -L -vn:

```plain text
irrelevant
```

### Logs of ip6tables -L -vn:

```plain text
irrelevant
```

### Logs of iptables -L -vn -t nat:

```plain text
irrelevant
```

### Logs of ip6tables -L -vn -t nat:

```plain text
irrelevant
```

### DNS check:

```plain text
172.64.155.249
104.18.32.7
```

**Comment by mkuron** [comment]
Confirmed. Happens on mine too. 9f7d965ea14035966a284082602655c3c3252e92 is not a commit in this git repository, so I assume you have local commits with local modifications. Could you please confirm which public commit that corresponds to?

**Comment by dirkpauli** [comment]
ups - right, this is the git number locally from my update history.

I haven't done any local changes to the files. 

Mailcow version must be from commit 37beed6; so version 2024-08a

**Comment by mkuron** [comment]
Duplicate of #6161, which is fixed in https://github.com/mailcow/mailcow-dockerized/commit/49e05f512061400db89cdbe6e435898e6e27bdc4 and will be part of the next release.
