### ISSUE TITLE
SOGo / Roundcube with subdomain

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#625]
Hi,

as in the title posted, how can I configure a subdomain for SOGo (instead of mydomain/SOGo) or for Roundcube (instead of mydomain/rc).

I haven't found any config, with which I can configure a subdomain. Do I need to install a nginx on the host (besides docker) and use this for a subdomain? Can someone give me a short howto, because I'm new to this stuff?!

Thanks in advance :-)

**Comment by PhoenixPeca** [comment]
Hello @mwrnck!

> Do I need to install a nginx on the host (besides docker) and use this for a subdomain?

Yes. You will need to set the host machine's nginx as a reverse proxy for the dockerized nginx-mailcow. To get yourself started, just follow the steps as stated in the [documentations](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/)

**Comment by ghost** [comment]
Thanks @PhoenixPeca ,
can you give an example-config for the nginx with a ssl-config? I don't get it to work:
First I change the bindings in the mailcow.conf and after this I create a new nginx file on the host, where I insert the lines of the docu.
If I open mail.example.de I get a blank page. Can you or anyone else help me with this?

**Comment by Braintelligence** [comment]
Would it be acceptible to just create a subdomain that points per HTTP301 to mydomain.com/SOGo ?
That's what I do in such cases, if it's only about having a more beautiful link.

**Comment by axd** [comment]
@mwrnck There's a thread open to achieve something like you want but it's in standby: https://github.com/mailcow/mailcow-dockerized/issues/393.

But as @Braintelligence says, that's the only way (for now) to make it work. (https://domain.com/SOGo).
