### ISSUE TITLE
Cannot start since update

### ISSUE THREAD

**Issue by SoftCreatR** [mailcow/mailcow-dockerized#628]
I've performed an update of mailcow and now, it fails to start properly:

```
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: readlink /var/lib/docker/overlay2: invalid argument
```

What can i do?

**Comment by andryyy** [comment]
Can you - just for a test - remove acme-mailcow from docker-compose and try again?

**Comment by SoftCreatR** [comment]
```
~/mailcow-dockerized # docker-compose rm acme-mailcow
No stopped containers
```

**Comment by andryyy** [comment]
No, remove it from docker-compose.yml. down and up -d again after that.

**Comment by SoftCreatR** [comment]
```
~/mailcow-dockerized # docker-compose down
Removing network mailcowdockerized_mailcow-network
~/mailcow-dockerized # docker-compose up -d
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: readlink /var/lib/docker/overlay2: invalid argument
```

**Comment by andryyy** [comment]
docker-compose stop acme-mailcow
docker-compose rm acme-mailcow

In case you didn't remove it before...

**Comment by andryyy** [comment]
Docker logs would be really helpful, too... which container is it?

**Comment by andryyy** [comment]
Try to start each container by running `docker-compose run x-mailcow` and try to find the broken one, please.

Edit: Which OS?

**Comment by SoftCreatR** [comment]
Tried that already. But the error appears on every container i try to run.

**Comment by andryyy** [comment]
systemctl stop docker
rm -rf /var/lib/docker/overlay2
rm -rf /var/lib/docker/image/aufs
rm -f /var/lib/docker/linkgraph.db
systemctl start docker

A very hard reset... but it does not delete your volumes. Keep in mind, that it will delelte all running containers on your host!

Please run the update script after this command.

**Comment by SoftCreatR** [comment]
Thank you, that seemed to work. Everything is back running.
