### ISSUE TITLE
[Feature Request] disable local delivery

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#630]
I would like to disable local delivery. Is there any way to do this?

---

**my setup:** I have two domains configured in Mailcow. `example1.tld` and `example2.tld`. `example1.tld` is used for sending and receiving e-mail. `example2.tld` will only use for MX-Backup or another use case: a email-domain that has not yet been migrated to mailcow.

**current behavior:** Wenn i send a email from `test@example1.tld` to `test@example2.tld`, then delivered mailcow that email localy. mailcow does not send the email to the server listed in the MX record.

**expected behavior:** Mailcow should send the e-mail to the mail server, which is stored in the MX-record of `example2.tld`.

**Comment by mritzmann** [comment]
Any update about this? :-)

**Comment by mkuron** [comment]
See https://serverfault.com/questions/281030/postfix-mx-lookup-for-delivery-instead-of-local-delivery-for-specific-domains — Postfix can‘t do it by itself. We would need to run two instances of Postfix to achieve that:
- one that accepts emails from authenticated users on ports 587 and 465, but does not do any local delivery (empty mydestination, no virtual_* options, etc.)
- one that accepts emails on port 25 as the mail exchanger for your domains and delivers them locally

**Comment by andryyy** [comment]
Hm, the current behavior is what Postfix does by default. You'd need to work with transport_maps then.

**Comment by mritzmann** [comment]
Okay, thanks. I close the issue because I don't think Mailcow can change this per default.

**Comment by mkuron** [comment]
It can actually be done by running two instances of Postfix simultaneously. So if you really need it, you could probably do. If someone posted a pull request that did this and didn't break anything else, I think it would be worthwhile considering.
