### ISSUE TITLE
[Question] How to backup Sogo

### ISSUE THREAD

**Issue by Seji64** [mailcow/mailcow-dockerized#631]
Hi,

 i was just wondering how it is possible to backup sogo related data (contacts, calendar entry's etc.) ?

Sorry for this dump question, but i am totally new to using docker.

Thanks in advance.

**Comment by mkuron** [comment]
All these entries are stored in MySQL, so you need to backup the database. There is a guide for that at https://mailcow.github.io/mailcow-dockerized-docs/u_e-backup_restore-mysql/ .

**Comment by Seji64** [comment]
Alright - thanks :-)

**Comment by Braintelligence** [comment]
I can't recommend this enough:
Run your whole mailbox-dockerized in its own VM that you can backup as a snapshot. You will never worry about data loss again.
