### ISSUE TITLE
Cannot modify email in SOGO IMAP account settings

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#634]
Hello,

I have an habit to have an internal account email "login@server.net" that I use purely for authentication purposes.
In SOGo/mailcow this is then my "default" email address.

When I go into the IMAP Account settings of SOGo, I can edit the email field to point to "firstname.name@server.net" (which is my public address), but when I save, the modification is not propagated, and the internal email is still my default one.

**Comment by andryyy** [comment]
Hi,

You need to report that to SOGo. They have a bug tracker. 

André

**Comment by etique57** [comment]
Hello,

I found this link which seems pretty to be the same problem but with an LDAP backend:
http://community.nethserver.org/t/default-mailaddress-in-sogo-3-2-cant-be-set/5629

I've logged a bug report here:
https://sogo.nu/bugs/view.php?id=4300

**Comment by etique57** [comment]
Hello,

the SOGo dev told me to put this:

You can set it with sogo-tool like this:
/usr/sbin/sogo-tool user-preferences set defaults ${USER_TO_MODIFY} SOGoMailCustomEmail '{"SOGoMailCustomEmail":"firstname.name@server.net"}'

Hint: Make sure to restart memcached, else you will get the cached value for some time :-)

I tried to translate it with the docker-compose exec command but it didn't work. Could you give me a hint?

Thanks§

**Comment by etique57** [comment]
Hello,

Any hint? ;)

Thanks!

**Comment by andryyy** [comment]
Hi,
Sorry, came here to answer this issue but then stumbled over the sync job issue first... 👍 
```
docker-compose exec sogo-mailcow gosu sogo /bin/bash -c "/usr/sbin/sogo-tool user-preferences set defaults USER_TO_MODIFY SOGoMailCustomEmail '{\"SOGoMailCustomEmail\":\"firstname.name@server.net\"}'"
```

**Comment by etique57** [comment]
Thanks!

It works great :)
