### ISSUE TITLE
Integrating mailcow with Amazon SES

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#637]
Having to setup an instance of mailcow for a friend, and I was thinking about using Amazon SES to relay outgoing messages. I found this doc about integrating SES to postfix:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html

I just found out that Mail For Good (a docker based mailing list server) uses SES for delivering: 
https://github.com/freeCodeCamp/mail-for-good
https://www.youtube.com/watch?v=_7U03GVD4a8

Considering SES price (0.10 per 1,000 email) that could be a standard feature for low volume/soho servers. What's the right path to proceed to integrate Mailcow and SES ?

**Comment by mkuron** [comment]
Amazon SES is simply a `relayhost`, which can be configured in Mailcow (check the docs). Of course, it only handles outgoing mail, so I guess the only scenario where this is useful is if you don‘t have a static IP address and have your incoming email delivered to a DynDNS host name. If you have a static IP, you can send outgoing mails directly without a relayhost.

I don‘t think you even need that `stunnel` stuff that Amazon documents. Postfix can use TLS relayhosts just fine.

**Comment by marrco** [comment]
well, I'd say Amazon SES is much more than simply a relay host, and it has nothing to do with dynamic or static IP address. My educated guess is that you just don't know SES, don't know why kind of companies are using it and why.
But if nobody here knows that service or is interested I will close this enhancement proposal in a few days.

**Comment by mkuron** [comment]
> I'd say Amazon SES is much more than simply a relay host

According to their documentation, it integrates with Postfix as if it were a relayhost. And if I look at their marketing materials, its main purpose seems to be delivering outgoing mail on behalf of another mail server. Granted, it has some additional features like monitoring and DKIM signing, but Mailcow can already do some of these things by itself.

> you just don't know SES, don't know why kind of companies are using it and why.

Well, then explain to us what SES is to you, what you want to use it for, what kind of integration you need, etc.

**Comment by andryyy** [comment]
You can simply integrate it as relayhost as @mkuron wrote.

It will not blacklist your mailcow for sending spam. There are services registered as “clean spam”, as is SES. If anything, we should punish SES Senders for potential spam in Rspamd. :-)

Iirc SES can add 1x1 pixels and stuff to catch who read your stuff. Ah, and also collect bounces. But that’s done on their side though, isn’t it? Integrates just fine as relayhost.

Correct me if I’m wrong.

**Comment by marrco** [comment]
The most important part is reputation. Relaying with ses you get very high deliverability. And considering the really low price, I'd say it could be worth for many companies' mail server.
Then there's the feedback loop and the bounce management. Again, considering the low price if you don't have a really high volume MTA it's cheaper than to spend hours to enroll in Microsoft snds etc. 

SES is a commodity that could save many hours of postmaster work for pennies. Deliverability statistics, virus checking, a nice panel, there are many features, I can't tell the future, but lately I've seen more than a few schools and business migrate to (relaying via) ses their email. 
One single issue that needs a few hours to get fixed is probably more expensive than a full year of SES. 

Using it as a relay is certainly an option. I don't know if it can be more integrated. I just found Mail For Good and I see they went further, so I'm asking for ideas and suggestions. Do you think AWS SES support could be a valuable addition to mailcow? Having it tightly integrated, from aws credential management to having a 'deliverability' section with links to ses statistics etc.

I don't have stats on mailcow installs but I know it's also installed on low-end VPS, so blacklisted IP space or port 25 limiting could be problems. But at the moment what I have in mind is that it could save hours of sys admin time just delegating delivery to ses for a fraction of cost.

Maybe using it as a relay is enough, but maybe it could be an idea to enhance mailcow to provide a better support for ses. Whats your idea?

**Comment by mkuron** [comment]
> Having it tightly integrated, from aws credential management

The credential management makes sense for Mail for Good because they require Amazon SES, but it doesn‘t actually save the admin much work. Since they need to configure SES with Amazon first anyway, they might just as well generate SMTP credentials on Amazon‘s website and paste them into Mailcow‘s relayhost configuration. That way, Mailcow can stay provider-neutral.

> having a deliverability section with links to ses statistics etc.

A link is not what I‘d call tight integration, it would be more like an advertisement (for one specific relayhost provider, even though there are many others that can be used too). 
I could see value in it though if you pulled stats and logs into Mailcow via Amazon‘s API though. On the other hand, such an integration could never provide all the information and configuration options that are available from Amazon‘s Admin Console, so the admin would likely still have to switch back and forth between Mailcow‘s and Amazon‘s consoles.
