### ISSUE TITLE
SOGo recurring all day events

### ISSUE THREAD

**Issue by rdanton** [mailcow/mailcow-dockerized#640]
Recurring all day events did not show in the webinterface. Can see them on IPhone and on Thunderbird, but not in the webinterface. Normal recurring events (with time) are visible in the webinterface.

Fresh installation today. Tried Ubuntu and Debain.

**Comment by mkuron** [comment]
Looks like a SOGo bug, so please report it at https://sogo.nu/bugs/. I can confirm that it happens on my install too.

**Comment by andryyy** [comment]
Thanks, fixed in dev by using official nightlies (again). The gnustep packages need to be the patched files from inverse.
