### ISSUE TITLE
[Question] Tagging Spam with [spam] and move to Inbox instead to Spam Folder

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#641]
I would like to have all Spam Mail in the Inbox, and not in the Spam-Folder. But with a [spam] tag in the Subject. Is this possible?

**Comment by andryyy** [comment]
Hi, first: the default sieve script is run after a users script. So you can create a  filter rule in SOGo to stop processing if a header “X-Spam-Flag” is found. 

Next you need to edit data/conf/local.d/force_actions.conf and add a new rule like this:

ADD_SPAM_TAG {
  action = “rewrite subject”;
  subject = “[Spam] %s”;
  require_action = “add header”;
}

Wrote this from my mobile. Hope I didn’t mess it up.

**Comment by mritzmann** [comment]
Hi andryyy, merci for your answer! I'll try it.

**Comment by feldsam** [comment]
Can this be added in mailcow UI under Administration tab in latest mailcow?

**Comment by andryyy** [comment]
Messing with the subject is not good when using DKIM and ARC. 

I prefer not to add it to the UI. But that’s just this one rule you need. :)

**Comment by feldsam** [comment]
hi, I mean, if I can add it via mailcow ui, there is alredy some settings in UI for adding custom rules...

**Comment by andryyy** [comment]
I see. Hmm. A very low priority rule could do it without breaking user settings. I’m not home to test or write it. But it shouldn’t be too hard.
