### ISSUE TITLE
aliases: goto adress validation incorrect

### ISSUE THREAD

**Issue by slintes** [mailcow/mailcow-dockerized#642]
Hey,

first of all: thanks for this great project! I started using mailcow today and I'm busy with configuration of my domains and mail adresses.

Im my old setup I used to do this:

- add 3 domains, `1stdomain.tld`, `mail.1stdomain.tld` and `2nddomain.tld`
- create a mailbox, e.g. `me@1stdomain.tld`
- create aliases for `hostmaster@mail.1stdomain.tld`, `postmaster@mail.1stdomain.tld`, `webmaster@mail.1stdomain.tld`, `abuse@mail.1stdomain.tld` and `security@mail.1stdomain.tld`, all forwarding to `me@1stdomain.tld`
- for the next domain, create an alias `@2nddomain.tld` forwarding to `@mail.1stdomain.tld`. That means that all addresses existing for `mail.1stdomain.tld` work for `2nddomain.tld` too. If I decide to use another generic mail address for all my domains, I only need to add it to `mail.1stdomain.tld`.

Unfortunately this is not possible with the mailcow UI, it complains that `@mail.1stdomain.tld` is not a valid goto address. Reason is the validation for being a email address here: https://github.com/mailcow/mailcow-dockerized/blob/dd3bd82838a7afca6ce80f35b9b3a07f75897634/data/web/inc/functions.mailbox.inc.php#L365

Would be nice if this validation takes also in account that goto addresses in format `@anymailcowdomain.tld` are valid too.

PS: I'm using `subdomain.1stdomain.tld` for the aliases in order to not coming in conflict with other "normal" addresses of `1stdomain.tld`.

Greetings, Marc

**Comment by slintes** [comment]
PS: that setup works when adding the aliases directly in the db

**Comment by mkuron** [comment]
Couldn‘t you use an alias domain to achieve just that?

**Comment by slintes** [comment]
I understood that I can't add additional domain specific mailboxes / aliases to alias domains. Is that correct? If so it's not an alternative to my approach. I just want to save the work for hostmaster/webmaster etc., which I have on every domain, and for what I'm always to one who should receive the mails.

**Comment by mkuron** [comment]
You can add aliases to alias domains. In fact, you need to be able do that because only mailboxes are inherited from the parent domain and not aliases.

**Comment by slintes** [comment]
Ok, then that's another reason that domain aliases won't work: the addresses are aliases ;)

Besides that: the validation is preventing valid configuration of postfix. Why discussing if it's possible to do that in another way?

**Comment by mkuron** [comment]
Oh, Postfix has so many options we couldn’t possibly expose all of them in the GUI.

The trouble with just adding the @domain.com alias to Postfix is that you can‘t use it for sending outbound mail  — Postfix‘s sender checks forbid you to do that and the addresses won’t show up in the „From“ field in SOGo either. So you should try to create all the needed redirections with a mixture of mailbox and domain aliases in the web GUI as-is.

**Comment by slintes** [comment]
I don't want to create mailboxes for those addresses. I'm using 1 mailbox only + many aliases + the configuration I described for at least 15 years now. I don't care if I can't use those addresses for sending mails, I can respond with my "regular address". I added the aliases directly into the database for now. But thanks for the discussion, even when the outcome isn't what I wished ;)

**Comment by andryyy** [comment]
> Ok, then that's another reason that domain aliases won't work: the addresses are aliases ;)

That shouldn't be a problem. 

I would gladly add it, but there are some processes to read that goto field, which may fail with this object in it.

**Comment by slintes** [comment]
Can you give more details on what might fail? Because I'm using this for some days now (by adding the entries manually to the database), and as far as I can say everything works as expected. Just wan't to be sure that I don't oversee something....

And besides that: probably I didn't understand yet how alias domains work. What happens when I use a alias domain? Do all addresses (aliases and mailboxes) of the target domain also work for the alias domain? Can I still add more aliases and mailboxes to the alias domain? I'm a bit confused ;)

**Comment by andryyy** [comment]
Need to re-check this. I might be wrong and it was only "address" from "alias" to cause errors. :)

All mailboxes will then work for the alias domain, too, yes. But not aliases. Aliases can be created for alias domains and domains separately.
