### ISSUE TITLE
Postfix - relay access denied, bounce

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#643]
Hi,
I noticed that in the last week I had a lot of errors like that on my Postfix log. Some customers are not receiving email coming from our web apps that uses this MX. I think that the reason is the bounce reported on this log. Anybody encountered a similar problem? Is there a solution?

Thanks

---------------

30/9/2017, 00:10:17 | info | NOQUEUE: reject: RCPT from unknown[62.149.156.25]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.ourmx.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.ourmx.it> proto=ESMTP helo=<smtpcmd15.ad.aruba.it>

30/9/2017, 00:15:00 | info | NOQUEUE: reject: RCPT from snt004-omc1s8.hotmail.com[65.55.90.19]: 454 4.7.1 <bounce+dbc26f.afb32-toratora1999=hotmail.it@mail.ourmx.it>: Relay access denied; from=<> to=<bounce+dbc26f.afb32-toratora1999=hotmail.it@mail.ourmx.it> proto=ESMTP helo=<SNT004-OMC1S8.hotmail.com>

**Comment by andryyy** [comment]
Hi, which Postfix log is this? We also need more log lines.

Looks like something is trying to use mailcow as relay without authentication?

**Comment by samuelebistoletti** [comment]
Hi, I took this log from Postfix Mailcow UI.

I launched `docker-compose logs postfix-mailcow | grep longhi` in SSH console in order to have the same log from Postfix. Here you can see the result

![schermata da 2017-10-02 18-07-49](https://user-images.githubusercontent.com/4482391/31087261-a9816f06-a79c-11e7-9e68-0e68de7dc5e8.png)

`postfix-mailcow_1    | Sep 20 23:12:34 mail postfix/smtpd[447]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 00:12:36 mail postfix/smtpd[1742]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 01:12:37 mail postfix/smtpd[2866]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 02:12:38 mail postfix/smtpd[3797]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 03:12:38 mail postfix/smtpd[4666]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 04:12:38 mail postfix/smtpd[5680]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 05:12:38 mail postfix/smtpd[6528]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 06:12:39 mail postfix/smtpd[6752]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 07:12:39 mail postfix/smtpd[8255]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 08:12:39 mail postfix/smtpd[9085]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
postfix-mailcow_1    | Sep 21 09:12:39 mail postfix/smtpd[10483]: NOQUEUE: reject: RCPT from unknown[62.149.156.23]: 454 4.7.1 <bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it>: Relay access denied; from=<> to=<bounce+c5e8a8.afb32-lorenzo.longhi=ordingbo.it@mail.18months.it> proto=ESMTP helo=<smtpcmd13.ad.aruba.it>
`

**Comment by samuelebistoletti** [comment]
This is an example of a customer that wrote to us because he never receives email from our applications that uses Mailcow as SMTP. I have tons of this rows in my postfix logs, reguarding also other email addresses.

**Comment by RobinFlikkema** [comment]
Is it possible that he doesn't have AUTH enabled in the application that sends email?

**Comment by samuelebistoletti** [comment]
I have it enabled. The most of the emails are successfully sent, only a few part encounter this problem.

**Comment by RobinFlikkema** [comment]
Only a few emails you say, are those specific domains? E.g. does everything to domain1.com fail while domain2.com works?
Or do some emails of domain1.com work and other not?

If it is the first, is it true that only domains that are not added to mailcow suffer from this problem?

**Comment by andryyy** [comment]
Looks like mailcow receives bounces which are not meant for it. These are not normal outgoing mails from authenticated users. These mails are returned to you as a matter of a bounce. But the recipient domain is not part of your mailcow server, and mailcow rejects to relay these mails to whatever destination they are meant for.

**Comment by samuelebistoletti** [comment]
Seems that different domains are involved, but sometimes in this same domains some emails pass others are bounced.
