### ISSUE TITLE
Error While testing Amazon SES Relay host

### ISSUE THREAD

**Issue by chaithanya1996** [mailcow/mailcow-dockerized#644]
Greetings Everyone. 

I installed mailcow in digital ocean droplet following the give tutorial. While Setting up Amazon SES as relay host and sending a test email in mailcow UI, i get following error  

Warning: require_once(inc/vars.inc.php): failed to open stream: No such file or directory in /web/inc/prerequisites.inc.php on line 2

Fatal error: require_once(): Failed opening required 'inc/vars.inc.php' (include_path='.:/usr/local/lib/php') in /web/inc/prerequisites.inc.php on line 2 

Anybody know how to solve this issue ?

Thanks in advance

**Comment by andryyy** [comment]
Should be already fixed in an update. When was your last update?

**Comment by chaithanya1996** [comment]
i just installed it now using this tutorial

https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by andryyy** [comment]
Can you run `git fetch origin master` and `git checkout origin/master data/web/inc/prerequisites.inc.php
`, please?

**Comment by chaithanya1996** [comment]
Thanks for Guidance. The issue is resolved
