### ISSUE TITLE
Autodiscover error

### ISSUE THREAD

**Issue by rafix1989** [mailcow/mailcow-dockerized#646]
I have an issue with autodiscover option. 

1. It's start when i try connect account to outlook 2013 via active sync. When i entry login, pass and server info i receive error: Cannot find server, so i thought that i will try via IMAP. and everything is ok.
2. I restart server and containers and did not help. ( I have updated version)
3. I install Wireshark, and check what happened. Screens shows what i have
![bez tytulu](https://user-images.githubusercontent.com/805762/31059698-f09a92f0-a706-11e7-85ce-09465b65cf37.png)
![bez tytulu2](https://user-images.githubusercontent.com/805762/31059699-f0a48350-a706-11e7-80a9-b68d28f174ff.png)
4. also i try connect to {mailcow.hostname}/Autodiscover/Autodiscover.xml. After input correct credential i have:  
![obraz](https://user-images.githubusercontent.com/805762/31059620-92ccaa10-a705-11e7-993f-5d865fb22a22.png)

Can you help me resolve this issue

**Comment by mritzmann** [comment]
similar to #615.

**Comment by andryyy** [comment]
The GET request reponse with ErrorCode 600 is fine.

Can you mail me your domain? I will check it. HTTPS needs to be enabled and working.

**Comment by rafix1989** [comment]
ok please give me your email address

**Comment by andryyy** [comment]
info@servercow.de

**Comment by jeremyj** [comment]
Hi, same problem here.
tcpdump between client and server shows:

Request:
```
	GET /autodiscover/autodiscover.xml HTTP/1.1
	Connection: Keep-Alive
	User-Agent: WinHttpRequest
	Host: autodiscover.example.com

```
Response:
```
	HTTP/1.1 401 Unauthorized
	Server: nginx
	Date: Wed, 04 Oct 2017 09:14:20 GMT
	Content-Type: text/html; charset=utf-8
	Transfer-Encoding: chunked
	Connection: keep-alive
	X-Powered-By: PHP/7.1.9
	WWW-Authenticate: Basic realm=""

```

**Comment by andryyy** [comment]
You cannot send a GET request to autodiscover. You also need to authenticate, see 401.

**Comment by jeremyj** [comment]
I'm not sending anything, Outlook 2013 is :-)
You can see this in @rafix1989's message too

**Comment by andryyy** [comment]
Yes, it does at first try without authentication to see what we respond with. The second try is then authenticated.

**Comment by andryyy** [comment]
So this does not indicate any error... Can you please send me your autodiscover URL via mail, too?

**Comment by jeremyj** [comment]
I understand, but after the unauthenticated request there is not an authenticated one. The client reports an error after the server response.

**Comment by nywiley** [comment]
I'm seeing the same thing as Jeremy.  Whats interesting is that it depends on whether I am on the local LAN or accessing from the outside.  When outside the local LAN to access the mailcow server, everything works fine.  When inside I get the same answers as Jeremyj ... a 401 error on http and then no further requests ... it just dies.   This is 2016 Outlook.

**Comment by andryyy** [comment]
Group policy?

**Comment by nywiley** [comment]
That was my thought, but I ran process monitor and checked all the registry accesses and its not it.

**Comment by nywiley** [comment]
What about changing the code in the autodiscover.php to throw a 600 versus a 401?

**Comment by nywiley** [comment]
Even more bizarre is that from the outside, there is never even an attempt to talk to port 80, its all done through 443, but inside the lan it tries to talk to 443 and 80 and its when it talks to 80 that it dies.  How can I get Outlook to stop talking on port 80?  I've tried the registry hacks and they dont even appear to be being accessed according to processmon

**Comment by andryyy** [comment]
401 is a valid response. It tells Outlook which mechanisms are available. I have it up and running with Outlook 2016 right now. :-/ When you are outside your LAN it seems to work, too. So it _should_ work. Could it be a policy running under an unsuitable name?
Your Windows domain name is not equal to your mail domain? 

You can still try to change the reponse in autodisocover.php. 

Can you open "https://autodiscover.domain.tld/autodiscover/autodiscover.xml" (with an without HTTPs) from within your LAN?

Split-brain DNS? Any SRV hints for autodiscover in a local DNS?

**Comment by nywiley** [comment]
The domain name and the mailserver are not the same.  But I took a machine off the domain and put it in the workgroup to test the issue of a Policy causing it.   Same result.

And yes I can open the https://autodiscover and provide credentials and get back a 600 response!

<?xml version="1.0" encoding="UTF-8"?>

-<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">


-<Response>


-<Error Id="2477272013" Time="17:28:470.685635">

<ErrorCode>600</ErrorCode>

<Message>Invalid Request</Message>

<DebugData/>

</Error>

</Response>

</Autodiscover>

**Comment by nywiley** [comment]
Maybe its the fact that the domain and the mail domain do not match.  I'm trying to migrate to a different domain and wanted to set up the mailcow as part of a separate domain name.   Maybe if the machine is part of a domain, it wont send credential for another domain when setting up outlook?  And thats why it is failing with the 401?

**Comment by nywiley** [comment]
Thats interesting, I made the same request via http://autodiscover and instead of being given a credentials box ... I got redirected to the mailcow UI web login page.

**Comment by nywiley** [comment]
And just FYI ... I synched my dockerized version today so all the code should be current.

**Comment by andryyy** [comment]
Your changes to the site will remain (they are merged), so it is still possible to be a local change. The fact it works outside your LAN sounds like a local problem.
Autodiscover is identical on http and https sites btw.
