### ISSUE TITLE
SOGo iOS Exchange Account and the contacts

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#647]
Hi,

since the first contact with mallow and SOGo don't works ActiveSync (Exchange) correct.
OK, only the the contacts.

I make a new contact in SOGo Web e.g. fon-private: 8888 the second field is fon-private: 9999
In iOS will displayed only one field fon-private: 8888 or for-private: 9999 never both
This is very sadly

jm3west

**Comment by andryyy** [comment]
Hey, that's something you will need to report to SOGo. But my guess is that they show fine in CardDAV and it is a limitation in EAS.
Can you report that to their bug tracker, please? :-)

**Comment by jm3west** [comment]
Dear André, the SOGo problem isn't your problem. I know!!!
But why do you implemented SOGo with so many errors?

ActiveSync contacts > iOS > awful (field problem)
ActiveSync calendar/tasks > iOS > awful

and this isn't new. This is from the first day

Or I must to buy a new phone. Android, maybe? :-)

**Comment by andryyy** [comment]
I've used EAS with contacts and calendars over SOGo for a long time without problems. On iOS, too. I am using it right now.

If you hit ActiveSync limitations, just use Card-/CalDAV. iOS has a natively implementation.
