### ISSUE TITLE
Oversigning protection

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#648]
Hi, I found this:

http://noxxi.de/research/breaking-dkim-on-purpose-and-by-chance.html

> The signature itself need to include all mail headers which might affect the display of the message. Each of these should be oversigned to protect against an attacker adding extra headers. The headers which obviously needs to be signed are any headers directly displayed to the user, i.e. Subject, From, To, Date and Sender. Additionally any headers affecting the display of the message should be included, i.e. Content-Type, Content-Transfer-Encoding, Content-Disposition and Mime-Version. And there are also headers which affect the future message flow or how this message is displayed in the context of others, i.e. Reply-To, In-Reply-To and References. It might also be useful to add the length of the body with the 'l' attribute as long as all headers which might affect the display of the message are included in the signature and oversigned. 

Does mailcow currently support oversigning to prevent spoofing?

**Comment by ChessSpider** [comment]
answer is no. I verified this works, meaning I can change the message-id, recipient, subject, add a reply-to header, etc..  all without failing the DKIM check. 
It is not possible to spoof/change the body of the email fortunately.  But it may in some cases be possible to hide it.

**Comment by vstakhov** [comment]
From the perspective of Rspamd:

You can specify any headers when doing the signature, e.g. `Subject:Subject`, so no `new` subject will be added. Alternatively, I can add logic do explicitly deny with `DKIM_FAIL` the cases when you have multiple unique headers as  defined by `RFC822`. Additionally, Rspamd already penalises such messages with rule `MULTIPLE_UNIQUE_HEADERS` which has quite high score. But the issue described is bad indeed.

**Comment by vstakhov** [comment]
That should be fixed by https://github.com/vstakhov/rspamd/commit/56ef361fe2a1a3b8d12f4cc2ef404c29b39b7c48 (not tested yet).

**Comment by ChessSpider** [comment]
Hi vstakhov, thanks for your reponse !

I think Mailcow also uses rspamd to sign the outgoing emails. I believe using https://rspamd.com/doc/modules/dkim_signing.html

To prevent spoofing of emails for the users of mailcow it would be best if unique headers would get double-signed by default and maybe the default signed headers could be expanded to 

```From:Sender:Reply-To:Subject:Date:Message-ID:To:Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive; ```

I saw a major organization using this as a signed headers (regardless if those headers were present or not). It does seem they forgot to do double-signing though :)

**Comment by ChessSpider** [comment]
Fyi, I tried spoofing the From: header and my message was rejected by google 


>  (host gmail-smtp-in.l.google.com[66.102.1.27] said: 550-5.7.1 [ipaddress     11] Our system has detected that this message is 550-5.7.1 not RFC 5322 compliant: 550-5.7.1 Multiple 'From' headers found. 550-5.7.1 To reduce the amount of spam sent to Gmail, this message has been 550-5.7.1 blocked. Please visit 550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant 550 5.7.1 and review RFC 5322 specifications for more information. k142si9392665wmg.149 - gsmtp (in reply to end of DATA command))

**Comment by vstakhov** [comment]
Yes, Rspamd does the same. But it is pretended to be an awful bug that breaks git mailer according to https://lwn.net/Articles/732570/ , heh.

**Comment by ChessSpider** [comment]
yeah, but multiple To: headers is fine. But as you pointed out the rspamd deals with those quite harshly:

```
Return-Path: <root@myprivatedomain.tld>
Delivered-To: cyber@companymail.tld
Received: from mail.companymail.tld ([172.22.1.5])
	by mail.companymail.tld with LMTP id cBihNWBF01mCCAAAprHitA
	for <cyber@companymail.tld>; Tue, 03 Oct 2017 08:08:00 +0000
Received: from myprivatedomain.tld (myprivatedomain.tld [9.9.9.9.9])
	by mail.companymail.tld (Postfix) with ESMTPS id B124E5E2E53
	for <cyber@companymail.tld>; Tue,  3 Oct 2017 08:08:00 +0000 (UTC)
Received: from myprivatedomain.tld (private.hostname.tld [123.123.123.123])
	(using TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by myprivatedomain.tld (Postfix) with ESMTPSA id AA89F2002CA;
	Tue,  3 Oct 2017 08:00:17 +0000 (UTC)
Received: by myprivatedomain.tld (Postfix, from userid 0)
	id 26430C0E26; Tue,  3 Oct 2017 10:00:17 +0200 (CEST)
From: My Colleague | A Daughter Company <mycollague@adaughtercompany.com>
Reply-To: hackme@example.com  <-- injected
Sender: hackerwhatever@theboss.com  <-- injected
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=adaughtercompany.com; s=mail;
	t=1507016330; bh=4ht9G50SlYlr7BPTCuy+KjNotHQlLEXbSKghIYlF3TI=;
	h=From:Subject:To;
	b=fGUynyz9L0EgYEYZ8U8d51fjEkOTAJOQ4K6DaiMnJOND5u3YsqsfsXkR33GhshHIp
	 rtRhRP3zbeHk6jPRwE7uW+DHi0gp2LoKvLZwXUAOj6KUlHKYWERZkuKs4vioJiOYD/
	 8abZfyGnVu1+IHuMSVOuiNjhCZjl+3K3PfNiH7oU=
Date: Tue, 3 Oct 2017 09:38:41 +0200
Subject: spoofedmail   <-- injected
Subject: Bij deze
Message-Id: <DoFA357ds-F0E1-49FE-9A03-478E89304625@adaughtercompany.com> <-- changed
Content-type: text/plain; boundary=foo  <-- injected
To: cyber@companymail.tld    <-- injected
To: machiel@originalrecipient.com
Authentication-Results: mail.companymail.tld; dkim=pass header.d=adaughtercompany.com; dmarc=pass (policy=quarantine) header.from=adaughtercompany.com; spf=pass smtp.helo=myprivatedomain.tld
X-Rspamd-Queue-Id: B124E5E2E53
X-Spamd-Result: default: False [9.05 / 16.00]
 FROM_HAS_DN(0.00)[]
 MID_RHS_MATCH_FROM(0.00)[]
 RCPT_COUNT_TWO(0.00)[2]
 R_SPF_ALLOW(-0.20)[+a]
 MIME_GOOD(-0.10)[text/plain]
 ARC_NA(0.00)[]
 MULTIPLE_UNIQUE_HEADERS(10.00)[To,Subject]   <-- quite harsh hitting right here
 RCVD_COUNT_THREE(0.00)[3]
 RCVD_NO_TLS_LAST(0.00)[]
 DYN_RL_CHECK(0.00)[]
 FROM_NEQ_ENVFROM(0.00)[mycollague@adaughtercompany.com,root@myprivatedomain.tld]
 MX_GOOD(-0.50)[cached: mail.tutanota.de]
 RCPT_MAILCOW_DOMAIN(0.00)[companymail.tld]
 FORGED_SENDER(0.30)[]
 ASN(0.00)[asn:12876, ipnet:51.15.0.0/17, country:FR]
 IP_SCORE(0.00)[ip: (7.91), ipnet: 51.15.0.0/17(3.96), asn: 12876(3.17), country: FR(0.08)]
 GREYLIST(0.00)[pass,body]
 REPLYTO_DOM_NEQ_FROM_DOM(0.00)[]
 HAS_REPLYTO(0.00)[hackme@example.com]
 R_DKIM_ALLOW(-0.20)[adaughtercompany.com]
 TO_DN_NONE(0.00)[]
 TO_MATCH_ENVRCPT_SOME(0.00)[]
 RCVD_VIA_SMTP_AUTH(0.00)[]
 DMARC_POLICY_ALLOW(-0.25)[adaughtercompany.com,quarantine]
X-Spam-Flag: YES
X-Spam: Yes
```

**Comment by vstakhov** [comment]
Multiple `to` are NOT fine. https://www.ietf.org/rfc/rfc5322.txt page 20

**Comment by ChessSpider** [comment]
haha, you and the RFC may think that, but google and postfix disagree with you

![spoofing](https://user-images.githubusercontent.com/2168372/31119293-bcf7084a-a830-11e7-973b-85f3042bccf0.png)

**Comment by andryyy** [comment]
We punish this with MULTIPLE_UNIQUE_HEADERS.

Thanks @vstakhov for looking into it, will update the images as soon as it hits stable.

**Comment by ChessSpider** [comment]
yes yes, my issue is not how it handles incoming emails.  My issue is mostly with how it handles outgoing emails.  (But I am of course happy and thankful for any improvements how to handle potential malicious incoming mails, with the sidenote that I do believe it is always the responsibility of the sender to properly configure DKIM. If the sender uses double signing on those headers it would fail DKIM check, DMARC check, and instant reject.  )

For extra emphasis:

> Hi vstakhov, thanks for your reponse !
> 
> I think Mailcow also uses rspamd to sign the outgoing emails. I believe using https://rspamd.com/doc/modules/dkim_signing.html
> 
> To prevent spoofing of **outgoing emails for the users of mailcow it would be best if unique headers would get double-signed by default and maybe the default signed headers could be expanded to**
> 
> `From:Sender:Reply-To:Subject:Date:Message-ID:To:Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive;`
> 
> I saw a major organization using this as a signed headers (regardless if those headers were present or not). It does seem they forgot to do double-signing though :)

**Comment by ChessSpider** [comment]
Hi @vstakhov, any chance you can implement proper double-signing and configurable signing-headers for the signing module ?

**Comment by vstakhov** [comment]
Headers could be configured for ages in Rspamd. It just lives in dkim 
module setup, not dkim_signing.

**Comment by ChessSpider** [comment]
Cool, I didn't know that. How can I configure, as I cannot find it in the
docs?
https://rspamd.com/doc/modules/dkim.html  /
https://rspamd.com/doc/modules/dkim_signing.html
Will you look into double-signing of headers in outgoing mails ? I'd really
appreciate it if you have the time.

**Comment by ChessSpider** [comment]
future reference for other parties interested, to change the headers signed by rspamd,..

create ```data/conf/rspamd/local.d/dkim.conf```:
and add the following contents:
```
sign_headers = "From:Sender:Reply-To:Subject:Date:Message-ID:To:Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive:From:Sender:Reply-To:Subject:Date:Message-ID:To:Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive;";
```

There is a problem currently in rspamd that it only signs headers which are actually present. This means that headers can still be added to the email if they were not there originally. I created https://github.com/vstakhov/rspamd/issues/1949 about this issue which is hopefully fixed soon.

**Comment by ChessSpider** [comment]
@vstakhov fixed the problem, this can be closed now 👍

**Comment by bjoe2k4** [comment]
@ChessSpider Why should there be all those mailinglist headers in the default `sign-headers` ? Won't that break immediately when posting to a mailinglist?

**Comment by ChessSpider** [comment]
@bjoe2k4 actually every post to a maillinglist would/should/could invalidate the DKIM-signing. E.g. due to different Subject, Message-Id or a changing To: address.  And with my current setup any maillinglist will also fail DMARC due to the SPF failure. Unfortunate but true.  Authenticated Received Chain is meant to prevent problems: https://en.wikipedia.org/wiki/Authenticated_Received_Chain. 

I got the list of mail-headers from an email I received from a Dutch bank. It seemed like a good default.

**Comment by bjoe2k4** [comment]
@ChessSpider sorry, but i see no need why a mailinglist **would** or **should** invalidate a DKIM signature. All these mailinglist-headers are invisible to the recipient unless the message sources are inspected. It is true that it **could** invalidate the signature if it modified some visual part of the message like subject or body, but then a good mailinglist software should strip away that signature anyways and it may replace it with its own.

I am subscribed to a handfull of mailinglists that don't edit the message at all apart from adding those mailinglist headers and a few others. And you said it yourself: if there is a dmarc policy on your domain, then SPF will fail for sure, so it is essentail that at least the DKIM signature stays valid.

I agree that ARC is a good thing meant to solve those problems, but it will take years if not decades, until one can rely on a broad adoption. Until then, i think we should not break things intentionally unless we have to.

**Comment by ChessSpider** [comment]
@bjoe2k4 most maillinglists at the least add a "footer" to your original message (Content body) with an unsubscribe link which invalidates the dkim.

**Comment by bjoe2k4** [comment]
@ChessSpider Is it really necessary to break those mailinglists that don't?

**Comment by ChessSpider** [comment]
@bjoe2k4 Your mailserver, your choice.  
In my current setup it won't be much of a difference; DKIM will likely fail. SPF will definitely fail. One of those will cause DMARC to fail. Maillinglists that I have seen change the Content-Body anyway.
ARC is the proposed solution for that problem. If the maillinglist and/or receiving mailllingserver does not implement that, there's not much I can do. 

Security is always a trade-off with usability; you have to make your own trade-off always.

**Comment by bjoe2k4** [comment]
@ChessSpider sigh, i am giving up.

Yes of course it is my choice, that's why i have removed these headers in the default set of signed headers. But shouldn't we at least provide a reasonable default set of signed headers? Just because a Dutch bank uses these headers doesn't make them the gold standard. 
Anyways, maybe the main problem is that oversigning is currently mandatory in rspamd after https://github.com/vstakhov/rspamd/issues/1949 and there is no way to disable it.
Maybe @vstakhov has a second opinion on this.

**Comment by ChessSpider** [comment]
huh? I don't know what you mean with the last statement, as far as i know you still need to manually change the configuration of rspamd. My suggestion of headers is not the default in rspamd (please correct me if I'm mistaken).
 In any case, the headers can be overriden as I described here:  https://github.com/mailcow/mailcow-dockerized/issues/648#issuecomment-350010869

There is no _mandatory_ oversigning in rspamd that I am aware of. You just need to list the header twice in the configuration file (previously to https://github.com/vstakhov/rspamd/issues/1949 it would refuse to do double-signing)

**Comment by bjoe2k4** [comment]
For me it is broken. Whatever you put in `sign_headers` will be signed, even if the header is not present. Putting it twice will actually put it three times in the signed headers. See also https://github.com/vstakhov/rspamd/issues/2136
Maybe you have any idea what i am doing wrong?

**Comment by ChessSpider** [comment]
``Whatever you put in sign_headers will be signed, even if the header is not present. ``
That is expected behavior. Otherwise someone else may add that header later and resend the message. The default of these headers are quite tame.
``Putting it twice will actually put it three times in the signed headers.``
That's a bug. Oversigning should not be mandatory. But it shouldn't break anything either if it does.

**Comment by ChessSpider** [comment]
What's the problem you're experiencing? When it signs empty headers double, or non-empty headers three times, what problem do you run into?

**Comment by bjoe2k4** [comment]
I think we should agree on the definition of oversigning. The way I see it, oversigning means you sign it `n+1`-times, where `n` is the number of times the header is present. 

According to that, if you sign a header that is not present, then you are oversigning it (`n=0` case). I would expect it not to be signed when it is not present. This is also what opendkim does. And i guess the majority of people that use rspamd have used opendkim before.

Actually the list you provided is very similar to the default of rspamd.
https://github.com/vstakhov/rspamd/blob/fb9106affc628be155fb2a4e7c83cd325c6e0202/src/plugins/dkim_check.c#L52-L57

**Comment by ChessSpider** [comment]
What's the diference between oversigning it once or twice? The effect of ``n+2``-times is the same as ``n+1`` times of oversigning.  Can you explain to me the problem you're facing? It seems to me we're now discussing implementation preferences 

NB, I do not dispute that : 
``Putting it twice will actually put it three times in the signed headers.``
is a bug. I just don't see in what use-case it would be a problem.

**Comment by bjoe2k4** [comment]
There is no difference between `n+2` and `n+1`. It's a bug but does not invalidate signatures. I think we agree at least on that.

My problem is that there is no way to configure a header to be signed only if it is present. This is not very practical, as it used to work on older versions of rspamd and this is also how opendkim works.

**Comment by ChessSpider** [comment]
> My problem is that there is no way to configure a header to be signed only if it is present. This is not very practical, as it used to work on older versions of rspamd and this is also how opendkim works.

yeah but that could open it to potential security problems. The reason of DKIM is to prevent header modification. By only signing headers if they're present, headers can be injected. Including important headers like ``CC`` or  worse, ``Reply-To``.

**Comment by bjoe2k4** [comment]
That's why you should include those unique, important headers twice if you want them oversigned, just as you described above. Instead rspamd by default is now forcing oversigning on headers that are not present, but omitting the oversigning on unique headers, which leave your potential security problems wide open.

Anyways, the most flexible solution would be to implement a second table of headers that you want to be oversigned. I have proposed such a solution to the developer in https://github.com/vstakhov/rspamd/issues/2136 and I will update it tomorrow to put more emphasis on the mandatory oversigning problem.

**Comment by ChessSpider** [comment]
I don't know what you mean. I don't see any current behavior that should result in problems. Apart from maybe an overzealous default signing list. But even that is debatable. And after having a night sleep, I think the enforced double-signing is a good thing too. Maybe it should be configurable though. 

I would argue the implementation of opendkim is wrong, based on your description.

**Comment by bjoe2k4** [comment]
OpenDKIM is developed by the Trusted Domain Project and its main author is also author/editor of the DKIM RFCs. Feel free to file a bug report there if you believe the implementation is wrong.

I am giving up here.

**Comment by ChessSpider** [comment]
It's not my intention to be dismissive; I just don't see a use case in which the behavior you described results in any kind of problem and in fact believe they're safe defaults.

**Comment by bjoe2k4** [comment]
I have provided a use case in the second paragraph of my previous comment https://github.com/mailcow/mailcow-dockerized/issues/648#issuecomment-378002474 where signatures are needlessly broken by default with the current behaviour.

**Comment by ChessSpider** [comment]
You mean maillinglists? But isn't that an argument to reduce the list of default signed headers? 
Oversigning is completely unrelated to that problem.

**Comment by bjoe2k4** [comment]
One more time, mandatory oversigning for headers that aren't present *is* the core problem here. From there you have two options:

- needlessly reduce the default list of signed headers
- keep the the default list and unnecessarily break signatures

**Comment by ChessSpider** [comment]
from the two options you presented, I agree with the first one ``needlessly reduce the default list of signed headers``.. Which I already mentioned/suggested  in https://github.com/mailcow/mailcow-dockerized/issues/648#issuecomment-378177789, https://github.com/mailcow/mailcow-dockerized/issues/648#issuecomment-378152567, after you told me the default sign list in rspamd was quite broad.

The reason why: signing headers which are not there is a security feature, as i described here https://github.com/mailcow/mailcow-dockerized/issues/648#issuecomment-378039357 . 

The signing of headers which aren't present is not the core problem; either you want dkim signing of headers or not. If you want dkim signing for those headers, you also want them oversigned due to the problems I describe above.  If you want optional double-signing, that just mean that 99% of the emails you send are vulnerable to header-injection as opposed to 0% when it's mandatory. 

If you still disagree, then lets agree to disagree..

**Comment by mkuron** [comment]
> One more time, mandatory oversigning for headers that aren't present is the core problem here.

So if I understand this correctly, @bjoe2k4's main problem is that he sends messages through his Mailcow server to a mailing list, the listserver transforms the messages (adding `List-ID` header etc.), sends it to all subscribers and the subscribers can now no longer verify the signature.

It is well-known that Mailing Lists and DKIM generally don't interact too well, see e.g. https://wiki.list.org/DEV/DKIM . The most obvious problem is modifying the body (adding a footer with a link to the listserver), but adding a mailing list tag to the subject or sender name, adding a `Reply-To`, etc. are also common.

We can't solve this issue in rspamd because we can't detect whether a message is going to a listserver and the transformation is therefore acceptable. This has to be solved on the listserver side (e.g. remove signature, perform the transformation, rewrite the `From` header, and resign with its own key). Until that is common practice, you need to refrain from using DKIM and SPF if you want to reliably use mailing lists. Not signing headers that are not present is not an option, as @chessspider said, because it allows making user-visible changes without breaking the signature.

**Comment by vstakhov** [comment]
The problem with mailing lists is long existing issue and it is usually solved by mailing lists software as following: it just removes or renames the original validated DKIM signature and adds its own signature. If your mailing list software is not doing this it is totally broken. WRT oversigning I do agree with @ChessSpider  and @mkuron: I don't think that OpenDKIM is a good example of a reference software. And the fact that its author is also a major contributor to DKIM standard means nothing: DKIM standard is quite crappy as well (but yes, we don't have anything to replace it in a sane matter).
