### ISSUE TITLE
Fatal: Dovecot is already running with PID 31

### ISSUE THREAD

**Issue by lindeto** [mailcow/mailcow-dockerized#65]
Hello,

my host has crashed. Now I get the following error message: 2017-02-23 07:06:28 master: Fatal: Dovecot is already running with PID 31 (read from /var/run/dovecot/master.pid).

Can i delete the pid-file? If so, how do i do this in the container?

Thanks in advance

**Comment by andryyy** [comment]
You can stop all containers with `docker-compose stop`, delete the container `docker-compose rm dovecot-mailcow` and restart/recreate the containers: `docker-compose up -d`

**Comment by lindeto** [comment]
It works! Thank you! :-)
