### ISSUE TITLE
Whitelist email format

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#650]
Hello,

I want to add an email with underscore to the whitelist but I get error "Record has invalid format". For example: my_name@email.com
This is forcing me to add *@email.com
Is this a bug?

**Comment by mkuron** [comment]
You can submit a pull request that changes the email validation. Underscores are valid for thr user part of an email address.

**Comment by andryyy** [comment]
Needs some more symbols and checks etc., but for now I just added the "_" char.

**Comment by catcun** [comment]
Awesome! Thank you both
