### ISSUE TITLE
Support UTF-8 in username

### ISSUE THREAD

**Issue by tioover** [mailcow/mailcow-dockerized#652]
Postfix support UTF-8 in mail address http://www.postfix.org/SMTPUTF8_README.html , e.g. 😂@example.com

**Comment by andryyy** [comment]
Yes, but do we need this❓

**Comment by tioover** [comment]
It's just cool!  ..or maybe other county people such as Japanese or Chinese... will be able to use self real name.
~~~I guess this change is simple, just modify postfix config and relax the limits of name?~~~

After all, it's not necessary feature  ... sorry my bad english.

**Comment by tioover** [comment]
Besides, if I sent a mail use UTF-8 address, server cannot receive, nor alias the mail that was sent:
~~~
To: 😂@example.com
~~~
even if catch-all !

> local-part of envelope RCPT address contains utf8 but remote server did not offer SMTPUTF8

**Comment by tioover** [comment]
If just simply add `smtputf8_enable = yes` to `main.cf`
GMail can successfully sent a mail to `😂@example.net`, but not seen in inbox.
> (SMTPUTF8 is required, but was not offered by host dovecot[172.22.1.6])

<img width="274" alt="2017-10-05 4 32 03" src="https://user-images.githubusercontent.com/930060/31198473-0ec6dce2-a91a-11e7-9c69-7c81228840f2.png">

**Comment by mkuron** [comment]
UTF8 email addresses are rarely found because they are not widely supported. But if we can support them, we should try to do so.

While outbound UTF8 should be as simple as you said, it probably takes more than just Postfix to make inbound UTF8 work: Dovecot (LMTP) and Rspamd (milter) might need config changes (or even patches) too.

**Comment by tioover** [comment]
@mkuron You're right, added `smtputf8_enable = yes` but:
> 32E8664445: to=<t@ioover.net>, orig_to=<😂@ioover.net>, relay=dovecot[172.22.1.6]:24, delay=3.9, delays=3.8/0.02/0.09/0, dsn=5.6.7, status=bounced (SMTPUTF8 is required, but was not offered by host dovecot[172.22.1.6])

Dovecot seem like don't support `SMTPUTF8`
https://dovecot.org/list/dovecot/2016-November/106029.html

It's not easy, I will close this issue.
