### ISSUE TITLE
Let's encrypt does not renew certificates

### ISSUE THREAD

**Issue by longtawan** [mailcow/mailcow-dockerized#654]
Hi there,

I know that there is a similar issue in that Forum but I think it doesn't really match my issue.
I set up mailcow dockerized a couple of month before and eveything went right.

Since October 2nd the Let's Encrypt certs are not valid anymore.

As far as I understood the process I ran docker-compose restart acme-mailcow but I then ended in errors.

Where did I go wrong?

Herzlichst,

Ingo

**Comment by Braintelligence** [comment]
Are you running the latest version? (update.sh)

Also, you shouldn't give away domains and IP addresses together with the software they're running on a public accessible platform, just saying.

**Comment by longtawan** [comment]
One more thing: I just wanted to replace the Let's Encrypt certs with certs I created but it seems that I don't know where to put them.
I used /etc/ssl/mail/... but obviously they weren't recognized.

**Comment by longtawan** [comment]
I forgot: I updated my mailcow with update.sh a couple of hours ago.

**Comment by mritzmann** [comment]
> but it seems that I don't know where to put them

Replace `data/assets/ssl/key.pem` and `data/assets/ssl/cert.pem` and set `SKIP_LETS_ENCRYPT=y` in `mailcow.conf`.

**Comment by longtawan** [comment]
I did it, but Server stated: certificate Let's Encrypt is not valid since Ocober 2nd...
It seems that my own certificates where not used by Mailcow.

**Comment by Braintelligence** [comment]
Did you restart at least nginx after providing your own certificates?

**Comment by longtawan** [comment]
Yes.
I restarted nginx and the whole docker system.

**Comment by longtawan** [comment]
Currently I try to use acme again

acme-mailcow_1       | acme-client: bad exit: netproc(218): 1
acme-mailcow_1       | acme-client: bad exit: challengeproc(221): 1
acme-mailcow_1       | Verified hashes.
acme-mailcow_1       | Retrying in 30 minutes...

**Comment by longtawan** [comment]
Sorry :-(

**Comment by Braintelligence** [comment]
Please stop spamming comments. Update your old answers, if you would respond to yourself instead, by editing them, you're flooding my inbox.

You can find more information here: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/ 

The docker-compose.yml tells you where the certificates from the acme container are stored...
