### ISSUE TITLE
Remove php vendor dir from git

### ISSUE THREAD

**Issue by mablae** [mailcow/mailcow-dockerized#655]
As a best practive the web/lib/vendor dir should not versionized by git. 

Better put it into `.gitignore` and let the vendors be installed at build time?

**Comment by mkuron** [comment]
The trouble is: we don‘t have a “build time”. We only have the update.sh script and not everybody uses that — many people prefer dealing with git and docker-compose themselves. I assume you meant to use a package manager like Composer to get the external libraries? A better solution would be to use git submodules as that neither requires calling an extra script at “build time” nor using anything but git. Also, we probably don’t need the dependency handling and pre-compiling that Composer can do.

**Comment by mablae** [comment]
With build time I meant to put it into the `Dockerfile`

**Comment by mkuron** [comment]
The PHP scripts (data/web directory) are not really part of any Dockerfile right now. That is intentional so that they can be changed without rebuilding. I guess we could move the vendor directory to inside the container and keep data/web as-is.

What do you think about using git submodules instead?

**Comment by mablae** [comment]
I would always prefer composer over git submodules.

**Comment by mkuron** [comment]
Any specific reasons? We likely don‘t need dependency handling.

**Comment by mablae** [comment]
> We likely don‘t need dependency handling.
Then why suggest even submodules? Why have a `composer.json` at all? 

Just extract the tar.gz and you are done ;)

Sorry.

**Comment by mkuron** [comment]
That would require doing it at Docker build. If the libraries were submodules, they‘d “feel” like they were part of the Mailcow repo. Also, submodules wouldn’t necessarily have dependency handling.
