### ISSUE TITLE
Using mailcow with user namespaces

### ISSUE THREAD

**Issue by svengo** [mailcow/mailcow-dockerized#656]
I've configured docker to run with [user namespaces](https://docs.docker.com/engine/security/userns-remap/). To start mailcow and avoid permission problems I needed to add ``userns_mode: "host"`` to the following services:

- dovecot-mailcow
- nginx-mailcow
- acme-mailcow
- fail2ban-mailcow
- ipv6nat

Maybe you can include these settings to the default ``docker-compose.yml``.

**Comment by mkuron** [comment]
ipv6nat and fail2ban make sense, as they need to modify the firewall settings and are privileged. Why do you need it for the other three containers though?

**Comment by svengo** [comment]
acme needs access to `/var/run/docker.sock`. dovecot and nginx are producing `Permission denied` errors without `userns_mode: "host"`:

    Attaching to mailcowdockerized_dovecot-mailcow_1
    dovecot-mailcow_1    | /docker-entrypoint.sh: line 18: /usr/local/etc/dovecot/sql/dovecot-dict-sql.conf: Permission denied
    [...]
    sven@fangorn:~/docker/mailcow-dockerized$ docker-compose logs nginx-mailcow
    Attaching to mailcowdockerized_nginx-mailcow_1
    nginx-mailcow_1      | /bin/sh: can't create /etc/nginx/conf.d/listen_plain.active: Permission denied
    [...]

**Comment by JOduMonT** [comment]
I also tried with userns_mode
as @mkuron mention and I notice, only ipv6nat and fail2ban complain about privilege.

**Comment by svengo** [comment]
A little update:

### dovecot-mailcow
I didn't manage to get dovecot running *without* `userns_mode: host`:

    dovecot-mailcow_1    | /docker-entrypoint.sh: line 24: /usr/local/etc/dovecot/sql/dovecot-dict-sql-quota.conf: Permission denied
    dovecot-mailcow_1    | Jul 27 12:54:01 mail cron[61]: (*system*) WRONG FILE OWNER (/etc/crontab)
    dovecot-mailcow_1    | Jul 27 12:54:01 mail cron[61]: (*system*imapsync) WRONG FILE OWNER (/etc/cron.d/imapsync)
    dovecot-mailcow_1    | Jul 27 12:54:01 mail cron[61]: (*system*dovecot-sync) WRONG FILE OWNER (/etc/cron.d/dovecot-sync)

### postfix-mailcow
Postfix runs without  `userns_mode: host` but I had to do a `chown 231072:231072 data/conf/postfix` before. The problem is that `data/Dockerfiles/postfix/postfix.sh` creates some files in the `sql` subdirectory. Maybe it would be better to use a template system like confd.

### nginx-mailcow
I get an error running without without `userns_mode: host`, I think it is also a problem with directory permissions:

    nginx-mailcow_1      | /bin/sh: can't create /etc/nginx/conf.d/listen_plain.active: Permission denied

### dockerapi-mailcow
Dockerapi needs access to the docker socket file `/var/run/docker.sock`. Without  `userns_mode: host` there is an error: 

    dockerapi-mailcow_1  | Traceback (most recent call last):
    dockerapi-mailcow_1  |   File "/server.py", line 13, in <module>
    dockerapi-mailcow_1  |     docker_client = docker.DockerClient(base_url='unix://var/run/docker.sock', version='auto')
    dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 38, in __init__
    dockerapi-mailcow_1  |     self.api = APIClient(*args, **kwargs)
    dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 152, in __init__
    dockerapi-mailcow_1  |     self._version = self._retrieve_server_version()
    dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 177, in _retrieve_server_version
    dockerapi-mailcow_1  |     'Error while fetching server API version: {0}'.format(e)
    dockerapi-mailcow_1  | docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))

### ipv6nat  and netfilter-mailcow
Ipv6nat  and netfilter-mailcow need `userns_mode: host` because of privileged mode:

    ERROR: for ipv6nat  Cannot create container for service ipv6nat: privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode
    
    ERROR: for netfilter-mailcow  Cannot create container for service netfilter-mailcow: privileged mode is incompatible with user namespaces.  You must run the container in the host namespace when running privileged mode
