### ISSUE TITLE
SyncJob bug: delete mails from destination always checked

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#657]
Hello,

I just noticed that I cannot uncheck the "delete mails from destination not present on source" check box.

**Comment by andryyy** [comment]
Thanks! :)

**Comment by roswitina** [comment]
Why was the file mailcow-setup-relayhost. sh deleted from DEV?

**Comment by andryyy** [comment]
It is integrated in the ui now. 

Mit besten Grüßen
André Peters
