### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by apoc4lyps** [mailcow/mailcow-dockerized#658]
Hi, the latest commit f0df390d12fcda51139c0d47fdfee957197c653d on site.conf causes ERR_SSL_PROTOCOL_ERROR with Chrome and Firefox. After removing ssl_session_tickets from config file https access is working again.

There is also a duplicated entry for Strict-Transport-Security Header.

**Comment by andryyy** [comment]
This was reverted, wasn’t it?

**Comment by andryyy** [comment]
Hm. No, it wasn't. But a previous change caused these errors, which indeed was reverted.

I cannot reproduce these errors, but I will check it. Anyone else? :-/

Edit: Are you running mailcow behind a RP?

**Comment by apoc4lyps** [comment]
no Reverse Proxy, default mailcow setup on Ubuntu 16.04.3 LTS. I validated with default settings and without ssl_session_ticket options agains ssllabs

with ssl_session_ticket
![image](https://user-images.githubusercontent.com/10954235/31319439-cc8d9274-ac63-11e7-8a00-83ef9ef86560.png)

without ssl_session_ticket
![image](https://user-images.githubusercontent.com/10954235/31319476-3de5aaa6-ac64-11e7-8b9e-78e8a04d2a9f.png)

**Comment by andryyy** [comment]
I have many installations live, I don't see these problems anywherey. :-/

Do you run the latest code?

**Comment by apoc4lyps** [comment]
yes. run update script and removed all modifications. for me it is ok with the site.conf modification, just wanted to give some feedback ;)

On Sunday, October 08, 2017 22:25 CEST, André Peters <notifications@github.com> wrote:
 
I have many installations live, I don't see these problems anywherey. :-/
Do you run the latest code?
