### ISSUE TITLE
32bit systems?

### ISSUE THREAD

**Issue by Sophrinix** [mailcow/mailcow-dockerized#659]
The pre reqs say this image requires a 64bit system. 
In order to run this on a 32 bit intel, I am assuming I would have to recompile all the software?
Are there build scripts anywhere to facilitate this? I have a 32 bit version of docker running, so I know that part is covered. Any help would be much appreciated it.

**Comment by mkuron** [comment]
Just run `docker-compose build` whenever `docker-compose pull` is suppose to be performed. Unfortunately Docker Hub doesn‘t support multiple architectures, so we can only provide pre-built amd64 images.
