### ISSUE TITLE
SyncJob: impossible to modify the sync folderH

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#663]
Hello,

Small bug on the SyncJob, I cannot modify the sync sub-folder once created.

**Comment by andryyy** [comment]
Thanks. 👍

**Comment by etique57** [comment]
I just updated, but unfortunately the bug seems to be still here.

My exact usecase is that right now the sub-folder is GMail and I would like to switch it to the root (so empty).

**Comment by andryyy** [comment]
It is not in master yet.

**Comment by etique57** [comment]
ah ok, understood :)
