### ISSUE TITLE
Maxage for Syncjob

### ISSUE THREAD

**Issue by Skydiver84de** [mailcow/mailcow-dockerized#671]
Hi,

looks like the maxage setting in sync job does not save the value "0". All Values 1 and greater are saved. If "0" is entered it is not saved and the old value (e.g. 1) is displayed after saving.

If a negative value is entered -> "0" is saved and displayed.

Greetings
Mario

**Comment by andryyy** [comment]
Thanks, will be fixed with the next merge.

**Comment by Skydiver84de** [comment]
Thank you! :-)
