### ISSUE TITLE
Disable ClamAV

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#672]
Hi,

I’m running the letest version of mailcow but ClamAV is taking up too much RAM and CPU and crashes my system daily, I looked around and someone mentioned to comment it out but im not sure where.

Can someone point me in the right direction please?

**Comment by andryyy** [comment]
Hi, you can set SKIP_CLAMD=y in mailcow.conf and run docker-compose up -d 👍

**Comment by ghost** [comment]
Thank you, that sorted it :)
