### ISSUE TITLE
Appointment times differ between iOS and WebUI

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#675]
Hi,

I just migrated from 0.14 to mailcow-dockerized. I'm on 40506d30526886ee681a3b7257c0cccf33bcc37a.
I set up my iPhone (iOS 10.3.3 14G60) with caldav which worked fine.

I look at a specific appointment. Example:
WebUI: Saturday, October 21th 2017 1900 hours
iOS: Saturday, October 21th 2017 1700 hours

So there is a time difference of 2 hours obviously. The appointment's correct time is 1700 hours btw.

mailcow.conf:
`TZ=Europe/Berlin`

What did I do wrong?

**Comment by Braintelligence** [comment]
This is a wild guess but I think the timezone settings of your iPhone concerning the calendar are wrong. Does CalDAV specify the timezone within events?

**Comment by imp1sh** [comment]
I set the iPhone to fixed timezone: Berlin.
Now it seems to be working but I still don't understand because it was the WebUI that displayed it wrong. 
I will close this though.

**Comment by Braintelligence** [comment]
This is strange, if you set the timezone in mailcow.conf and your browser doesn't override it, then the time should be displayed correctly. I have the same setting and everything's fine.

**Comment by imp1sh** [comment]
Well I figured out, that the issue was with importing:
Here is an example appointment:
```
BEGIN:VEVENT
UID:1ef159cc10
DTSTAMP:20171006T092748Z
CREATED:20171006T092748Z
LAST-MODIFIED:20171006T092748Z
SUMMARY:Eat lots of ice cream
DTSTART;TZID=Europe/Berlin:20171009T190000
DTEND;TZID=Europe/Berlin:20171009T230000
LOCATION:
DESCRIPTION:
CATEGORIES:
END:VEVENT
```
The WebUI displays this event as 21:00 hours. Any clues?
Newly created appointments are being processed correctly.

**Comment by Braintelligence** [comment]
Mine also contain this:
```
DTSTART;TZID=Europe/Berlin:20171025T133000
DTEND;TZID=Europe/Berlin:20171025T150000
```
But also this at the top portion:
```
BEGIN:VCALENDAR
PRODID:+//IDN bitfire.at//DAVdroid/1.9-gplay ical4j/2.x
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
TZURL:http://tzurl.org/zoneinfo/Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
```

**Comment by imp1sh** [comment]
VTIMEZONE wasn't in my file. I added it. Still having the same problems...
I fear this is a SOGO specific error and should be reported there, right?
Nothing mailcow can do about it I guess.

**Comment by Braintelligence** [comment]
If you imported this, maybe a SOGo restart after import may help?

**Comment by imp1sh** [comment]
My workaround was to import the ics files on the iPhone which worked just fine.
