### ISSUE TITLE
Server Side filters

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#676]
Hi,

I just migrated from 0.14 to mailcow-dockerized. I'm on 40506d30526886ee681a3b7257c0cccf33bcc37a.
Server side mail filters don't work any more. I just set up thunderbird with sieve plugin and I can see that my old sieve settings are basically still there.

When I look into the WebUI though there are no filters in:
Preferences - Mail - Filters

Did I do something wrong or what is happening here? It would be very nice to be able to continue using my older rules since it would mean a lot of work for all mailboxes to setup the filters manually one again via WebUI.

Thank you.

**Comment by imp1sh** [comment]
When I setup filters via Sogo interface they doesn't work either.

**Comment by andryyy** [comment]
Hi,
We would need Dovecot logs when this is happening (or not happening). Could you please also update?

**Comment by imp1sh** [comment]
Here's postfix:
```
Oct 24 01:48:10 srv115 postfix/qmgr[328]: E83A28003F: from=<lede-dev-bounces+surname=domain.e@lists.infradead.org>, size=6643, nrcpt=1 (queue active)tfix/lmtp[6553]: E83A28003F: to=<myperonal@ema.il>, relay=dovecot[fd4d:6169:6c63:6f77::2]:24, delay=0.42, delays=0.36/0/0/0.05, dsn=2.0.0, status=sent (250 2.0.0 <myperonal@ema.il> 6ExtEtqb7lniEwAAScn98A Saved)
Oct 24 01:48:10 srv115 postfix/smtpd[6548]: disconnect from bombadil.infradead.org[65.50.211.133] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7fix/postscreen[6537]: CONNECT from [181.143.94.74]:59353 to [172.22.1.5]:25
```
Corresponding dovecot:
```
dovecot-mailcow_1    | Oct 24 01:48:10 srv115 dovecot: lmtp(mypersonal@ema.il): 6ExtEtqb7lniEwAAScn98A: sieve: msgid=<17fab8bf-d959-eb61-b322-ad63ce988cdc@gmail.com>: stored mail into mailbox 'INBOX'
```
After migration to dockerized sogo interface did not show any filters at all. Those given in attached screenshot I just created out of desperation. Still not working though.
Also Screenshot of Thunderbird client with sieve plugin showing sieve filters that were migrated from non-dockerized installation.
![screenshot_2017-10-28_10-23-33](https://user-images.githubusercontent.com/3486156/32132826-4a65b2f0-bbcb-11e7-9105-7162fc313ca3.png)
![screenshot_2017-10-28_10-23-56](https://user-images.githubusercontent.com/3486156/32132827-4a82b58a-bbcb-11e7-8dd3-680cef416f59.png)
![screenshot_2017-10-28_10-27-38_edited](https://user-images.githubusercontent.com/3486156/32132828-4a9f2724-bbcb-11e7-906b-dc49da773524.png)

**Comment by th3noname** [comment]
I can confirm that sieve filters created in Sogo are not acutally applied. They don't appear within the mailboxes sieve folder and don't work. If i create the same filter with the sieve Thunderbird plugin the script gets created and works.

EDIT: I have a fresh mailcow installation from two days ago.

**Comment by andryyy** [comment]
I cannot confirm this. Filters are created.

You need to check a filter as active (checkbox left to the filter name) in SOGo and click the save button.

**Comment by th3noname** [comment]
I did exactly what you said without success. Then i restarted the complete mailcow stack and tried again and now it works. Strange. 
Well it works now.

**Comment by imp1sh** [comment]
After the following procedure my filters are working again, too.
I deleted all filter groups in sieve and all filter set in Sogo web UI.
Then I recreated the filters manually in Sogo web UI.

**Comment by stevesbrain** [comment]
Yeah, all created filters have always worked for me - odd that they weren't for you guys, but glad they are now :)
