### ISSUE TITLE
Changing SOGo Theme Colors

### ISSUE THREAD

**Issue by nickian** [mailcow/mailcow-dockerized#679]
I'm having a hard time finding information about how to change the color theme of SOGo. I found some color palettes in this file: 

/var/lib/docker/overlay2/2099c77a52824cd02b338a2ef0b887018cc7c25abad67583247ea981ce2da1c1/merged/usr/lib/GNUstep/SOGo/WebServerResources/js

That look like this after I "beautify" the minified JS. 

```
function e(e, t, n, r, i) {
        r.definePalette("sogo-green", {
            50: "eaf5e9",
            100: "cbe5c8",
            200: "aad6a5",
            300: "88c781",
            400: "66b86a",
            500: "56b04c",
            600: "4da143",
            700: "388e3c",
            800: "367d2e",
            900: "225e1b",
            A100: "fafafa",
            A200: "69f0ae",
            A400: "00e676",
            A700: "00c853",
            contrastDefaultColor: "dark",
            contrastLightColors: ["300", "400", "500", "600", "700", "800", "900"]
        }), r.definePalette("sogo-blue", {
            50: "f0faf9",
            100: "e1f5f3",
            200: "ceebe8",
            300: "bfe0dd",
            400: "b2d6d3",
            500: "a1ccc8",
            600: "8ebfbb",
            700: "7db3b0",
            800: "666666",
            900: "222222",
            A100: "d4f7fa",
            A200: "c3f5fa",
            A400: "53e3f0",
            A700: "00b0c0",
            contrastDefaultColor: "light",
            contrastDarkColors: ["50", "100", "200"]
        }), r.definePalette("sogo-paper", {
            50: "fcf7f8",
            100: "f7f1dc",
            200: "ede5ca",
            300: "e6d8ba",
            400: "e2d2a3",
            500: "d6c48d",
            600: "baa870",
            700: "857545",
            800: "524517",
            900: "433809",
            1000: "000000",
            A100: "ffffff",
            A200: "eeeeee",
            A400: "bdbdbd",
            A700: "616161",
            contrastDefaultColor: "dark",
            contrastLightColors: ["800", "900"]
        }),r.definePalette("sogo-dark", {
            50: "fafafa",
            100: "f2f2f2",
            200: "e8e8e8",
            300: "dfdfdf",
            400: "dedede",
            500: "d0d0d0",
            600: "b7b7b7",
            700: "828282",
            800: "595959",
            900: "444444",
            1000: "000000",
            A100: "ffffff",
            A200: "eeeeee",
            A400: "bdbdbd",
            A700: "616161",
            contrastDefaultColor: "dark",
            contrastLightColors: ["800", "900"]
        }), r.theme("default").primaryPalette("sogo-dark", {
            default: "900",
            "hue-1": "400",
            "hue-2": "800",
            "hue-3": "A700"
        }).accentPalette("sogo-dark", {
            default: "500",
            "hue-1": "A100",
            "hue-2": "300",
            "hue-3": "A700"
        }), DebugEnabled || (e.debugEnabled(!1), t.debugInfoEnabled(!1), i.disableWarnings(), r.generateThemesOnDemand(!0)), n.interceptors.push("AuthInterceptor"), n.interceptors.push("ErrorInterceptor")
    }
```

I tried modifying these and added this "sogo-dark" theme of my own, then restarted SOGo, but nothing changes.

I also tried inspecting elements in the browser and finding where in the CSS file they were. For example, for the top bar with the date, I found these CSS properties:

md-toolbar.md-default-theme:not(.md-menu-toolbar), md-toolbar:not(.md-menu-toolbar) {
    background-color: rgb(77,128,128);
    color: rgba(255,255,255,0.87);
}

In this file: mydomain.com/SOGo.woa/WebServerResources/css/theme-default.css

After editing that file directly and replacing those RGB colors with my own, restarting SOGo, and clearing my cache, nothing changes.

Is there an easier way of making color changes here to the UI? I am really disliking how Angular does this.

Thanks.

**Comment by nickian** [comment]
Weird. The updated colors randomly started showing up today. Are these files cached on the server side? I even tried restarting the memcached docker container the other day, but that didn't do the trick. Maybe it's some other caching mechanism?

**Comment by ashiq54689** [comment]
I think the best way to do this is to edit theme-blue.css and theme-blue.js from /opt/mailcow-dockerized/data/Dockerfiles/sogo/. Then rebuild the sogo-mailcow container and rerun all the container.

**Comment by zietbukuel** [comment]
@ashiq54689 I cannot find this file here. I only have these files:

`Dockerfile  acl.diff  bootstrap-sogo.sh  stop-supervisor.sh  supervisord.conf  syslog-ng.conf`

**Comment by DatAres37** [comment]
> @ashiq54689 I cannot find this file here. I only have these files:
> 
> `Dockerfile acl.diff bootstrap-sogo.sh stop-supervisor.sh supervisord.conf syslog-ng.conf`

That's because the themes have been removed half a year ago: https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/
See #2144
