### ISSUE TITLE
Question: mailcow-dockerized and Gitlab

### ISSUE THREAD

**Issue by felixoi** [mailcow/mailcow-dockerized#68]
Hello,

I have a little problem. I switched from mailcow to mailcow-dockerized because I saw it's recommended.
With mailcow Gitlab was automatically sending the emails but with mailcow-dockerized this is not functional. What I have to do?

Thanks,
felixoi

**Comment by andryyy** [comment]
Hi, we need logs or anything to start with.

**Comment by felixoi** [comment]
Ok.
The problem is I don't have much information. Normally `gitlab `is sending the emails trough `sendmail `or `postfix` but if `postix` is dockerized and `gitlab` can't reach `postfix`. There is nothing in the postfix log what tells me there was a new email regonized.

**Comment by felixoi** [comment]
I could connect through smtp I think but it would be nice to support the easy way.

**Comment by LucaDev** [comment]
For now just use SMTP - it's better than nothing :P In the end there shouldn't be a big difference between sendmail and SMTP
