### ISSUE TITLE
Autodiscover: SSL negotiation wasn't successful

### ISSUE THREAD

**Issue by Ringelnatz** [mailcow/mailcow-dockerized#681]
I can't get autodiscover (or even manual Exchange setup in Outlook) working with my fresh mailcow installation (no reverse proxy, bound to dedicated ip address). https://autodiscover.domain.tld shows up in the browser with valid certificate and entering credentials at /Autodiscover/Autodiscover.xml also works.

I ran the Microsoft Connectivity test:
![microsoft_remote_connectivity_analyzer](https://user-images.githubusercontent.com/12671383/31998577-9baee826-b990-11e7-89a0-8bddfbf3b941.png)
When running this test I have the following line in the nginx log:
```
nginx-mailcow_1      | 40.85.91.8 - - [25/Oct/2017:12:13:23 +0000] "GET /Autodiscover/Autodiscover.xml HTTP/1.1" 401 5 "-" "Microsoft-Server-ActiveSync/12.0+(TestExchangeConnectivity.com)"
```

I can't see where there could be a problem with the certificate installation.

**Comment by Oratorian** [comment]
I got the problem when i call https://autodiscover.doamin.tld/autodiscover/autodiscover.xml

i get the error 600 invalid request

**Comment by Ringelnatz** [comment]
That's not a problem but the expected behaviour. Unfortunately in my case it does not get to this point :-/

**Comment by Oratorian** [comment]
Nevermind ,https://testconnectivity.microsoft.com/ shows me the same result.

I got no SSL cert but my site is using one.

**Comment by mkuron** [comment]
@Ringelnatz‘s problem looks like your webserver and the analyzer don‘t have a common supported TLS cipher. Outlook of course supports the necessary ciphers to work with Mailcow, but I suspect the analyzer might not fully match Outlook. You could try changing the supported ciphers in the nginx config.

**Comment by Oratorian** [comment]
Ok, i tested the dev Branch which should obisouly supporting Office2016.

But Office2016 still cant get the information.

For MSOffice16 Outlook i had to use the ->OLCFG.exe which seems to work as a workaround.
My Mobile Office just worked like a charm. Same Setup as the Native Adnroid Mailclient.
Found in #615 Post by ChessSpider

**Comment by Ringelnatz** [comment]
@mkuron I am using the built in nginx without any reverse proxy. Why is the connectivity test working [here](https://github.com/mailcow/mailcow-dockerized/issues/510#issuecomment-322765505) and not with my installation?

It's not only the auto discovery. I can't get ActiveSync accounts working with macOS Outlook, Apple Mail, iOS Mail, ... (i think Apple Mail connects to domain.tld instead of mail/autodiscover.domain.tld??)

Is this "workaround" setup option for the mac version too?

EDIT: At least it's working with the built in mail app in Windows 10 🎉 🎉 🎉

**Comment by mkuron** [comment]
Outlook 2016 is a hit-and-miss game in terms of autodiscovery. It doesn‘t work in all versions, not in Office 365 and not in click-to-run installs. If you can, just downgrade to Outlook 2013.

MacOS Outlook doesn‘t support ActiveSync. Apple Mail doesn‘t support ActiveSync or autodiscovery. iOS Mail should work fine though.

If Windows 10 Mail is working, then your server is set up correctly. The workaround with the SSL ciphers should not be necessary for any current operating system.

**Comment by Ringelnatz** [comment]
> MacOS Outlook doesn‘t support ActiveSync. Apple Mail doesn‘t support ActiveSync or autodiscovery. 

Okay, I actually have an Exchange account running in Apple Mail and thought Exchange and ActiveSync mean the same thing (in iOS for example I have to add an Exchange account to use ActiveSync).
Thanks for clarifying the main issue here (using Outlook on mac), and who could know that Microsofts Connectivity tester is absolutely not informative when testing working setups.

> iOS Mail should work fine though.

iOS shows a certificate warning when adding the account. The certificate shown is the one from the web server at domain.tld, not for the mailcow server that sould be autodiscovered.
