### ISSUE TITLE
Mailcow rejects SEnder

### ISSUE THREAD

**Issue by Oratorian** [mailcow/mailcow-dockerized#683]
NOQUEUE: reject: RCPT from domain.com[someip]: 553 5.7.1 <user1@domain.com>: Sender address rejected: not owned by user user2@domain.com; from=<user1@domain.com> to=<user@somemailhost.com> proto=ESMTP helo=<www.domain.com>

How can i configure mailcow to let user2@domain.com send mail with user1@domain.com
without adding an alias. The problem is.
I cant specifie user1@domain.com as alias because it is needed as phisical address with a mailbox.
Is there a way to get around that error?

**Comment by Oratorian** [comment]
Solution found on Website thx

**Comment by rtulke** [comment]
where is the solution ?  have the same problem

**Comment by MarkusP** [comment]
You can find the solution for this error message here:
SMTP Error (553) - 5.7.1 <user@otherdomain.de>: Sender address rejected: not owned by user sender@domain.de

https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-disable_sender_verification/
