### ISSUE TITLE
Emails kind of lost while transfer

### ISSUE THREAD

**Issue by mrenker** [mailcow/mailcow-dockerized#687]
Hi,
I just transferred my Mails from my old provider to my mailcow instance.
My problem is, that the count of Mails that are in my inbox increased in the admin panel, but SOGo is just showing 2 of them. 
Does any one know, where the problem is?

**Comment by stevesbrain** [comment]
@smillingDeath Check file permissions - what user + group are they owned by (the actual mail files)?

**Comment by mrenker** [comment]
@stevesbrain  Where are those files located? I searched the postfix cointainer, but found none

**Comment by stevesbrain** [comment]
@smillingDeath They are in the Vmail volume. You can see where they are like this:

```bash
### Here we list our volumes to see the name of the vmail one
[root@mail mailcow-dockerized]# docker volume ls
DRIVER              VOLUME NAME
local               mailcowdockerized_crypt-vol-1
local               mailcowdockerized_dkim-vol-1
local               mailcowdockerized_mysql-vol-1
local               mailcowdockerized_postfix-vol-1
local               mailcowdockerized_redis-vol-1
local               mailcowdockerized_rspamd-vol-1
local               mailcowdockerized_vmail-vol-1

### Here we inspect the vmail volume to get more information on it - specifically, its mountpoint
[root@mail mailcow-dockerized]# docker volume inspect mailcowdockerized_vmail-vol-1
[
    {
        CreatedAt: 2017-10-20T15:14:40+10:30,
        Driver: local,
        Labels: {
            com.docker.compose.project: mailcowdockerized,
            com.docker.compose.volume: vmail-vol-1
        },
        Mountpoint: /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data,
        Name: mailcowdockerized_vmail-vol-1,
        Options: {},
        Scope: local
    }
]

### Here, we check permissions on a particular mailbox - for the email test@domain.com
[root@mail mailcow-dockerized]# ls -ls /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.com/test/cur/
total 4
4 -rw------- 1 5000 5000 1017 Nov 26  2014 '1416978565.M302717P5486.mail.domain.com,S=1017,W=1044:2,'
```

So unless you've modified something, each mail file should be 5000:5000 UID and GID for ownership. What you can do is:

```bash
chown -R 5000:5000 /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/*
```

Then ```docker-compose down; docker-compose up -d``` and you that'll fix any permissions-based errors for SOGo. I had the same issue when I rsync'd my mail across, as I brought it over with permissions attached, so I had to do this exact thing :)

**Comment by mrenker** [comment]
@stevesbrain thanks for you help, but sadly that didn´t work out...
There actually just two files with the correct permission in the folder. Could this be a database problem? 
Like the links to the files are still there, but the actual files aren´t?

**Comment by stevesbrain** [comment]
@smillingDeath Ah, sorry that wasn't the solution then! So the two files that are in there - these don't show up at all in SOGo? What about in your IMAP/POP3 client?
