### ISSUE TITLE
support for dynamic Forwarding Hosts under admin configuration

### ISSUE THREAD

**Issue by pandit77** [mailcow/mailcow-dockerized#691]
When adding "Forwarding Hosts" in admin/config interface the IP address is only resolved once.
this could be problematic if mailcow server is also used as mail relay from clients/servers connected via standard customer access line with dynamic address or if domain is moved to some other provider and thus getting new IP address.
it would be nice to have some kind of knob, which  enables regular check if Forwarding Hosts is still resolved to the same address or even do a check every time a clients connects to the server.
or if this is not possible, maybe have some daemon running to check if host still resolves to the same ip address.

**Comment by mkuron** [comment]
> it would be nice to have some kind of knob, which enables regular check if Forwarding Hosts is still resolved to the same address or even do a check every time a clients connects to the server.

It cannot be done at the time of connection because rspamd can only handle IP addresses in a redis map. Periodic updating is feasible though and would be easy enough to implement.

> if domain is moved to some other provider and thus getting new IP address

Domains don‘t move between email providers that often though and mail servers don‘t usually switch IP addresses very often, so dynamic resolutuion wasn‘t a design goal here. It was mainly meant as a help in migration (i.e. when you have old mail accounts forwarding messages to your new ones).

> this could be problematic if mailcow server is also used as mail relay from clients/servers connected via standard customer access line with dynamic address

Why do you need the forwarding hosts feature here? If your relay client uses authentication, it is never even checked against the list.

**Comment by pandit77** [comment]
> It cannot be done at the time of connection because rspamd can only handle IP addresses in a redis map. Periodic updating is feasible though and would be easy enough to implement.

ok understand

>  Domains don‘t move between email providers that often though and mail servers don‘t usually switch IP addresses very often, so dynamic resolutuion wasn‘t a design goal here. It was mainly meant as a help in migration (i.e. when you have old mail accounts forwarding messages to your new ones).`

that is of course not a standard use case. but it could happen

> Why do you need the forwarding hosts feature here? If your relay client uses authentication, it is never even checked against the list.

i use my homeserver for all mailing stuff fetchmail catches all my mails from several accounts also those not handled by my own maillcow server. i often use mutt as my client of choice 
when ever i try to send a mail from mail client not using an address configured on my mailcow server and my public ip is not listed in forwarding hosts i receive an error:

`<xxx@xxx.de>: host mail.xxx.de[185.xxx.xxx.170] said: 550
    5.7.1 Service unavailable; client [62.158.xxx.xxx] blocked using
    zen.spamhaus.org (in reply to RCPT TO command)
`

so the mail system on mailcow refuses to send the mails.
when i put my dynamic ip under forwarding hosts there is no check at all, and messages can be send, other messages can be bounced etc....

I hope that i was able to explain the issue in an understandable way

**Comment by mkuron** [comment]
Ok, the correct solution to your actual problem would be to check your mail client‘s configuration and make sure it uses authentication and not port 25, but 587 or 465.

**Comment by pandit77** [comment]
Thanks mkuron...  you finally helped me finding the issue... all my fault. i mixed up my local postfix config. 
i purged the whole postfix config and reconfigured everything again. re-hashed the authentication data, and now it works and i am able to use my mailcow server as relay for any domain i use. 
thanks for taking the time to help me.
