### ISSUE TITLE
rspamd sometimes does not display history

### ISSUE THREAD

**Issue by DasWiesel2305** [mailcow/mailcow-dockerized#692]
Since the last update via the "./update.sh" script I have some weird issue with rspamd.
Sometimes rspamd can not display the history in the UI ($DOMAIN/rspamd).
It is prompting instantly with "timeout while connecting to server" or "gateway timeout", but everything is working as it should only the rspamd history is not working.

I've gathered the following suspicious entries from the docker logs of the rspamd container.

2017-10-27 22:03:21 #18(controller) <61c729>; lua; history_redis.lua:194: got error timeout while connecting the server when getting history: no value

The strange thing is that it is working sometimes after showing this message, if I spam "Update". 
Once it has loaded and I like to update once again it is quitting with the above mentioned errors.

If you need any further information, I will gladly provide to you.

**Comment by DasWiesel2305** [comment]
I've also found that rspamd is causing one CPU core to lock at 100%, if the above mentioned phenomenom is present.

https://www2.pic-upload.de/img/34193560/1_core_100_cpu.png

I can solve it by restarting the rspamd docker container.

**Comment by markirb** [comment]
I think this is a duplicate of
https://github.com/mailcow/mailcow-dockerized/issues/575

After playing around a bit, it seems that sometimes the JSON API request does not return anything. I suspect some kind of runtime or memory issue of PHP with the default of 2000 last log entries returned. The returned JSON is around 7MB for me, so this thing is quite big...
The underlying code needs to decode the JSON from rspamd and reencode only the rows as JSON.
So this is huge overhead... maybe this could be avoided.

Another way which worked for me was to reduce the number of rows:
When creating a 
data/conf/rspamd/local.d/history_redis.conf
with a reduced size, e.g. 
```
servers = redis:6379;
nrows = 400;
key_prefix = "rs_history";
compress = true;
```
(restart rspamd-mailcow afterwards)
it worked reliably again for me.

**Comment by axd** [comment]
@markusg Your solution doesn't work for me.

I've researched and I'm receiving this error:
`SyntaxError: JSON.parse: unterminated string at line 1 column 1060611 of the JSON data`

The JSON it's truncated and it's incomplete on the response.

**Comment by andryyy** [comment]
Do you have that exact line?

**Comment by markirb** [comment]
@axd 
Is this the output of the Firefox JSON parser? I've noticed the same thing sometimes.
But i believe this is a problem of Firefox, as when you look at the RAW data, it is not truncated....
Furthermore, even when this error message shows up, the logs show just fine....

But sometimes you do not get a response at all, so maybe these are also two different problems,
do you also observe empty responses?
Since my log is now truncated i have no issues so far... waiting for it to fill again

**Comment by markusg** [comment]
ok now that i have my full log again, the error is
`TypeError: item.rcpt_mime is undefined admin.js:616:13`

**Comment by DasWiesel2305** [comment]
Thank you for the provided solutions. I will try out reducing the number of rows as described by @markusg.

I'll also apply the commit in #701 and report back if it is working as expected again.

**Comment by DasWiesel2305** [comment]
Unfortunately, the problem is still persistent. 

The rspamd controller process is causing a 100% CPU lock on one CPU core and the history is not loading in the mailcow UI log section or the rspamd history section. I am running the latest version of the master tree including #701 and by reducing the rows as described by markusg.

The history section in the rspamd WebUI is showing "Gateway Timeout, but the errors section below of rspamd is loading fine.

**Comment by andryyy** [comment]
I need the Rspamd logs, please.

**Comment by DasWiesel2305** [comment]
Hey andryyy, 

i uploaded the log file of the rspamd docker container on Google Drive, but be prepared it's approx 8 MB large.
https://drive.google.com/file/d/0B2j2VWAD13xGYUpVVHRpMm1KUmc/view

I've also noticed that the CPU load of the controller rspamd process is increasing over time, maybe a loop, which is not working correctly (only a guess, I'm not that experienced in programming). It is increasing in load and when it hits 100% the history is not working anymore and the rspamd WebUI is very slow to respond.

**Comment by markirb** [comment]
#701 wont fix anything i guess, its just a minor which i stumbled on.

But i still cannot reproduce the issue again.

@DasWiesel2305 
Can you try to size down your log and see if that helps?
`docker-compose exec redis-mailcow redis-cli ltrim rs_historyrspamd_zst 0 1000`
where the last number is the length (+1) of your remaining history (everything else is deleted).
You can try to gradually reduce the number and see if that is the problem

**Comment by DasWiesel2305** [comment]
@markusg 

Thank you for your provided solution, but it does not change the current state.
If I would like to see the history I get a "Cannot receive data from mail.$DOMAIN.de: {"error": "timeout while connecting the server"}", sometimes I just get a Gateway Timeout and then a try later it displays the history, then it does not display the history...This is so weird.

I tried to reduce the length to 100 already, but this does also not help. The rspamd controller process stays at 100% CPU usage for one core.

I uploaded a new log file to the Google Drive, now it is 10 Megabytes large.

https://drive.google.com/open?id=0B2j2VWAD13xGbU1lbTg0MWd2dUE

**Comment by andryyy** [comment]
There is still that empty map issue in your logs. Can you update your cow? 👍

**Comment by DasWiesel2305** [comment]
I am an idiot....as I have localy modified files the script has not pulled all changes. I have now fixed this and I am running now the latest version.

I'll report back, if I experience this isssue again.

Thank you for giving me this hint! ;)

**Comment by DasWiesel2305** [comment]
This issue can be considered as solved as everything is working just fine and blazing fast right now.

Thank to all guys, which helped me in this case! :+1:

**Comment by markirb** [comment]
So here i am again... now that my logs are full... same error 😄 
Most of the times the JSON request returns empty, and thus the JS says 
`Cannot draw rspamd history table`

This time i switched on error reporting in the json_api, and see what we get...
`<b>Fatal error</b>:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 4198400 bytes) in <b>/web/json_api.php</b> on line <b>805</b><br />`

The numbers in the error make no sense. But still this is a problem of two much data in the logs, which is 14MB for me.....
I think the log should be truncated to contain less entries.

**Comment by andryyy** [comment]
Will be fixed in the next dev push. And then in master.

**Comment by markirb** [comment]
I don't see any change regarding this issue. Which specific commit do you mean? 😕

**Comment by markirb** [comment]
ah now... looks nice  👍

**Comment by danielmorlock** [comment]
We also have the issue where the rspamd history is truncated. Any suggestions here?

**Comment by danielmorlock** [comment]
Update: Getting the JSON from redis i.e. http://redis:11334/history returns the full, non-truncated JSON file.

**Comment by andryyy** [comment]
There is no redis:11334 - you probably meant rspamd?

**Comment by danielmorlock** [comment]
Sorry yes, I meant rspamd: http://rspamd:11334/history

**Comment by danielmorlock** [comment]
My issue seems not to come from mailcow-dockerized. Please excuse my yell.
