### ISSUE TITLE
Hardcoded timeout for imapsync?

### ISSUE THREAD

**Issue by Fvbor** [mailcow/mailcow-dockerized#694]
Hey guys,

have trouble with imapsync (6-8k Mails in the postbox) and try to fix it with increase the timeout.
Set it from the default setting (20 minutes) to 120 minutes, no difference.
Found in the log of a smaller (78 Mails) sync job, with the same settings, the call of imapsync.

`/usr/local/bin/imapsync --timeout1 10 --tmpdir /tmp --subscribeall --delete2duplicates --tls1 --host1 {HIDDEN} --user1 {HIDDEN} --passfile1 /tmp/imapsync.kQutdkx --port1 143 --host2 localhost --user2 {HIDDEN} --passfile2 /tmp/imapsync.SepMK3k --no-modulesversion`

timeout1 is set to 10 minutes - Hardcoded.
I guess this is the right file/line

https://github.com/mailcow/mailcow-dockerized/blob/c6d461382cba82cf1459843f4af21d87f3392398/data/Dockerfiles/dovecot/imapsync_cron.pl#L67

Nice regards

Additional Information: The big job is never finished. Tested it over a few days and today with a complete new sync job.
Last run is empty
Open Logs displays a log containing "null"

**Comment by mritzmann** [comment]
In the current version the timout is harcoded to 600min.

https://github.com/mailcow/mailcow-dockerized/blob/8adf3d27db128bdeb45290ca9114aff9797f2a91/data/Dockerfiles/dovecot/imapsync_cron.pl#L74

I think this issue can be closed?
