### ISSUE TITLE
New Mailboxes can't login, url is "undefined"

### ISSUE THREAD

**Issue by DeDu** [mailcow/mailcow-dockerized#696]
Hello

I installed mailcow, using the documentation. 

The first Mailbox that I created worked fine. But now I want to add other mailboxes. And I did.
But when I login to SOGo with the correct username and pass, it says "Welcome" but then redirect me to http://mydomain.com/SOGo/undefined (Where mydomain.com is my real domain). I then stay on the login page.

Where is this "undefined" in the url coming from?

Thank you
Matthias

**Comment by lazyfrosch** [comment]
Have you restarted SoGO after adding those domains?
![bildschirmfoto von 2017-10-30 07-56-35](https://user-images.githubusercontent.com/121874/32158212-e13d8810-bd47-11e7-8591-2ef366e3ba8a.png)

**Comment by DeDu** [comment]
I did not. Sorry to have bothered you ;-)

Restarting in the Web App did not work, but after restarting in the console I was able to login.

Thank you!
