### ISSUE TITLE
Login to sogo after installation

### ISSUE THREAD

**Issue by Eggilein** [mailcow/mailcow-dockerized#699]
Hello,
i am new to mailcow and docker
I installed everything mentioned in the documentation
Login GUI for mailcow is working
login GUI for sogo is working, but i cannot login because i don't know a uer or password.
Is there a default user or admin 
Do i have to create a user  to have access? How is that done?

regards Egbert

**Comment by jpbaril** [comment]
SOGo is a webui for emails, calendars and contacts. You need to login with an email account created in the Mailcow ui. To login in the Mailcow UI use the default admin user with password "moohoo".
