### ISSUE TITLE
autodiscover broken

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#704]
Hi, autodiscover in Mailcow is broken, the error is coming back as Invalid password but I know the password corrent since it works via IMAP and exchange if I manually set the server address.

I've tried to use autodiscover in two client that I know works fine since i used them before with Mailcow Gmail Android app and the built in mail client in Windows 10.

I got this from Nginx logs no other logs files logged anything helpful.

<pre>
nginx-mailcow_1      | 2017/10/31 00:09:13 [error] 11#11: *358 FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for ryan@***.eu by 82.32.1**.35" while reading response header from upstream, client: 82.32.1**.35, server: mail-de.*****.be, request: "POST /autodiscover/autodiscover.xml HTTP/1.0", upstream: "fastcgi://172.22.1.7:9000", host: "autodiscover.*****.eu"
nginx-mailcow_1      | 82.32.1**.35 - ryan@******.eu [31/Oct/2017:00:09:13 +0000] "POST /autodiscover/autodiscover.xml HTTP/1.0" 401 0 "-" "Android-Mail/7.9.24.172525262.release"

nginx-mailcow_1      | 2017/10/31 00:27:27 [error] 11#11: *67 FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for ryan@****.eu by 82.32.1**.35" while reading response header from upstream, client: 82.32.1**.35, server: mail-de.****.be, request: "POST /AutoDiscover/AutoDiscover.xml HTTP/1.0", upstream: "fastcgi://172.22.1.7:9000", host: "autodiscover.*****.eu"
nginx-mailcow_1      | 82.32.1**.35 - ryan@*****.eu [31/Oct/2017:00:27:27 +0000] "POST /AutoDiscover/AutoDiscover.xml HTTP/1.0" 401 0 "-" "microsoft.windowscommunicationsapps"

</pre>

**Comment by stevesbrain** [comment]
I have not seen that before - however, did you follow [this guide](https://mailcow.github.io/mailcow-dockerized-docs/u_e-autodiscover_config/)? Have you set your DNS entries appropriately? Is this a standard setup, or do you have other reverse proxies etc. in the mix? Is this only a recent change, or has this been broken for you ever since you tried?

**Comment by K2rool** [comment]
DNS is setup correctly, this was a new installation with no custom modification.

I know it worked in the past since I got a older installation on a other server that I not got around to update yet which autodiscover works fine.

**Comment by stevesbrain** [comment]
@K2rool I'll give mine an update tomorrow and see if that breaks it then :) I last updated about 2 days ago.

**Comment by K2rool** [comment]
I've done more testing it's only broken when the password contains a symbol in my case the password had a @ in it.

For some reason that breaks the autodiscover script passwords with @ in it works fine with IMAP SMTP webgui and exchange/sogo.

**Comment by andryyy** [comment]
Hm, strange. I wonder if it is encoded.

Can you try to change the lines...
```
$login_user = strtolower(trim($_SERVER['PHP_AUTH_USER']));
$login_role = check_login($login_user, $_SERVER['PHP_AUTH_PW']);
```

...to...

```
$login_user = strtolower(trim($_SERVER['PHP_AUTH_USER']));
$login_pass = trim(htmlspecialchars_decode($_SERVER['PHP_AUTH_PW']));
$login_role = check_login($login_user, $login_pass);
```
?

**Comment by K2rool** [comment]
Thanks, @andryyy that fixed it not sure why it gets encoded but adding htmlspecialchars_decode seem to fix it.
