### ISSUE TITLE
authentication-server

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#706]
Hi, 
does anyone have any experience of using mailcow as an authentication server?

**Comment by mkuron** [comment]
If your application supports authentication against IMAP, then you can already use it (e.g. for Owncloud/Nextcloud).

Otherwise, if you want OAuth, this is a duplicate of #684.

**Comment by ChessSpider** [comment]
cool thx  :) ill close this issue ~~  the hint about IMAP auth is what i needed
