### ISSUE TITLE
SoGo sends mail every minute

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#712]
Since the last update SoGo is constantly sending mails every minute and keeps on pushing the load on the server.

Does anyone know how to stop this ?

![screenshot_20171102_135156](https://user-images.githubusercontent.com/11457234/32327104-9e198292-bfd5-11e7-8250-f657eee8bd1f.png)

**Comment by andryyy** [comment]
Hi,

Can you please show the output of these commands? => 

```
docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo /usr/sbin/sogo-ealarms-notify
docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo /usr/sbin/sogo-tool expire-sessions 60
```

**Comment by ghost** [comment]
I ran both and there is no output at all

**Comment by andryyy** [comment]
And `docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo ls -la /var/mail`? Any file? If yes, what's in it? `docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo cat /var/mail/sogo`

**Comment by ghost** [comment]
**First command:** 
 docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo ls -la /var/mail
total 0
drwxrwsr-x  2 root mail   6 Sep  7 02:00 .
drwxr-xr-x 11 root root 139 Sep  7 02:00 ..

**Second:**
docker exec -it $(docker ps -qf name=sogo-mailcow) gosu sogo cat /var/mail/sogo
cat: /var/mail/sogo: No such file or directory

**Comment by andryyy** [comment]
Could you please send me your sogo-mailcow logs to info@servercow.de? Logs from about 13 pm until now would be fine.

SOGo has not been updated in a while, that's strange. Both commands returned no data, too...

Does it persist when you run docker-compose down followed by up -d?

**Comment by andryyy** [comment]
It was a remaining local installation from before upgrading.
