### ISSUE TITLE
dockerapi-mailcow - Exit 0

### ISSUE THREAD

**Issue by bawe** [mailcow/mailcow-dockerized#713]
After restart of system or
systemctl stop docker.service
systemctl start docker.service

docker-compose ps shows:
mailcowdockerized_dockerapi-mailcow_1   python2 -u /server.py            Exit 0

docker-compose logs dockerapi-mailcow:
dockerapi-mailcow_1  |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
dockerapi-mailcow_1  | Stopping dockerapi-mailcow

**Comment by andryyy** [comment]
Thanks, that's fixed in the next push.
