### ISSUE TITLE
Fetchmail / Getmail Support?

### ISSUE THREAD

**Issue by Aylshamjake** [mailcow/mailcow-dockerized#714]
Hi there, 

I am trying to setup Mailcow alongside something like Fetch-mail / Get-mail so I can pull emails from a different provider such as 1and1. 

It says on this forum Fetch-mail works on Dockerized Mailcow but I cannot find documentation for it anywhere!
https://github.com/mailcow/mailcow/issues/789

Any help will be greatly appreciated!

**Comment by pandit77** [comment]
Hi,

 i think this should be possible by using the "sync jobs" feature under mailbox administration.

**Comment by Aylshamjake** [comment]
You would be right, thank you!

**Comment by xpcone** [comment]
Theses imapsync is doing shit.... 
For fetching mail , sending them via rspamd to dovecot and doing sieve rules on it, this imapsync shit is useless.

**Comment by tkorves** [comment]
@xpcone Think about your rude language - this is unacceptable.
