### ISSUE TITLE
can't send mail through mailcow, receiving works

### ISSUE THREAD

**Issue by plonxyz** [mailcow/mailcow-dockerized#716]
Hi 
I've just installed a new Mailcow-image on my vultr docker-vps. 

just the classic issue, i can reveive mails but I can't send any ..

any help is kindly appreciated

**Comment by Braintelligence** [comment]
At least post what the logs are saying.

**Comment by plonxyz** [comment]
sure, could you please tell me which logs you need?

**Comment by Braintelligence** [comment]
You did read the very well-written documentation before posting here, right?

https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/

**Comment by K2rool** [comment]
The vultr issue will due to they block outgoing on port 25 by default.

If you open a ticket they will remove the block.
