### ISSUE TITLE
Alpine Linux - Reduce disk space requirements

### ISSUE THREAD

**Issue by appdoodle** [mailcow/mailcow-dockerized#717]
I would suggest to move some of the remaining images such as mariadb to alpine base to reduce disk space requirements for mailcow leaving only SoGO on debian because of its GNUStep dependency.

**Comment by snc** [comment]
Don't know if all the images are based on the same Debian image, but if that's the case then the space is only claimed once.

**Comment by andryyy** [comment]
Debian and Alpine atm. Alpine Postfix packages also behave incorrect when validating DANE. Dovecot could be moved to Alpine, I guess, but there is no need as long as we are using "some" Debian based images.

10 Alpine + 1 Debian images == 1 Alpine + 10 Debian images.
