### ISSUE TITLE
dhparams.pem not regenerated

### ISSUE THREAD

**Issue by Siassei** [mailcow/mailcow-dockerized#718]
I have setup the awesome mailcow server on an blank vserver (ArchLinux) and configure bevor all require DNS settings. The docker container starts successfull and the Let's encrypt files are created successfull (with checks). But the dhparams.pem was not created by the container and insteady the sample file (${SSL_EXAMPLE}/dhparams.pem) was copyed to ssl director.

From me it is a security issue. If the file is cracked, a lot of server can be attacked. The script "mailcow-dockerized/data/Dockerfiles/acme/docker-entrypoint.sh" at Line 65 do that job. Please replace

`
[[ ! -f ${ACME_BASE}/dhparams.pem ]] && cp ${SSL_EXAMPLE}/dhparams.pem ${ACME_BASE}/dhparams.pem
`

with

`
[[ ! -f ${ACME_BASE}/dhparams.pem ]] && openssl dhparam -outform PEM -out  ${ACME_BASE}/dhparams.pem 2048 # or 4096
`

**Comment by mkuron** [comment]
Reusing and sharing dhparams is not generally considered a security issue. See e.g. https://security.stackexchange.com/questions/94390/whats-the-purpose-of-dh-parameters, https://news.ycombinator.com/item?id=9355649, https://security.stackexchange.com/questions/43355/what-are-the-implications-of-using-the-same-dh-parameters-in-a-tls-server. I believe Mailcow ships a 4096-bit dhparams.pem. Generating that takes quite a long time (~10 minutes), so we wouldn't want to regenerate that if we don't have to.

As far as I k now, the only way a dhparams can be unsafe is if it is too short (2048 bits is still considered sufficient and 4096 optimal) or was specially crafted to be easily attacked.

**Comment by andryyy** [comment]
The dhparams file is being regenerated after the first start of dovecot-mailcow. It says "generating ssl-params" which takes a while, as @mkuron said.

Also thanks for clarifying this, @mkuron - there's some great information in those links.

**Comment by jhesketh** [comment]
I'm not sure if a fresh deployment re-generates dhparams.pem, but on a deployment I have ./data/assets/ssl/dhparams.pem is unchanged from ./data/assets/ssl-example/dhparams.pem.

Should this be regenerated on update?

**Comment by Siassei** [comment]
@jhesketh  yeah, I had the same state. I was not sure if I you run the mailcow-container's long enough at first start and perhaps the regeneration of the dhparams was maybe canceled. I had also not readed the source code.
Yes, it would be better to generate a own file and restart after the docker container.

To have an unchanged dhparams.pem is a possible attack vector (in the theory) and if anyone find an attack strategy than alls server with the same dhparams.pem can be attacked.
Regenerate a new dhparams.pem should (my view MUST) be generated at an deployment. Generation of an 2048 file takes a few seconds and is the state of security that needed. So, it is no reason to not do that.

**Comment by jhesketh** [comment]
I agree. So is it a bug that some dhparams have not been regenerated, or is that left over from an older deployment? If it's the latter then update.sh or the docs should cover fixing the file.

**Comment by mkuron** [comment]
Why do you want to regenerate the file if it takes long (10 minutes or more depending on the CPU) and is not necessary? If you think it’s a security issue, please provide a link to literature that confirms that. I haven’t been able to find any.

**Comment by Siassei** [comment]
A own dhparams.pem is a little bit increase of security. Yes, it is true, acttually **there is no attack vector** for servers with same dhparams.pem **knowing**. **But the future will bring** ... perhaps ...  it could be possible to attack servers with the same dhparams.pem. So, why we should risk that? ... saftey first ???

e.g. read that https://security.stackexchange.com/questions/38206/can-someone-explain-what-exactly-is-accomplished-by-generation-of-dh-parameters

> But Diffie-Hellman requires some set-up parameters to begin with. These aren't secret and can be reused; plus they take several seconds to generate. **But they should be "clean", generated by you** so you know they're not provided by an attacker. The dhparam step generates the DH params (mostly just a single large prime number) ahead of time, which you then store for the server to use.

German, chapter 2.5 https://www.sherbers.de/howto/nginx/

@mkuron generating an 2048 bit dhparams takes on actually hardware roughly one minute. wtf. One minute .... and after that, the file on the server can be used for years.

**Comment by jhesketh** [comment]
So I know this has been closed for a while, but I came across some interesting documentation today: https://weakdh.org/ . As already mentioned in this thread 2048 is still "sufficient" but it does perhaps tip the argument towards doing it for future safety.
