### ISSUE TITLE
Domains not being shown correctly when alias domains added

### ISSUE THREAD

**Issue by myReaper** [mailcow/mailcow-dockerized#720]
Hi,

I have 4 domains added to Mailcow, in my case all Domains are the same but with different tld's (domain.de, domain.com, domain.net and domain.io).

Initially all domains were shown correctly in the Domains tab. Once I added the Domain Aliases, the domains tab now only shows the target domain (4 times) in the Domains tab.

![mailcow1](https://user-images.githubusercontent.com/5735944/32419731-4dd5cabe-c27f-11e7-93ab-1301cb82d7b4.png)
![mailcow2](https://user-images.githubusercontent.com/5735944/32419732-4df12016-c27f-11e7-9dfb-ad110885adba.png)

Best Regards
Michael

**Comment by andryyy** [comment]
Hm, I cannot reproduce it.
A SQL dump would be good. 

Do you come from a "normal" mailcow and migrated?

**Comment by andryyy** [comment]
It happened due to alias domains that were added while existing as "real" domains. The check was incorrect, I fixed this.
