### ISSUE TITLE
Alias chaining doesn't work

### ISSUE THREAD

**Issue by lenovouser** [mailcow/mailcow-dockerized#724]
Let's say I own `example.org` and `example.com`.

I create the mailbox `hello@example.com` and alias `hi@example.com` onto it.

Until now everything is working.

When I add a whole domain alias from `example.org` to `example.com` I can send an email to `hello@example.org` but not to `hi@example.org`, which fails with `Recipient address rejected: User unknown in virtual mailbox table`

This is weird and not what expected from domain aliasing. Is there a reason for this or can this be implemented / fixed?

**Comment by mkuron** [comment]
That is expected (and documented) behavior. Domain aliases only apply to mailboxes, not to aliases.

**Comment by andryyy** [comment]
I close this issue, but feel free to add ideas, feedback etc. 👍

**Comment by lenovouser** [comment]
Alright, I didn't find anything about it in the documentation so I wasn't sure. Is it in theory technically possible? If so, you could make it an option maybe.

**Comment by Braintelligence** [comment]
@mkuron Can you point us to where this is located in the documentation? I think the best way to implement this would be to allow "alias mirroring" to other domains on creation/edit of aliases, right?

**Comment by housejumper** [comment]
I'd like to see this too

**Comment by andryyy** [comment]
I added a tag. I'm not sure if we will ever add it. We could do this with a sql view or something like that.
