### ISSUE TITLE
Relayhost configuration

### ISSUE THREAD

**Issue by dave-washington** [mailcow/mailcow-dockerized#725]
Hi, I’ve configured a relayhost (relay.plus.net) through the mailcow UI but can’t see this in /etc/mailcow-dockerized/data/conf/postfix/main.cf. The reason for asking is that my relayhost does not require authentication so I have left the username and password blank, but is failing with the error ‘warning: SASL authentication failure: All-whitespace username’. I suspect somewhere in the configuration it is trying to use authentication when communicating with the relayhost but I can’t see where this is configured.
BTW. Adding a relayhost by editing /etc/mailcow-dockerized/data/conf/postfix/main.cf works for me.

Can we add a relayhost through the mailcow UI with a tickbox for authentication/no authentication?

**Comment by Waester** [comment]
Having same problem, anyway to disable authentication?

EDIT: One solution that worked for me was to type a random username and password, the SMTP relay still accepted that. Though not sure if this will work for all SMTP relays that don't require authentication.

**Comment by andryyy** [comment]
Fixed now. 👍 Will push soon.

**Comment by Waester** [comment]
I noticed a somewhat related bug.
It is not possible to delete username and password on existing relayhosts, it reverts to previous settings when saving if username and password is not entered.

**Comment by andryyy** [comment]
This is fixed, too.
