### ISSUE TITLE
Very pretty cow covering Admin GUI

### ISSUE THREAD

**Issue by dfroberg** [mailcow/mailcow-dockerized#728]
It's cute but not very user-friendly :)
Perhaps a smaller version like in the previous version.

![screenshot_11](https://user-images.githubusercontent.com/285403/32551909-65f8ccc6-c492-11e7-8882-43bd0613a654.png)

Versions running:
![screenshot_12](https://user-images.githubusercontent.com/285403/32552040-e796d3e0-c492-11e7-86ef-8a57ae4ea8db.png)

**Comment by lucianlazar1983** [comment]
You can fix this by uploading your logo in settings-->customization

**Comment by cklabautermann** [comment]
After updating I had it the same way. After flushing the browser cache it "minimized" to the upper left corner :-)

**Comment by mkuron** [comment]
That happens if you don‘t restart your browser (or clear the cache) after updating to the latest version. There was a CSS change recently.

**Comment by Braintelligence** [comment]
@mkuron Sounds like this can be closed? 😸
