### ISSUE TITLE
How to reload configuration files without "reset" the container?

### ISSUE THREAD

**Issue by tesoner** [mailcow/mailcow-dockerized#729]
How can i reload with changed config files without lost the data? When i use `docker-compose up -d` the data of my container is lost. 

_i know, this isn't a issue, but not exists a forum_

**Comment by mkuron** [comment]
There shouldn’t be any data in the containers. Anything that needs to be persistent is stored in volumes.

Or are you talking about modifications you manually made to the container via `docker exec`?

**Comment by tesoner** [comment]
I was talking about change SSL certificates, or mailcow.conf. I think the solution is use `docker-compose down && docker-compose up --no-recreate -d` or restart services independently, example:  `docker-compose restart postfix-mailcow dovecot-mailcow nginx-mailcow`

**Comment by mkuron** [comment]
You can use docker-compose to restart services, but the only advantage over down/up is that it’s a bit quicker. You don‘t lose any data by recreating the containers. Instead, you clean caches and temporary files, which may be necessary for some changes to be fully applied.
