### ISSUE TITLE
Can't login in SOGo

### ISSUE THREAD

**Issue by PhoenixPeca** [mailcow/mailcow-dockerized#73]
Hi Andre,

As of this moment in the `dev` branch: mailbox users can't login to their account. It's a consistent `Wrong username or password.`

![capture](https://cloud.githubusercontent.com/assets/9730242/23338254/723e4daa-fc40-11e6-9ee7-a3c3dc2b28f0.JPG)

**Comment by andryyy** [comment]
Hi, that's a dev branch for a reason. :-)
You need to build the SOGo image: `docker build data/Dockerfiles/sogo/ -t andryyy/mailcow-dockerized:sogo`. Should be enough to get it working.

**Comment by PhoenixPeca** [comment]
Ohhhh!!!! Sorry, I missed that. hahahah
