### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by luxflux** [mailcow/mailcow-dockerized#734]
I recently installed mailcow and it works like a charm! Thanks a lot for your work!

I tried to keep up with the changes done so that I could upgrade my system if necessary and also to see what changes when I'll upgrade. Unfortunately there is so much going on, that it's hard to keep track (at least for me).
Could we introduce something like a `CHANGELOG.md`? There are automated solutions like [conventional-changelog](https://github.com/conventional-changelog/standard-version) which requires you to use specific git commit messages. In a project I maintained, I simply added a merged PR to `CHANGELOG.md`, at first in a `next` section. When releasing, I just replaced `next` with a version.

What do you think about this? Or how do others keep track of the changes?

**Comment by snc** [comment]
Would be nice, I currently use the compare feature https://github.com/mailcow/mailcow-dockerized/compare/42567a352c95e0c5ff0ee3a260ed955421215218...master to have a look at the changes.

**Comment by mkuron** [comment]
We don‘t have version numbers and not all changes go through pull requests. So an auto-generated changelog wouldn‘t look much different than the output of `git log`.

Making contributors use specific commit message formats usually requires lots of discipline. And requiring everyone to include an edit to CHANGELOG.md is asking for merge conflicts...

I see the point of having a changelog, but I fear that maintaining one will not be worth the effort.

**Comment by luxflux** [comment]
I agree regarding the discipline, this is why I didn't use it for my project...
The updates to `CHANGELOG.md` were only done by me, after merging a PR.

**Comment by mritzmann** [comment]
I update Mailcow by hand according to the instructions: https://mailcow.github.io/mailcow-dockerized-docs/install-update/

It would be practical if there were a changelog with all important changes. Changes made via update.sh (e. g. add `echo "WATCHDOG_NOTIFY_EMAIL=" >> mailcow. conf`) could also be mentioned in the changelog, so that i can do the same after manual updates.

**Comment by andryyy** [comment]
Watchdog is not yet fully implemented.
