### ISSUE TITLE
Cannot connect using ActiveSync over SSL

### ISSUE THREAD

**Issue by klausweiss** [mailcow/mailcow-dockerized#736]
I've successfully installed `mailcow-dockerized` using this steps: https://mailcow.github.io/mailcow-dockerized-docs/install/
I don't use reverse proxy nor OpenStack (I've ommited step 4 of the installation).

I've used `mail.example.org` as FQDN, then added `example.org` in mailcow admin panel. I've created a mailbox: `klausweiss@example.org`.

I've been able to connect to mail account using IMAP and SMTP (with SSL), to CardDAV (with SSL) and to CalDAV (also with SSL). I am unable to connect to the server using Microsoft ActiveSync with SSL on both my Blackberry Q20 and Nokia E72. I've tried using both the `example.org` and `mail.example.org` as server addresses - both devices connect successfully when I specify the port as `80`, but fail to connect when the port is set to `443`.

I am using fresh install of _Ubuntu 16.04_ - mailcow is the only service is hosted on the machine.

**Comment by andryyy** [comment]
Do they support ActiveSync?
Can you create me a mail account and send the credentials to info@servercow.de?

**Comment by klausweiss** [comment]
Yes, they do. Sure, check your inbox.

**Comment by andryyy** [comment]
Thanks!

You use HSTS and your autodiscover.domain.tld certificate is not valid. I am not allowed to connect then.

**Comment by klausweiss** [comment]
Could you elaborate? I am not sure what you mean.

**Comment by klausweiss** [comment]
@andryyy, could you explain a little bit more extensively what do you mean, please?

**Comment by klausweiss** [comment]
Ok, here's what I've changed:

I'v set± `CNAME` entry `autodiscover.example.org.` to `example.org` (it was pointing to a wrong address before). I've corrected one for `autoconfig.example.org` too.

I've also added an entry in `mailcow.conf` to ADDITIONAL_SAN (`autoconfig.example.org`) so that the SSL certificate is generated for this domain as well.

Finally, I've put
```php
<?php
$autodiscover_config = array(
  // Enable the autodiscover service for Outlook desktop clients
  'useEASforOutlook' => 'yes',
  // General autodiscover service type: "activesync" or "imap"
  'autodiscoverType' => 'activesync',
  // Please don't use STARTTLS-enabled service ports here.
  // The autodiscover service will always point to SMTPS and IMAPS (TLS-wrapped services).
  'imap' => array(
    'server' => $mailcow_hostname,
    'port' => getenv('IMAPS_PORT'),
  ),
  'smtp' => array(
    'server' => $mailcow_hostname,
    'port' => getenv('SMTPS_PORT'),
  ),
  'activesync' => array(
    'url' => 'https://'.$mailcow_hostname.'/Microsoft-Server-ActiveSync'
  ),
  'caldav' => array(
    'url' => 'https://'.$mailcow_hostname
  ),
  'carddav' => array(
    'url' => 'https://'.$mailcow_hostname
  )
);
```
in `data/web/inc/vars.local.inc.php` file (according to https://mailcow.github.io/mailcow-dockerized-docs/u_e-autodiscover_config/) and restarted the containers using `docker-compose restart` inside the main directory of _mailcow_dockerized_.

If I open either `example.org/autodiscover/autodiscover.xml` or `autodiscover.example.org/autodiscover/autodiscover.xml` in the browser I get the following as a result after authenticating:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response>
    <Error Time="23:08:060.452514" Id="2477272013">
      <ErrorCode>600</ErrorCode>
      <Message>Invalid Request</Message>
      <DebugData />
    </Error>
  </Response>
</Autodiscover>
```

Still neither my Blackberry nor the Nokia can connect using `https`.

**Comment by klausweiss** [comment]
@andryyy you've guys already done amazing work. I'd be thankful if you found a few minutes more to help me figure this out (:

**Comment by andryyy** [comment]
TLS for autoconfig.domain.tld is auto-configured as is autodiscover. :-)

I checked using the creds you sent me a while ago. Autodiscover just worked fine.

The 600 error is correct. That's what is supposed to be seen when you don't send a POST request. 👍

**Comment by TiiFuchs** [comment]
You can always use https://testconnectivity.microsoft.com/ to test AutoDiscover as well as the ActiveSync part on it's own.

**Comment by tiirex9** [comment]
I'm running mailcow under 8080/8443 but have a reverse proxy on 443 for different domains.
I figured so far, that the AutoDiscover Feature outputs the mailcow_hostname (which is okay) but it uses the port of the HTTP_HOST in vars.inc.php. So I changed that using the variable $https_port and since then the AutoDiscover XML outputs the correct host/port.

I tried to test ActiveSync then, but realized on https://testconnectivity.microsoft.com/ that it's using port 443 anyway. And since the mailcow_host:443 is not routed to mailcow the ssl certificate is (of course) invalid. And even if it was, there would be no answer by mailcow.

Does ActiveSync support ports other than 443? Since obviously it is ignoring the other port.

**Comment by maverick85** [comment]
Did this evolve in any sense? I am looking to configure Outlook 2019 for Mac - Version 16.21 (190108).
Thanks

**Comment by andryyy** [comment]
I think they don't support ActiveSync nor do they support the "old" autodiscover. We may fix the autodiscover stuff in the future.

There are other much better, faster, lighter clients available for mail and calendars. :)

**Comment by maverick85** [comment]
If you take a look at [Compare Outlook for Mac with Outlook for Windows](https://support.office.com/en-us/article/compare-outlook-for-mac-with-outlook-for-windows-bd54cb79-d367-4c2f-89c7-3e5d16618f87) under exchange/miscellaneous they advert full exchange support.

> Synchronize Calendar, Mail, Tasks, Notes, Categories, and Contacts with the Exchange server: YES

Can you tell me which lighter clients are there available for Exchange protocol? Cheers.

**Comment by maverick85** [comment]
If you take a look at [Compare Outlook for Mac with Outlook for Windows](https://support.office.com/en-us/article/compare-outlook-for-mac-with-outlook-for-windows-bd54cb79-d367-4c2f-89c7-3e5d16618f87) under exchange/miscellaneous they advert full exchange support.

> Synchronize Calendar, Mail, Tasks, Notes, Categories, and Contacts with the Exchange server: YES

BTW, ActiveSync is for mobile only, neither Outlook for Mac or for Windows desktop apps have ActiveSync.
But anyway, can you please tell me then which lighter clients are there available for Exchange protocol? Cheers.

**Comment by andryyy** [comment]
That’s not true. EAS is available in Outlook for Windows up to 2016. Some O365 Office packages dropped EAS though. 

Exchange service is not EAS. You talk about EWS. 

EAS was also intended as mobile protocol but not limited to this specification. As I mentioned previously, it is available in almost all Outlook clients for Windows. :)

I recommend emClient!

**Comment by abctaylor** [comment]
Has anyone got EAS going with Office 356 ProPlus on Windows? If so can you direct me to the #issue with the resolution or if not, is there a fix ETA  @andryyy ?

Thanks guys, awesome product

**Comment by andryyy** [comment]
How can I fix it, if it was dropped?

**Comment by lucianlazar1983** [comment]
Hi all just to inform you that latest updates on Outlook mobile App for both iOS and Android broke activesync on Mailcow. Existing accounts are not working anymore and keep requesting the password. Anyone have this problem?

**Comment by K2rool** [comment]
The reason for it breaking is probably due to removal of  EAS support and now just supporting EWS which SOGo doesn't support, I've noticed in last year or so more and more Android mail client that support exchange removed EAS.I just use IMAP anyway so it's doesn't effect me.
