### ISSUE TITLE
Possibly unhandled rejection: 

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#74]
after loggin in SOGo i don't see the folder list, but using chrome developer tools i see this error:
/SOGo.woa/WebServerResources/js/vendor/angular.min.js:122 
`Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/SOGo/so/marco@[MUNGED].it/Mail/0/folderINBOX/expunge","headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"7a20992da2bf095c643c39cf5d8c477d077999da"}},"statusText":""}`

and the mailbox list is not displayed correctly : http://imgur.com/tuKwQeV

**Comment by andryyy** [comment]
Try to clean your cache and restart memcached. But this is really not a mailcow issue. :-/

**Comment by afzalarsalan** [comment]
Conveniently I've also just experienced this issue and have cleared my browser cache as well as restart memcached but unfortunately it doesn't fix this issue. It might be worth looking further into this problem

**Comment by afzalarsalan** [comment]
It seems that bringing the cluster down and then up was the necessary solution rather than simply restarting. Don't know why but it works

**Comment by andryyy** [comment]
Hm, that is strange.

**Comment by marrco** [comment]
i probably made a mistake. I'm still trying to learn docker, in fact when i restored my old config everything worked fine again. It makes sense that this just was a caching issue, not client side (i tried incognito mode and emptied cache). But i'm not 100% sure, still a newbie to dockerized apps

**Comment by fibis** [comment]
@afzalarsalan how did you bringing the cluster up and down? With start and stop? I have the same issue and want to try your solution.

**Comment by afzalarsalan** [comment]
Yup exactly, just straight docker-compose down && docker-compose up -d. Although I must mention I've been experiencing other weird anomalies with this version of Sogo such as email duplication when reopening folders but not on refresh. Very weird

**Comment by fibis** [comment]
That means that also all data will be deleted? That is not the right way for me 😄

**Comment by andryyy** [comment]
No, this happens with -v

**Comment by afzalarsalan** [comment]
Yeah data is stored in permanent volumes on your filesystem. As long as you don't delete the directory, you shouldn't lose anything

**Comment by fibis** [comment]
Thanks worked for me and the problem was solved
