### ISSUE TITLE
2FA in SOGo

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#740]
Hello everyone,

is it possible to provide 2FA (especially FIDO U2F) in SOGo and registering of 2FA for that purpose in the mailcow UI for each address by easy means?

It would be awesome if you could create a mailcow-configuration where accessing your stuff is only possible with usage of 2FA. This would create secure groupware environments for data-sensitive applications.

**Comment by mkuron** [comment]
You‘d need to do that on the Nginx level. I don‘t think SOGo provides hooks for that. Also, you‘d need to disable IMAP access as that protocol doesn‘t support any kind of 2FA but gives full access to your mailbox.

**Comment by Braintelligence** [comment]
Yeah I wanted to disable remote IMAP access when using such a configuration.

I don't see the connection to NGINX, though, yet. Is U2F handled by NGINX?

**Comment by mkuron** [comment]
Nginx is a proxy in front of SOGo. You could handle the 2FA on the proxy. You probably can‘t do it in SOGo because it doesn‘t support it. Of course, you could file a feature request with SOGo. You‘d lose many other features though (calendar and contacts syncing with smartphones for example), so this is something you’d likely only want to do in a high-security environment.

**Comment by Braintelligence** [comment]
Yes, I would need this for a high-security environment. 

But as a sidenote: There are NFC-capable FIDO U2F-keys, so theoretically you also could be able to use it via NFC-capable-Smartphone as long as you access SOGo via U2F-capable browser or specifically prepared app.

**Comment by Braintelligence** [comment]
It's funny how SOGo says requesting features is a form of contribution but doesn't specify a way of how to request features... https://github.com/inverse-inc/sogo

Should I hit up the mailing list for this or is there a better spot for requests?

**Comment by mkuron** [comment]
THere already are feature requests for that: https://sogo.nu/bugs/view.php?id=2722, https://lists.inverse.ca/sogo/arc/users/2016-10/msg00095.html . The only thing you can do to speed things up is to implement it yourself and submit the patch to the developers.

**Comment by Braintelligence** [comment]
I'm content knowing that the request was already made, thank you so much for looking it up. 👍 

I think incorporating FIDO U2F into webmail clients and mail apps (especially also via NFC) is the next big thing in mail-security.

I have a dream that someday I will stick my Yubikey into my PC for fetching my mails in Thunderbird 😸.

**Comment by mkuron** [comment]
I don’t think that will happen any time soon. There are so many email clients out there and IMAP, SMTP, CardDAV/CalDAV don‘t currently define any way of providing a second factor. An alternative that already works is app-specific passwords: your email client authenticates to the server not with the user‘s password, but with a very long token that was generated when the client was first configured. The user doesn‘t have this token memorized and ideally his client device is full-disk encrypted, so an attacker will have a hard time of getting the token. Alternatively, TLS client certificates could be used (these can even be stored on a Yubikey and are supported by Thunderbird and others).

**Comment by Braintelligence** [comment]
The specification for WebSockets was theoretically available since the HTML5-specification on such TCP-connections after its naming in 2008. It took almost till 2012 till RFC 6455 hit most of the relevant browsers and allowed widespread usage of it and then some years for popular frameworks to adapt it.

So if 2FA finds its way to E-Mail in the next 10 years I'm alright with it ;).

**Comment by Braintelligence** [comment]
@andryyy Did you get my mail on info@servercow ?

**Comment by andryyy** [comment]
Can you mail me again, @Braintelligence?

**Comment by Braintelligence** [comment]
@andryyy Just did. Maybe you're blocking my domain for some reason? :P

**Comment by phatina** [comment]
Any news about this feature?

**Comment by Adorfer** [comment]
Having 2FA would be really nice.

**Comment by andryyy** [comment]
How would you implement this with IMAP?

This is also not mailcow related but SOGo. :-)

**Comment by Braintelligence** [comment]
> How would you implement this with IMAP?

I thought SOGo was also using SQL with mailcow? Is it not viable to store 2FA in there and link it to SOGo? I mean is SOGo even capable of using 2FA natively, and if yes, where does it get the seed/whatever from?

**Comment by andryyy** [comment]
What do you want to secure with TFA here? Calenders, contacts, mails cannot be protected by TFA for obvious reasons. So ... you could protect the settings, I guess. Even filters are available via sieve.

It's something different when you decide to ONLY use SOGo and hide all services from public access. Then again, you need to ask SOGo to implement it.

**Comment by mkuron** [comment]
If you disable IMAP, POP and SMTP access and only leave SOGo webmail open, you could do it relatively easy. SOGo can delegate authentication to external services, like a SAML IdP or OAuth (which Mailcow could conceivably provide), so you don‘t need the feature integrated into SOGo. You would also lose CalDAV, CardDAV and EAS access.

Since nobody wants to give up mobile devices and native email clients to use exclusively webmail, I see no value in 2FA for mail — and as far as I can see, no email provider is doing it. Using 2FA for webmail and application-specific passwords (which I mentioned above) would be a more reasonable solution.

There is a specification for OAuth for IMAp with OAuth (I think Google uses that), but I‘m not sure if Dovecot supports it and which email clients can use it.

**Comment by Braintelligence** [comment]
D'accord. Thus my comment https://github.com/mailcow/mailcow-dockerized/issues/740#issuecomment-343769265 . Yeah, my earlier comment was about the idea of using SOGo exclusively as only client for everything (if you absolutely demand 2FA for your mail stuff). Next step could have been some kind of abstraction to SOGo instead of IMAP/SMTP in form of a native SOGo app that would support 2FA on mobile as well. (Does SOGo Connector support 2FA?) But that's not anywhere close to the scope of mailcow, it's SOGo stuff that SOGo could look at 😎.

**Comment by Adorfer** [comment]
this request ist about 2FA in Sogo, not about 2FA in imap/webcal etc. 
(this is why i do not ask about 2FA for mailcow webconsole in this issue either.)

**Comment by andryyy** [comment]
Create a feature request in SOGo then? ;-)

**Comment by Braintelligence** [comment]
@andryyy Is it actually possible to link a mailcow user account with SAML-authentication for SSO-purposes?

**Comment by andryyy** [comment]
Yes, with simplesaml for example. Needs to be implemented in SOGo and Dovecot then. The Dovecot part would be tricky.

If you like to live dangerously, you can store the credentials in the session. :O

**Comment by Braintelligence** [comment]
Those meme-nostalgia-feels!
![grafik](https://user-images.githubusercontent.com/6761196/49080880-5fe04a80-f245-11e8-9851-fba71d230108.png)

Well, I'm just eyeballing using mailcow-dockerized with a lot of other stuff together with the open-source SSO-solution https://gluu.org/

It looks and sounds fantastic and also provides a free smartphone 2FA-tool. It supports
- OAuth 2.0
- OpenID Connect
- User Managed Access 2.0 (UMA)
- SAML 2.0
- System for Cross-domain Identity Management (SCIM)
- FIDO U2F & UAF
- Lightweight Directory Access Protocol (LDAP)

Gluu would make a nice addition to mailcow-dockerized as part of a modern groupware-solution, as well, don't you think? Maybe we could even leverage the LDAP-functionality of SOGo in the long run then, too :joy_cat: .

Well, that's just my wishful thinking :sunglasses: 

EDIT: Here's an example docker-compose.yml btw: https://github.com/GluuFederation/gluu-docker/blob/3.1.4/examples/single-host/docker-compose.yml

**Comment by andryyy** [comment]
We offer LDAP authentication in managed mailcows.

**Comment by Braintelligence** [comment]
But that doesn't provide an exposition for SSO on other web services, right?

Could we leverage the OAuth2 interface of Gluu for Dovecot with this: https://wiki.dovecot.org/PasswordDatabase/OAuth2 ?

**Comment by andryyy** [comment]
We can also integrate SSO in managed mailcows.

**Comment by Braintelligence** [comment]
I see where this is going. Any objections to pull requests integrating Gluu (or similar) with mailcow-dockerized, just for the case that anyone feels up for it?

**Comment by andryyy** [comment]
This will not work. Gluu is a full IAM plattform, we can _use_ it with mailcow, but we cannot integrate it in mailcow: dockerized.

**Comment by Braintelligence** [comment]
I meant integrating it within the ecosystem by adding it to the docker-compose.yml and altering configuration files accordingly if a specific ENV variable is set, for example, so it would be accessible on a given domain and already intertwined with mailcow UI, SOGo and Dovecot (EDIT: and Nextcloud) at the necessary points.

**Comment by andryyy** [comment]
It is possible, but it is very complicated, I guess. SSO over all services is not easy, I also don't see a reason to add Gluu or another IAM, I just ... don't need it. A PR is fine with me, sure, as long as the guy to push it also supports it in the future.

You could also install a stack of Rspamd, Dovecot, Postfix etc. without mailcow and only use Gluu/LDAP in general as identitiy provider with all information like groups/aliases/quota stored in the IAM. That's what most business customers ask for (via LDAP then). These are custom setups that heavily depend on the given infrastructure.

For those interested, just write a mail. \o/

**Comment by Braintelligence** [comment]
Thanks for leaving open the possibility for a feature pr :).

**Comment by andryyy** [comment]
Sure. Why not?

**Comment by andryyy** [comment]
Another idea: Unlocking the account when logging in to mailcow. As long as your session with mailcow UI is valid, your mail account is unlocked. Or unlocking it for a user-defined time.

**Comment by Braintelligence** [comment]
Maybe combine both for safety reasons? But yeah, why not? 😼

**Comment by SomeGeek** [comment]
Sorry for being late to the party. I thought about this as well.

What about the following?

First of all, we disable logging in with user credentials to smtp, imap, eas, etc. Basically every non-webbased service. 

For every web based service (like roundcube, SoGo), we require 2FA. Or at least, it isn't hard to support 2FA when the respective maintainers add it. I read that SoGo [already supports 2FA](https://sogo.nu/bugs/view.php?id=2722) using SAML2 by, eg., using keycloak. However I reckon integrating something like this might not be a trivial task.

So, for the other services, we switch to a token-based model. If you want to use native clients, you first generate a token in the webinterface for the specific services you need (or all of them to start with). I haven't read into this, but it might be possible to tailor it down even more. Like: computer X uses token Y for mailbox foo@bar.com to access SMTP and IMAP.

I think something like this is already much better then the username/password used right now.

**Comment by chriscroome** [comment]
This is a bit of a tangent but the only thing I have thought of that would help here (I have been pondering about this matter for some months) is if the Mailcow server is set not to allow unencrypted HTTP, POP, IMAP or HTTP traffic (apart from Let's Encrypt verifications) and then Mailcow was set not to expose mailbox usernames in email headers (and I guess some things would need configuring with SOGo for this, or perhaps Postfix could simply clean the headers up) then you could use random strings for usernames, for example your login could be:

```
hD6YvCbxeEfDe2NtjJz3gijSOmLwvPXv@example.org
```
And your email address could be:

```
foobar@example.org
```

And if the string `hD6YvCbxeEfDe2NtjJz3gijSOmLwvPXv` cannot be found in any outgoing email headers then for someone to brute force your email account they need to brute force the username before they can then brute force the password and if long random local usernames are used then it would basically become impossible to brute force and once again the weak point would be the MUAs.

The advantage with this approach is that all existing MUAs would still work &mdash; adding 2FA to all existing SMTP and IMAP MUAs in an agreed manner might take a while&hellip;

**Comment by andryyy** [comment]
Just don't expose imap, smtp etc. and use Roundcube with a plugin for TFA. :o That's the easy way right now.

We could integrate SSO into SOGo (not easy) and only allow logins from within mailcow UI, after TFA has been verified.
Yes, this also means not to expose imap, smtp etc. to the public.

**Comment by SomeGeek** [comment]
> Just don't expose imap, smtp etc. and use Roundcube with a plugin for TFA. :o That's the easy way right now.

@andryyy 

I think it will be quite easy to do a small part of what I mentioned, actually. But it's a good start.

Provide the ability to generate tokens on the users' web interface. Save this to a token table in the database. Change the query where postfix/dovecot/etc looks for the passwords, direct them to that table instead. Or am I missing something here?

**Comment by andryyy** [comment]
So you need to generate a token (which ttl?) every time you login with a mail client?!

Much better to just unblock the mailbox when TFA was verified via UI.

AND splitting the behavior of web based clients (native TFA) and external clients?! No way.

I think the best method is to just unblock the services with mailcow UI for a given time. It still sucks... how long is a session valid? You cannot login once and trash the token. The password/login needs to be valid as long as you use mail. Your client will not login once and keep the connection open for imap, smtp etc. as long as you are logged in. That's not how it works. Your client will login several times for each action. And for as long as you are using mail, the password/account needs to be unlocked.

**Comment by chriscroome** [comment]
One additional security feature that would work for me would be to have optional whitelists of IP addresses that are allowed for each mailbox for authenticated SMTP and IMAP, potentially the whitelist could be linked to 2FA?

**Comment by SomeGeek** [comment]
@andryyy 

You sound so negative. Google uses exactly the same method for their Gmail accounts.

This token has a infinite lifetime, until the user deletes it. Also, in the future, we can display activity logs for a given token.

> Much better to just unblock the mailbox when TFA was verified via UI.

So you need to login on a web interface to use a native client... which is there because someone prefers it over a web interface in the first place? Hmmm.

> AND splitting the behavior of web based clients (native TFA) and external clients?! No way.

This is already the case. Mailcow UI has 2FA, everything else doesn't. My proposal allows to add 2FA to the online clients when they support it (or we implemented something to make it work). In the meantime, we solve the problem existing MUA's do not support 2FA given their permanent nature by tokens. If a machine gets compromised, you just retract that token... in a environment you can only access using 2FA.

I should clarify that these tokens are a addition to the passwords / 2FA, not replacements. The tokens are for long term usage, like desktop MUA's.

I think this might be a very solid solution which is not that hard to implement.

**Comment by andryyy** [comment]
I don't think you understand what I mean.

"Google uses exactly the same method for their Gmail accounts." No. I think you miss many, many points here. 

Just create a PR, please.

**Comment by Brightside56** [comment]
@andryyy , will you merge it if I create PR or will say "no, it doesn't fit"?

It can be implemented as written here

https://github.com/mailcow/mailcow-dockerized/issues/740#issuecomment-459328861

All IPs blocklisted by default for IMAP when 2FA is enabled as strict. Whitelisting of IP happens when user is passing 2FA in webui. IMAP server needs to return some message which will point user that 2FA needed

**Comment by andryyy** [comment]
It would be very cool to know how you plan to implement it. :)

Re-use existing mechanisms and no dirty hacks to implement it "some how" (that's what I'm afraid of as most things can be implemented fairly easy if they are hacky).

I think @mkuron agrees, that it would be great to see a plan before working on it. :)

**Comment by mkuron** [comment]
One could build upon `ALLOW_ADMIN_EMAIL_LOGIN` (#2388) to easily put 2FA in front of SOGo‘s web interface.

As for IMAP/SMTP, I don‘t think IP or time-based whitelisting is a good option. It‘s annoying when you change networks (e.g. on your smartphone) and it‘s insecure when you share IP addresses (e.g. on cellular networks). People will activate 2FA, find it super annoying, and deactivate it again.

Also, CardDAV/CalDAV/EAS would need it too, but there it‘s difficult because SOGo doesn‘t have an IP whitelist and Nginx doesn‘t know the authenticated user. Switching off IMAP/SMTP/DAV/EAS to get "full" 2FA is also not a good suggestion as it makes Mailcow significantly less useful.

I think the only proper solution would be to introduce application-specific passwords for IMAP/SMTP/DAV/EAS first. Long, randomly generated passwords that you can use when you set up your client, but don‘t need to memorize or write down. That‘s what Gmail does too. Only then does it make sense to implement 2FA for SOGo. Since all password validation is done in SQL queries, I guess it wouldn’t be that difficult to implement app-specific passwords.

**Comment by SomeGeek** [comment]
> I think the only proper solution would be to introduce application-specific passwords for IMAP/SMTP/DAV/EAS first. Long, randomly generated passwords that you can use when you set up your client, but don‘t need to memorize or write down. That‘s what Gmail does too. Only then does it make sense to implement 2FA for SOGo. Since all password validation is done in SQL queries, I guess it wouldn’t be that difficult to implement app-specific passwords.

This is exactly what I  proposed earlier:

> So, for the other services, we switch to a token-based model. If you want to use native clients, you first generate a token in the webinterface for the specific services you need (or all of them to start with). I haven't read into this, but it might be possible to tailor it down even more. Like: computer X uses token Y for mailbox foo@bar.com to access SMTP and IMAP.

If something goes wrong or a 'token' comes, for any reason, in the 'wrong' hands, you can just delete / reset that token. Would be great if it keeps track of those, so you know when and at what IP it was last used.

Indeed, more services use this too (like Gmail) and it seems to me like a very solid system. Especially because it doesn't break the clients, the token is still your 'password'. Only you have one for each devices, with more tools to manage it on the server side.

**Comment by immanuelfodor** [comment]
Huge +1 for making this change in an incremental fashion, first introducing app specific passwords/tokens. I always feel weird/insecure when I need to use the one and only account password everywhere (Android, scripts, etc).

**Comment by andryyy** [comment]
App specific passwords are fine.

I will probably implement it.

**Comment by andryyy** [comment]
What should it look like?

- Enable TFA for users
- Only enable  app passwds if TFA is enabled
- Disable app passwds if TFA is disabled, even if app passwds exist
- Show app passwds in UI? Does any provider actually do that? Or are they displayed once and then stored hashed?
- ...

**Comment by immanuelfodor** [comment]
IMHO, app passwords should be enabled with and without TFA enabled, as scripts might not be able to auth otherwise. This is like enabling "less secure" apps in GMail for IMAP access (no matter if TFA is used or not). App passwords should be displayed only once with a warning message that it won't be shown again ever, you can only remove them and add another one.

**Comment by mkuron** [comment]
App passwords should be usable independently of 2FA. Display them once, let the user assign a name to them, and store them hashed. The UI should display the names and let the user revoke them individually.

**Comment by andryyy** [comment]
Ok

**Comment by mkuron** [comment]
Now that we have app passwords for Dovecot, I think the next steps would be:
- enable use of app passwords with EAS, CalDAV and CardDAV (but not the SOGo web UI if possible)
- automatically generate an app password when mobileconfig.php is used

And if 2FA is enabled:
- use OAuth to delegate SOGo authentication to Mailcow web UI
- disable use of regular passwords with anything but the Mailcow web UI

**Comment by andryyy** [comment]
I thought about sponsoring IMAP authentication to SOGo. 

Can you write me your thoughts on it? Any better authentication interface for us?

**Comment by mkuron** [comment]
I thought you could log into to SOGo via OAuth, but after checking the documentation, it can actually only do SAML. We could certainly use that though (it‘s conceptually very similar to OAuth). Log into Mailcow web UI with 2FA and then log into SOGo via SAML.

What would you need IMAP authentication for? It doesn’t help with the above scenario. It would help with allowing EAS/DAV with app passwords, but we might be able to do that with a carefully crafted database view. If I read the documentation right, the user ID in the sogo view does not have to be unique, so we could use that to have multiple passwords for the same user.

**Comment by andryyy** [comment]
When we use SAML, we still need full IMAP access. We don't have a valid IMAP login at this point. I know there is a workaround like we do with direct logins to SOGo as admin, but it has some flaws and some things don't work the same way as they do, when you log in with your IMAP credentials. I don't remember what exactly it was, but some settings definitely didn't work as expected. 

If multiple rows are fine for SOGo, our problem would be solved. Otherwise IMAP authentication is an easy and quick fix. But expensive.

**Comment by mkuron** [comment]
Okay, I see. Try the multiple rows and if it doesn't work, it might actually be easier to add that to the SQL authentication backend than to sponsor the implementation of a completely new backend.

**Comment by andryyy** [comment]
I will try. :)

**Comment by mkuron** [comment]
Looking at the source code (https://github.com/inverse-inc/sogo/blob/1892aafae49b72b5fea435d8ed33f6067a108a2a/SoObjects/SOGo/SQLSource.m#L298), I can see that multiple rows are not currently supported. However, all you probably need to change is to put a `while ((row = [channel fetchAttributes: attrs. withZone: NULL]) != nil)` around the password check.

**Comment by andryyy** [comment]
We do also need to disable password changing in SOGo. Or for those using it, Roundcube. They will always change the primary password. That's bad.

**Comment by SomeGeek** [comment]
As we're going to provide a modified version of SOGo anyway, how about the using the opportunity to provide stable releases again, instead of nightlies regulary?

**Comment by andryyy** [comment]
We won't provide a modified SOGo version. 

You can buy SOGos support package, keep them alive and get access to the stable repository. You can build against this stable repository then.

If you sell SOGo, you should get this package.

**Comment by pc-coholic** [comment]
FYI: SOGo 4.3.3 (once released) adds 2FA support "for Google Authenticator"/OATH.

**Comment by phatina** [comment]
> FYI: SOGo 4.3.3 (once released) adds 2FA support "for Google Authenticator"/OATH.

Will generic TOTP work? E.g. FreeOTP from Red Hat... What about U2F support?

Thanks.

**Comment by andryyy** [comment]
Better ask inverse. :)

**Comment by marrobHD** [comment]
Authy support in SOGo would be nice

**Comment by andryyy** [comment]
Wrong tracker. :-)

**Comment by sameer-creator** [comment]
> FYI: SOGo 4.3.3 (once released) adds 2FA support "for Google Authenticator"/OATH.

its not working ...when i am enabling the 2FA its showing massage that copy key to google auth but actually no QR and key is present there ...

**Comment by andryyy** [comment]
Check the time on your server and device aaaand post to the SOGo tracker for SOGo issues, please. :)

**Comment by jmeile** [comment]
I'm also having the same issue as sameer-creator, I'm getting the same text, but no key. See the attachment at the bottom.

As andryyy suggested, I tried to locate the SOGO tracker:
https://github.com/inverse-inc/sogo

There is no tracker there. Does anybody has the link?

Best regards
Josef

![image](https://user-images.githubusercontent.com/2944439/88777614-b1ae4600-d187-11ea-927c-66a77d1cf03e.png)

**Comment by pc-coholic** [comment]
The SOGo-bugtracker is located here: https://sogo.nu/bugs/

With regards to the missing QR-Code: I've seen this bug before, but cannot remember where it was exactly... As far as I remember, it was something about not having the .js-library that produces the barcode included in the built...

**Comment by jmeile** [comment]
Thanks for the link. I will post the bug there.

For the interested:

It turns out that the key is only shown on the source code. I could copy it from there and add it to my Google Authentication. I guess this is indeed a bug with the css style sheets of the configuration page. Here is how it looks like:
![image](https://user-images.githubusercontent.com/2944439/88778550-f2f32580-d188-11ea-98cd-b7fd7f7ce940.png)

**Comment by pc-coholic** [comment]
Actually, it seems like I found the issue right in the SOGo tracker: https://sogo.nu/bugs/view.php?id=5090

Someone else also already posted about the bug in relation to mailcow, which was closed as unrelated to SOGo - yet yielded another commit to apparently fix just that ;-) https://sogo.nu/bugs/view.php?id=5038

**Comment by jmeile** [comment]
I just visited the bug you mentioned and then I saw the same javascript error on the console:
```
ReferenceError: QRCode is not defined
    link sgQrCode.directive.js:30
    Angular 29
 <sg-qr-code text="XXXXXXX">
```

I guess the file you are referring to is this one:
[sogo/UI/WebServerResources/package.json](https://github.com/inverse-inc/sogo/blob/cd37e989db6ca0c6d923373637377486d21b686b/UI/WebServerResources/package.json)

Where is it on mailcow?

By the way: this is a kind of ping-pong game: here it is been said that it should be reported into SOGO, but SOGO says that it should be reported in mailcow. So, it is an infinite loop I guess.

**Comment by jmeile** [comment]
By the way, that will only solve the problem with SOGO; however, you still can login on mailcow UI without 2FA.

Only the administrator can setup 2FA there. A normal user with just a mailbox can't setup this.

**Comment by dragoangel** [comment]
> Authy support in SOGo would be nice

Whenever you see "use Google Authenticator", it always mean that you can use Authy as well as other TOTP apps.

**Comment by dragoangel** [comment]
> Only the administrator can setup 2FA there. A normal user with just a mailbox can't setup this.

This last thing that need to be done if go over SAML implementation.

**Comment by jmeile** [comment]
> This last thing that need to be done if go over SAML implementation.

I don't really understand what you meant here.

So here again my question:
Can you protect the "mailcow UI" (not talking about SOGO) with 2FA? I saw that only the administrator can do it. The option is missing for normal users. So, I don't see any point on activating it for SOGO; on the "mailcow UI" you still can do: 
```
Reset SOGo profile: Reset profile now
This will destroy a users SOGo profile and delete all contact and calendar data irretrievable.
```

So, I guess so you can also bypass 2FA. Not talking about the fact, that you can still access other important stuff on that page.

**Comment by dragoangel** [comment]
> I guess the file you are referring to is this one:
> [sogo/UI/WebServerResources/package.json](https://github.com/inverse-inc/sogo/blob/cd37e989db6ca0c6d923373637377486d21b686b/UI/WebServerResources/package.json)

There isn't such file on filesystem, at least I also cant find it inside volumes or inside container itself via bash.

**Comment by sardaukar** [comment]
I posted the bug report on SOGo - seems to be fixed on their end. What's missing from mailcow to include the fix?

**Comment by MAGICCC** [comment]
Either compile the code on your own or wait until the next version of SOGo is released

**Comment by dragoangel** [comment]
Hi @andryyy, issue already resolved. Can be closed actually.

**Comment by MAGICCC** [comment]
Fixed/Added in https://github.com/mailcow/mailcow-dockerized/commit/00f692fbf9694bdb8003475eda5a0519d6827d5d + https://github.com/inverse-inc/sogo/commit/c73b40f62c96c72554c767959da85ed0b6a83bd2

**Comment by dragoangel** [comment]
@jmeile 
> So, I guess so you can also bypass 2FA. Not talking about the fact, that you can still access other important stuff on that page.

If you doesn't know: SOGo 2fa doesn't enable 2fa for EAS & carddav & caldav so no matter actually - your mail still available till you not lock out all EAS & IMAP 🙄.
