### ISSUE TITLE
Own SSL not working

### ISSUE THREAD

**Issue by tesoner** [mailcow/mailcow-dockerized#741]
I need some help to install own SSL in mailcow.
First, my SSL is a Comodo cert, (multi subdomains)
I did compose a .pem file as says https://ssl.comodo.com/support/creating-a-pem-file.php
> -----BEGIN CERTIFICATE----- 
(Your Primary SSL certificate: your_domain_name.crt) 
-----END CERTIFICATE----- 
-----BEGIN CERTIFICATE----- 
(Your Intermediate certificate: COMODOCA.crt) 
-----END CERTIFICATE----- 
-----BEGIN CERTIFICATE----- 
(Your Root certificate: AddTrustExternalCAROOT.crt) 
-----END CERTIFICATE-----

(Also i tried this config)
> -----BEGIN CERTIFICATE----- 
(Your Primary SSL certificate: your_domain_name.crt) 
-----END CERTIFICATE----- 
-----BEGIN CERTIFICATE----- 
(Your Intermediate certificate: COMODOCA.crt) 
-----END CERTIFICATE-----
but the result is same...

I did use the https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#use-own-certificates tutorial.

> To use your own certificates, just save the combined certificate (containing the certificate and intermediate CA/CA if any) to data/assets/ssl/cert.pem and the corresponding key to data/assets/ssl/key.pem.

Restart changed containers by running docker-compose up -d --no-recreate.
Also i did restart the services running `docker-compose restart dovecot-mailcow` (for each service)

I did a test in https://www.checktls.com/ and the results sounds good:
![test result](http://pix.toile-libre.org/upload/original/1510517967.png)

*But the email client allways says:*
![email client error](http://pix.toile-libre.org/upload/original/1510518167.png)

**Comment by K2rool** [comment]
Hi, you might forgot a Intermediate cert or chained the cert in the wrong order.

Mail client are more picky about ssl cert chain than browser, You can test if the cert is chain right on https://www.ssllabs.com/ssltest/ it should come back as Chain issues None.

I got a Comodo cert on one of my server too how i combine the cert was in the email when Comodo issued the cert in a zip file domain.crt and domain.ca-bundle just add the line in ca-bundle file to the end of crt file and use that for the ssl cert on Mailcow.
