### ISSUE TITLE
Outdated Docker Hub Images (mailcow/phpfpm:1.4)

### ISSUE THREAD

**Issue by danielmorlock** [mailcow/mailcow-dockerized#742]
The most recent mailcow/phpfpm:1.4 image on Docker Hub (https://hub.docker.com/r/mailcow/phpfpm/tags/) is outdated (last change 10 days ago) and does not reflect the recent changes from https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/phpfpm/Dockerfile (last change 23 days ago). 

So one do not need the Docker Hub if using docker-compose and building locally out of the repo. So do you plan to further support the Docker Hub or is it deprecated?

**Comment by markirb** [comment]
This is just a display issue, the hub file show  something else, but obviously not the current Dockerfile.

If you look at the commands, which your image was built with, you can see it is the current one:
`docker history --no-trunc  mailcow/phpfpm:1.4 `

**Comment by danielmorlock** [comment]
I'm just wondering why the `/usr/src/php.tar.xz` is missing when I download it from Docker Hub but does exist when I build it from source.

**Comment by andryyy** [comment]
It is fixed. 👍
