### ISSUE TITLE
(solved) ipv6 doesn't work beside docker

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#744]
Hello,

I update mailcow-dockerized to latest version. But I find ipv6 doesn't work beside it.

Before I start mailcow, I can do ping6, but after I start mailcow, it shows:
```
ping6 ipv6.google.com
connect: Network is unreachable
```
```
eth0      Link encap:Ethernet  HWaddr 02:6F:59:xx:xx:xx
          inet addr:172.31.18.127  Bcast:172.31.31.255  Mask:255.255.240.0
          inet6 addr: fe80::6fxxxxx/64 Scope:Link
          inet6 addr: 2a05:d01xxxxx/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:723257 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52570 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1048689755 (1000.1 Mb)  TX bytes:7283222 (6.9 Mb)

```
Only I reboot the server, the ping6 comes back.

On docker forum, it says the latest docker has this bugs so I switch back old docker version.

```
docker -v
Docker version 1.12.6, build 78d1802

docker-compose --version
docker-compose version 1.17.1, build 6d101fb
```

I used a old version of mailcow-dockerized(I forget which version) with docker 1.12.6 before, ipv6 works well.

Does someone know the problem? Thank you.

**Comment by mkuron** [comment]
Try the most recent version, 17.09.0-ce. That definitely works.
What did you find on the Docker forum? I am not aware of any such bug in recent versions.
Do you have a firewall set up on the host? If so, disable it for testing — Docker is known to sometimes interact adversely with existing iptables rules.

**Comment by pyy** [comment]
Thank for your comments.

The thing is:
I make a new mailcow-dockerized server under OpenSUSE 42.3 which offers docker 17.04.0-ce as default. But I meet all IPv6 interface got removed after I start mailcow.

As here reported:
https://github.com/moby/moby/issues/32433

So I change back to old docker 1.12.6, but it looks like that ipv6 doesn't work with this new version mailcow, which worked with old mailcow-dockerized before.

Thank you @mkuron , I will try  docker 17.07.0-ce first, and also try to disable firewall in the server.

**Comment by pyy** [comment]
I have tested on OpenSUSE 42.3 with docker 17.07.0-ce, and Debian9 with 17.09.0-ce. I use AWS EC2.

They all have the same problems.

Before start mailcow-dockerized, ipv6 works fine. I can ping out and also ping back from outside world.
But after start mailcow-dockerized, there is ipv6 interface, but cannot ping6 and also get time out when I ping this server from outside world.

I have tried disable firewall, but it still the same problem.

```
# iptables -S
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-N DOCKER-USER


```

I don't know it's docker's bug or mailcow's bug, or EC2's bug.

**Comment by pyy** [comment]
I solved the problem. 
Get help from https://github.com/moby/moby/issues/20559#issuecomment-217623129

It looks when docker start, it remove the default ipv6 gateway of the host. So I manually add it back, and then everything works fine now.

1. Before start mailcow, get the default ipv6 gateway info.
```
# ip -6 route show
2a05:d014:12b:xxxxxx dev eth0 proto kernel metric 256  pref medium
fe80::/64 dev eth0 proto kernel metric 256  pref medium
default via fe80::4f:49ff:fec7:xxx dev eth0 proto ra metric 1024  expires 1792sec hoplimit 64 pref medium
```
2. After mailcow start, add ipv6 gateway back:
```
# ip -6 route add default via fe80::4f:49ff:fec7:xxx dev eth0
```
3. Then try it again:
```
# ping6 ipv6.google.com
PING ipv6.google.com(pc-in-x8a.1e100.net (2607:f8b0:400e:c04::8a)) 56 data bytes
64 bytes from pc-in-x8a.1e100.net (2607:f8b0:400e:c04::8a): icmp_seq=1 ttl=38 time=147 ms
64 bytes from pc-in-x8a.1e100.net (2607:f8b0:400e:c04::8a): icmp_seq=2 ttl=38 time=147 ms
64 bytes from pc-in-x8a.1e100.net (2607:f8b0:400e:c04::8a): icmp_seq=3 ttl=38 time=147 ms
```

```
# docker-compose exec nginx-mailcow ping6 ipv6.google.com
PING ipv6.google.com (2a00:1450:4001:81d::200e): 56 data bytes
64 bytes from 2a00:1450:4001:81d::200e: seq=0 ttl=55 time=1.885 ms
64 bytes from 2a00:1450:4001:81d::200e: seq=1 ttl=55 time=1.721 ms
64 bytes from 2a00:1450:4001:81d::200e: seq=2 ttl=55 time=1.742 ms

```

**Comment by christianbur** [comment]
I have a similar problem when starting a docker network with ipv6 support (with Unique Local Unicast addresses), no outbound ipv6 communication is possible (on the host and in the containers). The ipv6 communication initiated ffrom the Internet works fine again. 
As soon as I shut down all docker networks with ipv6, the ipv6 communication from the host (to the internet) also works again.  

Docker Version Version:	18.03.0-ce.

The default route ist set `default via fe80::1 dev eth0  metric 1024  pref medium`
ping6 works `ping6 fe80::1%eth0`
