### ISSUE TITLE
SKIP_LETS_ENCRYPT is checked too late

### ISSUE THREAD

**Issue by mikrorechner** [mailcow/mailcow-dockerized#745]
The acme/docker-entrypoint.sh script currently only checks the SKIP_LETS_ENCRYPT variable in line 104. Because of that, it interferes with certificates in ${ACME_BASE} and makes it impossible to symlink certs and keys that are managed outside of mailcow.

Shouldn't the check happen before anything is actually done in the acme container?

**Comment by andryyy** [comment]
I moved it to the top. Remember that symlinking does not work, use hard links instead. 👍 

It is fixed in dev, I will merge this to master soon.

**Comment by mikrorechner** [comment]
Thanks for the fantastically fast reply and fix.

Hard links don't work for me unfortunately because they keys are kept on a different volume, but I need to have a skript to restart the containers anyway, so it can just as well copy over the files.
