### ISSUE TITLE
Enable sub-addressing

### ISSUE THREAD

**Issue by TiiFuchs** [mailcow/mailcow-dockerized#748]
Hi I'd like to use sub-addressing.
So I had a look into the postfix configuration.
In main.cf there was already an entry for recipient_delimiter.
In master.cf the maildrop configuration was missing some changes.

So I changed according to the docs http://www.postfix.org/MAILDROP_README.html#direct
I changed to `    maildrop  unix  -       n       n       -       -       pipe
      flags=ODRhu user=vmail argv=/path/to/maildrop 
      -d ${user}@${domain} ${extension} ${recipient} ${user} ${nexthop}`

Then I did a docker-compose down and docker-compose up -d and checked the config with docker exec. Everything was provisioned perfectly. But sadly it does not seem to work.
Did I miss anything? Does somebody already use this?

Thanks :)

**Comment by TiiFuchs** [comment]
Oh I just saw in the logs (overlooked that in the first place)

`stored mail into mailbox 'INBOX/Subaddressing'` (I sent an mail to user+subaddressing@domain.tld)

But I can't access this mail in SOGo. There is no folder visible.

Anyway. I'd like to have this mail in the inbox as every other mail too.

**Comment by andryyy** [comment]
You can click the folder symbol left to "INBOX". It expands. 👍

**Comment by TiiFuchs** [comment]
Yeah, but this does not work when the folder did not exist earlier. You have to relogin for the folder to be visible in SOGo.

But that's not what I want to achieve. I want those mails in the INBOX not in any subfolder.

But I skimmed a few configs and stumbled upon a config named sieve_after in the dovecot folder.
There is some code that appears to do exactly what I don't want. So I will comment it out and test if that does the job.

**Comment by mkuron** [comment]
You can log into the admin interface as your user and configure whether you want the subaddresses to go into subfolders or have the tag prepended to the subject.

**Comment by TiiFuchs** [comment]
So I found the option to change the behaviour from "subfolder" to "subject" in the backend. But since I need a "do nothing" option, I'm a little bit screwed.

(Background: I use a mailbox for incoming mail in GitLab, and it need's subaddressing to identify where the mail belongs to. You can give it one folder (inbox, no subfolders) and the subject will be the title of the issue. So neither subfolder nor subject is an option)

I thought I crawl the code and just add the option for doing nothing instead, but I can't find where the subject get's added to the email. Maybe someone can give me the hint, where to find the code for the subject changing. (I assume the `fileinto "INBOX/${1}";` part in data/conf/dovecot/sieve_after does the part for the folder moving, but there is no condition for the RCPT_WANTS_SUBJECT_TAG variable from redis.)
