### ISSUE TITLE
fail2ban restarting

### ISSUE THREAD

**Issue by menzerath** [mailcow/mailcow-dockerized#749]
I just updated my mailcow installation and since one of the latest commits (84a7a1a2e7e0015018f23f2e10a7fc1c89711dca I think) is fail2ban unable to start (`Restarting (1) 39 seconds ago`).
The log contains the following error:
```
IndentationError: unindent does not match any outer indentation level
  File "/logwatch.py", line 150
    ip = ipaddress.ip_address(addr.decode('ascii'))
                                                  ^
```

**Comment by andryyy** [comment]
Fixed it, sorry.

**Comment by menzerath** [comment]
Thanks!
