### ISSUE TITLE
Sieve Filter Edit not working

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#750]
Today i was playing with sieve filters and recognized that the edit function does not work correctly. It does not update the sieve filter. To adapt changes i have to remove the filter and add it again with the changes. I tried it for the type "Prefilter". There is no error message.

**Comment by andryyy** [comment]
Hmmm, can you delete your browser cache? I tried as admin and domain admin and couldn't reproduce it.

**Comment by phipag97** [comment]
Even when i delete my browser cache it does not work. But i see i wrote not precise enough. I see the updated script in the mailcow interface but the function is still of the old one.

This is my script:
```
require ["reject"];

if not address :is "from" [
	"xxx1",
	"xxx2"
]
{
	reject "Sie sind nicht authorisiert E-Mails an diese Adresse zu versenden.";
}
else
{
	redirect "xxx1";
	redirect "xxx2";
	redirect "xxx3";
	keep;
}
```

if i add or delete a redirect, the changes are only considered if i completely delete and readd the script.

**Comment by andryyy** [comment]
Ahh, okay, that could be due to the cache of Dovecot. Can you try to change `data/conf/dovecot/dovecot.conf` like this? =>

```
  sieve_before = dict:proxy::sieve_before;name=active;bindir=/var/vmail/sieve_before_bindir
  sieve_after = dict:proxy::sieve_after;name=active;bindir=/var/vmail/sieve_after_bindir
```
...to...
```
  sieve_before = dict:proxy::sieve_before;name=active;
  sieve_after = dict:proxy::sieve_after;name=active;
```
Restart Dovecot by running `docker-compose restart dovecot-mailcow`.

**Comment by andryyy** [comment]
Okay, I totally missed this => `Sieve uses the ID number as its cache index and to detect the need to compile. Therefore, if a script is changed, then its ID must also be changed for it to be reloaded. `
Will fix it in a bit.
