### ISSUE TITLE
IP spoofing? Unauthorized relay

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#758]
Hi,
I started to have this strange logs on our mail server.

18/11/2017, 22:28:49 | info | disconnect from unknown[172.22.1.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
-- | -- | --
18/11/2017, 22:28:49 | info | 25AAF13B565: to=<peter.patzwaldt@t-online.de>, relay=none, delay=0.39, delays=0.39/0/0/0, dsn=4.0.0, status=deferred (delivery temporarily suspended: host mx02.t-online.de[194.25.134.9] refused to talk to me: 554 IP=46.101.96.188 - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL))
18/11/2017, 22:28:49 | info | 25AAF13B565: from=<info@18months.it>, size=1889, nrcpt=1 (queue active)
18/11/2017, 22:28:49 | info | 25AAF13B565: message-id=<b1fcbfa138eab793f4bd9942de4403f0@www.doktorpotenz-hormone.com>
18/11/2017, 22:28:49 | info | 25AAF13B565: client=unknown[172.22.1.1]
18/11/2017, 22:28:49 | info | connect from unknown[172.22.1.1]
18/11/2017, 22:28:49 | info | WHITELISTED [172.22.1.1]:56958
18/11/2017, 22:28:49 | info | CONNECT from [172.22.1.1]:56958 to [172.22.1.6]:25

Someone has an explanation for that?
thanks

**Comment by K2rool** [comment]
Is this the strange line your talking about 

> delivery temporarily suspended: host mx02.t-online.de[194.25.134.9] refused to talk to me: 554 IP=46.101.96.188 - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL))

That just Deutsche Telekom mail servers rejecting your email due to your server ip been listed in there internal black list.

Since your talking about IP spoofing am guessing your talking about the IP address 172.22.1.1 I believe that is the IP that is logged when you relay email from the docker host server to Mailcow Postfix container.

**Comment by albertodega** [comment]
hi, i'm working on solving the problem stated above.
yes, 172.22.1.1 is the ip of the docker bridge.
and yes, de-telekom banned us beacuse of this problem: it's a few hours someone is using our servers as a relay. after digging a lot, i think it could be related to #202, but i'm unable to completely stop ipv6 connections, which seems to come directed to ::ffff:our_ipv4_ip . how can i stop that?

**Comment by mkuron** [comment]
If all incoming connections seem to be coming from 172.22.1.1, that means that they are relayed by Docker‘s userland proxy and not properly going through NAT. This might happen if you have a host firewall configured that creates its own iptables/ip6tables rules. If only IPv6 connections are affected, then perhaps Mailcow‘s ipv6nat container did not come up properly.

To quickly secure your open relay, you can turn off the userland proxy by butting the following into /etc/docker/daemon.json:
```
{
    "userland-proxy": false
}
```
This may cause your containers to lose internet access completely though if the NAT rules are missing. For further debugging, there are a few commands that may be helpful: `iptables --list`, `ip6tables --list`, `ifconfig`.

**Comment by K2rool** [comment]
I remember reading a few docker issue over the years that setting userland-proxy to false sometime result in the kernel error unregister_netdevice: waiting for interface become free which you need to force restart the server since it locks up the whole server not too sure if they ever fix that issue.

**Comment by mkuron** [comment]
>setting userland-proxy to false sometime result in the kernel error unregister_netdevice

That was a kernel bug that should be mostly fixed nowadays. If everything is configured correctly (i.e. NAT is working), no traffic should ever flow via the userland proxy. In fact, the Docker team has been debating to drop the userland proxy entirely for a while.

> `docker-compose down ipv6nat`

Taking ipv6nat down will cause all IPv6 traffic to flow via the userland proxy. That's not what you want. If you completely want to disable IPv6 (which you shouldn't), then you need to remove all IPv6 addresses from all network interfaces.

**Comment by K2rool** [comment]
Did not know that disabling it would cause all the traffic to go via userland proxy not rely a issue for my server since i don't have ipv6 added to my server anyway.

I've removed my suggestion of doing that from my last comment in case someone dose it and make the issue worst.

**Comment by samuelebistoletti** [comment]
For now we solved by disabling IPv6 on a firewall level. But this issue must be fixed out of the box for Mailcow, in my opinion. This is a huge problem since every Mailcow deploy that supports IPv6, by default, is an open relay for spammers!

**Comment by andryyy** [comment]
No, it is not an open relay for spammers.

**Comment by samuelebistoletti** [comment]
But that was our situation, a default installation, with no custom configuration on a Digital Ocean droplet. Can you please explain me why that situation wouldn't be replicable on any Mailcow deploy with that environment? Maybe I'm wrong, so I would like to fully understand the problem. Thanks

**Comment by mkuron** [comment]
> with no custom configuration on a Digital Ocean droplet

@samuelebistoletti, does Digital Ocean have any non-default Docker configuration?

> must be fixed out of the box for Mailcow

It's nothing that can be fixed on the Mailcow level. If the userland proxy rewrites requests to appear to be coming from a local address, then the Postfix server permits them.

**Comment by samuelebistoletti** [comment]
I mean no custom configuration on Mailcow level, I followed the guide on Mailcow website, that's all, on an Ubuntu 16.04 image with a DO firewall to expose the requested ports.
At this point I think that a warning on Mailgun docs website would be the right thing.
Thanks

**Comment by mkuron** [comment]
@andryyy, I think your change 4c98cbec27f17b05d81e7ff3a8835789e2b02a86 (which aims to prevent the open relaying in misconfiured setups) may break this: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/

**Comment by andryyy** [comment]
Yes, it does. :-/ We should change the docs. Or do you have another idea to prevent this when ipv6 nat fails?

**Comment by K2rool** [comment]
The edit to exclude 172.22.1.1 from mynetwork, for the local mta you could just update the docs to tell the user to create or use a existing mailbox on Mailcow and config the local mta to use relayhost with sasl_auth.

**Comment by mkuron** [comment]
I‘d still like to know why ipv6nat didn’t work for @samuelebistoletti... it‘s been rock solid for me and probably everyone else. Maybe he can still provide the ipv6nat logs and the ip6tables output I requested. After all, @andryyy‘s change doesn’t fix the problem for him, it only prevents the problem from being used as an open relay.

**Comment by mkuron** [comment]
Just a warning: @andryyy has reverted the `mynetworks` change in b1855587ec9076c8660e87b58db700cda07b6dad, so be careful when you upgrade, @samuelebistoletti. If you can provide it, I‘d still like to see the `iptables` output to understand what actually goes wrong on your server.

**Comment by samuelebistoletti** [comment]
Hi removing the network 172.22.1.1 from mynetwork was useless. An hour ago I started having unauthorized relay again, and that network was excluded from mynetworks.
IPv6 was already fully disabled, also removed IPv6 network configuration from /etc/network/interfaces.
Now I disabled userland proxy as suggested above, and it seems that open relay problem was resolved, but I'm not really sure, we should wait some time.

Any help would be really appreciated, thanks.

This is my iptables-save output right now:
# Generated by iptables-save v1.6.0 on Tue Dec  5 22:18:50 2017
*nat
:PREROUTING ACCEPT [3100:229947]
:INPUT ACCEPT [7:468]
:OUTPUT ACCEPT [78:5299]
:POSTROUTING ACCEPT [244:15394]
:DOCKER - [0:0]
-A PREROUTING -i eth0 -p tcp -m tcp --dport 2525 -j REDIRECT --to-ports 25
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -o docker0 -m addrtype --src-type LOCAL -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o br-5d906e7aae29 -m addrtype --src-type LOCAL -j MASQUERADE
-A POSTROUTING -s 172.22.1.0/24 ! -o br-5d906e7aae29 -j MASQUERADE
-A POSTROUTING -s 172.22.1.0/24 ! -o br-49c007873c90 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 587 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 465 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 25 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 12345 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 4190 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 995 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 993 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 143 -j MASQUERADE
-A POSTROUTING -s 172.22.1.7/32 -d 172.22.1.7/32 -p tcp -m tcp --dport 110 -j MASQUERADE
-A POSTROUTING -s 172.22.1.251/32 -d 172.22.1.251/32 -p tcp -m tcp --dport 443 -j MASQUERADE
-A POSTROUTING -s 172.22.1.251/32 -d 172.22.1.251/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A POSTROUTING -s 172.22.1.3/32 -d 172.22.1.3/32 -p tcp -m tcp --dport 587 -j MASQUERADE
-A POSTROUTING -s 172.22.1.3/32 -d 172.22.1.3/32 -p tcp -m tcp --dport 465 -j MASQUERADE
-A POSTROUTING -s 172.22.1.3/32 -d 172.22.1.3/32 -p tcp -m tcp --dport 25 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 12345 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 4190 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 995 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 993 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 143 -j MASQUERADE
-A POSTROUTING -s 172.22.1.4/32 -d 172.22.1.4/32 -p tcp -m tcp --dport 110 -j MASQUERADE
-A DOCKER -p tcp -m tcp --dport 587 -j DNAT --to-destination 172.22.1.4:587
-A DOCKER -p tcp -m tcp --dport 465 -j DNAT --to-destination 172.22.1.4:465
-A DOCKER -p tcp -m tcp --dport 25 -j DNAT --to-destination 172.22.1.4:25
-A DOCKER -d 127.0.0.1/32 -p tcp -m tcp --dport 19991 -j DNAT --to-destination 172.22.1.7:12345
-A DOCKER -p tcp -m tcp --dport 4190 -j DNAT --to-destination 172.22.1.7:4190
-A DOCKER -p tcp -m tcp --dport 995 -j DNAT --to-destination 172.22.1.7:995
-A DOCKER -p tcp -m tcp --dport 993 -j DNAT --to-destination 172.22.1.7:993
-A DOCKER -p tcp -m tcp --dport 143 -j DNAT --to-destination 172.22.1.7:143
-A DOCKER -p tcp -m tcp --dport 110 -j DNAT --to-destination 172.22.1.7:110
-A DOCKER -p tcp -m tcp --dport 443 -j DNAT --to-destination 172.22.1.251:443
-A DOCKER -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.22.1.251:80
COMMIT
# Completed on Tue Dec  5 22:18:50 2017
# Generated by iptables-save v1.6.0 on Tue Dec  5 22:18:50 2017
*filter
:INPUT ACCEPT [5411:561886]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [12526:5893912]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:DOCKER-USER - [0:0]
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-5d906e7aae29 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-5d906e7aae29 -j DOCKER
-A FORWARD -i br-5d906e7aae29 ! -o br-5d906e7aae29 -j ACCEPT
-A FORWARD -i br-5d906e7aae29 -o br-5d906e7aae29 -j ACCEPT
-A FORWARD -o br-49c007873c90 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-49c007873c90 -j DOCKER
-A FORWARD -i br-49c007873c90 ! -o br-49c007873c90 -j ACCEPT
-A FORWARD -i br-49c007873c90 -o br-49c007873c90 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 587 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 465 -j ACCEPT
-A DOCKER -d 172.22.1.4/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 25 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 12345 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 4190 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 995 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 993 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 143 -j ACCEPT
-A DOCKER -d 172.22.1.7/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 110 -j ACCEPT
-A DOCKER -d 172.22.1.251/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.22.1.251/32 ! -i br-5d906e7aae29 -o br-5d906e7aae29 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION -i br-5d906e7aae29 -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o br-5d906e7aae29 -j DROP
-A DOCKER-ISOLATION -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Tue Dec  5 22:18:50 2017

**Comment by riki137** [comment]
This is a pretty serious issue. My SMTP server was abused by IP spoofing spambots and wrecked my SendGrid reputation (because of SendGrid relay usage). I'm not sure why this is closed.

If anybody stumbles upon this, don't forget to clear your postfix mail queue after securing your server!

`docker-compose exec postfix-mailcow postsuper -d ALL` while container is running.

This should definitely be reopened.

**Comment by Adorfer** [comment]
This is out of scope here. unresponsible docker setups are not an bug or issue of mailcow.
