### ISSUE TITLE
dovecot: lmtp error after startup

### ISSUE THREAD

**Issue by phpfs** [mailcow/mailcow-dockerized#759]
Hello :)

Today, my dovecot log showed this error after I did `docker-compose up -d`:

```
19.11.2017, 14:53:17 | info | ssl-params: SSL parameters regeneration completed
-- | -- | --
19.11.2017, 14:53:11 | crit | lmtp: Fatal: master: service(lmtp): child 53 killed with signal 9
19.11.2017, 14:53:11 | err | master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
19.11.2017, 14:52:37 | info | ssl-params: Generating SSL parameters
```

Earlier, I was trying to build a backup-container to automate mailcow-to-s3 backups (https://github.com/phpfs/mailcow-backup-s3), but I don't know why this would interfere with dovecot... (all volumes are `:ro`)

Do you have any idea what this is about or related to?

Thanks so far :)

P.S.: Besides that, everything else works fine - I am able to send & receive emails as normally!

**Comment by andryyy** [comment]
Not a problem, just wait for it to finish regeneration. You may want to stop watchdog-mailcow if it takes too long. Watchdog does not yet wait for Dovecot to regenerate DH params - we should copy the dhparams anyway, I think.

**Comment by phpfs** [comment]
So watchdog is causing `crit | lmtp: Fatal: master: service(lmtp): child 53 killed with signal 9`?

**Comment by andryyy** [comment]
Yes, well, it tries to access lmtp and Dovecot kills it when it still is regenerating the dh params.
