### ISSUE TITLE
How to reset admin password Mailcow Docker?

### ISSUE THREAD

**Issue by garybsimon** [mailcow/mailcow-dockerized#76]
Hi,

I'm stucked at login screen.
How can change the admin password at Mailcow Docker version?
The old password change methods don't work.

Please let me know.
Thanks.

Great work.

**Comment by PhoenixPeca** [comment]
Hi @garybsimon, 
If you're in a new install of mailcow-dockerized. The default login credentials for admin is: 
Username: admin
Password: moohoo

For resetting a forgotten admin password, please refer to the docs: [https://mailcow.email/dockerized/?c=IV.%20Usage%20and%20Examples&p=Reset_admin.md](https://mailcow.email/dockerized/?c=IV.%20Usage%20and%20Examples&p=Reset_admin.md)

**Comment by garybsimon** [comment]
I have tried to get a new password or reset the db but I got this message:

> source mailcow.conf
mailcow-reset-admin#: command not found
> 

Need assistance :)

**Comment by PhoenixPeca** [comment]
Hi @garybsimon,
I haven't tried resetting mailcow-dockerized with this method. But I think before you can reset it, you need to change directory into the cloned repo in your home directory first.

Try to execute this:
`cd ~/mailcow-dockerized/`

`source mailcow.conf`

`docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DROP TABLE admin;"`

**Comment by i3i2ain** [comment]
> Hi @garybsimon,
> I haven't tried resetting mailcow-dockerized with this method. But I think before you can reset it, you need to change directory into the cloned repo in your home directory first.
> 
> Try to execute this:
> `cd ~/mailcow-dockerized/`
> 
> `source mailcow.conf`
> 
> `docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DROP TABLE admin;"`

DO NOT delete the admin table. This will break the whole installation. It cost me like 1 day to recover everything since I did not have any backup.

Use the official way / script from here: https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/

**Comment by esstat17** [comment]
I recently have a problem, maybe it can help.

# Show all running containers
```sh
docker compose ps -a
```
## Login to your docker container
docker exec -it sh mailcowdockerized-mysql-mailcow-1

## See password from mailcow.conf
mysql -uroot -p{PASSWORD} mailcow

## To list the tables within the mailcow database, you can use the following SQL command:
MariaDB [mailcow]> SHOW TABLES;
```sql
SHOW TABLES;
```

## Show admins
```sql
SELECT * FROM admin;
```

## Change password for user `admin`. Replace it with the actual username
```sql
UPDATE admin SET password = '{BLF-CRYPT}$2y$10$NEW_PASSWORD_HASH' WHERE username = 'admin';
```
## Remember to replace NEW_PASSWORD_HASH with the actual hash of the new password you want to set.

**Comment by Tariquaf** [comment]
1. Login to SSH

2. Change directory
cd /opt/mailcow-dockerized

3. Run following script
./helper-scripts/mailcow-reset-admin.sh

4. Type y and enter

It will reset your password and will display new password

Please note that this only changes the administrator password and not your password for SoGo or IMAP/SMTP logins.

**Comment by rosmarflores** [comment]
Please make sure you are in correct login page, if you wanted to login to admin panel you should go to domain.com/admin
I found that there are several login pages for mailcow such as /, /domainadmin, /admin what made me confused easily..
