### ISSUE TITLE
Firefox 57 is meant to support FIDO U2F but it doesn't work in mailcow

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#760]
Hello everyone!
I used an addon for Firefox to enable FIDO U2F which doesn't seem to be available for Firefox 57. But it seems Firefox 57 supports FIDO U2F natively: https://wiki.mozilla.org/Security/CryptoEngineering#Web_Authentication

Can you incorporate this into mailcow?

**Comment by Braintelligence** [comment]
Also I seem to have problems using FIDO U2F with ChromePortable latest version (62.0.3202.94), trying out another version now.

EDIT: Beta 63 also doesn't work. Trying native installed app instead of portable now.

EDIT2: Yup, something's wrong. They website is refreshing every 3 seconds saying `U2F: User-agent returned error. Error code: 2`

EDIT3: Ah, I found the culprit. It seems this only works via HTTPS. For some reason chrome decided to request the site via HTTP. I thought I had applied forced HTTPS to my config... Strange. @andryyy Does the update.sh not stash and pop changes to the nginx.conf and such?

**Comment by Braintelligence** [comment]
Upon further inspection you need to set `security.webauth.u2f` in about:config first, which is set to false. ( https://www.reddit.com/r/firefox/comments/71swp5/firefox_nightly_enables_support_for_fido_u2f/dndj9ph/ )

But mailcow UI doesn't recognize my Yubikey, it doesn't even flash. It works in the Yubico U2F demo with these settings, though: https://demo.yubico.com/u2f

EDIT: Getting these errors in mailcow UI:
![grafik](https://user-images.githubusercontent.com/6761196/32991664-ee7ba018-cd3f-11e7-8541-3e3137678549.png)
And also this below the big, grey SOGo button: `Warning: Invalid argument supplied for foreach() in /web/index.php on line 76`

**Comment by Braintelligence** [comment]
Related: https://github.com/kvhnuke/etherwallet/issues/1122

**Comment by andryyy** [comment]
I will fix it in a few mins. I will also answer your mail then, sorry @Braintelligence

**Comment by Braintelligence** [comment]
Dude, never apologize to anyone here, you're a life-saver 😸.

**Comment by andryyy** [comment]
Version 62.0.3202.94 of Chrome works fine!

But Firefox does indeed use u2f_sign/register in a different way Chrome does. I... have no idea. I think a function needs to return a different JSON array as requests var. For Chrome it is [{bla1},{bla2}] etc. - but Firefox needs something like {bla1:[{bla1.1,bla1.2}]} etc.

It looks like Chrome supports both variants, but I'm not sure. We should ask @Yubico what is going on here. Could be different U2F versions?!

**Comment by andryyy** [comment]
Oh, check this out: https://github.com/Yubico/php-u2flib-server/issues/58 I will fix it later then. Damn, I should have checked this before. :-D

**Comment by Braintelligence** [comment]
@andryyy Chrome works fine for me, as soon as I use HTTPs. For some reason my Chrome decided to visit it on HTTP, even though I set up forced HTTPS some updates ago. Does the update.sh overwrite your confs? I thought it would stash your old config and pop it afterwards.

**Comment by Braintelligence** [comment]
It really seems like the update.sh doesn't care for https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

What would be the best way to handle this?

**Comment by andryyy** [comment]
It does merge but prefers changes from mailcows repo. It _should_ not overwrite unless there is a conflict. You could try to add a new site like redir.conf.

**Comment by Braintelligence** [comment]
I'm only running mailcow on the whole virtual machine, though. I would just prefer for it to use HTTPS, since ACME is used by default anyway.

**Comment by Braintelligence** [comment]
Please drop me a comment here, when you've implemented this @andryyy 😸.
No hurries though, just wanted to make sure I'll know when it happened, since we don't really have "releases".

**Comment by andryyy** [comment]
Should be fixed now in dev. :-) But we need to add a text when adding a second key like "Insert your new U2F device now". When you try to add an already known key, it discards the key and times out.

**Comment by Braintelligence** [comment]
So if you try to add a new key, which was already being used, this key will be deleted from database instead?

**Comment by andryyy** [comment]
It just ignores the key. Without any errors. After a while you will see an error code 1, which - in this case - indicates a timeout.

**Comment by Braintelligence** [comment]
Ok, I see. Looking forward to a ping, when this hits master branch 😸 .
