### ISSUE TITLE
Please review phpfs/mailcow-backup-s3

### ISSUE THREAD

**Issue by phpfs** [mailcow/mailcow-dockerized#761]
Hi there :)

I personally like mailcow a lot - but for me it was missing a good way to automatically backup to f.ex. AWS S3.

Therefore, I created https://github.com/phpfs/mailcow-backup-s3/ :)

Please review, if my container is compliant with the mailcow-dockerized ecosystem - Thanks a lot ;)

Greetings, phpfs

**Comment by mkuron** [comment]
You should also back up the redis database (ideally, use the redis client to dump it), the Postfix queue (in case there are any messages that couldn’t be delivered to the destination server yet), and the rspamd training state. All of these are on separate volumes.

**Comment by markirb** [comment]
Hi,

love the idea, I was missing the same thing, but I don't use S3...

So in the last few days I assembled my own dockerized backup solution (right now i use a NAS), which can be configured to backup all your mailcow volumes as well a dump of the sql (and more..). I think it can easily be adapted to [S3](https://github.com/blacklabelops/volumerize/tree/master/backends/AmazonS3) (and use encryption!).
I used it some days now and got to a state where I want to share it. Have a look
https://github.com/markusg/backup-dockerized

@mkuron the redis volume already contains a dump right? (which is written to once in a while)

Also I am not sure if it really makes sense to backup the postfix queue. I think it is easy to backup an inconsitent state, but at the same time you do not want to hold the queue and thus your mailserver for just for a backup (?)

**Comment by mkuron** [comment]
The Redis volume contains something like a dump, but if the Redis server is running it is not guaranteed to be in a consistent state. So better make a dump yourself.

The Postfix queue may hold messages that couldn‘t yet be delivered, e.g. because the remote server is unreachable. If you back it up and restore, some messages may be delivered twice. If you don’t back it up, some messages may silently be never delivered. The latter is much worse, so I recommend backing it up.

**Comment by markirb** [comment]
About redis:
Logs show that redis dumps the db after 100 changes in 300 seconds.
According to [redis faq](https://redis.io/topics/faq) this is atomic.
Depending on your server load you might get an "outdated" backup which is different from current memory state.
Mine is written every 5 minutes...
But of course you could do a dump similar to SQL.

Postfix: Sure delivered twice is better than never....

**Comment by mkuron** [comment]
There is now a backup script in master, so this solution (which was incomplete anyway) is no longer needed.
