### ISSUE TITLE
after clean install cant access MariaDB

### ISSUE THREAD

**Issue by wheelix** [mailcow/mailcow-dockerized#763]
coming from mc 0.12 and 0.13 I just Installed mc-dockerized on a completely new system. Everything went well, i added domains and mailboxes as i know it and appreciated the new features!
I tried to log into SOGo and it went blank after welcoming me. (The DOM tells me its not just a white overlay) so i looked into the log files and here are notable excerpts:
Postfix:
_info_  `[...]   Internal error occurred. Refer to server log for more information. (in reply to RCPT TO command))`
Dovecot:
_err_  `managesieve-login: Error: Timeout waiting for handshake from auth server. my pid=42, input bytes=0`
_err_  `auth: Fatal: sql /usr/local/etc/dovecot/sql/dovecot-dict-sql-passdb.conf: Can't open configuration file /usr/local/etc/dovecot/sql/dovecot-dict-sql-passdb.conf: No such file or directory`
_err_  `master: Error: service(auth): command startup failed, throttling for 60 secs`
SOGo:
it began with
_info_  `[9]: [WARN] <0x0x55f4f3f00630[WOWatchDogChild]> pid 45 has been hanging in the same request for 7 minutes`
but suddenly it takes up 273 MB and spawned 20 children who notified some watchdog that they are ready :(

so.. i thought about looking into the syslog and there i found something strange popping up like every 20 sec: (i shortened it so it matched the ones above)
_warning_  `containerd: unable to save 17e90af56....... starttime: open /proc/23909/stat: no such file or directory`
_info_  `containerd: 17e90af56....... (pid 23909) has become an orphan, killing it`

The 17... container is **MariaDB** so something has to be wrong there but i have no clue at all where to start.

Thank you for helping me out, i hope my logs are not too detailed nor missing essential pieces of information.

**Comment by andryyy** [comment]
Hi, is this an OpenVZ/LXC/whatever-container machine?

**Comment by wheelix** [comment]
@andryyy I don't know what openVZ LXC is. My machine is a docker supporting vps on Ubuntu..

**Comment by K2rool** [comment]
@andryyy is only trying to find out what virtualization your vps is using as some container based one can have issues with running docker.

If you have no idea what the vps is running on, if you post the vps provider we might be able to tell you what virtualization they use.

**Comment by wheelix** [comment]
Ovh.. they did not answer on my request on Twitter yet.

**Comment by wheelix** [comment]
Kvm Openstack If I'm not mistaken
