### ISSUE TITLE
How are you guys dealing with spam reports?

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#764]
Hey everyone.
Today I started getting spam-reports from staff@hotmail.com saying that people try to send mails that don't pass my SPF check.

What are you doing with such mails? Ignore them? Filter them to the bin? Filter them to a specific folder?

**Comment by mkuron** [comment]
Do you by chance have a `ruf=` in your DMARC DNS record? If that is present, then you are asking receiving mail servers to inform you about all messages that fail DMARC.

If you don’t have that, it wouldn’t make much sense for Hotmail to send these messages (they would in fact be considered spam/backscatter). Forged sender domains are quite common and the real owner of the domain can do nothing about it.

**Comment by Braintelligence** [comment]
@mkuron Duh, I totally forgot about that. Yes I have a `ruf=` in that record. Currently it is going to an alias that is being redirected to my personal account.
Do you use this, as well? Maybe I should use a dedicated mail address for this.

**Comment by luxflux** [comment]
You may want to check https://dmarc.postmarkapp.com for an automated analysis of these mails...

**Comment by Braintelligence** [comment]
This looks interesting. Is there an open-source app that could deal with this, as well?

**Comment by luxflux** [comment]
Uh, I don’t know of any (but I didn’t search for it)... would be a nice addition to mailcow, though :)

**Comment by Braintelligence** [comment]
@luxflux Yeah, that's why I'm mentioning it 😸. By simply processing such mails and turning them into database-content which in turn is converted into human-readable-format would save a lot of space and be a great tool for monitoring.

**Comment by jpbaril** [comment]
https://github.com/techsneeze/dmarcts-report-parser
https://github.com/techsneeze/dmarcts-report-viewer
