### ISSUE TITLE
apache2 proxypass looking strange

### ISSUE THREAD

**Issue by MrYoshii** [mailcow/mailcow-dockerized#768]
Hi i have addet `ProxyPass "/mail" "http://darkside-gaming.at:8080/SOGo/so/" connectiontimeout=5 timeout=30 keepalive=on
        ProxyPassReverse "/mail "http://darkside-gaming.at:8080/SOGo/so/"
` to my sites-available but it looks like ...... :D 
i hope someone can help me
www.darkside-gaming.at/mail

**Comment by TiiFuchs** [comment]
The problem with that is that /SOGo/ uses resources (css, js) from /SOGo.woa/...
So if you do ProxyPass ... /SOGo/ then it is unable to get resources from /SOGo.woa/

I had the struggle a few days back myself but didn't find a perfect solution as of today.

What you can do is 

    ProxyPass /mail/ http://darkside-gaming.at:8080/
    ProxyPassReverse /mail/ http://darkside-gaming.at:8080/
    RewriteEngine on
    RewriteCond %{REQUEST_URI} !^/mail/SOGo
    RewriteRule ^(.*?)/? /mail/SOGo/$1 [R=301]

So if you access /mail you will be redirected to /mail/SOGo and the reverse proxy does everything as expected.

I had a similar config for me in use before, but this is from memory, so you may have to adjust a few things to get this to work...

Remember that you can use ProxyPass /mail/ http://127.0.0.1:8080/ if the container is on the same server as that apache server.
