### ISSUE TITLE
DNS records?

### ISSUE THREAD

**Issue by thomasb9511** [mailcow/mailcow-dockerized#77]
What DNS records should be set up to ensure best functionality?

**Comment by PhoenixPeca** [comment]
Hi,
it's more or less similar to the standardized version of mailcow.

The fundamental parts are the:
* MX Record
* TXT  Record for DKIM
* TXT  Record for SPF
* TXT  Record for DMARC
* A/AAAA Record for the mailcow UI
* A/AAAA Record for the autodiscover
* A/AAAA Record for the autoconfig

**Comment by thomasb9511** [comment]
I.E?


mail                IN A       1.2.3.4
dav                 IN A       1.2.3.4
autodiscover        IN A       1.2.3.4
autoconfig          IN A       1.2.3.4

@                   IN MX 10   mail

_imap._tcp          IN SRV     0 1 143 mail.example.org.
_imaps._tcp         IN SRV     0 1 993 mail.example.org.
_pop3._tcp          IN SRV     0 1 110 mail.example.org.
_pop3s._tcp         IN SRV     0 1 995 mail.example.org.
_submission._tcp    IN SRV     0 1 587 mail.example.org.
_caldavs._tcp       IN SRV     0 1 443 dav.example.org.
_carddavs._tcp      IN SRV     0 1 443 dav.example.org.
_autodiscover._tcp  IN SRV     0 1 443 autodiscover.example.org.

@                   IN TXT     "v=spf1 mx -all"
default._domainkey  IN TXT     "v=DKIM1; k=rsa; t=s; s=email; p=..."
; _dmarc            IN TXT     "v=DMARC1; p=reject; rua=mailto:mailauth-reports@example.org"

**Comment by sfnke** [comment]
All those SRV records are not necessary but optional, since Mailcow provides the configuration for IMAP/SMTP and other stuff within its `autoconfig.*` and `autodiscover.*` domain.

The other records seem to be correct and necessary.

**Comment by broedli** [comment]
Please check the guide in [our documentation](https://mailcow.github.io/mailcow-dockerized-docs/) and try to improve it if necessary. Every PR is welcome!

I'm closing this issue for now. Please feel free to open a new Issue in the repository of our documentation if needed.
