### ISSUE TITLE
What is nextcloud.sh

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#774]
Hi guys,

what is the nextcloud.sh script.
When I run the script is it without function

Kind regards
jm3west

**Comment by Braintelligence** [comment]
Did you read the commit message of that file?

**Comment by jm3west** [comment]
Oh yes, but how are the parameters and where can I read wich parameters gives it

**Comment by Braintelligence** [comment]
Wait, did you actually **read** the commit message of that file? It is a **work in progress**. It maybe doesn't work at all and is not supposed to currently.

**Comment by Braintelligence** [comment]
![grafik](https://user-images.githubusercontent.com/6761196/33213278-359e7e30-d127-11e7-9b78-053003aaaead.png)
I hope you **do** know what a commit message is.

**Comment by jm3west** [comment]
Oh sorry sorry sorry,

I just read the script message on terminal

Ashes over my head
