### ISSUE TITLE
Problem with Sieve scripts after update to current master

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#777]
Hello,

I updater Mailcow earlier this week and I just noticed that all my inbound mails are massively delayed.

I checked the logs and noticed this:
Temporarily unable to access necessary Sieve scripts (in reply to end of DATA command))

for each email I receive.

Any clue where I should look?

Cheers!

**Comment by lindeto** [comment]
Hello, 

I had the same problem, nothing went to update anymore. Even after a docker compose down followed by an up -d, no change.

After I accidentally opened the backend in the browser came the message: database initialization complete and then everything worked fine again.
