### ISSUE TITLE
MX Entry from foreign Host not resolved

### ISSUE THREAD

**Issue by brunick** [mailcow/mailcow-dockerized#78]
Hi, I've tried sending a mail, which came back as followed:

> mx postfix/smtp[108]: CF6F54EA: to=<info@brainfarmcinema.com>, relay=none, delay=1292, delays=1289/0.1/3/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=brainfarmcinema.com type=MX: Host not found, try again)

The host can easily resolve the domain, but the postfix container cannot, probably through the pdns service. 
Dig from Host:
>  dig mx brainfarmcinema.com
> ;; ANSWER SECTION:
> brainfarmcinema.com.    84849   IN      MX      5 ALT2.ASPMX.L.GOOGLE.com.
> brainfarmcinema.com.    84849   IN      MX      10 ALT3.ASPMX.L.GOOGLE.com.

Dig from PDNS-docker:

> dig mx brainfarmcinema.com  @172.22.1.254
> 
> ; <<>> DiG 9.10.3-P4-Ubuntu <<>> mx brainfarmcinema.com @172.22.1.254
> ;brainfarmcinema.com.           IN      MX

Can you guys help me get this fixed?

(shortened the dig parts)

**Comment by ghost** [comment]
@andryyy 

Can you add BIND9 to master? please )

**Comment by marrco** [comment]
i never had a single issue with pdns-resolver, and i run two instances of it for my mail servers for many years. And it's lighter on resource and imho a better choice than bind as a recursive dns.

**Comment by brunick** [comment]
well, there is an issue and i've been running this system for about 3 days. i guess this can be solved with pdns as well but this is an issue which i'm running into when sending to google app suite domains.
i'm not sure how pdns resolves its entrys, but it seems like a config-problem.

**Comment by andryyy** [comment]
Switched to Bind9 after all.
