### ISSUE TITLE
Activesync Hangs on large mailboxes in Outlook 2013/2016

### ISSUE THREAD

**Issue by reinistihovs** [mailcow/mailcow-dockerized#783]
Hi,
Im having trouble with Avtivesync and large mailboxes, Outlook says: WAITING FOR SERVER RESPONSE. ; Syncronizing Inbox, but no new mails arrive, outlook was open for several hours.

Any one with the same problem? Any fixes?

**Comment by Alireza2n** [comment]
Here are a few suggestions:
- Have you tired upgrading to latest release of mailcow? (via ./update.sh)
- What does your SoGO log say?

**Comment by reinistihovs** [comment]
1)
I have the latest version, that was the first probable fix, but no luck.
*tried rebooting host
*tried reseting activesync device cache
2)
Didnt collect any logs, as i remember there were no errors, but maybe im wrong.

And how i fixed it:
Found this- https://forum.iredmail.org/topic10785-iredmail-support-sogo-problem-with-activesync-outlook-2016.html
i changed some variables in sogo.conf   to
SOGoMaximumSyncWindowSize = 100;
SOGoMaximumSyncResponseSize = 2048;

after that i reset activesync cache for the particular user, and everything went well.

**Comment by andryyy** [comment]
These settings are not good for most Android clients. You should at least try not to use SOGoMaximumSyncWindowSize 100

**Comment by Alireza2n** [comment]
What sort of problems do these parameters cause?

________________________________

**Comment by mkuron** [comment]
@andryyy, is there any set of parameters that work for both Outlook and Android? If not, that's a SOGo bug.

**Comment by Braintelligence** [comment]
I thought ActiveSync was discouraged, since CalDavSynchronizer exists for Outlook?

**Comment by mkuron** [comment]
You can use either one. EAS is supported natively by Outlook, but doesn't appear to work with SOGo without problems. CalDav Synchronizer is a plugin with its own set of problems, but the CalDAV support in SOGo is relatively stable.
