### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by phipag** [mailcow/mailcow-dockerized#787]
Hello, in my postfix logs i see for some recipients the following error:
`warning: TLS library problem: error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:../ssl/record/rec_layer_s3.c:1399:SSL alert number 50:`
This results in a TLS Handshake error and the mail cannot be sent. For TLSv1.2 it works perfectly. Any suggestions?

**Comment by develth** [comment]
Same here, did you solved it?

**Comment by andryyy** [comment]
Some senders seem to use a SSLv3 encryption, you could remove !SSLv3 from `smtpd_tls_mandatory_protocols` and/or `smtpd_tls_protocols`-
