### ISSUE TITLE
docker-compose pull error

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#79]
Hi,
I want to update my Docker images.

After docker-compose pull I get the following error message:

`Feb 28 18:46:59 example dockerd[545]: time="2017-02-28T18:46:59.326883465+01:00" level=error msg="Not continuing with pull after error: manifest unknown: manifest unknown"
Feb 28 18:46:59 example dockerd[545]: time="2017-02-28T18:46:59.327114925+01:00" level=error msg="Handler for POST /v1.24/images/create returned error: manifest unknown: manifest unknown"
Feb 28 18:49:42 example dockerd[545]: time="2017-02-28T18:49:42.837110254+01:00" level=error msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
Feb 28 18:49:42 example dockerd[545]: time="2017-02-28T18:49:42.837289553+01:00" level=info msg="Translating \"manifest unknown: manifest unknown\" to \"manifest for mariadb:10.1 not found\""
Feb 28 18:49:42 example dockerd[545]: time="2017-02-28T18:49:42.837355184+01:00" level=error msg="Handler for POST /v1.24/images/create returned error: manifest for mariadb:10.1 not found"`

Maybe you can help me?

Thanks!

**Comment by broedli** [comment]
seems to me that docker is having temp. problems.

http://status.docker.com/

**Comment by mlzummo** [comment]
@broedli 
ERROR: manifest for memcached:latest not found can this be the same error?

**Comment by mzummo** [comment]
can confirm docker is having some on/off issues right now

**Comment by andryyy** [comment]
Yep, AWS has a huge outtake right now.

**Comment by rebek86** [comment]
Now it's working! Thank you! :-)
