### ISSUE TITLE
SSL Problem LetsEncrypt - No registration exists matching provided key

### ISSUE THREAD

**Issue by matias-casal** [mailcow/mailcow-dockerized#790]
Hi, in my MailCow instance everything works fine until my certificate expires, (auto renewal don't work).

This is what i get when i run

`docker-compose up acme-mailcow`

> acme-client: adding SAN: midomain.com
> acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/directory: directories
> acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 172.229.221.121
> acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1400:d:38e::3d5
> acme-mailcow_1       | acme-client: acme-v01.api.letsencrypt.org: DNS: 2600:1400:d:380::3d5
> acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: req-auth: autoconfig.bootweb.com.ar
> acme-mailcow_1       | acme-client: https://acme-v01.api.letsencrypt.org/acme/new-authz: bad HTTP: 403
> acme-mailcow_1       | acme-client: transfer buffer: [{ "type": "urn:acme:error:unauthorized", "detail": "No registration exists matching provided key", "status": 403 }] (120 bytes)
> acme-mailcow_1       | acme-client: bad exit: netproc(72): 1
> acme-mailcow_1       | Verified hashes.
> mailcowdockerized_acme-mailcow_1 exited with code 1

I try deletting /data/assets/ssl but that dont work

The SSL generated is:

> Common name: mail.example.org
> Organization: mailcow
> Valid from December 13, 2016 to November 28, 2019
> Serial Number: 7893282ffdddc61c614fd130b914cbfc
> Signature Algorithm: sha256WithRSAEncryption
> Issuer: mailcow

**Comment by matias-casal** [comment]
When i delete de assets/ssl the error change to this:

> acme-client: https://acme-v01.api.letsencrypt.org/acme/new-reg: bad HTTP: 400
>  acme-client: transfer buffer: [{ "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]", "status": 400 }] (267 bytes)
> acme-client: bad exit: netproc(78): 1

**Comment by matias-casal** [comment]
So, the problem was that the Dockerfile (data/Dockerfiles/acme/Dockerfile) does not update (i dont know why) so i make a manual update, delete the assets/ssl, rebuild the acme-mailcow image, run, and all good.

**Comment by SinoBoeckmann** [comment]
I've had the same issue like @Casy ... after doing the Update via ./update.sh the docker images of docker/acme was still 1.5 and (at this moment of writing) 10 months old and the Dockerfile was not updates.

So after removing the image, building it with the same name and docker-compose up the newly created image was used and everything is working fine.

Progress of git update looked fine so far - no error.

The only Problem i encouter so far is:
`/srv/docker-entrypoint.sh: line 15: redis-cli: command not found`
(But I consider to create a new issue for this)
