### ISSUE TITLE
[SOGo] Digital signature is not valid

### ISSUE THREAD

**Issue by tioover** [mailcow/mailcow-dockerized#792]
<img width="632" alt="2017-12-01 13 33 20" src="https://user-images.githubusercontent.com/930060/33469183-3af9aa1a-d69c-11e7-92e0-5a9b06e9b32e.png">
This email PGP signature has been valid, but SOGo show this warning.

I searched this [Re: [SOGo] Validating smime signature failes](https://lists.inverse.ca/sogo/arc/users/2013-07/msg00057.html)

Is this an issue? I'm not certainly.

**Comment by mkuron** [comment]
If anything, it's a SOGo bug that we can't fix ourselves. If the email is standard-compliant and the signature is valid, you can open a bug with SOGo's developers.

**Comment by andryyy** [comment]
I'm not sure, but it could be fixed in the new SOGo image.

**Comment by smileBeda** [comment]
This is not fixed - still happening in 2025 (not a MailCow issue, of course, just in case someone comes here to see this)

Unfortunately SOGO has no issues open in GitHub 
@mkuron - do you know where this can be reported to SOGO?

Thanks!
