### ISSUE TITLE
log postfix and dovecot to host syslog

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#793]
Hi there, is it possible to send logs from the postfix and dovecot contqiner to hosts' rsyslog?
Can you please share an example config? i am new to docker
Thanks

**Comment by Braintelligence** [comment]
The documentation has a chapter on how to setup logging. Please read the docs...

**Comment by lucianlazar1983** [comment]
It is not working:
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "logging". Valid top-level sections for this Compose file are: services, version, networks, volumes, and extensions starting with "x-".

**Comment by Braintelligence** [comment]
The error should tell you, that you placed logging too high in the topology of your yml file. You should look at other examples of docker-compose with a logging block...

**Comment by lucianlazar1983** [comment]
based on the Mailcow documentation:

> Edit docker-compose.yml and append, for example, this block to use the "gelf" logging plugin:


logging:
  log_driver: "gelf"
  options:
    gelf-address: "udp://graylog:12201"
    gelf-tag: "mailcow-logs"


So, i have appended that block as stated in the documentation with the difference that my driver is syslog.

**Comment by lucianlazar1983** [comment]
So, basd on that, i have put this block:


networks:
  mailcow-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

volumes:
  vmail-vol-1:
  mysql-vol-1:
  dkim-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:




logging:
  log_driver: "syslog"

**Comment by Braintelligence** [comment]
Again, the error should have told you that you should try a deeper level of topology. You picked the first level, which is wrong. 

https://docs.docker.com/compose/compose-file/compose-file-v2/#logging

**Comment by Braintelligence** [comment]
@andryyy Perhaps the docs should be extended by an example of a service with logging and also a mention that logging is an optional part of a service and seemingly not of the whole docker-compose.yml?

**Comment by lucianlazar1983** [comment]
Understood now, basically the block logging:
  driver: syslog must be placed inside each service and must pay attention to ident spaces for that.
Thank you again

**Comment by andryyy** [comment]
You can also configure Docker to always use syslog. They have some nice docs for this. 😊

**Comment by pra838** [comment]
> based on the Mailcow documentation:
> 
> > Edit docker-compose.yml and append, for example, this block to use the "gelf" logging plugin:
> 
> logging: log_driver: "gelf" options: gelf-address: "udp://graylog:12201" gelf-tag: "mailcow-logs"
> 
> So, i have appended that block as stated in the documentation with the difference that my driver is syslog.

It's working and can send to ELK stack.But not all maillogs (not emails delivery logs).


This is my docker-compose.yml 

` logging:
         driver: gelf
         options:
          gelf-address: "udp://172.20.111.199:12201"
          tag: "postfix"`

Below is my ELK stack received logs from above mentioned setup.

`@timestamp:Jul 29, 2024 @ 18:48:19.318 @version:1 command:/docker-entrypoint.sh /bin/sh -c exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf container_id:3cd0ce65fcaaffba82f88259028effcbb606e68e2fa864d33600dd472c6a1667 container_name:mailcowdockerized-postfix-mailcow-1 created:Jul 21, 2024 @ 14:07:06.255 host:mail.mailcow-devops.example.com`
