### ISSUE TITLE
Allow to choose ssl certs file names

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized#796]
Hello,

I would like to be able to point the containers to my letsencrypt certificate folders rather than /data/assets/ssl (in the docker-compose.yaml) so that I don't have to copy them by hand. (I can't understand how the ACME container is supposed to work in my case).

For this to work, it would be necessary to be able to choose the name of the files. Would this be possible to implement?

**Comment by andryyy** [comment]
Hi, no, sorry. You just need to link them there. It already is as easy as possible.
