### ISSUE TITLE
rspamd  : missing map file

### ISSUE THREAD

**Issue by Bitti09** [mailcow/mailcow-dockerized#8]
getting the following error in rspamd (normal mail functions are working as expected):

'rspamd-mailcow_1     | 2016-12-31 13:04:37 #8(normal) <35rhob>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/mid.inc
rspamd-mailcow_1     | 2016-12-31 13:04:37 #8(normal) <35rhob>; map; read_map_file: map file is unavailable for reading'

is this missing file required or  optional for rspamd ?

**Comment by andryyy** [comment]
Hi, 
can be ignored. You do not need it. :-)

**Comment by discofris** [comment]
https://github.com/vstakhov/rspamd/issues/1474
