### ISSUE TITLE
Can send but could not receive from any services

### ISSUE THREAD

**Issue by pavinthan** [mailcow/mailcow-dockerized#802]
Can send but could not receive from any services

Server Amazon EC2 Ubuntu 16.04 ```t2.small```
Domain jeylabs.xyz Hosted by Amazon Route 53

Route 53 and EC2 Inbound Rules Set Here 

<img width="772" alt="screen shot 2017-12-06 at 2 45 24 pm" src="https://user-images.githubusercontent.com/13897936/33654429-1d3b58c2-da96-11e7-8499-930caa27dd69.png">
<img width="1167" alt="screen shot 2017-12-06 at 2 53 21 pm" src="https://user-images.githubusercontent.com/13897936/33654431-1d75036a-da96-11e7-88cb-a832efb5a106.png">

**Comment by stevesbrain** [comment]
Looks like your MX record isn't set up correctly:

```bash
:: [steve@brain] ~
$ dig mx jeylabs.xyz

; <<>> DiG 9.11.2 <<>> mx jeylabs.xyz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43269
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jeylabs.xyz.                   IN      MX

;; ANSWER SECTION:
jeylabs.xyz.            287     IN      MX      25 mail.

;; Query time: 2 msec
;; SERVER: 10.10.10.254#53(10.10.10.254)
;; WHEN: Wed Dec 06 20:51:42 ACDT 2017
;; MSG SIZE  rcvd: 49

```

**Comment by pavinthan** [comment]
@stevesbrain Please check again, I just change it for test now it's rollback as in preview image and may I know how I config mx recode in Route 53

**Comment by stevesbrain** [comment]
Your MX record looks better now:

```bash
$ dig mx jeylabs.xyz

; <<>> DiG 9.11.2 <<>> mx jeylabs.xyz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62851
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1

;; QUESTION SECTION:
;jeylabs.xyz.                   IN      MX

;; ANSWER SECTION:
jeylabs.xyz.            300     IN      MX      25 mail.jeylabs.xyz.

;; AUTHORITY SECTION:
jeylabs.xyz.            172748  IN      NS      ns-410.awsdns-51.com.
jeylabs.xyz.            172748  IN      NS      ns-845.awsdns-41.net.
jeylabs.xyz.            172748  IN      NS      ns-1311.awsdns-35.org.
jeylabs.xyz.            172748  IN      NS      ns-1981.awsdns-55.co.uk.

;; ADDITIONAL SECTION:
mail.jeylabs.xyz.       40      IN      A       52.62.185.244

;; Query time: 191 msec
;; SERVER: 10.10.10.254#53(10.10.10.254)
;; WHEN: Wed Dec 06 20:57:03 ACDT 2017
;; MSG SIZE  rcvd: 206

```

You MX records are correct now! Everything else looks correct - only thing I'd do is change the reverse DNS of your IP to match. Do you have an email you want me to test sending to?

**Comment by pavinthan** [comment]
@stevesbrain Yes, admin@jeylabs.xyz 

Here is my delivery failed notice of Gmail

```
This is the mail system at host ip-172-31-29-9.ap-southeast-2.compute.internal.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<admin@jeylabs.xyz>: mail for jeylabs.xyz loops back to myself

Final-Recipient: rfc822; admin@jeylabs.xyz
Original-Recipient: rfc822;admin@jeylabs.xyz
Action: failed
Status: 5.4.6
Diagnostic-Code: X-Postfix; mail for jeylabs.xyz loops back to myself


---------- Forwarded message ----------
From: Pavinthan <ipavinthan@gmail.com>
To: admin@jeylabs.xyz
Cc: 
Bcc: 
Date: Wed, 6 Dec 2017 14:48:27 +0530
Subject: Can send but could not receive from any services
Can send but could not receive from any services
```

**Comment by stevesbrain** [comment]
I have sent a test email now - let me know if it arrives!

**Comment by stevesbrain** [comment]
Looks like it is a config issue - it bounced back saying:

``` The mail system <admin@jeylabs.xyz>: mail for jeylabs.xyz loops back to meyself>```

How did you set this up?

**Comment by pavinthan** [comment]
@stevesbrain, I just do ```sudo ./install.sh``` what I want to do to fix the issue?, may you please help me to fix it?

**Comment by stevesbrain** [comment]
@pavinthan I am happy to have a look at the system remotely, if you would like me to. Otherwise, I would be wondering if the admin user is forwarding to itself, possibly?

**Comment by pavinthan** [comment]
@stevesbrain Yes, may you please send me your email I can mail my Teamviewer credential.

**Comment by pavinthan** [comment]
Thanks @stevesbrain, Thank you for your help, 
I've deselect ```Backup MX options:``` and It's working fine now

**Comment by stevesbrain** [comment]
Oh excellent, glad to hear it @pavinthan :)

**Comment by pavinthan** [comment]
@stevesbrain with you it possible, Thanks @stevesbrain, Thank you very much.

**Comment by stevesbrain** [comment]
You are most welcome! :)
