### ISSUE TITLE
https://mailcow.github.io/mailcow-dockerized-docs/firststeps-relayhost/

### ISSUE THREAD

**Issue by copenhaus** [mailcow/mailcow-dockerized#803]
I can see the page was changed on about Sept 12, but the instruction doesn't help newbies like me....

https://mailcow.github.io/mailcow-dockerized-docs/firststeps-relayhost/

**Comment by stevesbrain** [comment]
I'll have a look at setting up a test relay (haven't done so yet) and make a PR if I successfully do so :)

Edit: I've set it all up, by if it's an authenticated relay, it will only deliver to the box it's authenticating as (even if it's whitelisted). Unauthenticated + whitelisted is accepted by the relaying postfix, but just seems to disappear into the aether :/ Will require some more investigating
