### ISSUE TITLE
EAS for Web-Calendar

### ISSUE THREAD

**Issue by alexanderrieder** [mailcow/mailcow-dockerized#805]
Hey Guys :)
I've got a question: is it possible to sync Web-Calendar (added in SoGo via .ics link) to EAS? Would be awesome :)

Greetings,

Alex

EDIT: I found a "Workaround": create a dummy user and add the calendar on the dummy user account. Now on you real account subscribe the calender via dummy user....  But for sure not the prettiest solution

**Comment by mkuron** [comment]
It doesn’t work via CalDAV either. That‘s a SOGo issue that we can’t fix. You could check their bugtracker though and report it if it hasn’t been reported yet.
