### ISSUE TITLE
Incorrect timezone in all containers

### ISSUE THREAD

**Issue by Alireza2n** [mailcow/mailcow-dockerized#806]
Hi,
Looks like the timezone in host does not get reflected in any of the containers.
This will cause logs with incorrect time display.

Great thanks for the awesome project btw. 👍

**Comment by andryyy** [comment]
Logging is in UTC. :-) We can add the TZ var to the environment for all containers. That should apply the corrrect TZ automatically.

**Comment by Alireza2n** [comment]
Ok, sure, I'll try to make changes and make a pull request. :)
