### ISSUE TITLE
Docker Container Probleme

### ISSUE THREAD

**Issue by axiades** [mailcow/mailcow-dockerized#807]
Hallo,

Ich hoffe mir kann jemand helfen,
Ich habe dass problem dass mein server alle 2 Tage Neugestartet werden muss wegen einem Spiel Welches auf diesem Läuft.

Jetzt will ich aber nicht jedes mal den Container per Hand neu starten.. Währe es irgendwie möglich dass dies Automatisiert passiert ?

Liebe Grüße

**Comment by andryyy** [comment]
Habe dir gerade mal gemailt. 👍
