### ISSUE TITLE
Fail2Ban Block

### ISSUE THREAD

**Issue by kalosa** [mailcow/mailcow-dockerized#808]
Hello,

Fail2ban is blocking users ip on the server, added as exclusion in admin dashboard but no luck. Should i whitelist only the IP or the 123.123.123.0/24?

**Comment by andryyy** [comment]
You can use both formats. It only saves valid values. :-)

**Comment by kalosa** [comment]
Great thank you

**Comment by kalosa** [comment]
I've added only the IP and still cannot establish connection via outlook, and neither the Webmail SOGo address working

**Comment by kalosa** [comment]
i've opened a remote session with teamviewer and the pc cannot ping the server, request time out even with the IP whitelisted, is there any other way to by pass it? In server logs does not show any activity from that ip at this time

**Comment by mkuron** [comment]
Obviously your IP is still banned. That should be cleared after the 30-minute timeout. Adding an address to the whitelist does not immediately clear the ban, it only prevents it from being banned in the future.

When you restart the fail2ban container, all bans should be cleared immediately — though this sometimes doesn’t work, in which case the bans persist indefinitely until you clear them manually with the `iptables` command or reboot the host. That‘s what I recommend for now: just reboot the host.

**Comment by kalosa** [comment]
I did a restart of the host and now the interface is not working

**Comment by mkuron** [comment]
Did all the Docker containers come back up? Since you’re now able to connect to the server, this is a different peoblem.

**Comment by kalosa** [comment]
how to i check that?

**Comment by kalosa** [comment]
this is what you mean ?

ONTAINER ID        NAME                                    CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS                                                                         
84c4eeffb5a7        mailcowdockerized_unbound-mailcow_1     0.00%               9.25MiB / 13.7GiB    0.07%               486kB / 190kB       6.55MB / 12.3kB     1                                                                            
ab478a3db18e        mailcowdockerized_rspamd-mailcow_1      1.16%               109MiB / 13.7GiB     0.78%               372kB / 276kB       38.4MB / 2MB        9                                                                            
2cf2573049d1        mailcowdockerized_acme-mailcow_1        0.05%               408KiB / 13.7GiB     0.00%               27.2kB / 9.6kB      14.3MB / 0B         3                                                                            
fe92df0c03ad        mailcowdockerized_fail2ban-mailcow_1    0.02%               7.078MiB / 13.7GiB   0.05%               0B / 0B             10.2MB / 0B         3                                                                            
6ec496e45b4b        mailcowdockerized_php-fpm-mailcow_1     0.01%               10.94MiB / 13.7GiB   0.08%               24.8kB / 16.5kB     27MB / 0B           3                                                                            
9d602a458fd4        mailcowdockerized_dovecot-mailcow_1     0.03%               32.39MiB / 13.7GiB   0.23%               514kB / 1.07MB      44.5MB / 106kB      33                                                                           
1419bb44645e        mailcowdockerized_watchdog-mailcow_1    0.00%               336KiB / 13.7GiB     0.00%               19.4kB / 728B       2.45MB / 0B         4                                                                            
3f6145e6f24a        mailcowdockerized_postfix-mailcow_1     0.02%               20.1MiB / 13.7GiB    0.14%               130kB / 223kB       37.4MB / 135kB      14                                                                           
2f6eee4e226b        mailcowdockerized_memcached-mailcow_1   0.03%               768KiB / 13.7GiB     0.01%               15.7kB / 728B       1.29MB / 0B         10                                                                           
aa38ec028ac8        mailcowdockerized_redis-mailcow_1       0.15%               20.23MiB / 13.7GiB   0.14%               682kB / 378kB       6.94MB / 16.5MB     4                                                                            
17e1a4c1b1d8        mailcowdockerized_ipv6nat_1             0.60%               3.227MiB / 13.7GiB   0.02%               0B / 0B             6.19MB / 0B         11                                                                           
9a2b41d38dc5        mailcowdockerized_sogo-mailcow_1        0.19%               201.6MiB / 13.7GiB   1.44%               124kB / 136kB       72.8MB / 16.4kB     28                                                                           
5ca8c13f802c        mailcowdockerized_clamd-mailcow_1       0.00%               514.3MiB / 13.7GiB   3.67%               23.2kB / 3.08kB     251MB / 16.4kB      8                                                                            
1d8f8c04940f        mailcowdockerized_mysql-mailcow_1       0.08%               145.3MiB / 13.7GiB   1.04%               247kB / 210kB       52.2MB / 15.6MB

**Comment by kalosa** [comment]
Also SOGo is down cannot access via webmail, can you help me out to figure out what cause this issue?

**Comment by mkuron** [comment]
Ok, they‘re all up. Now you need to check the logs for the individual services (sogo, nginx, php-fpm) to find out why the web site isn‘t working. Before you do that, you can try recreating the containers (`docker-compose down; docker-compose up -d`, this does not delete your data) and see if that helps.

**Comment by kalosa** [comment]
it seems the port is in use for nginx

`reating mailcowdockerized_nginx-mailcow_1 ... error                                            

ERROR: for mailcowdockerized_nginx-mailcow_1  Cannot start service nginx-mailcow: driver failed programming external connectivity on endpoint mailcowdockerized_nginx-mailcow_1 (a3a2a0da937731582e203a15f92450b65eed78a9ce56b5843de504747d51438f): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use`

**Comment by andryyy** [comment]
What is blocking the port? Apache? Nginx? Try `netstat -tulpen` or `ss -tulpn`

**Comment by kalosa** [comment]
It seems after all apache was using 3 ports included the ones nginx use and that's why on restart web interface and SOGo were down but server fully operational. All good now i have to remove apache from starting , thank you all!
