### ISSUE TITLE
Specific user in SOGo only blank page - IMAP with external clients works

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#809]
When trying to access SOGo for a specific user I only get a blank page. No errors in browser console. Any ideas?

**Comment by Braintelligence** [comment]
When manually changing the URL while logged in as this user from the Mail sub-app to the Calendar sub-app I get the calendar properly. Switching to mail makes the page blank again.

**Comment by andryyy** [comment]
Probably some Dovecot error. Can you check Dovecot logs and maybe SOGo log when this happens?

**Comment by Braintelligence** [comment]
SOGo log from one login try:
![grafik](https://user-images.githubusercontent.com/6761196/33728842-11e211f0-db7c-11e7-82b4-45ed37ef9385.png)

And dovecot:
![grafik](https://user-images.githubusercontent.com/6761196/33728889-4756f85a-db7c-11e7-877e-e24d92bf65b7.png)

**Comment by Braintelligence** [comment]
@andryyy Whenever you find the time I'd appreciate your assistance in resolving this =(. Then I'd know what to look out for in the future 😸.

**Comment by andryyy** [comment]
No free time.
The logs look okay. You may try to run down and up -d just to exclude some temporary error.

**Comment by Braintelligence** [comment]
That was the first thing I did. I even ran an update.

**Comment by andryyy** [comment]
I would need some login details to check it.

**Comment by Braintelligence** [comment]
Could we use a TeamViewer session for this? ^^

**Comment by andryyy** [comment]
That slows everything down. :-/ Is it a productively used mail account? Private? Commercial?

**Comment by Braintelligence** [comment]
Yes it is. Also data privacy sensitive. I mean I know you won't do crap, so I could change the PW real quick to something else, so you could try it out. But would that help you without access to the server?

**Comment by andryyy** [comment]
Not sure, I just wanted to check some more browsers.
You can try to add more debugging via sogo.conf. Like `//ImapDebugEnabled` and ``//MySQL4DebugEnabled``.

**Comment by Braintelligence** [comment]
I've sent you a mail on servercow :)

**Comment by Braintelligence** [comment]
There are 28 pages of logs now concerning the moment of login T_T... I've looked through them but didn't find something obvious.

Just so you know: That guy has a crapton of IMAP (sub)folders. Could that be the issue?

**Comment by andryyy** [comment]
Fixed by SOGo (they remove NUL chars from JSON now).
