### ISSUE TITLE
howto: dockerized without sogo (roundcube only) ?

### ISSUE THREAD

**Issue by mzummo** [mailcow/mailcow-dockerized#81]
install mailcow-dockerized without sogo and use roundcube instead?

**Comment by broedli** [comment]
please read the wiki for the roundcube part: https://mailcow.email/dockerized/?c=IV.%20Usage%20and%20Examples&p=Install_Roundcube.md
for removing sogo please stop the container and remove it from [docker-compose.yml](https://github.com/andryyy/mailcow-dockerized/blob/master/docker-compose.yml#L100-L120).
