### ISSUE TITLE
Automatisiertes Backup

### ISSUE THREAD

**Issue by axiades** [mailcow/mailcow-dockerized#810]
Guten Abend,

Ich habe ein Kleines Problem beim Backup der Daten.

Ich versuche derzeit dass Folgende 2 Befehle 
Befehl Nr.1 `docker run --rm -i -v $(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/vmail" }}{{ .Name }}{{ end }}{{ end }}' $(docker-compose ps -q dovecot-mailcow)):/vmail -v ${PWD}:/backup debian:stretch-slim tar cvfz /backup/backup_vmail_$(date +%d.%m.%Y-%H:%M).tar.gz /vmail`
Befehl Nr.2 `docker-compose exec -T mysql-mailcow mysqldump --default-character-set=utf8mb4 -u${DBUSER} -p${DBPASS} ${DBNAME} > backup_${DBNAME}_$(date +%d.%m.%Y-%H:%M).sql`

Automatisiert alle 6H Ausgeführt werden.

Sprich 6:00 - 12:00 - 18:00 - 24:00 Uhr 

Hoffe mir Kann da jemand weiter helfen weil per crontab -e funktioniert es leider nicht..

**Comment by exii88** [comment]
Habe das gleiche Problem.
Bei mir werden immer nur 0KB - Dateien angelegt.
Wenn ich den Befehl manuell ausführe passt alles.

**Comment by cm2484** [comment]
Versucht es mal mit dem vollständigen Pfad der Programme:
/usr/bin/docker .....
/usr/local/bin/docker-compose ....

**Comment by exii88** [comment]
Hilft leider auch nicht. Gleiches Ergebnis mit den 0KB - Dateien.

[backup-mail.txt](https://github.com/mailcow/mailcow-dockerized/files/1545931/backup-mail.txt)
[backup-mysql.txt](https://github.com/mailcow/mailcow-dockerized/files/1545932/backup-mysql.txt)

Wenn ich die Skripte manuell ausführe funktionieren diese.

**Comment by mkuron** [comment]
`$PWD` zeigt vermutlich auf das home directory und `$DBUSER` usw. sind nicht gesetzt, weil man dazu `source mailcow.conf` machen muss. Am besten alles in ein Skript schreiben (dabei beachten, dass $PATH im Cron-Job evtl. anders ist als auf der Shell, also absolute Pfade für alle Befehle nehmen) und das per Cron ausführen.

**Comment by mkuron** [comment]
`which docker-compose` klappt womöglich nicht, weil im Cronjob der PATH anders sein kann als auf der Shell. Deswegen explizit den absoluten Pfad angeben.

**Comment by exii88** [comment]
Das war tatsächlich bei mir die Lösung. Mit festen Pfaden zu "docker" und "docker-compose" funtionieren die beiden Skripte.
