### ISSUE TITLE
Shared folders do not get subscribed

### ISSUE THREAD

**Issue by jgeusebroek** [mailcow/mailcow-dockerized#819]
Scenario:
Share a mailbox (folder) using the SoGo interface from user A to user B.

User B get's a mail that a new shared mailbox has been added, however it cannot 
be seen automatically by imap clients. I had to use thunderbird (since apple mail cannot see unsubscribed mailboxes) to subscribe to the mailbox; only then I can see the mailbox.

Seems like a bug to me? Any suggestions?

**Comment by andryyy** [comment]
Hi, You just need to restart the client or log out and back in. Click the icon next to "other users" in SOGo to expand the folder. 👍

**Comment by jgeusebroek** [comment]
Thanks, but that doesn't work. I just repeated it to be sure.
Apple Mail, Thunderbird and Apple IOS mail do not see the newly shared folder.

I need to manually subscribe using Thunderbird, only then I can see the newly shared mailbox / folder. See attached screenshot, 'test' is not subscribed.

<img width="971" alt="screen shot 2017-12-14 at 18 57 23" src="https://user-images.githubusercontent.com/203215/34007142-07fb4e4c-e101-11e7-89c8-173bf23b9da6.png">
