### ISSUE TITLE
Problem building sogo container

### ISSUE THREAD

**Issue by zero-one-devteam** [mailcow/mailcow-dockerized#82]
Hi,

the initial build of all containers worked well, however when trying to build the sogo container again with

docker build data/Dockerfiles/sogo -t andryyy/mailcow-dockerized:sogo

I get the following error:

Running hooks in /etc/ca-certificates/update.d...
done.
--2017-03-01 20:27:31--  https://github.com/tianon/gosu/releases/download/1.9/gosu-amd64
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name 'github.com'.
To connect to github.com insecurely, use `--no-check-certificate'.

Tried to delete sogo container, sogo image, docker pull andryyy/mailcow-dockerized:sogo, all without success.

Also tried the suggested option --no-check-certificate and as well using curl, but then I will get other errors. So I assume, anything has been currupted ... Any ideas?

**Comment by andryyy** [comment]
Hi, that's strange, just tried it and it worked fine. Can you confirm it today?

**Comment by zero-one-devteam** [comment]
Yes, same error today. I can't imagine any reason for this ...

**Comment by zero-one-devteam** [comment]
I already tried to download the gosu files, put them into my AWS S3 bucket and changed the links in the Dockerfile - no success. Seems that anything with SSL is corrupted there ... I replaced the files in data/assets/ssl with a Letsencypt certificate - but I think that should not have any impact. Anything else I can try except of starting from scratch?

**Comment by andryyy** [comment]
What errors do you get with --insecure or --no-check-certificate? (I think --insecure was the correct option for curl).

**Comment by zero-one-devteam** [comment]
Maybe I am having some trouble with iptables. I started docker with --iptables=false --userland-proxy=false. All Container are working except of sogo. Am I missing a masq rule? I have these two:

MASQUERADE  all  --  172.22.1.0/24        anywhere            
MASQUERADE  all  --  172.17.0.0/16        anywhere

**Comment by andryyy** [comment]
I'm not sure about masquerading when building the containers.

I will close this as issue, but you can let us know what you changed etc. to get it working after all. :-)

**Comment by zero-one-devteam** [comment]
I did not get it solved other than fetching the two github files manually and adding 
COPY gosu /usr/local/bin/gosu
COPY gosu.asc /usr/local/bin/gosu.asc
to SOGo's Dockerfile.

No problems at all except with the sogo container and fetching the github files ...

I guess it is my special configuration, not a mailcow problem. Thanks for supporting me here!
