### ISSUE TITLE
SMTP rarely reachable via scripts

### ISSUE THREAD

**Issue by Pitastic** [mailcow/mailcow-dockerized#821]
_(Maybe_ related to  #813 _but with more input...)_

### This works fine

Hey,
I followed the docs and it seems to be working fine via

 - SOGo (included webmailer in the same docker-compose)
 - local Thunderbird on my home machine

I can send and receive Emails to various domains (gmail, t-online, gmx etc.) and Thunderbird automatically finds it's settings - nice :sunglasses:  .

My goal is to have another docker-compose with a webservice (lamp) to send a newsletter with this email-server.

### Here is the problem

If I try to send a mail via script from the same or from another server e.g. PHPMailer the connection already timed out:

```
2017-12-13 17:44:13 Connection: opening to ssl://mx.mp-sol.de:465, timeout=300, options=array()
2017-12-13 17:46:13 Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://mx.mp-sol.de:465 (Operation now in progress) [/mnt/web108/e2/86/57913686/htdocs/pitastic/t/PHPMailer/src/SMTP.php line 313]
2017-12-13 17:46:13 SMTP ERROR: Failed to connect to server: Operation now in progress (150)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshootin
```

I tried the exposed ports 25 , 465 , 587 with ssl, tls or without encryption.

The logs say nothing - it seems that the script does not reach the container. But a DNS misconfiguration makes no sense as I can send and receive mails (look above).

Nevertheless, here is my DNS config:
```
*	A	1.2.3.4
www	CNAME	@
@	A	1.2.3.4
mx	A	1.2.3.4
autodiscover	CNAME	mx.mydomain.de
autoconfig	CNAME mx.mydomain.de
@	MX 10	mx.mydomain.de
@	TXT	v=spf1 mx mx:otherdomain.de ~all
```
And this is `iptables _L -n`:

```
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2406 ctstate NEW,ESTABLISHED
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443 ctstate NEW,ESTABLISHED

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate ESTABLISHED

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.3           tcp dpt:587
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.3           tcp dpt:465
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.3           tcp dpt:25
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:12345
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:4190
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:995
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:993
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:143
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.6           tcp dpt:110
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.251         tcp dpt:8443
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.251         tcp dpt:8005

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0 
```

And `iptables -t nat -L -n`:

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.22.1.0/24        0.0.0.0/0           
MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           
MASQUERADE  all  --  172.18.0.0/16        0.0.0.0/0           
MASQUERADE  tcp  --  172.18.0.2           172.18.0.2           tcp dpt:80
MASQUERADE  tcp  --  172.22.1.3           172.22.1.3           tcp dpt:587
MASQUERADE  tcp  --  172.22.1.3           172.22.1.3           tcp dpt:465
MASQUERADE  tcp  --  172.22.1.3           172.22.1.3           tcp dpt:25
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:12345
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:4190
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:995
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:993
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:143
MASQUERADE  tcp  --  172.22.1.6           172.22.1.6           tcp dpt:110
MASQUERADE  tcp  --  172.22.1.251         172.22.1.251         tcp dpt:8443
MASQUERADE  tcp  --  172.22.1.251         172.22.1.251         tcp dpt:8005

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.3:587
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.3:465
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.3:25
DNAT       tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.6:12345
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.6:4190
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.6:995
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.6:993
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.6:143
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.6:110
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8443 to:172.22.1.251:8443
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8005 to:172.22.1.251:8005
```

The `HTTP_PORT` is on `8005` for a reverse apache proxy. But I tried the config also without the proxy.

For now I have connected my other docker-compose to mailcows network (`with docker network connect mailcow_mailcow-network other_container`) and the PHPMailer works with the hostname `postfix` as the smtp server. But this is not a good solution for long.

So I have no clue how to track down the problem or where I can look for information on my system.

_btw nice service_ :+1:

**Comment by Ringelnatz** [comment]
The docker internal DNS resolving does not work for connections to the host (try this out by attaching to a docker container and start a DNS lookup for your host's hostname). I am using the "solution" you described currently as I couldn't find any real solution for this.

**Comment by Pitastic** [comment]
okey, thx !

I could live with the workaround for services on the same machine :confused:
But the access from another server to the mailcow-dockerized instance of the described server above also does not work.

Should it be still impossible to send mails from outside the same server ? Why does Thunderbrid work then ?

**Comment by Ringelnatz** [comment]
Well that actually doesn't make sense to me. Of course it should be possible to reach the SMTP server from external (and obviously is because Thunderbird works).
Again the problem should be related to docker's internal DNS resolving. You could try e.g. CURLing your mailcow admin UI from the server itself and from inside a docker container.

**Comment by Pitastic** [comment]
CURLing my mailcow UI (via `https`) from

- the host
- from another server
- ~~and from inside the `mailcow_postfix-mailcow_1` container~~

works well.
My mainproblem is about connections from another server (no docker, other ip/hoster)... the part that makes no sense :wink:

**Edit:** I've got a redirect from a domain (`mail.`) to the MX (`mx.`) by the apache server on the host ... and I tried the wrong domain... with the MX domain it does not work from within the container !

**Comment by Ringelnatz** [comment]
So you can CURL your MX from your "another server", but reaching SMTP on your MX from the same machine does not work? This is really strange ... could your "another server" has been banned by the fail2ban container included with mailcow?
I can definitely reach your SMTP server from a server of mine 😅 so it should not be an issue of the mailcow/firewall setup.

**Comment by Pitastic** [comment]
I've updated my comment :yum:
The Fail2Ban was an earlier problem which is solved... I tested the SMTP connection with telnet and the [testingscript from bjaerris](https://bjaerris.com/testing-destination-mailserver-with-telnet-netcat-and-bash-scripting-smtpesmtp/) ... and connection established (port 25) - mail sent !
Nevertheless, sending in Python or PHP is still **NOT** working.

**It seems that the resolving of the hostname is not possible.**

e.g. This simple [pymow](https://pymotw.com/2/smtplib/) script:
```
#!/usr/bin/python

import smtplib
import email.utils
from email.mime.text import MIMEText

# Create the message
msg = MIMEText('This is the body of the message.')
msg['To'] = email.utils.formataddr(('Recipient', 'me@mp-sol.de'))
msg['From'] = email.utils.formataddr(('Author', 'test@mp-sol.de'))
msg['Subject'] = 'Simple test message'

server = smtplib.SMTP('mail')
server.set_debuglevel(True) # show communication with the server
try:
	server.sendmail('test@mp-sol.de', ['me@mp-sol.de'], msg.as_string())
finally:
	server.quit()
```
stucks at this traceback:
```
  File "sendmail.py", line 13, in <module>
    server = smtplib.SMTP('mail')
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
```

**Comment by urhovaldeko** [comment]
Should you be using `server = smtplib.SMTP('mail.mp-sol.de')` (or whatever your servername is) there?

**Comment by Pitastic** [comment]
Sure...forgot that...
Now it seems that it is working from my home pc but not from my other server (strato hosting). It seems that the important ports are just blocked by strato (where I tried to connect to my other mailserver).

So unfortunately the conclusion is:

- it is a PHPMail or hoster problem (port blocking) at strato
- scripts are working (even if the python script's complaining about the missing authentification - but that's ok)
- a docker is not able to resolve a domain to the same docker host

Thanks for your help - I still learned a lot about docker and dns :) ...close this
