### ISSUE TITLE
Service 'rspamd-mailcow' failed to build

### ISSUE THREAD

**Issue by unilogica** [mailcow/mailcow-dockerized#822]
After ran docker-compose up, I'm getting this error:

> Get:42 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 gnupg-curl amd64 1.4.20-1ubuntu3.1 [18.1 kB]
> Fetched 6634 kB in 25s (255 kB/s)
> ## E: Failed to fetch http://179.184.208.141:80/data/045ad476984c9f37/archive.ubuntu.com/ubuntu/pool/main/libk/libksba/libksba8_1.3.3-1ubuntu0.16.04.1_amd64.deb  Writing more data than expected (14122 > 7998)
> 
> ## E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ERROR: Service 'rspamd-mailcow' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y 	ca-certificates 	gnupg2   gnupg-curl 	apt-transport-https 	&& apt-key adv --fetch-keys https://rspamd.com/apt/gpg.key 	&& echo "deb https://rspamd.com/apt/ xenial main" > /etc/apt/sources.list.d/rspamd.list 	&& apt-get update && apt-get install -y rspamd 	&& rm -rf /var/lib/apt/lists/* 	&& echo '.include $LOCAL_CONFDIR/local.d/rspamd.conf.local' > /etc/rspamd/rspamd.conf.local 	&& apt-get autoremove --purge 	&& apt-get clean 	&& mkdir -p /run/rspamd 	&& chown _rspamd:_rspamd /run/rspamd' returned a non-zero code: 100

This image is deprecated?

**Comment by andryyy** [comment]
I think you didn't run docker-compose pull as it is mentioned in the docs.

**Comment by unilogica** [comment]
Thanks for your feedback, that's true. 

I had clicked only in **"Please see the official documentation for instructions."** and seen the overview. As my 2 cents, I'm locking for an alternative to Zimbra, and after a lot of tests I came tired to mailcow in a long sequence of a couple of hours in each configuration in a ton of enviroments of another solutions.

Mailcow it's phenomenal! And it can save a cloupe of hours of unwared or tired users like me adding "**docker-compose pull**" requirement  in https://mailcow.github.io/mailcow-dockerized-docs/ sumary. 

And I will explain: as a docker-compose user, it's first time I see this requirement (It's usual only ran docker-compose up and wait automatic docker pull orchestration).
