### ISSUE TITLE
Broken port field js validation when creating sync job

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#823]
![screenshot-2017-12-16 mailcow ui](https://user-images.githubusercontent.com/3899107/34070262-4557cb22-e263-11e7-854a-4dac80e4d7f7.png)

When specifying custom port in this form, js validation fails. Default value 143 works. Issue occurs in Firefox and Chrome as well. When I delete `min="1"` and `max="65535"` html attributes in browser, it's possible to submit the form. It worked before, broken probably with https://github.com/mailcow/mailcow-dockerized/commit/60e97503f711ed776c68a8adaa0a5cd2c20fd1a0

**Comment by Daniel133** [comment]
+1

**Comment by heino-vdbh** [comment]
+1

**Comment by andryyy** [comment]
This is fixed in dev. :-) Will be merged very soon.
Please re-open if it still fails for some reason!
