### ISSUE TITLE
docker-compose pull fails

### ISSUE THREAD

**Issue by Oratorian** [mailcow/mailcow-dockerized#825]
See Logfile for error output
[Console-Log.txt](https://github.com/mailcow/mailcow-dockerized/files/1568014/Console-Log.txt)

**Comment by andryyy** [comment]
That’s expected: dev. 

You can still build the images yourself.

**Comment by Oratorian** [comment]
wow that was fast :D

Sorry i just tried to tidy the post up and attached the Console-outout instead.
