### ISSUE TITLE
Restarting Containers

### ISSUE THREAD

**Issue by Oratorian** [mailcow/mailcow-dockerized#826]
I am using the dev branch for some testing and the Containers TAB gives the ability to restart all
containers.

But it is not, It is simply just throwing Error: when i click the restart behind a container.
This also happens when trying to restart SoGo

Attached some screenshots
![screenshot-2017-12-18 nulledhosting mail-ui](https://user-images.githubusercontent.com/18353000/34111241-6eb201ac-e409-11e7-9e9d-58d487d30143.png)
![screenshot-2017-12-18 nulledhosting mail-ui 1](https://user-images.githubusercontent.com/18353000/34111246-6f420842-e409-11e7-8ef4-42d702b0fcaf.png)
![screenshot-2017-12-18 nulledhosting mail-ui 3](https://user-images.githubusercontent.com/18353000/34111293-9a53e47e-e409-11e7-9e77-46176d86a261.png)

**Comment by andryyy** [comment]
Probably an older dockerapi container. That’s dev. 

Mit besten Grüßen
André Peters

**Comment by Oratorian** [comment]
Does the actual master branch include the quarantine and the debugging Menu option?

Or any way to get around this olderapi thing?

**Comment by andryyy** [comment]
No it doesn’t. Try docker-compose build dockerapi-mailcow followed by up -d

Mit besten Grüßen
André Peters

**Comment by Oratorian** [comment]
I recompiled the dockerapi-mailcow

I attached then to the dockerapi to get the logs

> `Attaching to mailcowdockerized_dockerapi-mailcow_1
dockerapi-mailcow_1  | Exception in thread Thread-1:
dockerapi-mailcow_1  | Traceback (most recent call last):
dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
dockerapi-mailcow_1  |     self.run()
dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/threading.py", line 754, in run
dockerapi-mailcow_1  |     self.__target(*self.__args, **self.__kwargs)
dockerapi-mailcow_1  |   File "/server.py", line 113, in startFlaskAPI
dockerapi-mailcow_1  |     app.run(debug=False, host='0.0.0.0', port='8080', threaded=True)
dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 841, in run
dockerapi-mailcow_1  |     run_simple(host, port, self, **options)
dockerapi-mailcow_1  |   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 733, in run_simple
dockerapi-mailcow_1  |     raise TypeError('port must be an integer')
dockerapi-mailcow_1  | TypeError: port must be an integer
dockerapi-mailcow_1  |

**Comment by andryyy** [comment]
Make Port an integer. This is dev and not expected to work. Other stuff is likely not working, too. It is a branch you can work on and fix stuff.

**Comment by bkleiner** [comment]
It's maybe worth mentioning that the master branch showed the same problem for me starting with a fresh install.

**Comment by andryyy** [comment]
I guess that happened when you built the images yourself. The pushed images work fine in master.

**Comment by bkleiner** [comment]
Yep, you right, i just checked again, it only happens when you build yourself.
