### ISSUE TITLE
Change Port of mailcow UI

### ISSUE THREAD

**Issue by Grosslukass** [mailcow/mailcow-dockerized#828]
Hello,

I have a problem with changing the ports for the mailcow UI.
Is there a file where I can change it?
I just found this: https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-system/#default-ports
but I dont know where to put it and how to exactly change the ports.
I want to run my own website on apache on standard-port and the mailcow UI on another one.

Thanks.

**Comment by hachre** [comment]
You should be able to edit `mailcow.conf` and there's two variables there that are relevant:

```
HTTP_PORT=80
HTTPS_PORT=443
```

Aftwards you prolly have to run `docker-compose up -d` to apply this.

**Comment by jajalla23** [comment]
i cant seem to access mailcow outside of my server. any help?

**Comment by BaronBa3ba3** [comment]
> i cant seem to access mailcow outside of my server. any help?

Hey jaja, I know its been a while; but I have fallen into the same issue. Did you find what you did wrong?

edit : what WE did wrong

**Comment by jajalla23** [comment]
> > i cant seem to access mailcow outside of my server. any help?
> 
> 
> 
> Hey jaja, I know its been a while; but I have fallen into the same issue. Did you find what you did wrong?
> 
> 
> 
> edit : what WE did wrong

Sorry, I don't remember what I did. 

I believe it had something to do with port forwarding or the server blocking the port to external
