### ISSUE TITLE
Feature: Nginx as IMAP / SMTP / POP proxy TLS

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#829]
Hi,

please consider this a feature request.
Currently there is only one certificate that may have alt-names defined so it serves multiple domain names.
One problem is that no more than 100 alt names are possible, see:
https://letsencrypt.org/docs/rate-limits/

The other thing is that if one plans to run mailcow-dockerized as a customer mail system the certificate tells which domains it contains. That maybe be delicate considering privacy protection.

What I also don't like very much is that IPv6 uses NAT. One nice thing about IPv6 is that you won't need NAT any more.

Given the above reasons it might be a more elegant approach to use Nginx as a proxy for IMAP / SMTP and POP connections. That way it would be possible to operate multiple domain names all with their own certificate.

If you think this is bullshit, just close it, no problem. I just thought maybe this could improve the solution a bit.

**Comment by levinuss** [comment]
If you say "customer mail system" you have multiple completely different domains? If its only about subdomains LE wildcards upport could help. https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by imp1sh** [comment]
Yes it's about completely different domains from different customers.

**Comment by mkuron** [comment]
Nginx as a mail proxy would be elegant indeed. Fail2ban would need to be adapted to get auth failure reports with the correct source IP from nginx, but otherwise integration would be pretty simple.

It can’t be used on port 25 though because Postfix and rspamd need the real source IP for blacklisting, and there is no _X-Forwarded-For_ for SMTP.
Furthermore, Nginx can‘t proxy the Managesieve protocol, which we also need. 

So: good idea, but it doesn’t work in practice.

**Comment by imp1sh** [comment]
SMTP actually makes no sense to run through Nginx, didn't think too much about that.
Isn't it possible to let Nginx handle IMAP / POP while sieve stays as it is?

**Comment by mkuron** [comment]
If we can’t do it for everything, there is no point in doing it at all. We‘d still need the NAT for the non-proxied services. The proxy would just add needless complexity without any gain.

**Comment by imp1sh** [comment]
> integration would be pretty simple.

You're telling me the reason would be complexity while you said that earlier?

Gain would be:
- More than 100 different hostnames for SSL
- better scalbility for more POP3 / IMAP hosts (redundancy)
- MUCH better privacy protection
Sad that you don't see it.

**Comment by mkuron** [comment]
It‘s more complex having it than not having it. Even though it seems simple to set up, it will require maintenance to keep working too.

Why would that 100-name limit go away? We‘d still be using the same certificate. And multiple certificates may even be possible within Dovecot itself.

Mailcow has no Dovecot clustering support, so we can’t make use of that scalability.

When you say privacy, I assume you mean separate certificates for each domain. I don’t consider that a big issue as that information is available through DNS too. Also, Managesieve, which can't be proxied, is also TLS-encrypted and would still provide the certificate with all names. There is a ticket open about adding whitelabeling support however (#528), which I guess is related, but certainly not the same thing.

**Comment by imp1sh** [comment]
> I don’t consider that a big issue as that information is available through DNS too.

That's just not true, as there aren't the tools to retrieve this information systematically and reliably.

**Comment by mkuron** [comment]
There are DNS-crawling services like the one built into http://bgp.he.net, which can give you such information for many/most domains and IP addresses...
