### ISSUE TITLE
Failure on docker-compose pull.

### ISSUE THREAD

**Issue by neyaoz** [mailcow/mailcow-dockerized#830]
I am getting this error when i follow the steps on,
https://mailcow.github.io/mailcow-dockerized-docs/install/

```
root@lipsum:/var/www/mail# docker-compose pull
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by neyaoz** [comment]
docker -v:
Docker version 17.09.1-ce, build 19e2cf6

docker-compose -v:
docker-compose version 1.8.0, build unknown

git status:
Your branch is up-to-date with 'origin/master'.

git log:
commit e4b91e06a393fa796f8875822398a3b258d2fe70

**Comment by stevesbrain** [comment]
You're on quite an old version of docker-compose:

`docker-compose version 1.17.1, build 6d101fb`

Try updating by `./update.sh` instead; this automatically pulls the latest docker compose, the latest mailcow repo, and all of the appropriate versions of the docker containers :)

**Comment by neyaoz** [comment]
It makes sense, thanks. I had installed via apt, and it is not containing the latest version of docker-compose.
