### ISSUE TITLE
Apple Mail woes

### ISSUE THREAD

**Issue by trick77** [mailcow/mailcow-dockerized#831]
After updating all containers to the most recent versions, I'm seeing a problem with Apple Mail when using IMAP. Sending mail, receiving mail, browsing through IMAP folders all works fine. However, Apple Mail always says "Moving messages" in the Activity window, an activity that never completes. Messages wont be moved from Inbox to the Archive or Trash folders, they are stuck while Apple Mail tries to move them.

The only workaround so far is to delete all *Index files in Apple's Maildir to force a full resync from the IMAP server. **However, once I select a bunch of messages archive or trash them, the problem starts again.**

- No error messages in Dovecot
- A few suspicious error messages in Apple Mail's log but not sure if related: "Reading failed from socket: <0x6080002b4e80 mail.myserver.com:993>, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"

Anyone else seeing this pattern?

**Comment by andryyy** [comment]
Hi, we would need a full Dovecot log from when this happens. :-)

**Comment by trick77** [comment]
Just the container log output? Any special debug flags?

**Comment by trick77** [comment]
This is a container log capture when it happens (it happens all the time). 

dovecot-mailcow_1    | Dec 21 18:50:01 mail CRON[10881]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:50:14 mail dovecot: imap(sendspam@here.tld): Connection closed (SELECT finished 124.914 secs ago) in=896 out=3156

dovecot-mailcow_1    | Dec 21 18:51:01 mail CRON[10887]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:51:01 mail CRON[10889]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:51:01 mail CRON[10887]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:51:15 mail dovecot: imap-login: Login: user=<sendspam@here.tld>, method=PLAIN, rip=10.20.30.40, lip=172.22.1.5, mpid=10900, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)

dovecot-mailcow_1    | Dec 21 18:51:19 mail dovecot: imap-login: Login: user=<sendspam@here.tld>, method=PLAIN, rip=10.20.30.40, lip=172.22.1.5, mpid=10906, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)

dovecot-mailcow_1    | Dec 21 18:51:23 mail dovecot: imap(sendspam@here.tld): Logged out in=542 out=1955

dovecot-mailcow_1    | Dec 21 18:51:23 mail dovecot: imap(sendspam@here.tld): Logged out in=449 out=1609

dovecot-mailcow_1    | Dec 21 18:52:01 mail CRON[10908]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:52:01 mail CRON[10910]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:52:02 mail CRON[10908]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:52:49 mail dovecot: lmtp(10912): Connect from 172.22.1.3

dovecot-mailcow_1    | Dec 21 18:52:50 mail dovecot: lmtp(sendspam@here.tld): MCqENQEDPFqgKgAAus99lg: sieve: msgid=<5a3c02f12c9df_58513ff0855e2530327478@syd.updn.io.mail>: stored mail into mailbox 'INBOX'

dovecot-mailcow_1    | Dec 21 18:52:50 mail dovecot: lmtp(10912): Disconnect from 172.22.1.3: Successful quit

dovecot-mailcow_1    | Dec 21 18:53:01 mail CRON[10918]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:53:01 mail CRON[10920]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:53:01 mail CRON[10918]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:54:01 mail CRON[10922]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:54:01 mail CRON[10924]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:54:01 mail CRON[10922]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:54:07 mail dovecot: imap-login: Login: user=<sendspam@here.tld>, method=PLAIN, rip=10.20.30.40, lip=172.22.1.5, mpid=10928, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
dovecot-mailcow_1    | Dec 21 18:55:01 mail CRON[10930]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:55:01 mail CRON[10932]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:55:01 mail CRON[10930]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:56:01 mail CRON[10935]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:56:01 mail CRON[10937]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:56:01 mail CRON[10935]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:56:11 mail dovecot: imap(sendspam@here.tld): Connection closed (SELECT finished 124.306 secs ago) in=826 out=2867

dovecot-mailcow_1    | Dec 21 18:56:14 mail dovecot: imap-login: Login: user=<sendspam@here.tld>, method=PLAIN, rip=10.20.30.40, lip=172.22.1.5, mpid=10944, TLS, TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)

dovecot-mailcow_1    | Dec 21 18:57:01 mail CRON[10946]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:57:01 mail CRON[10948]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:57:01 mail CRON[10946]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:57:33 mail dovecot: lmtp(10951): Connect from 172.22.1.3

dovecot-mailcow_1    | Dec 21 18:57:33 mail dovecot: lmtp(sendspam@here.tld): 2OLBHh0EPFrHKgAAus99lg: sieve: msgid=<mailcow/mailcow-dockerized/issues/831/353429401@github.com>: stored mail into mailbox 'INBOX'

dovecot-mailcow_1    | Dec 21 18:57:33 mail dovecot: lmtp(10951): Disconnect from 172.22.1.3: Successful quit

dovecot-mailcow_1    | Dec 21 18:58:01 mail CRON[10955]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:58:01 mail CRON[10957]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:58:02 mail CRON[10955]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 18:58:16 mail dovecot: imap(sendspam@here.tld): Connection closed (SELECT finished 122.276 secs ago) in=729 out=2189

dovecot-mailcow_1    | Dec 21 18:59:01 mail CRON[10961]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 18:59:01 mail CRON[10963]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

dovecot-mailcow_1    | Dec 21 18:59:01 mail CRON[10961]: pam_unix(cron:session): session closed for user root

dovecot-mailcow_1    | Dec 21 19:00:01 mail CRON[10965]: pam_unix(cron:session): session opened for user root by (uid=0)

dovecot-mailcow_1    | Dec 21 19:00:01 mail CRON[10967]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)

**Comment by hachre** [comment]
@trick77 Please edit `data/conf/dovecot/dovecot.conf` and enable `mail_debug = yes` there, then run `docker-compose restart dovecot-mailcow` and get a new log.

**Comment by trick77** [comment]
I'm closing this issue. The problem did not reappear after switching mail_debug on.
