### ISSUE TITLE
SSL (Let's Encrypt) http_proxy (Apache2) an the mailserver (mailcow)

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#832]
Hi guys,

I'm at the end with my knowledge :-(

I use a Pi3 as http_proxy (Apache2) and two VMs.
The Pi3 takes all ssl-certificates (Let's Encrypt) for the vhost.
One VM is a cloudserver and the other VM is the mailserver.
All ssl-hosts works without problems.

But, how can I make known the ssl-certificates for mailcow (postfix/dovecot) 

jm3west

**Comment by cwildfoerster** [comment]
you need to copy your lets encrypt certificates to data/assets/ssl as described in https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#use-own-certificates

**Comment by jm3west** [comment]
Oh, I'm sorry
I forgot to say all machines are in a different networks (vlan)
My problem is only the postfix/dovecot
The http (ssl) works fine in the different networks

Is there just the way copy & paste ?

**Comment by cwildfoerster** [comment]
You still need to get your certificates in that folder, postfix and dovecot use these certificates aswell as nginx. By the way you already implemented this according to: https://github.com/mailcow/mailcow-dockerized/issues/649
**EDIT:** your network configuration (vlan, firewall) is beyond mailcows scope, that something you need to figure out how to copy your certificates from one host to another host in another vlan. thats not that difficult.
