### ISSUE TITLE
Import emails from other providers

### ISSUE THREAD

**Issue by Dragnucs** [mailcow/mailcow-dockerized#834]
I thank you for the hard work you are doing in mailcow.

I have emails from other providers using roundcube (legtux.org) and sogo3 (gandi) as well.

How can I import my email to my very own mailcow install?

**Comment by cwildfoerster** [comment]
you could use something like [imapsync](https://imapsync.lamiral.info/)

**Comment by Dragnucs** [comment]
Thank you. I will look into it.

On 25 December 2017 21:08:02 WET, Constantin <notifications@github.com> wrote:
>you could youe something like
>[imapsync](https://imapsync.lamiral.info/)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mailcow/mailcow-dockerized/issues/834#issuecomment-353890841

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by igloocube** [comment]
This is already built in both at admin and user level in the mailcow web UI.

As admin: Configuration > Mailboxes > Sync jobs

As user: Scroll to the bottom of the page you get when you log in and 'Sync jobs' is on the right towards the bottom.

**Comment by Dragnucs** [comment]
Thank you @igloocube this works very well. It also allows me to mirror emails from providers not allowing automated forwards. This is a very interesting features that should be mentioned in the docs.

Thank you again.

**Comment by arunodhayam10d** [comment]
Hi @Dragnucs !
Can you please tell the configurations of sync jobs in mail cow web ui @Dragnucs ??

**Comment by MAGICCC** [comment]
See the docs https://mailcow.github.io/mailcow-dockerized-docs/firststeps-sync_jobs_migration/
Not that difficult
