### ISSUE TITLE
Trying to send mails from a Django app, problems with FQDN

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#836]
Hi everyone.
I'm trying to send mails from a Django app, but I get this:

```
27.12.2017 22:39:09  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
27.12.2017 22:39:09    self.run()
27.12.2017 22:39:09  File "/healthchecks/hc/lib/emails.py", line 22, in run
27.12.2017 22:39:09    msg.send()
27.12.2017 22:39:09  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/message.py", line 348, in send
27.12.2017 22:39:09    return self.get_connection(fail_silently).send_messages([self])
27.12.2017 22:39:09  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/backends/smtp.py", line 111, in send_messages
27.12.2017 22:39:09    sent = self._send(message)
27.12.2017 22:39:09  File "/usr/local/lib/python3.4/dist-packages/django/core/mail/backends/smtp.py", line 127, in _send
27.12.2017 22:39:09    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
27.12.2017 22:39:09  File "/usr/lib/python3.4/smtplib.py", line 793, in sendmail
27.12.2017 22:39:09    raise SMTPRecipientsRefused(senderrs)
27.12.2017 22:39:09smtplib.SMTPRecipientsRefused: {'recipient@mymailcow.com': (504, b'5.5.2 <19d1f69de707>: Helo command rejected: need fully-qualified hostname')}
```

I looked at the postfix master.cf in the repo here and realized that mailcow looks for a fully-qualified hostname. That's alright, but from what I know this should only happen, when there's no login data provided, right?

Any ideas what I could try out?

**Comment by andryyy** [comment]
Hi, Which port do you use? Is this app on the same server? using 172.22.1.1 as mail server?

**Comment by Braintelligence** [comment]
The Django app is running on a docker container within a Rancher ecosystem on a vServer on a dedicated server.

Mailcow is running on its own vServer on the same dedicated server.

I use port 25, should I try another one?

**Comment by mkuron** [comment]
25 is for delivery of incoming mails. Try 587, that is for authenticated submission.

**Comment by Braintelligence** [comment]
Well, "Asche auf mein Haupt" as we Germans say.

**Comment by Braintelligence** [comment]
Thanks @andryyy and @mkuron you are the best 😸

**Comment by 2567910** [comment]
@Braintelligence i dont get how you fixed it. Did you change the port of the email server to 587?
