### ISSUE TITLE
The server does not support secure connections.

### ISSUE THREAD

**Issue by pavinthan** [mailcow/mailcow-dockerized#839]
I used let's encrypt SSL for my mail.* domain,
I can send from web,
I can not send from outlook Clients

**Comment by mkuron** [comment]
You'll need to provide significantly more details to get help here. What works, what doesn't work, log files, screen shots, etc.

**Comment by pavinthan** [comment]
Thanks @mkuron, I flow this guide to fix this [https://github.com/mailcow/mailcow/wiki/Installing-existing-Let's-Encrypt-certificates](https://github.com/mailcow/mailcow/wiki/Installing-existing-Let's-Encrypt-certificates)
