### ISSUE TITLE
Ability to send an announcement to all users

### ISSUE THREAD

**Issue by chriscroome** [mailcow/mailcow-dockerized#842]
It would be convenient to have a way to send an announcement to all mailboxes on a Mailcow server (not aliases, just mailboxes).

One way to implement this would be to have a web form that admin users could use.

Another would be to have an alias, however if it was say, `users@example.org` then this would be great for spammers, so if it was implemented as an alias it would need to be limited to only allow a whitelist of authenticated users allowed to send emails to everybody.

An example use case, today there is a new version of [Docker CE, 17.12.0-ce](https://docs.docker.com/release-notes/docker-ce/) out (announcement not yet posted) and the upgrade will result is a little downtime and it would be nice not to have to get a list of email addresses via MySQL:

```bash
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -s -e "SELECT username FROM mailbox"
```

However this is not urgent, using MySQL is not the end of the world, and the "enhancement" label would be appropriate for this issue.

**Comment by andreas-git** [comment]
If i understand this right, i will just get the accounts list.
*iirc* pfadmin got broadcat message included and it works with vmail. Maybe is it possible to see how they doit and Assimilate it. 
https://sourceforge.net/projects/postfixadmin/files/postfixadmin/postfixadmin-3.1/

**Comment by andryyy** [comment]
Any idea what else we need? =>

![grafik](https://user-images.githubusercontent.com/2972950/46582108-535c2480-ca42-11e8-9d8f-b42165197946.png)

**Comment by patschi** [comment]
I believe this is solved as it was implemented by @andryyy in the past.
