### ISSUE TITLE
What "reasources" are?

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#852]
Hello, what is purpose of "resources"? I see that is special type of mailbox and mails are stored to dedicaded dir.

I can't figure out usage of this feature.

Thank you.

**Comment by mkuron** [comment]
They are special accounts that can be invited in the SOGo calendar. This is useful for reserving rooms or things.

From http://wiki.sogo.nu/ResourceConfiguration:
> SOGo supports the management of resources like meeting rooms or video projectors. A resource has, just like a person, a calendar, an email address and may be invited to events. The big difference is that resources auto accept invitations.
