### ISSUE TITLE
ERROR: for clamd-mailcow  You cannot remove a running container

### ISSUE THREAD

**Issue by unixfox** [mailcow/mailcow-dockerized#855]
Everytime I update mailcow I get this error:
```
Recreating 3e8e44968ff5_3e8e44968ff5_3e8e44968ff5_mailcowdockerized_clamd-mailcow_1 ... error

ERROR: for 3e8e44968ff5_3e8e44968ff5_3e8e44968ff5_mailcowdockerized_clamd-mailcow_1  You cannot remove a running container 3e8e44968ff5094087397676de657336216021652b705451315efb2ccbfe9d3c. Stop the container before attempting removal or force remove

ERROR: for clamd-mailcow  You cannot remove a running container 3e8e44968ff5094087397676de657336216021652b705451315efb2ccbfe9d3c. Stop the container before attempting removal or force remove
ERROR: Encountered errors while bringing up the project.
```

What should I do to fix this issue?

**Comment by mkuron** [comment]
`docker-compose down`. In theory, that shouldn’t be necessary, but sometimes compose loses track of the running containers.

**Comment by unixfox** [comment]
Thank you for your reply @mkuron.

I already tried that but when I execute after `docker-compose up -d` the same error appears.

**Comment by mkuron** [comment]
Then you need to use `docker ps` to get the container IDs and `docker rm` to terminate them. If even that fails, you need to reboot the host.

**Comment by unixfox** [comment]
I had a zombie container that I couldn't kill and stop.
A reboot resolved the issue, docker is strange sometimes...
Thank you.
