### ISSUE TITLE
Upgrading from mailcow 0.14 to dockerized; problem with importing old mails

### ISSUE THREAD

**Issue by Bentipa** [mailcow/mailcow-dockerized#856]
Hello,

[*as I upgraded to the new mailcow version (dockerized), I tried to copy the mails from /var/vmail/ into to  docker-volume (/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/).
The mails themselves where shown as a list entry in SOGo, but in the right upper corner, a popup was shown saying:  "No UID specified", the mail entry itself does not have any text and you can not click on it.

Is it possible to import the mails somehow, so they are shown correctly?
(Your tutorial of how to import the mails as a zip did not work, because an error of tar occured, which said the /backup/xyz.tar.gz was not not there but it was, another dude hat the same response)*]

Additionally:
When sending mails, this occurs: "Sent is not an IMAP4 folder "

Screenshots:
https://goo.gl/MM7Rn7
https://goo.gl/kCRDTG

I hope you can help me,
Benny

**Comment by hachre** [comment]
You need to make sure the permissions are correct. The files inside the vmail volume need to be owned by `5000:5000` as viewed from outside of any docker container. If that doesn't help check if you can find anything in the dovecot log by running:
```
docker-compose logs -f --tail=100 dovecot-mailcow
```

**Comment by Bentipa** [comment]
@hachre hah, that seems to be it, just one little mistake xD Thanks a lot, the UID thing is now fixed.

**Comment by hachre** [comment]
Glad it helped :)

**Comment by Bentipa** [comment]
The "Sent" issues is now also away, dunno why.
