### ISSUE TITLE
A docker newbie ask a docker question (backup)

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#858]
Hi,

is it possible just compress (tar) the mailcow_dockerized complete folder and good is.
When I have a problem then I do it uncompress the tar archive and the job goes on

Is this wrong?

**Comment by mkuron** [comment]
That‘s not the only place that contains Mailcow data. /var/lib/docker/aufs or /var/lib/docker/overlayfs contains the Docker images, but they can usually be retrieved again with `docker-compose pull`, so most people don‘t back them up. /var/lib/docker/volumes contains all the user mailboxes, databases, etc., so you need to back that up too.

**Comment by Siassei** [comment]
@jm3west For backup strategie, replace the tar-archive with an emashing tool like borg
https://borgbackup.readthedocs.io

You need to backup the mounted volumes + your mailcow folder. If you will restore the entry same system, you should also backup the used images of mailcow-service.

Example script file to backup an docker-compose service volumes with (optinal) images.
https://github.com/Siassei/docker-volume-backup/blob/master/docker_full_backup.sh

Usage: (note, it is dev-status. but a good entry point for your env)
```bash
MODE=backup # or restore

path=/opt/mydocker/project1/docker-compose.yml
project=project1
BACKUP_DIR=/tmp/mybackups
DATE=xxxx-xx-xx # with borg, that feature is not needed and currently sticked with x's

#export EXCLUDE_CONTAINER=1
#export EXCLUDE_VOLUMES=1

./docker_full_backup.sh $path $project $BACKUP_DIR $MODE $DATE
```

**Comment by pixelyo** [comment]
@Siassei would you be willing to create a backup and restore script for mailcow?
It would be amazing to have such a script similar to the update script.

@mkuron what are all the things to backup? We have the [mailboxes](https://mailcow.github.io/mailcow-dockerized-docs/u_e-backup_restore-maildir/) and [databases](https://mailcow.github.io/mailcow-dockerized-docs/u_e-backup_restore-mysql/) already referenced in the documentation. What else is missing?

**Comment by pixelyo** [comment]
seems like these things add to the mailboxes and database:

- Redis Database
- Postfix‘s queue
- Rspamd‘s training state

but there is probably more.
found this information in a [pull request about a backup script](https://github.com/mailcow/mailcow-dockerized/pull/639#pullrequestreview-65675175)

**Comment by mkuron** [comment]
#812 and #639 were attempts at backup scripts that were never finished. All the necessary information is in my comments there.

**Comment by pixelyo** [comment]
@mkuron thank you
so these are the things mentioned in the pull requests:
- Mailboxes
- MySQL Database
- Redis Database
- Postfix‘s queue
- Rspamd‘s training state

I see two more docker volumes on my system:
- mailcowdockerized_dkim-vol-1
- mailcowdockerized_crypt-vol-1

Are these volumes holding anything important?

I could also imagine that a backup of the `mailcow-dockerized` directory would be worth to be backed up.

--

general idea: would it be enough to just stop mailcow, make a copy of all volumes in `/var/lib/docker/volumes/`, make a copy of the `mailcow-dockerized` directory and then restart mailcow?

**Comment by andryyy** [comment]
I wrote something for all important data, will push soon.

**Comment by mkuron** [comment]
The backup script is now available in master.
