### ISSUE TITLE
No DKIM signature when sending via SMTP client

### ISSUE THREAD

**Issue by zero-one-devteam** [mailcow/mailcow-dockerized#86]
Hi,

I tested the dkmi signature with sending a mail to check-auth@verifier.port25.com. When doing this via SOGo's webmail, dkim result is passed. When doing this via email client (port 587 smtp), the message is not signed.

What could be the reason?

**Comment by andryyy** [comment]
Can you post `docker-compose logs rspamd-mailcow` output after trying to send an email from port 587?

**Comment by zero-one-devteam** [comment]
Sorry, my mistake. I used nginx as a proxy before and in this configuration DKIM did not work. Thus i changed configuration to default, but container was built from cache. Removing postfix container and re-building it solved my issue. Sorry!

**Comment by zero-one-devteam** [comment]
One additional information: If using nginx before postfix as an SMTP proxy, the user authentication is done via ngix (one has to provide a script for this). There is no second authentication done at postfix (usually not needed, other than with IMAP). In the dkim.conf of rspamd no dkim signature will be added to non authenticated users. So when using a proxy, you'll have to modify this setting.
