### ISSUE TITLE
Backup MX

### ISSUE THREAD

**Issue by pdomagala** [mailcow/mailcow-dockerized#860]
I saw similar issue, but it's closed and unresolved.
So, I have one question. "Normal"/old mailcow has option like https://github.com/mailcow/mailcow/wiki/Backup-MX-setup . I could set up 2nd server as mirror, but what now? I know the backup/restore process is very simple, but is it possible?

**Comment by igloocube** [comment]
What precisely are you trying to achieve? Having email synced between the 2 constantly or just relay from backup to primary?

You have these options when adding a domain in mailcow-dockerized (nothing in documentation, they would suggest they just relay to the primary server):

<img width="826" alt="screen shot 2018-01-07 at 16 33 11" src="https://user-images.githubusercontent.com/7476518/34651484-9e985262-f3c8-11e7-92ed-92c649cbdb76.png">
