### ISSUE TITLE
Mailcow eating a lot of RAM

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#861]
Hello,

I am sorry to disturb you guys again, but my mailserver started to eat up a lot of RAM. I joined to the SSH after a week to check updates...and server was using about 1500MB of RAM and there was about 600MB in SWAP. So i updated all containers - that rebooted them,,,but server started to eat the RAM again immediately after the upgrade, as you can see here:
![image](https://user-images.githubusercontent.com/9658012/34542308-4dc8e156-f0dc-11e7-9d88-a3144d577306.png)

Before few weeks, I was running older version of mailcow with RAM usage about 600MB stable.

Can you help me with this? Is the RAM usage for mails now that bigger with newer versions?

Thanks for your time

**Comment by hachre** [comment]
The major RAM usage comes from `clamd`. You can disable that in `mailcow.conf` near the bottom. The displayed RAM usage with clamd enabled is pretty normal.

**Comment by DJIronic** [comment]
OK, I think it's better to keep it on. I will more RAM to mailcow VM. How much RAM is OK to assign?

**Comment by andryyy** [comment]
Also depends on how many mailboxes you maintain on your server. Meta data and bayes hashes in Redis can eat up a lot of ram, too. You can set a maxmemory limit to Redis by editing docker-compose.yml and adding `command: redis-server --maxmemory 2048mb` or similar.
2 GB is a min for about 10-15 users, I'd say.

**Comment by DJIronic** [comment]
OK, I assigned 3GB of RAM to the VM and it runs just fine, I have about 30 mailboxes there, but only 5 are actively used.

**Comment by ghost** [comment]
My server crashed this morning, and I was wondering why the OOM.

Server had only 2 GB of ram without **swap**. I added 4 GB of **swap**, I think that will help.

In hope that could help someone else.

**Comment by Braintelligence** [comment]
@dctremblay You were wondering why your server with 2GB of RAM crashed for a software stack that requires at least 3GB RAM + Swap? https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/

**Comment by ghost** [comment]
Yeah! It ran well for a month before crashing.
We will see by adding swap how much time it will last.

I think that by decreasing thread pool of spamd and sogo it would be even lighter.

Thanks for the link !

**Comment by Directory** [comment]
hi im also experiencing issues with high memory usage and both solr and calmav are disabled, hows the followup with increasing swap size? in my case i have even less memory (1gb) so ik im really pushing the limits here lol.
