### ISSUE TITLE
UI improvement: Button for immediately restart SOGo after add a new domain

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#864]
![add_domain](https://user-images.githubusercontent.com/4533780/34574703-830f15e6-f178-11e7-98dd-70587bbfa251.png)

---

I would find a second button handy for a direct SOGo reboot. I think the screenshot says it all. :-)

**Comment by andryyy** [comment]
Yes, indeed. Will add it.
