### ISSUE TITLE
Mailbox Name Change is not reflected in Sogo

### ISSUE THREAD

**Issue by alexanderrieder** [mailcow/mailcow-dockerized#865]
If i change someones mailbox name in mailcow ui, it is still the "old" name in Sogo... How can i fix this? :)

**Comment by alexanderrieder** [comment]
I fixed it with a server restart.. However its strange..

**Comment by andryyy** [comment]
Should be enough to restart memcached-mailcow. :-) Or, well, wait a while.

**Comment by igorakkerman** [comment]
How can you even change a mailbox name? I can't find a way to do this on the UI...

**Comment by andryyy** [comment]
You can’t. He was probably talking about the real name of the user.

**Comment by igorakkerman** [comment]
Ok, do you have a suggestion on how to proceed if I wanted to "manually" rename the mailbox?

**Comment by andryyy** [comment]
Not that easy. Do you just want to keep the mails? Or do you need to keep calendars, contacts, sieve filters etc.?

**Comment by igorakkerman** [comment]
Only the mails. I don't currently use anything else. I was thinking about renaming the mailbox in dovecot if that's possible and manually change the row in MySQL using the mysql client in the Docker container. But I don't know if that would work and be enough... The mailbox has about 2.5GB btw :)

**Comment by andryyy** [comment]
Ah, okay, that's pretty easy then.

I'd just create a new mailbox then and login once (using SOGo for example).

Go to `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.tld` and just move the old mailbox name to the new name, like `mv old_username new_username`.
Edit: Forgot a step here => Move the existing new_username folder to something like new_username_old

Go back to the mailcow-dockerized directory and run:
```
source mailcow.conf
docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}
select password from mailbox where username = 'old_username';
# copy the output
update mailbox set password = '{SSHA256}xyz123' where username = 'new_username';
```

Restart SOGo after changing the database.

That should do it.

**Comment by igorakkerman** [comment]
Thanks a lot! I was able to do it. Here's what I'd add for anyone who also wants to rename their mailbox, e.g. from a@a.com to b@b.com:

- Before moving the mailbox files, de-activate the mailbox a@a.com in the UI, so that no email client is able to access it during the transition.
- Stop the postfix Docker container temporarily to avoid emails being delivered to the old mailbox.
- If you have defined aliases with a@a.com as a destination, modify them to point to b@b.com. I did it in a bulk using SQL update, something like:
```
update alias set goto = 'b@b.com' where goto = 'a@a.com';
```

Please let me know if any of these steps are unnecessary or wrong.

**Comment by porsager** [comment]
These steps to rename a mailbox would be great to have in the documentation, can I PR that somewhere?

**Comment by Braintelligence** [comment]
@porsager I'm not sure if I would want instructions for this in the documentation if this only works when `keep(ing) calendars, contacts, sieve filters etc.?` is not a requirement. People might lose data if they don't consider possible consequences properly.

@andryyy Can you elaborate on if it's more complicated if you want to keep the above mentioned things? Would it be too hard to create a mailcow script that we could call with docker-compose or even the Web GUI? Something like `docker-compose exec xyz rename-mailbox-address old@old.com new@new.com`?
