### ISSUE TITLE
mailcowdockerized_mysql-mailcow_1 restart indefinitely because it unable to read /data/conf/mysql/my.cnf

### ISSUE THREAD

**Issue by JOduMonT** [mailcow/mailcow-dockerized#866]
Hi;

I'm using CentOS with no userspace and SELinux in permissive mode.
Docker : 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs

I just git clone+gen without edition
but 
mailcowdockerized_mysql-mailcow_1 restart indefinitely because it unable to read /data/conf/mysql/my.cnf
at least it's what docker logs told me

I wonder what I missed ^?
> ERROR: mysqld failed while attempting to check config
> command was: "mysqld --max_allowed_packet=192M --max-connections=1500 --innodb-strict-mode=0 --skip-host-cache --skip-name-resolve --log-warnings=0 --verbose --help --log-bin-index=/tmp/tmp.k9qe216fwt"
> 
> mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 "Permission denied")
> Fatal error in defaults handling. Program aborted

it appear to run, at least mysql stop restarting
when I comment this line docker-compose.yml
`#./data/conf/mysql/:/etc/mysql/conf.d/:ro`

**Comment by andryyy** [comment]
May be related to SELinux or just wrong permissions. CentOS sometimes uses a 0077 umask instead of 0022 (correct my if I'm wrong). This will prevent other UIDs from reading files.
  
What is your umask? Could be added to the docs.

**Comment by bonanza123** [comment]
same problem here, my umask is 077 (debian stretch).
Fixed it without changing umask via
`find /opt/mailcow-dockerized -type d -exec chmod a+rX {} \;`
and
`find /opt/mailcow-dockerized -type f -exec chmod a+r {} \;`
