### ISSUE TITLE
Apple Mail with Active Sync

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#868]
I have seen that Mailcow [offers a profile](https://mailcow.github.io/mailcow-dockerized-docs/client-apple/) (SMTP/IMAP, Cal- /CardDav) for macOS. This works without problems and is very helpful.

However, the e-mail client also supports Exchange.

![mail](https://user-images.githubusercontent.com/4533780/34610366-1e66d2ce-f221-11e7-869f-de568faa82de.png)

My config:

![config](https://user-images.githubusercontent.com/4533780/34610588-172ee54a-f222-11e7-8adc-e679c5bb05f5.png)

The Login for Exchange works:

![auswahl](https://user-images.githubusercontent.com/4533780/34610463-7a7cded2-f221-11e7-89ce-d078ce2ea225.png)

But i receive no mails:

![error](https://user-images.githubusercontent.com/4533780/34610493-a6e28c7e-f221-11e7-9577-37738692df23.png)

That's no problem for me, but I'd still be surprised: Is ActiveSync for macOS not supported by Mailcow/SOGo?

**Comment by hachre** [comment]
It's only supported for Outlook on the PC, the included Windows 10 apps and Android and iOS smartphones by SOGo.

**Comment by mritzmann** [comment]
Okay, thanks for the information.

It's a pity that ActiveSync is not the same as ActiveSync. One might think its the same everywhere.

**Comment by mkuron** [comment]
macOS does not support ActiveSync. It only supports Exchange Web Services, which SOGo doesn‘t provide.
