### ISSUE TITLE
Add proxy configuration for Appache2 to documentation

### ISSUE THREAD

**Issue by horvan** [mailcow/mailcow-dockerized#869]
Hi folks. It's been a while since I used mailcow. Now that it is docerized and doesn't come with apache2 anymore I get troubels after installing mailcow

Let's say I like to use Apache for my website and Mailcow for mail. Than allmost everything works well but I am not able to redirect http://mail.domain.com:80 to https://mail.domain.com:8433 where nginx is listening. 

I know you droped apache2 but could you please provide a section in the doc that is describing how to run them side by side when using letsencrypt for both services that would be great. So users like me will get a great mail software and do not need to learn nginx from scratch to drive thair websites.

**Comment by m-bits** [comment]
Does https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ help?

**Comment by igloocube** [comment]
Does https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ help?

**Comment by horvan** [comment]
May be but I switched over to an other solution since mailows mariadb listen to 172.22.1.1 and doesn't work on a fresh debian server anymore.

Mailcow had the option to install it with apache bevore it's getting dockerized. But it would be great if there will be an option to use nginx as proxy for apache2 and install mailcow to mail.yourdomain.tdl because there are so many bugs and things to configure between nginx and other software than mailcow so that I would be realy happy if I could use apache behind nginx with let's encrypt right out of the box. So you can use mailcow without know to much about nginx and apache2 beside it to run your website. if you need it.

**Comment by mkuron** [comment]
> mariadb listen to 172.22.1.1 and doesn't work on a fresh debian server anymore.

What do you mean? MariaDB is not exposed and does not block any listen ports on the host. And it definitely works on a freshly-installed Debian server (though if there is a local MTA installed, you need to reconfigure it to free up port 25).

> But it would be great if there will be an option to use nginx as proxy for apache2

You can use any proxy you like. Mailcow doesn‘t need to know about it. And you don‘t need to care that Mailcow uses Nginx internally; you can just put an Apache proxy in front of it if you like.

> I would be realy happy if I could use apache behind nginx with let's encrypt right out of the box

You could use a cron job on the host to copy Mailcow‘s certificate to /etc/apache and run apache on the host.

**Comment by horvan** [comment]
I'll just give it a new try and make some nodes along the setup phase to provide better feedback on thees acctually two bugs. I like mailcow a lot.
