### ISSUE TITLE
[German]https:// = Mailcow interface

### ISSUE THREAD

**Issue by rellik8821** [mailcow/mailcow-dockerized#871]
Hey,
Wenn ich meine Website normal über www.meineseite.de öffne komm ich normale auf meine Page.
sobald ich ein https:// davor schreibe lande ich im Mailcow interface.

Mein webserver ist Apache2
Habe deshalb in der mailcow.conf den Port auf 8082 geändert.

Möchte nicht das ich über https das interface öffnen.
Hat jemand eine lösung?

Habe ein ReverseProxy am laufen aber das klappt glaube auch nicht so richtig.

**Comment by Braintelligence** [comment]
Klingt für mich eher nach einem Webserver-Einrichtungsproblem als nach einem Mailcow-Problem...

Vielleicht kannst du ja mal deine Apache Configs (ich glaub die mit den VHosts, bin eigentlich NGINX-Nutzer) hier reinkopieren und jemand ist so nett und hilft dir.

**Comment by rellik8821** [comment]
Seite.conf
```
<VirtualHost *:80>

    ServerName meineseite.de
        ServerAlias www.meineseite.de
        #ServerAdmin webmaster@site-a.com
        DocumentRoot /var/www/test

       

        ErrorLog ${APACHE_LOG_DIR}/site-a_error.log
        CustomLog ${APACHE_LOG_DIR}/site-a_access.log combined
</VirtualHost>
```


Proxy.conf
```
<VirtualHost *:443>
    ServerName mail.meineseite.de
    

   
    # You should proxy to a plain HTTP session to offload SSL processing
    ProxyPass / http://127.0.0.1:8082/
    ProxyPassReverse / http://127.0.0.1:8082/

    ProxyPreserveHost On
    ProxyAddHeaders On

    # This header does not need to be set when using http
    RequestHeader set X-Forwarded-Proto "https"

    


SSLCertificateFile /etc/letsencrypt/live/mail.meineseite.de-0001/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mail.meineseite.de-0001/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

mailcow.conf habe ich
```
HTTP_BIND=127.0.0.1
HTTP_PORT=8082
HTTPS_BIND=127.0.0.1
HTTPS_PORT=8443
```

**Comment by hachre** [comment]
Du musst ein 2. Virtualhost mit Port 443 und dem Hostname `meineseite.de` einrichten, inklusive der SSL Einstellungen aber ohne das ProxyPass Zeug.

Also z.B. bei Seite.conf folgendes hinzufügen:
```
<VirtualHost *:443>
    ServerName meineseite.de
    ServerAlias www.meineseite.de
    #ServerAdmin webmaster@site-a.com
    DocumentRoot /var/www/test
      
    ErrorLog ${APACHE_LOG_DIR}/site-a_error.log
    CustomLog ${APACHE_LOG_DIR}/site-a_access.log combined

    SSLCertificateFile /etc/letsencrypt/live/mail.meineseite.de-0001/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mail.meineseite.de-0001/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

In der `mailcow.conf` musst du eventuell einstellen, dass er auch ein Zertifikat für `meineseite.de` ausstellt und nicht nur für `mail.meineseite.de`, oder du kannst natürlich ganz eigene Zertifikate angeben.

**Comment by rellik8821** [comment]
Das läuft aber auch nur weil dann alles über https:// läuft.
komme jetzt gar nicht mehr auf http://

**Comment by hachre** [comment]
Das klingt jetzt danach, dass du alles in Seite.conf damit ersetzt hast, oder? Der Originalinhalt muss bleiben und das was ich geschrieben habe hinzugefügt werden.

**Comment by rellik8821** [comment]
Die Original seite.conf war noch. 
Aber jetzt löuft grade gar nix mehr werde glaube noch mal alles neu machen.

Ist ein ReverseProxy notwenig oder kann ich das weglassen?
Habe vor Apache als Haupt Webserver zu nutzen.

**Comment by hachre** [comment]
Du kannst den Apache größtenteils völlig unabhängig von Mailcow konfigurieren und musst nur den Inhalt aus deiner Proxy.conf irgendwo drin haben. Du kannst die Sachen auch alle in die selbe Datei stecken. Der Inhalt der Proxy.conf sollte am Besten nach den anderen VirtualHost Einträgen kommen.

**Comment by rellik8821** [comment]
Glaube habs jetzt zum laufen bekommen.

Wie mach ich das nur mailcow interface über Https läuft?
Wenn ich also https://www.meineseite.de aufrufe, das ich mit Firefox die meldung Fehler: Verbindung fehlgeschlagen  o.ä. bekomme?
  
weil möchte nicht das funktioniert https://ServerIP , obwohl es ja durch fehlende Zertifikate nicht aufrufbar ist.

**Comment by mablae** [comment]
@rellik8821 Du möchtest einfach TLS benutzen auch wenn du das noch nicht realisiert hast. 

Es gibt heute keinen sinnvollen Grund mehr, auf TLS zu verzichten, zumal die Zertifikate dank Lets Encrypt nichts mehr kosten.
