### ISSUE TITLE
Cant connect to DOMAIN.COM:8082

### ISSUE THREAD

**Issue by KeNzoooo** [mailcow/mailcow-dockerized#873]
Since im using Cloudflare my mailserver powered by mailcow doesnt work anymore. I cant access to the mailcow UI the Port/URL wont resolve. How do I fix that ? Already tried to reinstall mailcow many times, still doesnt work. Im really overwhelmed right now...

**Comment by Braintelligence** [comment]
Did you see this issue, maybe it could help? https://github.com/mailcow/mailcow-dockerized/issues/872

**Comment by KeNzoooo** [comment]
Oh noo yet, but thank you. I executed the command "docker-compose restart acme-mailcow && docker-compose logs -f --tail=100 acme-mailcow" and it gave me out "acme-mailcow_1       | mysqld is alive
acme-mailcow_1" & "| Sun Jan  7 20:13:05 UTC 2018 - Waiting for domain tables... Waiting for Docker API..."

**Comment by mkuron** [comment]
Cloudflare only supports HTTP/HTTPS, so your mailserver will never be able to receive incoming emails and IMAP/SMTP clients won‘t be able to connect. So you need to disable Cloudflare for the (sub)domain that your Mailcow server runs on.

**Comment by hachre** [comment]
@KeNzoooo it sounds like you might have updated Docker while the system was running... you should try shutting down Mailcow (`docker-compose down`) and rebooting the server!

**Comment by KeNzoooo** [comment]
So, I've done everything written on #872 still doesnt work. Here are the logs: `acme-mailcow_1       | Mon Jan  8 13:48:57 UTC 2018 - Found A record for kenzoo.pw: 789.789.789.789`
`acme-mailcow_1       | Mon Jan  8 13:48:57 UTC 2018 - Cannot match your IP 123.123.123.123 against hostname domain.com (789.789.789.789)`
`acme-mailcow_1       | Mon Jan  8 13:48:57 UTC 2018 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.`
`acme-mailcow_1       | Mon Jan  8 13:48:57 UTC 2018 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.`

Also tried to create a subdomain without cloudflare only with http, also dont work.
Also tried to shut down mailcow and rebooted the server, also dont work.

**Comment by andryyy** [comment]
Please use a FQDN as hostname, not domain.tld.

You need to disable the Cloudflare IP protection for this FQDN.

**Comment by KeNzoooo** [comment]
how do I use a FQDN as hostname ? never done this before

**Comment by andryyy** [comment]
In mailcow.conf set host.domain.tld as MAILCOW_HOSTNAME. :-) Run docker-compose down and docker-compose up -d afterwards. 

In Cloudflare you'd need to disable Cloudflares IP protection for this hostname then.

**Comment by KeNzoooo** [comment]
@andryyy Dang it! Thank you very much <3. Everything is working now

**Comment by andryyy** [comment]
Nice! 👍
