### ISSUE TITLE
Postfix-level postscreen_dnsbl_sites whitelist

### ISSUE THREAD

**Issue by Alireza2n** [mailcow/mailcow-dockerized#875]
Hi,
It would be nice to be able to have a feature to whitelist an ip or domain for postfix in mailcow admin UI, so when sender is blacked listed via dnsbl, admin can be able to white list that specific ip or domain.

Thanks

**Comment by mkuron** [comment]
You can use the forwarding hosts feature for this. However, that will also prevent spam from that IP from being rejected (it will only be flagged then), but usually that is what people want.
