### ISSUE TITLE
Automatic metadata stripper for attachments

### ISSUE THREAD

**Issue by ChessSpider** [mailcow/mailcow-dockerized#876]
Hi,

I was wondering, how would one implement automatic metadata removal for attachments in Mailcow (when sending email) ? Does anyone have experience with that?

**Comment by mkuron** [comment]
That would need to happen in a pre-queue milter or as an rspamd plugin. A quick Google search didn’t reveal any existing solutions, so this is probably a very niche application and you‘ll need to write it yourself.
