### ISSUE TITLE
why connection ended up with SQLSTATE[HY000] [1045] Access denied for user 'mailcow'@'172.22.1.4'  ?

### ISSUE THREAD

**Issue by unplugandplay** [mailcow/mailcow-dockerized#88]
Hello, I deployed mailcow using the docs and I ended up with "Access denied for user 'mailcow'@'172.22.1.4'  " ! 
I have not change my password, when I try to connect from local with 
 mysql -h 172.22.1.6 -u admin -p
I ended up with the same : Access denied for user 'mailcow'@'172.22.1.1' (using password: YES)

**Comment by andryyy** [comment]
Try docker-compose down -v to reset the volumes. This will delete all data. Or just delete the MySQL volume.

**Comment by unplugandplay** [comment]
thx
