### ISSUE TITLE
Remove language dropdown if only one is active

### ISSUE THREAD

**Issue by urhovaldeko** [mailcow/mailcow-dockerized#880]
There's no real point for language dropdown being visible when only one language is defined in vars.local.inc.php.

Simple git diff would be 

`index cedd07c..20841a7 100644`
`--- a/data/web/inc/header.inc.php`
`+++ b/data/web/inc/header.inc.php`
`@@ -45,7 +45,7 @@`
`     <div id="navbar" class="navbar-collapse collapse">`
`       <ul class="nav navbar-nav navbar-right">`
`         <?php`
`-        if (isset($_SESSION['mailcow_locale'])) {`
`+        if (isset($_SESSION['mailcow_locale']) && count($AVAILABLE_LANGUAGES) > 1) {`
`         ?>`
`         <li class="dropdown">`
`           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="lang-sm lang-lbl" lang="<?= $_SESSION['mailcow_locale']; ?>"></span><span class="caret"></span></a>`

**Comment by urhovaldeko** [comment]
There's also one of the login page, basically same count > 1 right before `<div class="btn-group pull-right">` there would do the trick.

**Comment by PhoenixPeca** [comment]
Just committed a fix.
