### ISSUE TITLE
Question: Reason for building containers?

### ISSUE THREAD

**Issue by kolaente** [mailcow/mailcow-dockerized#885]
Is there a reason for building 50% of the containers when setting up mailcow instead of building them before for everybody and then pulling from dockerhub? It would make deployment much easier.
Also I've wanted to add mailcow to the Rancher community catalog, but you can't build dockerimages directly on Rancher, only pull preexisting ones...

I really like the project, keep on the good work!

**Comment by mkuron** [comment]
They should all be on Docker Hub. Every time @andryyy merges the dev branch into master, he rebuilds all changed containers and pushes the image to Docker Hub.

Regarding Rancher: there are a few issues on here which may help you, e.g. #196.

**Comment by mkuron** [comment]
All containers have been uploaded with the most recent merge, so you shouldn't see any more rebuilds when you do `docker-compose pull && docker-compose up -d` after you update.
