### ISSUE TITLE
Configuring Bounce

### ISSUE THREAD

**Issue by crimsonvspurple** [mailcow/mailcow-dockerized#886]
Is there any guide on how to configure bounce address for mailcow?

For example, if I want to contain all bounce/delivery failures in to one specific mailbox?
Right now it is all going to one mailbox (the first one created i guess) but not the one I'd want them to go in to.

**Comment by mkuron** [comment]
What kind of bounces (messages Maiilcow rejects or messages Mailcow fails to deliver)? We don‘t do anything special, so all bounces will be delivered to the sender, as one would expect.

**Comment by crimsonvspurple** [comment]
Usually fails to deliver ones.

Not all the software using the send email features are configured very all (old apps). Some even sending from www-data@localhost etc.

However, *all* the bounces are getting back to admin@maindomain.
So it is a problem. Best if all bounces can be sent to bounce@maindomain

**Comment by mkuron** [comment]
I don’t think Mailcow treats admin@ special in any way, so it’s not clear to me why this is happening.

Could you please post the logs that appear at the time when such a message is bounced (`docker-compose logs -f postfix-mailcow`) and also the full bounce message including headers?

**Comment by crimsonvspurple** [comment]
I found this just now: 
```
X-Authentication-Warning: 2ndmaindomain: www-data set sender to admin@maindomain using -f
```

I think I'll look in to this and come back again if it doesn't go anywhere.

**Comment by mkuron** [comment]
Ok, so this clearly is not a Mailcow issue. It looks like the user account www-data on the sending machine (2nddomain) calls `sendmail -f admin@maildomain`, which sets the envelope-sender to admin@maildomain on all emails sent like this. So bounces are sent to that address and you‘ll need to reconfigure the sending machine if you want to change that.
