### ISSUE TITLE
Can't restart Sogo

### ISSUE THREAD

**Issue by unplugandplay** [mailcow/mailcow-dockerized#89]
![capture d ecran 2017-03-04 a 21 38 21](https://cloud.githubusercontent.com/assets/6077/23582091/01b09ee8-0123-11e7-9b20-bff0b24052c8.png)
This is what I end up to when trying to restart SoGo

**Comment by andryyy** [comment]
You didn't update the images.

**Comment by unplugandplay** [comment]
I uninstall the image
then docker-compose up -d
and it all went well !
![capture d ecran 2017-03-04 a 21 57 29](https://cloud.githubusercontent.com/assets/6077/23582209/9a4d9b9a-0125-11e7-92f9-163dd50b35bd.png)

nice !
