### ISSUE TITLE
acme-client and agreement url -- why the dynamic rebuild?

### ISSUE THREAD

**Issue by jas8522** [mailcow/mailcow-dockerized#892]
I [see here](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/Dockerfile) that to get around the acme-client's statically compiled agreement URL, the binary is dynamically built upon run of the container. This seems like a *lot* of overkill when you can instead edit [docker-entrypoint.sh](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh) and add the following to the arguments passed to acme-client:

`-a 'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'`

I'm curious as to why the dynamic rebuild was chosen over this? Maybe something to do with docker-entrypoint.sh not being static compared to the Dockerfile? (I'm admittedly very new to managing Docker containers and docker-compose)

**Comment by andryyy** [comment]
Seriously ... I just had a glance over the readme and missed that option. Shame on me. I will fix it, thanks.

**Comment by jas8522** [comment]
Thanks @andryyy :)
