### ISSUE TITLE
"550 User unknown in virtual mailbox table" when sending to a specific server

### ISSUE THREAD

**Issue by Follpvosten** [mailcow/mailcow-dockerized#893]
I set up my mailcow-dockerized instance in a VM at mail.karpador.xyz, and it works great for the most part (i sometimes have to manually restart docker after a reboot, but that's fine).  
Today, i tried sending an e-mail to my company's mail server (my own address there), which worked before. K-9 gave me a pretty interesting "No valid recipient" message, so i started investigating.

Works:
* Sending e-mail from and to gmail
* Sending e-mail internally on the mail server

Doesn't work:
* Sending any e-mail to or from my account on my employer's mail server (religio-x.com)

When i try sending an e-mail *from* the other server (to my server), i get a message undeliverable notice.  
The other way round, i get an error message from the server through SMTP.  
The error is always the same, as i can see in the logs:  
`550 5.1.1 <*@religio-x.com>: Recipient address rejected: User unknown in virtual mailbox table;`

It doesn't seem to happen with any other mail server. What could be the issue?

**Comment by mkuron** [comment]
This sounds like you added religio-x.com as a domain to your Mailcow server. Are you sure your own domain is the only one you added in the admin web interface?

**Comment by Follpvosten** [comment]
Thanks, that was the issue. I didn't think about it, i set it up as a temporary backup mailserver for religio-x some time ago. User error. Fixed.
