### ISSUE TITLE
How to use backup_and_restore.sh with cron and command-line

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#896]
Hello,

andryy pushed a new backup-and-restor-script which looks very nice.
Until now i used a self-made-script in connection with cron.
Since there is a script within mailcow-dockerized i would like to use this script.

To start the "backup" within mailcow-dockerized directory:

./helper-scripts/backup-and_restore.sh backup all ....

How can i use the whole path in the command line?
How to use the script in crontab?

Thanks for any advice.
Feuernatter

**Comment by ghost** [comment]
I made a mistake ....
How can i use the backup-path in den command line?

./helper-scripts/backup-and_restore.sh backup all /directory/dir/...

does not work ...

**Comment by andryyy** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/

Just pushed it. 👍

**Comment by cklabautermann** [comment]
I have the following entry in my /etc/crontab:

`51 23 * * * root BACKUP_LOCATION=/opt/backup /opt/mailcow-dockerized/helper-scripts/backup_and_restore.sh backup all`

and it works :-)
