### ISSUE TITLE
rspamd web UI forbidden after upgrade

### ISSUE THREAD

**Issue by levinuss** [mailcow/mailcow-dockerized#898]
Hey,
I just updated to the new master. While going through the new features in the Interface I wanted to go to the rspamd web interface as well. The password that worked before (the last login was some time ago but it worked with this password) didn't work. rspamd just displayed a red bar: "Forbidden". I tried setting the old and another password via the mailcow web interface and restarting the rspamd container. Same problem. I don't know for sure this is because of the new master but either way it has to be resolved..
Is this reproducible? What could be the problem?

**Comment by hachre** [comment]
The old password no longer worked for me anymore either. However, there is now a new UI in the Debug section of the Mailcow admin interface. I used that to set a new password and without even restarting rspamd, it worked with the new password instantly. So it does work in at least some cases.

**Comment by levinuss** [comment]
@hachre I did actually try the new UI in the debug section and that didn't work either though it displayed "password set successfully" to me. Rspamd login still not possible.

**Comment by andryyy** [comment]
What's in your `data/conf/rspamd/override.d/worker-controller-password.inc`?

**Comment by phipag** [comment]
I can confirm the issue. Even though there is the correct hash in the worker-controller-password.inc the login does not work.
For me it worked when i override the password with password = "hashed pw" in the worker-controller.inc

**Comment by andryyy** [comment]
`git checkout data/conf/rspamd/override.d/worker-controller.inc` should fix it. Could be a merge conflict. Also update dockerapi.

**Comment by levinuss** [comment]
The checkout does not help in my case. I discovered some strange things in the `worker-controller-password.inc`.
- The password hash is there, but
- Some strange things are written before the password hash
```
enable_password = "2018011419243614rspamadmcfgrspamdconfigpostloadCPUdoesnthaveSSSE3instructionssetrequiredforhyperscandisableit$passwdhash..
```
When I try to generate the password manually (looked for the old [documentation](https://github.com/mailcow/mailcow-dockerized-docs/pull/47)) I noticed that this string (with other formatting) is displayed as a warning before typing the password.
```
2018-01-14 20:08:49 #14(rspamadm) cfg; rspamd_config_post_load: CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
Enter passphrase:
$passwdhash..
```
I have little to no idea what the warning should tell me... According to Wikipedia its a instruction set that exsists on most recent (Intel) CPUs. My server is hosted at servercow so maybe you can say something about this @andryyy?

Maybe we could adjust the output parsing to take only the hash?
I copied the hash now manually and pasted it into the file. Access works.

**Comment by andryyy** [comment]
I fixed this a few minutes ago. :-)

It did not ignore stderr, this was fixed in dockerapi a few minutes (hours?) ago.

**Comment by levinuss** [comment]
Sorry, I didn't know that the docker api fix was related. Just updated after I wrote the post and can confirm its working now. Thank you! Close?

**Comment by andryyy** [comment]
No problem at all! Yes, we can close it, I think. :-)

**Comment by wblondel** [comment]
Hi,

I just got the same issue. Rspamd Web Interface password was lost after restoring a backup.
