### ISSUE TITLE
German test on English interface

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#902]
don't know what happened, but a part of my interface is in German:

![](https://i.imgur.com/x0A5Sms.png)

**Comment by levinuss** [comment]
Looks like the strings are [hardcoded into the php file](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/admin.php#L398). I couldn't find a language code for the translation files. Searched for it in the [German](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/lang/lang.de.php) and [English](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/lang/lang.en.php) file. A maintainer would probably have to add a new string for translation (I don't know how you are handling this) and then change it in the php file.

**Comment by PhoenixPeca** [comment]
Done! Please update your setup now. 😄
