### ISSUE TITLE
Unable to update mailcow installation cause of mysql-mailcow can not be stopped

### ISSUE THREAD

**Issue by menzbua** [mailcow/mailcow-dockerized#903]
Hi,

i'm trying to update my mailcow instance as described in https://mailcow.github.io/mailcow-dockerized-docs/install-update/

When i try to docker-compose up the updated containers i got an error message:

compose.config.config.find: Using configuration files: ./docker-compose.yml
WARNING: compose.config.environment.__getitem__: The LOG_LINES variable is not set. Defaulting to a blank string.
WARNING: compose.config.environment.__getitem__: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
docker.auth.find_config_file: Trying paths: ['/home/manuelmenz/.docker/config.json', '/home/manuelmenz/.dockercfg']
docker.auth.find_config_file: No config file found
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/version HTTP/1.1" 200 541
compose.cli.command.get_client: docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.4.0-108-generic, Components=[{u'Version': u'17.12.0-ce', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-108-generic', u'Os': u'linux', u'BuildTime': u'2017-12-27T20:09:53.000000000+00:00', u'ApiVersion': u'1.35', u'MinAPIVersion': u'1.12', u'GitCommit': u'c97c6d6', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.9.2'}}], Arch=amd64, BuildTime=2017-12-27T20:09:53.000000000+00:00, ApiVersion=1.35, Platform={u'Name': u''}, Version=17.12.0-ce, MinAPIVersion=1.12, GitCommit=c97c6d6, Os=linux, GoVersion=go1.9.2
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/info HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker info -> {u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'ContainerdCommit': {u'Expected': u'89623f28b87a6004d4b785663257362d1658a729',
                       u'ID': u'89623f28b87a6004d4b785663257362d1658a729'},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'mailcowdockerized_mailcow-network')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/networks/mailcowdockerized_mailcow-network HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {u'Attachable': True,
 u'ConfigFrom': {u'Network': u''},
 u'ConfigOnly': False,
 u'Containers': {u'06771446b8593d414918b1d6e49228f655b571d198197ad752f27c223f9fc666': {u'EndpointID': u'9e36ba38d6e8ede593c1dc39b1e54847cb5e5f8dc447df0724dc96d41880a0f1',
                                                                                       u'IPv4Address': u'172.22.1.7/24',
                                                                                       u'IPv6Address': u'fd4d:6169:6c63:6f77::e/64',
                                                                                       u'MacAddress': u'02:42:ac:16:01:07',
                                                                                       u'Name': u'mailcowdockerized_postfix-mailcow_1'},
                 u'0e5c84cdf6fb507bdeadcd9f84b573d1e78ddfc1bae46ae2eb09f90058fc30ba': {u'EndpointID': u'd6e02f36a85cc8b663bcef1a1bc80191d819c35a319ae244c225bb1a703a4c49',
                                                                                       u'IPv4Address': u'172.22.1.6/24',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_crypt-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_crypt-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2017-11-29T13:02:48+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'crypt-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_crypt-vol-1/_data',
 u'Name': u'mailcowdockerized_crypt-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_crypt-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_crypt-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2017-11-29T13:02:48+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'crypt-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_crypt-vol-1/_data',
 u'Name': u'mailcowdockerized_crypt-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_redis-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_redis-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-15T14:46:26+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'redis-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_redis-vol-1/_data',
 u'Name': u'mailcowdockerized_redis-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_redis-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_redis-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-15T14:46:26+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'redis-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_redis-vol-1/_data',
 u'Name': u'mailcowdockerized_redis-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_vmail-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_vmail-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-13T04:30:01+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'vmail-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data',
 u'Name': u'mailcowdockerized_vmail-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_vmail-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_vmail-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-13T04:30:01+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'vmail-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data',
 u'Name': u'mailcowdockerized_vmail-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_postfix-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_postfix-vol-1 HTTP/1.1" 200 310
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T11:53:19+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'postfix-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_postfix-vol-1/_data',
 u'Name': u'mailcowdockerized_postfix-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_postfix-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_postfix-vol-1 HTTP/1.1" 200 310
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T11:53:19+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'postfix-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_postfix-vol-1/_data',
 u'Name': u'mailcowdockerized_postfix-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_rspamd-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_rspamd-vol-1 HTTP/1.1" 200 307
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T13:46:09+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'rspamd-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_rspamd-vol-1/_data',
 u'Name': u'mailcowdockerized_rspamd-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_rspamd-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_rspamd-vol-1 HTTP/1.1" 200 307
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T13:46:09+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'rspamd-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_rspamd-vol-1/_data',
 u'Name': u'mailcowdockerized_rspamd-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_mysql-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_mysql-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T11:52:56+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'mysql-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data',
 u'Name': u'mailcowdockerized_mysql-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_mysql-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_mysql-vol-1 HTTP/1.1" 200 304
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2018-01-10T11:52:56+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'mysql-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_mysql-vol-1/_data',
 u'Name': u'mailcowdockerized_mysql-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_dkim-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_dkim-vol-1 HTTP/1.1" 200 301
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2017-11-29T13:02:31+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'dkim-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_dkim-vol-1/_data',
 u'Name': u'mailcowdockerized_dkim-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume <- (u'mailcowdockerized_dkim-vol-1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/volumes/mailcowdockerized_dkim-vol-1 HTTP/1.1" 200 301
compose.cli.verbose_proxy.proxy_callable: docker inspect_volume -> {u'CreatedAt': u'2017-11-29T13:02:31+01:00',
 u'Driver': u'local',
 u'Labels': {u'com.docker.compose.project': u'mailcowdockerized',
             u'com.docker.compose.volume': u'dkim-vol-1'},
 u'Mountpoint': u'/var/lib/docker/volumes/mailcowdockerized_dkim-vol-1/_data',
 u'Name': u'mailcowdockerized_dkim-vol-1',
 u'Options': {},
 u'Scope': u'local'}
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=mailcowdockerized', u'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/json?all=0&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dmailcowdockerized%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0 HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 15 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'dc9c228c49c0eda281dc7ed8c31884d4382008a48886f12fe85c10b68f198b9c')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/dc9c228c49c0eda281dc7ed8c31884d4382008a48886f12fe85c10b68f198b9c/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'/usr/bin/rspamd', u'-f', u'-u', u'_rspamd', u'-g', u'_rspamd'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/usr/bin/rspamd',
                      u'-f',
                      u'-u',
                      u'_rspamd',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'b23766710d65ae51a30955a68f0d8d6cd8d5890c1fce97155e35aba3a63e638f')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/b23766710d65ae51a30955a68f0d8d6cd8d5890c1fce97155e35aba3a63e638f/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'-g', u'--', u'/srv/docker-entrypoint.sh'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/sbin/tini',
                      u'-g',
                      u'--',
                      u'/srv/docker-entrypoint.sh'],
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'56a705afd6b63adc6506aad64ad864bf3b9ad2dd63f0b27c0ad6b7d9e48f4be9')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/56a705afd6b63adc6506aad64ad864bf3b9ad2dd63f0b27c0ad6b7d9e48f4be9/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'unconfined',
 u'Args': [u'-u', u'/logwatch.py'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'python2', u'-u', u'/logwatch.py'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'SKIP_FAIL2BAN=n',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'9e9a406ffb7d7ca2d7a3f9bb3f8fc2e11e675ad15f1ca1b41f402a6ca545b0b9')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/9e9a406ffb7d7ca2d7a3f9bb3f8fc2e11e675ad15f1ca1b41f402a6ca545b0b9/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'/usr/sbin/unbound'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/usr/sbin/unbound'],
             u'Domainname': u'',
             u'Entrypoint': [u'/docker-entrypoint.sh'],
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
             u'ExposedPorts': {u'53/tcp': {}, u'53/udp': {}},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'b3c25a6a0591fa24b615270d901e0452d5dbee1ea9be06a16cadf1c9d897ac90')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/b3c25a6a0591fa24b615270d901e0452d5dbee1ea9be06a16cadf1c9d897ac90/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'-c',
           u"envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active && envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active && envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active && nginx -qt && until ping phpfpm -c1 > /dev/null; do sleep 1; done && until ping redis -c1 > /dev/null; do sleep 1; done && exec nginx -g 'daemon off;'"],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
                      u"envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active && envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active && envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active && nginx -qt && until ping phpfpm -c1 > /dev/null; do sleep 1; done && until ping redis -c1 > /dev/null; do sleep 1; done && exec nginx -g 'daemon off;'"],
             u'Domainname': u'',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'0e5c84cdf6fb507bdeadcd9f84b573d1e78ddfc1bae46ae2eb09f90058fc30ba')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/0e5c84cdf6fb507bdeadcd9f84b573d1e78ddfc1bae46ae2eb09f90058fc30ba/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'php-fpm',
           u'-d',
           u'date.timezone=Europe/Berlin',
           u'-d',
           u'expose_php=0'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'php-fpm',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'ece104c41b2f74ddf0b23b54e2b1f8f3311c595ebc67a0833ad404ed54c75b94')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/ece104c41b2f74ddf0b23b54e2b1f8f3311c595ebc67a0833ad404ed54c75b94/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'/bin/sh',
           u'-c',
           u'exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh',
                      u'-c',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'b7be05136ff83bef86a3902ba388e089032a3438cbda10f593839fe48329c421')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/b7be05136ff83bef86a3902ba388e089032a3438cbda10f593839fe48329c421/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'-g', u'--', u'/bootstrap.sh'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/sbin/tini', u'-g', u'--', u'/bootstrap.sh'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'SKIP_CLAMD=y',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'28ab7138721d3a73df8fc84ca13e48143f53d6e395b71449ea2b79329d1543c1')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/28ab7138721d3a73df8fc84ca13e48143f53d6e395b71449ea2b79329d1543c1/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'unconfined',
 u'Args': [u'--retry'],
 u'Config': {u'ArgsEscaped': True,
             u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'--retry'],
             u'Domainname': u'',
             u'Entrypoint': [u'/docker-ipv6nat'],
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'8f3176f77f77d73376208935a2b9391a2c34901a3540628d4aebe5c1c9b98929')
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

The container where the timeout happens is the mysql-mailcow container. When i try to stop the container manually that did not work too. Nothing happens after docker stop command.

If you need further informations please let me know.

Regards
Manuel

**Comment by axd** [comment]
Are you using the automatic update way or the manual? It seems that shell doesn't load the mailcow.conf file were are those variables, check that if you have that file in your mailcow folder. 

Always try to use the automatic way.

**Comment by menzbua** [comment]
I tried the automatic way too but also no success.
The mailcow.conf file is in the directory:

ls -l mailcow.conf
-rw-rw-r-- 1 xxx xxx 1790 Jan  8 16:09 mailcow.conf

The problem i see is that i can not stop the mysql-mailcow container with docker stop, too. I can stop all mailcow containers manually except that.
