### ISSUE TITLE
iptables / mailcow-dockerized

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#908]
How to use any configuration management system which configures iptables on a system with mailcow-dockerized installed?

Sadly there is no docker-free mailcow :-(

**Comment by mkuron** [comment]
Short answer: don’t do it. Try to limit the services that are running and restrict the listen ports so you don‘t need a firewall.

Docker creates firewall rules itself to handle container traffic. In doing so, it pretends that there are no other existing rules and thus in general does not treat existing rules gracefully. It does have some support for ufw and if you are manually writing the rules, you may be able to tweak them to work as well.

There are many issues reported here (just search for iptables). This is not a Mailcow-specific issue and there is nothing we can do about it.

**Comment by patrick7** [comment]
Thanks for your feedback. Too bad there's no docker free version. 
There should be a solution for people using a firewall.

**Comment by andryyy** [comment]
You can still use netfilter as you like to. You just need to make sure to not mess with Docker filters. You could also disable iptables in Docker (there is a flag for that) and snapshot the currently set rules.

**Comment by mkuron** [comment]
Snapshotting the rules only works as long as the docker-compose-generated IP addresses don‘t change. But besides that, it would be a workable solution.
