### ISSUE TITLE
Quarantine tab does not show rejected mails

### ISSUE THREAD

**Issue by AikoAppeldorn** [mailcow/mailcow-dockerized#909]
Hey

I updated my Mailcow to the latest version today and found the Quarantine tab, but no rejected mails are displayed even though they have already been rejected.

Do I have to wait a certain amount of time or is there an error here?

**Comment by andryyy** [comment]
Hi,

Thanks for your donation! 👍 

Did you check the quarantaine settings and set a value for "items to keep"?

**Comment by AikoAppeldorn** [comment]
Hi,

yes, I set a value of 100 Mails.

**Comment by andryyy** [comment]
Updated via update.sh?

**Comment by andryyy** [comment]
Oh, a max size is set, too, I guess?

**Comment by AikoAppeldorn** [comment]
yes

**Edit:** I've seen the pipe.php in the rspamd directory and I've checked the nginx-mailcow log, but the file was never called. But I don't know of this is important.

**Comment by andryyy** [comment]
Max size, too? 

If so, may I have a look at it?

**Comment by AikoAppeldorn** [comment]
> Max size, too?

I will check this value, again. Can you tell me where I can find the value?

**Comment by andryyy** [comment]
In admin -> config.

![grafik](https://user-images.githubusercontent.com/2972950/34979081-9142343c-faa0-11e7-9048-8decc1091300.png)

**Comment by AikoAppeldorn** [comment]
![b01d8a6c-ad56-49c5-b270-6281289b6fc9](https://user-images.githubusercontent.com/6564899/34979482-a8ca60c4-faa1-11e7-97bc-5e797aec7c4d.jpeg)

Should I check any other values, too?

**Comment by andryyy** [comment]
No, that's fine. What is your "git diff" output?

**Comment by andryyy** [comment]
By the way: It does only display rejects by Rspamd. It will not show rejects by Postfix (postscreen), which happen due to blacklisted ips.

**Comment by AikoAppeldorn** [comment]
> No, that's fine. What is your "git diff" output?

I will check it this evening.

> By the way: It does only display rejects by Rspamd. It will not show rejects by Postfix (postscreen), which happen due to blacklisted ips.

Yes, I know. Because of this, I forked mailcow and removed the dnsbl lists from postscreen and added it to [rspamd rbl](https://git.hosted4u.de/Hosted4u/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/rbl.conf). I merged your master yesterday in my master branch.

**Comment by andryyy** [comment]
There are some more changes to master.cf etc., that you might have missed.

**Comment by AikoAppeldorn** [comment]
`There are some more changes to master.cf etc., that you might have missed.`

Actually I have merged all changes to my master. There were no merge conflicts. [Commit](https://git.hosted4u.de/Hosted4u/mailcow-dockerized/commit/9f983ac89f342d44cd75d0a42ab9bb71cc91897d)

**Comment by andryyy** [comment]
Can you check wether Nginx logs pipe.php access? phpfpm-mailcow logs would be great, too. This should help.

**Comment by AikoAppeldorn** [comment]
> Can you check wether Nginx logs pipe.php access? phpfpm-mailcow logs would be great, too. This should help.

Yesterday I looked into the nginx log file and I only saw the call of settings.php and forwarding.php, circa every 20 seconds.
I will check the nginx and php log in this evening, again.

**Comment by AikoAppeldorn** [comment]
So, here are the logs:

[php.log](https://github.com/mailcow/mailcow-dockerized/files/1635962/php.log)
[nginx.log](https://github.com/mailcow/mailcow-dockerized/files/1635963/nginx.log)

There is no pipe.php

**Comment by andryyy** [comment]
But you received a rejected mail at this moment? Meta exporter seems not to be active.

**Comment by AikoAppeldorn** [comment]
> But you received a rejected mail at this moment? Meta exporter seems not to be active.

Yes, I tested it with a rejected mail and there is no call of pipe.php.

**Comment by AikoAppeldorn** [comment]
Thank you. Fixed in Commit: https://github.com/mailcow/mailcow-dockerized/commit/c6bcf322ffcac59b372dffc76050e3ce89de246f
