### ISSUE TITLE
Where new dockerized mailcow store dkim cert and txt ?

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#912]
I want to transfer dkim and txt from old 0.14. Where I need to store on dockerized mailcow.
I try in _data of dkim docker but don't work.

Thank you !

**Comment by andryyy** [comment]
Hi, they are stored in Redis. You can import them via UI.

**Comment by petarkozic** [comment]
@andryyy 
:D Thank you !

**Comment by petarkozic** [comment]
@andryyy 
Becuase I'm migrated all from 0.14 I saw in admin old key only as defined without key.
I supposed that is because I restore mysql from old mailcow.
If I try to import DKIM manually from admin I get error:

Private key error: error:0E06D06C:configuration file routines:NCONF_get_string:no value

What can I do ? Thank's !
Also, I can't delete this old one !

<img width="955" alt="screen shot 2018-01-16 at 10 46 03 am" src="https://user-images.githubusercontent.com/17702869/34982441-af4557de-faaa-11e7-9ad8-6e10b79b3a5f.png">

**Comment by petarkozic** [comment]
@andryyy 
How can I resolve this import DKIM problem from old mailcow 0.14.
I want to keep old DKIM. 
Thanks.

**Comment by andryyy** [comment]
Copy the correct key content format in the UI. I used it just yesterday, it is not broken.
It only complains on invalid content.

**Comment by petarkozic** [comment]
@andryyy 
Can you please tell me location of key on old mailcow 0.14 which I need to copy ?
Thank's man.
