### ISSUE TITLE
configuration guides: ä ö ü are not displayed correctly (maybe a Safari Bug)

### ISSUE THREAD

**Issue by mritzmann** [mailcow/mailcow-dockerized#913]
## Problem

The name [in the documentation](https://mailcow.github.io/mailcow-dockerized-docs/client-outlook/) is not displayed if there is an umlaut in. Appears only in Safari. Not sure if this is a problem of mailcow-dockerized or mailcow-dockerized-docs.

## step to reproduce

1. open mail.example.com and login with a mailbox user (use a user with an ö, ä or ü in name)
2. click on `Show configuration guides for email clients and smartphones`
3. See guide for Microsoft Outlook (as example)

## Screenshot

**On Firefox:**

 Works correctly.

Screenshot:

> ![1](https://user-images.githubusercontent.com/4533780/34981234-31015362-faa7-11e7-9b16-ad714075f223.png)

URL: `https://mailcow.github.io/mailcow-dockerized-docs/client/#host=mail.example.com&email=markus%40example.com&name=M%C3%BCller+R%C3%BCegg&port=443&outlookEAS=1`

_(URLs from the example above are copy and pastet from `Show configuration guides for email clients and smartphones` Link.)_

---

**On Safari:** It doesn't work.

Screenshot:

> ![2](https://user-images.githubusercontent.com/4533780/34981275-4ded13c6-faa7-11e7-931f-e275f824cc68.png)

URL: `https://mailcow.github.io/mailcow-dockerized-docs/client/#host=mail.example.com&email=markus%40example.com&name=Müller+Rüegg&port=443&outlookEAS=1`

_(URLs from the example above are copy and pastet from `Show configuration guides for email clients and smartphones` Link.)_

**Comment by MAGICCC** [comment]
Seems like Safari doesn't like ASCII characters in a cookie: https://stackoverflow.com/questions/1969232/allowed-characters-in-cookies/1969339#1969339
I gonna ask my friend if he can do some encoding/decoding magic with the client.js in the docs repository. He may fix it later
