### ISSUE TITLE
How to list "High Spam"

### ISSUE THREAD

**Issue by hansapils** [mailcow/mailcow-dockerized#920]
Hi guys,

rspamd seems to be doing a great job. With new credentials I can log in the rspamd Webinterface and see which mails had a spam level above 15 and were rejected.

But how do I enable a user to see what emails were meant for him and became rejected?

hansapils

**Comment by cklabautermann** [comment]
This indeed would be a nice feature - e.g. to receive a daily email notification about which mails were rejected or are in quarantine...
...without the need to look into the **brand new and great quarantine section** of the mailcow ui ;-)

best regards,
Claudio
