### ISSUE TITLE
Stale data for deleted domains

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#921]
Hello,

I moved some domains from Mailcow and I noticed that at least /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain-name.xx is not deleted when the domain is. From the Rspamd settings map I can also see that rspamd still has rules for deleted domains.

I would like to know:
- How I can delete those rules from rspamd
- Is there any other stale data elsewhere? Perhaps in redis?

Thank you!

**Comment by mkuron** [comment]
DKIM keys stored in Redis are also domain-specific and probably not deleted automatically.

We could automatically delete all the corresponding vmail, MySQL and Redis entries when a domain is deleted from the web interface. When a mailbox is deleted, there are also some user-specific entries that could be deleted but probably aren’t.

I‘d actually be in favor of doing that only after a certain time delay (e.g. one week) in case the user/domain was accidental deleted.

**Comment by catcun** [comment]
I understand the reasoning behind leaving the data after the domain deletion and I don't mind. 
I just want an option (instructions/script/web) to manually delete it all
Options?

**Comment by hachre** [comment]
My opinion: I think the actual mail data should not be automatically deleted at all. The rest of the data can be deleted as proposed after a 7-14 day undo window. The mail data should only be deleted manually or through a special manual intervention in the UI after the 7-14 day window is over.

**Comment by catcun** [comment]
What about backups? I haven't check the backup script yet but I believe it does backup all.
My take: I delete when I no longer need; for mistakes I have backups. Keeping stale data is not something I do; keeping backups for months or years is normal.

**Comment by mkuron** [comment]
Until we get some kind of automatic cleanup implemented, you can manually delete mail data from the vmail directory in /var/lib/docker/volumes. The stuff in the database you can just leave as it won‘t take up much space (unless you add and remove domains and users on a daily basis).

**Comment by catcun** [comment]
@mkuron
Thank you. I always delete mail data. I am going to move some domains to a separated Mailcow server and I want to use the new backup script to restore all domains to the new instance and delete all that is not needed in both servers. I was hoping to be able to get a completely new server that way but it seems like it is not possible for now.
Anyway, I believe the backup script will make the move much easier so it is a trade off I am willing to take

**Comment by mkuron** [comment]
Let‘s leave this issue open. It could/should probably be fixed some time.

**Comment by mritzmann** [comment]
I think this is a big security issue.

Examples:

- A company fires the employee peter@ and hires a new employee, who is also called peter. It makes no sense for peter to be able to access all old e-mails.
- Shared instances: Someone registers with a domain that already existed before.

> I think the actual mail data should not be automatically deleted at all. The rest of the data can be deleted as proposed after a 7-14 day undo window.

I think it's very bad too. Deleted mailboxes have to be removed, completely. If necessary, every operator / admin has backups. The only thing you could do would be to automatically move the mailbox in the volume to another location and have it deleted after a few days.

**Comment by andryyy** [comment]
It was changed/fixed with the last "bigger" push.
