### ISSUE TITLE
leak sensitive data on the api debug 

### ISSUE THREAD

**Issue by schleyk** [mailcow/mailcow-dockerized#922]
Hi Mailcows =)

I found a security issue about the debug menu.
If the admin or the mail user itself change his password, the debuging outpout leaks the plaintext password  "Config / Debug / Logs / API" 

![2018-01-16 21_43_02-mailcow ui](https://user-images.githubusercontent.com/17356113/35011499-9d44d42c-fb06-11e7-8069-a8d08ee2e086.png)

**Comment by andryyy** [comment]
Very good catch, will fix this now!

**Comment by andryyy** [comment]
Fixed with 7701660
