### ISSUE TITLE
BCC Maps not listed

### ISSUE THREAD

**Issue by JanHuisink** [mailcow/mailcow-dockerized#924]
I just updated my installation and added a BCC map. This went fine but I can't list the maps I just created, the list is empty.

The API using `/api/v1/get/bcc/all` returns the following data:

```
[
    {
        "id": 1,
        "local_dest": "@test.domain",
        "bcc_dest": "test@archive.domain",
        "active_int": 1,
        "active": "&#10004;",
        "type": "rcpt",
        "created": "2018-01-17 09:21:02",
        "domain": "test.domain",
        "modified": null
    }
]
```

It seems that the webgui doesn't query the API.

**Comment by andryyy** [comment]
Hm, cannot replicate this here. :-/ 

Any errors in your browsers dev console?

**Comment by JanHuisink** [comment]
There were no errors in the dev console but after clearing the browser cache (should have thought about that before) it works.

**Comment by PhoenixPeca** [comment]
Hi @JanHuisink, Looks like the problem was resolved. I am closing this for now.
