### ISSUE TITLE
Postfix config change

### ISSUE THREAD

**Issue by igloocube** [mailcow/mailcow-dockerized#927]
What am I doing wrong please? First time I'd tried to customise settings like this.

I wish to set: ```smtpd_tls_received_header = yes``` in main.cf for postfix to show full TLS info in the headers.

I have tried both:
* ```docker-compose exec postfix-mailcow postconf -e "smtpd_tls_received_header = yes"```
* ```docker-compose restart postfix-mailcow```

And also:
* Adding ```smtpd_tls_received_header = yes``` to data/conf/postfix/main.cf
* ```docker-compose restart postfix-mailcow```

But afterwards still:
```
$ docker-compose exec postfix-mailcow postconf -d|grep smtpd_tls_received_header
smtpd_tls_received_header = no
```

**Comment by andryyy** [comment]
The config location is /opt/postfix :-) Just add it to data/conf/postfix/main.cf

**Comment by igloocube** [comment]
That's what I did with the 2nd thing I tried (see above) :(

**Comment by andryyy** [comment]
Postconf will always write the wrong value if you don’t add -c or -C /opt/postfix/conf as parameter

**Comment by igloocube** [comment]
Ok so 1 won't work, but I tried 2 different methods (stated above), the 2nd one not using postconf like you said, change conf in data/, just editing that file, then restarting the container, did not work.

**Comment by igloocube** [comment]
```
$ cat data/conf/postfix/main.cf | grep smtpd_tls_received_header
smtpd_tls_received_header = yes
$ docker-compose restart postfix-mailcow
Restarting mailcowdockerized_postfix-mailcow_1 ... done
$ docker-compose exec postfix-mailcow postconf -d|grep smtpd_tls_received_header
smtpd_tls_received_header = no
```

**Comment by andryyy** [comment]
docker-compose exec postfix-mailcow postconf -c /opt/postfix/conf

**Comment by igloocube** [comment]
Thanks @andryyy 

To clarify for any one finding this in future. Do not use ```postfix -d``` as it reads the wrong config. Use -c as below to check the config. :)

* Add ```smtpd_tls_received_header = yes``` to data/conf/postfix/main.cf (or what ever config you are changing)
* Verify the new config from the out put of: ```docker-compose exec postfix-mailcow postconf -c /opt/postfix/conf```
* Restart postfix: ```docker-compose restart postfix-mailcow```
