### ISSUE TITLE
GUI - Sync Jobs - Max Age Failure

### ISSUE THREAD

**Issue by Fvbor** [mailcow/mailcow-dockerized#928]
Created a new Sync Job on two different systems (One is a fresh installation), after changing the maximum age to a value over or equal 128 days, I got following message:
`MySQL: PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'delete1' at row 1 in /web/inc/functions.mailbox.inc.php:307 Stack trace: #0 /web/inc/functions.mailbox.inc.php(307): PDOStatement->execute(Array) #1 /web/json_api.php(530): mailbox('add', 'syncjob', Array) #2 {main}`

![image](https://user-images.githubusercontent.com/18524580/35066813-34885428-fbd2-11e7-9bd2-5599ff34260c.png)

While the creation is the max age not saved. When I edit the new sync job, I get an max age of 0.

**Comment by andryyy** [comment]
It is fixed, thanks.
