### ISSUE TITLE
How to set iOS Mail with Push?

### ISSUE THREAD

**Issue by Dirk23** [mailcow/mailcow-dockerized#93]
Hi,

i just installed mailcow, but i didn't install the docker one. I don't want to use docker.
I could see that you removed z-push:

> Z-Push removed - choose between SOGo (ActiveSync + DAV) and Roundcube

So how do i now setup my Mailclient on iOS to receive Emails via push? 

Regards

Dirk

**Comment by andryyy** [comment]
But this is the Docker repository.
You can just install the "standard" mailcow with SOGo enabled in the config file.

**Comment by Dirk23** [comment]
i did install "standard" mailcow with SOgo enabled, but i could not manage to get an "Exchange" account activated in iOS. Is there no other config needed than installing mailcow "standard" an enable SOgo?
I have Portforwarding for Ports 25,465,587,993 to mailcow-server
I have Apache Proxy for Port 80,443 to forward to mailcow-server (mail.mydomain.tld -> ProxyPass / https://mailcowserver and ProxyPassReverse / https://mailcowserver) wich works like a charm.
I have autoconfig and autodiscover Subdomains wich point to mail.mydomain.tld
I have valid certificates for all Domains and Subdomains (lets encrypt) and i replaced the self-signed Cert in Mailcow with the lets encrypt cert with intermediate cert included in it.
I go to iOS Settings -> Mail -> Accounts -> Add Account -> Exchange and fill out the needed fields, but iOS tells me it can not check the credentials and does not connect.

**Comment by Dirk23** [comment]
Strange, i reconfigured everything, now i could get connected.
