### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by jimmyr57000** [mailcow/mailcow-dockerized#930]
Hello,

I'm trying to install mailcow on a Debian 8 vps (fresh debian 8) but I have an error

http://prntscr.com/i24cw6

Thanks you

**Comment by andryyy** [comment]
There is a Postfix or Exim4 running. You can reconfigure, remove or stop it.

systemctl stop postfix; systemctl disable postfix;
systemctl stop exim4; systemctl disable exim4;

**Comment by jimmy-rich** [comment]
Thanks you!

I now have another strange problem .. https://prnt.sc/i24xn6

**Comment by jimmyr57000** [comment]
Thank you the problem and settled, for cons why I'm not https?

https://prnt.sc/i25u2x

This is not automatic?

**Comment by andryyy** [comment]
You can enable a redirect. Check the docs. :-)

**Comment by jimmyr57000** [comment]
Hello, 

problem solved thanks you andryyy!

do you already configure dns on cloudflare?

https://prnt.sc/i2b79f

I manage to receive the mails but against the sending does not work

Thanks,
