### ISSUE TITLE
Problems with PHP-FPM limits

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#931]
Hello, today I experience problems with whole stack. Unresponsive Postfix and Nginx. I figure out, taht problem was caused by php-fpm hitting max children limit (5).

So I increase it to 10 and restart container. After a while problem was here again, with same message

    seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 9 total children
    server reached pm.max_children setting (10), consider raising it

Probably it is caused by debug.php page - I experience it three times after refreshing that page, so there is something, which takes long tim eto complete and use all available process.

Of course, I can try increase max children to 30 or 60, but we should solve root of problem.

I also propose to use more php-fpm pools (containers), at least two:
- one for basic mail server functionality - postfix, rspamd, etc.
- second one for web ui

**Comment by feldsam** [comment]
I play a bit with pm values and create PR. This also increase max memory consuption

**Comment by feldsam** [comment]
I investigate debug page a little bit, and see that all logs are downloaded via api immediately. That should be loaded only when user clicks in dropdown on some logs page.

Anyway, I still think, that pm.max_children 5 is small, especially when there are more calls from rspamd...

**Comment by andryyy** [comment]
This should not happen and I cannot replicate it. It is - as I wrote - probably related to a reverse proxy setup. 

I am testing a separate worker for system stuff (dynamic) + web stuff (ondemand) right now. We can lazyload the tables, though.

**Comment by andryyy** [comment]
Furthermore each child can handle a lot of requests (default should be around ~300?), it should never block 5 workers for 5 requests.

**Comment by feldsam** [comment]
probably I miss-understood how it works, but I believe that if there are 5 slow requests, them all 5 children are in use. Am I wrong?

**Comment by lavdnone** [comment]
Might also be worth putting auto recovery when dying in to `etc/php-fpm.d/www.conf` or `etc/php-fpm.d/system.conf`
helps to keep php up with sogo and activsync

     ; If this number of child processes exit with SIGSEGV or SIGBUS within the time
     ; interval set by emergency_restart_interval then FPM will restart. A value
     ; of '0' means 'Off'.
     ; Default Value: 0
     emergency_restart_threshold = 10
     
     ; Interval of time used by emergency_restart_interval to determine when
     ; a graceful restart will be initiated.  This can be useful to work around
     ; accidental corruptions in an accelerator's shared memory.
     ; Available Units: s(econds), m(inutes), h(ours), or d(ays)
     ; Default Unit: seconds
     ; Default Value: 0
     emergency_restart_interval = 1m
     
     ; Time limit for child processes to wait for a reaction on signals from master.
     ; Available units: s(econds), m(inutes), h(ours), or d(ays)
     ; Default Unit: seconds
     ; Default Value: 0
     process_control_timeout = 10s

**Comment by feldsam** [comment]
This is already done
