### ISSUE TITLE
default relay host without domain

### ISSUE THREAD

**Issue by roswitina** [mailcow/mailcow-dockerized#939]
Can I use the web interface to set a default relay host that is not assigned to a domain? 

I have a MailCow server running on the internal network, which users in the internal network can use to send mail (the firewall blocks all other outgoing mailports) without having a mail account. This general relayhost (SMTP from the ISP) should prevent the classification of the outgoing mail as SPAM.

If this is not possible, can I do this in Postfix without damaging the system?  In any case, I would love the realization via the web interface (UI).

**Comment by hachre** [comment]
I'd like this feature as well: The ability to set a default system-wide relayhost.

**Comment by roswitina** [comment]
Can someone please give me a tip on how to do this without damaging the rest of the configuration.

**Comment by sanvit** [comment]
Any update on this please?

**Comment by andryyy** [comment]
You can set "relayhost" in data/conf/postfix/main.cf, it will not be destroyed by an update. There will never be a default value other than "empty" for this parameter. :)

**Comment by andryyy** [comment]
You can also try to set "*" as destination in mailcow UI.
