### ISSUE TITLE
Postfix stalls connection for 30 seconds

### ISSUE THREAD

**Issue by skollro** [mailcow/mailcow-dockerized#940]
Hello everyone,

it seems that my mailcow Postfix stalls SMTP connections for about 30 seconds which leads to timeouts of some mail clients. After the connection is established the mail is sent within seconds.
```
19/01/2018, 15:48:50 | info | connect from unknown[XX.XXX.XXX.XX]
19/01/2018, 15:48:50 | warning | warning: hostname mail.xxx.xx does not resolve to address XX.XXX.XXX.XX
19/01/2018, 15:49:20 | info | Anonymous TLS connection established from unknown[XX.XXX.XXX.XX]: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
...
```
Can you help me? If you need more information just tell me.

**Update:** If I send mails from e. g. SoGo it's sent immediately

**Comment by andryyy** [comment]
Which port are you coming in? 587?

**Comment by skollro** [comment]
Yes, 587. Client is Apple Mail.

**Comment by andryyy** [comment]
Do you use ipv6?

You could try to enable verbose logging for submission in `data/conf/postfix/master.cf` by adding a "-v" behind "smtpd":

```
submission inet n       -       n       -       -       smtpd -v
```

Restart Postfix by running `docker-compose restart postfix-mailcow` afterwards.

**Comment by skollro** [comment]
No, I'm not using IPv6. According to the log the 30 second delay happens between these two steps:
```
25/01/2018, 14:03:23 | info | > XXX[XXX.XXX.XXX.XX]: 220 mail.xxx.xx ESMTP Postfix
-- | -- | --
25/01/2018, 14:03:53 | info | < XXX[XXX.XXX.XXX.XX]: EHLO [YYY.YYY.Y.YY]
-- | -- | --
```

**Comment by mkuron** [comment]
The first line is the greeting Postfix sends, the second line is the client‘s reply. You could try connecting with netcat and seeing how long it takes for the greeting to show up:

```
nc mail.example.com 587
```

**Comment by andryyy** [comment]
I wonder wether that's related to missing IPv6 somehow. You could also try to remove "enable_ipv6" from docker-compose.yml + ipv6nat and the internal network declaration.

**Comment by mkuron** [comment]
It might also be that it's doing a reverse DNS lookup on the IP address and either the responsible DNS server is very slow or it times out after 30 seconds.

**Comment by andryyy** [comment]
That's even more likely.

**Comment by skollro** [comment]
@mkuron The greeting shows up immediately.

**Comment by ralphys** [comment]
In my case there is like 12-15 seconds delay sending emails from Webmail or desktop clients

As soon as postfix hits the /cleanup it seems to try to connect to an IPv6 address milter, even though I have disabled IPv6.

This is the slow down in my box... 

`postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: public/cleanup socket: wanted attribute: status
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: input attribute name: status
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: input attribute value: 0
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: public/cleanup socket: wanted attribute: reason
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: input attribute name: reason
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: input attribute value: (end)
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: public/cleanup socket: wanted attribute: (list terminator)
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: input attribute name: (end)
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: > mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.8]: 250 2.0.0 Ok: queued as 9096D260C08
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: abort all milters
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: milter8_abort: abort milter inet:rspamd:9900
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: < mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.8]: QUIT
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: > mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.8]: 221 2.0.0 Bye
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostname: smtpd_client_event_limit_exceptions: mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network ~? 127.0.0.0/8
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostaddr: smtpd_client_event_limit_exceptions: 172.22.1.8 ~? 127.0.0.0/8
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostname: smtpd_client_event_limit_exceptions: mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network ~? [::ffff:127.0.0.0]/104
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostaddr: smtpd_client_event_limit_exceptions: 172.22.1.8 ~? [::ffff:127.0.0.0]/104
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostname: smtpd_client_event_limit_exceptions: mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network ~? [::1]/128
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostaddr: smtpd_client_event_limit_exceptions: 172.22.1.8 ~? [::1]/128
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostname: smtpd_client_event_limit_exceptions: mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network ~? 10.0.0.0/8
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostaddr: smtpd_client_event_limit_exceptions: 172.22.1.8 ~? 10.0.0.0/8
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostname: smtpd_client_event_limit_exceptions: mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network ~? 172.16.0.0/12
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: match_hostaddr: smtpd_client_event_limit_exceptions: 172.22.1.8 ~? 172.16.0.0/12
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: abort all milters
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: milter8_abort: abort milter inet:rspamd:9900
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: disconnect event to all milters
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: milter8_disc_event: quit milter inet:rspamd:9900
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: disconnect from mailcowdockerized_php-fpm-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.8] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: master_notify: status 1
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: connection closed
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: auto_clnt_close: disconnect private/tlsmgr stream
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: rewrite stream disconnect
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/smtpd[334]: proxymap stream disconnect
postfix-mailcow_1    | Mar 24 19:49:01 mail postfix/lmtp[341]: connect to dovecot[fd4d:6169:6c63:6f77::7]:24: Cannot assign requested address
email delivery continues...`
