### ISSUE TITLE
Multiple assigned HTML IDs

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#942]
Hi there,

i recognized in the chrome dev toolbar, that there are a lot of multiple assigned HMTL IDs. 
There should just be one ID set in the HTML tree.

Example:
On mailbox.php the IDs 

    csrf_token
    confirm_password
    add_item
    description
    domain
    key_id

is set more then one time.

**Comment by andryyy** [comment]
We could change it to data attrs, but the way they are used shouldn't prevent the site from working. Like "if click on ID, check form parent forms" etc.

Should be fixed, though. 👍

**Comment by develth** [comment]
Yep, isn´t a show stopper, just wanted to mention. 
Could also change to css classes, should be a easier selector than the data[name="domain"] comparisons.
