### ISSUE TITLE
acme-client does not create certs for new domains

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#943]
Hi there!

I recognized that the acme-client doesn´t create new Certs for my new Domains. 
If i do 

    docker-compose restart acme-mailcow && docker-compose logs -f --tail=100 acme-mailcow

it stops with:

> 
> acme-mailcow_1       | acme-client: bad exit: netproc(3555): 1
> acme-mailcow_1       | acme-client: bad exit: challengeproc(3558): 1
> acme-mailcow_1       | Sat Jan 20 12:04:49 UTC 2018 - Error requesting certificate, restoring from previous acme request and restarting containers...
> acme-mailcow_1       | Sat Jan 20 12:04:49 UTC 2018 - Verified hashes.
> acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
> 100    68  100    68    0     0     34      0  0:00:02  0:00:02 --:--:--    31
> acme-mailcow_1       | Sat Jan 20 12:04:49 UTC 2018 - Restarting 117708c37f478eb1a4a24a47c677822b800d1a5590bef0c59151c8a633099d86...command completed successfully
> acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
> 100    68  100    68    0     0     68      0  0:00:01  0:00:01 --:--:--    35
> acme-mailcow_1       | Sat Jan 20 12:04:51 UTC 2018 - Restarting d11ff55dc1e687f2421f3231163ba2730f413177853f571ac9cd4771180e9c81...command completed successfully
> acme-mailcow_1       |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> acme-mailcow_1       |                                  Dload  Upload   Total   Spent    Left  Speed
> 100    68  100    68    0     0     34      0  0:00:02  0:00:02 --:--:--    33
> acme-mailcow_1       | Sat Jan 20 12:04:53 UTC 2018 - Restarting 3a3d2bbf3fcdd0a9de836cd660a76aa9fdf47d37b9f0d84a9bf3279de39885c6...command completed successfully
> acme-mailcow_1       | Sat Jan 20 12:04:55 UTC 2018 - Retrying in 30 minutes...

and it goes on and on.
Anything what i could do?

Thanks!

**Comment by andryyy** [comment]
DNS is correct and IPv6 (if in DNS) is reachable?

**Comment by develth** [comment]
Yes, for all Domains that should be configured

**Comment by develth** [comment]
For example, acme client says

> Confirmed A record autodiscover.mydomain.de
> Found A record for autodiscover.mydomain.de: 1.2.3.4

Further messages:


> acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating) acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating) acme-client: adding SAN

Then a list with my approx. 80 Domains (each with autoconfig + autodiscover) follow with adding SAN, ends with

> created acme-client: https://acme-v01.api.letsencrypt.org/acme/challenge/QQliRtfTZIKNzB cfwbZcB8aktnjC6fIBpQ-iUKZZnw/3139746646: challenge acme-client: 1Jrfvi5xZ55szBdrYbi7ArMNF50kXijXYqFrB-X24Iw: File exists acme-client: bad exit: netproc(7204): 1 acme-client: bad exit: challengeproc(7207): 1

**Comment by develth** [comment]
Almost all Domains where ok, but one had a wrong DNS Setup that resolved that no cert could be created.

**Comment by andryyy** [comment]
Need more infos. Shouldn’t be a problem. Except for broken IPv6

**Comment by develth** [comment]
Was in logs, just didn´t checked for other domain fails.

But now experienced another problem when added > 20 Domains and having more then 100 Domains.

**Comment by andryyy** [comment]
The posted excerpts don't help at all.

ACME still validates what it found to be healthy. Again: The only reason it still fails is a broken IPv6 config (that's _not_ in the logs) or a broken reverse proxy config.

**Comment by develth** [comment]
Ok, because the first error disappeared when i added the correct DNS settings to the one Domain.
Will go further. Thanks
