### ISSUE TITLE
Problem with portainer

### ISSUE THREAD

**Issue by jimmyr57000** [mailcow/mailcow-dockerized#944]
Hello,

I would like some help with DNS forwarding via cloudfare.

I am totally lost.

Thank you in advance.

**Comment by MAGICCC** [comment]
What is the issue?
Just set the proper A/AAAA and MX records for your domain. You may look into the [cloudflare docs](https://support.cloudflare.com/hc/en-us/articles/200169096-How-do-I-add-A-records-)

**Comment by jimmyr57000** [comment]
Hello, 

problem solved thanks! 

Other question:

I followed this to activate portainer

How to update all? I have to reinstall everything?

https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

Thank you

**Comment by MAGICCC** [comment]
The easiest way to upgrade mailcow is to run the `update.sh` script

**Comment by jimmyr57000** [comment]
just like to update the files I've changed in /root/mailcow-dockerized/data/conf/nginx/site.conf for activate portainer

I would like the container to take into account the modifications!

https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

the update.sh does not change anything ..
http://mail.funmc.fr/portainer/ :(

Thanks you!

**Comment by andryyy** [comment]
You can just use update.sh and your modifications will be merged, if there is no conflict. In case of a conflict, mailcows code is prefered.

**Comment by jimmyr57000** [comment]
Thanks you!

Working :)

**Comment by jimmyr57000** [comment]
I have another problem sorry 👎, 

I've created some mails, i can connect to it, but my friends can't. I have changed password, but it doesn't work.
I live in France, and he live in Belgium, does it come by that?

He can acceed to it only by VPN, but it's not easy for him

Thanks you for your help

**Comment by jimmyr57000** [comment]
Up

**Comment by Braintelligence** [comment]
Please post your full system specs, DNS settings (you can mask IPs and domains for privacy reasons, just give them a recognisable name), and mailcow logs (check docs how to retrieve them in the mailcow gui).
