### ISSUE TITLE
Rmilster is obsoleted (since rspamd 1.6)

### ISSUE THREAD

**Issue by klausenbusk** [mailcow/mailcow-dockerized#945]
I just stumbled on this, on rspamd website:

> RMILTER IS OBSOLETED SINCE RSPAMD 1.6
> OBSOLETION WARNING!
> From Rspamd 1.6, this project is obsoleted by milter protocol implementation in rspamd proxy. You should NOT use it in any new projects, there will be completely no updates (including bugfixes) and the compatibility with Rmilter is guaranteed merely unless Rspamd 1.7 release! Please switch to Rspamd proxy.
> Historically, Rmilter supported many other features besides Rspamd integration. So far, all these features are implemented in Rspamd which allows to simplify integration with different MTA (e.g. Exim, Haraka or other non-milter compatible servers). Therefore, if you use this functionality you should consider switching it to Rspamd where all equal features are usually better implemented and have active and actual support.

https://www.rspamd.com/rmilter/

**Comment by MAGICCC** [comment]
Since mailcow [fetches ](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/rspamd/Dockerfile#L13) the latest rspamd from [its repositories](https://rspamd.com/apt/dists/xenial/main/) it uses 1.7.0-git.x and thus we don't need to change anything.

**Comment by klausenbusk** [comment]
> Since mailcow fetches the latest rspamd from its repositories it uses 1.7.0-git.x and thus we don't need to change anything.

I see, this is a doc issue then. I got confused by https://mailcow.github.io/mailcow-dockerized-docs/ which mentions `Rmilter`.

**Comment by MAGICCC** [comment]
Ah I see, should be removed I guess
