### ISSUE TITLE
Two copies of main.cf

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#949]
Hello,
I see that the postfix container has two copies of main.cf:
1.	/etc/postfix/main.cf
2.	/opt/postfix/conf/main.cf

I know that to customize postfix I need to edit (2) but running postconf -e (1) gets modified. Is that as designed?
At least in my case, it is getting confusing as I am used to use postconf to check if my configuration is ok

**Comment by andryyy** [comment]
Hi,
You should always edit data/conf/postfix/main.cf for persistent changes or define "-c /opt/postfix/conf" when running postconf, for example `postconf -c /opt/postfix/conf something`.

Edit: We should create an alias in the container to prevent this. 👍

**Comment by catcun** [comment]
@andryyy
Awesome that will do it, thank you
