### ISSUE TITLE
Random mysql crashes

### ISSUE THREAD

**Issue by RomkaLTU** [mailcow/mailcow-dockerized#952]
Installed clean OS from Digitalocean image with docker on Ubuntu, installed mailcow, configured, no problems here, bus I constantly  getting this error:

```
Connection to database failed.
The following error was reported:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

Absolutely random crashes, this is sooo fcking annoying, before used Mailcow 0.xx for 2 years without any problem...I don't understand what is advantages of Docker except free headache. Considering to go back to 0.14.

**Comment by andryyy** [comment]
Need more info. Does SQL crash? Does name resolution just fail?

**Comment by RomkaLTU** [comment]
Where should i search for logs?

**Comment by andryyy** [comment]
I can have a look via AnyDesk, not too sure what exactly fails. Would be much faster. 👍

**Comment by RomkaLTU** [comment]
I could check logs but I don't know where to find it, obviously there's no logs in /var/logs

**Comment by andryyy** [comment]
You find that in the docs. Check mysql-mailcow logs. Check your syslog for oom kills etc.

**Comment by RomkaLTU** [comment]
I can only see current mysql logs no logs before restart. And anything in syslog about oom kills just a couple of lines like

`#011/go/src/github.com/containerd/containerd/metrics/cgroups/oom.go:98 +0x7d`

I think this is mysql problem could be great to have latest mailcow without docker.

**Comment by andryyy** [comment]
Logs are saved over restarts and are only purged when recreating the container.

We would have a lot of problems with SQL without Docker. Many people assume they can install SQL and they are ready to use it for everything that needs SQL. We need Barracuda and some other settings that are not default in SQL installations. You can also not just switch between versions and hope it will just work somehow. That's only ONE reason we use Docker.

I offered you to have a look at it and you didn't even bother to check the docs for debugging. System info is missing, too. I am willing to help, but.....

You most likely run out of RAM. No, that's not Docker related. That's SOGo and ClamAV sucking on resources. Reduce the worker count in data/conf/sogo/sogo.conf or disable/outsource ClamAV and you are fine.

**Comment by Braintelligence** [comment]
@RomkaLTU , @andryyy is offering you real-time support free of charge, why don't you say thank you and take up on his offer? Why do you not post your system specs or at least a remotefully useful log?

Switching mailcow to docker is the best thing to happen since sliced bread. It takes so much configuration hassle out of setting up a powerful mail server and it's incredible and out of the ordinary that we get this for free. If you're not content with what's offered, then create a PR on the non-dockerized mailcow or pay someone to do it, because I don't think that the maintainers will ever touch it in its old form again, and rightfully so.

**Comment by RomkaLTU** [comment]
I have 1G RAM, it's possible that I run out of RAM, maybe enabling swap partition could help? I will also try to disable Sogo and antivirus if I find how to do it in documentation, I think I need to disable docker container and prevent it from auto start.

I miss read support offer I rather do it myself. And I didn't complain about docker I just asked why, I using docker in development but not in production.

**Comment by Braintelligence** [comment]
1GB RAM is the absolute minimum to run mailcow. If I remember correctly then this is not enough for running SOGo and ClamAV as well, at least not without a swap file.
As recommended here https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-system/#minimum-system-resources you should use swap.

If you set up docker correctly, then there's no implication why you should hesitate to use it in production. Even more so, if the underlying project is maintained by security-conscious people like @mkuron .

EDIT: The 1GB RAM are the absolute minimum for a system that is meant to run mailcow **only**. If you have anything else running there, then this is bound to create problems.

**Comment by RomkaLTU** [comment]
Thanks for the help I will try to disable Sogo and Antivirus and will confirm if that helped (2-3 days without crashes).

**Comment by RomkaLTU** [comment]
Ok so I deleted all configurations where sogo and clamd mentioned in docker-compose.yml restarted server but still sogod and clamd booting up...Searched documention clear instructions how to disable something, didn't find. What I missed here?

**Comment by andryyy** [comment]
All configuartion files where it is mentioned? That's not good.

SKIP_CLAMD=y in docker-compose.yml for Clam.

Just set WOWorkersCount = "2"; in `data/conf/sogo/sogo.conf` for SOGo, that's good.

Run `docker-compose up -d --remove-orphans` if you deleted containers from docker-compose.yml or just `docker-compose up -d` if you changed SKIP_CLAMD.

**Comment by RomkaLTU** [comment]
Ok it seams that clamd was already disabled, changed WOWorkersCount to 2 and memory usage dropped by 200 MB, so now it's about 550MB

Need to mention that SKIP_CLAMD=y should be in mailcow.conf not in docker-compose.yml

Hope that helps, thanks for the help.

**Comment by marrco** [comment]
considering that "A value of 3 is a reasonable default for low usage. (....) Defaults to 1 when unset. " for WOWorkersCount according to https://sogo.nu/files/docs/SOGoInstallationGuide.html isn't CM-D default of 20 too high?

should I open a PR to have it set to 3 (or even to 1) or is there a reason to keep such a higher default?

**Comment by andryyy** [comment]
I already set this lower value in dev (uncommited).

3 is not enough considering people use ActiveSync for more than 3 mailbox acounts... Workers will be blocked until they reach their ttl or a memsize limit. I've set it to 7, which is still pretty low, imo. :-/
