### ISSUE TITLE
IMAPSync option enhancement request

### ISSUE THREAD

**Issue by Lucky88888** [mailcow/mailcow-dockerized#955]
Hi, 

First of all - really great job you and your team have done with this mailserver solution in a container! Thanks!

I have an enhancement request for the IMAP Sync option. I am not yet that familiar with Docker so I am not going to post the solution. Maybe later. 
On de FAQ's of the developer site of the IMAPSync code there are different settings proposed for different mail service providers. One of them is Gmail. I am currently in the process of migrating from Google Apps to Mailcow and notice that the migration (sync) is running against the hard limits of google. Lamiral has some tips, tweaks & tricks for that. 
See http://imapsync.lamiral.info/FAQ.d/  

Would it be possible to introduce a selectable foreign mail povider list and with that getting the best settings and configurations for the imapsync command? 

Thanks in advance. 

KR, Lucas.

**Comment by andryyy** [comment]
Hi, I just added options for automap, maxbytespersecond and skipcrossduplicates. Thanks to @gilleslamiral whom I finally forwarded a donation from mailcow to. 👍 👍

**Comment by Lucky88888** [comment]
@andryyy Thanks Andre. What would be the best option to retrieve this update?

**Comment by andryyy** [comment]
Waiting for a dev => master merge. But we will hurry!

**Comment by Lucky88888** [comment]
Just dit the update, and checked.
If I click on an adit of a sync task I get a screen where it starts dumping the array:
`Array ( [id] => 3 [user2] => info@.........`
