### ISSUE TITLE
DNS-entries

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#956]
Hi guys,

what's wrong here

![bildschirmfoto 2018-01-24 um 15 06 48](https://user-images.githubusercontent.com/25169532/35336657-625a793e-0119-11e8-9f95-8b4dcd461072.jpg)

The same is to ports
110, 443, 143, 465, 587, 993, 995, 4190.

My entries are e.g. ....
host: _imaps._tcp
typ: srv
prio: 0
weight: 1
data: mx1.domain.de

All others are green

regards
jm3west

**Comment by mkuron** [comment]
That’s a TLSA record, which shpuld contain a hash of your SSL public key. It is used for DANE email encryption and with some browser plugins to validate the SSL certificate. Even though it looks similar to an SRV record, it isn’t one.
