### ISSUE TITLE
Rename BACKUP_LOCATION env var to MAILCOW_BACKUP_LOCATION?

### ISSUE THREAD

**Issue by incyclum** [mailcow/mailcow-dockerized#957]
Because if you use that environment variable inline when using the helper script there's no problem,
but if you want to reuse (export) that var system wide (e.g. using it afterwards in a script or a rclone command), that var should be more precise, meaningful.

So I suggest using MAILCOW_BACKUP_LOCATION.

**Comment by incyclum** [comment]
Does someone can take a look on what can be done and side effects on this one?

**Comment by andryyy** [comment]
I will add it, thanks for reminding me. :-)
