### ISSUE TITLE
Portainer not available after update

### ISSUE THREAD

**Issue by wtrdk** [mailcow/mailcow-dockerized#958]
I've just update using update.sh. There were no errors reported.
After the update everything works just fine, but Portainer seems to be gone!
When I go to https://mail.mydomain.com/portainer I get a 404 error.

This worked fine until the update. Does anyone have a clue?

**Comment by MrJacK67** [comment]
See here :

[https://github.com/mailcow/mailcow-dockerized-docs/blob/master/docs/third_party-portainer.md](url)

**Comment by Braintelligence** [comment]
@MrJacK67 Your link doesn't work.

**Comment by Braintelligence** [comment]
@wtrdk Maybe this helps? https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/

**Comment by wtrdk** [comment]
That worked, but when I log in to portainer, I get an 'Failure, endpoint not found' error. After another reboot it worked!
