### ISSUE TITLE
Question to mailcow used components and there updates

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#959]
Based on an article from heise.de about a security problem in [clamav](https://www.heise.de/security/meldung/Jetzt-patchen-Angriffe-auf-Viren-Scanner-ClamAV-3951801.html), i am not sure what i can do in this case.

The second example is the SOGo version, which stays on an older version then SOGo offers on there website. Are there any reasons why it is, like it is?

**Comment by andryyy** [comment]
We use the latest nightlies for SOGo (3.2.10) with the upcoming 4.0 SQL patches.

Regarding ClamAV I don't see any updates, yet. We could build ClamAV from source, though...

**Comment by lgusewski** [comment]
To SOGo, had a second look to there history and realized that i was misleaded through there mix of version 3 and version 2 release notes in one list.

**Comment by Braintelligence** [comment]
@andryyy Are there any news regarding groups as SQL objects for SOGo? :)

**Comment by andryyy** [comment]
I don’t think that’s possible in sql

**Comment by lgusewski** [comment]
[Golem](https://www.golem.de/news/virenscanner-clamav-hat-zahlreiche-schwachstellen-1801-132417.html) is writing about this problem, too.
What do you recommend? Changing the mailcow.conf and disable ClamAV in the moment?

**Comment by andryyy** [comment]
Yes, disable it until we have a patched ClamAV.

**Comment by lgusewski** [comment]
I changed in mailcow.conf the line SKIP_CLAMD=n to SKIP_CLAMD=y and made an ./update.sh. After the restart, i see again a runing clamd-mailcow container in the administrator UI under debugging / containers. Start time is equal to the update time after my change in the config. Was this not the correct way to disable ClamAV?

**Comment by andryyy** [comment]
Run docker-compose up -d afterwards. The container will idle (a bash) but not be used.
