### ISSUE TITLE
broken SoGo

### ISSUE THREAD

**Issue by fibis** [mailcow/mailcow-dockerized#96]
After an update of my installation with the steps in the manual is my SoGo broken. On the left site are the folders of the e-mail account not shown, but under contacts you can see the contact books. Also the green button is always on the wrong position:
![screenshot-mail](https://cloud.githubusercontent.com/assets/7265809/23592625/2c71b55e-0204-11e7-98d0-312a26d9a7d3.png)

The Folders are still there when I try to view the mails with thunderbird. What could be the fault of this?

**Comment by broedli** [comment]
I cannot reproduce this issue and without any logs it is pretty much impossible to help. (`docker-compose logs service-mailcow`)
Did you try to restart mailcow-dockerized? (`docker-compose restart`)

**Comment by marrco** [comment]
i had a similar issue last week: https://github.com/andryyy/mailcow-dockerized/issues/74 and an other user added more info too.
