### ISSUE TITLE
Blacklists are not working at all

### ISSUE THREAD

**Issue by thalic** [mailcow/mailcow-dockerized#960]
Since the latest master commits, Blacklists are not working at all. We have "*@twitter.com" scope "user@mydomain.com" and scope "mydomain.com" in the Blacklist, but mails from twitter.com (and all other blacklisted) going through. This worked @  master with "Commits on Dec 26, 2017".

"MAILCOW_BLACK (999)" is not in the rspamd debug log as it was before.

Thank you.

**Comment by andryyy** [comment]
Can you post your Rspamd map, please? Or mail it to info@servercow.de.

Is watchdog running?

**Comment by andryyy** [comment]
I think I know the reason it stopped working... :-/ You'd need to add a second filter for '*@*twitter.com' until I fixed it.

**Comment by thalic** [comment]
Great that you have found the problem!
Unfortunately, I am not very familiar with the internal structure of rspamd. Which file (file name) is the rspamd-map which you would like to have?

**Comment by andryyy** [comment]
Should work without seeing the map file. :-)

Can you please run `wget -O data/conf/rspamd/dynmaps/settings.php https://raw.githubusercontent.com/mailcow/mailcow-dockerized/dev/data/conf/rspamd/dynmaps/settings.php` ?

That should fix it.

**Comment by thalic** [comment]
Wow that was quick! Got the file, will report tomorrow (need to get some blacklisted mail). 
Thanks!

**Comment by thalic** [comment]
Ok, after some testing: the patch did **not** fix the problem. I added `*@gmx.de` to the Blacklist - no blocking. Added `*@*gmx.de` - blocking. I did a full restart of the mailcow Server after wget-ing the file.

**Comment by thalic** [comment]
I did a full update with the latest code you commited seconds ago - it now works. Thanks again.

**Comment by andryyy** [comment]
Nice! It also takes a few seconds (up to 1-2 minutes) to fully read the settings map.
