### ISSUE TITLE
IPV4_NETWORK variable is never set

### ISSUE THREAD

**Issue by volcomism** [mailcow/mailcow-dockerized#964]
In the recent commit, you've added IPV4_NETWORK as a variable - but it's never set by any of the populating shell scripts.

Resulting in docker-compose error: 
`ERROR: Invalid subnet .0/24 : invalid CIDR address: .0/24`

https://github.com/mailcow/mailcow-dockerized/commit/4f2d9bc48e8c83db06c10a7075016d24f0db785e

**Comment by lgusewski** [comment]
Had also the problem with the IPV4_NETWORK and IPV6_NETWORK vars.
After docker-compose up -d i get:

`WARNING: The IPV4_NETWORK variable is not set. Defaulting to a blank string.
WARNING: The IPV6_NETWORK variable is not set. Defaulting to a blank string.
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
ERROR: Invalid subnet .0/24 : invalid CIDR address: .0/24`

Trying the IP from the vServer seems not the right value. Now my mailcow is actually dead. I also tried to generate a new mailcow.conf to see what should be the default values, but the script generator did not add something into the new mailcow.conf file.

**Comment by andryyy** [comment]
Damn... it is fixed, sorry!! I was in a hurry to fix that ClamAV issue....

**Comment by anoshop** [comment]
@andryyy ,
When time you plan to release FIxed VERSION ?

I also meet with this trouble now .
----------------

root@XXX:~/mailcow-dockerized# docker-compose up -d
WARNING: The IPV4_NETWORK variable is not set. Defaulting to a blank string.
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The IPV6_NETWORK variable is not set. Defaulting to a blank string.
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
**ERROR: Invalid subnet .0/24 : invalid CIDR address: .0/24**

**Comment by Braintelligence** [comment]
@jekyllcao This is already fixed by a commit if I'm not mistaken. I have no problems running the latest mailcow currently.

**Comment by lgusewski** [comment]
It is fixed. Run ./update.sh again and your mailcow should work.
