### ISSUE TITLE
Update generate_config.sh according to the changes for update.sh

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#965]
Since https://github.com/mailcow/mailcow-dockerized/commit/1f1ab0960c7d118d15fcd86a348885e399f4dd47 update.sh includes new variables, but generate_config.sh doesn't have them, a fresh mailcow instance fails to install before executing update.sh

I would fix it with a PR, but currently no time to do it

**Comment by andryyy** [comment]
Thanks, fixed it. Sorry for that mess (again).

**Comment by Braintelligence** [comment]
@andryyy I wish I had an army of people spotting mistakes in my projects 😂 . 👍 A ton of people are using mailcow, you should be proud 😸.

**Comment by andryyy** [comment]
I am, I love you guys! 👍

**Comment by Braintelligence** [comment]
@andryyy By the way, if possible it would be great if you could open an Ethereum and Litecoin account for donations 😸. (Better for small donations due to cheaper transaction costs.)

**Comment by catcun** [comment]
Feels like an army of people is continuously fixing and improving mailcow! The level of support is amazing.
Congrats @andryyy
