### ISSUE TITLE
Non-null host address bits in "fd::/8"

### ISSUE THREAD

**Issue by itlabs-eu** [mailcow/mailcow-dockerized#967]
Hello,

I've updated my mailcow server today and now I can't send or receive emails. From postfix logs:

warning: postscreen_access_list: non-null host address bits in "fd::/8", perhaps you should use "::/8" instead
warning: postscreen_access_list: permit_mynetworks: mynetworks lookup error -- ignoring the remainder of this access list
PASS NEW [2607:f8b0:400d:c09::233]:40565
connect from mail-qk0-x233.google.com[2607:f8b0:400d:c09::233]
warning: smtpd_client_event_limit_exceptions: non-null host address bits in "fd::/8", perhaps you should use "::/8" instead
Anonymous TLS connection established from mail-qk0-x233.google.com[2607:f8b0:400d:c09::233]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
warning: mynetworks: non-null host address bits in "fd::/8", perhaps you should use "::/8" instead
NOQUEUE: reject: RCPT from mail-qk0-x233.google.com[2607:f8b0:400d:c09::233]: 451 4.3.0 <mail-qk0-x233.google.com>: Temporary lookup failure; from=<myemail@gmail.com> to=<myotheremail@mydomain.com> proto=ESMTP helo=<mail-qk0-x233.google.com>
warning: smtpd_client_event_limit_exceptions: non-null host address bits in "fd::/8", perhaps you should use "::/8" instead

I've noticed that some new lines were added to mailcow.conf:

```
# Internal IPv4 /24 subnet, format n.n.n. (expands to n.n.n.0/24)
IPV4_NETWORK=172.22.1
# Internal IPv6 subnet in fd00::/8
IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
# Max log lines per service to keep in Redis logs
LOG_LINES=9999
```

Perhaps something to do with IPV6_NETWORK?

Thanks
Regards,
Marcelo

**Comment by andryyy** [comment]
Sorry, forget it, will check it now...

**Comment by andryyy** [comment]
Damn. Should be fixed now.

**Comment by itlabs-eu** [comment]
Yep, it works! Tks @andryyy
