### ISSUE TITLE
SOGo Integrator and CalDAV not working

### ISSUE THREAD

**Issue by levinuss** [mailcow/mailcow-dockerized#968]
Hey,
I built the latest third party plugins according to @mkuron s instructions in the (to be merged) [PR #33 in mailcow-dockerized-docs](https://github.com/mailcow/mailcow-dockerized-docs/pull/33). Everything worked fine, all addons were build right and I was able to download the SOGo Integrator 31.0.6 .xpi for Thunderbird for one of my two domains. I could install it into Thunderbird (52.6.0 on Ubuntu) and it showed up in the addon overview after a restart. But: Nothing happens. I am not asked for any passwords as suggested by the manual, I don't see any new calendars or address books. Any idea why? The account I want to config is successfully installed into Thunderbird, I can read and send mails and its set as the default account.
I wanted to try to get at least the calendar over DAV. So I configured a new network calendar in Thunderbird with "https://mailcow.mydomain.tld/SOGo/dav" (working for me with DAVdroid). I was asked for a password and a username. After confirming the new calendar was created but not available. I tried to sync it manually but did not work either.
I did notice some warnings in the SOGo log:
```
[34]: [WARN] \|SOGo\| tried to access undefined KVC key: 'davCollectionTag'
[34]: [WARN] \|SOGo\| tried to access undefined KVC key: 'davCalendarComponentSet'
[34]: [WARN] \|SOGo\| tried to access undefined KVC key: 'davOwner'
[34]: [IPv6] "PROPFIND /SOGo/dav/ HTTP/1.0" 401 0/306 0.001 - - 0
```

Am I making it wrong or what could be the problem here?

**Comment by mkuron** [comment]
> Everything worked fine, all addons were build right and I was able to download the SOGo Integrator 31.0.6 .xpi for Thunderbird for one of my two domains.  I could install it into Thunderbird (52.6.0 on Ubuntu) and it showed up in the addon overview after a restart. But: Nothing happens.

Could you rename the .xpi to .zip, unpack it and look for the extensions.rdf inside? It should contain your server's URL in multiple places. Please check whether these URLs are correct.

> I wanted to try to get at least the calendar over DAV. So I configured a new network calendar in Thunderbird with "https://mailcow.mydomain.tld/SOGo/dav" (working for me with DAVdroid). I was asked for a password and a username. After confirming the new calendar was created but not available. 

That is expected behavior. You need the full URL to the specific calendar, which you can copy by logging into the SOGo web interface and clicking the three dots next to the calendar. If you have Integrator installed and working, it will automatically create all calendars for you.

**Comment by levinuss** [comment]
I was able to edit the extension with the vim.zip addon. The update URL was wrong, the domain was missing ("https:///thunderbird-plugins.php?..."). I added the right one and it finally worked!
Thank you for your support and the guides, @mkuron!

**Comment by mkuron** [comment]
That sounds like you ran
```
echo example.com example.org | ./build-plugins.sh
```
instead of the correct
```
echo example.com example.org | ./build-plugins.sh mailcow.example.com
```

**Comment by levinuss** [comment]
Yes, you are right. Looks like I overlooked the argument in both the wirtten text and the command... My fault, sorry to bother you!

**Comment by mkuron** [comment]
Thanks anyway for testing my instructions. I‘ll add a check for the missing argument and then finally merge the pull request to the documentation.

**Comment by rototom** [comment]
Same problem here, but my update url seems to be ok ("isi:updateURL="https://mail.myserver.de/thunderbird-plugins.php?domain=mydomain.de&amp;plugin=%ITEM_ID%&amp;version=%ITEM_VERSION%&amp;platform=%PLATFORM%">"

**Comment by mkuron** [comment]
@rototom, update URL isn‘t the only field required. If you upload your xpi file here, I can have a closer look.

**Comment by rototom** [comment]
sogo-integrator-31.0.6-*****.net.zip

**Comment by mkuron** [comment]
@rototom, this looks fine. After I downloaded the file, I've deleted it from Github in case you wanted to keep your domain name private.

Are you seeing any requests in the nginx log when you start Thunderbird? Did you create the IMAP account in Thunderbird before installing the plugin?

**Comment by rototom** [comment]
I first enabled the imap account, than installed the plugin.
Here are some logs: 
`
nginx-mailcow_1      | 5.147.150.44 - - [16/Apr/2018:15:48:48 +0000] "GET /thunderbird-plugins.php?domain=mydomain.tld&plugin=sogo-integrator@inverse.ca&version=31.0.6&platform=Linux_x86_64-gcc3 HTTP/1.0" 200 869 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.6.0"
nginx-mailcow_1      | 5.147.150.44 - - [16/Apr/2018:15:48:48 +0000] "GET /thunderbird-plugins.php?domain=mydomain.tld&plugin=sogo-connector@inverse.ca&version=31.0.6&platform=Linux_x86_64-gcc3 HTTP/1.0" 200 855 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.6.0"
nginx-mailcow_1      | 5.147.150.44 - - [16/Apr/2018:15:48:48 +0000] "GET /thunderbird-plugins.php?domain=mydomain.tld&plugin=sieve@mozdev.org&version=0.2.12&platform=Linux_x86_64-gcc3 HTTP/1.0" 200 837 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.6.0"
nginx-mailcow_1      | 5.147.150.44 - - [16/Apr/2018:15:48:48 +0000] "GET /thunderbird-plugins.php?domain=mydomain.tld&plugin=imap-acl@sirphreak.com&version=0.2.7&platform=Linux_x86_64-gcc3 HTTP/1.0" 200 857 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.6.0"`

**Comment by mkuron** [comment]
Looks fine. It's checking for all the plugins, which are probably up to date already as I don't see any .xpi files being downloaded. Did you check whether your calendar/contacts have been set up already, without you being asked for the password? Also, you can try deleting your Thunderbird profile and starting over -- maybe there are some conflicting old settings.

**Comment by rototom** [comment]
I started all over with no success, no addressbooks, no calendar.

**Comment by rototom** [comment]
Here are the logs from thunderbird:
https://code.okaris.de/kezojagebi

**Comment by mkuron** [comment]
It looks like an essential part of SOGo connector is missing (sogoWebdav.js). Could you upload your connector xpi so I can have a look? https://sogo.nu/bugs/view.php?id=2836 Looks like it's the same problem, but on an older version. In any case, I cannot reproduce this issue with my server.

**Comment by rototom** [comment]
[sogo-connector-31.0.6.zip](https://github.com/mailcow/mailcow-dockerized/files/1916606/sogo-connector-31.0.6.zip)

**Comment by rototom** [comment]
It works with connector 17.0.6, but this one gets updated to the latest (defunctioning one) automatically, when I'm using my generated xpi...

**Comment by mkuron** [comment]
17.0.6 is almost five years old, so many things probably don‘t work anymore. 31.0.6 is working for me, so I don‘t know what‘s wrong. You could try other versions in between, perhaps even bisecting to the exact commit that breaks it for you. Just replace master in the build script with the appropriate commit hash from https://github.com/inverse-inc/sogo-connector.tb31/commits/master.

**Comment by mkuron** [comment]
https://lists.inverse.ca/sogo/arc/users/2018-01/msg00072.html -- do you have the Lightning extension installed? That's default in the Windows and macOS versions of Thunderbird, but Linux might be different.

**Comment by rototom** [comment]
Thank you very much! That did the trick. I use Linux and didnt have lightning installed.
Perhaps this should be mentioned in the docs?

**Comment by mkuron** [comment]
@rototom, I just did: https://github.com/mailcow/mailcow-dockerized-docs/commit/fa0d7d270bbf564226b493856e6925d808e3e232 . Thanks for reporting the issue and helping us figure out what was causing it.

**Comment by majacal** [comment]
hi

why is it necessary to set the account as the default account in thunderbird?
step 7

> If you already had other accounts configured in Thunderbird, select the new one () on the left, click the Account Actions dropdown and select Set as Default.

-matthias

**Comment by mkuron** [comment]
@matthiashertel, that's a SOGo limitation. Integrator only supports a single account and it assumes the default account to be the one.

**Comment by majacal** [comment]
@mkuron 
ok that means u can use only one account ?

**Comment by mkuron** [comment]
You don't even need more than one. Just log into the SOGo web UI with your other accounts and share your address books and calendars with your main account. They'll then show up in your main account in Thunderbird. If you need email too, just add them as plain IMAP accounts to Thunderbird.
