### ISSUE TITLE
Web interface (nginx & rspamd) does not work after update

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#969]
Hi,

I have a problem again. 

After an update, my server's web interface does not work. SMTP and IMAP work just fine with valid certs, but webamail adn webadmin are offline.

I am getting emails from watchdog about nginx and rspamd. So I restarted Nginx with checking his logs and i got just thsi message repeated:

![image](https://user-images.githubusercontent.com/9658012/35476922-593e4c2a-03b9-11e8-86c1-a0f6b97c4d0f.png)

then I tried the same with rspamd (it's longer and tells me nothing, but there is something about nginx:
![image](https://user-images.githubusercontent.com/9658012/35476943-969a14fa-03b9-11e8-8bba-2c4cccb62b54.png)

Thanks for your help again.

**Comment by mkuron** [comment]
Possible duplicate of https://github.com/mailcow/mailcow-dockerized/issues/962#issuecomment-361002832 ?

**Comment by DJIronic** [comment]
Yes, it was it.  Sorry for missing the thread :(

Thank you for your help.

**Comment by DJIronic** [comment]
OK, Sorry for re-opening this thread, but I just found out that this update broke my exchange connection. SMTP and IMAP are just fine, but every Exchange got disconnected and kicking me with an error or bad password. I changed the password and I am sure I put the right one there (tested multiple times with new passwords).

**Comment by Braintelligence** [comment]
@DJIronic Does this help: https://github.com/mailcow/mailcow-dockerized/issues/962#issuecomment-360981161

**Comment by DJIronic** [comment]
Yes, it helped with my nginx, mailcow admin and rspamd work just fine, but still have the issue with wrong password with SOGo & Exchange mail clients (android Gmail app).

Roundcube and  windows Outlook (with SMTP/IMAP connection( work just fine.

PS: I can't see any resolution of the SOGo & Exchange problem in the thread you shared. I did the edit in Nginx conf.

**Comment by mkuron** [comment]
Try restarting SOGo (`docker-compose restart sogo-mailcow`).

**Comment by DJIronic** [comment]
I can confirm, that worked! Thanks :)

**Comment by Braintelligence** [comment]
@DJIronic My link was about freshly cloning the repo, but I'm glad restarting sogo was all it took.
