### ISSUE TITLE
hide accounts of other domains

### ISSUE THREAD

**Issue by fibis** [mailcow/mailcow-dockerized#97]
Is there any possibility that a user can only see in SoGo Accounts of his own domain and not of the other domains, that are running on the same installation?

**Comment by broedli** [comment]
Have a look at the sogo [documentation](https://sogo.nu/files/docs/SOGoInstallationGuide.html#_multi_domains_configuration).
There is also this part in [sogo.conf](https://github.com/andryyy/mailcow-dockerized/blob/master/data/conf/sogo/sogo.conf#L18-L25) that hints at that function. But I haven't tested or tried it yet ...

**Comment by andryyy** [comment]
It already does.
