### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by nickian** [mailcow/mailcow-dockerized#974]
I had mailcow running just fine on a Digital Ocean server, then I hit 100% disk space and started getting errors so I had to create a new, larger server from a snapshot of the old mailcow one. I updated DNS/IPs, but now I'm getting this error when I try to go to my domain:

> **Proxy Error**
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /SOGo.
> 
> Reason: DNS lookup failure for: 127.0.0.1:8080sogo
> 
> Apache/2.4.18 (Ubuntu) Server at mydomain.com Port 443

Everything looks like it is running correctly when I run `docker ps -a`, so I'm not sure what's going on here.

I also ran the `update.sh` and `generate_config.sh` but that didn't seem to help.

Thanks!

**Comment by nickian** [comment]
Oops. It looks like I was running Apache in front of all of this. I stopped the Apache service, but now I just get a timeout/site not available error in my browser.

**Comment by nickian** [comment]
nginx is stuck in this state `b739c5b5d02f        nginx:mainline-alpine   "/bin/sh -c 'envsu..."   19 minutes ago      Restarting (1) 4 seconds ago`

**Comment by MAGICCC** [comment]
`docker ps -a` shows **every** container even when they are turned off. You may use `docker ps` or `docker-compose ps` or `docker info | grep Running` (this should output 16 containers when you use the default configs).
You may want to remove Apache and be sure nothing else is blocking ports, then you can try to start the containers and check their logs again

**Comment by nickian** [comment]
Thanks! Yes, removing Apache and restarting the nginx container did the trick.
