### ISSUE TITLE
[feature] separate sogo container for ActiveSync

### ISSUE THREAD

**Issue by lavdnone** [mailcow/mailcow-dockerized#976]
cellphones eat it bad
timeouts and other settings differ too much between webmail and ActiveSync
https://sogo.nu/files/docs/SOGoInstallationGuide.html#_microsoft_enterprise_activesync_tuning

such approach is suggested by SOGo
https://sogo.nu/nc/support/faq/article/dedicated-separate-sogo-instance-for-activesync.html

**Comment by Braintelligence** [comment]
Second link doesn't work for me. 404

**Comment by compuguy** [comment]
@Braintelligence both links work for me. I would agree with this choice. Activesync seems to be a bit flaky.

**Comment by lavdnone** [comment]
Here is the full text of that page copy-paste. instructions from SOGo how to do it.

FAQ
How to dedicate a separate SOGo instance for ActiveSync
Installation

A second SOGo instance (sharing almost everything with the primary SOGo instance) can be deployed and dedicated for ActiveSync clients. As you many know, ActiveSync clients tend to aggressively hold on to their connections; that behavior may starve web interface clients. Setting up a second instance ensures web interface clients get their fair share of connections.

Below are the steps to create a second SOGo instance, which has exactly the same configuration as the primary one, except it listens on a different TCP port (30000 instead of 20000); Apache will forward ActiveSync requests to port 30000 while regular web interface clients will continue to be forwarded to port 20000.
RedHat 7

    Add a new system user (sogoeas) dedicated for the second instance:

 useradd -d /var/lib/sogoeas -g sogo -c "SOGo EAS daemon" \
 	-s /usr/sbin/nologin -r sogoeas 

1. Create the home GNUstep directory for the *sogoeas* user:

 mkdir -p /var/lib/sogoeas/GNUstep/Defaults 

1. Create a **/var/lib/sogoeas/GNUstep/Defaults/.GNUstepDefaults** file, containing this:

 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//GNUstep//DTD plist 0.9//EN" "http://www.gnustep.org/plist-0_9.xml">
 <plist version="0.9">
 <dict>
 	<key>NSGlobalDomain</key>
 	<dict>
 	</dict>
 	<key>sogod</key>
 	<dict>
 		<key>WOPort</key>
 		<string>30000</string>
 	</dict>
 </dict>
 </plist> 

1. Ensure a correct ownership of **/var/lib/sogoeas/GNUstep/Defaults/.GNUstepDefaults**:

 chown -R sogoeas:sogo /var/lib/sogoeas 

1. Create a systemd service file - **/usr/lib/systemd/system/sogod-eas.service** - for the second SOGo instance, containing this:

 [Unit]
 Description=SOGo is a groupware server (EAS)
 After=network.target
 After=mariadb.service
 
 [Service]
 EnvironmentFile=-/etc/sysconfig/sogo
 Type=forking
 ExecStart=/usr/sbin/sogod -WOWorkersCount 120 -WOPidFile /var/run/sogo/sogo-eas.pid -WOLogFile /var/log/sogo/sogo-eas.log
 PIDFile=/var/run/sogo/sogo-eas.pid
 User=sogoeas
 
 [Install]
 WantedBy=multi-user.target 

1. Make the *sogoeas* user able to read/write SOGo data:

 chmod 0640 /etc/sogo/sogo.conf
 chmod 0775 /var/run/sogo/ /var/lib/sogo/
 chmod 0770 /var/log/sogo/ 

1. Ensure that **/var/run/sogo** keeps its permissions at reboot; change this line in **/etc/tmpfiles.d/sogo.conf**:

	d /var/run/sogo 0755 sogo sogo

to:

        d /var/run/sogo 0775 sogo sogo 	

1. Modify your apache proxy configuration so that **/Microsoft-Server-ActiveSync** points to the secondary SOGo instance; change this line in **/etc/httpd/conf.d/SOGo.conf**:

 ProxyPass /Microsoft-Server-ActiveSync \
 	http://127.0.0.1:20000/SOGo/Microsoft-Server-ActiveSync \
 	retry=60 connectiontimeout=5 timeout=700 
```to:

ProxyPass /Microsoft-Server-ActiveSync
http://127.0.0.1:30000/SOGo/Microsoft-Server-ActiveSync
retry=60 connectiontimeout=5 timeout=700 ```You may also want to adjust the MaxRequestWorkers directive in Apache to accomodate the extra connections.

1. Start the secondary SOGo instance and restart Apache:

 service sogod-eas start
 service httpd restart 

Debian 8

    Add a new system user (sogoeas) dedicated for the second instance:

 useradd -d /var/lib/sogoeas -g sogo -c "SOGo EAS daemon" \
 	-s /usr/sbin/nologin -r sogoeas 

    Create the home GNUstep directory for the sogoeas user:

 mkdir -p /var/lib/sogoeas/GNUstep/Defaults 

    Create a /var/lib/sogoeas/GNUstep/Defaults/.GNUstepDefaults file, containing this:

 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//GNUstep//DTD plist 0.9//EN" "http://www.gnustep.org/plist-0_9.xml">
 <plist version="0.9">
 <dict>
 	<key>NSGlobalDomain</key>
 	<dict>
 	</dict>
 	<key>sogod</key>
 	<dict>
 		<key>WOPort</key>
 		<string>30000</string>
 	</dict>
 </dict>
 </plist> 

    Ensure a correct ownership of /var/lib/sogoeas/GNUstep/Defaults/.GNUstepDefaults:

 chown -R sogoeas:sogo /var/lib/sogoeas 

    Create a service file ? /etc/init.d/sogo-eas ? for the second SOGo instance, containing this:

 #!/bin/bash
 ### BEGIN INIT INFO
 # Provides: sogo-eas
 # Required-Start: $remote_fs $network
 # Required-Stop: $remote_fs $network
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
 # Short-Description: SOGo-EAS server
 ### END INIT INFO
 
 # SOGo init script for Debian GNU/Linux
 #
 # Copyright (C) 2007-2010 Inverse inc.
 #
 # Author: Wolfgang Sourdeau <wsourdeau@inverse.ca>
 # Ludovic Marcotte <ludovic@inverse.ca>
 #
 # This file is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2, or (at your option)
 # any later version.
 #
 # This file is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; see the file COPYING. If not, write to
 # the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 # Boston, MA 02111-1307, USA.
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
 NAME=sogo
 EASNAME=sogo-eas
 DAEMON=/usr/sbin/sogod
 DESC="SOGo-EAS"
 
 USER=sogo
 EASUSER=sogoeas
 PREFORK=120
 
 PIDFILE=/var/run/$NAME/$EASNAME.pid
 LOGFILE=/var/log/$NAME/$EASNAME.log
 
 if [ -f /etc/default/$NAME ]; then
 . /etc/default/$NAME
 fi
 
 . /lib/lsb/init-functions
 
 if [ ! -x $DAEMON ]; then
 log_failure_msg "$DAEMON is not executable."
 exit 1
 fi
 
 set -e
 
 . /usr/share/GNUstep/Makefiles/GNUstep.sh
 
 DAEMON_OPTS="-WOWorkersCount $PREFORK -WOPidFile $PIDFILE -WOLogFile $LOGFILE"
 
 case "$1" in
 start)
 log_daemon_msg "Starting $DESC" "$EASNAME"
 
 # Enforce directory existence and permissions
 install -o $USER -g $USER -m 775 -d /var/run/$NAME
 install -o $USER -g $USER -m 770 -d /var/spool/$NAME
 install -o $USER -g $USER -m 770 -d /var/log/$NAME
 
 if ! start-stop-daemon -c $EASUSER --quiet --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS 
 then
 log_progress_msg "already running"
 fi
 log_end_msg 0
 ;;
 stop)
 log_daemon_msg "Stopping $DESC" "$EASNAME"
 start-stop-daemon --stop --pidfile $PIDFILE --retry=TERM/20/KILL/5 --oknodo
 log_end_msg 0
 ;;
 restart|force-reload)
 log_daemon_msg "Restarting $DESC" "$EASNAME"
 start-stop-daemon --stop --pidfile $PIDFILE --retry=TERM/20/KILL/5 --oknodo
 # Ensure directory's existence and permissions
 install -o $USER -g $USER -m 775 -d /var/run/$NAME
 install -o $USER -g $USER -m 770 -d /var/spool/$NAME
 install -o $USER -g $USER -m 770 -d /var/log/$NAME
 start-stop-daemon -c $EASUSER --quiet --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS 
 log_end_msg 0
 ;;
 status)
 status_of_proc -p $PIDFILE "$DAEMON" $EASNAME && exit 0 || exit $?
 ;;
 *)
 echo "Usage: $EASNAME {start|stop|restart|status}" >&2
 exit 1
 ;;
 esac
 
 exit 0 </ludovic@inverse.ca></wsourdeau@inverse.ca>

    Make the service active and started at boot:

 chown root:root /etc/init.d/sogo-eas
 chmod 0755 /etc/init.d/sogo-eas
 systemctl enable sogo-eas 

    Make the sogoeas user able to read/write SOGo data:

 chmod 0640 /etc/sogo/sogo.conf
 chmod 0775 /var/run/sogo/ /var/lib/sogo/
 chmod 0770 /var/log/sogo/ 

    Modify your apache proxy configuration so that /Microsoft-Server-ActiveSync points to the secondary SOGo instance; change this line in /etc/httpd/conf.d/SOGo.conf:

 ProxyPass /Microsoft-Server-ActiveSync \
 	http://127.0.0.1:20000/SOGo/Microsoft-Server-ActiveSync \
 	retry=60 connectiontimeout=5 timeout=700 
```to:

ProxyPass /Microsoft-Server-ActiveSync
http://127.0.0.1:30000/SOGo/Microsoft-Server-ActiveSync
retry=60 connectiontimeout=5 timeout=700 ```You may also want to adjust the MaxRequestWorkers directive in Apache to accomodate the extra connections.

    Start the secondary SOGo instance and restart Apache:

 service sogod-eas start
 service httpd restart

**Comment by nightah** [comment]
Has anybody actually tried doing this with much success?
I anticipate it would help though I'm sure it would be easier to get someone to implement with qualified data support such.

**Comment by lavdnone** [comment]
we just add another docker container from mailcow/sogo
and tweak site.conf to point Active Sync to it

        location ^~ /Microsoft-Server-ActiveSync {
          proxy_pass http://172.22.1.252:20000/SOGo/Microsoft-Server-ActiveSync;
          proxy_connect_timeout 1000;
          proxy_next_upstream timeout error;

**Comment by bretsky84** [comment]
I think this is related to the errors I have neem seeing.  Updated mailcow-dockerized on Sunday and it knocked out Cal/CardDAV sync and mail to outlook clients.  I just adjusted the:
~/mailcow-dockerized/data/conf/nginx/site.conf
to match the above comment.  One thing I noticed was that I had trouble logging into SOGo with the notmal URL but adding /so to it worked fine.  Are there any other URLs that need to be adjusted, ie the ones that DavDroid or other DAV clients sync with?  Are there any other issues that relate to this?

**Comment by andryyy** [comment]
You need more workers, that will fix it. Just add some to data/conf/sogo/sogo.conf in "SOGOWorkersCount" (or smiliar). 👍

**Comment by bretsky84** [comment]
can you let me know how to do that?

**Comment by bretsky84** [comment]
I only see "WOWorkersCount" is this the same thing?  Went from 7 to 30.  Revert to default  site.conf?

**Comment by andryyy** [comment]
Yes, revert and run docker-compose restart sogo-mailcow

**Comment by bretsky84** [comment]
Reverted, rebooted, success.  You are tagged as an owner, are you affiliated with the mailcow project?

**Comment by andryyy** [comment]
Yes, I am. :-)

**Comment by bretsky84** [comment]
Donation on the way.  Thank you so much for your hard work.  I have tried to get paid support or hosting but you guys don't email me back.  I think part of it is I only speak English.
-40 euros in your bank

**Comment by andryyy** [comment]
Hmm, that's weird. I am sorry I missed that, let me know whenever you need help. Please add andre.peters@debinux.de to CC. :-)

Thanks for your donation!

**Comment by extremeshok** [comment]
+1 for **separate sogo container for ActiveSync**

**Comment by lavdnone** [comment]
So are we going SOGo recommended way with separate ActiveSync or we giving up SOGo?

**Comment by andryyy** [comment]
What? We drop it because you don't like the current implementation? Just give it more workers. If you have a _huge_ setup, then you can think about starting a second instance for EAS. There is no recommendation to use a second SOGo instance anyway. It is a document about adding a dedicated SOGo pool when you hit that "limitation". You can also just use more workers. When the EAS instance hits the pool limit, you will run into EAS sync problems. This is a good workaround for some problems, but not _the_ solution.

**Comment by lavdnone** [comment]
The only problem with current is that SOGo recommends separate EAS for ActiveSync and for the good reason. Timeouts and other settings look completely different from webmail and will potentially Lower the load if separated. At minimum by not having webmail workers share 60 minute timeouts of ActiveSync will free them up. One don't have to have huge setup to long for optimization.

I think I've mentioned this earlier, that having we use docker it is not like we start a second server! same core, just separate php-fpm worker set for the purpose, with proper timeouts and tuneup.

**Comment by andryyy** [comment]
Where does it recommend that?

Running out of workers will still happen, webmail users just don't feel it. Say hello to "broken" EAS caches then.

There is a watchdog in SOGo to kill hanging workers, they will not all hang for 60 minutes, that's just not true.

PHP-FPM does not have _anything_ to do with EAS and SOGo...

**Comment by lavdnone** [comment]
I took info from here https://sogo.nu/support/faq/dedicated-separate-sogo-instance-for-activesync.html
"As you many know, ActiveSync clients tend to aggressively hold on to their connections; that behavior may starve web interface clients. Setting up a second instance ensures web interface clients get their fair share of connections."

Forgot that it is c on deb, non php
Maybe another deb container is too much indeed
