### ISSUE TITLE
Advice requested: Experience with removing deuplicate files in vmail folder and replace with hardlinks?

### ISSUE THREAD

**Issue by Lucky88888** [mailcow/mailcow-dockerized#977]
Hi,

Case:
I am migrating from Google apps to Mailcow. Google's IMAP folder structure creates a lot of duplicate messages when I am importing them with IMAP Sync.  

Question:
Is it advisable to run the following command?
`# rdfind -makehardlinks true -n false /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data`

Should I use hardlinks or symlinks? 

More info on rdfind: https://rdfind.pauldreik.se/

**Comment by MAGICCC** [comment]
Never tried the IMAP Sync, but why would it duplicate messages...

Anyway I wouldn't use any links, since they still refer to the vmail folder. Try something like `rdfind -n -makeresultsfile true`
It should output a textfile containing all duplicate files and since it's a dryrun it doesn't delete anything. Plus when it's successful you can do something like `rsync --remove-source-files --files-from foo.txt bar` to move the files to some backup folder

**Comment by Lucky88888** [comment]
Well I want to keep the files on their locations, so my intention is not starting deleting them. So I think I will end up using the links.

**Comment by hachre** [comment]
There's an extension for Thunderbird, which I use to handle duplicates after such an import. The name is "Remove Duplicate Messages (Alternate)". It works best when you allow Thunderbird to create a local copy of all mails. This is the default behavior when adding a new mail account to Thunderbird. Once that is done, you can run the addon by right-clicking the root of the UI tree on the left side and choosing "Remove Duplicates". It is able to find duplicates within 200,000 mails within seconds and will proceed to delete them both locally and on the server. You also have some choice over which of the duplicated mails you want to keep (based on what folder it is in).

**Comment by Braintelligence** [comment]
@MAGICCC I think GoogleMail has a folder "All messages" or something the like, which keeps copies of mails in all other folders.
Maybe that's the problem of @Lucky88888.

**Comment by andryyy** [comment]
You can now use "Skip duplicate messages across folders (first come, first serve)".
You should also write "All messages" in the exclude field.
