### ISSUE TITLE
SOGo login problems

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#979]
When logging in as user B I see SOGo saying "welcome user A" and then just going back to login prompt.

SOGo log says something like: [37]: <0x0x56414e21ca70[SOGoWebAuthenticator]> tried wrong password for user 

If I restart docker-compose login works once with the same credentials and then doesn't work again after a short while.

Login works normally for some specific users, though.

Any idea what's going on?

**Comment by Braintelligence** [comment]
The username in these errors also looks very weird. The username looks like a huge string of letters and numbers and is not equal to the mail address.

I now tested all users on that server and only about half of them can be logged in. All other users deliver this error.

Caldav Synchronization via Caldav Synchronizer for Outlook also has problems

**Comment by Braintelligence** [comment]
I tried "test or discover settings" in caldav synchronizer for user B now.
What I was shown for Personal calendar was the personal calendar of user A though (visible in the dav url).

This seems to have happened on last mailcow update but not for all users.

**Comment by andryyy** [comment]
It will never be able to login as this user or show any private data except for the pathes. I fixed it.

Problem: I allowed real mailboxes to be aliases in the sogo SQL view. SOGo does not like that. You'd need to delegate mailbox A to mailbox B inside SOGo.

**Comment by Braintelligence** [comment]
So I can update and it will work again? Will try later today.

**Comment by andryyy** [comment]
Yes.
