### ISSUE TITLE
latest update nginx not starting

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#980]
Hi there, ran update.sh today and after that nginx container is not starting anymore:

ea37e83e2e6d        nginx:mainline-alpine     "/bin/sh -c 'envsubs…"   58 seconds ago       Restarting (1) 23 seconds ago                                                                                                                                                mailcowdockerized_nginx-mailcow_1

Watchdog: nginx-mailcow service hit the error rate limit

What should i do? thanks

**Comment by andryyy** [comment]
Check the logs and remove a duplicate server block for https redirection

**Comment by lucianlazar1983** [comment]
Thank you, there was indeed a duplicate server redirect block inside conf.
Have a nice one!
