### ISSUE TITLE
Forwarding Hosts deferred

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#982]
HI, 

i added a web-servers hostname as "Forwarding Hosts".
In the description this is written:

> Incoming messages are unconditionally accepted from any hosts listed here

If i send a mail from my web-server with from   

> no-reply@mydomain.de

and no-reply is not a alias or mailbox, it fails with:

> Recipient address rejected: User unknown in virtual mailbox table

If i send a mail from my mailserver with is not configured in mailcow, it blocks with:

> Relay access denied

although it is whitelisted:

> WHITELISTED [1.1.1.1]:51926
>30.1.2018, 16:39:35 | info | Look up 1.1.1.1 on whitelist, result 200 PERMIT

How i could fix this?

Thanks, 
Thomas

**Comment by mkuron** [comment]
If mydomain.com is set up as a domain on your Mailcow, you also need to add the web server to `mynetworks` in data/conf/postfix/main.cf. Forwardinh hosts alone is not intended for this application.

**Comment by develth** [comment]
Thanks,

then the word "unconditionally" should be removed from the description :)

**Comment by mkuron** [comment]
You are using an invalid sender address and trying to use Postfix for relay access. That former is only allowed for `mynetworks` and the latter only for authenticated users. You can submit a pull request to clarify the help text if you like.

**Comment by develth** [comment]
Will do, because when a mail is denied of this, there is a condition.

Thanks for the explanation

**Comment by mkuron** [comment]
Well, mail is also denied if the HELO is invalid or the message is syntactically wrong. So the unconditionally refers to all spam filtering capabilities (rspamd and postscreen) and not to Postfix itself.

**Comment by develth** [comment]
Yes, but not in combination of "Forwarding Hosts".
Thought this settings in the Interface are also integrated in 

    smtpd_relay_restrictions

**Comment by andryyy** [comment]
Hm, what about adding it to check_client_access?
