### ISSUE TITLE
Send E-Mails from Command Line (Systemmail)

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#986]
I have a vServer only with Mailcow Dockerized. It work great.

But Mails from command Line (crontab error, system messages for updates with apticron) don't come in my mailbox.

Do I have to install a separat MTA (postfix) for this, or what I have forgot for settings?

Thank you for help and sorry for my bad english

**Comment by andryyy** [comment]
Hi, 

You can either follow https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/ or install "s-nail". Using "s-nail", you need to add `set smtp=smtp://127.0.0.1:25` to `/etc/s-nail.rc`.

**Comment by ghost** [comment]
Ah ok. Thank you. So I install postfix as send only. I had think I don't need it with mailcow.
So I can install postfix as Satelite System an change the port and the hostname?

**Comment by andryyy** [comment]
Just install as normal Internet system and apply the changes from the docs.

**Comment by ghost** [comment]
> Just install as normal Internet system and apply the changes from the docs.

Thank you. I have only one problem:
I don't have this line in my main.cf to disable
smtp      inet  n       -       -       -       -       smtpd
And so I have in mail.err log
postfix/master[5751]: fatal: bind 127.0.0.1 port 25: Address already in use

I use Debian Stretch. I found a old entry with this one:
master_service_disable = inet
With this line it works. Is this correct with this entry?
When its ok, its an idea to additional this info in https://mailcow.github.io/mailcow-dockerized-docs/firststeps-local_mta/

**Comment by andryyy** [comment]
Master.cf

**Comment by ghost** [comment]
ok. sorry. I don't have see the different master and main :). Now all works fine.
