### ISSUE TITLE
Mailbox Spam Filter and Temporary Aliases not available.

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#989]
Hello,
I've installed the latest version of mailcow-dockerized, followed the documentation.

However I can't find where the per-mailbox spam filter slider and the temporary mail aliases are.
I also believe there are other settings missing on my mailcow UI.

Am I missing something?

Thank you very much.

**Comment by cklabautermann** [comment]
Good morning,

just scroll down in mailcow UI Configuration -> user settings. There you should see 3 indexes called 

- Temporary email aliases
- Spam Filter
- Sync Jobs

You should find per mailbox Spam settings in the "Spam Filter" index.

BR
Claudio

**Comment by apintocr** [comment]
I've searched there but I still do not see the options.
I'm pretty sure they are not on the UI...

**Comment by SamuelNitsche** [comment]
Are you logged in as user or admin? I think you have to log in as user to see those settings.

**Comment by apintocr** [comment]
I tried with both a user and as admin.
As a user on the "User Settings" I only have password change and 2FA.

**Comment by SamuelNitsche** [comment]
Hm, that's strange. I have updated my installation and I cannot confirm your issues. At the bottom of the user.php site, I can adjust all those settings. Can you maybe post a screenshot of your site?

**Comment by apintocr** [comment]
Here
![image](https://user-images.githubusercontent.com/1459530/35726878-4c47b2ce-07fe-11e8-9aea-dc56aed4c0ba.png)

![image](https://user-images.githubusercontent.com/1459530/35726881-501b10da-07fe-11e8-8e4a-23b10fd01bc8.png)

**Comment by andryyy** [comment]
That's a domain admin, not a user.

**Comment by apintocr** [comment]
Oh... I see what you mean now!

**Comment by apintocr** [comment]
Thank you very much @andryyy 
I did not noticed I could login as a email user...

Closing this :)
