### ISSUE TITLE
ClamAV false positive

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#990]
Hello,

Las night I updated mailcow to master.
There is one Excel document template with macros that is being sent regularly from mailcow to external mailboxes that is now being flagged as a virus by rspamd. Before today the messages were allowed so I guess it is the update with the new ClamAV.
I checked at virustotal and the file comes all clean (even in ClamAV). Is there a way to add an exception to ClamAV for that file?
Here is what rspamd says:

VIRUS_FOUND(2000)
MAILCOW_AUTH(-20)
SUBJ_ALL_CAPS(2.475)[33]
MIME_GOOD(-0.1)[multipart/mixed,multipart/related,multipart/alternative,text/plain]
DYN_RL_CHECK(0)
ARC_NA(0)
FROM_EQ_ENVFROM(0)
TO_DN_NONE(0)
RCVD_TLS_ALL(0)
RCVD_COUNT_ZERO(0)[0]
FROM_HAS_DN(0)
RCPT_COUNT_ONE(0)[1]
TO_MATCH_ENVRCPT_ALL(0)
HAS_ATTACHMENT(0)
MID_RHS_MATCH_FROM(0)

Thank you

**Comment by andryyy** [comment]
You can either whitelist the sender or set ScanOLE2 no and/or OLE2BlockMacros no in `data/conf/clamav/clamd.conf`

Run `docker-compose restart clamd-mailcow` after changing these files.

**Comment by catcun** [comment]
@andryyy Thank you. I need to assess those solutions as all of them will reduce the security; whitelist the sender seems to be not that bad

**Comment by catcun** [comment]
Follow up

To add an exception: https://www.clamav.net/documents/how-do-i-ignore-whitelist-a-clamav-signature

Of course that does not solve my problem. 
After setting **OLE2BlockMacros no** to allow Office files with macros I had problems with some PDF files. 
Again, virustotal said they were clean but there was something interesting on the file details for all blocked PDFs: Being PDFs generated by filling forms all had javascript block(s). So I had to disable PUA detection using **DetectPUA no**

I feel insecure, but that's the way it is; the domain handles lots of documents with Macros and PDF forms. The rest is left for the workstation antivirus.

**Comment by Braintelligence** [comment]
@catcun Just wanted to thank you very much for the follow up. You helped me solve my problem 😁. Kudos to you not leaving us alone without your solution.

**Comment by Braintelligence** [comment]
Weird, since updating to the newest mailcow the attachment went through without changing any other configuration.
@andryyy Did you change something about how ClamAV reacts to macros?

**Comment by andryyy** [comment]
Nope, but it's possible they changed some macro detection internally.
