### ISSUE TITLE
Mailcow dockerized with custom docker webserver

### ISSUE THREAD

**Issue by garybsimon** [mailcow/mailcow-dockerized#992]
Hi there.

I want to ask one thing. Is there any way to add a custom docker container to the mailcow dockerized server which can host a website with another domain name?

Like: mailcow is on mail.mailsever.com
Website: WordPress container www.website.com

I think it's possible with portainer, but need to check before I make decisions.
Please let me know.

Thanks.

**Comment by andryyy** [comment]
Hi, you can just add a new site like "nano data/conf/nginx/mysite.conf"

**Comment by garybsimon** [comment]
Hi andryyy,
So when I good understand.
I can add a new container via portainer and select network bridge (mailcow).
What about the ports? 
I need to add the server code to nginx then it will create the reverse proxy for the new container? Right?

**Comment by andryyy** [comment]
You don't create a new container. You'd just use mailcows Nginx as is. :-)

**Comment by garybsimon** [comment]
Hi @andryyy.
Sorry for the blame, but I can't figure out, how to add my custom docker conatiner near mailcow.
I have created a new container and don't want to use mailcow nginx.
I want to create a separate conatiner with a Joomla in it, then I need to point my DNS to this container. 
The problem is, I cannot reach my container from outside.
The main question is, is it possible to use another conatiners with own domain name near mailcow suite?

Please give me some short tutorial whats the main points that I need to setup.
Thank you.
(sorry I'm newbie with docker stuff, mailcow is ok for me, but this make me angry) 

Best regards.
Gary

**Comment by andryyy** [comment]
You probably want to have your new container in the same Docker network as mailcow. You can change the compose file or extend it with another yml file.

**Comment by garybsimon** [comment]
So you mean like the portainer container but with custom domain name and settings not only like "/portainer".
Ok, I'll give a try. Thank you.

**Comment by thomas126** [comment]
And how can I get Wordpress running from docker auswellt using Mailcows database system and Nginx?
