### ISSUE TITLE
Using BCC Maps on multiple addresses returns "is not a valid RFC-5321 address" error

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized#993]
If I setup a BCC map to multiple address, like bellow:
![image](https://user-images.githubusercontent.com/1459530/35733056-bcd99484-0813-11e8-8a97-aca19a4e913b.png)
Gmail returns the following:
````
3B0A928B5D: to=<email1@gmail.com,email2@gmail.com>,
relay=gmail-smtp-in.l.google.com[74.125.133.27]:25, delay=0.82,
delays=0.25/0.09/0.45/0.03, dsn=5.1.2, status=bounced
(host gmail-smtp-in.l.google.com[74.125.133.27] said:
553-5.1.2 The recipient address <email1@gmail.com,email2@gmail.com>
is not 553 5.1.2 a valid RFC-5321 address. 199si1114255wmj.52 - gsmtp
(in reply to RCPT TO command))
````

The same happens if I use mailcow domains:
````
76CA828BB6: to=<apinto@mydomain.com,atomas@mydomain.com>,
relay=dovecot[172.22.1.8]:24, delay=0.37, delays=0.3/0.01/0/0.05, dsn=5.1.1,
status=bounced (host dovecot[172.22.1.8] said: 550 5.1.1 <"apinto@vanguardly.com,atomas"@vanguardly.com>
User doesn't exist: "apinto@mydomain.com,email2"@mydomain.com 
(in reply to RCPT TO command))
````

Please not the **"** before the **@** is __NOT__ a error. That is exactly how the log shows it.

**Comment by andryyy** [comment]
Sorry, I "fixed". Destination cannot be multiple addresses.

**Comment by apintocr** [comment]
@andryyy , is this a _hard_ limit? or can this be properly fixed?
I haven't yet dived into the mailcow code, however I can take this issue and try to make a proper fix.
I'd just like you to point me the right direction and I'll manage ;)

**Comment by andryyy** [comment]
It just isn't possible to return more than one.

**Comment by apintocr** [comment]
I see @andryyy , using bcc_recipient_maps is not possible for multiple addresses.

I've been reading a bit and found the following resources that I'll leave here for future reference:

- [stackoverflow - postfix recipient_bcc_maps multiple recipients how to?
](https://stackoverflow.com/questions/22537523/postfix-recipient-bcc-maps-multiple-recipients-how-to)
- [postfix.org - Postfix Address Rewriting](http://www.postfix.org/ADDRESS_REWRITING_README.html)
- [nabble.com - "always_bcc" for multiple recipients (via alias) and "recipient_bcc_maps" don't work](http://postfix.1071664.n5.nabble.com/quot-always-bcc-quot-for-multiple-recipients-via-alias-and-quot-recipient-bcc-maps-quot-don-t-work-td86962.html)

I've also found a "solution" - workaround - as bcc_maps expand regular aliases, you can just create a dummy alias to serve as the domain map. See below:

1. Create a Alias and forward it to the recipients you want, for example: Alias: bcc.name.4rdf5@example.com To: email1@example.com,email2@example.com,email3@gmail.com
2. Create a BCC Map to the previously created alias.

Notes:

- BCC Maps *DO* expand Aliases.
- Aliases *DO NOT* expand other aliases.
- I've added a random string (4rdf5) to make the alias more random, avoiding collision with future aliases - just a good practice, not required.

With this in mind we could tweak the current Mailcow BCC Maps system to effectively use BCC Maps to Multiple destinations by creating an association between the BCC Maps and the Aliases (hiding the dummy aliases from the UI for example).

Hope this helps :)
