### ISSUE TITLE
DNS Check, TLSA=0 or 111: Connection refused

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#997]
I have two problems, but I think its the same issue.

I have installed two mailcow server on two separate VM. The first, I have two weeks before all options in dns green checked. Today, I have retest and had 3 options with 111: Connection refused
_25._tcp.mx001.domain1.tld
_465._tcp.mx001.domain1.tld
_587._tcp.mx001.domain1.tld
But I don't know whats the problem.

Today, I have installed for a friend a other vm with Mailcow. All works fine. But the same three options have error
_465._tcp.mail01.domain2.tld as Value I see 0:
_993._tcp.mail01.domain2.tld as Value I see 0:
_995._tcp.mail01.domain2.tld as Value I see 0:

What can I do?
Thank you for all help

**Comment by andryyy** [comment]
Would need access to check this, the TLSA generator is still kind of buggy..

**Comment by andryyy** [comment]
Btw. "connection refused" happened due to your non-working Postfix...

Make sure mailcow is running properly on the second host and check logs if it does not.

**Comment by ghost** [comment]
` I have retest and had 3 options with 111: Connection refused
_25._tcp.mx001.domain1.tld
_465._tcp.mx001.domain1.tld
_587._tcp.mx001.domain1.tld`

This one is solved with this: https://github.com/mailcow/mailcow-dockerized/issues/998

for this one:

> _465._tcp.mail01.domain2.tld as Value I see 0:
_993._tcp.mail01.domain2.tld as Value I see 0:
_995._tcp.mail01.domain2.tld as Value I see 0:

I have only insert the value from _443._tcp.mail01.domain2.tld. It works. I hope its ok. Givs a way to check if the dns entrys are ok?

**Comment by andryyy** [comment]
I still need access or a hostname. You can mail me the hostname to info@servercow.de

The DNS check does exactly that: Tell you if your records are fine. TLSA is not obligatory.

**Comment by ghost** [comment]
Thank you for help. I have send you a mail

**Comment by andryyy** [comment]
The "fix" is to not verify peer names. It now shows correct values. But... you are using the self-signed default certificate for IMAP, SMTP etc. You need to copy the certificates to data/assets/ssl and restart affected containers. That's in the docs. :-) Since you are using a reverse proxy, you may want to request all needed names there and run a post-hook in your LE client to copy files, restart services etc.

@mkuron We should add a validation check for peer names to debugging, what do you think?

**Comment by ghost** [comment]
@andryyy thank you for help.

Was the only problem that mailcow don't generate autodiscover.mymaildomain.com ssl certificate because I run a nginx proxy?
Can you say me what do you have changed? On this mailserver ios find all options when i take exchange. On the second mailserver he don't find it automaticle

Now to generate the SSL Certificate:
For a test i had insert the domain in ADDITIONAL_SAN. When i restart the acme-mailcow and see the log I get this error:
`acme-client: transfer buffer: [{ "type": "http-01", "status": "invalid", "error": { "type": "urn:acme:error:unauthorized", "detail": "Invalid response from http://mailcowdomain.tld/.well-known/acme-challenge/96R2_3bg0pL8JcF5Yf8xpwWRGcKHFrqEjWilMr8nbZk: \"\u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003e\"", "status": 403 }, "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/X35fIlDNwP_fqvSORIqumRRUoqZWLzGRuK2WlNW-TaU/3340064449", "token": "96R2_3bg0pL8JcF5Yf8xpwWRGcKHFrqEjWilMr8nbZk", "keyAuthorization": "96R2_3bg0pL8JcF5Yf8xpwWRGcKHFrqEjWilMr8nbZk.8Y3k8d3uCdoHDo3O6pDAFA7v_Hill9S-RfT8W_Ti1_w", "validationRecord": [ { "url": "https://mailcowdomain.tld/.well-known/acme-challenge/96R2_3bg0pL8JcF5Yf8xpwWRGcKHFrqEjWilMr8nbZk", "hostname": "mailcowdomain.tld", "port": "443", "addressesResolved": [ "ipv4address", "ipv6address" ], "addressUsed": "ipv4address" }, { "url": "http:// mailcowdomain.tld /.well-known/acme-challenge/96R2_3bg0pL8JcF5Yf8xpwWRGcKHFrqEjWilMr8nbZk", "hostname": "mailcowdomain.tld", "port": "80", "addressesResolved": [ "ipv4address", "ipv6address" ], "addressUsed": "ipv6address" } ] }] (1465 bytes)`
How can I fix it? Or is the only way to generate a certificate with certbot?

Other question:
You write I can generate own and insert it to data/assets/ssl/. When I have 4 maildomains, i must generate 4 certificates for autodiscover and autoconfig. But I can not rename all to cert.pem. How can i insert more than one certificate in the folder?
And givs a way to use certbot autorenew and a symlink or so to the folder data/assets/ssl

**Comment by andryyy** [comment]
It depends on your reverse proxy wether or not you can request certs with acme-mailcow. You will need to request the certs by yourself (that's what you are doing right now) or pass all ACME requests to mailcow.

The IPv6 address for your AAAA record was broken, you will need to check this.

The only thing I changed was a "fix" for creating TLSA records. You use the snake-oil certs for mail.example.org in mailcow, the TLSA generator refused to connect untrusted, so it failed.

You don't need more than one cert for all names. You can extend LE certs with additional names.
Certbot has post-hooks, you can use a script as post-hook to restart Nginx, Dovecot and Postfix.

**Comment by ghost** [comment]
OK. Now all is clear. Thank you. Only two more things for this theme:
1. How can I check self if the ipv6 is broken? I would learn how can I see it to mail it to the hoster if there is a problem.
maildomain.tld has the mx to mail.mailcowdomain.tld, autodiscover and autoconfig.maildomain.tld has the cname to mail.mailcowdomain.tld and mail.mailcowdomain.tld has the a and aaaa record to the mailcowdomain.tld server. ping6 to google works. SO i think ipv6 work.

2. I have installed a new testserver. All works without problem. But I have the same issue like yesterday. I create the account and say exchange. On the server you have make changes, ios find all settings. on the new testone ios don't find the settings. The certs looks like ok, and i don't have used a nginx proxy.
Cert log:
`acme-mailcow_1       | Sun Feb  4 08:58:25 UTC 2018 - Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: autoconfig.maildomain.tld autodiscover.maildomain.tld mail.maildomain.tld
acme-mailcow_1       | mysqld is alive
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Waiting for domain table... Found domain tables.
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Found A record for autoconfig.maildomain.tld: myIpv4Address
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Confirmed A record autoconfig.maildomain.tld
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Found A record for autodiscover.maildomain.tld: myIpv4Address
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Confirmed A record autodiscover.maildomain.tld
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Found A record for mail.maildomain.tld: myIpv4Address
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Confirmed A record mail.maildomain.tld
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/account.key: account key exists (not creating)
acme-mailcow_1       | acme-client: /var/lib/acme/acme/private/privkey.pem: domain key exists (not creating)
acme-mailcow_1       | acme-client: adding SAN: autoconfig.maildomain.tld
acme-mailcow_1       | acme-client: adding SAN: autodiscover.maildomain.tld
acme-mailcow_1       | acme-client: /var/lib/acme/acme/cert.pem: certificate valid: 89 days left
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Verified hashes.
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - Certificate was not changed
acme-mailcow_1       | Sun Feb  4 08:58:27 UTC 2018 - ACME certificate validation done. Sleeping for another day.`

I hope this is my last problem. Thank you so much for help

Edit: Do you have a donate program for mialcow and help?
