### ISSUE TITLE
no listen to port 25?

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#998]
I don't think this problem https://github.com/mailcow/mailcow-dockerized/issues/997 is the same, because the second server work the telnet on port 25.

 A few days all works fine. Now mxtoolbox say smtp Failed To Connect 

a telnet localhost 25 from mailserver givs this:
telnet localhost 25
Trying ::1...
Connected to localhost.
Escape character is '^]'.
220 mx.mydomain.tld ESMTP Postfix

A telnet to ipv4 or ipv6 from the mailserver I get this:
Trying X.X.X.X...
telnet: Unable to connect to remote host: Connection refused

Where I can find a solution? I think internet connection is ok
ping google.de
PING google.de(fra16s07-in-x03.1e100.net (2a00:1450:4001:816::2003)) 56 data bytes
64 bytes from fra16s07-in-x03.1e100.net (2a00:1450:4001:816::2003): icmp_seq=1 ttl=59 time=3.66 ms
64 bytes from fra16s07-in-x03.1e100.net (2a00:1450:4001:816::2003): icmp_seq=2 ttl=59 time=3.73 ms
64 bytes from fra16s07-in-x03.1e100.net (2a00:1450:4001:816::2003): icmp_seq=3 ttl=59 time=3.81 ms
64 bytes from fra16s07-in-x03.1e100.net (2a00:1450:4001:816::2003): icmp_seq=4 ttl=59 time=3.74 ms

**Comment by D3luxee** [comment]
Your checks are running on localhost, mxtoolbox is external, maybe some firewalling or something between?

Maybe you could tell us your domain name so we can check the records and all the stuff.

With the informations you stated above its not possible to resolve this issue.

**Comment by ghost** [comment]
> Your checks are running on localhost, mxtoolbox is external, maybe some firewalling or something `between?`

I have checked not localhost on mxtoolbox. I have checked on mailserver telnet localhost 25 and it works, telnet publicIPv4 25 don't work.
I don't have make any change, but my last incoming mail was 8 hour before.

**Comment by D3luxee** [comment]
If telnet to your public ip does not work its related to your network settings and not to mailcow itself.

Check if the container bound its socket, check your firewall and routing configuration.

**Comment by ghost** [comment]
I think its iptables. But I don't have make changes. How can I fix it?
iptables -L -n
Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:12345
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:4190
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:995
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:993
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:143
ACCEPT     tcp  --  0.0.0.0/0            172.22.1.7           tcp dpt:110

On the second server I see more docker port (25 and so), but I don't know what is the problem

**Comment by ghost** [comment]
ok. port 25 is solved. apticron has installed exim4 and this was the problem. now i search the problem for web. i get 404 :)

**Comment by andryyy** [comment]
Docker-compose tells you what's blocked when you run "up -d". Check "netstat -tulpen" or "ss -tlpn"

**Comment by ghost** [comment]
docker-compose up -d
mailcowdockerized_mysql-mailcow_1 is up-to-date
mailcowdockerized_dockerapi-mailcow_1 is up-to-date
mailcowdockerized_dovecot-mailcow_1 is up-to-date
mailcowdockerized_ipv6nat_1 is up-to-date
mailcowdockerized_memcached-mailcow_1 is up-to-date
mailcowdockerized_watchdog-mailcow_1 is up-to-date
mailcowdockerized_postfix-mailcow_1 is up-to-date
mailcowdockerized_unbound-mailcow_1 is up-to-date
mailcowdockerized_redis-mailcow_1 is up-to-date
mailcowdockerized_clamd-mailcow_1 is up-to-date
mailcowdockerized_sogo-mailcow_1 is up-to-date
mailcowdockerized_php-fpm-mailcow_1 is up-to-date
mailcowdockerized_fail2ban-mailcow_1 is up-to-date
mailcowdockerized_nginx-mailcow_1 is up-to-date
mailcowdockerized_rspamd-mailcow_1 is up-to-date
mailcowdockerized_acme-mailcow_1 is up-to-date

netstat -tulpen
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name
tcp        0      0 127.0.0.1:19991         0.0.0.0:*               LISTEN      0          107174     23633/docker-proxy
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      0          12109      847/unbound
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      1000       30690      5252/sshd: donut@pt
tcp        0      0 0.0.0.0:38412           0.0.0.0:*               LISTEN      0          12474      836/sshd
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      0          12107      847/unbound
tcp6       0      0 :::25                   :::*                    LISTEN      0          106160     23496/docker-proxy
tcp6       0      0 ::1:8953                :::*                    LISTEN      0          12108      847/unbound
tcp6       0      0 ::1:6010                :::*                    LISTEN      1000       30689      5252/sshd: donut@pt
tcp6       0      0 :::4190                 :::*                    LISTEN      0          107617     23702/docker-proxy
tcp6       0      0 :::993                  :::*                    LISTEN      0          110708     24277/docker-proxy
tcp6       0      0 :::995                  :::*                    LISTEN      0          107910     23799/docker-proxy
tcp6       0      0 :::587                  :::*                    LISTEN      0          105957     23419/docker-proxy
tcp6       0      0 :::38412                :::*                    LISTEN      0          12476      836/sshd
tcp6       0      0 :::110                  :::*                    LISTEN      0          110805     24310/docker-proxy
tcp6       0      0 :::143                  :::*                    LISTEN      0          110764     24287/docker-proxy
tcp6       0      0 :::465                  :::*                    LISTEN      0          106125     23473/docker-proxy
tcp6       0      0 ::1:53                  :::*                    LISTEN      0          12105      847/unbound
udp        0      0 127.0.0.1:53            0.0.0.0:*                           0          12106      847/unbound
udp6       0      0 ::1:53                  :::*                                0          12104      847/unbound

**Comment by andryyy** [comment]
Logs? `docker-compose logs nginx-mailcow`

**Comment by ghost** [comment]
nginx-mailcow_1      | 2018/02/02 21:30:46 [emerg] 8#8: a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/02 21:31:47 [emerg] 9#9: a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/02 21:32:47 [emerg] 8#8: a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed
nginx-mailcow_1      | 2018/02/02 21:33:47 [emerg] 8#8: a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/site.conf:18
nginx-mailcow_1      | nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by andryyy** [comment]
Remove the duplicate block in data/conf/nginx/site.conf and run docker-compose restart nginx-mailcow

**Comment by andryyy** [comment]
Or... run git checkout origin/master data/conf/nginx/site.conf and restart nginx-mailcow. :-)

**Comment by ghost** [comment]
great. thank you. Have you an idea for this? https://github.com/mailcow/mailcow-dockerized/issues/997
the first problem is solved with this fix here.

But on the second server not. On the second server it run nginx as proxy, but all work. Only this thre dns entrys with 0:
