### ISSUE TITLE
Corrupt Filesystem

### ISSUE THREAD

**Issue by NicoDreamzZ** [mailcow/mailcow-dockerized#999]
Hey there,
my filesystem is completely trash. Now I need the location where the mails are located. I cannot start mailcow anymore. I need to get to the mails cause my mirror also failed.
Thanks for any help!

Greetings

**Comment by andryyy** [comment]
Hi, backup /var/lib/docker/volumes :-)

**Comment by NicoDreamzZ** [comment]
Thanks, you saved my life! :*

**Comment by NicoDreamzZ** [comment]
Last question: I have no knowledge in docker, how do i get the mails out of the volumes?

**Comment by andryyy** [comment]
You can just copy the directory to your new mailcow, but preserve the rights and file modes! Use rsync or at least "cp -rp".

If you just need the files, you don't have to do anything besides entering that directory.
